### ISSUE TITLE
Enhancement: JSON Validator

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#10008]
I'd like to know if a JSON validator would be important for other fellow developers especially that it is becoming natively supported by databases like PostgreSQL and MySQL, and whether it would be accepted as a core Yii validator by the core team. A typical application is submitting raw JSON content via a form.

**Comment by fernandezekiel** [comment]
does this mean that you are assigning the JSON into a particular attribute of a model?
or are you just using content-type json.
If it's the latter then there is no new feature needed

**Comment by YasserHassan** [comment]
It is for model attributes that correspond to JSON database columns. The JSON attribute could be filled by raw JSON content filled manually in a `textarea` or from a front-end JSON editor such as [josdejong/jsoneditor](https://github.com/josdejong/jsoneditor/). The minimum validation is proper JSON format but it could go higher to validating conformity to a schema.

In that case, introducing a new JSON data type to `yii\db\Schema` would be a good idea.

**Comment by fernandezekiel** [comment]
i think it's rather a rare case that we would be taking JSON as a direct input in a text area,
this implementation however is the more useful one in my opinion
https://github.com/tom--/yii2-dynamic-ar
this will map the json attributes of a column into actual propeties

**Comment by YasserHassan** [comment]
Thank you for the tip @fernandezekiel. It's a different case where JSON data is populated to the model itself but it's worth checking.
