### ISSUE TITLE
Ошибка в генерации запроса при использовании offset() и one()

### ISSUE THREAD

**Issue by shastox** [yiisoft/yii2#10004]
Задача: получить одну модель с оффсетом в 10.
Код:
`$model = Photo::find()->offset(10)->one();`
возвращает одну модель, но генерируется неправильный SQL:
`SELECT * FROM `photo` LIMIT 10`

Правильный SQL должен быть:
`SELECT * FROM `photo` LIMIT 1 OFFSET 10`

Исправление ошибки: 
`$model = Photo::find()->offset(10)->limit(1)->one();`

**Comment by samdark** [comment]
`one()` не добавляет LIMIT 1 автоматически. Так было задумано изначально.

**Comment by shastox** [comment]
Проблема не том, что `one()` не добавляет `LIMIT 1`, а в том, что метод `->offset(10)` приводит именно к части sql `LIMIT 10`.

Неужели вы считаете такое поведение нормальным / правильным / ожидаемым?

**Comment by samdark** [comment]
Какая база?

**Comment by shastox** [comment]
MySQL.

**Comment by samdark** [comment]
Can't reproduce:

![qip shot - screen 349](https://cloud.githubusercontent.com/assets/47294/10863427/461f9c9a-7fde-11e5-9a77-4ebb622bbb16.png)
![qip shot - screen 350](https://cloud.githubusercontent.com/assets/47294/10863428/47332462-7fde-11e5-9540-f248c6852d4d.png)

**Comment by shastox** [comment]
Как это не воспроизводится? :) На вашем же скрине видно, что есть баг, что `offset(10)` в вашем коде генерирует `LIMIT 10` на вашем же скрине. 

`offset(10)` - дает смещение.
`LIMIT 10` - извлекает 10 записей.

`User::find()->offset(10)->one()` -  хочу извлечь из базы пользователя, т.е. одну строку, а Yii извлекает 10 строк. Yii должен генерировать

`SELECT * FROM user OFFSET 10`

Да, результат будет одинаковым, потому что из 10 записей от MySQL PHP выбирает одну. Но если поставить 10 000, то MySQL извлечет 10 000 строк, а все потому, что код 

`User::find()->offset(10)->one()` генерирует не `смещение`, а `LIMIT`, т.е. количество записей

Надеюсь, все объяснил.

**Comment by samdark** [comment]
Не не не. На моём скрине `LIMIT 10, 18446744073709551615`, а не просто `LIMIT 10`.

**Comment by samdark** [comment]
Если LIMIT передаются два значения, то первое — offset, второе — limit.

**Comment by shastox** [comment]
Согласен, не досмотрел. Но все равно через Ж получается с этим one(), который не добавляет лимит 1, но раз вы сказали, что так задумывалось, тогда вопросов нет. Спасибо.
