### ISSUE TITLE
RBAC DbManager

### ISSUE THREAD

**Issue by Svyatoslav-S** [yiisoft/yii2#10006]
DbManager.php line 749 Should be removed or commented

    public function assign($role, $userId)
    {
        $assignment = new Assignment([
            'userId' => $userId,
            'roleName' => $role->name,

            'createdAt' => time(), // !!! Should be commented or elliminated

        ]);

        $this->db->createCommand()
            ->insert($this->assignmentTable, [
                'user_id' => $assignment->userId,
                'item_name' => $assignment->roleName,
              //  'created_at' => $assignment->createdAt,
            ])->execute();

        return $assignment;
    }

**Comment by samdark** [comment]
Why?

**Comment by Svyatoslav-S** [comment]
Assignment.php

<?php
/**
  * @link http://www.yiiframework.com/
  * @copyright Copyright (c) 2008 Yii Software LLC
  * @license http://www.yiiframework.com/license/
  */

namespace yii\rbac;

use Yii;
use yii\base\Object;

/**
  * Assignment represents an assignment of a role to a user.
  *
  * @author Qiang Xue <qiang.xue@gmail.com>
  * @author Alexander Kochetov <creocoder@gmail.com>
  * @since 2.0
  */
class Assignment extends Object
{
     /**
      * @var string|integer user ID (see [[\yii\web\User::id]])
      */
     public $userId;
     /**
      * @return string the role name
      */
     public $roleName;

!!!!!! Не дописано, закомментировано в релизе, а в контроллере одну 
строчку закомментировать забыли!

     /**
      * @var integer UNIX timestamp representing the assignment creation 
time
      */
    // public $createdAt;
}

25.10.2015 22:39, Alexander Makarov пишет:
>
> Why?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/yiisoft/yii2/issues/10006#issuecomment-150961677>.
>

-- 
-- Святослав Шульпин

**Comment by Svyatoslav-S** [comment]
Because in Yii2 2.0.6 Assignment.php:
<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace yii\rbac;

use Yii;
use yii\base\Object;

/**
 * Assignment represents an assignment of a role to a user.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @author Alexander Kochetov <creocoder@gmail.com>
 * @since 2.0
 */
class Assignment extends Object
{
    /**
     * @var string|integer user ID (see [[\yii\web\User::id]])
     */
    public $userId;
    /**
     * @return string the role name
     */
    public $roleName;


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! No property!
    /**
     * @var integer UNIX timestamp representing the assignment creation time
     */
   // public $createdAt;
}
