### ISSUE TITLE
Is there a possible to add/change a "schemaCache key" to flush schemaCache instead of via command

### ISSUE THREAD

**Issue by ihipop** [yiisoft/yii2#10003]
it not very convince to flush schemaCache  in a lot of servers via ```yii cache/flush-schema```
when deploy new code ,and if there was more than one server in Load balancing, execute the flush command ```Yii::$app->db->schema->refresh()``` will also can't be relaiable to apply the command to every server.
I think that if there was a ```schemaCache key``` configuration, we can make the old schemaCache invalid once the code is deploied and web page is requested.

**Comment by samdark** [comment]
Schma is stored using many keys. One key per table. Do you mean cache prefix?

**Comment by ihipop** [comment]
@samdark change ```cache prefix``` will invalid all the other  caches,I mean that if there is a common prefix of ```schemaCache```,for example
somehash(```common prefix```+```One key per table```)
change the  ```common prefix```  will flush the "schemaCache" reliably ,without clear the other caches

**Comment by samdark** [comment]
In this case it won't flush it strictly speaking. It would use new empty set of keys.

**Comment by ihipop** [comment]
@samdark  does a new empty key won't  invalid the ```schemaCache``` ?
I think that if nothing in the ```cachekey```, the ```Table schemaCache``` should be rebuild.

**Comment by samdark** [comment]
Schema will be invalidated, of course. But old data would be still there taking space.

**Comment by ihipop** [comment]
any update on this issue?

**Comment by cebe** [comment]
I do not really get the problem, why can't you invalidate schemaCache for all instances once the DB is updated?

Schema cache needs to be flushed in the moment where the database migrations are run so it has to apply to all cache servers in that very moment, regardless how the code is deployed. Do you have independent cache instances on each server?

**Comment by ihipop** [comment]
@cebe  yes，have independent  none-persistence cache instances in  different server section .
migrations sometimes is yii  irrelevant.

**Comment by cebe** [comment]
you have to implement a way to invalidate caches on all servers at once after you have applied migrations. that is not something yii can do.
