### ISSUE TITLE
Add postgres 'distinct on' expression support 

### ISSUE THREAD

**Issue by pahanini** [yiisoft/yii2#10013]
Postgres supports `distinct on` expressions but query builder does not support this fature. The only way I've found is  to use db expression in select method with some column

For example:
```
if ($distinctRequired) {
   $query->select(new Expression("DISTINCT ON (item.main_id) item.id"))
}
```

But may be it's better to add special distinctOn method?

```
if ($distinctRequired) {
   $query->distinctOn('main_id')
}
```

**Comment by samdark** [comment]
No since it is PostgreSQL specific.

**Comment by stenleegunz** [comment]
ебучий шляпник
