### ISSUE TITLE
yii\db\ActiveRecord executes two query for relations

### ISSUE THREAD

**Issue by raminious** [yiisoft/yii2#10016]
I created a simple User and Profile System, every User has one Profile

##### User Schema:  

id (pk) | email | password | ... |
---|---------|-------------|-----
58 | foo@bar | password |

##### Profile Schema:  
  
id (pk, fk)  | gender | phone | ... |
----|----------|----------|----
58 | 0 | +18187678 |

```php
    /**
     * every user has one profile
     * @return \yii\db\ActiveQuery
     */
    public function getProfile ()
    {
        return $this->hasOne(Profile::className(), ['id' => 'id']);
    }
```

Get Profile from User

```php
        $user = User::find()
            ->select(['user.*', 'user_profile.*'])
            ->joinWith('profile')
            ->where(['user.id' => 58])
            ->one();

        $profile = $user->profile;
```

After executing previous code, yii generate two Sql queries, I cant understand why the second query is generated. Is this a bug ?

![image](https://cloud.githubusercontent.com/assets/334716/10734821/6306ffbe-7c1a-11e5-9024-c31cdee49bfe.png)

ps - I test the code with and without ``` $eagerLoading ``` and the result was same

**Comment by samdark** [comment]
No, it's not a bug.

**Comment by raminious** [comment]
Thank you.
Can you please explain why the second query happens ?
I read [ActiveRecord](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html) section but still can't understand the logic of second query.

**Comment by samdark** [comment]
http://www.yiiframework.com/forum/index.php/topic/67995-eager-loading-disaster/
