### ISSUE TITLE
Module > Yii::configure components

### ISSUE THREAD

**Issue by njitram** [yiisoft/yii2#10024]
In my Module i register the component "cartManager", when i try to access the component inside the DefaultController it says: "Getting unknown property: yii\web\Application::cartManager".
When using setComponents it will work, to me it seems like a bug.

````
        //initialize the module with the configuration loaded from config.php
        $options = require(__DIR__ . '/config.php');
        \Yii::configure($this, $options);
        if(isset($options['components']))
            \Yii::$app->setComponents($options['components']);
````

I followed this guide:
http://www.yiiframework.com/doc-2.0/guide-structure-modules.html

**Comment by mdmunir** [comment]
`$this` variable is refer to `module` not to `Yii::$app`. The doc is correct but you doing wrong.
To register component to `Yii::$app` you must use `Yii::$app->set()` or `Yii::$app->setComponents`.
http://www.yiiframework.com/doc-2.0/yii-di-servicelocator.html#set()-detail
