### ISSUE TITLE
Problem in ActiveRecord (dot in column name is breaking query builder, mssql)

### ISSUE THREAD

**Issue by dkuzevanov** [yiisoft/yii2#10020]
'No.' is correct column name in MSSQL.
I made model and try to use it:

> $man = Model::find()->andFilterWhere(['like', 'No.', '62821'])->count();

But i got:

> Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 20018 An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name. [20018](severity 15) [(null)]
> The SQL being executed was: SELECT COUNT(*) FROM [CENSORED] WHERE [No].[] LIKE '%62821%''

Problem is in the **vendor/yiisoft/yii2/db/Schema.php:520**
There is **public function quoteColumnName($name)(...)**

In the second 'if' there have to be:

> if (($pos = strrpos($name, '.')) !== false **&& $pos !== strlen($name) - 1**) {..}

Instead:

> if (($pos = strrpos($name, '.')) !== false) {..}

**Comment by dkuzevanov** [comment]
May be '.No' is correct column name too? In this case we need to add check if dot is first or last.

**Comment by cebe** [comment]
`No.` is not a valid PHP property name so there is no point in supporting such column names on the AR level. Also allowing `.` in normal column names would complicate the code for automatic quoting of column names and may even make it impossible.

**Comment by dkuzevanov** [comment]
**cebe** You can access it by $object->{'No.'}

**Comment by PowerGamer1** [comment]
>  No.  is not a valid PHP property name
"No." is completely standard SQL compliant identifier when properly quoted. 

> so there is no point in supporting such column names on the AR level.
There is a point when the result of AR is converted into array (with `toArray()`) and the alias becomes a key in the array - no problems using array key with a dot in PHP whatsoever.

Currently there is no workaround at all (other than not using Query Builder) to produce an SQL with an alias having a dot - neither manual alias quoting using {{ }} symbols, nor using `\yii\db\Expression` helps. This must be supported on the framework level.

**Comment by dkuzevanov** [comment]
> This must be supported on the framework level.

I fully support this. It have to be done.

**Comment by dkuzevanov** [comment]
Another case,  '[No.]' is valid name too.
In case of:
> $man = Model::find()->andFilterWhere(['like', '[No.]', '62821'])->count();

will break query too.

Problem is in the **vendor/yiisoft/yii2/db/Schema.php:523**
I think, there have to be:
> if (strpos($name, '(') !== false || strpos($name, '[[') !== false || strpos($name, '{{') !== false **|| (substr($name, 0, 1) === '[' && substr($name, -1, 1) === ']')**) {..}

Instead of:

> if (strpos($name, '(') !== false || strpos($name, '[[') !== false || strpos($name, '{{') !== false) {



But all of this are a crutch :) We need more more general solution for this.
Thnx.

**Comment by dkuzevanov** [comment]
Are there info about this request?

**Comment by vasiluy-kondr** [comment]
Ran into the same issue. My db schema contains columns named after domains. Something like `example.com` get quoted as ``` `example`.`com` ```.

Fixed it by overriding `BaseActiveRecord::getDirtyAttributes` in my model.
```php
private $escapeDotInColumnNames = false;

public function beforeSave($insert)
{
    if (!parent::beforeSave($insert)) {
        return false;
    }

    $this->escapeDotInColumnNames = true;

    return true;
}

public function afterSave($insert, $changedAttributes)
{
    $this->escapeDotInColumnNames = false;

    parent::afterSave($insert, $changedAttributes);
}

public function getDirtyAttributes($names = null)
{
    $attributes = parent::getDirtyAttributes($names);
    if ($this->escapeDotInColumnNames) {
        foreach ($attributes as $key => $value) {
            if (strpos($key, '.') !== false) {
                $attributes["`$key`"] = $value;
                unset($attributes[$key]);
            }
        }
    }

    return $attributes;
}
```
