### ISSUE TITLE
Query each method does not recognize if there are no more rows

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#10023]
Like mentioned in: #9962 there is a problem with the recognition of the end of a resultset.

Example:
There is a table with 10 entries

``` php
foreach ($query->each() as $key => $value) {
    echo $key."\n";
}
```

after it selects the 10th row it throws an exception:

```
Exception 'PDOException' with message 'SQLSTATE[IMSSP]:
There are no more rows in the active result set.
Since this result set is not scrollable, no more data may be retrieved.'

in vendor\yiisoft\yii2\db\DataReader.php:111

Stack trace:
#0 vendor\yiisoft\yii2\db\DataReader.php(111): PDOStatement->fetch()
#1 vendor\yiisoft\yii2\db\BatchQueryResult.php(143): yii\db\DataReader->read()
#2 vendor\yiisoft\yii2\db\BatchQueryResult.php(112): yii\db\BatchQueryResult->fetchData()
#3 commands\TestController.php(26): yii\db\BatchQueryResult->next()
```

**Comment by SilverFire** [comment]
As for me, it is not a feature - it's a bug, and it affects only MSSQL

**Comment by samdark** [comment]
@SilverFire `feature:db` means it's database related, not the fact that it's a feature :)

**Comment by jadrovski** [comment]
yea it's a bug, how to fix? :-(

**Comment by samdark** [comment]
https://bugs.php.net/bug.php?id=65945

**Comment by alexkart** [comment]
So, this can't be fixed in the framework code?
If so, there is a workaround:
```
$allRows = [];
        try {
            foreach ($each as $index => $row) {
                $allRows[$index] = $row;
            }
        } catch (\PDOException $e) {
            if ($e->getMessage() !== 'SQLSTATE[IMSSP]: There are no more rows in the active result set.  Since this result set is not scrollable, no more data may be retrieved.') {
                throw $e;
            }
        }
```
And it works correctly, `$allRows` will contain all rows. The same is true for `batch()`.

**Comment by samdark** [comment]
> So, this can't be fixed in the framework code?

Can't we add the above workaroud to `each`?

**Comment by alexkart** [comment]
> > So, this can't be fixed in the framework code?
> 
> Can't we add the above workaroud to `each`?

Yes, created a PR
