### ISSUE TITLE
Documentation-ru mistake with Model::loadMultiple

### ISSUE THREAD

**Issue by mikbox74** [yiisoft/yii2#10030]
Hello!
I try exactly the same code in real production project: 
[Работа с несколькими моделями](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/input-multiple-models.md#%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D0%BC%D0%B8-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8F%D0%BC%D0%B8)
Alas, it does not work. I think the reason is different form names for different models.
I have replaced 
```php
Model::loadMultiple([$user, $profile], $post) 
```
by 
```php
$user->load($post) && $profile->load($post)
```
and now action works fine.
English guide has'nt this mistake.

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/0b4faf6fd2c0f56672bf6a959b7c8a5d4b89375b
