### ISSUE TITLE
How to implement RateLimit for the Rest API?

### ISSUE THREAD

**Issue by gb5256** [yiisoft/yii2#10036]
I am struggeling with how to implement the RateLimit.
The documentation is (for me) not clear. Perhaps somebody can give me a hint.
If I understand it correctly, I need to extend the user class like this: 

    class User extends ActiveRecord implements \yii\web\IdentityInterface, \OAuth2\Storage\UserCredentialsInterface, \yii\filters\RateLimitInterface

I have then created the three necessary functions within that user class:

    public function getRateLimit($request, $action) {   
    }
    public function loadAllowance($request, $action) {
    }
    public function saveAllowance($request, $action, $allowance, $timestamp) {   
    }

Do I now have to create the logic inside these three functions? Like calling the two columns to store the values? Does anybody have an example for this?
thanks a lot...

**Comment by mikehaertl** [comment]
The current rate limiter is meant to be used with a custom `yii\web\User` class or some identity model (e.g. a `User` ActiveRecord) where you have to implement the `RateLimitInterface` methods. In both cases you will probably rely on the *session* to identify the current visitor and store the internal rate limit data. But session based rate limiting is of very limited use in my opinion. It would only work if a potential attacker is very nice and sends along any session cookies with each request.

It would be much more reliable to at least have an IP based rate limiter.

@samdark Even with the current implementation we could build an IP based rate limiter. We could have something like `IpUser implements RateLimiterInterface`. It would represent a unique IP address and should use a persistent storage (DB, file, ...) to save/load the rate limiter data.

Opinion?

**Comment by samdark** [comment]
@mikehaertl yes, current one won't work for public APIs. Let's create separate issue about it.

**Comment by samdark** [comment]
@gb5256 I've added example to docs.

**Comment by gb5256** [comment]
@samdark & @mikehaertl
Thanks to both of you for making this more clear.
I was able to implement this now in my rest api and it works fantastic.
