### ISSUE TITLE
Likely bug in safeAttributes re scenarios

### ISSUE THREAD

**Issue by andrewblake1** [yiisoft/yii2#10034]
I have some rules that apply to all scenarios .(no on => ...)

I have SCENARIO_UPDATE for another rule that is conditionally added dependant on access check.

When using safeAttributes during SCENARIO_UPDATE, all of the default scenario attributes are ignored  because safeAttributes only takes into account SCENARIO_UPDATE - which doesn't exist in scenarios for the model when access has been denied.

possible solution in safeAttributes is change
```
return[];
```
for
```
$scenario = self::SCENARIO_DEFAULT;
```
I haven't yet noticed any detrimental consequences to this resolution but don't have a deep enough understanding to guarantee there isn't.

It is possible though unlikely that this is by design, as simply adding SCENARIO_UPDATE to one of the rules fixes the problem - enabling all other non scenario specific attributes to be returned as safe. Just because now the scenario is seen to exist.

**Comment by cebe** [comment]
can you paste a set of rules that reproduce the problem? also if you have implemented scenarios() method, paste its implementation too.

**Comment by andrewblake1** [comment]
I haven't implemented my own scenarios() - should I?

Extract:
```
public function rules()
{
    $rules = [
        [['account_id', 'user_id'], 'required'],
        /**
         * If 'on' is uncommented then the attributes above become safe in self::SCENARIO_UPDATE regardless of the
         * condition toggle below
         */
        [['user_id'], 'number'/*, 'on' => [self::SCENARIO_CREATE, self::SCENARIO_UPDATE]*/],
    ];

    $rules[] = [['email', 'name'], 'required', 'on' => self::SCENARIO_CREATE];

    /*
     * toggling the condition to false will not only stop email and name from being safe but also account_id and user_id
     * which should be safe in self::SCENARIO_UPDATE
     */
    if (true) {
        $rules[] = [['email', 'name'], 'required', 'on' => self::SCENARIO_UPDATE];
    }

    return $rules;
}
```

###### Further if it helps
Default implementation of scenarios seems correct - it can't produce a list of applied attributes for a scenario that isn't referenced in rules.

By returning \[\] (as opposed to throwing exception) it seems there is an expectation for scenarios to potentially be used that aren't in rules, however it seems it should return default attributes rather than none.

**Comment by cebe** [comment]
Okay, now I understand the problem. If you do not declare the update scenario in all cases in rules() you should implement scenarios() method and define explicitly which scenarios you have.

changing the implementation to return attributes on invalid/unknown scenario will break BC and may cause security issues. also if a scenario does not exist, you can not call validate() without receiving an exception. So if we would change it in safeAttributes you would still have the exception in validate().
I would leave the code as is.

**Comment by andrewblake1** [comment]
Ok, thanks. I will either implement scenarios or perhaps just add the scenario in on one rule as above.

Now that you have pointed it out, I can see I would have needed to alter similarly in activeAttributes and to remove the scenario check in validate.

I guess the security concern would be default attributes becoming safe in existing usages where they aren't currently. Possibly a doc thing - I had expected those default attributes to always be safe and probably unexpected to most (and a security concern in itself) that adding scenario to a single rule carrying one attribute enables all other default scenario attributes.
