### ISSUE TITLE
email post/get does not show in sending emails

### ISSUE THREAD

**Issue by klarizonemar** [yiisoft/yii2#10046]
I found out that the ContactForm model does not get the email filled out by the end user.

public function sendEmail($email)
{
        return Yii::$app->mailer->compose()
            ->setTo($email)//ok
            ->setFrom([$this->email => $this->name])//the name is ok but the email entered by the end user is not displaying. The value that is being displayed is from Yii::$app->params['adminEmail']
            ->setSubject($this->subject)//ok
            ->setTextBody($this->body)//ok
            ->send();
}

**Comment by samdark** [comment]
Do you mean end users are getting email with empty bodies using standard app template contact forms?

**Comment by klarizonemar** [comment]
The end users are getting the body, name and subject correctly but the email of the sender or setFrom() value is not correct. The email value seen in the mail inbox is the adminEmail instead of the email typed by the end user.

**Comment by samdark** [comment]
![mail](https://cloud.githubusercontent.com/assets/47294/10818331/d38d59d4-7e51-11e5-8142-210e5c6c0ea5.png)

**Comment by samdark** [comment]
Looks OK to me.

**Comment by klarizonemar** [comment]
Thank you for your response @samdark :)
