### ISSUE TITLE
How to set Relation Record

### ISSUE THREAD

**Issue by Liv1020** [yiisoft/yii2#10057]
In Yii1 we can set relation record as this:
```
$article = new Article();
$article->user = User::model()->findById(1);
```

but in 2, Not have such. I want to use it for new record and set an active record to it:

```
$article = new Article();
$article->user = User::findOne(1);
```

```
print $article->user;
```
print is user of 1

**Comment by samdark** [comment]
What do you need it for?

**Comment by klimov-paul** [comment]
Use `ActiveRecord::populateRelation()`

**Comment by Liv1020** [comment]
I need 
```
$article = new Article();
$article->user = User::findOne(1);
```
```
print $article->user;
```
like this, first set relation and call this set, not ar find mysql

**Comment by Liv1020** [comment]
```
Use ActiveRecord::populateRelation()
```
thank you @klimov-paul
