### ISSUE TITLE
verify count query performance

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#10055]
See https://github.com/yiisoft/yii/issues/3981#issuecomment-152211693

**Comment by mikk150** [comment]
I have seen this, can verify.

**Comment by pana1990** [comment]
@mikk150 can you show me a example for reproduced this issue? please

**Comment by cebe** [comment]
not sure there is a way to automatically detect this. Also not sure if mysql query optimizer should not care about htis.

**Comment by dynasource** [comment]
I've verified this with a statistics table with 1 million rows in MariaDb 10.1.9

It does not matter of either * or an indexed key is used in the subquery after which count(*) is used. The next queries give the same results.
```sql
SELECT SQL_NO_CACHE COUNT(*) 
FROM (
	SELECT *
	FROM stats_runner
) as A
```

```sql
SELECT SQL_NO_CACHE COUNT(*) 
FROM (
	SELECT timestamp
	FROM stats_runner
) as A
```

```sql
SELECT SQL_NO_CACHE COUNT(timestamp) 
FROM (
	SELECT timestamp
	FROM stats_runner
) as A
```

**Comment by cebe** [comment]
@dynasource the same "result" in which way? same performance?

**Comment by dynasource** [comment]
yeah. I verified the performance.

**Comment by cebe** [comment]
would be good to post the results here :)

**Comment by dynasource** [comment]
will do next time. I verified manually with many iterations and I didnt see any variation in total execution time.
