### ISSUE TITLE
Не правильная генерация CRUD 

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#10062]
при создании CRUD контролер получается 

       namespace app\modules\admin\Controllers;

тогда как надо 

       namespace app\modules\admin\controllers;

**Comment by samdark** [comment]
Что вводим в поля Gii?

**Comment by des1roer** [comment]
возможно возникает только при CamelCase именовании контролера\модели

**Comment by samdark** [comment]
Что именно вводим в поля Gii? Как воспроизвести?

**Comment by SilverFire** [comment]
Закрываю до появление новой информации
