### ISSUE TITLE
Problem with test environment

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2#10067]
I was setting up CI environment for an application based on Yii2 and found a strange issue.

I have wrong mysql user and password on purpose to see how build doesn't pass.
When running on ci:

```
php init --env=Development --overwrite=All
php yii migrate --interactive=0
```

I get:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.152' (using password: YES)'
ERROR: Build failed with: exit code 1
```

as expected. But when running:

```
php init --env=Development --overwrite=All
cd tests/ && php codeception/bin/yii migrate --interactive=0
```

I get:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.149' (using password: YES)'
Build succeeded.
```

the same exception with success code. I can not find any difference in configs.

**Comment by armpogart** [comment]
Investigating problem I've found out that in `yii/base/Application` if `YII_ENV` is set to `test` application instead of returning exit code that one must expect, throws `yii/base/ExitException` which I don't see even in ci (terminal) output.

Is it right behaviour? How on earth CI must understand that build failed, if we don't return right status code and simply throw exception which is not even visible?

**Comment by samdark** [comment]
Doesn't sound like right behavior to me.
