### ISSUE TITLE
Change Inflector::transliterate to public

### ISSUE THREAD

**Issue by dinhtrung** [yiisoft/yii2#10061]
In order to support transliteration, I have to install another composer module (yii2-transliteration) to do so.

Just found that simple conversion can be made with our transliterate.

Why don't we change `protected` to `public static transliterate` instead? It quite convenient some time.

Thanks,

**Comment by samdark** [comment]
Do you want transliteration only? There's `Inflector::slug()` for URLs.

**Comment by dinhtrung** [comment]
Yes, slug can be use to normalize the filename and url. However in some language (mine is Vietnamese) the meta-data or meta-keywords also should be transliterate for better SEO. Another use case is to generate Ascii equivalent version of name or contents. This is where transliteration come in handy. 

Does it make sense?

**Comment by samdark** [comment]
Better SEO w/ transliterated content? Are you absolutely sure?

Overall I agree that there could be cases.

**Comment by dinhtrung** [comment]
I'm not a SEO expert so I am not sure about the effective of transliteration keywords. However many websites in Vietnam include both transliterated and original keywords meta in the header.

There also some resources mention this and I believe search engine got index on transliterated content easier (more similar to English?).


https://moz.com/blog/so-you-want-to-know-about-foreign-language-seo-mozinar-q-a

For my recent project, I use it to convert SMS content. It is one of use case I think.

**Comment by samdark** [comment]
SMS content is definitely a good use case.

**Comment by SilverFire** [comment]
`Inflector::slug` removes all special characters. Example of slugging from the test:

```php
            'עִבְרִית' => 'iberiyt',
            'недвижимость' => 'nedvizimost',
```

When we make `Inflector::transliterate` public, we can get chars with diacritic symbols like this:

```php
'ʻibĕriyţ'
'nedvižimostʹ'
```
I can say about Russian word "недвижимость" that we don't use diacritics in transliteration and 'ž' is usually written like 'zh'. I'm sure there are many special rules of transliteration most of languages. 

Is it an expected behavior?

**Comment by SilverFire** [comment]
Found a solution that can be turned optionally.

`BaseInflector::transliterator` defaults to `Any-Latin; NFKD`.

NFKD is an option of forms normalization described on [unicode consorcium website](http://unicode.org/reports/tr15/#Normalization_Forms_Table)

So let's test different common options:
```php
$s = `获取到后台数据后 Український транслит на PHP! ¿Недвижимость или עִבְרִית?`;
$transliterators = ['Any-Latin; NFKD', 'Any-Latin; Latin-ASCII', 'Any-Latin; NFKD; [\u0080-\u7fff] remove'];
foreach ($transliterators as $transliterator) {
    echo "<br>" . transliterator_transliterate($transliterator, $string);
}
```

```
huò qǔ dào hòu tái shù jù hòu Ukraí̈nsʹkij translit na PHP! ¿Nedvižimostʹ ili ʻibĕriyţ?
huo qu dao hou tai shu ju hou Ukrainsʹkij translit na PHP! ¿Nedvizimostʹ ili ʻiberiyt?
huo qu dao hou tai shu ju hou Ukrainskij translit na PHP! Nedvizimost ili iberiyt?
```

The most spelling-correct is no.1, but the safest is no. 3.

Your thoughts?

**Comment by samdark** [comment]
We should make it an option.

**Comment by SilverFire** [comment]
It's already an option of `Inflector`. Do you want do make it as an option of `transliterate()` method?

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
Probably.

**Comment by SilverFire** [comment]
It's good idea. 
Do you want to pre-define listed above options of forms normalization?

**Comment by samdark** [comment]
Yes.

**Comment by SilverFire** [comment]
I'll handle this. Wait for the PR
