### ISSUE TITLE
Suggest force to convert $attribute use floatvar() after it successfully validate by numberValidator 

### ISSUE THREAD

**Issue by zhaosih** [yiisoft/yii2#10066]
values submitted by form are always string type, it's ok with Mysql.  
user_id=10 and user_id='10' both works.  
but when come to MongoDB , values are more type sensitive .

**Comment by samdark** [comment]
That would be change of behavior so it's a no go for 2.0.x. Will consider for 2.1.

**Comment by Faryshta** [comment]
I think this should be the job for a `FilterValidator`. PR required?

**Comment by klimov-paul** [comment]
Already solved by #12067
