### ISSUE TITLE
verify code never fresh when page fresh

### ISSUE THREAD

**Issue by bubifengyun** [yiisoft/yii2#10071]
thanks @ljfrocky in yiichina.com [here](http://www.yiichina.com/tutorial/410).

ljfrocky say that you can change *vendor/yiisoft/yii2/captcha/CaptchaValidator.php* 
as ![code](http://img.blog.csdn.net/20150528132730775)

false to true.

**Comment by samdark** [comment]
You mean captcha isn't refreshed during AJAX validation?

**Comment by bubifengyun** [comment]
in browse , click F5 refresh the page. it will never refresh verify code. but when I change *false*  to *true* , it will be freshed.

**Comment by bubifengyun** [comment]
it will fresh, when click the button.

**Comment by bubifengyun** [comment]
it is that you fresh the whole page, the verify code will not be changed. but the verify image will be changed with the same code.

if you click the button which labeled "change another verify code", the verify code  will be changed.

**Comment by bubifengyun** [comment]
if you know Chinese, 
如果刷新页面，比如按F5刷新，验证码不变，验证码图片改变了，但是图片中的字母数字还是那几个。

点击旁边的换个验证码按钮，工作正常。


如果按照上面说的，把false改为true，则一切正常。暂时没有发现副作用。

**Comment by samdark** [comment]
I understood what you're saying. During AJAX calls in the form may happen when you're focusing another input so re-generating captcha code each would've been too weird.

**Comment by SilverFire** [comment]
Agree with @samdark

**Comment by fishermanmax** [comment]
Thanks,but do you have a way to overwrite the function?
I overwrite it on /components/.
The code image is fresh,but the session didn't fresh.So I input every verifycode is error,error,error!.
Please help me do solve it ,Thank you a lot!!!My English is very poor,sorry.

**Comment by uussoft** [comment]
thanks
