### ISSUE TITLE
Can't create form w/o _csrf hidden input

### ISSUE THREAD

**Issue by gugglegum** [yiisoft/yii2#10078]
My form is submitted to external web-site. I using `yii\helpers\Html::beginForm()` in View to render form open-tag. But it adds unwanted hidden input `_csrf` which is absolutely useless for external web-site which will process my POST. Moreover external site can do CSRF-attack to my site by knowing my CSRF-key. Or it may not process my request due to unknown parameter `_csrf`.

Unfortunately, I have not found elegant solution to not to add this hidden input when using `beginForm()`. By analising the source code, there is no way to awoid this `_csrf` hidden input other than to set `Yii::$app->getRequest()->enableCsrfValidation = false`. But this is GLOBAL parameter! Here is fragment of yii\helpers\BaseHtml:

```
        $request = Yii::$app->getRequest();
        if ($request instanceof Request) {
            if (strcasecmp($method, 'get') && strcasecmp($method, 'post')) {
                // simulate PUT, DELETE, etc. via POST
                $hiddenInputs[] = static::hiddenInput($request->methodParam, $method);
                $method = 'post';
            }
            if ($request->enableCsrfValidation && !strcasecmp($method, 'post')) {
                $hiddenInputs[] = static::hiddenInput($request->csrfParam, $request->getCsrfToken());
            }
        }
```

I may have a several forms on one page (in one or in several view files which is included as partial or widget). Some of them may need CSRF-validation, some of them may not. And what should I do? If I do form for external web-site, I should set `enableCsrfValidation` to `false`, render form, then set `enableCsrfValidation` to `true`? More correct way is to store old value of `enableCsrfValidation` to temporary variable.

But what the hell the VIEW may want to change REQUEST? This is inappropriate behaviour. I should have a possibility to disable CSRF validation just once for single execution of `yii\helpers\Html::beginForm()`. This can be done via `$options`.

I decided to not to use `yii\helpers\Html::beginForm()` and use `yii\helpers\Html::beginTag()` instead. But it's little less convenient.

**Comment by samdark** [comment]
Yeah. ActiveForm should have an option to disable CSRF token per form...

**Comment by gugglegum** [comment]
Not only ActiveForm but Html::beginForm too.

**Comment by samdark** [comment]
Yep.

**Comment by gugglegum** [comment]
Also, can you explain why Html::beginForm() replaces form methods different from GET and POST to POST with hidden input named _method with value of original method? Why we need this simulation? Why we can't use native DELETE method in HTML forms?

```
            if (strcasecmp($method, 'get') && strcasecmp($method, 'post')) {
                // simulate PUT, DELETE, etc. via POST
                $hiddenInputs[] = static::hiddenInput($request->methodParam, $method);
                $method = 'post';
            }
```

**Comment by samdark** [comment]
Because browsers do not support that.

**Comment by cebe** [comment]
why don't you just use plain HTML? The Yii helper method is mainly useful for starting forms for your site including all the csrf stuff. if you just need a simple for for external post, just use plain HTML to create it.

**Comment by gugglegum** [comment]
cebe, yes, I can use plain HTML for external forms. But problem is not in external forms. I may want to have forms which doesn't need CSRF validation. For example, in some public web-services without authorization. This is actually not request-specific parameter. This is actually View-render parameter. I'm not agree with that my issue was closed without any changes in repo.

**Comment by machour** [comment]
One small blocker is that Yii handles csrf globally, and not on a form basis :
 - the <meta> csrf fields are placed in the main layout file using `Html::csrfMetaTags()`
 - the csrf token is tested in `\yii\web\Controller::beforeAction()`

So the user will also have to implement it's own beforeAction() to set `$enableCsrfValidation` to `false` for the specific action where he don't want the csrf token to be validated.
And by doing so, he may as well set `$enableCsrfValidation` to `false` in the action that generates the form and get rid of the csrf field that way :)

A new csrf option in `Html::beginForm()` would just come handy if you have two forms on the same page, one with csrf and one without it.. 

Should I prepare a PR for this anyway?

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
It's useful for forms at CSRF-enabled pages which post to non-CSRF-enabled pages.
