### ISSUE TITLE
TimestampBehavior trying to insert invalid values on MySQL

### ISSUE THREAD

**Issue by c-schmitz** [yiisoft/yii2#10076]
I am using the latest 'release' Yii version 2.0.6.

When trying to use the TimestampBehaviour it tries to insert invalid values instead of  NOW().

Query in trace actually executed is:

    INSERT INTO `responses_day` (`response_count`, `user_id`, `time_period`, `created`, `modified`) VALUES (3, 11, '2015-11-03', '1446550646', '1446550646')

Code of the model:

    <?php

    namespace app\models;
    use yii\db\ActiveRecord;
    use yii\behaviors\TimestampBehavior;

    class ResponseDay extends ActiveRecord
    {
        /**
         * @return string the name of the table associated with this ActiveRecord class.
         */
        public static function tableName()
        {
            return 'responses_day';
        }

        public static function getDb()
        {
            return \Yii::$app->mytestdb;
        }
        public function behaviors()
        {
            return [
                [
                    'class' => TimestampBehavior::className(),
                    'createdAtAttribute' => 'created',
                    'updatedAtAttribute' => 'modified'
                ],
            ];
        }
    }

SQL for table: 

    CREATE TABLE IF NOT EXISTS `responses_day` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `user_id` int(11) DEFAULT NULL,
      `response_count` float NOT NULL DEFAULT '0',
      `time_period` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `modified` datetime DEFAULT NULL,
      `created` datetime DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `Index_2` (`user_id`,`time_period`)
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

Insertion code:

            $ResponseDay=new ResponseDay;
            $ResponseDay->response_count=3;
            $ResponseDay->user_id=11;
            $ResponseDay->time_period='2015-11-03';
             $ResponseDay->save();

Expected behaviour:
Created/modified should be filled with the actual time stamp.

Instead:
Entries which contain '0000-00-00 00:00:00' are created.

**Comment by samdark** [comment]
Can you try removing `DEFAULT '0000-00-00 00:00:00',`?

**Comment by c-schmitz** [comment]
@samdark No change - the default is only on the field 'hitperiod' which is not filled by TimeStampBehaviour so it should not have any effect anyway. The only notable thing about this app is that it is a console command executing the insert. 
Question also is why it tries to insert a UNIX TIME stamp instead of NOW()? ("'1446550646'")

**Comment by samdark** [comment]
Ah, well, you forgot to configure it properly:

```php
public function behaviors()
{
    return [
        [
            'class' => TimestampBehavior::className(),
            'createdAtAttribute' => 'create_time',
            'updatedAtAttribute' => 'update_time',
            'value' => new Expression('NOW()'),
        ],
    ];
}
```
