### ISSUE TITLE
TimestampBehavior example in documentation does not work

### ISSUE THREAD

**Issue by c-schmitz** [yiisoft/yii2#10077]
The example code for TimeStampBehaviour in your documentation at  http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html#using-timestamp-behavior does not work,
 the one at http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html does.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/10076

**Comment by c-schmitz** [comment]
To be more precise -  the followoing error is thrown when using the first example code:

Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\behaviors\TimestampBehavior::beforeInsert'

**Comment by samdark** [comment]
It works but for UNIX timestamp fields only. Need to mention that.

**Comment by c-schmitz** [comment]
I am sorry but the mentioned first documentation exmaple does not work, even when adding the parameter 
    'value' => new Expression('NOW()'),
to the behaviour.

**Comment by samdark** [comment]
How exactly it does not work?

**Comment by c-schmitz** [comment]
See the mentioned error message above ;).

**Comment by samdark** [comment]
Unable to reproduce. It seems you're missing `'attributes' => [ ... ]`.
