### ISSUE TITLE
Update Database Access Object and yii\db\Command doc

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#10084]
Database Access Object (http://www.yiiframework.com/doc-2.0/guide-db-dao.html)

![dao](https://cloud.githubusercontent.com/assets/436950/10926013/654a523a-8250-11e5-965b-236b6f49adfb.png)

yii\db\Command ( http://www.yiiframework.com/doc-2.0/yii-db-command.html)

![yii_db_command](https://cloud.githubusercontent.com/assets/436950/10926109/66e447c6-8251-11e5-9a7c-f4a899e67d7b.png)

**Comment by samdark** [comment]
Good ideas. Thanks!
