### ISSUE TITLE
TimestampBehavior not executed when using model->updateCounters()

### ISSUE THREAD

**Issue by c-schmitz** [yiisoft/yii2#10080]
Problem:
When using the ActiveRecord method updateCounters() the TimeStampBehaviour is not executed.

Code: 
$ResponseDay=ResponseDay->findOne('100');
$ResponseDay->updateCounters(['response_count' => 1]);

Result:
Field 'modified' of the related table not being updated with latest time stamp

Expected result:
Since updateCounters() is an activeRecord method the behaviour should be properly executed.

Model code

Code of the model:

    <?php

    namespace app\models;
    use yii\db\ActiveRecord;
    use yii\behaviors\TimestampBehavior;

    class ResponseDay extends ActiveRecord
    {
        /**
         * @return string the name of the table associated with this ActiveRecord class.
         */
        public static function tableName()
        {
            return 'responses_day';
        }

        public static function getDb()
        {
            return \Yii::$app->mytestdb;
        }
        public function behaviors()
        {
            return [
                [
                    'class' => TimestampBehavior::className(),
                    'createdAtAttribute' => 'created',
                    'updatedAtAttribute' => 'modified',
                    'value' => new Expression('NOW()') // Workaround for issue #10076 
                ],
            ];
        }
    }

**Comment by c-schmitz** [comment]
#10076

**Comment by samdark** [comment]
It's executed only for `->save()`, `->update()` and `->insert()`.

**Comment by c-schmitz** [comment]
Then it is definitely a documentation issue  as this should be mentioned in the TimeStampBehaviour documentation, and maybe even in updateCounters documentation.

**Comment by samdark** [comment]
That's why I've updated docs.

**Comment by c-schmitz** [comment]
Ah great, thank you  - didn't see that at first. Btw, I like Yii2 alot better than Yii1 - huge improvement and fun to code with :-). So, thank you,again!
