### ISSUE TITLE
bower/jquery/dist does not exist

### ISSUE THREAD

**Issue by regha** [yiisoft/yii2#10089]
Hello,
After migrating to 2.0.6, i see this message:
"The file or directory to be published does not exist: /var/www/html/basic/vendor/bower/jquery/dist"

All worked well before...

**Comment by Renkas** [comment]
Ypu need to update composer asset plugin

```composer global require "fxp/composer-asset-plugin:~1.0.3"```

I think this should be added to UPGRADE.md

**Comment by samdark** [comment]
1.

**Comment by regha** [comment]
Thank for your reply,
I have tried to change in vendor/yiisoft/yii2/web/request.php file this line : 
 public $enableCookieValidation = false;
I changed true to false
And it works...
But perhaps, that's not the better thing to do...
