### ISSUE TITLE
Fields not showing required class with conditional validator in model

### ISSUE THREAD

**Issue by jhebb** [yiisoft/yii2#10085]
If I add a conditional validator to a rule in a model using 'when' or 'whenClient', it doesn't add the 'required' css class. Does commit feec6dc mean that's done on purpose?

I'm using the required class to visually cue users which fields are required by adding an asterisk with js. Should I just be manually adding the 'required' class in these cases or is there a better way?

**Comment by ferrika** [comment]
please show your view code

**Comment by ferrylukito** [comment]
please show your view code

**Comment by ferrylukito** [comment]
i have similliar issue while adding id to options attribute
like this 

```javascript
echo $form->field($user, 'name')->textInput(['id' => 'userName']);
```

**Comment by SilverFire** [comment]
@jhebb yeah, it seems to be done not accidentally.
We can't mark the field as required since we don't really know, whether it is.

You can add a `required` class to the field dynamically on validation of depend attributes.

**Comment by jhebb** [comment]
@SilverFire Thanks for the update!

For adding the required class dynamically, do you mean just some custom js, or is there a better Yii way to do this?

Any chance the Yii js validation will be updated to do this automatically in the future?

**Comment by SilverFire** [comment]
I meant custom JS.

> Any chance the Yii js validation will be updated to do this automatically in the future?

Of course if this feature is requested by more developers, we will consider adding it.

**Comment by jhebb** [comment]
Awesome, well count me in for a vote!

**Comment by sunny045** [comment]
Count me in too

**Comment by samdark** [comment]
Won't happen in 2.0 but we'll keep that in mind for 3.0.
