### ISSUE TITLE
ffmpeg required problem

### ISSUE THREAD

**Issue by sckn** [yiisoft/yii2#10082]
hi,
I upload yii2-basic project on shared-hosting service.
Yii2 return 
 PHP Core Warning – yii\base\ErrorException
PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/ffmpeg.so' - libswscale.so.2: cannot open shared object file: No such file or directory

I no need ffmpeg module how can I disable ?

**Comment by samdark** [comment]
Doesn't seem to be related to Yii in any way.
