### ISSUE TITLE
The view file not found when a controller is mapped

### ISSUE THREAD

**Issue by musay** [yiisoft/yii2#10086]
Since there is no corresponding file under mapped-to controller' view folder, application throws exception. When a controller is mapped, the views must be tried to find under mapped-from controller' view folder, not mapped-to controller.

**Comment by samdark** [comment]
Please elaborate on how to reproduce it.

**Comment by musay** [comment]
Consider this example to apply a module, which lets called 'forum' module and UserController has an action named 'edit';
[
  'account' => 'app\controllers\UserController',
  'article' => [
     'class' => 'app\controllers\PostController',
     'pageTitle' => 'something new',
  ],
]
(example taken from : http://www.yiiframework.com/doc-2.0/yii-base-module.html#$controllerMap-detail )

"?r=forum/account/edit" response' says, "The view file does not exist: /home/[user]/public_html/yii_example/modules/forum/views/account/edit.php

Of course there is no edit.php file under that directory, it located  /home/[user]/public_html/yii_example/views/user/account/ folder.

**Comment by samdark** [comment]
Agree. Should be fixed.

**Comment by Sibilino** [comment]
Any reason for basePath to not be configurable at Controller level? We could add _basePath in Controller and then have the Module configure its child controllers with according to this map.

I can make a pull request if this strategy is ok.

**Comment by lynicidn** [comment]
>Of course there is no edit.php file under that directory, it located /home/[user]/public_html/yii_example/views/user/account/ folder.
error - check path

**Comment by Sibilino** [comment]
This is what I meant. Making `viewPath` configurable in Controller, the `$controllerMap` can contain any needed path configuration:
```php
public $controllerMap = [
    'account' => [
        'class' => 'app\controllers\UserController',
        'viewPath' => '/home/[user]/public_html/yii_example/views/user/account'
    ],
    // ...
]
```

**Comment by Sibilino** [comment]
Yes, enhancement my be better. I'll update the changelog too.

**Comment by musay** [comment]
@Sibilino Changing viewPath doesn't make sense since the class already uses those views in that view path. The problem should be fixed by trying to detect whether the controller is mapped. If it is, the view path could automatically read. Defining viewPath is excess, I think.

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/d08ef83e2ad2d9b9813ec558d1adabfe7a90fc28
