### ISSUE TITLE
A bug with 'UNION' in sql

### ISSUE THREAD

**Issue by 1Pauletto** [yiisoft/yii2#10090]
Hello! I have a table with rows:

CREATE TABLE user_drive_share
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    id_user_from INT NOT NULL,
    email VARCHAR(255) NOT NULL,
    id_file VARCHAR(255) NOT NULL
);

INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (1, 39, 'myrobotbender@gmail.com', '0B5qCeQzjix39cWZBbU1naXVzdzg');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (2, 39, 'testtest3@gmail.com', '0B5qCeQzjix39cWZBbU1naXVzdzg');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (3, 39, 'showmemymailplease@gmail.com', '0B5qCeQzjix39cWZBbU1naXVzdzg');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (4, 39, 'myrobotbender@gmail.com', '0B5qCeQzjix39czd1SXBLMnA2WTg');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (5, 39, 'testtest3@gmail.com', '0B5qCeQzjix39czd1SXBLMnA2WTg');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (6, 39, 'showmemymailplease@gmail.com', '0B5qCeQzjix39czd1SXBLMnA2WTg');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (7, 39, 'myrobotbender@gmail.com', '0B5qCeQzjix39cE1NSHNHSXFmQU0');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (8, 39, 'testtest3@gmail.com', '0B5qCeQzjix39cE1NSHNHSXFmQU0');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (9, 39, 'showmemymailplease@gmail.com', '0B5qCeQzjix39cE1NSHNHSXFmQU0');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (10, 39, 'myrobotbender@gmail.com', '0B5qCeQzjix39aDdhRnVjWG91eDQ');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (14, 39, 'testtest3@gmail.com', '0B5qCeQzjix39Nk5KejJzRjR1T2c');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (19, 39, 'showmemymailplease@gmail.com', '0B5qCeQzjix39OVVxUGsySHYwVzA');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (18, 39, 'myrobotbender@gmail.com', '0B5qCeQzjix39OVVxUGsySHYwVzA');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (20, 39, 'myrobotbender@gmail.com', '0B5qCeQzjix39aE5mN2NCUG9LS0k');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (21, 34, 'showmemymailplease@gmail.com', '0B0meGz7eyLLOS0V6RElVNHRkY0E');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (22, 34, 'test-myrobotbender@gmail.com', '0B0meGz7eyLLOS0V6RElVNHRkY0E');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (23, 34, 'user-myrobotbender@gmail.com', '0B0meGz7eyLLOS0V6RElVNHRkY0E');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (24, 34, 'showmemymailplz@gmail.com', '0B0meGz7eyLLOS0V6RElVNHRkY0E');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (25, 34, 'showmemymailplz@gmail.com', '0B0meGz7eyLLOZmRnMzdHUVNGQlE');
INSERT INTO user_drive_share (id, id_user_from, email, id_file) VALUES (26, 39, 'testtest3@gmail.com', '0B5qCeQzjix39RDdPbVpuWnppUWc');

When I try to fetch them like this:
```
$shared = Yii::$app->db->createCommand("
            select id_user_from, count(id_user_from) as count, email
            from user_drive_share
            where id_user_from=$userId
            GROUP BY id_user_from, email;
            UNION
            select id_user_from, count(id_user_from) as count, email
            from user_drive_share
            where email='$email'
            GROUP BY id_user_from, email;
        ", [
            ':id' => $userId,
            ':email' => $email
        ])->queryAll();
```
I didn't get the row from second query with email condition. If I execute this query in command line all is ok. The result with params is:
```
[
    0 => 39
    1 => 'showmemymailplz@gmail.com'
] 
[
    0 => [
        'id_user_from' => '39'
        'count' => '6'
        'email' => 'myrobotbender@gmail.com'
    ]
    1 => [
        'id_user_from' => '39'
        'count' => '5'
        'email' => 'shevchuku@gmail.com'
    ]
    2 => [
        'id_user_from' => '39'
        'count' => '4'
        'email' => 'showmemymailplease@gmail.com'
    ]
]
```
If I do this:
```
$shared = Yii::$app->db->createCommand("
            select id_user_from, count(id_user_from) as count, email
            from user_drive_share
            where email=:email
            GROUP BY id_user_from, email;
        ", [
            ':email' => $email
        ])->queryAll();
```
I get:
```
[
    0 => [
        'id_user_from' => '34'
        'count' => '2'
        'email' => 'showmemymailplz@gmail.com'
    ]
]
```

**Comment by SilverFire** [comment]
```
            where id_user_from=$userId
```
```
            where email='$email'
```

You must use [param-binding](http://www.yiiframework.com/doc-2.0/guide-db-dao.html#binding-parameters) to prevent SQL injections.


What's your problem? It's not clear for me.
Please, post:
 - the query that was executed (you can find it in debug panel -> database)
 - var_dump of the query execution result
 - Expected result

**Comment by 1Pauletto** [comment]
I found the mistake. I forgot to remove ";" before "UNION", so all is ok:)

**Comment by corean** [comment]
I'm on it. 윤수 김 (corean@corean.biz) turned your email into a to-do.











[yii2] A bug with 'UNION' in sql (#10090)















What is this:



To-do receipts are automatically sent to let you know that your email was added to the recipient’s to-do list in Handle.















handle


the simple way to stay on top of your life.



Download in the App Store.(http://handle.com/dl)



Check out the Web App.(http://desktop.handle.com)
