### ISSUE TITLE
how to get index array with ActiveRecord

### ISSUE THREAD

**Issue by agangdi** [yiisoft/yii2#10099]
When I use self::find()->select('Username')->asArray()->all();  to select column Username from mysql, I got result as bellow:

        array(2) { [0]=> array(1) { ["Username"]=> string(7) "username1" } [1]=> array(1) { ["Username"]=> string(6) "username2" } }

        how to get array without key like this:
 array(2) {  [0]=>  string(9) "username1"  [1]=>  string(9) "username2" }

**Comment by lichunqiang** [comment]
```
self::find()->select('Username')->asArray()->column()
```
?

**Comment by agangdi** [comment]
NB, well done!
