### ISSUE TITLE
override yii.js confirm function

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/yii2#10097]
I want rewrite the behavior `yii.confirm` function, but now the context is `yii`

But what we are needed is the triggered target element, `yii` is global, we can get is anywhere, so it will be better for enhancement.

**Comment by samdark** [comment]
Is the problem that you can't get `event`?

**Comment by lichunqiang** [comment]
@samdark Yep, nothing but the `yii` object in the function..

**Comment by liyunfang** [comment]
//重写yii.js中的方法
if(yii !== undefined && yii.confirm !== undefined){
    yii.confirm = function (message, ok, cancel) {
          yourself code...
    };
}

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/1a48d248301bcf30f3d20fb17ac067db5a2efc11
