### ISSUE TITLE
Array to string conversion BaseHtml.php:1741 PHP 5.5

### ISSUE THREAD

**Issue by unNene** [yiisoft/yii2#10092]
Hi,

I'm using  "yii\bootstrap\NavBar" and on server is installed PHP 5.5. I can't access the application because of error: "Array to string conversion" on line 1741 in file BaseHtml.php:

1741: if (strpos($classes, ' ' . $class . ' ') === false)

![selection_119](https://cloud.githubusercontent.com/assets/900974/10951980/f41010ec-8348-11e5-9c1b-adab864d1f91.png)

Here is my code for NavBar begin:

     NavBar::begin([
        'brandLabel' => 'Lion Transport',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
      ]);

Temporary I fixed this problem by adding on BaseHtml.php line 1738, before if statement this code:

		$strClass = '';
		if(is_array($class))
		{
			foreach($class as $item)
			{
				$strClass .= ' '.$item;
			}
			$class = $strClass;
		}

**Comment by SilverFire** [comment]
That's a notice, not an error. Anyway failed to reproduce on basic template app.
Can you show a full call stack?

**Comment by cebe** [comment]
which version of yii and which version of the bootstrap extension are installed? you may run `composer show -i` to get this info.

**Comment by unNene** [comment]
bower-asset/bootstrap - v3.3.5 
yiisoft/yii2 -  2.0.6  
PHP 5.6.16-1+deb.sury.org~trusty+1 (cli)

**Comment by githubjeka** [comment]
It could be close.
