### ISSUE TITLE
Add support for events declared in the interfaces

### ISSUE THREAD

**Issue by omnilight** [yiisoft/yii2#10108]
Currently using `Event` object we can subscribe only on events, that are declared in some class or it's parent. But sometimes I want to declare event in the interface, implement it by some class, and subscribe on event in this interface, not in the class, example:

```php
interface SomeInterface
{
    const EVENT_SOME_EVENT = 'someEvent';
}

class SomeClass extends Component implements SomeInterface
{
   public function domSomething() {
       $this->trigger(self::EVENT_SOME_EVENT);
   }
}

Event::on(SomeInterface::class, SomeInterface::EVENT_SOME_EVENT, function() {
   // My handler
});
```

But in current implementation of the `Event::trigger` method only events for parent classes are checked, but not from interfaces. May be we should add checking for events in the interfaces too?

**Comment by samdark** [comment]
Any idea how implementation could look like?

**Comment by omnilight** [comment]
In the pull-request

**Comment by samdark** [comment]
OK. Looks quite interesting but also makes events not as lightweight as they used to be. Worth benchmarking...

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/b68613b7469a7e5df42e0f532cc5370964b07899 https://github.com/yiisoft/yii2/commit/e0f4114d77bef0e3f1847801b3a41f5a9f6dc62e
