### ISSUE TITLE
Refresh model in yii\rest\CreateAction ?

### ISSUE THREAD

**Issue by karpy47** [yiisoft/yii2#10107]
I have a model where I use TimestampBehavior like this:

    [
	'class' => TimestampBehavior::className(),
        'value' => new Expression('NOW()'),
    ]

This class is then extended from when creating a Rest API.
Now, when creating a new object using the API's default yii\rest\CreateAction a new object is created, but when returning the newly created object to the view-action all date-time attributes related to TimeStampBehaviour still show the unevaluated value: "object Expression('NOW()')".

If I insert "$model->refresh" after "$model->save()" in the run-action of yii\rest\CreateAction it works as expected, but that is obviously not the way to solve it. 
Guess I could make another CreateAction or point to another ViewAction using the CreateAction->$viewAction parameter. 
Or is this something that could be improved in yii\rest\CreateAction ?

**Comment by karpy47** [comment]
Solved it by adding this to my API-model...

    public function afterSave($insert, $changedAttributes) {
        $this->refresh();
    }

Seemed like the easiest solution.

**Comment by russianlagman** [comment]
@qiangxue problem is still not solved both in CreateAction and UpdateAction. Proposal is to add refresh() call.

**Comment by cebe** [comment]
Adding `refresh()` to the framework by default would be waste of ressources when it is not needed. the solution proposed above, by adding it to afterSave() would be the way to go in such cases.

**Comment by russianlagman** [comment]
@cebe it could be tuneable with the action parameter and turned off by default. Solution above is not a good idea when you implement crud apis for tens of models. Model must not be responsible for the context of it's usage.
