### ISSUE TITLE
getopt() friendly console app

### ISSUE THREAD

**Issue by alez007** [yiisoft/yii2#10100]
Hi,

Can I suggest making the default coreCommands for yii\console\Application more getopt() friendly ? I wanted to modify the config and make it dependent on some parameters from getopt(), for example load something different based on the value of --db parameter (I do not want to parse argv) and the fact that the controller command does not contain '-' or '--', getopt function is not firing. My solution was to create a wrapper over yii\console\Application and overwrite the coreCommands function with something like this:

return [
            '-message' => 'yii\console\controllers\MessageController',
            '-help' => 'yii\console\controllers\HelpController',
            '-migrate' => 'yii\console\controllers\MigrateController',
            '-cache' => 'yii\console\controllers\CacheController',
            '-asset' => 'yii\console\controllers\AssetController',
            '-fixture' => 'yii\console\controllers\FixtureController',
        ];

but I don't see how it hurts if you make this update directly into the framework.

**Comment by samdark** [comment]
Coule elaborate about why getopt isn't firing?

**Comment by alez007** [comment]
I was doing some tests with a simple php script, test.php contains the following code:
```php
!/usr/bin/env php
<?php
var_dump(getopt(null, ['db::']));
```

1. php test.php migrate --migrationPath=@yii/log/migrations --db=db2 returns empty array
2. php test.php -migrate --migrationPath=@yii/log/migrations --db=db2 returns as expected

I think getopt() gets confused by the fact the parameter 'migrate' is not a short or a long parameter, meaning it's not beginning with '-' or --'.

**Comment by samdark** [comment]
We aren't going to change the syntax.
