### ISSUE TITLE
Assets are not taking the file changes in module

### ISSUE THREAD

**Issue by Nosthertus** [yiisoft/yii2#10115]
I have made a custom layout and a custom assets class

the assets file looks like this:
```php
<?php

namespace backend\modules\admin\assets;

use yii\web\AssetBundle;

class AppAsset extends AssetBundle
{
	public $sourcePath = '@app/modules/admin/web';
    public $css = [
        'css/site.css',
    ];
    public $js = [
        'js/admin.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];
}
```

the layout file registers this asset, everything works fine until i make changes i need to load to the browser..

for example: i am making changes in `js/admin.js` but the browser is not getting thoses changes, just loads the old state even if i press `ctrl + f5` to force loading all files. for now i have to delete all assets folders inside `web/assets` everytime i make a change but this is kind of annoying

**Comment by martingeorg** [comment]
Might be related to #9835 even though this is about JavaScript files and not CSS.

**Comment by sinus86** [comment]
try to use the following configuration for appending the timestamp to every js-file.
http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#$appendTimestamp-detail

**Comment by Alex-Code** [comment]
If this is on a dev environment I tend to use the `forceCopy` option.
This will always overwrite the existing asset in the web folder.

```php
class MyAsset extends \yii\web\AssetBundle
{
    public $publishOptions = [
        'forceCopy' => YII_DEBUG
    ];
}
```

**Comment by Faryshta** [comment]
Thats for the way php determines the last time the folder was updated http://php.net/manual/en/function.filemtime.php a recursive solution might be developed but it have to take into account the compilation of files .less, .ts files.

**Comment by SilverFire** [comment]
`forceCopy` does not work fast enough to use it for development, meanwhile [AssetManager::linkAssets](http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#$linkAssets-detail) works pretty good. I don't think that any changes are required, so closing the issue. Thank you
