### ISSUE TITLE
AuthManager: make assign() to accept single permissions as well

### ISSUE THREAD

**Issue by Nosthertus** [yiisoft/yii2#10114]
Sometimes we have the need to assign an user a single permission without creating a role just for this permission.. or to modify a role just for the needs of this single user..

The reason why i would need this, is because there are users that needs the access which his role doesn't have, but i don't want to assign him an existing role and grant him access to view where he should not.. just one thing rather than the whole packet from the role

**Comment by samdark** [comment]
It's better to have a role for that specific thing. Use can have multiple roles assigned.
