### ISSUE TITLE
extending SluggableBehavior

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2#10118]
I need a slug field for my model and it's going to be shown in url address. current `yii\helpers\Inflector::slug()` method does not produce what I need (it removes characters of my language) so I easily extended it and made needed changes.
The problem is there is no easy way to make SluggableBehavior use the new `slug()` method instead of default one! there is a 50-line-length method named [`getValue()`](https://github.com/yiisoft/yii2/blob/master/framework/behaviors/SluggableBehavior.php#L132) and among so many other things, it produces the real slug value to be saved. Am I supposed to extend the behavior and copy the whole method to edit just [1 line](https://github.com/yiisoft/yii2/blob/master/framework/behaviors/SluggableBehavior.php#L157) of it?
I think it should have a `protected generateSlug()` method which makes it easy to extend and alter slug creation logic. or is there another way I'm not aware of?

**Comment by cebe** [comment]
good suggestion

**Comment by hesna** [comment]
I'll make a PR in an hour then :)

**Comment by cebe** [comment]
I'm already working on it :)

**Comment by hesna** [comment]
Woops, I actually spent 2 hours on it :D 
I also made some refactors, would you please take a look at my PR too? 
I didn't edit the changelog file since you did the real fix :)
