### ISSUE TITLE
Use multiple values from a form into where condition. 

### ISSUE THREAD

**Issue by harshitchaudhary** [yiisoft/yii2#10116]
I am trying to fetch values using **where()** query in yii2, I want to use multiple where conditions from which values will be fetched, I have tried several alternatives none of them seems to work. 

The number and contents of $values is varying

`$test = Material::find()->where(['Material.MaterialId' => $value])->joinWith(['objectName'])->all();` 
This one works for single value. But if i do a foreach loop to get all the variation values. So I get a string like
`$values = "'ID1','ID2','ID3','IDn',"; `
`$test = Material::find()->where('in', 'Material.MaterialId' , [$value])->joinWith(['objectName'])->all();`
It Returns Nothing But If I use is like that 
`$test = Material::find()->where('in', 'Material.MaterialId' , [ID1','ID2','ID3','IDn',])->joinWith(['objectName'])->all();`
This gets me the required results. I have also tried the same using **or in where clause and orWhere method**, I guess all are having same problem.

**Comment by SilverFire** [comment]
Do you want to get condition `WHERE Material.MaterialId IN ('ID1','ID2','ID3','IDn')`? If yes, `$values` must be an array.
`$values = "'ID1','ID2','ID3','IDn',";` is incorrect for the IN condition.

**Comment by unclead** [comment]
This use case is described in documentation
> in: operand 1 should be a column or DB expression. Operand 2 can be either an array or a Query object. It will generate an IN condition. If Operand 2 is an array, it will represent the range of the values that the column or DB expression should be; If Operand 2 is a Query object, a sub-query will be generated and used as the range of the column or DB expression. For example, ['in', 'id', [1, 2, 3]] will generate id IN (1, 2, 3). The method will properly quote the column name and escape values in the range. The in operator also supports composite columns. In this case, operand 1 should be an array of the columns, while operand 2 should be an array of arrays or a Query object representing the range of the columns.

You use `IN` condition in wrong way as already said @SilverFire

**Comment by harshitchaudhary** [comment]
yeah that was the error actually I was considering it as a string in square braces, But as @SilverFire  said its an array, So its resolved now. Thanks a lot @SilverFire  and @unclead .

**Comment by harshitchaudhary** [comment]
`$materials = Material::find()->where(['in','Material.MaterialId', $value])->joinWith(['objectName'])->all(); 
	 		$product = Product::find()->where(['Product.productId'=>$id, 'Product.ModelId'=>$mid])->joinWith(['product'=>function($query){
	 			$query->joinWith(['objectName','contents'=> function($query2){
	 				$query2->joinWith(['material'=> function($query3){
	 					$query3->where(['in','Material.MaterialId', $value])->joinWith(['objectName']);
	 				}]);
	 			}])->all();
	 		}])->one();`

Okay I ran into the same error, or might be slightly different. 
My **query3** give an error that In expect two operands whereas if I supply the same onto material model its working fine but in Product Model its not working.

Moreover I want to addIntoCart the products and its addons (I call them in material object). Where as If i rewrite my **query3** as  
`$query3->where(['in','Material.MaterialId', ['ID1','ID2']])->joinWith(['objectName']);`

its working in a way it supposed to be. Also If I use ArrayHelper::toArray($value) It returns me null, Might be because the **$value array** is now subarray. I am very sure the $value is array. 

Any Suggestions ?

**Comment by SilverFire** [comment]
PHP is not JavaScript, that's why you do not have a `$value` inside an anonymous funciton. You should inherit `$value` from the parent scope all the way long through closures with `use ($value)`

The code bellow should work fine.

```php
<?php

$materials = Material::find()->where(['in','Material.MaterialId', $value])->joinWith(['objectName'])->all(); 

$product = Product::find()->where(['Product.productId'=>$id, 'Product.ModelId'=>$mid])->joinWith([
	'product' => function($query) { 
		$query->joinWith([
			'objectName', 
			'contents' => function($query2) { 
				$query2->joinWith([
					'material'=> function($query3) { 
						$query3->where(['in','Material.MaterialId', $value])->joinWith(['objectName']); 
					}
				]);
			}
		])->all(); 
	}
])->one();


```

Read the anonymous function in PHP manual: http://php.net/manual/en/functions.anonymous.php.

Please notice that this is not a support forum. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem. Next time try to debug and dig into problem, you will earn more knowledge and spend less time.
