### ISSUE TITLE
Add support for constructor params in component configuration.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10128]
In Yii2 Components no longer need to subclass a specific class and therefore any object can theoretically be used as an (application) component.
The DI container is used to instantiate the object and any of its dependencies, however via component configuration it is impossible to pass in any constructor arguments.

Support for this could simply be added by reserving a key in the component configuration array that is then used as 2nd param for the `Yii::createObject()` call and thus gets passed to the DI container appropriately.

The only possible BC break is if the key is already used by existing component configurations. We should be safe if we use something like "constructorArgs".

Example:

        'components' => [
            'test' => [
                'class' => MyCoolClass::class,
                'constructorArgs' => [1, "Test", False]
            ]
        ]

**Comment by SamMousa** [comment]
Note: there currently is a workaround using a closure as the definition, but the downside is that that bypasses the DI container altogether..

**Comment by klimov-paul** [comment]
Same as #7324
