### ISSUE TITLE
Copy Paste Link To Facebook Post Not Showing Image Thumbnail Image

### ISSUE THREAD

**Issue by MrAwanishKumar** [yiisoft/yii2#10126]
Hi, 

I have a specific requirement in a  project like count the user click rate on the posted link over social networking site (for now facebook.com only) and the count should store in my website database.
The actions are - 
1- I have generated the URL (redirect url to my website, when users click on the image) like this -
    e.g - 
Redirect URL -  http://splitmedia.in/receive?partnerLinkHash=xdZ2iOSv07rS-cN&userReferenceHash=bN19UFgRVdRS8JqkqAiu4WpCPoXEbJRYrsUowNIK-9XYfC4O-yzxY_HHoS1_2qIetWSpoQIs0hw

where partnerLinkHash & userReferenceHash is unique hash code generated for the user and link.

and the image thumbnail link which should show while posting to facebook like -
Image URL - https://bookmein.in/myAssets/images/xexp400.jpg.pagespeed.ic.6Ww3IaWPD9.jpg

Now 
When I post the redirect url to my facebook, the image url thumbnail should show and when click on this thumbnail it should redirect to the redirect url.
I tried this, but it could not work for me
example copy and paste this following link on facebook, it does not work - 
< link rel='shortlink' href='http://splitmedia.in/receive?partnerLinkHash=xdZ2iOSv07rS-cN&userReferenceHash=bN19UFgRVdRS8JqkqAiu4WpCPoXEbJRYrsUowNIK-9XYfC4O-yzxY_HHoS1_2qIetWSpoQIs0hw' src='https://bookmein.in/myAssets/images/xexp400.jpg.pagespeed.ic.6Ww3IaWPD9.jpg'/ >

Need help here - How can I achieve this.

Thanks

**Comment by Alex-Code** [comment]
Git is for bug tracking, not questions.
Please use the forums, http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/

**Comment by MrAwanishKumar** [comment]
Oh Sorry, my mistake. 

Thank you
