### ISSUE TITLE
Select some columns with 'joinWith' method.

### ISSUE THREAD

**Issue by kzweb** [yiisoft/yii2#10120]
I'm trying to get a record to joinWith, but selecting only some columns (those that need only), but does not work. If you remove the 'select' function normally

```php
$city = LocalizationCity::find()
            ->from(LocalizationCity::tableName() . ' city')
            ->select(['city.id', 'city.name'])
            ->joinWith([
                'state' => function ($query) {
                    $query->from(LocalizationState::tableName() . ' state');

                    $query->select(['state.id', 'state.name']);
                },
            ])
            ->orderBy('city.id DESC')
            ->andWhere(['city.id' => 3559])
            ->one();`
           
            var_dump($city->state); // show NULL, If you remove the 'select', displays the related model 'state'.
```

Thank you.

**Comment by Faryshta** [comment]
Thats because you need to include the id of the state on the select. Otherwise you are searching for a null state.

`->select(['city.id', 'city.name', 'city.state_id'])`

**Comment by kzweb** [comment]
News to me (laughs), I'm almost sure I did before without having to select the fk column. But thanks, it worked now.
