### ISSUE TITLE
Configure component property when calling

### ISSUE THREAD

**Issue by jomonkj** [yiisoft/yii2#10134]
is it possible ?
```
Yii::$app->component(['property'=>'value'])->method(['arg1'=>'value']);
```

**Comment by samdark** [comment]
No, it's not possible. What's your use case for it?

**Comment by jomonkj** [comment]
i want to change component property dynamically.like
```
$object1 = Yii::$app->component(['property'=>'value1'])->method(['arg1'=>'value1']);
$object2 = Yii::$app->component(['property'=>'value2'])->method(['arg1'=>'value1']);
```
component property is defined globally for application in configuration file. and that property is not configurable in component->method().




I don't know, this is good idea?

**Comment by samdark** [comment]
Why can't you do the following?

```php
Yii::$app->component->property = 'value';
Yii::$app->component->method(['arg1'=>'value1']);
```

**Comment by jomonkj** [comment]
ok, Thanks

**Comment by samdark** [comment]
Yes. Components are global. Also check guide section on Dependency Injection.
