### ISSUE TITLE
HttpCache isn't working - Doesn't set `Cache-Control`

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#10136]
I have a controller with a behavior to set the `Cache-Control` header, yet it is not working. It actively sets `Cache-Control` to `no-cache`, the opposite of what I want. 

```
$ curl -I http://localhost:81/shopwiz/web/shopping/test
HTTP/1.1 200 OK
Date: Wed, 11 Nov 2015 09:31:46 GMT
Server: Apache/2.4.16 (Unix) OpenSSL/1.0.2d PHP/5.6.12
X-Powered-By: PHP/5.6.12
Set-Cookie: PHPSESSID=cianqlr5nalvnobkg4poe5tvu4; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: _csrf=1b672292015c36ad3eb1596ead43b721e09dae5f8493b7b87ca04305c4538579a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22fVvkcT5yURR7V8xtH3z14NHnfdiVOojx%22%3B%7D; path=/; httponly
Content-Type: text/html; charset=UTF-8
```

```
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'httpCache' => [
              'class' => 'yii\filters\HttpCache',
              'sessionCacheLimiter' => 'public',
              'cacheControlHeader' => 'public, max-age=3600',
            ],
        ];
    }
```

http://stackoverflow.com/questions/33643204/how-do-i-turn-on-http-caching-in-yii2
http://www.yiiframework.com/doc-2.0/guide-caching-http.html#cache-control

I found out I'm not the only one experiencing this problem. 

http://stackoverflow.com/questions/31697510/yii2-httpcache-issue

Yii version 2.0.6.

**Comment by cebe** [comment]
which http server are you using? nginx/apache?

**Comment by cebe** [comment]
You have to configure at least one of `lastModified``or `etagSeed` properties. Specifying max-age does not make much sense without saying when the page was modified.

**Comment by cebe** [comment]
This is also the answer to the first question you linked: http://stackoverflow.com/a/33649011/1106908
