### ISSUE TITLE
Query builder incorrect handle of inside functions

### ISSUE THREAD

**Issue by Tomino2112** [yiisoft/yii2#10131]
Hi, Seems like query builder doesn't generate query correctly when using function inside of another function. 

Example code:

    Model::find()
        ->select('TRUNCATE(SUM(table.column)/100,2) as count')
        ->all();

This simple query runs SQL:

    SELECT TRUNCATE(SUM(table.column)/1000, `2)` AS `count` FROM `table`

As you can see, the problem is that it adds "``" around the parameter of the outer function

Correct SQL should be:

    SELECT TRUNCATE(SUM(table.column)/1000, 2) AS `count` FROM `table`

**Comment by klimov-paul** [comment]
Duplicates #8276

**Comment by Tomino2112** [comment]
Actually solution was easier than I thought, so for anyone landing here:

You can also write select as an array and that way the query is created correctly.

My example above would be:

    Model::find()
    ->select(['count'=>'TRUNCATE(SUM(table.column)/100,2)'])
    ->all();
