### ISSUE TITLE
Debug toolbar breaks when using DI in controller.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10148]
When using DI in controller action to insert the User application component, the debug toolbar breaks.

Think this is another instance of #5402.

Suppose I implement the `IdentityInterface` on my `User` model, which is an instance of `ActiveRecord`.
At that point, `yii\web\User::$_identity` will contain an AR model, which cannot be serialized, because it contains a `yii\db\Connection`, which contains a `PDO` object.

**Comment by SamMousa** [comment]
Traces this back to the RequestPanel, it uses Yii::$app->requestedParams, which also contains injected params, which may contain stuff that cannot be serialized.

Regardless of the source, yii2-debug could implement this:

        foreach ($this->module->panels as $id => $panel) {
            try {
                $panelData = $panel->save();
                serialize($panelData);
                $data[$id] = $panelData;
            } catch (\Exception $e) {

            }

        }

This reduces performance (serialization happens twice, one for each panel and once for all data.
But the advantage is that other panels will still work if the request panel breaks. (Note that not all panels are as forgiving as the request panel, and the log and database panel will still break when there is no data available. (This is something that should be fixed in the panels, since they are for debugging I think they should be forgiving and at least render a basic error).

Regardless of the fix to yii2-debug, `yii\db\Connection` should implement __sleep and close the connection before being serialized.

**Comment by samdark** [comment]
Could you submit a pull request for request panel and another separate one for connection? Thanks!

**Comment by SamMousa** [comment]
For the connection:
https://github.com/yiisoft/yii2/pull/10149

I chose to implement `__sleep()` instead of the `Serializable()` since that interface is a headache unless you deploy it across your whole class hierarchy.

**Comment by SamMousa** [comment]
Have looked into fixing this for the panels in general; however there is no simple way to know what data is required.
- For now i'm leaving this open but not spending more time on it, if anyone wants to take a stab at it, feel free!

**Comment by samdark** [comment]
Original issue solved. Closing it till next alike issue appears with concrete case.
