### ISSUE TITLE
Validator email Yii2

### ISSUE THREAD

**Issue by vorobyev** [yiisoft/yii2#10142]
class User extends \yii\base\Model 
{
...
 public function rules() 
    {
        return [
        ['email', 'email', 'message' => 'Invalid email'],
];
....
}

$model->validate() do not work with email max length. It may be 256 symbols. But when i input more then 256 symbols, it return, then email is valid. 
P.S. Sorry, i am russian =)

**Comment by unclead** [comment]
In `EmailValidator` the email is considered invalid if it is longer than 320 characters
https://github.com/yiisoft/yii2/blob/master/framework/validators/EmailValidator.php#L74

But I found the answer to the SO which states that the maximum length 254
http://stackoverflow.com/a/574698

**Comment by vorobyev** [comment]
It work only on the server side((

**Comment by SilverFire** [comment]
I guess 320 chars is:
 - 254 chars for the email address
 - other 66 chars for the recipient name (see `allowName` option)

It may be fixed to use different allowed length depending on `allowName` property, but it's not a serious problem.


> It work only on the server side((
@vorobyev what do you mean? Do you have problems with JS validation?

**Comment by vorobyev** [comment]
SilverFire, JS not check email length. Validation is go, when form is submitted. Other validations are normal work in the client side.

**Comment by SilverFire** [comment]
@vorobyev you're right, there is not length check on the client-side. See [yii.validation.js:188](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.validation.js#L188)

@samdark should it be fixed?

**Comment by samdark** [comment]
JavaScript length check could be added.

Allowed length could be corrected as well but we need to make sure. In that StackOverflow answer there are many good references including reference validator.

**Comment by cebe** [comment]
SO links to IETF RFCs errata so that is a good source to refer to. Should be checked in very detail though.

**Comment by SilverFire** [comment]
I'm handling this
