### ISSUE TITLE
Incorrect ip when user uses proxy

### ISSUE THREAD

**Issue by mohammadhosain** [yiisoft/yii2#10140]
`yii\web\Request::getUserIP` uses `REMOTE_ADDR` to get user ip.The problem with this is, that `$_SERVER['REMOTE_ADDR']` is not always reliable. What if the user is behind a proxy, and the IP is shown by `HTTP_X_FORWARDED_FOR` header?

**Comment by samdark** [comment]
Then you have to override the method in your own class and make sure your proxy isn't forwarding `X-Forwarded-For` HTTP header. Reading IP from `X-Forwarded-For` by default is a security flaw.
