### ISSUE TITLE
Yii::$app->request->getCsrfToken() sets _csrf cookie when it's not supposed to

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#10141]
The documentation says it will just return the string. It's not supposed to set the cookie, unless the parameter is true. The default is false. 

```
  <?//= Html::csrfMetaTags() // sets _csrf cookie. prevents Fastly CDN caching. ?>
  <?php 
    $this->registerMetaTag(['name' => 'csrf-param', 'content' => '_csrf']);
    $this->registerMetaTag(['name' => 'csrf-token', 'content' => 'xxx']);
    Yii::$app->request->getCsrfToken(false);
  ?>
```

Will set the `_csrf` cookie no matter what! 

```
$ curl -I http://localhost:81/shopwiz/web/shopping/search?q=toaster
...
Set-Cookie: _csrf=ac48de0a55b72be4d5dc94aaf14b1db6f8fa879e0f277c327d49b355ed51ed2da%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%223JZXcJeh0JFdPKNyvB46FgN-OC5NZXKt%22%3B%7D; path=/; httponly
```

When you comment out `//    Yii::$app->request->getCsrfToken(false);` then it works and doesn't set the cookie, but then you can't get the token!

http://www.yiiframework.com/doc-2.0/yii-web-request.html#getCsrfToken()-detail

Yii version 2.0.6.

**Comment by samdark** [comment]
The whole idea of the token is that it's regenerated.
