### ISSUE TITLE
RangeValidator does not support array-like objects.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10154]
RangeValidator allows for validating subsets via the allowArray param.

It would be ideal, and perhaps logical, if it would have better support for other enumerable types.
For example:
- `\Traversable`
- `\yii\base\Arrayable`

This would allow stronger validation without ever affecting users that only store request data in it, since that data is limited to strings / (arrays of)* strings.

Practical, I have an AR model that uses a custom built Map object. This object is serializable to the database, but I can't validate it's values because it does not pass is_array. (It does however implement both `Traversable` and `Arrayable`.

I can make a PR with appropriate tests if you agree this would be nice to have.

**Comment by samdark** [comment]
Do it.

**Comment by SamMousa** [comment]
Okay, have started on this, creating the tests first.

Question: Currently, allowArray specifically checks for the array type; but what people actually mean is allow subset, should we change that?

Example: 

        'a' is in ['a', 'b'] -- works
        ['a'] is a subset of ['a', 'b'] -- works with allow array
        ['a'] is in [['a'],['b']] -- fails always

To me it seems a more appropriate name or meaning would be `$allowSubset`, regardless of the name, shouldn't the last case validate?

Also, should we validate non-array values if `$allowArray` is set to `true`? If we add support for array-like objects but allow both match types (subset, in), this will make it hard(er) to decide if we are doing a subset match (ie should iterate the array-like value) or an element match, in case there is no need to iterate over the array-like object.

Thoughts?

**Comment by samdark** [comment]
We can't change the name because of backwards compatibility.

**Comment by samdark** [comment]
Subset meaning is a bit vague. I'd be explicit.

**Comment by SamMousa** [comment]
I think set theory defines subsets quite explicitly.. Anyway what features
/ approach do you want?

**Comment by samdark** [comment]
I've got it wrong :)

Last case from your example definitely should be valid.

**Comment by SamMousa** [comment]
Have implemented this, moved most of the checking to `ArrayHelper` to allow it to be reused.
This significantly simplifies `RangeValidator`.

One scenario I'm not entirely sure how to handle:
1. `$allowArray = true`.
2. value is an array.
3. range is an array.

Since we allow array values, but not require them, it is ambiguous what we need to check:

        $val = new RangeValidator([
            'range' => [['a', 'b', 'c', 'd']], ['b']],
            'allowArray' => true
        ]);
        $val->validate(['a','b','c','d']) // Should return true.

When checking the above code, we do not know whether to interpret `['a','b','c','d']` as 1 array value(`in`), or as 4 string values(`subset`). 
I have chosen to always try subset first, and if that fails try `in`. --> In an ideal world we would not have "allow" array, but a stricter "use" array but we can't change that because of BC.

Feedback please!

**Comment by samdark** [comment]
One value looks more logical since both are arrays but you're right that it's confusing on how to do it because of how it works currently.

**Comment by SamMousa** [comment]
@samdark So then my currently proposed information looks good? --> I still need to do the minor refactorings @SilverFire proposed obviously, but other than that and adding a line to the changelog no changes required?

**Comment by samdark** [comment]
Yes. It's looking good.

**Comment by SamMousa** [comment]
Have added some more test and added the changes from @SilverFire, I think it's ready for merge ;-)

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/22d999728174b1c29af111c53ad487717b90c2fa
