### ISSUE TITLE
Allow setting css options per CSS file in AssetBundle::$css

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2#10158]
Situation : I need to register two CSS files in my asset bundle, `screen.css` for media="screen" and `print.css` for media="print". 

As far as I can see, the only way to do this for now is to call $view->registerCssFile() by hand when registering my assets, for my print.css file and pass the options in the second parameter.

I would find it better and simpler if I could specify the options in the AssetBundle::$css property like this:

```php
public $css = [
    'screen.css',
    ['print.css', 'media' => 'print'],
];
```

No BC break would be introduced by accepting an array as a $css entry type..

Any blockers?

**Comment by samdark** [comment]
Currently it's possible to do it by using separate asset bundle for print media type. I'm not sure it should be changed.

**Comment by machour** [comment]
You're right, I didn't see it that way.
But it still requires me to add a new class to switch a simple media attribute..

**Comment by machour** [comment]
Actually, I need 3 AssetBundle for what I'm trying to achieve, not 2.
I'm redoing this page head section: http://petstore.swagger.io/ 

```html
  <link href='css/typography.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/screen.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='print' rel='stylesheet' type='text/css'/>
  <link href='css/print.css' media='print' rel='stylesheet' type='text/css'/>
```

The `reset.css` file is to be used for both media screen and media print, but the problem is that the AssetManager only generate the <link> tag once for this file, even if it's present in both AssetBundle and using different media :

```php
class SwaggerUiAsset extends AssetBundle
{
    public $sourcePath = '@bower/swagger-ui/dist';
    public $css = [
        'css/typography.css',
        'css/reset.css',
        'css/screen.css',
    ];
}
class SwaggerUiPrintAsset extends AssetBundle
{
    public $sourcePath = '@bower/swagger-ui/dist';

    public $css = [
        'css/reset.css',
        'css/print.css',
    ];

    public $cssOptions = [
        'media' => 'print',
    ];
}
```
produces:
```html
<link href="/assets/6d4f3aa2/css/typography.css" rel="stylesheet">
<link href="/assets/6d4f3aa2/css/reset.css" rel="stylesheet" media="print">
<link href="/assets/6d4f3aa2/css/screen.css" rel="stylesheet">
<link href="/assets/6d4f3aa2/css/print.css" rel="stylesheet" media="print">
```
which makes `reset.css` unavailable for the screen media

So what I have to do for now is to declare 3 assets like this:

```php
class SwaggerUiAsset extends AssetBundle
{
    public $sourcePath = '@bower/swagger-ui/dist';
    public $css = [
        'css/reset.css',
    ];
}
class SwaggerUiScreenAsset extends AssetBundle
{
    public $sourcePath = '@bower/swagger-ui/dist';
    public $css = [
        'css/typography.css',
        'css/screen.css',
    ];
    public $cssOptions = [
        'media' => 'screen',
    ];
}
class SwaggerUiPrintAsset extends AssetBundle
{
    public $sourcePath = '@bower/swagger-ui/dist';

    public $css = [
        'css/print.css',
    ];

    public $cssOptions = [
        'media' => 'print',
    ];
}
```
in order to have `reset.css` available for both medias type.

Now imagine I also want to add a CSS specific for the `tv` media type, and not use `reset.css` when on TV.. I would need 4 AssetBundles classes!

In this case, with just one asset bundle and my proposed change I would simply do:

```php
class SwaggerUiAsset extends AssetBundle
{
    public $sourcePath = '@bower/swagger-ui/dist';
    public $css = [
        ['css/reset.css', 'media' => 'print, screen'],
        ['css/typography.css', 'media' => 'screen'],
        ['css/screen.css', 'media' => 'screen'],
        ['css/print.css', 'media' => 'print'],
        ['css/tv.css', 'media' => 'tv'],
    ];
}
```

and that would be it.

**Comment by samdark** [comment]
Yeah. In this case it makes sense.

**Comment by machour** [comment]
Added a PR for this.
The behavior is to override $cssOptions to enable the user from setting global options if needed.

I'm wondering if the same change should be implemented for $js and $jsOptions as well for consistency sake.. should I ?

**Comment by SilverFire** [comment]
What kind of JS options can be used?

**Comment by machour** [comment]
Changing the type, or using "defer" or "async"

**Comment by samdark** [comment]
Yes, it should be available for JS as well.
