### ISSUE TITLE
Yii2 2.0.7 ,

### ISSUE THREAD

**Issue by zxczxc12** [yiisoft/yii2#10152]
Yii2 2.0.7 , Linux Centos 6
Nginx + Apache

[notice] child pid 16684 exit signal Segmentation fault (11)

2.0.6 - all ok

( целый день промаялся выяснением почему перестало все работать, пока жестко не прописал 2.0.6. В текущем, самом последнем варианте, Yii2 2.0.7 ложит апачевский процесс на ровном месте  )

**Comment by SilverFire** [comment]
```
nginx -v
apachectl -V
php -v
php -m
```

**Comment by zxczxc12** [comment]
nginx version: nginx/1.7.3

Server version: Apache/2.2.31 (Unix)
Server built:   Aug 18 2015 07:09:23
Server's Module Magic Number: 20051115:40
Server loaded:  APR 1.3.9, APR-Util 1.3.9
Compiled using: APR 1.3.9, APR-Util 1.3.9
Architecture:   64-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/usr/local/apache"
 -D SUEXEC_BIN="/usr/local/apache/bin/suexec"
 -D DEFAULT_PIDLOG="logs/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="logs/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="/etc/httpd/mime.types"
 -D SERVER_CONFIG_FILE="/etc/httpd/httpd.conf"

 php -v
PHP 5.5.30 (cli) (built: Oct  6 2015 12:54:07)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.18,



 php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
ereg
fileinfo
filter
gd
gettext
hash
iconv
imap
intl
ionCube Loader
json
libxml
mbstring
mcrypt
memcached
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]
the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured)




Nginx , Apache and PHP has been compiled myself

Nginx:
configure arguments: --with-http_ssl_module --with-pcre --with-http_perl_module --with-http_realip_module --with-http_flv_module --with-file-aio

Apache:
/configure --enable-rewrite --enable-so --sysconfdir=/etc/httpd --prefix=/usr/local/apache

PHP:
./configure'  '--with-apxs2=/usr/local/apache/bin/apxs' '--enable-intl' '--with-mhash' '--enable-mbstring' '--with-mysql=/usr/local/mysql/' '--with-pdo-mysql=/usr/local/mysql/' '--enable-zip' '--enable-bcmath' '--with-xmlrpc' '--with-iconv' '--enable-session' '--with-freetype-dir' '--enable-cgi' '--with-mcrypt' '--with-gd' '--with-zlib' '--with-openssl' '--enable-soap' '--with-curl' '--with-jpeg-dir=/usr/local/lib/' '--with-png-dir=/usr/local/lib/' '--with-imap=/usr/local/src/imap-2007f' '--with-imap-ssl' '--with-kerberos' '--enable-pcntl' '--enable-roxen-zts' '--enable-sockets' '--with-gettext' '--with-mysqli=mysqlnd'

**Comment by SilverFire** [comment]
Окей, софт на первый взгляд выглядит неплохо.

Travis на тестах не выпадает в Segfault, потому нам нужна ваша помощь. Чтобы сделать сегфолт воспроизводимым, нужно найти, что его вызывает. Попробуйте собрать дамп памяти при краше. Есть хорошая русскоязычная статья на хабре: http://habrahabr.ru/company/bitrix/blog/153001/

Рекомендуется, чтобы PHP был собран с `--with-debug`, но можно попробовать хотя бы так.

**Comment by zxczxc12** [comment]
Предлагаю сделать по другому .
Я дам рута на сервак и настрою окружение при котором такое получается 
Скайп vasilevs57

**Comment by SilverFire** [comment]
@zxczxc12 ок, ща напишу

**Comment by SilverFire** [comment]
Воспроизвелось только в том окружении:

```php
public function actionCrash() {
    echo Inflector::transliterate('any string');
}
``` 

Стоит старый ICU и нет ICU Data.
```
php --info | grep ICU 
ICU version => 4.2.1
```

GDB Backtrace:
```
#0  0x0000000000af564b in zend_std_object_get_class (object=0x7f6c2d2e93e8)
    at /usr/local/php-5.5.30/Zend/zend_object_handlers.c:1502
#1  0x0000000000abe5c0 in zend_get_class_entry (zobject=0x7f6c2d2e93e8)
    at /usr/local/php-5.5.30/Zend/zend_API.c:238
#2  0x0000000000b0c07d in ZEND_CATCH_SPEC_CONST_CV_HANDLER (execute_data=0x7f6c35e67ec0)
    at /usr/local/php-5.5.30/Zend/zend_vm_execute.h:7112
#3  0x0000000000afd8a6 in execute_ex (execute_data=0x7f6c35e67ec0)
    at /usr/local/php-5.5.30/Zend/zend_vm_execute.h:363
#4  0x0000000000afd929 in zend_execute (op_array=0x7f6c35e9f7a0)
    at /usr/local/php-5.5.30/Zend/zend_vm_execute.h:388
#5  0x0000000000abd103 in zend_execute_scripts (type=8, retval=0x0, file_count=3)
    at /usr/local/php-5.5.30/Zend/zend.c:1327
#6  0x0000000000a25880 in php_execute_script (primary_file=0x7fff168baa40)
    at /usr/local/php-5.5.30/main/main.c:2525
#7  0x0000000000b70571 in do_cli (argc=3, argv=0x2e24020)
    at /usr/local/php-5.5.30/sapi/cli/php_cli.c:994
#8  0x0000000000b71606 in main (argc=3, argv=0x2e24020)
    at /usr/local/php-5.5.30/sapi/cli/php_cli.c:1378
```

**Comment by samdark** [comment]
Не уверен, что мы можем это решить на стороне Yii...

**Comment by SilverFire** [comment]
Согласен. Предлагаю закрыть.

**Comment by zxczxc12** [comment]
Обновление пакета icu решило вопрос 
yum update icu
