### ISSUE TITLE
DB Reconnect

### ISSUE THREAD

**Issue by nsanden** [yiisoft/yii2#10168]
I have a script that runs queries, sleeps, then tries to run some more queries. After the sleep though it always gives "Mysql has gone away" error. Same issue as here (for codeigniter) https://www.adherewebdesign.com/solving-mysql-server-has-gone-away-errors-in-codeigniter/

They solve it with $this->db->reconnect();

Do we need a similar method in Yii DB?

**Comment by samdark** [comment]
There are already `close()` and `open()` methods in `Connection`. Also it's much better idea to tell MySQL to hold connection a bit longer instead of re-connecting and repeating queries:

```php
SET SESSION wait_timeout = 18000;
```

It sets timeout per connection so it is effective only for that request or console command run.

**Comment by nsanden** [comment]
I tried `open()` and it did not do anything. Will try `wait_timeout` thanks.

**Comment by SilverFire** [comment]
`open()` checks that connection exists, but does not check whether it's alive.

**Comment by nsanden** [comment]
Right @SilverFire, that's what i thought I saw as well when i checked source

**Comment by tom--** [comment]
@samdark What hook do I use to make sure `SET SESSION wait_timeout = 18000;` is sent whenever a connection opens?

**Comment by samdark** [comment]
By using `Connection::EVENT_AFTER_OPEN`.

**Comment by AnatolyRugalev** [comment]
I solved this problem with adding "gc" event to application and binding to it some important jobs like connection close, logs flush and memory caches flush. Event triggers when queue worker goes into standby mode (no jobs currently executing).

@samdark, what do you think about adding event like that to the core? DB component may bind its close() method to it, for example

**Comment by samdark** [comment]
What did you have to extend to add gc event?

**Comment by thrieu** [comment]
@AnatolyRugalev Could you please share it?

**Comment by AnatolyRugalev** [comment]
Config:
```php
'on gc' => function(\yii\base\Event $event) {
    $app = $event->sender;
    $app->db->close();
    $app->redis->close();
}
```

I use modified `QueueBusController` from `trntv/yii2-command-bus` as queue workers. The main idea is to call GC every time when workers goes idle

```php
Yii::$app->trigger('gc');
```

After all, when I write my own components with memory cache or connection opens, I bind `close()` methods and memory clean on applications' GC event:

```php
public function init() {
    Yii::$app->on('gc', [$this, 'gc']);
    Yii::$app->on('gc', [$this, 'close']);
}
```

If you interested, I can provide you full controller code, but I need to clean it

**Comment by AnatolyRugalev** [comment]
And my question was about adding new event `EVENT_GC` to Yii core and binding to it `close()` methods in database components by default.

**Comment by artamonovdev** [comment]
```
try{
                \Yii::$app->db->createCommand("DO 1")->execute();
            }catch (\yii\db\Exception $e){
                \Yii::$app->db->close();
                \Yii::$app->db->open();
            }
```
