### ISSUE TITLE
Error 'Array to string conversion' in Html::div

### ISSUE THREAD

**Issue by yenidai** [yiisoft/yii2#10164]
Download Yii 2.0.6 (advanced application template )
Put this code somewhere in main.php in frontend

`echo Html::tag('div',['class' => 'hr-full']); `

You get error 'Array to string conversion' in '\vendor\yiisoft\yii2\helpers\BaseHtml.php'

**Comment by Alex-Code** [comment]
Please check documentation first.
http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#tag()-detail

`Html::tag` expects the 2nd parameter to be a string, I'm guessing you want `Html::beginTag`.
http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#beginTag()-detail

**Comment by yenidai** [comment]
It is possible to use code like this ?
    public static function tag($name, $content = '', $options = [])
    {        		
		if(is_array($content) && empty($options)){
			$html = "<$name" . static::renderTagAttributes($content) . '>';	
			return isset(static::$voidElements[strtolower($name)]) ? $html : "$html</$name>";
		}			
		else{
			$html = "<$name" . static::renderTagAttributes($options) . '>';
			return isset(static::$voidElements[strtolower($name)]) ? $html : "$html$content</$name>";
		}			
    }

**Comment by Alex-Code** [comment]
Just provide an empty string,
```php
echo Html::tag('div', '', ['class' => 'hr-full']);
```
