### ISSUE TITLE
Yii::powered is not using Yii::t

### ISSUE THREAD

**Issue by hugodiniz** [yiisoft/yii2#10170]
The function Yii:powered is not translated as in version 1.

**Comment by derekisbusy** [comment]
You can translate it in your view files using `Yii::t('app', Yii::powered())`

**Comment by SamMousa** [comment]
@derekisbusy That will not add the string to the translation file (since it can't resolve Yii::powered() when doing a simple parse).

**Comment by hugodiniz** [comment]
Thank you

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/10178

**Comment by SamMousa** [comment]
Done, this can be merged as far as I see

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/6d7627c2a51690175875fb8f21d444a3fb656ba6
