### ISSUE TITLE
Order by viaTable field

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#10174]
Is it possible to order by a field in the viaTable statement?

I've tried this, but without luck:
```php
$this->hasMany(Picture::className(), ['PictureID' => 'PictureID'])
	->viaTable('ArticlePictureRelation', ['ArticleID' => 'ArticleID'], function($query) {
		/* @var $query \yii\db\ActiveQuery */
		$query->orderBy(['position' => SORT_ASC]);
	});
```

**Comment by arogachev** [comment]
@thejahweh Please use forum to ask such questions. This is issue tracker. By the way, this question is answered on StackOverflow [here](http://stackoverflow.com/questions/27690401/activerecord-where-and-order-on-via-table/27691992#27691992).

**Comment by thejahweh** [comment]
I've asked it here, because there is no solution. The StackOverflow Answer does not work and is not really an answer to this question.

This is also a common problem on such n:m relations with attributes in the table between which is not solved.

**Comment by thejahweh** [comment]
So if this case isn't supported it would mean that a CMS-like navigation-table with multiple navigations and custom orders isn't possible.

```
Nav1
- Point1
- Point2
Nav2
- Point3
- Point1

**Comment by samdark** [comment]
How does it fail in your case? Which are SQL queries generated?

**Comment by thejahweh** [comment]
It doesn't work because it generates two queries.
1 which gives the id's of the pictures:
```
SELECT * FROM ArticlePictureRelation WHERE id=123 ORDER BY position
```

2 uses the ids from above:
```
SELECT * FROM Picture WHERE id in (123, 456, 789)
```
The second one can't respect the order by of the first one.

**Comment by FabrizioCaldarelli** [comment]
Why don't you use a joinWith ?

**Comment by cebe** [comment]
@thejahweh please provide the schema for the involved tables.

**Comment by thejahweh** [comment]
Ok I see it is a bit more complicated. It would maybe work with `joinWith` but the needed model does not know about his relation with the current model.

```
Article
- id
ArticleContentRelation
- contentID
- articleID
- position
Picture
- id
- active
PictureVariant
- pictureID
- language
- title
```
The ArticleContentRelation->`contentID` is related to Picture->`id`. The `contentID` can be related to another table and the `id` of the picture too, this is why the picture does not know about his relation. 

This means there are other relations like this:
```
Person
- id
PersonContentRelation
- contentID
- personID
- position
Document
- id
- active
DocumentVariant
- documentID
- language
- title
```

The database isn't from me, so I have to live with it.

**Comment by thejahweh** [comment]
So I've managed it to work, here is my solution:
```php
$variantClass = PictureVariant::className();
$contentClass = Picture::className();
$relationClass = ArticleContentRelation::className();
$language = null;
$fallback = null;
/* @var $variantClass ActiveRecord */
/* @var $contentClass ActiveRecord */
/* @var $relationClass ActiveRecord */
$contentPrimary = $contentClass::primaryKey()[0];
$primaryKey = self::primaryKey()[0];
if ($language === null) $language = strtoupper(substr(Yii::$app->language, 0, 2));
$variantenQuery = Yii::createObject(ActiveQuery::className(), [$variantClass,
	'link' => [$contentPrimary => 'contentID']
]);
/* @var $variantenQuery Query */
$variantenQuery
	->select([
		new Expression('TOP 1 *'),
		'pref' => 'CASE [language]
			WHEN :language THEN 2
			WHEN :fallback THEN 1
			ELSE 0 END'
	])
	->addParams([
		':language' => $language,
		':fallback' => $fallback
	])
	->from($variantClass::tableName())
	->where([$variantClass::tableName().'.['.$contentPrimary.']' => new Expression('[ContentTable].['.$contentPrimary.']')])
	->orderBy(['pref' => SORT_DESC]);
/* @var $query \yii\db\ActiveQuery */
$query = $variantClass::find();
$query->primaryModel = $this;
$query->link = [$primaryKey => $primaryKey];
$query->multiple = true;
$query->from = ['RelationTable' => $relationClass::tableName()];
$query->select('*');
$query->join('INNER JOIN', ['ContentTable' => $contentClass::tableName()], '[ContentTable].'.$contentPrimary.' = [RelationTable].contentID');
$query->join('CROSS APPLY', ['VariantenTable' => $variantenQuery]);
```
I had to put the Query together on my own.

And this is the generated SQL:
```sql
SELECT 
	* 
FROM 
	[ArticleContentRelation] [RelationTable] 
	INNER JOIN [Picture] [ContentTable] ON [ContentTable].PictureID = [RelationTable].ContentID 
	CROSS APPLY (
		SELECT TOP 1 *, 
			CASE [language] 
			WHEN 'EN' THEN 2 
			WHEN NULL THEN 1 
			ELSE 0 END AS [pref] 
		FROM [PictureVariant] 
		WHERE [PictureVariant].[PictureID]=[ContentTable].[PictureID] 
		ORDER BY [pref] DESC
	) [VariantTable] 
WHERE
	[RelationTable].[ArticleID]=64107
```

**Comment by thejahweh** [comment]
One problem is, that it does not work with `with` on a query:
```php
$query->with(['pictureVariants'])->all();
```
which gives me:
```
Getting unknown property: app\models\PictureVariant::ArticleID
```
This is maybe because Yii2 does not know about the tables in between the `Article` and the `Picture` objects and can't link them together.

But maybe someone has a better or more Yii2-like solution. :heart_eyes:

**Comment by degibons** [comment]
**Unfortunately**, **the problem** with sorting by field in junction table **is still exist**. 
For example we have three tables:
```
item:

| id | title  | 
---------------
| 1  |  dog   |
| 2  |  cat   |

item_has_value:

| item_id | value_id | rate |
-----------------------------
| 1       | 1        | 100  |
| 1       | 2        | 200  |
| 2       | 3        | 200  |
| 2       | 4        | 100  |

value:

| id | title  | 
---------------
| 1  |  bow   |
| 2  |  wow   |
| 3  |  mew   |
| 4  |  miaow |

```
And these relations:

```php
Item Model:

public function getValues()
{
        return $this->hasMany(Value::class, ['id' => 'valueId'])->via('itemValues');
}

public function getItemValues()
{
        return $this->hasMany(ItemHasValue::class, ['itemId' => 'id'])->orderBy(['rate' => SORT_DESC]);
}
```
And query to get linked values (properly sorted by `rate` field in juction table):
```php
... ->getItems()->with('values')->...
```
**It fails**, because the `orderBy` applies only in the first sql query (as it mentioned in https://stackoverflow.com/questions/27690401/activerecord-where-and-order-on-via-table/27691992#27691992).

But if we add these relation in `ItemHasValue` model:
```php
ItemHasValue Model:

public function getValue()
{
        return $this->hasOne(Value::class, ['id' => 'valueId']);
}
```

And perform these query:
```php
... ->getItems()->with([
    'itemValues' => function($query) {
                $query->with('value');
            },
])->...
```
It will sort related values properly.

So, question is - why does it happens, and why we can't sort properly by junction table field?
Maybe it is possible (in `via / viaTable` relations with sort) to add to the second query something like this: `... ORDER BY FIELD(id, 2, 1, 3, 4) ...` or sort it internaly?

**Comment by samdark** [comment]
@degibons please report separately instead of commenting on long-ago closed issue. This way your message would be lost.
