### ISSUE TITLE
Enhancement: Add Validation to yii\db\Command\batchInsert()

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#10175]
It is common to perform data validation before batch-inserting them as in importing data from an external source. It would be more efficient to perform data validation inside `batchInsert()` while looping through the data. An optional `$modelClass` or `$validationClass` string|object parameter could be used for validation. The resulting errors could be either collected and returned in an indexed array referring to row number and array of errors, or an exception thrown. An `$throwException` boolean argument could be used to choose between both.

**Comment by SilverFire** [comment]
`batchInsert()` is a command, that is not related to ActiveRecord, therefore it mustn't know anything about validation.
SO has a good answer for this problem http://stackoverflow.com/questions/27355262/activerecord-batch-insert-yii2
