### ISSUE TITLE
Enhancement: Add Prefix, Suffix, extraColumns, closure to yii\db\Command\batchInsert()

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#10173]
This suggestions aim to enable further processing of the data passed to batchInsert() before execution. For example, to add auditing data (`created_at`, `created_by`, `updated_at`, `updated_by`) to each data row. Currently the data array needs to be processed before passing it to `batchInsert()`. It would be more efficient perform this processing within the same loop inside `batchInsert()`. My suggestions are:
- Add `$prefix` and `$suffix` parameters to `batchInsert()` as arrays that are prepended  and appended to each data row while looping. The resulting row should match the array passed in `$columns`. Or use `$extraData` instead to be appended to each row.
- Use a closure to processes each row. It can exceed the above approach to add dynamic data such as a dynamically-generated product code or calculated value or even perform validation.

The closure approach is better because it's more generic and flexible but it would be good to have the two approaches together.

**Comment by SilverFire** [comment]
There is no reason to over-complicate `batchInsert()`. You can prepare data as you wish before calling `batchInsert()`.
