### ISSUE TITLE
ActiveForm hidden input shows label

### ISSUE THREAD

**Issue by it3rmit** [yiisoft/yii2#10185]
If I write 
```php
$form = ActiveForm::begin();
echo $form->field($model, 'field')->hiddenInput()
```
I am getting the label. I can't imagine cases, when this is needed. I suppose, that everybody expects the field become invisible for user. If I add empty label
```php
echo $form->field($model, 'field')->hiddenInput()->label('')
```
it still books some extra line and leaves it blank.

**Comment by SilverFire** [comment]
`echo $form->field($model, 'field')->hiddenInput()->label(false)`

Duplicates #2990, #2391, #4215 and many others. Try to search next time, please
