### ISSUE TITLE
Guide 2.0 links to articles of other databases not work

### ISSUE THREAD

**Issue by iCloud** [yiisoft/yii2#10189]
Working with Databases
----------------------

* [Sphinx](https://github.com/yiisoft/yii2-sphinx/blob/master/docs/guide/README.md)
* [Redis](https://github.com/yiisoft/yii2-redis/blob/master/docs/guide/README.md)
* [MongoDB](https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/README.md)
* [ElasticSearch](https://github.com/yiisoft/yii2-elasticsearch/blob/master/docs/guide/README.md)

All of them doesn't work in guide. 
All these lead to:
http://www.yiiframework.com/doc-2.0/guide-README.html

**Comment by SilverFire** [comment]
Duplicates #9922
