### ISSUE TITLE
eager loading with REST does not return relational data

### ISSUE THREAD

**Issue by jpodpro** [yiisoft/yii2#10180]
when performing a query with relational data and eager loading such as
```
$query = Track::find()
            ->with('owners')
            ->where( ['public' => 1] )
            ->orderBy( ['creation_date' => SORT_DESC] )
            ->limit( 10 )
            ->all();
```
the relational data is not returned in the resulting JSON object.

**Comment by SilverFire** [comment]
Did you try `->asArray()->all()`?

**Comment by jpodpro** [comment]
with the hours of searching you'd think that this could have been easier to find. FFS.

**Comment by SilverFire** [comment]
Could you show `var_dump($query)` and the resulting JSON?

**Comment by jpodpro** [comment]
your asArray() suggestion worked. i spent hours crawling the web for a solution and nowhere is anything like this posted. thanks.

**Comment by SilverFire** [comment]
@samdark is it an expected behavior?

**Comment by SilverFire** [comment]
Checked once more. Yes, it is.

**Comment by samdark** [comment]
Yes. It's expected: http://www.yiiframework.com/doc-2.0/guide-rest-resources.html

**Comment by jafaripur** [comment]
Also issue with ActiveDataProvider. With this we can't use asArray()!!
