### ISSUE TITLE
Here is a screen shot so you can help me fix my problem

### ISSUE THREAD

**Issue by 236286** [yiisoft/yii2#10184]
I did these steps:
1) curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
2) composer global require "fxp/composer-asset-plugin:~1.1.0"
3) composer create-project --prefer-dist yiisoft/yii2-app-basic basic

After that, I had a problem

Here is a screen shot so you can see the problem I am having:

![2015-11-18-180428_1280x1024_scrot](https://cloud.githubusercontent.com/assets/12777801/11240228/3639ea7e-8e1b-11e5-91f2-647fc28fb3a8.png)

Can you help me fix my problem?

**Comment by samdark** [comment]
Please use forums/gitter/irc for questions.

**Comment by githubjeka** [comment]
I tried help him but but nothing helps
https://github.com/francoispluchino/composer-asset-plugin/issues/163

**Comment by samdark** [comment]
https://github.com/francoispluchino/composer-asset-plugin/pull/158
