### ISSUE TITLE
Yii serve

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#10193]
When i entry ctrl+c after run "yii serve" and i run "yii serve" again it not works!

it happen because unlink function not run after execute passthru command in this [line](https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/ServeController.php#L91)

@samdark  why do you use $lock in this line?

Pd: it is testing in windows 7 with yii 2.0.7

**Comment by samdark** [comment]
Hmm... that's bad. Possible solutions:

1. Do it in `__destruct()`.
2. Do it in shutdown function.
3. We can probably simplify command by removing lock file at all checking `isAddressTaken` only.

**Comment by pana1990** [comment]
laravel use 3º option, it is best option imho.

**Comment by samdark** [comment]
Done.

**Comment by samdark** [comment]
Thanks!
