### ISSUE TITLE
Composer version at 2015-11-19 17:42:08 does strange

### ISSUE THREAD

**Issue by ivan-chkv** [yiisoft/yii2#10194]
$ ../composer.phar --version
Composer version 1.0-dev (dbcf8cae1384dfc5acab5ec1d07d43580d326a48) 2015-11-19 17:42:08
$ ../composer.phar update
...
$ ls -l vendor/bower
total 0
drwxr-xr-x  8 programmer  staff  272 20 ноя 09:26 bower-asset
$ ls -l vendor/bower/bower-asset
total 0
drwxr-xr-x  13 programmer  staff  442 20 ноя 09:26 bootstrap
drwxr-xr-x   6 programmer  staff  204 20 ноя 09:26 jquery
drwxr-xr-x   5 programmer  staff  170 20 ноя 09:26 jquery.inputmask
drwxr-xr-x   7 programmer  staff  238 20 ноя 09:26 punycode
drwxr-xr-x  19 programmer  staff  646 20 ноя 09:26 typeahead.js
drwxr-xr-x  10 programmer  staff  340 20 ноя 09:26 yii2-pjax

WTF

**Comment by samdark** [comment]
Do you have the following in your composer.json? https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L49

**Comment by samdark** [comment]
Overall it doesn't seem to be Yii issue.
