### ISSUE TITLE
getLastUpdatedID: Does the function exists?

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#10191]
```php
$query = \Yii::$app->db->createCommand()
        ->update(self::tableName(), ['status'=>self::STATUS_ACTIVE_ID], 'status = :status and dt_start < now()', ['status'=>self::STATUS_ACEPTED_ID])
        ->execute();
        //I need to get last updated IDs for the next chaned operations
        //Does the function exists? Because the PostgreSQL can do that as well as 1-2-3 via returning 
```

**Comment by SilverFire** [comment]
`getLastInsertID()` in Yii2 implements [PDO method](http://php.net/manual/en/pdo.lastinsertid.php) and there is no `getLastUpdateID()` in PDO since not all the DBMS support this feature.

If you work only with PgSQL, you can do the following:

```php
$query = \Yii::$app->db->createCommand()
        ->update(self::tableName(), ['status'=>self::STATUS_ACTIVE_ID], 'status = :status and dt_start < now() RETURNING id', ['status'=>self::STATUS_ACEPTED_ID])
        ->queryColumn();
```

**Comment by nineinchnick** [comment]
`RETURNING` is used in `Schema::insert()`, it makes sense to add `Schema::update()`.

**Comment by SilverFire** [comment]
Hm... Maybe. @samdark ?

**Comment by samdark** [comment]
@nineinchnick we won't be able to wire that into command in 2.0 anyway because of backwards compatibility.

**Comment by nineinchnick** [comment]
@samdark it would be a new method for the `Schema` classes, same as `insert` wasn't accepted in `Command`.

**Comment by samdark** [comment]
OK. I'd like to see a draft for it to make a decision.

**Comment by klimov-paul** [comment]
I am closing this issue as not genral one.
Also, the only way to fix it is usage of `RETURNING` statement, which is not supported by many DBMS.
In case you need such feature you should implement it inside your project or compose into a separated extension.
