### ISSUE TITLE
DI application component

### ISSUE THREAD

**Issue by imstd** [yiisoft/yii2#10197]
Hi. I am creating application component (service) and added dependency to it by constructor.
<code>public function __construct (\yii\web\User $user, $config = [])</code>. I figured out, that <code>Yii::createObject</code> doesn't look to application components DI, but only to <code>Yii::$container</code> DI.

Is it possible to inject dependencies like wihout manual Yii::$container->set() and Yii::createObject will look to app locator or not?? Or am I doing something wrong? What workflow do Y suggest?

Testing on PHP5.6 and Yii2.0.6. Btw great work on Yii2 so far, big fan here.

**Comment by samdark** [comment]
Injections are about container, not locator.
