### ISSUE TITLE
Using Async Methods in framework

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#10205]
Why don't they use async methods in the framework most of the time?
I think using async methods would be better for the performance.

**Comment by SilverFire** [comment]
Please, provide detailed information

**Comment by EngRajabi** [comment]
@SilverFire In most of the programming languages like Java and ASP.NET they use async methods for doing stuff like ORM, and networking jobs , authentication. most of the time to better the performance.
But in the framework I think we don't use them the way others do!

**Comment by samdark** [comment]
@EngRajabi still don't get it. How to use these "anync methods" in PHP?

**Comment by cebe** [comment]
@EngRajabi something like https://github.com/reactphp/promise ? I think this is out of the scope of Yii.

**Comment by samdark** [comment]
Definitely.
