### ISSUE TITLE
modules and main application layout issues

### ISSUE THREAD

**Issue by PommeVerte** [yiisoft/yii2#10204]
Hello,

If your module renders a view using an `@app` layout view file containing a reference to `render()` all hell breaks loose. All generated URLs and sub renders get prefixed by the module. (and either fail because the view doesn't exist, or generates broken links)

It's possible to avoid this behavior by using `render('//_something')` rather that `render('/_something')`, But this is only a crutch as it will only work in an `app-> module` relationship. If you do the same in a `module->module` scenario you're screwed. Same goes with URLs. 

Maybe I'm missing something obvious?

**Comment by cebe** [comment]
> If your module renders a view using an @app layout view file containing a reference to render()

can you be more specific about this? in general that is not true and depends on a lot of things, e.g. file locations and how you specify urls, etc...

**Comment by PommeVerte** [comment]
Ok, I'll try to keep this short and clear but there are a few moving parts here to bear with me. I'm going to go over the `render()` issue but the same thing could be said of using `URL::to()`.

Lets take the following files:

Imagine the following lines in **@frontend/views/layouts/main.php**

```php
$this->render('/site/_subView');
```

Now lets say we created a module with a path of (**@module**) as per the documentation and **without** setting a layout:

> If you do not configure the layout property, the application's layout will be used instead.

Add the following action to **@module/controllers/TestController.php** (and create the view, etc.):
```php
public function actionTest()
{
   $this->render('someview');
}
```

Now if you load `http://my.domain/module/test/test` Yii will give you an error saying it can't find `@module/views/site/_subView.php` when it should be trying to find `@frontend/views/site/_subView.php`.

This comes from [the following line](https://github.com/yiisoft/yii2/blob/master/framework/base/View.php#L174) in the code that is indiscriminate about where the render is coming from. It builds the path based on the controller being used (the module controller) rather than the view that called the render (which is a frontend view).

Again maybe I'm missing something obvious but hopefully you have enough info to clear things up for me if I am.

**Comment by cebe** [comment]
> though perhaps I simply need to apply a prefix slash in this case

exactly, if you do not add a slash you are creating relative URLs. If you are using the view from a module you have to be explicit about the URLs you create.

this is the same as with the render. starting with `/` means, use the current modules view directory (which is the application, if you are not in a module). `//` means to use the applications view directory always, regardsless of which module you are in.
Check the docs about that here: http://www.yiiframework.com/doc-2.0/guide-structure-views.html#named-views

**Comment by PommeVerte** [comment]
I beg to differ in that case.

What if I have module A and subModule B that is a submodule of A

Module A has a layout containing a `$this->render('/relativeView')` with `relativeView` living in module A's views folder

Now subModule B wants to use this layout. Therefore the render above refers to a file in subModule B's path and will fail.
If I switch it for  `$this->render('//relativeView')` then it looks for a file in the frontend path.
There is therefor no way to resolve the correct file?

**Comment by PommeVerte** [comment]
It feels like `render()` with a relative path inside a View should be relative to the views folder it belongs to. Am I making any sense?

**Comment by cebe** [comment]
if you specify a path not prefixed with `/` or `//` it is relative to the path where the view is. e.g. `../otherfile.php` is a valid relative path for render. specifying the path prefixed with `/` or `//` is relative to the current modules view path in the first case and absolute because of selecting the application view path in the second case.

**Comment by PommeVerte** [comment]
ah I see thanks

**Comment by PommeVerte** [comment]
Ok I'm awakening this again because this is still a problem with `URL::to()`

With URLs for example. Using `Url::to(['site/index']);` in the layout will:
- link to the `http://site.com/site/index` when the layout is loaded from the main app
- link to the `http://site.com/module/site/index` and break when the layout is loaded from a module
- same as above in a module/submodule logic

Thus we apply `Url::to(['/site/index']);` instead to:
- link to the `http://site.com/site/index` when the layout is loaded from the main app
- link to the `http://site.com/site/index` when the layout is loaded from a module (intended)
- **this however breaks acceptance testing as you would need to load `http://site.com/index-test.php/site/index`**

Is there any other option here?

**Comment by cebe** [comment]
> this however breaks acceptance testing as you would need to load http://site.com/index-test.php/site/index

I do not see a relation here... for site/index as well as /site/index the testing url will be the same.

**Comment by PommeVerte** [comment]
Well the application is set to run with `index.php` (via access rules). 
The acceptance tests however are set to run with `index-test.php` and this works fine as demonstrated : 

```
* I am on page "/index-test.php/site/index"
```

Using `Url::to(['controller/action'])` with relative paths load properly on top of index-test.php (`"/index-test.php/controller/action"`) however using prefix slashes like `Url::to(['/controller/action'])` loads the page `"/controller/action"` (`index.php` is implicit here).
This breaks all the links for the acceptance tests. (instead it loads "frontend" data and the DB may be empty or without proper data for the frontend)

Am I making sense?

**Comment by cebe** [comment]
adding a slash to the route should not have any effect on the generated url. Added a test to verify this: d6c45d3
