### ISSUE TITLE
Flash messages not showing after logging out a user.

### ISSUE THREAD

**Issue by drew1two** [yiisoft/yii2#10218]
With a clean install of advanced app.  Open frontend (and backend) siteController.
Add 
Yii::$app->session->setFlash('success', 'You have been successfully logged out!');
to line 107 of frontend/siteController
and Add
Yii::$app->session->setFlash('success', 'You have been successfully logged in!');
to line 91 before the return $this->goBack(); call.

Login and see the successfully logged in message.
Logout and notice there is no successfully logged out message.

Happens the same in the backend as well.

I have a working version I downloaded / updated at:-
"time": "2015-09-24 23:06:03".
(working) meaning I get my flash messages displayed as expected.
Just for some reason my new apps don't display them.

I can see from the logs that the flash messages are being set in the POST logout.
Just not being displayed in the GET index page.

I tried using $this->redirect(['site/login']); as well with the same results.

**Comment by unclead** [comment]
Sessio is destroyed after calling logout method tahts why you dont see any flash messages after redirect

You can call `Yii::$app->user->logout(false);` if you dont want to session will be destroyed
But i am unsure is it rght way or not

**Comment by drew1two** [comment]
I thought that as soon as you call:-
Yii::$app->session->setFlash(...
It automatically creates a new session?
So logout kills the 'user' session, but setting flash message immediately afterwards will create a new session for basic application functionality.

If I use Yii::$app->user->logout(false);. Does it still retain private information about the user (like username, email etc.)?  Or just their publically available info (like ip, browser etc.)?

**Comment by unclead** [comment]
This code works correct for me
```
    public function actionLogout()
    {
        Yii::$app->user->logout();
        Yii::$app->session->setFlash('success', 'Success');

        $this->redirect(Yii::$app->getUser()->loginUrl);
    }
```

But if i call `setFlash` before `logout` it doesnt work

**Comment by unclead** [comment]
If it doesnt work for you please write which version of yii do you use and show us full version of your action

**Comment by drew1two** [comment]
Your example is exactly the same I've implemented.  Because it wasn't working, I tested it out with a clean install of the advanced app.
I did exactly as you described above (which falls on line 107 of frontend/siteController when clean install).
example:-

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        Yii::$app->session->setFlash('success', 'You have been successfully logged out!');
        return $this->redirect(['site/login']);
        // return $this->goHome();
    }

This fails to render the flash message.  Though the following does render the flash message:-


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->session->setFlash('success', 'You have been successfully logged in!');
            return $this->redirect(['site/index']);
            // return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

Again, this is a clean install of yii2 advanced app.  Nothing else has been applied except for the addition of the 2 setFlash messages.

**Comment by drew1two** [comment]
Can someone else confirm this is the case with a fresh install of the advanced app please?  If it doesn't behave for you as I've described, I'll continue looking into my environment (which is windows 7 running wempserver 'nginx').

Thanx again for any confirmations / rebuttles.

**Comment by drew1two** [comment]
Verified.
Updated my app that worked using composer update (had to change "bower-asset-library": "vendor/bower" to "bower-asset-library": "vendor/bower-asset") and the flash message now doesn't get displayed when a user logs out.

**Comment by SilverFire** [comment]
So it worked on Yii 2.0.6 and broke in current dev version of 2.0.7?

**Comment by drew1two** [comment]
Correct

**Comment by drew1two** [comment]
Is that when the bower asset directory name changed?

**Comment by drew1two** [comment]
Sorry @SilverFire.
The previous version could be earlier than 2.0.6...*unsure.

**Comment by cebe** [comment]
> Is that when the bower asset directory name changed? (2.0.6 - 2.0.7)

that name should not have changed, if it did it was not caused by yii, but maybe by a composer update that broke it.

**Comment by drew1two** [comment]
Just today I got the 60 day warning about Composer needing an update.  I applied that update 'before' updating the working application.

**Comment by klimov-paul** [comment]
Issue confirmed.
Session is lost in case it has been destroyed and then reopened.
This happens because after being reopened session rerturns new session cookie value to the browser, while `session_id()` value remains to be the same. Check following 'logout' code:

```php
public function actionLogout()
    {
        var_dump($_COOKIE); // session coookie value = sess_id#1

        var_dump(Yii::$app->getSession()->getId()); // outputs: sess_id#1

        Yii::$app->user->logout();

        Yii::$app->session->setFlash('success', 'You have been successfully logged out!');
        Yii::$app->session->set('logout', __METHOD__ . ' at ' . date('Y-m-d H:i:s'));

        var_dump(Yii::$app->getSession()->getId()); // outputs: sess_id#1 !!!

        exit;
    }
```

While network console indicates response from 'POST logout' containing 'Set-Cookie: PHPSESSID=sess_id#2' !!!

I am unsure why this happens.

**Comment by klimov-paul** [comment]
The walk-around could be the regenerating session ID before return logout response:

```
public function actionLogout()
    {
        Yii::$app->user->logout();

        Yii::$app->session->setFlash('success', 'You have been successfully logged out!');
        Yii::$app->session->set('logout', __METHOD__ . ' at ' . date('Y-m-d H:i:s'));

        Yii::$app->session->regenerateID(); // Enforce new session ID usage
        
        return $this->goHome();
    }
```

In this case 2 'Set-Cookie' headers are passed to response and `session_id()` value updated.

**Comment by klimov-paul** [comment]
http://php.net/manual/ru/function.session-regenerate-id.php#107323

**Comment by klimov-paul** [comment]
It seems that new session ID cookie is sent once `session_destory()` is invoked.

The possible fix can be setting session ID to `null` manually at `Session::destroy()`:

```php
public function destroy()
    {
        if ($this->getIsActive()) {
            @session_unset();
            @session_destroy();
            @session_id(null); // unset cached session ID
        }
    }
```

This works for me, but I am unsure if this is a correct way.

**Comment by SilverFire** [comment]
Since we have not better ideas, I think we can do as @klimov-paul suggested
