### ISSUE TITLE
suggest : yii 2.1 rewrite

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#10219]
yii 2.1 rewrite PHP 7 .
better performance .
more objective .
use async method .
more ....

**Comment by derekisbusy** [comment]
Or how about as a C extension like Phalcon

**Comment by cebe** [comment]
Maybe, but we have to focus on other things first.

**Comment by samdark** [comment]
I won't do C extension. I'd rather use Zephir for it.

**Comment by samdark** [comment]
As for PHP7, 2.0 works with it so performance is already achieved.
