### ISSUE TITLE
php 5.4 - End of life

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#10222]
php 5.4 - End of life
http://ru2.php.net/supported-versions.php

Offer from Yii 2.1 to abandon support for php 5.4

**Comment by agungsijawir** [comment]
https://github.com/yiisoft/yii2/wiki/Ideas-for-2.1

**Comment by samdark** [comment]
Yes, we'll abandon 5.4 in 2.1.

**Comment by LAV45** [comment]
Thank you
