### ISSUE TITLE
ActiveForm 'fields' option

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#10221]
This is a feature request to add an option in ActiveForm called 'fields' in order to eliminate the need for individually *echo*-ing each field. We would be able to configure and echo the entire ActiveForm in one call instead of having to call *begin()* and *end()* and rendering the fields manually in between.

Currently we need to make at least 3 separate calls to render a form:
```php
<?php $form = ActiveForm::begin(); ?>
<?= $form->field($model,'test',['enableAjaxValidation'=>true])->textInput(['maxlength'=>10]) ?>
<?php ActiveForm::end(); ?>
```

Instead, we could achieve the same in a single call, for example:
```php
<?= ActiveForm::widget([
    'fields' => [
        [
            'type' => ActiveForm::TEXT_INPUT,
            'model' => $model,
            'attribute' => 'test',
            'enableAjaxValidation' => true,
            'options' => ['maxlength'=>10],
        ],
    ],
]) ?>
```

This would enable an insane amount of flexibility with forms. For example we would be able to pass the entire form as a parameter to another widget.

**Comment by cebe** [comment]
Could you elaborate more on the use cases for this? I do not really see the benefit of doing it this way.

**Comment by SilverFire** [comment]
So it's partially about *3 calls in 3 lines* vs *1 call in 11 lines*.
It does not break BC, just gives a new way to do the same. Despite that I'm not sure we need it in the core `ActiveForm`.

**Comment by petrabarus** [comment]
This is much like ExtJS, if I recall correctly. I met a use case for this. I once have to reuse same model multiple times with different order of fields and simple form view. Once you need a complex view, this will be unusable.

A convenient way, indeed. But I don't think it's needed in the core. Might want to release it as extension.

**Comment by vercotux** [comment]
Another use case is when you have a static widget area in the main layout and want to dynamically pass it some widgets/forms from your views. With this you can inject forms on the spot (through *$this->params* for example) without having to create a subclass for every single form.

It could go into core ActiveForm purely for its simplicity. I was able to achieve this a very crude way with just 5 lines of code.

**Comment by nineinchnick** [comment]
Such feature looks like a form builder that in Yii 1 was provided by the CForm class. Yii 2 doesn't currently provide anything like this. I do find it useful, so I support this feature request.

**Comment by Alex-Code** [comment]
Would this be better off as a widget to save adding more code to `ActiveForm`?
e.g.
```php
<?= ActiveFields::widget([
    'form' => $form,
    'fields' => [
        [
            'type' => ActiveForm::TEXT_INPUT,
            'model' => $model,
            'attribute' => 'test',
            'enableAjaxValidation' => true,
            'options' => ['maxlength'=>10],
        ]
    ]
]); ?>
```

**Comment by nineinchnick** [comment]
@Alex-Code you forgot the widget class in that example. I'd propose something obvious like a `FieldsGroup` widget.

**Comment by Alex-Code** [comment]
I called it `ActiveFields`, could be confusing as it's similar to `ActiveField` as the `s` might not be noticed.
Did think about `ActiveFieldBuilder`.

**Comment by SilverFire** [comment]
This feature may be implemented on-top of `ActiveForm` as a widget of extension, but not in core.

**Comment by vercotux** [comment]
Should I open a new issue for that?

**Comment by petrabarus** [comment]
I think what @SilverFire meant is that you should create a new extension yourself for that.

**Comment by vercotux** [comment]
Ah so it won't be included in Yii2. No point then.
