### ISSUE TITLE
ActiveRecord : func sum , avg ,...

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#10232]
in EntityFrameWrok
``` c#
Book.select(r=>r.price).sum();
```
function sum , count , min , max , avg ,....
add in orm in yii2
example
``` php
Book->find()->select('price')->sum();
```

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#normal-query ?
