### ISSUE TITLE
[Formatter] add support for numbers abbreviation 

### ISSUE THREAD

**Issue by coolcflame87** [yiisoft/yii2#10236]
Add support for numbers short abbreviation like asShortSize() does.

 e.g. 1000, 1230, 1500, 154000, 1500000, 1000000
 format them with an abbreviation. i.e.
 if it's a thousand, then 1k, 1.1k, 2k, 10k, 10.5k etc...
 and so on for the tens, hundreds thousands and millions, etc...

**Comment by nineinchnick** [comment]
Might be related to #9709
