### ISSUE TITLE
Bootstrapping component/module with same name

### ISSUE THREAD

**Issue by nkostadinov** [yiisoft/yii2#10233]
According to the documentation: "During the bootstrapping process, each component will be instantiated. If the component class implements yii\base\BootstrapInterface". But that is not entirely true. I have a "user" component and a "user" module - with the same name and added to the bootstrap section of my config ["user"]. The problem is that the current implementation checks that the user component doesn't implement the BootstrapInterface and skips it, but never checks the module with the same name. I think this is inconsistent behavior - what do you guys think ? The problem comes from this code in yii\base\Application(line:298)
```php
        foreach ($this->bootstrap as $class) {
            $component = null;
            if (is_string($class)) {
                if ($this->has($class)) {
                    $component = $this->get($class);
                } elseif ($this->hasModule($class)) {
                    $component = $this->getModule($class);
```

How can I "bootstrap" a module with the same id as a component ?

**Comment by samdark** [comment]
How do you manage to have two same-named bootstrap entries. Could you show your config bootstrap section?

**Comment by nkostadinov** [comment]
This is my config. I don't have two entries in the bootstrap element. But a component and a module with the same name:

````
return [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'gii', 'user'],
    'controllerNamespace' => 'app\commands',
    'modules' => [
        'gii' => 'yii\gii\Module',
        'user' => 'nkostadinov\user\Module'
    ],
    'components' => [
        'db' => $db,
        'user' => [
            'class' => 'nkostadinov\user\components\User'
        ]
    ],
    'params' => $params,
];
````
The module has bootstrap method but the component doesn't so nothing happens.

**Comment by samdark** [comment]
Right. Let's assume `test` is what specified in `boostrap`. There are following cases:

1. There are module `test` and component `test`. Both implement `BootstrapInterface`. Which should be called? (Currently it's component only).
2. There are module `test` and component `test`. Only module implements `BootstrapInterface`. Should module be called? (Currently nothing's called).
3. There are module `test` and component `test`. Only component implements `BootstrapInterface`. (Currently only component is called).
4. There's component only. Component is called.
5. There's module only. Module is called.
6. There's no module or component called `test`. `InvalidConfigException` is thrown.

**Comment by samdark** [comment]
@nkostadinov, @yiisoft/core-developers what's your opinion on correct behavior?

**Comment by klimov-paul** [comment]
Duplicates #5091

**Comment by samdark** [comment]
Yes, it's the same issue but I don't think current behavior is logically correct...

**Comment by traykovn** [comment]
Thanks for the comment, @samdark. I also support your opinion. The suggested solution is just a workaround, but the behavior is still not logically correct.

**Comment by klimov-paul** [comment]
The ony way to actually resolve the issue will be separate 2 different `boostrap`: `bootstrapComponents` and `bootstrapModules`. There is no way to avoid confusion. However current `boostrap` also allows usage of the callables, which does not relates to components or modules at all.

Callable can be used to resolve possible naming confusions. I can't see no other way.

**Comment by samdark** [comment]
I mean instead of executing only one option we may check for every possible option and execute it. I.e. if there is component named `test` and module named test `test`, I think there should be two totally separate attempts to execute `BootstrapInterface`.

**Comment by klimov-paul** [comment]
How does this make things better?
Checking component and module will load them both, executing thier `init()` method, while it could be undesiarable. If I want to load 'user' module, but don't want to load 'user' componet, such strategy will not solve my task.

Component bootstraping does not always require `BootstrapInterface` involvement. You can bootstrap any component, which means it will be initialized at the application execution begin.

Using only name at `bootstrap` is a shortcut. We allow specification of the components and modules inside it for simplicity of the API. If at some reason it is not acceptable, like with this issue, the callback should be used instead.

**Comment by nkostadinov** [comment]
another option would be to be able to specify section in the bootstrap config like this:

````
    'bootstrap' => ['gii', 'log', 'components' => ['test'], 'modules' => ['module1']]
````

**Comment by samdark** [comment]
@klimov-paul how about `#2` from my list?

**Comment by klimov-paul** [comment]
> There are module test and component test. Only module implements BootstrapInterface. Should module be called? (Currently nothing's called).

This is not exactly true. In this case component exists and it is initialized, thus `Component::init()` is invoked. Since it does not implement `BootstrapInterface`, `bootstrap()` is not invoked. This is a valid use case for `Application::bootstrap`.
Do not mess up `Application::bootstrap` and `BootstrapInterface`. `BootstrapInterface` is built up on top of the `Application::bootstrap`, but `Application::bootstrap` can work without it.

**Comment by samdark** [comment]
OK. Decided to close it.

**Comment by dynasource** [comment]
I dont understand this topic.  See #4192 #4525 #5091 
The solution is already given in the manual.

https://github.com/yiisoft/yii2/blob/master/docs/guide/structure-applications.md#yiibaseapplicationbootstrapbootstrap-

Info: If a module ID is the same as an application component ID, the application component will be used during the bootstrapping process. If you want to use the module instead, you may specify it using an anonymous function like the following:

[
    function () {
        return Yii::$app->getModule('user');
    },
]

**Comment by samdark** [comment]
Indeed.
