### ISSUE TITLE
Unable to verify your data submission on several cases

### ISSUE THREAD

**Issue by luqmansungkar** [yiisoft/yii2#10247]
Hi,

I'm using Yii version 2.0.6, advanced template. I got several notification from the log that someone using my app has got 'Unable to verify your data submission'. The problem is, I myself can't reproduce the problem, and the problem only occur several times, while most of the users don't get this problem. Here are some logs for the problem :
- http://pastebin.com/98BN9jkS
- http://pastebin.com/h1CcgdEu
- http://pastebin.com/qSQa4RrE
- http://pastebin.com/Zhp0jmNX

I am using adcanced template with backend and frontend in the same domain. Here are my config file :
- [Backend config](http://pastebin.com/gpXJ5qAV)
- [Frontend config](http://pastebin.com/ZHgdr5P4)

What might be the problem?

Thank you.

**Comment by SilverFire** [comment]
CSRF token might be changed upon submit moment.

> http://pastebin.com/qSQa4RrE

Here it seems that user was redirected from FaceBook with the unsigned POST request.

Please notice that this is not a support forum. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.
