### ISSUE TITLE
Weird behavior of Yii::t() while using "plural" and "spellout" formats

### ISSUE THREAD

**Issue by dajnz** [yiisoft/yii2#10240]
Hello,
I'm trying to learn how to use different formats which is supported by Yii::t() but it looks like Yii::t() works for me not like it described in Yii2 docs. So please look at my screenshots.

To test how **plural** format works I have taken sample code from Russian Yii docs, but due to some mysterious reasons **other** part of this rule overrides **one** and **few** parts, so for numbers from 2 to 9 **t()** constantly returns a content from **other** part of the rule.

Also, when I want to convert some number with help of **spellout** format into it string representation but in Russan, t() always returns english representation, at the same time I've **ru-RU** value for **language** property of my web application.

From screenshots you can learn version of intl and php, and here is some other info:
* Apache version - **2.4.7**
* OS - **Kubuntu 14.04**
* Platform - **x86_64**

![output-icu-source](https://cloud.githubusercontent.com/assets/11261945/11375669/8393a82e-92ed-11e5-97b2-fe4dfee65061.jpeg)
![output-icu](https://cloud.githubusercontent.com/assets/11261945/11375670/83977f4e-92ed-11e5-9b9e-d40bcde6e60e.jpeg)

**Comment by SilverFire** [comment]
`var_dump(INTL_ICU_DATA_VERSION)`

**Comment by dajnz** [comment]
Here is a result of var_dump: **string '56.1' (length=4)**

**Comment by SilverFire** [comment]
`var_dump(Yii::$app->sourceLanguage)`

**Comment by dajnz** [comment]
source language is default **en-US **

**Comment by SilverFire** [comment]
Okay, so here is your problem.
You compose the message in Russian (кошка, кошки, кошек), but as the source language is English, Yii tries to find translation of your message from English to Russian. If fails to do it, so falls back to English and uses your message with Russian words as an English one.

Set `Yii::$app->souceLanguage` to `ru-RU` and all will work as expected

**Comment by dajnz** [comment]
Ok, thank you @SilverFire, your solution works fine, but I thought the formatting (plural, spellout) was applied to translated string. So how can I use spellout for some number in arbitrary translation language? Do I need to specify translations for each digit in desired language?

**Comment by SilverFire** [comment]
Of course no. It's built in ICU. Are you still experiencing problems with spellout after you applyed the proposed solution?

**Comment by dajnz** [comment]
If I set my **Yii::$app->sourceLanguage** to **ru-RU** everything works fine, I receive my number spelled in Russian. But I can't figure out how to make it to spell my number in another languge, which for instance was selected by user to translate a website to. I've noticed Yii spelled a number only in current **Yii::$app->sourceLanguage** with no respect of a value of **Yii::$app->language**, I've tried **de-DE**, **zh-CN** and **en-US**.

So let's assume I've the following source code I want to be spelled in a current website language
```
<?= Yii::t('app', '{n, spellout}', ['n' => 2015]); ?>
```
If my **Yii::$app->sourceLanguage** is **ru-RU** then 2015 spelled in Russian correctly, and let's say some English-speaking user select English in my website language selector, and this cause a changing of **Yii::$app->language** value to **en-US**. Now the user expect to see the number spelled in selected language, but the number remains spelled in Russian.

I hope this explanation quite clear, I feel I'm missing something simple in mechanism of Yii translation, but I can't realize this.

Thank you for your help.

**Comment by samdark** [comment]
@dajnz you should have translation for the language you're going to use.
