### ISSUE TITLE
Cannot modify query object using filter attribute in ExistValidator

### ISSUE THREAD

**Issue by matjaz-elumina** [yiisoft/yii2#10242]
The anonymous function defined in filter attribute is called via call_user_func function which doesn't pass the parameters ($query in this case) by reference. So the changes you make to the $query object are not reflected back to the parent function.

Line 157 should probably say: 

`call_user_func_array($this->filter, [&$query]);`

Or am I missing something?

**Comment by samdark** [comment]
Objects are always passed by reference.

**Comment by matjaz-elumina** [comment]
Hm, doesn't seem that is the case. Whatever I do with the query object in the anonymous function nothing changes when the query is run in the validator. My solution helped though.

**Comment by matjaz-elumina** [comment]
I get it now. The problem is I'm trying to create a completely new Query object in filter function (because I'm dynamically creating the targetClass) and return it to the parent function for execution. And this doesn't work without explicitly passing the query object by reference.

Nice explanation here: http://stackoverflow.com/questions/9331519/how-do-you-pass-objects-by-reference-in-php-5/9332219#9332219

Would be good if you could implement my solution  because this would give us more freedom when modifying the query altogether.

**Comment by samdark** [comment]
Please provide an example of how you do it with anonymous function.

**Comment by matjaz-elumina** [comment]
[['item_id'], 'exist', 'targetAttribute' => 'id', 'filter' => function (&$query) { 
        $targetClass = $this->class;
        $query = $targetClass::find()->andWhere(['id' => $this->item_id]);            
    }],

**Comment by samdark** [comment]
You're overwriting query so that's expected that it's overwritten...

```php
[['item_id'], 'exist', 'targetAttribute' => 'id', 'filter' => function ($query) { 
    $query->andWhere(['id' => $this->item_id]);            
}],
```

**Comment by matjaz-elumina** [comment]
I know! But the way the filter function is called now it is not possible to overwrite the query.

It would be useful to have this option, so I can query the dynamic targetClass (defined when model is populated with input data)), and not the one you can specify with 'targetClass' attribute. 

Currently you can only do what you suggested. Add new conditions to the query which is no good for my example.

**Comment by samdark** [comment]
You can set class dynamically w/o overwriting query:

```php
[['item_id'], 'exist', 'targetAttribute' => 'id', 'filter' => function ($query) {
    $query->modelClass = $this->class;
    $query->andWhere(['id' => $this->item_id]);
}],
```

**Comment by matjaz-elumina** [comment]
Right! 

Thanks, you rock!
