### ISSUE TITLE
Routes with uppercase letters

### ISSUE THREAD

**Issue by hguenot** [yiisoft/yii2#10246]
Hi,
I don't really know if it is an issue or a real implementation choice...
In my application, I've go an "EventType" class model... and an "EventTypeController" controller. 
Due to regexp in Module::createControllerByID (`'%^[a-z][a-z0-9\\-_]*$%'`) my route `r=eventType` is not valid because route has to be in lowercase.
Thanks for your help.

**Comment by mdmunir** [comment]
`r=event-type`
