### ISSUE TITLE
multiple fileInput uploads only 1 file

### ISSUE THREAD

**Issue by burlakko** [yiisoft/yii2#10250]
When generating active form with multiple fileInput like it's shown here http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html#uploading-multiple-files the input's name attribute doesn't contain square brackets in the end. So when you submit this form $_FILES variable contains array with only one file - the last one of all  been submitted.
MailboxController.php
```
public function actionCompose() {
    $model = new Message();
    return $this->render('compose.php', ['model' => $model]);
}

public function actionSend() {
    var_dump($_FILES);exit();
}
```
View compose.php
```
<?php $form = ActiveForm::begin([
    'action' => ['/mailbox/send'],
    'options' => ['role' => 'form', 'enctype' => 'multipart/form-data'],
    'enableAjaxValidation' => true
]); ?>
    <?= $form->field($model, 'attachments')
        ->fileInput(['multiple' => true)
        ->label(false); ?>
<?php ActiveForm::end(); ?>
```

Generated input
```
<input type="file" multiple name="Message[attachments]" id="message-attachments">
```

It works only if I specify name with brackets in view
```
<?= $form->field($model, 'attachments')
    ->fileInput(['multiple' => true, 'name' => 'Message[attachments][]')
    ->label(false); ?>
```

**Comment by SilverFire** [comment]
It's described in the guide. Follow your link, scroll 1 page down and you'll find:

`    <?= $form->field($model, 'imageFiles[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>`

**Comment by burlakko** [comment]
oops! thanx SilverFire!
