### ISSUE TITLE
renderAjax doesn't reload js files

### ISSUE THREAD

**Issue by tongtoanbs** [yiisoft/yii2#10251]
I'm using `registerJsFile` inside `renderAjax` file. This is my ajax view file:
```php
$themeUrl = $this->theme->baseUrl;
$this->registerJsFile('@web'.$themeUrl.'/js/library/save-load.js', ['depends' => JqueryAsset::className()], uniqid());
$this->registerJs('console.log("Inline js script")');
```
and this is the `save-load.js` file
```javascript
console.log('js file');
```
As you can see the "Inline js script" shows every time I make a request, but the 'js file' only show for the first time. The same thing happen for my jquery code, it only work for the first request, then the next request it doesn't work anymore. Example:
```javascript
var $pjaxGrids = $(
        'div#pjax-load-bill-grid, div#pjax-save-bill-grid,'+
        'div#pjax-save-system-grid, div#pjax-load-system-grid, '+
        'div#pjax-save-toutimes-grid, div#pjax-load-toutimes-grid, '+
        'div#pjax-save-proposal-grid, div#pjax-load-proposal-grid, '+
        'div#pjax-save-consumption-grid, div#pjax-load-consumption-grid'
    );
$pjaxGrids.on('click', 'tr', selectRow);
```
This code only work for the first time, but if I move it to the `registerJs` instead of `registerJsFile` then it works in every request as I expect

**Comment by Alex-Code** [comment]
This is by design, A JavaScript file would typically only need loading once so all subsequent requests filter out already included files.

If you wan't to load it with every request you can add it's path to `yii.reloadableScripts` [yii.js](https://github.com/yiisoft/yii2/blob/1a48d248301bcf30f3d20fb17ac067db5a2efc11/framework/assets/yii.js#L50)

**Comment by FarzadKaramouz** [comment]
Hi,
Would you please explain how to add it's path to yii.reloadableScripts.
Thanks.

**Comment by jacksontong** [comment]
This is how I add the path to `yii.reloadableScripts`
```php
$themeUrl = $this->theme->baseUrl;
$ajax_create = '@web' . $themeUrl . '/js/project/ajax_create.js';
$this->registerJsFile($ajax_create, ['depends' => [yii\web\JqueryAsset::className(), \yii\jui\JuiAsset::className()]], $ajax_create);
$am = $this->assetManager;
/** @var \yii\web\AssetBundle $bundle */
$bundle = $am->bundles[$ajax_create];
$this->registerJs('
yii.reloadableScripts = [\''.implode(',',array_map(function ($value) use ($am, $bundle) {
        return $am->getAssetUrl($bundle, $value);
    }, $bundle->js)).'\'];
');
```
