### ISSUE TITLE
priority to last matched AccessControl rule or use total of all matched rules

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#10259]
in child class we must make merge at end for child rules priority but it's broke other behaviors merge
```php
	public function behaviors() {
		return ArrayHelper::merge([
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [],
			],
		], parent::behaviors());
	}
```

parent rules can be common like /admin/ access, child can be more specific controller access for users who pass /admin/ access for example
```php
	public function behaviors() {
		return ArrayHelper::merge(parent::behaviors(), [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'matchCallback' => function() {
							return $is_admin;
                    	}
					],
				],
			],
		]);
	}
```
```php
	public function behaviors() {
		return ArrayHelper::merge(parent::behaviors(), [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => false,
						'controllers' => ['admin/news'],
						'matchCallback' => function($rule, $action) {
                        	return $not_news_admin;
                    	}
					],
				],
			],
		]);
	}
```

**Comment by cebe** [comment]
> in child class we must make merge at end for child rules priority

why do you need to do this? what about simple `array_merge()`? I do not really get the use case.

**Comment by DrDeath72** [comment]
can you show example?

**Comment by cebe** [comment]
just replace `ArrayHelper::merge(` with `array_merge(`, this will not merge content of the behavior configs but will override them. But that may not be what you want.

**Comment by DrDeath72** [comment]
Yep, i want extend parent behaviors if it need, not replace, so other behaviors need merge at end, AccessControl at beginning and it not extend parent rules :(

**Comment by DrDeath72** [comment]
hmm... i think i can extend with second AccessControl with another behavior key, so parent and child filter be different and work together
