### ISSUE TITLE
Session component initialization over active session

### ISSUE THREAD

**Issue by quorzz** [yiisoft/yii2#10255]
Of course,  the best practice is use `Yii::$app->session` or cookie instead of handle with `$_COOKIE $_SESSION ...` directly.

but (yes, here is a but ) , if by any chance,  one call `session_start` before that called by `Yii`. 

for example, call `session_start` in the entry file or somewhere else ,

this will prevent the session component  to  `registerSessionHandler` `updateFlashCounters` .... 

then the session component no longer works well,

and in this case,  the bug is difficult to pull out.

so maybe we can give a detect at first `session_start` in `\yii\web\Session` ?

**Comment by quorzz** [comment]
In short,  call `session_start`  by developers maybe lead to errors of session component...

Maybe `Yii` can throw an exception or other handle in this case ?

**Comment by SilverFire** [comment]
It can be handled easily by calling `$this->getIsActive()` before `session_start()`.
I think it may be implemented.

**Comment by AnatolyRugalev** [comment]
@SilverFire , `$this->getIsActive()` is already called in beginning of `open()`.

```php
public function open()
    {
        if ($this->getIsActive()) {
            return;
        }

        $this->registerSessionHandler();

        $this->setCookieParamsInternal();

        @session_start();

        if ($this->getIsActive()) {
            Yii::info('Session started', __METHOD__);
            $this->updateFlashCounters();
        } else {
            $error = error_get_last();
            $message = isset($error['message']) ? $error['message'] : 'Failed to start session.';
            Yii::error($message, __METHOD__);
        }
    }
```

Maybe we can check this case by `getIsActive()` on `init()` and then throw an exception? Wouldn't this break BC?

**Comment by SilverFire** [comment]
Hm, I think yes, it will be ok, but need a @yiisoft/core-developers opinion

**Comment by klimov-paul** [comment]
If `session_start()` is called outside of the Yii scope, it is no longer safe for the Yii to handle it further.
If we will still register related shutdown code, it may break the logic of the code, which actually opened the session at the first place.
You should use `Session::open()` or the session start if it is possible, if it is not - it means session is handled by other framework or library and we can not interfere to it.

**Comment by quorzz** [comment]
@klimov-paul @SilverFire @cebe 

"we can't interfere that case".   Yes, I can't agree any more.

but I think we should at least throw an exception.

---

besides,  all the functions of session start with `@` ( \yii\web\Session ) .

So you can imagine how crazy it is if the third-party library or the developer himself touch the `session`

**Comment by quorzz** [comment]
@AnatolyRugalev  yeah,  good idea to me .

**Comment by klimov-paul** [comment]
> we should at least throw an exception

We we should not. `yii\web\Session` can still provide the access to the session variables normally, even if the session started elsewhere. Throwing exception here is not an option.

**Comment by quorzz** [comment]
@klimov-paul  yes...  the session component  can still work .

However `cookieParams`  and `sessionHandlers`  won't  be set as expect ,  `flash message` won't  work well .....

Since we can foresee this but can't interfere to it,  throw an exception to remind the develper himself to solve it may be an option.

this is just  my simple idea :-)

**Comment by rugabarbo** [comment]
I think here is more suitable ```Yii::warning()```.

**Comment by AnatolyRugalev** [comment]
If session was started outside of the Session component, should it register shutdown function?

```php
public function init() {
        parent::init();
        if ($this->getIsActive()) {
            Yii::warning("Session is already started", __METHOD__);
        }
        register_shutdown_function([$this, 'close']);
}
```
OR:
```php
public function init() {
        parent::init();
        if ($this->getIsActive()) {
            Yii::warning("Session is already started", __METHOD__);
        } else {
            register_shutdown_function([$this, 'close']);
        }
}
```
And why this call is inside of `init()`, but not in `open()`? Should component close session if it doesn't open it?
