### ISSUE TITLE
ActiveRecord Fixture [feature request]

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#10256]
Currently the ActiveFixture class defined **doesn't** interact with the ActiveRecord fixtures except to get the table name and then use the table schema to create the inserts directly on the database.

I propose to change this behavior and use the `ActiveRecord::load()` and `ActiveRecord::save()` methods to handle the data in the fixtures. Or create a new class `ActiveRecordFixture` that has this behavior.

This will allow to tests the rules defined on the ActiveRecord as well as checking that the errors are indeed the ones you would expect.

Example for a `User` active record the data
```php
return [
    'required_attributes' => [
        // pass no actual data and check that the required attributes contain validation errors.
        'attributeErrors' => ['username', 'email', 'password'],
    ],
    'success_register' => [
        'username' => 'Faryshta',
        'email' => 'angeldelcaos@gmail.com',
        'password' => 'secrets',
    ],
    'unique_attributes' => [
        'username' => 'Faryshta',
        'email' => 'angeldelcaos@gmail.com',
        'password' => 'secrets',
        // check that model was not saven since the username and email are already in use
        'attributeErrors' => ['username', 'email'],
    ],
];
```

currently thats impossible and the fixtures only allow me to test the table structure but not the models themselves.

**Comment by Macbenach** [comment]
in your case, your proposal would help in the review of the security does your proposal may extend N number of times any one model is static or dynamically each particular model ?

**Comment by Faryshta** [comment]
Each fixture would work with one model as it does right now. The `ActiveFixture::$depends` attribute would work similary and will allow a fixture to depend on others.

This proposal is aimed to actually use the `load()` and `save()` methods.

Right now the code is

```php
       foreach ($this->getData() as $alias => $row) {
            $primaryKeys = $this->db->schema->insert($table->fullName, $row);
            $this->data[$alias] = array_merge($row, $primaryKeys);
        }
```

which means the model methods are never used to insert the data, its not possible to check validation or ensure the safety of attributes before insert.

**Comment by klimov-paul** [comment]
Feature does not sounds to be worthy to be implemented to me.
Using ActiveRecord layer at the fixtures will make them running slower and consume extra memory, making tests execution heavier.
In the concept 'fixture' serves to prepare external resource (e.g. database) to the particular static state. It should not involve extra logic, which may be introduced by ActiveRecord.

**Comment by samdark** [comment]
Agree.
