### ISSUE TITLE
Submit after form validations errors;

### ISSUE THREAD

**Issue by Sf-Pr** [yiisoft/yii2#10266]
I have form with `enableAjaxValidation = true`, when i submit form, script send ajax request and recieve information about errors but don't stop submitting

**Comment by samdark** [comment]
Please show your controller action that's handling the form.

**Comment by Sf-Pr** [comment]
public function actionAjax()
    {
        $model = new LinkForm();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }

**Comment by Sf-Pr** [comment]
This is form:

<?php $form = ActiveForm::begin(array(
                'id'=>'user-form',
                'enableClientValidation'=>true,
                'enableAjaxValidation'=>true,
                'validationUrl' => '/roulette/ajax/')); ?>
           			<?= $form->field($model, 'link', [
                                'labelOptions' => ['label' => false],
                                'inputOptions'=> [
                                'rel' => 'get-trade-link',
                                'id' => 'par2',
                                'placeholder' => '',
                                'value' => Yii::$app->user->identity->link,
                                'style' => 'width: 800px'
                            ]
                            ]); ?>
			<?= Html::submitButton('Сохранить', ['class' => 'btn-yellow save-link']) ?>
            <?php ActiveForm::end(); ?>

**Comment by SilverFire** [comment]
Failed to reproduce with basic yii2 application template.
Could you try to reproduce your bug on clean install?

**Comment by samdark** [comment]
Closed till new data arrive.
