### ISSUE TITLE
Maximum execution time of 300 seconds exceeded when using oracle with gii

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#10260]
I am using Oracle for the first time with Yii2 and I've managed to connect the DB and access Gii. It is a large DB so I have just tried a small table with ~80 rows in for the model generator and I get

 `Maximum execution time of 300 seconds exceeded`

The hang seems to occur at this point in **Command.php**

    $this->prepare(true);
 
        $token = $rawSql;
        try {
            Yii::beginProfile($token, 'yii\db\Command::query');
 
            $this->pdoStatement->execute();
 
            if ($method === '') {
                $result = new DataReader($this);
            } else {
                if ($fetchMode === null) {
                    $fetchMode = $this->fetchMode;
                }
                $result = call_user_func_array([$this->pdoStatement, $method], (array) $fetchMode);
                $this->pdoStatement->closeCursor();
            }
     
Not really sure why this would happen for such a small table. I am connecting from a local XAMPP install to a live Oracle 11g DB. I have managed to use native PHP functions (`oci_connect()`) to connect and retrieve data. But having this issue will Yii2 2.0.7-dev

**Comment by nineinchnick** [comment]
Try disabling the relations option. If turned on (default), gii has to fetch all tables information.

**Comment by samdark** [comment]
There's no good way to speed it up. Either increase limits or do as @nineinchnick suggested.

**Comment by jonny7** [comment]
That did the trick, thank you. One final question I have here is. How do I change schema within my DB config?

**Comment by srinivasveerni** [comment]
Hi,

I am also facing the same problem. How to disable relations options in Yii2? Please tell me.

**Comment by jonny7** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-gii.html#generating-ar

"Generate relations" in the image

**Comment by srinivasveerni** [comment]
I imported the database from production into local XAMPP installation.
When trying to login the application it is giving the above error.
