### ISSUE TITLE
SwiftMailer::setReturnPath() in yii\mail\MessageInterface?

### ISSUE THREAD

**Issue by kroder** [yiisoft/yii2#10275]
As I can see there is no way to set custom Return-Path by built-in yii2-swiftmailer or how to do that?

**Comment by Alex-Code** [comment]
You can access the Swift message object,
```php
$headers = $message->getSwiftMessage()->getHeaders();
$headers->addPathHeader('Return-Path', 'person@example.org');
```
http://swiftmailer.org/docs/headers.html#path-headers

Or you could also extend `yii\swiftmailer\Message` to add the method yourself.
```php
'components' => [
//....
    'mailer' => [
        'class' => 'yii\swiftmailer\Mailer',
        'messageClass' => 'myMessageClass'
    ],
//...
],
```
