### ISSUE TITLE
tests documentation update

### ISSUE THREAD

**Issue by drew1two** [yiisoft/yii2#10274]
Following along with 'tests/README.md'.  Step 3 needs to be updated from:-
"
3. Create `yii2_advanced_tests` database then update it by applying migrations:

   ```
   codeception/bin/yii migrate
   ```
"
to:-
"
3. Create `yii2_advanced_tests` database then update it by applying migrations:

   ```
   cd tests
   php codeception/bin/yii migrate
   ```
"

**Comment by samdark** [comment]
That depends on how codeception is installed.
