### ISSUE TITLE
errors with advanced app installation

### ISSUE THREAD

**Issue by drew1two** [yiisoft/yii2#10271]
I've just tried installing another advanced app and got the following errors.

composer create-project --prefer-dist --stability=dev yiisoft/
yii2-app-advanced yii2_advanced_app_default_20151128
Installing yiisoft/yii2-app-advanced (dev-master a15b8b3b47a1ce78aadfa9e270b5203
45bc80c14)
  - Installing yiisoft/yii2-app-advanced (dev-master master)
    Downloading: 100%

Created project in yii2_advanced_app_default_20151128
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 2.1.*@stable | 1.11.*@s
table -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery 2.1.*@stable | 1.11.*@
stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yi
i2[2.0.6, dev-master, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

**Comment by SilverFire** [comment]
`composer global require "fxp/composer-asset-plugin:~1.1.0"`

**Comment by drew1two** [comment]
doh  was new puter and completely forgot about that one.  sorry.

Thanx @SilverFire
