### ISSUE TITLE
Unexpected behavior for Json::encode()

### ISSUE THREAD

**Issue by joni-jones** [yiisoft/yii2#10278]
I have xml with the following structure:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<file>
  <apiKey>ieu2iqw4o</apiKey>
  <modelName>Address</modelName>
  <calledMethod>getCities</calledMethod>
  <methodProperties>
    <FindByString>Kiev</FindByString>
  </methodProperties>
</file>
```

The described structure should be converted to array and the easiest way do it - it's encoding to json and decode back.
The following code:
```php
$document = simplexml_load_string($data);
$data = Json::encode((array) $document);
var_dump(Json::decode($data, true));
```
is return
```
Array
(
    [apiKey] => ieu2iqw4o
    [modelName] => Address
    [calledMethod] => getCities
    [methodProperties] => Array
        (
            [FindByString] => Array
                (
                )
        )
)
```
As you see the `FindByString` property is empty, but the implementation of `json_decode(json_encode((array) $document), true)` works correctly.

After debugging I found what https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseJson.php#L147 method not processing data for `FindByString` node, because the `$data` is a `SimpleXMLElement` object, but not `array`.

I think the typecasting `$data` to array in `foreach` should solve this problem.

**Comment by SilverFire** [comment]
@joni-jones would you like to make a PR?

**Comment by SilverFire** [comment]
Casting to array before foreach may break handling of `\Traversable` objects. 

I think we should add a new condition branch especially for XML Elements and cast `$data` there:

```php 
} elseif ($data instanceof \SimpleXMLElement)` {
    $data = (array) $data;
}
```

**Comment by joni-jones** [comment]
@SilverFire, to add new check for `SimpleXMLElement` it's not good idea, because in future may be needed another condition

**Comment by SilverFire** [comment]
I think it's not a problem

**Comment by joni-jones** [comment]
It's increase code complexety

**Comment by SilverFire** [comment]
Yes, it is, but your idea breaks iterating over `\Traversable` classes completely: https://3v4l.org/tWhcD

**Comment by joni-jones** [comment]
Typecasting was been a variant how to fix, but it doesn't consider `Traversable`, so need to find another solution.

**Comment by SilverFire** [comment]
I have already suggested the solution and it looks good enough for me, but I'm open to better options.

**Comment by joni-jones** [comment]
Maybe it would be better to check if element not traversable and when and typecasting to array?

**Comment by SilverFire** [comment]
@yiisoft/core-developers need your opinions

**Comment by samdark** [comment]
I think it's not JSON class responsibility to convert XML into arrays.

**Comment by joni-jones** [comment]
@samdark, yes, json functions not designed for it, but they can do it. The `Json::encode()` extends capabilities of `json_encode()`, but it shouldn't broke exists.

**Comment by LAV45** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseJson.php#L147
```php
foreach ((array)$data as $name => $value) {
    $result[$name] = $value;
}
```

**Comment by SilverFire** [comment]
@LAV45 could you read the issue a little bit more attentively, please?

@samdark Your opinion is generally correct, but there is a bunch of conditions to convert different objects to array. Why not add XML handling?

**Comment by LAV45** [comment]
@SilverFire , OK
then let's add a check
```php
if (!$items instanceof \Traversable) {
   $data = (array)$data;
}
foreach ($data as $name => $value) {
    $result[$name] = $value;
}
```

**Comment by SilverFire** [comment]
Casting to array is enough - no need to iterate over `$data` again.

**Comment by LAV45** [comment]
```php
$document = simplexml_load_string($xml);
var_dump($document instanceof \Traversable) // => true

$json = json_encode($document);
$data = json_decode($json, true);
var_dump($data);
/** return
array (
  'apiKey' => 'ieu2iqw4o',
  'modelName' => 'Address',
  'calledMethod' => 'getCities',
  'methodProperties' => 
  array (
    'FindByString' => 'Kiev',
  ),
)
*/
```

@joni-jones , in your case it is best to use standard php methods json_encode and json_decode

**Comment by joni-jones** [comment]
@LAV45 , now I use `json_encode/json_decode`, but it's little strange what `Json::encode()` brokes php methods.

**Comment by SilverFire** [comment]
Fixed https://github.com/yiisoft/yii2/commit/95edff3b1dc66829957f6999bd3c646d841e14d1
