### ISSUE TITLE
Declaring multiple relation to same table

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#10285]
I have the following schema: 
 * tournament(id, name)
 * game(id, tournamentId, team1Id, team2Id)
 * team(id, name)
 * player(id, name, teamId)

The game table will have 2 relation to the same table, team.

I am trying to create a relation in the Tournament model so that i get all the participated teams.

```php
public class Tournament extends ActiveRecord
{
    ...
    public function getGames()
    {
        return $this->hasMany(Game::className(), ['tournamentId' => 'id']);
    }

    public function getParticipatedTeams()
    {
        return $this->hasMany(Team::className(), [/*what should the link be?*/])->via('games');
    }
}
```

I tried to place the link as arrays as follows:
 * ['id' => ['team1Id', 'team2Id']]
 * [['id' => 'team1Id',], ['id' => 'team2Id']]

But those are not working, and i could not fing any solution from the web. Is it possible to do this kind of relation?

**Comment by Alex-Code** [comment]
Please use the forums for questions, http://www.yiiframework.com/forum/

You'd need two separate relations, `getTeamOne` `getTeamTwo` or a junction table.
* game(id, tournamentId)
* game_team (game_id, team_id)
* team(id, name)

**Comment by Locustv2** [comment]
I don't think a junction table would solve this problem. The junction table you added is between game and team and not between tournament and team. How would i still get the teams from the tournament model?
