### ISSUE TITLE
Описка

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#10280]
@samdark , ты наверно хотел написать server
https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/ServeController.php
```
~/www/site$ yii
...
- serve                        Runs PHP built-in web server
    serve/index (default)      Runs PHP built-in web server
```

**Comment by SilverFire** [comment]
Спасибо за внимательность, но это все таки не описка: [to serve](http://dictionary.cambridge.org/ru/%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/%D0%B0%D0%BD%D0%B3%D0%BB%D0%BE-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/serve_1)
