### ISSUE TITLE
ActiveRecord and MSSQL table names

### ISSUE THREAD

**Issue by szelest** [yiisoft/yii2#10293]
In my CartItem class that extends ActiveRecord I defined a function named tableName that returns my table name 'PARTS$Internet Customer Shopping Carts' However, below is an error message when I try calling the following CartItem::findAll(['Quantity'=>1]); 

SQLSTATE[42S02]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'PARTSWERX$Internet Customer Shopping'.
The SQL being executed was: SELECT \* FROM [PARTS$Internet Customer Shopping] [Carts] WHERE [Quantity]=1

It appeaser that the generated select statement has brackets in a wrong place.
It should be this:  [PARTS$Internet Customer Shopping Carts]
instead of [PARTS$Internet Customer Shopping] [Carts]

**Comment by darkdef** [comment]
Table name with spaces - does not allow you to get an alias from the table name (if you use non-strict sql syntax: "TableName t1", and not "TableName as t1").
The right way is to quote the table_name specified in dbEngine (for example, in MS SQL:
```php
    public static function tableName()
    {
        return '[PARTS$Internet Customer Shopping Carts]';
    }
```
