### ISSUE TITLE
Why was command line gii removed?

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii2#10300]
I had an old installation of Yii2 that had Gii command line generator. I'm using it to generate skeleton with my Editor. However, I have noticed major changes when I upgraded. We have new serve command (yay!) and gii is gone!

Is there any reason (an issue with reasoning why it was removed)? Is there any other way to generate sources without having to go to browser?

Thanks

**Comment by Faryshta** [comment]
1) do you have debug enabled? what is your console and common configuration?

**Comment by mtangoo** [comment]
I just cloned a basic app and its not there. I tried other template its not there.  It seems to me it was removed somewhere in commits. 

What do you mean by debug? You mean configuration? I. Will post it in the morning (it's night here)

**Comment by Faryshta** [comment]
do you have the vendor/yiisoft/yii2-gii folder installed?

**Comment by cebe** [comment]
@mtangoo it should not be removed, must be a bug somewhere.

**Comment by cebe** [comment]
this commit broke it: https://github.com/yiisoft/yii2-app-basic/commit/f60f7647c57d7ec535812c77fe34cc7b9020c403

**Comment by cebe** [comment]
fixed, thanks for reporting!

**Comment by mtangoo** [comment]
Wow! Thanks for fixing. I hope it didn't break advanced template also. 
Cheers

**Comment by mtangoo** [comment]
It works with basic template. I will check if there is any issue with advanced
