### ISSUE TITLE
PageCache should not cache errors

### ISSUE THREAD

**Issue by tahirm** [yiisoft/yii2#10308]
I am experiencing a problem with `PageCache` when there is an Error on the page. 

I have implemented `PageCache` filter for my actions in behaviors function of controller, it works fine and contents are served from cache for specified duration. 

`````
'pageCache' => [
    'class' => 'yii\filters\PageCache',
    'only' => ['display-all'],
    'duration' => 1800,
    'variations' => [Yii::$app->request->url, 'country-code'],
]

````
But when I have some server error on the page and view from `ErrorAction` is rendered, first time I see the error page but after that I get blank page with 500 status code in response until the cache is expired.

So is there any way to avoid `PageCache` from caching the page when there is an server error on page?

**Comment by samdark** [comment]
500 status code means error. Can you get from logs what's happened?

**Comment by tahirm** [comment]
@samdark  Are you asking about why the error happened or why im getting cached contents?
 
Regarding error I know why it happened and I fixed it, but since the contents were I cached i was still getting 500 response, even though the error was fixed. I reproduced it by intentionally introducing the error and then enabling the cache, but later i fixed the error but i was still getting cached contents.

So the main point is that I want to avoid caching contents when there is an server error. otherwise in production user can see the error for 30 minutes for example even though the error was fixed after 1 minute. but since the page was cached with error, user dont see the actual contents anymore.

**Comment by samdark** [comment]
I'm asking for the entry in logs for that 500 page that definitely should be there.

**Comment by samdark** [comment]
Ah.

**Comment by kidol** [comment]
@tahirm Could you test from master or apply patch #8613 manually? I think it should fix your problem.

**Comment by samdark** [comment]
#8614

**Comment by tahirm** [comment]
Thanks for fixing it guys. Sorry for late response. it works now.
