### ISSUE TITLE
Call afterAction even on exceptions?

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10306]
Currently when an exception is thrown in an action, afterAction is not called on any controller / module.

Shouldn't afterAction always run if beforeAction returns true?

My specific use case:
1. I have an API module.
2. This API module is used by some third party that does not handle response code. So in my after action I set the response code to 200 and store the real response code in a custom header.

When the controller action throws an exception I can't override the response code since afterAction never gets called.

--> I understand not wanting to change this because of BC, but maybe there should be some nice way to support letting these exceptions bubble up.

Currently I would have to override and copy the whole `\yii\base\Controller::runAction()` method just to add try / finally clause, also I would have to do this for every controller. 

Since the controller is in charge of calling the afterAction on each of its parents, there is no way to override this from a module.

Possible solutions would be to:
1. Move the actual execution (ie call to `$action->runWithParams()`) to a separate protected function, allowing for easy override.
2. Catching the exception, calling `afterAction()` and then rethrowing it (breaks BC).

Some rework in how / who is responsible for all of these calls could make for more intuitive behavior of the code in general. Currently module recurses to get the controller, then the controller recurses the other way to call before and after action on all parents.

Thoughts?

**Comment by samdark** [comment]
I don't think it should be called regardless. Action was terminated by unhandled exception so flow goes to error handler. You can make it return 200.

**Comment by uaoleg** [comment]
Such behavior looks really helpfull in case I whant to log API (webhook) request:

- using **init** method I can log **request** part
- using **afterAction** method I can log **response** part

But it some execption has been thrown than **response** part won't be logged
