### ISSUE TITLE
Get only related records when going down relations.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#10311]
I don't think this is a bug, but it would be a great feature/enhancement.

Assume this schema:
* category(id, name)
* article(id, categoryId, writerId, title, content)
* writer(id, name, age, location)

Category Model:
```php
    class Category extends ActiveRecord
    {
        ...
        public function getArticles()
        {
            return $this->hasMany(Article::className(), ['categoryId' => 'id']);
        }
    
        public function getWriters()
        {
            return $this->hasMany(Writer::className(), ['id' => 'writerId'])->via('articles');
        }
    }
```
Writer Model:
```php
    class Writer extends ActiveRecord
    {
        ...
        public function getArticles()
        {
            return $this->hasMany(Article::className(), ['writerId' => 'id']);
        }
    
        public function getCategories()
        {
            return $this->hasMany(Category::className(), ['id' => 'categoryId'])->via('articles');
        }
    }
```
Article Model:
```php
    class Article extends ActiveRecord
    {
        ...
        public function getCategory()
        {
            return $this->hasOne(Category::className(), ['id' => 'categoryId']);
        }
    
        public function getWriter()
        {
            return $this->hasOne(Writer::className(), ['id' => 'writerId']);
        }
    }
```

I want to get all articles written by a specific writer if i am starting at the category level. That is `category > writer > articles`, the articles should be only those belonging to the category.

Example:
```php
$category = Category::find()->with(['writers'])->where(['id' => 1])->one();
$articles = $category->writers[0]->articles;
```

In this case, `$articles` should be only those belonging to `$category`.

But in the case when `$writer = Writer::find()->....->one()`, then `$writer->articles` return all his articles

**Comment by klimov-paul** [comment]
> I want to get all articles written by a specific writer if i am starting at the category level.

I don't get it. Why start from category, if you want to get articles of the specific author?
The obvious solution for the taks will be:

```php
Article::find()->with(['writers', 'category'])->andWhere(['writerId' => $writerId])->all();
```

Or if there is a particluar category:
```php
Article::find()->with(['writers'])->andWhere(['writerId' => $writerId, 'categoryId' => $categoryId])->all();
```

Desribed feature make no sense.
