### ISSUE TITLE
Does not support PHP7

### ISSUE THREAD

**Issue by cevin** [yiisoft/yii2#10315]
```
PHP Fatal Error – yii\base\ErrorException

Uncaught Error: Call to undefined function yii\web\mb_strlen() in \path\vendor\yiisoft\yii2\web\ErrorHandler.php:394
Stack trace:
#0 \path\vendor\yiisoft\yii2\views\errorHandler\callStackItem.php(26): yii\web\ErrorHandler->argumentsToString(Array)
#1 \path\vendor\yiisoft\yii2\base\View.php(325): require('\path\...')
#2 \path\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('\path\...', Array)
#3 \path\vendor\yiisoft\yii2\web\ErrorHandler.php(233): yii\base\View->renderFile('\path\...', Array, Object(yii\web\ErrorHandler))
#4 \path\vendor\yiisoft\yii2\web\ErrorHandler.php(287): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#5 \path\vendor\yiisoft\yii2\views\errorHandler\exception.php(378): yii\web\ErrorHandler->renderCallStackIte
```

```
Warning: var_export does not handle circular references in \path\vendor\yiisoft\yii2\helpers\BaseVarDumper.php on line 187
```

**Comment by SilverFire** [comment]
What version of Yii do you use? Could you show `php -v` and `php -m` commands output?

**Comment by cevin** [comment]
PHP Version:

```
PHP 7.0.0RC8 (cli) (built: Nov 25 2015 14:17:20) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.4.0rc1, Copyright (c) 2002-2015, by Derick Rethans
```

Modules
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
gmp
hash
iconv
imap
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug
```

**Comment by cevin** [comment]
On linux, It's successfully.

**Comment by githubjeka** [comment]
@cevin How to reproduce?

**Comment by arisk** [comment]
For the error it looks like you don't have the `mbstring` extension installed?
For the warning Yii 1 had a similar issue with `var_export` and circular references.
https://github.com/yiisoft/yii/issues/1924

**Comment by cevin** [comment]
Yii version: 2.0.6

**Comment by SilverFire** [comment]
Could you try current dev version?

**Comment by cevin** [comment]
@SilverFire 

```
Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/7.0.0RC8
Yii Framework/2.0.7-dev
```

```
PHP Fatal Error – yii\base\ErrorException

Uncaught Error: Call to undefined function yii\web\mb_strlen() in \path\vendor\yiisoft\yii2\web\ErrorHandler.php:403
```

The extension `php_mbstring.dll` is loaded on php cli. but not worked on apache & php.

use command  `php -m` the mbstring in modules.  but use in browser, the mbstring it's not loaded.

**Comment by SilverFire** [comment]
Run `phpinfo()` on web, see for PHP config location (.ini) and fix it

**Comment by cevin** [comment]
@SilverFire  the `php.ini` is load success and not have any error.  maybe it's a php bug ? - -#

**Comment by vistart** [comment]
这是 Windows 版 PHP 独有的问题，与 PHP 7 无关，也与 Yii 无关。当前 Windows 存在多个版本时有很大概率会出现此问题。若解决此问题，请特别留意系统变量中的 PATH 变量、php.ini 和 Apache 中的 httpd.conf 之间的相互配合。
This issue of PHP only occurs in Windows version, it is not only a special issue of PHP 7, but also nothing to do with Yii. When there are multiple versions of  PHP in Windows, This issue will be a great probability. If you want to solve this problem, please note that with Windows Environment Variables, the path variable of php.ini, and path variable of httpd.conf.

**Comment by robert589** [comment]
I uploaded my yii2 advanced file to hosting server with php version 5.4, and i have this error

**Comment by cebe** [comment]
you need the mbstring extension to be installed.

**Comment by cevin** [comment]
new report.

PHP7.x on windows with mod_php will be fail, mbstring extension will not be loaded. Only run it on fastcgi with nginx it's will be okay.

**Comment by cebe** [comment]
in which way is that a Yii issue?

**Comment by dzb3688** [comment]
存在多个版本的php会存在问题。解决办法：
`php -m`
Warning: PHP Startup: Unable to load dynamic library 'C:\php\php_curl.dll' - 找不到指定的模块。in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\php_mbstring.dll' - 找不到指定的模块。in Unknown on line 0
复制ext目录*.dll 到'C:\php
![Uploading 20160405145344.png…]()

**Comment by cebe** [comment]
that is also not yii related but php configuration issue.
