### ISSUE TITLE
Deprecated error

### ISSUE THREAD

**Issue by alexweb** [yiisoft/yii2#10318]
Hi, I got the following error when send POST request to yii2 REST API:
```php
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated 
and will be removed in a future version. To avoid this warning 
set 'always_populate_raw_post_data' to '-1' in php.ini and use 
the php://input stream instead. in Unknown on line 0
```
My request component configuration:
```php
        'request' => [
            'class' => 'app\components\AppRequest',
            'cookieValidationKey' => '4454f6s4d5f6s4d5f4sd6f45ds4df',
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ]
        ],
```

I send application/json POST request in Advanced REST Client 
```php
{
"email":"user@example.com",
"password":"123123"
}
```
Any ideas?

**Comment by arisk** [comment]
@alexweb This has nothing to do with Yii. After you update your configuration in `php.ini` the error will go away.

**Comment by alexweb** [comment]
But what will happen if I update to php 7? Any workaround?

**Comment by arisk** [comment]
There is no deprecated code. You should update your `php.ini` so `$HTTP_RAW_POST_DATA` is no longer populated. Yii never uses and has never used `$HTTP_RAW_POST_DATA`

**Comment by alexweb** [comment]
So if change that settings it will work in php 7 too?

**Comment by arisk** [comment]
Should work just fine :-)

**Comment by alexweb** [comment]
Great! Thanks!

**Comment by SilverFire** [comment]
Try to stop XDEBUG session, if it's running.

**Comment by alexweb** [comment]
I don't use xDebug. Changing 'always_populate_raw_post_data' to '-1' helped.
