### ISSUE TITLE
Expose YII_ENV and/or YII_DEBUG to javascript

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2#10313]
Any chances that `YII_ENV` and/or `YII_DEBUG` constants can be exposed to javascript globally.

Use case: Sometime client-side script need information regarding debug state. The need rose in our project when we were working with `pjax` from javascript (not using Yii2-Pjax, because we needed custom implementation) and we were unable to set `timeout` based on `YII_DEBUG`. When using Yii2-Pjax extension we usually set timeout based on that info: `'timeout' => !YII_DEBUG`.

**Comment by SilverFire** [comment]
You can export it manually in your application asset. Is is not enough?

**Comment by samdark** [comment]
It should be. There's no need to have these exported by default.

**Comment by armpogart** [comment]
@SilverFire I don't get how can I export them in my AssetBundle, I mean the clean way to do it. In `js` field I can specify array of js files. Do you propose to include some js with global variable declarations only when in `YII_DEBUG`?

**Comment by SilverFire** [comment]
Yes. Something like `$this->registerJs('window.YII_DEBUG = true')`

**Comment by samdark** [comment]
Layout works well for the purpose.

**Comment by armpogart** [comment]
Ok, thanks. It is a solution, though it is a bit dirty. You need to remember to include it in all layouts, or views. So there won't be way to do it once and forget.

**Comment by samdark** [comment]
You can do it in controller or in another common place you choose.
