### ISSUE TITLE
Bootstrap assets are always loaded even if the dependecy is removed

### ISSUE THREAD

**Issue by Nosthertus** [yiisoft/yii2#10316]
I am trying to change the assets, the first reason for this is because i want to set a custom bootstrap made from less.. for now i am just trying to remove the bootstrap and then load other files that will replace the default bootstrap..

first, i tried removing the line `yii\bootstrap\BootstrapAsset'` in `AppAsset.php`, but even without this line, bootstrap is loaded, i thought it was because the server didn't send any header that changes the assets so i pressed `ctrl + f5` to force download. but still it is there

the second method i tried was adding this array in the `main.php` file and also removing the bootstrap dependecy in `AppAsset.php`

```php
'assetManager'=>[
	'bundles'=>[
		'yii\bootstrap\BootstrapAsset'=>[
			'sourcePath'=>'@webroot',
			'baseUrl'=>'@web',
			'css'=>['css/bootstrap.css']
		],
	],
],
```

at the first moment i saw that bootstrap was no longer being loaded from the default files, but my custom bootstrap isn't either and the console shows `/backend/web/assets/e8b935b7/css/bootstrap.css 404 (Not Found)`

**Comment by cebe** [comment]
> 'sourcePath'=>'@webroot',

you need to use `basePath` here. `sourcePath` will try to publish something.
