### ISSUE TITLE
VarDumper does not respect __debugInfo()

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10319]
When using VarDumper on an object that implements `__debugInfo()`, the `__debugInfo()` function is ignored.

http://php.net/manual/en/language.oop5.magic.php#language.oop5.magic.debuginfo

I think the "case" for object should definitely include a check for `__debugInfo()`.

**Comment by klimov-paul** [comment]
Resolved by commit 170c3766487e4470087ed9d94661b793d81a043b
