### ISSUE TITLE
FIND_IN_SET with WHERE in Active Record?

### ISSUE THREAD

**Issue by smilemd** [yiisoft/yii2#10326]
Is there a way to use FIND_IN_SET with WHERE without using findBySql in Active Record?

If not, could this be implemented? tnx.

PS: i don't get any answers about that on: http://www.yiiframework.com/forum/index.php/topic/68741-yii2-active-record-where-find-in-set/

**Comment by arisk** [comment]
Have you tried this? http://www.yiiframework.com/doc-2.0/yii-db-expression.html

**Comment by lichunqiang** [comment]
Your should use `yii\db\Expression`:
```
User::find()->where(new Expression('FIND_IN_SET(:status, status)'))->addParams([':status' => 1])->all();
```
