### ISSUE TITLE
PHP7 site/login session_regenerate_id

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#10325]
Related to https://github.com/yiisoft/yii2/pull/1812

I spent two days to get to this error
```
session_regenerate_id(): Failed to create(read) session ID: user (path: )
```

on PHP7RC8 `site/login` & `site/logout` just return 500 Error . There are no messages in any log. 

All because of this `@`.  https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L260

I'm very indignant

P.S. https://bugs.php.net/bug.php?id=70520
> [2015-10-19 05:11 UTC] jacky at xsteach dot com
i met the same problem on mac osx with php7RC5. I use yii2 framework with redis as session storage.It is ok when i install php7RC2, but get error session_regenerate_id(): Failed to create session ID: user (path: ). Is this issue fixed after RC3?

UPD: updated to php 7.0.0 . Same error.

UPD2: 

I commented the code
```
    'components' => [       
        //'session' => [
        //    'class' => 'yii\redis\Session',
        //    'timeout' => 60 * 60 * 24 * 30,
        //],
```
And now users can login & logout in site.

### Problems
1. What is wrong with `yii\redis\Session` .
2. Too much `@` in `vendor/yiisoft/yii2/web/Session.php` which hinder debugging

**Comment by samdark** [comment]
Can you try release of 7.0.0 w/o the fix first?

**Comment by githubjeka** [comment]
Too much @ in vendor/yiisoft/yii2/web/Session.php which hinder debugging

**Comment by samdark** [comment]
Any idea how to fix that?

**Comment by githubjeka** [comment]
In [this case](https://github.com/yiisoft/yii2/pull/1812)
`Warning: session_regenerate_id(): Session object destruction failed`

I also stumbled at this. This related with  public function [destroySession($id)](
https://github.com/githubjeka/yii2-redis/blob/fb83a885095b7ec3ce90ecdc3535b290a9aaa564/Session.php#L142)
http://php.net/manual/ru/function.session-set-save-handler.php

Similar fix is need as PR:
```
 $data = $this->redis->executeCommand('DEL', [$this->calculateKey($id)]);
 return $data === '' || $data === null ? false : true;
```

But I have burdened https://github.com/yiisoft/yii2/pull/1812#issuecomment-34112834

Another `@`  have no comment and therefore not very clear why hide the display of errors.

**Comment by samdark** [comment]
@githubjeka I think all these `@` are used in alike race condition cases.

**Comment by githubjeka** [comment]
But It just hide error, not fix:
> on PHP7RC8 site/login & site/logout just return **500 Error in browser** . There are no messages in any log.

Last thing I thought that Yii2 have `@` for understand why 500.

**Comment by samdark** [comment]
Well, in these cases, it's obviously wrong.

**Comment by githubjeka** [comment]
> This operator is affectionately known by veteran phpers as the stfu operator. 
Ok
