### ISSUE TITLE
'could not find driver' with sqlserver 

### ISSUE THREAD

**Issue by zuoRambo** [yiisoft/yii2#10329]
i have make and install the `freetds` and add the `mssql.so` to php.ini and the `mssql_connect` funtion works well,but when i config a `Connection` with 
```php
'dbSqlserver' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mssql:host=192.168.0.1;dbname=SKY',
            'username' => 'user',
            'password' => 'pwd',
        ],
```
i got the Exception info ` 'yii\db\Exception' with message 'could not find driver'`
what's wrong?

**Comment by SilverFire** [comment]
Seems not a problem of Yii. Check out [this SO question](http://stackoverflow.com/questions/20163776/connect-php-to-mssql-via-pdo-odbc?answertab=votes#tab-top)

**Comment by zuoRambo** [comment]
@SilverFire thanks, I have solved the problem. Below are the point,may be helpful for other developers.
When want to connect SqlServer by `PDO` in unix/linux platform, we need 'DBLIB' or 'freetds + odbc',
and the dsn string is 'dblib:host=....' or 'odbc:host=...'.
`'mssql:host=...'` will throw Pdo Exception: 'could not find driver'

**Comment by yuriEfin** [comment]
apt-get install php5-mysql
