### ISSUE TITLE
BC break in console app parameters

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#10323]
See https://github.com/yiisoft/yii2-gii/issues/107

**Comment by samdark** [comment]
Most probably caused by https://github.com/yiisoft/yii2/commit/ec27a2ee4886313cc3b5962f07975c2fb933d2e2

**Comment by samdark** [comment]
@mtangoo could you explore it a bit more?

**Comment by mtangoo** [comment]
Sure, its almost midnight here. I will do that tomorrow

**Comment by mtangoo** [comment]
So I made investigations and found [this line of code](https://github.com/yiisoft/yii2/commit/ec27a2ee4886313cc3b5962f07975c2fb933d2e2#diff-3f2a12dd38a81f2b0c96a4c9e6dd7eabR92) is the one that breaks things out.
```php
settype($value, gettype($default));
```

Commenting out makes things works (at least for generating a controller)

```bash
 php  yii  gii/controller --actions=index,edit,view --controllerClass=app\\controllers\\PosterController
Running 'Controller Generator'...

The following files will be generated:
        [new] controllers/PosterController.php
        [new] views/poster/edit.php
        [new] views/poster/index.php
        [new] views/poster/view.php

Ready to generate the selected files? (yes|no) [yes]:y

Files were generated successfully!
Generating code using template "/home/stefano/Desktop/yii2-app-basic-master/vendor/yiisoft/yii2-gii/generators/controller/default"...
 generated controllers/PosterController.php
 generated views/poster/edit.php
 generated views/poster/index.php
 generated views/poster/view.php
done!

```

**Comment by samdark** [comment]
@vchenin any ideas?

**Comment by pana1990** [comment]
i try to reproduced this issue but it works for me.

windows 7
php 5.6
yii 2.0.7
gii 2.0.5

**Comment by vchenin** [comment]
[already fixed](https://github.com/yiisoft/yii2/commit/f6b2c8f5bedd7b0f99b4bddfbd48efb15ce01251)
