### ISSUE TITLE
ActiveForm prevents button to open in new window (formtarget="_blank")

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#10322]
The **formtarget** directive is not working when the button is part of an ActiveFormorm.

```php
// This example does not work.  It submits the form data to the current window.
<?php $form = ActiveForm::begin(['method' => 'get']); ?>
        First name: <input type="text" name="fname"><br>
        Last name: <input type="text" name="lname"><br>
        <button type="submit" >Submit</button>
        <button type="submit" formtarget="_blank">Submit to a new window</button>
    <?php ActiveForm::end(); ?> 
```

```php
// This example works well. It submits the form data to a new window.
 <form id="w0"  method="get"> 
        First name: <input type="text" name="fname"><br>
        Last name: <input type="text" name="lname"><br>
        <button type="submit" >Submit</button>
        <button type="submit" formtarget="_blank">Submit to a new window</button>
  </form> 
```

**Comment by samdark** [comment]
Correct. `formtarget` isn't handled now in any way.

**Comment by twinni** [comment]
@samdark , isn't it a bug instead of an enhancement? The generated code for the button is ok. I assume that the activeForm.js handles the sumbit function without considering ``formtarget``.
Anyway, when you have a solution it would be great if you could solve it in 2.0.7.

**Comment by SilverFire** [comment]
I think it's an enhancement for JS ActiveForm plugin to support the `formtarget` attribute.
We are preparing the release, so 2.0.7 milestone is closed for new non-critical issues and PR.

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/fbedb8e750dbb752e43af718f4692c7d5d5e43d7
