### ISSUE TITLE
PHP 7.0.0 Released, is yii 2.0.6 FULLY compatible with it ?

### ISSUE THREAD

**Issue by duruitang** [yiisoft/yii2#10330]
The PHP development team announces the immediate availability of PHP 7.0.0. This release marks the start of the new major PHP 7 series.

PHP 7.0.0 comes with a new version of the Zend Engine, numerous improvements and new features such as

Improved performance: PHP 7 is up to twice as fast as PHP 5.6
Significantly reduced memory usage
Abstract Syntax Tree
Consistent 64-bit support
Improved Exception hierarchy
Many fatal errors converted to Exceptions
Secure random number generator
Removed old and unsupported SAPIs and extensions
The null coalescing operator (??)
Return and Scalar Type Declarations
Anonymous Classes
Zero cost asserts

**Comment by samdark** [comment]
http://www.yiiframework.com/news/92/php-7-released/

**Comment by zuoRambo** [comment]
good news

**Comment by Faryshta** [comment]
I compiled and ran php7 in a virtual machine.

2 of my projects ran flawlessly without any modification of the code whatsoever. There were no visible different between the php7 and php5.6 versions.
