### ISSUE TITLE
Yii::$app->user->isGuest for some reason checks findIdentity()

### ISSUE THREAD

**Issue by fridary** [yiisoft/yii2#10332]
In yii2 advanced app I have action with guest check:
```
public function actionLogin()
 {
        if (!Yii::$app->user->isGuest)
        ...
 }
```

I have modified `findIdentity($id)` in `common/models/User` from this:
```
public static function findIdentity($id)
{
        return static::findOne(['id' => $id]);
}
```
to this:
```
public static function findIdentity($id)
    {
        if (($model = static::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            throw new UserException('User not found');
        }
    }
```

now, if user is deleted and he is logged in (has session), message 'User not found' appears every time, I can not even `/logout`.

so, how to fix/mofidy `isGuest()` function? I have a lot of actions on my website that use `findIdentity($id)` and it is hard to modify them all to check whether user is nulled or not.

**Comment by klimov-paul** [comment]
@fridary, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
