### ISSUE TITLE
Ability to reload request cookies

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2#10339]
**Use case:**
We use geolocation function in yii Application::bootstrap() to geolocate the client and save his/her location in cookie. For this we check if cookie isn't set already, we add cookie with location value. Later on other pages we use the value of that cookie in several places. The problem is that when we first check for cookie existance `loadCookies()` is called and later on in application lifecycle it is never called again as it is already there see: https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L1198
So it turns out, though we have set the cookie in bootsrap and we rely on the fact that it is there, it actually is not there before another page (application) reload, when the cookies are read again.

So I propose to add something like `Yii::$app->request->reloadCookies()` or `Yii::$app->request->refreshCookies()`.

May I create PR request for that for Yii 2.0.7 release (it won't affect BC anyway)? We'll be happy to be able resolve the bug in our application (website) which is running on production now.

**Comment by cebe** [comment]
how do you add the cookie?

**Comment by armpogart** [comment]
Something like:
````php
if (!isset(Yii::$app->request->cookies['region_id'])) {
    $region_id = 'something';
    $cookie = new Cookie([
        'name' => 'region_id',
        'value' => $region_id,
        'expire' => time() + 30*24*60*60,
    ]);
    \Yii::$app->response->cookies->add($cookie);
}
````

And anywhere after doing this, I can't access that cookie, as it is actually not loaded. Because the cookies where loaded when I've done `if (!isset(Yii::$app->request->cookies['region_id']))`

**Comment by armpogart** [comment]
The problem wth my proposed solution is that I think that the problem overall discussed is not expected behavior. So we have also second approach to load cookies each time one access `Yii::$app->request->cookies` or if you think that is not optimal solution, the solution with adding reload function must be properly documented.

**Comment by AnatolyRugalev** [comment]
I think, the problem is that response and request cookies are two different collections. For me it is obvious to have data in request cookies that we had in beginning of request. And response collection is designed to send cookies, but not to store them.
Try this solutions:
1. You can check both collections every time
2. (better) Store current geolocation info in variable of geolocation application component. This solution will give you more control over cookies and related stuff

**Comment by quorzz** [comment]
@AnatolyRugalev  fully agreement ... that is not a bug  or even a shortcoming

**Comment by armpogart** [comment]
@AnatolyRugalev Thanks, I understand that they are two different collections, but I don't understand why we can't have reload function for example. If my application set's some cookie I expect it to be accessible. That will be the case also if we use PHP builtin cookies functionality without Yii wrappers, so I don't get why we can't have a little helper function there to reload it if needed. Also it will be wise to mention the behavior in documentation as for everyone coming from vanilla PHP coding that is the expected behavior.

@AnatolyRugalev Also I don't have any application component for geolocation as it is just one helper class, I don't need to wrap it in application component as it won't give me any additional value. So in my case I can't store it anywhere. The first approach you mentioned is working solution, but I'm reading that data at least in 5 places in my application, so it will be very ugly to check both collections in 5 places.

Any justification not to add additional method?

**Comment by AnatolyRugalev** [comment]
How do you suppose to do that? Request component sends them only at the end of request, this is by design
```php
// CookieCollection
public function reload() {
    $this->_cookies = ArrayHelper::merge(Yii::$app->request->loadCookies(), Yii::$app->response->getCookies());
}
```
Is this what you want to do? :question:

**Comment by armpogart** [comment]
@AnatolyRugalev Hmmm... I see, it send cookies with headers, which is already late for the php script to read them. So, yes, I don't see any other option that something like your written. But I'm not sure that it is the right way to do it.

But at the end I'm for adding such functionality or at least mentioning it in documentation with the suggested (recommended) way to access just set cookies, because it is expected to have your cookies ones they're set, at least in PHP, so if Yii does something different from that it is worth mentioning it.

**Comment by AnatolyRugalev** [comment]
@armpogart this is exactly what you can find in [docs](https://github.com/yiisoft/yii2/blob/master/docs/guide/runtime-sessions-cookies.md#cookies-)
