### ISSUE TITLE
Connection::useSlave()

### ISSUE THREAD

**Issue by drscre** [yiisoft/yii2#10331]
We already have `Connection::useMaster()` which forces the execution of db queries on master.

But sometimes an opposite is required: to force the execution of db queries on a slave.

For example, you might need to set some variables affecting subsequent selects like

SET SESSION group_concat_max_len = 1024

or to create in-memory temporary tables for complex selects

CREATE TEMPORARY TABLE product_sort ... ENGINE = MEMORY
INSERT INTO product_sort ...
SELECT \* FROM products INNER JOIN product_sort ORDER BY product_sort.srt

It is possible to force a command to run on slave by explicitly calling `command::prepare(TRUE)`, but it would be nice to have a shortcut method

**Comment by dynasource** [comment]
considering your usecases and the fact that `prepare()` accepts a forcing slave parameter, it makes sense to also have a `useSlave` method in Connection

**Comment by samdark** [comment]
Agree.

**Comment by kiros32** [comment]
Any news?)

**Comment by dynasource** [comment]
we're waiting for a PR

**Comment by drscre** [comment]
Is anybody working on PR?

**Comment by samdark** [comment]
Seems not.

**Comment by des1roer** [comment]
need useSlave

**Comment by samdark** [comment]
Won't be implemented in 2.0.
