### ISSUE TITLE
vendor\fzaninotto\faker\src\Faker\Provider

### ISSUE THREAD

**Issue by devjana** [yiisoft/yii2#10333]
Inside folder provider i found some others folders like en_Us
when I read the file text.php I didn't understand anything can anyone explain what role 
of this text.php and licence exist in the bottom of the file?

**Comment by samdark** [comment]
You mean https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/en_US/Person.php? These are fake data provides for various types of data.

**Comment by devjana** [comment]
no I mean this https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/en_US/Text.php
in the line 3368 there is  laws
what's the diffrent bettween this and the yii licence

**Comment by samdark** [comment]
Ah, that's the license to ALICE'S ADVENTURES IN WONDERLAND book text used in Faker :)

**Comment by devjana** [comment]
you mean framwork use the text from the book because of that they integrate the licence,

**Comment by samdark** [comment]
Yes.

**Comment by devjana** [comment]
so the are no relation bettwen the yii licence and the licence integrate in faker

**Comment by samdark** [comment]
None.

**Comment by devjana** [comment]
you mean "None" they are no relation

**Comment by samdark** [comment]
Yes.
