### ISSUE TITLE
server info is visible even after debug if false.

### ISSUE THREAD

**Issue by ajkosh** [yiisoft/yii2#10340]
when any errorexception and  fatal error occurs they are showing sever info.i set debug is false in entry script but still it is showing.
then i set below lines in config file components.
```
 'errorHandler' => [
            'errorAction' => 'site/error',
            'errorView' => '@app/views/site/error.php',
            'exceptionView' => '@app/views/site/error.php',
        ],
```

now it is handling but no appassets are loading in error page if exception error hit.

**Comment by samdark** [comment]
We need a way to reproduce it. Can you do it with fresh basic app?

**Comment by ajkosh** [comment]
yes i checked with new basic app.
i changed following things.
in site view/contact.php
```
<div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name1') ?> //here i chnged name to name1 for error
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
````
after change attribute name it is giving exception.so i changed in config file now.
```
  'errorHandler' => [
            'errorAction' => 'site/error',
             'exceptionView' => '@app/views/site/error.php',
        ],
```
now it is showing error as string file ,see attachment

1 why layout is missing for error view if i set  'exceptionView' => '@app/views/site/error.php' and any exception occurs. 

2 why it shows server info even debug is set to false in entry script.see 2nd attachment.(this can be handled by set  'exceptionView' => '@app/views/site/error.php' )
![screenshot from 2015-12-07 14 22 13](https://cloud.githubusercontent.com/assets/8582472/11622762/0fc65c4c-9cee-11e5-92a5-3ad0adb672e6.png)

![screenshot from 2015-12-07 14 11 36](https://cloud.githubusercontent.com/assets/8582472/11622668/5dcc862e-9ced-11e5-8dda-983e9289b204.png)

**Comment by klimov-paul** [comment]
You have a error inside your `error.php` view, thus you see the error handler fallback error representation.
Still, it is not good to expose `$_SERVER` in this case.

**Comment by ajkosh** [comment]
This can be handled by set  'exceptionView' => '@app/views/site/error.php', but why layout is missing when it render to error.php.

**Comment by klimov-paul** [comment]
Are you able to read? Your application tells your all the resons pretty well:

> Notice: Undefined variable: name in /var/www/html/testapp/views/site/error.php line 10

**Comment by ajkosh** [comment]
i know name is not set in model but my purpose was creating error and show you server info if any exception happens. 
this is written in yii2 docs
The error handler is enabled by default. You may disable it by defining the constant YII_ENABLE_ERROR_HANDLER to be false in the entry script of your application.
so i did this but nothing effective
defined('YII_ENABLE_ERROR_HANDLER') or define('YII_ENABLE_ERROR_HANDLER', false);
defined('YII_DEBUG') or define('YII_DEBUG', false);

**Comment by samdark** [comment]
@ajkosh Paul is trying to tell you that there's an error in error handing view. That's why it's falling back to plain text.

**Comment by ajkosh** [comment]
i want to handle exception and render this error to error.php,so my question is why application layout is missing.when i set this to config file.
```
'errorHandler' => [
            'errorAction' => 'site/error',
             'exceptionView' => '@app/views/site/error.php',  // i m setting this
        ], 
```

**Comment by klimov-paul** [comment]
> but why layout is missing when it render to error.php.

That is why.

**Comment by samdark** [comment]
Server info in this case should not be displayed definitely.

**Comment by ajkosh** [comment]
ok so i handled this .how i can add layout to my error page is there option so i can set layout for 
'exceptionView' .

**Comment by klimov-paul** [comment]
Unable to reproduce: no `$_SERVER` information output performed in case any error occur during error view rendering. Only `An internal server error occurred.` text displayed.

**Comment by ajkosh** [comment]
did you set debug false.
but i installed new app ,nothing i changed.

**Comment by samdark** [comment]
@ajkosh are you using master version of Yii? I remember I've fixed something like that after 2.0.6...

**Comment by klimov-paul** [comment]
#6419

**Comment by ajkosh** [comment]
i installed using composer and following is in my json file
"yiisoft/yii2": "*",

**Comment by klimov-paul** [comment]
@ajkosh, try to start from the bigininng: what are the steps to reproduce the problem in details?

**Comment by ajkosh** [comment]
may be my mistake i checked now composer is not updating yii2 if this issue is fixed recently .i m using 2.0.6 when i update some composer error are coming.
so dont know this can be issue.
