### ISSUE TITLE
Any plan for translate strings in default views?

### ISSUE THREAD

**Issue by su-xiaolin** [yiisoft/yii2#10348]

**Comment by AnatolyRugalev** [comment]
@su-xiaolin, what views are you talking about?

**Comment by su-xiaolin** [comment]
app/views/site/*.php

**Comment by SilverFire** [comment]
I think your question relates https://github.com/yiisoft/yii2-app-basic or https://github.com/yiisoft/yii2-app-advanced

Could you, please, re-create it there?
