### ISSUE TITLE
bug in dropColumn() public method

### ISSUE THREAD

**Issue by Kerych74** [yiisoft/yii2#10349]
yii\db\Migration » yii\base\Component » yii\base\Object dropColumn() public method doesn't work with sqlite
![screenshot 2015-12-08 02 30 52](https://cloud.githubusercontent.com/assets/14916179/11645519/6a3dd274-9d55-11e5-831b-7eeb9f810dc2.png)

**Comment by unclead** [comment]
Sqlite does not support drop column. Look at answer on SO: http://stackoverflow.com/a/8442173
