### ISSUE TITLE
PHP7.0 upgrade show error Constructor failed in MessageFormatter

### ISSUE THREAD

**Issue by heartshare** [yiisoft/yii2#10342]
IntlException

Constructor failed
r/yiisoft/yii2/i18n/MessageFormatter.php at line 102
93949596979899100101102103104105106107108109110111            return $this->fallbackFormat($pattern, $params, $language);
        }
 
        if (version_compare(PHP_VERSION, '5.5.0', '<') || version_compare(INTL_ICU_VERSION, '4.8', '<')) {
            // replace named arguments
            $pattern = $this->replaceNamedArguments($pattern, $params, $newParams);
            $params = $newParams;
        }
 
        $formatter = new \MessageFormatter($language, $pattern);

**Comment by Faryshta** [comment]
which yii2 version are you using? I think this commit already fixed it https://github.com/yiisoft/yii2/commit/97f2fca72ff24a1a6cc12786eb063c17041e2009 but it hasn't been released yet. I think you have to use `dev` on composer and run `composer update`

**Comment by heartshare** [comment]
Yii Version 	2.0.6

    changed
    "yiisoft/yii2": "^2.0.6@dev",
    to
    "yiisoft/yii2": "dev-master",
    
    and run composer update, now version is : Yii Version 	2.0.7-dev
but it still show error after upgrade php 7
    
vendor/yiisoft/yii2/i18n/MessageFormatter.php at line 101

**Comment by heartshare** [comment]
intl

Internationalization support	enabled
version	1.1.0
ICU version	4.2.1

**Comment by SilverFire** [comment]
Run the requirements checker as described in the [guide](http://www.yiiframework.com/doc-2.0/guide-start-installation.html#verifying-installation)

It seems you don't have ICU data

**Comment by samdark** [comment]
Well, check with `master` branch. I've fixed it there.

**Comment by heartshare** [comment]
ICU version	Warning	Internationalization support	ICU 49.0 or higher is required when you want to use # placeholder in plural rules (for example, plural in Formatter::asRelativeTime()) in the yii\i18n\Formatter class. Your current ICU version is 4.2.1.
ICU Data version	Warning	Internationalization support	ICU Data 49.1 or higher is required when you want to use # placeholder in plural rules (for example, plural in Formatter::asRelativeTime()) in the yii\i18n\Formatter class. Your current ICU Data version is (ICU Data is missing

Yes thanks

**Comment by skylei** [comment]
@samdark High version of the switch will not appear compatible?

**Comment by SilverFire** [comment]
@skylei what kind of switch are you  talking about?

**Comment by skylei** [comment]
@SilverFire 
Thank you. I've already solved it!

**Comment by georgekaf** [comment]
I can confirm this issue.

I had to recompile ICU (v56.1) in my server (Centos 6), because the repo won't  go beyond 4.2.1, and then you either recompile your whole php installation (if you have a custom installation) or you uninstall intl.so and reinstall it using pecl/yum.

**Comment by samdark** [comment]
Yep. That's server config issue. We've documented it already.
