### ISSUE TITLE
Getting Error: Unknown command "test", while running the console command.

### ISSUE THREAD

**Issue by chaitenyay** [yiisoft/yii2#10345]
I am trying to create the console command and follow the instruction given in doc.

I created a file into console/controllers/TestController.php

<?php
namespace console\controllers;

use yii\console\Controller;
use yii\helpers\Console;

class TestController extends Controller
{
   public function actionIndex()
    {
        echo "Hello world.";        
    }
}

While  I am running the following commad into cli, getting below error message.

$ yii test
Error: Unknown command "test".

Please let me know, what I missed.

**Comment by rugabarbo** [comment]
Does your console's configuration contain this line?
```
[
    ...
    'controllerNamespace' => 'console\controllers',
    ...
];
```

**Comment by chaitenyay** [comment]
Thanks rugabarbo for the prompt reply.
