### ISSUE TITLE
HttpBasicAuth does not follow AccessFilter rules

### ISSUE THREAD

**Issue by EmadOmar** [yiisoft/yii2#10357]
I have already looked at the source code, and I know that `HttpBasicAuth` performs without checking `AccessFilter` rules. And this does not allow some actions to be accessed without authorization.

For instance, the following defined behaviors should prevent non-authorized requests from accessing all actions but `index` action.

```php
public function behaviors() {
    $behaviors = parent::behaviors();

    $behaviors['authenticator'] = [
        'class' => HttpBasicAuth::className(),
        'auth' => [$this, 'authenticateUser'],
    ];

    $behaviors['access'] = [
        'class' => AccessControl::className(),
        'rules' => [
            ['allow' => true, 'roles' => ['@'],],
            ['actions' => ['index'], 'allow' => true, 'roles' => ['?'],],
        ],
        'denyCallback' => [$this, 'denyCallback'],
    ];

    ...

    return $behaviors;
}
```

Regardless of what defined in `AccessFilter` rules, `HttpBasicAuth` denies accessing to `index` action although it should be allowed.

I suggest putting an option like `handleFailure` or `shouldHandleFailure` which disables the call of `\yii\filters\auth\AuthInterface::handleFailure()` when set to false, and let `AccessFilter` take care of the rest.

**Comment by SilverFire** [comment]
I guess you can do something like:

```php
    $behaviors['authenticator'] = [
        'class' => HttpBasicAuth::className(),
        'except' => ['index'],
        'auth' => [$this, 'authenticateUser'],
    ];
```

Also take a look at https://github.com/yiisoft/yii2/issues/7405 and this PR http://github.com/yiisoft/yii2/pull/10188.

**Comment by EmadOmar** [comment]
Err .. I am sorry it slipped my mind. Another question, why not letting `AccessFilter` handle unauthorized access. And make `AuthMethod` sub classes only handle invalid authentication credentials?

This was mentioned here https://github.com/yiisoft/yii2/issues/7776#issuecomment-83110193 too.

**Comment by SilverFire** [comment]
I think it shouldn't be mixed because of application design. Authentication is not a task for `AccessFilter`, it may be handled globally or even hardcoded - it does not matters. `AccessFilter` just filters request with some set of rules.
