### ISSUE TITLE
Race condition in yii.js's script filter

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#10358]
The script filter in yii.js which prevents loading the same script twice has a race condition.
When a script file is first loaded, the ajax request is allowed to go through, and the script is added to loadedScripts. If the same script file is requested again while the first request is still loading, it will immediately be aborted. However, the script is not yet loaded, so subsequent scripts that might depend on this file will fail.

This does not cause a problem with $.html and friends, because they use synchronous ajax to load the scripts. However, this is deprecated, and will hopefully be fixed in jquery 3.0: https://github.com/jquery/jquery/issues/1895. Pjax also does it asynchronously: https://github.com/yiisoft/jquery-pjax/commit/7a47df7b36d1031fbd576929e040ebab588b207b

So e.g. loading two pjax partials which both have an activeform (and thus need yii.activeform.js)  at the same time will cause the second one to break, because the inline script will execute before yii.activeform.js is loaded (assuming the base page didn't load yii.activeform.js).

**Comment by SilverFire** [comment]
> Pjax also does it asynchronously: yiisoft/jquery-pjax@7a47df7

`$.getScript(src).done(next).fail(next)` does it work asynchronously? It calls for the next JS only when previous is done or failed, it was the main idea. Or I have misunderstood you?

> If the same script file is requested again while the first request is still loading, it will immediately be aborted. 

Why the new JS could be requested again? 
We have three ways to get a new JS: as a result of AJAX or PJAX requests or not as a result of request (loaded JS injects another `<script>`).
Both of the AJAX and PJAX requests are being passed through `ajaxPrefilter`. The third option is not a normal behaviour at all, so I think we shouldn't take care of it.

**Comment by nkovacs** [comment]
> $.getScript(src).done(next).fail(next) does it work asynchronously? It calls for the next JS only when previous is done or failed, it was the main idea. Or I have misunderstood you?

"only when previous is done or failed" -> that's the problem. The prefilter will fail the script that's already loaded, even though it's still loading. So next will run, and it will execute the inline script.

> Why the new JS could be requested again? 

You click a pjax link, which loads a page that contains activeform. yii.activeform.js is requested, it runs through ajaxPrefilter, and is added to loadedScripts immediately. Before it finishes loading however, you click another link that loads a different page that contains activeform (or even the same link), which again requests yii.activeform.js. Since yii.activeform.js is in loadedScripts, the request for it will immediately be aborted, triggering the evaluation of the next script. If yii.activeform.js has not loaded yet, the inline script will fail.

**Comment by nkovacs** [comment]
The solution would be to store promises in `loadedScripts`, resolve them when the first xhr finishes, and only abort the subsequent xhrs when the promises are resolved. You could even store the xhr object itself, since it also implements the Promise interface.

**Comment by SilverFire** [comment]
Now it's clear for me, thank you very much for the detailed explanation.

Would you like to deal with it and make a PR? :)

**Comment by Alex-Code** [comment]
Just hacked this together as a test.
For responses that contain `HTML` it will parse out the inline script tags, These could then be run after all `ajax` requests have completed.

```js
var scripts = [];
jQuery.ajaxSetup({
    converters: {
        "text html": function(value) {
            return $.map($.parseHTML(value, true), function(item) {
                if ('SCRIPT' === item.nodeName && !item.src) {
                    scripts.push(item);
                } else {
                    return item;
                }
            });
        }
    }
});
```

**Comment by SilverFire** [comment]
@nkovacs could you check the PR https://github.com/yiisoft/yii2/pull/12651

**Comment by nkovacs** [comment]
I'll take a look, thanks.

**Comment by Alex-Code** [comment]
Would something like this work?
```javascript
var remote = [],
    inline = [],
    css = [];
jQuery.ajaxSetup({
    converters: {
        "text html": function(value) {
            return $('<div>').append($.map($.parseHTML(value, document, true), function(item) {
                if ('SCRIPT' === item.nodeName) {
                    !item.src ? inline.push(item) : remote.push(item.src);
                } else if ('LINK' === item.nodeName && 'stylesheet' === item.rel.toLowerCase()) {
                    css.push(item);
                } else {
                    return item;
                }
            })).html();
        }
    }
});
$(document).ajaxComplete(function(event, xhr, settings) {
    if ('html' === settings.dataType) {
        var next = function() {
            var script = remote.splice(0, 1);
            script.length ? $.getScript(script[0]).done(next) : $(document.body).append(inline.splice(0));
        };
        next();
    }
});
```

This would pick out all `script` elements and after fetching all remote scripts it would then add the inline scripts.

**Comment by SilverFire** [comment]
@Alex-Code thank you for the idea, but it looks rather as a hack. I'd not like to implement it

**Comment by Alex-Code** [comment]
It's all standard `jQuery`.
This has a couple advantages over the existing in that it catches `<link rel="stylesheet" />` elements before they're added to the page and inline scripts are delayed until all remote scripts have been run.

It's not a complete solution as it doesn't do any if the reloadable script checks yet.
