### ISSUE TITLE
What's the best use of component, can we write the business logic inside the component?

### ISSUE THREAD

**Issue by chaitenyay** [yiisoft/yii2#10353]
I am new to yii2 and just want to understand, how to use component efficiently. Can we write business logic in-side the component.
e.g.
Reading the jobs from DB and doing some processing with respect to the jobs and updating the status again.

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for bug reports.

**Comment by chaitenyay** [comment]
As per the request, I posted the question on forum. Request you to reply
http://www.yiiframework.com/forum/index.php/topic/68841-whats-the-best-use-of-component-can-we-write-the-business-logic-inside-the-component/
