### ISSUE TITLE
Support wildcard category name in messages config

### ISSUE THREAD

**Issue by rmrevin** [yiisoft/yii2#10359]
Hello.
There was a need to ignore certain dictionaries of translation. The application uses the following configuration:
```php
    'component.i18n' => [
        'class' => yii\i18n\I18N::className(),
        'translations' => [
            'myapp*' => [
                'class' => yii\i18n\PhpMessageSource::className(),
                'basePath' => '@base/messages',
            ],
        ],
    ],
```

And there are two different sources of translations (one in the application, the other at the level of cmf). I need to do at the application level to ignore the directory like this:
```php
return [
    'sourcePath' => __DIR__ . '/..',
    'messagePath' => __DIR__,
    'languages' => ['en', 'ru', 'de'],
    'translator' => 'Yii::t',
    'except' => [
        // ...
    ],
    'ignoreCategories' => [
        'myapp*',
    ],
    'only' => ['*.php'],
    'format' => 'php',
];
```

But the framework only supports exact match name. It may be better to make the ability to support this construction. Or make a separate verification method that I can override it.
https://github.com/yiisoft/yii2/blob/master/framework%2Fconsole%2Fcontrollers%2FMessageController.php#L481

**Comment by rmrevin** [comment]
Create pull request?

**Comment by SilverFire** [comment]
@rmrevin could you please explain the expected result?
Your wildcard in config
```php
    'ignoreCategories' => [
        'myapp*',
    ],
```
should match `myapp/one`, but not `myapplication/one`, correct?

**Comment by rmrevin** [comment]
I think that everything should be ignored.
Since of the i18n design `myapp*` means any coincidence, for example: `myapp.some`, `myapplication`, `myapp/some/test`, etc.

**Comment by samdark** [comment]
So the change is about `message` console command only and is about supporting wildcard in `ignoreCategories`. Makes sense. Feel free to create PR.

**Comment by SilverFire** [comment]
Merged https://github.com/yiisoft/yii2/commit/b6054acdb227bd6b8e3bed39c6d04fd0ece02552
