### ISSUE TITLE
How to create Virtual relations with ActiveRecords 

### ISSUE THREAD

**Issue by nadeemse** [yiisoft/yii2#10361]
Problem:

We are facing problem with statistics data, like on our business model customer has orders, reward points, feedbacks, complaints and some more relations.

when we run a get one customer we have to find all orders, max order, min order, number of order placed by customer in one branch, highest order by branch all these data is required to generates graphs.

how we are using it right now is to create multiple relation in model and get like this.

```
 $model = Customer::find()
            ->with([
                'firstOrder',
                'highSumOrder',
                'lowestSumOrder',
                'orderSourceCount',
                'order',
                'loyalty'
            ])
            ->where(['id' => $id])
            ->one();
```
And for this we are creating to many functions in model class that i don't want, so i am if there is any way to achieve this by virtual relationship like we define only one relation and utilized that for all possibilities.

eg.
```
$model = Customer::find()
            ->with([
                'order as FirstOrder' => function($query) {
                     $query->orderBy(['date' => SORT_ASC])->limit(1)
               },
                'order as highestSum' => function($query) {
                     $query->orderBy(['total_sum' => SORT_DESC])->limit(1)
               },
               .
               .
               .
            ])
            ->where(['id' => $id])
```
Like in above example we will use "order" as base relation and create FirstOrder from base relation.

**Comment by Faryshta** [comment]
related #6951

**Comment by SamMousa** [comment]
My implementation of 'Virtual Fields' #8316 would solve your problem.

Added advantage is that it doesn't use join so it won't break other queries when using joinWith.

The problem with using 1 relation for multiple aggregations is that they fail or become overcomplicated as soon as there are other joins / groupings in place.

**Comment by bebr42** [comment]
A 'client server approach' to the problem: Create a view in the database that produces just the values and names you want. Access it in Yii just like a (separate) table, only UPDATE (save) will not work.
The performance should also be much butter, at least with real DBs like PostgreSQL.

**Comment by SilverFire** [comment]
Please, see https://github.com/yiisoft/yii2/issues/12491 and https://github.com/yiisoft/yii2/commit/2250612cb861947c3fcaab91f0d60d116978a88e for the solution
