### ISSUE TITLE
Two login in yii2 ( Student and Tutor )

### ISSUE THREAD

**Issue by daskon** [yiisoft/yii2#10366]
Please give me the code solution for this issue. I have a Assignment to do. my DB has two tables, one for Tutor another one for users. users table is used to login to the system as student. and same goes for Tutor table. up to now students can login. but can't login Tutor. when I'm entering Tutor login details it goes to users login. this Assignment is kind of Student feedback portal. using Yii2.
( can i do something by using 'switchIdentity()' or loginByCookie() )
PLEASE HELP ME GENTLEMEN-TS !!

**Comment by SilverFire** [comment]
GitHub is for bug reports. Please use [forum](www.yiiframework.com/forum/) for questions.

**Comment by daskon** [comment]
Okay, where is this forum ? i can't login page not found

**Comment by agungsijawir** [comment]
@daskon http://www.yiiframework.com/forum/
