### ISSUE TITLE
Yii2: arrayDataProvider get model

### ISSUE THREAD

**Issue by dungphanxuan** [yiisoft/yii2#10367]
Hi team, i have issues when cal getModels() method with ArrayDataProvider.
I have data `['a','b','c']`.

```php
$dataProvider = new ArrayDataProvider([
            'allModels' => ['a','b','c'].,
            'pagination' => [
                'pageSize' => $limit,
            ],
        ]);
```

when i call data with limit=2 and page = 1. i getModels() then receive data:

```
"a",
"b"
```

So when i call with limit=2 and page =2. so data not correct:

```
2: "c"
```

So, what i missing or error!

**Comment by SilverFire** [comment]
What is expected result as for you? The result looks OK.
PageSize 2, Page 2 = SQL LIMIT 2 OFSET 2

**Comment by samdark** [comment]
Лучше об этом спросить на форуме или в чате.
