### ISSUE TITLE
Double formatting in i18n fallback 

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#10363]
When intl extension is not available, fallback formatting works wrong for double values:

```php
echo Yii::t('app', 'Here is a big number: {n, number}', ['n' => 2e+8]);

// Intl: Here is a big number 200,000,000
// No intl: Exception(Message format 'number' is only supported for integer values. You have to install PHP intl extension to use this feature
```

Expected: float should be formatted as with intl

[MessageFormatter.php:344](https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageFormatter.php#L344)

**Comment by AnatolyRugalev** [comment]
@SilverFire, I'm stuck on this:
```
1) yiiunit\framework\i18n\FallbackMessageFormatterTest::testNamedArguments with data set #3 ('Here is a big number: {f, number}', 'Here is a big number: 200,000,000', array(200000000.0))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Here is a big number: 200,000,000'
+'Here is a big number: 200000000'
/home/travis/build/yiisoft/yii2/tests/framework/i18n/FallbackMessageFormatterTest.php:151
/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:36
```
Is it really needs to split thousands as with `intl`?

**Comment by AnatolyRugalev** [comment]
I don't see that current implementation supports any number formatting, we are getting just plain number:
[MessageFormatter.php:345](https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageFormatter.php#L345)

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/3b31aa771a4f59cbf4bc01202a3f29e994f14cdd
