### ISSUE TITLE
docs: bad octal number representation

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii2#10369]
That's what we see in [docs](http://www.yiiframework.com/doc-2.0/yii-helpers-basefilehelper.html#createDirectory()-detail):

```php
public static boolean createDirectory ( $path, $mode = 509, $recursive = true )
```

And in the source:

```php
public static function createDirectory($path, $mode = 0775, $recursive = true)
```

**Comment by samdark** [comment]
Nice catch.

**Comment by cebe** [comment]
I do not think apidoc has any chance to detect that the original representation was not decimal but octal...

**Comment by samdark** [comment]
If it's `mode` it's usually octal, isn't it?

**Comment by samdark** [comment]
We can make an exception...

**Comment by cebe** [comment]
mode can mean anything depended on the context :) Of course we could hardcode all the places we know in Yii but that could mess up the apidoc generator a bit.

**Comment by samdark** [comment]
Could it be exposed in config?

**Comment by cebe** [comment]
I am open for ideas on how to solve this, I do not see a good way right now, may reopen it, maybe someone has an idea about it.

**Comment by SilverFire** [comment]
Maybe we can handle it with a special PHPDoc comment?

**Comment by hiqsol** [comment]
This is rough, but it's enough for the problem and suitable for similar situations when you can be sure that this const is used only in special representation. 

```php
protected static $_specialConsts = [
  '509' => '0775',
  ...
] ;

public function renderConst ($value) 
{
  if (isset(static::$_specialConsts[(string) $value]) {
    return static::$_specialConsts[(string) $value] ;
  } 
  return somedefaultrenderconst($value);
} 
```

**Comment by cebe** [comment]
@hiqsol want to send a PR to apidoc extension?
