### ISSUE TITLE
Console help incorrect when using DI

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10372]
When using Dependency Injection, the console helper lists the injected dependencies as command parameters:

```
DESCRIPTION

Grants specified role to the user.


USAGE

yiic auth/grant <user> <authManager> <userId> <roleName> [...options...]
```

In this case `user` and `authManager` are type hinted for DI in the controller action. 
The console helper could detect this and skip them, since it is never possible to pass php objects as command line arguments.

**Comment by samdark** [comment]
Good catch. Do you want to work on a pull request?

**Comment by SamMousa** [comment]
Can do.

**Comment by samdark** [comment]
Great. Thank you.

**Comment by SamMousa** [comment]
#10457

**Comment by SamMousa** [comment]
Can this be reopened?
I realize that DI in controller actions never made it to a release version if Yii, however the arguments for this change still stand.

Since the commandline only supports passing in strings anything that cannot be coerced from a string can be hidden from the help.

Suppose I have an action with the following signature:
````
class Foo extends ... {

    public function actionBar(Connection $db) {

    }
}
````
Leaving out the question of whether this would work when executing: `yiic foo/bar` (by default it would not).

The help given does not make sense since there is no way for me to pass the given type. My proposal is to hide these parameters from the help. This changes behavior in 2 cases:
1. The code is wrong: The user gets an error about a missing argument but in the help he cannot see anything about that argument.
2. The code is right (implements DI): The user gets proper help.

Also it would be nice to support PHP7 type hints:
````
class Foo extends ... {
    public function actionBar(int $number) {

    }
}
````

**Comment by SamMousa** [comment]
@cebe If I recreate the PR (that adds tests and fixes help) would you merge it?

Alternatively you could cherry-pick it and fix the changelog.

**Comment by samdark** [comment]
Yes, it makes sense.

**Comment by mishamosher** [comment]
I've noted that declaring the console action parameters with a supported type (`string`, `int`), the console help skips them. Is this intended?

**Comment by samdark** [comment]
Likely not but that's a separate issue. Please report it separately. Thanks.
