### ISSUE TITLE
Call to undefined method yii\web\View::getDb()

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#10388]
When I call following function at time throw PHP Fatal Error – yii\base\ErrorException(Call to undefined method yii\web\View::getDb()).

```php
    public function getCollegeList()
    {
		$clgData = self::find()->orderBy('college_name ASC')->asArray()->all();
		return \yii\helpers\ArrayHelper::map($clgData, 'college_id', 'college_name');
    } 
```

Why the call this fatal error?

**Comment by samdark** [comment]
Please provide stacktrace.

**Comment by hirenbhut93** [comment]
I call above function in following ActiveRecord class.
```
class College extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'college';
    }
    
    -------------------------------
    
    public function getCollegeList()
    {
		$clgData = self::find()->orderBy('college_name ASC')->asArray()->all();
		return \yii\helpers\ArrayHelper::map($clgData, 'college_id', 'college_name');
    }
    
} 
```
But when I call this function in another controller at time call  PHP Fatal Error – yii\base\ErrorException(Call to undefined method yii\web\View::getDb()).

Please so my screenshot.

![screenshot-localhost 2015-12-15 10-06-20](https://cloud.githubusercontent.com/assets/8121721/11802167/86e3adcc-a313-11e5-8efd-aa6bcb11ea7e.png)

**Comment by AnatolyRugalev** [comment]
Can you show your call code? Looks like you calling statically non-static method. Try to add `static` keyword:
```php
 public static function getCollegeList()
```

**Comment by hirenbhut93** [comment]
Yes, I know if use  static is working. 
But I have used same not static function in Yii 2.0.4 is working.
In Yii 2.0.6 is not working Why?

**Comment by cebe** [comment]
@hirenbhut93 please show the code that is calling the function.

**Comment by hirenbhut93** [comment]
Sorry, My mistake.

**Comment by cristal2431** [comment]
May I know what was the issue @hirenbhut93

**Comment by klysiak** [comment]
I have the exactly same problem. On my dev server where I use PHP7.3 it works perfectly. Copied to prod server (PHP 5.6 - no option to upgrade at the moment) it throws the above error. 

Yii 2.0.30

![Zrzut ekranu 2019-12-30 o 15 42 47](https://user-images.githubusercontent.com/7317373/71586602-1a164580-2b1b-11ea-9e18-29e664b7b341.png)
