### ISSUE TITLE
Bug in \yii2\web\Request - Uninitialized string offset: 0

### ISSUE THREAD

**Issue by adam2314** [yiisoft/yii2#10386]
while using baseurl and not providing trailing '/'
you will receive the error.
possible solution:
`if ($pathInfo[0] === '/') {`
to
`if (isset($pathInfo[0])&&$pathInfo[0] === '/') {`

**Comment by Alex-Code** [comment]
Which version are you using?
Looks like this has already been fixed, https://github.com/yiisoft/yii2/commit/dd818e17dfa047b529fe6fbd88a2c52ab747ead5

**Comment by adam2314** [comment]
im using 2.06 i saw this bug it dosen't fix that cause you still get to $pathInfo[0] will it isn't set

**Comment by Alex-Code** [comment]
Just noticed, The fix is in 2.0.7

**Comment by adam2314** [comment]
@samdark dd818e17dfa047b529fe6fbd88a2c52ab747ead5 
does not solve this issue.

**Comment by Alex-Code** [comment]
`substr` will return `false` if the string is empty.

**Comment by adam2314** [comment]
what’s throwing the Uninitialized string offset: 0
is the line:
`if ($pathInfo[0] === '/') { `
and not the line after

**Comment by Alex-Code** [comment]
`if ($pathInfo[0] === '/') {` has been removed in 2.0.7 in favor of `substr`

**Comment by adam2314** [comment]
oh crap you're absolutely right.
i'm terribly sorry i misread the all thing.
