### ISSUE TITLE
BUG - Postgresql INHERITS

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#10389]
The schema [reader](https://github.com/yiisoft/yii2/blob/master/framework/db/pgsql/Schema.php#L338) disregard the pk of an inherited table.

e.g.
```sql
CREATE TABLE example (
  id   SERIAL PRIMARY KEY,
  name VARCHAR(20)
);

CREATE TABLE bug () INHERITS (example); 
```

The schema of the table bug will not consider the `id` as a valid primary key.

**Comment by samdark** [comment]
Do you an idea on how to fix that?

**Comment by nineinchnick** [comment]
PostgreSQL itself does not inherit PK constraints:

 http://www.postgresql.org/docs/9.1/static/ddl-inherit.html

taken from http://www.postgresql.org/docs/9.1/static/ddl-inherit.html

Maybe the problem is that it doesn't actually read columns from the parent table?

**Comment by llfm** [comment]
Oh, you're right (the truth sucks).

> All check constraints and not-null constraints on a parent table are automatically inherited by its children. Other types of constraints (unique, primary key, and foreign key constraints) are not inherited.

Thanks!
