### ISSUE TITLE
bug in captcha

### ISSUE THREAD

**Issue by mahsa92** [yiisoft/yii2#10385]
Hi
I'm using captcha in my project and it works , but there is problem in a specific scenario.
if user enters a wrong text for captcha then refresh it (by clicking on it) to generate another captcha , after this captcha always throw exception
For solving this problem i had to disable clientValidation
Is there any other solution?

**Comment by samdark** [comment]
Which exception is that?

**Comment by mahsa92** [comment]
sorry I didn't say my sentence in a right way . I mean it doesn't validate captcha code and always shows error message 'The verification code is incorrect.'

**Comment by SilverFire** [comment]
Failed to reproduce on Yii2 basic application.
Could you bring us more details to make your problem possible to reproduce?
First, try to reproduce it on the clear application instance

**Comment by mahsa92** [comment]
you can test it in http://en.msrt.ir/en/contactus form

**Comment by SilverFire** [comment]
It works fine: ![Screenshot](http://savepic.ru/8094331.png)

**Comment by mahsa92** [comment]
i told it works fine. but in a specific scenario it doesn't work
please follow this instruction:
1.enter a wrong captcha
2.now click on image and it would generate another captcha
now if you enter the right captcha code it always shows errors until you refresh page completely

**Comment by SilverFire** [comment]
I've reproduced the bug on your site, but still failed to do the same with the clean Yii2 installation

**Comment by mahsa92** [comment]
I added these codes to controller

      public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                // 'fixedVerifyCode' => YII_ENV_DEV ? 'test' : null,
            ],
        ];
    }
I added these codes to my model

      ['verifyCode', 'captcha', 'captchaAction'=>'/user/auth/captcha']

I added these codes to my form

            <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
            'captchaAction' => 'auth/captcha',
            'template' => '<div class="row"><div class="col-lg-6">{image}</div><div class="col-lg-6">{input}</div></div>',
            'options'=>['style' => 'direction:ltr', 'class' => 'form-control']
        ]) ?>

I just did this.Is something wrong with it?

**Comment by SilverFire** [comment]
Thank you for the report. The problem was in the beginning `/` in `captchaAction` validation config
