### ISSUE TITLE
i18n default settings & errors

### ISSUE THREAD

**Issue by PELock** [yiisoft/yii2#10397]
Hi,

I found a bug related to i18n settings. I set my language in controllers init() function depending on the URL (site.com/en -> english, site.com/ru -> russian). Default language is set to 'en' (not en-US) in config file.

`			\Yii::$app->language = 'en';
			\Yii::$app->sourceLanguage = 'en';`

Now I run my site with the debug toolbar and it says there's an error when 'en' is used (source language):

`error	yii\i18n\PhpMessageSource::loadMessages	The message file for category 'yii' does not exist: /home/bartek/www/public_html/site.com/vendor/yiisoft/yii2/messages/en/yii.php

The bug is inside I18n.php file:

```php
    /**
     * Initializes the component by configuring the default message categories.
     */
    public function init()
    {
        parent::init();
        if (!isset($this->translations['yii']) && !isset($this->translations['yii*'])) {
            $this->translations['yii'] = [
                'class' => 'yii\i18n\PhpMessageSource',
                'sourceLanguage' => 'en-US', <-- BUG BUG BUG
                'basePath' => '@yii/messages',
            ];
        }
        if (!isset($this->translations['app']) && !isset($this->translations['app*'])) {
            $this->translations['app'] = [
                'class' => 'yii\i18n\PhpMessageSource',
                'sourceLanguage' => Yii::$app->sourceLanguage,
                'basePath' => '@app/messages',
            ];
        }
    }
```

It assumes the source language is always 'en-US', instead it should be set according to the application setting, and it should be set the same way translations are set for app* section:

`                'sourceLanguage' => Yii::$app->sourceLanguage,`

**Comment by kidol** [comment]
Duplicate #7964
