### ISSUE TITLE
Problem on UrlManager

### ISSUE THREAD

**Issue by alemedinam** [yiisoft/yii2#10398]
I'm using the next UrlManager 
```php
'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false, 
            'showScriptName' => false,
            'rules' => [
                'module/<module:\w+>/<controller:\w+>/<action:\w+>' => '<module>/<controller>/<action>',                
                'debug/<controller>/<action>' => 'debug/<controller>/<action>',
            ]
        ],
```
and a .htaccess file like:
```php
RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule . index.php
```
for hiding index.php on the url. It works good but in some modules I get this:

http://localhost/prueba/frontend/web/module/Configuracion/configuracion/update?grupo=E+&codigoTipoGrupo=T

What I want to avoid is show this part "/module/ " of the url. It sometimes appears and I don't know if it is a bug or I'm doing something wrong.

Doing this:

```php
<?= Html::a('<i class="fa fa-edit"></i>'.$text, ['configuracion/update', 'grupo' => $model->Grupo, 'codigoTipoGrupo' => $model->CodigoTipoGrupo], ['class'=>'btn btn-block '.$buttonColor.' btn-xs']) ?>
```

Or this 
```php
<a href="<?=Url::toRoute('calificaciones/index')?>">
```

I'm getting the same result

**Comment by SilverFire** [comment]
You have hardcoded `module` in your first URL rule. Change first rule to

```php
'<module:\w+>/<controller:\w+>/<action:\w+>' => '<module>/<controller>/<action>',
```

Please notice that this is not a support forum. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

**Comment by alemedinam** [comment]
@SilverFire thank you too much :) 
I'll keep in mind
