### ISSUE TITLE
DI Container vs Debug Tool

### ISSUE THREAD

**Issue by Alez** [yiisoft/yii2#10391]
Recently i've discovered that i can use DI in controller method like so
```php
public function actionIndex($age = null, ActiveDataProvider $dataProvider)
```
and it will create instance with all the configurations.
But some time after that i noticed that my debug panel is not working and it says
```
Not Found (#404): Unable to find debug data tagged with '566ee7f9bc09b'.
```
In log file i found
```
2015-12-14 18:44:02 [127.0.0.1][-][-][warning][yii\log\Dispatcher::dispatch] Unable to send log via yii\debug\LogTarget: Exception 'Exception' with message 'Serialization of 'Closure' is not allowed' 

in D:\OpenServer\domains\tikitoki-yii\vendor\yiisoft\yii2-debug\LogTarget.php:57

Stack trace:
#0 D:\OpenServer\domains\tikitoki-yii\vendor\yiisoft\yii2-debug\LogTarget.php(57): serialize(Array)
#1 D:\OpenServer\domains\tikitoki-yii\vendor\yiisoft\yii2-debug\LogTarget.php(118): yii\debug\LogTarget->export()
#2 D:\OpenServer\domains\tikitoki-yii\vendor\yiisoft\yii2\log\Dispatcher.php(183): yii\debug\LogTarget->collect(Array, true)
#3 D:\OpenServer\domains\tikitoki-yii\vendor\yiisoft\yii2\log\Logger.php(173): yii\log\Dispatcher->dispatch(Array, true)
#4 [internal function]: yii\log\Logger->flush(true)
#5 {main}
```
So i replaced type hint DI way with normal DI Container
```php
$dataProvider = Yii::$container->get('yii\data\ActiveDataProvider');
```
Now it works.

Is it bug?

**Comment by samdark** [comment]
It's an issue in debugger. Have you tried `master` branch?

**Comment by kirsenn** [comment]
I can't get it working like this:
it throws `BadRequestHttpException 'Missing required parameters: gateTickets'...` when I do `public function actionIndex(PortalGateTickets $gateTickets)`

**Comment by Alez** [comment]
I have save bug with latest available version ```8c8631000303876fb2e07cf8043d2c49973fc994```

**Comment by samdark** [comment]
Can't reproduce. What I've done:

1. Took basic app template.
2. Replaced `actionIndex` line in `SiteController` with `public function actionIndex($age = null, ActiveDataProvider $dataProvider)`.
3. Added `use yii\data\ActiveDataProvider;` to the top of the file.
4. Tried it in a browser.

Both page and debug panel are OK.

**Comment by Alez** [comment]
So, did a research and find out that closures in behaviors causes that kind of problem.
Furthermore, if any related models has closures in behaviors they cause that issue too.
```php
    public function behaviors()
    {
        return [
            [
                'class' => AttributeBehavior::className(),
                'attributes' => [
                    ..........
                ],
                'value' => function () {
                    ..........
                },
            ],
        ];
    }
```
So then debugger tool starts to work, it logs controller's $actionParams, and tries to serialize them
```php
    /**
     * Exports log messages to a specific destination.
     * Child classes must implement this method.
     */
    public function export()
    {
        $path = $this->module->dataPath;
        FileHelper::createDirectory($path, $this->module->dirMode);

        $summary = $this->collectSummary();
        $dataFile = "$path/{$this->tag}.data";
        $data = [];
        foreach ($this->module->panels as $id => $panel) {
            $data[$id] = $panel->save();
        }
        $data['summary'] = $summary;
        file_put_contents($dataFile, serialize($data));  // <--- here
        if ($this->module->fileMode !== null) {
            @chmod($dataFile, $this->module->fileMode);
        }

        $indexFile = "$path/index.data";
        $this->updateIndexFile($indexFile, $summary);
    }
```
First parameter is null, so it is ok, but second parameter is a ActiveDataProvider with pack of models with closures it behaviors.
I guess it is a well known problem.

**Comment by samdark** [comment]
Yes, it is.
