### ISSUE TITLE
[2.0.6 - SluggableBehavior] - Error generate slug with Unicode characters (Vietnamese)

### ISSUE THREAD

**Issue by sieulog** [yiisoft/yii2#10394]
When I generate string example: 

Input: Đi chơi ở đâu bây giờ nhỉ
Result: i-choi-o-au-bay-gio-nhi

Currently, Result missing Đ, đ character. Please, help me!

**Comment by SilverFire** [comment]
I guess is is fixed in 2.0.7 https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseInflector.php#L280
Could you check, please?

**Comment by sieulog** [comment]
@SilverFire Ok, thank you! I will check it.

**Comment by zinzinday** [comment]
Pull #5164 

add to bootstrap 

\Yii::$container->set('yii\helpers\Inflector', [
    'transliterator' => 'Any-Latin; Latin-ASCII; Lower()'
]); 

To usage for full unicode

**Comment by SilverFire** [comment]
@sieulog I've just check the latest dev-version. Since 2.0.7 you input will be slugged to `di-choi-o-dau-bay-gio-nhi`

**Comment by sheillendra** [comment]
error also if the word contains a dot (.)
