### ISSUE TITLE
Disable tag options in radiolist

### ISSUE THREAD

**Issue by faravaghi** [yiisoft/yii2#10390]
Hi,
how can i do disable tag option in radiolist?
[radiolist](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L987)
in my form i have status field and i want show this with toggle bottun and my code is:
```php
echo $form->field($model, 'status',
		['template'=>'{label}<div class="col-md-6 col-xs-9"><div class="btn-group" data-toggle="buttons">{input}</div> {hint} {error}</div>']
	)
	->radioList(
		[1=>'active', 0=>'deactive'],
		[
			'item' => function($index, $label, $name, $checked, $value) {
				return '<label class="btn btn-white btn-info btn-round">' . Html::radio($name, $checked, ['value'  => $value, 'autocomplete'=>'off']) . $label . '</label>';
			}
		]
	)
	->label(NULL, ['class'=>$labelClass]);
```
but in html show this:
```html
<div data-toggle="buttons" class="btn-group">
	<input type="hidden" value="" name="model[status]">
	<div id="model-status">
		<label class="btn btn-white btn-info btn-round">
			<input type="radio" autocomplete="off" value="1" name="model[status]">active
		</label>
		<label class="btn btn-white btn-info btn-round">
			<input type="radio" autocomplete="off" value="0" name="model[status]">deactive
		</label>
	</div>
</div>
```
how can fix it and don't show ```<div id="model-status"> ```?

**Comment by AnatolyRugalev** [comment]
Currently tag disabling is not supported, you can only change it's name and options:
```php
$tag = isset($options['tag']) ? $options['tag'] : 'div';
unset($options['tag'], $options['unselect'], $options['encode'], $options['separator'], $options['item'], $options['itemOptions']);
return $hidden . static::tag($tag, implode($separator, $lines), $options);
```
Try:
```php
echo $form->field($model, 'status',
        ['template'=>'{label}<div class="col-md-6 col-xs-9">{input}{hint} {error}</div>']
    )
    ->radioList(
        [1=>'active', 0=>'deactive'],
        [
            'item' => function($index, $label, $name, $checked, $value) {
                return '<label class="btn btn-white btn-info btn-round">' . Html::radio($name, $checked, ['value'  => $value, 'autocomplete'=>'off']) . $label . '</label>';
            }
        ],
        [
            'tag' => 'div', // this is by default
            'class' => 'btn-group',
            'data-toggle' => 'buttons',
        ]
    )
    ->label(NULL, ['class'=>$labelClass]);
```

**Comment by faravaghi** [comment]
What is the need of the div tag? Why can not it be eliminated?

**Comment by SilverFire** [comment]
We can make it disabled when `$options['tag']` is false

**Comment by faravaghi** [comment]
not work this and show ```< id="model-status">``` without tag name!!!

**Comment by SilverFire** [comment]
Of course it does not work :) I said that we can implement such behavior and tagged the issue as `ready for adoption`

**Comment by AnatolyRugalev** [comment]
@SilverFire, agree. May be it should be implemented for any similar behavior such as in `checkbox`? Or even to do this inside of `Html::tag()`?

By the way, `< id="model-status">` is not a valid HTML, we should handle it somehow

**Comment by SilverFire** [comment]
Dou you mean `checkboxList`? Then yes.

No, I don't think that it should be put in `Html::tag()`

**Comment by faravaghi** [comment]
In fact, I want have a [bootstrap radio buttons list](http://getbootstrap.com/javascript/#buttons-checkbox-radio). but when insert a tag into html, Format interrupted...

**Comment by SilverFire** [comment]
Related to https://github.com/yiisoft/yii2-bootstrap/issues/45

**Comment by faravaghi** [comment]
How write it?

**Comment by SilverFire** [comment]
@faravaghi your problem is not solved yet

**Comment by SilverFire** [comment]
@faravaghi it's solved now: https://github.com/yiisoft/yii2/commit/85c6a903dced72cce0ce95f8fd424fd492ceb4e6
