### ISSUE TITLE
Get All The Active User Id List

### ISSUE THREAD

**Issue by MrAwanishKumar** [yiisoft/yii2#10404]
Hi,

There is a requirement to show the all logged in user name to admin. For example - 
Suppose we have 100 users and at a time 50 users are logged in, so how can I get the list of these 50 users.

I tried searching on github and yii2 documentation, but did not find. Please share link if exists. 

Thanks

**Comment by SilverFire** [comment]
An option will be to use custom DbSession with additional `user_id` field. Than it's easy to count active users with SQL query and condition like `user_id IS NOT NULL and expire - $maxLifetime > NOW() - '30 minutes'` (pseudocode)

Please notice that this Yii2 is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

**Comment by samdark** [comment]
See

**Comment by samdark** [comment]
Linked issue is a cookbook draft.
