### ISSUE TITLE
Error when installing fxp/composer-asset-plugin:~1.1.1

### ISSUE THREAD

**Issue by Calcio** [yiisoft/yii2#10406]
Failed to download fxp/composer-asset-plugin from dist: The "https://api.github.com/repos/francoispluchino/composer-asset-plugin/zipball/daca454b94539a4e6d30937dfc6b817eceb03f28" file could not be downloaded: failed to open stream: Connection timed out
    Now trying to download from source

**Comment by SilverFire** [comment]
Does not relate Yii.
It seems you have connection problems
