### ISSUE TITLE
endPage sends content

### ISSUE THREAD

**Issue by rodion-k** [yiisoft/yii2#10403]
in the following method in yii\web\View class
```php
    public function endPage($ajaxMode = false)
    {
        $this->trigger(self::EVENT_END_PAGE);
        $content = ob_get_clean();
        echo strtr($content, [
            self::PH_HEAD => $this->renderHeadHtml(),
            self::PH_BODY_BEGIN => $this->renderBodyBeginHtml(),
            self::PH_BODY_END => $this->renderBodyEndHtml($ajaxMode),
        ]);
        $this->clear();
    }
```
function ob_get_clean() turn off output buffering and then content is sent. Is this a right behaviour to send content before $request->send()?

**Comment by samdark** [comment]
It cleans up view buffer. There's another one wrapping it.

**Comment by rodion-k** [comment]
ob_get_clean() not only clean up but it turn off buffering. From php manual: 
ob_get_clean() essentially executes both ob_get_contents() and ob_end_clean()
http://php.net/manual/en/function.ob-get-clean.php

**Comment by samdark** [comment]
https://3v4l.org/Z3HUb

**Comment by rodion-k** [comment]
Ok, in my case content and headers are really sends after endPage call and all HttpExceptions have incorrect http status because 
```php
$response->setStatusCode($exception->statusCode);
```
called after 
```php
Yii::$app->runAction($this->errorAction)
```
in yii\web\ErrorHandler::renderException

**Comment by samdark** [comment]
OK. That's another issue. How to reproduce that?

**Comment by rodion-k** [comment]
put $this->endPage() to view or layout which rendered on error and go to page that doesn't exists. HTTP status must be 404 but it 500

**Comment by samdark** [comment]
Both `beginPage()` and `endPage()` are for layouts only. These should not be used in error views.

**Comment by rodion-k** [comment]
I use layout which contains ``` endPage() ``` for error view

**Comment by samdark** [comment]
How exactly?

**Comment by rodion-k** [comment]
frontend\controllers\SiteController.php:
```php
class SiteController extends Controller
{
    public $layout = 'base';
    ...
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
}
```
views\layouts\base.php
```html
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <?= Html::csrfMetaTags() ?>

    <title><?= $this->title ?></title>

    <?php $this->head() ?>
</head>

<body>
<?php $this->beginBody() ?>
    
<?= $content ?>
    
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>
```
views/site/error.php
```html
<div class="site-error">
    <h1><?= Html::encode($exception->getMessage()) ?></h1>
</div>
```

**Comment by rodion-k** [comment]
I forgot write ``` beginPage() ```. Sorry and thanks for help
