### ISSUE TITLE
Field Name Quotes missing with PgSQL with select()

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#10402]
Here is the code:

````php
$this->query = Entity::find();
$default = ['{{*maintable}}.*'];
$this->related = ['{{%table}}.nEntityID', '{{%table}}.sEntityName']
$this->query->select(ArrayHelper::merge($default, $this->related));
$data = $this->query->asArray()->all();
````

This will work perfectly with MySQL or may be other DB but not with PgSQL. This is because PgSQL will convert field and tables to lower case if those are not quoted. 

The query which is being executed by above code is not quoting the field name. It is quoting table name which are `{{%table}}` but not to the field added after it which is `{{%table}}.nEntityID`

Is there anything I am missing or Yii should Quote those field names?

**Comment by avinashz** [comment]
Also if `$this->related = ['{{%table}}.nEntityID', '{{%table}}.sEntityName']` is used as `$this->related = ['nEntityID', 'sEntityName']`,

i.e.: without table name then it is quoting fields properly

**Comment by nineinchnick** [comment]
To quote column names you should use `{{%table}}.[[sEntityName]]`.
