### ISSUE TITLE
Cannot getId in login IdentityInterface with SQL Server 2008 R2

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#10400]
I don't know my auth failed in SQL Server 2008 R2, not throw any error or anything 
After debugging i see in [User Component](https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L237) not getting id (NULL)

I produce with standard script from advanced template, id in database I added in last field (*my hipotesis if id in last or not first field*) because previously existing primary key in the front (this database has been used, so I can not change the overall) only use the characters, so I made a new field (id)

```php
    public static function tableName(){
        return 'User';
    }
	
	public static function primaryKey(){
		return 'id';
	}
```

**Comment by o-rey** [comment]
Seems like you haven't flushed schema cache. Try ```./yii cache/flush-schema```

**Comment by klimov-paul** [comment]
Closed, since there is no response from the author.
