### ISSUE TITLE
accept date validation with month grater then 12

### ISSUE THREAD

**Issue by Kerych74** [yiisoft/yii2#10407]
and then put record 0000-00-00 to the database
![screenshot 2015-12-16 18 08 22](https://cloud.githubusercontent.com/assets/14916179/11848018/8911eaec-a420-11e5-92a4-765b6910b770.png)
![screenshot 2015-12-16 18 11 30](https://cloud.githubusercontent.com/assets/14916179/11848017/890cddc2-a420-11e5-99dd-531c7d53c7ba.png)

**Comment by SilverFire** [comment]
Could you show you validation rule, please?

**Comment by Kerych74** [comment]
['userBirthDate', 'date', 'format' => 'YYYY-mm-dd', 'max' => '2012-12-31', 'min' => '1920-01-01'],
            ['userBirthDate', 'required'],

**Comment by samdark** [comment]
Well, your format is wrong. `Y` stands for `year of "Week of Year"`, `m` stands for `minute in hour`: http://www.yiiframework.com/doc-2.0/yii-validators-datevalidator.html#$format-detail

**Comment by Kerych74** [comment]
Thanks
