### ISSUE TITLE
При создании CRUD получается Controllers а не сontrollers

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#10411]
![screenshot_40](https://cloud.githubusercontent.com/assets/10970793/11860319/830e8de2-a495-11e5-8a85-ce063a12c5a7.png)

получаю namespace app\modules\lesson\Controllers ;

вот новое приложение, ничего не менял. приходится руками в нижний регистр переводить

**Comment by SilverFire** [comment]
Вы же сами написали в `Controller Class` namespace с Controllers в верхнем регистре
