### ISSUE TITLE
About restful relation data return limit

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2#10410]
```php
class Album {
    ......
    public function getPhotos($limit) {
        return (new query())->from('photos')->limit($limit)->all()
    }
}
```
How to transmit 'limit' param in url?
http://api.example.com/albums/123

**Comment by Lynnworld** [comment]
you may add limit in query url like  http://api.example.com/albums/123?limit=10

**Comment by hiscaler** [comment]
If i will get 10 albums and 5 photos per album. I use http://api.example.com/albums?limit=10&photoLimit=5?
Is not pretty.

**Comment by SilverFire** [comment]
Construct custom URL rule like:

```php
    'urlManager' => [
        'enablePrettyUrl' => true,
        'showScriptName' => false,
        'rules' => [
            [
                'pattern' => 'album/<id:\d+>/<photoLimit:\d+>',
                'route' => 'site/album'',
                'defaults' => [
                    'photoLimit' => 5
                ]
            ]
        ]
    ],
```

**Comment by fernandezekiel** [comment]
currently you can only limit the model used by the ActiveDataProvider,
first of all i would suggest that you do this in the controller level, basically altering what the `prepareDataProvider` and `findModel` params of the index action and the view action does.
```php
....
$query->with(['photos' => function ($q) {$q->limit(Yii::$app->request->getQueryParam('photoLimit'))} ])
...
```
however if i had a choice i would do it like facebook graph API:
```
GET /albums?expand=photos[limit=5]
```

**Comment by hiscaler** [comment]
@SilverFire Tks
@fernandezekiel Tks, Like facebook graph API 
```php
GET /albums?expand=photos[limit=5]
```
is good O(∩_∩)O

**Comment by hiscaler** [comment]
@cebe Can support it
```php
GET /albums?expand=photos[limit=5]
```

**Comment by cebe** [comment]
`?expand=photos[limit=5]` would result in `$_GET['expand']` to be =`"photos[limit=5]"` which you can parse to get what you want.
