### ISSUE TITLE
ошибка с bower

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#10413]
решил с нуля установить Yii 2 через composer

http://www.yiiframework.com/doc-2.0/guide-start-installation.html

    composer create-project --prefer-dist yiisoft/yii2-app-basic yii2lesson

получаю

    The file or directory to be published does not exist: F:\OpenServer\domains\yii2lesson\vendor\bower/jquery/dist

ладно верю
![1ghbi](https://cloud.githubusercontent.com/assets/10970793/11861863/53a62dec-a4a6-11e5-89bb-965bb90d43b3.png)

bower поставился в папку bower-asset

кроме как ручками перенести нет более изящного метода?

http://ru.stackoverflow.com/questions/475421/yii-2-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-%D1%81-bower

**Comment by cebe** [comment]
this somethimes happens if you use an old version of composer. Please update your composer and make sure you use the latest version of the asset plugin also:

```
composer self-update
composer global require "fxp/composer-asset-plugin:~1.1.1"
```

**Comment by des1roer** [comment]
if I am not mistaken, fxp/composer-asset-plugin:~1.1.1  is out of date

**Comment by des1roer** [comment]
I did composer self-update

**Comment by des1roer** [comment]
I'm sorry, I had a version 1.0.3
