### ISSUE TITLE
Date validator - $timestampAttribute should accept an array

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#10417]
To use the ``$timestampAttribute`` in date validator you need one rule for each attribute. Accepting an array would allow to validate many attributes within one rule.

Example:
```php
// current solution
 ['startDate', 'date', 'timestampAttribute' => 'dbStartDate', 'timestampAttributeFormat' => 'yyyy-MM-dd'],
 ['endDate', 'date', 'timestampAttribute' => 'dbEndDate', 'timestampAttributeFormat' => 'yyyy-MM-dd'],
```

```php
// possible solution
 [['startDate', 'endDate'], 'date', 'timestampAttribute' => ['dbStartDate',  'dbEndDate'], 'timestampAttributeFormat' => 'yyyy-MM-dd'],
```

**Comment by cebe** [comment]
This is not possible, `['startDate', 'endDate']` is a shorthand which in fact creates two validators with the same configuration. From that point it is unclear what `'timestampAttribute' => ['dbStartDate',  'dbEndDate']` is supposed to be.

**Comment by twinni** [comment]
@cebe, as long as the size of the proposed ``timestampAttribute`` array equals the size of the ``$attributes`` property the relationship between them should be clear.

The proposed enhancement would make validation much simpler for models having lot's of date attributes.

**Comment by SilverFire** [comment]
@twinni implementing this feature in the core is impossible without adding some special crutch. We won't do it.

**Comment by cebe** [comment]
@twinni there is no ``$attributes`` property.

**Comment by twinni** [comment]
@cebe, the ``$attributes`` property is meant to be the string | array of attributes to be validated by this validator. So the validator already iterates over the $attributes property. 

I felt that it might not too difficult to assign an array element form ``timestampattribute`` the the ``$attributes``. But I accept saying that's impossible.

So what do you think about a solution based on naming convention for the ``timestampattribute``? We could use constants like "self" or "prefix:any" to specify the target attribute. "self" could mean overwrite the current attribute while "prefix:" could be the name of currently checked attribute prefxid with the the prefix value (startDate -> anystartDate )?

**Comment by twinni** [comment]
I just got an other idea. We could also use the ``$attributes`` array to name the attribute where the filtered value should be stored. Then this would fit for all filter validators.
['fromDate' => 'dbFromDate', 'toDate' => 'dbToDate', ...]

**Comment by SilverFire** [comment]
I'm standing against suggested idea because the use case is quite specific and all of proposed ways make interface unclear.

**Comment by cebe** [comment]
agree with @SilverFire, this introduces more complexity than it helps.
