### ISSUE TITLE
isGuest() check in controller's action with HttpBearerAuth

### ISSUE THREAD

**Issue by valeriblack** [yiisoft/yii2#10418]
Hello!
I'm trying to make one of my actions allowed to both guests and registered users with checking isGuest() inside this action to provide user specific info if user authorised.
But if I use HttpBearerAuth inside behaviours I always get error "You are requesting with an invalid credential." and as you can see I'm unable to use 'except' inside authenticator.
The code looks like this:
```
public function behaviors()
	{
	    $behaviors = parent::behaviors();
	    $behaviors['authenticator'] = [
	        'class' => HttpBearerAuth::className()
	    ];
	    //Access is not used at all by Yii in this situation...
	    $behaviors['access'] = [
		    'class' => AccessControl::className(),
		    'rules' => [
		        [
		            'allow' => true,
		            'roles' => ['?', '@']
		        ],
		    ],
		];
	    
	    return $behaviors;
	}
```

The same topic from another user at yiiframework forum:
http://www.yiiframework.com/forum/index.php/topic/67962-api-authenticator-blocking-guest-users/

**Comment by cebe** [comment]
You should only add the `HttpBearerAuth` behavior if the user is a guest. If he is already authenticated you do not require additional auth via HttpBearer so you must skip adding the behavior.
You must remove the `'?'` from AccessControl then.

**Comment by valeriblack** [comment]
I want both guests and authenticated users to have access to the same action.
If I do not authorize user with bearer access token on every page I can't use isGuest(), because it returns true even with authenticated users.

**Comment by SilverFire** [comment]
Check out #7405
