### ISSUE TITLE
Hint block in \yii\bootstrap\ActiveField

### ISSUE THREAD

**Issue by hugodiniz** [yiisoft/yii2#10420]
Different from \yii\widgets\ActiveField, in the bootstrap version of this object is used tag "p" and class "help-block" for the hint blocks. I suggest to use the default class "hint-block". Why not use tag "div" ?

**Comment by mikehaertl** [comment]
The class follows the suggestion in the bootstrap manual: http://getbootstrap.com/css/#forms-help-text

The only difference is, that we use a `p` instead of a `span`. Not sury why that is, but it doesn't seem to hurt.

**Comment by hugodiniz** [comment]
Thank you, @mikehaertl. But with this class name, when there is a validation error in the input, the hint is getting red like the error.

**Comment by mikehaertl** [comment]
@hugodiniz Yes, that's right. But unfortunately that's what Bootstrap suggests. They don't make a difference between a hint and an error message. So not sure how to fix this. This is rather an issue with bootstrap itself.

**Comment by hugodiniz** [comment]
Thank you again, @mikehaertl . I'm using a customized ActiveField extending bootstrap\ActiveField, where a class "hint-block" is used, as is the widgets\ActiveField. I use a hint popover inspired in gii.
