### ISSUE TITLE
ColumnSchemaBuilder - Not null column

### ISSUE THREAD

**Issue by nevermnd** [yiisoft/yii2#10422]
With the new migration syntax, in MSSQL all columns are created as NOT NULL whether they have been defined so or not. I think the implementation of the class ColumnSchemaBuilder for MSSQL should add a explicit NULL for nullable columns.

Ex:
```php
protected function buildNotNullString()
{
    return $this->isNotNull ? ' NOT NULL' : ' NULL ';
}
```

**Comment by samdark** [comment]
How's that? I've just tried MSSQL 2015:

```sql
create table A (
	id int
);
```

Creates null-able column as expected.

**Comment by nevermnd** [comment]
In MSSQL 2008

```sql
create table B (
   name varchar(10)
);
```
name is created as NOT NULL by default

**Comment by nevermnd** [comment]
Apparently there are two scenarios in which the columns are created as not null by default:
* When SET ANSI_NULL_DFLT_ON is Set On
* When ANSI_NULL_DEFAULT setting of the database is Set to OFF and BOTH SET and SET ANSI_NULL_DFLT_ON ANSI_NULL_DFLT_ON are Set to OFF

http://sqlstudies.com/2014/03/31/default-nullability-of-a-new-column/

**Comment by samdark** [comment]
I see. Yes, I agree that it should be adjusted. Need to check how all supported DBs behave with `NULL`.

**Comment by samdark** [comment]
MySQL is OK with it.

**Comment by samdark** [comment]
PostgreSQL is OK.

**Comment by nevermnd** [comment]
Oracle, SQLite and Cubrid are ok with it too.

**Comment by samdark** [comment]
Merged https://github.com/yiisoft/yii2/commit/2498a9b3bb8b1b535b0dfc451218217a63610eb7. Thank you!

**Comment by samdark** [comment]
Revered proposed fix because of tests break. It doesn't behave well with primary keys.

**Comment by nevermnd** [comment]
Since we can't change `notNull` behavior, i think adding a method `null` or `nullable` to 
explicitly set the column nullability is the best solution.
