### ISSUE TITLE
ActiveRecord link can't work with 2 relation

### ISSUE THREAD

**Issue by wilianto** [yiisoft/yii2#10426]
I have table like this

<b>Product</b>
id | name

<b>Spec</b>
id | feature 

<b>ProductSpec</b>
product_id | spec_id | value

product_id has one relation to Product id
spec_id has one relation to Spec id

This is my code

    $product = new Product(['name' => 'Product 1']);
    $spec = new Spec(['feature' => 'Feature 1']);
    if($product->save() && $spec->save()){
        $product_spec = new ProductSpec();
        $product_spec->link('product', $product);
        $product_spec->link('spec', $spec);
        $product_spec->save();
    }

But when I ran the code, I got this error:

Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails
CONSTRAINT `FK_ps_spec` FOREIGN KEY (`spec_id`) REFERENCES `spec` (`id`) ON DELETE CASCADE ON UPDATE CASCADE

This was the generated query `INSERT INTO product_spec (product_id) VALUES (1)`

Is this a bug?

**Comment by SilverFire** [comment]
Could you show `var_dump($spec)` before link and relation definition in your model

**Comment by cebe** [comment]
as far as I see, the issue here is that the junction table model has to be saved with both Ids set. 
Which relations have you defined inside of the models?

**Comment by cebe** [comment]
If you define a relation between Spec and Product using viaTable() or via() you can use one relation for link(). You may use the third parameter of link() to set columns like "value". http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#link%28%29-detail
