### ISSUE TITLE
fileCache has a bug

### ISSUE THREAD

**Issue by advance100** [yiisoft/yii2#10423]
when **$directoryLevel =0,**
[warning][yii\caching\FileCache::setValue] Unable to write cache file 'D:\wamp\www\bucaoxin\admin\runtime/cache/_field\settings.bin': file_put_contents(D:\wamp\www\bucaoxin\admin\runtime/cache/_field\settings.bin): failed to open stream: No such file or directory

 ~~~
public static function getSettings(){
		$cache = \Yii::$app->getCache();
		$cache->cachePath = \Yii::getAlias('@runtime/cache/_field');
		$cache->directoryLevel = 0;
		$setting = $cache->get('settings');
		if($setting===false){
			$setting = [];
			$data = SqlModel::getAllBySql('setting');
			$data = ArrayHelper::map($data,'name','data'); 
			foreach ($data as $k=>$v){
				$setting[$k]=@unserialize($v) ? @unserialize($v) : $v;
			}
			$cache->set('settings',$setting);
		}
		return $setting;
	}
 ~~~
add **FileHelper::createDirectory($cache->cachePath);** 
before $cache->set('settings',$setting);

**Comment by cebe** [comment]
this is already handled in init(): https://github.com/yiisoft/yii2/blob/d9f8933737cf851744b0ea70dee158621c0fef3d/framework/caching/FileCache.php#L78-L81

if you change the cache path afterwards you have to ensure it exists yourself. This is not a good idea anyway, why are you doing this?
