### ISSUE TITLE
Replace mysql params posible bug

### ISSUE THREAD

**Issue by guvi77** [yiisoft/yii2#10432]
Hi,

I have the following situation:
I defined a class for a module that has relation to itself (parent module). Each module has a translation:

```php
class Module extends \yii\db\ActiveRecord {
    public function getCurrentTranslation()
    {
        return $this->hasOne(ModuleTranslate::className(), ['id_mdll' => 'id_mdl'])->onCondition(['lang_mdll' => ':lang'])->from(ModuleTranslate::tableName());
    }    
    public function getParentModule()
    {
        return $this->hasOne(Module::className(), ['idmdl_mdl' => 'id_mdl'])->from(['parentModule' => Module::tableName()]);
    }        
}
class ModuleTranslate extends \yii\db\ActiveRecord {
}
```

I tried to do the call: 

```php
Module::find()->joinWith('currentTranslation', 'parentModule', 'parentModule.currentTranslation')->addParams([':lang' => 'en'])->all()
```

PS: I know that the call will throw an error regarding the missing alias for the translation table which is used twice without alias, but it throwed another error.

When the mysql statment is prepared the :lang param from the query is replaced with :qp1 and :qp2 and I get the error "SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens".

I'm not sure if is a bug, but I expected the sql statment  to be:

```sql
SELECT `module_mdl`.* FROM `module_mdl` LEFT JOIN `module_mdl_lang` ON (`module_mdl`.`id_mdl` = `module_mdl_lang`.`id_mdll`) AND (`lang_mdll`=':lang') LEFT JOIN `module_mdl` `parentModule` ON `module_mdl`.`id_mdl` = `parentModule`.`idmdl_mdl` LEFT JOIN `module_mdl_lang` ON (`parentModule`.`id_mdl` = `module_mdl_lang`.`id_mdll`) AND (`lang_mdll`=':lang')
```

but instead, it is (I displayed in db\Command line 836): 

```sql
SELECT `module_mdl`.* FROM `module_mdl` LEFT JOIN `module_mdl_lang` ON (`module_mdl`.`id_mdl` = `module_mdl_lang`.`id_mdll`) AND (`lang_mdll`=:qp1) LEFT JOIN `module_mdl` `parentModule` ON `module_mdl`.`id_mdl` = `parentModule`.`idmdl_mdl` LEFT JOIN `module_mdl_lang` ON (`parentModule`.`id_mdl` = `module_mdl_lang`.`id_mdll`) AND (`lang_mdll`=:qp2) ) 
```

I expected the param name not be changed so I can replace it globally in the statement, but it was transformed in 2 params: :qp1 and :qp2

**Comment by SilverFire** [comment]
First of all `->onCondition(['lang_mdll' => ':lang'])` is incorrect, because `:lang` is treated as a string, not as a placeholder. You should wrap it with `new Expression(':lang')`.

But I guess you might not need `->addParams([':lang' => 'en'])`, if you update the method as follows:

```php
    public function getCurrentTranslation($lang)
    {
        return $this->hasOne(ModuleTranslate::className(), ['id_mdll' => 'id_mdl'])->onCondition(['lang_mdll' => $lang])->from(ModuleTranslate::tableName());
    }    
```

**Comment by guvi77** [comment]
Hi,

I know it was something like Yii 1.x but I tried that trick because I 
didn't find a solution to call a relation with parameters, something 
like Module::find()->joinWith(['currentTranslate' => ['params' => $lang]]).
I searched all the internet for something like this and I find nothing.

Maybe I don't understand yet the new framework but it's seems to me more 
complicated to get multiple related models into a single query, 
especially when you have a relation to same model (paret / child).

Sorry to bother you.
Thanks.
Ovidiu.

**Comment by SilverFire** [comment]
```php
Module::find()->joinWith(['currentTranslate' => function ($query) {
    $query->andWhere(['lang' => $lang])
}]);
```

Check out our guide: http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#joining-with-relations

**Comment by guvi77** [comment]
It's not working, because the framework does't allow to use params for a 
relation when you use it like Model::find() and not 
$alreadyInstance->relation($params).
It will throw the error: Missing argument 1 for 
models\Module::getCurrentTranslation(), called in 
vendor/yiisoft/yii2/db/BaseActiveRecord.php on line 1121 and defined

The model used:

class Module extends ActiveRecord {

public function getCurrentTranslation($lang)
{
return $this->hasOne(ModuleTranslate::className(), ['id_mdll' => 
'id_mdl'])->onCondition(['lang_mdll' => 
$lang])->from(ModuleTranslate::tableName());
}
public function getParentModule($lang)
{
return $this->hasOne(Module::className(), ['id_mdll' => 
'id_mdl'])->from([Module::tableName() => 'parentModule']);
}
}


class ModuleTranslate extends ActiveRecord {

public function getCurrentTranslation($lang)
{
return $this->hasOne(ModuleTranslate::className(), ['id_mdll' => 
'id_mdl'])->onCondition(['lang_mdll' => 
$lang])->from(ModuleTranslate::tableName());
}

}

call:

Module::find()->joinWith(['currentTranslate' => function ($query) use 
($lang) {
$query->andWhere(['lang_mdll' => $lang])
}]);

If I change the getCurrentTranslation relation to:

public function getCurrentTranslation()
{
return $this->hasOne(ModuleTranslate::className(), ['id_mdll' => 
'id_mdl'])->from(ModuleTranslate::tableName());
}

and make the call:

Module::find()->joinWith(['currentTranslate' => function ($query) use 
($lang) {
$query->andWhere(['lang_mdll' => $lang])
}]); it's working, the final query is: select * from modules left join 
module_translation_mdll on id_mdl = idmdl_mdll  where language_code='en' 
but, it's not what I wanted, because if I do not have a translation the 
module record it will not be in the result

So I used:

Module::find()->joinWith(['currentTranslate' => function ($query) use 
($lang) {
$query->onCondition(['lang_mdll' => $lang])
}]);

with the good result : select * from modules left join 
module_translation_mdll on id_mdl = idmdl_mdll and lang_mdll = 'en'   .

The bad part is I can not reuse the relation call for lazy cases. I have 
to duplicate the relation.


My big problem is that if you'll have 2-3 table to join with a 
translation table it will be a nightmare writing the call without the 
posibility to pass aliases for tables and other parameters. In my small 
example I want to get the modules with parents and the translations for 
each module and each parent. The call will be something like:

Module::find()->joinWith([ 'currentTranslation' => function($query) use 
($lang) { $query->onCondition(['lang_mdll' => $lang]); }, 
'parentModule', 'parentModule.currentTranslation' => function($query) 
use ($lang) { $query->from(['parentModuleTranslation' => 
call_user_func(array($query->modelClass, 'tableName'))]); 
$query->onCondition(['parentModuleTranslation.lang_mdll' => $lang]); }, 
])->all();


Usually the models that are translated inherit a class that extends 
custom class TranslationActiveRecord extends ActiveRecord where the 
currentTranslationMethod that add the relation on a specific logic.

If I have to build some dynamic model related queries depending on the 
user configuration I will be fucked, because the joins must be made 
manually or to make a wrapper that sucks because of the increase of 
complexity.

I really loved the yii1.x flexibility even it had eating a lot of memory 
for activerecord and I would like to continue with yii2, but it seems 
very difficult to work with relations when you want dynamic things to 
generate.

I let you be and don't bother you again. I will try to find alternatives 
or other frameworks.

Merry Christmas!
Ovidiu.
