### ISSUE TITLE
What is issue?

### ISSUE THREAD

**Issue by zinzinday** [yiisoft/yii2#10437]
Model
```
class User extends yii\elasticsearch\ActiveRecord{
    public function attributes(){
        return ['name','role'];
    }
}
```
Action
```
        $user = new User(['name' => 'nghia', 'role' => 2]);
        if ($user->save()) {
            var_dump(User::findOne(['role' => 2]));
        }
```
Result:
`NULL`

**Comment by SilverFire** [comment]
Could you show the requests, that were submitted to ElasticSearch on save and find?

**Comment by zinzinday** [comment]
Model is saved but can not to find this time, refresh browser get result of previous.

**Comment by SilverFire** [comment]
Please, attach the requests, that were submitted to ElasticSearch on save and find

**Comment by cebe** [comment]
elasticsearch has no realtime search. It takes a few milliseconds or up to seconds (depended on your config) to fetch the record. The only thing that works in real time is fetching by primary key. i.e. calling findOne() with pk value only or directly calling `::get($pk)`

**Comment by cebe** [comment]
afair, there is also some direct commit thing that makes it directly available but that is not recommended as it slows down the server a lot.

**Comment by cebe** [comment]
That is the reason why we have the following in the tests: https://github.com/yiisoft/yii2-elasticsearch/blob/master/tests/ActiveRecordTest.php#L63 this flushes the index and makes sure inserted or updated records are available.

**Comment by zinzinday** [comment]
Ohm, thank @cebe . i have know about problem. 
Thanks advanced
