### ISSUE TITLE
ErrorException::isFatalError() returns if error is one of fatal type. E_CORE_WARNING - non-fatal error.

### ISSUE THREAD

**Issue by stovbur** [yiisoft/yii2#10444]
Yii2 framework on my shared-hosting throws an error: "PHP Core Warning – yii\base\ErrorException. Module 'dom' already loaded".
this is E_CORE_WARNING (non-fatal error) http://php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-core-warning
https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorException.php#L79

**Comment by SilverFire** [comment]
This is out of Yii2 scope. Contact your shared hosting support and check out the following SO question: http://stackoverflow.com/questions/19653926/php-remove-fix-module-not-found-or-already-loaded-warnings

We are preferring to avoid shared hostings.
