### ISSUE TITLE
count() and groupBy() together ActiveQuery

### ISSUE THREAD

**Issue by crnimilos** [yiisoft/yii2#10443]
I think that count() should logically return array of groupBy so instead of writing: 
```php
Post::find()
    ->select(['COUNT(*) AS cnt,categoryID'])
    ->groupBy(['categoryID'])
    ->indexBy('categoryID')
    ->all();
```
we could be able to write
```php
Post::find()->groupBy('categoryID')->indexBy('categoryID')->count();
```

What do you people think about it? I think it would be nice...

**Comment by samdark** [comment]
I don't think implicit is good in this case.
