### ISSUE TITLE
Gii adds PJAX outside of PHP tags

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#10441]
Using newest Gii from development branch. During CRUD generation there is an option to add Pjax into index view of CRUD. But when I check this option, it adds Pjax::begin(); and Pjax::end(); outside of PHP tags. Please  fix the issue.

**Comment by SilverFire** [comment]
Thank you for your report. Fixed: https://github.com/yiisoft/yii2-gii/commit/2ae663d62efe3662e72813c5b0c9f633249fe715
