### ISSUE TITLE
error in DBTarget.php

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#10442]
hi im using postgreSQL and when the error log try save in the DB i get this error
in mysql work correctly

the problem is the timestamp :S

$command->bindValues([
                ':level' => $level,
                ':category' => $category,
                ':log_time' => $timestamp,
                ':prefix' => $this->getMessagePrefix($message),
                ':message' => $text,
            ])->execute();

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  la sintaxis de entrada no es válida para integer: «1450637439.0133»
The SQL being executed was: INSERT INTO "log" ("level", "category", "log_time", "prefix", "message")
                VALUES (1, 'yii\base\ErrorException:1', 1450637439.0133, '[webmaster][backend][/backend/ticket/index]', 'exception ''yii\base\ErrorException'' with message ''Class ''backend\assets\AceAsset'' not found'' in C:\xampp\htdocs\backend\views\layouts\LeftColumn.php:20
Stack trace:
#0 C:\xampp\htdocs\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('''', '''')
#1 C:\xampp\htdocs\vendor\yiisoft\yii2\base\Controller.php(386): yii\base\View->renderFile('''', '''', '''')
#2 C:\xampp\htdocs\vendor\yiisoft\yii2\base\Controller.php(372): yii\base\Controller->renderContent('''')
#3 C:\xampp\htdocs\backend\controllers\TicketController.php(61): yii\base\Controller->render('''', '''')
#4 C:\xampp\htdocs\vendor\yiisoft\yii2\base\InlineAction.php(55): backend\controllers\TicketController->actionIndex()
#5 C:\xampp\htdocs\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user_func_array('''', '''')
#6 C:\xampp\htdocs\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams('''')
#7 C:\xampp\htdocs\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('''', '''')
#8 C:\xampp\htdocs\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('''', '''')
#9 C:\xampp\htdocs\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest('''')
#10 C:\xampp\htdocs\backend\web\index.php(18): yii\base\Application->run()
#11 {main}')

**Comment by spiritdead** [comment]
@samdark  can add this fix for the 2.0.7 ?

**Comment by samdark** [comment]
What's your schema?

**Comment by spiritdead** [comment]
'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'pgsql:host=localhost;dbname=cashadgroup',
            'username' => 'postgres',
            'password' => '123456',
            'charset' => 'utf8',
            'schemaMap' => [
                'pgsql'=> [
                    'class'=>'yii\db\pgsql\Schema',
                    'defaultSchema' => 'public' //specify your schema here
                ]
            ], // PostgreSQL
        ],
the db connect correctly is the timespan return float and not integer :S see the value

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: la sintaxis de entrada no es válida para integer: «1450637439.0133»
The SQL being executed was: INSERT INTO "log" ("level", "category", "log_time", "prefix", "message")
VALUES (1, 'yii\base\ErrorException:1', 1450637439.0133, '[w.....

.0133 :S im using the default dbtarget table

**Comment by samdark** [comment]
I mean what are your "log" table columns?

**Comment by spiritdead** [comment]
im using the default
$this->createTable('log', [
            'id' => Schema::TYPE_PK,
            'level' => Schema::TYPE_INTEGER,
            'category' => Schema::TYPE_STRING . '(255)',
            'log_time' => Schema::TYPE_INTEGER . ' NOT NULL',
            'prefix' => Schema::TYPE_TEXT,
            'message' => Schema::TYPE_TEXT,
            'new' => Schema::TYPE_BOOLEAN .' NOT NULL DEFAULT true',
        ], $tableOptions);

**Comment by spiritdead** [comment]
damn is a error in my IDE is double :S and the postgreSQL is extrict, in mysql this truncate the double
