### ISSUE TITLE
[PROPOSAL] query as immutable activerecord object

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#10459]
this could be successfully used for Statistical queries without setters getters method, and is actually faster and could potentially used for other generator queries as well

``` php
class WhateverCount extends \yii\db\ImmutableActiveRecord
{
    public function query()
    {
        return (new \yii\db\Query())->select(['related_id', 'counted' => 'count(*)'])->from('tablename')->groupBy('related_id'); //OR SOMETHING
    }
}

class WhateverModel extends \yii\db\ActiveRecord
{
    public function tablename()
    {
        return 'sometable';
    }

    public function getWhateverCount()
    {
        $this->hasOne(WhateverCount::class,['id'=>'related_id']);
    }
}
```

``` php
WhateverModel::find()->with('whateverCount')->all();
```

would do queries like this then

``` sql
SELECT * FROM sometable;
SELECT related_id, count(*) counted FROM tablename WHERE related_id IN (...) GROUP BY related_id
```

it would give opportunity to do things like this

``` php
WhateverModel::find()->with([
    'whateverCount'=>function($query) {
        $query->andWhere(['>','created_at','2013-02-14 3:22:17']
    }
])->all();
```

And gridview would also like this :)

**Comment by mikk150** [comment]
Right now I am using default \yii\db\ActiveRecord to do so

```php
class LenderLeadSentCount extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tablename';
    }

    public function attributes()
    {
        return ['related_id','counted'];
    }

    public static function find()
    {
        $query=parent::find();
        return $query->select(['related_id', 'counted' => 'count(*)'])->groupBy('related_id');
    }
}
```

It actually works well, and does everything I need, but it shouldn't think that you can mutate attributes

**Comment by mikk150** [comment]
will it happen?

**Comment by samdark** [comment]
It's quite interesting way of using AR. I love it.

Besides assigning attributes directly there are `setAttributes()` and `load()`.

**Comment by klimov-paul** [comment]
For me it breaks ActiveRecord pattern.
The main essence of ActiveRecord - it can save itself. Such immutable ActiveRecord cann't save anything.

**Comment by samdark** [comment]
Well, we may call it aggregate record.

**Comment by mikk150** [comment]
@klimov-paul yes, this pattern would not save anything hence the issue. there are actually other issues too, like sometimes I need to put pk in attributes and sometimes not(but it is wrong anyway)

When I discovered that I could hack up AR like shown in comment, i use it heavily(since I do lots of aggregating queries)

**Comment by klimov-paul** [comment]
The idea itself could be considered, but it will produce confusion. If we add something like this in the core it may be misused.
Actual implementation should be based on a trait, since we have several extension for NOSQL database, which may also require it.

**Comment by mikk150** [comment]
as you can see, AR can also be misused :D
I have no idea, how this can be accomplished in NOSQL. I have used mongodb, but I have never aggregated there

**Comment by mikk150** [comment]
@samdark I am not sure, if we could call it aggregaterecord, since user might not even aggregate anything. There are other immutable queries like generators

**Comment by samdark** [comment]
The SQL ↑ is better to be created using query builder...

**Comment by klimov-paul** [comment]
It seems the feature itself is already represented via `Query::asArray()` option. If it is enabled, no attribute match checks will be performed.

```php
class WhateverCount extends \yii\db\ImmutableActiveRecord
{
    public function query()
    {
        return (new \yii\db\Query())
            ->select(['related_id', 'counted' => 'count(*)'])
            ->from('tablename')
            ->groupBy('related_id')
            ->asArray(true);
    }
}

class WhateverModel extends \yii\db\ActiveRecord
{
    public function tablename()
    {
        return 'sometable';
    }

    public function getWhateverCount()
    {
        $this->hasOne(WhateverCount::class,['id'=>'related_id']);
    }
}

$rows = WhateverModel::find()->with('whateverCount')->all();
foreach ($rows as $row) {
    echo $row->whateverCount['counted'];
}
```

**Comment by mikk150** [comment]
that's nice and all, but you are still using ActiveRecord for wrong purpose :) plus you cannot do relations this way (because arrays do not have that information)

**Comment by dynasource** [comment]
@mikk150, is this something like Mysqls views?

**Comment by mikk150** [comment]
Yes and no.
you could use this to interface views, but not limited to
This approach should eliminate need for views.
I right now use it to generate reports

**Comment by dynasource** [comment]
that sounds quite useful. Do you still think this is something for the core to adopt? Or do you see it to be more useful as a special extension?

**Comment by mikk150** [comment]
To be honest, I do not care, because it is not useful for developers who do not create reports so it could be in its own repository.

**Comment by dynasource** [comment]
alright. In that case we will acknowledge it to be useful as an extension.  Thanks for your fast reply.

**Comment by mikk150** [comment]
@dynasource @samdark Just a reminder: you should really try to make it in Yii3
