### ISSUE TITLE
can't solve 'date' validation problem with 'max', 'min' properties

### ISSUE THREAD

**Issue by Kerych74** [yiisoft/yii2#10455]
I can't understand - function returning string (verified by var_dump()):
````php
['userBirthDate', 'date', 'format' => 'yyyy-MM-dd', 
    'max' => function() {
        $date = new DateTime();
        date_sub($date, date_interval_create_from_date_string('12 years'));
        $maxDate = date_format($date, 'Y-m-d');
        return $maxDate;
    },
    'min' => function() {
        $date = new DateTime();
        date_sub($date, date_interval_create_from_date_string('100 years'));
        $minDate = date_format($date, 'Y-m-d');
        return $minDate;
    }
],
````
 but I have the mistake:
"Object of class Closure could not be converted to string".

![screenshot 2015-12-22 01 16 07](https://cloud.githubusercontent.com/assets/14916179/11944870/ca86f558-a849-11e5-8ae4-de43156cd096.png)

Where the problem?

Thanks!

**Comment by unclead** [comment]
Hmmm why do you try to use closure as value of min/max property if they supports only integer or string?

Look at the doc:
> Lower limit of the date. Defaults to null, meaning no lower limit. This can be a unix timestamp or a > string representing a date time value. If this property is a string, $format will be used to parse it.
