### ISSUE TITLE
[Idea] For Yii 2.1 use namespaced functions and constants as shortcuts.

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#10454]
This is a proposal for this idea https://github.com/yiisoft/yii2/wiki/Ideas-for-2.1#functions

The idea is to create namespaced functions such as

```php
namespace yii\application;

use Yii;

function login($identity, $duration = 0) {
     return Yii::$app->getUser()->login($identity, $duration);
}
```

Then on the controller

```php

namespace app\controller;

use function yii\application\user;

class SiteController extends \yii\web\Controller
{
     public function actionLogin()
     {
          $model = new LoginForm();
          // load, validate password, etc

          return login($model->user);
     }
}
```

My proposal requires that the minium php version for 2.1 would be php 5.6. One issue would be that there is no function or constant autoloading.

For that we can use the `\yii\base\Application::bootstrap()` and allow modules to load a file with all their  shortcuts for functions and contants. something like a file named `framework\base\shortcuts.php`.

It will also allow third party to develop their own shortcuts like

```php
use function rmrevin\yii\fontawesome\FA\icon as i;

echo i('close'); // <i class="fa fa-close"></i>
```

That would be the main advantage over global functions since it won't cause conflicts among which function will be used if a third party library wants to define its own shortcuts such as  `user()`, `url()` or i want to have predefined shortcuts for my application only.

**Comment by klimov-paul** [comment]
Using plain functions even namespaced ones breaks the OOP.
I am against such approach.

**Comment by samdark** [comment]
Could be considered for helpers since syntax is interesting but as @klimov-paul stated already, it will make everything less flexible.

@Faryshta any ideas on how to deal with reduced flexibility?

**Comment by SilverFire** [comment]
Agree with @klimov-paul. I don't like using function-style shortening of OOP calls.

**Comment by samdark** [comment]
Closing till ideas about dealing with flexibility are there.

**Comment by Faryshta** [comment]
Then why is this on the wiki? https://github.com/yiisoft/yii2/wiki/Ideas-for-2.1#functions

also notice I said 'as shortcut' for commonly used functions. Not to replace the existing functionality.

**Comment by samdark** [comment]
To raise the question on how to deal with ability to extend. If it can't be solved, it won't be implemented. That wiki page isn't a plan. It's ideas.

**Comment by Faryshta** [comment]
> To raise the question on how to deal with ability to extend. If it can't be solved

what do you mean?

**Comment by samdark** [comment]
I mean currently in case of `Html` and alike helpers we can use late static binding to extend and customize functionality. I'm not sure if we're able to do the same in case of functions.

**Comment by Faryshta** [comment]
Ohh I get your point. Thats why we will use namespaced functions.

For example function  `yii\helpers\a()` would be a short cut for `yii\helpers\Html::a()`. If someone extends the `Html` class for example `common\helpers\Html` then that person can also create namespaced shortcuts using that class `common\helpers\a()` or something similar. After all those are just shortcuts to existing funcionality.

That will also allow third party to create personalized shortcuts like `rmrevin\yii\fontawesome\FA\icon()`

**Comment by samdark** [comment]
Now we can replace Html with our own implemenation transparently extending from origian but referencing it in the code as it was. I doubt it's possible with functions.

**Comment by Faryshta** [comment]
I honestly don't get whats not going to work.

We can still replace Html with our own implementation transparently since the functions will be just shortcuts, not the actual functionality.

Then new shortcuts can be made as they are needed if they are needed at all. In the example above `yii\helpers\a()` would still be a shortcut for `yii\helpers\Html::a()` regardless on how many times the Html class gets extended.

**Comment by SilverFire** [comment]
> `yii\helpers\a()` would still be a shortcut for `yii\helpers\Html::a()`

In this example `yii\helpers\a()` brings ambiguity. `a()` relates to the `Html` helper, why do we expose it to `yii\helpers` namespace? The better example will be `Html::encode()` vs `Json::encode()`. What is the proper name for them? `encode()` and `json_encode()`? `html_encode` and `encode()`? It looks kludgy, as for me. Why not to leave them just `Html::encode()` and `Json::encode()`?

There are hundreds of helper methods so we need to create a hundred of unobvious shortcuts for them? Of course we can create shortcuts only for the methods, that are popular. but then we will probably have tons of issues and pull requests with topic `Why do we have shortcut for Html::a(), but don't have one for Html::script, huh?`. 

For these reasons I think we shouldn't even start working on this.
