### ISSUE TITLE
Yii2 Gridview filter URL does not work inside form

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#10456]
Show my code below
```php
<?php $form = ActiveForm::begin([
	'id' => 'select-form',
	'method'=>'get',
	'action' => ['formaction'],
]); ?>

<?= GridView::widget([
	'dataProvider' => $dataProvider,
	'filterModel' => $searchModel,
	'filterUrl' => ['testfu'],
	'columns' => [
	
	-----------------------------
	
	]
]); ?>

<?php ActiveForm::end(); ?>
```

When gridview inside active form at time filterUrl does not work.
Whenever use filterUrl in gridview at time call form action/current controller action.

Why?

**Comment by SilverFire** [comment]
Why did you decide it should work?
yii.gridView.js wraps the gridView with the form automatically. Since HTML does not support nested forms, you have some unexpected behavior.

**Comment by hirenbhut93** [comment]
@SilverFire 

Because I have use checkboxcolumn in my grid view.
I submit grid view with selected checkbox. 
Any alternative options is available?

**Comment by SilverFire** [comment]
You can get a list of checked rows using JS. Checkout the manual http://www.yiiframework.com/doc-2.0/yii-grid-checkboxcolumn.html

```js
var keys = $('#grid').yiiGridView('getSelectedRows');
// keys is an array consisting of the keys associated with the selected rows
```

**Comment by SilverFire** [comment]
Something like here https://github.com/mickgeek/yii2-actionbar/blob/master/Widget.php#L216
