### ISSUE TITLE
problem with custom query and postgreSQL 

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#10450]
hi all im trying use this query

```php
$users = (new Query())
    ->select([
        'date(to_timestamp(created_at)) as dateResult',
        'array_agg(DISTINCT id) as ids','count(*) as count'
    ])
    ->from(User::tableName())
    ->groupBy(['date(to_timestamp(created_at))'])
    ->orderBy(['dateResult' => SORT_DESC])
    ->limit(10)->all();
```

but i get this error

```
The SQL being executed was: SELECT date(to_timestamp(created_at)) as dateResult, array_agg(DISTINCT id) as ids, count(*) as count FROM "user" GROUP BY date(to_timestamp(created_at)) ORDER BY "dateResult" DESC LIMIT 10
```

and testing in PGADMIN 3, the problem is "dateResult"  and the correct sintax is dateResult, is a bug in yii2 ?

**Comment by SilverFire** [comment]
> but i get this error

It's not a text of error, it's just the executed query. Could you show the error?

**Comment by spiritdead** [comment]
SQLSTATE[42703]: Undefined column: 7 ERROR: no existe la columna «dateResult»
LINE 1: ... GROUP BY date(to_timestamp(created_at)) ORDER BY "dateResul...
^
The SQL being executed was: SELECT date(to_timestamp(created_at)) as dateResult, array_agg(DISTINCT id) as ids, count(*) as count FROM "user" GROUP BY date(to_timestamp(created_at)) ORDER BY "dateResult" DESC LIMIT 10
Error Info: Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  no existe la columna «dateResult»
LINE 1: ... GROUP BY date(to_timestamp(created_at)) ORDER BY "dateResul...
                                                             ^
)
↵
Caused by: PDOException

SQLSTATE[42703]: Undefined column: 7 ERROR: no existe la columna «dateResult»
LINE 1: ... GROUP BY date(to_timestamp(created_at)) ORDER BY "dateResul...
^

in C:\xampp\htdocs\vendor\yiisoft\yii2\db\Command.php at line 837

**Comment by SilverFire** [comment]
```php
->orderBy(['date(to_timestamp(created_at))' => SORT_DESC])
```

**Comment by spiritdead** [comment]
@SilverFire  thanks, im translating my app mysql to postgreSQL, and im testing in pgadmin 3 and is a little hard find postgresql information for yii2

**Comment by SilverFire** [comment]
There is nothing special you must know in Yii to use PostgreSQL. You error does not relates Yii and it might be easily googled - there is a bunch of similar questions on SO.

Please note, GitHub issues is designed for bugs, not for questions and support. Try to dig into problem a little, instead of asking someone for a answer - you will earn much more experience.

http://www.yiiframework.com/doc-2.0/guide-start-looking-ahead.html
