### ISSUE TITLE
Yii::$app->getRequest()->serverName  check of isset

### ISSUE THREAD

**Issue by Wolframcheg** [yiisoft/yii2#10451]
In my application I need get domain name. I get it from request by means of next command :

```php
Yii::$app->getRequest()->serverName
```
But when I run functional tests I get Exeption, because the created crawler doesn't have variable  $_SERVER['SERVER_NAME']. This is content of $_SERVER : 
```
{
  'HTTP_HOST' =>  string(9) "localhost"
  'HTTP_USER_AGENT' =>  string(19) "Symfony2 BrowserKit"
  'HTTPS' =>  bool(true)
  'REQUEST_URI' =>  string(15) "/index-test.php"
  'REQUEST_METHOD' =>  string(3) "GET"
}
```
Many parameters of class Request have check of isset : 
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L842
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L851
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L869

But getServerName doesn't have it.
Sorry for my bad English )

**Comment by radiocity** [comment]
Php [checks](https://github.com/php/php-src/blob/71c19800258ee3a9548af9a5e64ab0a62d1b1d8e/sapi/cgi/cgi_main.c#L829) server_name variable for existing, I believe.

**Comment by radiocity** [comment]
Всё таки без индусов не обошлось...

**Comment by samdark** [comment]
?

**Comment by radiocity** [comment]
Зачем делать проверку поля, если оно по умолчанию забивается самим php?

**Comment by samdark** [comment]
В первом посте написано же: https://github.com/yiisoft/yii2/issues/10451#issue-123325703

**Comment by radiocity** [comment]
Понял.  Извиняюсь 😊

**Comment by NabiKAZ** [comment]
@samdark 
is better Yii::$app->getRequest()->serverName or Yii::$app->request->serverName ?

**Comment by samdark** [comment]
@NabiKAZ doesn't matter.

**Comment by alexagapovpav** [comment]
Yii::$app->request->hostInfo
