### ISSUE TITLE
[\yii\di\Instance] Something went wrong

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#10467]
It seems there is a problem with the documentation and method implementation.
```php
Instance::ensure('db');
```
![oops](https://cloud.githubusercontent.com/assets/675367/11985734/ec63a44c-a9d8-11e5-9f7e-a1d6e889d3ce.png)
- https://github.com/yiisoft/yii2/blob/master/framework/di/Instance.php#L110
- https://github.com/yiisoft/yii2/blob/master/framework/di/Instance.php#L129

In [unit tests](https://github.com/yiisoft/yii2/blob/master/tests/framework/di/InstanceTest.php) there is no validation on the use case

**Comment by SilverFire** [comment]
It makes no sense to call `ensure` without the second argument.
You MUST pass an object or a class name to ensure that `db` in `Yii::$app` is instance of second argument.

**Comment by LAV45** [comment]
Can I something not so understood
```php
/*
* ...
* @param string $type the class/interface name to be checked. If null, type check will not be performed.
* ...
*/
public static function ensure($reference, $type = null, $container = null)
```

**Comment by SilverFire** [comment]
Well, it seems I was wrong, sorry.
Let's move to the PR

**Comment by SilverFire** [comment]
Thank you for digging in the problem and a good fix! https://github.com/yiisoft/yii2/commit/fcf25e8fa1e8070abe9df21c89a35f245a338cd4

Happy NY :)
