### ISSUE TITLE
Error when querying using LIKE with params

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#10462]
```php
...
class Suite extends \yii\db\ActiveRecord
{
   ...
    public static function findByLocation(string $location) : array
    {
        return self::find()
            ->innerJoin('hotel', 'suite.hotel_id=hotel.id')
            ->innerJoin('pt_hotel_address', 'hotel.id=pt_hotel_address.hotel_id')
            ->innerJoin('address', 'pt_hotel_address.address_id=address.id')
            ->where(['like', 'address.district', ':location'], [':location' => $location])
//            ->params([':location' => $location]) <--- it does not work too, same error. Same for addParams()
            ->all();
    }
}
```
Error:
```
Database Exception – yii\db\Exception

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
The SQL being executed was: SELECT `suite`.* FROM `suite` INNER JOIN `hotel` ON suite.hotel_id=hotel.id INNER JOIN `pt_hotel_address` ON hotel.id=pt_hotel_address.hotel_id INNER JOIN `address` ON pt_hotel_address.address_id=address.id WHERE `address`.`district` LIKE '%:location%'
Error Info: Array
(
    [0] => HY093
    [1] => 0
)
↵
Caused by: PDOException

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

in /home/sidney/www/bitbucket/..../vendor/yiisoft/yii2/db/Command.php at line 837
```

Should not any of those tries do work?

Yii 2.0.6
PHP 7.0

**Comment by lichunqiang** [comment]
```
->andWhere(['like', 'address.district', $location])
```

**Comment by cebe** [comment]
thanks, @lichunqiang

**Comment by slinstj** [comment]
Yeah, thanks, but that way I know, it is in the docs. 

The real question is: How to achieve that **using binded params**. If I can use binded params in other queries, why i cant use in 'like' queries?

This is the question.
Thanks.

**Comment by slinstj** [comment]
@cebe @lichunqiang

**Comment by cebe** [comment]
> but that way I know, it is in the docs.

I am very sure it is not, if you find it, it needs to be fixed.

When using array syntax, the binding is done internally by yii. binding is only needed if you write string condition.

**Comment by slinstj** [comment]
By
> but that way I know, it is in the docs.

I meant:
> ->andWhere(['like', 'address.district', $location])

My only preoccupation about that is: will Yii do some type of sql injection prevention (even that binding data in PDO layer) when I call `->andWhere(['like', 'address.district', $location])` without expressely binding parameters the same way it will do if I call something like `->where('fieldX' => ':data', [':data' => $someData])` expressely binding params?

Thanks @cebe

**Comment by lichunqiang** [comment]
> will Yii do some type of sql injection prevention

of course

**Comment by slinstj** [comment]
@lichunqiang, maybe it can be *of course* for you, not for all just because of one detail: in the most of methods we have a :placeholder but specifically in this one we haven't. 

So I really don't want to think what is your definition of *of course* because it could be something not so natural or logical like in this case.

**Comment by SilverFire** [comment]
We can mention it in the guide

**Comment by slinstj** [comment]
Hi @SilverFire, 

I am still not sure about the exact way that Yii uses `->where(['like', 'field', $value]).` calls. Does Yii use a pdo prepared statement internally even without we use a `:placeholder`?

OR

... Yii just insert the own `$value` inside the sql query like it does in other calls like `->where(['field', $value])`? In this case, how we could use `like` with prepared statements instead?

I would like to investigate it but I have no free time for a while. 
Thank u.

**Comment by unclead** [comment]
>  Does Yii use a pdo prepared statement internally even without we use a :placeholder?

Yeap, as far as i see in the code Yii converts all values to placeholders and then executes query as usual pdo statement

```
        foreach ($values as $value) {
            if ($value instanceof Expression) {
                foreach ($value->params as $n => $v) {
                    $params[$n] = $v;
                }
                $phName = $value->expression;
            } else {
                $phName = self::PARAM_PREFIX . count($params);
                $params[$phName] = empty($escape) ? $value : ('%' . strtr($value, $escape) . '%');
            }
            $parts[] = "$column $operator $phName";
        }
```

**Comment by slinstj** [comment]
Thank you, @unclead 

Based in your answer, I have debugged `yii\db\QueryBuilder::buildLikeCondition()` and it generates a final string like `" 'address'.'district' LIKE :qp0 "` where `:qp0` will be the `$value` after have been binded.
