### ISSUE TITLE
can't solve 'when' validation problem

### ISSUE THREAD

**Issue by Kerych74** [yiisoft/yii2#10466]
````php
['userArea', 'required', 'when' => function($this) {
    return $this->userCountry == 'United States';
}],
````
![screenshot 2015-12-23 17 45 05](https://cloud.githubusercontent.com/assets/14916179/11980695/058d61b0-a99d-11e5-81b2-5579a9bb4875.png)

**Comment by SilverFire** [comment]
You don't have `whenClient` option. Please, follow [guide](http://www.yiiframework.com/doc-2.0/guide-input-validation.html#conditional-validation)

**Comment by SilverFire** [comment]
@Kerych74 for the last 2 days you've post 3-in-a-row issues that are not bugs.

Please notice, GitHub is for bug reports. We're kindly asking you not to abuse GitHub and visit our [forum](http://www.yiiframework.com/forum/) or [Gitter chat](https://gitter.im/yiisoft/yii2) for support. Thank you

**Comment by Kerych74** [comment]
OK. I undestand
