### ISSUE TITLE
Different return value when calling \yii\db\ActiveRecord::tableName()

### ISSUE THREAD

**Issue by khotim** [yiisoft/yii2#10464]
gii generated this function:
```php
public static function tableName()
{
    return '{{%table_a}}';
}
```

my query looks like this:
```php
public function getHistoryA()
{
    $expression = new \yii\db\Expression('"'.$this->tableName().'" as source_table');
    $query = $this->getTransactionA()
        ->select(['col1', 'col2', 'col3', $expression])
        ->orderBy('col1');
    $query->union($this->getHistoryB(), true);
        
    return $query;
}
```
then, in my view:
```php
foreach ($modelA->getHistoryA()->asArray()->all() as $key => $historyA) {
    echo $historyA['source_table'] .' - '. $modelA->tableName();
}
```
that will result like this (including quote):
```html
`table_a` - {{%table_a}}
`table_b` - {{%table_a}}
```
i'm hoping i could use the `source_table` for conditional purpose, something like:
`if ($modelA->tableName() === $historyA['source_table'])`

**Comment by cebe** [comment]
can you show the query that is executed? you should find it in the debug toolbar.

**Comment by khotim** [comment]
query:
```sql
(SELECT `col1`, `col2`, `col3`, "`table_a`" as source_table FROM `history_table_a` ORDER BY `col1`)
UNION ALL
(SELECT `col1`, `col2`, `col3`, "`table_b`" as source_table FROM `history_table_b` ORDER BY `col1`)
```

**Comment by SilverFire** [comment]
It's an expected behavior.

`{{%table_a}}` is being converted to `` `table_a` ``, and then you wrap it with `"`.

You should use `Yii::$app->db->getSchema()->getRawTableName($this->tableName)` instead

**Comment by khotim** [comment]
i'd expect `$modelA->tableName()` convert `{{%table_a}}` to `` `table_a` `` as well but it doesn't seem so.

anyway, thanks. i switch to `getRawTableName()`.
