### ISSUE TITLE
Return active records by select query

### ISSUE THREAD

**Issue by StagnantIce** [yiisoft/yii2#10479]
Hi all
I want display my rows in data provider (grid view) without remove dublicates.

Example:

Order::find()->joinWith('orderItems');

public function getOrderItems() {
    return $this->hasMany(OrderItems::className(), ['order_id' => 'id']);
}

And i want see all order items with order dublicates. But i see only one order with array order items.

Order::find()->joinWith('orderItems')->indexBy('orderItems.id') not work =(.

Thanks.

**Comment by samdark** [comment]
Start with OrderItems:

```php
$orderItems = OrderItems::find()->joinWith('order');
```

btw., please use forums for questions since GitHub is for bug reports.

**Comment by StagnantIce** [comment]
I dont want start with OrderItems, orders can have no items, but i want see them.
