### ISSUE TITLE
Guide: Core Validators - links errors

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2#10470]
On top of the page http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html

The list of core validator (from 1 to 23) should be links to the anchors on the same page only:
````
<li><a href="#boolean"></a><a href="./yii-validators-booleanvalidator.html">boolean</a></li>
````
 should be
````
<li><a href="#boolean">boolean</a></li>
````
This will make it easier to read the correct information on the guide part.

**Comment by SilverFire** [comment]
Agree on this. Would you like to submit a PR?

**Comment by CedricYii** [comment]
Well, I don't know how to do, and it doesn't seem trivial. Can you handle it?

**Comment by SilverFire** [comment]
Okay

**Comment by cebe** [comment]
Fixed, thanks for reporting!
