### ISSUE TITLE
Views share functionality

### ISSUE THREAD

**Issue by dhiman252** [yiisoft/yii2#10484]
Hi Team,

Is there any functionality of sharing a variable across all the views in a controller ?
Like the laravel provides this functionality.
If we have a controller then in its constructor we can make use of the following line
<pre>
public function __construct(){
        view()->share('roleCustomer', User::getRole(User::ROLE_CUSTOMER));
        view()->share('roleProfessional', User::getRole(User::ROLE_PROFESSIONAL));
        view()->share('roles', User::getRole());
        view()->share('user', Auth::user());
        view()->share('currentLanguage', App::getLocale());
    }
</pre>
Now all the views render this controller actions will have the above variables always available.

**Comment by kidol** [comment]
`$this->view->params['foo'] = 'bar';`

**Comment by SilverFire** [comment]
@kidol thank you

**Comment by SilverFire** [comment]
@dhiman252 please, visit our guide http://www.yiiframework.com/doc-2.0/guide-structure-views.html#sharing-data-among-views
