### ISSUE TITLE
Possible parser error on subquery when you use hash format of where clause

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2#10481]
Hello,

Here's 2 forms of exactly the same query that returns different results but the only difference is the format of where clause used in the subquery in querybuilder

Main Query

```php
        $query1=(new \yii\db\Query())
            ->select(['question.id'])
            ->from('question')
            ->innerJoin('option', 'option.question_id=question.id')
            ->where(['not exists', $subquery1])
            ->groupBy('question.id')
            ->all();
```

Subquery Option A:

```php
        $subquery1 = (new \yii\db\Query())
            ->select(['label'])
            ->from('option')
            ->where(['option.question_id'=>'question.id', 'option.mark'=>1]);
```

Subquery OPTION B:

```php
        $subquery1 = (new \yii\db\Query())
            ->select(['label'])
            ->from('option')
            ->where('option.question_id=question.id AND option.mark=1');
```

Option A Generates;

```sql
SELECT `question`.`id` FROM `question` INNER JOIN `option` ON option.question_id=question.id WHERE NOT EXISTS (SELECT `label` FROM `option` WHERE (`option`.`question_id`='question.id') AND (`option`.`mark`=1)) GROUP BY `question`.`id`
```

OPTION B Generates;

```sql
SELECT `question`.`id` FROM `question` INNER JOIN `option` ON option.question_id=question.id WHERE NOT EXISTS (SELECT `label` FROM `option` WHERE option.question_id=question.id AND option.mark=1) GROUP BY `question`.`id`
```

The only real difference is the where clause in Option where 'question.id' is enclosed in quotes.
Both Queries return data but only option B match raw SQL possible because the parser maybe treating 'question.id' as a string.

Is my observation correct or is there a different way to pass a value in the hash format of the where clause without enclosing it as a string?

**Comment by CedricYii** [comment]
I guess things behave like expected.

If you want to avoid escaping, you need to write this way:
````
 $subquery1 = (new \yii\db\Query())
            ->select(['label'])
            ->from('option')
            ->where(['option.question_id'=> new \yii\db\Expression('question.id'),
                     'option.mark'=>1]);

````

**Comment by dbd5** [comment]
@CedricYii,

I think your review of this issue was a bit on the surface.
My concern is primarily the need for consistency in the interface, why is 'option.question_id' parsed properly even though it is in quotes like 'question.id' but the later needs escaping?

A

**Comment by cebe** [comment]
> http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#hash-format
> 
> It is written as an array whose keys are column names and values the corresponding values that the columns should be.

values are quoted properly so if you want to pass something else than simple values, you have to wrap them in an expression.
