### ISSUE TITLE
A Session bug.

### ISSUE THREAD

**Issue by cevin** [yiisoft/yii2#10489]
File `https://github.com/yiisoft/yii2/blob/master/framework/web/User.php : 573`

If set session handler is redis, function `regenerateID` will be error.

**Comment by samdark** [comment]
Can you provide error message along with stacktrace?

**Comment by cevin** [comment]
`Failed to create(read) session ID "tmp path"`.

**Comment by SilverFire** [comment]
Could you show a stacktrace, please?

**Comment by githubjeka** [comment]
@cevin What is PHP version?

**Comment by cevin** [comment]
@SilverFire  just return 500 error.not have any trace info.

use `var_dump` & `exit`  let me know the problem is `session_regenerate_id`. And the error is a redis problem just like @githubjeka .

**Comment by githubjeka** [comment]
@cevin 
Comment `@` in https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L263 and you see ^_^

**Comment by githubjeka** [comment]
And try update `yiisoft/yii2-redis` to `dev-master`

**Comment by SilverFire** [comment]
@cevin did you solve your problem?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/10583

**Comment by cevin** [comment]
@SilverFire 

`\yii\redis\Session` add a function like this.

```
    public function regenerateID($deleteOldSession = false)
    {
        return true;
    }
```

**Comment by githubjeka** [comment]
Dear SilverFire.
`return true;` is equals he solved his problem. 

Close issue ^_^

**Comment by SilverFire** [comment]
I'm closing the issue in favour of https://github.com/yiisoft/yii2/issues/10583
