### ISSUE TITLE
Query::indexBy with dimensions

### ISSUE THREAD

**Issue by quantum13** [yiisoft/yii2#10487]
I've just read, that I need to create issue for PR. This is it.

Very often I need to get models with index not by key, but by not unique attribute (as array). For example to index models by status or related id.

Quick example (for model Customer from tests):
```php
$customerClass::find()->indexBy('name', ['status'])->orderBy('id')->asArray()->all();
```
will return
```
array(2) {
  [1] => // status "1"
  array(2) {
    'user1' => // name
    array(6) {'id' => "1", 'email' => "user1@example.com", 'status' => "1" ... }
    'user2' =>
    array(6) {'id' => "2", 'email' => "user2@example.com", 'status' => "1" ...}
  }
  [2] => // status "2"
  array(1) {
    'user3' =>
    array(6) {'id' => "3", 'email' => "user3@example.com", 'status' => "2"... }
  }
}
```
and (I use this case very often)
```php
$customerClass::find()->indexBy(null, ['status'])->orderBy('id')->asArray()->all();
```
will return
```
array(2) {
  [1] => //status
  array(2) {
    [0] => // just array index
    array(6) {'id' => "1", 'email' => "user1@example.com", 'status' => "1" ... }
    [1] =>
    array(6) {'id' => "2", 'email' => "user2@example.com", 'status' => "1" ...}
  }
  [2] =>
  array(1) {
    [0] =>
    array(6) {'id' => "3", 'email' => "user3@example.com", 'status' => "2"... }
  }
}
```

I created pull request with possible realization and some tests: #10477 (realization in this pull request is not completed, concept only).

**Comment by quantum13** [comment]
@yiisoft/core-developers any comments?

**Comment by SilverFire** [comment]
We are preparing 2.0.7 release now. This issue is assinged to a next release, so we will check it later. Thank you for your patience

**Comment by SilverFire** [comment]
The feature request is discarded. Please, see the [comment in the PR](https://github.com/yiisoft/yii2/pull/10477#issuecomment-188460352)
