### ISSUE TITLE
BaseHtml.php Html::a() method why not send the $scheme value for Url::to() it's a problem？

### ISSUE THREAD

**Issue by toshcn** [yiisoft/yii2#10486]
```php
public static function a($text, $url = null, $options = [])
 {
        if ($url !== null) {
            $options['href'] = Url::to($url);//not send the boolean value $scheme 
        }
        return static::tag('a', $text, $options);
 }
```

use the Html::a() to create a hyperlink tag , but method can't send the boolean value $scheme for Url::to(); it's a problem？

**Comment by samdark** [comment]
Where do you want to get that $scheme?

**Comment by SilverFire** [comment]
I guess @toshcn suggests to add a parameter `$scheme` to `Html::a()` method and pass it to `Url::to`.

**Comment by samdark** [comment]
It's not possible in 2.0.x.

**Comment by toshcn** [comment]
in Url::to() method:
public static function to($url = '', $scheme = false)

I want to use Html::a() create a hyperlink has hostInfo (  domain name), but can't send a parameter to Url::to(), the value $scheme is for Url::to() method.

**Comment by toshcn** [comment]
BaseHtml.php Html::a():
I thought can rewrite like that:
public static function a($text, $url = null, $options = [])
{
      if ($url !== null) {
           if (isset($options['scheme'] && $options['scheme'] != '')) {
                $options['scheme'] = (boolean) $options['scheme'];
                $options['href'] = Url::to($url, $options['scheme']);
                unset($options['scheme']);
           } else {
                $options['href'] = Url::to($url);
           }
      }
      return static::tag('a', $text, $options);
}

**Comment by samdark** [comment]
Will consider it for 2.1. Can't change method signatures in 2.0.x.

**Comment by cebe** [comment]
if you really need the scheme you can just call `Html::a('text', Url::to(..., 'https'))`. I think adding it to `Html::a()` will make it too complex.

**Comment by toshcn** [comment]
It's only way to cleate a hyperlink has hostInfo in 2.0.x
like thas:
Html::a( 'text', null, [ 'herf' => Url::a( ['your controller method url'], true ) ]);
Html::a( 'text', null, [ 'herf' => Url::a( ['your controller method url'], 'http' ) ]);
Html::a( 'text', null, [ 'herf' => Url::a( ['your controller method url'], 'https' ) ]);

**Comment by cebe** [comment]
`Html::a('Test page',  Url::to(['/site/test'], 'https'))` This works just fine.

**Comment by Faryshta** [comment]
I think it would be easier to add an special `option`

```php
public static function a($text, $url = null, $options = [])
 {
        if ($url !== null) {
            $options['href'] = Url::to(
                $url,
                ArrayHelper::remove($options, 'scheme', 'http')
            );
        }
        return static::tag('a', $text, $options);
 }
```

**Comment by cebe** [comment]
we could but I am not convinced that this is needed given that it works already really easy using Url::to()

**Comment by samdark** [comment]
I don't think we should introduce it. It complicates API.
