### ISSUE TITLE
Active records by select query is not working correctly for some case.

### ISSUE THREAD

**Issue by StagnantIce** [yiisoft/yii2#10492]
Hi all, 

my recent issue closed #10479 without any answer for me.

I want display my rows in data provider (grid view) without remove dublicates.

Example:

Order::find()->joinWith('orderItems');

public function getOrderItems() {
    return $this->hasMany(OrderItems::className(), ['order_id' => 'id']);
}

And i want see all order items with order dublicates. But i see only one order with array order items.

Order::find()->joinWith('orderItems')->indexBy('orderItems.id') not work =(.

If i change Order on OrderItems:

OrderItems::find()->joinWith('order');

orders with not items not displayed.

Thank you.

**Comment by samdark** [comment]
It was answered. Please use forums for questions if you're not sure it's a bug or not.

**Comment by StagnantIce** [comment]
How ??

"You cannot start a new topic"

**Comment by samdark** [comment]
Reply to 2—3 existing topics. That's spam protection.
