### ISSUE TITLE
Big size of log file (yii\log\FileTarget) increases processing time

### ISSUE THREAD

**Issue by AstRonin** [yiisoft/yii2#10491]
Hi all,

I have a configuration for logs:
```php
'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['info'],
                    'logFile' => '@runtime/logs/info.log',
                ],
            ],
        ],
```
Yii2 - 2.0.6
php - 5.6

Problem is next, when file become bigger also increases processing time of application
For example,
file == 2Mb, processing time ~ 400 ms
file == 4Mb, processing time ~ 600 ms
file == null, processing time ~ 100 ms

**Comment by SilverFire** [comment]
Ensure you have turned on [FileTarget::enableRotation](http://www.yiiframework.com/doc-2.0/yii-log-filetarget.html#$enableRotation-detail) and reduce [FileTarget::maxFileSize](http://www.yiiframework.com/doc-2.0/yii-log-filetarget.html#$maxFileSize-detail).

The problem might be related to your local environment characteristicsю

**Comment by AstRonin** [comment]
Yes, I can. But is it normal to have the hundreds files by 500 Kb? Please, maybe you will verify about some bug.

**Comment by SilverFire** [comment]
Ok, let it be open for additional check

**Comment by kidol** [comment]
@AstRonin
How many messages you log per application instance? If you have more than 1000 messages, try setting `exportInterval` to `0`. Also do you log to disk, NAS, ...?

I made simple test and don't see an issue:

log size: 0 MB = ~3ms processing time for `FileTarget::export()`
log size: 9 MB = ~3ms

Adding ``` for ($i=0;$i<100;$i++) {Yii::warning("test");}```

log size: 0 MB = ~5ms
log size: 9 MB = ~5ms

**Comment by AstRonin** [comment]
And Does processing time of app not increase?
Not too many messages, a few tens.
Disc is common HDD
OS is Windows
Strange...

**Comment by kidol** [comment]
Ok this is very strange. I'm now able to reproduce it to some degree.
If I delete the log file and reload the page, the timing slowly goes up on every page load (on SSD as well as on spinning disk). At only 1 MB size it takes 100ms for the `export()` method.

Now the funny part: If I then delete the log file and replace it with an already 9MB big log file, the timing is constant again as in my previous benchmark.

Is this maybe some windows related issue (write cache ...)?

> I checked on several computers (but windows)

It means you also tested on linux?

**Comment by kidol** [comment]
Looks like it's AntiVirus. If I disable real-time protection or add exclusion for log directory, problem is gone.

**Comment by samdark** [comment]
File size should not affect write speed unless file is scanned or read by something blocking it.
