### ISSUE TITLE
MongoDB, MongoDbTarget, text of message as an \Exception

### ISSUE THREAD

**Issue by AstRonin** [yiisoft/yii2#10496]
Hi all,

Can we add condition in method `yii\mongodb\log\MongoDbTarget::export()` like it is in? 
https://github.com/yiisoft/yii2/blob/master/framework/log/DbTarget.php#L71
```php
if ($text instanceof \Exception) {
    $text = (string) $text;
} else {
    $text = VarDumper::export($text);
}
```
Because VarDumper making very big info if it a Exception stacktrace

**Comment by AstRonin** [comment]
Can I ask other question about this function `MongoDbTarget::export()`?
Why we don't use `batchinsert` in this function?
http://php.net/manual/ru/mongocollection.batchinsert.php
We can avoiding the costs of network

**Comment by samdark** [comment]
That's separate issue. Let's discuss it separately.

**Comment by AstRonin** [comment]
ok, sorry
https://github.com/yiisoft/yii2/issues/10501
