### ISSUE TITLE
Неправильное форматирование даты

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#10499]
Запись в гриде из базы отображается через 1 год.
![4](https://cloud.githubusercontent.com/assets/5754949/12030120/acb39d94-ae0a-11e5-9f5e-3d8b6437369a.png)
![3](https://cloud.githubusercontent.com/assets/5754949/12030117/a90bef0c-ae0a-11e5-8649-8519edbf92b3.png)
```php
//grid column
 [
  'attribute' => 'started_at',
  'format' => 'datetime'
 ],
//global config
 'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'dateFormat' => 'd MMM YYYY',
            'datetimeFormat' => 'd MMM YYYY (HH:mm)',
            'timeFormat' => 'HH:mm',
            'nullDisplay' => '',
],
```

**Comment by Vovan-VE** [comment]
Bug in ICU is occiring for dates near to year edge (or to year end only - not sure).

**Comment by samdark** [comment]
Need your PHP/ICU version, OS version.

**Comment by exru** [comment]
Linux utsserver 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64
![5](https://cloud.githubusercontent.com/assets/5754949/12034595/2656d826-ae44-11e5-8140-8cc206b02722.png)

**Comment by exru** [comment]
```php
$formatter = new IntlDateFormatter('en_US', IntlDateFormatter::NONE, IntlDateFormatter::NONE, $timeZone, null, 'd MMMM YYYY (HH:mm)');
//Выдает 29 December 2016 (11:00)
//А с русским беда
```

**Comment by exru** [comment]
Нашел как исправить 
```php
 'datetimeFormat' => 'd MMMM yyyy (HH:mm)',
//но все равно надо заглушку наверное поставить
```
