### ISSUE TITLE
MongoDB, MongoDbTarget::export(), using batchInsert

### ISSUE THREAD

**Issue by AstRonin** [yiisoft/yii2#10501]
Why we don't use `batchInsert` in this function [yii\mongodb\log\MongoDbTarget::export()](https://github.com/yiisoft/yii2-mongodb/blob/master/log/MongoDbTarget.php#L55)?
http://php.net/manual/ru/mongocollection.batchinsert.php
We can avoiding the costs of network.

**Comment by klimov-paul** [comment]
Same question can be asked for regular `yii\log\DbTarget`:
https://github.com/yiisoft/yii2/blob/master/framework/log/DbTarget.php#L67

It also may benefit of usage `batchInsert()`, which is available for relational databases.

`MongoDbTaget` follows the same convension. Perhaps it is a mistake, which should be fixed - in this case it should be fixed for `DbTarget` as well, perhaps there was some reson for such behavior - in this case we need to find out which it was before make a decision.

**Comment by klimov-paul** [comment]
MongoDB issue opened at:
https://github.com/yiisoft/yii2-mongodb/issues/102

As for regular `DbTarget`: at present state usage of `batchInsert` for it will be unsafe: see #11242,  #6526 , #9276
