### ISSUE TITLE
a problem in Compare validator

### ISSUE THREAD

**Issue by engmmrj** [yiisoft/yii2#10505]
hi
a problem  in  Compare validator.
['password_repeat', 'compare', 'compareAttribute' => 'password_hash'],

when password_hash is not empty and password_repeat is empty.
 validate is true.

**Comment by samdark** [comment]
Why are you comparing hash with password?

**Comment by engmmrj** [comment]
Is field of null == field of string ?

**Comment by samdark** [comment]
What do you mean? `null == ''`? Yes.

**Comment by engmmrj** [comment]
when i  filled password_hash text box and password_repeat was null .
form vlaidate returened true.

**Comment by samdark** [comment]
Is it user model or some other model? If it's user model then hash should not be obtained from the form at all.
