### ISSUE TITLE
Active record and graphql

### ISSUE THREAD

**Issue by gwelr** [yiisoft/yii2#10500]
Is there any plan or discussions to add graphql support to ActiveRecord ?
I know GraphQL is still a moving target but I wonder if there is any plan about it.

**Comment by gwelr** [comment]
GraphQL home: http://graphql.org/
GraphQL working draft: http://facebook.github.io/graphql/

**Comment by samdark** [comment]
No, there's no plan implementing it. You can do it and release as an extension.

**Comment by mushahidh** [comment]
very rude. :(

**Comment by TerraSkye** [comment]
https://github.com/tsingsun/yii2-graphql there is an extension already.

**Comment by cedx** [comment]
@TerraSkye Too bad: the README is in Chinese or Japanese or a language which I can't read...
