### ISSUE TITLE
PageCache looses headers/cookies/status if response data cache entry gets lost while fragment cache entry still lives

### ISSUE THREAD

**Issue by drscre** [yiisoft/yii2#10506]
The problem arises because PageCache stores response content and response headers/status/cookies in **separate** cache keys.

If response header/status/cookies entry gets lost but fragment cache entry still lives (for example, when memcached hits it's memory limit), the response headers will get lost:

``` php
class PageCache extends ActionFilter {
...
  public function beforeAction($action) 
  {
        ...
        if ($this->view->beginCache($id, $properties)) {
            $response->on(Response::EVENT_AFTER_SEND, [$this, 'cacheResponse']);
            return true;
        } else {
            $data = $this->cache->get($this->calculateCacheKey()); // < --- Cache miss can happen here!
            if (is_array($data)) {
                $this->restoreResponse($response, $data);
            }
            $response->content = ob_get_clean();
            return false;
        }
  }
...
}
```

**Comment by samdark** [comment]
Indeed. What do you think is the best way to fix that?

**Comment by drscre** [comment]
I think, the simplest way is not to use FragmentCache at all and explicitely use php buffering instead. (see my proposed pull request)

**Comment by kidol** [comment]
> not to use FragmentCache at all and explicitely use php buffering instead

But then dynamic content feature is lost: http://www.yiiframework.com/doc-2.0/yii-base-view.html#renderDynamic%28%29-detail

Not sure about a better solution though.

**Comment by drscre** [comment]
@kidol You are right about dynamic content, thanks. If we leave it out, it will be a compatibility break.

**Comment by cebe** [comment]
we could fetch header cache data before calling beginCache() on the view. if header data is a cache miss, we invalidate the content cache too.
