### ISSUE TITLE
Yii2 Pjax inside ListView Item is not working

### ISSUE THREAD

**Issue by robert589** [yiisoft/yii2#10502]
I have been trying to resolve this issue in these few days, basically i am trying to have commetn and child comments, the comment has a button/link called 'retrievecomment' to retrieve child comment.

I found out that The pjax is not working, it keeps refreshing the whole page.

**Edited: The code below is inside _list_comment.php, _list_comment.php is inside the index.php ListView, So _list_comment.php will be called several times depends on the number of items**

		<div class="row">	
				<?= $model['comment']?>
		</div>
			
			
		<?php Pjax::begin([
				'id' => 'childCommentData-'.$comment_id,
		    	'timeout' => 5000,
				'clientOptions'=>[
				    	'container' => '#childCommentData-' . $comment_id,

				    	'linkSelector'=>'#retrieveComment'.$comment_id
						]
				]);?>
				<div  class="row">

					<div id="selector"align="right">
					<?= Html::a('Retrieve Comment', ["../../thread/index?id=" . $model['thread_id'] . "&comment_id=" . $comment_id], 
												['data-pjax' => '#childCommentData-'.$comment_id, 'class' => 'btn btn-default'
												,'id' => 'retrieveComment' . $comment_id]) ?>
					</div>
					<div  class="col-md-12">

						<?php if(isset($retrieveChildData)){ ?>
							<?= ListView::widget([

									'dataProvider' => $retrieveChildData,
									'options' => [
										'tag' => 'div',
										'class' => 'list-wrapper',
											'id' => 'list-wrapper',
									],
					    				'layout' => "\n{items}\n{pager}",

									'itemView' => function ($model, $key, $index, $widget) {
										return $this->render('_list_child_comment',['model' => $model]);
									}, 
									'pager' => [
						       	 		'firstPageLabel' => 'first',
						        		'lastPageLabel' => 'last',
						        		'nextPageLabel' => 'next',
						        		'prevPageLabel' => 'previous',
						        		'maxButtonCount' => 3,
									],
								]) ?>

						<?php } ?>
						

					</div>
			</div>
			<?php Pjax::end();?>
		
	</div>
</article>

The error  says "Model is not defined" which is the outer space of the pjax. This is the reason why i think the whole page is refreshed

**I also put this in the java script code**

               <?php  $this->registerJsFile(Yii::$app->request->baseUrl.'/js/list_comment.js');
			$script =<<< JS
		$(document).pjax('retrieveComment' + $comment_id, '#childCommentData-' + $comment_id, { fragment: '#childCommentData-' + $comment_id });

		$('#childCommentData-' + $comment_id ).on('pjax:error', function (event) {
								    alert('Failed to load the page');
								    event.preventDefault();
								});
		JS;
			$this->registerJs($script);
		?>

And i keep receive the alert failed to load page.

**The response header:** 
Request URL:http://localhost/startUp/thread/index?id=1&comment_id=1&_pjax=%23childCommentData-1
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:[::1]:80
Response Headers
view source
Connection:close
Content-Length:1387
Content-Type:text/html; charset=UTF-8
Date:Tue, 29 Dec 2015 12:02:18 GMT
Server:Apache/2.4.9 (Win64) PHP/5.5.12
X-Powered-By:PHP/5.5.12
Request Headers
view source
Accept:text/html, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Type:application/x-www-form-urlencoded; charset=UTF-8

Host:localhost
Referer:http://localhost/startUp/thread/index?id=1
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
X-CSRF-Token:UkwwSXdGUE4gO2MdRCMBDDENRBMkMykHGQ9XeB4uYTlnHGECGgkbPQ==
X-PJAX:true
X-PJAX-Container:#childCommentData-1
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
id:1
comment_id:1
_pjax:#childCommentData-1

**Comment by SilverFire** [comment]
It's always hard to read bug reports without exact problem description but with tons of irrelevant code.

> The error says "Model is not defined" which is the outer space of the pjax. This is the reason why i think the whole page is refreshed

It is an exception, isn't it? Then show the screenshot and a stacktrace.
Show your controller action, that handles the PJAX request.

The issue because it's rather related to the developer's error, than to Yii2 or Pjax therefore I'm closing it. 

@robert589 you sill can post answer to my questions and I'll help you.

**Comment by dynasource** [comment]
@robert589, please see my post at:
https://github.com/yiisoft/yii2/issues/4486#issuecomment-50322596

Reloads are because of issues in your own implementation. Its not a PJAX or Yii thing.

**Comment by SilverFire** [comment]
I'm closing the issue because @robert589 is inactive and the problem is not verified.
