### ISSUE TITLE
PJAX removes important scripts if it is placed in layout

### ISSUE THREAD

**Issue by KROT47** [yiisoft/yii2#10509]
e.g. If you put Pjax in layout and ActiveForm in view then comes:
1 view execution
* ActiveForm assets registration

2 layout execution
* Pjax::begin(), which launches $view->clear() - here ActiveForm Assets would be removed

So in the end ActiveForm stays without JS assets
Maybe you should remove $view->clear() from Pjax::init or replace it?

Thanks!

**Comment by SilverFire** [comment]
Yeah, I've faced this problem but then found, that we just should not call `Pjax::begin()` in the layout and couple reasons for it. 

It's often necessary to configure PAJX on certain pages in special way.. Sometimes the page should be rendered without PJAX at all. Placing PJAX call in `layout` means that we should create our own View and handle both of the examples in configuration way.

I'd prefer to leave `Pjax::begin()` in each view file. Global configuration you can store in params and most of views will have something like `Pjax::begin(Yii::$app->params['default-pjax'])`

**Comment by SilverFire** [comment]
For now we will not remove `$view->clear()` because of the design and BC.
