### ISSUE TITLE
Caching db...

### ISSUE THREAD

**Issue by free6k** [yiisoft/yii2#10510]
We have next code in `yii\db\command::queryInternal()`(https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L817)

Why in cache key not information about dependency?

In my work i have next case:
i wrote tests for configuration model, for this i created 2 models with different name, after i have get same results, because $cacheKey not contains dependency.

Example this tests here: https://github.com/free6k/yii2-tag-dependency-helper/blob/master/tests/DatabaseTest.php#L244

if always change $id_author = 3, tests not working...

why it was made? thanks and happy new year!

**Comment by cebe** [comment]
dependency is added on set and evaluated inside of Cache::get(). https://github.com/yiisoft/yii2/blob/master/framework/caching/Cache.php#L112
