### ISSUE TITLE
ActiveRecord additional attribute and JSON response format

### ISSUE THREAD

**Issue by zibra** [yiisoft/yii2#10511]
Hi,

Inside my model class (Exhibition > ActiveRecord) I have additiona attribute declated by:
```php
    public function getFullPath()
    {
        return 'media/'.$this->poster_url;
    }
```
In my controller I use action:
```php
    public function actionJson()
    {
        $items = Exhibition::find()->all();
        \Yii::$app->response->format = 'json';
        return $items;
    }
```
but it shows only attributed from database table. How to filter them, modify values and add some dynamic (additional, calculated) attributes?

Should I just my own JSON from the scratch?

**Comment by SilverFire** [comment]
Check out the [Array::toArray()](http://www.yiiframework.com/doc-2.0/yii-helpers-basearrayhelper.html#toArray()-detail) for one-time call or the [ArrayableTrait](http://www.yiiframework.com/doc-2.0/yii-base-arrayabletrait.html) for well-desined approach.

GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.
