### ISSUE TITLE
yii\base\Security.php -> generateRandomKey() in 2.0.7-dev throws "Unable to generate a random key"

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#10519]
As i could see there is a new Implementation of `generateRandomKey()`. We end up in base Exception:

```
Message: Unable to generate a random key
File: vendor/yiisoft/yii2/base/Security.php
Line: 542
```

Environment:

+ PHP Version 5.5.9-1ubuntu4.9
+ CGI/FastCGI

OpenSSL is enabled:
```
OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1f 6 Jan 2014
OpenSSL Header Version	OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by samdark** [comment]
@tom-- any idea?

**Comment by tom--** [comment]
One: Relative to <= 2.0.6, OpenSSL was removed for non-Windows platforms owing to https://bugs.php.net/bug.php?id=70014 and the general OpenSSL concerns.

Two: I don't understand why this system cannot read /dev/urandom. @nadar would you put `phpinfo()` into a gist please? That might have clues.

**Comment by nadar** [comment]
@tom-- i just wrote you in gitter.

**Comment by tom--** [comment]
@nadar in what now?

**Comment by nadar** [comment]
i just wrote you a private message on Gitter (https://gitter.im/tom--), as there is sensitive data.

**Comment by tom--** [comment]
oh.

if you want to keep your `phpinfo()` off github, you can email me at fsb@thefsb.org

**Comment by tom--** [comment]
@nadar please try this test script and paste the results here:

```php
<?php

$tests = [
    "function_exists('random_bytes')",
    "defined('OPENSSL_VERSION_TEXT') ? OPENSSL_VERSION_TEXT : null",
    "PHP_VERSION_ID",
    "function_exists('mcrypt_create_iv')",
    "DIRECTORY_SEPARATOR",
    "sprintf('%o', lstat('/dev/urandom')['mode'])",
    "sprintf('%o', lstat('/dev/urandom')['mode'] & 0170000)",
    "bin2hex(@file_get_contents('/dev/urandom', false, null, 0, 16))",
];

foreach ($tests as $i => $test) {
    $result = eval('return ' . $test . ';');
    printf("%2d  %s\n    %s\n\n", $i+1, $test, var_export($result, true));
}
```

**Comment by nadar** [comment]
```

 1  function_exists('random_bytes')
    false

 2  defined('OPENSSL_VERSION_TEXT') ? OPENSSL_VERSION_TEXT : null
    'OpenSSL 1.0.1f 6 Jan 2014'

 3  PHP_VERSION_ID
    50509

 4  function_exists('mcrypt_create_iv')
    false

 5  DIRECTORY_SEPARATOR
    '/'

 6  sprintf('%o', lstat('/dev/urandom')['mode'])
    '0'

 7  sprintf('%o', lstat('/dev/urandom')['mode'] & 0170000)
    '0'

 8  bin2hex(@file_get_contents('/dev/urandom', false, null, 0, 16))
    ''
```

**Comment by tom--** [comment]
@nadar thanks. i added another test to the script. please update your output

**Comment by nadar** [comment]
```

 1  function_exists('random_bytes')
    false

 2  defined('OPENSSL_VERSION_TEXT') ? OPENSSL_VERSION_TEXT : null
    'OpenSSL 1.0.1f 6 Jan 2014'

 3  PHP_VERSION_ID
    50509

 4  function_exists('mcrypt_create_iv')
    false

 5  DIRECTORY_SEPARATOR
    '/'

 6  sprintf('%o', lstat('/dev/urandom')['mode'])
    '0'

 7  sprintf('%o', lstat('/dev/urandom')['mode'] & 0170000)
    '0'

 8  bin2hex(@file_get_contents('/dev/urandom', false, null, 0, 16))
    ''

 9  ini_get('open_basedir')
    '/var/www/vhosts/MY_EXAMPLE_HOST_DOT_COM/:/tmp/'
```

**Comment by tom--** [comment]
Looks like shared hosting in which the provider has denied access to `/dev/urandom` and doesn't have mcrypt. This leaves you in a tough position because problems with OpenSSL's RNG arose last year: It was discovered that PHP was using it in an unsafe way that didn't get fixed until 5.6.10 and OpenSSL's RNG fell out of favor in general. This is why Yii stopped using it in 2.0.7 for systems other than Windows.

I can think of two options for you:

- Get your hosting provider to install the PHP mcrypt extension. This reads internally from `/dev/urandom` but not in a way that the open_basedir setting inhibits. I just tested with PHP 5.4 and restrictive open_basedir and `mcrypt_create_iv()` appeared to work.

    On this Ubuntu system it would be (for a sysop as simple as) `apt-get install php5-mcrypt` and restart FPM

- Get your hosting provider to append `":/dev/urandom"` to the open_basedir INI setting and restart FPM

I don't know how to configure an Ubuntu LTS to use LibreSSL instead of OpenSSL. This would be a nice option.

I don't think it would be fair to the community of Yii users to reintroduce unconditional OpenSSL. Part of the idea with this update was tighten Yii's use of available RNGs.

**Comment by tom--** [comment]
Actually, a couple more options:

- extend `Security::generateRandomKey()` something [like this](https://gist.github.com/tom--/990c0f72aee4fe5a502c) and configure Yii to use your component instead of the base component. NOTE: I have not tested this  
- stay on 2.0.6

**Comment by nadar** [comment]
Thanks for you reply and your effort regarding this problem! It would be nice to know how many Yii users would have the same issue on their hosting providers, but for me its not a problem to avoid this problem as i can partially manage those servers by our selfs since i know what has to be changed. So i guess, the issue can be closed and other users will find this topic trough googling.

**Comment by tom--** [comment]
I'm keeping the [diagnostic script here](https://gist.github.com/tom--/ff7173f9c8a3431a2f7e) for anyone else experiencing issues.

**Comment by linslin** [comment]
For everybody who did not install php-mcrypt right now (thats why the exception was thrown in my case), http://php.net/manual/de/mcrypt.installation.php:

Linux 
```
apt-get install php5-mcrypt
mv -i /etc/php5/conf.d/mcrypt.ini /etc/php5/mods-available/
php5enmod mcrypt
service apache2 restart
```

**Comment by tom--** [comment]
Hi @linslin Would you please run the [platform diagnostic script](https://gist.github.com/tom--/35f8a029d77467559cf2#file-testplatform-php)? I am curious why your PHP cannot read /dev/urandom.

**Comment by mcki0127** [comment]
Here are my results prior to installing mcrypt.

```
 1  function_exists('random_bytes')
    false

 2  defined('OPENSSL_VERSION_TEXT') ? OPENSSL_VERSION_TEXT : null
    'OpenSSL 1.0.1f 6 Jan 2014'

 3  PHP_VERSION_ID
    50509

 4  function_exists('mcrypt_create_iv') ? bin2hex(mcrypt_create_iv(8, MCRYPT_DEV_URANDOM)) : null
    NULL

 5  DIRECTORY_SEPARATOR
    '/'

 6  sprintf('%o', lstat('/dev/urandom')['mode'])
    '20666'

 7  sprintf('%o', lstat('/dev/urandom')['mode'] & 0170000)
    '20000'

 8  bin2hex(file_get_contents('/dev/urandom', false, null, 0, 8))
    'bddd76d88fdc02ae'

 9  ini_get('open_basedir')
    ''
```

**Comment by tom--** [comment]
@mcki0127 Couple of bits of info that could be in the diag script but unfortunately are not:

- os?
- yii version? this issue's title mentions 2.0.7

**Comment by riyaskp** [comment]
Here are my result before installing mycrypt 

1 function_exists('random_bytes')
 false 
2 defined('OPENSSL_VERSION_TEXT') ? OPENSSL_VERSION_TEXT : null 
'OpenSSL 1.0.1f 6 Jan 2014'
3 PHP_VERSION_ID 
50509 
4 function_exists('mcrypt_create_iv') ? bin2hex(mcrypt_create_iv(8, MCRYPT_DEV_URANDOM)) : null NULL 
5 DIRECTORY_SEPARATOR 
'/' 
6 sprintf('%o', lstat('/dev/urandom')['mode']) 
'0' 
7 sprintf('%o', lstat('/dev/urandom')['mode'] & 0170000) 
'0' 
8 bin2hex(file_get_contents('/dev/urandom', false, null, 0, 8)) 
'' 
9 ini_get('open_basedir') '/var/www/clients/client1/web4/web:/var/www/clients/client1/web4/private:/var/www/clients/client1/web4/tmp:/var/www/MY_EXAMPLE_HOST_DOT_COM/web:/srv/www/MY_EXAMPLE_HOST_DOT_COM/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin'

OS: Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-74-generic x86_64)
Yii version 2.0.7.

**Comment by tom--** [comment]
@riyaskp your open_basedir prevents reading anything in /dev

php7 is also a good option. (it's also very fast)

**Comment by mcki0127** [comment]
@tom-- 
OS: Ubuntu 14.04.4 LTS
Yii version: 2.08

php5enmod mcrypt fixed the problem for me.

**Comment by tom--** [comment]
@mcki0127 thanks.

i do not understand why generateRandomKey() could not read /dev/urandom on your system.

**Comment by cebe** [comment]
> i do not understand why generateRandomKey() could not read /dev/urandom on your system.

open_basedir.

**Comment by professor93** [comment]
OS: Ubuntu 14.04.4 LTS
Yii version: 2.08

php5enmod mcrypt fixed the problem for me too.

**Comment by tom--** [comment]
@cebe open_basedir was empty in the output from mcki0127. you were probably looking at  riyaskp's.

**Comment by cebe** [comment]
Oh yeah right. For mcki0127 it could be a difference in web and console PHP?
