### ISSUE TITLE
optimisticLock: potential security

### ISSUE THREAD

**Issue by svok** [yiisoft/yii2#10520]
It looks for me that current version system of optimisticLock allows security vialation. Suppose, an attacker forms 2 requests: one is normal, while in another request  the version number is increased by 1. In this case an unintended behavior of the model may occure.

On the other hand, I do not see any reason for sequential numbering of the record version. A random version ID (or hash) may preform the same job: if the ID has changed we thow a reject event. So any update between my read and write will unpredictably change the ID and my attempts will be rejected.

So, I suggest to change (BaseActiveRecord.php:718)
```
        if ($lock !== null) {
            $values[$lock] = $this->$lock + 1;
            $condition[$lock] = $this->$lock;
        }
```
by
```
        if ($lock !== null) {
            $difference = '9223372036854775806';
            $rand_percent = bcdiv(mt_rand(), mt_getrandmax(), 12);
            $values[$lock] = bcmul($difference, $rand_percent, 0);
            $condition[$lock] = $this->$lock;
        }
```
or something similar.

**Comment by klimov-paul** [comment]
> Suppose, an attacker forms 2 requests: one is normal, while in another request the version number is increased by 1.

Version attribute should not be exposed to the user input or form submission. You should specify validation rules in the that way.

**Comment by svok** [comment]
Well, I'm not going to show the user version field, but I need to send it in the hidden field. This is not a problem to fake this value for an experienced attacker. The optimisticLock is supposed to be used in financial operations and is very attractive for such attacks.

He forms TWO requests one after another. In one request version is 101, in another is 102. The attacker first sends request with 102, then he replaces 101->103 in the first request and ... the validation will be successfully passed since the actual version of the record will be 103 according to `$this->$lock + 1`.

Anyway, I cannot imagine why you need so predictive sequential numbering of the record version.
