### ISSUE TITLE
yii2 modals displaying hidden under menu

### ISSUE THREAD

**Issue by ber5ien** [yiisoft/yii2#10524]
Hi Team,

I am not sure if this is Yii2 issue or something else.

I have a strange issue when suddenly modals are displaying under menu so they are being hovered by the menu.

![image](https://cloud.githubusercontent.com/assets/854403/12115138/83a8f19a-b3a7-11e5-8283-5a3885565258.png)

    <div class="wrap">
        <nav id="w12" class="navbar-inverse navbar-fixed-top navbar" role="navigation"><div class="container"><div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#w12-collapse"><span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span></button><a class="navbar-brand" href="/index.php">My Brand</a></div><div id="w12-collapse" class="collapse navbar-collapse"><ul id="w13" class="navbar-nav navbar-right nav"><li><a href="/index.php/site/index">Home</a></li>
    <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">Tickets <b class="caret"></b></a><ul id="w14" class="dropdown-menu"><li><a href="/index.php/tickets/open" tabindex="-1">Unassigned</a></li>
    <li class="divider"></li>
    <li><a href="/index.php/tickets/user" tabindex="-1">Your Tickets</a></li>

example of my modal

    <div id="TimeSheetModal" class="fade modal" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">
    <div class="modal-content">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Timesheets Entries View</h4>
    </div>
    <div class="modal-body">
    <div class="time-view">

    <div id="w8" class="grid-view">
    <table class="table table-striped table-bordered"><thead>
    <tr><th>Staff Id</th><th>Comment</th><th>Timespent</th><th>Entry Made</th></tr>
    </thead>
    <tbody>
    <tr><td colspan="4"><div class="empty">No results found.</div></td></tr>
    </tbody></table>
    </div>
    </div>
    <a href="view-time-details?id=308900">View in Details</a><a class="pull-right" href="/index.php/foc/request?id=308900">Request FOC</a>
    </div>

</div>
</div>

Many Thanks

**Comment by samdark** [comment]
Seems to be project specific. It's better to discuss it at forums if you're not sure it's a bug or not.
