### ISSUE TITLE
namespace should be in small letter "namespace app\controllers;"

### ISSUE THREAD

**Issue by anmolview** [yiisoft/yii2#10527]
In BASIC app,
After  generating crud

ie generated Controller is UserController.php
 Under UserController.php 

namespace app\Controllers;
it give error: Not Found (#404)

after change C to c  :  "namespace app\controllers;"
 its working perfectly.

**Comment by lichunqiang** [comment]
It's your own responsibility, you should be carefully input the `Controller Class` field.

**Comment by anmolview** [comment]
OK i got it.
