### ISSUE TITLE
Class SolrClient not found

### ISSUE THREAD

**Issue by zeevy** [yiisoft/yii2#10523]
i have installed solr pecl extension for php.  I am able to connect to solr and search the documents using raw php code as bellow 

$client = new SolrClient(['hostname' => 'localhost', 'port' => 8983, 'path' => 'solr/documents']);
$query = new SolrQuery();
$query->setQuery('radio');

$query->addField('id')->addField('title');
$query->setHighlight(true);
$query->addHighlightField('content');
$query->setHighlightFragsize(500);
$query_response = $client->query($query);
$response = $query_response->getResponse();

which is working fine, but i use this code in yii controller i get the bellow error.

 PHP Fatal Error – yii\base\ErrorException
Class 'app\controllers\SolrClient' not found

"SolrClient" is a inbuilt php function, don't know why yii is searching for it in the controllers 

nginx/1.6.2
PHP 5.6.14
Yii Framework/2.0.6

**Comment by Alex-Code** [comment]
Yii2 uses namespaces, you need to prefix global classes with a backslash \
`\SolrClient`

**Comment by zeevy** [comment]
yes thanks alex

**Comment by SilverFire** [comment]
Thank you @Alex-Code
