### ISSUE TITLE
Url validator passes incorrect values

### ISSUE THREAD

**Issue by sosnovski** [yiisoft/yii2#10533]
К примеру url вида http://ya.1ru.!@.!$%^ считается валидным. Это нормальное поведение?

For example URL like `http://ya.1ru.!@.!$%^` passes the validation. Is it a normal behavior?

**Comment by SilverFire** [comment]
Verified. The url passes the validation, but it's inforrect.

**Comment by SilverFire** [comment]
The regular expression captures only `http://ya.1ru`, leaving `.!@.!$%^` unmatched.

```pcre
/^(http|https):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+)/i
```

Maybe, we should improve the regexp to check the domain name from the biggining till the first `/` or `?`

**Comment by samdark** [comment]
Yep.

**Comment by Shadowmad** [comment]
Good evening,

I have fixed this bug and did PR. https://github.com/yiisoft/yii2/pull/10600 Please review the code
