### ISSUE TITLE
Method addChild from PhpManager and DbManager incorrectly by ManagerInterface

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#10537]
https://github.com/yiisoft/yii2/blob/master/framework/rbac/ManagerInterface.php#L136

```
/**
     * Adds an item as a child of another item.
     * @param Item $parent
     * @param Item $child
     * @return boolean whether the child successfully added
     * @throws \yii\base\Exception if the parent-child relationship already exists or if a loop has been detected.
     */
    public function addChild($parent, $child);
```

But `PhpManager` and `DbManager`  returns only `true` and `\yii\base\InvalidCallException` returned, not `\yii\base\Exception`.

**Comment by samdark** [comment]
There are 2 exceptions thrown (depends on driver), both as subclasses of `\yii\base\Exception` so this part is correct.

**Comment by samdark** [comment]
Same about returned values. It depends on the driver. The condition of returning a boolean is met by all current drivers.
