### ISSUE TITLE
Adding value-less attribute in <form> tag using ActiveForm::begin

### ISSUE THREAD

**Issue by gvanto** [yiisoft/yii2#10532]
How can I add a value-less attribute to the form tag?

I want to have:
```
<form data-abide >
```
according to: http://foundation.zurb.com/sites/docs/abide.html

I've tried
```
<?php $form = ActiveForm::begin(['id' => 'contact-form', 'options'=>['data-abide'=>'']]); ?>
```
but get output:
```
<form data-abide="ak8hvf-abide" >
```

http://www.yiiframework.com/forum/index.php/topic/69191-adding-attributes-to-form-tag
http://stackoverflow.com/questions/34667635/how-to-add-valueless-attribute-to-form-tag-using-yii2-activeform

**Comment by lichunqiang** [comment]
It works fine.

Are you do something extra by yourself?

https://github.com/yiisoft/yii2/blob/master/framework%2Fhelpers%2FBaseHtml.php#L1740-L1762

**Comment by gvanto** [comment]
Not done anything extra by myself no.
Also tried boolean true as value:
```
<?php $form = ActiveForm::begin(['id' => 'contact-form', 'options'=>['data-abide'=>true]]); ?>
```

But still get:
```
<form id="contact-form" data-abide="8j636r-abide" method="post" action="/contact">
```

**Comment by lichunqiang** [comment]
It strangely, I can not reproduce. Wait for other people point out the reason..

**Comment by gvanto** [comment]
You have tried:
```
<?php $form = ActiveForm::begin(['id' => 'contact-form', 'options'=>['data-abide'=>true]]); ?>
```

And get:
```
<form data-abide>
```
?

That's really strange yes! :-(

**Comment by lichunqiang** [comment]
Yep...

**Comment by gvanto** [comment]
Bugger!

I'm using this as code base btw: 
https://github.com/foundationize/yii2

It is exact install of yii2 basic app, but uses foundationize/yii2-foundation package too. As far as I know nothing has changed in the implementation of ActiveForm::begin()

**Comment by SilverFire** [comment]
@gvanto you've posted the right code

```php
<?php $form = ActiveForm::begin(['id' => 'contact-form', 'options' => ['data-abide' => true]]); ?>
```

I guess you get  `data-abide="ak8hvf-abide"` because Abide plugin searches for the DOM elements with `data-abide` attribute and sets the value of the attribute to some random key. Yii2 does can't do it for sure.

**Comment by gvanto** [comment]
Thanks SilverFire, this makes sense. Is there any downside to trying to use adide.js together with Yii2's validation? (Probably yii2's is enough already huh?)

**Comment by SilverFire** [comment]
No, Yii2 does not forces it's own validation. If built-in validation does not fit your architecture and you can not adjust it - you can try to use anything else.

**Comment by gvanto** [comment]
I was more thinking of using adide for pretty formatting of validation output - but I don't see why Yii's builtin validation wouldn't be good enough - have looked through docs looks pretty solid should cover most things (especially with conditional validation).

**Comment by SilverFire** [comment]
Yii2 validation is extendable, you can create your own validator with solid logic and validate input it both server- and client-side. Check out built-in validators to find the validators for your needs and get inspiration for your own validators developing.
