### ISSUE TITLE
Restriction in order By

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#10535]
How can I add a "custom" order by?
I can't write this:
```php
$query->orderBy('CASE WHEN x = y THEN 0 ELSE 1 END');
```

Shouldn't this [method](http://www.yiiframework.com/doc-2.0/yii-db-querytrait.html#orderBy%28%29-detail) read the string as it is? Like the `where` method.

**Comment by samdark** [comment]
Have you tried wrapping a string with `\yii\db\Expression`?

**Comment by llfm** [comment]
This?
```php
$query->orderBy(new \yii\db\Expression('CASE WHEN x = y THEN 0 ELSE 1 END'));
```
 It doesn't work. The final guilty is [guy](https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L808).

**Comment by samdark** [comment]
Right. It works with columns only now...

**Comment by cebe** [comment]
It should work when using array syntax: `$query->orderBy(['CASE WHEN x = y THEN 0 ELSE 1 END' => SORT_ASC]);`

But we may allow expression too.

**Comment by andrewnester** [comment]
@cebe I've checked, actually it already allows using `Expression` for order by.
following test is passed successfully
```
$query->orderBy(new Expression('CASE WHEN x = y THEN 0 ELSE 1 END'));
$this->assertEquals(['CASE WHEN x = y THEN 0 ELSE 1 END' => SORT_ASC], $query->orderBy);
```

Expressions are processing here https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L801

So I guess there is no need to change anything

**Comment by samdark** [comment]
Yes, a test would not hurt.

**Comment by cebe** [comment]
related to #8824
