### ISSUE TITLE
Unknown method unique() exception in Migrations. 

### ISSUE THREAD

**Issue by ejoo** [yiisoft/yii2#10544]
I'm trying to create migration with unique method to apply uniqueness to the field. Here is the example code that throws unknown method exception.

 $this->createTable('posts', [
            'id' => $this->primaryKey(),
            'title' => $this->unique()->notNull()
        ]);

update: 
Here is the snapshot of the error:
![capture](https://cloud.githubusercontent.com/assets/8073885/12222498/0454db60-b7e0-11e5-9fe6-bf979b7f901d.PNG)

**Comment by samdark** [comment]
Which framework version are you using?

**Comment by ejoo** [comment]
@samdark  I'm using 2.0.7.

**Comment by nizarhunzai** [comment]
having same issue..

**Comment by SilverFire** [comment]
You should declare the column type first.

`$this->integer()->unique()->notNull()`

**Comment by nizarhunzai** [comment]
thank you @SilverFire.
