### ISSUE TITLE
can't get  return value  when i used Event Handlers

### ISSUE THREAD

**Issue by xjdata** [yiisoft/yii2#10543]
```php
    const EVENT_GENERATE = 'generate';
    public function generate()
    {
       return (string)mt_rand(100000, 999999) 
    }
```
in my controller
```php
$code=  $this->trigger(self::EVENT_MAKE_CODE));
//$code =  true;
```
how to get this  return value?   or  My mistake   Improper use of the event?

thk!

**Comment by SilverFire** [comment]
[Event::trigger](http://www.yiiframework.com/doc-2.0/yii-base-event.html#trigger()-detail) is a void function.

If you want to return some value from the event - create a custom Event class and pass it as a second argument to the [Component::trigger()](http://www.yiiframework.com/doc-2.0/yii-base-component.html#trigger()-detail) method.

**Comment by SilverFire** [comment]
Although I don't think that using events to return something is a good idea. Multiple handlers may be attached to a single event. It's better to use behaviors, helpers or traits for your case.

**Comment by SilverFire** [comment]
And the last one. For the future please notice, that GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

**Comment by xjdata** [comment]
all right , i will send question to   to those place next .  but  still thank  you .
