### ISSUE TITLE
Ternary operator being used to pass referenced instance in Module::getInstance() method

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#10542]
The line I am talking about is this one https://github.com/yiisoft/yii2/blob/master/framework/base/Module.php#L150

The issue is better described here http://stackoverflow.com/questions/3389928/can-you-pass-by-reference-while-using-the-ternary-operator

The fix is simple, we can even use the `ArrayHelper` class

`return ArrayHelper::getValue(Yii::$app->loadedModules, static::className());`

**Comment by SilverFire** [comment]
Question on SO is about passing scalars by reference with `&`.
In `getInstance()` we don't use `&` operand, because classes are always passed by reference in PHP.

There is no need to change anything, as for me.
