### ISSUE TITLE
Internationalization message extraction

### ISSUE THREAD

**Issue by petrabarus** [yiisoft/yii2#10547]
So I want to divide the translations in my codebase base on, let's say, `frontend` and `backend` like in `yii2-app-advanced` template.

I have like this in the `common/config/main.php`

```
        'i18n' => [
            'translations' => [
                'frontend*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                ],
                'backend*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@backend/messages',
                ],
            ]
        ]
```

and something like this
```
//frontend\controllers\SiteController::actionIndex
Yii::t('frontend/index', 'Test');
//backed\controllers\SiteController::actionIndex
Yii::t('backed/index', 'Test');
```

At first when I was trying to extract the messages, I thought running the `message/extract` will automatically put all of the categories into the `basePath` set in the translations.

But turns out it was put under the `common` directory. And when I read the config file generated by `message/config` it said like this

```
// Root directory containing message translations.
    'messagePath' => __DIR__,
```

and in this guide 

http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#using-the-message-command

> `messagePath`: path where to store message files, which should match the i18n's `basePath` parameter stated in config.

So does that mean we have to set a config for each category and message source?

I mean, why not we let the message source / translations provide the config for the extraction?

I mean something like this

```
        'i18n' => [
            'extractor' => [ //default configuration for extractor
                'languages' => ['de'],
                'translator' => 'Yii::t',
                'removeUnused' => true,
                'except' => [ //if this is being overriden by an extractor, the extractor will run in a new loop
                    '.svn',
                    '.git',
                    '.gitignore',
                    '.gitkeep',
                    '.hgignore',
                   '.hgkeep',
                   '/messages',
                ],
            ],
            'translations' => [
                'frontend*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'extractor' => [ //config per message source
                        'removeUnused' => false,
                    ]
                ],
                'backend*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@backend/messages',
                    'extractor' => [
                        'class' => 'my\custom\PhpMessageExtractor',
                        'removeUnused' => true,
                    ]
                ],
            ]
        ]
```

This way we don't need to set an additional config for the `message/extract` and we can just set the config using `--appconfig` if we do want to have additional config.

And this way we can refactor `yii\console\controllers\MessageController` pulling up methods like `saveMessagesToPHP`, `saveMessagesCategoryToPHP`, `saveMessagesToPO`, `saveMessagesToPOT`, `saveMessagesToDb` to classes, e.g., `yii\i18n\PhpMessageExtractor`, `yii\i18n\DbMessageExtractor`, `yii\i18n\GettextMessageExtractor`.

**Comment by samdark** [comment]
Because extraction tool is independent from `i18n` component and in fact it's independent from the app as well. We don't really want to put these in application config since it's not needed fro the application to function.
