### ISSUE TITLE
ErrorHandler: cannot use errorAction for 3rd party Exceptions

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#10559]
I am trying to port Payum into a Yii2 extension, however the ErrorHandler in Yii2 is preventing me to correctly handle some exceptions thrown by Payum.

In Yii1 it was possible to [attach an event handler to 'onException'](https://github.com/Payum/PayumYiiExtension/blob/master/src/Payum/YiiExtension/PaymentController.php#L18).

In Yii2 no such event exists, so one must rely on ErrorHandler. ErrorHandler however [ignores a custom errorAction](https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L91) because the exceptions that need to be handled are not children of UserException.

How should I handle this with an extension?

**Comment by SilverFire** [comment]
You can wrap the Payum call in try/catch block. Usually there is no need to change global error handling behavior.

**Comment by vercotux** [comment]
I can do that, but not the extension users. Do I have to require them to wrap every component call in a try catch? That would be very inconvenient.

I guess I have to fix ErrorHandler, include it in the extension and tell the users to override the default one on controller init.

**Comment by samdark** [comment]
Create a wrapper that forwards calls and does try-catch internally. You have to somehow deal with error though.

**Comment by vercotux** [comment]
You mean something like this (inside a Component)? 

```PHP
public function __call($methodName, $methodParams) {
    if (method_exists($this->payum, $methodName)) {
        return call_user_func_array(array($this->adLdapClass, $methodName), $methodParams);
    }       
}
```

Is it ok to override a magic methods like that? I remember in Yii1 it was advised against it. Just wanna follow proper standards.

**Comment by samdark** [comment]
Either that or multiple methods for concrete API. It's OK to override magic methods overall but check if you need standard Yii behavior as well. If you do, run `parent::__call`.
