### ISSUE TITLE
Console silent prompt

### ISSUE THREAD

**Issue by makroxyz** [yiisoft/yii2#10551]
Is there any way to have a silent prompt in Console Application? (ex: enter a password)

**Comment by samdark** [comment]
Currently not.

**Comment by lichunqiang** [comment]
https://github.com/Seldaek/cli-prompt

You can use this.

**Comment by makroxyz** [comment]
Thanks but I'm on a Linux server... This extension is based on .exe file
Il 12 gen 2016 05:19, "LightOfHeaveN" <notifications@github.com> ha scritto:

**Comment by lichunqiang** [comment]
@makroxyz It supported linux...

**Comment by makroxyz** [comment]
sorry, my fault... thanks!

**Comment by samdark** [comment]
Won't be implemented in 2.0.
