### ISSUE TITLE
following error is coming when i run composer update or run any commnd

### ISSUE THREAD

**Issue by anoopavk** [yiisoft/yii2#10554]
following error is coming when i run composer update or run any command

Fatal error: Call to undefined method Fxp\Composer\AssetPlugin\Package\Version\VersionParser::parseLinks() in /root/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php on line 272

**Comment by samdark** [comment]
Update global fxp installation:

```
composer global require "fxp/composer-asset-plugin:~1.1.1"
```

**Comment by anoopavk** [comment]
When i run this command they show same error.

**Comment by samdark** [comment]
`composer self-update && composer global require "fxp/composer-asset-plugin:~1.1.1"`

**Comment by anoopavk** [comment]
![error](https://cloud.githubusercontent.com/assets/16552679/12258853/c38da8c4-b937-11e5-8362-d9e348cbf80d.jpg) @ now!..

**Comment by samdark** [comment]
Weird.

**Comment by cebe** [comment]
looks like composer broke api on update and now it can not run. try removing global composer vendor dir, which is `/root/.composer/vendor` in your case and run the commands again.

**Comment by anoopavk** [comment]
Thanks....

**Comment by ajkosh** [comment]
i did everything mentioned above
still i m getting error
The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).
./composer.json has been updated
The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by SilverFire** [comment]
Check out the solution suggested by @cebe in [this comment](https://github.com/yiisoft/yii2/issues/10554#issuecomment-171623038)
