### ISSUE TITLE
Yii2 Datepicker error display issue

### ISSUE THREAD

**Issue by desaikalpesh34** [yiisoft/yii2#10552]
i have issue while using yii2 datepicker widget
i am using

In View

```php
 <?php
          echo DatePicker::widget([
         'model' => $modeljob,
        'attribute' => 'due_date',
        'options' =>['class'=>'form-control'],
       //'language' => 'ru',
      //'dateFormat' => 'yyyy-MM-dd',
     ]);?>
```

in Model

```php
[['job_no','status_id','due_date'], 'required'], 
```

while create new job validation error not displaying on page (red and green)

**Comment by samdark** [comment]
Could you provide a screenshot?

**Comment by desaikalpesh34** [comment]
![screenshot from 2016-01-12 14 43 54](https://cloud.githubusercontent.com/assets/10667017/12259390/6cf58ed8-b93b-11e5-8a16-dff5eea3f027.png)

**Comment by desaikalpesh34** [comment]
![create new job 2016-01-12 14-46-41](https://cloud.githubusercontent.com/assets/10667017/12259410/96590638-b93b-11e5-8f9e-5e9f87362506.png)

**Comment by desaikalpesh34** [comment]
i try hard but not success...:)
when i hit submit button its return to create action and don't show validation error hence user confuse what is going wrong...

**Comment by SilverFire** [comment]
You are calling widget without ActiveForm. The following should work as expected:

```
$form->field($modeljob, 'due_date')->widget(DatePicker::className(), [
        'model' => $modeljob,
        'attribute' => 'due_date',
        'options' =>['class'=>'form-control'],
        //'language' => 'ru',
       //'dateFormat' => 'yyyy-MM-dd',
]);
```

**Comment by desaikalpesh34** [comment]
ohhh my god!!!!!
sorry for my mistake....
Its amaging
thanks a lot @ SilverFire
