### ISSUE TITLE
405, method not allowed after login

### ISSUE THREAD

**Issue by dawei101** [yiisoft/yii2#10568]
### Step:

1. User's logging status is expired
2. user request with POST method from page
3. redirect to login page
4. user sign in , and redirect to the RETURN URL with GET
5. 405

**Comment by samdark** [comment]
Makes sense overall. POST won't be filled so there's no sense to have it as return URL same about other methods that aren't GET.

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/7381abbcc1c119b46186e350e776c6a8ce940a89
