### ISSUE TITLE
can not connect to database in baidu app engine

### ISSUE THREAD

**Issue by luobenyu** [yiisoft/yii2#10560]
## connection problem 
connect from any ip to a specified baidu app engine (e.g. purchased pro)failed. 
## configs
as in baidu app engine (pro) , "%" stands for any ip to access in whitelist, and connection from command-line or a SQL client succeed.
## respond
"yii\db\Exception" as "Access Denied" for "'my_account'@'%'"

**Comment by lichunqiang** [comment]
are you sure configed password correctly?

**Comment by cebe** [comment]
@luobenyu please post the full error message including stack trace, also verify your password and username

**Comment by SilverFire** [comment]
Closing the issue because @luobenyu is inactive and the seems to be not YIi2-related.
