### ISSUE TITLE
REST URL parameters are not parsing on the prod server 

### ISSUE THREAD

**Issue by alexweb** [yiisoft/yii2#10561]
Hi,
I have this url in my app: http://site.com/api/users/1   (api - is a REST module)
And it's working correctly on the dev server - returns a User model. 
However when I uploaded the code on the prod, that url is not working anymore.
I got a message: 

```xml
<response>
<name>Bad Request</name>
<message>Required parameters are missing: id</message>
<code>0</code>
<status>400</status>
<type>yii\web\BadRequestHttpException</type>
</response>
```

If I set ID as GET parameter like this: http://site.com/api/users/1?id=1 everything is working correctly. So the problem is that parameters are not parsing on the prod.
What can be a reason? What server configuration settings are critical when framework parses URLs like:  http://site.com/api/users/1 ?

PS: my UrlManager config:
```php
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'class'=>'app\components\LangUrlManager',
            /*
             * REST api rules
             */
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'api/user',
                    'except' => [
                        'index',
                        'create',
                        'delete',
                    ],
                    'extraPatterns' => [
                        'POST login' => 'login',
                    ],
                ],
            ],
        ],
```

**Comment by fernandezekiel** [comment]
declare the `tokens` property of the UrlRule, something like this:
```php
'tokens' => ['{id}' => '<id:[\d-]+>']
```

**Comment by alexweb** [comment]
Hm. Yes, it helped. 
However it's strange that the URL works well on the dev server without tokens parameter. 
Do you know the reason? 
Is it possible to set ```php 'tokens' => ['{id}' => '<id:[\d-]+>'] ``` for all rest rules?

**Comment by fernandezekiel** [comment]
@alexweb  are you using the same Yii versions on both servers?

**Comment by alexweb** [comment]
Yes

**Comment by fernandezekiel** [comment]
can you check the `yii\rest\UrlRule` class file of the production server? does the token parameter contain any value?

also i can see that you are using a custom url manager

**Comment by alexweb** [comment]
There is nothing special in url manager. It doesn't change anything in parameters.
