### ISSUE TITLE
Behaviour magic get and set not working.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#10576]
I am creating a behaviour to easily create extra fields in my ActiveRecord when needed. I have some ActiveRecords where i have many extra fields to add like mentioned here: http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#selecting-extra-fields

So to avoid creating each extra fields manually in every ActiveRecord, i am trying to create a behavior to achieve this, but the __get and __set are not working.

```php
class MyBehavior extends Behavior
{
    private $_dynamicAttributes = [];

    public function __get($name)
    {
        try {
            return parent::__get($name);
        } catch (UnknownPropertyException $exception) {
            return $this->getDynamicAttribute($name);
        }
    }

    public function __set($name, $value)
    {
        try {
            parent::__set($name, $value);
        } catch (UnknownPropertyException $exception) {
            $this->setDynamicAttribute($name, $value);
        }
    }

    protected function getDynamicAttribute($name)
    {
        return ArrayHelper::getValue($this->_dynamicAttributes, $name);
    }

    protected function setDynamicAttribute($name, $value)
    {
        $this->_dynamicAttributes[$name] = $value;
    }
}
```

Here is my try on this. If i add a `die()` at the top of either the `__get()` or `__set()`, none of them triggers. But let's assume i am trying to get an attribute named '`average`', the `__get()` will trigger if i have  the function `getAverage()` defined in the behavior, else it will just throw `UnknownPropertyException` without triggering the `__get()` or `__set()` of the behavior.

**Comment by SilverFire** [comment]
Use PHP trait instead of behaviour.

Behaviour does not inject its own magic methods to the parent object. Yii only tries to run the missing method from behaviours ([source](https://github.com/yiisoft/yii2/blob/master/framework/base/Component.php#L280)).

**Comment by cebe** [comment]
@Locustv2 if you override `__get()` and `__set()` in the behavior you also have to override canGetProperty() and canSetProperty().

**Comment by cebe** [comment]
reopening this as a documentation issue. Should be mentioned on the properties guide.

**Comment by Locustv2** [comment]
@cebe ohh i see. Thanks, it's working great now. Let me have the link when it's ready.

**Comment by dynasource** [comment]
is this still open?

**Comment by samdark** [comment]
Yes. @cebe planned to document it.

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/b87999f6bb82b8b6e8cbfbcbf06eba263d02007a
