### ISSUE TITLE
component for ajax request

### ISSUE THREAD

**Issue by masiha68** [yiisoft/yii2#10570]
Hi
I use this component for checking ajax request

```php
<?php
 

namespace app\component;

use yii;
use yii\filters\VerbFilter;

class myAjaxAccess extends VerbFilter{

    public function beforeAction($event)
    {

         $action = $event->action->id;
        if (isset($this->actions[$action])) {
            $verbs = $this->actions[$action];
        } elseif (isset($this->actions['*'])) {
            $verbs = $this->actions['*'];
        } else {
            return $event->isValid;
        }
////check if action is ajax request=> allowed
         if(in_array('ajax',$verbs))
        {
            if (Yii::$app->request->isAjax) {
                return $event->isValid;
            }
            else
            {
                throw new yii\web\MethodNotAllowedHttpException('Method Not Allowed. This url can only handle the following request methods:AJAx ');

            }
        }

        return parent::beforeAction($event);


    }

} 
```

My problem is I can not use this class?

**Comment by SilverFire** [comment]
How do you use it? What do you expect?

Please notice, that GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

**Comment by masiha68** [comment]
'verbs'=>[
                    'class'=>myAjaxAccess::className(),
                    'actions'=>[
                        'index'=>['get'],

                        '*'=>['ajax'],
                    ]
                ]
i am not sure but i think it is a bug 
yii could not be found Ajax request

**Comment by SilverFire** [comment]
1. What happens when you access index page with plain GET? If the result does not match your expectations, describe them.
2. What do you get when you access index page with AJAX? If the result does not match your expectations, describe them.
3. What do you get when you access any other action with AJAX? If the result does not match your expectations, describe them.
4. What do you get when you access any other action with AJAX? If the result does not match your expectations, describe them.

**Comment by masiha68** [comment]
'verbs'=>[
                'class'=>VerbFilter::className(),
                'actions'=>[
                    'index'=>['get'],

                    '*'=>['ajax'],
                ]
            ]
when i have an ajax request ...
![stetup1](https://cloud.githubusercontent.com/assets/5849044/12323471/b3261f58-bad0-11e5-90a2-3a83cf87a698.JPG)

**Comment by SilverFire** [comment]
Please, post exact answers to my questions.
