### ISSUE TITLE
Duplicate an ActiveQuery?

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#10578]
Is it possible to clone an ActiveQuery object? I saw [Query::create()](http://www.yiiframework.com/doc-2.0/yii-db-query.html#create%28%29-detail) but which is not able to create a new ActiveQuery object, just a Query object.

If there is now way to duplicate an ActiveQuery object then this is a feature request. Otherwise sorry for my lack of knowledge!

**Comment by samdark** [comment]
`$queryCopy = clone $query`?

**Comment by robsch** [comment]
Ok, thank you. And what is the purpose of Query::create()? Why does a Query object not just get cloned?

**Comment by samdark** [comment]
It's used specifically to create query from active query in the process of preparing active query for QueryBuilder since it's not aware of active part at all.

**Comment by robsch** [comment]
Thanks again.
