### ISSUE TITLE
Is E_USER_ERROR  fatal error?

### ISSUE THREAD

**Issue by TheSaturn** [yiisoft/yii2#10577]
Hello! 
I created model with one little mistake. 
```
    public function rules()    {
        return [        ['text', 'max' => 100],     ];
        //instead of 
       // return [        ['text', 'string',  'max' => 100],     ];
    }
```
and I get no error because error type is E_USER_ERROR
The message of error:
```
  ["message"]=>
  string(1024) "Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Invalid validation rule: a rule must specify both attribute names and validator type.' 
```
Is it ok? Now I get only this html and nothing more.  I don't see the error
```
<div class="priem">
        <form id="w0" action="/" method="post">
<input type="hidden" name="_csrf" value="==">
```
if not, I can fix it.

**Comment by samdark** [comment]
How to reproduce it?

**Comment by samdark** [comment]
All unhandled exceptions/errors in Yii are stopping exection. It's expected.

**Comment by TheSaturn** [comment]
To reproduce:
1) create model:
```
<?php
namespace app\models;

use yii\base\Model;

class SomeForm extends Model
{
    public $text;

    public function rules()
    {
        return [
            ['text', 'max' => 1],
        ];
    }
}
```
2) action in controller:
```
public function actionSiteRecord()
    {
        $model = new SomeForm();
        return $this->render('record', ['model' => $model]);
    }
```
3)  record.php:
```
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model \app\models\SomeForm */
/* @var $form ActiveForm */
?>
<div class="priem">
        <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'text') ?>
        <?php ActiveForm::end(); ?>
</div>
```

**Comment by samdark** [comment]
What's YII_DEBUG value in your index.php?

**Comment by TheSaturn** [comment]
It is setted to development version. 
```
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```

**Comment by githubjeka** [comment]
Do you except  `['text', 'max' => 100],` equals `['text', 'string' 'max' => 100],` ?

**Comment by githubjeka** [comment]
![image](https://cloud.githubusercontent.com/assets/874234/12346630/27c0e5e6-bb67-11e5-8e0c-c60f4531c41a.png)

What's wrong?

**Comment by SilverFire** [comment]
Seems to be expected, as for me.

**Comment by TheSaturn** [comment]
githubjeka, do you run $model->validate in controller? I've got same error inside controller. We get yii\base\InvalidConfigEsception. But inside __toString() method of ActiveField that Exception catched and converted to E_USER_ERROR (due to __toString cannot throw exception) 
![image](https://cloud.githubusercontent.com/assets/10252514/12348580/68426b1c-bb8a-11e5-98d6-305c3e899d34.png)

**Comment by githubjeka** [comment]
I see.
What do you propose to do?

**Comment by TheSaturn** [comment]
Error slightly exit script due to this: https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L190 
My error_reporting is not E_ALL.
I think we need to rewrite function handleError for detecting __toString in backtrace or change "if" to
```
if (error_reporting() | E_USER_ERROR & $code)
```
or may be better to 
```
if (error_reporting() & $code || YII_DEBUG)
```
Or may be better to force error_reporting(E_ALL) in debug mode?
