### ISSUE TITLE
Using oracle native functions in query builder

### ISSUE THREAD

**Issue by faradoxuz** [yiisoft/yii2#10582]
Hi Guys,
this is not working, can you help me 
```
$command = (new \yii\db\Query())
                    ->select("SUBSTR(column_name,1,18)")
                    ->from("table_name")
                    ->all();
```
```
error is ORA-00907: missing right parenthesis;
```
but this works:
```
$command = \Yii::$app->db->createCommand(Select SUBSTR(column_name,1,18) from table_name )
                                                ->queryAll();
```
Help me with! Please

**Comment by githubjeka** [comment]
Use https://gitter.im/yiisoft/yii2 for your question.
And try to use [\yii\db\Expression](http://www.yiiframework.com/doc-2.0/yii-db-expression.html)

**Comment by SilverFire** [comment]
Please, show the executed SQL query.

Try \yii\db\Expression, as @githubjeka suggested.

```php
$command = (new \yii\db\Query())
                    ->select(new \yii\db\Expression("SUBSTR(column_name,1,18)"))
                    ->from("table_name")
                    ->all();
```

Please notice, that GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

**Comment by faradoxuz** [comment]
@githubjeka!
the same error

**Comment by SilverFire** [comment]
Please, show the executed SQL query.

**Comment by githubjeka** [comment]
@faradoxuz 
if the code doesn't work
```
$command = (new \yii\db\Query())
                    ->select(new \yii\db\Expression("SUBSTR(column_name,1,18)"))
                    ->from("table_name")
                    ->all();
```
then yii2 has problem.

I haven't oracle. Please explore for yourself and send PR ;)

**Comment by faradoxuz** [comment]
@SilverFire 
```
SQL being executed was: SELECT SUBSTR(T.NAME, \"1\", \"18)\" FROM \"TARIFFS\"
```

**Comment by SilverFire** [comment]
And what was the code, that generated such query?

**Comment by githubjeka** [comment]
```php
echo (new \yii\db\Query())
                    ->select("SUBSTR(column_name,1,18)")
                    ->from("table_name")
                    ->rawSql;
```

**Comment by faradoxuz** [comment]
>Четверг, 14 января 2016, 22:44 -08:00 от Dmitry Naumenko <notifications@github.com>:
>
>Please, show the executed SQL query.
>Try \yii\db\Expression, as  @githubjeka suggested.
>$command = (new \yii\db\Query())
>                    ->select(new \yii\db\Expression("SUBSTR(column_name,1,18)"))
>                    ->from("table_name")
>                    ->all();
>Please notice, that GitHub is for bug reports. We are happy to help you on  support forum or in gitter room  https://gitter.im/yiisoft/yii2 . It's always better to text there, unless you are sure it is a Yii2 core problem.
>—
>Reply to this email directly or  view it on GitHub .
Это вы который сделал видеоурок про codeigniter?

**Comment by faradoxuz** [comment]
@githubjeka , @SilverFire 
is there any solutions?

**Comment by githubjeka** [comment]
@faradoxuz Show me your code like as 
```
echo (new \yii\db\Query())
                    ->select("SUBSTR(column_name,1,18)")
                    ->from("table_name")
                    ->rawSql;
```

and his result

**Comment by faradoxuz** [comment]
undefined property rawSql

**Comment by githubjeka** [comment]
Sorry, corrected code is 
```
echo (new \yii\db\Query())
                    ->select("SUBSTR(column_name,1,18)")
                    ->from("table_name")
                    ->createCommand()
                    ->rawSql;
```

**Comment by faradoxuz** [comment]
```php
 $tariffs = (new \yii\db\Query())
                    ->select("SUBSTR(T.NAME,1,18)")
                    ->from("TARIFFS T")
                    ->createCommand(\Yii::$app->db_o)
                    ->rawSql;
```
result:
```sql
SELECT SUBSTR(T.NAME, \"1\", \"18)\" FROM \"TARIFFS\" \"T\" 
```

**Comment by githubjeka** [comment]
can you try ` ->select("SUBSTR(NAME,1,18)")`

**Comment by githubjeka** [comment]
Can you try ` ->select(new \yii\db\Expression('SUBSTR(T.NAME,1,18)'))`

**Comment by faradoxuz** [comment]
same error ((
```
SQLSTATE[HY000]: General error: 907 OCIStmtExecute: ORA-00907: missing right parenthesis\n The SQL being executed was: SELECT SUBSTR(T.NAME, \"1\", \"18)\" FROM \"TARIFFS\" \"T\"
```
but in this case:
```php
$tariffs = \Yii::$app->db_o->createCommand(
"SELECT SUBSTR(NAME,1,18) from TARIFFS"
 )->queryAll();
```
this code working

**Comment by githubjeka** [comment]
You don't run the my code. I expected

```sql
SELECT SUBSTR(NAME, \"1\", \"18)\" FROM \"TARIFFS\" \"T\"
```

instead your 

```sql
SELECT SUBSTR(T.NAME, \"1\", \"18)\" FROM \"TARIFFS\" \"T\"
```

**Comment by faradoxuz** [comment]
```error
SQLSTATE[HY000]: General error: 907 OCIStmtExecute: ORA-00907: missing right parenthesis\n The SQL being executed was: SELECT SUBSTR(NAME, \"1\", \"18)\" FROM \"TARIFFS\"
```

**Comment by githubjeka** [comment]
Dublicate https://github.com/yiisoft/yii2/issues/7994
