### ISSUE TITLE
className yii\base\Module bug

### ISSUE THREAD

**Issue by punkwang** [yiisoft/yii2#10587]
Yii2 2.0.5

className yii\base\Module

line 447 runAction function

```php
$parts = $this->createController($route);
if (is_array($parts)) {
    /* @var $controller Controller */
    list($controller, $actionID) = $parts;
    $oldController = Yii::$app->controller;
    Yii::$app->controller = $controller;
    $result = $controller->runAction($actionID, $params);
    Yii::$app->controller = $oldController; ////////////// If this "oldController" is NULL in the event of an individual will call controller or depend on the method submitted to the controller empty anomalies

    return $result;
} else {
    $id = $this->getUniqueId();
    throw new InvalidRouteException('Unable to resolve the request "' . ($id === '' ? $route : $id . '/' . $route) . '".');
}
```

Such as I am in the Response: : EVENT_AFTER_SEND call Url: : to would be an error!!!!!

**Comment by SilverFire** [comment]
Sorry, I didn't understand you.
Please, post steps to reproduce, the problem itself and the expected result.

**Comment by samdark** [comment]
Also try updating to 2.0.6 and check if the issue is gone.

**Comment by punkwang** [comment]
$response->on(Response::EVENT_AFTER_SEND,function($html){
$link=Url::to(['site/index']); // expected  "controller is null"
});

**Comment by punkwang** [comment]
yii\base\Module  line 447 runAction function

Yii::$app->controller = $oldController;  // $oldController may be is null

**Comment by SilverFire** [comment]
I still don't understand you, sorry :confused:
If someone got @punkwang idea - please, explain it in other words.

**Comment by kidol** [comment]
I had similar problem with PageCache. If you do

```$this->renderDynamic('echo Yii::$app->controller->id;');```

and enable PageCache, you'll get:

>Trying to get property of non-object

because PageCache listens for AFTER_SEND event (and at that point `Yii::$app->controller` was set back to `null` already).

However, after reload PageCache works as expected because `Yii::$app->controller` is available at the time when reading from cache :)

![err](https://cloud.githubusercontent.com/assets/440902/12357477/6564e4f6-bba8-11e5-8661-389876cae396.png)

**Comment by samdark** [comment]
@punkwang is what @kidol described the same issue?

**Comment by kidol** [comment]
OK the code snippet from @punkwang produces:

```php
$response->on(Response::EVENT_AFTER_SEND,function($html){
     $link=Url::to(['site/index']);
});
```

![err](https://cloud.githubusercontent.com/assets/440902/12358117/049b2262-bbac-11e5-9464-fa9f0ef3a3bb.png)

In my case I think I wanted to get `Yii::$app->controller->route` in `renderDynamic` + PageCache to generate dynamic advertising code.

**Comment by punkwang** [comment]
@samdark yes same issue!

**Comment by cebe** [comment]
A simple fix would be to use an absolute route by prepending a slash: `Url::to(['/site/index'])`.

**Comment by andrewnester** [comment]
what if instead this  https://github.com/yiisoft/yii2/blob/master/framework/base/Module.php#L455

we will use this code

```
            if ( $oldController !== null ) {
                Yii::$app->controller = $oldController;
            }
```

does it makes sense? will it impact on something?

**Comment by SilverFire** [comment]
I guess it will work, but I'm something can get broken. I'd rather do as @cebe suggested.

**Comment by lynicidn** [comment]
да, косяк там
try as temporary solve
Yii::$app->urlManager->createUrl(['/site/index']);

**Comment by undefinedor** [comment]
```php
//yii\base\Module
public function runAction($route, $params = [])
    {
        $parts = $this->createController($route);
        if (is_array($parts)) {
            /* @var $controller Controller */
            list($controller, $actionID) = $parts;
            $oldController = Yii::$app->controller; 
            Yii::$app->controller = $controller;
            $result = $controller->runAction($actionID, $params);
            Yii::$app->controller = $oldController;

            return $result;
        } else {
            $id = $this->getUniqueId();
            throw new InvalidRouteException('Unable to resolve the request "' . ($id === '' ? $route : $id . '/' . $route) . '".');
        }
    }
```
```
    $oldController = Yii::$app->controller; 
    Yii::$app->controller = $oldController;
```
what's the aims of the two statements?

**Comment by samdark** [comment]
Not to interfere with current web controller.
