### ISSUE TITLE
GridView initColumns:531 - Error array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by compleatguru** [yiisoft/yii2#10580]
I have a raw sql which return dataset having column name as integers.
The error was on initColumns()

```php
$column = Yii::createObject(array_merge([
                    'class' => $this->dataColumnClass ? : DataColumn::className(),
                    'grid' => $this,
                ], $column));
```

I got a fix by modifying at guessColumns()

```php
 foreach ($model as $name => $value) {
                if(ctype_digit($name) && is_int($name)){
                    $name = "$name";
                }
                $this->columns[] = $name;
            }
```

hope this is useful for others who have similar problem.
[GridView.txt](https://github.com/yiisoft/yii2/files/91260/GridView.txt)

**Comment by SilverFire** [comment]
Seems to be truth.
There is a check against string [source](https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L525), so `guessColumns()` should always cast the name to string.

I'll fix.
