### ISSUE TITLE
Make bower assets suggested packages instead of dependencies

### ISSUE THREAD

**Issue by bpicolo** [yiisoft/yii2#10591]
There's quite the pain point around the global bower requires stuff, and it's actively poor for people who simply don't want to use bower.'

It would be really cool to get rid of these as forced dependencies

**Comment by githubjeka** [comment]
Dublicate https://github.com/yiisoft/yii2/wiki/Ideas-for-2.1#client-side

**Comment by bpicolo** [comment]
Sure, that's fair.

"Require node.js" Is something I'll have the same complaint about though. ;)

**Comment by githubjeka** [comment]
Yii framework is php framework. Because js css depends should be removed. :hocho:
It would be cool if Ember.js save php code :pill:

**Comment by SilverFire** [comment]
Work on this problem is in process
