### ISSUE TITLE
BlameableBehavior not work in ConsoleApplication

### ISSUE THREAD

**Issue by maxyc** [yiisoft/yii2#10599]
if i use
```
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
```

and change manualy 
            $news->created_by = 1;
            $news->updated_by = 1;

result:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_by' cannot be null
The SQL being executed was: INSERT INTO `articles` (`city_id`, `company_id`, `name`, `note`, `text`, `active`, `created_by`, `updated_by`, `image`, `code`, `active_from`, `active_to`, `created_at`, `updated_at`) VALUES (2, NULL, 'Rerum molestiae id ut ut delectus.', '....

**Comment by maxyc** [comment]
даже если руками укажу на ид пользователя, он перезатирается бехевиором

**Comment by maxyc** [comment]
vendor/yiisoft/yii2/behaviors/BlameableBehavior.php:108
думаю ошибка где то тут

**Comment by SilverFire** [comment]
Пользователь залогинен?
Перед `$model->save()` сделайте 
```php
var_dump(Yii::$app->get('user', false));
```



> даже если руками укажу на ид пользователя, он перезатирается бехевиором

Это ожидаемое поведение

**Comment by maxyc** [comment]
а пользователя можно логинить в консоли? пойду доки читать )
прошу прощения за тупость )

**Comment by SilverFire** [comment]
Из коробки нельзя. Консоль не хранит сессий, как браузер :)
Можно сделать что-то в стиле `./yii do/something --user=maxys`

**Comment by manquer** [comment]
While a end user may not directly "login" using console, significant background jobs for async processing  use queues / cron etc, these actions has to be attributed to the user. There should be easier way than overriding the default value callable in every single table model.
