### ISSUE TITLE
Don`t correct AR use with field = Null

### ISSUE THREAD

**Issue by Mirocow** [yiisoft/yii2#10603]
* Database: Postgres 9.4
* PHP version: 5.6
* Yii 2.07 - dev

I used ytii2 last developed version, i repeat it on release version

that`s correct

```
        $items = BadOffer::find()->andFilterWhere(['OR',
                                                   ['moderator_id' => $user->id],
                                                   ['moderator_id', 3]
        ]);
```

but don`t work

```
        $items = BadOffer::find()->andFilterWhere(['OR',
                                                   ['moderator_id' => $user->id],
                                                   ['=', 'moderator_id', null]
        ]);
```

```
        $items = BadOffer::find()->andFilterWhere(['OR',
                                                   ['moderator_id' => $user->id],
                                                   ['moderator_id' => null]
        ])
```

but that`s correct

```
        $items = BadOffer::find()->andFilterWhere(['OR',
                                                   ['moderator_id' => (new Expression('Null'))],
                                                   ['moderator_id' => $user->id],
        ]);
```

**Comment by SilverFire** [comment]
I believe it's an expected behavior. @cebe ?

**Comment by cebe** [comment]
> ['moderator_id', 3]

This syntax is not supported, what should it do?

> ['=', 'moderator_id', null]

wrong usage, it will result in SQL `` `moderator_id` = NULL`` which is invalid HTML.

> ['moderator_id' => null]

This is correct and will be `` `moderator_id` IS NULL``



> ['moderator_id' => (new Expression('Null'))]

This works.

What exactly is the problem?

**Comment by SilverFire** [comment]
@Mirocow I'm closing the issue since you are inactive.
If you have something to add - feel free to post comments here.
