### ISSUE TITLE
Slug behavior can't auto generate

### ISSUE THREAD

**Issue by tuannda** [yiisoft/yii2#10606]
Hello, I config in model follow bellow

use yii\behaviors\SluggableBehavior;

      [
        'class' => SluggableBehavior::className(),
        'attribute' => ['title', 'slug'],
        'slugAttribute' => 'slug',
        'ensureUnique' => true,
        'immutable' => true
      ],

When i typing in field slug string: tiếng việt có dấu. I see in database field slug is tiếng việt có dấu.

I think it should is tieng-viet-co-dau.

Thank you!

**Comment by SilverFire** [comment]
It's weird to make `slug` dependant from `slug`. I'd suggest to change it to

```php
    'attribute' => 'title',
    'slugAttribute' => 'slug',
```

Then please show the following

**Comment by SilverFire** [comment]
Oh, wait a minute.

> When i typing in field slug string

You have `'immutable' => true` and you are filling slug manually. Current behavior is expected.
Fill `title`, leave `slug` untouched and all will work as expected.
