### ISSUE TITLE
Wrong default value when using MSSql database

### ISSUE THREAD

**Issue by alberdigital** [yiisoft/yii2#10604]
PHP version: 5.4.31
Yii2 version: 2.0.6
Database: mssql 11.0.2100 via ODBC
Driver name: sqlsrv

When our application loads the default values for columns of a database table in mssql into an ActiveRecord, and these default values are empty strings, the ActiveRecord gets "(\'\')" instead of an empty string.

It looks that the problem occurs in these piece of code:

File: /yiisoft/yii2/db/mssql/Schema.php
Method: loadColumnSchema()

```
if ($info['column_default'] == '(NULL)') {
    $info['column_default'] = null;
}

if (!$column->isPrimaryKey && ($column->type !== 'timestamp' || $info['column_default'] !== 'CURRENT_TIMESTAMP')) {
    $column->defaultValue = $column->phpTypecast($info['column_default']);
}

return $column;
```

This code checks the representation of a null value when getting the table schema, but not the representation of an empty string. We think it could be fixed by adding this check:

```
if ($info['column_default'] == '(\'\')') {
    $info['column_default'] = '';
}
```

**Comment by SilverFire** [comment]
Thank you for bug report and digging in. Would you like to submit a PR?

**Comment by andrewnester** [comment]
Does this PR solve this issue too? https://github.com/yiisoft/yii2/pull/9773

**Comment by SilverFire** [comment]
Not sure, need to test

**Comment by samdark** [comment]
Could be. It's quite big so hard to analyze and apply.

**Comment by samdark** [comment]
Also it has conflicts so not sure how to apply it.

**Comment by alexkart** [comment]
Fixed by https://github.com/yiisoft/yii2/pull/17420
