### ISSUE TITLE
Yii2 multiple model in a single action not work

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#10601]
I try 

```php
    public function actionCreate()
    {
    $human = new Human();
    $passport = new Passport;

    if ($human->load(Yii::$app->request->post()) && $passport->load(Yii::$app->request->post()) && Model::validateMultiple([$human, $passport]))
    {

        $human->save(false); // skip validation as model is already validated
        $passport->id = $human->passport_id; // no need for validation rule on user_id as you set it yourself
        $passport->save(false);

        return $this->redirect(['view', 'id' => $human->id]);
    }
    else
    {
        return $this->render('create', [
                    'human' => $human,
                    'passport' => $passport,
        ]);
    }

    /* if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->id]);
    } else {
        return $this->render('create', [
            'model' => $model,
        ]);
    }*/
}
```

and view

    <?php

    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use app\modules\proj\models\Passport;

    /* @var $this yii\web\View */
    /* @var $model app\modules\proj\models\Human */
    /* @var $form yii\widgets\ActiveForm */
    ?>

    <div class="human-form">

        <?php
        $form = ActiveForm::begin([
                    'id' => $human->isNewRecord ? 'human-form-create' : 'human-form-update',
        ]);
        ?>

        <?= $form->field($human, 'name')->textarea(['rows' => 6]) ?>

            <?= $form->field($human, 'passport_id')->textInput() ?>

        <div class="form-group">
        <?= Html::submitButton($human->isNewRecord ? 'Create' : 'Update', ['class' => $human->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

    <?php ActiveForm::end(); ?>

    </div>

Call to a member function formName() on a non-object

 var_dump($human) = NULL

**Comment by des1roer** [comment]
http://ru.stackoverflow.com/questions/483746/yii-2-%D1%84%D0%BE%D1%80%D0%BC%D0%B0-%D0%B8%D0%B7-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9

**Comment by SilverFire** [comment]
GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem. 

Therefore I'm closing the issue, however I will still answer here trying to help you.

Ensure that the view, where you're trying to access `$human` is the view, you are rendering.
Try to reproduce the problem on clean Yii2 installation.
Reduce the code to minimum required to reproducing.
