### ISSUE TITLE
DB connection pool

### ISSUE THREAD

**Issue by D1M** [yiisoft/yii2#10616]
In xdebug (on localhost) i see Opening DB connection: ~515.7 ms every time. I can't find any properties to define connection pool size or similar in config. I can define class, dsn, schemaCache and etc...

May be someone knows why yii2 Opening DB connection every time and spend ~500ms for that?

Thanks!

**Comment by samdark** [comment]
Because it's PHP. Every request it initializes everything and at the end of request destroys it.

**Comment by cebe** [comment]
> and spend ~500ms for that

that depends on your environment. usually opening db connection is done in much less time.

**Comment by DaSourcerer** [comment]
@D1M: That sounds very much like a DNS timeout. I'm assuming you're using MySQL: Try setting [`skip-name-resolve`](http://dev.mysql.com/doc/refman/5.5/en/server-options.html#option_mysqld_skip-name-resolve).

Yii 2 has no connection pooling as such. But you can achieve pretty much the same effect through adding [`PDO::ATTR_PERSISTENT`](http://php.net/manual/pdo.constants.php#pdo.constants.attr-persistent) to [`Connection.attributes`](http://www.yiiframework.com/doc-2.0/yii-db-connection.html#$attributes-detail). Be advised that this will enable stale transactions to persist through PHP request cycles, so be bloody careful! If you want to improve on that, enable the [MySQL thread cache](https://dev.mysql.com/doc/refman/5.5/en/connection-threads.html) and set the thread cache to the number of the expected concurrent connections.

@cebe is right in that opening database connections is usually a very cheap operation. Doesn't say there is no room for improvement :smirk:

**Comment by D1M** [comment]
Thanks for the comments!
Of course, i understand that php has troubles with connection pooling. 
My questing was - maybe today we have some solution for persistent connection or pooling out-of-the-yii2-box. 
And  yes, i read all articles regarding PDO attributes, but it will be helpfull to have such things OOTB.

P.S. e.g. hhvm + hack+ connection pooling (https://docs.hhvm.com/hack/reference/class/AsyncMysqlConnectionPool/) or similar solutions.

**Comment by DaSourcerer** [comment]
Well, if you're really looking for an OoTB solution, perhaps the [ms plugin](http://php.net/manual/en/intro.mysqlnd-ms.php) for the MySQLnd driver is what you are looking for?

**Comment by turowicz** [comment]
This creates a problem because opening a mysql connection over SSL is slow.

**Comment by cebe** [comment]
@turowicz usually DB is on a local network and connection is made without SSL, if you really need SSL connection, you have to live with the drawbacks. If possible creating an SSH tunnel instead of using SSL might be the better option. Anyway, this is nothing Yii can help you with, its a server configuration issue.

**Comment by turowicz** [comment]
I guess so @cebe
