### ISSUE TITLE
Undefined property: app\components\WebUser::$isGuest

### ISSUE THREAD

**Issue by tapshell** [yiisoft/yii2#10611]
The PHP version: `5.5.9`

`app/config/web.php`:
```php
'user' => [
            'class' => 'app\components\WebUser',
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
```

`app\components\WebUser.php`:
```php
<?php

namespace app\components;

use yii\web\User as YiiWebUser;

class WebUser extends YiiWebUser
{
    
    protected function afterLogin($identity, $cookieBased, $duration)
    {
        Test::test();
        parent::afterLogin($identity, $cookieBased, $duration);
    }

}
```

`app\components\Test.php`:
```php
<?php

namespace app\components;


class Test
{

    public static function test()
    {
        \Yii::$app->user->isGuest;
    }

}
```

1. A user login with `Yii::$app->user->login($this->getUser(), 3600*24*30)` 
2. Then expire the server session manually
3. In the next request, `Yii::$app->user->isGuest` will trigger the following methods `app\components\WebUser::renewAuthStatus()` -> `app\components\WebUser::loginByCookie()` -> `app\components\WebUser::afterLogin()` -> `app\components\Test::test()`

## This will cause the php notice:
```
PHP Notice – yii\base\ErrorException
Undefined property: app\components\WebUser::$isGuest
```
It seems that the `__get` magic method in the `yii\bae\Component` is not work here.

If you change code in `app\components\Test::test()` from ` \Yii::$app->user->isGuest` to ` \Yii::$app->user->getIsGuest()`, the code works good.

![2016-01-19 2 58 39](https://cloud.githubusercontent.com/assets/6316857/12411955/b57377f6-bebd-11e5-9ac5-f204461a2094.png)

**Comment by cebe** [comment]
afterLogin() may be called within a call to `__get()` on the WebUser class. Inside of such a call PHP does not support another request through `__get()`. You have to call the method explicitly: `\Yii::$app->user->getIsGuest();`.

**Comment by marcovtwout** [comment]
Similar clarification on this subject: https://github.com/asinfotrack/yii2-audittrail/issues/5#issuecomment-204246631
