### ISSUE TITLE
Adding Extra Quotes to Unique Field Rule with Gii Model Generation

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#10613]
I am having field called `sEmailAddress` in my table which is defined as unique key constraints. 

Now when I use Gii to generate model of that table it is wrapping extra quotes to field name to the rule. This happens for `unique` rule only. Field Name is fine with other rules. 

```php
public function rules()
{
	return [
		[['sUserName', 'sEmailAddress'], 'required'],
        [['sEmailAddress', 'sPasswordHash', 'sPasswordResetToken'], 'string', 'max' => 255],
        [['"sEmailAddress"'], 'unique']
    ];
}

```

You can note extra quote in third rule which is generated for uniqueness.

Here are the setup details:

Yii Version: 2.0.6
Environment : dev
Debug Mode : Yes
DB: PostgreSQL 9.4

**Comment by samdark** [comment]
Could you provide SQL to create the table you're generating model for?

**Comment by avinashz** [comment]
Here it goes

```sql
CREATE TABLE user
(
  "nUserID" serial NOT NULL, -- Primary key for User.
  "nCreatorID" integer,
  "sUserName" character varying(64) NOT NULL, -- Unique user name for system
  "sEmailAddress" character varying(255) NOT NULL, -- Unique email address
  "sFirstName" character varying(64) NOT NULL,
  "sLastName" character varying(64) DEFAULT NULL::character varying,
  "sAuthKey" character varying(32) NOT NULL,
  "sPasswordHash" character varying(255) NOT NULL, -- Hased password for User
  "sPasswordResetToken" character varying(255) DEFAULT NULL::character varying, -- Hashed Token to reset Password
  "nUserType" smallint DEFAULT 3, 
  "nRoleID" integer, 
  "nStatus" smallint DEFAULT 0, -- 0=Inactive, 1= Active
  "sIPAddress" character varying(16) NOT NULL, -- IP Address from where User was registerred
  "dDateAdded" timestamp without time zone NOT NULL, -- Date when User added
  "dDateModified" timestamp without time zone, -- Date when User Modified
  "bDeleted" boolean DEFAULT false, -- 0= Not Deleted, 1 = Deleted
  "dDateDeleted" timestamp without time zone, -- Date when user Deleted
  CONSTRAINT "nUserID" PRIMARY KEY ("nUserID"),
  CONSTRAINT "sEmailAddress" UNIQUE ("sEmailAddress")
)
WITH (
  OIDS=FALSE
);
ALTER TABLE user
  OWNER TO postgres;
COMMENT ON TABLE user
  IS 'User details of system';
COMMENT ON COLUMN user."nUserID" IS 'Primary key for User.';
COMMENT ON COLUMN user."sUserName" IS 'Unique user name for system';
COMMENT ON COLUMN user."sEmailAddress" IS 'Unique email address';
COMMENT ON COLUMN user."sPasswordHash" IS 'Hased password for User';
COMMENT ON COLUMN user."sPasswordResetToken" IS 'Hashed Token to reset Password';
COMMENT ON COLUMN user."nStatus" IS '0=Inactive, 1= Active';
COMMENT ON COLUMN user."sIPAddress" IS 'IP Address from where User was registerred';
COMMENT ON COLUMN user."dDateAdded" IS 'Date when User added';
COMMENT ON COLUMN user."dDateModified" IS 'Date when User Modified';
COMMENT ON COLUMN user."bDeleted" IS '0= Not Deleted, 1 = Deleted';
COMMENT ON COLUMN user."dDateDeleted" IS 'Date when user Deleted';

```

**Comment by avinashz** [comment]
This is what I have got when I have done `var_dump($uniqueIndexes); die;` in model generator. We can see extra quote from there itself.

```php
array (size=1)
  'sEmailAddress' => 
    array (size=1)
      0 => string '"sEmailAddress"' (length=15)
```

Looks like we are getting extra quoted information from `getUniqueIndexInformation` method of `/vendor/yiisoft/yii2/db/pgsql/Schema.php`

**Comment by samdark** [comment]
It could be so. We'll look into it for 2.0.8 but if you'll find solution before us, let us know.

**Comment by avinashz** [comment]
Sure

**Comment by avinashz** [comment]
@samdark I am not expert at PostgreSQL, but do you know if because of its behavior of converting fields to lower case its returning column name like this?

**Comment by samdark** [comment]
I have no idea.

**Comment by chitwarnold** [comment]
@avinashz i would propose you install an extension of gii called "enhanced-gii" it works like a charm with PostgreSQL(PG). It has most if not all the rings and bells you will require to navigate the monster features of PG like schemas and the likes. 

I am using uuid's natively autogenerated by the PG after installing a uuid extension on the server works fine except on deleting related documents where i regret to announce that i feel f*d so if you can help me with the deleting part i will appreciated below is the Address to by Issue

https://github.com/yiisoft/yii2/issues/10773

**Comment by cebe** [comment]
Created a test case with a lowercase column name, which is working fine. As soon as one letter in the name becomes upper case, the issues occurs.

**Comment by cebe** [comment]
fixed, thanks for reporting!
