### ISSUE TITLE
Differences beetwen ActiveRecord::findAll($condition) and ActiveRecord::find()->where($condition)->all(). 

### ISSUE THREAD

**Issue by nplander** [yiisoft/yii2#10615]
<code>var_dump(News::findAll(['LIKE', 'title', 'заголовок'])); // array(0) { } </code>
<code>var_dump(News::find()->where(['LIKE', 'title', 'заголовок'])->all()); // array(6) { ... }</code>
<code>var_dump(News::findAll(['>', 'id', 5])); // array(1) { ... }</code>
<code>var_dump(News::find()->where(['>', 'id', 5])->all()); // array (13) { ... }</code>
Why?

**Comment by cebe** [comment]
Because that's what the docs say:

> Returns a list of active record models that match the specified primary key value(s) or a set of column values.
http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findAll%28%29-detail
