### ISSUE TITLE
Getting two db queries while page cache checking for unknown reason

### ISSUE THREAD

**Issue by radiocity** [yiisoft/yii2#10623]
```php
class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\filters\PageCache',
                'only' => ['news'],
                'duration' => 0,
                'dependency' => [
                    'class' => 'yii\caching\DbDependency',
                    'sql' => 'SELECT updated FROM {{%news}} ORDER BY updated DESC LIMIT 1',
                ],
                'variations' => [
                    //Yii::$app->request->get('category'),
                    //Yii::$app->request->get('id')
                ]
            ],
        ];
    }
    public function actionNews($category = false, $id = false)
    {
        $test = 'ehlo';
        return $test; // same with echo or var_dump
    }
}
```
And getting following queries in mysql log:
```mysql
38 Connect	root@localhost on localhost
38 Query	SET NAMES 'utf8'
38 Query	SELECT updated FROM `news` ORDER BY updated DESC LIMIT 1
38 Query	SELECT updated FROM `news` ORDER BY updated DESC LIMIT 1
```
Why this heppens?
PS If return instruction commented, only one query appears. 

> Следующий код  делает два запроса к базе на проверку полностраничного кеширования при наличии возвращаемого значения в экшене News. Почему? Как этого избежать?
> Если убрать инструкцию return, то делается только один запрос.

**Comment by SilverFire** [comment]
Please, show a stacktrace, that leads to a second SQL query.

**Comment by radiocity** [comment]
Sorry, but I dont know, how to make a stacktrace, so here information from debug log
```
1	12:55:09.781	trace	yii\base\Application::bootstrap	Bootstrap with yii\log\Dispatcher
2	12:55:09.781	trace	yii\base\Module::getModule	Loading module: debug
3	12:55:09.794	trace	yii\base\Application::bootstrap	Bootstrap with yii\debug\Module::bootstrap()
4	12:55:09.802	trace	yii\base\Module::getModule	Loading module: gii
5	12:55:09.803	trace	yii\base\Application::bootstrap	Bootstrap with yii\gii\Module::bootstrap()
6	12:55:09.808	trace	yii\web\UrlRule::parseRequest	Request parsed with URL rule: /news/
7	12:55:09.808	trace	yii\web\Application::handleRequest	Route requested: 'site/news'
8	12:55:09.812	trace	yii\base\Controller::runAction	Route to run: site/news
9	12:55:09.830	info	yii\db\Command::query	SELECT updated FROM `news` ORDER BY updated DESC LIMIT 1
C:\OpenServer\domains\localhost\controllers\SiteController.php (75)
10	12:55:09.831	info	yii\db\Connection::open	Opening DB connection: mysql:host=localhost;dbname=localhost
C:\OpenServer\domains\localhost\controllers\SiteController.php (75)
11	12:55:10.836	info	yii\db\Command::query	SELECT updated FROM `news` ORDER BY updated DESC LIMIT 1
C:\OpenServer\domains\localhost\controllers\SiteController.php (75)
```

**Comment by SilverFire** [comment]
I guess the first query was not executed indeed.

Let's take a look at [Command::queryInternal()](https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L806)

On [Line 810](https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L810) you are getting the first info, than the method tries to get query result from cache, it fails to do that and goes down and executes the query indeed.

**Comment by radiocity** [comment]
> You don't have an info about success saving to cache. Do you have correctly configured cache?

I guess it is configuried, coz it works
```php
'cache' => [
    'class' => 'yii\caching\FileCache',
],
```

**Comment by anestor-sugar** [comment]
@radiocity do you have some data in `news` table?

**Comment by andrewnester** [comment]
@radiocity do you have some data in news table?

**Comment by radiocity** [comment]
Yep. There was data inside table

**Comment by andrewnester** [comment]
I found out what the problem is.
`Cache::get` called 2 times.

1) First one https://github.com/yiisoft/yii2/blob/master/framework/widgets/FragmentCache.php#L140 called from `FragmentCache::init()`
2) Second one https://github.com/yiisoft/yii2/blob/master/framework/filters/PageCache.php#L169 called from 'beforeAction'

`Cache::get` checks for dependency each time it's called.
But `Dependency` has an attribute called `$reusable`. You can set it to true for you PageCache dependency and it will work fine.

Note: don't forget to clear your cache after you set this option to true

**Comment by radiocity** [comment]
> But Dependency has an attribute called $reusable. You can set it to true for you PageCache dependency and it will work fine

Thank you. Solution works great
