### ISSUE TITLE
Error 400 - Reason and How to resolve this problem?

### ISSUE THREAD

**Issue by tuannda** [yiisoft/yii2#10621]
I seen notified Yii2 return error 400. But I don't know reason. and How to resolve it.

Envionment:

1. Varnish cache -> Nginx -> HHVM + MySQL -> Yii2
2. Xampp -> Yii2

-----php init with Development env----

When using action create or update -> Yii2 return error 400.

Thank you!
YiiVN

**Comment by tuannda** [comment]
Sometimes not always

**Comment by yxdj** [comment]
You can show some code,,,
csrf ?it will work on request by post

**Comment by andrewnester** [comment]
mostly likely your forgot to include CSRF token when you send POST request for create or update

**Comment by SilverFire** [comment]
GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.
