### ISSUE TITLE
Controller class/file name suggestion

### ISSUE THREAD

**Issue by iddqdidkfa** [yiisoft/yii2#10620]
Why each controller should have `Controller` in class name and file name? Its already in namespace and directory structure is clear enough to understand that this class is a controller.

Lets do (in next major release?)
```php
<?php

namespace frontend\controllers;

use yii\web\Controller;

class Users extends Controller
```

instead of
```php
<?php

namespace frontend\controllers;

use yii\web\Controller;

class UsersController extends Controller

```

directory structure:
- frontend
    - controllers
        - Users.php
    - models
        - Users.php
    - views
        - users
            - view.php

. . .

**Comment by Alex-Code** [comment]
Taking your example above wouldn't you then need to alias the `Users` model class so it doesn't conflict with the `Users` controller class.

**Comment by klimov-paul** [comment]
Duplciates #260

**Comment by iddqdidkfa** [comment]
@Alex-Code actually I prefer to use `User` for models not `Users`. I can also use full namespace `\frontend\models\Users::className()` or as you said I can use alias.

**Comment by githubjeka** [comment]
https://github.com/yiisoft/yii2/issues/2709
