### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by bohdan-vorona** [yiisoft/yii2#10627]
``There is also a PDF version of the Definitive Guide and a Definitive Guide Mirror which is updated every 15 minutes.``

The link to PDF doesn't work. The requested URL /yii2-guide.pdf was not found on this server.

**Comment by samdark** [comment]
Which page are you talking about?

**Comment by bohdan-vorona** [comment]
@samdark , this one https://github.com/yiisoft/yii2.

**Comment by SilverFire** [comment]
Fixed https://github.com/yiisoft/yii2/commit/50deb075c85e5cca2d285302c7d7d9210233af85

**Comment by SilverFire** [comment]
Thank you for the report
