### ISSUE TITLE
BaseStringHelper::truncateHtml adds suffix regardless of the string length

### ISSUE THREAD

**Issue by mattheobjornson** [yiisoft/yii2#10629]
Hi,

I am using StringHelper::truncateWords (Yii2 v2.0.6) and found out that $suffix always gets added to returned string if $asHtml is set to true, regardless of fact that the string was not actually truncated. This differs from the behaviour of the same function when $asHtml is set to false. 
I would expect it to behave consistently and return the same string if it was not truncated (either with suffix, or without).
```php
$str='lorem ipsum';

StringHelper::truncateWords($str, 3, '...', true);
// returns "lorem ipsum..."

StringHelper::truncateWords($str, 3, '...', false)
// returns "lorem ipsum"
```
For now I have overridden BaseStringHelper::truncateHtml(...)
```php
return $generator->generateFromTokens($truncated) . $suffix;
```
to
```php
return $generator->generateFromTokens($truncated) . ($totalCount >= $count ? $suffix : '');
```
which seems to do the job.
Maybe should be considered in upstream.

**Comment by andrewnester** [comment]
Hi @mattheobjornson 
I've created PR with fix provided by you. Thanks!
