### ISSUE TITLE
Captcha always returns incorrect code on a fresh installation.

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2#10636]
Captcha on the contact page in basic template always returns "Validation code is incorrect" on the latest 2.0.6 stable release fresh installation

**Comment by cebe** [comment]
unable to reproduce. make sure your session storage works correctly and check the PHP error logs as well as the Yii logs. Also verify that cookies are accepted by your browser.

**Comment by evil1** [comment]
My fault, the problem trully was related to sessions. Nginx didn't have a write access to sessions temp folder.
