### ISSUE TITLE
Move createValidators from yii\base\Model into yii\validators\Validator

### ISSUE THREAD

**Issue by t-kanstantsin** [yiisoft/yii2#10630]
I suggest to move functionalitiy of method `createValidaotors` into `yii\validators\Validator`. Suggest to place it beside `createValidator` and rename to `createValidators` (or `createValidatorArray`).
It will allow reuse method functionality outside of model. E.g. add set of validators in rules-like way without need to manually create those validators.

New method signature in yii\validators\Validator:

``` php
    /**
     * @param \yii\base\Model $model the data model to be validated.
     * @param array $rules
     * @see Model::rules()
     */
    public function createValidators($model, array $rules)
```

Method createValidators in yii\base\Model class:

``` php
    public function createValidators()
    {
        return Validator::createValidators($this, $this->rules());
    }
```

**Comment by SilverFire** [comment]
Could you explain the example of a use case in details?

**Comment by t-kanstantsin** [comment]
Sure. 
I have product with lot of parameter. They are dynamically added and must be validated according it's own type. I must validate this parameters, but they have different types (boolean, int, date, one of select and some other). Sometimes it can be more than one validator (for example parameter named 'description' would have filter to spitp dangerous tags and check length). 
So this product parameters have common validation (e.g. for name), but value (or choice) validated in separated special class with config for each type. E.g.
```php
[
    Type::BOOLEAN => [['value'], 'boolean'],
    Type::INT => [['value'], 'integer'],
],
```
I don't want to create all validators for all type at the same time, so I must copy-paste code from `yii\base\Model::createValidators()` to create and attach only needed validators.

**Comment by SilverFire** [comment]
> They are dynamically added

So product is instance of `DynamicModel`?

**Comment by dapatrese** [comment]
We had a similar discussion about attaching validators dynamically via behaviors: #5438
Found a workaround there, but that was some time ago. So it might need some adjustments today.
Maybe it helps.

**Comment by t-kanstantsin** [comment]
@SilverFire not so. Product is instance of `Product`. But it has only few onw fields. Other fields added with models `Parameter` and `ProductToParameter`. And I must validate those parameter basing on their types.
I can have a lot of parameter types so I don't want describe them all in rules block with specifying `when` attribute - in this case, it would be so awkward.

**Comment by samdark** [comment]
Sounds interesting overall.
