### ISSUE TITLE
login to a website when login other one in the same server

### ISSUE THREAD

**Issue by m-wardany** [yiisoft/yii2#10634]
I have two projects yii2 advanced template , only backend login needed
when I log into one of them the other one automatically login , same with logout . after logout from one of them it logout from the other one too ,
this is not happening in my local machine , only on live server
main-local was generated via composer with unique  cookieValidationKey

**Comment by githubjeka** [comment]
from Session.php
```
 /**
     * @var string a string prefixed to every cache key so that it is unique. If not set,
     * it will use a prefix generated from [[Application::id]]. You may set this property to be an empty string
     * if you don't want to use key prefix. It is recommended that you explicitly set this property to some
     * static value if the cached data needs to be shared among multiple applications.
     */
    public $keyPrefix;
```

try to change `Application::id`

**Comment by samdark** [comment]
Are both frontend and backend on the same domain?

**Comment by m-wardany** [comment]
yes 
but no login in the frontend for both websites

**Comment by m-wardany** [comment]
@githubjeka 
didn't work

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2-app-advanced/issues/110
