### ISSUE TITLE
Nav not rendered correct

### ISSUE THREAD

**Issue by unNene** [yiisoft/yii2#10648]
Hi,

I'm using Nav widget from yii2.

My NavBar is not rendered correct, please the class name how is displayed in this screenshot:
![image](https://cloud.githubusercontent.com/assets/900974/12535656/a90b9a74-c292-11e5-9471-41e69eae36bd.png)

I'm using default NavBar code from yii2 basic app.

Maybe I need to install something to server or where I can find my problem ? ( In browser console  don't have any errors ).

**Comment by unNene** [comment]
I found problem, this was in file BaseHtml.php

Now I cloned BaseHtml.php from this source and is working fine:
https://raw.githubusercontent.com/yiisoft/yii2/master/framework/helpers/BaseHtml.php

Function: addCssClass()

Problem come from this post: https://github.com/yiisoft/yii2/issues/10092

**Comment by SilverFire** [comment]
How to reproduce it?

**Comment by unNene** [comment]
In old version of BaseHtml.php, function addCssClass() has a bug, it's a problem with Array to String conversion.

Now I see that problem was fixed.
