### ISSUE TITLE
 Полное отключение assets в консоли, для генерации чистого html

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#10640]
1) Имеем консольное приложение, внутри которого происходят некоторые действия.
Эти действия вызывают рендеринг виджетов и отправляют данные по вебсокету.
Соответственно, в некоторый момент времени, происходит ошибка с ассетами. Это логично т.к. консоль не имеет вывода.

2) Отключаем ассеты в файле конфигурации: 'assetManager' => ['bundles' => FALSE].
Вроде бы ассеты перестали создаваться, но менеджер все равно выполняет проверку до их подключения требуя наличия папки assets. И вот это не правильно: если нет банделсов, значит и папка не нужна!
 
3) Однако сделать так: 'assetManager' =>false  мы не можем. Это было бы огромным плюсом да и правильно, с точки зрения консольного приложения. А понадобиться это может для генерации чистого Html или Widget и отдачи его по вебсокету.

**Comment by samdark** [comment]
Да, действительно не очень логично создавать директорию в данном случае. Если знаете, как именно решить, может сделаете pull request?

**Comment by exru** [comment]
ок!

**Comment by exru** [comment]
@samdark примите пулл?

**Comment by SilverFire** [comment]
@exru а где он?

**Comment by githubjeka** [comment]
примите факс :)

**Comment by SilverFire** [comment]
@exru похоже, вы открыли PR внутри своего форка

**Comment by githubjeka** [comment]
В coreComponents от `\yii\console\Application` нет assetManager. 

Поэтому PR не логичный
```php
public static function register($view)
    {
         if (\Yii::$app instanceof \yii\web\Application){
            return $view->registerAssetBundle(get_called_class());
        }
    }
```

Это должно быть решено по другому.

**Comment by githubjeka** [comment]
Проблема тут просто в проверки существования папки, вот эту проверку и надо отключить в нужный момент.

**Comment by exru** [comment]
@githubjeka хоть один весомый аргумент, за то что нужно делать кучу лишних операций помимо проверки на то, что папка есть?

**Comment by exru** [comment]
P.S. Не собираюсь из-за 2 строчек кода разводить демагогию. Задача тривиальная - решил тривиально. Знаете как сделать проще и быстрее: наслаждайтесь. Говорю это абсолютно лояльно без единой нотки сарказма или негатива.

**Comment by SilverFire** [comment]
@exru сделайте для начала PR в правильную сторону, а там уже и продолжим обсуждение.

**Comment by samdark** [comment]
Перепроверил. `basePath` используется не только для бандлов, но для `publish()`. Не использование бандлов не гарантирует отсутствие ручной публикации.
