### ISSUE TITLE
Expression not binding params

### ISSUE THREAD

**Issue by jpodpro** [yiisoft/yii2#10647]
i have tried everything to bind parameters to an expression and they never do. the following code does NOT bind the user field - it leaves the query looking for ':user'.

```PHP
$exp = new \yii\db\Expression( "SELECT * FROM user WHERE username = ':user'", [':user' => 'admin'] );
```

according to the documentation parameter binding is supported by expressions - so how are they supposed to work? everywhere else they work properly using the above syntax. here they do not. am i missing something?

**Comment by SilverFire** [comment]
Where did you find such an example?
Please, check out the DAO goude page: http://www.yiiframework.com/doc-2.0/guide-db-dao.html#binding-parameters

**Comment by jpodpro** [comment]
it's all over the Expression documentation page:

http://www.yiiframework.com/doc-2.0/yii-db-expression.html

"$params: public property
List of parameters that should be bound for this expression. The keys are placeholders appearing in $expression and the values are the corresponding parameter values."

**Comment by SilverFire** [comment]
So you wright something like

```php
$exp = new \yii\db\Expression( "SELECT * FROM user WHERE username = ':user'", [':user' => 'admin'] );

$result = Yii::$app->db->createCommand($exp)->queryAll();
```

But `:user` does not become `admin`?

**Comment by jpodpro** [comment]
i just did exactly that in my debugger. $result is empty and $exp->expression does not change ':user' to 'admin'

**Comment by cebe** [comment]
\yii\db\Expression is meant to be used in *parts* of an SQL query. it is not meant to contain the whole query itself.

This will work:

```php
$exp = "SELECT * FROM user WHERE username = ':user'";
$params =  [':user' => 'admin'];

$result = Yii::$app->db->createCommand($exp, $params)->queryAll();
```

**Comment by jpodpro** [comment]
please consider updating the documentation for Expression as i find it misleading.

**Comment by terabytesoftw** [comment]
> would be cool tough that we can have different query expressions with its own parameters and as soon it's used i can merge and bind such variables.

You can open an issue, and give a clear example, this problem is closed, thank you.
