### ISSUE TITLE
About the AutoValidation

### ISSUE THREAD

**Issue by cevin** [yiisoft/yii2#10644]
```php
# Controller
$rules['title'] = [
    [
        'required',
        'opts' => [
            'message' => 'Title is required',
        ]
    ]
];

$rules['note'] = [
    [
        'required',
        'opts' => [
            'message' => 'Note is required',
        ]
    ]
];


$model = new \yii\base\DynamicModel(array_keys($rules));
foreach ($rules as $field => $rule) {
    foreach ($rule as $item) {
        $model->addRule($field, $item[0], $item['opts']);
    }
}
```

```php
<?php echo $form->field($model,'title')->textInput()->hint('Please enter title'); ?>
<?php echo $form->field($model,'note')->textarea(); ?>
```

The field `title` is missed with validation but field `note` is worked ...   Why...

Ps: javascript validation fail. server validation is successfully.

**Comment by SilverFire** [comment]
Failed to reproduce.

Could you show the code, that performs validation, values of the fields before the validation, the expected and the actual result?

**Comment by SilverFire** [comment]
![screenshot 2016-01-23 001](https://cloud.githubusercontent.com/assets/4499203/12530751/8624cf9a-c1f1-11e5-84e7-11816e862b1d.png)

**Comment by cevin** [comment]
@SilverFire 

Service validate is worked. But in browser, javascript validate is not worked(Field: title)

**Comment by SilverFire** [comment]
Also works

![screenshot 2016-01-23 002](https://cloud.githubusercontent.com/assets/4499203/12530853/b7d7e362-c1f4-11e5-850c-720c8c122eeb.png)

**Comment by cevin** [comment]
![default](https://cloud.githubusercontent.com/assets/338110/12530904/839a6230-c228-11e5-8fb0-483dd06d44d7.PNG)

wtf...

**Comment by cevin** [comment]
Yii: 2.0.6
PHP: 7.0.2
Platform:windows 10

**Comment by SilverFire** [comment]
If you have a way to reproduce it - please, post it and we will check it
