### ISSUE TITLE
Issue when trying to set default value for drop down list

### ISSUE THREAD

**Issue by oraluben** [yiisoft/yii2#10655]
view code is
```php
<?= $form->field($model, 'educational_level')->dropDownList(User::EDUCATIONAL_LEVEL,
                ['options' => [User::DEFAULT_EDUCATIONAL_LEVEL => ['selected' => true]]]) ?>
```
I found that my parameter options was overrode in
<code>\yii\helpers\BaseHtml::renderSelectOptions</code>
by<code>$attrs['selected'] = $selection !=== ...</code>, and<code>$selection</code> was computed in
<code>\yii\helpers\BaseHtml::activeListInput</code>
<code>$selection = static::getAttributeValue($model, $attribute)</code>
So I wander if I was doing this in wrong way, or it is a bug.

**Comment by samdark** [comment]
It's expected since you're using active form. It takes selected value from the model.
