### ISSUE TITLE
HttpBearerAuth is broken under FPM/FastCGI - Request class issue.

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii2#10650]
Running PHP 7.0.2 under FPM/FastCGI the Authorization header does not get passed from web server to PHP thus when in the HttpBearerAuth you check for the Authorization presence it won't be found thus no auth can be made.

This is not really an issue with HttpBearerAuth but with the Request class itself because it should do more work to detect the headers on various environments.   
In order to fix this issue, i had to subclass the Request class as: 
```php
<?php

namespace app\yii\web;

use \yii\web\Request as BaseRequest;

class Request extends BaseRequest
{
    /**
     * Returns the header collection.
     * The header collection contains incoming HTTP headers.
     * @return HeaderCollection the header collection
     */
    public function getHeaders()
    {
        $headers = parent::getHeaders();
        
        static $map = ['Authorization' => 'REDIRECT_HTTP_AUTHORIZATION'];
        if ($map !== null) {
            foreach ($map as $k => $v) {
                if (!$headers->get($k) && isset($_SERVER[$v])) {
                    $headers->set($k, $_SERVER[$v]);
                }
            }  
            $map = null;
        }
        
        return $headers;
    }
}
```

And then make sure apache/.htaccess contains:
```
# if no mod rewrite, use below:
# SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

# if mod rewrite: 
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteBase /    
    
    # add missing auth header under FPM/FastCGI
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
</IfModule>
```

Is there any chance to have this properly fixed in the core?

**Comment by samdark** [comment]
It doesn't look like a proper fix but rather a fix that's specific to your server config. Are you sure it applies to every setup using nginx?

**Comment by twisted1919** [comment]
@samdark in addition to above, `Request::getAuthUser` and `Request::getAuthPassword` are also problematic, i.e: HttpBasicAuth filter is broken. With the above fix into .htaccess and below code, the issue is fixed and HttpBasicAuth works again.

```php
    /**
     * @return string the username sent via HTTP authentication, null if the username is not given
     */
    public function getAuthUser()
    {
        if ($authUser = parent::getAuthUser()) {
            return $authUser;
        }
        
        $key = 'REDIRECT_HTTP_AUTHORIZATION';
        if (isset($_SERVER[$key]) && stripos($_SERVER[$key], 'basic ') === 0) {
            if (($info = base64_decode(substr($_SERVER[$key], 6))) && strpos($info, ':') !== false) {
                return explode(':', $info)[0];
            }
        }
        
        return null;
    }
    /**
     * @return string the password sent via HTTP authentication, null if the password is not given
     */
    public function getAuthPassword()
    {
        if ($authPass = parent::getAuthPassword()) {
            return $authPass;
        }

        $key = 'REDIRECT_HTTP_AUTHORIZATION';
        if (isset($_SERVER[$key]) && stripos($_SERVER[$key], 'basic ') === 0) {
            if (($info = base64_decode(substr($_SERVER[$key], 6))) && strpos($info, ':') !== false) {
                return explode(':', $info)[1];
            }
        }

        return null;
    }
```

**Comment by twisted1919** [comment]
@samdark - I don't think it's a fix specific to my configuration alone, it's just how things when under FPM/FastCGI and when you have nginx/apache combo. 

I lost few hours trying to figure this issue out, google doesn't help that much but there are users complaining about some headers not being properly passed to PHP in certain environments(FPM/FastCGI).

The above code can be written framework specific, and it doesn't add any extra overhead to what is already there since it first looks for the most common things and just if it does not find them it starts digging more. 

Also, i believe a solid note about this issue should be placed in the documentation (together with the .htaccess example) .

Thanks.

**Comment by samdark** [comment]
The case when nginx is used as a proxy to apache introduces tons of issues when environment vars and headers are modified to be non-standard. The bad thing is that it depends very much of how these variables are passed so there's no fix that would work for all possible configs. The good thing is that most of these could be configued to match non-proxied environment.

**Comment by twisted1919** [comment]
@samdark - gotcha, somehow makes sense. Basically for these special use cases, subclassing the request class and add our logic makes more sense. 
If that's all i guess this can be closed, just keep in mind that with php7 you'll see more of these environments than you'd expect :)
