### ISSUE TITLE
yii\web\ErrorHandler doesn't take \Error class (php >=7) into consideration

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii2#10657]
This related to http://www.yiiframework.com/forum/index.php/topic/69432-debug-while-creating-rest-services/

Basically, the current error handler does not take into consideration the new \Error class introduced in php 7 thus leading to all sorts of weird behavior. The linked article also contain a fix for the issue.

Reference: http://php.net/manual/en/class.error.php

**Comment by twisted1919** [comment]
Also, in same context, throwing a yii\db\IntegrityException is useless as it cannot be catched.
so adding an extra ` && !$exception instanceof \Exception` to the if statement makes it work again.

This is really serious issue, why is it labeled for 2.0.8 when it will render 2.0.7 useless for rest services?

**Comment by cebe** [comment]
why can't yii\db\IntegrityException be caught? As far as I see the only problem is, that PHP errors that have been converted to Exceptions by the language itself are not handled properly...

**Comment by twisted1919** [comment]
Have no idea about why yii\db\IntegrityException isn't caught, i did a get_class($exception) right inside the \yii'web\Errorhandler::convertExceptionToArray() and that's what it yelled, yii\db\IntegrityException.
Then adding that to the if statement made it work:
```php
protected function convertExceptionToArray($exception)
    {
        if (!YII_DEBUG && !$exception instanceof UserException && 
            !$exception instanceof HttpException && 
            !$exception instanceof \Error && 
            !$exception instanceof \Exception) {
            $exception = new HttpException(500, 'There was an error at the server.');
        }
[...]
```
I don't know the framework internals so i can't comment onto why, but for sure it simply doesn't work.

**Comment by cebe** [comment]
can you show the code that tries to catch it?

**Comment by twisted1919** [comment]
@cebe - i think you're missing my point here.
i have this code, most of it taken from CreateAction class for rest :
```php
    public function actionCreate()
    {
        // the class name
        $modelClass = $this->modelClass;
        
        /* @var $model \yii\db\ActiveRecord */
        $model = new $modelClass([
            'scenario' => $modelClass::SCENARIO_CREATE,
        ]);

        $model->load(request()->getBodyParams(), '');
        if ($model->save()) {
            response()->setStatusCode(201);
            response()->getHeaders()->set('Location', Url::toRoute(['users/view', 'uid' => $model->uid], true));
        } elseif (!$model->hasErrors()) {
            throw new ServerErrorHttpException(t('app', 'Failed to create the object for unknown reason.'));
        }
        
        return $model;
    }
```
The model has an email column which should be unique and i try to insert same data once again.
This of course triggers an error with the database server because of duplicate column. 
Now, the exception handler cannot catch this specific error and it returns a generic error:
```
{
  "name": "Internal Server Error",
  "message": "There was an error at the server.",
  "code": 0,
  "status": 500
}
```
 This would be avoided and a proper message would be shown, if the exception handler class, in it's convertExceptionToArray method, would also include \Exception (as well as \Error) in it's initial if statement check.

Makes sense now ?

**Comment by kidol** [comment]
Looks like you have disabled YII_DEBUG. Obviously in production environment, you don't want to show all exceptions to the client, because it could expose sensitive data (that's why it's limited to HttpException and UserException). If you turn on YII_DEBUG, you should see proper message about IntegrityException.

You could do:

```php
try {
    $model->save();
} catch (\yii\db\IntegrityException) {
    // Record already exist, throw your custom exception
}
```

**Comment by twisted1919** [comment]
@kidol - no, i have not disabled the YII_DEBUG.

**Comment by kidol** [comment]
Well I just tested and get proper exception message when YII_DEBUG is enabled:

> {"name":"Integrity constraint violation","message":"SQLSTATE[23000]: Integrity constraint violation: ...

 If it's disabled, I see the same json you posted.

**Comment by twisted1919** [comment]
@kidol - Shame on me, i did not noticed my ip address has changed and i was defining the yii debug mode based on that. Thank you for your hints, made me realize the issue.
