### ISSUE TITLE
feature or enhancement-add extra filters on grid.

### ISSUE THREAD

**Issue by ajkosh** [yiisoft/yii2#10653]
I dont know it is fine but ,i think yii has not feature so you can add extra filters on gridview. These filters can be inside (current scenario of grid) or you can add extra filter like search.php.May be this is possible but no documentation from yii team.
And very hard to find how to implement filters on arrayDataProvider.
And very hard to add extra filters on  activeDataProvider.

**Comment by SilverFire** [comment]
I believe that additional filters could be easily added.

Pass `$searchModel` and `$dataProvider` from your action to the view:

```php
public function actionIndex()
{
    $searchModel = new ItemSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
    ]);
}
```

Then create a form above the GridView like this:

```php
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row">
        <div class="col-md-2">
            <?php echo $form->field($model, 'id') ?>
        </div>
            <div class="col-md-2">
            <?php echo $form->field($model, 'name') ?>
        </div>
            <div class="col-md-2">
            <?php echo $form->field($model, 'whatever') ?>
        </div>
        </div>
    <div class="form-group">
        <?php echo Html::a('Create item', ['create'], ['class' => 'btn btn-success']) ?>
        <?php echo Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?php echo Html::a('Reset', ['index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>
```

And you will get something like this:

![screenshot 2016-01-25 001](https://cloud.githubusercontent.com/assets/4499203/12544864/116681ac-c346-11e5-90a7-6de7ff7e1bed.png)

**Comment by SilverFire** [comment]
I'm leaving the issue opened as a documentation request.

Could be added to the [Filtering data](http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#filtering-data) section of the Guide or to @samdark cookbook.

**Comment by unclead** [comment]
Also it can be useful to add note about http://www.yiiframework.com/doc-2.0/yii-grid-gridview.html#$filterSelector-detail

This property allows you to use filters outside the GridView

**Comment by ajkosh** [comment]
can yii add selection on grid column so we can hide and show column.like below
this like hide column in jquery data table
![screenshot from 2016-01-25 14 40 23](https://cloud.githubusercontent.com/assets/8582472/12546740/e33a14b6-c371-11e5-9305-8fce7deaccfb.png)

**Comment by ajkosh** [comment]
I checked online no one has idea about working filters with arrayDataProvider?

**Comment by SilverFire** [comment]
> can yii add selection on grid column so we can hide and show column.like below
> this is like hide column in jquery data table

@ajkosh one problem = one issue

Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](http://www.yiiframework.com/forum/), on [IRC](http://www.yiiframework.com/chat/) (#yii on freenode), or [Gitter](https://gitter.im/yiisoft/yii2).

Please use one of the above mentioned resources to discuss the problem.

**Comment by samdark** [comment]
It's guide-related so I'd add this to guide.
