### ISSUE TITLE
DynamicModel  validator attribute when is not work.

### ISSUE THREAD

**Issue by cevin** [yiisoft/yii2#10651]
use DynamicModel  the validator `when` is not work in browser.

```php
$model->addRule('dynamic_field_1','required',['when'=>function($model){return $model->field_1 == 100}]);
```

**Comment by cebe** [comment]
for client validation, you need to specify `whenClient`. http://www.yiiframework.com/doc-2.0/yii-validators-validator.html#$whenClient-detail

**Comment by cevin** [comment]
@cebe  thks~~ it's workd!! :)
