### ISSUE TITLE
Annotations Action Method

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#10652]
set action method or route action like symfony va asp.net

Asp.Net
```c#
[HttpGet]
[Route("{productId:int}/{productTitle}")]
public ActionResult GetProduct(int productId)
{
}
```
Symfony
```php
 /**
     * @Route("/edit/{id}")
     * @Method({"GET", "POST"})
     */
    public function editAction($id)
    {
    }
```
we can set method or route action or method controller like symfony

**Comment by SilverFire** [comment]
Currently we don't use annotations to affect any logic.
To filter requests per-method use [VerbFilter](http://www.yiiframework.com/doc-2.0/guide-structure-filters.html#verb-filter) or filter by [UrlRules](http://www.yiiframework.com/doc-2.0/guide-rest-routing.html#routing)
