### ISSUE TITLE
error yii2activeform

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#10658]
hi, im using a model for the login form and i added the rules 

```php
/**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }
```
but when i enter in the web i get this in the jquery

```javascript
jQuery(document).ready(function () {
jQuery('#login-form').yiiActiveForm([{"id":"loginform-username","name":"username","container":".field-loginform-username","input":"#loginform-username","validate":function (attribute, value, messages, deferred, $form) {yii.validation.required(value, messages, {"message":"Usuario no puede estar vacío."});}},{"id":"loginform-password","name":"password","container":".field-loginform-password","input":"#loginform-password","validate":function (attribute, value, messages, deferred, $form) {yii.validation.required(value, messages, );}},{"id":"loginform-rememberme","name":"rememberMe","container":".field-loginform-rememberme","input":"#loginform-rememberme","validate":function (attribute, value, messages, deferred, $form) {yii.validation.boolean(value, messages, {"trueValue":"1","falseValue":"0","message":"Recordarme debe ser \"1\" o \"0\".","skipOnEmpty":1});}}], []);
});
```
and this error
Uncaught SyntaxError: Unexpected token )

if see the password not add the message 
why happend this :/ ?

**Comment by cebe** [comment]
which version of yii are you using?

**Comment by spiritdead** [comment]
@cebe  im using 2.0.7 the current version

**Comment by cebe** [comment]
so you are using the master branch? 2.0.7 is not yet released ;)

**Comment by spiritdead** [comment]
@cebe i updated my yii2 using composer, is a fix for the 2.0.8 this error ?

**Comment by cebe** [comment]
looks like in this line the json_encode() returns an empty string...
https://github.com/yiisoft/yii2/blob/master/framework/validators/RequiredValidator.php#L110

@spiritdead which application language you are using?

**Comment by spiritdead** [comment]
@cebe  im using Spanish translation

**Comment by spiritdead** [comment]
@cebe the main error is when try encode the message get 
the error is Malformed UTF-8 characters, possibly incorrectly encoded

i will suggest add a validation if get a error display the default message

**Comment by cebe** [comment]
please paste the full error message including stack trace.

**Comment by spiritdead** [comment]
@cebe  i modified the function, the error is in the JSON, this not return stacktrace

return 'yii.validation.required(value, messages, ' . json_encode($options, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ');';

when try encode, this get the error
Malformed UTF-8 characters, possibly incorrectly encoded

**Comment by spiritdead** [comment]
@cebe  i found the problem, is when in the attributeLabel contains Ñ or others elements

```php
/**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'username' => 'Usuario',
            'password' => 'Contraseña',
            'rememberMe' => 'Recordarme'
        ];
    }

**Comment by cebe** [comment]
make sure all your files are encoded as UTF-8

**Comment by spiritdead** [comment]
@cebe  oh damn is the file, but is rare this file "loginForm.php" is the default in the advanced

**Comment by spiritdead** [comment]
![error encode](https://cloud.githubusercontent.com/assets/3202978/12556375/b85828e2-c357-11e5-8e2b-1b4afc9d97ca.png)
see the right-bottom corner

**Comment by cebe** [comment]
It has the correct encoding for me. Seems your setup is broken in some way.

**Comment by spiritdead** [comment]
@cebe thx for the support, but i will suggest add a validation for check if the attributelabel not get error utf8 :)
