### ISSUE TITLE
Single tab or 4 spaces

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2#10666]
One of users were confused about text [All code in a class must be indented with a single tab.](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md) while at the same file there is "Code MUST use 4 spaces for indenting, not tabs.", which is also defined by PSR-2 code standard.

Please, correct that "a single tab" or provide better explanation, if that is exception.

**Comment by Sammaye** [comment]
The code used to be 1 tab, but then was converted to 4 spaces so it seems the docs have not been updated

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/ed80bbeff2d903dde2377b04c8074cadf63315d5
