### ISSUE TITLE
Yii2 translate - Error messages not replacing {formattedLimit}

### ISSUE THREAD

**Issue by rafaelwithoeft** [yiisoft/yii2#10660]
### FileValidator.php (line 252) missing the variable FormattedLimit to replace.

'The file "Desenvolvimento de Jogos para Android.pdf" is too big. Its size cannot exceed _{formattedLimit}_.'

    case UPLOAD_ERR_INI_SIZE:
    case UPLOAD_ERR_FORM_SIZE:
        return [$this->tooBig, ['file' => $file->name, 'limit' => $this->getSizeLimit()]];

It should be:

       return [$this->tooBig, ['file' => $file->name, 'limit' => $this->getSizeLimit(), 'formattedLimit' => Yii::$app->formatter->asShortSize($this->getSizeLimit())]];

Best Regards,
Rafael

**Comment by SilverFire** [comment]
Hello. What is your language?

**Comment by SilverFire** [comment]
Thank you, fixed
