### ISSUE TITLE
query clause: `in( 4, 3, 2, 1)` does not output the same order result

### ISSUE THREAD

**Issue by haoliangxxx** [yiisoft/yii2#10663]
dbms: `maraidb 15.1`
sql: `select id, name from user where id in ( 5, 4, 3, 2 )`

It's a **dbms behavior**:

    I executed the sql in mariadb, it output with order: `2,3,4,5`

However, There is a way to make sure
    `ActiveRecord::find()->where(['id' => [5,4,3,2], 'name' => ['hello']])->inOrder(true||'id')->all()`
outputs with order in clause?

I think it is like `indexBy`, so it can be supported.

**Comment by SilverFire** [comment]
Please, check out this stash: http://gostash.it/en/stashes/262
