### ISSUE TITLE
Documentation at yiiframework.com corrupted (bad html?)

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#10662]
Hey guys, I just tried the URL with two different browsers and in both cases it looks like some bad html is in place somewhere.

This is the url with the issue

http://www.yiiframework.com/doc-2.0/guide-input-multiple-models.html

and here's a screenshot with Safari (Chrome has also same results)

<img width="979" alt="screen shot 2016-01-25 at 21 55 49" src="https://cloud.githubusercontent.com/assets/880939/12564232/6f32c7a6-c3ae-11e5-9f1c-3ce0b747a715.png">

**Comment by samdark** [comment]
Can't reproduce. Check if there are any weird extensions/plugins installed.
