### ISSUE TITLE
Caption for DetailView Widget

### ISSUE THREAD

**Issue by gbespyatykh** [yiisoft/yii2#10667]
Missed caption for table rendered by DetaiView widget

**Comment by SilverFire** [comment]
Could you described your problem in detail?

**Comment by gbespyatykh** [comment]
The caption and captionOptions widget options isn`t presented in DetailView

**Comment by klimov-paul** [comment]
> caption for table

This does not make any sense: table does not have caption

**Comment by gbespyatykh** [comment]
Caption tag presented in HTML specification: http://www.w3schools.com/tags/tag_caption.asp
Also yii/grid/GridView has the caption and captionOptions in widget properties

**Comment by gbespyatykh** [comment]
Okay, then I should use 'foreach' instead of widget...

**Comment by klimov-paul** [comment]
```php
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'label' => 'My Caption Label',
                'value' => 'My Caption Value',
            ],
            'id',
            'name',
        ],
    ]) ?>
```

**Comment by gbespyatykh** [comment]
Yes, of course. But this is bad solution, because you must also specify colspan attribute at row to merge columns. CSS styles for columns and rows will affect on this caption made by tr and td tags. Caption is easer for styling.

Why caption is used in the GridView widget, but not used in DetailView?
