### ISSUE TITLE
andFilterWhere unsets existing condition when value for new condition isEmpty

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#10664]
Creating a search condition for a column based on the value that may come from one of two different fields.

```php
// This does not work as expected
// The condition for objektID will deleted when $this->objektID is null
 $query->andFilterWhere([
             'objektID' => $this->getAttribute('relationname.columname'),
             'objektID' => $this->objektID,           // unsets existing condition on objektID when value is null
  ]);
```

```php
// This works  
 $query->andFilterWhere([
             'objektID' => $this->getAttribute('relationname.columname'),
           ]);
// The conition for objektID will not be deleted when $this->objektID is null
$query->andFilterWhere([
             'objektID' => $this->objektID,           
  ]);
```

**Comment by SilverFire** [comment]
> // This does not work as expected

It works as expected since the hash keys must be unique. Otherwise the last key definition will be used.


> // The conition for objektID will not be deleted when $this->objektID is null

Method `andFilterWhere()` is not designed to delete any existing filter conditions.

I guess you need a coalesce:

```php
$query->andFilterWhere([
   'objektID' => $this->getAttribute('relationname.columname') ?: $this->objektID
])
```

**Comment by twinni** [comment]
@SilverFire, thanks for your answer. It was my fault not recognizing that the hash key must be unique.

The idea of using the coalsche operator is great. 
Your example show's the usage of the ternary operator (?:) which works very well.

Since php 7.0 the coalsche operator (??) is also possible and looks like:
```php
 $query->andFilterWhere([
   'objektID' => $this->getAttribute('relationname.columname') ?? $this->objektID
])
```

**Comment by SilverFire** [comment]
Yes, but since Yii2 has PHP 5.4 as a minimum requirement, we tend to post PHP5-compatible suggestions, if it's possible.
