### ISSUE TITLE
ActiveQuery::joinWith() still executes multiple sqls 

### ISSUE THREAD

**Issue by yvvq** [yiisoft/yii2#10676]
joinWith() doesn't execute less sqls compare to with()

```
$orders = Order::find()->joinWith('customer')->all();
```
execute following sqls:
```
SELECT `order`.* FROM `order` LEFT JOIN `customer` ON {{order}}.[[customer_id]] = {{customer}}.[[id]]

SELECT * FROM `customer` WHERE 0=1
```

and  
```
$orders = Order::find()->with('customer')->all();
```
execute following sqls:
```
SELECT * FROM `order`

SELECT * FROM `customer` WHERE 0=1
```

obviousely, the first  sql of joinWith() is more complicate. 

it's also exists in more complicate scenes.

**Comment by yvvq** [comment]
sorry for misunderstanding the joinWith popurse

**Comment by klimov-paul** [comment]
Duplicates #10016

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#lazy-eager-loading
