### ISSUE TITLE
yiiActiveForm.beforeValidate don't triggered on validate()

### ISSUE THREAD

**Issue by efureev** [yiisoft/yii2#10681]
`beforeValidate` don't triggered on validate() on setting:
```
'validationUrl' => Url::toRoute('/cabinet/validate-change-phone'),
```
Triggered only on `Submit`

https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L292

Change code to
```
var event = $.Event(events.beforeValidate);
$form.trigger(event, [messages, deferreds]);
if (submitting) {             
                if (event.result === false) {
                    data.submitting = false;
                    submitFinalize($form);
                    return;
                }
            }
```
 triggered event

**Comment by SilverFire** [comment]
> beforeValidate don't triggered on validate() on setting

Could you describe step-by-step way to reproduce the error, please?

Можно по-русски

**Comment by SilverFire** [comment]
Failed to reproduce on basic application template.

```php
$this->registerJs("$('#contact-form').on('beforeValidate', function (event, messages, deferreds) {
   console.log(event, messages, deferreds);
   // console log message appears regardless of form configuration
});");
```

I'm closing the issue unless new details provided by @efureev

**Comment by lynicidn** [comment]
хм, у меня тоже не работает dev-master 2.0.9-dev

**Comment by lynicidn** [comment]
если закоментировать проверку, в строке, которую указал @efureev 
if (submitting) {     

или им предложенный вариант, то событие таки создается

**Comment by lynicidn** [comment]
@SilverFire you test it with differed url for validate and submit ?

**Comment by lynicidn** [comment]
вот даже если там сделать
if (submitting || data.settings.validationUrl !== undefined)
то уже жизнь наладица, но на сколько это костыль судить вам

**Comment by lynicidn** [comment]
это связано даже не сразными урлами экшн и валидации, но и даже без validationUrl
фиксим:
если на 528 строке добавить
data.submitting = true;
т.е. перед запуском валидации, так же как и в методе beforeSubmit в "1м чтении", - то вроде ниче не падает, логика не страдает и beforeValidate начинает отрабатывать, но перестает отправляться форма, что ожидаемо - мы всегда прерываем beforeValidate устанавливая свой, поэтому нужно отключать у формы
'validateOnSubmit' => false,

но до этого форма и сабмитилась, потому что обработчик не становился куда нужно.

Кстати это событие легко проверить - повесьте свой обработчик function(){return false;}
на beforeValidate - и сабмитьте форму сколько угодно - это нынешнее состояние дел ;) - сейчас флаг validateOnSubmit не влияет на результат валидации

**Comment by samdark** [comment]
@SilverFire ?

**Comment by githkim** [comment]
Sorry, but after this fix, event 'beforeValidate' will called after blur on any field with enabled client validation. But 'afterValidate' will not called. For example, this code does not work now:
```javascript
    // Form submition with enabling/disabling submit-button to prevent request multisend
    $(document).on('beforeValidate', 'form', function (event, messages, deferreds) {
        console.log('beforeValidate');
        $(this).find('[type=submit]').attr('disabled','disabled');
    }).on('afterValidate', 'form', function (event, messages, errorAttributes) {
        console.log('afterValidate');
        if (errorAttributes.length) {
            alert('Check form errors!');
            $(this).find('[type=submit]').removeAttr('disabled');
        }
    }).on('beforeSubmit', 'form', function (event) {
        console.log('beforeSubmit');
        $(this).find('[type=submit]').removeAttr('disabled');
    });
```

**Comment by lynicidn** [comment]
проблема никак не связана с before validate, этот код не менялся, менялось только событие before, не надо ляля тут, что после этого фикса... просто афтер никому не нужен был, вот и не фиксили, так как и не вылавливали ошибку

**Comment by SilverFire** [comment]
See #12069

**Comment by SilverFire** [comment]
Fixed by https://github.com/yiisoft/yii2/commit/418b27326c8753e1224080a958930550ff4d11ac
