### ISSUE TITLE
better deleteAll and updateAll

### ISSUE THREAD

**Issue by olehlong** [yiisoft/yii2#10689]
Hello. 
It would be nice to have an option to use more difficult conditions in deleteAll and updateAll. Or an option to build query like find:
`History::delete()->where(..)->andWhere(...)->all();`
For example, yii1:
`History::model()->deleteByPk($ids, 'user_id=:uid AND status != :status"', array(':uid' => Yii::app()->user->id, ':status' => 'processing'));`
This query will have IN, !=, = operators.
But in yii2 it would be difficult to build the same query (as far as I know).
```
History::deleteAll('id IN (:ids) AND user_id=:uid AND status!=:status', [
                    ':ids' => implode(',', $ids), 
                    ':uid' => Yii::$app->user->id,
                    ':status' => 'processing'
                ]);
```
It doesn't look nice in compare to yii1 version.
It there any better solution?
Thanks in advance.

**Comment by SilverFire** [comment]
I guess we can use something like

```php
$query = new Query();
$query->where(...)->andWhere(...);

History::deleteAll($query->where, $query->params);
```

**Comment by SilverFire** [comment]
Or even

```php
History::deleteAll([
    'and', ['and', ['in', 'id', ':ids'], ['=', 'user_id', ':uid']], ['!=', 'status', ':status']
], [
    ':ids' => [1,2,3],
    ':uid' => 10,
    ':status' => 'processing'
]);
```

**Comment by olehlong** [comment]
Thank you!

**Comment by olehlong** [comment]
Last one throws an error:

> SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
> The SQL being executed was: DELETE FROM `history` WHERE ((`id`=':ids') AND (`uid` = ':uid')) AND (`status` != ':status')

```
History::deleteAll([
                    'and', ['and', ['in', 'id', ':ids'], ['=', 'uid', ':uid']], ['!=', 'status', ':status']
                ], [
                    ':ids' => $ids, 
                    ':uid' => Yii::$app->user->id,
                    ':status' => 'processing'
                ]);
```

But it works without params:

```
History::deleteAll([
                    'and', ['and', ['in', 'id', $ids], ['=', 'uid', Yii::$app->user->id]], ['!=', 'status', 'processing']
                ]);
```

**Comment by SilverFire** [comment]
Oh, sorry, it was a fast answer without check. Of course, where conditions definition using array syntax does not require manual parameter binding.

I've edited my last post not to baffle other members.
