### ISSUE TITLE
[yii2 basic template + mongodb] Login Remember me feature is not working

### ISSUE THREAD

**Issue by usmanp24** [yiisoft/yii2#10688]
Hi,

I am using mongodb and yii2..I have added all the requirements to connect with mongodb...created the collection and user in it. And login is working flawlessly. But Remember Me feature is not working.

When i switch to mySQL database then Remember me feature is working without changing any configuration but with mongodb it is not.

I think when application runs then application is not looking for auth_key into mongodb.

P.S. enableAutoLogin is true as well. All the configuration is fine that is why it is working on mySQL.

**Comment by SilverFire** [comment]
How to reproduce it?

**Comment by usmanp24** [comment]
Just login with the valid credentials and Remember me checked.

close the browser....

open the browser....open your web application...user should be signed in..but he is not

**Comment by SilverFire** [comment]
Once you change session handler from Mongo to default one, the problem disappears?
Did you try to debug queries to Mongo?

**Comment by usmanp24** [comment]
actually i am new to yii2 and i have absolutely no idea how to do above mentioned stuff :)

how to change the session handler to mongo? :)

and how to debug queries? :)

Thanks

**Comment by SilverFire** [comment]
I thought we are talking about [Custom Session Storage](http://www.yiiframework.com/doc-2.0/guide-runtime-sessions-cookies.html#custom-session-storage), aren't we?

**Comment by usmanp24** [comment]
No...I am not using custom session. I am using the default feature of basic template..that is login with remember me option.

There is no session table involve in it.. 

Basically at the time of user registration we generate an auth_key and save it in the database. And on login with Remember me checked...A cookie is saved in the browser with the combination of id/auth_key/duration named as _identity.

So when the application runs it checks in the database for auth_key if it is valid or not...if it is valid then user is loggedin...

This is what i am talking about [Info](http://www.yiiframework.com/doc-2.0/guide-security-authentication.html#implementing-identity)

**Comment by SilverFire** [comment]
> Just login with the valid credentials and Remember me checked.
> 
> close the browser....
> 
> open the browser....open your web application...user should be signed in..but he is not

Failed to reproduce on basic yii2 app template.
We need more details.



> and how to debug queries? :)

Please, check out Yii2 debug panel.
