### ISSUE TITLE
yii\bootstrap\Nav not work when yii2 Nav include bootstrap.js,my global Asset include bootstrap.min.js

### ISSUE THREAD

**Issue by buuug7** [yiisoft/yii2#10687]
my global asset file is below
![image](https://cloud.githubusercontent.com/assets/12119289/12639705/ba88eda0-c5e0-11e5-95f6-753fd5bd47e7.png)

my assetManager is like below
![image](https://cloud.githubusercontent.com/assets/12119289/12639717/d4097722-c5e0-11e5-8e2c-c94f21875eae.png)

when i turn mode from dev to prod ,yii\bootstrap\Nav widge not work

![image](https://cloud.githubusercontent.com/assets/12119289/12639793/4cf3a6da-c5e1-11e5-86a3-6319978b5b89.png)

**Comment by buuug7** [comment]
twice include bootstrap.js will let some buttons,navs plugin not work,but how can i remove the bootstrap.js??

**Comment by klimov-paul** [comment]
There is no `yii\bootstrap\BootStrapPluginAsset` class, there is `yii\bootstrap\BootstrapPluginAsset` ('strap' in lower case) instead. So your config simply defines extra bundle with 'bootstrap.js' in addition to standard one.

**Comment by buuug7** [comment]
when i  modfied my asset file ,it works,Thanks klimov-paul,i  become your follower
