### ISSUE TITLE
[Web][Request] getIsSecureConnection doesn't handle SSL request behind ELB

### ISSUE THREAD

**Issue by Tomino2112** [yiisoft/yii2#10684]
Hi,

There is an issue with determining if connection is secure.  

`\yii\web\Request:526 function getIsSecureConnection`

Correctly checks for `HTTP_X_FORWARDED_PROTO` header which is set by ELB if ELB listener is set to HTTPS protocol. 

BUT if you want to use websockets in your app, you have to set your ELB to use SSL instead of HTTPS and using SSL doesn't set the above mentioned header. 

Hence all my route rules for subdomain: `https://<module>.domain.com' => '<module>/default` are looking for match with 'http://' and therefore not working.

Maybe would be good to have some fallback that checks https in the url?

**Comment by cebe** [comment]
> use SSL instead of HTTPS

could you explain the difference? also, what is ELB?

**Comment by Tomino2112** [comment]
@cebe ELB is "Elastic Load Balancer" - load balancer provided by Amazon AWS. It is used in almost every bigger project hosted on Amazon. 

In ELB you can setup "Listeners" which is basically control of what traffic is the balancer listening for.

Usually you setup HTTP and HTTPS listeners if you have just normal website. Most of the admins set it up so ELB is taking care of HTTPS instead of the server/instance itself. 

This means that ELB receives request on HTTPS and then pass it down to instance as simple HTTP request. This simplifies the server configuration (nginx,apache etc.) But of course, you want to know if user is actually making secure request. That is why Amazon adds headers to every request that is passed down to instances. In this case it sets **X-Forwarded-Proto** header, which is set to "https" if  client made a https request to ELB.

Yii correctly checks for this header when it determines if the connection is secure.

The real issue is when you have also api and want to use sockets. Sockets do not communicate via http/https but via TCP/SSL connections (lower layer). **Amazon does not support X-Forwarded-* headers on SSL/TCP connections**

So if you want to have api with sockets behind your ELB, you have to ditch HTTPS listeners and instead setup SSL listeners. And this is where the issue is, because when Yii checks for "X-Forwarded-Proto" it is empty even though the request has been done over secure connection. 

I am not sure what is the best solution for this. Would it be safe to check the URL for "https" pattern? can it be spoofed? 

At the moment I had to extend the request class and always return true from `getIsSecureConnection` since we always use https. But it is not bulletproof so it would be nice to see how could Yii handle it better.

**Comment by SamMousa** [comment]
In my opinion the current behavior is a security issue. If I want to know if a connection is secure, why on earth would I check a possibly user provided header?

If you wish to use that there should be a configuration in the `Request` component that allows me to configure trusted proxy IPs.

Currently `getIsSecureConnection()` can't be trusted:
````
curl -v --header "X-Forwarded-Proto: https" "http://prime.sam/dev"
*   Trying 192.168.37.2...
* Connected to prime.sam (192.168.37.2) port 80 (#0)
> GET /dev HTTP/1.1
> Host: prime.sam
> User-Agent: curl/7.43.0
> Accept: */*
> X-Forwarded-Proto: https
> 
< HTTP/1.1 200 OK
< Server: nginx/1.9.3 (Ubuntu)
< Date: Thu, 04 Feb 2016 08:05:45 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< 
bool(true)
````

**Comment by Tomino2112** [comment]
@SamMousa Well yes and no... If you are using the ELB, the header cannot be spoofed, because it goes through the ELB, if the header is set, it is discarded by ELB and set to correct value. 

But if you are not using ELB, then yes there is security hole, that should be addressed by the the the developer or even better by Yii framework. 

Some config such as `respectELBHeaders => true` could be added to the `request` class to handle that. 

Mind you, that is separate issue, it still wouldn't solve the issue I reported at the beginning

**Comment by SamMousa** [comment]
@Tomino2112 What prevents me from talking directly to your webserver even if you have a reverse proxy configured.

My point is that in general checking for a secure connection (for which you reported a bug) is currently a broken feature.

**Comment by Tomino2112** [comment]
@SamMousa I dont think you understand how ELB works. There is no way to access the instance directly. Only out facing thing is the ELB, and all routing between ELB and servers themselves is the internal AWS routing. at no point there is anything facing out from the instances. Only thing you can access is the ELB and you cannot fake the headers to ELB.

And no, it is not what I reported, and yes I am aware of how to setup websockets with ELB. But as you can see from the screenshots on that link, you have to setup SSL connection on your ELB, and then you don't get the headers in Yii and thus cannot determine if the connection was made secure way or not. And thats what the problem is. I am not asking how to setup something, I am just saying that once you go over SSL and not HTTPS behind ELB you have no way of telling if the connection is secure or not.

**Comment by SamMousa** [comment]
I know, but from a PHP perspective this cannot be automatically determined. The only way for PHP to "know" that is for you to tell it; hence my suggestion to configure trusted proxy IPs in the request object.

Basically you want to be able to "detect" whether a connection is secure but at the same time you are telling me they are always secure since you have configured that in ELB? Why not just skip the check then? 

Assuming ELB is configured to proxy both normal and SSL connections and it does not allow you to add any headers then how should the backend know whether the incoming connection was secure?

**Comment by Tomino2112** [comment]
@SamMousa Yes that is exactly what I did actually. I had to extend the `request` class and just return true in `getIsSecureConnection()` 

So if there is no secure way to say if connection is secure or not, there should be some settings that doesn't require me extending the request class. I can imagine a lot of devs spending hours and days trying to figure out whats happening. 

Even if ELB is configured to pass both HTTP and HTTPS connections, the header will be always correct as ELB doesn't let you pass your own X-FORWARDED-PROTO and forces its own values. I don't know the algorithm that they determine if it as secure or not, but since you have to configure your certificates on ELB, I believe its quite low-level stuff and cannot be faked.

**Comment by SamMousa** [comment]
You said ELB doesn't pass a header for socket connections.. so in that case what header is there to trust?

**Comment by Tomino2112** [comment]
Yes that is the initial problem. If you setup your ELB to listen for SSL `getIsSecureConnection()` is false even though it should be true.

When you say 

> Assuming ELB is configured to proxy both normal and SSL connections

If you mean that ELB is configure to use HTTPS and SSL, that is not possible, as you can configure only one or the other. 

So bottom line is, if you configure ELB to SSL there is no way for Yii to know if the connection was secure. If there is no way to actually know if its secure or not, then there should be some kid of configuration that allows you to tell Yii if the connection is secure or not.

Or you could create your own evaluation function for whatever other cases there might be - which is, I suppose, same as extending the class...

**Comment by SamMousa** [comment]
I don't see the use. @Tomino2112 the only reason Yii uses it is to determine the hostInfo.
If you want to override that you can do it via configuration:
````
...
'components' => [
    'request' => [
        'hostInfo' => 'https://mysite.com/yii-app3'
    ]
]
````

**Comment by Tomino2112** [comment]
@SamMousa not true, Yii is using `getIsSecureConnection` to parse routes

**Comment by mikehaertl** [comment]
> The real issue is when you have also api and want to use sockets. Sockets do not communicate via http/https but via TCP/SSL connections (lower layer). 

@Tomino2112 I wonder, how you set up the listener in this case. You say, there's no HTTP involved. But if there's no HTTP request, I assume that there's also no web server like Apache or Nginx used. But how does Yii listen for requests in this case?

**Comment by Tomino2112** [comment]
@mikehaertl Doesn't matter what protocol you using, ngnx is listening on port 80. You can use TCP connection to port 80 instead of HTTP protocol. So if you want to use sockets, you setup ELB to listen on SSL 443 and pass it to TCP on 80

**Comment by mikehaertl** [comment]
@Tomino2112 Ok, thanks. Still trying to understand the difference between HTTP/HTTPS and TCP/SSL socket connection. You say "TCP connection to port 80 instead of HTTP protocol". But if nginx is listening on port 80 it expects HTTP requests (which you obviously seem to send). So why can't you use HTTP/HTTPS in the first place? Or put another way: What's the advantage to TCP/SSL and how do they differ from regular HTTP/HTTPS?

**Comment by mikehaertl** [comment]
@Tomino2112 Kind of answering my own question: http://stackoverflow.com/questions/16945345/differences-between-tcp-sockets-and-web-sockets-one-more-time

I'm not sure, if Yii is really meant to be used like this. In your case I'd probably configure Nginx to inject the missing  `X-Forwarded-Proto` header before it passes on the request to php-fpm.

**Comment by SamMousa** [comment]
@Tomino2112 if you look through the source code there is only 3 locations the function is used:
1. getHostInfo
2. getPort
3. getSecurePort

All of these are in the `Request` object and all of these can also be manually configured. As far as I can tell `getIsSecureConnection` or `isSecureConnection` is nowhere else in the source code.

**Comment by Tomino2112** [comment]
@mikehaertl Yii doesn't have to support websockets, you have to create another app for that. In my case NodeJS app. Mu report was initially about how Yii determines if the connection is secure or not based on server configuration that is very specific to using AWS ELB. 

Simple explanation: Yii does check ELB-specific headers (so obviously someone thought of that) **but**  AWS does not support those headers in every scenario, **which means that Yii will tell you the connection is not secure even though it is** and that could classify as a bug. So - what should the framework do in those cases? 

From above conversations, since this is so specific and quite fiddly, best way seems to be manually tell the framework if the connection is secure or note, regardless what way you do that.

@SamMousa  Sorry its been quite a while when I stared this issue, and dont remember exactly my digging trough the code, I suppose the route evaluation is using one of those functions that you listed above.

**Comment by mikehaertl** [comment]
@Tomino2112 Not sure if I can follow. As you say, Yii is not ready for websockets. It's made for web apps and APIs, so you will never need ELB with TCP/SSL protocol but can always use HTTP/HTTPS.

Or put another way: Can you describe a scenario apart from websockets, where you can't use ELBs HTTP/HTTPS protocols?

**Comment by Tomino2112** [comment]
@mikehaertl No, you will need ELB with TCP/SSL protocol because you have your websocket app sitting behind it as well as your Yii website. 

So, lets say you have rest API written in Yii and websocket API written in NodeJS. Both of them sitting behind ELB.

In that case you will need to listen for TCP and SSL protocols because of the sockets, but Yii will not recognize secure connection because above header is not set

**Comment by SamMousa** [comment]
@Tomino2112 can this issue be closed then?
Since it can be resolved using configuration, and the scenario you describe SHOULD be resolved via configuration and not detection, I think this can be closed.

**Comment by mikehaertl** [comment]
@Tomino2112 But that are two different applications: One is your Yii REST API and the other is the NodJS websocket. I don't understand how you can have two apps behind one load balancer. You'd need two ELB instances in that case.

**Comment by Tomino2112** [comment]
@SamMousa Can I just ask to repeat exactly what is the best config to solve this with? Just so we have some definite answer. Thanks

**Comment by Tomino2112** [comment]
@mikehaertl  Does this diagram makes it any clearer for you? 
![diagram1](https://cloud.githubusercontent.com/assets/1140217/13048171/088b84f0-d3dc-11e5-9370-d9ca5a086c93.jpeg)

**Comment by mikehaertl** [comment]
@Tomino2112 Hmm, how does nginx know, whether to forward to Yii or Websocket app?

**Comment by Tomino2112** [comment]
@mikehaertl I dont think that should be discussed here really, its server setup 101. Just google nginx virtual hosts. Just understand that ELB is managing traffic between instances/servers not applications. You are thinking about it on too of a high level

**Comment by mikehaertl** [comment]
@Tomino2112 Don't worry, I know, how to setup Nginx :). The question here is really, why you have 1 ELB for 2 Apps. Nginx somehow has to dispatch the connections on some criteria and that's what I don't get in your setup. Personally I think, the infrastructure setup is not optimal.

**Comment by cebe** [comment]
@Tomino2112 if there is an nginx between ELB and yii, why not set the header in the nginx config?

**Comment by Tomino2112** [comment]
@mikehaertl There are couple of ways to set this up with nginx, and I dont see a problem in any of them. Of course for big project you will have the apps on separate servers, even ELBs etc, but for normal-sized project I don't see whats not to understand on this setup. 

As you said, ELB is dispatching the connections, it does not care about what data does it transferring. You have to decide what to do with the connection on your side - nginx.

**Comment by Tomino2112** [comment]
@cebe Yes that would be one way to do it. But I would always prefer some kind of detection rather than hard-coding it, in case the setup changes

**Comment by SamMousa** [comment]
@Tomino2112:
````
...
'components' => [
    'request' => [
        'hostInfo' => 'https://{your_domain}',
        'port' => 80,
        'securePort' => 443

````

There is no safe detection method @Tomino2112; the current detection method is even faulty and actually a security issue. (I'll make an new issue for that @cebe).

**Comment by Tomino2112** [comment]
@SamMousa Good, we can close this now :)

**Comment by mcarbonneaux** [comment]
ELB ok, but on other reverse proxy/LB, there many framework supporting use of x-forward- header !

like symfony for exemple : http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html 

like that you can acces your site from diffrente url through different lb...
