### ISSUE TITLE
Query->count() fails when parameters are in SELECT statement

### ISSUE THREAD

**Issue by jpodpro** [yiisoft/yii2#10686]
the following reasonably simple query fails with an "invalid parameter number" exception.

```PHP
$query = User::find()
            ->addSelect( ['*', 'CASE WHEN username LIKE :phrase THEN 1 ELSE (0) END AS relevance'] )
            ->where( ['like', 'username', "admin%", false] )
            ->params( [':phrase'   => "admin %"] );

count = $query->count();
```

when performing the count, yii appears to throw away the select statements (thus removing the bound parameter) and then fails because the provided parameter is no longer in the SQL. i have encountered this problem before. why can't yii simply ignore provided parameters that aren't found in the query?

**Comment by klimov-paul** [comment]
>  yii appears to throw away the select statements (thus removing the bound parameter) 

Yes, howver it is unlikely we can do anything about it.

> can't yii simply ignore provided parameters that aren't found in the query?

It can not: this matter is handled by PDO internally and Yii has not influence on it.

Try to use `yii\db\Expression` with parameters in your select, this should fix the issue for you:

```php
$query = User::find()
            ->addSelect( [
                '*',
               new Expression( 'CASE WHEN username LIKE :phrase THEN 1 ELSE (0) END AS relevance', [
                   ':phrase'   => "admin %"]
               ])
            ] )
            ->where( ['like', 'username', "admin%", false] );

$count = $query->count();
```
