### ISSUE TITLE
requirements.php file throws error when php intl extension not installed

### ISSUE THREAD

**Issue by JiLiZART** [yiisoft/yii2#10697]
I have this message in console
`PHP Notice:  Use of undefined constant INTL_ICU_VERSION - assumed 'INTL_ICU_VERSION'`
when run `php requirements.php` in my app

**Comment by cebe** [comment]
which version are you trying? Afair, this has been fixed already.

**Comment by JiLiZART** [comment]
@cebe 2.0.6

**Comment by cebe** [comment]
fixed by https://github.com/yiisoft/yii2/commit/f393a84a0fb50296259adf12eaa277df0b5aa8bb, will be fixed in 2.0.7.
