### ISSUE TITLE
\yii\i18n\I18N::format() invalid pattern, wont translate placeholders in certain cases

### ISSUE THREAD

**Issue by tuuling** [yiisoft/yii2#10690]
When trying to translate a sentence with anything but simple placeholders ({var}) it fails unexpectedly. An example would be:
`Yii::t('account', 'Next payment is in {days, plural, =1{# day} other{# days} ({date})',
                        [
                            'days' => $days,
                            'date' => $date
                        ]`

The result here would be that it translates the message, but will leave the placeholders unaffected. The reason here is that when \yii\i18n\I18N::format() method spots `{days, plural, =1{# day} other{# days}` it first tries to format it with /MessageFormatter first (yii2/i18n/I18N.php:112). And for /MessageFormatter {date} is an invalid placeholder. This is a bit unexpected, as if I would use just the {date} in my translation key it would only use only the simple strtr() method and replace the string correctly.

This also happens when you try to use placeholders with forward slashes {/link} as this is also an invalid format for a placeholder for /MessageFormatter. Which would be a common usecase in strings where you want to have tags "Click {link} here {/link} to move on" for example.

The possible fix here would be to do the strtr() replacement first and then do the /MessageFormatter one. I'm not sure if this change wont break anything else tho.

Yii version: 2.0.5

**Comment by SilverFire** [comment]
Your message is malformed, you've missed a closing bracket.

Next payment is in {days, plural, =1{# day} other{# days}_**}**_ ({date})

**Comment by SilverFire** [comment]
> This also happens when you try to use placeholders with forward slashes {/link} as this is also an invalid format for a placeholder for /MessageFormatter. Which would be a common usecase in strings where you want to have tags "Click {link} here {/link} to move on" for example.

It is by design. Use `openLink`, `closeLink` instead

**Comment by tuuling** [comment]
Sry, the missing bracket was my mistake but the problem is still valid even with correct number of braces.

IF this is by design I would assume this would be better documented at least, which I did not find. If I would use "Click {link} here {/link} to move on" it would work fine, I would then assume that this is a correct way to use it. If I would do something like "Click {link} here {/link} to move on to {page, number}" it would not work. Which is very misleading as using {/link} and {page, number} separately would work just fine.

This:
`Yii::t('account', 'Next payment is in {days, plural, =1{# day} other{# days}} ({date})', [ 'days' => 11, 'date' => '11.12.2015' ]);`
Will output 
`Next payment is in {days, plural, =1{# day} other{# days}} ({date})`
But I would assume it to output:
`Next payment is in 11 days (11.12.2015)`

In this case it is very hard to figure out why this is not working as:
`Yii::t('account', 'Next payment is on ({date})', [ 'date' => '11.12.2015' ]);`
and 
`Yii::t('account', 'Next payment is in {days, plural, =1{# day} other{# days}}', [ 'days' => 11]);`
both work fine.

I have currently fixed this by extending the \common\components\i18N::format method and doing:
`    public function format($message, $params, $language)
    {
        $params = (array) $params;
        if ($params === []) {
            return $message;
        }

        $p = [];
        foreach ($params as $name => $value) {
            $p['{' . $name . '}'] = $value;
        }

        $fixedMessage = strtr($message, $p);

        return parent::format($fixedMessage, $params, $language);
    }`

IF this is by design, I see it as poor design/documentation. I'm not sure what the reason is for doing /MessageFormatter before strtr() but it seems that switching the order fixes the problem and does not cause any additional problems.

**Comment by SilverFire** [comment]
Could you show the result of the following code execution:

```php
echo 'PHP: ' . PHP_VERSION;
echo "\n"
echo 'ICU version: ' . INTL_ICU_VERSION;
echo "\n";
echo 'ICU version: ' . INTL_ICU_DATA_VERSION;
```

**Comment by tuuling** [comment]
PHP: 5.5.29-1~dotdeb+7.1 ICU version: 4.8.1.1 ICU version: 4.8.1

I also considered that the ICU version could be a culprit here. But I was unable to test with different configurations.

**Comment by SilverFire** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#verifying-installation
There is a manual for requirement check closer to the end of the paragraph.

It will say to you, that `ICU 49.0 or higher is required when you want to use <code>#</code> placeholder in plural rules`.

So just update your env :)

**Comment by tuuling** [comment]
Sry for the bad examples. I did notice that too and tried without the # but the result is still the same. I debugged it, and the thing it did not like was {/link} and {date} (there are prolly more). All that the plural rule did was that it triggered the /MessageFormatter to parse the string.

For example doing 
`Yii::t('account', 'Next payment is in {days, number} ({date})', [ 'days' => 11, 'date' => '11.12.2015' ]);`
would still fail to parse
`Next payment is in {days, number} ({date})`

My devops skills fall short of updating my env, as it seems that 49 is available only for deb8 (we use deb7) If you can confirm that my examples work with v 49 I could then embark on updating it.

**Comment by SilverFire** [comment]
I can't check on v.49, but v.52 works as expected. Just update your ICU.

**Comment by lynicidn** [comment]
try change `other` to `many`

**Comment by lynicidn** [comment]
Yii::t('account', 'Next payment is in {days, plural, =1{# day} **many**{# days}} ({date})', [ 'days' => $days, 'date' => $date

**Comment by tuuling** [comment]
@lynicidn other and many are different things actually. See http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html

**Comment by tuuling** [comment]
it appears that Debian 7 ICU latest php5-intl package comes with ICU v49. Deb 8 comes with v52. 

IF anyone is interested how to overwrite your i18n class then the config value would be:
`'i18n' => [
            'class' => 'common\components\i18n',`
