### ISSUE TITLE
Problem with $model->loadDefaultValues() and DEFAULT NULL in PostgreSQL

### ISSUE THREAD

**Issue by wallysalami** [yiisoft/yii2#10692]
We have a bug here with Yii2 2.0.6 and our PostgreSQL database. When a column is set with `DEFAULT NULL`, Yii2 puts a string `NULL` (NULL written as a text) in the attribute after we call `$model->loadDefaultValues()`.

Example:

```SQL
CREATE TABLE "test"
(
	"id" SERIAL PRIMARY KEY,
	"name" varchar(255) DEFAULT NULL
);
```

and

```php
$model = new Test;
$model->loadDefaultValues();
var_dump($model->name);
```

The output is

`string(4) "NULL"`

The expected output would be

`NULL`

<br>
I believe the problem is in yii\db\pgsql\Schema:

```php
protected function findColumns($table)
{
    ...
    foreach ($columns as $column) {
        ...
        if ($column->isPrimaryKey) {
            ...
        } elseif ($column->defaultValue) {
            if ($column->type === 'timestamp' && $column->defaultValue === 'now()') {
                ...
            } elseif ($column->type === 'boolean') {
                ...
            } elseif (stripos($column->dbType, 'bit') === 0 || stripos($column->dbType, 'varbit') === 0) {
                ...
            } elseif (preg_match("/^'(.*?)'::/", $column->defaultValue, $matches)) {
                ...
            } elseif (preg_match("/^(.*?)::/", $column->defaultValue, $matches)) {
                $column->defaultValue = $column->phpTypecast($matches[1]);
            } else {
                ...
            }
        }
    }

    return true;
}
```

In our case, the value of `$column->defaultValue` comes as a string `NULL::character varying`.

**Comment by SilverFire** [comment]
Would you like to submit a PR?

**Comment by wallysalami** [comment]
Sorry, I'm a little confused with pull requests here. I think I save it in #10694. Is that it?

**Comment by cebe** [comment]
> Sorry, I'm a little confused with pull requests here.

except that you have [not created a new branch](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#3-create-a-new-branch-for-your-feature-based-on-the-current-yii-master-branch) for the pull request, it looks like you have done everything right ;)
Its okay for now but keep in mind that everything you push to master will end up in that pull request, also if you want to make other pull requests in the future you have to clean up your forks master branch first. Check out the contribution guidelines for details: https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by wallysalami** [comment]
Oh, sorry, I should have read that guide carefully. Well, I'll do it properly next time.

As I commented in #10694, it looks like there is another pull request (#9773 ) with a fix like mine.
