### ISSUE TITLE
Make \yii\web\Cookie configurable

### ISSUE THREAD

**Issue by Deprecator** [yiisoft/yii2#10699]
There is an issue with the default class Cookie which is not configurable in its native implementation, i.e various configruations are spreaded across several yii's components such as User, Request. But if there is a need to set some cookie of our own, like one defining chosen user language, we have to either manually set the domain for the cookie or make some sort of configuration in the params.php config file. That`s to make a working cookie which can be accessed across subdomains.

The point is that the Cookie class should be a Component descendant, so we can configure it like we can do with Session.

**Comment by Deprecator** [comment]
I'm going to implement such approach in one of my projects so if the issue is to be approved, I could make a pull request.

**Comment by samdark** [comment]
Have you tried using DI container for it?

**Comment by Deprecator** [comment]
Currently I'm using the following approach(yii advanced app):

frontend/config/main-local.php

<code>
<pre>
return [
    'components' => [
        'cookie' => [
            'class' => 'yii\web\Cookie',
            'domain' => '.domain.zone' # set the actual domain name here
        ]
    ]
]
</pre>
</code>

And this is the piece of code which I use to send the cookie:

<code>
            $lang = 'en';
            $cookie = Yii::$app->get('cookie');
            if($cookie instanceof \yii\web\Cookie) {
                Yii::configure($cookie, ['name' => 'lang', 'value' => $lang]);
                Yii::$app->getResponse()->getCookies()->add($cookie);
            }
</code>

Seems to be working but I think it would be better to encapsulate it into Yii::$app->getCookie() method which would return a \yii\web\Cookie object.

**Comment by samdark** [comment]
I think it's a bad idea to make app a cookie factory.

**Comment by Deprecator** [comment]
What would be the best approach then?

**Comment by Deprecator** [comment]
I mean we have the same approach with the Session class, why does Cookie behave differently?

**Comment by samdark** [comment]
Because session is a singleton i.e. there could not be two sessions while there could be multiple cookies.

**Comment by samdark** [comment]
See http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#practical-usage

**Comment by Deprecator** [comment]
Ah, my bad, I missed the singleton part. So the suggested solution for my issue would be applying the following code somewhere in beforeAction of my base web controller?

<code>
<pre>
Yii::$container->set('yii\web\Cookie', ['domain' => Yii::$app->params['cookie']['domain']]);
</pre>
</code>

And the following where there is a cookie operation required:

<code>
<pre>
$lang = 'en';
$cookie = Yii::$container->get('yii\web\Cookie');
Yii::configure($cookie, ['name' => 'lang', 'value' => $lang]);
Yii::$app->getResponse()->getCookies()->add($cookie);
</pre>
</code>

And the config part should be in a params-local.php:

<code>
<pre>
return [
    'cookie' => [
        'domain' => '.domain.zone'
    ]
];
</pre>
</code>

**Comment by samdark** [comment]
Yep.
