### ISSUE TITLE
Gridview pagination broken

### ISSUE THREAD

**Issue by badis** [yiisoft/yii2#10706]
When i have moved my website from My first hosting provider to Hostgator i get the following message for every instance of gridview :

Showing {begin, number}-{end, number} of {totalCount, number} {totalCount, plural, one{item} other{items}}

Is this related to a php extension ?

@cebe

**Comment by samdark** [comment]
Yes. You need intl.

**Comment by badis** [comment]
but it's already installed . Here are more informations : 
PHP - Version - 5.4.45: Ok!
PHP - GD Extension: Ok!
PHP - INTL Extension: Ok!
PHP - EXIF Extension: Ok!
PHP - Multibyte String Functions: Ok!
PHP - Curl Extension: Ok!
PHP - ZIP Extension: Ok!
LDAP Support: Warning! (Hint: Optional - Install PHP LDAP Extension and Zend LDAP Composer Package)
PHP - APC Support: Warning! (Hint: Optional - Install APC Extension for APC Caching)
PHP - SQLite3 Support: Ok!

**Comment by samdark** [comment]
What's ICU version?

**Comment by badis** [comment]
PHP version: 5.4.45
PHP OS: Linux
Language: en-US
Intl installed: yes
ICU version: 3.6
ICU data version: INTL_ICU_DATA_VERSION

**Comment by samdark** [comment]
That's too old. Try updating it.

**Comment by tlgtrn** [comment]
I have this line on top of table

    {totalCount, number} {totalCount, plural, one{öğenin} other{öğenin}} {begin, number}-{end, number} arası gösteriliyor.

It is in Turkish.

i18n config (basically) :
'language' => 'tr',
'i18n' => [
'translations' => [
'app' => [
'class' => 'yii\i18n\PhpMessageSource',
'basePath' => '../../common/messages',
'fileMap' => [
'app' => 'messages.php',
],
]
]
]

php int version:
version 1.1.0
ICU version 4.2.1

**Comment by samdark** [comment]
What's source language of your application?

**Comment by tlgtrn** [comment]
well, it was not set. at least I did not. but I add this line:
```
// set source language to be English
  'sourceLanguage' => 'en-US',
```
 and it is same problem again.

Obviously it is not a translation problem, I see Turkish words there bur format is the thing.

**Comment by samdark** [comment]
Well, it's either config or intl or ICU data.

**Comment by badis** [comment]
In my case, it has been resolved by upgrading :
PHP - INTL Extension - ICU
