### ISSUE TITLE
Model isAttributeChanged() function always return false but attributed was changed

### ISSUE THREAD

**Issue by tumdav** [yiisoft/yii2#10701]
``` php
 public function afterSave($insert, $changedAttributes)
    {
        if (!$insert) {
            var_dump($this->isAttributeChanged('start'));
            print_r($changedAttributes);
            print_r($this->start);
            die;
        }

        parent::afterSave($insert, $changedAttributes);
    }

<pre class='xdebug-var-dump' dir='ltr'>
    <small>boolean</small>
    <font color='#75507b'>false</font>
</pre>
Array
(
    [start] => 1459339199
)
1459339194

```

**Comment by tumdav** [comment]
Model int attributes always in list of $changedAttributes

**Comment by SilverFire** [comment]
Failed to reproduce on clean app template. Please, try to reproduce it on new clear installation and provide the exact steps to reproduce.

**Comment by tumdav** [comment]
When attribute type is int and I use model->load() function it gets request param as string and as a result it takes that att value was changed  e.g attr old value is 1 and from request model load is '1'

**Comment by samdark** [comment]
That's reverse of what you've reported initially. Everything that comes from forms is a string so you should configure `rules()` to typecast properly.

**Comment by tumdav** [comment]
I know and i configure it in rules.

``` php
    [['start', 'end', 'alert',], 'integer'],
```

**Comment by samdark** [comment]
So why it's still string?

**Comment by tumdav** [comment]
Because i get attributes from api request not from form.
```php
$model->load(Yii::$app->request->post());

**Comment by cebe** [comment]
integer validator does not cast, it will only check if string is numeric

**Comment by cebe** [comment]
if you want to cast to integer after validation, you can add a filter after the validator:

```php
    [['start', 'end', 'alert',], 'integer'],
    [['start', 'end', 'alert',], 'filter', 'filter' => 'intval'],
```

This wil call http://php.net/manual/en/function.intval.php on the value

**Comment by tumdav** [comment]
Ok it will work but why should we add filter when we define it as an integer?

**Comment by samdark** [comment]
Because in case of text field you may send `42` as a value and it should be text in this case, not number.

**Comment by tumdav** [comment]
Ok. Thanks a lot.
