### ISSUE TITLE
custom validation error messages is not hiding after correcting itsinput

### ISSUE THREAD

**Issue by vc7deo** [yiisoft/yii2#10700]
i have problem with custom validation its not hiding even after correcting the input but other regular validation is working fine.Also if we correct the input we can submit.please check my code below

            [['arrival_date','return_date'], 'date', 'format' => 'php:d-m-Y'],
            ['arrival_date','validateDates'],

            public function validateDates(){
              if(strtotime($this->return_date) <= strtotime($this->arrival_date)){
              $this->addError('arrival_date','Please give correct Start and End dates');
              $this->addError('return_date','Please give correct Start and End dates');
              }
           }

**Comment by SilverFire** [comment]
Do you have a problem with dependent field?
If you have error in both `arrival_date` and `return_date`, than change `arrival_date`, the error for this input disappears, but the error for `return_date` is still being displayed?

**Comment by vc7deo** [comment]
yes..i removed Yes i removed `arrival_date ` error but `return_date` error still showing.Also these error will display only when we click on the submit button.so user don't know whether they enter right input till the input button is submitted..

**Comment by SilverFire** [comment]
Partially duplicates #3987

You must trigger the second field validation manually

```js
    $('#arrival_date').update(function () {
        $(this).closest('form').yiiActiveForm('validateAttribute', 'return_date');
    });
```

**Comment by vc7deo** [comment]
still not working.. you can see it here

http://flywingzdestination.com/flywings/frontend/web/service/airticket

**Comment by vc7deo** [comment]
@ SilverFire ... did you check the issue?

**Comment by SilverFire** [comment]
I can't reproduce the error in your form.
