### ISSUE TITLE
Setting static variable in a constructor

### ISSUE THREAD

**Issue by mxkh** [yiisoft/yii2#10705]
Why i can't set static variable in a model constructor ?

My `Post` model has a `public static $truncateText = false;` and i want to set this variable in constructor like this

  
       `$model = new $this->modelClass([
            'scenario' => $this->scenario,
            'truncateText' => true,
        ]);

        return new ActiveDataProvider([
            'query' => $model::find()
                ->status()
                ->car($id)
                ->user(Yii::$app->user->identity->getId())
                ->hasComments()
                ->hasLikes(),
        ]);`

But i get the Exception
`Setting unknown property: frontend\modules\v1\models\post\Logbook::truncateText`

So, i trying to set it manually

        `$model = new $this->modelClass([
            'scenario' => $this->scenario,
        ]);
        $model::$truncateText = true;

        return new ActiveDataProvider([
            'query' => $model::find()
                ->status()
                ->car($id)
                ->user(Yii::$app->user->identity->getId())
                ->hasComments()
                ->hasLikes(),
        ]);`

And it works, of course, but in my opinion the installation of static properties in the constructor is much cleaner.

This is a small example to how to set the static property using `ReflectionClass`

`public function configure($config = [])
{
        $class = new \ReflectionClass(static::class);
        foreach ($config as $name => $value) {
            $class->setStaticPropertyValue($name, $value);
        }
    }`

**Comment by SilverFire** [comment]
Currently you must create your own setter in order to set static class property using `Yii::createObject`.

I guess is by design. Let's wait for other opinios.

**Comment by samdark** [comment]
Yes. It's by design.

**Comment by mxkh** [comment]
@samdark OK! My solution that helped me. Maybe it could be useful to someone
`/**
 * Class StaticConstructor
 * @package frontend\modules\v1\components
 */
trait StaticConstructor
{
    public function __set($name, $value)
    {
        if (array_key_exists($name, get_class_vars(static::class))) {
            $reflectionProperty = new \ReflectionProperty(static::class, $name);
            if ($reflectionProperty->isStatic()) {
                $reflection = new \ReflectionClass(static::class);
                $reflection->setStaticPropertyValue($name, $value);
            } else {
                parent::__set($name, $value);
            }
        } else {
            parent::__set($name, $value);
        }
    }
}`

` /**
  * @static @method Post __set()
 */
class Post extends ActiveRecord
{
    use PostTrait;
    use StaticConstructor;`

`/** @var Post $model */
        $model = new $this->modelClass([
            'scenario' => $this->scenario,
            'truncateText' => true, // static property that already defined in class
            'truncateTextCount' => 300, // static property that already defined in class
        ]);`

**Comment by klimov-paul** [comment]
> My solution that helped me. Maybe it could be useful to someone

Most obvious solution if you want to set static properties via `Yii::createObject()` is definition of the non-static setter for it:

```php
class Post extends ActiveRecord
{
    public static $truncateText = false;

    public fucntion setTruncateText($value)
    {
        $this->truncateText = $value;
    }
```

Although the issue overall does not make any sense.
