### ISSUE TITLE
Using custom date pattern for Message Formatting creates extra space

### ISSUE THREAD

**Issue by VojtechH** [yiisoft/yii2#10719]
When a custom date pattern is used for Message Formatting in a way [suggested in the i18n tutorial](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#date) an extra space is created.

The example in the tutorial looks like this:

`echo \Yii::t('app', 'Today is {0, date, yyyy-MM-dd}', time());`

The space preceding the "yyyy-MM-dd" pattern is taken as a part of the pattern.

This can be solved by either removing the preceding space in the example in the tutorial or by trimming the space if that's an intended behavior.

**Comment by SilverFire** [comment]
I believe it's a typo in docs. @samdark do you agree?

**Comment by samdark** [comment]
Yes.

**Comment by SilverFire** [comment]
Thank you, fixed

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/4d15aa06851d5b27c98c614204054f9454a5f754

**Comment by VojtechH** [comment]
Thank you for the quick fix.
