### ISSUE TITLE
ActiveRecord::find()->all() return array of empty object.

### ISSUE THREAD

**Issue by oraluben** [yiisoft/yii2#10714]
`User` is a class defined as `User extends ActiveRecord implements IdentityInterface`.
There are two records in `User` table, and I use `User::find()->all()` to query records.
The result is `[{}, {}]`.
I output log in `ActiveQuery::populate($rows)` and found that it is this method that return empty object for each record.
Am I in a wrong way using `ActiveRecord::find()`?

**Comment by SilverFire** [comment]
Failed to reproduce on basic Yii2 template.
How to reproduce it? Could you try the same on the clean installation?

**Comment by oraluben** [comment]
Sorry and I found why I get wrong result.
`ActiveQuery::all()` return an array of `ActiveRecord`, and `json_encode` will return {} for an `ActiveRecord`.
