### ISSUE TITLE
Feb 2016: Lets fix migrations!

### ISSUE THREAD

**Issue by df2** [yiisoft/yii2#10717]
@samdark @cebe @SilverFire @klimov-paul 
It seems that people are bringing up these issues individually and they all reference each other and all we have is a spiders web of disparate pull requests, none in any particularly complete state.

I'm talking about the missing migrations features:

->char()
->first()
->after()

A mon avis, we should also think about altering indexes: adding or dropping column[s], renaming indexes? 

Can we come up with a definitive list of what needs to be done and a timescale? When's the .7 release? Who is setting up database servers so all 6 sets of tests can be run?

Thanks,

Chris

**Comment by samdark** [comment]
There are already methods for managing columns and indexes.

The base set is done. The rest are the ones requested in separate issues. 2.0.7 release is going to happen when we'll deal with issues assigned to that milestone.

I think @cebe has setup for many DBMS. I personally can run tests for MySQL, SQLite, MSSQL.

**Comment by samdark** [comment]
Closing since it's meta-issue.

**Comment by df2** [comment]
@samdark Appreciate the reason to close this... That being said it seems appropriate to follow up here.

My mission the next 7 days is to use these guys (https://www.enciva.com/oracle-database-only.html) with a linode box w/ PHP7 and PECL OCI8. 

That will create an Oracle env. So I plan to at least be able to run the Oracle test suite by next Monday.

I will setup a 12c database. Is it sufficient if we can get tests passing with that version? Rel. #9617

**Comment by SilverFire** [comment]
@df2 I will be thankful for dealing with that issue. 
I have local OCI env, but some of OCI test are broken in master. 

> Is it sufficient if we can get tests passing with that version

Yes, it is. But it's not a quite easy task :) Feel free to contact me in PM

**Comment by df2** [comment]
@SilverFire You bet! Should, hopefully, just be a case of compiling the PECL library and linking it with the Oracle Client Library. 

> Why does db/oci/Schema not have a typemap? (#9617)

We'll find out.... will PM when we have made some progress...

**Comment by df2** [comment]
@SilverFire Making progress bro... whether it loads or not is to be seen still haha...
![2016-02-03-012118_1680x1024_scrot](https://cloud.githubusercontent.com/assets/1834925/12777891/7096f042-ca14-11e5-979f-03b80478aaa1.png)

**Comment by df2** [comment]
@SilverFire Seems to load :+1: 
```
# php -i | grep oci
oci8
oci8.connection_class => no value => no value
oci8.default_prefetch => 100 => 100
oci8.events => Off => Off
oci8.max_persistent => -1 => -1
oci8.old_oci_close_semantics => Off => Off
oci8.persistent_timeout => -1 => -1
oci8.ping_interval => 60 => 60
oci8.privileged_connect => Off => Off
oci8.statement_cache_size => 20 => 20
```

**Comment by SilverFire** [comment]
Great! You did it :) OCI installation for PHP is tricky

**Comment by df2** [comment]
Yeah, linking the client sdk was a head scratcher for a minute or two. I put the server in Newark and the Oracle server is in NY so there's a few ms latency. (Sound like HFT? lol)

Any gotchas you know of re OCI and yii\db going in?

**Comment by SilverFire** [comment]
Nothing special, as far as I know.

```
'dsn' => 'oci:dbname=//localhost:49161/xe',
```

(xe is a SID)
