### ISSUE TITLE
Infinite creation of folders if an asset accidentally sets $sourcePath = '@webroot/assets'

### ISSUE THREAD

**Issue by wallysalami** [yiisoft/yii2#10710]
One of our employees got a weird error when he used an asset like

```php
class MyBuggyAsset extends AssetBundle
{
    public $sourcePath = '@webroot/assets';
    ...
}
```

Yes, I know this is incorrect, but the effect is quite unpleasant. In some cases, Yii2 copies recursively all the assets again to the folder in assets. If `MyBuggyAsset`'s hash is `cccccc`, we get a directory tree like

- aaaaaa
- bbbbbb
- ccccccc
  - aaaaaa
  - bbbbbb
  - cccccc
    - aaaaaa
    - bbbbbb
    - ccccccc
      - ...

A simple fix would be adding a check in `BaseFileHelper`'s `copyDirectory`, to check if destination is a child of source.

```php
public static function copyDirectory($src, $dst, $options = [])
{
    if ($src === $dst || strpos($dst, $src) !== false){
        throw new \Exception( "Trying to copy a directory to itself or a subdirectory." );
    }

   ...
}
```

Can I make a pull request with that fix?

P.S. The Unix `cp`command has that "problem" as well.
P.S.S. In a funny coincidence, I read [this post on Reddit](https://www.reddit.com/r/tifu/comments/41l7qn/tifu_by_accidentally_creating_33_million_folders/) today.

**Comment by samdark** [comment]
Well, copying recursively is a bad idea :) If you have time, make a pull request. I can't promise to merge it though. Depends on how much it would clutter non edge case scenario.

**Comment by wallysalami** [comment]
Pull request: done! Thanks for the quick reply, as usual. Yii2 is pretty cool, and I'm glad to help a little.

Oh, by the way, @rotnes detected the bug.

**Comment by SamMousa** [comment]
Wouldn't it be good to also add a check to see if the assetPath is not a subdirectory if the webroot folder?
Since it never makes sense to publish already publicly available contents anyway?

**Comment by cebe** [comment]
if someone has the directory layout as it was the default in yii 1.1, e.g.

`@webroot = /var/www`
`@app = /var/www/protected`

and the app directory is protected by htaccess, it would still make sence. I'd not add such a restriction.

**Comment by samdark** [comment]
While recursive copying is definitely not valid, copying from web root is OK.

**Comment by klimov-paul** [comment]
Well. Actually I can not see any problem here.
There are plenty of possibiities to create an infinite loop in application. No wonder XDebug has 'xdebug.max_nesting_level' parameter.
There could be a lot of possible developer mistakes, which can lead to such situation.
I don't see a reason for any extra checks (which will impact performance more or less anyway) on this matter.
