### ISSUE TITLE
The format of Birthdate is invalid

### ISSUE THREAD

**Issue by plex19** [yiisoft/yii2#10713]
Hello,
I have a problem and I want to solve it, but tried and searched so long and it´s still there.
I followed the book yii2forbeginners until chapter 8, but I can´t finish it and create a profile
If I try to create one I type first and second name, gender, also birthdate, after I press create I get the message "The format of Birthdate is invalid".

**Comment by samdark** [comment]
Please ask book author. This issue tracker is about framework bugs.
