### ISSUE TITLE
Why yii\grid\ActionColumn use TwitterBootstrap dependent markup

### ISSUE THREAD

**Issue by eresik** [yiisoft/yii2#10712]
yii\grid\ActionColumn use TwitterBootstrap dependent markup by default.

It's not very good.

It turns out that you are not using the bootstrap, and the module uses ActionColumn, you have to take advantage of dependency injection for that would see the standard actions buttons.

https://github.com/yiisoft/yii2/blob/master/framework/grid/ActionColumn.php#L143
https://github.com/yiisoft/yii2/blob/master/framework/grid/ActionColumn.php#L153
https://github.com/yiisoft/yii2/blob/master/framework/grid/ActionColumn.php#L165

**Comment by samdark** [comment]
What do you propose to use instead of it?

**Comment by SilverFire** [comment]
I agree that it's not a good thing.
We can create an `ActionColumn` class in bootstrap extension and define those bootstrap-dependent buttons there.

**Comment by samdark** [comment]
@SilverFire OK but what do you propose to use for non-bootstrap buttons then? Also it would likely break existing apps.

**Comment by SilverFire** [comment]
Anyway it's a BC breaking change that goes to 2.1.
Non-bootstrap buttons will look ugly :)

**Comment by dynasource** [comment]
moving anything external out of the core software is always a good idea. 
If you do it right, why would it break BC?

Why not compare icons with the logic behind translations. 
Why not give create a default icon mapping and the user the option this "icon-mapping"

**Comment by samdark** [comment]
Because in existing apps bootstrap buttons would be replaced with something else on update.

**Comment by dynasource** [comment]
it wouldnt if you make the icon mapping dependant on the version of TWBS

**Comment by samdark** [comment]
How's that?

**Comment by dynasource** [comment]
you define:
- a core Icon class
- in every view, for every icon, you call this Icon class
- based on the 'icon library', you define its root
- based on the version of this library, you defined the path of the mapping file
- with every update of the Icon library, you refer to the correct mapping.

**Comment by samdark** [comment]
OK. Two questions:

1. What would it use if there's no bootstrap extension present?
2. How not to break compatibility to for existing users with bootstrap extension used?

**Comment by dynasource** [comment]
1) if no icon library is used, the base Icon class wont render an Icon
2) if you use TWBS for existing users
/web/Icon.php
/web/Icon::$libraryPath
/web/Icon::$version
/web/Icon::render('update')

and then a folder:
/web/icon/twbs/1_0.php
/web/icon/twbs/2_0.php
/web/icon/twbs/3_0.php

With ie. 2_0.php:

return [
  'update'=>'glyphicon-ok-2'
]
With ie. 3_0.php:

return [
  'update'=>'glyphicon-ok-circle'
]

**Comment by samdark** [comment]
How would Icon detect if twbs is installed?

**Comment by dynasource** [comment]
well, you provide a default path for the mapping file in Icon, like:
'@vendor/yiisoft/yii2-bootstrap/mapping.php

If the file does not exist, nothing is rendered.

You have to put a default somewhere, as you want to have a default theme anyways.

**Comment by samdark** [comment]
So for all existing apps there will be a need to specify additional path else icons will disappear. That's what I call backwards compatibility break.

**Comment by dynasource** [comment]
If people update to 2.0.7, they just like now:
- have a default reference to glyphicons, 
- except this is done centrally in /web/Icon.php by a connector-label, like 'update'
- if TWBS is installed, the corresponding icon will be shown
- if not installed, the connectorlabel will be shown

Nobody would have to get any issue.

**Comment by samdark** [comment]
Yes, that would solve it.

**Comment by samdark** [comment]
It's still BC breaking since the way of configuring it would change, right?

**Comment by dynasource** [comment]
whether you are a hardcoding it in the view with names like 'glyphicons' 
or using a mapping with 'connectors' wont change anything for current users, right?

**Comment by samdark** [comment]
Right.

**Comment by dynasource** [comment]
I have a solution ready. Will create a PR next week.

**Comment by samdark** [comment]
Won't be changed in 2.0.
