### ISSUE TITLE
$dataProvider->getModels(); Very slow event if there have many rows.

### ISSUE THREAD

**Issue by yoyhosoft** [yiisoft/yii2#10724]
Hi,
I found some issue that may impact performance,
here is my code that very slow when I run it's.

```
       $searchModel = new ItemsMainSearch();
       $dataProvider = $searchModel->search(Yii::$app->request->queryParams); 

	$modelList = $dataProvider->getModels();
	echo \yii\widgets\LinkPager::widget([
	   'pagination'=>$dataProvider->pagination,
	]);
```

After that I comment code at below, and speed comeback.
```
       $searchModel = new ItemsMainSearch();
       $dataProvider = $searchModel->search(Yii::$app->request->queryParams); 

	// $modelList = $dataProvider->getModels();
	echo \yii\widgets\LinkPager::widget([
	   'pagination'=>$dataProvider->pagination,
	]);
```

I not sure it's slow because $dataProvider->getModels() or not, so I test by using below code, and it's comeback to very slow again.
```
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => ....
?>
```

So, could you please check on this issue.

P.S. Totals rows after query about > 100,000 rows
P.S. Sorry for my English, because very I drunk Today.

**Comment by lynicidn** [comment]
ArrayDataProvider ?

**Comment by yoyhosoft** [comment]
ItemsMainSearch class is extends ItemsMain
ItemsMain class is extends \yii\mongodb\ActiveRecord

**Comment by lynicidn** [comment]
very small info
show method `search`

**Comment by yoyhosoft** [comment]
```
    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = ItemsMain::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere(['like', '_id', $this->_id])
            ->andFilterWhere(['like', 'simple_sku', $this->simple_sku])
            ->andFilterWhere(['like', 'product_name', $this->product_name])
            ->andFilterWhere(['like', 'sale_price', $this->sale_price])
            ->andFilterWhere(['like', 'discounted_price', $this->discounted_price])
            ->andFilterWhere(['like', 'discounted_percentage', $this->discounted_percentage])
            ->andFilterWhere(['like', 'currency', $this->currency])
            ->andFilterWhere(['like', 'category', $this->category])
            ->andFilterWhere(['like', 'picture_url', $this->picture_url])
            ->andFilterWhere(['like', 'brand', $this->brand])
            ->andFilterWhere(['like', 'create_time', $this->create_time])
            ->andFilterWhere(['like', 'update_time', $this->update_time]);

        return $dataProvider;
    }
```

**Comment by SilverFire** [comment]
Could you show the query, that was generated by Yii? Run this it directly in MongoDB. Show the timings, please.

I'm not tagging the issue with `ext:mongodb` label, because the conversation is already long here.

**Comment by yoyhosoft** [comment]
I will do loging the query Tonight.

One more thing I ever loging time in search function, it's not make query slow(with search paramiters/ or without out search paramiters),
but it's slow eventif I use ` $dataProvider->getModels()`.

P.S. I guess, maybe it's relate with memory allocation.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/data/ActiveDataProvider.php#L106
try configure pagination

**Comment by lichunqiang** [comment]
I think you should enhance your sql query performance.

**Comment by yoyhosoft** [comment]
I use default config (20  rows/page)

**Comment by SilverFire** [comment]
@yoyhosoft `like` is a very expensive operation, with your DB size it could take really much time.
So please, post the query and try to execute it directly in Mongo console.

**Comment by yoyhosoft** [comment]
@SilverFire I can remember that I ever test direct query to MongoDB console, it's took time less than 1.5s, however I will test again Tonight.

**Comment by dynasource** [comment]
This is not for the bug tracker, but slowness is completely logical looking at your SQL:
1) you are running a LIKE search on a medium large table 100.000
2) you are running many of the likes
3) perhabs you are also ordering.

Together this could result in a very long query, especially on non-indexed cols.

**Comment by samdark** [comment]
@dynasource it's MongoDB.

**Comment by yoyhosoft** [comment]
I will check query string that yii generate, it' may include search by including empty parameter.But when I use MongoDb console I search by one field like `db["itemsmain"].find({category:\Camera\})`

P.S. 'category' field is hache index

**Comment by samdark** [comment]
I've moved issue to mongo ext repo. Please continue discussion there.

**Comment by yoyhosoft** [comment]
Hi, @samdark
`search()` function return _yii\data\ActiveDataProvider_ object
`ActiveDataProvider extends BaseDataProvider`
and `getModels()` is in `BaseDataProvider`

and also I can't find `getModels()` inside yiisoft/yii2-mongodb ext.

So, could you please re-check again for this.

**Comment by lynicidn** [comment]
@yoyhosoft Issue moved to yiisoft/yii2-mongodb#82

**Comment by samdark** [comment]
The issue is about performance and it's connected with underlying engine, not with how data provider works,
