### ISSUE TITLE
AssetManager does not add the timestamp for manually registered files

### ISSUE THREAD

**Issue by m00nk** [yiisoft/yii2#10725]
In my config I have allowed to add the timestamps:

```
'assetManager' => [
	'appendTimestamp' => true, 
],
```
and the AssetManager adds the timestamp for the files I registered via AssetBundles. But if I register the files manually (like in the code below),  it does not:
 
```
$as = $this->assetManager->publish($widget->getViewPath().'/assets');
$this->registerJsFile($as.'/my_script.js');
```

**Comment by SilverFire** [comment]
It's by design: `appendTimestamp` is used only in `AssetManager::getAssetUrl()`, that works with bundles only.
I'd like to wait for opinion of my teammates.

**Comment by dynasource** [comment]
Currently the View is little bit inconsistent on this matter:
```php
    public function registerJsFile($url, $options = [], $key = null)
    {
        $url = Yii::getAlias($url);
        $key = $key ?: $url;
        $depends = ArrayHelper::remove($options, 'depends', []);

        if (empty($depends)) {
            $position = ArrayHelper::remove($options, 'position', self::POS_END);
            $this->jsFiles[$position][$key] = Html::jsFile($url, $options);
        } else {
            $this->getAssetManager()->bundles[$key] = new AssetBundle([
                'baseUrl' => '',
                'js' => [strncmp($url, '//', 2) === 0 ? $url : ltrim($url, '/')],
                'jsOptions' => $options,
                'depends' => (array) $depends,
            ]);
            $this->registerAssetBundle($key);
        }
    }
```

When you define a depend, you are using the AssetBundle, if not, it will use HTML.
For an optimal scenario, behavior is the same, so that AssetBundle is used at all times.

Till that time, the workaround is to append a timing yourself, which seems to be possible.

**Comment by samdark** [comment]
According to the code timestamps should be added. I think what you're experiencing is with line 318 of `AssetManager`:

```php
public function getAssetUrl($bundle, $asset)
{
    // ...

    if ($this->appendTimestamp && ($timestamp = @filemtime("$basePath/$asset")) > 0) {
        return "$baseUrl/$asset?v=$timestamp";
    } else {
        return "$baseUrl/$asset";
    }
```

The `$timestamp = @filemtime("$basePath/$asset")) > 0` condition gives false since asset was just published and file was just copied. It means there's no sense to add timestamp. In case you'll run the same code and file won't be copied (not modified) you may get timestamp.

**Comment by dynasource** [comment]
he is using View::registerJsFile(), doesnt look that it goes through AssetManager?

**Comment by samdark** [comment]
Oh, right.

**Comment by klimov-paul** [comment]
`AssetManager` can not affect `View::registerJsFile()` method, and its configuration does not covers it.
This is exoected behavior.

**Comment by vsokolov525** [comment]
In order to use View::registerJsFile() and appendTimestamp I changed View::registerJsFile() in next way:

$this->getAssetManager()->bundles[$key] = new AssetBundle([
    'baseUrl' => '',
    'js' => [strncmp($url, '//', 2) === 0 ? $url : ltrim($url, '/')],
    'jsOptions' => $options,
    'depends' => (array) $depends,
	'basePath' => (strpos($url, '/js') === 0 ? Yii::getAlias('@webroot') : null)
]);

All my js-files are in @webroot/js folder.

**Comment by cronfy** [comment]
For those who is interested in (temporary?) solution:

Instead of `registerJsFile()` we can create new AssetBundle on the fly. Replace `$this->registerJsFile($file)` in your view with this code:

```
$file = '/js/page.js';
$asset = new \yii\web\AssetBundle([
    'js' => [ltrim($file, '/')],
    'basePath' => '@webroot',
    'baseUrl' => '/'
]);
$this->getAssetManager()->bundles[$file] = $asset;
$this->registerAssetBundle($file);
```
