### ISSUE TITLE
andWhere() does not append two andWhere conditions correctly

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#10732]
I do query the ActiveRecord User Model as following:

Query:

```php
User::find()->where(['mail' => 'foo@bar.com'])->andWhere(['<=', 'valid_from_timestamp', time()])->andWhere(['>=', 'valid_to_timestamp', time()])->one();
```

Expect:
```sql
SELECT * FROM `user` WHERE ((`mail`='foo@bar.com') AND (`valid_from_timestamp` <= 1454418201) AND (`valid_to_timestamp` >= 1454418201))
```

Result:
```sql
SELECT * FROM `user` WHERE ((`mail`='foo@bar.com') AND (`valid_from_timestamp` <= 1454418201)) AND (`valid_to_timestamp` >= 1454418201)
```

As you can see the last andWhere does not get capsulatet correctly in to the first where condition. I got the statement from the yii2-debug database profiler.

Env:
Yii-Version: 2.0.6

**Comment by SilverFire** [comment]
It's by design.

Use [Hash format](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#hash-format) or [and operator](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#operator-format)

**Comment by nadar** [comment]
Ok. But for what then is the `andWhere()` method good, to apply only 1 (one) and condition?

**Comment by SilverFire** [comment]
It works like this:

```
1
1 & 1
(1 & 1) & 1
((1 & 1) & 1) & 1
```

**Comment by nadar** [comment]
Ok, got it. This should probably be written in the docs somewhere.
