### ISSUE TITLE
PrettyUrl accepts unlimited slashes allowing /route//////

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#10739]
based on https://github.com/yiisoft/yii2/pull/10733#discussion_r51703531

It seems that slashes can be appended in the URL, without issues.
This means that the following urls render correctly:

http://localhost/dmn/yii-application/frontend/web/index.php/site/about
http://localhost/dmn/yii-application/frontend/web/index.php/site/about/////
or
http://localhost/dmn/yii-application/frontend/web/index.php/site/about/////////////////

All returning the same page.

This can be reproduced by installing i.e. the Advanced App with setting:
```php
   'urlManager'=>[
        'class'=>'yii\web\UrlManager',
        'enablePrettyUrl' => true,            
    ]
```

**Comment by andrewnester** [comment]
Verified. It accepts multiple slashes at the end of URL

**Comment by andrewnester** [comment]
Just added PR that fixes issue - if we have multiple slashes at the end of URL it should be handled as invalid URL

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/e8a7a8a0f4e86e3a374cf273fc6cbbbbfd214dfe
