### ISSUE TITLE
Query Builder: add custom command 'afterFrom'

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2#10730]
I haven't found a good way to add database's custom commands keeping the db/Query logic.
For example, hierarchical query in Oracle would contain :
```
START WITH idcompany = :idcompany
CONNECT BY prior idcompany = idcompany_parent
````
Adding a new method 'afterFrom' to db/query may be useful, so that it would be possible to write:
```
$query->select('*')
           ->from('company')
           ->afterFrom( 'START WITH idcompany = :idcompany
                         CONNECT BY prior idcompany = idcompany_parent' )
           ->addParams( [':idcompany' => $idcompany] );
```
So that it would also be working with db/Query and db/ActiveRecord.
Maybe there is already a way to do it?

**Comment by klimov-paul** [comment]
Specific SQL constructions will not be supported - there too many possible places fro them to appear.
You can still use `Query` object while building cutsom SQL expressions:

```
$query = new Query();
// ...
$db = Yii::$app->getDb();
list ($sql, $params) = $db->getQueryBuilder()->build($query);
```

**Comment by CedricYii** [comment]
Thanks for the hint.
However I can't understand the way you are thinking to customize the query. Maybe by replacing keyword in the sql generated? But this would mean to do it once at the end of building process, which won't always be possible easily.
My exemple was an activeQuery but my main concern is to use it for activeRecords with many relations and eagerLoading.

Thanks to your suggestion, I guess I can extend the  yii\db\QueryBuilder::build() method.
Basically, there are "only" 5 main places for them to appear:
````php
public function build($query, $params = [])
    {
...
        $clauses = [
            $this->buildBeforeSelect($query->beforeSelect, $params),
            $this->buildSelect($query->select, $params, $query->distinct, $query->selectOption),
            $this->buildBeforeFrom($query->beforeFrom, $params),
            $this->buildFrom($query->from, $params),
            $this->buildBeforeJoin($query->beforeJoin, $params),
            $this->buildJoin($query->join, $params),
            $this->buildBeforeWhere($query->beforeWhere, $params),
            $this->buildWhere($query->where, $params),
            $this->buildBeforeGroupBy($query->beforeGroupBy, $params),
            $this->buildGroupBy($query->groupBy),
            $this->buildHaving($query->having, $params),
        ];
...
    }
````

**Comment by cebe** [comment]
@CedricYii does this solve your problem? https://github.com/yiisoft/yii2/issues/10869#issuecomment-184856367

**Comment by CedricYii** [comment]
@cebe Thanks for pointing this out as I haven't tought of your yii\db\Expression idea.
However this would not really help for the hierarchical query that is supposed to be defined by the root object (gives permissions to see all objects of user's compagnies under its hierarchy): I can't attach this query part by an expression to a particular 'tableName', as it could receive join tables afterwards (which is not allowed). So as far as I know the only place accepted by Oracle is between the last join and the where clause (ie beforeWhere).

**Comment by fdezmc** [comment]
I am agree with @CedricYii. 
Expression is not enough to customize the query in activeRecords with many relations and eagerLoading either. [#11807 (comment)](https://github.com/yiisoft/yii2/issues/11807#issuecomment-229199407)
@CedricYii solution, could handler my needs of hint index in mysql. Adding this kinds of hooks, allow to define the specific functionality for each driver in its specific deriver class:

- yii\db\cubric\QueryBuilder.php
- yii\db\mssql\QueryBuilder.php
- yii\db\mysql\QueryBuilder.php
- yii\db\oci\QueryBuilder.php
- yii\db\pgsql\QueryBuilder.php
- yii\db\sqlite\QueryBuilder.php
