### ISSUE TITLE
Url Manager

### ISSUE THREAD

**Issue by Leffka** [yiisoft/yii2#10734]
Hello all.
Install yii2 basic from composer.

in config/web.php add
`'urlManager' => [
            'class' => 'yii\web\urlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
],`

in /web/ create file .htaccess and add

AddDefaultCharset utf-8
Options +FollowSymLinks
IndexIgnore */*
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php

don't work `'showScriptName' => false`
in url: http://bapp.local/site/index
on page: The requested URL /site/index was not found on this server.

**Comment by samdark** [comment]
Please use forums for asking configuration questions. GitHub is for bugs.
