### ISSUE TITLE
Change private attribute yii\base\Theme $_baseUrl to protected $_baseUrl

### ISSUE THREAD

**Issue by ustmaestro** [yiisoft/yii2#10741]
This change is caused by fallowing situation described in example and if we need more manipulation with theme $_baseUrl in child classes.
In my case $this->theme->getBaseUrl(true) need to return absolute url to theme folder, i try to extend yii\Base\Theme to change getBaseUrl() function to return the absolute url, used in email layouts and templates for images, css, etc... 
Example:

In my app config

        'view' => [
            'theme' => [
                'class' => 'frontend\components\AppTheme',
                'pathMap' => [
                    '@app/views' => [
                        '@app/themes/mythemename/views',
                    ]
                ],
                'basePath' => '@app/themes/mythemename',
                'baseUrl' => '@web/themes/mythemename',
            ],
        ],

In my frontend\components\AppTheme.php

        <?php
        namespace frontend\components;

        use yii\helpers\Url;

        class AppTheme extends \yii\base\Theme
        {
           // private $_baseUrl;

            /**
             * @return string the base URL (without ending slash) for this theme. All resources of this theme are considered
             * to be under this base URL. $scheme true|false - absolute or relative URL
             * Absolute URL is used in email templates
             */
            public function getBaseUrl($scheme = false)
            {
                if($scheme) {
                    return rtrim(Url::home(true),'/') .'/'. ltrim($this->_baseUrl, '/');
                } else {
                    return $this->_baseUrl;
                }
            }
        }

**Comment by kidol** [comment]
You can override like this instead:

```php
public function getBaseUrl($scheme = false)
{
   $baseUrl = parent::getBaseUrl();
   return $scheme ? (rtrim(Url::home(true),'/') .'/'. ltrim($baseUrl, '/')) : $baseUrl
}
```

**Comment by dynasource** [comment]
_baseUrl is set by setBaseUrl and should be private. Setting it to protected will confuse logic. If you want to extend, you can use the central functions like kidol suggests.

**Comment by ustmaestro** [comment]
If anyone is interested my finnaly theme class frontend\components\AppTheme.php looks

    <?php
    namespace frontend\components;
    
    use yii\helpers\Url;
    
    class AppTheme extends \yii\base\Theme
    {
        /**
         * @inheritdoc
         */
        public function getBaseUrl($scheme = false)
        {
            return ($scheme) ? rtrim(Url::to(parent::getBaseUrl(),true),'/') : parent::getBaseUrl();
        }
    }
