### ISSUE TITLE
Not all assets are downloaded in a multi-server environment

### ISSUE THREAD

**Issue by adamwinn** [yiisoft/yii2#10744]
We deploy our code in a multi-server load-balanced environment.  Right after we deploy our code, the asset folders are blank and yii will download the assets on-demand if they are missing.  The issue is that when the first page is viewed post-deploy, about half the assets are loaded on server1 and half the assets are loaded on server2.  Therefore, when you first view the site, multiple CSS and JS asset files are missing and it takes a couple page refreshes until all of the assets are loaded onto server1 or server2.

Below is my AssetBundle code.  How can I get yii2 to download all of the assets to server1 or server2 upon the first page view instead of half of the assets going to server1 and half going to server2?  Do we need to enable sticky sessions or some other method?

What I'd like to have happen is if I go to the site and I land on server1, all of the assets would then be loaded onto server1 and the site would be functional without missing asset files.  Then if another person views the site and lands on server2, they would have all the asset files loaded onto server2.  Right now some assets are be loaded onto server1 and the rest are being loaded onto server2, so required CSS and JS files are missing.

```php
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/site.css',
    ];
    public $js = [
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'kartik\grid\GridViewAsset',
        'kartik\dynagrid\DynaGridAsset',
        'kartik\sortable\SortableAsset',
        'kartik\select2\Select2Asset',
        'kartik\form\ActiveFormAsset',
        'kartik\base\WidgetAsset',
        'kartik\base\AnimateAsset',
        'kartik\dropdown\DropdownXAsset',
    ];
}
```

**Comment by klimov-paul** [comment]
Duplicates #7441
