### ISSUE TITLE
Yii::$app->controller changes when I call Yii::$app->runAction() 

### ISSUE THREAD

**Issue by vtvz** [yiisoft/yii2#10752]
When I call runAction somewhere (another controller, view), Yii::$app->controller changes to last controller called by runAction. I thought Yii::$app->controller contains main controller, what created in start of program. For example, I request "?r=site/index" and Yii::$app->controller contains always SiteController instance, no matter call I runAction or not. Is it feature or bug? And how can I get access to main controller?

Version of framework 2.0.6

P.S. Sorry for my bad English

**Comment by klimov-paul** [comment]
This is expected behavior.
