### ISSUE TITLE
Link model with two relations

### ISSUE THREAD

**Issue by xfg** [yiisoft/yii2#10758]
Hi. I have model with two relations
```
class Model extends \yii\db\ActiveRecord
{
  public function getFirst()
  {
    return $this->hasOne(First::className(), ['id' => 'first_id']);
  }

  public function getSecond()
  {
    return $this->hasOne(Second::className(), ['id' => 'second_id']);
  }
}
```

Now I want to save this model. I do so

```
$model = new Model;
$model->setAttributes([...]);
$model->link('first', $firstModel);
$model->link('second', $secondModel);
```
But I get the constraint violation error in MySQL, because the link method tries to save model after [first call](https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1439). How to solve this problem ?

Thanks.

**Comment by dynasource** [comment]
can you supply more information about this constraint violation error?

**Comment by xfg** [comment]
@dynasource, yes, sure. My mysql table have two foreign keys. In my code I want to save new record to mysql table. I try to link my model with relations through the link method, but the link method saves the record to database after first call. Thus only first foreign key is satisfied, but second foreign key not.

That is I can save the model only with one foreign key. If the foreign keys more than one, then the link method does not solves this problem.

**Comment by dynasource** [comment]
I see. Well, the current implementation of link() does not support your usecase. Its just for linking 2 models. If you want to link more models, than you have to write your own script, without using link()

**Comment by xfg** [comment]
@dynasource thanks for answer. Is it possible to offer this improvement to yii core team? I am hardly able to do it, because my level written english is very bad.
