### ISSUE TITLE
assetManager's forceCopy with appendTimestamp breaks Pjax

### ISSUE THREAD

**Issue by itnelo** [yiisoft/yii2#10759]
> $ php yii
> This is Yii version 2.0.6.

I use this configuration for assetManager in my dev environment:

```
'assetManager' => [
    'appendTimestamp' => true,
    'forceCopy' => true,
],
```

Before I realized where was a problem, errors like that appears:

![screen shot 2016-02-05 at 13 04 52](https://cloud.githubusercontent.com/assets/2988715/12843243/19fe8e74-cc09-11e5-9520-3852e12aff17.png)

I think it happens if javascript assets will change after force publish according to params $forceCopy and $appendTimestamp. Does information about this conflict exists in documentation, maybe I missed something about pjax config?

Should I stop using this configuration of assetsManager or problem just in incorrect pjax using?

My view, btw:

```
<?php

use ...

/**
 * @var View $this
 * @var ActiveDataProvider $dataProvider
 * @var UserSearch $searchModel
 */

$this->title = Yii::t('user', 'Manage users');
unset($this->params['breadcrumbs']['module']['url']);

UsersAsset::register($this);
?>

<?= $this->render('/_alert', [
    'module' => Yii::$app->getModule(ModuleHelper::USERS),
]) ?>

<?= $this->render('/_menu') ?>

<div class="users-admin-workspace">
    <?php Pjax::begin() ?>

    <?= GridView::widget([
        'dataProvider' 	=> $dataProvider,
        'filterModel'  	=> $searchModel,
        'layout'  		=> "{items}\n{pager}",
        'tableOptions' => ['class' => 'table table-striped'],
        'columns' => ...
    ]); ?>

    <?php Pjax::end() ?>
</div>

```

Pjax response example:

```
<title>Manage users</title>
    <div id="w3" class="grid-view"><table class="table table-striped"><thead>
<tr><th><a href="/project_name/admin/users?UserSearch%5Busername%5D=&amp;UserSearch%5Bemail%5D=in&amp;UserSearch%5Bregistration_ip%5D=&amp;UserSearch%5Bcreated_at%5D=&amp;_pjax=%23w2&amp;sort=username" data-sort="username">Username</a></th><th><a href="/project_name/admin/users?UserSearch%5Busername%5D=&amp;UserSearch%5Bemail%5D=in&amp;UserSearch%5Bregistration_ip%5D=&amp;UserSearch%5Bcreated_at%5D=&amp;_pjax=%23w2&amp;sort=email" data-sort="email">Email</a></th><th><a href="/project_name/admin/users?UserSearch%5Busername%5D=&amp;UserSearch%5Bemail%5D=in&amp;UserSearch%5Bregistration_ip%5D=&amp;UserSearch%5Bcreated_at%5D=&amp;_pjax=%23w2&amp;sort=registration_ip" data-sort="registration_ip">Registration ip</a></th><th><a href="/project_name/admin/users?UserSearch%5Busername%5D=&amp;UserSearch%5Bemail%5D=in&amp;UserSearch%5Bregistration_ip%5D=&amp;UserSearch%5Bcreated_at%5D=&amp;_pjax=%23w2&amp;sort=created_at" data-sort="created_at">Registration time</a></th><th>Confirmation</th><th>Block status</th><th>&nbsp;</th></tr><tr id="w3-filters" class="filters"><td><input type="text" class="form-control" name="UserSearch[username]" value=""></td><td><input type="text" class="form-control" name="UserSearch[email]" value="in"></td><td><input type="text" class="form-control" name="UserSearch[registration_ip]" value=""></td><td><input type="text" id="usersearch-created_at" class="form-control" name="UserSearch[created_at]">
</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
</thead>
<tbody>
<tr><td colspan="7"><div class="empty">No results found.</div></td></tr>
</tbody></table>
</div>
    <script src="/project_name/assets/d05994ed/jquery.js?v=1454663051"></script>
<script src="/project_name/assets/efa3b273/jquery-ui.js?v=1454663051"></script>
<script src="/project_name/assets/efa3b273/ui/i18n/datepicker-ru.js?v=1454663051"></script>
<script src="/project_name/assets/76a163db/yii.js?v=1454663051"></script>
<script src="/project_name/assets/76a163db/yii.gridView.js?v=1454663051"></script>
<script type="text/javascript">$('#usersearch-created_at').datepicker($.extend({}, $.datepicker.regional['ru-RU'], {"dateFormat":"yy-mm-dd"}));
jQuery('#w3').yiiGridView({"filterUrl":"\/project_name\/admin\/users?UserSearch%5Busername%5D=\u0026UserSearch%5Bemail%5D=in\u0026UserSearch%5Bregistration_ip%5D=\u0026UserSearch%5Bcreated_at%5D=\u0026_pjax=%23w2\u0026_pjax=%23w2","filterSelector":"#w3-filters input, #w3-filters select"});</script>
```

**Comment by dynasource** [comment]
does it work when you use an ID in the Pjax Widget?

**Comment by itnelo** [comment]
Change from
`<?php Pjax::begin() ?>`
to
`<?php Pjax::begin(['id' => 'my_unique_widget']) ?>`
causes no effect.

Without assetsManager's property ['forceCopy' => false] all works normally (without pjax widget 'id' too)

**Comment by dynasource** [comment]
well, in your pjax response I see sorting references to _pjax=#w2 while the gridview has id 'w3'

is your call actually being done by pjax? I dont see a PJAX call in your console trace

**Comment by itnelo** [comment]
yes, but it seems like pjax use jquery selector of parent html element for his sorting logic, i.e.

```
<div id="w2">
     response here (<div id="w3" class="grid-view"> ... </div>)
</div>
```

with `<?php Pjax::begin(['id' => 'my_unique_widget']) ?>` string which you noticed will become:
_pjax=#my_unique_widget

and... error repeats

**Comment by dynasource** [comment]
what does your Pjax Jquery script look like (see bottom page)

**Comment by itnelo** [comment]
```
<script type="text/javascript">jQuery(document).ready(function () {
$('#usersearch-created_at').datepicker($.extend({}, $.datepicker.regional['ru-RU'], {"dateFormat":"yy-mm-dd"}));
jQuery('#w3').yiiGridView({"filterUrl":"\/project_name\/admin\/users","filterSelector":"#w3-filters input, #w3-filters select"});
jQuery(document).pjax("#w2 a", "#w2", {"push":true,"replace":false,"timeout":1000,"scrollTo":false});
jQuery(document).on('submit', "#w2 form[data-pjax]", function (event) {jQuery.pjax.submit(event, '#w2', {"push":true,"replace":false,"timeout":1000,"scrollTo":false});});
});</script>
```

**Comment by dynasource** [comment]
- is your jquery.pjax.js actually loaded?
- whats happens if you remove the datepicker() script
- can you reproduce this issue within a clean 2.0.6 app?
- and in the 2.0.7-master?

**Comment by itnelo** [comment]
> $ composer create-project --prefer-dist yiisoft/yii2-app-basic basic

In clean 2.0.6 problem exists: https://github.com/itnelo/yii2-issue-10759

Files added/edited:
- config/web.php (lines 10-13)
- controllers/SiteController.php
- models/SearchForm.php
- views/site/index.php (lines 22-32)

**Comment by dynasource** [comment]
I will have a look

**Comment by dynasource** [comment]
I confirm this is a bug https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L810

Because of different versioning appendings to the JS files, the Pjax will load JS files twice. This results into a javascript error when using the form again. 

The Pjax JS script must be updated to either:
- ignore the version appending when comparing strings
- or take the new scripts and remove the old ones from the page.

**Comment by SilverFire** [comment]
Sorry for a late reply, but this issue probably will not be fixed.

Unfortunately It's impossible to unload old scripts.
I don't want to introduce any special code that will change behavior depending on some URL parameters because it's unstable thing.

@yiisoft/core-developers @nkovacs could you give your thoughts on this, please?

**Comment by SilverFire** [comment]
Usually it's not necessary to append timestamps on production. You can enable `forceCopy` or `linkAssets` in AssetManager during the development.

**Comment by dynasource** [comment]
well, I dont see a big deal in changing the Pjax script to ignore the version paramater. After all, its the current page that the user sees. Why import a newer script. It more logical to do that with a full page refresh.

**Comment by klimov-paul** [comment]
This can not fixed anyhow.
`AssetManager` does it job appending timestamp attribute as requested, while `Pjax` tracks the new JS URLs.
The oly solution is enhance the `Pjax` to parse JS / CSS URL and strip query param, but this will break assets, which are composed based on query param.
There is no solution.
This issue is just a developer overhead - it will not appear in normal cercumstances on production server.

**Comment by dynasource** [comment]
I disagree. Why would Pjax import the same script twice in the first place.

**Comment by nkovacs** [comment]
The whole page should be reloaded if something like this happens. If you ignore the version parameter, you get a page with html that needs the new version of the script, but the browser will have the old version of the script
Pjax has a feature to do this in these cases: https://github.com/defunkt/jquery-pjax#layout-reloading

**Comment by dynasource** [comment]
a reload will mean that pjax won't work at all in a appendTimestamp scenario, as version strings are always different.

**Comment by SilverFire** [comment]
Thank you for your replies.

I tag this issue as `wontfix` for the following reasons:

 - It's not a normal situation for the production server. On the dev-server it can be solved using `forceCopy` or `linkAssets` properties of AssetManager.
 - It's not possible to unsee the seen, so it's not possible to unload the loaded :)
 - We won't add any special logic to pjax that will ignore timestamp, because adding timestamp to ignore it makes no sense.

**Comment by dynasource** [comment]
I disagree with closing this one. At least the JS errors caused by default Yii scripts should be solved. Perhabs its because of Yii.js. You should take a look at the example App of @itnelo https://github.com/itnelo/yii2-issue-10759

**Comment by SilverFire** [comment]
> I disagree with closing this one. At least the JS errors caused by default Yii scripts should be solved.

The error are caused because the code that must be present on the page in single instance. Instead it is loaded twice.

Using PHP include the same file with the class twice and you will get error. It's a kind of that.

**Comment by dynasource** [comment]
could there be a solution in which double loading the class, won't result into JS errors?

**Comment by SilverFire** [comment]
It doesn't matter. Even if we'll fix it for Yii2-core JS assets, it will not affect thousands of other JS plugins from all over the world

**Comment by dynasource** [comment]
well, Ill stop arguing ;), but still I think there is something wrong with the fact that users can bump into a problem like this, wasting hours on searching for a reason why their Pjax isnt working. 

IMHO, the core must be perfect, even for rare (and perhabs odd) combination of settings like the given example of appendTimestamp & forceAssets. Unless this is already documented of course.

**Comment by SilverFire** [comment]
@dynasource agree. We are constantly working on Yii2 polishing with a great help of community :+1: 

Currently we have 800+ issues and it will be great to solve all of them, so there is still a long way to go. 
Thank you for your help!
