### ISSUE TITLE
Sum with condition on ActiveQuery Select

### ISSUE THREAD

**Issue by mata-man** [yiisoft/yii2#10755]
When using `SUM` with a condition like `IF` on the select method of activequery it generates incorrect SQL.

```
Model::find()->select('sum(if(my_field = 20, 1, 0))')
``` 
Will result in the following select statement to be generated 
```
Select SUM(IF(`my_field`, `1`,`0))` FROM TABLE
```
The current work around is to use the `AddSelect()` method

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/yii-db-query.html#select%28%29-detail
> Note that if you are selecting an expression like CONCAT(first_name, ' ', last_name), you should use an array to specify the columns.
