### ISSUE TITLE
Pjax fail to prevent replace state, on form submit

### ISSUE THREAD

**Issue by hscstudio** [yiisoft/yii2#10756]
I use pjax for form submit
```php
<?php $form = ActiveForm::begin([
        'options' => [
            'data-pjax' => true,
        ],
    ]); ?>
....
```

Only it, and pjax submit running well.

But, then I want to prevent replace state, with add parameter data-pjax-replace-state
```php
<?php $form = ActiveForm::begin([
        'options' => [
            'data-pjax' => true,
            'data-pjax-replace-state' => false,
        ],
    ]); ?>
...
```
But this way not prevent replace state. URL still replace with pjax.

**Comment by samdark** [comment]
Have you tried code from master branch?

**Comment by hscstudio** [comment]
Yes, sure

**Comment by SilverFire** [comment]
Why do you think, that `pjax` handles `data-pjax-replace-state` attribute of the form?

**Comment by hscstudio** [comment]
I only read in source

[https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L153](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L153)

**Comment by SilverFire** [comment]
It's not about the forms, it's about links with `data-method`

**Comment by SilverFire** [comment]
You must set [Pjax::enablePushState](http://www.yiiframework.com/doc-2.0/yii-widgets-pjax.html#$enablePushState-detail) and enableReplaceState
