### ISSUE TITLE
Empty changedAttributes in behavior after using updateCounters for model

### ISSUE THREAD

**Issue by bobahvas** [yiisoft/yii2#10750]
Controller

    use yii\web\Controller;

    class TestController extends Controller {

        public function actionTest() {
            $model = TestModel::findOne(1);
            $model->updateCounters(['test_counter' => 1]);
            $model->save();
        }

    }

Model

    use yii\db\ActiveRecord;
    
    class TestModel extends ActiveRecord {
        public function behaviors() {
            return [
                [
                    'class' => TestBehavior::className()
                ]
            ];
        }
    }

Behavior
    
    class TestBehavior extends Behavior {

        const TYPE_INSERT = 'insert';
        const TYPE_UPDATE = 'update';
        const TYPE_DELETE = 'delete';

        public function events() {
            return [
                BaseActiveRecord::EVENT_AFTER_UPDATE => 'afterUpdate'
            ];
        }

        public function afterUpdate($event) {
            var_dump($event->changedAttributes);
        }
    }

So, var dump will be empty.

**Comment by dynasource** [comment]
Your confusion is understandable because of your code. You are executing a database command twice.

First in 'updateCounters' and then in 'save' (which is not necessary)
The save command is actually calling the Event and its empty, because the update has already been done.

If you want to make use of the behavior for the changeAttributes, make sure you are using the save() or update() methods

**Comment by bobahvas** [comment]
ok, thank you.

But in your guide http://www.yiiframework.com/doc-2.0/guide-db-active-record.html

> Note: If you use yii\db\ActiveRecord::save() to update a counter column, you may end up with inaccurate result, because it is likely the same counter is being saved by multiple requests which read and write the same counter value.

And i want to update counter. And i also want to get changed attribute in my behavior, because it changed.

How can a do it?

So, I think it is a bug.

**Comment by samdark** [comment]
It's about the following approach:

```php
$model = TestModel::findOne(1);
$model->test_counter++;
$model->save();
```

**Comment by bobahvas** [comment]
If I will use the following approach result can be wrong.
It is written in your documentation.

I quoted part of your documentation.

> Note: If you use yii\db\ActiveRecord::save() to update a counter column, you may end up with inaccurate result, because it is likely the same counter is being saved by multiple requests which read and write the same counter value.

**Comment by samdark** [comment]
That's true cause it's not atomic. In order to atomic `updateCounters` does update right away so:

1. Calling `save()` isn't needed.
2. Attributes are updated immediately so you won't get anything changed.

That's all expected.

**Comment by bobahvas** [comment]
@samdark, I don't understand.
I have behavior, that start working on after update. That mean, that $model change any attributes. I must watch changed attributes and if my counter was changed - push to redis (for an example).

    $model = TestModel::findOne(1);

    var_dump($model->test_counter);

    $model->updateCounters(['test_counter' => 1]);

    var_dump($model->test_counter);

I see that `test_counter` changed in `$model` object, also i see changes in DB. I think, that behavior should start working after that moment (after saving).

**Comment by dynasource** [comment]
that seems like a valid usecase, to have an Event fired after the counter reaches a specific number. Till that time, you can fire the event yourself by using $model->afterSave()
