### ISSUE TITLE
Session is not started automatically when getting session id

### ISSUE THREAD

**Issue by tahirm** [yiisoft/yii2#10763]
If we try to get session id before setting or getting any property in session, session is not started automatically. For example in following code:
````
php
$session = Yii::$app->session;
$sessionId = $session->id;
````
In above code `$sessionId` is empty because session is not started already.
To fix it, we just need to add `$this->open()` in `getId()`function of `yii\web\Session` like following:
````php
public function getId()
{
    $this->open();
    return session_id();
}
````
If all we need is above change then I can fix it and make a pull request. I just need confirmation that this is the only place where I need to make changes.

**Comment by samdark** [comment]
It is expected that session isn't started if it's not needed. ID gives current session ID which is empty in case session isn't there. I'm against changing this behavior.

**Comment by SilverFire** [comment]
I'm pretty sure that it will break our internal or someone's custom logic. The following code will not work anymore:

```php
if (Yii::$app->session->id === null) {
   echo 'Yay, there is no session id';
}
```
