### ISSUE TITLE
Doc update about coding standard for the order of properties of 1 type

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#10767]
I was looking for a coding standard for ordering public properties. I couldnt find something on this subject at https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#42-properties

Perhabs this is something to elaborate and to put in the standards. Currently I am trying to make a choice out of the following 6 options:
- required ordering
- alphabetic ordering
- most used ordering
- similarity/group ordering
- type cast ordering 
- random ordering

Which one (and perhabs a combination) is to be used and should be put in the coding style doc?

**Comment by cebe** [comment]
> similarity/group ordering

This is what is mostly used as related properties are put together. alphabetic ordering makes no sense as IDE navigation will bring you to the property you need in most cases. "most used" is hard to guess.
I also do not see a reason for ordering by type .

**Comment by dynasource** [comment]
> similarity/group ordering

if this is chosen, perhabs there is some order for these groups too. Plus an ordering within a group. 

For instance:
- Step 1: Create groups of related properties 
- Step 2: Order these groups on class hierarchy. First the properties meant for the current __CLASS__, then the properties for subclasses.
- Options step 3: Within these groups, order these properties on alfabet

**Comment by klimov-paul** [comment]
There no scrict rules on this matter and I personally prefer to keep it that way.
The actual order of the fields is a matter of readability and comprehesion. Each particular class and fields list may require different approach. The main goal - it should be easy to read.

**Comment by dynasource** [comment]
what are your criteria for readability and comprehesion?

**Comment by cebe** [comment]
I'm also unsure whether it is useful to create strict rules about this. @dynasource do you see a problem with current classes ordering? If not I suggest to just leave everything as is and focus on creating things.

**Comment by dynasource** [comment]
well, its not that I am advocating for strict rules. I am just wondering if there was a general rule of thumb. If not, that isn't a problem, but then still its useful to know that there aren't rules about this matter.

**Comment by klimov-paul** [comment]
> what are your criteria for readability and comprehesion?

That is the source of the problem - it can not be measured. Thus it is unlikely any strict rules can be composed for this.

**Comment by dynasource** [comment]
@klimov-paul: have you every reordered, lets say, a class with > 7 properties? There must have been some criteria ;)

Its not that a strict rule should be the outcome, but I think is useful to have some kind of direction, like a soft rule of thumb, ie.:
- "if you have more then 7 properties, properties could be grouped based on mutual similarities, but this is not mandatory"

**Comment by samdark** [comment]
No specific rules for it. It was also discussed as PSR-12 and was heavily criticized in PHP-FIG mailing list.
