### ISSUE TITLE
Problem with custom rules?

### ISSUE THREAD

**Issue by Clyff** [yiisoft/yii2#10762]
I have a form that have some custom rules which was working fine. Just today I've noticed that the custom rules aren't working anymore.

After various tests i cannot find the reason why. Just in case, i made a new application like this:

    composer create-project --prefer-dist yiisoft/yii2-app-basic basic

After configuring db, i added in my ContactForm a rule like this:

    return [
        //...
        ['name', 'validateTest']
    ]

And i added the function:

    public function validateTest($attribute)
    {
        $this->addError($attribute, 'error');
    }

Still, if i submit the form with any value in the name, it won't show any error. Something changed? Is there is a new method to add rules that i don't know of? If i am doing something wrong, i apologize.

**Comment by SilverFire** [comment]
Failed to reproduce.

Maybe related to https://github.com/yiisoft/yii2/issues/10723?

**Comment by Clyff** [comment]
I Just found what was happening:

If i don't have `enableAjaxValidation ` set in my form, after submit it, it will not do any of my custom rules if any other attribute have an error.

In my example above, if i submit the form with only a name, it won't trigger the custom error. But, if i have all fields filled it will.

This happens only with me? Or is this the expected behavior of the form? If so, is it possible to change that to show all errors after submit including the ones made by custom rules? In my applications i usually don't enable the ajax validation.

**Comment by SilverFire** [comment]
It's expected. I've pointed you to the issue #10723 where @cebe posted an answer on your question: https://github.com/yiisoft/yii2/issues/10723#issuecomment-177975280

**Comment by Clyff** [comment]
I see. Thank you for clarify this.

**Comment by SilverFire** [comment]
You're welcome :)
