### ISSUE TITLE
Problems Deleting Related Records Where the Relation is Created via UUID field

### ISSUE THREAD

**Issue by chitwarnold** [yiisoft/yii2#10773]
Hi I am using UUID's in my application to ensure uniqueness of records, when they are ported. My problems originate from trying to delete related records. the Relationship was created via the uuid columns. Yii 2, seems to read the relations well on all CRUDS(search) except on the Deletion of Related Records where i get this type ot err

`SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "bb3c42"
LINE 1: ... FROM "pm"."project_sites" WHERE project_code = 64bb3c42-c31...
^
The SQL being executed was: DELETE FROM "pm"."project_sites" WHERE project_code = 64bb3c42-c31d-439d-ac22-1b0fca6a9e83

Error Info: Array
(
    [0] => 42601
    [1] => 7
    [2] => ERROR:  syntax error at or near "bb3c42"
LINE 1: ... FROM "pm"."project_sites" WHERE project_code = 64bb3c42-c31...`

Since the UUID begins with a  number for some reason, it assumes the entire parameter is an integers/number and the query fails on the first instance of an alphabet.

My Environment  includes

- Linux Ubuntu 14.04 LTS, PHP 5.6, PostgreSQL 9.4 , Yii 2 Advanced Template

@samdark @cebe @qiangxue and others  please help

**Comment by chitwarnold** [comment]
FIXED IT : 

` 
** Update /vendor/mootensai/yii2-relation-trait.php,  RelationTrait::deleteWithRelated() , modifying the   value by forcefully wrapping it in single quotes **

	if(count($this->{$data['name']})){
                        $relPKAttr = $this->{$data['name']}[0]->primaryKey();
                        $isCompositePK = (count($relPKAttr) > 1);
                        foreach ($link as $key => $value) {
                            if(isset($this->$value)){
                            	//
                            	$value = "'".$this->$value."'";
                    
                                $array[$key] = $key . ' = ' . $value;
                            }
                        }
                        $error = !$this->{$data['name']}[0]->deleteAll(implode(' AND ', $array));
                    }
`

This was a problem that originated from an oversight from the plugins core code, it's duplication is also abit slim but the code above is the patch. 

Works like a breeze

**Comment by chitwarnold** [comment]
Thanks sam, i am closing this ticket.

**Comment by samdark** [comment]
Yep. Sure.

**Comment by chitwarnold** [comment]
Hope this Helps someone
