### ISSUE TITLE
PO file is missing it's header

### ISSUE THREAD

**Issue by Renkas** [yiisoft/yii2#10775]
I think Yii message generator/extractor should also add a header to PO file. For example the translation service I'm using has now stopped supporting PO files without header through their API and I'm forced to find somekind of quick fix for that. But it would be nice to have this in the core functionality.

How should the header be populated? Should it be configurable through messages configuration file maybe? I have no answers for that - but I think this should be in the scope of framework.

Some information about it: http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html#sec-poheader

**Comment by samdark** [comment]
Setting it in config sounds OK.

**Comment by Renkas** [comment]
I think this can be closed now as the headers were added as a fix for: #11212
