### ISSUE TITLE
Jquery version restriction in composer.json prevents to install jquery 2.2

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#10785]
https://github.com/yiisoft/yii2/blob/master/composer.json#L70

```
    "require": {
        ...
        "bower-asset/jquery": "2.1.*@stable | 1.11.*@stable",
```

http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

Is it expected that jquery 2.2 will break something?

**Comment by samdark** [comment]
No.
