### ISSUE TITLE
CheckboxColumn, value у всех 1, если checkboxOptions является замыканием

### ISSUE THREAD

**Issue by Uterm** [yiisoft/yii2#10784]
Использую в GridView yii\grid\CheckboxColumn. Если checkboxOptions является замыканием, и если явно не устанавливать value, то у всех чекбоксов value будет 1:
`'checkboxOptions' => function ($model, $key, $index, $column) {
    return ['checked' => 'true'];
}`
Приходится в замыкании явно указывать value, например 'value' => $model->id.

По аналогии, если checkboxOptions массив, то все работает правильно:
`'checkboxOptions' => [
    'checked' => 'true',
]`

Предпологаю, что ошибка кроется [тут](https://github.com/yiisoft/yii2/blob/master/framework/grid/CheckboxColumn.php#L128).

**Comment by SilverFire** [comment]
`if (!isset($options['value'])) { ... ` нужно вынести за пределы условия, в которое он заключен

**Comment by Uterm** [comment]
Так точно, не стал пояснять, т.к. это было очевидно.
