### ISSUE TITLE
Guide Test Fixtures - broken link

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#10789]
Go to http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html#fixtures-format 

the "documentation" hyperlink is broken. 

![2016-02-08_1352](https://cloud.githubusercontent.com/assets/436950/12898709/446f4a86-ce6b-11e5-8104-b17179a90c46.png)

**Comment by samdark** [comment]
That document refers to itself. It was 2 separate documents before. These are to be merged.

**Comment by lukBarros** [comment]
Samdark believe he's speaking What OS 2 links are broken , lead paragraph 404 um , like myself checked .

WHY NOT exists This file EVEN IF HE AND linked ?

**Comment by lukBarros** [comment]
Look, in the current master version this file exists: https://github.com/yiisoft/yii2/blob/master/docs/guide/test-fixtures.md

Who problem? Named erro!

test-fixtures.md e test-fixture.md

**Comment by lukBarros** [comment]
See #10890 PU

**Comment by SilverFire** [comment]
PR is merged https://github.com/yiisoft/yii2/commit/9b9d198f2482b0b47115762837e19d33fb994402
Thank you!

**Comment by lukBarros** [comment]
@duynguyen0511 done! @SilverFire  lets rock!
