### ISSUE TITLE
vagrant + composer update

### ISSUE THREAD

**Issue by emimarz** [yiisoft/yii2#10795]
I have the same error that issue 6537

I have the latest composer but this error still happen

https://github.com/yiisoft/yii2/issues/6537

**Comment by cebe** [comment]
> I have the latest composer but this error still happen

also the latest composer asset plugin?

**Comment by SDKiller** [comment]
May be related https://github.com/francoispluchino/composer-asset-plugin/issues/170

**Comment by emimarz** [comment]
I have the latest version of composer asset plugin, dev-master
but I still having this error.
Now I could reduce to this

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package jquery.inputmask could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for yiisoft/yii2 2.0.6 -> satisfiable by yiisoft/yii2[2.0.6].
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

**Comment by emimarz** [comment]
Never mind, I could resolve it, I don't know why happen but I found a way to avoid this error.
If clear cache of composer and delete vendor folder and run composer update
this error disappear.

closing
