### ISSUE TITLE
Translate in VerbFilter

### ISSUE THREAD

**Issue by hugodiniz** [yiisoft/yii2#10799]
I suggest to use "Yii::t" in the error message in VerbFilter.

**Comment by samdark** [comment]
Is the message really helpful/meaningful for end user when presented in native language?

**Comment by hugodiniz** [comment]
@samdark, thank you for your reply. Generally is not helpful/meaningful. But in the moment is the only error message I translated by other way. Maybe creating a message property in VerbFilter is a better solution.

**Comment by SilverFire** [comment]
The error message in VerbFilter is an exception, so the issue duplicates https://github.com/yiisoft/yii2/issues/8931
