### ISSUE TITLE
Bug in yii\i18n\Formatter when using spanish date format (dd/MM/yyyy)

### ISSUE THREAD

**Issue by stupidusername** [yiisoft/yii2#10793]
I'm getting the following error when I use the DatePicker widget. I pick one date let's say 10/01/2016. And then when I do a post and the same field gets populated by the posted value I'm getting this value instead 01/10/2016. But when I use a date like this 28/02/2016 I have no issues.

In short:
01/10/2016 => post => 10/01/2016 => post => 01/10/2016
28/02/2016 => post => 28/02/2016 => post => 28/02/2016

This is my Formatter config:
'formatter' => [
    'class' => 'yii\i18n\Formatter',
    'thousandSeparator' => ' ',
    'decimalSeparator' => ',',
    'dateFormat' => 'dd/MM/yyyy',
    'nullDisplay' => ' ',
],

I think the error is in Formatter::normalizeDatetimeValue

// finally try to create a DateTime object with the value
if ($checkTimeInfo) {
    $timestamp = new DateTime($value, new DateTimeZone($this->defaultTimeZone));
    $info = date_parse($value);
     return [$timestamp, !($info['hour'] === false && $info['minute'] === false && $info['second'] === false)];
}

I printed the array that is being returned by date_parse and that's when the day and the month are beign switched. Maybe the function needed was date_parse_from_format.

I hope I was clear enough. Let me know if you don't understand something. Thanks!

**Comment by stupidusername** [comment]
Actually this date 28/02/2016 is causing an exception and it's not being changed because of that

} catch (\Exception $e) {
    throw new InvalidParamException("'$value' is not a valid date time value: " . $e->getMessage()
        . "\n" . print_r(DateTime::getLastErrors(), true), $e->getCode(), $e);
}

**Comment by cebe** [comment]
how do you store the data in the database?

**Comment by stupidusername** [comment]
I'm not storing those dates on the database. They are only used in a search model and I don't do any write operations on their corresponding fields.

**Comment by stupidusername** [comment]
I have other date fields that are stored as yyyy-mm-dd on the database but so far I didn't notice any erros using them.

**Comment by cebe** [comment]
you should configure the date validator for the search model to convert the dates into unambigous format like, e.g. yyyy-mm-dd  to make it work for the formatter. passing a date like 01/10/2016 to the formatter is ambigous between month and day so it does not know how to parse it correctly.

**Comment by stupidusername** [comment]
Thanks. I did know that the formatter works if the date format is unambigous but it would be nice if the formatter used the specified date format on the configuration when the date format is ambigous.

**Comment by cebe** [comment]
formatter is used for converting machine readable format into human readable. It can not work on ambigous inputs.
