### ISSUE TITLE
Efficiency CSS on Requirement Checker

### ISSUE THREAD

**Issue by muhammadcahya** [yiisoft/yii2#10791]
Ok, Yes I understand that the requirement is rarely used and it is only for development, not for production.

But if it must be with the current method, using the 6807 lines only for css ? like in [css.php](https://github.com/yiisoft/yii2/blob/master/framework/requirements/views/web/css.php)
Only using the container, alerts are also table css class ?

I do not know this is important or not, but when I do online requirement checker on a network connection is not good that this is really felt.

What's your opinion ? :)

**Comment by samdark** [comment]
It's OK to remove unused stuff.

**Comment by muhammadcahya** [comment]
:+1:

**Comment by klimov-paul** [comment]
At the present state Checker CSS is just a full copy of Twitter Bootsrtap CSS.
It is put there in such way for simpicity and to be easy to update.
Custom CSS could be composed for the checker, but the core team does not have spare resources for its composition and suport.

**Comment by muhammadcahya** [comment]
Yes current css code just a full copy of bootstrap 3
But i think this is no need a 6807 lines only for css style, 'same' css code, not all useful code inside core framework. like @samdark say, I think will be better to remove unused stuff.

**Comment by samdark** [comment]
Absolutely. Do you want to handle it?

**Comment by muhammadcahya** [comment]
Okay, but I want to take a break tonight
Maybe tomorrow, and please to be checked later :)

**Comment by muhammadcahya** [comment]
https://github.com/yiisoft/yii2/issues/10791
