### ISSUE TITLE
Compare validator does not work with dynamically added fields

### ISSUE THREAD

**Issue by elguja** [yiisoft/yii2#10790]
Compare validator can't take dynamically added compareAttribute and does not work.

I'm using wbraganca dynamicform and kartik fieldrange widgets.
As I could figure out, they are not reason of this issue.

What can I do to solve this problem? 

![comparevalidator](https://cloud.githubusercontent.com/assets/11720178/12903314/50189b2e-cee0-11e5-8013-007e40350b11.jpg)

**Comment by samdark** [comment]
How fields are added? This should be called in order for validation to work properly: https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md#adding-and-removing-fields-dynamically

Looks like extension issue, not framework one.

**Comment by elguja** [comment]
@samdark Thank you for your fast reply.

I forgot to write this validation does not work on first instance of the model, which is added just like not dynamic form field. (at this time extensions addItem script have not run yet).

this code is in view file.
`<?php 
    echo FieldRange::widget([
    'form' => $form,
    'model' => $modelEducation,
    'label' => 'Enter date range',
    'attribute1' => "[{$i}]start_date",
    'attribute2' => "[{$i}]end_date",
    'type' =>  FieldRange::INPUT_DROPDOWN_LIST,
    'useAddons' => false,
    'separator' => 'to',
    'items1' => [''=>'Select...', 1997 => '1997', 1998 => '1998', 1999 => '1999'],
    'items2' => [''=>'Select...', 1997 => '1997', 1998 => '1998', 1999 => '1999'],
    ]);
    ?>`

I think compare validator gets compareAttribute directly from model validation rules 

`[['start_date'], 'compare', 'compareAttribute'=>'end_date', 'operator'=>'<=', 'skipOnEmpty'=>true],
 [['end_date'], 'compare', 'compareAttribute'=>'start_date', 'operator'=>'>='],`

and because of that it does not have index prefix, and can not compare values of these fields.

**Comment by samdark** [comment]
Well, extension forms these so it should be fixed on its side.
