### ISSUE TITLE
bower asset wrong alias

### ISSUE THREAD

**Issue by bobonov** [yiisoft/yii2#10800]
Made a fresh installation of Yii 2.0.6 basic template and along with it are installed the various bower.
Bower asset path are as following schema
bower/bower-asset/<assets_name>
but the alias to bower in
yiisoft/yii2/base/Application.php at line 456
 is defined as:
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
and should be 
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower'.DIRECTORY_SEPARATOR .'bower-asset');

**Comment by SDKiller** [comment]
You are probably using pretty outdated version of https://github.com/francoispluchino/composer-asset-plugin

**Comment by bobonov** [comment]
yes my error, I regularly do composer global update. But on this machine it was a bit of time that I didn't develop, and even with update the assets plugin was stick to 1.0.3 as update do not advance versions but only minor version.
