### ISSUE TITLE
No event AFTER response sent

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#10802]
Is there any way to do something **after** response sent other then modify entry script? There is only `EVENT_AFTER_REQUEST`, which triggers before response sent.
[Application Lifecycle](http://www.yiiframework.com/doc-2.0/guide-structure-applications.html#application-lifecycle)

**Comment by cebe** [comment]
@Vovan-VE http://www.yiiframework.com/doc-2.0/yii-web-response.html#EVENT_AFTER_SEND-detail

**Comment by Vovan-VE** [comment]
@cebe Thank you, I missed it.
