### ISSUE TITLE
CSRF when using REST

### ISSUE THREAD

**Issue by grin1** [yiisoft/yii2#10809]
I've read a lot of documentation on how CSRF is working with Yii 2 - this is really great because everything is working automatically. Now I'm using Yii 2 as a REST backend without using Yii2 views. So I am loosing Yii comfort, because I have to handle CSRF myself. My frontend consists of an Angular.js application. I really do not want to disable CSRF altogether, because I'm using cookies to authenticate users. Can we extend the docu on how to use Yii2 CSRF when creating an AJAX application? I've set the response format to `FORMAT_JSON` and because of this I have no meta tags, and so not a csrf meta tag, at all.

Do I have to extend the Yii2 response handler, so that every response contains the token? Or can I use cookies for that? I also have CORS enabled, so maybe I do not need CSRF at all? Can we extend Yii so that it outputs the CSRF token using another way (like cookies) when using `FORMAT_JSON`?

**Comment by fernandezekiel** [comment]
to be honest implementing a CSRF on a REST API i think is pointless

**Comment by grin1** [comment]
@fernandezekiel I really do not know exactly. I have CORS enabled, so the only domain that is allowed to make requests is the frontend. So XSS from other domains are prohibited because of CORS right? So I just have to make sure that I have no XSS flaws in my frontend and I am got to go right?

**Comment by cebe** [comment]
@grin1 when starting your angular application you have to pass the CSRF token to it in some way.

when doing ajax request, you have to pass the CSRF token as a header, e.g.:

```js
        $http({
            url: "/myurl",
            method: "POST",
            headers: {
                'X-CSRF-Token': $scope.getCsrfToken()
            }
        })...
```

**Comment by grin1** [comment]
@cebe Yes, but how do I get this token? Yii normally adds it as meta tag or form tag (when using Yii views). But Yii offers no possibility to send the token via cookie or ajax response. Is this not a wanted core-feature?

**Comment by cebe** [comment]
@grin1 you should pass it in the initial HTML page that contains the angular application.
e.g.
```php
<div
    ng-app="..."
    ng-controller="..."
    ng-init='csrfToken=<?= Json::htmlEncode(Yii::$app->request->csrfToken) ?>;'>
```

**Comment by yasinn** [comment]
then application become yii + angular. I think what @grin1  want is a pure single page application.

**Comment by tunecino** [comment]
@yasinn the process is basically the same but implementation will always depend from a client to another.
@grin1 First store the token somewhere after receiving it from server. Here is a login action example that returns the `csrf_token` as response:

```php
public function actionLogin()
{
    $model = new LoginForm();

    if ($model->load(Yii::$app->request->bodyParams, '') && $model->login())
    {
        $client = Yii::$app->params['client'];
        $access_token = Yii::$app->security->generateRandomString();

        $cache = Yii::$app->cache;
        if ($cache->add($access_token, ['id' => Yii::$app->user->identity->id], $client->accessExpiry) === false)
            throw new ServerErrorHttpException('Failed for unknown reason.');

        return [
            'user' => [
                'name' => Yii::$app->user->identity->username,
                'email' => Yii::$app->user->identity->email,
            ],
            'grant' => [
                'refresh_token' => Yii::$app->user->identity->authKey,
                'access_token' => $access_token,
                'expires_at' => time() + $client->accessExpiry,
                'csrf_token' => Yii::$app->request->getCsrfToken(),
            ]
        ];
    }

    return $model;
}
```
Then when received by angular store it somewhere. I put it in session or local storage depending on that `remember me` checkbox being checked or not. Then create an interceptor for it in angular to be auto linked to all requests different from HEAD, GET or OPTTIONS:

```javascript
(function() {
  'use strict';

  angular
    .module('Auth')
    .factory('AuthInterceptor', AuthInterceptor);

  AuthInterceptor.$inject = ['$injector', 'Session'];
  function AuthInterceptor($injector, Session) {
    return {
        request: function(config){

            if (['GET','HEAD','OPTIONS'].indexOf(config.method) === -1) 
              config.headers['X-CSRF-Token'] = Session.getCsrfToken(); // this method returns the token as received from server

            return config;
        }
    }
  };

})();
```

Also note that [the way how (XSRF) Protection is expected to be handled by angular](https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection) is different from how Yii is doing it. Angular expects the cookie to be readable and holding the same token received in header. while `Yii::$app->request->getCsrfToken()` will generate 2 different CSRF tokens. the 2nd is sent within the cookie and Yii has its magical way to compare them later. So I'd recommend protecting that cookie by enabling its `httpOnly` flag so JavaScript can't access it. I do it in Yii's config file:

```php
'components' => [
    'request' => [
        'class' => '\yii\web\Request',
        'csrfCookie' => ['httpOnly' => true],
        ...
```

And that will already solve most of browser's local/session storage vulnerabilities to cross-site scripting as far as your related actions for generating or revoking tokens accepts POST, DELETE and PUT verbs only.
