### ISSUE TITLE
AccessRule ошибка в обработке allows

### ISSUE THREAD

**Issue by arkhamvm** [yiisoft/yii2#10803]
Класс AccessRule:
```php
    public function allows($action, $user, $request)
    {
        if ($this->matchAction($action)
            && $this->matchRole($user)
            && $this->matchIP($request->getUserIP())
            && $this->matchVerb($request->getMethod())
            && $this->matchController($action->controller)
            && $this->matchCustom($action)
        ) {
            return $this->allow ? true : false;
        } else {
            return null;
        }
    }
```

Получается, что в случае если хоть одна функция в условии вернет false, на выходе получим null.
В следствие этого, в AccessControl::beforeAction вызовется denyCallback не конкретного rule, а behavior'а.

Например:
```php
			'access' => [
				'class'	 => AccessControl::class,
				'rules'	 => [
					[
						'actions'	=> ['index'],
						'allow'			 => true,
						'matchCallback'	 => function($rule, $action) {
							return false;
						},
				                'denyCallback'   => function($rule, $action) {
 					                     throw new ExceptionFOO;
				                }
					],
				],
				'denyCallback'   => function($rule, $action) {
					throw new ExceptionBAR;
				}
			]
```

Вызовется ExceptionBAR.

**Comment by arkhamvm** [comment]
Решить можно следующим образом:
```php
    public function allows($action, $user, $request)
    {
        return $this->matchAction($action)
            && $this->matchRole($user)
            && $this->matchIP($request->getUserIP())
            && $this->matchVerb($request->getMethod())
            && $this->matchController($action->controller)
            && $this->matchCustom($action);
   }
```

**Comment by arkhamvm** [comment]
Возможное решение:
```php
    public function allows($action, $user, $request)
    {
        return $this->allow
            && $this->matchAction($action)
            && $this->matchRole($user)
            && $this->matchIP($request->getUserIP())
            && $this->matchVerb($request->getMethod())
            && $this->matchController($action->controller)
            && $this->matchCustom($action)
    }
```

**Comment by githubjeka** [comment]
Красивое решение. 

А PR можете и тестов парочку было бы здорово.

**Comment by SilverFire** [comment]
Мне кажется, что такое условие было сделано не случайно. Нужно проверить историю коммитов чтобы понять, зачем так сделали и что может сломаться

**Comment by githubjeka** [comment]
и null пропал в решении, а он же нужен был для чего...нужны тесты!

**Comment by kittig** [comment]
I have the same problem in PHP7.

I changed the code in vendor/yiisoft/yii2/filters/AccessControl.php
`
118             if ($allow = $rule->allows($action, $user, $request)) {
119                 return true;
120             } else { 
120             // } elseif ($allow === false) {  // CHANGE THIS LINE    

`

**Comment by cebe** [comment]
Not sure I understand correctly but `null` has a meaning here:

> `@return boolean|null true if the user is allowed, false if the user is denied, null if the rule does not apply to the user`

null is used as neither allow or deny here: https://github.com/yiisoft/yii2/blob/7ba631b4ae3a40206e752fded8775b65491d1bcb/framework/filters/AccessControl.php#L118-L129

**Comment by samdark** [comment]
Right. So rule wasn't applied and "deny" is a result of no rules match. Then everything works as it was designed.

**Comment by arkhamvm** [comment]
@samdark, @cede, So if "matchCallback" is only used to determine **if the rule should be applied**, сan I suggest additional callback to check **is the rule allowed** to user?
Something like this:
```php
            'access' => [
                'class'  => AccessControl::class,
                'rules'  => [
                    [
                        'actions'   => ['index'],
                        'allow'          => true,
                        'allowCallback'  => function($rule, $action) {
                            return (1 === rand(0,1));
                        },
                    ],
                ],
            ]
```
```php
    public function allows($action, $user, $request)
    {
        if ($this->matchAction($action)
            && $this->matchRole($user)
            && $this->matchIP($request->getUserIP())
            && $this->matchVerb($request->getMethod())
            && $this->matchController($action->controller)
            && $this->matchCustom($action)
        ) {
            return ($this->allow && $this->allowCustom) ? true : false;
        } else {
            return null;
        }
    }

    protected function allowCustom($action)
    {
        return empty($this->allowCallback) || call_user_func($this->allowCallback, $this, $action);
    }
```

If this option is accessible, i can create pull request.

**Comment by arkhamvm** [comment]
In additional, it would be nice, if "allow" variable can be closure (```php function ($rule, $action)```) too, "allowCustom" is would not be necessary.

**Comment by samdark** [comment]
Isn't "is the rule allowed" === "if the rule should be applied"?

i.e. Rule is attached to permission. If permission is on the path from what's checked to user role in the RBAC hierarchy then Rule will be executed.

**Comment by arkhamvm** [comment]
@samdark, please, can you explain, do i understand correctly: there is no way to call "denyCallback" if "matchCallback" returned "false", and this option does not planned?

**Comment by cebe** [comment]
you can use a rule that denies if it matches:

```php
 'access' => [
                'class'  => AccessControl::class,
                'rules'  => [
                    [
                        'allow'          => false,
                        'matchCallback'  => function($rule, $action) {
                            return (1 === rand(0,1));
                        },
                        'denyCallback' => function() { ... }
                    ],
                ],
            ]
```

**Comment by samdark** [comment]
@arkhamvm yes. If permission wasn't matched, rule isn't executed. Ever.

**Comment by arkhamvm** [comment]
@samdark, @cebe, thanks for explanation.
