### ISSUE TITLE
Passing model by GET append params instead of overwritting

### ISSUE THREAD

**Issue by koxu1996** [yiisoft/yii2#10808]
I am passing model by GET and after first submit request look like this:
![First submit](http://snag.gy/qw12q.jpg)

after second request:
![Second submit](http://snag.gy/py61w.jpg)
I think params should be overwritten, but maybe I am missing something in code.

**Form model**
```
class TestForm extends Model
{
    public $text;

    public function rules()
    {
        return [
            ['text', 'safe'],
        ];
    }
}
```
**Controller**
```
public function actionTest()
    {
        $model = new TestForm();       
        $model->load(Yii::$app->request->get());
        return $this->render('test', ['model'=>$model]);
    }

```
**View**
```
<?php $form = ActiveForm::begin(['method'=>'GET']); ?>
    <?= $form->field($model, 'text') ?>
    <?= Html::submitButton('OK') ?>
<?php ActiveForm::end(); ?>
```

PHP version: 5.5.9-1ubuntu4.14 
Yii2 version: 2.0.6
OS: Ubuntu 14.04
Browser: Chrome 48.0.2564.97 (64-bit)

**Comment by grin1** [comment]
`$model = new TestForm();       
$filter->load(Yii::$app->request->get());`

Use `$model` instead of `$filter$`?

**Comment by koxu1996** [comment]
@grin1 Before posting issue I was changing variables name and I did not notice this one. Now corrected, but issue is still valid.

**Comment by klimov-paul** [comment]
You should specify form action explicitely to the URL without model parameters, otherwise it will just append input data to the current URL per each submit.
