### ISSUE TITLE
[rest/UrlRule] Allow parameters in each controller.

### ISSUE THREAD

**Issue by thiagotalma** [yiisoft/yii2#10816]
It does not make much sense to have a global definition of the attributes "only" and "except". There would be few use cases accordingly.

The most common use case would depend on the definition for each controller.

Something like that:

```php
'urlManager' => [
    'rules' => [
        [
            'class' => 'yii\rest\UrlRule',
            'controller' => [
                'user',
                'post' => [
                    'only' => ['create', 'delete'],
                ],
                'comment' => [
                    'except' => ['delete'],
                ]
            ],
        ]
    ],
],
```

What do you think of this?

**Comment by samdark** [comment]
UrlRule already resolves to controller and action. Why do I need to specify it once again?

**Comment by thiagotalma** [comment]
leave it alone...
