### ISSUE TITLE
buildJoinWith not using di container i.e. \Yii::createObject()

### ISSUE THREAD

**Issue by adamdry** [yiisoft/yii2#10814]
As the title suggests in ActiveQuery line 407 (in my version) which looks like this:
`$this->joinWithRelations(new $this->modelClass, $with, $joinType);`

uses the "new" keyword instead of using \Yii::createObject() - this causes our DI to fail on ActiveRecords which have dependencies.

Any chance it could be changed to use \Yii::createObject() ? :)

**Comment by cebe** [comment]
duplicate of #8639
