### ISSUE TITLE
Abstract Super Globals such as $_SERVER for each request into \yii\web\Request

### ISSUE THREAD

**Issue by caleblloyd** [yiisoft/yii2#10824]
With the release of PHP7 and the new Pthreads package, running a threaded HTTP Server from the PHP CLI is now a viable thing to do (as opposed to running a webserver and running PHP as a FastCGI script). The Yii2 Framework directly references Super Globals such as $_SERVER variables in many places, which are global variables and cannot be changed on each request. In order to support multiple requests within the same process, these variables would need to abstracted.

I think that supporting long-running PHP web servers from the CLI is going to be an increasingly important thing for developers since development is shifting towards microservices.  This would allow for state to be stored in memory from one request to the next.

**Comment by SamMousa** [comment]
PSR-7 defines these abstractions (not sure if it fully covers the `$_SERVER` global for cli requests.
It would be nice if `yii\web\Application::run()` would accept a `ServerRequestInterface` object as parameter and use that instead.

For users that prefer to use `$_SERVER` there are implementations that can create such an object form globals. Such as `zendframework/zend-diactoros`: https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php#L54

**Comment by caleblloyd** [comment]
In addition to Zend Diactoros, there's also a PR in progress for ServerRequestInterface in the Guzzle PSR7 project: https://github.com/guzzle/psr7/pull/54.  Going this route would definitely streamline server creation.  I imagine there will be plenty of Raw HTTP Request to PSR7 ServerRequestInterface parsers coming soon.

As it turns out, we are actually going to have to change all calls to $_SERVER, $_COOKIE, $_GET, $_POST, and $_FILES.  What if we add an abstraction in \yii\web\Request for each of these Super Globals.  Then check to see if there is an instance of a \Psr\Http\Message\ServerRequestInterface in the Request.  If so, we pull the value from the ServerRequest, otherwise we pull it from a super global.  Here's an example of edits to \yii\web\Request:

    /** @var \Psr\Http\Message\ServerRequestInterface */
    public $serverRequest;

    public function getQueryParams()
    {
        if ($this->_queryParams === null) {
            if ($this->serverRequest !== null){
                return $this->serverRequest->getQueryParams();
            }
            return $_GET;
        }
        return $this->_queryParams;
    }

    public function getServerParams()
    {
            if ($this->serverRequest !== null){
                return $this->serverRequest->getServerParams();
            }
            return $_SERVER;
    }

    // do this for $_SERVER, $_COOKIE, $_GET, $_POST, and $_FILES

As long as we develop using the "psr/http-message" message at https://github.com/php-fig/http-message, any \Psr\Http\Message\ServerRequestInterface from any library supporting the spec could work with Yii2.

All references to  $_SERVER, $_COOKIE, $_GET, $_POST, and $_FILES in Yii2 would need to be switched to reference their abstractions in Yii::$app->request

**Comment by samdark** [comment]
HTTP message isn't yet accepted as a standard. I agree overall that 2.1 should be at least PSR-7 compatible.

**Comment by SamMousa** [comment]
http://www.php-fig.org/psr/ it is accepted right?

**Comment by samdark** [comment]
Only the ones in "ACCEPTED" section.

**Comment by samdark** [comment]
Ah, yes. I've confused HTTP Message with something else in the works.

**Comment by samdark** [comment]
Without BC breaks... are you sure?

**Comment by SamMousa** [comment]
Yes, unless of course you count third party code that uses `$_XXX` break as BC breaks..

**Comment by samdark** [comment]
Nope, that's fine, I think.

**Comment by samdark** [comment]
Do you want to work on a draft implementation?

**Comment by caleblloyd** [comment]
I am working on a draft implementation now, should have it posted in a couple hours

**Comment by klimov-paul** [comment]
Resolved by commit 722022f744dbac8b0ef930caf877efdf388898e5
