### ISSUE TITLE
EachValidator does not respect skipOnEmpty for individual values

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#10825]
As I can see - the underlying problem is in `\yii\validators\Validator` itself - because `skipOnEmpty` check is done in `validateAttributes()`.

And `\yii\validators\EachValidator` directly calls `validateAttribute()` - so check for `skipOnEmpty` is bypassed.

**Comment by SilverFire** [comment]
Well, for me it seems to be expected. In my projects I always use `filter` before `each` to normalize attribute before using `each` over it.
I'd like to see @klimov-paul's opinon

**Comment by SDKiller** [comment]
If it is by design - at least a note in phpdoc should be added, because as of now it is confusing:

```
...in the same format as at [[yii\base\Model::rules()]]...
```

**Comment by klimov-paul** [comment]
Resolved by commit d22a3a0a07befc274cac49a96dfcea3372953138
