### ISSUE TITLE
Talk About yii2 in Brazil

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#10829]
Talk About yii2 in Brazil

Excuse me but did not know which channel to use to speak to the core team on the disclosure of yii2 in my country , Brazil .

April is the FLISOL (Festival Latin American Free Software Installation ) in over 400 cities in Latin America and the Caribbean , including in my city , Maceio .

Will lecture on the theme: Yii2 PHP framework - Fast and furious php development

See more information on the official http://flisol.info/FLISOL2016/Brasil/Maceio project

My heart beats strong with yii2 !

**Comment by samdark** [comment]
Great! Thanks for spreading the word. You may contact me directly via `sam@rmcreative.ru` if you have specific questions.

**Comment by samdark** [comment]
Announced here: http://www.yiiframework.com/forum/index.php/topic/69681-flisol-2016-maceio-brazil/
