### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#10838]
Hello guys !

The new yii site is taking to be released , I made an issue over nearly 12 months.

I have a web development company , we have already developed more than 2000 website designs , electronic eyesores , news portals, etc. (see www.id5.com.br ) .

I would put myself at the disposal couple do / finish what we have done regarding it as a gift to u , by the brilliant work they are doing with Yii2 !

What do you think?

**Comment by pana1990** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/issues

**Comment by lukBarros** [comment]
@pana1990  ok man, its is cool! In 2015 it not public for community. Cool!

One question: because it was created other 'organization' for this?

**Comment by samdark** [comment]
It's in development. We're going to focus on it more soon. If you want you can create pull requests solving issues.
