### ISSUE TITLE
[ENH] Add shortcuts to ConsoleController

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#10840]
Add shortCuts method to create alias in options commands.

Usage : 

```php
// In ServeController 
public function shortCuts()
{
      return [
             'd' => 'docroot',
             'p' => 'port',
      ];
}
```

In console : 

```bash
yii serve -p=8888 -d=frontend/web
```

What do you think about it?

**Comment by samdark** [comment]
Could be useful, yes.

**Comment by djagya** [comment]
I like this feature, I could implement that

**Comment by pana1990** [comment]
ok, I will try to create a pull request for this feature.

**Comment by pana1990** [comment]
resolve in https://github.com/yiisoft/yii2/commit/857eee24515535eae6fe01283e313f24de563cbc

**Comment by pana1990** [comment]
@SilverFire can you set this issue in milestone 2.0.8?

**Comment by SilverFire** [comment]
Yepp, done

**Comment by pana1990** [comment]
@SilverFire thanks you very much
