### ISSUE TITLE
Yii2 slack oficial?

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#10841]
Yii2 slack oficial for talk about yii2 and components?

**Comment by samdark** [comment]
There's already IRC and gitter. Not sure it worth creating another channel...

**Comment by cebe** [comment]
definitively not worth adding more different channels. The value of a chat channel increases with participants. We should try to get all people onto one channel instead of opening many different ones.

**Comment by zorobabel** [comment]
Sorry guys but the IRC channel seems a cemetery, @lukBarros idea is good, not everyone know how to use IRC, I think that Slack is a better tool for this purpose (example: https://strapi.slack.com/) but the final decision is on you.

**Comment by cebe** [comment]
> not everyone know how to use IRC

should not be that hard: http://www.yiiframework.com/chat/

**Comment by zorobabel** [comment]
yes, it's not hard to use but IMO slack is more dynamic
