### ISSUE TITLE
Error on updating to 2.0.7

### ISSUE THREAD

**Issue by silverslice** [yiisoft/yii2#10844]
I've tried to update Yii 2 in basic application from 2.0.6 to 2.0.7 with these commands:
```
composer self-update
composer global require "fxp/composer-asset-plugin:~1.1.1"
composer require yiisoft/yii2 2.0.7
```
Composer gave me this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: yiisoft/yii2-composer[2.0.4, 2.0.3].
    - Can only install one of: yiisoft/yii2-composer[2.0.4, 2.0.3].
    - Can only install one of: yiisoft/yii2-composer[2.0.4, 2.0.3].
    - yiisoft/yii2 2.0.7 requires yiisoft/yii2-composer ~2.0.4 -> satisfiable by yiisoft/yii2-composer[2.0.4].
    - Installation request for yiisoft/yii2 2.0.7 -> satisfiable by yiisoft/yii2[2.0.7].
    - Installation request for yiisoft/yii2-composer == 2.0.3.0 -> satisfiable by yiisoft/yii2-composer[2.0.3].

Installation failed, reverting ./composer.json to its original content.
```

**Comment by brucealdridge** [comment]
i had the same issue, had to `rm -r vendor composer.lock` and `composer install` but not ideal :confused:

**Comment by hahawang** [comment]
i had the same issue

**Comment by Ximich** [comment]
This problem was already happened: https://github.com/francoispluchino/composer-asset-plugin/issues/65

Remove vendor && composer.lock works for me.
Suggest remove all client side dependencies in future major release.

**Comment by cebe** [comment]
> This problem was already happened: francoispluchino/composer-asset-plugin#65

this does not seem to be related.

I wonder where this comes from:
>     - Installation request for yiisoft/yii2-composer == 2.0.3.0 -> satisfiable by yiisoft/yii2-composer[2.0.3].

have you specified a requirement for `yiisoft/yii2-composer` in your composer.json?

**Comment by cebe** [comment]
reproduced the problem:

If you run only

```
composer require yiisoft/yii2 2.0.7
```

it will try to update only `yiisoft/yii2` and not touch any other dependencies in your composer.json. Same is true for the following:

```
composer update yiisoft/yii2
```

You should either run `composer update` to update all packages, or include all packages that are problematic, in this case  `composer update yiisoft/yii2 yiisoft/yii2-composer`.

**Comment by cebe** [comment]
for future compatibility I suggest you remove the requierement to `yiisoft/yii2-composer` from your composer.json, it is not needed and pulled in by yiisoft/yii2 anyway.

**Comment by silverslice** [comment]
I haven't dependency `yiisoft/yii2-composer` in composer.json. This is most likely a problem with composer asset plugin.

**Comment by cebe** [comment]
Seems the problem exists also with other packages that require yii2-composer. can you show your composer.json?

btw, `composer update yiisoft/yii2 yiisoft/yii2-composer` should work in any case.

**Comment by silverslice** [comment]
My composer.json:
```
{
    "name": "silverslice/app",
    "description": "myapp",
    "type": "project",
    "license": "BSD-3-Clause",
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.5",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-imagine": "^2.0",
        "yiidoc/yii2-redactor": "*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*",
        "codeception/codeception": "2.1.*"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

```
I've tried to run `composer update yiisoft/yii2 yiisoft/yii2-composer` and got the same error for `bower-asset/jquery.inputmask`. 

The problem is that version 2.0.7 increases the minimum requirements for 2 libraries: `yiisoft/yii2-composer` (from * to ~2.0.4) and `bower-asset/jquery.inputmask` (from 3.1.* to ~3.2.2). So the correct way to update to 2.0.7 is to run `composer update yiisoft/yii2 yiisoft/yii2-composer bower-asset/jquery.inputmask`.

**Comment by cebe** [comment]
> So the correct way to update to 2.0.7 is to run composer update yiisoft/yii2 yiisoft/yii2-composer bower-asset/jquery.inputmask.

Thanks for finding this out. I updated the instructions on http://www.yiiframework.com/download/
