### ISSUE TITLE
After update yii to 2.0.7 (from 2.0.6), debug panel lost styles.

### ISSUE THREAD

**Issue by dslpp056193** [yiisoft/yii2#10848]
What reason?

**Before update:**

> ![image](https://cloud.githubusercontent.com/assets/11080873/13043805/f68d4470-d3e3-11e5-9b14-5d1150223b7a.png)

**After update:**

> ![image](https://cloud.githubusercontent.com/assets/11080873/13043813/0196efd8-d3e4-11e5-87eb-d0f0335f5b7f.png)

Command panel does not display errors.

**Comment by cebe** [comment]
no idea, I have styles in 2.0.6 as well as 2.0.7...

**Comment by mikehaertl** [comment]
@dslpp056193 Have you tried to delete the content of your `/assets` directory?

**Comment by dslpp056193** [comment]
@mikehaertl No, i have not tried remove assets.
I just update fxp composer to last version (by recomendation in [UPDATE.md](https://github.com/yiisoft/yii2/blob/2.0.7/framework/UPGRADE.md)) and run next command
`composer require yiisoft/yii2 2.0.7`

**Comment by dslpp056193** [comment]
And more one moment:
"composer require yiisoft/yii2 2.0.7" not working.
It's command working, only if remove next folders:
<project>/vendor/yiisoft/
<project>/vendor/bower/jquery.inputmask/

**Comment by dslpp056193** [comment]
Now try again update yii to 2.0.7 and Now try again update yii to 2.0.7 and styles not dropped, but my previous comment still relevant.

**Comment by dslpp056193** [comment]
I think you need recommend to remove "vendor" folder, before update yii to new version.
And then all be fine.

**Comment by cebe** [comment]
the proper way of upgrading to 2.0.7 seems to be the following:

```
composer update yiisoft/yii2 yiisoft/yii2-composer bower-asset/jquery.inputmask
```

see https://github.com/yiisoft/yii2/issues/10844#issuecomment-184453542
