### ISSUE TITLE
yii2\db\Connection attributes PDO::ATTR_CASE problem

### ISSUE THREAD

**Issue by phelan** [yiisoft/yii2#10858]
when setting db->attributes PDO::ATTR_CASE=PDO::CASE_LOWER
mysql table column name is in upper case，the active record do not change the attribute to lower case,could this be a problem to use? shall we going to fix it？

**Comment by cebe** [comment]
why do you need PDO::ATTR_CASE for mysql?

**Comment by phelan** [comment]
because our DBA rules,they automatic change the column name to upper case，but writing a attribute in upper case is very stupid，so i tried to set  PDO::ATTR_CASE=PDO::CASE_LOWER, but find the active record does not affect，so i changed few code to make it affect

**Comment by cebe** [comment]
related to #9457

**Comment by SilverFire** [comment]
I'm closing the issue as a duplicate. Feel free to join the conversation in #9457 to help us solve the problem
