### ISSUE TITLE
Boolean subquery support

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#10855]
Currently to generate the condition,

``` sql
 AND (parent_id = 1 OR (SELECT 1 FROM `table` WHERE id = `table`.parent_id AND parent_id = 1))
```

I have to hack `QueryBuilder` a bit,

``` php
->andWhere(['', 'parent_id = 1 OR', (new Query)->select([new Expression(1)])->from('table')->where('`parent_id` = 1 AND `id` = `table`.`parent_id`')])
```

Would feel a bit cleaner if you could do the below.

``` php
->andWhere(['or', 'parent_id = 1', (new Query)->select([new Expression(1)])->from('table')->where('`parent_id` = 1 AND `id` = `table`.`parent_id`')])
```

**Comment by Alex-Code** [comment]
Not sure if there's a better place but to test I put the `Query` check in the `buildAndCondition` method.

```php
    public function buildAndCondition($operator, $operands, &$params)
    {
        //...
        if (is_array($operand)) {
            $operand = $this->buildCondition($operand, $params);
        } elseif ($operand instanceof Query) {
            list($operand, $params) = $this->build($operand, $params);
        }
        //...
    }
```

I can do a PR if needed?

**Comment by SilverFire** [comment]
As far as I see, it is already implemented for some conditions: 

 - [buildInCondition()](https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L1111)
 - [buildSimpleCondition()](https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L1326)
 - [buildHashCondition()](https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L971)

Therefore I'm suggesting to expand the practice to the neighbour methods to make them consistent.
