### ISSUE TITLE
getIsSecureConnection is not secure.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10854]
When checking to see if a connection is secure we should not rely on possibly user-supplied headers.
While the framework itself only uses `yii\web\Request::getIsSecureConnection()` for generating URLs, others might use it to expose sensitive information.

For example, I might allow users to access the site non-securely, but deny them access to any sensitive information.
If I were to verify if the connection is secure by calling `getIsSecureConnection()` there could be user or attacker (MITM) supplied headers suggesting the connection is secure, while in reality it is not.

In my opinion there are only 2 situations where we can reasonably assume a connection is secure:
1.  The webserver directly tells us, via `$_SERVER['HTTPS']` (since this cannot be spoofed).
2. Configuration tells us this is a secure connection.

All detection methods based on headers are security risks.

**Comment by samdark** [comment]
I agree to make it use `$_SERVER` only.

**Comment by kidol** [comment]
In Symfony they use whitelist for this stuff. Looks like this: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1181

In total they use 3 properties:

- `$trustedProxies`
- `$trustedHeaders` Defines which headers should be trusted from the trusted proxies
- `$trustedHostPatterns` To verify the HTTP_HOST

So with these Yii could verify SSL & client ip set with special http headers as well as protect against http host injection.

**Comment by samdark** [comment]
Sounds good to add these.

**Comment by SamMousa** [comment]
Suggested configuration approach:
````
/**
     * @var array The configuration for trusting security related header.
     * The array key is a regular expression for matching the hostname.
     * The value is a list of headers to trust.
     * Example: trust all headers from domains ending in '.trusted.com'
     * ```
     * [
     *     '/^.*\.trusted.com$/' => ['-.*-']
     * ]
     * ```
     */
    public $trustedHostConfig = [];
````

Then:
1. When constructing the `HeaderCollection` in `getHeaders()` filter the untrusted headers.
2. Make all other functions that read headers use the `HeaderCollection`. Specifically:
- Response (`HTTP_RANGE`)
- HttpCache (`HTTP_IF_NONE_MATCH`, `HTTP_IF_MODIFIED_SINCE`)
- ErrorHandler (`HTTP_X_REQUESTED_WITH`)
- Request --> several.
3. No changes / writing to `$_SERVER` so everyone should use the frameworks' `Request` object.

I can implement this for 2.0.13 if my approach sounds acceptable.
On a side note, if desired, I can fix the specific issue regarding `getIsSecureConnection` but that could lead to stuff breaking for people with no easy way to fix it (since they can't configure trusted hosts).

**Comment by samdark** [comment]
Sounds good. One note though is that `*` wildcard should be supported for the case when you're behind trusted properly configured reverse proxy.

**Comment by SamMousa** [comment]
Why create the exception? `//` is a wildcard, or `/.*/` or whatever :).

**Comment by samdark** [comment]
Hmm... do we actually need regular expressions there?

**Comment by SamMousa** [comment]
Well if people don't want to whitelist each IP / hostname manually then you need some kind of matching.

Either you invent your own format and use specific matching we keep it simple and use a well established format.
Since this happens only once per request it's not really relevant performance wise.

**Comment by samdark** [comment]
I think a simple wildcard might do a good enough job. Alternatively we can accept an anonymous function such as:

```php
$trustedProxies = function($hostname) {
    return in_array($hostname, Yii::$app->params['proxies']);
}
```

That would cover all possible cases.
