### ISSUE TITLE
Update $typeMap for MySQL

### ISSUE THREAD

**Issue by gemini1389** [yiisoft/yii2#10859]
In version 2.0.7 for migration was introduced unsigned(), and therefore I propose to update some values in $typeMap for MySQL.
https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L25
```php
Schema::TYPE_BIGPK => 'bigint NOT NULL AUTO_INCREMENT PRIMARY KEY',
Schema::TYPE_STRING => 'varchar',
Schema::TYPE_SMALLINT => 'smallint',
Schema::TYPE_INTEGER => 'int',
Schema::TYPE_BIGINT => 'bigint',
```

and propose to replace TYPE_PK, because the PK in most cases greater than 0:
```php
Schema::TYPE_PK => 'int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY',
Schema::TYPE_BIGPK => 'bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY',
```

**Comment by SilverFire** [comment]
```php
Schema::TYPE_STRING => 'varchar',
Schema::TYPE_SMALLINT => 'smallint',
Schema::TYPE_INTEGER => 'int',
Schema::TYPE_BIGINT => 'bigint',
```

Could you elaborate, please why are you suggesting to remote the length from these types?

```php
Schema::TYPE_PK => 'int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY',
Schema::TYPE_BIGPK => 'bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY',
```

It will cause BC-breaking for user's migrations, I'd like to avoid it.

**Comment by cebe** [comment]
We have discussed this before, we will not add unsigned by default.

**Comment by gemini1389** [comment]
**SilverFire**, I'm sorry, that is not immediately wrote.
These are standard values that are not necessarily write, the database expose length itself. Another reason was the fact that the maximum length without unsigned on 1 greater than with unsigned. For example, "int(10) unsigned" and "int(11)".

P.S. Sorry for my English, I use a translator. :)

**Comment by SilverFire** [comment]
We are international. Можно по-русски, а можна і українською :)

**Comment by SilverFire** [comment]
Well, there is one hidden reason, why we can not remove the length from the default. The reason is [QueryBuilder::getColumnType()](https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L616) that checks, whether the value of the type according to the `typeMap` has curly brackets to decides, whether it is possible to apply a length to this type.

**Comment by gemini1389** [comment]
Перейду на українську)

На скільки розумію, то вказаний реплейс відпрацює в тому випадку, якщо переданий тип поля не існує в $this->typeMap, тобто написаний "руками". Але якщо писати міграцію по такому принципу, як створена міграція і yii2-advanced, то до цього реплейсу справа не дійде. Покажу приклад по типу integer.

Міграція з yii2-advanced:
https://github.com/yiisoft/yii2-app-advanced/blob/master/console/migrations/m130524_201442_init.php#L24
Метод integer():
https://github.com/yiisoft/yii2/blob/master/framework/db/SchemaBuilderTrait.php#L107

Можливо я не так зрозумів Ваш коментар

**Comment by SilverFire** [comment]
Дійсно, в наведеному вами прикладі, це не має значення, але `alterColumn`, `createTable` та `addColumn` використовують `getColumnType` для забезпечення сумісності міграцій для різних баз даних.

**Comment by gemini1389** [comment]
Мені здається, що не має вплинути. Наприклад, метод [Migration::addColumn()](https://github.com/yiisoft/yii2/blob/master/framework/db/Migration.php#L309)
```php
$this->addColumn('table', 'column', 'int(11)');
$this->addColumn('table', 'column', $this->integer());
$this->addColumn('table', 'column', Schema::TYPE_INTEGER);
```
Перший варіант - це написані нами особисто параметри, які пройдуть через реплейс.
Другий варіант - параметри, які будуть згенеровані фреймворком, але теж пройдуть через реплейс, так як попадуть до [QueryBuilder::getColumnType()](https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L608) вже у вигляді рядку.
Третій вариант - не дійде до реплейса, так як це ключ у массиві [$typeMap](https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L25).

Правда, якщо правильно зрозумів код, то для unsigned є тільки такі варіанти використання:
```php
$this->addColumn('table', 'column', 'int(10) unsigned');
$this->addColumn('table', 'column', $this->integer()->unsigned());
```

Чесно признаюсь, не тестував написаний код, суджу тільки по коду фреймворка.

**Comment by SilverFire** [comment]
> Перший варіант - це написані нами особисто параметри, які пройдуть через реплейс.

Якщо замінити значення `Schema::TYPE_INTEGER` з 'int(11)' на `int`, то виконнаня

```php
$this->addColumn('table', 'column', 'int(6)');
```

призведе до створення стовпчика без обмеження довжини. Можете перевірити

**Comment by gemini1389** [comment]
Перевірив. На сервері MariaDB 10.1. Тестував тільки на типі integer.

Ось тестова міграція:
```php
<?php
use yii\db\Migration;
use yii\db\Schema;
class m303030_000000_test extends Migration
{
	public function up()
	{
		$tableOptions = null;
		if ($this->db->driverName === 'mysql') {
			// http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
			$tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
		}
		$this->createTable('{{%test}}', [
			'id' => $this->primaryKey(),
			'username' => $this->string()->notNull()->unique(),
			'auth_key' => $this->string(32)->notNull(),
		], $tableOptions);

		$this->addColumn('{{%test}}', 'test1', Schema::TYPE_INTEGER);
		$this->addColumn('{{%test}}', 'test2', 'int(6)');
		$this->addColumn('{{%test}}', 'test3', 'int(6) unsigned');
		$this->addColumn('{{%test}}', 'test4', $this->integer());
		$this->addColumn('{{%test}}', 'test5', $this->integer()->unsigned());
	}
	public function down()
	{
		$this->dropTable('{{%test}}');
	}
}
```
Ось результат її роботи:
```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `auth_key` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `test1` int(11) DEFAULT NULL,
  `test2` int(6) DEFAULT NULL,
  `test3` int(6) unsigned DEFAULT NULL,
  `test4` int(11) DEFAULT NULL,
  `test5` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

```
Все працює нормально, на скільки бачу. По суті ми не змінюємо логіки роботи ядра.

**Comment by SilverFire** [comment]
Це вже після `Schema::TYPE_INTEGER => 'int'`?

**Comment by gemini1389** [comment]
Саме так. База сама виставить ліміт довжини для стовпчика. Як видно по стовпчиках test4 та test5, значення база виставила правильні відповідно до параметра unsigned

**Comment by SilverFire** [comment]
Але це точно одного разу виринало, треба пошукати.

**Comment by SilverFire** [comment]
О, ось воно: https://github.com/yiisoft/yii2/issues/9585#issuecomment-148935309

**Comment by gemini1389** [comment]
Це трішки інша ситуація. Я прошу змінити дефолтні значення тільки для MySQL. На жаль, про інші БД судити не візьмусь.

**Comment by SilverFire** [comment]
Наразі я не бачу в цьому нагальної потреби. Не могли б ви пояснити, що саме це змінить/покращить?

**Comment by gemini1389** [comment]
На мою точку зору це спростить роботу. Зараз при створенні/редагуванні таблиць потрібно слідкувати за довжиною. Або потрібно вручну вказувати значення довжини (якщо хочеться отримати int(10) unsigned), або прописувати int(11) примусово в іншому коді.

Наприклад, коли ведеться робота над проектом, де БД була створена ще з "int(10) unsigned". В цій ситуації потрібно слідкувати за типом поля, щоб створювались Foreigen Keys.

Загалом потрібний контроль за довжиною полів та FK є причиною створення цієї пропозиції.

**Comment by SilverFire** [comment]
Робота з таблциями, в яких є стільки даних, вимагає певних знань і досвіду. Якщо вам відома різниця між `int(11) unsigned` та `int(10) unsigned`, ви підготуєте відповідний DDL і все буде ок. 

Я планах реалізація ідеї з #9585, а ці зміни конфліктні за логікою. Проблема в #9585 буде муляти, при чому постраждають в першу чергу новачки, тому я віддаю перевагу їй.
