### ISSUE TITLE
After update yii to 2.0.7 not work redirect in view

### ISSUE THREAD

**Issue by rahimov** [yiisoft/yii2#10851]
Not work redirect in layout view
this code: 
```php
Yii::$app->response->redirect('@frontendUrl');
```

**Comment by cebe** [comment]
this should not have worked that way before... can you show more surrounding code?

1. redirecting in a view file is bad practice, the controller should make decision on that
2. the application should be halted when redirect has been called, so you need to call `Yii::$app->end()`.

**Comment by rahimov** [comment]
1. yes, i'm change own code to access behavior
2. thanks, the previous version worked without Yii::$app->end()

past code in layout:
```php
if (!Yii::$app->user->isGuest){
    if (!Yii::$app->user->can('loginToBackend')) {
        Yii::$app->response->redirect('@frontendUrl');
    }
}
```

**Comment by cebe** [comment]
this should be done on controller level or application wide in `beforeAction`.
