### ISSUE TITLE
expression in findOne

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#10857]
this cases not work:
```php
City::findOne(['=', new Expression('LOWER(`name`)'), strtolower($name)]);
City::findOne(['and', ['=', new Expression('LOWER(`name`)'), strtolower($name)]]);
```
this work fine:
```php
City::find()->andWhere(['=', new Expression('LOWER(`name`)'), strtolower($name)])->one();
```

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findOne%28%29-detail
> The method accepts:

>    - a scalar value (integer or string): query by a single primary key value and return the corresponding record (or null if not found).
>    -    a non-associative array: query by a list of primary key values and return the first record (or null if not found).
>    -    an associative array of name-value pairs: query by a set of attribute values and return a single record matching all of them (or null if not found). Note that ['id' => 1, 2] is treated as a non-associative array.
