### ISSUE TITLE
ES6 assets converter doesn`t work

### ISSUE THREAD

**Issue by macklay** [yiisoft/yii2#10866]
I try to use such babel converter option for ES6 support:
```
'js'   => ['js', './node_modules/.bin/babel {from} --out-file {to}'],
```
But it doesn`t work because "from" and "to" files(and their filemtime) are the same:

Yii AssetConverter class:
```php 
if ($this->forceConvert || @filemtime("$basePath/$result") < @filemtime("$basePath/$asset")) {
                    $this->runCommand($command, $basePath, $asset, $result);
                }
```

**Comment by klimov-paul** [comment]
This is expected behavior since file extension (and thus file name) does not change during the conversion.
You should use different fike extension for the asset source file or set `forceConvert` to `true`.
