### ISSUE TITLE
Yii 2 can't find "bower"

### ISSUE THREAD

**Issue by dslpp056193** [yiisoft/yii2#10862]
After install, yii2 have link to bower as `"vendor/bower/"`, but composer install bower to `"bower-asset"` directory everytime.
I try change try link in `composer.json`, but some yii2 module show error, but always try open `"vendor/bower"` instead of composer.json link `"vendor/bower-asset"`.

Solution of this problem: chang directory name "bower-asset" to "bower", but it's need do everytime after update yii to new version by composer, and it's not good. It's a bug and should be fixed.

**Comment by dizews** [comment]
Hello, I wrote a composer Hook for this:

```php
class ComposerHook
{
    public static function bowerLinked(Event $event)
    {
        $vendorDir = __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR;
        chdir($vendorDir);

        $bower = 'bower';
        if (file_exists($bower) || is_link($bower)) {
            $event->getIO()->write($vendorDir . $bower.' is exist');
            return;
        }

        if (symlink('bower-asset', $bower)) {
            $event->getIO()->write($vendorDir . $bower.' was created');
        } else {
            $event->getIO()->writeError($vendorDir . $bower .' error!');
        }
    }
}
```

composer.json

```json
"scripts" : {
        "post-install-cmd": [
            "ComposerHook::bowerLinked"
        ]
    }
```

**Comment by samdark** [comment]
Do you have the following line in your composer.json? https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L51

**Comment by dslpp056193** [comment]
@samdark Of course, i have this line!
But if delete "vendor" and use "composer install", inside vendor creating "bower-asset" instead of "bower".
@dizews Write good solution, but if i use framework, i want just install and work, but not fix framework bugs)
And if this bug fix in the future, i will have to clean all fixes)

**Comment by samdark** [comment]
That's weird cause it works well for me without any changes...

**Comment by cebe** [comment]
@dslpp056193 make sure you have the latest version of composer and composer asset plugin:

```
composer self-update
composer global require "fxp/composer-asset-plugin:~1.1.1"
```

**Comment by dizews** [comment]
@samdark this bug will happen unexpectedly. I could not find out concrete case for this bug.

**Comment by dslpp056193** [comment]
Yes, i updated my composer to last version before updating yii.

**Comment by quantum13** [comment]
I've just checked this issue on machine with the same trouble. It has gone after updating composer-asset-plugin
