### ISSUE TITLE
smtp transport not being used as it should

### ISSUE THREAD

**Issue by thebruins** [yiisoft/yii2#10868]
I have defined an smtp transport in my Yii2 config as follows:
```
return [
  'class' => 'Swift_SmtpTransport',
  'host' => 'smtp.googlemail.com',
  'username' => 'username',
  'password' => 'password',
  'port' => '587',
  'encryption' => 'tls',  
];
```
I do not set the username and password there because I have two Google accounts and my application decides which account should be used to send a specific email.
To set the username and password, I do this somewhere else in my application:
```
  $transport = $this->mailer->getTransport();
  $transport->setUsername('some username');
  $transport->setPassword('some password');
  $this->mailer->setTransport($transport);
```
To verify the transport method & parameters are set properly, I did a print_r($message->mailer) which shows the correct username and password during different tests.

However, eventhough $message->mailer is set properly for all emails that need to be sent, only the first message respects this; all subsequent messages are sent using the same credentials as the first message.

Could this be because Yii2 reuses the connection to Google? The first time a message is sent I see this in $message->mailer:
```
 [_buffer:protected] => Swift_Transport_StreamBuffer Object
                (
                    [_stream:Swift_Transport_StreamBuffer:private] =>
                    [_in:Swift_Transport_StreamBuffer:private] =>
                    [_out:Swift_Transport_StreamBuffer:private] =>
```
The second message shows:
```
            [_buffer:protected] => Swift_Transport_StreamBuffer Object
                (
                    [_stream:Swift_Transport_StreamBuffer:private] => Resource id #165
                    [_in:Swift_Transport_StreamBuffer:private] => Resource id #165
                    [_out:Swift_Transport_StreamBuffer:private] => Resource id #165
```
... which leads me to believe that it is using a connection that has already been established or something?

**Comment by klimov-paul** [comment]
Address your question to:
https://github.com/swiftmailer/swiftmailer
