### ISSUE TITLE
Failed logic on DataColumn

### ISSUE THREAD

**Issue by efureev** [yiisoft/yii2#10863]
![2016-02-16 14-46-01 datacolumn php](https://cloud.githubusercontent.com/assets/5524684/13072673/75aabb9c-d4bc-11e5-8edb-0169c0a7c2b0.png)

**Comment by SilverFire** [comment]
Could you elaborate it, please?

**Comment by efureev** [comment]
different logic behaviors:
```
if (($this->header !== null || $this->label === null) && $this->attribute === null) {
...
}
```
```
if ($this->header !== null || ($this->label === null && $this->attribute === null)) {
...
}
```

**Comment by SilverFire** [comment]
> different

Different from what?

P.S.: Можно по-русски

**Comment by efureev** [comment]
Разная логика для этой логической операции: 
```
(true || true) && false => false
```
```
true || (true && false) => true
```

**Comment by klimov-paul** [comment]
Original logic is correct: fallback to the parent implementation if both `label` and `attribute` is not set or `header` is set explicitely.
