### ISSUE TITLE
Ambiguity when delete table with migration tool yii v2.0.7

### ISSUE THREAD

**Issue by s-o-f** [yiisoft/yii2#10876]
I have table "products_from_store" in database.
For deleting this table with Yii Migration Tool in Yii v.2.0.7 i use console command:

`yii migrate/create drop_products_from_store`

but Yii generates migration with empty methods up and down.

There's ambiguity with commands for dropping table or column. 
Yii tries to delete column "products" from table "store".

**Comment by zelenin** [comment]
```migrate/create drop_products_from_store``` creates an empty migration with name ```drop_products_from_store```. that's all.

**Comment by s-o-f** [comment]
In yii version 2.0.7 it must add dropTable method in up();
http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#drop-table

**Comment by zelenin** [comment]
Oh, you're right.

**Comment by VirtualRJ** [comment]
I guess it is because the regex that creates the migration checks first for a combination of `drop....from` and your table name includes 'from'. Which actually tries to create a drop column which it probably cannot create.

https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php#L519

The code responsible for it:

```php
elseif (preg_match('/^drop_(.+)_from_(.+)$/', $name, $matches)) {
                $content = $this->renderFile(Yii::getAlias($this->generatorTemplateFiles['drop_column']), [
                    'className' => $className,
                    'table' => mb_strtolower($matches[2], Yii::$app->charset),
                    'fields' => $this->fields
                ]);
```

**Comment by samdark** [comment]
@VirtualRJ is correct.

**Comment by samdark** [comment]
@s-o-f any proposals on how to fix it?

**Comment by s-o-f** [comment]
Yeah, i think the name of new migration must be: "remove_column_from_table" (replace "drop" to "remove").

**Comment by samdark** [comment]
It doesn't matter for the case. `products_from_store` would still match it.

**Comment by VirtualRJ** [comment]
@samdark but it wouldn't match the 'remove' and then move to next if where it would match the drop regex

**Comment by samdark** [comment]
Right. I don't like such change though because SQL used is `drop` in both cases and Migration methods are `dropColumn()` and `dropTable()`. That would be inconsistent.

**Comment by VirtualRJ** [comment]
If it is allowed to change the command then you could do:

- `drop_..._from_table_...` (but it has the same issue as current one, but makes it even less likely to happen) or
- `drop_column_..._from_...` and `drop_table_...` (for consistency reasons)

**Comment by pana1990** [comment]
i suggest the following syntax : 

- drop_xxx_from_yyy to dropcolumn_xxx_from_yyy or dropColumn_xxx_yyy
- drop_xxx to droptable_xxx or dropTable_xxx

What do you about it?

**Comment by samdark** [comment]
Fixed by https://github.com/yiisoft/yii2/pull/11808
