### ISSUE TITLE
FR: Create multiple model from post request

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#10877]
Acording this doc http://www.yiiframework.com/doc-2.0/guide-input-tabular-input.html#creating-a-dynamic-set-of-new-records prefer we add method to encapsulation that thing.

``` php
public function actionCreate()
{
    $settings = Setting::createMultiple(Yii::$app->request->post());
    foreach($settings as $setting){
        ...
        $setting->save();
    }
}
```

Assume in the view we have javascript that can add or delete lines dynamically. We can use this to create, update, delete multiple.

``` php
public function actionCreate()
{
    $oldSettings = Setting::find()->indexBy('id')->all();
    $newSettings = Setting::createMultiple(Yii::$app->request->post(), null, $oldSettings);

    // delete unused old data
    foreach($oldSettings as $setting){
        ...
        $setting->delete();
    }

    // create new or update 
    foreach($newSettings as $setting){
        ...
        $setting->save();
    }
}
```

I can submit PR for this.

**Comment by arisk** [comment]
You could use `deleteAll` instead of deleting in a loop. But in any case I don't see why you would delete and recreate most, if not all the settings. Imagine the case where you have 100 settings but only change 1 one of them (not uncommon).

**Comment by mdmunir** [comment]
@arisk 
Thats it that i want to propose. Its only delete unused old data. If we have 100 record and just one that not posting again, we just delete one record.

**Comment by samdark** [comment]
Yes, that's a good thing to fix but it should not get too complicated.

**Comment by mdmunir** [comment]
It should be more simple than `Model::loadMultiple()`. The problem is, how to check the two model are equal. I mean, the one are model but the other are array.

**Comment by samdark** [comment]
Probably by getting an array from model via `$model->attributes`?

**Comment by mdmunir** [comment]
@samdark 
I can submit PR for this. You can review it.

**Comment by samdark** [comment]
OK. Please do.

**Comment by mdmunir** [comment]
#11271

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/10299
