### ISSUE TITLE
yii2 advanced template for multiple layers front-end

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#10875]
yii2 advanced template for multiple layers front-end

In the back all logic, modules, models, etc, in the front only controllers and views (using models by back) i have multiples front ends duplicate folder front-end?

**Comment by SilverFire** [comment]
I'm not sure, whether I've understood your question correctly, but if you have multiple front-ends on the same node, you can configure multiple hosts in your web-server to access the same document root.

If you have multiple nodes, you must deploy your project entirely.
