### ISSUE TITLE
ActiveRecord: Alias with nested relations

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2#10878]
I am starting to use the new alias possibility in 2.0.7 which sounds great.
However, I can't figure out how to use it with nested relations.

The expected sql would be:

```
select * from customer c
left join order o on o.customerid = c.customerid and o.amount=100
left join product p on p.productid = o.productid
```

But building the query:

``` php
$customer = Customer::find()
                   ->alias('c')
                   ->joinWith('order o')
                   ->joinWith('order.product p') 
                   ->addOnCondition('o.amount' => 100)
```

Gives something like:

```
select * from customer c
left join order o on o.customerid = c.customerid and o.amount=100
left join order on order.customerid = c.customerid
left join product p on p.productid = order.productid

```

Maybe using `joinWith('order o.product p')` or `joinWith('order.product o.p')`  would make sense but none are allowed.
Am I missing something?

**Comment by Alex-Code** [comment]
You need to do the second relation as an anonymous function.
```php
$customer = Customer::find()
    ->alias('c')
    ->joinWith(['order o' => function($q) {
        $q->joinWith('product p') 
            ->addOnCondition('o.amount' => 100);
    }]);
```

**Comment by CedricYii** [comment]
Thanks, you are right, it does the trick.
I will use it as a workaround. However it breaks the new magic of easily writing aliases.
I believe the syntax ``joinWith('order o.product p')`` would be clearer and should be implemented.

**Comment by Alex-Code** [comment]
Each call to `joinWith` will be treated as a new join, it doesn't check to see if the relation has previously been specified.

**Comment by CedricYii** [comment]
I mean I would expect to be able to write:
````
$customer = Customer::find()
                   ->alias('c')
                   ->innerJoinWith('order o.product p') 
                   ->addOnCondition('o.amount' => 100)
````
(ie only one joinWith).

**Comment by CedricYii** [comment]
I was hoping that the label for this would rather be ``feature/db`` or even ``type:enhancement`` to have this writing syntax enabled.

**Comment by dynasource** [comment]
> Thanks, you are right, it does the trick.
> I will use it as a workaround.

Lets keep it simple for now by following 1 way to do it (suggested by @Alex-Code  https://github.com/yiisoft/yii2/issues/10878#issuecomment-185116346)
