### ISSUE TITLE
Missing IIS configuration in installation guide

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#10881]
Where IIS Configuration in installation guide ?

Why only apache and nginx recommended configuration ?

**Comment by SilverFire** [comment]
You're right, there is no configuration example for Microsoft IIS since there were no requests and for sure it's not the most popular platform in the community.
However, we are glad to add update the guide and add a sample IIS config.

Would you like to provide a PR?

**Comment by adiramardiani** [comment]
If I've experienced I will provide a PR, but sorry that I am still very new in IIS, so I do not know **best practice** in installation yii2 for IIS :(

**Comment by samdark** [comment]
Won't be implemented in 2.0.
