### ISSUE TITLE
Invalid parameter in MessageFormatter

### ISSUE THREAD

**Issue by laxity7** [yiisoft/yii2#10884]
Yii 2.0.7 (in Yii 2.0.6 there is no this error)

![image](https://cloud.githubusercontent.com/assets/6792144/13111998/0b005804-d59a-11e5-97e3-c0b28ae260e1.png)

on line 100 MessageFormatter, where `$params = $newParams; ` $newParams returns null, expected an array.

The error is solved simple determination of `$newParams` as empty array:

```
$newParams = [];
$pattern = $this->replaceNamedArguments($pattern, $params, $newParams);
$params = $newParams;
```

**Comment by cebe** [comment]
what is the code you call that makes this fail? Also in my code the lines number is 108, not 109, are you sure you have used the original yii code?

**Comment by laxity7** [comment]
oh, sorry. 
yes, it I try to fix this error and add a line '$newParams = [];' to the line 98

**Comment by cebe** [comment]
adding `$newParams = [];` normally should not be necessary. We need a way to reproduce the error to fix it properly. can you show the code that fails? Seems to be related to a message you pass to a string validator.

**Comment by laxity7** [comment]
Simple example, 
```
$message = 'Incorrect password (length must be from {min, number} to {max, number} symbols).';
Yii::$app->getI18n()->format($message, ['attribute' => 'password'], Yii::$app->language);
```

Or take a clean yii framework with basic template, put this rule of validation for LoginForm:
`['username', 'string', 'min'=> 0, 'max'=>10, 'message' => 'Incorrect username (length must be from {min, number} to {max, number} symbols).'],`
and receive the error message

**Comment by cebe** [comment]
> in Yii 2.0.6 there is no this error

dependend on the version of intl extension there could have been an error.

I have reproduced the issue.

**Comment by cebe** [comment]
Fixed, thanks for reporting!
