### ISSUE TITLE
ActiveRecord: alias in relation

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2#10883]
Dynamic aliases in relation seem to be missing. Consider this example:
````php
class Customer {
...
  public function getOrders()
  {
      return $this->hasMany( Order::className(), ['customerid' => 'customerid'] )
                  ->andOnCondition( [ 'statusid' => 1 ] );
  }
...
}
````
Then
````php
$customer = Customer::find()
                   ->alias( 'c' )
                   ->innerJoinWith('orders o');
````
Build the query:
````
select customer.* from customer c
join order o on o.customerid = c.customerid 
where statusid = 1
````
So the alias has been applied on customerid but not on statusid in the getOrders relation.
Which is likely to result in a ``column ambiguously defined`` error (as statusid is in every tables).

Is there a way to define 
````php
public function getOrders()
{
      return $this->hasMany( Order::className(), ['customerid' => 'customerid'] )
                 //add dynamic alias here with $this->getCurrentRelationAlias()
                  ->andOnCondition( [ $this->getCurrentRelationAlias() . '.statusid' => 1 ] ); 
}

````
so that all the conditions can be aliased dynamically (a same relation may be used several times with different aliases)?
As Yii is able to know the alias of order in the hasMany() part for this relation, I guess it should be able to recall it in the OnCondition part?

(Issue [https://github.com/yiisoft/yii2/issues/7263] doesn't seem to deal with conditions added inside relations; but I may misunderstand).

**Comment by cebe** [comment]
> (Issue [#7263] doesn't seem to deal with conditions added inside relations; but I may misunderstand).

it does. I do not see how this is different from #7263

**Comment by CedricYii** [comment]
Examples in #7263 are putting emphasis on columns' aliases. Here my main concern is about using the same table in different relations with different aliases. Consider this example:
````php
class Order {
...
  //first relation with table COMPANY
  public function getCustomer()
  {
      return $this->hasOne( Company::className(), ['id' => 'customerid'] ) //table COMPANY
                  ->andOnCondition( [ 'type' => 'customer' ] );
  }

  //second relation with table COMPANY
  public function getSupplier()
  {
      return $this->hasOne( Company::className(), ['id' => 'supplierid'] ) //table COMPANY
                  ->andOnCondition( [ 'type' => 'supplier' ] );
  }
...
}
````
Then we could write
````php
$orders = Order::find()
                   ->alias( 'o' )
                   ->innerJoinWith('customer c')
                   ->innerJoinWith('supplier s');
````
To build query
````sql
select o.* from order o
join company c on c.id = o.customerid and c.type = 'customer'
join company s on s.id = o.supplierid and s.type = 'supplier'

````

**Comment by cebe** [comment]
can you please post that in  #7263, it fits the topic perfectly. here it will get lost.
