### ISSUE TITLE
global-events

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#10899]
is not global event: http://www.yiiframework.com/doc-2.0/guide-concept-events.html#global-events
global event:
```php
Event::on(ActiveRecord::className(), ActiveRecord::EVENT_AFTER_INSERT, function ($event) {
    Yii::trace(get_class($event->sender) . ' is inserted.');
});
```

**Comment by SilverFire** [comment]
Could you elaborate why it is not a global event?

**Comment by lynicidn** [comment]
@SilverFire in doc example is app event

if i want create global event for all app i should write
Event::on(\yii\base\Application::class, 'myEvent', $handler);

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/e8d309dddb6e12a0c07891ef2f6d95cef83acc70/framework/base/Event.php#L52

https://github.com/yiisoft/yii2/blob/e8d309dddb6e12a0c07891ef2f6d95cef83acc70/framework/base/Event.php#L90

**Comment by SilverFire** [comment]
This article is about new feature for 2.0.7, that allows to bind event to the interface

**Comment by lynicidn** [comment]
спорить или доказывать не буду, оставлю для потомков
Event::on('yii\base\Component', 'event', $handler) - global event for all components

**Comment by samdark** [comment]
@lynicidn предложение переименовать что есть в application-wide events?

**Comment by lynicidn** [comment]
@samdark а смысл переименовывать, там показаны обычные события компонента, любого, просто на примере приложения

просто это вводит в заблуждение людей, на гиттере в англочатике был вопрос по глобальным событиям, и человек реально не въезжал

**Comment by samdark** [comment]
Так в чём преложение?

**Comment by lynicidn** [comment]
ну можно и переименовать, но смысл, что глобальные события не раскрыты в документации

**Comment by samdark** [comment]
С компонентом получается тоже не совсем глобальное.

**Comment by lynicidn** [comment]
можно завязаться на хелпер
Event::on(Yii::class, 'eventName', $handler);
а вызывать Event::trigger(Yii::class, 'eventName', $event)
надо тестить, но думаю проблем не будет

**Comment by lynicidn** [comment]
и проверять вначале события на объекте, классе, а потом на хелпере если не найдено, как вариант, но класс там обязателен, т.к. там смотрит всех его предков

**Comment by samdark** [comment]
Ну так это фактически то же, что и на application.

**Comment by samdark** [comment]
Подумаю, как можно в этом месте улучшить доку.

**Comment by lynicidn** [comment]
не то же,
Yii ты не создаешь объект и у него нет ->trigger метода
а у приложения есть

**Comment by lynicidn** [comment]
в текущем контексте события приложенияи события глобальные это одно и тоже

**Comment by samdark** [comment]
Подумал-подумал и решил, что случай слишком специфичен, чтобы его отдельно раскрывать.
