### ISSUE TITLE
Authorization rules ips possible bag

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2#10898]
Yii 2.0.7, PHP 7

````php
class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'signup'],
                        'allow' => false,
                        'ips' => ['156.67.89.0'],
                    ],`
````
from localhost ::1 at the login and signup pages returns Forbidden (#403)

**Comment by SilverFire** [comment]
Are you talking about the IPv6 address?

**Comment by rumatakira** [comment]
Not necessary. Logically, this should not happen.

**Comment by SilverFire** [comment]
So you thing there is a BC break somewhere?

**Comment by rumatakira** [comment]
I am just convert IPv4 to IPv6 in the rule - result the same

**Comment by SilverFire** [comment]
So did the behavior changed from 2.0.6 to 2.0.7?

**Comment by cebe** [comment]
1. which action are you trying to access?
2. the default rule is deny all, so your code currently does not allow any access to `['login', 'signup']` actions.

**Comment by rumatakira** [comment]
1. The behavior the same with IPv4 and IPv6.
2. Both actions 'login' and 'signup' blocked with (403) for access from localhost, no matter what IP or IPs specified in rule

**Comment by cebe** [comment]
you have specified 2 rules:

one for the action 'logout' that allows access for all logged in users. and another that denies all users from `['login', 'signup']` that have IP 156.67.89.0. There is no further rule, so everyone else is denied too. You need a rule that allows others on ['login', 'signup'] afterwards.

**Comment by rumatakira** [comment]
Works. Only for IPv6 addresses.

**Comment by cebe** [comment]
added a test to verify AccessRule works as expected.

**Comment by rumatakira** [comment]
Thank you!
