### ISSUE TITLE
AssetConverter command override with main-local

### ISSUE THREAD

**Issue by kirsenn** [yiisoft/yii2#10895]
I have two different converter engines for different environments for scss files.
My config files are:
main.php:
```
'assetManager' => [
            'baseUrl' => '/assets',
            'converter' => [
                'commands' => [
                    'scss' => ['css', 'scss -E UTF-8 {from} {to}']
                ]
            ],
```
main-local.php:
`...'scss' => ['css', 'sassc {from} {to}']...`

What I expected to get in final $config after merging it with `yii\helpers\ArrayHelper::merge` and passed to yii\web\Application:
```Array
(
    [0] => css
    [1] => sassc {from} {to}
)
```
What I really got:
```
Array
(
    [0] => css
    [1] => scss -E UTF-8 {from} {to}
    [2] => css
    [3] => sassc {from} {to}
)
```

I know that is normal ArrayHelper::merge behavior: "For integer-keyed elements, the elements from the latter array will be appended to the former array."
Why not to use string keys like:
`'scss' => ['ext => ''css', 'command' => 'sass {from} {to} --sourcemap'],`

**Comment by Faryshta** [comment]
i don't see how to fix it without a bc break. Your solution seems spot on how to solve it.

**Comment by klimov-paul** [comment]
Since #11899 merged you can replace the `commands` key.
