### ISSUE TITLE
$_SESSION not found on user controller

### ISSUE THREAD

**Issue by shubham994** [yiisoft/yii2#10893]
In my web app i am using auth token. So on logout I am deleting this auth token. I have saved auth token in $_SESSION. When i print $_SESSION on logout action, it is empty. I am able to get $_SESSION in every controller except this controller. I am using this controller for login, forgot password, verify mail,  reset password and logout. This controller does not have access control while other controllers have access controls.

**Comment by ZAYEC77** [comment]
@shubham994 You can use `Yii::$app->session` component.

**Comment by LeePenn** [comment]
Check if session is open

**Comment by ZAYEC77** [comment]
@shubham994 what about method `Yii::$app->session->getIsActive()`?

**Comment by shubham994** [comment]
In user controller  `Yii::$app->session->isActive`  returns nothing where as in other controllers it returns 1.

Also if I stop logout and go back to other controller I get my values in $_SESSION.

**Comment by SilverFire** [comment]
I guess the problem relates to nested call of magic methods, which is not supported in PHP.

Try `Yii::$app->session->getIsActive()`, as @ZAYEC77 suggested, it should work as expected. Otherwise - please, let us know.

**Comment by shubham994** [comment]
@SilverFire I am not getting anything in `Yii::$app->session->getIsActive()` in user controller where as elsewhere it is working fine.

**Comment by SilverFire** [comment]
> I am not getting anything

What is anything?) Is it `NULL`?

**Comment by shubham994** [comment]
yes it is `Null`

**Comment by SilverFire** [comment]
Please, give us the exact way to reproduce the problem on the clean application installation

**Comment by shubham994** [comment]
It is working now. I had not written these behavioursin the controller
`public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }`   

I am unable to understand the reason behind this tho.

**Comment by shubham994** [comment]
@SilverFire Can you please explain why I had to add above behaviour to get $_SESSION in logout action.

**Comment by SilverFire** [comment]
Are you on 2.0.7?

**Comment by shubham994** [comment]
Yes I am on 2.0.7

**Comment by SilverFire** [comment]
Please, give us the exact step-by-step way to reproduce the problem on the clean application installation

**Comment by shubham994** [comment]
Just remove the behaviours on logout action in site controller. You will get an empty array in $_SESSION.

**Comment by SilverFire** [comment]
It's expected because the framework does not start the session unless it's required.

```php
    public function actionLogout()
    {
        echo "Just on action run:<br>";
        var_dump($_SESSION);

        Yii::$app->user->getIsGuest();
        echo "After session open:<br>";
        var_dump($_SESSION);
        
        Yii::$app->user->logout();

        echo "After logout:<br>";
        var_dump($_SESSION);

        Yii::$app->end();
        //return $this->goHome();
    }
```

**Comment by shubham994** [comment]
Thanks @SilverFire got it now.
