### ISSUE TITLE
error while uploading file (rule error)

### ISSUE THREAD

**Issue by postolachiserghei** [yiisoft/yii2#10906]
hi
after update to last release i faced a problem while working on uploading a file, i think that this is a bug because   : 

result after submit form -> 
$_FILES:
Array
(
    [TestForm] => Array
        (
            [name] => Array
                (
                    [image] => 
                )

            [type] => Array
                (
                    [image] => 
                )

            [tmp_name] => Array
                (
                    [image] => 
                )

            [error] => Array
                (
                    [image] => 4
                )

            [size] => Array
                (
                    [image] => 0
                )

        )

)
$_POST:
Array
(
    [_csrf] => YnhUdW0xT0gWLRdFK119egEvACRbZHsKAxkTByIHYi9VOxEwJn8ECg==
    [TestForm] => Array
        (
            [image] => 
        )

)
$model->getErrors():
Array
(
    [image] => Array
        (
            [0] => Please upload a file.
        )

)

my code is : 
model -> 
class TestForm extends Model
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%test}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['image'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'image' => 'Image',
        ];
    }

}

controller-> 
public function actionTest()
    {
        $model = new \app\models\forms\TestForm();
        if (yii::$app->request->isPost) {
            if (Yii::$app->request->isAjax) {
                die(Json::encode(ActiveForm::validate($model)));
            }
            if($model->validate()){
                $model->save();
            }else{
                
                $print_r = '<pre>';
                $print_r .= print_r($_FILES, true);
                $print_r .= '</pre>';
                echo '$_FILES:<br/>'.$print_r;
                
                $print_r = '<pre>';
                $print_r .= print_r($_POST, true);
                $print_r .= '</pre>';
                echo '$_POST:<br/>'.$print_r;
                
                $print_r = '<pre>';
                $print_r .= print_r($model->getErrors(), true);
                $print_r .= '</pre>';
                echo '$model->getErrors():<br/>'.$print_r;
                die();
            }
        }

view->
$form = ActiveForm::begin([
            'options' => ['enctype' => 'multipart/form-data'],
            'enableAjaxValidation' => false,  //tested also with  enabled validation
            'enableClientValidation' => false,
        ]);
?>
<?= $form->field($model, 'image')->fileInput(); ?>
<div class="form-group">
    <?= Html::submitButton('submit', ['class' => 'btn btn-primary']) ?>
</div> 

<?php ActiveForm::end(); ?>

**Comment by MysteryDragon** [comment]
It's not automatic operation. You must upload your file, described here (pay attention on Controller): [Uploading Files - Yii2 Guide](http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html)
