### ISSUE TITLE
Feature Request: Add filter hook for key value in ArrayaHelper::map

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#10904]
how about adding filter hook to key and value of final array for `ArrayHelper::map`,

I am having this use case, I am fetching data from Database but when I generate my array using map, I want my keys to be encrypted using some logic.

```php
$array = [
  [
     'id' => '1', 'name' => 'name1 here'
  ],
  [
     'id' => '2', 'name' => 'name2 here'
  ]
]
```

final array would be like below:

```php
[
 'encrypt of id 1' => 'name1 here',
 'encrypt of id 2' => 'name2 here'
]

```

better suggestion most welcome!

**Comment by quantum13** [comment]
`ArrayHelper::map` accepts closures in $from, $to and $group

**Comment by SilverFire** [comment]
@quantum13 thank you
