### ISSUE TITLE
The proposal to add to ActiveRecord::setAttribute return $this

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#10907]
You will be able to do:
```php
$modelActiveRecord->setAttributes($datum, false)->save();
```

**Comment by SilverFire** [comment]
I believe it was already discussed, but I can't find an issue and don't remember a decision =/

I've tagged it with BC breaking tag, thus assigned it to the 2.1.x milestone.

There are other void methods, that may be enhanced in same way, but it's a disputable question, whether we need it

**Comment by DrDeath72** [comment]
Тогда уже это делать ко всем сеттерам и везде :)

**Comment by githubjeka** [comment]
@SilverFire BC why? Old code will work

```php
$model->setAttribute();
//do something 
$model->save();
```

**Comment by taxp** [comment]
@SilverFire This one,  eh? [https://github.com/yiisoft/yii2/issues/7331](url)

**Comment by SilverFire** [comment]
@taxp yes, you're right, thank you!
