### ISSUE TITLE
Dependency Injection for Closure configuration

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10908]
Currently an element in the `component` applciation configuration can be a closure:
```php
    'components' => [
        'pheanstalk' => function() {
            $result = new \Pheanstalk\Pheanstalk('localhost');
            $result->watch('daily');
            return $result;
        },
```

This is fine, but does not work when my object depends on other components and I want to use DI:
```php
    'components' => [
        'pheanstalk' => function(yii\web\User $user) {
            $result = new \Pheanstalk\Pheanstalk('localhost');
            $result->watch($user->getId());

            return $result;
        },
```

Since we now have `Container::invoke` we could simply use that:
```php
public static function createObject($type, array $params = [])
    {
        if (is_string($type)) {
            return static::$container->get($type, $params);
        } elseif (is_array($type) && isset($type['class'])) {
            $class = $type['class'];
            unset($type['class']);
            return static::$container->get($class, $params, $type);
        } elseif (is_callable($type, true)) {
            return call_user_func($type, $params);
        } elseif (is_array($type)) {
            throw new InvalidConfigException('Object configuration must be an array containing a "class" element.');
        } else {
            throw new InvalidConfigException('Unsupported configuration type: ' . gettype($type));
        }
    }
```

Changing `call_user_func($type, $params)` to `Yii::$container->invoke($type, [$params]);` would be backwards compatible.
1. It adds an array around `$params`, making it the first positional argument.
2. Invoke will fill any dependencies then pass the `$params` array (which is never set in this use case) as the first positional argument that is not explicitly type hinted for DI.

**Comment by samdark** [comment]
Sounds interesting. @yiisoft/core-developers what's your opinion?

**Comment by qiangxue** [comment]
:+1:

**Comment by SilverFire** [comment]
:+1:

**Comment by SamMousa** [comment]
#10931

Note: Currently there is a circular dependency between the container and the app, I have removed this dependency by checking if `Yii::$app` is an instance of `\Yii\base\Application`.
While the practical need for using Yii's DI container without a Yii app might be minimal, it makes testing easier and circular dependencies should be avoided if possible, right?

**Comment by samdark** [comment]
Yes.

**Comment by SamMousa** [comment]
Hmm, can I mention @yiisoft/core-developers?

The implementation is essentially ready, just need to know if I should fix the test or the container (see @klimov-paul  comments in PR)
