### ISSUE TITLE
Rest - problem with custom response format

### ISSUE THREAD

**Issue by kiros32** [yiisoft/yii2#10905]
I tried to customize my response format with instructions that I found here - http://www.yiiframework.com/doc-2.0/guide-rest-error-handling.html

    'components' => [
        'response' => [
            'class' => 'yii\web\Response',
            'on beforeSend' => function ($event) {
                $response = $event->sender;
                if ($response->data !== null && Yii::$app->request->get('suppress_response_code')) {
                    $response->data = [
                        'success' => $response->isSuccessful,
                        'data' => $response->data,
                    ];
                    $response->statusCode = 200;
                }
            },
        ],
    ],

Yes it works, but I started to get exception 'yii\base\InvalidParamException' with message 'Response content must not be an array.'

What am I doing wrong? What should I return instead of array?

**Comment by kiros32** [comment]
I also found that this happens when I use browser to send simple GET request to my api.
My controller extends \yii\rest\ActiveController.
But it seems like application smart enough to understand that I using browser and it tries to send me regular web response, not json or array.

**Comment by CedricYii** [comment]
Have you checked the accepted format of your browser?
See [Content Negociation in the guide](http://www.yiiframework.com/doc-2.0/guide-rest-response-formatting.html)

**Comment by kiros32** [comment]
Yes, contentNegotiator helped me already.
