### ISSUE TITLE
ActiveRecord: Alias syntax in ActiveQuery::joinWith()

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2#10900]
The actual syntax to build a relation with an alias is
````
$customer = Customer::find()
                   ->innerJoinWith('orders o');
````
And it works (it is great to have this new feature). However it involves relying on regex (which I'd rather avoid as it could lead to overcomplicated troubles and possibly performance issue) and I feel like it could be confusing to use a db like syntax whereas orders in not a table name here.

Why not also allowing to use the syntax already used in Query::select() , Query::from() or Query::join()? Like:
````
$customer = Customer::find()
                   ->innerJoinWith( ['o' => 'orders'] );
````
This would make parsing easier (skip regex), coding clearer and may give better consistency between methods of the framework.

**Comment by cebe** [comment]
there is already a different way of using an array for joinWith. this will conflict with the syntax you propose.

**Comment by CedricYii** [comment]
I agree but I believe the BC may not be a sufficient reason to avoid consistency within the framework.

However it seems that if first and second elements are [string => string], they could be treated differently (as opposed to [string => function] or [integer => string] for the actual syntax).
