### ISSUE TITLE
i18 trouble - Invalid Parameter

### ISSUE THREAD

**Issue by blessedness** [yiisoft/yii2#10901]
my config:
`
'language'=>'ru-RU',`

        'i18n' => [
            'translations' => [
                '*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en-US',
                ],
            ],
        ],

in view, use 
`<?= \Yii::$app->formatter->asCurrency($model->working_hour, 'грн.'); ?>`

and get error 

`Invalid Parameter – yii\base\InvalidParamException`
`Formatting currency value failed: 1 Number formatting failed: U_ILLEGAL_ARGUMENT_ERROR`

set currency in latin - all good,
set currency without dot ('грн') - empty currency and no errors

**Comment by cebe** [comment]
> @param string $currency the 3-letter ISO 4217 currency code indicating the currency to use.

what you passed there is not an ISO currency code.
