### ISSUE TITLE
Unnesessary extra exceptions are created by `views/errorHandler/exception.php` itself

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#10919]
With Chrome developer tools or Firefox Firebug enabled extra `yii\web\NotFoundHttpException` occurs (file `sizzle.min.map` not found).

Because of that line I guess:

https://github.com/yiisoft/yii2/blob/master/framework/views/errorHandler/exception.php#L402

```
//@ sourceMappingURL=sizzle.min.map
```

Imo, shoulld be removed to avoid irrelevant log records.

**Comment by cebe** [comment]
yes, should be removed.

**Comment by SamMousa** [comment]
While I understand the preference for not including external javascript files on an error page, would it not be acceptable to instead:
1. Require sizzle via "bower-asset/sizzle"
2. Include the non-minimized file via `file_get_contents()`

Added advantage would be a more clearly defined dependency.

**Comment by cebe** [comment]
I would not consider this very simple: https://github.com/yiisoft/yii2/blob/master/framework/views/errorHandler/exception.php#L440 :) I'd just remove it now and leave it as is.

**Comment by SamMousa** [comment]
@cebe Ok if I create new issue for cleaning that up then?
--> regardless of simplicity the framework would be improved by removing a possibly unnecessary dependency ;-)

**Comment by cebe** [comment]
feel free to work on that if you think Sizzle can be easily removed from error page.
