### ISSUE TITLE
Prepend ini_set with error suppressor (@)

### ISSUE THREAD

**Issue by alexjeen** [yiisoft/yii2#10914]
On our production enviroments, ini_set is not allowed due to security reasons;

    Warning: ini_set() has been disabled for security reasons in /......../vendor/yiisoft/yii2/base/ErrorHandler.php on line 58

Prepending @ to ini_set in both ErrorHandler.php suppresses the warning.

**Comment by samdark** [comment]
Almost anything could be disabled via `disable_functions`. I don't think it's a good idea to supress every possible function call.
