### ISSUE TITLE
Баг капчи в модуле

### ISSUE THREAD

**Issue by obuhovski** [yiisoft/yii2#10910]
Инпут:
```php
<?= $form->field($commentForm,'captcha') ->widget(\yii\captcha\Captcha::classname(), ['captchaAction'=>'/main/site/captcha'])?>
```
Правило:
```php
['captcha', 'captcha','captchaAction'=> '/main/site/captcha'],
```

Капча используется на странице /blog/post/post1, но сам экшн по адресу /main/site/captcha.

Проблема в том, что проходит только первоначальное значение капчи. При дальнейшем обновлении, картинка меняется, но принимает все равно только первое значение.

Методом проб и ошибок установил, что проблема в строке:
https://github.com/yiisoft/yii2/blob/master/framework/captcha/Captcha.php#L153
Т.е. в JS приходит 2 слеша:
yiiCaptcha//main/site/captcha.

**Comment by SilverFire** [comment]
У вас Yii 2.0.7?

**Comment by obuhovski** [comment]
Да

**Comment by obuhovski** [comment]
Если указать адрес без первого слеша, то картинка отображаться не будет. Т.к. это относительный адрес и он преобразуется в "/blog/main/site/captcha"

**Comment by prog-man** [comment]
Присоединяюсь к этой проблеме, только в моем случае экшн капчи и модуль формы и контроллер - все находится в одном модуле, проблема именно когда в модуле происходит все действие. Здесь описал проблему: http://www.yiiframework.ru/forum/viewtopic.php?f=19&t=35535&p=181339#p181339

Версия: 2.0.7

**Comment by nsept** [comment]
+1 В точности такая же проблема как у @prog-man
