### ISSUE TITLE
Add shortcut relation syntax feature for DetailView like GridView widget

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#10923]
```php
//GridView
[
'attribute' => 'category',
'value' => 'category.name'
],
```

With grid view for get relation is work with shortcut feature
https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L180

But for DetailView is not have feature for this, with configuration above only show string `category.name` in rendered output 
must manually like :
```php
//ListView
[
'attribute' => 'category',
'value' => $model->category->name,
],
```
https://github.com/yiisoft/yii2/blob/master/framework/widgets/DetailView.php#L39

**Comment by SilverFire** [comment]
GridView is designed to work with a set of models, while DetailView is used to represent the only model.
Therefore, implicit value definition makes no sense. Also, it's a major BC break, so this idea can not be accepted.

**Comment by samdark** [comment]
There's no real sense doing so because you can use `$model->category->name` directly unlike GridView which requires more code.

**Comment by cebe** [comment]
> you can use $model->category->name directly

You can not if `$model->category` could be null.

@adiramardiani this feature also exists in DetailView, you just have to use it like this:

```php
'attribute' => 'category.name'
```
not
```php
'value' => 'category.name'
```
