### ISSUE TITLE
Rest API and ActiveDataProvider with relation query issue

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2#10927]
In Rest api, When add a relation query:
```php
$query = User::find();
$query->with(['test']);

$dataProvider = new ActiveDataProvider([
    'query' => $query,
]);

return $dataProvider;
```
the relation data `test` not loaded in the response. But when use this query without DataProvider and pagination it's work and return `test` relationship information:
```php
return $query->asArray()->all();
```
the above code with ActiveDataProvider work with GridView.

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/10180

**Comment by jafaripur** [comment]
@SilverFire Why this issue closed? also #10180 is closed!
I this issue is critical...

**Comment by fernandezekiel** [comment]
@jafaripur the structure of the response objects in rest api is not dictated by the dataprovider but the fields() and extraFields() of the model's instance have a look in the docs

**Comment by jafaripur** [comment]
@fernandezekiel I use rest controller instead ActiveController. I think this is normal to use rest controller to return active data provider. This can be do but the relationship not fetched. Any one have a solution for this issue!

**Comment by fernandezekiel** [comment]
i don't think you have read this part then
http://www.yiiframework.com/doc-2.0/guide-rest-resources.html

**Comment by jafaripur** [comment]
@fernandezekiel  I read it. Check the latest section about ActiveDataProvider. I use ``yii\rest\Controller`` for my rest api and custom query and customization.

Why ActiveDataProvider in rest controller doesn't return relationship data. Check my question in this first post.

**Comment by jafaripur** [comment]
@samdark @SilverFire Why this issue is closed? I think this is a bug in rest controller API for return relation data.

**Comment by samdark** [comment]
Because it's a duplicated of #10180

**Comment by githubjeka** [comment]
return $dataProvider->getModels();

**Comment by kirill-konshin** [comment]
```
$dataProvider->getModels()
```

Does not work.

The thing that works is in your main model (which has other things) you should do:

```php
public function fields()
{
    $json = parent::fields();
    $json['photo'] = function () {
        return $this->photo ? $this->photo->toArray() : null;
    };
    return $json;
}

public function getPhoto()
{
    return $this->hasOne(Photo::className(), ['id' => 'photoId']);
}
```

But I think this case should be somehow covered by shorthand methods.

**Comment by rattanan** [comment]
$dataProvider->query->with(["departments", "statuses"])->asArray()->all()
