### ISSUE TITLE
Can I pass null values to UrlManager->createUrl? If I can than UrlManager has issue.

### ISSUE THREAD

**Issue by eresik** [yiisoft/yii2#10935]
Can I use UrlManager so? 
```
// at UrlManager config
'rules'=>[
   ['<param1>/<param2>'=>'site/index'], //rule1
   ['<param1>'=>'site/index'], //rule2
   
]
...
//some file
Url::to([
 'site/index',
 'param1'=>'blablabla',
 'param2'=>isset($foo)?$foo->someVar:null, //if null - use rule2, else use rule1
]);
```
i.e. pass null when dont use param.

If such use is prohibited, it is necessary to specify in the documentation.
Because such use leads to unpredictable behavior. Sometimes works, sometimes does not work, 
depending on the order createUrl calls.

in any case unpredictable behavior it is very difficult to track error.

**Comment by cebe** [comment]
This is expected, `null` means "not set" that would be the equivalent of the parameter not being provided in the URL so rule2 fits.

**Comment by eresik** [comment]
Than its UrlManager issue.
```
echo Url::to(['site/index','param1'=>111,'param2'=>null]); 
echo Url::to(['site/index','param1'=>111,'param2'=>222]); 
```
output: 
/111
/111?param2=222

reverse order same Url::to calls:
```
echo Url::to(['site/index','param1'=>111,'param2'=>222]); 
echo Url::to(['site/index','param1'=>111,'param2'=>null]); 
```
output as expected: 
/111/222
/111

**Comment by eresik** [comment]
Possible reason.
Look at:
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L318
```
$cacheKey = $route . '?' . implode('&', array_keys($params));
```
need filter $params and unset null values
