### ISSUE TITLE
filter missing from pagination

### ISSUE THREAD

**Issue by paglasoft** [yiisoft/yii2#10936]
Hi, when I search for something in a Grid view, it return results based on filter but when i click on pagination link(next page) filter get removed.

**Comment by mdmunir** [comment]
its going ok in my local.

**Comment by cebe** [comment]
same here, unable to reproduce.

**Comment by tomofu74** [comment]
Same problem?
https://stackoverflow.com/questions/69316202/how-to-save-gridview-filters-for-pagination-in-yii2
