### ISSUE TITLE
Endless directory create loop after defining $sourcePath in AppAsset.php

### ISSUE THREAD

**Issue by AntoninSlejska** [yiisoft/yii2#10933]
I receive the following error message:

Failed to create directory "C:\xampp\htdocs\yii\frontend\web\assets\ **1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209\assets\1bc5b209** ": mkdir(): No such file or directory

after defining the sourcePath in \yii\frontend\assets\AppAsset.php:
```
namespace ap1_epas\assets;

use yii\web\AssetBundle;

class AppAsset extends AssetBundle {

    public $sourcePath = '@webroot';
    // public $basePath = '@webroot';
    // public $baseUrl = '@web';
    public $css = [
        'css/fix_bootstrap.css',
        'css/light.css',
        'css/toastr.min.css',
        'css/font-awesome.css',
    ];
    public $js = [
        'js/jquery.blockUI.js',
        'js/jquery.cookie.js',
        'js/toastr.min.js',
        'js/custom.js',
    ];
    public $jsOptions = array(
        'position' => \yii\web\View::POS_HEAD
    );
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];
}
```

In the directory \yii\frontend\web\assets is created a new directory **1bc5b209**, which contains directory **assets**, which contains directory **1bc5b209**, ...

In the head of the website is the following (correct) code:

```
<head>
...
<link href="/yii/frontend/web/assets/1bc5b209/css/fix_bootstrap.css" rel="stylesheet">
<link href="/yii/frontend/web/assets/1bc5b209/css/light.css" rel="stylesheet">
<link href="/yii/frontend/web/assets/1bc5b209/css/toastr.min.css" rel="stylesheet">
<link href="/yii/frontend/web/assets/1bc5b209/css/font-awesome.css" rel="stylesheet">
...
<script src="/yii/frontend/web/assets/1bc5b209/js/jquery.blockUI.js"></script>
<script src="/yii/frontend/web/assets/1bc5b209/js/jquery.cookie.js"></script>
<script src="/yii/frontend/web/assets/1bc5b209/js/toastr.min.js"></script>
<script src="/yii/frontend/web/assets/1bc5b209/js/custom.js"></script>
</head>
```

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/3030, https://github.com/yiisoft/yii2/issues/10710

**Comment by AntoninSlejska** [comment]
The solution:
Copy the css, js,... files to the directory: **\yii\frontend\assets** and change the public $sourcePath to ''**@app/assets**';
