### ISSUE TITLE
AccessControl does not redirect login

### ISSUE THREAD

**Issue by kiuka** [yiisoft/yii2#10934]
Hello,

I just updated to 2.0.7, and it seems something wrong with user handling. After the session expiry, it does not redirect to the login screen.

Controller (it should not match to guests, according to the documentation):

```
class DefaultController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => \yii\filters\VerbFilter::className(),
                'actions' => [
                ],
            ],
        ];
    }
}
```

It works well with 2.0.6.

**Comment by samdark** [comment]
So you log user in, wait for session expiry and hitting refresh in the browser?

**Comment by samdark** [comment]
What do you get exactly?

**Comment by kiuka** [comment]
Yes, exactly. I get an error, because the controller trying to use the user data, that is not exist (\Yii::$app->user->identity is null).

**Comment by kiuka** [comment]
For be more specific: it should redirect when a guest try to access to the controller, due to the AccessControl.

The documentation says everything else is denied, if set at least one rule (http://www.yiiframework.com/doc-2.0/yii-filters-accesscontrol.html):

```
            'rules' => [
                // deny all POST requests
                [
                    'allow' => false,
                    'verbs' => ['POST']
                ],
                // allow authenticated users
                [
                    'allow' => true,
                    'roles' => ['@'],
                ],
                // everything else is denied
            ],
```

I tried to reverse the core to 2.0.6, and it is working after the downgrade.

**Comment by samdark** [comment]
What is the error you're getting? Text, stacktrace, file, line number?

**Comment by samdark** [comment]
btw., what happends if you're not loggin in at all i.e. open a browser private tab and going to that page?

**Comment by kiuka** [comment]
I have found the problem. 

I use beforeAction in my controllers, and it ruins the AccessControl check if I return true instead the return value of the parents beforeAction method.

I dont know if this is a bug, or not, but it definitely has changed since the last version:)

Controller:

```
class ExampleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action);

        // do some stuff here

        return true;
    }
}

```

**Comment by samdark** [comment]
No, it did not. It's like that from the very beginning of Yii 2: https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L245

**Comment by samdark** [comment]
I'll check this with latest version on a basic app.

**Comment by samdark** [comment]
Tried on basic app. It works well redirecting to login even if `beforeAction` returns `true`.

**Comment by kiuka** [comment]
I use advanced app, I've tested on a bare app, but it only fails, when I enable pretty url-s, and doesnt call the parent method inside controllers beforeAction. I dont really understand why is it fails in my project, but doesnt matter, it works if I do call it:)

so thanks anyway.

**Comment by PonyPC** [comment]
dude! I meet the same problem!!!
someone can execute in actions without auth.....

**Comment by PonyPC** [comment]
I can see a lot of errors in app.log.
In some action, it is need user id for search, cause nothing is provided, it will genenate an app exception in app.log
Imaging if there is some critical code can only be operated by authored user...

**Comment by samdark** [comment]
@PonyPC can you help reproducing it starting with basic app template?

**Comment by kiuka** [comment]
@PonyPC you should return the parent method (return parent::beforeAction(); ), and than it should be ok.
As I remember, it was because some i18n modul, but Im not sure:(
