### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by ominds** [yiisoft/yii2#10944]
/**
     * Executes the query and returns a single row of result.
     * @param Connection $db the database connection used to execute the query.
     * If this parameter is not given, the `db` application component will be used.
     * @return array|boolean the first row (in terms of an array) of the query result. False is returned if the query
     * results in nothing.
     */
    public function one($db = null);

I think this documentation is wrong, this function returns null, not boolean False

**Comment by Alex-Code** [comment]
It depends which class you're calling the method on.

http://www.yiiframework.com/doc-2.0/yii-db-query.html#one()-detail returns false
http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#one()-detail returns null

**Comment by ominds** [comment]
Here's my code

$x = ExtendActiveRecord::findOne(['abc' => 11]);
var_dump($x);
// prints NULL

**Comment by ominds** [comment]
Seems to be leading me to one() in QueryInterface.php

**Comment by Alex-Code** [comment]
http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findOne()-detail returns null

**Comment by ominds** [comment]
Correct me if I'm wrong, the result depends on who implements the interface?

If so, shouldn't the documentation for the interface itself say that its return is dependent of the implementer or array|boolean|null ? I was just following my IDE intellisense and it led me to one() in QueryInterface.php which said it returned a boolean.

I'm on yii2 version 2.0.6 since documentation looks different on website, so it might just be outdated in my installation?

**Comment by Alex-Code** [comment]
`ActiveRecord` uses `ActiveRecordInterface` which says to return null.

**Comment by klimov-paul** [comment]
Duplicates #8677
