### ISSUE TITLE
UploadedFile and file extension validator

### ISSUE THREAD

**Issue by jeebus3000** [yiisoft/yii2#10948]
Model rule:
```php
   public function rules() {
        return [
            [["social_photo"], "file", "skipOnEmpty" => TRUE, "extensions" => "jpg, jpeg"],
        ];
    }
```
CRUD controller update action:
```php
    public function actionUpdate($id) {
        $oModel = $this->findModel($id);
        $bIsPopulated = $oModel->load(Yii::$app->request->post());
       
        if ($bIsPopulated) {
            $oModel->id_editor = Yii::$app->user->identity->id;
            $oModel->social_photo = UploadedFile::getInstance($oModel, "social_photo");            
            ///
            if (!! $oModel->social_photo && $oModel->validate())
                $oModel->social_photo->saveAs(sprintf(Yii::$app->params["sUploadFilePath"], Yii::getAlias("@frontendWeb"), $oModel->social_photo->baseName, $oModel->social_photo->extension));
        }

        if ($bIsPopulated && $oModel->save()) {
            return $this->redirect(["view", "id" => $oModel->id]);
        } else {
            return $this->render("update", [
                "oModel" => $oModel,
            ]);
        }
    }
```
Form field:
```html
    <?php $oForm = ActiveForm::begin(["options" => ["enctype" => "multipart/form-data"]])?>
    <?=$oForm->field($oModel, "social_photo")->fileInput(["accept" => "image/*"])?>
    
    <div class="form-group">
        <?= Html::submitButton($oModel->isNewRecord ? "Create" : "Update", ["class" => $oModel->isNewRecord ? "btn btn-success" : "btn btn-primary"])?>
    </div>

    <?php ActiveForm::end() ?>
```
I select jpeg file, submit and never get redirected to the "view" with validation error "Разрешена загрузка файлов только со следующими расширениями: jpg, jpeg.". What am I doing wrong?

**Comment by SilverFire** [comment]
> `$oModel->id_editor = Yii::$app->user->identity->id;`

Could be done with the BlamableBehavior


> `!! $oModel->social_photo`

No need for `!!`

Failed to reproduce. Are you sure that you are uploading jpg or jpeg files?

**Comment by SDKiller** [comment]
@jeebus3000 

Have you attempted to upload the same file each time or tried different files?

I had similar validation errors with some `.doc` and `.xls` files - there was something wrong in particular file (this mostly happened with files converted by _OpenOffice_) which made `finfo` report wrong mime type and validation failed.

**Comment by jeebus3000** [comment]
I've tried several different jpeg files, all the same result.
_В пыхву эту валидацию. Disabling of validation solves my problem._

**Comment by SilverFire** [comment]
Это не лучшее решение проблемы. Мы будем рады решить проблему, если вы поможете нам ее воспроизвести

**Comment by jeebus3000** [comment]
Вернул валидацию, ошибка больше не появляется. Были какие-то сторонние причины ¯\\_(ツ)_/¯
Спасибо!

**Comment by SilverFire** [comment]
Пожалуйста
