### ISSUE TITLE
PHP Docs not work correctly with netbeans

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#10947]
When i type `Yii::$app->request->` they are no listing of `yii\web\Request` method in autocomple popup.
![screenshot from 2016-02-24 08 01 45](https://cloud.githubusercontent.com/assets/5828252/13272377/2f35d300-dace-11e5-802b-0f901e830105.png)

This is when i am using `/* @var $request \yii\web\Request */` then type `$request->`
![screenshot from 2016-02-24 08 04 03](https://cloud.githubusercontent.com/assets/5828252/13272406/5fe92196-dace-11e5-84c1-ad4faf90c0e1.png)

I am unsure. But IMO, its can be solved with move comment docs from `yii\base\Application` to `yii\console\Application` and `yii\web\Application`.
use
```php
namespace yii\console;
/**
 * @property Request $request
 */
class Application extends \yii\base\Application
```
```php
namespace yii\web;
/**
 * @property Request $request
 */
class Application extends \yii\base\Application
```

instead of
```php
namespace yii\base;
/**
 * @property \yii\console\Request|\yii\web\Request $request
 */
class Application extends Module
```

**Comment by SilverFire** [comment]
Makes sense. Would you like to submit a PR?

**Comment by samdark** [comment]
@cebe I guess you need to check it.

**Comment by cebe** [comment]
looks like a bug in Netbeans as it does not understand that the method will return two different types of classes... We use this pattern in a lot of places. A fix would need to duplicate the methods in web and console application. Not sure if it is worth it. How fast is Netbeans in fixing reported issues?

**Comment by cebe** [comment]
The proposed PR adds `@property` tags. This is not enough as these would get removed because not corresponding getters/setters exist. I suggest to use an approach like https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md to fix this on application side and report an issue on Netbeans.

**Comment by samdark** [comment]
Since there's nothing that could be done framework-side, closing it.

**Comment by mdmunir** [comment]
@samdark 
Of course it could be done from framework-side. My PR can resolve it.

@cebe 
> The proposed PR adds @property tags. This is not enough as these would get removed because not corresponding getters/setters exist.

Why we need getter/setter must exist? Your model generator (gii) can generate `@property` tags for every columns in table without any getter/setter.
If we realy need getter/setter for `@property` tags, then we must move `getRequest()` from base application to both console application and web application.

**Comment by cebe** [comment]
> Why we need getter/setter must exist?

because `@property` tags for IDE are auto generated based on getter/setters using this command: https://github.com/yiisoft/yii2/blob/master/build/controllers/PhpDocController.php#L32-L42

> If we realy need getter/setter for @property tags, then we must move getRequest() from base application to both console application and web application.

if it would be only Request component, we could easily do that, but this issue affects more components like ErrorHanlder, Response, View, ...

**Comment by mdmunir** [comment]
>if it would be only Request component, we could easily do that, but this issue affects more components like ErrorHanlder, Response, View, ...

Then we must move all of that properties.

See **yii2 class reference site**, go to [`yii-web-application.html`](http://www.yiiframework.com/doc-2.0/yii-web-application.html) and look `$request` property. Is that documentation correct?
![screenshot from 2016-02-25 21 36 34](https://cloud.githubusercontent.com/assets/5828252/13322850/14587f10-dc09-11e5-8b3b-fa68b479bfd4.png)

Does it mean `yii\web\Application::$request` can have tipe `yii\console\Request`?
