### ISSUE TITLE
Support ArrayAccess / Arrayable in BaseHtml::checkboxList

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10941]
The selection argument for `BaseHtml::checkboxList` must either be array or string:
```php
foreach ($items as $value => $label) {
            $checked = $selection !== null &&
                (!is_array($selection) && !strcmp($value, $selection)
                    || is_array($selection) && in_array($value, $selection));
```

Since `ArrayHelper` has an `isIn` command why not use that one? That will work for anything that's `Traversable`.

**Comment by samdark** [comment]
Any examples on why it's useful?

**Comment by SamMousa** [comment]
Well for my specific use case, I have collection objects that serialize to the database.
I can't use the collection object for a checkboxlist since it is not an `array` (even though it implements `\ArrayAccess` and `\Traversable`.

**Comment by samdark** [comment]
OK. That makes sense.

**Comment by SamMousa** [comment]
#10953 
I have added an `isTraversable` to `ArrayHelper` and used that instead of `is_array` in `BaseHtml`.

**Comment by SamMousa** [comment]
Implementation was merged. Thanks!
