### ISSUE TITLE
error when joining two table

### ISSUE THREAD

**Issue by eddy20062010** [yiisoft/yii2#10952]
public function getPhotos()
    {
        return $this->hasOne(Images::className(), ['id' => 'photo']);
    }

 $model=\backend\models\Team::find()->select(["name as image","description","CONCAT(first_name,space(5),last_name,space(10),'  -  ',space(10),title) as title"])->where('id=:page',[':page'=>$page])->innerJoinWith("photos")->one();
                

Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
The SQL being executed was: SELECT `name` AS `image`, `description`, CONCAT(first_name,space(5),last_name,space(10),' - ',space(10),title) as title FROM `quickbrain_team` INNER JOIN `quickbrain_image_gallery` ON `quickbrain_team`.`photo` = `quickbrain_image_gallery`.`id` WHERE id='2'

and when i use Team::tableName()."id=:page" to solve ambiguity return empty results

**Comment by Alex-Code** [comment]
Please use the forums for questions, http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/

As for empty results do you have any data that matches the condition?
Do you have related data in the `Images` table as you're using `INNER JOIN`.
