### ISSUE TITLE
Add gitattribute for less merge conflict in changelog.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10958]
Not sure where I read this, but you could specify `merge union` for the changelog file.
Since order of individual lines is not important this will decrease merge conflicts for that file.

http://git-scm.com/docs/gitattributes

**Comment by samdark** [comment]
Order of individual lines is important.

**Comment by SamMousa** [comment]
The order of categories is important; currently there is a section per bug type.
By simply adding a small header for those, union merge will be able to always merge the changelog.
The order of individual lines within each category (bug, enh and chg) doesn't matter.

Anyway, not something I care deeply about just something I read that I thought might come in handy.

**Comment by cebe** [comment]
I think we should add it, changelog lines will be automatically ordered correctly on release anyway: https://github.com/yiisoft/yii2/blob/master/build/controllers/ReleaseController.php#L128-L151

**Comment by SamMousa** [comment]
I'm gonna unsubscribe, I assume you don't need a PR for changing .gitattributes :+1:

**Comment by cebe** [comment]
do you know the exact syntax? Then you could paste it here. I would need to look it up.

**Comment by SamMousa** [comment]
Lol, someone else read the same blog: https://github.com/olivierlacan/keep-a-changelog/issues/56
I think it's: `CHANGELOG.md merge=union`

**Comment by cebe** [comment]
added.  @SamMousa thanks for the hint!
