### ISSUE TITLE
Remove Yii autoloader

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10964]
Whether yii2 is installed via composer or via zip archive, the composer autoloader is always included.

I propose to:
1. Remove `classes.php` and instead add `classmap` configuration to `composer.json`.
2. Remove `Yii::autoload()`;
3. Remove `Yii::$classMap`;

This will not break BC for people not manually adding stuff to the classmap.
Of course for all others it will break BC so might be better to put it in 2.1.

**Comment by cebe** [comment]
composer will not autoload anything using aliases. e.g. anything in namespace `app\` will stop working.

**Comment by SamMousa** [comment]
@cebe Composers' `classmap` key will scan files just like you do, example from my `autoload_classmap.php`:
````
    'app\\components\\ActiveDataProvider' => $baseDir . '/protected/components/ActiveDataProvider.php',
    'app\\components\\ActiveField' => $baseDir . '/protected/components/ActiveField.php',
    'app\\components\\ActiveForm' => $baseDir . '/protected/components/ActiveForm.php',
    'app\\components\\ActiveQuery' => $baseDir . '/protected/components/ActiveQuery.php',
    'app\\components\\AfterSaveException' => $baseDir . '/protected/components/AfterSaveException.php',
    'app\\components\\AggregateValidator' => $baseDir . '/protected/components/AggregateValidator.php',
````

**Comment by cebe** [comment]
this means that every time you add a class, you have to rebuild composer classmap?

**Comment by SamMousa** [comment]
Yes, same is true for `classes.php` right? I don't see the difference between running `composer dumpautoload` (which is automatically done after `composer install` / `composer update`) and the script (i'm assuming) you use when preparing zip archives.

**Comment by cebe** [comment]
I am talking about development workflow when working with yii. If I create classes in phpstorm I do not want to run composer dumpautoload in order for them to work.

**Comment by SamMousa** [comment]
Of course you don't, but you don't want to add it to classes.php either do you??

**Comment by SamMousa** [comment]
Ah wait, my bad, I'm not communicating clearly.

I want to remove the `classmap` part of the autoloader, since that's 100% superfluous. (I hadn't notice Yii also has an autoloader for namespaces which support aliases).

The autoloader using aliases can be replaced by configuration in composer.json as well but that is indeed not a valid option for people not using composer.

So then my suggestion becomes a bit different:
1. Remove `classes.php` and instead add classmap configuration to composer.json.
2. Remove the classmap loader from `Yii::autoload()`;
3. Remove `Yii::$classMap`;

**Comment by hiqsol** [comment]
I did investigation to this question.

Indeed `classes.php` together with `Yii::$classMap` could be removed painlessly. Composer completely substitutes this functionality.
But `Yii::autoload` should be left in it's place because of classes based on Yii aliases: `app\`, `frontend\` and so on.

**Comment by SamMousa** [comment]
@hiqsol Thanks, i'm just thinking, couldn't we also (eventually) replace that part by passing setAlias on to   the composer classloader? (Just a thought)

**Comment by hiqsol** [comment]
> I am talking about development workflow when working with yii. If I create classes in phpstorm I do not want to run composer dumpautoload in order for them to work.

No, you don't need to. Because `classmap` functionality just makes class resolving faster.
When you create class and it is available through PSR-4 autoload it will work immediately without `composer dumpautoload`.

**Comment by klimov-paul** [comment]
Does anyone remember Yii2 can be installed without Composer?
https://github.com/yiisoft/yii2/blob/master/docs/guide/start-installation.md#installing-from-an-archive-file-
https://github.com/yiisoft/yii2/blob/master/docs/guide/start-installation.md#other-installation-options-

**Comment by SamMousa** [comment]
@klimov-paul Yes I do and I explicitly mentioned that in the issue; the zip archive also includes the vendor directory and thus the composer autoloader.

**Comment by cebe** [comment]
We could theoretically do many thing. What problem are you trying to solve here? I do not get the point?

**Comment by SamMousa** [comment]
Remove functionality from Yii that is already provided by a library that's available 100% of the time?

Essentially making the codebase smaller without removing any functionality.

**Comment by cebe** [comment]
there is no need to include composer autoload file if I want to skip it so this will remove functionality.
Also classmap can be used to load classes from libraries that do not support composer.
The provided classmap file is 23kb which is 0.4% of the framework size. You would not notice any improvement. Yii comes with a fully functional PSR-4 autoloader. I see no sense in removing any functionality from it. dropping classMap property is a BC break and not shipping the classes file does not make sense when we have the classMap property.

**Comment by hiqsol** [comment]
@SamMousa, concerning remove Yii::$classMap
it's not really good idea because of the way autoloading works.
First autloader (Yii) looks for the class then next autoloader (Composer) looks for the class. And `classmap` mechanism is here to speed up the look up process for well known classes.
Normal PSR autloading requires actual looking for files including calling `file_exits()` while classmap is a straight mapping from class to path.
So to get the most boost `classmap` looking has to be done in the very first place.

What I tried (and it works fine) is to use composer generated classmap instead of `classes.php`:

```diff
diff --git a/Yii.php b/Yii.php
index 83cd858..afff18a 100644
--- a/Yii.php
+++ b/Yii.php
@@ -26 +26 @@ spl_autoload_register(['Yii', 'autoload'], true, true);
-Yii::$classMap = require(__DIR__ . '/classes.php');
+Yii::$classMap = require(parent(__DIR__, 2) . '/composer/autoload_classmap.php');
```

It gives you small thing - you don't need to keep (generate) `classes.php` file.
Also it speeds up resolving of other (non Yii) classes in `composer/autoload_classmap.php`.

**Comment by SamMousa** [comment]
@hiqsol I know, that is exactly what my goal was ;-)
I didn't suggest removing classmap altogether, just removing it from Yii and using the one provided by composer.

**Comment by cebe** [comment]
We could add this information to the guide here: http://www.yiiframework.com/doc-2.0/guide-tutorial-performance-tuning.html#optimizing-autoloader

But should also add a note, that loading huge classmap files can also have negative impact on processing time.

**Comment by SamMousa** [comment]
It's already mentioned (`dumpautoload -o`) is essentially the same.
