### ISSUE TITLE
Conflict in config

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2#10979]
If I add in /common/config/main.php:
````php
'components' => [
    'errorHandler' => [
        'displayVars' => ['_GET', '_POST', '_FILES', '_COOKIE', '_SESSION', '_ENV', '_SERVER'],
    ],
....
````
I have a mistake on **php yii migrate:**
![screen2016-02-27-05 20 37](https://cloud.githubusercontent.com/assets/16696651/13370758/174563dc-dd12-11e5-9f5a-b8918af88b89.png)

Wthout this component - everything works good.

**Comment by fernandezekiel** [comment]
the displayVars is only a property of `yii\web\ErrorHandler`
this isn't used in the console applications, console apps use `yii\console\ErrorHandler`

set this configuration only under the web application not under the common (like frontend/backend)
