### ISSUE TITLE
Is it necessary to write a Form class extend Model?

### ISSUE THREAD

**Issue by FavorMylikes** [yiisoft/yii2#10977]
I saw source code of Yii2 default application.I found that,SignupForm extend Model,and User extend ActiveRecord,That means User extend ActiveRecord too.
Why do I have to write a From extend Mode rather than Activerecord?
Or,Can I use User class to save value come from $_POST immediately?
So I don't have to have rewrite function rules() attributeLabels() in From class.
Isn't it?

**Comment by cebe** [comment]
ActiveRecord is a database bound model, Model can be used to validate input that is not stored in db.
