### ISSUE TITLE
Include minified jQuery when not debugging?

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#10973]
Currently Yii always includes a non-minified jQuery:

https://github.com/yiisoft/yii2/blob/master/framework/web/JqueryAsset.php

Shouldn't this be changed to serve the minified jQuery when not in debugging mode?

**Comment by cebe** [comment]
related to #5942 / #3324 (cc351d0)

I do not see any issues with making it the default behavior though. Not sure if this will affect creation of minified assets.

**Comment by SamMousa** [comment]
I agree; arguing that it can be changed by overriding the whole `JQueryAsset` seems a bit overkill to me.

Shall I implement a `JqueryAsset` that has the minified as default and sets it to the source in the constructor when `YII_DEBUG = true`

**Comment by cebe** [comment]
Normally this should be done by overriding it in `init()` instead of constructor. That however may break code that set properties via AssetManager::$bundles.

**Comment by SamMousa** [comment]
That's why i'm proposing doing it in the constructor

**Comment by cebe** [comment]
makes sense.

**Comment by klimov-paul** [comment]
Duplicates #5942
