### ISSUE TITLE
Active Form Hidden Field issue

### ISSUE THREAD

**Issue by desaikalpesh34** [yiisoft/yii2#10984]
i can not assign value with array to hidden input
something like
` <? $form->field($model, 'user_id[]')->hiddenInput(['value'=>[11,12]])->label(false);?>`
its generate error like  Array to string conversion.

**Comment by Sammaye** [comment]
Hidden inputs in HTML cannot do this.

I guess you are "hiding" a select? In this case you might want to CSS hide it instead or something

**Comment by SilverFire** [comment]
<?= $form->field($model, 'user_id[]')->hiddenInput(['value'=>implode(',', [11,12])])->label(false);?>

**Comment by desaikalpesh34** [comment]
yes i want this how can i solve this

**Comment by desaikalpesh34** [comment]
i just want to load model of $model->user_id =[11,12]; to send push notification from csv file.
here value 11,12 comes from csv file uploaded by user.
