### ISSUE TITLE
No check for handling SQL error in ActiveRecord updateAll()

### ISSUE THREAD

**Issue by yetanotherse** [yiisoft/yii2#10983]
`updateAll()` returns an integer with number of rows updated. Syntax below.

`public static integer updateAll ( $attributes, $condition = '', $params = [] )`

However there is no way to check if `updateAll()` was successful. In `update()` method, there is a provision to check for SQL failure since it returns either boolean or integer depending on success or failure of query execution as shown below.

`public integer|boolean update ( $runValidation = true, $attributeNames = null )`

Or may be there is a way still to check for `updateAll()` failure but not documented?

**Comment by quantum13** [comment]
updateAll does not run validations, does not calls before save etc. It convient call to command::update with set model table name.

Btw update() does not return false with sql errors:
* @return integer|boolean the number of rows affected, or false if validation fails or [[beforeSave()]] stops the updating process.

With sql errors exceptions will be thrown in both cases

**Comment by yetanotherse** [comment]
Thanks for the clarification.
