### ISSUE TITLE
File validator fails fake file extention even if file extention is allowed

### ISSUE THREAD

**Issue by iamserjo** [yiisoft/yii2#10985]
If a user uploads  a video file that named as 123.wmv but container actually is "asf" (mime "video/x-ms-asf") - validator says you got wrong extention. Even though you allowed asf and wmv.

here is the problem in FileValidator.php that i figured out (+ my debug and comments)
```

    protected function validateExtension($file)
    {
       `$extension = mb_strtolower($file->extension, 'utf-8');

        if ($this->checkExtensionByMimeType) {

            $mimeType = FileHelper::getMimeType($file->tempName, null, false);
            if ($mimeType === null) {
                return false;
            }

            $extensionsByMimeType = FileHelper::getExtensionsByMimeType($mimeType);
            var_dump($mimeType);//"video/x-ms-asf" 
            var_dump($extensionsByMimeType);//array(2) { [0]=> string(3) "asf" [1]=> string(3) "asx" } 
            var_dump($extension);//string(3) "wmv"

            if (!in_array($extension, $extensionsByMimeType, true)) {//trying to find "wmv" in array(2) { [0]=> string(3) "asf" [1]=> string(3) "asx" } 
                return false;
            }
        }

        if (!in_array($extension, $this->extensions, true)) {
            return false;
        }

        return true;
    }


```

**Comment by iamserjo** [comment]
For this very case i fixed this problem this way:

```
            if (!in_array($extension, $extensionsByMimeType, true) && !count(array_intersect($extensionsByMimeType, $this->extensions))) {
                return false;
            }
```

**Comment by SilverFire** [comment]
I guess your're looking for this option: 
http://www.yiiframework.com/doc-2.0/yii-validators-filevalidator.html#$checkExtensionByMimeType-detail

**Comment by iamserjo** [comment]
If we set $checkExtensionByMimeType to false - this lets upload any mime type. I want the validator  to check mime. But if file name extention != real mime type - we cant pass this rule.
Just imagine that your video 1123.asf file was accidently named as 1123.wmw.  If you allowed wmv and asf extentions, this file won't pass the rule despite excpected any of them.

**Comment by iamserjo** [comment]
If we set $checkExtensionByMimeType to false - this lets upload any mime type. I want the validator to check mime. But if file name extention != real mime type - we cant pass this rule.
Just imagine that your video 1123.asf file was accidently named as 1123.wmw. If you allowed wmv and asf extentions, this file won't pass the rule despite excpected any of them.

**Comment by SilverFire** [comment]
Then allow all video with [mimeTypes](http://www.yiiframework.com/doc-2.0/yii-validators-filevalidator.html#$mimeTypes-detail) mask

**Comment by iamserjo** [comment]
I know there was that way to solve my problem. My problem looks like a wierd behavior that forced me to debug code to get how it really works.

**Comment by SilverFire** [comment]
I see :)
However, we are not going to accept this kind of logic in the core.
Create your own FileValidator and override the behavior
