### ISSUE TITLE
Validation generated by gii

### ISSUE THREAD

**Issue by vladim1** [yiisoft/yii2#10996]
When we use gii we get the following code
```php
public function actionCreate()
{
        $model = new Entity();

        $model->load(Yii::$app->request->post());
        if ($model->validate() && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
}
```
According to the documentation the ```save()``` method performs validation by default.
```php
public boolean save ( $runValidation = true, $attributeNames = null )
```
where ```runValidation```
```
Whether to perform validation (calling validate()) before saving the record. Defaults to true. If the validation fails, the record will not be saved to the database and this method will return false.
```
So, IMO the code
```php
 if ($model->validate() && $model->save())
```
should be replaced with
```php
 if ($model->save())
```
Moreover, if captcha is being used in the model, than the code
```php
$model->validate() && $model->save()
```
doesn't work at all. After ```$model->validate()``` the verification code changes and the second validation in ```$model->save()``` doesn't succeed. That's the way I came to this point.

**Comment by klimov-paul** [comment]
> When we use gii we get the following code

Use in which way exactly?
CRUD generator creates 'create' action without extra `validate()` call:
https://github.com/yiisoft/yii2-gii/blob/master/generators/crud/default/controller.php#L109
