### ISSUE TITLE
Getter function for View::$title so that Pjax requests don't change the page title.

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii2#10998]
As already mentioned yesterday [in this old issue](https://github.com/yiisoft/yii2/issues/662) I would prefer to have a View::getTitle() function which returns the Views $title attribute.

And that this function is used where the title of the View is accessed e.g. in class Pjax.

Easy example:
in my layout/main.php I have this code to add the application name to the page title:

```
<title><?= $this->title ? Html::encode(Yii::$app->name." | $this->title") : (Yii::$app->name.' | Home') ?></title>
```

And in the views something like:

```
$this->title = Yii::t('app', MyModel::label(2)); 
// or something else
$this->title = 'Some title';
```

With the code in the layout view file the application name is added to the title => Fine.

BUT on every Pjax request only the normal view title is used (so without the application name) and the page title is changed incorrectly. This is because only the `$view->title` is used.
(code from class Pjax)

```
if ($view->title !== null) {
     echo Html::tag('title', Html::encode($view->title));
}
```

Do you have another suggestion how this issue can be fixed?
I mean other then extend the `yii\web\View` and `yii\widget\Pjax` classes as overwrite/extend them with functions?

Which would be cumbersome because in the pjax class the title is directly echoed in `pjax::init` so an setting of the title before `parent::init()` call would work. I would have to copy and paste the complete init function and change one line `$view->title` to `$view->getTitle()` and have to check for changes on every yii update to also re-do the changes to my extended pjax class.

Of course I could change every view where i set the title and add the application name directly.
But in my opinion a getter (maybe also a setter) function for the title would be the easiest. 

If the View Class has a getTitle() function (and this function would be used instead of $view->title) we could just overwrite the Class via components and extend it with e.g. 

```
public function getTitle()
{
    if ($this->title === null) {
        return Yii::$app->name;
    }
   return  Yii::$app->name .' | '.$this->title;
}   
```

Then the Application Name (or something else) could be easily added to page and wouldn't change after pjax requests.

This would also help if the title comes from the db (e.g. multi language) or would be different for e.g. mobile devices.

**Comment by Faryshta** [comment]
i can't understand your example or how is it changing the title.

can you make an example with copies of your layout and pjax widget?

**Comment by SilverFire** [comment]
@Faryshta pjax is designed to find `<title>` tag inside a response and update document's title [Source](https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L751)

You have `title` in `View` and once you set it - you use it everywhere. As for me, current behavior is correct and clear therefore here is nothing to change in core. You can create your own `Pjax` class and override default `getTitle()` method. Thank you! :)

**Comment by Bhoft** [comment]
@SilverFire so you mean I should set the title in "every view" to get the application Name attached to it?

You also don't understand it correctly. 

There isn't a `getTitle()` function in the `Pjax` class.
There is also none in the `View` Class!

My request was that a getTitle function is added to the `View` Class and that this function is used in the `Pjax` class `init()` function so this [lines are changed ](https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php#L113-L115)

I only have in my /layout/main.php 

    <title><?= $this->title ? Html::encode(Yii::$app->name." | $this->title") : (Yii::$app->name.' | Home') ?></title>

and in my rendered view e.g. the following title and a grid with pjax enabled.

    $this->title = 'test title';

So on the normal render the page title is "my application | test title" and after I sort the grid via pjax the title is only "test title".

And as i have written above the title is echoed directly in the `Pjax::init` so the only solution is to completely rewrite the `Pjax::init` function and this could cause trouble if the source is changed in future versions.

**Comment by SilverFire** [comment]
> so you mean I should set the title in "every view" to get the application Name attached to it?

No, I meant that we have a `$title` property in `View` and that's the only place designed to store the page title.

> There isn't a getTitle() function in the Pjax class.
> There is also none in the View Class!

Wohoops, I thought we have one in the `Pjax` class.



> My request was that a getTitle function is added to the View Class and that this function is used in the Pjax class init() function so this lines are changed

Agree on this. Feel free to create a PR

**Comment by klimov-paul** [comment]
> Do you have another suggestion how this issue can be fixed?

You can use `View::beforeRender()` method or `beforeRender` event to setup default page title, and then override it inside particular view.

```
class MyView extends View
    public function beforeRender($viewFile, $params)
    {
        $this->title = Yii::$app->name . ' | Home'; // default title
        return parent::beforeRender($viewFile, $params);
    }
```

**Comment by klimov-paul** [comment]
Relates #662

**Comment by klimov-paul** [comment]
I can see no reason for the introduction of the getter method for the view title.
Public property has enough flexibility for the manipulation and there are enough ways to setup default title value.
Around the core code we try o minimize usage of the magic getters for the better performance. `View::title` is just a one of such examples.

**Comment by klimov-paul** [comment]
> Do you have another suggestion how this issue can be fixed?

You can also setup default `View::title` value at the application configuration level:

```php
return [
    'components' => [
        'view' => [
            'title' => 'My default page title'
        ],
    ],
];
```

**Comment by Bhoft** [comment]
@klimov-paul if I use your beforeRender method it sets the application name correctly after an pjax request. But somehow on my normal render my page title is now 

 <title>application name | application name | application name | application name | application name | test page</title>

with this code

    public function beforeRender($viewFile, $params)
    {
        if (!$this->title) 
            $this->title = Yii::$app->name . ' | Home'; // default title
        else 
            $this->title = Yii::$app->name . ' | '.$this->title; // default title
        return parent::beforeRender($viewFile, $params);
    }

I guess this is because beforeRender is called several times.
I also don't think that this is the correct position.

I also doesn't want to set a default page title. I wanted to add the application name per default to the page title. And this could be depended on the current language, output (e.g. export to pdf) different.

Therefore I wanted a simple getter / setter for the now private View::$_title which i can overwrite when i extend my view.

**Comment by SilverFire** [comment]
Wait, I meant to create `getTitle()` in `Pjax` class, not in `View`.

**Comment by Bhoft** [comment]
@SilverFire this would not really work.
If I add the "application name" to the title in the layout/main.php  (because there is no function in the View to overwrite) I also have to extend the Pjax class to do the same change here as well.

If there is a private $_title in the View class and a getTitle, setTitle function i can just extend the View Class and have

    public function getTitle()
    {

        $title = parent::getTitle();
        if ($title === null) {
            return Yii::$app->name;
        }
        return Yii::$app->name .' | '.$title;
    }

And it works everywhere and no changes to the Pjax init is needed.

**Comment by klimov-paul** [comment]
In your case it is better to introduce your own method `composeTitle()`, which will add application name to the title.
I see no reason for suport such flow in the core, since regular page title have no regular pattern (like trainling site name), which is considered a better for the SEO.

**Comment by Bhoft** [comment]
I just can't see any performance, BC issues by changing the View title to a private variable and use a function. This would only enhance the flexibility and won't destroy the BC.

Your suggestion to add my own function `composeTitle` to my extended view would also work.
But then I (and others) would have to change every view template and change the code to use the composeTitle function. 

I could also add a $_mytitle variable to my view and my functions to add the application in there (this is not the problem).
But this would also not work when I use several modules from other developers which are all using their own view templates and just use "$this->title" in their views.

If the View::$title would be private and there is a function which we can overwrite this would work just out of the box so also after Pjax requests, other modules etc.

**Comment by Bhoft** [comment]
No News about this issue?

**Comment by samdark** [comment]
Nope. @SilverFire is busy right now.

**Comment by SilverFire** [comment]
As @klimov-paul said, separate `composeTitle()` method solves the problem, however I don't mind to create additional accessors.

My personal opinion: could be done

I'd like to hear @yiisoft/core-developers opinion.

**Comment by brdsoft** [comment]
I think it is not necessary to set the title (render title tag) when enablePushState is set to false.
Pjax.php:116 `if ($view->title !== null && $this->enablePushState) {`

**Comment by samdark** [comment]
@brdsoft yes but that's totally unrelated. Please create separate issue.

**Comment by samdark** [comment]
As for this issue, I think current state of things is OK. If you need to add postfix for all titles you may use an event such as `EVENT_END_PAGE`.

**Comment by SilverFire** [comment]
Considering this issue did not get a community support and there are ways to do the same without changes in core, I'm closing this issue.

**Comment by artcer** [comment]
I use quick and simple solution to solve this problem.

```
$this->title = 'My title';
if (Yii::$app->request->isAjax) {
    $this->title .= Yii::$app->params['titleEnding'];
}
```

As Pjax is Ajax request, you can add your site name to the title when request isAjax. 
I know this is not the best solution, but it might help for some people.
