### ISSUE TITLE
suppot for ActiveQuery::EVENT_AFTER_FIND

### ISSUE THREAD

**Issue by quorzz** [yiisoft/yii2#10991]
if we query with  `asArray` to return an array instead of AR object,  the ActiveRecord::EVENT_AFTER_FIND no longer trigger . 

should we add an event ActiveQuery::EVENT_AFTER_FIND ? 

As a preliminary idea, it can be trigger at  https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L222

 such as:

```
        if (!$this->asArray) {
            foreach ($models as $model) {
                $model->afterFind();
            }
        } else {
            // trigger ActiveQuery::EVENT_AFTER_FIND  here
            foreach ($models as $key => $model) {
                $models[$key] => $this->afterFind($model);
            }
        }

```

**Comment by klimov-paul** [comment]
Duplicates #10427
