### ISSUE TITLE
Proposal add `GridView::layoutSections`

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#10995]
`yii\grid\GridView` provides property `layout`, which allows manipulation of the several sections `{summary}`, `{items}` and `{pager}`. 
While adding complex extra HTML to the layout (such as buttons or even another widgets), usage of the `layout` is not convinient.
It whould be nice to have another property like `layoutSections`, which can be populated by HTML contents, which then will be passed to corresponding layout placeholder:

```php
GridView::widget([
    'layout' => "<div>{summary}\n{exportButton}</div><div>{items}\n{pager}</div>",
    'layoutSections' => [
            '{exportButton}' => Html::a('Export', ['export'])
    ],
]);
```

**Comment by klimov-paul** [comment]
Such mechanism can be also used to **replace** default grid sections, like 'summary' or 'pager', without extending of the `GridView` class.

**Comment by cebe** [comment]
how about this?

```php
<?php
$exportButton = Html::a('Export', ['export']);
echo GridView::widget([
    'layout' => "<div>{summary}\n{$exportButton}</div><div>{items}\n{pager}</div>",
]);
```

**Comment by klimov-paul** [comment]
Make sense. Feature does not worth overcomplecating the `GridView` class.
