### ISSUE TITLE
Improving yii's captcha strength

### ISSUE THREAD

**Issue by xwz** [yiisoft/yii2#1100]
# CAPTCHA Strengths and Weaknesses

Based on the paper "Text-based CAPTCHA Strengths and Weaknesses" http://ly.tl/p22 yii's internal captcha generator is weak.
## Measuring attack effectiveness.

**Coverage** is the fraction of captchas that the solver attempts to answer. **Precision** is the fraction of captchas answered correctly. _A captcha scheme is broken when the attacker is able to reach a precision of at least 1% (1 in 100 attempts)._
## Design principles

The following principles apply to the design of the captcha core features:
1. **Randomize the captcha length**: Don’t use a ﬁxed length, it gives too much information to the attacker.
2. **Randomize the character size**: Make sure the attacker can’t make educated guesses by using several font sizes / several fonts. 
   Using several fonts reduces the classiﬁer accuracy and the scheme’s learnability.
3. **Wave the captcha**: Waving the captcha increases the difﬁculty of finding cut points in case of collapsing and helps mitigate the risk of the attacker ﬁnding the added line based on its slope when using lines.
## Anti-recognition
1. Use anti-recognition techniques as a means of strengthening captcha security.
2. Don’t use a complex charset.
## Anti-Segmentation
1. Use collapsing or lines.
2. Be careful while implementing.
3. Create alternative schemes.

**Comment by dynasource** [comment]
to what extent is the current captcha safe enough? If this is too low, we should give this higher priority, otherwise this is a nice to have and not an issue.

**Comment by samdark** [comment]
It's not really defending you if someone is using OCR.

**Comment by dynasource** [comment]
is OCR dependant on images over HTTP?

**Comment by samdark** [comment]
OCR can work with any image. There aren't many images which are hard for OCR and easy for humans nowadays so most CAPTCHAs aren't totally safe.

**Comment by dynasource** [comment]
In the past Ive made a captcha based on CSS. There are a lot over variations thinkable, using different techniques to create numbers based on random HTML, JS & CSS combinations. But you could argue that this is already getting out of the yii scope. Should be abandon support for this?

**Comment by samdark** [comment]
The interface for CAPTCHA Yii has is a very nice one. It allows to customize generation and calculations. Defaults aren't too strong and that could be adjusted based on what @xwz proposed.

**Comment by cronfy** [comment]
On last week I tried to protect a form with yii2's builtin captcha. Results were sad: there were absolutely no difference whether captcha was enabled or not. Logging showed that bots were correctly solving it without a single mistake.

Then I installed himiklab/yii2-recaptcha-widget, and it solved the problem.

Keeping in mind these two points:

 * This functionality can be easily provided by extensions.
 * It is hard (imho) to develop and support strong captcha, especially if it is opensourced.

I am just curious: why captcha is required to be in core at all?

**Comment by cebe** [comment]
> I am just curious: why captcha is required to be in core at all?

it is not required, we can move it to an extension in 2.1.

**Comment by dynasource** [comment]
agree, this is complex enough to move away from core.

About these bots, chances are that they are actually real people in Asia ;) solving captcha all day.

**Comment by samdark** [comment]
Agree about captcha. Worth moving out of the core.

**Comment by samdark** [comment]
https://www.reddit.com/r/PHP/comments/6fl2uo/yii_2012_is_released/dikr7hd/
