### ISSUE TITLE
RBAC store into DB wrong type

### ISSUE THREAD

**Issue by tuannda** [yiisoft/yii2#11009]
I config components in config.php with
```
'authManager' => [
	'class' => 'yii\rbac\DbManager',
	'defaultRoles' => ['member'],
],
```

But when 

$auth = Yii::$app->authManager;
$adminRole = $auth->createPermission('admin');
$adminRole->description = "Admin Role";
$auth->add($adminRole);

I seen in DB type = 2. It's wrong..

**Comment by mdmunir** [comment]
whats wrong?
permission type are 2.
https://github.com/yiisoft/yii2/blob/master/framework/rbac/Item.php#L19

**Comment by tuannda** [comment]
@SilverFire but I use follow:

```
$auth = Yii::$app->authManager;

$adminRole = $auth->getRole('admin');

```
It return empty record because I use getRole function query with Type = 1 not yet Type = 2.
