### ISSUE TITLE
TimestampBehavior and BlameableBehavior cause non-dirty records updated

### ISSUE THREAD

**Issue by lacek** [yiisoft/yii2#11002]
`ActiveRecord::update` is supposed to save only changed attributes.
Suppose we have an ActiveRecord with `TimestampBehavior` attached and there's no dirty attributes.
When `save` or `update` method is called on this record, `beforeSave` method is called and triggers the behavior to update the `updated_at` attribute. Thus update is always performed.

Similarly, `BlameableBehavior` updates `updated_by` attribute if `update` is called on a clean record by a user with ID different from original `updated_by` attribute.

**Comment by lacek** [comment]
A fix that works for me is to override the `evaludateAttributes` method and skips calling parent one when it is beforeUpdate event with no dirty attributes:

```php
    public function evaluateAttributes($event)
    {
        if ($event->name === BaseActiveRecord::EVENT_BEFORE_UPDATE &&
                empty($this->owner->getDirtyAttributes())) {
            return;
        }
        parent::evaluateAttributes($event);
    }
```

**Comment by samdark** [comment]
It changes current behavior a bit but seems to be a good change. @yiisoft/core-developers opinions?

**Comment by mdmunir** [comment]
:+1:

**Comment by SilverFire** [comment]
:+1:

**Comment by tonydspaniard** [comment]
That was actually to be my new suggestion

**Comment by Faryshta** [comment]
I am working on a patch. is the property name `skipUpdateOnCleanAttributes` too long? any other suggestion?
