### ISSUE TITLE
ImageValidator validate by gd types

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#11007]
Add ability to validate by IMG_GIF, IMG_JPG, IMG_PNG constants instead of mimeTypes :)

**Comment by samdark** [comment]
How do I get these constraints from the file uploaded?

**Comment by DrDeath72** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/validators/ImageValidator.php#L133

**Comment by samdark** [comment]
What's wrong with mime?

**Comment by DrDeath72** [comment]
> If the fileinfo extension is not installed, it will fall back to getMimeTypeByExtension()

**Comment by DrDeath72** [comment]
Я часто гружу файлы просто вставляя адрес в диалоге выбора файла, он его тянет в темп и оттуда как локальный грузит. Бывает что файлы без расширения, отдаются скриптом и прочее. И если он будет проверять по расширению, то оно не загрузится. у меня так и бывает, потому что проверка стоит по расширению. А если совпадет что и fileinfo не стоит то вообще не загрузишь определенный тип :)

**Comment by samdark** [comment]
What if we don't have GD and are using, for example, imagemagick instead?

**Comment by DrDeath72** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/captcha/Captcha.php#L179

**Comment by samdark** [comment]
Won't be implemented in 2.0.
