### ISSUE TITLE
Weird behavior with currency formatter

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#11004]
There are some issues when formattind some currency ISOs.
USD works fine:
`Yii::$app->formatter->asCurrency(3.40, 'USD');` => $3.40
`Yii::$app->formatter->asCurrency(3.40, 'usd');` => $3.40

CAD works fine:
`Yii::$app->formatter->asCurrency(3.40, 'CAD');`  => CA$3.40
`Yii::$app->formatter->asCurrency(3.40, 'cad');`  => CA$3.40

MUR not showing decimals when ISO is upper case:
`Yii::$app->formatter->asCurrency(3.40, 'MUR');`  => MUR3
`Yii::$app->formatter->asCurrency(3.40, 'mur');` => MUR3.40

Also, is it possible to change the symbol for each currency? For example if i want to display `Rs` instead of `MUR` i tried adding `\NumberFormatter::CURRENCY_SYMBOL => 'rs'` without any luck.

**Comment by cebe** [comment]
can you please run the following script and paste the output here?

```php
<?php
echo "PHP: " . PHP_VERSION . "\n";
echo "ICU: " . INTL_ICU_VERSION . "\n";
echo "ICU Data: " . INTL_ICU_DATA_VERSION . "\n";
```

**Comment by Locustv2** [comment]
PHP: 7.0.2 
ICU: 56.1 
ICU Data: 56.1

**Comment by cebe** [comment]
seems ICU data somehow defines formatting pattern for `MUR` currency to have zero decimals...

I have played around a bit and noticed that the symbol and formatting changes dependend on locale.
So if you set locale to `fr-MU` you get the `Rs` symbol.

> Also, is it possible to change the symbol for each currency? For example if i want to display Rs instead of MUR i tried adding \NumberFormatter::CURRENCY_SYMBOL => 'rs' without any luck.

If you want to force a symbol you have to leave the currency blank, e.g.:

```php
        $formatter->locale = 'fr-MU';
        $formatter->currencyCode = null;
        $formatter->numberFormatterSymbols = [NumberFormatter::CURRENCY_SYMBOL => 'rs'];
        echo $this->formatter->asCurrency(3.40); // 3 rs
```

This is a limitation of intl extension, we can not change that.

**Comment by Locustv2** [comment]
Ohh i see.

Well it's weird that it works differently with different cases, but it this is on the intl extension, i guess this is not an issue that can be solved.

However i've been playing around it for a while trying different locales.

```php
        Yii::$app->charset = 'utf-8';
        var_dump(Yii::$app->formatter->asText('र')); // display the symbol well
        $formatter = Yii::$app->formatter;
        $formatter->locale = 'en_IN';
        var_dump($formatter->asCurrency(3.40)); // displays ₹ instead of र
```

It's supposed to be the same symbol but it's not being displayed.

Thanks.

**Comment by cebe** [comment]
this data all comes from the PHP intl extension which uses CLDR data. If you find wrong formatting or wrong symbols being displayed, please report this to http://cldr.unicode.org/, thanks!
