### ISSUE TITLE
Rbac- Assign multiple permissions to a role on a single line.

### ISSUE THREAD

**Issue by alejosv** [yiisoft/yii2#11017]
Every time I implemented a 'Rbac' from scratch, I have to do something like this:

```
<?php
namespace app\commands;

use Yii;
use yii\console\Controller;

class RbacController extends Controller
{
    public function actionInit()
    {
        $auth = Yii::$app->authManager;
        ...
        $viewStudents = $auth->createPermission('viewStudents');
        $viewStudents->description = 'Students view';
        $auth->add($viewStudents);

        $createStudent = $auth->createPermission('createStudent');
        $createStudent->description = 'Create a student';
        $auth->add($createStudent);
        ...
```

When I'm creating roles, then I assigned permissions this way:

```
       ...
       $management = $auth->createRole('management');
       $management->description = 'Management Staff';
       $auth->add($management);
       $auth->addChild($management, $createStudent);
       $auth->addChild($management, $viewStudents);
       ... 
```

Check the `addChild()` method that belongs to the `yii\rbac\DBManager` class, to see if, instead of assigning a permit at once, I could do it in "line one", or example something like:

```
       ...
       $auth->addChild($management, [$createStudent, $viewStudents]);     
       ...
```

So, I made an implementation to avoid repeating code for the same task. This the method can receives an array rather than a string:

```
<?php
namespace yii\rbac;

use Yii;
use yii\caching\Cache;
use yii\db\Connection;
use yii\db\Query;
use yii\db\Expression;
use yii\base\InvalidCallException;
use yii\base\InvalidParamException;
use yii\di\Instance;

class DbManager extends BaseManager
{
    ...
    /**
     * @inheritdoc
     */
    public function addChild($parent, $childs)
    {
        foreach ($childs as $child) {
            if ($parent->name === $child->name) {
                throw new InvalidParamException("Cannot add '{$parent->name}' as a child of itself.");
            }

            if ($parent instanceof Permission && $child instanceof Role) {
                throw new InvalidParamException('Cannot add a role as a child of a permission.');
            }

            if ($this->detectLoop($parent, $child)) {
                throw new InvalidCallException("Cannot add '{$child->name}' as a child of '{$parent->name}'. A loop has been detected.");
            }

            $this->db->createCommand()
                ->insert($this->itemChildTable, ['parent' => $parent->name, 'child' => $child->name])
                ->execute();

            $this->invalidateCache();   
        }

        return true;
    }
```

I suppose at phpManager will be same. Is valid this change in any way?

**Comment by SilverFire** [comment]
It is an API sugar, that could be implemented, but in a little different way:

```php
public function addChildren($parent, $children) 
{
    foreach ($children as $child) {
        $this->addChild($parent, $child);
    }

    return true;
}

**Comment by samdark** [comment]
I'm neutral about it. Not very useful to me personally.

**Comment by dynasource** [comment]
this will cause several issues:
* BC break
* the implementation is too detailed, at cost of flexibility
* addChild is not exactly what you are doing (you are adding multiple children)
* this architecture should be more developed around $composition instead of DbManager

So regarding this suggestion, it has too many side effects to accept. 
Thanks for sharing your opinion & solution.

**Comment by alejosv** [comment]
Usually (not always) interfaces are built with more than one level of permission or access (CRUD, CRUDL, MADS, BREAD). To implement an RBAC I have to send multiple permissions by role. The current implementation of RBAC force me to send one by one each permission, calling the `addChild` function multiple times for the same role. At this point, I see much more inflexible, force the developer to send permissions separately, the RBAC allows a single call sending 1...N permissions, and this save me several lines of code for each role.

Finally, do not understand, what is really inconvenient to do in one line of code what actually needs to be done in two or more lines, and that this would be considered a "minor change" to facilitate its implementation, I can't see "several issue" in this, possibly, this is a very personal vision.
