### ISSUE TITLE
after clear directory Runtime, FileCache Error in first load

### ISSUE THREAD

**Issue by herisetiyawan** [yiisoft/yii2#11010]
Hallo,

I just try using FileCache, but after i clean foledr runtime and load page, i alway got error in first load

![2016-03-03_154356](https://cloud.githubusercontent.com/assets/4680533/13489039/39a36a0c-e157-11e5-920f-75df5d4bdcca.png)

mycode:
`    public function actionTestcache() {
        $key = 'user';
        $cache = new FileCache();
        $model = $cache->get($key);
        if ($model === false) {
            echo 'Create New<br>';
            $model = \application\models\AdminUser::findOne(1);
            $cache->set($key, $model);
            return $model;
        }
        echo $model->fullname;
    }`

thank you

**Comment by mdmunir** [comment]
https://guides.github.com/features/mastering-markdown/

Are you sure its good pleace for asking?

> PS: Always using `return ... ;` for action instead of `echo ...:`
