### ISSUE TITLE
yii\web\UploadedFile getBaseName return null in 'phpStudy' tookit

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2#11012]
in [phpStudy](http://www.phpstudy.net) toolkit, use 'Apache + PHP5.5', if upload file is chinese, will return null.

**Comment by samdark** [comment]
name is obtained directly from `$_FILES`. Can you check if it's null in there or not?

**Comment by samdark** [comment]
- https://www.drupal.org/node/1292436
- https://stackoverflow.com/questions/4451664/make-php-pathinfo-return-the-correct-filename-if-the-filename-is-utf-8

**Comment by hiscaler** [comment]
I test now, in my win7 OS is ok, but in win2008 server in my client is return null.
Who use win2008, please test it, thank you.

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/a0f9bf289353c4fc4aebc46fe263c20ec39d5976

**Comment by h0mjam** [comment]
Method returned file name w\o extension (PATHINFO_FILENAME), hoverer must return with extension (PATHINFO_BASENAME)
