### ISSUE TITLE
Pjax id cannot contain dot in name

### ISSUE THREAD

**Issue by koxu1996** [yiisoft/yii2#11016]
Simple code like following result in not working pjax (normal request instead of ajax):
**Controller:**
```
public function actionTest()
{
   return $this->render('test', ['time' => date('H:i:s')]);
}
```
**View:**
```
use yii\helpers\Html;
use yii\widgets\Pjax;
Pjax::begin(['id'=>'test.id']);
   echo Html::a("Refresh", ['site/index'], ['class' => 'btn btn-lg btn-primary']);
   echo $time;
Pjax::end();
```
In the docs there is no mention about allowed characters in name, so I suggest to add this information.

PHP version: 5.5.9-1ubuntu4.14 
Yii2 version: 2.0.6
OS: Ubuntu 14.04
Browser: Chrome 49.0.2623.75 (64-bit)

**Comment by Alex-Code** [comment]
This isn't specific to `Pjax` as such, It's to do with selectors.

I'd recommend against using a dot in an `id` attribute because you'll need to escape it when using `jQuery`.
e.g. `$('#test\\.id')` which doesn't happen automatically.

**Comment by alejosv** [comment]
If you need support a dot in the html selector can you check before to assign the id 

```
        $id = 'test.id';
        $dot = '.';

        if(strstr($id, $search)) {
                $index = strpos($id, $dot);
                if($index != false) {
                       $id = substr_replace($id, chr(92).chr(92).$dot, $index, strlen($dot));
                }
        }
```
This converts ```test.id``` in ```test\\.id``` , this for javascript work it. In your case, I would be inclined to implement this directly: ```yii2/framework/widgets/Pjax.php```, with that quiet work with the points id selectors. Yii should consider these cases.

**Comment by SilverFire** [comment]
As @Alex-Code said, it's not a good idea to use `.` char in HTML element ID. 

I don't think that we must implement selectors' encoding and overcomplicate code.
I'm closing the issue, but feel free to post your thoughts @yiisoft/core-developers
