### ISSUE TITLE
Cannot modify or remove cookies when authenticated.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#11011]
When i start a new session, unauthenticated, i can add, modify and remove cookies but when i login, it stops working.

Here is a script i made to test:

```php
public function actionTest()
    {
        $request = Yii::$app->getRequest()->getCookies(); 
        $response = Yii::$app->getResponse()->getCookies();
        var_dump($request->toArray(), $response->toArray());

        if($request->has('pref')) {
            $cookie = $request->get('pref');
            $cookie->value = ['time' => time()];
            //var_dump('modifying');
            //$response->add($cookie);
            var_dump('removing');
            $response->remove($cookie);
        }
        else {
            $cookie = new \yii\web\Cookie([
                'name' => 'pref',
                'value' => ['time' => time()],
                'expire' => time() + (86400 * 360),
            ]);
            $response->add($cookie);
            var_dump('added');
        }
        return;
```

When not logged in:
`$request->toArray()` contains `_csrf` and `pref` and it is modified/deleted when i refresh the page.
`$response->toArray()` is empty

When logged in:
`$request->toArray()` contains `_csrf` and `pref` and `_identity` nothing happens when i refresh the page
`$response->toArray()` contains only `_identity`

**Comment by samdark** [comment]
Can't reproduce on basic application template. It behaves the same way either when authenticated or not.
