### ISSUE TITLE
The file or directory to be published does not exist:\vendor\bower/jquery/dist' 

### ISSUE THREAD

**Issue by rahulron** [yiisoft/yii2#11021]
i m getting this error  when i run composer update 
Exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: C:\wamp\www\tallyportal\vendor\bower/jquery/dist'

**Comment by SilverFire** [comment]
This problem is related to your issue #11020 and was [discussed many times](https://github.com/yiisoft/yii2/issues?q=is%3Aissue+%27The+file+or+directory+to+be+published+does+not+exist+is%3Aclosed). 

Fix your fxp plugin and all will be ok
