### ISSUE TITLE
composer update is not working

### ISSUE THREAD

**Issue by rahulron** [yiisoft/yii2#11020]
whenever i m downloading yii 2 using composer it is giving below error.
even i cant run composer.update.

The "fxp/composer-asset-plugin" plugin requires composer-plugin-api 1.0.0, this
*WILL* break in the future and it should be fixed ASAP (require ^1.0 for example
).

Fatal error: Call to undefined method Fxp\Composer\AssetPlugin\Package\Version\V
ersionParser::parseLinks() in C:\Users\test\AppData\Roaming\Composer\vendor\fxp
\composer-asset-plugin\Repository\VcsPackageFilter.php on line 272

**Comment by quantum13** [comment]
update composer and composer-asset-plugin:
`composer self-update`
`composer global require "fxp/composer-asset-plugin:~1.1.2"`

**Comment by rahulron** [comment]
Sorry but still same error is coming.after run 1.1.2

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/10554, https://github.com/yiisoft/yii2/issues/9794,
