### ISSUE TITLE
No plural in the relation name

### ISSUE THREAD

**Issue by arjenmeijer** [yiisoft/yii2#11022]
Sometimes, and I do not know why, Gii generates a relation without plural (s). For example
```
    public function getGebeurtenistype()
    {
        return $this->hasOne(\app\models\Gebeurtenistype::className(), ['gebeurtenistype_id' => 'gebeurtenistype_id']);
    }
```
This gives errors in forms.

The bug? was first seen in the IO generator of  mootensai/yii2-enhanced-gii.
However, he writes: 

> I've tried using yii2 default gii module, and it gives me the same error when using your database. Maybe you should create an issue on yii2 github.

**Comment by klimov-paul** [comment]
This is expected: 'has-one' relation is genereted in singular, only 'has-many' - in plurar.
