### ISSUE TITLE
BaseStringHelper::truncateHtml not work correctly with UTF-8

### ISSUE THREAD

**Issue by tol17** [yiisoft/yii2#11026]
Problem in line:
168: `$currentCount = str_word_count($token->data);`
This function return not correctly word count, if string in MB code (in my case - russian).

There are many reliases for function str_word_count_utf8($str).
I suggest to choose the best.

**Comment by hiscaler** [comment]
From [stackoverflow](http://stackoverflow.com/questions/13884178/str-word-count-function-doesnt-display-arabic-language-properly)
```php
function mb_str_word_count($string, $format = 0, $charlist = '[]')
    {
        $ret = null;
        $string = trim($string);
        $words = empty($string) ? [] : preg_split('~[^\p{L}\p{N}\']+~u', $string);

        switch ($format) {
            case 0:
                $ret = count($words);
                break;
            case 1:
            case 2:
                $ret = $words;
                break;
            default:
                $ret = $words;
        }

        return $ret;
    }
```

**Comment by tol17** [comment]
I have seen such a pre-processing line:
`$string = str_replace("\xC2\xAD",'', $string);        // soft hyphen encoded in UTF-8`
[https://en.wikipedia.org/wiki/Soft_hyphen]

**Comment by samdark** [comment]
@tol17 what's the text you're truncating? How you're calling the code? What's expected? What have you received?

**Comment by samdark** [comment]
Added unicode aware word counter btw: https://github.com/yiisoft/yii2/commit/c17f887583fae751ea080c55265146e2a1178b70

**Comment by tol17** [comment]
Sorry, I read stackoverflow about UTF spaces without check.
I am test your function with Unicode Characters:
'NO-BREAK SPACE' (U+00A0): 2 Bytes in UTF-8: 0xC2 0xA0 (c2a0)
'NEXT LINE (NEL)' (U+0085): 2 Bytes in UTF-8: 0xC2 0x85 (c285)
'LINE SEPARATOR' (U+2028): 3 Bytes in UTF-8: 0xE2 0x80 0xA8 (e280a8)
'PARAGRAPH SEPARATOR' (U+2029): 3 Bytes in UTF-8: 0xE2 0x80 0xA8 (e280a8)
Thats Ok.
Test:
`$this->assertEquals(5, StringHelper::countWords('1word 2word3word 4word 5word'));`

**Comment by samdark** [comment]
You said you have input string in Russian...

**Comment by samdark** [comment]
Seems the string above is corrupted.

**Comment by tol17** [comment]
In testWordCount() has Russian strings, test is ok. I feared about UTF spaces but it looks good.
String '1word 2word�3word 4word 5word' copies from webpage to Notepad++ correctly with all spaces.

**Comment by samdark** [comment]
OK so back to my question... Could you please answer it? https://github.com/yiisoft/yii2/issues/11026#issuecomment-197057030

**Comment by tol17** [comment]
[BaseStringHelper_truncateHtml_in_out.txt](https://github.com/yiisoft/yii2/files/175882/BaseStringHelper_truncateHtml_in_out.txt)
Truncating text and out in file. Call:
`<?php echo \yii\helpers\StringHelper::truncateWords($model->body, 30, '...', true) ?>`
I expected 30 words with correct html marking, looks like truncate english string.
Out: words count more then 30, hasn't  suffix.

**Comment by samdark** [comment]
Werid. I cannot reproduce it with the text you've provided.

**Comment by tol17** [comment]
```
public function actionTest()
    {
        $rus = '<p> раз два три четыре пять </p> <p> шесть семь восемь девять десять</p>';
        $eng = '<p> one two three four five </p> <p> six seven eight nine ten</p>';
        
        echo \yii\helpers\StringHelper::truncateWords($rus, 6, '...', true);
        echo '</br>';
        echo \yii\helpers\StringHelper::truncateWords($eng, 6, '...', true);
    }
```

Out:
 раз два три четыре пять

шесть семь восемь девять десять

one two three four five

six
...

English string truncated normally. If $count = 3 russian string truncated very queerly:
раз два три

шесть семь восемь

one two three
...

**Comment by samdark** [comment]
@tol17 fixed it. Check if it's now OK in you case.
