### ISSUE TITLE
Redirect and ajax

### ISSUE THREAD

**Issue by nepster-web** [yiisoft/yii2#11032]
Сразу извиняюсь, за то что напишу вопрос только для русскоязычной аудитории, так-как на англ объяснить не смогу. 

**Есть простая задача:**
Наполнить форму данными, отправить на сервер, если все хорошо, то должен сработать редирект на другую страницу и показать flash сообщение. 

Все работало хорошо, до того момента, как я решил включить ajax валидацию:

```
        Yii::$container->set('yii\widgets\ActiveForm', [
            'fieldClass' => 'app\components\backend\ActiveField',
            'enableClientValidation'=> false,
            'enableAjaxValidation' => true,
            'validateOnChange'=> false,
            'validateOnBlur'=> false,
        ]);
```

После этого кода все по прежденему работает за исключением того, что flash сообщения не показываются. Было очень странно такое наблюдать, я долго не мог понять в чем проблема, пока не полез в js. 

Давайте обратим внимание на следующий код в файле yii.js:

```
function initRedirectHandler() {
        // handle AJAX redirection
        $(document).ajaxComplete(function (event, xhr, settings) {
            var url = xhr.getResponseHeader('X-Redirect');
            if (url) {
                window.location = url;
            }
        });
    }
```

Если не считать проблему, что это не работает в некоторых IE, то на первый взгляд ничего подозрительного нет. Для примера, я чуть изменил данный код:

```
function initRedirectHandler() {
        // handle AJAX redirection
        console.log ('ajaxComplete INIT');
        $(document).ajaxComplete(function (event, xhr, settings) {
        console.log ('ajaxComplete');
            var url = xhr.getResponseHeader('X-Redirect');
            if (url) {
                window.location = url;
            }
        });
    }
```

![11](https://cloud.githubusercontent.com/assets/5681979/13548776/e09a3ba6-e300-11e5-8b1e-267b456e7303.png)

Опять никаких подозрений все хорошо. Но если использовать ajax валидацию будет примерно такое:

![22](https://cloud.githubusercontent.com/assets/5681979/13548780/f147fd94-e300-11e5-9784-c034eb049cd9.png)

Если присмотреться, мы увидим, что событие ajaxComplete выполняется 2 раза, хотя запрос был послан только один. Я отключил все сторонние скрипты, чтобы убедиться, что проблема не в них. 

Исходя из этого редирект каким-то образом выполняется 2 раза, в ходе чего затираются flash сообщения. 

Я чуть-чуть поэкспериментировал и написал что-то такое:

```
    function initRedirectHandler() {
        // handle AJAX redirection
        var redirect = [];
        $(document).ajaxComplete(function (event, xhr, settings) {
            var url = xhr.getResponseHeader('X-Redirect');
            if (url && redirect.indexOf(url) < 0) {
                redirect.push(url);
                window.location = url;
            }
        });
    }
```

В ходе теста все проблемы решились. Тоесть редирект срабатывает только один раз и все flash сообщения на месте. 

Однако в любом случае ситуация очень интересная, я не знаю что вызывает двойной вызов события, но я видел похожие тикеты на гитхабе, который были закрыты по причине того, что это не могули воссоздать. 

Возможно это даже не проблема самого Yii2, а скорее jQuery, но хотелось бы получить иммунитет и возможно более опытные разработчики выиснят в чем причина такого поведения.

**Comment by SilverFire** [comment]
С русским языком все ок, только среди core-разработчиков трое говорят по-русски.

Да, событие действительно порождается дважды. Первый раз на уровне событий документа в [yii.js:326](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L326), а потом в [yii.activeForm.js:348](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L348) в результате success ajax запроса.

Не смотря на то, что это кажется излишним, проблем с редиректом быть по идее не должно, ведь оба раза придет один и тот же объект XHR.

Судя по истории коммитов, тут нет никакого скрытого смысла, и, возможно, повторный принудительный вызов события можно удалить. Но у меня есть сомнения, что все действительно так просто

**Comment by nepster-web** [comment]
У меня предположение, что редирект выполняется 2 раза. Тоесть 

```
 window.location = url;
```

Успевается послать два запроса на редирект и браузер это честно отрабатывает. При первом редиректе теряются флеш сообщения, при втором мы уже попадаем на страницу, где флеш сообщения удалены.

В моем экспериментальном коде:
```
 function initRedirectHandler() {
        // handle AJAX redirection
        var redirect = [];
        $(document).ajaxComplete(function (event, xhr, settings) {
            var url = xhr.getResponseHeader('X-Redirect');
            if (url && redirect.indexOf(url) < 0) {
                redirect.push(url);
                window.location = url;
            }
        });
    }
```

Я попробовал воспользоваться неким флагом, чтобы проверить решиться ли проблема если мы сможем отсечь повторный запрос. И после этого все работает как нужно. 

Конечно можно сделать пулл-реквест с таким небольшим хаком, но хотелось бы понять подробнее в чем дело.

**Comment by nepster-web** [comment]
Что там, на выходных все отдыхают ? =) Счастливчики.

**Comment by SDKiller** [comment]
@nepster-web 

IMO, this https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L349 is
 excessive and is source of most of **_events-double-handling_** issues.

I don't know why [kartik-v](https://github.com/kartik-v) invoked triggering event manually as this is global event which is triggered anyway.

**Comment by nepster-web** [comment]
@SDKiller 
Честно говоря не совсем понял причем тут  kartik-v ?

**Comment by SilverFire** [comment]
Да, проблема из-за двойной обработки события возникает. Удалить этот вызов полностью мы не можем, так как это будет хорошим сломом обратной совместимости.
Могу предложить вот такой вариант изменения, при котором слом есть, но его можно восстановить конфигурационно. Так как JS не покрыт тестами, трогать его нужно оочень аккуратно. @yiisoft/core-developers 

```diff
diff --git a/framework/assets/yii.activeForm.js b/framework/assets/yii.activeForm.js
index fa27d34..76551c3 100644
--- a/framework/assets/yii.activeForm.js
+++ b/framework/assets/yii.activeForm.js
@@ -99,8 +99,10 @@
          *  - event: an Event object.
          *  - jqXHR: a jqXHR object
          *  - textStatus: the status of the request ("success", "notmodified", "error", "timeout", "abort", or "parsererror").
+         *
+         * Defaults to `undefind`, means no event will be triggered.
          */
-        ajaxComplete: 'ajaxComplete'
+        ajaxComplete: undefined
     };
 
     // NOTE: If you change any of these defaults, make sure you update yii\widgets\ActiveForm::getClientOptions() as well
@@ -346,7 +348,9 @@
                         data: $form.serialize() + extData,
                         dataType: data.settings.ajaxDataType,
                         complete: function (jqXHR, textStatus) {
-                            $form.trigger(events.ajaxComplete, [jqXHR, textStatus]);
+                            if (events.ajaxComplete !== undefined) {
+                                $form.trigger(events.ajaxComplete, [jqXHR, textStatus]);
+                            }
                         },
                         beforeSend: function (jqXHR, settings) {
                             $form.trigger(events.ajaxBeforeSend, [jqXHR, settings]);
```

**Comment by nepster-web** [comment]
@SilverFire а как на счет моего варианта, где просто идет проверка на с помощью флага в yii.js ? Вроде это проще и ничего не ломает.

**Comment by SilverFire** [comment]
Если приложение использует PJAX, будет невозможно сделать редирект на один и тот же URL дважды

**Comment by planet17** [comment]
Где-то на английском видел более-менее громоздкое объяснения почему это не меняют, но что там было не помню.

> P.S.: Каюсь! Пишу JS, только в JS-файлах, и в случаях с ajax - всегда использовал исключительно свой JS для обработки ошибок/скролла/подсветок/прочих ui-фичей.

> P.S.S.: Люблю велосипеды без излишних цепей и рулей.

Лично у меня была ситуация когда я просто вешал кастомную функцию с ajax для некоторой модификации данных и получал при завершении своей два вызова родной.

Слегка иная ситуация. Но станет критичным двойной вызов, данный хак может кому-то помочь. Можно заменить на свою собственную функцию с ajax, и обрывать работу скрипта до родных двойных вызовов.

Для себя выбрал такой способ:
`[ВашаФорма].on('beforeSubmit',function(){[ВашаПользовательскаяФункция];return false;});`

Вытекающие из такого подхода:
- Для любителей стандартных валидаций от html5 на стороне клиента - они таки работают в этом случае.
- В своей пользовательской функции необходимо самому писать ajax, и быть уверенным что все сделано правильно.
- Не знаю как поведет себя конкретно валидация ajax написанная на сервере, проверкой не занимался.

**Comment by nepster-web** [comment]
Ну в таком случае можно просто копировать yii.js, вносить свои изменения и подменять реализацию в конфиге в asset. Вот честно в последнее время наступаю на грабли готовых релазиаций от yii. Кстате вроде больше не 1 фраэмворк не предалает из коробки подобных штук. 

Наверно самый удачный вариант будет действительно подменить yii.js на свою реализацию или я не прав ?

**Comment by SilverFire** [comment]
@nepster-web конечно можете подменить своим, но было бы хороши исправить это в core.

@samdark @klimov-paul взгляните на это [сообщение](https://github.com/yiisoft/yii2/issues/11032#issuecomment-193140267), пожалуйста. Если вы не против - применим такой патч.

**Comment by samdark** [comment]
Я не против.

**Comment by klimov-paul** [comment]
Мне тяжело судить - я полагаюсь на ваше мнение.

**Comment by SilverFire** [comment]
Предложено решение лучше: https://github.com/yiisoft/yii2/pull/10538

**Comment by SilverFire** [comment]
Переносится на 2.1.x из-за того, что PR #10538 ломает обратную совместимость

**Comment by dynasource** [comment]
see https://github.com/yiisoft/yii2/pull/13545#issuecomment-280837915

**Comment by derekisbusy** [comment]
#13545 and yiisoft/jquery-pjax#52 may fix this issue.
