### ISSUE TITLE
ArrayHelper::add

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#11031]
Like ArrayHelper::remove but add if not set, instead of

```
        if (!isset($options['alt'])) {
            $options['alt'] = '';
        }
```

add($array, $key, $value) :)

**Comment by samdark** [comment]
How is it better than `$arr[$key] = $value;`?

**Comment by DrDeath72** [comment]
t's yours code :)
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L430
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L468
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L525
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1730
etc...

**Comment by samdark** [comment]
Ah. Then the name isn't correct. It's not really "add". @yiisoft/core-developers any idea on how to name it better?

**Comment by DrDeath72** [comment]
include?

**Comment by SilverFire** [comment]
I've googled a little bit and found smth similar in [Laravel](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Arr.php#L31) and it is called `add` there. But I agree with @samdark that `add` is not the best method name.

Maybe, something like `put` or `addIfNot` or `setIfNot`..

**Comment by kidol** [comment]
There is `Cache::add()` though. Better let doc comments do the description in favor for short name.

**Comment by samdark** [comment]
OK. Probably `add()` isn't that bad...

**Comment by SamMousa** [comment]
How about `default()` or `setDefault()` since that what it'll probably be used for?

**Comment by DrDeath72** [comment]
default sux

**Comment by klimov-paul** [comment]
What is wrong with `ArrayHelper::merge()`?
It seems it could solve this need pretty well:

```php
$myArray = ArrayHelper::merge(['alt' => ''], $myArray);
```

**Comment by samdark** [comment]
Same thing, different syntax.

**Comment by twisted1919** [comment]
Since there is a check for key existance, `add` makes sense, otherwise would have been just `set`.

**Comment by samdark** [comment]
Yes. I think it makes sense.

**Comment by dynasource** [comment]
this is covered by PHP7:
```php
$array['key'] =$array['key'] ?? 'new value';
```
