### ISSUE TITLE
Have you considered adding a magic property getIsAjaxButNotPjax() to `yii\web\Request`?

### ISSUE THREAD

**Issue by vistart** [yiisoft/yii2#11039]
Maybe I would regard the form action as the validation URL. and the validation request is AJAX-style but not PJAX, meanwhile the form submission process is PJAX-style (also known as AJAX-style).
Now, If I want to know whether the request is validation or submission, I would take the following statements:
```php
public function actionNew()
{
    if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax) {
        // validation
    }
    // submission
}
```
In the above conditional statement, the `getIsPjax()` method will execute `getIsAjax()` method again, and the position of these two magic properties cannot be switched.
Have you considered adding the following magic property to `yii\web\Request`:
```php
public function getIsAjaxButNotPjax()
{
    return $this->getIsAjax() && empty($_SERVER['HTTP_X_PJAX']);
}
```
in order to avoid executing `getIsAjax()` twice.

**Comment by cebe** [comment]
`getIsAjax()` contains a very trivial check so what do we gain by adding this method?

**Comment by vistart** [comment]
Two checks(isAjax && !isPjax) may be reduced to only one.

**Comment by cebe** [comment]
yes but what is the benefit? it will hardly be any faster.

**Comment by vistart** [comment]
Right, the performance improvement is very limited.
