### ISSUE TITLE
Formatter asDuration(0) returns nulldisplay instead of 0 seconds

### ISSUE THREAD

**Issue by VirtualRJ** [yiisoft/yii2#11038]
`Yii::$app->formatter->asDuration(0)` returns the `nullDisplay` variable. Is this by design or can we enhance the output to either `'0 seconds'` or `'<1 second'`.

**Comment by cebe** [comment]
I don't think it is by design, we do not have a test for it, so I would consider it a mistake that should be fixed. Can you send a pull request?

**Comment by Ni-san** [comment]
Easy to fix, but what about the wrong values? Maybe we should throw a human-readable exception for all cases

**Comment by VirtualRJ** [comment]
@Ni-san what do you consider a wrong value?

**Comment by Ni-san** [comment]
Anything that is not a string or a number and any string which cannot be parsed as an interval

**Comment by VirtualRJ** [comment]
@Ni-san the construct of DateInterval throws a readable error (which it will do if none of the possible options match): `DateInterval::__construct(): Unknown or bad format ([the value specified])`. Don't think a custom error handler will give a better readable response than that.
