### ISSUE TITLE
yii.validation.js should use Regexp.test instead of String.match

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#11037]
This is just a small nitpick.
yii.validation.js uses [String.match](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/match), but since it only cares whether there is a match or not, it should use [RegExp.test](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test).

On a related note, you don't have any tests for the js validation code, right?

**Comment by cebe** [comment]
makes sense, can you send a pull request?

> On a related note, you don't have any tests for the js validation code, right?

we currently do not have any, do you have an idea how to easily set up testing for these?

**Comment by nkovacs** [comment]
Yeah, I have set up mocha for javascript unit testing in my Yii apps. There's a small Yii app inside the test directory with a single controller and a single view that loads mocha + a bunch of libraries (chai, sinon, leche and their connectors), the asset bundles to be tested and their corresponding test asset bundles, and then uses [mocha-phantomjs](https://www.npmjs.com/package/mocha-phantomjs) to run the tests.
Travis unfortunately doesn't support multiple languages, so [you have to manually install npm using nvm](http://austinpray.com/ops/2015/09/20/change-travis-node-version.html) if you want to have npm in your project. And it's probably going to run the mocha tests for each php version needlessly.

**Comment by nkovacs** [comment]
Here's a prototype: https://github.com/yiisoft/yii2/compare/master...nkovacs:mocha
You can open the index-test.php file in a browser to run the tests. I haven't set up travis yet, and a lot of the code is really ugly and hacky, but some of that is also unavoidable, since I wanted to use `clientValidateAttribute` to generate the options used by the js code instead of hardcoding it into the js test file.

**Comment by cebe** [comment]
cool, thanks. will check it out.

**Comment by arogachev** [comment]
This also applies to `yii.js`. For js tests I think it's better to create separate issue since it's more common and complex problem.
