### ISSUE TITLE
Mode::findOne() problem

### ISSUE THREAD

**Issue by Sajjad-dehghani** [yiisoft/yii2#11042]
Hello,
I was try to use Model::findOne() on models and i have a problem, Why findOne() is not case sensitive?

$result=Model::findOne(["value"=>'a']);
$result=Model::findOne(["value"=>'A']);

They are return same result and don't have different result?

What is my bad coding? 
Thanks.

**Comment by cebe** [comment]
this depends on your database. if your dbms collation is case insensitive, it will find the same records if you query for A or a. In mysql, e.g. `utf8_unicode_ci` the `ci` part stands for case insenstive.
this has nothing to do with yii or `findOne()` in particular.
