### ISSUE TITLE
Formatter error on dateTime and time.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#11059]
I am using formatter functions `asDatetime` and `asTime` and it's working fine but i noticed that it's logging an error message that says:

`yii\i18n\PhpMessageSource::loadFallbackMessages`
> The message file for category 'yii' does not exist: C:\xampp7\htdocs\oceanview\vendor\yiisoft\yii2/messages/en_US/yii.php Fallback file does not exist as well: C:\xampp7\htdocs\oceanview\vendor\yiisoft\yii2/messages/en/yii.php

`asRelativeTime` and other formatter functions works fine.
The 2 files are missing from all of my yii2 applications.

**Comment by SilverFire** [comment]
What version of Yii2 do you use?
AFAIK I've fixed this problem in 2.0.7 release:

> Bug #7964: Fixed i18n message sources to load fallback messages in a smarter way (silverfire)

**Comment by Locustv2** [comment]
I am using 2.0.7 Version.

**Comment by SilverFire** [comment]
What are your application and source languages?

**Comment by Locustv2** [comment]
i18n is not configured and the language set in my config is `en_US`

**Comment by SilverFire** [comment]
The language and locale separator is `-`, not `_`. Change language to `en-US` and problem will disappear.

**Comment by Locustv2** [comment]
Ok all working now, the problem disappeared but the fallback file `/vendor/yiisoft/yii2/messages/en/yii.php` still does not exist?

**Comment by SilverFire** [comment]
It must not exist. Yii2 source language is English, no need to translate English to English.

**Comment by kavolorn** [comment]
Looks like fix is working for en-US, but my app has en-GB as default one. Should it be working too?

**Comment by SilverFire** [comment]
@kavolorn please, create a separate issue with detailed description
