### ISSUE TITLE
controller->redirect() not support checkAjax

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#11058]
Hi

yii\web\Respone->redirect() has tree parameters

~~~
public function redirect($url, $statusCode = 302, $checkAjax = true)
~~~

why not add the same parameter in yii\web\Controller->redirect() ?

**Comment by SilverFire** [comment]
It's a minor BC break, however the idea is good.

I think we can do it. @yiisoft/core-developers thoughts?

**Comment by samdark** [comment]
What's the use case when checking AJAX should be turned off?

**Comment by pigochu** [comment]
@samdark 
I test in Yii 2.0.7. and create simple CRUD code via gii.

If I use GridView in Pjax , when I click "delete" button  . it will load full page.

but when I turn off ajaxCheck , it will redirect to  actionIndex() and load pjax content.

~~~
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return Yii::$app->getResponse()->redirect(['category/index'], 302, false);
    }
~~~

**Comment by samdark** [comment]
OK. Looks valid.

**Comment by almirb** [comment]
Hello @pigochu !

I used your approach above and is working fine. The only thing that's a little annoying is the scroll of the page to the top after the delete action.  
Are you experiencing the same?

**Comment by lynicidn** [comment]
```php
if (Yii::$app->request->isAjax) {
    return Yii::$app->response->redirect(['category/index'], 302, false);
}
```

what is behavior if request is ajax and need check on it? return 302 code?

**Comment by almirb** [comment]
I solved It with:
````js
$.pjax.defaults.scrollTo = false;
````

Also tried to put this setting internally into my Kartik gridview with the code below, to avoid global changes i in my pjax configuration:
````php
'pjaxSettings' => ['options' => ['scrollTo' => false]],
````
But It didn't work.

**Comment by pigochu** [comment]
Now I upgrade yii to 2.0.8 , and create a test controller for testing.
I create CRUD from gii and "Enable Pjax" checkbox is checked .

I have not change any code . I got the response when I click "Delete".
![image](https://cloud.githubusercontent.com/assets/1013744/15796553/413aac52-2a32-11e6-949d-ae659aa85ad8.png)

We can see , the page will not load by pjax, other file still loaded.

But I change code in my action.

```
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        if (Yii::$app->request->isAjax) {
            return Yii::$app->response->redirect(['/group-test/index'], 302, false);
        }
        return $this->redirect(['index']);
    }

```
![image](https://cloud.githubusercontent.com/assets/1013744/15796597/e5f8448e-2a32-11e6-93da-99abc4a0a7fc.png)

The page will load index only.
