### ISSUE TITLE
Controller::redirect() does not work from ErrorHandler::errorAction

### ISSUE THREAD

**Issue by m00nk** [yiisoft/yii2#11054]
Задача:
в проекте есть много мест, где для неавторизованных пользователей вызывается **throw HttpException(403)**. Нужно только гостей редиректить на страницу аутентификации. Решено было таким образом:

в конфиге подключаем **errorHandler**

```php
		'errorHandler' => [
			'errorAction' => 'site/error',
		],
```

В **SiteController** такой код:

```php
	public function actionError()
	{
		if(($exception = Yii::$app->getErrorHandler()->exception) === null)
			$exception = new HttpException(404, Yii::t('yii', 'Page not found.'));

		if($exception instanceof HttpException)
			$code = $exception->statusCode;
		else
			$code = $exception->getCode();

		if($code == 403 && Yii::$app->user->isGuest)
			return $this->redirect(['/user/account/login']);

		...
```

В одной из предыдущих версий это работало нормально, но сейчас страница стала получать код статуса 403, вместо 302 и редиректа не происходит:

![redirect](https://cloud.githubusercontent.com/assets/516574/13614564/36909108-e582-11e5-97a3-28dc9cc23c62.png)

Если это не ошибка, то подскажите как правильно разрулить ситуацию. 

Спасибо и сорри за русский.

**Comment by SilverFire** [comment]
На первый взгляд все правильно. Вы порождаете HttpException со статус-кодом 403, а потом еще довешиваете редирект.

> подскажите как правильно разрулить ситуацию

Я бы исправил ваш код таким образом:

```php
        if($code == 403 && Yii::$app->user->isGuest) {
            Yii::$app->response->statusCode = 302;
            return $this->redirect(['/user/account/login']);
        }
```



> В одной из предыдущих версий это работало нормально

Точного ответа дать не могу, можете попробовать найти коммит, изменивший поведение с помощью [git bisect](https://git-scm.com/book/ru/v1/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-Git) и я постараюсь это прокомментировать.

Пока задачу закрываю, но если что - высказывайте свои мысли.

**Comment by SilverFire** [comment]
Хм, что-то я фигню посоветовал :)

Если посмотреть на [ErrorHandler.php:120](https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L120-L124), можно увидеть, что статус-код будет все равно установлен из исключения.

Попробуйте

```php
        if($code == 403 && Yii::$app->user->isGuest) {
            $exception->statusCode = 302;
            return $this->redirect(['/user/account/login']);
        }
```

**Comment by m00nk** [comment]
> На первый взгляд все правильно. Вы порождаете HttpException со статус-кодом 403, а потом еще довешиваете редирект.

И в чем криминал-то? Кто сказал, что исключение должно обязательно всплыть на самый верх? Ведь ErrorHandler и создан, чтобы его перехватывать и обрабатывать как-то более цивилизованно, чем просто вывести "404 Page not found". Или я не прав?

Решение с $exception->statusCode = 302; не проходит, т.к. переменная $exception внутренняя для метода внутри ErrorHandler::renderException(), из SiteController::actionError() ее изменить нельзя. Потому тикет и создал.

Заменить во всем коде все вызовы HttpException на что-то типа
if(Yii::$app->user->isGuest) return $this->redirect(...); else throw HttpException(403) конечно можно, то как-то это коряво. 

Я пока решил так: создал потомка ErrorHandler, подменив в нем метод renderException(), изменим в нем завершающий код:

было:
```php
   if ($exception instanceof HttpException) 
            $response->setStatusCode($exception->statusCode);
   else
            $response->setStatusCode(500);

   $response->send();
```
стало:

```php
	if($response->statusCode != 302)
	{
		if($exception instanceof HttpException)
			$response->setStatusCode($exception->statusCode);
		else
			$response->setStatusCode(500);
	}

	$response->send();
```

Для моего случая работает. Имхо такое поведение  (редиректы пропускаем, иначе возвращаем статус, порожденный исключением) более логично. Может стоит внести в фремворк?

**Comment by samdark** [comment]
```php
Yii::$app->getResponse()->redirect($url)->send();
return;
```

**Comment by samdark** [comment]
Обработка ошибок — особый случай.

**Comment by jonpaulh** [comment]
This note saved my life. Thank you. I can now use the below in my config

    `'on beforeAction' => function ($event){
        
        if(Yii::$app->user->isGuest && Yii::$app->getRequest()->url !== Url::to(Yii::$app->getUser()->loginUrl))
        {
            Yii::$app->getResponse()->redirect(Url::to(\Yii::$app->getUser()->loginUrl))->send(); 
            return;
        }

    },`
