### ISSUE TITLE
Bind array in the ON condition inside the INNERJOIN

### ISSUE THREAD

**Issue by andresilvawebcomum** [yiisoft/yii2#11053]
Good afternoon,

I'm having a little trouble defining the ON condition inside the INNERJOIN. As the documentation states the ON parameter can either be a string or an array.

In my specific case, I have a variable named "category" that can either be an array or an integer. When the variable is an array I have to use the following code in order to build the IN statement inside the query.

```php
$this->innerJoin('shop_categories_lang scl', [
    'shop_products_categories.id_category => scl.id_category',
    'scl.is_visib' => 1,
    'scl.id_category' => $id_category,
    'scl.lang' => \Yii::$app->language
]);
```

But by using this code `'shop_products_categories.id_category' => 'scl.id_category'` doesn't work since the generated SQL will be <code>\`shop_products_categories\`.\`id_category\` = 'scl.id_category'</code> which isn't the desired output, since the tables won't be joining properly.

However if I use the following string format, I'll have no way to bind an array in order to build the IN part of the query.

`$this->innerJoin('shop_categories_lang scl', '(scl.id_category = shop_products_categories.id_category) AND (scl.is_visib=1) AND (scl.id_category IN (:category)) AND (scl.lang=:lang)', [':category' => $category, ':lang' => \Yii::$app->language]);`

What's the best way to build the IN part of the query while maintaining  this desired output `'shop_products_categories.id_category' = `scl`.`id_category`

**Comment by SilverFire** [comment]
Please, try the following:

```php
    'shop_products_categories.id_category' => new \yii\db\Expression('scl.id_category')
```
