### ISSUE TITLE
Ajax logout

### ISSUE THREAD

**Issue by sushil2501** [yiisoft/yii2#11064]
Hi lam trying to logout using Ajax but when I refresh the page it show the user still logged in.is there any way to logout using Ajax in yii2

**Comment by gramotei** [comment]
Hello @sushil2501 !

Could you please post the code for both JS and your backend. Because for me it works both logout and even redirect to home because Yii has special handler for this. (it is listening for X-Redirect header in  .ajaxComplete )

```javascript

<button id="logout" type="button">logout</button>
<?php $this->registerJs('initlogout()'); ?>
<script type="text/javascript">
	function initlogout() {
		$('#logout').click(function() {
			alert('logging out');
			$.ajax('/user/logout', {
				method: 'GET',
				success: function() {
					alert('done');
				}
			});
		});
	}
</script>
```

```php
public function actionLogout() {
    Yii::$app->user->logout();
     $this->redirect(['/']);
}

```

**Comment by SDKiller** [comment]
@sushil2501 

May be you have something like this in controller:

https://github.com/yiisoft/yii2-app-advanced/blob/master/frontend/controllers/SiteController.php#L46

?

**Comment by SilverFire** [comment]
Show your code

**Comment by sushil2501** [comment]
Hi @gramotei 

this is  my code

**Comment by sushil2501** [comment]
Hi @gramotei

thank you i just got it working.problem was related to my code.there are other things which i was doing in my actionLogout() that was killing the code before reaching it to the Yii::$app->user->logout();
