### ISSUE TITLE
Yii2 Rest checkAccess ViewAction

### ISSUE THREAD

**Issue by scottix** [yiisoft/yii2#11065]
I don't quite understand the logic of checkAccess in the Yii Rest API

yii2\rest\ViewAction.php
```
$model = $this->findModel($id);
if ($this->checkAccess) {
    call_user_func($this->checkAccess, $this->id, $model);
}
```
Why would I query the model before I have verified access?

Also the model is irrelevant to whether I have access to it not.

**Comment by fernandezekiel** [comment]
this can be record-level access, not just access of controller/action

**Comment by scottix** [comment]
I'll give you an example:
I have a model called Widgets and I have valid access to the action, and I want to access widget id 5

Rest Call:
Authorization: Bearer ABCDE
GET widget/id/5

I have another model widget_permissions that has a record
ABCDE -> [1,2,3,4,6]
which shows ABCDE does not have access to widget 5 but I still query it regardless?

**Comment by tunecino** [comment]
Here is one more example: 

Your model represents an Article and only its Author is allowed to Edit or Delete it:

```php
public function checkAccess($action, $model = null, $params = [])
{
    if ($action === 'update' or $action === 'delete') {
        if ($model->author_id !== \Yii::$app->user->id)
            throw new \yii\web\ForbiddenHttpException('You can only '.$action.' articles that you\'ve added.');
    }
}
```

**Comment by Forin** [comment]
... continued in forum: http://www.yiiframework.com/forum/index.php/topic/70163-yii2-rest-checkaccess/
