### ISSUE TITLE
Problem with mocks in tests with Object

### ISSUE THREAD

**Issue by Koudy** [yiisoft/yii2#11062]
Hello, I have some strange behavior in tests: when I mock class which is inherited from Object I can't call to some(I realy don't know whats the difference) functions - it just return ```NULL``` without any errors:

```
$tmpMock = $this->getMock(\yii\base\Object::class);

var_dump($tmpMock->hasProperty('tmp'));
exit;
```
Result is:
![a033044368190da562e962d687af9e09](https://cloud.githubusercontent.com/assets/4976467/13637152/42790160-e61f-11e5-930b-5463ad380fc0.png)

And same behavior for private and nonexistent function: I can call to it without any errors and it will return ```NULL```.

```
$tmpMock = $this->getMock(\yii\base\Object::class);

var_dump($tmpMock->someFnc());
exit;
```
Result the same.

When I mock class, which isn't inherited from Object, I get an error(Pricelist is not extends from Object):
```
$tmpMock = $this->getMock(Pricelist::class);

var_dump($tmpMock->someFnc());
exit;
```
Result is:
![6d0b7892c2a18a0353b9c5dd7448fce3](https://cloud.githubusercontent.com/assets/4976467/13637312/2ccda18a-e620-11e5-963d-d915946c4b15.png)

And I have no problem to call existing functions of this class.

Im use Yii ```2.0.7```, yii2-codeception ```2.0.4```, codeception ```2.1.2``` (same on the 2.1.6) and php7.

**Comment by Koudy** [comment]
@klimov-paul, it's not a question, it's a bug, I can't test code, can't mock functions.

**Comment by klimov-paul** [comment]
Do you know waht exactly ` $this->getMock()` does?

**Comment by Koudy** [comment]
@klimov-paul, I need mock function, like ```isCanCalculated``` so it will return ```true```, then I try to call public function ```calculate``` and it just return ```NULL``` and doesn't execute code.

**Comment by klimov-paul** [comment]
So, you do NOT know.
Lets take another try: how does `getMock()` method works.
Really, once you will get question answered - you can resolve your problem.
So?

**Comment by klimov-paul** [comment]
I can tell for sure, this does not relates to Yii - it relates to 'PHPUnit Mock Framework' usage.
You have made quite a common mistake with your code.
But one you'll give enough attention to the description of the `getMock()` method and its arguments - you can get things right.

**Comment by Koudy** [comment]
@klimov-paul, thanks.
