### ISSUE TITLE
i have problem with the console, csrf validation.

### ISSUE THREAD

**Issue by alfredogt** [yiisoft/yii2#11069]
I'm trying to run a background process.
my idea is, execute a command in php which in turn run the console Yii2.

$result = exec('php yii controller/action param param > result.log &');

In Localhost everything works great, but the server does not work :(

shows me the message: "Unable to verify the data sent", this should not make sense since it is running from the console.

When I run the command directly from the console, everything is going well, but when the command is launched at runtime does not work.

Friends, thank you very much collaboration.

"This was translated from Spanish"

**Comment by Ni-san** [comment]
To run this action from console you should disable CSRF validation (in your controller declare public $enableCsrfValidation = false; or redeclare public function beforeAction). On the other hand, the best solution is to create command for this action (console controller, extends yii\console\Controller)
