### ISSUE TITLE
Conflict of data-method with Trix editor

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#11060]
The [Trix](https://trix-editor.org/) from basecamp has buttons with `data-method` attributes in it's toolbar. This conflicts, if you also load the `yii.js` asset on a page. It will basically always submit the form when you click any of the Trix editor buttons in a dialog, for example the Link dialog.

This could be fixed if we check for valid values of `data-method` (GET, POST, DELETE, ...) and ignore all other cases in `yii.js`.

Als see https://github.com/basecamp/trix/issues/200

**Comment by SamMousa** [comment]
Checking for specific values is not only inefficient, it is not a generic solution; since there could be other libraries that conflict.
I propose instead disabling the handler for any descendants of a noconflict class, for example: `disable-yii-handlers`.

**Comment by mikehaertl** [comment]
@SamMousa Sounds good. There's just a limitation, that you can't have both, Yii + Trix in any container with `.disable-yii-handlers`. But I could live with that.

Sidenote: Trix team also suggested, that they'd accept a change to `data-trix-method`. I'll see if I find time for it. But we should also fix it on the Yii side of things. `data-method` is very generic and could still be used by other libraries.

**Comment by SilverFire** [comment]
Resolved by https://github.com/basecamp/trix/pull/203
