### ISSUE TITLE
add additional param to not encode the key

### ISSUE THREAD

**Issue by ApXaHgheJI** [yiisoft/yii2#11068]
There is also a problem : 
I store from other project an key=value
When I try to get it from Yii2: Key = app_routes_urls - it make a md5 of this key.
Because in my key are "_" simbol.

Problem 
$key = ctype_alnum($key) && StringHelper::byteLength($key) <= 32 ? $key : md5($key);

There is no flag for leave the key unchanged.
I think its a good idea for cases like this - when you need to work with external MemCache service.

**Comment by SilverFire** [comment]
I'm sorry to say, but your description is unclear to me. 

What part of code are you talkin about? What is the actual and expected result? How to reproduce?

P.S.: мы знаем русский

**Comment by ApXaHgheJI** [comment]
"/vendor/yiisoft/yii2/caching/Cache.php" путь к скрипту и метод "buildKey"

Ок - очень рад - и так трабла в том что - если использовать данный класс для получения данных из внешней БД MemCache - и при этом в ключе есть спец символы а не только буквы от A-Za-z, а такие как (_ underscore ) - тогда скрипт хэширует всегда в md5 ключь - и запрашивает get(md5(key)).

ИМХО - это не удобно - мой случай в том что сайт написан на одном движке а Back я пишу на Yii2.
И так будет всегда - так как в классе данный метод отвечает за создание ключа - но было бы хорошо думаю добавить спец параметр для того что бы ключ не менялся - а запрашивался таким , каким его указали.

Возможно такая же тема была бы актуальна и для метода set().

Как выход вижу в класс MemCache добавить параметр - leaveKeyUnchanged - его можно было бы задавать от куда надо ( тобишь конфиг или что еще ) и в "buildKey" методе проверять данный параметр.


Вот примерно так.

**Comment by SilverFire** [comment]
Спасибо, так понятнее.

Как вы правильно заметили, `_` не относится к численно-буквенным символам, потому происходит преобразование в md5. Такое поведение функции ожидаемое и не будет изменено в ядре, в том числе из соображений сохранения обратной совместимости.

Самым простым и правильным решением для вас будет создание своего класса `Cache`, который будет наследоваться от `yii\caching\Cache` и содержать переопределенный метод `buildKey()`.

**Comment by ApXaHgheJI** [comment]
согласен с вами - можно наследовать - но и гибкость никто не отменял...
поделился мыслями )
