### ISSUE TITLE
Query count() doesn't work when its used with joinWith()

### ISSUE THREAD

**Issue by rampach** [yiisoft/yii2#11063]
If in the DB you have:
User - 1 row
Articles - 5 rows

`<?php .... User::find()->joinWith('articles')->count();  ....?>`

The count will return 5, but I think that it should return 1.To work as expected I need to change the query to:

`<?php .... User::find()->joinWith('articles')->count('DISTINCT ' . User::tableName() . '.Id');  ....?>`

**Comment by gramotei** [comment]
@rampach  I think it works as excepted. It doesn't know what actually you want to count if you don't specify distinct. And in this case User is also not needed. Assuming you have **user_id** column in **Articles** table and that **user_id** could not be _null_ I would write:

```php
Article::find()->select('user_id')->distinct()->count();
```

**Comment by rampach** [comment]
@gramotei if i want to list only the users that posted only active articles like:

`
$query = User::find()
->joinWith('articles')
->where([Article::tableName() . '.Status' => Article::STATUS_ACTIVE]);

return new ActiveDataProvider([
    'query' => $query,
]);
`
In this case the totalCount of the provider will be 5, not 1.But in the grid for example, there will be only one user. Is this the correct behaviour?

**Comment by cebe** [comment]
if you join, you have to ensure models in the result are unique. In your query, adding distinct may already be enought for that:

```php
$query = User::find()->distinct()->joinWith('articles')->where([Article::tableName() . '.Status' =>Article::STATUS_ACTIVE]);
```
