### ISSUE TITLE
Set $extraParams from Swift_Transport_SimpleMailInvoker in yii2-swiftmailer

### ISSUE THREAD

**Issue by EvilKarter** [yiisoft/yii2#11061]
I am using Yii2 with the yii2-swiftmailer extenxion. I want to set the parameter $extraParams of the Swift_Transport_SimpleMailInvoker

At the moment I changed the class to this:

    class Swift_Transport_SimpleMailInvoker implements Swift_Transport_MailInvoker
    {
          public function mail($to, $subject, $body, $headers = null, $extraParams = null)
          {
              $extraParams = '-f my@email.com'; // I added this line
             
              if (!ini_get('safe_mode')) {
                  return @mail($to, $subject, $body, $headers, $extraParams);
              } else {
                  return @mail($to, $subject, $body, $headers);      
              }
          }
    }

It works quite fine but is really not a clean solution to change a file in the vendor directory. I also tried the possibility to set the $extraParams in the yii Project but it doesn't work. 

SO can you please add a function like setExtraParams($string) in the yii2-swiftmailer Extensioen?

**Comment by klimov-paul** [comment]
There is no need of 'mail invoker' usage. It is triggered from 'transport'. You should setup corresponding transport to use plain `mail` function.

**Comment by EvilKarter** [comment]
thx kilmov-paul.
But is there a way to reuse all created templates in mail directory? or have to be all templates to be rebuild as Strings?
