### ISSUE TITLE
can not install bower-asset/jquery 1.11.*@stable

### ISSUE THREAD

**Issue by kminooie** [yiisoft/yii2#11070]
I do have latest fxp/composer-aset-plugin (v1.1.2) but when I try to force jquery 1.11 by adding this "bower-asset/jquery": "1.11.*@stable" 
to composer.json file after creating a new YII2 project, I end up getting this error:

> Your requirements could not be resolved to an installable set of packages.
>
> Problem 1
>    - The requested package bower-asset/jquery could not be found in any version, there may be a typo in the package name.
>  Problem 2
>   - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
>    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
>    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
>    - Installation request for yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yii2[2.0.6, 2.0.7].

this is really issue #6537 but that one is locked for some reason. this used to work before, I don't know if its the recent updates in composer in fxp/composer-asset-plugin but it has stopped working.

my current composer version is "Composer version 1.0-dev (e8abc90b923250527a2d68712b663f0f41790594) 2016-03-09 11:44:27"

I have already created this issue https://github.com/francoispluchino/composer-asset-plugin/issues/202  

and was able to work around it by removing bower-asset/jquery 1.11.*@stable from composer.json, running composer update and then adding it from command line: 

> composer require "bower-asset/jquery:1.11.*@stable"

I thought that I should mention it here in case other people had the same issue. I don't actually expect anything be done about it.

**Comment by SilverFire** [comment]
The issue is definitely related to FXP plugin and composer, not to Yii2.
Therefore I'll leave it closed for now

**Comment by anoopcontriverz** [comment]
This issue is related to FXP
so you first update FXP with the below latest command
composer global require "fxp/composer-asset-plugin:~1.0.3" it will work

**Comment by schmunk42** [comment]
I ran into a similar issue. I had a `bower` and `bower-asset` folder in `vendor`. Worked fine after removing them.
