### ISSUE TITLE
exception in BaseArrayHelper (traversable)

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#11071]
so conceived?
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L703
or need 
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L12

**Comment by SilverFire** [comment]
It's not by design, we've just overseen it. Would you like to create a PR?

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/91e2c7182603a476305498e7633950d3dd831b7e
