### ISSUE TITLE
Error in ArrayHelper::index

### ISSUE THREAD

**Issue by nesstas** [yiisoft/yii2#11079]
$array = [
    ['id' => '123', 'data' => 'abc', 'device' => 'laptop'],
    ['id' => '345', 'data' => 'def', 'device' => 'tablet'],
    ['id' => '345', 'data' => 'hgi', 'device' => 'smartphone'],
];
$result = ArrayHelper::index($array, null, 'id');
Аrray not grouped by id on the first level.

$result= 
Array
(
    [] => Array
        (
            [id] => 345
            [data] => hgi
            [device] => smartphone
        )

)

**Comment by samdark** [comment]
Which Yii version do you use?

**Comment by nesstas** [comment]
yii2 2.0.7

**Comment by SilverFire** [comment]
This method is available in the development version of Yii2 framework and will be available in release 2.0.8.
