### ISSUE TITLE
Confusing documentation of yii\web\Response::redirect()

### ISSUE THREAD

**Issue by microcosm-maureen** [yiisoft/yii2#11078]
The documentation of the `$url` parameter states, "Note that the route is with respect to the whole application, instead of relative to a controller or module." This seems to suggest that to redirect to e.g. `posts/index` `$url` must be `['posts/index']`. However, Gii's CRUD generator creates code like this:

    public function actionDelete($id)
    {
      $this->findModel($id)->delete();
      return $this->redirect(['index']);
    }

Which redirects to the current controller's `index` action. I think it would be fine to remove that sentence entirely, as the next sentence links to `yii\helpers\Url::to()`, which links to `yii\helpers\Url::toRoute()`, which documents the correct format.

**Comment by cebe** [comment]
`$this->redirect()` refers to the controller method `redirect()`, which is able to resolve relative routes. 
`yii\web\Response::redirect()` is a different method.

**Comment by microcosm-maureen** [comment]
D'oh! Thanks for clarifying.
