### ISSUE TITLE
Throwing UserException includes the stack trace to the end user

### ISSUE THREAD

**Issue by adamwinn** [yiisoft/yii2#11084]
In my code I have:
```phpcode
throw new UserException('Error:  File has a very large number of rows.  The file is most likely corrupt.');
```
I read that throwing a UserException will not show the stack trace to the end user, but when the exception is thrown, yii is outputting:
```phpcode
exception 'yii\base\UserException' with message 'Error: File has a very large number of rows. The file is most likely corrupt.' in /Users/awinn/Documents/code/htdocs/remv2/models/Agreement.php:320 Stack trace: #0 /Users/awinn/Documents/code/htdocs/remv2/controllers/SiteController.php(224): app\models\Agreement->import() #1 [internal function]: app\controllers\SiteController->actionUpload() #2 /Users/awinn/Documents/code/htdocs/remv2/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #3 /Users/awinn/Documents/code/htdocs/remv2/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #4 /Users/awinn/Documents/code/htdocs/remv2/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('upload', Array) #5 /Users/awinn/Documents/code/htdocs/remv2/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('site/upload', Array) #6 /Users/awinn/Documents/code/htdocs/remv2/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) #7 /Users/awinn/Documents/code/htdocs/remv2/web/index.php(17): yii\base\Application->run() #8 {main}
```
my http sniffing program I have shows the below response from the server, which is all I want to show to the user.
```phpcode
Exception: Error:  File has a very large number of rows.  The file is most likely corrupt.
```

**Comment by adamwinn** [comment]
Yes I do.  But that shouldn't matter since the docs at http://www.yiiframework.com/doc-2.0/guide-runtime-handling-errors.html say:

> Info: If an exception is a descendant of yii\base\UserException, no call stack will be displayed regardless the value of YII_DEBUG. This is because such exceptions are considered to be caused by user mistakes and the developers do not need to fix anything

**Comment by SDKiller** [comment]
https://github.com/yiisoft/yii2/issues/6723#issuecomment-68508428

**Comment by adamwinn** [comment]
So how can I throw an error message to the user without the stack trace included?  The docs I referenced earlier state that it is possible.

**Comment by SilverFire** [comment]
Failed to reproduce on clean Basic Yii2 Application template:

![screenshot 2016-03-11 0013](https://cloud.githubusercontent.com/assets/4499203/13695141/64f7dbf8-e764-11e5-902e-fddd7b7b2f9f.png)

```difff
diff --git a/controllers/SiteController.php b/controllers/SiteController.php
index 4ffba24..7fb2ab3 100644
--- a/controllers/SiteController.php
+++ b/controllers/SiteController.php
@@ -3,6 +3,7 @@
 namespace app\controllers;
 
 use Yii;
+use yii\base\UserException;
 use yii\filters\AccessControl;
 use yii\web\Controller;
 use yii\filters\VerbFilter;
@@ -89,6 +90,9 @@ class SiteController extends Controller
 
     public function actionAbout()
     {
+        throw new UserException('test');
+
+
         return $this->render('about');
     }
 }
```

Result is the same regardless of YII_DEBUG flag state

**Comment by SilverFire** [comment]
[ErrorHandler::convertExceptionToString()](https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L307) is also adjusted to work as expected
