### ISSUE TITLE
I'm always authorized in Yii2

### ISSUE THREAD

**Issue by semiromid** [yiisoft/yii2#11089]
I use the example of a standard user authentication (basic). I open - basic/web/index.php?r=site/login
and write login and password - admin/admin.

If i use browser GoogleChrom, I'm always authorized in Yii2. Even if I reboot the computer.
```
.....
return Yii::$app->user->login($this->getUser(), 60);
.....
```

How can I fix this? This is not normal behavior.

**Comment by SilverFire** [comment]
Please, do not open multiple issues for the same problem. Let's continue discussion in your previous issue #11085
