### ISSUE TITLE
Cookies are not deleted in Google Chrome if use yii2

### ISSUE THREAD

**Issue by semiromid** [yiisoft/yii2#11085]
I use framework Yii2. When i make:

`Yii::$app->user->login($this->getUser(), 60);//cookies for 60 seconds`

Browser Google Chrome does not remove cookies after the expiration of 60 seconds.

If I do not use a framework Yii2: (если использовать чистый php , не использовать механизм Yii::$app->user->login Yii2)

`setcookie("test", time() + (60), "/"); `

it all works. (То всё работает хорошо) 

Why, if you use Yii2, that does not  delete cookies in browser GoogleChrom?

**Comment by SilverFire** [comment]
Failed to reproduce

![screenshot 2016-03-11 001](https://cloud.githubusercontent.com/assets/4499203/13695011/6119128c-e763-11e5-85ef-67552b41c14c.png)

**Comment by SilverFire** [comment]
Try to reproduce on clean application install and post exact steps to reproduce the problem. I'm closing issue for now/

**Comment by SilverFire** [comment]
This comment was originally posted by @semiromid at https://github.com/yiisoft/yii2/issues/11089.
Moved here by @silverfire.

-----


I use the example of a standard user authentication (basic). I open - basic/web/index.php?r=site/login
and write login and password - admin/admin.

If i use browser GoogleChrom, I'm always authorized in Yii2. Even if I reboot the computer.
```php
.....
return Yii::$app->user->login($this->getUser(), 60);
.....
```



How can I fix this? This is not normal behavior.

**Comment by SilverFire** [comment]
Please, show entire list of changes you do to basic application in order to reproduce the problem.

**Comment by semiromid** [comment]
I want to correct the issue.
Cookies are deleted from your browser by timeout.  name cookies -`_identity`
But I'm always authorized in Yii2. Even if I reboot the computer.

I change code in models\LoginForm:
.....
return Yii::$app->user->login($this->getUser(), 60);
.....

```

I change code in config\web.php:
'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
            //'authTimeout' => 10,
            'identityCookie' => [ 
                'name' => '_identity'
            ],
        ],
```

**Comment by SilverFire** [comment]
Confirmed on clean basic application installation.

Steps to reproduce:

1. Clone basic application
2. Navigate on login page
3. Login with demo/demo, leave `Remember me` checkbox **un**checked
4. Close browser
5. Open browser and navigate to basic app homepage.

Expected:

 - User is logged out

Actual:
 - :white_check_mark: FireFox: User is logged out
 - :x: Chrome: User is logged in

Can anybody else reproduce? @yiisoft/core-developers

**Comment by samdark** [comment]
https://stackoverflow.com/questions/10617954/chrome-doesnt-delete-session-cookies

**Comment by samdark** [comment]
Seems to be Chrome, not us.

**Comment by semiromid** [comment]
As yii2 determines that the user is authenticated, if cookies  deleted from your browser?  name cookies -_identity.

**Comment by samdark** [comment]
Session.

**Comment by semiromid** [comment]
I would like to invite you to make a method like authTimeout.

Хочу предложить вам сделать метод, похожий на свойство  authTimeout, что бы можно было по выбору пользователя, устанавливать или не устанавливать время для удаления сессионных кук.

Something like that
Example:
```
public function login()
    {
        if ($this->validate()) {
            Yii::$app->session->authTimeout = $this->rememberMe ? 60 : 0;//<----- Something like that
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 60 : 0);
        }
        return false;
    }
```

**Comment by samdark** [comment]
Have you tried that it works?

**Comment by semiromid** [comment]
This does not work. I gave an example, that would be good. Because in browser GoogleChrom,  does not remove a session cookie.

**Comment by samdark** [comment]
Well, yes. That's browser behavior we can't change.

**Comment by semiromid** [comment]
Почему это нельзя сделать как то так? 
Why is it you can not do something like this?

write in  index.php 



```
/* Начало */

// если у нас есть сессионная кука...
if (!empty($_COOKIE[session_name()])) {
    // сначала явно начнем сессию
    session_status() == PHP_SESSION_NONE && session_start();
    // если сессия свежая (то есть нет нашей пометки о последнем использовании)
    if (empty($_SESSION['LAST_USE'])) {
        // запишем когда сессия начата
        $_SESSION['LAST_USE'] = $_SERVER['REQUEST_TIME'];
    } else {
        // иначе считаем что сессия старая, значит нужно проверить 
        // что сессия не истекла =>
        // если последнее обращение было позже чем 60 секунд назад...
        if ($_SESSION['LAST_USE'] < $_SERVER['REQUEST_TIME'] - 60) {
            // обнулим сессию
            session_destroy();
            $_SESSION = [];
            // и начнем её заново, раз она уже была
            session_start();
        } else {
            // последнее обращение было только что, 
            // сбросим время последнего использования
            $_SESSION['LAST_USE'] = $_SERVER['REQUEST_TIME'];
        }

    }
}

/* Конец */

Yii::createWebApplication($config)->run();
```
