### ISSUE TITLE
ajax bug of verifyCode

### ISSUE THREAD

**Issue by FavorMylikes** [yiisoft/yii2#11090]
Can not set enableClientValidation false and enableAjaxValidation  true at the same time
`$form->field($model, 'verifyCode','enableClientValidation'=>false,'enableAjaxValidation'=>true])`
When you click submit button,browser will send double times ajax requests.
The first time when change verifyCode input,and the second time happened at click submit button.So you will get a error message"The verification code is incorrect" every time

**Comment by SilverFire** [comment]
It is expected behavior. 

http://stuff.cebe.cc/yii2docs/yii-captcha-captchavalidator.html

> Note that once CAPTCHA validation succeeds, a new CAPTCHA will be generated automatically. As a result, CAPTCHA validation should not be used in AJAX validation mode because it may fail the validation even if a user enters the same code as shown in the CAPTCHA image which is actually different from the latest CAPTCHA code.
