### ISSUE TITLE
Wrong behavior of AttributeBehavior::getValue() 

### ISSUE THREAD

**Issue by tonydspaniard** [yiisoft/yii2#11095]
Currently I have faced an issue with `AttributeBehavior::getValue()` when using `BlameableBehavior`. 

Model configuration: 

```php 
// regular configuration 
 public function behaviors()
    {
        return [
            'blameable' => [
                'class' => BlameableBehavior::className()
            ],
// ...
```

Force value setting
```php 
// setting
$make->getBehavior('blameable')->value = $worker->createdBy;  // set the value for blameableBehavior
```
Running the script on CentOS release 6.4 (Final) and PHP 5.6.7 caused the following error: 

```php
call_user_func() expects parameter 1 to be a valid callback, no array or string given 
```
Checking my custom logs, traced back to the `AttributeBehavior::getValue()` which provides the following check: 

```php
 if ($this->value instanceof Closure || is_array($this->value) && is_callable($this->value)) {
 ```
I fixed adding the following prior that check and solved the issue for me: 
```php 
if(is_int($this->value) || is_string($this->value)) {
   return $this->value;
}      
```

**Comment by klimov-paul** [comment]
This is odd. Any string or integer value should not pass the original `if` statement.

**Comment by SilverFire** [comment]
Failed to reproduce. Could you add a failing test or provide more detailed way?

**Comment by tonydspaniard** [comment]
@klimov-paul @SilverFire

> This is odd. Any string or integer value should not pass the original if statement. 

I know, and it did not occurred on my local system (iMac) but on the staging server (CentOS release 6.4 (Final)). 

> Failed to reproduce. Could you add a failing test or provide more detailed way? 

I do not know how can I be more explicit but by writing the tests my self to run on CentOS release 6.4 (Final). 

It was a very awkward issue that happened to the  crawler I wrote for my current project. Will do the tests whenever possible.

**Comment by SilverFire** [comment]
I have some servers with CentOS 6.4. Please, write a test and I'll try it on those servers.
Also it will be good to know PHP version.

**Comment by samdark** [comment]
@tonydspaniard any updates?

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
