### ISSUE TITLE
Bug with Expression parameters binding in a query

### ISSUE THREAD

**Issue by Mirocow** [yiisoft/yii2#11092]
Such dont work

```php
                    $models = CarModel::find()->select([
                            '*',
                            new Expression('MAX( IF(car_generation.year_end IS NULL, 9999, car_generation.year_end) ) as max_year')
                    ])->joinWith('generation')->where(['and',
                            new Expression('car_generation.year_begin IS NOT NULL'),
                            new Expression('cars_model.mark_id=:mark_id AND car_generation.year_begin IS NOT NULL',  [':mark_id' => $this->context->route['models']['MARK']['id']]),
                    ])->groupBy(['cars_model.model_id'])->asArray()->all();
```
but that work right

```php
                    $models = CarModel::find()->select([
                            '*',
                            new Expression('MAX( IF(car_generation.year_end IS NULL, 9999, car_generation.year_end) ) as max_year')
                    ])->joinWith('generation')->where(['and',
                            new Expression('car_generation.year_begin IS NOT NULL'),
                            new Expression('cars_model.mark_id=:mark_id AND car_generation.year_begin IS NOT NULL'),
                    ], [':mark_id' => $this->context->route['models']['MARK']['id']])->groupBy(['cars_model.model_id'])->asArray()->all();
```

So it is a bug or intended?

**Comment by samdark** [comment]
Looks like parameters passed via Expression constructor either aren't used or are overridden instead of being merged.

**Comment by samdark** [comment]
@Mirocow can you check pull request ↑

**Comment by klimov-paul** [comment]
> Such dont work

How exactly it does not work? What is exact error message?

**Comment by samdark** [comment]
@klimov-paul about the parameters aren't bound/

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/b182586cd3ded908cb89801e2d7cdf6fd21d810e

Thank you for your report

**Comment by CedricYii** [comment]
Btw, I think that this feature should be dropped (in Expression and other where clauses as well) as I couldn't see its added value.
The code is getting less clear when using this whereas it's always possible to add an ->addParams() after the query definition. So the framework is encouraging poor coding style, and it's getting more complicated and slower without significant benefits imho.

**Comment by cebe** [comment]
@CedricYii I am planning to review and simplify Querybuilder in this regard for 2.1.x

**Comment by CedricYii** [comment]
@cebe Thanks you for the feedback. So Yii will stay on the good way to keep it simple, light with useful features only, that's a great news!
