### ISSUE TITLE
Bug: ActiveForm need click button twice before it can submit

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#11103]
If submit button use name="submit"

**Comment by samdark** [comment]
You mean active form? How to reproduce that using basic project template?

**Comment by mdmunir** [comment]
In app basic template (fresh install).
`@app/views/site/login.php` change submit button name from "login-button" to "submit" (line 37).

**Comment by pana1990** [comment]
@mdmunir  it is not error, it is convention from JQuery you can read note in [docs](https://github.com/yiisoft/yii2/blob/master/docs/guide/input-forms.md): 

```Be careful when naming form elements such as submit buttons. According to the jQuery documentation there are some reserved names that can cause conflicts:```

**Comment by pana1990** [comment]
duplicated https://github.com/yiisoft/yii2/issues/8993

@mdmunir  Can you please close this issue?
