### ISSUE TITLE
createUrl function is duplicating the route

### ISSUE THREAD

**Issue by vc7deo** [yiisoft/yii2#11105]
I tried to create a dynamic url using below code

  ```
   $route = Yii::$app->controller->route;
   $params = $_GET;
   array_unshift($params, '/'.$route);
```

And created a link like below

`<?= Html::a('link', [Yii::$app->urlManager->createUrl($params)]); ?>`

but link is generating like 

`http://localhost/multi/backend/web/multi/backend/web/site/index`

in the above link **multi/backend/web/**  is repeating ..dont know whats the problem

**Comment by hiscaler** [comment]
Use
```php
<?= Html::a('link', Yii::$app->urlManager->createUrl($params)); ?>
```
