### ISSUE TITLE
set layout in Action Class

### ISSUE THREAD

**Issue by sheillendra** [yiisoft/yii2#11102]
I hope to define a layout can also be done this way
```
public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => 'error-layout'
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
```

**Comment by SilverFire** [comment]
I think it can be done with one of the following approaches:

```php
public function beforeAction($action)
{
    if ($action->id === 'error') {
        $this->layout = 'error-layout';
    }
    parent::beforeAction($action);
}
```

Or create your own `ErrorAction` class, that extends from `yii\web\ErrorAction` and override method `beforeRun()` as follows: 

```php
protected function beforeRun()
{
    return $this->controller->layout = 'error-layout';
}
```

Or add to your error view line

```php
Yii::$app->controller->layout = 'error-layout';
```

But I think we still can add the suggested property to the `ErrorAction` class. @yiisoft/core-developers opinions?

**Comment by klimov-paul** [comment]
> But I think we still can add the suggested property to the ErrorAction class. 

This does not make any sense. The best placefor changing layout will be inside the error view file:

```php
<?php
$this->context->layout = 'error-layout';
?>
...
```
