### ISSUE TITLE
generateRandomKey in freebsd

### ISSUE THREAD

**Issue by quantum13** [yiisoft/yii2#11111]
Hello.

I have Yii 2.0.7 on FreeBSD 10.2-RELEASE
output of diagnostic script from #10519:
```
1  function_exists('random_bytes')
    false

 2  defined('OPENSSL_VERSION_TEXT') ? OPENSSL_VERSION_TEXT : null
    'OpenSSL 1.0.1p-freebsd 9 Jul 2015'

 3  PHP_VERSION_ID
    50618

 4  function_exists('mcrypt_create_iv') ? bin2hex(mcrypt_create_iv(8, MCRYPT_DEV_URANDOM)) : null
    NULL

 5  DIRECTORY_SEPARATOR
    '/'

 6  sprintf('%o', lstat('/dev/urandom')['mode'])
    '120755'

 7  sprintf('%o', lstat('/dev/urandom')['mode'] & 0170000)
    '120000'

 8  bin2hex(file_get_contents('/dev/urandom', false, null, 0, 8))
    '9918d772ab5fd4cb'

 9  ini_get('open_basedir')
    ''
```
I know, that I can install mcrypt, and generateRandomKey will work fine. 

In comment in generateRandomKey in branch with /dev/urandom written `Do not follow symbolic link at '/dev/urandom', as such would be suspicious`. But in my system /dev/urandom is link to /dev/random. I checked freebsd 9.0, /dev/urandom is also link to /dev/random. 

https://en.wikipedia.org/wiki//dev/random#FreeBSD :

> Unlike the Linux /dev/random, the FreeBSD /dev/random device never blocks. Its behavior is similar to the Linux /dev/urandom, and /dev/urandom on FreeBSD is linked to /dev/random.

Maybe for freebsd addtitional checks can be added?

**Comment by SilverFire** [comment]
FreeBSD 9.3:

```
 1  function_exists('random_bytes')
    false

 2  defined('OPENSSL_VERSION_TEXT') ? OPENSSL_VERSION_TEXT : null
    'OpenSSL 1.0.1i 6 Aug 2014'

 3  PHP_VERSION_ID
    50431

 4  function_exists('mcrypt_create_iv') ? bin2hex(mcrypt_create_iv(8, MCRYPT_DEV_URANDOM)) : null
    '32399989674a4be0'

 5  DIRECTORY_SEPARATOR
    '/'

 6  sprintf('%o', lstat('/dev/urandom')['mode'])
    '120755'

 7  sprintf('%o', lstat('/dev/urandom')['mode'] & 0170000)
    '120000'

 8  bin2hex(file_get_contents('/dev/urandom', false, null, 0, 8))
    '7c2d3149d8dffa02'

 9  ini_get('open_basedir')
    ''
```

**Comment by SilverFire** [comment]
@tom-- We need your opinion, please :)

**Comment by tom--** [comment]
Thanks @quantum13 for carefully investigating and reporting this.

I propose we add a branch that tests:

- `DIRECTORY_SEPARATOR` === '/'`, and
- the operating system IS NOT Linux, and
- `/dev/random` is a special character device (as in the current code)

in this case we can read `/dev/random` in the same way that we currently read `/dev/random`. (We had a branch a bit like this in a previous version.) As far as I know, there is no reason to avoid `/dev/random` except on Linux.

If these conditions are true, and we successfully read from `/dev/random`, we can cache this knowledge in the `$_randomSource` property with a new constant `SOURCE_RANDOM`.

I guess this means 2.0.9?

I will not be able to work on this myself until the end of this week. But I will be able to review code if anyone else wants to take the lead.

**Comment by samdark** [comment]
Sounds good. 2.0.8 sounds more like it.
