### ISSUE TITLE
RBAC DbManager getPermissionsByUser cannot get default role permission.

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#11115]
I have set default roles same way using yii2 documentation.
http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-default-roles

When, I try to get all permissions by the method named getPermissionsByUser of DbManager but no results return.

It is possible to get default role permission for specifically user based on user group?

**Comment by samdark** [comment]
No. Default roles aren't within RBAC hierarchy so these aren't available.
