### ISSUE TITLE
An error in user component?

### ISSUE THREAD

**Issue by caijq4ever** [yiisoft/yii2#11112]
英文不太好，下面用中文来描述。:)
我下载的是app-basic项目，在`app\config\web.php`中定义了user组件(component)，如下：
```php
    'components' => [
        ...
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
            'idParam' => 'store_id',
        ],
        ...
```
同时我新建了admin模块(module)，不巧的是在`app\modules\admin\config\web.php`中也定义了user组件，如下:
```php
    'components' => [
        ...
        'user' => [
            'class' => 'app\web\User'
            'identityClass' => 'app\modules\admin\models\Admin',
            'enableAutoLogin' => true,
            'idParam' => 'admin_id',
        ],
        ...
```
---
如上，出现了两个`$idParam`，当我在http://localhost/path/to/project/web/index.php中使用user验证机制登录admin与store时，在session中永远存的都是store_id，而非两个都存。

目前我的解决方案是：在`app\web\User::init`中覆盖```$this->idParam = Yii::$app->controller->componets['user']['idParam']```，还有个疑问，用```$this->idParam = Yii::$app->controller->module->user->idParam```报错。

### Please fix it!:)

**Comment by samdark** [comment]
Is it possible to translate into English?

**Comment by caijq4ever** [comment]
I'm using basic app. This project had a `Modules` it named `admin`. I defined `user` component in `app\config\web.php` and `app\modules\admin\config\web.php`.  And defined `$isParam` in two `user ` components`. As two code previews in the question description. 

I have two questions.
Q1:
An error in `user` component When I'm login and logout. These two actions will invoke `switchIdentify` in `yii\web\User` and setted `$isParam` in session. There was no `admin_id` but `store_id` setted in session. 

 Q2:
Finally I solved question one. The way is redefined `$isParam` in `yii\web\User`. like this:
```php
    public function init()
    {
        parent::init();

        $this->idParam = Yii::$app->controller->module->components['user']['idParam']; //good
        //$this->idParam = Yii::$app->controller->module->user->idParam;  //wrong

        if ($this->identityClass === null) {
            throw new InvalidConfigException('User::identityClass must be set.');
        }
        if ($this->enableAutoLogin && !isset($this->identityCookie['name'])) {
            throw new InvalidConfigException('User::identityCookie must contain the "name" element.');
        }
    }
```
Why `$this->idParam = Yii::$app->controller->module->user->idParam` is wrong?

My English is very poor! :) Do you understand my situation?

**Comment by samdark** [comment]
Overall it looks like you're doing something too unusual which is better to discuss at forums before it could be considered a bug.

**Comment by caijq4ever** [comment]
If the project use two `user` components, Then these two `$idParam` would not be set in session.

**Comment by caijq4ever** [comment]
@qiangxue  这个问题怎么解决？
