### ISSUE TITLE
SluggableBehavior breaks sql query

### ISSUE THREAD

**Issue by drSun** [yiisoft/yii2#11116]
Hi!
I've got a CRUD generated by gii, the last stable yii2, php 5.6, windows, openserver.
If there is a row in db with empty slug column (look here https://yadi.sk/i/QQ1rNBx0qB28R), then in search model after validation you get $this->slug == -2, so after $query->andFilterWhere(['like', 'slug', $this->slug]) you just get broken sql 
```
...[where] => Array
        (
            [0] => like
            [1] => slug
            [2] => -2
        )...
```

In this case I have an empty gridview without any rows.

**Comment by hiscaler** [comment]
You SQL is
```php
SELECT * FROM YOUTABLENAME WHERE slug LIKE '%-2%'
```
Generate sql is right, but not like '-2' slug field in you data rows.
