### ISSUE TITLE
Remeber migrationPath: feature

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#11126]
Накатываем миграцию: 
   php yii migrate/up --migrationPath=@common/modules/blog/migrations
Далее указанный путь  должен запоминаться в БД т.к. при наличии большого количества модулей прописывать для всех migrationPath мучительно.
   php yii migrate/down --migrationPath=@common/modules/blog/migrations
Хочется сделать просто php yii migrate/down или php yii migrate/redo

**Comment by samdark** [comment]
Как насчёт сделать `migrate_blog.sh` и прописать путь там?

**Comment by SilverFire** [comment]
Согласен с @samdark

**Comment by exru** [comment]
А винда?

**Comment by exru** [comment]
@samdark  @SilverFire  А как же тогда сделать php migrate/down 2???
НЕ друзья вы не правы!

**Comment by samdark** [comment]
А винда умеет батники и powershell. И bash и винда умеют принимать параметры. Это может выглядеть, например, так:

`./migrate.sh down 2`

**Comment by SilverFire** [comment]
> А винда?

migrate_blog.bat?

**Comment by samdark** [comment]
Ещё одна причина так не делать — если у нас путей много, запросто можно забыться и выполнить команду не там.

**Comment by exru** [comment]
php migrate/down 2 - выдаст эксепшн

**Comment by exru** [comment]
@samdark дак для этого и нужна фича

**Comment by exru** [comment]
@samdark Так или иначе мы всегда ссылаемся на класс с миграцией, down же отдельно не напишешь.

**Comment by exru** [comment]
@SilverFire migrate_blog.bat - и для всех остальных систем будем плодить батники сашки и.т.д. А вот интегрировать с php не как?
К примеру задача будет организовать откат миграций из админки, что тоже батники писать?

**Comment by exru** [comment]
Всего-то надо добавить поле, это даже на обратную совместимость не повлияет :(

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/issues/9698#issuecomment-147696833

**Comment by samdark** [comment]
Не поле добавлять не будем. А вот как Павел показывает можно сделать в 2.1 вполне.
