### ISSUE TITLE
Class Default does not exist when update attribute in User Active Record

### ISSUE THREAD

**Issue by robert589** [yiisoft/yii2#11128]
I try to update profile_path in User database of mine, then it return class Default does not exist when $user->update executed

> private function updateToUserProfile($total_path){
> 
>         $user = User::findOne(\Yii::$app->user->getId());
>         if($user->photo_path != $total_path){
>             $user->photo_path = $total_path;
>             if($user->update()){
>                 return true;
>             }
>             else{
>                 return false;
>             }
>         }
>         return true;
> 
>     }

**Comment by robert589** [comment]
Hi i think this is a bug, i forgot to add it occurs on the yii2 library

**Comment by samdark** [comment]
There's no "Default" class in Yii.
