### ISSUE TITLE
composer update causes ReflectionException  Class html does not exist

### ISSUE THREAD

**Issue by vimlan** [yiisoft/yii2#11123]
Hi,

After composer update i get the following error in my website. I am using Yii2 basic 
reflection

![reflection](https://cloud.githubusercontent.com/assets/9458596/13775971/f706c8c4-eac0-11e5-9225-c1e4a6bf4ecc.png)

This works on my local server where I have not done the composer update yet.

Does anyone knows what is this issue?

**Comment by SilverFire** [comment]
How to reproduce it?

**Comment by Alex-Code** [comment]
Is this a case-sensitivity issue? In the pic the class name is lowecase.

**Comment by vimlan** [comment]
If you have a basic Yii2 setup update the composer dependencies. Then try to access the url that is not allowed for the non members(login users). You will get the above error. 

e.g logout is allowed only if user is logged in to the system. So if i go to my website and type the url  mywebsite.com/site/logout it gives the above error. 
If I use the url  mywebsite.com/site/login it do not show any error

**Comment by Alex-Code** [comment]
Can you show your controller code?

**Comment by vimlan** [comment]
Below is my controller SiteController.php

<?php
namespace app\controllers;
use Yii;
use yii\filters\AccessControl;
use app\components\Controller;
use yii\filters\VerbFilter; use yii\helpers\Url;

class SiteController extends Controller {
 public $defaultAction = 'login';

public function behaviors()
{
    if (\Yii::$app->user->isGuest) {
        if(in_array($this->action->id ,['logout','sales'])){
            return $this->redirect(Url::to(['site/login']));
        }
    }

    if(!\Yii::$app->session->has('checkinuser')){            
        if(in_array($this->action->id ,['sales'])){
            Yii::$app->base->redirectOnLogin();
        }
    }


}

public function init() {
    $this->layout = "main";
    $this->setMain("login");
    parent::init();
}

public function actions()
{
    return [
        'error' => [
            'class' => 'yii\web\ErrorAction',
        ],
        'captcha' => [
            'class' => 'yii\captcha\CaptchaAction',
            'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
        ],
    ];
}

public function actionLogout()
{
    Yii::$app->user->logout();
    return $this->goHome();
}


public function actionLogin(){  
    $this->setMain("login");
    if (!\Yii::$app->user->isGuest) {
        Yii::$app->base->redirectOnLogin();
    }
    $model = new LoginForm(['scenario' => 'login']);
    if ($model->load(Yii::$app->request->post())) {  
        if ($model->login() && $model->validate()) {
            //on sucess redirect users to page that he has access to or support page                
            Yii::$app->base->redirectOnLogin();
        }else{

            $model->errors;
            foreach($model->errors as $key => $val){
                if($key=="device_id" && $val[0] == "error.notfound"){
                    return  Yii::$app->response->redirect(Url::to(['site/activate']));
                }
            }
           return $html = $this->render('login', ['model' => $model]);
            //return Json::encode($html);
        }
    } else {
        return $html = $this->render('login', ['model' => $model,]);
        //return Json::encode($html);
    }
}

}
public function actionSupport(){
    $this->setMain("support");
    $model = new LoginForm(['scenario' => 'resetpassword']);
    return $this->render('support');
}

public function actionHome(){
    return $this->render('index');

}
}

**Comment by Alex-Code** [comment]
The `behaviors` method should return an array.
What you're trying to do is documented here, http://www.yiiframework.com/doc-2.0/guide-security-authorization.html
