### ISSUE TITLE
Each Validator message formatting

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#11139]
### What steps will reproduce the problem?

```php
public function rules() {
    return [
			['mmm', 'each', 'rule' => [
				'exist', 'targetClass' => zzz::className(), 'targetAttribute' => 'xxx',
				'message' => 'User "{value}" was not found.'
			]],
    ];
}
```
### What is the expected result?
```User xxx was not found```
```User yyy was not found```
### What do you get instead?
```User "array()" was not found.```
### Additional info

| Q                | A
| ---------------- | ---
|   Yii    | 2.0.7-dev
|   Php    | 5.5
| Windows | 7

**Comment by SDKiller** [comment]
@dryu 

https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L361

**Comment by SilverFire** [comment]
@dryu make sure that array of `mmm` contains only strings.

**Comment by dryu** [comment]
@SilverFire It is an array of strings, of course. 

The EachValidator is supposed to let underlying validator to apply the formatting for error messages (unless explicitly configured otherwise) instead of trying to do so on the input array which is always an array and thus common formatting ruled from the parent Validator class do not apply to it. 

-A (mobile)

On Mar 19, 2016, at 11:33 PM, Dmitry Naumenko <notifications@github.com> wrote:

Closed #11139.

**Comment by SilverFire** [comment]
Oh, I understand you now. Thank you for detailed explanation.

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/a0e614eb20a045864fce5187ab513cd2066ebf6d
