### ISSUE TITLE
yii\base\FileHelper should follow symlinks

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#11130]
The Yii2 FileHelper (https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L254) should follow symlinks or ist there any reason it should not follow symlinks?

```php
if (is_link($src)) {
$src = readlink($src);
}
```

something like this should do the trick.

**Comment by samdark** [comment]
How to reproduce ths issue?

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.

**Comment by nadar** [comment]
I am not sure how to setup a test with symlinks to reproduce this issue, but in order to recreate:

1. Create symlink "foo" which is related to folder "storage" which contains some files
2. run `FileHelper::copyDirectory('foo', 'path/to/where/you/want/to/copy/foo');`

As `foo` is a symlink to `storage` it will not "follow" the symlink, which could be fixed with something like:

```php
if (is_link($src)) {
    $src = readlink($src);
}
```

Expected:
copyDirectory should copie a directory even its a symlink.

**Comment by SilverFire** [comment]
I don't think that method must follow symlinks by default, but it makes sense to introduce additional option `followSymlinks` in order to have controlled behavior

**Comment by nadar** [comment]
An additional option to force following symlinks would be a good solution i guess, this way current implementations do not have an unexpected behavior but people who like to enable.

**Comment by SilverFire** [comment]
Exactly :) Would you like to submit a PR?

**Comment by nadar** [comment]
Sure, but first i have to understand how you are runing file tests in phpunit (https://github.com/yiisoft/yii2/blob/master/tests/framework/helpers/FileHelperTest.php#L616).

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/blob/master/.travis.yml#L58

**Comment by AnikanovD** [comment]
Cannot reproduce
