### ISSUE TITLE
CSRF protection error because of small post_max_size

### ISSUE THREAD

**Issue by summerknight** [yiisoft/yii2#11131]
**Example:**
post_max_size = 8M
CSRF protection is enabled, CSRF token is posted as hidden form field

I upload less than 8M on a server. Ok
I upload a bit more than 8M on a server. Error:

> Bad Request (#400)
> Unable to verify your data submission. 

**Solution:**
I increase post_max_size. No error.

Maybe a very rare situation is explained above. Is it a feature? If so maybe it will be good to mention this feature somewhere, ex. in yii2 cookbook. Or maybe I did something wrong.

Thanks!

**Comment by arisk** [comment]
I don't think this is an issue. Your `post_max_size` setting should always be larger than your `upload_max_size` setting anyway. Every other form value you submit will also add to the post size.

**Comment by oz-freeman** [comment]
$_POST and $_FILES variables are empted on a server side if a post_max_size error triggered. Before any scripting starts. With no error or exception. 
So your _csrf variable is gone too and yii throw BadRequestHttpException before you can handle that
