### ISSUE TITLE
HttpCache should be able to generate weak etags

### ISSUE THREAD

**Issue by particleflux** [yiisoft/yii2#11137]
When using `yii\filters\HttpCache` for etag generation, it should be configurable to allow generation of weak etags due to following problem:

1. Yii generates _standard_ etag
2. nginx modifies it to be a _weak_ etag
3. the client sends `If-None-Match` with the weak etag
4. Yii2 compares a weak to a non-weak etag, fails and re-sends response

This happens only when nginx has gzip compression enabled and with nginx >= 1.7 ( http://hg.nginx.org/nginx/rev/e491b26fa5a1 )

I think a configurable option to generate _weak_ etags would be the best solution to that problem.

**Comment by samdark** [comment]
Since you're into it, can you help implementing it?

**Comment by particleflux** [comment]
sure - would have patched/extended that thing on my own anyway until release ;)
