### ISSUE TITLE
FragmentCache doesn't clean view's cacheStack on empty content

### ISSUE THREAD

**Issue by roro15** [yiisoft/yii2#11132]
When nested cache components has empty content parent component doesn't handle dynamic content.
Code from FragmentCache::run():
`            if ($content === false || $content === '') {
                return;
            }
            array_pop($this->getView()->cacheStack);`

so when content is empty array_pop is not called.
Then:
` if (empty($this->getView()->cacheStack) && !empty($this->dynamicPlaceholders)) {
                $content = $this->updateDynamicContent($content, $this->dynamicPlaceholders);
            }`
and `empty($this->getView()->cacheStack)` returns false.
So i get unhandled dynamic placeholders in parent component.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.7
| PHP version      | 5.6.17
| Operating system |

**Comment by roro15** [comment]
Any progress with this issue?

**Comment by kidol** [comment]
This bug was introduced by me, I will look at it soon.
