### ISSUE TITLE
Doc - How to extend base classes

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#11142]
What would be the best way to do things like this?

- Overwrite a method in a core class, extending it.
- Use another core class, expecting it to use your overwritten method.

e.g.
```php
class BaseHtml extends \yii\helpers\BaseHtml {
  function checkbox () {
    //custom version
  }
}
...
$activeField->checkbox() //will use the \yii\helpers\BaseHtml.
```

Thoughts:

- The `Yii::$classMap['yii\helpers\Html'] = 'custom\Html.php'` negates the `extends`.
- Then you need to rename your class and write a `require` above the class declaration (not sure).

This is correct? There's a better way? Didn't found anything about this in the docs.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/helper-overview.md#customizing-helper-classes-
