### ISSUE TITLE
Question: Can themes be stored in ./vendor/{provider}/... ?

### ISSUE THREAD

**Issue by davidjeddy** [yiisoft/yii2#11148]
### What steps will reproduce the problem?
composer install a package that contains a theme, it will be stored wherever composer stores other packages. Editing ./config/web.php -> components['views'] as typical for theme installation.

### What is the expected result?
theme should load assets as expected

### What do you get instead?
Assets are 404 not found

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      |  5.6.x
| Operating system | *nix

Exp:
```
        'view' => [
            'theme' => [
                'pathMap' => [
                    '@app/views' => '@vendor/davidjeddy/yii2-portfolio-theme/themes/orange-strings',
                ],
                'pathMap' => [
                        '@frontend/views' => [
                            '@base/vendor/davidjeddy/yii2-portfolio-theme/themes/orange-strings',
                        ]
                    ],
                'baseUrl' => '@frontendUrl/themes/orange-strings',
            ],
        ],
```

**Comment by cebe** [comment]
how do you load the assets in the theme files?

**Comment by davidjeddy** [comment]
@cebe an example css resource is loaded using the following:
`<link rel='stylesheet' type='text/css' href='<?php echo $this->theme->baseUrl; ?>/files/main_style.css' `

**Comment by cebe** [comment]
if your asset files are not in a web accessible directory, you have to use asset publishing to copy them. i.e. create AssetBundle classes and register them in your views. http://www.yiiframework.com/doc-2.0/guide-structure-assets.html

**Comment by davidjeddy** [comment]
Sorry, still a bit lost here, I understand registering CSS/JS/IMG assets via the RegisterAsset() in the theme's view layout header. Just to clarify I should then register the theme in the applications config array (as above). Can namespaces be used in the pathMap / baseUrl ?

**Comment by cebe** [comment]
`baseUrl` does not make sense here since the theme is not web-accessible anyway.
