### ISSUE TITLE
Unchecked require checkbox don't pass client validation.

### ISSUE THREAD

**Issue by vitalykhy** [yiisoft/yii2#11155]
I have a register form created by **ActiveFrom** with **required checkbox**. On the model I have **['fz152', 'required']** on method rule. If **client validation is enabled** this checkbox doesn't react on the action.
Function **isEmpty** https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.validation.js#L15 detect a hidden input value **0 as a false**. And validation on my case is not work. If add a || **value == 0** that it works fine.

I solved this problem by change the method **isEmpty**. 

Yii version  2.0.6

**Comment by laxity7** [comment]
you do something incorrectly or unclear explanation.
please, give more information

**Comment by vitalykhy** [comment]
Ok, I have a model:
`class LoginForm extends Model
{
    public $email;
    public $password;
    public $password_repeat;
    public $school;
    public $userType;
    public $rememberMe = true;
    public $fz152;

    private $_user;
  
    const SCENARIO_LOGIN = 'login';
    const SCENARIO_REGISTER = 'register';
  
    public function rules()
    {
        return [
            [['email', 'password', 'password_repeat','school','userType', 'fz152'], 'required']
        ];
    }
...
}`
and I have a view:
`...
<?= $form->field($model, 'fz152')->label(false)->checkbox() ?>
...`

If checkbox is not select, client validation is pass, and if checkbox is select, client validation is pass too. And next actions will describe above)

**Comment by SilverFire** [comment]
> <?= $form->field($model, 'fz152')->label(false)->checkbox(['uncheck' => false]) ?>

**Comment by laxity7** [comment]
Yes, it's "bug".
I use something like it =)
```['fz152', 'boolean', 'trueValue'  => 1, 'falseValue' => 1, 'message' => 'Input required'],```

**Comment by laxity7** [comment]
oh, yes, it's "bug"
I use something like it =)
`['fz152', 'boolean', 'trueValue'  => 1,'falseValue' => 1, 'message' => 'Input required'],`

**Comment by SilverFire** [comment]
@laxity7 I can't agree with you, it is not a bug

**Comment by laxity7** [comment]
@SilverFire,  yes and no. You expect that it will be required, but it turns out not mandatory for the user. It misleads, but not a real bug

**Comment by wolverineo250kr** [comment]
looks like it doesnt work for ajax validation
