### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/yii-application/frontend/web/v1/site/login

### ISSUE THREAD

**Issue by bschauhan** [yiisoft/yii2#11151]
### What steps will reproduce the problem?
1) I have create yii2 rest + angular application
2) I have to create one login method in yii and angular
3) than submit login form with angular post ajax
4) show error "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/yii-application/frontend/web/v1/site/login. (Reason: CORS header 'Access-Control-Allow-Origin' missing)."

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      | 5.6.19
| Operating system | ubuntu 14

**Comment by cebe** [comment]
> Reason: CORS header 'Access-Control-Allow-Origin' missing

If you are doing cross origin requests, you have to setup CORS behavior in your controler. See documentation on how to do this: http://www.yiiframework.com/doc-2.0/yii-filters-cors.html

**Comment by bschauhan** [comment]
@cebe: I have already used  "Cors" behaviors in over controller.

**Comment by tunecino** [comment]
@bschauhan can you share code ? how does your `behaviors()` method look like ? did you implement authentication ? if yes, does it work when authentication is disabled ?

**Comment by awebc** [comment]
me too .
angularjs http post application/json . not support
when i set content type :www url encode  . it is ok
