### ISSUE TITLE
Unsafe attribute with custom validator which every time executes

### ISSUE THREAD

**Issue by conick** [yiisoft/yii2#11153]
Is there is a simply way to use unsafe attribute in default scenario with custom validator which executes every time?

```
public function rules()
{
	return [
		['photo', CmFileValidator::className(), 'skipOnEmpty' => false],
		....
	];
}
```
Attribute "photo" sets by own logic in behaviour and it should has correct value from DB.
With rules above after `$model->load()` attribute "photo" sets as null.
If I add "!" before attribute in rules - validator doesnt runs. 

I find only this way for unsafe attribute using with validator's running:
```
public function scenarios()
{
	$scenarios = parent::scenarios();
	$photoKey = array_search('photo', $scenarios['default']);
	$scenarios['default'][$photoKey] = '!photo';
	return $scenarios;
}
```

Is this the only solution?

**Comment by mdmunir** [comment]
:+1: 
https://github.com/yiisoft/yii2/pull/10234

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/da82ff3fb1625597706d9da3c76ca5a0a1ee7ad5
