### ISSUE TITLE
why memcache store session is not work?

### ISSUE THREAD

**Issue by crazyfd** [yiisoft/yii2#11156]
### What steps will reproduce the problem?
```php
<?php
$config = [
    'components' => [
        'request' => [
            'cookieValidationKey' => '5eOHMbIsNLmoIjvzaJsfRkXMuzJ1xaD9',
        ],
        'memCache' => [
            'class' => 'yii\caching\MemCache',
            'servers' => [
                [
                    'host' => '192.168.0.54',
                    'port' => 11211,
                    'weight' => 60,
                ],
            ],
        ],
        'session' => [
            'class' => 'yii\web\CacheSession',
            'cache' => 'memCache',
        ],
    ],
];
```

Yii::$app->session->set('test','hello');
when i reload page ,Yii::$app->session->get('test') is null,so what is wrong?

### Additional info
![6c020157-9be2-4c0b-af39-a4157942ad2d](https://cloud.githubusercontent.com/assets/5456580/13912904/ac0e44d0-ef7c-11e5-9d22-69596565bf7a.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6.10
| Operating system | mac 10.11

**Comment by SilverFire** [comment]
Do you have corresponding session data in Mongo collection?

**Comment by crazyfd** [comment]
@SilverFire ，i don't save session data in Mongo collection，but i used memcache.
```php
public function actionTest()
{
        Yii::$app->session->set('testyii','yii ok');
        //echo Yii::$app->session->get('xiaoyongb')."<br/>";   // reload page,session can't keep,
        $host='192.168.0.54';
        $port=11211;
        $mem=new \Memcache();
        $mem->connect($host,$port);
        $mem->set('test2','test2 ok');
        //echo $mem->get('test2');    // reload page,this is ok
}
```

**Comment by klimov-paul** [comment]
Does the regular session works fine for you?

**Comment by crazyfd** [comment]
@klimov-paul ，yes,use file is ok

**Comment by klimov-paul** [comment]
Does MemCache works fine as a data storage? Are you able to perform `set` and `get` on your `memCache` component?

**Comment by crazyfd** [comment]
@klimov-paul ，yes，i use memCache component is work
```php
 Yii::$app->memCache->set('testyii','yii ok');
//echo Yii::$app->memCache->get('testyii');
```
this is ok.

**Comment by SilverFire** [comment]
Is the problem still unsolved?

**Comment by klimov-paul** [comment]
I am unable to reproduce the problem.

Reveiwing provided config I see that MemCache is configured in the wrong way:

```php
'memCache' => [
            'class' => 'yii\caching\MemCache',
            'servers' => [
                [
                    'host' => '192.168.0.54',
                    'port' => 11211,
                    'weight' => 60, // ONLY ONE SERVER WITH WEIGHT 60%
                ],
            ],
        ],
```

It specifies single server with wieght 60%, which means for the 40% cases it has no place to go.
Perhaps this is the cause.

**Comment by crazyfd** [comment]
thinks,@klimov-paul , @SilverFire , i remove weight attribute or set weight 100,it's work.
