### ISSUE TITLE
404 ошибка при реализации REST API в качестве модуля

### ISSUE THREAD

**Issue by matiosfree** [yiisoft/yii2#11167]
Создаю REST API в качестве модуля **v1** следующим образом:
1. Создаю контроллер frontend\modules\v1\controllers\UserController;
2. Задаю модель: `public $modelClass = 'common\models\db\User';`
3. Задаю конфигурацию:
`
'urlManager' => [
    'enablePrettyUrl' => true,
    'enableStrictParsing' => true,
    'showScriptName' => false,
    'rules' => [
        'class' => 'yii\rest\UrlRule',
        'controller' => frontend\modules\v1\controllers\UserController::class, //пробовал так же v1/user
    ],
],
`

Выдает 404 ошибку при переходе на 
site.com/v1/user   
site.com/v1/user/1  
и т.д. 

Если флаг **enableStrictParsing** установить в **false**, то
site.com/v1/user   - открывается корректно
site.com/v1/user/1  и др. выдает 404 ошибку

Частично с проблему решает данный способ: http://www.yiiframework.ru/forum/viewtopic.php?f=30&t=31639#p176988, но он не совсем удачный и красивый

### Доп. инфо

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6.12
| Operating system | Windows 7 (OpenServer)

**Comment by michaelantipenko** [comment]
Так вроде и должна быть 404. Url должны быть site.com/v1/user**s** и site.com/v1/user**s**/1. Либо в конфигурации:
`['class' => 'yii\rest\UrlRule', 'pluralize' => false]`

**Comment by matiosfree** [comment]
**pluralize**  так же проверял. Никакого эффекта это не дало (для модуля)

**Comment by michaelantipenko** [comment]
@matiosfree верните `'controller' => 'v1/user'`, так `frontend\modules\v1\controllers\UserController::class`, судя по исходникам работать не должно как вы хотите. У меня на проекте UrlRule прекрасно себя чувствует в виде модуля.

**Comment by matiosfree** [comment]
Проверил на этот раз с 
**'controller' => 'v1/user'** и **'pluralize' => false**
Теперь работает. Хотя раньше проверял и не работало... магия однако

**Comment by SilverFire** [comment]
Закрываю
