### ISSUE TITLE
Logout btn is not in line with the rest of the menu

### ISSUE THREAD

**Issue by Morpheus-ro** [yiisoft/yii2#11161]
When I installed Yii2 with composer"

composer create-project yiisoft/yii2-app-basic basic 2.0.7

and I'm viewing the page
http://localhost/web/site/login and enter admin/admin
the next page, the redirected page (home), has the logout not in line with the others links from the menu.

| Q                | A
| ---------------- | ---
| Yii version | 2.0.7
| PHP version | 5.5.9
| Operating system | Ubuntu 14.04

**Comment by SilverFire** [comment]
Moved to yii2-app-basic repo. Thank you
