### ISSUE TITLE
Add export of validation options without the js string

### ISSUE THREAD

**Issue by laxity7** [yiisoft/yii2#11163]
For example, now the clientValidateAttribute function  in  yii\validators\SomeValidator returns a string

``` php
public function clientValidateAttribute($model, $attribute, $view)
{
    $options = [
        'trueValue' => $this->trueValue,
        'falseValue' => $this->falseValue,
        'message' => Yii::$app->getI18n()->format($this->message, [
        'attribute' => $model->getAttributeLabel($attribute),
        'true' => $this->trueValue,
        'false' => $this->falseValue,
        ], Yii::$app->language),
    ];
    ///...
    ValidationAsset::register($view);

    return 'yii.validation.boolean(value, messages, ' . json_encode($options, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ');';
}
```

This function can't be used without yii.validation.
Please, add new function or change this that it returned an array, like this

``` php
public function clientValidateAttribute($model, $attribute, $view)
 {
    $options = [
        'trueValue' => $this->trueValue,
        'falseValue' => $this->falseValue,
        'message' => Yii::$app->getI18n()->format($this->message, [
        'attribute' => $model->getAttributeLabel($attribute),
        'true' => $this->trueValue,
        'false' => $this->falseValue,
        ], Yii::$app->language),
    ];

    ///...

    return $options;
}
```

It is possible to make it so, for example

``` php
public function clientValidateOptions($model, $attribute)
{
    $options = [
        'trueValue' => $this->trueValue,
        'falseValue' => $this->falseValue,
        'message' => Yii::$app->getI18n()->format($this->message, [
        'attribute' => $model->getAttributeLabel($attribute),
        'true' => $this->trueValue,
        'false' => $this->falseValue,
        ], Yii::$app->language),
    ];
    // ... other setting options
    return $options;
}

public function clientValidateAttribute($model, $attribute, $view)
{
    $options = $this->clientValidateOptions($model, $attribute)
    ///...
    ValidationAsset::register($view);

    return 'yii.validation.boolean(value, messages, ' . json_encode($options, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ');';
}
```

**Comment by Alex-Code** [comment]
Can you give a use case?

**Comment by laxity7** [comment]
@Alex-Code, we use own validation and export validation of rules from a backend model to a frontend.
Now it is necessary to use crutches (copy-paste of formation of options from all classes of validation in ours a big class). It looks terribly

**Comment by SilverFire** [comment]
The idea is good, as for me.

Let's wait for additional opinions form @yiisoft/core-developers team

**Comment by samdark** [comment]
Good to me as well. For 2.1 I was thinking about writing these options to data-attributes of the fields so it would be handy start.

**Comment by Faryshta** [comment]
@samdark how do you plan to have several validations using data-attributes?

**Comment by SilverFire** [comment]
@laxity7, would you like to create a PR?

**Comment by samdark** [comment]
@Faryshta something like:

```
data-validate-validatorName="{key: value, key: value}"
```

**Comment by laxity7** [comment]
@SilverFire, yes, I can do it next week.
@samdark, I think it will be better so:
`data-validate-rule="number" data-validate-options="{max: 20, min: 0}"`
Thus it isn't convenient to transfer error messages, because may be too long data-attribute

**Comment by Alex-Code** [comment]
@laxity7 According to a discussion here there isn't a limit on the length a data attribute can have.
http://stackoverflow.com/questions/1496096/is-there-a-limit-to-the-length-of-html-attributes

**Comment by SilverFire** [comment]
> I think it will be better so:

No, it's not better because you can have multiple rules for the same attribut

**Comment by Faryshta** [comment]
I agree with @SilverFire I think the data-attribute idea is far from clear and usable. And even if you make a data attribute for each rule name, that doesn't allow you to have custom rules outside yii2, some keys are not easy to implement as json such as `when` which is a callable method in js.

And something like

```
public function rules()
{
    return [
        // check passwords match
        ['password', 'compare', 'targetAttribute' => 'passwordConfirm']
        // check the password is not the same as username
        ['password', 'compare', 'operator' => '!=', 'targetAttribute' => 'username'],
        // check the password is not the same as birthday
        ['password', 'compare', 'operator' => '!=', 'targetAttribute' => 'birth_date'],
    ];
}
```

Will rewrite the same validator over and over.

**Comment by laxity7** [comment]
@SilverFire, you are right, I didn't think about it.
Then I'm not sure that will conveniently use data-attributes, especially as in the example above

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/pull/13014#issuecomment-264972828

**Comment by cebe** [comment]
> Why is getClientOptions() protected?
> 
> It should be public so that a custom implementation of ActiveField can bypass clientValidateAttribute completely. That was the point of #11163.

With the current implementation one can extend the Validator client validation without re-implementing all options related logic. However every validator must be extended to have a custom JS validation implementation, which does not seem good to me. So I am also for making the options method public.

**Comment by nkovacs** [comment]
> With the current implementation one can extend the Validator client validation without re-implementing all options related logic. 

That's a good point, but you're still very limited in what you can do in `clientValidateAttribute` because of the way `ActiveField` uses it.

The two use cases I see for `getClientOptions` are:
1. Generating a json that describes the model's validation rules. This would be useful for a REST api, since you wouldn't need to define the same rules again in the frontend code, it can just retrieve the rules from the api.
2. Replacing `ActiveField` and yii.validate.js with a different implementation, e.g. one that uses data attributes.

`clientValidateAttribute` is very tightly coupled to `ActiveField` and `yii.validation.js`. For 2.1, I'd suggest removing it, and instead having a mapping of validator class names to client validation functions in `ActiveField` (custom solutions would have to use their own mapping). But that should be a separate discussion.

**Comment by SilverFire** [comment]
Good point. I don't mind to make it public

**Comment by dynasource** [comment]
> Why is getClientOptions() protected?

very simple. Looked at the contents of this PR, the necessity of a public interface is not obvious. On the contrary, your example about externally modifying the options does provide ground for making it public.

**Comment by nkovacs** [comment]
I've opened a PR, but I ran into a minor problem with backwards compatibility: #13145 
To be completely backwards compatible, the method would have to be named something else, and it would have to call the existing protected `getClientOptions` method in `ImageValidator`.
