### ISSUE TITLE
Submit button with propperty 'name'=>'submit' has issue

### ISSUE THREAD

**Issue by asbator** [yiisoft/yii2#11160]
### What steps will reproduce the problem?
Inside _form.php
Html::submitButton(... , ... , ['name'=>'submit']);

### What is the expected result?
Form is submitted at once

### What do you get instead?
It is submitted after second click on it.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 207
| PHP version      |  701
| Operating system | Win 7 XAMPP

**Comment by Alex-Code** [comment]
Same as https://github.com/yiisoft/yii2/issues/11103
You can't give your `submit` button the name "submit".

**Comment by pana1990** [comment]
Duplicated https://github.com/yiisoft/yii2/issues/8993

**Comment by pana1990** [comment]
read https://github.com/yiisoft/yii2/blob/master/docs/guide/input-forms.md

> Forms and their child elements should not use input names or ids that conflict with properties of a form, such as submit, length, or method. Name conflicts can cause confusing failures. For a complete list of rules and to check your markup for these problems, see DOMLint.

**Comment by SilverFire** [comment]
Thank you @Alex-Code @pana1990
