### ISSUE TITLE
Duplicated code: active radio & checkbox

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#11168]
The [activeRadio()](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1410) has the same code as [activeCheckbox()](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1459). Shouldn't it be in a common function?

** radio() and checkbox() too.

**Comment by samdark** [comment]
Probably. Want trying a fix?

**Comment by cesarnicola** [comment]
Hi! This is my first contribution, please let me know if you have comments.
Thanks
