### ISSUE TITLE
Cache Component Enhancement, shortcut to retrieve cache data

### ISSUE THREAD

**Issue by ryusoft** [yiisoft/yii2#11172]
##### Suggestion to add shortcut function "retrieve" to "\yii\caching\Cache" Component as below:
```php
/**
  * Retrieve data from cache or generate the content if cache not found or expired
  * a short cut for get and set the value from cache
  *
  * @param mixed $key a key identifying the value to be cached. This can be a simple string or
  * a complex data structure consisting of factors representing the key.
  * @param mixed $callback the callback function that return data to be cache
  * @param integer $duration the number of seconds in which the cached value will expire. 0 means never expire.
  * @param \yii\caching\Dependency $dependency dependency of the cached item. If the dependency changes,
  * the corresponding value in the cache will be invalidated when it is fetched via [[get()]].
  * This parameter is ignored if [[serializer]] is false.
  * @return mixed the data cached
  */
public function retrieve($key, $callback, $duration = 0, $dependency = null)
{
     if (($data = $this->get($key)) === false) {
         $data = call_user_func($callback);
         $this->set($key, $data, $duration, $dependency);
     }
     return $data;
}
```

So instead of every time when trying to retrieve data from cache e.g.
```php
$key = 'data-cache-key';
$duration = 3600;
$dependency = null;//or some cache dependency

if (($data = Yii::$app->cache->get($key)) === false) {
    $data = [
        ['name'=>'RYU', 'Ranking': 9],
    ];//heavy computation db query or calculation to generate this data
    Yii::$app->cache->set($key, $data, $duration, $dependency);
}

//continue using $data to do something else
```

We could write the code as below:
```php
$key = 'data-cache-key';
$duration = 3600;
$dependency = null;//or some cache dependency

$data = Yii::$app->cache->retrieve($key, function() {
    return [
        ['name'=>'RYU', 'Ranking': 9],
    ];//heavy computation db query or calculation to generate this data
}, $duration, $dependency);

//continue using $data to do something else
```

**Comment by SilverFire** [comment]
No way :laughing: I discussed this idea with @samdark in PM month ago and planned to implement it soon :)

Currently I have a project-scope implementation, that works for me ([code](https://github.com/hiqdev/hipanel-core/blob/master/src/base/Cache.php)) but it can not be accepted in core because it is not flexible enough. This thing is trickier than it appears.

The following use cases must be covered:

1. Static key, closure depends on some variables:
```php
$cache->retrieve(['foobarcache', $images, $user_id], 3600, function () use ($images, $user_id) {
      return Foo::apiCall('getBar', [$images, $user_id]);
});
  ```

**Comment by cebe** [comment]
does this add any additional value except introducing a different way to do the same thing?

**Comment by samdark** [comment]
No.

**Comment by cebe** [comment]
why do we need it then?

**Comment by SilverFire** [comment]
To have a simple way to do this thing without copy-pasting with simple and clear API

**Comment by cebe** [comment]
> without copy-pasting

what do you mean with that?

**Comment by SilverFire** [comment]
Take a look at the first post in this issue and compare 2nd and 3rd blocks of code.
I've posted example in the PR: https://github.com/yiisoft/yii2/pull/11173#issuecomment-200236312

**Comment by cebe** [comment]
case 1 (current way) is obvious about which code is executed in which case.
case 2 needs a lookup in the docs to understand it completely (assuming I see this code written by someone else)

**Comment by Alex-Code** [comment]
I think the name doesn't make it clear as to what it does.
Maybe `getWithSet`?

**Comment by CedricYii** [comment]
This method offers very little enhancement while it is confusing and making the learning curve a little more tedious. I would not expect it to be maintained in the core framework.

**Comment by cebe** [comment]
I do not see good reasons to add this. thanks for the suggestion though.
