### ISSUE TITLE
Yii serve do nothing when I try to run it.

### ISSUE THREAD

**Issue by nikita-ushakov** [yiisoft/yii2#11184]
### What steps will reproduce the problem?

I was trying to get started with Yii2 framework. As described in [documentation][1] i did 

    $composer global require "fxp/composer-asset-plugin:~1.1.1"
    $composer create-project --prefer-dist yiisoft/yii2-app-basic yii2-test

then I `cd yii2-test` and run `php yii serve --port=8888`

### What is the expected result?

That it would run server

### What do you get instead?

Server exit with code 255. Debugger said that it stops [on the line][2] 

    $fp = @fsockopen($hostname, $port, $errno, $errstr, 3);

and error message is 

    fsockopen(): unable to connect to localhost:8888 (Connection refused)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | PHP 5.6.19-1+deb.sury.org~wily+1 (and also PHP 5.6.11-1ubuntu3.1)
| Operating system | Ubuntu 15.10

  [1]: http://www.yiiframework.com/doc-2.0/guide-start-installation.html
  [2]: https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/ServeController.php#L116

**Comment by samdark** [comment]
Probably the port is occupied or the firewall is prevening using it. It's not Yii issue but OS configuration one.

**Comment by nikita-ushakov** [comment]
I just want to share it.

This strange behaviour was caused by xdebug setting

    xdebug.halt_level=E_NOTICE|E_WARNING|E_USER_WARNING|E_USER_NOTICE

To solve my problem I had to just exclude `E_WARNING` from it.

Some explanations:

Before starting `yii serve` command checks if another application uses selected port.
This is done in method `isAddressTaken` by trying to open socket to localhost at this port

    $fp = @fsockopen($hostname, $port, $errno, $errstr, 3);

, so every time the port is empty (and yii may use it), fsockopen generates warning which is suppressed by `@`.

The result: if you have xdebug and it makes all scripts to halt on warnings - `yii serve` will not start.

A little piece of code that I tested manually (and which may help somebody not to dive in debugging from the first step)

```
    if (extension_loaded('Xdebug')) {
        $xdebugHaltLevel = ini_get('xdebug.halt_level');
        if ($xdebugHaltLevel & E_WARNING) {
            ini_set('xdebug.halt_level', ($xdebugHaltLevel ^ E_WARNING));
        }
    }
```
Or something like this. How do you think, is it appropriate workaround?

Sorry that I write to closed issue

**Comment by cebe** [comment]
> if you have xdebug and it makes all scripts to halt on warnings

this is not a good idea when working with yii as it breaks PHP behavior. Yii errorhandler will convert all non-suppressed warnings into exceptions anyway so this settings is quite useless for yii development and should be avoided. I do not think there is a need to change anything in the framework here.
