### ISSUE TITLE
DIRECTORY IS NOT WRITABLE BY WEB PROCESS !

### ISSUE THREAD

**Issue by osnwach** [yiisoft/yii2#11186]
I created an app with Yii2 Advanced template.
I have hosted it on a SHARED HOSTING SERVER.

It has been working fine, but recently it is down. it keeps displaying an error:
Invalid Configuration – yii\base\InvalidConfigException

'The directory is not writable by the Web process: /home/nicjccom/public_html/assets'

My webhost have been trying to fix it, no luck yet!

What could be causing this issue ?

What do I ask my WebHost to do, in order to fix it ?  

Thanks for giving us Yii2.

**Comment by SilverFire** [comment]
`chmod 777 /home/nicjccom/public_html/assets` should fix the problem

**Comment by UmamaheshMaxwell** [comment]
> `chmod 777 /home/nicjccom/public_html/assets` should fix the problem
> 
> Please, check out our [installation guide](http://www.yiiframework.com/doc-2.0/guide-start-installation.html) in order to complete your setup correctly

This fixed my problem :) , thank you !!!
