### ISSUE TITLE
Migrations' db setting not respected.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11182]
### What steps will reproduce the problem?
1. Set a db on the migration controller `test1`.
2. Create a migration, set its public `$db` variable to `test2`.
3. Execute the migration.

### What is the expected result?
The migration should be run on `test2` database.

### What do you get instead?
The migration is executed on `test1` instead.

### Additional info
Exempt from: `yii\console\controller\MigrateController` line 124:
````
        return new $class(['db' => $this->db]);
````
MigrateController always overrides the `db` setting for migrations it creates.

### Possible solution
Let the migration resolve the database itself (code is already there), by not passing it from the migrate controller to the migration.

This does not break BC for cases where the name of the database component is `db`.

**Comment by cebe** [comment]
That is documented behavior: http://www.yiiframework.com/doc-2.0/yii-db-migration.html#$db-detail

> Note that when a Migration object is created by the `migrate` command, this property will be overwritten
> by the command. If you do not want to use the DB connection provided by the command, you may override
>  the [[init()]] method like the following:
> 
>  ```php
public function init()
{
    $this->db = 'db2';
    parent::init();
}
```
