### ISSUE TITLE
Migrate down bug

### ISSUE THREAD

**Issue by matiosfree** [yiisoft/yii2#11199]
Создаю несколько миграций, в каждой выполняется команда на создание таблицы в БД (MySQL)
В методе **down()** содержится код для удаления таблицы:

`$this->dropTable('{{%my_second_table}}');`

1. Запускаю команду **php yii migrate/up** - все ок, новые таблицы появляются в БД, в таблицу **yii_migration** записываются номера ревизий.
2. Сразу же откатываю одну ревизию: **php yii migrate/down**  - таблица из БД удаляется, а запись с номером ревизии из  **yii_migration** почему-то не удаляется.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6.12
| Operating system | Windows 7 (OpenServer)

**Comment by SilverFire** [comment]
Вопрос решили?

**Comment by matiosfree** [comment]
Да, прошу прощения за ложную тревогу. Путем отладки оказалось, что в одной из миграций метод **down()**  возвращал **false** поэтому таблица дропалась, а ее ревизия из  **yii_migration** не удалялась. Так что всему виной моя невнимательность)
