### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#11194]
\composer.json

	{
		"name": "yiisoft/yii2-app-basic",
		"description": "Yii 2 Basic Project Template",
		"keywords": [
			"yii2",
			"framework",
			"basic",
			"project template"
		],
		"homepage": "http://www.yiiframework.com/",
		"type": "project",
		"license": "BSD-3-Clause",
		"support": {
			"issues": "https://github.com/yiisoft/yii2/issues?state=open",
			"forum": "http://www.yiiframework.com/forum/",
			"wiki": "http://www.yiiframework.com/wiki/",
			"irc": "irc://irc.freenode.net/yii",
			"source": "https://github.com/yiisoft/yii2"
		},
		"minimum-stability": "stable",
		"require": {
			"php": ">=5.4.0",
			"yiisoft/yii2": ">=2.0.5",
			"yiisoft/yii2-bootstrap": "*",
			"yiisoft/yii2-swiftmailer": "*",
			"amnah/yii2-user": "^5.0",
			"voskobovich/yii2-many-many-behavior": "^3.0",
			"2amigos/yii2-date-picker-widget": "~1.0",
			"intervention/image": "^2.3",
			"codeception/codeception": "*",
			"codeception/specify": "*",
			"wbraganca/yii2-videojs-widget": "~1.0",
			"bower-asset/punycode": "1.3.*",
			"bower-asset/jquery.inputmask": "3.1.*",
			"bower-asset/punycode": "1.3.*"
		},
		"require-dev": {
			"yiisoft/yii2-codeception": "^2.0",
			"yiisoft/yii2-debug": "*",
			"yiisoft/yii2-gii": "*",
			"yiisoft/yii2-faker": "*"
		},
		"config": {
			"process-timeout": 1800
		},
		"scripts": {
			"post-create-project-cmd": [
				"yii\\composer\\Installer::postCreateProject"
			]
		},
		"extra": {
			"yii\\composer\\Installer::postCreateProject": {
				"setPermission": [
					{
						"runtime": "0777",
						"web/assets": "0777",
						"web/uploads": "0777",
						"yii": "0755"
					}
				],
				"generateCookieValidationKey": [
					"config/web.php"
				]
			},
			"asset-installer-paths": {
				"npm-asset-library": "vendor/npm",
				"bower-asset-library": "vendor/bower"
			}
		}
	}

///////////////////

	 composer update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
		- yiisoft/yii2 2.0.7 requires bower-asset/punycode 1.3.* -> no matching package found
		- yiisoft/yii2 2.0.6 requires bower-asset/jquery.inputmask 3.1.* -> no matching packa
		- yiisoft/yii2 2.0.5 requires bower-asset/jquery.inputmask 3.1.* -> no matching packa
		- yiisoft/yii2 dev-master requires bower-asset/punycode 1.3.* -> no matching package
		- yiisoft/yii2 2.0.x-dev requires bower-asset/punycode 1.3.* -> no matching package f
		- Installation request for yiisoft/yii2 >=2.0.5 -> satisfiable by yiisoft/yii2[2.0.5,
	-master].

	Potential causes:
	 - A typo in the package name
	 - The package is not available in a stable-enough version according to your minimum-stab
	   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

	Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problem

**Comment by SilverFire** [comment]
```bash
composer global require "fxp/composer-asset-plugin:~1.1.1"
composer update
```

**Comment by hassansheikh** [comment]
Thanks! Its work :)

**Comment by phping1** [comment]
ths!@SilverFire

**Comment by bettermentit** [comment]
Thanks! @SilverFire, its working.....
Great job!

**Comment by edwinover** [comment]
Thanks @SilverFire !
