### ISSUE TITLE
Add append() option to ColumnSchemaBuilder

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11195]
Currently appending anything to a column type in a migration must be done when you're done working with the object:
````
$type = $this->string(15)->notNull() . ' collate ascii_bin';
````

It would be great to have a more uniform syntax:
````
$type = $this->string(15)->notNull()->add('collate ascii_bin')->add('character set ascii')
````

That way I can pass the object around as well, for example my migration might have a function `stringId()` that represents an ascii string key, but in some uses i might want to add `notNull()` and in others I don't...

**Comment by df2** [comment]
I think it is best with only one call: `->append('collate ascii_bin character set ascii')`

Some name choices:
- `add()`
- `append()`
- `custom()`
- `extra()`
- `bespoke()`

**Comment by samdark** [comment]
How about `and()`?

**Comment by SamMousa** [comment]
Add sounds good.

**Comment by df2** [comment]
```
$type = $this->char(15)->unique()->custom('collate ascii_bin character set ascii');
```

**Comment by df2** [comment]
```
$type = $this->char(15)->unique()->add('collate ascii_bin character set ascii');

**Comment by samdark** [comment]
```php
$type = $this->char(15)->unique()->and('collate ascii_bin character set ascii');
```

**Comment by df2** [comment]
`and` is not available below PHP 7. `with`, `attach`, `also` ?

**Comment by SamMousa** [comment]
Let me know when you make a final decision and I'll implement it.

**Comment by df2** [comment]
See #11198. It's `plus()` at the moment. Will require tests being written too.

**Comment by SamMousa** [comment]
AH  you already created a PR :) all I have to do is sit back and relax ;)

I'm confused about how php version is relevant.. Can you explain?

**Comment by SamMousa** [comment]
Ah it's probably a reserved word :)

**Comment by tunecino** [comment]
`include()` or `involve()` ?

**Comment by michaelarnauts** [comment]
Any chance this will be included in the next version?

**Comment by samdark** [comment]
@michaelarnauts yes but we need to agree on method name. Implementation is already here https://github.com/yiisoft/yii2/pull/11198/files thanks to @df2.

**Comment by SamMousa** [comment]
@samdark I think you (yii core team) should just decide, there is no real discussion here; just suggestions and preferences.
Only 1 valid argument against using `and`, which is PHP < 7 compatibility.

**Comment by rob006** [comment]
:+1:  for `append()`

`add()` can be considered as an arithmetic operation, and `and()` as a logical operation. `append()` looks more clearly in this case.

**Comment by samdark** [comment]
Agree with @rob006. Let it be `append()`.

**Comment by mikehaertl** [comment]
@samdark Sorry, I'm late to the party :). But maybe reconsider `append()`. Looking at `Migration::createTable()` where we have a similar feature, the argument is called `$options`:

http://www.yiiframework.com/doc-2.0/yii-db-migration.html#createTable()-detail

 So wouldn't `options()` be more consistent?

**Comment by samdark** [comment]
`$options` is OK as argument but I don't think it's OK as method name which appends a single fragment.

**Comment by mikehaertl** [comment]
Hmm, can't really see the difference. But I'm also fine with `append()`. Just wanted to point to the similarity.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/27866bf9d6bd27b52eae97bf33dba2228058ac88
