### ISSUE TITLE
Namespace case-sensivity

### ISSUE THREAD

**Issue by yujin1st** [yiisoft/yii2#11201]
When you create new model with crud, PhpStorm shows error "namespace reference is not case-censitive" on "use Yii;" string

![2016-03-26 12 11 50](https://cloud.githubusercontent.com/assets/2317913/14057992/185b0bbe-f34c-11e5-9ee6-85b26f4aba2e.png) 
![2016-03-26 12 14 32](https://cloud.githubusercontent.com/assets/2317913/14058016/e4680770-f34c-11e5-91e4-31509edfa085.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version   | 7.0.0
| Operating system | mac os 10.11.3, 
| IDE | PhpStorm 2016.1

**Comment by Faryshta** [comment]
i think thats a phpstorm issue. what happens when you click on the 'more' link?

**Comment by samdark** [comment]
Yes. That is PhpStorm issue.

**Comment by Alex-Bond** [comment]
Question - why we need it by default?

**Comment by samdark** [comment]
https://youtrack.jetbrains.com/issue/WI-31242

**Comment by samdark** [comment]
Here it is, reported.

**Comment by yujin1st** [comment]
Thank you =)
