### ISSUE TITLE
PHP 7, Yii 2.0.8 namespace missing

### ISSUE THREAD

**Issue by mpostman** [yiisoft/yii2#11205]
### What steps will reproduce the problem?
common/config/bootstrap.php
```
<?php
Yii::setAlias('@common', dirname(__DIR__));
Yii::setAlias('@frontend', dirname(dirname(__DIR__)) . '/frontend');
Yii::setAlias('@backend', dirname(dirname(__DIR__)) . '/backend');
Yii::setAlias('@console', dirname(dirname(__DIR__)) . '/console');
```
backend/views/layouts/main.php
```
use backend\components\HeaderWidget; 
<?= HeaderWidget::widget() ?>
```

backend/components/HeaderWidget.php
```
<?
namespace backend\components;

use yii\base\Widget;
use yii\helpers\Html;

class HeaderWidget extends Widget
{
    private $logged=false;
    public function init()
    {
        parent::init();
        if (!\Yii::$app->user->isGuest) {
            $this->logged =true;
        }
    }

    public function run()
    {
        if($this->logged)
            return $this->render('header');
        else
            return Html::encode('');
    }
}
```
### What do you get instead?
> Unknown Class – yii\base\UnknownClassException
> Unable to find 'backend\components\HeaderWidget' in file: /var/www/yii/backend/components/HeaderWidget.php. Namespace missing?

### Additional info
Already update composer
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7
| Operating system | Centos

**Comment by Faryshta** [comment]
try to change the first like to `<?php` maybe the configuration of php doesn't allow short tags on your computer

**Comment by mpostman** [comment]
Why closed?

> try to change the first like to <?php maybe the configuration of php doesn't allow short tags on your computer

not helped!

**Comment by Faryshta** [comment]
Did you changed the  first line? do you have the same issue with other files?

**Comment by klimov-paul** [comment]
Closed unless more information provided.
