### ISSUE TITLE
there's no way to limit results in a hasMany relation

### ISSUE THREAD

**Issue by jpodpro** [yiisoft/yii2#11206]
i understand how hasMany works so i don't see an easy way to solve this. however it seems strange that you can't properly limit the result rows of a hasMany relation per record.

for example, if i do:
```php
Post::find()->with( ['comments'] )->where( ['id' => '1,2,3,4,5'] )->all();
```

and i have a getComments relation defined in Post like this:
```php
$this->hasMany( Comment::className(), ['postId' => 'id'] )->limit( 10 );
```

then the original query only returns 10 comments TOTAL instead of 10 comments per post. is there proper way to limit hasMany rows per record? obviously i can limit manually in the code but in the case of a great deal of hasMany records i'd rather not be working with a huge data set all at once.

**Comment by Faryshta** [comment]
do you know how to do it in plain sql?
