### ISSUE TITLE
documentation bug for \yii\rest\Controller::enableCsrfValidation

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#11215]
The documentation of [\yii\rest\Controller::enableCsrfValidation](http://www.yiiframework.com/doc-2.0/yii-rest-controller.html#$enableCsrfValidation-detail) inherits from \yii\web\Controller. The link to Request is relative, so it's broken here.

**Comment by nkovacs** [comment]
Making the link absolute (`[[\yii\web\Request::enableCsrfValidation]]`) would probably fix it, but I don't know how to generate the documentation to test it out.

**Comment by cebe** [comment]
Fixed, thanks for reporting!

If you have a yii dev setup that [includes extensions](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#extensions) you can generate the docs as follows:

```
# start in repo root
./extensions/apidoc/apidoc api framework/ apidocs
```

You find the generated docs in folder `apidocs`.
