### ISSUE TITLE
redirect can't execute in beforeAction with yii 2.0.7

### ISSUE THREAD

**Issue by crstudio** [yiisoft/yii2#11210]
redirect can't return in beforeAction with Yii 2.0.7,
but it can execute do in Yii 2.0.3
All extend yii\web\Controller.

```php
public function beforeAction($action)
    {
        return $this->redirect(['/login']);
    }
```

### Additional info

| Q                   | A
| ----------------- | ---
| Yii version      | 2.0.7 
| PHP version   | 7.0 or 5.5
| Operating system | Windows 10 x64

**Comment by SilverFire** [comment]
How to reproduce the error?

**Comment by quorzz** [comment]
1.    `redirect `  can't  redirect  at once ...
      try ` $this->redirect('/')->send();   `
      it will be abort the request and redirect immediately.

2.   beforeAction  should return  a  boolean value

@crstudio

**Comment by SilverFire** [comment]
@quorzz is right

**Comment by crstudio** [comment]
@qorzz I have tried, it is ok now.

**Comment by cebe** [comment]
> beforeAction should return a boolean value

more specifically it should return `false` in this case.
