### ISSUE TITLE
Number validator incorrectly handles values of some data types

### ISSUE THREAD

**Issue by azaikin** [yiisoft/yii2#11220]
### What steps will reproduce the problem?
Case 1:
```php
$value = true;
$validator = new \yii\validators\NumberValidator;
$validator->validate($value);
```
Case 2:
```php
$value = new \stdClass();
$validator = new \yii\validators\NumberValidator;
$validator->validate($value);
```
### What is the expected result?
Case 1: validate() returns false
Case 2: validate() returns false
### What do you get instead?
Case 1: validate() returns true
Case 2: validate() triggers an error 'Object of class stdClass could not be converted to string' in NumberValidator.php:108
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04

**Comment by samdark** [comment]
Fixed with https://github.com/yiisoft/yii2/commit/f312163258a45b839273936b43658c206ff67885. Thanks for reporting.
