### ISSUE TITLE
 \yii\i18n\Formatter::format() -- add $options parameter

### ISSUE THREAD

**Issue by nikhiltri** [yiisoft/yii2#11226]
I'm working on creating an editable GridView, which is essentially using the Formatter to output fields as form elements. Much of it is more straight-forward than I expected, making it easier to implement than in Yii1. (Yay Yii2!). There are a few functions that I'm overriding that I wonder if my changes would be useful for other developers. 

One is to add a third parameter to the Formatter [format()](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L301) function to pass an array of options, like so:

`public function format($value, $format, $options = [])`

that then gets passed to the related as*() method. This allows me to pass form element attributes to the as function for its output.

I realize this may be a particular case, but is this something others would benefit from as well?

**Comment by dynasource** [comment]
aren't the options already support by using an array for $format, as shown in https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L309 and the example at http://www.yiiframework.com/doc-2.0/guide-output-formatting.html

**Comment by dynasource** [comment]
aren't the options already supported by using an array for $format, as shown in https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L309 and the example at http://www.yiiframework.com/doc-2.0/guide-output-formatting.html
