### ISSUE TITLE
RBAC: DbManager::getRolesByUser returns an empty array when userid is 0

### ISSUE THREAD

**Issue by rvandevelde** [yiisoft/yii2#11223]
### What steps will reproduce the problem?
Add an user with an user id 0 and call getRolesByUser().

### What is the expected result?
Expected result is a return value of all the roles the user has

### What do you get instead?
An empty array

### Additional info
DbManager::getRolesByUser() has a check for empty parameter starting on line https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L456:

```php
        if (empty($userId)) {
            return [];
        }
```

Since empty will also return true on values like int 0 and string "0" it returns an empty array. 

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      |  5.6
| Operating system |  Linux/Windows

**Comment by samdark** [comment]
The check should be `isset($userId) && $userId !== ''`.

**Comment by VirtualRJ** [comment]
Made a pull request to fix it. It actually should test for `!isset($userId) || $userId === ''`
