### ISSUE TITLE
RateLimiter does not appear to work

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#11224]
### What steps will reproduce the problem?

User class:
```php
	public function getRateLimit($request, $action) {
		//return [$this->rate_limit, $this->rate_window];
		return [1, 60]; // not more than 1 request in 60 seconds
	}

	public function loadAllowance($request, $action) {
		[$this->rate_allowance, $this->rate_allowance_update_at];
	}

	public function saveAllowance($request, $action, $allowance, $timestamp) {
		$this->rate_allowance = $allowance;
		$this->rate_allowance_update_at = $timestamp;
		$this->save(false);
	}
```

Controller class:
```php
	public function behaviors() {
		return [
			'rateLimiter' => [
				'class' => 'yii\filters\RateLimiter',
				'enableRateLimitHeaders' => false
			]
		];
	}
```
### What is the expected result?
1 request in 60 seconds only. Every other request within 60 seconds should fail with TooManyRequests exception.

### What do you get instead?
Still able to issue many requests under 1 minute. The limiter is invoked as I see "Check rate limit" messages in the log, but no actual limit is enforced.

### Additional info
I want to use yii\filters\RateLimiter to prevent abuse of my web application with self-made user scripts that tend to try and scrap the screen contents by issuing many requests at short window frame.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.5
| Operating system | Windows

**Comment by klimov-paul** [comment]
Please provide full definition of your `User` class.

**Comment by dryu** [comment]
It is too big and contains sensitive information. I provided the implementation functions from ```RateLimiterInterface``` which are used in the ```yii\filters\RateLimiter```. If there is anything else you need - let me know.

**Comment by klimov-paul** [comment]
Ok, then provide the first 10 rows of its declaration, staring from `class` keyword.

**Comment by dryu** [comment]
```php
/**
 * Class User
 * 
 * @property $rate_limit
 * @property $rate_window
 * @property $rate_allowance
 * @property $rate_allowance_update_at
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface, RateLimitInterface {

	public static function tableName() {return 'Users';}

	public function attributeLabels() {
		return [
			....
		];
	}
```

What is there you need to know?

I looked in the source of ```yii\filters\RateLimiter``` and I do not understand the logic in ```checkRateLimit```:

```php
$allowance += (int) (($current - $timestamp) * $limit / $window);
```

$allowance can never be decremented with this logic, thus the condition for TooManyRequests will never be triggered ($allowance < 1).

$allowance is being set to 0 on the first request:

```sql
UPDATE [Users] SET [rate_allowance]=0, [rate_allowance_update_at]=1459256843, WHERE [id]='xxx'
```

For all consequent requests ```rate_allowance``` is never updated:
```sql
UPDATE [Users] SET [rate_allowance_update_at]=1459256851WHERE [id]='xxx'
```

When checking what is the calculated value of $allowance in ```checkRateLimit``` function I always get this number - 24320989.

The logic here eludes me completely.

**Comment by klimov-paul** [comment]
Is this correct?
```
public function loadAllowance($request, $action) {
        [$this->rate_allowance, $this->rate_allowance_update_at];
    }
```

Why does it miss `return` statement?

**Comment by dryu** [comment]
A mistake on my part. Sorry. It is working now. *sigh* I should probably go home, it is been a long day. Thanks again.
