### ISSUE TITLE
Losing data when use "joinWith()"

### ISSUE THREAD

**Issue by ruslanbat** [yiisoft/yii2#11239]
When I get data as
$query =  Store::find()->with('nomenclature')->asArray()->limit(100)->all();
echo count($query); //100
this normal result but i can't sorting my records.

When  i use this variant i can sorting my records
$query =  Store::find()->joinWith('nomenclature')->asArray()->limit(100)->all();
echo count($query); //93
Why 93? where I lost data

Store have record with the same nomenclature_id
 
Yii 2.0.7
PHP 5.6.16-2 
Ubuntu
Postgresql 9.4

**Comment by Faryshta** [comment]
open the debug and show us the executed queries

**Comment by cebe** [comment]
you probably filtered some records out that had no join canditate.

**Comment by Faryshta** [comment]
use a `groupBy('store_id')` at the end and it will work fine
