### ISSUE TITLE
Suggestion Gii Clear model class field after generation file(-s)

### ISSUE THREAD

**Issue by sokoji** [yiisoft/yii2#11232]
So. Now I'm generating Models after creating migrations.

I have 20+ tables in my database. I need 20+ Models.

The process:
1. I select table name, 
2. then click on "Model Class" field, this field have auto filling function.
3. After generation new Model I _need to clear "Model class" field_ 
4. and then select new table to auto fill up model class field.

It will be good to clear this field automatic (remove 3 step), isn't it?

**Comment by Faryshta** [comment]
sounds like a good improvement, meanwhile as a work around you can use the `./yii gii` command which is very easy to use and if you just use the up arrow key on your key board you get all the previoiusly used configurations.

And both in the graphic and the command you can use wild cards like "*" to generate files for EVERY table in your schema.

**Comment by sokoji** [comment]
@Faryshta thanx for your advice!

One moment:
I use table names in plural and models in singular. Example: table "posts" and model "Post".
That's why "*" or key up will not help me.

Are my naming rules wrong?

Thank you!

**Comment by klimov-paul** [comment]
> It will be good to clear this field automatic (remove 3 step), isn't it?

No. Although at some cases, like yours, it make sense, it will cause troubles at other ones.
For example: 
1. I fill up the web form with model parameters and generate a model
2. I open up generated file(s) and realize I have forgotten to include some esential option, like `enable i18n`
3. I return to the web form, adjust missing option and regenerate model.

At the step 3 I do NOT want to enter paramters like class name again.
