### ISSUE TITLE
Question: How to disable extension bootstrapping?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#11236]
### What steps will reproduce the problem?

We have a [metapackage](https://github.com/dmstr/yii2-cms-metapackage/issues/2) which contains some other Yii 2.0 extensions. If someone installs the package several extensions/modules are registered automatically in the application bootstrap process.

Is there a way to disable calls to `bootstrap()` in the configuration, eg. via `$extensions`?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |   2.0.7
| PHP version      |  5.6.18
| Operating system |   Linux (Docker)
| Related issues | https://github.com/dmstr/yii2-cms-metapackage/issues/2#issuecomment-203553611

**Comment by mdmunir** [comment]
manually update file `@vendor/yiisoft/extensions.php` then remark specific bootstrap :grinning:

**Comment by akaSStalkALEX** [comment]
I am using some kind of hack:
```
$extensions = require Yii::getAlias('@vendor/yiisoft/extensions.php');
unset($extensions['packageName']);
$config  = [
    ...
    'extensions' = $extensions
    ...
];
```

**Comment by mdmunir** [comment]
another why. in `bootstrap.php` and
```php
Yii::$container->set('ext\ns\Bootstrap',function(){
    return new yii\base\Object(); // or new stdClass();
});
```
