### ISSUE TITLE
SluggableBehavior in latest version work not properly

### ISSUE THREAD

**Issue by buuug7** [yiisoft/yii2#11241]
### What steps will reproduce the problem?
i used yii2-app-basic template,when use SluggableBehavior,it work not properly with chinese,below is my code ,what extra config i needed?

### What is the expected result?
it can translate chinese into english. eg:美国 ->mei-guo

### What do you get instead?
![image](https://cloud.githubusercontent.com/assets/12119289/14168023/bbf6f216-f751-11e5-8c19-1923d4302670.png)

### Additional info
![image](https://cloud.githubusercontent.com/assets/12119289/14166928/11fd15e4-f74a-11e5-99f6-cf8e8a6f7596.png)

| Q                | A
| ---------------- | ---
| Yii version      | 	Yii v2.0.7
| PHP version      | php5.5.12
| Operating system | win7

**Comment by SilverFire** [comment]
It seems, that you do not have ICU.
Did you verify your environment with requirements checker [as described in the guide](http://www.yiiframework.com/doc-2.0/guide-start-installation.html#verifying-installation)?

I've added a test to verify your case: https://github.com/yiisoft/yii2/commit/499ee6de9ea468cb2a95ecc43a7a588f8b1a321e

**Comment by buuug7** [comment]
yes i know

**Comment by SilverFire** [comment]
So do you have ICU?

**Comment by buuug7** [comment]
i used php with the php-cgi.exe in the nginx server
my problem is resolved by modified php.ini file
![image](https://cloud.githubusercontent.com/assets/12119289/14198981/9b0b9306-f812-11e5-8a81-bb22c6e7c781.png)
![image](https://cloud.githubusercontent.com/assets/12119289/14198987/a5869da8-f812-11e5-9120-65aceaf86e34.png)
