### ISSUE TITLE
RBAC is missing getRolesByRole()

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#11245]
Rbac makes it possible to specify a role that has a parent role. There is however no function `getRolesByRole($roleName)` to get it's children.

This function is almost identical to the function `getPermissionsByRole($roleName)`.

in `yiisoft/yii2/rbac/DbManager.php`:
```php
    /**
     * @inheritdoc
     */
    public function getRolesByRole($roleName)
    {
        $childrenList = $this->getChildrenList();
        $result = [];
        $this->getChildrenRecursive($roleName, $childrenList, $result);
        if (empty($result)) {
            return [];
        }
        $query = (new Query)->from($this->itemTable)->where([
            'type' => Item::TYPE_ROLE,
            'name' => array_keys($result),
        ]);
        $roles = [];
        foreach ($query->all($this->db) as $row) {
            $roles[$row['name']] = $this->populateItem($row);
        }
        return $roles;
    }
```
in `yiisoft/yii2/rbac/ManagerInterface.php`:
```php
    /**
     * Returns all child roles that the specified role represents.
     * @param string $roleName the role name
     * @return Role[] all child roles that the role represents. The array is indexed by the role names.
     */
    public function getRolesByRole($roleName);

```

**Comment by samdark** [comment]
I think it should something like `getChildRoles()`.

**Comment by samdark** [comment]
What do you need it for?

**Comment by michaelarnauts** [comment]
I have a admin-interface to manage the Users, Roles and Permissions where I would like to be able to get the assigned child Roles of a specified Role. This already exists for Permissions (`getPermissionsByRole`), but it doesn't for Roles.

**Comment by samdark** [comment]
OK. Makes sense.

**Comment by samdark** [comment]
Do you have time for a pull request?

**Comment by michaelarnauts** [comment]
I've added a PR, but you should check to be sure. I haven't tested the code of `PhpManager`.
