### ISSUE TITLE
Overriding validation rules could be more flexible

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#11243]
I have generated models of my database with gii so the validation rules are automatically generated based on the database constraints. Now, the models I really use extend these generated models, so my custom methods don't get overwritten when I do a datbase change and re-run gii.

The issue I'm now facing is that I want to change a validation rule.

In my generated class:
```php
    public function rules()
    {
        return [
            [['username', 'password', 'firstname', 'lastname'], 'required'],
            [['username', 'firstname', 'lastname'], 'string', 'max' => 50],
            [['password'], 'string', 'max' => 60],
        ];
    }
```

In my extended class:
```php
    public function rules()
    {
        return [
            [['username', 'firstname', 'lastname'], 'required'],
            [['username', 'firstname', 'lastname'], 'string', 'max' => 50],
            [['password'], 'string', 'max' => 60],
            [['password'], 'required', 'on' => 'create'],
            [['password'], 'safe', 'on' => 'update'],
        ];
    }
```

Unfortunalty, I have to copy all the rules and when I run a db update, I have to remember to copy the rules again.

In case I only want to add a rule, I could do a `parent::rules()` and `array_merge()` them, but I can't unset a specific rule (to remove the `'password'` from the first `'required'` line). 

This works nicely with `function actions()` and `function behaviors()` since they provide keys you can `unset()`.

**Comment by nkostadinov** [comment]
I dont get the problem. Why dont you use:
```
$rules = parent::rules();
unset($rules['password']);
array_merge($rules, [(your rules)])
```

**Comment by klimov-paul** [comment]
You may add named key for the validation rules and manipulate them later:

```php
public function rules()
    {
        return [
            [['username', 'password', 'firstname', 'lastname'], 'required'],
            [['username', 'firstname', 'lastname'], 'string', 'max' => 50],
            'password' => [['password'], 'string', 'max' => 60],
        ];
    }

...
public function rules()
    {
        $rules = parent::rules();
        unset($rules['passoword']);
        return $rules;
    }

```

**Comment by michaelarnauts** [comment]
Ah, this seems to be missing in the docs.

**Comment by SilverFire** [comment]
I'm leaving this issue open is a docs issue
Would you like to send PR with updated article?

**Comment by sheillendra** [comment]
About named key of the validation rules, could implement it to gii?
