### ISSUE TITLE
batchInsert incorrectly quotes SQL query with values, containing {{ }} symbols

### ISSUE THREAD

**Issue by mutyonok** [yiisoft/yii2#11242]
### What steps will reproduce the problem?

`$this->db->createCommand()->batchInsert('table', ['column1'], [["input-{{value}}"]])->execute();`
### What is the expected result?

Value inserted into a table
### What do you get instead?

[yii\db\Exception] SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax
The SQL being executed was: `INSERT INTO "table" ("column1") VALUES ('input-"value"')`
### Additional info

The problem is that `Command::setSql` method quotes already prepared batch insert query with `'/(\\{\\{(%?[\w\-\. ]+%?)\\}\\}|\\[\\[([\w\-\. ]+)\\]\\])/'` regexp inside `Connection::quoteSql` which does not know anything about the context 

| Q | A |
| --- | --- |
| Yii version | Yii v2.0.7 |
| PHP version | PHP 5.6.16 (cli) (built: Nov 27 2015 10:28:34) |
| Operating system | Any |

**Comment by Faryshta** [comment]
thats a documented behavior, for yii2 `{{ }}` are reserved characters that are used to quote tables. you need to sanitize them, something like `\{\{ \}\}`

**Comment by mutyonok** [comment]
the problem is only in batchInsert method, because it quotes SQL after a query is already built.
You have table name and columns as parameters of a batchInsert method - just quote them, not the whole query.

**Comment by mutyonok** [comment]
I consider it a bug anyway. Also documentation is not clear as well.

**Comment by SilverFire** [comment]
It is documented clearly as for me: http://www.yiiframework.com/doc-2.0/guide-db-dao.html#quoting-table-and-column-names

Since we will not change this behavior, how do you suggest to improve documentation?

**Comment by mutyonok** [comment]
first of all, the behaviour of insert and batchInsert is not consistent.
For `insert` I could pass any value for a column. I can't believe you don't see any issue here.
Second: Documentation clearly says only about pure SQL which I write in `createCommand`.
for higher order functions like `insert` and `batchInsert` where I don't deal with SQL directly, how would one know that for column values these quoting rules apply as well?

**Comment by klimov-paul** [comment]
This issue has same source as #6526 and #9276 : the values for the batch insert are not bound as PDO params, but are inserted directly instead. Thus when it comes to quote table and column names the value surrounded by `{{` and `[[` are processed as table or column names.

**Comment by SilverFire** [comment]
Makes sense. I'm suggesting to re-write batchInsert in order to use parameter binding. The only thing I'm afraid of is a limit of PDO parameters, if there is any.

**Comment by xhook** [comment]
@SilverFire this will make it slow as hell. We tried it with buildInCondition. It's just unusable after few thousand bound params.

**Comment by mutyonok** [comment]
@SilverFire what do you think about this solution?
```
public function batchInsert($table, $columns, $rows)
{
  $quotedTable = $this->db->quoteSql($table);
  
  $quotedColumns = [];
  foreach ($columns as $column) {
  	$quotedColumns[] = $this->db->quoteSql($column);
  }
  
  $sql = $this->db->getQueryBuilder()->batchInsert($quotedTable, $quotedColumns, $rows);
  
  $this->setSql($sql); //but do not quote this SQL as it was already quoted
  
  return $this;
}
```

**Comment by SilverFire** [comment]
Are you showing method in `Command`, or `QueryBuilder`?

**Comment by mutyonok** [comment]
snippet for Command.php

**Comment by starhobbit** [comment]
I told u about this bug on YiiConf :)

**Comment by samdark** [comment]
Seems @SilverFire did a pull request about it a long time ago: https://github.com/yiisoft/yii2/issues/13236
