### ISSUE TITLE
problem with saveAs()

### ISSUE THREAD

**Issue by ContzZz** [yiisoft/yii2#11257]
### What steps will reproduce the problem?

```php
$answer->save();
            $path = Yii::getAlias('@app') .'/web/uploads/'.$answer->answer_id;
            $answer->save();
            if (!file_exists($path)) {
                mkdir($path, 0777);
            }
            chmod($path, 0777);
            $answer->save();
            $answer->answer_image = '/backend/web/uploads'.$answer->answer_id.'/'.date('his').$answer->file->name;
            $answer->save();
            $answer->file->saveAs( $path.'/'.date('his').$answer->file->name);
```

### What is the expected result?
I want to save image.
### What do you get instead?
i have error
finfo_file(W:\userdata\temp\php99DB.tmp): failed to open stream: No such file or directory
### Additional info
i try save model before saveAs but it does not help.
so i go to yii\web\UploadedFile and comment some lines

```php
public function saveAs($file, $deleteTempFile = true)
    {
       // if ($this->error == UPLOAD_ERR_OK) {
       //     if ($deleteTempFile) {
       //         return move_uploaded_file($this->tempName, $file);
       //     } elseif (is_uploaded_file($this->tempName)) {
                return copy($this->tempName, $file);
        //    }
       // }
       // return false;
    }
```

after that all works good. but i think it's bad idet change core

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.0.0
| Operating system | win7

**Comment by mdmunir** [comment]
https://www.facebook.com/groups/yiitalk/

1. Ensure you load uploaded file using `UploadedFile::getInstance()`.
2. Ensure you do not save file twice.

**Comment by sfalpha** [comment]
I just hit this bug too. This caused by file validation fails on 2nd time validation (Which implicitly called before save())

I think this can reproduce easily by call $model->save() twice, just that.

Workaround for now is use $model->save(false) if u need to save the model more than once.

**Comment by cebe** [comment]
@ContzZz as pointed out by @sfalpha you should run validation only once. The best way to do it is calling `validate()` once and then save the model with `$model->save(false)`. Make sure to check the return value of `validate()` call and do not proceed if it fails.

**Comment by sfalpha** [comment]
Although this bug closed, How can you ensure than validate will run once while save() still implicitly call validate() ???

Consider situation that some model need to save twice() (save, get id, update another tables, get id back and save this model), and there is called to UploadFile's saveAs() in between. 2nd save always fails because it defaults to validate the data, saveAs() defaults to delete temp file.

At least you should document it somehow that $deleteTempFile = false need to be set if you do save() the model twice.

Currently I do set $deleteFempFile = false if I need to save model twice as workaround.

**Comment by cebe** [comment]
if you need to save multiple times you should call vlidate once and call save(false) afterwards in all calls to save.
