### ISSUE TITLE
FR/Enh: Make RBAC Rule more flexible

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#11254]
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | -

Currently to assign `rule` to `role` we must register rule class via `BaseManager::addRule()` then assign `role` with that registered `rule`.
```php
$auth = Yii::$app->authManager;

// add the rule
$rule = new \app\rbac\AuthorRule;
$auth->add($rule);

$updateOwnPost = $auth->createPermission('updateOwnPost');
$updateOwnPost->ruleName = $rule->name; 
$auth->add($updateOwnPost);
```
Prefer we can skip registering rule and directly use className as `ruleName`.
```php
$auth = Yii::$app->authManager;

$updateOwnPost = $auth->createPermission('updateOwnPost');
$updateOwnPost->ruleName = 'app\rbac\AuthorRule'; // <- here
$auth->add($updateOwnPost);
```

**Comment by samdark** [comment]
Yeah, could be done.
