### ISSUE TITLE
Unexpected behaviour of $this->renderAjax(...)

### ISSUE THREAD

**Issue by tolik505** [yiisoft/yii2#11267]
### renderAjax doesn't return css and config of js plugins. 
It replaces them with <![CDATA[YII-BLOCK-HEAD]]><![CDATA[YII-BLOCK-BODY-BEGIN]]> 

### Before some latest commits, renderAjax returned css and config of plugins

```html
<link href="/assets/c3132b9a/css/select2.css?v=1456864258" rel="stylesheet">
<link href="/assets/c3132b9a/css/select2-addl.css?v=1456864258" rel="stylesheet">
<link href="/assets/c3132b9a/css/select2-krajee.css?v=1456864258" rel="stylesheet">
var s2options_c4acac00 = {"themeCss":".select2-container--krajee","sizeCss":"","doReset":true,"doToggle":true,"doOrder":false};
var select2_ae6b82b7 = {"theme":"krajee","width":"100%","placeholder":"Select states ...","language":"en"};
</script>
<input type="hidden" name="_csrf" value="T25reXR5NFYhAxtAFyZZbmIcJw1GAGQPdxckTRsuRhkhBBIMHg5NMQ==">    
<div class="form-group content-append filled item-0 tr"><!-- widgetBody -->
        <button type="button" class="btn btn-info btn-template-mover ui-sortable-handle"><i class="glyphicon glyphicon-move"></i></button>
        <button type="button" class="btn btn-danger btn-template-delete"><i class="glyphicon glyphicon-trash"></i></button>
....
```

### Now it doesn't returns expected data
```html
<![CDATA[YII-BLOCK-HEAD]]><![CDATA[YII-BLOCK-BODY-BEGIN]]>    
<div class="form-group content-append filled item-0"><!-- widgetBody -->
        <button type="button" class="btn btn-info btn-template-mover ui-sortable-handle"><i class="glyphicon glyphicon-move"></i></button>
        <button type="button" class="btn btn-danger btn-template-delete"><i class="glyphicon glyphicon-trash"></i></button>
...
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7
| Operating system | ubuntu 14.04

**Comment by SilverFire** [comment]
Can you find it with `git bisect`?

**Comment by tolik505** [comment]
The problem is here https://github.com/yiisoft/yii2/commit/7dc984d35928128b3612fb6aa4ed19b03ee963fd#diff-9569d5ac7fb33f42bb07237c09ee32cbL181

**Comment by SilverFire** [comment]
Thank you!

**Comment by tolik505** [comment]
Don't mention it!

**Comment by pana1990** [comment]
@tolik505 it works for me, could you display your code?

**Comment by tolik505** [comment]
Yes, sure!
Here is the action
`public function actionGetNewRow()
    {
        $request = Yii::$app->request;
        $className = $request->post('className');
        $container = $request->post('container');
        $index = $request->post('index');
        $relModels[$index] = new $className;

        return Json::encode([
            'replaces' => [
                [
                    'what' => ".$container .content-append:last-child",
                    'data' => $this->renderAjax('//templates/_related_form_fields', ['relModels' => $relModels] )
                ]
            ]
        ]);
    }`
Here is the view
`if (!isset($form)) {
    $form = FormBuilder::begin([
        'id' => 'dummy-form'
    ]);
}
foreach ($relModels as $index => $elModel) { ?>
    <div class="form-group content-append filled item-<?= $index ?> tr">
        <?php
        foreach ($elModel->getFormConfig($index) as $attr => $el) {
                echo $form->renderField($elModel,  "[{$index}]$attr", $el);
        } ?>
    </div>
<?php }`
FormBuilder extends ActiveForm.
When I return the previous version of ActiveForm
` public function init()
    {
        if (!isset($this->options['id'])) {
            $this->options['id'] = $this->getId();
        }
        echo Html::beginForm($this->action, $this->method, $this->options);
    }
    
    public function run()
    {
        if (!empty($this->_fields)) {
            throw new InvalidCallException('Each beginField() should have a matching endField() call.');
        }

        if ($this->enableClientScript) {
            $id = $this->options['id'];
            $options = Json::htmlEncode($this->getClientOptions());
            $attributes = Json::htmlEncode($this->attributes);
            $view = $this->getView();
            ActiveFormAsset::register($view);
            $view->registerJs("jQuery('#$id').yiiActiveForm($attributes, $options);");
        }

        echo Html::endForm();
    }`
it work good.
The problem is in ActiveForm.

**Comment by pana1990** [comment]
mmm, it is strange. 

@SilverFire do you try reproduced this issue? it works for you?

**Comment by SilverFire** [comment]
> Here is the view

It seems, that you do not have `FormBuilder::end()`, have you?

What is FormBuilder? That commit changed behavior of output buffer handling in `init()` and `run()` methods by adding `ob_*()` functions' calls. Did you update your `FormBuilder` methods?

**Comment by SilverFire** [comment]
Removed from 2.0.8 milestone because nobody have neither reproduced this nor reported similar issue.

**Comment by SilverFire** [comment]
Added a line to UPGRADE.md: https://github.com/yiisoft/yii2/commit/37fdc8c5e5e2c31eab12847f2dadb5f5687aa212

**Comment by cebe** [comment]
> It seems, that you do not have FormBuilder::end(), have you?

I am very certain that this is the problem. when calling begin() on a widget you must call end() otherwise the widget stack is broken.

**Comment by tolik505** [comment]
Yes, the problem was in that. Sorry for the false alarm.
