### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by bubifengyun** [yiisoft/yii2#11273]
my table has many attributes, including `total_days`, `part1_days`, `part2_days` and so on.
using gii, I can create ActiveRecord model. the first day of every year, I want to update `total_days`=`part1_days`+`part2_days`+$somedata. I can update use SQL directly, and I also find `updateAll` which could be used. however it not support `part1_days`. could you add the feature that the self attribute could be used in updateAll function.

thank you.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6.15
| Operating system | Linux deepin 15.1.1

**Comment by cebe** [comment]
You can do it like this:

```php
ActiveRecord::updateAll(['total_days' => new \yii\db\Expression('part1_days + part2_days + :somedata', [':somedata' => $somedata])]);
```
