### ISSUE TITLE
output json

### ISSUE THREAD

**Issue by ivantree** [yiisoft/yii2#11274]
I want output json not xml 
in my config file is 
![qq 20160405122936](https://cloud.githubusercontent.com/assets/9014680/14271312/4fe0e19a-fb2a-11e5-8551-d0d8b681d54e.png)
and controller file is 
![qq 20160405123239](https://cloud.githubusercontent.com/assets/9014680/14271335/98b9780a-fb2a-11e5-8941-c34bd7f671c1.jpg)
still output xml format.
I do not want like is 
![qq 20160405125145](https://cloud.githubusercontent.com/assets/9014680/14271593/256a89fe-fb2d-11e5-9664-554bcdbc8df9.png)
**how can I set in config file ? Thanks a lot!**

**Comment by SilverFire** [comment]
Default REST Contoller, that you extend from already contains `contentNegotiatior` config: https://github.com/yiisoft/yii2/blob/master/framework/rest/Controller.php#L46

Create your own `Controller` class in your project, that extends `yii\rest\Controller`, override this behavior config once and extend all your classes from your new default controller. That's it!
