### ISSUE TITLE
E_NOTICE error_reporting 

### ISSUE THREAD

**Issue by wozzup** [yiisoft/yii2#11276]
in a controller method:

```
// no error report
if ($var) {}
```

```
//report: Undefined variable: var
if ($var)
```

**Comment by mdmunir** [comment]
:+1: 
![screenshot from 2016-04-05 13 40 37](https://cloud.githubusercontent.com/assets/5828252/14273380/780bb186-fb34-11e5-8526-f43e785e2526.png)

In my case, should error in line 37

**Comment by SilverFire** [comment]
It seems that the problem is related rather to PHP than to Yii2, isn't it?
