### ISSUE TITLE
Error when link record in one to many relation

### ISSUE THREAD

**Issue by iushev** [yiisoft/yii2#11270]
Hi
I have one active record that have one to many relation with other one.
In my primary model relation is defined like this:
```php
class Product extends ActiveRecord
{
...
    public function getProductOptions()
    {
        $query = $this->hasMany(ProductOption::className(), ['product_id' => 'id']);
        $query->indexBy(function ($row) {
            return $row->option->key_name . '_' . $row->id;
        });
        return $query;
    }
...
}
```
When save data i link ```ProductOption``` with ```Product```
```php
$product->link('productOptions', $productOption);
```
and this throw exception "Object of class Closure could not be converted to string".
The exception is throw from 'vendor/yiisoft/yii2/db/BaseActiveRecord.php' at row 1239: 
```php
        // update lazily loaded related objects
        if (!$relation->multiple) {
            $this->_related[$name] = $model;
        } elseif (isset($this->_related[$name])) {
            if ($relation->indexBy !== null) {
                $indexBy = $relation->indexBy;
                $this->_related[$name][$model->$indexBy] = $model;  // this row throw exception
            } else {
                $this->_related[$name][] = $model;
            }
        }
```
The error is occur because i have ```indexBy``` with function. In my case I need this.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      |  5.5.9-1ubuntu4.14
| Operating system | Linux 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64

**Comment by SilverFire** [comment]
Seems to be a bug. [QueryBuilder](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#indexing-query-results) docs declares that it is possible and I can not find elsewhere information that is does not work for ActiveRecord.
Would you like to help us in fixing this by submitting a PR?
