### ISSUE TITLE
Yii does not call beforeSubmit on dynamically AJAX-loaded forms

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#11272]
I don't know if this is a problem with Yii or just something that wasn't considered. I can't even find `beforeSubmit` in the documentation as there are no search results.

### What steps will reproduce the problem?
Load a form via AJAX: `$('#emailBody').load('email-form');`
Try to listen to the `beforeSubmit` event: `$('#emailBody').on('beforeSubmit', '#emailForm', function(event) {`

### What is the expected result?
I expected the `beforeSubmit` even would be called. It's not. Even if I have to bind the events manually, I kind of expected I could do something like `yii.bindFormEvents('#emailForm');` or maybe Yii hooks into JQuery with `$('#emailForm').yiiBindFormEvents()`.

### What do you get instead?
The events are completely ignored. The validations don't work either.

### Additional info
Yii 2.0.7, PHP 5.6.19, Windows/Cygwin

More info, more code:

http://stackoverflow.com/questions/36414968/how-do-i-bind-to-beforesubmit-event-on-an-ajax-loaded-form-in-yii/

**Comment by cebe** [comment]
See my answer on stackoverflow: http://stackoverflow.com/a/36416206/1106908
If that does not help and you think it is an issue in yii, we can discuss it further. For now I am closing this issue.
