### ISSUE TITLE
Autogeneration of the migration code breaks MongoDB migration

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#11280]
Originally reported at:
https://github.com/yiisoft/yii2-mongodb/issues/96

Latest addition:
https://github.com/yiisoft/yii2/pull/9490

was made in the wrong way: `BaseMigrateController` was affected by relational DB related logic.

Thus, MongoDb migration now fails with error "The view file does not exist: "

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/pull/11281

**Comment by jafaripur** [comment]
Before i have same issue but I fixed it with this solution:

```php
    'controllerMap' => [
        'mongodb-migrate' => [
            'class' => 'yii\mongodb\console\controllers\MigrateController',
            'migrationPath' => '@app/migrations/mongodb'
        ]
    ],
```
and for generate migration:

```
php yii mongodb-migrate/create user_collection
```

MongoDB migration going to mongodb folder under migrations folder.

**Comment by Faryshta** [comment]
@jafaripur have you tried it with yii 2.0.7?

**Comment by jafaripur** [comment]
@Faryshta Yes, I use latest Yii2 master
