### ISSUE TITLE
ActiveRecord::unlink() is unnecessarily nulling foreign key property

### ISSUE THREAD

**Issue by PMan2** [yiisoft/yii2#11283]
Hello,
I have problem with foreach on line 1307 in BaseActiveRecord.php, which is nulling foreign key property of parent model.
I'm using custom delete behavior, where I cancel "real" model deletion and I just set the "deleted" attribute to "true" instead.

Important part of my custom delete behavior code:
```php
public function beforeDelete($event) {
    ...
    $owner->{$this->deletedAttribute} = true;
    $owner->save();
    $event->isValid = false;
}
```

So imho it would be correct to keep foreign key value, but only when "$delete" parameter is set to "true", so it won't break the other functionality.

**Original code:**
```php
foreach ($relation->link as $a => $b) {
    $model->$a = null;
}
$delete ? $model->delete() : $model->save(false);
```

**Altered code:**
```php
if (!$delete) {
    foreach ($relation->link as $a => $b) {
        $model->$a = null;
    }
}
$delete ? $model->delete() : $model->save(false);
```

When programmer want to unlink without delete, it will do the nullification of foreign key, which is OK. But when he wants to delete foreign model, it will keep the foreign key value. This doesn't matter when you do "real" delete (foreign model will be deleted anyway), but when you override deletion in behavior by updating "deleted" attribute, you keep data in database and when the non-nullable foreign key is nullified, the SQL update crashes.

Cheers and thanks.

~PMan

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.5.30
| Operating system | Win 8.1

**Comment by klimov-paul** [comment]
ActiveRecord deleting does not connected to the `unlink()` method anyhow inside the core.
It seems to invoke it yourself somewhere, thus you should apply your logic at that place on your own.
