### ISSUE TITLE
DSN Empty error

### ISSUE THREAD

**Issue by sahifedp** [yiisoft/yii2#11295]
I am getting the following error on SOME Ajax calls:

Exception (Invalid Configuration) "yii\base\InvalidConfigException" with message 
"Connection::dsn cannot be empty."

I can make exactly the same call again and it's fine, it just appears intermittently.

There is nothing wrong with my configuration or my database connection.

(localhost on WAMP 3  AND win 10)
Im using  .env config file (trntv starter kit)

stack trace:
Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Connection::dsn cannot be empty.'

in F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php:523

Stack trace:
#0 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(836): yii\db\Connection->open()
#1 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(823): yii\db\Connection->getMasterPdo()
#2 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(796): yii\db\Connection->getSlavePdo()
#3 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(680): yii\db\Connection->getDriverName()
#4 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\ActiveRecord.php(294): yii\db\Connection->getSchema()
#5 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\ActiveRecord.php(317): yii\db\ActiveRecord::getTableSchema()
#6 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\ActiveRecord.php(176): yii\db\ActiveRecord::primaryKey()
#7 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\BaseActiveRecord.php(102): yii\db\ActiveRecord::findByCondition(1)
#8 F:\lamp\www\ara20\common\models\User.php(126): yii\db\BaseActiveRecord::findOne(1)
#9 F:\lamp\www\ara20\vendor\yiisoft\yii2\web\User.php(614): common\models\User::findIdentity(1)
#10 F:\lamp\www\ara20\vendor\yiisoft\yii2\web\User.php(176): yii\web\User->renewAuthStatus()
#11 F:\lamp\www\ara20\vendor\yiisoft\yii2\web\User.php(346): yii\web\User->getIdentity()
#12 F:\lamp\www\ara20\vendor\yiisoft\yii2\base\Component.php(130): yii\web\User->getIsGuest()
#13 F:\lamp\www\ara20\common\behaviors\LocaleBehavior.php(46): yii\base\Component->__get('isGuest')
#14 [internal function]: common\behaviors\LocaleBehavior->beforeRequest(Object(yii\base\Event))
#15 F:\lamp\www\ara20\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\base\Event))
#16 F:\lamp\www\ara20\vendor\yiisoft\yii2\base\Application.php(372): yii\base\Component->trigger('beforeRequest')
#17 F:\lamp\www\ara20\frontend\web\index.php(25): yii\base\Application->run()
#18 {main}

**Comment by samdark** [comment]
.env config file is the culprit.
