### ISSUE TITLE
Cache.SerializerPath as a non-existent folder

### ISSUE THREAD

**Issue by thiagotalma** [yiisoft/yii2#11297]
### What steps will reproduce the problem?
Set application `runtimePath` as a non-existent folder. Parent folder is writable.

### What is the expected result?
The folder should be created when it does not exist.

### What do you get instead?
```
yii\base\ErrorException
Base directory /srv/www/app/runtime/app-master does not exist, please create or change using %Cache.SerializerPath
```

**Comment by klimov-paul** [comment]
`Cache.SerializerPath` - what is this?

**Comment by thiagotalma** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtmlPurifier.php#L50

**Comment by klimov-paul** [comment]
You should report this to `HTMLPurifier` project

**Comment by thiagotalma** [comment]
I understand.
But would not a task for Yii2 ensure that the folder that will write exist?

**Comment by klimov-paul** [comment]
no

**Comment by thiagotalma** [comment]
ok, thanks!
