### ISSUE TITLE
Pjax in the file layout does not publish assets registered in the view file

### ISSUE THREAD

**Issue by voskobovich** [yiisoft/yii2#11305]
### What steps will reproduce the problem?

Wrap in layout (main.php) content variable in Pjax widget

``` php
<?php Pjax::begin(['id' => 'js-pjax-main-container']); ?>
    <?= $content ?>
<?php Pjax::end(); ?>
```

In view file registration JS, CSS code and some pjax widget

``` php
<?php Pjax::begin(['id' => 'js-pjax-some-container']); ?>
    ...
<?php Pjax::end(); ?>

<?php
$this->registerJs('alert(1)');
$this->registerCss('#js-pjax-main-container { background: blue; }');
?>
```

Reload main container

``` js
$.pjax.reload({container: '#js-pjax-main-container'});
```
### What is the expected result?

The response should include posted the JS, CSS and some pjax js code.
### What do you get instead?

The response does not contain the published JS and CSS.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.7 |
| PHP version | 5.6 |
| Operating system | Debian |

**Comment by Alex-Code** [comment]
You need to put the `register` functions before the `Pjax` widget.
If it's a `Pjax` request `Pjax::end()` will call `Application:end()`

**Comment by voskobovich** [comment]
But it's not rational.
The application itself must understand that all publications between pjax::begin() and pjax::end() need to be published.

**Comment by dynasource** [comment]
registering & publishing assets is out of the scope of the Pjax widget. If you want this to be executed inline, you have to do this manually.

**Comment by derekisbusy** [comment]
#13545 fixes this issue.
