### ISSUE TITLE
Request class cann't return ONLY domain (without scheme)

### ISSUE THREAD

**Issue by dmitriiPopov** [yiisoft/yii2#11309]
`Yii::$app->request->getHostInfo()` returns 'http://example.com'. There is no method for handling $_SERVER['HTTP_HOST'] and returning ONLY domain, e.g. `Yii::$app->request->getDomain()` which returns only 'example.com'.
I think will be better to add this method in yii\webRequest class for working in same yii-interface with superglobal variable $_SERVER.

**Comment by tunecino** [comment]
I use this:
```php
private function getHost($url)
{
    // by @stanev01 : http://stackoverflow.com/questions/16027102/get-domain-name-from-full-url#answer-16027164
    // getHost("http://mail.somedomain.co.uk") -> outputs 'somedomain.co.uk'
    $pieces = parse_url($url);
    $domain = isset($pieces['host']) ? $pieces['host'] : '';
    $rx = '/(?P<domain>[a-z0-9][a-z0-9\-]{1,63}\.[a-z\.]{2,6})$/i';
    if (preg_match($rx, $domain, $regs)) return $regs['domain'];
    return false;
}
```

**Comment by tunecino** [comment]
is the code I just suggested good enough for a built-in method ? It worked fine with me but I'm not good with regex stuff. does it cover all cases ?

**Comment by tunecino** [comment]
@jonathansampson any suggestion ? do you like to contribute to Yii ? we would like a similar thing [here](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L521-L591).

**Comment by tunecino** [comment]
or maybe it should be better based on a maintained list like [this one](https://publicsuffix.org/list/public_suffix_list.dat)  -- https://publicsuffix.org/

**Comment by tunecino** [comment]
oh there is already a PHP implementation linked in the learn more section:
 https://github.com/jeremykendall/php-domain-parser
