### ISSUE TITLE
Add ArrayHeloper::multiGet(), ::multiSet

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#11310]
I'm suggesting to add a new ArrayHelper method `multiGet`:

```php
$array = [
    'a' => 1,
    'b' => 2,
    'c' => 3
];

$new = ArrayHelper::multiGet($array, ['a', function ($array) { return 'b'; }]));
// ['a' => 1, 'b' => 2]
```

**Comment by taxp** [comment]
Ain't multiGet the same method as native PHP's workaround?
```php
$array = [
    'a' => 1,
    'b' => 2,
    'c' => 3
];
$keys = ['a', 'b'];
$new = array_intersect_key($array, array_flip($keys));;
/*
[
    'a' => 1,
    'b' => 2
]
*/
```

**Comment by SilverFire** [comment]
Yes, it's very similar, but will work with `ArrayHelper::getValue()`

**Comment by cebe** [comment]
What are the use cases for this method?

**Comment by SilverFire** [comment]
For example you have array and you need to build a new one that contains some values from previous.

```php
$array = ['username' => 'silverfire', 'password' => '123123', 'whatever' => 'abc', 'date' => '2016-04-20'];

// Yii::info('Blah', ['username => $array['username'], 'date' => $array['date']]);
Yii::info('Blah', ArrayHelper::multiGet($array, ['username', 'date']);
```

**Comment by lynicidn** [comment]
как правило в дебаг надо вносить все данные, ну и info не принимает кажись массив

**Comment by SilverFire** [comment]
It was not an example of `Yii::info` usage or debug. It's about values extracting

**Comment by SilverFire** [comment]
Mostly resolved by https://github.com/yiisoft/yii2/pull/11462
