### ISSUE TITLE
Use custom class. eg. Connection， but some of the components are written yii\db\Connection

### ISSUE THREAD

**Issue by netyum** [yiisoft/yii2#11313]
### What steps will reproduce the problem?
e.g 

yii\rabc\DbManager 

My db compoent 's class was custom class.
so 
```
namespace yii\rabc;
...
class DbManager extends BaseManager
{
   ...
    public function init()
    {
        parent::init();
        // Connection was yii\db\Connection ，， why not pass configuration settings.
        $this->db = Instance::ensure($this->db, Connection::className());
        if ($this->cache !== null) {
            $this->cache = Instance::ensure($this->cache, Cache::className());
        }
    }
    ...
```
### What is the expected result?

"db" refers to a common\components\Connection component. yii\db\Connection is expected.

### What do you get instead?

This is not good.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 
| PHP version      | 
| Operating system |

**Comment by mdmunir** [comment]
What your DbManager::$db config?

**Comment by klimov-paul** [comment]
Your custom connection class should extend `yii\db\Connection`:

```php
namespace common\components;

class Connection extends \yii\db\Connection
{
   ...
}
```
