### ISSUE TITLE
addForeignKey doesn't parse first table string for prefix rule

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii2#11312]
### What steps will reproduce the problem?

Create a migration and add two tables, in the second try to refer to the first:

```php
$this->addForeignKey(
            'FK_site_config_client',
            '{{%site_config}}',
            'client_id',
            '{{%client}}',
            'id',
            'CASCADE'
        );
```

### What is the expected result?

should add constraint

### What do you get instead?

SQL syntax error - cant execute alter {{%site_config}} ...

### Additional info

yii2 stable

**Comment by Faryshta** [comment]
which version of yii2 you use? I tried the same code and I got no error. (with empty tables site_config and client

**Comment by cebe** [comment]
same here. unable to reproduce.

**Comment by philippfrenzel** [comment]
was 2.0.7 but if you can't reproduce - might be another reason... :/ Thanks for debugging

**Comment by cebe** [comment]
does it still happen for you? please provide more information about where you run the query and paste the full error including stack trace.
