### ISSUE TITLE
ActiveRecord::setAttributes() incorrect behaviour on unsafe attributes

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#11315]
Loading unsafe attribute with $model->setAttributes(['x' => 123], false); works if $model is an instance of `\yii\base\Model` and does not work if $model is an instance of `\yii\db\ActiveRecord` and the X attribute not present in database but defined in PHP class (see examples below).

`Model` example 1:  `x` is safe attribute (no bug).
```PHP
class User extends \yii\base\Model
{
	public $x;
	public function rules()
	{
		return [['x', 'safe']];
	}
}
function test()
{
	$user = new User();
	$user->setAttributes(['x' => 123], true);
	var_dump($user->x); // 123 - correct
}
```

`Model` example 2:  `x` is unsafe attribute (no bug).
```PHP
class User extends \yii\base\Model
{
	public $x;
}
function test()
{
	$user = new User();
	$user->setAttributes(['x' => 123], false);
	var_dump($user->x); // 123 - correct
}
```

`ActiveRecord` example 1:  `x` is safe attribute (no bug).
```PHP
/**
 * @property int $id <-- from user table in database
 * @property string $name <-- from user table in database
*/
class User extends \yii\db\ActiveRecord
{
	// Note: database table "user" does not have "x" field.
	public $x;
	public function rules()
	{
		return [['x', 'safe']];
	}
}
function test()
{
	$user = new User();
	$user->setAttributes(['x' => 123], true);
	var_dump($user->x); // 123 - correct
}
```

`ActiveRecord` example 2:  `x` is unsafe attribute (BUG !).
```PHP
/**
 * @property int $id <-- from user table in database
 * @property string $name <-- from user table in database
*/
class User extends \yii\db\ActiveRecord
{
	// Note: database table "user" does not have "x" field.
	public $x;
}
function test()
{
	$user = new User();
	$user->setAttributes(['x' => 123], false);
	var_dump($user->x); // null - INCORRECT! should have been 123 as in `Model` example 2!
}
```

The reason this bug happens is because `ActiveRecord` overrides `attributes()` method which returns only fields from database unlike `Model::attributes()` which returns fields defined in the PHP class.

| Yii version      |  2.0.8-dev
| PHP version      |  7.0.1
| Operating system |  Windows

**Comment by mdmunir** [comment]
IMO its not bug. You may override `Model::attributes()` method to change the default behavior.

```php
public function attributes()
{
    $attrs = parent::attributes();
    $attrs[] = 'x';
    return $attrs;
}
```

**Comment by PowerGamer1** [comment]
I think doing what you suggest will break some other functionality of `ActiveRecord` in places where `ActiveRecord` internally uses its version of `attributes()` for its own needs and excepts `attributes()` to return ONLY fields defined in database.

What I described IS actually a bug, because base class `Model` defines `attributes()` method to do one thing and the inherited `ActiveRecord` class overrides `attributes()` method to do a completely DIFFERENT thing.

**Comment by samdark** [comment]
As far as I remember it was done on purpose. @cebe, @qiangxue do you remember thinking process behind it?

**Comment by klimov-paul** [comment]
Inconsistency between Model attributes and ActiveRecord attributes has been discussed many times. For example, at #1967, #2893
The resolution for this matter is following: if you wish to remove this inconsitency, you should do it on your own redeclaring `attributes()` method for the particular ActiveRecord class.
