### ISSUE TITLE
A more convenient use of groupBy in ActiveRecord

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#11317]
I am not aware of such functionality in Yii2, so consider this a feature proposal.

It would be nice if we could somehow use `groupBy()` in the following or similar fashion:

```php
$averageAge = User::find()
    ->groupBy(['country'])
    ->average('age');

// Print average age of users from USA, Russia
echo $averageAge['country']['US'];
echo $averageAge['country']['RU'];
```

The example uses `average()`, but the same would apply to other aggregate functions.

The main perk is being able to somehow do this on-the-fly, *without adding properties to the ActiveRecord*.

**Comment by vercotux** [comment]
It appears you have incorrectly labelled this feature request as "question".

**Comment by klimov-paul** [comment]
You may always use `Query::asArray(true)` for this.

**Comment by vercotux** [comment]
Thank you. I was not aware of that function. However I still believe it is rather illogical that Query's aggregate functions (count,average,min,max,sum) return a single scalar value when coupled with groupBy, which is very inconsistent with standard SQL. Wouldn't it make more sense to return them as an array by default?
