### ISSUE TITLE
gii/ CRUD / Model / Database Exception /Oracle

### ISSUE THREAD

**Issue by SSiwek** [yiisoft/yii2#11329]
Hi,

please be lenient with my English. Thank you.

When I try to create a new model I get the following error:

```
Database Exception – yii\db\Exception

SQLSTATE[HY000]: General error: 942 OCIStmtExecute: ORA-00942: Tabelle oder View nicht vorhanden
 (ext\pdo_oci\oci_statement.c:148)
 The SQL being executed was: SELECT username
 FROM dba_users u
 WHERE EXISTS (
 SELECT 1
 FROM dba_objects o
 WHERE o.owner = u.username )
 AND default_tablespace not in ('SYSTEM','SYSAUX')
Error Info: Array
(
    [0] => HY000
    [1] => 942
    [2] => OCIStmtExecute: ORA-00942: Tabelle oder View nicht vorhanden
 (ext\pdo_oci\oci_statement.c:148)
)


↵ 
Caused by: PDOException 

SQLSTATE[HY000]: General error: 942 OCIStmtExecute: ORA-00942: Tabelle oder View nicht vorhanden
 (ext\pdo_oci\oci_statement.c:148)

in C:\Users\vendor\yiisoft\yii2\db\Command.php at line 840
```
This is caused by the function findSchemaNames() in ../oci/Schema.php .
My DB-Admin is not willing to give the db user I have to use the rights to read the views needed in that statement.

For what purpose there is the need to know the schemas in the DB, when I want to create a single model?

May be you can help 
Sven

**Comment by SilverFire** [comment]
It is by design. You can override this default behavior by creating your own `Schema` and `Connection` that extend `yii\db\oci\Schema` and `yii\db\Connection` respectively.

```php
namespace app\db;

class Connection extends \yii\db\Connection
{
    public function init()
    {
        $this->schemaMap['oci'] = 'app\db\oci\Schema';
    }
}
```

And define connection in your config as follows:

```php
'db' => [
   'class' => 'app\db\Connection',
   'dsn' => '...',
]
```

**Comment by SSiwek** [comment]
Hi,

very cool. That does the trick :) . 
Thank you very much.

Sven
