### ISSUE TITLE
AR find() and findOne()

### ISSUE THREAD

**Issue by berthojoris** [yiisoft/yii2#11324]
When using AR to query, as in the example
`MyModel::find()->where(['request_id' => $data->id_access])->one();` and using `findOne()` 
will produce
`SELECT * FROM tbl_ads WHERE request_id='cNLVnVxknr'`
Isn't it should query created by the AR is 
`SELECT * FROM tbl_ads WHERE request_id='cNLVnVxknr' LIMIT 1` ? To get a faster query results

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6
| Operating system | Windows

**Comment by arisk** [comment]
See #9578
