### ISSUE TITLE
Php7 errors may be not serializable

### ISSUE THREAD

**Issue by zuozp8** [yiisoft/yii2#11333]
Php7 introduced \Throwable interface that covers old \Exception and new \Error types. When \Error is thrown \yii\log\Target in formatMessage() method tries to serialize it and fails. There is already workaround to avoid serializing \Exceptions and it should be expanded to cover all \Throwable.

**Comment by cebe** [comment]
related https://github.com/yiisoft/yii2-debug/pull/100

**Comment by samdark** [comment]
@zuozp8 a stack trace of such error could be helpful.

**Comment by zuozp8** [comment]
i'll prepare fix

**Comment by samdark** [comment]
OK. Thanks!

**Comment by cebe** [comment]
@samdark at least here it should be fixed: https://github.com/yiisoft/yii2/blob/master/framework/log/Target.php#L241-L243 there are several duplicates of the same code in other log targets.

**Comment by zuozp8** [comment]
Stack trace is as following repeating over and over many times:
PHP Stack trace:
PHP   1. yii\base\ErrorHandler->handleException($exception = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/base/ErrorHandler.php:0
PHP   2. yii\log\Logger->flush($final = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/base/ErrorHandler.php:111
PHP   3. yii\log\Dispatcher->dispatch($messages = *uninitialized*, $final = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Logger.php:173
PHP   4. yii\log\Target->collect($messages = *uninitialized*, $final = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Dispatcher.php:183
PHP   5. yii\log\FileTarget->export() /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Target.php:111
PHP   6. array_map(*uninitialized*, *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/FileTarget.php:106
PHP   7. yii\log\Target->formatMessage($message = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/FileTarget.php:106
PHP   8. yii\helpers\BaseVarDumper::export($var = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Target.php:245
PHP   9. yii\helpers\BaseVarDumper::exportInternal($var = *uninitialized*, $level = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/helpers/BaseVarDumper.php:147
PHP  10. var_export(*uninitialized*, *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/helpers/BaseVarDumper.php:187
PHP Warning:  var_export does not handle circular references in /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/helpers/BaseVarDumper.php on line 187
PHP Stack trace:
PHP   1. yii\base\ErrorHandler->handleException($exception = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/base/ErrorHandler.php:0
PHP   2. yii\log\Logger->flush($final = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/base/ErrorHandler.php:111
PHP   3. yii\log\Dispatcher->dispatch($messages = *uninitialized*, $final = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Logger.php:173
PHP   4. yii\log\Target->collect($messages = *uninitialized*, $final = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Dispatcher.php:183
PHP   5. yii\log\FileTarget->export() /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Target.php:111
PHP   6. array_map(*uninitialized*, *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/FileTarget.php:106
PHP   7. yii\log\Target->formatMessage($message = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/FileTarget.php:106
PHP   8. yii\helpers\BaseVarDumper::export($var = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/log/Target.php:245
PHP   9. yii\helpers\BaseVarDumper::exportInternal($var = *uninitialized*, $level = *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/helpers/BaseVarDumper.php:147
PHP  10. var_export(*uninitialized*, *uninitialized*) /home/konrad/Pulpit/mhde/vendor/yiisoft/yii2/helpers/BaseVarDumper.php:187
