### ISSUE TITLE
GridView DataColumn and Html::a()

### ISSUE THREAD

**Issue by alkaest2002** [yiisoft/yii2#11338]
### What steps will reproduce the problem?

In a gridView I put the following Data Column

```
[   
                'headerOptions' => ['class' => 'text-center'],
                'attribute' => 'participants',
                'contentOptions' => ['class' => 'text-center'],
                'value' => function($m, $key, $index, $column) {
                    return $m->participants .' - ' .Html::a(Yii::t('session','Add'),
                        ['participant/index', 'session_id' => $m->id],
                        ['data' => ['pjax' => 0]]);
                },
                'format' => 'html'
],
```

### What is the expected result?

the link part should be (_I am not sure whether this is an exact supposition_): 

`<a href="/backend/participant/index?session_id=xxx" data-pjax="0">[aggiungi]</a>`

### What do you get instead?

the data-pjax attribute is absent

`<a href="/backend/participant/index?session_id=xxx">[aggiungi]</a>`
### Additional info

When I switch `format` from `html` to `raw`, I get the expected result.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      |  5.6.10
| Operating system | Mac OSX - El Capitan 10.11.4 MAMP Pro 3.5

**Comment by SilverFire** [comment]
Thank you for the report. It is by design. Please, check [HtmlPurifier](http://www.yiiframework.com/doc-2.0/yii-helpers-htmlpurifier.html) documentation
