### ISSUE TITLE
yii\web\Request->setHostInfo(null)

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11336]
### What steps will reproduce the problem?
Set the host info to `NULL`.
### What is the expected result?
I expect the `getHostInfo()` function to re-determine the host info.

### What do you get instead?
An empty string.

### Additional info
When configuring the request component it sometimes make sense to configure the hostinfo conditionally, for example:
````
'request' => [
    'hostInfo' => CONSOLE ? 'http://coolstuff.com' : null
]
````
In this scenario when the value is set to `NULL` because `setHostInfo` trims the value, it gets set to `'"` instead.

It's a minor change but one that makes more sense in my opinion, it never makes sense to pass in an empty string anyway since that is not a valid host name, so optionally an exception could even be thrown when setting it to an invalid hostname.

**Comment by lynicidn** [comment]
+1 also hostInfo in urlManager can set error hostInfo and not throw exception

**Comment by devypt** [comment]
@samdark pull request?

**Comment by cebe** [comment]
Fixed, thanks for reporting!

**Comment by cebe** [comment]
@devypt sorry, have not seen your comment :)

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L481

**Comment by lynicidn** [comment]
@cebe throw error if you configure request and not configure urlManager

**Comment by cebe** [comment]
which error? and where is it thrown?

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L403

https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L476

**Comment by lynicidn** [comment]
and current bug also exist in urlManager

**Comment by cebe** [comment]
could you elaborate? I do not see the problem... maybe show some code or config that causes a problem?

**Comment by cebe** [comment]
you mean the same change should be applied to UrlManager? That would make sense.

**Comment by lynicidn** [comment]
@cebe yes, need allow use null as host info in urlManager also

**Comment by cebe** [comment]
done.
