### ISSUE TITLE
ActiveRecord relations in triggers

### ISSUE THREAD

**Issue by vtatsakovich** [yiisoft/yii2#11340]
**Yii2 / PHP 5.6.10**
If you will try to use relation in trigger (like a afterSave), you will not be able to get relational object and also it will disappear for future actions with model object. 
Is it expected behaviour? 

Example:

**House model:**

```
public function getUser(){
	return $this->hasOne(User::className(), [‘id’ => ‘user_id’]);
}

```
```
$someObject = House::findOne([‘id’ => 1]);
$someObject->user; // will get user object
```

**In case of trigger:**
```
$someObject->save();

public function afterSave($insert, $changedAttributes){
	$this->user; // empty
}
```
**After trigger:**
```
$someObject->user; // also empty
```

Who can clarify this? :)

**Comment by klimov-paul** [comment]
Unable to reproduce.

**Comment by vtatsakovich** [comment]
Just realised that this reproducing in case of using Codeception and UnitTests.
