### ISSUE TITLE
Simplify setting of request content/type

### ISSUE THREAD

**Issue by kiros32** [yiisoft/yii2#11357]
Hi!
I build API app and it works with json and xml formats.
But when partners sending me data application needs to know data format.
So I asking partners to send additional header - Content-Type:application/[json|xml]

Some of my partners just can't send this header.... Or just lazy, whatever...

Is there any way to set type of input data in url?

For example: https://api.*****.com/v2/blah/add/?access-token=****&_format=json

And when the will send post data as json it will parse it properly.

I didn't find solution in google(

In API config I also have

    'components' => [
       ........
        'request' => [
            'parsers' => [
                'application/json'  => 'yii\web\JsonParser',
                'application/xml' => [
                    'class' => 'bobchengbin\Yii2XmlRequestParser\XmlRequestParser',
                    'priority' => 'tag',
                ],
            ],
        ],
        .......
    ],

Thanks!

**Comment by CedricYii** [comment]
Have look at the api doc?
http://www.yiiframework.com/doc-2.0/yii-filters-contentnegotiator.html#$formatParam-detail
=> _format=application/json

**Comment by kiros32** [comment]
Yes

The name of the GET parameter that specifies the response format

And I need to tell application about format of request data which came with POST request.

**Comment by CedricYii** [comment]
For the request part, how about extending:
http://www.yiiframework.com/doc-2.0/yii-web-request.html#getContentType%28%29-detail ?

**Comment by kiros32** [comment]
Yes , extending is always possible, but why don't implement this feature in the framework?
I don't think that I am the one who found it inconvenient.

**Comment by SilverFire** [comment]
`ContentNegotiator` is designed to set proper response format depending on request headers from client and follows RFC 2045. 
We can not accept the proposed changes to core because your use case is some kind of non-documented project-specific magic.
Yii components architecture allows you to change this default behavior in your local scope.

Thank you
