### ISSUE TITLE
after redirect  getFlash()  is null? why? 

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#11351]
### What steps will reproduce the problem?
I am is chinese people at shanghai
my yii2 versions is yii2.08-dev
i use Yii::$app->getSession()->setFlash('success', "save is success"); in siteController/addAction
than  use $this->redirect("site/index");
i use  Yii::$app->getSession()->getFlash('success');   
why??
### What is the expected result?
i want use yii\bootstrap\Alert  in layout/main.php
### What do you get instead?
 it is "NULL";
i use Yii2.0.7   it  is good;

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8-dev
| PHP version      |  5.6.19
| Operating system |  win10 professional edition

**Comment by klimov-paul** [comment]
Duplicates #9187
