### ISSUE TITLE
Wrong end query generated by framework.

### ISSUE THREAD

**Issue by jaiminmoslake7020** [yiisoft/yii2#11355]
### What steps will reproduce the problem?

This is my query.

`INSERT  INTO visualization_title ( v_text , v_align ) VALUES ( :v_text , :v_align );`

This data is inserted by foreach loop. Means dynamically 

`Array
(
    [v_text] => 'Population (millions)'
    [moslake_table_id] => 64
    [v_align] => 'high'
)`

**I have created this function for that.**

    public  function handleDynamicInserts($data)
    {
        foreach ($data as $k=>$v)
        {

            //AppBasic::printR($v , 0);

            $sql = "

              INSERT INTO `".$k."`   
                          
             ";

            $fieldString = " ( " ;
            $valueString = " ( " ;
            $count = 0 ;
            foreach ($v as $k1=>$v1)
            {
                if($k1 == "moslake_table_id")
                {
                    if(self::checkVisualizationId($v1))
                    {
                        if($count < (sizeof($v)) && $count != 0)
                        {
                            $fieldString .= "," ;
                            $valueString .= "," ;
                        }

                        $fieldString .= " `visualization_id` ";
                        $valueString .= " :".$k1." ";
                    }
                }
                else
                {
                    if($count < (sizeof($v)) && $count != 0)
                    {
                        $fieldString .= "," ;
                        $valueString .= "," ;
                    }

                    $fieldString .= " `".$k1."` ";
                    $valueString .= " :".$k1." ";

                }

                $count++;

            }
            $fieldString .= " ) " ;
            $valueString .= " );" ;

            $sql .= $fieldString."  VALUES  ".$valueString;

            //echo $sql ;
            //echo "<br/><br/>";
            $command = Yii::$app->db->createCommand($sql);

           // if($k == "visualization_dataLabels")
           // {
                AppBasic::printR($v , 0);
            //}

            foreach ($v as $k1=>$v1)
            {
                if($k1 == "moslake_table_id")
                {
                    $command->bindParam(':'.$k1.'', $v[$k1]);
                }
                else
                {
                    $command->bindParam(':'.$k1.'', $v[$k1]);
                }

               // if($k == "visualization_dataLabels")
               // {
                   // AppBasic::printR($command , 0);
               // }
            }

           // if($k == "visualization_dataLabels")
            //{
                AppBasic::printR($command , 0);
            //}

            //AppBasic::printR($command);
           // AppBasic::printRT( $command->execute() ) ;

        }

        //

    }
`

**When I print $command**

`    yii\db\Command Object
    (
    [db] => yii\db\Connection Object
        (
            [dsn] => mysql:host=192.168.1.201;dbname=opsinsights
            [username] => root
            [password] => root
            [attributes] => 
            [pdo] => PDO Object
                (
                )

            [enableSchemaCache] => 
            [schemaCacheDuration] => 3600
            [schemaCacheExclude] => Array
                (
                )

            [schemaCache] => cache
            [enableQueryCache] => 1
            [queryCacheDuration] => 3600
            [queryCache] => cache
            [charset] => utf8
            [emulatePrepare] => 
            [tablePrefix] => 
            [schemaMap] => Array
                (
                    [pgsql] => yii\db\pgsql\Schema
                    [mysqli] => yii\db\mysql\Schema
                    [mysql] => yii\db\mysql\Schema
                    [sqlite] => yii\db\sqlite\Schema
                    [sqlite2] => yii\db\sqlite\Schema
                    [sqlsrv] => yii\db\mssql\Schema
                    [oci] => yii\db\oci\Schema
                    [mssql] => yii\db\mssql\Schema
                    [dblib] => yii\db\mssql\Schema
                    [cubrid] => yii\db\cubrid\Schema
                )

            [pdoClass] => 
            [enableSavepoint] => 1
            [serverStatusCache] => cache
            [serverRetryInterval] => 600
            [enableSlaves] => 1
            [slaves] => Array
                (
                )

            [slaveConfig] => Array
                (
                )

            [masters] => Array
                (
                )

            [masterConfig] => Array
                (
                )

            [_transaction:yii\db\Connection:private] => 
            [_schema:yii\db\Connection:private] => yii\db\mysql\Schema Object
                (
                    [typeMap] => Array
                        (
                            [tinyint] => smallint
                            [bit] => integer
                            [smallint] => smallint
                            [mediumint] => integer
                            [int] => integer
                            [integer] => integer
                            [bigint] => bigint
                            [float] => float
                            [double] => double
                            [real] => float
                            [decimal] => decimal
                            [numeric] => decimal
                            [tinytext] => text
                            [mediumtext] => text
                            [longtext] => text
                            [longblob] => binary
                            [blob] => binary
                            [text] => text
                            [varchar] => string
                            [string] => string
                            [char] => string
                            [datetime] => datetime
                            [year] => date
                            [date] => date
                            [time] => time
                            [timestamp] => timestamp
                            [enum] => string
                        )

                    [db] => yii\db\Connection Object
 *RECURSION*
                    [defaultSchema] => 
                    [exceptionMap] => Array
                        (
                            [SQLSTATE[23] => yii\db\IntegrityException
                        )

                    [_schemaNames:yii\db\Schema:private] => 
                    [_tableNames:yii\db\Schema:private] => Array
                        (
                        )

                    [_tables:yii\db\Schema:private] => Array
                        (
                        )

                    [_builder:yii\db\Schema:private] => 
                )

            [_driverName:yii\db\Connection:private] => mysql
            [_slave:yii\db\Connection:private] => 
            [_queryCacheInfo:yii\db\Connection:private] => Array
                (
                )

            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => Array
                (
                )

        )

    [pdoStatement] => PDOStatement Object
        (
            [queryString] => 

              INSERT INTO `visualization_title`   
                          
              (  `v_text` , `v_align`  )   VALUES   (  :v_text , :v_align  );
        )

    [fetchMode] => 2
    [params] => Array
        (
            [:v_text] => 'Population (millions)'
            [:moslake_table_id] => 64
            [:v_align] => 'high'
        )

    [queryCacheDuration] => 
    [queryCacheDependency] => 
    [_pendingParams:yii\db\Command:private] => Array
        (
        )

    [_sql:yii\db\Command:private] => 

              INSERT INTO `visualization_title`   
                          
              (  `v_text` , `v_align`  )   VALUES   (  :v_text , :v_align  );
    [_refreshTableName:yii\db\Command:private] => 
    [_events:yii\base\Component:private] => Array
        (
        )

    [_behaviors:yii\base\Component:private] => 
)`

### What is the expected result?

Query should get executed succefully. 

### What do you get instead?

**
But when i execute query**

`
yii\db\Command Object
(
    [db] => yii\db\Connection Object
        (
            [dsn] => mysql:host=192.168.1.201;dbname=opsinsights
            [username] => root
            [password] => root
            [attributes] => 
            [pdo] => PDO Object
                (
                )

            [enableSchemaCache] => 
            [schemaCacheDuration] => 3600
            [schemaCacheExclude] => Array
                (
                )

            [schemaCache] => cache
            [enableQueryCache] => 1
            [queryCacheDuration] => 3600
            [queryCache] => cache
            [charset] => utf8
            [emulatePrepare] => 
            [tablePrefix] => 
            [schemaMap] => Array
                (
                    [pgsql] => yii\db\pgsql\Schema
                    [mysqli] => yii\db\mysql\Schema
                    [mysql] => yii\db\mysql\Schema
                    [sqlite] => yii\db\sqlite\Schema
                    [sqlite2] => yii\db\sqlite\Schema
                    [sqlsrv] => yii\db\mssql\Schema
                    [oci] => yii\db\oci\Schema
                    [mssql] => yii\db\mssql\Schema
                    [dblib] => yii\db\mssql\Schema
                    [cubrid] => yii\db\cubrid\Schema
                )

            [pdoClass] => 
            [enableSavepoint] => 1
            [serverStatusCache] => cache
            [serverRetryInterval] => 600
            [enableSlaves] => 1
            [slaves] => Array
                (
                )

            [slaveConfig] => Array
                (
                )

            [masters] => Array
                (
                )

            [masterConfig] => Array
                (
                )

            [_transaction:yii\db\Connection:private] => 
            [_schema:yii\db\Connection:private] => yii\db\mysql\Schema Object
                (
                    [typeMap] => Array
                        (
                            [tinyint] => smallint
                            [bit] => integer
                            [smallint] => smallint
                            [mediumint] => integer
                            [int] => integer
                            [integer] => integer
                            [bigint] => bigint
                            [float] => float
                            [double] => double
                            [real] => float
                            [decimal] => decimal
                            [numeric] => decimal
                            [tinytext] => text
                            [mediumtext] => text
                            [longtext] => text
                            [longblob] => binary
                            [blob] => binary
                            [text] => text
                            [varchar] => string
                            [string] => string
                            [char] => string
                            [datetime] => datetime
                            [year] => date
                            [date] => date
                            [time] => time
                
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
The SQL being executed was: 

              INSERT INTO `visualization_title`   
                          
              (  `v_text` , `v_align`  )   VALUES   (  '\'Population (millions)\'' , '\'high\''  );' 

in C:\xampp\htdocs\dev\ops-insights\_protected\vendor\yiisoft\yii2\db\Schema.php:628

Stack trace:
#0 C:\xampp\htdocs\dev\ops-insights\_protected\vendor\yiisoft\yii2\db\Command.php(792): yii\db\Schema->convertException(Object(PDOException), '????           ...')
#1 C:\xampp\htdocs\dev\ops-insights\_protected\common\components\FrontEndHelper.php(896): yii\db\Command->execute()
#2 C:\xampp\htdocs\dev\ops-insights\_protected\backend\controllers\ReportController.php(751): common\components\FrontEndHelper->handleDynamicInserts(Array)
#3 [internal function]: backend\controllers\ReportController->actionChartCreate()
#4 C:\xampp\htdocs\dev\ops-insights\_protected\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\dev\ops-insights\_protected\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\dev\ops-insights\_protected\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('chart-create', Array)
#7 C:\xampp\htdocs\dev\ops-insights\_protected\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('report/chart-cr...', Array)
#8 C:\xampp\htdocs\dev\ops-insights\_protected\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 C:\xampp\htdocs\dev\ops-insights\backend\index.php(18): yii\base\Application->run()
#10 {main}
`

### Additional info
**
My $data array**

`Array
(
    [visualization_chart] => Array
        (
            [v_type] => 'bar'
            [moslake_table_id] => 1
        )

    [visualization_credits] => Array
        (
            [v_enabled] => false
            [moslake_table_id] => 11
        )

    [visualization_legend] => Array
        (
            [v_x] => -40
            [moslake_table_id] => 20
            [v_verticalAlign] => 'top'
            [v_shadow] => true
            [v_layout] => 'vertical'
            [v_floating] => true
            [v_backgroundColor] => ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF')
            [v_align] => 'right'
            [v_y] => 80
        )

    [visualization_title] => Array
        (
            [v_text] => 'Population (millions)'
            [moslake_table_id] => 64
            [v_align] => 'high'
        )

    [visualization_subtitle] => Array
        (
            [v_text] => 'Source: Wikipedia.org'
            [moslake_table_id] => 31
        )

    [visualization_dataLabels] => Array
        (
            [v_enabled] => true
            [moslake_table_id] => 33
        )

    [visualization_tooltip] => Array
        (
            [v_valueSuffix] => ' millions'
            [moslake_table_id] => 39
        )

    [visualization_xAxis] => Array
        (
            [v_categories] => ['Africa', 'America', 'Asia', 'Europe', 'Oceania']
            [moslake_table_id] => 44
        )

    [visualization_yAxis] => Array
        (
            [v_min] => 0
            [moslake_table_id] => 50
        )

    [visualization_labels] => Array
        (
            [v_overflow] => 'justify'
            [moslake_table_id] => 63
        )

)`

| Q                | A
| ---------------- | ---
| Yii version      | 
| PHP version      | 
| Operating system |

**Comment by SilverFire** [comment]
:scream: This problem belongs to your function, not to Yii
