### ISSUE TITLE
Model validate some attribute error

### ISSUE THREAD

**Issue by dcb9** [yiisoft/yii2#11368]
### What steps will reproduce the problem?

I have two scripts:

```php
<?php

namespace idarex\pingppyii2;

class OrderForm extends \yii\base\Model
{
    public $order_no;
    public $subject;

    public function rules()
    {
        return [
            [['order_no', 'subject'], 'required'],
        ];
    }
}
```

```php
<?php

class OrderFormTest extends PHPUnit_Framework_TestCase
{
    public function testValidate()
    {
        $form = new \idarex\pingppyii2\OrderForm();
        $form->order_no = '1234';
        $this->assertTrue($form->validate('order_no'), 'order_no is not empty');
    }
}
```

And runs `phpunit tests/OrderFormTest.php`

### What is the expected result?

```
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

.

Time: 58 ms, Memory: 6.25Mb

OK (1 test, 1 assertion)
```

### What do you get instead?

```
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

F

Time: 62 ms, Memory: 6.25Mb

There was 1 failure:

1) OrderFormTest::testValidate
order_no is not empty
Failed asserting that false is true.

/Users/bob/Documents/idarex/pingpp-yii2/tests/OrderFormTest.php:11
/Users/bob/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:149
/Users/bob/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:100

FAILURES!
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | PHP 5.5.30 (cli)
| Operating system | OS X 10.11.3 (15D21)

**Comment by mdmunir** [comment]
how about
```php
$this->assertTrue($form->validate(['order_no']), 'order_no is not empty');
```

**Comment by lynicidn** [comment]
брехня, код выложен не весь
```php
oknimdy@debian:~/www/yii2$ vendor/bin/phpunit tests/framework/base/PingTest.php 
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /home/oknimdy/www/yii2/phpunit.xml.dist

.

Time: 64 ms, Memory: 3.25Mb

OK (1 test, 1 assertion)
```
for code
```php
<?php
namespace yiiunit\framework\base;

use yii\base\Model;
use yiiunit\TestCase;

class PingTest extends TestCase
{
    public function testPing()
    {
        $ping = new Ping();
        $ping->require = 'req';
        $this->assertTrue($ping->validate('require'));
    }
}

class Ping extends Model
{
    public $require;

    public function rules()
    {
        return [
            [['require'], 'required'],
        ];
    }
}
```

**Comment by dcb9** [comment]
@mdmunir Thanks a lot, it works. It seems I should learn more about Yii2 internal source code.

@lynicidn Hey, I had two required property. You can  reproduce the problem: add one more property, and add required rule for it.

**Comment by lynicidn** [comment]
ну да, глупо было писать так https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L240

там если не массив передан, то уже идет валидация всех аттрибутов перечисленных в валидаторе - это баг

**Comment by dcb9** [comment]
@lynicidn I can't read what you said. but I can understood the code. Thank you!

**Comment by lynicidn** [comment]
@dcb9 am write for russian coders, reopen please issue, may be fixed it

**Comment by SilverFire** [comment]
It's not a bug because behavior is tested and documented, but it can be improved to support string, if nobody minds. @yiisoft/core-developers

**Comment by klimov-paul** [comment]
My opinion: it does not make sense.

**Comment by lynicidn** [comment]
hm, need prepare attributes to array or throw exception

по русски - должно быть строгое приведение к ожидаемому типу или же выброшено исключение. Скрытая непредсказуемая неожидаемая логика - это и есть баг :)

**Comment by klimov-paul** [comment]
Disagreed: method argument type is documented as `array`. If we will perform explicit check for the type match for each argument of each method around the framework it will produce significant performance impact.
There are many similar places around the core code.

**Comment by lynicidn** [comment]
@klimov-paul `string` not documented, only empty (null) in doc

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/pull/11376

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L328

Says:

> @param array $attributeNames list of attribute names that should be validated.

What is uncrear?

**Comment by lynicidn** [comment]
@klimov-paul read next
>     * If this parameter is empty, it means any attribute listed in the applicable
     * validation rules should be validated.

**Comment by lynicidn** [comment]
what is behavior if is string ? exception? null? what?

**Comment by SilverFire** [comment]
@klimov-paul I'm unsure here, because somewhere we cast string to array and somewhere not. 
For example: 

https://github.com/yiisoft/yii2/blob/master/framework/caching/TagDependency.php#L43
https://github.com/yiisoft/yii2/blob/master/framework/behaviors/SluggableBehavior.php#L137
https://github.com/yiisoft/yii2/blob/master/framework/i18n/I18N.php#L107
... and so on

I'd like to see more opinions from @yiisoft/core-developers

**Comment by samdark** [comment]
It's currently documented and tested that it accepts array. I don't think it's a good idea to allow passing scalar to `$model->validate()`.
