### ISSUE TITLE
Does "punycode:1.4.*" not meet yii2 requirements?

### ISSUE THREAD

**Issue by vistart** [yiisoft/yii2#11364]
### What steps will reproduce the problem?

Use punycode 1.4.* or later version:
```
"bower-asset/punycode": "^1.4.0",
```

then update the project, the composer will output the problem:
```
yiisoft/yii2 2.0.7 requires bower-asset/punycode 1.3.* -> satisfiable by bower-asset/punycode[v1.3.2]
```

Does punycode 1.4.* not meet yii2 requirements?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6.20
| Operating system | Windows 10

**Comment by vistart** [comment]
@samdark 
Would you consider the jquery:1.12.*@stable ?

**Comment by samdark** [comment]
Probably yes.

**Comment by cebe** [comment]
https://github.com/jquery/jquery/tree/1.12.0 has no bower.json?

**Comment by cebe** [comment]
okay, seems bower points to another repo... https://github.com/jquery/jquery/pull/2706#issuecomment-155823857
