### ISSUE TITLE
$cookies not been set when return image data stream

### ISSUE THREAD

**Issue by lusnaow** [yiisoft/yii2#11374]
### What steps will reproduce the problem?

```php
    public function actionTest(){
        $cookies = \Yii::$app->response->cookies;
        $cookies->add(new \yii\web\Cookie([
            'name' => 'authnum_session',
            'value' => '1234',
        ]));
        header('Content-type:image/png');
        imagepng($this->img);
    }
```

Get.Https.
Get image properly,but no cookie.
### What is the expected result?
$cookies should be set
### What do you get instead?
setcookie("authnum_session","1234"); worked.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version    |  2.0.7
| PHP version     | 5.5.7 
| Operating system |  Ubuntu 12.04.1 LTS X86_64

**Comment by Alex-Code** [comment]
How are you checking for cookies clientside?

**Comment by lusnaow** [comment]
I check it with Developer Tools of Chrome and Postman.Same result.

**Comment by samdark** [comment]
You're mixing direct headers and output with Yii's delayed headers and output. That's why. Use `Yii::$app->response`.

**Comment by lusnaow** [comment]
So Yii can not be used as a tool to develop APIs for mobile Apps?

**Comment by tunecino** [comment]
@lusnaow what @samdark is saying is that you are doing it wrong. here you'll find how to set data to headers in Yii: http://www.yiiframework.com/doc-2.0/guide-runtime-responses.html

**Comment by Alex-Code** [comment]
http://www.yiiframework.com/doc-2.0/guide-runtime-responses.html#response-body

From memory, may or may not work.
```php
$headers = Yii::$app->response->headers;
$headers->add('Content-type', 'image/png');

$response = Yii::$app->response;
$response->format = \yii\web\Response::FORMAT_RAW;

ob_start();
imagepng($image);
return ob_get_clean();
```
