### ISSUE TITLE
Duplicate content when use catchAll on beforeRequest in application config

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#11371]
### What steps will reproduce the problem?

This case use advanced project template (fresh install)

frontend/config/main.php
```php
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    ...
	'on beforeRequest' => function () {
		\Yii::$app->catchAll = [
			'site/maintenance'
		];
    },
   ...
];

```

SiteController.php
```php
...
public function actionMaintenance() {
        return $this->render('maintenance');
}
...
```

### What is the expected result?

Not duplicate content rendering

### What do you get instead?

![my yii application 2016-04-17 20-27-39](https://cloud.githubusercontent.com/assets/8703419/14587277/dd804d24-04da-11e6-9f9e-acdb8b649ad8.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      | 5.6.15
| Operating system | Windows 7

**Comment by mdmunir** [comment]
are you sure its because `\Yii::$app->catchAll`?
remark your code then execute.
```php
'on beforeRequest' => function () {
//        \Yii::$app->catchAll = [
//            'site/maintenance'
//        ];
    },
```

**Comment by adiramardiani** [comment]
Yes sure sir, without `\Yii::$app->catchAll` application is working without duplicate
```php
'on beforeRequest' => function () {
		/*\Yii::$app->catchAll = [
			'site/maintenance'
		];*/
    },
```
result : 
![my yii application](https://cloud.githubusercontent.com/assets/8703419/14590657/88215742-052a-11e6-9134-5a3ec94c8ab6.png)

With `\Yii::$app->catchAll ` :
```php
'on beforeRequest' => function () {
		\Yii::$app->catchAll = [
			'site/maintenance'
		];
    },
```

result :
![my yii application 2016-04-17 20-27-39](https://cloud.githubusercontent.com/assets/8703419/14590661/a2dda68a-052a-11e6-9cd2-d8d4d56e6388.png)

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/5982

**Comment by adiramardiani** [comment]
I see, this is debugger issue, i hope this is can fixed
Thanks
