### ISSUE TITLE
Documentation for attributeLabels() in class yii\base\Model is ambiguous.

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii2#11372]
Currently yii\base\Model has the following implementation of attributeLabels():

    public function attributeLabels()
    {
        return [];
    }

However comments for that function as well as documentation (http://www.yiiframework.com/doc-2.0/yii-base-model.html#attributeLabels()-detail) says:
"By default an attribute label is generated using generateAttributeLabel()"

I think it should be corrected to say something like this: "By default this function returns an empty array. If you want to overload this function then you can use generateAttributeLabel()."

I am not sure why not to add implementation right into Model class:

    public function attributeLabels()
    {
        $attributeLabelList = [];
        foreach($this->attributes() as $attribute)
        {
            $attributeLabelList[$attribute] = 
                $this->generateAttributeLabel($attribute);
        }
        
        return $attributeLabelList;
    }

Actually as I see Gii uses more complicated algorithm to generate labels (it converts 'id' into 'ID' whereas generateAttributeLabel() converts it into 'Id'). Again, why wouldn't make it consistent?

Yii version 2.0.6.

File 'Model.php' (latest commit on Mar 22, 2016):
https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L287

**Comment by samdark** [comment]
Documentation is correct. If the label is in the array returned from `attributeLabels`, exactly what's returned is used. Otherwise, it's generated.

**Comment by vitalyspirin** [comment]
Probably I misunderstand something. If I use default implementation of attributeLabels() then I get empty array. It's not generated. Gii creates a model that overloads that function hard-coding array of labels.

**Comment by samdark** [comment]
Yes. That's how it's supposed to work.
