### ISSUE TITLE
Allowed query strings in urlManager with enablePrettyUrl

### ISSUE THREAD

**Issue by rtwent** [yiisoft/yii2#11375]
Configuration of urlManager:

```php
'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'suffix' => '/',
            'rules' => [
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ],
        ],
```

The link http://localhost.com/result/ will provide page with results of some application. When we speak about duplicate content for SEO purposes the page http://localhost.com/result/?query=bla-bla will provide us the same result as http://localhost.com/result/ (response code and content). It is not correct.

Is it possible to make UrlManager configurable for allowed query strings when enablePrettyUrl = true
E.g. when links like http://localhost.com/result/?query=bla-bla will not find route and return response with code 404 (because they are really absent), while http://localhost.com/result/?page=2 will return the second page of some content.

It will be the good possibility to do this with a help of UrlManager, but not with a help of Controllers (or webserver settings) or workarounds like meta canonical and meta noindex in view files.

**Comment by samdark** [comment]
Have you tried enabling strict parsing?

**Comment by rtwent** [comment]
`'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => true,
            'suffix' => '/',
            'rules' => [
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ],
        ],`

Expecting:
http://localhost.com/result/index/ to get 200
http://localhost.com/result/index/?query=bla-bla to get 404

Having:
http://localhost.com/result/index/ getting 200
http://localhost.com/result/index/?query=bla-bla getting 200

How is it possible to set query string in url rules?
neither
`<controller:\w+>/<action:\w+>/\\?query=test' => '<controller>/<action>`
nor
`<controller:\w+>/<action:\w+>/\?query=test' => '<controller>/<action>`
`<controller:\w+>/<action:\w+>/?query=test' => '<controller>/<action>`
working for me.

**Comment by TerraSkye** [comment]
shouldnt this logic be executed in a controller filter?

**Comment by samdark** [comment]
> How is it possible to set query string in url rules?

It's not possible.

**Comment by rtwent** [comment]
Excuse me for my bad idea. I think @TerraSkye is right. The place for doing this job is in the controller. Here some reasons to close this issue: 

1. There would be a lot of configuration details, e.g. pjax, sort, page. So, configuration array will become more fat (hard to read). 
2. These configurations of query strings could be the same in different controllers. Such types of tasks are better to solve by behaviours or inheritance or beforeInit().
3. No one from my colleagues that use laravel or symphony does not think about it. Their frameworks does not provide such functionality.

**Comment by kidol** [comment]
@rtwent Just set a canoncial url if you want to make sure Google & Co. index the correct/unique url's: https://support.google.com/webmasters/answer/139066?hl=en

Yii has some limited support for it: http://www.yiiframework.com/doc-2.0/yii-helpers-baseurl.html#canonical%28%29-detail

So try this in controller:

```php
$this->view->registerLinkTag(['rel' => 'canonical', 'href' => yii\helpers\Url::canonical()]);
```

I guess you also have to add `$page` param to action signature if you want Google to index url's containing `?page=x`:

```php
public function actionIndex($page = 1)
```
