### ISSUE TITLE
Flyweight pattern for specific AR models.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11388]
In some cases the number of rows in a table is severely limited. In such a scenario it might be more efficient to use the flyweight pattern.

Consider: 
1. There is a `Post` entity, many exist.
2. Each `Post` belongs to an `Author`, of which only 20 exist.

Getting 1000 posts with their authors will generated 2000 AR models, considering there are only 20 authors, each author will be represented by approximately 50 duplicate AR objects.

If we use the flyweight pattern, instead of 2000 there will be 1020 AR models (1000 posts + 20 authors).

There are some up and downsides to this approach, therefore I think it should always be opt-in.

What do you guys think?

**Comment by klimov-paul** [comment]
It is already so, in case you are using `ActiveQuery::with('author')`.

**Comment by SamMousa** [comment]
Reusing the object is not the same as applying the flyweight pattern.
The pattern if applied properly would work across multiple (unrelated) queries as well.

**Comment by klimov-paul** [comment]
I see no reason for supporting this, since there is already a mechanism, which allows related object reusage.
The possible benefit does not worth the effots.

**Comment by cebe** [comment]
if you want to have this in your application, you can override instantiate method in a base AR class.

**Comment by SamMousa** [comment]
I know, just wanted to check if this is something that is desirable in Yii core ;-) apparently it's not so I'll use my own implementation!

**Comment by lynicidn** [comment]
@SamMousa u confused pattern - Identity Map

**Comment by SamMousa** [comment]
No, I mean flyweight pattern. In this case could be a combination of both though. My goal is memory usage reduction, identity map does query time reduction; depending on implementation it could be combined though

**Comment by lynicidn** [comment]
> identity map does query time reduction;
no, identity map create only unique objects, but query is full (not optimize query)

**Comment by SamMousa** [comment]
https://en.wikipedia.org/wiki/Identity_map_pattern

--> It skips the query altogether reducing query time for a request.

https://en.wikipedia.org/wiki/Flyweight_pattern

Note that these patterns are not mutually exclusive and both make sense for my original post. ^^

**Comment by lynicidn** [comment]
@SamMousa 

>Note that these patterns are not mutually exclusive and both make sense for my original post. ^^

now this
