### ISSUE TITLE
GridView summary totalCount is not formatted in v.2.0.7. Incorrect thousands separator.

### ISSUE THREAD

**Issue by shum16** [yiisoft/yii2#11386]
### What steps will reproduce the problem?
Render GridView with totalCount >= 1000.

### What is the expected result?
Summary text: "Showing records 1-50 of 26 019".

### What do you get instead?
Summary text: "Showing records 1-50 of 26,019" (Показаны записи 1-50 из 26,019).

### Additional info
There used to be a correct separator in v.2.0.4 before I updated to v.2.0.7.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      | 5.5.9
| Operating system | Any
| Language | RU

**Comment by samdark** [comment]
What's `Yii::$app->language` set to?

**Comment by shum16** [comment]
I've got `'language' => 'ru'` in config file.

**Comment by samdark** [comment]
Could you try with `ru_RU`?

**Comment by shum16** [comment]
this doesn't help.

**Comment by samdark** [comment]
Which ICU data version do you have? Which intl version?

**Comment by shum16** [comment]
Thanks a lot, Alexander! I've installed php5-intl and now I have a proper separator!
