### ISSUE TITLE
Suggetion about event.

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#11389]
Reopen old issue #3243. Maybe for 2.1

Event as jquery like
### 1. Trigger event using `name` or `object` (break BC? yes/no).

Currently, to send event object, it must be as as second parameter of `trigger()`. But, event object itself contain name property. Better first parameter can be event name or event object.

``` php
// use
Yii::$app->trigger('myEvent');
// or use
$myEvent = new Event('myEvent');
Yii::$app->trigger($myEvent);
```
### 2. Use `return false;` or `$event->stopPropagation()` to stop handling (break BC? no).

Currently to stop event handling we use `$event->handled = true`. Prefer using `return false`. 

``` php
Yii::$app->on('myEvent', function($event){
    //...
    if ($condition){
        return false;
        // or $event->stopPropagation();
        // instead of $event->handled = true;
    }
});

Yii::$app->trigger('myEvent');
```
### 3. Add extra parameter when trigger event (break BC? no).

``` php
Yii::$app->on('myEvent', function($event, $param1, $param2){
    // do with $param1 and $param2
});

Yii::$app->trigger('myEvent',['param1', 'param2']);
```

**Comment by samdark** [comment]
There's going to be an event manager PSR in the works soon: https://groups.google.com/forum/#!topic/php-fig/MFL__YvumkE

**Comment by samdark** [comment]
Here: https://github.com/bretterer/fig-standards/blob/event-manager/proposed/event-manager.md

It totally makes sense so I'd adopt it.

**Comment by mdmunir** [comment]
hmm... What `target` actually is? What different with `sender`? If event only triggered from Event Manager, i am affraid we must adopt namespace.

**Comment by samdark** [comment]
It doesn't force you to name events in any certain way but yes, I guess it would lead to names like `namespace.eventName`. Target serves the same purpose as sender. You can see targets in JavaScript DOM events everywhere. Usually it is what triggered the event.

**Comment by mojifan** [comment]
@mdmunir I like this way ，Laravel's event is implemented
