### ISSUE TITLE
Accessors & Mutators

### ISSUE THREAD

**Issue by ShNURoK42** [yiisoft/yii2#11382]
Спрошу на русском, я видел тут так делают, мне будет проще.
Я уже создавал подобный тикет, но его закрыли сославшись на https://github.com/yiisoft/yii2/issues/9656 однако как я понял оттуда, там немного не об этом и его откатили.

Скажите можно добавить аналог https://laravel.com/docs/5.2/eloquent-mutators#accessors-and-mutators
Чтобы через `$model->name` вызывать `$model->getNameAttribute` в первую очередь, понимаю, что это сахар и можно писать `$model->nameAttribute`, но думаю первый вариант логичней.
В общем хотелось бы еще раз услышать за и против, или может я чего упустил и так сделать нельзя?
Спасибо.

**Comment by ShNURoK42** [comment]
@klimov-paul в каком месте это вопрос? На форуме я эту тему тоже поднимал, но сослались на закрытый тикет. Хотя это не то. На форуме тоже не густо http://yiiframework.ru/forum/viewtopic.php?f=27&t=33288

С "уходом" @qiangxue и редкими визитами @cebe я так понимаю сейчас основное это пилить виджеты?

**Comment by klimov-paul** [comment]
```php
public function getUsername()
{
    return $this->username;
}
```

Сделать getter для `username` приоритетнее атрибута попросту не выйдет: либо будет бесконечная рекурсия, либо просто исчезнет возможность обратиться с "сырому" атрибуту из вне.

Ваш вопрос обсуждался уже много раз в разных местах - там несколько страниц объяснений почему мы так не делаем. С тем чтобы их прочитать - я вам помочь не могу - обратитесь к другому специалисту.

**Comment by ShNURoK42** [comment]
@klimov-paul в laravel как раз и реализован "хук", чтобы отключить свойство, а по поводу возможности обратиться к "сырому" атрибуту вообще не понял, как вы тогда обращаетесь к "сырому" атрибуту в наследниках, ну того же `Object`, в котором у геттера приоритет выше?

**Comment by SilverFire** [comment]
> как вы тогда обращаетесь к "сырому" атрибуту в наследниках, ну того же Object, в котором у геттера приоритет выше?

Аттрибут называем с подчеркиванием.

```php

class Foo
{
    protected $_secret;

    public function getSecret()
    {
        return $this->_secret;
    }

    public function setSecret($secret)
    {
        $this->_secret = md5($secret);
    }
}

**Comment by SilverFire** [comment]
Единственный вариант, как я могу себе представить реализацию - это добавить метод вроде `getRawAttribute($attribute)`, который будет доставать данные только из `$_attributes`, минуя геттеры. Но тогда для записи в БД нужно юзать `getRawAttributes()` вместо нынешнего `getAttributes()`, а это - хороший слом обратной совместимости.

Если у вас есть идеи, как можно это сделать так, чтобы и волки были сыти, и овцы целы - поделитесь, пожалуйста.

**Comment by ShNURoK42** [comment]
@SilverFire про обратную совместимость не знаю что и как, поэтому и спрашиваю.

Я вроде и понял вас, а вроде и нет. Если не затруднит давайте начнем сначала.
1. Мы добавляем возможность создания геттера/сеттера, который не работает со "своим" виртуальным свойством.
2. При обращении к `getAttribute()` также пропускаем через этот геттер, при обращении к `setAttribute($name)` пропускаем через сеттер. Получается мы массив `$_attributes` не изменяем, но так мы не получим сырое свойство. Для этого можно ввести `getRawAttribute($attribute)`, которое обходит геттер и берет данные напрямую в `$_attributes`.

Я не понял, зачем для записи использовать `getRawAttributes()`?
