### ISSUE TITLE
Oracle (oci) charset not respected 

### ISSUE THREAD

**Issue by SSiwek** [yiisoft/yii2#11387]
Hi,

please be lenient with my English. Thank you.

I connect to an Oralce Instance wich is not in charset utf8.

I dont get the correct chars for the German special chars ÄÖÜ ...

I tried to give the "charset Attribut" but it is not respected in connecton.php .

I inspected the source and found a good place to add that 
With my modification I get the German Umlaute.

connection.php in function createPdoInstance()

I added the part with oci.

[...]
```php
            if (isset($driver)) {
                if ($driver === 'mssql' || $driver === 'dblib') {
                    $pdoClass = 'yii\db\mssql\PDO';
                } elseif ($driver === 'sqlsrv') {
                    $pdoClass = 'yii\db\mssql\SqlsrvPDO';
                }
                if ($driver==='oci' && $this->charset !== null ){
                	$this->dsn .= ";charset=".$this->charset;
                }
            }
```

I think, that it can be added to the source...

thank you
Sven

**Comment by samdark** [comment]
@SSiwek do you have time to work on a pull request?

**Comment by SSiwek** [comment]
I havent done that before.
I have read some docu now and I am unsure how to create a branch to put my modification in. I installed yii2 via composer only....

Sven

**Comment by samdark** [comment]
Well, here's the guide: https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md If it's too much for you at this stage, let us know so others would be able to work on it.

**Comment by SSiwek** [comment]
Hi,
I have done the "Prepare your development enviroment" Part of git-workflow.md
Now I am on "Working on bugs and featrures" 
Points 1 to 4 are done. 
Now I am stuck on "5. Update Changelog".  I dont have a number "enh #999:"  and my version of the file CHANGELOG is missing the Section "Work in progress"
Maybe I have done something wrong? I work with Egit/Eclipse

**Comment by samdark** [comment]
1. You need a fresh code from upstream.
2. The number for changelog is a number of issue. In this case it's `#11387`.

**Comment by SSiwek** [comment]
Hi,
I deleted all lokal files and starteted all over. I have done all steps from git-workflow.md.
I still dont have "Work in progress" in CHANGELOG. I am giving up.
Sven

**Comment by cebe** [comment]
it's actually `2.0.8 under development`, no need to be so strict about the changelog, concentrate on the code, we can fix the rest ourselfs :)

**Comment by cebe** [comment]
fixed the guide https://github.com/yiisoft/yii2/commit/b9315c265a308ad17d34f834865e8a8ffbfce2f7

**Comment by cebe** [comment]
As the documentation of $charset already says it only works for mysql, sqlite and pgsql, I added a not about this that the configuration should be applied directly in the dsn instead of doing it magically internally. Thanks for the PR anyway!
