### ISSUE TITLE
middle/right clicking links that should go through handleAction()

### ISSUE THREAD

**Issue by zuozp8** [yiisoft/yii2#11384]
### What steps will reproduce the problem?
Create link like
```php
echo Html::a('submit', ['site/foobar'], [
     'data' => [
        'method' => 'post',
        'params' => [
            'name1' => 'value1',
            'name2' => 'value2',
        ],
    ],
]);
```
Click that link with middle mouse button or click with right button → open in new tab
### What is the expected result?
Nothing should happen.
### What do you get instead?
this link opens in new tab with GET request without extra params, this often caused errors like 404 or 405

**Comment by SilverFire** [comment]
See #11385
