### ISSUE TITLE
Model rules "number" or "integer" client side validation

### ISSUE THREAD

**Issue by berthojoris** [yiisoft/yii2#11394]
### What steps will reproduce the problem?
When I set my rules on model
`[['current_salary', 'phone', 'mobile'], 'number'],`
Client side validation running as well, but I found a little bit strange. If I enter `+` character in front of the numbers, client side validation is pass. Likewise with `integer` validation 

### What is the expected result?
The word `number` to validation if it can match the `+` character in front of the numbers? Does it not seem odd at usage rules? What if the name is replaced with `mobileformat` validation or something closer to his function/name if you want to validate the format of telephone numbers to accept `+` character in front of the numbers. Should not validate `number` only permits the use of numbers from 0-9?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6
| Operating system | Windows

**Comment by cebe** [comment]
`+` and `-` are allowed for indicating positive and negative numbers.
Here is the regex pattern that checks it: https://github.com/yiisoft/yii2/blob/6f7f9ea4e56bda185b6017202a25d3d99ff99192/framework/validators/NumberValidator.php#L51 you can adjust that if you do not want to allow +.
