### ISSUE TITLE
Query & ActiveRecord wronlgy place ` on column name

### ISSUE THREAD

**Issue by bobonov** [yiisoft/yii2#11391]
### What steps will reproduce the problem?
I face this issue with mysql driver, didn't test with other even if I think that is strctly related to this since column quoting is on db level.

$list = StrutturaAllegati::find()->select('concat(pathFile, filename) as file')->all();
$list = (new \yii\db\Query())->select('concat(pathFile, filename) as file')->from('struttura_allegati')->all();

### What is the expected result?
I expect a query like the following (if the expected behavior is to quote columns name)
SELECT concat(\`pathFile\`, \`filename\`) as \`file\` FROM \`struttura_allegati\`

### What do you get instead?
Both the command produce wrong sql by placing \` in wrong position for the last term of concat putting \` after parenthesis, and it does not quote the first column
This is the wrong sql by the error message:
The SQL being executed was: SELECT concat(pathFile, \`filename)\` AS \`file\` FROM \'struttura_allegati\'

**Note**
Passing the select argument as an array produce a working query but without quoting columns
SELECT concat(pathFile, filename) as file FROM \`struttura_allegati\`
Don't know if this is correct since I'm not sure if the correct behavior is to quote columns when they are part of a db function.

### Additional info
Yii 2.0.7
PHP 5.6.11
Kubuntu 15.10
Mysql driver with MariaDB 10.0.23

**Comment by klimov-paul** [comment]
Duplicates #8276
