### ISSUE TITLE
Issue with restfull , json response and numeric data

### ISSUE THREAD

**Issue by matias-yii** [yiisoft/yii2#11399]
### What steps will reproduce the problem?
use restcontroller 
create an action
inside that action add;
query some data with $query->queryAll() 
return data
call this rest with a client and get response as json
### What is the expected result?
{'value1'=>1,'value2'=>2,'value3'=>3}
### What do you get instead?
The number should be numbers instead of strings
{'value1'=>'1','value2'=>'2','value3'=>'3'}

### Additional info
json_encode should  use JSON_NUMERIC_CHECK on options to avoid this.

| Q                | A
| ---------------- | ---
| Yii version      | 2
| PHP version      |  
| Operating system |

**Comment by lisps** [comment]
maybe this is related to this entry http://stackoverflow.com/questions/5094312/unsigned-ints-with-json-decode-in-php

**Comment by cebe** [comment]
This is expected because PDO returns all data as strings. ActiveRecord will convert integer columns to integer, so you have to use AR layer if you want the conversion.

Alternatively you can configure `JsonResponseFormatter::$encodeOptions` to include the `JSON_NUMERIC_CHECK` option.
