### ISSUE TITLE
Dependency Injection issue

### ISSUE THREAD

**Issue by KasianenkoMykhailo** [yiisoft/yii2#11396]
### What steps will reproduce the problem?

I am registering dependency injection in entry script 

```php
Yii::$container->setSingleton(
    'yii\redis\Connection',
    'app\components\MyCustomConnection',
    [
        'hostname' => 'myhost',
        'port'     => 7777,
        'database' => 5,
    ]
);
```

that in code, when I am trying to get object from the container:

with any of these ways
 
1) 
```php
class SomeClass  {
private $redis;
    public function __construct(\yii\redis\Connection $redis) {
        $this->redis = $redis;
    }
}
```

2) 
```php
class SomeOtherClass {
    public function someAction() {
       $redis = Yii::$container->get('\yii\redis\Connection')
    }
}
```

3)
```php
$application = new yii\console\Application(
[
 'components' => [
       'redis' => '\yii\redis\Connection'
    ]
]
);
```

I got empty array in the instance of app\components\MyCustomConnection,
which I registred with Yii::$container->set

### What is the expected result?

I expect to get     [
        'hostname' => 'myhost',
        'port'     => 7777,
        'database' => 5,
    ]

in app\components\MyCustomConnection::__constructor($config = []) {
     \\ here $config is empty :(
     parent::__construct($config);
}

### What do you get instead?
Instead I got empty array in constructor

### Additional info

I see it happends in 

\yii\di\Container
```php
protected function build($class, $params, $config) {
         \\ at this point
         \\ $params = [ 'hostname' => 'myhost','port'=> 7777,'database' => 5 ];
         \\ $config = []
        list ($reflection, $dependencies) = $this->getDependencies($class);
        \\ $dependency = [ 0=>[] ]

       \\ here seems, that $dependency is mixing $params, and $config 
        foreach ($params as $index => $param) {
            $dependencies[$index] = $param;
        }

       \\ here we have $dependency = [0=>[], 'hostname' => 'myhost','port'=> 7777,'database' => 5]

        $dependencies = $this->resolveDependencies($dependencies, $reflection);

       \\ after resolving dependency does not changed an still [0=>[], 'hostname' => 'myhost','port'=> 7777,'database' => 5]
    
           if (empty($config)) {
           \\ here looks like 4 params passed to constructor
           \\ new app\components\MyCustomConnection([], 'myhost', 7777, 5);
           \\ Bu I guess should be  new app\components\MyCustomConnection(['myhost', 7777, 5]);
            return $reflection->newInstanceArgs($dependencies);

          \\ So I sugest to instead of
            foreach ($params as $index => $param) {
                $dependencies[$index] = $param;
            }
         \\ do
         if ([] === $config) {
            $config = $params;
            $dependencies = $this->resolveDependencies($dependencies, $reflection);
            return $reflection->newInstanceArgs($dependencies);
         }
         
        }

}
```

| Q                         | A
| ----------------        | ---
| Yii version            |  2.0.7
| PHP version         |  5.6
| Operating system |  Debian 8

**Comment by mdmunir** [comment]
how about
```php
Yii::$container->setSingleton('yii\redis\Connection',[
    'class' => 'app\components\MyCustomConnection',
    'hostname' => 'myhost',
    'port'     => 7777,
    'database' => 5,
]);
```

**Comment by KasianenkoMykhailo** [comment]
Even more strange, thing is, even if I declare my CustomClass __constructor() args
like
class MyCustomConnection extends \yii\redis\Connection
{
     public $hostname;
     public $port;
     public $database;
    
    public function __construct(array $config = [], $hostname, $port, $database)
    {
        $this->hostname = $hostname;
        $this->port = $port;
        $this->database = $database;

        parent::__construct($config);
    }
}


that, what I have in Container::build($class, $params, $config) {

        // $params = [ 'hostname' => 'myhost','port'=> 7777,'database' => 5 ];
        list ($reflection, $dependencies) = $this->getDependencies($class);

        foreach ($params as $index => $param) {
            $dependencies[$index] = $param;
        }

      /* $dependencies = [
         0 => [],
         1 => yii\di\Instance,
         2 => yii\di\Instance,
         3 => yii\di\Instance,
         'hostname' => 'myhost',
         'port' => 777,
         'database' => 5
     ]
     */
      $dependencies = $this->resolveDependencies($dependencies, $reflection);
     // InvalidConfigException("Missing required parameter \"$name\" when instantiating \"$class\"."); throwed
     // So $params, that I passed to conatiner are ignored?

    /**
     * Registers a class definition with this container and marks the class as a singleton class.
    * ....
     * @param array $params the list of constructor parameters. The parameters will be passed to the 
class
   * ....
     */
   /* Yii::$container->setSingleton(
         'yii\redis\Connection',
         'app\components\MyCustomConnection',
            [
             'hostname' => 'myhost',
            'port'     => 7777,
            'database' => 5,
         ]
   ); 
*/
}

**Comment by mdmunir** [comment]
parameter `$config` must be last parameter

**Comment by KasianenkoMykhailo** [comment]
Thanks, mdmunir, the first variation works,
if I register dependency injection like this

`Yii::$container->setSingleton('yii\redis\Connection',[
    'class' => 'app\components\MyCustomConnection',
    'hostname' => 'myhost',
    'port'     => 7777,
    'database' => 5,
]);`

I $config will be successfuly passed to __constructor($config = [])

but

if I registering Dependency injection with constructor params 

`Yii::$container->setSingleton(
    'yii\redis\Connection',
    'app\components\SpRedisConnection',
    [
        'hostname' => 'localhost',
        'port'     => 6379,
        'database' => 3
    ]
);`

And I have declared constructor params in my class like 
`class MyCustomConnection extends \yii\redis\Connection
{
public $hostname;
public $port;
public $database;

public function __construct($hostname, $port, $database, $config = [])
{
    $this->hostname = $hostname;
    $this->port = $port;
    $this->database = $database;

    parent::__construct($config);
}
}`

// (I changed arguments declaration and passing $config as last param) as mdmunir adviced

// but still

`Container::build($class, $params, $config) {
    // ... $params = [ 'hostname' => 'myhost','port'=> 7777,'database' => 5 ];
   $dependencies = [
       0 => [],
       1 => yii\di\Instance,
       2 => yii\di\Instance,
       3 => yii\di\Instance,
       'hostname' => 'myhost',
       'port' => 777,
       'database' => 5
   ]
 // ...
// Throws Exception
}`

// I think this is an issue

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/yii-di-container.html#setSingleton()-detail
If you want to passing as constructor paramater. Use as non assositing array
```php
Yii::$container->setSingleton('yii\redis\Connection',
    'app\components\MyCustomConnection',
    ['myhost', 7777, 5]);
```

**Comment by KasianenkoMykhailo** [comment]
Thank a lot, I didn't pay attention, that $params should be <list>, which, probably means non assosiative array.
Problem is solved.
