### ISSUE TITLE
Hypercomments integration

### ISSUE THREAD

**Issue by h0ckeypl4yer** [yiisoft/yii2#11392]
Возникает проблема с обработкой события ajaxComplete при подключении hyperComments. Он ajaxом подменяет свою область комментариев формой входа и при реакции на событие ajaxComplete получаем xhr равным null. И ловим ошибку
`TypeError: Cannot read property 'getResponseHeader' of undefined`

Могу предположить, что это не единственный плагин, с которым может возникнуть такая проблема.

**Comment by samdark** [comment]
Есть идеи как поправить или хотя-бы вопроизвести?

**Comment by h0ckeypl4yer** [comment]
Вот код вставки виджета. Достаточно добавить его на любую страницу.
`<div id="hypercomments_widget"></div>
<script type="text/javascript">
    _hcwp = window._hcwp || [];
    _hcwp.push({widget:"Stream", widget_id: 72989});
    (function() {
        if("HC_LOAD_INIT" in window)return;
        HC_LOAD_INIT = true;
        var lang = (navigator.language || navigator.systemLanguage || navigator.userLanguage || "en").substr(0, 2).toLowerCase();
        var hcc = document.createElement("script"); hcc.type = "text/javascript"; hcc.async = true;
        hcc.src = ("https:" == document.location.protocol ? "https" : "http")+"://w.hypercomments.com/widget/hc/72989/"+lang+"/widget.js";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hcc, s.nextSibling);
    })();
</script>`

**Comment by lynicidn** [comment]
this work fine in project on yii 2.0.7
```html
<script type="text/javascript">
					_hcwp = window._hcwp || [];
					_hcwp.push({widget:"Stream", widget_id: 00000});
					(function() {
						if("HC_LOAD_INIT" in window)return;
						HC_LOAD_INIT = true;
						var lang = (navigator.language || navigator.systemLanguage || navigator.userLanguage || "en").substr(0, 2).toLowerCase();
						var hcc = document.createElement("script"); hcc.type = "text/javascript"; hcc.async = true;
						hcc.src = ("https:" == document.location.protocol ? "https" : "http")+"://w.hypercomments.com/widget/hc/0000/"+lang+"/widget.js";
						var s = document.getElementsByTagName("script")[0];
						s.parentNode.insertBefore(hcc, s.nextSibling);
					})();
				</script>
```

**Comment by h0ckeypl4yer** [comment]
![2016-04-21 13 08 05](https://cloud.githubusercontent.com/assets/7531693/14705426/29e722ca-07c2-11e6-9828-95d4b9441dff.png)
Я получаю в консоли такие ошибки. ВИджет сам отображается, но ошибки в консоли видны

**Comment by lynicidn** [comment]
http://portal.salt.zone/news/277

**Comment by s1lver** [comment]
Аналогичная ситуация
![Hypercomments](http://dl1.joxi.net/drive/2016/04/26/0012/2733/838317/17/64c073b02e.png)

**Comment by SilverFire** [comment]
Буду разбирать после релиза. Если кто-то желает помочь - буду рад пул-реквесту

**Comment by SilverFire** [comment]
Сейчас не воспроизводится. По идее исправлено коммитом be44d26
