### ISSUE TITLE
ActiveRecord::findByCondition() - @internal tag

### ISSUE THREAD

**Issue by thiagotalma** [yiisoft/yii2#11400]
The `@internal` PHPDoc tag is even necessary [here](https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecord.php#L168) - `ActiveRecord::findByCondition()`?

It causes warnings in the IDE when overriding the method.

**Comment by Faryshta** [comment]
its used by `findOne()` and `findAll()` methods so I think a warning is mandatory.

**Comment by samdark** [comment]
Yes. It is necessary.
