### ISSUE TITLE
Yii ActiveForm submit button broken!

### ISSUE THREAD

**Issue by demogorgorn** [yiisoft/yii2#11402]
After this fix (https://github.com/yiisoft/yii2/pull/10351) the submit button in active form works only on the second time.
In JS console: ReferenceError: $button is not defined

In yii.activeForm.js there is no the variable $button!

Line: 579

**Comment by SilverFire** [comment]
Reverted: https://github.com/yiisoft/yii2/commit/5686a9ddebad3d8b6f1d041d8c45403937c7de09

**Comment by SilverFire** [comment]
Will continue discussion in that PR, thank you

**Comment by demogorgorn** [comment]
Thank you!

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/fbedb8e750dbb752e43af718f4692c7d5d5e43d7
