### ISSUE TITLE
Here is an error in the class of \Yii\Db\Command at line 230

### ISSUE THREAD

**Issue by lanzhi** [yiisoft/yii2#11407]
class Exception only has three params, but four given;

To my surprise, it run so long is not apparent to anyone, and so the IDE

File: yii2/framework/db/Command.php
Line: 230 [prepare($forRead = null)]
context: 
        try {
            $this->pdoStatement = $pdo->prepare($sql);
            $this->bindPendingParams();
        } catch (\Exception $e) {
            $message = $e->getMessage() . "\nFailed to prepare SQL: $sql";
            $errorInfo = $e instanceof \PDOException ? $e->errorInfo : null;
            throw new Exception($message, $errorInfo, (int) $e->getCode(), $e);
        }

**Comment by lynicidn** [comment]
need full stack :d

**Comment by Faryshta** [comment]
show your sql and your params.

**Comment by cebe** [comment]
DB exception has 4 params, its all correct: https://github.com/yiisoft/yii2/blob/4f4fa6fdf0a45921ef48ffcd2941352c33a8dd28/framework/db/Exception.php#L32

Note the difference between `Exception` i.e. class from same namespace and `\Excpetion`, which is the class from root namespace.
