### ISSUE TITLE
[ENH] console::displayTable method

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#11412]
I am working in this issue https://github.com/yiisoft/yii2/issues/1763, i am needing anything to display routes in a table, for example Console::displayTable().

Usage : 

``` php
Console::displayTable(['URI', 'Action'], [
           ['GET /admin/configuration ', 'ConfigurationController/index '],
           ['POST /admin/configuration ', 'ConfigurationController/update']
], $colspan = '+', $separator = '-', $conector = '|');
```

```
// Output : 
// +----------------------------------+----------------------------------------+
// | URI                              | Action                                 |
// +----------------------------------+----------------------------------------+
// | 'GET /admin/configuration        | ConfigurationController/index          |
// +-----------------------------------+---------------------------------------+
// | 'Post/admin/configuration         | ConfigurationController/update        |
// +-----------------------------------+---------------------------------------+
```

I think to this feature is useful in other cases.

what do you think about it? can i send pr with this feature?

**Comment by lynicidn** [comment]
http://symfony.com/doc/current/cookbook/console/style.html#content-methods

**Comment by cebe** [comment]
>what do you think about it? can i send pr with this feature?

would be a great addition, go ahead :)

**Comment by pana1990** [comment]
@cebe @lynicidn can you check my pr?

**Comment by Sarke** [comment]
Question.  Why does Yii2 re-implement many of these same features from `symfony/console` instead of just using it (or at least creating a wrapper for it)?

`symfony/console` is install most times anyways, since `codeception` depends on it.

**Comment by samdark** [comment]
@Sarke we've started nearly the same time Symfony did. Symfony console architecture is very different. You will have totally different style of web / console controllers which is uniform in case of Yii.
