### ISSUE TITLE
Debug toolbar memory leak

### ISSUE THREAD

**Issue by djeux** [yiisoft/yii2#11419]
I'm building a queue system for Yii2 with beanstalkd. I've got a console controller to run in a loop checking for new jobs.

`````php
    while ($run) {
            $job = $queue->listen($tubeName);

            if (null !== $job) {
                try {
                    $job->handle();
                } catch (Exception $e) {
                    $this->stderr($e->getMessage());
                    Yii::error($e->getMessage(), 'queue.' . $tubeName);
                    $job->release();
                }
            }

            if ($this->isStopped() || $this->shouldRestart()) {
                $run = false;
            }
        }

```````

If I run it inside a loop I will constantly get increased memory usage (without handling any jobs). After cutting parts of the loop I found out that
```php
$this-isStopped() and $this->shouldRestart() 
```
Is causing it. The methods simply check for a key to be present inside cache (redis)

```php
if (Yii::$app->cache->get(self::RESTART_CACHE_KEY)) {
            $this->stdout("Restarting worker");
            return true;
        }
        
        return false;
```

So just checking cache is taking more and more memory?

Yii 2.0.7

**Comment by djeux** [comment]
Will close for further investigation until I find the real reason for the leak.

**Comment by djeux** [comment]
Reason for the leak is using 'debug' module enabled in console application. 
Is there a reason for such behavior?

**Comment by cebe** [comment]
do you have the debug toolbar enabled or just YII_DEBUG=true?

**Comment by djeux** [comment]
Module, not just YII_DEBUG=true

**Comment by samdark** [comment]
It could be logs collection w/o flushing.

**Comment by djeux** [comment]
Could be, if the flushing is happening at the end of console request. But if the request does not end (loop) it just grows and grows.

**Comment by samdark** [comment]
@djeux could you do manual flushing here and there and report if that helped?

**Comment by djeux** [comment]
Reducing flushInterval or manually flushing doesn't help. Although Log::flush() is getting called a lot.

Well, just have to remember to disable debug module if using infinite console commands.

**Comment by djeux** [comment]
Hokay here's the walkthrough.

\yii\debug\Module adds his \yii\debug\LogTarget to the log->targets.

\yii\debug\LogTarget::collect() is constantly called when the "flushInterval" is reached, but since $final is always FALSE (since the request doesn't end) all it does is just append the messages to \yii\debug\LogTarget::$messages (line 116), which grows and grows the longer the command is running and is never flushing.

**Comment by samdark** [comment]
That's expected behavior. Needs to be documented somewhere near http://www.yiiframework.com/doc-2.0/guide-runtime-logging.html#flushing-exporting

**Comment by djeux** [comment]
Yes, doesn't look like a bug. Just needs clarification for cases when console applications are expected to run in loops.

**Comment by cebe** [comment]
yeah, debug toolbar is not built to flush constantly like e.g. file logger. it will only write data once request is finished.

**Comment by cebe** [comment]
@samdark sorry, did not understand your message, so you think this should just have a warning in the docs, right?

**Comment by djeux** [comment]
Shouldn't simply adding 
```
if (Application instanceof \yii\console\Application && count($this->message) > $this->flushInterval) {
    $this-export();
}
```

help??
