### ISSUE TITLE
Implement Object::shortClassName()

### ISSUE THREAD

**Issue by Rafalsky** [yiisoft/yii2#11413]
Can you please implement shortClassName() static method to yii\base\Object class.

I currently use PHP 5.5 where I can use
`
yii\base\Object::class
`

to get className with namespace. The same using static method in yii\base\Object:
`
Object::classname();
`

I like to get className without namespace. For example to verify post data:

```
if ($request->isPost && $attributes = $request->post(Article::shortClassName()) {
    $model->attributes = $attributes;
    $model->save();
}
```

I think that below code is better than:
```
$request->post('Article');
```

It is achievable using ReflectionClass (currently fastest way):
```
(new \ReflectionClass($model))->getShortName())
```

**Comment by cebe** [comment]
`yii\helpers\StringHelper::basename(Article::class)` is what you are looking for.
