### ISSUE TITLE
Bug/Error: Console Application

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#11425]
### What steps will reproduce the problem?
Execute
```
$ ./yii
```
### What is the expected result?
No error
### What do you get instead?
```
PHP Fatal error:  Cannot use yii\console\Markdown as Markdown because the name is already in use in /home/mdmunir/projects/php/yii-id/yii2-playground/vendor/yiisoft/yii2/helpers/BaseConsole.php on line 10
PHP Fatal error:  Class 'yii\helpers\Console' not found in /home/mdmunir/projects/php/yii-id/yii2-playground/vendor/yiisoft/yii2/console/ErrorHandler.php on line 68

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master
| PHP version      | 7.x
| Operating system | Debian

https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseConsole.php#L10
use `yii\console\Markdown` in `yii\helpers` namespace but `yii\helpers\Markdown` exists.

**Comment by cebe** [comment]
fixed, thanks for reporting!
