### ISSUE TITLE
Oracle schema.php / function findColumns

### ISSUE THREAD

**Issue by SSiwek** [yiisoft/yii2#11428]
Hi,
again please be lenient with my English.

The select used in this function is rather slow  on the DB's I can connect to, 

So I looked at it and eventually I found at last a little speed up.
The main timeconsumer in this select is the inner select to retrieve attribute "Key".
Maybe one should get this attribut in an extra select.

For now I modified the select as followed( speed up by factor 10, if repeatedly called )

```sql
        $sql = <<<SQL
SELECT a.column_name, a.data_type, a.data_precision, a.data_scale, a.data_length,
    a.nullable, a.data_default,
    (   SELECT D.constraint_type
        FROM ALL_CONS_COLUMNS C
        inner join ALL_constraints D on D.OWNER = C.OWNER  and d.TABLE_NAME=c.TABLE_NAME and D.constraint_name = C.constraint_name
        WHERE C.OWNER = A.OWNER
           and C.table_name = A.table_name
           and C.column_name = A.column_name
           and D.constraint_type = 'P') as Key,
    com.comments as column_comment
FROM ALL_TAB_COLUMNS A
inner join ALL_OBJECTS B ON b.owner = a.owner and ltrim(B.OBJECT_NAME) = ltrim(A.TABLE_NAME)
LEFT JOIN all_col_comments com ON (A.owner = com.owner AND A.table_name = com.table_name AND A.column_name = com.column_name)
WHERE
    a.owner = :schemaName
    and b.object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
    and b.object_name = :tableName
ORDER by a.column_id
SQL;
```

Sven

**Comment by cebe** [comment]
can you send a pull request with the changes?
if its too hard to do with git you can just edit the file on github: https://github.com/yiisoft/yii2/blob/master/framework/db/oci/Schema.php there is an edit button on the top right.
