### ISSUE TITLE
CompareValidator client side validation not working with specific IDs

### ISSUE THREAD

**Issue by gael-wogenstahl** [yiisoft/yii2#11423]
I found this issue while using the `CompareValidator`between 2 attributes when the attribute to be compared to has a specific ID.

In my model I have two attributes `A` and `B` and I setup a `compare` validator on attribute `B` to be greater than attribute `A`.
In my view I use a specific ID for my attribute `A`.

When client side validation is triggered I get an error no matter what the value of input `B` is.

Digging into the PHP and Javascript code I found out that:
- In `yii.validation.js` on line 289 the following code would not return the value of attribute to compare to `compareValue = $('#' + options.compareAttribute).val();`
- In `CompareValidator.php` on line 222 the initialisation of `compareAttribute` in `options` table is done through the `Html::getInputId` method instead of using the specific ID provided

Being not as talented and expert as you guys on the Yii2 framework I have no clue how to solve that problem if it is solvable in any way.
Can you help ?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8-dev
| PHP version      | 5.5.9-1ubuntu4.14
| Operating system | Ubuntu Server 14.04

**Comment by Alex-Code** [comment]
Not sure on the best work around for this.
Do you need to specify your own id?

**Comment by SilverFire** [comment]
Related to https://github.com/yiisoft/yii2/issues/9811
Closing as a duplicate
