### ISSUE TITLE
LinkPager duplicate page (page=1 & without)

### ISSUE THREAD

**Issue by mhoogstraten** [yiisoft/yii2#11424]
### What steps will reproduce the problem?
When adding an overview that contains a LinkPager. Make sure there are atleast 2 pages. Click on page 2 and go back to page 1, now the GET parameter contains page=1.

### What is the expected result?
The GET parameter should be removed, this because search engines see this as duplicate content (with and without the "page=1" GET parameter).

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8-dev
| PHP version      |  7.0.2
| Operating system |  Windows 10

**Comment by SilverFire** [comment]
Set `forcePageParam` to `false`

http://www.yiiframework.com/doc-2.0/yii-data-pagination.html#$forcePageParam-detail
