### ISSUE TITLE
The message file for category 'yii' does not exist

### ISSUE THREAD

**Issue by MaXL-ru** [yiisoft/yii2#11429]
I have many errors in log file:
```
The message file for category 'yii' does not exist: ...vendor/yiisoft/yii2/messages/en-GB/yii.php Fallback file does not exist as well: ...vendor/yiisoft/yii2/messages/en/yii.php
```

Yii (2.0.7) `$language` is `en-GB`.

I have already seen that @SilverFire has been already fixed (#7964).

**Comment by cebe** [comment]
do you get this error with yii 2.0.7 ?

**Comment by MaXL-ru** [comment]
Yes.

**Comment by klimov-paul** [comment]
Well, we do not have translations for `en-GB` as well as for `en`:
https://github.com/yiisoft/yii2/tree/master/framework/messages

They are considred as not necessary ones.
If you wish to avoid error messages in logs, you should configure `sourceLanguage` to be `en-GB`.

**Comment by MaXL-ru** [comment]
I already set this in config:

``
'language'  => 'en-GB',
'sourceLanguage' => 'en-GB'
```
but errors happened.

**Comment by cebe** [comment]
what does your message source config look like, i.e. i18n component config.

**Comment by MaXL-ru** [comment]
```
'i18n' => [
      'translations' => [
        'app*' => [
          'class' => 'yii\i18n\PhpMessageSource',
          'basePath' => '@app/messages',
          'sourceLanguage' => 'en-GB'
        ]
      ]
    ]
```

I already tried to comment this config.

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/c3c0d04f5bc58c5ad08da13797e27d956ebec043
