### ISSUE TITLE
Bad template 'tableName' for findOne()

### ISSUE THREAD

**Issue by efureev** [yiisoft/yii2#11422]
```
class Customer extends ActiveRecord
{
	public static function tableName()
	{
		return '{{%customers}} c';
	}
}
```
 // work nice!
```$customer = Customer::find()->where(['id'=>9])->one();```
// don't work! -> Exception: The table does not exist: {{%customers}} c
```$customer = Customer::findOne(9);```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.6
| Operating system | MAC OS

**Comment by CedricYii** [comment]
The bug might be that it works with find()!

**Comment by cebe** [comment]
yeah, tablename should be a simple name only. if you want to define a fixed alias, you should override `find()`:

```php
public static function find()
{
    return parent::find()->alias('c');
}
```
