### ISSUE TITLE
Strange Bug ! Apache restart 

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [yiisoft/yii2#11437]
### What steps will reproduce the problem?
step 1 : create a class in any folder of yii framework.
step 2 : structure of class code must be like under :
```
namespace app\components; #or any thing
class Bug{
	public function load(){
		foreach($examples as $e){
			call_user_func($a,&$b);
		}
	}
}
```
call class 'Bug' in any place:

```
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;

class SiteController extends Controller
{
    public function actionIndex()
    {
        new \app\components\Bug;
    }
}
?>
```

### What is the expected result?
show error .
### What do you get instead?
Apache restart !!!

### Additional info
apache error log :
`[Wed Apr 27 19:53:36.208403 2016] [mpm_winnt:notice] [pid 9064:tid 400] AH00428: Parent: child process 6816 exited with status 3221225477 -- Restarting.
[Wed Apr 27 19:53:36.813088 2016] [ssl:warn] [pid 9064:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Apr 27 19:53:36.843255 2016] [mpm_winnt:notice] [pid 9064:tid 400] AH00455: Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3 configured -- resuming normal operations
[Wed Apr 27 19:53:36.843255 2016] [mpm_winnt:notice] [pid 9064:tid 400] AH00456: Apache Lounge VC11 Server built: Jul 17 2014 11:50:08
[Wed Apr 27 19:53:36.843255 2016] [core:notice] [pid 9064:tid 400] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Wed Apr 27 19:53:36.845257 2016] [mpm_winnt:notice] [pid 9064:tid 400] AH00418: Parent: Created child process 8772
[Wed Apr 27 19:53:37.539436 2016] [ssl:warn] [pid 8772:tid 380] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Apr 27 19:53:37.885145 2016] [ssl:warn] [pid 8772:tid 380] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Apr 27 19:53:37.917167 2016] [mpm_winnt:notice] [pid 8772:tid 380] AH00354: Child: Starting 150 worker threads.
[Wed Apr 27 19:53:39.539831 2016] [mpm_winnt:notice] [pid 9064:tid 400] AH00428: Parent: child process 8772 exited with status 3221225477 -- Restarting.`

php error log :
`[27-Apr-2016 19:53:37 Asia/Tehran] PHP Fatal error:  Call-time pass-by-reference has been removed in C:\xampp\htdocs\ziaratban\components\Bug.php on line 7`

| Q                | A
| ---------------- | ---
| Yii version      | 2 Basic
| PHP version      | 5.6.3
| Operating system | Windows 8.1

**Comment by cebe** [comment]
looks like a problem with your php setup, this is not caused by yii.

**Comment by cebe** [comment]
also as the php messages says, call time pass by reference does not work, so do not use it.

**Comment by abolfazl-ziaratban** [comment]
thanks for reply.

> looks like a problem with your php setup, this is not caused by yii.

i test this class in a single php file and see php error but in yii framework the above problem(apache restart) has occurred
why this error in yii is different ? but in single php file is ok !

maybe a program like antivirus cause this error.
