### ISSUE TITLE
Yii::setAlias() in the entry script

### ISSUE THREAD

**Issue by achertovsky** [yiisoft/yii2#11431]
yii2 basic template

entry script code.
```
<?php

// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/../config/bootstrap.php'); // file exists

$config = require(__DIR__ . '/../config/web.php');

$application = new yii\web\Application($config);
$application->run();
```

bootstrap.php code
```
<?php
Yii::setAlias('web', dirname(__DIR__) . '/web');
```

in site/index trying to do `Yii::getAlias('@web');` and get empty string

**Comment by df2** [comment]
@achertovsky If you still need this, is just because you miss the @ sign when you set the alias.

**Comment by achertovsky** [comment]
@df2 thx. i'll check

**Comment by cebe** [comment]
> Yii::setAlias('web', dirname(__DIR__) . '/web');

note that `@web` is a URL, and `@webroot` is a path! So if your webapp is directly under the hostname , the base url (`@web`) must be empty.
