### ISSUE TITLE
RBAC migration type

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#11448]
Hi all. Is it normally?
https://github.com/yiisoft/yii2/blob/master/framework/rbac/migrations/m140506_102106_rbac_init.php#L88
Check this out. user_id have VARCHAR type instead INT. Or i something don't understand?

**Comment by samdark** [comment]
Yes. It's OK.

**Comment by samdark** [comment]
User ID may be, for example, UUID.
