### ISSUE TITLE
When have two models in the form and use errorSummary for each, When happen errors of one model, show errors in two errorSummary block!

### ISSUE THREAD

**Issue by NabiKAZ** [yiisoft/yii2#11440]
When have two models in the form and use `errorSummary `for each, When happen errors of one model, show errors in two error summary block!

```
<?= $form->errorSummary($model1); ?>
<?= $form->errorSummary($model2); ?>
```

**Comment by cebe** [comment]
can you elaborate on the problem? If you specify two blocks I'd expect two blocks to be displayed, no?

**Comment by TerraSkye** [comment]
$form->errorSummary([$model1,$model2]); 
isnt that what you mean?

**Comment by NabiKAZ** [comment]
@TerraSkye Yes, Thanks!
