### ISSUE TITLE
longtext mysql not exist in yii\db\schema

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11447]
current version yii2

im trying add using yii\db\Schema 
in the migration a attribute type longtext, why this not exist in the class ?

i can add manually like 'LONGTEXT NOT NULL'...

work perfectly but i cant see longtext,etc in the class

regards

**Comment by spiritdead** [comment]
@cebe  this can be included in 2.0.8 or is better wait to 2.0.9 ?

**Comment by cebe** [comment]
2.0.8 is about to be released, nothing will be included anymore, sorry :)

**Comment by SilverFire** [comment]
LONGTEXT is available only in MySQL. Since it is very driver-specific, I don't think we must include it in core.

I'm closing the issue, but if you have any thought on this - feel free to share them. Thank you

**Comment by SilverFire** [comment]
Duplicates #8950
