### ISSUE TITLE
flash could not be auto destroy when session is auto start

### ISSUE THREAD

**Issue by cartmanchen** [yiisoft/yii2#11459]
**when session is auto start. `getIsActive` is always return `true`,  the `updateFlashCounters` method could not be execute, so the flash could not be auto desdroy.**

```php
public function open()
    {
        if ($this->getIsActive()) {
            return;
        }

        $this->registerSessionHandler();

        $this->setCookieParamsInternal();

        @session_start();

        if ($this->getIsActive()) {
            Yii::info('Session started', __METHOD__);
            $this->updateFlashCounters();
        } else {
            $error = error_get_last();
            $message = isset($error['message']) ? $error['message'] : 'Failed to start session.';
            Yii::error($message, __METHOD__);
        }
    }
```
I use `Yii::$app->session->setFlash('sucess', 'message')` to set a flash;
Then use `getFlash('success')` in the view;
But when i request next time, the flash already exists;

### Additional info
Yii version: 2.0.7
PHP version : 5.6

**Comment by samdark** [comment]
Are you sure `Yii::$app->session->setFlash('sucess', 'message')` isn't called in the same action prior to rendering the view that has `getFlash('success')`?

**Comment by cartmanchen** [comment]
yes, I'm sure.
The mehod `updateFlashCounters()` not be called, my session is autostart

**Comment by samdark** [comment]
I cannot reproduce it.

- Start with basic app template.
- In SiteController add:

```php
public function actionA()
{
    Yii::$app->session->setFlash('success', 'message');
    return $this->redirect(['site/b']);
}

public function actionB()
{
    return Yii::$app->session->getFlash('success');
}
```

- Access `/index.php?r=site/a`.
- We're redirected to `/index.php?r=site/b` and "message" is displayed.
- Refresh `/index.php?r=site/b`, see "message" disappear.

**Comment by samdark** [comment]
OK. Reproduced with `session.auto_start = 1` set in php.ini.
