### ISSUE TITLE
hmvc in Yii2

### ISSUE THREAD

**Issue by sahifedp** [yiisoft/yii2#11452]
Hi
I Worked with Cakephp and codeigniter and little Yii2, and I found Yii2 very Awesome..
for example work with composer , model , widgets &.. in Yii2 is very good , 
but:
cakephp 3 support 3 level HMVC (by plugin and route prefix) , codeigniter support unlimited level HMVC, but I don't know how to use HMVC in Yii2.

I want create a module that need HMVC structure (it has admin and frontend and many controller in admin and frontend)
My module structure:

`ModuleName

      admin

           controllers

                AdminController.php

                OtherController.php

          views

                ...
     frontend

          controllers

               SiteController.php

               OtherController.php

          views

              ...

    Models

          ...

    ModuleName.php

`
I seen [https://github.com/vtvz/yii2-hmvc](url) and [https://gist.github.com/samdark/1124018](url) , but I do not know where to I start?
(I work based on yii basic app)
thank you anyway...

**Comment by samdark** [comment]
I'd not try to use Yii that way:

1. There are widgets.
2. You can extract your domain layer out of controllers instead of trying to reuse controllers.

**Comment by sahifedp** [comment]
thank you
I want create a Independent Module that can be installed with composer, as a result I can't use domain layer. 
To use widgets, how to handle the request to run a widget? should I use a controller as interface?

**Comment by samdark** [comment]
You absolutely can extract domain layer and provide it from the module. Widgets are used in views typically.

**Comment by sahifedp** [comment]
Please tell me a link to learn domain layer or examples of its use.
I could not find good documentation about domain layer.
Thanks for your patience.

**Comment by samdark** [comment]
http://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215
