### ISSUE TITLE
Hi~guys, can I ask you a question?

### ISSUE THREAD

**Issue by duruitang** [yiisoft/yii2#11453]
Yii always has so much bugs fixed, Can I use Yii2 in production for 3 years with no update to latest version?

```
Version 2.0.8 is a patch release of Yii 2.0 which contains
about 100 minor new features and bug fixes in 300 commits,
 by 64 contributors, changing 150 files.
```

**Comment by samdark** [comment]
Depends if it works and if security issues were found. Old version won't spontaneously blow up anyway.

**Comment by Faryshta** [comment]
@duruitang 

wow.... unlikely for any software at all. Plus the update is very simple if you use composer.
