### ISSUE TITLE
Smart restful url rules for controllers pattern

### ISSUE THREAD

**Issue by iamwebdesigner** [yiisoft/yii2#11455]
I am developing a module called `ApiModule` where all controllers extends restful `ActiveController` and I have about tens of controllers for now and its number is increasing. Every time I add a controller I forget to add it in configurations to the `[[controllers]]` property of `yii\rest\UrlRule` and wonder why it is not working for some time, unless I remember the reason. I tried to use a pattern like: `api/*`, but it does not work. I wonder, is it possible to apply some patterns for restful url rules as described below, so it was not necessary to modify it once the pattern is declared?

**Comment by TerraSkye** [comment]
isnt it api<controller:\w+>  ?

**Comment by iamwebdesigner** [comment]
@TerraSkye yes, seems it is working, this was the only option I havent tried. Thank you for the prompting.
I think it should be documented, I really didnt expected that `[[controllers]]` property is a part of a rule itself.

**Comment by samdark** [comment]
@iamwebdesigner where'd you expect these in the docs?

**Comment by Forin** [comment]
http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html#configuring-url-rules

**Comment by iamwebdesigner** [comment]
@samdark probably [somewhere here](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/rest-routing.md#Маршрутизация)

**Comment by iamwebdesigner** [comment]
@TerraSkye @samdark it seems I was wrong. I thought `api/<controller:\w+>` was working, because I was requesting only `index` action and it was working by default `UrlManager`'s rules. As long as I tried saving the data, it didnt work and I had to include all module's controllers again.

**Comment by iamwebdesigner** [comment]
anything new on this?

**Comment by samdark** [comment]
Nope.

**Comment by TerraSkye** [comment]
For an action you would add the action param? <action:\w+> if im not mistaken

**Comment by iamwebdesigner** [comment]
@TerraSkye no there isnt any action, only names of controllers
