### ISSUE TITLE
gii "ctrl+c" issue Chromium 

### ISSUE THREAD

**Issue by newbie67** [yiisoft/yii2#11456]
Please, sorry for my English.

Bug actual for Chromium. I use actual version 49.0.2623.108 Built on Ubuntu 14.04 with Shockwave Flash 21.0 r0

### What steps will reproduce the problem?
1) Open gii
2) Generate any code
3) Use "ctrl + c"
4) Paste code in your .php file

### What do you get?
Syntax error. Cas we have invisible characters instead of spaces.

### Additional info
| Yii version             |  2.08
| PHP version         | any
| Operating system | Ubuntu 14.04

### Screenshot
![img](http://www.pixic.ru/i/q0p1o0N627e0e5f6.png)

**Comment by cebe** [comment]
duplicate of https://github.com/yiisoft/yii2-gii/issues/145 ? could you try to upgrade gii to dev-master and see if it is fixed?

**Comment by newbie67** [comment]
> uplicate of yiisoft/yii2-gii#145 ?

Yep.

> could you try to upgrade gii to dev-master and see if it is fixed?

Yep. It's fixed!
