### ISSUE TITLE
Problem with EachValidator in 2.0.8

### ISSUE THREAD

**Issue by anmoroz** [yiisoft/yii2#11468]
An example of rules in the model:
```php
// $this->brands = [1];
public function rules()
{
    return [
        [['brands'], 'each', 'rule' => ['integer']],
    ];
}
```
When $this->brands = [1]; errors should not be

After validation I have an error "brands must be an integer."

The problem is probably in \yii\validators\EachValidator in 131 lines
```php
foreach ($value as $k => $v) {
            $model->$attribute = $v;
            $validator->validateAttribute($model, $attribute);
.....
```

```
$model->$attribute = $v;
var_dump($v, $model->$attribute);

vendor/yiisoft/yii2/validators/EachValidator.php:132:int 1
vendor/yiisoft/yii2/validators/EachValidator.php:132:
array (size=1)
  0 => int 1
```

Yii 2.0.8 
PHP version   7.0.5 
Operating system OS X

**Comment by anmoroz** [comment]
Such behavior validator due setter

My model:
```php
private $brands;
........

    /**
     * @param string $brands
     */
    public function setBrands($brands)
    {
        if (is_scalar($brands) && preg_match('/^\d+(?:,\d+)*$/', (string) $brands)) {
            $this->brands = explode(',', (string) $brands);
        }
    }
```

I do not know if this is a bug in validator.

**Comment by cebe** [comment]
you should remove the private property, it prevents the attribute from being set.

**Comment by cebe** [comment]
assuming you are using active record

**Comment by anmoroz** [comment]
This model is not ActiveRecord. Attribute brand in my case must be an array. 
EachValidator assigns attribute brands of integer or string value at the time of validation. I did not expect this.
I can do attribute "brands" public and move method setBrands from model. But, it seems to me, this is not the right solution.

**Comment by cebe** [comment]
the best way would be to have it as a public property and do the transformation in a filter validator.

**Comment by anmoroz** [comment]
Thanks, I'll do what you recommend.
But I think that the validator should not change the model state in validation process.

**Comment by dsergey** [comment]
How I can now implement this logic if I use eachValidator for check integer in catIds? https://github.com/yiisoft/yii2/issues/3660#issuecomment-44921519

**Comment by cebe** [comment]
> But I think that the validator should not change the model state in validation process.

that's the purpose of filter validators, we have not introduced another concept of filters beside validation flow because this way, they can be mixed.
