### ISSUE TITLE
multiple checkboxList submits empty string

### ISSUE THREAD

**Issue by julianrutten** [yiisoft/yii2#11469]
### What steps will reproduce the problem?
Create a form with multiple checkboxList activefields with the same attribute name. For example:
```php
echo $form->field($model,'_attribute')->checkboxList($items);
echo $form->field($model,'_attribute')->checkboxList($items);
```
### What is the expected result?
Any selected checkboxes should be submitted

### What do you get instead?
An empty string. Because the hidden input for the second checkboxList overrides the selected options of the first.

### Additional info
This is an easy fix: 
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L930

Change this line to:
```php
if(isset($options['unselect']) && $options['unselect'] !== false)
```

This way you can just set ['unselect' => false] on the second (and any after with the same name) and it will exclude the hidden input. It will still submit an empty string when nothing is selected because of the first checkboxList which does have the unselect hidden input.

| Q                | A
| ---------------- | ---
| Yii version      | >= 2.0
| PHP version      | 5.4
| Operating system | CentOS

**Comment by rob006** [comment]
> This way you can just set ['unselect' => false] on the second

You can use `['unselect' => null]`.

**Comment by julianrutten** [comment]
Totally forgot about that, thanks :)
