### ISSUE TITLE
enable gzip

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11479]
im trying find information of this, but i cant find good information.

i see this 
http://stackoverflow.com/questions/31516074/how-to-enable-gzip-compression-in-yii2
http://stackoverflow.com/questions/10975908/yii-compress-your-application-output-using-gzip

is the correct way for activate gzip in yii2 ?

or i can configure this in the common config

regards

**Comment by cebe** [comment]
why not let the webserver do it?

**Comment by cbhp** [comment]
That's a pretty bad idea. The webserver (nginx/apache/...) should handle compression if the browser support it. It's not a job of the application.
