### ISSUE TITLE
UniqueValidator seems to be unhappy with ::class syntax

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#11473]
Failing test on 2.1.x branch:

yiiunit\framework\validators\UniqueValidatorTest::testValidateScopeNamespaceTargetClass:

https://travis-ci.org/yiisoft/yii2/jobs/126971192#L281

**Comment by Faryshta** [comment]
https://github.com/yiisoft/yii2/blob/2.1/framework/validators/UniqueValidator.php#L113 its because this line. `get_class($model)` returns a value without trailing `\` we should use `instanceof` instead

**Comment by Faryshta** [comment]
thinking it twice i think there are use cases where you need the exact same class and not an inherited class.

**Comment by cebe** [comment]
thanks for checking.
