### ISSUE TITLE
[ENH] 2.1 change the signature of certain methods to use variadic functions

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#11475]
http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list

For example, right now when dealing with several models on `ActiveForm::errorSummary()`

```php

echo $form->errorSummary(array_merge([$user], [$userAddress], $userImages, $userFriends));

// would be simplier as

echo $form->errorSummary($user, $userAdress, ...$userImages, ...$userFriends);
```

And the method would be much simplier to debug if the signature is changed

```php
/**
 * @param Model|Model[] $models the model(s) associated with this form
 * @param array $options the tag options in terms of name-value pairs.
 */
specially handled:

public function errorSummary($models, $options = []) {}

// changed to

/**
 * @param Model[] $models the model(s) associated with this form
 * @param array $options the tag options in terms of name-value pairs.
 */
public function errorSummary(Model ...$models, array $options = []) {}
```

To give an example, other methods can benefit from this too

**Comment by SilverFire** [comment]
It must not work like you've described. Declaring the first parameter as variadic will likely lead to the fatal error since only the last parameter can be variadic

**Comment by Faryshta** [comment]
you are right, almost every method ends with an `options` parameter. Changing that as the first param is not a good idea either.
