### ISSUE TITLE
ArrayHelper / dropdownlist support ajax update

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11472]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.x
| Operating system | windows

im trying find this in yii2 but this not exist

http://www.yiiframework.com/wiki/24/

can arrayHelper add this improvement or the dropdownlist in activefield?

@samdark 

regards

**Comment by cebe** [comment]
You mean CHtml::listData()? That is now provided by ArrayHelper::map().

**Comment by spiritdead** [comment]
@cebe  i know, but i cant find any method for update this using ajax, like the example yii 1.1
http://www.yiiframework.com/wiki/24/

**Comment by pana1990** [comment]
@spiritdead check this article http://www.yiiframework.com/wiki/665/overcoming-removal-of-client-helpers-e-g-ajaxlink-and-clientscript-in-yii-2-0/

**Comment by spiritdead** [comment]
@pana1990 well, :/ i readed the document and see the reason  i think can close this request
