### ISSUE TITLE
Can't sent email via swiftmailer after update 2.0.8

### ISSUE THREAD

**Issue by x11RPM** [yiisoft/yii2#11471]
Yii2 can't send email by using mailer component after update to v 2.0.8. it can work normally on 2.0.6 (not sure for 2.0.7).

In v.2.0.6 when sent an email it will have a two lines show in **PHP Script Name** in DirectAdmin at Email usage menu.
Example:
```
frontend/controllers/SiteController.php
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SimpleMailInvoker.php
```

But after update yii2 to 2.0.8
There nothing show in PHP Script Name (if using yii mailer).
Code have not to change anything too.

Tried to use mail() function, it works normally.

Code:
```
\Yii::$app->mailer->compose()
    	->setFrom('admin@domain.com)
    	->setTo('somemail@hotmail.com')
    	->setSubject('Hello Test')
    	->setTextBody('Can u see me?')
    	->send();

```

Config:
```
'mailer' => [
						'class' => 'yii\swiftmailer\Mailer',
						'useFileTransport'=> false,
						'transport' => [
								'class' => 'Swift_SmtpTransport',
								'host' => 'smtp.gmail.com',
								'username' => 'xxxx@gmail.com',
								'password' => 'xxxxx',
								'port' => '465',
								'encryption' => 'ssl',
						],
				],
```
Another config
```
'mailer' => [
						'class' => 'yii\swiftmailer\Mailer',
]
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 5.6.8

**Comment by cebe** [comment]
can you try to track this down using `git bisect`?

**Comment by SilverFire** [comment]
I can't see any headers with stacktrace on 2.0.6. Check out yii2-switfmailer to a previous release, no stacktraces as well.
