### ISSUE TITLE
ArrayHelper with checkboxlist error groups

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11480]
### What steps will reproduce the problem?
when i try get a attribute second level relation
### What is the expected result?
the attribute
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.x
| Operating system | windows

im trying this

```php
<?= $form->field($model, 'bird_mutation')->checkboxList(ArrayHelper::map(BirdSpecieMutation::find()->where(['bird_specie_id' => $model->bird_specie_id])->all(),'id','birdMutation.name','birdMutation.birdMutationType.label'),['prompt' => 'Select Mutations','itemOptions' => ['class' => 'i-checks']]) ?>
```

a second level relationship for make groups in a relation N:M

but i get this error

```
PHP Warning – yii\base\ErrorException

htmlspecialchars() expects parameter 1 to be string, array given
```

this no have recursive for get the value ?

**Comment by cebe** [comment]
> htmlspecialchars() expects parameter 1 to be string, array given

that means you somewhere assigned an array where a string would have been expected.

**Comment by spiritdead** [comment]
@cebe  yes i updated my title issue and question

i get this only when i try use checkboxlist, this no have any method for groups ?

**Comment by SilverFire** [comment]
Please, show the result of the following code:

```php
var_dump(BirdSpecieMutation::find()->where(['bird_specie_id' => $model->bird_specie_id])->limit(1)->all());
```

**Comment by spiritdead** [comment]
@SilverFire  the table bird_specie_mutation is a relation N:M this table contain the relations of the table bird_specie and bird_mutation

**Comment by SilverFire** [comment]
So what does the code above returns?

**Comment by spiritdead** [comment]
@SilverFire 
array (size=1)
  0 => 
    object(common\models\BirdSpecieMutation)[135]
      private '_attributes' (yii\db\BaseActiveRecord) => 
        array (size=3)
          'id' => int 1
          'bird_specie_id' => int 1
          'bird_mutation_id' => int 1
      private '_oldAttributes' (yii\db\BaseActiveRecord) => 
        array (size=3)
          'id' => int 1
          'bird_specie_id' => int 1
          'bird_mutation_id' => int 1
      private '_related' (yii\db\BaseActiveRecord) => 
        array (size=0)
          empty
      private '_errors' (yii\base\Model) => null
      private '_validators' (yii\base\Model) => null
      private '_scenario' (yii\base\Model) => string 'default' (length=7)
      private '_events' (yii\base\Component) => 
        array (size=0)
          empty
      private '_behaviors' (yii\base\Component) => 
        array (size=0)
          empty

**Comment by SilverFire** [comment]
Do you have birdMutation relation?

**Comment by spiritdead** [comment]
@SilverFire  yes

this is the relations of BirdSpecieMutation


```code
/**
     * @return \yii\db\ActiveQuery
     */
    public function getBirdMutation()
    {
        return $this->hasOne(BirdMutation::className(), ['id' => 'bird_mutation_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBirdSpecie()
    {
        return $this->hasOne(BirdSpecie::className(), ['id' => 'bird_specie_id']);
    }
```

**Comment by SilverFire** [comment]
Failed to reproduce
