### ISSUE TITLE
Use of fields in nested attributes as keys in relations

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#11489]
Originally reported by @Lisio at https://github.com/yiisoft/yii2-mongodb/pull/53

Required if we have to get all files (without content) related to some documents. In this case we are recomended to use metadata field as a container for other fields. For example, Image model will have the following properties:

``` javascript
{
    "metadata": {
        "post_id": ObjectId("abcd01234567890123456789"),
        "width": 640,
        "height": 480
    }
}
```

and relation in Post model can be declared like this

``` php
public function getImages()
{
    return $this->hasMany(Image::className(), ['metadata.post_id' => '_id']);
}
```

I suppose if such enhancement is to be made it should be placed at ActiveRelationTrait since it may affect not only MongoDB. For example: ElasticSearch may have the same use case.

The problem with the relation by nested attribute is there is not way to declare a reverse relation to it.
How Image will relate to the Post in this case?

In order to suport this feature we need to compose full-scale nested attributes logic at the top of yii\db* layer.

**Comment by lynicidn** [comment]
need do full support for inner form - load, validate, populate

**Comment by cebe** [comment]
Another open questions is how such a relation is handled in a non lazy loading case.

**Comment by dynasource** [comment]
Is it really preferable to insert a dimension inside a dimension? From an architectural perspective this is questionable

**Comment by Lisio** [comment]
For fs.files collection the only way to store references correctly is to put them inside metadata property.

**Comment by dynasource** [comment]
can you elaborate?
