### ISSUE TITLE
Querying by self linked relation work incorrectly

### ISSUE THREAD

**Issue by iamwebdesigner** [yiisoft/yii2#11481]
I have a table which links to itself and contains of the following attributes:
id
name
parentid <- this one is linked to id attribute
Inside by model I declare relation as so:
```php
public function getGroup()
{
    return $this->hasOne(Category::className(), ['id' => 'parentid']);
}
```
I try to make a query to this model and group them by parent's name. I am using this query to achieve described:
```php
Category::find()
	->alias('t')
	->joinWith(['group g'])
	->asArray(true)
	->where('t.parentid IS NOT NULL')
	->select("t.id, t.name AS text, g.name AS group") // <- note alias name
	->all();
```
I get the right SQL, but the result I am getting is incorrect. In each row I dont have a group field (it is null). I tried to debug the framework code and I have found that query return correct data, but on mapping stage `group` is lost. After many more of debugging I have noticed that `group` is rewritten due to the relation's name coincides the select's alias. I dont know is it right to consider it as a bug or not, but logically I was expecting the `group` to be the alias I have set in select. I think it is not correct to override fields when relations are mapped and the `asArray` is set to `true`, what do you think?

**Comment by cebe** [comment]
you can not select a field that does not exist in a model. You either need to fetch data using asArray() or declare a property e.g. `public $groupName` on the model and change your select to populate that:

```php
    ->select("t.id, t.name AS text, g.name AS groupName") // <- note alias name
```

**Comment by iamwebdesigner** [comment]
@cebe I have `asArray` set to `true` in my query:
```php
Category::find()
    ->alias('t')
    ->joinWith(['group g'])
    ->asArray(true)  // <- NOTE I set it to true
    ->where('t.parentid IS NOT NULL')
    ->select("t.id, t.name AS text, g.name AS group")
    ->all();
```

**Comment by SilverFire** [comment]
@iamwebdesigner what are you getting in the result of this query, what is expected and what SQL is being executed?

**Comment by lynicidn** [comment]
http://dev.mysql.com/doc/refman/5.7/en/keywords.html group is reserver

**Comment by lynicidn** [comment]
```
`group`
```

**Comment by iamwebdesigner** [comment]
@SilverFire I get correct SQL (I run it on database IDE and I get correct results), the results presented by PDO are correct too (I found out it when debugging). I get my `group` key overidden in each row by method `findWith`: https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQueryTrait.php#L160 of line https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQueryTrait.php#L173 I guess the reason is the clash with the relation's name

**Comment by cebe** [comment]
> I have found that query return correct data, but on mapping stage group is lost.

what do you mean with that? if you use asArray, there is no "mapping step".

**Comment by iamwebdesigner** [comment]
@cebe I mean relations mapping, please check my comment above

**Comment by cebe** [comment]
okay so maybe what you want is joinwith without eager loading?

```
    ->joinWith(['group g'], false)
```

**Comment by iamwebdesigner** [comment]
@cebe this one is working, thanks
