### ISSUE TITLE
[ActiveQuery] When I use parent::findOne(), the return value is an instance of current class.

### ISSUE THREAD

**Issue by takashiki** [yiisoft/yii2#11496]
### What steps will reproduce the problem?

```php
class Article extends ActiveRecord
{
}

class ArticleForm extends Article 
{
    public function getModel($id)
    {
         return parent::findOne($id);
    }
}

$model = (new ArticleForm())->getModel(1);
var_dump($model);
```

### What is the expected result?

$model is instance of Article.

### What do you get instead?

$model is instance of ArticleForm.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      |  5.6
| Operating system |  linux

**Comment by Faryshta** [comment]
This is a known issue because of the way `get_current_class()` works, it can't be solved on php5.4

You have to use `get_parent_class()` and store the result in a variable.

```php
$parentClass = get_parent_class();
return $parentClass::findOne($id);
```

**Comment by lynicidn** [comment]
return Article::fineOne()

**Comment by takashiki** [comment]
In fact, function getModel is written in a trait, so `return Article::findOne()` is not very practical.

**Comment by spiritdead** [comment]
i have the same problem :S

**Comment by Faryshta** [comment]
mmmm if its inside a trait then `parent` wouldn't work either not even in php5.5+

**Comment by takashiki** [comment]
ok, I got it.

**Comment by SilverFire** [comment]
Thank you @Faryshta
