### ISSUE TITLE
gzip in requirements.php

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11495]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.x
| Operating system | ---

can add the verification of GZIP support in the requirements.php ?

regards

**Comment by mdmunir** [comment]
https://github.com/yiisoft/yii2-app-advanced/blob/master/requirements.php#L48-L50

**Comment by SilverFire** [comment]
Thank you @mdmunir
