### ISSUE TITLE
SluggableBehavior causes memory exhausting with unique slug

### ISSUE THREAD

**Issue by bizley** [yiisoft/yii2#11492]
The reason for this is UniqueValidator misconfiguration but at the moment it is not detected and causes memory exhausting through infinite validation loop.

With the current SluggableBehavior construction it is not possible to throw exception informing about this but should not be that difficult to fix. Anyway - just reporting this for your information.

### What steps will reproduce the problem?

1. Create DB table with 'name' and 'slug' columns (among others).
2. Create ActiveRecord model for the table.
3. Add few records there with the same 'name'.
4. Add behavior configuration for the AR:

```php
    public function behaviors()
    {
        return [
            [
                'class'           => \yii\behaviors\SluggableBehavior::className(),
                'immutable'       => false,
                'attribute'       => 'name',
                'ensureUnique'    => true,
                'uniqueValidator' => ['targetAttribute' => 'name'],
            ]
        ];
    }
```
(```targetAttribute``` **does not** include slug attribute)
5. Update one of the previously added records.

### What is the expected result?

InvalidConfigException thrown "UniqueValidator configuration doesn't allow to create unique slug".

### What do you get instead?

Fatal error - memory exhausted.

### Additional info

I know this is because of the UniqueValidator misconfiguration. [makeUnique()](https://github.com/yiisoft/yii2/blob/master/framework/behaviors/SluggableBehavior.php#L204) method enters infinite loop here. Still - this configuration is good for one DB row so cannot be rejected all the time.
We could detect the problem by checking the validation query - if it's the same on the second loop iteration it means the validation will always return false - and exception can be thrown. The problem is there is no easy way to check this query right now.

What do you think?

**Comment by SilverFire** [comment]
It's just another way how you can shoot yourself in the foot :) Thank you for the report, but I don't think that it's really necessary to introduce more logic for each slug generation just to prevent misconfiguration.

**Comment by Faryshta** [comment]
@SilverFire i agree this is a missconfiguration, but I wanna call your attention on something else.

```php
    protected function validateSlug($slug)
    {
        /* @var $validator UniqueValidator */
        /* @var $model BaseActiveRecord */
        $validator = Yii::createObject(array_merge(
            [
                'class' => UniqueValidator::className()
            ],
            $this->uniqueValidator
        ));
        $model = clone $this->owner;
        $model->clearErrors();
        $model->{$this->slugAttribute} = $slug;
        $validator->validateAttribute($model, $this->slugAttribute);
        return !$model->hasErrors();
    }
```

Wouldn't it make sense to make `$validator` and `$model` into static variables so they are not created and destroyed each validation?

**Comment by bizley** [comment]
I would like also to suggest optimisation of default unique slug creation mechanism. Instead of checking every ```slug-N+1``` existing entry we could get the highest ```N``` at the beginning so for 101st row with the same base slug we can do 2 queries instead of 102.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/pull/4675#discussion_r16093242
