### ISSUE TITLE
Add ability for ArrayDataProvider to generate column labels when data array is empty

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#11490]
Add a new property `ArrayDataProvider::modelClass` to manually specify which model `ArrayDataProvider` must use to generate column labels. This change will allow `ArrayDataProvider` to correctly generate column labels using `Model::getAttributeLabel()` method when provided data array is empty.

**Comment by PowerGamer1** [comment]
Implemented in https://github.com/yiisoft/yii2/pull/11491.

**Comment by SilverFire** [comment]
Merged: https://github.com/yiisoft/yii2/commit/7cfd454bd1350223c2de6400570adbcb1c48bba4
