### ISSUE TITLE
yii.initScriptFilter cancel ajax request with different data params

### ISSUE THREAD

**Issue by airmoi** [yiisoft/yii2#11494]
While implementing fullcalendar with gcal plugin to load holidays in my project, I experienced an issue I couldn't figure out :
The first month was properly loaded, but when I tried to change view to another month, nothing was loaded from google API (no ajax call was made)

After hours of debugging, I finally found that ajax query was cancelled before it was sent by a function in yii.js : yii.initScriptFilter.

As I understand, this function prevent from loading already loaded scripts, but it only uses the requested url to detect them without any consideration for data params, which in my case was preventing google API to be called to get next month events as the url is stile the same but params are store in the data attribute.

I noticed there is an option to set a "reloadable" list of scripts, but in my case, I have no control on it as the url is generated on the fly by fullcalendar's gcal plugin (except if I change plugin's code which is was I did to unlock the situation). 

Also, shouldn't it take in consideration the "cache" option stored in the ajax call ? 

I think line 383 of yii.js should be change to append the data options to the url before you store it to loadedScripts array :
`var url = options.url.charAt(0) === '/' ? hostInfo + options.url : options.url;`
With something like this : 
`var url = (options.url.charAt(0) === '/' ? hostInfo + options.url : options.url) + options.data;`

Yii version   2.0.7  
PHP version  5.6   
Operating system  OSX 10.10

**Comment by spiritdead** [comment]
@airmoi  update to yii 2.0.8 and test again :)

**Comment by airmoi** [comment]
Sorry, il misstyped yii's version, I also updated to 2.0.8, and I stile had the issue

Romain Dunand

**Comment by cebe** [comment]
Not sure I understand what is going on here. Why would you load the exact same URL via script tag and expect it to return different data? Also if the response is JSONP, yii will not cache it. Please give more information about how this works. also links to the libraries you are using would be helpful.

**Comment by airmoi** [comment]
Because of post data, the url is still the same, but post data differs, so results also differs.

I'm using this lib : 
https://github.com/philippfrenzel/yii2fullcalendar
with fullcamendar gcal extension  : https://raw.githubusercontent.com/fullcalendar/fullcalendar/master/src/gcal/gcal.js (http://fullcalendar.io/docs/google_calendar/)

**Comment by Rjgoolsby** [comment]
Any update on this? I'm running into the same issue. Airmoi, you said you changed gcal's code. What was your workaround?

**Comment by cebe** [comment]
As far as I understand, your requests are JSONP, can you explain why this condition does not match then? https://github.com/yiisoft/yii2/blob/993f2aef28851a888878eaedb84db8233dfc12a3/framework/assets/yii.js#L379

**Comment by Rjgoolsby** [comment]
Unfortunately, the data type being returned is json (see attached photo). 
I changed yii.js it to account for this oddity: 
```
if (options.dataType == 'jsonp' || options.dataType == 'json') {
   return;
}
```
then I overrode the Yii Asset with my version of yii.js. I don't know if this is worth changing as I don't know the unintended consequences (I'm going to continue and if something arises I'll address it then). 

Disclaimer: I haven't fully inspected gcal.js. I'm going to do that today.  

<img width="1097" alt="screen shot 2016-08-04 at 9 51 47 am" src="https://cloud.githubusercontent.com/assets/10386821/17404397/7a72ab42-5a29-11e6-87ba-ce4356c09717.png">

**Comment by SilverFire** [comment]
You can specify the URL to your JSON resource in [reloadableScripts](https://github.com/yiisoft/yii2/blob/993f2aef28851a888878eaedb84db8233dfc12a3/framework/assets/yii.js#L50)

Does it solves your problem?

**Comment by Rjgoolsby** [comment]
.... That moment where you realize the solution was right in your face *face palm*. This will work. Thanks for the help. I've totally overlooked that this entire time.

**Comment by cebe** [comment]
it was mentioned in the original issue report that this option was not possible for some reason:

> I noticed there is an option to set a "reloadable" list of scripts, but in my case, I have no control on it as the url is generated on the fly by fullcalendar's gcal plugin (except if I change plugin's code which is was I did to unlock the situation).


@airmoi any comments?

**Comment by airmoi** [comment]
Hi, 

Sorry for late answer
Thank for reopening the issue as the reloadableScripts workaround is not suitable in my case (script url is not predictable as it is generated by a third party script).

Has I mentioned in the first thread, the issue is that the filter is applied regardless data params in the ajax query. It occurs with fullCalendar's gcal plugin, but I guess it may also occurs with some other third party libraries.

Here is a JsFiddle example (you'll have to provide a google API key for tests)
https://jsfiddle.net/11tmv4ce/

Just add a breakpoint line 383 of yii.js after first load, then go to previous/next month, you'll see call being cancelled because the option.url is always the same, but options.data differs

**Comment by airmoi** [comment]
@Rjgoolsby as a workaround, I changed gcal's line 75 to append a timestamp to the base url : 
`var url = API_BASE + '/' + encodeURIComponent(sourceOptions.googleCalendarId) + '/events?callback=?&_=' + jQuery.now(); // jsonp`

For now it works, but this is not a confortable situation as this is a third party script I shouldn't have to edit

**Comment by Alex-Code** [comment]
I think URL params will need to be included in the `loadedScripts` array or have something like a wildcard option.
```javascript
reloadableScripts.push('https://www.googleapis.com/calendar/v3/calendars/*');
```
The `*` would denote that any URL that starts with `...` would be reloadable.
