### ISSUE TITLE
RenderPartial Issue

### ISSUE THREAD

**Issue by apickstock** [yiisoft/yii2#11501]
I am producing email to queue, with the message content from a renderPartial Layout.
$queue->message = $this->renderPartial('/emaillayouts/exemail', ['model' => $model]);
When i run the code in 2.0.8 the rendered content is produced onscreen above the existing layout. this wasn't in the case of Yii 2.0.7

in 2.0.7 the renderPartial isn't rendered to screen
i have reverted down to 2.0.7 all now ok.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8 
| PHP version      | 5.5 & 5.6
| Operating system | Windows 2012 R2 Server Running IIS

**Comment by SilverFire** [comment]
Can you find a commit that introduced the problem with `git bisect`?

**Comment by SamMousa** [comment]
Are you sure there is no `ob_flush` or similar statement in your view? As far as I can tell there have been no changes in `BaseMailer` or `View` that would change output handling.

**Comment by cebe** [comment]
closing because no information provided.
