### ISSUE TITLE
As of MySQL 5.7.5, the default SQL mode includes STRICT_TRANS_TABLES.

### ISSUE THREAD

**Issue by turboezh** [yiisoft/yii2#11503]
### What steps will reproduce the problem?
```
CREATE TABLE the_table
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  the_field VARCHAR(255)
);
```
```
class m160504_162839_the_migration extends Migration
{
    public function up()
    {
        // set by default in MySQL >= 5.7.5
        //$this->execute("SET sql_mode='STRICT_TRANS_TABLES'");

        $this->truncateTable('the_table');
        $this->insert('the_table', ['the_field' => 'test']);
        $this->update('the_table', ['the_field' => 2], ['the_field' => 1]);

        // but this will pass in strict mode -> `['the_field' => '1']`
        // $this->update('the_table', ['the_field' => 2], ['the_field' => '1']);
    }

    public function down()
    {
        return false;
    }
}
```

### What is the expected result?
Migration passes.

### What do you get instead?
```
*** applying m160504_162839_the_migration
    > truncate table the_table ... done (time: 0.095s)
    > insert into the_table ... done (time: 0.019s)
    > update the_table ...Exception 'yii\db\Exception' with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'test'
The SQL being executed was: UPDATE `the_table` SET `the_field`='2' WHERE `the_field`=1'

in /home/alex/www/billing2/www/app/vendor/yiisoft/yii2/db/Schema.php:628

Error Info:
Array
(
    [0] => 22007
    [1] => 1292
    [2] => Truncated incorrect DOUBLE value: 'test'
)
```

### Additional info

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict
"As of MySQL 5.7.5, the default SQL mode includes STRICT_TRANS_TABLES."

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | PHP 7.0.4-7ubuntu2 (cli) ( NTS )
| MySQL              | mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64)
| Operating system | Ubuntu 16.04

**Comment by SilverFire** [comment]
Well, I don't really understand how does Yii belong to the problem. Could you explain, please?

**Comment by turboezh** [comment]
Yii doesn't belong to this directly. But MySQL default behavior has been changed and it brings some backward incompatible pieces of code (I've brought only one posible case, and it's real one I've faced). Should Yii handle this or left it to an end-user is the decision to be made, I think.

**Comment by samdark** [comment]
That's expected. You've passed invalid data and MySQL errored. Yii should not try to correct it.
