### ISSUE TITLE
ActiveQuery create model not through dependency injection

### ISSUE THREAD

**Issue by Liv1020** [yiisoft/yii2#11505]
### What steps will reproduce the problem?
```
\Yii::$container->set('app\models\Order', 'app\resources\Order');

$product = Product::findOne(1);
$orders = $product->orders;

//$order not app\resources\Order
```
### What is the expected result?
```
\Yii::$container->set('app\models\Order', 'app\resources\Order');

$product = Product::findOne(1);
$orders = $product->orders;

//$order == app\resources\Order
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | centos7

**Comment by Liv1020** [comment]
yii core should call any class through dependency injection(Yii::createObject())

**Comment by cebe** [comment]
no, it should not. If you want to replace an existing class in the framework, you can set it in `Yii::$classMap`. No idea why you would do that in your application...
