### ISSUE TITLE
activefield widget disabled option

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11508]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.x
| Operating system | win

im trying find documentation or any but when i try this i get errors

$form->field($model, 'name')->widget(MaskedInput::className(),['mask' => '*{4,5}','disabled' => true])
Setting unknown property: yii\widgets\MaskedInput::disabled

not only in this plugin is in all widgets, how can define the attribute disabled :/

if i define 'options' => ['disabled' => true], this lost the class and we need define directly too

**Comment by HaruAtari** [comment]
It happened becauce `options` argument override default value in constructor. You can do this:
```php
$form
    ->field($model, 'name')
    ->widget(MaskedInput::className(),[
        'mask' => '*{4,5}', 'options'=>[
            'disabled' => true,
            'class' => 'form-control',
        ]
    ]);
```

**Comment by samdark** [comment]
That's expected behavior.
