### ISSUE TITLE
problem with attributes in mayus like ifToggled activeField

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11509]
### What steps will reproduce the problem?

im adding attributes with mayus (ifToggled) and this render in lower (iftoggled)

### What is the expected result?

if i define in mayus the attribute ifToggled the render display the same result ifToggled

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.x
| Operating system | win

im using this

```php
<?= $form->field($model,'bird_external')->checkbox(['class' => 'i-checks','ifToggled' => $jsExternals]) ?>
```

and the render display

```php
<input type="checkbox" id="bird-bird_external" class="i-checks" name="Bird[bird_external]" value="1" iftoggled="    $(&quot;#bird-name&quot;).prop(&quot;disabled&quot;,!this.checked);" style="position: absolute; opacity: 0;">
```

if can see the attribute iftoggled is lowecapped

steps to reproduce:

add any attribute in mayus, and the rendered is lowercapped

**Comment by samdark** [comment]
It can't be. We're not transforming attribute case. Most probably you're checking in Chrome web inspector which does that. Check page source instead.

**Comment by spiritdead** [comment]
@samdark  if i define the attribute 

why if this work

$js = <<<JS
    $('input#bird-bird_external').on('ifToggled',function(event){ $("#bird-name").prop("disabled",!this.checked);});
JS;
$this->registerJs($js);

why the other option cant work and the problem is the uppercase in the params

**Comment by samdark** [comment]
I can't confirm it at all. Please provide steps to reproduce the problem starting with basic app template.

**Comment by spiritdead** [comment]
@samdark 

in the example i used this http://icheck.fronteed.com/

```php
$jsExternals = 'console.log("hello");';
<?= $form->field($model,'bird_external')->checkbox(['class' => 'i-checks','ifToggled' => $jsExternals]) ?>
```
you can see if work in the console of the browser, and the event is never fired

but when you add using this method (jquery directly) work

```php
$js = <<<JS
    $('input#bird-bird_external').on('ifToggled',function(event){ $("#bird-name").prop("disabled",!this.checked);});
JS;
$this->registerJs($js);
```

**Comment by samdark** [comment]
Well, `'ifToggled' => $jsExternals` isn't about event handling at all. It sets attribute value.

**Comment by samdark** [comment]
If you absolutely want JavaScript in the value, check http://www.yiiframework.com/doc-2.0/yii-web-jsexpression.html
