### ISSUE TITLE
Error with yii2-authclient

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2#11518]
Hi,

Could someone take a look and advise please?

Thanks

**### What steps will reproduce the problem?**
Register web application with twitter or facebook and attempt social sign up or login. (sorry - edit, this error ALSO occurs with google and linkedin)

**### What is the expected result?**
Successful logon to application via social network with the help of yii2-authclient

**### What do you get instead?**
exception 'yii\base\ErrorException' with message 'Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT'' in /var/www/domain.com/vendor/yiisoft/yii2-authclient/BaseOAuth.php:244
Stack trace:
#0 /var/www/domain.com/vendor/yiisoft/yii2-authclient/BaseOAuth.php(244): yii\base\ErrorHandler->handleError(8, 'Use of undefine...', '/var/www/versit...', 244, Array)
#1 /var/www/domain.com/vendor/yiisoft/yii2-authclient/BaseOAuth.php(179): yii\authclient\BaseOAuth->defaultCurlOptions()
#2 /var/www/domain.com/vendor/yiisoft/yii2-authclient/OAuth1.php(163): yii\authclient\BaseOAuth->sendRequest('POST', 'https://api.twi...', Array, Array)
#3 /var/www/domain.com/vendor/yiisoft/yii2-authclient/OAuth1.php(82): yii\authclient\OAuth1->sendSignedRequest('POST', 'https://api.twi...', Array)
#4 /var/www/domain.com/vendor/yiisoft/yii2-authclient/AuthAction.php(319): yii\authclient\OAuth1->fetchRequestToken()
#5 /var/www/domain.com/vendor/yiisoft/yii2-authclient/AuthAction.php(195): yii\authclient\AuthAction->authOAuth1(Object(dektrium\user\clients\Twitter))
#6 /var/www/domain.com/vendor/yiisoft/yii2-authclient/AuthAction.php(177): yii\authclient\AuthAction->auth(Object(dektrium\user\clients\Twitter))
#7 [internal function]: yii\authclient\AuthAction->run()
#8 /var/www/domain.com/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#9 /var/www/domain.com/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array)
#10 /var/www/domain.com/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('auth', Array)
#11 /var/www/domain.com/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/security/a...', Array)
#12 /var/www/domain.com/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 /var/www/domain.com/frontend/web/index.php(22): yii\base\Application->run()
#14 {main}

**### Additional info**

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | PHP 5.5.9-1
| Operating system | ubuntu4.16

**Comment by lynicidn** [comment]
sudo apt-get install php5-curl
