### ISSUE TITLE
Why in class ActiveRecord method attributes() non static ?

### ISSUE THREAD

**Issue by axklim** [yiisoft/yii2#11517]
### What steps will reproduce the problem?
Why in class ActiveRecord method attributes() non static ?

`
    public static function primaryKey()
    {
        return static::getTableSchema()->primaryKey;
    }

    /**
     * Returns the list of all attribute names of the model.
     * The default implementation will return all column names of the table associated with this AR class.
     * @return array list of attribute names.
     */
    public function attributes()
    {
        return array_keys(static::getTableSchema()->columns);
    }

`
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.21
| Operating system | Debian 7.10

**Comment by axklim** [comment]
sorry for my petty comments =)

**Comment by klimov-paul** [comment]
See #1318
