### ISSUE TITLE
Prevent auto auth status renew from PHP session when user authKey changed

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#11512]
The same user can have several active sessions (for ex., from different devices). Sometimes it is necessary to invalidate all active user sessions (for example, right after the password change). Currently the framework does not provide such functionality but it can be easily implemented similar to how it is done for cookie-based auto-login - by storing user identity authKey (`IdentityInterface::getAuthKey()`) in the session along with user ID and checking if this key remained the same before doing auto-login based on ID value stored in the $_SESSION.

Then if someone wants to invalidate all active sessions for a user he only needs to change the return value of `IdentityInterface::getAuthKey()` for that user.

**Comment by kidol** [comment]
Made basically the same patch some time ago: #9746

**Comment by PowerGamer1** [comment]
I implemented the feature in https://github.com/yiisoft/yii2/pull/11513 but looks like it will break BC because currently `IdentityInterface::getAuthKey()` is allowed to be unimplemented if `yii\web\User::enableAutoLogin` is `false` and my patch requires `IdentityInterface::getAuthKey()` to be implemented always. Still, I think the described feature should be built into the framework.

**Comment by PowerGamer1** [comment]
@kidol 
> Made basically the same patch some time ago: #9746

Indeed my solution is basically a duplicate of yours in every aspect.
