### ISSUE TITLE
Using oci_bind_by_name() with createCommand()

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#11514]
### What steps will reproduce the problem?

`PLS-00382: expression is of wrong type`

`
    $c = oci_connect($host, $pass, $db) or die;
    // set cursor
    $refcur = oci_new_cursor($c);

    $q = "BEGIN :RC := REPORT_CARDS.GET_DATA(:I_YEAR); END;";
    $data = Yii::$app->db->createCommand($q)
                         ->bindParam(':I_YEAR', $s, PDO::PARAM_INT)
                         // will this line below work with Yii2?
                         ->bindParam(':RC', $refcur, NULL, -1, OCI_B_CURSOR)
                         ->execute(); // or ->queryAll()`

### What is the expected result?
That data is returned, which it is using plain PHP.

`$stid = oci_parse($conn, "BEGIN :RC := REPORT_CARDS.GET_DATA(:I_YEAR); END;");
	// get cursor
	$refcur = oci_new_cursor($c);
	
	$I_YEAR = 2014;

	// Bind the input parameter
	oci_bind_by_name($stid,':I_YEAR', $P_YEAR, 4);
	oci_bind_by_name($stid, ':RC', $refcur, -1, OCI_B_CURSOR);

	oci_execute($stid);
	
	oci_execute($refcur);
	oci_fetch_all($refcur, $res);
	var_dump($res);`

### What do you get instead?

`PLS-00382: expression is of wrong type`

A couple of things are:
1 - I'm unsure how to call oci_new_cursor() with my existing DB connection, I tried Yii::$app->db, but it failed? So I just hard coded it into a new oci_connect().

2 - How to use `oci_bind_by_name()` with createCommand() properly within Yii2? Is it possible or do I need to use plain PHP here?

**Comment by lynicidn** [comment]
https://www.google.ru/search?q=PLS-00382:+expression+is+of+wrong+type&ie=utf-8&oe=utf-8&gws_rd=cr&ei=mokrV9mCNMuwsQGSnqL4BQ

**Comment by jonny7** [comment]
@lynicidn I have looked at it through Google. I still can't bind the $refur param using `->bindParam(':RC', $refcur, OCI_B_CURSOR, -1)`

**Comment by lynicidn** [comment]
first link contains


Change the datatype of sqlCommand from NVARCHAR2 to varchar2. Execute immediate expects varchar, varchar2 or char. Code given below should work

**Comment by jonny7** [comment]
@lynicidn So the $refcur needs to be a `PDO::PARAM_STR`? Why?

**Comment by lynicidn** [comment]
don't know, but it problem not in yii

**Comment by jonny7** [comment]
It is if oci_bind_by_name() can't be used within createCommand() and needs a feature request.

**Comment by lynicidn** [comment]
http://php.net/manual/en/function.oci-bind-by-name.php
look here

**Comment by lynicidn** [comment]
ah yeah in context yii in can not work you not set cursor on execute

**Comment by lynicidn** [comment]
u use http://php.net/manual/ru/ref.pdo-oci.php ?

**Comment by jonny7** [comment]
@klimov-paul Can I feature request this and a fuller OCI set of tools?
