### ISSUE TITLE
Implement an loading Image

### ISSUE THREAD

**Issue by tambey** [yiisoft/yii2#11525]
### What steps will reproduce the problem?
I'am new in yii2. I wanna show an loading image after user click the link.

index.php

```
<style type="text/css">
    
    .loading{
       background-image: url('http://dkclasses.com/images/loading.gif');
       background-position: center center;
       background-repeat: no-repeat;
    }
    
    .error
    {
       background-image: url('http://dkclasses.com/images/loading.gif');
       background-position: center center;
       background-repeat: no-repeat;
    }
   
</style>

<?php
use yii\helpers\Html;    

echo Html::a(
        'Go To the link',
        array('users/datum'),
        array(
            'update'=>'#resultat',
            'beforeSend' =>"function(){
                   $('#colorId').addClass('loading'); 
            }",
            'complete'=>"function(){ 
                $('colorId').removeClass('loading');
            }",
            'error'=>"function(){ 
                $('colorId').addClass('error');
            }"
        )
        );
?>

```
```
<div id="colorId" class="loading"></div>

<div id="resultat">
    Hello World
</div>
```

UsersController.php
`  public function actionIndex()
    {
                return $this->render('index');
    }`
### What is the expected result?
I couldnt see the loading image. Any one knows where can be the problem.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 
| PHP version      | 
| Operating system |

**Comment by lynicidn** [comment]
'#resultat' - палишься
а вообще тебе на форум

**Comment by tambey** [comment]
No. not #resultat is not the Problem. but thank you

**Comment by tambey** [comment]
i am registered in the [http://www.yiiframework.com/forum/](support forum) but i can not start a new Topic.
