### ISSUE TITLE
[php 7.0.*]IntlException  Constructor failed in vendor/yiisoft/yii2/i18n/MessageFormatter.php

### ISSUE THREAD

**Issue by hezll** [yiisoft/yii2#11528]
### What steps will reproduce the problem?
vendor/yiisoft/yii2/i18n/MessageFormatter.php

about line 101

        $formatter = new \MessageFormatter($language, $pattern); //the problem is here.
        if ($formatter === null) {
            $this->_errorCode = intl_get_error_code();
            $this->_errorMessage = 'Message pattern is invalid: ' . intl_get_error_message();

when MessageFormatter has some problems with construct
this will call a IntlException immediately due to the new exception feature under php7 
### What do you get instead?
I just add up 

    try{
        $formatter = new \MessageFormatter($language, $pattern);
    }cache(\IntlException $e){
        $formatter = null;
    }

This helps me fix it.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7.0.*
| Operating system | centos 6.5

**Comment by cebe** [comment]
in previous php versions this resulted in the constructor to create a NULL formatter. Needs to be fixed.

**Comment by tom--** [comment]
Judging from these patterns https://3v4l.org/94MvA I would say

- This constructor should not throw in php7 but return an empty object
- Yii should test with `empty($formatter)` instead of `$formatter === null`

**Comment by cebe** [comment]
Looks like HHVM also has a different implementation... :-/
