### ISSUE TITLE
[php 7.0.*]Uninitialized string offset: 0 1. in /data/wwwroot/app/vendor/yiisoft/yii2/web/Request.php

### ISSUE THREAD

**Issue by hezll** [yiisoft/yii2#11526]
### What steps will reproduce the problem?
I just run xxx/index.php in php 7.0.1, how ever there is a notice error of Uninitialized string offset: 0
come from in /data/wwwroot/webstore/vendor/yiisoft/yii2/web/Request.php

line 726

if ($pathInfo[0] === '/') {
            $pathInfo = substr($pathInfo, 1);
        }

the reason may be that under php 7.0.* , $pathInfo is false and no string offset 0 is existed.

### What is the expected result?
the correct index page
### What do you get instead?

I just add the data type checking.
     if (is_array($pathInfo)&&$pathInfo[0] === '/') {
             $pathInfo = substr($pathInfo, 1);
        }

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.6
| PHP version      | php 7.0.3
| Operating system | window&centos

**Comment by rob006** [comment]
It has been fixed in v2.0.7.

**Comment by hezll** [comment]
by the way，how about the intlException ?
vendor/yiisoft/yii2/i18n/MessageFormatter.php
try{
        $formatter = new \MessageFormatter($language, $pattern);
}catch(\IntlException $e) {
$formatter= null;
}

**Comment by hezll** [comment]
I add a try catch for fixing it temporarily.
