### ISSUE TITLE
yii\db\QueryBuilder, buildInCondition Bug / Upgrade note required

### ISSUE THREAD

**Issue by ryusoft** [yiisoft/yii2#11536]
### What steps will reproduce the problem?
For 'IN' condition, 3rd operand now cannot support none-array value, where in 2.0.7 is accepted, and this change not listed in upgrade note. e.g.
```
$ids = 1;
$query->andWhere(['IN', 'id', $ids]);
//if $ids is not array, will get error at QueryBuilder, line: 1186, where the "$values" is not array
```
 suggest to add in upgrade note, or add (array) conversion for variable $values
### What is the expected result?
expected to work as in 2.0.7, not sure any reason to change.

### What do you get instead?
Error, line 1186

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.5.9
| Operating system | Linux

**Comment by klimov-paul** [comment]
Caused by commit baab8d6a68e46394c04125eef094003527ab08e1 from PR #10961

**Comment by klimov-paul** [comment]
Previously there was a typecast for the values to `array`, which have been removed.
However there is a question remains if using of scalar value was allowed at the first place or not.

**Comment by cebe** [comment]
fixed.
