### ISSUE TITLE
What if I want same value for multiple checkbox list : checkboxList()

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#11533]
### What steps will reproduce the problem?

I need check box list with below name and value:

Name 1 : Val1
Name 2 : Val2
Name 3 : Val1

### What is the expected result?

Actually it should load three checkboxes but instead it is loading only two because the array key become same.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      |  5.5.12
| Operating system | Win 8 (64 bit)

**Comment by SilverFire** [comment]
Could you show your code?

**Comment by avinashz** [comment]
@SilverFire Well, I have system where I am getting name and value from user and that become a value and label for check box list. 

I am having certain cases where user have entered same with the different name. Array which gets generated here will remove the duplicates because same key occurs. 

But with the case of checkbox it is valid if multiple checkbox having the same value.

**Comment by SamMousa** [comment]
@avinashz, we can't turn the arrays / keys around since that would cause the same issue but with labels instead of values.

As a workaround you could use the formatter:
````
$selected = 1;
Html::checkboxList('name', null, [
    ['value' => 1, 'label' => 'label 1'],
    ['value' => 1, 'label' => 'label 2']
    ['value' => 2, 'label' => 'label 3']
], [
    'formatter' => function($index, $label, $name, $checked, $checkbox) use ($selected) {
        Html::checkbox($name, $checkbox['value'] === $selected, [
           'value' => $checkbox['value']
           'label' => $checkbox['label']
        ]);
    }
]);
````
Note that there is no need for you to use the `checkboxList` helper function; in your case it might make more sense to just loop over your list and render checkboxes using `Html::checkbox`.

@yii-core-developers: We could add support for duplicate values by supporting the alternative syntax I used above natively. This would not break BC since passing in a label of type `array` currently fails.

**Comment by avinashz** [comment]
@SamMousa thanks for this. I don't want to turn array/key here. Actually, what I was looking for is requested by you to the Core team :+1:

**Comment by SilverFire** [comment]
The workaround suggested by @SamMousa is fine.

We could extend `$items` parameter of the `Html::checkboxList()` method to make it possible to pass something like

```php
    ['value' => 1, 'label' => 'label 1'],
    ['value' => 1, 'label' => 'label 2']
    ['value' => 2, 'label' => 'label 3']
```

but I'm afraid that we'll get additional if-conditions and over complicated code for no good reason.

**Comment by avinashz** [comment]
@SamMousa any input on how to how to achieve the same for dropdownList? that one accept the same kind of array param and hence the same issue.

**Comment by SamMousa** [comment]
@avinashz Not sure there is anything you can really hook into for that. You could always render the options manually. Alternatively you could provide an `ArrayObject` that uses objects that implement `__toString()` as keys. Theoretically iterables can have duplicate keys, the basic php array just can't.
