### ISSUE TITLE
Illegal offset type in isset or empty when using CompareValidator

### ISSUE THREAD

**Issue by gdiazderadaa** [yiisoft/yii2#11531]
### What steps will reproduce the problem?

1. Setup a CompareValidator in a form

 ```
    public function rules()
    {
        return [
            [['parent_model_id', 'model_id'], 'required'],
            [['parent_model_id', 'model_id'], 'integer'],
            [['parent_model_id'], 'unique', 'targetAttribute' => ['parent_model_id', 'model_id']],
            [['parent_model_id'], 'compare', 'compareAttribute' => ['model_id'], 'operator' => '!='],
        ];
    }
```
2. Open the form in a browser to get the following error:

yii2\db\BaseActiveRecord.php, line 1498

```
    public function getAttributeLabel($attribute)
    {
        $labels = $this->attributeLabels();
        if (isset($labels[$attribute])) {
          ...
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 5.5.28
| Operating system | Windows 7

**Comment by cebe** [comment]
compareAttribute must be a string, not an array: http://www.yiiframework.com/doc-2.0/yii-validators-comparevalidator.html#$compareAttribute-detail

**Comment by gdiazderadaa** [comment]
Thanks @cebe
