### ISSUE TITLE
Enviroment

### ISSUE THREAD

**Issue by sozidatel79** [yiisoft/yii2#11538]
### What steps will reproduce the problem?
define the project as developer environment
Is no problem with rights or owner.
i have set  0777 on the all directories to be sure is no write issue when i deploy the init  file.
### What is the expected result?
Is no debug panel on the bottom presented.
### What do you get instead?
Just clean footer with credits.
### Additional info
http://gadgets-market.com/
| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 7.0.4
| Operating system | ubuntu server 16.04

**Comment by slinstj** [comment]
You have not said, so, do you have `debug` enabled in your configs?
```
$config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
    ];
```

**Comment by cebe** [comment]
debug toolbar access is restricted by IP address. Also in production environment you should not use 0777 permissions.

**Comment by sozidatel79** [comment]
"Also in production environment you should not use 0777 permissions"
you right, i did it just for check. actually i use 644.
I newbie in Yii2.
