### ISSUE TITLE
jQuery loading after yii.js

### ISSUE THREAD

**Issue by shubham994** [yiisoft/yii2#11542]
### I have created a new yii2 project in which I have stopped jQuery from web.php. Now I have created a jQueryAsset and added it to depends part of AppAsset. But when i run the project yii.js loads before jQuery.js
Here Is my Code:

JqueryAsset

`class JqueryAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $js = [
    		'js/jquery.min.js',
    ];
}`

AppAsset

` public $depends = [
    		'app\assets\JqueryAsset',
        	'yii\web\YiiAsset',
        	'yii\bootstrap\BootstrapAsset',
    ];`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.5.12
| Operating system | Windows

**Comment by cebe** [comment]
that is because yii.js does not know about the new jQuery. You have to define a dependecy for the new Jquery Asset in assetmanager:

```
                'yii\web\YiiAsset' => [
                    'depends' => [
                        'app\assets\JqueryAsset',
                    ],
                ],
```
