### ISSUE TITLE
Dependency of input ids into the whole framework

### ISSUE THREAD

**Issue by ericmaicon** [yiisoft/yii2#11546]
Imagine that your application request two tabs of the same form. The system also has a button that add more tabs as the user will using it. 

**_tab.php**
~~~php
<?php $form = ActiveForm::begin([
...
]); ?>
    <div class="row">
        <div class="col-sm-3">
            <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
       </div>
    </div>
<?php ActiveForm::end();?>
~~~

Bearing this in mind, because of the following code, it will reproduce an HTML with duplicated ids:

**BaseHtml.php**
~~~php
public static function activeInput($type, $model, $attribute, $options = [])
    {
        $name = isset($options['name']) ? $options['name'] : static::getInputName($model, $attribute);
        $value = isset($options['value']) ? $options['value'] : static::getAttributeValue($model, $attribute);
        if (!array_key_exists('id', $options)) {
            $options['id'] = static::getInputId($model, $attribute);
        }
        return static::input($type, $name, $value, $options);
    }
~~~

**output:**
~~~html
<input type="text" id="personsearch-first_name" class="form-control" name="PersonSearch[first_name]" maxlength="45">
~~~

Having a simple input with duplicated id is not the problem, but when you start to work with JS (MaskInput widget, datepicker...) it become a mess and nothing work anymore.

**InputWidget.php**
~~~php
public function init()
    {
        if ($this->name === null && !$this->hasModel()) {
            throw new InvalidConfigException("Either 'name', or 'model' and 'attribute' properties must be specified.");
        }
        if (!isset($this->options['id'])) {
            $this->options['id'] = $this->hasModel() ? Html::getInputId($this->model, $this->attribute) : $this->getId();
        }
        parent::init();
    }
~~~

Everything on the framework seems to be related to the id. Since the one of the ideas of a framework is to be abstract and let the user free to do anything, it shouldn't be so rigid, right?

I tried to override some classes (ActiveForm, ActiveField, HTML, MaskedInput.....) to treat it on my system, but it started to become a huge solution for a small problem. Besides, it didn't solve the problem and created others: JS validator stop working for e.g.

I guess not, since I checked the core code, but I would like to know if there is a solution to it without change my system logic (I researched here and didn't find for a duplicated issue). If not, I would like to know if someone had the same thought and if the core team is thinking about a solution to it.

Thank you in advance.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  5.6.21
| Operating system | Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016

**Comment by lynicidn** [comment]
if u set custom id for input - u must configure widget for present custom id

**Comment by mdmunir** [comment]
https://github.com/mdmsoft/yii2-widgets/blob/master/TabularWidget.php
Maybe you can get something.

**Comment by cebe** [comment]
I do not really understand the problem, if you have duplicate automatic ids, why not set them explicitly yourself?

**Comment by ericmaicon** [comment]
@mdmunir, thank you. I am checking this yet.

@cebe your advice is kind of a "hack" but it work, though.
~~~php
            <?= $form->field($model, 'postal_code')->widget(MaskedInput::className(), [
                'mask' => 'A#A-#A#',
                'options' => [
                    'id' => 'postal_code-' . $model->person_id . $model->brokerage_id,
                ]
            ]) ?>
~~~

I will finish to test @mdmunir one.

**Comment by cebe** [comment]
I would not call that a hack, this way you have a proper solution with meaningful input IDs...

**Comment by cebe** [comment]
btw, better separate the Ids, otherwise you will get problems when e.g. personid is 11 and brokerage_id is 1 or vice versa. both will produce id 111 ;)

```php
                    'id' => "postal_code-{$model->person_id}-{$model->brokerage_id}",
```

**Comment by ericmaicon** [comment]
Yes, thank you, I reached this error already. LOL

I just said about "hack" because I was expecting the framework to not require the use of id.
