### ISSUE TITLE
MySQL integer pk overflow vector

### ISSUE THREAD

**Issue by df2** [yiisoft/yii2#11541]
`yii\db\mysql\QueryBuilder`

```php
public $typeMap = [
    Schema::TYPE_PK => 'int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY',
    Schema::TYPE_UPK => 'int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY',
];
```

Max value of `int` column is 4,294,967,295 (unsigned) (http://dev.mysql.com/doc/refman/5.7/en/integer-types.html).

That's only 10 digits, so the type map should be changed to `int(10)`.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/pull/12072#issuecomment-237392712

**Comment by rob006** [comment]
@cebe 

```
mysql> CREATE TABLE `m1197_testing`.`inttest` ( `a1` INT NOT NULL , `a2` INT UNSIGNED NOT NULL ) ENGINE = InnoDB;
Query OK, 0 rows affected (0,04 sec)

mysql> DESCRIBE inttest;
+-------+------------------+------+-----+---------+-------+
| Field | Type             | Null | Key | Default | Extra |
+-------+------------------+------+-----+---------+-------+
| a1    | int(11)          | NO   |     | NULL    |       |
| a2    | int(10) unsigned | NO   |     | NULL    |       |
+-------+------------------+------+-----+---------+-------+
2 rows in set (0,01 sec)
```

MySQL 5.6

**Comment by cebe** [comment]
@rob006 thanks for checking! fixed.

**Comment by cebe** [comment]
that's actually a breaking change.

**Comment by cebe** [comment]
reverted the change: 144d78e

I'm setting this to 2.1 now but I am unsure if we should change anything as it is a subtle break that has no real value imo.

**Comment by rob006** [comment]
> that's actually a breaking change.

Why?

**Comment by cebe** [comment]
see https://github.com/yiisoft/yii2/commit/85d89e489311e20c626bcb90129c0c86978fcee4#commitcomment-18556122

**Comment by rob006** [comment]
@cebe Did you test this? I have no problems with creating FK between `INT(10) UNSIGNED` and `INT(11) UNSIGNED`.

**Comment by cebe** [comment]
according to @samdark it fails. Which MySQL version are you using?

**Comment by rob006** [comment]
Tested on MySQL 5.6.

**Comment by samdark** [comment]
Hmm... seems I was wrong and it's indeed possible. Singned/unsigned should match but MySQL is OK w/ referencing int(10) PK from int(11) FK.

**Comment by samdark** [comment]
Sorry for confusion.

**Comment by nkovacs** [comment]
> Hmm... seems I was wrong and it's indeed possible. Singned/unsigned should match but MySQL is OK w/ referencing int(10) PK from int(11) FK.

That's because the display width does not limit the range of values that can be stored in the field: http://dev.mysql.com/doc/refman/5.7/en/numeric-type-attributes.html
So it's effectively the same type. The display width is only metadata that tells the mysql client to pad it with spaces so that numbers display nicely under each other.
On the other hand, unsigned changes the type, it can no longer store values larger than 2^31-1, so if you had a signed int referencing an unsigned int, it would be possible to have ids that you cannot store in the foreign key.

**Comment by samdark** [comment]
Yes, I'm aware of the fact. Just remember that some incompatibilities were not tolerated and was sure it was display width as well.
