### ISSUE TITLE
(Bug) PostgreSql alter column on default value 

### ISSUE THREAD

**Issue by coolTr1x** [yiisoft/yii2#11540]
### What steps will reproduce the problem?
Hi. I wanted alter default value in column
```php
$this->alterColumn('categories_slides', 'is_active', $this->boolean()->defaultValue(false));
```

### What do you get instead?
`ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...ies_slides" ALTER COLUMN "is_active" TYPE boolean DEFAULT FALSE`

| Q                                | A
| --------------------------- | --------
| Yii version                   |  2.0.8
| PHP version                | 5.6
| PostgreSql version      | 9.4.7
| Operating system        | Debian GNU/Linux 7.9 (wheezy)

**Comment by coolTr1x** [comment]
In docs written, what must ```SET DEFAUL```
http://www.postgresql.org/docs/9.1/static/sql-altertable.html

**Comment by cebe** [comment]
the problem here is that for alterColumn a different syntax applies than for create table. ColumnSchemaBuilder only works for the create table syntax, there is not much we can do about that.
