### ISSUE TITLE
APl Layout Problem on yii\helpers\BaseArrayHelper::index()

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii2#11556]
FYI there is a Problem with the generated API documentation due to missing blank lines in the source code.
e.g.

```
* The result will be an associative array, where the key is the value of `id` attribute
* ```php
...
* ]
* ```
```

and following.

http://www.yiiframework.com/doc-2.0/yii-helpers-basearrayhelper.html#index%28%29-detail

**Comment by SilverFire** [comment]
Fixed by bc63b7607fce5d1282067d0d722c726280acb57a
Thank you
