### ISSUE TITLE
execute multiple commands into a prepared statement

### ISSUE THREAD

**Issue by vinairaj** [yiisoft/yii2#11555]
### How To execute multiple commands into a prepared statement In yii2 
I am  using **postgresql**. 

###  when I call a function like..

> 
SELECT proc_customer_request('cities_cur','REGISTRATION','05E000~1'); FETCH ALL IN "cities_cur"

### What do you get instead?

SQLSTATE[42601]: Syntax error: 7 ERROR: cannot insert multiple commands into a prepared statement The SQL being executed was: SELECT proc_customer_request('cities_cur','REGISTRATION','05E000~1');  FETCH ALL IN "cities_cur"

### Additional info

```
$connection = \Yii::$app->db;
$sql ="SELECT proc_customer_request('cities_cur','REGISTRATION','05E000~1');  FETCH ALL IN "cities_cur"; 
$result = $connection->createCommand($sql)->queryAll();
```

Please Help me to This.

| Q                | A
| ---------------- | ---
| Yii version      | 2
| Operating system | ubundu

**Comment by SilverFire** [comment]
Your problem is related to PDO rather than to Yii. Check out this answer: http://stackoverflow.com/a/6461110/3584248

**Comment by vinairaj** [comment]
hi,

I already checked that but it shows an error PDO not found.
how to use 
$db=new  PDO(); in yii2 and I am using postgresql.
i checked the php.ini file and enabled the extension for pdo and pgsql. and when run phpinfo(); it shows PDO and pgsql are enabled.

Please help me to do this..

**Comment by neoacevedo** [comment]
I apologize if I reopen this issue but I don't know if is exactly a PDO or a PostgreSQL problem.
On MySQL/MariaDB works fine. For instance, I need to read some sql files, one of them auth_item.sql for RBAC. On migration, works on MariaDB but not works on PostgreSQL. I haven't tested on SQL Server (I can't make work the driver) but that's the issue.
