### ISSUE TITLE
Links in Advanced template & email templates

### ISSUE THREAD

**Issue by PELock** [yiisoft/yii2#11559]
Info:

1. I'm running site with an Advanced template (Yii 2.0.8)
2. I put my email templates in "common" directory ("common" namespace)
3. Email templates generates dynamic links (in its body) for the frontend site

Now:

1. I need to send those emails from backend (admin panel) and frontend (on user action)
2. I'm using this in email templates:

`<?= Yii::$app->urlManager->createAbsoluteUrl(['site/login']) ?>`

Problem:

1. When run from the frontend it works fine (urlManager uses URL rules from the frontend)
2. When run from the backend it generates invalid links (of course)
3. When I duplicate frontend URL rules in my backend config (e.g. add urlManagerFrontend in configuration) I won't be able to generate those links in the frontend & vice-versa...

Questions:

1. Is there an easy way to use frontend link generation in both frontend & backend for common email templates?

2. Should I generate links outside of email templates in controller code (I would hate to do that)?

3. Are there any plans to make this thing more easier, maybe I'm missing something? I don't think URL rules duplication is a good solution, it's easy to miss updated entries (e.g. common URL manager rules or direct access to the frontend URL manager)?

**Comment by samdark** [comment]
1. No easy-easy way. Problem `3.` is because of which URLManager is used, right? You can introduce `getEmailUrlManager()`  that would get you a manager to use in emails.
2. Not really.
3. You can put your URL rules into separate config file and require it from both frontend and backend configs to avoid duplication. It's already in advanced template guide.

**Comment by PELock** [comment]
Thank you @samdark I did what you've said

1. Moved common rules into the \common\config\url-rules.php
2. Introduced:

```
	public function getEmailUrlManager()
	{
		if (!isset(Yii::$app->urlManagerFrontEnd))
		{
			return Yii::$app->urlManager;
		}
		else
		{
			return Yii::$app->urlManagerFrontEnd;
		}
	}
```

In common component.

PS. There should be some IsFrontend() IsBackend() functions too ;)
