### ISSUE TITLE
Debug Toolbar throws 'Bad Request (#400): Missing required parameters: tag'

### ISSUE THREAD

**Issue by kategee** [yiisoft/yii2#11557]
I have debug toolbar turned on, but in source code I see:

`<div id="yii-debug-toolbar" data-url="/debug/default/toolbar?tag=5734a917576ac" style="display:none" class="yii-debug-toolbar-bottom">Bad Request (#400): Missing required parameters: tag</div>`

**Config:**

```
'log'          => [
			'traceLevel' => YII_DEBUG ? 3 : 0,
			'targets'    => [
				[
					'class'  => 'yii\log\FileTarget',
					'levels' => [ 'error', 'warning' ],
				],
			],
		],

```

**Htaccess:**
```
RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule ^.*$ /index.php? [L]
```

**Versions:**

Yii 2.0.8
PHP 5.4.13
‪CentOS 6.5 (Final)‬

**Comment by SilverFire** [comment]
I think this problem is related to your env rather then to Yii core.

**Comment by SilverFire** [comment]
Try to change

```apache
RewriteRule ^.*$ /index.php? [L]
```

to
 
```apache
RewriteRule . index.php
```

**Comment by kategee** [comment]
For others who run into the issue @SilverFire's solution solved the issue by changing the rewriterule in .httaccess
