### ISSUE TITLE
CheckboxColumn can not  angular work after GridView reload by pajax.

### ISSUE THREAD

**Issue by twocabbages** [yiisoft/yii2#11551]
### What steps will reproduce the problem?
CheckboxColumn can not  angular work after GridView reload by pajax.

```
            $(document).off('click.yiiGridView', checkAll).on('click.yiiGridView', checkAll, function () {
                $grid.find("input[name='" + options.name + "']:enabled").prop('checked', this.checked);
                $grid.find("input[name='" + options.name + "']:enabled").addClass('checked');
            });
            $(document).off('click.yiiGridView', inputs + ":enabled").on('click.yiiGridView', inputs + ":enabled", function () {
                var all = $grid.find("input[name='" + options.name + "']").length == $grid.find("input[name='" + options.name + "']:checked").length;
                $grid.find("input[name='" + options.checkAll + "']").prop('checked', all);
            });
```
$grid is not the GridView that display on web
### What is the expected result?
Do you have any better solutions?
### What do you get instead?
            $(document).off('click.yiiGridView', checkAll).on('click.yiiGridView', checkAll, function () {
                $grid = $("#" + $grid.attr("id"));
                $grid.find("input[name='" + options.name + "']:enabled").prop('checked', this.checked);
                $grid.find("input[name='" + options.name + "']:enabled").addClass('checked');
            });
            $(document).off('click.yiiGridView', inputs + ":enabled").on('click.yiiGridView', inputs + ":enabled", function () {
                var all = $grid.find("input[name='" + options.name + "']").length == $grid.find("input[name='" + options.name + "']:checked").length;
                $grid.find("input[name='" + options.checkAll + "']").prop('checked', all);
            });

### Additional info

| Q                | A
| ---------------- | ---
| Yii version   |    dev-master
| PHP version     |  5.6.19
| Operating system |  mac

**Comment by SilverFire** [comment]
`$grid` is pointing to the scope where you've called `setSelectionColumn`.
When the grid is updated using pjax `setSelectionColumn` must be called once more. Are you sure, that it is called indeed?
