### ISSUE TITLE
Remove some cache backends

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#11560]
- memcache(without `d`) is terribly outdated.
- XCache is pretty much dead. Not updated for a long time and doesn't support CLI.
- Zend data cache is too rarely used to be part of the framework.

**Comment by cebe** [comment]
dependend on minimum required version, the ApcCache could be simplified to use APCu only.

**Comment by samdark** [comment]
Yes. Agree.

**Comment by SamMousa** [comment]
When making these changes would it not make sense to separate the cache backends into a separate repository?
Either 1 repository for all the core backends or 1 per backend.

(Not sure if it is a long-term goal to separate parts of the yii core into separate smaller repositories or if a large monolithic repository is preferred).

**Comment by samdark** [comment]
Not in these case. What's left is quite common.

**Comment by samdark** [comment]
memcache (w/o `d`) can't be removed since it's the only option on Windows.
