### ISSUE TITLE
DI container will throw exception for optional arguments.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11561]
### What steps will reproduce the problem?
1. Create the DI container.
2. Use it to get an instance of a class that optionally requires an interface (for which no class has been registered).

````
class Test {
    public function __construct(SomeInterface $a = null) {
    }
}

````
### What is the expected result?
I expect my class to get constructed and the interface parameter to be set to `null`.

### What do you get instead?
PHP Fatal Error 'yii\base\ErrorException' with message 'Cannot instantiate interface SomeInterface'

### Proposed solution:
1. Check if the class is an interface, if so don't instantiate it.
2. If it is an interface and it is optional, just skip it.
3. Otherwise throw another error.

**Comment by SamMousa** [comment]
Would it be easier to add a label for issues that have a PR open?
I'm trying to look in the issue list to see where I can assist, showing me which issues already have a PR would allow others to identify bugs that they can work on.
I suggest: `status:in progress`.

**Comment by lynicidn** [comment]
https://qafoo.com/blog/083_never_use_null.html
example:
https://github.com/zendframework/zend-paginator/blob/master/src/Adapter/NullFill.php

**Comment by SamMousa** [comment]
@lynicidn I don't think that applies here.
1. When the DI container does not know the dependency it cannot instantiate it, and not knowing implies it also doesn't know about a "null"-implementation. Since if that existed it would happily use that since it obeys the contract.
2. I could implement my object where the dependencies get injected to use a "null"-implementation if no instance of a specific dependency was passed in.
3. Yii uses `null` everywhere to signify no value, in this case I think consistency is more valuable.

**Comment by lynicidn** [comment]
Yii not used
Instance::ensure('SomeInterface', null);

**Comment by SamMousa** [comment]
Not sure what you mean with your responses, a little more text would be appreciated!

**Comment by cebe** [comment]
> Would it be easier to add a label for issues that have a PR open?

we already have that: "status:under development" but we do not use it much.
