### ISSUE TITLE
models not save attributes correctly

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11574]
### What steps will reproduce the problem?

when load the form after submit form

### What is the expected result?

save the information in the DB

### What do you get instead?

the model save in the DB but not save all attributes

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.*
| Operating system | win

this is the rules of the model

[['bird_couple_id', 'clutch_number', 'egg_counter', 'created_at', 'updated_at'], 'required'],
            [['bird_couple_id', 'clutch_number', 'egg_counter', 'created_at', 'updated_at'], 'integer'],
            [['birthday_date', 'incubation_date', 'band_date', 'independization_date'],'integer', 'on' => 'update'],

the methods in the "on => update" not save when i call this 
$model->load(Yii::$app->request->post())

but if you see the $_POST the attributes exist

of course if i add this attributes in the rule "integer" or "required" this save correctly

but i need use on => update because the javascript validation cant save dates only if is integer and i make the cast in php

i cant see here how can define "$safeOnly = false" in the load

```php
public function load($data, $formName = null)
    {
        $scope = $formName === null ? $this->formName() : $formName;
        if ($scope === '' && !empty($data)) {
            $this->setAttributes($data);

            return true;
        } elseif (isset($data[$scope])) {
            $this->setAttributes($data[$scope]);

            return true;
        } else {
            return false;
        }
    }

public function setAttributes($values, $safeOnly = true)
    {
        if (is_array($values)) {
            $attributes = array_flip($safeOnly ? $this->safeAttributes() : $this->attributes());
            foreach ($values as $name => $value) {
                if (isset($attributes[$name])) {
                    $this->$name = $value;
                } elseif ($safeOnly) {
                    $this->onUnsafeAttribute($name, $value);
                }
            }
        }
    }
```

**Comment by egorio** [comment]
@spiritdead, `load()` doesn't save it just fill attributes, you should call `save()` after `load()`, for example:

```
$model->load(Yii::$app->request->post()) && $model->save()
```

Also, please note, that the GitHub Issue Tracker is for bug reports and feature requests only.
Please ask your questions on the support [forum](http://www.yiiframework.com/forum/), on [IRC](http://www.yiiframework.com/chat/) (#yii on freenode), or [Gitter](https://gitter.im/yiisoft/yii2).
