### ISSUE TITLE
No way to do SELECT FOR UPDATE via ActiveRecord::find()

### ISSUE THREAD

**Issue by Lexxtor** [yiisoft/yii2#11570]
I want to do query like:
`SELECT * FROM table FOR UPDATE`
Via:
```php
table::find()
  ->postFix('FOR UPDATE')
  ->all();
```

| Q                | A
| ---------------- | ---
| Yii version     |  2.0.8-dev

**Comment by SilverFire** [comment]
You probably need something like

```php
    $sql = Type::find()->createCommand()->getRawSql();
    Yii::$app->db->createCommand($sql . ' FOR UPDATE')->execute();
```

**Comment by Lexxtor** [comment]
@SilverFire I know that, but I want to get array of ActiveRecord`s in a nice short way.

**Comment by SilverFire** [comment]
Currently it is not possible
