### ISSUE TITLE
DI circular dependency segfault

### ISSUE THREAD

**Issue by RiderSx** [yiisoft/yii2#11583]
### What steps will reproduce the problem?
Given the two classes which require instance of each other in constructor:

```php
class ClassA {
  public function __constructor(ClassB $classB) {
  }
}

class ClassB {
  public function __constructor(ClassA $classA) {
  }
}
```
Set them as singletones:

```php
\Yii::$container->setSingleton(ClassA::class);
\Yii::$container->setSingleton(ClassB::class);
```
Then in third class try to require in constructor instance of some them:

```php
class ClassC {
  public function __constructor(ClassA $classA) {
  }
}
```

### What is the expected result?
Correct work

### What do you get instead?
Segfault

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.0.6
| Operating system | Ubuntu 14.04

**Comment by klimov-paul** [comment]
Same as #11492

https://github.com/yiisoft/yii2/issues/11492#issuecomment-216807154

**Comment by samdark** [comment]
By "Correct work" you mean exception?

**Comment by RiderSx** [comment]
Oh, sorry, realized that it's not possible :) But exception would be great, instead of segfault.
