### ISSUE TITLE
UploadedFile getBaseName() return empty in php=5.4

### ISSUE THREAD

**Issue by hossin-esm** [yiisoft/yii2#11589]
UploadedFile getBaseName() return empty in php=5.4

**Comment by hossin-esm** [comment]
for resolve :

public function getBaseName()
{
	// https://github.com/yiisoft/yii2/issues/11012
	//return mb_substr(pathinfo('_' . $this->name, PATHINFO_FILENAME), 1, null, '8bit');
	return mb_substr(pathinfo('_' . $this->name, PATHINFO_FILENAME), 1, mb_strlen('_' . $this->name), '8bit')
}

**Comment by klimov-paul** [comment]
Unable to reproduce at 5.4.45
