### ISSUE TITLE
ERROR ON MYSQL INBUILD FUNCTION (DATE_FORMAT)

### ISSUE THREAD

**Issue by EsoftsLimited** [yiisoft/yii2#11581]
### What steps will reproduce the problem?
On running the following query
$sms = (new Query())
		             ->from(Model::tableName())	            
		             ->select("created_at, DATE_FORMAT(created_at,'%W') as date_of_week , DAY(created_at) as date_day, count(*) as count")		             
		             ->groupBy(['date_day'])
		             ->all();
### What is the expected result?
I expect the query to give me an array of data grouped by date, the expected sql is 
`SELECT `created_at`, DATE_FORMAT(created_at, '%W') AS `date_of_week`, DAY(created_at) as date_day, count(*) as count FROM `models``
### What do you get instead?
But it seems the Query builder is escaping the second parameter of date_format as follows

SELECT `created_at`, DATE_FORMAT(created_at, `'%W')` AS `date_of_week`, DAY(created_at) as date_day, count(*) as count FROM `models`

Please note the erroneous part  `'%W')` How can i avoid this?

**Comment by klimov-paul** [comment]
Duplicates #10344

**Comment by EsoftsLimited** [comment]
Thank you solved
