### ISSUE TITLE
FileValidator checkExtensionByMimeType wrong message

### ISSUE THREAD

**Issue by andrewblake1** [yiisoft/yii2#11588]
Just had to step thru to find why was getting message that extension wasn't allowed when it was. Turned out the file was Mime type image/gif for a .bmp extensioned file.

Message should have said something like "Extension .bmp does not match mime type image.gif".

Issue is that validateExtension performs the check for valid extensions and for mime type to extension match, however it only has the one message when returning false which is that extension isn't allowed - hence confusing to a user and is wrong message.

Have turned off checkExtensionByMimeType for now.

**Comment by Faryshta** [comment]
I think there is not an error message for the case you mention. The message `$wrongMimeType` is used when the property `$mimeTypes` is set with a list of allowed mime types, not to match the file extension and mime type.

How about a new error message `$notMatchMimeTypeAndExtension` ? as usual the names I propose are bloby.

**Comment by andrewblake1** [comment]
Yip, the new message sounds fine. Wasn't proposing any solution, was just hiliting the problem.

**Comment by Faryshta** [comment]
@andrewblake1 no prob, you can still make an opinion about how to name the new error message, i will make the PR.

**Comment by andrewblake1** [comment]
Naming of the new message as you have suggested sounds good.

**Comment by githubjeka** [comment]
May be better auto turn off checkExtensionByMimeType if `empty($mimeTypes)` ? Then you get `$wrongMimeType` message.

Why it checks twice now?

**Comment by SilverFire** [comment]
> Extension .bmp does not match mime type image.gif

This kind of error is useless because:
1. The average user will not understand what's going on
2. Extension is a lie (probably). That's why we do not trust extensions by default and force mime-type checking.

> Issue is that validateExtension performs the check for valid extensions and for mime type to extension match, however it only has the one message when returning false which is that extension isn't allowed - hence confusing to a user and is wrong message.

As a result of point 2, mime-type checking is safer. But it's not convenient enough, because usually we know the extensions we want to allow, but don't know representative mime-types.

Assuming there is a simple way to get mime-type for the extension, we give a simple way to declare allowed mime-types through extensions.

In case you want to rely on extensions only, set property [checkExtensionByMimeType](http://www.yiiframework.com/doc-2.0/yii-validators-filevalidator.html#$checkExtensionByMimeType-detail) to `false`.

Current behavior is just correct, no changes required, as for me.

**Comment by andrewblake1** [comment]
Current behaviour caused confusion for my tester due to a wrongly named file which does happen in the real world. This resulted in having to step thru to find out what was wrong. When this system goes live, we will receive support calls. This is not the first time I have come across files with incorrect extensions and won't be the last. It is of course a rare situation, and my debate would be that although the message suggested as a solution might not be understood by an average user, it is clearer  and more accurate than the alternative which is just plain inaccurate.

I.e. the extension was allowed - that is image.bmp. The user was left with no idea how to resolve the issue by the error message, fortunately we were only testing. I still don't even know how we ended up with the misnamed file - but have seen it happen before.

If this is closed then I will continue to use my extended FileValidator class that is dealing with this but I think one day someone will come across this and raise it again.

**Comment by SilverFire** [comment]
> The user was left with no idea how to resolve the issue by the error message

I agree, that more specific error message is better.

**Comment by ArgosOleg** [comment]
I had the same issue, and here is my solution:

- first check default extention,
- second check mime type and write another error message.

> 
    public function rules()
    {
        return [
            [['file'], 'file', 'extensions' => 'png, jpg, jpeg', 'checkExtensionByMimeType' => false],
            [['file'], 'file', 'extensions' => 'png, jpg, jpeg', 'wrongExtension' => Yii::t('app', "It seems that your file corrupted, try re-save this file with another name and upload again.")],
        ];
    }

Maybe it's help someone.
Sorry if this off-top

p.s. but if we create in validator new error message when extension of file try validate by MIME type, which we can rewrite (when use validator), it would be great.
Then my solution can be shown like this:

> 
    public function rules()
    {
        return [
            [['file'], 'file', 'extensions' => 'png, jpg, jpeg', 'wrongExtensionsByMimeType' => Yii::t('app', "It seems that your file corrupted, try re-save this file with another name and upload again.")],
        ];
    }

and default message of **wrongExtensionsByMimeType** in validator can be something like: `Yii::t('yii', 'File extension and its MIME type is different.');`
