### ISSUE TITLE
Options method for rest calls doesn't work.

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii2#11585]
### What steps will reproduce the problem?
Create a module and bootstrap it, then in the module's bootstrap method register the url rules, in my case the rule registered is :
```php
...
$rules = [
[  
    'class'      => 'app\yii\rest\UrlRule',  
    'tokens'     => ['{id}' => '<id:(\w+)>'],  
    'controller' => [  
        'v1/item/types'        => 'v1/item/types',  
        'v1/item/categories'   => 'v1/item/categories',  
        'v1/item/post-types'   => 'v1/item/post_types',  
        'v1/item'              => 'v1/item/item',  
    ],  
]
];  
$app->getUrlManager()->addRules($rules, false);
...
```
Then do a Options request to any endpoint.

### What is the expected result?
I expect the options request to pass.

### What do you get instead?
Instead i get back a 404 response code. whoot?

I have to add a rule like:
```php
'OPTIONS <opts:(.*)>' => 'preflight/index',
```
In order to catch all requests and send them to a controller/action, otherwise it seems all the api calls that require a preflight call will fail.  
Please note that there is no issue with CORS or the like.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7.0.6
| Operating system | Linux / Centos 7

**Comment by tunecino** [comment]
are your controllers extending `yii\rest\ActiveController` or `yii\rest\Controller` ?

**Comment by twisted1919** [comment]
@tunecino - They extend ActiveController which looks lke:
```php
<?php

namespace app\yii\rest;

use app\yii\web\Response;
use yii\filters\Cors;
use yii\filters\auth\HttpBearerAuth;
use app\yii\rest\Serializer;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController as BaseActiveController;

class ActiveController extends BaseActiveController
{

    // the serializer
    public $serializer = [
        'class' => Serializer::class,
    ];
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        // setup CORS before any other filters
        $behaviors = ArrayHelper::merge([
            'corsFilter' => [
                'class' => Cors::class,
            ],
        ], parent::behaviors());
        
        // setup the contentNegotiator filter
        $behaviors['contentNegotiator']['formats']['application/vnd.api+json'] = Response::FORMAT_JSONAPI;
        
        // setup the authenticator filter
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::class,
        ];
        
        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        // if parrent does not pass, stop
        if (!parent::beforeAction($action)) {
            return false;
        }

        // logger to collect info before each action
        app_get('activityLog')->log();

        // return default behavior
        return true;
    }
}
```

**Comment by tunecino** [comment]
when you remove the `authenticator` or replace it by this:
```php
$behaviors[1] = [
    'class' => HttpBearerAuth::class,
];
```
does it work ?

**Comment by twisted1919** [comment]
@tunecino - weird enough, that works. What's the deal?

**Comment by twisted1919** [comment]
I think i spoke too soon. gimme more mins.

**Comment by tunecino** [comment]
also you need to except the option action from the `authenticator`. try this:
```php
unset($behaviors['authenticator']);
$behaviors['authenticator'] = [
    'class' =>  HttpBearerAuth::className(),
    'except' => ['options'],
];
```

**Comment by twisted1919** [comment]
Yeah, i spoke too soon, even with using `except` option, it still gives a 404 page.  
For what it worth, a GET request to same endpoint works, and my actions method in controller looks like:
```php
public function actions()
    {
        return ['options'];
    }
```
So i am not sure why is failing...

**Comment by tunecino** [comment]
shouldn't that override all `ActiveControlle::actions()` ? 

I thought it may be related to https://github.com/yiisoft/yii2/pull/8626 as you are implementing the authenticator filter. any way a it is a `404` and not `401` which means those patterns may be missing to configs :
```php
$patterns = [
    '{id}' => 'options',
    '' => 'options',
];
```
 or the action is not found. and that is why I first asked if it was extending `yii\rest\Controller` as in similar cases you need to add the action manually like:
```php
$_verbs = ['POST', 'GET', 'OPTIONS'];

public function actionOptions ()
{
    if (Yii::$app->getRequest()->getMethod() !== 'OPTIONS') {
        Yii::$app->getResponse()->setStatusCode(405);
    }
    Yii::$app->getResponse()->getHeaders()->set('Allow', implode(', ', $this->_verbs));
}
```

**Comment by twisted1919** [comment]
I am defining my own actions in controller, create/update/delete/index, that's why i don't need then in actions() map...

**Comment by twisted1919** [comment]
I found the error. It's because actions() has to return an array of key => configuration, but in my case i was returning just the key, stupid.
