### ISSUE TITLE
Routing rules for modules and application controller conflict

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2#11584]
### What steps will reproduce the problem?

I used this rules for routing:

```
'<module>/<controller>/<action>/<id:\w+>' => '<module>/<controller>/<action>',
'<controller>/<action>/<id:\w+>' => '<controller>/<action>',
```

### What is the expected result?

When opening module link like an ``roles/role/create`` no action taken and this route dispatched in log:
```
Bootstrap with yii\gii\Module::bootstrap()
Request parsed with URL rule: <controller>/<action>/<id:\w+>
Route requested: 'roles/role'
Route to run: roles/role/index
```

But my module name is roles and should be load module (<module>) rules instead of application controller.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  dev-master
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.0.4

**Comment by samdark** [comment]
Framework does exactly what's in the rules:

`roles/role/index` has 3 segments so `<module>/<controller>/<action>/<id:\w+>` is skipped immediately because there are 4 segments so it can't match. `<controller>/<action>/<id:\w+>` has 3 segments and all three match well so it's executed.
