### ISSUE TITLE
NULL to Empty string when column defined like char

### ISSUE THREAD

**Issue by superfba** [yiisoft/yii2#11590]
### What steps will reproduce the problem?
CREATE TABLE `NewTable` (
`id`  int NOT NULL ,
`column1`  char(10) NULL ,
`column2`  char(10) NULL ,
PRIMARY KEY (`id`)
)
;

Generate Model with gii

$model = new \app\models\NewTable;
$model->column1 = "aaaaa";
$model->column2 = "";
$model->save();

### What is the expected result?
When i try to insert with Yii 2.7
INSERT INTO `NewTable` (`column1`, `column2`) VALUES ('aaaaa','')

### What do you get instead?
instead with Yii 2.8
INSERT INTO `NewTable` (`column1`, `column2`) VALUES ('aaaaa',NULL)

### Additional info
I've found a change in Schema.php files, the array $ typemap has been modified:
in Yii 2.7: 'char' => self :: TYPE_STRING,
in Yii 2.8: 'char' => self :: TYPE_CHAR

| Q                | A
| ---------------- | ---
| Yii version      |  2.8
| PHP version      |  5.6.3
| Operating system | centos/windows 10

**Comment by klimov-paul** [comment]
Duplicates #11532
