### ISSUE TITLE
Identity Map and Unit of Work Pattern in AR

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#11596]
why not use Identity Map and Unit Of Work in Active Record like EntityFramework?
or 
why not use doctrine better than AR
the Doctrine : A NEW entity instance has no persistent identity, and is not yet associated with an EntityManager and a UnitOfWork (i.e. those just created with the “new” operator).

The Doctrine Project is the home to several PHP libraries primarily focused on database storage and object mapping. The core projects are a Object Relational Mapper (ORM) and the Database Abstraction Layer (DBAL) it is built upon. Doctrine has greatly benefited from concepts of the Hibernate ORM and has adapted them to fit the PHP language.
Large Community and integrations with many different frameworks (Symfony, Zend Framework, CodeIgniter, Flow, Lithium and more)
[http://www.doctrine-project.org/](url)

**Comment by samdark** [comment]
We're aware of Doctrine and it could be used with Yii.

Identity map could lead to issues with relations and in web-PHP doesn't have much benefits because context is terminated on response. Unit Of Work is already implemented.

**Comment by tunecino** [comment]
> why not use doctrine better than AR

check this: https://github.com/kenjis/php-orm-benchmark/blob/master/README.md#results

**Comment by samdark** [comment]
https://github.com/yiister/yii2-mappable-ar
