### ISSUE TITLE
Laravel Queues,jobs equivalent

### ISSUE THREAD

**Issue by dhiman252** [yiisoft/yii2#11602]
Do we have any thing equivalent to the Laravel Queues and jobs in Yii2 ?

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-queue

**Comment by dhiman252** [comment]
Please mention this package in the extention lists, also do we have the broadcast function on the event like laravel ?

**Comment by cebe** [comment]
it is not stable yet.
