### ISSUE TITLE
yii\caching\DbDependency running SQL command multiple times

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#11603]
### What steps will reproduce the problem?
```
$cacheDependency = Yii::createObject([
    'class' => 'yii\caching\DbDependency',
    'sql' => 'SELECT COUNT(*) FROM agent_assignment WHERE agent_id='.Yii::$app->user->identity->agent_id,
]);

$cacheDuration = 10; //seconds before its deleted from cache

$accountsManaged = InstagramUser::getDb()->cache(function($db) {
    return Yii::$app->user->identity->accountsManaged;
}, $cacheDuration, $cacheDependency);
```
### What is the expected result?
I expect it to run the query provided only once.
### What do you get instead?
Query runs 3 to 5 times as shown in the following image:
<img width="1393" alt="additionalsql" src="https://cloud.githubusercontent.com/assets/5470101/15437236/aa74e6d4-1ece-11e6-9929-0a745a81e99e.png">

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.7
| Operating system | OS X El Capitan Version 10.11.4

**Comment by jmbb** [comment]
I think you should make it reusable

https://github.com/yiisoft/yii2/blob/master/framework/caching/Dependency.php#L32

**Comment by BAWES** [comment]
Thanks @jmbb , making it reusable does make it work the way I intend it to.
Shouldn't this be the default for `yii\caching\DbDependency` considering I only made one request?

**Comment by mdmunir** [comment]
only execute once.
```php
$dependency = Yii::createObject([
        'class' => 'yii\caching\DbDependency',
        'sql' => 'SELECT COUNT(*) FROM product',
    ]);

$products = Yii::$app->getDb()->cache(function($db) {
    return (new Query())
        ->from('product')
        ->limit(10)
        ->all($db);
}, 5, $dependency);
```
![screenshot from 2016-05-21 07 42 06](https://cloud.githubusercontent.com/assets/5828252/15445494/b4b29870-1f29-11e6-9f80-4242f9b5ad9d.png)

**Comment by mdmunir** [comment]
`Yii::$app->getDb()->cache()` mean `beginCache` and `endCache`. Every query will be treat as a single cache data.
