### ISSUE TITLE
the namesapce named Yii is not found

### ISSUE THREAD

**Issue by undefinedor** [yiisoft/yii2#11600]
```php
<?php
/**
 * Yii bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require(__DIR__ . '/BaseYii.php');

/**
 * Yii is a helper class serving common framework functionalities.
 *
 * It extends from [[\yii\BaseYii]] which provides the actual implementation.
 * By writing your own Yii class, you can customize some functionalities of [[\yii\BaseYii]].
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class Yii extends \yii\BaseYii
{
}

spl_autoload_register(['Yii', 'autoload'], true, true);
Yii::$classMap = require(__DIR__ . '/classes.php');
Yii::$container = new yii\di\Container();
```
I have some confusion that why the file named Yii.php don't have namespace.
I know the class named Yii extends \yii\BaseYii .But I found some file generated by gii like this.

```php
namespace common\models;

use Yii;

/**
 * This is the model class for table "xxx".
```
You will find the 'Yii' . But I find no namespace named Yii  in framework.
This make me confusion.
***
My English is not good,I'm sorry.

**Comment by SilverFire** [comment]
Yii is located under the root namespace and is included manually in `index.php`. See https://github.com/yiisoft/yii2-app-basic/blob/master/web/index.php

**Comment by cebe** [comment]
`Yii` is a class in the root namespace, other yii classes are in the `yii\` namespace.

**Comment by undefinedor** [comment]
Why the file generated by gii is use Yii  not use yii. Though the namespace is not case-sensitive . The IDE named phpstrom show this occurred  a warning.

**Comment by cebe** [comment]
that is a bug in the IDE. see #11201

**Comment by undefinedor** [comment]
I see. Thank you very much :)
