### ISSUE TITLE
HTTP 400 - Unable to verify your data submission

### ISSUE THREAD

**Issue by spiro-stathakis** [yiisoft/yii2#11608]
My Yii 2 application was progressing well until I received an unusual error about a bad HTTP request. The error is:

HTTP 400 Unable to verify your data submission.

I have looked it up and much of the literature indicates the cause being due to a CSRF issue. However the CSRF components are all in place within the HTML head section and the hidden field is submitting the correct token. I would prefer to have feature in the application. Also when I switch it off it appears that redirects $this->back() , $this->goHome() have stopped working.

In order to try and identify the source of the problem, I have installed a fresh copy of yii using the following command :

composer create-project yiisoft/yii2-app-advanced advanced 2.0.8

and then tried to login to the newly generated website (without any of my own code added). The error is still there and I am receiving the HTTP 400 error.

The version of composer I am using is :

Composer version 1.1.1 2016-05-17 12:25:44

And the composer.json file is below. Would anyone mind trying this in their own environment to determine if this issue is a general one or specific to my environment. I am not sure how to trace back the cause of the error as the logs are not reporting anything about it. Thanks for any help you can offer.

composer.json:

{
"name": "yiisoft/yii2-app-advanced",
"description": "Yii 2 Advanced Project Template",
"keywords": ["yii2", "framework", "advanced", "project template"],
"homepage": "http://www.yiiframework.com/",
"type": "project",
"license": "BSD-3-Clause",
"support": {
"issues": "https://github.com/yiisoft/yii2/issues?state=open",
"forum": "http://www.yiiframework.com/forum/",
"wiki": "http://www.yiiframework.com/wiki/",
"irc": "irc://irc.freenode.net/yii",
"source": "https://github.com/yiisoft/yii2"
},
"minimum-stability": "stable",
"require": {
"php": ">=5.4.0",
"yiisoft/yii2": ">=2.0.6",
"yiisoft/yii2-bootstrap": "*",
"yiisoft/yii2-swiftmailer": "*"
},
"require-dev": {
"yiisoft/yii2-codeception": "*",
"yiisoft/yii2-debug": "*",
"yiisoft/yii2-gii": "*",
"yiisoft/yii2-faker": "*"
},
"config": {
"process-timeout": 1800
},
"extra": {
"asset-installer-paths": {
"npm-asset-library": "vendor/npm",
"bower-asset-library": "vendor/bower"
}
},
"scripts": {
"post-install-cmd": "php init --env=Development --overwrite=n"
}
}
0

### Additional info
Yii version = 2.0.8 
PHP version = 5.4.42 
OS = Mac (MAM 3.5)

**Comment by arisk** [comment]
Can you show your Yii configuration file?

**Comment by spiro-stathakis** [comment]
This is my frontend/config/main-local from a fresh installation of web app that is showing the problem. 
```php 
<?php 
$config = [
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '9HF6zZwHKCHfPlRQ85219zFPx5PksdMU',
        ],
    ],
];

if (!YII_ENV_TEST) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
    ];
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
    ];
}

return $config;

**Comment by arisk** [comment]
Just tried with a fresh installation but I can't reproduce your problem. Can you verify that cookies are getting created by printing them somewhere in your view? `var_dump($_COOKIE);`

**Comment by spiro-stathakis** [comment]
Hi @arisk looks like cookies are not getting generated. The output of 

```php var_dump($_COOKIE)
array(0) { } 
```

**Comment by SilverFire** [comment]
Same here, failed to reproduce.

**Comment by re1naldo** [comment]
I'm using Yii 2.0.9 and got this error too. `var_dump($_COOKIE)` gives empty array. Strangely, this Bad Request error only happened in certain server. I tested the application in my servers (Linux Mint & CentOS) and everything worked great. 

Is there Apache or PHP configuration that related to this issue? I read `mod_security` could cause cookie problems. Is that true?

This could be related to https://github.com/yiisoft/yii2/issues/8885.

**Comment by spiro-stathakis** [comment]
I got fixed by running the ./init script in your app root folder.

**Comment by re1naldo** [comment]
@spiro-stathakis I saw you used advanced application template. Does basic template have such command? I couldn't run it.

**Comment by ElConrado** [comment]
still same issue here basic template

**Comment by SilverFire** [comment]
@ElConrado in case you have a clear way to reproduce the problem - please, open a separate issue. Thank you!
