### ISSUE TITLE
Broken link to GridView in official guide

### ISSUE THREAD

**Issue by MacGyer** [yiisoft/yii2#11609]
Found a broken link in the official guide under Data Widgets sections, specifically a GridView referencing error.

> Data grid or yii\widgets\GridView is one of the most powerful Yii widgets. It is extremely useful [...]

### What steps will reproduce the problem?
View [documentation guide](http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#gridview)

### What is the expected result?
A clickable link referencing yii\grid\GridView

### What do you get instead?
A non-clickable (broken) red coloured text mentioning yii\\**widgets**\GridView

**Comment by SilverFire** [comment]
Thank you for noticing!

**Comment by MacGyer** [comment]
Need to reopen as I just saw on the same page there are more GridView and ActionColumn referencing links:

[PJAX section](http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#using-gridview-with-pjax)

**Comment by SilverFire** [comment]
Fixed as well, thank you!
