### ISSUE TITLE
E_DEPRECATED errors in PHP 7

### ISSUE THREAD

**Issue by miradnan** [yiisoft/yii2#11607]
### What steps will reproduce the problem?
Call a method inside another controller statically
I have two controllers A and B. Class B extends Class A. My script calls self::actionFunc($id); Which is a non-static method. I cannot make it static because Yii does not support action methods to be static. Also I can't initialize the object. I get parameter error if I do ((new B())->actionFunc($id); 

### What is the expected result?
It should return the response from B::actionFunc($id); method.

### What do you get instead?
E_DEPRECATED error

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7
| Operating system | CentOS

**Comment by mdmunir** [comment]
I unsure what you traying to do. 
Why you calling action method as static? 
Just use action to handle request.

**Comment by Faryshta** [comment]
there are better ways to do it. Make an action class and use it on both controllers

http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html#standalone-actions

**Comment by SilverFire** [comment]
@Faryshta suggested right thing
