### ISSUE TITLE
In gii tool model generator while overwrite model should not overwrite existing code

### ISSUE THREAD

**Issue by nagarajanp1naga** [yiisoft/yii2#11601]
### What steps will reproduce the problem?
In gii tool model generator, create model for a table. Click preview & overwrite it.

### What is the expected result?
Click preview check file diff. Existing code are red color.Here some codes i don't want, some of my custom methods want to keep the same.
### What do you get instead?
My custom methods which i created earlier its overwriting.

### Additional info
Please email me the solution ASAP.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.0.5
| Operating system | windows vista

**Comment by cebe** [comment]
you can copy the generated code and apply the parts you want with a diff tool like PHPStorm "Compare with Clipboard" option.
