### ISSUE TITLE
JsonParser exception, seems to parse headers alongside the body

### ISSUE THREAD

**Issue by tehmaestro** [yiisoft/yii2#11615]
### What steps will reproduce the problem?
I get multiple POST requests from an iOS device. Not all requests have these issues, actually,a very small percent of requests coming from iOS devices are affected.

Here is the exception I get:
`exception 'yii\web\BadRequestHttpException' with message 'Invalid JSON
data in request body: Syntax error.' in
/var/app/current/components/parser/JsonParser.php:23
Stack trace:
#0 /var/app/current/vendor/yiisoft/yii2/web/Request.php(399):
app\components\parser\JsonParser->parse('POST /v1/ios/us...',
'application/jso...')`

As you can see the content type is correct, but the `php://input` contains what seem to be the request headers. Did anybody else encounter this issue? Thank you.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.5.15
| Operating system | Linux

**Comment by samdark** [comment]
`php://input` should not contain headers. Seems your client is doing something wrong.
