### ISSUE TITLE
[bug] ActiveRecord query -> select using concat results in ORA-00907: Rechte Klammer fehlt

### ISSUE THREAD

**Issue by SSiwek** [yiisoft/yii2#11619]
Hi 
I am using an Oralce DB:

Sourcecode
`    	$query->select('DKDNR AS id, DKDNR, CONCAT( DNAME, CONCAT( DNAME2, CONCAT( DPLZSO10, DORT ) ) ) AS text')
    	->andFilterWhere(['like', 'DNAMEMATCH', $such])
    	->andFilterWhere(['in','DADRTYP',['10','30','99']]);
    	$query->innerjoinWith([
    			'cfkol' => function ($query) {
    			$query->onCondition(['DFAKOL' => '025PAL']);
    			},
    			]);`

in Debug Data you can see:
`SELECT "DKDNR" AS "id", "DKDNR", CONCAT( DNAME, CONCAT( DNAME2, CONCAT( DPLZSO10, "DORT ) ) )" AS "text" FROM "C_KUNDEA" INNER JOIN "C_FKOL" ON ("C_KUNDEA"."DKDNR" = "C_FKOL"."DFAKOLKDNR") AND ("DFAKOL"='025PAL') WHERE ("DNAMEMATCH" LIKE '%BIELEF%') AND ("DADRTYP" IN ('10', '30', '99'))  \models\CKUNDEAQuery.php (23)
`

The query parser does a   

> "DORT

and a

>  )"

  in the select, which is complety wrong.

SSiwek

**Comment by klimov-paul** [comment]
Duplicates #10344
