### ISSUE TITLE
ModSecurity is blocking yii2 due to SQL injection in cookies after login

### ISSUE THREAD

**Issue by esaesa** [yiisoft/yii2#11616]
### What steps will reproduce the problem?
Logging in using yii standard identity while enabling csf firewall ldf and modSecurity
### What is the expected result?
normal data submission to server
### What do you get instead?
the firewall suspect the content of submitted cookies data as follow:

> 

[Sun May 22 21:51:37.736980 2016] [:error] [pid 8251:tid 3044014960] [client xxx.xxx.xxx.xxx] ModSecurity: Access denied with redirection to http://domain.com/ using status 302 (phase 2). Pattern match "(?i:(?:,.*?[)\\\\da-f\\"'`][\\"'`](?:[\\"'`].*?[\\"'`]|\\\\Z|[^\\"'`]+))|(?:\\\\Wselect.+\\\\W*?from)|((?:select|create|rename|truncate|load|alter|delete|update|insert|desc)\\\\s*?\\\\(\\\\s*?space\\\\s*?\\\\())" at REQUEST_COOKIES:_identity. [file "/etc/apache2/conf.d/modsec_vendor_configs/OWASP/rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf"] [line "82"] [id "981257"] [rev "2"] [msg "Detects MySQL comment-/space-obfuscated injections and backtick termination"] [data "Matched Data: ,\\x22\\x22,2592000] found within REQUEST_COOKIES:_identity: 24beb122a2ed6eb7993739c9bdacf76699bcfb6f8be5890b159d3bd9ed8060c7a:2:{i:0;s:9:\\x22_identity\\x22;i:1;s:14:\\x22[5,\\x22\\x22,2592000]\\x22;}"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "8"] [tag "Host: domain.com"] [tag "application-multi"] [tag "language-mutli"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [hostname "domain.com"] [uri "/admin/index"] [unique_id "V0JNxSLDlDPwxmggOMamCQAAAQB"]

> 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | win7

**Comment by cebe** [comment]
looks like a false positive, what do you suggest yii to do about this?

**Comment by esaesa** [comment]
The content of _identity  cookies may be need to be sql safe to pass through sql security rules

**Comment by cebe** [comment]
what do you mean with "sql safe" in this case? everything that is passed to a db query by yii is properly escaped. What you see here is a false alarm.

**Comment by esaesa** [comment]
escaping _identity data before storing them in cookies

**Comment by bizley** [comment]
This is clearly false positive.
@esaesa You might want to remove this rule in your whitelist.conf

**Comment by samdark** [comment]
I confirm it's a false positive. Also escaping should happen on output, not on input so that rule doesn't make much sense to me.
