### ISSUE TITLE
yii\web\Response sendFile() method does not set attachment name when [inline=>true]

### ISSUE THREAD

**Issue by friek108** [yiisoft/yii2#11612]
### What steps will reproduce the problem?

Sending a file to the browser using the sendFile() method in yii\web\Response does not render a page title when inline is set to true. If you set it to false, the attachment name is set correctly. However, if you render say a PDF (I do it in a new tab _blank), the page title defaults to the relative URL, in my case: **https://mydomain.com/file?id=2484** will just render "file" as the page title and PDF title. 

`
Yii::$app->response->sendFile($fullPath,$file->filename,['mimeType'=>$file->type,'inline'=>true]); return Yii::$app->response->send();   
`     
### What is the expected result?

The page title and PDF title should be set to $file->filename (eg. "My Sample File.pdf"). In the above example, it should equal $file->filename
### What do you get instead?

file
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |
| PHP version | 5.5.12 |
| Operating system | Windows 10 (WAMP) |

**Comment by Alex-Code** [comment]
From what I've seen by similar questions on Google I don't think this is possible.

It might work if you can include the file name in the url, `https://mydomain.com/file/My%20Sample%20File?id=2484`

**Comment by developeruz** [comment]
I've checked that `Content-Disposition` header is set [correctly](https://github.com/yiisoft/yii2/blob/fd56b8d4ed767a1ec542fca96e380ad78d9ab55f/framework/web/Response.php#L612): `inline; filename="test.txt"` and logic is quite [simple](https://github.com/yiisoft/yii2/blob/fd56b8d4ed767a1ec542fca96e380ad78d9ab55f/framework/web/Response.php#L773). Although some browsers like IE [don't support](https://stackoverflow.com/questions/36177894/content-disposition-inline-filename-issue-with-ie) filename for `inline`, therefore Yii cannot do anything about this issue.
