### ISSUE TITLE
Some confusions with ListView

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#11627]
There are some confusions with the ListView attributes and some minor issues as well.

Assume this ListView here:

``` php
<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'summary' => 'My Summary',
    'summaryOptions' => ['class' => 'bold'],
    'options' => ['class' => 'bordered bgwhite'],
    'itemOptions' => ['class' => 'item'],
    'itemView' => '_list-item',
    'showOnEmpty' => false,
]); ?>
```

First of all, when i modify the `summary` attribute, the content is not rendered in a `tag` but it's just text. So `summaryOptions` does not apply the class to the summary text.

And next, according to the docs, `showOnEmpty` is :

> Whether to show the list view if $dataProvider returns no data.

But when the `showOnEmpty` attribute is `false`, i still see the listview with the empty text inside. When `true` i see the listview with nothing inside.

Shouldn't it be:
- when `false` => don't show the list view container at all
- when `true` => show the listview with the empty text?
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |
| PHP version | 7.0.2 |
| Operating system | Windows 7 |

**Comment by klimov-paul** [comment]
Resolved by #12740
