### ISSUE TITLE
How to use Dynamic Model to validate the restful api input request?

### ISSUE THREAD

**Issue by symoo** [yiisoft/yii2#11623]
### What steps will reproduce the problem?
I want to validate the post input from my app client, which some attributes has been required.
And because some attributes are Active Record  irrelevant, so I try to use Dynamic Model on validation.
### What do you get instead?
The post data is this:
```
public function actionGet_school_list_test()
    {
        $this->sendEncryptRequestParams([
            'lang' => 0,
            'location_id' => 0,
            'grade_id' => 0,
            'school_type_id' => 0,
            'token' => Http::createUserToken(1),
        ]);
        
        return $this->actionGet_school_list();
    }
```
and the called action is this:
```
public function actionGet_school_list()
    {
        //获取并验证参数
        if (empty($request = $this->parseRequest()))
            return $this->createErrorResponse();

        $model = DynamicModel::validateData($request, [[['lang', 'location_id', 'grade_id', 'school_type_id', 'token'], 'required']]);
        if ($model->hasErrors())
        {
            return $this->createResponse([]);
        }

        $expect = ['lang' => 0, 'location_id' => 0, 'grade_id' => 0, 'school_type_id' => 0, 'token' => 1];
        if ($this->validateRequest($request, $expect) == false){
            Http::$ERR_NO =  Http::$ERR_NO_PARAM_ERROR;
            Http::$ERR_STR =  Http::$ERR_PARAM_ERROR;
            return $this->createErrorResponse();
        }

//        获取数据并返回
        $schools = School::find()->getSchoolListByFilter($request);

        return $this->createResponse($schools);
    }
```

But when some attributes are do not exist in the post, and required validator works,
some error has been given:
{
    "name": "Unknown Property",
    "message": "Getting unknown property: yii\\base\\DynamicModel::location_id",
    "code": 0,
    "type": "yii\\base\\UnknownPropertyException",
    "file": "/mnt/hgfs/Code/wenxiaoyou/vendor/yiisoft/yii2/base/Component.php",
    "line": 143,

So i wonder if I use  The Dynamic Model in a  wrong way, or there is aother way to do the job?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version     | 2.0.7 
| PHP version       | 7.0.4
| Operating system   | CentOS 7 64bit

**Comment by symoo** [comment]
my fault

**Comment by rnv619** [comment]
Can you please let me know what was the issue? because I am facing same one. 


Thanks in Advance.
