### ISSUE TITLE
beginTransaction() does not warn if transactions are not supported

### ISSUE THREAD

**Issue by cronfy** [yiisoft/yii2#11633]
When  one uses beginTransaction() with MySQL, it does not perform a check to ensure that transactions are supported by engine. InnoDB supports transactions, but MyISAM does not. 

Consider this code:

```php
$db = Yii::$app->db;
$transaction = $db->beginTransaction();

try {
    $item = new Item();
    $item->save();

    $properties = new Properties();
    $properties->item_id = $item->id;

    // defined as NOT NULL in database, so MySQL will fail to save this record
    $properties->not_null = null;

    $properties->save();

    $transaction->commit();

} catch(\Exception $e) {

    $transaction->rollBack();

    throw $e;
}
```

Here I set ```$properties->not_null``` to ```null```, and MySQL will not save the record because of Integrity constraint violation.

With InnoDB everything works as expected - exception is thrown and neither ```$item``` nor ```$properties``` are saved. 

But with MyISAM exception is thrown too, but as transaction is not supported, it can not be rolled back, and ```$item``` remains saved in the database, while ```$properties``` relation is not saved.

I suggest that beginTransaction() should throw an exception if transactions are not supported.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.20
| Operating system | Linux

**Comment by klimov-paul** [comment]
This is expected.
Same thing happens for SQLite, which does not support transactions at all.
Such behavior allows libraries to switch between different DBMS without extra logic.
You have to ensure your DBMS supports transactions yourself.

**Comment by cronfy** [comment]
@klimov-paul ok, but then it at least has to be mentioned in the documentation. Current documentation gives no clue why transactions may not work as expected.

**Comment by cronfy** [comment]
@klimov-paul and ideally there could be a method to check whether transactions are supported or not, i. e. ```yii\db\Transaction::supported()```. Because currently switching between different DBMS can lead to unexpected **silent** results (unexpected are ok, because switching to other DBMS may be complex, but it shoud not be silent).

**Comment by klimov-paul** [comment]
Such method can NOT help your situation anyhow. MySQL database may contain MyISAM and INNODB tables at the same time and those tables can be affected by the single query. INNODB operations will be transactional, while MyISAM will not.
THere is not possible check for this.
