### ISSUE TITLE
tablePrefix is broken?

### ISSUE THREAD

**Issue by yapi68** [yiisoft/yii2#11634]
Before version 2.0.8 when using `tablePrefix` it can be useful set column names in ActiveQuery like `{{%tableName.columnName}}`. Yii was convert this into correct quoted column name `'tbl_tableName'.'columnName'`. In Yii 2.0.8 this behavior is broken and no info for workaround can be found.

### What steps will reproduce the problem?
Try to search records like:
`User::find()->where(['{{%users.email}}' => 'test@email.com'])->one();`

### What is the expected result?
Expected to see one ActiveRecord of User type.
Expected SQL: `SELECT * FROM 'tbl_users' WHERE 'tbl_users'.'email' = "test@email.com" LIMIT 1`

### What do you get instead?
Database exception. `{{%tableName.columnName}}` converts in `{{%tableName.'columnName}}'`
SQL: `SELECT * FROM 'tbl_users' WHERE {{%tbl_users.'email}}' = "test@email.com" LIMIT 1`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      |  5.6.17-0+deb8u1
| Operating system |  Debian 8.0.1

**Comment by philippfrenzel** [comment]
I guess the syntax should be
{{%users}}.email

than you should be fine

**Comment by yapi68** [comment]
Yes, I know how to solve this `{{%users}}.email` or even `{{%users}}.[[email]]`. Ive found it in core. But it does not described in docs. And why it was changed? No one word in UPGRADE.md about this change!

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-dao.html#quoting-table-and-column-names
Previous version are bug https://github.com/yiisoft/yii2/pull/11238

**Comment by yapi68** [comment]
The bug thats working perfectly and as expected (by me) :)
