### ISSUE TITLE
yii\widgets\Menu url bug

### ISSUE THREAD

**Issue by dkhlystov** [yiisoft/yii2#11639]
Exception throws while using empty string (current) route in url array.

```
echo \yii\widgets\Menu::widget([
    'items' => [
        ['label' => 'Another item', 'url' => ['', 'id'=>'another id']],
    ],
]);
```

**Comment by Vovan-VE** [comment]
Item with `url` = `<current url>` should be always _active_. Add `'active' => false` to the item.

**Comment by dkhlystov** [comment]
I don't need advice. Just reported a bug.

**Comment by lynicidn** [comment]
@cebe it not bug, current behavior not neede, look @Vovan-VE 
this code always set active class for this link

**Comment by lynicidn** [comment]
menu link must not depended on current route, only `active` flag
and author don't understand that $_GET['id'] not exists on all requests - is not require

**Comment by dkhlystov** [comment]
@lynicidn see [Menu docs](http://www.yiiframework.com/doc-2.0/yii-widgets-menu.html#$items-detail). Url... will be processed by **yii\helpers\Url::to()**... Active: boolean, **optional**...

I know, that **any param** from url array not exists on all requests. 
Why "menu link must not depended on current route"?

**Comment by lynicidn** [comment]
@dkhlystov look
[view'', 'id' => 1] - on route a/view this work
['create', 'id' => ???]

**Comment by dkhlystov** [comment]
@lynicidn what problem with your code? Remove `id` from second url.

If you need example of usage **Menu** widget with current route, try to make list filtering by another list (products by category or products by brand or users by group) in different controller/action.
```
// common/widgets/Brands
$items = [];
foreach ($brands as $brand)
    $items[] = ['label' => $brand->name, 'url' => ['', 'brand_id' => $brand->id]];
Menu::widget(['items' => $items]);

// frontend/views/product/index
Brands::widget();

// frontend/views/store/product
Brands::widget();

// frontend/views/user/favorite
Brands::widget();

// frontend/views/brand/description
Brands::widget();

// backend/views/product/index
Brands::widget();
```
I see that there are some difficulties in determining the activity. But this is widget difficulties because **active is optional** (in accordance with the documentation).

**Comment by lynicidn** [comment]
param of route is require for generate link
if u can get current route via '', then current action params is not accessable, only via Yii::$app->actionParams
and your "universal" link should be as 
$params = Yii::$app->actionParams;
$params[0] = '';
$params - вот он роут который ты ищешь, но меню тут не причем ваще, меню это виджет, и  я не считают что он должен отталкиваться от роута еще для чего то помимо выявления актив или нет

в твоем случае кстати всегда такой роут будет активен

**Comment by lynicidn** [comment]
и то я тут щас подумал, такой подход все поломать могут простые кастомные урл рулесы
к примеру
actionView($id)

<c:\w+>/<slug:\w+><c>/view
вот с такким правилом, если у нас наше url rule по слугу ищет айтем и подготавливает параметры для экшена, то ты уже попадаешь с таким подходом, так что он не "universe" вообщем а костыль скорее

**Comment by dkhlystov** [comment]
> param of route is require for generate link

Developer decides this

> в твоем случае кстати всегда такой роут будет активен

In my opinion, the active state of the menu item should be determined with considering the parameters

> и то я тут щас подумал, такой подход все поломать могут простые кастомные урл рулесы
к примеру

This works perfectly with **UrlManager**

**Comment by SilverFire** [comment]
```php
$route = Yii::app()->urlManager->parseUrl(Yii::app()->request);

foreach ($brands as $brand)
    $items[] = ['label' => $brand->name, 'url' => array_merge($route, ['brand_id' => $brand->id]];
```
