### ISSUE TITLE
suggest add yii\web\User::getUniqueId()

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#11636]
suggest add logic for check of unique user (identity guests - simple way)
```php
public function getHash()
{
    return md5(implode('blabla' [
        $browserAgent,
        $ip,
        $callback,
    ]));
}
```

**Comment by tunecino** [comment]
do you mean like [browser fingerprinting](http://programmers.stackexchange.com/questions/122372/is-browser-fingerprinting-a-viable-technique-for-identifying-anonymous-users) ? what you are doing can't be solved using csrf tokens instead ?
```php
return Yii::$app->request->getCsrfToken()
``` 
It should return a token that client can hold but also attach a different one to the request within a httpOnly token that can be validated later whenever enableCsrfValidation is set to true. it should work with all methods except GET, HEAD and OPTIONS but it doesn't depend on any client data so no guessing.

a different option is by using the built-in security class helpers. like maybe `encryptByKey()` and `decryptByKey()`.

**Comment by lynicidn** [comment]
@tunecino about it https://support.google.com/analytics/answer/3123662?hl=en
example:
```php
class GuestUnique implemetns IdentityInterface
{
    public function getId(){
        return md5(implode('blabla' [
            $browserAgent,
            $ip,
            $callback,
        ]));
    }
    public static function findIdentity($id)
    {
        return new self(); //how here can create identity by id(unique hash) ?
    }
}
```

**Comment by lynicidn** [comment]
and this solution work with 2 identity - for guests (for unique id) and for auth user of app

**Comment by lynicidn** [comment]
am suggest create new identifier for any user - guest, logged

**Comment by lynicidn** [comment]
inner guid

**Comment by tunecino** [comment]
interesting. thanks for the link. I also found this:

https://www.clickinsight.ca/about/blog/implement-user-id-tracking

which explains little bit more how User-ID works with google analytics. but I'm not sure if it is a good idea to tie on `$browserAgent` and `$ip` on generating that hash. I trust more cookies and random tokens. people in the same house may use the same computer or people having the same smartphone with a last software update in an airport with free internet connection may provide the same values as all should also have the same IP. also IPs are mostly dynamic. I can restart internet and keep using the same session if it uses cookies while to your app it will be me from a different device. won't be better to use `Yii::$app->security->generateRandomString()` instead ? then saving it in a database (or even better in `Yii::$app->cache`) and send user a cookie holding a copy of that token until he does signup or login so you know who he is and you decide if that token should be grouped or replaced by other...

BTW a similar feature in Yii2 that generates a unique ID based on pre-stored data is the ETag used with REST HTTP caching (see it in [docs](http://www.yiiframework.com/doc-2.0/guide-caching-http.html#etag)) it is implemented as a filter and what it does in source code can be resumed by this:

```php
$seed = serialize([$post->title, $post->content])
$etag = '"' . rtrim(base64_encode(sha1($seed, true)), '=') . '"';
```

**Comment by lynicidn** [comment]
@tunecino thx for more detail, good link

**Comment by samdark** [comment]
That's application specific. Don't think it fits framework well.
