### ISSUE TITLE
Should publish be skipped for dummy asset bundles?

### ISSUE THREAD

**Issue by arisk** [yiisoft/yii2#11630]
### What steps will reproduce the problem?
Set `'bundles' => false` in `AssetManager`
### What is the expected result?
Dummy bundles should skip publishing
### What do you get instead?
`publish` method is called

### Additional info

https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L285

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.6
| Operating system | OS X

**Comment by klimov-paul** [comment]
Yes it should. `publish()` method have appropriate internal checks for the 'dummy' case.
