### ISSUE TITLE
Wrong pageCount in Pagination

### ISSUE THREAD

**Issue by Nex-Otaku** [yiisoft/yii2#11647]
ActiveDataProvider pagination returns wrong pageCount.

### Reproducing

// Total 8 items.
// We have 5 items on page.
// It makes 2 pages.

$dataProvider = new ActiveDataProvider(['query' => Notes::find()]);

$dataProvider->setPagination(['pageSize' => 5]);

$pageCount = $dataProvider->pagination->pageCount;

### Expected result

$pageCount is 2

### What do you get instead

$pageCount is 0

### Additional info

Console test is attached.
[TestPageCountController.zip](https://github.com/yiisoft/yii2/files/286274/TestPageCountController.zip)

Put controller class in console/controllers and run
 yii test-page-count

Pull request with bugfix is provided.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 5.6
| Operating system | Windows

**Comment by Alex-Code** [comment]
I don't think setting the `pagination` component should fetch the models, It might cause confusion.

```php
$query = Notes::find();
$dataProvider = new ActiveDataProvider(['query' => $query]);
$dataProvider->setPagination(['pageSize' => 5]);
$query->where(['foo' => 'bar']); //Will have no effect as the models have already been fetched.
```

**Comment by Nex-Otaku** [comment]
@Alex-Code it is not.

It is calling prepareTotalCount which queries "COUNT(*)" on table. No models are fetched.

And every time query object is used in ActiveDataProvider, it is cloned. So there should be no problems.

**Comment by Alex-Code** [comment]
Ah yes, It only performs a `COUNT(*)` but I think my issue above is still valid.
```php
$query = Notes::find();
$dataProvider = new ActiveDataProvider(['query' => $query]);
$dataProvider->setPagination(['pageSize' => 5]);
$pageCount = $dataProvider->pagination->pageCount; //May return 5
$query->where(['foo' => 'bar']);
$pageCount = $dataProvider->pagination->pageCount; //Would still return 5 even though the query has changed.
```
I wouldn't expect setting the options of `Pagination` to initiate a query.
Maybe passing the total count to the `Pagination` object itself would be better.

```php
$dataProvider->pagination->getPageCount($dataProvider->totalCount);
```

**Comment by Nex-Otaku** [comment]
I assume that developer should not change query after fetching data. 

Asking "what total page count" is fetching data.

If he needs to change query after fetching data, he must reset models with DataProvider methods, and fetch new data.

**Comment by Faryshta** [comment]
Thats documented. http://www.yiiframework.com/doc-2.0/yii-data-basedataprovider.html#getPagination()-detail

```php
$dataProvider = new ActiveDataProvider(['query' => $query]);
$dataProvider->prepare();
$dataProvider->pagination->pageSize = 5;
$pageCount = $dataProvider->pagination->pageCount;
```

**Comment by lynicidn** [comment]
yii app work with php as concept dying model, is say Quang and all properies as public in components for once configure only before init (clear configure with expected behavior).
try:
```php
$dataProvider = new ActiveDataProvider(['query' => $query, 'pagination' => ['pageSize' => 5]]);
```

**Comment by Nex-Otaku** [comment]
@Faryshta this sucks, I dont need to retrieve models. All I need is correct page count.

Retrieving models will slow down my app.

**Comment by samdark** [comment]
@Nex-Otaku @lynicidn suggestion should solve the issue.

**Comment by za4me** [comment]
`$dataProvider = new ActiveDataProvider(['query' => $query, 'pagination' => ['pageSize' => 5]]);`
In my case this not enough, need add `$dataProvider->prepare()` after and it will work.

But if i set
```
$dataProvider->pagination->pageSize = 5;
$dataProvider->prepare();
```
without `search()` method it's not working.
