### ISSUE TITLE
Conditional relation

### ISSUE THREAD

**Issue by kaiserfedor** [yiisoft/yii2#11643]
Hello, I want to use conditional for relation in my model, for example:

     /**
     * @return \yii\db\ActiveQuery
     */
    public function getChannels()
    {
        return $this->is_work_in_all_channel ? $this->getChannelsByProfile() : $this->getChannelsRelation();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChannelsRelation()
    {
        return $this->hasMany(Channel::className(), ['id' => 'channel_id'])
            ->viaTable('employee.employee_channel', ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChannelsByProfile()
    {
        return $this->hasMany(Channel::className(), ['profile_id' => 'id'])
            ->viaTable('user.profile', ['id' => 'profile_id']);
    }

It's work fine, when I work with a single model, but when I use it in with() function, relation execute just for first model because of this [code](https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQueryTrait.php#L162)

I've been trying override findWith(), but it use private method normalizeRelations() https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQueryTrait.php#L182

How can I fix this problem?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  5.6
| Operating system |  Ubuntu15.10

**Comment by lynicidn** [comment]
relation static for all owners
dynamical relation - is bad code - you don't understand that is relation

**Comment by lynicidn** [comment]
you must instantiate other models for others logic, but it not solve bugs in you code
Relation is abstraction for models in db repository

**Comment by lynicidn** [comment]
and not bug, is expected behavior - use forum for more info

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/3352
