### ISSUE TITLE
5.	In Yii2 why Some controller is  working fine with the url  ‘view/12’, some controller working with ‘view?id=12’ 

### ISSUE THREAD

**Issue by nagarajanp1naga** [yiisoft/yii2#11651]
### What steps will reproduce the problem?
  Creating views, models & controllers from Yii2 gii tool

### What is the expected result?

All controller should work with the url format like <controller>/<view>/<id>

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7
| Operating system | windows

**Comment by lynicidn** [comment]
read manual enableStrictParsing

**Comment by nagarajanp1naga** [comment]
Thanks,

Do u mean the below,

'urlManager' => [
		    'class' => 'yii\web\UrlManager',
            'enablePrettyUrl' => true,
