### ISSUE TITLE
Bug sqlite querybuilder

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#11652]
As Sqlite does not support autoincrement on BIGINT, issues arise:
* Sqlite + Querybuilder
* Sqlite + migrating the log migration

Solution is added in PR

**Comment by dynasource** [comment]
more info on this ie. http://stackoverflow.com/questions/24095211/replacing-sqlite-net-bigint-with-integer-for-autoincrement-primary-key-constra

**Comment by lynicidn** [comment]
http://storage4.static.itmages.ru/i/16/0529/h_1464489117_1611153_ebda14f234.png
hmmmm

**Comment by rob006** [comment]
duplicates #11527
