### ISSUE TITLE
Can we have some of yii\base\application properties keep as protected?

### ISSUE THREAD

**Issue by magicaner** [yiisoft/yii2#11656]
I am developing CMS and find my self that I need retrieve application preterites like `name`, `charset`, `sourceLanguage`, `language` from another sources, eg from custom configuration component, which keeps all this information at database. 

I was planing to keep those properties as protected and add getter|setter functions to avoid standard behavior. Unfortunately, base abstract class have them as `public`, and php do not allows to change property visibility in descendant classes. To solve my issue I have to copy core class and replace it by my needs. 

I would be much appreciated if you will add ability for developers to set getters and setters for app level properties like `name`, `charset`, `sourceLanguage`, `language`. Not big issue actually. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8

**Comment by lynicidn** [comment]
add test for it - all methods need cover

**Comment by magicaner** [comment]
@lynicidn tests are added

**Comment by samdark** [comment]
It looks OK but I want to ask for @yiisoft/core-developers opinions first.

**Comment by cebe** [comment]
this is a bit of overkill, why do you need this for all of the mentioned properties?

changing `sourceLanguage` means you need to change the code so there is no sense in putting this into the database, same for charset.

**Comment by magicaner** [comment]
@cebe I am having custom configuration source, and all application options are saved here. And want add getter to application which allows me read those options transparently from my configuration, just like they are application properties, this is actually very flexible. Why not allow developers such feature? I tried to explain carefully at issue above, please take a look.

**Comment by cebe** [comment]
@magicaner you did not give reasoning for the single properties. Imo it does not make any sense to configure sourceLanguage and charset dynamically. it may be useful to language and name though.

**Comment by magicaner** [comment]
@cebe okie, I will try again :)
I suppose they are stored at configuration for some reasonable reasons. And if configuration moved to separate component than it is reasonable to read them directly instead of setting application properties on each initialization? also setting them at application will create duplications in such case.

**Comment by cebe** [comment]
the question is, what is the point of setting sourceLanguage and charset dynamically from database? it does not make any sense to me as these depend on how the code is written.

**Comment by magicaner** [comment]
@cebe if you need real example here is one:
Lets purpose CMS allows to setup multiple websites per one application instance. Each website can have own configuration, can setup configuration from admin panel without touching static config files,  can have own themes and translation files and so on. They can have different sourceLanguage and charset. 

Do you think something wrong with that?

**Comment by cebe** [comment]
If you have a theme that has files in different charset than the application you run into a lot of problems.
Also if your theme has different source language than the application, the property to change the source language would be the one of the MessageSource and not the property in the application itself.

**Comment by SilverFire** [comment]
Agreed with @cebe

Closing unless further information provided

**Comment by magicaner** [comment]
@SilverFire does this mean pull request will be declined also?
@cebe Guys you doing a bit bureaucracy here. 
Look, the provided changes does not braking the basic design, those properties are already public, and can be changed even during application run. 
What is changed is only public geters and seters are added, which mean properties still stays under public visibility. 
So this talk is not about what is good or what is not. I just added geters and seters... Which is makes application class more extendable.... 
I will appreciate if you will read issue more carefully

**Comment by cebe** [comment]
as explained before, the only property for which it could make sense would be $language but language is usually set in some request handler where information about requested browser language is available. for all other properties there is no sense in doing this. If you want to populate settings from a database a more appropriate place would maybe be `init()`.
