### ISSUE TITLE
Auto Login not worked when login by access token

### ISSUE THREAD

**Issue by mathedu4all** [yiisoft/yii2#11650]
### What steps will reproduce the problem?
Login by access token.

### What is the expected result?
auto login by cookie.

### What do you get instead?
auto login not worked.

I found the reason.

The identity and duration is not written into the cookie when login by access token.

Since the cookie is written by switchIdentity function in yii/web/user.php, but it is not applied in LoginByAccessToken function?

**Comment by tunecino** [comment]
It shouldn't work. the propose of token based authentication is to not use session and being able to remove it completely so you can build a stateless environnement like RESTful Web Service APIs. see [docs](http://www.yiiframework.com/doc-2.0/guide-rest-authentication.html) for more info.
