### ISSUE TITLE
RFI: Yii2: error handling and redirects

### ISSUE THREAD

**Issue by ppokrovsky** [yiisoft/yii2#11663]
Hi.

First of all - thanks for a wonderful framework. It's absolutely glorious.

Just a request for information I guess. I bumped into a bug in my app recently. I have a custom error handler which for certain types of exceptions sets an exception message to flash and redirects user back.

It was implemented like this:
```php
class CustomErrorAction extends ErrorAction
{
    public function run()
    {
        if (($exception = \Yii::$app->getErrorHandler()->exception) === null) {
            return '';
        }
        if ($exception instanceof CustomException) {
            $message = $exception->getMessage();
            \Yii::$app->session->setFlash('customexception', \Yii::t('app', $message));
            return $this->controller->redirect(\Yii::$app->request->getReferrer());
        }
        return parent::run();
    }
}
```

it used to work, but then I upgraded to ```2.0.8``` and it started to throw ```500```

so I found this note in the [docs](http://www.yiiframework.com/doc-2.0/guide-runtime-handling-errors.html):
```
Note: If you need to redirect in an error handler, do it the following way:
Yii::$app->getResponse()->redirect($url)->send(); return; 
```

and I changed implementation to this:
```php
class CustomErrorAction extends ErrorAction
{
    public function run()
    {
        if (($exception = \Yii::$app->errorHandler->exception) === null) {
            return '';
        }
        if ($exception instanceof CustomException) {
            $message = $exception->getMessage();
            \Yii::$app->session->setFlash('customexception', \Yii::t('app', $message));
            $redirect = \Yii::$app->request->referrer;
            \Yii::$app->response->redirect($redirect)->send();
            return true;
        }
        return parent::run();
    }
}
```
and the bug's gone.

Just curious though, has there been a change in the core or my first approach was never correct and should not have worked in the first place?

Thank you!

**Comment by SamMousa** [comment]
I imagine that the error handler is called regardless if a controller exists. Suppose the error occurs for one of these reasons:
1. Controller does not exist.
2. Controller constructor throws an exception.

In these cases the controller, which you access via the service locator might not be available. 
You can try it by checking out 2.0.7 and creating a controller that just throws an exception.

**Comment by samdark** [comment]
The behavior changed but it was never intended to work w/o `->send()` in case of error handler.
