### ISSUE TITLE
GridView filter row is always positioned in the thead element

### ISSUE THREAD

**Issue by koredalin** [yiisoft/yii2#11666]
### What steps will reproduce the problem?
GridView->**$filterPosition** = self::FILTER_POS_BODY;
This variable is set to tbody as default. No matter of it's value - **the filter row** is always added to the **thead** element.

### What is the expected result?
 **The filter row** has to be positioned as the **$filterPosition** property is.

### What do you get instead?
 **The filter row** is always added to the is always added to the **thead** element.

### Additional info
renderTableHeader() -> elseif ($this->filterPosition === self::FILTER_POS_BODY) {$content .= $this->renderFilters();}
code should be moved to the renderTableBody() method of the GridView class.
Same case is for the footer function-method.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.8
| Operating system | Windows

**Comment by klimov-paul** [comment]
> This variable is set to tbody as default. No matter of it's value - the filter row is always added to the thead element.

This is expected: see the description for the filter position constants:

```
- [[FILTER_POS_HEADER]]: the filters will be displayed on top of each column's header cell.
- [[FILTER_POS_BODY]]: the filters will be displayed right below each column's header cell.
- [[FILTER_POS_FOOTER]]: the filters will be displayed below each column's footer cell.
```

If you choose `FILTER_POS_HEADER` filter appears at the top row of `thead`, if `FILTER_POS_BODY` - at the bottom of `thead` if `FILTER_POS_FOOTER` - at the footer.

**Comment by koredalin** [comment]
Thank you Paul,
I have override GridView class. Functions renderTableHeader(), renderTableBody(). All works fine now.
I'm not sure if I understand exactly the configurations, so I've wrote mine.

Regards
Hristo Hristov
