### ISSUE TITLE
how to add an ID for CSS file by appasset?

### ISSUE THREAD

**Issue by sumic** [yiisoft/yii2#11660]
appasset.php
```
public $css = [
        'css/site.css',
    ];
```
view source 
`<link href="/css/site.css" rel="stylesheet">
`
i want to add an id for my css file like this:
`<link href="/css/site.css" rel="stylesheet" id=""maincss">`
how can i do that?
thx~!

**Comment by jmbb** [comment]
That is invalid html
http://www.w3schools.com/tags/tag_link.asp

**Comment by mdmunir** [comment]
```php
public $css = [
        ['css/site.css', 'id' => 'css-id'],
        'other_style.css',
    ];
```

**Comment by sumic** [comment]
@mdmunir thank u very much~

**Comment by Faryshta** [comment]
@jmbb https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link its valid. 

@sumic please close the issue.
