### ISSUE TITLE
For $user->save() created_at datatype changed as datetime so its not working in yii2

### ISSUE THREAD

**Issue by nagarajanp1naga** [yiisoft/yii2#11677]
### What steps will reproduce the problem?
Changed user table created_at column datatype as datetime, updated model from gii tool. And passing created_at value as '2016-06-02 05:32:21'.

### What is the expected result?
Data should save in user table.

### What do you get instead?

Database Exception – yii\db\Exception
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1464845800' for column 'created_at' at row 1
The SQL being executed was: INSERT INTO `user` (`access_token`, `email`, `created_at`, `password_hash`, `auth_key`, `updated_at`) VALUES ('lZ3lk2o6cIVVDtNiRi6OynVEV9nISgxU', 'naga1@gmail.com', '1464845800', '$2y$13$iy8ldHu1uG.ndZYO9fYjpu8/0k6hVehpdYZT4WzK29fDnYDbeifK.', 'yrIWw1QeHU6SWhL2btl1UJSInEp_GR2R', '1464845800')

Error Info: Array
(
    [0] => 22007
    [1] => 1292
    [2] => Incorrect datetime value: '1464845800' for column 'created_at' at row 1
)

↵
Caused by: PDOException
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1464845800' for column 'created_at' at row 1

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      | 7
| Operating system | linux

**Comment by nagarajanp1naga** [comment]
Resolved 

I commented these behaviors() in User model

/*    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
*/

**Comment by samdark** [comment]
Either that or you can configure `TimestampBehavior`.
