### ISSUE TITLE
Adds year to date

### ISSUE THREAD

**Issue by strelov1** [yiisoft/yii2#11676]
### What steps will reproduce the problem?

```
       $date = "29.12.1988";
        var_dump(Yii::$app->formatter->asDate($date, 'dd.MM.Y')); // 29.12.1989
        var_dump(Yii::$app->formatter->asDate((new \DateTime($date)), 'dd.MM.Y')); //29.12.1989
        var_dump(Yii::$app->formatter->asDate($date, "php:d.m.Y")); //29.12.1988
        var_dump(Yii::$app->formatter->asDate($date, "«d» MMMM Y")); //«29» декабря 1989

```
     
### What is the expected result?
       $date = "29.12.1988";
        var_dump(Yii::$app->formatter->asDate($date, 'dd.MM.Y')); // 29.12.1988
        var_dump(Yii::$app->formatter->asDate((new \DateTime($date)), 'dd.MM.Y')); //29.12.1988
        var_dump(Yii::$app->formatter->asDate($date, "php:d.m.Y")); //29.12.1988
        var_dump(Yii::$app->formatter->asDate($date, "«d» MMMM Y")); //«29» декабря 1988
### Additional info

| Q                | A
| ---------------- | ---
| Yii version     2.07 | 
| PHP version     5.6.20 | 
| Operating system  Ubuntu 14.10|

**Comment by lynicidn** [comment]
strtotime

**Comment by githubjeka** [comment]
ICU bug

**Comment by strelov1** [comment]
http://userguide.icu-project.org/formatparse/datetime
y  year 1996
Y  year of "Week of Year" 1997
