### ISSUE TITLE
Create new AuthorizerInterface

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11679]
I want to implement a custom authorization tool that does not support all the "management" functions defined in `ManagerInterface`

The only method that is used by the framework is `checkAccess`.
I propose moving this method to a separate `AuthorizerInterface`, `ManagerInterface` would then extend the new interface.

The goal of this split is to separate the management of permissions and the checking of permissions. This change would not break backwards compatibility.

Advantage of this approach is also that it becomes easier to implement adapters to other authorization systems.

Combined with this change I would also change the `yii\web\User` to accept a configuration for which authorizer it would use:
````
/**
     * Returns auth manager associated with the user component.
     *
     * By default this is the `authManager` application component.
     * You may override this method to return a different auth manager instance if needed.
     * @return \yii\rbac\ManagerInterface
     * @since 2.0.6
     */
    protected function getAuthManager()
    {
        return Yii::$app->getAuthManager();
    }
````

Would become:
````
    public $authorizer;
    protected function getAuthManager()
    {
        return isset($this->authorizer) ? Yii::$app->get('authorizer') : Yii::$app->getAuthManager();
    }
````

Allowing developers to change the component used via configuration, as is the common approach in the framework.

**Comment by nkostadinov** [comment]
While we are on the subject - using checkAccess for both checking if a user belongs to a role and whether they have permission to do some task is confusing at least.

**Comment by samdark** [comment]
Makes sense to me.

**Comment by SamMousa** [comment]
Should I implement or will you?

**Comment by samdark** [comment]
If you have time, it would be great if you'll do it. I'm back from vacation and there's endless list of unread issues :)

**Comment by SamMousa** [comment]
Closing this since the only point that needs to be discussed is the name of the interface and that can be done in the PR.

**Comment by cebe** [comment]
we usually keep issues open until pr is merged.
