### ISSUE TITLE
Possible documentation broken link

### ISSUE THREAD

**Issue by ComradePashka** [yiisoft/yii2#11680]
Hi! I am not sure I should start an issue here, but it's not clear which option should I choose from suggested ones for [Contributing to Yii2](https://github.com/yiisoft/yii2/blob/master/.github/CONTRIBUTING.md)

In [official documentation](http://www.yiiframework.com/doc-2.0/index.html) there is a subject "Auth Clients" and it seems everything looks fine with URL at https://github.com/yiisoft/yii2/blob/master/docs/guide/security-overview.md
But at the site there is also navigation at left side that has wrong URL for this topic pointing to: http://www.yiiframework.com/doc-2.0/guide-README.html
instead of:
https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/README.md
I guess last one is correct, isn't it?
 
![image](https://cloud.githubusercontent.com/assets/15798005/15749568/8b14c544-28eb-11e6-88ab-f6f2778528b8.png)

And I have no idea where can I make a pull request to fix it and is it possible at all.

**Comment by CedricYii** [comment]
Duplicate of #9922
