### ISSUE TITLE
BC Break for fixture parameters.

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#11683]
### What steps will reproduce the problem?

Execute command

`yii fixture "*" -User`

### What is the expected result?

Loads all the fixtures except for the `UserFixture`

### What do you get instead?

Tries to determine the `-User=1` alias which doesn't exist for the fixture controller.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | linux

Its caused by commit https://github.com/yiisoft/yii2/commit/6a5df6476831e4131e9a33d6f01d643508f88aa6 which add the alias shortcuts.

**Comment by Faryshta** [comment]
@yiisoft/core-developers the BC is already broken, would you be interested in a fix which requires a change on the command call?

`yii fixture "*, -User"

Instead of

`yii fixture "*" -User`

**Comment by samdark** [comment]
Well, yes. It's better than broken.
