### ISSUE TITLE
LoginRequired throws 'ForbiddenHttpException' for AJAX requests

### ISSUE THREAD

**Issue by flowip** [yiisoft/yii2#11685]
### What steps will reproduce the problem?
1) Sign in
2) Remove session cookie
3) Try to make simple AJAX request

### What is the expected result?
Redirect to login page.

### What do you get instead?
Sine 2.0.8 I get 403 error instead.

### Additional info
As I see it's because of '$canRedirect' variable. Tested in Chrome 51.

| Q                | A
| ---------------- | ---
| Yii version     |  2.0.8 
| PHP version      |  5.6
| Operating system  |  Debian

**Comment by SamMousa** [comment]
@flowip This behavior was changed in 2.0.8.
Are you setting your accept headers to something that does not include `html`? If you are requesting `json` via AJAX then redirecting you to a page that returns `html` is not the logical thing to do.

If you prefer to have the old behavior you can set `$acceptableRedirectTypes` and have it include the mime type of the request you are making.

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.

**Comment by flowip** [comment]
@SilverFire 

I'm sending AJAX request  to get html with the following headers: 
```
Accept:*/*
X-Requested-With:XMLHttpRequest
```

If it's desired behavior since 2.0.8 to return 403 error if a user is not logged in for requests with these headers, I think this ticket should be closed.

I do want to redirect user if he was logged out.
I have implemented redirect this way in my controller:
```
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    if (Yii::$app->user->getIsGuest()) {
                        Yii::$app->user->loginRequired(true, false);
                    } else {
                        throw new ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
                    }
                },
            ],
        ];
    }
```

**Comment by joeyblack835** [comment]
@flowip When I do Yii::$app->user->loginRequired(true, false) in beforeAction, it runs the action first and then redirects.

**Comment by SamMousa** [comment]
Don't necro unrelated issues please.
