### ISSUE TITLE
ActiveForm breaks when ::begin and ::end are called in different views

### ISSUE THREAD

**Issue by adlogic** [yiisoft/yii2#11687]
It is related with recent changes to support auto setting of enctype property. This feature works only when ::begin and ::end methods are called in the same view. Otherwise, output buffers stack will be corrupted, which leads to broken output.
### What steps will reproduce the problem?
wizard.php
```
<?= $this->render('_form_top', [
    'model' => $model,
]) ?>

<!-- SOME CONTENT HERE -->

<?= $this->render('_form_bottom', [
    'model' => $model,
]) ?>
```
_form_top.php
```
<?php use yii\widgets\ActiveForm ?>
 
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
```
_form_bottom.php
```
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<?= Html::submitButton('Save', ['class' => 'btn btn-primary btn-btn']) ?>

<?php ActiveForm::end(); ?>
```
### What is the expected result?
```
<form>
    <input />
    <!-- some content -->
    <button />
</form>
```
### What do you get instead?
```
<input />
<!-- some content -->
<form>
    <button />
</form>
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | CentOS

So, it should be stated implicitly in documentation and upgrade guide, or auto-enctype should be removed/rewritten.

**Comment by lynicidn** [comment]
```php
<?php $form = ActiveForm::begin(); ?>
<?= $this->render('_form_top', [
    'model' => $model,
    'form' => $form,
]) ?>

<!-- SOME CONTENT HERE -->

<?= $this->render('_form_bottom', [
    'model' => $model,
    'form' => $form,
]) ?>
<?php $form->end(); ?>
```

**Comment by adlogic** [comment]
Yeah, but I have some common content before ::begin and some after ::end, so I need another 2 renders with 2 more views. And I have them in 6 wizard steps. So, I ended up with custom ActiveForm override to speed up things.

Anyway, mentioned change breaks backwards compatibility between 2.0.7 and 2.0.8, so it should be stated implicitly in docs.

**Comment by pana1990** [comment]
it's Strange, that code works for me...

**Comment by lynicidn** [comment]
@pana1990 hm, render output buffer - in close tag form. First view on this time also rendered (without open form tag)

**Comment by pana1990** [comment]
@lynicidn upsss, yeah i see, i will try to fix later

**Comment by cebe** [comment]
While it was possible before it was never intended to work this way. I am updating the docs to be explicit about this.
