### ISSUE TITLE
Multiple Uniques generated in a model

### ISSUE THREAD

**Issue by midcore-nam** [yiisoft/yii2#11684]
### What steps will reproduce the problem?
Using Gii to generate a model.
simple table with a column name 'C1'
### What is the expected result?
I should only get 1 Unique rule in the rules array
### What do you get instead?
public function rules() 
    { 
        return [
            [['LinkedId', 'CreatedByUserId', 'LastModifiedByUserId'], 'integer'],
            [['CreatedTimestamp', 'LastModifiedTimestamp'], 'safe'],
            [['CreatedByUserId', 'LastModifiedByUserId'], 'required'],
            [['C1'], 'string', 'max' => 150],
            [['C1'], 'unique'],
            [['C1'], 'unique'],
            [['C1'], 'unique'],
            [['C1'], 'unique'],
            [['C1'], 'unique'],
            [['C1'], 'unique'],
            [['C1'], 'unique'],
            [['LinkedId'], 'exist', 'skipOnError' => true, 'targetClass' => Table1draft::className(), 'targetAttribute' => ['LinkedId' => 'id']],
        ]; 
    } 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7
| Operating system | win 10

**Comment by samdark** [comment]
1. Could you post a schema for the table?
2. Which database is that? MySQL?

**Comment by midcore-nam** [comment]
yes i'm using MySQL.
Column C1 is unique.

**Comment by midcore-nam** [comment]
![image](https://cloud.githubusercontent.com/assets/16084009/15832192/11c1c046-2bef-11e6-91b0-6f437bc04ed4.png)
