### ISSUE TITLE
SluggableBehavior and compound words

### ISSUE THREAD

**Issue by brussens** [yiisoft/yii2#11699]
### What steps will reproduce the problem?
You can not convert complicated words in the slug.

### What is the expected result?
Converted slug from string.

### What do you get instead?
Empty result.

### Additional info
For example, it is impossible to generate slug from a string of "Северо-Казахстанская область" or "Општина Пехчево". Empty result returns.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7.0.4
| Operating system | Windows 10

**Comment by SamMousa** [comment]
From `Inflector::slug()`:
````
/**
     * Returns a string with all spaces converted to given replacement,
     * non word characters removed and the rest of characters transliterated.
     *
     * If intl extension isn't available uses fallback that converts latin characters only
     * and removes the rest. You may customize characters map via $transliteration property
     * of the helper.
     *
     * @param string $string An arbitrary string to convert
     * @param string $replacement The replacement to use for spaces
     * @param boolean $lowercase whether to return the string in lowercase or not. Defaults to `true`.
     * @return string The converted string.
     */
````
I guess your strings don't contain any latin characters and your installation does not have the `intl` extension available.

**Comment by brussens** [comment]
Hmm... Intl extension avaliable...

**Comment by samdark** [comment]
@brussens should not happen then. A way to verify that is to create a pull request with a unit test failing.

**Comment by SamMousa** [comment]
@samdark, regardless of this being a bug, would it not make sense to always throw an exception in case the result is an empty string?

--> If yes, then I can implement that.

**Comment by samdark** [comment]
Not really. If the input is empty then empty output is a valid.

**Comment by SamMousa** [comment]
But creating a slug for an empty string is more likely an error than
intentional right?

**Comment by samdark** [comment]
It depends on where it's used. It may be optional URL.

**Comment by brussens** [comment]
Very much sorry !!! The problem malfunction expansion Intl on Open Server. On the Linux server, all okay.
