### ISSUE TITLE
'date' core validator is converting timezones when just requesting formatting.

### ISSUE THREAD

**Issue by decimoseptimo** [yiisoft/yii2#11692]
A picture is worth a thounsad words.
![sin titulo](https://cloud.githubusercontent.com/assets/16873203/15797730/9d6f8cba-29d6-11e6-9762-9ad11459e2f6.png)

createdAtTimeMachineFormat 
original value is 7:30:16 PM, returned result is 02:30:16 but should be 19:30:16 as that is the straight converison from PM to 24hrs. format. Application timezone is set to 'America/Tijuana', that's -07:00, and there is just that difference between the expected and returned value.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7.x
| Operating system | win10

**Comment by agungsijawir** [comment]
Have you set dateFormat on formatter components on your config? http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#$timeFormat-detail

**Comment by decimoseptimo** [comment]
No i haven't enabled the i18n component.

**Comment by agungsijawir** [comment]
Not i18n component, but formatter component.  See here for timezone settings.

http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#$defaultTimeZone-detail

**Comment by agungsijawir** [comment]
Please try it.

**Comment by decimoseptimo** [comment]
`'formatter' => ['defaultTimeZone' => 'UTC'],`

As that is doesn't do anything as the model attributes values come from db colums in the UTC timezone. Chaging it to 'America/Tijuana' mess things up, as I already am formatting the values to the user in the DataColumn.

My yii\grid\DataColumn

`[
                'attribute' => 'createdAtTime',
                'value' => function($model) {
                    //return $model->created_at;
                    return Yii::$app->formatter->asTime($model->created_at);
            }],`

**Comment by decimoseptimo** [comment]
As I am still wrestling with dates. I further dug into this issue. I've come to the realization that when

 `    //'timezone' => 'America/Tijuana',`

and

`'formatter' => [
            'defaultTimeZone' => 'UTC',
            'timeZone' => 'America/Tijuana',
        ],` 

are both set. The former will matematticaly add to the latter.

In my example the source value is `17:30:16 PM` so formatter generates ` 19:30:16 ` which is correct. But if latter `application::$timezone = 'America/Tijuana'` the value will be `2:30:16` (-7 hours from formatter). Or if `application::$timezone = 'Etc/GMT+2'` the value will be `21:30:16`. (+2 hours from formatter).

Hope it helps.

**Comment by cebe** [comment]
formatter is used to convert dates that are stored in common timezone, normally UTC in the database into user timezone. if you do not want the formatter to change the timezone, `defaultTimeZone` and `timeZone` property must be the same. see also http://www.yiiframework.com/doc-2.0/guide-output-formatting.html#time-zones

**Comment by decimoseptimo** [comment]
I understand this better that when I started the issue. And merely judging by the title sounds fair to close it. But what about my last but one comment, is that behaviour expected ?

**Comment by cebe** [comment]
Maybe I did not completely understand your comment but if you set the timezone in the formatter explictily, it will ignore application timezone. So I do not really get what you want to say with that.

**Comment by cebe** [comment]
Here is the test that verifies timezone conversion: https://github.com/yiisoft/yii2/blob/master/tests/framework/i18n/FormatterDateTest.php#L656-L666
If you come up with a failing conversion, let me know.

**Comment by decimoseptimo** [comment]
I'm sorry because I'm not being orderered in my ideas. The issue IS NOT happening with yii\i18n\Formatter but rather IS happening at yii\validators\DateValidator.

**Comment by cebe** [comment]
DateValidator has a [`timeZone`](http://www.yiiframework.com/doc-2.0/yii-validators-datevalidator.html#$timeZone-detail) property which defaults to the application timezone. it will assume that the input date is in that timezone and will convert it to a unix timestamp (which is always UTC) or convert it to the `timestampAttributeFormat` using the `timestampAttributeTimeZone`.

**Comment by cebe** [comment]
So in your case it should convert the input time from `America/Tijuana` to UTC. If you do not want any conversion, you have to set the `timestampAttributeTimeZone` to `America/Tijuana`.

**Comment by decimoseptimo** [comment]
I've been analysing this (just the whole day), and agree you're correct, just some thoughts:
In my opinion the "timezone" word usage is a bit ambiguate.

in yii\i18n\Formatter
Formatter::$defaultTimeZone //from (UTC)
Formatter::$timeZone //to (Application)

in yii\validators\DateValidator
DateValidator::$timeZone; //from (User input)
DateValidator::$timestampAttributeTimeZone; //to (UTC)

Same attribute means different direction. And same direction with different attribute.
I understand that both $timeZone attributes matches application::$timezone name tought.

I better understand now how both classes work, BUT I was CLUELESS at first. I think the documentation needs an example (or reference to a wiki) that put this two classes together to work, perhaps leaving a "pending example" mark.

**Comment by cebe** [comment]
yep, I agree. that is why I marked this issues as documentation issue.
