### ISSUE TITLE
active form with validation url

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#11691]
### What steps will reproduce the problem?

``` php
 <?php $form = ActiveForm::begin([
        'method' => 'get',
        'action' => ['search'],
    'enableAjaxValidation' => true,
    'validationUrl' => ['search-validate'],
]); ?>
```
### What is the expected result?

validation
### What do you get instead?

validation request send to `/index.php?r=site/search-validate&r=site/search&SearchForm[searchAttribute]=searchValue&...`
//&r=site/search not need. override validation route
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9-dev |
| PHP version | 5.6 |
| Operating system | deb |

**Comment by lynicidn** [comment]
with 
'enablePrettyUrl' => true,
this ok.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L328 - it's valid ?

https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L340 i think this arguments need generate in action of form, for what is hidden?

**Comment by lynicidn** [comment]
это связано даже не сразными урлами экшн и валидации, но и даже без validationUrl
фиксим:
если на 528 строке добавить 
data.submitting = true;
т.е. перед запуском валидации, так же как и в методе beforeSubmit в "1м чтении", - то вроде ниче не падает, логика не страдает и beforeValidate начинает отрабатывать, но перестает отправляться форма, что ожидаемо - мы всегда прерываем beforeValidate устанавливая свой, поэтому нужно отключать у формы
'validateOnSubmit' => false,

но до этого форма и сабмитилась, потому что обработчик не становился куда нужно.

Кстати это событие легко проверить - повесьте свой обработчик function(){return false;}
на beforeValidate - и сабмитьте форму сколько угодно - это нынешнее состояние дел ;) - сейчас флаг validateOnSubmit не влияет на результат валидации

**Comment by lynicidn** [comment]
@samdark переоткрой или создать новый?

**Comment by lynicidn** [comment]
>https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L328 - it's valid ?

sorry, this correct, but better really equals with 0

>for what is hidden? 

if i don't use cookie and send form to absolute url, i send ?PHPSESSID also?

**Comment by samdark** [comment]
PHPSESSID is sent by PHP itself. Yii doesn't affect that.

**Comment by dynasource** [comment]
this topic hard to support. Please reformulate your problem & give us a clear pointer what should be done/improved.

**Comment by derekisbusy** [comment]
#13545 and yiisoft/jquery-pjax/pull/52 fixes this issue.
