### ISSUE TITLE
Formatter ignore Timezone

### ISSUE THREAD

**Issue by MagSag** [yiisoft/yii2#11696]
I have UCI version 51.1 on my local computer but online UCI version 54.1. My timezone is Africa/Nairobi (+03:00);  the problem is the previous solution, adding timezone to the date: ```
Yii::$app->formatter->asDatetime('2016-3-1 10:08:27' . Yii::$app->getTimeZone(),'php:D d-M-Y H:i:s');
//Result is 2016-3-1 10:08:27
```)  is working on my local computer.
Online if I add the timezone it displays the date in UTC:

//Result is 2016-3-1 7:08:27

and if I remove the timezone it's displaying the date correctly.

I try to accuse the version but have not found enough theory to support the accusion.

I really don't get it!!!! I have to pass through all my code to remove the timezone I added; before doing that I wanted to know if my accusation is correct and move on.
Yii version 2.6
php version 5.4

**Comment by samdark** [comment]
@MagSag can you update Yii to latest version and check again?

**Comment by cebe** [comment]
@MagSag you may set the formatter defaultTimeZone to `Africa/Nairobi` so you do not have to add it to every date value.

**Comment by cebe** [comment]
also not that `Yii::$app->getTimeZone()` returns the default value from php configuration. it may be different on your server. you should set it explicitly in your application config.
