### ISSUE TITLE
batchInsert with empty rows

### ISSUE THREAD

**Issue by tut4ever** [yiisoft/yii2#11693]
### What steps will reproduce the problem?
Yii::$app->db->createCommand()
                ->batchInsert('{{%note_tag}}',
                    ['note_id', 'tag_id'], [])
                ->execute();

### What is the expected result?
Syntax error

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.6.19
| Operating system | Windows 8.1 Enterprise N Edition

**Comment by SamMousa** [comment]
Confirmed that this will create invalid SQL at least on MySQL.

1. We could add a check to see if the rows array is empty, but then do we throw an exception or not? --> Not doing the query still means my request has succeeded (I've successfully inserted an empty set)

2. While we are at it we might also want to check each row for the proper number of fields.

**Comment by SamMousa** [comment]
@samdark Feel free to assign this to me after answering my questions ^^

**Comment by samdark** [comment]
1. Inserting nothing when nothing was provided is a success. Should not throw exception.
2. Won't DB do it by itself?

**Comment by SamMousa** [comment]
Yes database will check it but if the batch is big it will be faster to check it yourselves; basically we save the round-trip to the db.

**Comment by rob006** [comment]
But it will slow down every proper query.

**Comment by SamMousa** [comment]
We loop over the array anyway, it'll be O(2n) which it the same; I'll
benchmark it.

**Comment by rob006** [comment]
But what is the point of duplicate this validation to increase performance of **incorrect** code?

**Comment by SamMousa** [comment]
Better error handling; isn't it essentially the same as the unique
validator?

What do you suggest?

**Comment by samdark** [comment]
I suggest ignoring this case. It's not likely to happen when system gone live.

**Comment by rob006** [comment]
> What do you suggest?

I suggest ignore it. Unique validator is only validator, not internal and mandatory additional validation - you are free to not use unique validator if you know what you're doing. 
Besides, if data for `batchInsert()` came from user input, it should be already validated by validation rules. You suggest validate this three times - first by validators, second by additional check in `batchInsert()` and the third time by DBMS.

**Comment by buelsenfrucht** [comment]
I have the same issue on Postgres, using batchInsert in migrations.
Calling batchInsert with an empty array generates invalid SQL like

`INSERT INTO table (col1, col2) VALUES;`

I was thinking about fixing it with just returning an empty string if array is empty, but I'm not so deep into Yii to know if that would have any side effect...
