### ISSUE TITLE
AuthAssignment Backwards incompatibility (Yii 2 to Yii 1.1)

### ISSUE THREAD

**Issue by jrobles-boom** [yiisoft/yii2#11702]
### What steps will reproduce the problem?

There's no way to change the primarykey name on Auth\DbManager

### What do you get instead?

Hardcode user_id instead overridable placeholder.

### Rationale
I've got a huge application on Yii1 to be migrated to Yii2. That is a lot of work to be done at once, so I'm migrating progressively, and both Applications must be functional at the same time.

Auth\DbManager should not have hardcoded primary key column (*user_id*) that prevents me to reuse the Database structure of the legacy application (primary key *userid* --- no underscore)

### What I propose.

Implement primaryKey() or $primaryKey on Auth\DbManager, so it could be easily overriden by extension or configuration.

**Comment by samdark** [comment]
I'm OK adding it. Would you like to make a pull request?

**Comment by jrobles-boom** [comment]
Of course, what branch should I use?

**Comment by samdark** [comment]
Master.

**Comment by jrobles-boom** [comment]
Certainly, there's more than I thought first time, as it is a completely different implementation.
What should it be the minimum compatibility changes?

In my case, I should customize also **item_name** to **itemname**, as _AuthItem_, _AuthItemChild_ and _AuthRule_ are somewhat static on my application. _AuthAssignment_ is updated several times a day. 

I could make another pull request to implement $authAssignmentPk['user_id'] and $authAssignmentPk['item_name'] as both are Pks of the table.

.. but I don't know if this implementation would suffice on other cases.

#### AuthAssignment

1.1  |  itemname |  userid | bizrule | data
2.0 |   item_name |  user_id  | created_at
    
#### AuthItem
1.1 |  name  |  type |   description | bizrule |data
2.0  |  name  |  type   | description |rule_name  | data   | created_at | updated_at
    
#### AuthItemChild
1.1  |  parent  | child
2.0  |   parent  | child

#### AuthRule
2.0 |   name    | data  | created_at | updated_at

**Comment by samdark** [comment]
Hmm... How about creating an SQL view for the purpose?

**Comment by SamMousa** [comment]
@jrobles-boom, would this ease your migration? 
https://github.com/yiisoft/yii2/issues/11679

That way you could just implement the access check yourself using the old database structure (by porting parts of yii1 auth manager).

**Comment by samdark** [comment]
If either of the alternatives would work, I'd like to revert changes merged previously.

**Comment by jrobles-boom** [comment]
@samdark Ugly but functional. I had the same idea yesterday, but tried to forget :) I've sent a pull request with the missing pk. It's working for my app right now, as I can maintain other tables than AuthAssignment as they are. Permissions structure will be rebuilt on the new application anyways, but I need to keep the thousand users assignments.
@SamMousa Could be done, indeed, but the pull request I sent suffice.
@samdark is your call. the pull request does not harm anyways. :)

**Comment by samdark** [comment]
I've reverted previous change. Since it's not common to change the structure and it could be achieved by other means (views and what @SamMousa pointed out), I prefer things to be simpler.

**Comment by jrobles-boom** [comment]
@samdark thanks!
