### ISSUE TITLE
ENH: Ability to remove session cookie

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#11706]
### What steps will reproduce the problem?

`\Yii::$app->session->destroy()` (also called by `\Yii::$app->user->logout(true)`)
### Actual result

New session cookie was sent.
### What do you want?

Ability to configure session to send cookie deletion when session is destroing.
So, `\Yii::$app->session->destroy()` will cause session cookie to be deleted.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |
| PHP version | 5.5.9 |
| Operating system | Ubuntu 14.04 |

**Comment by samdark** [comment]
Try master please.

**Comment by Vovan-VE** [comment]
Yes, same result at master on a3cf6302cb1ce9ef2446f88ccf97cb9b1a7d4428 . Debug module said in the end:

> User '...' logged out from 127.0.0.1

and nothing else. Response headers shows `Set-Cookie:` with new session id and deletion of user identity.

**Comment by Vovan-VE** [comment]
I just fetch `dev-master` with composer. Looks like it was not so fine.

**Comment by Vovan-VE** [comment]
Oh, composer refers to different repository.

**Comment by SilverFire** [comment]
Normal `session_destroy()` behavior deleted all data associated with the session, but does not drop a cookie ([proof](http://php.net/manual/en/function.session-destroy.php)).
If you need to drop cookie as well - you can do it in your project.
