### ISSUE TITLE
Undefined index in core view

### ISSUE THREAD

**Issue by achertovsky** [yiisoft/yii2#11700]
### What steps will reproduce the problem?
Cause exception. yii/base/ErrorException must cause it
### What is the expected result?
Right display of log
### What do you get instead?
Undefined index: class in file /data/projects/dsmtool/vendor/yiisoft/yii2/views/errorHandler/exception.php on line 385

### Additional info
i'm logging all errors of system and found it

| Q                | A
| ---------------- | ---
| Yii version      |  This is Yii version 2.0.9-dev.
| PHP version      | PHP 5.5.9-1ubuntu4.17
| Operating system | ubuntu 14.04 lts

**Comment by samdark** [comment]
Can't reproduce it. What I've done:

- Installed basic project template.
- Modified SiteController:

```php
public function actionIndex()
{
    throw new ErrorException('test');
    return $this->render('index');
}
```

![exception](https://cloud.githubusercontent.com/assets/47294/15831259/6341b6d4-2c25-11e6-80a9-6c75aeaaceb7.png)
