### ISSUE TITLE
Tests fail due to chmod not being supported on non-local filesystems.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11711]
### What steps will reproduce the problem?
I'm running tests in vagrant using ubuntu 15.10 and php 5.6

### What is the expected result?
Test succeeds.
### What do you get instead?
````
1) FileHelperTest::testCopyDirectoryPermissions
Destination directory has wrong mode!
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'755'
+'0775'
````
### Additional info
It seems to me that these are in fact the same permissions, they just use a different notation. I could not find anyhting in the PHP docs pointing to changed behavior for `fileperms()`.

| Q                | A
| ---------------- | ---
| Yii version      | 38445c6e3ef2ea2db66f02909d7a3759386e820f
| PHP version      | php 5.6.11
| Operating system | Ubuntu 15.10

**Comment by samdark** [comment]
Can you come up with a fix?

**Comment by SamMousa** [comment]
I'll give it a go.

**Comment by SamMousa** [comment]
Oh just noticed now that 755 and 0775 are actually not the same, so it might actually be a bug :) -- regardless I'll look into the fix.

**Comment by SamMousa** [comment]
It seems `chmod` is returning `true` when it shouldn't; could be related to using a vagrant mount (ubuntu host and ubuntu guest).

**Comment by SamMousa** [comment]
Have changed tests so they are skipped when runtime is not on a local file system.
-- It could be a nice feature to add support for configuring the runtime directory it uses in `config.local.php`; that way devs could just change it locally to something like `/tmp`.

**Comment by samdark** [comment]
Merged.

**Comment by samdark** [comment]
Thanks!
