### ISSUE TITLE
DbSessionTest fails when SQLite is not available.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#11712]
### What steps will reproduce the problem?
Run tests on a system without SQLite
### What is the expected result?
Tests depending on SQLite get skipped, or in case of test just requiring any kind of database, use another one.

### What do you get instead?
Exception / failed tests.

### Additional info

For DbSessionTest i'd like to add a check to see if SQLite is available and if not I'll use `markTestSkipped`.
Alternatively I could implement a fallback, since theoretically DbSessionTest does not require SQLite, it just requries any DB. 

Goal of this bug report is to make the test output less verbose for developers creating PRs ;-)

| Q                | A
| ---------------- | ---
| Yii version      | master
| PHP version      | 5.6
| Operating system | Ubuntu 15.10

**Comment by samdark** [comment]
Makes sense.
