### ISSUE TITLE
I18n migration - tables without prefix

### ISSUE THREAD

**Issue by OndrejVasicek** [yiisoft/yii2#11722]
### What steps will reproduce the problem and what do you get?
Executing `yii migrate --migrationPath=@yii/i18n/migrations/` creates tables without prefix.

### What is the expected result?
Tables with prefix set in common/main-local.php?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.15
| Operating system | Win10

**Comment by arturf** [comment]
this issue can be closed, guys )
