### ISSUE TITLE
Error displayed at production env, yii\web\DbSession, line 184

### ISSUE THREAD

**Issue by pastuhov** [yiisoft/yii2#11726]
### What steps will reproduce the problem?
0. Production 
1. Using ``vendor/yiisoft/yii2/web/DbSession.php``
2. Problem with insert statment (Integrity constraint violation: SQLSTATE[23505]: Unique violation: 7 ERROR)

### What is the expected result?
Error logged to error log (``error_log()``) and NO output to browser (no ``echo()``)

### What do you get instead?
Error displayed

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7.0.7-1
| Operating system | Debian

### Go deeper
1. File ``vendor/yiisoft/yii2/web/DbSession.php``
2. Line 184 ``echo $exception;``
3. Why? :smiley:

**Comment by samdark** [comment]
It's not possible to move any further with the data provided. How to reproduce it?

**Comment by cebe** [comment]
please also provide the stack trace of the error

**Comment by cebe** [comment]
Is your application using on one server or are multiple servers using the same database?

**Comment by deadkrolik** [comment]
I have the same issue. I just want to disable any errors display on production, but can't do it. 

I set YII_DEBUG to false, YII_ENV to prod, created light layout for errors. But can't avoid that message after template is rendered.

**Comment by pastuhov** [comment]
@samdark & @cebe use mater/slave + time lag or ather problem

**Comment by samdark** [comment]
@pastuhov do you have master/slave for sessions?

**Comment by deadkrolik** [comment]
Example to reproduce issue:
1. Add this code to controller's action
```php
\Yii::$app->session->get('azaza');
return;
```
2. Change user name for database connection.
3. Set YII_DEBUG to false
4. Refresh page

You will get the error ```Database Exception: SQLSTATE[42000] [1044] Access denied for user 'X'@'localhost' to database 'Y'``` at the and of page.

Disabling any errors is useful on production server. User shouldn't be able to see such detailed information for security reasons.

**Comment by samdark** [comment]
I cannot reproduce that:

![Error](https://cloud.githubusercontent.com/assets/47294/17137824/eda4caae-5345-11e6-8abf-b555fa48b0d6.png)

**Comment by samdark** [comment]
Ah, indeed it's in the page source.

**Comment by samdark** [comment]
Fixed. Thanks for helping with reproducing it.
