### ISSUE TITLE
Comand builder not return correct results when use HAVING COUNT in sql

### ISSUE THREAD

**Issue by andreipasat** [yiisoft/yii2#11728]
### What steps will reproduce the problem?
I generate a sql query using command builder which looks like that :

```sql
SELECT `p`.*, `p`.`id` AS `p_id`, `c`.`c_name`, `c`.`id` AS `c_id`, `sc`.`sc_name`, `cl`.`cl_url`, `cl`.`cl_company_name`, `cl`.`cl_name`, `cl`.`cl_surname` 
FROM `property` `p` 
JOIN `categories` `c` ON p.p_category_id = c.id 
JOIN `sub_categories` `sc` ON p.p_sub_category_id = sc.id 
JOIN `clients` `cl` ON p.p_client_id = cl.id 
JOIN `property_kitchen_options` `pko` ON p.id = pko.pko_property_id 
WHERE p_status = "active" AND p.p_is_sell = 0 AND cl.cl_not_show_objects = 0 AND p.p_type = 'buy' AND p.p_category_id = 3 
AND pko.pko_kitchen_option_id IN(10,5) 
GROUP BY `p_id` 
HAVING COUNT(pko.pko_property_id) = 2 
ORDER BY `p_show_price` DESC, `p_price` ASC, `p`.`p_add_date` DESC LIMIT 5
```

When I run this sql in phpmyadmin i get right results but when i try to get results in code i get empty array or wrong results.

```php
$results  = $command->queryAll();
```

I tryed to use queryRow(),queryColumn() query() and the same problem.

If I remove HAVING COUNT(pko.pko_property_id) = 2 from sql all work fine

Anyone have ideas how to fix this problem ?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  - 1.1.17
| PHP version      |  - 5.5.12
| Operating system |  - windows 8

**Comment by samdark** [comment]
1.1.17 is 1.x. It should be reported to https://github.com/yiisoft/yii
