### ISSUE TITLE
Enhacement for Query caching

### ISSUE THREAD

**Issue by rtwent** [yiisoft/yii2#11734]
Is it possible to make query caching more simple, like laravell has: 
https://laravel.com/docs/4.2/queries#caching-queries
Just:

> ->remember($minutes)->get()

Instead of closures in controllers (models). 

The advantages of the absence of closures in controllers, as I think is obvious. Remembering in minutes (like laravell does) is not comfortable too (seconds will be the best decision).

The idea of **not an expert**: The injecting of Cache component to DAO or ActiveRecord is a bad idea, Can ActiveRecord use some trait as it does with yii\base\ArrayableTrait (toArray() method), but this trait will respond for caching and will have this closure one time. Instead of repeating closures hundreds of times in application.

THANK YOU

**Comment by samdark** [comment]
> The advantages of the absence of closures in controllers, as I think is obvious. 

Nope. Could you elaborate?

**Comment by Alex-Bond** [comment]
@rtwent @samdark actually this feature was in first version of framework, but it was removed from core in Yii2. If you can return is it will be perfect.

**Comment by rtwent** [comment]
@samdark 
> Instead of repeating closures hundreds of times in application.

That's I think is the main advantage.
Secondary, it is not pretty code. When I hate fat controllers (read it "repeating closures" in it), I have to put closures in model. That's can have an advantage when I reuse such queries in different controllers, but if I want just find something one time only in my application. Such code will be more pretty
`Customer::find()->where(['id' => 1])->remember(3600)->one();`
then:
`$db = \Yii::$app->db;
$result = Customer::getDb()->cache(function ($db) {
    return Customer::find()->where(['id' => 1])->one();
});
`
Finally, I am not sure about amount of memory that will be used with closure and without it. It need to be tested.

Could You explain, why are You so "categorial" defending closures?
Thank You.

**Comment by samdark** [comment]
I'm not really about defending closures. I'm more of against introducing more ways to do the same thing.

> Such code will be more pretty

I'm not sure about it. With `->cache` call it's obvious what happens. In case of `remember()` it isn't.

> Finally, I am not sure about amount of memory that will be used with closure and without it. It need to be tested.

Absolutely. Do you have time for it?

**Comment by rtwent** [comment]
> Absolutely. Do you have time for it?
I'll try to help You, but it will be not fast.

**Comment by SilverFire** [comment]
The issue seems to be abandoned. I'm closing it unless further information provided.
