### ISSUE TITLE
Instead of the table displays the variables of the layout ({pager}{items})

### ISSUE THREAD

**Issue by molleker** [yiisoft/yii2#11731]
The problem appear after moving to a new server. 
For every instance of gridview I get the variables of the layout ({pager}{items}{pager}).

I run requirements.php and all is OK (no warnings, no errors).

 Yii version  2.0.3    
Intl installed (Version 3.0.0)
ICU version 57.1
 PHP version 5.4.45

**Comment by cebe** [comment]
please provide more information about the problem. what do you do, what do you see and what did you expect to see instead?

**Comment by molleker** [comment]
On the old server everything worked. 
Admins moved our site to a new webserver and after that all tables on pages are not displayed. I.e. in place of gridview I see this text: "{pager}{items}{pager}"

**Comment by cebe** [comment]
if it works on one server and not on the other the problem is very likely not inside of yii, but your server environment.
