### ISSUE TITLE
[docs] Conditional validation not available for all validators

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#11747]
### What steps will reproduce the problem?

See the docs: http://www.yiiframework.com/doc-2.0/guide-input-validation.html#conditional-validation
### What is the expected result?

It should exist some information declaring that _"... not all core validators have a `when` param available (e.g. 'safe')..."_
### What do you get instead?

Nothing talking about it. I tried to use an approach like `'when' => Yii::$app->user->can('admin')` in a `safe` validator.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |

**Comment by cebe** [comment]
safe is the only exception as it is not really a validator...

**Comment by slinstj** [comment]
That is one more reason to have that information. To be either a marker or a real validator would not necessarily prevent it to have `when`. It is a simple info that can avoid a bit of wasting of time.
Thanks for mark it like `type: docs`.
