### ISSUE TITLE
pjax form submit with ajax validation is not working

### ISSUE THREAD

**Issue by ceovishnu** [yiisoft/yii2#11746]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | Ubuntu 15.10

**Comment by ceovishnu** [comment]
@samdark is there a pjax issue or ajax valiadtion issue.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/pull/11743

check this code

**Comment by samdark** [comment]
@ceovishnu how to reproduce the issue?

**Comment by nevermnd** [comment]
Same as #11727 i think.

**Comment by samdark** [comment]
OK. Closing as duplicate.

**Comment by derekisbusy** [comment]
#13545 and yiisoft/jquery-pjax/pull/52 fixes this issue.
