### ISSUE TITLE
ENH: Model->load($data, '') return if anything was loaded - now always true

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#11757]
### What steps will reproduce the problem?

```php
class MyForm extends \yii\base\Model {
    public $foo;
    public function rules()
    {
        return [
            ['foo', 'safe'],
        ];
    }
}

$model = new MyForm();
var_dump($model->load(['foo' => 42], ''));
var_dump($model->load(['trash' => 37], ''));
```

### What is the expected result?

```
bool(true)     // yes, anything was loaded
bool(false)    // no, nothing was loaded
```

### What do you get instead?

```
bool(true)
bool(true)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04
| BC break | Behaviour change

**Comment by samdark** [comment]
Sounds like a bug. Need a test case for it.

**Comment by undefinedor** [comment]
$modal->load() will call  $modal->setAttributes(), It's safeOnly default.
```php
   /**
     * Sets the attribute values in a massive way.
     * @param array $values attribute values (name => value) to be assigned to the model.
     * @param boolean $safeOnly whether the assignments should only be done to the safe attributes.
     * A safe attribute is one that is associated with a validation rule in the current [[scenario]].
     * @see safeAttributes()
     * @see attributes()
     */
    public function setAttributes($values, $safeOnly = true)
    {
        if (is_array($values)) {
            $attributes = array_flip($safeOnly ? $this->safeAttributes() : $this->attributes());
            foreach ($values as $name => $value) {
                if (isset($attributes[$name])) {
                    $this->$name = $value;
                } elseif ($safeOnly) {
                    $this->onUnsafeAttribute($name, $value);
                }
            }
        }
    }
```

**Comment by samdark** [comment]
`trash` is unsafe but `true` is returned.

**Comment by klimov-paul** [comment]
From the doc block of `Model::load()`:

> `@return boolean whether load() found the expected form in $data.`

Method `load()` returns `true` in case some form data is present. It indicates the web form was actually submitted no matter with which data.

To be more precise:

```
class MyForm extends \yii\base\Model {
    public $foo;
    public function rules()
    {
        return [
            ['foo', 'safe'],
        ];
    }
}

$model = new MyForm();
var_dump($model->load(['MyForm' => ['foo' => 'anything']])); // outputs `true`
var_dump($model->load(['foo' => 'anything'])); // outputs `false`
```

In case `formName()` is empty - any non empty data will be considered as passed:

```
class MyForm extends \yii\base\Model {
    public $foo;

    public function formName()
    {
        return null;
    }

    public function rules()
    {
        return [
            ['foo', 'safe'],
        ];
    }
}

$model = new MyForm();
var_dump($model->load(['foo' => 'anything'])); // outputs `true`
```

**Comment by klimov-paul** [comment]
I can see no bug here.

**Comment by Vovan-VE** [comment]
There is no problems when loading data from 'formName' sub-array. But empty form name is special case. In this case input data extracted from somewhere in a way which does not matter for subject. I'm sure that I did extract it correctly.

Now I want to handle input array `['field' => 'value', ...]` with a form(s). In my case that array(s) goes from structured JSON input to my API:

```js
{
    "books": [
        {                       // <-- item data
            "field": "value",
            ...
        },
        ...   // <-- more items
    ],
    ... // <-- another types of items
}
```

In a specific case I want to handle item data with different unrelated forms sequentally to do unrelated stuff. So, I pass same data to `Model::load()` for different forms:

```php
$item_data = ['foo' => 42, 'bar' => 37]; // $input[$type][$i]
if ($foo_form->load($item_data, '')) {
    ...
}
if ($bar_form->load($item_data, '')) {
    ...
}
```

I extected `Model::load()` does what I need, but it's not. Currently there is no ability to check if a form was changed by the input or not (like dirty attributes in AR).

**Comment by cebe** [comment]
> In a specific case I want to handle item data with different unrelated forms sequentally to do unrelated stuff. So, I pass same data to Model::load() for different forms:

if the forms are unrelated, why is their data in the same array?

What you describe is different functionality than what load() is supposed to do so you should not use load() for it.
