### ISSUE TITLE
Mysql longtext in migration

### ISSUE THREAD

**Issue by rmrevin** [yiisoft/yii2#11764]
### What steps will reproduce the problem?
Create and execute migration with mysql driver
```php
$this->createTable('test_longtext', [
    'id' => $this->primaryKey(),
    'content' => $this->longText(),
]);
```

### What is the expected result?
Must create a table with a field type `LONGTEXT`.

### What do you get instead?
Exception `PHP Notice 'yii\base\ErrorException' with message 'Undefined index: LONGTEXT'`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.20
| Operating system | Debian

### Fix
In class `yii\db\ColumnSchemaBuilder` replace string 366
from
```php
return $this->categoryMap[$this->type];
```
to
```php
return isset($this->categoryMap[$this->type]) ? $this->categoryMap[$this->type] : $this->type;
```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchemaBuilder.php#L411

**Comment by iamwebdesigner** [comment]
@samdark can you tell how to create long text or medium text in this case? I cannot find any documentation on this.

**Comment by samdark** [comment]
Specify type explicitly.

**Comment by iamwebdesigner** [comment]
can you give an example on how to do it, please? I am stuck here and cannot find any in docs.

**Comment by samdark** [comment]
```
'text' => 'mediumtext',
```

**Comment by iamwebdesigner** [comment]
So I have checked out the yii2 project source code related to this issue and made a workaround for others facing the same issue.
- Create a new trait in a separate file with this content:
```php
trait TextTypesTrait
{
    /**
     * @return \yii\db\Connection the database connection to be used for schema building.
    	 */
	    protected abstract function getDb();
       /**
        * Creates a text column.
        * @return ColumnSchemaBuilder the column instance which can be further customized.
        * @since 2.0.6
        */
    	public function mediumText()
    	{
         		return $this->getDb()->getSchema()->createColumnSchemaBuilder('mediumtext');
    	}

    	public function longText()
    	{
		         return $this->getDb()->getSchema()->createColumnSchemaBuilder('longtext');
	    }
}
```
- Include this trait inside the class you want a `meduimtext` or `longtext` type:
```php
class m... extends Migration
{
    // depends on where you create the trait. I have created it inside project files 'helpers' folder
    use app\helpers\TextTypesTrait;
    ...
}
```
- Use methods `mediumText()` and `longText()` where necessary:
```php
   'mediumtextattribute' => $this->mediumText(),
```

**Comment by zzpwestlife** [comment]
@iamawebgeek Thanks. That helps a lot.

**Comment by faizanktk** [comment]
@samdark how can i use it like this
'content' => $this->longText(),

**Comment by jmone** [comment]
$this->createTable('test_longtext', [
    'id' => $this->primaryKey(),
    'content' => $this->text(),
]);
**$this->alterColumn('test_longtext', 'content', 'LONGTEXT');**

method longText() not exists, you can alter column as the example.
