### ISSUE TITLE
pjax form in modal submit problem , request url many time

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#11761]
I create a bootstrap modal , the modal content loaded from a pjax page.
The pjax page is ActiveFom and set 'data-pjax' => true.

If I open 2 times modal ( open the modal , and close modal , then reopen the modal )
Then I submit form (in modal) , it will request url 2 times .

I think this bug  is ActiveForm echo this javascript.

``` javascript
jQuery(document).on('submit', "#my-container-id form[data-pjax]", function ...
```

Thats why I open  modal 2 times, it will submit 2 times.

So I put the code before <?php Pjax::begin(); ?> to fixed it

``` javascript
<script>
jQuery(document).off('submit', "#my-container-id form[data-pjax]");
</script>
```

I hope ActiveForm can fixed the problem automatic. Is it possible ?
### Additional info

Yii version : 2.0.8

**Comment by edgardmessias** [comment]
I have the same problem

**Comment by dynasource** [comment]
your usecase is too vague and specific to properly support. If you are able to show your code with proof that this is really a Yii problem, Ill reopen it again. Thanks!

**Comment by derekisbusy** [comment]
#13545 and yiisoft/jquery-pjax/pull/52 fixes this issue.
