### ISSUE TITLE
Yii2 Mongodb relational searching is not working

### ISSUE THREAD

**Issue by mohitkadelongraph** [yiisoft/yii2#11763]
### What steps will reproduce the problem?

I am trying to do a relational search like - users and orders collections in mongo db.
I have referenced user_id in orders collection and wrote below code:
```
// In OrderSearch Model
public function search($params){
    ...
    $query->with(['user']); // for related document
    ...
    ...
    $query->andFilterWhere(['like', 'user.email', $this->email]);
}

// In Order Model
public function getUser(){
    return $this->hasOne(User::className(), ['_id' => 'user_id']);
}
```

### What is the expected result?
No Result Found! Nothing happened.

### What do you get instead?
It should search with relational data. Like if I enter an email it should give me all orders for that email.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2
| PHP version      | 5.5.9
| Operating system | Ubuntu

**Comment by cebe** [comment]
mongodb does not support joins so you can not make a search query in this way. also `with` does only load the related data after the search result has been returned from mongodb. what your query checks is whether the `user.email` attribute on the OrderSearch model contains the email.

**Comment by BenasPaulikas** [comment]
@mohitkadelongraph if you use grid view you can add SELECT2 to that column and search users by email via yii action and then return user._id and then do andFilterWhere(['user_id' => $this->user_id])
