### ISSUE TITLE
URL Not Found when using action camel case and params

### ISSUE THREAD

**Issue by rfiedler** [yiisoft/yii2#11766]
**### What steps will reproduce the problem?**

Controller :  **ReportsController**
Action : **actionTecnicalReport($id)**
Try Access url :  **reports/tecnical-report/1**

**### What is the expected result?**

Accessing the page

**### What do you get instead?**

Not Found 404

**### Additional info**

if i remove param ($id) the url **works**  
Controller :  **ReportsController**
Action : **actionTecnicalReport**
url :  **reports/tecnical-report**

> 'urlManager' => [
>             'class' => 'yii\web\UrlManager',
>             'showScriptName' => false,
>             'enablePrettyUrl' => true,
>             'rules' => array(
>                 '\<controller:\w+\>/\<id:\d+\>' => '\<controller\>/view',
>                 '\<controller:\w+\>/\<action:\w+\>/<id:\d+>' => '\<controller\>/\<action\>',
>                 '\<controller:\w+\>/\<action:\w+\>' => '\<controller\>/\<action\>',
>             ),
>         ],

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5 July 11, 2015
| PHP version      | 5.5.9
| Operating system | ubuntu 4.13

**Comment by rob006** [comment]
>  `'<controller:\w+>/<action:\w+>/id:d+' => '<controller>/<action>',`

Did you try:
` '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',`
?

**Comment by lynicidn** [comment]
[\w-]+

**Comment by lynicidn** [comment]
https://regex101.com/r/nN6uI5/1

**Comment by lynicidn** [comment]
you do as https://regex101.com/r/nN6uI5/2

**Comment by rfiedler** [comment]
Tks !!   It works !


'urlManager' => [
          'class' => 'yii\web\UrlManager',
'showScriptName' => false,
'enablePrettyUrl' => true,
'rules' => array(
'\<controller:\w+\>/\<id:\d+\>' => '\<controller\>/view',
'\<controller:\w+\>/\<action**:[\w-]+**\>/\<id:d+\>' => '\<controller\>/\<action\>',
'\<controller:\w+\>/\<action:\w+\>' => '\<controller\>/\<action\>',
),
],


I think that if yii2 developers have developed friendly url with traces  (controller/action-with-trace) have also developed the default  urlmanager  configuration

**Comment by cebe** [comment]
> I think that if yii2 developers have developed friendly url with traces (controller/action-with-trace) have also developed the default urlmanager configuration

where did you find the default configuration without `-`? it is correct in the docs here: http://www.yiiframework.com/doc-2.0/yii-web-urlmanager.html#$rules-detail

**Comment by rfiedler** [comment]
Possibly an old documentation when the Yii version was 2.0.5
(Now its up-to-date and works fine ! )

Tks
