### ISSUE TITLE
Problem About ControllerMap

### ISSUE THREAD

**Issue by undefinedor** [yiisoft/yii2#11762]
### What steps will reproduce the problem?
As http://www.yiiframework.com/doc-2.0/guide-structure-applications.html say

controllerMap
This property allows you to map a controller ID to an arbitrary controller class. By default, Yii maps controller IDs to controller classes based on a convention (e.g. the ID post would be mapped to app\controllers\PostController). By configuring this property, you can break the convention for specific controllers. In the following example, account will be mapped to app\controllers\UserController, while article will be mapped to app\controllers\PostController.

```php
[
    'controllerMap' => [
        [
            'account' => 'app\controllers\UserController',
            'article' => [
                'class' => 'app\controllers\PostController',
                'enableCsrfValidation' => false,
            ],
        ],
    ],
]
```

### What is the expected result?

200 OK

### What do you get instead?

404 NOT FOUND

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 7.0
| Operating system | Windows

The related code about ControllerMap - \yii\base\Module line:505
```php
        // module and controller map take precedence
        if (isset($this->controllerMap[$id])) {
            $controller = Yii::createObject($this->controllerMap[$id], [$id, $this]);
            return [$controller, $route];
        }
```
This code means  I should config this property like following:
``` php
[
    'controllerMap' => [
        'account' => 'app\controllers\UserController',
        'article' => [
                'class' => 'app\controllers\PostController',
                'enableCsrfValidation' => false,
            ],
        ],
]
```

So...How to config is right?

**Comment by mdmunir** [comment]
you use extra array.

**Comment by cebe** [comment]
@undefinedor yes, there is an extra array inside the configuration array, this would be correct:

```
[
    'controllerMap' => [
            'account' => 'app\controllers\UserController',
            'article' => [
                'class' => 'app\controllers\PostController',
                'enableCsrfValidation' => false,
            ],
    ],
]
```

**Comment by undefinedor** [comment]
@cebe  http://www.yiiframework.com/doc-2.0/guide-structure-applications.html  show the wrong usage. Could you update it ?

**Comment by cebe** [comment]
oh, yes sure.

**Comment by cebe** [comment]
done. thanks for reporting!
