### ISSUE TITLE
Unable to check if component property isset or empty

### ISSUE THREAD

**Issue by vasiluy-kondr** [yiisoft/yii2#11771]
### What steps will reproduce the problem?

There is small test

``` php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');

$config = [
    'id' => 'app',
    'basePath' => dirname(__DIR__),
    'components' => [
        'captcha' => [
            'name' => 'foo bar',
            'class' => 'yii\captcha\Captcha',
        ],
    ],
];

$application = new yii\web\Application($config);
echo '<plaintext>';
echo implode(', ', [
    isset(Yii::$app->captcha->name) ? 'set' : 'not set',
    empty(Yii::$app->captcha->name) ? 'empty' : 'not empty',
    'value: ' . Yii::$app->captcha->name,
    isset(Yii::$app->captcha->name) ? 'set' : 'not set',
    empty(Yii::$app->captcha->name) ? 'empty' : 'not empty',
]);
```
### What is the expected result?

`set, not empty, value: foo bar, set, not empty`
### What do you get instead?

`not set, empty, value: foo bar, set, not empty`
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |
| PHP version | 7.0.7 |
| Operating system | Windows 10 |

**Comment by cebe** [comment]
this seems to fail only on php 7: https://travis-ci.org/yiisoft/yii2/builds/138698808

**Comment by vasiluy-kondr** [comment]
At the moment the issue is only breaking reCaptcha extension, but I've already put temporary workaround into my index.php
```php
if (PHP_MAJOR_VERSION === 7) {
    Yii::$app->reCaptcha->secret;
}
```

**Comment by georaldc** [comment]
Might be related to this:

https://bugs.php.net/bug.php?id=69659

It looks like running isset over a property that needs to go through __get forces the __isset magic method to be called first on the ServiceLocator class (it used to be __get() followed by __isset(). Tested with 7.0.4, before this bug was noticed by the PHP team and I'm able to get the test by @cebe to pass).

**Comment by cebe** [comment]
This is a BC break in PHP: https://3v4l.org/jEUfg

**Comment by cebe** [comment]
in the PHP bug [69659](https://bugs.php.net/bug.php?id=69659), nikic wrote:

> For reference, the way to fix any issues with this change is to make sure your __isset() or 
> offsetExists() functions behave correctly. If this change causes issues with your code, it indicates that 
> you already have a broken __isset/offsetExists implementation, but it's brokenness did not 
> previously surface (one bug canceling another...)

this means the semantics of `__isset()` in yii's service locator component are questionable.
it will return true only if the component is already loaded, even though `__get()` would load it afterwards if it will be called. Fixing this would need a BC break however it seems like a reasonable fix to me even for 2.0.x. @yiisoft/core-developers opinions?

**Comment by klimov-paul** [comment]
I vote for the fix: `__get()` and `__isset()` should be consistent.

**Comment by samdark** [comment]
I'm for fixing it but we should measure before/after performance and take a good look at tests we have...

**Comment by klimov-paul** [comment]
> we should measure before/after performance

In normal flow performance will not be affected. Framework does not ever call `isset()` over `ServiceLocator`. Only custom developer code may be affected.

**Comment by cebe** [comment]
the only difference will be one more call to isset() inside of `__isset()` there should not be any change in performance.
