### ISSUE TITLE
osx 10.11.5中文乱码（使用ArrayDataProvider乱码，使用ActiveDataProvider并没有乱码）

### ISSUE THREAD

**Issue by liufee** [yiisoft/yii2#11770]
### What steps will reproduce the problem?
使用ArrayDataProvider然后渲染模版，部分中文乱码，部分中文不会乱码
使用ActiveDataProvider中文都没有乱码
以上情况都是在osx下会发生，在linux下都不会乱码
### What is the expected result?
正常显示中文
### What do you get instead?
。。。

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.6   2.0.7   2.0.8
| PHP version      |   5.5    7
| Operating system |  osx 10.11.5  升级osx之前也是这样

**Comment by sidgwick** [comment]
哥们, 你的编码问题吧. 还有这里允许使用中文提问么?
