### ISSUE TITLE
TimestampBehavior, not updating the "updated_at" if updated_at has already some value

### ISSUE THREAD

**Issue by zeevy** [yiisoft/yii2#11778]
### What steps will reproduce the problem?
In Model
<pre>
<code>
    public function behaviors() {
        return ArrayHelper::merge(parent::behaviors(), [
            ['class' => TimestampBehavior::className()],
        ]);
    }
</code>
</pre>
In Controller
<pre>
<code>
           $model = $this->findModel($id); // which returns the model object
           if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
</code>
</pre>
### What is the expected result?
$model->updated_at value updated with current unix timestamp

### What do you get instead?
$model->updated_at value not updated, it still have the old vlaue

### Additional info

| Q                | A
| ---------------- | ---
| Yii version    |   2.0.8
| PHP version      | 5.6.16
| Operating system  | Windows 10 - Apache2

**Comment by samdark** [comment]
Were model attributes updated? If the form data submitted is the same as model data, attributes won't be saved and behavior won't be triggered.

**Comment by zeevy** [comment]
ya your are correct, its not triggered because of the same data submitted.
thanks.
