### ISSUE TITLE
yii.js breaking AJAX requests?

### ISSUE THREAD

**Issue by iadj** [yiisoft/yii2#11773]
When a request is made using `$.getJSON`, the web page redirects to the requested URL because of the yii.js `initRedirectHandler` function. Oddly everything works fine in localhost and the redirect only happens in production.

```
    function initRedirectHandler() {
        // handle AJAX redirection
        $(document).ajaxComplete(function (event, xhr, settings) {
            var url = xhr && xhr.getResponseHeader('X-Redirect');
            if (url) {
                window.location = url;
            }
        });
    }
```

**Comment by lynicidn** [comment]
window.location = true|false

**Comment by iadj** [comment]
@lynicidn The function in the OP is the function from `yii.js`. The `url` var appears to be the actual URL being requested by AJAX in `window.location`.

**Comment by lynicidn** [comment]
yes, this bug https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L327

**Comment by iadj** [comment]
The issue I'm experiencing appears to be related to something else. Haven't figured out what yet.
