### ISSUE TITLE
git ignore bring many matters

### ISSUE THREAD

**Issue by FataliBud** [yiisoft/yii2#11779]
### The description of the problem 

Since the 2.0.8 version of yii2 ,due to the .gitignore file join to the "index.php", "index-test.php" and "/yii",etc, the installation of the yii2 is not complete.
In particular, the `yii` command file is ignored, it's not  friendly for the new developer.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | OS X

**Comment by samdark** [comment]
If you're talking about advanced application template, you need to run `./init`. That's in the docs.

**Comment by FataliBud** [comment]
thanks！
