### ISSUE TITLE
Run action from another & params

### ISSUE THREAD

**Issue by talovicnedim** [yiisoft/yii2#11785]
I want to run console action from another one. 

This is how my code looks like:

` Yii::$app->runAction('math/calculate', ['id' => 123]);`

Error:

`Unknown option: --id`

As I can see from the docs, 2nd parameter is an array.

**Comment by samdark** [comment]
There's no clean way to do it currently. In one of my extensions I'm doing it like https://github.com/samdark/yii2-webshell/blob/master/controllers/DefaultController.php#L67.

I think there should be more direct way doing that which is to be wrapped into nice API.

**Comment by cebe** [comment]
please show your action definition, the call should work as you do it.

**Comment by talovicnedim** [comment]
This is how my code looks:

namespace console\controllers;

use Yii;
use yii\console\Controller;

```
class ScheduleController extends Controller {
     public function actionIndex(){

           Yii::$app->runAction('math/calculate', ['id' => 123]); 
 
     }
}
```
Reponse:

`Error: Unknown option: --id`

However, I took @samdark's code and it works.

**Comment by samdark** [comment]
Well, my code is kinda hacky.

**Comment by cebe** [comment]
I mean the action you want to call. MathController::actionCalculate()

**Comment by talovicnedim** [comment]
OK. Here's my code:

```
namespace console\controllers;

use yii\console\Controller;

class MathController extends Controller {

    public function actionCalculate($id) {
            return 3+2;
    }

}

```

I've simplified my code. However, it doesn't work.

**Comment by cebe** [comment]
call should be `           Yii::$app->runAction('math/calculate', [123]); ` instead then.

**Comment by wigginskuang** [comment]
> call should be `Yii::$app->runAction('math/calculate', [123]);` instead then.

it works
