### ISSUE TITLE
How to delete an installed extension?

### ISSUE THREAD

**Issue by nishadotcom** [yiisoft/yii2#11786]
How to delete an installed extension from my source????

Ex.
I installed yii-social extension.

I do not want it. I want to remove it.

How can I do that????

Best
nishadotcom

**Comment by agungsijawir** [comment]
If you use composer to install that extension, remove from composer.json and perform composer update.
If no, delete manually from vendor folder.

Please close this issue and use form / irc to ask such question, this is bug tracking system btw.

**Comment by nishadotcom** [comment]
Thank You
