### ISSUE TITLE
 requires two operands error, when \yii\db\Expression used  in `OR` where statement

### ISSUE THREAD

**Issue by sahifedp** [yiisoft/yii2#11782]
Hi
I want use \yii\db\Expression with OR , but I get Operator '...' requires two operands , on /yiisoft/yii2/db/QueryBuilder.php line 1381.
my code:

           $query = model::find();
           $condition = 'EXISTS (....)';
           $query->andWhere([
                'OR',
                ['t.user_id' => 10],
                [new \yii\db\Expression($condition)],
            ]);

I changed my a algorithm  and got result. but I think top algorithm Must have worked.

**Comment by sahifedp** [comment]
I'm sorry.
I removed `[,]` fro befor and after `new \yii\db\Expression($condition)` , and worked.
thanks

**Comment by Gsubha** [comment]
we can also use
 $query = model::find();
$query->andWhere([ 'OR', "{$this->tblName}.order_status_id!= 3 and {$this->tblName}.order_status_id!= 1"])
