### ISSUE TITLE
Автоматическое преобразования типа, возможно ли?

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#11799]
### What steps will reproduce the problem?
Имеем некую модель производную от ActiveRecords. Назовем объект от модели как $this. У модели имеются следующий фильтры
```PHP
public function rules()
{
    return [
        [['filter_duration_id', 'filter_hotel_id'], 'integer'],
    ];
}
```

В эту модель пришли данные из POST (ВАЖНО в примере типы данных сохранены, пришли строки!!!)
```PHP

$this->load(['filter_duration_id'=>'1', 'filter_duration_id'=>'2'], '');
$this->validate();
$this->save();

// далее производим следующую операцию... 
$indexCommon = IndexCommon::findOne($this->id); // эта модель существует, связь 1 к 1
// из БД грузятся следующие данные filter_duration_id = 1, filter_hotel_id = 2 (типы сохранены!!! это integer)
$indexCommon->attributes = [
    'filter_duration_id' => $this->filter_duration_id,
    'filter_hotel_id' => $this->filter_hotel_id,
];

$indexCommon->save(false); // произойдет обновление записи!

// $indexCommon->save(true) // тоже типы не преобразуютя
```

### What is the expected result?
Обновление записи $indexCommon не требуется согласно коду
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L717
Должна срабатывать оптимизация!

### What do you get instead?
Вижу, что сохранение происходит

### Additional info
Это происходит так как фреймворк детектирует изменение значения через метод getDirtyAttributes. Формально изменился только тип. Фактически значение не изменилось.

### Что я предлагаю?
(Этот вариант лучше!) Может как-то автоматически присваивать тип, если есть соотвествующий фильтр?
Может быть исправить работу детектора getDirtyAttributes?

### Workaround
```PHP
$indexCommon->attributes = [
    'filter_duration_id' => (int) $this->filter_duration_id,
    'filter_hotel_id' => (int) $this->filter_hotel_id,
];
$indexCommon->save(false); // обновления не будет!
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.22
| Operating system | Windows 7 x64 Sp1

**Comment by klimov-paul** [comment]
Duplicates #8619
