### ISSUE TITLE
RBAC with two permissions that have rules

### ISSUE THREAD

**Issue by drutalj** [yiisoft/yii2#11790]
### What steps will reproduce the problem?

I have this RBAC configuration:

```php
$rule1 = new \app\rbac\Rule1;
$auth->add($rule1);

$rule2 = new \app\rbac\Rule2;
$auth->add($rule2);

$permission1 = $auth->createPermission('permission1');
$permission1->ruleName = $rule1->name;
$auth->add($permission1);

$permission2 = $auth->createPermission('permission2');
$permission2->ruleName = $rule2->name;
$auth->add($permission2);

$auth->addChild($permission1, $permission2);
```

If rule2 fails one should expect permission1 (with rule1) to be checked.

Now, the behavior is: if permission2 fails in rule2 parent permission won't be checked at all.

Otherwise I still have to manually check every level in the permission chain.

The problem is in function `checkAccessRecursive` in class `DbManager`:

```php
if (!$this->executeRule($user, $item, $params)) {
   return false;
}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Can you provide whole hierarchy including user assignment plus call to check access?

**Comment by drutalj** [comment]
This is my hierarchy:

```php
$auth = Yii::$app->authManager;

$rule1 = new Rule1Rule();
$auth->add($rule1);

$rule2 = new Rule2Rule();
$auth->add($rule2);

$permission1 = $auth->createPermission('permission1');
$permission1->ruleName = $rule1->name;
$auth->add($permission1);

$permission2 = $auth->createPermission('permission2');
$permission2->ruleName = $rule2->name;
$auth->add($permission2);

$auth->addChild($permission1, $permission2);

$role1 = $auth->createRole('role1');
$auth->add($role1);

$auth->addChild($role1, $permission1);

$auth->assign($role1, 1);
```

These are rules:
```php
class Rule1Rule extends Rule
{
    public $name = 'rule1';
    
    public function execute($user, $item, $params)
    {
        echo "Rule1<br>";
        return true;
    }
}
```

```php
class Rule2Rule extends Rule
{
    public $name = 'rule2';

    public function execute($user, $item, $params)
    {
        echo "Rule2<br>";
        return false;
    }
}
```

And this is my call:

```php
var_dump(\Yii::$app->user->can('permission1'));
echo "<br>--------<br>";
var_dump(\Yii::$app->user->can('permission2'));
```
that outputs:
```
Rule1
bool(true) 
--------
Rule2
bool(false)
```
If the rule2 returns false, the check stops and I think it shouldn't because in this case it should check the parent permission.

When I remove `rule2` from `permission2`, the output is:
```
Rule1
bool(true)
--------
Rule1
bool(true)
```

**Comment by samdark** [comment]
It works as expected. Here's your hierarchy.

![rbac](https://cloud.githubusercontent.com/assets/47294/16210949/69414f2c-3747-11e6-99f8-5eff021b9dbc.png)

We need to get from what's checked to the user's role. So:

```php
\Yii::$app->user->can('permission1');
```

Permission1 (true) → Rule 1 (true) → Role 1 (true).

```php
\Yii::$app->user->can('permission2');
```

Permission 2 (true) → Rule 2 (false, makes no sense to check further) → Permission1 → Rule 1 → Role 1.
