### ISSUE TITLE
yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no matching package found.

### ISSUE THREAD

**Issue by ak868308** [yiisoft/yii2#11794]
Unable to install any extension every time composer shows such error
![img_21062016_183658](https://cloud.githubusercontent.com/assets/7982249/16230755/b126fc30-37e0-11e6-9b4c-fc22a44543f0.png)

please help
Thanks in advance

**Comment by cebe** [comment]
you need to update `yiisoft/yii2-composer` to 2.0.4 or downgrade your composer version.

**Comment by ak868308** [comment]
How to downgrade ?

**Comment by ak868308** [comment]
![com_2](https://cloud.githubusercontent.com/assets/7982249/16233377/c112a828-37eb-11e6-9579-a31ca492fdb3.PNG)

**Comment by cebe** [comment]
thats okay to show up on this call. did it solve the problem?

**Comment by ak868308** [comment]
Yes thanks lot
