### ISSUE TITLE
Mobi filetype upload failure

### ISSUE THREAD

**Issue by cleippi** [yiisoft/yii2#11795]
### What steps will reproduce the problem?

Creating a file input type with extension mobi, such as:

```
public function rules()
    {
        return [
            [['mobiFile'], 'file', 'extensions' => 'mobi'],
            [['epubFile'], 'file', 'extensions' => 'epub'],
            [['pdfFile'], 'file', 'extensions' => 'pdf'],
        ];
    }
```

Then going and uploading a file with extension mobi. epub and pdf work just fine.

### What is the expected result?

The file should upload without any error

### What do you get instead?

An error message:

> Only files with these extensions are allowed: mobi.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.15
| Operating system | Windows 8.1

I also checked in the mimetypes and mobi is there, so I'm not sure why this is not working.
https://github.com/yiisoft/yii2/blob/master/framework/helpers/mimeTypes.php

Using a rule such as the following solves the problem, but from what I've read this sounds like it might introduce security vulnerabilities so I'm weary to leave it this way

`[['mobiFile'], 'file', 'extensions' => 'mobi', 'checkExtensionByMimeType' => false],`

**Comment by samdark** [comment]
I guess it can't determine mime type properly... Can you dig into it a bit further?

**Comment by cleippi** [comment]
Sure, is there anything specific you need?

**Comment by samdark** [comment]
A file you're trying to upload would be good.

**Comment by samdark** [comment]
Also make sure you have `application/x-mobipocket-ebook` in the list of your mime types.

**Comment by cleippi** [comment]
Here's an example file (had to zip it because mobi upload isn't supported):
[mobi example.zip](https://github.com/yiisoft/yii2/files/328413/mobi.example.zip)

Also, as for the list of mime types, is this the one?
https://github.com/yiisoft/yii2/blob/master/framework/helpers/mimeTypes.php
If so, then it should be there because my local file is the same.

**Comment by georaldc** [comment]
It looks like native php functions cannot parse out the mime type for mobi files. PHP returns it's fallback value of "application/octet-stream" if it cannot determine the mime type for a file.

**Comment by agungsijawir** [comment]
I had same issue and must set `checkExtensionByMimeType` to false to make it work.

Btw, I got this result,
```php
    var_dump(FileHelper::getMimeTypeByExtension($filename));
    var_dump(FileHelper::getMimeType($filename, null, false));
    var_dump(FileHelper::getExtensionsByMimeType('application/x-mobipocket-ebook'));
```
output
```
string(30) "application/x-mobipocket-ebook"
string(24) "application/octet-stream"
array(2) {
  [0]=>
  string(4) "mobi"
  [1]=>
  string(3) "prc"
}
```

Seems here https://github.com/yiisoft/yii2/blob/master/framework/validators/FileValidator.php#L363 return false, even though extension exists on $extensionsByMimeType from previous line. 

php: 5.5.59

**Comment by georaldc** [comment]
@agungsijawir it fails because "application/octet-stream" is what gets passed to FileHelper::getExtensionsByMimeType(), which then gives back an array that does not contain "mobi"

**Comment by samdark** [comment]
We're relying on `fileinfo` PHP extension to determine mime type which seems to fail on "mobi" files. Since definition is already there, we have no way to affect this behavior.

**Comment by cleippi** [comment]
Okay, so is this the best option for me then? 

`[['mobiFile'], 'file', 'extensions' => 'mobi', 'checkExtensionByMimeType' => false],`

**Comment by samdark** [comment]
Seems so. If you'll find a better way, tell us.
