### ISSUE TITLE
Yii 2.0.8 can not get user data when attribute without 'require'

### ISSUE THREAD

**Issue by bubifengyun** [yiisoft/yii2#11802]
### What steps will reproduce the problem?

In the beginning, i use 2.0.6, the id was set auto-increase in MySQL, so I can see the Model Class, which is generated by gii, id is not setted 'require'. In the form, I can set id directly, if save, the model will update its id.

### What is the expected result?

When i use `composer update`, the Yii version goes from `2.0.6` to `2.0.7`, `2.0.8`. But one day, i test my website, I find that I cannot update my id.

### What do you get instead?

I hope, in the Model class, without set `require`, the attribute can be updated from the form.

### Additional info

Thank you.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 5.6.15
| Operating system | Windows 7, and Linux Deepin 15.2 64bit

**Comment by mdmunir** [comment]
> I hope, in the Model class, without set `require`, the attribute can be updated from the form.

Yes. You can use `safe` instead of `require`.

**Comment by bubifengyun** [comment]
Thank you very much. I find the problem in my situation as follows,

I add new item in MySQL as `can be null`. but the new Item can not be setted in the yii2, so i add `required` for the new item in `rules` function. But i want to reset `id` isolated, it failure. So I debug, find that the error is new item null. I change the `required` to `safe`, it works well. Thank you.
