### ISSUE TITLE
Question: Planed release date 2.1

### ISSUE THREAD

**Issue by wetzesa** [yiisoft/yii2#11806]
We planning releases for our applications a long time before the development start. For future upgrades and new development project it is necessary to now when the release 2.1 is planned.

**Comment by samdark** [comment]
No date is decided yet.

**Comment by rubenjleon** [comment]
When there is an update to the framework, where will it be announced?

**Comment by wetzesa** [comment]
Is it planned as the next release after 2.0.9 or will the patch version going to double digit like 2.0.10 or 2.0.11?

**Comment by samdark** [comment]
@rubenjleon Official website news.

@wetzesa both 2.0.10 and 2.1.0 are to be released.

Closing the issue since it's more of a question.
