### ISSUE TITLE
urlManager rules

### ISSUE THREAD

**Issue by talovicnedim** [yiisoft/yii2#11801]
HI everyone,

I've created an A record on my DNS server that points to the specific IP address. 

When I open _app.example.com_ everything looks perfect - except URLs.

```

 'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
	    'suffix' => '/',
            'rules' => [
                'http://app.example.com/<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',                
                'http://app.example.com/<controller:\w+>/<action:\w+>' => '<controller>/<action>', 
            ]
],
```

Links are almost okay except one thing. It adds slashes that are not needed.

For an example, my link looks like this:

http://app.example.com//site/index/
http://app.example.com//site/about/

I've tried almost everything and I cannot fix this issue.

**Comment by talovicnedim** [comment]
Why did you label it as a question since after I've copied a piece of code (with small modification) from the documentation it results with a buggy link?

http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#rules-with-server-names

From the docs:

```

[
    'http://admin.example.com/login' => 'admin/user/login',
    'http://www.example.com/login' => 'site/login',
]
```

Small modification:

```
[
    'http://app.example.com/login' => 'site/login',
]
```
    
and the result:

`<a href="http://app.example.com//login/">Login</a>`

As you can see there are two slashes.

**Comment by cebe** [comment]
unable to reproduce, added a unit test: 9cac131
