### ISSUE TITLE
Add Hint Index in queries with join relations

### ISSUE THREAD

**Issue by fdezmc** [yiisoft/yii2#11807]
Hi, 
the use of Expression don't work to hint index with activeRecord in joins with relations.

```
// works!!!
$query = (new Query)->from([new Expression('{{%user}} USE INDEX (primary)')]);

// joinWith relation fails
$query = (new Query)->from([new Expression('{{%user}} USE INDEX (primary)')])
->joinWith('userProfile');
```

Note: userProfile is a relation between user and profile ON user.id = profile.user_id

ActiveQuery class method joinWithRelation takes as $parentAlias an expression resulting in:

SELECT \* FROM `user` USE INDEX (primary) LEFT JOIN `profile` ON `user` USE INDEX (primary).`id` = `profile`.`user_id`

instead of 

SELECT \* FROM `user` USE INDEX (primary) LEFT JOIN `profile` ON `user`.`id` = `profile`.`user_id`

Related issue: [Add Hint Index in queries](https://github.com/yiisoft/yii2/issues/10869)

**Comment by pstddc** [comment]
try:
```php
// joinWith relation fails
$query = (new Query)->from(['userAlias' => new Expression('{{%user}} USE INDEX (primary)')])
->joinWith('userProfile');
```

**Comment by pstddc** [comment]
allow set from as 
- array [alias => expression|tablename]
- string 'tablename'

this incorrect ['tablename']

**Comment by fdezmc** [comment]
Hi @pstddc, 

```
// joinWith relation fails
$query = (new Query)->from(['userAlias' => new Expression('{{%user}} USE INDEX (primary)')])
->joinWith('userProfile');
```

expected:
SELECT `userAlias`.* FROM `user` `userAlias` USE INDEX (primary) LEFT JOIN `profile` ON `userAlias`.`id` = `profile`.`user_id`

get error:
SELECT `userAlias`.* FROM `user` USE INDEX (primary) `userAlias` LEFT JOIN `profile` ON `userAlias`.`id` = `profile`.`user_id`

**Comment by fdezmc** [comment]
Long time ago I open a issue #10869 in order to Add Hint Index in queries. I did a pull request to solve this. 
@cebe point out a way to do this with existing methods using Expression: 

```
// your first example:
$query = (new Query)->from([new Expression('{{%user}} USE INDEX (primary)')]);
// your second example
$query = (new Query)
       ->from([new Expression('`user` `t` FORCE INDEX (primary) IGNORE INDEX FOR ORDER BY (i1)')])
       ->leftJoin(['p' => 'profile'], 'user.id = profile.user_id USE INDEX (i2)');

```
so I remove the pull request. 
This approach don't work in queries with join relations as I explain above:

```
// joinWith relation fails
$query = (new Query)->from([new Expression('{{%user}} USE INDEX (primary)')])
->joinWith('userProfile');
```
get error:
SELECT * FROM user USE INDEX (primary) LEFT JOIN profile ON user USE INDEX (primary).id = profile.user_id

@pstddc approach don't work too:

```
// joinWith relation fails
$query = (new Query)->from(['userAlias' => new Expression('{{%user}} USE INDEX (primary)')])
->joinWith('userProfile');

```
get error:
SELECT userAlias.* FROM user USE INDEX (primary) userAlias LEFT JOIN profile ON userAlias.id = profile.user_id

I am overwriting quoteTableNames method on db/mysql/QueryBuilder.php to re-build the alias, tableName and hint index, but I feel it is like a hack, changing general code to allow a specific functionality.
From my point of view, an approach like the one in #10872 is better since it's face a specific task, its cleaner and it is more readable. But I would like your opinions about it.

**Comment by pstddc** [comment]
what is error ? you can put log?

**Comment by fdezmc** [comment]
The from alias should be just after the table name -> FROM user userAlias USE INDEX (primary)

**Comment by fdezmc** [comment]
May be should to take a look at [http://dev.mysql.com/doc/refman/5.7/en/index-hints.html](http://dev.mysql.com/doc/refman/5.7/en/index-hints.html)

**Comment by nsanden** [comment]
Find myself needing this today

**Comment by dynasource** [comment]
closed in favor of https://github.com/yiisoft/yii2/issues/10869
