### ISSUE TITLE
Change andWhere to andFilterWhere in ExistValidator?

### ISSUE THREAD

**Issue by Clyff** [yiisoft/yii2#11814]
### What steps will reproduce the problem?

I'm using the yii\validators\ExistValidator to validate some fields in my model (Instructor) like this:

``` php
    public function rules()
    {
        return [
            [['program_id', 'institution_id'], 'required'],
            [['program_id', 'institution_id'], 'exist', 'skipOnError' => true, 'targetClass' => Program::className(), 'targetAttribute' => ['program_id' => 'id', 'institution_id' => 'institution_id']],
        ]
    }
```
### What do you get?

In my form when I select a `program_id`it triggers the error (because the other field, `institution_id`, is empty) and the error only goes away when I select one institution and re-select the program.

At the end, the validation is working fine. But I don't think is very intuitive for all users in this case.
### What is the expected result?

Is just a suggestion, but can we avoid the empty values before do the validation? When the form is submited any empty value will be verified by RequiredValidator if it's required anyway.

A little change in the yii\validators\ExistValidator would work:

```
protected function createQuery($targetClass, $condition)
{
    /* @var $targetClass \yii\db\ActiveRecordInterface */
    $query = $targetClass::find()->andFilterWhere($condition);
    if ($this->filter instanceof \Closure) {
        call_user_func($this->filter, $query);
    } elseif ($this->filter !== null) {
        $query->andFilterWhere($this->filter);
    }
    return $query;
}
```

At the moment I'm doing a custom validation, but i can't see why the yii\validators\ExistValidator can't change.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9-dev |
| PHP version | 5.6.22-1+donate.sury.org~trusty+1 |
| Operating system | Ubuntu (64-bit) |

**Comment by Faryshta** [comment]
add `'skipOnEmpty' => true` and it will behave the way you expect.
