### ISSUE TITLE
make currency code show after value in formatter->asCurency()

### ISSUE THREAD

**Issue by Tarekajaj** [yiisoft/yii2#11810]
### What steps will reproduce the problem?
in config I have
```
'formatter' => [
	'currencyCode' => 'AED',
],
```   
then I use
`\Yii::$app->getFormatter()->asCurrency(100);`

I get _AED100.00_

How can I specify the pattern of the output like I want to get **100.00 AED**

**Comment by samdark** [comment]
It depends on locale you're using. Either set different locale to the component or change application language.
