### ISSUE TITLE
\yii\log\Target::$except not working as expected?

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#11819]
### What steps will reproduce the problem?

In config:

```php
'log' => [
    'traceLevel' => YII_DEBUG ? 3 : 0,
    'targets'    => [
        [
            'class'  => 'yii\log\FileTarget',
            'levels' => ['error', 'warning'],
            'except' => [
                'yii\web\HttpException:404',
            ],
        ],
        [
            'class'      => 'yii\log\FileTarget',
            'levels'     => ['error'],
            'categories' => [
                'yii\web\HttpException:404',
            ],
            'logFile'    => '@runtime/logs/http-404.log',
        ],
    ],
],

```

### What is the expected result?

Expected that all errors except 404 will be written to default `app.log` and 404 errors - to `http-404.log`

### What do you get instead?

404 errors are written to both log files.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      |  5.7
| Operating system |  Windows

**Comment by SDKiller** [comment]
Strange, but could not reproduce the same with with 2.0.8

**Comment by samdark** [comment]
Well, then it seems it was fixed.
