### ISSUE TITLE
How to get a new line in a Gridview column

### ISSUE THREAD

**Issue by indicalabs** [yiisoft/yii2#11823]
### What steps will reproduce the problem?
I am traing to display two attributes in a single GridView::widget column, with a new line in between them.
Below is the code, but the "\n". or br tag is not converting into new line. Is there any alternative way? 
`[
'label' => 'Message',
'attribute' => 'message',
'value' => function ($searchModel) {
	return  Yii::$app->formatter->asNtext($searchModel->message)."\n".Yii::$app->formatter->asDatetime($searchModel->sent_time);
      },
],`
### What is the expected result?
New Line in between attribute values
### What do you get instead?
No new line in between attributes
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  Latest
| PHP version      |  7
| Operating system | Linux
Thank you for your help

**Comment by cebe** [comment]
the output will be html so you should use a `<br>` instead of `\n`.

**Comment by indicalabs** [comment]
@cebe Thank you for your help.
`'format' => 'html',` with a `<br>` tag fixed the issue.
