### ISSUE TITLE
CSRF

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#11822]
### What steps will reproduce the problem?
Send POST CSRF param in array _csrf[] = NWR5V0o5N3h7VBQmFW5fElcXFBgpXmEQRAopYDlQQjZfHBMiKwoOIQ%3d%3d
### What is the expected result?
Return 400 Bad Request or something more...
### What do you get instead?
Getting crash of app
![crash](http://image.prntscr.com/image/f087f52b87dc4f319bb72ede1eed6d7d.png)
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | Windows 10.1

**Comment by cebe** [comment]
fixed, thanks for reporting!
