### ISSUE TITLE
Add SQL function and type support to Query

### ISSUE THREAD

**Issue by darvids0n** [yiisoft/yii2#11829]
Function and type support is related

``` php
$results = (new Query())
    ->selectType('schema.mySqlType')
    ->fromFunction('schema.funcname', $param1, $param2, $param3)
    ->where(['myType_field1', 'xyz'])->all();
```

More secure than raw SQL, we can then 'bind' function parameters. Already caching column metadata anyway so we can also look up e.g. `pg_type` and `pg_proc` for postgres to get this info, plus a function to convert from type metadata to a sane PHP type which we already do with base types.

**Comment by samdark** [comment]
Good idea.

**Comment by SilverFire** [comment]
Can be achieved somehow like this:

```php
new \yii\db\Expression('function_name(:param, :param1)', [
    ':param' => 'love',
    ':param1' => 'Yii'
]);
```
