### ISSUE TITLE
Yii::app->modules on Centos6

### ISSUE THREAD

**Issue by sergey-program** [yiisoft/yii2#11824]
On first line it crashes

        if (\Yii::$app->modules) {
            foreach (\Yii::$app->modules as $name => $namespace) {
                $module = \Yii::$app->getModule($name);

                if (!isset($module->menuList) || empty($module->menuList->getList())) {
                    continue;
                }

                $menu = array_merge($module->menuList->getList(), $menu);
            }
        }

But on Ubuntu (local) it works. Why this can happen?

Routes and params are valid, I recheck it several times. Code executed in view (main layout).

**Comment by samdark** [comment]
How exactly it crashes?

**Comment by sergey-program** [comment]
http://awesomescreenshot.com/0745z7hdc3

The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by samdark** [comment]
What's in the logs?

**Comment by sergey-program** [comment]
[Sun Jun 26 15:23:31 2016] [error] [client 31.128.129.81] PHP Fatal error:  Can't use method return value in write context in /var/www/xxx/backend/views/layouts/_sidebar.php on line 39, referer: http://xxx/panel/articles/article/list

latest one

**Comment by samdark** [comment]
What's in the `_sidebar.php` around line 39?

**Comment by sergey-program** [comment]
Is a view, that `$this->render('_sidebar')` in main `/backend/layouts/main.php`. Look code in first post. I erase everything from there for clear tests.

**Comment by sergey-program** [comment]
```
<?php

namespace backend\components;

use backend\components\sidebar\MenuList;
use yii\base\InvalidConfigException;
use yii\base\Module;

/**
 * Class ModuleExtended
 *
 * @package backend\components
 *
 * @property MenuList   $menuList
 * @property array|null $requiredModules
 */
class ModuleExtended extends Module
{
    public $menuList;
    public $requiredModules;

    /**
     * @throws InvalidConfigException
     */
    public function init()
    {
        $this->menuList = new MenuList();
        parent::init();
        $this->checkRequiredModules();
    }

    /**
     * @param string $moduleName
     *
     * @return $this
     */
    public function addRequiredModule($moduleName)
    {
        $this->requiredModules[] = $moduleName;

        return $this;
    }

    /**
     * @return array
     */
    public function getRequiredModules()
    {
        return $this->requiredModules;
    }

    /**
     * @throws InvalidConfigException
     */
    public function checkRequiredModules()
    {
        if ($this->requiredModules) {
            foreach ($this->requiredModules as $moduleName) {
                if (!\Yii::$app->hasModule($moduleName)) {
                    throw new InvalidConfigException('Module requires another module. ' . $moduleName . ' not enabled.');
                }
            }
        }
    }
}
```

**Comment by rob006** [comment]
> `empty($module->menuList->getList())`

Prior to PHP 5.5 you can not pass expression (method) to `empty()`, you need use variable. Try `$module->menuList->list` or use helper variable.

**Comment by sergey-program** [comment]
@rob006 YES! THANK YOU! 
Localy I have Ubuntu php 5.5, on Centos php  5.4 That's was a problem. Thank you again. Can be closed.
