### ISSUE TITLE
IN array condition when using `yii\db\Query`

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#11827]
### What steps will reproduce the problem?
```php
$statuses = [1, 2, 3];
$rows = (new \yii\db\Query())
    ->select('*')
    ->from('user u')
    ->leftJoin('profile p', new \yii\db\Expression('p.id = u.profile_id AND p.status IN (:statuses)', [':statuses' => $statuses]))
   // OR ->leftJoin('profile p', 'p.id = u.profile_id AND p.status IN (:statuses)', [':statuses' => $statuses])
    ->createCommand()
    ->getRawSql();
```
### What is the expected result?
```sql
SELECT * FROM `user` `u` 
LEFT JOIN `profile` `p` 
ON p.id = u.profile_id AND p.status IN (1, 2, 3)
```
### What do you get instead?
```sql
SELECT * FROM `user` `u` 
LEFT JOIN `profile` `p` 
ON p.id = u.profile_id AND p.status IN (1)
```
### Additional info
It seems to be more a `PDO` issue but maybe Yii could have a way to circunvent it when calling `Command::bindPendingParams()`.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  7.0.4
| Operating system | Ubuntu 16.04

**Comment by pstddc** [comment]
onCondition

**Comment by pstddc** [comment]
->leftJoin()->onCondition()

**Comment by slinstj** [comment]
`onCondition()` is not available for Query but for ActiveQuery.

**Comment by pstddc** [comment]
try:
```php
->leftJoin('profile p', ['p.id' => 'u.profile_id', 'p.status' => $statuses])
```

**Comment by slinstj** [comment]
It really works @pstdd! Thank you so much!

In my real test i just had to make an adjustment because `x.id` was used two (or more) times, so, just in case someone else need it, I did it using `and` because the key duplication:

```php
// ...
->leftJoin('table x', ['and', ['x.id' => new \yii\db\Expression('t.x_id')], ['x.id' => $arrayIds]])
```

And it is generating this SQL:
```sql
... LEFT JOIN `table` `x` ON (`x`.`id`=t.x_id) AND (`x`.`id` IN (2, 4))
```
