### ISSUE TITLE
Declaration of mssql\QueryBuilder::buildOrderByAndLimit() should be compatible with db\QueryBuilder::buildOrderByAndLimit

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#11839]
PHP Warning `'yii\base\ErrorException'` with message "Declaration of `yii\db\mssql\QueryBuilder::buildOrderByAndLimit($sql, $orderBy, $limit, $offset)` should be compatible with `yii\db\QueryBuilder::buildOrderByAndLimit($sql, $orderBy, $limit, $offset, &$params)`"

**Comment by klimov-paul** [comment]
Declarations of the `buildOrderByAndLimit()` method are identical:

https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L863
https://github.com/yiisoft/yii2/blob/master/framework/db/mssql/QueryBuilder.php#L51

Closed, unless more information provided.

**Comment by githubjeka** [comment]
Opps, branch v2.1
https://github.com/yiisoft/yii2/blob/2.1/framework/db/QueryBuilder.php#L847
https://github.com/yiisoft/yii2/blob/2.1/framework/db/mssql/QueryBuilder.php#L51

**Comment by samdark** [comment]
I've just merged master in 2.1. @githubjeka Could you re-check?

**Comment by githubjeka** [comment]
@samdark 
[mssql/QueryBuilder](https://github.com/yiisoft/yii2/blob/2.1/framework/db/mssql/QueryBuilder.php#L51-L63) doesn't use `$params` from parent [QueryBuilder](https://github.com/yiisoft/yii2/blob/2.1/framework/db/QueryBuilder.php#L848)

**Comment by samdark** [comment]
OK. I just want to be sure it wasn't fixed in master...

**Comment by cebe** [comment]
introduced by #10682, fixed it.
