### ISSUE TITLE
LinkSorter bug 

### ISSUE THREAD

**Issue by ITfighter** [yiisoft/yii2#11830]
When i set label for attribute, i see exception: 
![bug](https://cloud.githubusercontent.com/assets/14202900/16370597/b9b9d79c-3c49-11e6-8b8f-a18c935233ec.png)

Code:
<?= ListView::widget([
'dataProvider' => $dataProvider,
'itemView' => 'market_place_item',
'layout' => "{sorter}\n{summary}\n{items}\n{pager}", // Add sorter to layout because it's turned off by default
'sorter' => [
'linkOptions' => [
],
'attributes' => [
'service_type'=>
'label' => 'Test'

],
]
],]
); ?>

but when i remove label option, all is good. Please help me, thank )

**Comment by schoradt** [comment]
The Label must be set in the declaration of the sort instance see [http://www.yiiframework.com/doc-2.0/yii-data-sort.html](http://www.yiiframework.com/doc-2.0/yii-data-sort.html).
