### ISSUE TITLE
NTEXT is being deprecated in MSSQL

### ISSUE THREAD

**Issue by Lifesnoozer** [yiisoft/yii2#11835]
The column type `NTEXT` is being deprecated in MSSQL, it's recommended to use `NVARCHAR(MAX)` instead (https://msdn.microsoft.com/en-us/library/ms187993.aspx), `\yii\db\mssql\QueryBuilder` should probably use `NVARCHAR(MAX)` instead of `NTEXT` for `Schema::TYPE_TEXT` to avoid problems.

**Comment by SilverFire** [comment]
Resolved in #12663
