### ISSUE TITLE
pjax fragment will load full page

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#11847]
1. I create a modal and content is loaded via pjax
2. I want to reload modal content and only replace .modal-body , so I use fragment property.

Here is my code
~~~javascript
    $.pjax.reload('#container-checkpoint .modal-body' , {
                url : 'this is my url',
                async: false,
                container: '#container-checkpoint',
                fragment: '.modal-body',
                push: false,
                replace: false
    });
~~~
This code can work , and modal content reload is correct  ,  but server response full page html !!

![image](https://cloud.githubusercontent.com/assets/1013744/16447235/247f0b94-3e1e-11e6-975a-650134f2816c.png)
(pjax request)

![image](https://cloud.githubusercontent.com/assets/1013744/16447274/449c940a-3e1e-11e6-9876-ebcbd577e1ef.png)
(full html)

**Comment by samdark** [comment]
In your action you should detect if request is PJAX and render partial instead of doing full render.

**Comment by pigochu** [comment]
Why  render partial ? my view is using Pjax::begin.
If I never use fragment property , server will response correct data .
But I don't want replace all content to modal. I want replace  .modal-body only.

Is the header X-PJAX-Container correct ?

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
Is it sending X-PJAX-Container in this case? If yes, could you try adding it to https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L328 and checking again with your use case?

**Comment by pigochu** [comment]
Why I need use Request::isPjax ?
In my case , my view is using Pjax::begin() , but it will render full page(with layout).
If I change render() to renderAjax() . its also work fine. but why I need change to renderAjax() ?
The widget Pjax::begin() will auto do the same thing when I don't use fragment.

Now I change YII2's Pjax Source Code.
~~~php
    protected function requiresPjax()
    {
        $headers = Yii::$app->getRequest()->getHeaders();
        return  $headers->get('X-Pjax') && explode(' ', $headers->get('X-Pjax-Container'))[0] === '#' . $this->options['id'];
        // return $headers->get('X-Pjax') && $headers->get('X-Pjax-Container') === '#' . $this->options['id'];
    }
~~~
It works fine . but I don't know is it correct for PJAX spec ?

**Comment by pigochu** [comment]
Wa ha.. 
I fixed the problem in my case.
I  add the line in my action before render.

~~~php
            Yii::$app->getRequest()->headers->set('X-Pjax-Container' , explode(' ', Yii::$app->getRequest()->headers['X-Pjax-Container']));
            return $this->render('attachment', [
                'model' => $model
            ]);
~~~

**Comment by samdark** [comment]
Weird.

**Comment by pigochu** [comment]
@samdark 

U can see my first comment . It send "X-PJAX-Container: #checkpoint-container .modal-body" .You can see it in first picture.
So Pjax::requiresPjax() will return false , and render full page.

**Comment by samdark** [comment]
Ah! Got it. Yes, the fix seems to be correct.

**Comment by enkr1** [comment]
Hi, 

Is this issue still active? I cannot solve it with the solution u provided.

In my case, I have declared a `Pjax` which wraps a `GridView` such as:
```php

<?php Pjax::begin([
  'id' => $gridviewId,
  'enablePushState' => false,
  'enableReplaceState' => false,
  'timeout' => -1,
]); ?>

<?= GridView::widget([  
//...

```

I want to avoid the page reload/refresh as for now it ONLY works when the dataset is small. Meaning, the more data I have to display in the `GridView`, the page will be reloaded.
