### ISSUE TITLE
\yii\db\Query *join methods parse $on arrays as a condition, destroying SQL statements

### ISSUE THREAD

**Issue by pvlg** [yiisoft/yii2#11842]
Т.к. https://github.com/yiisoft/yii2/issues/7549 был закрыт, то открываю новый.

Предположим есть модуль который содержит следующий запрос

```php
$query = new Query();
$query->from(['order' => Order::tableName()]);
$query->leftJoin([
    'user' => User::tableName(),
], ['order.UserId' => 'user.Id']);
```
обратите внимание, что в названиях колонок есть символы в верхнем регистре.

если использовать бд postgresql, то будет сгенерирован sql

```sql
SELECT "order".* FROM "tbl_order" "order" LEFT JOIN "tbl_user" "user" ON "order"."UserId" = "user"."Id"
```
если использовать бд mysql, то будет сгенерирован sql

```sql
SELECT `order`.* FROM `tbl_order` `order` LEFT JOIN `tbl_user` `user` ON `order`.`UserId` = `user`.`Id`
```
Обратите внимание на кавычки.

Если следовать примечанию в документации https://github.com/nevermnd/yii2/blob/d9fb32e62c86cd0b46147f4068be9299538f652f/framework/db/Query.php#L639, то получается такой код

```php
$query = new Query();
$query->from(['order' => Order::tableName()]);
$query->leftJoin([
    'user' => User::tableName(),
], 'order.UserId = user.Id');
```

Сформированный sql корректно отработает в mysql, но не в postgres т.к. postgres приводит названия колонок к нижнему регистру, если они не заключены в кавычки, но если написать такой код

```php
$query = new Query();
$query->from(['order' => Order::tableName()]);
$query->leftJoin([
    'user' => User::tableName(),
], '"order"."UserId" = "user"."Id"');
```

то сформированный sql не отработает в mysql, т.к. mysql не понимает двойные кавычки, ему нужен обратный апостроф.

**Comment by klimov-paul** [comment]
Use quoting markup:

```php
$query = new Query();
$query->from(['order' => Order::tableName()]);
$query->leftJoin([
    'user' => User::tableName(),
], ['{{order}}.[[UserId]]' => '{{user}}.[[Id]]']);
```

**Comment by pvlg** [comment]
Thank you! I think it would be nice it is to specify in the documentation. At least I have not found.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/db-dao.md#quoting-table-and-column-names-
