### ISSUE TITLE
BaseInflector slug creation

### ISSUE THREAD

**Issue by Lugat** [yiisoft/yii2#11848]
When using BaseInflectors transliterate method, is checks if the intl Extension is loaded, but it also requires ICU. It would be nice, if the BaseInflector could also check for ICU version or you could specify an attribute to use your fallback solution with strtr. In my case the slug creation always causes problems, due to the fact, that our hoster only offers a lower version of ICU.

**Comment by samdark** [comment]
The check won't be reliable because different languages require different minimum ICU data version.

**Comment by Lugat** [comment]
Damn. Then I need to put a dirty hack inside :/
