### ISSUE TITLE
EachValidator + UrlValidator: $defaultScheme is not prepended

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#11849]
### What steps will reproduce the problem?

Create form with multiple url input.
Define `defaultScheme => 'http'` in model rule:

```
['domain_aliases', 'each', 'rule' => ['url', 'defaultScheme' => 'http', 'enableIDN' => true]],
```

Paste urls without scheme, i.e `example.com`

### What is the expected result?

`http://example.com`

### What do you get instead?

Validation passes, `http` is not prepended, url is saved as is `example.com`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | Windows/Debian

**Comment by pstddc** [comment]
defaultScheme - not required - default

**Comment by SDKiller** [comment]
@pstddc 

Sorry, haven't got it

**Comment by SDKiller** [comment]
My fault, was using wrong vendor folder.

Everything is Ok on current `2.0.8`
