### ISSUE TITLE
Single value in "IN" condition cause error in QueryBuilder

### ISSUE THREAD

**Issue by arkhamvm** [yiisoft/yii2#11858]
### What steps will reproduce the problem?
```php
$query = (new Query())
                ->select(['some_id'])
                ->from(AnyTable::tableName())
		->where([
				'AND',
					['IN', 'some_field', 'some_value'],
					['NOT IN', 'some_field', 'some_value2'],
		]);
```

### What is the expected result?

```sql
SELECT some_id
FROM any_table
WHERE ((some_field IN ('some_value')) AND (some_field NOT IN ('some_value2'))
```

### What do you get instead?

```
yii\base\ErrorException: Invalid argument supplied for foreach() in vendor/yiisoft/yii2/db/QueryBuilder.php:1186
```

### Current yii2 code
```php
// yii\db\QueryBuilder

        if ($values instanceof Query) {
            return $this->buildSubqueryInCondition($operator, $column, $values, $params);
        }

        .....

        $sqlValues = [];
        foreach ($values as $i => $value) {   // <= Error line №1186
              ....
        }
```

### Possible fix

```php
// yii\db\QueryBuilder

        if ($values instanceof Query) {
            return $this->buildSubqueryInCondition($operator, $column, $values, $params);
        }
        else if (false === is_array($values)) {
             $values = [$values]; // Convert single value to array with one element
        }

        .....

        $sqlValues = [];
        foreach ($values as $i => $value) {
              ....
        }
```

Or throw exception, something like: "The 'value' argument for 'in' condition should be array or Query".

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  7.0.4
| Operating system | Linux 4.4.0-24

**Comment by Alex-Code** [comment]
Why don't you pass an array if you're doing an `IN`?

**Comment by arkhamvm** [comment]
There is no documentation or phpdoc about it. 
Docs just say that '$params' must be array in 'where' function call. So, that's exactly what I did.

**Comment by rob006** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryInterface.php#L115

And you should probably use 
```php
['=', 'some_field', 'some_value'],
['!=', 'some_field', 'some_value2'],
```

**Comment by arkhamvm** [comment]
@rob006, just imagine instead of 'some_value' $some_variable, that can be array or single value too. Your example will cause error, if $some_variable becomes an array.

**Comment by samdark** [comment]
It's by design. `IN` is for checking if column value is in the set of values. For a single value either you should pass an array anyway or you should use `=`.

**Comment by arkhamvm** [comment]
@samdark, Ok, why not to throw exception at least?

**Comment by samdark** [comment]
You're already getting an error.

**Comment by karmrajzala** [comment]
@arkhamvm Here In condition or Not in Condition your passing parameter should be in array. Go though this [link](http://www.yiiframework.com/doc-2.0/yii-db-query.html#where%28%29-detail)
