### ISSUE TITLE
Yii2 throws Bad Request when adding the web application as Facebook Custom Tab

### ISSUE THREAD

**Issue by OscarIbarra** [yiisoft/yii2#11853]
I have a simple Yii2 Web application that works fine when I access it in the main browser window.  But this Web application is intended to work inside a Facebook Page as a Custom Tab.

When I test the application as a Facebook Custom Tab it throws Bad Request Error but outside it doesn't.

What am I doing wrong?

Thanks in advance.

**Comment by samdark** [comment]
What's in the logs?

**Comment by OscarIbarra** [comment]
How do you see the logs in yii?

2016-06-30 1:45 GMT-05:00 Alexander Makarov <notifications@github.com>:

**Comment by samdark** [comment]
Usually they're in `runtime` directory. See http://www.yiiframework.com/doc-2.0/guide-runtime-logging.html

**Comment by klimov-paul** [comment]
Closed unless more information provided.
