### ISSUE TITLE
Rest Api Cross-Origin Request Blocked Problem for authenticated methods

### ISSUE THREAD

**Issue by zeevy** [yiisoft/yii2#11854]
I am facing cors problem in rest api only for authenticated methods when accessed via javascript, when i removed the authentication every thing works as expected.
non authenticated methods like index and view working fine. Authenticated methods are working only  for same origin.

### What steps will reproduce the problem?
<code>
<pre>
    public function behaviors(){
        return ArrayHelper::merge(parent::behaviors(), [
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
                'cors' => [
                    'Origin' => ['*'],
                ],
            ],
            'authenticator' => [
                'class' => CompositeAuth::className(),
                'except' => ['index', 'view'],
                'authMethods' => [
                    HttpBasicAuth::className(),
                    HttpBearerAuth::className(),
                    QueryParamAuth::className(),
                ],
            ],
        ]);
    }
</pre>
</code>
### What is the expected result?
Normal execution of the script
### What do you get instead?
Error: Cross-Origin Request Blocked
 (Reason: CORS header 'Access-Control-Allow-Origin' missing)

### Response Headers When accessed authenticated methods (ex post)
HTTP/1.1 200 OK
Date: Thu, 30 Jun 2016 05:55:07 GMT
Server: Apache/2.4.17 (Win64) PHP/5.6.16
X-Powered-By: PHP/5.6.16
WWW-Authenticate: Bearer realm="api"
Content-Length: 335
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json; charset=UTF-8

### Response Headers when accessed non auth methods (ex get)
HTTP/1.1 200 OK
Date: Thu, 30 Jun 2016 05:58:45 GMT
Server: Apache/2.4.17 (Win64) PHP/5.6.16
X-Powered-By: PHP/5.6.16
access-control-allow-origin: http://********.com
X-Pagination-Total-Count: 500
X-Pagination-Page-Count: 25
X-Pagination-Current-Page: 1
X-Pagination-Per-Page: 20
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.16
| Operating system | Windows 10 64bit (apache 2)

**Comment by zeevy** [comment]
It seems to be working this way ( has to add "corsFilter" before "authenticator" ). if we use ArrayHelper::merge its not working as expected.
<pre>
<code>
    public function behaviors(){
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::className(),
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
                'Access-Control-Request-Headers' => ['*'],
            ],
        ];
        
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'except' => ['index', 'view', 'options'],
            'authMethods' => [
                HttpBasicAuth::className(),
                HttpBearerAuth::className(),
                QueryParamAuth::className(),
            ],
        ];
        
        return $behaviors;
    }

</code>
</pre>

**Comment by tunecino** [comment]
@zeevy it has been documented recently here: http://www.yiiframework.com/doc-2.0/guide-rest-controllers.html#cors
