### ISSUE TITLE
Selected in dropDownList

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2#11865]
### What steps will reproduce the problem?
Use dropDownList.

### What is the expected result?
```
$form->field($customerModel, 'groupId')->dropDownList(
$customerGroupsList,
[
    'options' =>
    [
        $customerGroupDefaultId => ['selected' => true],
    ],
]
)
```

### What do you get instead?
```
$form->field($customerModel, 'groupId')->dropDownList(
$customerGroupsList,
[
    'options' =>
    [
        $customerGroupDefaultId => ['Selected' => true],
    ],
]
)
```

### Additional info
[stackoverflow](http://stackoverflow.com/questions/31104715/yii2-dropdownlist-select-default-option)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7 x64
| Operating system | Windows 10

**Comment by michaelantipenko** [comment]
Why not use model for set groupId? $customerModel->groupId = $customerGroupDefaultId

**Comment by jainabhishek14** [comment]
```<?=
    $form->field($addressModel, "[{$index}]city_id")->dropDownList(
         ArrayHelper::map(City::find()->all(), 'id', 'name'), ["options" => [
               $locationModel->city_id => ["Selected" => true]
         ]
    ])  
?>
```
What is the issue in this?
