### ISSUE TITLE
Add more flexibility to LinkPager Widget

### ISSUE THREAD

**Issue by cyphix333** [yiisoft/yii2#11868]
I'm using the LinkPager widget and would like it if you could add a parameter to decide in what order to place the `First/Prev` and `Next/Last` buttons.

At the moment it's hardcoded that the buttons go in the aforementioned order and the only way for me to change this is to extend the widget and override the class.

The reason I want to change this is because I want to use numbers for the First/Last pages and hence want to keep all the numbers together - as another note; if these parameters are implemented it should also check to see if the First/Last numbers have already been shown, because at the moment if you use numbers for the First/Last buttons then it duplicates the number twice in certain situations.

| Q | A |
| --- | --- |
| Yii version | 2.0.7 |
| PHP version | 5.5.28 |
| Operating system | Win 7 / CentOS |

**Comment by samdark** [comment]
What do you want to get in the end?

**Comment by cyphix333** [comment]
Well for example I'm trying to get something like this:

![untitled-1](https://cloud.githubusercontent.com/assets/9627036/16541514/c439c142-40b7-11e6-8a4e-295773a8c5cf.png)

...where "1" is obviously the first page and "10" is the last page.

**Comment by samdark** [comment]
Looks like introducing a template as in grid view could be a good idea...

**Comment by rubenjleon** [comment]
I would like something like this where you can control the number of pages displayed via a dropdown, type in the page number you want to go to, etc.

![screen shot 2016-07-06 at 8 42 07 am](https://cloud.githubusercontent.com/assets/9327021/16624198/a88d5634-4355-11e6-974a-0c86c70ee2e5.png)

**Comment by samdark** [comment]
Well, that's a bit different. It cannot be achieved with simple template...

**Comment by samdark** [comment]
Won't be implemented in 2.0.
