### ISSUE TITLE
[2.0.8 - BaseInflector] - Error get slug with Unicode characters from BaseInflector(Vietnamese)

### ISSUE THREAD

**Issue by lamptt** [yiisoft/yii2#11867]
When I get slug string example:
BaseInflector::slug('quảng bình');
Result: qung-binh

Currently, Result missing 'ả' character. Please, help me!

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/yii-helpers-baseinflector.html#$transliterator-detail
