### ISSUE TITLE
Message formatter "fallback" plural - mb_substr() cannot calculate the length of the string in multi-byte encoding (UTF-8)

### ISSUE THREAD

**Issue by madrussa** [yiisoft/yii2#11863]
### What steps will reproduce the problem?
Trying to format the following message:
`{recipientCount,plural,=0{There are no recipients}=1{The only recipient is {recipientName}}=2{The two recipients are {recipientName}}other{Too many recipients to list, # in total}}`
when using an integer value of 1 or 2 it always falls back to other.

### What is the expected result?
To display the message "The two recipients are {recipientName}" when recipient count is 2.

### What do you get instead?
I got the message "Too many recipients to list, # in total}"

### Explanation and possible solution:
The issue resides in how the plural fallback mechanism works in yii2/framework/i18n/MessageFormatter.php. Lines 404 and 407 use NULL as the length parameter in mb_substr, but this can cause issues with UTF-8 strings as the length sometimes cannot be determined.
`$selector = trim(mb_substr($selector, $pos + 1, null, $charset));`

I suggest the following fix:
`$selector = trim(mb_substr($selector, $pos + 1, mb_strlen($selector, $charset), $charset));`

Using mb_strlen($selector, $charset) should correctly detect the length so the selector can return the correct value to match against. Otherwise it returns an empty string which does not match the current argument.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 5.3.6
| Operating system | Ubuntu 14

**Comment by samdark** [comment]
Fixed. Thanks!
