### ISSUE TITLE
Inflector slug returns empty string

### ISSUE THREAD

**Issue by croatiangrn** [yiisoft/yii2#11860]
When I use `$val = 'Lorem ipsum'; var_dump(Inflector::slug($val);)` it works as expected on localhost, but on live server returns string""(0).
Other Inflector methods like humanize/camelize work both on localhost and liveserver. Slug is the only problem.
### What is the expected result?
slug from the given value
### What do you get instead?
empty string

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system |

**Comment by samdark** [comment]
Do you have intl and ICU installed?

**Comment by croatiangrn** [comment]
Requirements say that intl is installed and ICU gives warning that it needs
higher version.

pet, 1. srp 2016. 12:29 Alexander Makarov <notifications@github.com> je
napisao:

**Comment by samdark** [comment]
Well, that's the reason.

**Comment by croatiangrn** [comment]
But on my localhost I don't even have intl and ICU extensions and it still works as expected..

**Comment by samdark** [comment]
Probably because it falls back to native PHP replacement when you don't have intl at all.
