### ISSUE TITLE
registerJsFile issue when has "&" in url

### ISSUE THREAD

**Issue by c4ys** [yiisoft/yii2#11877]
### What steps will reproduce the problem?

`<?php $this->registerJsFile('http://api.map.baidu.com/api?v=2.0&ak=key',['position'=>View::POS_HEAD]);?>`

### What is the expected result?
`<scrip src="http://api.map.baidu.com/api?v=2.0&ak=key"></script>`

### What do you get instead?
`<scrip src="http://api.map.baidu.com/api?v=2.0&amp;ak=key"></script>`

### Additional info
Add ['encode'=>false] in options?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.2
| Operating system | fedora 24

**Comment by samdark** [comment]
It works as expected. `&` should be encoded in src.
