### ISSUE TITLE
Docs Guide (input-multiple-models.md) - Example assumes PK id's are in sync

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2#11870]
I noticed that in the example on this page: [https://github.com/yiisoft/yii2/blob/master/docs/guide/input-multiple-models.md](https://github.com/yiisoft/yii2/blob/master/docs/guide/input-multiple-models.md)

The `UserController`'s `actionUpdate` function assumes that the `user` table's primary key and the `user_profile` table's primary key are in sync. This may not always be the case, and is likely to cause issues for users down the road (and during development).

It would be better to use the relation's foreign key which maps back to the user table. Example in "solution" below.

My `user` table is stock from advanced migration example. So the `id` is auto-incrementing primary key.

In my `user_profile` table, I have:

    id (auto incrementing primary key), user_id (foreign key to user table's id column), nicename, phone, address, etc, etc.

In the example, using `findOne($id)`, it is grabbing the current model/user id and trying to find that same id in the user_profile table. This would generally work. However, say you manually create a `user_profile`, the incremental value of the id would now be 1 higher than the user table. Until you manually go into your database and fix the incremental value, it will always be 1 off. **If it is off, it will grab the wrong profile!!!**

### Solution

Clip of what the docs should show:

`https://github.com/yiisoft/yii2/blob/master/docs/guide/input-multiple-models.md`

    class UserController extends Controller
    {
        public function actionUpdate($id)
        {
            $user = User::findOne($id);
            $profile = Profile::findOne(['user_id' => $id]);  // <-- fix
            // -- truncated
        }
    }

I understand that not everyone may have `user_id` column, they may name it something else. So I am not sure how to "officially" doc this. I am just pointing out the possible issue.

### Alternative Solution

Since not everyone will use the same column names, maybe in their `Profile` model, they can make their own `findProfile()` function.

    public static function findProfile($userId)
    {
        return self::findOne(['user_id' => $userId]);  // replace 'user_id' with your column name
    }

Then call it in `UserController`:

    $profile = Profile::findProfile($id);

**Comment by samdark** [comment]
Fixed. Thanks!

**Comment by WadeShuler** [comment]
Your Welcome.

While it is fixed for clarity, are there any Yii docs/guides that would lead a user up to creating the 'user_profile' column, or assigning a getter for it? This assumes they track the profile id in the user table, or have created a getter or variable to hold it. My user table has no knowledge of the profile table. In my profile table, I have a fk holder the user's id it matches.

What I am saying is, there are multiple ways to do it. So if there are guides/docs that would instruct the user on creating a profile table, and mapping the user id, so that your code using `$user->profile_id` would work for them, then maybe we should link to it so they can setup the prerequisites. 

You could do this (using relation):

    $profile = Profile::findOne($user->userProfile->user_id);

Where `userProfile` is my relation to my `user_profile` table, and `user_id` is a fk to the `user` table.

I actually created a getter:

    /common/models/User.php
    public function getProfileId()
    {
        return $this->userProfile->user_id;  // userProfile is relation and user_id is fk to user table
    }
    
    use in UserController.php
    $profile = Profile::findOne($user->profileId);  // calls the getter function in User

While I obviously can read the guide and solve the issue myself, others (newer to Yii) may be lost. Which is why I was wondering if there was some guides or docs we could link to, that would get them set up with handling the user profile as you have demonstrated. Something that if they follow, they are already properly setup to use the code on this page.

**Comment by samdark** [comment]
Well, user profile could be implemented in many ways and we can't show all these. There's no single correct way doing it.
