### ISSUE TITLE
Error in mailer under console, but it work in backend

### ISSUE THREAD

**Issue by skvarovski** [yiisoft/yii2#11887]
### What steps will reproduce the problem?
i have subscription in console and backend for mailing for test.
in template i use inserting php tag :

<? foreach ($a as $v) : ?>
.....
html + <?= $v->id  ?>
...
<? endforeach; ?>

### What is the expected result?
send email

### What do you get instead?
error  in console 
PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: v'
in  .... site.loc/common/mail/subscription_mail.php:50
... in backend it work..
This error appeared after updating PHP (5.4 -> 5.6) and Yii (2.0.7->2.0.8)

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  5.6
| Operating system | Debian 7

**Comment by samdark** [comment]
Please provide a way to reproduce the problem starting with clean basic application template. Thanks.

**Comment by githubjeka** [comment]
@skvarovski  
When you updated PHP 5.4 to 5.6, you set error_reporting to `ALL` in php.ini. 
```
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
```
http://php.net/manual/en/function.error-reporting.php
Consequently `PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: v'`

**Comment by skvarovski** [comment]
Можно тут по-русски:
конечно, я перекинул шаблон и контроллер на новый дистрибутив yii2-app-advanced развёрнутый композером и результат тот же. Самое забавное что под open server на php 5.6 все работает. Если можно я выложу тут пример-исходник более компактный. 

Напомню, что код котроллера под консолью и бэкэндом одинаковый, чую что разница между fpm и cli при обновлении случилась.

**Comment by AnikanovD** [comment]
@skvarovski 
Obviously, problem in your template. We can't help without full code of template.
If access happening in `foreach` scope, then variable will be defined in any case. 
This means that `<?= $v->id ?>` not in `foreach`.
Also don't use short tags. Use `<?php` instead `<?`.

**Comment by skvarovski** [comment]
@samdark  Вы оказались правы, тысяча извинений! проблема в тегах. ошибка была очень знакомая. тормозил.
