### ISSUE TITLE
Yii2 resutfull custom response will cause 301 redirection

### ISSUE THREAD

**Issue by chiefysu** [yiisoft/yii2#11889]
### What steps will reproduce the problem?
when I put below to config

```php
        'response' => [
             'class' => 'yii\web\Response',
             'on beforeSend' => function ($event) {
                 $response = $event->sender;
                 if ($response->data !== null && Yii::$app->request->get('suppress_response_code')) {
                     $response->data = [
                         'success' => $response->isSuccessful,                    
                         'data' => $response->data,
                         'status' => $response->statusCode,
                     ];
                     $response->statusCode = 200;
                 }
             },
         ],
```

and then I try post a new record   the Yii2 will cause  302 redirection to header location address;

and I change  $response->statusCode = 201;
 It works fine so what happend ?
How to fixed?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
What are you trying to achieve?

**Comment by klimov-paul** [comment]
Closed, unless more coherit description provided.
