### ISSUE TITLE
RadioList return empty value in all radio except last

### ISSUE THREAD

**Issue by PeterJason** [yiisoft/yii2#11888]
### What steps will reproduce the problem?
**Controller:**
```
$job = new Job;
$type = Type::find()->all();

var_dump(Yii::$app->request->post('Job'));
```

**View:**

```
foreach($type as $value){
	{
		echo '<td>';
			echo $form->field($job, "Type_Id")->radioList([$value->Id => $value->Name], ['class'=>'text-muted'])->label(false);
		echo '</td>';
	}
}
```

**var_dump return:**

**If i select first or each others radio (except last):**

  `'Type_Id' => string '' (length=0)`
  
**If i select last radio:**

  `'Type_Id' => string '20' (length=2)`
### HTML output?

```
<div class="form-group field-job-Type_Id">
<input type="hidden" name="Job[Type_Id]" value=""><div id="job-Type_Id" class="text-muted"><label><input type="radio" name="Job[Type_Id]" value="14"> Blue </label></div>
<div class="help-block"></div>
</div>

<div class="form-group field-job-Type_Id">
<input type="hidden" name="Job[Type_Id]" value=""><div id="job-Type_Id" class="text-muted"><label><input type="radio" name="Job[Type_Id]" value="18"> Red </label></div>
<div class="help-block"></div>
</div>

<div class="form-group field-job-Type_Id">
<input type="hidden" name="Job[Type_Id]" value=""><div id="job-Type_Id" class="text-muted"><label><input type="radio" name="Job[Type_Id]" value="20"> Purple </label></div>
<div class="help-block"></div>
</div>
```

### What is the expected result?

When i select a radio button return the right value.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.6.15
| Operating system | Xamp (Cross-platform)

**Comment by samdark** [comment]
How could we reproduce it?

**Comment by PeterJason** [comment]
What do you mean with that?

**Comment by samdark** [comment]
Ah. I've got it. You're creating a number of radio lists. Each one is separate. You either need to create buttons or call `$form->field($job, "Type_Id")->radioList(..., ['class'=>'text-muted'])->label(false);` once feeding it an array of **all** values. See ArrayHelper for a good way to get such array from ARs.

**Comment by PeterJason** [comment]
Yes @samdark . My output reproduce this: [Click to view image](http://image.prntscr.com/image/3e7438dc3fc54783b9b39137f09b06fe.png)

**Comment by samdark** [comment]
It's not framework issue. It works as expected. See https://github.com/yiisoft/yii2/issues/11888#issuecomment-230359986

**Comment by PeterJason** [comment]
With Arraymap i can't write one by one,? Only all?

Like this?
`$form->field($job, "Type_Id")->radioList(ArrayHelper::map(Type::find()->where(['Id' => $Type->Id])->one(), 'Id', 'Name'))->label(false);`

I plan to make a table:
```
<tr>
<td>value1 and radio 1</td>
<td>value2 and radio 2</td>
<td>value2 and radio 3</td>
</tr>
```
value1 & radio1 | value2 & radio2 | value3 & radio3
