### ISSUE TITLE
Query is passed as reference in widget

### ISSUE THREAD

**Issue by LauraArmitage** [yiisoft/yii2#11893]
I have created my own widget to display a graph:
```
$assessmentQuery = Assessment::find();
GraphOverTimeWidget::widget([
	'objectsQuery' => $assessmentQuery,
]);
```

Inside the widget I add further conditions to the query before executing it, e.g.
```
$this->objectsQuery
	->andWhere(['not', ['date' => NULL]]);
...
$results = $this->objectsQuery->all();
```
Then in the view, after calling the widget: 
```
var_dump($assessmentQuery->createCommand()->rawSql);
```

I would expect this to show 
```
"SELECT * FROM `assessment`"
```
but instead I get 
```
"SELECT * FROM `assessment` WHERE (NOT (`date` IS NULL))"
```

- If I pass a string through and change it or append to it (using `.=`) it doesn't affect the variable in the view
- If I reassign the variable to be something else e.g. inside the widget `$this->objectsQuery = User::find()` it does not affect the variable in the view
- I am wondering if the same happens when initialising any class properties in this way

This seems very odd and I can't find it documented anywhere so I am assuming it is a bug rather than being deliberate. 

---
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.22
| Operating system | OSX El Capitan 10.11.5

**Comment by klimov-paul** [comment]
http://stackoverflow.com/questions/6972860/object-copy-versus-clone-in-php
