### ISSUE TITLE
custom Pagination with pageParam and pageSizeParam don't work with DataProvider

### ISSUE THREAD

**Issue by dkduyanh** [yiisoft/yii2#11891]
### What steps will reproduce the problem?
I tried to create my own DataProvider with custom pageParam and pageSizeParam as below:

```php
$dataprovider = new \app\components\adapters\AdminDataProvider([
	'allModels' => \app\models\dao\user\Users::getInstance()->getList(),
	'pagination' => [
		'pageParam' => 'page',
		'pageSizeParam' => 'rpp',
		'pageSize' => 10,
	],
	'sort' => [
		'attributes' => ['user_id', 'user_username'],
	],		 		
]);
```

But the paging params always returns '-page' and '-per-page'

### What is the expected result?

They should be same with defined values.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  5.5.12
| Operating system |  Windows

**Comment by cebe** [comment]
> But the paging params always returns '-page' and '-per-page'

where do you see these? in the URL? where does the leading `-` come from?

**Comment by dkduyanh** [comment]
yes, in the url.

http://mydomain.com/index/test?page=3&per-page=10

Instead

http://mydomain.com/index/test?page=3&rpp=10

However, they work fine when I log-out and log-in again.

**Comment by cebe** [comment]
do you have some user specific caching enabled on the site?

**Comment by dkduyanh** [comment]
Yes, I use cache component with FileCache for getting data from model, However my DataProvider is out-side cache block. 

I also create admin by overriding user component to separate sessions from front-end. 

'admin' => [
            'class' => 'app\modules\admincp\components\Admin',
            'identityClass' => 'app\modules\admincp\components\AdminIdentity',
            'enableAutoLogin' => false,
      		'enableSession' => true,
            'loginUrl' => '/admincp/auth/login',
			'returnUrl' => '/admincp/index',
        ],

**Comment by cebe** [comment]
please disable the cache and check if the issue still exists. I am unable to reproduce this on a clean application installation.

**Comment by klimov-paul** [comment]
Closed unless more information provided.

**Comment by enkr1** [comment]
Any updates?

**Comment by samdark** [comment]
@enkr1 no. Do you have more info about the issue?

**Comment by enkr1** [comment]
I solved it, but my case is different. here is my solution https://forum.yiiframework.com/t/multiple-gridview-with-data-of-same-model-in-one-page/81732/4?u=enkr1

**Comment by My6UoT9** [comment]
U need to give the dataprovider an ID, then the paginator will work. 
https://www.yiiframework.com/doc/api/2.0/yii-data-basedataprovider#$id-detail

The reason for what the OP describes: https://github.com/yiisoft/yii2/blob/master/framework/data/BaseDataProvider.php#L216
