### ISSUE TITLE
RadioList problem

### ISSUE THREAD

**Issue by PeterJason** [yiisoft/yii2#11902]
### What steps will reproduce the problem?
**View:**

```
$data = ArrayHelper::map(Job::find()->all(), 'Id', 'AllData'); 


echo $form->field($type, "Job_Id")->radioList($data,                             [
		'item' => function($index, $label, $name, $checked, $value) {
			$return = $label;
			return $return;
		}
	])->label(false);
```

**Model Job:**
```
    public function getAllData(){       
        $radio = '<input type="radio" name="Typecurriculum[Job_Id]" value="'.$this->Id.'"> ' . $this->Name;
        $full = '<label>'. $radio . $image . $input1 . $input2 . '<br>' .'</label>';
		
        return $full;
    }
```

From this way works well...but if i change the variable $radio to the end of the line like this:
`$full = '<label>' . $image . $input1 . $input2 . '<br>' . $radio .'</label>';`

**I got always the error:**

> JOB ID MUST BE AN INTEGER.

### What is the expected result?

Display list of radio button without any error. First example in variable '$full' works great, but it does not show the structure that i desire

### What do you get instead?

**I got always the error:**

> JOB ID MUST BE AN INTEGER.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.15
| Operating system | Windows 10

**Comment by cebe** [comment]
please show the stacktrace of the error.

**Comment by klimov-paul** [comment]
Closed unless more information provided.
