### ISSUE TITLE
How can I get relation by relation type

### ISSUE THREAD

**Issue by dcb9** [yiisoft/yii2#11905]
### What steps will reproduce the problem?
Hello, I want to use type for relation in my model, for example:

```
class A extends ActiveRecord{
    public function getModel() {
        return $this->hasOne($this->type, ['id' => 'type_id']);
    }
}
```

I can not use Eager Loading.

### What is the expected result?

```
$a = A::find()->with('model')->one();
```

### What do you get instead?

```
$a = A::find()->one();
$model = $a->model; // lazy loading  correct
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 7.0.4
| Operating system | debian

**Comment by cebe** [comment]
A relation must be defined on a fixed type. it is not possible to make it depend on different classes the same way it is not possible to define a foreign key for different tables.
