### ISSUE TITLE
format=>date in GridView round (ceil) datetime 

### ISSUE THREAD

**Issue by EvilKarter** [yiisoft/yii2#11909]
### What steps will reproduce the problem?
In a table with a datetime column I only want to show the date.

	 <?= GridView::widget([
		'dataProvider' => $dataProvider,
		'columns'      => [
			[
				'attribute'      => 'create_time',
				'format'         => 'date',
				'contentOptions' => ['class' => 'hidden-xs'],
				'headerOptions'  => ['class' => 'hidden-xs'],
			],
		],]);?>

### What is the expected result?
In database the value is **2016-07-05 23:50:27** so the output should be **05.07.2016**
### What do you get instead?
In database the value is **2016-07-05 23:50:27** so the output is **06.07.2016**

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.16
| Operating system | Wampserver 3.0.0

**Comment by samdark** [comment]
That's extremely weird. Ideally we'd like to get a unit test that fails for it since it seems that it's not easy to reproduce.

**Comment by cebe** [comment]
that is a timezone issue. if your database is e.g. UTC and your application timezone is Europe/Berlin, 23:50 is already the next day.

**Comment by EvilKarter** [comment]
Yes I know that is a timezone issue.

But my first line in index.php is:

    date_default_timezone_set('Europe/Berlin');

But the formatter is using UTC as default and doesn't check if php default timezone is set. 

Is this behaviour intended or is it just coincidence? Because so I have to set default time zone for new DateTime objects AND set timezone in formatter

**Comment by cebe** [comment]
if your data is stored in a different timezone than UTC you have to configure defaultTimeZone of the formatter: http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#$defaultTimeZone-detail

date_default_timezone_set sets the output timezone of the appliction.

**Comment by EvilKarter** [comment]
ok but if I take a look into my database the datetime is saved in correct timezone. 
Also NOW() returns the correct datetime (EUROPE/BERLIN).

**Comment by cebe** [comment]
if your db returns data in EUROPE/BERLIN you have to configure the formatter to also use EUROPE/BERLIN, by setting $defaultTimeZone
