### ISSUE TITLE
Overwrite loginUrl at runtime for specific actions or controllers

### ISSUE THREAD

**Issue by netbrothers-tr** [yiisoft/yii2#11918]
### What steps will reproduce the problem?

Try to overwrite the login URL at runtime, e.g. like so:

    \Yii::$app->user->loginUrl = null;

### What is the expected result?

I would expect, that the forbidden exception will be thrown and the user will be confronted with the corresponding message.

### What do you get instead?

The user will still be redirected to the previously and statically set login page (in `config/web.php`).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  7.0.4
| Operating system | Ubuntu 16.04

### Workaround ###

I was able to work around this by overwriting the `beforeAction` method like so:

    public function beforeAction($action)
    {
        parent::beforeAction($action);
        if (\Yii::$app->user->loginRequired()) {
            // my customized redirect behaviour ...
        }
    }

**Comment by samdark** [comment]
At which part of the code `\Yii::$app->user->loginUrl = null;` was used?

**Comment by netbrothers-tr** [comment]
I tested it by placing the code within the `beforeAction` method like so:

    public function beforeAction($action)
    {
        parent::beforeAction($action);
        \Yii::$app->user->loginUrl = null;
    }

Then it didn't work.

**Comment by samdark** [comment]
Have you tried calling it before `parent::beforeAction($action);`?

**Comment by samdark** [comment]
Wait, you're setting it to `null` which means exactly "redirected to the previously and statically set login page": https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L378 so it works as designed.

**Comment by netbrothers-tr** [comment]
I was guided by the sentence `Set the loginUrl property to be null to show a HTTP 403 error instead of redirecting to the login page.` on [this page](http://www.yiiframework.com/doc-2.0/guide-rest-authentication.html) of The Definitive Guide to Yii 2.0. I've expected a 403 error instead of the login page. Is the guide wrong/ambiguous?

**Comment by pstddc** [comment]
```php
if ($return = parent::beforeXXX) {
//...
}
return $return; //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by netbrothers-tr** [comment]
> Have you tried calling it before `parent::beforeAction($action);`?

@samdark, This actually makes the difference. Thanks! :+1:
