### ISSUE TITLE
To consider echo'ing in init + run widgets a bad practice

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#11915]
I want to propose a change on the way Yii widgets are flushing output. The current implementation is in IMHO a bad practice. The ActiveFormTest https://github.com/yiisoft/yii2/blob/master/tests/framework/widgets/ActiveFormTest.php shows clearly why this behavior smells. Many ob_starts / ob_ends are required which doesnt really contribute to the ease of extending Yii widgets nor creating unit tests for them. Its also a bad practive from a OO perspective and not for the least, its confusing and timeconsuming for the end user to handle it.

To conclude. We should render output by using the return statement of run() only. In PHP7, this will be the primary method to return a string.

### What steps will reproduce the problem?
1) Create your own unit test on a Yii widget that has an echo in either init() or run().
   It will fill your console with echo's.

2) Override a Yii widget: The echos are difficult to control

### What is the expected result?
Yii should capture output and echo at 1 place. This is a better practice for:
- unit testing
- overriding
- debugging output behavior

### What do you get instead?
difficult controllable echo's in ActiveForms, GridViews and many more widgets

**Comment by klimov-paul** [comment]
Output buffer usage at `ActiveForm` can not be removed due to #11203

**Comment by dynasource** [comment]
I strongly doubt that there isnt a solution for removing the 'echos' in favor of 'return strings' statements. This is supported by the fact that Im already overriding all Yiis widgets which have this behavior, without having any issues.

**Comment by samdark** [comment]
That's OK to prefer returns where possible.

**Comment by cebe** [comment]
there are two types of widgets:

1. widgets that surround some content with begin() and end() and optionally modify it like e.g. `Spaceless`, `ActiveForm`, `FragmentCache`, `ContentDecorator`. These are designed to work with output buffering for the content they work with.
2. Widgets that only provide some HTML output they render. These are fine with returning things in run() without using ob_*.

I have made the implementation in yii already consistent about this on the 2.1 branch: https://github.com/yiisoft/yii2/commit/98ed490c3d0f0c80072bdb11e0937089c6e78cca

**Comment by cebe** [comment]
related: #10771

**Comment by dynasource** [comment]
great! Thanx!

**Comment by cebe** [comment]
does that solve the issue?

**Comment by dynasource** [comment]
it does if the inits() are captured & the bootstrap widgets are part of this fix.

**Comment by cebe** [comment]
> the inits() are captured

what do you mean with that?

will check bootstrap later

**Comment by dynasource** [comment]
I see that its fixed in 2.1. Great work.
