### ISSUE TITLE
Active Record join with relation and asArray() issue

### ISSUE THREAD

**Issue by ceovishnu** [yiisoft/yii2#11914]
whenever u use "joinwith" with "viaTable" and use asArray() it's give the Calling unknown method: yii\db\ActiveQuery::getDb() error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | Ubunu 15.10

**Comment by ceovishnu** [comment]
@qiangxue  is there a querytrait issue or u can't use asArray in via table callable function.

**Comment by samdark** [comment]
Please provide code on how you're using it exactly. Thanks!

**Comment by ceovishnu** [comment]
i have used below code.

`$query = EventMedia::find()->joinWith([
                        'event'=> function ($innerQuery) use($params) {
                            $innerQuery->andOnCondition('event.slug = :event_slug',[':event_slug'=>$params['event']]);
                            $innerQuery->viaTable('event_edition',['event_edition_id'=>'fk_event_edition_id'],function ($innerSubQuery) use ($params){
                                $innerSubQuery->andOnCondition('event_edition.slug = :event_edition_slug',[':event_edition_slug'=>$params['edition']]);
                            });
                        },
                        'eventmediatext', 'eventmediaface', 'eventmedialabel'])
                        ->select(['event_edition.thumb_root', 'event_media_text.fk_event_media_id', 'event_media_id', 'media_file_name', 'event_media_id', 'event_media.fk_event_edition_id', 'label_detection', 'face_detection', 'text_detection'])
                        ->where('event_media_id = :event_media_id',[':event_media_id' => $params['id']])->asArray()->all();
        echo '<pre>';
        print_r($query);
        exit;`

**Comment by cebe** [comment]
please also provide the relation definition of `event` relation.

**Comment by ceovishnu** [comment]
sure, below are relation defination

```
public function getEventedition() {
        return $this->hasOne(EventEdition::className(), ['event_edition_id' => 'fk_event_edition_id'])->select(['title', 'file_prefix', 'thumb_root', 'fk_event_id','event_edition_id','slug']);
    }

    public function getEvent() {
        return $this->hasOne(Event::className(), ['event_id' => 'fk_event_id'])->select(['title', 'file_prefix', 'event_id','slug'])->via('eventedition');
    }
    
    public function getEventmediatext() {
        return $this->hasMany(EventMediaText::className(), ['fk_event_media_id' => 'event_media_id'])
                        ->joinWith(['participant'])
                        ->select(['event_media_text_id', 'fk_event_media_id', 'label', 'is_bib_no', 'position_x', 'position_y', '.area_width', 'area_height']);
    }

    public function getEventmediaface() {
        return $this->hasMany(EventMediaFace::className(), ['fk_event_media_id' => 'event_media_id'])
                        ->joinWith(['participantface'])
                        ->select(['event_media_face_id', 'fk_event_media_id', 'position_x', 'position_y', 'area_width', 'area_height', 'detection_confidence', 'detector']);
    }
```

**Comment by ceovishnu** [comment]
@cebe any update regarding the same if u have.

**Comment by klimov-paul** [comment]
Duplicates #12311
