### ISSUE TITLE
ViewAction and urlManager suffix issue

### ISSUE THREAD

**Issue by esaesa** [yiisoft/yii2#11925]
### What steps will reproduce the problem?
 1- Enable suffix and pretty url in url manager

`'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'suffix' => '.html',

            // Disable index.php
            'showScriptName' => false,
            // Disable r= routes
            'enablePrettyUrl' => true,
            'rules' => array(
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ),
        ],`

2- Generate link using `'url' => [\yii\helpers\Url::to(["site/page", 'view' => 'about'])]`

3- Visit the generated link which will be http://localhost/site/page.html?view=about.html
with 
### What is the expected result?
About page about.php is rendered
### What do you get instead?
Error: The view file does not exist: C:\vhosts\backend\views\site\pages/about.html

### Additional info
If the suffix is "/" then the error will be The view file does not exist: C:\vhosts\backend\views\site\pages/about/.php
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6
| Operating system | Win7

**Comment by cebe** [comment]
> http://localhost/site/page.html?view=about.html

how did you get that link? The correct link is http://localhost/site/page.html?view=about and I have just verified that I get that link with your config.

**Comment by esaesa** [comment]
using `'url' => [\yii\helpers\Url::to(["site/page", 'view' => 'about'])]` while suffix is on

**Comment by esaesa** [comment]
I confirm the problem but this is happening but during the rendering of Nav Widget and actually inside the line `return Html::tag('li', Html::a($label, $url, $linkOptions) . $items, $options);` of public function renderItem($item).
I traced it till `$options['href'] = Url::to($url);` of public static function a and the url here is `/site/page.html?view=about`
But the return is /site/page.html?view=about.html

**Comment by cebe** [comment]
can you show the code that defines the widget? I am not able to reproduce the issue.

**Comment by esaesa** [comment]
Here is the code from view template file
`<?php
NavBar::begin([
    'brandLabel' => Yii::$app->params['appName'],
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar navbar-default navbar-static-top',
    ],
]);

$menuItems = [
    ['label' => 'Home', 'url' => ['/site/index']],
    ['label' => 'About', 'url' => [\yii\helpers\Url::to(["site/page", 'view' => 'about'])]],
    ['label' => 'Contact', 'url' => ['/site/contact']],
    ['label' => 'xxx', 'options' => ['href'=>'xxxxx']],

];
if (Yii::$app->user->isGuest) {
    $menuItems[] =['label' => 'Register', 'url' => ['/site/register']];
    $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']] ;
} else {
    $menuItems[] = [
        'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
        'url' => ['/site/logout'],
        'linkOptions' => ['data-method' => 'post']
    ];
    $menuItems[] =['label' => 'Control Panel', 'url' => ['/admin']];

}

echo Nav::widget([
    'options' => ['class' => 'navbar-nav '],
    'items' => $menuItems,
]);
NavBar::end();
?>`

**Comment by cebe** [comment]
> ['label' => 'About', 'url' => [\yii\helpers\Url::to(["site/page", 'view' => 'about'])]],

this is duplicated: 

you do either

```php
['label' => 'About', 'url' => \yii\helpers\Url::to(["site/page", 'view' => 'about']) ],
```

or 

```php
['label' => 'About', 'url' => ["site/page", 'view' => 'about'] ],
```

but not both.
