### ISSUE TITLE
Rest API Url Rule setting

### ISSUE THREAD

**Issue by shyandsy** [yiisoft/yii2#11928]
### What steps will reproduce the problem?

If I config url rule in this way, the rest api works. 
I can access the api by 
get http://api.shyclouds.com/frontend/web/dealer/view?access-token=<my_auth_token>
post http://api.shyclouds.com/frontend/web/dealer/view with username and password

```php
'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false, //使用restful时候，此参数必须为false，否则会404
            'showScriptName' => false,
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'dealer',
                ],

            ],
        ],
```
### What is the expected result?
but I wanna access the dealer/view in the way
post http://api.shyclouds.com/frontend/web/dealer
get http://api.shyclouds.com/frontend/web/dealer/(my_auth_token)

### What do you get instead?

according to the documentation:http://www.yiiframework.com/doc-2.0/guide-rest-routing.html
I try the url rule:
```php
'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false, //使用restful时候，此参数必须为false，否则会404
            'showScriptName' => false,
            'rules' => [
                [
                    'POST dealer' => 'dealer/index',
                    'GET dealer/<access-token:\w+>' => 'dealer/view',
                ],
            ],
        ],
```
I got error message said "Setting unknown property: yii\web\UrlRule::POST dealer"

If I set the url rules as follow
```php
'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false, //使用restful时候，此参数必须为false，否则会404
            'showScriptName' => false,
            'rules' => [
                'POST dealer' => 'dealer/index',
                'GET dealer/<access-token:\w+>' => 'dealer/view',
            ],
        ],
```
I got error message "Not Found (#404)"

 
### Additional info
http://www.yiiframework.com/doc-2.0/guide-rest-routing.html

I think you should add an example how to use the url rule:
```php
[
    'PUT,PATCH users/<id>' => 'user/update',
    'DELETE users/<id>' => 'user/delete',
    'GET,HEAD users/<id>' => 'user/view',
    'POST users' => 'user/create',
    'GET,HEAD users' => 'user/index',
    'users/<id>' => 'user/options',
    'users' => 'user/options',
]
```
| Q                | A
| ---------------- | ---
| Yii version      | 2
| PHP version      | 7.0.7
| Operating system | centos 7 x64

**Comment by cebe** [comment]
the first config should already give you what you want. Note that the controller names are pluralized automatically:  http://api.shyclouds.com/frontend/web/dealer ->  [http://api.shyclouds.com/frontend/web/dealer**s**](http://api.shyclouds.com/frontend/web/dealers)

see http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html#trying-it-out

**Comment by shyandsy** [comment]
First, by the configuration 1, when I access dealer/view by 
http://api.shyclouds.com/frontend/web/dealers/xxxxxxx       (xxxxxxx is token)
or 
http://api.shyclouds.com/frontend/web/dealer/xxxxx             (xxxxxxx is token)

I got 404 not  found error


Secondly, how to use the configuration 2?
```php
[
    'PUT,PATCH users/<id>' => 'user/update',
    'DELETE users/<id>' => 'user/delete',
    'GET,HEAD users/<id>' => 'user/view',
    'POST users' => 'user/create',
    'GET,HEAD users' => 'user/index',
    'users/<id>' => 'user/options',
    'users' => 'user/options',
]
```

**Comment by cebe** [comment]
putting the token into the URL is not a good idea, it should be sent via reqular auth methods such as HTTP Basic or Bearer auth. Please use the form for such questions.

**Comment by shyandsy** [comment]
according to the document (http://www.yiiframework.com/doc-2.0/guide-rest-authentication.html), there are three way to do the authentication. I just used second way.

I agree with you, it is not a good idea. but there must be a way to solve this problem
