### ISSUE TITLE
AttributeBehavior should be able to respect current attributes values

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#11923]
I would like to propose an improvement to an `AttributeBehavior` which will allow it to respect current attributes values. The behavior should update only non-empty attributes when a special flag like `skipUpdateOnFilled` is set to `true`. This won't break the BC if we set this flag to `false` by default.

Use-case: `Page` entity has three attributes: `meta_title`, `meta_description`, `meta_keywords`. We need to copy `title` to each of the attributes _only if_ they are empty. This will allow users to set some of them manually and to let the behavior fill the others.

The behavior should be defined like this:

``` php
[
    'class' => AttributeBehavior::className(),
    'skipUpdateOnFilled' => true,
    'attributes' => [
        self::EVENT_AFTER_VALIDATE => [
            'meta_title',
            'meta_description',
            'meta_keywords',
        ],
    ],
    'value' => function ($event) {
        return $event->sender->title;
    },
],
```

At the moment the `AttributeBehavior` won't allow you to achieve this behavior. The only workaround is to add three behaviors for each attribute with custom `value` which will check if the corresponding attribute is empty or not.

The problem can't be solved even by extending the base behavior without copy-pasting the `evaluateAttributes()` method.

**Comment by samdark** [comment]
@yiisoft/core-developers thoughts?

I think it could be useful.

**Comment by Kolyunya** [comment]
By the way the `SluggableBehavior::immutable` illustrates that the option I propose is *really* needed.

**Comment by SilverFire** [comment]
Good idea, could be implemented.

@Kolyunya, would you like to submit a PR?

**Comment by Kolyunya** [comment]
@SilverFire thank you! I've already did a pull request: #11969. It needs a review.
