### ISSUE TITLE
fileMode property doesn't apply for rotated files in logging framework

### ISSUE THREAD

**Issue by deadkrolik** [yiisoft/yii2#11922]
### What steps will reproduce the problem?

I have a config log section:

```php
$config = [
        ...
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                    'enableRotation' => true,
                    'fileMode' => 0666,
                    'logFile' => '@app/runtime/logs/yii_log.txt',
                ],
            ],
        ],
]
```

And after some actions I have several log files in logs directory:

> kd@kd:~/.../runtime/logs# ls -al
-rw-rw-rw- 1 www-data   www-data   2615 июля   8 13:04 yii_log.txt
-rw-r--r-- 1 www-data   www-data   2615 июля   8 13:04 yii_log.txt.1
-rw-r--r-- 1 www-data   www-data   2615 июля   8 13:04 yii_log.txt.2

### What is the expected result?

All log files should have the same 0666 permissions.

### What do you get instead?

Main log file has 0666 permissions, but not all rotated files.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      | 5.4.9
| Operating system | Ubuntu

**Comment by klimov-paul** [comment]
Resolved by commit 09b1fd47e071acdc9ec0c1988684d367fb067e02
