### ISSUE TITLE
I have some doubts about yii2 rbac

### ISSUE THREAD

**Issue by 1356611026** [yiisoft/yii2#11929]
I have some doubts about yii2 rbac.i Import '.\vendor\yiisoft\yii2\rbac\migrations\schema-mysql.sql'  and i find the column named type of auth_item table is added a normal index, and data type is integer (11).I don't know why.

firstly,because the column type only has two value: 1 and 2,why set it integer (11)? why not set it tiny integer?tiny integer is 1 byte,but integer 11 is 4byte.
secondly,as far as i know when there is many duplicate value in any column,even though has a  index but will not work!

do you have the same idea with me?please help me,thank you.

**Comment by shyandsy** [comment]
I guess that optimizes the sql like following
   select * from auth_item where type = TYPE_ROLE 
   or 
   select * from auth_item where type = TYPE_PERMISSION

**Comment by samdark** [comment]
Index is for queries like @shyandsy suggested.

> secondly,as far as i know when there is many duplicate value in any column,even though has a index but will not work!

I doubt that. Run EXPLAIN query and see that index is used.

Type isn't optimal indeed. It doesn't matter much because there aren't many rows but could be adjusted.
