### ISSUE TITLE
log \n problem

### ISSUE THREAD

**Issue by jiaowoxiaoqingba** [yiisoft/yii2#11924]
### program

>         print_r($info);
>         print_r($category);
>         if ($security == 'info')
>         {
>             Yii::info($info, $category);
>         }

### result

> 
> Array
> (
>     [trackid] => 86f1d8e23c01daa7095a712f16294520
>     [jdb_id] => 0
>     [@message] => app\components\Controller::beforeAction	array (
>   'server' => '::1',
>   'remote' => '::1',
>   'url' => 'http://localhost/paygent/web/index.php/wallet/loans-link-count-query',
>   'method' => 'POST',
>   'post' => 
>   array (
>     'begin' => '1466438400',
>     'end' => '1467889968',
>   ),
> )
> )
> payment-wallet-loans-link-count-query

### log

> {"trackid":"84cb257d9338f6b474171b7e00949dc8","jdb_id":"0","@message":"app\\components\\Controller::beforeAction\tarray (\n  'server' => '::1',\n  'remote' => '::1',\n  'url' => 'http:\/\/localhost\/paygent\/web\/index.php\/wallet\/loans-link-count-query',\n  'method' => 'POST',\n  'post' => \n  array (\n    'begin' => '1466438400',\n    'end' => '1467889968',\n  ),\n)","level":"info","category":"payment-wallet-loans-link-count-query","@timestamp":"2016-07-09T17:26:09.906+08:00","trace":[{"file":"D:\\WWW\\paygent\\util\\Logger.php","line":97,"function":"info","class":"yii\\BaseYii","type":"::"},{"file":"D:\\WWW\\paygent\\components\\Controller.php","line":201,"function":"trace","class":"app\\Util\\Logger","type":"::"},{"file":"D:\\WWW\\paygent\\components\\Controller.php","line":107,"function":"trace","class":"app\\components\\Controller","type":"->"}]}

### problem

\n and \ how to get rid of the log

**Comment by cebe** [comment]
> \n and \ how to get rid of the log

what do you mean with that? and where did you get the output from? Please show your logroute config.

**Comment by klimov-paul** [comment]
Closed unless more information provided.
