### ISSUE TITLE
Pjax duplicates parameters and converts space to +

### ISSUE THREAD

**Issue by DMGPage** [yiisoft/yii2#11921]
I have two problems with pjax and maybe someone can help me. I have one pjax form which with get params reload grid view. And grid view have pjax filters which reload grid again. So my problems is:

1. if I submit form it adds all params to url and convert space to "+" like this "?name=my+name". But now if I use grid filter it add new params to url and convert "+" to "?name=my%2Bname&search=test". So in result php will get "my+name" instead of "my name".

2. second problem is duplicate url params. If I use my form and grid filters many times, I get duplicate params in url like this "?name=&name=&search=&search=".

Any ideas how to fix any of these issues?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8

**Comment by agungsijawir** [comment]
Seems you do it wrong. I had this problem to but because my setup (both on widget and layout) is wrong. Please share your view code.

**Comment by DMGPage** [comment]
Here is my example:
[search.zip](https://github.com/yiisoft/yii2/files/356610/search.zip)

Tell me what I am doing wrong.

**Comment by agungsijawir** [comment]
@DMGPage

Your code was:
```php
<?= Html::beginForm('', 'get', ['class' => 'form-horizontal', 'id' => 'search-form', 'data-pjax' => true]); ?>
```

you need to specify target form-action in array `[]` if you want to target same as action. change to:
```php
<?= Html::beginForm([''], 'get', ['class' => 'form-horizontal', 'id' => 'search-form', 'data-pjax' => true]); ?>
```

Quite weird for me observing this behavior. Becase on docs it says `array|string` ([see here](http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#beginForm()-detail))

**Comment by DMGPage** [comment]
Why? Form will call Url:to() and from [documentation](http://www.yiiframework.com/doc-2.0/yii-helpers-baseurl.html#to%28%29-detail): "an empty string: the currently requested URL will be returned".

And how does your suggestion fix any of my problems with pjax?

**Comment by agungsijawir** [comment]
Have you try to use `['']` ?

**Comment by DMGPage** [comment]
Yes, and from, what I see, it fix duplicates parameters in url. Only problem, that I can not find any explanation, why [''] have different behaviour from ''. Even returned urls are equal, but with '' pjax duplicates params and with [''] will replace.

But first pjax problem remains. It still replace empty space with +.

**Comment by agungsijawir** [comment]
Is all fields empty?

From what I know, space will be converted to `+` based on URL Encoding.
http://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20
http://www.blooberry.com/indexdot/html/topics/urlencoding.htm

On my browser, Chrome & Edge works fine.

Chrome
![chrome](https://cloud.githubusercontent.com/assets/1901132/16758925/aa3eebd0-483e-11e6-9f0b-d01062a0792b.PNG)

![edge](https://cloud.githubusercontent.com/assets/1901132/16758960/cf6067b8-483e-11e6-8219-dee0f32ab171.PNG)

**Comment by DMGPage** [comment]
It is fine that space is converted to +. Problem is next time when pjax is called, because it replace + with "%2B" and now $_GET param has value "+" instead of space.

1. enter in form "first name" and submit form: "?first_name=first+name&last_name=&email=&address=";
2. enter in grid filter phone and pjax change url to: "?phone=123&first_name=first%2Bname&last_name=&email=&address=";
3. echo $_GET['first_name']; returns "first+name".

**Comment by agungsijawir** [comment]
Works fine:
![Works fine](https://cloud.githubusercontent.com/assets/1901132/16761305/c0f1e9da-4849-11e6-8f3d-6bd725f6d687.PNG)

---

Consider using `Yii::$app->request->getQueryParams();` instead `$_GET`
I think your issue now is not related by Yii code, but rather than your system environment setup / settings.

**Comment by DMGPage** [comment]
Yes this change everything :)
`public function getQueryParams()
    {
        if ($this->_queryParams === null) {
            return $_GET;
        }
        return $this->_queryParams;
    }`

Btw in my example I use "Yii::$app->request->get('first_name')" and result is wrong:
![pjax](https://cloud.githubusercontent.com/assets/3495137/16761874/d107f950-482a-11e6-8a56-6401ab614e15.png)

And from your result I see that you did only 1. step and did not searched in grid. Problem only appear after second pjax call when it takes current url and add new params.

**Comment by agungsijawir** [comment]
I did not only one or two pjax call, but more than that. The result are same, works perfect.

![edge](https://cloud.githubusercontent.com/assets/1901132/16762734/0bd88c3c-4850-11e6-9484-47613da36340.PNG)

**Comment by DMGPage** [comment]
Wait what environment settings should I check? I did clean yii installation and I still have same problem.

**Comment by agungsijawir** [comment]
What about Encoding you use on your browser, UTF-8 or what?
What your regional settings, if you use Windows(tm) OS?
php version?
yii2-pjax version?
can you use latest yii2 version, yii2 v2.0.9?
kindly submit your output `phpinfo()` result page. Also, please run requirements.php in your yii2 installations.

See image below, either by `+` or `%20`, the result are same on me.
![edge](https://cloud.githubusercontent.com/assets/1901132/16764957/91154128-485b-11e6-81d9-bfdd10a4f405.PNG)

**Comment by DMGPage** [comment]
_What about Encoding you use on your browser, UTF-8 or what?_
Yes, utf-8

_What your regional settings, if you use Windows(tm) OS?_
Windows 7 - language for non-unicode programs: Latvian (Latvia)

_php version?_
[info.pdf](https://github.com/yiisoft/yii2/files/360783/info.pdf)

_yii2-pjax version?_
version what comes with yii 2.0.9

_On your dev-tools (chorme, edge, mozilla), Request & Response Headers, especially for pjax / xhr request._
[request.pdf](https://github.com/yiisoft/yii2/files/360905/request.pdf)

_Please run requirements.php in your yii2 installations._
[requirements.pdf](https://github.com/yiisoft/yii2/files/360815/requirements.pdf)

_See image below, either by + or %20, the result are same on me._
In my case + is replaced with %2B and it happens in firefox and chrome.

**Comment by agungsijawir** [comment]
Can you change your Regional Settings to US?

I did test on Firefox too, but behavior was same.
![edge](https://cloud.githubusercontent.com/assets/1901132/16796381/a9d65a38-490c-11e6-8673-c822aad897f4.PNG)

**Comment by DMGPage** [comment]
Wait you have name in form and name in grid? Of Course you will have different result. Could you test with my view file? Or at least use different names and follow steps described above.

_Can you change your Regional Settings to US?_
![linux mint 17 3](https://cloud.githubusercontent.com/assets/3495137/16798032/c81e9a4c-48f2-11e6-9989-9c148c51ebdb.png)

**Comment by agungsijawir** [comment]
here
https://github.com/yiisoft/yii2/issues/11921#issuecomment-231980458

**Comment by DMGPage** [comment]
Here #11921 you do not have grid filter result combined with form params. Your url contains only form fields and this request works for me too. But if then I enter something in grid filter, data is changed. Well everything you can see in request.pdf. There is 2 requests: 1. after form submit; 2. after grid filter.

**Comment by agungsijawir** [comment]
Ah, I see...

To produce this issue:
- Use `Html::beginForm()` and `Html::endForm()`, put an input box (named it `first_name`) and wrap the form with pjax.
- Write GridView with filter enabled and wrap it with pjax.
- Perform submit form with space on textbox, i.e `this is test`. Url with get params will change to `this+is+test`.
- Perform filter on GridView filter (i.e on `Something` field on `MyModel` model) with space on string field, i.e. `find a thing`, enter.
- Url will changed to `controller/action?MyModel[Something]=find+a+thing&first_name=this%20is%20test` . When dump `\Yii::$app->request->get('first_name')`, output will be `find+a+thing`.

note:
- If form model and GridView searchModel is different, issue is reproduced. Even if using Model that extends from `\yii\base\Model` for use in search form.
- Both ActiveForm and Html::beginForm() 
- Yii2 v2.0.9
- php5.5.37 & php5.6.181+deb.sury.org~trusty+1

**Comment by agungsijawir** [comment]
Can you use same model as GridView on your search form?

**Comment by DMGPage** [comment]
Yes, and result not changed. Here is my test view, model and controller:
[search.zip](https://github.com/yiisoft/yii2/files/361194/search.zip)

**Comment by SilverFire** [comment]
![ezgif-311761952](https://cloud.githubusercontent.com/assets/4499203/19412793/f43d9a6a-9325-11e6-890d-0b83e2903e2e.gif)

Failed to reproduce

**Comment by DMGPage** [comment]
Test is performed differently than I described and @agungsijawir reproduced. From your gif I can see that you @SilverFire did not entered any text in first form. Please read accurately @agungsijawir [comment](https://github.com/yiisoft/yii2/issues/11921#issuecomment-232306765) how to reproduce this issue.

**Comment by SilverFire** [comment]
@DMGPage that you for pointing out my mistake
