### ISSUE TITLE
Error Exception while installing Yii 2.0.9

### ISSUE THREAD

**Issue by abhij89007** [yiisoft/yii2#11936]
### What steps will reproduce the problem?
I tried installing the latest version using the command "php composer.phar create-project yiisoft/yii2-app-advanced advanced 2.0.9", but it thrown an exception while installing the dependencies. 

### What is the expected result?
It should have installed all the dependencies. Attaching the screenshot of the error. 

### What do you get instead?
![2016-07-12_0244](https://cloud.githubusercontent.com/assets/15982920/16747006/998aba30-47da-11e6-8167-b61c9e93857a.png)

Does this mean i should install other version, or am i missing something?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | Windows

**Comment by cebe** [comment]
make sure you use the latest version of composer and the asset plugin

**Comment by abhij89007** [comment]
I had latest versions for both, but it still didn't worked. Same error. Just to same time, i went ahead to install using .tar file.
Thanks.
