### ISSUE TITLE
a link in Pjax Gridview with POST not passing data-params to to pagination of nested gridview

### ISSUE THREAD

**Issue by indicalabs** [yiisoft/yii2#11937]
### What steps will reproduce the problem?

A Gridview column in a Pjax container has a link with post method, and post parameters, that opens a second gridview with pagination.
The second gridview's pagination has empty parameters, 
### What is the expected result?

The second gridview pagination should get the post parameters,
### What do you get instead?

No post parameters passed
### Additional info

the generated link from the first Gridview column
`<a data-params="{"sid":"576d9f5f9486b100052f4f62"}" data-pjax="" data-method="post" href="/msgs/msgs/open-msg.html?id=576da0629486b100052f4f65”>Some text here...</a>`

Pjax container's options `
'enablePushState' => false,
    'clientOptions' => ['method' => 'POST']
` is making the below link's method as POST, but data-params from the above link is not passing.

The generated link from the pagination of the second gridview that was opened with the above link
`<a data-page="1" href="/msgs/msgs/open-msg.html?id=576da0629486b100052f4f65&page=2&per-page=4">2</a>`

| Q | A |
| --- | --- |
| Yii version | dev-master |
| PHP version | 7 |
| Operating system | Linux |

**Comment by indicalabs** [comment]
I think its all about pagination to support POST parameters?
if I set params like below, they are appearing in the POST link as GET params.

`$dataProvider->pagination->params = ['s_id' => $sid];`

**Comment by dynasource** [comment]
this is a too specific usecase (integration of 3 widgets) to support. Thanks for sharing though. If you found a solution already, plz feel free to do a PR.

**Comment by solicomo** [comment]
I encounter this problem, too.

Setting params of pagination does not work for me.

And I found a relative discussion: https://github.com/yiisoft/yii/issues/169

Making pagination support POST makes sense for me.

So far, GET has to be used if sorting, filter, and pagination are working together.

**Comment by srakl** [comment]
is there  a solution for this? pagination doesn't seem to work with POST.

```
 <?php Pjax::begin([
        'id'=>'pjax-reports', 
        'timeout'=>false, 
        // 'enablePushState' => true, 
        'clientOptions' => [
            'method' => 'POST', 
            'url' => Url::to(['/test/default/index'])
            ]
        ]); 
    ?>
```

if i don't put  `  'url' => Url::to(['/test/default/index'])` the pagination works. but the filter doesn't. and vice versa. Any ideas?
