### ISSUE TITLE
Cannot generate inline radioList 

### ISSUE THREAD

**Issue by farhanz95** [yiisoft/yii2#11934]
I have been trying to use inline codes to make my codes appear more neatly, Without inline method it would look like this
![image](https://cloud.githubusercontent.com/assets/16377745/16735050/321bd75a-47ba-11e6-89e1-8261f2657658.png)
And this is my current code
![image](https://cloud.githubusercontent.com/assets/16377745/16735128/8ef81fce-47ba-11e6-8ab4-bc8f172fb23d.png)

Which is not good because I want the radio input form list to appear line by line

But when I try  to insert inline code 

![image](https://cloud.githubusercontent.com/assets/16377745/16735182/c412cc7c-47ba-11e6-9be9-6db280bb2026.png)

, error as below will occur

![image](https://cloud.githubusercontent.com/assets/16377745/16735200/d1162f0e-47ba-11e6-843e-bd6c1ca6375d.png)

![image](https://cloud.githubusercontent.com/assets/16377745/16735207/d619e856-47ba-11e6-990f-8164866d3eae.png)

I have tried everything, and it still says Calling unknown method: yii\widgets\ActiveField::inline()

Below I attatch with the coding of the use file "yii\widgets\ActiveField"
** I have try Ctrl+F for inline but no result came out **

![image](https://cloud.githubusercontent.com/assets/16377745/16735268/0abadc1e-47bb-11e6-948e-b3b62ccec663.png)

This problem have been haunting me for the past month, I have tried researching and done everything I can do to solve this problem, searching everything of Yii method and function, deep Google Search but still cannot solve this problem, I even revert back to the Yii basic and advance template default settings but the error still comes out, I hope that someone can help solve this problem or give other solution on how to produce inline radioList

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/issues/4565#issuecomment-231760592
