### ISSUE TITLE
MigrateController uses hyphens in auto-generated FK/IDX names

### ISSUE THREAD

**Issue by VojtechH** [yiisoft/yii2#11935]
### What steps will reproduce the problem?

There are hyphens in Foreign Key and Index names auto-generated by the MigrateController (since Yii 2.0.8).

These names are used when the "create table" migration is generated using the MigrateController (specifically by the generateMigrationSourceCode method).

It can cause problems. For example, when using Propel ORM.

MySQL accepts only underscores in unquoted schema object identifiers: http://dev.mysql.com/doc/refman/5.7/en/identifiers.html

### What is the expected result?

Instead of hyphens I would suggest to use underscores in the identifiers name template.

For example:
`'idx' => $this->generateTableName("idx_$table_$column"),`
`'fk' => $this->generateTableName("fk_$table_$column"),`

It will be necessary to change DOCS as well. It contains examples with this naming.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8

**Comment by samdark** [comment]
> It can cause problems. For example, when using Propel ORM.

Why? Does Propel use these unescaped?

**Comment by samdark** [comment]
Personally I'm using both `-` and `_` in key names for years without any issues.

**Comment by VojtechH** [comment]
> Why? Does Propel use these unescaped?
I have this issue with Propel reported from a fellow developer. I'll get back with more info.

I'm usually trying to avoid names that requires quotation just to be on a safe side (even when I use quotation all the time by myself).

**Comment by VojtechH** [comment]
I have investigated the details. When Propel validates the DB schema, it allows only characters that MySQL docs lists as "permitted in unquoted identifiers".

Here is the link to the file used for the validation (and link to the specific rule):
https://github.com/propelorm/Propel2/blob/master/resources/xsd/database.xsd#L216

I have also searched through recommendation regarding naming convention for FKs and basically all sources I found suggested some kind of pattern with only underscores used.

At first I liked the pattern with hyphens used in 2.0.8 as it was easier to read. But now as I see it's not so conventional and can cause problems, I'm rather switching back to underscores.

**Comment by bizley** [comment]
I'm using both hyphens and underscores in foreign keys without problems but it looks like in general the name should follow [a-z0-9_]+ pattern - at least it is common agreement on the internet and I haven't found any good explanation on this. I think it would be safer to remove hyphens from all generated names just in case,

**Comment by samdark** [comment]
OK. I have no idea why they've introduced such a limitation. Never experienced any problems using `-`.

Since we're often using `_` for column and table names and these appear in FK/IDX names, not using `-` would be result into a big mess where it's hard to distinguish if part separated by `_` is name of the table or name of the column.

**Comment by bizley** [comment]
I've read about identifiers for MySQL, MSSQL, MariaDB, and PostgreSQL, and everywhere hyphen is allowed in quoted identifiers. It looks like Propel makes it more restrict than it should.

**Comment by samdark** [comment]
Yeah. I don't think it worth restricting it in Yii.

**Comment by VojtechH** [comment]
Ok. Thank you for the consideration.
