### ISSUE TITLE
Active Query joinWith Problem

### ISSUE THREAD

**Issue by jai3232** [yiisoft/yii2#11939]
### What steps will reproduce the problem?

I tried to run this active query  

Personal::find()
    ->select(['personal.id_personal AS value', 'CONCAT(personal.nama, \' (No. KP: \', personal.no_kp, \')\') AS label', 'personal.id_personal AS id'])
    ->joinWith('personalPerjawatans')
    ->orderBy('nama')
    ->asArray()
    ->all();

### What is the expected result?

I got an error stated that "Undefined index: id_personal" related to file in C:\wamp\www\yii2\eprofiling2\vendor\yiisoft\yii2\db\ActiveRelationTrait.php . line 456

### What do you get instead?

When I removed 'AS value' from the select function, there is no error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 
| PHP version      | 
| Operating system |

**Comment by Alex-Code** [comment]
You can alias columns using `key`=>`value` pairs.
```
->select(['id' => 'personal.id_personal'])
```

**Comment by klimov-paul** [comment]
> I got an error stated that "Undefined index: id_personal"

You should either disable relation fetching:

```php
->joinWith('personalPerjawatans', false)
````

Or add junction field `id_personal` in your select statement.
