### ISSUE TITLE
Default value from model after Gii generator

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#11946]
make auto-generated fields in the model , as well as Auto-mapping in the view

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system |

**Comment by des1roer** [comment]
and default value of text column is null not empty string

**Comment by samdark** [comment]
Please elaborate.

**Comment by klimov-paul** [comment]
Closed, unless more information provided
