### ISSUE TITLE
 Yii2 - Where can I store common resources

### ISSUE THREAD

**Issue by sherinjose** [yiisoft/yii2#11944]
Hi all,

Now I am using `Yii2 - advanced` version for developing my application. In that application, some data like images is adding from the `backend` area. Here I need to access those data from the `frontend` also. So I need to keep those data in a common shared sector. I know there is a common directory in between `backend` and `frontend` where we can place the common configurations, models, etc. My question is whether I can store my shared resources in that common folder or in any other manner.

Any help will be appreciated. Please help

**Comment by Alex-Code** [comment]
Please use the forums for questions, Git is for issue tracking.
