### ISSUE TITLE
All triggers do not work when the method updateAttrigutes is used

### ISSUE THREAD

**Issue by Razzwan** [yiisoft/yii2#11957]
### What steps will reproduce the problem?
use method of ActiveRecord `updateAttributes($attributes)`

### What is the expected result?
Triggers (before save, after save) are triggered

### What do you get instead?
All triggers are sleep

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.6
| Operating system | ubuntu 16.04

**Comment by klimov-paul** [comment]
This is expected behavior.
