### ISSUE TITLE
Yii2 RESTful custom response is being ignored

### ISSUE THREAD

**Issue by kynamar** [yiisoft/yii2#11951]
## What steps will reproduce the problem?
I am trying to use the following custom response in my main.php config file(api folder)

```php
 'response' => [
            'class' => 'yii\web\Response',
            'on beforeSend' => function ($event) {
                $response = $event->sender;
                if ($response->data !== null && Yii::$app->request->get('suppress_response_code')) {
                    $response->data = [
                        'success' => $response->isSuccessful,
                        'data' => $response->data,
                    ];
                    $response->statusCode = 200;
                }
            },
                ],
```

### What is the expected result?
When I access http://localhost/MyProject/api/web/v1/colors?per-page=2, instead of 

```json
{ status:true, data:[{"id":1,"color_name":"Red","color_code":"#FF0000","active":1},{"id":2,"color_name":"White","color_code":"#FFFFFF","active":1}]} 
```

I get only
```json
[{"id":1,"color_name":"Red","color_code":"#FF0000","active":1},{"id":2,"color_name":"White","color_code":"#FFFFFF","active":1}]
```

What could cause this problem ?
Thank you in advance.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |   2.0.8
| PHP version      |   5.5.12
| Operating system |

**Comment by samdark** [comment]
What's in your `$response->data` and `$_GET`?

**Comment by kynamar** [comment]
How can I get the values for this variables ? 
I use something like this in ColorController 
`public function afterAction($action, $result) {
        var_dump($_GET);
        var_dump(\Yii::$app->response->data);
        return parent::afterAction($action, $result);
    }`
and i get the result : `array(1) {
  ["per-page"]=>
  string(1) "2"
}
NULL`
but I do not know if this is the correct way to get that values. I am a beginner in php and Yii programming.

Thank you.

**Comment by samdark** [comment]
Well, you don't have `suppress_response_code` in your GET so it's expected that code in `on beforeSend` isn't reached.
