### ISSUE TITLE
how to use filter with each in model rules?

### ISSUE THREAD

**Issue by sahifedp** [yiisoft/yii2#11952]
Hi 
I want apply `HtmlPurifier` filter  to array field.

I trid it:
`[['tag_names'], 'each', 'filter' => ['filter' => '\yii\helpers\HtmlPurifier::process']]`

but in get this error:
`Setting unknown property: yii\validators\EachValidator::filter` error

any Idea?
thanks.

**Comment by sahifedp** [comment]
I think `each` doesn't have the `filter property`, So It must be changed to enhancement issue.

**Comment by samdark** [comment]
```php
array_walk(function($row) {
});
```

**Comment by VirtualRJ** [comment]
As far as I understand the validator. The each validator doesn't need a filter property as you define the filter rule in the rule property. So instead of:
```php
[['tag_names'], 'each', 'filter' => ['filter' => '\yii\helpers\HtmlPurifier::process']]
```
I think it should be:
```php
[['tag_names'], 'each', 'rule' => ['filter' => '\yii\helpers\HtmlPurifier::process']]
```

**Comment by samdark** [comment]
@VirtualRJ is correct.

**Comment by omzy83** [comment]
If you want to use the `filter` validator with `boolval`, it needs to be done like this:

`[['attribute'], 'each', 'rule' => ['filter', 'filter' => 'boolval']],`
