### ISSUE TITLE
Code style: self for private methods

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#11955]
The [code style](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#self-vs-static) says: "accessing private static properties MUST be done via self: self::$_events". This should be extended to private methods too, no? It doesn't make sense to call a private method with static, you made it private because you don't want it to be overridden, but if you call it with static, it can be overridden:

```php
<?php

error_reporting(-1);

class Base
{
    private static function bar()
    {
        echo "base bar";
    }
    
    public static function foo()
    {
        static::bar();
    }
}

class Child extends Base
{
    public static function bar()
    {
        echo "child bar";
    }
}

Child::foo();
```

This will output "child bar": http://sandbox.onlinephpfunctions.com/code/9449f2f694febed6008525b59b2d007b55b227ba

**Comment by samdark** [comment]
In order to call private method with `_` you should name it with `_` which we don't want. Actually, for 2.1 I'd like to change code style to not using `_` for private properties.

**Comment by nkovacs** [comment]
I think you misunderstood something. I wasn't talking about naming private methods, but calling them with `self` vs `static`. According to the current rules, it should be `static`, because they're not in the exceptions, which doesn't make sense.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/11956

**Comment by samdark** [comment]
Ah, that. Well, it doesn't make sense to force either `static` or `self` because these are totally different and should be used according to the case you're trying to solve.

**Comment by nkovacs** [comment]
If you look at my example, I think that's a mistake.
If the methods were not static, it would output "base bar": http://sandbox.onlinephpfunctions.com/code/a59083057540007d3310645307509e899e7d0a97
So I think it makes sense to forbid static in this case.

**Comment by samdark** [comment]
It's not a mistake. There are cases when late static binding is not desired.

**Comment by nkovacs** [comment]
Well, that's what I'm saying. This is such a case, but the current rule requires you to use static here.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/466fc9db32be0f7432760a96d512246f6584e39d
