### ISSUE TITLE
Develope Yii2 Framework plugin in PhpStorm

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#11964]
the large framewrok like symfony,... have pluign for ide like netbeans, phpstrom.
netbeans plugin [https://github.com/nbphpcouncil/nb-yii2-plugin](https://github.com/nbphpcouncil/nb-yii2-plugin)
develope yii2 plugin for phpstorm

**Comment by samdark** [comment]
We don't have resources to do it by core team members.

There's one btw. so you can contribute to it: https://github.com/cmazx/yiistorm
