### ISSUE TITLE
New validation rule in models?

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2#11968]
What you think about new class rule in models?

Example:
```
public function rules()
{
    return [
        [
            ['exampleField'], 'integer'
        ],
        [
            ['items'], '\Vendor\library\SuperItemModel' // model for each item validation
        ]
    ];
}
```

I know about [EachValidator](https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-core-validators.md#yiivalidatorseachvalidatoreach-) and may be use it.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7 x64
| Operating system | Windows 10

**Comment by fernandezekiel** [comment]
i don't quite understand what you want here, is the items property containing an array of models?

**Comment by Alex-Code** [comment]
Sounds like they wan't to validate against a relation.

**Comment by springimport** [comment]
[Here](https://github.com/springimport/magento2-swagger-api/blob/master/lib/Model/Body4.php#L59) is an example of validation.

**Comment by klimov-paul** [comment]
Will not be supported.
You can use an extension for this, like following one:
https://github.com/yii2tech/embedded
