### ISSUE TITLE
Generate dropDownList from a boolean field in a model 

### ISSUE THREAD

**Issue by bernhar** [yiisoft/yii2#11962]
I have a form. In this form I want to show a dropDownList (instead of a checkbox), as I want to know if it is blank (null), or answered (true or false). Using the following code will always bring me the PROMPT option when FALSE.

```
<?= $form
    ->field($model, 'bln_choice')
    ->dropDownList(['1' => 'Yeah!', '0' => 'Nope!'],['prompt'=>'Chose, dude!'])
?>
```
Is there a way to do so in a native fashion?
Thanks

**Comment by sokollondon** [comment]
Same problem. It helped:

```
echo Html::activeLabel($model, 'is_active');
echo Html::dropDownList('Post[is_active]', ($model->is_active===false ? '0' : $model->is_active), [false=>'No', true=>'Yes'], ['class'=>'form-control']);
```
