### ISSUE TITLE
ActiveField::checkbox() - There's no way to force check/uncheck.

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii2#11960]
### What steps will reproduce the problem?

Having below code:  

``` php
<?= $form->field($model, 'categories[]', ['options' => ['class' => 'xform-group']])->checkbox([
    'uncheck'      => null,
    'class'        => 'chk',
    'id'           => 'model-category_id_' . $category->id,
    'label'        => $category->name,
    'labelOptions' => ['class' => 'chk full-width'],
    'template'     => '{input}{beginLabel}{labelTitle}{endLabel}{error}',
    'value'        => $category->id,
    'checked'      => true,
]);?>
```
### What is the expected result?

I expect to see the checkbox checked.  
### What do you get instead?

The checked option is ignored.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 7.0.8 |
| Operating system | CentOS 7 |

**Comment by w3lifer** [comment]
> This method will generate the "checked" tag attribute **according** to the model attribute **value**.

[Source](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#checkbox()-detail)

This means the following:

``` php
$model->myAttribute = true;

echo $form->field( $model, 'myAttribute')->checkbox(); // checked ckeckbox
```

**Comment by twisted1919** [comment]
@w3lifer - That still does not fix the issue i am referencing. It works fine for attribute directly, but if your attribute is an array then it does not work anymore. In 1.1.x versions you could set the checked attribute manually, this should be the case here too, so that my above use case to work properly.

**Comment by cebe** [comment]
how should a checkbox work for an array valued attribute?

**Comment by cebe** [comment]
maybe what you want is `activeCheckboxList`?

**Comment by cebe** [comment]
but to fix this issue we could set `checked` option only if it does not exist already here: https://github.com/yiisoft/yii2/blob/0ac161b69d77db3179cf17388aedd8df35246079/framework/helpers/BaseHtml.php#L723

**Comment by desaikalpesh34** [comment]
still not working
`<?php echo $form->field($model, "is_listable[$contentModel->id]")->checkbox(['label'=>'','class'=>'content_is_listable_class','checked'=>true]); ?>`

this must be checked by default render but not working.
