### ISSUE TITLE
Guide, grid view forbidden

### ISSUE THREAD

**Issue by TomaszKane** [yiisoft/yii2#11978]
Hi, tiny problem here:

### What steps will reproduce the problem?
1. Go to http://www.yiiframework.com/doc-2.0/guide-README.html
2. type "grid view" in search field
3. click on "Class yii\grid\GridView"

### What is the expected result?
Class GridView documentation

### What do you get instead?
403 Forbidden

**Comment by SilverFire** [comment]
Failed to reproduce. Could be a temporary issue

**Comment by rob006** [comment]
The same situation for http://www.yiiframework.com/doc-2.0/guide-db-migrations.html right now.
