### ISSUE TITLE
Yii2. Saving $form (widget/ActiveForm) in Session

### ISSUE THREAD

**Issue by evalenzuela** [yiisoft/yii2#11970]
I am trying to save $form (After doing $form = ActiveForm::begin(())

```
$fofArgs = [
           'form' => $form,
        ];
 Yii::$app->session->set('fofArgs', $fofArgs);
```
Then I go to a different controller/action:

`var_dump(Yii::$app->session->get('fofArgs'));`

But it prints null. I tried serializing before adding it to the session but it returns an error, "Closures can not be serialized", so maybe the null result has to do with closures too? 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |   2
| PHP version      |  5.6
| Operating system |  OSX

**Comment by Alex-Code** [comment]
Can you serialize the config array you create the form with instead?

**Comment by KostyaChoporov** [comment]
Why you trying save ActiveForm into session? "Closures can not be serialized" - expected result.

**Comment by evalenzuela** [comment]
Hi Guys, thanks for answering. Yes I have reviewed and Closures can not be serialized, and that is how PHP works, althought you can use SuperClosure but that works only if you try to serialize directly a closure and not an object which has closures in it.

I have a widget inside a form, which through Pjax adds fields dinamically, so I am trying to pass $form to be able to create those dynamic fields from $form.

**Comment by samdark** [comment]
Yes, it's not possible to save closures so I'd store config representation of the form as @Alex-Code suggested.

**Comment by spoonmediahh** [comment]
@samdark and how you get the config representation of the form?
