### ISSUE TITLE
Link models just Insert into DB without performing behaviors of related models

### ISSUE THREAD

**Issue by amelkikh** [yiisoft/yii2#11971]
When linking models are not performed the behaviors of the model for the associated relation.

### What steps will reproduce the problem?
For example:
 Model Provider, Model Game, Model ProviderGame.
Provider relation  hasMany "games" via table ProviderGame.
After successful validation I saved Game model and then link Game to Provider through relation "games".
### What is the expected result?
Behavior for the ProviderGame model will be performed , eg. TimestampBehavior, rules etc.
### What do you get instead?
Instead of working with the model happens insert record into DB by commandBuilder

https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1232
```
/* @var $viaTable string */
static::getDb()->createCommand()
    ->insert($viaTable, $columns)->execute();
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.7
| PHP version      |  5.6
| Operating system |  Linux Mint Rosa / Cinnamon (64-bit)

**Comment by klimov-paul** [comment]
This is expected behavior. You should not use `link()` method in case you need to run validation on junction model - in this case model should be populated and validation manually.
