### ISSUE TITLE
yiiActiveForm beforeValidate and afterValidate incorrect triggering

### ISSUE THREAD

**Issue by githkim** [yiisoft/yii2#11972]
### What steps will reproduce the problem?
After fix issue #10681, event `beforeValidate` will called after blur on any field with enabled client validation. But `afterValidate` will not called. For example, this code does not work now:
```javascript
    // Form submition with enabling/disabling submit-button to prevent request multisend
    $(document).on('beforeValidate', 'form', function (event, messages, deferreds) {
        console.log('beforeValidate');
        $(this).find('[type=submit]').attr('disabled','disabled');
    }).on('afterValidate', 'form', function (event, messages, errorAttributes) {
        console.log('afterValidate');
        if (errorAttributes.length) {
            alert('Check form errors!');
            $(this).find('[type=submit]').removeAttr('disabled');
        }
    }).on('beforeSubmit', 'form', function (event) {
        console.log('beforeSubmit');
        $(this).find('[type=submit]').attr('disabled','disabled');
    });
```
In result, button will disabled after blur on first field with clientValidationRule.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  5.5.30
| Operating system | Windows 7, Ubuntu 14.04

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/pull/11994

check this code

**Comment by githkim** [comment]
@lynicidn thanks! I've checked this pull request. It works on right way!

**Comment by samdark** [comment]
PR merged.

**Comment by gmalpeli** [comment]
Sorry my english. Problems whit ajax css validate:  In a form, when a field is filled with a valid value, the div style of this field , change to "form-group..... has-success",  With this change, all fields in the form, change the div style, to "form-group..... has-success",  So all are green...

**Comment by pstddc** [comment]
@gmalpeli it's not related issue?

это же не связано с этим багом? дивы никто не трогал, меняли клиентскую валидацию в яваскрипте

**Comment by SilverFire** [comment]
The issue is reopened since the accepted PR caused wrong behavior

**Comment by SilverFire** [comment]
See #12069

**Comment by SilverFire** [comment]
Fixed by https://github.com/yiisoft/yii2/commit/418b27326c8753e1224080a958930550ff4d11ac
