### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#11973]
In http://www.yiiframework.com/doc-2.0/guide-input-forms.html#creating-forms

```php
// allow multiple files to be uploaded:
echo $form->field($model, 'uploadFile[]')->fileInput(['multiple'=>'multiple']);

// allow multiple items to be checked:
echo $form->field($model, 'items[]')->checkboxList(['a' => 'Item A', 'b' => 'Item B', 'c' => 'Item C']);
```

**PROBLEM:** Periodically it (`'items[]'`) causes confusion for some people.

### Ex1 with items[]
```php
$model = new \yii\base\DynamicModel(['items' => ['a', 'b']]);
$form = \yii\widgets\ActiveForm::begin();
echo $form->field($model, 'items[]')->checkboxList(['a' => 'Item A', 'b' => 'Item B', 'c' => 'Item C']);
$form::end();
```
![image](https://cloud.githubusercontent.com/assets/874234/16908987/179e6d98-4cd8-11e6-8f15-cd5857fcd381.png)
name of input is correct but **default value not setted.**
<hr>
### Ex2 without items[]
```php
$model = new \yii\base\DynamicModel(['items' => ['a', 'b']]);
$form = \yii\widgets\ActiveForm::begin();
echo $form->field($model, 'items')->checkboxList(['a' => 'Item A', 'b' => 'Item B', 'c' => 'Item C']);
$form::end();
```

![image](https://cloud.githubusercontent.com/assets/874234/16909031/7d99c58e-4cd8-11e6-9e78-c695be9735a5.png)

name of input is correct and **default value setted.**

Need to have finally add the sample code to set the initial values and the correct the documentation
(checkboxlist could be remove from the example for `items[]`).

Rel https://github.com/yiisoft/yii2/issues/11960 https://github.com/yiisoft/yii2/issues/11533 https://github.com/yiisoft/yii2/issues/7697 https://github.com/yiisoft/yii2/issues/7456

**Comment by SilverFire** [comment]
Reverted because of BC breaking. See #12407 for further information.
