### ISSUE TITLE
TimestampBehavior $value null on EVENT_BEFORE_UPDATE got UNIX Timestamp

### ISSUE THREAD

**Issue by badyusuke** [yiisoft/yii2#11995]
All my others models has a default TimestampBehavior configuration and works properly, with 'created_at' and 'updated_at' values using new \yii\db\Expression('NOW()').
But i have a specific model that need set an 'updated_at' value just when it triggers an ActiveRecord::EVENT_BEFORE_UPDATE event. I'm trying the code below and getting an Unix Timestamp value on my 'resolved_at' database field.

I already searched some issues but i really dunno how fix it. On docs, it's say to refresh model, but where in the code i have to put it? Could you help me, please?

Sorry for my bad english ;(

### What steps will reproduce the problem?

On ActiveRecord Model
```
  public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    static::EVENT_BEFORE_INSERT => ['created_at'],
                    static::EVENT_BEFORE_UPDATE => ['resolved_at'],
                ],
                'value' => new Expression('NOW()'),
            ],
    ]}
```
On Controller
```
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
```
### What is the expected result?

After update the model, i expect that 'resolved_at' field has a proper format like 'Y-m-d H:i:s'

### What do you get instead?

After update the model, the 'resolved_at' field has a Unix Timestamp value.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  7.0.8
| Operating system |  Windows 7 64bits with XAMPP for Windows 7.0.8

**Comment by pstddc** [comment]
create migration for change column type from integer to datetime

**Comment by TerraSkye** [comment]
its a question please use the forum
