### ISSUE TITLE
yii2 batch more than million data, out of memory

### ISSUE THREAD

**Issue by Liv1020** [yiisoft/yii2#11996]
### What steps will reproduce the problem?
Using Batch to deal with millions of data, the inevitable emergence of memory overflow

### What is the expected result?
Normal memory

### What do you get instead?
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 587690376 bytes)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.23
| Operating system | Ubutu

**Comment by pstddc** [comment]
show full code

**Comment by Liv1020** [comment]
```
         $query = SellCustomer::find()
            ->delete(false)
            ->andWhere(['BETWEEN', 'last_follow_time', $start, $end])
            ->level([SellCustomer::LEVEL_H, SellCustomer::LEVEL_A, SellCustomer::LEVEL_B, SellCustomer::LEVEL_C]);

        foreach ($query->each(100) as $model){
            //this is my update
        }

````

**Comment by klimov-paul** [comment]
> delete(false)...level()

Obviously you are using non standard solution. Thus we can not hlp you.
Report your issue to the author of the `Query` you are using.

**Comment by Liv1020** [comment]
@klimov-paul this is use ActiveQuery by yii,
```
/**
     * 获取是否删除的
     * @param bool $val
     * @return $this
     */
    public function delete($val = true)
    {
        $this->andWhere('isdel' => ($val ? 1 : 0)]);
        return $this;
    }

```

**Comment by lynicidn** [comment]
`  //this is my update`

show this code

**Comment by klimov-paul** [comment]
Duplicates #9269

**Comment by Liv1020** [comment]
@lynicidn 
//this is my update

this code I delete, you use simple code also get out of memory error
