### ISSUE TITLE
BaseActiveRecord after refresh incorrect oldAttributes

### ISSUE THREAD

**Issue by only-victor** [yiisoft/yii2#11990]
In the BaseActiveRecord->refresh() field _oldAttributes is the same as _attributes. I think it is wrong.

See patch https://github.com/yiisoft/yii2/compare/master...only-victor:patch-1

The $record->_oldAttributes may be different than $record->_attributes. 
Therefore $this->_oldAttributes must be the same as $record->_oldAttributes.
For example I can change $record->_attributes in afterFind handler and now $this->_oldAttributes will not be equal $record->_oldAttributes.

**Comment by klimov-paul** [comment]
@only-victor, can you open a pull request for this?

**Comment by only-victor** [comment]
I don't know to do it.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by only-victor** [comment]
@samdark Sorry, but I don't understand what exactly I must to do.

**Comment by samdark** [comment]
Ah, you have branch already. Then it's simpler and can be done via GitHub UI: https://help.github.com/articles/creating-a-pull-request/

**Comment by klimov-paul** [comment]
Resolved by commit 4f7b1b081714018d3d086b2379701da0255d9855

**Comment by only-victor** [comment]
@klimov-paul Thanks.
