### ISSUE TITLE
Yii2: RadioList and CheckboxList - The for attribute of the label element must refer to a non-hidden form control.

### ISSUE THREAD

**Issue by adampblack** [yiisoft/yii2#12009]
### What steps will reproduce the problem?
$form->field($model, 'attribute')->radioList($model->arrAttributeOptions)
$form->field($model, 'attribute2')->checkboxList($model->arrAttribute2Options)

### What is the expected result?
For example, the checkbox list active field produces this (note label and hidden input):
```
<div class="form-group field-modelname-attributename">
   <label class="control-label" for="modelname-attributename">Attribute Label</label>
   <input type="hidden" name="Modelname[attributename]" value="">
   <div id="modelname-attributename">
       <div class="radio"><label><input type="radio" name="Modelname[attributename]" value="attributevalue1" checked> attributevaluelabel1</label></div>
       <div class="radio"><label><input type="radio" name="Modelname[attributename]" value="attributevalue2"> attributevaluelabel2</label></div>
       <div class="radio"><label><input type="radio" name="Modelname[attributename]" value="attributevalue3"> attributevaluelabel3</label></div>
   </div>
</div>
```

### What do you get instead?
Go to a w3C validator: "Error: The for attribute of the label element must refer to a non-hidden form control."

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | yii2.05
| PHP version      | PHP 5.5.9
| Operating system | Ubuntu 14.04.4 LTS

**Comment by shevchik87** [comment]
I tried and repeated problem
Can I solve this problem?

**Comment by cebe** [comment]
If you have a way to solve it, you can send a pull request :)

**Comment by nagyt234** [comment]
This issue still exists.
