### ISSUE TITLE
Widget INIT event

### ISSUE THREAD

**Issue by user57376** [yiisoft/yii2#12000]
In order to enhance widgets with behaviors, we could simply use of the attach method.

```
class MyBehavior extends Behavior
{
   
    public function attach($owner)
    {
        parent::attach($owner);
        
        // do stuff
    }
    
}
```

Usually that's enough, but in this case I want to manipulate the configuration values too. 

For example:

```
echo Tabs::widget([
    'as remember' => ['class' => TabsRememberBehavior::className()],
    'items' => [
        ...
    ],
]);

```
The TabsRememberBehavior has to read the last tab position from a cookie and then activate that one in the items. But in this configuration order the behavior can't do his job because the items aren't set yet.

So, to be sure all configuration values are set I would like to have a Widget::EVENT_INIT.

**Comment by unclead** [comment]
i think it is similar with what was discussed in scope of #8133

**Comment by samdark** [comment]
@unclead yes but scope is narrower.

**Comment by unclead** [comment]
If you decided to append this feature to the core it would be great, because i also think that such feature can be useful in some cases

**Comment by cebe** [comment]
adding events to Widgets can help with making them more extensible but I would not limit this to EVENT_INIT. there should also be something like before and after render/run. not sure about which exactly yet.

**Comment by samdark** [comment]
We can start with init and then proceed as requested.

**Comment by klimov-paul** [comment]
Duplicates #7435
