### ISSUE TITLE
Remove validation  dynamically

### ISSUE THREAD

**Issue by actcux** [yiisoft/yii2#12003]
I have an issue with a form witch shows fields from 2 models,  a checkbox enables the fields of the second model; so I want, when the checkbox is checked it adds a validation rule for the field of the second model, and when it is unchecked the rules have to be removed. To add the rules is working fine with $('#myform').yiiActiveForm('add', attributes), but to remove the validation it is not working or maybe I am doing wrong, I trying with $('#myform').yiiActiveForm('remove', 'field-id'); but no success.

Can you help me with this please?

Thank you.

**Comment by samdark** [comment]
Are you using the same ID as was used when you were adding it?

**Comment by actcux** [comment]
After checking my code and looking the ID of the input $('#tour-form').yiiActiveForm('add', {  'id': '**slideritem-sid**', 'name': 'sid', 'container': '.field-slider_id', 'input':  '**#slider_id**',...}) and the to remove    $('#tour-form').yiiActiveForm('remove', '**slideritem-sid**'); I tried changing the ID for id for both in the add and remove to the id set in the "input" attribute and now it works. 
$('#tour-form').yiiActiveForm('add', { ..., 'id': 'slider_id', ... }), $('#tour-form').yiiActiveForm('remove','slider_id');

Thank you.
