### ISSUE TITLE
Yii autoloader error

### ISSUE THREAD

**Issue by Olegf13** [yiisoft/yii2#12011]
I'm getting an error while trying to use `\Yii` as a Composer dependency in my project.

### What steps will reproduce the problem?

```
mkdir test
cd test
composer require yiisoft/yii2
php sandbox.php
```

Contents of `sandbox.php` file:

```
<?php
require __DIR__ . '/vendor/autoload.php';

// just for test that other libs autoloading works fine
echo \yii\helpers\Markdown::$defaultFlavor . PHP_EOL; // "original"
echo \Yii::getVersion() . PHP_EOL; // Fatal error: Uncaught Error: Class 'Yii' not found in ...
```

### What is the expected result?

`2.0.9`

### What do you get instead?

`Fatal error: Uncaught Error: Class 'Yii' not found in ...`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | PHP 7.0.8
| Operating system | Ubuntu 16.04

**P.S.:** If update `vendor/yiisoft/Yii.php` file with next contents:

```
<?php
/**
 * Yii bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace yii;

/**
 * Yii is a helper class serving common framework functionalities.
 *
 * It extends from [[\yii\BaseYii]] which provides the actual implementation.
 * By writing your own Yii class, you can customize some functionalities of [[\yii\BaseYii]].
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class Yii extends \yii\BaseYii
{
}

spl_autoload_register(['yii\Yii', 'autoload'], true, true);
Yii::$classMap = require(__DIR__ . '/classes.php');
Yii::$container = new yii\di\Container();

```

And then call `echo \yii\Yii::getVersion() . PHP_EOL;` - all works fine.

**Comment by klimov-paul** [comment]
You miss following line:

```php
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
```

**Comment by Olegf13** [comment]
Ok, thanks )

And by the way, can you please explain me why class `Yii` is not included into `\yii` namespace and is available at 'root' namespace instead?

**Comment by klimov-paul** [comment]
@Olegf13, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by samdark** [comment]
@Olegf13 it was a long-long-ago decision. As @klimov-paul pointed out, it's better to discuss that at forums.

**Comment by Olegf13** [comment]
Ok, thanks for your answers.
