### ISSUE TITLE
Feature Request: private to protected scope changes in UploadedFile

### ISSUE THREAD

**Issue by ArekX** [yiisoft/yii2#12016]
Problem we found is with `UploadedFile`, specifically `private static $_files;`. We wanted to use validation functionality and processing of files (loaded through server from some remote location) through models while relying on original `UploadedFile` (by extending it) and we basically needed to extend almost all of the methods in `UploadedFile` just because of `private static $_files;`. line, while otherwise we would override 2 or 3 methods to what we need.

Now I know that this might be a minor issue and also some people might find issues with not using private, but it would help great to people which want to extend by overriding. :)

Also, as a more elaborate feature, it may be good to consider refactoring `UploadedFile` to `BaseFile` and make UploadedFile extend its features.

**Comment by samdark** [comment]
What's the use case for `BaseFile`? What should go into it?

**Comment by samdark** [comment]
@yiisoft/core-developers thoughts?

**Comment by ArekX** [comment]
For now i would put stuff like --> `name`, `tempName`, `type`,`size`,`error`
As for functions --> `__toString`, `getBaseName`, `getExtension`, `getHasError` and `saveAs`

And change `FileValidator` to work with `BaseFile` instead of `UploadedFile` (which looks like it wont be a big change). I think it should work easily with both `UploadedFile` and other classes which extend `BaseFile`

**Comment by samdark** [comment]
As for access to `$_files`, can't you use `loadFiles()` instead?

**Comment by ArekX** [comment]
In what way can I use `loadFiles()` to access `$_files` ?

1. It's `private` --> https://github.com/yiisoft/yii2/blob/master/framework/web/UploadedFile.php#L200
2. It's calls `self::loadFilesRecursive` which not only is also `private` but is called using `self` instead of `static` (which I guess makes sense since it's private). IMHO it might be a good idea to [always use static in framework classes](http://www.programmerinterview.com/index.php/php-questions/php-self-vs-static/) and I saw exactly that in almost all places inside Yii 2 with few exceptions like this one.

By the looks of it, this class is really locked down tight and is not easily extendable.

**Comment by samdark** [comment]
OK, I mean if we'll make it protected.

**Comment by samdark** [comment]
Yes, these are valid concerns.

**Comment by ArekX** [comment]
Just pinging. Is there going to be any resolution to this issue?

**Comment by SilverFire** [comment]
Related to https://github.com/yiisoft/yii2/issues/12620

Good time to fix this issue as well

**Comment by dynasource** [comment]
agreed. The BaseFile suggestion is a good one. Put standard file methods over there. Then create its implementations UploadedFile & RemoteFile & LocalFile in Yii's core.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
