### ISSUE TITLE
Incorrect quoting

### ISSUE THREAD

**Issue by khvalov** [yiisoft/yii2#12014]
### What steps will reproduce the problem?
Incorrect quoting for group by 
`hotels=\app\models\Hotels::find() ->select('hotels.*') ->orderby('st_makepoint(hotels.latitude,hotels.longitude)  <-> st_makepoint(40.1268,-74.9677)')->limit(10)->all();`

### What is the expected result?
sql statement: 
`select * from common.hotels order by st_makepoint(hotels.latitude,hotels.longitude)  <-> st_makepoint(40.1268,-74.9677) limit 10;`

### What do you get instead?
`SELECT "hotels".* FROM "common"."hotels" ORDER BY st_makepoint(hotels.latitude, hotels.longitude) <-> st_makepoint(40.1268, "-74"."9677)" LIMIT 10
`
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10-dev
| PHP version      | 5.5.37
| Operating system | OsX

**Comment by samdark** [comment]
You mean order by, not group by, right?

**Comment by samdark** [comment]
What's database server you're using?

**Comment by khvalov** [comment]
Yes, I'm about order by. 
I'm using Postgres + PostGIS 
Actualy solved by using DBExpression 

`
 $hotels=\app\models\Hotels::find()
                ->select('hotels.*')
                ->orderBy([new \yii\db\Expression('st_makepoint(hotels.latitude,hotels.longitude)  <-> st_makepoint(40.1268,-74.9677)')])
                ->limit(10)
                ->all();
`
