### ISSUE TITLE
Feature Request: private to protected scope changes in ActiveQueryTrait

### ISSUE THREAD

**Issue by ArekX** [yiisoft/yii2#12015]
I know this might be a bit strange to ask, but I would like if it is possible to change private scope of `createModels` in `ActiveQueryTrait`. 

Generally my opinion is that one should never use private scope inside frameworks since you never know which part of the framework somebody might use and modify by extending that class and overriding that function. It would be best to use only protected and public.

Here is a reason why I would find this change to be really good:
We wanted to make a functionality which extends ActiveRecord query and allows you to do things like:

``` php
ActiveRecord::find()->configure([
   'scenario' => 'some-scenario',
   'attribute1' => '...'
   // ...
])->andWhere()->orWhere()->all();
```

Which would basically return all models already set with attributes and scenarios of my choosing. You could argue that I could do this in `afterFind` of a specific model but this leaves way more customization ability because sometimes I want to avoid doing things (like loading additional data) in `afterFind` when a specific scenario is set and there is no way to do this in current Yii 2. If I could extend `createModels` function. Here is how it would look like in extended ActiveQuery:

``` php
class ActiveQueryExtension extends yii\db\ActiveQuery {
    public $modelConfig = [];

    public function configure($data)
    {
        $this->_modelConfig = $data;
        return $this;
    }

    protected function createModels($rows) 
    {
        $models = parent::createModels($rows);

        foreach($models as $model) {
              \Yii::configure($model, $this->modelConfig);
        }   

        return $models;
    }
}
```

**Comment by samdark** [comment]
@yiisoft/core-developers thoughts?

**Comment by cebe** [comment]
you can just override `populate()` method for this instead of `createModels()` with the same effect.

**Comment by cebe** [comment]
In general, we have private methods to allow refactoring internals without the risk of breaking backwards compatibility.

**Comment by ArekX** [comment]
True you can, but overriding `createModels()` allows for cleaner code. 

If you try to override `populate()` to get the effect of setting a scenario and/or other attributes before `afterFind()` is called we would have to do this:

```php
class ActiveQueryExtension extends yii\db\ActiveQuery {
    public $modelConfig = [];

    public function configure($data)
    {
        $this->_modelConfig = $data;
        return $this;
    }

    public function populate($rows)
    {
        if (empty($rows)) {
            return [];
        }

        $models = $this->createModels($rows);

        foreach($models as $model) {
            \Yii::configure($model, $this->modelConfig);
        }

        if (!empty($this->join) && $this->indexBy === null) {
            $models = $this->removeDuplicatedModels($models);
        }
        if (!empty($this->with)) {
            $this->findWith($this->with, $models);
        }
        if (!$this->asArray) {
            foreach ($models as $model) {
                $model->afterFind();
            }
        }

        return $models;
    }
}
```

As you can see, I would have to override the whole `populate()` function which is:
1. It makes code unnecessary longer, just because I cannot access `createModels()`
2. It's way worse for keeping compatibility with future versions of Yii 2 releases.

**Comment by cebe** [comment]
sorry, I missed the part of using the config in afterFind().

**Comment by ArekX** [comment]
Just pinging. Is there going to be any resolution to this issue?

**Comment by dynasource** [comment]
within your inheritance usecase, I dont see why the afterFind() event won't do in combination with overriding populate() (in which you set & unset the event).

If you can convince me of that, we will make it protected.

**Comment by ArekX** [comment]
I do not understand how do you mean to do that. Could you provide an example?

**Comment by dynasource** [comment]
Have you tried a solution with the 'after find' event yet? https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L901

**Comment by ArekX** [comment]
I don't think you understood what the problem is here. It is too late when I use `afterFind()` or After Find event. I need to configure the model before afterFind() executes.

Here is an example of use case inside one model:

```php
public function afterFind()
{
    if ($this->scenario == 'something') {
         $this->populateRelation('relationName');
         // set some other variables... 
   }

    if ($this->property == 'somethingElse') { // property which needs to be set before a call to afterFind()
        $this->callMethod();
    }
    
    parent::afterFind();
}
```

Could you provide me an example where I can use something like this and where I can set properties and scenarios so that using `ActiveRecord::find()->configure([ /* modelProperties go here */ ])->all()` triggers correct branching in `afterFind()` ?

**Comment by dynasource** [comment]
why arent you doing it like this? Afterfind() is just a Event triggerer as you can see https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L901
```php
public function afterFind()
{
    parent::afterFind();

    if ($this->scenario == 'something') {
         $this->populateRelation('relationName');
         // set some other variables... 
   }

    if ($this->property == 'somethingElse') { // property which needs to be set before a call to afterFind()
        $this->callMethod();
    }

    
}
```

**Comment by ArekX** [comment]
Please explain how that would work? :)

So that I can use this:
```php
ActiveRecord::find()->configure([ 
'scenario' => 'something',
'property' => 'somethingElse'
])->all();
```

And **all** found models will have their **scenario and property already set** when `afterFind()` gets called?
If I understood correctly I should set the after find event on each of those models and then remove it afterwards? Please tell me **which function** should I extend in `ActiveQuery` to attach that event so that it gets called when `parent::afterFind()` is executed?

The only way your solution would work is that I set a behavior to every model I need this to be done and set model configuration inside that behavior statically which:
1. Is not configurable outside of the same model (unless you expect me to set configuration statically?)
2. It would defeat the purpose of simple extension which would be done easily if just one function goes to protected.

The ONLY solution which I know which keeps all of this is that I make a hack by using `indexBy` and passing my own function in there which does the configuration and that is a horrible implementation IMO.

**Comment by dynasource** [comment]
see my previous comment and try to do it like this:

```php
$myCallback = function ($event) {
    $event->sender->scenario = 'something';
};
Event::on(MyActiveRecord::className(), MyActiveRecord::EVENT_AFTER_FIND, $myCallback);
MyActiveRecord::find()->all();
Event::off(MyActiveRecord::className(), MyActiveRecord::EVENT_AFTER_FIND, $myCallback);
```

**Comment by ArekX** [comment]
Ok as I see that would work. But that seems also more like a hack that a good solution, and if not coded and maintained, it may cause many problems. 

Also I cannot believe that I should make a workaround like this instead of doing a simple extension of one function.

No this is not a good solution.

**Comment by dynasource** [comment]
I acknowledge and respect your eagerness for desiring the best solution. In the future we will put effort in improving the architecture around ActiveQuery & ActiveRecord. For now you already have 2 possible and valid ways to solve your problem:
* By extending ActiveRecord and set default parameters
* By using Events

thanks for sharing your thoughts

**Comment by ArekX** [comment]
It seems quite rude to cut someone off like this without giving a chance to say something about it. So I will leave this issue with these thoughts:

1. Your workaround won't work correctly for use cases when the same model will be loaded inside `afterFind()`, as is in case of recursive parent-child loading since children will get the same configuration because of the global event. Or in any other use case when the same model will be loaded in `afterFind()`. So that is something to keep in mind when using this.

2. Keeping methods private in an open source project is not a good idea in the long run IMHO. I understand your idea of making people do better implementation with what they have while making code more robust to future changes but as you see, you need a perfect foresight for this and an ability to see the future. Aside from that, there are currently some things in Yii that are impossible to do because of this, and the time I spend "convincing" that some change is needed is the time taken from doing actual work with Yii. Not to mention all of the other integration checks and tests needed to be passed until the next version/revision is released. Your time would be better spent on making this framework even better than trying to code around changes to allow maximum compatibility with other people code. You do not want to make another Wordpress I hope :)

Anyways, thanks for clarification. I guess I have no other choice than to go with this workaround. Hope things will get different as Yii progresses. :)

**Comment by dynasource** [comment]
We are very pleased to see your effort to convince us of the necessity. Dont feel bad about your topic been closed. Sometimes we close subjects in order to not to repeat ourselves. I will create a PR today which solves your issue.
