### ISSUE TITLE
How change verify code that generated by captcha to a number without any words or alphabet?

### ISSUE THREAD

**Issue by aminkt** [yiisoft/yii2#12018]
Hi.
I'm trying to completely customize yii2 captcha for my country.
i changed it's font to Persian fonts but English alphabet is not valid in my case.
So i think it's good to change verify code that generated by captcha to a number without any words or alphabet.
Is there any way to do this?
thanks.

**Comment by bizley** [comment]
Looks like you have to extend CaptchaAction and override generateVerifyCode() method.

**Comment by aminkt** [comment]
Can you give me an example?
