### ISSUE TITLE
Feature Request: private to protected scope changes

### ISSUE THREAD

**Issue by ArekX** [yiisoft/yii2#12013]
I know this might be a bit strange to ask, but I would like if it is possible to change private scope of `createModels` in `ActiveQueryTrait`. 

Generally my opinion is that one should never use private scope inside frameworks since you never know which part of the framework somebody might use and modify by extending that class and overriding that function. It would be best to use only protected and public.

Here is a reason why I would find this change to be really good:
We wanted to make a functionality which extends ActiveRecord query and allows you to do things like:
```php
ActiveRecord::find()->configure([
   'scenario' => 'some-scenario',
   'attribute1' => '...'
   // ...
])->andWhere()->orWhere()->all();
```
Which would basically return all models already set with attributes and scenarios of my choosing. You could argue that I could do this in `afterFind` of a specific model but this leaves way more customization ability because sometimes I want to avoid doing things (like loading additional data) in `afterFind` when a specific scenario is set and there is no way to do this in current Yii 2. If I could extend `createModels` function. Here is how it would look like in extended ActiveQuery:
```php
class ActiveQueryExtension extends yii\db\ActiveQuery {
    public $modelConfig = [];

    public function configure($data)
    {
        $this->_modelConfig = $data;
        return $this;
    }

    protected function createModels($rows) 
    {
        $models = parent::createModels($rows);

        foreach($models as $model) {
              \Yii::configure($model, $this->modelConfig);
        }   

        return $models;
    }
}
```

Other problems we found is with `UploadedFile`, specifically `private static $_files;`. We wanted to use validation functionality and processing of files (loaded through server from remote location) through models while relying on original `UploadedFile` (by extending it) and we basically needed to extend almost all of the methods in `UploadedFile` just because of `private static $_files;`. line, while otherwise we would override 2 or 3 methods to what we need.

Now I know that this might be a minor issue and also some people might find issues with not using private, but it would help great to people which want to extend by overriding. :)

**Comment by samdark** [comment]
> Generally my opinion is that one should never use private scope inside frameworks since you never know which part of the framework somebody might use and modify by extending that class and overriding that function. It would be best to use only protected and public.

http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html

In general we agreed not to expose methods w/o a reason. Each case should be discussed separately.

**Comment by samdark** [comment]
Would you please copy-paste two issues mentioned to separate tickets? Thanks!

**Comment by ArekX** [comment]
Done. :)

Tickets are: #12016 and #12015
