### ISSUE TITLE
Not working select as

### ISSUE THREAD

**Issue by ilyaplot** [yiisoft/yii2#12019]
### What steps will reproduce the problem?
My code in the controller:
`$artists = Artist::find()->select("artist_id as id, name")->all();`
`Yii::$app->response->format = Response::FORMAT_JSON;`
`return $artists; `
Model:
`public $id;`
### What is the expected result?
[{"id":1234,"name":"artist name"}, ......]
### What do you get instead?
[{"name":"artist name"}, ......]
### Additional info
So it works: 
`echo $artists[0]->id; // 1234`
How to display the required data into the json array without the cycle?
Sorry for my English.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  7.0.8
| Operating system |  Debian 7

**Comment by ilyaplot** [comment]
It really is not a bug?

**Comment by samdark** [comment]
I wasn't able to reproduce that. The code you've pasted gives expected results with both `id` and `name`.

**Comment by ilyaplot** [comment]
Please, try it in the PostgreSQL

**Comment by ilyaplot** [comment]
pgsql version 9.5

`-- Table: cms.artist

CREATE TABLE cms.artist
(
  artist_id integer NOT NULL DEFAULT nextval('cms.artist_id_seq'::regclass),
  name character varying,
  CONSTRAINT artist_id PRIMARY KEY (artist_id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE cms.artist OWNER TO postgres;
GRANT ALL ON TABLE cms.artist TO postgres;`

**Comment by ilyaplot** [comment]
This code
```
$artists = Artist::find()->select("artist_id as id")->all();
 Yii::$app->response->format = Response::FORMAT_JSON;
return $artists; 
```
Returns this type
`[{},{},{},{},{},{},{},{}.....]`

**Comment by klimov-paul** [comment]
Such example can not work, since serialization is made on model attributes, which is static and refer to the related table scema - not the selected fields set.

However, you may try to use `asArray(true)`:

```php
$artists = Artist::find()->select("artist_id as id")->asArray(true)->all();
Yii::$app->response->format = Response::FORMAT_JSON;
return $artists;
```

**Comment by samdark** [comment]
Right. I was testing w/ a model that had `id` field.
