### ISSUE TITLE
DbMessageSource migration doesn't create primary key in message table

### ISSUE THREAD

**Issue by umneeq** [yiisoft/yii2#12023]
Why it doesn`t create it?
https://github.com/yiisoft/yii2/blob/master/framework/i18n/migrations/m150207_210500_i18n_init.php#L35
And of course CRUD generate ID field in _form.php.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/i18n/migrations/m150207_210500_i18n_init.php#L40
