### ISSUE TITLE
FR, ENH: Database View Emulator (AR for query statement)

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#12025]
It same as `ActiveRecord` except the source not from `table` (or existing view) but from query statement.

```php
class InvoicePaid extends QueryRecord
{
    public static function query()
    {
        return 'select invoice_id, sum(value) as value from payment group by invoice_id';
        // or return query object
    }
}

class Invoice extends ActiveRecord
{
    ...
    
    public function getPaid()
    {
        return $this->hasOne(InvoicePaid::class, ['invoice_id' => 'id']);
    }
}

// ***********
InvoicePaid::find()->where(['>', 'value', 100])->all();

foreach(Invoice::find()->joinWith('paid')->all() as $model) {
    echo $model->paid->value;
}
```

Why?
-------
Of course it can be more simple by create `view` for that statement then create AR for that `view`. 
But, i want in my application, my database is used only as storage. All rules (validation, integrity, relation, trigger, storage procedure and also view) should be done in aplication.

What do you think?

**Comment by samdark** [comment]
The concept is interesting.

1. I assume it's read only. Correct?
2. Could it use eager loading somehow in case of `with`?

**Comment by mdmunir** [comment]
> 1. I assume it's read only. Correct?
> 2. Could it use eager loading somehow in case of with?

1. Yes. Or, to make it writable, we should override method `updateAll()` and `insert()`. 
But, read only is enough.
2. I wish.

The problem is, how to resolve attributes? IMO, hardcode is more simple.

**Comment by klimov-paul** [comment]
What is wrong with exending ActiveRecord overriding `find()` method to add extra query condition?

```php
class Payment extends \yii\db\ActiveRecord
{
     ...
}

class InvoicePaid extends Payment
{
    public $value;
 
    public static function find()
    {
        return parent::find()
            ->select(invoice_id, sum(value) as value)
            ->groupBy('invoice_id');
    }
}
```

Any relation, which uses `InvoicePaid` will use adjusted query.

**Comment by mdmunir** [comment]
> What is wrong with exending ActiveRecord overriding find() method to add extra query condition?

Not sure.Need test.

**Comment by mdmunir** [comment]
It work for me
```php
class InvoicePaid extends \yii\db\ActiveRecord
{

    public function attributes()
    {
        return[
            'invoice_id', 'paid'
        ];
    }

    public static function find()
    {
        return parent::find()
                ->select(['invoice_id', 'paid' => 'sum([[value]])'])
                ->from('{{%payment_dtl}}')
                ->groupBy(['invoice_id']);
    }
}

Invoice::find()->with('paid')->all();
```
Buat eager loading create statement
```sql
SELECT "invoice_id", sum("value") AS "paid" 
FROM "payment_dtl" 
WHERE "invoice_id" IN (2, 3) 
GROUP BY "invoice_id"
```
instead of
```sql
SELECT "invoice_id", "paid" 
FROM (SELECT "invoice_id", sum("value") AS "paid" 
    FROM "payment_dtl" 
    GROUP BY "invoice_id") AS t 
WHERE "invoice_id" IN (2, 3)
```
I mean, custom sql should be treated as sub query.

**Comment by klimov-paul** [comment]
> But eager loading create statement...instead of

I can't see any problem: both queries should produce same results (first one will be faster).

**Comment by mdmunir** [comment]
just to ensure it work fine in any sitation. Just like `view` as.

**Comment by cebe** [comment]
@mdmunir thanks for the suggestion and your contruibution, as discussed in the pull request, https://github.com/yiisoft/yii2/pull/12050 this is better suited as an extension so I am closing this issue.
