### ISSUE TITLE
console command not working for removing the frontend cache

### ISSUE THREAD

**Issue by ceovishnu** [yiisoft/yii2#12027]
whenever you fire the console command `./yii cache/flush cacheFrontend` then it's removing the console cache not frontend cache.

it's should be working for specific component name but it's give the below prompt but not working.

`The following cache components will be flushed
 cache 
Flush above cache components? (yes|no) [no]:yes
The following cache components were processed:
	* cache (yii\caching\FileCache)`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | Ubuntu 15.10

**Comment by ceovishnu** [comment]
@samdark any suggestion from your end, because i think it's not any permission issue for removing the cache using console as per requested environment.
i have change the component name but still it's give the same prompt message.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/CacheController.php#L35
