### ISSUE TITLE
ActiveRecord GROUP_CONCAT bug

### ISSUE THREAD

**Issue by he11d0g** [yiisoft/yii2#12020]
### What steps will reproduce the problem?
```
$model = new Pokemon::find();
$model->select('pokemon.*, GROUP_CONCAT("{",`pokemon_type`.`type_id`,""}") as cntType');
```

### What is the expected result?
`var_dump($model->createCommand()->getRawSql());`
> SELECT \`pokemon\`.*, GROUP_CONCAT("{", \`pokemon_type\`.\`type_id\`, "}") AS \`cntType\`

### What do you get instead?
`var_dump($model->createCommand()->getRawSql());`
and see this : 

> SELECT \`pokemon\`.*, GROUP_CONCAT("{", \`pokemon_type\`.\`type_id\`, \`"}")\`AS \`cntType\`

Each argument CONCAT_GROUP function starting from 2 taken in quotes. It is not right.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  PHP 5.4.45
| Operating system | Centos 6

**Comment by klimov-paul** [comment]
Duplicates #8276
