### ISSUE TITLE
Update jQuery version

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#12029]
Can we update `jQuery` version to the latest stable branch which is `3.*` at the moment?

Won't it break any of existing frontend components?

**Comment by samdark** [comment]
https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

> Despite the 3.0 version number, we anticipate that these releases shouldn’t be too much trouble when it comes to upgrading existing code. Yes, there are a few “breaking changes” that justified the major version bump, but we’re hopeful the breakage doesn’t actually affect that many people.

- https://jquery.com/upgrade-guide/3.0/
- https://github.com/jquery/jquery-migrate#migrate-older-jquery-code-to-jquery-30

**Comment by rugabarbo** [comment]
Must be closed. 

There are:
* issue https://github.com/yiisoft/yii2/issues/15768 – for 2.0.x
* extension https://github.com/yiisoft/yii2-jquery – for 2.1.x
