### ISSUE TITLE
query->one() is slow

### ISSUE THREAD

**Issue by shushenghong** [yiisoft/yii2#12024]
### What steps will reproduce the problem?
we found that one() is slow if our search condition is not a primary key and if the database is large.

`User::find(['status' => 1])->one();`

if we change to 
`User::find(['status' => 1])->limit(1)->one();`
is much more faster.

if we choose one() not all(), can yii2 auto add limit 1?

![image](https://cloud.githubusercontent.com/assets/3275714/17174033/04b6ae9c-5431-11e6-85f2-09e51c6d5d58.png)

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/issues/4348

**Comment by shushenghong** [comment]
laravel have a first()
