### ISSUE TITLE
Problems with MemCache on windows

### ISSUE THREAD

**Issue by zakdma** [yiisoft/yii2#12037]
Windows, php 5.5 Yii 2.0.6, memcached 1.4.4
I'm using configuration for caching
```
'cache' => [
            'class' => 'yii\caching\MemCache',
            'useMemcached' => false,
            'servers' => [
                [
                    'host' => '127.0.0.1',
                    'port' => 11211,
                    'weight' => 64,
                ],

            ]
        ],
        'session' => [
            'class' => 'yii\web\CacheSession',
            'cache' => 'cache',
        ],
```
**Expected result:** sessions data stored in memcache
**Actual result:** Sessions does not save to memcache

Debuger has led me to this class yii\caching\MemCache.php (line 293)
There is line
`$expire = $duration > 0 ? $duration + time() : 0`
So we add time() to duration. It produce in $expire very big number. I think memcache cannot save data with such duration and data actually does not save but function return true.
Changing this line to `$expire = $duration > 0 ? $duration : 0` solved the problem.

**Comment by samdark** [comment]
Seems it's due to #9707. I've re-checked and it seems there was no need to merge it i.e. we've always used timestamps which were OK.

Fixed it.

Thanks for reporting.

**Comment by zakdma** [comment]
It does not work for me.
This fix did not change $expiration calculation.
I don't know why but my memcached server (version 1.4.4 on windows) do not save keys with timestamp expirations. It returns true but does not save any data.
Similar issue https://github.com/symfony/symfony/issues/14789

**Comment by samdark** [comment]
Do you have memcahe or memcached extension?

**Comment by zakdma** [comment]
php_memcache of course. There is no official php_memcached extension for windows.

**Comment by samdark** [comment]
What's memcached (not extension) version do you have?

**Comment by zakdma** [comment]
memcached 1.4.4 for windows
http://downloads.northscale.com/memcached-win64-1.4.4-14.zip

**Comment by samdark** [comment]
Reproduced. Components:

```php
'cache' => [
    'class' => \yii\caching\MemCache::className(),
],
```

SiteController:

```php
public function actionSet()
{
    $result = Yii::$app->cache->set('test', 42, 1440);
    var_dump($result);
}

public function actionGet()
{
    $result = Yii::$app->cache->get('test');
    var_dump($result);
}
```

**Comment by samdark** [comment]
Seems the problem is with that specific version of memcached (win64-1.4.4-14) for Windows you have.

I've tried with Northscale binaries and it's all fine:

- http://downloads.northscale.com/memcached-1.4.5-x86.zip
- http://downloads.northscale.com/memcached-1.4.5-amd64.zip

**Comment by samdark** [comment]
Your binary also fails tests while northscale one does not. You can try it yourself:

```
 phpunit tests/framework/caching/MemCacheTest.php
```
