### ISSUE TITLE
BUG: Wrong error message from ViewAction

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#12038]
### What steps will reproduce the problem?
* Define `ViewAction` in `SiteController`
```php
public function actions()
{
    return [
        ...
        'page' => [
            'class' => 'yii\web\ViewAction'
        ]
    ];
}
```
* Create file `@views/site/pages/index.php'
```php
<?php
   yii\helpers\Json::decode('{"a"}');    
```
* Open `index.php?r=site/page&view=index`

### What is the expected result?
Got `yii\base\InvalidParamException` `Syntax error`.

### What do you get instead?
Get `Not Found (#404)` exception.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master
| PHP version      | 5.6
| Operating system | debian 7

**Comment by mdmunir** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/ViewAction.php#L90-L96

**Comment by samdark** [comment]
Introduced new exception class to handle that.
