### ISSUE TITLE
Serving an image for display to the browser through Response::sendFile

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#12046]
I need to serve an image to the browser through an `<img>` tag:
```HTML
<img src="<?= Url::to(['site/image']) ?>" alt="" />
```
When I use `Response::sendFile` to do that:
```PHP
	public function actionImage()
	{
		return app()->getResponse()->sendFile('path/to/image/image.png');
	}
```
it generates a `Content-Disposition` HTTP header which I think should not be present in the response in a case like that. I think there should be an option in `Response::sendFile` to disable generation of `Content-Disposition` header.

**Comment by samdark** [comment]
I think you can use:

```php
return app()->getResponse()->sendFile('path/to/image/image.png', [
    'mimeType' => 'image/png',
    'inline' => true,
]);
```

**Comment by PowerGamer1** [comment]
Using `'inline' => true` still produces `Content-Disposition` header which should not be at all in the response:
```
Content-Disposition: inline; filename="image.png"
```

**Comment by samdark** [comment]
Nope. It won't affect anything.
