### ISSUE TITLE
Issues with functional testing

### ISSUE THREAD

**Issue by igravity** [yiisoft/yii2#12042]
I have a [question on StackOverflow](http://stackoverflow.com/questions/38657320/issues-with-yii2-advanced-functional-tests). I thought I should bring it to your notice

### What steps will reproduce the problem?

 - install `yii2-advanced-app`
 - make sure the version of Yii 2 is 2.0.9
 - bootstrap the tests directory
 - run the functional test

### What is the expected result?
 - a proper run of the default tests

### What do you get instead?
 - error: undefined index `SCRIPT_FILENAME`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  5.6
| Operating system |  Windows 7

**Comment by samdark** [comment]
Should be OK when https://github.com/yiisoft/yii2-app-advanced/pull/190 is merged.

**Comment by samdark** [comment]
But overall, it should work even now. We have these tests running in Travis and it's passing.

**Comment by samdark** [comment]
https://travis-ci.org/yiisoft/yii2-app-advanced
