### ISSUE TITLE
Json::encode() behaves differently from json_encode() when JsonSerializable::jsonSerialize() returns []

### ISSUE THREAD

**Issue by EvgenyOrekhov** [yiisoft/yii2#12043]
The documentation states that Json helper 

> enhances the PHP built-in functions json_encode() and json_decode()

and not _changes_ their behavior.

But Json::encode() behaves differently from json_encode() when JsonSerializable::jsonSerialize() returns [].

### What steps will reproduce the problem?
```php
class EmptyJsonModel extends Model implements \JsonSerializable
{
    public function jsonSerialize()
    {
        return [];
    }
}

$data = new EmptyJsonModel();
var_dump(Json::encode($data));
```
### What is the expected result?
```
[]
```
### What do you get instead?
```
{}
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | master
| PHP version      | 7.0.8
| Operating system | Ubuntu 16.04.1 LTS x86_64

**Comment by klimov-paul** [comment]
> But Json::encode() behaves differently from json_encode() when JsonSerializable::jsonSerialize() returns [].

This is expected. See #957

> and not changes their behavior.

This is absolutely true. `json_encode()` provides several flags to control thier behavior. By default Yii uses thier combination, which is equal to `320`.
You may use your own set of encode options if it is needed:

```php
Json::encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
``

**Comment by samdark** [comment]
@klimov-paul how about adjusting https://github.com/yiisoft/yii2/pull/12044 to check out current behavior + document the difference?

**Comment by EvgenyOrekhov** [comment]
@klimov-paul I expect `Json::encode()` here to return `{}` only if I use the `JSON_FORCE_OBJECT` option.
I also expect `json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)` to be replaceable with `Json::encode($data)` in all cases (except for JavaScript expressions, as the documentation states).

**Comment by klimov-paul** [comment]
Resolved by commit acfe21b4001b3a7775ea7755266548b96b1fd192

**Comment by klimov-paul** [comment]
Adjusted at 01e2ba1d28c3945156ecfd88e298e1d5129d2eb4

**Comment by samdark** [comment]
Hmm... wouldn't that break something in REST APIs part?

**Comment by klimov-paul** [comment]
Unlikely `JsonSerializable` is not used anywhere in the core.
Thus normal serialization of the models and other Yii classes will not be affected.

**Comment by samdark** [comment]
OK.
