### ISSUE TITLE
"Bad Request (#400): Unable to verify your data submission" on unmodified sample project

### ISSUE THREAD

**Issue by VTopoliuk** [yiisoft/yii2#12049]
### What steps will reproduce the problem?
1. Install basic yii2 app
`composer create-project --prefer-dist yiisoft/yii2-app-basic basic`
2. Navigate to login page
3. Enter any login and password

### What is the expected result?
User logged in

### What do you get instead?
Bad Request (#400)
Unable to verify your data submission.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  5.4.45
| Operating system |  Amazon Linux

**Comment by samdark** [comment]
Which browser is used?

**Comment by samdark** [comment]
Are cookies enabled?

**Comment by VTopoliuk** [comment]
Browser: Safari Version 9.1.1 (11601.6.17), Chrome Version 51.0.2704.103 (64-bit)
Cookies are enabled.

Log from server (domain changed)

[server.txt](https://github.com/yiisoft/yii2/files/391544/server.txt)

**Comment by VTopoliuk** [comment]
Logs from server
[server-2.txt](https://github.com/yiisoft/yii2/files/391548/server-2.txt)

**Comment by VTopoliuk** [comment]
More details:
Running in docker, server is placed behind the Varnish.

**Comment by samdark** [comment]
Are you running Wordpress at the same host?

**Comment by VTopoliuk** [comment]
Yes, wordpress is running on the same host.

**Comment by samdark** [comment]
Well, that's weird. I've tried reproducing that but found no way to do it.

1. Can you try with master instead of 2.0.9?
2. Can you try on a separate host without Wordpress?

**Comment by VTopoliuk** [comment]
Sure, I will check it. I can share access yii app if we can move this conversation to any private channel.

**Comment by tunecino** [comment]
is amazon linux covered by the security class ? 
I think it is based on CentOS but they kind of maintaining it by themselves: https://alas.aws.amazon.com/ 
if not tested with Yii2 before then it may also be useful to try tom's script first https://github.com/yiisoft/yii2/issues/10519#issuecomment-168782810 to see if it works same as other linux distros

also shouldn't be there a `_csrf` cookie ? i don't see it in logs

**Comment by VTopoliuk** [comment]
@tunecino I don't know how Yii2 works as I have installed it first time yesterday, but demo app doesn't work. I will try to run script.

@samdark I tried on separate host and everything works fine.

**Comment by tunecino** [comment]
well $_POST has a generated _csrf token so I may be wrong about security scripts. I guess they works fine. I think the issue is with the `_csrf` cookie not being sent. when csrf validation is enabled yii will compare that `_csrf` token in $_POST against a second one stored in a cookie. see more about it in the following 2 methods: http://www.yiiframework.com/doc-2.0/yii-web-request.html#$enableCsrfCookie-detail
maybe session conflicts with WordPress. I don't know.

**Comment by samdark** [comment]
What I'd suspect:

1. Varnish config somehow messing up cookies. When trying separate host, have you used Varnish as well?
2. Wordpress. I have no idea how/why it may affect Yii.

Anyway, doesn't seem to be a problem with Yii itself which we may fix so closing the issue.

**Comment by 11ravi** [comment]
Hey,
@samdark @klimov-paul @qiangxue How to solve this??

Bad Request (#400)
Unable to verify your data submission.

The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.
Project perfectly working on localhost,
same code on live server but not working.
yii2 2.0.15.

**Comment by alexdran** [comment]
in My case _csrf value was there on the form and correctly transferred to post array after, indeed disabling the _csrf validation with **Yii::app()->request->enableCsrfValidation = false;** was helping but no need to arrive that far.

I have solved with:
- composer self-update
- composer update
- cookie cleaning
