### ISSUE TITLE
Response::sendFile Content-Disposition header with non-ASCII filenames

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#12047]
When `$attachmentName` of `Response::sendFile` method contains non-ASCII characters the method creates invalid `Content-Disposition` HTTP header (according to specification HTTP headers cannot contain non-ASCII characters). In such a case the filename must be encoded according to https://tools.ietf.org/html/rfc5987 (also see https://tools.ietf.org/html/rfc6266#section-5).

Example:
```PHP
return \Yii::$app->getResponse()->sendFile('somepath', 'руссо туристо.txt');
```
The file "Save As..." window prompted by IE11 contains invalid file name.

**Comment by shirase** [comment]
#12040

**Comment by samdark** [comment]
Duplicate of #10563
