### ISSUE TITLE
Form submission error after controller redirect()

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#12052]
### What steps will reproduce the problem?
1. I have `ProjectController`, which has actionEdit(). This action has `ActiveForm` to edit a project. Inside of actionEdit() I pass `$model` for `ActiveForm` validation and also `$project`, which consists of the data about the project (to place this data inside of the input (inside of the `value` property). 
2. When `ActiveForm` is submitted, this part of the code is being executed: 
```php
if( $model->load(System::post()) && $model->validate() ) {
    if( $model->update($project_id) ) {
        System::setFlash('success', 'Great! Success, blah, blah');
        return $this->redirect(['project/edit', 'id' => $website_id]);
    } else {
        System::setFlash('danger', 'Error, blah, blag');
        return $this->redirect(['project/edit']);
    }
}
```
Everything seems to be correct and it DOES WORK - good!

However, after form is submitted and all data of the project is saved in the database - second try to submit the form will consequence the `site/error` (which is default `SiteContoller`).  I have found out that the problem is related to the `$this->redirect()` function. 

In simple: if form is submitted successfully and redirected to the same page (eg. initial page `project/add` and redirecting page is the same) for the first time - then no problem happens. After second submission I received an error as described above. 

### What is the expected result?
Form should be easily submitted every time without an error. 

### What do you get instead?
Submission error. Form is submitted and data is saved in the database, however redirection is causing the error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| Nginx | 1.4.6
| PHP version      |  7.0.7-4+deb.sury.org~trusty+1
| Operating system | Ubuntu 14.04 trusty

**Comment by bologer** [comment]
Anyone?

**Comment by Alex-Code** [comment]
Have you looked to see what the error is? `runtime/logs`

**Comment by bologer** [comment]
@Alex-Code, yes, this is what I have inside: 

```php 
2016-08-01 08:57:10 [{IP}][1][-][warning][yii\debug\Module::checkAccess] Access to debugger is denied due to IP address restriction. The requesting IP address is {IP}
    in /path/to/backend/views/layouts/main.php:176
    in /path/to/backend/controllers/SettingsController.php:65
2016-08-01 08:57:10 [{IP}][1][-][info][application] $_COOKIE = [
    'PHPSESSID' => 'gv04f6ufa86opn8ghflt03b9v0'
    '_csrf' => 'f924d80ecf9756a1ca1bbe3c8dce6b143b40e9c901b30a39c7ee13b32d54f559a:2:{i:0;s:5:\"_csrf\";i:1;s:32:\"9GuqhJG9wVArmd-tYQmfaucZlZUACGDL\";}'
    '_identity' => '5e6be1e8434dd816d42c45a5243408d76337c06485d1e5a63338f4a18855d43ca:2:{i:0;s:9:\"_identity\";i:1;s:14:\"[1,\"\",2592000]\";}'
]

$_SESSION = [
    '__flash' => []
    '__id' => 1
]

$_SERVER = [
    'REDIRECT_REDIRECT_STATUS' => '200'
    'REDIRECT_STATUS' => '200'
    'HTTP_HOST' => ...'
    'HTTP_X_REAL_IP' => '...'
    'HTTP_X_FORWARDED_FOR' => '...'
    'HTTP_CONNECTION' => 'close'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    'HTTP_REFERER' => '...'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch'
    'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en-US;q=0.8,en;q=0.6,es;q=0.4,ru;q=0.2,uk;q=0.2'
    'HTTP_COOKIE' => 'PHPSESSID=gv04f6ufa86opn8ghflt03b9v0; _csrf=f924d80ecf9756a1ca1bbe3c8dce6b143b40e9c901b30a39c7ee13b32d54f559a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%229GuqhJG9wVArmd-tYQmfaucZlZUACGDL%22%3B%7D; _identity=5e6be1e8434dd816d42c45a5243408d76337c06485d1e5a63338f4a18855d43ca%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A14%3A%22%5B1%2C%22%22%2C2592000%5D%22%3B%7D'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu) mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.17 OpenSSL/1.0.1f'
    'SERVER_NAME' => '...'
    'SERVER_ADDR' => '...'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '...'
    'DOCUMENT_ROOT' => '...'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '...'
    'SERVER_ADMIN' => 'info@...'
    'SCRIPT_FILENAME' => '...'
    'REMOTE_PORT' => '53049'
    'REDIRECT_URL' => '/backend/web//settings/all'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.0'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'REQUEST_URI' => '/admin/settings/all'
    'SCRIPT_NAME' => '/backend/web/index.php'
    'PHP_SELF' => '/backend/web/index.php'
    'REQUEST_TIME_FLOAT' => 1470041830.584
    'REQUEST_TIME' => 1470041830
]
```

But it seems that it is not related to the problem that I have. 
Anyone knows how to fix this issue? 

Btw, it seems that I have fixed my problem by using `$this->refresh()` instead of `$this->redirect()`.

**Comment by samdark** [comment]
Seems errors isn't related. Do you have reliable way to reproduce it starting with basic project template?

**Comment by bologer** [comment]
@samdark, yes, I will do it and add more info here.

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
