### ISSUE TITLE
Bad Request (#400) || All the forms suddenly stopped working

### ISSUE THREAD

**Issue by saurabhsrb** [yiisoft/yii2#12054]
Everything was working fine till yesterday, I've done composer update at today morning and after that all the form stopped working. When ever i create or update a record using form, the yii system return 400

# I have Csrf token in my head tag.
# I have csrf field in my form

Still i am having this problem. On more thing i noticed when i logout and use that form it works fine. and after logging in the form says same error (#400)

I had cleared my cookie cache several time but still having the same issue.

On the other hand i have another project with advanced template working fine.

Please help me to fix this. I am facing this issue since morning 

Any help will be appreciated

Source : https://bitbucket.org/saurabhsrb/school-management-system/src

:(

| 2.0.9      | 
| 5.5.12      | 
| Windows7 |

**Comment by samdark** [comment]
Duplicate of #12049?
