### ISSUE TITLE
Hi, how to add custom AuthClient icon in standart component yii2-authclient?

### ISSUE THREAD

**Issue by denoll** [yiisoft/yii2#12064]
Hello, please tell me how to add custom AuthClient icon in standart component yii2-authclient?
After the last update Yii2 was gone one client of a regional network of customers icon, how to add another icon to my custom client?

**Comment by klimov-paul** [comment]
@denoll, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
