### ISSUE TITLE
Class-level Event handler does not set the $event->sender property.The documentation might be wrong. 

### ISSUE THREAD

**Issue by DrmagicE** [yiisoft/yii2#12076]
Class-Level Event Handlers chapter of The Definitive Guide to Yii 2.0 indicates that:

>  A class-level event is not associated with a particular object. As a result, it will cause the invocation of class-level event handlers only. For example:

```
use yii\base\Event;
Event::on(Foo::className(), Foo::EVENT_HELLO, function ($event) {
    echo $event->sender;  // displays "app\models\Foo"
});
Event::trigger(Foo::className(), Foo::EVENT_HELLO);

```
> Note that, in this case, $event->sender refers to the name of the class triggering the event instead of an object instance.

[http://www.yiiframework.com/doc-2.0/guide-concept-events.html#class-level-event-handlers](url)
But the yii\base\Event::trigger() only set $event->sender when the $class parameter is an object：

```
        if (is_object($class)) {    
            if ($event->sender === null) {
                $event->sender = $class;
            }
            $class = get_class($class);
        } else {
            $class = ltrim($class, '\\');
        }         
...
```      
I have  tried to run the above code, and the $event->sender is null. I wonder whether there is a bug or just a mistake in the documentation.
### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 
| Operating system |

**Comment by mdmunir** [comment]
correct me if i am wrong.
You should not call `Event::trigger()` directly. You should call `trigger()` from instance class.
```php
Event::on(Foo::className(), Foo::EVENT_HELLO, function ($event) {
    echo $event->sender;  // displays "app\models\Foo"
});

$foo = new Foo();
$foo->trigger(Foo::EVENT_HELLO);

// or
class Bar extends Foo
{

}

$bar = new Bar();
$bar->trigger(Foo::EVENT_HELLO);
```

**Comment by DrmagicE** [comment]
@mdmunir Thanks.But I think `Event::trigger()` also can be called directly.
It seems that it is a mistake in documentation.The comments of `$sender ` is as  below:
```
   /**
     * @var object the sender of this event. If not set, this property will be
     * set as the object whose "trigger()" method is called.
     * This property may also be a `null` when this event is a
     * class-level event which is triggered in a static context.
     */
     public $sender;
```
The comments says that **This property may also be a `null` when this event is a class-level event which is triggered in a static context.** .But the documentation says that when triggering a class-level event by calling the static method` yii\base\Event::trigger()`,**$event->sender refers to the name of the class triggering the event**.

The Documentation seems wrong.

**Comment by mdmunir** [comment]
ya, it seems the documentation wrong.

**Comment by klimov-paul** [comment]
The doc comments for `Event::sender` says it should be `null` for class-based events:
https://github.com/yiisoft/yii2/blob/master/framework/base/Event.php#L32-L38

So I suggest it is a error in the guide.

**Comment by klimov-paul** [comment]
Resolved by commit d55d8f60705a2fafc87df1a6abd70c077eaa093d

**Comment by Bob-Al-Max** [comment]
Can sombody give an example how class-level Event handler should be use? 
For example  - I have an ActiveRecord class "Posts", so where should I put this code Event::on(ActiveRecord::className(), ActiveRecord::EVENT_AFTER_INSERT, function ($event) {
    Yii::debug(get_class($event->sender) . ' добавлен');
});  ?  In a class method? And then trigger the event in the PostController? It's not clear for me. Any help appreciate/

**Comment by samdark** [comment]
No. Somewhere outside before actually using AR.

**Comment by rugabarbo** [comment]
@Bob-Al-Max 
If you need help, please go to the forum: http://www.yiiframework.com/forum/
Don't use GitHub as forum, please.
