### ISSUE TITLE
Use of default parameters while URL creation.

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#12070]
Suppose we have a rule:
~~~
[
    'pattern' => 'post/<page:\d+>/<tag>',
    'route' => 'post/index',
    'defaults' => ['page' => 1],
],
~~~
This rule returns false while trying to create a URL without explicit `page` specification.
~~~
$rule->createUrl($manager, 'post/index', ['tag' => 'foo']); // false
~~~ 
Why can't we use default parameters in pattern while URL creation? Is it by design? 

It seems to me that we should be able to use optional parameters both while URL creation and parsing.

**Comment by Kolyunya** [comment]
@cebe it's very easy to verify - we can add a new test case in `yiiunit\framework\web\UrlRuleTest` at line `176`:

~~~php
['post/index', ['tag' => 'a'], 'post/2/a'],
~~~

This test case fails.

**Comment by mdmunir** [comment]
> Is it by design?

 I think yes. This rule only match with url `['post/index', 'page' => 1, ...]`

**Comment by mdmunir** [comment]
if you need default value `$_GET['page']`, you should define it at action method
```php
public function actionIndex($page = 1)
{
    ...
}
```

**Comment by rob006** [comment]
Duplicates #10970

**Comment by Kolyunya** [comment]
@mdmunir it turns out that this is a bug.

@rob006 thank you!
