### ISSUE TITLE
Accessing parent Module from Model/ActiveRecord

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#12084]
This is a feature request/question. Currently the [modules documentation](http://www.yiiframework.com/doc-2.0/guide-structure-modules.html) provides no information on the topic of models. Modules can contain models (activerecordss), but there is no obvious way to access the module that contains them. How do we do this?

When we want to access the module from a controller (contained within same module), we can do so via ```$this->module```. This is not possible in models. How can we access the module from a contained model without forcing the module users to use a predefined fixed module ID (eg. ```Yii::$app->getModule('fixed-id')```)?

A simple use case for this is allowing the module user to tune validation variables for the modules/activerecords contained within.

**Comment by mdmunir** [comment]
to access current module, use `Yii::$app->controller->module`

**Comment by Charius** [comment]
And how you want to tune validation variables for models? Through the config file? I guess this make no sense, cause user shouldn't have the ability you describe. Or who is the user of module, other modules? If so, then you should just extend models but not change their behaviour, IMO.

**Comment by vercotux** [comment]
@mdmunir This is a neat trick. Thanks.

@Charius Yes, through the config file. It makes perfect sense to allow module users to define certain things such as string lengths for validation. The user is of course a programmer who is using other modules. And no, extending modules is not the way to go, especially when you include 10s or 100s of modules (see \yii\rbac\Rule).

@klimov-paul This is not a question. It is a feature request for the missing documentation.

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/guide-structure-modules.html#accessing-modules

**Comment by vercotux** [comment]
@mdmunir That's all fine, but it says nothing about models specifically. Currently it seems like there is no standard way of implementing models in modules. Whatever flies. Should module users be overriding the models? Should the model developers somehow make them reusable? What about migrations for active records? Should everything be fixed? Not a word about any of this.
