### ISSUE TITLE
session_destroy(): Session object destruction failed

### ISSUE THREAD

**Issue by Shin1gami** [yiisoft/yii2#12085]
### What steps will reproduce the problem?

- create default `yii2-advanced` app (`development` env)
- add this component config:
```
'session' => [
    'class' => 'yii\web\CacheSession',
    'cache' => 'sessionCache',
    'timeout' => 600000
 ],
'sessionCache' => [
    'class' => 'yii\caching\FileCache',
    'cachePath' => '@runtime/cache/session'
]
```
- log in
- log out

### What is the expected result?
proper logout
### What do you get instead?
php warning
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10-dev|
| PHP version      | PHP 7.0.6|
| Operating system | Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux|

``` in /srv/www/yii2t/vendor/yiisoft/yii2/web/Session.php:198 ```

**Comment by cebe** [comment]
can you please paste the full stack trace of the error?

**Comment by samdark** [comment]
@Shin1gami should be OK now. Thanks for reporting.
