### ISSUE TITLE
Asset converter fails to detect conversion errors

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#12096]
### What steps will reproduce the problem?
1. Install `lessc` compiler.
2. Configure application to the debug mode.
3. Define an asset bundle with `.less` files in it.
4. Register the asset bundle in a view.
5. **Revoke write permissions from the server process in the directory where compiled `.css` should be written**.
6. Open the page with that view in a browser.

### What is the expected result?
An error page should be shown saying that asset could not be converted.

### What do you get instead?
No errors occur.

### Additional info
* The `lessc` command returns correct exit code (`1`) when I execute it manually.
* `$status = proc_close($proc);` in `AssetConverter::runCommand()` always equals `0` even when no `.css` files were written by the `lessc`.

**Comment by Morr123** [comment]
http://web-sprints.ru/ustanovka-yii2-na-openserver/  there help you

**Comment by klimov-paul** [comment]
Indeed, according to the php.net using `proc_close()` result for status code obtained may be unreliable:
http://php.net/manual/en/function.proc-close.php

However, I am unsure in which way it can be fixed.

**Comment by klimov-paul** [comment]
I am unable to reproduce your problem: the proper error is thrown n case there is not enough permission to write less compile result file.
Thus there is no way I can help you.

**Comment by klimov-paul** [comment]
@Kolyunya, try to modify `AssetConverter::runCommand()` in following way:

```php
protected function runCommand($command, $basePath, $asset, $result)
    {
        $command = Yii::getAlias($command);
        
        $command = strtr($command, [
            '{from}' => escapeshellarg("$basePath/$asset"),
            '{to}' => escapeshellarg("$basePath/$result"),
        ]);
        $descriptor = [
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];
        $pipes = [];
        $proc = proc_open($command, $descriptor, $pipes, $basePath);
        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        foreach ($pipes as $pipe) {
            fclose($pipe);
        }
        $status = proc_get_status($proc);
        $exitCode = proc_close($proc);
        if (!$status['running']) {
            $exitCode = $status['exitcode'];
        }

        if ($exitCode === 0) {
            Yii::trace("Converted $asset into $result:\nSTDOUT:\n$stdout\nSTDERR:\n$stderr", __METHOD__);
        } elseif (YII_DEBUG) {
            throw new Exception("AssetConverter command '$command' failed with exit code $exitCode:\nSTDOUT:\n$stdout\nSTDERR:\n$stderr");
        } else {
            Yii::error("AssetConverter command '$command' failed with exit code $exitCode:\nSTDOUT:\n$stdout\nSTDERR:\n$stderr", __METHOD__);
        }

        return $exitCode === 0;
    }
```

And notify me if works for you.

**Comment by Kolyunya** [comment]
@klimov-paul gonna try it. Thank you!

**Comment by klimov-paul** [comment]
Closing since there is no way to reproduce and no response from the author.
