### ISSUE TITLE
Confusing wording in doc-2.0/guide-tutorial-i18n.html#Specifying default translation

### ISSUE THREAD

**Issue by jaaf** [yiisoft/yii2#12098]
I found this section's introduction a bit obscure and confusing:

> **Specifying default translation**
> You can specify default translations that will be used as a fallback for categories that don't match any other translation. This translation should be marked with *. In order to do it add the following to the application config:

I suggest:

> **Specifying default message source**
> You can specify a default message source that will be used as fallback for a category that don't match any configured category. You can do that by configuring a wildcard category `*`. In order to do that, add the following to the application config:

**Comment by samdark** [comment]
Fixed. Thank you for a good suggestion.
