### ISSUE TITLE
Sometimes, when opening /backend/web it renders everything from /frontend/web/

### ISSUE THREAD

**Issue by hobroker** [yiisoft/yii2#12102]
I don't know how to reproduce the problem, but if I put a `die('test');` on /backend/web/index.php, it works once properly and then it starts to render the /frontend/

It seems to ignore everything in /backend/ besides /backend/web/index.php
And if I give a syntax error to the /backend/web/config/main.php it doesn't show any error.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | PHP 5.5.9-1ubuntu4.19
| Operating system | Ubuntu 14.04.4 LTS

**Comment by Alex-Code** [comment]
Is this based off the advanced or basic template?
Which webserver are you using?
What's your server config for routing to front and backend?

**Comment by hobroker** [comment]
It's based off the advanced template.
I'm using Apache/2.4.7 (Ubuntu).
The config files were not changed. They're the same as the advanced

Turns out it's because the YII_DEBUG constant, which was set to true. I've set it to false and it works as expected.

Why is that?

**Comment by hobroker** [comment]
Ok, so I solved it by removing /backend/runtime/cache/ and /backend/runtime/debug/
