### ISSUE TITLE
Empty Pragma header in HttpCache

### ISSUE THREAD

**Issue by sergeymakinen** [yiisoft/yii2#12100]
### What steps will reproduce the problem?

Define any callback in `HttpCache` and check for output headers.

### What is the expected result?

No empty `Pragma` header or a `Pragma` header with some value (according to 14.32 of the [spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)). It looks like there should be no `Pragma` at all.

### What do you get instead?

Empty `Pragma` header (see the [source code](https://github.com/yiisoft/yii2/blob/master/framework/filters/HttpCache.php#L192)).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.23
| Operating system | Debian

**Comment by cebe** [comment]
As far as I remember this is to override the default `Pragma` header generated by PHP when a session is started.

Consider the following PHP script, which just outputs "hi":

```
$ curl -s -i http://localhost/dev/test.php
HTTP/1.1 200 OK
Date: Tue, 09 Aug 2016 12:43:14 GMT
Server: Apache/2.4.10 (Debian)
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

hi
```

as soon as I add a call to `session_start()` I get the following:

```php
<?php
session_start();
echo "hi
```

```
$ curl -s -i http://localhost/dev/yiisoft/yii2/apps/basic/test.php
HTTP/1.1 200 OK
Date: Tue, 09 Aug 2016 12:48:14 GMT
Server: Apache/2.4.10 (Debian)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=o0dljplf3mjgfk40rhbcagse90; path=/
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

hi
```

**Comment by cebe** [comment]
Similar results can be seen on the basic app.

First request to the main page which has no session:

```
$ curl -s -i http://localhost/dev/yiisoft/yii2/apps/basic/web/ | head 
HTTP/1.1 200 OK
Date: Tue, 09 Aug 2016 12:49:49 GMT
Server: Apache/2.4.10 (Debian)
Set-Cookie: _csrf=25cb6e4be8cba1cea538e6aca5e42b0cf2c1ce5ce1961701c388e69a733787f0a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22PcamLcFD8gwHye7e_07ENxwsEDx-XeCb%22%3B%7D; path=/; httponly
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html lang="en-US">
```

second request to the contact page which creates a session for the CSRF validation:

```
$ curl -s -i http://localhost/dev/yiisoft/yii2/apps/basic/web/index.php?r=site/contact | head -n 14
HTTP/1.1 200 OK
Date: Tue, 09 Aug 2016 12:51:05 GMT
Server: Apache/2.4.10 (Debian)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=m6vst7n686h1e3ipavkf0aaqa2; path=/; HttpOnly
Set-Cookie: _csrf=66065d3503cf7e5cd8e6e30eed84a7e52e508b025288ec5f71ae4b00da6252e2a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22e5_3YuGodaEPd--cPrx2R9njL0y0EKKk%22%3B%7D; path=/; httponly
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html lang="en-US">
```

**Comment by cebe** [comment]
since https://github.com/yiisoft/yii2/commit/f2d477dce6ab0d5f215e8a4e285e8eda646eb673#diff-9b712893364682c254348705f9821220L116 this call should not be necessary anymore since the header will be removed by http://php.net/manual/en/function.session-cache-limiter.php so it should be fine to remove the call.

**Comment by cebe** [comment]
verified that on the basic app, cache control headers are sent as expected.
