### ISSUE TITLE
ActiveRecord CONCAT bug

### ISSUE THREAD

**Issue by dkduyanh** [yiisoft/yii2#12108]
### What steps will reproduce the problem?

$model = User::find()->select(['id', 'fullname' => new Expression("CONCAT(`user_name`, `last_name`)") ])->all();

echo $model[0]->id;                   //==> OK
echo $model[0]->fullname;         //==> Error: Getting unknown property: app\models\User::fullname

//generated query (raw query)
SELECT `id`, CONCAT(`user_name`, `last_name`) AS `fullname` FROM `users`  //==> run OK

### What is the expected result?
the fullname from the MySQL CONCAT function 

### What do you get instead?
Error: Getting unknown property: app\models\User::fullname

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  5.4
| Operating system |  Windows 10

**Comment by rob006** [comment]
Do you have `fullname` property in `User` model?

**Comment by Alex-Code** [comment]
As @rob006 said, You'll either need a property of `fullname` in the class or return the result as an array `->asArray()->`

**Comment by dkduyanh** [comment]
It works perfectly when have fullname property in User model. Thanks all.
