### ISSUE TITLE
yii\rest\Serializer extraFields() as array

### ISSUE THREAD

**Issue by njspok** [yiisoft/yii2#12107]
### What steps will reproduce the problem?
Send rest api query as ?expand[0]=one,two,three

### What is the expected result?
Some domain errors or ignore this situation

### What do you get instead?
Error preg_split() expects parameter 2 to be string, array given

### Additional info

```
yii\rest\Serializer
    protected function getRequestedFields()
    {
        $fields = $this->request->get($this->fieldsParam);
        $expand = $this->request->get($this->expandParam);

        // $expand may be array, not validation

        return [
            preg_split('/\s*,\s*/', $fields, -1, PREG_SPLIT_NO_EMPTY),
            preg_split('/\s*,\s*/', $expand, -1, PREG_SPLIT_NO_EMPTY),
        ];
    }
```

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 7.0.8
| Operating system |  ubuntu 14.04

**Comment by cebe** [comment]
fixed, thanks for reporting!
