### ISSUE TITLE
Join table with a known value at block "on"

### ISSUE THREAD

**Issue by Razzwan** [yiisoft/yii2#12104]
### What steps will reproduce the problem?
If want use relation in model as that:
~~~php
    /**
     * @param int $val - value from query param
     */
    public function getRelation($val = 25)
    {
        return $this->hasMany(RelationTable::className(), [
            'rel_id' => 'id',
            'other_id' => $val,
        ]);
    }
~~~

### What is the expected result?
I mean, it would be converted to sql
~~~SQL
...  
  LEFT JOIN rel as relationAlias 
    ON 
      relationAlias.rel_id = mainAlias.id 
      AND relationAlias.other_id = 25 
...
~~~

### What do you get instead?
But this converted to:
~~~SQL
...  
  LEFT JOIN rel as relationAlias 
    ON 
      relationAlias.rel_id = mainAlias.id 
      AND relationAlias.other_id = mainAlias.25
...
~~~
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      | 7.0.6
| Operating system | Ununtu 16.04

**Comment by rob006** [comment]
You should use `andOnCondition()` in this case.

**Comment by Razzwan** [comment]
@rob006 Thank you, now try

**Comment by Razzwan** [comment]
Yes, my problem is solved with `andOnCondition()`. Closed
