### ISSUE TITLE
Yii2框架中的一个小问题，控制器action被加载两次的bug

### ISSUE THREAD

**Issue by leyuxinsi** [yiisoft/yii2#12118]
这是我前几天在开发一个文章阅读统计功能时候发现的问题。当时我想做的是页面访问一次，数据库访问量+1，但是无意中我发现，每次刷新后，访问量居然增加2个。

初步以为模型被调用了2次，后来排查发现并不是。于是我用file_put_contents函数，随机写入文件发现，我的所有控制器action都被执行了两次。测试代码如下：

```php
public function actionIndex()
 {
        file_put_contents(rand(10000,99999).'.txt','123');
        return $this->render('index');
 }
```

以上代码会生成两个文件。

后来我发现，每当我注释掉`return $this->render('index');`时候，问题就会被解决。所以我就去比对官方原始安装包和我的代码，发现只要我在layout的html代码里面的head中加上`<link rel="icon" href="">`并且其中的href值为空，那么控制器的action就会被加载两次，如果我给href加上一个链接值，那么控制器就没有问题。

这个问题，在发生错误时候，没有任何的报错，程序也运行的很好，只是在有些情况下会发现异常，比如我统计文章访问量。我想应该属于一个bug

还有一个注意点：当上面那个href值为空时候，只要控制器内有内容输出，比如echo 123或者var_dump，那么这个控制器加载两次的问题也不会发生。

**Comment by cebe** [comment]
> <link rel="icon" href="">

adding that code will cause the browser to try loading the icon from the main URL so each time you load the page, the browser will access the same URL again to load the icon. that is why your action is called twice.
