### ISSUE TITLE
Yii2 Query Builder Issue - Using MySQL user-variables

### ISSUE THREAD

**Issue by edmondetemi** [yiisoft/yii2#12111]
We have tried to build a query in Yii2 to select 2 articles from each category, but the problem is with the user-variables and with the CASE statement as we see Yii2 doesn't support them in this way, so can anyone please explain or correct us how is the right way to use them in Yii2 in this case.

Thank you in advance.

------

```php
$varsQuery = (new \yii\db\Query())
			->select(['@var_category_id:=NULL', '@rn:=NULL']);
			
$subtableQuery = (new \yii\db\Query())
			->select(['category_id', '@rn:=(CASE WHEN @var_category_id = category_id THEN @rn +1 ELSE 1 END) AS rn', '@var_category_id:=category_id'])
			->from(['vars' => $varsQuery, 'articles'])
			->where(['category_id' => $categories])
			->orderBy('published_date ASC');
			
$query = (new \yii\db\Query())
			->select(['c.id', 'sub_table.*'])
			->from(['sub_table' => $subtableQuery])
			->innerJoin('categories c', 'c.id = sub_table.category_id')
			->where('rn' <= 2)
			->orderBy('published_date DESC');
```

**Comment by Alex-Code** [comment]
Does this work? Set the variables before the query.
```php
\Yii::$app->db->createCommand('SET @var = NULL;')->execute();
```

**Comment by edmondetemi** [comment]
Thank you Alex but is not working.

**Comment by samdark** [comment]
How exactly it's not working?

**Comment by edmondetemi** [comment]
After i set the variables as you said shows me this error:

PHP Fatal Error – yii\base\ErrorException
Allowed memory size of 134217728 bytes exhausted (tried to allocate 65552 bytes)

**Comment by samdark** [comment]
You mean it happens w/ only

```php
\Yii::$app->db->createCommand('SET @var = NULL;')->execute();
```

?

**Comment by edmondetemi** [comment]
Yes

**Comment by samdark** [comment]
Looks like PDO bug. Yii doesn't do much in this case. Just passing query to PDO for execution.

**Comment by edmondetemi** [comment]
Now shows me this error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column '@var_category_id:=category_id' in 'field list'.

With this code now:

		\Yii::$app->db->createCommand('SET @var_category_id = NULL, @rn = NULL;')->execute();
		/*
		$varsQuery = (new \yii\db\Query())
			->select(['@var_customer_id', '@rn']);
			*/
		$subtableQuery = (new \yii\db\Query())
			->select(['*', '@rn:=(CASE WHEN @var_category_id = category_id THEN @rn +1 ELSE 1 END) AS rn', '@var_category_id:=category_id'])
			->from(['vars' => $varsQuery, 'articles'])
			//->from(['vars' => $varsQuery, 'articles'])
			->where(['category_id' => $categories])
			->orderBy('published_date ASC');
			
		$query = (new \yii\db\Query())
								->select(['c.id', 'sub_table.*'])
								->from(['sub_table' => $subtableQuery])
								->innerJoin('categories c', 'c.id = sub_table.category_id')
								->where('rn' <= 2)
								->orderBy('sub_table.published_date DESC');

**Comment by samdark** [comment]
Well, this case is different. It's escaping. You need to wrap these names with https://github.com/yiisoft/yii2/blob/master/framework/db/Expression.php

**Comment by edmondetemi** [comment]
Now i have tried to use those variables and cases with Expression but still get an error:

Error:
PHP Fatal Error – yii\base\ErrorException
Allowed memory size of 134217728 bytes exhausted (tried to allocate 65552 bytes)

The code:

$varsQuery = (new \yii\db\Query())
			->select([new \yii\db\Expression('@var_category_id:=NULL, @rn:=NULL')]);
			
		$subtableQuery = (new \yii\db\Query())
			->select(['*', new \yii\db\Expression('@rn:=CASE WHEN @var_category_id = category_id THEN @rn +1 ELSE 1 END AS rn'), new \yii\db\Expression('@var_category_id:=category_id')])
			->from(['vars' => $varsQuery, 'articles'])
			->where(['category_id' => $categories])
			->orderBy('published_date DESC');
			
		$query = (new \yii\db\Query())
								->select(['sub_table.*'])
								->from(['sub_table' => $subtableQuery])
								->innerJoin('categories c', 'c.id=sub_table.category_id')
								->where('rn' <= 2);

**Comment by samdark** [comment]
Have you tried adding LIMIT to the query? Probably it's getting too many records.

**Comment by edmondetemi** [comment]
Thnx anyway @samdark, the problem was so tiny in visibility, but caused a big problem by escaping the limit.

The problem was on:

->where('rn' <= 2);

Corrected in this way:

->where(['<=', 'rn', 2])



Thank you once again for your help.
