### ISSUE TITLE
Possible ExistValidator optimization

### ISSUE THREAD

**Issue by iBotPeaches** [yiisoft/yii2#12125]
### What steps will reproduce the problem?

Having a large amount of ActiveRecord's (500+) that include` ExistValidators` all cause `SELECT EXISTS(SELECT * FROM foo WHERE id=bar)` database calls. On a table that has 4 foreign key relations, this is 4 * n queries and after trying to do 500 at once, that quickly balloons to 2k queries.

### What is the expected result?
Static cache much like done on the RBAC rules.

### What do you get instead?
No cache for `ExistValidator`, so repeated calls for the same foreign_key cause a new query thus making response time much greater. 

### Additional info

This of course introduces the problem of more memory use and might not work if system contains too many records, but I'd take more memory use than more queries in our case. It may be beneficial to add `cache` options like `DbManager` of rbac. Gauging interest/feedback before I put forth a PR.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.15
| Operating system | centos7

**Comment by samdark** [comment]
How did you get 500 records validated at once?

**Comment by iBotPeaches** [comment]
There not, my bad on explaining. They are iterated through and saved individually so the various `beforeValidate` and `afterSave` events can fire. At this point during the save individually, validation is triggered and thus above happens.

I could probably disable validation during the save at that point, but I can't trust the data so I think I need it.

Thanks for quick response.

**Comment by samdark** [comment]
If you're sure these are always valid, skip validation. If you aren't sure then exist validation isn't the kind of validation to be cached. Each second database may change its state so it should be validated just before it's saved.
