### ISSUE TITLE
Problem with php links in \yii\db\ActiveRecord

### ISSUE THREAD

**Issue by forzi** [yiisoft/yii2#12134]
### What steps will reproduce the problem?
```
  $a = [1, 2, 3];
  foreach ($a as &$val) {}
  FormsCompare::find()->select('id')->where(['id' => $a])->all();
  echo $a[2];
```

### What is the expected result?
3 #integer

### What do you get instead?
:qp2 #string

### Additional info
FormsCompare extends \yii\db\ActiveRecord - absolute normal yii2 model with connection to mysql with minimal extended changes.

| Q                | A
| ---------------- | ---
| Yii version      |   2.0.7-dev
| PHP version      |  5.6.23
| Operating system |  linux

**Comment by samdark** [comment]
It's how PHP works.
