### ISSUE TITLE
302 jump to http://site/login

### ISSUE THREAD

**Issue by shyandsy** [yiisoft/yii2#12144]
### What steps will reproduce the problem?
I have a project which runs on the machine A nicely. Today I copy all files on the machine A to the machine B, and also copy the database and correspond user to machine B.

1.if I write <?php echo "1111";?> in the index.php  it works
2.if I use the index.php of Yii2 project, yii2 always return http 302 and jump tp http:site/login
 
### What is the expected result?
show site/login when I open website

### What do you get instead?
http://site/login  dns not found

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |     2.0.9
| PHP version      |  7.0.7
| Operating system |  centos 7 x64
| nginx |  1.10

**Comment by cebe** [comment]
hard to tell what is wrong but as it works on one server and not on the other it is very likely a problem with your setup and not yii. it could be related to the FCGI environment variables configured in your nginx config. compare the output of `<?php print_r($_SERVER); ?>` on each machine.

**Comment by shyandsy** [comment]
the index.php of yii2 has been executed, so I dont think the problem is on the environment, and the $server is exactly same.

are there any other way to analysis what is wrong ?

**Comment by githubjeka** [comment]
May be PrettyUrl of urlManager setting ?
See http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#using-pretty-urls

**Comment by shyandsy** [comment]
@githubjeka 
thank you very much. I solved that problem after read your hint.
```php
'request' => [
            //'baseUrl'=>'/',                // it works after remove this line
            'csrfParam' => '_csrf-dealer',
        ],
```
