### ISSUE TITLE
Yii2 ActiveDataProvider fetch result correct but showing totalCount 0 in summary text

### ISSUE THREAD

**Issue by ak868308** [yiisoft/yii2#12141]
I am trying to filter data using dropdown so the query executed perfectly produces a result is always correct but in summary total count is '0' always but not first time when page loaded. This is annoying me I am completely unable to trace the error through debugging tool. But the important thing is that the same code is working fine on my local machine whenever I deployed the same code to production it shows 0 counts
My Model search code : 

`public function search($params) {

    $query = Tasks::find();

    $query->where(['q_id' => $this->job_id]);

    // $query->orderBy('created_at DESC');

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'pagination' => [
            'pageSize' => 20,
        ],
    ]);

    $this->load($params);

    if (!empty($this->keyword) || $this->keyword != '') {

        $query->andWhere('MATCH(task_title,task_description, priority) AGAINST("' . $this->keyword . '*" IN BOOLEAN MODE)');
    }

    if (is_numeric($this->filterby)) {
        $query->andFilterWhere(['status' => $this->filterby]);
    } else {
        $query->andFilterWhere(['IN', 'status', [10, 4, 2]]);
    }

    if (!empty($this->sortby) || $this->sortby != '') {
        $query->orderBy($this->sortby . ' DESC');
    }

    return $dataProvider;
}`

**Comment by cebe** [comment]
> whenever I deployed the same code to production it shows 0 counts

if it works fine in one environment it is unlikely a bug in yii. also your code has several issues that may allow SQL injection. please fix that first and report back if there is a way to reproduce the problem.

**Comment by ak868308** [comment]
Problem with this line 
`$query->where(['q_id' => $this->job_id]);`
When I comment this line all are working fine. while I checked $this->job_id produces a value.
Only the difference is in my controller used like this
`$searchModel->job_id = Yii::$app->request->get('job_id');`
without formName. My other prams are coming with Model ie. formName like XyzModel['keywor'] while job is dont have it.
