### ISSUE TITLE
Silent ActiveRecord::updateAttributes on new record

### ISSUE THREAD

**Issue by AnatolyRugalev** [yiisoft/yii2#12143]
### What steps will reproduce the problem?

Call `ActiveRecord::updateAttributes()` on new `ActiveRecord` instance. Example:

```php
$post = new Post();
$post->getIsNewRecord();            // true
$post->updateAttributes(['status' => Post::STATUS_ACTIVE]);
$post->getIsNewRecord();            // false
$post->save(false);                 // true
```

### What is the expected result?

Exception when updating attributes of new record

### What do you get instead?

Record is not saved into database because `getIsNewRecord()` lies about actual status

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.0.8

**Comment by klimov-paul** [comment]
Resolved by commit 143f9070af42bff3b86255c6c18931cf3d732c2a
