### ISSUE TITLE
Exception – yii\authclient\InvalidResponseException ( with github )

### ISSUE THREAD

**Issue by zeevy** [yiisoft/yii2#12146]
### What steps will reproduce the problem?
Enable social login via AuthClient Lib
### What is the expected result?
Success full login when using Github
### What do you get instead?
Request failed with code: 403
### Additional info

Exception – yii\authclient\InvalidResponseException
Request failed with code: 403, message: Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

In "vendor\yiisoft\yii2-authclient\BaseOAuth.php" Line 221.

May be due to the change that authclient now uses "yii2-httpclient" instead of curl

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.19
| Operating system |  Windows 10

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2-authclient/issues/128
