### ISSUE TITLE
unique validator does not show custom message

### ISSUE THREAD

**Issue by omidgh88** [yiisoft/yii2#12152]
### What steps will reproduce the problem?
when i define unique rule for multiple fields like:
[['type_id', 'title'], 'unique', 'targetAttribute' => ['type_id', 'title'], 'message' => Yii::t('app', 'Duplicated Data Entries.')],

### What is the expected result?
i expecte to show Yii::t('app', 'Duplicated Data Entries.')

### What do you get instead?
but default message is shown.

### Additional info
when i remove "'targetAttribute' => ['type_id', 'title']," part my message has been shown but it is not the rule i want.

| Yii version      2.0.9
| PHP version      5.5.34
| Operating system windows 10

**Comment by rob006** [comment]
You should use `comboNotUnique` for error message in this case: https://github.com/yiisoft/yii2/blob/master/framework/validators/UniqueValidator.php#L70

**Comment by omidgh88** [comment]
thanks a lot it works.

**Comment by cebe** [comment]
@rob006 thanks for [noting the BC break](https://github.com/yiisoft/yii2/pull/11323#issuecomment-239628861), not sure if we should introduce a fallback in the code to avoid the break or just add a note to the UPGRADE docs. @yiisoft/core-developers opinions?

**Comment by rob006** [comment]
@cebe I think that both messages should be configured by `message` property and `comboNotUnique` should be deprecated. Another property for message is just confusing and does not give any benefit. So :+1: for fallback,  but for `comboNotUnique` uses.

**Comment by SilverFire** [comment]
I suggest the following fallback:

```php
    public function init()
    {
        parent::init();
        if ($this->message === null) {
            if (is_array($this->targetAttribute)) {
                $this->message = Yii::t('yii', 'The combination {values} of {attributes} has already been taken.');
            } else {
                $this->message = Yii::t('yii', '{attribute} "{value}" has already been taken.');
            }
        }
    }
```

And use the appropriate placeholders with the `$message` depending on what is `targetAttribute`

**Comment by rob006** [comment]
@SilverFire If `comboNotUnique` is set you should use it as default value for `message`.

**Comment by SilverFire** [comment]
@rob006 yepp, you're right :)
