### ISSUE TITLE
BaseHtml class has e error

### ISSUE THREAD

**Issue by 3212lin** [yiisoft/yii2#12167]
### What steps will reproduce the problem?
when you use the method img of the yii\helpers\BaseHtml,it will produce a error
it will create html like this `<images>...</images>`

### What is the expected result?
`<img alt='' src='the image url'>`

### What do you get instead?
on the line 441 in the yii\helpers\BaseHtml, 

replace" the return static::tag('images', '', $options) " to the " return static::tag('img', '', $options); "

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.5
| Operating system |

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L441
