### ISSUE TITLE
Just not work

### ISSUE THREAD

**Issue by Piterden** [yiisoft/yii2#12164]
### What steps will reproduce the problem?
I have install Yii and try to serve - it is worked but throw exception, it's normal. I want model. Ok - generator Gii. I see CRUD, ok. Try to make model.
### What is the expected result?
Model
### What do you get instead?
den@probook ~/basic[0] $ ./yii gii/crud --controllerClass 'EventsController' --modelClass 'Event'
Running 'CRUD Generator'...

Code not generated. Please fix the following errors:

 - modelClass: Class '1' does not exist or has syntax error.
 - controllerClass: Controller class name must be suffixed with "Controller".

den@probook ~/basic[0] $ ./yii gii/crud --controllerClass 'PageController' --modelClass 'Event'
Running 'CRUD Generator'...

Code not generated. Please fix the following errors:

 - modelClass: Class '1' does not exist or has syntax error.
 - controllerClass: Controller class name must be suffixed with "Controller".

den@probook ~/basic[0] $ ./yii gii/crud --controllerClass 'app\controllers\PageController' --modelClass 'Event'
Running 'CRUD Generator'...

Code not generated. Please fix the following errors:

 - modelClass: Class '1' does not exist or has syntax error.
 - controllerClass: Controller class name must be suffixed with "Controller".

den@probook ~/basic[0] $ ./yii gii/crud --controllerClass app\controllers\PageController --modelClass 'Event'
Running 'CRUD Generator'...

Code not generated. Please fix the following errors:

 - modelClass: Class '1' does not exist or has syntax error.
 - controllerClass: Controller class name must be suffixed with "Controller".

den@probook ~/basic[0] $ 

### Additional info
I suppose 'suffixed' means 'ends with'.
You could tell me that there is something that I can find in docs. And you would be right I haven't open docs only read help of `yii` bash command.
I think, that if I can't create CRUD model from bash without docs - that would be better for me do not use this soft. First I want to create model and then to look at the docs to modernize it.

PS Red console color is allright)
| Q                | A
| ---------------- | ---
| Yii version  2.0.9    | 
| PHP version  PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS ) Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.8-0 | 
| Operating system ubuntu0.16.04.2 |

**Comment by samdark** [comment]
You've used wrong syntax. Parameters are `--name=value` with `=`.
