### ISSUE TITLE
PHP Fatal error: Call to a member function log() yii2/BaseYii.php on line 400

### ISSUE THREAD

**Issue by davidhagen** [yiisoft/yii2#12166]
### What steps will reproduce the problem?
if(empty($data) || empty($data['Step1']['email'] || empty(Step2(['study_reason'])))){
            throw new \yii\base\UserException( "Sorry, your session has expired" );
            Yii::setLogger('Session expired');
  }
It just throws error in the apache log file -
Call to a member function log() on a non-object in /var/www/vendor/yiisoft/yii2/BaseYii.php on line 400

It doen't likes this line - static::getLogger()->log($message, Logger::LEVEL_ERROR, $category);

I tried with php5.5.9 and php7. All same error

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5 and 2.0.9
| PHP version      | PHP Version 5.5.9-1 and also php version
| Operating system | Ubuntu 14.04

**Comment by Alex-Code** [comment]
You're calling `setLogger`, so changing the logger object to a string.
You need one of `Yii:error|info|trace|warning();` depending on your reason to log.
