### ISSUE TITLE
Add "trimWidth" to List Html helpers

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#12175]
**Feature request** – Add "trimWidth" to the specially handled options of List Html helpers.

When I generate a list input, e.g. a drop-down, from DB data, sometimes I need to trim the width of the strings used for options or labels. This is presentation logic so it belongs in the view. But it ends up being really messy.

yii\helpers\Html could help by adding "trimWidth" to the specially handled options of appropriate methods that, when set to an integer, does something like

    mb_strimwidth($text, 0, $width, '…', 'UTF-8')

Maybe "trimWidth" could also be set to a callable.

**Comment by klimov-paul** [comment]
I am against such change.

For drop-down width is usually set by CSS: e.g. CSS style limits the drop-down width in closed state, while  being opened it can exceed it.

![drop-down](https://cloud.githubusercontent.com/assets/1482054/17700813/f720133c-63cf-11e6-93e5-ba0099c7526d.jpg)

In case you compose select from some really long strings, you should handle possible trim on your own.

**Comment by samdark** [comment]
Agree that it's out of scope of Html helpers.

**Comment by tom--** [comment]
y'all understand this truncating strings, right? it's not about width of dom elements.

*width* refers here to string length taking into account that some non-latin characters count as double width. see [mb_strimwidth](http://php.net/manual/en/function.mb-strimwidth.php)

in some situations, a too long string can screw up your display. the best fix is not css but to truncate the string. e.g. 

![a grid view example](https://monosnap.com/file/0pN2CpZaKG0ibjFLYpWZ2uqDFrl1cQ.png)

**Comment by samdark** [comment]
You can truncate string with CSS.

**Comment by tom--** [comment]
Not if you want to allow wrap, iiuc.

**Comment by samdark** [comment]
You can do it for multiple lines as well.

**Comment by rob006** [comment]
@samdark How do you want to truncate multi-line string with CSS?

**Comment by samdark** [comment]
https://codepen.io/martinwolf/pen/qlFdp

**Comment by rob006** [comment]
It does not work on FF, not mention IE.

**Comment by samdark** [comment]
I've re-checked and it seems there's no way to do it with CSS within dropdown list. Still, since options for it are fed manually via an array, it is easy to truncate at that stage:

```php
$items = [
    'short' => 'This is the short text',
    'long' => 'This is the long long text which is here for a reason',
];

array_walk($items, function(&$item, $key, $prefix) {
    $item = StringHelper::truncate($item, 10);
})

echo Html::dropDownList('test', null, $items);
```

**Comment by samdark** [comment]
Overall doesn't seem to be responsibility of the widget itself so I'd leave that part to developer.
