### ISSUE TITLE
Проблема composer-plugin-api 1.0.0

### ISSUE THREAD

**Issue by ASYOU99** [yiisoft/yii2#12170]
Problem 1
- Installation request for yiisoft/yii2-composer 2.0.3 -> satisfiable
by yiisoft/yii2-composer[2.0.3].
- yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no
matching package found.
Problem 2
- yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no
matching package found.
- yiisoft/yii2 2.0.3 requires yiisoft/yii2-composer * -> satisfiable by
yiisoft/yii2-composer[2.0.3].
- Installation request for yiisoft/yii2 2.0.3 -> satisfiable by
yiisoft/yii2[2.0.3].
Пробовал разные версии асет-плагина, делал dow-grade composer ничего пока не помогает.
При попытке обновить сам плагин:
Problem 1
    - The requested package composer-plugin-api 1.1.0 is satisfiable by composer-plugin-api[1.1.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package composer-plugin-api 1.0.0 exists as composer-plugin-api[1.1.0] but these are rejected by your constraint.
  Problem 3
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no matching package found.
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no matching package found.
    - Installation request for yiisoft/yii2-composer (locked at 2.0.3) -> satisfiable by yiisoft/yii2-composer[2.0.3].

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.3
| PHP version      | 5.5
| Operating system | win7

**Comment by githubjeka** [comment]
альтернатива http://rmcreative.ru/blog/post/yii--fxp-i-asset-packagist

**Comment by klimov-paul** [comment]
Most likely you are using too old version of composer.
Try:

```
composer self-update
```

**Comment by ASYOU99** [comment]
Пробовал self-update ничего не меняется говорит что использую последнюю версию

**Comment by klimov-paul** [comment]
Try to use `yiisoft/yii2-composer` version  `2.0.4` instead of `2.0.3`

**Comment by ASYOU99** [comment]
тогда подскажите как отдельно вытянуть композер с одной версии и вставить ее в другую(или вставляется просто копипастом)

**Comment by ASYOU99** [comment]
все ок получилось спасибо. Не знаю может и тупо сделал: взял 2 файла composera из корня с последней версии advanced и просто скопировал себе в проект поверх своих.
