### ISSUE TITLE
adding the values of two different textboxes and displaying the result in 3rd textbox in YII

### ISSUE THREAD

**Issue by deepakparam** [yiisoft/yii2#12180]
Hello Everyone, 

I am new to YII framework and i am trying to learn it. I got stuck at a point need your Help!

My problem is:

adding the values of two different textboxes and displaying the result in the third textbox.

I have written a code for that, but its not working...Plz help me....
**The Code is as follows: - For calculation**
<?php  
    $script= <<<EOD
        $(function() {
             $('#Buy_Rate').change(function() {  
                updateTotal();
            });

            $('#Sell_Quantity').change(function() {  
                updateTotal();
            });

            var updateTotal = function () {
            var brate = parseInt($('#Buy_Rate').val());
            var sqty = parseInt($('#Sell_Quantity').val());
            var totalAmount = brate * sqty;

            if (isNaN(totalAmount) || totalAmount < 0 || totalAmount > 100000) {
                totalAmount = '';
            }

            $('#Net_Buy').val(totalAmount);
            };
            EOD;
            $this->registerJs($script, View::POS_READY);
         });             
    
    $this->registerJs($script);
?>

**The Code is as follows: - For view**
<?php
namespace app\models;

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Sharename;
use  yii\web\View;

/* @var $this yii\web\View */
/* @var $model app\models\ShareDetails */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="share-details-form">

    <?php $form = ActiveForm::begin(); ?>
        <div class="container">
            <div class="col-md-6">                
               <?= $form->field($model,'Share_Name')->dropDownList(
                    ArrayHelper::map(Sharename::find()->all(),'Share_Name','Share_Name'),    ['prompt'=>'Select Share']
                ) ?>

                <?= $form->field($model, 'Buy_Rate')->textInput(['maxlength' => true, 'placeholder' => $model->getAttributeLabel('Buy_Rate')]) ?>

                <?= $form->field($model, 'Buy_Quantity')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'Sell_Rate')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'Sell_Quantity')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'Brokerage')->textInput(['maxlength' => true]) ?>
            </div>
           
            <div class="col-md-6"> 
                <?= $form->field($model, 'Net_Buy')->textInput(['maxlength' => true, 'readOnly'=>true]) 

                ?>

                <?= $form->field($model, 'Net_Sell')->textInput(['maxlength' => true, 'readOnly'=>true]) ?>    

                <?= $form->field($model, 'Net_Position')->textInput(['maxlength' => true, 'readOnly'=>true]) ?>

                <?= $form->field($model, 'Remaining_Lot')->textInput(['maxlength' => true, 'readOnly'=>true]) ?>

                
            </div>
            <div class="col-md-12 form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?> 
</div>

Your help is greatly appriciated.....
| Q                | A
| ---------------- | ---
| Yii version      | 
| PHP version      | 
| Operating system |

**Comment by Alex-Code** [comment]
Please use the forum for questions, Git is for issue tracking.
http://www.yiiframework.com/forum/index.php/forum/42-general-discussions/
