### ISSUE TITLE
Hyphens in Urls don't work as expected

### ISSUE THREAD

**Issue by kategee** [yiisoft/yii2#12184]
Added a rule to my urlManager:

`'<controller:\w+>/<action:\w+>/<key:[0-9a-zA-Z_\-]+>' => '<controller>/<action>',`

have an action specified

`public function actionResetPassword( $key ) {
    echo $key;
}`

allowed action in behaviors: `reset-password`

Go to url: ~/action/reset-password/som3k3yh3r3 -> You get 404.

Go to url: ~/action/reset-password -> You get 400 request "Missing required parameter: key"

--

WORKS:

rule: `reset-password`

action: `actionResetpassword($key)`

url tested: `~/action/resetpassword/somekeyhere`

--

DOESN'T WORK:

rule: `reset-password`

action: `actionResetPassword($key)`

url tested: `~/action/reset-password/somekeyhere`

--

DOESN'T WORK:

rule: `reset-password`

action: `actionResetpassword($key)`

url tested: `~/action/reset-password/somekeyhere`

--

WORKS:

rule: `reset-password`

action: `actionResetPassword()`

url tested: `~/action/resetpassword`

--
OS: CentOS 6.5
PHP: 5.4.12
Yii: 2.0.9

**Comment by klimov-paul** [comment]
Duplicates #11766
