### ISSUE TITLE
bug: incorrect get cookies

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#12196]
```php
//set cookies
\Yii::$app->response->cookies->add(new \yii\web\Cookie([
            'name'=>'lang',
            'value'=>\Yii::$app->language,
            'expire'=>time()+3600*24*30,
        ]));
//get cookies
\yii\helpers\VarDumper::dump(\Yii::$app->request->cookies->getValue('lang'), 10, true); exit;
/* returns
yii\web\Cookie#1
(
    [name] => 'lang'
    [value] => 'en-US'
    [domain] => ''
    [expire] => null
    [path] => '/'
    [secure] => false
    [httpOnly] => true
)

//but expecting about 'en-US'
*/
Is it normally?
```

**Comment by exru** [comment]
coockies string "7eb8a9d0b2505537a34a61698556219c7dcd0bd19685e3d729f08fd36af47ff1a%3A2%3A%7Bi%3A0%3Bs%3A4%3A%22lang%22%3Bi%3A1%3BO%3A14%3A%22yii%5Cweb%5CCookie%22%3A7%3A%7Bs%3A4%3A%22name%22%3Bs%3A4%3A%22lang%22%3Bs%3A5%3A%22value%22%3Bs%3A5%3A%22en-US%22%3Bs%3A6%3A%22domain%22%3Bs%3A0%3A%22%22%3Bs%3A6%3A%22expire%22%3BN%3Bs%3A4%3A%22path%22%3Bs%3A1%3A%22%2F%22%3Bs%3A6%3A%22secure%22%3Bb%3A0%3Bs%3A8%3A%22httpOnly%22%3Bb%3A1%3B%7D%7D"

**Comment by exru** [comment]
yii version 2.0.9

**Comment by SilverFire** [comment]
Failed to reproduce.
