### ISSUE TITLE
`Html::errorSummary` dupliate errors and errors beyond first one

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#12193]
Currently `Html::errorSummary` will display only the first error message for attributes having several errors attached:

```PHP
$model->addError('a1', 'Error1');
$model->addError('a1', 'Error2');
echo Html::errorSummary($model);
```

Also, sometimes the same error message can be added to the different model attributes. When the errors are displayed under each input field in the form such duplicate error message looks OK. But when the errors are displayed as a separate list with `errorSummary` it makes absolutely no sense to display duplicate error messages several times.

```PHP
// ...
[['a1', 'a2'], 'unique', 'targetAttribute' => ['a1', 'a2']],
[['first_name', 'last_name'], 'exist', 'targetAttribute' => ['a1', 'a2'], 'message' => 'The user with the specified name does not exist']
// ...
echo Html::errorSummary($model);
```

In my PR I added new option `showAllErrors` to display error messages beyond the first on each attribute. Also, I modified the code of `Html::errorSummary` to automatically skip any duplicate error messages in the list of errors.

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/bb7a36c5c682529f52bdea94fe940095f9463993
