### ISSUE TITLE
GridView filtering in form of tag-system

### ISSUE THREAD

**Issue by niklaswolf** [yiisoft/yii2#12207]
Hi there,
I'm planning to build a filter-system that works like a tag-system (I don't know exactly how it's called). To give an example I attached a screenshot of such a filter-system.
<img width="854" alt="bildschirmfoto 2016-08-19 um 12 34 55" src="https://cloud.githubusercontent.com/assets/16021919/17807380/71d25298-660a-11e6-9638-6e1ca8be8f1d.png">

My question now is, if there is a already existing way to build such a system with Yii's GridView or if I have to start building something on my own. I spent half a day searching the web, but I did not find something (the cause could of course be that I don't know the "right" name of such a system.)

To give a more concrete example, one requirement I have is to implement a language-filter for a list of persons, where you can optionally select multiple languages and the corresponding language-level for this language. A chosen language (with corresponding level) should then be listed as one "tag", which should be deletable.

**Comment by Alex-Code** [comment]
Please use the forums for questions, http://www.yiiframework.com/forum/index.php/forum/42-general-discussions/
Git is for issue tracking.
