### ISSUE TITLE
Suggestion: Add an append method to active queries

### ISSUE THREAD

**Issue by karpy47** [yiisoft/yii2#12204]
In version 2.0.9 an append() method was when setting up migrations (#11195). I'd like the same method for normal queries. 

In my case I need to add a special collation (utf8_swedish_ci) to get sorting right, but I still want to keep the columns db collation (utf8_unicode_ci) as it works in most cases/countries.

I got it working anyway doing this... 

    $sql = self::find()->orderBy(['name' => SORT_ASC])->createCommand()->rawSql;
    $sql = $sql.' COLLATE utf8_swedish_ci';
    $result = self::findBySql($sql)->all();

I'd rather see it work like this... (similar to how it works for migrations)

    $result = self::find()->orderBy(['name' => SORT_ASC])->append('COLLATE utf8_swedish_ci')->all();

Guess it could be handy for other cases as well.

**Comment by SilverFire** [comment]
Looks useful, but I don't have sure thoughts on this. @yiisoft/core-developers

**Comment by cebe** [comment]
I could not find information in the MySQL docs, is the COLLATE part of the ORDER BY statement or an addition to the whole query? i.e. which is the correct syntax if I for example apply a limit:

```sql
SELECT `name` FROM `table` ORDER BY `name` LIMIT 1 COLLATE utf8_general_ci;
```

or 

```sql
SELECT `name` FROM `table` ORDER BY `name` COLLATE utf8_general_ci LIMIT 1;
```

?

**Comment by cebe** [comment]
Seems the collate specification is part of the order by, so the addition does not make sense, you should write the code like this then;

```php
$records = self::find()->orderBy('name ASC COLLATE utf8_general_ci')->all();
```

**Comment by karpy47** [comment]
I already tried adding the collation to the ORDER BY clause like cebe suggested, but it fails with a DB exception...

    "name": "Database Exception",
    "message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'order clause'\nThe SQL being executed was: SELECT `id`, `name` FROM `region` ORDER BY `0`",
     "code": 42,
     "type": "yii\\db\\Exception",
     "file": "C:\\dev\\www\\vbs\\vendor\\yiisoft\\yii2\\db\\Schema.php",
     "line": 633,

However I agree that it would be the best solution.

**Comment by klimov-paul** [comment]
You should use `\yii\db\Expression`:

```php
$records = self::find()->orderBy(new \yii\db\Expression('name ASC COLLATE utf8_general_ci'))->all();
```

**Comment by karpy47** [comment]
ok, got it.

**Comment by aleksbelic** [comment]
I've just used @klimov-paul solution for case-insensitive sorting of active records in SQLite - works great!
In case someone needs it:

`Person::find()->orderBy(new \yii\db\Expression('name COLLATE NOCASE ASC'))->all();`
