### ISSUE TITLE
Pagination deosn't work when i use findBySql

### ISSUE THREAD

**Issue by pLe0mAx** [yiisoft/yii2#12205]
Hello i have dataprovider, where i use findBySql. The reason to use findBySql is that i have dynamically "left joins" in my query.

This is my query:

> $prodQuery = Product::findBySql('
              SELECT `product`.* 
              FROM `product` 
              LEFT JOIN `productLang` ON `product`.`id` = `productLang`.`product_id` 
              LEFT JOIN `product_cat` ON `product`.`id` = `product_cat`.`product_id` 
              LEFT JOIN `page` ON `product_cat`.`page_id` = `page`.`id` 
              LEFT JOIN `page` `parent` ON `page`.`id_in` = `parent`.`id`'
              .$joinString.
              ' WHERE ( '
                    .$whereString.
                    ' AND (`language`=\''.$lang->url.'\')) GROUP BY `product`.`id` '); 

In $joinString i have all joins to one table and in $whereString i have other conditions.

Here is my dataprovider

> $dataProvider = new ActiveDataProvider([
                'query' => $prodQuery,
                'pagination' => [
                    'totalCount' => count($prodQuery->all()),
                    'pageSize' => $pageSize,
                    'route' => Yii::$app->getRequest()->getQueryParam('first_step'),
                ],
                'sort' => [
                    'defaultOrder' => $orderArr,
                ],
            ]);

And i my view i use Listview. The problem is that pagination and sotring doesn't work. In my test site i have 4 products, when i set pageSize = 1, pagination has 4 pages, but in every page i have all 4 products.

Where is my error? Or how can i rewrite it, to have dynamically joins, because at the beginning i tried with Products::find()->joinWith()... but then i cannot have dynamically joins.

Thanks in advance.

**Comment by cebe** [comment]
you should either use SqlDataProvider instead or create the joins dynamically by calling join() method on the query.
