### ISSUE TITLE
rbac permission hierarchy seems a bit odd

### ISSUE THREAD

**Issue by alez007** [yiisoft/yii2#12206]
Hi gents, 

In RBAC documentation 'updateOwnPost' permission is the parent of 'updatePost' permission. 
> $auth->addChild($updateOwnPost, $updatePost);

In my opinion this is a bit illogical, mainly because 'updatePost' sounds more like a general permission and 'updateOwnPost' is a more concise one, a branch of 'updatePost' if you will. 

Now, let's imagine we add 'updateOwnPost' as a child of 'updatePost':
> $auth->addChild($updatePost, $updateOwnPost);

and keep the same roles as owners of those permissions, 'admin' owns 'updatePost', 'user' owns 'updateOwnPost'. 

One would expect that when 'admin' does
> Yii::$app->user->can('updateOwnPost')

this should be a success because 'updateOwnPost' is a child of 'updatePost', but in fact, the 'owner' rule of 'updateOwnPost' comes into play and, of course, admin is not owner, therefore this actually fails.

Any thoughts ?

**Comment by samdark** [comment]
Documentation is correct. Draw hierarchy on paper and try going from permission to role. If you can, access is allowed. If you can't it's not. On the way the simpler the checks the better.
