### ISSUE TITLE
Problem with lazy loading (relations) YII2

### ISSUE THREAD

**Issue by dmitriiPopov** [yiisoft/yii2#12211]
I have a query, for example: `Library::find()->where(['slug' => $slug])->joinWith('books')->one();`
I'm waiting for 1 request to mysql database and filling relation 'books', BUT I have 2 requests:
1st - `SELECT * FROM tbl_library WHERE 'slug'='library-test')`
2nd - `SELECT * FROM tbl_books WHERE 'library_id'=123`

Why yii2 can't execute only 1 request and with PHP resources prepare `Library` with needed relation? Is any extensions available?

**Comment by klimov-paul** [comment]
Duplicates #6446
