### ISSUE TITLE
UnlinkAll for conditionally relation

### ISSUE THREAD

**Issue by svit-ws** [yiisoft/yii2#12213]
### What steps will reproduce the problem?

I have relation in Trait:

``` php
    public function getPhones()
    {
        /** @var $this \yii\db\ActiveRecord */
        return $this->hasMany(Phone::className(), ['sub_id' => 'id'])
            ->andOnCondition(['sub_type' => static::tableName()]);
    }
```

And in afterSave:

``` php
        if (!$insert) {
            $this->unlinkAll('phones', true);
        }
```
### What is the expected result?

to delete only `['sub_type' => static::tableName()]` links
### What do you get instead?

deletes all links w/o ON condition
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.6.23 |
| Operating system | CentOS |

**Comment by SilverFire** [comment]
Confirmed

**Comment by SilverFire** [comment]
Only `where` condition is checked in https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1436

**Comment by Razzwan** [comment]
Oh no. I'm use it too. That is why i have trubles.

**Comment by SilverFire** [comment]
Thank you for the report. Fixed
