### ISSUE TITLE
Left join a compute attribute and 'Group By' query work with ActiveDataProvider

### ISSUE THREAD

**Issue by shining228** [yiisoft/yii2#12223]
### What steps will reproduce the problem?
`
//table name = user
class User extends ActiveRecord {
    public $totalAmount;
    public function getOrders() {
        return $this->hasMany(OrderInfo::className(), ['user_id' => 'user_id']);
    }
}

//table name = order_info
class OrderInfo extends ActiveRecord {

}

class UserSearch extends User {
   public $searchAmount;

   public function search($params) {
      $query = User::find();
       $query->select([
               'user.*',
               'SUM(order_info.goods_amount) AS totalAmount',
        ])->joinWith('orders')->groupBy('user.user_id');

        /******** other query and data provider code ********/

        $query->andFilterWhere(['>', 'totalAmount', $this->searchAmount]);
        return $dataProvider;
    }
}
`

### What is the expected result?
In GridView, totalAmount can be filter and show.
### What do you get instead?
A Database Exception, like this:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'totalAmount' in 'where clause'
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `user`.*, SUM(order_info.goods_amount) AS totalAmount FROM `user` LEFT JOIN `order_info` ON `user`.`user_id` = `order_info`.`user_id` WHERE (`totalAmount` > '100') GROUP BY `user`.`user_id`) `c`

If I use 'GROUP BY' in this query, ActiveDataProvider::prepareTotalCount will generate a sub query to count user, should I subclass ActiveDataProvider and handle about this? If I don't use 'GROUP BY', only the few users(totalAmount > 0) shows in GridView.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.15
| Operating system |

**Comment by klimov-paul** [comment]
You should use `HAVING`

**Comment by shining228** [comment]
Thanks, this is perfect!
