### ISSUE TITLE
SqlDataProvider with SQL Server DBMS (sqlsrv 2008)

### ISSUE THREAD

**Issue by hoaaah** [yiisoft/yii2#12224]
### What steps will reproduce the problem?
I Tried to create Gridview with SQLDataProvider, but it give an error.
This worked fine with mySQL Database but it give an error with sql server.
### What is the expected result?
This is the code

```php
$totalCount = Yii::$app->db->createCommand('
            SELECT COUNT(a.Tahun) AS jumlah FROM
                    (SELECT * FROM Ta_data WHERE year = :year) a
                    INNER JOIN
                    (
                    SELECT DISTINCT Kd_A, Kd_B  FROM Ta_data WHERE year = :year
                    ) b ON a.Kd_A = b.Kd_A AND a.Kd_B = b.Kd_B
                    GROUP BY a.Tahun     
            ')
                    ->bindValue(':year', $year)
                    ->queryScalar();
        var_dump($totalCount);
```

$totalCount in above give "array to string convertion error".
And in DataProvider

```php
        $dataProvider = new SqlDataProvider([
            'sql' => '
            SELECT a.* FROM
                    (SELECT * FROM Ta_data WHERE year = :year) a
                    INNER JOIN
                    (
                    SELECT DISTINCT Kd_A, Kd_B  FROM Ta_data WHERE year = :year
                    ) b ON a.Kd_A = b.Kd_A AND a.Kd_B = b.Kd_B               

                        ',
            'params' => [
                    ':year' => $year,
            ],
            'totalCount' => 1234,
            'sort' =>false, // to remove the table header sorting
            'pagination' => [
                'pageSize' => 50,
            ],
        ]);
```

variabel above give an "undefined offset error".

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  5.5.12
| Operating system | Windows 10

**Comment by cebe** [comment]
please provide the stack trace for both errors.

**Comment by hoaaah** [comment]
Already got solution. I can't reuse :year parameters twice, another year parameter in query must use another name (i.e year1). Based on http://www.php.net/manual/en/pdo.prepare.php

> You must include a unique parameter marker for each value you wish to pass in to the statement when you call PDOStatement::execute(). You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on.

This is PDO issue, not Yii2 issue. Thanks
