### ISSUE TITLE
Unique Validator doesn't display custom message when used with Combination.

### ISSUE THREAD

**Issue by InsaneSkull** [yiisoft/yii2#12248]
When unique validation used with more than one attribute it's not displaying correct validation message.

`[[employee', 'product'], 'unique', 'targetAttribute' => ['employee', 'product'], 'message' => 'Product already assigned to this employee.'],`
### What I am expecting :
`Product already assigned to this employee.`

### What I get :
`The combination "58"-"2" of Employee and Product has already been taken.`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9

**Comment by rob006** [comment]
duplicates #12152

**Comment by InsaneSkull** [comment]
Thanks, don't know about it.
