### ISSUE TITLE
FR, CHG: Move UploadedFile into Request

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#12244]
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes/no
| Tests pass?   | 
| Fixed issues  | #7908

Instead of using
```php
$model->image = UploadedFile::getInstance($model,'image');
```
prefer using
```php
$model->load($request->files());
```
much better if also added to `$request->post()`. So, when we do `$model->load($request->post());` its also load uploaded file.

**Comment by samdark** [comment]
That could potentially introduce security issues i.e. uploading of files may happen if validation rules aren't used carefully.

**Comment by samdark** [comment]
Also it couples files and request more.

**Comment by SilverFire** [comment]
Agreed with @samdark
