### ISSUE TITLE
Setting unknown property: yii\widgets\ActiveForm::layout

### ISSUE THREAD

**Issue by mainpart** [yiisoft/yii2#12245]
Hello. I've tried to specify options for ActiveForm::begin
`$form` = ActiveForm::begin(['layout' => 'horizontal']);`

Expected attribute to be specified as something in FORM tag but got 

Setting unknown property: yii\widgets\ActiveForm::layout
in /vendor/yiisoft/yii2/base/Component.php

| Yii version      |  2.0.6 / @dev
| PHP version      |  5.6.x
| Operating system | Ubuntu

**Comment by haiflive** [comment]
see defination.
`use yii\widgets\ActiveForm;`
change to
`use yii\bootstrap\ActiveForm;`
