### ISSUE TITLE
dateTime()->defaultValue("NOW") error

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2#12256]
![5](https://cloud.githubusercontent.com/assets/16696651/17868134/c95f00e2-68ad-11e6-89c3-9cc7789df9df.png)

| Yii version   2.0.9   | 
| PHP version    7.0.7 mysql  Ver 14.14 Distrib 5.7.12, for Win32  | 
| Operating system Win 10|

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchemaBuilder.php#L254
