### ISSUE TITLE
Add DetailView Attribute support for name with spaces

### ISSUE THREAD

**Issue by modomodo** [yiisoft/yii2#12262]
### What steps will reproduce the problem?

Unlike GridView, I was surprised to find that DetailView attributes doesn't support names with spaces. 
I had the following DetailView setup:

``` php
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'timestamp',
            'Sample No_',
            'Sample Date',
            'Sample ID',
            'Name No_',
            'Employee Name'
        ],
        'options' => [
            'class' => ['table striped hovered border bordered']
        ]
    ]) ?>
```
### What is the expected result?

A DetailView to be rendered similar to the one below:
![image](https://cloud.githubusercontent.com/assets/5679726/17884445/ff8f820e-6920-11e6-9e74-1acf17eb53ff.png)

> The above image is simply an example. The attribute names used didn't contain spaces
### What do you get instead?

![image](https://cloud.githubusercontent.com/assets/5679726/17884404/c7853fca-6920-11e6-9523-ec351fd5a00d.png)
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.7 |
| PHP version | 5.6.23 |
| Operating system | Windows 10 |
## Proposed Solution

Changing the regex used to validate the attributes to the following:

``` php
/^([\w\.\s]+)(:(\w*))?(:(.*))?$/
```

Worked and the DetailView was rendered without any problems. As shown below
![image](https://cloud.githubusercontent.com/assets/5679726/17884578/c87b8226-6921-11e6-9b31-ff03d609f75e.png)

**Comment by modomodo** [comment]
Here's a link to play around with the regex: https://regex101.com/r/xK6iG3/2

**Comment by Razzwan** [comment]
I do not understand, why attributes with spaces?

**Comment by modomodo** [comment]
This is due to the actual fields in the table containing spaces. And this cannot be changed due to the same database being used for other backend systems that use spaces.

**Comment by modomodo** [comment]
After a bit of reading... I realised adding `\s` allows for some harmful characters such as '\n'.

A better version for the regex would be this:
```php
/^([\w\. ]+)(:(\w*))?(:(.*))?$/
```
Here's an updated link to play with the regex: https://regex101.com/r/xK6iG3/3

**Comment by samdark** [comment]
Seems OK to me. @modomodo do you want to submit a pull request to speed things up?

**Comment by modomodo** [comment]
@samdark Definitely 😄. Never contributed to an open source project but stoked to learn how to

**Comment by samdark** [comment]
Seems to be related to #4408

**Comment by WadeShuler** [comment]
'Employee Name' is a label, not a valid attribute name.

Spaces in database columns, violates best practices and is frowned upon. I actually haven't tried, is it possible to create a table column with spaces in say MySQL?

I don't think Yii should change anything, in regards to accepting spaces in the attributes. You should use valid column names and avoid the issue all-together. If this isn't DB info, and say from a CSV, then reformat it or sanitize it, prior to loading it in the DetailView.

**Comment by modomodo** [comment]
@WadeShuler It is possible, and for databases, that have other legacy enterprise back-ends that can't be changed, this is often the case. See the following resource on column names with spaces: 
* [The Language of SQL, Second Edition > 2. Basic Data Retrieval > Column Names with Embedded Spaces](https://www.evernote.com/l/AI5bXRUk-OhJeZJXIagnHFglplzsEH0fxwY/)
* [Create a table with a space in the name in mySQL - StackOverflow](https://stackoverflow.com/questions/18184614/create-a-table-with-a-space-in-the-name-in-mysql)

It is DB info directly pulled from a model and supplied to the `DetailView` as below:
```php
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'timestamp',
            'Sample No_',
            'Sample Date',
            'Sample ID',
            'Name No_',
            'Employee Name'
        ],
        'options' => [
            'class' => ['table striped hovered border bordered']
        ]
    ]) ?>
```
Its also valid use case and `GridView` currently supports it, so its not a matter of a single user requesting a feature but one that already exists in other parts of the framework.

**Comment by samdark** [comment]
Such column names are valid in SQL. I'd like to see how many adjustments it would take to support it and if it worth supporting before making a decision.

**Comment by WadeShuler** [comment]
They are valid, they are not recommended and are frowned upon. Point being, YOU SHOULD NOT BE USING SPACES IN COLUMN NAMES... EVER! Fix your backend db, or create a function to loop through your results and insert underscores to the column names before tossing it to DetailView.

We should not have the framework bogged down with (even more) regex for bad practices like this!

**Comment by samdark** [comment]
There are cases when you're working on integration project which already has database you can't touch. Often happens in big enterprises. Happened to me multiple times while working for Siemens.

**Comment by dynasource** [comment]
related to #4408, discussion is moved there
