### ISSUE TITLE
Breadcrumbs options class

### ISSUE THREAD

**Issue by hamad251** [yiisoft/yii2#12264]
### What steps will reproduce the problem?

      <?php echo Breadcrumbs::widget([
            'homeLink' => [
                'label' => Yii::t('yii', 'Home'),
                'url' => Yii::$app->homeUrl,
            ],
            'options'=>[
                ['class' => 'uk-breadcrumb']
            ],
            'activeItemTemplate' => "<li class=\"uk-active\">{link}</li>\n",
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

### What is the expected result?
    <ul class="uk-breadcrumb"><li><a href="http://localhost:8888/amala">Home</a></li>
    <li class="uk-active">test</li>
    </ul>

### What do you get instead?
    <ul 0-class="uk-breadcrumb"><li><a href="http://localhost:8888/amala">Home</a></li>
    <li class="uk-active">test</li>
    </ul>

### Additional info

Way I get `0-class="uk-breadcrumb"` instead of  `class="uk-breadcrumb"`

| Q                | A
| ---------------- | ---
| Yii version      |  2
| PHP version      |  5.5
| Operating system |  OSX 10

**Comment by SilverFire** [comment]
You have redundant nested level

Replace

```php
        'options'=>[
            ['class' => 'uk-breadcrumb']
        ],
```

with
```php
        'options'=>[
            'class' => 'uk-breadcrumb'
        ],
```
