### ISSUE TITLE
yii Migration alterColumn error

### ISSUE THREAD

**Issue by binkabir** [yiisoft/yii2#12268]
### What steps will reproduce the problem?
Use the migration `$this->alterColumn` function to change a column in your db. 
### What do you get instead?
'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near

### Additional info
I drilled down to see what was going on in the QueryBuilder.php class and I noticed that the `$this->db->quoteColumnName($column)` was duplicated. in line 472

    ` return 'ALTER TABLE ' . $this->db->quoteTableName($table) . ' CHANGE '
            . $this->db->quoteColumnName($column) . ' '
            . $this->db->quoteColumnName($column) . ' '
            . $this->getColumnType($type);`

| Q                | A
| ---------------- | ---
| Yii version     | 2
| PHP version      | 5.6 
| Operating system  |  ubuntu

**Comment by SilverFire** [comment]
> Use the migration $this->alterColumn function to change a column in your db.

Could you show you code?

**Comment by binkabir** [comment]
Hi @SilverFire 
`  $this->alterColumn('mda', 'isSubUnitEnabled', "is_sub_unit_enabled ENUM('True','False') CHARACTER SET latin1 COLLATE latin1_swedish_ci  NULL DEFAULT NULL");
`

**Comment by cebe** [comment]
alterColumn can not rename a column, the second argument is only the column type without the name.

**Comment by binkabir** [comment]
Hi @SilverFire 
`  $this->alterColumn('mda', 'isSubUnitEnabled', "is_sub_unit_enabled ENUM('True','False') CHARACTER SET latin1 COLLATE latin1_swedish_ci  NULL DEFAULT NULL");
`

**Comment by binkabir** [comment]
@cebe, well I simply commented out the second duplicate `$this->db->quoteColumnName($column) .`
and it worked out all well :)
