### ISSUE TITLE
Yii2 的开发速度太慢了吧？

### ISSUE THREAD

**Issue by luxixing** [yiisoft/yii2#12276]
@qiangxue  强哥，我一直在关注yii2的开发和路线图，发现yii2的开发速度有点慢啊，laravel 5.3已经发布，PHP的版本最低要求是 5.6了，我们这边还是没啥动静
bower 官方已经停止更新，我们还在支持

请问这块我们有什么改进计划吗？

我的英文不好，就直接用中文了，表达意思会精确点

**Comment by cebe** [comment]
Google translate:

> @qiangxue strong brother, I have been concerned yii2 development and roadmap found yii2 development speed a little Mana, laravel 5.3 has been released, the minimum required PHP version is 5.6, and our side still nothing happened
bower officials have stopped updating, we also support
> 
> Will this what we have to improve the program?
> 
> My English is not good, the direct use of Chinese, the meaning of the expression will be exact point

**Comment by cebe** [comment]
Yii 2.1 is in development already and will require at least PHP 5.5.

Did not understand what you want to say with the other points...

**Comment by lichunqiang** [comment]
Generally speak, our step is too slow. :sob:

**Comment by cebe** [comment]
Maintaining Yii is a lot of work and we all do it in our free time. We are currently also working on a [new website](https://github.com/yiisoft-contrib/yiiframework.com) improving documentation and so on. This all takes a lot of time and effort.

If you want to speed things up you can help with discussion and implementing things.

I'm closing this now as there is nothing to fix or change at this point.
