### ISSUE TITLE
Collections instead of array of Active Records.

### ISSUE THREAD

**Issue by Razzwan** [yiisoft/yii2#12291]
In https://github.com/yiisoft/yii2/issues/10806 I propoused to transform the array of active records (in relation hasMany) to collection object. I can do it. But no subscribed. Whether the issue is interesting team?

**Comment by samdark** [comment]
It was discussed multiple times. While it sounds good there are doubts and cons:

1. At the time we were not able to come up with a good use case where collections are significantly better than arrays.
2. Extra overhead.
3. It was likely to break backward compatibility. Back then it was significant enough obstacle to drop proposal. Now, when 2.1 is in development, it's not an issue.

**Comment by samdark** [comment]
Let's keep discussion in original issue though.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2-collection
