### ISSUE TITLE
CSRF validator issue

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#12307]
### What steps will reproduce the problem?
Send POST to any url.
### What is the expected result?
Whether or not we have csrf token.
### What do you get instead?
Error
![img](http://image.prntscr.com/image/dab4eb320ff74b4fb054f9e0919a5b8a.png)

### Additional info
When disable "enableCsrfValidation" it works good.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | Windows 10.1

**Comment by SilverFire** [comment]
How to reproduce this error using clear basic Yii2 application template?

**Comment by tunecino** [comment]
@RSalo the cookie is missing, there should be a `httpOnly` flagged cookie holding a second token that server will compare with that csrf token you are sending. if not matching (they are different by matching I mean when [decrypted back by yii](https://github.com/yiisoft/yii2/blob/3d40628bd92a62cde7e886bbe6d1b8a19edc3a2f/framework/web/Request.php#L1419)) a 400 status code (bad request) should be expected.
In Yii when you send to client that csrf token using `generateCsrfToken()` like:

```php
return [
    'user' => [ 
        'name' => Yii::$app->user->identity->username,
        'access_token' => $access_token,
        ...
        '_csrf' => Yii::$app->request->generateCsrfToken()
    ]
];
```
the related cookie as shown [here](https://github.com/yiisoft/yii2/blob/3d40628bd92a62cde7e886bbe6d1b8a19edc3a2f/framework/web/Request.php#L1314) will be added to the request. you just need to send it back along with that `_csrf` token value in the body response.

**Comment by RSalo** [comment]
@SilverFire just do POST request in format "application/vnd.google-earth.kml+xml" to any route...
@tunecino "POSTMAN doesn't do that by default as a browser does" - it doing it. because if we send request as GET we not have error...
![alt](http://image.prntscr.com/image/729a95e58d0a414db2724322bc213010.png)

**Comment by tunecino** [comment]
> POSTMAN doesn't do that by default as a browser does

by that I meant automatically sending back the cookie received by server with all future requests to the same domain. I'm not sure if there is an advanced config or a way to do it manually in Postman.

> it doing it. because if we send request as GET we not have error...

that is also expected as csrf validation is for all verbs except 'GET', 'HEAD' and 'OPTIONS': https://github.com/yiisoft/yii2/blob/3d40628bd92a62cde7e886bbe6d1b8a19edc3a2f/framework/web/Request.php#L1383

http://www.yiiframework.com/doc-2.0/guide-security-best-practices.html#avoiding-csrf

**Comment by samdark** [comment]
Well, either disable CSRF validation or implement cookies in POSTMAN. Framework behaves as expected.
