### ISSUE TITLE
Max and Min Error when validate whith compare in values

### ISSUE THREAD

**Issue by solucionti** [yiisoft/yii2#12302]
Hi, I'm doing validations using rules. This is the code
```
     $rules   = parent::rules();
        $rules[] = ['name', 'required'];
        $rules[] = [
          ['max_week'],
          'compare',
          'compareAttribute' => 'min_week',
          'operator'         => '>=',


        ];

        return $rules;
```
When I use the minimum value between 0 and 99 works properly, but when I use 99-100 get the following error message.

![good_app](https://cloud.githubusercontent.com/assets/9874555/17944237/454ac4a8-6a15-11e6-98ce-09f475f0db39.png)

![error_app](https://cloud.githubusercontent.com/assets/9874555/17944214/22314ce4-6a15-11e6-9e07-aa87340bfa1b.png)

Thanks

**Comment by cebe** [comment]
You have to set 'type' => 'number' otherwise the comparison is made as strings and not numbers.

http://www.yiiframework.com/doc-2.0/yii-validators-comparevalidator.html#$type-detail
