### ISSUE TITLE
Proposal: Enhance cache component to cache values by callback

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#12312]
When using the cache component I often find myself writing the same repetitive pattern like this:

``` php
<?php
class Article
{
    public function getAvailability()
    {
        $cache = Yii::$app->cache;
        $key = 'article:availabilty:'.$this->number;
        $cachedValue = $cache->get($key);
        if ($cachedValue===false) {
            // ... some expensive operation here e.g. a remote API call ...
            $cache->set($key, $value);
            return $value;
        } else {
            return $cachedValue;
        }
    }
}
```

To make this easier, I propose to add a new very simple method to `yii\caching\Cache`:

``` php
    /**
     * Gets the value stored under $key from cache. If there is no value stored for
     * that key, the value is evaluated from the callback and stored to the cache.
     *
     * @param string $key the cache key
     * @param Callable $callback the callback that evaluates the cache value
     * @param int $duration the caching duration. Default is 3600.
     * @param yii\caching\Dependency|null $dependency the cache dependency
     * or `null` for none.
     * @return mixed the cached value
     */
    public function cached($key, $callback, $duration = 3600, $dependency = null)
    {
        $cachedValue = $this->get($key);
        if ($cachedValue===false) {
            Yii::trace("Evaluating and storing value for $key", __METHOD__);
            $value = call_user_func($callback);
            $this->set($key, $value, $duration, $dependency);
            return $value;
        } else {
            Yii::trace("Serving $key from cache", __METHOD__);
            return $cachedValue;
        }
    }
```

With this method, the above getter can be simplified to:

``` php
    public function getAvailability()
    {
        $key = 'article:availabilty:'.$this->number;
        return Yii::$app->cache->cached($key, function () {
            // ... some expensive operation here e.g. a remote API call ...
            return $value;
        });
    }
```

As an alternative, we could even enhance the implementation of `Cache::get()`. I'm missing a `$default` argument there anyway. This is how it could look:

``` php
/**
 * @param string $key the cache key
 * @param mixed|Callable $default the default value to return if $key does not exist.
 * If this is a Callable, its return value is stored to the cache under the given key.
 * The default is `false`.
 * @param int $duration the caching duration if a callback is used. Default is 3600.
 * @param yii\caching\Dependency|null $dependency the cache dependency if a callback
 * is used or `null` for none.
 * @return mixed the cached or evaluated value
 */
public function get($key, $default = false, $duration = 3600, $dependency = null)
```

**Comment by samdark** [comment]
- https://github.com/yiisoft/yii2/pull/11959
- https://github.com/yiisoft/yii2/issues/11172

It popped up again. @yiisoft/core-developers seems to be in everyone's wish lists :) How about implementing it?

**Comment by mikehaertl** [comment]
Ha, I knew I'm not the only one. :)

Yes, I can give it a try.

**Comment by SilverFire** [comment]
+ #11173

Voting for. How to name this method? I don't like `cached` because it is not self-explanatory. In #11173 the `retrieve` method name was suggested. It is better, but is not perfect as well. How about `callback` or `closure`?

```php
Yii::$app->cache->closure('activeUsers', function () {
    return $this->longOperation();
}, 1000);
```

**Comment by mikehaertl** [comment]
@SilverFire Have you also seen my alternative suggestion? How about extending `get()`? This way we could combine 2 features in one method:

 * Default values if the key does not exist
 * Callbacks to init the cached value

We should also note somewhere, that `false` values can not be cached.

**Comment by SilverFire** [comment]
No, I don't think this is a good reason to break a BC of the `get()` method

**Comment by mikehaertl** [comment]
@SilverFire The change does not break BC. If you don't pass a `$default` it would behave just as before.

**Comment by rob006** [comment]
@mikehaertl Every change of method signature breaks BC.

**Comment by samdark** [comment]
In this case *technically* BC isn't broken.

**Comment by SilverFire** [comment]
You've suggested `$default` as a required parameter, didn't you?

Even considering `$default` as an optional parameter, I don't want to change `get()` signature because it must stay as simple as possible.

**Comment by mikehaertl** [comment]
Yes, sorry, `$default` would be optional. Of course, this should go to Yii 2.1 then. I can't see why this change would be a big problem. Unless somene extended from `Cache` and overrides `get()` with his own custom parameters, everything would work as before. This could clearly be described in the upgrade guide for 2.1.

**Comment by SilverFire** [comment]
@samdark I think we can do it right now with a separate method. No need to delay this feature to 2.1

**Comment by mikehaertl** [comment]
I think there's no right or wrong in this matter. One can argue against another method because it would add yet another method to the API which is simply not neccessary. `get()` and this other method would basically do exactly the same thing and a `$default` is missing from `get()` anyway. So why not fix this and keep the API minimal?

**Comment by SilverFire** [comment]
> get() and this other method would basically do exactly the same thing and a $default is missing from get() anyway

First of all, it will be a BC breaking of `get()` method's signature.
Second, it makes `get()` method not as simple and straightforward as it looks and as it must be indeed.

**Comment by kidol** [comment]
```php
Yii::$app->cache->get(function($key = "my key", $duration = 3600) {
   ...
   return $data;
});
```

Then read params via reflection. :trollface:

**Comment by samdark** [comment]
:) Of course, https://github.com/yiisoft/yii2/issues/12312#issuecomment-258647518 isn't good since reflection is performance killer.

**Comment by kidol** [comment]
Actually it looks pretty ok, like <5ms for PHP 5 @ 1.000 iterations https://3v4l.org/k3Gja

**Comment by samdark** [comment]
When using PHP 7.1? It's 10ms when using 5.6 and 7.0 and 50ms when using HHVM.

**Comment by kidol** [comment]
This is what I get locally, 5.6 and 7.0
>0.0050010681152344
>0.0019998550415039

Saw similar numbers on 3v4l. But yes, HHVM seems  to be much slower.
>Output for hhvm-3.13.2
>0.012503147125244

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/pull/13186

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/aed3a222a20edd14859053a45b6b62889ca41a59
