### ISSUE TITLE
Flash messages work locally but not online on live server

### ISSUE THREAD

**Issue by atrandafir** [yiisoft/yii2#12332]
### What steps will reproduce the problem?

Simply trying to use flash messages in a contact form.

It works locally on Windows7 with XAMPP but does not work on the live dedicated server.

Controller code:  

```
public function actionContact()
{
	$model = new ContactForm();
	if ($model->load(Yii::$app->request->post()) && $model->validate()) {
		if ($model->sendEmail()) {
			Yii::$app->session->setFlash('success', Yii::t('app', 'Gracias por contactar. Te responderemos a la mayor brevedad posible.'));
		} else {
			Yii::$app->session->setFlash('error', Yii::t('app', 'Hubo un error al enviar tu mensaje.'));
		}
		return $this->refresh();
	} else {
		return $this->render('contact', [
			'model' => $model,
		]);
	}
}
```

View code:  

```
<?php if(Yii::$app->session->hasFlash('error')): ?>
	<div class="error alert alert-danger alert-dismissible" role="alert">
	  <button id="close-error" type="button" class="error close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  <?= Yii::$app->session->getFlash('error') ?>
	</div>
<?php endif; ?>

<?php if(Yii::$app->session->hasFlash('success')): ?>
	<div class="success alert alert-success alert-dismissible" role="alert">
	  <button id="close-success" type="button" class="close success" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  <?= Yii::$app->session->getFlash('success') ?>
	</div>
<?php endif; ?>
```

### What is the expected result?

I expect to see the flash message but I do not see it.

### What do you get instead?

Nothing, the flash never appears.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | v2.0.9
| PHP version      | PHP 5.6.24
| Operating system | CentOS Linux release 7.0.1406 x86_64

### It does work if switching to databse session

If I configure the session component like this it does work:  

```
'session' => [
  'class' => 'yii\web\DbSession',
  'sessionTable' => 'session', // session table name. Defaults to 'session'.
],
```
So what do you suggest to try? Could this be a bug? Or maybe something wrong with the server setup?

**Comment by samdark** [comment]
Try regular session handler.

**Comment by cebe** [comment]
If it works locally, it is very likely a problem in your setup and not a problem with yii.

**Comment by atrandafir** [comment]
Not sure if I understand what you mean, but I've tried outside the framework with this script.  

```
<?php

error_reporting(-1);
ini_set('display_errors', 'On');

// Start the session
session_start();
?>
<!DOCTYPE html>
<html>
<body>

<?php
if (isset($_GET['set'])) {
  // Set session variables
  $_SESSION["favcolor"] = "green";
  $_SESSION["favanimal"] = "cat";
  echo "Session variables are set.";
}

?>
  
<?php
if (isset($_GET['get'])) {
  // Echo session variables that were set on previous page
  echo "Favorite color is " . $_SESSION["favcolor"] . ".<br>";
  echo "Favorite animal is " . $_SESSION["favanimal"] . ".";
}
?>

</body>
</html>
```

### Results

```
Warning: session_start(): open(/var/lib/php/session/sess_2ucajoeqpdnv2vqdkglqcm4vb2, O_RDWR) failed: Permission denied (13) in /var/www/vhosts/.../.../frontend/web/test-session.php on line 7
Warning: Unknown: open(/var/lib/php/session/sess_2ucajoeqpdnv2vqdkglqcm4vb2, O_RDWR) failed: Permission denied (13) in Unknown on line 0
Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/session) in Unknown on line 0
```

So I guess indeed must be something wrong with my setup. 

All other applications were running php 5.4 on this server, then last week I've upgraded to php 5.6 from Plesk Panel and setup this domain to run 5.6 instead of 5.4.

But what I find strange is how come Yii doesn't detect this problem and show error or log it? Is it because it's just a php warning and in production mode this is not logged?

**Comment by cebe** [comment]
> Warning: Unknown: open(/var/lib/php/session/sess_2ucajoeqpdnv2vqdkglqcm4vb2, O_RDWR) failed: Permission denied (13) in Unknown on line 0

PHP does not have permission to write sessions on your server.

Yii [does log an error if session generation fails](https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L139), if you have setup logging correctly you should see this being logged in yiis /runtime folder.

**Comment by atrandafir** [comment]
I've managed to fix it running this: 

```
cd /var/lib/php
chmod 1733 session/
```
After reading some related articles:  
https://kb.plesk.com/en/127510
https://talk.plesk.com/threads/issues-with-var-lib-php-session-after-plesk-update.282891/

**Comment by atrandafir** [comment]
Okay I understand but just to get it clear. If I make a fresh installation of the advanced application and init it in production mode, I think it won't log this error.

What would be the correct way to debug the application that is currently running in production mode?

Editing the index.php file and setting `YII_DEBUG` to true?

**Comment by cebe** [comment]
This should cause the error message to be logged: https://github.com/yiisoft/yii2-app-advanced/blob/a85ffce09cd3a72bce106f59573d2656970d7c2e/frontend/config/main.php#L29-L34
