### ISSUE TITLE
Communication problem

### ISSUE THREAD

**Issue by PandaHugMonster** [yiisoft/yii2#12347]
Good day. I'm a big fan of yii-framework.
Few minutes ago one of Moderators after one response locked the thread. I haven't been rude, I haven't been arguing. I just wanted to say thank you and ask the reason why is the feature can't be added.

Is that a common practice to be rude with any of contributers here?

**Comment by SilverFire** [comment]
Hello. You are talking about [this conversation](https://github.com/yiisoft/yii2/issues/305#issuecomment-242735807), right?

Let me explain my decision. The topic was started more than 3 years ago (May 18, 2013) and @qiangxue posted his disagreement with the idea, and the topic has been forgotten for year and a half. Then Dec 12, 2014 a lonely post was added, then 1.5 more years of silence.
I've concluded that the problem does not affect major amount of Yii developers and the topic must be locked to prevent further discussions.

Sorry for a harsh move, I did not want to offend you or any other member of Yii community.

**Comment by samdark** [comment]
I've provided extra explanation in that topic.

**Comment by PandaHugMonster** [comment]
SilverFire - now thank you. No hard feelings. I feel better now. Thank you.

**Comment by SilverFire** [comment]
You're welcome ;)
