### ISSUE TITLE
Autocomplection not work in PHPStorm for BaseActiveRecord::findOne()

### ISSUE THREAD

**Issue by paulzi** [yiisoft/yii2#12349]
### What steps will reproduce the problem?
```php
$model = Example::findOne(1);
$model->attribute_in_db = 1; // attribute_in_db is marked as not found
```

### Possible solution
If I replace `@return static|null` to `@return static` in BaseActiveRecord::findOne() autocomplection works normally.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.*
| PHP version      | *
| PHPStorm | 10

**Comment by paulzi** [comment]
See [https://github.com/yiisoft/yii2-gii/pull/184]

**Comment by SilverFire** [comment]
Thank you
