### ISSUE TITLE
Bug: incorrect formatter output with explicit MIN_FRACTION_DIGITS

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#12345]
``` php
'numberFormatterOptions'=>[
                NumberFormatter::MIN_FRACTION_DIGITS => 0,
                NumberFormatter::MAX_FRACTION_DIGITS => 0,
 ]

\Yii::$app->formatter->asCurrency($model->price, 'EUR');

//output 129 517,00 €
```

**Comment by cebe** [comment]
Here is why this happens: http://php.net/manual/en/numberformatter.formatcurrency.php#114376

**Comment by exru** [comment]
@cebe this happens while 
main.php //global configuration
```php
'numberFormatterOptions'=>[
                NumberFormatter::MIN_FRACTION_DIGITS => 0,
                NumberFormatter::MAX_FRACTION_DIGITS => 0,
 ]
````

**Comment by cebe** [comment]
Fixed, thanks for reporting! Also congrats to the nice issue number :)

**Comment by ptz-nerf** [comment]
Have same problem in 2.0.12(intl is 1.1). asCurrency() ignores numberFormatterOptions.
Code after https://github.com/yiisoft/yii2/blob/2.0.12/framework/i18n/Formatter.php#L1373 breaks formatting. If I delete it or place before "// set attributes" comment or delete options in Formatter config (such as decimalSeparator, thousandSeparator) all works fine.

**Comment by cebe** [comment]
@ptz-nerf please open a new issue and provide the code that produces the problem.

**Comment by PendalF89** [comment]
Hi! I have a same problem in 2.0.16, ICU version is 60.2, PHP version is 7.2.15, OS Ubuntu 18,04.
`echo Yii::$app->formatter->asCurrency(2000, 'USD'); // "2 000,00 $", but except "2 000 $"`
