### ISSUE TITLE
yii.activeForm.js validateAttribute

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#12374]
How manual validate form input?

```php
<?

namespace app\components\widgets;

class ActiveForm extends \yii\widgets\ActiveForm {

	public $enableAjaxValidation = false;
	public $enableClientValidation = true;
}
```
```js
$('#w0').yiiActiveForm('submitForm') // work, show errors
$('#w0').yiiActiveForm('resetForm') // work, hide errors
$('#w0').yiiActiveForm('validateAttribute', 'dynamicmodel-text') // nope...

$('#w0').yiiActiveForm('validate') // work only after $('#w0').yiiActiveForm('data').submitting = true
```

**Comment by RSalo** [comment]
@SilverFire grandfather can. pensioner benefits... ;)

**Comment by DrDeath72** [comment]
2.0.9

**Comment by samdark** [comment]
So https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md#triggering-validation-for-individual-form-fields doesn't work for you?

**Comment by DrDeath72** [comment]
yep, nothing happens

**Comment by mztest** [comment]
$('#w0') , It may not your form widget already。 Make sure of there is only one widget inside of the  page. Or you can define your own id for this form.

**Comment by SilverFire** [comment]
![ezgif-91097417](https://cloud.githubusercontent.com/assets/4499203/19412828/c2bd847c-9326-11e6-8cc3-649e93b7a7c1.gif)

Failed to reproduce

**Comment by DrDeath72** [comment]
i understand what error... field add class has-error but i don't use it, only errors summary, it's stay empty...

**Comment by SilverFire** [comment]
Yeah, error-summary is server-side validation result, JS has nothing to do with it

**Comment by DrDeath72** [comment]
`$('#w0').yiiActiveForm('submitForm')` fill it...
