### ISSUE TITLE
Fatal error: Error when compiled in HHVM

### ISSUE THREAD

**Issue by thanhpv-h9** [yiisoft/yii2#12371]
### What steps will reproduce the problem?
Compile my yii2 project by command:
```
INDEX_TMP="/var/run/hhvm/fileindex"

find /var/www/html -name \*.php > $INDEX_TMP

hhvm --hphp -t hhbc -v AllVolatile=true --input-list $INDEX_TMP --output-dir /var/run/hhvm/
```
Yii2 throw an exception in class Session.php
```
private function setCookieParamsInternal()
    {
        $data = $this->getCookieParams();
        extract($data); // failed
        if (isset($lifetime, $path, $domain, $secure, $httponly)) {
            session_set_cookie_params($lifetime, $path, $domain, $secure, $httponly);
        } else {
            throw new InvalidParamException('Please make sure cookieParams contains these elements: lifetime, path, domain, secure and httponly.');
        }
    }
```
### What is the expected result?
Run yii2 application after compiled code by hhvm
### What do you get instead?
`extract()` functions can't run in hhvm compiled. Link to issue: [Fatal error: Could not create variable environment (repo mode only)](https://github.com/facebook/hhvm/issues/6840)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.8
| Operating system | Centos 7

**Comment by samdark** [comment]
Seems it's not going to be fixed in HHVM. Am I right?

**Comment by thanhpv-h9** [comment]
Yes. Should use other function for extract array to variables.

**Comment by samdark** [comment]
It's not the only place we're using `extract()`:

- https://github.com/yiisoft/yii2/blob/master/framework/base/View.php#L325
- https://github.com/yiisoft/yii2/blob/master/framework/requirements/YiiRequirementChecker.php#L307
- https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L236

**Comment by cebe** [comment]
how comes view rendering works in HHVM then?

**Comment by samdark** [comment]
@thanhpv-h9 is talking about compiling HHVM. So far we've checked VM-runtime version.

**Comment by klimov-paul** [comment]
> Should use other function for extract array to variables.

I am afraid this is not possible. I can not imagive the way to emulate `extract()` behavior.

There could be a fix for `setCookieParamsInternal()`, so it does not use `extract()` function.
But HHVM will still fail on any attempt to use `View::render()` anyway.

**Comment by klimov-paul** [comment]
> I can not imagive the way to emulate `extract()` behavior.

Although, I can:

```php
foreach ($array as $key => $value) {
    $$key = $value;
}
```

However, I am unsure if it work on HHVM either.

**Comment by samdark** [comment]
@thanhpv-h9 can you check if @klimov-paul solution works?

**Comment by SilverFire** [comment]
Works as expected: https://3v4l.org/fvemu

Replaced `$$key` with `${$key}` to make it a bit more readable

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/f7bd7c2b6b1b9941e3c50d99e4f07ff17d513cca

**Comment by rob006** [comment]
> Works as expected: https://3v4l.org/fvemu

It does not prove anything - `extract()` also works on 3v4l: https://3v4l.org/t1cZ1

**Comment by samdark** [comment]
@rob006 it works in runtime but fails compiling.

**Comment by samdark** [comment]
@SilverFire have you measured performance?

**Comment by klimov-paul** [comment]
I suppose the fix should be reverted.

**Comment by klimov-paul** [comment]
Actually, it is weird to think direct dynamic vars creation works, while standard `extract()` fails.
Either it is a bug of HHVM or they should fail both at least. Or they shoulb both work.

**Comment by klimov-paul** [comment]
See comment: https://github.com/facebook/hhvm/issues/6840#issuecomment-200058514

> This violates the assumptions made by repo-authoritative mode

It seems both ways will fail on 'repo-authoritative mode'. Thus I can not see the way we can support it.

**Comment by klimov-paul** [comment]
Commit f7bd7c2 should be reverted.

Note: that usage of `extract()` at `Session::setCookieParamsInternal()` is not necessary at all. We can use its source array just as well.

The only place we can not do anything with `extract()` is view rendering.

**Comment by SilverFire** [comment]
> it works in runtime but fails compiling.

I've verified that HHVM compiles project after my patch, but did not verified that it does not work before patching.

Verified on Ubunty 14.04 with 

```
# hhvm --version
HipHop VM 3.11.1 (rel)
Compiler: 3.11.1+dfsg-1ubuntu1
Repo schema: 2f678922fc70b326c82e56bedc2fc106c2faca61
```

Commit reverted eb02b36

**Comment by klimov-paul** [comment]
Good, however this is not over yet.
We should get rid of `extract()` usage at `Session::setCookieParamsInternal()` and use plain array there.

**Comment by SilverFire** [comment]
@thanhpv-h9 could you check your HHVM version?

**Comment by klimov-paul** [comment]
22a224d232f23502bc2bfa3afce38dd337513b5a
