### ISSUE TITLE
New validator RequiredIfNotEmpty

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#12370]
I have an idea about new validator that is make required one of another fields when one of this field is filled.
Example: one of variant of usefulness - date. We have 3 field "day", "month" and "year". If one of this field is not empty to do error for others fields.
Thanks for  understanding!

**Comment by tunecino** [comment]
I think we already have that:
http://www.yiiframework.com/doc-2.0/guide-input-validation.html#conditional-validation

**Comment by samdark** [comment]
As @tunecino mentioned, it could already be achieved.

**Comment by RSalo** [comment]
@tunecino @samdark it isn't suitable for me, because i need somehow get all attributes of concrete rule of array. If you know how i can do it, advise me plz=)
