### ISSUE TITLE
`UploadedFile` bug with largest files.

### ISSUE THREAD

**Issue by wao138** [yiisoft/yii2#12386]
When uploaded file, more than 200M `UploadedFile::getInstances()` return `null`.
In test i tried load image in `tiff` extension.

For uploaded file, I use extension `yii2-file-upload-widget`.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.4.45
| Operating system | Linux

**Comment by klimov-paul** [comment]
http://stackoverflow.com/questions/4534433/unable-upload-big-files-to-server-using-php
