### ISSUE TITLE
Gii -  Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by xerong** [yiisoft/yii2#12388]
I have a table 'cm_template. and i wanted to generate a model using gii. I already enabled tablePrefix in the config file as '_cm' When i tried to generate a model,  i got the below error. I have tried all i could but i could not fix this error.  Please note that this is my 4th software projects i would do with yii .

SQLSTATE[42000]: Syntax error or access violation: 1102 Incorrect database name ''
The SQL being executed was: SHOW TABLES FROM ``
Error Info: Array
(
    [0] => 42000
    [1] => 1102
    [2] => Incorrect database name ''
)
↵
Caused by: PDOException

SQLSTATE[42000]: Syntax error or access violation: 1102 Incorrect database name ''

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version    | 5.6
| Operating system | win 8

**Comment by SilverFire** [comment]
Please, show your DSN from the `db` component confirugation

**Comment by xerong** [comment]
@silverFire, thanks for your prompt response.
'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost;dbname=churchmanager',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8',
            'tablePrefix'=>'cm_'
        ],

**Comment by SilverFire** [comment]
Ok, I will check this

**Comment by krebse** [comment]
That's like occuring when GII attempt to get relations because when set relations on no relation the error fix !

**Comment by xerong** [comment]
Yes, i created a relationship with another table, cm_templateCategory. I was able to access data on FK (catId) constraints on cm_template. Please see attached mysql table.
I selected "No relation" and i was able to generate the model successfully. But my "Template" class does note contain
public function getTemCategory()
    {
        return $this->hasOne(TemplateCategory::className(), ['id' => 'catid']);
    }
![template-table](https://cloud.githubusercontent.com/assets/5096796/18083373/c56861c0-6e9a-11e6-9258-73f3d9323628.jpg)

**Comment by mainpart** [comment]
Got this issue today.

**Comment by mattxw** [comment]
I encountered this issue. Gii can generate models, but can't generate its relation with another. User registration, migration, and another stuff works except for Gii Model Generator, for now.

**Comment by mainpart** [comment]
put 
`prefer_stable: true`
line in your composer.json and run update - that will give you temporary solution
