### ISSUE TITLE
Component class documentaion's mistake

### ISSUE THREAD

**Issue by agarb7** [yiisoft/yii2#12392]
http://www.yiiframework.com/doc-2.0/yii-base-component.html#behaviors()-detail

Says:
> Behavior names can be strings or integers. If the former, they uniquely identify the behaviors. If the latter, the corresponding behaviors are anonymous and their properties and methods will NOT be made available via the component (however, the behaviors can still respond to the component's events).

But properties and methods of anonymous behaviors will BE made available via the component.

**Comment by cebe** [comment]
fixed, thanks for reporting!
