### ISSUE TITLE
yii\data\Sort active class

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#12397]
want add "active" to current sort link without manual add class with GET param check
```
<?= $oSort->link('name', [
    'class' => ltrim(Y::get($oSort->sortParam), '-') == 'name' ? 'active' : false,
]) ?>
```
sux and wrong with multy

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/data/Sort.php#L148

**Comment by DrDeath72** [comment]
How default order and current order link class related?

**Comment by klimov-paul** [comment]
@DrDeath72, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by DrDeath72** [comment]
it's not bug, it's wanted future

**Comment by cebe** [comment]
@DrDeath72 this feature is already provided but the added class is not `active` but `asc` and `desc` to apply styling dependent on the sort order.

**Comment by DrDeath72** [comment]
attributes can be asc or desc separately by default it can't be used for active mark link

**Comment by cebe** [comment]
not sure what you mean with active then. The class is only added if the current attribute is being used for sort: https://github.com/yiisoft/yii2/blob/master/framework/data/Sort.php#L284-L285

**Comment by DrDeath72** [comment]
hm... my fault, asc or desc class only on current sort attributes...
