### ISSUE TITLE
Accessibility: add ARIA attributes (required and invalid) for inputs

### ISSUE THREAD

**Issue by tekord** [yiisoft/yii2#12399]
Suggestion. Add `aria-required` attribute rendering to required inputs. Example:

``` html
<div class="form-group field-supportissueform-subject required">
  <label class="control-label" for="supportissueform-subject">Subject</label>
  <input type="text" id="supportissueform-subject" class="form-control" 
         name="SupportIssueForm[subject]" aria-required> <!-- here! -->
</div>
```

Also if the field has validation errors then add `aria-invalid` attribute to field.

More about these attrubutes here:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute

**Comment by Oxyaction** [comment]
started work on this feature

**Comment by tekord** [comment]
Thank you :)
