### ISSUE TITLE
a bug  about   the   function   fnmatch

### ISSUE THREAD

**Issue by donblack01** [yiisoft/yii2#12408]
### What steps will reproduce the problem?
   on  the  centos7  install  yii2 2.0.9   

when  I  installed yii2   I  access    http：//localhost/basic/web    show  this problem like  this ：’Call to undefined function yii\base\fnmatch()   in /usr/local/nginx/html/basic/vendor/yiisoft/yii2/base/ActionFilter.php line 150‘  ,
I refer to the PHP manual  this function     support to  php7  so  i do  not  kown  how  to  solve it

### What do you get instead?
  no  

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      |    7.0.10
| Operating system | centos7

**Comment by donblack01** [comment]
![9pa57 la073nbj b6a fc](https://cloud.githubusercontent.com/assets/21120018/18123154/3349907e-6f9f-11e6-9ad9-c0163dc7f5ac.png)

**Comment by klimov-paul** [comment]
I am afraid there is nothing I can help you with. This is definetely not Yii issue.

`ActionFilter` wildcard support is covered by unit test:
https://github.com/yiisoft/yii2/blob/master/tests/framework/base/ActionFilterTest.php#L141

which is correctly passing on PHP 7:
https://travis-ci.org/yiisoft/yii2/jobs/156473399

php.net docs clearly says `fnmatch()` function is a part of the core and should be available at PHP7.

This must be problem with your environment.

**Comment by Alex-Code** [comment]
According to a comment here http://unix.stackexchange.com/questions/305639/centos-6-7-and-fnmatch-in-php#comment537104_305639 this function should be available in the php packages provided by CentOS but may not if you'd compiled it yourself.
