### ISSUE TITLE
Avoid Exceptions for true Database Agnosticism

### ISSUE THREAD

**Issue by danvick** [yiisoft/yii2#12403]
### Suggestion
Could we use warnings instead of exceptions in Queries

Example: in db\oci\QueryBuilder addForeignKey() function:
``if ($update !== null) {
     throw new Exception('Oracle does not support ON UPDATE clause.');
}``

Could we just suppress the $update and turn it to null then warn the user. This will allow one to switch databases without much hassle.

### Additional info
| Yii version      | 2.0.9
| PHP version      | 5.6.23
| Operating system | Windows 10

**Comment by samdark** [comment]
`ON UPDATE` is too important to be ignored. Either you're relying on it or you're relying on code to do the same.
