### ISSUE TITLE
unknown property: yii\widgets\ListView::counter

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2#12405]
| Yii version      | 2.0.9
| PHP version      | 5.6.23
| Operating system | W
![8](https://cloud.githubusercontent.com/assets/16696651/18114278/4c8bfefa-6f36-11e6-8629-4652c0d1547d.png)
10

**Comment by SilverFire** [comment]
Свойство `counter` является статическим, принадлежит классу [Widget](https://github.com/yiisoft/yii2/blob/master/framework/base/Widget.php#L31) и не может быть изменено при создании объекта. Если вы хотите изменить `id` вашей таблицы, пользуйтесь параметром `id`, он будет обработан [сеттером](https://github.com/yiisoft/yii2/blob/master/framework/base/Widget.php#L130-L139)
