### ISSUE TITLE
TypeError in \yii\validators\EachValidator::validateAttribute()

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#12414]
```php
use yii\base\Model;

class ProfileForm extends Model
{
    private $_noticeList = [];

    public function rules()
    {
        return [
            // ...
            [['noticeList'], 'each', 'rule' => ['integer']],
            // ...
        ];
    }

    public function getNoticeList()
    {
        return $this->_noticeList;
    }

    public function setNoticeList(array $data)
    {
        $this->_noticeList = $data;
    }
}

class DefaultController extends Controller
{
    public function actionTest()
    {
        $model = new ProfileForm();
        $model->setNoticeList([1, 2, 3]);
        var_dump($model->validate());
    }
}
```

В результате валидации получаем ошибк:
TypeError:
`Argument 1 passed to common\models\ProfileForm::setNoticeList() must be of the type array, integer given`

EachValidator зачем-то использует для хранения промежуточных значений `$model->$attribute`

```php
// vendor/yiisoft/yii2/validators/EachValidator.php:131
    public function validateAttribute($model, $attribute)
    {
        $value = $model->$attribute;
// ...
        foreach ($value as $k => $v) {
            $model->$attribute = $v;
// ...
        }
// ...
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.10
| Operating system | Linux Debian

**Comment by klimov-paul** [comment]
See #9935

**Comment by LAV45** [comment]
@klimov-paul ну так проблема от этого ведь ни куда не денеся!
Я привел ещё одного пример использования валидатора при катором возникает ошибка.
Если решение данной проблемы имеет смысл, тогда зачем её закрывать?

**Comment by cebe** [comment]
@LAV45 I did not understand the issue, can you try to explain in english?

**Comment by klimov-paul** [comment]
> ну так проблема от этого ведь ни куда не денется!

Проблема #9935 тоже некуда не денется. Ее решение требует использование текущего атрибута в качестве промежуточного хранилища.
В вашем случае вам следует снять строгую типизацию с метода-установщика значения для атрибута.
Помимо проблемы с валидатором, он также будет провоцировать 500 ошибку при неверном формате данных отправленных с формы.
Второй вариант - создавать ваш собственный валидатор.
