### ISSUE TITLE
How to open transaction saving data in the model

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#12410]
I would like to perform a transactional insert and modify the data, but `ActiveRecord` does not provide a way to open a transaction, then how do I solve this problem?

**Comment by samdark** [comment]
Open it using connection.

**Comment by xiaoxing598** [comment]
error 'Call to a member function begin() on null',Do you have an example for me?
```
$db = Yii::$app->getDb();
        $ts = $db->getTransaction();
        $ts->begin();
        try {
            $db->getQueryBuilder()->insert('users',
                [
                    'nickname' => '张三', 'username' => 'zhangshan',
                    'password' => md5('Abc!23'), 'createAt' => time()
                ],
                $params
            );
            var_dump($params);
            $ts->commit();
        } catch (Exception $e) {
            $ts->rollBack();
        }
```

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/yii-db-connection.html#getTransaction%28%29-detail "Returns the currently active transaction."

use beginTransaction() instead.
