### ISSUE TITLE
fileValidator

### ISSUE THREAD

**Issue by SergiiBoiarchenko** [yiisoft/yii2#12415]
### What steps will reproduce the problem?
in controller in create or update action:

$model->file_photo = UploadedFile::getInstances($model, 'file_photo');
$model->save();

in model:
public function rules() {
        return [
              [['file_photo'], 'file', 'maxSize' => 1024, 'extensions' => 'jpg']
        ]
}

### What is the expected result?
validate uploaded files

### What do you get instead?
validator all time return message "Please upload a file."

### Additional info
if property 'maxFiles' for fileValidator not set or set 1 and use UploadedFile::getInstances for multiple upload files the fileValidarot all time return message "Please upload a file."

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9 July 11, 2016
| PHP version      | 5.6.25-2+deb.sury.org~xenial+1
| Operating system | Linux work 4.4.0-21-generic #37-Ubuntu

**Comment by klimov-paul** [comment]
This is expcted behavior since `UploadedFile::getInstances()` returns array, while validator processes only single object.

**Comment by SergiiBoiarchenko** [comment]
Maybe the best way throw exception about misconfiguration validator in this case?

**Comment by klimov-paul** [comment]
There is no missconfiguration of validator - you populate the validated field incorrectly, so it considered empty. Validator just respond the invalid input from the form in correct way.
