### ISSUE TITLE
Bug on migration tool when creating fields with brackets in comment

### ISSUE THREAD

**Issue by uniserpl** [yiisoft/yii2#12423]
### What steps will reproduce the problem?
./yii migrate/create create_sets_table --useTablePrefix=1 --fields="name_ru:string(255):notNull:comment('Name of set (RU)')"

### What is the expected result?
$this->createTable('{{%sets}}', [
     'id' => $this->primaryKey(),
     'name_ru' => $this->string(255)->notNull()->comment('Name of set (RU)'),
]);

### What do you get instead?
$this->createTable('{{%sets}}', [
     'id' => $this->primaryKey(),
     'name_ru' => $this->string(255)->notNull()->comment('Name of set (RU)')**()**,
]);

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 7.0.8
| Operating system | Ubuntu 16.04

**Comment by pana1990** [comment]
i confirm this bug, you see my pr https://github.com/yiisoft/yii2/pull/12513/files
