### ISSUE TITLE
Image Not load

### ISSUE THREAD

**Issue by PeterJason** [yiisoft/yii2#12425]
### What steps will reproduce the problem?

Why yii2 (2.0.6) not load images with names like digit.png, digita.png, digital.png, etc..? If the name of image contains name digit the image not load. Why?

### The code?
echo Html::img(Yii::getAlias('@web'.'/img/asdfdigitasdfsdf.png'));

### What do you get instead?

> Failed to load resource: the server responded with a status of 403 (Forbidden)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.6.15
| Operating system | Windows 10

**Comment by samdark** [comment]
Yii can't deny image access so it should be a problem with server config.

**Comment by PeterJason** [comment]
Are u tried? I'm testing in localhost and only happens with Yii2.
