### ISSUE TITLE
How to use csrf with html5 history?

### ISSUE THREAD

**Issue by SidKwok** [yiisoft/yii2#12424]
### What steps will reproduce the problem?

1. I would like to use `csrf` in yii2.
2. In Frontend I use html5 `history` apis.
3. My website only has one `index.html` and `static`, it means I set up the route in fronend.
4. Every time I visit different urls of my website I will direct it to `index.html` in Nginx.

### What is the expected result?

I would like to set `csrf` for all my urls.

### What do you get instead?

Not all my urls, only `/index`

### My opinion

I rewrite the direction in `Nginx`, so I have no way to use `csrf` in yii2

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |7.0.9
| Operating system |centos 6.3

**Comment by cebe** [comment]
1. csrf is enabled in yii by default: http://www.yiiframework.com/doc-2.0/guide-security-best-practices.html#avoiding-csrf
2. how does index.html relate to yii? yii uses an index.php
3. what kind of redirection are you performing in nginx and how is that related to csrf?
4. how exactly are you using history apis so that this is relevant for csrf?

**Comment by SidKwok** [comment]
1. Thanks.
2. You can check [vue-cli/webpack](https://github.com/vuejs-templates/webpack), it will build a spa. I take it as a `static` file so it works just fine. But if I want to use `csrf`, I have to pass it through `index.php`. 
3. I used history apis to establish routes in front end, so I need to `rewrite` in nginx to make sure `404` won't happen.
4. I would like to use `csrf` in `post` request. 
5. I didn't use `index.php`, which means I can't use session or cookie in my application. What should I do?

**Comment by samdark** [comment]
You can't generate tokens without PHP and seession/cookie. That's how CSRF works — you're saving token somewhere safe i.e. in session or in a cookie and then verifying it w/ what was sent with the form.

**Comment by SidKwok** [comment]
I know. If I want to use cookie/session, I have to go through PHP. But my router is in front end, so I need to rewrite the direction in nginx such like `rewrite ^(.+)$ /index.html last;`, which I found on [this](http://readystate4.com/2012/05/17/nginx-and-apache-rewrite-to-support-html5-pushstate/). But if I go through PHP, my `url` will change, which means if I visit `/index/a`, I still go to `/index`. So how can I go through PHP and in the same time I can visit my exact `url`?

**Comment by samdark** [comment]
I have no idea about how your frontend router works and how/when redirects are performed so sees I can't help unless it's clear.

**Comment by SidKwok** [comment]
Sorry for my poor English.... I use history apis in frontend, which help me `go` to another `url` in frontend instead of refreshing the browser. So I have only one `index.html`, but I have routes like `/index` and `/index/a`.Because I didn't set `/index/a` in `Yii2`, if I visit `/index/a` directly, it will response   `404`. What should I do in `Yii2` to make sure every `url` I visit can direct to the correct `url`. And I would like to use csrf.

**Comment by TerraSkye** [comment]
u could use a catchAll request in Yii, wich redirect all request to 1 path.
that way u have the php layer, and CSRF possibility

**Comment by cebe** [comment]
closing as this is not about a framework bug or feature.
