### ISSUE TITLE
Misleading documentation for yii\db\Connection

### ISSUE THREAD

**Issue by heanluen** [yiisoft/yii2#12429]
### What steps will reproduce the problem?
Go to http://www.yiiframework.com/doc-2.0/yii-db-connection.html

In the description:
"then call open() to be true." is in-correct or misleading. My understanding is that calling open() will return true, but in fact it is a void method. 

### What is the expected result?
It should should be open() followed by getIsActive() to check connection.

### What do you get instead?
NA

### Additional info
NA

**Comment by cebe** [comment]
fixed, thanks for reporting!
