### ISSUE TITLE
could not find driver: Caused by: PDOException

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2#12420]
Not sure how to fix this. 

### What steps will reproduce the problem?
Clean install on Ubuntu 14.04

### What is the expected result?
Database driver is installed

### What do you get instead?
could not find driver
Caused by: PDOException
could not find driver
in /var/www/mp/vendor/yiisoft/yii2/db/Connection.php at line 603

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by githubjeka** [comment]
`sudo apt-get install php5-mysql`

**Comment by JohnMaina** [comment]
I have the issue after running a yii2 project on a different PC (Different from the one it was developed on). I am using Windows 8.1 and WAMP, connecting to a remote SQL server. From PHPinfo(), I can see that I have;
PDO drivers (mysql, odbc and sqlite) enabled. For pdo_mysql, I can see mysqlnd 5.0.11. What could be the problem?

NB. I am new to yii2.
