### ISSUE TITLE
Extra quote when comparing columns using where

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#12427]
### What steps will reproduce the problem?
if you have put sub-query as one of the selecting column with columns check in where condition. 

#### Code Example

```
$order = Order::find()
		       ->select('COUNT([[nOrderID]])')
			->where(['=', Order::tableName().'.[[nUserID]]', User::tableName().'.[[nUserID]]'])
			// Below having the same output too
			// ->where([Order::tableName().'.[[nUserID]]' => User::tableName().'.[[nUserID]]'])
			->createCommand()->rawSql;
										
				
$user = User::find()
			->select(['*', '('.$order.') AS orders'])
			->orderBy('nUserID DESC')
			->one();
```

### What is the expected result?
It should not quote both the parts

````
SELECT *, (SELECT COUNT("nOrderID") FROM "order" WHERE "order"."nUserID" = "user"."nUserID") AS orders FROM "user" ORDER BY "nUserID" DESC
````

### What do you get instead?
It is adding extra quote to the value part of the array in where method.

**Please note extra quote in where condition of sub-query**

````
SELECT *, (SELECT COUNT("nOrderID") FROM "order" WHERE "order"."nUserID" = '"user"."nUserID"') AS orders FROM "user" ORDER BY "nUserID" DESC
````

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      |5.5.12
| Operating system | Win 8
| Database | PostgreSQL 9.4

**Comment by klimov-paul** [comment]
You should either use palin strin to compose your condition or `yii\db\Expression` instance.
