### ISSUE TITLE
Module.php getControllerPath()

### ISSUE THREAD

**Issue by bostin** [yiisoft/yii2#12422]
### What steps will reproduce the problem?
call ```Yii::$app->getControllerPath();``` on Windows OS
### What is the expected result?
D:\wamp\www\local.yii2.com\backend\controllers
### What do you get instead?
D:\wamp\www\local.yii2.com/backend/controllers

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.23
| Operating system | windows 10

### Code:

/path/to/framework/base/Modules.php:235
```
    public function getControllerPath()
    {
        return Yii::getAlias('@' . str_replace('\\', '/', $this->controllerNamespace));
    }
```

I think it should be:
```
    public function getControllerPath()
    {
        return Yii::getAlias('@' . str_replace('\\', DIRECTORY_SEPARATOR, $this->controllerNamespace));
    }
```

Am I right ?

**Comment by krebse** [comment]
Yeah that's just work on Unix platforms

**Comment by cebe** [comment]
it does not matter for PHP but we can fix that.

**Comment by cebe** [comment]
Not easy to fix because in aliases only `/`is allowed as separator. Also `/` works fine as directory separator in PHP on all platforms so I would not change it unless it causes any problems.

**Comment by bostin** [comment]
OK! Thank you! @cebe @krebse
