### ISSUE TITLE
Do not submit active form when AJAX validation returns any erros

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#12449]
Уважаемые коллеги, сделайте наконец-то нормальный ajax error для ActiveForm!
Не надо делать submit, если по каким-то причинам нет полей!!!
Привожу самый простой пример:
```php
<?php                         
  $form = ActiveForm::begin([
    'enableAjaxValidation'=>true,
   ]);
?>
  <?= Html::error($model, 'someAttribute') ?>
  <?= Html::submitButton()?>
<?php $form->end() ?>
```
Казалось бы всё чётко, но 'enableAjaxValidation' всех нас дружно посылает куда подальше. Он даже спрашивать не будет, пришли ошибки или нет, просто форма уйдет в submit. Естественно это связанно с банальным отсутствием полей(пусть даже hidden), как бы нет ввода, то и проверять нечего. И это в корне неправильно. Ведь мы на сервере можем искусственно добавлять ошибки в модель, причем не к конкретному полю, а может быть к виртуальному. 
Простой пример есть куча Html::checkbox('config[]'), и нам не надо выводить ошибки для каждого из них, достаточно было бы общего Html::error($model, 'config'), здесь мы смогли бы форсировать ошибки. Может верстка не позволять поставить ошибки сразу после поля.
Тоже самое касается errorSummary.

**Comment by RSalo** [comment]
Чот понять не могу, тебе нужен ajax error или submit? Ты уже разберись=)

**Comment by exru** [comment]
@RSalo ХОЧУ ЧТОБЫ ФОРМА НЕ САБМИТИЛАСЬ, ЕСЛИ С СЕРВЕРА ПРИЛЕТАЕТ ОШИБКА!!!! ЕСЛИ НЕТ ИНПУТОВ, ДАЖЕ ПРИ НАЛИЧИИ ОШИБОК ОНА УЙДЕТ В САБМИТ!!!!!! ЭТО НЕ ПРАВИЛЬНО!!!! ОШИБКА ЕСТЬ И ЕЁ НАДО ВЫВЕСТИ, А НЕ ИГНОРИРОВАТЬ!!!!!

**Comment by RSalo** [comment]
@exru а как можно сделать аякс валидацию без запроса? Твои варианты? У меня возникает такое ощущение, что ты не пользовался аяксом=)
Что мешает задать урлу, по которой будет проиходить валидация?($validationUrl)

**Comment by SilverFire** [comment]
Translating the idea to non-Russian contributors:

### The use case

1. Render an `ActiveForm` with enabled AJAX validation.
2. Do not render Foo field, required for the active model scenario.
3. Fill all fields to satisfy validation. Submit the form.
4. AJAX validation request returns array with theOne of them is "The Foo field is required"

### What is the desired result?

The submit gets prevented, the error is displayed somewhere in the form.

### What do you get actually?

The submit succeeds, but validation fails on the server side

**Comment by samdark** [comment]
Не согласен с предложением. В некоторых случаях надо сабмитить даже когда нет полей.

**Comment by exru** [comment]
@samdark объясни на пальцах, почему, вместо того чтобы отправлять фичу в топку. В данном случаее это элементарно как синхронизация модели с сервером. Ошибка на серве есть? Есть. Поле для вывода ошибок есть? Есть. Так почему же форма делает сабмит элементарно не проверив перед этим наличие ошибок?

**Comment by samdark** [comment]
Потому что не сделав сабмит нельзя проверить, есть ли ошибка на сервере.
