### ISSUE TITLE
Migrations should force run on master

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/yii2#12446]
### What steps will reproduce the problem?

Configuration with replications:

```
'db' => [
	'class' => yii\db\Connection::className(),
	'dsn' => 'mysql:host=192.168.10.11;port=3306;dbname=kit',
	'username' => 'vagrant',
	'password' => 'vagrant',
	'slaveConfig' => [
		'username' => 'vagrant',
		'password' => 'vagrant',
	],
	'slaves' => [
		['dsn' => 'mysql:host=192.168.10.12;port=3306;dbname=kit']
	]
]
```

create a migration, for example:

```
$this->createTable($this->tb_name, [
    'id' => $this->primaryKey(),
    'status' => $this->smallInteger(1)->notNull()->defaultValue(0),
    'identity' => $this->smallInteger(1)->notNull(),
    'is_online' => $this->smallInteger(1)->notNull()->defaultValue(0),
    'register_at' => $9this->integer()->notNull(),
    'phone' => $this->string(11)->notNull()->unique(),
]);

$this->createIndex('idx_phone', $this->tb_name, 'phone');
```

### What is the expected result?

The migration will run successfully.

### What do you get instead?

There is an error occured.

### Additional info

After create table, It will fetch the schema information, and it will connect to slave to fetch that.

but the replication it not performed.

We can disable slave to resolve this problem?

Just set `Connection::$enableSlaves = false` when execute the migrations. Or some else suggestion?

Thanks.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9?
| PHP version      | 7.0.1
| Operating system | centos

**Comment by samdark** [comment]
Disabling slaves by default makes sense.
