### ISSUE TITLE
My docker environment. Create a project does not run

### ISSUE THREAD

**Issue by 51168** [yiisoft/yii2#12447]
### What steps will reproduce the problem?
1.composer global require "fxp/composer-asset-plugin:^1.2.0"
2.composer create-project --prefer-dist yiisoft/yii2-app-basic basic
3.run localhost/basic/web
get error
Fatal error: Class 'Composer\Autoload\ClassLoader' not found in /acs/code/yiisoft/vendor/composer/autoload_real.php on line 23

### What is the expected result?
Normal operation

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      |5.5
| Operating system |centos6.5 docker

**Comment by cebe** [comment]
how did you install composer and what is the composer version? (`composer --version`)

**Comment by 51168** [comment]
curl -sS https://getcomposer.org/installer | php install composer 
Composer version 1.2.0

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
