### ISSUE TITLE
More options to redirect after login

### ISSUE THREAD

**Issue by cyphix333** [yiisoft/yii2#12458]
I know currently you can utilise the [returnURL](http://www.yiiframework.com/doc-2.0/yii-web-user.html#getReturnUrl()-detail) method, but from what I understand this uses a value from the session and hence wouldn't be 100% reliable.

For example, say the user wasn't logged into the site, they open up 3 tabs and decide to login from the first tab; when they login they will now be redirected to the same location as they have in their 3rd tab, which is incorrect.

The only idea I can come up with is storing the current page info in a hidden form field and then the page they login from will always return the correct page to the login controller.

Yes I can do this myself, but just a suggestion to perhaps add something in a future version where you can automatically get this value filled out by using the [ActiveForm](http://www.yiiframework.com/doc-2.0/yii-widgets-activeform.html) widget and then it will handle the redirect automatically too.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.5.28
| Operating system | Win 7 / CentOS

**Comment by samdark** [comment]
How about the case when you don't have a form at all?

**Comment by cyphix333** [comment]
Well I guess then this option wouldn't be suitable in that instance :stuck_out_tongue: 

But when do people ever login without a form?

**Comment by samdark** [comment]
You may need to redirect back w/o a form and in many instances you don't need to redirect at all so I don't think it should be part of the framework.

**Comment by cyphix333** [comment]
I'm saying make it an option, not replace the current methods with it; and obviously it wouldn't be automatically included as part of each form so when you don't need to redirect you simply don't include that certain field - but if you do, you include it, the framework notices that field and takes care of the redirect for you. :)

**Comment by samdark** [comment]
It's not common enough to be part of the framework.

**Comment by cyphix333** [comment]
With all due respect I disagree - how is it no common that someone wants a user to be redirected to the correct place after login?

**Comment by samdark** [comment]
I mean it should not be added to any form. You can easily do such redirect yourself:

1. A hidden field.
2. Simple `if` in controller.

There's no need for anything special to achieve it.

**Comment by cyphix333** [comment]
Yes I know it's not hugely difficult but it's easier if the framework had a simple form field via ActiveForm which would automatically include the current page url and then automatically take care of the redirect for you so all you have to do is include the form field; simple as that :)

Otherwise you have to get make up the current page url yourself via the current route + add on the query vars and then put something in your controller to do the redirect based off of that value.

Anyway, just my thoughts - no worries if doesn't end up getting added :)

**Comment by samdark** [comment]
`Url::current()` helps you making the value for the URL.

**Comment by cyphix333** [comment]
Hmmmmm ok thanks, but I assume that doesn't work with "pretty ur;l's"? Guess that's not a big deal though.

**Comment by cebe** [comment]
> but I assume that doesn't work with "pretty ur;l's"?

of course it does.
