### ISSUE TITLE
rule date just accept 02 for month

### ISSUE THREAD

**Issue by masiha68** [yiisoft/yii2#12457]
hi
 i use date rule for checking date with his format 1989-02-06
and i wanna the date rule be sensitive to 02 instead of 2
this is my code 
` [['birthDate'], 'date', 'format' => 'php:Y-m-d']`

**Comment by masiha68** [comment]
whats happen !!! why my issue closed

**Comment by samdark** [comment]
Because it's not a framework issue but a question which should be asked elsewhere. See bot's comment for links.

**Comment by masiha68** [comment]
can you get me a rule that validate this date 1989-02-06 ??

**Comment by samdark** [comment]
Not at GitHub.

**Comment by masiha68** [comment]
why???

**Comment by samdark** [comment]
> Because it's not a framework issue but a question which should be asked elsewhere. See bot's comment for links.
