### ISSUE TITLE
ActiveRecord update() returning TRUE?

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#12461]
This is likely a very minor, probably documentation-related issue.

According to the documentation ActiveRecord's [`update()`](http://www.yiiframework.com/doc-2.0/yii-db-activerecord.html#update()-detail) method returns either *integer* or **boolean**. Is this right? We know that it can return `FALSE` when failing, but does it ever really return `TRUE`? When?

I am only bringing this up, because according to the same documentation [`delete()`](http://www.yiiframework.com/doc-2.0/yii-db-activerecord.html#delete()-detail) explicitly only returns *integer* or **false**, rather than *boolean*, which makes sense.

**Comment by CedricYii** [comment]
I guess you are right, it never returns `true`. It is the case for update (https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecord.php#L525) and the same applies for updateInternal() (https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L733).
You could make a pull request to fix it.

**Comment by cebe** [comment]
fixed, thanks for reporting.
