### ISSUE TITLE
ActionColumn : Hide column issue in visibleButtons 

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#12468]
### What steps will reproduce the problem?

I used  `visibleButtons` in actioncolumn like.

```php
'visibleButtons' => [
    'view' => Yii::$app->user->can('/demo/view'),
    'update' => Yii::$app->user->can('/demo/update'),
    'delete' => Yii::$app->user->can('/demo/delete')
],
```
### What is the expected result?

When all button is false at time hide this actioncolumn.

### What do you get instead?

Actioncolumn is not hide when all button is false.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | UBUNTU

**Comment by lebedyncrs** [comment]
I will try to fix it

**Comment by hirenbhut93** [comment]
@lebedyncrs When i used `Closure` at time is work?

**Comment by SilverFire** [comment]
Rejected. See #12480 for details.

**Comment by hirenbhut93** [comment]
Why is close this issue?

**Comment by cebe** [comment]
`$visibleButtons` is evaluated per data cell and not for the whole column, so you can not fix this in the column itself, you have add it manually in your config:

```php
'visible' => Yii::$app->user->can('/demo/view') || Yii::$app->user->can('/demo/update') || Yii::$app->user->can('/demo/delete'),
'visibleButtons' => [
    'view' => Yii::$app->user->can('/demo/view'),
    'update' => Yii::$app->user->can('/demo/update'),
    'delete' => Yii::$app->user->can('/demo/delete')
],
```
