### ISSUE TITLE
Docs: Customizing Query Classes could be improved

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2#12462]
There is a small topic on Customizing Query Classes in the guide:
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#customizing-query-classes

But some points remain unclear to me.

For example, it looks like the guide is advising to write the class Comment and the class CommentQuery in the same file Comment.php. Is it intentional? Then it should be explained and written explicitly.

Another good issue is how to have a model with a default custom query (can be done with init() in the custom query class).
And the most complex and useful information is how to have a model extending another model with a default custom query.
These issues have been explained by @xVismutx in https://github.com/yiisoft/yii2/issues/7869

But it would be really better to find in the guide directly (rather than in a "hard to find" closed issue)!

**Comment by cebe** [comment]
> For example, it looks like the guide is advising to write the class Comment and the class CommentQuery in the same file Comment.php. Is it intentional? Then it should be explained and written explicitly.

no that should not be in the same file, because autoloading would not work anymore. fixed: 5bdca129a4a59ea6074118139983c642a347aaf7

About the other issues, the problem is very specific so I am not sure how to document the solution in a generic way in the guide. maybe a wiki entry is better suited for this?

**Comment by CedricYii** [comment]
Thank you for clarifying this.
It is better to have all information needed in one place (so maybe adding a detail section would then be preferable).
Working with a common model uses by several frontends extending this model is quite common.
I have proposed a new version from which I think I could have guessed the way to do it.
