### ISSUE TITLE
changing CookieValidationKey after each ./init

### ISSUE THREAD

**Issue by vrublevskiyvitaliy** [yiisoft/yii2#12477]
After each deploy of my project (after running ./init) all new cookieValidationKeys are generated. After it I'm loosing all previous cookies. And because project is updating very often, at least one time per day, I think that I don't want to generate new cookieValidationKeys each time. 

My question is this: why do we need to generate new cookieValidationKey at init? What can I lose after I will use only one cookieValidationKey(per application) all the time.

**Comment by samdark** [comment]
Why are you re-initializing the project during deploy?

**Comment by vrublevskiyvitaliy** [comment]
Because in some commit for example I can change some requirements etc. I'm using 2 folders, www1 and www2. One folder for running now project, one for future version. At each deploy I'm using future folder to copy project, setup it, and init. So, it's easier and more cleaner to run ./setup and ./init after each deploy, than to run it only in the cases when it needed. So at each deploy I each time run setup and init.  

But even if I don't run init at each deploy, but only in the cases when it need to be done, the problem is the same. I will lose cookies.

**Comment by samdark** [comment]
How do you prevent overriding `-local.php` files then?

**Comment by samdark** [comment]
Overall it's OK to check for valiation key existence before re-generating.

**Comment by vrublevskiyvitaliy** [comment]
I don't change -local.php files at server. 
Thank you for your time and reply!

**Comment by samdark** [comment]
How do you keep API keys and other production-only info out of Git repository then?

**Comment by vrublevskiyvitaliy** [comment]
@samdark I keep it in Git repository. I understand that it is a bit unsafe. But I want to be sure, that if at my deploy smth will go wrong, I will have site alive. So, I use www1 and www2 system and run init each time.

**Comment by vrublevskiyvitaliy** [comment]
@samdark I don't have a private info(production only), it's just a pet project. So it's a little easier for me.

**Comment by samdark** [comment]
OK. It makes sense to keep a key if it's already there either way.

**Comment by SilverFire** [comment]
Neither [`Installer::generateCookieValidationKey()`](https://github.com/yiisoft/yii2-composer/blob/master/Installer.php#L274) nor [setCookieValidationKey in the init script](https://github.com/yiisoft/yii2-app-advanced/blob/master/init#L211) do not change validation key if it already exists.

When you run `./init`, the script prompts smt like 

```
      exist backend/config/main-local.php
            ...overwrite? [Yes|No|All|Quit] 
```

and if you say Yes, it overrides the entire file, not only the validationKey.

I don't think that `./init` must not take care of configs merging instead of replacing
