### ISSUE TITLE
UrlNormalizer breaks BC

### ISSUE THREAD

**Issue by AnatolyRugalev** [yiisoft/yii2#12475]
I am using `Yii::$app->request->resolve()` in my custom request resolving for testing purpose in `beforeRequest` event of `Application`

### What is the expected result?

Code:
```php
list($route, $params) = Yii::$app->request->resolve();
```
expected to be executed without exceptions

### What do you get instead?

This kind of exception:

![Stack trace](http://dn.imagy.me/201609/06/64d224bcdabf3bfdf561c28c44b537a3.png)

I think at least we can add this to upgrade instructions

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10-dev?

**Comment by cebe** [comment]
it should be disabled by default in 2.0.x then. Enabled by default in 2.1.

**Comment by samdark** [comment]
@cebe can you handle it?

**Comment by klimov-paul** [comment]
Resolved by commit 821f035c90f308e64e12805b3fea3d217cebffc3

**Comment by klimov-paul** [comment]
Fixed bda1dbe004146679cca3177761ad19cf11a769d9

**Comment by AnatolyRugalev** [comment]
Thank you!

**Comment by rob006** [comment]
Guide should be also updated.
https://github.com/yiisoft/yii2/blob/master/docs/guide/runtime-routing.md#url-normalization-
