### ISSUE TITLE
Internet provider with proxy compression - Ajax Call breaks yii2 site 

### ISSUE THREAD

**Issue by papppeter** [yiisoft/yii2#12488]
### What steps will reproduce the problem?
Use mobile net with proxy, compressing site into one file. (css, js is included in main dom)
Try to do Ajax Call.
### What is the expected result?
Working site.
### What do you get instead?
After Ajax call site is broken.

### Additional info
js,css file cannot filtered out because proxy did modify the output.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | Linux

**Comment by SilverFire** [comment]
It what exact way your assets are being broken?

> js,css file cannot filtered out because proxy did modify the output.

What kind of filtration you are talking about?

**Comment by papppeter** [comment]
I think i found the answer as well:

Yii::$app->response->headers->set('Cache-Control','no-transform');

that tells the proxy that code should not be transformed into one page design. (proxy does not includes the js, css files into the html code)
