### ISSUE TITLE
Overriding configuration that uses numeric arrays. AssetConverter

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#12486]
### What steps will reproduce the problem?
Have 2 configuration files that are combined using `yii\helpers\ArrayHelper::merge`

### What is the expected result?
When I have a environment or local configuration directive, I want it to override the configuration.

### What do you get instead?
`AssetConverter` defines its parameters as numeric array. In my opinion this should be an associative array instead of assigning meaning to the order of elements in the array. 

````
public $commands = [
        'less' => ['css', 'lessc {from} {to} --no-color --source-map'],
        'scss' => ['css', 'sass {from} {to} --sourcemap'],
        'sass' => ['css', 'sass {from} {to} --sourcemap'],
        'styl' => ['css', 'stylus < {from} > {to}'],
        'coffee' => ['js', 'coffee -p {from} > {to}'],
        'ts' => ['js', 'tsc --out {to} {from}'],
    ];
````

### Proposal
Add support for associative configuration in `AssetConverter`:

````
public $commands = [
        'less' => ['ext' => 'css', 'cmd' => 'lessc {from} {to} --no-color --source-map'],
        'scss' => ['ext' => 'css', 'cmd' => 'sass {from} {to} --sourcemap'],
        'sass' => ['ext' => 'css', 'cmd' => 'sass {from} {to} --sourcemap'],
        'styl' => ['ext' => 'css', 'cmd' => 'stylus < {from} > {to}'],
        'coffee' => ['ext' => 'js', 'cmd' => 'coffee -p {from} > {to}'],
        'ts' => ['ext' => 'js', 'cmd' => 'tsc --out {to} {from}'],
    ];
````

This can be done without breaking backward compatibility; it offers several pros:
- Allows for proper configuration overriding / cascading.
- Is a bit more readable (although one could argue that an array with just 2 elements is readable as is).
- It can serve as a refactoring template for other occurrences where an numeric array is used when an associative array would be more appropriate.

Since we already have `ArrayHelper::isAssociative`, the refactor will be relatively simple:
Before
````
public function convert($asset, $basePath)
    {
        $pos = strrpos($asset, '.');
        if ($pos !== false) {
            $ext = substr($asset, $pos + 1);
            if (isset($this->commands[$ext])) {
                list ($ext, $command) = $this->commands[$ext];
                $result = substr($asset, 0, $pos + 1) . $ext;
                if ($this->forceConvert || @filemtime("$basePath/$result") < @filemtime("$basePath/$asset")) {
                    $this->runCommand($command, $basePath, $asset, $result);
                }

                return $result;
            }
        }

        return $asset;
    }
````
After;
````
public function convert($asset, $basePath)
    {
        $pos = strrpos($asset, '.');
        if ($pos !== false) {
            $ext = substr($asset, $pos + 1);
            if (isset($this->commands[$ext])) {
                if (ArrayHelper::isAssociative($this->commands[$ext]) {
                    $targetExt = $this->commands[$ext]['ext'];
                    $command = $this->commands[$ext]['command'];
                } else {
                    list ($targetExt, $command) = $this->commands[$ext];
                }
                $result = substr($asset, 0, $pos + 1) . $targetExt;
                if ($this->forceConvert || @filemtime("$basePath/$result") < @filemtime("$basePath/$asset")) {
                    $this->runCommand($command, $basePath, $asset, $result);
                }

                return $result;
            }
        }

        return $asset;
    }
````

**Comment by SilverFire** [comment]
I agree, that the idea is useful, but not happy that after refactoring we can get two different incompatible definitions in `AssetConverter::commands` simultaneously.

**Comment by SamMousa** [comment]
You mean that it would be a problem if in my `web.php` I use a different format from my `local.php` ?

**Comment by SilverFire** [comment]
Yes. I understand that you code will handle this use case, but in general it is not OK to store inconsistent data in the same property

**Comment by SilverFire** [comment]
Maybe, we can create AssetConverterCommand class, that will normalize definitions on creating and provide a unique interface?

**Comment by SamMousa** [comment]
That's always possible, though might be unneeded complexity. You could just mark the old syntax as deprecated and then remove its support in the next BC breaking release.

It's not like this is a big thing for any developer to change.

**Comment by SamMousa** [comment]
Hmm, what about just implementing `setCommand` instead of `public $command` ? Then you can normalize it there and even throw errors on misconfiguration. (Which is an improvement regardless of changing the syntax).

**Comment by klimov-paul** [comment]
Duplicates #10895
