### ISSUE TITLE
Isn't function Model::attributeLabels() supposed to be static?

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii2#12482]
File https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L287 has dynamic function attributeLabels(). This function is overloaded when using Gii model generator. 

### What is the expected result?
It would be reasonable to call that function directly (statically) without creating empty instance. (Why would I need empty instance? Just like in Yii1 CActiveRecord::findAll() was dynamic requiring creating empty instance prior to calling but in Yii2 findAll() was changed to static).

Example of expected call:
User::attributeLabels();

### What do you get instead?
$user = new User();
$user->attributeLabels();

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      | 5.4
| Operating system | Ubuntu

PS. The same applies to other similar functions that don't really need creation of instance and can be used class-wide (generateAttributeLabel etc).

**Comment by noname007** [comment]
this sounds more better 🙉

**Comment by cebe** [comment]
nope, it is not: see #1318. An active record class may implement a mechanism for dynamic fields and thus must determine the value of attributes() or attributeLabel() from an object context.
