### ISSUE TITLE
Db cache never expire

### ISSUE THREAD

**Issue by vov4ik08** [yiisoft/yii2#12487]
Hello. I have some strange problem with cache. I use memcached My code is:
` $content = \Yii::$app->db->cache(function ($db) {
            return ContentModel::find()
                ->active()
                ->select()
                ->with('contentHasFiles')
                ->orderBy(['id' => new Expression('RAND()')])->limit(4)->all();
        }, 10);`

This request return 4 rand record from db. This request is cached and have derution 10 second. But after 10 second data is not changed, it comes from cache. Cache never expier. Help me please. Thank you.

**Comment by samdark** [comment]
So it it memcache, memcached or DB cache?

**Comment by vov4ik08** [comment]
My config.
 ` 'cache' => [
            'class' => 'yii\caching\MemCache',
            'useMemcached'=>true,
            'servers' => [
                [
                    'host' => '127.0.0.1',
                    'port' => 11211,
                    'weight' => 100,
                ],

            ],
        ], `

**Comment by vov4ik08** [comment]
Some strange, after restart Memcached in the server all work correct. Thank you and sorry.
