### ISSUE TITLE
test

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#12485]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by githubjeka** [comment]
Что случилось, братцы?

**Comment by SilverFire** [comment]
Боту стало плохо

**Comment by githubjeka** [comment]
эбола?

**Comment by SilverFire** [comment]
е :)

**Comment by githubjeka** [comment]
Божечки, вот это вас колбасит....

**Comment by cebe** [comment]
it is fixed now.

**Comment by cebe** [comment]
sorry for spamming :)
