### ISSUE TITLE
CORS not work in 2.0

### ISSUE THREAD

**Issue by lomotony** [yiisoft/yii2#12494]
### What steps will reproduce the problem?

I add the corsFilter in behaviors of my controller which extend `\yii\rest\Controller` like below

```
<?php
/**
 * This is class file for Controller.
 * This is base controller for non-restful apis
 *
 */

namespace backend\components;

use Yii;
use yii\filters\Cors;
use backend\behaviors\ControllerBehavior;

class Controller extends \yii\rest\Controller
{
    /**
     * This method is used to valide the user's authority with token.
     * This method is invoked right before an action is executed.
     *
     * The method will trigger the [[EVENT_BEFORE_ACTION]] event. The return value of the method
     * will determine whether the action should continue to run.
     *
     * If you override this method, your code should look like the following:
     *
     * ```php
     * public function beforeAction($action)
     * {
     *     if (parent::beforeAction($action)) {
     *         // your custom code here
     *         return true;  // or false if needed
     *     } else {
     *         return false;
     *     }
     * }
     * ```
     *
     * @param Action $action the action to be executed.
     * @return boolean whether the action should continue to run.
     */
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            $this->attachBehavior('ControllerBehavior', new ControllerBehavior);
            return $this->checkAuth();
        }

        throw new HttpException(400, "Fail to resolve the action.");
    }

    /**
     * serialize the response in format of json
     *
     */
    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];

    public function behaviors()
    {
        return array_merge([
          'corsFilter' => [
              'class' => Cors::className(),
              'cors' => [
                'Origin' => [
                    'http://web.wm.com'
                ],
                'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'DELETE'],
                'Access-Control-Allow-Credentials' => true,
              ],
          ],
        ], parent::behaviors());
    }
}

```

I use angular to call the api which use `POST` verb, but error happens like below

![screenshot - 09082016 - 08 19 23 pm](https://cloud.githubusercontent.com/assets/6621024/18349055/aac75b8c-7601-11e6-9214-6a8e6e96bd7b.png)
![screenshot - 09082016 - 08 19 58 pm](https://cloud.githubusercontent.com/assets/6621024/18349056/aeb8c596-7601-11e6-8c90-d40e46f0d332.png)

I find the `OPTIONS` request call the real action, so cause the action throw 400 exception. I don't know why? I think the `OPTIONS` request should not reach the action.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 5.5.37
| Operating system | linux

**Comment by tunecino** [comment]
1- you are missing the [Options Action](https://github.com/yiisoft/yii2/blob/master/framework/rest/OptionsAction.php) which is defined in `\yii\rest\ActiveController` but not in parent `\yii\rest\Controller`. you'll need to manually add it. (quick example [this](https://github.com/tunecino/Yii2_foundation-apps/blob/cc01d7179cb93936dd74945f0173cbc1725f2963/backend/auth/controllers/TokenController.php#L42) + [this](https://github.com/tunecino/Yii2_foundation-apps/blob/cc01d7179cb93936dd74945f0173cbc1725f2963/backend/auth/config/rules.php))

2- CORS should be handled before authentication + parent authenticator already defined in `\yii\rest\Controller` should be unset. check those 2 links from docs for more details:
http://www.yiiframework.com/doc-2.0/guide-structure-filters.html#cors
http://www.yiiframework.com/doc-2.0/guide-rest-controllers.html#cors
