### ISSUE TITLE
Likely minor bug yiiActiveForm ajax validation

### ISSUE THREAD

**Issue by andrewblake1** [yiisoft/yii2#12499]
I think possibly a bug (though could be something else I have done) however it does appear that:

When ajax validation is enabled for specific individual attributes and if validation has failed such as to produce error message. Clicking submit removes errors of the ajax validated attributes if clientValidation errors are produced.

Works as expected if 
`                if ($.isEmptyObject(messages) && needAjaxValidation) {
`
is changed to 
`                if (needAjaxValidation) {
`

To reiterate:
ajaxValidation is disabled for form but enabled for some attributes e.g. phone number and address validation. Some other fields have some clientValidation.

Typeing invalid data into the ajaxValidated fields triggers ajax validation as expected and errors are displayed.

Problem is that clicking submit when there are failing client validated (non ajax validated attributes) seems to clear the errors of the ajax validated attributes.

**Comment by SilverFire** [comment]
> Works as expected if 
> `if ($.isEmptyObject(messages) && needAjaxValidation) { `
> is changed to 
> `if (needAjaxValidation) {`

We follow the logic not to produce XHR request for the AJAX validation, while there is still something wrong and we can detect on client-side.

Once we click `submit`, we force full form validation from the very beginning, so we clear all error messages (both AJAX and client-side validation) and check all rules. 

Therefore

> Problem is that clicking submit when there are failing client validated (non ajax validated attributes) seems to clear the errors of the ajax validated attributes.

is an expected behavior.

**Comment by andrewblake1** [comment]
@SilverFire, I do understand what you are saying, and yes it would seem on face value your explanation would be correct. However ...

I don't believe it is intuitive for a user that if an attribute is invalidated via ajax onblur, that the error message is removed on submit. If the error message has been brought in via ajax, and the field has not changed then clearing it because there is a client validated error means that the user then has to fix the client validated error, before then clicking submit, to then see the ajax validated error ... messy!

Perhaps a more logical approach would be to run the ajax validated attribute validations immediately after the client validated ones on submit - which I think might be what happens if client validation passes (but not when it fails).

It just simply isn't clean for a user to have to hit submit twice to obtain two separate lists effectively of invalidated fields, 1 that is client validated, and 1 that is ajax validated. This logic should be invisible to the user ... the user shouldn't be effected by what we ajax validate and what we client validate (they don't know what ajax is nor a client normally). To them, the current operation will just seem like a weird bug.

Example of current operation:

1. User enters first name "Andrew", client validated required
2. User forgets to enter last name "Blake", client validated required
3. User enters an invalid phone number, ajax validated, get "Phone number is invalid."
4. User fills in a bunch of other things (intending on checking out the phone number later - or perhaps a lot of this really large form has been auofilled by the browser)
5. User clicks submit - result is "Last name is required" error message - note that the invalid phone number message is now gone.
6. User adds "Blake" to last name - as that is the only hilited error on the page
7. User clicks "Submit" - result is "Phone number is invalid".
8. User fixes the phone number
8. User clicks "Submit" - result is that it finally submits successfully.

Call me fussy, but one way or another (either fixed in Yii, or forked) I can't live with that operation currently just isn't right. When the user clicks submit the first time, one way or another errors with the form should be displayed.

If what I have described above is the current operation then it isn't right. There is a possibility that I have mucked up something somewhere to cause this operation however it appears by @SilverFire's comment that it is expected behaviour, makes it appear to me that this is in fact a bug.

**Comment by SilverFire** [comment]
Makes sense, thank you for a detailed explanation of you POV

**Comment by SilverFire** [comment]
Could you check it after the fix?

**Comment by andrewblake1** [comment]
Will do. Cheers.
