### ISSUE TITLE
Bug in Compare validation(compareAttribute)

### ISSUE THREAD

**Issue by madensit** [yiisoft/yii2#12506]
### What steps will reproduce the problem?
in this validation code :
`['second_attribute', 'compare', 'compareAttribute' => 'first_attribute', 'operator' => '<'],`
i tried to compare second attribute to first attribute and if second one is greater than first one show the error.
it means second attribute must be less than first one.

### What is the expected result?
i expected when i set first attribute value and second one if the second one is greater than first one show the error tha contain (second attribute must be less than "first attribute".)
and when i set correctly don't show error and validate it.

### What do you get instead?
But when the digits of first attribute are not equal to second on it show error wrongly.
i mean for example when first one value is 10 and second one is 7 its true and it hasn't error but yii show error for me, like this :
![image](https://cloud.githubusercontent.com/assets/16185486/18409981/11f5bbfe-776b-11e6-8327-9768e83f1874.png)

but when i set first attribute value 10 and second one 07 it work correctly. like this : 
![image](https://cloud.githubusercontent.com/assets/16185486/18410005/55ad349e-776b-11e6-9c23-4779e12c22a0.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version | 2.0
| PHP version | PHP Version 5.6.4-4ubuntu6.4
| Operating system | Ubuntu x86_64

**Comment by klimov-paul** [comment]
You should set `CompareValidator::type` to be 'nubmer'.
https://github.com/yiisoft/yii2/blob/master/framework/validators/CompareValidator.php#L51
