### ISSUE TITLE
Time to have Yii2 microframework? 

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii2#12500]
I love yii but in some moments it's a way too heavy.  For example when using as API there's bunch of things dealing with views you don't need. 

Is it a time for yii to have its microframework? To me the answer is yes and I vouch for framework that handles request/response, ActiveRecord and Dao, and controllers. 

What do you guys (both core dev and others)  think?

**Comment by Sammaye** [comment]
Views? You are using the REST API aspect of Yii2, right? http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html

**Comment by SilverFire** [comment]
We do have plans to decouple framework components in order to minimize minimum required amount of code. 

We also have a plan to decouple routing and controllers, as well as other framework components. See [Plans for next major release](https://github.com/yiisoft/yii2/wiki/Plan-for-next-major-versions) to know more.

I'm closing this issue because it's too broad to leave it open as a feature request. Thank you

**Comment by klimov-paul** [comment]
Duplicates #11659

**Comment by mtangoo** [comment]
@cebe Micro in terms of code that it depends on to work. I mean the minimum code. I was not aware of the development @SilverFire linked to. So I thank him.

As per difference, I think I was a bit vague. Yii is already wonderful in writing code as you just demonstrated, but it comes with a lot of code that are tightly coupled and in many cases you don't use them nor they are necessary. Like the case when you just need REST Part view becomes redundant which also means bootstrap,jquery, Grids et al are not needed. So I think my concept of microframework means stripped to only necessary.

I will follow the linked threads closely.
Thank you!

**Comment by mtangoo** [comment]
@klimov-paul You are right. 
github should have a "merge issues" ;)

**Comment by Sammaye** [comment]
Though, I see your point, being in the code base doesn't mean the classes and files are actually loaded.

**Comment by mtangoo** [comment]
>Though, I see your point, being in the code base doesn't mean the classes and files are actually loaded.
well what about bundling those files that are actually loaded as micro and leave the user to choose "full" framework when they need the rest. That is one of my points I was trying to raise. I see the discussion in linked issues. There are some things already explained there better than I could do
