### ISSUE TITLE
Yii2 ActiveRecord : not throw error when a attribute is not load (or set)

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [yiisoft/yii2#12507]
### What steps will reproduce the problem?
```
# Role Table Structure (#id,#name,#enable)
$role =
	Role::find()
		->select('id,name')
		->where(['id' => 1])
	->one()
;
		
var_dump($role->enable);
```

### What is the expected result?
return `NULL` !
### What do you get instead?
i believe this behavior should not be exists in yii2 framework.
yii2 must throw error if a attribute not be selected from query.
why ?
i always select needed column for better performance in memory usage.
for example i have a table posts(`#id,#title,#content,#a_longblob_field,#enable`) and i want only enable or disable a post. so to do this only select `id` and `enable` , then change enable column value.
in this operation column `content` and `a_longblob_field` not be loaded.
after a few months , i changed a piece of code. this change is related with a access to new column.
and when run yii2 project , my yii2 project do not throw error. this is dangerous !
do this feature is in yii2 ?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.3

**Comment by SilverFire** [comment]
In general it is recommended to code as specific conditions as possible in order to prevent unexpected behavior.

Suggested behavior implementation is a major BC breaking change and will not be implemented.
