### ISSUE TITLE
Documentation of the User::can() method

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#12517]
It seems to me that the `User::can()` method documentation and signature are somewhat misleading. I personally used to think for a long period of time that this method can only check **permissions** until I've managed to inspect the sources.

The documentation states that the method checks if the user can perform the operation as specified by the given **permission** while it can actually check it by a given **role** to.

The `$permissionName` argument name is also misleading. I would suggest to use `$itemName` (like [here](https://github.com/yiisoft/yii2/blob/master/framework/rbac/PhpManager.php#L124)) or something generic like this.

The `User::can()` method name is misleading too. The `can` verb can be used with permissions not roles. You can say: `Can I moderate the forum?` but you can't say `Can I the forum moderator?`. There should be a separate method for checking roles like `User::is()` or something similar.

**Comment by samdark** [comment]
The name is specified as so intentionally. While you can pass roles in, it's not a good idea to do so since it defies the purpose of RBAC except edge cases.
