### ISSUE TITLE
Suggestion: yii\grid\DataColumn Closure $format

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#12515]
Currently the [`$format`](http://www.yiiframework.com/doc-2.0/yii-grid-datacolumn.html#$format-detail) only takes *string* or *array*. Could we add support for *Closure*, like it's done with [`$value`](http://www.yiiframework.com/doc-2.0/yii-grid-datacolumn.html#$value-detail)?

Here is a simple use case for this: Your model separately stores a `$price` and a `$currency`. You want to use the 'currency' format in your DataColumn to display the price using the corresponding currency. Right now there is no way to pass the `$currency` value as it is stored in the model to the formatter.

Adding Closure to 'format' would allow us to use DataColumn as follows:

    [
        'class' => DataColumn::className(),
        'attribute' => 'price',
        'format' => function($model) { return ['currency', $model->currency]; },
    ]

**Comment by SilverFire** [comment]
I don't see a good reason to introduce dynamic format because it was designed to be as light as possible. Need something more - put a closure in the `value` option:

```php
    [
        'class' => DataColumn::className(),
        'attribute' => 'price',
        'value' => function($model) { 
            return Yii::$app->formatter->asCurrency($model->price, model->currency);
        },
    ]
```
