### ISSUE TITLE
Insert query builder doesn't use schema cache in case of table with alias

### ISSUE THREAD

**Issue by sleptor** [yiisoft/yii2#12518]
``` php
$db = Stat::getDb();
$query = $db->getQueryBuilder()->insert('{{%stat}} as s', $cols, $params);
$db->createCommand($query, $params)->execute();
```

The code will work well, but table schema will never being cached even schemaCache is enabled into connection.

The problem here https://github.com/yiisoft/yii2/blob/master/framework/db/Schema.php#L125
getRawTableName method assumes that no alias in a table name.

I guess it's not a bug and it works as designed. 
I suggest improving QueryBuilder Insert method to allow use array as table name with an alias.
For instance,
$db->getQueryBuilder()->insert(['{{%stat}}' => 's'], $cols, $params);

**Comment by SG5** [comment]
@sleptor can you say what database do you use?

**Comment by sleptor** [comment]
@SG5 It was postgress 9.5 and it seems to me the issue is not related to DB version or vendor.

**Comment by SG5** [comment]
@sleptor I think it is, because Mysql doesn't support alias with `INSERT`

**Comment by cebe** [comment]
what's the point of an alias in INSERT?

**Comment by sleptor** [comment]
@cebe Sure, aliases are not strongly necessary. You can do without them even in SELECT queries. But it makes a query more compact and readable especially complex queries.

Why alias (or table name) was required in my query:
```
INSERT INTO statistics AS s ("a_id", "b_id", "c_id", ... "created_at") 
VALUES (...) 
ON CONFLICT ("a_id", "b_id", "c_id", ... "created_at") 
DO UPDATE SET counter= s.counter+1, counter2 = s.counter2+1, amount = s.amount + ...
```
if remove alias here we'll catch error:
```
SQLSTATE[42702]: Ambiguous column: 7 ERROR: column reference "counter" is ambiguous
LINE X: DO UPDATE SET counter=counter+1
```

**Comment by sleptor** [comment]
Since Upsert has arrived in 2.0.14 my exact case is not actual anymore I guess.
