### ISSUE TITLE
Formatter::asDecimal() with intl when $decimals not set

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#12520]
``` PHP
/**
 * Formats the value as a decimal number.
 * ...
 * @param integer $decimals the number of digits after the decimal point. If not given the number of digits is determined from the
 * [[locale]] and if the [PHP intl extension](http://php.net/manual/en/book.intl.php) is not available defaults to `2`.
 * ...
 */
public function asDecimal($value, $decimals = null, $options = [], $textOptions = [])
```

When PHP intl extension is enabled the number of decimal digits after the decimal point is NOT determined automatically from locale because ICU does not have such functionality. If intl is enabled and `$decimals` is `null` the `Formatter::createNumberFormatter()` will do:

``` PHP
        if ($decimals !== null) {
            $formatter->setAttribute(NumberFormatter::MAX_FRACTION_DIGITS, $decimals);
            $formatter->setAttribute(NumberFormatter::MIN_FRACTION_DIGITS, $decimals);
        }
```

If not specified `NumberFormatter::MIN_FRACTION_DIGITS` defaults to 0 and `NumberFormatter::MIN_FRACTION_DIGITS` defaults to 3 ALWAYS regardless of locale set for the `NumberFormatter`.

This is very easy to test:

``` PHP
<?php
$f = new \NumberFormatter("en", \NumberFormatter::DECIMAL); // set whatever locale you want
var_dump($f->getLocale());
var_dump($f->getAttribute(NumberFormatter::MIN_FRACTION_DIGITS)); // will be 0
var_dump($f->getAttribute(NumberFormatter::MAX_FRACTION_DIGITS)); // will be 3
```

`Formatter::asDecimal()` should be fixed to always default to a value of 2 for `$decimals` regardless if intl is enabled or not.

**Comment by cebe** [comment]
> Formatter::asDecimal() should be fixed to always default to a value of 2 for $decimals regardless if intl is enabled or not.

why exactly?

**Comment by cebe** [comment]
current default will format the following:

input | output
--- | ---
123.456798 | 123.456
123.5 | 123.5
123 | 123

which is a good default imo.

**Comment by PowerGamer1** [comment]
> why exactly?

Because currently if someone uses `Formatter` without intl and then enables intl many numbers in different places will be formatted differently. The result of decimal number formatting with and without intl ideally should be the same. For example, when someone uses `asDecimal` to format currency numbers (without currency code, so `asCurrency` cannot be used) without intl they will be formatted correctly: 123.4 will be 123.40. But then if intl is enabled the currency number 123.4 will be formatted incorrectly as 123.4.

Besides, at the very least incorrect comment:
```PHP
If not given the number of digits is determined from the [[locale]]
```
should be fixed.

**Comment by cebe** [comment]
Its hard to find a suitable default here, using a number of 2 always does not seem useful to me, also re-implementing intl to keep the behavior would be overkill. I adjusted the docs about this to be more explicit.
