### ISSUE TITLE
Setting options inside active field widget problem

### ISSUE THREAD

**Issue by esaesa** [yiisoft/yii2#12524]
The modification is done based on [https://github.com/yiisoft/yii2/issues/9536](https://github.com/yiisoft/yii2/issues/9536) but is issue is happened whatever used inside options
The following image for normally generated captcha using the code

    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                        
                    ]) ?>

The second image is with wrong field
![yp9ayj](https://cloud.githubusercontent.com/assets/5354709/18453982/26341718-7942-11e6-9360-a396e0128c20.jpg)
Modifing the field to add a placeholder as follow makes the field loose its bootstrap class

    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                        'options'=>['placeholder'=>'Enter the captcha word']
                    ]) ?>
![wjdaqo](https://cloud.githubusercontent.com/assets/5354709/18453986/2f3da202-7942-11e6-8ae5-4b7d681c7e6f.jpg)

**Comment by SilverFire** [comment]
[`Captcha::$options`](https://github.com/yiisoft/yii2/blob/master/framework/captcha/Captcha.php#L84) array is pre-defined in the class properties, so once you pass you own options, you override the default. Solution: pass `'class' => 'form-control'` as well
