### ISSUE TITLE
Database logging causes bad performance for large queries

### ISSUE THREAD

**Issue by kidol** [yiisoft/yii2#12528]
Problem is `yii\db\Command:execute()` and related methods always call `getRawSql()` to log the query: https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L830
Of course, `Yii::info()` is always called, even if there is no related log target.

This is for just 3.000 large rows inserted (in one query), adds a 9 second overhead. :boom: 

Before:

![rawsql1](https://cloud.githubusercontent.com/assets/440902/18464291/665fbf1a-7990-11e6-8af1-7e5637cd614e.png)

After commenting out `$this->getRawSql()` in `Command::execute()`:

![rawsql2](https://cloud.githubusercontent.com/assets/440902/18464324/a43def96-7990-11e6-91d0-024a81fbb802.png)

Possible solution is to add `$logQueries` to `Connection` class. Setting it to `false` would skip all calls to `Yii::info()` as well as `getRawSql()` within `Command` class.

**Comment by SilverFire** [comment]
Most probably disk IO takes that overhead time.

Do you have YII_DEBUG enabled?
Did you try to create a `/dev/null` handler for `yii\db\Command::execute` message category?

**Comment by kidol** [comment]
No it's only about the call to `getRawSql()`. I don't even have a log target for db.

You can see in stats above, 2.370 seconds are spend within `getRawSql()` itself, the rest (~6.4 seconds) are spend in the methods it's calling.

**Comment by klimov-paul** [comment]
Method `Command::getRawSql()` may cause a perfromance impact  since it parses parameters in the SQL and replaces it with thier values. These string processing may take significant time to be performed.
However, it is still unlikely it will take several seconds to do so.

**Comment by klimov-paul** [comment]
In your timeline it seems the method `Connection::getSlavePdo()` causes the time consumption.
It is used inside `Schema::quoteValue()`, which is used at `Command::getRawSql()`.

**Comment by kidol** [comment]
I have looked at `getSlavePdo()` before and noticed nothing unusual in the way it works. It's expected I guess because it's called 24k times - unnecessarily in this case. Also I have no slave configured.

>However, it is still unlikely it will take several seconds to do so.

9,000 milliseconds / 3,000 rows = 3 ms per row. These are rather large rows (causing big sql string and 3000 * 12 params `getRawSql()` has to crunch through).

**Comment by klimov-paul** [comment]
Are you able to compose standalone performance test for this matter?

**Comment by kidol** [comment]
Argh xdebug has increased those number :smile: But it gets even more obvious without it.

Time taken: 4.148236989975
vs
Time taken: 0.6350359916687

Run snippet, then change in `execute()`
```php
$rawSql = "X"; //$this->getRawSql();
```

and run again...

```php
$start = microtime(true);
$values = '';
$params = [];

for ($i=0; $i<10000; $i++) {
    $values .= "(:a1_{$i}, :a2_{$i}, :a3_{$i}, :a4_{$i}, :a5_{$i}, :a6_{$i}, :a7_{$i}, :a8_{$i}, :a9_{$i}),";
    $params["a1_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a2_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a3_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a4_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a5_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a6_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a7_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a8_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
    $params["a9_{$i}"] = [str_repeat('a', 50), \PDO::PARAM_STR];
}

$values = rtrim($values, ',');

try {
    \Yii::$app->db->createCommand("INSERT INTO nonexisting (a1, a2, a3, a4, a5, a6, a7, a8, a9) VALUES {$values}")->bindValues($params)->execute();
} catch (\Exception $e) {
    die("Time taken: " . (microtime(true) - $start));
}
```

**Comment by sleptor** [comment]
discovered the same issue recently.

my workaround was not to use execute method directly
$cmd = $db->createCommand($query, $params);
$cmd->prepare(false);
$cmd->pdoStatement->execute();

**Comment by cebe** [comment]
related to #7608

**Comment by sleptor** [comment]
great! thank you
