### ISSUE TITLE
captcha not change on page refresh

### ISSUE THREAD

**Issue by mozhgan-km** [yiisoft/yii2#12527]
I am using the default captcha implementation of the yii2 advanced framework. I have a problem: I want to change my captcha  every time I refresh a page but when I refresh the page my captcha  does not change.
also when captcha client validation failed ,captcha code doesnt change and doesnt refresh itself automatically, i think it made brute force problem.

**Comment by SilverFire** [comment]
See http://www.yiiframework.com/doc-2.0/yii-captcha-captchaaction.html#$testLimit-detail

**Comment by SilverFire** [comment]
And http://www.yiiframework.com/doc-2.0/yii-captcha-captchaaction.html#getVerifyCode()-detail

**Comment by bhargav3vedee** [comment]
You can try this simple way,

```
<script>

window.onload = hello;

function hello()
{    
  document.getElementById('loginform-captcha-image').click();
}

</script>
```
