### ISSUE TITLE
UrlRules not working on module

### ISSUE THREAD

**Issue by aryraditya** [yiisoft/yii2#12526]
i tried to use Url::to('site/index') on module, but it seems like not work properly

my url rule on config
`
            'rules' => array(
                'home'=>'site/index',
            ),`

i tried code bellow on `modules/admin/views/default/index.php` and the results are like not depending the rules

```php
<?php print_r(yii\helpers\Url::to('site/index')); ?> \n
<br>
<?php print_r(yii\helpers\Url::to(['site/index'])); ?>
<br>
```

results : 

> site/index
/yii2/basic/web/admin/site/index 

but when i try outside the modules, it is working properly

**Comment by zelenin** [comment]
```Url::to('/site/index')```
use forum for questions
