### ISSUE TITLE
ContentNegotiator should throw 406 Not Acceptable instead of 415 Unsupported Media Type

### ISSUE THREAD

**Issue by chervand** [yiisoft/yii2#12539]
### What steps will reproduce the problem?

Send a request to a RESTful endpoint with HTTP header `Accept` containing not supported by the server format (i.e `text/html`).
### What is the expected result?

`406 Not Acceptable` response code returned.
### What do you get instead?

`415 Unsupported Media Type` response code returned.
### Additional info

In case server is incapable to respond with acceptable by client format it should return 406.
415 should be returned only if server can't process received entity according to `Content-Type` header (requests like POST or PUT).

ContentNegotiator throws UnsupportedMediaTypeHttpException in that case.

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.5.9 |
| Operating system | Ubuntu 14.04 |

**Comment by klimov-paul** [comment]
Resolved by commit 2e01076abc2c5d4db9edbc2043e8e9442bdfe294

**Comment by SamMousa** [comment]
@samdark I think this needs to be reopened. The fix never got committed to the correct branch.
