### ISSUE TITLE
Yii2 Gridview Pjax Not Working On Ipad,Iphone

### ISSUE THREAD

**Issue by thiruopti** [yiisoft/yii2#12535]
Create a sample gridview with pjax option
update any row of the grid using jquery ajax. after completing ajax, reload the grid using pjax like following, -  $.pjax.reload({container:container_id});

The corresponding row status should be updated without page refresh

Nothing get updated, Only after reloading the grid was updated
Problem exist only in ipad,iphone only

**Comment by TerraSkye** [comment]
Is it in safari or chrome?

**Comment by tunecino** [comment]
@thiruopti  could you try this ?
```javascript
$.pjax.reload({container: container_id, timeout: 1000})
```
may be related to https://github.com/yiisoft/yii2/issues/9040

**Comment by dynasource** [comment]
something for the pjax forum
