### ISSUE TITLE
When handle the db exception from controller then email target is not working.

### ISSUE THREAD

**Issue by ceovishnu** [yiisoft/yii2#12536]
When u handle the db exception from controller then email target configuration not working for same exception. And same issue occur in file target.  

It's should work in both case controller,email as well as file target as per your configuration.

Whenever i submit the from at that time i handle the db exception through try and catch but i have already configured the email target for db error so this email target is not working.**

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | Ubuntu 15.10

**Comment by samdark** [comment]
How to reproduce the issue?

**Comment by ceovishnu** [comment]
controller code is below with exception handling.

```
public function actionUpdate($id) {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
                $model->validate();
                $model->id='dasdasdasdasd';
            try {
                $model->save();
            } catch (\Exception $e) {
                $exception = $e->getMessage();
            }
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }
```

And frontend/config/main code is below

```
'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\DbTarget',
                    'levels' => ['error', 'warning'],
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error','warning'],
                    'categories' => ['yii\db\*'],
                ],
                [
                    'class' => 'yii\log\EmailTarget',
                    'levels' => ['error','warning'],
                    'categories' => ['yii\db\*'],
                    'message' => [
                        'from' => ['log@example.com'],
                        'to' => ['admin@example.com', 'developer@example.com'],
                        'subject' => 'Database errors at example.com',
                    ],
                ],
            ],
        ],
```

when i submit the update form at time throw db exception but in this case this db exception notification does not send throug an email as per my configuration.

in short suppose when we handle the exception from the controller or any action at a time it's does not send email or file exception handling as per configuration from frontend but when i disable the exception handling from the controller or action at that time it's exception work as send the email or file target as per configuration.

**Comment by TerraSkye** [comment]
isnt that cause u catch the exception? instead of letting it forward to the errorhandler?

**Comment by samdark** [comment]
It is. You need to re-throw it in order for it to be logged. Or, get a message and log it yourself.
