### ISSUE TITLE
Cache about UrlManager

### ISSUE THREAD

**Issue by undefinedor** [yiisoft/yii2#12530]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.10
| Operating system | Windows

Why not add new  property like 'enableCache' to  decide whether to enable  caching。
The property named 'cache' just to select the cache object or the ID of the cache application component that is used to cache the metadata.
```php
/**
     * @var Cache|string the cache object or the application component ID of the cache object.
     * Compiled URL rules will be cached through this cache object, if it is available.
     *
     * After the UrlManager object is created, if you want to change this property,
     * you should only assign it with a cache object.
     * Set this property to false if you do not want to cache the URL rules.
     */
    public $cache = 'cache';// line 112
```

**Comment by SilverFire** [comment]
This is a common way of configuring something in Yii. Answering on question `why not`, I can say that it's just a question of decision in the project coding style.

Sorry, but I have to reject the suggestion.
