### ISSUE TITLE
No active controller is available in ActiveController

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2#12543]
### What steps will reproduce the problem?

I have a ActiveController. The default action work for crud but i have an `extraPatterns` and define it in my `actions()`:

``` php
$actions['all'] = [
    'class' => All::class,
    'modelClass' => $this->modelClass,
    'checkAccess' => [$this, 'checkAccess'],
];
```

This error just occurred in `all` route not default crud actions.

Create url in my model with `Url::to(['test/view', 'id' => 12], true)`
### What is the expected result?

Url should be created, I implement `getLinks` method in my model.
### What do you get instead?

This Error: 

```
"message": "Unable to resolve the relative route: test/view. No active controller is available.",
```
### Additional info

| Q | A |
| --- | --- |
| Yii version | dev-master |
| PHP version | 5.6 |
| Operating system | Ubuntu 14.04 |

**Comment by cebe** [comment]
> Url::to(['test/view', 'id' => 12], true)

use `'/test/view'` insetad of `'test/view'`.

**Comment by jafaripur** [comment]
@cebe Thank you. But this is not correctly create the url, This ul is created:

```
http://localhost/api/web/test/view?id=57da7cf054df560d2e10d191
```

But expected is this:

```
http://localhost/api/web/v1/test/57da7cf054df560d2e10d191
```

I used module for my rest services.

**Comment by mdmunir** [comment]
@jafaripur 
show your `url rules` and `extraPaterns`

**Comment by jafaripur** [comment]
```php
[
    'class' => \yii\rest\UrlRule::class,
    'controller' => 'v1/test',
    'pluralize' => false,
    'tokens' => [
        '{id}' => '<id:\\w+>'
    ],
    'extraPatterns' => [
        'GET all' => 'all',
        'OPTIONS all' => 'options',
    ],
],
```

**Comment by mdmunir** [comment]
> This error just occurred in `all` route not default crud actions.
> The problem is just exist in `all` route.

IMO this issue is come from your `All` class not from yii

**Comment by jafaripur** [comment]
``All`` route class is a normal action and extend from ``yii\rest\Action`` and similar to rest default view route ``yii\rest\ViewAction``

**Comment by cebe** [comment]
@jafaripur could you check whether this issue has been fixed in YIi 2.0.10?

**Comment by cebe** [comment]
related to #12795

**Comment by jafaripur** [comment]
@cebe Yes, It's fixed.

**Comment by cebe** [comment]
Great, thanks for the feedback!
