### ISSUE TITLE
Recent change in View::registerCssFile and View::registerJsFile is breaking asset urls

### ISSUE THREAD

**Issue by glennmicallef-betsson** [yiisoft/yii2#12544]
Most of the logic in both functions has been refactored but is mostly the same. 
However the following line was added to the logic and it's removing @web alias result from urls.

`$url = str_replace(Yii::getAlias('@web'), '', $url);`

I'm not sure why this was done however I don't think it should be done this way.
File: yii2/framework/web/View.php
Commit to master: fd6dd73cec3e7a35855c9d088f839581a9e09ace

**Comment by SilverFire** [comment]
Probably it could cause some problems, but I don't see them for now.

Could you describe your use case? What is the asset URL you are trying to register, what is `@web` alias value, what link do you expect and what do you get instead.

Thank you

**Comment by SilverFire** [comment]
Most probably you have `@web` alias value overlaps that with the URL in some way.

**Comment by glennmicallef-betsson** [comment]
Yes that is exactly the case.

Examples where this is not working would be:

@web value: `/backend`

I have a case when there is an external absolute url (cdn) which happens to have /backend
URL: `https://cdn123.cdn.net/cdn-origin/backend/assets/8e6a4a56/dist/js/script.min.js`

I have another case when I am running the application at an offset (en/blog) and I need make every request starting with /en/blog/backend/... otherwise the server will never grab my request. I am doing this by setting the AssetManager baseUrl to `/en/blog/backend` and it used to work until this update.
URL: `/en/blog/backend/assets/8e6a4a56/dist/js/script.min.js`

In both cases `/backend` is being removed from the url.

Thanks
