### ISSUE TITLE
Allow configuration of key used with REST Actions

### ISSUE THREAD

**Issue by MatthewDaize** [yiisoft/yii2#12556]
Just being a nitpick but currently, REST UrlRule and related Actions are hard-coded to use the primary key (id) in order to identify/find models. This works great, however if you design your application so the primary key is not exposed, the current implementation just does not work -- it requires re-creating each of the CRUD methods.

Our current API implementation prevents the primary key from being exposed/used to reduce attack surface in the form of brute-forcing/guessing primary keys throughout the resource methods. As an alternative, we have a separate unique field that uses UUID as the format -- we did not want to re-code the models to use UUID as a primary key (since string-based primary keys can be much more complex and less supported in some cases).

At this point, we write CRUD methods to get around this, but It would be helpful if either a separate configuration parameter used to re-define what UrlRule uses as a key for each of the methods, and use an out-of-box class for this purpose.

**Comment by mdmunir** [comment]
```php
[
    'class' => 'yii\rest\UrlRule',
    'controller' => 'user',
    'tokens' => [
        '{id}' => '<uuid:\\w+>'
    ]
]

Url::to(['user/view', 'uuid' => 'asdfgqwqwqoi4355']); // yoursite.com/users/asdfgqwqwqoi4355
```

**Comment by fernandezekiel** [comment]
it sure looks like a nitpick to me, 
however you can always reconfigure the Action::$findModel and insert your own finder, no need to create new actions

**Comment by MatthewDaize** [comment]
Thank you for confirming this. I had previously overridden the action class in order to attain this.

I wasn't sure if it was worth bringing up that it uses primaryKey() to find the model instead of allowing it to support other unique keys out of box.

Thanks!
