### ISSUE TITLE
TimestampBehavior

### ISSUE THREAD

**Issue by sbilyalov** [yiisoft/yii2#12551]
I start a new project with yii2 (latest version on 14/08/16). I try to use TimestampBehavior on my model like this (in my old project its worked fine):

```
/**
* @inheritdoc
*/
public function behaviors()
{
    return [
        TimestampBehavior::className(),
        'value' => function () {
            return new Expression('UTC_TIMESTAMP()');
        }
    ];
}
```
I am get exception: Calling unknown method: yii\db\Expression::attach()

Use example from docs:
```
/**
* @inheritdoc
*/
public function behaviors()
{
    return [[
        TimestampBehavior::className(),
        'value' => new Expression('UTC_TIMESTAMP()')
    ]];
}
```

Get Unsupported configuration type: object

### Additional info

| Yii version      | 2.0.9
| PHP version      | 5.5.x
| Operating system | Max OS 10.11.06

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html#using-timestamp-behavior

You forget 'class' key
