### ISSUE TITLE
Can't Install Yii2 on Heroku.

### ISSUE THREAD

**Issue by pareekbhagu** [yiisoft/yii2#12558]
I'm trying to install Yii2-basic-application template on Heroku. 
But I'm facing dependency/composer issues. 

The application runs perfectly on local machine, but while deploying to `heroku`, it throws
a ReflectionClass Error, (Class yii\debug\Module not found). This exception is about yii2-debug
module (https://github.com/yiisoft/yii2-debug). 
I don't know anything about the internal workings of composer. 
I have run `composer update`, `composer dump-autoload` but no help.
The files actually exist on the server, which makes me think it might be a problem about class-mapping in composer related files.

I would also appreciate alternate workarounds, as it is critical.

If it is the composer-asset-plugin that is causing it, Isn't there a manual workaround ? Shouldn't it be mentioned somewhere on forums, while Yii team fixes it in the next upcoming version of Yii2, a  working solution	that can atleast ENSURE that application will install perfectly. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by mdmunir** [comment]
Are you using option `--no-dev` in composer?

**Comment by pareekbhagu** [comment]
no. Didn't run composer update with `-no-dev` option ..my require-dev section is here .. 

"require-dev": {
        "yiisoft/yii2-codeception": "*",
		
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },

I moved the yii2-debug from required-dev to required.

**Comment by SilverFire** [comment]
Heroku uses `composer install` with `--no-dev` [as a default](https://devcenter.heroku.com/articles/php-support#build-behavior). You have `debug` listed in `bootstrap` section of Yii application config, but do not have dev-dependencies installed.

You can either:
 * move `yiisoft/yii2-debug` to `require` section of `composer.json` 
 * do not use debug-panel on the prod environment.

Choose one of these and push your application again

**Comment by SilverFire** [comment]
Proof: http://yii2-basic-app.herokuapp.com/

**Comment by pareekbhagu** [comment]
I shall be so thankful if you could kindly list the exact steps you followed to make the above app running? 
 That way I might get an insight into what am I doing wrong.

**Comment by SilverFire** [comment]
* Open `composer.json` and move `yiisoft/yii2-debug`, `yiisoft/yii2-gii` from `require-dev` to the `require` section
* `composer update`
* `git add composer.lock composer.json && git commit -m 'updated composer.json'
* `git push heroku master`

Something like this

**Comment by cainns98** [comment]
@SilverFire I am having an issue with routing on an Advanced Yii2 install. All views other than index return not found. I have been searching with no hope. Just loaded your heroku above, and it too has issues with routing. (all the links result in 404s)

Any ideas?

**Comment by omzy** [comment]
> * Open `composer.json` and move `yiisoft/yii2-debug`, `yiisoft/yii2-gii` from `require-dev` to the `require` section
> * `composer update`
> * `git add composer.lock composer.json && git commit -m 'updated composer.json'`
> * `git push heroku master`
> 
> Something like this

How is this a valid solution? On production I don't need dev dependencies, so I should be able to install by doing `composer install --no-dev`. However this results in the error message "ReflectionException : Class yii\debug\Module does not exist".

Yes I have `debug` listed in the application config, but this is enclosed within `if (YII_ENV_DEV) {`. So it should never try to load it in.

**Comment by samdark** [comment]
@omzy It should not be loaded if it's enclosed properly...

**Comment by guillovale** [comment]
thanks Silver
