### ISSUE TITLE
dbsession row user expired don't be deleted 

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#12559]
### What steps will reproduce the problem?

a session expire the row in the session table still in the table

### What is the expected result?

auto-clean session table

### What do you get instead?

https://github.com/yiisoft/yii2/blob/master/framework/web/DbSession.php#L214

why the maxlifetime isn't used in the function ?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6
| Operating system | *

**Comment by mdmunir** [comment]
if you want system always deleted expired session, set `gcProbability = 100`

**Comment by samdark** [comment]
It's by design as @mdmunir mentioned.
