### ISSUE TITLE
framework/di/Container.php getDependencies bug

### ISSUE THREAD

**Issue by fightingbamboo** [yiisoft/yii2#12566]
### What steps will reproduce the problem?
in old code, if $c === null, will return yii\base\Instance object. it is wrong.
### What do you get instead?
```php
@@ -428,7 +428,7 @@ class Container extends Component
                     $dependencies[] = $param->getDefaultValue();
                 } else {
                     $c = $param->getClass();
-                    $dependencies[] = Instance::of($c === null ? null : $c->getName());
+                    $dependencies[] = $c === null ? [] : Instance::of( $c->getName());
                 }
             }
         }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version          | 2.0.10
| PHP version       |5.6 
| Operating system |mac

**Comment by SilverFire** [comment]
Could you explain the problem you are trying to fix?

**Comment by fightingbamboo** [comment]
I fixed.
```php
@@ -428,7 +428,7 @@ class Container extends Component
                     $dependencies[] = $param->getDefaultValue();
                 } else {
                     $c = $param->getClass();
-                    $dependencies[] = Instance::of($c === null ? null : $c->getName());
+                    $dependencies[] = $c === null ? [] : Instance::of( $c->getName());
                 }
             }
         }
```
in old code, if $c === null, will return yii\base\Instance object. it is wrong.

**Comment by mdmunir** [comment]
> in old code, if $c === null, will return yii\base\Instance object. it is wrong.

Why you think this is wrong. How to reproduce in the real code?
https://github.com/yiisoft/yii2/blob/master/tests/framework/di/ContainerTest.php
What test are missing?

**Comment by cebe** [comment]
returning an array if no class is specified is not correct. Current code is okay.

**Comment by fightingbamboo** [comment]
Instance::of(null) is ok??

**Comment by cebe** [comment]
it will result in exception here: https://github.com/yiisoft/yii2/blob/e327d018b436b823d2e430f83a80e1ab1b9e92e3/framework/di/Container.php#L458 but that is expected as far as I see.

Please show the code you are running, that fails. Otherwise we can not help you.

**Comment by fightingbamboo** [comment]
I wrote a project,extension of yii 2. url: https://github.com/fightingbamboo/cyii2.
when run   ./vendor/bin/phpunit --group=di;
if do not change the code, too many errors.
