### ISSUE TITLE
Create index if columns - expression

### ISSUE THREAD

**Issue by TheSaturn** [yiisoft/yii2#12567]
### What steps will reproduce the problem?
In migration try to create index on two columns with ordering
        $this->createIndex('idx_id_create_at', 'file', '(created_at DESC, id DESC)', true);
### What is the expected result?
Wrapped rightly index
### What do you get instead?
SQL error  

### Additional info
As you can see
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L534
$column parametr always will be wrapped with brackets, but in this file
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L967
function have condition -  
```
if (strpos($columns, '(') !== false) {
                return $columns;
```
I think this condition was made specifically for my case - custom index expression. But it will never work due to double brackets. 
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
PostgreSQL 9.5

**Comment by SilverFire** [comment]
The following should work as expected:

```php
$this->createIndex('idx_id_create_at', 'file', [new Expression('created_at DESC'), new Expression('id DESC')], true);
```
