### ISSUE TITLE
View problem on JS and CSS file registration

### ISSUE THREAD

**Issue by rad8329** [yiisoft/yii2#12574]
Hello,

I have some AssetBundle classes with baseUrl and basePath different from the common `@web` and `@webroot`. It helps  me to shared some resources between backend-frontend (both instances are in the same domain http://exmaple.com/ and  http://exmaple.com/backend/), my baseUrl is `@cdnweb` which is defined `Yii::setAlias('cdnweb', '/mlm/pubroot/cdn');`

Before those  [changes](https://github.com/yiisoft/yii2/commit/fd6dd73cec3e7a35855c9d088f839581a9e09ace#commitcomment-19091647) my url paths looks like:

/mlm/pubroot/cdn/global/css/bootstrap-extend.css?v=1467914844

After:
/mlm/pubroot/backend/mlm/pubroot/cdn/global/css/bootstrap-extend.css?v=1467914844

I consider that if the $bundle object is necessary to have baseUrl property defined as  `@web`, this must be injected.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | PHP 7.0.8
| Operating system | Linux C001 4.4.0-38-generic #57-Ubuntu

**Comment by SilverFire** [comment]
How do you register your assets?

**Comment by rad8329** [comment]
In the main layout `$bundle = DashboardAsset::register($this);`

**Comment by SilverFire** [comment]
And what's inside you `DashboardAsset`?

**Comment by rad8329** [comment]
DashboardAsset.php
```
<?php

namespace common\assets;

class DashboardAsset extends BaseAsset
{
    public function init()
    {
        parent::init();
    }
}

```

```
<?php

namespace common\assets;

use yii\web\View;

class BaseAsset extends \yii\web\AssetBundle
{
    public $basePath = '@cdn';
    public $baseUrl = '@cdnweb';

    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'yii\validators\ValidationAsset',
        'yii\widgets\ActiveFormAsset',
    ];
    public $jsOptions = ['position' => View::POS_END];

    public function init()
    {
        parent::init();

        $this->js = [
            'global/vendor/animsition/animsition.js',
            'global/vendor/asscroll/jquery-asScroll.js',
            'global/vendor/mousewheel/jquery.mousewheel.js',
            'global/vendor/asscrollable/jquery.asScrollable.all.js',
            'global/vendor/ashoverscroll/jquery-asHoverScroll.js',
            'global/vendor/switchery/switchery.min.js',
            'global/vendor/intro-js/intro.js',
            'global/vendor/screenfull/screenfull.js',
            'global/vendor/slidepanel/jquery-slidePanel.js',
            'global/vendor/jquery-placeholder/jquery.placeholder.js',
            'global/vendor/alertify-js/alertify.js',
            'global/js/core.js',
            'base/assets/js/site.js',
            'app/js/mlm.js',
            'base/assets/js/sections/menu.js',
            'base/assets/js/sections/menubar.js',
            'base/assets/js/sections/gridmenu.js',
            'base/assets/js/sections/sidebar.js',
            'global/js/configs/config-colors.js',
            'base/assets/js/configs/config-tour.js',
            'global/js/components/asscrollable.js',
            'global/js/components/animsition.js',
            'global/js/components/slidepanel.js',
            'global/js/components/switchery.js',
            'global/js/components/jquery-placeholder.js',
            'global/vendor/select2/select2.js',
            'global/vendor/bootstrap-select/bootstrap-select.js',
            'global/vendor/webui-popover/jquery.webui-popover.js',
            'global/vendor/jquery-strength/jquery-strength.js',
            'app/js/bootstrap-filestyle.js',
            'global/vendor/jquery-strength/jquery-strength.js',
            'global/vendor/bootstrap-datepicker/bootstrap-datepicker.js',
            'global/vendor/slidepanel/jquery-slidePanel.js',
            'base/assets/js/app.js',
        ];

        $this->css = [
            'base/assets/css/site.css',
            'global/vendor/alertify-js/alertify.css',
            'global/vendor/select2/select2.css',
            'global/vendor/bootstrap-select/bootstrap-select.css',
            'global/vendor/webui-popover/webui-popover.css',
            'base/assets/examples/css/pages/profile.css',
            'global/vendor/jquery-strength/jquery-strength.css',
            'global/vendor/bootstrap-datepicker/bootstrap-datepicker.css',
            'app/css/guest-v2.css',
            'global/vendor/asscrollable/asScrollable.css',
            'global/vendor/switchery/switchery.css',
            'global/vendor/intro-js/introjs.css',
            'global/vendor/slidepanel/slidePanel.css',
            'base/assets/examples/css/pages/errors.css',
            'global/fonts/glyphicons/glyphicons.css',
            'global/vendor/flag-icon-css/flag-icon.css',
            'global/fonts/ionicons/ionicons.css',
            'global/fonts/web-icons/web-icons.css',
            'global/fonts/brand-icons/brand-icons.css',
            'global/fonts/font-awesome/font-awesome.css',
            'global/fonts/octicons/octicons.css',
            'global/fonts/themify/themify.css',
        ];
    }
}
```

In the common boostrap-local.php 

```
<?php

Yii::setAlias('cdn', realpath(dirname(dirname(__DIR__)).'/../../pubroot/cdn'));
Yii::setAlias('cdnweb', '/mlm/pubroot/cdn');
```
And my pubroot looks like:

![captura de pantalla de 2016-09-20 13-46-29](https://cloud.githubusercontent.com/assets/5356143/18684310/5d96d3ce-7f39-11e6-96d5-8598684e2fc3.png)

**Comment by dynasource** [comment]
Im having the same problem.
The issue starts after commit 3a215d0a007790fc8332ff5607607baeb0d8c89b which doesnt seem to connected to a issue.

Perhabs an idea to revert this commit and create a new issue for this?

**Comment by SilverFire** [comment]
@rad8329 failed to reproduce. After the `BaseAsset` registration I get URLs like these:

```html
<script src="/mlm/pubroot/cdn/global/vendor/animsition/animsition.js"></script>
<script src="/mlm/pubroot/cdn/base/assets/js/site.js"></script>
<script src="/mlm/pubroot/cdn/app/js/mlm.js"></script>
<script src="/mlm/pubroot/cdn/base/assets/js/sections/menu.js"></script>
<script src="/mlm/pubroot/cdn/global/js/configs/config-colors.js"></script>
```

Btw, `/global/css/bootstrap-extend.css` does not belong `BaseAsset` you've posted. Could you check again where from does this CSS file registration come?

**Comment by SilverFire** [comment]
@dynasource Please, provide the code and actual/expected result. Thank you

**Comment by rad8329** [comment]
Clarified:

My directory structure is substantially different from the Yii2 advanced template, because some company policies.

MAIN DIRECTORY STRUCTURE
-------------------

```
app/core
        api/
        backend/
        common/        
        console/     
        frontend/
app/environments/ 
app/tests/
app/vendor/
pubroot
    api/
        index.php               api instance
        index-test.php
    backend/
        media
            assets/
        index.php               backend instance
        index-test.php
    cdn/
    media
        assets/
    index.php                   frontend instance
    index-test.php              
runtime
    api/
    backend/
    console/
    frontend/
```

At frontend instance no problem, all url paths are 0k, the issue is at backend instance.

Actual:
```html
<script src="/mlm/pubroot/backend/mlm/pubroot/cdn/global/vendor/animsition/animsition.js?v=1467914844"></script>
```
Expected:

```html
<script src="/mlm/pubroot/cdn/global/vendor/animsition/animsition.js?v=1467914844"></script>
```

**Comment by SilverFire** [comment]
Still no luck to reproduce :( 

Could you try to collect minimum required code to reproduce the issue on basic or advanced application template?

**Comment by rad8329** [comment]
Of course, I'll do a repository with the advanced application template, and I'll do some changes to reproduce it, just like my template

**Comment by SilverFire** [comment]
Thank you, waiting for your reply

**Comment by dynasource** [comment]
I have a custum basePath for all my assets on a ramdisk for speed (especially for testing). My asset urls before were like this for my app located at (http://localhost/dmn/lw/5/dev/frontend/web):
* http://localhost/tmp/lw_5_dev/1e26dfb2/css/select2-bootstrap3.css

Now these are changed to path including my app basePath (which is incorrect). Also, a suffix is added, which is wrong. So 2 sideeffects.
* http://localhost/dmn/lw/5/dev/frontend/web/tmp/lw_5_dev/1e26dfb2/css/select2-bootstrap3.css/

**Comment by SilverFire** [comment]
The changes are reverted 3ec3ce931216a44ec0b850c429c9d8c7f9a17e6d

Thank you for reporting. Please, check current behavior and report whether all works as before.

**Comment by dynasource** [comment]
I can confirm it works again. Thx!

**Comment by rad8329** [comment]
Thanks.

I've arrived too late, but the template is ready  [https://github.com/rad8329/yii2-app-advanced](https://github.com/rad8329/yii2-app-advanced)
