### ISSUE TITLE
Workaround for ONLY_FULL_GROUP_BY config in MySQL 5.7

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#12571]
MySQL 5.7 enabled `ONLY_FULL_GROUP_BY` by default. This causes some generated ActiveQuery queries to throw an error.
A workaround could be to add `ANY_VALUE()` around the select elements.

More information can be found here: http://www.tocker.ca/2014/01/24/proposal-to-enable-sql-mode-only-full-group-by-by-default.html

**Comment by cebe** [comment]
> This causes some generated ActiveQuery queries to throw an error.

which queries exactly? As far as I see there are no such queries in yii itself so that would be an issue of your application, which you have to fix.

**Comment by michaelarnauts** [comment]
Never mind, it seems that it was a ActiveQuery with custom sql statements.

**Comment by SamiUrias** [comment]
Using ANY_VALUE() works for me :)
