### ISSUE TITLE
Update dependency version for HTMLPurifier?

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#12572]
`HTMLPurififier` is now on 4.8.0, current dependent version is 4.6.0 from 2013-11-30

**Comment by samdark** [comment]
No, it's not. `~4.6` means any 4.x version more or equal than 4.6 but not 5.0.

**Comment by samdark** [comment]
So it should install 4.8.

**Comment by Alex-Code** [comment]
My bad, my `composer.json` was missing the tilde character `~`, thought it was being locked by Yii's.
