### ISSUE TITLE
Trying to delete the module a second time causes Exception with no error message

### ISSUE THREAD

**Issue by winternet-studio** [yiisoft/yii2#12582]
### What steps will reproduce the problem?
Inadvertently I tried to delete a model twice in a row. Of course the second time fails, but there is no error message explaining why it fails! Code for reproduction:

```
$model = Customer::findOne(44);
if (!$model->delete()) {
	throw new \Exception('First delete attempt failed '. json_encode($model->getErrors()));
}
if (!$model->delete()) {
	throw new \Exception('Second delete attempt failed. '. json_encode($model->getErrors()));
}
```

### What is the expected result?

$model->getErrors() should have returned an error message saying something like "The database record does not exist" or even better "The database record has already been deleted".

### What do you get instead?

I get the exception message: `Second delete attempt failed. []`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.2
| Operating system | Windows 10 64-bit

**Comment by cebe** [comment]
> $model->getErrors()

this is for validation of user input only, it is not related to any other operations on the model.

The failure of the deletion is reported by the database in form of rows affected by the DELETE operation. There is not more information than success or failure so it is not possible to provide a message with more details.

**Comment by winternet-studio** [comment]
Ohh, thanks for the clarification. Isn't there a way that I as a developer can get to the MySQL error message somehow? That is pretty important in debugging...

**Comment by cebe** [comment]
There is no MySQL error message, there are just 0 rows affected by the DELETE query.
