### ISSUE TITLE
Migrations: Extended integer types

### ISSUE THREAD

**Issue by GT-Volk** [yiisoft/yii2#12581]
Hello!
I would like to expand a little in the choice of type integer migrations.
Also available **smallInteger**, **integer** and **bigInteger** would be great to add also such **tyniIntege** and **mediumInteger**

____________________________________________________
Доброго времени суток!
Хотелось бы немного расширить выбор типа integer в миграциях. 
Кроме имеющихся **smallInteger**, **integer** и **bigInteger** было бы здорово добавить еще и например **tyniInteger** и **mediumInteger**

**Comment by SilverFire** [comment]
These types are MySQL specific and are not supported by the majority of the DBMS supported by Yii, so we'd prefer to avoid adding them, sorry
