### ISSUE TITLE
Performance improvement AccessControl

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#12592]
Already talked with @samdark about this. There is an performance improvement opportunity for yii applications with many rules. My local performance xdebug profiler shows an average of 1,5% better performance for yii apps using \yii\filters\AccessControl

Within the current situation, AccessControl loads all rules in init(). I dont see a reason for this behavior.
See: https://github.com/yiisoft/yii2/blob/master/framework/filters/AccessControl.php#L99
BeforeAction seems to be the only one using these rules and it quits after hitting the first matching rule.
So therefore it would be more logical to setup a rule when its used.

**Comment by samdark** [comment]
Could it be done w/o breaking backwards compatibility?

**Comment by dynasource** [comment]
it could for those depending on rules to be already set a init(), but I dont think that is a common usecase. The solution is quite straightforward.

**Comment by samdark** [comment]
OK. How about a pull request?

**Comment by githubjeka** [comment]
Can be closed & need to adjust Milestone
