### ISSUE TITLE
Add findOneOrFail method to activerecord

### ISSUE THREAD

**Issue by amin0256** [yiisoft/yii2#12595]
please add a method to active record that is "findOneOrFail".
When active record can't find any model throw a notFoundHttpException.
sorry for my bad language.
thanks.

**Comment by samdark** [comment]
I don't think it should be added to AR since AR should not be aware of context in which it's used. Especially about HTTP. What if it's used, for example, in console application?

**Comment by amin0256** [comment]
But this is a popular method in eloquent of laravel and save time! every time i use method find of AR, after that i have to respect maybe model not found !

**Comment by Thoulah** [comment]
You can add something simple like this in your controller:
```php
if ($result === null)
	throw new \yii\web\NotFoundHttpException('No result.');
```

Or you can extent AR and add a function.

**Comment by cebe** [comment]
Gii generates such a method for your controller in a CRUD by default: https://github.com/yiisoft/yii2-gii/blob/a5136efe5495dd1e941615e5c4a4ed09c44af194/generators/crud/default/controller.php#L157
