### ISSUE TITLE
Microsoft SQL Server error with 'yii\web\DbSession'

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#12599]
### What steps will reproduce the problem?

Create table `session` using migration:

```
        $this->createTable('{{%session}}', [
            'id' => $this->string()->notNull(),
            'expire' => $this->integer(),
            'data' => $this->binary(),
            'PRIMARY KEY ([[id]])',
        ]);
```

Configure session handler:

```
        'session'      => [
            'class'        => 'yii\web\DbSession',
            'sessionTable' => '{{%session}}',
        ]
```

Run web application.
### What is the expected result?

No error
### What do you get instead?

Session data are not written into database because of error:

```
Exception (Database Exception) 'yii\db\Exception' with message 
'SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Implicit conversion from data type nvarchar to binary is not allowed. Use the CONVERT function to run this query.
The SQL being executed was: 
INSERT INTO [session] ([data], [id], [expire]) VALUES ('__flash|a:0:{}dummy|s:5:"12345";', '9ds6jo8mg1j2dctk8ifip3mbd7', 1474802513)' 
```

Error is repeated with `session.serialize_handler` value set to `php_serialize`, `php` and `php_binary`.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.5.16 |
| Operating system | Windows Server 2012 R2 Standard Edition |

**pdo_sqlsrv**

```
Microsoft SQL Server 2012 (SP1) - 11.0.3156.0 (X64) 
    May  4 2015 18:48:09 
    Copyright (c) Microsoft Corporation
    Standard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)
```

**Comment by SDKiller** [comment]
UPD:
running sql from https://github.com/yiisoft/yii2/blob/master/framework/web/migrations/schema-mssql.sql produces error:

```
Error: SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Column, parameter, or variable #3: Cannot find data type BLOB.
```

**Comment by SilverFire** [comment]
Could you check now, please?

**Comment by SDKiller** [comment]
Should not be `varbinnary(max)` with single `n` ?

**Comment by SilverFire** [comment]
It must. Updated

**Comment by SDKiller** [comment]
Still get 

`
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query. The SQL being executed was: INSERT INTO [session2] ([data], [id], [expire]) VALUES ('__flash|a:0:{}', 'trbq50v3h7fcder9pf0749e8u7', 1474890125)'
`

**Comment by samdark** [comment]
Reproduced.

**Comment by samdark** [comment]
Seems LOBs aren't supported by MSSQL official PDO driver: http://sqlsrvphp.codeplex.com/SourceControl/latest#pdo_sqlsrv/pdo_stmt.cpp see `//TODO` :(

**Comment by samdark** [comment]
https://github.com/Microsoft/msphpsql/issues/140

**Comment by samdark** [comment]
The solution is to cast explicitly `CONVERT(VARBINARY, :p1)` everywhere where value is bound.

**Comment by samdark** [comment]
@SDKiller would you please check if it works for you if you have some time?

**Comment by SDKiller** [comment]
@samdark 

Error on calling `Yii::$app->session->set()` is gone. 

But now there is a problem with getting values form session with `get()`. 
Data is empty - but `data` column is not empty.

Maybe it is a separate issue with session handler on windows server and converting data back from binary type?

Switched back to session table with `text` type for `data` column - at least it was working.

**Comment by samdark** [comment]
Should be separate thing. What I've fixed is about MSSQL PDO not working with `varbinary(max)`.

**Comment by njasm** [comment]
PHP 7.1.0
Yii 2.0.12
SQL Server 2017
DbSession

having problems decoding session from DbSession on MS SQL with [data] column as VARBINARY(MAX).
session decode is Failing. changed the datatype to nvarchar(max) seems to be working..

**Comment by cebe** [comment]
@njasm please open a new issue. This one is already assigned to a closed milestone.
