### ISSUE TITLE
`composer require yiisoft/yii2` 太难过

### ISSUE THREAD

**Issue by genyii** [yiisoft/yii2#12597]
Yii2很好，我用Yii也两三年了，但现在的Yii2安装一直是个痛点，每次安装或者新引入一个包都死慢，很不爽bower-asset这么搞，我知道后面的版本会分离，只求能尽快把composer和bower分开。laravel每次安装都是很快的

**Comment by Maslow** [comment]
Agree!
You can try the composer mirror of China at http://www.phpcomposer.com/

**Comment by genyii** [comment]
@Maslow Thanks,but it's not work. the problem is `composer-asset-plugin`, it costs a lot of time.

**Comment by lichunqiang** [comment]
Pls use english to explain your issue/.

**Comment by genyii** [comment]
Can I install yii2 or require a new yii2 extension without composer-asset-plugin? 
------------------ Original ------------------

**Comment by SilverFire** [comment]
> Can I install yii2 or require a new yii2 extension without composer-asset-plugin?

Yes, you can. Check out https://asset-packagist.org/, or read https://github.com/yiisoft/yii2/issues/8688 to know more.
