### ISSUE TITLE
cant see my post paramters

### ISSUE THREAD

**Issue by mhadad** [yiisoft/yii2#12596]
I keep installing a new app on my vps and I just cant receive any post parameters. 
Whether I use $_POST or $request = Yii::$app->request;...Its just empty and no errors are shown.

I'm running the app on php 5.6 and the requirements page shows a pass for all...Apache httpd on Unix

**Comment by devmustafa** [comment]
Are you using the restful api?

**Comment by Razzwan** [comment]
Try this: `Yii::$app->request->bodyParams`
