### ISSUE TITLE
Call to a member function getRequest() on a non-object in XXX/vendor/yiisoft/yii2/log/Target.php

### ISSUE THREAD

**Issue by senguttuvang** [yiisoft/yii2#12603]
### What steps will reproduce the problem?
php vendor/bin/codecept run unit --steps --xml --coverage --coverage-xml --coverage-html -c tests/codeception/frontend

### What is the expected result?
Expecting it to run without PHP exception

### What do you get instead?
PHP Exception encountered

Stack trace:

`PHP Fatal error: Call to undefined method stdClass::getRequest() in /src/vendor/yiisoft/yii2/log/Target.php on line 293 PHP Stack trace: PHP 1. {main}() src/vendor/codeception/codeception/codecept:33 PHP 3. Symfony\Component\Console\Application->run() src/Codeception/Application.php:103 PHP 4. yii\log\Logger->flush() src/vendor/yiisoft/yii2/log/Logger.php:173 PHP 6. yii\log\Dispatcher->dispatch() src/vendor/yiisoft/yii2/log/Dispatcher.php:188 PHP 8. yii\log\FileTarget->export() src/vendor/yiisoft/yii2/log/FileTarget.php:106 PHP 10. yii\log\Target->formatMessage() src/vendor/yiisoft/yii2/log/Target.php:270`

Related:
https://github.com/yiisoft/yii2-debug/issues/111
https://github.com/yiisoft/yii2/issues/11667
https://github.com/yiisoft/yii2/issues/6803
https://github.com/yiisoft/yii2/pull/6739

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | PHP 5.6
| Operating system | Ubuntu 14.04

**Comment by githubjeka** [comment]
I can't reproduce... what is cause of the problem?

**Comment by senguttuvang** [comment]
When you run codeception unit tests with any Log component enabled, it throws this exception after the test execution.

**Comment by githubjeka** [comment]
![image](https://cloud.githubusercontent.com/assets/874234/19143202/e8a191b6-8baa-11e6-9b46-f8f97458ee8d.png)

**Comment by senguttuvang** [comment]
When I had FileTarget, I too didn't get the issue. I'm facing this issue only when using [Bugsnag](https://github.com/pinfirestudios/yii2-bugsnag) plugin. May be, it's because of the plugin issue and nothing to do with core framework?

```php
 'log' => [
            'traceLevel' => 8,
            'targets' => [
                [
                    'class' => 'pinfirestudios\yii2bugsnag\BugsnagLogTarget',
                    'levels' => ['error', 'warning', 'info', 'trace'],
                    'logVars' => [],
                ]
            ],
        ],
```

**Comment by samdark** [comment]
Yes https://github.com/pinfirestudios/yii2-bugsnag/blob/master/src/BugsnagLogTarget.php#L35

**Comment by samdark** [comment]
@githubjeka thanks for checking it.
