### ISSUE TITLE
Validator whenClient should also accept a PHP callback

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#12600]
With `Validator::when` you receive the currently validated `$model`, so you can make the validation depend on model values.

But with `whenClient` you can only specify a fixed string with a js validation function. So currently it's not possible to create a dynamic client validation function that depends on a model property. I suggest to make 'whenClient' either a string or a PHP callback which returns a string with the js validation function.

Here's an example how this could be used to create dynamic js:

```
'whenClient' => function ($model, $attribute) {
    return 'function (attribute, value) {'.
        ($model->status==='open' ? 'return true;' : 'return value=="foo"').
        '}';
},
```

**Comment by SilverFire** [comment]
It is possible to generate client validation function with code like this:

```php
'whenClient' => $this->clientStatusValidation()
...
private function clientStatusValidation()
{
    return 'function (attribute, value) { ... }'
}
```

Closure will make the thing easier, but it's a BC breaking change and I doubt about it's necessity.

**Comment by cebe** [comment]
The model passed to the closure does not have any difference compared to just using `$this` when defining rules in this case. If the attribute can change, that must be reflected in JS code, if it can not change in the current form you can access the current value using `$this`. I do not see why allowing a closure here is necessary.

**Comment by mikehaertl** [comment]
>The model passed to the closure does not have any difference compared to just using $this

Hmmm, you're probably right. I first thought, it's the same situation as in `when`. There we can't use `$this` as the submitted attributes are not assigned yet. But that makes no sense when talking about client validation.

I just wasn't sure, if `rules()` isn't called on a "naked" instance (`new MyModel`). If you can confirm that this is not the case, and we always get the current model instance in `$this` then I agree that this change here is not neccessary.

**Comment by mikehaertl** [comment]
I've tested with `$this` in my use case and it seems to work as expected. So feel free to close this unless you still see a case where `$this` would not work.
