### ISSUE TITLE
ActiveRecord tries to 'get' write-only properties marked as 'safe' when validating

### ISSUE THREAD

**Issue by arthibald** [yiisoft/yii2#12605]
I wish to massively assign a write-only property, for example password:

    // In ActiveRecord extension
    ...

    public function rules(){
        return [...
            [['password'],'safe']
        ...]
    }

    public function setPassword($password){
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    ... no getter ...

When validating I get `Exception: Getting write-only property`. It appears that the validation function is attempting to retrieve the attribute `password` unnecessarily, perhaps even creating a superfluous Validator.

**Comment by SilverFire** [comment]
It's not a bug. Attribute getting is required for validation (see [Validator::validateAttributes():251](https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L251)

You can implement null-returning getter, if you do not want to expose password after it was set.

**Comment by arthibald** [comment]
Well, I could add a null-returning getter.. but that isn't really appropriate, doesn't really make sense and has an effect on other areas of the code. I'd much rather the AR kept throwing the exception if an attempt is made to access the attribute.

'Attribute getting is required for validation', isn't really an answer. Safe attributes don't need to be validated or ever retrieved. I think this a product of the design decision to use an extra special 'validator' to mark an attribute safe or unsafe for massive assignment. 

I suppose I can always overwrite the `safeAttributes()` function to something more flexible....

**Comment by SilverFire** [comment]
> I think this a product of the design decision to use an extra special 'validator' to mark an attribute safe or unsafe for massive assignment.

Yes, you're right.

**Comment by cebe** [comment]
You can define scenarios() manually, `safe` is a helper to allow defining rules without the need to define `scenarios()`.

**Comment by arthibald** [comment]
@SilverFire Still trying to understand why this was closed..

I've managed to fix the issue by overriding the, as far as I can tell, unnecessary `validateAtrributes()` function in my own SafeValidator extension:

    namespace common\components;
    
    class SafeValidator extends \yii\validators\SafeValidator{
      public function validateAttributes($model, $attributes = null)
      {
      }
    }

And including it it in my bootstrap:

    Yii::$container->set('yii\validators\SafeValidator', 'common\components\SafeValidator');

Note that `validateAttribute()` singular is already overridden in a similar way in `yii\validators\SafeValidator`.

Any reason why this wasn't done already? Or was it just missed?

**Comment by arthibald** [comment]
@cebe Before tweaking SafeValidator, I found it made more sense to work-around this issue by overriding `safeAttributes()` in my ActiveRecord extension, rather than overriding `scenarios()`:

    public function safeAttributes()
    {
      $safeAttributes = parent::safeAttributes();
      $safeAttributes[] = 'password';
      return $safeAttributes;
    }

One could of course add various scenario checks in here if necessary. 

I almost prefer using this method over creating an extra validator (which isn't really a validator) to mark a safe attribute.

**Comment by cebe** [comment]
Okay, I see that overriding validateAttribute**s**() would work.

But your concept of storing password like this does not allow validating password constraints e.g. minimum length. A normal validator needs a getter to validate the attribute.

**Comment by arthibald** [comment]
@cebe Yep I agree, I will add them in future. The fix still stands though and thanks! :)
