### ISSUE TITLE
Automatically generated labels and i18n?

### ISSUE THREAD

**Issue by cyphix333** [yiisoft/yii2#12606]
Just wondering when you're using ActiveField and Yii automatically generates the labels for the field, how does this work when you need to use i8n? I assume if you want to use i18n you will need to make your own labels by passing it in in translated form?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.5.28
| Operating system | Windows 7 / CentOS

**Comment by samdark** [comment]
Yes.
