### ISSUE TITLE
The length field in `yii\db\SchemaBuilderTrait::binary()` is being ignored for mysql.

### ISSUE THREAD

**Issue by kanyuga** [yiisoft/yii2#12618]
### What steps will reproduce the problem?

Trying to create a `LONGBLOB` field via 

    $this->db->createCommand()->createTable("test_blob", [
        "id" 	=> $this->integer(),
        "datum" => $this->binary(4294967295), // LONGBLOB
        "txt" 	=> $this->string()
    ])->getSql();

### What is the expected result?
    CREATE TABLE `test_blob` (
    	`id` int(11),
    	`datum` blob(4294967295),
    	`txt` varchar(255)
    );
### What do you get instead?
    CREATE TABLE `test_blob` (
    	`id` int(11),
    	`datum` blob,
    	`txt` varchar(255)
    );

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.9
| Operating system | Ubuntu 16.04
| Source | http://stackoverflow.com/questions/39721423/yii2-create-migration-with-longblob-field

**Comment by cebe** [comment]
you are using the DB independent syntax, which is limited like this. If you want to create a MySQL specific column, you can use MySQL specific syntax: 

```php
    "datum" =>'LONGBLOB',
```

**Comment by kanyuga** [comment]
Shouldn't the `binary` function not take in a length then?

**Comment by cebe** [comment]
MySQL BLOB does not take a length so we can not translate the specification of a length to mysql syntax.
