### ISSUE TITLE
Update Action of ActiveController is not working when used with "common\models\User" class.

### ISSUE THREAD

**Issue by mfuzailzubari** [yiisoft/yii2#12616]
### What steps will reproduce the problem?

Make a REST API using "common\models\User" class.
### What is the expected result?

The user object should update its at least one attribute on PUT/PATCH request.
### What do you get instead?

No Update of any column at all.
### Additional info

When ever I try to update the user object and initiates a PUT/PATCH request the user attributes doesn't get updated. 

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 7.0.11 |
| Operating system | Ubuntu 16.04 LTS |

**Comment by fernandezekiel** [comment]
what content-type are you using? there are content-types that cannot work with PUT/PATCH but will work with POST... i think this is somehow addressed already
