### ISSUE TITLE
Yii2 URL Management - issue in passing key-value pairs in URL

### ISSUE THREAD

**Issue by bhuwanmohan** [yiisoft/yii2#12617]
I am upgrading my website from Yii 1.1 to Yii2. In the older site using Yii 1.1, the url can be given as 

`http://example.com/index.php/controller_name/action_name/queryString/123`

But in Yii2 I have to change this request to 

    http://example.com/index.php/controller_name/action_name?queryString=123

in order to make it work, otherwise I get a **404 Not Found** error.

I already know that this feature has been removed in Yii2 [Github issue 6866][1], but since the older site heavily uses this particular feature, I would like to know if there is any workaround, without changing each individual URL in the existing website.

Also asked on Stackoverflow [Yii2 URL Management - issue in passing key-value pairs in URL][2]

Thanks

  [1]: https://github.com/yiisoft/yii2/issues/6866
[2]: http://stackoverflow.com/questions/39723340/yii2-url-management-issue-in-passing-key-value-pairs-in-url

**Comment by cebe** [comment]
see http://stackoverflow.com/questions/39723340/yii2-url-management-issue-in-passing-key-value-pairs-in-url#comment66744532_39723340
