### ISSUE TITLE
catch Throwable in ErrorHandler::handleException

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#12619]
If there's an exception during the rendering of the error page, ErrorHandler will catch it and display a simple message: https://github.com/yiisoft/yii2/blob/2.0.9/framework/base/ErrorHandler.php#L117

This should catch `Throwable` in PHP 7 as well.

**Comment by cebe** [comment]
There are many other places where `\Throwable` could be relevant:

- [ ] guide should explain it when catching things for transactions: https://github.com/yiisoft/yii2/blob/master/docs/guide/db-dao.md#performing-transactions-
- [ ] https://github.com/yiisoft/yii2/blob/e23a4197327f7c387a41751d3ada6a1974414c68/framework/base/Widget.php#L103
- [ ] https://github.com/yiisoft/yii2/blob/e23a4197327f7c387a41751d3ada6a1974414c68/framework/caching/DbCache.php#L225
- ... (search for `catch (\Exception` in yii code base) ...
