### ISSUE TITLE
denyCallback in yii\filters\AccessRule is not working as expected

### ISSUE THREAD

**Issue by Renkas** [yiisoft/yii2#12626]
### What steps will reproduce the problem?

My rule definition

```
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                        'denyCallback' => function($rule, $action) {
                            return Yii::$app->response->redirect(['user/edit-plan']);
                        }
                    ]
```
### What is the expected result?

I expect that for logged in users the `denyCallback` would be executed.
### What do you get instead?

I get generic HTTP 403 Forbidden error page
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.10-dev |
| PHP version |  |
| Operating system |  |

**Comment by Alex-Code** [comment]
Not sure if this is a bug or something that should be documented but the `denyCallback` for an `AccessRule` will only be called if `allow` is `false` and the rule denies.

This should work for you.
```php
[
  'actions' => ['signup'],
  'allow' => false,
  'roles' => ['@'],
  'denyCallback' => function() {
    return \Yii::$app->response->redirect(['user/edit-plan']);
  }
],
```

**Comment by samdark** [comment]
@Alex-Code is correct.

**Comment by Renkas** [comment]
@Alex-Code 's solution works.

But it's still not the behaviour I would expect from this. And I did not find the documentation to be helpful on this. If you don't want to change the behaviour then maybe try to document it better?
