### ISSUE TITLE
A custom input widget won't be validated if you change the ID

### ISSUE THREAD

**Issue by coderlex** [yiisoft/yii2#12629]
Validation of custom widget will not happen if you change it's auto-generated id.
But all works fine when changing the id of 'standard' inputs.

This happens because all input-setting methods (like `ActiveField::textInput()` or `ActiveField::checkboxList()`) call the protected `ActiveField::adjustLabelFor()` function which sets the internal `$_inputId` variable eigther. But the `ActiveField::widget()` method doesn't do this (BTW it also causes incorrect label's `for` value).

I suppose the issue can be solved by adding call of `adjustLabelFor()` in `widget()` method.

Now I'm using the following weird-looking workaround:
```php
echo $form->field($tag, 'category_id')
	// A hack to set internal input id
	->textInput([
		'id' => $form->id . '-category_id'
	])
	->widget(\frontend\widgets\Dropdown::className(), [
		'items' => $categoryIdOptions,
		'prompt' => 'Select a category...',
		'blockOptions' => [
			'class' => 'remodal__dropdown'
		],
		'options' => [
			'id' => $form->id . '-category_id'
		]
	]);
```

**Comment by cebe** [comment]
can you send a pull request with your fix?
