### ISSUE TITLE
Proposal: Provide an interface for UploadedFile

### ISSUE THREAD

**Issue by sadovnik** [yiisoft/yii2#12620]
If client sends files in a way that PHP does not handle natively (via `$_FILES`) it would be a problem to validate them using `FileValidator`.

My case was uploading photos via JSON API. To send a photo, client encodes it with base64 and puts as a prop to the request body. There's two options how to handle this request. The first one is to do it manually and the second one is to make an ugly extension of `UploadedFile` to override `$_FILES`-specific methods.

Possible similar case is uploading photos by link.

I encourage everyone to share their experience and thoughts about this topic.

**Comment by TerraSkye** [comment]
It would solve my issues as well, ive done it the manual way

**Comment by Alex-Code** [comment]
Is this 3rd party JS or your own?
I had a similar need where I was modifying images client side that would be uploaded so used `ajax` and `FormData`. This will save the need for base64 encoding and allow the use of `$_FILES`.

**Comment by samdark** [comment]
I think it's a good idea.

**Comment by sadovnik** [comment]
@Alex-Code I also suggest to use `multipart/form-data` if possible. In my case it was not.

**Comment by Oxyaction** [comment]
Suggest to resolve this issue will be better to move the code responsible for file extraction from `UploadedFile` to other class that implements extraction strategy.

**Comment by SilverFire** [comment]
Related to https://github.com/yiisoft/yii2/issues/12016

**Comment by sadovnik** [comment]
@Oxyaction is it possible to make it without breaking BC?

**Comment by klimov-paul** [comment]
Resolved by #14801
