### ISSUE TITLE
AssetBundles include Assets twice

### ISSUE THREAD

**Issue by hiasl** [yiisoft/yii2#12624]
### What steps will reproduce the problem?
- I use grunt to combine/compress my JS/CSS. This includes jQuery, YiiAsset, ValidationAsset and ActiveFormAsset
- In order get my minifies js/css into the source code, I created my one and only "AppAsset" pointing to my minified files. It looks like this:

```
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'https://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700',
        'css/dist/project.min.css'
    ];
    public $js = [
        'js/dist/libs.min.js',
        'js/dist/project.min.js'
    ];
    public $depends = [];
}

```
- To avoid that Yii2 includes it own JS again for form validation, I added the following lines to my web.php, which "redirect" alls dependencies to the one AppAsset.

```
        'assetManager' => [ // below are all Yii assets, which are actually merged into the single JS file via Grunt
            'bundles' => [  
                'yii\web\JqueryAsset' => [
                    'sourcePath' => null,
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
                'yii\web\YiiAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
                'yii\validators\ValidationAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
                'yii\widgets\ActiveFormAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
            ],
        ],

```

### What is the expected result?

I expect to have 2 JS script tags (one for libs.min.js, one for project.min.js) and one for CSS (project.min.css). 

### What do you get instead?

This works for all pages except the ones which contain forms using ActiveForm and ClientSide Validation. Pages with form validation include the 2 JS Files at the end of the  twice (2 x libs, 2 x project) but only 1 x the css file (in the head).

The first 2 occurrence of the 2 JS files is before inline form validation JS Code, the second is in the common position.

The strange thing: So apparently Yii2 understands that instead of directly including jQuery and the other Assets it should include my single AppAsset. But it does not understand that it already did include them once before.

Any help / fix appreciated. Thanks.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.5.9-1ubuntu4.19
| Operating system | Ubuntu

**Comment by dynasource** [comment]
it would be helpful if you show a screenshot of your issue.

**Comment by hiasl** [comment]
Sure, here it is
![bildschirmfoto 2016-09-28 um 21 40 14](https://cloud.githubusercontent.com/assets/800026/18929431/bb3ecb8a-85c4-11e6-96cd-b033dbb91a41.png)

**Comment by mdmunir** [comment]
>  I added the following lines to my params.php

Not in `params.php`. But in `web.php` under `components` section.

**Comment by hiasl** [comment]
Sorry, my mistake in the ticket, I copied the src from web.php, not from params.php. Problem is still the same.

**Comment by Alex-Code** [comment]
Are you using `Pjax`?
Could you show your layout, seems a bit odd having `div` elements before and after the `script` tags.

**Comment by hiasl** [comment]
- No,  I'm not using PJAX. 
- The divs before and after are odd (and I also already fixed this), but it's not the issue. 
- The layout is also not relevant and I can not post the link at the moment, because it's still protected.
Anyway, the layout does not show a difference, but all JS Files are included twice and therefore also executed twice, which is especially nice for jQuery's toggle() :-)

**Comment by hiasl** [comment]
Here's the layout (short version). I found out that:

- `$content` contains both the JS tags and the JS validation code
- `<?php $this->endBody() ?>` again includes the JS tags


```
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?php echo Yii::$app->languageDetector->getCurrentLanguage(); ?>">
<head>
    <meta charset="<?php echo Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo Html::csrfMetaTags(); ?>
    <title><?php echo Html::encode($this->title); ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<main id="content">
    <div class="container">
        <div class="row">
            <?php echo $content; ?>
        </div>
    </div>
</main>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

```

**Comment by hiasl** [comment]
My rendered page now looks like this at its end:

```
<!-- END of content -->
<script src="/js/dist/libs.min.js"></script>
<script src="/js/dist/volksoper.min.js"></script>
<script type="text/javascript">jQuery(document).ready(function () {
jQuery('#w0').yiiActiveForm([{"id":"contactform-first","name":"first","container":".field-contactform-first","input":"#contactform-first","error":".help-block.help-block-error","validate":function (attribute, value, messages, deferred, $form) {yii.validation.required(value, messages, {"message":"Vorname darf nicht leer sein."});yii.validation.string(value, messages, {"message":"Vorname muss eine Zeichenkette sein.","max":25,"tooLong":"Vorname darf maximal 25 Zeichen enthalten.","skipOnEmpty":1});}},{"id":"contactform-last","name":"last","container":".field-contactform-last","input":"#contactform-last","error":".help-block.help-block-error","validate":function (attribute, value, messages, deferred, $form) {yii.validation.required(value, messages, {"message":"Nachname darf nicht leer sein."});yii.validation.string(value, messages, {"message":"Nachname muss eine Zeichenkette sein.","max":25,"tooLong":"Nachname darf maximal 25 Zeichen enthalten.","skipOnEmpty":1});}},{"id":"contactform-email","name":"email","container":".field-contactform-email","input":"#contactform-email","error":".help-block.help-block-error","validate":function (attribute, value, messages, deferred, $form) {yii.validation.required(value, messages, {"message":"E-Mail darf nicht leer sein."});yii.validation.email(value, messages, {"pattern":/^[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$/,"fullPattern":/^[^@]*<[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?>$/,"allowName":false,"message":"E-Mail ist keine gültige Emailadresse.","enableIDN":false,"skipOnEmpty":1});yii.validation.string(value, messages, {"message":"E-Mail muss eine Zeichenkette sein.","max":40,"tooLong":"E-Mail darf maximal 40 Zeichen enthalten.","skipOnEmpty":1});}},{"id":"contactform-tel","name":"tel","container":".field-contactform-tel","input":"#contactform-tel","error":".help-block.help-block-error","validate":function (attribute, value, messages, deferred, $form) {yii.validation.string(value, messages, {"message":"Telefonnummer muss eine Zeichenkette sein.","max":30,"tooLong":"Telefonnummer darf maximal 30 Zeichen enthalten.","skipOnEmpty":1});}},{"id":"contactform-nachricht","name":"nachricht","container":".field-contactform-nachricht","input":"#contactform-nachricht","error":".help-block.help-block-error","validate":function (attribute, value, messages, deferred, $form) {yii.validation.string(value, messages, {"message":"Nachricht muss eine Zeichenkette sein.","skipOnEmpty":1});}}], []);
});</script>        </div>
    </div>
</main>
<script src="/js/dist/libs.min.js"></script>
<script src="/js/dist/volksoper.min.js"></script></body>
</html>
```

**Comment by hiasl** [comment]
one more info: also Yii Debug Toolbar Code (if active) is added twice to the page, if a form is contained in the content (and therefore the validation code).

**Comment by Alex-Code** [comment]
What is generating `$content`? Do you have `$this->endBody();` in it.

**Comment by samdark** [comment]
Please provide your layout.php

**Comment by hiasl** [comment]
@samdark layout.php is above
@Alex-Code : you were right, I had a `{{ void(this.endBody()) }}` in it (using Twig). Thanks a lot for finding this! But when I remove it, I do not get the inline JS form validation code anymore. It does not get inserted in the position of `$this->endBody()` in my layout.

**Comment by dynasource** [comment]
good to hear. To conclude, assets were registered twice because of calling endBody() twice?

About the other issue, please open another yii issue if you dont seem to be able to find a solution.

**Comment by hiasl** [comment]
I don't know (and don't think) if they were registered twice, but they were output twice. This does not happen anymore. But I would like to keep this open to understand, why now the validation code is not output anymore in the single position at `$this->endBody()`. I also found out that if I remove this

```
        'assetManager' => [ // below are all Yii assets, which are actually merged into the single JS file via Grunt
            'bundles' => [  
                'yii\web\JqueryAsset' => [
                    'sourcePath' => null,
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
                'yii\web\YiiAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
                'yii\validators\ValidationAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
                'yii\widgets\ActiveFormAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'js' => [],
                    'depends' => ['app\assets\AppAsset']
                ],
            ],
        ],
```
from my web.php, the other js files still do not get included (which I would expect, but not if course not want).

So what is the logic? I suppose that any JS Code should be inserted right before the closing `</body>` tag, where `$this->endBody()` is called, right?

**Comment by dynasource** [comment]
In order to keep the issue tracker clean and intuitive, you should open another issue as you are facing another issue now.

**Comment by hiasl** [comment]
okey :-)

**Comment by hiasl** [comment]
then thanks a lot to everybody, it really helped me.
