### ISSUE TITLE
PHP Fatal Error – yii\base\ErrorException

### ISSUE THREAD

**Issue by shnwqshnwq** [yiisoft/yii2#12623]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.5
| Operating system | centos

Call to undefined function yii\base\fnmatch()

 in /path/to/vendor/yiisoft/yii2/base/ActionFilter.php

 protected function isActive($action)
    {
        $id = $this->getActionId($action);
 
        if (empty($this->only)) {
            $onlyMatch = true;
        } else {
            $onlyMatch = false;
            foreach ($this->only as $pattern) {
                if (fnmatch($pattern, $id)) {
                    $onlyMatch = true;
                    break;
                }
            }
        }

I get the message from php document for fnmatch function :

For now, this function is not available on non-POSIX compliant systems except Windows.

**Comment by cebe** [comment]
> centos

centos is not posix compliant? looks like its something wrong with your PHP setup.

See

- https://github.com/yiisoft/yii2/issues/12408#issuecomment-243721437
- http://unix.stackexchange.com/questions/305639/centos-6-7-and-fnmatch-in-php

**Comment by shnwqshnwq** [comment]
i suggest to change  fnmatch to an anonymous like this

            foreach ($this->only as $pattern) {
				if (instanceof of \Closure) {
					$onlyMatch = call_user_func($pattern, $id);
					if ($onlyMatch) {
						break;
					}
				} else if ($pattern == $id){
					$onlyMatch = true;
					break;
				}
            }
and i think fnmatch should be replaced by other functions as it probably can lead to some errors, what do you think?

**Comment by samdark** [comment]
Hmm... based on what's written following @cebe links, it seems standard CentOS is OK.

**Comment by cebe** [comment]
If you are able to compile PHP yourself you seem to have enough permisson to configure the server yourself.
