### ISSUE TITLE
dropTable + IF EXISTS; createTable + IF NOT EXISTS

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#12633]
I don't know is this the proper place for suggestions but anyway

I want to create Migration so there is a method

`$this->dropTable('table_name');`

but the statement i want to execute is 

`$this->execute("DROP TABLE IF EXISTS `table_name`");`

which works fine but It would be much cleaner if i **could** write

`$this->dropTable('table_name')->ifExists();`

or as a second parameter

`$this->dropTable('table_name', $exists = true )`

The same goes for creating a table with `if not exists` ...

**Comment by klimov-paul** [comment]
Duplicates #7722
