### ISSUE TITLE
Batch Query Result no longer works for large result sets in PHP7

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#12637]
### What steps will reproduce the problem?

Install PHP7 and try and select a result set which exceeds the 128MB default limit of a PHP process.

### What is the expected result?

The PDO cursor streams to the batch result.

### What do you get instead?

Out of Memory exception

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7
| Operating system | Ubuntu

### Additional

Most likely need to use pagination in the future editions of batch query result since unbuffered queries have some serious problems and limitations.

**Comment by klimov-paul** [comment]
Duplicates #9269

**Comment by Sammaye** [comment]
But that issue seems to think everything is fine if you upgrade or change to ensure not dupicate connection threads are open.This issue is one that is traceable in PHP7 since a bug fix so now: http://php.net/manual/en/mysqlinfo.concepts.buffering.php 

> When using libmysqlclient as library PHP's memory limit won't count the memory used for result sets unless the data is fetched into PHP variables. With mysqlnd the memory accounted for will include the full result set.

And since mysqlnd is not only the most feature rich but also default install (and recommended, unlike libmysqlclient which is actually stated as not) it makes sense that the code needs to move around this.
