### ISSUE TITLE
Calling Yii::getAlias() in class method return error `Invalid path alias`

### ISSUE THREAD

**Issue by brutto** [yiisoft/yii2#12631]
### What steps will reproduce the problem?
Have class `File extends ActiveRecord` with method:
```
    public function getUploadsDir()
    {
        return \Yii::getAlias('@uploads');
    }
```

and in my config (in common section) i have this:
```
    'aliases' => [
        ...
        '@uploads' => '/var/uploads/project',
        ...
    ],
```
### What is the expected result?
When i try to use this method it's obviously have to return `/var/uploads/project`. BTW if i use directly `echo \Yii::getAlias('@uploads');` it works as expected.

### What do you get instead?
Unfortunatelly calling method `File::getUploadsDir()` i have error message `Invalid path alias: @webroot/assets` and i do not realise why if directly calling \Yii::getAlias() working well. =\

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version    |  7.0 |
| Operating system |Ubuntu trusty|

**Comment by dynasource** [comment]
this has nothing to do with your example '@uploads'. This is about the alias @webroot/assets which is your basePath in $app->urlManager.

The solution is in creating an assets folder within @webroot

**Comment by brutto** [comment]
@dynasource thnx for reply, digging in that line too. I forgot to point this issue appears with **console** use only. Am i correct realize that **@webroot** point to `basePath` param in config and **@web** point to `baseUrl`?

And yes, it can be _fixed_ this with set in ~/config/local.php `basePath` param, but i missunderstand how it works. =\ I found several places in config where `basePath` param set and without this _fix_ everithing work correct via **web**.

PS: sorry for nooby questions maybe, but can not google anything with insight explains.

**Comment by samdark** [comment]
Yes. Web may assume some paths. Console can't.
