### ISSUE TITLE
createCommand  results in ORA due to a suspicious "yii2." injected for table name

### ISSUE THREAD

**Issue by SSiwek** [yiisoft/yii2#12642]
Hi 

I do not understand at which point the "yii2." is injected into that command.

I think there is a problem, because I use alias for the tablename.
I shortend the statement for you to this minimum.
The SQL-Statement in real is much more complex.

### What steps will reproduce the problem?

```
		$command = $connection->createCommand("select t.* from task t");
		$result = $command->queryOne();
```

### What is the expected result?
That the command is executed

### What do you get instead?
Database Exception – yii\db\Exception

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii2.task' doesn't exist
 The SQL being executed was: select t.* from task t
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'yii2.task' doesn't exist
)

↵ 
Caused by: PDOException 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii2.task' doesn't exist
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10-dev
| PHP version      | 5.6.8
| Operating system | Windows

**Comment by SilverFire** [comment]
`yii2` is the name of your database and the error says that you do not have table `task` in database `yii2`
