### ISSUE TITLE
AccessControl not redirecting from yii\web\User::loginRequired() if authorization fails

### ISSUE THREAD

**Issue by keithslater** [yiisoft/yii2#12646]
I'm not sure if loginRequired is called or
When authorization fails, the user isn't redirected to login. I have the following set in config/web.php - 

    'loginUrl' => ['/user/login'],

This used to work but it doesn't seem to anymore. Seems like it's an issue with redirecting. If I add this to my access behavior -

    'denyCallback' => function ($rule, $action) {
					$this->redirect('/user/login');
					var_dump('didnt redirect');
					exit;
				},

It doesn't redirect me. It does however var dumps "didnt redirect." If I removed the var dump, exit, it will try to load the page. If I throw an exception in the denyCallback, the exception will appear. Ideally I don't want to do denyCallback and have it redirect if authorization fails like it used to.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10-dev
| PHP version      | php 7.0.10
| Operating system | macOS Sierra and Ubuntu

In trying to do additional debugging, I can verify that loginRequired is called and that it is getting to return Yii::$app->getResponse()->redirect($this->loginUrl);. Is also appears that the redirect method has the correct url in _headers, location, to redirect to in the response and is trying to set the status as a 302 redirect.

**Comment by rob006** [comment]
You can't use `$this` in anonymous method. Try enable error reporting in PHP config - you probably messed up something, but you don't see this, because you mute all errors.

**Comment by keithslater** [comment]
I think it's because the page is throwing an exception before it can redirect. Probably something with a db query and  not having data. I will check it out.
