### ISSUE TITLE
Migrations - add column before

### ISSUE THREAD

**Issue by bhagwatchouhan** [yiisoft/yii2#12644]
### What steps will reproduce the problem?

Call the method addColumn of Migration class.

### What is the expected result?

It should allow to specify the column options to insert column before or after existing columns.

### What do you get instead?

There is no such option available in addColumn method.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

The method signature is addColumn($table, $column, $type) and it does not provide options to specify the before or after column to insert column at desired position instead of always getting it added at last.

**Comment by SilverFire** [comment]
See [after()](http://www.yiiframework.com/doc-2.0/yii-db-columnschemabuilder.html#after()-detail) method description

**Comment by bhagwatchouhan** [comment]
This issue was raised for Migration Class [addColumn()](http://www.yiiframework.com/doc-2.0/yii-db-migration.html#addColumn()-detail) method and has nothing to do with [after()](http://www.yiiframework.com/doc-2.0/yii-db-columnschemabuilder.html#after()-detail) method provided by ColumnSchemaBuilder.

It's specific to Migration class addColumn method and inability to specify after or before column while adding a new column using it.

**Comment by rob006** [comment]
```php
$this->addColumn('post', 'topic_id', $this->integer()->after('id'));
```
?

**Comment by bhagwatchouhan** [comment]
Ok. Thanks for your response. It seems to be the solution since $type which 3rd parameter of addColumn is instance of ColumnSchemaBuilder class and it's support to chained methods. :+1:
