### ISSUE TITLE
indexBy(callable) not calling when used column()

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [yiisoft/yii2#12649]
### What steps will reproduce the problem?
why indexBy() with a anonymous function not working ? but with a column name worked.
**my code**
```
print_r(
	Role::find()
		->select(['name','id'])
		->indexBy(function($row){
			#exit('fire'); #not run
			return $row['id']*3;
		})
	->column()
);
```

### What is the expected result?
```

(
    [12] => a
    [46] => b
    [313] => c
)
```
### What do you get instead?
```

(
    [0] => a
    [1] => b
    [2] => c
)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.3
| Operating system | ?

**Comment by Alex-Code** [comment]
Does it work if you use `->all();`?
`column()` will just return the first column of data.
