### ISSUE TITLE
What is that? Why did you remove that are functions?

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#12652]
I updated just now my application. and the result;
UrlManager; AddRule didn't find.
View; BeforeRender changed.
and a lot of problems..

What is going on there??
Why are you changing everytime in core???

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.0-beta
| PHP version      | 5.4
| Operating system | Windows.. Nginx.

**Comment by SilverFire** [comment]
Yii 2 Beta was released 2 years ago and when you use beta version, you should understand, that API is not stabilized and may be changed.

Since Yii 2.0.0 release we do not break BC a lot. All minor BC breaks are listed in [UPGRADE.md](https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md), following it you can easily update your project code.

**Comment by serhatozles** [comment]
I know.. Okay sorry about that. There is a problem i think.. Becouse I can see on ["here"](https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php) AddRule Function and other functions. But after update files, There is no functions like that. Different Class on there. What's wrong on there?

**Comment by SilverFire** [comment]
`composer show`

**Comment by serhatozles** [comment]
yiisoft/yii2-bootstrap                  2.0.0-beta         The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer                   dev-master e882cc3 The composer plugin for Yii extension installer
yiisoft/yii2-debug                      2.0.3              The debugger extension for the Yii framework
yiisoft/yii2-gii                        2.0.0-beta         The Gii extension for the Yii framework
yiisoft/yii2-httpclient                 dev-master 9921313 HTTP client extension for the Yii framework
yiisoft/yii2-jui                        2.0.0-beta         The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer                2.0.3              The SwiftMailer integration for the Yii framework
yurkinx/yii2-image                      dev-master 0d6d261 Yii2 extension for image manipulating using Kohana Imag...

**Comment by cebe** [comment]
most likely you are missing the composer asset plugin and thus composer installs an old version that does not need it. you should require stable package versions and follow installation instructions as described in the guide: http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-yii

**Comment by serhatozles** [comment]
woow it's my mistake. it fixed after install "composer-asset-plugin". thanks for that @cebe and sorry my first message.
