### ISSUE TITLE
FR, ENH: Show alternative when command not found

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#12659]
![screenshot from 2016-10-04 12 52 42](https://cloud.githubusercontent.com/assets/5828252/19064042/cfb631fe-8a31-11e6-9a3b-b4d542c9469f.png)

**Comment by samdark** [comment]
Excellent idea.

**Comment by cebe** [comment]
Solution is implemented. Thanks for the suggestion and your contribution!
