### ISSUE TITLE
Classmap not working for yii\base\Object and yii\base\Component

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#12654]
### What steps will reproduce the problem?
Use the following in a app's bootstrap.php:
```php
Yii::$classMap['yii\base\Object'] = $yiiPath . '/app/base/_Object.php';

or 

Yii::$classMap['yii\base\Component'] = $yiiPath . '/app/base/_Component.php';
```

### What is the expected result?
That _Object.php is loaded instead of Yii's default

### What do you get instead?
My designated file is not loaded

### How is this possible?
I narrowed this issue down to the fact that Object is already loaded during Yii.php. Within this file, the Yii::$container is loaded:
```php
Yii::$classMap = require(__DIR__ . '/classes.php');
Yii::$container = new yii\di\Container();
```
Container extends from Component + Object so these are already loaded and therefore cannot be classmapped.

**Comment by dynasource** [comment]
a solution to this, could be by making Container to adopt its parents methods. 
Another working solution is the following:

```php
require(YII_PROJECT_ROOT . '/vendor/autoload.php');
\Composer\Autoload\includeFile(YII_PROJECT_ROOT . '/vendor/dmn/yii2/app/base/_Object.php');
require(YII_PROJECT_ROOT . '/vendor/yiisoft/yii2/Yii.php');
```

I close this one as this latter solution works fine.

**Comment by klimov-paul** [comment]
The simpliest way is usage of `\yii\BaseYii` instead of `Yii` for the class map specification:

```php
\yii\BaseYii::$classMap['yii\base\Object'] = $yiiPath . '/app/base/_Object.php';
```

**Comment by dynasource** [comment]
this throws:
```php

Fatal error: Cannot declare class yii\BaseYii, because the name is already in use in E:\home\dmn\lw\5\dev\vendor\yiisoft\yii2-dev\framework\BaseYii.php on line 60
```

**Comment by klimov-paul** [comment]
> Fatal error: Cannot declare class yii\BaseYii, because the name is already in use 

Indeed. You'll need to declare `Yii` class yourself to make this work:

```php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/vendor/autoload.php');

class Yii extends \yii\BaseYii
{
}

spl_autoload_register(['Yii', 'autoload'], true, true);
Yii::$classMap = require(__DIR__ . '/vendor/yiisoft/yii2/classes.php');
\yii\BaseYii::$classMap['yii\base\Object'] = __DIR__ . '/MyObject.php';
Yii::$container = new yii\di\Container();

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
```

**Comment by dynasource** [comment]
in what way is your solution simpler? ;)

**Comment by klimov-paul** [comment]
It is not - it is just a correction for the my initial comment.

**Comment by Mirieri** [comment]
This issue should be reopened

**Comment by bizley** [comment]
This is some misconfiguration on your side. Please ask for the solution at the [forum](https://forum.yiiframework.com/).
