### ISSUE TITLE
ADD Arbitrary checks to \yii\debug\Module::checkAccess

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#1266]
In `/app/config/web.php`:

``` php
'modules' => array(
    'debug' => array(
        'class' => 'yii\debug\Module',
        'accessValidators' => [
            [
                'callback' => 'yii\debug\access\IP',
                'data' => [
                    '127.0.0.1',
                    '::1',
                ],
            ],
            [
                'callback' => 'app\components\debug\access\UserLogin',
                'data' => [
                    'me',
                    'boss',
                ],
            ]
        ]
    ),
),
```

Or should i implement it myself, any wishes and guidelines to follow ? What about and/or logic between different validators ? Or framework-wide composite validator ?

(Now kludged by adding over-widened IP ranges for all involved persons and their access providers)

**Comment by samdark** [comment]
That's how it could be implemented: https://github.com/samdark/yii2-webshell/commit/2508d8780fb0552f82f5271eb56c955761aa87cc

**Comment by dynasource** [comment]
see @samdarks comments
