### ISSUE TITLE
Error message in phpStorm

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#12673]
![image](https://cloud.githubusercontent.com/assets/874234/19104488/72610f6a-8ae5-11e6-9d4c-092085249b70.png)

**Comment by samdark** [comment]
Seems it's a bug in PhpStorm. Could you report that to their tracker and post a link here? https://youtrack.jetbrains.com/issues/WI

**Comment by SilverFire** [comment]
Not a bug.

http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by githubjeka** [comment]
It's going to blow up in Yii2 face. Lol...

**Comment by samdark** [comment]
Later — yes. Probably. We have to watch and prepare...

**Comment by cebe** [comment]
duplicate of https://github.com/yiisoft/yii2/issues/7936
