### ISSUE TITLE
Traits not autoloading

### ISSUE THREAD

**Issue by RdeWilde** [yiisoft/yii2#12687]
### What steps will reproduce the problem?
Create a trait in app/models, for example call it Filtering. (where app is your actual root)
Create a model that uses the Filtering trait.
Create a REST controller in app/controllers using the model above
Open up the REST index url.

### What is the expected result?
Listing the data with implementing the Filtering trait functionality on the model

### What do you get instead?
Error that the trait could not be found. It seems like it is not autoloaded (correctly)

### Additional info
Debug on
It seems not to autoload (as it is not in the vendor dir and Yii not getting it?).
When I manually put it in the composer autoload classmap, it works correctly.
Possibly timing is relevant too.
```
<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'app\models\Filtering' => $vendorDir . '/../models/Filtering.php',
);
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.*
| Operating system | Some linux

**Comment by cebe** [comment]
1. what is the name of the Trait and which namespace is it located in, what is the exact name of the file and the exact error message?
2. are you using the Yii autoloader?

**Comment by RdeWilde** [comment]
1. I figured I was lacking some info; It is the model using the trait, not the controller, I will correct it.

Names(paces);
`/models/Filtering.php`
```
<?php
namespace app\models;

/**
 * Class Filtering
 * @package app\models
 */
trait Filtering {
}
```
`./controllers/RecreationObjectTypeController.php`
```
<?php
namespace app\controllers;

/**
 * Recreation object types
 */
class RecreationObjectTypeController extends yii\rest\ActiveController {
	public function init() {
		$this->modelClass =	\us\ours\models\RecreationObjectType::className();
		$this->modelsNamespace 	=	'\us\ours\models';

		parent::init();
	}
}
```
`vendor/us/ours/models/RecreationObjectType`
```
namespace us\ours\models;
use app\models\Filtering;
use yii\web\Linkable;
class RecreationObjectType extends \yii\db\ActiveRecord implements Linkable
{
	use Filtering;
```
2. Error message
```
Fatal error: Trait 'app\models\Filtering' not found in /var/www/vhosts/domain.ext/httpdocs/vendor/us/ours/models/RecreationObjectType.php on line 74
```

**Comment by cebe** [comment]
looks really weird, can you show the full stack trace of the error?

**Comment by RdeWilde** [comment]
There's none that I'm aware of, just the error above as black text on white page.

I'll try to dig up more when I'm at work tomorrow.

**Comment by cebe** [comment]
you should enable YII_DEBUG then

**Comment by dynasource** [comment]
@RdeWilde is it solved yet

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.

**Comment by RdeWilde** [comment]
No sorry, been busy meanwhile

**Comment by RdeWilde** [comment]
Debug is enabled. If you require further information, please eleborate.

**Comment by cebe** [comment]
> can you show the full stack trace of the error?

**Comment by RdeWilde** [comment]
Where should I find this stack trace? It is not on my screen. Debug is on. Possibly it crashes before Yii is properly initiated?

**Comment by cebe** [comment]
if the class is loaded after the Yii application has been created in index.php and YII_DEBUG is true, you should see a stack trace. Otherwise your environment is broken in some way.

can you paste the content of your index.php file?
