### ISSUE TITLE
RBAC rules with protected/private properties

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#12681]
### What steps will reproduce the problem?

Add a RBAC rule with a `private` property via `DbManager`.
### What is the expected result?

Rule added successfully.
### What do you get instead?

```
PHP Notice 'yii\base\ErrorException' with message 'unserialize(): Error at offset 100 of 104 bytes'
in /srv/http/bfauto/vendor/yiisoft/yii2/rbac/DbManager.php:608
```
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 7.0.11 |
| Operating system | Linux 4.7.6-1 |

**Comment by githubjeka** [comment]
@Kolyunya Please provide the code to the reproduce.

**Comment by Kolyunya** [comment]
@githubjeka try to add the following rule via `DbManager`:
```
namespace app\rbac;

use yii\rbac\Rule;

class TestRule extends Rule
{
    public $name = 'rule';

    private $foo;

    public function execute($user, $item, $params)
    {
        return true;
    }
}
```

**Comment by SilverFire** [comment]
Which DBMS do you use?

**Comment by SilverFire** [comment]
Probably related to https://github.com/yiisoft/yii2/issues/10176

**Comment by Kolyunya** [comment]
@SilverFire I'm using `PostgreSQL`. This issue turns to be a duplicate of the #10176 but it wasn't solved in fact.

> @SilverFire I stopped using private and protected fields in Rule classes.

This is not the solution of the problem IMO.

**Comment by SilverFire** [comment]
The problem is out of Yii scope: https://bugs.php.net/bug.php?id=53756

**Comment by Kolyunya** [comment]
@SilverFire if you carefully read the page you referenced you will notice that this is the expected behavior of the PHP interpreter and the problem is right inside the Yii scope. The wrong column type is used to store serialized rule data. It must be a binary column, not string.

**Comment by SilverFire** [comment]
> The wrong column type is used to store serialized binary rule data. It must be a binary column, not string.

We already use binary column: [1](https://github.com/yiisoft/yii2/blob/master/framework/caching/migrations/schema-pgsql.sql#L18), [2](https://github.com/yiisoft/yii2/blob/master/framework/caching/migrations/m150909_153426_cache_init.php#L51)

Are you sure you have column of `bytea` type?

**Comment by Kolyunya** [comment]
@SilverFire I think you may be referencing non-relevant parts of the code. The RBAC migration [uses](https://github.com/yiisoft/yii2/blob/master/framework/rbac/migrations/schema-pgsql.sql#L20) the `text` column type.
