### ISSUE TITLE
BeforeAction and hyphenated Actions

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii2#12692]
### What steps will reproduce the problem?
In a controller:

```php
public function beforeAction($action)
{
   die("Before action:".$action->controller->id.'/'.$action->id);
}

public function actionHyphenAction()
{
   //Code
}

```
Call to http://localhost/controller/hyphen-action

### What is the expected result?
Before action: controller/hypen-action

### What do you get instead?
Before action: site/error
Because It is calling to error handler

### Additional info
If we use hyphened action, calls to error handler.
If we use NON-hyphened action, it works fine.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.8
| Operating system | Ubuntu 14

**Comment by cebe** [comment]
Hyp**h**enAction vs. hypen-action?

**Comment by nacesprin** [comment]
0.o I don't understand your question.

By calling actionHyphenAction(), it causes an error in beforeAction($act){ echo $act->id }
However, by calling actionHyphenaction(), it works as expected.

**Comment by cebe** [comment]
my question was about the difference between hypen and hyphen.

if you see `site/error`, that means an exception has been thrown. You should enable YII_DEBUG and see what happened.

**Comment by nacesprin** [comment]
Ok. A clear example is:

I visit: /site/request-password-reset  then throws a 404 not found error.
However, if I change:

Site Controller:
`
public function actionRequestPasswordReset() {}
`
by
`
public function actionRequestpasswordreset() {}
`
And I visit: /site/requestpasswordreset 
It shows the correct page.

So, I understand It is something wrong, and due to this, when I try to get the $action->id in beforeAction($action) function, it is taking the error handler action instead of RequestPasswordReset() action

This is my url manager:

`
'urlManager' => [
			'enablePrettyUrl' => true,
			'enableStrictParsing' => true,
			'showScriptName' => false,
			//'catchAll' => ['site/offline'],
			'rules' => [
				'<controller:\w+>/<action:\w+>/<id:\w+>' => '<controller>/<action>',
				'<controller:\w+>/<action:\w+>' => '<controller>/<action>',
				'<controller:\w+>/<id:\w+>' => '<controller>',
			],
		],
`

**Comment by samdark** [comment]
You have strict parsing enabled which means do according to rules and disable defaults. `\w+` means words only which `-` doesn't match. Outcome is expected.
