### ISSUE TITLE
Max and Min for masked fields don't work

### ISSUE THREAD

**Issue by ianpierreg** [yiisoft/yii2#12690]
### What steps will reproduce the problem?
Guys, I wonder if there is any way to work this error.

Basically, everytime I use yii2 masks it doens't give me error messages for max and min.

For example: If I have a date field and set min => 8 in the rules

and then I fill the field like 24/0 (where it should be something like 24/10/1994) it will be accepted. 

What do I do?
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
1. How do you validate? PJAX? Clientside? Serverside?
2. How do you define fields?
3. How do you define validation?

**Comment by ianpierreg** [comment]
I only put min => 8 in the rules, like following:

 [['cep'], 'string', 'min' => 8],

If i use text input, it validates (Must be greater than 8) but if I use maskedInput it doesn't work.

Actually, I just tried with maskedinput and that worked now it is not working anymore again.

**Comment by ianpierreg** [comment]
brackets solved my problem

**Comment by wilsonfalai** [comment]
brackets?
Can you show a example?
