### ISSUE TITLE
SluggableBehavior autofills SlugAttribute in the GridView

### ISSUE THREAD

**Issue by Shybko** [yiisoft/yii2#12696]
### What steps will reproduce the problem?
There is behaviors() method in the ActiveRecord, and looks like this
```
'slug' => [
    'class'        => SluggableBehavior::className(),
    'attribute'    => 'name',
    'ensureUnique' => true,
    'immutable'    => true,
],
```
There is standard GridView with columns id, name, slug.
### What is the expected result?
When I type something in the name filter field, it should search only by this field.

### What do you get instead?
Now if I type in the name filter field something it also fills the slug filter, but I don't need it.

I found the solution
```
$searchModel = new LandingSearch();
$searchModel->detachBehavior('slug');

$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
```

But I think it should behave correct by default, without any `detachBehavior`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9

**Comment by samdark** [comment]
The model doesn't know the context it works in. It's by design.

**Comment by agendy** [comment]
I don't understand what should I do to prevent that ?
