### ISSUE TITLE
Setting Default value to NULL in Rules

### ISSUE THREAD

**Issue by aretxaga** [yiisoft/yii2#12693]
Add a Model Rule to set a default value to NULL if empty like this:
**[['some_field'], 'default', 'value' => NULL]**
Then add another Rule under this one to Trim the text for the same field like this:
**[['some_field], 'trim']**
When the Model attribute 'some_field' is empty and you run save the attribute will be set to " " empty string and not NULL because of the Trim rule.

In order to avoid this problem the Trim rule must be defined before the default rule.
Maybe this should be mentioned on the documentation?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      | 5.5.9
| Operating system | Linux

**Comment by githubjeka** [comment]
It was documented. 
http://www.yiiframework.com/doc-2.0/guide-input-validation.html#declaring-rules

>When the validate() method is called, it does the following steps to perform validation:

1. Determine which attributes should be validated by getting the attribute list from yii\base\Model::scenarios() using the current scenario. These attributes are called active attributes.
2. Determine which validation rules should be used by getting the rule list from yii\base\Model::rules() using the current scenario. These rules are called active rules.
3. Use each active rule to validate each active attribute which is associated with the rule. **The validation rules are evaluated in the order they are listed.**
