### ISSUE TITLE
Using ActiveRecord to save data to MySQL is not valid

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#12700]
I found a strange problem, using the model to save the data without any action, but the use of `createCommand` to execute the SQL is successful.

For example, I use the model to save data:
```
$model = new User();
$model->uuid = 123;
$model->name = 'lee';
$model->save();
```
The implementation of the above code does not prompt any errors, while there is no update in the database.

But I use the following code to be successful, remember that this is in the same project:
```
Yii::$app->db->createCommand()->insert('app_info', [
    'uuid' => 123, 'name' => 'lee'
])->execute();
```
The above code can be very good work, I use the Framework version 2.0.9.

Here is my specific code:
```
<?php
namespace app\models;
use yii\db\ActiveRecord;
class User extends ActiveRecord
{
}
```

**Comment by rob006** [comment]
You probably have some validation errors. Try add `var_dump($model->getErrors());` after `$model->save()`.

**Comment by xiaoxing598** [comment]
@rob006 I got the results:`array(0) { }`, I didn't write anything in the model, there is no definition of safe field, the default is safe?

**Comment by rob006** [comment]
Try add

```php
    public static function tableName()
    {
        return 'app_info';
    }
```

into model class.

**Comment by xiaoxing598** [comment]
@rob006 I found that not only the update operation is not effective, and even the query operation is not the result, the following code can not be a good job
```
$model = User::findOne(123);
```
$model is null, but db not empty

**Comment by xiaoxing598** [comment]
@rob006 @samdark 
```
$model = User::findOne(123);
$model->uuid = 123;
$model->name = 'lee';
$model->save();
```
I got an error message:'Creating default object from empty value'

**Comment by xiaoxing598** [comment]
Do I need to do this?

```
$model = User::findOne(123);
if (!$model) {
    $model = new User();
    $model->uuid = 123;
}
$model->name = 'lee';
$model->save();
```
Hope to give some advice, thank you!

**Comment by samdark** [comment]
Yes, you need this, of course.
