### ISSUE TITLE
BaseStringHelper::truncateHtml calls HTMLPurifier lexer with null $context

### ISSUE THREAD

**Issue by mattheobjornson** [yiisoft/yii2#12703]
### What steps will reproduce the problem?

Calling `StringHelper::truncateWords($model->body, 20, '...', true)` on server without php-xml package installed (DOMDocument class missing in php).
### What is the expected result?

StringHelper truncates $model->body to 20 words
### What do you get instead?

 PHP Fatal Error – yii\base\ErrorException
Call to a member function register() on null in /basepath/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DirectLex.php at line 79 
### Additional info

[BaseStringHelper::truncateHtml line 157](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseStringHelper.php#L157) calls HTMLPurifier lexer->tokenizeHTML with $context set to null. It works in case of DOMLex (which depends on DOMDocument class) but in case it uses DirectLex, it tries to [call register method on null context](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Lexer/DirectLex.php#L79). I assume DirectLex is poorly programmed here but I think a fix should be also considered on the yii2 side, maybe something like

```
$lexer = \HTMLPurifier_Lexer::create($config);
$context = new \HTMLPurifier_Context;
$tokens = $lexer->tokenizeHTML($string, $config, $context);
```

in truncateHtml() would be sufficient.

@samdark The same issue is reported [here](http://yiiframework.ru/forum/viewtopic.php?t=38077), btw.

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.6/any |
| Operating system | Linux/any |

**Comment by Alex-Code** [comment]
@mattheobjornson Are you able to check if the tests still pass when providing a `$context` object?
I had a quick look and it doesn't get used much outside of `DirectLex` so shouldn't cause any issues.

**Comment by mattheobjornson** [comment]
Seems that phpunit tests also depend on DOMDocument class (phpunit.xml.dist cannot be parsed) so they do not run at all without it. This may be as well the reason why this issue was not discovered earlier.

For test purposes I forced HTMLPurifier to load DirectLex in all cases.
Without fix:
```
mattheo@e350m1-lubuntu:~/development/projects/git/yii2$ php vendor/bin/phpunit --group=helpers
PHPUnit 4.8.27-9-g7b58ff0 by Sebastian Bergmann and contributors.

...............................................................  63 / 248 ( 25%)
............................................................... 126 / 248 ( 50%)
.......................................................EE...... 189 / 248 ( 76%)
...........................................................

Time: 684 ms, Memory: 26.00MB

There were 2 errors:

1) yiiunit\framework\helpers\StringHelperTest::testTruncate
Error: Call to a member function register() on null

/home/mattheo/development/projects/git/yii2/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DirectLex.php:79
/home/mattheo/development/projects/git/yii2/framework/helpers/BaseStringHelper.php:159
/home/mattheo/development/projects/git/yii2/framework/helpers/BaseStringHelper.php:108
/home/mattheo/development/projects/git/yii2/tests/framework/helpers/StringHelperTest.php:110
/home/mattheo/development/projects/git/yii2/vendor/phpunit/phpunit/phpunit:47

2) yiiunit\framework\helpers\StringHelperTest::testTruncateWords
Error: Call to a member function register() on null

/home/mattheo/development/projects/git/yii2/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DirectLex.php:79
/home/mattheo/development/projects/git/yii2/framework/helpers/BaseStringHelper.php:159
/home/mattheo/development/projects/git/yii2/framework/helpers/BaseStringHelper.php:131
/home/mattheo/development/projects/git/yii2/tests/framework/helpers/StringHelperTest.php:127
/home/mattheo/development/projects/git/yii2/vendor/phpunit/phpunit/phpunit:47

FAILURES!
Tests: 248, Assertions: 922, Errors: 2.
mattheo@e350m1-lubuntu:~/development/projects/git/yii2$ 
```
With fix (providing valid context object):
```
mattheo@e350m1-lubuntu:~/development/projects/git/yii2$ php vendor/bin/phpunit --group=helpers
PHPUnit 4.8.27-9-g7b58ff0 by Sebastian Bergmann and contributors.

...............................................................  63 / 248 ( 25%)
............................................................... 126 / 248 ( 50%)
............................................................... 189 / 248 ( 76%)
...........................................................

Time: 696 ms, Memory: 26.00MB

OK (248 tests, 938 assertions)
mattheo@e350m1-lubuntu:~/development/projects/git/yii2$ 
```
