### ISSUE TITLE
Why yii2 vendors folder is so big?

### ISSUE THREAD

**Issue by aminkt** [yiisoft/yii2#12706]
Hi

I tried to develop very easy and light project by yii2.

After i run composer in every project in yii2 i can see that size of vendor folder become so large.

For example in one project my codes take 15Mb but vendors folder war 130Mb.

How can reduce size of vendors folder?

not: I did not install any widget by composer. just update it.

**Comment by rob006** [comment]
Try use `--no-dev --prefer-dist` switches on composer install/update.

**Comment by aminkt** [comment]
And if i need add some extensions in dev stability but don't update yii core to dev stability what should i do?

**Comment by githubjeka** [comment]
Don't worry about it. Because usually it works project without yii2 is size of ~200mb

**Comment by aminkt** [comment]
Thanks a lot @githubjeka  :)
