### ISSUE TITLE
"whenClient" doesn't work

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#12705]
Hi! I try to show error for client-side validation for any cases, but validation doesn't show errors for validator as i expected. Example code:
Rules;
```
            ['minutes', 'required',
                'whenClient' => "function (attribute, value) {
                    return false;
            }"],
```
View:
`                        <?= $addWorkForm->field($model, 'minutes')->dropDownList($minutes); ?>`
I expected, client-side validator should display error message, but it's not... I think, this issue looks like this https://github.com/yiisoft/yii2/issues/11755

**Comment by Alex-Code** [comment]
Returning false means it'll never run.
Remove the `whenClient` config and the rule will apply.
