### ISSUE TITLE
Exception `SAVEPOINT LEVEL1 does not exist` instead of deadlock exception

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#12715]
### What steps will reproduce the problem?

``` php
\Yii::$app->db->transaction(function () {
    \Yii::$app->db->transaction(function () {
        // here comes queries to cause unexpected deadlock
    });
});
```
### What is the expected result?

See an exception about deadlock.
### What do you get instead?

Exception `SAVEPOINT LEVEL1 does not exist` from https://github.com/yiisoft/yii2/blob/2.0.9/framework/db/Connection.php#L690
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 7.0.8 |
| MySQL | 5.7 |
| OS | Ubuntu 16.04.2 |

**Comment by SilverFire** [comment]
Which DBMS do you use?

**Comment by Vovan-VE** [comment]
MySQL 5.7

**Comment by Vovan-VE** [comment]
I did hope but it's not. When deadlock occuring, `PDO::inTransaction()` is still `true`.

What about such patch? It keep throwing original exception from transaction body, ignoring (logging) exception from `rollback()`.

```diff
 } catch (\Exception $e) {
     if ($transaction->isActive && $transaction->level === $level) {
+        try {
             $transaction->rollBack();
+        } catch (\Exception $e_rollback) {
+            \Yii::error($e_rollback, __METHOD__);
+            // continue to throw original exception $e
+        }
     }
     throw $e;
 }
```

Both exception has previous exception, so it cannot be attached to each other without separate exception class.

Is PR acceptable? Is test case required (can second connection be opened just with `DatabaseTestCase::prepareDatabase()` keeping other tests work?)?

**Comment by samdark** [comment]
Unit test is required and, I think, it's better to start with PR which contains failing test without a fix first.

**Comment by Vovan-VE** [comment]
I need to do `pcntl_fork()` to run into deadlock in the test case. Is it allowed for tests ever?

**Comment by samdark** [comment]
No idea if it would work with travis.

**Comment by cebe** [comment]
@Vovan-VE if it helps to create a test case that is reliable and produces the error it is fine. @samdark travis is running plain ubuntu instances so if it works locally it should be fine on travis.

**Comment by Vovan-VE** [comment]
Currently I made deadlock situation.

I currently playing with MySQL only at first. I do the following steps (both transactions are SERIALIZABLE):

process A | process B
--- | ---
`START TRANSACTION` | wait
`SELECT ... WHERE id = 42` (shared lock) | wait
kick process B to resume | `START TRANSACTION`
`sleep(1)` | `UPDATE ... WHERE id = 42` (wait for exclusive lock)
`UPDATE ... WHERE id = 42` |

I'm not sure if it will work for other DBMS or not. With MySQL if switch isolation to REPEATABLE READ, then `SELECT ... LOCK IN SHARE MODE` is required to hit deadlock, but it's MySQL specific AFAIK.

I fork one child. There are currently following problems:

1. I want parent process to hit deadlock, so I do bad transaction in parent (process A). It seemed logically for me: bad logic - bad result. But MySQL (unexpectedly for me) dooms harmless child process B which does correct transaction. I'm not sure is it consistent result or not. I will try to spawn two children and will do transactions there. Here I need to lift up info about expected and/or unexpected exception. I don't know how better to do this. Child exit status is not enough. I will use at first just temp files.

2. In case of accident PHP's fatal error in child process phpunit continues to run all other tests there, while parent has some relax nearby inside `pcntl_waitpid()`. After that parent continues to run all the same rest tests. The output in terminal is a mess. I'm not so familar with phpunit. I'm catching `\Exception` in child process and do `exit` anyway. I don't know how to deal with this.

**Comment by Vovan-VE** [comment]
Just as a note. https://www.percona.com/blog/2012/08/17/percona-xtradb-cluster-multi-node-writing-and-unexpected-deadlocks/
Cross-node transactions may cause deadlock more easily, but only at `COMMIT`, not at safepoints.
