### ISSUE TITLE
Fix consistency on method descriptions

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#12712]
### What steps will reproduce the problem?
I see two issues. When comparing method descriptions in the framework, there are
1) different descriptions for methods returning booleans. 
2) the use of the term 'value' which is quite vague for an output that is known

### What is the expected result?
1) consistent descriptions
2) use the term boolean

### What do you get instead?
To examples:
A) https://github.com/yiisoft/yii2/blob/master/framework/validators/IpValidator.php#L535 :
* Returns a **value** indicating whether a property can be read.

B) https://github.com/yiisoft/yii2/blob/master/framework/validators/IpValidator.php#L535 : 
* Checks whether the IP is in subnet range

# Suggestion
I would like to suggest to change of these descriptions to 1 format, preferably:
* Returns a **boolean** indicating whether a property can be read.

**Comment by samdark** [comment]
I agree that consistency is a good thing to achieve. As for description, I don't think it makes sense to mention boolean because it's in the `@return boolean` tag already. I'm for:

```
@return boolean whether a property can be read
```

**Comment by dynasource** [comment]
its a bit unclear to me how your @doc template would look like. Can you give me full example.

**Comment by samdark** [comment]
```
/**
   * Checks whether the IP is in subnet range
   *
   * @param string $ip an IPv4 or IPv6 address
   * @param integer $cidr
   * @param string $range subnet in CIDR format e.g. `10.0.0.0/8` or `2001:af::/64`
   * @return boolean whether the IP is in subnet range
   */
```

**Comment by dynasource** [comment]
At first hand, this look clear and logical. On the other hand, compared to the @docs for getter methods, it  adds inconsistency.

Getter methods always start with 'Returns ....'. If you change the statement for booleans, the statement for getters should be changed too. But its hard to change the statement for getters, making it more logical to stay with 'Returns' in the first place, for every function that returns 'something'.

Of course this is double with @return, which is not optimal, but as this is for IDE purposes, not a great deal. One could argue that these @return will even go away in the future because of PHP return type hinting.

To conclude. I would suggest to keep the format starting with Return like this:
```php
    /**
     * Returns a boolean whether the IP is in subnet range
     * @param string $ip an IPv4 or IPv6 address
     * @param integer $cidr
     * @param string $range subnet in CIDR format e.g. `10.0.0.0/8` or `2001:af::/64`
     * @return boolean whether the IP is in subnet range
     */

consistent with other getters

    /**
     * Returns all behaviors attached to this component.
     * @return Behavior[] list of behaviors attached to this component
     */
    public function getBehaviors()
    {
        $this->ensureBehaviors();
        return $this->_behaviors;
    }
```

**Comment by SilverFire** [comment]
It's not always easy to say in few words what exactly will be returned. Especially when you have multiple return types described. Added to code style recommendations

**Comment by SilverFire** [comment]
Resolved by bbfdba0

**Comment by SilverFire** [comment]
And f9177d2

**Comment by dynasource** [comment]
:+1:
