### ISSUE TITLE
checkDNS in EmailValidator returns false positives

### ISSUE THREAD

**Issue by genichyar** [yiisoft/yii2#12714]
### What steps will reproduce the problem?

checking DNS in EmailValidator doesn't raise error if I enter wrong email. For example, `qwert@dfjkdfjkdf.dkdfj`
### What is the expected result?

I expect that it will be showing an error that email in invalid.
### What do you get instead?

No error is shown.
### Additional info

if I use `checkdnsrr('dfjkdfjkdf.dkdfj', 'A')` it returns true but `checkdnsrr('dfjkdfjkdf.dkdfj', 'MX')` returns false.

I think that error occurs because `checkdnsrr` also search over all subdomains of my hostname. If I append dot to domain name in `checkdnsrr` the problem disapears.

So I propose change line 99 in EmailValidator to:

`$valid = checkdnsrr($matches['domain'] . '.', 'MX') || checkdnsrr($matches['domain'] . '.', 'A');`

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.6.26 |
| Operating system | CentOS 6.0 |

**Comment by Thoulah** [comment]
My best guess is that your DNS returns incorrect values. Maybe catching unknown domains to a certain IP address?

```
var_dump( checkdnsrr('dfjkdfjkdf.dkdfj', 'A') );
var_dump( checkdnsrr('dfjkdfjkdf.dkdfj', 'MX') );
```

```
bool(false)
bool(false)
```

**Comment by genichyar** [comment]
@Thoulah , I think you are right but I don't change any DNS params in my VPS. So problem can occurs with any Yii2 developer.

I think that error occurs because `checkdnsrr ` **search over all subdomains of my hostname**. If I use `dns_get_record('dfjkdfjkdf.dkdfj', DNS_A)` it returns
```php
Array
(
    [0] => Array
        (
            [host] => dfjkdfjkdf.dkdfj.XXXXXX.com
            [class] => IN
            [ttl] => 21599
            [type] => A
            [ip] => 37.140.X.X
        )
)
```
where `XXXXXX.com` is hostname of my server, `37.140.X.X` is IP of my server.

If i put a dot at the end of a checking hostname there is no problem. In this case `checkdnsrr` doesn't search over all subdomains. For example,

```php
var_dump( checkdnsrr('dfjkdfjkdf.dkdfj', 'A') ); // bool(true)
var_dump( checkdnsrr('google.com', 'A') ); // bool(true)
var_dump( checkdnsrr('dfjkdfjkdf.dkdfj.', 'A') ); bool(false)
var_dump( checkdnsrr('google.com.', 'A') ); // bool(true)
```

I can make PR but I don't know how this solution will work in other OS, for example, in Windows. Please try `checkdnsrr` with dot if you can.

**Comment by twisted1919** [comment]
Appending dot at the end is the correct way of doing the check.
