### ISSUE TITLE
Widget->getId() suggestion

### ISSUE THREAD

**Issue by dunaicapa** [yiisoft/yii2#12716]
### What steps will reproduce the problem?
display a widget on the page thats js is operating with its widget id
ajax load the same widget with after the first one

### What is the expected result?
widgets may work

### What do you get instead?
widgets will not work because their js selector interfares

### Additional info
Widget::getId() may use microtime instead of a static counter so its impossible to get the same id in any iteration
for example:

    public function getId($autoGenerate = true)
    {
           if ($autoGenerate && $this->_id === null) {
                $this->_id = static::$autoIdPrefix . (microtime(true)*10000);
           }

        return $this->_id;
    }

| Q                | A
| ---------------- | ---
| Yii version      | 2.*
| PHP version      *
| Operating system  *

**Comment by unclead** [comment]
why don't you just set id manually to prevent such error?

**Comment by dunaicapa** [comment]
I dont want to, because the framework could handle it and im lazy.

**Comment by klimov-paul** [comment]
Duplicates #4749

**Comment by dynasource** [comment]
@dunaicapa shows (again) that an improvement on this matter is required in practice. Perhabs coupling it to microtime is not good, based on https://github.com/yiisoft/yii2/pull/4749#issuecomment-52639594 but perhabs other solutions are possible.

Solutions in which the ID is unique base on the __CLASS__ or a specific object state, based on the preference of the developer.
