### ISSUE TITLE
Provide `version` property for the `Application`

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#12726]
Extracted from https://github.com/yiisoft/yii2-debug/issues/143

It may be useful to provide `version` property for the `Application` class, which can be used for logging and debugging.

There should be a posibility to setup version as a PHP callback, which will return its actual value.

It also make sense to inroduce this property at `Module` level.

**Comment by klimov-paul** [comment]
Possible implementation proposed at #12727

**Comment by klimov-paul** [comment]
Actually there is already `yii\base\Application::version` public field, which can be used:
https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L100

So the question is if it should be converted to virtual property for more flexibility.

**Comment by klimov-paul** [comment]
Resolved by commit 8d05bd9

**Comment by dynasource** [comment]
thanks!
