### ISSUE TITLE
how to make a update query with a limit

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [yiisoft/yii2#12729]
Query:
```
Yii::app()->db->createCommand()
			->update('test', ['test' => 2], ['name' => 'test'])
			->execute();
```
I need to add a limit to how to do it?
eg.
```
		Yii::app()->db->createCommand()
			->update('test', ['test' => 2], ['name' => 'test'])
			->limit(1)
			->execute();
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0
| Operating system | Linux

**Comment by Alex-Code** [comment]
What are you trying to achieve?

**Comment by mariuszkrzaczkowski** [comment]
He needs to update a single entry and not all,
the names are the same so I have to have a limit
in mysql is impossible to do this for example.
```mysql
UPDATE table SET checked = 1 WHERE field = 'xxx' LIMIT 1
```

**Comment by dynasource** [comment]
thats odd. What is your usecase to have ony 1 single entry updated?

**Comment by Alex-Code** [comment]
This seems a bit specific, I'd just do raw SQL
`->createCommand("UPDATE table SET checked = 1 WHERE field = 'xxx' LIMIT 1")->execute();`

**Comment by mariuszkrzaczkowski** [comment]
it needs to log database
and the query must be run on multiple database engines

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/7606
