### ISSUE TITLE
yii\base\Model->load() have a mistake?

### ISSUE THREAD

**Issue by devlat** [yiisoft/yii2#12730]
I want to populate model attributes by form data. Below is my code:
`$user->load(Yii::$app->request->post(), 'SignUpForm');`
So it's doesn't work. 
I looked at the source code and saw that setting safeOnly = true by default in setAttributes. The load () funtion is ignores it, so setAttributes() call safeAttributes, not attributes(). It is normally?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.11
| Operating system | Ubuntu 16.04

**Comment by devlat** [comment]
Oh, excuse me. I'm begginer in Yii2, this is issue is a wrong. I didn't know about scenarios.

**Comment by Charius** [comment]
just close it

**Comment by devlat** [comment]
@Charius 
Thank you.
