### ISSUE TITLE
Url::to("/", "//") or how to generate absolute links without protocol

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2#12738]
The UrlManager does not support currently generating absolute links without the protocol part.
This is pretty common to avoid "mixed content" messages in browsers.

I have a domain `http://domain.com` so I need to get from UrlManager `//domain.com`.

Following is current output:

```
Url::to('//', true) ---> "//"
Url::to('/', '//') ---> "//://domain.com/"
Url::to('/', 1) ---> "http://domain.com/" or "https://domain.com/"
Url::to('//', 1) ---> "//"
```

So no proper protocolless absolute link.

Did I miss something or can this feature be added?
Thank you.

**Comment by samdark** [comment]
Looks similar to #12691
