### ISSUE TITLE
Optional UrlRule prefix

### ISSUE THREAD

**Issue by dmitry-zaporozhan** [yiisoft/yii2#12733]
Default url parameters do not work during parsing if parameter is at the beginning of url rule and is omitted.

`language` is optional and is in the **end** of url rule - works as expected for parsing and creation.
```
[
    'pattern'=>'<controller>/<action>/<language>',
    'route'=>'<controller>/<action>',
    'defaults'=>['language'=>'en'],
]
```
`language` is optional and is in the **beginning** of url rule - parsing does not work if language is omitted, creation works as expected.
```
[
    'pattern'=>'<language>/<controller>/<action>',
    'route'=>'<controller>/<action>',
    'defaults'=>['language'=>'en'],
]
```

**Comment by cebe** [comment]
duplicate or related to #10970?

**Comment by dmitry-zaporozhan** [comment]
I dont think so.
Using this rule
```
[
    'pattern'=>'<language>/<controller>/<action>',
    'route'=>'<controller>/<action>',
    'defaults'=>['language'=>'en'],
]
```
`Url::to(['site/index'])` produces `/site/index` which leads to 404 exception.
`Url::to(['site/index', 'language'=>'en'])` produces `/en/site/index` which works.

**Comment by dmitry-zaporozhan** [comment]
My mistake
