### ISSUE TITLE
Skipping a save on empty dirty values not always valid

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#12749]
This one took a while to figure out.

### What steps will reproduce the problem?
* Save an AR with no changed values (taken from DB)
* During this save, changes to this DB record are made (in my case in beforeSave with an updateAll)

### What is the expected result?
That my save is correctly executed.

### What do you get instead?
The AR thinks nothing is changed because of (https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L751), but in fact, a change was indeed evident because of the the DB record is changed, so the AR should actually think there is something changed.

Additionally, one could think of other people updating the record.

I would expect that the framework would always check for realtime changes and not work with a shortcut. If somebody is saving an AR, you expect it to save. Not the opposite.

**Comment by dynasource** [comment]
the strange thing about this one that it is so hard to test because different behavior occurs between Mysql & Sqlite:
* mysql follows this path: https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L598
* sqlite follows this path: https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L592

**Comment by dynasource** [comment]
the difference between mysql & sqlite was caused by that mysql was returning an int and sqlite a boolean.

**Comment by samdark** [comment]
Add a timestamp behavior to it.

**Comment by dynasource** [comment]
I think that something is fundamentally wrong with https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L751

As a developer you are expecting that if you are saving something, it is really saved. The current implementation makes an assumption that nothing has changed, which in practice actually wasnt the case. 

Shouldnt the default implementation be that nothing is 'assumed' and a choice is made for realtime data?

**Comment by samdark** [comment]
> As a developer you are expecting that if you are saving something, it is really saved. 

I'm expecting it not to save if nothing was changed. Not sure why you want to save in this case...

**Comment by dynasource** [comment]
> I'm expecting it not to save if nothing was changed

Which also means that you want to have the latest data out of the DB

**Comment by samdark** [comment]
There's `->refresh()` method if you want to ensure data is current.

**Comment by dynasource** [comment]
I tried ```php ->refresh ``` and lot of other methods in BaseActiveRecord but not of them made my tests pass. The only solution that is working is that I use ->updateAll() without updating the current record.

**Comment by dynasource** [comment]
to extend this issue with a concrete example:
* because of this issue, an attribute called 'active' is toggled in the DB at every save, although explicitly 'true' is posted.

**Comment by samdark** [comment]
Hmm... isn't http://www.yiiframework.com/doc-2.0/yii-behaviors-attributetypecastbehavior.html solving it?

**Comment by dynasource** [comment]
could be. The question is, should we ignore a save which has become valid because of changes in the DB.

**Comment by samdark** [comment]
We're relying on model state, we're not re-querying data automatically since doing that isn't necessary in most cases and causes performance issues.

**Comment by dynasource** [comment]
that makes sense. I will try to find the reason why https://github.com/yiisoft/yii2/issues/12749#issuecomment-253975410 isnt working. Thanks!
