### ISSUE TITLE
unit tests are broken, TravisCI fails

### ISSUE THREAD

**Issue by mytskine** [yiisoft/yii2#12745]
The commit 3e1588b5b9cfc2d2b09a2352586eb464dfae81b0 applied yesterday (2016-10-14) broke the unit tests because of missing name spaces "use"s.

See [Travis CI's failure](https://travis-ci.org/yiisoft/yii2/builds/167325003) for this commit.

**Comment by cebe** [comment]
Thanks for reporting, will fix it asap.
