### ISSUE TITLE
yii.activeForm.js form init callback

### ISSUE THREAD

**Issue by werew01f** [yiisoft/yii2#12744]
Suggestion for improvement.

add yiiActiveForm afterInit event https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js

example: I'm register sctipt in view
`$this->registerJsFile('/js/add.js', [
    'depends'  => [\yii\web\JqueryAsset::className(), yii\widgets\ActiveFormAsset::className()]
]);`

And this append after yii.activeForm.js, but before actual init call
`$view->registerJs("jQuery('#$id').yiiActiveForm($attributes, $options);});");`

To make sure that the form is initialized
`setInterval(function(){
  if (typeof $('#formID).data('yiiActiveForm') !== 'undefined') { /* yes! drop interval */ } else { /* no wait :( */ }; }, 100);`
insead of normal afterInit callback

**Comment by SilverFire** [comment]
Thank you for idea. Would you like to submit a PR?
