### ISSUE TITLE
Migration Generator - incorrect foreign key field

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#12748]
### What steps will reproduce the problem?

`yii migrate/create create_products_combine_with_table  --fields="combine_with_id:bigPrimaryKey:unsigned,product_id:bigInteger:unsigned:notNull:foreignKey(products)"`

Some clarification - primary key of `products` table is `product_id`
It is generating `id` but should generate `product_id`
### What is the expected result?

```
public function up()
{
    ...

    // add foreign key for table `products`
    $this->addForeignKey(
        'fk-products_combine_with-product_id',
        'products_combine_with',
        'product_id',
        'products',
        'product_id',
        'CASCADE'
    );
}
```
### What do you get instead?

```
public function up()
{
    ...

    // add foreign key for table `products`
    $this->addForeignKey(
        'fk-products_combine_with-product_id',
        'products_combine_with',
        'product_id',
        'products',
        'id',
        'CASCADE'
    );
}
```
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.10-dev |
| PHP version | 5.6.9 |

**Comment by SilverFire** [comment]
@mdmunir

**Comment by MKiselev** [comment]
@tsanchev everything works as described in the documentation, migration mechanism is unknown about what field in the products table is the primary key.
------
Всё работает как и описано в документации, механизму миграции неизвестно о том, какое поле в таблице products является первичным ключом.

@SilverFire предлагаю поставить label:type:enhancement и в качестве решения могу предложить когда foreignKey прописывается с параметрами, вторым параметром передавать название поля, т.е. вот так: ```foreignKey(products, product_id)```
Если решение устраивает, то готов приступить к реализации.

**Comment by tsanchev** [comment]
@MKiselev i think it would be better if the migration mechanism gets the primary key field directly from the database of the given table instead of an extra parameter to foreignKey

**Comment by MKiselev** [comment]
@tsanchev the mechanism of creating migration nowhere use the database component, so I think members unlikely to support the idea.

**Comment by samdark** [comment]
There are 2 ways of solving the problem:

1. Specify FK column as parameter.
2. Get FK column from DB (that would require querying existing schema).

**Comment by samdark** [comment]
These two could be combined. If key isn't specified, get it from DB.

**Comment by MKiselev** [comment]
@samdark Ok.

I resolve this issue.

**Comment by MKiselev** [comment]
I was made this logic:
![untitled diagram 1](https://cloud.githubusercontent.com/assets/4495801/19479650/4a69b7d8-9561-11e6-919d-40356630405e.png)

FK field may set like this: ```foreignKey(products product_id)```

Please make code review.

If all good, i will update docs.

**Comment by MKiselev** [comment]
@samdark thanks for code review.
Add this logic for ```create junction``` too?

**Comment by samdark** [comment]
Yes.
