### ISSUE TITLE
ActiveDataProvider should avoid query data when data count is zero

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/yii2#12752]
### What steps will reproduce the problem?

> This is not a bug, just a suggestion.

[ActiveDataProvider::prepareModels](https://github.com/yiisoft/yii2/blob/master/framework/data/ActiveDataProvider.php#L98)  because there had queried total count, so when query count is 0, there is not need to query list.
### What is the expected result?

When query is none result, there is should be one query which is query the total of result, no need for query the list.
### What do you get instead?

Two query performed.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 7.0.11 |
| Operating system | Cenots. |

**Comment by samdark** [comment]
I agree that it would be good if it can be done w/o much hacking...

**Comment by Alex-Code** [comment]
Would this work?

```php
if (($pagination = $this->getPagination()) !== false) {
    if (0 === ($pagination->totalCount = $this->getTotalCount())) {
        return [];
    }
    $query->limit($pagination->getLimit())->offset($pagination->getOffset());
}
```

**Comment by samdark** [comment]
Probably. Is it covered by unit tests?

**Comment by TerraSkye** [comment]
i would swap 
`if (0 === ($pagination->totalCount = $this->getTotalCount())) {`

with 
`if (($pagination->totalCount = $this->getTotalCount()) === 0) {`

as we always compare  against something ( this case its 0 ).
or is this just my personal prefference.

**Comment by cebe** [comment]
related to #6373
