### ISSUE TITLE
Have you considered providing support for new MySQL JSON features such as aggregation functions

### ISSUE THREAD

**Issue by vistart** [yiisoft/yii2#12751]
MySQL have got native support for JSON ( in MySQL 5.7), and is getting JSON aggregation functions ( in MySQL 8.0).
Have you considered providing extra support for the JSON features?
[JSON Labs Release: Overview](http://mysqlserverteam.com/json-labs-release-overview/)
[MySQL 8.0 Labs: JSON aggregation functions](http://mysqlserverteam.com/mysql-8-0-labs-json-aggregation-functions/)

**Comment by samdark** [comment]
Which features would you like to have?

**Comment by klimov-paul** [comment]
Duplicates #10436
