### ISSUE TITLE
groupBy()  on mysql 5.7

### ISSUE THREAD

**Issue by undefinedor** [yiisoft/yii2#12753]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0
| Operating system | Centos7

SELECT list is not in GROUP BY clause and contains nonaggregated column 'tuodian.item_assessment_result.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by SilverFire** [comment]
It's out of Yii scope.

http://stackoverflow.com/questions/23921117/disable-only-full-group-by
