### ISSUE TITLE
Request for making validators accessible by associative key

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#12762]
The more I am working with validators, the more I need to have access to validators that are set. The current implementation is non-associative which makes accessing hard. Additionally, when debugging ActiveRecords with ie. print_r , its hard to tell which validator is which.

Therefore I would like to suggest to make the validators accessible by associative key. This would not have to be BC as the current implementation does not really support such an access.

**Comment by samdark** [comment]
Can't you do it now?

**Comment by dynasource** [comment]
Nope.

The non-associative append function of ArrayObject (http://php.net/manual/en/arrayobject.append.php)  is used:
* https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L443

This is consistently processed further in Model.php like i.e. https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L424

**Comment by samdark** [comment]
I see. What do you plan to do with validators which are set?

**Comment by dynasource** [comment]
imagine usecases in which you need to know which Validators are active for a Model and to display it to the user. Perhabs you want to do some specific ordering. Perhabs you want to build widgets based on these validators. Then you want to know which one is which.

**Comment by dynasource** [comment]
I already have this functionality in operation for a while now and its very useful for 'reading' purposes too. It enables you to read 'rules' faster. It also helps debugging faster.

Example:
```php
                $rules = [
                    
                    'title-required' => ['title', 'required'],
                    'title-string' => ['title', 'string', 'max' => 100],
                    'title-ucfirst' => ['title', 'filter', 'filter' => 'ucfirst'],
                    'title-purifier' => ['title', 'filter', 'filter' => [Purifier::class, Purifier::ALPHA_NUMERIC_LATIN]],
                    'title-unique' => ['title', 'unique', 'when' => function(){
                        return $this->isTitleUnique();
                    }],
                   
```

**Comment by samdark** [comment]
I've tried to imagine use case and failed to. More readability could be achieved with comments. Having keys in debug info doesn't add much to the overall picture.

**Comment by dynasource** [comment]
Another usecase for associative keys is the overriding of rules() in child ARs. There are cases thinkable in which rules have to be disabled or changed. 

The same applies for attached behaviors who need to check for specific rules.

Last but definately not least. I would foster the appraoch to define unique names for rules. If you have many Active Records, its way easier to compare rules between them. You instantely see if you have set all the right rules for similar attributes and if you are missing any which enhances security & consistency.

**Comment by dynasource** [comment]
My last usecase: a widget which shows the degree of which a form is completed. Some rules can be more important than others and require a larger percentage of http://getbootstrap.com/components/#progress

**Comment by klimov-paul** [comment]
> Another usecase for associative keys is the overriding of rules() in child ARs. There are cases thinkable in which rules have to be disabled or changed.

This is already possible: you can define keys for the rules inside `rules()` method and use them while overridig them:

```php
class Parent extends Model
{
    public function rules()
    {
        return [
            'my' => ['name', 'string'],
        ];
    }
}

class Child extends Parent
{
    public function rules()
    {
        $rules = parent::rules();
        $rules['my'] = ['name', 'email'];
        return $rules;
    }
}
```

**Comment by klimov-paul** [comment]
In general, we can change `Model::createValidators()` in the way it will preserve the keys from `rules()` result array using `ArrayObject::offsetSet()` instead of `ArrayObject::append()`.

**Comment by samdark** [comment]
Technically we can change that but I still don't see why. As @klimov-paul mentioned, inheritance works well now.

@dynasource do you have a case where you need to change already instantiated validators?

**Comment by dynasource** [comment]
Usecases are endless, depending on the depth in which a developer is making use of Validators. The deeper you go, the more the relevant associative keys will get. Next to that, I also see this as a best practice.

But lets not waste too much time on this subject. Lets wait for others to request this feature (as I am not withhold having it already in action for a while now)

**Comment by samdark** [comment]
So far there were static use cases w/ class inheritance and it works well now.
