### ISSUE TITLE
Migrations - support for non integer primary keys

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#12767]
This is not an issue but a suggestion

It would be great if non integer primary keys can be created in this way

    $this->createTable('messages', [
        'message_id' => $this->string()->primaryKey(), // or maybe $this->primaryKey()->string()
    ]);

Instead of this:

    $this->createTable('messages', [
        'message_id' => $this->string()->notNull(),
        'PRIMARY KEY (message_id)',
    ]);

In general my recommendation for primary keys is if there is a type specification, the primary key is of the specified type. Thus eliminating the need of bigPrimaryKye which can be declared using $this->bigInteger()->primaryKey(). If the type is not specified the primary key defaults to integer as is now.

There is already core code in Yii2 which can take advantage of this - rbac migrations

This support should also be implemented and in "migration generation" for example

    yii migrate/create create_messages_table --fields="message_id:string:primaryKey"

**Comment by rob006** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/11638
