### ISSUE TITLE
Upgrade from 2.0.8 to 2.0.9 does not work 

### ISSUE THREAD

**Issue by saidbakr** [yiisoft/yii2#12761]
### What steps will reproduce the problem?
I followed the instruction of upgrade from 2.0.8 to 2.0.9 found [in this official document](https://github.com/yiisoft/yii2/blob/2.0.9/framework/UPGRADE.md)

### What is the expected result?
When typing `yii` command in the project root folder it should print out `This is Yii version 2.0.9.` in the first line.
### What do you get instead?
I get `This is Yii version 2.0.8.`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      |  5.6.15
| Operating system | Windows 10 Home 64 bit

**Comment by samdark** [comment]
What have you done exactly?

**Comment by saidbakr** [comment]
@samdark Exactly I have done the steps considered in [**this links**](https://github.com/yiisoft/yii2/blob/2.0.9/framework/UPGRADE.md), regarding upgrading from 2.0.8 to 2.0.9. In other words, I have run the following two commands:

```
php composer.phar self-update
php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"
```

**Comment by saidbakr** [comment]
I think that the following line **should be added** to the instructions:

`composer update yiisoft/yii2 yiisoft/yii2-composer bower-asset/jquery.inputmask`

**Comment by samdark** [comment]
Ah! That's what you mean...

**Comment by saidbakr** [comment]
@samdark I think that `php composer.php require "yiisoft/yii2:~2.0.9"` will replace the old version. For example, supposed a modification has been done to `SiteController` before upgrade, I think it should be lost after upgrade.

**Comment by samdark** [comment]
SiteController is your code, not the framework.
