### ISSUE TITLE
ActiveRecord: Autoincrement field not populated after save if field is not primary key

### ISSUE THREAD

**Issue by dtagliavini** [yiisoft/yii2#12768]
### What steps will reproduce the problem?
Create a new table (i'm using mysql 5.5.41)

```sql
CREATE TABLE `test` (
	`id` INT(11) NOT NULL,
	`autoinc` INT(11) NOT NULL AUTO_INCREMENT,
	`test` VARCHAR(50) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `autoinc` (`autoinc`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
```

in a controller action put this code:

```php
$model = new \app\models\Test();
$model->id = 2;
$model->test = 'prova';
$model->save();
return print_r($model->getAttributes());

```
execute this action

### What is the expected result?
I expected the autoinc field was populated with last insert id automatically

### What do you get instead?
empty $model->autoinc after save

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.4.38
| Operating system | CentOS release 6.5

**Comment by samdark** [comment]
The field is populated on the database side so you have to re-read the record with calling `->refresh()` in this case. It's not done by default since most of the time you already have all the data you've just saved. Won't be changed.
