### ISSUE TITLE
Component->trigger can't pass a data

### ISSUE THREAD

**Issue by anton-lyubch** [yiisoft/yii2#12766]
### What steps will reproduce the problem?
$component = new \yii\base\Component();
$component->on('test', function($event) {
    print_r($event->data);
}, ['foo'=>'123']);
$component->trigger('test', new \yii\base\Event(['data'=>['bar'=>'456']]));

### What is the expected result?
['foo'=>'123', 'bar'=>'456']

### What do you get instead?
['foo'=>'123']

### Additional info
I think the developer should may pass an additional parameters via `trigger` too. Not only via `on`.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.5.9
| Operating system | Ubuntu

**Comment by klimov-paul** [comment]
This is expected. `Event::data` is always overridden by the values from event handler.
It is clearly documented:
https://github.com/yiisoft/yii2/blob/master/framework/base/Event.php#L45-L49

**Comment by Jafarili** [comment]
@klimov-paul but it's a silly behavior!
we should have this ability to pass data when we want to trigger an event
