### ISSUE TITLE
\yii\web\User::can() and guest

### ISSUE THREAD

**Issue by genichyar** [yiisoft/yii2#12771]
Using \yii\web\User::can() for guest always returns false for all my cases. But it checks permissions and executes all relative bizrules. 

Why does \yii\web\User::can() not return false for guest default without any checks?

**Comment by genichyar** [comment]
Problem can be viewed at another point.

Why does \yii\rbac\PhpManager::checkAccess() execute \yii\rbac\PhpManager::checkAccessRecursive even if assignments and defaultRoles are empty?

**Comment by samdark** [comment]
I guess it could be improved. Need to review code though.

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/5795b3937eab3764a79e180f259dbabd6f655dad
