### ISSUE TITLE
YII2 mongodb Search optimization

### ISSUE THREAD

**Issue by EsoftsLimited** [yiisoft/yii2#12776]
### What steps will reproduce the problem?
I have inserted 20,million record in my mongidb and mysql application, and i have generated a crud view from the collection model, when i search for any record, it takes about 72 & 68 seconds respectively on the two databases to return results (am suing `Yii::getLogger()->getElapsedTime()`) , this is on my localhost and i feel that is too much a wait;
The table is simple with people names phone and emails

### What is the expected result?
How should i optimize this to ensure i get results in millisecond 
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.0
| Operating system | Ubuntu 16.04

**Comment by dynasource** [comment]
why do you think this is a Yii2 issue?
