### ISSUE TITLE
Wrap checkbox of CheckBoxColumn with <label> ?

### ISSUE THREAD

**Issue by prabowomurti** [yiisoft/yii2#12777]
Is it possible to wrap the input checkbox of `\yii\grid\CheckBoxColumn` with `<label>` tag? My aim is to make the checkbox easier to check.

My current (and dirty) method is to modify the `<td>`

```php
[
    'class' => 'yii\grid\CheckBoxColumn',
    'contentOptions' => [
        'onclick' => 'this.getElementsByTagName("input")[0].checked = ! this.getElementsByTagName("input")[0].checked;',
        'style' => 'cursor: pointer'
    ],
],
```

Preview : clicked, but can not check
![unchecked](https://cloud.githubusercontent.com/assets/38052/19509681/2709f8f8-960a-11e6-80a3-51c279dcb62a.png)

Clicked inside the td, checked
![checked](https://cloud.githubusercontent.com/assets/38052/19509620/d259e7fa-9609-11e6-9f3e-f621606434c4.png)

**Comment by dynasource** [comment]
its not a helpdesk over here
Use the $content of Column for custimization (which you could have found yourself if you look in the code https://github.com/yiisoft/yii2/blob/master/framework/grid/Column.php#L40)
