### ISSUE TITLE
Failed to create the object for unknown reason.

### ISSUE THREAD

**Issue by psfpro** [yiisoft/yii2#12773]
I'm got Exception 'Failed to create the object for unknown reason.'
```
$model->save() == false
and
$model->hasErrors() == false
```
In what situations can it be?
This is magic of Yii2? We don't know what happend

**Comment by pstddc** [comment]
look `beforeValidate` should return true if valid

**Comment by MKiselev** [comment]
@psfpro this exception generated in one place: https://github.com/yiisoft/yii2/blob/495553616dc41b9a5db141931388d9502d19eb13/framework/rest/CreateAction.php#L56

Please ensure what you model has rules() for attributes required by DB and ```Yii::$app->getRequest()->getBodyParams()``` has model attributes.

For debug you may dump $model after load in yii/rest/CreateAction.php
