### ISSUE TITLE
ActiveForm afterValidate doesn't work

### ISSUE THREAD

**Issue by devlat** [yiisoft/yii2#12783]
afterValidate doesn't work. But beforeValidate is work. Below my code:
```
$('.send-msg-form').on('afterValidate', function(event, message){
   console.log('DONE');
});
```
When I use beforeValidate - console.log('DONE') is work, but with afterValidate he don't work. Maybe I don't know something, I'm new in Yii2. I want to cancel form submit after validating through this events, it's correct?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      |7.0
| Operating system | Ubuntu 16.04

**Comment by devlat** [comment]
beforeSubmit doesn't work too...

**Comment by dynasource** [comment]
plz provide your shortest HTML+JS code in which the events do not work

**Comment by devlat** [comment]
`<?php $form = ActiveForm::begin([
            'id' => 'send-message-form',
            'options' => ['class' => 'form-vertical send-msg-form'],
            'action' => 'index.php?r=chat/send-msg',
            'enableAjaxValidation' => true,
        ]);
        ?>

        <?= $form->field($model, 'message'); ?>

        <?php ActiveForm::end() ?>`

That is my view with form. Below is js code. beforeValidate is work well done, beforeSubmit don't. Maybe I doing mistake?
`$('.send-msg-form').on('beforeValidate', function() {
    console.log(2);
});

$('.send-msg-form').on('beforeSubmit', function () {
    console.log(1);
});`

**Comment by dynasource** [comment]
'beforeSubmit event is triggered before submitting the form after all validations have passed.'

are you sure your form is validating successfully?

**Comment by devlat** [comment]
Clients validations? Yes. After validating Yii2 send data to server(controllers action is executes).

**Comment by devlat** [comment]
Thank for response. All work well. I'm just wroted wrong code with a validation. I'm apologize for this issue. Further will write same questions on Yii forums. Sorry for my english.
