### ISSUE TITLE
DB LIMIT  and ORDER BY in UPDATE 

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [yiisoft/yii2#12780]
New feature, adding the possibility to use LIMIT and ORDER BY in data update
example:
UPDATE table SET checked = 1 WHERE field = 'xxx' LIMIT 1
UPDATE table SET checked = 1 WHERE field = 'xxx' LIMIT 1 ORDER BY type DESC

$query = $db->createCommand()->update('xxx', [
    'id' => 55,
    ]);
$query->limit(1);
$query->orderBy(['type ' => SORT_DESC]);
$query->execute();

**Comment by dynasource** [comment]
relates #12729

**Comment by SilverFire** [comment]
Duplicates #7606
