### ISSUE TITLE
Refactoring of /caching/Dependency

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#12798]
After looking at the dependency architecture for while now, it became clear that a lot of refactoring is still left to do. Duplicate code can be removed, function names can be improved, docs can be added and so on.

Examples of duplicate code:
- https://github.com/yiisoft/yii2/blob/master/framework/caching/Dependency.php#L47
- https://github.com/yiisoft/yii2/blob/master/framework/caching/Dependency.php#L65

Examples of function names:
1. one would 'evaluateDependency' expect to give a boolean, as that is the result of an evoluation. This is confusing as the function is simply a setter
  https://github.com/yiisoft/yii2/blob/master/framework/caching/Dependency.php#L45
2. the naming of 'getHasChanged' does return a boolean. If thats the case you would expect it to be called 'isChanged' or 'isCacheChanged'. Its also not named to be used as a magic getter because of its required argument.
3. 'generateDependencyData'. This is too vague. What is it doing? It comes back in every Dependency class. The objective is stated 'to determine if dependency has been changed'. Then this method should at least cover elements of this objective.

This is just a first review of the architecture so I can imagine there are more opportunities for improvement. Its possible to improve the architecture for 2.0.10 with deprecated functions.

I am willing to do PRs for it.

**Comment by samdark** [comment]
Good observations. I'm for fixing these.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
