### ISSUE TITLE
Trying to get property of non-object when i open index.php

### ISSUE THREAD

**Issue by IRONIS** [yiisoft/yii2#12794]
When i try to open index.php i am catch 500 error. In log file i see "Trying to get property of non-object in /var/www/lightsoft/site-com/vendor/yiisoft/yii2/log/Dispatcher.php on line 186"

Why that happened?

| Q | A |
| --- | --- |
| Yii version | 2.0.10 |
| PHP version | 7 |
| Operating system | Ubuntu 16.04 lts |

**Comment by Alex-Code** [comment]
I'd say it's a config error.
What's the log section of your config?

**Comment by cebe** [comment]
This can happen if the instantiation of a log target fails and while trying to log that failure other targets are not instantiated yet.

**Comment by samdark** [comment]
Do you have a stacktrace?

**Comment by samdark** [comment]
What's your config for log component?

**Comment by IRONIS** [comment]
Thank you! You were right, config section was wrong.

**Comment by samdark** [comment]
@cebe ?
