### ISSUE TITLE
problem with relation class after upload yii2 on shared hosting

### ISSUE THREAD

**Issue by hmkhafan** [yiisoft/yii2#12808]
i have relation database that when i upload my site on cpanel it's not working and return

> PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'common\models\SubCategoryBook' not found' 

in /home/nosan/site/common/models/Book.php:44

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

SubCategoryBook class is in common\models but it seem's not working.

**Comment by dynasource** [comment]
As this is a fatal PHP error on one of your own classes, you have to look for the solution out of the scope of Yii:
* does your class common\models\SubCategoryBook actually exist?
* is it in common/models path?
* does it have a namespace common\models?
* does it have a base id case sensitve SubCategoryBook?
