### ISSUE TITLE
Modules not persist ErrorHandler Configuration

### ISSUE THREAD

**Issue by rfiedler** [yiisoft/yii2#12805]
### What steps will reproduce the problem?                       
1- Main App Error Handler Config:

` 'errorHandler' => ['errorAction' => 'site/error']`

2- Module Error Handler Config:

```
public function init() { 

        $this->set('errorHandler', [
            'class' => 'yii\web\ErrorHandler',
            'errorAction' => $this->id . '/default/error',
        ]);

}
```

3- Force any error inside the module, like Exception, HttpException ...

### What is the expected result?

Module Application redirects to **"mymodule/default/error"**

### What do you get instead?

Application redirects to **"site/error"**

### Additional info

In **Module** DefautController -> actionIndex

The command **$this->module->components** return right configuration:

```
array(1) {
  ["errorHandler"]=>
  array(2) {
    ["class"]=>
    string(20) "yii\web\ErrorHandler"
    ["errorAction"]=>
    string(24) "mymodule/default/error"
  }
}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      |5.5.9-1ubuntu4.17
| Operating system | Server: Apache/2.4.7 (Ubuntu)

**Comment by dynasource** [comment]
if you want your Module to override the base Application errorHandler, you really have to override it ;) and not by adding a component with a similar name to your module.

You should use this code:
```php
 $this->module->set('errorHandler', [
            'class' => 'yii\web\ErrorHandler',
            'errorAction' => $this->id . '/default/error',
        ]);

```

or more stable (if you are working with submodules):

```php
 Yii::$app->set('errorHandler', [
            'class' => 'yii\web\ErrorHandler',
            'errorAction' => $this->id . '/default/error',
        ]);
```

**Comment by rfiedler** [comment]
Hi , I try your suggestion but nothing´s works .

In my Module.php  on init function, i try:

```

 Yii::$app->set('errorHandler', [
            'class' => 'yii\web\ErrorHandler',
            'errorAction' => $this->id . '/default/error',
        ]);

```
 
and i try:
```
 $this->module->set('errorHandler', [
            'class' => 'yii\web\ErrorHandler',
            'errorAction' => $this->id . '/default/error',
        ]);

```

Both set properly component errorHandler with **"mymodule/default/error"**  but when Errorhandler component run , **"$this->errorAction"** is **"site/error"** in **all** cases. To test this i´m change line 93 as shown in the code below:

**ErrorHandler.php Line:93**

From
` $result = Yii::$app->runAction($this->errorAction);`

To
`$result = Yii::$app->runAction(Yii::$app->errorHandler->errorAction);`


Everythings Works !

@samdark see this, its a bug ?

**Comment by dynasource** [comment]
try something with '//' like the following:
* $app->errorHandler->errorAction = '//error/default/index';

**Comment by rfiedler** [comment]
@dynasource  not work too.

```
 Yii::$app->set('errorHandler', [
            'class' => 'yii\web\ErrorHandler',
            'errorAction' => "//".$this->id . '/default/error',
        ]);
```

I´m keep with old solution for now until @samdark analise **ErrorHandler.php Line:93** when module´s set´s new errorHandler configuration using  **Yii::$app->set** method.

**Comment by dynasource** [comment]
This is not an issue for the issue tracker. This is something you can debug yourself.

To give you more clues: it all depends on where your error is occurring. If your error occurs before 'beforeAction', your setting will never be loaded.

To give you an example which works: a bootstrapped ErrorModule, to be loaded in $app->bootstrap:
```php
class ErrorModule extends \dmn\yii2\app\module\Module implements \yii\base\BootstrapInterface
{
    /**
     *
     * @param \yii\web\Application $app
     */
    public function bootstrap($app)
    {
        $app->errorHandler->errorAction = '//error/default/index';
    }
}
```
