### ISSUE TITLE
ImageValidator and svg files

### ISSUE THREAD

**Issue by werew01f** [yiisoft/yii2#12801]
### What steps will reproduce the problem?
ImageValidator validateImage always fail for svg file
### What is the expected result?
SVG is scalable image type, but structured as XML.
I think that image validator should correct validate SVG graphic files.
### What do you get instead?
Problem in https://github.com/yiisoft/yii2/blob/master/framework/validators/ImageValidator.php#L133
getimagesize always fails for svg.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10?
| PHP version      | 7.0
| Operating system | Ubuntu 16.04

**Comment by Alex-Code** [comment]
What are you wanting to validate?

**Comment by samdark** [comment]
SVGs aren't really images so what you should validate is probably XML via DTD.

**Comment by werew01f** [comment]
i want use imageValidation for png, jpeg and other image files such as svg.
i know thats SVG aren't images at all, but its kind of image-type file, so i think that imageValidation should forks for it.
Just valid svg or not.

**Comment by rob006** [comment]
https://grepular.com/Scalable_Vector_Graphics_and_XSS

**Comment by samdark** [comment]
Yes, uploaded SVGs should be validated and probably sanitized. Not sure it should be part of the core image validator though...

**Comment by rob006** [comment]
Treating svg like regular images will create lot of problems and potential security issues. If I allow users to upload images I would not expect that I need to protect against XSS in uploaded files.

**Comment by samdark** [comment]
Agree. I'd prefer it as a separate component.
