### ISSUE TITLE
После 2.0.10 сломалась защита от двойной отправки формы

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#12814]
Задача проста. Нужно отключить кнопку сабмит во избежание двойного нажатия.
До 2.0.10 работал следующий код.
```
// дизейблим кнопку после клика
$('.jsBeforeSubmitFormBtn').click(function(){
        var $this = $(this);
        setTimeout(function(){
            $this.attr('disabled', 'disabled');
        }, 1);
    });
// если ошибки при валидации, обратно энейблим.. если все без ошибок все нормально отправлялось
    $('.jsBeforeSubmitFormBtn').parents('form').on('afterValidate', function (event, messages, errorAttributes) {
        if(errorAttributes.length > 0) {
            $('.jsBeforeSubmitFormBtn').removeAttr('disabled');
        }
    });
```
Вижу в чейнжлогах большую работу над yii.activeForm.js. Я так понимаю раньше вы делали submit, теперь вы видимо "продолжаете событие" ранее инициированное пользователем. То есть кликаете в мою задизейбленную кнопку - соответственно отправки формы не происходит. 

Вопрос... как это возможно реализовать теперь? Какие вы можете дать рекомендации?

ЗЫ: Пробовал на момент её энейблить. но получается некрасивый лаг...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |
| Operating system |
|Browser| Chrome|

**Comment by samdark** [comment]
Duplicated of https://github.com/yiisoft/yii2/issues/12809
