### ISSUE TITLE
actions function how config callback function?

### ISSUE THREAD

**Issue by zplzpl** [yiisoft/yii2#12818]
### What steps will reproduce the problem?
```
    public function actions()
    {
        return [
            'importFile' => [
                'class' => 'backend\components\uploader\actions\UploadAction',
                'fileStorage' => 'fileStorage',
                'multiple' => false,
               
               /*like this*/
                'callback' => function(&$output){
                        $output["test"] = "hello";
                 }

                'validationRules' => [
                ]
            ]
        ];
    }
```

```
class UploadAction  extends Action
{
           public function run(){
                   $output = array();
                   $this->callback($output);
                   return $output;
            }
}
```

### What is the expected result?

print $output :
`$output = array("test"=>"hello")`

### What do you get instead?

Calling unknown method callback()

### Additional info

Or other ways to achieve?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version       |5.5.17
| Operating system  |window 7

**Comment by samdark** [comment]
It's not supported currently.

**Comment by dynasource** [comment]
the $callback in your example is too vague to be adopted in the general Action class:
* How should it be named?
* Which parameters should it get?
* When should it be called?

With respect to your specific usecase. I see that you've already done an implementation with UploadAction. If you want to have a callback, you can set it yourself there. 

```php
class UploadAction  extends Action
{
	public $myDesiredCallback;

	public function run(){
		$output = array();
		call_user_func($this->myDesiredCallback,$output);
		return $output;
	}
}
```

but now I am writing your code ;)
