### ISSUE TITLE
Error handling for fatal errors suppressed by @

### ISSUE THREAD

**Issue by laszlovl** [yiisoft/yii2#12811]
I just spent a while tracing a problem where Yii generated a blank page, without any indication about the error that occured. The cause is as follows:

* An E_RECOVERABLE_ERROR error occured during session_regenerate_id()
* Because web/Session::regenerateID() uses the @ operator in the call to session_regenerate_id, the level reported by error_reporting() is 0 during the rest of the call stack (http://php.net/manual/en/function.set-error-handler.php)
* 0 doesn't match ErrorHandler's `if (error_reporting() & $code)`, which means it falls back to `return false`
* Because of the `return false`, the error is delegated to PHP's default error handler (http://php.net/manual/en/function.set-error-handler.php), which means to abort the application (http://php.net/manual/en/errorfunc.constants.php). Usually this happens quietly, unless you've enabled `display_errors`.

Ref: https://3v4l.org/GcklS

This behavior was introduced in 6709154792bcced1381cdd6e4f4f5ebf9724cbc0, which doesn't provide any background. Perhaps @klimov-paul recalls the details?

I think ErrorHandler::handleError() should always handle "aborting" errors (E_ERROR, E_CORE_ERROR, E_COMPILE_ERROR , E_USER_ERROR, E_RECOVERABLE_ERROR), regardless of the value of `error_reporting()`. Otherwise, users will have no way to debug errors in @ calls, which are used by Yii itself.

This shouldn't be a problem for backwards compatibility, because these errors will abort the application either way - with or without this change. Having an error in your logs when this happens is always better than it happening quietly. But if you do worry about it, this behavior could be enabled for YII_ENV_TEST only.

**Comment by laszlovl** [comment]
Correction: `set_error_handler` doesn't apply to fatal errors like E_ERROR anyway, these are handled correctly by `ErrorHandler` regardless of the `error_reporting()` level.

The change would only apply to  E_USER_ERROR and E_RECOVERABLE_ERROR then.

**Comment by klimov-paul** [comment]
> This behavior was introduced in 6709154, which doesn't provide any background. Perhaps @klimov-paul recalls the details?

This change was made to solve issue #3459 (PR #4750), allowing `error_get_last()` function to return some value.

> Because of the return false, the error is delegated to PHP's default error handler

There should not be any problem. Default PHP error handler should respect `error_reporting()` value. e.g. if function call prefixed with `@` it should not display any error.

**Comment by klimov-paul** [comment]
Unable to reproduce. Native PHP error handler processes errors correctly.
Following code:

```php

class SiteController extends \yii\web\Controller
{
    public function actionTest()
    {
        error_reporting(E_ALL);
        ini_set('display_errors', 'on');

        $callback = function() {
            trigger_error('My error message');
            return false;
        };

        session_set_save_handler($callback, $callback, $callback, $callback, $callback, $callback);

        @session_start();

        $lastError = error_get_last();
        if (empty($lastError)) {
            return 'Success';
        }
        return 'Success. Last error = ' . $lastError['message'];
    }
}
```

Outpust:

```
Success. Last error = My error message
```

**Comment by laszlovl** [comment]
Let me try to give a simpler description. Take the following [example](https://3v4l.org/3ZYTK). (Not a hypothetical case - it can happen for example at https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L284)

```php
@trigger_error('error', E_USER_ERROR);

echo 'Never reached';
```

This aborts script execution (because the error handler returns false) but it's not actually turned into an `ErrorException` by `ErrorHandler` (because of the @ operator). This means you get a blank page with no indication of what happened.

**Comment by dynasource** [comment]
http://php.net/manual/en/language.operators.errorcontrol.php
'If you have set a custom error handler function with set_error_handler() then it will still get called, but this custom error handler can (and should) call error_reporting() which will return 0 when the call that triggered the error was preceded by an @.'
