### ISSUE TITLE
Passing php variables to \yii\web\JsExpression()

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#12823]
Hi,

I'm trying to use `\yii\web\JsExpression()` with highcharts and building a custom tooltip, I'm struggling to be able to pass PHP parameters to the function though. I have seen https://github.com/yiisoft/yii2/issues/9609. Is there a way to pass in a php variable so it can be used with `\yii\web\JsExpression()`

    <?php
    $var = 'hello';
    'formatter' => \yii\web\JsExpression('function(){
           return {$var};
     }')

**Comment by dynasource** [comment]
doesnt the following fulfill your needs?:
```php
<?php
$var = 'hello';
'formatter' => \yii\web\JsExpression('function(){
       return "'.$var.'";
 }')
```

**Comment by samdark** [comment]
It should be properly escaped or whitelisted though. Else you'll get into big trouble.

**Comment by cebe** [comment]
it should be done like this:

```php
<?php
$var = 'hello';
'formatter' => \yii\web\JsExpression('function(){
       return ' . \yii\helpers\Json::htmlEncode($var) . ';
 }')
```
