### ISSUE TITLE
Enhancement: add new function to yii2 exceptions

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#12825]
Very often we come across simple lines where we have to throw an exception if the precedent condition is not true.

for example:

```php
    public function actionView($id)
    {
        $model = User::find()->where(['id' => $id])->one();

        if($model) {
                throw new NotFoundHttpException('The user does not exist');
        }
        ...
    }
```

But i think it would be better if we could throw the exception on the same line as the query.
Example:

```php
    public function actionView($id)
    {
        $model = User::find()->where(['id' => $id])->one() 
        or NotFoundHttpException::throw('The user does not exist');
        ...
    }
```

**Comment by samdark** [comment]
It's less clear as to me. Not going to change framework code style in this regard.

Thanks for opinion though.

**Comment by dynasource** [comment]
thats is interesting. Havent seen this approach yet.

**Comment by klimov-paul** [comment]
It is sugnificant where exception is thrown. Exception object stores the stacktrace to the line, where it was thrown.
If `throw` operator will be moved inside static method, this stacktrace will show incorrect path, eliminating its benefit.

**Comment by dynasource** [comment]
ahh didnt see that change too. I meant the 'or' logical operator.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L19
