### ISSUE TITLE
Enhancement: add homeUrl to yii\web\User

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/yii2#12827]
It would be good if you could to specify a different home URL for logged in users.
### What is the expected result?
For logged in users, when I call `Controller::goHome()` or `Controller::goBack()` (when `returnUrl` is not setted) I would want to redirect users on a special account page, something like a dashboard.
And for detecting the home page in these calls use:
`Yii::$app->getUser()->getIsGuest() ? Yii::$app->getHomeUrl() : Yii::$app->getUser()->getHomeUrl();`
This will be useful for redirecting users after sign up or log in.
### What do you get instead?
Now it redirects users to the website home page which it gets from `Yii::$app->getHomeUrl()`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by mdmunir** [comment]
add column url to your user table and call `Yii::$app->user->identity->url`

**Comment by dynasource** [comment]
this is a common usecase. However, setting meta data such as an 'url' should not be defined in the core User class. 

A better alternative is to stay closer to the original homeUrl an the 'request logic'. The way I have implemented is by using different application tiers for different area's. If you are in the 'userarea' you are implementing a user tier in which you can set this $homeUrl by default arleady.

For those not having such an advanced implementation, enabling a $callback for homeUrl could be useful.

**Comment by Tigrov** [comment]
@dynasource could you describe more about how you implement this in your application.

**Comment by dynasource** [comment]
please take a look at this discussion https://github.com/yiisoft/yii2/issues/4771

I have 3 applications per platform:
* backend
* visitorend
* userend

You can define the homeUrl per application.

**Comment by Tigrov** [comment]
@dynasource thanks for your implementation. But I think that in my case there is no reason to devide application on 3 parts. I use 2 only backend and frontend.

As you mentioned before:
> For those not having such an advanced implementation, enabling a $callback for homeUrl could be useful.

For me it seems a good solution.

@cebe what do you think about to enabling a $callback for `Yii::$app->homeUrl`?

**Comment by Tigrov** [comment]
Another solution to change `Yii::$app->homeUrl` on event `User::EVENT_AFTER_LOGIN`.
