### ISSUE TITLE
session_regenerate_id(): Session object destruction failed. ID: user (path: )

### ISSUE THREAD

**Issue by EvgenyOrekhov** [yiisoft/yii2#12821]
`session_regenerate_id(): Session object destruction failed. ID: user (path: )` after upgrade to 2.0.10.
### What steps will reproduce the problem?
1. Add this component config:
   
   ```
   'session' => [
       'class' => 'yii\redis\Session',
       'redis' => [
           'hostname' => 'localhost',
       ],
       'timeout' => 10,
   ],
   ```
2. Log in to the application.
3. Wait 10 seconds.
4. Refresh the application page.
### What is the expected result?

No warning.
### What do you get instead?

PHP Warning – yii\base\ErrorException

session_regenerate_id(): Session object destruction failed. ID: user (path: )
1. in vendor/yiisoft/yii2/web/Session.php at line 282

``` php
     * Please refer to <http://php.net/session_regenerate_id> for more details.
     * @param boolean $deleteOldSession Whether to delete the old associated session file or not.
     */
    public function regenerateID($deleteOldSession = false)
    {
        if ($this->getIsActive()) {
            // add @ to inhibit possible warning due to race condition
            // https://github.com/yiisoft/yii2/pull/1812
            if (YII_DEBUG && !headers_sent()) {
                session_regenerate_id($deleteOldSession); // <-- line 282
            } else {
                @session_regenerate_id($deleteOldSession);
            }
        }
    }
```
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.10 |
| PHP version | 7.0.12 |
| Operating system | Alpine Linux 3.4 |

**Comment by samdark** [comment]
Yes, the behavior in debug mode is different in 2.0.10. It doesn't ignore errors anymore. What should be fixed is the cause of this error.

**Comment by dynasource** [comment]
this one is not particularly connected to redis

Im getting it too after refreshing with F5 too fast with the debug tool bar on.

**Comment by KunalAwasthiKooky** [comment]
the issue can be reproduced by triggering an ajax call every second then trying login or signup with Yii 2 user identity class.

**Comment by samdark** [comment]
@KunalAwasthiKooky what session backend is used?

**Comment by EvgenyOrekhov** [comment]
I am no longer interested in this. Feel free to reopen if needed.

**Comment by KunalAwasthiKooky** [comment]
@samdark Sorry for late reply

**Comment by KunalAwasthiKooky** [comment]
@samdark sorry for late reply, we had an ajax call on interval at checkout page to check stock validity of products, we had a popup for user sign-in but when user tries to sign-in we got `session_regenerate_id(): Session object destruction failed. ID: user (path: )` error, maybe it was an issue on local env, feel free to close this from my side.
