### ISSUE TITLE
Gridview FilterUrl does ignores # link in URL

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#12836]
### What steps will reproduce the problem?

Create a Gridview Filter Url that should jump to the gridview inside of the page by appending the `#` id of the gridview:

```php
	<?= GridView::widget([
		'id' => 'some-grid',
		'dataProvider' => $dataProvider,
		'filterModel' => $filterModel,
		'filterUrl' => Url::current(['#' => 'some-grid']),
		'columns' => [
// ...
		],
	]); ?>
```

### What is the expected result?

After filtering the URL should end with `#some-grid`.

### What do you get instead?

No `#` part of the URL.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by arogachev** [comment]
Fully fixed in #13230.

**Comment by cebe** [comment]
@arogachev thanks for taking care of this, seems my JS skills are not up to date...

**Comment by arogachev** [comment]
@cebe No problem. We all make mistakes sometimes.
