### ISSUE TITLE
YII_ENV_TEST and renewing / regenerateing the session id

### ISSUE THREAD

**Issue by wetzesa** [yiisoft/yii2#12835]
We have a problem with the renewing / regenerateing of session id's in case of YII_ENV_TEST.

We use the session id as additional information for the backend system to recognize user's which have pass the 2 factor login successful.

On the production and dev env all is fine. Only on our test and QA systems we have many trouble.

The question is why in the class yii/web/User.php:switchIdentity the regenerateID method only is called if the ENV it is not YII_ENV_TEST.

Additional the concept about the ENVs handling is not clear. Sometimes in the code there are if (YII_ENV_TEST) or if (!YII_ENV_TEST) is implemented but for DEV and PROD are no implementations or else if cases.

Can you please explain how is the concept and why it is implemented like it is?

We use actually Yii 2.0.7 and do now the "update" to 2.0.10
Apache 2.4.16 with PHP 5.5.14 on SLES 12 SP1.

Regarding tickets:
https://github.com/yiisoft/yii2/issues/2664
https://github.com/yiisoft/yii2/issues/2253

**Comment by wetzesa** [comment]
Short question - how is the status of discussion?

**Comment by dynasource** [comment]
can you find your answer in https://github.com/yiisoft/yii2/issues/2664?

**Comment by dynasource** [comment]
the answer is inside here https://github.com/yiisoft/yii2/issues/130#issuecomment-19931343
