### ISSUE TITLE
Migrate redo RBAC problem 

### ISSUE THREAD

**Issue by izac1** [yiisoft/yii2#12838]
### What steps will reproduce the problem?

first init rbac migrate 
`php yii migrate --migrationPath=@yii/rbac/migrations`
then (if you have other migrate) you need redo all migrate 
`php yii migrate\redo 10`
and you have error 

>  failed to open stream: No such file or directory rbac_init_migrations
> in your project , but you dont have this file in you project migrate folder , have this migrate in @yii/rbac/migrations folder. But yii dont detect this. 
> ### What is the expected result?
> 
> Redo all migrations and redo rbac migrations in folder @yii/rbac/migrations with out error.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.6 |
| PHP version | 5.6 |
| Operating system | Debian x64 |

**Comment by mdmunir** [comment]
https://github.com/yiisoft/yii2/issues/9698
