### ISSUE TITLE
Хочу предложить фичу-трейт

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#12849]
Недавно сделал трейт, который я начал использовать просто повально везде... мне кажется он очень удобен

Очень часто возникает ситуация, когда требуется несколько раз дергать один и тот же метод, но хочется что бы объект этого метода оперативно кешровал данные у себя. Достичь этого можно например создав приватную переменную для кеширования.

Недавно сделал вот такой трейт. Да есть к чему стремиться, но он вот такой:
```php
/**
 * Кешер данных модели
 * Позволяет сократить количество шаблонного кода с добавлением приватных
 * переменых кеша
 */
trait ModelCacheTrait
{

    private $_cache = [];

    /**
     * Получить данные с кешированием
     * @param string $key ключ кеша
     * @param callable $callback коллбэк с кодом получения данных
     * @return mixed данные
     */
    protected function cachedGet($key, $callback)
    {
        // Через isset и null не получится!!! нужно знать есть ли ключ в массиве
        if (!array_key_exists($key, $this->_cache)) {
            $this->_cache[$key] = call_user_func($callback);
        }
        return $this->_cache[$key];
    }
}

// Использование
class BusinessModel
{
    use \app\ModelCacheTrait;

    public function makeRandomPrecurrentDate()
    {
        $currentTime = strtotime($this->makeCurrentDate());
// БИЗНЕС ЛОГИКА
    }

    public function makeCurrentDate()
    {
        return $this->cachedGet(__METHOD__, function(){
            $lastHalf = time(); // БИЗНЕС ЛОГИКА, возможно придется дергать БД, упростил...
            return date('c', $lastHalf);
        });
    }
}
```

Ну вот... Просто вот такое предложение. Может возможно его как-то подтюнить, шобы сделать удобнее в использовании и включить в либы фреймворка...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by samdark** [comment]
Дубль https://github.com/yiisoft/yii2/issues/12312
