### ISSUE TITLE
Creating ActiveRecord instances

### ISSUE THREAD

**Issue by nanodesu88** [yiisoft/yii2#12843]
Hey!
Why we still needs to create instances instead of using a ```BaseActiveRecord::singleton``` (like yii1 ```ActiveRecord::model```)?
Constructions like https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRelationTrait.php#L179 is refactoring unfriendly and creates unnecessary entities.

Bad english, sry.

**Comment by dynasource** [comment]
because the className is packed in a variable over there, enabling the whole statement to be in 1 line

**Comment by nanodesu88** [comment]
```php
ActiveRecordChild::instance()
```
or
```php
BaseActiveRecord::instance($className)
```
?

**Comment by dynasource** [comment]
must say that:
```php
BaseActiveRecord::instance($this->modelClass)
```

is more elegant than:
```php
(new $this->modelClass)
```

What exactly is your reason to enable this? Can you elaborate?

**Comment by nanodesu88** [comment]
```php
(new $this->modelClass)
```
creates new unnecessary instance each time, when we just need get basic class-based information like relation-info, labels, etc

**Comment by samdark** [comment]
It allows us to have this information instance-based. For example, labels now could depend on model attributes etc.
