### ISSUE TITLE
How does the caching DbDependency work exactly?

### ISSUE THREAD

**Issue by cyphix333** [yiisoft/yii2#12845]
I'm starting to use the built in query caching such as:

`$sql = $db->createCommand('SELECT * FROM my_table WHERE something=1')->cache(3600)->queryAll();`

Now I tried to find out how to delete the cache for this item once the database info has been changed, as I understand you can't do it with the normal [delete](http://www.yiiframework.com/doc-2.0/yii-caching-cache.html#delete()-detail) method as you need to provide a key, which you obviously don't use with query caching.

Then I thought about using the [DbDependency](http://www.yiiframework.com/doc-2.0/yii-caching-dbdependency.html), however unsure how this is beneficial.

How does it _know_ the data has changed and needs to invalidate the cache item? Wouldn't it need to run the query to find out and thus defeat the purpose of caching in the first place!?

I am I better off using something like [TagDependency](http://www.yiiframework.com/doc-2.0/yii-caching-tagdependency.html) instead so that when I change the data I can then just invalidate the cache myself?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.5.28
| Operating system | Win7 / CentOS

**Comment by cyphix333** [comment]
@samdark I am trying to post on the forum but it's not sending me my password reset email; I have tried multiple times.

**Comment by cebe** [comment]
@cyphix333 ping me on [IRC](http://www.yiiframework.com/chat/) (#yii on freenode), to fix your forum login.
