### ISSUE TITLE
ActiveQuery doesn't typecasting columns if asArray is true

### ISSUE THREAD

**Issue by MaXL-ru** [yiisoft/yii2#12841]
ActiveQuery doesn't typecasting columns if asArray is true.

```php
var_dump(Model::find()->asArray(true)->all());
var_dump(Model::find()->all());
```

```
array(1) {
  [0]=>
  array(5) {
    ["id"] => string(1) "7"
    ["name"] => string(9) "TEST111"
  }
}

array(1) {
  [0]=>
    ...
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(5) {
      ["id"] => int(7)
      ["name"] => string(9) "TEST111"
    }
    ...
}
```

For `asArray(true)` id column is `string` but for `asArray(false)` id is `int`.

`createModels` method in `ActiveQueryTrait` doesn't use `ColumnSchema`.

Is it bug or we must add info about that to docs ?

**Comment by dynasource** [comment]
well spotted. It would be better to have this more consistent. How hard do you think it would be to fix this?

**Comment by klimov-paul** [comment]
Duplicates #9329
