### ISSUE TITLE
How to get action back in Behavior content?

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#12842]
```
public function events()
    {
        return [
            Controller::EVENT_BEFORE_ACTION => 'beforeAction',
            Controller::EVENT_AFTER_ACTION => 'afterAction',
        ];
    }


public function afterAction($event)
    {
        $actionId = $event->action->id;

       //I'm going to intercept the content of the browser after the execution of the action.
        return $event->isValid;
    }
```

My purpose is to record the running time of each action to start execution and end the execution, but I also want to record the contents of the action returned to the user. I don't know what method to get here, please help me!

**Comment by dynasource** [comment]
you are aware of the fact that this is a issue tracker and the Yii forum is for questions?

For record of running times, you should use class level event handlers in your bootstrap.php
http://www.yiiframework.com/doc-2.0/guide-concept-events.html#class-level-event-handlers

If you want to know which event handlers exist for your usecase, you should search in for '->trigger' in the Yii folder.

**Comment by xiaoxing598** [comment]
My goal is to want to be in `Controller:: EVENT_AFTER_ACTION` event processing to get the contents of the current action returned to the browser.
I do have the definition of such a behavior:
`class MonitorBehavior extends Behavior{}`

**Comment by dynasource** [comment]
whats wrong with https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L297

**Comment by xiaoxing598** [comment]
Thank you very much!
