### ISSUE TITLE
XmlResponseFormatter outputs "false" as empty string

### ISSUE THREAD

**Issue by kavolorn** [yiisoft/yii2#12856]
### What steps will reproduce the problem?

Use boolean value in return from a rest controller.

```php
return [
    'success' => false,
    'data' => [
        'reason' => 'No authentication configured.',
    ]
];
```
### What is the expected result?

```xml
<response>
    <success>0</success>
    <data>
        <reason>No authentication configured.</reason>
    </data>
</response>
```

### What do you get instead?

In case of true value I see 1 returned. I expected to see 0 returned for false. Would it be more correct or empty value is correct enough?

I understand that PHP itself converts false to an empty string. I'm trying to question from the XML consumer side what is the desired output format.

```xml
<response>
    <success></success>
    <data>
        <reason>No authentication configured.</reason>
    </data>
</response>
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      | any
| Operating system | any

**Comment by nanodesu88** [comment]
Whats about something like ```php $child->appendChild(new DOMText((string) ($value === false ? '0' : $value)));``` here: ?https://github.com/yiisoft/yii2/blob/333c4b6b4f4c3d33a30c8380d2da3eaadf08cb59/framework/web/XmlResponseFormatter.php#L94

**Comment by samdark** [comment]
Sounds OK to me. @yiisoft/core-developers ?

**Comment by dynasource** [comment]
with respect to https://www.w3.org/TR/xmlschema11-2/#boolean, the following options are prescribed:
* 'true' | 'false' | '1' | '0'

with respect to readibility and ambiguity, I would choose for true or false, since the return of 1 in consoles actually mean an error.

**Comment by kavolorn** [comment]
@nanodesu88 correct place

**Comment by kavolorn** [comment]
I would like to see 'true' and 'false' too. Thats what I actually expected :)
Should be very small fix!

**Comment by samdark** [comment]
```php
if ($value === true) {
    $value = 'true';
} elseif ($value === false) {
    $value = 'false';
}
$child->appendChild(new DOMText((string) $value);
```

**Comment by nanodesu88** [comment]
^ nvm, i am just testing some github behaviors

**Comment by samdark** [comment]
Fixed.
