### ISSUE TITLE
ActiveRecord in some cases can not query the data

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#12858]
A very simple query sample:
```
Component::findOne('1234');
```
I try to call it from the controller in two ways, but get two results. First of all, I visited an address in the browser, and then the results were very smooth:
```
object(app\models\Component)#69 (8) {...}
```
The second time I let other services to call my address, this time did not check out the results.
```
NULL
```

I began to try to analyze the problem, and finally see some differences in `yii\db\QueryBuilder:: buildCondition` in the output `$condition`.

First case:
```
[warning][yii\db\QueryBuilder::buildCondition] {"id":"1234"}
```
Second case:
```
[warning][yii\db\QueryBuilder::buildCondition] {"id":{"0":"1234"}}
```

So I think the problem should be here, but I think I do not understand why there is such a difference, can help me to analyze!

**Comment by cebe** [comment]
please show what you pass to `Component::findOne()` to get the two results.

**Comment by xiaoxing598** [comment]
I found the reason, because the other side of the argument is object, it will be converted into a string type can: `Component::findOne(str_val ($id))`.
