### ISSUE TITLE
Upgrade documentation 2.0.10 is wrong

### ISSUE THREAD

**Issue by seisvalt** [yiisoft/yii2#12850]
In upgrade documentation 
`php composer.phar require "yiisoft/yii2:~2.0.9"`

to upgrade to 2.0.10 should be?
`php composer.phar require "yiisoft/yii2:~2.0.10"`

**Comment by dynasource** [comment]
its already fixed in https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md but after the tag has been attached. Therefore its still visible in https://github.com/yiisoft/yii2/blob/2.0.10/framework/UPGRADE.md

**Comment by cebe** [comment]
I have added more detailed instructions for upgrade to be more clear.
