### ISSUE TITLE
Separate Migrate controller functionallity into separate component

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2#12862]
This is not the first time I encounter the need to use migration functionality without access of console and to do that programmatically, so I decided to do something about it. I don't like idea of bridges that allow use of console commands from web application interface, so this should be handled in more effective way.

To do that, migration functionality should be separated and migrate controller converted in such way that it is mere user of mentioned migration component, to avoid duplicating code and contribute in code reuse.

I have already started to work on that, I have created `Migrator` component that is fully compatible with requirements of migrate controller using yii component event system. Only issue with such move is that this change will hinder any class that is extending `BaseMigrateController` or `MigrateController` methods, except actions itself.

I think all the functionality that is currently accessible only via console interface, should be converted in similar way, so that Yii framework could be used as a base for complex applications that handle their own package management or custom installers and would like to give extended control of application via web interface, without _hacking_ the framework.

See my progress so far in [migrator](https://github.com/Deele/yii2/tree/migrator) branch.

I would like to see your comments on my use of events (and other parts of code) and idea (separation of console controller functionality into components) overall. I'm trying to make as little changes as possible, to avoid breaking anything and creating new issues. The end result should make migrate controller work the same as it is already working, with the difference of its code sitting inside component.

So far, I have received positive feedback from @cebe , so I will continue my work on it until migrate controller has regained all of its functions via Migrate component.

**Comment by samdark** [comment]
Make a pull request. It will be much easier to review.

**Comment by Deele** [comment]
@samdark I am guessing that this component needs proper testing and better documentation in comments before I make pull request. I just [finished most of implementation](https://github.com/yiisoft/yii2/compare/master...Deele:migrator) that was in my head and will try to do simple testing as soon as possible. What about unit tests (are they mandatory?) and what are recommendations regarding file headers (copyright and stuff) and code style (is anybody checking it)? This is my first contribution that introduces new files into repository, that is why I have such questions.

**Comment by cebe** [comment]
> needs proper testing and better documentation in comments before I make pull request

A pull request does not need to be perfect when submitted, we will comment on the current state and it will evolve until it is good to be merged.

> What about unit tests (are they mandatory?)

Not mandatory, but good to have. There are already tests for [migrate controller](https://github.com/yiisoft/yii2/blob/master/tests/framework/console/controllers/MigrateControllerTestTrait.php).

> what are recommendations regarding file headers (copyright and stuff) and code style (is anybody checking it)?

You can copy file headers from other files in the framework. But you can also just leave them away, we have a command that automatically adds them.

About code style, check https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md
We will add comments about everything that needs adjustments if you create a PR.

**Comment by dynasource** [comment]
> Not mandatory, but good to have

Mandatory if you'd ask me

**Comment by samdark** [comment]
I'm for having tests as well. They take time, of course, but you won't break the solution again and will find most issues early which is great.

**Comment by Deele** [comment]
@cebe Allright, thank you, I will PR as soon as I test it.

@dynasource Can you suggest some material/guide what to unit test (every method?) and how to test correctly (to conform with Yii standards)? I have asked many times about [yii2 guide regarding unit testing](http://www.yiiframework.com/doc-2.0/guide-test-unit.html) but still, there is no progress.

**Comment by dynasource** [comment]
@Deele, what you can not see does not imply that there is not any 'progress'. A lot of publications & improvements on both @docs and architecture are to be expected in testing Yii.

For now, I can already give you some pointers. Please read the manual of PHPunit to understand the why's and how's of unittesting https://phpunit.de/manual/current/en/phpunit-book.pdf

With respect to the creation of unit tests for Yii. You should follow the following principles:
* choose the smallest possible testenvironment (unit) for your test. The less objects that interfere, the more stable (and fast) you test will be
* dont create tests that are maintenance heavy and are likely to fail at every software changes) Assertions against a big HTML block is usually not a best practice.
* choose carefully about the method name. It should exactly do what it is named.
* only add useful tests. Think like a policy/rule maker. Which rules should never be broken? Create tests for it.
* dont mix assertions & preparations too much. Try put variable preparation in the beginning of the test and end the testMethod with the assertions
* keep every testMethod as short as possible (test only 1 thing at a time)
* keep every testMethod as independant as possible. It should run independantly
* stay away from difficult fixtures as you can use getMocks/createMocks
* make it as fast as possible. Within my suite, I test projects in parallel. When all of your tests run <3 seconds, you never want to go back.

Tests are the ultimate proof of the logic behind your software. A stranger should know what your software can do just by looking at your tests. If you a thinking from this perspective, the quality of your tests will improve.

**Comment by samdark** [comment]
Won't be implemented in 2.0. Likely will be in 3.0.
