### ISSUE TITLE
FileMutex: unlink(...): No such file or directory

### ISSUE THREAD

**Issue by schojniak** [yiisoft/yii2#12860]
### What steps will reproduce the problem?

doing many parallel locks
### What is the expected result?

no error
### What do you get instead?

No such file or directory in
 `unlink($this->getLockFilePath($name));`
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.10 |
| PHP version | 5.5.9 |
| Operating system | linux Ubuntu 14.04.4 |

**Comment by schojniak** [comment]
first unlink() then fclose() solved it for me

**Comment by samdark** [comment]
This is extremely weird. Any idea why?

**Comment by schojniak** [comment]
``fclose() `` release lock, then other process call ``acquireLock`` and ``releaseLock``; there is no file to ``unlink`` in first process.

**Comment by schojniak** [comment]
you can call ``unlink`` on open file (Unix, I don't know how it works on windows)

**Comment by kidol** [comment]
I tested, does work on unix, but not on windows (permission denies error). So following should be enough to fix:
```php
@unlink($this->getLockFilePath($name));
```

**Comment by cebe** [comment]
@kidol wouldn't that possibly unlink a file that is locked by another process already?

**Comment by schojniak** [comment]
Can you look at #12831? 

"FileMutex does not have MS Windows operating system support." was deleted to enable tests on windows.

**Comment by kidol** [comment]
@cebe Yes that's what's happening already on unix (see error message in issue description). Fix is just to add `@` to suppress that error.
Little strange if script A deletes file while script B already acquired file handle and is now trying to call flock on it. But it works, you can see here: https://3v4l.org/SilHY

**Comment by kidol** [comment]
Some more info regarding unlink on unix: http://stackoverflow.com/questions/23287997/why-is-unlink-successful-on-an-open-file

**Comment by samdark** [comment]
Also verified that Windows gives you `Permission denied` in case you're trying to unlink locked file.

**Comment by samdark** [comment]
@kidol is it possible to solve w/o using `@`?

**Comment by kidol** [comment]
Hmm, looks like symfony does not remove the lock file at all: https://github.com/symfony/symfony/pull/10475#issuecomment-51464260

Problem is the following:
- Script A unlocks and calls unlink
- Script B was waiting (file handle already acquired) and will now acquire a lock on non-existing file
- Script C starts and is simply creating a new file and is able to lock it...

Maybe it's better to refactor class so that locks get serialized into a single lock-file. Means if script wants to acquire lock it has to:

- Open lock file
- flock in blocking mode
- Unserialize locks array
- If $locks[$name] === true, unlock file, sleep(1) and return to step 2
- If $locks[$name] === false, set it to true, serialize and save, unlock file, return true

That's at least how I implemented such locking in the past and it works well.

**Comment by samdark** [comment]
Wouldn't that create too many unnecessary I/O blocks even for unrelated locks

**Comment by kidol** [comment]
No, unless you run many short-living locks/scripts in parallel, which is uncommon I think. Also I see no use case to use locks in a web application. If there is one, then it may lead to problems under heavy load indeed.

In case of the symfony solution: User could use the systems temp path for these files so the runtime folder does not get polluted with these lock files.

Maybe symfony solution is better for the sake of simplicity..

**Comment by rob006** [comment]
> No, unless you run many short-living locks/scripts in parallel, which is uncommon I think.

I'm using locks in such scenario. And locks can be useful in web app - sometimes you need do some heavy task (like image processing, that could take ~5 seconds) and you want to be sure that you will not do the same job by 20 parallel processes.

If we can't delete lock file immediately after release, there should be garbage collector at least, which will delete old lock files.

**Comment by samdark** [comment]
> No, unless you run many short-living locks/scripts in parallel, which is uncommon I think. Also I see no use case to use locks in a web application. If there is one, then it may lead to problems under heavy load indeed.

I did that for background tasks w/o queue. These were run via about 20 cronjobs which were independent and all used locks.

**Comment by kidol** [comment]
@rob006 @samdark 
Assume each job takes only 500ms and locking has overhead of 10ms. You can now calculate approx. how many jobs you can run in parallel before you get issues with blocking.
That's what I meant with "No, unless..."

In case you thought one lock will block the lockfile until the lock is released, this is not the case. It will flock + LOCK_EX, write new state then flock + LOCK_UN. Same procedure when releasing the lock.

**Comment by kidol** [comment]
Possible solution for unlink-problem: http://stackoverflow.com/questions/17708885/flock-removing-locked-file-without-race-condition
Didn't test it yet.
