### ISSUE TITLE
Expression params

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#12874]
### What steps will reproduce the problem?
```
        $square = new Expression("ST_GeometryFromText('POLYGON((:downLeftPoint, :topLeftPoint, :topRightPoint, :downRightPoint, :downLeftPoint))')", [
            ':downLeftPoint' => $coord['downLeftPoint'],
            ':topLeftPoint' => $coord['topLeftPoint'],
            ':topRightPoint' => $coord['topRightPoint'],
            ':downRightPoint' => $coord['downRightPoint'],
        ]);

blahblah->where("ST_Contains($square, coord_point::geometry)")
```
### What is the expected result?

```
WHERE (ST_Contains(ST_GeometryFromText('POLYGON((100500 100500, 200500 200500, 300500 300500, 400500 400500))'), coord_point::geometry))
```
Important to get params without quotes. So i using Expression, otherwise query will be fail.
### What do you get instead?
```
    yii\db\Exception: SQLSTATE[XX000]: Internal error: 7 ERROR:  parse error - invalid geometry
HINT:  "POLYGON((:d" <-- parse error at position 11 within geometry
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.12
| Operating system | Debian 8

**Comment by githubjeka** [comment]
Can you send PR with this sql as a test?

**Comment by RSalo** [comment]
@githubjeka for example you can try this:
```
        $square = new Expression("ST_GeometryFromText('POLYGON((:downLeftPoint, :topLeftPoint, :topRightPoint, :downRightPoint, :downLeftPoint))')", [
            ':downLeftPoint' => '100500 100500',
            ':topLeftPoint' => '200500 200500',
            ':topRightPoint' => '300500 300500',
            ':downRightPoint' => 400500 400500,
        ]);
$this->find()->select("ST_Contains($square, POINT(100500, 100500)::geometry)")
```
Query should looks like this:
```
select ST_Contains(ST_GeometryFromText('POLYGON((100500 100500, 200500 200500, 300500 300500, 400500 400500))'), POINT(100500,100500)::geometry)
```

You should use PostgreSQL and install PostGIS.

**Comment by klimov-paul** [comment]
This is incorrect usage SQL expression `POLYGON((` is a part of the string value, you can not use bound parameters for its parts composition. You should pass the entire geometry as a single parameter:

```php
$square = new Expression("ST_GeometryFromText(:geoText)", [
            ':geoText' =>"POLYGON(({$coord['downLeftPoint']}, {$coord['topLeftPoint']}, {$coord['topRightPoint']}, {$coord['downRightPoint']}))"  ,
]);
```

**Comment by RSalo** [comment]
@klimov-paul it doesn't work.
```
        $square = new Expression("ST_GeometryFromText(:geoText)", [
            ':geoText' => "POLYGON(({$coord['downLeftPoint']}, {$coord['topLeftPoint']}, {$coord['topRightPoint']}, {$coord['downRightPoint']}, {$coord['downLeftPoint']}))"
        ]);
$this->find()->select("ST_Contains($square, coord_point::geometry)"))
```
Exception:
```
yii\db\Exception: SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000004" requires 2
```

**Comment by klimov-paul** [comment]
You have a clear error message - search for the extra bound param, which have no value specified.
I can not debug your program for you.

**Comment by dynasource** [comment]
> coord_point::geometry

there it is....

**Comment by RSalo** [comment]
@dynasource but it's default postgresql feature. explicit type conversion...

**Comment by klimov-paul** [comment]
Are you able to compose your query using native PHP PDO without Yii being involved?

**Comment by RSalo** [comment]
@klimov-paul yes, it's not a problem, but i think, yii should be better for filtering sqlinjection than native bindParam or not?

**Comment by lynicidn** [comment]
@klimov-paul проблема изначально была в том что уии не проверяет на уникальность параметры для биндинга, т.е. в пдо можно сделать так
:var OR :var и пробиндить 1 :var = 1 то в уии нет - он ругается, что кол-во параметров не совпадает, те которые надо биндить и тек которые плейсхолдеры, проблема в уникализации параметров в контексте запроса, т.е. надо ждать не 2 параметра а array_unique([:val, :val])

**Comment by klimov-paul** [comment]
Причем здесь Yii?
В последний раз повторяю вопрос: вы можете предоставить рабочий(!) код на чистом PHP с использованием PDO и связываемых параметров, который покрывает вашу задачу?

**Comment by RSalo** [comment]
@klimov-paul @lynicidn проверил на чистом пдо
работает:
```
            $stmt = $conn->prepare("select :downLeftPoint");
            $stmt->bindParam(':downLeftPoint', $coord['downLeftPoint']);
```
не работает:
```
            $stmt = $conn->prepare("select ':downLeftPoint'");
            $stmt->bindParam(':downLeftPoint', $coord['downLeftPoint']);
```
и выводит ошибку:
```
Error: PDOStatement::bindParam(): SQLSTATE[HY093]: Invalid parameter number: :downLeftPoint
```

т.е. пхп не может забиндить параметры, если они строковые... так что оказывается, дело не в юии=)
