### ISSUE TITLE
Console::getScreenSize  mode con use en-US

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii2#12873]
C:\Users\root>mode con

设备状态 CON:
---------
    行:　       9001
    列:　　     120
    键盘速度:   31
    键盘延迟:　 1
    代码页:     936

C:\Users\root>mode con cp select=437

Status for device CON:
----------------------
    Lines:          9001
    Columns:        120
    Keyboard rate:  31
    Keyboard delay: 1
    Code page:      437

**Comment by kids-return** [comment]
Windows 10  

updateProgress
![5](https://cloud.githubusercontent.com/assets/4520936/19845127/cd842f42-9f6e-11e6-9b66-cfae2df8c5c2.png)

color 
![4](https://cloud.githubusercontent.com/assets/4520936/19845133/d6d717a8-9f6e-11e6-8667-e08ce552775b.png)


![3](https://cloud.githubusercontent.com/assets/4520936/19845140/e3ab318a-9f6e-11e6-8083-c3b5ac1578f4.png)

**Comment by kids-return** [comment]
Laravel SymfonyCommand 
![6](https://cloud.githubusercontent.com/assets/4520936/19845326/d3dfc23c-9f70-11e6-88dc-f71b0ec0bebb.png)

**Comment by dynasource** [comment]
are you executing both laravel & yii commands in the same console?

**Comment by kids-return** [comment]
yes. os is windows 10.

**Comment by kids-return** [comment]
I'm sorry, I understand the differences of before
