### ISSUE TITLE
Enable SchemaCache in Yii2 ,but i got exception: Getting unknown property model::property_name

### ISSUE THREAD

**Issue by benlee7** [yiisoft/yii2#12875]
In Yii2 , I set the enableSchemaCache true, but i got an exception  : Getting unknown property model::property_name.
If I remove enableSchemaCache setting , then it's fine.
Did anyone have the same thing before?

**Comment by githubjeka** [comment]
Just delete `/app/runtime/cache/`

**Comment by githubjeka** [comment]
Need more information about settings of `php yii cache/flush-schema` and default `FileCache`
http://www.yiiframework.com/doc-2.0/guide-tutorial-performance-tuning.html#enable-schema-caching

**Comment by dynasource** [comment]
it seem that your DB has changed. Have you added a column somewhere?

**Comment by benlee7** [comment]
Finally, I figure out what happened.

**Comment by benlee7** [comment]
Finally I figure out what happened.
In vendor/yiisoft/yii2/db/Schema.php, there is a method getCacheKey, when you set enableSchemaCache true, every time you get table schema, you will use getCacheKey as key from cache(I use memcache as my table schema cache)
`    protected function getCacheKey($name)
    {
        return [
            __CLASS__,
            $this->db->dsn,
            $this->db->username,
            $name,
        ];
    }`
It is not like the following method : 
` protected function getCacheTag()
    {
        return md5(serialize([
            __CLASS__,
            $this->db->dsn,
            $this->db->username,
        ]));
    }`
I don't know why, So I replace by this: 
`    protected function getCacheKey($name)
    {
        return md5(serialize([
            __CLASS__,
            $this->db->dsn,
            $this->db->username,
            $name,
        ]));
    }`
Then it works.
I find some docs of memcache , I didn't find which can use array as key, maybe someone find it ,please tell me . There is the link ablout memcache::set from php doc [http://php.net/manual/en/memcache.set.php](url) and use like this:
`bool Memcache::set ( string $key , mixed $var [, int $flag [, int $expire ]] )`

**Comment by dynasource** [comment]
@benlee7: you were using an array as a key?

**Comment by benlee7** [comment]
> @benlee7: you were using an array as a key?
No, the yii2 use array default, I change it to string

**Comment by dynasource** [comment]
in the end the key is already stringified, as can be seen over here:
* https://github.com/yiisoft/yii2/blob/master/framework/caching/Cache.php#L89

there must be something else going on

**Comment by dynasource** [comment]
closed as it likely not to be a framework issue.
