### ISSUE TITLE
yii\helpers\Console::updateProgress  overflow

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii2#12879]
Is this a question?
![1](https://cloud.githubusercontent.com/assets/4520936/19852601/4cacef2c-9f9f-11e6-8d42-f101e7f818f9.png)

![2](https://cloud.githubusercontent.com/assets/4520936/19852613/50e7c346-9f9f-11e6-9c61-f3ad49f2f0a7.png)

**Comment by samdark** [comment]
Probably.

**Comment by dynasource** [comment]
@kids-return, what exactly is your problem? Can you describe it? If its about the multiple lines that are added, that typically has to do with your console not supporting TTY.

**Comment by samdark** [comment]
@dynasource note cursor position.

**Comment by dynasource** [comment]
I saw the cursor. I once experienced a cursor like this inside a non tty console

**Comment by samdark** [comment]
Hmm... well, I'm not sure what the problem is either. He's changing value and position of the cursor changes as well... @kids-return could you elaborate?

**Comment by kids-return** [comment]
I use windows 10 is the default DOS.
The cursor will use a position, probably because the cursor is not insert type, resulting in overflow.
UpdateProgress will wrap.
In Mac OS is normal. I hope updateProgress can be compatible with windows dos.
Only need 3 to 4 can be compatible with windows dos.
You can test the windows.

Test the code is official
```php
    public function actionTest() {
        Console::startProgress(0, 10, 'Insert Database: ');
        for ($n = 1; $n <= 10; $n++) {
            Console::updateProgress($n, 10);
        }
        Console::endProgress();
    }
```
@samdark @dynasource

**Comment by kids-return** [comment]
yii\helpers\Console 970 line  3 to 4

**Comment by dynasource** [comment]
I am afraid its because of your DOS console. The same behavior will happen in the PhpStorm console. On the contrary, more advanced consoles like linux systems  support it. However, I am surprised to see this behavior in the new console of Windows 10. How are you using Windows 10? Virtualbox? Docker?

**Comment by kids-return** [comment]
My office computer is windows 10, not DOCKER and Virtualbox.
The console is windows 10 by default

**Comment by kids-return** [comment]
I think the windows console there is this problem.

**Comment by dynasource** [comment]
perhabs you could try something like this:
http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by samdark** [comment]
Nah, it should work under Windows. I have an environment. Will try to reproduce.

**Comment by samdark** [comment]
![win10_progress](https://cloud.githubusercontent.com/assets/47294/19960881/89b3f7f8-a1c0-11e6-9b0a-1e7cfe53184a.png)

Unable to reproduce. No wrapping is there...

**Comment by samdark** [comment]
@kids-return if you know how exactly to reproduce it, let us know. I've used exactly your code and it works well...

**Comment by kids-return** [comment]
![image](https://cloud.githubusercontent.com/assets/4520936/19961066/7e6ce564-a1eb-11e6-8bdc-0b1e7a5db704.png)

I am referring to this question, you have to reproduce him.
UpdateProgress should be on one line, not multiple lines

You use the current code test
You need: yii\helpers\BaseConsole 970 line 3 Modify 4
![image](https://cloud.githubusercontent.com/assets/4520936/19961241/78050cc8-a1ec-11e6-9674-1ea575bade97.png)

Forgive me for my ability to express :(
@samdark

**Comment by samdark** [comment]
Oh!

**Comment by samdark** [comment]
Fixed. Thanks for keeping explaining.
