### ISSUE TITLE
The function getPrimaryKey in the BaseActiveRecord class  dose not work well

### ISSUE THREAD

**Issue by yeoman-chen** [yiisoft/yii2#12887]
### when i use the function getPrimaryKey to get the primary key of data table, if the code not defined attributes ，it returns null  string ,I think it  dose not work well.

 codes of the function  getPrimaryKey :

```php
public function getPrimaryKey($asArray = false)
{
        $keys = $this->primaryKey();
        if (!$asArray && count($keys) === 1) {
            return isset($this->_attributes[$keys[0]]) ? $this->_attributes[$keys[0]] : null;
        } else {
            $values = [];
            foreach ($keys as $name) {
                $values[$name] = isset($this->_attributes[$name]) ? $this->_attributes[$name] : null;
            }
            return $values;
        }
   }
```

### What is the expected result?
if the code not defined attributes ，return the primary key of data table is better.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      |5.6.18
| Operating system |centos 6.5

**Comment by arogachev** [comment]
Please show the contents of your `attributes()` method. Did you override it to return empty array?

Are you sure that foreign key constraints do exist in the table you are referring to?

**Comment by yeoman-chen** [comment]
@arogachev  
The data table dose not use foreign keys  and not define or override attributes()

**Comment by arogachev** [comment]
@yeoman-chen Sorry, I did mean primary keys.
