### ISSUE TITLE
activerecord unnecessary method call  get from cache

### ISSUE THREAD

**Issue by PaulWeb** [yiisoft/yii2#12882]
### What steps will reproduce the problem?
before in config I set redis as my cache 
simple query without any cache:
```
Customers::find()->where(['id'=>1])->with(['roles','accounts'])->one()
```

### What is the expected result?
 In Profile I expected to see only this [http://joxi.ru/KAx9e87H4JxkKr](http://joxi.ru/KAx9e87H4JxkKr) and also queries from with clause

### What do you get instead?
But [http://joxi.ru/KAgGK6XSgpMvqA](http://joxi.ru/KAgGK6XSgpMvqA) 

For what? Why this meaningless method call? time from .844 to .859 waste 15 ms,  and then also every query in with clause. 

I know it is trace 15ms (maybe without debug it will be 5 ms (with socket open) or less in productions ) but why if I don't need cache?

### Additional info

According yii2 documentation [http://www.yiiframework.com/doc-2.0/guide-caching-data.html](http://www.yiiframework.com/doc-2.0/guide-caching-data.html)

```
$result = Customer::getDb()->cache(function ($db) {
    return Customer::find()->where(['id' => 1])->one();
});
```
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by PaulWeb** [comment]
Sorry, please close or remove this issue, schema cache

**Comment by dynasource** [comment]
np
