### ISSUE TITLE
403 error on http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html

### ISSUE THREAD

**Issue by Arknium** [yiisoft/yii2#12883]
Other guides work well on Special Topics section.
![captura](https://cloud.githubusercontent.com/assets/1624006/19871445/90911f6c-9f7a-11e6-813d-fc75fd1a84d8.PNG)

**Comment by Arknium** [comment]
fixed

**Comment by rob006** [comment]
This issue comes back regularly #11978

**Comment by cebe** [comment]
could be that it happens when the guide gets rebuilt. Will not look into that as I hope to replace it with the new website soon.
