### ISSUE TITLE
The test is not being used

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#12897]
The test \yiiunit\framework\ar\ActiveRecordTestTrait::testFindScalar() is not being used
There are other tests of a trait are not used.

https://github.com/LAV45/yii2/commit/8201dee0abbd997b109d8a3bc495ace915629020
https://travis-ci.org/LAV45/yii2/builds/172776879

**Comment by dynasource** [comment]
thanks for sharing. Proper test management will be more and more important. Worst case scenario is that you have all kinds of unnecessary 'ghost tests' in place which prevent you from doing updates.

It would be nice to have a workflow & criteria in place to deal with the removal of tests.

**Comment by LAV45** [comment]
The matter is that none of the tests which is a Trait not executed
Here is an example from the documentation how to connect Trait for phpunit tests
[Mocking Traits and Abstract Classes](https://phpunit.de/manual/current/en/test-doubles.html#test-doubles.mocking-traits-and-abstract-classes)

**Comment by dynasource** [comment]
nope, tests in traits are executed fine. However, in this particular case, testFindScalar was overrided and never executed.

**Comment by dynasource** [comment]
https://github.com/yiisoft/yii2/pull/12909/commits/757bca59d56fdf30a709cfbdc31bcb699d148170

**Comment by LAV45** [comment]
Please check also these tests, they just are not used
https://github.com/LAV45/yii2/commit/a0f7628b8350d8b0b8a68abd5cc73518d353e7f2
https://travis-ci.org/LAV45/yii2/builds/172993859

**Comment by dynasource** [comment]
didnt see your first link, thought it was 1.

**Comment by dynasource** [comment]
see https://github.com/yiisoft/yii2/pull/12909#discussion_r86779365
