### ISSUE TITLE
How to use the fixture in the new version

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#12899]
I found in the new version (2.0.10) has been fully using the Codeception framework, but the official document of the fixture does not seem to update, I hope to be able to get on the testing document, only from the Codeception document on how to find more about Yii2 and the results of the case, especially in the use of fixture.

**Comment by dynasource** [comment]
please tell us what to improve on docs after reading the following resources?
* http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html
* http://danaluther.blogspot.nl/2015/12/testing-in-yii-20-with-codeception.html

**Comment by xiaoxing598** [comment]
I see these documents are based on the YII2 library `yii\test\InitDbFixture`, but the new version has not been used in it, I do not know what is the intention? I imagine the simple use of PHPUNIT, you can go to the database in each test case to fill some data, how to do it? I mean, I don't want to be loaded on a document like that.

**Comment by dynasource** [comment]
your last lines are a bit unclear to me. Can you please elaborate in more detail on what are you trying to achieve and what is preventing you from doing so.

**Comment by xiaoxing598** [comment]
Please forgive my poor English ^_^, I wrote a test case, I think at this point what to do before the execution of the function, actually want to notice to insert some data into MySQL. I would like to use the fixture to solve, but the effort has not been successful for a long time.

**Comment by dynasource** [comment]
functional or unit tests?

**Comment by xiaoxing598** [comment]
unit tests

**Comment by dynasource** [comment]
in the past, I used fixtures for that. But after a while I concluded that this was not optimal for several reasons.:
* The unit tests we're too much entangled with 'fixture' logic
* Unit tests are more difficult to manage/update
* You always have to go to the fixtures to understand which data was used
* Its was error prone when multiple tests use the same DB data

After a long research, I concluded it was way more useful to put it all in the test method itself. Similar like PHPunit's getMock(). In the beginning of the test method, you prepare the data. And then you test it. Its easy to grasp and to manage. Its not entangled with other parts of your test suite and self contained. An example:

```php
class ArticleTest extends AppTestCase
{
    public function testSave()
    {
        $identity = $this->mockLogin();
        $model = new Article([
            'title' => 'Test',
        ]);
        $model->save();

        $this->assertEquals('test', $model->slug);
        $this->assertEquals($identity->id, $model->created_by);
        $this->assertEquals($identity->id, $model->updated_by);
        $this->assertTrue(is_int($model->created_at));
        $this->assertTrue(is_int($model->updated_at));
    }
}

One can argue, would this go at cost of performance? Well, if you are either setting them up with fixtures at the beginning of your run or during the testMethod, doesnt really make a difference. Actually, when testing a method only, its way more faster than a site wide fixture setup. And when you are using SQLite for your testsuite (which I am recommending anyone), performance isnt even a subject on the agenda anymore for record insertion.

**Comment by xiaoxing598** [comment]
You mean if I want to test a query function, I can write like this:

```
class ArticleTest extends AppTestCase
{
    public function testFind()
    {
        $model = new Article([
            'title' => 'Test',
        ]);
        $model->save();
        
        $articleModel = $model->findOne('1');
        $this->assertEquals('Test', $articleModel->title);
    }
}
```
Do I understand correctly?

**Comment by dynasource** [comment]
A few important improvement:
* you run in to the risk that other models are already exist in the DB if you specify a ID manually
* its better to seperate the $config variable if you use it later in the assertions (static state)
* its better to name variables to their state (in this case dbModel)

```php
class ArticleTest extends AppTestCase
{
    public function testFind()
    {
        $config = [
            'title' => 'Test',
        ];
        $model = new Article($config);
        $model->save();

        $dbModel = Article::findOne($model->id);
        $this->assertInstanceOf(Article::className(), $dbModel);
        $this->assertEquals($config['title'], $dbModel->title);
    }
}

**Comment by xiaoxing598** [comment]
ok, thanks!!!
