### ISSUE TITLE
Lowercased table name in migrations

### ISSUE THREAD

**Issue by zlakomanoff** [yiisoft/yii2#12904]
### What steps will reproduce the problem?
`yii migrate/create add_API_PACKAGE_NAME_column_to_PROJECTS_SETTINGS_table --fields="API_PACKAGE_NAME:string(256)"`

### What is the expected result?
`$this->addColumn('PROJECT_SETTINGS', 'API_PACKAGE_NAME', $this->string(256));`

### What do you get instead?
`$this->addColumn('project_settings', 'API_PACKAGE_NAME', $this->string(256));`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.12
| Operating system | Arch GNU/Linux

**Comment by samdark** [comment]
Issue confirmed. Do you want to fix / add unit test for it?

**Comment by zlakomanoff** [comment]
Yes, i can. I will do this on next week.
