### ISSUE TITLE
FR: Validation, send error message to other attribute

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#12900]
Sometimes i need when some attribute going invalid, the error message sending to other attribut. We can add property `sendErrorTo` (or someting else) to class `Validator`, so we can do this
```php
public function rules()
{
    return [
        ['date', 'date', 'timestampAttribute' => 'date_timestamp'],
        ['date_timestamp', 'compare', 'operator' => '>', 'compareValue' => time(), 'sendErrorTo' => 'date'],
    ];
}
```
I want when `date_timestamp` is invalid, the attribute `date` that going error because only `date` attribute that appear in form.
Sorry for RIP english.

**Comment by dynasource** [comment]
Such functionality is indeed useful. Which other usecases can we think of around an error? If there are many, we could give birth to a new class ValidationError, handling all kinds of actions after a Validation error has occurred.

**Comment by samdark** [comment]
Already could be implemented using custom callback.

**Comment by samdark** [comment]
Use cases are interesting.

**Comment by mdmunir** [comment]
> Already could be implemented using custom callback.

I am unsure. How about this?
```php
public function addError($model, $attribute, $message, $params = [])
    {
        $params['attribute'] = $model->getAttributeLabel($this->sendErrorTo ? : $attribute);
        if (!isset($params['value'])) {
            $value = $model->$attribute;
            if (is_array($value)) {
                $params['value'] = 'array()';
            } elseif (is_object($value) && !method_exists($value, '__toString')) {
                $params['value'] = '(object)';
            } else {
                $params['value'] = $value;
            }
        }
        $model->addError($this->sendErrorTo ? : $attribute, Yii::$app->getI18n()->format($message, $params, Yii::$app->language));
    }
```
Need more test

**Comment by samdark** [comment]
Technically it's doable but what are use-cases exactly?

**Comment by mdmunir** [comment]
Use case
* Compare timestamp (like my example above).
* Another case, i dont know how to elaborate in english.
```php
public function rules()
{
    return [
        [['item_id'], 'exist', 'skipOnError' => true, 'targetClass' => Item::className(), 'targetAttribute' => ['item_id' => 'id'], 'sendErrorTo' => 'item_name'],
        ['item_name', 'safe',],
    ];
}
```
`item_id` is stored as hidden field and his value provided from autocomplete (`item_name`). So, when `item_id` is invalid, i want `item_name` is going error.

**Comment by samdark** [comment]
Makes sense to me. @klimov-paul need your opinion on the subject.

**Comment by klimov-paul** [comment]
My opinion this is a little bit twisted and may cause a side effects.

The 'date timestamp' example has a significant drawback since `date_timestamp` attribute becomes 'safe' since it has a validation rule on it.

'item_name -> item_id' example can be solved using `InlineValidator`:

```php
public function rules()
{
    return [
       ['item_name', 'validateExist']
    ];
}

public function validateExist($attribute, $params)
{
    $validator = new ExistValidator([
        'targetClass' => Item::className(),
        'targetAttribute' => ['item_id' => 'id'],
    ]);
    
    $errorMessage = null;
    if (!$emailValidator->validate($value, $errorMessage)) {
        $this->addError('item_id', $errorMessage);
    }
}
```

I think the feature is not general and can be already achieved by other means.

**Comment by samdark** [comment]
@mdmunir ?

**Comment by mdmunir** [comment]
> The 'date timestamp' example has a significant drawback since date_timestamp attribute becomes 'safe' since it has a validation rule on it.

```php
        ['!date_timestamp', 'compare', 'operator' => '>', 'compareValue' => time(), 'sendErrorTo' => 'date'],
```
> I think the feature is not general and can be already achieved by other means.

How about **Simplify**?

**Comment by dynasource** [comment]
@mdmunir, can you think of a solution in which your usecase is covered with a callback?

**Comment by mdmunir** [comment]
> can you think of a solution in which your usecase is covered with a callback?

I am unsure. My solution is more simple
```php
        $model->addError($this->sendErrorTo ? : $attribute, Yii::$app->getI18n()->format($message, $params, Yii::$app->language));

```

**Comment by dynasource** [comment]
its simple indeed, but it also looks like a quickfix. It would be nicer to fix your issue from a composition perspective, one that has a longer life expectancy.

**Comment by samdark** [comment]
How about clientside validation in this case?

**Comment by mdmunir** [comment]
> How about clientside validation in this case?

Ya, that make more complicated. I have no idea.

**Comment by samdark** [comment]
Then I think we'd better close the issue since there means to hack it as needed via callbacks.

**Comment by mdmunir** [comment]
@samdark What your simple sugestion?
Use InlineValidator can safe all the day. But its mean we are losing client validation.
Beside, not all server validator have client validator like `date`, `exist`, `unique`, etc. So, IMO, its ok if we skip client validation when `sendErrorTo` is not null.

**Comment by mdmunir** [comment]
```php
        if ($enableClientValidation) {
            $validators = [];
            foreach ($this->model->getActiveValidators($attribute) as $validator) {
                /* @var $validator \yii\validators\Validator */
                $js = $validator->clientValidateAttribute($this->model, $attribute, $this->form->getView());
                if ($validator->sendErrorTo == '' && $validator->enableClientValidation && $js != '') {
                    if ($validator->whenClient !== null) {
                        $js = "if (({$validator->whenClient})(attribute, value)) { $js }";
                    }
                    $validators[] = $js;
                }
            }
        }

```

**Comment by samdark** [comment]
> So, IMO, its ok if we skip client validation when sendErrorTo is not null.

No, it's not. Half-working solutions are OK for a project not using client validation but absolutely unacceptable for a framework.

**Comment by mdmunir** [comment]
> Half-working solutions are OK for a project not using client validation but absolutely unacceptable for a framework.

where your comment when `unique` has no client validation?

**Comment by samdark** [comment]
Well, it's a different case. In that case it's not possible to do with a client validation. In case of setting error to another attribute it should be possible.

**Comment by zhcdsan** [comment]
samdark, think about dynamicform example. basically we have two scenarios: create and update.
for both, all fields are rendered. so, doesn't makes sense to validate unique in client side only?

i'm thinking about createMultiple and loadMultiple when form grows up. enable ajax validation will cause a lot of server hits, possibly database hits and etc.

my work around for now is a ownValidator that checks repeated elements inside a form. looks like:

js part
`uniqueOnClientSide: function (messages, attribute, modelClass, $form) {
            timeArray = [];
            occurs = {};

            $form.find('[id ^='+modelClass+'-][id $=-'+attribute+']').each(function(i, field) {
                timeArray[i] = $(field).val();
                if (occurs[timeArray[i]] != null ) {
                    occurs[timeArray[i]]++;
                    if (occurs[timeArray[i]] > 1) {
                        messages.push('repeated!');
                    }
                } else {
                    occurs[timeArray[i]] = 1;
                }
            });
        }`

and asset part:

`public function clientValidateAttribute($model, $attribute, $view)
    {
        ClientUniqueValidationAsset::register($view);

        $modelClass = get_class($model);
        $modelName = end(explode('\\', $modelClass));
        $formModelName = strtolower($modelName);

        return 'ownValidators.uniqueOnClientSide(messages, "' . $attribute . '", "' . $formModelName . '", $form);';
    }`

do you think that framework core can work with that problem?

repair that i'm not saying that client validation will replace backend. but following yii2 performance concept, this solution will be a nice thing to have. do you agree?
