### ISSUE TITLE
Cookie-based login works only if $duration > 0

### ISSUE THREAD

**Issue by DmLapin** [yiisoft/yii2#12907]
Maybe not problem, but feature request.
### What steps will reproduce?
Set 
```
user' => [
    'enableAutoLogin' => true,
]
```
Do `$app->user->login($userModel)`
### What is the expected result?
User logged in, browser gets identity cookie with expire = 0 (until the browser is closed)
### What do you get instead?
User logged in, browser doesn't get identity cookie.
### Purpose
Session's lifetime is limited. By default, php session expires in ~25 min. Imagine, that you open browser, log in and go to lunch. After that you are automatically logged out despite 'enableAutoLogin' => true. 

I expect that if I don't check "Remember me" ($duration = 0), I will be able to work until closing browser. And if I check "Remember me", I will be able to auto-login during `$duration` time. Is my logic wrong?
### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by dynasource** [comment]
enableAutoLogin is a setting which enables your users to use the 'remember me' checkbox. Its up to them if they want to make use of it. 

As a developer, you should not decide for the user to have its session kept alive when the browser is still open. Safety is advised (of course depending of what kind of app you've built).

**Comment by kidol** [comment]
>I expect that if I don't check "Remember me" ($duration = 0), I will be able to work until closing browser. 

Increase session lifetime or better: implement auto-update via ajax-request.

**Comment by samdark** [comment]
That's expected and documented:

```
@param integer $duration number of seconds that the user can remain in logged-in status.
 Defaults to 0, meaning login till the user closes the browser or the session is manually destroyed.
 If greater than 0 and [[enableAutoLogin]] is true, cookie-based login will be supported.
 Note that if [[enableSession]] is false, this parameter will be ignored.
```

**Comment by dynasource** [comment]
Docs deserve easier descriptions of the different scenarios

**Comment by samdark** [comment]
@dynasource any suggestions?

**Comment by dynasource** [comment]
yes, will fix a PR for it
