### ISSUE TITLE
yii\rbac\DbManager & Yii::$app->user->can Создаёт слишком много запросов.

### ISSUE THREAD

**Issue by GT-Volk** [yiisoft/yii2#12902]
Добрый день!
Суть проблемы такова, любая проверка роли, например:
`Yii::$app->user->can('viewListServices')`
Создаёт сразу **4 SQL запроса**:
```
SELECT * FROM `auth_assignment` WHERE `user_id`='1'
SELECT * FROM `auth_item` WHERE `name`='viewListServices'
SELECT * FROM `auth_item` WHERE `name`='mdAdmin'
SELECT `parent` FROM `auth_item_child` WHERE `child`='viewListServices'
```
У меня в шаблоне с главным меню больше 20 подобных проверок, в итоге получается, что любой экшен автоматически создаёт сразу более 100 запросов к базе. Это крайне нерационально. Не логичнее ли сразу выгребать все роли, которые закреплены за пользователем, а потом в методе **can()** просто сравнивать с кэшем (как это делается при повторной проверке роли например)?

**Comment by MysteryDragon** [comment]
Это не только логично, но и происходит, насколько я могу видеть по коду того же `yii\rbac\DbManager` :)

**Comment by MysteryDragon** [comment]
`yii\web\User`:
```
    public function can($permissionName, $params = [], $allowCaching = true)
    {
        if ($allowCaching && empty($params) && isset($this->_access[$permissionName])) {
            return $this->_access[$permissionName];
        }
        // <...>
    }
```

`yii\rbac\DbManager`:
```
    public function checkAccess($userId, $permissionName, $params = [])
    {
        $assignments = $this->getAssignments($userId);
        $this->loadFromCache();
        if ($this->items !== null) {
            return $this->checkAccessFromCache($userId, $permissionName, $params, $assignments);
        } else {
            return $this->checkAccessRecursive($userId, $permissionName, $params, $assignments);
        }
    }
```

**Comment by MysteryDragon** [comment]
I will try to translate this issue:
@GT-Volk says that he makes 20 such checks as `Yii::$app->user->can('viewListServices')` in his template, so finally he sees "over 100 MySQL queries" per page. And he offers to get all user roles into cache, and use cache values in `User::can()`.

I think Yii already has all that needed in this case.
We can set `cache` property of `authManager`, so RBAC information will be stored into cache.
So we don't need also caching data in `User::can()`.
`DbManager` caches everything except user assignments, but that's a moot point: do we actually want to cache assignments? If we are, we can use fragment caching and other common tricks.

**Comment by samdark** [comment]
@GT-Volk have you tried setting DBManager::$cache to `'cache'` in config?

**Comment by GT-Volk** [comment]
Yes, I tried to include a cache. As a result, remains one query to the database to test 
``` SELECT * FROM `auth_assignment` WHERE` user_id` = '1' ```

Но мне кажется это изначально неправильным кэшировать запросы которых вообще быть не должно.

**Comment by MysteryDragon** [comment]
Like operate with any other data, stored in database in your project. We may cache or not cache this data. It's local project policy.
But cache invalidation is always actual and difficult question, as a "payment for benefits" :)

**Comment by MysteryDragon** [comment]
Perhabs, some new `yii\web\User` property will be useful in this case. `cacheAccess`?

**Comment by GT-Volk** [comment]
У себя это решил пока так, добавил к identity свою проверку.
```
public function can(string $permissionName, array $params = [], bool $allowCaching = true) : bool
{
    if (empty($this->_myRoles)) {
        /* @var CheckAccessInterface */
        $authManager = Yii::$app->authManager;
        $allRoles = $authManager->getChildren($this->role_name);
        foreach ($allRoles as $roleName => $role) {
            $this->_myRoles[] = $roleName;
        }
    }
    return in_array($permissionName, $this->_myRoles, false);
}
```
Чекаю `Yii::$app->user->identity->can('viewListServices')`
В результате создаётся всего один SQL запрос, и на моём количестве проверок отрабатывает это в 10-12 раз быстрее.

**Comment by samdark** [comment]
Вопрос уже много раз обсуждался. Кешировать (даже в пределах запроса) назначенные юзеру роли не безопасно в общем случае. Например, отнимаем у админа права, а он всё ещё может что-то делать. Или другой пример — права выдаются по времени.
