### ISSUE TITLE
Error to load modal with scenery

### ISSUE THREAD

**Issue by jhansonpk** [yiisoft/yii2#12915]
### What steps will reproduce the problem?
Using scenarios in model

### What is the expected result?
load model

### What do you get instead?
yii\base\ErrorException: Array to string conversion in \yiisoft\yii2\base\Model.php:757

### Additional info
a variable of type array is being concatenated

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.3
| Operating system | Linux Ubuntu 14 LTS

**Comment by samdark** [comment]
Could you provide exactly how to reproduce the error starting with clean basic project template?

**Comment by jhansonpk** [comment]
Hello, basically the use of scenarios, and when loading data from a form for example, will fall into this error, because the code is written wrong, I will provide for you the exact point of error, is a variable that is being treated as an array and string at the same time, so the error.

https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L748

in line 757 you will find the variable $ attribute being used in two ways, causing the error.

if ($attribute[0] !== '!' && !in_array('!' . $attribute, $scenarios[$scenario]))

I believe that should affect both the basic and the advanced template

**Comment by arogachev** [comment]
@jhansonpk Could you provide specific example?

**Comment by samdark** [comment]
```php
if ($attribute[0] !== '!' && !in_array('!' . $attribute, $scenarios[$scenario]))
```

- `$attribute[0] !== '!'` means 1st character of attribute name isn't `!`.
- `!in_array('!' . $attribute, $scenarios[$scenario])` means attribute name prefixed with `!` should not be in current scenario.

I see no tests for array here.

**Comment by jhansonpk** [comment]
the $attribute variable is checked her first index, $atribute[0]
then in a second check, it is concatenated with '!' . $attribute.

let's imagine that the value of $attribute is an array, the first time being true or false is not going to mistake the second time, there is a concatenation with this variable, and this will cause a runtime error.

**Comment by samdark** [comment]
Yes but attribute can't be an array if everything is done according to manual. And if it's not then it's not a good idea to be silent about it.
