### ISSUE TITLE
Question: why RBAC doesn't allow assign permission to user?

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii2#12914]
RBAC allows assign roles to user but not permissions directly.
So when it is necessary to assign a specific permission to a user we have to create specific role which isn't convenient.

I'm thinking about implementing such ability and I'm curious to know if there is a good reason to not to do it? :)

Thanks.

**Comment by samdark** [comment]
There are many:

1. It make UIs much more complicated.
2. It becomes hard to track who got which permission and why.
3. Logic becomes a bit more complex.
