### ISSUE TITLE
Unique validator ignores custom message when using targetAttribute

### ISSUE THREAD

**Issue by zeitgeist13** [yiisoft/yii2#12918]
### What steps will reproduce the problem?

Add a unique validator for two attributes and define a custom Error message: 

```
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rate_id', 'vehicle_id'], 'required'],
            [['rate_id', 'vehicle_id'], 'integer'],
            [['price'], 'number'],
            [['rate_id'], 'exist', 'skipOnError' => true, 'targetClass' => Rate::className(), 'targetAttribute' => ['rate_id' => 'id']],
            [['vehicle_id'], 'exist', 'skipOnError' => true, 'targetClass' => Vehicle::className(), 'targetAttribute' => ['vehicle_id' => 'id']],
            ['vehicle_id', 'unique', 'targetAttribute' => ['vehicle_id', 'rate_id'], 'message' => 'Dieses Fahrzeug wird in diesem Tarif schon verwendet.'],
        ];
    }
```
### What is the expected result?

The validation message should be  'Dieses Fahrzeug wird in diesem Tarif schon verwendet.'

### What do you get instead?

The validation message is 'Die Kombination "1"-"1" für Fahrzeug and Rate ID wird bereits verwendet.'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.8
| Operating system | Linux Mint 18

**Comment by SDKiller** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/validators/UniqueValidator.php#L96

**Comment by rob006** [comment]
This should be fixed in 2.0.10. Are you sure you're using 2.0.10?

**Comment by zeitgeist13** [comment]
Sorry, my bad. After updating it works fine.

**Comment by leocharrua** [comment]
Hello. I have this issue with version 2.0.14. 

`['worker_id', 'unique', 'targetAttribute' => ['team_id', 'worker_id'], 'message' => Yii::t('app', 'This Worker is assigned to another Team.')],
`

I get the generic message error:  "The combination of fields has already been taken."

Also, the message appears in both fields, and must be only in worker_id, as I understand.

Thanks

![yii2_validator_message](https://user-images.githubusercontent.com/1721923/145534377-779db73b-6522-4100-96ae-294a8326bcdc.jpg)

**Comment by bizley** [comment]
Please use the forum / slack channel or other to ask such questions, thank you.

**Comment by leocharrua** [comment]
Sorry @bizley , Why I must do that? I think this is a bug. Thanks

**Comment by bizley** [comment]
Hmm, sorry, maybe I was too fast with this. Anyway - your description indicates that it behaves differently than expected but first of all - use the current version (2.0.43) and if it still happens create a new issue describing the error. Thank you.

**Comment by leocharrua** [comment]
Ok. Thanks for the clarification. Unfortunately I can update the Yii version because I have a very close deadline. Thanks anyway.
