### ISSUE TITLE
Detaching the AFTER_FIND event of behavior

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#12910]
### What steps will reproduce the problem?

Create a behavior which will change values of an ActiveRecord value on AFTER_FIND event:

```php
class JsonUnserializeBehavior extends Behavior
{
	public $fields = [];
	
	public function events()
	{
		return [
			ActiveRecord::EVENT_AFTER_FIND => 'unserializeJson',
		];
	}
	
	public function unserializeJson()
	{
		foreach ($this->fields as $name) {
			$array = Json::decode($this->owner->{$name});
			$this->owner->{$name} = $array['de'];
		}
	}
}
```

Attach the behavior to an ActiveRecord, example User:

```php
public function behaviors()
{
	return [
		'unserializejson' => [
			'class' => JsonUnserializeBehavior::class,
			'fields' => ['text'],
		]
	];	
}
```

As far is could see there is no way to detach this after find behavior:

```
$model = UserModel::findOne($id);
$model->detachBehavior('unserializejson');
$model->text; // The output is already processed through the `unserializejson` behavior.
```

same for:
```
$model = new UserModel();
$model->detachBehavior('unserializejson');
$text = $model->findOne($id)->text; // as findOne generate s a new model object the detaching does not work.
```
Any suggestions? Inputs?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7
| Operating system | Ubuntu 16.04

**Comment by dynasource** [comment]
because of your behavior, events are set. If you want to detach these events, you should use Event::off(). More information is to be found at:
http://www.yiiframework.com/doc-2.0/guide-concept-events.html

**Comment by nadar** [comment]
@dynasource Thank you for the hint, but this does not work either as its a mistake by design (or there is something hidden i can not see). 

How can i detach an event which has been triggered already when the data is populated? 

```php
$model = new User();
$model->off(ActiveRecord::EVENT_AFTER_FIND);
// ActiveRecord::EVENT_AFTER_FIND is off for $model
$data = $model->findOne(1); // $data = ActiveRecord::EVENT_AFTER_FIND is on again
$data->off(ActiveRecord::EVENT_AFTER_FIND); // event already triggered, unable to switch off
```

**Comment by dynasource** [comment]
to get a better understanding of Events, I would suggest you to take a look at the Event class:
* https://github.com/yiisoft/yii2/blob/master/framework/base/Event.php

Regarding your usecase. You should execute:
```php
Event::off(ActiveRecord::className(),ActiveRecord::EVENT_AFTER_FIND);
```
this will remove all the events.

If you want to remove 1 particular event, you should have the ID of the callback, like this:
```php
$callback = function(){};
Event::on(ActiveRecord::className(),ActiveRecord::EVENT_AFTER_FIND,$callback);
Event::off(ActiveRecord::className(),ActiveRecord::EVENT_AFTER_FIND,$callback);
```

**Comment by nadar** [comment]
@dynasource, thank you for the reply and taking time for my issue. Sadly i have to say this does not work either. Maybe i can take some time and generate a unit test in order to demonstrate the problem.

**Comment by dynasource** [comment]
you're welcome. Too bad that it doesn't work out. Have you already debugged the Event::$_events? That will give you some clues.

**Comment by nadar** [comment]
Yes, but when a behavior is attached to a class, then it registers the events which is why there is no possibility to detach the EVENT_AFTER_FIND event inside a behavior.

**Comment by dynasource** [comment]
> there is no possibility

there is always a way

**Comment by nadar** [comment]
dear @dynasource Once again, i always stumble upon this problem. Maybe the Event base class should introduce something lick lockOff() which will unset the event from the events list and and prevent from regenerate on next model. There is no sequence (as far as i can see) to detach the ActiveRecord::EVENT_AFTER_FIND event.

**Comment by nadar** [comment]
Problem related inputs: https://gist.github.com/nadar/ae6aeefcad4d590848faca35a718cb28

**Comment by dynasource** [comment]
isnt your problem related to the fact that your Behavior is always attached to your ActiveRecord?

**Comment by samdark** [comment]
It is. Me and @nadar are discussing the best way to solve it.

**Comment by manchenkoff** [comment]
The issue is still open as I see?

**Comment by nadar** [comment]
@manchenkoff regarding the possibility to detach an after find event: yes

**Comment by ItsReddi** [comment]
@nadar was there any solution in the meantime?

**Comment by nadar** [comment]
And again :-) Having the same problem. Unable to detach the after find event and also unable to initialize an ActiveRecord "static" attribute (which is not in the list of attributes from the database). :-(

**Comment by nadar** [comment]
I still believe the solution proposed here  https://gist.github.com/nadar/ae6aeefcad4d590848faca35a718cb28 would perfectly solve any of those issue.

**Comment by My6UoT9** [comment]
Hm ideally there would something like asArray(), which allows to disable afterFind.
https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L231

**Comment by nadar** [comment]
If the active query could also populate custom row data, this would be fixed and the active query could directly store values into the model, then you have the full flexibility to do with that model property whatever you want. Not just issues with events.
