### ISSUE TITLE
After composer update, pjax stopped working.

### ISSUE THREAD

**Issue by manu1222** [yiisoft/yii2#12919]
### What steps will reproduce the problem?
composer update will modify pjax.jquery.js from "version": "2.0.3" to "version": "2.0.6"

### What is the expected result?
Pjax should work fine. (neither pagination, nor search)

### What do you get instead?
js error: uncaught exception: no pjax container for pjax-container

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.5.12
| Operating system | Windows

**Comment by dynasource** [comment]
we are dropping support for PJAX. The past has shown that it is simply too timeconsuming to support this external package. You should either search through our forum to find clues, or in the pjax forum. https://github.com/defunkt/jquery-pjax

**Comment by samdark** [comment]
Wait, we have our own fork.

**Comment by samdark** [comment]
And 2.0.6 is indeed ours...

**Comment by samdark** [comment]
@manu1222 what Yii version is used? What PJAX version is used?

**Comment by manu1222** [comment]
@samdark Yii Version is 2.0.6 and Pjax version is 2.0.6

**Comment by samdark** [comment]
Can you update Yii to latest 2.0.10?

**Comment by dynasource** [comment]
alright, in that case (here we go again :) ), please show us your code.

**Comment by manu1222** [comment]
@samdark sure, let me update it.

**Comment by manu1222** [comment]
@samdark It's latest version now, but same pjax js error. Do you recommend me to install 'jquery-pjax'?

**Comment by dynasource** [comment]
it seems your pjax-container is not created or connected. Pasting your code would be helpful

**Comment by manu1222** [comment]
@dynasource @samdark 

Below code is working fine if I replace updated vendor's folder with the older one (before composer update).
http://pastebin.com/qXM5J0G9

**Comment by dynasource** [comment]
you should add a custom 'id' to the Pjax

**Comment by dynasource** [comment]
https://github.com/yiisoft/yii2/issues/4486#issuecomment-50332165

**Comment by manu1222** [comment]
@dynasource I tried it by adding id, but no luck.

Here is the composer.json file: http://pastebin.com/K4sL8gTt

**Comment by samdark** [comment]
Where's `pjax-container` in markup?

**Comment by manu1222** [comment]
@dynasource @samdark 

When I removed , 'timeout' => 10000, 'clientOptions' => ['container' => 'pjax-container'] , it started working again.

**Comment by samdark** [comment]
Well, obviously you don't have `pjax-container` anywhere on the page. Not sure why it worked before...

**Comment by manu1222** [comment]
@dynasource @samdark 

Got it, there was no pjax-container, that's why this error happened. Not sure why it worked before...
