### ISSUE TITLE
Repeat of past migrations

### ISSUE THREAD

**Issue by RichWeber** [yiisoft/yii2#12912]
### What steps will reproduce the problem?

I have some migrations before v2.0.10

<img width="666" alt="2016-11-03 21 52 47" src="https://cloud.githubusercontent.com/assets/1702252/19982726/e71dc42e-a20f-11e6-9e8b-8e6d72cdc1ce.png">

Versions names are without namespaces.

### What is the expected result?

When I added the new config for `migrationNamespaces` I see that my past migrations were not executed.

<img width="566" alt="2016-11-03 21 59 47" src="https://cloud.githubusercontent.com/assets/1702252/19982986/e5acaa14-a210-11e6-9dc0-317b90036b71.png">

My configuration:

```
'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'console\migrations',
                'usolutions\sms\migrations',
                //'lajax\translatemanager\migrations', // wait for namespace in module
            ],
            'migrationPath' => null, // allows to disable not namespaced migration completely
        ],
    ],
```

Migrations table:

<img width="697" alt="2016-11-03 22 00 59" src="https://cloud.githubusercontent.com/assets/1702252/19983065/2137ca3c-a211-11e6-9191-7465c6abc951.png">

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6
| Operating system | Linux

**Comment by klimov-paul** [comment]
This is expected behavior. If migration has been applied without namespace in the past - it should remain to be without namespace.

You should manually adjust migration history to contain namespaced names if you wish o refactor migrations to namespace
.
This can be done using `migrate mark` command:
1) mark all migrations down
2) change config to use namespaces
3) add namespaces to migration source codes
4) mark all migrations up

**Comment by RichWeber** [comment]
OK, I understand

But, it turns out all of these actions are to be done by all the team members on the local machines. And then still have it all to do on servers.

Okay, it's not a problem if there are couple dozen migrations. But if there are hundreds or thousands - it will be a very long process, which can lead to errors.

Why can not we verify the version of migration without namespaces and with it?

**Comment by dynasource** [comment]
@klimov-paul, for what reason are namespaces so important for migrations? Arent the base names not unique in 99,99% of the time. Or are we already takings migrations into account without the m000000_000000 formatting?

**Comment by klimov-paul** [comment]
Namespaces are not mandatory: you can use both namespaced and non namespaced mogrations at the same time.
No one forces you to deal with those migrations, which are already in the history.
But if you want to drop non-namespaced migrations completely you'll have to deal with history records at all project copies - that is true.

**Comment by RichWeber** [comment]
@klimov-paul could you tell how I can create migration with namespaces in the extension?

```
vagrant@genesix:/app$ ./yii migrate/create NewMigrationWithNamespace -p=@usolutions/sms/migrations
Yii Migration Tool (based on Yii v2.0.10)

Create new migration '/app/vendor/U-Solutions/us-sms-module/migrations/m161104_095707_NewMigrationWithNamespace.php'? (yes|no) [no]:
```

**Comment by klimov-paul** [comment]
If you wish to continue usage of non namespaced migrations you should NOT disable `migrationPath` in your config. However, in this case you should separate folders for namespaced and non-namespaced migrations, e.g. if migration namespace is `app\migrations` migration path should NOT refer to `@app/migrations` directory.

**Comment by klimov-paul** [comment]
> could you tell how I can create migration with namespaces in the extension?

You should specify full qualified class name as it is done in unit test:
https://github.com/yiisoft/yii2/blob/master/tests/framework/console/controllers/MigrateControllerTestTrait.php#L347-L356

**Comment by RichWeber** [comment]
>You should specify full qualified class name as it is done in unit test:

thanks, but I can't figure out how to set a namespace

```
'migrate' => [
            // 'class' => 'yii\console\controllers\MigrateController',
            'class' => 'console\controllers\MigrateController',
            'migrationNamespaces' => [
                'usolutions\sms\migrations',
                'console\migrations',
            ],
            'migrationPath' => null, // allows to disable not namespaced migration completely
        ],
```

if my extension's namespace has array index 0 then all is fine

```
vagrant@genesix:/app$ ./yii migrate/create NewMigrationWithNamspace                              
Yii Migration Tool (based on Yii v2.0.10)

Create new migration '/app/vendor/U-Solutions/us-sms-module/migrations/M161104103223NewMigrationWithNamspace.php'? (yes|no) [no]:y
```

How can I set namespace if it has for example 1-st array index in the config?

```
'migrate' => [
            // 'class' => 'yii\console\controllers\MigrateController',
            'class' => 'console\controllers\MigrateController',
            'migrationNamespaces' => [
                'console\migrations',
                'usolutions\sms\migrations',
            ],
            'migrationPath' => null, // allows to disable not namespaced migration completely
        ],
```

I try:

```
vagrant@genesix:/app$ ./yii migrate/create usolutions\sms\migrations\NewMigrationWithNamspace                              
Yii Migration Tool (based on Yii v2.0.10)

Create new migration '/app/console/migrations/M161104105157UsolutionssmsmigrationsNewMigrationWithNamspace.php'? (yes|no) [no]:
```

or

```
vagrant@genesix:/app$ ./yii migrate/create NewMigrationWithNamspace -p=@usolutions/sms/migrations
Yii Migration Tool (based on Yii v2.0.10)

Create new migration '/app/vendor/U-Solutions/us-sms-module/migrations/m161104_104408_NewMigrationWithNamspace.php'? (yes|no) [no]:
```

or

```
vagrant@genesix:/app$ ./yii migrate/create usolutions\sms\migrations\NewMigrationWithNamspace -p=@usolutions/sms/migrations
Yii Migration Tool (based on Yii v2.0.10)

Create new migration '/app/vendor/U-Solutions/us-sms-module/migrations/m161104_104630_usolutionssmsmigrationsNewMigrationWithNamspace.php'? (yes|no) [no]:
```

and I get a file without namespaces or wrong folder (console\migrations)

**Comment by klimov-paul** [comment]
You should proprly escape backslash (`\`) symbol for migration name parameter.

https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php#L536-L542

**Comment by RichWeber** [comment]
Ohh! thanks a lot
