### ISSUE TITLE
Confirmation message is prompted twice

### ISSUE THREAD

**Issue by antoniom** [yiisoft/yii2#12921]
### What steps will reproduce the problem?
Create an ActiveForm:

```
<?php $form = ActiveForm::begin(); ?>
    ....
    <?= Html::a('Delete', ['delete', 'id' => $model->id], ['class' => 'btn btn-danger', 'data-confirm' => 'Are you sure?']) ?>
<?php ActiveForm::end(); ?>
```

### What is the expected result?
The confirmation message should be prompted only once.

### What do you get instead?
The confirmation message is prompted twice.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.5
| Operating system | Linux

The problem is introduced in 2.0.10 (checked on 2.0.9 and is running as expected). and most probably is related to PR #11999

**Comment by samdark** [comment]
Confirmed.

**Comment by samdark** [comment]
This is the commit introduce this behavior: 3ba72da6fa11c7565de7ceb002bdf6ff86c841d4
