### ISSUE TITLE
ArrayHelper::getValue does not throw as documented

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#12927]
### What steps will reproduce the problem?
```PHP
var_dump(\yii\helpers\ArrayHelper::getValue('test', 'someProp', 123));
```
### What is the expected result?
`InvalidParamException` thrown.
### What do you get instead?
No exception, output: 123.

Yii version: 2.0.10

```PHP
    /**
     * Retrieves the value of an array element or object property with the given key or property name.
     * ...
     * @param array|object $array array or object to extract value from
     * ...
     * @throws InvalidParamException if $array is neither an array nor an object.
     */
    public static function getValue($array, $key, $default = null)
```

**Comment by dynasource** [comment]
confirmed.

This method should throw an exception when the $key does not exist in the object / array (shown by the corresponding tests)

**Comment by TerraSkye** [comment]
Current behavior would return the fedault value instead if an exception

**Comment by TerraSkye** [comment]
My bad, missread the issue.

**Comment by SilverFire** [comment]
> should throw an exception when the $key does not exist in the object / array (shown by the corresponding tests)

Does not sound right to me and not found in tests.

**Comment by PowerGamer1** [comment]
@SilverFire
What is the rationale for not erroring out when first argument is neither array nor an object? IMO when this method is called like this it means something not right and it is better if it manifests with error than silently works in a way that does not really makes sense.

**Comment by SilverFire** [comment]
Erroring for non-array will break BC for cases, when `$array` is null, for example.

**Comment by dynasource** [comment]
> Does not sound right to me and not found in tests.

1. https://github.com/yiisoft/yii2/blob/master/tests/framework/helpers/ArrayHelperTest.php#L719
2. https://github.com/yiisoft/yii2/blob/master/tests/framework/helpers/ArrayHelperTest.php#L729

**Comment by SilverFire** [comment]
It's an error thrown by object of `Post1` class as a result of access to property that does not exist

**Comment by cebe** [comment]
it was added in 9e66e08bc7ee3480504418f011150a76c94b9782 (#802) not sure why. seems accidentally added.

**Comment by PowerGamer1** [comment]
> it was added in  9e66e08  (#802) not sure why. seems accidentally added.

Judging by that diff you might as well say that
```PHP
 } else {  
    return $default;  
}
```
was added accidentally at the end of `getValue()` function. Notice how original version of `getValue()` from that diff while not throwing exception would still error out (with PHP error) when first argument is neither array nor object.

Currently, `getValue()` is documented as follows:
```PHP
@param array|object $array array or object to extract value from
```
When doing coding according to documentation, you cannot call `getValue(123, 'test', 'default')` and expect it to return 'default'.

Documentation aside, I highly doubt that in existing code like:
```PHP
getValue($somevar, 'test', 'default');
```
the author of the code actually EXPECTED to get `'default'` when `$somevar` is null, integer or alike. I highly doubt that in existing places using `getValue()` it would make any sense for the first argument to be anything other than array or object. Again, IMO it is better to error out saying "hey, look, $array is invalid so there might be something wrong in the code where the value of $array has originated from" rather than silently ignoring the problem as if nothing happened.

As for the BC breaking. First, it is yet has to be proven that any code in Yii relies on `getValue(123, 'test', 'default')` returning 'default' (and even if there is such code it should be analyzed and fixed accordingly). Second, if the user code relied on such behavior of `getValue()` it was written in violation of `getValue()` documentation and you cannot talk about backwards compatibility with such code.

**Comment by cebe** [comment]
Digging into this again I found that the last `return $default;` is not added by accident but is valid for retrieval of nested items, e.g. `getValue($array, 'test.name', 'default');` should return 'default' if the key `test` does not exist but also if `name` does not exist in `test`. However this allows weird things like:

```php
$array = [];
getValue($array, 'test.name', ['name' => 'hi']); // returns "hi"
```

I think this should be refactored and tested better in 2.1.

**Comment by filipchuk** [comment]
e963b2a broke BC, now we can't use null (which is often used) as 1st argument. I think this is not a correct way

**Comment by SilverFire** [comment]
@filipchuk this change is already considered as BC breaking, thank you for confirmation. 

Related: https://github.com/yiisoft/yii2/issues/13248

**Comment by filipchuk** [comment]
@SilverFire Thank you for quick reaction!

**Comment by SilverFire** [comment]
You're welcome
