### ISSUE TITLE
Feature request: Allow additional parameters for renderDynamic

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#12938]
I propose that similar to Yii 1, it should be possible to pass additional parameters to `renderDynamic` that get serialized and stored in cache together with the cached content. The parameters should then be supplied to the `$statement` when it is `eval()`ed with `evaluateDynamicContent()`:

```php
public function renderDynamic($statement, $params);
```

```php
public function evaluateDynamicContent($statements, $params = [])
{
    extract($params);
    return eval($statements);
}
```

## How this worked in Yii 1

In Yii 1 we could have a construct like the following:

**`views/layouts/main.php`**
```php
<?php $this->renderDynamic('renderTracking', $this->trackingParams) ?>
```

**`components/BaseController.php`**
```php
public $trackingParams = [];
public function renderTracking($params = [])
{
    $params['user_id'] = Yii::app()->user->id;
    return 'dataLayer = '.json_encode($params);
}
```

**`views/site/some-page.php`** 

```php
$this->trackingParams = [
    'pageType' => 'some-page',
];
```

**`views/site/some-other-page.php`** 

```php
$this->trackingParams = [
    'pageType' => 'some-other-page',
    'other_param' => 'foo',
];
```

If we enable pache caching for these views the following happens:

 * The `pageType` and other data is set per view in `trackingParams`
 * The current `trackingParams` are passed to `renderDynamic` and thus serialized and stored in cache
 * In `renderTracking()` we receive these stored view dependend data in `$params` and enhance it with the current user id

## Situation in Yii 2

The above is no longer possible in Yii 2, at least not without an ugly trick like:

```php
<?= $this->renderDynamic(
    'return $this->renderTracking(unserialize('. serialize($this->trackingParams).'));'
); ?>
```

I would not consider this to be very readable or easy to follow for fellow team members.

**Comment by dynasource** [comment]
can you supply an example in which the parameters are processed in eval()?

**Comment by mikehaertl** [comment]
Not sure if I understand your question. But after more thinking I think, the implementation is actually very simple:

```
/**
 * Renders dynamic content returned by the given PHP statements.
 * This method is mainly used together with content caching (fragment caching and page caching)
 * when some portions of the content (called *dynamic content*) should not be cached.
 * The dynamic content must be returned by some PHP statements.
 * @param string $statements the PHP statements for generating the dynamic content.
 * @param array|null $params parameters that should be made available as variables in $statement.
 * The keys are variable names and the values the corresponding variable values. These will
 * be serialized and stored to the cache.
 * @return string the placeholder of the dynamic content, or the dynamic content if there is no
 * active content cache currently.
 */
public function renderDynamic($statements, $params = null)
{
    if ($params!==null) {
        $statement = 'extract(unserialize('.serialize($params).'));'.$statement;
    }
    if (!empty($this->cacheStack)) {
        $n = count($this->dynamicPlaceholders);
        $placeholder = "<![CDATA[YII-DYNAMIC-$n]]>";
        $this->addDynamicPlaceholder($placeholder, $statements);

        return $placeholder;
    } else {
        return $this->evaluateDynamicContent($statements);
    }
}
```

**Comment by dynasource** [comment]
ahh...I get it. You want to prepare the $params before eval and not use them inside eval(). Thats a different approach than I am using.

Apart from the approach, I agree that this feature is useful. Lets fix this.

**Comment by mikehaertl** [comment]
@samdark Strictly speaking, isn't this another BC breaking change? So shouldn't this be 2.1.x?

**Comment by samdark** [comment]
Yes.

**Comment by dynasource** [comment]
@mikehaertl, have you already put your solution in practice? Are there any no side effects? 

@yiisoft/core-developers, is there a reason why the second argument for renderDynamic had been dropped for Yii2 (see https://github.com/yiisoft/yii2/issues/12938#issue-187932884)

**Comment by samdark** [comment]
Which 2nd argument? https://github.com/yiisoft/yii/blob/1.1.17/framework/web/CController.php#L923

**Comment by mikehaertl** [comment]
@samdark From the comment block:

> The first parameter to this method should be a valid PHP callback, while the rest parameters will be passed to the callback.
>
> Note, the callback and its parameter values will be serialized and saved in cache. Make sure they are serializable.

@dynasource Did not test it yet, but can do so and will report back.

**Comment by samdark** [comment]
Ah... right. Yes, seems to be inconvenient in 2.0.

**Comment by mikehaertl** [comment]
@dynasource So far my tests look good. I also found this related comment where Qiang proposes a similar workaround: https://github.com/yiisoft/yii2/issues/6358#issuecomment-65400987

**Comment by dynasource** [comment]
thanks for the reference.

Can you elaborate on your solution with respect to Qiangs comment https://github.com/yiisoft/yii2/issues/6358#issuecomment-65399935

**Comment by mikehaertl** [comment]
> Can you elaborate on your solution with respect to Qiangs comment #6358 (comment)

The proposed solution makes it more convenient to pass cache-time parameters to `renderDynamic()` and gives us back a feature that we had in Yii 1 and is now missing in Yii 2. 

Instead of this:

```php
<?= $this->renderDynamic("\$var = unserialize('".serialize($var)."'); return foo(\$var);") ?>
```

You could write this much more readable code:

```php
<?= $this->renderDynamic('return foo($var);', [
    'var' => $var,
]) ?>
```

**Comment by dynasource** [comment]
I think its useful. Can you prepare a PR?

**Comment by dynasource** [comment]
closed with https://github.com/yiisoft/yii2/commit/224aac83ab093a71018578caf11dbeadedb9c781
