### ISSUE TITLE
Setting isNewRecord = false dont have effect

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#12932]
### What steps will reproduce the problem?
```php
$model = new Model();
$model->setIsNewRecord(false); //from docs this should switch between insert / update when you are calling save
$model->id = '1'; //pk
$model->save();
```

### What is the expected result?
The record with id 1 should be updated.

### What do you get instead?
```
$model->save(); //returning true. But NOTHING is done no new record and no updated record
$model->update(); //returning int(0)
$model->insert(); // returning true but is ignoring the setted pk value
```

### Additional info
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.8
| Operating system | Ubuntu 16.04

**Comment by dynasource** [comment]
the title does not match with your example?

**Comment by ItsReddi** [comment]
Yes im sorry. fixed it.

**Comment by dynasource** [comment]
is there a reason in your usecase not to get the $model with find() first?

**Comment by ItsReddi** [comment]
In our case we have to prevent dulicates. But the second unique identifier is not available in the first finding of the model. The identifier its presented by an API and every single call to this API is money. 

So we are trying to find the model with the first unique identifer if we cannot find it we assume its a new record. If certain attributes are changed (other models involved) we are doing the api call and are getting the second unique identifier and trying to find it again.

The use case could be done via controller logic or via some model load function but first would be business logic in controller and second would lead to a redesign of validation logic. Because of that we tried to use `setIsNewRecord()` and found that "Bug" or misleading documentation.
Since `setIsNewRecord() public method Sets the value indicating whether the record is new.` and `Whether the record is new and should be inserted when calling save()` and in this case the return value of save() that equals true but nothing is done.

**Comment by dynasource** [comment]
well, the reality is that the use of setIsNewRecord() alone is not enough. In example, if I want an existing record to be cloned to the DB, I have to execute:
```php
        $this->id = NULL;
        $this->setIsNewRecord(true);
```

Your usecase is the other way around, but the function is mainly meant to be used for the scenario above. See also https://github.com/yiisoft/yii2/issues/566#issuecomment-19827203

**Comment by ItsReddi** [comment]
Well you are right its the other way around.
But neverless i think its a bug or not?
i think at least `save()` should not return true its the most misleading part beside of the documentation.

"setIsNewRecord() alone is not enough": what would be enough without having a declaration like
`$newModel = $oldModel;` ?

**Comment by dynasource** [comment]
> the most misleading part beside of the documentation.

if you have ideas for improvements, please feel free to do a PR.

> what would be enough without having a declaration

perhabs you can do the research for your usecase?

**Comment by SilverFire** [comment]
Accidentally moved to debug

**Comment by dynasource** [comment]
Im closing this issue. To quote Qiang: https://github.com/yiisoft/yii2/issues/566#issuecomment-19832634 ' For people who use this, they know what they are doing'. Using this setIsNewRecord is to be done in rare usecases and not something to promote as a default practice. Developers should not use this for the example in this issue as the frameworks architecture is not designed for this usecase.
