### ISSUE TITLE
Yii2 rest controller response

### ISSUE THREAD

**Issue by desaikalpesh34** [yiisoft/yii2#12931]
### What steps will reproduce the problem?
create two controller for rest api something like
using rest\Controller

```php
<?php
namespace api\modules\v1\controllers;

use common\models\Lesson;
use yii\rest\Controller;
use Yii;

class LessonController extends Controller
{
    public function actionCreate()
    {
        $model = new Lesson();
        if($model->load(Yii::$app->request->getBodyParams(), ''))
        {
            if(!$model->validate())
            {
               return $model->errors;
            }
            return  $model->save(false);
        }

    }
}
```
using rest\ActiveController

```php
<?php
namespace api\modules\v1\controllers;

use common\models\Lesson;
use yii\rest\ActiveController;
use Yii;

class LessonController extends ActiveController
{
    public $modelClass="common\models\Lesson";
}

```
make post request  for both, response is different

### What is the expected result?
response is different like
[respone for rest\ActiveController](http://prntscr.com/d45fnl)
for rest\Controller
[response for rest\ActiveController](http://prntscr.com/d45g3j)

### What do you get instead?
response will be same according to rest\ActiveController

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |5.6.8
| Operating system | windows 7

**Comment by tunecino** [comment]
To get the same output you'll need to return that `$model` instance instead of just `$model->errors`:
https://github.com/yiisoft/yii2/blob/master/framework/rest/CreateAction.php#L61
