### ISSUE TITLE
How to format the data in the field when the model is displayed?

### ISSUE THREAD

**Issue by zplzpl** [yiisoft/yii2#12930]
### What steps will reproduce the problem?

like this?

`<?= $form->field($product, 'price', ['format'=>['decimal',4]])->textInput(['placeholder' => '']) ?>`

Formatted data only when the display is displayed, I have a lot of fields that need to be handled in this way, if there is a better way to do this.

Submit the data, I will do in the validator in formatted data.

### What is the expected result?

1.23456789 => 1.2346

### What do you get instead?
method not found

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.5.3
| Operating system | windows 7

**Comment by zplzpl** [comment]
In fact, I think after setAttirubtes do this data format, more reasonable. But I didn't find the after event.

**Comment by SilverFire** [comment]
Try to create your own `CurrencyInput` widget that will encapsulate formatting logic.
