### ISSUE TITLE
Pjax stopped binds to the dynamically loaded content after upgrade.

### ISSUE THREAD

**Issue by Shybko** [yiisoft/yii2#12934]
### What steps will reproduce the problem?
Pagination within ListView is not working after ajax loaded ListView.

### What is the expected result?
Pagination must work after ListView loaded via ajax.

In Yii 2.0.9 within the file `yii\widgets\Pjax.php` was the sting
`$js .= "jQuery(document).pjax($linkSelector, \"#$id\", $options);";`
that binded pjax even to the dynamically loaded content.
Now in version 2.0.10 that string looks like 
`$js .= "jQuery(document).pjax($linkSelector, $options);";`
And bacause of this the pagination is not working, after ajax loaded ListView.

**Comment by Shybko** [comment]
This commit https://github.com/yiisoft/yii2/commit/10a2954d13766624a0de6d5d5a0c433c6ae68f65#diff-49539454e5bfd76e31a848d4039ee992 broke the code.

**Comment by dynasource** [comment]
that corresponds with PR https://github.com/yiisoft/yii2/pull/11347

**Comment by Alex-Code** [comment]
It seems a bit odd, if the second argument is a string pjax adds it to the options object as `{container: '#id'}` which is what the commit does directly.

**Comment by dynasource** [comment]
if I look at the Pjax API https://github.com/defunkt/jquery-pjax#fnpjax:
```js
$(document).pjax('a', '#pjax-container')
```
@Shybko is right. Then https://github.com/yiisoft/yii2/pull/11347 has been a faulty commit.

**Comment by Alex-Code** [comment]
Isn't
```js
$(document).pjax('a', '#pjax-container')
```
the same as?
```js
$(document).pjax('a', { container: '#pjax-container' })
```
which is what the commit does.
I've got a `ListView` in a `Pjax` container and pagination still works.

**Comment by dynasource** [comment]
hmmm...it seems so if I look further in the api:
```js
The synopsis for the $.fn.pjax function is:

$(document).pjax(selector, [container], options)

- selector is a string to be used for click event delegation.
- container is a string selector that uniquely identifies the pjax container.
- options is an object with keys described below

```

@Shybko , are your problems gone when adding IDs to your widgets?

**Comment by Shybko** [comment]
@dynasource 
> @Shybko , are your problems gone when adding IDs to your widgets?

Yes. I've overrided Pjax.php and take back the line

`$js .= "jQuery(document).pjax($linkSelector, \"#$id\", $options);";`

after that the probled has went.

@Alex-Code 
> I've got a ListView in a Pjax container and pagination still works.

I have custom code that load the ListView via ajax, the pagination is not work with actual code. But when I change the line with specifying container ID (as I wrote above), the pagination works well.

**Comment by dynasource** [comment]
@SilverFire, do you remember this PR https://github.com/yiisoft/yii2/pull/11347?

**Comment by SilverFire** [comment]
Yes, I do. I remember that I've inspected PJAX code to make sure we can drop the second parameter.

Once you call `$(document).pjax()`, we get [here](https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L44).

Then we get into [`optionsFor()`](https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L659-L676) function and reach the [second condition](https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L666), and the `container` object should have (and it really has) a `container` option.

**Comment by SilverFire** [comment]
![ezgif-1337730736](https://cloud.githubusercontent.com/assets/4499203/20196015/76152bc2-a7a1-11e6-8e61-69c05c5bd1f6.gif)

**Comment by SilverFire** [comment]
Works as expected, as for me

**Comment by dynasource** [comment]
yeah, it's strange. If it wasn't correct, it is likely that we already would have known in the issue tracker.

**Comment by Shybko** [comment]
@SilverFire 
Here is my demonstration
![ezgif-2141203265](https://cloud.githubusercontent.com/assets/8832640/20209652/2df5689a-a7fe-11e6-9e66-ae3cd76fd35e.gif)

**Comment by Shybko** [comment]
As you can see, after loading listView via custom ajax function (custom filter you can see on the demonstration), the pagination stops to work. But after page reload the pagination works again.

**Comment by SilverFire** [comment]
Do you have any errors in the JS console?

**Comment by Shybko** [comment]
@SilverFire 
No. There are no errors.

**Comment by dynasource** [comment]
> after loading listView via custom ajax function the pagination stops to work.

are you sure you have set the ID in the Pjax::widget()?

**Comment by Shybko** [comment]
@dynasource 
I didn't set ID
Here is example of my code

```
<div id="full-notification-block">
    <?php Pjax::begin(); ?>
    <div id="list-notifications">
        <?= \yii\widgets\ListView::widget([
            'dataProvider'     => $dataProvider,
            'itemView'         => '_notification-item',
            'layout'           => '{items}',
            'emptyText'        => '<span class="media-link">' . AcpMsg::t('Уведомления отсутствуют.') . '</span>',
            'emptyTextOptions' => [
                'tag'   => 'li',
                'class' => 'media empty-text text-center',
            ],
            'viewParams'       => [
                'notificationSettings' => $notificationSettings,
                'listCategories'       => $listCategories,
            ],
            'options'          => [
                'tag'   => 'ul',
                'class' => 'media-list media-list-linked media-list-bordered',
            ],
            'itemOptions'      => [
                'tag' => false,
            ],
        ]); ?>

    </div>

    <div class="panel-footer">
        <div class="heading-elements">

            <?php if(($notificationCount = $dataProvider->getTotalCount())) : ?>
                <span class="heading-text text-semibold"><?= AcpMsg::t('{notificationCount, plural, one{# уведомление} few{# уведомления} many{# уведомлений} other{# уведомлений} }', ['notificationCount' => $notificationCount]); ?></span>
            <?php endif; ?>

            <div class="pull-right">
                <?php echo \yii\widgets\LinkPager::widget([
                        'pagination' => $dataProvider->getPagination(),
                    ] + $pagerSettings); ?>
            </div>
        </div>
    </div>
    <?php Pjax::end(); ?>
</div>
```

**Comment by dynasource** [comment]
you should. Try it out.

**Comment by Shybko** [comment]
I have some thoughts. When I load the page via ajax, there is loading html page with ListView and JS code that attach pjax to the just loaded listView, but in my code I cut only html I need, and embed it into my page, but JS I don't embed, that can be my problem.

So I think it would be better if pjax will be binded even to the dynamically loaded listView/GridView without JS injection (like it was in Yii 2.0.9).

**Comment by dynasource** [comment]
please try `Pjax::begin(['id'=>'this-is-a-unique-id']);`

**Comment by Shybko** [comment]
@dynasource 
After that the problem has went..
You were right, guys. Thank you.

**Comment by dynasource** [comment]
no problem. We thank you for reporting. It seems that the commit you are pointing to has changed default behavior. We are going to fix it with https://github.com/yiisoft/yii2/issues/12969
