### ISSUE TITLE
Unable to install Composer packages with current composer.lock

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#12946]
I'm trying to to install all project dependencies (including those that needed for development).

```
composer install
```

As a result I get the following error:

> Problem 1
> - Installation request for phpunit/phpunit 4.8.x-dev -> satisfiable by phpunit/phpunit[4.8.x-dev].
> - phpunit/phpunit 4.8.x-dev requires sebastian/environment ~1.3 -> no matching package found.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
> see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by dynasource** [comment]
issue confirmed.

**Comment by cebe** [comment]
this depends on the php version installed on dev machine. will fix it.

**Comment by cebe** [comment]
@arogachev @dynasource for verification, could you provide the php version you used for testing

**Comment by dynasource** [comment]
I simply did the following:
- use the guide https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#3-prepare-the-testing-environment-
- git clone https://github.com/yiisoft/yii2.git
- composer install

**Comment by dynasource** [comment]
my php version in CLI: 7.0.10

**Comment by cebe** [comment]
I have updated composer.json to contain a target platform so that dependencies should now be installable on different platforms. This works on travis as of https://travis-ci.org/yiisoft/yii2/builds/174347785 please also check if it works for you now.

**Comment by arogachev** [comment]
@cebe

```
php -v
PHP 5.6.11-1+deb.sury.org~trusty+1 (cli)
```

**Comment by cebe** [comment]
@arogachev does composer install work for you now?

**Comment by dynasource** [comment]
@cebe, it works now. Well done.

**Comment by arogachev** [comment]
@cebe Just checked it, now it works fine. Thank you for solving this problem.
