### ISSUE TITLE
Installing dependencies for development - composer install or composer update?

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#12947]
[Prepare the testing envinronment](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#3-prepare-the-testing-environment-) section of [Git workflow for Yii2 contributors](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) document says that we need to run `composer update` to install dependencies:

> run `composer update` to install dependencies (assuming you have composer installed globally).

But why not `composer install`? `composer.lock` exists in project and under version control. It guarantees that every developer will have exactly the same set of dependencies and their versions.

Or am I missing something? Is it related to features of Composer Asset Plugin?

Running `composer install` is not even possible now because of #12946.

**Comment by dynasource** [comment]
I agree. The docs can be more clear about this. I am also wondering why install is not working. In my local development environment I already have removed FXP, so I cannot check the update command.

**Comment by cebe** [comment]
related to #12946

**Comment by cebe** [comment]
the reason for adding composer update here is mainly the problem described in #12946. dependencies installed on one php version may not be installable on another version.

**Comment by cebe** [comment]
fixed by d429878776a7139c1daceb29e8524739a067ed6d, thanks for reporting!
