### ISSUE TITLE
Feature Request: Mapping params in UrlRule

### ISSUE THREAD

**Issue by webdevsega** [yiisoft/yii2#12954]
Sometimes it is necessary to make a parameter in the URL in a pretty format. In application, this parameter should come as a numeric value. It would be useful to make the possibility of mapping the parameters of the routing.

For example:
```php
[
    'pattern' => 'reviews/<typeId:(banks|leasing|refactoring)>',
    'route' => 'review/category',
    'mapping' => [
        'typeId' => [
            'banks' => Bank::TYPE,
            'leasing' => LeasingCompany::TYPE,
            'refactoring' => RefactoringCompany::TYPE
        ]
    ]
]

// result: /reviews/leasing
echo Url::to(['review/category', 'typeId' => LeasingCompany::TYPE])
// result: /reviews/banks
echo Url::to(['review/category', 'typeId' => Bank::TYPE])
```
Your opinion?

**Comment by cebe** [comment]
Why is `LeasingCompany::TYPE` not `'leasing'`?

**Comment by dynasource** [comment]
> Why is LeasingCompany::TYPE not 'leasing'?

exactly. Mapping is not required and an overkill.

**Comment by cebe** [comment]
At least not at this level, if you want mapping that would be done on DB layer and via a method in AR class.
