### ISSUE TITLE
composer update warning :  yiisoft/yii2-codeception is abandoned

### ISSUE THREAD

**Issue by kcloze** [yiisoft/yii2#12951]
### composer update get warning as blow:

```
Package yiisoft/yii2-codeception is abandoned, you should avoid using it. Use codeception/codeception instead.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.11
| Operating system | ubuntu

**Comment by SilverFire** [comment]
That's true. This summer codeception integration with Yii2 was [refactored](https://github.com/yiisoft/yii2-app-basic/pull/71) and `yiisoft/yii2-codeception` package is really abandoned.

http://codeception.com/for/yii
