### ISSUE TITLE
In afterSave, $changedAttributes include attributes with different types but same value

### ISSUE THREAD

**Issue by jhon100** [yiisoft/yii2#12950]
I have a form with a checkbox field 'desabilitado'. Saving the model with no changes in the form and testing the afterSave in model with this code:

```php   
public function rules()
{
        return [
            [['desabilitado',  'is_deleted'], 'integer'],
            [...]
        ];
}

 public function afterSave($insert, $changedAttributes)
{
        var_dump($changedAttributes['desabilitado']);
        var_dump($this['desabilitado']);
        die;
        [...]
}
```

the output is
```php  
int(1) 
string(1) "1"
```

Could be this corrected in the core, since the value has no changes, or we must typecast all attributes been verified? 
In the last case would bee good a mention in docs, actually it only say this

> $changedAttributes: The old values of attributes that had changed and were saved. You can use this parameter to take action based on the changes made for example send an email when the password had changed or implement audit trail that tracks all the changes. $changedAttributes gives you the old attribute values while the active record ($this) has already the new, updated values.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11-dev
| PHP version      |5.6.24

**Comment by jhon100** [comment]
The same occur with input text
```php   
int(6) 
string(1) "6"
```

**Comment by unclead** [comment]
i guess you have to use `yii\behaviors\AttributeTypecastBehavior` (see #12067)

**Comment by samdark** [comment]
@jhon100 please try as @unclead suggested and tell us if it worked.

**Comment by jhon100** [comment]
@samdark, yes it works. Thanks @unclead .
So for $changedAttributes work properly I need to use that behavior whenever I have non string fields in the model?

**Comment by samdark** [comment]
Yes.

**Comment by jhon100** [comment]
Ok @samdark , but in this case the docs should mention this. As I wrote in my first post there is nothing in the docs about the need of typecasting or that we can use the AttributeTypecastBehavior as a solution.

**Comment by samdark** [comment]
I guess you're getting data via forms, right?

**Comment by jhon100** [comment]
yes

**Comment by samdark** [comment]
The thing is that issue lies not within dirty attributes implementation. It works correctly. It lies into the fact that everything you submit via browser comes to us as a string and we have to convert it manually. Previously we did that via custom rules. Now there's `AttributeTypecastBehavior` for solving the issue.

`AttributeTypecastBehavior` is in the guide so I'm not sure where to mention it additionally...

**Comment by jhon100** [comment]
I understand that data submited via forms can affect other places than afterSave function but you may agree that remember all that is written in the guide is not easy. Now I found in http://www.yiiframework.com/doc-2.0/guide-db-active-record.html what you say and remember that I read it before.
As this issue is specific about the afterSave function, I think a mention in the afterSave function like this can help a lot.

> Remember that there is no automatic conversion for the values loaded from HTTP request, so $changedAttributes may not work properly. You may use yii\behaviors\AttributeTypecastBehavior to facilitate attribute values typecasting.
