### ISSUE TITLE
DB DATE_FORMAT in QueryBuilder

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [yiisoft/yii2#12953]
I have to create an example query using QueryBuilder, but I couldn't figure out how. Can this be done? 
And if not, how can it be added to QueryBuilder?
```mysql
SELECT * FROM contacts WHERE DATE_FORMAT(birthday,'%m%d') BETWEEN DATE_FORMAT('2016-11-01', '%m%d') AND DATE_FORMAT('2016-11-30', '%m%d')

```
I know that DATE_FORMAT supports mysql, oracle has a different function
http://www.sqlines.com/mysql-to-oracle/date_format

**Comment by dynasource** [comment]
ever tried Expression? http://www.yiiframework.com/doc-2.0/yii-db-expression.html

**Comment by mariuszkrzaczkowski** [comment]
Yes I checked with Expression does not work.

**Comment by mariuszkrzaczkowski** [comment]
Why do you close when the problem is not solved?

**Comment by samdark** [comment]
How exactly it doesn't work? Which syntax have you tried?

**Comment by mariuszkrzaczkowski** [comment]
```php
$row = (new \yii\db\Query())
		->from('vtiger_contactsubdetails')
		->where(new \yii\db\Expression("DATE_FORMAT(birthday, '%m%d') BETWEEN DATE_FORMAT('2016-11-01', '%m%d') AND DATE_FORMAT('2016-11-30', '%m%d')"))->one();

```

**Comment by mariuszkrzaczkowski** [comment]
I get an error:
Uncaught exception 'PDOException' with message 'SQLSTATE[42883]: Undefined functio

**Comment by samdark** [comment]
Can you post the rest of the error?

**Comment by mariuszkrzaczkowski** [comment]
Updated the an earlier post

**Comment by dynasource** [comment]
https://www.drupal.org/node/991898

**Comment by Alex-Code** [comment]
What RDBMS are you using?

**Comment by mariuszkrzaczkowski** [comment]
@dynasource 
"SQLSTATE[42883]: Undefined function" This is the message from the database engine 

@Alex-Code
PostgreSQL

**Comment by dynasource** [comment]
does that function exists? https://www.postgresql.org/docs/7.4/static/functions-formatting.html

**Comment by Alex-Code** [comment]
PostgreSQL doesn't have a `DATE_FORMAT` function.
You'll need to use https://www.postgresql.org/docs/8.2/static/functions-formatting.html
or create your own `DATE_FORMAT` function wrapper.

**Comment by mariuszkrzaczkowski** [comment]
I know the function doesn't exist that's why I'm asking how to do it in QueryBuilder, so that it works with all available databases.
So YII doesn't support this function?

**Comment by samdark** [comment]
Nope, it does not. There's no way we can support everything.

**Comment by alexraputa** [comment]
@mariuszkrzaczkowski, try this: 
`$row = (new \yii\db\Query())
    ->from('vtiger_contactsubdetails')
    ->where(['between', 'birthday', '2016-11-01', '2016-11-30'])
    ->one();`

**Comment by mariuszkrzaczkowski** [comment]
It would work, but I wanted the query to ignore the year

**Comment by Alex-Code** [comment]
Depending on your project you could create an install script that creates function wrappers depending on the db system.
http://okbob.blogspot.co.uk/2009/08/mysql-functions-for-postgresql.html
Part way down that page is an example.

**Comment by alexraputa** [comment]
@mariuszkrzaczkowski, if so:
$row = (new \yii\db\Query())->from('vtiger_contactsubdetails')->where(['between', new Expression("to_char(birthday, 'MM-DD')"), '11-01', '11-30'])->one();

**Comment by mariuszkrzaczkowski** [comment]
@Alex-Code
The problem with creating functions is that not all servers allow for that, and this is an app that can be installed on any server.

@alexraputa 
This is not a solution to the problem.

**Comment by samdark** [comment]
I understand what you need but that's quite specific requirement so I'd suggest implementing it in your own subclass.
