### ISSUE TITLE
Composer: Could not scan for classes inside "path/to/app/vendor/phpunit/php-timer/src/" which does not appear to be a file nor a folder (macOS sierra)

### ISSUE THREAD

**Issue by ta4** [yiisoft/yii2#12958]
Try to install Yii2 advanced template and get error
`Composer: Could not scan for classes inside "path/to/app/vendor/phpunit/php-timer/src/" which does not appear to be a file nor a folder`

This error happens after "composer install" (and update too).

Error message shows after line "Generating autoload files".

Installing previous Yii version (2.0.9) without problems.

"vendor/phpunit/php-timer/src" is empty

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |5.6.25
| Operating system |macOS Sierra

**Comment by samdark** [comment]
Looks like permissions issue. Make sure your process can write to project directories.

**Comment by ta4** [comment]
@samdark I tried, process can write to project directories. But derictories phpunit is empty. Old Yii 2 (for example "yiisoft/yii2": ">=2.0.6",) versions installs successfully. This issue happens after update to last macOS version (sierra).

**Comment by ta4** [comment]
Issue with "codeception/base": "^2.2.3". Thanks @githubjeka

**Comment by warmaris** [comment]
Same problem after update some packages on Linux Mint 18.3. Solved after composer self-update and fixing permissions of .composer folder.

**Comment by yohandh** [comment]
How did you resolve this @ta4. I am getting following error:
**[RuntimeException]
/vendor/codeception/module-yii2/src/" which does not appear to be a file nor a folder**
