### ISSUE TITLE
link with data-method still affects form client validation

### ISSUE THREAD

**Issue by DarthLegiON** [yiisoft/yii2#12965]
I have a form, here is its ending code:
```php
...
<?= $form->field($orderForm, 'acceptOfferta')->checkbox(['label' => 'Accept?'])->label(false) ?>
    <br>
    <?php echo Html::submitButton(Html::mIcon('done') . 'Activate', ['class' => 'btn btn-success btn-raised']);
    echo Html::a(Html::mIcon('clear') . 'Cancel', ['cancel-order', 'id' => $order->id, 'returnPage' => 'index'], ['class' => 'btn btn-primary', 'data-method' => 'post']);
    ActiveForm::end();
    ?>
```
Validation rules on checkbox:
```php
[['acceptOfferta'], 'boolean'],
[['acceptOfferta'], 'compare', 'operator' => '==', 'compareValue' => true, 'message' => 'Error message'],
        
```
If I click the "a" tag and didn't check the box, error message appears instead of submission to 'cancel-order'. 
Disabling client validation removes problem, but it is only a temporary solution. I cannot move link outside the form.

I saw issue #8161 and related, they were declared fixed, but I still have problem on Yii 2.0.10. Browser: Chrome.

**Comment by DarthLegiON** [comment]
@cebe can you tell me, has this issue been verified yet?

**Comment by cebe** [comment]
no, it is still labeled "status:to be verified".

**Comment by DarthLegiON** [comment]
@cebe how can this process be speeded up? I still have this problem.

**Comment by cebe** [comment]
You could try to fix the problem yourself or look at the code and propose a possible solution. Having a unit test might also be helpful.

**Comment by njasm** [comment]
pushing up this issue.. we need a solution for it.. how about updating the labes to discussion? i believe this is already verified? I'm also having this issue.. 

although
> Disabling client validation removes problem, but it is only a temporary solution. I cannot move link outside the form.

with 2.0.12, and clientValidation = false, ajaxValidation = true, the issue is present.

**Comment by DarthLegiON** [comment]
@njasm there have to be no any client-side checks in the form for successful following the link. But that's not right, button must be isolated from form it placed in. Maybe we should look for bugs in javascript, find it and submit a pull request but I haven't enough time for it and it requires waiting for next release.
I hoped this bug fixed in 2.0.12 or 2.0.13 but I see developers team has another priorities, that's sad :(

**Comment by njasm** [comment]
@DarthLegiON by sayin
> there have to be no any client-side checks in the form for successful following the link

you say that not even ajaxValidation should be performed?

I've worked around the problem by not using the `data-*`attributes and implement my own JS login.
besides `data-method`, `data-confirm` only also makes the achor be binded by ActiveForm JS logic.

Indeed, lets start by pointing the code that should be refactored, and try to find a potential solution for it? that way we might help core developers with a push request? do you have time to do some experiments in a test branch?

**Comment by DarthLegiON** [comment]
@njasm clientValidation **and** ajaxValidation must be shut down to make this feature work inside a form. In another case it triggers some form events and starts validation, and if it fails, request terminates.

>do you have time to do some experiments in a test branch?
Maybe, but not right now.

**Comment by DarthLegiON** [comment]
I don't know when but it was fixed. At least there are no bugs in my case now. Thanks.

**Comment by DarthLegiON** [comment]
@njasm what about your problem now?
