### ISSUE TITLE
GridView and Methods

### ISSUE THREAD

**Issue by hik200** [yiisoft/yii2#12964]
### What steps will reproduce the problem?
```
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            'destination',
            'code',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]->off('change'))?>
```
### What is the expected result?
Prevent processing for change event
### What do you get instead?
Call to a member function off() on a non-object

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by dynasource** [comment]
you should use (new GridView())->off()

**Comment by hik200** [comment]
but where i should use widget?

**Comment by dynasource** [comment]
```php
$grid = new GridView();
$grid ->off();
$grid->run(); //similar as widget()
```

**Comment by hik200** [comment]
Thx this all!

**Comment by hik200** [comment]
how name is Prevent processing for change event, if i make `$grid->off('change')` it don`t work
