### ISSUE TITLE
Wrong order of migrations in `migrate/down all`

### ISSUE THREAD

**Issue by evgen-d** [yiisoft/yii2#12974]
### What steps will reproduce the problem?
console config:
```php
'controllerMap' => [
    'migrate' => [
        'class' => 'yii\console\controllers\MigrateController',
        'migrationNamespaces' => [
            'app\migrations',
            'app\modules\mymodule\migrations',
        ],
        'migrationPath' => null,
    ],
],
```
apply some migrations:
```
app\migrations\M140506102106One
app\migrations\M160909083544Two
app\migrations\M160930135248Three
app\modules\mymodule\migrations\M161018124749Four
app\modules\mymodule\migrations\M161025123028Five
app\migrations\M161110133341Six
```
In DB this looks like:

| version                                                                              | apply_time     |
| ------------------------------------------------------------------------| ----------------- |
| app\modules\mymodule\migrations\M161025123028Five | 1478886628  |
| app\migrations\M161110133341Six                                   | 1478886628  |
| app\modules\mymodule\migrations\M161018124749Four | 1478886627  |
| app\migrations\M160930135248Three                              | 1478886592  |
| app\migrations\M160909083544Two                                 | 1478886589  |
| app\migrations\M140506102106One                                 | 1478886588  |

Then run `./yii migrate/down all`

### What is the expected result?

I expected the following order of rollback:

```
app\migrations\M161110133341Six
app\modules\mymodule\migrations\M161025123028Five
app\modules\mymodule\migrations\M161018124749Four
app\migrations\M160930135248Three
app\migrations\M160909083544Two
app\migrations\M140506102106One
```

### What do you get instead?

I got the following order of rollback:

```
app\modules\mymodule\migrations\M161025123028Five
app\migrations\M161110133341Six
app\modules\mymodule\migrations\M161018124749Four
app\migrations\M160930135248Three
app\migrations\M160909083544Two
app\migrations\M140506102106One
```

I got this because two migrations have `apply_time` 1478886628. Function `getMigrationsHistory` gets data from DB by this command:
```php
$query->select(['version', 'apply_time'])
  ->from($this->migrationTable)
  ->orderBy('apply_time DESC, version DESC')
  ->limit($limit)
  ->createCommand($this->db)
  ->queryAll();
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | master
| PHP version      | 7.0
| Operating system | Fedora 24

**Comment by SilverFire** [comment]
Merged https://github.com/yiisoft/yii2/commit/4b1f17db8ff754bef7c5ba1452a443714a888a83
