### ISSUE TITLE
$childRoles = Yii::$app->authManager->getChildRoles($id);  work wrong

### ISSUE THREAD

**Issue by murat-celik** [yiisoft/yii2#12976]
$id is my any role and  want to get childRoles. But getChildRoles($id) return and my $id role.

![bbf910bd325a4613af346ae65d576e68](https://cloud.githubusercontent.com/assets/10754763/20236863/b770eefa-a8cb-11e6-816c-71219670e9f3.png)

 Yii version : 2.0.10
PHP version : 5.6.12  
Operating system : mac os x sierra

**Comment by samdark** [comment]
Please provide code you've created RBAC hierarchy with and code that you're calling to get the issue.

**Comment by evgen-d** [comment]
@murat-celik 
[`getChildRoles()`](http://www.yiiframework.com/doc-2.0/yii-rbac-managerinterface.html#getChildRoles()-detail) return `yii\rbac\Role[]`

> All roles directly adding to the role. The array is indexed by the role names. First element is a Role item that are getting by $roleName.

So this is not a bug

**Comment by samdark** [comment]
@evgen-d is right.

**Comment by murat-celik** [comment]
1) I have one role. 
2) Role name is "Sevko". 
3) "Sevko" no have any Child Role.
4)  Run  getChildRoles("Sevko").  
5) Return yii\rbac\Role[].
6) In this return exist also "Sevko" Role item.
7)  This is really true usage ? 

@evgen-d @samdark

**Comment by samdark** [comment]
Well, at least it is what's implemented and what is described in phpdoc.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/324b38d504b96b9bfc739094accda1f36a43548c
