### ISSUE TITLE
testBindParamValue test is failing with PostgreSQL and HHVM 3.15.2

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#12982]
Extracted from #12936 and #12971.

For example see this [build job](https://travis-ci.org/yiisoft/yii2/builds/175302218).

**PostgreSQL version:** 9.3.15
**HHVM version:** 3.15.2

```
yii\tests\unit\framework\db\pgsql\CommandTest::testBindParamValue

Failed asserting that false is true.

/home/travis/build/yiisoft/yii2/tests/framework/db/CommandTest.php:199

/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:47
```

Related code:

```php
$command = $db->createCommand('SELECT [[int_col]], [[char_col]], [[float_col]], [[blob_col]], [[numeric_col]], [[bool_col]] FROM {{type}}');
// $command->prepare();
// $command->pdoStatement->bindColumn('blob_col', $bc, \PDO::PARAM_LOB);
$row = $command->queryOne();
$this->assertEquals($intCol, $row['int_col']);
$this->assertEquals($charCol, $row['char_col']);
$this->assertEquals($floatCol, $row['float_col']);
if ($this->driverName === 'mysql' || $this->driverName === 'sqlite' || $this->driverName === 'oci') {
    $this->assertEquals($blobCol, $row['blob_col']);
} else {
    $this->assertTrue(is_resource($row['blob_col'])); // Test fails here
    $this->assertEquals($blobCol, stream_get_contents($row['blob_col']));
}
```

**Comment by SilverFire** [comment]
Thank you for the report. Do you have any suggestions?

**Comment by arogachev** [comment]
Not yet. Unfortunately I have not much experience with HHVM, but will try to see what can cause this error.

**Comment by photodude** [comment]
Likely need to look at your pgsql driver methods for `createCommand()` and `queryOne()`

The failure here seems to be indicating the query failed since $row['blob_col'] is not a resource

**Comment by SilverFire** [comment]
HHVM support is dropped. #14178

**Comment by samdark** [comment]
For 2.1 it is. For 2.0 it is not.

**Comment by cebe** [comment]
I think we should not actively drop support on 2.0 and still handle issues if they get reported, but unless someone reports it actively (not we see it in failing tests), I see no need to create a workaround to make it work.

**Comment by samdark** [comment]
OK. Makes sense.
