### ISSUE TITLE
testSaveSerializedObject test is failing with PostgreSQL and HHVM 3.15.2

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#12981]
Extracted from #12936 and #12971.

For example see this [build job](https://travis-ci.org/yiisoft/yii2/builds/175302218).

**PostgreSQL version:** 9.3.15
**HHVM version:** 3.15.2

```
yii\tests\unit\framework\db\pgsql\CommandTest::testSaveSerializedObject

Failed asserting that 0 matches expected 1.

/home/travis/build/yiisoft/yii2/tests/framework/db/pgsql/CommandTest.php:86

/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:47
```

Related code:

```php
$db = $this->getConnection();

$command = $db->createCommand()->insert('type', [
    'int_col' => 1,
    'char_col' => 'serialize',
    'float_col' => 5.6,
    'bool_col' => true,
    'blob_col' => serialize($db),
]);
$this->assertEquals(1, $command->execute()); // Test fails here
```

**Comment by SilverFire** [comment]
Thank you for the report. Do you have any suggestions?

**Comment by SilverFire** [comment]
Thank you for the report. Do you have any suggestions?

**Comment by arogachev** [comment]
Not yet. Unfortunately I have not much experience with HHVM, but will try to see what can cause this error.

**Comment by photodude** [comment]
Likely need to look at your pgsql driver methods for `createCommand()`, `insert()`, and `execute()`

note: `createCommand()` is common to both failing tests.

**Comment by cebe** [comment]
See my comments at https://github.com/yiisoft/yii2/pull/12971#issuecomment-260211160 and https://github.com/yiisoft/yii2/pull/12971#issuecomment-260211253

**Comment by SilverFire** [comment]
HHVM support is dropped. #14178
