### ISSUE TITLE
DetailView::widget contentOptions not working

### ISSUE THREAD

**Issue by omidgh88** [yiisoft/yii2#12997]
my code is : 
```php
<?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    [
                        'attribute' => 'sabtaresh_model',
                        'contentOptions' => ['class' => 'text-center'],
                        'headerOptions' => ['class' => 'text-center'],
                    ],
                ],
                ]) ?>
```

and nothing appear in td or th class. any advice?

p.s : why new lines didn't show in my comment?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 5.6
| Operating system | win,xampp

**Comment by dynasource** [comment]
can you post the HTML result please?

**Comment by omidgh88** [comment]
@dynasource thanks for your response : 
`<tr><th>مدل ثبتارش</th><td><span dir="ltr">420i (COUPE)(A/T)</span></td></tr>`
but i change code to achive my goal to : 
`[
                        'attribute' => 'sabtaresh_model',
                        'value' => '<span dir="ltr">'.$model->sabtaresh_model.'</span>',
                        'format' => 'raw',
                        'contentOptions' => ['class' => 'text-center'],
                        'headerOptions' => ['class' => 'text-center'],
                    ],`

**Comment by dynasource** [comment]
can you take a look at https://github.com/yiisoft/yii2/blob/master/framework/widgets/DetailView.php and post us your findings, whether this is an issue or not?

**Comment by omidgh88** [comment]
oh sorry, i found that these options are availible in 2.0.10. mine is 2.0.9
thanks
