### ISSUE TITLE
[Bug] The session info and Yii::$app->user->id is inconsistent when session is timeout.

### ISSUE THREAD

**Issue by niceapple** [yiisoft/yii2#12995]
### What steps will reproduce the problem?
After update to version 2.0.10, the session and Yii::$app->user->id is inconsistent.

When user login, wait for a long time, **session is timeout**, if checking permission with roles, it throws **"#403 Forbidden"**, **but Yii::$app->user->id still keep the last user id.**

### What is the expected result?
Keep the consistent between the **session info** and **Yii::$app->user->id** when session is timeout.

### What do you get instead?
If we use roles '@' it recognize user still log in because of **Yii::$app->user->isGuest is still false**, but if checking specific roles as 'admin'..., it throws null.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04.4 LTS

**Comment by samdark** [comment]
Are you sure behavior is different in 2.0.9?

**Comment by niceapple** [comment]
**When does the issue occur?**
Open Yii2 application, log in, then close the browser.

**What do you see?**
Yii::$app->session->id IS NULL
Yii::$app->user->id is 1 (latest user id)

**What was the expected result?**
Yii::$app->user->id = Yii::$app->session->id = NULL is session is timeout.

**Can you supply us with a stacktrace? (optional)**
No stacktrace

**Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)**

![2016-11-14_222703](https://cloud.githubusercontent.com/assets/925738/20271359/266d7344-aabd-11e6-89ad-71efa1e3ea18.png)
![2016-11-14_224237](https://cloud.githubusercontent.com/assets/925738/20271357/266b7ab2-aabd-11e6-9859-f24e97204702.png)
![2016-11-14_224713](https://cloud.githubusercontent.com/assets/925738/20271358/266d70b0-aabd-11e6-90f3-3d9956f0d6bc.png)
![yii2-after-update-to-2 0 10](https://cloud.githubusercontent.com/assets/925738/20271360/2676d272-aabd-11e6-8048-d5a989b69316.png)

**Comment by niceapple** [comment]
By the way, 
If I downgrade to 2.0.8 `"yiisoft/yii2": "2.0.8",` it works normally.

Thanks for your support!

**Comment by SilverFire** [comment]
@niceapple could you find commit that introduces wrong behavior using [git bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search), please?

**Comment by alexxxst** [comment]
I have the same bug and stacktrace for it:

```
2016-12-13 11:32:44 [195.42.*.*][206][-][error][yii\base\ErrorException:2] yii\base\ErrorException: session_regenerate_id(): Session write failed. ID: user (path: /var/lib/php/session) in /var/www/basic/vendor/yiisoft/yii2/web/Session.php:282
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'session_regener...', '/var/www/basic/...', 282, Array)
#1 /var/www/basic/vendor/yiisoft/yii2/web/Session.php(282): session_regenerate_id(false)
#2 /var/www/basic/vendor/yiisoft/yii2/web/DbSession.php(103): yii\web\Session->regenerateID(false)
#3 /var/www/basic/vendor/yiisoft/yii2/web/User.php(626): yii\web\DbSession->regenerateID(true)
#4 /var/www/basic/vendor/yiisoft/yii2/web/User.php(299): yii\web\User->switchIdentity(Object(app\models\User), 2592000)
#5 /var/www/basic/vendor/yiisoft/yii2/web/User.php(682): yii\web\User->loginByCookie()
#6 /var/www/basic/vendor/yiisoft/yii2/web/User.php(188): yii\web\User->renewAuthStatus()
#7 /var/www/basic/vendor/yiisoft/yii2/web/User.php(340): yii\web\User->getIdentity()
#8 /var/www/basic/vendor/yiisoft/yii2/base/Component.php(130): yii\web\User->getIsGuest()
#9 /var/www/panel3/panel/controllers/TicketController.php(65): yii\base\Component->__get('isGuest')
#10 /var/www/basic/vendor/yiisoft/yii2/base/Controller.php(152): app\controllers\TicketController->beforeAction(Object(yii\base\InlineAction))
#11 /var/www/basic/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('view', Array)
#12 /var/www/basic/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('ticket/view', Array)
#13 /var/www/basic/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 /var/www/panel3/panel/web/index.php(22): yii\base\Application->run()
#15 {main}
```

Also I'm on php 7.0.14 and sessions stored in DB (app\components\DbSession) – at least this is strange.

**Comment by SilverFire** [comment]
@alexxxst your problem is not related to this issue. Most probably PHP tries to save session to you local file system.

> Session write failed. ID: user (path: /var/lib/php/session)

**Comment by alexxxst** [comment]
@SilverFire I have same behavior described by @niceapple and this stacktrace appeared in log at same time.

> Most probably PHP tries to save session to you local file system.

But my application stores sessions in DB. Why and how?

**Comment by SilverFire** [comment]
O_o

Sorry, overseen `/var/www/basic/vendor/yiisoft/yii2/web/DbSession.php` in your stacktrace.

**Comment by cebe** [comment]
sounds like https://github.com/yiisoft/yii2/issues/9438#issuecomment-131622124

**Comment by alexxxst** [comment]
Can reproduce it in 2.0.11

`yii\base\ErrorException: session_regenerate_id(): Session write failed. ID: user (path: /var/lib/php/session) in /var/www/basic/vendor/yiisoft/yii2/web/Session.php:283
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'session_regener...', '/var/www/basic/...', 283, Array)
#1 /var/www/basic/vendor/yiisoft/yii2/web/Session.php(283): session_regenerate_id(false)
#2 /var/www/basic/vendor/yiisoft/yii2/web/DbSession.php(103): yii\web\Session->regenerateID(false)
#3 /var/www/basic/vendor/yiisoft/yii2/web/User.php(618): yii\web\DbSession->regenerateID(true)
#4 /var/www/basic/vendor/yiisoft/yii2/web/User.php(292): yii\web\User->switchIdentity(Object(app\models\User), 2592000)
#5 /var/www/basic/vendor/yiisoft/yii2/web/User.php(674): yii\web\User->loginByCookie()
#6 /var/www/basic/vendor/yiisoft/yii2/web/User.php(188): yii\web\User->renewAuthStatus()
#7 /var/www/basic/vendor/yiisoft/yii2/web/User.php(333): yii\web\User->getIdentity()
#8 /var/www/basic/vendor/yiisoft/yii2/base/Component.php(132): yii\web\User->getIsGuest()
#9 /var/www/panel3/panel/controllers/ServiceController.php(75): yii\base\Component->__get('isGuest')
#10 /var/www/basic/vendor/yiisoft/yii2/base/Controller.php(154): app\controllers\ServiceController->beforeAction(Object(yii\base\InlineAction))
#11 /var/www/basic/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('list', Array)
#12 /var/www/basic/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('service/list', Array)
#13 /var/www/basic/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 /var/www/panel3/panel/web/index.php(22): yii\base\Application->run()
#15 {main}`

**Comment by SilverFire** [comment]
The originally reported problem is NOT verified.

I have tried to reproduce the problem using clear Yii Basic Application template with Yii 2.0.11

1. Configure components as follows:

```php
'session' => [
    'GCProbability' => 100, // set GC probability to 100%
],
'user' => [
    'identityClass' => User::class, // user class from Yii basic template
    'authTimeout' => 6,
    'enableAutoLogin' => false,
]
```

2. Add lines to `index.php` view:

```
    Guest: <?php var_dump(Yii::$app->user->isGuest); ?><br />
    user-id: <?php var_dump(Yii::$app->user->id); ?><br />
    session-id: <?php var_dump(Yii::$app->session->id); ?><br />
```

3. Login. See on the index page:

```
Guest:
/var/www/basic.yii2.local/views/site/index.php:17:boolean false

user-id:
/var/www/basic.yii2.local/views/site/index.php:18:string '101' (length=3)

session-id:
/var/www/basic.yii2.local/views/site/index.php:19:string '378vhk5mnacq5nl6s52ebgqfo2' (length=26)

```

4. Refresh page immedieately. See the same.

5. Wait 6+ seconds (according to the `authTimeout` property), refresh page. See:

```
Guest:
/var/www/basic.yii2.local/views/site/index.php:17:boolean true

user-id:
/var/www/basic.yii2.local/views/site/index.php:18:null

session-id:
/var/www/basic.yii2.local/views/site/index.php:19:string '4c4bq19ln414ce3k4i9pvtgng2' (length=26)
```


In case I'm reproducing this problem in a wrong way - please, post the right way to reproduce the decribed problem. Thank you!

**Comment by SilverFire** [comment]
@alexxxst your problem is definitely related to #9438 and should be discussed there.
