### ISSUE TITLE
onchange, activeDropDownList  donot working 

### ISSUE THREAD

**Issue by skcn022** [yiisoft/yii2#12998]
```php
$form = ActiveForm::begin(); 
    echo Html::activeDropDownList($model, 
                'client_key',
                ArrayHelper::map(ListClient::find()->all(), 'client_key', 'cli_stat_name_l'), 
                ['prompt'=>'All Clients...'],
                ['onchange'=>'this.form.submit()']);
    ActiveForm::end(); 
```
activeDropDownList  onchange didnot working when have ['prompt'=>'All Clients...'], 

I comment ['prompt'=>'All Clients...'],  it work

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | PHP Version 5.6.3
| Operating system | windows 7

**Comment by Alex-Code** [comment]
Is your example above as it is in your code? If so you've got the options as two separate parameters which is why it'll work when you comment it out.

Try
```php
echo Html::activeDropDownList(
    $model, 
    'client_key',
    ArrayHelper::map(ListClient::find()->all(), 'client_key', 'cli_stat_name_l'), 
    ['prompt'=>'All Clients...', 'onchange'=>'this.form.submit()']
);
```

**Comment by SilverFire** [comment]
@Alex-Code is right
