### ISSUE TITLE
Include [skip js] in commit message for skipping js tests in Travis

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#12992]
I think this can be useful, because 99% of code changes are related to PHP. By including `[skip js]` we can skip both installing dependencies (`npm install`) and running tests (`npm test`) and speed up Travis builds. I think this can be done with custom git hook, also we need somehow access commit message in Travis.

**P.S.** However maybe it's not worth implementing and it's just me overcomplicating things.

This is just a raw idea, decided to share it.

**Comment by samdark** [comment]
It will pollute log messages much. Is there a way to do it w/o marking commit messages with it? Closing this issue. Let's discuss in https://github.com/yiisoft/yii2/issues/12993
