### ISSUE TITLE
(oracle 11g)The create action is saving the values incorrectly

### ISSUE THREAD

**Issue by thiagoluis** [yiisoft/yii2#12991]
### What steps will reproduce the problem?
Using Oracle Database 11g.

I created a CRUD for the table:

tb_domain (sq_domain, no_domain, nr_matricula).

The create action is saving the values incorrectly.

The update and delete action is correct.

### What is the expected result?
The values must be registered correctly.

### What do you get instead?
After executing the creation action, the no_domain column has the value of the nr_domain.
![create](https://cloud.githubusercontent.com/assets/7280981/20247743/aca908c2-a9bb-11e6-904b-0613825fe68d.png)
![view](https://cloud.githubusercontent.com/assets/7280981/20247746/bbb6833a-a9bb-11e6-9bb7-9fe4aa579313.png)

### Additional info

**script**
```
CREATE SEQUENCE  "SQ_DOMINIO";

CREATE TABLE "TB_DOMINIO"
 (	"SQ_DOMINIO" NUMBER(6,0),
	"NO_DOMINIO" VARCHAR2(40 BYTE),
	"NR_MATRICULA" NUMBER(6,0)
);

create or replace TRIGGER "TG_TB_DOMINIO" before insert
on TB_DOMINIO for each row
declare
    integrity_error  exception;
    errno            integer;
    errmsg           char(200);
    dummy            integer;
    found            boolean;

begin
    if :new.SQ_DOMINIO IS NULL then
      select SQ_DOMINIO.NEXTVAL INTO :new.SQ_DOMINIO from dual;
   end if;
exception
    when integrity_error then
       raise_application_error(errno, errmsg);
end;
```

**action**
```
    /**
     * Creates a new Dominio model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Dominio();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->SQ_DOMINIO]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
```

**model**
```
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "TB_DOMINIO".
 *
 * @property integer $SQ_DOMINIO
 * @property string $NO_DOMINIO
 * @property integer $NR_MATRICULA
 *
 * @property TBITEMDOMINIO[] $tBITEMDOMINIOs
 * @property TBQUESTAO[] $tBQUESTAOs
 */
class Dominio extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'TB_DOMINIO';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // [['SQ_DOMINIO'], 'required'],
            // [['SQ_DOMINIO'], 'unique'],
            [['NR_MATRICULA'], 'integer'],
            [['NO_DOMINIO'], 'string', 'max' => 40],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'SQ_DOMINIO' => 'Sq  Dominio',
            'NO_DOMINIO' => 'No  Dominio',
            'NR_MATRICULA' => 'Nr  Matricula',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTBITEMDOMINIOs()
    {
        return $this->hasMany(TBITEMDOMINIO::className(), ['SQ_DOMINIO' => 'SQ_DOMINIO']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTBQUESTAOs()
    {
        return $this->hasMany(TBQUESTAO::className(), ['SQ_DOMINIO' => 'SQ_DOMINIO']);
    }

}
```

**form**
```
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Dominio */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="dominio-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'NO_DOMINIO')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'NR_MATRICULA')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.5.9
| Operating system | Ubuntu Trusty 64bits

**Comment by samdark** [comment]
Can you check which SQL is executed? Could be done via debug panel.

**Comment by thiagoluis** [comment]
I forced an error by placing an invalid expression in the NR_MATRICULA column:

```
public function beforeSave($insert)
    {
        if ($insert) {
                $this->NR_MATRICULA = new \yii\db\Expression('abc');
        }
        return parent::beforeSave($insert);
    }
```

> SQLSTATE[HY000]: General error: 984 OCIStmtExecute: ORA-00984: column not allowed here
> (/usr/lib/php/PDO_OCI-1.0/oci_statement.c:142)
> The SQL being executed was: INSERT INTO "TB_DOMINIO" ("NO_DOMINIO", "NR_MATRICULA") VALUES ('TEST', abc) RETURNING "SQ_DOMINIO" INTO :qp1

**Comment by samdark** [comment]
It looks normal, isn't it? Are you sure it's not one of your triggers?

**Comment by thiagoluis** [comment]
I dropped the TG_DOMINIO trigger and forced an error in the expression to display the command:

```
    public function beforeSave($insert)
    {
        if ($insert) {
                $this->SQ_DOMINIO = new \yii\db\Expression('xSQ_DOMINIO.nextval');
        }
        return parent::beforeSave($insert);
    }
```

> 
> SQLSTATE[HY000]: General error: 2289 OCIStmtExecute: ORA-02289: sequence does not exist
> (/usr/lib/php/PDO_OCI-1.0/oci_statement.c:142)
> The SQL being executed was: INSERT INTO "TB_DOMINIO" ("NO_DOMINIO", "NR_MATRICULA", "SQ_DOMINIO") VALUES ('TEST', 123, xSQ_DOMINIO.nextval) RETURNING "SQ_DOMINIO" INTO :qp2

I have successfully execute the command on the client, but in the app the behavior continues incorrect.

**In client** OK
`INSERT INTO "TB_DOMINIO" ("NO_DOMINIO", "NR_MATRICULA", "SQ_DOMINIO") VALUES ('TEST', 123, SQ_DOMINIO.nextval);
`

**Comment by samdark** [comment]
OK. Can you execute it w/o forcing any errors and check debugger log for SQL then?

**Comment by thiagoluis** [comment]
**5828f47db7384	2016-11-13 23:17:17	10.0.0.1	4	0	POST	No	http://php.localhost/brb/dominio/create**

```
23:17:17.798	48.9 ms	SELECT	SELECT D.CONSTRAINT_NAME, D.CONSTRAINT_TYPE, C.COLUMN_NAME, C.POSITION, D.R_CONSTRAINT_NAME,
        E.TABLE_NAME AS TABLE_REF, F.COLUMN_NAME AS COLUMN_REF,
        C.TABLE_NAME
FROM ALL_CONS_COLUMNS C
INNER JOIN ALL_CONSTRAINTS D ON D.OWNER = C.OWNER AND D.CONSTRAINT_NAME = C.CONSTRAINT_NAME
LEFT JOIN ALL_CONSTRAINTS E ON E.OWNER = D.R_OWNER AND E.CONSTRAINT_NAME = D.R_CONSTRAINT_NAME
LEFT JOIN ALL_CONS_COLUMNS F ON F.OWNER = E.OWNER AND F.CONSTRAINT_NAME = E.CONSTRAINT_NAME AND F.POSITION = C.POSITION
WHERE C.OWNER = 'QST'
   AND C.TABLE_NAME = 'TB_DOMINIO'
ORDER BY D.CONSTRAINT_NAME, C.POSITION
```


```
23:17:17.794	1.8 ms	SELECT	SELECT a.column_name, a.data_type, a.data_precision, a.data_scale, a.data_length,
    a.nullable, a.data_default,
    com.comments as column_comment
FROM ALL_TAB_COLUMNS A
inner join ALL_OBJECTS B ON b.owner = a.owner and ltrim(B.OBJECT_NAME) = ltrim(A.TABLE_NAME)
LEFT JOIN all_col_comments com ON (A.owner = com.owner AND A.table_name = com.table_name AND A.column_name = com.column_name)
WHERE
    a.owner = 'QST'
    and b.object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
    and b.object_name = 'TB_DOMINIO'
ORDER by a.column_id
```
`23:17:17.852	1.2 ms	INSERT	INSERT INTO "TB_DOMINIO" ("NO_DOMINIO", "NR_MATRICULA", "SQ_DOMINIO") VALUES ('TEST', 123, SQ_DOMINIO.nextval) RETURNING "SQ_DOMINIO" INTO :qp2``

```
23:17:17.847	0.7 ms	SELECT	SELECT ud.referenced_name as sequence_name
FROM user_dependencies ud
JOIN user_triggers ut on (ut.trigger_name = ud.name)
WHERE ut.table_name = 'TB_DOMINIO'
AND ud.type='TRIGGER'
AND ud.referenced_type='SEQUENCE'
```

**5828f47dda22a	2016-11-13 23:17:18	10.0.0.1	4	0	GET	No	http://php.localhost/brb/dominio/view?id=189**

![client_query](https://cloud.githubusercontent.com/assets/7280981/20249843/41d7ce06-a9e9-11e6-8e7d-e8d70acf03bb.png)

There is no evidence of this insertion in the way it is presented. :(

**Comment by samdark** [comment]
What if you'll execute

```sql
INSERT INSERT INTO "TB_DOMINIO" ("NO_DOMINIO", "NR_MATRICULA", "SQ_DOMINIO") VALUES ('TEST', 123, SQ_DOMINIO.nextval)
```

w/o Yii via your GUI software?

**Comment by thiagoluis** [comment]
It works, the record is inserted successfully. Also with createCommand () worked.

**Comment by samdark** [comment]
Are there any additional update or insert queries during the same request?

**Comment by thiagoluis** [comment]
No, things are like the gii generated.

**Comment by samdark** [comment]
Then I don't get how it happens at all. Queries logged are exactly what is executed.

**Comment by samdark** [comment]
It could be PDO bug or something though. Do you have a server with other software versions to try it?

**Comment by thiagoluis** [comment]
Really should be it. Upgraded the oci8, I'll test other versions and say what happened. Thank you!

**Comment by thiagoluis** [comment]
The problem was that I installed a version of oci8 incompatible with my version of php.

After installing version 2.0.12 compatible, things worked as expected.

Many thanks, sorry for that!

**Comment by thiagoluis** [comment]
The issue has not been resolved.

I executed the action with createCommand () and got excited because it saved correctly:

```php
public function actionCreate()
{
        $model = new Dominio();

        if ($model->load(Yii::$app->request->post()) /*&& $model->save()*/) {
            $stmt = Yii::$app->db->createCommand('insert into tb_dominio (SQ_DOMINIO,NO_DOMINIO,NR_MATRICULA) VALUES (SQ_DOMINIO.nextval,:p1,:p2)');
            $stmt->bindValue(':p1', $model->NO_DOMINIO);
            $stmt->bindValue(':p2', $model->NR_MATRICULA);
            $stmt->execute();exit;
            return $this->redirect(['view', 'id' => $model->SQ_DOMINIO]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
}
```

https://pecl.php.net/package/oci8

**OCI8**
![oci8](https://cloud.githubusercontent.com/assets/7280981/20280718/bce904f6-aa94-11e6-8091-bca5002316e2.png)

**PDO_OCI**
![pdo-oci](https://cloud.githubusercontent.com/assets/7280981/20280750/dbb29b86-aa94-11e6-809c-450381ff039c.png)


:~(

**Comment by samdark** [comment]
I have no ideas left :(

**Comment by thiagoluis** [comment]
It worked!

I researched a way to execute the command generated by yii in my GUI software, and I found this:

http://stackoverflow.com/questions/12105669/returning-parameters-in-oracle-sql-insert-statements

Then I went up to the code file `db/oci/Schema.php` `insert()` method and added the command inside pl/sql:

```SQL
DECLARE
    qp2 number;
BEGIN
INSERT INSERT INTO "TB_DOMINIO" ("NO_DOMINIO", "NR_MATRICULA") VALUES ('TEST', 123) RETURNING "SQ_DOMINIO" INTO :qp2;
END;
```

That way it worked!

Please, when possible, check if this is the case (I believe it to be).
