### ISSUE TITLE
Why createAbsoluteUrl() is working right only with showScriptName = false and enablePrettyUrl = true?

### ISSUE THREAD

**Issue by papalapa** [yiisoft/yii2#13009]
### What steps will reproduce the problem?
I'm using advanced app and want build correct cross-links from backend (http://admin.site.dev) and fronend (http://site.dev). My code:
```php
// in backend config file
'components' => [
	'reverseUrlManager' => [
		'class'           => yii\web\UrlManager::className(),
		'baseUrl'         => 'http://site.dev',
		'enablePrettyUrl' => false,
		'showScriptName'  => true,
	],
],
// in backend view
echo Yii::$app->get('reverseUrlManager')->createAbsoluteUrl(['/hello']);
```
### What is the expected result?
`http://site.dev/hello`
### What do you get instead?
`http://admin.site.dev/hello`

### Additional info

But! If I set `showScriptName = false` and `enablePrettyUrl = true` - all is working right.
The problem is in this line [https://github.com/yiisoft/yii2/blob/2.0.9/framework/web/UrlManager.php#L321](https://github.com/yiisoft/yii2/blob/2.0.9/framework/web/UrlManager.php#L321):
```php
$baseUrl = $this->showScriptName || !$this->enablePrettyUrl ? $this->getScriptUrl() : $this->getBaseUrl();
```
Is it correct?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.27
| Operating system | Ubuntu 14.04 x64

**Comment by cebe** [comment]
> 'showScriptName'  => true,

if you show scriptname, you have to set `scriptUrl` also, not only `baseUrl`.
