### ISSUE TITLE
Access to the controller through the command mode can not be output log

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#13007]
I output in the project root directory:
`./yii script/index`

A log is recorded in the `index` method of the `ScriptController`, but the log is not output in the `app.log`.

**Comment by xiaoxing598** [comment]
There is no place where I can't get the answer to my question.

**Comment by xiaoxing598** [comment]
No one replied to me
![qq 20161116143035](https://cloud.githubusercontent.com/assets/5615719/20336965/0e5c9e2c-ac09-11e6-9939-a30e659c4048.png)

**Comment by xiaoxing598** [comment]
@SilverFire can you help me?

**Comment by dynasource** [comment]
please use the forum for questions http://www.yiiframework.com/forum/

**Comment by xiaoxing598** [comment]
@dynasource I tried to register but there was this error

![qq 20161121192118](https://cloud.githubusercontent.com/assets/5615719/20480968/bb5c15fc-b01f-11e6-93ba-8344cf4c41c2.png)

**Comment by dynasource** [comment]
you should fill in the right captcha ;)

**Comment by xiaoxing598** [comment]
I did not see the verification code, did not see the input box.

![qq 20161121201637](https://cloud.githubusercontent.com/assets/5615719/20482391/6b891dec-b027-11e6-8920-eaf6139d135b.png)

**Comment by xiaoxing598** [comment]
I know, GFW to Google's website blocked, I use VPN to visit it.

**Comment by dynasource** [comment]
please read http://www.yiiframework.com/doc-2.0/guide-runtime-logging.html carefully to fix your issue

**Comment by xiaoxing598** [comment]
I can generate a log through the browser, but through the command mode is not recorded, I do follow the document using the log records.
