### ISSUE TITLE
download file does not work in Safari correctly

### ISSUE THREAD

**Issue by jbmckee** [yiisoft/yii2#13001]
I am using the following to allow a user to download a generated zip file:

		$headers = Yii::$app->response->headers;
		$headers->set('Content-Disposition', "attachment; filename={$file_name}");
		$headers->set('Content-Type', 'application/zip');
		Yii::$app->response->content = $zipfile;
		return;

This works fine in every browser except Safari. Unfortunately, if the file name is file.zip, it downloads as file.zip.html

However, this works as expected:
		header('Content-Type: application/zip');
		header("Content-disposition: attachment; filename={$file_name}");
		echo $zipfile;
		exit;

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
Have you tried special response methods for file uploads?

**Comment by jbmckee** [comment]
I originally was going to use Yii::$app->response->sendContentAsFile($zipfile, $file_name)->send(); but was under the impression that there was a bug with this method. This is why I went with the Yii::$app->response->content = $zipfile;

However, I just tried Yii::$app->response->sendContentAsFile($zipfile, $file_name)->send();  on Mac in both Chrome and Safari and by golly, it did work. So, maybe whatever bug there was has been fixed. 

Thanks for your attention.
