### ISSUE TITLE
BaseHtml::renderSelectOptions, problem with non-strict comparison

### ISSUE THREAD

**Issue by antishov** [yiisoft/yii2#13017]
### What steps will reproduce the problem?
Execute next rows:
~~~
$options = ['multiple' => true];
BaseHtml::renderSelectOptions([0, 'IAB26'], [0 => 0, 'IAB25' => 'IAB25', 'IAB26' => 'IAB26'], $options);
~~~

### What is the expected result?
~~~
<option value="0" selected>0</option>
<option value="IAB25">IAB25</option>
<option value="IAB26" selected>IAB26</option>
~~~

### What do you get instead?
~~~
<option value="0" selected>0</option>
<option value="IAB25" selected>IAB25</option>
<option value="IAB26" selected>IAB26</option>
~~~

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |5.5.37-1+deprecated+dontuse+deb.sury.org~precise+1
| Operating system |Ubuntu 12.04.5 LTS

**Comment by klimov-paul** [comment]
The obvious solution will be usage string `'0'` instead of integer `0`:

```php
BaseHtml::renderSelectOptions(['0', 'IAB26'], ['0' => '0', 'IAB25' => 'IAB25', 'IAB26' => 'IAB26'], $options);
```

I am unsure if it is safe to switch to strict comparision at `BaseHtml::renderSelectOptions()` as it may break existing applications.
