### ISSUE TITLE
ArrayHelper::isIn, problem with non-strict comparison

### ISSUE THREAD

**Issue by antishov** [yiisoft/yii2#13015]
### What steps will reproduce the problem?
Execute next row
ArrayHelper::isIn('IAB25', [0, 'IAB26']);

### What is the expected result?
false

### What do you get instead?
true

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.5.37-1+deprecated+dontuse+deb.sury.org~precise+1
| Operating system | Ubuntu 12.04.5 LTS

**Comment by klimov-paul** [comment]
You should set `$strict` paramter to `true`:

```php
ArrayHelper::isIn('IAB25', [0, 'IAB26'], true);
```

**Comment by antishov** [comment]
Ok. But in the class `yii\helpers\BaseHtml` I have a problem with method `renderSelectOptions`: in the line 1724 `$strict` selected as `false`, so option with value `IAB25` will improperly marked as selected.

**Comment by antishov** [comment]
I have not selected the correct title for issue, sorry.

**Comment by klimov-paul** [comment]
Open a separated one.
