### ISSUE TITLE
Possible Bug in HHVM Postgres implementation

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#13010]
There are two tests in the Yii Postgres related DB implementation that fail on HHVM:

https://github.com/yiisoft/yii2/pull/12971#issuecomment-260134653

```
There were 2 failures:

1) yii\tests\unit\framework\db\pgsql\CommandTest::testSaveSerializedObject

Failed asserting that 0 matches expected 1.

/home/travis/build/yiisoft/yii2/tests/framework/db/pgsql/CommandTest.php:86
/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:47

2) yii\tests\unit\framework\db\pgsql\CommandTest::testBindParamValue

Failed asserting that false is true.

/home/travis/build/yiisoft/yii2/tests/framework/db/CommandTest.php:199
/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:47
```

They are temporarilty skipped for now:

- https://github.com/photodude/yii2/blob/7eef801f7b0093429b870c7f2c894c3aa8511063/tests/framework/db/pgsql/CommandTest.php#L77-L79
- https://github.com/photodude/yii2/blob/7eef801f7b0093429b870c7f2c894c3aa8511063/tests/framework/db/CommandTest.php#L198-L199

I guess it could be related to blob columns because I was not able to reproduce it with plain PDO:

- https://github.com/cebe/hhvm-bugreport/blob/master/bug.php
- https://travis-ci.org/cebe/hhvm-bugreport/builds/176069208

### What steps will reproduce the problem?

not clear yet, only failing yii tests but plain PDO passes.

### What is the expected result?

same outcome as in normal PHP.

**Comment by arogachev** [comment]
@cebe They are already created as separate issues #12981 and #12982.

**Comment by arogachev** [comment]
Related: #12981 and #12982.

**Comment by SilverFire** [comment]
Related https://github.com/yiisoft/yii2/commit/5c6ba33e553476cddd468df0ef9b99a00d7e0411

**Comment by SilverFire** [comment]
HHVM support is dropped.
