### ISSUE TITLE
Yii3 as PHP server :)

### ISSUE THREAD

**Issue by adamasantares** [yiisoft/yii2#13011]
Yii is a big framework and will be great if Yii3 will work as server

Something like this:
https://github.com/lukaszkujawa/php-multithreaded-socket-server

It will be great to have one app instance for all requests...

**Comment by cebe** [comment]
> It will be great to have one app instance for all requests...

that does not scale and also can not connect to a database via PDO as these are usually blocking requests. You can already use Yii in such scenarios but it will not be part of yii core.
