### ISSUE TITLE
Support JSON in schemabuildertrait

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#13019]
Related to #10436

Regardless of how we choose to handle JSON fields at the ORM layer, it makes sense to support JSON fields in the schema builder.

Currently the following databases exist:
````
cubrid ?
mssql y
mysql y
oci ?
pgsql y
sqlite y
````

For databases that don't have support for storing JSON natively it could instead be stored as a blob.

This is part of #10436 is relatively simple to implement and doesn't require a lot of design decisions since it regards the JSON as opaque. In the future of course it would be great to have full support for JSON in the ORM layer as well.

**Comment by samdark** [comment]
I'm OK with having it out of the box.

**Comment by Reexel** [comment]
Can you add request for Redis?

**Comment by cebe** [comment]
@Reexel what do you mean? We have no migrations or SchemaBuilder for redis. you can just store JSON in redis if you want, there is no need to define a schema.
