### ISSUE TITLE
Calling $auth->getChildRoles on a Role with no children throws hard PHP Error

### ISSUE THREAD

**Issue by oduncan10** [yiisoft/yii2#13021]
### What steps will reproduce the problem?
Create a role using rbac/DbManager createRole() and add() Methods:

```php
$role = $manager->createRole($model->name);
            $role->name = $model->name;
            $role->description = $model->description;
            $role->type = $model->type;
            $role->ruleName = $model->ruleName;
            $role->data = $model->data === null || $model->data === '' ? null : Json::decode($model->data);
            $manager->add($role);
```

In a view call getChildRoles() on the new role

`$auth->getChildRoles($role->name);`

### What is the expected result?
A graceful return/error, boolean false, something that doesn't break the view

### What do you get instead?
PHP Warning – yii\base\ErrorException

array_key_exists() expects parameter 2 to be array, null given

yii2\rbac\DbManager line 481

### Additional info
if you add a permission to the role via addChild() you do not get the array_key_exists error.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version | 7.0.10
| Operating system |  Windows 10

**Comment by murat-celik** [comment]
Fixed here.

https://github.com/yiisoft/yii2/commit/73a30780b384d90605a7091d61ac302c902e6e4c

@oduncan10

**Comment by SilverFire** [comment]
@murat-celik thank you for pointing.

@oduncan10 you can either require unstable version of Yii framework, or wait for 2.0.11 release

**Comment by oduncan10** [comment]
Thanks guys.
