### ISSUE TITLE
add .vtt mimetype to yii2/framework/helpers/mimeTypes.php

### ISSUE THREAD

**Issue by idejanovic** [yiisoft/yii2#13024]
### What steps will reproduce the problem?
        $mimeType = FileHelper::getMimeTypeByExtension('myfile.vtt') ;
        if (empty($mimeType)) {
            echo (":( expecting text/vtt\n");
        } else {
            echo (":)\n");
        }
### What is the expected result?
:)
### What do you get instead?
:( expecting text/vtt

### Additional info
It should be: text/vtt

Thanks!

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.5.38
| Operating system | macOS

**Comment by SilverFire** [comment]
We are not maintaining our own version of the mime file, this is taken from http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=markup

Please report to the Apache project if you want to change mime types.

**Comment by SilverFire** [comment]
Also see https://github.com/yiisoft/yii2/issues/9744#issuecomment-162289620 for possible solution
