### ISSUE TITLE
slug is not working for single word

### ISSUE THREAD

**Issue by vc7deo** [yiisoft/yii2#13032]
for example

www.example.com/content/about-us 
is working 
in table slug is "about-us "

www.example.com/content/about

is not working. it shows 404 page
in table slug is "about"

**Comment by samdark** [comment]
That's clearly a problem in the application code. Yii doesn't handle finding a record by slug.

**Comment by danielchirinos** [comment]
I have the same problem, I have not yet been able to solve it, I thought about adding a slug manually and then to the single words to add a - at the end, it was so www.example.com/about- but I do not know if it's the result.
