### ISSUE TITLE
GroupUrlRule nesting fails with error

### ISSUE THREAD

**Issue by cronfy** [yiisoft/yii2#13037]
### What steps will reproduce the problem?

Consider this config:

```
        "urlManager" => [
            "enablePrettyUrl" => true,
            "showScriptName" => false,
            "suffix" => "/",
            "rules" => [
                [
                    'class' => 'yii\web\GroupUrlRule',
                    'rules' => [
                        [
                            'class' => 'yii\web\GroupUrlRule',
                            'rules' => [
                                [
                                    'pattern' => "faq/post",
                                    'route' => "faq/post",
                                ],
                            ]
                        ]
                    ]
                ]
            ]
        ]
```

And open site.com/faq/post/

### What is the expected result?

I expect ```FaqController::actionPost()``` will be invoked to display the page.

### What do you get instead?

I see error
```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: yii\web\GroupUrlRule::name
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | any
| Operating system | any

Looks like problem is in this line: https://github.com/yiisoft/yii2/blob/master/framework/web/CompositeUrlRule.php#L51

With this line commented everything works as expected.

**Comment by samdark** [comment]
Is it the same as https://github.com/yiisoft/yii2/issues/10231?

**Comment by cronfy** [comment]
It looks similar, but I am not familiar with yii\rest\UrlRule, #10231 seems more complex issue for me.

**Comment by dynasource** [comment]
yeah, its the type of error. Closed in favor of https://github.com/yiisoft/yii2/issues/10231
