### ISSUE TITLE
Wincache can not flush on console

### ISSUE THREAD

**Issue by vuongminh** [yiisoft/yii2#13049]
I have run cache/flush-all and cache/flush cache both return same result:

The following cache components were processed:

        * cache (yii\caching\WinCache) - not flushed

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |7.0.9
| Operating system |Window 10/IIS 10

**Comment by dynasource** [comment]
* whats the actual return value of flush()? http://www.yiiframework.com/doc-2.0/yii-caching-cache.html#flush()-detail 
* do you see some clue in your PHP log?

**Comment by vuongminh** [comment]
@dynasource The actual return value of flush is **FALSE** and haven't php log

**Comment by dynasource** [comment]
according to http://php.net/manual/en/function.wincache-ucache-clear.php, this is because of a failure in your environment. Out of the Yii scope unfortunately.
