### ISSUE TITLE
Search appends same GET Params over and over

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii2#13046]
### What steps will reproduce the problem?
Search form without manually placing the action url via Url::to()
### What is the expected result?
replacing the get param with the new param
### What do you get instead?
Appends the same get param over and over

### Additional info
If you do not place the action url like
` ActiveForm::begin(['method' => 'get', 'options' => ['data-pjax' => true]]);`

it will append the get over and over however, if you do 

` ActiveForm::begin(['action' => Url::to(['/catalog/index']), 'method' => 'get', 'options' => ['data-pjax' => true]]);`

it will not.  If you inspect the form both output the same url.  My form is also wrapped in a standard pjax widget like `Pjax::begin(['id' => 'catalog']);`.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |7.0.10
| Operating system |Windows 10

**Comment by dynasource** [comment]
can you provide some arguments why the ActiveForm should filter these by default? And what are the potential risks of doing so?

**Comment by cebe** [comment]
> If you do not place the action url like
> ActiveForm::begin(['method' => 'get', 'options' => ['data-pjax' => true]]);
> 
> it will append the get over and over however, if you do
> 
> ActiveForm::begin(['action' => Url::to(['/catalog/index']), 'method' => 'get', 'options' => ['data-pjax' => true]]);
> 
> it will not.

This is expected because the form will send to the current URL by default, which includes some get params. As it is a 'get' form, it will append to the current url. If you specify the action of the form, the params are not included.

**Comment by skworden** [comment]
I would think it's not intended.  If you search "name" it will append "name=test" if you clear and search again (not refershing the page.  i.e. pjax)  it will do "name=test&name=test1" and so forth.  If you manually put the action URL  it will leave all other get params in tact while not appending the same params over and over. 

Depending on what your server setting are you can get errors for too long of url.  I actually only noticed this because I have a catalog page and i filtered based on  about 10 mfgs (checkbox list).  I unchecked the 10 mfg. then checked about 10 more and hit the url error.  

my url was something like.  http://localhost/yii2/catalog?CatalogSearch%5Bcompany_id%5D=

each check of a mfg filter adds "CatalogSearch%5Bmfg%5D=" multiple that by 20 and it's pretty nasty looking as well as really long (potentially throwing the apache error).  

If you unchecked then recheck a new filter it just appends leaving the old filters.  There is no behavioral differences and the old params are not even passed to the action they are just left in the url.

**Comment by cebe** [comment]
I know, there is just no way to change this from yii code. The url is specified explicitly in the code generated by gii as this is the way it should be done: https://github.com/yiisoft/yii2-gii/blob/ffefc12a47f9bdabdd53076767b92dbceb6283e9/generators/crud/default/views/_search.php#L23
