### ISSUE TITLE
Make stdout accessible for console components

### ISSUE THREAD

**Issue by netbrothers-tr** [yiisoft/yii2#13044]
This is another feature request. When using components in a web controller we can access `Yii::trace()`, `Yii::debug()` and so forth statically from within the component. However, when using application components in a console environment, we can't use the `stdout()` function from within the component, because it's not accessible statically. I'm looking for a consistent way of outputting messages in a console application that makes use of components. Any suggestions?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by klimov-paul** [comment]
See:
https://github.com/yiisoft/yii2/issues/12163#issuecomment-240046093

**Comment by netbrothers-tr** [comment]
Thanks for the hint! I also just found out that anything (public) defined in the controller can be accessed through `Yii::$app->controller`. Hence, anything logging related can be accessed that way also from a component. So no worries there!
