### ISSUE TITLE
MSSQL tests

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#13047]
Just found it, have not checked it in detail.

Would this allow us to run unit tests against MSSQL?

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ubuntu

Possibly even on travis?

**Comment by schmunk42** [comment]
Should be able with Docker, works on Travis and there's also a container for it https://hub.docker.com/r/microsoft/mssql-server-linux/

More expensive tests might only be run on specific branches.

Let me know if you need more input.

**Comment by samdark** [comment]
Yes, it seems this way of solving it is good.

**Comment by schmunk42** [comment]
Above PR & example build/test https://git.hrzg.de/schmunk42/yii2/builds/73924

**Comment by samdark** [comment]
Seems to be done.
