### ISSUE TITLE
Menu: isItemActive bug with module route

### ISSUE THREAD

**Issue by haqqi** [yiisoft/yii2#13042]
I believe to add url for module route in the config of Menu widget is just using

```
'items' => [
      [
        'label' => 'Menu for Module',
        'url' => ['module/controller/action'],
      ],
]
```

As i look at function `isItemActive` in the Menu class line 311, it assumes that the defined url is without module id. So, the config above does not activate item on url `localdomain.dev/module/controller/action`. I need to define the url to only `['controller/action']` to activate that menu inside the module. But this will render `/controller/action` in the menu link instead.

I think this is not right. So, i use workaround just remove the line

```
$route = Yii::$app->controller->module->getUniqueId() . '/' . $route;
```

and it works just like i want to using the correct url in config. I will send pull request if it is accepted.

**Comment by SilverFire** [comment]
The behavior is correct. If you want to get URL to module, add beginning `/` to the `url`:

```php
'items' => [
      [
        'label' => 'Menu for Module',
        'url' => ['/module/controller/action'],
      ],
]
```
