### ISSUE TITLE
HTML5 "form" attribute isn't propagated to hidden fields when checkbox is used

### ISSUE THREAD

**Issue by EagleGas** [yiisoft/yii2#13053]
### What steps will reproduce the problem?

Создать форму ActiveForm.
Задать ей ID - любой, например my-form.
После ActiveForm::end(); - подчеркиваю это важно!
Задать чек бокс с указанием значения при снятом флажке, указать какой форме принадлежит этот чекбокс. 
Например

`<?= $form->field($model, 'edited')->checkbox(['uncheck' => 'no', 'value' => 'yes', 'form' => 'my-form'], false) ?>`
 
### What is the expected result?

В итоге мы должны получить

```
<div class="col-sm-10">
<input type="hidden" name="Objects[edited]" form="my-form" value="no">
<input type="checkbox" id="objects-edited" name="Objects[edited]" value="yes" checked="" form="my-form">
<div class="help-block help-block-error "></div>
</div>
```

### What do you get instead?

```
<div class="col-sm-10">
<input type="hidden" name="Objects[edited]" value="no">
<input type="checkbox" id="objects-edited" name="Objects[edited]" value="yes" checked="" form="my-form">
<div class="help-block help-block-error "></div>
</div>
```

В скрытом поле пропущен атрибут принадлежности формы.
В итоге если флажок снят то не передается значение "no".

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.19
| Operating system | windows 7 sp1

**Comment by dynasource** [comment]
You are point to the HTML5 `form` attribute https://www.sitepoint.com/the-html5-form-attribute/

Manually setting attributes to the hiddenInput is not yet supported, as can be seen at https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L727

This is something to evaluate.

**Comment by EagleGas** [comment]
I add manually hiddenInput.
Everything works perfectly.
```
<input type="hidden" name="Objects[edited]" value="no" form="my-form">
<div class="col-sm-10">
<input type="checkbox" id="objects-edited" name="Objects[edited]" value="yes" form="my-form">
<div class="help-block help-block-error "></div>
</div>
```
Value "no" - send with data form, if checkboxInput is not checked.

**Comment by samdark** [comment]
> После ActiveForm::end(); - подчеркиваю это важно!

Can you elaborate this part?

**Comment by EagleGas** [comment]
```
<?php $form = ActiveForm::begin([
			'id' => 'my-form'
   ]); ?>
<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
<?= Html::submitButton('Save', ['class' =>  'btn btn-success'']) ?>
<?php ActiveForm::end(); ?>

<?= $form->field($model, 'edited')->checkbox(['uncheck' => 'no', 'value' => 'yes', 'form' => 'my-form'], false) ?>

```
Извините, но мой английский не очень хорош, чтоб на нем писать.
Я привел пример кода.
По своим соображениям , я вынужден вынести чекбокс за пределы формы.
И это ничего страшного, так как существует атрибут  "form" в HTML5 
который отправить данные этого чекбокса вместе с формой по сабмиту, ЕСЛИ он был отмечен.

Используя возможность фреймворка я задаю передаваемое значение по умолчанию - 'uncheck' => 'no'.
В итоге сгенерится скрытое поле 
```
<input type="hidden" name="Objects[edited]" value="no">
```
над чекбоксом, с тем же именем ('name');
Но не добавится указанный атрибут "form".
И при сабмите формы значение "no" не будет отправлено!
Подчеркиваю - данная проблема только если чекбокс вынесен ЗА ПРЕДЕЛЫ формы.
если задать вручную
<input type="hidden" name="Objects[edited]" value="no" **form="my-form">**
ТО все работает как надо.
Добавьте пожалуйста возможность добавления атрибута "form" дополнительным полям 
генерируемым для передачи значения по умолчанию для чекбокса.

**Comment by samdark** [comment]
OK. This is about https://www.sitepoint.com/the-html5-form-attribute/ which allows fields to be out of form but submitted with a form.

The issue is that Yii is creating hidden input for a checkbox but `form` from the field isn't propogated to this hidden input.

**Comment by dynasource** [comment]
related #7946
