### ISSUE TITLE
Yii2 Guide Incomplete: Internationalization

### ISSUE THREAD

**Issue by ChrGriffin** [yiisoft/yii2#13052]
Page: http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html

This page makes reference to storing translations in PHP files for each 'category', but makes no mention at all to what these files look like, what class they extend (if any), or what format the translations are stored in (object? associative array?). This section could be expanded to include this information, as right now it's not of much use to a newcomer to Yii or Yii 2 who doesn't know what these files should look like, just that they should exist.

**Comment by dynasource** [comment]
have you seen the links to 'yii\i18n\PhpMessageSource' http://www.yiiframework.com/doc-2.0/yii-i18n-phpmessagesource.html ?

**Comment by cebe** [comment]
added some small improvements. is it more clear now?

**Comment by ChrGriffin** [comment]
dynasource: Yes I have, I personally got translations working before I opened the issue; it's not so much a request for help as an indication that I experienced difficulty understanding that part of the documentation, so others might as well.

cebe: It definitely is, as before there was no indication that 'how to make these files' would be covered - it simply jumped from 'you need these files' to 'now that you have them'. So it's more clear now for sure. But unless the major 'push' is to get people to generate it automatically via the message command, it still places no focus on how one might write the translation files manually if one so desired; for very simple sites it's almost more complication than it's worth to run the command line instead of just writing it yourself- it might be well served to have an example of a typical translations file or folder structure, so readers will understand the concept and structure if nothing else. As it stands, a total newcomer is essentially presented with: 'do this command line thing and trust it will work out fine'. I personally prefer to see how something is put together manually, before being shown the automated alternative. Of course that's just my suggestion; there may be deeper intent behind the documentation that I don't see.

**Comment by dynasource** [comment]
@ChrGriffin, thanks for sharing your view on this part of our documentation. It seems that you are confident about what needs to be improved. Are you able to add your improvement with a pull request to https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-i18n.md? Would be great!

**Comment by ChrGriffin** [comment]
For sure, as soon as I'm able I'll do that!

**Comment by dynasource** [comment]
great. Thanks
