### ISSUE TITLE
"\yii\web\Response::EVENT_AFTER_SEND" twice ran, in each application run!

### ISSUE THREAD

**Issue by sahifedp** [yiisoft/yii2#13056]
Hi
I used `\yii\web\Response::EVENT_AFTER_SEND` trigger in my module bootstrap, to doing anything at end of application run. But it ran twice in each request:

     class Bootstrap implements BootstrapInterface {
          public function bootstrap($app) {
               \yii\base\Event::on(
                    \yii\web\Response::className(),
                    \yii\web\Response::EVENT_AFTER_SEND, 
                    function ($event) {
                       var_dump("do anything");
                    });
        }
}
![screenshot_20161122_090622](https://cloud.githubusercontent.com/assets/9697407/20512308/cc6dac88-b093-11e6-9661-2eb8ed4397ed.png)

Has better event instead of this event? or this event must be corrected? or my code has error?

Thanks.

### Additional info
| Yii version 2.0.10 |
| PHP version 7.0.11 |
| Operating system: kubuntu 16.10 |

**Comment by vuongminh** [comment]
if your site in environment dev (have module debug and in view files you call endBody) the last trigger is module debug. Try change environment to prod and test again.

**Comment by sahifedp** [comment]
I changed environment to prod and debug to false, but still event ran twice.

        \yii\base\Event::on(
              \yii\web\Response::className(), 
              \yii\web\Response::EVENT_AFTER_SEND,  
               function ($event) {
                          echo 'YII_ENV_PROD:';
                          var_dump(YII_ENV_PROD);
                          echo 'YII_DEBUG:';
                          var_dump(YII_DEBUG);
               });

![screenshot_20161122_153700](https://cloud.githubusercontent.com/assets/9697407/20523288/8f8e332e-b0c9-11e6-9a1d-9fec0edc7aa1.png)

**Comment by samdark** [comment]
Unable to verify. Tried with clean basic project template.

**Comment by cebe** [comment]
@sahifedp try to print `Yii::$app->requestedRoute` and `Yii::$app->requestedAction` to see whether these are from the same or from differentrequests.

**Comment by sahifedp** [comment]
Hi 
I have done many test and ... 
Finally I found that sahifedp\stats\Bootstrap::bootstrap() action ran twice.
By printing stack trace on every run, two result seen:
First: 
     1. in /www/rtv/vendor/sahifedp/stats/Bootstrap.php at line 23
     2. sahifedp\stats\Bootstrap::sahifedp\stats\{closure}(yii\base\Event)
     3. in /www/rtv/vendor/yiisoft/yii2/base/Event.php at line 216    call_user_func(Closure, yii\base\Event)
     4. in /www/rtv/vendor/yiisoft/yii2/base/Component.php at line 548 – yii\base\Event::trigger('yii\web\Response', 'afterSend', yii\base\Event)
    5. in /www/rtv/vendor/yiisoft/yii2/web/Response.php at line 317 – yii\base\Component::trigger('afterSend')
    6. in /www/rtv/vendor/yiisoft/yii2/base/Application.php at line 381 – yii\web\Response::send()
    7. in /www/rtv/app/web/index.php at line 16 – yii\base\Application::run()
    --- end ---
Second: 
    1. in /www/rtv/vendor/sahifedp/stats/Bootstrap.php
    --- end ---

My extentions composer is: 
{
    "name": "sahifedp/stats",
    "description": "An extension for managing ads for yii2.",
    "type": "yii2-extension",
    "minimum-stability": "beta",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2-bootstrap": "~2"
    },
    "autoload": {
        "psr-4": {
            "sahifedp\\stats\\": ""
        }
    },
    "extra": {
        "bootstrap": "sahifedp\\stats\\Bootstrap"
    }
}

**Comment by dynasource** [comment]
out of the Yii core scope

**Comment by sahifedp** [comment]
I tested it on the other platform ( xampp x86  on Win7 with php5.6.19), but problem not solved.
Do I have change the algorithm, or change my composer ,or ...?
why bootstrap method ran twice?
any idea?
thanks

**Comment by dynasource** [comment]
could it be your debug toolbar?

**Comment by sahifedp** [comment]
No, I disabled debug toolbar. By enabling debug toolbar ,bootstrap method run Four times.
Please pay attention to stack trace.
I don`t know where called  "/www/rtv/vendor/sahifedp/stats/Bootstrap.php" directly in second time.

**Comment by dynasource** [comment]
1. how many times is it called when removing the `extra` parameter from composer
2. whats happens if you remove the Events

**Comment by cebe** [comment]
@sahifedp can you show the content of `vendor/yiisoft/extensions.php`?

**Comment by sahifedp** [comment]
vendor/yiisoft/extensions.php: 
https://paste.ubuntu.com/23646456/

**Comment by sahifedp** [comment]
My extention was twice in `vendor/yiisoft/extensions.php` .
I removed vendor dir and ran composer update.
problem solved.
I had continuous updates from Yii 2.0.6. I think problem occurred due it.
Thanks.

**Comment by cebe** [comment]
I see no way how an entry indexed with 0 could be added to that array... https://github.com/yiisoft/yii2-composer/blob/f55d47ac0b284257663e2d077c97677f3aaec238/Installer.php#L96
