### ISSUE TITLE
Unique Validator shows generic message when rule fails

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2#13055]
Hello,

It appears that for some reason the message specified for unique validators do not show up when validation fails rather a generic message is shown?

### What steps will reproduce the problem?
Add a unique rule with a custom message to a model involving more than one column

### What is the expected result?
When the rule fails the custom message provided in the rule should be displayed eg;
This Book and Author are already associated

### What do you get instead?
A generic message like the following is displayed eg;
The combination "1"-"1" of Book, Author has already been taken.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | **2.0.9**
| PHP version      |**5.6**
| Operating system |**Linux/Ubuntu 14.04.3**

    public function rules()
    {
        return [
...
            [['book_id', 'author_id'], 'unique', 'targetAttribute' => ['book_id', 'author_id'], 'message' => 'This Book and Author are already associated'],
...
        ];
    }

**Comment by rob006** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/12918.

**Comment by dbd5** [comment]
Thanks @rob006, will update to 2.0.10 and provide feedback

**Comment by dbd5** [comment]
Glad to report that updating to 2.0.10 resolved the issue, thanks
