### ISSUE TITLE
Возможно не оптимальная работа метода User::can

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#13059]
### What steps will reproduce the problem?
Имею социальную сеть, допустим храбрахабр. В зависимости от того есть ли право пользователя редактирования поста требуется показать элемент интерфейса на определенном посте с кнопкой редактирование. Использую yii\rbac\DbManager

Право пользователя проверяется по авторизации и по правилу пользователя.

```php
// использую этот метод
Yii::$app->user->can(Rights::USER_POST_UPDATE, ['model' => $model])
```

### What is the expected result?
Если человек гость: Генерируется 4 запроса к БД
Если авторизован: Генерируется 4 запроса к БД

### What do you get instead?
Если человек гость: Не создается запросов
Если авторизован: Генерируется 4 запроса к БД

### Additional info
То есть. Мне кажется, что не должно генерироваться запросы в случае, если человек не авторизован. Возможно я не прав и чего-то не понимаю.

Сейчас я пользуюсь этой конструкцией
```php
!Yii::$app->user->isGuest && Yii::$app->user->can(Rights::USER_POST_UPDATE, ['model' => $model])
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10?
| PHP version     | 7.0.8 
| Operating system  | Windows NT K-USER 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) AMD64

**Comment by SilverFire** [comment]
Будет исправлено пул-реквестом https://github.com/yiisoft/yii2/pull/12785

**Comment by SilverFire** [comment]
Дубликат #12771
