### ISSUE TITLE
GridView widget and bootstrap awesome checkboxes

### ISSUE THREAD

**Issue by cupjkh** [yiisoft/yii2#13060]
GridView widget does not bootstrap awesome checkboxes.
An example of a patch to add support

[awesomechecboxlist.txt](https://github.com/yiisoft/yii2/files/608237/awesomechecboxlist.txt)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |5.4

**Comment by dynasource** [comment]
please elaborate on your usecase

**Comment by cupjkh** [comment]
awesome checkbox - https://github.com/flatlogic/awesome-bootstrap-checkbox
need format, but GridView widget does not support the format:
`  <div class="checkbox">
    <input type="checkbox" id="checkbox1">
    <label for="checkbox1">
        Check me out
    </label>
  </div>`

**Comment by dynasource** [comment]
> but GridView widget does not support the format:

can you point to Yii2 source code which prevents you from getting your desired result.

**Comment by cupjkh** [comment]
In Yii in CheckboxColumn.php, in renderHeaderCellContent and renderDataCellContent:
return Html::checkbox($this->getHeaderCheckBoxName(), false, ['class' => 'select-on-check-all']);

**Comment by ebtc** [comment]
I might be able to supply some more info, as I was just about to open an issue on something similar. 
If I understand the OP correctly he wants to use a checkboxcolumn, that is formated a certain way, in a standard grid.

I was trying to do the same thing now but could not tell the grid to set the resulting column within divs and append a label. I tried it this way:

```
yii\grid\GridView::widget([
                    'dataProvider' => $messages,
                    'columns' => [
                        [
                            'class' => 'yii\grid\CheckboxColumn',
                            'content' => function ($model, $key, $index, $column) { //TODO: should replace content, but does not
                                var_dump($model);
                                return '<div class="checkbox checkbox-primary m-r-15">'.$column.'<label for="checkbox"></label></div>';
                            }
                        ],
                        [
                            'label'=>false,
                            'value' => function($data) {
                                return isset($data->user) ? $data->user->avatarImage : '';
                            },
                            'format' => 'raw',
                            'contentOptions' => function ($message, $key, $index, $grid) {
                                $url = url(['message/view', 'id' => $message->id]);
                                return ['data-href' => $url];
                            },
                        ],
```

As far I understand the docs the "content" option should give you that ability. But it does not seem to want to do that.

Any ideas?

**Comment by buttflattery** [comment]
Has this issue been merged to the latest release or not does not seem to be working for me at the moment i am using `yii 2.0.14`
