### ISSUE TITLE
Help option does not work in sub-module command

### ISSUE THREAD

**Issue by haimanman** [yiisoft/yii2#13071]
Since 2.0.10, Yii2 add a help option for command controllers by default, but when the command is in submodule, that dose not work.

Fixing this is very simple, just modify [yii\console\Controller#L125](https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L125), 
change `$this->id` to `$this->uniqueId`.

**Comment by cebe** [comment]
thanks for reporting this, do you want to send a pull request to fix it?
