### ISSUE TITLE
Provide *.d.ts files for yii.*.js

### ISSUE THREAD

**Issue by MrElectroNick** [yiisoft/yii2#13077]
### What steps will reproduce the problem?

nonw

### What is the expected result?

Have at least yii.d.ts file to reference in TypeScript

### What do you get instead?

no type hinting in IDE

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7
| Operating system | Linux Mint 18.0

**Comment by dynasource** [comment]
@yiisoft/core-developers, do we think this is a priority feature?

**Comment by SilverFire** [comment]
Could be implemented, but with a low priority

**Comment by samdark** [comment]
@MrElectroNick low priority basically means it could take forever. If you want to speed it up you can do a pull request with changes necessary.

**Comment by MrElectroNick** [comment]
@samdark Ok. Got it :-) That's exactly what I'm going to do

**Comment by samdark** [comment]
Won't be implemented in 2.0.
