### ISSUE TITLE
Why yii\base\Model::getActiveValidators($attribute) don`t return validator, if i add '!' as prefix to attribute name in rules.

### ISSUE THREAD

**Issue by porshkevich** [yiisoft/yii2#13087]
if i add next to rules:

```php
[['!coinsImage'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg'],
```
i will exclude it from massive assignment, but can`t get that validator when use:

```php
$model->getActiveValidators('coinsImage');
```

I think next condition wrong:

```php
if ($validator->isActive($scenario) && ($attribute === null || in_array($attribute, $validator->attributes, true))) {
                $validators[] = $validator;
            }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by developeruz** [comment]
Workaround: 
```$model->getActiveValidators('!coinsImage');```
but it is not obvious.
You can find a proper fix in my PR #13088
