### ISSUE TITLE
Rename InvalidParamException to InvalidArgumentException?

### ISSUE THREAD

**Issue by sadovnik** [yiisoft/yii2#13080]
Seems like there is misuse of parameter term. :)

See "Parameters and arguments" section of https://en.wikipedia.org/wiki/Parameter_(computer_programming)

**Comment by arogachev** [comment]
Interesting remark, I think this can be considered as a part of refactoring for 2.1 because of BC break.

From documentation of `yii\base\InvalidParamException`:

> InvalidParamException represents an exception caused by invalid parameters passed to a method.

Yes, calling it "arguments" is more correct.

**Comment by dynasource** [comment]
agree. This should become 'arguments' indeed.

**Comment by samdark** [comment]
Agree.
