### ISSUE TITLE
\yii\db\pgsql\Schema thinks primary key indexes aren't unique indexes

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2#13085]
### What steps will reproduce the problem?

Using PostgreSQL 9.6 with the following DEPART table structure:

```
datos=> \d depart
            Table "public.depart"
 Column  |         Type          | Modifiers 
---------+-----------------------+-----------
 dept_no | numeric(2,0)          | not null
 dnombre | character varying(14) | 
 loc     | character varying(14) | 
Indexes:
    "pk_depart" PRIMARY KEY, btree (dept_no)
```

As anyone knows, a primary key index is, conceptually, a "special" unique index.

But:

```
./yii shell
Psy Shell v0.7.2 (PHP 7.0.8-0ubuntu0.16.04.3 — cli) by Justin Hileman
>>> $s = new \yii\db\pgsql\Schema
[...]
>>> $s->db = Yii::$app->db
[...]
>>> $s->findUniqueIndexes($s->getTableSchema('depart'))
=> []
>>> 
```

### What is the expected result?

`\yii\db\pgsql\Schema::findUniqueIndexes()` must returns primary key indexes, too:

```
>>> $s->findUniqueIndexes($s->getTableSchema('depart'))
=> [
     "pk_depart" => [
       "dept_no",
     ],
   ]
```

### What do you get instead?

An empty array.
Additionally, GII model generator doesn't generate a 'unique' validation rule for the primary key attribute, but it should do it:

```
/**                                                                         
 * @inheritdoc                                                              
 */                                                                         
public function rules()                                                     
{                                                                           
    return [                                                                
        [['dept_no'], 'required'],                                          
        [['dept_no'], 'number'],                                            
        [['dnombre', 'loc'], 'string', 'max' => 14],                        
    ];                                                                      
}                                                                           
 ```

### Additional info

The problem is in https://github.com/yiisoft/yii2/blob/master/framework/db/pgsql/Schema.php#L345. The `WHERE idx.indisprimary = FALSE` is filtering the primary key indexes, but shouldn't.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.8-0ubuntu0.16.04.3
| Operating system | Ubuntu 16.04.1 LTS 64-bit

**Comment by samdark** [comment]
I don't think it's a good idea to include PK into unique indexes list and especially to generate unique validator for it using Gii. The thing is that PK is usually a surrogate key i.e. serial integer which is never set directly but is taken from a sequence. For such field, unique checks are useless and are performance killers.

**Comment by samdark** [comment]
1. The `findUniqueIndexes()` method is to find indexes explicitly marked as unique. PK is a special case.
2. Changing it is a very significant backwards compatibility break.

So we won't change that. Thanks for proposal anyway.

**Comment by ricpelo** [comment]
No problem, I understand that. Obviously the best approach is to use surrogate keys whenever possible. Thank you very mucho for the explanation!

**Comment by fabioaccetta** [comment]
I have the same problem, but my primary key column is neither a serial nor a numerical one, instead it is of type `ltree`.

What about making gii to detect this difference and generate a `unique` rule when the column is not a serial one?
Could the function `findUniqueIndexes()` be changed to detect this situation?
