### ISSUE TITLE
Error with rules which include a defaults 

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2#13086]
### What steps will reproduce the problem?
I only have 1 rule which includes a defaults but it is not working as expected. 
Here is the rule

`                [
                    'pattern' => '<language>/<brand>',
                    'route' => 'site/brand',
                    'defaults' => ['language' => 'en'],
                ] 
`

If I access domain.com/brand1 I get an error "Not Found (#404)"

Note that if I setup this rule instead: 

`                [
                    'pattern' => 'test/<language>/<brand>',
                    'route' => 'site/brand',
                    'defaults' => ['language' => 'en'],
                ] 
`

and I access domain.com/test/brand1 then I get the expected result and I am redirected to site/brand with the language parameter defaulted to 'en'

### What is the expected result?

The rule should be applied and the default language set to 'en' . 

### What do you get instead?

yii\web\HttpException:404

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.12
| Operating system | Windows 10

**Comment by samdark** [comment]
Could be related to https://github.com/yiisoft/yii2/pull/12610

**Comment by rob006** [comment]
See #13624
