### ISSUE TITLE
symlink(): Cannot create symlink

### ISSUE THREAD

**Issue by zxczxc12** [yiisoft/yii2#13094]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.8
| Operating system | Win10
OpenServer 5.2.2

https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L520-L523

**Comment by samdark** [comment]
Duplicate of https://github.com/yiisoft/yii2/pull/7931
