### ISSUE TITLE
ActiveForm in a pjax-container

### ISSUE THREAD

**Issue by donhuankk** [yiisoft/yii2#13096]
I have ActiveForm in a pjax-container. When i access page using direct link, client validation on form works fine.

But when i try to refresh pjax-container contents client validation not works at all.

How can i reinitialize client validation handlers using pjax:success event without writing tons of code?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0
| Operating system |  Debian 8

**Comment by derekisbusy** [comment]
#13545 Fixes this issue.
