### ISSUE TITLE
Console application: Negative integer parameter causes "Unknown alias" error

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii2#13108]
### What steps will reproduce the problem?
Create console controller with an action which has one required parameter:

    public function actionSend($chatId)
    {
        $result = \Longman\TelegramBot\Request::sendMessage([
            'chat_id'   => $chatId,
            'text'      => 'some text',
        ]);
    }

Than run this command with negative `chatId`:

    yii messenger/send -12345

### What is the expected result?

Expected result is running `actionSend()` with `$chatId` equals to `-12345`

### What do you get instead?

You'll get `Error: Unknown alias: -12345`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.13
| Operating system | Ubuntu 16.0.4

**Comment by klimov-paul** [comment]
What will happen if you wrap your value in quotes:

```
yii messenger/send '-12345'
```

?

**Comment by pana1990** [comment]
@cebe  @uaoleg check my pull request https://github.com/yiisoft/yii2/pull/13220 please.

@cebe can you set this issue to 2.0.11 version?

**Comment by SilverFire** [comment]
Merged: https://github.com/yiisoft/yii2/commit/b985ea34766ca7830b505704a78812ebd40ede08

**Comment by pantsarny** [comment]
still not working, for example:
./yii my-command -123_456

**Comment by samdark** [comment]
```sh
./yii vk/video "-123_456"
```

How about this?

**Comment by pantsarny** [comment]
> ```shell
> ```shell
> ./yii vk/video "-123_456"
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> How about this?
> ```

the same. quotes are interpreted at bash level.

**Comment by bizley** [comment]
Maybe this

```
./yii vk/video -- -123_456
```

**Comment by pantsarny** [comment]
> 

thanks! its works
