### ISSUE TITLE
Oracle optimisation

### ISSUE THREAD

**Issue by zlakomanoff** [yiisoft/yii2#13122]
### What steps will reproduce the problem?
ORM generate system queries like this

```
SELECT
  D.CONSTRAINT_NAME, 
  D.CONSTRAINT_TYPE, 
  C.COLUMN_NAME, 
  C.POSITION, 
  D.R_CONSTRAINT_NAME,
  E.TABLE_NAME AS TABLE_REF, 
  F.COLUMN_NAME AS COLUMN_REF,
  C.TABLE_NAME
FROM ALL_CONS_COLUMNS C
  INNER JOIN ALL_CONSTRAINTS D ON D.OWNER = C.OWNER AND D.CONSTRAINT_NAME = C.CONSTRAINT_NAME
  LEFT JOIN ALL_CONSTRAINTS E ON E.OWNER = D.R_OWNER AND E.CONSTRAINT_NAME = D.R_CONSTRAINT_NAME
  LEFT JOIN ALL_CONS_COLUMNS F ON F.OWNER = E.OWNER AND F.CONSTRAINT_NAME = E.CONSTRAINT_NAME AND F.POSITION = C.POSITION
WHERE C.OWNER = :schemaName
   AND C.TABLE_NAME = :tableName
ORDER BY D.CONSTRAINT_NAME, C.POSITION;
```
this query is wery slow and require to many io.

### What is the expected result?
Execution time 0.8 sec

### What do you get instead?
Execution time 0.025 sec

### Additional info
This hint speedup 11g, i think it working for 12g too, but need investigate
`/*+ PUSH_PRED(C) PUSH_PRED(D) PUSH_PRED(E) */`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.13
| Operating system | Arch GNU/Linux

**Comment by SilverFire** [comment]
How do you suggest to improve this query?

**Comment by zlakomanoff** [comment]
Use hint, like this

```
SELECT
  /*+ PUSH_PRED(C) PUSH_PRED(D) PUSH_PRED(E) */
  D.CONSTRAINT_NAME, 
  D.CONSTRAINT_TYPE, 
  ...
```

**Comment by SilverFire** [comment]
Would you link to send a PR?

**Comment by zlakomanoff** [comment]
yes, i will

**Comment by samdark** [comment]
@mikkelcp1 interesting but we may need some help:

1. The comment will, for certain, will be lost in this long-closed issue. It is worth creating a new one.
2. I currently don't have a good Oracle setup in place so it may take too much time for me to fix/test it properly. If you have time for a pull request that would be way faster.
