### ISSUE TITLE
Bug/Error: ActiveDataProvider::getCount() error when query has extra column

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#13120]
### What steps will reproduce the problem?
```php
$query = MyModel::find()
    ->select(['*', 'score' => 'MATCH([[content]]) against(:term IN BOOLEAN MODE)'])
    ->andWhere(['>', 'score', 0], [':term' => $this->q]);

$dataProvider = new ActiveDataProvider([
    'query' => $query,
 ]);
```

### What is the expected result?
`ActiveDataProvider::getCount()` will return number of row with `score` not zero

### What do you get instead?
```
Database Exception – yii\db\Exception
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
The SQL being executed was: SELECT COUNT(*) FROM `travel_package_search`  WHERE `score` > 0
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.x
| DBMS     | MySql
| Operating system | Ubuntu 16.04

**Comment by Alex-Code** [comment]
If you use `HAVING` this should work as expected as `Query` will use a subquery on count.
```php
$query = MyModel::find()
    ->select(['*', 'score' => 'MATCH([[content]]) against(:term IN BOOLEAN MODE)'])
    ->andHaving(['>', 'score', 0], [':term' => $this->q]);
```

https://github.com/yiisoft/yii2/blob/master/framework/db/Query.php#L427

**Comment by cebe** [comment]
this is a limitation of PDO, you can not bind params to select().
