### ISSUE TITLE
Guide: RBAC - frontend\models\SignupForm::signup()  correct the docs

### ISSUE THREAD

**Issue by rubenjleon** [yiisoft/yii2#13125]
http://www.yiiframework.com/doc-2.0/guide-security-authorization.html
Section:  **frontend\models\SignupForm::signup()**
In the section describing assigning default roles at sign up, I suggest fixing the docs so the code works:

```php
$auth = Yii::$app->authManager;
``` 
should be 
```php
$auth = \Yii::$app->authManager;
```

Or add the following code to **frontend\models\SignupForm::signup()** by default
```php
use Yii;
```

### What steps will reproduce the problem?
- Install Advanced app
- configure the database, 
- run the migration to create the "user"  table

Follow:  
http://www.yiiframework.com/doc-2.0/guide-security-authorization.html
```php
        'authManager' => [
        	'class' => 'yii\rbac\DbManager',
        ],
```
- Run the RBAC migration:
```
yii migrate --migrationPath=@yii/rbac/migrations
```
- create the console/controllers/RbacController  as described in the Guide
- Run, the 
``` 
yii rbac/init
```
- Modify frontend\models\SignupForm::signup() as described in the Guide
- Now sign up a new user.  Upon submit, I get this Error:

Class 'frontend\models\Yii' not found

### What is the expected result?
I expected this user to be assigned a default role in the db (auth_assignment table) but I get a stack trace.

### What do you get instead?
```
00:47:35.996	error	Error	Error: Class 'frontend\models\Yii' not found in /Library/WebServer/vhosts/advanced/frontend/models/SignupForm.php:71
Stack trace:
#0 /Library/WebServer/vhosts/advanced/frontend/controllers/SiteController.php(153): frontend\models\SignupForm->signup()
#1 [internal function]: frontend\controllers\SiteController->actionSignup()
#2 /Library/WebServer/vhosts/advanced/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#3 /Library/WebServer/vhosts/advanced/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#4 /Library/WebServer/vhosts/advanced/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('signup', Array)
#5 /Library/WebServer/vhosts/advanced/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('site/signup', Array)
#6 /Library/WebServer/vhosts/advanced/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 /Library/WebServer/vhosts/advanced/frontend/web/index.php(17): yii\base\Application->run()
#8 {main}
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  7.0.11
| Operating system |  macOS Sierra Version 10.12.1

**Comment by dynasource** [comment]
thanks for sharing this issue. It makes sense to have examples in the docs to be more reliable.

**Comment by SilverFire** [comment]
The issue consists of two parts. @dynasource could you check migrations as well?
