### ISSUE TITLE
Query bind params using operator format with MSSQL 

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#13138]
### What steps will reproduce the problem?
    $count->where(['between', 'field', ':start',':end' ])
           ->addParams([':start' => $x, ':end' => $y]);

### What is the expected result?

The query not to to fail

### What do you get instead?

Invalid parameter number: parameter was not defined

BUT, if I change the clause to: `where('field BETWEEN :start AND :end' )->addParams([':start' => $x, ':end' => $y]);`

Query succeeds, is this expected behavior?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10.?
| PHP version      | 5.6
| Operating system | Windows 7

**Comment by samdark** [comment]
No, it's not. What is the query generated by query builder in case of error?

**Comment by jonny7** [comment]
SELECT * FROM (SELECT *, SUM(CASE WHEN type IS NULL THEN 1 ELSE 0 END) OVER (PARTITION BY id) AS sorter FROM "reg" ) t WHERE digit BETWEEN :startRange AND :endRange ORDER BY "sorter" DESC, "id", "type"

is the query if I don't use the operator format. When I change to operator format it returns:

>SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
Failed to prepare SQL

    SELECT * FROM (SELECT *, SUM(CASE WHEN type IS NULL THEN 1 ELSE 0 END) OVER (PARTITION BY id) AS sorter FROM "reg" ) t WHERE [digit] BETWEEN :qp2 AND :qp3 ORDER BY [sorter] DESC, [id], [type]

**Comment by samdark** [comment]
OK. That's definitely a bug. If you want it fixed in 2.0.11 you may work on a pull request. Otherwise, will get back to in after 2.0.11 release.

**Comment by jonny7** [comment]
Ok thanks, i'll have a look into it :+1:

**Comment by cebe** [comment]
> ['between', 'field', ':start',':end' ]

array syntax does automatic quoting so params will not work inside of the parameters unless you use Expression.
