### ISSUE TITLE
Add support for Closures in grid column footer and header

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2#13130]
It is a common need to add into gridview widget sum of totals into column footers, or optionally formatted output (e.g. red text for negative values). Current implementation (/grid/column.php) only accepts strings. Adding support for more flexible closures would allow much more flexible implementations.

Example of view implementation:

```
<?= GridView::widget([
   'dataProvider' => $dataProvider,
   'filterModel' => $searchModel,
   'showFooter' => true,
   'columns' => [
	...
	[
	   'attribute' => 'counter',
	   'footer' => function(yii\data\ActiveDataProvider $dataProvider, $filterModel, $column){
		   return $dataProvider->query->sum('counter');
	   },
	],
	...
   ],
]); ?>

```

PR will follow.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11

**Comment by klimov-paul** [comment]
You do not need a `Closure` for this:

```php
<?= GridView::widget([
   'dataProvider' => $dataProvider,
   'filterModel' => $searchModel,
   'showFooter' => true,
   'columns' => [
	...
	[
	   'attribute' => 'counter',
	   'footer' => $dataProvider->query->sum('counter'),
	],
	...
   ],
]); ?>
```

**Comment by mtangoo** [comment]
Hi,
I believe this is a valid use case and Grid is in many cases representing some sort of numbers with a footer representing some sort of calculation done with the column (like summation).

Currently a workaround is creating a component that works on summation as extending datacolumn is not an option. Adding that will be great.

Plus @klimov-paul solution does not work for SqlDataProvider.

**Comment by mtangoo** [comment]
Some So questions with hints on closure:
https://stackoverflow.com/questions/28003381/yii2-gridview-how-use-totals-on-footer-property
https://stackoverflow.com/questions/40629352/yii2-get-sum-in-footer-of-gridview

**Comment by samdark** [comment]
@mtangoo I see no need for the closure support there as well. Footer value could be pre-computed and doesn't depend on anything that isn't available before the call unlike rows.

**Comment by mtangoo** [comment]
@samdark I don't want to be stiff-necked here but most of us "pre-computes" it by getting models and loop through them singling out the column and do around the math. That is not efficient. If I have let say 10 columns, I have to go thru the same process 10 time.

May be I'm missing something and my solution is based on misinformation in which case I would like to hear your opinion on how you deal with such case, especially when you have many columns in the table.

Thank you!

**Comment by samdark** [comment]
Won't you do exactly the same loop in the closure you want?

**Comment by mtangoo** [comment]
> Won't you do exactly the same loop in the closure you want?

Is that so? I thought in that case the gridView will be calling the closure passing current model value, If it was so then for each row one iteration would do it by passing same model to all columns.

So in my solution if I have `c` columns and provider have `m` models then total iterations would be `c times m` while with closure it will be only `m` since at every iteration (row) all closure get called.

**Comment by lubosdz** [comment]
I think this issue is more about developer-friendly API. 
Sure, there are always workarounds. 
From developer's view creating workarounds & pre-computations is less flexible than using closure. 
Particularly, if they are already supported on other similar places ...

**Comment by samdark** [comment]
What if you want average or weighted average or percentage instead of sum in the footer? How would you do that with closure?

**Comment by mtangoo** [comment]
@samdark , I see your point. I have tried to create a solution with your use case and I found that it is far complex than just taking models and calculate somewhere else. I then agree it is not worthy the efforts.
