### ISSUE TITLE
i18n plural is not working on production

### ISSUE THREAD

**Issue by Webkadabra** [yiisoft/yii2#13137]
### What steps will reproduce the problem?

In my view, I got:

```
return Yii::t('nfy', '<strong>{n,plural,=0{No orders} =1{One order} other{# orders}}</strong> need to be fulfilled', ['n' => $this->count]);
```

In messages (`nfy.php`) I have

```
'<strong>{n,plural,=0{No orders} =1{One order} other{# orders}}</strong> need to be fulfilled' => '<strong>{n,plural,=0{Нет заказов} =1{Один заказ} one{# заказ} few{# заказа} many{# заказов} other{# заказа}}</strong> которые нужно отправить', 
```

On a local machine, translation is applied correctly. However, on a production server, I get a raw translation string (this is what gets rendered after `Yii::t`):

```
{n,plural,=0{Нет заказов} =1{Один заказ} one{# заказ} few{# заказа} many{# заказов} other{# заказа}} которые нужно отправить
```
### What is the expected result?

It should be like `4 заказа которые нужно отправить`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.5.38
| Operating system | CentOS

**Comment by cebe** [comment]
please check the log file for warnings. It should contain more info on why the server env complains about the message pattern.

**Comment by samdark** [comment]
Do you have intl and ICU data installed?

**Comment by Webkadabra** [comment]
@samdark yes:

```
> php -i | grep ICU
ICU version => 4.2.1
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I thought it could be because of missing libs too, but devops ensured intl and ICU is installed.

**Comment by Webkadabra** [comment]
@samdark @cebe thanks for the feed back, I found some additional info in warnings!

```
2016-12-05 18:26:16 [91.200.3.238][9][-][warning][yii\i18n\I18N::format] Formatting message for language 'ru' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_CHARACTER. The message being formatted was: <strong>{n,plural,=0{Нет заказов} =1{Один заказ} one{# заказ} few{# заказа} many{# заказов} other{# заказа}}</strong> которые нужно отправить.
2016-12-05 18:26:16 [91.200.3.238][9][-][warning][yii\i18n\I18N::format] Formatting message for language 'ru' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_CHARACTER. The message being formatted was: <strong>{n,plural,=0{Нет заказов} =1{Один заказ} one{# заказ} few{# заказа} many{# заказов} other{# заказа}}</strong> по которым нужно получить оплату и отправить.
```

**Comment by Webkadabra** [comment]
Looks like I need a newer version of ICU, I will update on how this goes after my ICU is updated. Thanks!

**Comment by samdark** [comment]
Yes. You've got it right.

**Comment by cebe** [comment]
at least ICU 4.8 should be used.

**Comment by SilverFire** [comment]
There is a requirements checking script. Check out [Verifing Instalation](http://www.yiiframework.com/doc-2.0/guide-start-installation.html#verifying-installation) guide article to know more

**Comment by buttflattery** [comment]
is there, by any chance a possibility to use the fallback old method in case we are not able to update the ICU extension @SilverFire  @samdark

**Comment by cebe** [comment]
@buttflattery in which environment do you have ICU < 4.8? even debian oldoldstable (wheezy) has ICU 4.8.

**Comment by buttflattery** [comment]
@cebe my hosting provider is using `Red Hat 4.4.7 (from around 2012?)`, Linux `version 2.6.32`. `requirements.php` says the same - 

> ICU is too old, and ICU Data is missing. 

And they don't want to make any changes on the server

**Comment by buttflattery** [comment]
@cebe is there anything I can do to sort out this problem?

**Comment by samdark** [comment]
Yes. Either change your hosting or persuade them to update.

**Comment by buttflattery** [comment]
:( isn't there any possibility of copying the `yii\i18n\MessageFormatter` code to a new file. and place in `components` and override the `format()` like below
 
```
public function format($pattern, $params, $language)
{
    $this->_errorCode = 0;
    $this->_errorMessage = '';

    if ($params === []) {
        return $pattern;
    }

    return $this->fallbackFormat($pattern, $params, $language);
}
```

and then add the class mapping in bootstrap like 

 `Yii::$classMap['yii\i18n\MessageFormatter'] = 'path/to/your/MessageFormatter.php';`

In the modified file `MessageFormatter` method presence of `intl` library will never be checked so the fallback is used as default.

Would this be vulnerable by any mean or will have negative effect other than i have to update the file every time i update composer. @samdark

**Comment by samdark** [comment]
Yes, you can do that as well but fallback doesn't work well with non-default language and has very limited functionality compared to intl.
