### ISSUE TITLE
Guide Docs: RBAC namespace clarification/correction

### ISSUE THREAD

**Issue by rubenjleon** [yiisoft/yii2#13132]
http://www.yiiframework.com/doc-2.0/guide-security-authorization.html

The yellow Note right after **Building Authorization Data** I believe may incorrectly state the syntax for the namespace in the advanced app 
 
```
Note: If you are using advanced template, you need to put your RbacController inside console/controllers directory and change namespace to console/controllers.
```

Namespace should be:
```
console\controllers
```

**Comment by cebe** [comment]
Took me some time to notice the difference, just to be clear, you are talking about the backslash vs. slash in the namespace, right?

**Comment by cebe** [comment]
Fixed, thanks for reporting!
