### ISSUE TITLE
Creating url using yii\helpers\Url::to

### ISSUE THREAD

**Issue by samuelroxo** [yiisoft/yii2#13156]
There is a issue when you try to create a url passing absolute path and schema in parameters.

For exemple:
`Url::to('@cdn/images/logo.gif', 'http');`
When `@cdn` is an alias for `//cdn.exemple.com`

Will output:
`http://www.example.com/cdn.exemple.com/images/logo.gif`

The lack of some blocks of code after the following commit may be causing this issue:
https://github.com/yiisoft/yii2/commit/2d91723934abac1b9d202eae3827de015b7c927a#diff-477d3f5c7059d9e20a85ef9675f2af3cL221

**Comment by cebe** [comment]
@rob006 it seems to be caused by your commit, could you check it?

**Comment by rob006** [comment]
#13157
