### ISSUE TITLE
View::registerJsFile doesn't append timestamp for not mapped assets

### ISSUE THREAD

**Issue by DarthLegiON** [yiisoft/yii2#13163]
Hello!
I used such code for registering Js file in view:
```php
$this->registerJsFile('@web/js/result-index.js', ['depends' => [AppAsset::className()]]);
```
I have an `appendTimestamp` property set on `true` but timestamp near file import doesn't appears (see https://github.com/yiisoft/yii2/pull/10297#issuecomment-265699405).

It behaviors such way because of truncating alias `@web/js/result-index.js` to relative `/js/result-index.js` and `$basePath = null` (see https://github.com/yiisoft/yii2/commit/3ec3ce931216a44ec0b850c429c9d8c7f9a17e6d) for created `AssetBundle`. Solution is only using `assetMap` property of `AssetManager` and creating aliases for used Js files. 

```php
'assetMap' => [
    'result-index.js' => '@web/js/result-index.js',
],
```

Is there another, more simple solution? I have a lot of dynamically registered Js and Css files in my project, creating aliases may take some time, and this solution is not universal for all potential use cases. Thanks!

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.8
| Operating system | CentOS 6, Windows 10

**Comment by SilverFire** [comment]
> I have a lot of dynamically registered Js and Css files in my project

You can create AssetBundles for those JS as CSS files and `appendTimestamp` will apply to them. I can't suggest you easier way to solve your problem, sorry.
