### ISSUE TITLE
Bad translation in bulgarian

### ISSUE THREAD

**Issue by therendstudio** [yiisoft/yii2#13169]
### What steps will reproduce the problem?
File vendor\yiisoft\yii2\messages\bg\yii.php:74
### What is the expected result?
  '{attribute} must be a string.' => 'Полето "{attribute}" трябва да съдържа текст.',

### What do you get instead?
  '{attribute} must be a string.' => 'Полето "{attribute}" трябва съдържа текст.',

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by samdark** [comment]
Would you please send a pull request?
