### ISSUE TITLE
Allow repeated initialization in yii.captcha.js

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13166]
HTML:

```html
<img id="captcha" src="/site/captcha/">
```

JS:

```js
$('#captcha').yiiCaptcha({
    refreshUrl: '/site/captcha?refresh=1',
    hashKey: 'yiiCaptcha/site/captcha'
});
```

On each repeated init according `init` method will run and as a result 1 more additional AJAX request will be executed when clicking on the image.

Even the plugin is tiny, ideally it needs to check if it was already initialized with this element.

- If it was initialized before with the same exact settings - we can warn the user with according message.
- If it was initialized before but with different settings, we need to destroy it and reinitialize it with new settings.

Comparing of the settings is not difficult here, but as an alternative we can always destroy and reinitialize.

As I said in #13159, majority of the people will never get into this kind of trouble because they just add captcha on PHP side, it will automatically generate JS and they forget about it.

But with writing tests and potential decoupling of JS I think it becomes more important.

I think `yii.captcha.js` is not the only plugin with this problem, but firstly I noticed it there in #13160.

**Comment by dynasource** [comment]
can you shortly point us to the difference of this topic compared to https://github.com/yiisoft/yii2/issues/13159?

**Comment by arogachev** [comment]
@dynasource #13159 is about `destroy` method, this is about `init` method.

**Comment by dynasource** [comment]
thx

**Comment by dynasource** [comment]
> But with writing tests and potential decoupling of JS I think it becomes more important.

that a good argument. Lets detangle the captcha JS into smaller units and refactor it to perfection. I have the feeling that you already have a PR in mind to fix it right?

**Comment by arogachev** [comment]
@dynasource No PR yet, but I know how to fix it. I think we should fix it first with current code condition, then do refactoring / decoupling at the global level. Also decoupling needs more thinking and diccussion - use ES6 or not, etc.

**Comment by samdark** [comment]
Closing:

1. We won't be able to do it in 2.0.14.
2. 2.0.15 can't have enhancements.
3. 2.1 won't have captcha (it will be separate package).
