### ISSUE TITLE
Yii can't validate the _identity cookie in backend

### ISSUE THREAD

**Issue by Imlegendb** [yiisoft/yii2#13174]
Updated my advanced app to latest Yii 2.0.10 using composer, and since then Yii can't validate the _identity cookie it generates. This problem appears only in backend part of the application. I see _identity cookie (expires in 31 days) and I can access it using $_COOKIE["_identity"], but \Yii::$app->getRequest()->getCookies()->getValue('_identity') always returns null unless I set enableCookieValidation to false.

When I try to open any frontend page or even some page with "die()" in it, all backend pages start working, but after an hour or so, I have to deal with that problem again.

Yii 2.0.10
PHP 7.0.4

**Comment by cebe** [comment]
You need different names for backend and frontend cookie, this was not the case in advanced app if you got it before 2.0.9. See https://github.com/yiisoft/yii2-app-advanced/commit/ec1148c4f62e12098a3eb650f8e66fe6c23a6323 and https://github.com/yiisoft/yii2-app-advanced/commit/bb35a7543aa5b718b01d6cd576d78da9e4193249

**Comment by Imlegendb** [comment]
But what if I want sessions to be shared between backend and frontend? It looks like I have to create separate login pages now, or did I get something wrong?

This is how I access my backend app, so I dont really need different names for cookie.

```
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if(\Yii::$app->user->identity->admin == 0) 
                                return false;
                            
                            return true;
                        },
                    ],
                ],
            ],
        ];
    }
```

**Comment by cebe** [comment]
if you want both apps to share the cookie, you have to set the same cookie validation key in backend and frontend.
