### ISSUE TITLE
Filter in where with null

### ISSUE THREAD

**Issue by Aficionado-desu** [yiisoft/yii2#13177]
### What steps will reproduce the problem?
Try to filter the records where field_name is null with andFilterWhere(['field_name' => null])

### What is the expected result?
Get the records where field_name is null.

### What do you get instead?
No filter on filter_name field.

### Additional info
I'm new to Yii, and maybe I'm wrong, but in documentation says:

> ['status' => null] generates status IS NULL.

But in QueryTrait.php, line 227, if the filter has a null value, it gets dropped:

`foreach ($condition as $name => $value) {
                if ($this->isEmpty($value)) {
                    unset($condition[$name]);
                }
            }`

I 'solved' it with a string 'null' (instead of a real null value) and then, in QueryBuilder.php, line 1038, I changed:

`if ($value === null) {`

(Is this situation even possible? If value=null was previously unset, how can be null here?)

with

if ($value === 'null') {

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version     |7.0.8-0ubuntu0.16.04.3 
| Operating system |GNU/Linux

**Comment by dynasource** [comment]
to my knowledge this does not work. You have to use  andFilterWhere('field_name IS NULL') for that.

**Comment by Alex-Code** [comment]
By design the filter functions ignore empty input, http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#filter-conditions

If you wan't to compare on `null` you need to use `andWhere(['field_name' => null])`.

**Comment by Aficionado-desu** [comment]
Yes, you are right. Sorry, I mixed andFilterWhere with andWhere.
