### ISSUE TITLE
RBAC BaseManager - check if rulename === ''?

### ISSUE THREAD

**Issue by atomasevic** [yiisoft/yii2#13179]
I'm referring to this function:

```
    protected function executeRule($user, $item, $params)
    {
        if ($item->ruleName === null) {
            return true;
        }
        $rule = $this->getRule($item->ruleName);
        if ($rule instanceof Rule) {
            return $rule->execute($user, $item, $params);
        } else {
            throw new InvalidConfigException("Rule not found: {$item->ruleName}");
        }
    }
```

You have `$item->rulename === null` check, what about `$item->rulename === ''` (empty string check)?

Some migration utilities create (like https://github.com/c006/yii2-migration-utility) create insert data with rulename as empty string. 

Does this make any sense to you, or should I post issue to yii2-migration-utility github?

**Comment by samdark** [comment]
Posting to yii2-migration-utility is a good idea.
