### ISSUE TITLE
Add GraphQL Support (Yii2.1.x ideas)

### ISSUE THREAD

**Issue by zzzeep** [yiisoft/yii2#13182]
> GraphQL is a query language for your API, and a server-side runtime for executing queries by using a type system you define for your data. GraphQL isn't tied to any specific database or storage engine and is instead backed by your existing code and data.

A GraphQL query is a string that is sent to a server to be interpreted and fulfilled, which then returns JSON back to the client.

![image](https://cloud.githubusercontent.com/assets/13196890/21074468/aa8c3706-bf34-11e6-8fd4-c9c8399b7cab.png)

**Comment by samdark** [comment]
I'm afraid it's out of scope of the core framework and it's better to be done as community extension. If there is something particular to adjust in the framework to support such extension, let us know.

**Comment by tunecino** [comment]
Yap community have responded if anyone is interested:
https://github.com/tsingsun/yii2-graphql

I didn't try it as I'm happy using classic REST as far as I can design and expand relations the way I want, ask for specific fields, filter, sort, limit results and expect proper pagination. So I don't see much advantages worth the switch but I'm also aware that GraphQL is getting too popular and may become a requirement to interact with other apps at some point in the future. So it is always nice to see community working in such extensions.

**Comment by upasanadash** [comment]
Hello everyone,
could anyone tell me GraphQL supports Yii 1.1 Framework or not?

**Comment by samdark** [comment]
No, that one is for Yii 2.0 only.

**Comment by upasanadash** [comment]
But I want to use it with Yii 1.1. As the project structure already in Yii 1.1. Could you suggest me something?

**Comment by samdark** [comment]
Brief googling revealed https://github.com/TerraSkye/yii1-graphql. Not sure how good is that.

**Comment by upasanadash** [comment]
thank you
