### ISSUE TITLE
Why Yii2's variable declaration is different from PHP standards?

### ISSUE THREAD

**Issue by Mapsai** [yiisoft/yii2#13187]
Hello,

I'm wondering why Yii2 developers use slightly different local variable declaration in comments than PHP documentations?

For example from documentation:
`/** @var string $key The key to delete */`

In Yii2 we have:
`/* @var $this yii\web\View */`

Does this change mean something different for Yii2 specifically or just it's developers' choice?

**Comment by samdark** [comment]
Both are OK.

- `/* @var` is vardoc syntax.
- `/** @var` is phpdoc syntax.

Previously Netbeans IDE supported vardoc only while PhpStorm supported both. Not sure how it's now.

**Comment by Mapsai** [comment]
Understood. Thank you for quick response.
