### ISSUE TITLE
Same loop, more iteration the longer it take (insertion of 7.5Millions via query)

### ISSUE THREAD

**Issue by vinpel** [yiisoft/yii2#13180]
### What steps will reproduce the problem?
i'm not sure it 's a bug or not but when i insert a lot of data into a mySQL (7.5 Millions).
I take data from an xml zipped file.
Each time the same loop is more and more slower :

|Avancement|Time In seconds|Memory
|----|--|--
|0% (0/7561217) ETA: n/a         |Temps : 14.824               |memoire : 19.75 megabytes
|0% (50000/7561217) ETA: 2253 sec.|Temps : 14.694               |memoire : 20 megabytes
|1% (100000/7561217) ETA: 2238 sec.|Temps : 16.012               |memoire : 22.25 megabytes
|1% (150000/7561217) ETA: 2371 sec.|Temps : 19.880               |memoire : 21.25 megabytes
|2% (200000/7561217) ETA: 2944 sec.|Temps : 20.388               |memoire : 22.75 megabytes
|3% (250000/7561217) ETA: 2924 sec.|Temps : 21.284               |memoire : 20.25 megabytes
|3% (300000/7561217) ETA: 3049 sec.|Temps : 24.312               |memoire : 22.5 megabytes
|4% (350000/7561217) ETA: 3605 sec.|Temps : 25.113               |memoire : 21.25 megabytes
|5% (400000/7561217) ETA: 3580 sec.|Temps : 28.114               |memoire : 23 megabytes
|5% (450000/7561217) ETA: 3982 sec.|Temps : 28.781               |memoire : 20.25 megabytes
|6% (500000/7561217) ETA: 4095 sec.|Temps : 31.229               |memoire : 22.75 megabytes
|7% (550000/7561217) ETA: 4346 sec.|Temps : 33.106               |memoire : 20 megabytes
|7% (600000/7561217) ETA: 4594 sec.|Temps : 36.200               |memoire : 23.25 megabytes
|8% (650000/7561217) ETA: 4976 sec.|Temps : 37.894               |memoire : 19.75 megabytes
|9% (700000/7561217) ETA: 5214 sec.^T|Temps : 39.509               |memoire : 23.5 megabytes
|9% (750000/7561217) ETA: 5448 sec.|Temps : 40.795               |memoire : 20.75 megabytes
|10% (800000/7561217) ETA: 5544 sec.|Temps : 43.306               |memoire : 22.5 megabytes
|11% (850000/7561217) ETA: 5771 sec.|Temps : 44.139               |memoire : 20.25 megabytes
|11% (900000/7561217) ETA: 5861 sec.|Temps : 45.581               |memoire : 22.75 megabytes
|12% (950000/7561217) ETA: 6082 sec.|Temps : 48.165               |memoire : 22.25 megabytes
|13% (1000000/7561217) ETA: 6298 sec.|Temps : 49.626               |memoire : 23.25 megabytes
|13% (1050000/7561217) ETA: 6380 sec.|Temps : 52.070               |memoire : 21 megabytes
|14% (1100000/7561217) ETA: 6719 sec.

### What is the expected result?
Constant time been each 50 000 insertion

### What do you get instead?
start a  14 sec -> 67 sec and each time it get slower

  * I read data from a local disk (xml file).
  * The format of the data are all the same
  * no other activity on the server

every 50 000 i print time
every 600 it do "loop" of 2 querys :

      $countData=$Rqcount->select('COUNT(*) as nb,field)
      ->from($nomtable)
      ->where(['in',$nomChamp,$ArrayOf600Id])
      ->groupBy($this->champExport[$nomTable]['donnee_unicite'])
      ->All();
and :

     \Yii::$app->db->createCommand()->batchInsert(  
     $nomtable, $nomChamp,$ArrayOf600DataLines)->execute();

without the query (read Xml, do all the other test) no noticeable change of duration ... 
strange ... 
did yii2 store something that can be desactivated who can slow that ?
have you an idea ?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6
| Operating system | Alpine 3.3.3

**Comment by nkostadinov** [comment]
this must be the mysql slowing down as you insert more data into it. do you have indexes ? do you clear the table after each batch insert of 50k ? I dont think this is an yii issue

**Comment by dynasource** [comment]
try to insert without:
* other queries (they will slow you down when the tables gets bigger)
* indexes (which slow down inserts)

**Comment by cebe** [comment]
as said above, the bigger your table, the longer it takes to handle indexes and the longer it takes to compute a `GROUP BY` on the table.
