### ISSUE TITLE
css files of widgets are not adding in html 

### ISSUE THREAD

**Issue by kishor10d** [yiisoft/yii2#13193]
### What steps will reproduce the problem?
I am using multiple widgets in yii2-advanced-template. Assets are generating for every widget in ```web/assets``` folder. But only JS are added to HTML, not CSS.

Also if I want to register the css with ```$this->registerCssFile();```, it is not adding css in html at all.

**Note :**  The same is working in other fresh yii2-advance-template but not in my current template.

### What is the expected result?
Add all required JS and CSS. and widget work as expected.

### What do you get instead?
JS are added in HTML but no CSS, and widget not working as expected.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | PHP 5.6.24 (cli) (built: Jul 20 2016 21:19:29)
| Operating system | Windows 10

**Comment by Alex-Code** [comment]
First I'd update to the latest version of Yii and check if the issue still exists.
If it does then we need more code to diagnose.

What widgets are you using?
What does your action look like?
What does your view look like?

**Comment by kishor10d** [comment]
**What widgets are you using?** : kartik-v/file-upload, 2amigos/file-upload. Anyway, it happens with all widgets I have. I think registerCssFile is not working as expected.

**What does your action look like?**

_Action_

```
public function actionUploadProductImages()
{
	$prId = Yii::$app->request->get("id");
	$prodModel = \backend\models\Product::findOne($prId);
	$mdlproductimage = new \backend\models\ProductImages();
	$mdlproductimage->prid = $prId; 
	
	if($prId > 0 ){
		return $this->render('auto', [
			'prodModel' => $prodModel,
			'mdlproductimage' => $mdlproductimage,
		]);
	} else {
		return $this->redirect(['index']);
	}
}
```

**What does your view look like?**

_auto.php_

```
<?php
use yii\helpers\Html;
$this->title = Yii::t('app', 'Upload Images : '.$prodModel->prodname);
?>
<div class="container">
	<ul class="breadcrumb">
		<li><a href="index.php?r=vendor/vendorlayout">Home</a></li>
		<li class="active"><?= $this->title ?></li>
	</ul>
	<div class="product-create">
		<h1><?= Html::encode($this->title) ?></h1>
	    <?= $this->render('_form2', [
	    	'prodModel'=>$prodModel,
	        'mdlproductimage'=> $mdlproductimage,
	    ]) ?>
	</div>
</div>
```

__form2.php_

```
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
//use kartik\file\FileInput;
use dosamigos\fileupload\FileUploadUI;
?>
<link rel="stylesheet" type="text/css" href="<?= Yii::$app->params["BACK_BASE_URL"]?>css/form.css" />
<div class="row">
    <div class="col-md-12 col-xs-12"> 
        <div class="product-form">
            <?php $form = ActiveForm::begin([ 'action'=>"index.php?r=product/upload-images", 'options' => ['enctype' => 'multipart/form-data', 'id' => 'productImagesForm']]); ?>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                	<?php echo Html::activeHiddenInput($prodModel, 'prid');?> 
                </div>
            </div>
            <div class="mt20"></div>
            <div class="row">
            	<div class="col-md-12 col-sm-4 col-xs-12">
	            <?= FileUploadUI::widget([
			            'model' => $mdlproductimage,
			            'attribute' => 'image',
			            'url' => ['product/image-upload', 'id' => $mdlproductimage->primgid],
			            'gallery' => false,
			            'fieldOptions' => [
			                    'accept' => 'image/*'
			            ],
			            'clientOptions' => [
			                    'maxFileSize' => 2000000
			            ],
			            // ...
			            'clientEvents' => [
			                    'fileuploaddone' => 'function(e, data) {
			                                            console.log(e);
			                                            console.log(data);
			                                            $.each(data.result.files, function(index, file){
			                                                console.log(file.url);
			                                            });
			                                        }',
			                    'fileuploadfail' => 'function(e, data) {
			                                            console.log(e);
			                                            console.log(data);
			                                        }',
			            ],
			        ]);
			    ?>
			    </div>
			</div>
			<div class="mt20"></div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
```

**Comment by cebe** [comment]
how does the asset bundle look like and which files do not get published/registered?

**Comment by dynasource** [comment]
> Note : The same is working in other fresh yii2-advance-template but not in my current template.

please take in mind that this is not a helpdesk. The fact that the same is working in a fresh advanced template (as you pointed out), this has something to do with your customized code.

**Comment by kishor10d** [comment]
@dynasource : Thanks. I ask the same question on stackoverflow (which is the right place of asking help). I got the solution there.
I missed ```$this->head()``` in head section of ```layout/main.php```. I thought it may be any configuration setting I missed, so I want to know that; Is there any configuration regarding this or not? Anyway I understand my mistake.
