### ISSUE TITLE
Unique validator on form with ajaxValidation enabled and validationUrl set showing error

### ISSUE THREAD

**Issue by oduncan10** [yiisoft/yii2#13197]
### What steps will reproduce the problem?
set up form with: 

```php
$form = ActiveForm::begin(['id' => $formId,
    'enableAjaxValidation' => true,
    'validationDelay' => 500,
    'validationUrl' => ['/controller/validate'],
    'validateOnType' => true
]);
```

```php
$form->field($model, 'username')->textInput()
```

in controller set up action for valdationUrl: 

```php
   public function actionValidate() {
        $model = new formModel();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }
    }
```

In model: 

```php
    public function rules() {
        return [
                ['username', 'unique', 'message' => 'This username has already been taken.'],
        ];
    }
```

### What is the expected result?
On update of existing model, the unique validator ignores the existing value (username) and only checks against other usernames, if you blur the field without changing the username it should validate with no errors, but if you change it to another username that already exists in the DB it should throw an error saying the username is already taken.
### What do you get instead?
username: admin

On update of a model instance. If you blur the username field without changing the value (admin), it shows the validation error message (username has already been taken), but lets you save the model (I assume it validates on the server side, which it should).  However, in this case it should NOT show the error message.  This only became apparent when I enabled ajaxvalidation on the form and set up a validation url, so it is important to set up the form the same way.

### Additional info

On update of a model instance. If you change the username field from admin to another value (ex. james) and a record exists with the username james it shows the validation error message (as it should) and will not let you save (will not pass server side validation) as it should. 

It appears to behave almost as intended, it just shouldn't show validation error on attribute when attribute value matches the current attribute value of the model being updated.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0.10
| Operating system | Windows 10

**Comment by cebe** [comment]
In the update case you have to use the correct model instance in the validation action, i.e. pass the id of the model to the action and load the model from the database. otherwise unique validator validates a new model instance which of course can not be added as there already exists a user named admin.
