### ISSUE TITLE
Wrong @inheritdoc DocBlock tag

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2#13208]
It comes from https://github.com/php-integrator/atom-base/issues/257 .

The `@inheritdoc` tag used across the framework source code (as well as the Gii-generated code) seems to be wrong. [Draft PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#62-using-the-inheritdoc-inline-tag-to-augment-a-description) uses `{@inheritDoc}` (note the capital D and the curly braces), and [phpDocumentor](https://www.phpdoc.org/docs/latest/guides/inheritance.html#the-inheritdoc-tag) uses `{@inheritDoc}` inside the long description.

This issue could be easily fixed with a simple `@inheritdoc` => `@inheritDoc` massive change.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by cebe** [comment]
related to #11635

**Comment by cebe** [comment]
I do not think it should be changed in Yii. See my comment in php-integrator/atom-base#257.
