### ISSUE TITLE
[docs] Autoload some fixtures now we dont have FixtureHelper

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#13203]
I am pretty sure we should have any docs about using fixtures globally (practical examples). Current docs limits itself by saying: 

> Using global fixtures is similar to using non-global ones. The only difference is that you declare these fixtures in yii\codeception\TestCase::globalFixtures() instead of fixtures(). When a test case loads fixtures, it will first load global fixtures and then non-global ones.

### What is the expected result?
Docs about **practice ways** to load fixtures automatically, like global fixes, even for **functional** testing;

### What do you get instead?
http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html#defining-and-using-global-fixtures
It does not explain how to do it. I used to load fixtures through FixtureHelper that now is not included in the fw anymore. Even FixtureHelper is not documented. I found how to use it by reading comments in issues and over web.

### Additional info
http://www.yiiframework.com/forum/index.php/topic/73349-how-to-auto-load-some-fixtures-for-functional-testing/

If anyone could give some tips/guidelines I could even update the docs after and make a PR.

Thanks. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.01
| Operating system | Mint 18

**Comment by cebe** [comment]
I have written an answer to your forum post. FixtureHelper is not a class provided by Yii, so I have no idea what that was or how it works. Fixtures as described in the guide are mainly used for unit testing. If there is a way to use them for functional testing the `FixtureController` class could maybe help with that, but i have no experience with that.

**Comment by samdark** [comment]
I think it's this helper: https://github.com/yiisoft/yii2-app-advanced/blob/2.0.0/tests/codeception/common/_support/FixtureHelper.php

**Comment by samdark** [comment]
Codeception Yii module nowadays is able to load fixtures by itself: http://codeception.com/for/yii

**Comment by slinstj** [comment]
codeception.com/for/yii is really useful. I already had readen from the start to the end.

But, the only thing I see I can do using codeception, without Yii facilities (I mean, an Yii helper like FixtureHelper) is to use `load` config of the codeception to dump all data in a only set before each test *or*  use haveInDb() method. 

Not sure that it (haveInDb) will be *pleasant* to code, but it could be a cleaner way to "declare" pre requisites in the functional testing or to show real data situation. Obviously could be turn a mess too!

**Comment by slinstj** [comment]
> I have written an answer to your forum post. 

Thank you. I will see it!

> FixtureHelper is not a class provided by Yii, so I have no idea what that was or how it works. Fixtures as described in the guide are mainly used for unit testing. If there is a way to use them for functional testing the FixtureController class could maybe help with that, but i have no experience with that.

Ok, no problem. I think samdark has already answered. It seems that those fixtures things will not be "managed" entirely by Yii anymore, but from now on we will have to use codeception ways to do it.

**Comment by slinstj** [comment]
If you don't have plans to document something about it, I think this issue could be closed.

Thanks.
