### ISSUE TITLE
rest url rule generate wrong schema

### ISSUE THREAD

**Issue by tumdav** [yiisoft/yii2#13200]
Url config
```php
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'enableStrictParsing' => false,
    'rules' => [
       [
         'class' => 'yii\rest\UrlRule',
         'controller' => ['v1/channel']
       ]
   ]
```
Endpoint
```
domain.com/app-name/frontend/web/index.php/v1/channels
```

Generated endpoint
```
"_links": {
      "self": {
         "href": "domain.com/app-name/frontend/web/v1/channel?offset=1"
      }
    }
```

Yii version |  2.0.9

**Comment by cebe** [comment]
what exactly is wrong? note that `'showScriptName' => false` does not match the URL you have given above.

**Comment by tumdav** [comment]
@cebe  I  use pluralize schema **/channels**, but generated url isn't pluralize **/channel**

**Comment by cebe** [comment]
I am unable to reproduce this issue. I have created a unit test to verify the behavior of yii\rest\UrlRule with your parameters.

**Comment by tumdav** [comment]
It's caused, when I use extra patterns.

Config example

```
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'enableStrictParsing' => false,
    'rules' => [
       [
         'class' => 'yii\rest\UrlRule',
         'controller' => ['v1/channel'],
           'extraPatterns' => [
            'my' => 'my' 
         ]
       ]
   ]
```

Request url in index action
```
domain.com/v1/channels
```
Generated url
```
  "_links": {
      "self": {
        "href": "domain.com/v1/channels?offset=1"
      }
    },
```
__________________________________
Request url in custom action
```
domain.com/v1/channels/my
```
Generated url
```
  "_links": {
      "self": {
        "href": "domain.com/v1/channel/my?offset=1"
      }
    },
```

**Comment by cebe** [comment]
Reproduced, if you explicitly state a HTTP verb in the extra pattern it should work: `'GET my' => 'my' `.

**Comment by cebe** [comment]
Fixed. Thanks for reporting!
