### ISSUE TITLE
Yii2 broken after composer update

### ISSUE THREAD

**Issue by pkarczmarczyk94** [yiisoft/yii2#13205]
### What steps will reproduce the problem?
composer update
I am using Yii2 and AngularJS.

After doing composer update I am getting this error in my apache logs: 
`Uncaught Error: Call to undefined method yii\\helpers\\ArrayHelper::filter() in private/vendor/yiisoft/yii2/log/Target.php:136`

I am getting 500 errors and good data from yii to angular.
Before composer update everything works perfectly.
I've got installed "fxp/composer-asset-plugin" in my composer.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.14
| Operating system | Ubuntu/Apache

**Comment by Sammaye** [comment]
Are you sure the composer updated correctly? I can see the function right here https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L842 and by a quick browse of history on the fle it seems it was never accidently removed in a version.

It sounds like you maybe got a partial download or something.

**Comment by pkarczmarczyk94** [comment]
Yea, I've got it too and that's the weirdest thing... I've copied this function to Targed and invoked it as self and everything worked fine, then I've changed filter to index - just for tests - and no errors again...

**Comment by Sammaye** [comment]
Ah, this is very weird

**Comment by pkarczmarczyk94** [comment]
I,ve tried to reinstall composer using this:
`curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
composer global require "fxp/composer-asset-plugin"`

maybe that's the problem...

**Comment by Sammaye** [comment]
Looks good to me, if composer was the problem it would all be broken. Is the visibility of the function public for you?

**Comment by pkarczmarczyk94** [comment]
It's public static

**Comment by Sammaye** [comment]
Hmm, this is officially very weird

**Comment by pkarczmarczyk94** [comment]
I can give you whole backtrace from error if it helps

**Comment by Sammaye** [comment]
Yeah, that will help anyone else too

**Comment by Sammaye** [comment]
I was going to say it was maybe autoloading but if you can use the index function that's no the case either

**Comment by pkarczmarczyk94** [comment]
`PHP Fatal error:  Uncaught Error: Call to undefined method yii\\helpers\\ArrayHelper::filter() in /home/public_html/user/private/vendor/yiisoft/yii2/log/Target.php:136\nStack trace:\n#0 
/home/public_html/user/private/vendor/yiisoft/yii2/log/Target.php(116): yii\\log\\Target->getContextMessage()\n#1
 /home/public_html/user/private/vendor/yiisoft/yii2/log/Dispatcher.php(188): yii\\log\\Target->collect(Array, true)\n#2
 /home/public_html/user/private/vendor/yiisoft/yii2/log/Logger.php(173): yii\\log\\Dispatcher->dispatch(Array, true)\n#3

[internal function]: yii\\log\\Logger->flush(true)\n#4 
{main}\n  thrown in /home/public_html/user/private/vendor/yiisoft/yii2/log/Target.php on line 136`

**Comment by pkarczmarczyk94** [comment]
I thought about autoloader too, but index function doesn't throw error

**Comment by Sammaye** [comment]
Hmm, right now I am ready to look at PHP itself. Are you using Apache fork or cgi?

**Comment by pkarczmarczyk94** [comment]
apache and php 7.0.14

**Comment by Sammaye** [comment]
But is Apache using the default forking method or did you alter it use fcgi?

**Comment by pkarczmarczyk94** [comment]
I need to ask our admin, sorry i don't know, i though you are asking what kind of server I'm using... my bad. As soon as I get info I'll send it here

**Comment by Sammaye** [comment]
Tell him to restart apache and any PHP processes that might be running as well

**Comment by pkarczmarczyk94** [comment]
Ok, I'll tell him. In  the mean time I've tried to use this function in one of my controllers with same result... Call to undefined function...

**Comment by pkarczmarczyk94** [comment]
I've found file `php7.0-fpm.conf` in apache folder 
`
<IfModule !mod_php7.c\>

    <IfModule proxy_fcgi_module\>

        <IfModule setenvif_module\>
        SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
        </IfModule\>

        <FilesMatch ".+\.ph(p[3457]?|t|tml)$"\>
            SetHandler "proxy:unix:/run/php/php7.0-fpm.sock|fcgi://localhost"
        </FilesMatch\>
        <FilesMatch ".+\.phps$"\>
            Require all denied
        </FilesMatch\>
        <FilesMatch "^\.ph(p[3457]?|t|tml|ps)$"\>
            Require all denied
        </FilesMatch\>
        
    </IfModule\>

</IfModule\>
`
But I really don't know if it's good file

**Comment by Sammaye** [comment]
Aha, try running `sudo service php7.0-fpm restart` and see if that clear the PHP cache

**Comment by pkarczmarczyk94** [comment]
still nothing

**Comment by Sammaye** [comment]
Damn :( hmm

**Comment by samdark** [comment]
That looks like a local issue with cache or something. Since we have the method in the source, it's not framework issue we can fix. Closing the issue. Feel free to post about fixing it if you'll find a way.

**Comment by pkarczmarczyk94** [comment]
Ok, I've found solution class was overwritten by someone and it was loaded from other file... Tanks for help;)
