### ISSUE TITLE
Database exception using DbSession

### ISSUE THREAD

**Issue by puku** [yiisoft/yii2#13212]
### What steps will reproduce the problem?
When I'm trying to login on the website, from time to time I'm receiving an error message.
After reloading of the page everything is ok.
`YII_DEBUG `is enabled, `YII_ENV_DEV` is set to true.

Maybe this issue is linked with [this one](https://github.com/yiisoft/yii2/pull/1812)

[Stackoverflow question](http://stackoverflow.com/questions/41158812/yii2-dbsession-exception)
### What do you get instead?

> Integrity constraint violation – yii\db\IntegrityException
> 
> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
> The SQL being executed was: UPDATE `session` SET `id`=0 WHERE `id`='3u5r7gq6pqh8s0gjrusfqpmni7'
> Error Info: Array
> (
>     [0] => 23000
>     [1] => 1062
>     [2] => Duplicate entry '0' for key 'PRIMARY'
> )
> ↵
> Caused by: PDOException
> 
> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
> 
> in /var/www/develop/vendor/yiisoft/yii2/db/Command.php at line 844

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0
| Operating system | Ubuntu 14.04

**Comment by bizley** [comment]
I think `DbSession` should check if [$newID](https://github.com/yiisoft/yii2/blob/master/framework/web/DbSession.php#L104) is properly set before trying to [update DB with it](https://github.com/yiisoft/yii2/blob/master/framework/web/DbSession.php#L114).

**Comment by dynasource** [comment]
looks like it. If session_regenerate_id fails to generate an ID, its no use to update the DB with it.

**Comment by bizley** [comment]
Should the old session row be deleted in case the new ID can not be generated? For something like to prevent loosing the old data in race condition case?

I've tested `DbSession` simulating loosing ID and deleting session row in that case - everything looks ok.

**Comment by yanhuixie** [comment]
Same issue with Redis session implementation.
session_regenerate_id(): Session object destruction failed. ID: user (path: )
/vendor/yiisoft/yii2/web/Session.php L282
Yii2 2.0.10

**Comment by andrewnester** [comment]
@bizley I guess there is no need to delete session row. `session_regenerate_id` could fail, for instance, because of network issues and when will be ran second time it will return valid ID.

**Comment by andrewnester** [comment]
@yanhuixie it's a bit different, `DbSession::regenerateID` doesn't ask `session_regenerate_id` for session destruction

**Comment by bizley** [comment]
@andrewnester can you confirm that old row is deleted or updated later on? Because if not there is the risk of DB storage overfill.

**Comment by andrewnester** [comment]
@yanhuixie thanks for reasonable question! In this case `DbSession:: gcSession` will handle all expired data

**Comment by puku** [comment]
I still have issue with it. The problem is that 

> Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `session` (`data`, `id`, `expire`) VALUES ('', 1, 1499947188) in /var/www/release/vendor/yiisoft/yii2/db/Schema.php:636

> Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'PRIMARY'
The SQL being executed was: UPDATE `session` SET `id`=5 WHERE `id`='1v0dqepld1pk9eqn3rp0ckpsfc' in /var/www/release/vendor/yiisoft/yii2/db/Schema.php:636

One of the solution is to check if there is any duplicates in the database, before inserting or updating db. But I'm not sure this solution is the correct ones.

**Comment by ddinchev** [comment]
I would like to reopen this issue as I now (after 2.0.13 upgrade) get a lot of errors like this. I've proposed a PR.

**Comment by sergeymakinen** [comment]
ATM the only proper way to fix it (IMO) is #13879.

**Comment by rob006** [comment]
We can catch exception and retry?

**Comment by samdark** [comment]
Yes, we can but it's like a hotfix. Proper solution is #13879

**Comment by rob006** [comment]
Implementation of upsert looks really complicated to me, it probably will be source of new bugs and may make situation even worse. I prefer use this hotfix in patch release and switch to upsert in 2.0.14.

**Comment by samdark** [comment]
Makes sense. Let's do try-catch for 2.0.13.1 and replace implementation with upsert when it's ready. Would you help with a pull request?

**Comment by sergeymakinen** [comment]
Yes, a hotfix in 2.0.13.1 sounds reasonable.
For example it took a whole day to make PostgreSQL (pre 9.5, since 9.5 it's as easy as ABC) QB produce this (it's correct and handles lots of DMBS specifics):
```sql
WITH
        "EXCLUDED" ("email", "name", "address", "bool_status", "profile_id") AS (VALUES (:qp0, :qp1, :qp2, :qp3, CAST(NULL AS int4))),
        "upsert" AS (UPDATE "customer" SET "email"="EXCLUDED"."email", "name"="EXCLUDED"."name", "address"="EXCLUDED"."address", "bool_status"="EXCLUDED"."bool_status", "profile_id"="EXCLUDED"."profile_id" FROM "EXCLUDED" WHERE (("customer"."email"="EXCLUDED"."email")) RETURNING "customer".*)
INSERT INTO "customer" ("email", "name", "address", "bool_status", "profile_id") SELECT "email", "name", "address", "bool_status", "profile_id" FROM "EXCLUDED" WHERE NOT EXISTS (SELECT 1 FROM "upsert" WHERE (("upsert"."email"="EXCLUDED"."email")))
```

So it will definitely require testing (in addition to unit tests).

**Comment by samdark** [comment]
Wow, ↑ isn't how it is usually done.

**Comment by ddinchev** [comment]
I thought about resubmitting an MR with try/catch and ignore if there is a duplicate key. There is no need to retry when we've hit the race condition as session data has just been saved.

However, I'm not sure how to verify it's a duplicate key in DBMS-independent way. For MySQL the PDO error code is 1062 but I couldn't find the ones for MSSQL, Postgres and SQLite.

**Comment by samdark** [comment]
@sergeymakinen https://github.com/symfony/symfony/pull/10652/files may give you some hints (related problem).

**Comment by sergeymakinen** [comment]
@samdark It was 04 or 05 am and I was not clear. :) The code was for a generic upsert implementation where `REPLACE` is not a replacement.

**Comment by sergeymakinen** [comment]
@samdark While the sample code is pretty logical when working with sessions. But did they miss pgsql? I would wonder why. 👹

**Comment by samdark** [comment]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php — here's latest version.

**Comment by samdark** [comment]
Tests are quite interesting as well: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/PdoSessionHandlerTest.php

**Comment by sergeymakinen** [comment]
This means that the hardest part (pgsql <9.5) is done. Other implementations are trivial. MySQL’s and MSSQL’s upserts are also completed.

**Comment by cebe** [comment]
> Duplicate entry '1' for key 'PRIMARY'

your sessionid is 1?

**Comment by samdark** [comment]
Oh. Original exception is even "better" ID is 0

**o_0**

**Comment by ddinchev** [comment]
@samdark if there is no progress on this, I can try to pick it and create an MR based on Symphony's solution.

**Comment by samdark** [comment]
@sergeymakinen is trying hard to finish upserts support.

**Comment by puku** [comment]
Sorry, for confusions, I've found out that my problem was linked with incorrect type of Mysql field `id` in the table `session`.

**Comment by samdark** [comment]
@puku thanks for letting us know. We still want upserts for sessions though so I'm leaving it open for now.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/issues/11401
