### ISSUE TITLE
ENH: Ability to not shuffle masters connection

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#13219]
> The `Connection` component also supports load balancing and failover between masters just as it does between slaves.
>
>> The `Connection` component supports load balancing and failover between slaves. When performing a read query for the first time, the `Connection` component will **randomly** pick a slave and try connecting to it. If the slave is found "dead", it will try another one.

Please, add ability to disable shuffling of masters, so they will be tried in the defined order.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by SilverFire** [comment]
@Vovan-VE would you like to submit a PR?

**Comment by Vovan-VE** [comment]
Merged into 2.0.11.
