### ISSUE TITLE
Method \yii\db\QueryTrait::limit accept only integes, not expressions

### ISSUE THREAD

**Issue by Ni-san** [yiisoft/yii2#13221]
### What steps will reproduce the problem?
I going to create query like this `Order::find()->limit(new Expression('1 + (random() * 9) :: INT'))->all()`

### What is the expected result?
Expecting `SELECT * FROM "order"."order" LIMIT (random() * 9) :: INT` (postgresql)

### What do you get instead?
Method \yii\db\QueryBuilder::buildLimit ignore my limit value, cause it's not numeric (check using ctype_digit).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.14
| Operating system | *nix

**Comment by SilverFire** [comment]
@Ni-san would you like to submit a PR?
