### ISSUE TITLE
Migrations Bug in Postgres

### ISSUE THREAD

**Issue by dersonsena** [yiisoft/yii2#13229]
Hello everyone! I am using migrations with a Postgres database and found a bug. This is my database connection configuration file:
```php
'db' => [
    'class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=xxx;dbname=xxx',
    'username' => 'xxx',
    'password' => 'xxx',
    'charset' => 'utf8',
    'tablePrefix' => 'TBL_',
    'attributes' => [
        PDO::ATTR_CASE => PDO::CASE_UPPER
    ],
]
```

And below my migration file. You will see that there are two simple SQL statements for changing columns:
```php
public function safeUp()
{
    $this->alterColumn('{{%GRU}}', 'GRU_DES', $this->string(64));
    $this->alterColumn('{{%GRU}}', 'GRU_OBS', $this->text());
}
```

When you run the migration, the console returns the following error:
```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: is_nullable' in /<projectDirectory>/vendor/yiisoft/yii2/db/pgsql/Schema.php:497
```

By debugging the ``yiisoft/yii2/db/pgsql/Schema.php`` file on line 497, I noticed that the array indices sent per parameter are **all in uppercase**. Being that in the body of the method are being used **in lowercase**

```php
// yiisoft/yii2/db/pgsql/Schema.php

protected function loadColumnSchema($info)
{
    $column = $this->createColumnSchema();
    $column->allowNull = $info['is_nullable'];
    $column->autoIncrement = $info['is_autoinc'];
    $column->comment = $info['column_comment'];
    $column->dbType = $info['data_type'];
    ....
    ....
    ....
```

This is the value coming from the ``$info`` of the ``loadColumnSchema``:
```php
Array
(
    [TABLE_SCHEMA] => public
    [TABLE_NAME] => TAB_migration
    [COLUMN_NAME] => version
    [DATA_TYPE] => varchar
    [CHARACTER_MAXIMUM_LENGTH] => -1
    [COLUMN_COMMENT] => 
    [MODIFIER] => 184
    [IS_NULLABLE] => 
    [COLUMN_DEFAULT] => 
    [IS_AUTOINC] => 
    [ENUM_VALUES] => 
    [NUMERIC_PRECISION] => 
    [NUMERIC_SCALE] => 
    [SIZE] => 180
    [IS_PKEY] => 1
)
```

I thought about doing a PR, but I preferred to create an issue to better document the problem.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 7.0.14
| Operating system | MacOS

**Comment by dersonsena** [comment]
@samdark  would not it be better to put this issue inside a **bug** or something related? Although the correction of this problem is simple, at first glance it can be categorized as a bug.

**Comment by klimov-paul** [comment]
It is questionable, if this issue is a bug, since it is causes by your actions with setting PDO attribute:

```
PDO::ATTR_CASE => PDO::CASE_UPPER
```

**Comment by klimov-paul** [comment]
I am not even sure, if fixing `Schema::loadColumnSchema()` will end the problems.
See #9457 for example.

**Comment by klimov-paul** [comment]
Resolved by commit 8f5f54045593be0af4d0595d4bbbf0034f993882

**Comment by dersonsena** [comment]
Thank you very much @klimov-paul !! I saw that I had been implemented this fix for MySQL, Oracle ... however, for PostgreSQL not. Thank you! :)

**Comment by dersonsena** [comment]
@klimov-paul Following the same reasoning as in the example above, in the `findConstraints($table)` method you must also add this check:
```php
...
foreach ($this->db->createCommand($sql)->queryAll() as $constraint) {
    if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_UPPER)
        $constraint = array_change_key_case($constraint, CASE_LOWER);
...
```

**Comment by klimov-paul** [comment]
0a978f9d1e7365b44761ad67de223d977d8f03c4

**Comment by dersonsena** [comment]
Nice @klimov-paul ! If I see anything else related to it, put it here! =D

**Comment by dersonsena** [comment]
@klimov-paul Hi! Another case where it should be treated. In the `findTableNames($schema = '')` method:

```php
...
foreach ($rows as $row) {
    if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_UPPER)
        $row = array_change_key_case($row, CASE_LOWER);

    $names[] = $row['table_name'];
}
...
```

**Comment by klimov-paul** [comment]
It is already covered.

**Comment by dersonsena** [comment]
Oops .... sorry! I had not seen. Thanks @klimov-paul
