### ISSUE TITLE
Unexpected behavior for clearing cache with ApcCache 

### ISSUE THREAD

**Issue by alexxxst** [yiisoft/yii2#13224]
### What steps will reproduce the problem?

Use "yii\caching\ApcCache" for application (web and console) cacher (APC or APCu).
Use your web-app to put something in cache.
Try to flush cache from console-app.
Check your web-app for cache data exists. It exists.

### What is the expected result?

Expected clear cache, like "yii\caching\FileCache", but I can't flush fastcgi APC(u) cache from a php cli script (console-app) since the cli script will run from a different process as fastcgi.

### What do you get instead?

Probably some way to run cache flush via web-app from console-app?
Any ideas?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.14 etc.
| Operating system | Linux / MacOS

**Comment by rob006** [comment]
Duplicates #10503

**Comment by rob006** [comment]
@samdark Maybe `CacheController` should display some notice when user tries flush `ApcCache`?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/13226
