### ISSUE TITLE
Why need in lastModified - $params ? And how can I get a variable from the GET request?

### ISSUE THREAD

**Issue by semiromid** [yiisoft/yii2#13222]
Why need in lastModified - $params ? $params returns NULL even when i send GET request with params.   And how can I get a variable from the GET request in anonymous function for last Modified?

I can do so (get params form GET request) - How i can params form GET request in  YII2?:
$a2 = $_GET['number'];

```
public function behaviors()
{
    return [
        [
            'class' => 'yii\filters\HttpCache',
            'only' => ['index'],
            'lastModified' => function ($action, $params) {
                $q = new \yii\db\Query();
                return $q->from('post')->max('updated_at');
            },
        ],
    ];
}
```

| Q                | A
| ---------------- | ---
| Yii version     2.0. ? |  Yes, This is Yii version 2.0.8.
| PHP version      | 5.6
| Operating system  | windows 8 and Linux last

**Comment by Alex-Code** [comment]
Please use the forums for questions, http://www.yiiframework.com/forum/index.php/forum/42-general-discussions/

If you're unsure first refer to the documentation as it may have the answer, http://www.yiiframework.com/doc-2.0/yii-filters-httpcache.html#$params-detail

Get the param `number`
`\Yii::$app->request->get('number')`

**Comment by semiromid** [comment]
Ok. I am sorry.
