### ISSUE TITLE
DetailView & cyrillic attribute names

### ISSUE THREAD

**Issue by bsyomov** [yiisoft/yii2#13243]
### What steps will reproduce the problem?
put Cyrillic attribute name(s) in attribute filed
I have model built on 1С oData API, so field names are mixture of russian and english languages. =|
### What do you get instead?
 InvalidConfigException('The attribute must be specified in the format of "attribute", "attribute:format" or "attribute:format:label"')

### Additional info
Seems like this regexp needs /u modifier:
  if (!preg_match('/^([\w\.]+)(:(\w*))?(:(.*))?$/', $attribute, $matches))
                  

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.27
| Operating system | Debian 7

**Comment by SilverFire** [comment]
@yiisoft/core-developers I think the same was discussed earlier, but I can not find that issue.

**Comment by samdark** [comment]
It was partially fixed but since original reporter said it is not needed anymore, it was not finished. 

@bsyomov it is not a priority for us since such schemas are not common. If you want it fixed you have to send us a pull request containing a fix and unulit tests verifying it.

**Comment by bsyomov** [comment]
Sorry, but I do not have to waste time on studying creating a pull request for now.

if (!preg_match('/^([\w.]+)(:(\w*))?(:(.*))?$/', $attribute, $matches))
if (!preg_match('/^([\w.]+)(:(\w*))?(:(.*))?$/u', $attribute, $matches)) 
works for me. 
And it's not so critical at all, i can just use ['label','value'] notation instead.
But using non-english names in oData, SOAP etc. not so rare.
