### ISSUE TITLE
Composer dependency problem

### ISSUE THREAD

**Issue by inacho** [yiisoft/yii2#13247]
I can't execute `composer update` or `composer install` because Yii2 depends on "bower-asset/jquery", which not longer exists (https://github.com/bower-asset/jquery)

Any solution?
Thanks

# Wokraround: https://github.com/yiisoft/yii2/issues/13247#issuecomment-267952064

**Comment by nadar** [comment]
https://github.com/fxpio/composer-asset-plugin/issues/268

> After removing my Composer caches, I confirm that the problem comes from Packagist. Composer downloads a list of repository providers in COMPOSER_HOME/repo/https---packagist.org/provider-bower-asset$jquery.json (for jquery).

> The problem comes with the virtual packages referenced by many packages with provide and replace section.

**Comment by hartmantam** [comment]
`bower-asset` is totally down, no repo inside
![Prove](https://cloud.githubusercontent.com/assets/8369976/21312567/a5f01276-c5a1-11e6-836e-4320f3ce9152.png)

**Comment by SilverFire** [comment]
### For those who faced this problem - try [https://asset-packagist.org](https://goo.gl/9QFEvt) as an alternative.

**Comment by klimov-paul** [comment]
Relates https://github.com/fxpio/composer-asset-plugin/issues/268

**Comment by mrSerg161** [comment]
@SilverFire 
![12334423](https://cloud.githubusercontent.com/assets/12622963/21313656/2701f714-c604-11e6-8016-f7e9d81e3f39.JPG)
composer install is ok, but yii not found jquery

**Comment by alxark** [comment]
If your facing this problem: 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing bower-asset/jquery (1.12.4)
    Downloading: Failed
    Failed to download bower-asset/jquery from dist: The "https://api.github.com/repos/bower-asset/jquery/zipball/a76fe112f860279382d9f6336fe040fd8f8aa13d" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing bower-asset/jquery (1.12.4)
    Cloning a76fe112f860279382d9f6336fe040fd8f8aa13d


  [RuntimeException]
  Failed to clone https://github.com/bower-asset/jquery.git via https, ssh, git protocols, aborting.
  - https://github.com/bower-asset/jquery.git
    Cloning into '/private/var/www/backend/app/vendor/bower-asset/jquery'...
    remote: Repository not found.
    fatal:***@github.com/bower-asset/jquery.git/' not found
  - git@github.com:bower-asset/jquery.git
    Cloning into '/private/var/www/backend/app/vendor/bower-asset/jquery'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
  - git://github.com/bower-asset/jquery.git
    Cloning into '/private/var/www/backend/app/vendor/bower-asset/jquery'...
    fatal: remote error:
      Repository not found.

```

to fix this situation you can add this to your composer.json

 ```
"repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
```

**Comment by bizley** [comment]
asset-packagist does not respect `"bower-asset-library": "vendor/bower"` setting probably. Now `@bower` alias points to `vendor/bower` and asset-packagist puts bower packages in `bower-asset` folder.

**Comment by hartmantam** [comment]
@mrSerg161 paste the following content to `web.php`

```
$config = [
        ...
        'aliases' => [
            '@bower' => '@vendor/bower-asset',
            '@npm'   => '@vendor/npm-asset',
        ],
        ...
    ];
```

**Comment by SilverFire** [comment]
@bizley that's right.

@hartmantam thank you for a right snippet.

**Comment by SilverFire** [comment]
@Seldaek is is possible to drop those package from Packagist.org?

**Comment by SilverFire** [comment]
Related: https://github.com/composer/packagist/issues/756

**Comment by lan143** [comment]
@hartmantam after composer install we have 2 bower folders. Is change alias, another packages not found
![index](https://cloud.githubusercontent.com/assets/98252/21314441/30ccff2e-c608-11e6-8e06-50a7a1842892.png)

**Comment by SilverFire** [comment]
@lan143 forget about `vendor/bower` and `vendor/npm` dirs

**Comment by lan143** [comment]
@SilverFire Im remove vendor folder before composer install.

**Comment by cebe** [comment]
here is a simple workaround that does not include asset-packagist: https://github.com/fxpio/composer-asset-plugin/issues/268#issuecomment-267964486

**Comment by AprSoft** [comment]
https://asset-packagist.org/site/about look this.

**Comment by hartmantam** [comment]
@lan143 I didn't encountor this issue tho... and i don't have a `bower` folder in the `vendor` folder. but you can try to move `jquery` and `yii2-pjax` in `bower` to `bower-asset`, it may solve the problem
![bower-asset folder structure](https://cloud.githubusercontent.com/assets/8369976/21315635/f9c8ba1e-c5b1-11e6-85bc-8546cffc7171.PNG)

**Comment by SilverFire** [comment]
https://github.com/fxpio/composer-asset-plugin/issues/268#issuecomment-267976882

**Comment by Charius** [comment]
well https://github.com/bower-asset/jquery.inputmask.git is 404 now

**Comment by nkostadinov** [comment]
I still have problem updating via composer 

```
 - Installing bower-asset/jquery.inputmask (3.3.3)
    Downloading: Failed
    Failed to download bower-asset/jquery.inputmask from dist: The "https://api.github.com/repos/bower-asset/jquery.inputmask/zipball/a92cb06b4fe5788ebe7e45e56842c6141632b3ab" file could not be downloaded (HTTP/1.1 404 Not Found)
```

I cannot find a working solution to this problem though the issue is closed

**Comment by Charius** [comment]
use asset-packagist.org

**Comment by nkostadinov** [comment]
@Charius I can switch to asset-packagist, but is this the final solution ? I thought it was just a temporary workaround.

**Comment by Charius** [comment]
@nkostadinov I guess it's not final solution, otherwise all the issues related with this in other projects are closed, so, there is other option

**Comment by SilverFire** [comment]
Asset-packagist is not a temporary solution. It's a full alternative to `fxp/composer-asset-plugin`, you are free to choose. We are going to add a guide article about it soon: https://github.com/yiisoft/yii2/issues/13064

**Comment by rob006** [comment]
>  It's a *full* alternative to fxp/composer-asset-plugin

No, it's not. It still doesn't have some features (and never will) that `composer-asset-plugin` have: https://github.com/yiisoft/yii2/issues/8688#issuecomment-240085100

**Comment by nkostadinov** [comment]
Well it is not compliant with the current solution. I have my composer packages with their bower dependencies and they do not work. It keeps installing them in vendor/bower. So now I have 60% installed in vendor/bower-asset and other 40% installed in vendor/bower. Does anyone know a fix for this ?

**Comment by SilverFire** [comment]
@rob006 it's a full alternative for a general usage scenario. You are right, it does not cover some special cases described via the link you've provided.

> Does anyone know a fix for this ?

Most probably https://asset-packagist.org does not know some of your required bower packages.

1. Remove `fxp/composer-asset-plugin` from your global composer
2. Run `composer update` in your project
3. Most probably you will see an error that some of your requirements can not be satisfied.
4. Copy the missing bower-asset/package name and submit it to https://asset-packagist.org
5. Run `composer update` again. Repeat 3-5 until all your bower-requirements are submitted

We've already imported top-1500 of npm and bower packages, but we are considering about importing more.

**Comment by nkostadinov** [comment]
Aha, I didn't know I have to SUBMIT the packages - that's important information. I thought that that asset-packagist.org did that automatically upon request from composer so you don't have to manually enter each.
