### ISSUE TITLE
session setFlash can't work when happend \yii\db\IntegrityException

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#13251]
- PHP version 7.0.10
- YII version 2.0.10
- OS: Windows 10
- Session Handler : yii\web\DbSession

This is my code :
~~~php
    public function actionDelete($id) {
        try{
            $this->findModel($id)->delete();
            Yii::$app->session->setFlash('success' , 'Delete ok。');
            return $this->redirect(['index']);
        } catch (\yii\db\IntegrityException $e) {
            Yii::$app->session->setFlash('error' , 'Delete error。');
        }
        return $this->redirect(['view' , 'id' => $id]);
    }
~~~

if delete success , the "success flash message" will be render in action "index"
if delete happend exception , the "error flash message" will not be render in 'view' action.

but when I add two line 
~~~php
    public function actionDelete($id) {
       // add two line here
        Yii::$app->session->setFlash('error' , 'Delete error。');
        return $this->redirect(['view' , 'id' => $id]);
        try{
            $this->findModel($id)->delete();
            Yii::$app->session->setFlash('success' , 'Delete ok。');
            return $this->redirect(['index']);
        } catch (\yii\db\IntegrityException $e) {
            Yii::$app->session->setFlash('error' , 'Delete error。');
        }
        return $this->redirect(['view' , 'id' => $id]);
    }
~~~

the error flash message be rendered ...... why ? :(

**Comment by pigochu** [comment]
my quick fix , close db connection then setFlash ..... it works
~~~php
    public function actionDelete($id) {
        try{
            $this->findModel($id)->delete();
            Yii::$app->session->setFlash('success' , 'Delete ok。');
            return $this->redirect(['index']);
        } catch (\yii\db\IntegrityException $e) {
            Yii::$app->db->close(); // fix here
            Yii::$app->session->setFlash('error' , 'Delete error。');
        }
        return $this->redirect(['view' , 'id' => $id]);
    }
~~~

**Comment by SilverFire** [comment]
Which DBMS do you use for sessions?

**Comment by pigochu** [comment]
@SilverFire 

mariadb 10.1.12

**Comment by SilverFire** [comment]
Ok, we will check this issue after releasing 2.0.11 version

**Comment by dynasource** [comment]
Am I interpreting the quick fix right?:
*  "The flash set to DbSession only works after the DB has been closed."

**Comment by SilverFire** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [session setFlash can't work when happend \yii\db\IntegrityException](https://trello.com/c/0OyArYgg/7-session-setflash-can-t-work-when-happend-yii-db-integrityexception)

**Comment by pigochu** [comment]
@dynasource 

You can see my code,
it can work in "try" section,but can't work in "catch" section.
If $this->findModel($id)->delete() has exception , setflash  can't work.

**Comment by rob006** [comment]
@pigochu Do you use any transactions in your model?

**Comment by pigochu** [comment]
@rob006 
sorry....
I forgot I have a transaction ...
when I rollback transaction , it can setFlash now.
