### ISSUE TITLE
Confirm dialog on submit button is fired twice, If the button is placed in the form

### ISSUE THREAD

**Issue by MatthewPattell** [yiisoft/yii2#13255]
### What steps will reproduce the problem?

I created active form:

```
ActiveForm::begin([
    'validateOnBlur'        => false,
    'validateOnChange'      => false,
    'enableAjaxValidation'  => false,
    'enableClientValidation'=> false,
    'options' => [
        'id' => 'emails',
        'data' => [
            'pjax' => 1
        ],
        'enctype' => 'multipart/form-data'
    ],
    'action' => ['update', 'id' => $model->id]
]) ?>
```
...some fields...
```
Html::a(Yii::t('app', 'Delete Message'), ['delete-email', 'id' => $model->id], [
    'class' => 'btn btn-primary',
    'data' => [
        'confirm' => 'Are you sure want to delete this message?',
        'method' => 'post',
    ]
]);
```
...some fields...
```
<? ActiveForm::end(); ?>
```

Simplified:
```
<? ActiveForm::begin([]) ?>

<?= Html::a('Delete', ['delete-email', 'id' => $model->id], [
    'class' => 'btn btn-primary',
    'data' => [
        'confirm' => 'Are you sure want to delete this message?',
        'method' => 'post',
    ]
]); ?>

<? ActiveForm::end(); ?>
```
### What is the expected result?
Should see a dialog box with the question.

### What do you get instead?
Two dialog appear one after another.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0
| Operating system | Windows 10

![screenshot_2](https://cloud.githubusercontent.com/assets/10459911/21348032/57579398-c6bc-11e6-8ab3-3144d42e7714.png)

Similar problem:
[https://github.com/yiisoft/yii2/issues/6642](https://github.com/yiisoft/yii2/issues/6642)

**Comment by arogachev** [comment]
I think it's better to wait when the tests for `yii.activeForm.js` will be written to prevent breaking of something else. I can handle this later.

**Comment by TrueZurg** [comment]
Hello!
I have the same issue after updating yii2 to 2.0.10.
Found, that the problem is in `yii.activeForm.js` and in this line `data.submitObject.trigger("click");`
```
var updateInputs = function ($form, messages, submitting) {
...
data.validated = true;
if (data.submitObject) {
    data.submitObject.trigger("click");
} else {
    $form.submit();
}
...
```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/13357

**Comment by SilverFire** [comment]
I can reproduce the issue on 2.0.10, but current master branch seems to work correctly.

@MatthewPattell @TrueZurg @dhimancontact @yupe @alemedinam @bariew could you try your code on master branch? To do it, run `composer require "yiisoft/yii2:dev-master"`

**Comment by et-soft** [comment]
I'm have similar bug. After update yii to "dev-master", confirm dialog became shown 1 times. Thank you!

**Comment by samdark** [comment]
Then it seems the issue is solved.

**Comment by tonny-sofijan** [comment]
@samdark when will the fix incorporated to stable release? I prefer using stable branch than dev-master. Thanks.

**Comment by SilverFire** [comment]
We are going to release 2.0.11 in a week or two

**Comment by TrueZurg** [comment]
Yii version 2.0.11.2 - problem is still here.

**Comment by samdark** [comment]
@TrueZurg, same problem? Is info in the ticket enough to reliably reproduce it?

**Comment by TrueZurg** [comment]
@samdark yes.
Inside ActiveForm I have tag "a" with data-confirn. And if some field has not valid value there will be no successful confirmation. I wrote about it early here.

I've tried 2.0.12 yet.

**Comment by samdark** [comment]
Please try 2.0.12.

**Comment by TrueZurg** [comment]
@samdark tried 2.0.12. Now data-confrim not works at all with a tag. There will be redirect to a tag url regardles confirm!

**Comment by TrueZurg** [comment]
@samdark tried 2.0.12 The same effect!

**Comment by samdark** [comment]
@TrueZurg I've re-checked with code from master and the following snippet:

```php
<? ActiveForm::begin([]) ?>

<?= Html::a('Delete', ['delete-email', 'id' => 'test'], [
    'class' => 'btn btn-primary',
    'data' => [
        'confirm' => 'Are you sure want to delete this message?',
        'method' => 'post',
    ]
]); ?>

<? ActiveForm::end(); ?>
```

Dialogue appears once.

**Comment by samdark** [comment]
So your issue may be different from what was reported and fixed in this one. If so, please create a new issue with details on how to reproduce it. Thanks.
