### ISSUE TITLE
Deferred validation hitting multiple times

### ISSUE THREAD

**Issue by jhon100** [yiisoft/yii2#13261]
In many of my models I've a 'disabled' field, I need to validate if the record being disabled can be disabled (cheking if the record is referenced from some table in database).
As I've a "SuperController" from all my controllers inherits, I want to put the validation logic in this "SuperController" so it can be implemented once. 
For this I'm registering a javascript code in my actionUpdate in "SuperController" and inside of this javascript I make an ajax request to "/current-controller-can-disable/";

This is my test code.
```js
$('#tipos-de-relacionamentos-form').on('beforeValidate', function (event, messages, deferreds) {
    if($('#tiposderelacionamentos-desabilitado').prop('checked')){
        deferreds.add(function(def) {
              $.post("<?= \yii\helpers\Url::to(['can-disable']); ?>")
              .done(function(data) {
                     messages['tiposderelacionamentos-desabilitado'].push('Error message');
                     def.resolve();
            })
        });
  }
    return true;
});

References:
https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md#custom-validation
https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md#deferred-validation-
```

In the form, the 'disabled' is a check box  and I validate it only in update and if it is checked.
The issue is that the validation works fine, the request is made and the form 'waits' the response before submiting.
If I check the checkbox, the validation show an error when the record can not be disabled, but when I uncheck the checkbox and hit submit, it submits the form twice.
In true, if I hit the submit two times with the checkbox checked the form is not submited but when I uncheck the checkbox the form is submited 3 times (and so on), so I think there is an issue with deferred validation.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11-dev
| PHP version      | 5.6.24
| Operating system |Windows 10 ( Xampp )

**Comment by arogachev** [comment]
Currently there are no tests for `yii.activeForm.js`. Hopefully I'll write it soon and such issues will be easier to detect. I will try to verify this issue.

**Comment by jhon100** [comment]
Thank you @arogachev. I'm new to Yii and don't know where to investigate so let me know  if you need more info.

**Comment by jhon100** [comment]
There is nothing wrong with Deferred validation. The issue was in an third party extension that I use for modal cruds:
```js
            // Submit form when user clicks submit button
            $(modalFormSubmitBtn).click(function (e) {
                var data;

                // Test if browser supports FormData which handles uploads
                if (window.FormData) {
                    data = new FormData($(modalForm)[0]);
                } else {
                    // Fallback to serialize
                    data = $(modalForm).serializeArray();
                }
                $(modalForm).data('yiiActiveForm').submitting = true;
                $(modalForm).yiiActiveForm('validate');
                $(modalForm).on('submit', function (e) {
                    e.preventDefault();
                    instance.doRemote(
                        $(modalForm).attr('action'),
                        $(modalForm).hasAttr('method') ? $(modalForm).attr('method') : 'GET',
                        data
                    );
                });
            });
```

As the on('submit'...) is inside a click handler, i changed it to:

```js
           [...]
                $(modalForm).off('submit.modalremote').on('submit.modalremote', function (e) {
           [...]
                });

```
