### ISSUE TITLE
Allow EachValidator to add more than one error

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#13266]
Currently EachValidator will [abort its validation loop](https://github.com/yiisoft/yii2/blob/7a3a342127ed0d4ca5532a4d970f9770ebff77e0/framework/validators/EachValidator.php#L148) as soon as the first item hits a validation error.

Take the following example where we combine 'each' with a 'unique' validator for every item:

    ['user_ids', 'each',
        'rule' => [ 'unique',
            'targetClass' => User::class,
            'targetAttribute' => 'id',
            'skipOnError' => false, // this has no effect on the each validator
        ],
    ],

The 'user_ids' attribute will only know of 1 (the first) record that failed to meet the 'unique' criteria, when in reality there could very well be multiple. The end user has to eliminate one validation error at a time between re-submitting the form. Clearly not ideal. What we want is a list of all user_ids which did not validate as 'unique'.

It would be great if `'skipOnError' => false` inside 'rule' was taken into account and the loop was able to validate all the items in the array in one run.

**Comment by SilverFire** [comment]
@klimov-paul what do you think about this idea?

**Comment by klimov-paul** [comment]
This is questionable: `EachValidator` processes attribute values a a whole entity and thus should provide a solid error message.
Still this behavior can be made optional.

**Comment by klimov-paul** [comment]
Resolved by commit d4ac47abe7ad771946b52b0f89505370ffffae82
