### ISSUE TITLE
the behaviors attach to controllers ? 

### ISSUE THREAD

**Issue by symoo** [yiisoft/yii2#13265]
### What steps will reproduce the problem?
sorry about my poor english.
in the [Definitive guide](http://www.yiiframework.com/doc-2.0/guide-structure-filters.html)
**cors** section it says

> The Cors filter should be defined before Authentication / Authorization filters to make sure the CORS headers will always be sent.

but thing is different when the behavior config array key is string.
in the `Restful Web Services` -> `Authentication` section,
the behaviors function is this.
```
public function behaviors()
{
    $behaviors = parent::behaviors();
    $behaviors['authenticator'] = [
        'class' => CompositeAuth::className(),
        'authMethods' => [
            HttpBasicAuth::className(),
            HttpBearerAuth::className(),
            QueryParamAuth::className(),
        ],
    ];
    return $behaviors;
}
```
and i still need CORS filter, so i added:
```
 public function behaviors()
    {
        $behaviors = parent::behaviors();
        
        $behaviors['corsFilter'] = [
            'class' => Cors::class,
        ];
        $behaviors['authenticator'] = [
            'class'  => HttpBearerAuth::class,
            'except' => ['options'],
        ];

        return $behaviors;
    }
```
problem is when HttpBearerAuth throw a 401 excetion, CORS filter has not been preformed.
so `Access-Control-Allow-Origin` not set in HTTP Header,
 it cause a error in browser with XML HttpRequest.

### What is the expected result?
i find the reason for that is letter "a" is bigger than letter 'c'.
so authenticator run first, and throw exception interrupt the response.
it is design  to do this or just a bug?

### What do you get instead?

i changed the array key, and works well. bu still confused.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version     PHP 7.0.14. |
| Operating system |
MacOS

**Comment by mcariatm** [comment]
@symoo please leave me your solution for this issue
