### ISSUE TITLE
Question: how to get module from components?

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii2#13270]
Dear yii elders and geeks :)

What are good ways to get module from inside of components of the module?
I mean this one obviously isn't:

```php
class MyComponent {
    public function doIt()
    {
        $module = Yii::$app->getModule('my-module');
    }
}
```

Because of spreading `'my-module'` all around the code is not good.
Using a constant like `MyModule::NAME` is not quite enough because it is not flexible.

E.g. for module controllers it's not a problem because of `$module` property populated at request processing.

**Comment by cebe** [comment]
could be done via DI container getSingleton()?

**Comment by klimov-paul** [comment]
Module instance can be obtained using its class name:

```
MyModule::getInstance();
```

If controller is already created it can be obtained via its instance:

```php
$currentModule = Yii::$app->controller->module;
```

Explicit binding for the module inside component will not be supported as it introduces cycle reference.

**Comment by dynasource** [comment]
@hiqsol, regarding your question and your criteria, the cleanest way is to construct the Component during the init() call of the Module and to inject the Module in the Component's $module property. 

This prevents you from having to use the Module alias `my-module` or to use the global Yii scope.
