### ISSUE TITLE
Invalid -- parsing in CLI

### ISSUE THREAD

**Issue by Sartor** [yiisoft/yii2#13277]
### What steps will reproduce the problem?
in bash:
`./yii -- help`
### What is the expected result?
Standart yii2 actions list
### What do you get instead?
`Error: Unknown command "--".`

Following the guides, double minus (--) must be parsed as end of any options. More info:
http://www.gnu.org/prep/standards/standards.html#Command_002dLine-Interfaces
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html (Guideline 10)
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7.0.8
| Operating system | Linux Mint

**Comment by samdark** [comment]
So basically `--` should be ignored in this case, right?

**Comment by Sartor** [comment]
In this case - yes. But after this symbol we must not treat any arguments as options. Problem in my case is than I can't pass any negative number as argument for my yii console comand.

Example:
`./yii task:check users -1`
In this case we have 3 arguments : task:check, users and -1
But now -1 treats as options with name "1"
GNU/POSIX variant is:
`./yii task:check users -- -1`
But it doesn't work

**Comment by cebe** [comment]
negative numbers have been fixed on master already. please try the latest dev version.
