### ISSUE TITLE
FixtureController::$namespace default value does not work for advanced template

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#13272]
### What steps will reproduce the problem?

1. Install yii2 advanced;
2. Create some fixtures in the conventional path `common\fixtures`;
2. Try to load any fixture (`php yii fixture/load "*"`).

### What is the expected result?
Load the fixtures inside `common\fixtures`;

### What do you get instead?

> Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @tests/unit/fixtures'

I have to specify `--namespace=...` option 

An error using a feature of an fresh installation of the Yii doesn't seem a good 'welcome' to a newcomer and, in this case, would require some time to he figure out what is going on since the error message say nothing about `namespace` but `path alias` instead.
 
### Proposed

* Use the common configuration file in advanced to define the default namespace for fixture; Or 
* The default value for `$namespace` could be an array containing both basic and advanced default values. Inside the fw code it could be checked: if array so try/catch paths in the order / if string, just use it.
* Additionally the error message should describe a bit better what caused the error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.1
| Operating system | Mint 18

**Comment by samdark** [comment]
From the proposal, 1st and last points make total sense.

**Comment by samdark** [comment]
Do you have time to work on pull requests for core framework (better exception) and advanced project template (extra config)?

**Comment by slinstj** [comment]
Not much, to be honest, but I can manage it in the next weeks. :+1:

**Comment by samdark** [comment]
Would be perfect. Thanks!

**Comment by SilverFire** [comment]
Thank you!

**Comment by slinstj** [comment]
You are welcome :+1:
