### ISSUE TITLE
Run JS tests in multiple real browsers

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13276]
Extracted from #12936.

See initial suggestion from @nkovacs and further small discussion https://github.com/yiisoft/yii2/pull/12936#issuecomment-259927498.

From one side, this is good to catch IE8 errors such as "class" or "boolean" reserved keywords like in #12722. From the other side it can be extra overhead considering amount and complexity of existing JS code.

**Comment by samdark** [comment]
I don't think we have many issues with browser differences so it doesn't worth to have that in regular builds. Won't mind an ability to run it on a local machine though...

**Comment by schmunk42** [comment]
Here are some examples how to setup [different browsers with Docker](https://github.com/dmstr/phd5-app/blob/master/tests/docker-compose.test.yml#L54-L62) (or IE via modern.ie VM) - https://github.com/dmstr/phd5-app/blob/master/tests/codeception/e2e.suite.yml

You can view the [browsers via VNC](https://github.com/dmstr/phd5-app/blob/master/tests/Makefile#L20-L21) and also run coverage for e2e tests.

Let me know if you need more input on this topic, also for JavaScript testing i.e.

**Comment by samdark** [comment]
Closing since it requires too much effort w/o much gain.
