### ISSUE TITLE
薛强你好，有没有可能用console操作服务端的git

### ISSUE THREAD

**Issue by baizhiqiang** [yiisoft/yii2#13274]
我计划做一个关于中英文翻译的版本控制与团队协作系统，想问下是否可能用Yii2 的console操作服务端的git，如果可以应该怎么做。
另外是否可以提供点思路，像github这样的网站上的项目，实际的物理存储是以什么形式存储的，文件还是数据库呢？
谢谢你。

**Comment by arogachev** [comment]
@baizhiqiang Please use English if it's possible. @qiangxue is not available here for a long time.

Here is a translation for other developers (used Google Translate, I have not made any corrections to prevent possible loss of meaning:

---

**Titile:** Xue Qiang Hello, there is no possible use console operation of the server-side git
**Description:** I plan to do a translation on the English version of the control and team collaboration system, I would like to ask whether the console can be used Yii2 server operation git, if it should be how to do.

Also can provide some ideas, such as github the site of the project, the actual physical storage is stored in what form, file or database?

thank you.

---

It's unclear what's your problem?
