### ISSUE TITLE
Exception 'ReflectionException' with message 'Class db does not exist'

### ISSUE THREAD

**Issue by OtezVikentiy** [yiisoft/yii2#13279]
### What steps will reproduce the problem?
i created a migration with a comand yii migration/create xxx
then i wanted to run the comand yii migrate and got the error:

`
Yii Migration Tool (based on Yii v2.0.10)

Exception 'ReflectionException' with message 'Class db does not exist'

in D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\di\Container.php:422

Stack trace:
#0 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\di\Container.php(422): ReflectionClass->__construct('db')
#1 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\di\Container.php(362): yii\di\Container->getDependencies('db')
#2 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\di\Container.php(154): yii\di\Container->build('db', Array, Array)
#3 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\di\Instance.php(157): yii\di\Container->get('db')
#4 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\di\Instance.php(131): yii\di\Instance->get(NULL)
#5 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\console\controllers\MigrateController.php(170): yii\di\Instance::ensure('db', 'yii\\db\\Connecti...')
#6 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\base\Controller.php(152): yii\console\controllers\MigrateController->beforeAction(Object(yii\base\InlineAction))
#7 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('', Array)
#8 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('', Array)
#9 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array)
#10 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array)
#11 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 D:\Program Files (x86)\Ampps\www\project\advanced\vendor\yiisoft\yii2\yii(37): yii\base\Application->run()
#13 {main}

`

### Additional info

| Yii version      2.0
| PHP version      5.6
| Operating system  - win 10

could you help me please?

**Comment by githubjeka** [comment]
Or try to run from PC. Yii2 not run on phone device

**Comment by SilverFire** [comment]
You should configure DB connection

**Comment by OtezVikentiy** [comment]
@SilverFire, trusy me, i've configured everything i found in advanced version. 

main-local.php in directories:
common/config
console/config
environments/dev и environments/prod

where should i look further?

**Comment by OtezVikentiy** [comment]
@githubjeka, поставил basic yii2 для теста.

файл yii: (полный сток)

`#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
`
______________________________________________________________________________________________
файл console.php:

`<?php

$params = require(__DIR__ . '/params.php');
$db = require(__DIR__ . '/db.php');

$config = [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'app\commands',
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost;dbname=yii2basic',
            'username' => 'project',
            'password' => 'project',
            'charset' => 'utf8',
        ],
    ],
    'params' => $params,
    /*
    'controllerMap' => [
        'fixture' => [ // Fixture generation command line.
            'class' => 'yii\faker\FixtureController',
        ],
    ],
    */
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
    ];
}

return $config;
`
______________________________________________________________________________________

проверил, что до БД можно дотянуться вот так:

<?php
        $connection = Yii::$app->db;
        if ($connection)
        echo "Есть подключение к БД";
        else
        echo "Нет подключения к БД";
 ?>

подключение к бд есть - миграция не проходит... выдает все ту же ошибку.

Есть еще идеи?... о_О Про DB конфиг я уже 100 раз слышал... могу на гит выложить вообще все что установлено всю директорию basic, которую установил...

Что здесь не так? все по инструкции сделано.

**Comment by githubjeka** [comment]
Есть тимвьёвер? и добро пожаловать в https://gitter.im/yiisoft/yii2/rus, там всё быстро решается. Здесь не место это обсуждать ....

**Comment by OtezVikentiy** [comment]
@githubjeka да, тимвьюер есть, вечером смогу быть за компом, сможешь подключиться помочь? Ок, далее буду писать в чат =))
