### ISSUE TITLE
yii\validators\RegularExpressionValidator JS validator is applied, even if when is specified

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#13283]
### What steps will reproduce the problem?
Make a model, that has RegularExpressionValidator in rules & when on this validator
make a page that uses this property on html
### What is the expected result?
Since when is applied, RegularExpressionValidator JS validator should not be registered(unless clientWhen is applied)
### What do you get instead?
RegularExpressionValidator JS validator is always registered

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.29
| Operating system | Ubuntu 16.04

**Comment by mikk150** [comment]
currently, I am using hack to get around with it
```php
[
'whenClient' => 'function() {return false}'
]
```

**Comment by SDKiller** [comment]
It behaves exactly as it should according to docs

https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L177

**Comment by mikk150** [comment]
@SDKiller That is actually true,
since the improvement could potentially be not BC, maybe 2.1?

Because I think really if when is defined, it should not register JS validator, since it does not know output of it

**Comment by SDKiller** [comment]
It is BC

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/7546
