### ISSUE TITLE
Some Travis builds fail because connection with MySQL can't be established

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13284]
Examples of the recent failed builds:

- https://github.com/yiisoft/yii2/commit/30e599b94fbe79bd7bbec29a26987bb0ae4e2a0a, https://travis-ci.org/yiisoft/yii2/builds/187060307
- https://github.com/yiisoft/yii2/commit/abac69206d6c78707d64a1e75535883c9c86ac3a, https://travis-ci.org/yiisoft/yii2/builds/187060644.

Exact job where failure happened: https://travis-ci.org/yiisoft/yii2/jobs/187060646

```
mysql -e 'CREATE DATABASE `yiitest`;';

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysql-5.6/mysqld.sock' (111)

The command "mysql -e 'CREATE DATABASE `yiitest`;';" failed and exited with 1 during .

Your build has been stopped.
```

By the way, I saw this error before in some builds too.

Will try to investigate what's wrong and what causing it.

**Comment by cebe** [comment]
related https://github.com/travis-ci/travis-ci/issues/5088 ?

**Comment by cebe** [comment]
https://travis-ci.org/yiisoft/yii2/jobs/188143283#L105

**Comment by cebe** [comment]
https://github.com/travis-ci/travis-ci/issues/6842#issuecomment-268845739

**Comment by cebe** [comment]
This is still happening... https://travis-ci.org/yiisoft/yii2/jobs/198069379#L111

**Comment by SilverFire** [comment]
May be fixed by https://github.com/yiisoft/yii2/pull/13360

**Comment by cebe** [comment]
That PR does not touch travis. but we may skip travis as soon as that one is merged and use gitlab CI instead.
