### ISSUE TITLE
Unable yii\base\Model::AddError mark specific item of array

### ISSUE THREAD

**Issue by reticulum** [yiisoft/yii2#13281]
### What steps will reproduce the problem?
Creating some array parameter in model, e.g. here: 
http://www.yiiframework.com/doc-2.0/yii-validators-eachvalidator.html
In model form we will make some inputs for this parameter:
`<?= $form->field($model, 'categoryIDs[0]') ?>`
`<?= $form->field($model, 'categoryIDs[1]') ?>`

### What is the expected result?
Only field with error must be marked as incorrect.

### What do you get instead?
All fields of this array are marked as incorrect.

And in custom validation rule in model, if i set one: 
`public function validateCategoryId($attribute, $params)`
i will only able to get common name of array-attribute `categoryIDs` instead of specific `categoryIDs[n]`.

So now i cannot detect and mark specific item of array parameter in model.

**Comment by klimov-paul** [comment]
This is expected behavior. You should use tabular input for your goal.
