### ISSUE TITLE
Translation 'and' separator

### ISSUE THREAD

**Issue by jetexe** [yiisoft/yii2#13287]
### What steps will reproduce the problem?
Try to submit any two values that must be unique
### What is the expected result?
Normal transtation
### What do you get instead?
there's no way to translate 'and' separator in 
https://github.com/yiisoft/yii2/blob/master/framework/validators/UniqueValidator.php#L251
second param must be translatable separator

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | any
| Operating system | any

**Comment by SilverFire** [comment]
Confirmed. Would you like to submit a pull request with fix?

**Comment by jetexe** [comment]
#13372 a pull request with fix
