### ISSUE TITLE
Superfluous UTF-8 BOM in messages/az/yii.php

### ISSUE THREAD

**Issue by abra7134** [yiisoft/yii2#13296]
Superfluous UTF-8 BOM in messages/az/yii.php.
Later it is inserted into the answer on network.
See screenshot.

![messages_az](https://cloud.githubusercontent.com/assets/16083210/21563168/6e9c4448-ce98-11e6-9962-90ab2bebbef9.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.29
| Operating system | Debian 8.6

**Comment by arogachev** [comment]
I scanned the entire `framework` directory. Indeed, this file has a BOM.

```
grep -rlI $'\xEF\xBB\xBF'
messages/az/yii.php
```

Used [this command](http://stackoverflow.com/a/2858757/4323648) for scanning with additionally ignoring of binary files.

Good nitpick, I'll send PR in the next few minutes.

**Comment by cebe** [comment]
added a check to travis.yml: 17c2725

**Comment by arogachev** [comment]
Good idea to automate detecting BOM in Travis, 👍
