### ISSUE TITLE
Yii2 Guide website | Wrong text formatting on "Creating Forms" page

### ISSUE THREAD

**Issue by Enkey** [yiisoft/yii2#13291]
On guide page "Creating Form" in subsection "Creating Lists" you can found a small bug in text formatting.
[http://www.yiiframework.com/doc-2.0/guide-input-forms.html#creating-activeform-lists](http://www.yiiframework.com/doc-2.0/guide-input-forms.html#creating-activeform-lists)
Thanks.

**Comment by RSalo** [comment]
What?
