### ISSUE TITLE
JS tests started to fail with error: "Timeout of 2000ms exceeded"

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13305]
Example of commit - https://github.com/yiisoft/yii2/commit/f6b9aac0bf68490703c5e87f6841bdb1bb64346e
According build - https://travis-ci.org/yiisoft/yii2/builds/187973030
According job - https://travis-ci.org/yiisoft/yii2/jobs/187973039

Timeout was removed in PR #13160, see this discussion - https://github.com/yiisoft/yii2/pull/13160#discussion_r91474889.

I think we need either to increase it a bit and / or add `travis_retry` for `npm test` command.

**Comment by cebe** [comment]
Imo it is totally fine if tests run 30sec when travis is on high load, not sure if there is a need for a timeout at all. can it be disabled?

**Comment by arogachev** [comment]
I thought maybe it's better to pass this option in `npm test` call in Travis instead of having it as a default in `package.json`. But it's not crucial, let's leave it like that for now. Anyway it fixes the problem.

With Vagrant sometimes even 30 seconds is not enough for me, but it happens **very** seldom. Repeated call solves the problem.

As for disabling it completely - good idea too, I'll take a look if it's possible.

**Comment by arogachev** [comment]
@cebe Yes, turns out that it can be disabled completely. Just opened a PR with a better fix. We don't have to worry about it now.
