### ISSUE TITLE
Yii2 debugger pages indexed by google

### ISSUE THREAD

**Issue by aminkt** [yiisoft/yii2#13302]
Hi.

We develop a shopping system and publish it in internet.

just a week after, we see google indexed all debugger pages and our backend sql data.

note: some times for debugging we enabled debug system and then disabled that.

How can stop yii from indexing debug pages?

**Comment by aminkt** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/14914854/21567591/8a4081ee-cec2-11e6-9c64-67b661dcb591.jpg)

**Comment by cebe** [comment]
you should not enable debug toolbar on a production system ever. If you still do so you need to at least limit requests by IP or other methods.

Anyway, we could send headers to prevent indexing such pages.

**Comment by aminkt** [comment]
Thank you a lot.
:)))

**Comment by samdark** [comment]
I don't think sending headers makes any sense...

**Comment by aminkt** [comment]
I think you should add no index tag in head of debug pages.
