### ISSUE TITLE
Preventing of race conditions in script filter in yii.js works incorrectly

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13307]
I found these issues during writing tests for `yii.js`.

The fix (#12651, https://github.com/yiisoft/yii2/commit/1ab204e481c15a5969098363509407694e7965e1) for #10358 is incorrect. Not only it's not intuitive for understanding (mostly because of the way `if` checks are written), contains copy paste, magic numbers, it also causes some bugs.

The content of `initScriptFilter()` after applying this fix:

```js
function initScriptFilter() {
    var hostInfo = getHostInfo();
    var loadedScripts = {};

    var scripts = $('script[src]').map(function () {
        return this.src.charAt(0) === '/' ? hostInfo + this.src : this.src;
    }).toArray();
    for (var i = 0, len = scripts.length; i < len; i++) {
        loadedScripts[scripts[i]] = true;
    }

    $.ajaxPrefilter('script', function (options, originalOptions, xhr) {
        if (options.dataType == 'jsonp') {
            return;
        }

        var url = options.url.charAt(0) === '/' ? hostInfo + options.url : options.url;

        if (url in loadedScripts) {
            var item = loadedScripts[url];

            // If the concurrent XHR request is running and URL is not reloadable
            if (item !== true && !isReloadable(url)) {
                // Abort the current XHR request when previous finished successfully
                item.done(function () {
                    if (xhr && xhr.readyState !== 4) {
                        xhr.abort();
                    }
                });
                // Or abort previous XHR if the current one is loaded faster
                xhr.done(function () {
                    if (item && item.readyState !== 4) {
                        item.abort();
                    }
                });
            } else if (!isReloadable(url)) {
                xhr.abort();
            }
        } else {
            loadedScripts[url] = xhr.done(function () {
                loadedScripts[url] = true;
            }).fail(function () {
                delete loadedScripts[url];
            });
        }
    });
    
    // Filter for CSS is not related with this fix so its code is not included for brevity
}
```

Let's abstract from using pjax and consider simpler examples using [$.getScript()](https://api.jquery.com/jquery.getscript/) jQuery function. Calls of it will trigger `$.ajaxPrefilter`.

## 1st problem - Setting resolving callbacks only for the 1st request

Let's say we have 2 concurrent requests:

```js
$.getScript('/js/concurrent.js');
$.getScript('/js/concurrent.js');
```

and 2nd will succesfully complete earlier.

As a result, 1st one will be immediately aborted. However, script will not be marked as loaded, because of this code:

```js
loadedScripts[url] = xhr.done(function () {
    loadedScripts[url] = true;
}).fail(function () {
    delete loadedScripts[url];
});
```

These callbacks are only set for the **1st** request and all subsequent requests will be considered as concurrent and handled differently. So the implementation relies on the fact that 1st request always finishes earlier.

So it's possible to load `/js/concurrent.js` again even without marking it as "reloadable".

## 2nd problem - Designed to work with pairs of XHR

This part:

```js
// Abort the current XHR request when previous finished successfully
item.done(function () {
    if (xhr && xhr.readyState !== 4) {
        xhr.abort();
    }
});
// Or abort previous XHR if the current one is loaded faster
xhr.done(function () {
    if (item && item.readyState !== 4) {
        item.abort();
    }
});
```

is designed to work with pairs of XHR. So even it can work for 2 requests, if we talking about concurrent requests, why limit their count to 2? It can be 3, 4, 5, etc.

At least having 3 concurrent requets:

```js
$.getScript('/js/concurrent.js');
$.getScript('/js/concurrent.js');
$.getScript('/js/concurrent.js');
```

can cause unpredictable behavior too.

## 3rd problem - Not adapted to the case of concurrent requests to different urls

At the beginning, when `$.ajaxPrefilter` is fired, `url` variable is calculated:

```js
var url = options.url.charAt(0) === '/' ? hostInfo + options.url : options.url;
```

Then it's used in marking script as loaded or deleting it in case of fail:

```js
loadedScripts[url] = xhr.done(function () {
    loadedScripts[url] = true;
}).fail(function () {
    delete loadedScripts[url];
});
```

But again, if we are talking about concurrent requests, this can also easily happen:

```js
$.getScript('/js/concurrent1.js');
$.getScript('/js/concurrent2.js');
```

Two requests are done to 2 different urls and not immediately completed. Let's say `/js/concurrent2.js` completes earlier. Then `url` for the `/js/concurrent1.js` will be `undefined` because it was overwriitten when the callbacks were attached to `/js/concurrent1.js`.

So for the `/js/concurrent1.js`:

```js
loadedScripts[url] = true;
```

is identical to:

```js
loadedScripts[undefined] = true;
```

which is a valid JS (we can set a object property with a key `undefined`), but obviously it's not what we expected. So it's possible to load `/js/concurrent1.js` again even without marking it as "reloadable".

## 4th problem - `xhr.abort()` calls `xhr.fail()`

You can read details in this [blog article](http://paulrademacher.com/blog/jquery-gotcha-error-callback-triggered-on-xhr-abort/) for example.

So when we have:

```js
$.getScript('/js/concurrent.js');
$.getScript('/js/concurrent.js');
```

If 2nd request will complete earlier, 1st one will be immediately aborted, but along with `abort()`, `fail()` callback will be called and will try to delete it from loaded scripts.

**Comment by arogachev** [comment]
So to fix **1** and **2** we need to consider all script loading requests as a queue (not divide them to pairs or separate 1st, they are all concurrent) and additionally separate them by the url to fix **3**. So @nkovacs was on the right track in https://github.com/yiisoft/yii2/issues/10358#issuecomment-163218693.

In case of a success of one of the requests we can abort all concurrent requests to the same url and mark the script as loaded clearing the queue. It's better to add locking mechanism during this clenup and not accept any other requests to this url to prevent errors and additional race conditions. Because cleanup code is synchronous (not depend on the network connection) and executes way faster, it's an admissible thing to do and should not affect UX.

With fail we can just delete this request from this url's / asset's queue and hope that some others will complete successfully. If all will fail, we need to mark the script as not loaded. As I think, accepting new requests is valid during fail cleanup and will not cause any errors or race conditions.

Fix for **4** is apparently easy, we need to check `textStatus` parameter value to be equal `abort`:

```js
xhr.fail(function (jqXHR, textStatus) {
    if (textStatus === 'abort') {
        return;
    }

    // The rest of the code
```

**Comment by SilverFire** [comment]
> ### 1st problem - Setting resolving callbacks only for the 1st request

> ... So the implementation relies on the fact that 1st request always finishes earlier.

No, it was not designed to rely on that fact.

Let's inspect that code step-by-step:

1. `$.getScript('/js/concurrent.js');`. The produced XHR promise will be called **first**
2. Line [:440] is reached, the XHR gets stored  in the `loadedScripts` variable, `done` and `fail` handlers are attached to the XHR.
3. `$.getScript('/js/concurrent.js');`. Concurrent request is started, the produced XHR promise will be called **second**
4. As the URL is present in the loaded list and does not equal `true`, the **first** XHR is still running, so the line [:420] is reached.
5. The **first** XHR request gets additional `done` event handler on line [:425]. That handler is designed to __cancel__ the **sencond** XHR request, if the **first** is successfully loaded earlier.
6. The **second** XHR request gets additional `done` event handler on line [:431]. That handler is designed to __cancel__ the **first** XHR request, if the **second** is successfully loaded earlier.


[:431]: https://github.com/yiisoft/yii2/commit/1ab204e481c15a5969098363509407694e7965e1#diff-f433792b516845f488519deb1a72741aR431
[:425]: https://github.com/yiisoft/yii2/commit/1ab204e481c15a5969098363509407694e7965e1#diff-f433792b516845f488519deb1a72741aR425
[:440]: https://github.com/yiisoft/yii2/commit/1ab204e481c15a5969098363509407694e7965e1#diff-f433792b516845f488519deb1a72741aR440
[:420]: https://github.com/yiisoft/yii2/commit/1ab204e481c15a5969098363509407694e7965e1#diff-f433792b516845f488519deb1a72741aR420

**Comment by SilverFire** [comment]
> ### 2nd problem - Designed to work with pairs of XHR

> can cause unpredictable behavior too.

Yes, it looks quite unpredictable.




> ### 3rd problem - Not adapted to the case of concurrent requests to different urls

From my POV, only requests to the same URL are concurrent. Could you explain how can be concurrent a pair of requests to different URLs?

**Comment by SilverFire** [comment]
> ### 4th problem - `xhr.abort()` calls `xhr.fail()`

I didn't know that, but it worked somehow =/ Thank you for digging in

**Comment by SilverFire** [comment]
Generally I agree with your ideas of the filter enhancements.

**Comment by arogachev** [comment]
As for the **1st problem**, let me explain again.

We are calling **2** requests at the same time:

```js
$.getScript('/js/concurrent.js');
$.getScript('/js/concurrent.js');
```

Let's name **1st** request **"A"** and the **2nd** - **"B"**.

**1)** The **A** receives `done` and `fail` callbacks and this XHR added to mark the script as "in the process of loading" and to refer to it later:

```js
loadedScripts[url] = xhr.done(function () {
    loadedScripts[url] = true;
}).fail(function () {
    delete loadedScripts[url];
});
```

**2)** For the **B** this code is not executed (because `url` is in `loadedScripts` now) and some handling of the concurrent requests is performed via attaching callbacks and calling `xhr.abort()`:

```js
// Abort the current XHR request when previous finished successfully
item.done(function () {
    if (xhr && xhr.readyState !== 4) {
        xhr.abort();
    }
});
                    
// Or abort previous XHR if the current one is loaded faster
xhr.done(function () {
    if (item && item.readyState !== 4) {
        item.abort();
    }
});
```

The **A** and "B" are still in the process of loading.

**3)** Now imagine that **B** request finishes first.

In its `done` callback the **A** request will be aborted using `xhr.abort()`. As a result (see *4th problem*), this code will be additionally executed for the **A**:

```js
delete loadedScripts[url];
```

But this part will be never called:

```js
loadedScripts[url] = true;
``` 

because **A** request was aborted and only `fail()` callback was fired. So even if the script was loaded successfully with the **B**, it was not marked as "loaded" and it's possible to load it again even if it's not "reloadable":

```js
$.getScript('/js/concurrent.js');
```

Do you understand it now? I reproduced it in tests even before I found **2nd problem**.

**Comment by arogachev** [comment]
> From my POV, only requests to the same URL are concurrent. Could you explain how can be concurrent a pair of requests to different URLs?

Even they are not concurrent in the way requests for the same url are, just imagine the case when we loading 2 different scripts at the same time:

```js
$.getScript('/js/script1.js');
$.getScript('/js/script2.js');
```

If **1st** will not be completed at the moment of running `$.ajaxPrefilter` for `script2.js`, `url` variable will be overwritten and lost (`undefined`) for the `script1.js` as a result.

So `script1.js` will not be correctly marked as loaded and like in **1st problem**, it's possible to load it again even if this script is not set as "reloadable":

```js
$.getScript('/js/script1.js');
```
