### ISSUE TITLE
Allow pjax with "data-pjax" with no value in yii.js

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13300]
I found this issue during writing tests for `yii.js`.

After https://github.com/yiisoft/yii2/commit/9807b2e1a1ac1c671c860ab448eab8bf9154b2bf we lose the ability to have pjax links like 

```html
<a data-pjax href="#">
```

or 

```html
<a data-pjax="" href="#">
```

(which is essentially the same).

This is because of:

```js
pjax = $e.data('pjax') || 0,
```

`"" || 0` resolves to `0`.

This condtradicts with confuring pjax described in the docs for example [here](https://github.com/yiisoft/jquery-pjax#fnpjax):

> Or try this selector that matches any `<a data-pjax href=>` links inside a `<div data-pjax>` container.

I think that the older behavior - `pjax !== undefined && pjax !== 0 && $.support.pjax` is more correct, also note that @arisk sent the PR including this check in #12737 (https://github.com/yiisoft/yii2/pull/12737/commits/383aa471c684e011e48862943a52a8b7c22a08b0), then it was ignored.

It will be better if we disable pjax only if `data-pjax` attribute is set to `0` only:

```js
usePjax = pjax !== undefined && pjax !== 0 && $.support.pjax,
```

Note however that this check in [Yii2 pjax adaptation](https://github.com/yiisoft/jquery-pjax):

```js
// Ignore links with data-pjax="0"
if ($(link).data('pjax') == 0) {
    return;
}
```

needs to be modified accordingly too, because `"" == 0` will evaluate to `true`.

Can be:

```js
$(link).data('pjax') === 0)
```

(`data` returns `0` as `number`).

Or in case of a `string` which is returend by `attr` for example:

```js
$(link).attr('data-pjax') === '0'
```

Or maybe even better:

```js
parseInt($(link).data('pjax')) === 0
```

> Note: I already fixed it in `yii.js` in PR containing tests for `yii.js`. PR will be sent soon.

**Comment by samdark** [comment]
Agree that it should be fixed as you've described.

**Comment by Mirocow** [comment]
Substituting this
