### ISSUE TITLE
Handle relative and absolute URLs coincidence in CSS filter in yii.js

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13310]
I found this issue during writing tests for `yii.js`.

Let's take a look at the current contents of the CSS filter in `yii.js` which is a part of `initScriptFilter()` function and used to prevent loading of the same stylesheets.

```js
$(document).ajaxComplete(function (event, xhr, settings) {
    var styleSheets = [];
    $('link[rel=stylesheet]').each(function () {
        if (isReloadable(this.href)) {
            return;
        }
        if ($.inArray(this.href, styleSheets) == -1) {
            styleSheets.push(this.href)
        } else {
            $(this).remove();
        }
    })
});
```

The url is retrieved from `this.href` and used as is.

With JS filter it's converted to absolute to prevent possible coincidence of urls like `/js/script.js` and `http://foo.bar/js/script.js` which are essentially the same if the current site is `http://foo.bar`:

```js
 var url = options.url.charAt(0) === '/' ? hostInfo + options.url : options.url;
```

So I think the same needs to be done with CSS.

Currently if if the current site is `http://foo.bar` and we load `/css/stylesheet.css` first and then `http://foo.bar/css/stylesheet.css`, it will be loaded as a duplicate.

I think it was simply forgotten to be added for CSS.

> **Note:** I already fixed it in PR containing tests for `yii.js`. PR will be sent soon.

**Comment by samdark** [comment]
Yes, should be fixed,
