### ISSUE TITLE
Format as date 0n 01-01-2017 returns wrong year

### ISSUE THREAD

**Issue by wimrademaker** [yiisoft/yii2#13311]
The date formatter returns a wrong year (2016) when using January 1 2017
Using another day seems to go fine.

<?= Yii::$app->formatter->asDate('2017-01-01', 'dd-MM-Y')?>
Returns 01-01-2016

<?= Yii::$app->formatter->asDate('2017-01-02', 'dd-MM-Y')?>
Returns 02-01-2017

Yii version 2.0.10 
PHP 5.6.29

**Comment by cebe** [comment]
Y is the year for the calendar week of that day. use `y` instead. http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax
