### ISSUE TITLE
Allow underscores for extension namespaces

### ISSUE THREAD

**Issue by Nex-Otaku** [yiisoft/yii2#13321]
### What steps will reproduce the problem?

1. Open Gii page.

2. Open Extension Generator.

3. Try to enter namespace with underscores, for example "nex_otaku\".

### What is the expected result?

Underscores should be allowed, as it is valid for PSR-4.

### What do you get instead?

You will see validation error "Only letters, numbers and backslashes are allowed."

### Additional info

PSR-4:
2.4. Underscores **have no special meaning** in any portion of the fully qualified class name.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10-dev
| PHP version      | 5.6.12
| Operating system | Windows

**Comment by cebe** [comment]
Would you like to fix it and send a pull request?
