### ISSUE TITLE
Check "Referer" in request header in method getReturnUrl in User class

### ISSUE THREAD

**Issue by iushev** [yiisoft/yii2#13323]
Maybe is good idea to check "Referer" in request header when resolve return URL in method getReturnUrl in yii\web\User class.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 5.6
| Operating system | Ubuntu

**Comment by cebe** [comment]
Referer is user input and can not generally be trusted. It needs to be validated dependent on the use case.

**Comment by samdark** [comment]
It's not safe at all to rely on it.

**Comment by iushev** [comment]
Usually it set by browser.

**Comment by samdark** [comment]
It can be set by any client.

**Comment by SilverFire** [comment]
Agreed with @samdark and @cebe 

Sorry, the behavior will not be changed
