### ISSUE TITLE
Postgresql shema turns numeric column to string

### ISSUE THREAD

**Issue by pgrzelka** [yiisoft/yii2#13320]
### What steps will reproduce the problem?
```
CREATE TABLE measure
(
    id UUID PRIMARY KEY NOT NULL,
    height NUMERIC(5,2) DEFAULT 0,
    weight NUMERIC(5,2) DEFAULT 0
);
```
```
$model = Measure::find()->one();
print_r($model->toArray());
```

### What is the expected result?
`['id' => '...', 'height' => 12.2, 'weight' => 10.5]`

### What do you get instead?
`['id' => '...', 'height'  =>  '12.2', 'weight' => '10.5']`

### Additional info
With one little change in function _getColumnPhpType_ in class _\yii\db\Schema_ code works perfect.

```
      static $typeMap = [
            // abstract type => php type
            'smallint' => 'integer',
            'integer' => 'integer',
            'bigint' => 'integer',
            'boolean' => 'boolean',
            'float' => 'double',
            'double' => 'double',
            'decimal' => 'double', // new line added
            'binary' => 'resource',
        ];
```
Without this line column phpType for postgresql numeric column is string.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      |7.0.8-0ubuntu0.16.04.3
| Operating system |Ubuntu
| Postgresql      |9.5

**Comment by cebe** [comment]
`NUMERIC(5,2)` can not be safely represented as double or float. PHP does not provide a type that can contain fixed digit decimal numbers. Thus to preserve precision, it is kept as string.
