### ISSUE TITLE
CSRF Cookie is not sending simetimes and  BadRequestHttpException is throwing

### ISSUE THREAD

**Issue by chim0380** [yiisoft/yii2#13334]
Site work by https only and  CSRF on. 

Fragment  main.config.

```
'request' => [
            'cookieValidationKey' => 'xxxxxxx',
            'csrfParam' => '_frontendCSRF',
            'enableCookieValidation' => true,
            'enableCsrfValidation' => true,
            'csrfCookie' => [
                'httpOnly' => true,
                'path' => '/',
                'secure' => true,
            ],

```
Simetimes, nearly 3-4 times in day I see in log:

> [error][yii\web\HttpException:400]
> exception 'yii\web\BadRequestHttpException' with message 'Не
> удалось проверить переданные данные.'
> in
> /www/vendor/yiisoft/yii2/web/Controller.php:110

Most of this exceptions was thrown if device Android 5.1 (other versions Android or ios 9 
on rare occasions ). 

 I see that in this case  a cookie _frontendCSRF  was not send to server (90%) or it does not match with the POST '_frontendCSRF' 

> $_POST = [
>     '_frontendCSRF' =>
> 'WEguTFBTSkthJUodNmoJITwiYX05NT8DCAxYNCo/HzozCn0YHBEYHw=='
>     'LoginForm' => [
>         'email' => 'xxxx@icloud.com'
>         'password' => 'xxxxxx'
>         'rememberMe' => '1'
>     ]
>     'x' => '163'
>     'y' => '437'
> ]
> 
> $_COOKIE = [
>     '_frontendCSRF' =>
> 'df180a7a1c13a8645c7c6113e84d258ce94e2be79cba6afc3125207b4ca00b83a:2:{i:0;s:13:\"_frontendCSRF\";i:1;s:32:\"KbvCu_mzfMxAywxkA7ObmwOVaqfscRlZ\";}'

Can we solve this problem  without shutting off CSRF ?

### What is the expected result?
 
Don't throw exception

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.23
| Operating system | FreeBSD 10.1

**Comment by samdark** [comment]
Exception is expected in this case since that's what CSRF protection is all about.

**Comment by chim0380** [comment]
Why client don't send cookie?  Special Android 5.1
May be enableCookieValidation need to set  false  or httpOnly need to set  false?

**Comment by samdark** [comment]
If you don't need it, you can disable it: https://github.com/samdark/yii2-cookbook/blob/master/book/csrf.md
