### ISSUE TITLE
Compare validator enhancement

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2#13333]
Compare validator should be triggered on the field itself and also on the compareAttribute change event

['password', 'required'],
['repassword', 'required'],
['repassword', 'compare', 'compareAttribute' => 'password', 'message' => Yii::t('app', "Passwords don't match")],

1. Fill in the password field
2. Fill in the repassword filed
3. Go back and change password field - nothing happens.
The idea is to trigger the validation on both field.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.4.16
| Operating system | Centos 7 x64

**Comment by jhon100** [comment]
I guess fixing #12864  will fix this too.

**Comment by evil1** [comment]
Yes, you are right!
The nature of the issue is the same.
But in my opinion, single compare validator must compare both fields and must be triggered for both comparable fields instead of making two rules like in that issue:
['cred_rendimentos', 'compare', 'compareAttribute' => 'cred_despesas', 'operator' => '>=' ],
['cred_despesas', 'compare', 'compareAttribute' => 'cred_rendimentos', 'operator' => '<' ],

**Comment by jhon100** [comment]
Yes, it makes sense.

**Comment by SilverFire** [comment]
Related to https://github.com/yiisoft/yii2/issues/12636

**Comment by samdark** [comment]
Won't be implemented in 2.0.
