### ISSUE TITLE
Specify modelClass attribute in rest ActiveController like Yii::createObject() style

### ISSUE THREAD

**Issue by njspok** [yiisoft/yii2#13332]
### What steps will reproduce the problem?

I cant specify model in rest ActiveController by attribute modelClass like this

```php
        'some-controller' => [
            'class' => 'yii\rest\ActiveController',
            'modelClass' =>  [
                'class' => 'humhub\modules\fooddelivery\models\OrderFood',
                'some-model-attribute' => 'value',
        ],
```

Whether such a possibility in the future?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      |  PHP 7.0.8-0ubuntu0.16.04.3
| Operating system | Ubuntu

**Comment by klimov-paul** [comment]
No, this will not be supported as `modelClass` is used not only for model creation but for the ActiveQuery creation too.
