### ISSUE TITLE
MySQL 5.7 - createTable in migration create MyISAM instead of InnoDB

### ISSUE THREAD

**Issue by michaelnguyen547** [yiisoft/yii2#13338]
### What steps will reproduce the problem?
Create a migration such as the below

```
$this->createTable('alert_project', [
    'project_id' => $this->integer()->notNull(),
    'alert_id' => $this->integer()->notNull(),
    'content' => $this->text()->notNull(),
    'recipient' => $this->text()->notNull(),
    'variable_1_label' => $this->string(128)->null(),
    'variable_1_value' => $this->decimal(6, 2)->null(),
    'variable_2_label' => $this->string(128)->null(),
    'variable_2_value' => $this->decimal(6, 2)->null(),
    'active' => $this->integer(1)->defaultValue(0),
]);

$this->createIndex('project_id', 'alert_project', 'project_id');
$this->addForeignKey('FK_alert_project_project_id', 'alert_project', 'project_id', 'project', 'id', 'CASCADE', 'CASCADE');

$this->createIndex('alert_id', 'alert_project', 'alert_id');
$this->addForeignKey('FK_alert_project_alert_id', 'alert_project', 'alert_id', 'alert', 'id', 'CASCADE', 'CASCADE');
```

Got the Success migration as showed

![migrateup](https://cloud.githubusercontent.com/assets/436950/21736922/95903cbe-d431-11e6-9098-21486d32f776.png)

### What is the expected result?
'alert_project' table is created and is InnoDB and have foreigner key constraints 

### What do you get instead?
'alert_project' table is created and is MyISAM thus no foreigner key constraints

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.19
| MySQL version | 5.7.11
| Operating system | Windows 10

P/S: I tested on Ubuntu Box which does not have the described issue

Yii version 2.0.10
PHP version 5.5.9
MySQL version 5.5.53

Likely MySQL 5.7 is the source.

**Comment by bizley** [comment]
Isn't this because of the default storage engine you have set in your MySQL? Migration does not set storage engine silently. That is why as there is this line at the beginning in examples:

    if ($this->db->driverName === 'mysql') {
        // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
        $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
    }

You can set engine manually in `createTable()` method (3rd argument as in: `$table`, `$columns`, `$options`).

**Comment by michaelnguyen547** [comment]
thanks @bizley
