### ISSUE TITLE
Very strange behaviors while work with symfony/process and proc_open

### ISSUE THREAD

**Issue by yanhuixie** [yiisoft/yii2#13349]
### What steps will reproduce the problem?
We are using trntv/yii2-command-bus to handle the asynchronous background process. The yii2-command-bus use symfony/process and proc_open to make a console/yii shell invoking. For example, assuming the final command generated by symfony/process was 
```shell
/usr/bin/php /path/to/app/console/yii command-bus/handle TzoyOToiYbWblabla...== &
```
. Just the first parameter of proc_open. 
And, the proc_open may failed, no error, no warning, nothing logged.
### What is the expected result?
Yes, we wish the background job was normally processed. But, no luck.
After tons of experiments, we found out the following things.
1) If the YII_DEBUG = true, then proc_open always works fine, else see the following.
2) If the YII_DEBUG = false, though proc_open will failed, but if we make a Yii::warning() call before the proc_open statement, miracle will happen! It works! But, if using Yii::info() instead of Yii::warning(), it's no help (failed again).
3) The symfony/process synchronous call is normally(no care about YII_DEBUG), the scenario we meet is asynchronous call. 
### What do you get instead?
We have been confusing days and googling all the pattern we can try. So... we post this issue here.
### Additional info
We are sure that the our related function code of console command-bus are tested and work normally some days before (with YII_DEBUG = false). What we did these days that have just made a composer update to the "vendors", it updated lots of components, including upgrade Yii 2.0.9 to 2.0.10. So sorry that we can't reproduce the environment as previous... Any suggestion is appreciated. Thanks everyone.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.14
| Operating system | Centos 7.2

### The code snippet of vendor/symfony/process/Process.php/start
```php
...
if ('\\' === DIRECTORY_SEPARATOR && $this->enhanceWindowsCompatibility) {
	$commandline = 'cmd /V:ON /E:ON /D /C "('.$envline.$commandline.')';
	foreach ($this->processPipes->getFiles() as $offset => $filename) {
		$commandline .= ' '.$offset.'>'.ProcessUtils::escapeArgument($filename);
	}
	$commandline .= '"';

	if (!isset($this->options['bypass_shell'])) {
		$this->options['bypass_shell'] = true;
	}
} elseif (!$this->useFileHandles && $this->enhanceSigchildCompatibility && $this->isSigchildEnabled()) {
	// last exit code is output on the fourth pipe and caught to work around --enable-sigchild
	$descriptors[3] = array('pipe', 'w');

	// See https://unix.stackexchange.com/questions/71205/background-process-pipe-input
	$commandline = $envline.'{ ('.$this->commandline.') <&3 3<&- 3>/dev/null & } 3<&0;';
	$commandline .= 'pid=$!; echo $pid >&3; wait $pid; code=$?; echo $code >&3; exit $code';

	// Workaround for the bug, when PTS functionality is enabled.
	// @see : https://bugs.php.net/69442
	$ptsWorkaround = fopen(__FILE__, 'r');
} elseif ('' !== $envline) {
	$commandline = $envline.$commandline;
}
// if make a \Yii::warning call here, or with YII_DEBUG = true, proc_open will work normally. //by xie
$this->process = proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $env, $this->options);

if (!is_resource($this->process)) {
	throw new RuntimeException('Unable to launch a new process.');
}
$this->status = self::STATUS_STARTED;
...
```

**Comment by samdark** [comment]
Nothing obvious came to my mind. The issue seems to be complex... If everything worked before, there's a good way to find out. You say that it was fine with 2.0.9? Can you fix dependency version in `composer.json`, run update and try? If it works then you can find a commit introducing change that made everything broken using [git bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search).

**Comment by yanhuixie** [comment]
Thanks for your advice, @samdark ! We will try it soon and post the feedback.

**Comment by yanhuixie** [comment]
Hi, @samdark ! Maybe some things become more complicated and interesting.... We find several slightly older host with different PHP versions. The following is the result of the experiment (Our vendor package of 2016-08-02 2016-10-06 2016-10-20 2016-11-25 2017-01-06 tested).
### Host A:
Centos 7.2
PHP 7.0.11 (cli) (built: Sep 17 2016 09:23:18) ( NTS )
All the test passed, no matter YII_DEBUG or Yii 2.0.9 or 2.0.10.
### Host B:
Centos 7.2
PHP 7.0.13 (cli) (built: Nov 10 2016 22:33:41) ( NTS )
Only YII_DEBUG=true or with Yii::warning() should pass, no matter Yii 2.0.9 or 2.0.10.
### Host C:
Mac OSX 10.11.6
PHP 7.0.14 (cli) (built: Dec 20 2016 18:38:52) ( NTS )
All the test passed, no matter YII_DEBUG or Yii 2.0.9 or 2.0.10.

Now, I think the following facts can be confirmed.
1) This behavior is irrelevant to the version of Yii2 (My guess is wrong).
2) This behavior is relevant to the version of PHP (new speculation).

But, we still confusing about the YII_DEBUG and Yii::warning. Why do they affect the functionality of proc_open? Is there some method to dig into the proc_open? or YII_DEBUG and Yii::warning will affect the environment of proc_open runtime that out of the parameters passed to proc_open?

**Comment by samdark** [comment]
> Why do they affect the functionality of proc_open?

No idea. They should not.

> Is there some method to dig into the proc_open?

strace.

> or YII_DEBUG and Yii::warning will affect the environment of proc_open runtime that out of the parameters passed to proc_open?

It looks like so. It could be error handler or additional logging...

**Comment by yanhuixie** [comment]
Thanks @amdark ! We will try strace and feedback later.

**Comment by dynasource** [comment]
@yanhuixie, what is the status of this ticket?

**Comment by yanhuixie** [comment]
Oh, we are sorry, @dynasource . There is no conclusion yet, we have recently busing for other things, and will continue to this research some days later.
