### ISSUE TITLE
AccessControl behavior "role" could be confusing 

### ISSUE THREAD

**Issue by gvasilopulos** [yiisoft/yii2#13344]
### What steps will reproduce the problem?
there is no problem just a litte confusing implementation 
### Additional info

taken from the Yii2 guide:

```php
public function behaviors()
{
    return [
        'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'actions' => ['index'],
                    'roles' => ['managePost'],
                ],
```

It seems that 'roles'=>['managePost'] really refers to permission
so it may be 'permissions'=>['managePost']
to avoid confusion.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6
| Operating system |

**Comment by cebe** [comment]
Yeah, according to RBAC checks should only be made against permissions so it would make sense to rename that for better user education.

**Comment by samdark** [comment]
Agree that it should be renamed.

**Comment by samdark** [comment]
I'm for supporting both keys in 2.1.x and dropping `roles` in 2.1.

**Comment by bizley** [comment]
Maybe some other name is needed here, something that means (or concerns) "roles+permissions" because in 2.1 expect issue like: 
> It seems that 'permissions'=>['?', 'admin'] really refers to roles

I suggest "**applyTo**" or "**check**".

**Comment by samdark** [comment]
`only`?

**Comment by cebe** [comment]
"only" is too generic, we have "actions", "controller", "ips"... then "only"-what?

**Comment by SilverFire** [comment]
How about `can`? It is alike `Yii::$app->user->can()`

> I'm for supporting both keys in 2.1.x and dropping roles in 2.1.

IMHO it's not the change that requires such a massive BC breaking. I'm OK even with having both permanently.

**Comment by samdark** [comment]
`can` doesn't sound descriptive. The access rule itself has `allow` which is very close to `can`.

**Comment by bizley** [comment]
What about `privileges`? It sounds descriptive for both roles and permissions: "admin privileges", "editing privileges".

**Comment by thyseus** [comment]
Actually, you can pass an array of roles, of permissions or even mixed here.

So i suggest that 'roles' and 'permissions' should be aliases and be both valid even in yii 2.1, as long as only one of them are specified. 

Roles and Permissions are both valid entities here.

This way we also stay backward-compatible.

**Comment by cebe** [comment]
sure that is the point of the issue. find a name that fits both because both are allowed. I do not think we should go with two separate properties, it will only make the implementation too complicated.

**Comment by thyseus** [comment]
The Implementation is straightforward in my opinion:

```php
if($roles && $permissions)
  return array_merge($roles, $permissions);
else if (!$roles && !$permissions)
  return null;
else 
  return $roles || $permissions;
```

or even prettier if there is some code logic guru :)

**Comment by thyseus** [comment]
This way we could do something like:

```php
'roles' => ['role_1', 'role_2'],
'permissions' => ['permission_1', 'permission_2'],
```

which seems quite readable for me.

**Comment by samdark** [comment]
Yes, indeed it looks OK.

**Comment by thyseus** [comment]
Perhaps https://github.com/yiisoft/yii2/pull/13403 may already be the solution? Please Code Review, thanks !

**Comment by bizley** [comment]
The point is that you can do 

    'roles' => ['permission_1', 'permission_2'],
    'permissions' => ['role_1', 'role_2'],

and it's perfectly fine. That is why we think about one new name for this key.

**Comment by Kolyunya** [comment]
Roles and permissions are already called [`items`](https://github.com/yiisoft/yii2/blob/master/framework/rbac/Item.php). Why don't we stick to the existing naming convention of the RBAC framework and call it just `items`?

**Comment by samdark** [comment]
Item is a general internal name which is not really exposed in the docs or in RBAC papers.

**Comment by Kolyunya** [comment]
@samdark it is indeed exposed: [1](http://www.yiiframework.com/doc-2.0/yii-rbac-dbmanager.html#$itemTable-detail), [2](http://www.yiiframework.com/doc-2.0/yii-rbac-dbmanager.html#$itemChildTable-detail), [3](http://www.yiiframework.com/doc-2.0/yii-rbac-phpmanager.html#$itemFile-detail).

**Comment by samdark** [comment]
Well, that is API, not docs and not RBAC original paper. Anyway, thanks for suggestion, it got handy for a pull request.
