### ISSUE TITLE
Formatter: asTime can't recognize DST (summer time) without delivered date -> ambiguous result

### ISSUE THREAD

**Issue by Enrica-r** [yiisoft/yii2#13343]
### What steps will reproduce the problem?
The described issue happens only if `formatter->defaultTimeZone === 'UTC'` and `formatter->timeZone <> 'UTC'`. Format time only (without date info).

### What is the expected result?
Example: I live in the local zone 'Europe/Zurich' ( from UTC in winter +1h, in summer +2h). A user enters a time of '00:30 h' in a time field only (enter date is 31-Jul-2016). The app stores '22:30 h UTC' correctly because it's summer. The database can't store the date in a time field. Today on 07-Jan-2017 a user is opening a view of this record. He sees 23:30 h because Yii formatter normalizes the current date in `DateTime`object what is in winter.

This behavior isn't  the intention probably! Consequence: the time (shift) is dependent of viewing date. 

### What do you get instead?
Locale time only (as stored in db) formatted if there is no date information delivered. Time Zone shifting makes sense only for timestamps or datetime fields. Yii formatter already suppresses time zone shifting for dates without time info. Same should be done for time values like '11:30:15'.

I found the same issue at kartik-v's DateControl extension (see https://github.com/kartik-v/yii2-datecontrol/issues/102).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0.x
| Operating system | windows 10

**Comment by cebe** [comment]
you can not perform any meaningful timezone conversion on a time-only information.
Where does Yii do that? Please show some code and the expected output of it.

**Comment by bizley** [comment]
This is expected behavior. You can not convert time between DST and standard without knowing the date.

**Comment by Enrica-r** [comment]
Why do you think this is expected behavior and in the same time you say that's not possible without knowing the date?

I have built a very simple example:
I created in db a field named "time" with a value of '12:00:00'. Timezone is MET (Europe/Zurich).

Output:
![output](https://cloud.githubusercontent.com/assets/2463365/21746113/619fcbf8-d53b-11e6-947c-8b1e15196061.jpg)
This is the (quick and dirty) code to generate above output:
```php
    $formattedTime = Yii::$app->formatter->asTime($model->time);
    $formattedDt = Yii::$app->formatter->asDatetime($model->time);
    ?>
    <table>
        <tr>
            <td>Unformatted raw from db: </td>
            <td><?php echo $model->time;?> </td>
        </tr>
        <tr>
            <td>Formatted with Yii formatter "asTime": </td>
            <td><?php echo $formattedTime;?> </td>
        </tr>
        <tr>
            <td>Same content formatted "asDateTime":&nbsp; </td>
            <td><?php echo $formattedDt;?> </td>
        </tr>
    </table>
```
It's clear that if I run same app next summer it will show in line 2 the value '14:00:00' and then next November '13:00:00' again. This is confusing for users. Think what happens if have an app with a weekly delivery time of something. You enter in October 13:00h but in November it shows 14:00h (its wrong you deliver still at 13:00 h).

BTW this can't happen with a timestamp/datetime db field because Yii uses the original entered date for time zone offset even if 'asTime' is formatted.

As you can see in line 3 Yii is generating "internally" a fully dateTime object with current date? This happens in yii/i18n/formatter function normalizeDatetimeValue.

If you set a 'timeZone' different then 'defaultTimeZone' it has impact to asDateTime and asTime. You can't differentiate. 

Discussion of different options:
-It's acceptable that the formatted time will change after DST change.
-If not acceptable then we can't use UTC in db with local time zone for datetime attributes also.
-If not acceptable then store all times only as datetime or timestamp in db.
-If not acceptable then split 'timeZone' in 'timeZoneTimeOnly' and 'timeZoneDateTime'
-If not acceptable change in view formatter option each time before formatting 'time'
-If not acceptable do the same as with date only already in Yii. Here Yii ignores timeZone shifting.

It's up to you. Without correction in Yii I will do option 2 or 5. But I would prefer option 6. Option two means learn to all developers never using data type 'time' in db.

I only wanted to show that time zone handling isn't that simple. Thanks for discussing.

**Comment by cebe** [comment]
Thank you for the detailed report. That is a use case I had not considered before.

**Comment by bizley** [comment]
I'm sorry, you are right. We need to check if a value is just time without date (so option 6).
