### ISSUE TITLE
Add the ability to not render empty row in GridView when dataProvider does not have any data

### ISSUE THREAD

**Issue by dkhlystov** [yiisoft/yii2#13352]
### What steps will reproduce the problem?
```php
<?= \yii\grid\GridView::widget([
	'dataProvider' => new \yii\data\ArrayDataProvider([
		'allModels' => [],
	]),
	'showHeader' => false,
	'emptyText' => false,
]) ?>
```

### What is the expected result?
`<table><tbody></tbody></table>`

### What do you get instead?
`<table><tbody><tr><td colspan="0"><div class="empty"></div></td></tr></tbody></table>`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |5.6
| Operating system |xubuntu 16.04

**Comment by developeruz** [comment]
Is it solve your problem?
```php
<?= \yii\grid\GridView::widget([
	'dataProvider' => new \yii\data\ArrayDataProvider([
		'allModels' => [],
	]),
       'showOnEmpty' => false,
	'emptyText' => '<table><tbody></tbody></table>',
]) ?>
```

**Comment by dkhlystov** [comment]
I got `<div class="empty"><table><tbody></tbody></table></div>`
And the `GridView::$layout` has not been used for rendering.

Thank you for the idea, but the solution is more like a crutch.

[Where do I want to use it](https://github.com/dkhlystov/yii2-arrayinput/blob/master/widgets/ArrayInput.php#L85)

**Comment by samdark** [comment]
How would you solve it?

**Comment by dkhlystov** [comment]
[In this place](https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L487) I would like to add something like
```php
if ($this->emptyText === false)
	return "<tbody>\n</tbody>";
```

**Comment by dkhlystov** [comment]
or add an additional condition [here](https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L486) `if (empty($rows) && $this->emptyText !== false) {`

**Comment by samdark** [comment]
Additional condition solution sounds good to me.

**Comment by SilverFire** [comment]
@dkhlystov would you like to submit a PR?

**Comment by dkhlystov** [comment]
What do you mean? What is PR?

**Comment by SilverFire** [comment]
PR is a pull request.

We have a [Git workflow for Yii 2 contributors](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md), that will help you to do it for the first time

**Comment by dkhlystov** [comment]
This is to complicated for me.

**Comment by samdark** [comment]
Then either core team or community will handle it later. Thanks for idea.

**Comment by newerton** [comment]
https://github.com/kartik-v/yii2-grid/issues/800
