### ISSUE TITLE
Incorrect BaseActiveRecord->getDirtyAttributes() work with int values

### ISSUE THREAD

**Issue by Mubat** [yiisoft/yii2#13355]
I have an conclusion to use `getDirtyAttributes()`. It return attributes that have no difference between old value in integer type, that got from DB, and new value, came from page form in string type.

### What steps will reproduce the problem?
Save integer attributes into DB. Open form again and submit it again. String numeric values came and `getDirtyAttributes()` returns array with attributes where string numeric value = old integer numeric value.
For example, classint with old value from DB `article_id` = 2 (int) and came from page form new value `article_id` = "2" (String).

### What is the expected result?
Return no integer attributes.

### What do you get instead?
Return all integer attributes.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0
| Operating system | Ubut

**Comment by samdark** [comment]
That's expected. When you're getting data from forms you have to typecast it since all these are strings by default (got by PHP as so): http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#attributes-typecasting
