### ISSUE TITLE
Migration failed.

### ISSUE THREAD

**Issue by midcore-nam** [yiisoft/yii2#13363]
### What steps will reproduce the problem?
just a simple migration returns this error
### What do you get instead?

Migration failed. The rest of the migrations are canceled.
PHP Core Warning 'yii\base\ErrorException' with message 'PHP Startup: Unable to                                                                                                                                 load dynamic library 'C:\Program Files (x86)\PHP\v7.0\ext\php_mysql.dll' - The s                                                                                                                                pecified module could not be found.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7
| Operating system | server 2012 r2 running xampp

**Comment by cebe** [comment]
This is not a Yii bug but a problem with your PHP setup. The mysql extension seems missing.
