### ISSUE TITLE
Regression: FormatConverterTest::testPHPDefaultFormat

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#13367]
There's a regression in 2.1 `FormatConverterTest::testPHPDefaultFormat` test after recent merge:

https://travis-ci.org/yiisoft/yii2/jobs/190761227

Here's the merge itself: https://github.com/yiisoft/yii2/commit/d6892d554ac80daf2bad0b11a55fe07a9804dff7

Then there are few commits fixing compatibility:

- https://github.com/yiisoft/yii2/commit/736fb099fb42fe174e1159f07b65132d8a5f7434
- https://github.com/yiisoft/yii2/commit/9eabc170ad04d2b249b28b41213958e343a13bb8
- https://github.com/yiisoft/yii2/commit/a7b9ef650cf81a90bec24287d60c8acbe6692060

**Comment by rugabarbo** [comment]
@samdark 

I propose to close this issue. Now the test is OK.
