### ISSUE TITLE
Class 'HTMLPurifier_VarParser_Flexible' not found

### ISSUE THREAD

**Issue by PeterJason** [yiisoft/yii2#13364]
### What steps will reproduce the problem?
          $test = \yii\helpers\HtmlPurifier::process($text, function ($config) {
          $config->getHTMLDefinition(true)
                 ->addAttribute('img', 'data-type', 'Text');

### What do you get instead?

> Class 'HTMLPurifier_VarParser_Flexible' not found

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |  7.0.13
| Operating system | Windows

**Comment by samdark** [comment]
Can't reproduce it:

1. Started with basic project template.
2. Added the following to `SiteController::actionIndex()` and launched the page:

```php
$test = \yii\helpers\HtmlPurifier::process('123', function ($config) {
    $config->getHTMLDefinition(true)
           ->addAttribute('img', 'data-type', 'Text');
});
```

No errors.

**Comment by PeterJason** [comment]
You are right @samdark, i tried in other project and works great. 
Do u know how can i fix it? I think is a problem with installation.
Thank you.

**Comment by samdark** [comment]
No idea what's broken so I'm afraid I can't guess it.

**Comment by lynicidn** [comment]
try composer install
break package?

**Comment by PeterJason** [comment]
@lynicidn i tried that, but everything is updated. :(

**Comment by PeterJason** [comment]
Problem solved.
If someone have same more in future, can follow this steps:

1º Install again yii2 in other location
2º Copy folder ezyang in vendor/ezyang
3º Paste in old project (replace all is ask)

Now works.
