### ISSUE TITLE
Proposal: Specify value for 'null' return value in hasOne() relation

### ISSUE THREAD

**Issue by thyseus** [yiisoft/yii2#13366]
### Problem description

Imagine you have the following common scenario:

```php
class User {  
  public function getMessages() { return $this->hasMany(User, ['recipient' => 'id']); } 
}

class Message { 
  public function getRecipient() { return $this->hasOne(User, ['id' => 'recipient']); } 
}
``` 

```php
$user = new User;
$user->name = 'Demo';
$user->save();

$message = new Message;
$message->title = 'Hello, World!';
$message->recipient = $user;
$message->save();
```

Everything fine so far:

| id | User | Message 
| --- | --- | ---
| 1 | demo | Hello, World!

Now lets imagine we remove the User:

```php
$user->delete();
```

We have following scenario:

| id | User | Message 
| --- | --- | ---
| null | null | Hello, World!

And $message->user will return null:

```php
var_dump($message->user);
-> null
```

It would be nice to be able to do something like this in this scenario:

| id | User | Message 
| --- | --- | ---
| null | 'Deleted User' | Hello, World!

This can be done this way:

```php
class Message {  
  public function getRecipientIfAvailable() {
    if(!$this->recipient)
      return 'Deleted User';
    else
     return $this->recipient;
  }
}
```

This is fine, but i propose to create something like this in ActiveRecord:

```
class Message { 
  public function getRecipient() { 
    return $this->hasOne(User, ['id' => 'recipient'])->whenNull('Deleted User'); 
  } 
}
```

With this approach, we could even pass another object or anonymous function to determine what should happen when an null value occurs.

Thanks for reading, what do you think about this? Would love to do an example implementation if the community agrees to the necessity of his feature !

**Comment by lynicidn** [comment]
it's other logic not depended with relation

**Comment by lynicidn** [comment]
public function getUserLabel()
{
return $this->user_id ? $this->user->name : 'Why Deleted? Must be New?';
}

**Comment by lynicidn** [comment]
also fk must be null (not required) - why deleted?

**Comment by thyseus** [comment]
Yes, i thought about it. Since relations return an ActiveQuery instance, this would be extremely difficult, if not impossible to implement this way.

Are there any experiences on how other ORM´s handle this issue?

**Comment by thyseus** [comment]
Issue closed, i realized it makes no sense :)

**Comment by lynicidn** [comment]
good solution ArrayHelper::getValue($this->user, 'name', 'Deleted');

**Comment by thyseus** [comment]
Wow! Great. Didn´t knew that !
