### ISSUE TITLE
cannot update with extra conditions in BaseActiveRecord

### ISSUE THREAD

**Issue by lxyfirst** [yiisoft/yii2#13365]
### What steps will reproduce the problem?
The update function in yii\db\BaseActiveRecord  is
```
public function update($runValidation = true, $attributeNames = null)
```
when execute db update operation , the default condition is the old primary key  , you cannot add extra conditions .

### What is the expected result?
It should support update with extra conditions in BaseActiveRecord .   

### What do you get instead?
maybe we can modify the original update function  or add a new function :
```  
public function updateWithCondition($extraConditions,$runValidation = true, $attributeNames = null)
```  

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by lynicidn** [comment]
update always call on exist record (model)
what is condition for record ?

**Comment by samdark** [comment]
If you call a non static update on AR instance, it is pretty logical that it will run on that instance. If you need to update more than one record or if you need extra conditions then you should use 
http://www.yiiframework.com/doc-2.0/yii-db-activerecord.html#updateAll()-detail
