### ISSUE TITLE
Resolve URL to original route & params

### ISSUE THREAD

**Issue by Tarekajaj** [yiisoft/yii2#13361]
Hello,
is there a way to resolve the original route and params of a URL?

i.e. I have the url rule `'read/<id>'=>'site/read'` I want to be able to resolve the URL `/read/10` to the original route and param `['site/read', 'id'=>10]`

is this possible? 

I can do this to the current request using `Yii::$app->getRequest()->resolve()` but I need to be able to do this for any provided URL.

Thanks.

**Comment by samdark** [comment]
Yes. You can create Request instance, set parameters needed and pass it to `Yii::$app->getUrlManager()->parseRequest($request);`.

**Comment by Tarekajaj** [comment]
```
$request = new \yii\web\Request();
$request->setPathInfo('read/10');
$routeAndParams = Yii::$app->getUrlManager()->parseRequest($request);
```
did the trick for me.
many thanks @samdark
