### ISSUE TITLE
Join tables not working in gridview 

### ISSUE THREAD

**Issue by bhattaxay** [yiisoft/yii2#13370]
### What steps will reproduce the problem?
Hello, I have a question. I have three tables in database users, userlanguage and language respectively.
I want to show user language by getting it id from userlangauage table and take the name of language from language master.

It working proper when i only show the data of users table, because i am joining that two different tables('userlangauage', 'language') in users model.

### What is the expected result?
I want to show user's language by getting languageID from userlanguage table and from that to get languagName from language table.

### What do you get instead?
When i trying to render index.php than it does not render the data of join tables.

### Additional info

modelsearch.php

```php
$query ->select([
            'user.userID',
            'user.userEmail',
            'languageName', 
            'l.languageName',
            'user.userName',
            'user.userMobile',
            'user.userGender',
            'user.userStatus', 
             ])
            ->from('users user')
            ->leftjoin('userlanguage ul', 'user.userID = ul.userID')
            ->leftjoin('language l', 'ul.languageID = l.languageID'); 
```

model.php

```php
public function getuser(){
        return $this->hasOne(Users::className(), ['userID' => 'userID']);
    }
    public function getlanguages(){
        return $this->hasOne(Language::className(), ['languageID' => 'languageID']);
    }
//    public function getuserslanguage(){
//        return $this->hasOne(Userlanguage::className(), ['userID' => 'userID']);
//    }
    public function getuserslanguage() {
        return $this->hasOne(Userlanguage::className(), ['userID' => 'userID'])->from(userlanguage::tableName() . ' FBF');
    }
```

index.php

```php
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
                  'user.userEmail:email',
                  'l.languageID',
                  'user.userName',
                  'userMobile',
                  'userGender',
                  'l.languageName',
      ['class' => 'yii\grid\ActionColumn'],
]);
?>
```

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/4143#issuecomment-47646180

**Comment by bhattaxay** [comment]
@samdark 

What kind of more info you required? I mentioned all info as above.

**Comment by Alex-Code** [comment]
Should the query be using `joinWith` to use the model relations?

**Comment by samdark** [comment]
Which model is used in `modelsearch.php` and how exactly?

**Comment by samdark** [comment]
How exactly `$dataProvider` instance is created?

**Comment by bhattaxay** [comment]
@Alex-Code 
No, I am passing it in  query=>[ ]

**Comment by bhattaxay** [comment]
@samdark 

UsersSearch.php in which i m making a leftjoin

**Comment by bhattaxay** [comment]
@samdark 

It passes all elements in array as below:

```
            'user.userID',
            'user.userEmail',
            'languageName', 
            'l.languageName',
            'user.userName',
            'user.userMobile',
            'user.userGender',
            'user.userStatus',
```

**Comment by samdark** [comment]
Would you please combine everything together starting from basic template so it's easy to reproduce?

**Comment by bhattaxay** [comment]
```
okk Now, forget that above code. Please refer this code It works the query as per i required now only remaining part is when i try to load my join table data in grid view it throw me 
Error of: Getting unknown property: backend\models\Users::languageID 
```

> Below is my code:
> 
> UsersSearch:(SearchModel)

```
$query = Users::find()->joinWith([
                'userslanguage' => function (\yii\db\ActiveQuery $query) {
                    $query->joinWith(["languages"=>function($c){$c->from("language languages");}]);
                }
            ]);
```

> Result of above query is which i required :


` `SELECT `users`.* FROM `users` LEFT JOIN `userlanguage` ON `users`.`userID` = `userlanguage`.`userID` LEFT JOIN `language` `languages` ON `userlanguage`.`languageID` = `languages`.`languageID```


> Users.php (Model)

> Below is my fuction which i used in model for join table.

```
public function getuser(){
        return $this->hasOne(Users::className(), ['userID' => 'userID']);
    }
    public function getuserslanguage(){
        return $this->hasOne(Userlanguage::className(), ['userID' => 'userID']);
    }
    public function getlanguages(){
        //Customer::findOne(123);
        return $this->hasOne(Language::className(), ['languageID' => 'languageID']);
    }
```

> index.php(GridView)
> where i have to show data which comes from my query

```
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'userEmail:email',
            'l.languageID',
            'languages.languageName',
            'userName',
            'userMobile',
            'userGender',
            ['class' => 'yii\grid\ActionColumn'],
]);
```

**Comment by samdark** [comment]
That's still not enough to reproduce the issue. I don't have tables structure, I don't have all the code etc. 

Since it's not clear what causes the issue, I can't do anything about it unless a clear way to reproduce it w/o having all your code is provided.

**Comment by bhattaxay** [comment]
okk I provide it you here

**Comment by bhattaxay** [comment]
> Users table contains following fields:

```
userID
userName
userPassword    etc.
```

> Userlanguage table contains following fields:

```
userlanguageID
userID
languageID
```

> language table contains following fields:

```
languageID
languageName
languageStatus
```


> I need to show users selected language in UsersModel

**Comment by bhattaxay** [comment]
> UsersSearch.php


`<?php

namespace backend\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use backend\models\Users;
use backend\models\Userlanguage;
use backend\models\Language;
use yii\db\Query;


class UsersSearch extends Users
{
   
    public function rules()
    {
        return [
            [['userID', 'countryId', 'userHomeCityID', 'userCurrentCityID', 'userStars', 'userFans', 'userLike', 'userNutural', 'userDontLike'], 'integer'],
            [['userEmail', 'userPassword', 'userName', 'userMobile', 'userCountryCode', 'userAbout', 'userBirthDate', 'userGender', 'userHeightUnit', 'userWeightUnit', 'userBodyColour', 'userEyesColour', 'userHairColour', 'userAdditionalInformation', 'userProfilePicture', 'userCoverPhoto', 'userLastLogin', 'userCreatedDate', 'userStatus', 'userDeviceType', 'userDeviceID', 'userType'], 'safe'],
            [['userHeight', 'userWeight'], 'number'],
        ];
    }

 
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    
    public function search($params)
    {
        $query = Users::find();


        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }
        
        $query->select("users.*,userlanguage.*,languages.*");
        $query->joinWith(["user"=>function($a){$a->from("users user");}]);
        $query->joinWith(["userslanguage"=>function($b){$b->from("userlanguage userslanguage");}]);
        $query->joinWith(["languages"=>function($c){$c->from("language languages");}]);

        
        // grid filtering conditions
        $query->andFilterWhere([
            'userID' => $this->userID,
            'countryId' => $this->countryId,
            'userBirthDate' => $this->userBirthDate,
            'userHomeCityID' => $this->userHomeCityID,
            'userCurrentCityID' => $this->userCurrentCityID,
            'userHeight' => $this->userHeight,
            'userWeight' => $this->userWeight,
            'userStars' => $this->userStars,
            'userFans' => $this->userFans,
            'userLike' => $this->userLike,
            'userNutural' => $this->userNutural,
            'userDontLike' => $this->userDontLike,
            'userLastLogin' => $this->userLastLogin,
            'userCreatedDate' => $this->userCreatedDate,

        ]);

        $query->andFilterWhere(['like', 'userEmail', $this->userEmail])
            ->andFilterWhere(['like', 'userPassword', $this->userPassword])
            ->andFilterWhere(['like', 'userName', $this->userName])
            ->andFilterWhere(['like', 'userMobile', $this->userMobile])
            ->andFilterWhere(['like', 'userCountryCode', $this->userCountryCode])
            ->andFilterWhere(['like', 'userAbout', $this->userAbout])
            ->andFilterWhere(['like', 'userGender', $this->userGender])
            ->andFilterWhere(['like', 'userHeightUnit', $this->userHeightUnit])
            ->andFilterWhere(['like', 'userWeightUnit', $this->userWeightUnit])
            ->andFilterWhere(['like', 'userBodyColour', $this->userBodyColour])
            ->andFilterWhere(['like', 'userEyesColour', $this->userEyesColour])
            ->andFilterWhere(['like', 'userHairColour', $this->userHairColour])
            ->andFilterWhere(['like', 'userAdditionalInformation', $this->userAdditionalInformation])
            ->andFilterWhere(['like', 'userProfilePicture', $this->userProfilePicture])
            ->andFilterWhere(['like', 'userCoverPhoto', $this->userCoverPhoto])
            ->andFilterWhere(['like', 'userStatus', $this->userStatus])
            ->andFilterWhere(['like', 'userDeviceType', $this->userDeviceType])
            ->andFilterWhere(['like', 'userDeviceID', $this->userDeviceID])
            ->andFilterWhere(['like', 'userType', $this->userType]);
//            ->andFilterWhere(['like', 'userslanguage.userID' => $this->userID])
//            ->andFilterWhere(['like', 'userslanguage.languageID' => $this->languageID])
//            ->andFilterWhere(['like', 'userslanguage.userlanguageDefault' => $this->userlanguageDefault])
//            ->andFilterWhere(['like', 'languages.languageID' => $this->languageID])
//            ->andFilterWhere(['like', 'languages.languageName' => $this->languageName])
//            ->andFilterWhere(['like', 'languages.languageStatus' => $this->languageStatus]);

        return $dataProvider;
    }
}
`

**Comment by bhattaxay** [comment]
> Users.php(Model)


```
<?php

namespace backend\models;

use Yii;


class Users extends \yii\db\ActiveRecord
{
    
    public static function tableName()
    {
        return 'users';
    }

    
    public function rules()
    {
        return [
            [['userEmail', 'userPassword', 'userName', 'userMobile', 'userCountryCode', 'countryId', 'userHomeCityID', 'userCurrentCityID', 'userHeight', 'userHeightUnit', 'userWeight', 'userWeightUnit', 'userBodyColour', 'userEyesColour', 'userHairColour', 'userAdditionalInformation', 'userProfilePicture', 'userCoverPhoto', 'userStatus', 'userDeviceType', 'userDeviceID', 'userType'], 'required'],
            [['countryId', 'userHomeCityID', 'userCurrentCityID', 'userStars', 'userFans', 'userLike', 'userNutural', 'userDontLike'], 'integer'],
            [['userBirthDate', 'userLastLogin', 'userCreatedDate'], 'safe'],
            [['userHeight', 'userWeight'], 'number'],
            [['userStatus', 'userType'], 'string'],
            [['userEmail', 'userPassword', 'userProfilePicture', 'userCoverPhoto'], 'string', 'max' => 100],
            [['userName', 'userHeightUnit', 'userWeightUnit'], 'string', 'max' => 20],
            [['userMobile', 'userGender', 'userDeviceType'], 'string', 'max' => 10],
            [['userCountryCode'], 'string', 'max' => 5],
            [['userAbout', 'userDeviceID'], 'string', 'max' => 500],
            [['userBodyColour', 'userEyesColour', 'userHairColour'], 'string', 'max' => 50],
            [['userAdditionalInformation'], 'string', 'max' => 4000],
            [['userEmail'], 'unique'],
            [['userName'], 'unique'],
            [['userMobile', 'countryId'], 'unique', 'targetAttribute' => ['userMobile', 'countryId'], 'message' => 'The combination of User Mobile and Country ID has already been taken.'],
        ];
    }

  
    public function attributeLabels()
    {
        return [
            'userID' => 'User ID',
            'userEmail' => 'User Email',
            'userPassword' => 'User Password',
            'userName' => 'User Name',
            'userMobile' => 'User Mobile',
            'userCountryCode' => 'User Country Code',
            'countryId' => 'Country ID',
            'userAbout' => 'User About',
            'userBirthDate' => 'User Birth Date',
            'userGender' => 'User Gender',
            'userHomeCityID' => 'User Home City ID',
            'userCurrentCityID' => 'User Current City ID',
            'userHeight' => 'User Height',
            'userHeightUnit' => 'User Height Unit',
            'userWeight' => 'User Weight',
            'userWeightUnit' => 'User Weight Unit',
            'userBodyColour' => 'User Body Colour',
            'userEyesColour' => 'User Eyes Colour',
            'userHairColour' => 'User Hair Colour',
            'userAdditionalInformation' => 'User Additional Information',
            'userProfilePicture' => 'User Profile Picture',
            'userCoverPhoto' => 'User Cover Photo',
            'userStars' => 'User Stars',
            'userFans' => 'User Fans',
            'userLike' => 'User Like',
            'userNutural' => 'User Nutural',
            'userDontLike' => 'User Dont Like',
            'userLastLogin' => 'User Last Login',
            'userCreatedDate' => 'User Created Date',
            'userStatus' => 'User Status',
            'userDeviceType' => 'User Device Type',
            'userDeviceID' => 'User Device ID',
            'userType' => 'User Type',
        ];
    }
    
    public function getUser(){
        return $this->hasOne(Users::className(), ['userID' => 'userID']);
    }
    
    public function getUserslanguage()
    {
        return $this->hasMany(Userlanguage::className(), ['userID' => 'userID']);
    }
    
    public function getLanguages(){
        
        return $this->hasMany(Language::className(), ['languageID' => 'languageID'])
            ->viaTable('userlanguage', ['userID' => 'userID']);
                
    }
    

}

```

**Comment by bhattaxay** [comment]
> index.php


```
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Users', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
  
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
           'userID',
            'userEmail:email',
            [    
                'attribute' => 'userslanguage.languageID',
                'value' => 'languages.languageID',
            ],
            'languages.languageName',
            'languages.languageStatus',
            'userName',
            'userMobile',
            'userGender',
            'userStatus',
            ['class' => 'yii\grid\ActionColumn']
});
 
?>


</div>
```

**Comment by bhattaxay** [comment]
@samdark 

I have provide you the code suggest me it's working fine but now it show me error in search model, which do not load the element of join tables.

**Comment by samdark** [comment]
OK, this info should be enough. Will get back to it after 2.0.11 release.

**Comment by bhattaxay** [comment]
okk

**Comment by bhattaxay** [comment]
Have you got any solution, which i told you as above?

**Comment by bhattaxay** [comment]
Is this a proper solution? follow the link: [http://stackoverflow.com/questions/41609092/yii2-gridview-three-tables-joins](url)

**Comment by samdark** [comment]
As I said, I'm unable to check it before 2.0.11 release.

**Comment by softark** [comment]
> ```
> // ->andFilterWhere(['like', 'userslanguage.userID' => $this->userID])
> // ->andFilterWhere(['like', 'userslanguage.languageID' => $this->languageID])
> // ->andFilterWhere(['like', 'userslanguage.userlanguageDefault' => $this->userlanguageDefault])
> // ->andFilterWhere(['like', 'languages.languageID' => $this->languageID])
> // ->andFilterWhere(['like', 'languages.languageName' => $this->languageName])
> // ->andFilterWhere(['like', 'languages.languageStatus' => $this->languageStatus]);
> ```

@bhattaxay Do you mean that the code breaks when you uncomment these lines? It's because your User model doesn't have those attributes like 'languageID', 'userlanguageDefault', ... etc.

Are you really sure it is a bug in the framework? Or, are you just asking for help in coding? If the latter is the case, this is not the place for it. Please ask your questions in the Yii framework's forum or SO.

**Comment by lynicidn** [comment]
try select('*')->,,,,,

**Comment by bhattaxay** [comment]
@softark 

> Forget that part right now. Because my issue is i got the value form database but i can not load it in my

 `gridview(index.php)`

**Comment by softark** [comment]
@bhattaxay So, I guess it's **your** issue. Please withdraw it from here, unless you are pretty sure it's an issue caused by some bug in the framework. What do you say about it?

**Comment by bhattaxay** [comment]
@samdark , @softark I found the solution which i need. Follow this below link of Yii Forum [http://www.yiiframework.com/wiki/851/yii2-gridview-sorting-and-searching-with-a-junction-table-column-many-to-many-relationship#add-comment](url)

**Comment by ErwinIbrani** [comment]
Yes
