### ISSUE TITLE
Default `$id` for `BaseDataProvider`

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#13376]
### What steps will reproduce the problem?
Add multiple dataproviders to a page, forget to set an `id`.

### What is the expected result?
Pagination works.

### What do you get instead?
Pagination works globally, all dataproviders get paged.

### Additional info
````
    /**
     * @var string an ID that uniquely identifies the data provider among all data providers.
     * You should set this property if the same page contains two or more different data providers.
     * Otherwise, the [[pagination]] and [[sort]] may not work properly.
     */
````

### Proposed solution
Why not add a default increasing id to dataproviders in the same way as we do for widgets? There is no downside to having an ID, as far as I can tell. If needed we could even have the first `id` be the empty string so there is no BC issue.

**Comment by samdark** [comment]
Do you mean multiple grids?

**Comment by SamMousa** [comment]
@samdark Yes I mean multiple grids, and thus multiple data providers; the code snippet is a source comment from  the `baseDataProvider` class.
I'd propose to implement a simple static counter that sets an id for all but the first active data provider, in the same manner it is done for widgets; this will:
- Not change anything if you have 1 provider
- Not change anything if you have 1 or more providers but they have ids.
- Add ids if you have multiple providers but have not set ids.

**Comment by samdark** [comment]
Yes. That could be a good idea.

**Comment by samdark** [comment]
Could that break anything?

**Comment by SamMousa** [comment]
If we choose the first `$id` to be `""` the I think we're fine; of course of people depend on the broken behavior then all bets are off...

Also this will not work if the order of grids is not consistent; consider a page with 5 grids that are randomly ordered then autoincrement will work unreliably but not setting ids (and thus having shared ids) will work by paging all gridviews at the same time...

**Comment by samdark** [comment]
People may rely on GET parameter names.

**Comment by SamMousa** [comment]
Yes that is why I suggest the first id to be `""`, so their parameter names won't change.

**Comment by SamMousa** [comment]
Can you confirm this is something you'd merge?

**Comment by samdark** [comment]
Yes. That's clearly a bug. I can't imagine a case when this is desired behavior so I'm all for fixing it.
