### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by ztdan4ik** [yiisoft/yii2#13371]
### What steps will reproduce the problem?
Simply you can see this short screen video http://i.de-v.net/1478867817.webm
It seems that the session is not being flushed properly after logout.

### What is the expected result?
After login it should redirect me to the prev page.

### What do you get instead?
I redirected to the logout url after login

### Additional info
I using starter kit project based yii2 advanced

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04.5 LTS

**Comment by samdark** [comment]
Could you reproduce it using basic project template?

**Comment by SilverFire** [comment]
Can not reproduce neither on the local yiisoft/yii2-app-basic installation, nor on the demo installation of trntv/yii2-starter-kit (https://github.com/trntv/yii2-starter-kit#demo)
