### ISSUE TITLE
Problem of using multiple selection in filter

### ISSUE THREAD

**Issue by DMGPage** [yiisoft/yii2#13379]
### What steps will reproduce the problem?

1. Add drop-down list that allows multiple selections to GridView filter.
2. Select some value from drop-down.
3. Select any page from grid pagination.
4. Select different value from drop-down.

### What is the expected result?
After step 4 drop-down value should be changed to new.

### What do you get instead?
Value that was selected before.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6
| Operating system | Linux

I made same test in yii2-app-advanced and here is my simple example files that must be inserted to reproduce this problem.
[frontend.zip](https://github.com/yiisoft/yii2/files/701578/frontend.zip)

**Comment by DMGPage** [comment]
Problem is very similar to this: https://github.com/yiisoft/yii2/issues/8708 and I have same url behaviour as described here: https://github.com/yiisoft/yii2/issues/8708#issuecomment-137359486

**Comment by SilverFire** [comment]
Verified

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/36960da10150e71ce19c53074e7ccc1debbf1b75
