### ISSUE TITLE
SluggableBehavior and empty $attribute value

### ISSUE THREAD

**Issue by yapi68** [yiisoft/yii2#13378]
### What steps will reproduce the problem?

```php
    /**
     * @return array
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['slug'] = [
            'class' => SluggableBehavior::className(),
            'attribute' => 'title',
            'slugAttribute' => 'code',
            'ensureUnique' => true,
            'immutable' => true
        ];

        return $behaviors;
    }
```

### What is the expected result?
SluggableBehavior should not runs if model `title` attribute is empty. In example above if value of `title` attribute is not set, value of `code` attribute should not changes.

### What do you get instead?
In example above if value of `title` attribute is not set, value of `code` attribute sets to '-2'.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10?
| PHP version      | 7.0.13
| Operating system | Debian 8.1

**Comment by cebe** [comment]
could be solved by adding a property like `$skipOnEmpty` as far as I see.

**Comment by SilverFire** [comment]
@yapi68 would you like to submit a PR?

**Comment by andrewnester** [comment]
@SilverFire I've just added PR for this feature https://github.com/yiisoft/yii2/pull/13449
