### ISSUE TITLE
Ability to set formName in model

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#13373]
Can we add the option to set the `formName` of a `model`?
I'm currently using a trait but would be handy for it to be built in.

**Comment by samdark** [comment]
Do you mean input?

**Comment by Alex-Code** [comment]
```
$model1 = new MyModel;
$model1->formName = 'MyChosenName';

echo $model1->formName; //Outputs 'MyChosenName'
```

**Comment by SDKiller** [comment]
It was already rejected 2 years ago ;(

https://github.com/yiisoft/yii2/issues/6090

**Comment by samdark** [comment]
No. If you want it, add it as a public class property yourself.

**Comment by dynasource** [comment]
@Alex-Code, what exactly is your use case for a dynamic formName?

**Comment by Alex-Code** [comment]
I've got a custom behaviour that handles model relations so when creating an `ActiveForm` I needed it to be able to set the `formName`.

**Comment by flaviovs** [comment]
I second that request. When you have more than one instance of the same model class in the same HTML form, it is not possible to distinguish (i.e. to `->load()`) them without a dummy subclass. I'm not talking about tabular input here, but things like "mainEmail", "reminderEmail", "followupEmail" being on the same form, all being of the same `Email` model, in which case `$form->field($model, 'attribute')` will generate `Email[attribute]` names for all different instances. I understand that adding another properties to `Model` is not desirable, but IMHO from an architectural perspective the "form name" property is an instance attribute (defaulting to the class name), not a class one, so this might justify the addition.

I have managed to workaround this by adding the trait below to models I anticipate might be put together with others of the same class in one single page, but it would be nice if we get some support from the framework for this.

```php
trait FormNameModelTrait
{
    protected $_formName;

    public function formName()
    {
        return $this->_formName ?: parent::formName();
    }

    public function setFormName($name)
    {
        $this->_formName = $name;
    }
}

**Comment by PELock** [comment]
This is so frustrating, having 2 forms of the same type and trying to load them in one controller action. Why not make it easier for Yii2 devs? My simplest solution is to use extra model property and override the formName() method

```php
	public $_formName;

	public function formName()
	{
		return $this->_formName;
	}
```

The best and logical solution would be to set the form name in its constructor

```php
$model_form_variant_a = new ModelForm("form-name-a");
$model_form_variant_b = new ModelForm("form-name-b");
```

**Comment by PELock** [comment]
The stubbornness of Yii2 devs leads ppl to Laravel ;)
