### ISSUE TITLE
Query causes infinite loop within framework

### ISSUE THREAD

**Issue by booba2003** [yiisoft/yii2#13383]
### What steps will reproduce the problem?
1. for component "db" set `'enableQueryCache' => true`
2. `SomeModelActiveRecord::find()->where(['>', 'int_field', time()])->min('int_field')`. Important condition: this query must return `null`

### What is the expected result?
receive `null`

### What do you get instead?
Query will be repeated many times before memory will be exhausted. If `enableQueryCache` set to `false`, bug not reproduced

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.12, 7.0.14
| Operating system | windows & debian

**Comment by TerraSkye** [comment]
Do u have a sleep in it?

**Comment by samdark** [comment]
Do you mean endless loop?

**Comment by samdark** [comment]
Could you post full code snippet please?

**Comment by booba2003** [comment]
Yes, loop is endless
```
<?php

namespace yii2portal\news;

use Yii;
use yii2portal\news\models\News;

class NewsModule extends \yii\base\Module
{

    private $_nextDelayedGlobal = -1;

    public function getNextDelayedGlobal(){

        if($this->_nextDelayedGlobal == -1){
            $this->_nextDelayedGlobal = News::find()
                ->where(['>', 'datepublic', time()])
                ->min('datepublic');
        }

        return $this->_nextDelayedGlobal;
    }


}
```

**Comment by TerraSkye** [comment]
i dont see the loop in  there?

**Comment by booba2003** [comment]
Looping occurs somewhere inside yii

**Comment by samdark** [comment]
Aha. I thought the loop was made by you :) The fact that it's within framework changes everything. Will try to reproduce it after 2.0.11 release.

**Comment by cebe** [comment]
are you using DbCache?

**Comment by booba2003** [comment]
Yes, chained
