### ISSUE TITLE
getInputId and Html::getInputId not working with tabular input

### ISSUE THREAD

**Issue by eothein** [yiisoft/yii2#13381]
### What steps will reproduce the problem?
Creating a Form with multiple models of the same type. When referencing one of the input field in the form by using `Html::getInputId` give not the adjusted id of the input type.

E.g. model = `Prices `and attribute `child `price will generate `prices-child` and not `prices-x-child `with x = the primary id of the model

### What is the expected result?
 `prices-x-child` with x = the primary id of the model

### What do you get instead?
`prices-child`

**Comment by SilverFire** [comment]
Do something like this:

```php
foreach ($models as $model) {
   $i = $model->getPrimaryKey()
   echo $form->input($model, "[$i]child");
   // Html::getInputId($model, "[$i]child"); // returns prices-14195-child
}
```

Then each field input ID will contain the primary key.

**Comment by eothein** [comment]
The fix you have writen is a local fix: if in the future Yii decides to have another way of formatting the ID's the code above won't work and Yii will not be backward compatible.
