### ISSUE TITLE
[Docs] "Multiple Attributes Validation" > "Custom validator" should be omitted.

### ISSUE THREAD

**Issue by softark** [yiisoft/yii2#13387]
There is a newly added section called "Multiple Attributes Validation" in "Validating Input" guide.
I think the first half of it is very useful, providing practical solutions for common scenarios with multiple-attribute validation.
But as for the latter half of it, I mean "Custom validator" sub-section, I think it should be omitted from the guide. It tries to show too complicated a technique for seemingly minor advantages. Some advanced developers may see it interesting, but It's not helpful for the supposed readers of the guide.

**Comment by softark** [comment]
Related with #12778

**Comment by samdark** [comment]
Do you mean https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md#custom-validator-?

**Comment by softark** [comment]
Yes, I do.
It's very interesting, but not suitable for the guide.

**Comment by samdark** [comment]
Could be moved to cookbook article...

**Comment by softark** [comment]
I agree.

**Comment by samdark** [comment]
Done. Thanks for a good suggestion.
