### ISSUE TITLE
compareValidator do not work when change selector

### ISSUE THREAD

**Issue by mohammadhosain** [yiisoft/yii2#13397]
compareValidator do not work when feild selector changed.

https://github.com/yiisoft/yii2/blob/master/framework/validators/CompareValidator.php#L250

**Comment by TerraSkye** [comment]
https://github.com/yiisoft/yii2/issues/12565
i think its the same one as this.

**Comment by SilverFire** [comment]
@TerraSkye is right.

Duplicates https://github.com/yiisoft/yii2/issues/9811
