### ISSUE TITLE
Yii2 sets incorrect date to the cache file, which creating automaticly

### ISSUE THREAD

**Issue by azazello86** [yiisoft/yii2#13398]
### What steps will reproduce the problem?

I use own class 'contentUrlRule' in 
        'urlManager' => [
            'rules' => [
				[
					'class' => 'common\components\contentUrlRule', 
				],
            ],
        ],

My class contentUrlRule  implements UrlRuleInterface. I notice that the file '963454f612a8b5fb4a63ba1e97f028a1.bin' in folder frontend/runtime/cahe/96 has wrong create date (xx-xx-xx 16.01.2018). One year more than needed. It has to be xx-xx-xx 16.01.2017.

### What is the expected result?

Correct created date

### What do you get instead?

Incorrect created date

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.4.30
| Operating system | CentOS

**Comment by rob006** [comment]
This is how FileCache works - mtime is used as cache expire date.

https://github.com/yiisoft/yii2/blob/2.0.10/framework/caching/FileCache.php#L150

**Comment by azazello86** [comment]
Thank you, very much!
