### ISSUE TITLE
Add javascript between <script> tags in BaseHtml::jsFile

### ISSUE THREAD

**Issue by mhoogstraten** [yiisoft/yii2#13415]
### What steps will reproduce the problem?
https://developers.google.com/+/web/+1button/
Add javascript between <script> tags

### What is the expected result?
<script src="https://apis.google.com/js/platform.js" async defer>{lang: 'nl'}</script>

### What do you get instead?
<script src="https://apis.google.com/js/platform.js" async defer></script>

### Additional info
BaseHtml::jsFile() has empty strings inside <script> tag (static::tag('script', '', $options)), should be an option/param to be filled. Suggestion:
```php
    public static function jsFile($url, $options = [])
    {
        $options['src'] = Url::to($url);
        $script = ArrayHelper::remove($options, 'script', '');
        if (isset($options['condition'])) {
            $condition = $options['condition'];
            unset($options['condition']);
            return self::wrapIntoCondition(static::tag('script', $script, $options), $condition);
        } else {
            return static::tag('script', $script, $options);
        }
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.2
| Operating system | Win10

**Comment by Alex-Code** [comment]
Isn't it invalid to have script within a `script` tag that also has a `src` attribute?

**Comment by cebe** [comment]
http://stackoverflow.com/questions/6528325/what-does-a-script-tag-with-src-and-content-mean#6528343 

can't you just add another tag fore the one with src?

**Comment by mhoogstraten** [comment]
I've read it, not sure if it's true. I don't know why Google is using this approach, if anyone has a clue the feedback is welcome. @cebe that's what i am using.

**Comment by dynasource** [comment]
I don't see any examples at Google with both an src & innerHtml. As @Alex-Code states, this is an unexpected practice which we prefer not to implement. You can use Yii's functions `registerJs` (Yii::$app->view->registerJs) for the innerHTML configuration objections.

This corresponds to Googles examples https://developers.google.com/+/web/+1button/#examples
