### ISSUE TITLE
Lang file for Azerbaijani language is in the wrong encoding (UTF-8 with BOM) vendor\yiisoft\yii2\messages\az.php

### ISSUE THREAD

**Issue by BumbuKhan** [yiisoft/yii2#13410]
### What steps will reproduce the problem?
Setup Azerbaijani language and try to redirect from any action
In my case:
`Yii::$app->language = 'az';`
`...`
`return $this->redirect(Url::toRoute(['site/signup', 'lang' => Yii::$app->language]));`
### What is the expected result?
Redirect to the mentioned route
### What do you get instead?
White (dead) page

I have changed the encoding of that file (**by seting it to UTF-8 without BOM**) and now redirect works fine

At least Yii has to show me that headers have already sent:
_**Cannot modify header information - headers already sent by (output started at C:\OpenServer\domains\alimok.com.loc\vendor\yiisoft\yii2\messages\az\yii.php:1)**_

P.S.
I detected that after putting a native PHP header
`header('Location: google.ru');`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.19
| Operating system | Windows 10

**Comment by samdark** [comment]
Could you fix that and make a pull request?

**Comment by andrewnester** [comment]
@BumbuKhan Hi! thanks for pointing this issue!
Let us know if you are going to create PR, otherwise I will do it myself. Thanks!

**Comment by cebe** [comment]
I think the BOM has been fixed already on master: #13298 and we now have a test that verifies no further BOMs are added: https://github.com/yiisoft/yii2/issues/13296#issuecomment-269926500
Thanks for reporting!

**Comment by BumbuKhan** [comment]
The project I currently work on doesn't use the latest varsion of framework...
Thank you guys anyway, next time I will search before creating any issue.
I love Yii2 && wish you luck
