### ISSUE TITLE
MultipartFormDataParser adds an extra newline to every value.

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#13416]
### What steps will reproduce the problem?

Send in a `multipart/form-data` request using PUT or PATCH (so that `MultipartFormDataParser` parses it.)

### What is the expected result?

The parsed body should be identical to how PHP parses it if you use POST.

### What do you get instead?

Every value has an extra newline at the end.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6
| Operating system | Debian 7

**Comment by klimov-paul** [comment]
Resolved by commit c73de31a9029d8352eeb7344c8cc6c0ffef35a75
