### ISSUE TITLE
Incorrect error message when file is too big

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/yii2#13421]
### What steps will reproduce the problem?
in model:
```
	public function rules() {
		$rules = [
			[['attachment'], 'file',
				'minSize' => 64,
				'maxSize' => 1024 * 1024 * 5,
			],
		];
	}
```

### What is the expected result?
The file "test.file" is too big. Its size cannot exceed 5 MiB.

### What do you get instead?
The file "test.file" is too big. Its size cannot exceed 2 MiB.

in code:
`{yii.validation.file(attribute, messages, {"message":"File upload failed.","skipOnEmpty":true,"mimeTypes":[],"wrongMimeType":"Only files with these MIME types are allowed: .","extensions":[],"wrongExtension":"Only files with these extensions are allowed: .","minSize":64,"tooSmall":"The file \"{file}\" is too small. Its size cannot be smaller than 64 B.","maxSize":5242880,"tooBig":"The file \"{file}\" is too big. Its size cannot exceed 2 MiB.","maxFiles":1,"tooMany":"You can upload at most 1 file."});}}`
So it seems maxSize is defined correctly, the error message is incorrect. Am I missing something?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.1.0
| Operating system | Debian 3.14.79-2~ui80+4

**Comment by SilverFire** [comment]
`FileValdator` depends not only on `maxSize` property, but on the PHP configuration.

https://github.com/yiisoft/yii2/blob/master/framework/validators/FileValidator.php#L297

Most probably the file size is limited to 2 Mb in your environment configuration.

**Comment by Thoulah** [comment]
Is there a way I can verify this?

But... let's assume you are correct, shouldn't `"maxSize":5242880` be adjusted to this value as well?
