### ISSUE TITLE
single field AjaxValidation sending all form Data

### ISSUE THREAD

**Issue by ibrahimcougar** [yiisoft/yii2#13428]
hi , on Active form when enable attr enableAjaxValidation for a single field why it send all form data to validationUrl  .Why framework do not send only that field value with csrf?
or i have some problems in using form? 

sorry for my english.

Thanks.

**Comment by SilverFire** [comment]
Sometimes the form data can not be validated separately e.g. CompareValidator. This requires us to send the whole form via AJAX, so the behavior is by design.
