### ISSUE TITLE
Blameable behaviours not updating fields

### ISSUE THREAD

**Issue by Wamae** [yiisoft/yii2#13424]
### What steps will reproduce the problem?
created a table with added_by, and updated by e.t.c.

used below in my model (also tried it without the 'blameable')

'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'added_by',
                'updatedByAttribute' => 'updated_by',
            ],

### What is the expected result?
The added by and updated by set
### What do you get instead?
Nothing

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10?
| PHP version     5.6.15 |
| Operating system | windows 10

**Comment by SilverFire** [comment]
Checked BlamableBehavior locally - works as it should. Most probably you have something wrong in your code

**Comment by SilverFire** [comment]
Added unit test to verify that behavior works as expected
https://github.com/yiisoft/yii2/commit/3d549374bf86773bbe38b550c732edb309afb0f9

**Comment by Wamae** [comment]
Thanks.Will do with that.
