### ISSUE TITLE
Unable to map controller when in subdirectory of a module

### ISSUE THREAD

**Issue by nkostadinov** [yiisoft/yii2#13433]
### What steps will reproduce the problem?

Create an "identity" module and a controller inside "controllers/api/OauthController". Try to map the controller to something else e.g.

```
    'modules' => [
        'identity' => [
            'class' => IdentityModule::className(),
            'controllerMap' => [
                'api/oauth' => '\app\controllers\OauthController',
            ],
        ],
    ],
```

### What is the expected result?

When requesting "/identity/api/oauth" to call the action from the mapped controller

### What do you get instead?

The original controller is executed. It is impossible to map a controller inside a subfolder 

| Yii version      | 2.0.11-dev
| PHP version      | 7.0.0
| Operating system | Windows

**Comment by TerraSkye** [comment]
the key of the controller  in the config cannot be api/oauth. 
normaly u would define it as ```oauth``` 
and if you want the url to be /identity/api/oauth. u would solve that through the url rules.

**Comment by SilverFire** [comment]
@TerraSkye is right.

**Comment by nkostadinov** [comment]
Well I don`t quite agree. I see no problem in defining the key of the controller including the path since its the only way to specify this controller like a namespace. Specifying only the name cannot solve the cases where I have controllers with the same name in different folders. It seems a little inconsistent to be able to only map controllers in the root of controllers folder.
What @TerraSkye proposed is just a workaround which is not the same as mapping the controller. Why is there mapping of controllers if we can solve this via url rules ?
May be I do not understand how this is gonna work, could you provide example configuration ? Just let me clarify that i have logic in the module which need to be kept, and I want to access $this->module in my controller pointing to the right module in this case 'identity'.

**Comment by TerraSkye** [comment]
your case would be a submodule. api in your identity module.

**Comment by nkostadinov** [comment]
If the framework allows controllers in subfolders there should be a way to map that. that's my point and I'm aware of all the other workarounds. I think it should just be modified to allow 'path/controller' in the map section just like it tries to find it in createController.

**Comment by TerraSkye** [comment]
But thej you will never know when to redirect to it.

I have a module named moduleA
A contoller in it :
api/auth

ModuleA has a submodule api. With a controller auth. 

Wich one gets used.?

In my opinion. The controllers should be flat as a key value manner.

**Comment by nkostadinov** [comment]
@TerraSkye the same rule applies now without the mapping. What you suggest is that controllers should only reside on one level in each module and every nesting should be done with submodules or url rules. May be you have a point but this is the situation now we are not changing anything just making it consistent.

**Comment by dynasource** [comment]
I dont see the problem in this issue. Why should the current architecture be made more complex by parsing a forward slash into a subdirectory. Way to much magic, while this is not necessary.

Why don't you use the current Module implementation (which is designated for routing)? Like this:

```php
'modules' => [
    'identity' => [
        'class' => IdentityModule::className(),
        'modules' => [
            'api' => [
                'controllerMap' => [
                    'oauth' => '\app\controllers\OauthController',
                ],
            ]
        ]
    ],
],
````

**Comment by nkostadinov** [comment]
@dynasource how is this supposed to work without the 'class' element in the module section - the controller is in a subdirectory not in a submodule. It will just throw an exception. Complexity remains the same since the fw already allows subdirectories in the controllers routed with a slash. This just makes it more consistent because it allows to override every controller via controllerMap, not just the root level controllers.

**Comment by dynasource** [comment]
> how is this supposed to work without the 'class' element in the module section

for the API module? I forgot that in my example obviously

> Complexity remains the same
we should strive to have 1 way of doing things.
