### ISSUE TITLE
Anonymous function in GridView don't work with related tables

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2#13435]
![28](https://cloud.githubusercontent.com/assets/16696651/22236688/8669b934-e207-11e6-8e29-671d449db597.png)
| Yii version      | 2.0.10

and normally works with not joined tables.

**Comment by TerraSkye** [comment]
it is ```$data->user->photo``` and not : ```$data->user.photo```

**Comment by bashkarev** [comment]
and see the syntax [Html::img](http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#img()-detail) `alt` must be in the options

**Comment by rumatakira** [comment]
$data->user->photo 
![29](https://cloud.githubusercontent.com/assets/16696651/22319161/957c8b0c-e380-11e6-9757-d6ae27f3919a.png)
or  $data->user.photo - the same result:

**Comment by rumatakira** [comment]
It works only by this way:
```php           
[
     'attribute' => 'user.photo',
     'format' => 'raw',
     'value' => function($data) {
          $tmp = $data->user->photo;
          return Html::img("data:image/png;base64, $tmp", ['class' => 'img-responsive', 'alt' => 'User photo']);
     },
]
```

**Comment by samdark** [comment]
That's PHP to you.
