### ISSUE TITLE
MSSQL DB session doesn't work

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#13436]
See https://github.com/yiisoft/yii2/issues/12599#issuecomment-274663294

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | any
| Operating system | any

**Comment by andrekociuba** [comment]
Hi,
I just modified the field 'data' to type varchar(max) and works

**Comment by njasm** [comment]
PHP 7.1.10
Yii 2.0.12
SQL Server 2017
DbSession

having problems decoding session from DbSession on MS SQL with [data] column as VARBINARY(MAX).
session decode is Failing. changed the datatype to nvarchar(max) and it seems to be working..

**Comment by bscheshirwork** [comment]
:checkered_flag: 
Happy Halloween!
:jack_o_lantern: 

![peek 2017-10-31 14-06](https://user-images.githubusercontent.com/5769211/32221043-11241e74-be45-11e7-9734-2a39a2480ead.gif)
