### ISSUE TITLE
 Is it possible not to add HostInfo in function response->redirect()?

### ISSUE THREAD

**Issue by neilqin** [yiisoft/yii2#13447]
when use nginx for proxy, is nginx listen port is not 80 or 443 and nginx set Host is like this : proxy_set_header Host $host;

so in backend server apache is can not get the right server_port, so redirect is wrong,

in this problem is know my nginx set is Incorrect, but i can not change it , so i test it ,remove HostInfo， response->redirect() is ok ,

i want to know if function response->redirect can not auto add hostinfo to url?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
It can but we won't make the change in the framework since it's a special case. Extend response component and customize as needed.
