### ISSUE TITLE
ActiveField with $options['tag'=>false] outputting empty (not valid) tag.

### ISSUE THREAD

**Issue by tonykor** [yiisoft/yii2#13445]
### What steps will reproduce the problem?
```
$form = ActiveForm::begin([
    'id'          => 'create',
    'fieldConfig' => [
        'template'=>'{label}<br>{input}{hint}{error}',
        'options' => [
            'tag'=>false,
        ],
    ],
]); ?>

<?= $form->field($model, 'name')->textInput(['maxlength' => true]); ?>
```
### What is the expected result?
`<label class="control-label" for="object-name">Name</label><br><input type="text" id="object-name" class="form-control" name="Object[name]" maxlength="150"><div class="help-block">`
### What do you get instead?
```
< class="field-object-name required">
<label class="control-label" for="object-name">Name</label><br><input type="text" id="object-name" class="form-control" name="Object[name]" maxlength="150"><div class="help-block"></div>
</>
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?

**Comment by Alex-Code** [comment]
You can only change the tag, not omit it.

Do you have a use case for trying to remove it?

**Comment by samdark** [comment]
Have you tried latest master code?

**Comment by tonykor** [comment]
@Alex-Code documentation say that when the value is false, the container tag will not be rendered at all.

http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#$options-detail

@samdark No, i'm using 2.0.6

**Comment by samdark** [comment]
Well, upgrade.

**Comment by samdark** [comment]
The issue was fixed. Either it's in 2.0.10 or in 2.0.11 which is to be released.

**Comment by samdark** [comment]
Should be #11949 which is part of 2.0.10.

**Comment by tonykor** [comment]
ok, thanks. Sorry for disturbing.
