### ISSUE TITLE
Pjax default linkSelector

### ISSUE THREAD

**Issue by Enkey** [yiisoft/yii2#13448]
Sometimes inside Pjax container I want to have a link without any listener and I solve the problem in this way:
```php
<?php Pjax::begin([
    'id' => 'list',
    'linkSelector' => '#list a:not([data-pjax=0])'
 ]); ?>
<a href="#" id="customListener" data-pjax="0">custom js or simple link</a>
<a href="some/link">pjax link</a>
<?php Pjax::end(); ?>
```

I do it because in Pjax widget default value of link selector is `'#' . $id . ' a'`
So I propose to make default link selector to: `'#' . $id . ' a:not([data-pjax=0])'`

Or may be I can achieve the same goal in other way?
Thanks.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by Alex-Code** [comment]
Could you expand on the issue you're having?
Pjax will ignore click events for any links with `[data-pjax=0]`, https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L78

**Comment by Enkey** [comment]
Hi, @Alex-Code , Sorry, I understand what was the trouble. I use jquery 3 and i copy a version of jquery.pjax for this version (https://gist.github.com/oh-ren/7afed121c2cd29993bd26c996fc6f501). In source code as you can see wast't ignored `[data-pjax=0]`. So may be PR was unnecessary, i can just change my local version of jquery.pjax.

**Comment by samdark** [comment]
We have our own fork of pjax so we can't guarantee other forks work well. Sorry.
