### ISSUE TITLE
Static form controls

### ISSUE THREAD

**Issue by grachov** [yiisoft/yii2#1344]
In case of so deep integration with Bootstrap 3 maybe it has sense to add support of [form static controls](http://getbootstrap.com/css/#forms-controls-static) because they are very close by markup to the regular form fields except the paragraph is used instead of the input? It should be useful when some attribute should be rendered as non-editable value.

**Comment by lukBarros** [comment]
I never understood Why Things As label , badges OR panels have not been mapped As widgets?

By Simplicity ? I'm stronger SUPPORT All Written in the form of widgets , THAT abstre Quite the boot do deenvolvedor , or almost 100 % , leaving ONLY html para gridar The Screen and Elements scheme.

Fact already open hum suggesting THAT ticket not Correspondent design , but could not agree .

See yiisoft/yii2-bootstrap/#26

**Comment by klimov-paul** [comment]
I suppose 'static controls' is not the only thing you are missing.
It whould be nice to have a list of similar features to consider.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-bootstrap/pull/34

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-bootstrap/issues/43
