### ISSUE TITLE
dynamic subdomain route not work in php7.0

### ISSUE THREAD

**Issue by skvarovski** [yiisoft/yii2#13440]
### What steps will reproduce the problem?
use route 'http://<<param1:\w+>>.site1.ru/<<param2:\w+>>' => 'supp/view',

### What is the expected result?
route not work

### What do you get instead?
i have not correct url for Yii2

### Additional info
on Win10+openServer via php 5.6 all work correctly 

use \yii\helpers\Url::to(['/supp/view','param1'=>$model['param1'],'param2'=>$model['param2']])

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.15
| Operating system | Ubuntu LTS 16.04.1

**Comment by skvarovski** [comment]
add example into info

**Comment by rob006** [comment]
Could you show values of `$model['param1']` and `$model['param2']`?

**Comment by skvarovski** [comment]
param1 & param2 is row on Model. But Win10+php5.6 work correctly and route make correct URL aka para1.site1.ru/param2

**Comment by samdark** [comment]
What's the result when using PHP7?

**Comment by skvarovski** [comment]
result in ubuntu lts16   - PHP7 i see link <a href="/supp/view?param1=aaa&param2=bbb">....</a>
result in win10+PHP5.6  - all normal ... as right <a href="param1.site1.ru/param2">...</a>

**Comment by dynasource** [comment]
issue confirmed locally with PHP 7.1.2-dev. It seems that the basePath is inserted.

Example:
`$this->rules['http://www.example.com/custompage'] = 'article/index'` 

So instead of 
`http://www.example.com/custompage`

A link with a basePath is created:
`http://www.example/whatever-basepath-i-am-at/custompage`

**Comment by cebe** [comment]
That is expected behavior and documented: check the "Note" on http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#rules-with-server-names

**Comment by cebe** [comment]
@skvarovski please provide the following information:

- full urlManager config on both systems
- the yii version you use on both systems

**Comment by SilverFire** [comment]
@skvarovski we are waiting for you input in order to solve your problem.

please provide the following information:

- full urlManager config on both systems
- the yii version you use on both systems

**Comment by chhbunrath** [comment]
how can I create dynamic sub domain in rules?
