### ISSUE TITLE
Unexpected behavior with Yii::$app->response->headers->set('Content-Type','application/pdf')

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#13450]
### What steps will reproduce the problem?

Yii::$app->response->headers->set('Content-type', '**application/pdf**');

...
I was trying to use http://demos.krajee.com/mpdf and it didn't work so i thought that there is a problem with the extension for not rendering the pdf, but instead sending result in text/html. than i explicitly set the response headers and still no luck

### What is the expected result?

in the browser i should get 

Content-Type:**application/pdf**

### What do you get instead?

Content-Type:**text/html**

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11-dev
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
You should set response type to RAW.
