### ISSUE TITLE
Change assets dependency while creating

### ISSUE THREAD

**Issue by mhoogstraten** [yiisoft/yii2#13456]
### What steps will reproduce the problem?
```php
$asset = new \common\assets\TextExpanderAsset();
$asset->depends[] = 'common\themes\fancy\Asset';
$asset::register( $this );
```

### What is the expected result?
```html
<link href="/web/assets/bfaa24ff/css/expander.css?v=1485522608" rel="stylesheet">
<link href="/web/css/theme.css?v=1485522609" rel="stylesheet">
```

### What do you get instead?
```html
<link href="/web/css/theme.css?v=1485522609" rel="stylesheet">
<link href="/web/assets/bfaa24ff/css/expander.css?v=1485522608" rel="stylesheet">
```

### Additional info
TextExpanderAsset its depency is never the same, it is used by theme and by widget. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.3
| Operating system | Win10

**Comment by mhoogstraten** [comment]
Had no markdown, html text is now visible

**Comment by samdark** [comment]
Please provide code for these asset bundles. It's not clear how these are configured now.

**Comment by cebe** [comment]
> $asset::register( $this );

this does not work, `register` is a static method and has no idea of object context.

To customize bundle settings you have to set them on the asset manager's $bundles property.

http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#customizing-asset-bundles

**Comment by mhoogstraten** [comment]
I know it does not work that way, but in some cases it would be handy for re-usablity 

```php
class TextExpanderAsset extends AssetBundle
{
    public $sourcePath = '@common/assets/plugins/text-expander';
    public $css = [
        'css/expander.css',
    ];
    public $js = [
        'js/expander.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'common\assets\BootstrapAsset',
    ];
}
```

This AssetBundle is standard, but we use it for different domains. This bundle will be loaded when TextExpanderWidget is called. Usually this works, but now we have a custom view that inherits the basic view and it needs an order on how the assets are loaded. Now I could make a custom Asset bundle which i load inside that template with the appropriate order, but it would be nicer if we could change the dependencies before registering.

**Comment by cebe** [comment]
check the docs I linked, you can already do this.

**Comment by mhoogstraten** [comment]
How would the approach be? Like this(?):
```php
    public function init()
    {
        parent::init();
        if($_SERVER['HTTP_HOST'] == 'domain1.com')
                $this->depends = [
                       'yii\web\YiiAsset',
                       'common\assets\BootstrapAsset',
                       'common\assets\TextExpanderAsset',
                ];
        elseif($_SERVER['HTTP_HOST'] == 'domain2.com')
                $this->depends = [
                       'yii\web\YiiAsset',
                       'common\assets\TextExpanderAsset',
                       'common\assets\BootstrapAsset',
                ];
        elseif($_SERVER['HTTP_HOST'] == 'domain3.com')
                $this->depends = [
                       'yii\web\YiiAsset',
                       'common\assets\TextExpanderAsset',
                       'common\assets\BootstrapAsset',
                ];
        elseif($_SERVER['HTTP_HOST'] == 'domain4.com')
                $this->depends = [
                       'yii\web\YiiAsset',
                       'common\assets\TextExpanderAsset',
                       'common\assets\BootstrapAsset',
                ];
        elseif 
                //etc.
    }
```
