### ISSUE TITLE
Pjax suddenly broken

### ISSUE THREAD

**Issue by robov** [yiisoft/yii2#13464]
Apparently I upgraded to 2.0.11-dev and now my pjax/ajax opens in a new window instead of the right place
Can I revert back to 2.0.10 ?

**Comment by robov** [comment]
I can show it in my live dev site... I can share you the login... but that needs to be private

**Comment by samdark** [comment]
It is much better to provide a way to reproduce it starting from basic application template.

**Comment by robov** [comment]
I understand... but that would require me to actually write that application... I just noticed that my app broke after the update

**Comment by robov** [comment]
I am now looking to see if I can find more info
I do have some errors while updating composer
```

    - yiisoft/yii2 2.0.9 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.10 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.

```
I did a upgrade on min stability dev, and after that changed it back stable and ran composer... then I got these errors

**Comment by licanulla** [comment]
With the upgrade to 2.0.10 activeforms are not submitted at all via pjax. No ajax call is made. I see many commits to related files but had no time to investigate. Downgraded to 2.0.9 and it's working again.

**Comment by cebe** [comment]
@licanulla can you try with the latest master? Also, if it is not fixed on master, a `git bisect` search would be awesome to find the breaking commit.

**Comment by robov** [comment]
After destroying my vendor folder and composer update to 2.0.10 everything worked again...
