### ISSUE TITLE
Documentation request: Add description for using the `add_column_to_table` migration syntax for adding multiple columns

### ISSUE THREAD

**Issue by kanyuga** [yiisoft/yii2#13466]
The documentation does not indicate that you can use the `add_column_to_table` syntax to add multiple columns to a table.

From http://stackoverflow.com/a/41920364/428543:

> It isn't clear from the docs but you can create multiple columns in one migration:
> `yii migrate/create add_xxx_column_yyy_column_to_zzz_table --fields="xxx:integer,yyy:text"`

**Comment by samdark** [comment]
Fixed. Thanks!
