### ISSUE TITLE
other point to entry for static route - not work.

### ISSUE THREAD

**Issue by skvarovski** [yiisoft/yii2#13474]
### What steps will reproduce the problem?
make clone index.php and add
$application->defaultRoute='site/login';
$application->requestedParams=['param1'=>'aaa','param2'=>'bbb'];
$application->run();

### What is the expected result?
use static route & requestParams for Action

### What do you get instead?
if 'enablePrettyUrl' => true - not work and render site/index
if 'enablePrettyUrl' => false - roure work, but without param 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6
| Operating system | Win10

**Comment by cebe** [comment]
> make clone index.php and add
> $application->defaultRoute='site/login';
> $application->requestedParams=['param1'=>'aaa','param2'=>'bbb'];
> $application->run();

this is not supposed to work this way. requested route and parameters are determined based on the `request` component which reads information from `$_SERVER` variable.

What are you trying to do?

**Comment by skvarovski** [comment]
due to the fact that the problem with the subdomains for my calculation will be determined more than six months (very Problem https://github.com/yiisoft/yii2/issues/13440).

make other point to entry.

**Comment by cebe** [comment]
closing this as a duplicate then.

**Comment by skvarovski** [comment]
no, is not duplicate. is other way for making other point to entry, when first way not work

**Comment by cebe** [comment]
Sorry but I do not understand what you are trying to do here. Please provide more detailed information on the problem.
