### ISSUE TITLE
Yii2 does not call actions in controller's behavior

### ISSUE THREAD

**Issue by dslpp056193** [yiisoft/yii2#13473]
I think it will be very good, if behavior's actions in controller were calling like a controller's actions.

**Comment by derekisbusy** [comment]
It might also be worth adding similar functionality to modules the applications as well. One advantage of using this with application behaviors is that it would allow extensions to integrate with other more cleanly. For example an extension could attach a single behavior to the application that can then add modules, controllers, actions and events as needed.

**Comment by samdark** [comment]
What's your use case for it?

**Comment by samdark** [comment]
See discussion in a pull request.
