### ISSUE TITLE
UniqueValidator with two targetAttribute not work after update

### ISSUE THREAD

**Issue by orcoliver** [yiisoft/yii2#13475]
Hi,
In a model i have

```php
[['reo_orden',` 'reo_articulo'], 'unique', 'targetAttribute' => ['reo_orden', 'reo_articulo'], 'message' => 'El articulo ya está `cargado.'],
```

Before update the debugger show:

```sql
SELECT EXISTS(SELECT * FROM `cop_renord` WHERE (`reo_orden`='14') AND (`reo_articulo`='001401239'))
```

After update:

```sql
SELECT EXISTS(SELECT * FROM `cop_renord` WHERE (`reo_orden`='14') AND (`reo_articulo`='14'))
```

Composer update output:

```
Updating yiisoft/yii2 dev-master (03e0607 => 221603a) Checking out 221603ae2c
```

composer.json after update:

```json
"minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.5",
```

PHP version: 5.6.22

Thks for help.

**Comment by Alex-Code** [comment]
Could be from this change, https://github.com/yiisoft/yii2/commit/b82caa97e82ff8b99389b56958fb1e1310637c4b#diff-b7eeda2fac6ce8131377ce36953a329aR227

**Comment by developeruz** [comment]
targetAttribute related to validate attribute if another isn't set. 
`[['reo_orden', 'reo_articulo'], 'unique', 'targetAttribute' => ['reo_orden', 'reo_articulo' => 'reo_articulo'], 'message' => 'El articulo ya está cargado.'],`

**Comment by cebe** [comment]
> 'reo_articulo' => 'reo_articulo'

this was equal to simply specifying `'reo_articulo'`, is that still the case? If not, we should fix that.

**Comment by developeruz** [comment]
Here the PR for fix BC, but I believe the current simplifying is wrong, it makes people confusing. Please look at #7820 
If I have written:
`
[ 'attr1',  'unique', 'targetAttribute' => ['attr2', 'attr3'] ],
`
current simplifying mean `'attr2' => 'attr2' and 'attr3' => 'attr3'`. The reasonable question is where attr1 is used even if `unique` specified for attr1? I suggest use simplifying like `'attr1' => attr2` if another is not specified. @cebe, if you agree with this I will create PR and mark it as BC breaking.

**Comment by cebe** [comment]
@developeruz thanks for the fix! I think it will be more confusing, if we implicitly add a key that is different from the value. As far as I see, the current behavior is okay. Also the case where the attribute that receives the error message is not among the targetAttributes is very rare.

**Comment by orcoliver** [comment]
Thank you for help. This is working again.
