### ISSUE TITLE
how to set security flags (httpOnly and secure) for ALL cookies

### ISSUE THREAD

**Issue by leetas** [yiisoft/yii2#13486]
### What steps will reproduce the problem?
set custom cookies with Yii2

### What is the expected result?
All cookies has httpOnly and secure

### Additional info
My code:
```
'components' => [
        'session' => [
            'cookieParams' => [
                'httpOnly' => true,
                'secure' => true
            ]
        ],
        'cookies' => [
            'class' => 'yii\web\Cookie',
            'httpOnly' => true,
            'secure' => true
        ],
        'request' => [
            ....
            'csrfCookie' => [
                'httpOnly' => true,
                'secure' => true
            ]
        ],
        'user' => [
            ....
            'identityCookie' => [
                'name' => '_identity',
                'httpOnly' => true,
                'secure' => true,
            ],
        ],
```
1. I get session, csrf and identity cookies with required flags, but maybe possible set it with one config line?
2. All my custom cookies are without security flags. How to config Yii2 that all my cookies which I created with `Yii::$app->request->cookies;` will have security flags by default?

**Comment by samdark** [comment]
There is currently no way to set defaults application-wide. Instantiation could go through dependency container. Then it would be possible.
