### ISSUE TITLE
Errors while following the instructions from "Asset processing with Grunt"

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#13483]
### What steps will reproduce the problem?

D:\web\www\marelin\app>npm install -g grunt-cli
C:\Users\Anton\AppData\Roaming\npm\grunt -> C:\Users\Anton\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt
C:\Users\Anton\AppData\Roaming\npm
`-- grunt-cli@1.2.0

D:\web\www\marelin\app>npm install grunt --save-dev
npm WARN saveError ENOENT: no such file or directory, open 'D:\web\www\marelin\app\package.json'
D:\web\www\marelin\app
`-- UNMET PEER DEPENDENCY grunt@1.0.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'D:\web\www\marelin\app\package.json'
npm WARN grunt-concat-sourcemap@0.4.3 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-typescript@0.8.0 requires a peer of grunt@~0.4.5 but none was installed.
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.
npm ERR! code 1
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11-dev
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
That's definitely not Yii issue but config issue w/ grunt. You can open your issue at https://github.com/samdark/yii2-cookbook which is more appropriate place...
