### ISSUE TITLE
UniqueValidator breaking for non-SQL ActiveRecord

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#13485]
See https://github.com/yiisoft/yii2-mongodb/issues/180

**Comment by cebe** [comment]
This line was compatible with the interfaces before, but now requires a specific implementation:

https://github.com/yiisoft/yii2/blob/72a690216a7165be1402271db353199044218d7f/framework/validators/UniqueValidator.php#L163

cc @developeruz 

We should add an instanceof check there.

**Comment by klimov-paul** [comment]
`ActiveQueryInterface::asArray()` should be used at that line instead of `createCommand()` usage.

**Comment by cebe** [comment]
`select()` is also not provided by some implementations such as redis.

**Comment by samdark** [comment]
@klimov-paul `asArray()` does not prevent `afterFind()`. See https://github.com/yiisoft/yii2/issues/13453

**Comment by cebe** [comment]
@samdark `afterFind()` is not called on an array...

**Comment by samdark** [comment]
Right.

**Comment by klimov-paul** [comment]
`select()` can be avoided at all

**Comment by cebe** [comment]
it was added for optimization.

**Comment by klimov-paul** [comment]
I have noticed

**Comment by klimov-paul** [comment]
Still either it should belong `QueryInterface` or removed from validator.

**Comment by cebe** [comment]
`$query instanceof \yii\db\ActiveQuery` can be done. I am working on a solution.

**Comment by developeruz** [comment]
`$query` always [instanceof ActiveQuery](https://github.com/yiisoft/yii2/blob/72a690216a7165be1402271db353199044218d7f/framework/validators/UniqueValidator.php#L197)  or not?

**Comment by samdark** [comment]
@developeruz nope https://github.com/yiisoft/yii2-mongodb/blob/master/ActiveQuery.php

**Comment by cebe** [comment]
@developeruz no, it can be an instance of mongodb, elasticsearch or redis query. the only thing they have in common is ActiveQueryInterface.

**Comment by samdark** [comment]
The fix looks good to me.

**Comment by cebe** [comment]
It is good but it is not enough. I am working on tests for redis and elasticsearch.

**Comment by cebe** [comment]
@developeruz I have included your fix in #13487. Thank you!
