### ISSUE TITLE
Persistent PHP process and Yii2 Logger

### ISSUE THREAD

**Issue by adrianofoschi** [yiisoft/yii2#13490]
### What steps will reproduce the problem?
Start a PHP persistent process (ie. a PHPWebSocket) with Yii2 console command and useYii:info('text') to log something
### What is the expected result?
Yii write the log file at runtime
### What do you get instead?
The log it's written on file only if I kill the PHP process

### Additional info
I'm using PHPSocketIO library. I'm starting the process into a console across a Yii2 Console Controller command.

**Comment by TerraSkye** [comment]
You can configure to flush after 1 message is output

**Comment by cebe** [comment]
logs are exported after 1000 items are written by default, as @TerraSkye said, you need to configure the flushInterval to have messages written earlier.

**Comment by adrianofoschi** [comment]
Thanks you.
