### ISSUE TITLE
yii\db\Expression in console\controllers\MessageController

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#13494]
https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/MessageController.php#L456

```php
$db->createCommand()
    ->update(
        $sourceMessageTable,
        ['message' => new \yii\db\Expression("CONCAT('@@',message,'@@')")],
        ['in', 'id', $obsolete]
    )->execute();
```
For MySQL, MsSQL, CUBRID
```
"CONCAT('@@',message,'@@')"
```

For SqLite3, PostgreSQL
```
"'@@' || message || '@@'"
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      |  7.0
| Operating system | Linux

**Comment by SilverFire** [comment]
@LAV45 we will be thankful if you can submit a PR.

**Comment by LAV45** [comment]
OK, I'll try to send PR soon.
