### ISSUE TITLE
yii\base\Model::load() misleading documentation or doesn't treat form's name correctly

### ISSUE THREAD

**Issue by KalmanBodor** [yiisoft/yii2#13491]
I was trying this:

```
//model
use yii\base\Model;

class EntryForm extends Model
{
    public $name;
    public $email;
    public function rules() {
		return [ [ [ 'name', 'email' ], 'required' ] ];
    }
}

//controller
$model->load(Yii::$app->request->post());
```

I was expecting $model to be populated, even if I'm not sending the form's name, but I always got an empty one.
I tried naming my form in the view, and specifying the name of the form when calling load(), didn't help (but I might have been missing something in this case).

Digging into the base Model, I saw that load() was checking for the name of the form, but $scope always got a value, so it never entered the branch where the form's name is an empty string (line 822), where it would set the attributes for the whole $data.

I ended up calling load with en empty string as the form's name:
`$model->load(Yii::$app->request->post(), '');`
In this was I got my model populated.

Is this a bug in the code or the documentation should specify that for unnamed forms and empty string must be passed?

Thanks!

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10, Avanced template
| PHP version      |5.5.9-1ubuntu4.20
| Operating system |Linux yii 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64

**Comment by rob006** [comment]
Try:
```php
class EntryForm extends Model
{
    public function formName() {
        return '';
    }

    public $name;
    public $email;
    public function rules() {
		return [ [ [ 'name', 'email' ], 'required' ] ];
    }
}

**Comment by samdark** [comment]
It is expected to work like that so it seems that docs may be unclear about the case.

**Comment by samdark** [comment]
Checked docs and both explanation and guide mention `formName`.

**Comment by dynasource** [comment]
this usecase shows room for improvement. The current implementation is not obvious enough.
