### ISSUE TITLE
Pjax missing id

### ISSUE THREAD

**Issue by hdewaart** [yiisoft/yii2#13492]
in vendor/yiisoft/yii2/widgets/Pjax.php line 206.
I'm missing the \"#$id\".
I think the line should be
`jQuery(document).pjax($linkSelector, \"#$id\", $options);`

Without this id pjax is running once in a modal.
When refreshing the page and open the modal pjax is ruuning fine.
But closing the modal and opening it again, pjax is not running anymore.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.4.16
| Operating system | Linux

**Comment by derekisbusy** [comment]
```php
jQuery(document).pjax($linkSelector, \"#$id\", $options);
```
This line shouldn't matter as it get treated the same as:
```php
jQuery(document).pjax($linkSelector, $options);
```

You need to rebind the click events when the modal opens because they get unbound when the modal closes.

```php
$('#myModal').on('show.bs.modal', function (e) {
    jQuery(document).pjax($linkSelector, $options);
})
```

**Comment by samdark** [comment]
@derekisbusy is correct.

**Comment by hdewaart** [comment]
When I  roleback this fix "h0ckeypl4yer Fix Pjax container" on 10a2954  on Apr 13, 2016.
My Modal containers are working!
Seems to be breaking BC

**Comment by samdark** [comment]
@SilverFire can you take a look?

**Comment by dynasource** [comment]
I recall this commit indeed to change the behavior of the Pjax widget. Before the widget worked without a custom ID. More info at https://github.com/yiisoft/yii2/issues/12919.

With respect to the modal. Once the Pjax container is removed, either by Pjax itself or by a Modal implementation, the developer is responsible for rebinding. For this a customized ID is required to have a match between local & server.

**Comment by derekisbusy** [comment]
@hdewaart Did you have `'clientOptions' => ['container' => ... ]` set to a value that's different from the id. This is the only thing I see that would change the behavior in update 10a2954. What does your pjax widget call look like?

**Comment by derekisbusy** [comment]
@hdewaart Also did you move your modal and pjax widget to the layout file? Pjax doesn't work properly when called in the layout file.

**Comment by dynasource** [comment]
> Pjax doesn't work properly when called in the layout file.

this depends on:
* the complexity of your Application code
* whether you are using the latest Yii2 release 2.0.11 (which is improved on stability on pjax widgets in layouts)

**Comment by dynasource** [comment]
see https://github.com/yiisoft/yii2/pull/13545#issuecomment-280837915
