### ISSUE TITLE
release command improvements

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#13502]
Release command currently has a few minor issues:

- [ ] on patch release it does not adjust the changelog correctly on prepare
- [ ] on patch release the next version is wrong, e.g. 2.0.12.1 is the next after 2.0.11.1 while it should be 2.0.12
- [ ] on packaging apps, it should verify the yii version that got installed by composer
- [ ] as an additional check `git verify-commit HEAD` and `git tag --verify 2.0.11` could be run after creating commits and tags to verify the signing works correctly.

**Comment by samdark** [comment]
Not critical for 2.0. Won't do.
