### ISSUE TITLE
Double attach of behavior in \yii\base\Component::attachBehaviorInternal() BC break

### ISSUE THREAD

**Issue by paulzi** [yiisoft/yii2#13508]
See:
https://github.com/yiisoft/yii2/commit/954c771fdbd867500bc5de8498a3a7453716a74a?diff=split#diff-d45d5e14cbb9739c2e1c63b53ba5e363L669

### What steps will reproduce the problem?
Attach behavior in `behaviors()` to model without key:
```php
/**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            [
                'class' => 'common\behaviors\I18nBehavior',
            ],
        ];
    }
```

### What is the expected result?
Behavior::attach() is called once.

### What do you get instead?
Behavior::attach() call twice.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.1
| PHP version      | 5.6
| Operating system | ubuntu

**Comment by cebe** [comment]
There is now a 2.0.11.2 release including this fix. https://github.com/yiisoft/yii2/blob/2.0.11.2/framework/CHANGELOG.md#20112-february-08-2017
