### ISSUE TITLE
BaseListView: pass widget to pager

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#13504]
This is a very simple enhancement request.

Many custom pagers (eg. InfiniteScroll) rely on their parent container (ListView) to function correctly. For example they may need to extract the ListView widget's ID value to correctly inject new items.

In BaseListView [`renderPager()`](https://github.com/yiisoft/yii2/blob/25eafa560ec1dbcff606bccedd56abd66a8b9339/framework/widgets/BaseListView.php#L236) when creating the LinkPager object, pass the BaseListView widget (`$this`) to it as well.

**Comment by samdark** [comment]
I've implemented infinite scroll that works for lists before and I don't remember if there was a need to have ListView object in LinkPager... would you please elaborate why it's needed?

**Comment by vercotux** [comment]
In case of infinitescroll we do not need the entire ListView object. The critical part is the ListView's `options['id']` value, which as we know is typically auto-generated. The ID is eventually used by the infinite scroll widget in order to locate the item container and inject new items.

For a real world example, have a look at [this](https://github.com/nirvana-msu/yii2-infinite-scroll). Notice how we need to manually set the ListView ID and then duplicate it by passing it yet again to the pager. This could be avoided entirely if the pager was able to somehow access the parent ListView (or at least the ID).

**Comment by samdark** [comment]
We can get container element using `parents()` even w/o knowing its ID. Passing ID around for this special case, in fact, looks good to me. Better than coupling these two not directly related widgets. I'm against introducing the change.

**Comment by dynasource** [comment]
it won't be a bad idea to change https://github.com/yiisoft/yii2/blob/25eafa560ec1dbcff606bccedd56abd66a8b9339/framework/widgets/BaseListView.php#L244 towards a DIC implementation so that users can define their own linkpager class
