### ISSUE TITLE
ui Dialog bootstrap require ?

### ISSUE THREAD

**Issue by i-skiba** [yiisoft/yii2#13505]
### What steps will reproduce the problem?
Now Dialog requires bootstrap.js because in init method 

```
namespace yii\jui;

class Dialog extends Widget
{
....

public function init()
    {
        parent::init();
        echo Html::beginTag('div', $this->options) . "\n";
        
        //Fix for closing icon (x) not showing up in dialog
        $this->getView()->registerJs("
            var bootstrapButton = $.fn.button.noConflict(); 
            $.fn.bootstrapBtn = bootstrapButton;", 
            \yii\web\View::POS_READY
        );
    }
.....
}

```
after update to 2.0.11 our project throws javascript exception 

```

 is not function a $.fn.button.noConflict()

```
 

### What is the expected result?

But we dont use bootstrap in our project

### What do you get instead?
Please, back clear  init without any js 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6
| Operating system | Debian

**Comment by cebe** [comment]
@samdark this is more of a jui issue related to the fix merged yesterday.
