### ISSUE TITLE
SCHEMA OCI RBAC YII2

### ISSUE THREAD

**Issue by jdgonzalez907** [yiisoft/yii2#13513]
### What steps will reproduce the problem?
Migration for create rbac in ORACLE 11g
### What is the expected result?
The tables for rbac
### What do you get instead?
Nothing

### Additional info
See http://www.yiiframework.com/forum/index.php/topic/73769-migration-rbac-in-oracle11g-and-yii2/page__gopid__306998#entry306998

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.0
| Operating system | Windows server 2012 r2

**Comment by samdark** [comment]
@cebe you said it's about escaping but I see that in the script it's escaped: https://github.com/yiisoft/yii2/blob/master/framework/rbac/migrations/schema-oci.sql#L24

What was meant exactly?

**Comment by cebe** [comment]
it is escaped in sql file but not in the migration: https://github.com/yiisoft/yii2/blob/97c43c248010baba1726ca32af6e4a0c553d24d8/framework/rbac/migrations/m140506_102106_rbac_init.php#L59

**Comment by SilverFire** [comment]
@jdgonzalez907 thank you for the report
