### ISSUE TITLE
Inflector plural rules - pasta/pastum

### ISSUE THREAD

**Issue by spencer4of6** [yiisoft/yii2#13515]
### What steps will reproduce the problem?
```
echo \yii\helpers\Inflector::singularize('pasta');
```

### What is the expected result?
Echos out "pasta".

### What do you get instead?
Echos out "pastum".

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |7.0.9
| Operating system |Windows 10 Home

This is by no means a breaking or critical issue. I'm just reporting it so an update can potentially go in the next release.

**Comment by cebe** [comment]
according to my dictionary, pasta has no singular.

**Comment by cebe** [comment]
See also https://en.wiktionary.org/wiki/pasta#English can not find a reference for `pastum` in english language.

**Comment by spencer4of6** [comment]
@cebe That is true. That is why "pastum" is an undesired output of the method. Adding it to the list of `$specials` in the Inflector alongside "rice", "graffiti", "pliers", and other words without singulars should fix the issue.

**Comment by cebe** [comment]
Oh, sorry, I read your issue wrong and thought you would expect `pastum` but got `pasta` :)
