### ISSUE TITLE
ActiveForm validateOnType cursor placement

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii2#13519]
### What steps will reproduce the problem?
Use activeform with validateOnType set to true
### What is the expected result?
Cursor stays in current position and not move to end of field.
### What do you get instead?
Cursor moves to end of input field after the validation sends.  

### Additional info
This is a problem because if you are trying to fix the validation error as soon as you type and if you are not faster than the validation delay time it will move the cursor to the end of the field. Your only option is to delete the whole filed and retype everything again or deal with the cursor moving to the end on almost every keystroke.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      |7
| Operating system |windows 10

**Comment by SilverFire** [comment]
![validateontype](https://cloud.githubusercontent.com/assets/4499203/23824787/a8d261fe-0685-11e7-920f-4512b2f5fb25.gif)

**Comment by SilverFire** [comment]
I'm closing the issue. If you still have the problem and can provide more information on how to reproduce the problem, please share it with us. Thank you.

**Comment by skworden** [comment]
I believe you are tying too fast to notice try setting the delay to a lower time so you can see.

```
public $validateOnType = true;
public $validationDelay = 100;
```

**Comment by SilverFire** [comment]
Can not reproduce even with short delay.
You might have problem related to other plugins.
Could you try to reproduce the problem on [clean Yii2 application](https://github.com/yiisoft/yii2-app-basic) and report, if it sill occurs?
