### ISSUE TITLE
Adding aditional information in Docs about default values in rules validator

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii2#13526]
Hello. I would like to suggest to add aditional information in documentation.
I think it is handy indicate in the blue "Info:" section of the link: http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#default the use of loadDefaultValues() http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#default-attribute-values

I think the two links are related. I had to create a post in the forum (http://www.yiiframework.com/forum/index.php/topic/73785-default-validation-rule-set-value-from-schema/) because I didn't found the solution of my problem. I think if the information about loadDefaultValues() were related in the blue box of http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#default it will be handy for other developers.

**Comment by samdark** [comment]
Agree. These could be cross-linked.
