### ISSUE TITLE
Issue with URL::to when the URL only contains a default element

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2#13522]
### What steps will reproduce the problem?

in the config/main.php add the following rule

`                [
                    'pattern' => '<language>',
                    'route' => 'site/index',
                    'defaults' => ['language' => 'en'],
                ], 
`

Then create a URL like that

`Url::to(['site/index', 'language' =>'en'])`

### What is the expected result?
The generated URL should be 

`<a href="/">Home</a>`

### What do you get instead?

`<a href="//">Home</a>`

The slash is duplicated

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.1
| PHP version      | 7.1.0
| Operating system | Windows 10 and Ubuntu 16.04

Issue is not reproducible on Yii 2.0.10

**Comment by MattDalm** [comment]
Hi 

I just tried the fix you committed and it works fine now. 

Thanks.

--Matt

**Comment by cebe** [comment]
There is now a 2.0.11.2 release including this fix. https://github.com/yiisoft/yii2/blob/2.0.11.2/framework/CHANGELOG.md#20112-february-08-2017
