### ISSUE TITLE
`yii\db\BaseActiveRecord::deleteAll()` should be compatible with `yii\db\ActiveRecordInterface::deleteAll()`

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#13538]
### What steps will reproduce the problem?

`BaseActiveRecord` declares method `deleteAll()` declared at `ActiveRecordInterface` changing its signature:

https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecordInterface.php#L262
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L199

Creating custom ActiveRecord implementation extending `BaseActiveRecord` forces to use new signature, even if it makes no sense.

### What is the expected result?

Custom ActiveRecord should be able to use `ActiveRecordInterface::deleteAll()`, which accepts single paramerter only:

```php
public static function deleteAll($condition = null) {}
```

### What do you get instead?

PHP Compile Error – yii\base\ErrorException

Declaration of yii2tech\filedb\ActiveRecord::deleteAll($condition = NULL) must be compatible with yii\db\BaseActiveRecord::deleteAll($condition = '', $params = Array)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | *
| Operating system | *

Issue extracted from https://github.com/yii2tech/filedb/pull/7

**Comment by samdark** [comment]
Indeed that looks a wrong and `$params = []` should be in the interface but I don't understand how it works now. It is like that since 2013.

**Comment by klimov-paul** [comment]
Additional params can be added during class/interface inheritance - it is fine.
The problem is adding `$params` at `BaseActiveRecord` twists the function signature unnecessary.
Additonal argument `$params` makes sense for `yii\db\ActiveRecord`, which uses `PDO`, but is absolutely redundant for NOSQL based ActiveRecord like MongoDB.

**Comment by cebe** [comment]
so we should remove $params from BaseActiveRecord, right?

**Comment by klimov-paul** [comment]
Resolved by commit 319e27c45c04d19a21b39598998038ad5464d2f8
