### ISSUE TITLE
Possible BC break in ExistValidator

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#13533]
### What steps will reproduce the problem?

https://github.com/yiisoft/yii2/commit/b82caa97e82ff8b99389b56958fb1e1310637c4b#diff-c36c8f68f6255dc8840038b8c921813eL54

> ~If the key and the value are the same, you can just specify the value.~

Upgrade Yii 2.0.10 => 2.0.11.1

```php
/**
 * @property integer $foo_id
 */
class A extends ActiveRecord {
}

/**
 * @property integer $foo_id
 * @property integer $a_id
 */
class B extends ActiveRecord {
    public function rules()
    {
        return [
            [
                ['a_id'],
                'exist',
                'targetClass' => A::class,
                'targetAttribute' => ['a_id' => 'id', 'foo_id'],  // shortcut 'foo_id' as documented before
            ],
        ];
    }
}
```

So, `B::foo_id == A::foo_id` and `B::a_id == A::id`

A:

id | foo_id
-- | --
42 | 997

```php
$b = new B();
$b->foo_id = 997;
$b->a_id = 42;

if (!$b->save()) {
    \Yii::error($b->errors);
    throw ...;
}
```

### What is the expected result?

```mysql
SELECT EXISTS(SELECT * FROM `a` WHERE (`id`=42) AND (`foo_id`=997))
```

Validation passed.

### What do you get instead?

```mysql
SELECT EXISTS(SELECT * FROM `a` WHERE (`id`=42) AND (`foo_id`=42))
```

Validation failed: `Attribute "a_id" is incorrect`.

### Additional info

Fix code as such:

```diff
- [['a_id'], 'exist', 'targetClass' => A::class, 'targetAttribute' => ['a_id' => 'id', 'foo_id']]
+ [['a_id'], 'exist', 'targetClass' => A::class, 'targetAttribute' => ['a_id' => 'id', 'foo_id' => 'foo_id']]
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.1
| PHP version      | 7.0.13
| Operating system | Ubuntu 16.04

**Comment by ddinchev** [comment]
This has been breaking many of our tests as we use a convention where primary and foreign keys match (primary key of `user` table would be `user_id`, the foreign key in `vehicle` table would be `user_id`.

The issue is caused by this line:
https://github.com/yiisoft/yii2/blob/master/framework/validators/ExistValidator.php#L144

So, if you are depending on multiple foreign columns for one `exist` rule validation, workaround is to do:

```
/**
 * @property integer $foo_id
 */
class A extends ActiveRecord {
}

/**
 * @property integer $foo_id
 * @property integer $a_id
 */
class B extends ActiveRecord {
    public function rules()
    {
        return [
            [
                ['a_id'],
                'exist',
                'targetClass' => A::class,
                'targetAttribute' => ['a_id' => 'id', **'foo_id' => 'foo_id'**]
            ],
        ];
    }
}
```

**Comment by cebe** [comment]
we will ship a hotfix release for this within the next 24h.

**Comment by developeruz** [comment]
I have already created [PR](https://github.com/yiisoft/yii2/pull/13534). The problem is in line https://github.com/yiisoft/yii2/blob/master/framework/validators/ExistValidator.php#L141 and there is no test for this part in the framework.

**Comment by cebe** [comment]
There is now a 2.0.11.2 release including this fix. https://github.com/yiisoft/yii2/blob/2.0.11.2/framework/CHANGELOG.md#20112-february-08-2017
