### ISSUE TITLE
 How to configure modules as subdomain in yii2 application?

### ISSUE THREAD

**Issue by kishansiliconinfo** [yiisoft/yii2#13535]
### What steps will reproduce the problem?
I have created two virtual host on local system,both are point to root folder of the yii2 application.

**1.ServerName dev.com**
**2.ServerName seller.dev.com**

I use request component to change backend url pattern backend/web/index.php to "webxadmin" with .htaccess on root.

For more info : [stackoverflow](http://stackoverflow.com/questions/28118691/yii2-htaccess-how-to-hide-frontend-web-and-backend-web-completely)

Here is my module inside backend/module/seller/seller.php working with yii-2 project i have e-commerce site i am trying to access my seller module on sub-domain like seller.dev.com with all module controller and action?

Tried : **component->urlmanage** in backend.
`'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            'seller.dev.com' => 'seller/default/index/',
            ],`

### What is the expected result?

expected result default action of the module controller.

seller/default/index

This is the view content for action "index". The action belongs to the controller "backend\module\seller\controllers\DefaultController" in the "seller" module.

You may customize this page by editing the following file:
/opt/lampp/htdocs/advanced/backend/module/seller/views/default/index.php

### What do you get instead?

I am getting frontend part of yii application with default controller and action.

### Additional info
I asked this question in Stackoverflow.
[more info](http://stackoverflow.com/questions/42002051/is-it-possible-to-assign-subdomain-to-module-for-example-seller-domain-com-to-s?noredirect=1#comment71182832_42002051)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.15
| Operating system | ubuntu 16.04 LTS 32 bit

**Comment by cebe** [comment]
> 'seller.dev.com' => 'seller/default/index/'

to match domain in URL rules you must include `http://`, since 2.0.11, you can also use protocol relative URL: `//seller.dev.com`

**Comment by kishansiliconinfo** [comment]
tired everything not working :)
