### ISSUE TITLE
Codeception tests in modules do not work

### ISSUE THREAD

**Issue by yapi68** [yiisoft/yii2#13547]
### What steps will reproduce the problem?
1. Install yii2-basic-app in /var/www/basic. Try to launch tests from /var/www/basic: codecept run unit - it runs normally.
2. Create any valid module, ex. `admin`, and include it in `config/web.php`
3. Move `tests` folder and `codeception.yml` file to `admin` (or do `codecept bootstrap` in it)
4. Navigate to /var/www/basic/admin and try to launch tests again: codecept run unit - multiple errors will be dropped, for ex. "Class app\models\User not found"

### What is the expected result?
Test must be lauched

### What do you get instead?
Multiple errors about invalid classes.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11?
| PHP version      | 7.0.15
| Operating system | Debian 8.1 x64

**Comment by samdark** [comment]
Have you adjusted paths to config files, bootstrap etc.?

**Comment by samdark** [comment]
Also please post errors you're getting.

**Comment by vinpel** [comment]
i've do a something similar to you it work.
(i try to adapt to you'r exemple, with and advanced app)
With Yii2 2.0.10 

Ensure yii2 codeception test are OK.
i have only done unit test in my module, rest work probably the same wat


bootrap admin /admin/tests 

admin/codeception.yml
```php
namespace: admin\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: '../common/config/test-local.php'
```

admin\tests\unit.suite.yml
```php
class_name: UnitTester
modules:
    enabled:
        - Yii2:
            part: [orm, email, fixtures]
        - Asserts
```
admin\test\unit\SampleTest.php
```php
<?php
namespace admin;

use Yii;
/**
* valid docblock
*/
class sampleTest extends \Codeception\Test\Unit
{
 /**
  * @var \modules\historique\UnitTester
  */
  protected $tester;
 public function testAjouteSimpleMessageHistoriqueUtilisateur(){
    $random_message1=Yii::$app->getSecurity()->generateRandomString(10);
    $random_message2=Yii::$app->getSecurity()->generateRandomString(10);
    $this->assertFalse( $random_message1== $random_message2);
 }
}
```

```

**Comment by samdark** [comment]
I'm not sure what is the problem to be fixed in the framework is then.
