### ISSUE TITLE
Checkall checkbox in gridview in a modal windows doesn't work after pjax refresh of the modal window

### ISSUE THREAD

**Issue by ydakilux** [yiisoft/yii2#13549]
### What steps will reproduce the problem?
Well, it's complex.
I have a form,containing a modal window, and in this modal window, there's a gridview.
In this gridview, the firdst columns is a checkbox column.

use yii\widgets\Pjax;

Pjax::begin();
<?= GridView::widget([
    'id' => 'mymodal-gridview',
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'pjax'=>true,
    'pjaxSettings'=>[
        'enablePushState'=>false,
        'neverTimeout'=>true,
    ],
    'columns' => [
        ['class' => 'yii\grid\CheckboxColumn'],
  ....
 ....

Pjax::end();

When the gridview show, the check_all checkbox on top of the gridview work without problem.

But after a refresh op the gridview through pjax, the check_all checkbox doesn't work anymore

I use the function 
  $.pjax.reload({url: url, container:'#mymodal-gridview-pjax'});

 to reload the modal window

 I traced into javascript, there is an event linked with the check_all checkbox. It's fired when I click on it.
 Event is in file  vendor\yiisoft\yii2\assets\yii.gridView.js, function is setSelectionColumn

  So, the part fired from the click event is : 
            initEventHandler($grid, 'checkAllRows', 'click.yiiGridView', checkAll, function () {
                $grid.find(inputs + ":enabled").prop('checked', this.checked);
            });

 But nothing append on screen.

### What is the expected result?
Check_all checkbox working all the time
### What do you get instead?
Check_all checkbox working only the first time.
If a refresh the whole page, will the full URL ( without the PJAX). The check_all checkbox work again

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10 and 2.0.11, but was working with 2.0.6
| PHP version      | PHP 5.5.9
| Operating system | Windows NT 3.2 build 9200 ( Windows Server 2012 )

**Comment by derekisbusy** [comment]
You probably need to rebind the events after your pjax reload. So reinitialize the grid after pjax reload call.

**Comment by samdark** [comment]
@derekisbusy is correct about it.

**Comment by ydakilux** [comment]
I tried like this : 

     $.pjax.reload({url: url, container:'#mymodal-gridview-pjax'});
     $('.mymodal-gridview-pjax').yiiGridView('init');

  But without success.

**Comment by dynasource** [comment]
please search the forum for 'pjax stopped working'. You will find enough info on this subject. You should add a ID to every Pjax widget for better stability.
