### ISSUE TITLE
Keep Relations via a Junction Table DRY

### ISSUE THREAD

**Issue by zuozp8** [yiisoft/yii2#13543]
When I use [Relations via Junction Table](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#junction-table) I often repeat the same join logic twice.

As in the [example](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#junction-table) i have 
```
return $this->hasMany(Item::className(), ['id' => 'item_id'])
            ->via('orderItems');
```
but in such case I would already have relation `item` defined in `OrderItem`. To avoid duplicating those join-logic I need to write code like
```
$query = (new OrderItem)->getItem();
$query->primaryModel = $this;
$query->via('orderItems');
return $query;
```

I think ActiveRecord needs way of defining those relations in way that reuses existing relations in other models. It will encourage writing code with higher quality.

**Comment by samdark** [comment]
Personally I don't think it would be good because it will be hard to find where the relation is defined exactly. Currently you can surely expect that everything used on a model is defined within the model.

**Comment by samdark** [comment]
@cebe, @SilverFire, @klimov-paul need opinions.

**Comment by klimov-paul** [comment]
> I think ActiveRecord needs way of defining those relations in way that reuses existing relations in other models.

It is already possible to use relation of the related model. Both eager and lazy loading is covered: no one forces you to define relation `item` using `via` - you may select primary models with relation `orderItems`, which will select its own relation item. Then you can use code like following:

```php
$model->orderItems[0]->item;
```

I can not see any problem here.

**Comment by cebe** [comment]
@zuozp8 Not sure what you are aiming at. You are worried about duplicating `['id' => 'item_id']` ? Quite sure it is not worth the effort implementing something that removes that and replaces it with a method call that hides the information at this place making someone reading the code to look it up in the other class. I do not think it is worth implementing.

**Comment by samdark** [comment]
@klimov-paul I think @zuozp8 is asking about reusing definition from another model, not returning related model itself...

**Comment by klimov-paul** [comment]
I noticed.
However defining duplicating relation using `via()` at main model is absolutely unnecessary.
You may avoid not only duplication of junction keys but the whole relation all together.

It is your choice to dulicate relation to `Item` at main model, you can use `oderItems->item` instead just fine. Thus I can not see why any changes are necessary here.

**Comment by samdark** [comment]
I see. So it seems we all agree that it won't be implemented.
