### ISSUE TITLE
Setting Rest pageSize Variable in yii2?

### ISSUE THREAD

**Issue by mehrantp** [yiisoft/yii2#13544]
I Want to set number of items per page in rest app.
I tested every items that change this value (pageSize) in activeDataProvider instance of rest Controller Like Overriding prepareDataProvider method or actionIndex.
But It Dose not effect.
Every time run code I get the default 20 items per page that set in activeDataProvider 
What is the solution?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 2.5.6
| Operating system | Mac OS Sierra 10.12.2

**Comment by JamesLeon** [comment]
I believe the REST controller provides all the RESTFUL actions you need by default without the developer needing to write additional code.  If you want to customize things like pagination size, you have to unset an action method to disable the inherited action and then provide your own method to handle data.


```php
public function actions()
    {
        $actions = parent::actions();

        //disable "index", "create", "update", "delete", "options" actions
        unset(
            $actions['index'],
            $actions['create'],
            $actions['update'],
            $actions['delete'],
            $actions['options']
        );

        return $actions;

    }
```

Then redefine actionIndex() method yourself to do what you need.  
```php
    public function actionIndex()
    {
        //\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $myQuery = mySpecialModel::find();
        $dataProvider = new ActiveDataProvider([
            'query'      => $myQuery,
            'pagination' => [
                'pageSize' => 0,
            ],
            'sort'       => [
                'defaultOrder' => [
                    'sortOrder' => SORT_ASC,
                    'manu'      => SORT_ASC,
                ],
            ],
        ]);

        return $dataProvider;
    }
```

**Comment by Ryadnov** [comment]
```
    public function actions()
    {
        $actions = ArrayHelper::merge(
            parent::actions(),
            [
                'index' => [
                    'prepareDataProvider' => function ($action) {
                        /* @var $modelClass \yii\db\BaseActiveRecord */
                        $modelClass = $action->modelClass;

                        return Yii::createObject([
                            'class' => ActiveDataProvider::className(),
                            'query' => $modelClass::find(),
                            //'pagination' => false,
                            'pagination' => [
                                'pageSize' => 5,
                            ],
                        ]);
                    },
                ],
            ]
        );

        return $actions;
    }
```

**Comment by mehrantp** [comment]
@JamesLeon 
Thanks James 
Your solution Worked! :)

**Comment by petr-panek** [comment]
>     public function actions()
>     {
>         $actions = ArrayHelper::merge(
>             parent::actions(),
>             [
>                 'index' => [
>                     'prepareDataProvider' => function ($action) {
>                         /* @var $modelClass \yii\db\BaseActiveRecord */
>                         $modelClass = $action->modelClass;
> 
>                         return Yii::createObject([
>                             'class' => ActiveDataProvider::className(),
>                             'query' => $modelClass::find(),
>                             //'pagination' => false,
>                             'pagination' => [
>                                 'pageSize' => 5,
>                             ],
>                         ]);
>                     },
>                 ],
>             ]
>         );
> 
>         return $actions;
>     }


There is simpler way. ArrayHelper::merge is not necessary, only redefine `prepareDataProvider` for action `$actions['index']`:

`
public function actions(): array
    {
        $actions = parent::actions();

        $actions['index']['prepareDataProvider'] = function ($action) {
            return new \yii\data\ActiveDataProvider([
                'query' => $this->modelClass::find()
                    ->where(['shopUid' => Yii::$app->getRequest()->get('shopUid')]),
                'pagination' => [
                    'pageSize' => 5
                ],
            ]);
        };

        return $actions;
    }
`

**Comment by CheckeredFlag** [comment]
As of 2.0.11, an even simpler way is adding this to the `container` config section via dependency injection:
```
'container' => [
    'definitions' => [
        'yii\data\Pagination' => [
            'pageSize' => 5,
        ],
    ],
],
```

Thought I'd add this for the sake of anyone looking for how to solve this via config.
