### ISSUE TITLE
fixture/load ignores fixtures in subdirectories

### ISSUE THREAD

**Issue by d1rtyf1ng3rs** [yiisoft/yii2#13551]
### What steps will reproduce the problem?

Problem involves fixture search process on `fixture/load` ( `yii\console\controllers\FixtureController::actionLoad()` ).
Let's say we have these fixtures under fixture namespace:
```
fooFixture.php
barFixture.php
sub\bazFixture.php
sub\fooFixture.php
```
The confirmation dialog would find all of them, but *strips everything to basename()*:
```
foo
bar
baz
foo
```
On confirmation, it would try to find & load them *directly* under fixture namespace, ignoring subdirectories.
### What is the expected result?
Instead of stripping found fixtures to basename(), their relative path sould be used (relatively to namespace dir). For aforementioned example, expected result is:
```
foo
bar
sub\baz
sub\foo
```
### What do you get instead?
```
foo
bar
baz
foo
```

### Additional info

Mentioned *expected result*  raises another problem in `FixtureController::getFixtureConfig()`: flag `isNamespaced` is calculated by presence of slashes in fixture name, whereas fixtures in subdirectories would have slashes and have no namespace.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      | 7.0.13
| Operating system | Ubuntu 16.04

**Comment by d1rtyf1ng3rs** [comment]
Made a [pull request](https://github.com/yiisoft/yii2/pull/13553) with proposed solution.
Would like to hear some comments / critics first, expecially about `getFixturesConfig()` changes.

**Comment by samdark** [comment]
Is it related to https://github.com/yiisoft/yii2-faker/pull/24?

**Comment by d1rtyf1ng3rs** [comment]
Yes, current issue totally "mirrors" yiisoft/yii2-faker#24.
