### ISSUE TITLE
yii\filters\AccessControl does not accept params for rules

### ISSUE THREAD

**Issue by ahmadazizi** [yiisoft/yii2#13552]
While implementing RBAC we usually check access either via  `yii\web\User::can()` or` yii\filters\AccessControl` behavior(the preferred way).

The can method accept parameters, the Yii guide example:
```
if (\Yii::$app->user->can('updatePost', ['post' => $post])) {
    // update post
}
```

but  yii\filters\AccessControl does not accept any parameters, here is the piece of source code in its class: 
```
    protected function matchRole($user)
    {
        if (empty($this->roles)) {
            return true;
        }
        foreach ($this->roles as $role) {
            if ($role === '?') {
                if ($user->getIsGuest()) {
                    return true;
                }
            } elseif ($role === '@') {
                if (!$user->getIsGuest()) {
                    return true;
                }
            } elseif ($user->can($role)) {
                return true;
            }
        }
        return false;
    }
```

It would be much more reliable, practical if it also accept parameters.

**Comment by klimov-paul** [comment]
Duplicates #7643

**Comment by ahmadazizi** [comment]
Ohh, sorry,
BTW, why don't you tag that issue as improvement?
