### ISSUE TITLE
Compare validator does not work with tabular data

### ISSUE THREAD

**Issue by jhon100** [yiisoft/yii2#13566]
I've a form with tabular data and tried to use compareValidator in 2 select inputs. I'm using other validators with no problems. The problem with compareValidator seems to be related to this code in yii.validation.js:
```javascript
[...]
            var compareValue,
                valid = true;
            if (options.compareAttribute === undefined) {
                compareValue = options.compareValue;
            } else {
                compareValue = $('#' + options.compareAttribute).val();
            }
[...]
```
`$('#' + options.compareAttribute)` translates to something like `$('#mymodel-parcela_min')` but would be like `$('#mymodel-0-parcela_min')`, `$('#mymodel-1-parcela_min')`...

So we need to include the index in the above code when the data is tabular (I dont know how, maybe grabing this info from the field being validated?). While this is not fixed, do you know some workaround?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11-dev

**Comment by samdark** [comment]
How do you attach validators to individual tabular input items?

**Comment by jhon100** [comment]
Nothing special, I only add the index in the field:
```php
<?= $form->field($configParcela, "[{$i}]tx_financeira")->textInput(['maxlength' => true]) ?>
```

And I create the rules in model:
```php
[['tx_financeira'], 'number'],
```
This is example of valiadation that works and the error message is showed correctly only in the wrong field . The javascript generated is:
```javascript
{"id":"parcelasdeplanodepagamento-0-tx_financeira",
"name":"[0]tx_financeira",
"container":".field-parcelasdeplanodepagamento-0-tx_financeira",
"input":"#parcelasdeplanodepagamento-0-tx_financeira",
"validate":function (attribute, value, messages, deferred, $form) {
 yii.validation.number(value, messages, {"pattern":/^\s*[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s*$/,"message":"\u0022Tx Financeira\u0022 deve ser um número.","skipOnEmpty":1});
 yii.validation.number(value, messages, {"pattern":/^[0-9]+([\.,]\d{0,4})?$/,"message":"Formatos aceitos: 15.58 ou 15,58 (com 1 a 4 casas decimais)","skipOnEmpty":1});}
}
```

For comparevalidator the rules are:
```php
['parcela_min', 'compare', 'compareAttribute' => 'parcela_max', 'operator' => '<=', 'type' => 'number', 'skipOnEmpty' =>true],
['parcela_max', 'compare', 'compareAttribute' => 'parcela_min', 'operator' => '>=', 'type' => 'number'],
```

And the generated javascript is:

```javascript
{"id":"parcelasdeplanodepagamento-0-parcela_min",
"name":"[0]parcela_min",
"container":".field-parcelasdeplanodepagamento-0-parcela_min",
"input":"#parcelasdeplanodepagamento-0-parcela_min",
"validate":function (attribute, value, messages, deferred, $form) {
  yii.validation.number(value, messages, {"pattern":/^\s*[+-]?\d+\s*$/,"message":"\u0022Parcela Min\u0022 deve ser um número inteiro.","skipOnEmpty":1});
  yii.validation.required(value, messages, {"message":"\"Parcela Min\" não pode ficar em branco."});
  yii.validation.compare(value, messages, {"operator":"<=","type":"number","compareAttribute":"parcelasdeplanodepagamento-parcela_max","skipOnEmpty":1,"message":"\"Parcela Min\" deve ser menor ou igual a \"Parcela Max\"."});}
}
```

**Comment by samdark** [comment]
So the number of items in your tabular input is fixed? No ability to add more?

**Comment by jhon100** [comment]
The ability exists, I did not mentioned because I think this dont inflluence in this issue. I'm using wbraganca/yii2-dynamicform and if I remove or add items the widget readjust the indexes in form and add or remove the validations (that works fine with other validators)

**Comment by jhon100** [comment]
What if we change the 'compare' signature to include the 'attribute' argument as the trim does?
So the signature could be
`compare: function (attribute, value, messages, options) ` 
instead of
`compare: function (value, messages, options)`

In this way we can access the attribute info like this:
```javascript
id: "parcelasdeplanodepagamento-0-parcela_min"
input: "#parcelasdeplanodepagamento-0-parcela_min"
name: "[0]parcela_min"
```
We can easily get the index from this info with some regex and the compare function could be changed to include this index when getting the compareValue. It could automatically verify if the input is array (having '[]') or add an option to treat the input as array when needed. 
The only aditional change would be in yii\validators\CompareValidator to include the 'attribute' too.
```php
    public function clientValidateAttribute($model, $attribute, $view)
    {
        [...]
        return 'yii.validation.compare(attribute, value, messages, ' . json_encode($options, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ');';
    }
```

**Comment by samdark** [comment]
I think it's OK to do.

**Comment by firefox747** [comment]
Didn't it work in prior Yii2 versions? I thought it did, but i could not find any relevant changes in the latest update.

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/9811

**Comment by SilverFire** [comment]
I'm closing this issue as a duplicate. @jhon100 if you want to submit a PR - we are glad to accept it
