### ISSUE TITLE
Query builder feature - postgresql FOR, NOWAIT and SKIP LOCKED

### ISSUE THREAD

**Issue by mikolajzieba** [yiisoft/yii2#13584]
### What steps will reproduce the problem?
Creating an SQL query with a FOR, NOWAIT or SKIP LOCKED using a Query Builder.
https://www.postgresql.org/docs/9.5/static/sql-select.html

### What is the expected result?
Pass a SKIP LOCKED to an SQL query using query builder. 

### What do you get instead?
I have to use createCommand and write whole sql query by hand. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10

**Comment by samdark** [comment]
Can't be implemented since it is DBMS specific feature and Yii's query interface supports many engines.
