### ISSUE TITLE
User has to click twice on submit button to submit form

### ISSUE THREAD

**Issue by neovmt** [yiisoft/yii2#13589]
### What steps will reproduce the problem?
Create ActiveForm with two submit buttons:

`<?= Html::submitButton('Load', ['class' => 'btn btn-primary', 'name'=>'submit', 'value'=>'submit_html']) ?>`
`<?= Html::submitButton('Export CSV', ['class' => 'btn btn-primary', 'name'=>'submit', 'value'=>'submit_export']) ?>`

### What is the expected result?
Form should be submitted on one click to submit button

### What do you get instead?
User has to click twice on any submit button to submit form.

### Additional info
Similar issue: https://github.com/yiisoft/yii2/issues/10555

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7
| Operating system | Linux

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/13531#issuecomment-277831483
