### ISSUE TITLE
Improve performance of Yii FileHelper

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#1360]
Just being obsessive to make the **great Yii framework** more better. Can we use <a href="http://php.net/manual/en/function.glob.php" target="_blank">glob</a> or <a href="http://php.net/manual/en/class.directoryiterator.php" target="_blank">DirectoryIterator</a> vs `opendir` or `readdir`? Let know if I need to contribute. This may also be an easier way to manage file/directory listings.

**Comment by dynasource** [comment]
this issue will be closed because of its age, few stakeholders and the absence of progress. Please do a vote if you want it to be reopened again.
