### ISSUE TITLE
yii2-markdown fails silently PHP 7.0.15 | opcache enabled

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#13601]
### What steps will reproduce the problem?
1. *Enable OPCache* (PHP 7.0.15)
2. composer create-project yiisoft/yii2-app-advanced advanced 2.0.11
3. ./init
4. Edit e.g. view/index
```php
<?php
use yii\helpers\Markdown;

$formattedText = Markdown::process('http://www.google.de', 'gfm-comment');
echo $formattedText;
exit;
?>
```
### Results:
above example with *opcache.enable=0*
![grafik](https://cloud.githubusercontent.com/assets/3147888/23063372/80278978-f50a-11e6-868c-9aceeb1229a6.png)

above example with *opcache.enable=1*
![grafik](https://cloud.githubusercontent.com/assets/3147888/23063410/b92ea90e-f50a-11e6-912b-69aa3b114852.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.15-fpm
| Operating system | 	Linux 175d55071de6 4.9.8-moby #1 SMP Wed Feb 8 09:56:43 UTC 2017 x86_64

**Comment by cebe** [comment]
which version of `cebe/markdown` is that? `composer show` can tell you.

**Comment by cebe** [comment]
oh wait, did you configure opcache to strip comments? that would mean the annotation system gets broken and no handlers are loaded for parsing content.
There should probably be a note in the docs for that.

**Comment by ItsReddi** [comment]
yep its working.
wasted 4 hours today and you need seconds +1
tried any opcache setting but not that one 😢
