### ISSUE TITLE
Ability to set currency symbol in formatter do not working

### ISSUE THREAD

**Issue by Fisher-mast** [yiisoft/yii2#13629]
### What steps will reproduce the problem?
I'm configure my `frontend/config/main.php`:

```php
'language' => 'ru-RU',
    'components' => [
        ...
        'formatter' => [
            'dateFormat' => 'dd.MM.yyyy',
            'decimalSeparator' => ',',
            'thousandSeparator' => ' ',
            'currencyCode' => 'RUB',
            'numberFormatterOptions' => [
                NumberFormatter::MIN_FRACTION_DIGITS => 0,
                NumberFormatter::MAX_FRACTION_DIGITS => 2,
            ],
            'numberFormatterSymbols' => [
                NumberFormatter::CURRENCY_SYMBOL => '₽',
            ]
        ],
    ],
```
### What is the expected result?

When i writting 

```php
<?= Yii::$app->formatter->asCurrency(100000) ?>
```

i expect to see `100 000 ₽ (my symbol)`

### What do you get instead?

but i get `100 000,00 руб.`

### Additional info

When i setting parameter `numberFormatterSymbols`, parameter `numberFormatterOptions` not working after (before result was `100 000 руб.`)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2?
| PHP version      | 7.1.0
| Operating system | ubuntu/trusty64
| and i testing too on native vagrant settings of yii2 | same result

thats my first issue, sry if something wrong

**Comment by SilverFire** [comment]
@samdark is the issue verified?

**Comment by samdark** [comment]
No, not yet.

**Comment by samdark** [comment]
@Fisher-mast can you run the following in your environment?

```php
$formatter = new NumberFormatter('ru_RU', NumberFormatter::CURRENCY);
$formatter->setSymbol(NumberFormatter::CURRENCY_SYMBOL, 'RUR1');
echo $formatter->formatCurrency(123, 'RUR');
```

**Comment by Fisher-mast** [comment]
@samdark sure, result
`123,00 р.`

**Comment by samdark** [comment]
Means your ICU version ignores setting currency symbol. I haven't found which versions are affected and if PHP version matters but I have the same issue reproduced at https://3v4l.org/7pPWr

**Comment by samdark** [comment]
@Fisher-mast one more thing to check. ICU version:

```php
echo defined('INTL_ICU_VERSION') ? INTL_ICU_VERSION : 'no ICU';
```

**Comment by samdark** [comment]
Here's what I've found so far:

- 58.2 — works
- 58.1 — works
- 57.1 — works
- 55.1 — does not work
- 54.1 — does not work
- 52.1 — does not work

**Comment by Fisher-mast** [comment]
@samdark yep my version is 52.1

**Comment by Fisher-mast** [comment]
@samdark updated my icu to 58.2 version and CURRENCY SYMBOL working perfectly. But value NumberFormatter::MIN_FRACTION_DIGITS => 0 still igroring (somebody create new issue https://github.com/yiisoft/yii2/issues/13768).
If someone do not know how update ICU on php 7.0 - here tutor:

> sudo su    
> 
> #Install ICU
> wget http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-src.tgz
> tar zxvf icu4c-58_2-src.tgz
> cd icu/source
> ./configure --prefix=/opt/icu5c && make && make install
> 
> #Install intl.so from php source
> cd ../..
> wget https://github.com/php/php-src/archive/php-7.0.15.tar.gz
> tar -xvf php-7.0.15.tar.gz
> cd php-src-php-7.0.15/ext/intl
> 
> export LD_LIBRARY_PATH=/opt/icu5c/lib
> phpize
> ./configure --enable-intl --with-icu-dir=/opt/icu5c
> make
> make install
> 
> #Activate extension (cli and fpm)
> echo "extension=intl.so" > /etc/php/7.0/mods-available/intl.ini
> ln -s /etc/php/7.0/mods-available/intl.ini /etc/php/7.0/cli/conf.d/20-intl.ini
> ln -s /etc/php/7.0/mods-available/intl.ini /etc/php/7.0/fpm/conf.d/20-intl.ini

**Comment by auxww** [comment]
You should not set 'currencyCode' => 'RUB', then it will be well done.

config
```
'formatter' => [
            //'currencyCode' => 'RUR',
            'numberFormatterOptions' => [
                NumberFormatter::MIN_FRACTION_DIGITS => 0,
                NumberFormatter::MAX_FRACTION_DIGITS => 0,
            ],
            'numberFormatterSymbols' => [
                NumberFormatter::CURRENCY_SYMBOL => '&#8381;',
            ],
        ],
```

formatter call
```
<?= Yii::$app->formatter->asCurrency(Yii::$app->user->balance) ?>
```

output
```
200 000 ₽ 
```

look inside the yii\i18n\Formatter
```
    public function asCurrency($value, $currency = null, $options = [], $textOptions = [])
    {
            //...
            $currency = $currency ?: $this->currencyCode;
            if ($currency && !isset($textOptions[NumberFormatter::CURRENCY_CODE])) {
                $textOptions[NumberFormatter::CURRENCY_CODE] = $currency;
            }
            $formatter = $this->createNumberFormatter(NumberFormatter::CURRENCY, null, $options, $textOptions);
            //die(print_r($textOptions, 1));
            //die($formatter->getSymbol(\NumberFormatter::CURRENCY_SYMBOL));
            if ($currency === null) {
                $result = $formatter->format($value);
            } else {
                $result = $formatter->formatCurrency($value, $currency);
            }
            //...
```

When you setting up a currency code value in Yii config, it creates NumberFormatter with additional options: $textOptions = [5 => 'RUR'], then calls formatCurrency($value, $currency) and results as 'р.'. 
```
$result = $formatter->formatCurrency($value, $currency);
```

Otherwise it creates calls NumberFormatter with an empty $textOptions = [], calls format($value) and NumberFormatter::CURRENCY_SYMBOL is applied, this results as '₽'.
```
$result = $formatter->format($value);
```
This works on both windows/mac notebook and frebsd/centos (or any other) server, with 7 or 5.4 php.

As for me, It's not, a little bit, usable, but it works if you wanna.

Best wishes,
auxww

**Comment by cebe** [comment]
> You should not set 'currencyCode' => 'RUB', then it will be well done.

yep, setting currencyCode will override the symbol.

**Comment by tonny-sofijan** [comment]
Sorry, not so in topic, but, I want to set my thousand (.) and decimal (,) separator in my currency (my currency example:  Rp 12.500,50). My formatter code:
```
        'formatter' => [
            'defaultTimeZone' => 'UTC',
            'timeZone' => 'Asia/Jakarta',
            'dateFormat' => 'php:d-m-Y',
            'datetimeFormat' => 'php:d-M-Y H:i:s',
            'decimalSeparator' => ',',
            'thousandSeparator' => '.',
            'currencyCode' => 'Rp ',
            'numberFormatterOptions' => [
                NumberFormatter::MIN_FRACTION_DIGITS => 0,
                NumberFormatter::MAX_FRACTION_DIGITS => 2,
            ],
        ],
```
The output is `Rp 12.500.50 ` <- decimal is .
I'm expecting `Rp 12.500,50` <- decimal is ,

What went wrong? 
Thanks.

**Comment by dicrtarasov** [comment]
> Sorry, a little out of topic, but, I want to set my thousand (.) and decimal (,) separator in my currency Have the same problem as metioned by tonny-sofijan.
thousandSeparator not working in asCurency

**Comment by mohdqasim98** [comment]
I am using Amazon Linux Image ( based on Centos 7) and can't find new version of ICU for my Linux version.The latest version available is ICU50.
Any workaround for this ?

**Comment by edarede** [comment]
Hi.
I am using yii en local machine.
I have an error:

Invalid Configuration – yii\base\InvalidConfigException
The default currency code for the formatter is not defined and the php intl extension is not installed which could take the default currency from the locale.

cannot resolve. please helpme whit this error.
tk.

**Comment by samdark** [comment]
Well, install intl extension.

**Comment by dicrtarasov** [comment]
You can configure property `currencyCode` of Formatter component in app config:
https://www.yiiframework.com/doc/api/2.0/yii-i18n-formatter#$currencyCode-detail

..or just install php-intl extension package.

**Comment by edarede** [comment]
hanks. I'm launching yii from the command line:
_ php yii serve --port = 8083 --docroot = "frontend/web/"_
but not from xammp (in xaamp if that dll is there)
How do i launch yii from xammp?

**Comment by dicrtarasov** [comment]
Please, read XAMPP documentation.
