### ISSUE TITLE
Refactor `asJson` and `asXml` methods of web controller

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#13620]
I think that the `data` parameters of the `yii\web\Controller::asJson()` and the ``yii\web\Controller::asXml()` should be optional defaulting to an empty array.

I use `$this->asJson([]);` quite often when I have no data to return to the client but the response should be a valid JSON object.

Why don't we make it optional and allow us to call it like `$this->asJson();`? Isn't it clearer?

**Comment by samdark** [comment]
I don't think so. It would be easier to make a mistake accidentally forgetting data.
