### ISSUE TITLE
Setting `logger` property in Dispatcher doesn't affect Yii::getLogger()

### ISSUE THREAD

**Issue by antonmarin** [yiisoft/yii2#13637]
### What steps will reproduce the problem?
in config set: 
```
components => [
    log => [
        class => yii\log\Dispatcher,
        logger => someLoggerClass,
    ]
]
```
### What is the expected result?
Yii::getLogger() instance of someLoggerClass
### What do you get instead?
Yii::getLogger() instance of yii\log\Logger

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6
| Operating system | MacOS

**Comment by antonmarin** [comment]
I think that Dispatcher->setLogger(logger) should call Yii::setLogger(logger)

**Comment by dynasource** [comment]
thanks for your feedback. Please look at the following topic https://github.com/yiisoft/yii2/issues/12163 for more info about this subject

**Comment by antonmarin** [comment]
Um. Do you mean that i should call \Yii::setLogger(MyLogger::class); in my index.php ?
That's really ugly solution. Is there another way?

**Comment by dynasource** [comment]
right in your bootstrap.php (or before instantiating your Application).  More info at https://github.com/yiisoft/yii2/issues/7555#issuecomment-131794988

**Comment by antonmarin** [comment]
That's better, but doing like this i will config my logger in two places. Is this really necessary? Why don't just call Yii::setLogger()?

**Comment by dynasource** [comment]
setting in once in your bootstrap should be enough. We also have a guide for you with more info on this topic http://www.yiiframework.com/doc-2.0/guide-runtime-logging.html#log-targets

**Comment by antonmarin** [comment]
i mean that config in main.php will still exist and another part of config (setting logger) will be in different place

**Comment by antonmarin** [comment]
@dynasource what do you think about #13641 ?
