### ISSUE TITLE
AJAX validation for models with conditional rules

### ISSUE THREAD

**Issue by depesr** [yiisoft/yii2#13648]
### What steps will reproduce the problem?

Create a model with fields that are conditionally required.
For example:
Field1 is required by default.
Field2 is required when field1 = 2

### What is the expected result?
When using active form with selectbox for field1, by selecting value = 2 in field1 and submitting form, the field2 should show error message

### What do you get instead?
Field2 does not show any erro message, although the results of AJAX request contains one.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6.29
| Operating system | Mac os sierra

**Comment by SilverFire** [comment]
Implement `whenClient` for Field2 as show here:
http://stackoverflow.com/questions/28756397/yii2-conditional-validator-always-returns-required

Add `change` event listener on the Field1 to trigger `change` event of Field2
