### ISSUE TITLE
Introduce model collections

### ISSUE THREAD

**Issue by ElijahGM** [yiisoft/yii2#13644]
Do we have this option on yii2? where a callback can be applied to collection of models through active Query to allow for modification of models before returning sample code

```
Model::find()->iterate(function($model)
{
    return model->attribute=modify(model->attribute)
})->all();

```
I understand one way to achive this is through afterFind, one drawback to this includes, its not triggered when you use asArray() and sometime you want to dynamically modify the attribute without alot of` if else `statements in the afterFind()

**Comment by dynasource** [comment]
the is no support yet for advanced (object) array handling with the use of Collections

**Comment by ElijahGM** [comment]
I have added a support am waiting for it to be approved

**Comment by rob006** [comment]
You can use `array_map()` for this.

**Comment by ElijahGM** [comment]
@rob006 thanks array_map() can work, I think 
```
Model::find()->iterate(function($model)
{
    return model->attribute=modify(model->attribute)
})->all();
```
provides a neater way of doing the job

**Comment by samdark** [comment]
If something like that is to be done, proper collections and populating models into collections should be introduced instead of hardcoding things into model itself.

**Comment by samdark** [comment]
- https://github.com/yiisoft/yii2/issues/12291
- https://github.com/yiisoft/yii2/issues/10806
- https://github.com/yiisoft/yii2/pull/12304
- https://github.com/yiisoft/yii2/issues/9763
- https://github.com/yiisoft/yii2/issues/8185
- https://github.com/yiisoft/yii2/issues/2423

**Comment by leandrogehlen** [comment]
I'm using for this cases the [YaLinqo](https://github.com/Athari/YaLinqo), it's good and have a good performance.

**Comment by SamMousa** [comment]
Something like this could (should) be used: https://github.com/nikic/iter

Basically this feature is not related to AR or models, but to iterators.

Alternatively if you do not want a dependency, you could introduce an IteratorHelper that exposes the functionality.
Ideally these things should be implemented lazily, to optimize cases where not every element is iterated over...

**Comment by rob006** [comment]
Related: #13921

**Comment by Faryshta** [comment]
how about just editing this line? https://github.com/yiisoft/yii2/blob/master/framework/db/Query.php#L229 to make it configurable to what it will use to store the data from the database

something like

```php

public $collectionClass;

public function collection()
{
    if (null !== $this->collectionClass) {
        return new $this->collectionClass();
    }
    return [];
}

public function all()
{
    // ...
    $result = $this->collection();
    // ...
}
```

that way it can be configured per model or query

```php
class Store extends ActiveRecord
{
     public static function find()
     {
          $query = parent::find();
          $query->collectionClass = StoreCollection::className();
          return $query;
     }
}
```

bc break is kept and if you want more specific behavior you can extend `collection()` method.

**Comment by cebe** [comment]
I started experimenting with something that could become an official extension: https://github.com/yiisoft/yii2-model-collection
here are some usage docs: https://github.com/yiisoft/yii2-model-collection/tree/master/docs/guide

It's an early draft so it may not even work. but I'd like to have your feedback on it.

**Comment by SamMousa** [comment]
Looks nice! I'll add some comments.

**Comment by ElijahGM** [comment]
This is look awesome

**Comment by cebe** [comment]
Closing this issue now, track of implementation details will be discussed at https://github.com/yiisoft/yii2-collection
