### ISSUE TITLE
Formatter: asDatetime return wrong datetime value

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#13659]
### What steps will reproduce the problem?
\Yii::$app->formatter->asDatetime('25-02-2017 13:40', 'medium')
### What is the expected result?
Feb 25, 2017, 1:40:00 PM
### What do you get instead?
Feb 25, 2017, 7:10:00 PM

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.1
| Operating system | Ubuntu

**Comment by SilverFire** [comment]
Please, run the following code and share the output with us

```php
var_dump(Yii::$app->timeZone);
var_dump(Yii::$app->formatter->timeZone);
var_dump(date_default_timezone_get());
var_dumo(ini_get('date.timezone'));
```

**Comment by hirenbhut93** [comment]
string(12) "Asia/Kolkata"
string(12) "Asia/Kolkata"
string(12) "Asia/Kolkata"
string(0) ""

**Comment by SilverFire** [comment]
Method `asDatetime()` expects DateTime in UTC and converts it in your local time zone. 
`Asia/Kolkata` is `UTC+05:30`, so you get your time +5 hours 30 minutes.
You should set your timezone to UTC to prevent time conversion.
