### ISSUE TITLE
Duplicate slashes if set param 'suffix' of the component UrlManager to '/' 

### ISSUE THREAD

**Issue by InteLigent** [yiisoft/yii2#13656]
### What steps will reproduce the problem?
#13522
```php
[
    'suffix'     => '/',
    ['pattern' => '<page:\d+>', 'route' => 'site/index', 'defaults' => ['page' => 1]],
]
```

Then create a URL like that

Url::to(['site/index', 'page' => 1])

### What is the expected result?
The generated URL should be
```text
<a href="/">Home</a>
```
### What do you get instead?
```text
<a href="//">Home</a>
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.15
| Operating system | Centos 6

Issue is not reproducible on Yii 2.0.10

**Comment by SilverFire** [comment]
Probably will be fixed by https://github.com/yiisoft/yii2/pull/13624

**Comment by Kolyunya** [comment]
Is there a typo in the issue description? The URL rule has a `site/brand` route and the URL creation example - `site/index`.

**Comment by InteLigent** [comment]
Sorry, for my typo in the description. I corrected it.

**Comment by Kolyunya** [comment]
Confirmed via #13660.

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/pull/13624/commits/7206b2ba8a9e2a7648fa5507ce338fc851bc0a6e
