### ISSUE TITLE
Alert documentation update

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2#13661]
I was looking for a way to remove Close Button in Alert widget. In yii2 API it is mentioned that `closeButton` widget parameter is type of `array`, but looking into source code clarified the situation - `closeButton` can be set to `false`. Please update the docs, so that type can be `array` or `boolean`.

**Comment by Kolyunya** [comment]
@evil1 where do you read docs at? A quote from the [official docs](http://www.yiiframework.com/doc-2.0/yii-bootstrap-alert.html#$closeButton-detail):

```
$closeButton public property
The options for rendering the close button tag. ... If this is false, no close button will be rendered.
```

**Comment by samdark** [comment]
Fixed by merging @Kolyunya pull request.
