### ISSUE TITLE
better to call invalidateCache() after assign and revoke methods in RBAC

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2#13662]
### What steps will reproduce the problem?
assigning/revoking roles to users via `\yii\rbac\DbManager::assign()` and  `\yii\rbac\DbManager::revoke()` methods.

### What is the expected result?
The user immediately gain access to given roles.

### What do you get instead?
user's won't immediately gain access to given roles if caching is enabled. cache should be manually flushed or `\yii\rbac\DbManager::invalidateCache()` must be called.

Is there a special reason `invalidateCache()` is not called in `assign()` and `revoke()` while it's called in many other methods like `addItem()`? 
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version     | 5.6.27
| Operating system | OSX

**Comment by SilverFire** [comment]
I don't think it was done by design. Would you like to create a Pull Request?

**Comment by SilverFire** [comment]
Maybe it was done because of performance reasons. Hard to say now.

**Comment by hesna** [comment]
@SilverFire sure, I'll make a PR.
btw, as a performance point of view it's better to make users invalidate cache whenever needed, as most scenarios are something like this (example from official guide):
```php
$createPost = $auth->createPermission('createPost');
$auth->add($createPost);

$updatePost = $auth->createPermission('updatePost');
$auth->add($updatePost);

$author = $auth->createRole('author');
$auth->add($author);
$auth->addChild($author, $createPost);

$admin = $auth->createRole('admin');
$auth->add($admin);
$auth->addChild($admin, $updatePost);
$auth->addChild($admin, $author);

$auth->assign($author, 2);
$auth->assign($admin, 1);
```
the `invalidateCache()` method would be called 9 times in this simple scenario! although removing it from those methods might be considered as breaking BC cause some users might be counting on it. so maybe adding it to `assign` and `revoke` is the only way to go?

**Comment by SilverFire** [comment]
Roles and permissions creating does not happens often. Normally, we configure RBAC once and do not change it unless business requires.
Roles assignation happens much more often. When [defaultRoles](http://www.yiiframework.com/doc-2.0/yii-rbac-basemanager.html#$defaultRoles-detail) property is not configured, it may occur every time we create a new user, for example.

**Comment by hesna** [comment]
I looked a bit more and it seems user-role assignments stored in `auth_assignment` table do not get cached at all! so `revoke` and `assign` do not need to call `invalidateCache` method. 
I'm not sure what caused my initial problem when assigning new roles to a user wouldn't take effect until I flushed cache, but until I can reproduce the problem, I think this issue can be closed.
please let me know if I'm wrong about `auth_assignment` table not being cached. thanks.
