### ISSUE TITLE
Console optionAliases() using hyphen (-) mark on alias

### ISSUE THREAD

**Issue by neotrouz** [yiisoft/yii2#13670]
I running console using options that I set on `optionAliases()` and assume I can using hyphen (-) mark. Example: `['start-date' => 'startDate']`.
So I set with `-start-date="2017-01-01"`

I check `yii\console\Request` only `^-(\w+)` allowed.
Since its name changed from `shortCuts` to `optionAliases`, I think using hyphen (-) should included. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.1

**Comment by pana1990** [comment]
@neotrouz @samdark check my pr please

https://github.com/yiisoft/yii2/pull/13678

**Comment by neotrouz** [comment]
👍 
Thanks :)
