### ISSUE TITLE
ReflectionException: Method yii\base\View::unknown() does not exist

### ISSUE THREAD

**Issue by yapi68** [yiisoft/yii2#13671]
Very hard to explain. But it seems there is a bug in yii2 debug info system.

This exception is raised when trying to get undefined variable in nested view. For example in yii2 basic app with YII_DEBUG sets in true you can change `contact.php` view file to render nested view `contact_form.php`. In that file try to get any undefined variable to raise an exception. Standard debug info will be "broken" - no color highlighting, strange rows in the end.

### What steps will reproduce the problem?
1. Install yii2-basic-app
2. Set YII_DEBUG to `true`
3. Change the view @app/views/site/contact.php to
```
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render("contact_form"); ?>
```
4. Create `contact_form.php` file:
```
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;

$model->text; // <-- Exception will be throw here
?>
<div class="site-contact">
...
</div>
```
5. Navigate to `/index.php?r=site%2Fcontact` and see broken (not fully colored) debug view.

### What is the expected result?
Correct standard debug view.

### What do you get instead?
Broken (not fully colored) debug view.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2?
| PHP version      | 7.0.15
| Operating system | Debian 8.1.

This bug is appearing **ONLY** in nested views. If you try to call `$model->text` in main `contact.php` file nothing obvious happens. The debug view will be draw perfectly.

**Comment by yapi68** [comment]
Screenshots of "broken" debug view:

![screen_1](https://cloud.githubusercontent.com/assets/1772714/23353414/67e6081e-fcdd-11e6-814f-b2379516c5d7.JPG)

![screen_2](https://cloud.githubusercontent.com/assets/1772714/23353372/3037362c-fcdd-11e6-8890-9d886457d1d9.JPG)

**Comment by samdark** [comment]
I can't reproduce it. Did exactly what you did. Got the following:

![yii base errorexception - http yii2-basic local](https://cloud.githubusercontent.com/assets/47294/23356083/9ca4e5c8-fce9-11e6-8e0a-7deedab636a7.png)

**Comment by samdark** [comment]
If you have additional details — please post here.

**Comment by SilverFire** [comment]
I've seen this kind of broken Debug view on local machine, but failed to reproduce it

**Comment by yapi68** [comment]
Which additional info do you need?

**Web-server:** nginx/1.10.2
**PHP**: 7.0.15 x64

### PHP modules enabled: ###
[PHP Modules]

- calendar
- Core
- ctype
- curl
- date
- dom
- exif
- fileinfo
- filter
- ftp
- gd
- gettext
- hash
- iconv
- intl
- json
- libxml
- mbstring
- mysqli
- mysqlnd
- openssl
- pcntl
- pcre
- PDO
- pdo_mysql
- Phar
- posix
- readline
- Reflection
- session
- shmop
- SimpleXML
- soap
- sockets
- SPL
- standard
- sysvmsg
- sysvsem
- sysvshm
- tokenizer
- wddx
- xdebug
- xml
- xmlreader
- xmlwriter
- xsl
- Zend OPcache
- zip
- zlib

[Zend Modules]

- Xdebug
- Zend OPcache

**Comment by yapi68** [comment]
![screen_3](https://cloud.githubusercontent.com/assets/1772714/23356808/455f0912-fcec-11e6-9708-13b4656490c4.JPG)

Look at this screenshot! It\`s ok with color highlighting, but `unknown()` function calling again, when requiring `index.php` file. Why? 

Listing: index.php
```
<?php
// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'prod');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/../config/web.php');
$env = require(__DIR__ . '/../config/' . (defined('YII_ENV') ? YII_ENV . '/' : '') . 'web.php');

(new yii\web\Application(\yii\helpers\ArrayHelper::merge($config, $env)))->run();
```

**Comment by samdark** [comment]
No idea. Please tell us how to reproduce the error starting with basic application else we can't fix it.

**Comment by yapi68** [comment]
@samdark 

Ok. Look, you have:
![screen_4](https://cloud.githubusercontent.com/assets/1772714/23357568/6cfc1430-fcef-11e6-906f-3a5ca5194baf.JPG)

But I have:
![screen_5](https://cloud.githubusercontent.com/assets/1772714/23357567/6cf7d154-fcef-11e6-8c7e-b7a692f3d7a3.JPG)

Which OS do you have? C:\dev\... - like in Windows. But I have Debian 8.1 x64.

**Comment by yapi68** [comment]
I reproduce this bug again on other server (same as first one):

1. composer create-project --prefer-dist yiisoft/yii2-app-basic basic
2. edit @app/views/site/index.php

```
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<?= $this->render("index_include"); ?>
<div class="site-index">
...
</div>
```
3. Add file @app/views/site/index_include.php with content:
```
<?php

var_dump($model);

```
4. Navigate to /index.php and got same error!!!

**Comment by samdark** [comment]
Yes, I've tested on Windows 10. Going to check on mac.

**Comment by yapi68** [comment]
@samdark @SilverFire I have found it! This bug reproduces on systems with xdebug enabled! When I disable xdebug in PHP 7.0.15 config - bug has been disappeared!

PHP 7.0.15 (php-fpm)
php7.0-xdebug 2.5.0
Nginx 1.10.2

Hope now you can reproduce and confirm a bug.

**Comment by samdark** [comment]
Reproduced.

**Comment by samdark** [comment]
Put together a fix. Please verify if it works for you.

XDebug seems to be producing trace lines with `function` specified as a string `"unknown"` when code is out of any function. Normal PHP uses `null` in this case.

**Comment by yapi68** [comment]
@samdark Confirm, your fix is working. Thanks for help.
