### ISSUE TITLE
Broken Error trace due to regression bug

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#13689]
Just traced a regression bug caused by commit https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L199

It happens when a Closure method is injected into ReflectionMethod causing:
"An Error occurred while handling another error" and breaking the Error page.

The solution is an extra check on $method for type checking on a Closure. Will create a PR for it.

**Comment by samdark** [comment]
How to reproduce it?

**Comment by dynasource** [comment]
this will be part of the unit test
