### ISSUE TITLE
new getOrSet in cache component warning message not as expected

### ISSUE THREAD

**Issue by lessmind** [yiisoft/yii2#13690]
### What steps will reproduce the problem?
trigger a getOrSet warning

### What is the expected result?
see message "Failed to set cache value for key {json_encode($key)}"

### What do you get instead?
see message "Failed to set cache value for key {json_encode($value)}"

### Additional info
Actually I never run into this, just checking out new features and found the code probably won't act as expected.

**Comment by SilverFire** [comment]
Thank you for your report. Fixed
