### ISSUE TITLE
Proposal: Boolean DataColumn formatter should determine dropDownList filter for grid column

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#13698]
### What steps will reproduce the problem?
Use boolean formatter for single column in GridView

### What is the expected result?
Formatter should determine filtering control (dropDownList).

### What do you get instead?
Filter for that column is TextBox and user can not type 'true' or 'false' text to filter GridView results. Moreover column shows now localized text so user try use those words and can not filter the results.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.6.2
| Operating system | Windows 10 EDU

**Comment by mklemarczyk** [comment]
Thanks for development this proposal.
When can I expect it to be released?

**Comment by samdark** [comment]
This month, I think.
