### ISSUE TITLE
Cache flushing issue

### ISSUE THREAD

**Issue by deniskoronets** [yiisoft/yii2#13691]
### What steps will reproduce the problem?
Configure schema caching or add some caching logic in controller only for frontend/ part of website (advanced yii2 template), then try to flush schema through console command: ./yii cache/flush-all

### What is the expected result?
frontend cache is flushed

### What do you get instead?
frontend cache is remain, actually only console cache is flushed.

### Additional info
this may be critical, b/c once some changes are deployed, exception may be thrown till cache will be cleared.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2.
| PHP version      | 7.1.2
| Operating system | Linux Mint

**Comment by SilverFire** [comment]
Keeping components configuration in sync is a developer's responsibility.
In case you have the same component configuration for both `frontend` and `console` application, you can move the definition into a separate file, e.g. `common.php` and include it in your configs
