### ISSUE TITLE
catchAll could possibly have option to ignore the 'db' connection?

### ISSUE THREAD

**Issue by patpwilly** [yiisoft/yii2#13709]
### What steps will reproduce the problem?
edit config to use the 'catchAll' option with a simple route, mine was 'site/maintenance'.
Application should have a 'db' configured, but have the MySQL server completely down.
### What is the expected result?
Expect to see the view requested by the 'catchAll' route
### What do you get instead?
SQL EXCEPTION ERROR connection refused.

### Additional info
When the MySQL server was brought back online the catchAll functioned as expected, routing the user to the correct view.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6
| Operating system | Windows

**Comment by Kolyunya** [comment]
Do you establish (explicitly or implicitly) a DB connection in `site/maintenance` action?

**Comment by devmustafa** [comment]
What I also suggest here is make the ability to add the statusCode for the response object.
So, instead of:
`'catchAll' => ['site/maintenance']`

Is to add the statusCode like:
`'catchAll' => ['site/maintenance', 503]`
Or:
`'catchAll' => [
        'route' => 'site/maintenance',
        'statusCode' => 503
    ]
`
Because it's always return 200 which doesn't make sense in most of the cases.

**Comment by samdark** [comment]
@devmustafa that sounds like totally unrelated issue. Please create a separate ticket for it. Thanks.

**Comment by patpwilly** [comment]
No, in site/maintenance it's only html and html layout. 
The 'catchAll' I'm doing is so I can take the db and engine completely offline.  In this case I don't want/need the 'db' component to try and connect.
My problem is that I don't wish to comment out/remove the 'db' component when I put a 'catchAll' in place. 

However,  and this is probably my true issue, I have an 'as beforeRequest' in the configuration that is calling the db for information.  I'm probably hitting that before the 'catchAll' is even processed aren't I?

If so, sorry about the mix up.  
Thank you.

**Comment by devmustafa** [comment]
@samdark created [#13719](https://github.com/yiisoft/yii2/issues/13719)

**Comment by Kolyunya** [comment]
@patpwilly do you mean `on beforeRequest`? This seems like a real source of your issue since this code is executed before each request even those handled via `catchAll`.

**Comment by samdark** [comment]
@patpwilly yes, that's the source of your issue. It's executed before anything.
