### ISSUE TITLE
In Default ErrorView render by `yii\web\ErrorAction` ，the `Yii::$app->response->statusCode` is not correct

### ISSUE THREAD

**Issue by ihipop** [yiisoft/yii2#13707]
### What steps will reproduce the problem?
use  `Composer` to initialize  a clean Yii2 advanced app template
in `frontend/views/site/error.php`   add the following line
```php
<?= Yii::$app->response->statusCode?>
```
then, navigate to `a none-existing Url Location` in Browser,such as `http://yaa-frontend.dev/xxx`

### What is the expected result?

the above PHP code added to   `frontend/views/site/error.php`    should output `404`

### What do you get instead?
the  above PHP code added to   `frontend/views/site/error.php`    just output `200`  in page content
 **_this is not correct_**

**Note:** HTTP code in Browser is 404, **_this is correct_**.
![image](https://cloud.githubusercontent.com/assets/423077/23608685/817c32da-02a5-11e7-8875-60ad1f7aa897.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | PHP 7.1
| Operating system | Ubuntu 16.04 LTS

**Comment by arogachev** [comment]
Reproduced with latest code from master branch, it's indeed a bug.

**Comment by samdark** [comment]
Fixed. Preparing pull request.

**Comment by ihipop** [comment]
@samdark  Thanks  for  your effort

**Comment by arogachev** [comment]
@ihipop Related PR is not merged yet. We'll close it when it will be finished.
