### ISSUE TITLE
JS form validation not work without submitting = true

### ISSUE THREAD

**Issue by Commander223** [yiisoft/yii2#13714]
trying to validate form via javascript
```js
form.yiiActiveForm('validate', true);
```

php form
```php
<?php $form = ActiveForm::begin([
	'validationUrl' => ['validate-url'],
	'enableAjaxValidation' => true,
	'enableClientValidation' => true
]); ?>
//fields
<?php ActiveForm::end(); ?>
```

Do not show an error in the form

Digging in 

> yii.activeForm.js

show that
`submitting = data.submitting && !forceValidate;`
line 309

after script call 
`updateInputs($form, $.extend(messages, msgs), submitting);`
but submit equal to false, so we come to line 658
```js    
$.each(data.attributes, function () {
    if (!this.cancelled && (this.status === 2 || this.status === 3)) {
        updateInput($form, this, messages);
    }
});
```
but before in code we don't change status of fields, so 
`(this.status === 2 || this.status === 3)`
false because default status 0
But if submitting is true we see different check
```js
            $.each(data.attributes, function () {
                if (!$(this.input).is(":disabled") && !this.cancelled && updateInput($form, this, messages)) {
                    errorAttributes.push(this);
                }
            });
```
line 621
we don't check status of input

At this time
```js
		form.yiiActiveForm('data').submitting = true;
		form.yiiActiveForm('validate');
```
work, but if validation true it submit form

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0.15
| Operating system | Ubuntu 16.04.4

**Comment by dynasource** [comment]
confirmed

**Comment by samdark** [comment]
@SilverFire could you take a look?

**Comment by bologer** [comment]
hi guys, any progress on this issue?

**Comment by bologer** [comment]
@Commander223 , did you find any temporary solution for that?

**Comment by samdark** [comment]
@arogachev do you have time to take a look?

**Comment by alexkolgene** [comment]
Same problem. I am trying to use validation, and only one way i can apply it: 
`form.data('yiiActiveForm').submitting = true;
form.yiiActiveForm('validate', true);`

But this cause submitting form and i do not want my form to submit :)

**Comment by dmirogin** [comment]
I think this is going to work after https://github.com/yiisoft/yii2/commit/8f2d9baf98003c912d91c1fad962e0835ff01f3f

**Comment by SilverFire** [comment]
Right.

**Comment by malkeetseefat** [comment]
you can use custom ajax like this after validate

$('#formid').on('afterValidateAttribute', function (event, attribute, messages) {
   ajax here......
});
