### ISSUE TITLE
findOne with postgreSQL throws exception

### ISSUE THREAD

**Issue by 1Luc1** [yiisoft/yii2#13718]
### What steps will reproduce the problem?
With a postgreSQL db call the ::findOne Method with a invalid column value.
 E.g.: Customer::findOne(['id' => 1, 'age' => $customer->name]);
Column age is integer; wheras $customer->name is string

### What is the expected result?
Calling the same findOne method as shown above with an mysql db, will return an empty ActiveRecord.

### What do you get instead?
An exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer:

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0.15
| Operating system | ubuntu 16.10
| postgreSQL     |  9.5.6
| mysql    | 5.7.17
| nginx   | 1.10.1

**Comment by samdark** [comment]
Well, that's how PostgreSQL works. Yii API forms a request, DB responds. If you have an idea on how to solve that, let us know in comments and I'll reopen the issue.

**Comment by 1Luc1** [comment]
Ok i understand. I just thought calling api methods on different db will have the same result; wouldn't it be possible to catch the exception and return an ActiveRecord?

**Comment by samdark** [comment]
How do I tell if it's kind of real error or the case we have in this issue?

**Comment by 1Luc1** [comment]
I got the point. alright, thanks for the clarification.

**Comment by samdark** [comment]
You're welcome.
