### ISSUE TITLE
login problem caused by cookies in two applications with same domain 

### ISSUE THREAD

**Issue by mozhgan-km** [yiisoft/yii2#13716]
Hello, 
I have two separated applications so these two apps have  different cookieValidationKey and source code , and i set domain property of identityCookie in user component  to login in all sub-domains of each app. one of them is sub.example.com  and the other is example.com.
now i want to login to sub.example.com , in my cookies  i have two PHPSESSID with different domain attribute,one of them is  .example.com  and the other is .sub.example.com ,so i cant login.

**Comment by cebe** [comment]
you need separate cookie names for the login. See advanced app docs on how to solve it:

https://github.com/yiisoft/yii2-app-advanced/blob/bb35a7543aa5b718b01d6cd576d78da9e4193249/docs/guide/topic-shared-hosting.md#adjust-sessions-and-cookies

**Comment by mozhgan-km** [comment]
i mean two different apps with different dbs,actually each of them has their owns frontend and backend not depended to each other,they are just in same domain
see them:
 http://hiau.ac.ir/fa , 
http://faculty.hiau.ac.ir/fa

**Comment by samdark** [comment]
It doesnt' matter if these are separate apps or not.

**Comment by mozhgan-km** [comment]
see below picture, now i cant login
![screenshot from 2017-03-07 13 57 07](https://cloud.githubusercontent.com/assets/13865493/23652577/b48d4896-033e-11e7-98a4-97bb4018d19f.png)

**Comment by mikehaertl** [comment]
@mozhgan-km You can configure different `domain` in the [cookieParams](http://www.yiiframework.com/doc-2.0/yii-web-session.html#setCookieParams()-detail) of your session component:

```
'session' => [
    'cookieParams' => [
        'domain' => 'hiau.ac.ir',
```

**Comment by mozhgan-km** [comment]
@mikehaertl I set these too,but my problem doesn’t solve!this problem is for different cookieValidationKey,if i put same cookieValidationKey for two sites,the problem solve,but i dont want to have same cookieValidationKey because they are completely separate!
