### ISSUE TITLE
'default' validator returns blank value instead of null if attribute uses some filter

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii2#13710]
### What steps will reproduce the problem?

table.attrib1 is able to store NULL values

```
public function rules()
        return 
            [
                [['attrib1'], 'default'],
                [['attrib1'], 'filter','filter'=>'ucwords'],

```

### What is the expected result?
attrib1 on database must be NULL value if is posted as blank value

### What do you get instead?
attrib1 on database is blank value instead of NULL

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.15
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
That's how PHP's `ucwords` works. If it's supplied with `null` return value is `''`. There's is no plan to change that.

**Comment by rob006** [comment]
Try switch order of these rules - put `default` rule after `filter`.

**Comment by nacesprin** [comment]
@rob006 Thanks! It worked!

@samdark I think it should be indicated on the documentation related about 'default' and 'filter' rules

**Comment by Aradiv** [comment]
@nacesprin 
This applies to all rules not only rules with default.

From the Documentation:
http://www.yiiframework.com/doc-2.0/guide-input-validation.html
> 3. Use each active rule to validate each active attribute which is associated with the rule. **The validation rules are evaluated in the order they are listed**.
