### ISSUE TITLE
Add statusCode to response object for catchAll config

### ISSUE THREAD

**Issue by devmustafa** [yiisoft/yii2#13719]
In the case of `catchAll` config, I suggest making the ability to add the statusCode for the response object:
So, instead of:
`'catchAll' => ['site/maintenance']`

Is to add the statusCode like:
`'catchAll' => ['site/maintenance', 503]`
Or:
`'catchAll' => [
        'route' => 'site/maintenance',
        'statusCode' => 503
    ]
`

Because it always returns 200 which doesn't make sense in most of the cases.

**Comment by Kolyunya** [comment]
I think this should be encapsulated inside a controller. If I have multiple `catchAll` stubs I don't want to status code in addition to action path and parameters.

**Comment by samdark** [comment]
I agree with @Kolyunya. That is easily doable in the action itself.

**Comment by devmustafa** [comment]
Thanks, I was able to add this line of code to the action and it solves the issue:
`Yii::$app->response->statusCode = 503;`

**Comment by devmustafa** [comment]
@Kolyunya, it can also handled this way:
`
$headers = Yii::$app->response->headers;
$headers->add('Retry-After', '30');
`

**Comment by Kolyunya** [comment]
@devmustafa glad you were able to solve the issue! And thanks for the tip! :+1:
