### ISSUE TITLE
Ability to render an optional container tag in DetailView widget

### ISSUE THREAD

**Issue by ARHImed82** [yiisoft/yii2#13723]
## Proposal ##

I use Bootstrap in my projects. So I need to wrap every DetailView widget into div container with 'table-responsive' css classs for mobile devices.

## Solution ##

Add new public property 'container' in yii\widgets\DetailView class, for example:

```
<?php
echo DetailView::widget([
     ... ,
     'container' => [
          'tag' =>'section',
          'class' => 'table-responsive',
     ],
     ... ,
]);
?>
```

**Comment by rob006** [comment]
Why not

```
<section class="table-responsive">
<?php
echo DetailView::widget([
     ... ,
]);
?>
</section>
```
?

**Comment by ARHImed82** [comment]
Yes, you are right. I do so.
But I mean to add such feature in core yii\widgets\DetailView class, not do it manually every time.

**Comment by samdark** [comment]
While it sounds logical, it's out of scope of the DetailView itself. You may extend from Yii's detail view to introduce the feature or simple wrap with HTML tags as @rob006 suggested.
