### ISSUE TITLE
Yii::$app->formatter->asDateTime(time(), 'php:'.DATE_ATOM) does not return the same as date(DATE_ATOM) 

### ISSUE THREAD

**Issue by MelleDijkstra** [yiisoft/yii2#13720]
### What steps will reproduce the problem?
Running the below code returns 2 different outcomes. Shouldn't it be the same? or am I missing something.
```
echo date(DATE_ATOM);
echo "<br />".Yii::$app->formatter->asDatetime(time(), 'php:'.DATE_ATOM);
die();
```
produces:
```
2017-03-07T22:22:40+01:00
2017-03-07\GMT+122:22:40+01:00
```
As you can see the `\T` doesn't get escaped and is evaluated as `\GMT+1`

### What is the expected result?
Expecting the same output for the yii2 formatter when using the `php:` format prefix.
```
2017-03-07T22:22:40+01:00
2017-03-07T22:22:40+01:00
```

### What do you get instead?
Instead the formatter doesn't escape the `\T` and evaluates it as `\GMT+1`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2 (development mode)
| PHP version      | PHP 5.6.21 (cli) (built: Apr 27 2016 20:13:54) <br/>**I really need to upgrade to 7 ;p**
| Operating system | Windows 10

**Comment by snedi** [comment]
It should be the same of course. Here is the [example from php docs](http://php.net/manual/en/class.datetime.php#datetime.constants.types)
DATE_ATOM
Atom (example: 2005-08-15T15:52:01+00:00)

Yes it seems that there is a problem with escaping. Would like to fix. Assign please.

**Comment by samdark** [comment]
@snedi feel free to work on it.

**Comment by cebe** [comment]
is that with or without intl extension installed? Looks like a problem with the format converter

**Comment by samdark** [comment]
This one looks to be relatively easy to cover with tests since @MelleDijkstra did a great job finding out exact conditions when it fails.

**Comment by samdark** [comment]
Reproduced.

**Comment by samdark** [comment]
The issue is in `BaseFormatConverter::convertDatePhpToIcu()`. Seems we can't solve the issue and keep using `strtr` at the same time.

**Comment by MelleDijkstra** [comment]
@cebe Yes I have the intl extension installed.
