### ISSUE TITLE
Multiple yii\* namespace roots hurts performance

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#13727]
This isn’t specifically an issue with the Yii framework itself, but affects both Yii and each of the 1st party Yii extensions on https://github.com/yiisoft, so this seemed like the best repo to post it in.

I just came across this article, [Optimizing Composer’s Autoload Performance][1], which analyzed the performance hit of PSR-4 autoloading when there are multiple conflicting root namespaces.

For example, Yii’s root namespace is `yii\`, and the Debug extension’s root namespace is `yii\debug\`. When loading a Debug class, such as `yii\debug\panels\AssetPanel`, Composer has to check two places:

- `yii2/debug/panels/AssetPanel.php`
- `yii-debug/panels/AssetPanel.php`.

These extra checks can add up:

> The framework developer can still help the application developer by providing very specific namespaces in each of its composer.json autoload section and by ensuring that each namespace is tied to only one package. This optimization is really worthwhile (22% increased performance in Mouf's case!)

There are two ways Yii/extensions could avoid this unnecessary performance loss: Either change Yii’s root namespace to `yii\framework\` (so nothing gets the root namespace of just `yii\`), or change the extensions’ root namespaces from `yii\x\` to `yiisoft\x\`. (My vote would be the latter.)

Changing root namespaces is a breaking change, so I’m not expecting an immediate resolution on this, but seems like a good thing to consider when starting work on Yii 3, if not before.

(And yes, I realize running `composer dump-autoload -o` will avoid this entire issue, but many people don’t know they should be running that, and it’s an easy thing to forget.)

[1]: http://mouf-php.com/optimizing-composer-autoloader-performance

**Comment by rob006** [comment]
> When loading a Debug class, such as yii\debug\panels\AssetPanel, Composer has to check two places

Are you sure about that? Debug extension has more specific namespace (`yii\debug`) so `yii2-debug/panels/AssetPanel.php` should be checked first (successfully). So we have only one check in this case.

**Comment by brandonkelly** [comment]
Hm, good point, I had forgotten that Yii registers its own autoloader, and just verified that extension aliases are getting added before `@yii`, so they are checked first. Nevermind me!

**Comment by rob006** [comment]
> I had forgotten that Yii registers its own autoloader

It doesn't matter, composer works in the same way - it prefer more specific namespaces. You can even release extension with `yii\debug\panel` namespace in `composer.json` and then composer will try load panels from your extension first, then from `yii2-debug`, and at the end will search framework code.

The problem that you describes exist only if multiple extensions uses global namespace directly - have such declaration i `composer.json`:

```json
    "autoload": {
        "psr-4": {
            "yii\\": ""
        }
    },
```
