### ISSUE TITLE
SluggableBehavior immutable option with Anonymous function fails

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2#13728]
### What steps will reproduce the problem?
1. Add the SluggableBehavior to a class
2. Set the value attribute to an annonymous function
3. set 'immutable' => true for the slug
4. Create a new record (RESULT Slug is generated correctly by the anonymous function)
5. Update the record created in (4)
 
### What is the expected result?
The old slug should stay unchanged, the anonymous function should not be called. The slug should not be replaced.

### What do you get instead?
A new slug is generated even though immutable is set to true

### Additional info
This is similar to #6430 except that an anonymous function was not used in that issue.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.30
| Operating system | Ubuntu

**Comment by Kolyunya** [comment]
Confirmed (https://github.com/Kolyunya/yii2/commit/c7c3ef93141db7a190b53db2640e711f1aeba7e9).
