### ISSUE TITLE
getQueryParams() method in yii.js fails on URL with question mark and no query parameters

### ISSUE THREAD

**Issue by vladdnepr** [yiisoft/yii2#13738]
### What steps will reproduce the problem?

1. Make GridView with filter in column
2. Enter some text, press Enter

### What is the expected result?

Filter must work without JS errors

### What do you get instead?

Filter not work.

In Console i see error "Uncaught TypeError: Cannot read property 'replace' of undefined"
![image](https://cloud.githubusercontent.com/assets/2308269/23753746/45b499f0-04e3-11e7-87b8-f686223af186.png)

This error appeared after this commit https://github.com/yiisoft/yii2/commit/17df7577a53ee2ac35d8e53ed87aaf03ce9309ac#diff-f433792b516845f488519deb1a72741aR293

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by vladdnepr** [comment]
JS context in error line
![image](https://cloud.githubusercontent.com/assets/2308269/23753931/f0fd72dc-04e3-11e7-91db-37bb3d5b4304.png)

**Comment by arogachev** [comment]
You should elaborate that for reproducing this issue with GridView initial URL must be like `/admin/capsules/index?` (that is with question mark only and no query parameters). And the core problem is in`getQueryParams()` in yii.js (which can be used separately). So I changed the title to better reflect problem for future reference.
