### ISSUE TITLE
session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/session)

### ISSUE THREAD

**Issue by miradnan** [yiisoft/yii2#13740]
### What steps will reproduce the problem?
I had 2.0.8 and I upgraded to 2.0.11
### What is the expected result?
It should allow me to browse the app instead it started throwing error
### What do you get instead?
session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/session)

<img width="1418" alt="screen shot 2017-03-09 at 9 02 40 pm" src="https://cloud.githubusercontent.com/assets/397415/23757239/3b7fc274-050c-11e7-9627-c08d51dfdb63.png">

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0.15
| Operating system | Ubuntu 14

**Comment by samdark** [comment]
Do you have permissions allowing your webserver user to access `/var/lib/php/session`?

**Comment by miradnan** [comment]
Yes. I gave it 777 even though it doesn't work. I have 2.0.8 working on the same machine and PHP config without any issues.

**Comment by samdark** [comment]
Well, "failed to write session data" means exactly what it's saying i.e. file could not be written by the user running PHP process. 2.0.8 was ignoring the fact and continue running with empty session. Current version throws this error to warn developer that it's not OK and session, in fact, isn't written.

You should check for permissions again and make sure that the user (usually `www-data`) can actually write to that directory.

**Comment by miradnan** [comment]
Alex,

I checked the folder permissions before I posted this as an issue. 
My sessions are stored in MySQL database. sessions doesn't even have to write to the folder in the first place. They should directly read and write in MySQL. I can share my session config if needed pls let me know 


Thanks,
Mir Adnan

**Comment by samdark** [comment]
Hmm...

> My sessions are stored in MySQL database.

But

> session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/session)

That doesn't seem to make sense. Do you have right config file loaded?

**Comment by miradnan** [comment]
Yes. The same config was working absolutely fine with 2.0.8. I upgraded and this issue came up.

Here is my sessions config.
<img width="361" alt="screen shot 2017-03-10 at 9 24 33 am" src="https://cloud.githubusercontent.com/assets/397415/23781450/684d5854-0573-11e7-9945-229af99731b2.png">

File common\db\DbSession contains
```php
namespace common\db;

use Yii;
use yii\db\Connection;
use yii\db\Query;
use yii\base\InvalidConfigException;
use yii\di\Instance;
use yii\web\MultiFieldSession;
use yii\web\ErrorHandler;
use yii\db\Exception;
use common\helpers\RequestHandler;
use common\components\BrowserComponent;

class DbSession extends \yii\web\DbSession {

    /**
     * Device Type 1
     */
    const DEVICE_TYPE = 1;

    /**
     *
     * @var type 
     */
    public $executed = false;

    /**
     * Session write handler.
     * Do not call this method directly.
     * @param string $id session ID
     * @param string $data session data
     * @return boolean whether session write is successful
     */
    public function writeSession($id, $data) {
        if ($this->executed) {
            return $this->executed;
        }
        $this->executed = true;

        // exception must be caught in session write handler
        // http://us.php.net/manual/en/function.session-set-save-handler.php
        try {
            $query = new Query;
            $exists = $query->select(['id'])
                    ->from($this->sessionTable)
                    ->where(['id' => $id])
                    ->createCommand($this->db)
                    ->queryScalar();
            $fields = $this->composeFields($id, $data);

            $fields['ip'] = RequestHandler::getIp();
            $fields['device_type'] = self::DEVICE_TYPE;
            $fields['device_info'] = BrowserComponent::getBrowser();

            if (!empty(Yii::$app->session['user']['id'])) {
                $fields['user_id'] = Yii::$app->session['user']['id'];
            }

            if ($exists === false) {
                $this->db->createCommand()
                        ->insert($this->sessionTable, $fields)
                        ->execute();
            } else {
                unset($fields['id']);
                $this->db->createCommand()
                        ->update($this->sessionTable, $fields, ['id' => $id])
                        ->execute();
            }
        } catch (\Exception $e) {
            $exception = ErrorHandler::convertExceptionToString($e);
            // its too late to use Yii logging here
            error_log($exception);
            echo $exception;

            return false;
        }

        return true;
    }

}
```

**Comment by miradnan** [comment]
@samdark - It works well if I don't override the writeSession method. The code is pretty much the same. All I am doing here is adding additional fields to session record.

**Comment by samdark** [comment]
Looks similar to https://github.com/yiisoft/yii2/issues/9438 with same reason of failure.
