### ISSUE TITLE
yii\db\query generates wrong SQL

### ISSUE THREAD

**Issue by SSiwek** [yiisoft/yii2#13744]
### What steps will reproduce the problem?
[...]
            ->andFilterWhere(['=', 'ABRECHNUNGSMODUS', $this->ABRECHNUNGSMODUS])
            ->andFilterWhere(['or', [ 'MANUELL' => null ], 	['!=', 'MANUELL', 'X'] 	 ]);

### What is the expected result?
[...]
AND ("ABRECHNUNGSMODUS" = 'manuell') AND ( ("MANUELL" is null )  OR ("MANUELL" != 'X') )

### What do you get instead?

[...]
 AND ("ABRECHNUNGSMODUS" = 'manuell') AND (("MANUELL" != 'X'))

In the Dokumentation ( http://www.yiiframework.com/doc-2.0/yii-db-query.html#where()-detail )
it is written : ['status' => null] generates status IS NULL.

Sven

**Comment by samdark** [comment]
That's because you're using `andFilterWhere()` and instead of `andWhere()`. `andFilterWhere()` skips the condition if the value is empty.
