### ISSUE TITLE
Can we optimize get table columns command?

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#13746]
I'm looking to debug and i saw yii2 everytime is trying to get table columns. but table columns not everytime changing. can we might do any cache system for that i'm just wondering?

![taslak](https://cloud.githubusercontent.com/assets/4962332/23798313/bfeb5136-05ac-11e7-99a9-ed9d8fa04be1.png)

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-tutorial-performance-tuning.html#enable-schema-caching
