### ISSUE TITLE
Test-suite fails with ICU 57.1

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#13750]
### What steps will reproduce the problem?

Run tests on a system with ICU 57.1
https://github.com/yiisoft/yii2/pull/13360#issuecomment-284504403

### What is the expected result?

Green tests

### What do you get instead?

Red tests, see https://travis-ci.org/yiisoft/yii2-docker/jobs/209762936#L2178

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | Any
| Operating system | Alpine LInux (Docker)

Running them on i.e. Debian with 52.1 is fine. See https://gitlab.com/yiisoft/yii2-docker/builds/11975020 or https://travis-ci.org/yiisoft/yii2-docker/builds/209762928

*Ignore the green alpine-7.1 build*

**Comment by samdark** [comment]
@schmunk42 I've adjusted tests a bit to tolerate valid ICU differences.

**Comment by schmunk42** [comment]
There are still some issues left: https://gitlab.com/yiisoft/yii2/builds/12180932

**Comment by schmunk42** [comment]
It looks to me like it does not use the new variations in the test data: https://gitlab.com/yiisoft/yii2/builds/12180932 - like it has no effect to check the ICU version.

Or do I get that wrong?

**Comment by samdark** [comment]
Weird but seems so.

**Comment by samdark** [comment]
I can re-do it other way.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/13797

**Comment by samdark** [comment]
@schmunk42 is that still the case?

**Comment by amarox** [comment]
Actual ICU version is 60.2

**Comment by schmunk42** [comment]
@amarox With which OS and PHP versions are you testing?

**Comment by schmunk42** [comment]
@samdark Could you review https://github.com/yiisoft/yii2/pull/15559 - it would greatly help for testing issues like this.

**Comment by samdark** [comment]
#15559 merged.

**Comment by schmunk42** [comment]
-  the builds on Travis still use ICU version `52.1` and are passing
- `-debian` builds (7.2) on GitLab use `57.1` and are passing https://gitlab.com/yiisoft/yii2-docker/-/jobs/48925154
- `-alpine` builds (7.2) on GitLab use `58.2` and are failing https://gitlab.com/yiisoft/yii2-docker/-/jobs/51069444 - but failed tests seem not related to ICU

So I think this can be closed.

**Comment by schmunk42** [comment]
> @amarox With which OS and PHP versions are you testing?

@amarox Are you on ArchLinux?

**Comment by amarox** [comment]
@schmunk42 docker
https://github.com/docker-library/php/blob/57b41cfc2d1e07acab2e60d59a0cb19d83056fc1/7.2/stretch/fpm/Dockerfile

**Comment by amarox** [comment]
ICU updated manually

**Comment by schmunk42** [comment]
@amarox Do you see errors on 60.2? Do we need to test it?

**Comment by amarox** [comment]
checked. no errors.
