### ISSUE TITLE
object not found

### ISSUE THREAD

**Issue by abhishek20195** [yiisoft/yii2#13753]
this is my main.php code
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
    'bootstrap' => ['log'],
    'modules' => [
          'api' => [ 
               'basePath' => '@app/modules/v1',
            'class' => 'backend\modules\api\Api',
        ],
    ],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the backend
            'name' => 'advanced-backend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
             
            'showScriptName' => false,
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'api\Employee'   // our country api rule,
                     
                ]
            ],
        ]
    ],
    'params' => $params,
];

###  
![image](https://cloud.githubusercontent.com/assets/25658904/23820876/9fd75d94-0648-11e7-8ac6-7eb592874277.png)
 
![image](https://cloud.githubusercontent.com/assets/25658904/23820886/fa09a1fa-0648-11e7-85be-033966f2cb65.png)

 plz give me solution

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by devmustafa** [comment]
Your configuration array misses the 'id' key.
`'id' => 'app-backend'`
