### ISSUE TITLE
Formatter::asDecimal() ignores NumberFormatter::MIN_FRACTION_DIGITS options

### ISSUE THREAD

**Issue by Oldeu** [yiisoft/yii2#13768]
I want to show max 2 fractional digits. I used the Formatter like this:
`Yii::$app->formatter->asDecimal($distance, 2, [\NumberFormatter::MIN_FRACTION_DIGITS => 0])`

### What is the expected result?

input | output
------------ | -------------
152.23641 | 152,24
152.7 | 152,7
152 | 152

### What do you get instead?

input | output
------------ | -------------
152.23641 | 152,24
152.7 | 152,70
152 | 152,00

The reason is when `$decimal` is **not** `null`, `NumberFormatter::MIN_FRACTION_DIGITS` and `NumberFormatter::MAX_FRACTION_DIGITS` will be overwritten. See [`createNumberFormatter` L1361 - L1371](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1349):

imo this should be altered to
```php
if ($decimals !== null) { //this should be done in first place
    $formatter->setAttribute(NumberFormatter::MAX_FRACTION_DIGITS, $decimals);
    $formatter->setAttribute(NumberFormatter::MIN_FRACTION_DIGITS, $decimals);
}
// set attributes
foreach ($this->numberFormatterOptions as $name => $value) {
    $formatter->setAttribute($name, $value);
}
foreach ($options as $name => $value) {
    $formatter->setAttribute($name, $value);
}
```
The actual behaviour is ignoring my explicit setting in this case. I know, changing this order would be inconsistent on systems with no intl enabled an others with intl enabled. But with no intl loaded this code isn't able to run beacause of missing class NumberFomatter, is it? I think this is a bug. I didn't test this with no intl enabled.

### Additional info

| Q                | A
| ---------------- | ----
 Yii version      | 2.0.11.2
 PHP version      | 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
 Operating system | Linux Mint 18

**Comment by rob006** [comment]
May be related to #13629

**Comment by Oldeu** [comment]
Just an info: I solved this by writing this: `\Yii::$app->formatter->asDecimal(round($this->distance, 2))`
I don't know which way should be preferred...

**Comment by samdark** [comment]
@Oldeu could you check ICU version in that environment?

```php
echo defined('INTL_ICU_VERSION') ? INTL_ICU_VERSION : 'no ICU';
```

**Comment by Oldeu** [comment]
@samdark result is 55.1

**Comment by cebe** [comment]
> asDecimal($distance, 2, [\NumberFormatter::MIN_FRACTION_DIGITS => 0])

You are setting $decimals explicitly in the second param, this will override the MIN/MAX_FRACTION_DIGITS setting, leave $decimals as null if you want to have it variable.
