### ISSUE TITLE
Menu::renderItems() throws exception if active item's class is defined as an array.

### ISSUE THREAD

**Issue by Pikseli** [yiisoft/yii2#13770]
### What steps will reproduce the problem?

Create a menu with an active item having class defined as an array. Exception is also thrown if item is first or last.

```php
echo \yii\widgets\Menu::widget([
    'activeCssClass' => 'item--active',
    'items' => [
        [
            'label' => 'Foo',
            'url' => '/foo',
            'active' => true,
            'options' => [
                'class' => [
                    'item',
                    'item--foo'
                ]
            ]
        ]
    ]
]);
```
### What is the expected result?

```html
<ul>
    <li class="item item--foo item--active"><a href="/foo">Foo</a></li>
</ul>
```

### What do you get instead?

PHP Notice – yii\base\ErrorException

Array to string conversion

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.1.0
| Operating system | macOS Sierra 10.12.3

**Comment by Kolyunya** [comment]
@Pikseli are you sure it's supposed to work as you expected? Could you please provide a reference to the docs?

**Comment by Kolyunya** [comment]
It's currently [no supported](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1836). Probably worth implementing.

**Comment by Kolyunya** [comment]
@Pikseli seems like it's [not supposed to work](http://www.yiiframework.com/doc-2.0/yii-widgets-menu.html#$itemOptions-detail) as you expect it. Should not throw exception though.

>options: array, optional, the HTML attributes for the menu container tag.

**Comment by samdark** [comment]
Yes. That would be consistent with `Html::tag()` with `class` option. Should be applied consistently through framework.
