### ISSUE TITLE
joinWith() fails with relations provided by behaviors attached via DI configuration

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#13779]
### What steps will reproduce the problem?

1. Create `\yii\db\ActiveRecord`, eg. `Post`, and override `instantiate()`:
```php
public static function instantiate($row) {
	return Yii::$container->get(static::class);
}
```
2. Create `\yii\base\Behavior`, eg. `PostBehavior`, which contains a new *user* relation for `Post`:
```php
public function getUser() {
	return $this->owner->hasOne(User::class, ['id' => 'user_id']);
}
```
3. Attach `PostBehavior` to `Post` using DI container definitions, eg.:
```php
'container' => [
	'definitions' => [
		'common\models\Post' => [
			'as myBehavior' => 'common\behaviors\PostBehavior',
		],
	],
],
```

4. Execute `Post::find()->joinWith('user')->all();`

### What is the expected result?

Everything works fine if `PostBehavior` is added directly inside `Post::behaviors()`, but fails when included through application's DI container definitions.

### What do you get instead?

>Invalid Parameter – yii\base\InvalidParamException
>common\models\Post has no relation named "user".

### Additional info

The problem appears to lie in [`\yii\db\ActiveQuery::buildJoinWith()`](https://github.com/yiisoft/yii2/blob/13de76714bd5482d0c2b9a68b7cb5d4977fc7bd0/framework/db/ActiveQuery.php#L439), where our ActiveRecord is being instantiated using `new $this->modelClass` rather than `Yii::createObject($this->modelClass)` thus causing the relations defined via DI-provided behaviors to be disregarded.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6
| Operating system | Ubuntu

**Comment by samdark** [comment]
Looks valid at the first sight. Would you like to fix it with a pull request containing the fix and a unit test? If yes then it has a chance to be merged into 2.0.12.

**Comment by lynicidn** [comment]
need change `AR::instantiate` too

**Comment by vercotux** [comment]
@samdark I'm working on the PR + unit tests as you requested.
@lynicidn Generally you should, yes, but it isn't relevant to this specific case so I omitted it.

**Comment by lynicidn** [comment]
try
$post = new Post();
$user = User::findOne();
$post->link('user', $user);
you also get exception that user relation not found

**Comment by vercotux** [comment]
Read my post again.

**Comment by lynicidn** [comment]
if you want change logic for create models - it need do for all cases

**Comment by lynicidn** [comment]
best way:
```php
Event::on(Post::class, 'init', function(ModelEvent $e) {
$e->sender->attachBehavior($myBehavior); 
});
```
this global work for all cases and don't break active record design

**Comment by vercotux** [comment]
@lynicidn This issue is about attaching behaviors via configuration, which is an officially supported feature in Yii2, so one would expect it to work consistently. The issue highlights a case in which the official feature breaks.

That said, your approach is very different and sounds like it can work. By the way, where would you put your code to ensure it is always run before any controllers/components etc?

**Comment by lynicidn** [comment]
read from here https://github.com/yiisoft/yii2/issues/5786#issuecomment-192049982

**Comment by vercotux** [comment]
@lynicidn That does not answer my question at all.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/6808
