### ISSUE TITLE
Session data being cleared when user is still logged in (by autologin)

### ISSUE THREAD

**Issue by jhon100** [yiisoft/yii2#13777]
I'm using DbSession and in configuration only set the class (yii\web\DbSession).
I'm storing a simple data in session that is being cleared after a short time. 

The issue is that if the user check the 'remember me' he will be logged in for a long time.

Changing the timeout in config will not help because if the user does not check the 'remember me', loggin session must terminate in a short time (lets say 3 hours). But this 3 hours will affect the session data of the user that choosed autologin.

Could you add some check in the core to not clear the session if user is still logged in? (by autologin)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12-dev
| Operating system |windows 10

**Comment by samdark** [comment]
Autologin is not connected to session at all. What it does is storing a token in a cookie and using that token to log in again with a totally different session. If you need to store user data forever or between different sessions, use proper persistent storage such as database.
