### ISSUE TITLE
How to add custom attributes in <link> tag

### ISSUE THREAD

**Issue by jagroop** [yiisoft/yii2#13786]
I want to add attribute media="screen" in <link> tag, all assets paths are defined in AppAsset.php file
```php
 public $css = [

               'frontend/web/css/site.css',

		'frontend/web/css/custome.css',

		'frontend/web/css/font-awesome.css',

		'frontend/web/css/jquery.bxslider.css',        

    ];
```
i see no room for that, i have also checked documentation but found nothing.

[Docs](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html)

### What is the expected result?

```html
<link href="/assets/597be7e4/css/bootstrap.css" rel="stylesheet" media="screen">
```

### What do you get instead?
```html
<link href="/assets/597be7e4/css/bootstrap.css" rel="stylesheet">
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 7.0.1
| Operating system | Ubuntu 14.04

Thanks !!!

**Comment by Aradiv** [comment]
there is the [$cssOptions ](http://www.yiiframework.com/doc-2.0/yii-web-assetbundle.html#$cssOptions-detail)

so you can define 

`public $cssOptions = ['media' => 'screen'];`

this will add media="screen" to all css files in this assetBundle.

If you want to have different media types i would suggest to create a seperate bundle per media and require the media bundles in the main bundle.

**Comment by samdark** [comment]
You can also specify options as

```php
['frontend/web/css/site.css', 'media' => 'screen']
```

It's documented: http://www.yiiframework.com/doc-2.0/yii-web-assetbundle.html#$css-detail

**Comment by jagroop** [comment]
thanks @Aradiv @samdark  :)
