### ISSUE TITLE
Joined Gridview shows fewer records

### ISSUE THREAD

**Issue by lowap** [yiisoft/yii2#13782]
### What steps will reproduce the problem?

ModelQuery:

    public function mq() {
        $this->select([
                    '*',
                    'TRIM(TRAILING \'.\' FROM TRIM(TRAILING \'0\' FROM adn)) AS adn',
                    'TRIM(TRAILING \'.\' FROM TRIM(TRAILING \'0\' FROM fdn)) AS fdn',
                    'TRIM(TRAILING \'.\' FROM TRIM(TRAILING \'0\' FROM zgn)) AS zgn',
                ])
                ->leftJoin('mq', 'mqid = mq.id');
        return $this;
    }

ModelSearch:

    public function search($params) {
        $query = Za::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query->mq(),
            'sort' => ['defaultOrder' => ['aonr' => SORT_DESC]],
            'pagination' => [
                'pageSize' => 15,
            ],
        ]);

### What is the expected result?

15 records on one page

### What do you get instead?

3, 3, 3, 6, 4, 3 etc. records on one page
> Zeige 1-3 von 9.802 Einträgen.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.25
| Operating system | Windows Server 2012 R2

**Comment by TerraSkye** [comment]
probably a join fault. (showing less records)

**Comment by lowap** [comment]
I've checked the (simple) query and it seems to be alright. totalCount is also alright.

**Comment by samdark** [comment]
Can't be reproduced without tables schema, data model code and exact queries. It would be great if you'll be able to find the reason for it.

**Comment by lowap** [comment]
I've figured it out that if I'm doing like this:

    public function mq() {
        $this->select([
                'za.*',
                ...
            ])
            ->leftJoin('mq', 'mqid = mq.id');
    return $this;
    }
then it's rendering normally 15 records. Without `za.` it's not working. I have no clue why I'm absolutely not an expert in oop or yii, sorry.

**Comment by TerraSkye** [comment]
do u have a group by somewhere?

**Comment by lowap** [comment]
nope. that's all:

    SELECT `za`.*, ... `lwnr`
    FROM `za`
    LEFT JOIN `mq` ON za.mqid = mq.id
    ORDER BY `aonr` DESC
    LIMIT 15

**Comment by githubjeka** [comment]
Probably populate doesn't work correctly....
Can u show rawSql from your $query and executed result of raw sql ?

**Comment by lowap** [comment]
rawSql? it's above your comment, isn't it, or do you mean something else?
But this is interesting:
![compared](https://cloud.githubusercontent.com/assets/25388044/23952787/ddfb925a-0992-11e7-95cf-0a91b192c211.jpg)
The join section. However it's the same in both cases but why is it 2x? Other than that there is no difference in var_dump().

**Comment by TerraSkye** [comment]
Do you have an index by on the model?that would cause thrm to overwrite eachother

**Comment by lowap** [comment]
I don't think so. I'm not that professional to use such things.

**Comment by githubjeka** [comment]
No.
http://www.yiiframework.com/doc-2.0/yii-db-command.html#getRawSql()-detail

**Comment by lowap** [comment]
SELECT *, TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM adn)) AS adn, TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM fdn)) AS fdn, TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM zgn)) AS zgn, `lwnr` FROM `za` LEFT JOIN `mq` ON za.mqid = mq.id

**Comment by githubjeka** [comment]
and raw result. From phpadmin for example...

**Comment by bizley** [comment]
I'm almost sure there are duplicated rows because of the joined relation. Some `mq` table rows probably are related to the same `za` table row and because there is no `indexBy` set in query the default one is taken which is primary key here. Since the same key in array is there more than once every duplication overwrites the previous one hence the less rows displayed per page.

See [this line in ActiveQuery](https://github.com/yiisoft/yii2/blob/2.0.11.2/framework/db/ActiveQuery.php#L212).

**Comment by lowap** [comment]
In `mq` there are only distinct records. I'm joining on ids, and selecting only **lwnr** what is a varchar, so it's not the primary key (only a unique index), so it's not the auto incr **id** of the table.

**Comment by bizley** [comment]
I'm confused. There is no distinct statement in your query and you select all columns (*). Simple way to check if there are any duplicates is to fetch data using the same query outside of Yii framework or to use Query methods instead of ActiveQuery (so no models) - Query does not remove duplicates if there is no `indexBy`.

**Comment by lowap** [comment]
phpmyadmin is forbidden at the moment and I have no idea how can I make it work. Can I do it somehow in Sqlyog?

**Comment by samdark** [comment]
Yes. With SQL.

**Comment by bizley** [comment]
I'm not familiar with this one. You can do this in mysql console if you have got access there or call something like this as a test in your Yii application:

    $data = Yii::$app->db->createCommand(/* query here */)->queryAll();

and see what is inside `$data`.

**Comment by lowap** [comment]
I have `za`, it's the main table that I'm querying. It has 164 records. I'm `left join`-ing the table `mq` (where only distinct values can be found) on the foreign key **mqid**, and I'm just selecting a `varchar` from `mq`. So in the end I have this:

id | a1 | a2 | ... | lwnr
| -- | -- | -- | -- | ---
01 | xx | yy | ... | lw1
02 | ab | cd | ... | lw1
03 | ds | ff | ... | (null)
04 | ee | rr | ... | lw111
05 | gf | tg | ... | (null)

There can't be any duplicates. This is 100% sure.
This is a hell lot of data! Should I paste here all of them?

**Comment by rob006** [comment]
> then it's showing 15 records, but the ids are still wrong: they are coming still from mq. 

Do you have `zaid` column in `mq`?

**Comment by lowap** [comment]
no, I don't, but it's clear now:

> Note: It is important to disambiguate column names when building relational queries involving JOIN SQL statements. A common practice is to prefix column names with their corresponding table names.

Until now I haven't done so but now it's time. However as I remember I have read somewhere before (maybe not about yii) that it's a good practice to use simply id, col1, col2, etc.
Yeah I've found it: [http://www.yiiframework.com/wiki/227/guidelines-for-good-schema-design/](url)

- DON'T prepend db table names to field names

however it stays clearly there that it's meant to be only for AR, it would be nice to mention that if we want to use JOINs it should be otherwise (are there any applications, that don't use JOINs? or appr. how many percent?)
- DO name a table's own ID column "id"

**Comment by SilverFire** [comment]
I've failed to reproduce the problem it and I have no ideas why are you facing it.

@lowap in case you still experience this problem, could you help us reproduce this problem with a unit test?

**Comment by freddokresna** [comment]
i got this problem too

it's quite difficult to explain it in words,hope you guys get it via image i share

the raw sql was correct, but the gridview eliminated "duplicated"

![2023-03-09 17_39_35-Mozilla Firefox](https://user-images.githubusercontent.com/753514/223999811-ea36cde1-71fa-412c-b8af-d0b0b9cde851.png)
![2023-03-09 17_39_15-MySQL Workbench](https://user-images.githubusercontent.com/753514/223999795-259d8622-3ae4-4935-87e6-90ed5507ec53.png)
![2023-03-09 17_39_04-MySQL Workbench](https://user-images.githubusercontent.com/753514/223999802-2f94efdb-35ff-4bd6-8e26-d20c4d59b065.png)

**Comment by freddokresna** [comment]
![2023-03-09 17_44_37-mobil - Apache NetBeans IDE 16](https://user-images.githubusercontent.com/753514/224000839-3a53c862-6a52-4eb8-8ce3-65237ee26928.png)
this is how i query on yii2

**Comment by bizley** [comment]
Please do not necro old issue, you can always ask at our forum. This was already answered - you are fetching the models here and since these are the same models, duplicates are not listed. You need to change the context or use SqlDataProvider.
