### ISSUE TITLE
Expire timestamp on RBAC assignments

### ISSUE THREAD

**Issue by vschettino** [yiisoft/yii2#13789]
I think it would be awesome if the Yii2's RBAC manager could handle a expire timestamp while we assign a role to a user. Probably it's a common needed feature, and I can't see a good workaround without changing de framework's core. Something like that:

`$auth = Yii::$app->authManager;`
`$auth->assign($author, 2, 1272509157); `

It might break some BC, so the method for doing it should be broadly discussed. First I thought about adding a column `expire_timestamp` at `auth_assignment` table and changing the  `yii\rbac\ManagerInterface` and those classes who implement it.

**Comment by samdark** [comment]
I think it's out of scope of RBAC. If I'd need something like that I'd schedule jobs (either by cron or otherwise) which would use `yii\rbac\ManagerInterface` to remove certain roles.

**Comment by vitorhorta** [comment]
@samdark I think we could avoid overengineered solutions for many cases if RBAC could handle temporary assignments.

**Comment by samdark** [comment]
Another way to achieve that is via a custom Rule which has an expiration time as argument. You put it between role and permissions in RBAC hierarchy. Additionally you can pass user as an argument. This way you'll be able to expire particular assignments.

Overall I don't think that expiring roles or assignments is common requirement. Googling displayed only one result of kind of weird system where there was an ability to expire role (not assignment). If you have some references proving that it's common, I'd like to get these.

**Comment by samdark** [comment]
Till then closing the issue.

**Comment by vschettino** [comment]
@samdark I do know some softwares that offers the ability of expiring role atributions. For instance, we have [OpenProject](https://www.openproject.org/enterprise-edition/#tab-expiration-dates) and Gitlab [8.11](https://about.gitlab.com/2016/08/22/gitlab-8-11-released/).  [Laravel](https://github.com/artesaos/defender) and [Drupal](https://www.drupal.org/project/role_expire) seems to have solutions that support this kind of feature as well.

There's some ways to implement this kind of feature, like @samdark and @vitorhorta have shown. But they would be likely less graceful and more work intensive than having it built-in on the core.

**Comment by samdark** [comment]
Checked OpenProject. It has expiration dates for project membership which can't be solved via adding expiration timestamps to RBAC. Same about GitLab. Could be solved with custom Role though.

That unofficial Drupal module is exactly my first variant with crontab.

Unofficial Laravel module isn't flexible and covers only one use case to temporarily assigning a single permission directly to user which is considered RBAC bad practice.

**Comment by vschettino** [comment]
I got these links to show that this is a common feature. I think we should discuss whether rbac module should support this or not. I don't think using cronjobs or custom Rules, would be the best way of doing it since we would need more tables, code and dependencies for implement like that.

**Comment by samdark** [comment]
Adding timestamps basically won't solve majority of cases when you need to grant temporary permission to edit a certain model.

**Comment by drigos** [comment]
I didn't understand the statement regarding the model.

**Comment by samdark** [comment]
OK. We have a blog. I need to give a temporary permission limited to 10 hours to edit post "Hello, world!" to user "drigos". How would I do it with RBAC?

**Comment by vitorhorta** [comment]
We would assign the temporary permission or role to "drigos" by simply:

`$auth->assign('post/edit',$drigos->id,TEN HOURS)`

And to make sure he can only edit a specific post we use rules.
I can't see a better way to do this without RBAC help.

**Comment by samdark** [comment]
1. You can assign `post/edit` to multiple users at the same time.
2. Expiration time is unique per user + post.
3. It can't be stored within permission because permission is applied differently for each user.
4. You're using Rule anyway so why not to handle expiration there as well as post ID check?

**Comment by samdark** [comment]
So, as I said, Rule solves it well in any variation possible and there are many.

**Comment by terciogarcia** [comment]
Indeed, Rules can deal with it, but it demands much more engineering than a build-in solution. 
Mainly when it involves many use cases.

**Comment by samdark** [comment]
How would you implement build-in solution within RBAC for the case I've described? i.e. we want to give a temporary permission to edit post=Hello to user=Alex and post=World to user=Carsten.
