### ISSUE TITLE
Inputmasks stopped working after Yii 2.0.11 update beacuse of a bug in jquery.inputmask plugin

### ISSUE THREAD

**Issue by arturszulc** [yiisoft/yii2#13790]
### What steps will reproduce the problem?
1. Create a view with masked input using following configuration:
```php
$input->widget(\yii\widgets\MaskedInput::className(), [
                'clientOptions' => [
                    'alias' => 'currency',
                    'prefix' => false,
                ],
            ])
```
2. Load page and look at javascript console.

### What is the expected result?

Input with inputmask works as expected.

### What do you get instead?

Inputmask does not work correctly, throws an error at JavaScript console:
`Uncaught TypeError: str.replace is not a function`

Due to this all other Javascript-dependent functions stop working (other plugins, widgets etc.).

### Additional info

I managed to establish that:

- bug does not happen on Yii 2.0.10, because of jquery.inputmask plugin version 3.2.7 is used
- bug is related to #11906 

There is no timeline when this will be fixed in jquery.inputmask plugin. However, Yii's composer.json states that older version of jquery.inputmask can be installed
```json
"bower-asset/jquery.inputmask": "~3.2.2 | ~3.3.3"
```
so user can force installing older version by adding
```json
"bower-asset/jquery.inputmask": "~3.2.2"
```
to the composer.json in app's main directory. It should be noted in upgrades section.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.30
| Operating system | Windows (browser), Linux (server)

**Comment by davidjeddy** [comment]
See https://github.com/RobinHerbots/jquery.inputmask/issues/2 the inputmask library is not longer available. From what I can tell it 'was' working due to github aliasing the package. Now the alias is released composer is failing to install.
