### ISSUE TITLE
GettextMessageSource is deleting entries with removeUnused=false

### ISSUE THREAD

**Issue by particleflux** [yiisoft/yii2#13792]
### What steps will reproduce the problem?

application config:

```
'i18n' => [
            'translations' => [
                '*' => [
                    'class' => 'yii\i18n\GettextMessageSource',
                    'basePath' => dirname(dirname(__DIR__)) . '/messages',
                    'useMoFile' => false,
                ],
            ],
        ],
```

- message source set to po files
- i18n config with `removeUnused => false` and `format => po`
- execute message/extract with said config

### What is the expected result?

unused entries should stay in the translation file

### What do you get instead?

unused entries are deleted

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0.14
| Operating system | Gentoo

**Comment by samdark** [comment]
Added test that verifies that it works as expected.

**Comment by samdark** [comment]
Are you on HHVM?
