### ISSUE TITLE
Add INSERT INTO SELECT support

### ISSUE THREAD

**Issue by JQueryBoy14** [yiisoft/yii2#13807]
there is an issue regarding this added function.

I tried a query like ***insert into ... select ... from ... where ...***

An error says ***[Microsoft][ODBC Driver 11 for SQL Server]COUNT field incorrect or syntax error***

### What steps will reproduce the problem?
***Yii::$app->db->createCommand()->insert(Class1::tableName(), Class2::find()
->select([ ... ])
->where([ 'id' => 1 ])
)->execute()***

### What is the expected result?
***insert into table1 ( ... ) select ... from table2 where id = 1***

### What do you get instead?
An error says ***[Microsoft][ODBC Driver 11 for SQL Server]COUNT field incorrect or syntax error***

but when i check my SQL logs, it prints the query but it is not yet prepared like
***insert into table1 ( ... ) select ... from table2 where id = :qp0***

### Additional info
I tried removing where condition and it works:

***Yii::$app->db->createCommand()->insert(Class1::tableName(), Class2::find()->select([ ... ]))->execute()***

| Q                | A
| ---------------- | ---
| Yii Version | ***2.0.11.2***
| PHP Version| ***5.6.15***
| Operation System | ***MS Windows 8.1***

**Comment by samdark** [comment]
Does it work with conditions at all in MSSQL?

**Comment by sergeymakinen** [comment]
It does: https://technet.microsoft.com/en-us/library/ms189872(v=sql.105).aspx
I suspect there's something with escaping. I can take a look.

**Comment by sergeymakinen** [comment]
@JQueryBoy14 do you have unique placeholders in your query: http://stackoverflow.com/a/34158696?

**Comment by JQueryBoy14** [comment]
if **placeholder** means **bind values/parameters**

i think i have a **unique** placeholder which is **:qp0**.

This was generated by yii itself when i use the AR

**Comment by sergeymakinen** [comment]
@JQueryBoy14 I see, thanks.

I confirm this. Works okay without preparing, fails with preparing. I look through it.

**Comment by sergeymakinen** [comment]
I have opened #13843 to fix this.
