### ISSUE TITLE
error during install fxp 

### ISSUE THREAD

**Issue by ibrahimcougar** [yiisoft/yii2#13803]
### What steps will reproduce the problem?
composer global require "fxp/composer-asset-plugin:^1.2.0" or
composer global require "fxp/composer-asset-plugin:*"
### What do you get instead?
`PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Package\RootPackage::getConfig() in /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php:111
Stack trace:
#0 /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php(74): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::getConfigBase(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/FxpAssetPlugin.php(82): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::build(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 /usr/share/php/Composer/Plugin/PluginManager.php(215): Fxp\Composer\AssetPlugin\FxpAssetPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 /usr/share/php/Composer/Plugin/PluginManager.php(188): Composer\Plugin\PluginManager->addPlugin(Object(Fxp\Composer\AssetPlugin\FxpAssetPlugin))
#4 /usr/share/php/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object in /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php on line 111

Fatal error: Uncaught Error: Call to undefined method Composer\Package\RootPackage::getConfig() in /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php:111
Stack trace:
#0 /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php(74): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::getConfigBase(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/FxpAssetPlugin.php(82): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::build(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 /usr/share/php/Composer/Plugin/PluginManager.php(215): Fxp\Composer\AssetPlugin\FxpAssetPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 /usr/share/php/Composer/Plugin/PluginManager.php(188): Composer\Plugin\PluginManager->addPlugin(Object(Fxp\Composer\AssetPlugin\FxpAssetPlugin))
#4 /usr/share/php/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object in /home/ic/.config/composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php on line 111
`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      |  7
| Operating system | ubuntu 16.04.2

**Comment by samdark** [comment]
Try `composer self-update`.

**Comment by ibrahimcougar** [comment]
sorry for late 
i tried 
`composer self-update   `
and the result is 
`  [InvalidArgumentException]             
  Command "self-update" is not defined.  
`
this problem is new i am using yii2 for 8 month 
i think the problem is with fxp version 1.3.0

thanks.

**Comment by samdark** [comment]
Hmm...

```
composer self-update --no-plugins
```

**Comment by mbraidy** [comment]
I have the same problem, and when I tried
`composer self-update --no-plugins`
I got 
 **[InvalidArgumentException]             
  Command "self-update" is not defined.**

**Comment by devmustafa** [comment]
can you remove `~/.composer/cache` and try to install again.

**Comment by mbraidy** [comment]
it did not work
after deleting the cache and after `sudo composer update`, I got the following output

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing fxp/composer-asset-plugin (v1.3.0)
    Downloading: 100%         

PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Package\RootPackage::getConfig() in /home/michel/www/integral.is/_protected/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php:111
Stack trace:
#0 /home/michel/www/integral.is/_protected/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php(74): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::getConfigBase(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 /home/michel/www/integral.is/_protected/vendor/fxp/composer-asset-plugin/FxpAssetPlugin.php(82): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::build(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 /usr/share/php/Composer/Plugin/PluginManager.php(215): Fxp\Composer\AssetPlugin\FxpAssetPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 /usr/share/php/Composer/Plugin/PluginManager.php(188): Composer\Plugin\PluginManager->addPlugin(Object(Fxp\Composer\AssetPlugin\FxpAssetPlugin))
#4 /usr/share/php/Composer/Installer/PluginInstaller.php(62): Composer\Pl in /home/michel/www/integral.is/_protected/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php on line 111

**Comment by ibrahimcougar** [comment]
me too still not work....

**Comment by frazelli** [comment]
How did you install the composer? If you used apt-get, just remove it `apt-get remove composer` 
And install by using command 
`curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer`.
It will fix the issue.

**Comment by mbraidy** [comment]
Thank you Alex
that solve the problem

**Comment by ChangePlaces** [comment]
for ubuntu (path difference):

``` curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer.```
