### ISSUE TITLE
PostgreSQL. wrong json data escaping in SQL

### ISSUE THREAD

**Issue by rgen3** [yiisoft/yii2#13808]
### What steps will reproduce the problem?
When trying to batchInsert into PostgreSQL json formatted data, which includes double curly brackets I've got wrong sql formatting
```php
$items = [
  ['json' => '{"param" : "1", "param" : "{{value}}"}', 'id' => 1]
];
```
```php
 $command = $this->db->createCommand()->batchInsert(
                    ModelName::getTableSchema()->name,
                    array_keys($items[0]),
                    $items
                );
```
### What is the expected result?
Expected sql statement is
```sql
INSERT INTO table (id, json) VALUES (1,  '{"param" : "1", "param" : "{{value}}"}');
```
### What do you get instead?
```sql
INSERT INTO table (id, json) VALUES (1,  '{"param" : "1", "param" : ""}');
```
### Additional info

The problem is in quoteSql method of yii\db\Connection class.
( https://github.com/yiisoft/yii2/blob/master/framework/db/Connection.php#L846 )

Regex pattern replaces the values, not the table name
```php
'/(\\{\\{(%?[\w\-\. ]+%?)\\}\\}|\\[\\[([\w\-\. ]+)\\]\\])/',
```
I used the next solution to fix this:

Created file "Connection" in components directory, then implemented my Connection class by default yii2 Connection. 

```php
namespace common\components;

class Connection extends \yii\db\Connection
{}
```

And override the quoteSQL method

```php
public function quoteSql($sql)
    {
        return preg_replace_callback(
            '/(\\{\\{(%[\w\-\. ]+%?)\\}\\}|\\[\\[([\w\-\. ]+)\\]\\])/',
            function ($matches) {
                if (isset($matches[3])) {
                    return $this->quoteColumnName($matches[3]);
                } else {
                    return str_replace('%', $this->tablePrefix, $this->quoteTableName($matches[2]));
                }
            },
            $sql
        );
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1
| Operating system | CentOS 7

**Comment by rgen3** [comment]
The problem is not only with Postgresql, but with quoteSql method of yii\db\Connection class.
For example I use this statement

```
$command = Yii::$app->db->createCommand("
  INSERT INTO texts
  SET field1=\"you should use utm_media=[[square_quotes]]\", 
  field2=\" or you could use utm_source={{other_quotes}}\""
)
```

And I want $command->rawSql to be 
```
 INSERT INTO texts
  SET field1="you should use utm_media=[[square_quotes]]", 
  field2=" or you could use utm_source={{other_quotes}}"
```

But I get
```
INSERT INTO texts 
SET field1="you should use utm_media=`square_quotes`", 
field2=" or you could use utm_source=`other_quotes`"
```

**Comment by samdark** [comment]
Ah... Both `[[` and `{{` are special symbols in Yii and should be escaped: http://www.yiiframework.com/doc-2.0/guide-db-dao.html#quoting-table-and-column-names

**Comment by rgen3** [comment]
And what about batchInsert?

@samdark thank you for the answer, but I found that problem may be not in the createCommand, but in 
batchInsert

For example, I use the following code 

```
$data = [
            [
                'key' => 'value',
                'text' => 'this is the {{text}}'
            ]
        ];

$sql = Yii::$app->db->createCommand()->batchInsert('tableName', array_keys($data[0]), $data)->rawSql;
$sql = Yii::$app->mysql->createCommand()->batchInsert('tableName', array_keys($data[0]), $data)->rawSql;
```

And I've got 

```
'INSERT INTO "tableName" ("key", "text") VALUES ('value', 'this is the "text"')' 
'INSERT INTO `tableName` (`key`, `text`) VALUES ('value', 'this is the `text`')'
```

For quoting it uses 

```
vendor/yiisoft/yii2/db/Schema.php
public function quoteValue($str)
    {
        if (!is_string($str)) {
            return $str;
        }

        if (($value = $this->db->getSlavePdo()->quote($str)) !== false) {
            return $value;
        } else {
            // the driver doesn't support quote (e.g. oci)
            return "'" . addcslashes(str_replace("'", "''", $str), "\000\n\r\\\032") . "'";
        }
    }
```

And in this method no brackets is escaped?


BatchInsert method have to escape special characters, isn't it? 
And the JSON data type is available in MySQL >= 5.7

**Comment by starhobbit** [comment]
This problem is not PG related - it's Yii2 related. And problem is only in batchInsert

**Comment by starhobbit** [comment]
https://github.com/yiisoft/yii2/issues/11242

**Comment by samdark** [comment]
Yes. It's a duplicate. Thanks for finding it out.
