### ISSUE TITLE
Allow FindOne to accept complex where conditions

### ISSUE THREAD

**Issue by enigmatix** [yiisoft/yii2#13804]
The FindOne method checks to see if an array is associative, and if so, prepares a where clause based on the associative array.  Otherwise, it will try to fetch a record based on the integer value of the variable.

I would expect that the findOne method instead checks to see if the variable is an array of any type, rather than just associative.  This would allow for all types where conditions to be supported.

### What steps will reproduce the problem?

Have a table with 2 user records, user id 1 and user id 2 and:

`$user = User::findOne(['!=','id',1]);
`
### What is the expected result?

`echo $user->id; // prints 2;
`
### What do you get instead?

`echo $user->id; // prints 1;
`
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6
| Operating system | Ubuntu

**Comment by samdark** [comment]
The current behavior is not correct indeed. It should either support complex conditions or throw an exception.

**Comment by Kolyunya** [comment]
All "*non-associative*" arrays are currently treated as primary key. I can't see a straightforward fix for that...

```php
    protected static function findByCondition($condition)
    {
        $query = static::find();

        if (!ArrayHelper::isAssociative($condition)) {
            // query by primary key
            $primaryKey = static::primaryKey();
            if (isset($primaryKey[0])) {
                $pk = $primaryKey[0];
                if (!empty($query->join) || !empty($query->joinWith)) {
                    $pk = static::tableName() . '.' . $pk;
                }
                $condition = [$pk => $condition];
            } else {
                throw new InvalidConfigException('"' . get_called_class() . '" must have a primary key.');
            }
        }

        return $query->andWhere($condition);
    }
```

**Comment by cebe** [comment]
I do not think there is a reliable way to distinguish between a string primary key value or a string that could have been meant to be a condition. The docs are very clear about what the parameters expect imo.

**Comment by enigmatix** [comment]
I should point out that my request was to support complex 'where' arrays, not a complex condition as a string.  I agree that it should not support complex string conditions.  Couldn't this be achieved simply changing 

`ArrayHelper::isAssociative($condition)` to `is_array($condition)` @ line 174?

As then, the array will be automatically handled at `return $query->andWhere($condition);` whether there are complex conditions or not.

**Comment by cebe** [comment]
The array syntax accepted by where() is significantly different from what an array means for findOne().

**Comment by enigmatix** [comment]
I take it you are referring to this from the docs:

[Docs link
](http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findOne()-detail)
> Returns a single active record model instance by a primary key or an array of column values.

I understand the difference in philosophy now.  It's unfortunate, as findOne and andWhere share a common execution pathway, as findOne _calls_ andWhere, and I maintain the functionality would be easily supported without any BC breaks.

It should definitely throw an exception when supplied with a non-associative array then.  As per the original re-producable steps, I would not expect that this functionality is intended:

`
$user = User::findOne(['!=','id',1]);
echo $user->id; //prints 1
`

**Comment by samdark** [comment]
Yes, throwing an exception is an option.

**Comment by rob006** [comment]
Throwing exception will break BC - support for non-associative arrays is mentioned even in method phpdoc.

**Comment by samdark** [comment]
Right right.

**Comment by enigmatix** [comment]
I see, yes, apologies for the hassle.  It does say it in the phpdoc.  I think the example could be clearer.   Are you happy for me to submit a pull request for a more complete phpdoc?

**Comment by samdark** [comment]
Yes.

**Comment by enigmatix** [comment]
PR [14002](https://github.com/yiisoft/yii2/pull/14002) created
