### ISSUE TITLE
Wrong items per page + total count when using groupBy and sorting on column other than hasMany viaTable m2m column

### ISSUE THREAD

**Issue by GlyphDataServices** [yiisoft/yii2#13800]
Edit- Please see the attachments below.  I reduced this to a minimal working example and attached all the required files to my latest comment.  
~ 

I have a search model organisms with a basic m2m relation and another hasOne relation. organisms hasMany programs, viaTable organismsPrograms.

```
tbl organisms
----------------
id | name | external_institution_id
```

```
tbl organisms_programs
------------------
organism_id | program_id
```

```
tbl programs
----------------
id | name
```

organisms also hasOne externalInstitution

```
tbl externalInstitutions
----------------
id | name
```

Organisms model relations

```
    public function getExternalInstitution()
    {
        return $this->hasOne(Institutions::className(), ['id' => 'external_institution_id'])->alias('externalInstitution');
    }

    public function getOrganismsPrograms()
    {
        return $this->hasMany(OrganismsPrograms::className(), ['organism_id' => 'id'])->alias('organismsPrograms');
    }

    public function getPrograms()
    {
        return $this->hasMany(Programs::className(), ['id' => 'program_id'])->viaTable('organisms_programs', ['organism_id' => 'id'])->alias('programs');
    }
```

OrganismsSearch method: 

 ```
 public function search($params,$settings=false)
    {
        // sorting on m2m relation causes incorrect items per page count.  

        $query = Organisms::find()
                    ->alias('t')

        // same problem exists with false/true for eager/lazy loading
        $query->joinWith('programs',false,'LEFT JOIN');
        $query->joinWith('organismsPrograms',false,'LEFT JOIN');
        $query->joinWith('externalInstitution',true,'LEFT JOIN');


        $query->groupBy('t.id');
        $s=Yii::$app->request->get('sort');
        // for m2m relations, only set groupBy if we're actually sorting on that relation
        if ( $s == 'organismsPrograms.program_id' || $s == '-organismsPrograms.program_id')
            $query->addGroupBy('organismsPrograms.program_id');
        $query->addGroupBy('externalInstitution.name');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort'=> ['defaultOrder' => $defaultOrder],
        ]);

        $this->load($params);

        // sort only on the pivot table, not the m2m model- breaks ipp count
        $dataProvider->sort->attributes['organismsPrograms.program_id'] = [
            'asc' => ['organismsPrograms.program_id' => SORT_ASC],
            'desc' => ['organismsPrograms.program_id' => SORT_DESC],
        ];
        $dataProvider->sort->attributes['externalInstitution.name'] = [
            'asc' => ['externalInstitution.name' => SORT_ASC],
            'desc' => ['externalInstitution.name' => SORT_DESC],
        ];


        if (!$this->validate()) {
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere(['t.id' => $this->id])
            ->andFilterWhere(['in', 't.external_institution_id', $this->externalInstitutionSelect])
            ->andFilterWhere(['in', 'programs.id', $this->programSelect])

        // this has no effect on items per page count
        //$countQuery = clone $query;
        //$pagination = new Pagination(['totalCount' => $countQuery->count(),'defaultPageSize'=>5]);
        //$dataProvider->setPagination($pagination);

        return $dataProvider;
    }
}

```
This search method is used to populate a gridView.

There is an organisms row that has two programs. the rest of the organisms have one program. I have pageSize set to 5. When sorting on the externalInstitution column, the pager returns 4 items because it counts the organism row with 2 programs as two rows.

As you can see by the comments in this code, I've been trying different permutations of groupBy statements with my sorting. I have the problem narrowed down to something in the pager or dataprovider that returns the wrong items per page depending on sort criteria.

When I sort on the programs column, it counts the rows correctly and returns 5 items in the page.

In Yii1 this problem was solved by setting Criteria->together = true. I have no idea how to solve it in Yii2.

The groupBy statements must be included or postgres throws an error that the 'column x must be included in groupBy or an aggregate function.'

A subquery might be one possible workaround but I'd prefer to fix the pager, perhaps with a more appropriate instance of the pagination object, because I'm not sure how efficient subqueries will be compared to left joins. Efficiency is paramount because the tables will be large.

[Cross-posted to stackoverflow](http://stackoverflow.com/questions/42881124/yii2-dataprovider-wrong-items-per-page-when-using-groupby-and-sorting-on-column)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | php-5.6.30-1.fc24.x86_64
| Operating system | Linux

**Comment by SilverFire** [comment]
In case there is a framework problem, could you provide the minimum required code to reproduce the problem?

**Comment by GlyphDataServices** [comment]
@SilverFire You can't reproduce it with the code above?  I can't simplify it any more than that.

**Comment by rob006** [comment]
See https://github.com/yiisoft/yii2/issues/13782#issuecomment-286803255

**Comment by GlyphDataServices** [comment]
I have reduced this to a minimal example using the canonical posts hasMany authors.  Required files are in the attached zip.  I haven't tried to reproduce this with MySQL, only Postgres. 

If you load the example, you'll see the M2M relation breaks the page count, but only after sorting.  I tried cloning $query and giving that to the paginator for the count query, but that didn't fix the problem. I was able to solve this in Yii1 but not sure what to do here. 

[m2m-count-example.zip](https://github.com/yiisoft/yii2/files/854426/m2m-count-example.zip)

Thanks, please see attached.

**Comment by rob006** [comment]
@GlyphDataServices You have multiple authors assigned to one post. Your query returns one post multiple times (for each combination author-post), but query will remove duplicated records. You should use `indexBy` if you want leave duplicated posts in grid view or avoid grouping by `author_id` if you want display one post only once.

**Comment by samdark** [comment]
Yeah. What @rob006 suggested is correct.

**Comment by GlyphDataServices** [comment]
The problem still occurs whether using groupBy or not.  Having multiple authors for one post is what I want- a basic many to many relation. Substitute Books for Posts if that makes more sense.  Book has many authors, Author has many books. 

Using indexBy has no effect, and gives error "illegal offset type" when I try to use an alias like $query->indexBy('t.id') instead of just $query->indexBy('id')

In some circumstances postgres requires group by.  But regardless, **removing the groupBy statements does not solve this problem.**

using the attribute postsAuthors.author_id instead of authors.name gives thecorrect count initially
	$query->addGroupBy('postsAuthors.author_id'); 
instead of 
		$query->addGroupBy('authors.name');
But when sorting on any of the columns, the bug reappears.  

To further complicate things, In Postgres, when using two relations in a query, you MUST have group by for both columns.  

Please try it out on Postgres.  I'm re-attaching the example with a languages relation.

[postgres-count-bug-2.zip.zip](https://github.com/yiisoft/yii2/files/856483/postgres-count-bug-2.zip.zip)

**Comment by rob006** [comment]
> Using indexBy has no effect, and gives error "illegal offset type" when I try to use an alias like $query->indexBy('t.id') instead of just $query->indexBy('id')

Try use 
```php
    $query->indexBy(function ($row) {
        return $row['author_id'] . '-' . $row['post_id'];
    })
```

**Comment by GlyphDataServices** [comment]
That causes an error:  Getting unknown property: app\models\Posts::author_id

$row in the indexBy callback doesn't contain any relations, just Post columns (regardless of groupBy)

```
$row: 

app\models\Posts#1
(
    [author_ids] => null
    [postsAuthorsSearch] => null
    [authorsSearch] => null
    [languageSearch] => null
    [yii\db\BaseActiveRecord:_attributes] => [
        'id' => 1
        'name' => 'Post A'
        'language_id' => 1
    ]
    [yii\db\BaseActiveRecord:_oldAttributes] => [
        'id' => 1
        'name' => 'Post A'
        'language_id' => 1
    ]
    [yii\db\BaseActiveRecord:_related] => []
    [yii\base\Model:_errors] => null
    [yii\base\Model:_validators] => null
    [yii\base\Model:_scenario] => 'default'
    [yii\base\Component:_events] => []
    [yii\base\Component:_behaviors] => []
)
```

**Comment by GlyphDataServices** [comment]
Even more interesting... remove the authors relation, and make postsAuthors into a hasOne relation.  The problem persists.

**Comment by rob006** [comment]
> That causes an error: Getting unknown property: app\models\Posts::author_id

Then add `author_id` and `post_id` properties to Post model.

**Comment by GlyphDataServices** [comment]
@rob006  Error gone, but it causes the dataprovider to return only one row at a time.

**Comment by rob006** [comment]
Make sure that you have this columns in `select` part of query: http://www.yiiframework.com/doc-2.0/yii-db-query.html#addSelect()-detail

**Comment by GlyphDataServices** [comment]
The way I solved this was to use a postgres aggregate function for sorting the gridView instead of groupBy.  Sorting on an imploded array of m2m results doens't make sense anyway, unless you specify ordering of the join result.

It's still possible to filter the gridView on the m2m relation with multi-select filter, but when sorting on the aggregate m2m_column instead of m2mRelation.column the pager will get the correct page/total counts.  

Hope this helps some other postgres users

```php
$query->select(['t.*']);
$query->addSelect(["string_agg(m2mRel.column, ', ') as m2m_column"]);

```

Also add 
```php
public $m2m_column;
```
To declare it in your model, and add it to the safe rule in your search model.
