### ISSUE TITLE
ActiveForm does not submit form

### ISSUE THREAD

**Issue by maxxi165** [yiisoft/yii2#13818]
### What steps will reproduce the problem?
Create active form
```
<? $form = ActiveForm::begin() ?>
<button type="submit" name="submit" value="submit">Submit</button>
<? $form->end() ?>
```
Form does not submits after submit button click. It DOES submit after second click on button.

### What is the expected result?
Form submission after first click.

### What do you get instead?
Form submission after second click.

### Additional info
Баг появился после обновления с 2.0.10 на 2.0.11.2
Если кнопку заменить на `<button type="submit">Submit</button>`, то все срабатывает.
На самом деле, name нужен для использования нескольких сабмит-кнопок на форме.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.4
| Operating system | win,linux

**Comment by dynasource** [comment]
duplicates https://github.com/yiisoft/yii2/issues/13589
