### ISSUE TITLE
How can i use the Mysql's `ORDER BY FIELD()` with ActiveRecord.

### ISSUE THREAD

**Issue by piaoyii** [yiisoft/yii2#13811]
Hi, the question is the title~

**Comment by Alex-Code** [comment]
You can use an [expression](http://www.yiiframework.com/doc-2.0/yii-db-expression.html) and please keep questions to the forums, Git is for issue tracking

```php
->orderBy(new Expression('FIELD(column, 1, 2, 3, 4'));
```

**Comment by piaoyii** [comment]
But it's not work in version 2.0.6,so i upgrade the version.
now, it can work in version 2.0.11.
