### ISSUE TITLE
HasMany ViaTable with orWhere produces andWhere query

### ISSUE THREAD

**Issue by slnw** [yiisoft/yii2#13819]
### What steps will reproduce the problem?
```
$query = $this->hasMany(Table::className(), ['id' => 'table_id'])
			->viaTable(Table2::className(), ['table2_id' => 'id']);

$query->orWhere('table.col = 1');

$query->createCommand()->rawSql;
// SELECT * FROM `table` WHERE (table.col = 1) AND (`id` IN ('26', '27', '28'))
```

### What is the expected result?
```SELECT * FROM `table` WHERE (table.col = 1) OR (`id` IN ('26', '27', '28'))```

### What do you get instead?
```SELECT * FROM `table` WHERE (table.col = 1) AND (`id` IN ('26', '27', '28'))```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.24
| Operating system | Mac Sierra

**Comment by rob006** [comment]
This is expected. This `AND` condition comes from relation and it is required if you need related records.

**Comment by samdark** [comment]
@rob006 is correct. What's in relation definition should be executed no matter what.
