### ISSUE TITLE
Codeception/Fixture Documentation is outdated

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#13810]
There are several issues regarding tests if you stick to the docs.

The way:
1. installed a new advanced template 2.0.11 and initialized a new development environment
2. got to http://codeception.com/for/yii via Yii2 Documentation
 2.1. first issue: `composer exec codecept run` is out of date should be `vendor/bin/codecept run`
 2.2. second issue: error on running tests. because codeception.yml refers to `test-local.php` these files doesnt exist by default. And no hint what to be in this file. He fixed codeception.yml to test.php after reading "Manual Configuration" & and updated test.php to load the correct configs.
 2.3. closed http://codeception.com/for/yii because it seems to be outdated and it is not clear if anything mention there is working, so trial & error / stackoverflow is the only way to get the best practices
3. Setup Fixtures: http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html
 3.1. Try to setup a fixture that depends on another fixture like described in docs above.
 Problem here:
 Since the refactored testing structure is using `datafile` for fixtures in the example, there seems no logical way to introduce some depending fixtures. *If you stick to the Docs and try to use the examples in advanced template*

From Yii:
(LoginFormTest.php) || Advanced Template
```php
   public function _before()
    {
        $this->tester->haveFixtures([
            'user' => [
                UserFixture::className(),
                'dataFile' => codecept_data_dir() . 'user.php'
            ],
        ]);
   }
```

Edited UserFixture:
```php
<?php
namespace common\fixtures;

use yii\test\ActiveFixture;

class User extends ActiveFixture
{
    public $modelClass = 'common\models\User';
    public $depends = [
        'common\fixtures\UserDependsOnThis',
    ];
}
```

So, the above cannot work because dataFile cannot be specified in `$depends`, the dependency will fail silently and the tests may throw foreign_key exceptions.

The Guide should be updated somehow. I dont know what is best practice for espacially 3. otherwise we would update it.

**Comment by samdark** [comment]
https://github.com/Codeception/codeception.github.com/pull/130

**Comment by samdark** [comment]
> 2.2. second issue: error on running tests. because codeception.yml refers to test-local.php these files doesnt exist by default. And no hint what to be in this file. He fixed codeception.yml to test.php after reading "Manual Configuration" & and updated test.php to load the correct configs.

These files are there right after initializing advanced project environment by running `./init` which is well described in both `README` and docs.

**Comment by samdark** [comment]
Need clarification about point 3. Haven't got it at all...

**Comment by ItsReddi** [comment]
> These files are there right after initializing advanced project environment by running ./init which is well described in both README and docs.

I'll recheck that but i think that the files are not generated.

Clarification for 3:

**Situation:**
In most applications we need to setup table dependecies via relations espacially if you are using a non NoSql database. Relation support are one of the things you will look up, if you try to find a nice framework for your task.

**The point of view from a new Yii2 developer:**
Oh that framework looks quite well and the core team also offers an advanced template to try out some things. I am advanced dont need that basic.

The new developer will assume that the advanced application, since it is developed by core team, is a fast startup and a sort of best practice to archieve fast results.

But: With the above described situation it is not.

Back to the developer, he started reading the guide and set up some models with relations to test the usage. And if he come into tests the problem described comes up.

Advanced Template | The developer assume it is *best practice*.
```php
 public function _before()
    {
        $this->tester->haveFixtures([
            'user' => [
                UserFixture::className(),
                'dataFile' => codecept_data_dir() . 'user.php'
            ],
        ]);
   }
```
This function is telling you, ok it seems to be best practice to use the dataFile property in your test classes, weird so i have to write it over and over again?

The attribute dataFile in this place, will give you the restriction that you are not able to work with dependencies. Like described in the docs.
http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html

It tells you that you may can define dataFile. Thats not correct. You are forced to define if you are using the advanced template.

You will end up extending the base Fixture class and overwriting the init to be able to
```php
    public function init()
    {
        $this->dataFile = codecept_data_dir() . 'fixturefile.php';
        parent::init();
    }
```

**Comment by samdark** [comment]
Ah, right. Got it about `#3`. Pull request changing it to a practice allowing dependencies is very welcome.
