### ISSUE TITLE
problem get data post message of restfull api

### ISSUE THREAD

**Issue by loongdefect** [yiisoft/yii2#13826]
Hi all,
I have using framework for my backend and create a module api restful.
my frontend use angular-cli, when i make a request login as below:
`var data = "username=username2&password=123456";`

`var xhr = new XMLHttpRequest();`
`xhr.withCredentials = true;`

`xhr.addEventListener("readystatechange", function () {`
`  if (this.readyState === 4) {`
`    console.log(this.responseText);`
`  }`
`});`

`xhr.open("POST", "http://esl.com/backend/web/api/user/login");`
`xhr.setRequestHeader("authorization", "Basic dXNlcm5hbWUyOjEyMzQ1Ng==");`
`xhr.setRequestHeader("content-type", "application/x-www-form-urlencoded");`
`xhr.setRequestHeader("cache-control", "no-cache");`

`xhr.send(data);`

On Api I use code as below get post data:
`$post = \Yii::$app->request->post();`

But all request had $post = array empty
use postman is ok

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 7.0
| Operating system | window

**Comment by samdark** [comment]
What's in `$_POST`?

**Comment by loongdefect** [comment]
Hi samdark,
$_POST= {array}[0]

**Comment by samdark** [comment]
Means no data was received by PHP.

**Comment by samdark** [comment]
How about `Yii::$app->request->getRawBody()`?

**Comment by loongdefect** [comment]
Hi samdark,
Thank for answer.
I resolve this issue, it is problem cross domain of apache.
