### ISSUE TITLE
Generate safe migrations by default?

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#13827]
Extracted from [here](https://github.com/yiisoft/yii2/pull/13823#issuecomment-288435844).

Currently `migrate/create` command generates unsafe migrations by default.

While some DBMSs don't support transactions if your DBMS does support it (which is(?) the majority of cases) you want to use safe migrations by default. 

Current template adds friction to the development process when you constantly have to uncomment safe methods and remove unsafe ones.

We can leave everything as it is, turn it the other way around or add command parameter for that. Any ideas?

I checked the history and unsafe migrations [were always used by default](https://github.com/yiisoft/yii2/commit/6dc45276b56f6a0d06eb17e9a0af93b88da42d5e).

**Comment by samdark** [comment]
DBMS which doesn't support transactions for schema changes is MySQL. If there are `safeUp()` and `safeDown()` implemented, migration is executing just fine so I'd change template to use safe methods by default.

**Comment by Renkas** [comment]
Is there any real reason to have separate safe and "non-safe" migrations?

**Comment by samdark** [comment]
Not really :)

**Comment by ItsReddi** [comment]
in my opinion it truly make sense to have unsafe migration methods.
Not anyone is aware of the fact that ddl statements are not transactionable, so the non-safe methods are an indicator for other developers in your team to ask you. "why we do not use the safe methods?"

**Comment by samdark** [comment]
Well, I guess that was the case why these were added. It could be solved with a comment about MySQL in docs and phpdoc.

**Comment by Kolyunya** [comment]
In fact safe ones were added after non-safe.

**Comment by Sarke** [comment]
I'd go as far as printing a warning every time there are schema migration changes on a mysql DB.  Without knowing, the developer will assume that the "safeUp" is a transaction, but if it fails their db will be stuck in an inconsistent uncertain state.
