### ISSUE TITLE
Get Primary Key Uniqueidentifier Yii 2.0.11

### ISSUE THREAD

**Issue by anibalcatheringer** [yiisoft/yii2#13828]
### What steps will reproduce the problem?

Hello,
I was using the Yii2 2.0.7 and now I've upgraded to the latest version.
My primary key is setup with uniqueidentifier type and the default value is: newsequentialid()

So after insert an entry, I do the code: $modelX->getPrimaryKey(); It returns null

Can someone help me? It is working on 2.0.7 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
What is `newsequentialid()`?

**Comment by samdark** [comment]
What is the database server you are using?

**Comment by anibalcezarr** [comment]
MSSQL, newsequentialid() u put this on default value of the primary key to generate a unique identifier

**Comment by samdark** [comment]
@sergeymakinen could you take a look at the issue?

**Comment by sergeymakinen** [comment]
@samdark sure, I will.

**Comment by sergeymakinen** [comment]
Well, I couldn’t reproduce this issue. `getPrimaryKey()` works consistent across all versions I have tested on (2.0.7-2.0.11.2). Depending on an AR configuration it returns `null` or `(newsequentialid())`.
I need that table schema and a code sample that behaves incorrectly.

**Comment by anibalcezarr** [comment]
Schema: http://image.prntscr.com/image/c4ad3fc9da6c4a4687605b272dc01465.png
Code: 
`public function actionAdd(){
        
        $modelContact = new Contact;
        
        if ($modelContact->load(Yii::$app->request->post())) {
            $modelContact->save();
            return $this->redirect(['contact/index']);
        }
        return $this->render('add',[ 'modelContact' =>$modelContact ]);
    }`

Debuggin:

http://image.prntscr.com/image/0d31575079814bba84ea89ff4511e1d1.png

**Comment by sergeymakinen** [comment]
Thank you! It behaves same to me in both 2.0.7 and 2.0.11. I mean AR can't return its new GUID. It's not implemented yet in the MSSQL driver.
I could probably fix this.

**Comment by anibalcezarr** [comment]
Ahh weird, because on 2.0.7 works fine hahaha
But yeah, if you could fix it, would be perfect man! Thanks

**Comment by SilverFire** [comment]
@sergeymakinen is the problem related to Yii2 MSSQL driver implementation?

**Comment by sergeymakinen** [comment]
@SilverFire yes… We need to use [`OUTPUT`](https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql) that works like `RETURNING` to solve this issue. I could fix this in 2.0.13 as soon as I finish with constraints. Otherwise you’re welcome. :)

**Comment by craiglondon** [comment]
Has this issue been resolved or is still outstanding?

**Comment by samdark** [comment]
Was not resolved.

**Comment by craiglondon** [comment]
Thanks for the update.
