### ISSUE TITLE
Incorrect usage of \yii\web\ForbiddenHttpException

### ISSUE THREAD

**Issue by smsteel** [yiisoft/yii2#13822]
Method `\yii\web\User::loginRequired` throws this exception, but it must be used for situations, when

> a user has been authenticated but is not allowed to perform the requested action

Which is not the case, `\yii\web\UnauthorizedHttpException` should be used istead.

**Comment by samdark** [comment]
From `UnauthorizedHttpException` description:

> Use this exception to indicate that a client needs to authenticate or login
   to perform the requested action. If the client is already authenticated and
   is simply not allowed to perform the action, consider using a 403
   [[ForbiddenHttpException]] or 404 [[NotFoundHttpException]] instead.

**Comment by samdark** [comment]
So yes, seems to be valid.

**Comment by bizley** [comment]
Dude, your "now" is 6 years old...
