### ISSUE TITLE
Small documentation fix in Url::remember() / Url::previous()

### ISSUE THREAD

**Issue by MysteryDragon** [yiisoft/yii2#13821]
There is such explanation for `$name` argument in `BaseUrl::remember()` / `BaseUrl::previous()` phpdoc:
> The name associated with the URL to be remembered. This can be used later by previous(). If not set, it will use yii\web\User::$returnUrlParam.

But it's not true about `yii\web\User::$returnUrlParam`. Actually, it will use `yii\web\User::getReturnUrl()` (https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseUrl.php#L319), which behavior differs from described behavior of `BaseUrl` methods.

We expecting null, if there are no information in `$returnUrlParam`, but actually due to `yii\web\User::getReturnUrl()` it will return `Yii::$app->homeUrl`.

I think that the best way is change this behavior of `BaseUrl` someday, but because of BC break it seems that better way is simply fix documentation.

**Comment by samdark** [comment]
I don't see any contradicting statements in docs. Could you send a pull request with proposed changes?

**Comment by MysteryDragon** [comment]
@samdark all right, I created pull request, but I had tried to avoid it 'cause of my bad English skills.

**Comment by MysteryDragon** [comment]
If it will be more clarifying, I also can create pull request with changes, that fits current documentation declaration, or create demonstrative tests (there are no any tests for `Url::previous()` as I see).

**Comment by samdark** [comment]
The thing is that in the end `$returnUrlParam` is used a result of calling a getter so I don't see a big issue there.

**Comment by MysteryDragon** [comment]
@samdark yes, but if there are no information in `$returnUrlParam`, we're expecting `null`, right? "It just using some predefined parameter name", documentation says, isn't it?
But we will receive `Yii::$app->homeUrl`, as we can see here:
https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L371
It's not `null` at all. It cannot be `null`.

...Am I still unconvincing? :)

**Comment by samdark** [comment]
Right. Would you like to send a pull request fixing it?

**Comment by MysteryDragon** [comment]
@samdark if we're talking about fixing documentation to describe such (current) behavior - I'm already send one, #13836 . There are terrible English (maybe), that's why explanation is not perfect at all, and I'm ready for fixing it.
If you mean `BaseUrl::remember()` / `BaseUrl::previous()` code fix to improve it's behavior and make it matching documentation - yes, of course, I can do this. (I vote for that.)
