### ISSUE TITLE
Paragraphs in validation are treated differently in JS and PHP validation

### ISSUE THREAD

**Issue by DavidSili** [yiisoft/yii2#13847]
### What steps will reproduce the problem?
- In the "function rules()" in a model pass the 'max' rule for 'string' (that is to be used for a text area)
- When the page loads, enter a text in the text area containing at least one new line
- Press submit

### What is the expected result?
- Text has passed both JS and PHP validation, page refreshes, it is saved and returns notification that it is saved

### What do you get instead?
- Text passes JS validation, returns notification that it is saved, page refreshes, the text IS NOT saved, and returns notification that it IS saved

### Additional info
- Every new line in PHP is treated as two characters compared to JS where it is treated as one

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.15
| Operating system | Ubuntu 16.04.4

**Comment by cebe** [comment]
please provide the rules() that apply in this case.

**Comment by DavidSili** [comment]
I am sorry, but I will not be able to provide more info - I have switched jobs (and thus left the project in Yii that I was working on). I only remember now that it was a 'max' rule for strings.
I am sorry that I can no longer be of help in regard to this bug.

**Comment by samdark** [comment]
Closing since it's not possible to fix it w/o info.
