### ISSUE TITLE
count() on Query with orderBy and limit leads to wrong results

### ISSUE THREAD

**Issue by doerler** [yiisoft/yii2#13846]
The change to `Query:queryScalar` #11122 (and the refactoring #13144) changes the behaviour (which temporary unsets `limit `and `offset`) of  `Query::queryScalar` when `orderBy `is not empty. 

If `limit` is set to a value lower then results count and `orderBy` is not empty the `Query::count()` returns limit instead of the expected count.

Shouldn't  `limit `and `offset` be unset in both blocks, like this?:

```php
protected function queryScalar($selectExpression, $db)
{
    if ($this->emulateExecution) {
        return null;
    }

    $limit = $this->limit;
    $offset = $this->offset;
    $this->limit = null;
    $this->offset = null;

    $result = null;
    if (
        !$this->distinct
        && empty($this->groupBy)
        && empty($this->having)
        && empty($this->union)
        && empty($this->orderBy)
    ) {
        $select = $this->select;

        $this->select = [$selectExpression];

        $command = $this->createCommand($db);

        $this->select = $select;

        $result = $command->queryScalar();
    } else {
        $result = (new Query)->select([$selectExpression])
            ->from(['c' => $this])
            ->createCommand($db)
            ->queryScalar();
    }
    $this->limit = $limit;
    $this->offset = $offset;
    return $result;
}
```

Background:
MariaDB for example had no problems with `order by' and aggregate functions like count().
So we use the same query for pagination and count in our REST interface.
A workaround on application site is to empty orderBy or limit before executing the count() query,
but this worked until 2.0.11 - so this is a breaking change IMHO.

 
Example of "wrong" raw sql generated by  `Query::count()` :

```
SELECT COUNT(*) FROM (SELECT * FROM `product` WHERE (`name` LIKE :qp0) AND (`class_id`=:qp1) ORDER BY `parent_id`, `sort` LIMIT 100) `c`
```

**Comment by samdark** [comment]
Would you please post a simple model code and how you do a query with it?

**Comment by doerler** [comment]
Thanks for your fast response!

Assuming with have a model Product and a  yii\web\Controller based controller with following action:
 ````
    public function actionProducts()
    {
        $products = Product::find();

        $limit = Yii::$app->request->get('limit', 100);
        $start = Yii::$app->request->get('start', 0);
        $sort  = Yii::$app->request->get('sort', null);

        if ($limit > 0) {
            $products->limit(intval($limit));
        }
        if ($start > 0) {
            $products->offset(intval($start));
        }
        if ($sort != null) {
            $sort = Json::decode($sort);
            foreach ($sort as $s) {
                $products->addOrderBy($s['property'].' '.$s['direction']);
            }
        }
        /* ... some filtering code ... */

        $response = [
            'products' => $products->asArray()->all(),
            'total' => $products->count()
        ];
        Yii::$app->response->format = 'json';
        return $response;
    }
````

In our db are 1000 products for example.

Calling the action with `https://.../products?limit=10&sort[{"property":"name","direction":"DESC"}]`
returns prior Yii: 2.0.11:
`{"products":[{ .... 10 products ....}],"total":"1000"}`
and now:
`{"products":[{ .... 10 products ....}],"total":"10"}`

We are aware that we could unset limit, offset, orderBy like it is done by Yii in ActiveDataProvider::prerpareTotalCount() for example, but actually the update to the current Yii version breaks our code.

**Comment by Alex-Code** [comment]
I can't check with tests until I'm home but I wonder if removing the `empty($this->groupBy)` conditional and clearing the `orderBy` before the `createCommand` would work.

```php
protected function queryScalar($selectExpression, $db)
    {
        if ($this->emulateExecution) {
            return null;
        }
        if (
            !$this->distinct
            && empty($this->groupBy)
            && empty($this->having)
            && empty($this->union)
        ) {
            $select = $this->select;
            $limit = $this->limit;
            $offset = $this->offset;
//
            $order = $this->orderBy;
//
            $this->select = [$selectExpression];
            $this->limit = null;
            $this->offset = null;
//
            $this->orderBy = null;
//
            $command = $this->createCommand($db);
            $this->select = $select;
            $this->limit = $limit;
            $this->offset = $offset;
//
            $this->orderBy = $order;
//
            return $command->queryScalar();
        } else {
            return (new Query)->select([$selectExpression])
                ->from(['c' => $this])
                ->createCommand($db)
                ->queryScalar();
        }
    }
```

**Comment by doerler** [comment]
Sure, removing the empty($this->orderBy) (not groupBy) condition and resetting orderBy like you've done in your snippet would work.

**Comment by SamMousa** [comment]
I don't agree this is a bug though (it is definitely an undocumented BC breaking change).

Count should return the exact same number as the number of results.
So this should hold:
````
foreach($everyInstanceOfQuery as $q) {
    count($q->all()) === $q->count();
}
````

Side note, I don't see the reason for 2 implementations in `yii\db\Query`. I expect the database to always optimize, wrapping stuff in an extra query shouldn't make a difference:
````
// "Unoptimized"
SELECT count(*) FROM (select * from t)
// "Optimized"
SELECT count(*) FROM from t;
````

MySQL explain: `Select tables optimized away`

**Comment by samdark** [comment]
Not wrapping it may give different number in certain cases...

**Comment by SamMousa** [comment]
Are you referring to `count()` ignoring `null` values?

**Comment by samdark** [comment]
Yes.

**Comment by SilverFire** [comment]
Oh, good example of mighty BC breaking.

I agree with @SamMousa that this change is correct and both `limit` and `offset` should be applied even for count.

I think it will be extremely hard to debug working projects that could be affected with this change. 
Considering these changes were suggested to "optimize", not not to change something, we can say that BC breaking was introduced accidentally. Profit from the optimization does not worth potential problems, so I think we should revert it.

**Comment by doerler** [comment]
As long as you're using database `count(*)` aggregate function for `Query::count()` it depends on the database - so InnoDB for example doesn't even care about the limit in the SQL statement. 
In this case results of `$q->limit(1)->all()` and `$q->limit(1)->count() ` are not equal anyway. Other database engines may handle this in other ways.

And the nasty thing here is wrapping the query gives you another result:

`SELECT count(*) FROM product;` => 1000
`SELECT count(*) FROM product LIMIT 1;` => 1000
`SELECT count(*) (SELECT * FROM product LIMIT 1) c;` => 1

**Comment by SamMousa** [comment]
Oh, that is nasty. From your example though, it seems that wrapping it will always work??

**Comment by doerler** [comment]
For InnoDB wrapping will always count the rows of the inner SQL statement, but i think this not the point here. IMHO it would have been better if `Query::count()` were named `Query::totalCount()` and `Query::count()` respects limit. 

But we should keep in mind that the `Query::count()` problem is a side effect of changing `Query::queryScalar()`.

**Comment by SamMousa** [comment]
@doerler It was always my understanding that count just gives me the number of records I can expect when doing `->all()`. 
Total count is a very weird and subjective concept. You're proposing to remove some criteria for counting (like `limit`), but not others (like `where`).

For queries I think wrapping is the most intuitive solution, basically an efficient alternative to this dumb implementation:
````
return count($this->all());
```

It will be reliable and predictable in all cases on all databases.

**Comment by xyluet** [comment]
Just want to ask
I do a simple query with queryScalar, but result is undefined. is it bug ? 
I'm using Yii 2.0.11.2

**Comment by IvoPereira** [comment]
@samdark as you closed the issue, what would be the most reasonable way following the best practices handling this case?

Doing what @SamMousa suggested?

That would work on the majority of the cases, however, when processing a large batch results that may seem noticeable.

**Comment by SamMousa** [comment]
What did I suggest?
