### ISSUE TITLE
Uses UniqueValidator and alias for table

### ISSUE THREAD

**Issue by vladis84** [yiisoft/yii2#13842]
### What steps will reproduce the problem?
Uses UniqueValidator and alias for table.

I think the resolution of this Issue has caused a problem with query aliases. If someone overrides the find() method of the model and uses it to add and alias to the model table, the validator will execute a query that will cause an error.

Maybe the prefix used on the validator query should be extracted from the Query object and not from the tableName() method.

### What is the expected result?
Add in column alias for table.

### What do you get instead?
 ambiguous error sql while using unique validator

### Additional info
parent issues #13704 
| Q                | A
| ---------------- | ---
| Yii version      |  2.0.13
| PHP version      | 7.0.17
| Operating system |

**Comment by vladis84** [comment]
There is a method getTableNameAndAlias is **private**.
```php
yii\db\ActiveQuery::getTableNameAndAlias
```
Have any other suggestions for solving the error?

**Comment by jlorente** [comment]
I think yii\db\ActiveQuery::getTableNameAndAlias() method could become a public method since it does not modify anything in the ActiveQuery object and is only used to retrieve information about the query. Then we could use the method to patch the UniqueValidator.

**Comment by vladis84** [comment]
I'm not sure about that.
All public methods ActiveQuery modify the query and use fluent interface.
Consistency code bases.

**Comment by vladis84** [comment]
I propose to render the method in helper.
Alexander you do not mind?
@samdark

**Comment by samdark** [comment]
Which helper?

**Comment by vladis84** [comment]
I will transfer this code to the helper.
https://github.com/vladis84/yii2/blob/40cf0dd7da4e23582a9a844af8a30bc43d09f8d7/framework/db/ActiveQuery.php#L559

I am make pull request.
