### ISSUE TITLE
Undefinded index when JOIN and indexBy

### ISSUE THREAD

**Issue by gaginsgagins** [yiisoft/yii2#13859]
When i try use this code

```php
Printer::find()->select(["concat(printer.name,' в ', o.name) name"])
            ->joinWith('cartPrinters c')->joinWith('auditories o')
            ->where(['c.id_cart'=>$this->id])
            ->indexBy('printer.id')->column();
```

rised exception

> PHP Notice – yii\base\ErrorException
> 
> Undefined index: printer.id

but in SQL all work normaly 

```sql
SELECT concat(printer.name,' в ', o.name) name, printer.id FROM `printer` LEFT JOIN `cart_printer` `c` ON `printer`.`id` = `c`.`id_printer` LEFT JOIN `printer_auditory` ON `printer`.`id` = `printer_auditory`.`id_printer` LEFT JOIN `auditory` `o` ON `printer_auditory`.`id_auditory` = `o`.`id` WHERE `c`.`id_cart`=45
```

When i try indexBy('**id'**)

```php
Printer::find()->select(["concat(printer.name,' in', o.name) name"])
            ->joinWith('cartPrinters c')->joinWith('auditories o')
            ->where(['c.id_cart'=>$this->id])
            ->indexBy('id')->column();
```

SQL rised exception

> Column 'id' in field list is ambiguous

**Comment by gaginsgagins** [comment]
I solve this problem by use indexBy with callable
`Printer::find()->select(["concat(printer.name,' в ', o.name) name, printer.id"])
            ->joinWith('cartPrinters c')->joinWith('auditories o')
            ->where(['c.id_cart'=>$this->id])
            ->indexBy(function ($row) {
                return $row['id'];
            })->column();`
But whay **indexBy('printer.id')->column();** not working?

**Comment by samdark** [comment]
According to docs it should work...

**Comment by gaginsgagins** [comment]
Yes, but when i try it, i have
![s2](https://cloud.githubusercontent.com/assets/25243076/24439581/c7015600-1457-11e7-848b-d72a78457314.PNG)

**Comment by SamMousa** [comment]
I think my PR will fix this as well: https://github.com/yiisoft/yii2/pull/13891

**Comment by cebe** [comment]
fixed, thanks for reporting!
