### ISSUE TITLE
Configure in outher runtime folder?

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#13850]
### What steps will reproduce the problem?
In the forum no founds abourt it, samples dont work.

### What is the expected result?
Move runtime another folder

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      7|
| Operating system UBUNTU SERVER 14|

**Comment by MysteryDragon** [comment]
http://www.yiiframework.com/doc-2.0/yii-base-application.html#$runtimePath-detail
Pay attention that this methods require full path, but allow you to use aliases.

**Comment by MysteryDragon** [comment]
And more obvious answer:
`config/main.php`:
```
return [
    'runtimePath' => '@app/runtime-test',
];
```
