### ISSUE TITLE
Option to hide individual database operations in migration

### ISSUE THREAD

**Issue by francislavoie** [yiisoft/yii2#13853]
I have some large migrations which have many individual `insert` statements to load the database with a good initial state. These SQL statements contain some large base64 encoded data blobs. When I run `yii migrate --interactive=0`, every `insert` is printed to `stdout` in full.

I would like an option to make all the individual SQL operations (those written in white between 
each migration file) to be hidden, so I'm only left with messages about each migration file being run. Could this be added to the framework?

https://github.com/yiisoft/yii2/issues/13040 this is a similar issue, but I more specifically care about only reducing the amount of output rather than getting rid of all of it (I could do `>/dev/null` for that if I wanted to).

Thanks

**Comment by cebe** [comment]
If you do not want your inserts to be printed you can do so by calling 

```php
$this->db->createCommand()->insert($table, $columns)->execute();
```

instead of

```php
$this->insert($table, $columns);
```

**Comment by rob006** [comment]
See https://github.com/yiisoft/yii2/pull/13787

**Comment by francislavoie** [comment]
@cebe that's not at all a solution. That would require me to change every migration to use that kind of execution scheme. What I want is to conditionally show or hide those logs, with some commandline option. For example, Laravel only shows the name of the migration file being run, not every operation being done. An option to get that kind of output would be preferable.

**Comment by cebe** [comment]
> That would require me to change every migration to use that kind of execution scheme.

as far as I understood the issue you were talking about one specific migration that inserts large blobs.

**Comment by cebe** [comment]
Could be implemented by changing `echo` in `yii\db\Migration` to a `output()` method which checks a property `$quiet` that would not print the information when set to true.
This could be conrtolled by a flag in MigrateController.

**Comment by samdark** [comment]
There's `yii\db\Migration::$maxSqlOutputLength` which could possibly solve the issue...

**Comment by cebe** [comment]
its only applied to raw SQL currently. This issue is about removing all output that is generated by Migration.

**Comment by francislavoie** [comment]
@cebe sorry, I wrote the issue a few months ago. I could've been clearer. Poor wording by me.

One another idea is instead of an option, you could quiet the output of debug is not on, leaving SQL logging only when debug is on. I think that would technically be better. (IIRC there is a debug mode for CLI, right? I'm not at my PC right now, can't check). Maybe that's too much of a breaking change for everyone else. If we a implement a `$quiet` property, that is configurable via the application config for the migrations, right? I'll have to dig around in the source later probably. I think I can probably make a PR.

**Comment by francislavoie** [comment]
I was looking through the code to see how I would implement this. This is what I'm thinking:

 - Add a `$quiet` property to `yii\db\Migration`, to be set via `yii\console\controllers\BaseMigrateController` in the `createMigration` function.
- Every function in `yii\db\Migration` has two echos. I'd like to pull those out into private functions to remove some duplication. I'm thinking calling them `echoStart($string)` and `echoDone($time)`
- `echoStart` would just be `echo "    > $string ...";`, but also wrapped with a check if `$this->quiet !== null`.
- `echoDone` would be `echo ' done (time: ' . sprintf('%.3f', microtime(true) - $time) . "s)\n";` similarly wrapped with the check for quiet.

`migrateUp` and such in `BaseMigrateController` already do the work of printing out which class is being run and the time elapsed, so there's still that information visible.

Does this make sense? I can get started on a PR with this today, I just want to make sure I'm not planning on doing something that doesn't make sense.

**Comment by cebe** [comment]
first part sounds good to me, I'd use a different name for the methods, `beginCommand()` and `endCommand()` could be used they do not only echo but also track the time.

Not sure about changing MigrateController output to one line because quite will only affect output printed by migration methods, while one could have own echo output in a migration that does not respect the $quiet property. I'd leave these as they are for now.

**Comment by francislavoie** [comment]
Okay thanks @cebe, I'll start working on it as soon as I can.
