### ISSUE TITLE
Suggestion: Configurable Extra Patterns in main.php?

### ISSUE THREAD

**Issue by ehjcrittenden** [yiisoft/yii2#13864]
### What is the expected result?
I would like to suggest an addition that would complement the resource level configuration options. I would also suggest that we allow configuration in the application URLmanager. My proposal can be seen here. http://www.yiiframework.com/forum/index.php/topic/72222-enhancement-suggestion-configurable-extra-patterns-in-mainphp/

### Additional info

```php
"class"      => "yii\rest\UrlRule",
'controller' => 'v1/posts',
'tokens'     => [
    '{id}' => '<id:\\w+>'
],
'extraPatterns' => [
     // This is what I am proposing
     'GET full-post/{id}' => [  
           'action' => 'fullPost',
           'fields' => [],
           'expand" => ['authors', 'comments'],
           "etc" => ,
      ]
 ]
```

| Q                | A
| ---------------- | ---
| Yii version         | 2.0.?
| PHP version      | 7.0

**Comment by samdark** [comment]
It is possible to achieve it but the way wasn't well documented. Added it to the guide.
