### ISSUE TITLE
ActiveField hiddenInput()->label(false)->hint(false) renders a 15px visual gap

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#13868]
Issue: `$form->field($model,'attribute')->hiddenInput()->label(false)->hint(false)` renders a 15px tall gap in the form (persumably due to the `.form-group` CSS class).

In the past we were told to overcome this by using `Html::activeHiddenField()`, but that solution is even worse because it completely bypasses validation.

hiddenInput() without a label, without a hint, should not be inserting a gap into the form. The whole point of a hidden field is for it to be *hidden*, not transparent.

**Comment by Locustv2** [comment]
@vercotux can you give a snippet of your code? I just tried it and it works as expected. The 15px is from the margin for the `.form-group` but this should not affect your layout unless you have something in between like `<div class="clearfix"></div>`

```php
public function actionForm()
{
    $this->layout = false;
    \yii\bootstrap\BootstrapAsset::register($this->view);
    \yii\web\YiiAsset::register($this->view);

    $this->view->beginPage();
    $this->view->head();
    $this->view->beginBody();

    $model = new \yii\base\DynamicModel([
        'firstname' => null,
        'lastname' => null,
        'password' => null,
        'email' => null,
    ]);

    $form = \yii\widgets\ActiveForm::begin();
    echo $form->field($model, 'firstname');
    echo $form->field($model, 'lastname');
    echo $form->field($model, 'password')->hiddenInput()->label(false)->hint(false);
    echo $form->field($model, 'email');
    yii\widgets\ActiveForm::end();

    $this->view->endBody();
    $this->view->endPage();

    return $this->renderContent('This is a test');
}

```

**Comment by cebe** [comment]
closing as no feedback has been given for a long time.

**Comment by vercotux** [comment]
I figured this only happens when using Kartik's ActiveForm, so it's unlikely a Yii2 issue.
