### ISSUE TITLE
The worst PHP framework. Why these lines done work

### ISSUE THREAD

**Issue by twob-shahid** [yiisoft/yii2#13860]
`\app\models\UserMenu::find()->orderBy(['display_order' => SORT_DESC]);`

or

`\app\models\UserMenu::orderBy(['display_order' => SORT_DESC])->find();`

or

`\app\models\UserMenu::findAll(['active'=>1])->orderBy(['display_order' => SORT_DESC])->find();`

**Comment by hiqsol** [comment]
The worst question on GitHub ever :)

**Comment by devmustafa** [comment]
Yii2 ActiveRecord has a descriptive list of chainable functions. Check it here: http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html

**Comment by fernandezekiel** [comment]
man... RTFM

**Comment by jblac** [comment]
There is only one reason those commands wouldn't work.  There appears to be some sort of IO error between your keyboard and the internet.
