### ISSUE TITLE
Code style may should be more suitable.

### ISSUE THREAD

**Issue by mztest** [yiisoft/yii2#13869]
### What steps will reproduce the problem?
[PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)
Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

[Yii 2 Core Framework Code Style](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md)
Property names MUST start with an initial underscore if they are private.
### Additional info

Is that a little conflicting？
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by MysteryDragon** [comment]
Funny that I noticed same point yesterday and even thought about creating issue. But then I began suspect that it's deliberate decision of yii2 core developers. :)

**Comment by bizley** [comment]
As the linked internal doc states Yii 2 uses PSR-2 **compatible** style, not a strict one.

**Comment by samdark** [comment]
It is intentional and is caused by technical problem with magic properties and getters/setters in an Object.
