### ISSUE TITLE
AMD support for out-of-box JavaScript modules

### ISSUE THREAD

**Issue by alpharder** [yiisoft/yii2#1387]
For now it's impossible to use default ActiveForm and GridView widgets at project which uses AMD/RequireJS for javascript insertion into page.

For example:
yii\grid\GridView::run() now has line 

``` php
$view->registerJs("jQuery('#$id').yiiGridView($options);");
```

The solution from the outside should look like:

``` php
// Somewhere in layout:
$view->amd = true;
...
// At yii\grid\GridView::run()
$view->registerJs("$('#{$id}').yiiGridView({$options});", [
    'jquery'=>'$',
    'jquery.yiiGridView'=>'yiiGridView'
]);
```

The second method argument accepts code dependencies. The generated code for example above would be:

``` js
require(['jquery', 'jquery.yiiGridView'], function($, yiiGridView) {
    $('#my-grid-view').yiiGridView({'foo':'bar'});
});
```

You may sight `$view->amd = true;` line, this signals the View object of having to use AMD-like way of JavaScript insertion into page. When it set to false, View uses default way of JS insertion (jQuery-spaghetti, as for current realisation), also the listed code dependencies would be loaded using registerScriptFile().

**Comment by dynasource** [comment]
out of the scope of Yii2. You can create your own Assets if you want your own custom JS implementation

**Comment by liangjh08** [comment]
Without modular, it's difficult to manage my frontend (js,css) . Yii's AssetBundle is not quit enough. Frontend tech develops fast,  can Yii provide some support?

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/blob/master/book/structure-asset-processing-with-grunt.md. Any tool could be used alike.
