### ISSUE TITLE
Summary model attribute by related tables

### ISSUE THREAD

**Issue by Unlite** [yiisoft/yii2#13878]
Hi, i tried to google this problem but there are no results. Can someone help me?
I have product table, product_arrivals (contains amount of product incoming) and product_sales(product decreasing number). Product alredy have all relations with those tables.
I need a field in Product model that will contain (sum(all product arrivals) - sum(all product sales)). 
So it will be the "Amount of product" at the moment.
I can get it manually in the model like 
```php
//Product model
public $_amount = 0;
    
public function getAmount()
    {
        foreach($this->productsArrivalHasProducts as $arrival_product){ //getting the relation
            $this->_amount += $arrival_product->amount;
        }
        foreach($this->productToSales as $sale_product){ //getting the relation
            $this->_amount -= $sale_product->amount;
        }
        return $this->_amount;
    }

    public function setAmount($amount)
    {
        $this->_amount = $amount;
    }

```
But i think it is not right bcs with such solution i can't filter my GridView widget.
I think it should be counted on query stage. Can someone explain me, is it possible?
And if it is, can you explain how to use it in searchModel too?
Thanks for attention and sorry for my bad english 😄

**Comment by SamMousa** [comment]
You could try: https://github.com/MarketFlow/yii2-virtual-fields

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#selecting-extra-fields
