### ISSUE TITLE
Before save must check special character and convert them, for prevent vuln

### ISSUE THREAD

**Issue by rahmatheruka** [yiisoft/yii2#13870]
### What steps will reproduce the problem?
before save
### What is the expected result?
special character exp: "<script>alert('hello');</script>" must convert with somthing method, for example method htmlspecialchars
### What do you get instead?
special character exp: "<script>alert('hello');</script>" must convert with somthing method, for example method htmlspecialchars

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |> 5.6
| Operating system |

**Comment by Alex-Code** [comment]
It's up to you to strip out anything bad, the framework doesn't know automatically if something should be striped.

That's what rules are for.
```php
public function rules()
{
    return [
    //...
        ['attribute', 'filter', 'filter' => 'strip_tags']
        //or
        ['attribute', 'filter', 'filter' => function($value) { return HtmlPurifier::process($value); }],
    //..
    ];
}
```

**Comment by samdark** [comment]
No. For different contexts different escaping should be performed differently. Framework doesn't know the context you're outputting data in.
