### ISSUE TITLE
Deprecate ApcCache

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#13885]
http://php.net/manual/en/intro.apc.php
>  This extension is considered unmaintained and dead. However, the source code for this extension is still available within PECL GIT here: http://git.php.net/?p=pecl/caching/apc.git.

Can we deprecate this?

Vaguely related: #13226

**Comment by rob006** [comment]
APCu is still supported, there is no point in deprecating this.

**Comment by SamMousa** [comment]
Ah, didn't see it supports both. Still the APC part can be deprecated then, and for 2.1 `useAPCu` could be set to true?

**Comment by samdark** [comment]
Yes. APC part could be safely deprecated. APCu should stay as is.
