### ISSUE TITLE
Add issue label has:pr

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#13884]
It would be great if a new label could be introduced for issues that have a PR.
For people who want to:
- Review PRs.
- Implement fixes.

This would save a lot of time!

**Comment by samdark** [comment]
For reviewing PRs you can use https://github.com/yiisoft/yii2/pulls.

**Comment by SamMousa** [comment]
I know that, but today I spent a lot of time looking at old inactive issues. There is no way for me to get an idea of the total size of outstanding work.
Total open bugs: 616
Total open PRs: 174

The overlap is hard to measure without checking each issue individually.
I'd like the label; if you feel it is a lot of work to add it then I understand.

**Comment by samdark** [comment]
So how are you going to use it? Select all issues without pull requests?

**Comment by SamMousa** [comment]
Yes, or with if I need to get an idea of the overlap.

**Comment by samdark** [comment]
https://twitter.com/sam_dark/status/847485233322524675

**Comment by SamMousa** [comment]
> not at the moment but I'll add it to our Feature Request List!

**Comment by samdark** [comment]
I guess it's better to wait for GitHub to implement it... lots of workload adding it.
