### ISSUE TITLE
Getting unknown property: yii\console\Application::newFileMode

### ISSUE THREAD

**Issue by mitjao** [yiisoft/yii2#13887]
### What steps will reproduce the problem?
Console Application:

```php
$gii = new \yii\gii\generators\model\Generator($params);
$files = $gii->generate();
foreach ($files as $file) {
     $file->save();
}
```

### What is the expected result?
Files are saved.

### What do you get instead?

> Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\Application::newFileMode'

`yii\gii\CodeFile::save()` tries to access `yii\console\Application::newFileMode` (and `yii\console\Application::newDirMode`) which do not exist.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.17
| Operating system  | macOS 10.12.4

**Comment by samdark** [comment]
Because you're not accessing it from within Gii module. What are you trying to achieve?

**Comment by mitjao** [comment]
I'm writing a console command to automatically update my model classes.
