### ISSUE TITLE
need 'position' for css assets

### ISSUE THREAD

**Issue by diss1dent** [yiisoft/yii2#13888]
google pagespeed did'nt like a lot of css in head.. can anyone help?

**Comment by Charius** [comment]
as an option you can compress your assets and after compressing you will have a few css and js files

**Comment by samdark** [comment]
@diss1dent where else do you want to put your CSS? It's not valid elsewhere.

**Comment by samdark** [comment]
HTML doesn't allow putting CSS anywhere except `<head>`. There's `scoped` attribute but it's not really supported: http://caniuse.com/#search=scoped

**Comment by diss1dent** [comment]
my frontend developers make css file almost on 0.5mb  compressed, it is really bad for sitespeed to keep it all load before html tree, i just want to do like so or link rel="stylesheet"
https://www.screencast.com/t/qif0GRU2

**Comment by samdark** [comment]
No, it is a bad idea which is against HTML specification. It should be done via either inlining (applying to elements directly in any place or putting it in the style tag in the head) or with some help from JavaScript: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

**Comment by diss1dent** [comment]
It was so in html 4, i did'nt find it in html 5
and validator does not make any errors about style and link rel="stylesheet" after footer..
inlining is bad idia according to your link...

https://www.screencast.com/t/g98BUruL8q
https://www.w3.org/TR/html5/links.html#link-type-stylesheet
https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=http%3A%2F%2Fgoogle.com

**Comment by samdark** [comment]
Hmm... seems you're right about the spec. Still, Google suggests the opposite: https://developers.google.com/speed/pagespeed/service/MoveCSSToHead i.e. moving CSS to head.

**Comment by b-fett** [comment]
Can we use something like [that](https://github.com/filamentgroup/loadCSS) to solve the problem?

**Comment by b-fett** [comment]
@samdark , what you'll say?

**Comment by samdark** [comment]
I'd not go to that direction. Yii is primarily PHP framework and I'd like to stay it like that and even be more of PHP framework than it is now.
