### ISSUE TITLE
Behaviors don't check their owner.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#13896]
### What steps will reproduce the problem?
Attach an `AttributeBehavior` to `Component`

### What is the expected result?
I expect it to fail since `AttributeBehavior` only supports being attached to a `ActiveRecord`.

### What do you get instead?
It succeeds silently until I manually call `evaluateAttributes`. Then it throws an exception.

### Additional info
In this specific case one could argue that the call above would not naturally occur (since a component that is not a model will not fire an `ActiveRecord::EVENT_BEFORE_UPDATE` event.
Still I think it makes sense for a behavior to do some checking at attach time instead of blindly making assumptions that are hard to validate.

One way to implement this would be to add a function to the base behavior:
````
protected function validateOwner($owner) {
    return true;
}
````

Which would then be called by `attach()` before attaching the behavior.

Not sure if that's the way to go, just an option, open to other suggestions.

When using PHP Traits it is common to ensure preconditions by adding `abstract public function foo()` to the trait.

**Comment by klimov-paul** [comment]
I can see no benefit of checking owner type - it will simply degrade the script performance (especially for ActiveRecord) without much benefit. I do not consider wrong behavior owner attachment is spead enough mistake.

> When using PHP Traits it is common to ensure preconditions by adding abstract public function foo() to the trait.

I do not understand, what do you mean. Can you provide some example for this?

**Comment by samdark** [comment]
In the context of the most common usage of behavior, AR, I agree with @klimov-paul. Won't be changed for the sake of AR performance.
