### ISSUE TITLE
DbTarget log transaction bug

### ISSUE THREAD

**Issue by shirase** [yiisoft/yii2#13890]
### What steps will reproduce the problem?
Use DbTarget as targets for log config
Open transaction
Generate error

### What is the expected result?
Error is logged in db

### What do you get instead?
Error is not logged in db

### Additional info
Logger execute insert query, but active transaction is rollback.

### Solution
Rollback current transaction before insert log row.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6.2
| Operating system |

**Comment by bizley** [comment]
Have you called `Yii::error()` before `rollBack()`? Call it after. It's up to you to do it properly, not the framework.

**Comment by shirase** [comment]
I do not call Yii::error(), it called when error occur.
Example:
I start transaction, then try to get not existent property. I have exception, but i don'd see it in db.
I think errors must be logged any way. And that error is logged if i use file target for logger.

**Comment by shirase** [comment]
As solution i can use additional db connection for logger, but it no obviously.

**Comment by samdark** [comment]
Most likely it is a bug. If an error occurred, logging should happen after rolling back a transaction.
