### ISSUE TITLE
ArrayHelper::multisort doesn't support ArrayIterator?

### ISSUE THREAD

**Issue by undsoft** [yiisoft/yii2#13897]
### What steps will reproduce the problem?
Run this code:
```php
use yii\base\Component;
use yii\console\Controller;
use yii\helpers\ArrayHelper;

class StatusController extends Controller{

    public function actionCount()
    {
        // Prepare data.
        $packAsArray = [
            new Dog(['rank' => 2]),
            new Dog(['rank' => 3]),
            new Dog(['rank' => 4]),
            new Dog(['rank' => 1]),
        ];

        $packAsIterator = new \ArrayIterator($packAsArray);

        // Now sort.
        ArrayHelper::multisort($packAsArray, 'rank'); // Works

        ArrayHelper::multisort($packAsIterator, 'rank'); // Exception: array_multisort(): Argument #7 is expected to be an array or a sort flag'
    }
}

class Dog extends Component {
    public $rank;
}

class Pack extends \ArrayIterator {

}
```

### What is the expected result?
Both arrays sorted.

### What do you get instead?
Exception: array_multisort(): Argument #7 is expected to be an array or a sort flag'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | PHP 7.0.15 (cli)
| Operating system | Mac OS Sierra 10.12 (16A313a)

**Comment by SilverFire** [comment]
PHP function `array_multisort` does not support `ArrayIterator` as an argument, so the problem is out of Yii scope. We will not write custom implementation to support this use case, sorry
