### ISSUE TITLE
An assetBundle problem

### ISSUE THREAD

**Issue by David3310273** [yiisoft/yii2#13899]
### Hi, I have the code like this:
```
class BootBoxAsset extends AssetBundle
{
    public $sourcePath = '@vendor/almasaeed2010/adminlte';

    public $css = [
    ];

    public $js = [
        'https://cdn.bootcss.com/bootbox.js/4.4.0/bootbox.js'
    ];

    public $depends = [
        'plugins\jQuery\jquery-2.2.3.min.js',
        'bootstrap\js\bootstrap.min.js',
    ];

    public $jsOptions = ['position' => \yii\web\View::POS_HEAD];
}
```
As the code shows above, I want to use bootbox.js which requires the related jquery and bootstrap dependency that located in my $sourcePath variable combined with the directories in $depends array,
when I register this asset in my view, there's an error tells me that the `Class plugins\jQuery\jquery-2.2.3.min.js does not exist`, so what should I do to register the dependency not start from `yii` directory?
thanks!

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      |7.0
| Operating system |ubuntu

**Comment by khan-07** [comment]
You need a create a separate asset for those two files. And then give the path to those bundles in $depends. 
```

class NewAsset extends AssetBundle
{
 //if the files in the web directory
  $baseUrl = '@web';

    public $css = [
    ];

    public $js = [
        'plugins\jQuery\jquery-2.2.3.min.js',
'bootstrap\js\bootstrap.min.js',
    ];

    public $depends = [
        
        
    ];

    public $jsOptions = ['position' => \yii\web\View::POS_HEAD];
}
```
Then use it like this.

```
class BootBoxAsset extends AssetBundle
{
    public $sourcePath = '@vendor/almasaeed2010/adminlte';

    public $css = [
    ];

    public $js = [
        'https://cdn.bootcss.com/bootbox.js/4.4.0/bootbox.js'
    ];

    public $depends = [
        'yii/web/NewAsset
    ];

    public $jsOptions = ['position' => \yii\web\View::POS_HEAD];
}

```
