### ISSUE TITLE
Add many migrationPathes support for RBAC module

### ISSUE THREAD

**Issue by Mubat** [yiisoft/yii2#13918]
**m140506_102106_rbac_init** RBAC migration has not any namespace, so I can't use it with my project migrations.

And `migrationPath` option at [yii\console\controllers\BaseMigrateController](https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php) doesn't support arrays.

In this case, I should configure to migrate modules based on [yii\console\controllers\BaseMigrateController](https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php)  to use both of pathes.

Need support arrays of migration pathes in  `migrationPath` option.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.17-2+deb.sury.org~xenial+1
| Operating system | Ubuntu 16.04.2 LTS

**Comment by SilverFire** [comment]
Currently we have the following migrations:

 - [i18n](https://github.com/yiisoft/yii2/blob/4931f3f123a046ae52a92ebd6948ba3b8b862c46/framework/i18n/migrations/m150207_210500_i18n_init.php)
 - [log](https://github.com/yiisoft/yii2/blob/3ea671454c8eff030ad7f24f6b2262f28683b203/framework/log/migrations/m141106_185632_log_init.php)
 - [rbac](https://github.com/yiisoft/yii2/blob/1c496532e5883e6342824dd2e16e82c096c6a237/framework/rbac/migrations/m140506_102106_rbac_init.php)
 - [session](https://github.com/yiisoft/yii2/blob/d437c4bd3755109b786131195d5e4e0e6985768b/framework/web/migrations/m160313_153426_session_init.php)
 - [cache](https://github.com/yiisoft/yii2/blob/510c4922247f9c6d38093200de4b1978826a4c68/framework/caching/migrations/m150909_153426_cache_init.php)

Considering that currently developers COPY migrations to their applications to use them, adding namespace to migration is harmless for working applications.

However, there are some tricky points. Currently when we (core team) want to fix something in one of aforementioned migrations, we can simply patch it and developers will copy it for new installations, so old applications will not be affected automatically in any way.

Applying namespaces to these migrations, we will encourage developers to set `yii\(rbac|log|etc)\migrations` to their migrate controller namespaces, so we should take care not to change existing migrations

**Comment by Mubat** [comment]
Hi @SilverFire 
Let me say how I see using this feature.
A lot of projects in our team are small and have short devtime (~2 weeks). Therefore it would be more comfartable to configure namespaces in config file unlike to manipulate with migration files. And we can correct projects configuration quickly. 
If we would need to correct some old project, we can download exactly that version of migration that we used in development time - it write in _composer.lock_ file.
Also developers will have an opportunity to use method you described, if he wish to use unchangeable core migration.

In described way we use migrations in our projects now:

- in big projects we copy core migrations to our default migration folder;

- in small projects we describe second migration in config file. For example:
```php
'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'common\migrations',
            ],
        ],
        'migrate-rbac' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationPath' => '@yii/rbac/migrations/'
        ],
    ],
```

**Comment by SilverFire** [comment]
Yes, anyway it will say on developer's desisions

**Comment by bscheshirwork** [comment]
From [#13918](#issuecomment-296955521)

trivial case:

1. Current schema (not ideal):
Apply migration in project without namespace `./yii migrate/up`
Apply migration from vendor module without namespace `./yii migrate/up --migrationPath=@yii/rbac/migrations/`

2. Module have update, migration have namespace now. Project not modified.

3. BC: Migration in module must still work with old syntax. (Autoload must use any of both method)

**Comment by Mubat** [comment]
@bscheshirwork, I am like a typical lazy programmer want to type only `yii migrate/up` and all shold work fine :smile:

**Comment by bscheshirwork** [comment]
Yes. 

After update `project` `config`. 

I tell about unchanged `project`
(some other people, who update the `module` but don't know about awesome new features)

**Comment by githubjeka** [comment]
Without namespace this leads to strange errors)
https://github.com/githubjeka/tracker-issues/issues/7#issuecomment-299484654

**Comment by rob006** [comment]
Support for arrays in `migrationPath` was added in #14241

**Comment by samdark** [comment]
Thanks. I guess it solves this issue as well...
