### ISSUE TITLE
Guide runtime sessions

### ISSUE THREAD

**Issue by alejosv** [yiisoft/yii2#13910]
### What steps will reproduce the problem?
Within any view, use:

```php
echo Alert::widget([
   'options' => ['class' => 'alert-info'],
   'body' => Yii::$app->session->getFlash('postDeleted'),
]);
```

Where 'postDeleted' is a `Yii::$app->session->addFlash` in a controller

### What is the expected result?
A html markup in the view of a alert using bootstrap classes.

### What do you get instead?
The following error: Array to string conversion

File:  vendor/yiisoft/yii2-bootstrap/Alert.php
Line: 110
Function: `protected function renderBodyEnd()`

### Additional info
The online documentacion say this widget, in the body option must use a string [http://www.yiiframework.com/doc-2.0/yii-bootstrap-alert.html#$body-detail](http://www.yiiframework.com/doc-2.0/yii-bootstrap-alert.html#$body-detail) but the example in http://www.yiiframework.com/doc-2.0/guide-runtime-sessions-cookies.html#flash-data, allow a array. I managed modified this behavior to widget allow array, but I don't know if this is a functionallity that should have. Whatever, the example in "Guide runtime sessions cookies" not should be with array.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 7.0.17-2
| Operating system | Ubuntu 16.04

**Comment by Locustv2** [comment]
`Alert::$body` takes in a string as parameter: http://www.yiiframework.com/doc-2.0/yii-bootstrap-alert.html#$body-detail

`Session::getFlash()` returns array if `addFlash` was used - http://www.yiiframework.com/doc-2.0/yii-web-session.html#getFlash()-detail

Use `Yii::$app->session->setFlash('postDeleted', 'message')` instead.
