### ISSUE TITLE
Tell us more/detail about yii.js in The Definite Guide to Yii 2.0 / Working with Client Scripts

### ISSUE THREAD

**Issue by Chhoeachim** [yiisoft/yii2#13924]
I want to know more/detail about functionality that hidden in yii.js.
I'm trying to research all over Google and I found this one [https://yii2-cookbook.readthedocs.io/forms-activeform-js/](url). And I already finished it.
But I think, there are more. That's why I'm always curious about yii.js.
Don't mind me. I'm a lazy developer and I've always want to write less and clean code.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/12541
