### ISSUE TITLE
Testing Cloned Yii2

### ISSUE THREAD

**Issue by khan-07** [yiisoft/yii2#13928]
Hi,
I have cloned the github yii2 repository. My question is, If i change anything locally in the yii2/framework how do i go about getting the yii-basic or advanced app from that source for testing purposes. Sorry if this question is stupid but i can't figure it out. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.
| PHP version      |7.0
| Operating system |Ubuntu 16.04

**Comment by cebe** [comment]
If this is for your application development you should not make changes to the app in that environment.
If it is for working on Yii2 for contribution, there is a guide describing the setup at https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#3-prepare-the-testing-environment- 

`php build/build dev/app basic` will install a basic app that is linked to the framework.
