### ISSUE TITLE
Performs a substitution in Expression of two Query

### ISSUE THREAD

**Issue by Inkognitoo** [yiisoft/yii2#13929]
### Poblem
I have two query with Expession that have same placeholder name but different content and I want to union them, but substitution execute in two place by one value

### What steps will reproduce the problem?
```php
$one_type = 'TYPE_ONE';
$two_type = 'TYPE_TWO';

$one = (new Query())
    ->select(['one.name', 'one.desctiption',
    new Expression(
        ':type AS type',
        [':type' => $one_type]
    )])
    ->from('tbl_one')
    ->alias('one');

$two = (new Query())
    ->select(['two.name', 'two.desctiption',
    new Expression(
        ':type AS type',
        [':type' => $two_type]
    )])
    ->from('tbl_two')
    ->alias('two');

$query = (new Query())
    ->select(['name', 'description', 'type'])
    ->from(['one_two' => $one->union($two)]);

echo $query->createCommand()->getRawSql();
```

### What is the expected result?
```sql
SELECT `name`, `description`, `type` FROM
  (
    (SELECT `one`.`name`, `one`.`description`, 'TYPE_ONE' AS type FROM `tbl_one` `one`)
      UNION
    (SELECT `two`.`name`, `two`.`description`, 'TYPE_TWO' AS type FROM `tbl_two` `two`)
  ) `one_two`;
```
### What do you get instead?
```sql
SELECT `name`, `description`, `type` FROM
  (
    (SELECT `one`.`name`, `one`.`description`, 'TYPE_ONE' AS type FROM `tbl_one` `one`)
      UNION
    (SELECT `two`.`name`, `two`.`description`, 'TYPE_ONE' AS type FROM `tbl_two` `two`)
  ) `one_two`;
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.15
| Operating system | ubuntu 16.04.4

**Comment by TerraSkye** [comment]
that works as designed, u should change the placeholder of the second one?

**Comment by Inkognitoo** [comment]
@TerraSkye, yes, I did.
But you really sure that this is correct behavior is to override value in separate query?

**Comment by TerraSkye** [comment]
u are using them as a union , thefore u combine the 2 queries into 1?
or am i mistaken.

**Comment by sergeymakinen** [comment]
It's how it works at the moment. `QueryBuilder` merges `$params` from all involved query objects and that's why it's overridden.

**Comment by cebe** [comment]
This is expected behavior. If you use params in one query, each param needs a unique name.
