### ISSUE TITLE
Visible property for tags

### ISSUE THREAD

**Issue by pptyasar** [yiisoft/yii2#13939]
Its very help full if we have visible property for tags itself

**Comment by pptyasar** [comment]
When using Html helper class. There is no visible property for tags like like this one

echo Menu::widget([
    'items' => [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => '...', 'url' => ['/site/superadmin'], 'visible' => Yii::$app->user->isSuperAdmin()],//Here is a good way
    ],
]);

**Comment by cebe** [comment]
a single Html Tag can be wrapped into an if statement:

```php
if ($visible) Html::tag(...);
```

This is more obvious code than with a parameter.
