### ISSUE TITLE
Tag method in BaseHtml no closing slash

### ISSUE THREAD

**Issue by naemhd** [yiisoft/yii2#13933]
### What steps will reproduce the problem?

using tag method for void elements Ex. <br> will not add closing slash /> to the tag

### What is the expected result?
void element should have closing slash Ex. <link /> <br/>
### What do you get instead?
no closing slash in void element <br>

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.0
| Operating system | Linux

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/pull/13934
