### ISSUE TITLE
AssetBundle problem

### ISSUE THREAD

**Issue by coftsonyk** [yiisoft/yii2#13930]
```php
class PageAsset extends AssetBundle
{
    public $js = [
        '/js/custom-script.js',
        ['/js/page-script.js', 'depends' => 'app\assets\AppAsset']
    ];
}
```

The file /js/page-script.js and the dependent AppAsset bundle are not connected to the page, although information on their connection is displayed in the debug panel.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.4
| Operating system | Linux

**Comment by samdark** [comment]
How do you register this bundle?

**Comment by coftsonyk** [comment]
in module view file

`app\assets\PageAsset::register($this);`

**Comment by cebe** [comment]
> 'depends' => 'app\assets\AppAsset'

`depends` is not an option that works inside the `$js` property. An asset bundle either depends on another one as a whole or not, not for a single file.
