### ISSUE TITLE
Improve view registerMetaTags feature.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#13935]
When creating layouts we register the description and keywords meta tags in it.

```php
$view->registerMetaTag([
    'name' => 'description',
    'content' => 'This website is about funny raccoons.'
], 'page_description');
$view->registerMetaTag([
    'name' => 'keywords',
    'content' => 'funny,raccoons,pictures,videos,blablabla'
], 'page_keywords');
```
But sometimes we need to override these meta tags in the views. Using the second parameter of `registerMetaTag` use the one in the layout rather than the one defined in the view file.

index.php
```php
$view->registerMetaTag([
    'name' => 'description',
    'content' => $model->description
], 'page_description');
$view->registerMetaTag([
    'name' => 'keywords',
    'content' => implode(',', ArrayHelper::getColumn($model, 'categories.name')),
], 'page_keywords');
```

I think it would be better if it would use the one in the view file when using the second parameter or add another parameter to switch it.

**Comment by Alex-Code** [comment]
Would a character flag work, something like an exclamation ! before the key name.
Any subsequent calls to `registerMetaTag` with the same key would then check if the existing one has the flag.

```php
$view->registerMetaTag([
    'name' => 'description',
    'content' => $model->description
], '!page_description');
$view->registerMetaTag([
    'name' => 'keywords',
    'content' => implode(',', ArrayHelper::getColumn($model, 'categories.name')),
], '!page_keywords');
```

**Comment by berosoboy** [comment]
View files are processed first, then layout files.
I think you can do this at your layout files:
```
if (!isset($this->metaTags['page_description'])) {
    $view->registerMetaTag([
        'name' => 'description',
        'content' => 'This website is about funny raccoons.'
    ], 'page_description');
}
```
