### ISSUE TITLE
Forced client validation doesn't show validation error messages

### ISSUE THREAD

**Issue by glagola** [yiisoft/yii2#13940]
### What steps will reproduce the problem?
$('#contact-form').yiiActiveForm('validate', true);
### What is the expected result?
I expected to see validation error messages. According to documentation last parameter in the function is forceValidation.
### What do you get instead?
I saw no errors.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.1.3
| Operating system | Linux

**Comment by SilverFire** [comment]
Resolved by 8f2d9ba
