### ISSUE TITLE
VerbFilter - "Trying to get property of non-object"

### ISSUE THREAD

**Issue by suver** [yiisoft/yii2#13955]
### What steps will reproduce the problem?

```php
class ManageController extends CommonController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
   
   // ****
   public function actionDelete()
   {
       // ***
   }
}
```

### What is the expected result?

PHP Notice – yii\base\ErrorException

Trying to get property of non-object
1. in /var/www/crmisk/src/crmisk/vendor/yiisoft/yii2/filters/VerbFilter.php at line 90

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.1
| Operating system | RH6

**Comment by samdark** [comment]
Can not reproduce.
