### ISSUE TITLE
InputWidget: width issue

### ISSUE THREAD

**Issue by Commifreak** [yiisoft/yii2#13954]
See https://github.com/kartik-v/yii2-widget-switchinput/issues/17
and https://github.com/kartik-v/yii2-widget-switchinput/issues/17#issuecomment-273370289

tl:dr

Sometimes, the switch input width is broken after 2nd rendering:

1st try:

![ok](https://cloud.githubusercontent.com/assets/87267/24901495/895dc216-1ea7-11e7-9337-5cce72f1dc35.JPG)

2nd:

![nok](https://cloud.githubusercontent.com/assets/87267/24901500/8edabf46-1ea7-11e7-8d00-9735c2d04495.JPG)

All up-to-date.

**Comment by samdark** [comment]
Looks like third party component issue. Can't be fixed in the Yii iteslf.
