### ISSUE TITLE
Yii::setAlias

### ISSUE THREAD

**Issue by unasoft** [yiisoft/yii2#13957]
I encountered a problem when adding an alias, I added in bootstrap an alias @app but Yii overwrites it in
**/yii/base/Application**

`    public function setBasePath($path)
    {
        parent::setBasePath($path);
        Yii::setAlias('@app', $this->getBasePath());
    }`

What if you add to the functions, the parameter overwrite, like so `setAlias($alias, $path, $overwrite = true)`
and in the framework where **setAlias** is used to set the parameter `$overwrite` false, like so

`    public function setBasePath($path)
    {
        parent::setBasePath($path);
        Yii::setAlias('@app', $this->getBasePath(), false);
    }`

PS
Sorry. My english is bad.

**Comment by samdark** [comment]
I think for this particular case we can skip setting an alias if it's already there.

**Comment by cebe** [comment]
what is the use case for defining `@app` but not configuring application `basePath`?

**Comment by ejsoft** [comment]
Directory structure: 
```
| app
  | --- backend
  | --- console
  | --- frontend
| public
  | --- backend
  | --- frontend
```

set in bootstrap.php `Yii::setAlias('@app', 'path to app directory')` and use `namespace app\backend or app\console or app\frontend`

I think it's better to make a choice, not to force set it without the ability to change

**Comment by samdark** [comment]
Re-checked. Seems what you need could be achieved as @cebe suggested. Closing.
