### ISSUE TITLE
Add auto generating names in migrations index and foreignkey

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#13967]
Is it possible to add auto generate names in createIndex and addForeignKey, like in phpmyadmin?

**Comment by Vovan-VE** [comment]
Do you mean **$this->addForeignKey(~'fk-name'~, 'table', ...);** ?
How will you drop this FK in corresponding `down()` method and in any future migrations?

**Comment by rob006** [comment]
See #11910

**Comment by cebe** [comment]
as discussed in #11910 I do not think this is a good idea.
