### ISSUE TITLE
Migration: MS SQL alterColumn with ->null() syntax error

### ISSUE THREAD

**Issue by tsdogs** [yiisoft/yii2#13973]
### What steps will reproduce the problem?
In migration if I do:
$this->alterColumn('table','column',$this->integer()->null());

### What is the expected result?
IMHO the column should be created without error with:
ALTER TABLE [table] ALTER COLUMN [column] integer NULL

### What do you get instead?
SYNTAX ERROR:
ALTER TABLE [table] ALTER COLUMN [column] integer NULL DEFAULT NULL

### Additional info

The DEFAULT NULL should not be there!!!
Might be related to #12077 and #11158

**Comment by tsdogs** [comment]
I temporarily solve this by doing:
$this->alterColumn('table','column',$this->integer().' NULL');

**Comment by cebe** [comment]
which DBMS is that? MySQL?

**Comment by samdark** [comment]
MSSQL as said in the title.

**Comment by dillix** [comment]
I also have this issue on MySQL:
`access_token` varchar(100) NULL DEFAULT NULL
