### ISSUE TITLE
Add ArrayHelper::setValue()

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#13978]
ArrayHelper quite a powerful substance and it has a lot of useful methods for working with arrays.
Would suggest you add to the base supply another ArrayHelper::setValue()

Whose main task is to edit or add individual elements of the array.
The implementation can be seen here:
https://github.com/LAV45/yii2-settings/blob/master/src/helpers/BaseArrayHelper.php#L59
And tests:
https://github.com/LAV45/yii2-settings/blob/master/tests/helpers/ArrayHelperTest.php

A couple of examples for clarity:
```php
ArrayHelper::setValue(['key1' => 'val1'], 'key.in.arr', 'val');
/* return => 
[
    'key1' => 'val1',
    'key' => [
        'in' => [
            'arr' => 'val'
        ]
    ],
]
*/

$data = [
    'key' => [
        'in' => [
            'val1',
            'key' => 'val'
        ]
    ],
];
ArrayHelper::setValue($data, 'key.in', ['arr' => 'val']);
/* return => 
[
    'key' => [
        'in' => ['arr' => 'val']
    ],
]
*/
```

**Comment by SilverFire** [comment]
Duplicates #6644

Suggesting to continue discussion there
