### ISSUE TITLE
[IpValidator]  IPv6 validation can not be used. PHP is compiled without IPv6

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#13976]
### What steps will reproduce the problem?

Start validating some ip address usin IpValidator

### What is the expected result?

Should be fine?

### What do you get instead?

`yii\base\InvalidConfigException`: IPv6 validation can not be used. PHP is compiled without IPv6

### Additional info

PHP should not be compiled without IPv6 support...
My machine ( works )
```
$ php -a
Interactive mode enabled

php > var_dump(defined('AF_INET6'));
php shell code:1:
bool(true)
php > $hex = unpack('H*hex', inet_pton('2001:db8::1'));
php > echo substr(preg_replace('/([a-f0-9]{4})/i', '$1:', $hex['hex']), 0, -1);
2001:0db8:0000:0000:0000:0000:0000:0001
```

Container ( does not work )
```
$ docker run -it php
Interactive shell

php > var_dump(defined('AF_INET6'));
bool(false)
php > $hex = unpack('H*hex', inet_pton('2001:db8::1'));
php > echo substr(preg_replace('/([a-f0-9]{4})/i', '$1:', $hex['hex']), 0, -1);
2001:0db8:0000:0000:0000:0000:0000:0001

```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      |  7.0
| Operating system | Docker container

**Comment by cebe** [comment]
where did you get the container, how was it created?

**Comment by mikk150** [comment]
It's php docker container..
The problem is, that even though `var_dump(defined('AF_INET6'))` says that IPv6 is not installed `inet_*` methods that this validator relies on are working as they should

**Comment by mikk150** [comment]
Yep
IpValidator works perfectly with without even this AF_INET6

```Dockerfile
FROM php:7.0

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apt-get update && apt-get install -y \
    libcurl4-gnutls-dev libssl-dev \
    zlib1g-dev libicu-dev g++ \
    git \
 && docker-php-ext-configure intl \
 && docker-php-ext-install -j$(nproc) pdo pdo_mysql curl intl zip \
 && git clone https://github.com/mikk150/yii2.git /usr/src/yii2 \
 && cd /usr/src/yii2 \
 && git checkout check-docker \
 && curl -sS https://getcomposer.org/installer | php -- \
 && php composer.phar global require fxp/composer-asset-plugin \
 && php composer.phar update -n --no-scripts

WORKDIR /usr/src/yii2
CMD [ "php", "vendor/bin/phpunit", "tests/framework/validators/IpValidatorTest.php" ]
```
and then run the container
My branch is master without those checks
