### ISSUE TITLE
Cannot declare class m140209_132017_init, because the name is already in use

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#13989]
### What steps will reproduce the problem?
configure
```
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'app\migrations',
                'yii\rbac\migrations',
                'dektrium\user\migrations',
                'mdm\admin\migrations',
            ],
        ],
    ],
```

### What is the expected result?
migrate up
### What do you get instead?
```sh
./yii migrate/up 1
Yii Migration Tool (based on Yii v2.0.11-dev)

Total 1 out of 17 new migrations to be applied:
	dektrium\user\migrations\m140209_132017_init

Apply the above migration? (yes|no) [no]:y
*** applying dektrium\user\migrations\m140209_132017_init
PHP Compile Error 'yii\base\ErrorException' with message 'Cannot declare class m140209_132017_init, because the name is already in use'
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | yiisoft/yii2                 dev-master 03e0607 Yii PHP Framework Version 2
| PHP version      |PHP 7.1.3 (cli) (built: Mar 17 2017 22:24:22) ( NTS )
| Operating system |Debian

**Comment by cebe** [comment]
do you have an other migration with that name?

**Comment by bscheshirwork** [comment]
I find problem
no set namespace in the  migration file
new feature so new

**Comment by bscheshirwork** [comment]
After I put namespace into a migration class file 
I still can do apply the migration without `config` 
```
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'app\migrations',
                'yii\rbac\migrations',
                'dektrium\user\migrations',
                'mdm\admin\migrations',
            ],
        ],
    ],
```
using `--migratePath`? 
```
./yii migrate/up --migrationPath=@yii/rbac/migrations/
./yii migrate/up --migrationPath=@dektrium/user/migrations
./yii migrate/up --migrationPath=@mdm/admin/migrations
```

**Comment by SilverFire** [comment]
We will add namespaces to migrations
https://github.com/yiisoft/yii2/issues/13918

**Comment by bscheshirwork** [comment]
The migration with namespace still work in the old project (i.e. module migration)?

**Comment by SilverFire** [comment]
I'm not sure that I've got your question.

**Comment by bscheshirwork** [comment]
Sorry( So...
1. Current schema (not ideal):
Apply migration in project without namespace `./yii migrate/up`
Apply migration from vendor module without namespace `./yii migrate/up --migrationPath=@yii/rbac/migrations/`

2. Module have update, migration have namespace now. Project not modified.

3. BC: Migration in module must still work with old syntax. (Autoload must use any of both method)

**Comment by SilverFire** [comment]
Could you re-post this message to #13918 and we will continue discussion there?
