### ISSUE TITLE
Feature request: ASCII Tables

### ISSUE THREAD

**Issue by tonykor** [yiisoft/yii2#13987]
Hello,

please consider adding a function to Console helper, which will create an ANSII tables from array of data like in Zend https://framework.zend.com/manual/2.1/en/modules/zend.text.table.html

Thanks.

**Comment by pana1990** [comment]
i am woriking this feature https://github.com/yiisoft/yii2/pull/11415#issue-150664421

duplicated https://github.com/yiisoft/yii2/issues/11412

Thanks for your link ;)

**Comment by arogachev** [comment]
Closing as duplicate of #11412.
