### ISSUE TITLE
yii\caching\Cache::getOrSet() has a type requirement for \Closure, but callable would be sufficient

### ISSUE THREAD

**Issue by spikyjt** [yiisoft/yii2#13981]
At this line: https://github.com/yiisoft/yii2/blob/master/framework/caching/Cache.php#L569 the method signature requires `\Closure`, however the implementation uses `call_user_func()`, for which callable is sufficient. This could be checked with `is_callable()`.

Allowing any callable, rather than specifically `\Closure`, would allow one to use an array callable. This is preferable in model objects, because closures cannot be serialized.

I appreciate that serializing closures will be a future addition to Yii, but it is not ready yet. This limitation makes `getOrSet()` mostly unusable for me.

**Comment by spikyjt** [comment]
@SilverFire may have an opinion on this as he wrote the code.

**Comment by SilverFire** [comment]
Fixed, thank you for your suggestiong
