### ISSUE TITLE
How to inherit relational classes along with inherited class?

### ISSUE THREAD

**Issue by ReNoM** [yiisoft/yii2#13990]
Is it possible to inherit several ActiveRecord models with support of inheritance in relations between them (hasOne, hasMany)? Example:

File structure:
1. common/models/Model.php
2. common/models/Relation.php
3. frontend/models/Model.php
4. frontend/models/Relation.php

```
// common/models/Model.php

namespace common\models;
class Model extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'model';
    }

    public function getRelation() {
        return $this->hasOne(Relation::className(), ['id' => 'relation_id']);
    }
}
```

```
// common/models/Relation.php
namespace common\models;
class Relation extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'relation';
    }
}
```

```
// frontend/models/Model.php
namespace frontend\models;
class Model extends \common\models\Model
{
}
```

```
// frontend/models/Relation.php
namespace frontend\models;
class Relation extends \common\models\Relation
{
    public function getProperty()
    {
        return 2;
    }
}
```

Following code doesn't work:
```
$model = new \frontend\models\Model;
echo $model->relation->property;

```
Is there something possibilities to get this code works?

**Comment by rob006** [comment]
AR will not magically use fronted models in relations. You need to redefine it in every model. But you can use some hack to simplify this:

```php  
    public function getRelation() {
        return $this->hasOne(static::getNamespace() . '\Relation', ['id' => 'relation_id']);
    }
```

You need to implement `getNamespace()` yourself, but there are examples of how to do it: http://stackoverflow.com/questions/28182783/get-namespace-of-an-object-using-an-abstract-class-or-trait

**Comment by krukru** [comment]
This will be a common problem for anyone using this type of file structure (anyone using yii2-advanced-template).

When you have a large project, redefining relations in models is not practical.

I am interested in your solution @rob006, where should `getNamespace()` be defined?

**Comment by rob006** [comment]
@krukru You probably have some base class for all ActiveRecord models in your app, so I would put it there. But it may be useful enough to put it into `BaseObject` class in framework core.

Also note that this solution introduces a lot of magic and forces mirroring all models structure for each namespace. It is also more complicated when you need link models with different namespace. In large project these limitations can be really painful, so this is rather a solution for super-lazy people in short-time projects. :)

Personally I'm using dictionary method with models map, and something like this:

```php
    public function getUsers() {
        return $this->hasOne(static::getRelationsClassmap()['users'], ['id' => 'relation_id']);
    }
```

I declare maps manually, but you could use "relative namespaces" as default implementation and override it only when it's needed.
