### ISSUE TITLE
View::beginContent and AssetBundle::register

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#13993]
### What steps will reproduce the problem?
create 2 layouts:
1. `root.php`:
```php
RootAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<?= $content?>

</html>
<?php $this->endPage() ?>
```
2. `main.php`:
```php
$this->beginContent('@alias/to/layouts/root.php');
?>
<body>
<?php $this->beginBody() ?>
//body here
<?php $this->endBody() ?>
</body>
<?php $this->endContent(); ?>
```
### What is the expected result?
RootAsset is registered
### What do you get instead?
RootAsset is not register.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.1.1-1
| Operating system | debian 4.9.0-2-amd64

**Comment by lynicidn** [comment]
if root asset move to `main.php` it work

**Comment by ejsoft** [comment]
right, because `root.php` is executed after` main.php` and the registration of assets occurs in the `$this->endBody()` you need move 
```
<?php $this->beginBody() ?>
//body here
<?php $this->endBody() ?>
```
in root.php

PS
sorry for my english)

**Comment by lynicidn** [comment]
@ejsoft yes, am understand problem
