### ISSUE TITLE
Duplicate URL issues

### ISSUE THREAD

**Issue by rahulmishra1991** [yiisoft/yii2#14004]
My SEO guy showing duplicate URL for the following URL
https://www.icando.ng/#
https://www.icando.ng/?
https://www.icando.ng/index.php

It will redirect on https://www.icando.ng 

This is my YII 2.0 project..Please share the solution for this.

My .htaccess code 

RewriteEngine On
RewriteBase /
RewriteCond %{HTTPS} off
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteRule .* https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)\?*$ index.php?r=$1 [L,QSA]

config/web.php

 'enablePrettyUrl' => true,
//'enableStrictParsing' => true,
'showScriptName' => false,

Thanks

**Comment by rahulmishra1991** [comment]
How can i avoid these special characters from URl?

**Comment by Thoulah** [comment]
`?` and `#` are characters that are ok to be there. Not sure why your "SEO guy" has a problem with this.

The index.php can probably be avoided with this code in your `.htaccess`
```
RewriteBase /
RewriteCond %{THE_REQUEST} ^GET.*index\.php [NC]
RewriteRule (.*?)index\.php/*(.*) /$1$2 [R=301,NE,L]
```
(untested)
