### ISSUE TITLE
how to use hmget

### ISSUE THREAD

**Issue by biankemi** [yiisoft/yii2#14008]
### What steps will reproduce the problem?
使用redis的hmget方法批量获取的时候
`\Yii::$app->redis->hmget("test",["key1","key2"])`
报错 `mb_strlen() expects parameter 1 to be string, array given`

### What is the expected result?
可以获取到key1 key2的value

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version    | 5.6
| Operating system | Windows 7

**Comment by cebe** [comment]
`\Yii::$app->redis->hmget("test", "key1","key2")`
