### ISSUE TITLE
Warning after erase runtime/cache dir. in PHP7.1

### ISSUE THREAD

**Issue by xarakiry** [yiisoft/yii2#14015]
After erase directory runtime/cache/ and reload the page an error
PHP Warning – yii\base\ErrorException
filemtime(): stat failed for ..../../../../runtime/cache\96\963454f612a8b5fb4a63ba1e97f028a1.bin
in 
vendor\yiisoft\yii2\caching\FileCache.php
```
protected function getValue($key)
    {
        $cacheFile = $this->getCacheFile($key);
 
        **if (@filemtime($cacheFile) > time()) {**
            $fp = @fopen($cacheFile, 'r');
            if ($fp !== false) {
                @flock($fp, LOCK_SH);
                $cacheValue = @stream_get_contents($fp);
                @flock($fp, LOCK_UN);
                @fclose($fp);
                return $cacheValue;
            }
        }
```
I think it must be 
` if (is_file($cacheFile) && @filemtime($cacheFile) > time()) {`
instead of 
`if (@filemtime($cacheFile) > time()) {`

PS.
Everything is ok in PHP 5.5

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
![2017-04-20_10-28-52](https://cloud.githubusercontent.com/assets/4180510/25216536/36b9b650-25b4-11e7-8f36-34869a837068.png)

| PHP version      | 7.1
| Operating system | Windows 8.1

**Comment by samdark** [comment]
I can't reproduce that. PHP 7.1.2, Windows 10.

**Comment by samdark** [comment]
What's your Yii version? Have you tried code from master branch?

**Comment by cebe** [comment]
how can a function prefixed with `@` throw a warning?

**Comment by bizley** [comment]
[scream](http://php.net/manual/en/book.scream.php) enabled?

**Comment by xarakiry** [comment]
@samdark  To reproduce you need to delete all files from runtime/cache directory
Then start app again(reload page) and look into runtime/cache. It is empty
Yii2 doesn't make cache again
PHP7 x64

I'm using openserver
After change php version to 5.5 everything is ok

**Comment by xarakiry** [comment]
I'm using code loaded with composer as described in http://www.yiiframework.com/download/

**Comment by samdark** [comment]
Unable to reproduce with PHP 7.1.2. Is there anything special about your config?

**Comment by xarakiry** [comment]
I think it's a php bug of x64, cause everything is ok on 7.1.
I've similar error on line 264 gii Generator
`@mkdir(dirname($path), 0755, true);`

**Comment by dynasource** [comment]
While resetting my caches & cache folders on daily base, I never ever had this error, either in 7.0.1 till 7.0.10 or in 7.1.0 till 7.1.5RC. It really looks like something in your local environment.

**Comment by zava75** [comment]
Есть решение php 7 openserwer WIN10? Папка кеша пуста runtime / cache

**Comment by splaa** [comment]
I just commented out the following line in the php.ini file; xdebug.scream

**Comment by zava75** [comment]
Решено! Поменял версию open server на последнею!
