### ISSUE TITLE
Suggestion for yii\rest\CreateAction and yii\rest\UpdateAction

### ISSUE THREAD

**Issue by ReNoM** [yiisoft/yii2#14010]
Callable property for yii\rest\CreateAction and yii\rest\UpdateAction which should allows modifying new model before saving was produced. I think it would be useful and more conveniently than make these things in beforeAction of model or make redefinition of actionCreate / actionUpdate entirely.

**Comment by samdark** [comment]
Could you provide an example? It's not clear now...

**Comment by ReNoM** [comment]
For example I wanna prepare my model by such scenario - to set up author_id field manually (instead of loading it from the POST data). In the scenario author_id would be set from user.id of the authorised user.

**Comment by samdark** [comment]
Still can't get it :(

**Comment by cebe** [comment]
so you want a beforeSave() event or function in the action class instead of the model?

**Comment by ReNoM** [comment]
Ok. For example we can use something similar with another yii\rest\ActiveController actions. It's findModel for yii\rest\ViewAction, yii\rest\UpdateAction, yii\rest\DeleteAction and prepareDataProvider for yii\rest\IndexAction. I think the suggestion should be done by adding another callable property, which should supports CreateAction. For example (controller code):


```
    public function actions()
    {
        $actions = parent::actions();
        $actions['create']['prepareModel'] = [$this, 'prepareModel'];
        return $actions;
    }

prepareModel($model) {
    $model->author_id = Yii::$app->user->id;
    return $model;
}
```

**Comment by Deele** [comment]
If I understood op issue correctly, then I had a similar issue where I wanted to load specific language for multi-lingual model, depending on request.

I did it like this:

For [$modelClass](http://www.yiiframework.com/doc-2.0/yii-rest-activecontroller.html#$modelClass-detail) I create new model class `ApiArticle` that extends `Article`.

Inside `ApiArticle` I added event handlers:

    public function init()
    {
        parent::init();
        $this->on(
            self::EVENT_AFTER_FIND,
            [$this, 'loadSelectedLanguage']
        );
        $this->on(
            self::EVENT_BEFORE_VALIDATE,
            [$this, 'loadSelectedLanguage']
        );
    }

and a method

    public function loadSelectedLanguage()
    {

        /**
         * @var yii\rest\ActiveController $controller
         */
        $controller = Yii::$app->controller;
        $this->language = $controller->language;
    }

With similar method you can make changes, predefine values and do anything else with model that is managed via API.

**Comment by ReNoM** [comment]
Yes, it should works. But as I understand, you quoted a part of ActiveRecord model code. My offer is add support for same feature to action classes yii\rest\CreateAction and yii\rest\UpdateAction.

**Comment by Deele** [comment]
@ReNoM You are talking about very specific situation that should be dealt with in very specific way. Using ActiveRecord events and extended class is much more flexible and it really works. I don't think that there should be special `prepareModel` thing for create and update, because it is possible to require preparation for read, read collection and delete actions too, not to mention custom actions that would require some preparation too, and to implement that, it would require too much work to justify not using custom ActiveRecord class.

**Comment by ReNoM** [comment]
Can you prove justification of necessity for your assertion "because it is possible to require preparation for read, read collection and delete actions too, not to mention custom actions that would require some preparation too"? I don't think so, because there we can use the findModel property for these purposes. As for custom actions... I don't think that they need a similar feature, because it's custom actions, and programmer in any case must develops full code of these actions kind. Some words from Yii developers?

**Comment by tunecino** [comment]
I'm not sure if adding this feature is a good idea. The ActiveController class is providing simple actions and developers are supposed to override them within their controllers whenever they require a different implementation. Adding more code to default implementation may make it more complex and harder to follow to newcomers and less people will do the override thing as it should be.

**Comment by ReNoM** [comment]
@tunecino but why the developers added support for similar features inside yii\rest\IndexAction, yii\rest\ViewAction, yii\rest\UpdateAction, yii\rest\DeleteAction? I mean prepareDataProvider and findModel properties, which I mentioned above. I think yii\rest\ActiveController class was added as simplified and typical cases usage version of yii\rest\Controller. It means that purpose of yii\rest\ActiveController creation is allow to develop restful web api with minimal code repetition between different controllers from the box. In other cases you can use yii\rest\Controller or override methods of yii\rest\ActiveController as you mentioned above.

**Comment by tunecino** [comment]
Well that makes sense too @ReNoM . I personally understood how REST works after checking the code inside `yii\rest\Controller`. Before that and by just reading docs I used to extend `yii\rest\ActiveController` and unsettling its actions even if I didn't need any of them. Understanding how `yii\rest\Controller` works was the key point to link what I knew from `yii\web\Controller` to how REST works. So maybe overall improvements to REST should be the following:

1. improve docs with examples to use `yii\rest\Controller` before jumping to `yii\rest\ActiveController`. `yii\rest\ActiveController` may be better presented as a helper class instead of actual REST.
2. `checkAccess()` method may be better moved to `yii\rest\Controller`.
3. `yii\rest\OptionsAction` may be better moved to `yii\rest\Controller` or at least explained in docs to be added if required. (I remember having seen @cebe suggesting an alternative implementation for it but I can't find that conversation)

I know those are different issues but I'm just trying to say that when the use of `yii\rest\Controller` and its relation to `yii\rest\ActiveController` are clearer then it will make sense to improve `yii\rest\ActiveController` and add features like the one you are suggesting which I think it will become useful in that case.

**Comment by Faryshta** [comment]
i dont see why its not ok to have a `checkAccess()` in the controller and the action, we just need a way to attach them without overwrite previous parameters.

something like

```php
class Action
{
     public function checkAccess()
     {
          $this->controller->checkAccess();
          if (null !== $this->checkAccess) {
              call_user_func($this->checkAccess, $this->id);
          }
     }
}
```

and for the `prepareModel()`. if you want to modify the model before running the `save()` logic you need to over write the entire `CreateAction::run()` method. you can't call `parent::run()` anywhere so for me it makes sense to have such method.

**Comment by ReNoM** [comment]
My implementation of this feature for yii\rest\CreateAction.

Contents of vendor/yiisoft/yii2/rest/CreateAction.php file or code of custom class inherited from yii\rest\CreateAction class:
```diff
+   public $prepareModel;

    public function run()
    {
        if ($this->checkAccess) {
            call_user_func($this->checkAccess, $this->id);
        }

        /* @var $model \yii\db\ActiveRecord */
        $model = new $this->modelClass([
            'scenario' => $this->scenario,
        ]);

        $model->load(Yii::$app->getRequest()->getBodyParams(), '');
+       if($this->prepareModel !== null) {
+           $model = call_user_func($this->prepareModel, $model);
+       }
        if ($model->save()) {
            $response = Yii::$app->getResponse();
            $response->setStatusCode(201);
            $id = implode(',', array_values($model->getPrimaryKey(true)));
            $response->getHeaders()->set('Location', Url::toRoute([$this->viewAction, 'id' => $id], true));
        } elseif (!$model->hasErrors()) {
            throw new ServerErrorHttpException('Failed to create the object for unknown reason.');
        }

        return $model;
    }
```
Next you should override an actions() method of your controller, and describe code of custom prepareModel realization:
```diff
// some code of some controller
// ...
// ...
// code ends
+   public function actions()
+   {
+       $actions = parent::actions();
+
+       $actions['create']['prepareModel'] = [$this, 'prepareModel'];
+
+       return $actions;
+   }
+
+   public function prepareModel($model)
+   {
+       // fill up field manually
+       $model->some_field = 'some_value';
+       return $model;
+   }
// code of your controller follows further
```
Currently I use a custom class which is inherited from yii\rest\CreateAction class. In the class I have overridden run() method entirely.

**Comment by mikk150** [comment]
I think you should do different models from common for REST api afterall

gives you more control, and there you can do pretty much whatever you want without hacking Controller

**Comment by Vovan-VE** [comment]
Why not to implement the feature as some extension points (callbacks and/or overrideable methods) to let framework components (REST actions) be more flexible? Let end developer to decied how to use it.

Are PRs allowed?
