### ISSUE TITLE
[enh] Add `like`, `in` and `between` operators to `Query::andFilterCompare()` method.

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#14013]
something like

```php
->andFilterWhere('attribute', '~hello'); // attribute like '%hello%'
->andFilterWhere('attribute', '=2,3'); // attribute in (2, 3)
->andFilterWhere('attribute', ':2013-01-01,2015-03-31'); // attribute between '2013-01-01' and '2015-03-01'
```

or

```php
->andFilterWhere('attribute', 'like:hello'); // attribute like '%hello%'
->andFilterWhere('attribute', 'in:2,3'); // attribute in (2, 3)
->andFilterWhere('attribute', 'between:2013-01-01,2015-03-31'); // attribute between '2013-01-01' and '2015-03-01'
```

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/tests/framework/db/QueryTest.php#L77-L110

**Comment by Faryshta** [comment]
@klimov-paul different methods. i mention `andFilterCompare()` method, not `andFilterWhere()` please read the examples on my post.

**Comment by klimov-paul** [comment]
I can not see `andFilterCompare` at the issue description:

![filter-where](https://cloud.githubusercontent.com/assets/1482054/25222732/fa12a4e2-25c1-11e7-8c02-f0bb3ff88356.JPG)

**Comment by Faryshta** [comment]
you are right, i only put it on the title and edited the description

**Comment by klimov-paul** [comment]
I am against such change: using comparison operators like `>`, `<` and so on can be justified as they can be used only for the number-type attributes. For the string attributes usage of magic keywords produces ambigous behavior.

`andFilterCompare()` allows value to be a pure value, e.g. `5`, `6.7` and so on. Covering strings with it eliminates such ability: for the string value `~something` is a valid exact match value.

> ->andFilterCompare('attribute', '~hello'); // attribute like '%hello%'

What if I wish to search tilda (`~`) symbol in `attribute` what should I do? If I type `~` in the search field - it will search `like '%%'`.

> ->andFilterCompare('attribute', '=2,3'); // attribute in (2, 3)

Coma (`,`) can not be used for syntax as at some locales it is a decimal separator. If I wish to search value between `5.6` and `7.8` in russian locale it will end with following string: `=5,6,7,8`.

In general I do not like the idea of invension the full-scale internal language for comparison definition inside the Yii core - especially at `yii\db\Query` level .It is better to be extracted to the separated extension.

**Comment by Faryshta** [comment]
there is an alternate syntax i proposed

->andFilterCompare('attribute', 'like:hello'); // attribute like '%hello%'
->andFilterCompare('attribute', 'in:2,3'); // attribute in (2, 3)
->andFilterCompare('attribute', 'between:2013-01-01,2015-03-31'); // attribute between '2013-01-01' and '2015-03-01'

and i didn't though about using coma for decimal separator, then how about pipelines? `=5,6|5,8`

question: `>5,6` works right how?
