### ISSUE TITLE
Unique validation rules does not work with transaction

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#14019]
### What steps will reproduce the problem?
Create transaction to save 2 new models into database
First is one of properties in the second, and the second has a unique validation rule.

### What is the expected result?
Save models and all save methods returns true.

### What do you get instead?
Saving poll lock returns false without any error.
If I do not check it for equals to true, it saves record anyway.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.2
| Operating system | Windows 10

Database engine: MySQL, InnoDB

Here is some code for example:
```php
$pollOpinion = new PollOpinion();
$pollOpinion->save(); // returns true

$pollLock = new PollLock();
$pollLock ->poll_opinion_id = $pollOpinion->id;
$pollLock ->user_id = $user->id;
$pollLock ->save(); // returns false
```

**Comment by cebe** [comment]
when saving multiple models in a row it is better to run validation for all models before calling save().

```php
if ($modelA->validate() && $modelB->validate()) {
    // ...
    $modelA->save(false);
    // ...
    $modelB->save(false);
}

```

Also I do not see the use of transaction in your code.
What exactly is the bug?

**Comment by mklemarczyk** [comment]
Sice when you saves them with separate save methods?

**Comment by mklemarczyk** [comment]
@cebe Cebe you shown option without using a transaction...
