### ISSUE TITLE
function findViewNames() in yii\db\pgsql\Schema skip materialized views

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii2#14012]
### What steps will reproduce the problem?
I have some materialized views and try to use InitDbFixture in my test and got exception 
` [yii\db\Exception] SQLSTATE[42809]: Wrong object type: 7 ОШИБКА:  "my_materialized_view" - это не таблица и не сторонняя таблица`
that happens on stage 
```php
    public function beforeLoad()
    {
        $this->checkIntegrity(false);
    }
```

My code research  shows that problem in
```php
namespace yii\db\pgsql\Schema;
....
    protected function findViewNames($schema = '')
    {
        if ($schema === '') {
            $schema = $this->defaultSchema;
        }
        $sql = <<<SQL
SELECT c.relname AS table_name
FROM pg_class c
INNER JOIN pg_namespace ns ON ns.oid = c.relnamespace
WHERE ns.nspname = :schemaName AND c.relkind = 'v'
ORDER BY c.relname
SQL;
        return $this->db->createCommand($sql, [':schemaName' => $schema])->queryColumn();
    }
```

It skip only views,  but for materialized views sql must be 
```php
$sql = <<<SQL
SELECT c.relname AS table_name
FROM pg_class c
INNER JOIN pg_namespace ns ON ns.oid = c.relnamespace
WHERE ns.nspname = :schemaName AND (c.relkind = 'v' OR c.relkind = 'm' )
ORDER BY c.relname
SQL;
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | ~2.0.11
| PHP version      |7.1.3 
| Postgres | 9.6.1

**Comment by samdark** [comment]
@Insolita how about a pull request?
