### ISSUE TITLE
[ActiveRecord] setAttributes method not working !

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [yiisoft/yii2#14026]
### What steps will reproduce the problem?

**class**
```
class myTestClass extends yii\db\ActiveRecord{

    const TBL_NAME = 'test';
    
    public static function tableName(){
        return self::TBL_NAME;
    }
    
    public function behaviors(){
        return [
            'typecast' => [
                'class' => AttributeTypecastBehavior::className(),
                'attributeTypes' => [
                    'a' => AttributeTypecastBehavior::TYPE_INTEGER,
                    'b' => AttributeTypecastBehavior::TYPE_INTEGER,
                ],
                'typecastAfterFind' => true,
                'skipOnNull' => true,
            ],
        ];
    }
}
```

**action**
```
$myOldClass = myTestClass::findOne(1);

yii::trace($myOldClass->attributes);

$newClass1 = new myTestClass(['attributes' => $myOldClass->attributes]);
$newClass2 = new myTestClass();
$newClass3 = new myTestClass();

$newClass2->setAttributes($myOldClass->attributes);
$newClass3->attributes = $myOldClass->attributes;

yii::trace($newClass1->attributes);
yii::trace($newClass2->attributes);
yii::trace($newClass3->attributes);
```

**yii trace output**
`[ 'id' => 1, 'a' => 1, 'b' => 1, ]`
`[ 'id' => null, 'a' => null, 'b' => null, ]`
`[ 'id' => null, 'a' => null, 'b' => null, ]`
`[ 'id' => null, 'a' => null, 'b' => null, ]`

### What is the expected result?
`[ 'id' => 1, 'a' => 1, 'b' => 1, ]`
`[ 'id' => 1, 'a' => 1, 'b' => 1, ]`
`[ 'id' => 1, 'a' => 1, 'b' => 1, ]`
`[ 'id' => 1, 'a' => 1, 'b' => 1, ]`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6.3

**Comment by SilverFire** [comment]
You do not have validators for attributes `a` and `b` therefore they are not considered safe.
Describe validation or pass `false` as a second argument of `setAttributes()` method to skip attributes safety checking.

See [Model::setAttribute()](http://www.yiiframework.com/doc-2.0/yii-base-model.html#setAttributes()-detail) docs
