### ISSUE TITLE
Table aliasing not working with unique validator

### ISSUE THREAD

**Issue by Renkas** [yiisoft/yii2#14028]
### What steps will reproduce the problem?
I have a base model where I have set up an unique validator.
I then have a couple of models that extend from that - and those use table aliases - because I often need to query these together.
Now when I create a new model and try to validate the input I get a SQL error because unique validator generates where clause with table name and not with table alias.

### What is the expected result?
Unique validator should use table alias

### What do you get instead?
I get a SQL error because unique validator generates where clause with table name and not with table alias.

### Additional info
This is the SQL error. You should get the picture on what I'm doing from that
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'translation.language_id' in 'where clause'
The SQL being executed was: SELECT `id` FROM `translation` `localNames` WHERE (`localNames`.`type`=1) AND ((`translation`.`language_id`='1') AND (`translation`.`type`=1) AND (`translation`.`entity_id`=9495)) LIMIT 2

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12-dev
| PHP version      | 7.0.14
| Operating system |  Linux

**Comment by Renkas** [comment]
[UniqueValidator ->prepareConditions](https://github.com/yiisoft/yii2/blob/master/framework/validators/UniqueValidator.php#L235) seems to be the problem spot. Is it really neccessary to prefix column name with a table name?

**Comment by Renkas** [comment]
Ok I dug a little deeper and this functionality was added as a partial fix for #13704 
There is a issue that tries to solve the problem #13842 
And a pull request #13857 

But it seems the solution has been stalled :(

**Comment by samdark** [comment]
Closing this one as duplicate.
