### ISSUE TITLE
Suggestion for \yii\data\Sort

### ISSUE THREAD

**Issue by vuongminh** [yiisoft/yii2#14023]
Currently a `direction` when createUrl, sortParam, link of `\yii\data\Sort` is automate detect via `sortParam` or not it will get a default in `attributes` config. But some case it's not flexible when I want to specified direction.

Example:
```php

$sort->link('price', SORT_DESC);

```

And a `label` in `attributes` config should be accept closure 

```php

$attributes = [
       'price' => [
                 'desc' => ['price' => SORT_DESC],
                 'asc' => ['price' => SORT_ASC],
                 'label' => function($direction) {
                       return $direction === SORT_DESC ? 'high to low' : 'low to high';
                 }
       ]

];

```

**Comment by rob006** [comment]
#8456
