### ISSUE TITLE
Configuration: 'identityClass' property of User component cause migration error.

### ISSUE THREAD

**Issue by dabagab** [yiisoft/yii2#14034]
### What steps will reproduce the problem?
I set the `identityClass` property in the `common/config.php`
Run `vagrant destroy` then `vagrant up` commands which will rerun the migration.

```
'user' => [
            'identityClass' => 'common\models\User',
        ]
```

### What is the expected result?
The migration run without error.
The migration files are fine! Because when I remove the `user` component from the `common/config.php` it runs perfectly without any errors!

### What do you get instead?
```
==> PHP-Yii-VM: Exception 'yii\base\InvalidConfigException' with message 'The configuration for the "user" component must contain a "class" element.'
==> PHP-Yii-VM: 
==> PHP-Yii-VM: in /vagrant/app/vendor/yiisoft/yii2/di/ServiceLocator.php:202
==> PHP-Yii-VM: 
==> PHP-Yii-VM: Stack trace:
==> PHP-Yii-VM: #0 /vagrant/app/vendor/yiisoft/yii2/di/ServiceLocator.php(258): yii\di\ServiceLocator->set('user', Array)
==> PHP-Yii-VM: #1 /vagrant/app/vendor/yiisoft/yii2/base/Component.php(169): yii\di\ServiceLocator->setComponents(Array)
==> PHP-Yii-VM: #2 /vagrant/app/vendor/yiisoft/yii2/BaseYii.php(521): yii\base\Component->__set('components', Array)
==> PHP-Yii-VM: #3 /vagrant/app/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(yii\console\Application), Array)
==> PHP-Yii-VM: #4 /vagrant/app/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
==> PHP-Yii-VM: #5 /vagrant/app/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
==> PHP-Yii-VM: #6 /vagrant/app/yii(26): yii\console\Application->__construct(Array)
==> PHP-Yii-VM: #7 {main}

```
However if I set the `class` property then I will not be able to use `identityClass` property. In runtime I will get the `Setting unknown property: common\models\User::identityClass` error. So this is the trap.

Why I set the `identityClass` because I have to reach properties of the User object.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      |  7.0
| Operating system | Ubuntu Server 16.04 (Vagrant box)

**Comment by Renkas** [comment]
You are missing the `class` element from the configuration.

Even the error states it ;)

**Comment by dabagab** [comment]
> However if I set the class property then I will not be able to use identityClass property. In runtime I will get the Setting unknown property: common\models\User::identityClass error. So this is the trap.
> 
> Why I set the identityClass because I have to reach properties of the User object.

Yes I missing, but If add the `class` element, I will get the quoted error. So it seems the `class` and the `identityClass` element cannot use together! It does not make sense, because without the `identityClass` property I am not able to get some attribute of the user class: `\Yii::$app->user->identity->someAttribute`

**Comment by samdark** [comment]
The issue is that you're in the console environment when applying migration and no web user is available there. It is as it should be. In migrations you should never try to use models.

**Comment by dabagab** [comment]
I did not use the 'user' model in the migration or in the console environment. So I do not get your explanation. My configuration is existing under **common**

**Comment by samdark** [comment]
I don't get it. What are you using to run migrations? Console `migrate` command?
