### ISSUE TITLE
Create Pretty Url in Yii2 Console

### ISSUE THREAD

**Issue by kakalos12** [yiisoft/yii2#14037]
Hi,
Please help me. I'm dealing with the problem of creating the pretty url in console app. 
Here is my config in console.php :

```
'urlManager' => [
        'enablePrettyUrl' => true,
        'scriptUrl' => 'https://example.com',
        'rules' => [
            'api/unsubscribe/<param:\w+>' => 'api/web/unsubscribe'
        ]
    ],
```

But when I tried to create a pretty url in console using this line of code

```
Url::to([
        "api/web/unsubscribe",
        'param' => base64_encode(serialize($params))
    ]);
```

It creates a url like example.com/api/web/unsubscribe?param=aTo4NjAwOw%3D%3D

Any solutions to create a url like example.com/api/unsubscribe/aTo4NjAwOw%3D%3D

**Comment by Faryshta** [comment]
which version of yii2 you use? you can check by running `composer show yiisoft/yii2`

**Comment by kakalos12** [comment]
I'm using versions : * 2.0.11.2

**Comment by kakalos12** [comment]
This is my web.php config. It's having the problem that it duplicates the "api" string. it generates the url like /api/api/web/unsubscribe?param=YToxOntzOjY6ImtzZGZpZSI7czo0OiJzZGllIjt9

While the console generates the url api/web/unsubscribe?param=aTo4NjAwOw%3D%3D

`'modules' => [
        'api' => [
            'class' => 'app\modules\api\Module'
        ]
    ],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '8+S5+4eKX)U&!QM;FCA/}<ew;#y~y#gc',
            'parsers' => [
                'application/json' => 'yii\web\JsonParser'
            ]
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache'
        ],
        'user' => [
            'identityClass' => 'app\models\db\Users',
            'enableAutoLogin' => false,
            'loginUrl' => null,
            'enableSession' => false
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => false,
            'scriptUrl' => 'https://sesmailer.net',
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'api/list',
                    'extraPatterns' => [
                        'GET <id:\d+>/subscribers' => 'subscribers',
                        'POST <id:\d+>/addSubscriber' => 'add-subscriber',
                        'GET <id:\d+>/getAutoresponders' => 'get-autoresponders'
                    ],
                    'tokens' => [
                        '{id}' => '<id:\\d+>'
                    ],
                    'pluralize' => false
                ],
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'api/subscriber',
                    'extraPatterns' => [
                        'GET list/<listId:\d+>' => 'get-list-subscriber'
                    ],
                    'tokens' => [
                        '{id}' => '<id:\\d+>',
                        '{query}' => '<query:\\w+>'
                    ],
                    'except' => [
                        'index',
                        'create'
                    ],
                    'pluralize' => false
                ],
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'api/account',
                    'pluralize' => false
                ],
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'api/user',
                    'extraPatterns' => [
                        'POST authenticate' => 'authenticate'
                    ],
                    'pluralize' => false
                ],
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'api/campaign',
                    'pluralize' => false
                ],
                'api/subscribe/<token:\w+>' => 'api/web/subscribe',
                'api/callback/<param:\w+>' => 'api/web/callback',
                // 'api/track/open' => 'api/web/track-open',
                // 'api/track/click' => 'api/web/track-click',
                'api/unsubscribe/<param:\w+>' => 'api/web/unsubscribe'
            ]
        ],
        'httpclient' => [
            'class' => 'GuzzleHttp\Client'
        ],
        'db' => require (__DIR__ . '/db_' . YII_ENV . '.php')
    ],`

**Comment by Faryshta** [comment]
can you try?

```php
Url::to([
      "/api/web/unsubscribe", // notice slash at first
      'param' => base64_encode(serialize($params))
]);
```

**Comment by kakalos12** [comment]
it's strange. This trick fixed the problem in the web version. But does not fix the problem in the console.

**Comment by kakalos12** [comment]
Just realize that the pattern that I defined not working with base64 string.

**Comment by Faryshta** [comment]
close the issue then :smile: i see that your reg ex only accepts letters, how about:

`'api/unsubscribe/<param:[\w\d-=]+>' => 'api/web/unsubscribe'`

**Comment by kakalos12** [comment]
Thanks @Faryshta , I just edited the regex ex and it works
