### ISSUE TITLE
file upload max file should accept closure 

### ISSUE THREAD

**Issue by m-wardany** [yiisoft/yii2#14031]
in fileValidator isn't it better to make 'maxFiles' attribute accepts closure beside integer so when we need to make model accept fixed number of files and user cannot upload more than this specific number on insert or update 

 like this :
```
'maxFiles'=> function($model){
    $current_files_nember` = count($this->relatedFiles);
    $max_files = 5 ;
    return $max_files - $current_files_number;
}

```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7
| Operating system | ubuntu 16.4

**Comment by cebe** [comment]
why do you need a closure for that? you can assign the value directly in `rules()`.

**Comment by samdark** [comment]
Right. Since `rules()` isn't static, you could do it.
