### ISSUE TITLE
SQLDataProvider is broken after the fix for #13883

### ISSUE THREAD

**Issue by xloading** [yiisoft/yii2#14046]
### What steps will reproduce the problem?
I have used previously the following actions in my REST controllers without any issues:
```php
public function actionTest($param1, $param2, ...)
    {
        $dataProvider = new SqlDataProvider([
            'sql' => "LONG_AND_COMPLEX_SQL_HERE",
            'params' => [':bind1' => $param1, ':bind2' => $param2, ... ],
        ]);

        return $dataProvider;
    }
```
### What is the expected result?
Fetched data was returned without any problems.
### What do you get instead?
After the following commit: https://github.com/yiisoft/yii2/commit/79f16b149239c0d1314102999a2fc8353ee8cb0b#diff-ae590364dfa0d2f31362d9cc86726fc1
I started getting
```
SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
```
exception, because the introduced totalCount fallback does not consider 'params' at all.
Seems it was coded for too narrow case.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.5.3
| Operating system | Mac OS X

**Comment by SilverFire** [comment]
@samdark @SamMousa

**Comment by SamMousa** [comment]
Hmm, looking into it.

**Comment by SamMousa** [comment]
Okay, the error is obvious now... You have both SQL and params and for count I simply ignore params...

**Comment by SilverFire** [comment]
@SamMousa do you have to submit a PR?

**Comment by SamMousa** [comment]
Yes, I'm working on it now, expect < 20 mins :)

**Comment by SamMousa** [comment]
I'm having an issue with the test case; it does not fail when it should because it uses sqlite....

**Comment by SamMousa** [comment]
@xloading I have created a PR for the fix, as a workaround you could supply the total count manually!

**Comment by xloading** [comment]
Thanks a lot Sam!
I will test it tonight and let you know the results.

**Comment by SilverFire** [comment]
PR #14047 is merged. Thank you
