### ISSUE TITLE
Subclassing \yii\db\Command breaks internal db operations

### ISSUE THREAD

**Issue by crtlib** [yiisoft/yii2#14048]
If you subclass \yii\db\Command and change default fetchMode to \PDO::FETCH_NUM, for example, you get internals of ActiveRecord broken.
With such a subclass I get the following exception upon login:
`yii\base\ErrorException "Undefined index: field" in yiisoft/yii2/db/mysql/Schema.php at line 133`

Of course, it's possible to easy overcome this issue, but I think internal DB operations should use the original Command class. Or it should be stated clearly in the docs that subclassing the Command can lead to such results.

**Comment by samdark** [comment]
Replacing any class with your own implementation may lead to issues despite both classes implement the same interface. Any abstractions tend to leak. Especially at lower levels. I don't think we should state it explicitly in docs because we'd have to add it to all the classes we have.
