### ISSUE TITLE
ActiveRecord one() on big tables causing a lot of memory usage

### ISSUE THREAD

**Issue by awesomeguy3** [yiisoft/yii2#14053]
### What steps will reproduce the problem?
I'm having a huge MySql table with tens of thousands of rows (really big rows too). 
I wanted to take a single row without condition but rather with order by. 
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Duplicated of #13875
