### ISSUE TITLE
Captcha without refresh button

### ISSUE THREAD

**Issue by DanielsonSilva** [yiisoft/yii2#14060]
The version of yii1.1 had a refresh button when using the CCaptcha. When using Captcha in yii2, there's not a option to add a refresh button beside de image to the form have some visual feature that tell the user how to refresh the captcha, the user has to guess that it have to click the image or program to appear a message telling how to refresh the captcha.

If is there some way to add the refresh button in captcha in yii2 framework, please share the knowledge.

Thanks.

**Comment by samdark** [comment]
There currently isn't except adding some HTML and JavaScript yourself.
