### ISSUE TITLE
many ActiveQuery combinations + filtering in GridView

### ISSUE THREAD

**Issue by lowap** [yiisoft/yii2#14063]
### What steps will reproduce the problem?
define many ActiveQueries and try to use them in ModelSearch.
### What is the expected result?
That we dont't have to create as many ModelSearch-es or search methods in ModelSearch, as many combinations of ActiveRecords we want to use. It would be much better if we were able to use ActiveRecords in Controller, but then at the moment filtering in GridView doesn't work if we do so.

```php
public function actionIndex() {
        $searchModel = new AgSearch;
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);
        $dataProvider->query->mq()->norm();...
```

### What do you get instead?
We have to create as many ModelSearch-es or search methods in ModelSearch, as many combinations of ActiveRecords we want to use.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.25
| Operating system | Windows Server 2012 R2 Standard Edition

**Comment by cebe** [comment]
I don't really get what you are asking for. If you have `n` different scenarios you need to write `n` functions to return what you need. These functions can share common parts, what exactly do you want the framework to do here?

**Comment by lowap** [comment]
I'm just asking the question, if this is alright this way, I mean is it planned to behave like this, or am I missing something, or something could be enhanced in yii regarding this.
There is ActiveQuery, what should mean flexibility, shouldn't it? That we can simply change scenarios. But if it's working only if you have to repeat 90% of code 1-2-3-4-5...x then where is your flexibility?
I'm not an expert, but I can imagine, it could work so that you define a separate action only in controller where you want to use a certain combination of AQs - that would be completely alright -, and it would feed the same view, and the same ModelSearch, so that you don't have to duplicate ModelSearch also. Or do I see it false?

**Comment by vuongminh** [comment]
Maybe you need: https://github.com/yii2tech/ar-search

**Comment by lowap** [comment]
I experience that sometimes it's working, sometimes not (when I add more AQs? or when I add them in the wrong order...?). Can be that I'm doing a mistake, however I think I'm doing always the same.

**Comment by samdark** [comment]
@lowap any idea how to reproduce it?

**Comment by lowap** [comment]
Officially, should it be working like this? So with AQ defined in controller action?

**Comment by lynicidn** [comment]
как то приходилось такое делать - решал примерно так
```php
$post = $this->request->post();
$postSearch = new PostSearch();
$postSearch->load($post);
$query = $this->postService->filterQuery($postSearch);
$query->joinWith(['user' => function($q) {
    $userSearch = new UserSearch();
    $userSearch->load($post);
    $this->userService->filterQuery($userSearch, $q);
}]);
```

service method example
```php
public function filterQuery($searchModel, $query = null) {
    if ($query === null) {
        $query = $this->find();
    }
    //...other filter logic
    return $query;
}
```
