### ISSUE TITLE
Table schema not getting refreshed for some Command methods

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#14072]
(Follow-up issue for https://github.com/yiisoft/yii2/issues/3305#issuecomment-296772327)

`yii\db\Schema::refreshTableSchema()` is called after most schema-altering methods in `yii\db\Command` are called, but not the following ones:

- `createTable()`
- `addForeignKey()`
- `dropForeignKey()`
- `addCommentOnColumn()`
- `dropCommentFromColumn()`

Each of these do have an effect on what gets memoized by `getTableSchema()`, so they should be clearing the schema cache.

### What steps will reproduce the problem?

1. call `yii\db\Schema::getTableSchema()` for a table that doesn’t exist
2. create the the table
3. call `yii\db\Schema::getTableSchema()` again for the same table name 

### What is the expected result?

a `yii\db\TableSchema` object is returned

### What do you get instead?

`null` is returned, because it was cached as `null` in step 1, and that cache was not cleared in step 2.

### Additional info

Similar steps to reproduce for the other functions listed above.

PR is forthcoming…

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11, 2.0.12 (dev) @ https://github.com/yiisoft/yii2/commit/bda091bbb24de594adaae0554421cb81598b00f1

**Comment by khalwat** [comment]
Awesome. I just pushed a change to `generator-craftplugin` that does `Craft::$app->db->schema->refresh()` in the `Install.php` migration just before calling the `insertDefaultData()` method.
