### ISSUE TITLE
Different length of a string in js ActiveFrom validation and php StringValidation

### ISSUE THREAD

**Issue by MatthewPattell** [yiisoft/yii2#14086]
### What steps will reproduce the problem?
Create active form with textarea input.
Add string validator to input with max length 20.
Enter in textarea text (19 characters) with line break. 
### What is the expected result?
Js not counting line breaks, but php takes them.
### What do you get instead?
Js validation true and php validation false. If in form exist fileinput, this behavior is bad for validator.

![screenshot_1](https://cloud.githubusercontent.com/assets/10459911/25553914/d3a854e2-2cc8-11e7-9f2f-3a6a2262792e.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/10459911/25553913/d3a74804-2cc8-11e7-8b11-d02b19745631.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/10459911/25553912/d3a6dd7e-2cc8-11e7-9074-c430a1dc7954.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.1
| Operating system | Windows 7

**Comment by TerraSkye** [comment]
I cant find the duplicate, but its been reported already, JS handles newline with 1 charachter while php takes 2

**Comment by samdark** [comment]
It was for Yii 1.1, I guess...
