### ISSUE TITLE
defaults values in hostnames patterns not working

### ISSUE THREAD

**Issue by tonykor** [yiisoft/yii2#14082]
Seems like default values not working with hostnames patterns.

### What steps will reproduce the problem?
having in rules:

```
[
 'pattern'=>'//<language:\w{2}>.'.$params['domain']."/<controller>/<action>",
 'route'=> '<controller>/<action>',
 'defaults'=>['language'=>'en']
],
```

requesting 
`http://domain.com/action/controller` returns 404 
while 
`http://ru.domain.com/action/controller`working good

### What is the expected result?

`http://domain.com/action/controller` with language=en in params
and
HTTP 200 OK response
 
### What do you get instead?

error	yii\web\HttpException:404	exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11?

**Comment by samdark** [comment]
Would you please check it with code from master? Thanks.

**Comment by tonykor** [comment]
@samdark same on master

`2.0.12-dev PHP 5.5.30`

`exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request`

**Comment by samdark** [comment]
@rob006 could you check it? May be connected to the pull request by you merged recently.

**Comment by rob006** [comment]
Right now only slashes are supported as optional params separators, handling dots in hostname looks like can of worms. It will be easier to solve this by creating custom rule or overriding UrlManager, than fighting with optional prams in hostname.
