### ISSUE TITLE
UrlManager::createUrl() cache may degrade performance in some cases

### ISSUE THREAD

**Issue by rob006** [yiisoft/yii2#14094]
Consider this test: https://github.com/rob006/yii2-dev/blob/2f520f339dc616f2875ebf258cbacdd4e9ea597d/tests/framework/web/UrlManagerCreateUrlTest.php#L707

`UrlManager::createUrl()` was called 2 times, but this results 3 `UrlRule::createUrl()` calls. That's because on second URL creation first check is on [cached rule](https://github.com/rob006/yii2-dev/blob/2f520f339dc616f2875ebf258cbacdd4e9ea597d/framework/web/UrlManager.php#L466), and then again on [regular rules array](https://github.com/rob006/yii2-dev/blob/2f520f339dc616f2875ebf258cbacdd4e9ea597d/framework/web/UrlManager.php#L378).

There is no point to check the same rule 2 times, second `UrlRule::createUrl()` call should be skipped.

refs #13350

**Comment by rossoneri** [comment]
@rob006 I tried to solve your problem, you can merge my branch to see .
