### ISSUE TITLE
AssetManager should delete old directories/files when new ones are published

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#14099]
AssetManager should be smart enough to delete the old copies of directories/files when new ones are published.

We were able to pull this off in Craft by overriding `hash()` to return a nested directory name, in the format of `PATH_HASH / MTIME_HASH`, where `PATH` is the path given to the method, and `MTIME` is the latest file modified time of the given path. Then, `publishDirectory()` and `publishFile()` were overridden to clear out any neighboring directories relative to the published directory/file – as it can be assumed that those directories represent the same source dir/file path, but just with different modified times.

Here’s the commit, for reference: https://github.com/craftcms/cms/commit/2293c3cc595a9190b5afdbb675eec0f0b3252968

Note that this depends on a custom [`clearDirectory()`](https://github.com/craftcms/cms/blob/2293c3cc595a9190b5afdbb675eec0f0b3252968/src/helpers/FileHelper.php#L322) method on FileHelper, which Yii is free to copy over, if wanted.

**Comment by SilverFire** [comment]
I don't know, whether it was done on purpose and can not imagine why it could be.

Maybe someone from @yiisoft/core-developers knows

**Comment by mikk150** [comment]
I use [Deployer](https://github.com/deployphp/deployer) to get rid of this issue, new application is deployed all the time so all assets are compiled and copied always and older ones are deleted automatically..

**Comment by brandonkelly** [comment]
Yeah not saying there aren’t deployment solutions to this. In our case, Craft is a self-hosted, designer-friendly CMS, so we can’t expect every single user to solve this problem for themselves. I just figured, since the issue does affect every Yii2 project, I might as well put our solution out there, in case there's interest in fixing it at the core.

**Comment by klimov-paul** [comment]
Outdated assets should be removed manually.
Even if `AssetManager` will use nested directories, removing internal hashed folders, it will be unable to detect AssetBundles, which are out of use.
For example: if you start your project with `yii2-bootstrap` and then removed it switching to custom CSS, folder remained after `BootstrapAsset` will remain at its place.

While updating your project you should clear `assets` folder yourself as it is done at `yii2tech/selfupdate`:
https://github.com/yii2tech/selfupdate/blob/master/SelfUpdateController.php#L407-L417

**Comment by klimov-paul** [comment]
Also note, that extra checks for existing assets folders will lead to performance degradation.

**Comment by mikk150** [comment]
yes, it is pretty bad performance degredation
I would rather have big assets folder than poor performance

**Comment by samdark** [comment]
The reason for not implementing it explained well by @klimov-paul. Cleaning up on each request would be very significant performance degradation.
