### ISSUE TITLE
Using my username and password but login with another account

### ISSUE THREAD

**Issue by farshidbahmani** [yiisoft/yii2#14097]
I'm beginner in using yii2 framework. I have an strange problem.

Sometimes after login with my **username** and **password** in my website, it shows me another account and profile, like I use another username for login.

As I said this occurrence happening sometimes **not always**.

What could be related this problem? (controller, session, cookie or ....)
I think this happens when the `enableAutoLogin` is true

This is `frontend/config/main.php`:

```
return [
    'id' => 'app-frontend',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'frontend\controllers',
.
.
.
    'components' => [
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'enableSession' => true,
            'identityCookie' => [
               'name' => 'frontEndIdentityUser', 
               'path' => '/'
            ]
        ],
        'session' => [
            'name' => 'frontEndIdentity',
            'savePath' => __DIR__ . '/../runtime/sessions',
        ],
    ],
    'params' => $params,
];
```

| Yii version      | 2.0.?

**Comment by rossoneri** [comment]
Is it possible that other programs can change the files under session's savePath?
