### ISSUE TITLE
Rendering huge view's causes memory leaks

### ISSUE THREAD

**Issue by awesomeguy3** [yiisoft/yii2#14102]
I noticed (using Yii2 debugger and memory_get_peak_usage()) that one of my actions take a LOT of memory when rendering, to be specific, around 180MB on the server side. Now, I've been playing around and debugging and trying to see where the memory is leaking, and found out that Controller's render() function triples the memory usage of the view. 

### What steps will reproduce the problem?
Having huge multidimensional array and generating a lot of HTML from it takes a lot of memory, but not as near as when rendering is finished. I've placed memory_get_peak_usage(); die(); at the end of the view file, and it was third of what it was when render was finished (also checked with memory_get_peak_usage() and got 180MB after rendering. Render partial is around 1/2 of render's memory usage. 
Peak memory usage before rendering the view was around 15MB. 

### What is the expected result?
In this case I wouldn't expect more than 100 MB of memory to be used to finish everything.

### What do you get instead?
A huge amount of memory consumed.

### Additional info
Peak memory usage:
- before view ~ 15MB
- at the end of the view file ~ 60MB
- after render ~ 180MB
- browser memory used (mozilla developer toolbar net panel) ~ 5 MB

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.8
| Operating system | Linux CentOs 7

**Comment by rob006** [comment]
Does the use of reference change anything?

```php
$this->render('view', ['data' => &$data]);
```

**Comment by SilverFire** [comment]
Could you provide sample data and view to reproduce the problem?

**Comment by awesomeguy3** [comment]
@rob006 It changes nothing. 

@SilverFire Sorry, but no, it's under NDA so I cannot share it. But as I realise, you could create some big multidimensional array and a view which will go through it and generate a lot of html. It doesn't need to be the amount of memory like I'm seeing, you just need to check the amount of memory before the view, in the view (at the end of it) and after render. 
That's how I noticed it triples the peak memory usage from the end of the view.

**Comment by klimov-paul** [comment]
There are several causes for the memory consumpltion during view rendering:

1) Using output buffering: while rendering Yii use PHP output buffer (e.g. writing PHP echo into memory buffer instead of stdout). Longer the view code increases buffer size.

2) Layout rendering - while applying layout extra output buffering is used to wrap initial render result into layout: at this stage rendered content consumes memory twice: first as `$content` variable, second - inside layout output buffer.

3) Usage of widgets with thier instance references as `ActiveForm` (e.g. constructions like `$form = ActiveForm::begin()`) produces object references to the widget instances, which will be dropped only after view rendering complete.

I can not see any way framework can be improved towards reducing memory consumtion during view rendering.

**Comment by awesomeguy3** [comment]
@klimov-paul I realised that all once I've dug deeper into the code, but I'm just saying that there should be some possible solution to this. 
I know this scenario is rare, but if unnecessary memory usage could be avoided, or freed on time, it would be quite a jump on performance for apps that have hundreds or thousands of users active at a time and considering that even basic views can consume up to 5 MB of memory.

**Comment by klimov-paul** [comment]
It can not be done without loss of functionality.
The only way is using stdout directly during rendering without using output buffer. But this will break several crucial features like HTML header (title, CSS, JS etc) composition, error handling and so on.

I do not consider your use case common enough to be worthy of creation of another full-scale HTML rendering framework. Especially while modern application moving forward to usage of on-page-site JS Frameworkds with REST combination.

As some quick solution you can split your long view into several ones and use `php://temp` or `tmpfile()` to save rendering result and output it inside the controller. But this is all not trivial and require custom adjsutments.

**Comment by SilverFire** [comment]
> Sorry, but no, it's under NDA

We don't ask you to disclosure any sensitive data. Just provide a sketch data structure and view that will case memory leak

**Comment by lubosdz** [comment]
What is your memory limit ? Actually what makes you think it's the Controller which causes your memory exhaustion? Controller should only pass some data into view - so more likely it would be database or other data resource which causes exhaustion. Framework itself uses ~2-3 MB of memory alltogether and the Controller has directly nothing to do with data population - it's the model's responsibility. Without providing some demo script your issue description is pretty vague & hard to trace down.

**Comment by awesomeguy3** [comment]
@lubosdz I've tested all of the code, and memory usage before going into view is around 15MB in this case, at the end of the view ~60MB, and just after render ~180MB.

**Comment by cebe** [comment]
@awesomeguy3 how big is the HTML content that has been rendered?

**Comment by bowpunya** [comment]
i have the same problem, rendering around 170,000 rows of data to table cause memory exhausted, but when i'm not passing the data array through the view it is fine, i'm saying that i have no problem with the query or the controller.

**Comment by lubosdz** [comment]
This issue could be related to specific [output buffering settings/limits](http://php.net/manual/en/outcontrol.configuration.php), hard to track it down without knowing specific environment settings. Perhaps could be simulated by significantly limiting output buffer size since views always buffer the output?
