### ISSUE TITLE
getUserIdsByRole() docs

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#14108]
Not sure if this is a bug or document error.

The docs for [`getUserIdsByRole()`](http://www.yiiframework.com/doc-2.0/yii-rbac-dbmanager.html#getUserIdsByRole()-detail) say the method returns an array of `yii\rbac\Assignment` but it actually just returns an array of user ids.

Should the docs say the return is an array or should the method return an array of `yii\rbac\Assignment`?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2

**Comment by SilverFire** [comment]
Seems to be a typo in docs.

@samdark should we update docs or change code? :)

**Comment by samdark** [comment]
It's docs mistake. Method name states it should return IDs.
