### ISSUE TITLE
Setting pageSize  in ActiveDataProvider to 0 gives exact 1 result in grid instead of all found in query

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft/yii2#14106]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.23
| Operating system | Kubuntu 14.04
I am using Apache server and  **mongodb** 3.2.12

As per [this documentation](http://www.yiiframework.com/doc-2.0/yii-data-pagination.html#$pageSize-detail) setting pageSize to 0 gives all result/document from collection/table

### What steps will reproduce the problem?
model file
```
class Somemodel extends \yii\mongodb\ActiveRecord 
{
...
```

search model file

```
class SomemodelSearch extends Somemodel
{
...
public function search($params)
    {
        $query = Somemodel::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort'=> ['defaultOrder' => ['_id'=>SORT_DESC]],
            'pagination' => ['pageSize' => 0]
        ]);
        ...

```
### What is the expected result?
We should get all the result/documents of the collection/table

### What do you get instead?
Only one result is shown in grid i.e. dataProvider gives only 1 result/document instead of all in the collection/table

### Additional info
However setting pagination to false in search method in SomemodelSearch.php gives expected result i.e. all result/document from collection/table

**Comment by SamMousa** [comment]
What do you get if you add this to your search, after constructing the dataprovider:
````
var_dump($dataProvider->getPagination()->getLimit());
die();
````

?

**Comment by SOHELAHMED7** [comment]
> What do you get if you add this to your search, after constructing the dataprovider:
> 
> var_dump($dataProvider->getPagination()->getLimit());
> die();
> ?

`'pageSize' => 10`  int(10)
`'pageSize' => 11`  int(11)
`'pageSize' => 0`  int(-1)
`'pageSize' => -1`  int(-1)
`'pageSize' => -2`  int(-1)

**Comment by SOHELAHMED7** [comment]
**More Info**

Consider a newly (fresh) generated CRUD of a collection (no files modified or no changes in code made)
It has 203 documents
In search model class (SomemodelSearch.php) -> in method `search()`
Nothing is searched so all 203 documents must be shown in **Grid**

```
public function search($params)
{
    // $query ...

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'sort'=> ['defaultOrder' => ['_id'=>SORT_DESC]],
        'pagination' => ['pageSize' => 0]
    ]);

    ...
```

Case 1
When you set `pageSize` to 10 it shows 10 rows per page (Summary -> Showing 1-10 of 203 items.) Pager widget is shown

Case 2
When you set `pageSize` to 11 it shows 11 rows per page (Summary -> Showing 1-11 of 203 items.) Pager widget is shown

Case 3
When you set `pageSize` to 0 it shows 1 rows per page (Summary -> Showing 1-1 of 203 items.) Pager widget is **NOT** shown <--  (Answer to **When does the issue occur?**)

As per [this document](http://www.yiiframework.com/doc-2.0/yii-data-pagination.html#$pageSize-detail) when pageSize is set 0 all records/rows must be shown in grid but it shows only 1 without the pager widget <-- (Answer to **What do you see**)

It must show all (203) records in grid in one single page  <-- (Answer to **What was the expected result?**)


However setting pagination as false
```
public function search($params)
{
    // $query ...

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'sort'=> ['defaultOrder' => ['_id'=>SORT_DESC]],
        'pagination' => false
    ]);

    ...
```

gives expected result (this works fine)
it shows all (203) results in one single page

**Comment by SOHELAHMED7** [comment]
I have tried to reproduce this issue in RDBMS Mysql 

All things work fine here

setting `pageSize`  to `0` show all records of  a table in grid (shows summary  as     Showing 1-203 of 203 items.)


setting `'pagination'`  to `false` show all records of  a table in grid (shows summary  as     Total 2 items.)
