### ISSUE TITLE
Suggestion for yii\validators\EachValidator: option which allows validation of non array values

### ISSUE THREAD

**Issue by ReNoM** [yiisoft/yii2#14115]
Add an option which also allows to perform validation of non array values, and considers their such as array with one element. For example, validation rule for some field of search model:
`[['some_field'], 'each', 'rule' => ['integer']]`

Examples of query params:
1. some_field[]=1000,some_field[]=1001 // validation passed
2. some_field[]=1000 // validation passed
3. some_field[]=test // validation not passed, because it is not an integer value
4. some_field=1000 // validation not passed, because value is not inside array
5. some_field=test // validation not passed, because value is not inside array

My offer is to add option, with which item 4 of list will be also passed. Example with this option:
1. some_field[]=1000,some_field[]=1001 // validation passed
2. some_field[]=1000 // validation passed
3. some_field[]=test // validation not passed, because it is not an integer value
4. some_field=1000 // validation passed
5. some_field=test // validation not passed, because it is not an integer value

It will be useful for example for REST services. I think it will add more flexibility in usage.

**Comment by klimov-paul** [comment]
I can see no sense in such change. The goal of `EachValidator` is checking value to be array of something explicilty. If attribute is not an array - normal validator should be used. If value caould be either scalar or array - you should create your own validator for it.

**Comment by ReNoM** [comment]
But if I will create normal validator, it will deny array values. I mean situation when both construction should works:
some_field[]=1000,some_field[]=1001
some_field=1000

Currently I can make it works only with custom validator.

**Comment by ReNoM** [comment]
But if it will be implemented as option, `EachValidator` by default will be work same as now.

**Comment by klimov-paul** [comment]
Why particular attribute can be either a scalar or array? It does not seem right.
Sounds like 'attribute can be an email or date'.

**Comment by rob006** [comment]
You can use `filter` validator to convert scalar to array before `each` validator.

**Comment by ReNoM** [comment]
@klimov-paul Only for usage convenience. As I mentioned above, for example, in REST api.
@rob006 thanks, `filter` validator with option `skipOnArray` really resolves described goal of suggestion. Example:
`[['some_field'], 'filter', 'skipOnArray' => true, 'filter' => function ($value) { return [$value]; } ]`
it should be described above than `EachValidator` rule.
