### ISSUE TITLE
Invalid timezone when using `asDatetime` formatter

### ISSUE THREAD

**Issue by maximal** [yiisoft/yii2#14125]
I have the following environment:
 * PHP-FPM php.ini
   ```
   date.timezone = "Europe/Moscow"
   ```
 * Yii2 web config:
   ```
   // $config = [
   // 'components' => [
   // ...
   'formatter' => [
       'defaultTimeZone' => 'Europe/Moscow',
   ],
   ```
 * Server (Debian 8.8 x64) default timezone is also `Europe/Moscow` (+0300):
   ```
   % date -R        
   Mon, 08 May 2017 16:07:33 +0300
   ```

When I try to print formatted date and time using Yii2 formatter, I get an invalid 1 hour offset.
Even though, when I use the formatting from inside of `DateTime` class, it works just fine.

Code:
```php
<?= '2017-05-07 19:10:26' ?>
<?= (new \DateTime('2017-05-07 19:10:26'))->format('c') ?>
<?= Yii::$app->formatter->asDatetime('2017-05-07 19:10:26', 'php:c') ?>
```

Output:
```
2017-05-07 19:10:26
2017-05-07T19:10:26+03:00
2017-05-07T20:10:26+04:00
```

**Comment by ptz-nerf** [comment]
Did you try to update the intl\tz data?

**Comment by cebe** [comment]
as @ptz-nerf says, make sure your environment is aware of Russia's latest timezone changes. If it still happens, I am happy to reopen it.

**Comment by maximal** [comment]
The error still happens.

`intl`:
![image](https://user-images.githubusercontent.com/980679/27761073-2be8c602-5e5e-11e7-9565-6eb1900fe5e6.png)

`date`:
![image](https://user-images.githubusercontent.com/980679/27761091-40cabe18-5e5e-11e7-9f43-045d8f4c8380.png)

**Comment by bscheshirwork** [comment]
What about 
```php
    <?= '2017-05-07 19:10:26' ?><br />
    <?= (new \DateTime('2017-05-07 19:10:26', new \DateTimeZone(Yii::$app->formatter->defaultTimeZone)))->format('c') ?><br />
    <?= Yii::$app->formatter->asDatetime('2017-05-07 19:10:26', 'php:c') ?><br />

```
?

**Comment by aix27249** [comment]
I have this bug too, and I'm having it for years. Currently experiencing it with 2.0.12.

Apparently this bug DEPENDS on some server packages or configuration, for example, I have such invalid offset on Centos 7 (with PHP 7.1.7), but doesn't have it on Arch Linux (PHP 7.1.7 too).

**Comment by maximal** [comment]
Yes, I also have been experiencing this bug for almost a year or more.

**Comment by maximal** [comment]
@bscheshirwork, here:

```
2017-05-07 19:10:26
2017-05-07T19:10:26+04:00
2017-05-07T18:10:26+03:00
```

**Comment by bscheshirwork** [comment]
@maximal reverted at case of your first comment? %)
>Output:
>
>2017-05-07 19:10:26
>2017-05-07T19:10:26+03:00
>2017-05-07T20:10:26+04:00

>
>2017-05-07 19:10:26
>2017-05-07T19:10:26+04:00
>2017-05-07T18:10:26+03:00

So... Can tell about both of this case in one time, pls?

```php
    <?= '2017-05-07 19:10:26' ?><br />
    <?= (new \DateTime('2017-05-07 19:10:26'))->format('c') ?>
    <?= (new \DateTime('2017-05-07 19:10:26', new \DateTimeZone(Yii::$app->formatter->defaultTimeZone)))->format('c') ?><br />
    <?= Yii::$app->formatter->asDatetime('2017-05-07 19:10:26', 'php:c') ?><br />
```

**Comment by aix27249** [comment]
@bscheshirwork ,

**Arch Linux (everything is OK here):**
2017-05-07 19:10:26
2017-05-07T19:10:26+03:00
2017-05-07T19:10:26+00:00
2017-05-07T22:10:26+03:00

**CentOS (not OK):**
2017-05-07 19:10:26
2017-05-07T19:10:26+03:00
2017-05-07T19:10:26+00:00
2017-05-07T23:10:26

**Comment by ptz-nerf** [comment]
Did you try to update intl to last pecl 3.0? 

OS | CentOS
version | PECL-3.0.0
ICU version | 58.2
ICU Data version | 58.2
Everything is ok.

На правах рекламы https://github.com/yiisoft/yii2/issues/10982

**Comment by maximal** [comment]
:)

**Comment by SilverFire** [comment]
Seems to be environment-related. Can not reproduce on PHP 7.1 ICU 59

**Comment by fidi87** [comment]
I had the same. It seems formatter adds its timezone to default timezone of the server. That is why I added to config (default time zone was unchanged):
```
'components' => [
       ...
	'formatter' => [
            'timeZone' => 'UTC',
       ],
      ...
    ],
```
At last it solved my problem to show correct date formatted
