### ISSUE TITLE
Redundant Html Id in Active Field

### ISSUE THREAD

**Issue by nicovicz** [yiisoft/yii2#14127]
if you see the source code, there is a redundant code

https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L779-L780

it should be 
```
$inputID = $this->getInputId();
$options['id'] = $inputID;
```

**Comment by Thoulah** [comment]
I don't think it's redundant, see https://github.com/yiisoft/yii2/commit/6745bdb65e1f0a8a91c94348f34b7899e25e2ba9#diff-afe28192283fbfadaf6145620191c339R728
