### ISSUE TITLE
Проблема с фильтрацией. Yii 2.0.11.2

### ISSUE THREAD

**Issue by jurazubach** [yiisoft/yii2#14128]
Добрый день, установлена версия "advanced"
Проблема заключается с фильтрацией таблиц по всему проекту.

Контроллер : 
```
$searchIpFilters = new CrmIpFiltersSearch();
$dataProvider = $searchIpFilters->search(Yii::$app->request->queryParams);

return $this->render('index', [
        'dataProvider' => $dataProvider,
        'searchIpFilters' => $searchIpFilters
]);
```

Модель стандартная :
```
метод search()
$query = CrmIpFilters::find();
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        $this->load($params);

        if (!$this->validate()) {
            return $dataProvider;
        }
        $query->orderBy('created_at DESC');

        $query->andFilterWhere(['like', 'ip_address', $this->ip_address])
            ->andFilterWhere(['like', 'created_at', $this->created_at]);

        return $dataProvider;
```

```
public function rules()
    {
        return [
            [['ip_address'], 'string', 'max' => 50],
            [['ip_address', 'created_at'], 'safe'],
        ];
    }
```

Вьюха : 
```
<?php Pjax::begin(['id' => 'ip-filters', 'enablePushState'=>false]); ?>
                <?php echo GridView::widget([
                    'id' => 'ip-filters',
                    'filterModel' => $searchIpFilters,
                    'dataProvider' => $dataProvider,
                    'tableOptions' => ['class'=>'table table-bordered items'],
                    'summary' => '',
                    'columns' => [
                        'created_at',
                        'ip_address',
                    ],
                ]); ?>
                <?php Pjax::end(); ?>

```
Все скрипты подключены, но всеравно не работает фильтрация
Единственный вариант заставить фильтроватся : 
`$.pjax.reload({container:'#ip-filters', push:false});`
после выполнения этого кода, таблица начинает полностью нормально функционировать.
До вызова ее, ни обычная фильтрация через GET запросы, ни ajax.
Вводишь данные в input, нажимаешь Enter, и ничего не происходит, абсолютно все без ошибок.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.15
| Operating system | macOS 10.11.6

**Comment by samdark** [comment]
В какой версии последний раз работало?

**Comment by jurazubach** [comment]
Нивкакой, проект с Yii 1 на Yii2 переносится, там серч моделей небыло ведь, даже на чистом бутстрапе после инициализации проекта не работало. Такое ощущение что оно не инициализируется гдето, а после pjax.reload, инициализирует таблицу и все работает

**Comment by MysteryDragon** [comment]
```
<?php Pjax::begin(['id' => 'ip-filters', 'enablePushState'=>false]); ?>
                <?php echo GridView::widget([
                    'id' => 'ip-filters',
```
Смущает то, что идентификаторы одинаковые. Возможно, это и сбивает скрипты.
У меня на рабочем проекта с Yii 2.0.11.2 эта связка работает без огрех.

**Comment by samdark** [comment]
Слишком мало информации, чтобы воспроизвести. Давайте пока на форум, а потом обратно, как выясним, в чём именно проблема.
