### ISSUE TITLE
DI + variadic arguments

### ISSUE THREAD

**Issue by rodion-k** [yiisoft/yii2#14126]
### What steps will reproduce the problem?
1. Add class with variadic dependencies

```
class EventDispatcher extends \Symfony\Component\EventDispatcher\EventDispatcher
{
    public function __construct(EventSubscriberInterface ...$subscribers)
    {
        foreach ($subscribers as $subscriber) {
            $this->addSubscriber($subscriber);
        }
    }
}
```
2. Try to get dispatcher without subscribers

`Yii::$container->get(EventDispatcher::class)`

### What is the expected result?
No arguments passed to constructor
### What do you get instead?
Not instantiable – yii\di\NotInstantiableException

Can not instantiate Symfony\Component\EventDispatcher\EventSubscriberInterface.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11-dev
| PHP version      |  7.0.15

**Comment by dynasource** [comment]
@samdark, isnt this the issue that I had a weeks ago, in which constructor parameter typehints are responsible for (magical) instantiation?

Perhabs because of this code https://github.com/yiisoft/yii2/blob/master/framework/di/Container.php#L432

**Comment by SamMousa** [comment]
I've created a PR with tests  https://github.com/yiisoft/yii2/pull/14190 (ignore name of the branch..)

**Comment by SamMousa** [comment]
This is a complicated scenario:
1. A variadic parameter is always the last one, it is always optional.
2. It supports type hints.
3. We support passing in a params array.

Some design choices must be made:
1. We will never instantiate anything when it is variadic? (Yes)
2. Will we consume passed params? (Yes)
3. Will we do any type checking (No)

Between braces my opinions. I think when we see a variadic parameter we can just add all remaining passed in parameters to the argument list and forward the call.
If there's wrong types stuff will break, but that's fine.

**Comment by SamMousa** [comment]
I've implemented the fix.
