### ISSUE TITLE
Html::errorSummary() doesn't recognise the encode flag

### ISSUE THREAD

**Issue by therendstudio** [yiisoft/yii2#14122]
### What steps will reproduce the problem?

1. Add model error with html markup
2. Call Html::errorSummary($mode,['encode'=>true])

### What is the expected result?
The markup to be displayed unencoded
### What do you get instead?
The markup is being encoded and the encode flag is not recognized

### Additional info
While debugging I found out that the 
`1187:        $encode = ArrayHelper::remove($options, 'encode', true);`
line in BaseHtml.php returns the string "false" instead of the bool value false.
The problem is resolved by converting the return value to int:
`1187:        $encode = (int)ArrayHelper::remove($options, 'encode', true);`
* Perhaps the ArrayHelper should be modified to not return string values when they are given as another type

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.28
| Operating system | Windows 7

**Comment by therendstudio** [comment]
Similarly the **ActiveForm::encodeErrorSummary** cannot switch off encoding

**Comment by samdark** [comment]
It's covered by a test and it works as expected: https://github.com/yiisoft/yii2/blob/master/tests/framework/helpers/HtmlTest.php#L1162
