### ISSUE TITLE
Multiple validateAttribute() calls when scenarios() returns duplicate attributes

### ISSUE THREAD

**Issue by krukru** [yiisoft/yii2#14134]
Consider the following snippet
```php
    // some model class
    public function scenarios()
    {
        return [
            Model::SCENARIO_DEFAULT => [
                'foo',
                'foo',
            ],
        ];
    }

    public function rules()
    {
        return [
            ['foo', 'required'],
            ['foo', 'customFunction'],
            ['foo', 'filter', 'filter' => 'boolval'],
        ];
    }
```

Then when performing validation, all of the validation rules will be triggered twice, since the same attribute has been returned twice from ```scenarios()```. This does not have to be the default scenario, it could be your custom defined scenario.

Of course this is an obvious client mistake, you should not return foo twice, but when you have a more complex case, for example when merging with ```parent::scenarios()```, you could end up with the same mistake. 

I think that the framework should simply ignore attributes that have already been validated. If some attribute passed a validator once, it should obviously pass it twice as well and the second validation is not needed. Other then the minor performance waste, there is no real issue when the validator is idempotent.
However filters, custom functions and probably other things need not be idempotent, so calling them multiple times might produce an unwanted result.

One example is if you have a filter that converts a unix timestamp to a datetime string.

**Comment by bizley** [comment]
This is the case indeed.

While this can be fixed in several places with simple `array_unique` I think the best place for this is [Model::activeAttributes()](https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L776) because both [Model::validate()](https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L337) and [Validator::validateAttributes()](https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L247) should take duplicated attribute names as arguments if set directly and process them as many times as developer wants.

I can prepare PR.

**Comment by krukru** [comment]
@bizley I agree fully, but could you let me have this one? :)

**Comment by bizley** [comment]
Sure thing.

**Comment by dynasource** [comment]
This usecase doesnt feel right. This problem should solved at the source instead of monkey patching afterwards in the core.

**Comment by bizley** [comment]
This is the first place where you can correct the array (the `scenarios()` method can be overriden so fixing this in parent is useless). The only other options are:
- introduce new method (or any other process) that will fix the list (overkill IMHO),
- teach developers not to duplicate attributes in `scenarios()` :trollface:

**Comment by dynasource** [comment]
isnt it quite obvious not to duplicate attributes in arrays, like in every array you define?

**Comment by bizley** [comment]
When defining array directly - yes. But when merging array with parent's version it's not.

**Comment by dynasource** [comment]
the duplication starts at the moment of the merge, so I would expect the 'repair' logic to happen over there.

**Comment by bizley** [comment]
I'm not insisting on correcting this in core but it's such a small addition that can fix potential issue and save someone's time.

    class Parent extends Model
    {
        public function scenarios()
        {
            return [
                'test' => ['a', 'b'],
            ];
        }
    }

    class Child extends Parent
    {
        public function scenarios()
        {
            return [
                'test' => array_merge(parent::scenarios()['test'], ['b', 'c']),
            ];
        }
    }

    $child = new Child();
    echo $child->scenarios()['scenario']; // shows ['a', 'b', 'b', 'c']

**Comment by krukru** [comment]
Forcing the client to make the array unique at the merge level in `scenarios()` is in my opinion boilerplate that could be avoided
