### ISSUE TITLE
BC cloning DB does not keep DB's state with SQLite

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#14131]
As discussed with @cebe, this topic is opened to address an issue when cloing a Sqlite DB and expecting it to have the original state. Somehow this is broken and I drilled it down to commit: 
https://github.com/cebe/yii2/commit/5ed6910e1cca13c3fea677a564dc13a36533f50c

and in specific because of:
```php
$this->pdo = null;
```

Hiding this works and enables me to clone & reuse data of a SqlLite database for testing purposes

**Comment by cebe** [comment]
I think we can make an exception for sqlite in-memory dbs. Sent a PR.
