### ISSUE TITLE
Incorrect datetime via formatter (php 7.1)

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#14155]
```php
//timeZone is default
var_dump(
   date('Y-m-d H:i:s'), 
   \Yii::$app->formatter->asDatetime(time(), 'php:Y-m-d H:i:s')
); exit;
//_.php:9:string '2017-05-13 02:33:18' (length=19)
//_.php:9:string '2017-05-13 03:33:18' (length=19) 
```
exru@hp:/etc/php/7.1/fpm$ php -v 
PHP 7.1.5-1+0~20170511141858.23+jessie~1.gbpe4bc94 (cli) (built: May 11 2017 16:19:47) ( NTS ) Copyright (c) 1997-2017 The PHP Group Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies     with Zend OPcache v7.1.5-1+0~20170511141858.23+jessie~1.gbpe4bc94, Copyright (c) 1999-2017, by Zend Technologies     with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

**Comment by bscheshirwork** [comment]
more info http://php.net/ChangeLog-7.php#7.1.5

```
Date:

    Fixed bug #74404 (Wrong reflection on DateTimeZone::getTransitions).
    Fixed bug #74080 (add constant for RFC7231 format datetime).
```
```
Intl:

    Fixed bug #65683 (Intl does not support DateTimeImmutable).
    Fixed bug #74298 (IntlDateFormatter->format() doesn't return microseconds/fractions).
```

**Comment by mklemarczyk** [comment]
I also got problems with date and time, it shows wrong time. Stored in MySQL in UTC, and suppose to be shown in +2, but it does not show correct time.

**Comment by SilverFire** [comment]
/home/silverfire/prj/www/basic.yii2.local/controllers/SiteController.php:45:string '2017-10-13 07:52:59' (length=19)
/home/silverfire/prj/www/basic.yii2.local/controllers/SiteController.php:45:string '2017-10-13 07:52:59' (length=19)

**Comment by cebe** [comment]
the issue can occur when php timezone db is not up to date with the one used by intl.
