### ISSUE TITLE
Delete Link with Confirm Dialog / Post Request fails if yii.js is not loaded at click

### ISSUE THREAD

**Issue by kasoft** [yiisoft/yii2#14153]
### What steps will reproduce the problem?
Create a view with a Delete Button like

<?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>

### What is the expected result?
As it's a delete operation, the confirm dialog should always appear. Also it should be always a POST Request.

### What do you get instead?
If the Html part of the delete Button is loaded, but the yii.js is not initialized (maybe a slow connection or whatever), you will get an error message (This Method is only allowed with POST) without the Confirm Dialog. If you do a lot of delete operations fast, this occures some times. This should not be possible. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 
| Operating system |

**Comment by cebe** [comment]
This depends on how you organize tha javascript on your site. See "Option 3" of http://stackoverflow.com/a/3811546/1106908
I do not think there is a way to fix this from yii side.
