### ISSUE TITLE
Inconsistency in yii\web\Session setFlash and addFlash

### ISSUE THREAD

**Issue by vbazovic** [yiisoft/yii2#14158]
### What steps will reproduce the problem?
Different behavior on yii\web\Session for setFlash() & andFlash() when empty flashes.
In setFlash:
` $_SESSION[$key] = $value;`
In addFlash there is surplus [ ]:
```
if (empty($_SESSION[$key])) {
            $_SESSION[$key] = [$value];
 }
```
### What is the expected result?
Should behave the same!

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      |  php 5.6
| Operating system | Linux/GNU Debian

**Comment by cebe** [comment]
andFlash supports multiple flash messages for the same key, setFlash only supports one message per key.

**Comment by samdark** [comment]
I think it's there already:

> If there are existing flash messages with the same key, the new one will be appended to the existing message array.
