### ISSUE TITLE
Incorrect Value When Using loadDefaultValues with DATETIME Field

### ISSUE THREAD

**Issue by Knight-Yoshi** [yiisoft/yii2#14157]
I have a MySQL table that looks like this
<img width="1059" alt="screenshot 2017-05-14 18 06 34" src="https://cloud.githubusercontent.com/assets/6134576/26038185/60f0da46-38d0-11e7-9edc-d91dbef5f4f6.png">

When saving after calling the AR's `loadDefaultValue()` method it a DB exception is thrown.

```
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'CURRENT_TIMESTAMP' for column 'created_on' at row 1
The SQL being executed was: INSERT INTO `image_set` (`created_on`, `last_updated_on`, `total`, `title`, `user_id`, `slug`) VALUES ('CURRENT_TIMESTAMP', CURRENT_TIMESTAMP, 1, 'Title', 1, 'title')
```

In this case I can avoid loading default values. However, I have other tables that will require loading the default values that also have DATETIME fields.

**Comment by rossoneri** [comment]
@Knight-Yoshi It seems the default value of `created_on` is  a string value 'CURRENT_TIMESTAMP', is it true?
