### ISSUE TITLE
ActiveField->enableAjaxValidation is always ignored and ActiveForm->enableAjaxValidation is mandatory

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii2#14156]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.5
| Operating system | Ubuntu server 16.04

```
<?php $form = ActiveForm::begin([
            'id'=>'model-form',
            'enableAjaxValidation'=>false,
        ]); ?>
```
`<?= $form->field($model, 'attr1')->textInput(['enableAjaxValidation' => true]) ?>`
`<?= $form->field($model, 'attr2')->textInput() ?>`

Do not send ajax validation request for NONE of the fields

And this is the jquery code generated on the footer:
```

jQuery('#model-form').yiiActiveForm([
{"id":"model-attr1","name":"attr1","container":".field-model-attr1","input":"#model-attr1",, ......... 

{"id":"model-attr2","name":"attr2","container":".field-model-attr2","input":"#model-attr2", ......... 
```

(Note that "enableAjaxValidation" is not on the json string.
- - - - - - - - -
```
<?php $form = ActiveForm::begin([
            'id'=>'model-form',
            'enableAjaxValidation'=>true,
        ]); ?>
```
`<?= $form->field($model, 'attr1')->textInput(['enableAjaxValidation' => false]) ?>`
`<?= $form->field($model, 'attr2')->textInput() ?>`

Do SEND ajax validation request for ALL of the fields.

And this is the jquery code generated on the footer:

```
jQuery('#model-form').yiiActiveForm([
{"id":"model-attr1","name":"attr1","container":".field-model-attr1","input":"#model-attr1","enableAjaxValidation":true, ......... 

{"id":"model-attr2","name":"attr2","container":".field-model-attr2","input":"#model-attr2","enableAjaxValidation":true, ......... 
```

(Note that "enableAjaxValidation" is in all json strings)
- - - - - - - - -
So, ActiveForm::$enableAjaxValidation is the mandatory over ActiveField::$enableAjaxValidation

**Comment by InsaneSkull** [comment]
`enableAjaxValidation` is not an textInput attribute. It's an ActiveField option.
So, `<?= $form->field($model, 'attr1', ['enableAjaxValidation' => false])->textInput() ?>`
[http://www.yiiframework.com/doc-2.0/yii-widgets-activeform.html#field()-detail](http://www.yiiframework.com/doc-2.0/yii-widgets-activeform.html#field()-detail)
[http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html)

**Comment by nacesprin** [comment]
You are right. I'm so silly ¬.¬
