### ISSUE TITLE
error on exists validator after d811f1e

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii2#14150]
Hi i have just updated to the latest version d811f1e
and now my exists validator fails with an sql error.

I have this rule in my Submission Class.

     [['submission_call_id'], 'exist', 'skipOnError' => true, 'targetClass' => SubmissionCall::className(), 'targetAttribute' => ['submission_call_id' => 'id']],

The SubmissionCall Class have this tablename

    public static function tableName()
    {
	return '{{%submission_call}}';
    }

The generated sql is 

    SELECT EXISTS(SELECT * FROM `submission_call` WHERE (`0`.`id`='12'))`

Of course this sql is wrong, but why?
Are there still some changes to the exists validator missing?
Is this a newly introduced bug due to the latest change?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | d811f1e
| PHP version      | 5.6
| Operating system | Windows

**Comment by cebe** [comment]
> Is this a newly introduced bug due to the latest change?

quite sure it is.

**Comment by bscheshirwork** [comment]
rules like this
```php
            [['unitId'], 'exist',
                'skipOnError' => true,
                'targetClass' => DurationUnit::className(),
                'targetAttribute' => ['unitId' => DurationUnit::tableName() . '.id'],
                'filter' => function (DurationUnitQuery $query) {
                    $query->active();
                }
            ],
```
produced error now :rage: :anger: :fire: :fire_engine: 
```SQL
SELECT EXISTS(SELECT * FROM `duration_unit` WHERE (`duration_unit`.[[`duration_unit`.id]]=1) AND (`duration_unit`.`stateOfFlags`=1))'
```
:smile_cat:

**Comment by bscheshirwork** [comment]
Can create "error on exists validator after c6ab3f8" :1st_place_medal:

**Comment by samdark** [comment]
Ohh... the case for manual prefixing wasn't taken into account :(

**Comment by bscheshirwork** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/validators/ExistValidator.php#L226
https://github.com/yiisoft/yii2/blob/master/framework/validators/UniqueValidator.php#L179
https://github.com/yiisoft/yii2/blob/master/framework/validators/UniqueValidator.php#L299

I think need function named like `applyPrefix($column, $prefix = null)` for this case

**Comment by bscheshirwork** [comment]
#14160

**Comment by bscheshirwork** [comment]
#14161

**Comment by bscheshirwork** [comment]
So... Ordinary unique validator has some error without alias :smile_cat: 
```
            [['unitId', 'value'], 'unique', 'targetAttribute' => ['unitId', 'value']],
```
```
            [['unitId', 'value'], 'unique', 'targetAttribute' => ['unitId', 'value']],
```

**Comment by samdark** [comment]
@Bhoft could you try now?

**Comment by Bhoft** [comment]
Works.  The select for the exists validation is now correct:


    SELECT EXISTS(SELECT * FROM `submission_call` WHERE (`submission_call`.`id`=12))
