### ISSUE TITLE
Incorrect spellout via formatter (php 7.1) 

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#14164]
```php
//lang  = RU
\Yii::$app->formatter->asSpellout(32000);
//тридцать две тысяч
//должно быть "тридцать две тысячи"
```

**Comment by exru** [comment]
PHP: 7.1.5-1+0~20170511141858.23+jessie~1.gbpe4bc94 ICU: 52.1 ICU Data: 52.1

**Comment by cebe** [comment]
> //lang  = RU

can you clarify what exactly you set as locale?

**Comment by cebe** [comment]
Same issue here with locale `ru_RU`, but I am very sure it is not a Yii issue but a bug in ICU/intl or CLDR data.
please report to either:

- http://site.icu-project.org/bugs
- or http://cldr.unicode.org/index/bug-reports
