### ISSUE TITLE
[rest] Configurable Extra Patterns in main.php broke url parameters

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#14167]
If you configure default expand #13864, it does not read url expand param anymore.

### What steps will reproduce the problem?
Configure main.php with rule
```php
				[
					'class' => 'yii\rest\UrlRule',
					'controller' => ['participant'],
					'ruleConfig' => [
						'class' => 'yii\web\UrlRule',
						'defaults' => [
							'expand' => 'user',
						]
					],
				],
```
And try go to the url: participants?expand=user,detail

### What is the expected result?
User and detail are shown as extra field.
Without param, user is only shown as extra field.

### What do you get instead?
User is shown as extra field.
Without param, the same, user is shown as extra field.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      |  5.6.2
| Operating system | Window 10

**Comment by Faryshta** [comment]
what does debug says? take an screenshot of the section 'Request' please

**Comment by cebe** [comment]
closing as no feedback is provided for a long time.
