### ISSUE TITLE
ArrayHelper::merge() gives duplicated for integer key values

### ISSUE THREAD

**Issue by odai-alali** [yiisoft/yii2#14175]
> If each array has an element with the same string key value, the latter will overwrite the former (different from array_merge_recursive).

however, merging this to array twice 
["pluginOptions" => ["allowedFileTypes" => ["image"]]]
will give
["pluginOptions" => ["allowedFileTypes" => [0 => "image", 1 => "image"]]]

Shouldn't these values overriden? It would be usefull in merging config arrays for widgets

**Comment by klimov-paul** [comment]
This is expected behavior.

**Comment by odai-alali** [comment]
Yes i know that it works for string key, i qouted the documentation that says that

I am suggesting to make it possible to override duplicate values too, we are using this method extensivly with merging config arrays, having this ability in this method would be helpful

**Comment by rob006** [comment]
http://www.yiiframework.com/doc-2.0/yii-helpers-replacearrayvalue.html
