### ISSUE TITLE
Remove HHVM support?

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#14178]
Are there project actually running on HHVM? Considering performance of PHP 7 it doesn't really make sense to support it so I'd drop it in 2.1.

**Comment by yyxx9988** [comment]
I agree. HHVM is not a standard PHP interpreter and is not used extensively, it is not necessary to continue to support it. The YII2 team should speed up the development of new features, for example, providing mysql5.7 JSON format support for ActiveRecord.

**Comment by takobell** [comment]
FWIW, we've tracked several server stats for [Craft](https://craftcms.com) installs for the last few years and of the roughly 50,000 records since we started doing this, 28 of them are on a HHVM PHP version.

A yearly breakdown:

2017: 2
2016: 16
2015: 10

It's already a very small % and it looks like PHP 7 has killed it even more.

**Comment by cebe** [comment]
Is there any significant effort needed to support HHVM? I do not remember big issues recently.

**Comment by bizley** [comment]
Not significant I guess but there will be no need for something like [that](https://github.com/yiisoft/yii2/blob/2.0.11.2/tests/framework/console/controllers/PHPMessageControllerTest.php#L81-L85).

**Comment by samdark** [comment]
I see two pros in dropping it:

- No code like @bizley pointed to. There's more in the error handler.
- Faster Travis builds.

**Comment by Faryshta** [comment]
https://www.reddit.com/r/HHVM/ the hhvm subreddit is also dead. seems like it died around php7.0 release

the official blog is also dead and the latest release which was this month is only catching up to php 5.6 features http://hhvm.com/blog/2017/04/13/hhvm-3-19.html

**Comment by sergeymakinen** [comment]
I also agree that HHVM is not actual anymore, thanks to PHP 7.

**Comment by cebe** [comment]
Running a little poll here: https://twitter.com/cebe_cc/status/866398230665453568
please answer and share!

**Comment by samdark** [comment]
https://twitter.com/petrabarus/status/865361789466181632 @petrabarus

**Comment by petrabarus** [comment]
I really don't mind if you dropped the HHVM support for 2.1. We already have plan to migrate to PHP7 next quarter. Maybe thinking of migrating from 2.0 to 2.1. 
Not that I don't like HHVM, though. But I met some hassles of handling some plugins or extensions that were not intended for HHVM.

**Comment by samdark** [comment]
http://symfony.com/blog/symfony-4-end-of-hhvm-support

**Comment by cebe** [comment]
Interesting to see that they come to the same discussion also with a twitter poll on nearly the same time :)

**Comment by samdark** [comment]
I've participated in it ;)

**Comment by klimov-paul** [comment]
Relates: #13010, #12981, #12982

**Comment by cebe** [comment]
https://github.com/nikic/PHP-Parser/commit/5b43809b48564c6c8619932a31caa723740ebb29

**Comment by SamMousa** [comment]
If the PR has been merged should this be closed?

**Comment by dmirogin** [comment]
@SamMousa i think so.
