### ISSUE TITLE
ActiveForm & ActiveField Support for HTML 5 Form Elements

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#1418]
Can we plan ActiveForm & ActiveField support for [new HTML5 form elements](http://www.w3schools.com/html/html5_form_elements.asp) like `<output>
`, `<datalist>`, or `<keygen>`? Most browsers support these (except the odd IE). This is more a proposal - not essentially an issue.

**Comment by dynasource** [comment]
most of this is supported by Html already. One can use Html::tag and in some widgets support for custom tags is already supplied.
