### ISSUE TITLE
PageCache: Missing cacheCookies and cacheHeaders

### ISSUE THREAD

**Issue by boehsermoe** [yiisoft/yii2#14187]
In the current version of 
[PageCache](https://github.com/yiisoft/yii2/blob/master/framework/filters/PageCache.php)
the properties `cacheCookies` and `cacheHeaders` are no used in the class!

It looks, that it is been removed in an refactoring process:
https://github.com/yiisoft/yii2/commit/da944aa9c0a5b1ea39ebeee1404bc4b1934b3b74

What do you think about, to set an HTTP-Header with expired datetime for the PageCache?

Something like that
```
    protected function restoreResponse($response, $data)
    {
        ...
	$response->headers->set('Page-Cache-Expires', date('Y-m-d H:i:s', time() + $this->duration));
        $this->afterRestoreResponse(isset($data['cacheData']) ? $data['cacheData'] : null);
    }
```

**Comment by sergeymakinen** [comment]
It's still in use: https://github.com/yiisoft/yii2/blob/master/framework/filters/PageCache.php#L279
