### ISSUE TITLE
Forced validation in yiiActiveForm do not trigger afterValidate event

### ISSUE THREAD

**Issue by lenyy** [yiisoft/yii2#14186]
Hi there, so for me YiiActiveForm is not performing validation on field when is set manually so i need your help to check if its my problem or Yii.
From the [Yii cookbook](https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md#trigger-validation-for-the-whole-form) if we want to perform validation on form we just need to call 
```javascript
$('#contact-form').yiiActiveForm('validate', true);
```
we assume that it should validate the whole form and send the event afterValidate because the form was validated. But that doesn't happen and its because of this lines in [yii.activeForm.js](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L619-L627)
that clearly say that the event afterValidate can only be launched if we are trying to submit the form which we don't because we only want the validation itself.
Currently i have a workaround by playing with the events that looks like this
```javascript
var validationHandler = function () {
     var form = $('#criar-tarefa-form');
     var data = form.data('yiiActiveForm');
     data.submitting = true;
     data.shouldSubmit = false;
     form.on('afterValidate', handler);
     form.on('beforeSubmit', function () {
               var data = $('#criar-tarefa-form').data('yiiActiveForm');
               if (!data.shouldSubmit) {
                     data.shouldSubmit = true;
                     return false;
               }
     });
     $form.yiiActiveForm('validate', false);
};
```
but its dirty and unnecessary if the event could be fired after the validation ends.
To solve that problem it could be as simple as
```javascript
 var updateInputs = function ($form, messages, submitting) {
        var data = $form.data('yiiActiveForm');

        if (data === undefined) {
            return false;
        }

        var errorAttributes = [];
            $.each(data.attributes, function () {
                if (!$(this.input).is(":disabled") && !this.cancelled && updateInput($form, this, messages)) {
                    errorAttributes.push(this);
                }
            });

            $form.trigger(events.afterValidate, [messages, errorAttributes]);

        if (submitting) {
            updateSummary($form, messages);

            if (errorAttributes.length) {
                if (data.settings.scrollToError) {
                    var top = $form.find($.map(errorAttributes, function(attribute) {
                        return attribute.input;
                    }).join(',')).first().closest(':visible').offset().top - data.settings.scrollToErrorOffset;
                    if (top < 0) {
                        top = 0;
                    } else if (top > $(document).height()) {
                        top = $(document).height();
                    }
                    var wtop = $(window).scrollTop();
                    if (top < wtop || top > wtop + $(window).height()) {
                        $(window).scrollTop(top);
                    }
                }
                data.submitting = false;
            } else {
                data.validated = true;
                if (data.submitObject) {
                    applyButtonOptions($form, data.submitObject);
                }
                $form.submit();
                if (data.submitObject) {
                    restoreButtonOptions($form);
                }
            }
        } else {
            $.each(data.attributes, function () {
                if (!this.cancelled && (this.status === 2 || this.status === 3)) {
                    updateInput($form, this, messages);
                }
            });
        }
        submitFinalize($form);
    };
```

we just pass the errorAttributes setting and the form event before checking if we are submitting. because we want validation only.´

### Yii Version 2.0.11.2

Thanks in advance

**Comment by jesseteal** [comment]
I can confirm that lenyy 's fix works. Thank you! I've been wrestling with this problem for too long.  I'll post back if I encounter any problems.

**Comment by lenyy** [comment]
@jesseteal np but be careful if you change the updateInputs function from yii because once you composer update and composer finds a new yii version that file probably will be overwritten by it.

**Comment by githubjeka** [comment]
And fix it https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md#trigger-validation-for-the-whole-form

**If `'enableAjaxValidation' => true, 'enableClientValidation' => false`:**
 `$('#form-wizard-step3').yiiActiveForm('validate', true);` works only

**If `'enableAjaxValidation' => true, 'enableClientValidation' => true`:**
 `$('#form-wizard-step3').yiiActiveForm('validate');` works only
 `$('#form-wizard-step3').yiiActiveForm('validate', true);` not

**If `'enableAjaxValidation' => false, 'enableClientValidation' => true`:**
 `$('#form-wizard-step3').yiiActiveForm('validate');` not
 `$('#form-wizard-step3').yiiActiveForm('validate', true);` not

**If `'enableAjaxValidation' => false, 'enableClientValidation' => false`:**
 `$('#form-wizard-step3').yiiActiveForm('validate');` works only
 `$('#form-wizard-step3').yiiActiveForm('validate', true);` not

**Comment by samdark** [comment]
@jesseteal, @lenyy I've re-checked it with a fix and it seems it doesn't work well. It validates field that triggered validation but marks the rest of the fields as valid while they either aren't yet validated or aren't valid.

**Comment by lenyy** [comment]
sorry i forgot to post my form settings. Currently i have 
````
'validateOnChange' => false,
'enableAjaxValidation' => true
````
for my workaround to work,.

@samdark did you check with the workaround i posted?  When i tried i got the desired results, i did not change because when you realeased a new version mine would get overwriten by new version so i opted to stay with bug version and control the events my self

**Comment by samdark** [comment]
I did. My comment is about it.

**Comment by lenyy** [comment]
Oh ok sorry, if you need any help just say i can try and test it

**Comment by lenyy** [comment]
Thanks @samdark and @arogachev for the fix.
Will try it with next yii release
