### ISSUE TITLE
Change yii2/docs/guide/test-fixtures.md, maybe more

### ISSUE THREAD

**Issue by pceuropa** [yiisoft/yii2#14182]
Example in [test-fixtures.md](https://github.com/yiisoft/yii2/blob/master/docs/guide/test-fixtures.md#using-fixtures) use yiisoft/yii2-codeception (DEPRACED)
```
namespace app\tests\unit\models;
use yii\codeception\DbTestCase;

class UserProfileTest extends DbTestCase
{
//code 
}
```
Maybe, add class DbTestCase to yii/test/ or app/tests/fixtures location. In my dev environment i copy [DbTestCase](https://github.com/yiisoft/yii2-codeception/blob/master/DbTestCase.php) and [TestCase](https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php) to yii/test folder and it looks like it work fine.
```
<?php
namespace app\tests\unit;

use yii\test\DbTestCase;
use app\tests\fixtures\UserProfileFixture;

class UserTest extends DbTestCase
{
    public function fixtures() {
        return [ 'profiles' => UserProfileFixture::className() ];
    }

    public function testMe()
    {
    }
    // ...test methods...
```
And could on permanently add /fixtures/data/[user.php](https://github.com/yiisoft/yii2/blob/master/docs/guide/test-fixtures.md#fixtures-format) to app/tests/ location ?

I can do pull request. But I would like to know if it makes sense?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0
| Operating system | Debian 8

**Comment by samdark** [comment]
Writing about deprecated stuff definitely doesn't make sense. Should be updated.

Note http://codeception.com/for/yii
