### ISSUE TITLE
ActiveRecord findOne ambiguity

### ISSUE THREAD

**Issue by winterxc** [yiisoft/yii2#14183]
### What steps will reproduce the problem?
User::findOne(['or', ["email" => $this->username], ["username" => $this->username]])

### What is the expected result?
the actual SQL is  "SELECT * FROM `user` WHERE `id` IN ('or', NULL, NULL)"

### What do you get instead?
But what i want is:
User::find()->where(['or', ["email" => $this->username], ["username" => $this->username]])->one();

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      |  5.6
| Operating system | Unbunt 16.04

**Comment by Alex-Code** [comment]
Complex conditions are not supported on the shorthand find methods.

http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findOne()-detail
See the note.

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2/issues/7888#issuecomment-86786985
