### ISSUE TITLE
Add constants and function for sysexits(3) to ConsoleHelper

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#14188]
When I'm authoring console controllers I want a consistent way to choose exit codes for errors. I don't want to have to "think of a number" every time I return a non-zero exit code. And I don't want to invent my own schema. So years ago I adopted the old [FreeBSD sysexits(3)](http://man.openbsd.org/sysexits) codes and definitions. This has worked well for me.

A little while ago, I added something like a port of sysexits.h to my extension of the Yii2 ConsoleHelper. Now, instead of magic numbers like `return 64;`, I have `return ConsoleHelper::EX_USAGE;` and the IDE's autocomplete means I no longer have to refer to sysexits(3) man page to choose an exit code.

I'm sending a PR in case you would like to incorporate this into Yii.

**Comment by samdark** [comment]
Overall it makes sense.
