### ISSUE TITLE
ServiceLocator tree traversal

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#14184]
Suppose I have a nested module hierarchy:
````
App <- A <- B <- C
````

My module A loads its translation doing something similar to:
````
$this->module->get('i18n')->....

````

It uses its parent, which is a descendant of `Module` and thus of `ServiceLocator` to retrieve a dependency.
Now consider a different configuration:
````
App <- B <- A <- C
````
The `B` module has no user facing parts, so it does not know or care about i18n. Module A will however be broken as well since it can no longer locate an i18n component.

While there are arguments for:
1. Injecting dependencies
2. Configuration `i18n` in module `B` so it is available to `A`.

However a simple solution that could work very intuitively as well is to have the `ServiceLocator` class hand off a request to its parent if it cannot fulfill it.
This solution will not break backwards compatibility but add more flexibility for modules and will stop forcing them to use `Yii::$app` as a global service locator.

As a side note the boolean argument `$throwException` should be removed, it is not needed for performance, instead, calling code should just catch the exception.

Note that currently `ServiceLocator` has no concept of a parent, so this should be implemented at the module level:
1. `$module->get()`
2. If we have a parent, go to 3, otherwise 4.
3. Call `parent::get()`, catching any exception.
4. Forward call via `$this->module->get()`, don't catch exception.

**Comment by lynicidn** [comment]
duplicate https://github.com/yiisoft/yii2/issues/4130 ?

**Comment by SamMousa** [comment]
@lynicidn It is definitely not a duplicate, though it is related.

**Comment by samdark** [comment]
Checking parent container makes sense to me. `$throwException` should be discussed/addressed separately.

**Comment by SamMousa** [comment]
> `$throwException` should be discussed/addressed separately.

Regardless of what is decided there, it won't be in 2.x right? Since it breaks BC?
In that case I'll leave it for now.

**Comment by SamMousa** [comment]
@dynasource @klimov-paul feel free to weigh in before there is a PR next time.
If I make an issue, it is marked ready for adoption and you don't take the time to respond you are wasting my time.

**Comment by dynasource** [comment]
we are doing our best to look at many topics as possible. In this case you relied on one opinion, so that is a risk. Especially because PR's require at least 3 approvals of core members to be adopted.

Please don't hesitate to call for more core members opinions before creating a PR.

**Comment by SamMousa** [comment]
My bad, I assumed the label ready for adoption meant ready for adoption :|
