### ISSUE TITLE
Let models for forms provide values for DropDownList

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#14198]
I like the way of ActiveForms to create full featured forms. But I thought one thing could be improved: like `attributeLabels` and `attributeHints` there could be `attributeValues` for fields like DropDowns. That could tidy up view files with forms to something like this:

    <?php $form = ActiveForm::begin() ?>
        <?= $form->field($myFormModel, 'color')->dropDownList() ?>
    <?php  ActiveForm::end() ?>

IMO, it would also move the dealing with the value list to the right place, i.e. to the form model.

Model could than provide this function:

    class MyForm extends Model {
        
        public function attributeValues() {
            return [
                'color' => ['black', 'white'],
            ];
        }
        public function attributeLabels() {...}
        public function attributeHints() {...}
    }

Signature of dropDownList could change to

    function dropDownList($items = null, $options = [])

So `$items` can be provided, but don't have to. If so `attributeValues` would not be used.

Just an idea. Thanks guys!

**Comment by samdark** [comment]
It's better to introduce specific methods that return these values rather than trying to generalize it.
