### ISSUE TITLE
timezone is wrong

### ISSUE THREAD

**Issue by zhangjett** [yiisoft/yii2#14196]
### What steps will reproduce the problem?
I am in CHINA，produce UNIX timestamp By \yii\validators\parseDateValuePHP without hasTimeInfo.Then,i change timestamp to datetime by data() is wrong,it's +8 hours
### What is the expected result?
it is right datetime
### What do you get instead?
When $date->setTime(0, 0, 0), do not set timeZone to  UTC

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.1
| Operating system | windows 10

**Comment by zhangjett** [comment]
2017-05-24 00:00:00 in China, it's should 2017-05-23 16:00:00

**Comment by Renkas** [comment]
Why not include a sample code?

**Comment by zhangjett** [comment]
i think that logic have some problem i use it in `rules()`
