### ISSUE TITLE
Migration ColumnSchemaBuilder set NOT NULL by default

### ISSUE THREAD

**Issue by deniskoronets** [yiisoft/yii2#14208]
I think that in 90% of cases developers are use not null values in database tables. Is it possible to turn NOT NULL is selected by default in migration?

Or at least allow dev to set his own ColumnSchemaBuilder for migrations via console config. It is currently hard coded into Schema class:
https://github.com/yiisoft/yii2/blob/master/framework/db/Schema.php#L327

**Comment by githubjeka** [comment]
It's not a question.

But IMHO this new feature breaks habitual behavior about null by default from database.

**Comment by samdark** [comment]
Indeed, not a question but we won't implement it anyway:

1. As @githubjeka said, it contradicts what's used in databases.
2. It breaks compatibility.
