### ISSUE TITLE
Idea for new built-in validator: proxy to the another validator

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14214]
AR model have getter and setter to attribute `amount` for work with `value` (example: currency stored in intval) and in crud using this field
```php
    public function getAmount()
    {
        return sprintf('%1$01.2f', $this->value / 100);
    }

    public function setAmount($amount)
    {
        $this->value = $amount * 100;
        return $this;
    }
```
and we need set a validation rule for `amount`
```
    public function rules()
    {
         return [
            [['value'], 'integer'],
            [['amount'], function ($attribute, $params) {
                foreach ((array)($params['targetAttribute'] ?? []) as $targetAttribute) {
                    foreach ($this->getErrors($targetAttribute) as $error) {
                        $this->addError($attribute, strtr($params['message'] ?? '{attribute} have error in dependencies {targetAttribute}: {error}', [
                            '{attribute}' => $this->getAttributeLabel($attribute),
                            '{targetAttribute}' => $this->getAttributeLabel($targetAttribute),
                            '{error}' => $error,
                        ]));
                    }
                }
            }, 'params' => ['targetAttribute' => 'value', 'message' => Yii::t('category','{attribute} have error in dependencies {targetAttribute}: {error}')]],
         ];
    }
```

And how about convert this to the new `proxyValidator`?

**Comment by lynicidn** [comment]
you render field `amount` and want collect errors for `value` ? for what?

**Comment by bscheshirwork** [comment]
amount is representation of value.

**Comment by lynicidn** [comment]
nope - amount here is virtual attribute. Read about `skipOnError`. For what in you code validate formatted amount attribute ?
example:
1. input in field amount = 100
2. with error amount field will be contains formatted 100 that break next submit (after fix errors)

плохо с английским - вообщем смысла нет в этом валидаторе - если мы меняем данные через виртуальные аттрибуты - они либо не должны меняться, т.е. 
$a = $model->amount = 100;
echo $model->amount === 100; //false

да и ошибки собирать для поля - которого не было в запросе - бесполезно

**Comment by bscheshirwork** [comment]
Вообще не о том.
Валидатор-прокси позволяет выводить ошибки для существующего в отображении поля модели (Для приведённого примера - amount, основываясь на валидации другого поля sum, которое существует в AR как отражение поля таблицы.). Также данный валидатор позволит задать значение внутреннего поля, "проверив" "внешнее".

**Comment by samdark** [comment]
Won't support that. Looks too complicated not to do it simpler via callback.
