### ISSUE TITLE
Bug in Html::beginForm() for when request contains get parameters which are arrays

### ISSUE THREAD

**Issue by dergus** [yiisoft/yii2#14213]
### What steps will reproduce the problem?
1. Create form (using Html::beginForm()) which  contains multiple inputs with the same key and outputs all inputs  back to user
2. Submit form several times

### What is the expected result?
there shouln't be any hidden fields
### What do you get instead?
there are  hidden fields in form

### Additional info
The problem is that Html::beginForm() makes hidden inputs from get parameters and adds them to the form and thus duplicates inputs, I actually didn't quite understood the whole reason behind adding these hidden fields.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.14
| Operating system | WIndows 10

**Comment by TerraSkye** [comment]
Isnt that the case for statefull forms?

**Comment by pawelkania** [comment]
I have same problem:
1. create GET form,
2. add some array inputs e.h. `<input type="checkbox" name="status[]" value='active'>`
3. open page with form `/url/to/form?status[]=inactive`,
4. select in form checkbox (set status to active),
5. send form

What I expect:
Form with only one field sent - with `/url/to/form?status[]=active`

What I see:
Form with two fields sent - `/url/to/form?status[]=active&status[]=inactive`

Problem is in `https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L351` which creates hidden fields for all get params.

**Comment by cebe** [comment]
if you specify `$action` without parameters, no input fields will be generated, e.g. `beginForm(['controller/action'])`.

**Comment by dergus** [comment]
@cebe got it, thx, though still would appreciate to know why those hidden input fields generated at all

**Comment by cebe** [comment]
they are created to ensure URL keeps the parameters. If target is `index.php?p1=example` and you create a form without hidden input, the `p1=example` will be lost after submitting. creating a hidden field will append form params to the url instead of overwriting query string.
