### ISSUE TITLE
Странное поведение RBAC

### ISSUE THREAD

**Issue by pvlg** [yiisoft/yii2#14222]
Столкнулся со странным поведением rbac.

Реализовал проверку прав примерно как тут
http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-default-roles

```php
class ClientRule extends Rule
{
    public $name = 'client';

    public function execute($user, $item, $params)
    {
        if (!Yii::$app->user->isGuest) {
            return (bool)Yii::$app->user->identity->is_client; // is_client == false
        }

        return false;
    }
}

$auth = Yii::$app->authManager;

$clientRule = new ClientRule();
$auth->add($clientRule);

$clientRole = $auth->createRole('client');
$clientRole->ruleName = $clientRule->name;
$auth->add($clientRole);

$adminRole = $auth->createRole('admin');
$auth->add($adminRole);
$auth->addChild($adminRole, $clientRole);

$auth->assign($adminRole, 1); // Пользователю даю права "admin"

// main.php
 'authManager' => [
    'class' => DbManager::class,
    'defaultRoles' => ['client'],
],
```

Выполняю проверку
```php
var_dump(Yii::$app->user->can('client'));
// false
```

Получаю false, но должно было быть true, т.к. admin содержит client. После некоторого изучения кода нашел причину
```php
    protected function checkAccessRecursive($user, $itemName, $params, $assignments)
    {
        ...
        if (!$this->executeRule($user, $item, $params)) { // если execute возвращает false (т.е. когда is_client == false), то дальнейшие проверки не происходят
            return false;
        }

        if (isset($assignments[$itemName]) || in_array($itemName, $this->defaultRoles)) {
            return true;
        }

        $query = new Query;
        $parents = $query->select(['parent'])
            ->from($this->itemChildTable)
            ->where(['child' => $itemName])
            ->column($this->db);
        foreach ($parents as $parent) {
            if ($this->checkAccessRecursive($user, $parent, $params, $assignments)) {
                return true;
            }
        }

        return false;
    }
```

**Comment by kounelios13** [comment]
Would it be easy for you to translate it to English?It *would* be better for many people to be able to understand what your problem is

**Comment by samdark** [comment]
@kounelios13 sorry that we're communicating in English this time. No time for me to translate it :(

Не вижу противоречий. К client прицеплено правило. Правило по задумке, если прицеплено к роли или разрешению, должно отработать и вернуть `true` чтобы проверка считалась пройденной. В данном случае этого не происходит.

**Comment by pvlg** [comment]
Правило ClientRule возвращает false, но также правило является дочерним по отношению к admin. Т.е. если пользователь является администратором и происходит проверка ```php Yii::$app->user->can('client')```, то должно вернутся true, т.к. ```php $auth->addChild($adminRole, $clientRole)```.

**Comment by pvlg** [comment]
@samdark Правило ClientRule возвращает false, но также правило является дочерним по отношению к admin. Т.е. если пользователь является администратором и происходит проверка ``` Yii::$app->user->can('client')```, то должно вернутся true, т.к. ``` $auth->addChild($adminRole, $clientRole)```.

**Comment by kounelios13** [comment]
@pvlg Sorry friend but if you can't speak or write english I am afraid that it will be difficult for you to get any help

**Comment by pvlg** [comment]
@samdark Получается если использовать правила и оно возвращает false, то родительские разрешения не выполняются. Не нашел где об этом написано в документации. Также если это так (родительские разрешения для правил не выполняются), то по этой ссылке http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-default-roles есть некоторая неточность.

```$auth->addChild($admin, $author);```

Эта проверка никогда не отработает, т.к.
1. Если UserGroupRule вернет false, то родительские проверки происходить не будут.
```php
        if (!$this->executeRule($user, $item, $params)) {
            return false;
        }
```
2. Если UserGroupRule вернет true, то т.к. разрешение находится в defaultRoles, оно вернет true.
```php
        if (isset($assignments[$itemName]) || in_array($itemName, $this->defaultRoles)) {
            return true;
        }
```

Следовательно смысла этой строки ```$auth->addChild($admin, $author)``` в мануале нет.

**Comment by samdark** [comment]
Правило не является дочерним. Оно является необходимым условием в любом случае.
