### ISSUE TITLE
ReflectionException with message Class float does not exist.

### ISSUE THREAD

**Issue by hmkhafan** [yiisoft/yii2#14225]
<?= $form->field($model, 'agentcodemelli')->textInput(['autofocus' => true,'maxlength' => true,'placeHolder'=>'کد ملی معرف'])->label(false) ?>
![image](https://cloud.githubusercontent.com/assets/15983125/26528785/d23843a4-43c7-11e7-8ed7-79e7075bc1ec.png)

**Comment by hmkhafan** [comment]
hello, 
on local my code is true and worke correctly, but when i uploud on the host this error occure. its my code for register form:
`<?php $form = ActiveForm::begin(['successCssClass'=>'ter','errorCssClass'=>'ter']); ?>
            <div class="card-block p-a-2">
                <h3>عضویت</h3>
                <p class="text-muted">حساب کاربری خود را بسازید!</p>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-user"></i>
                            </span>
                    <?= $form->field($model, 'agentcodemelli')->textInput(['autofocus' => true,'maxlength' => true,'placeHolder'=>'کد ملی معرف'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-user"></i>
                            </span>
                    <?= $form->field($model, 'name')->textInput(['maxlength' => true,'placeHolder'=>'نام'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-user"></i>
                            </span>
                    <?= $form->field($model, 'family')->textInput(['maxlength' => true,'placeHolder'=>'نام خانوادگی'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-user"></i>
                            </span>
                    <?= $form->field($model, 'username')->textInput(['maxlength' => true,'placeHolder'=>'نام کاربری'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-user"></i>
                            </span>
                    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true,'placeHolder'=>'موبایل'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-user"></i>
                            </span>
                    <?= $form->field($model, 'codemelli')->textInput(['maxlength' => true,'placeHolder'=>'کد ملی'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-user"></i>
                            </span>
                    <?= $form->field($model, 'job')->textInput(['maxlength' => true,'placeHolder'=>'شغل'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                    <span class="input-group-addon">@</span>
                    <?= $form->field($model, 'email')->textInput(['maxlength' => true,'placeHolder'=>'ایمیل'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-lock"></i>
                            </span>
                    <?= $form->field($model, 'birthday')->textInput(['maxlength' => true,'placeHolder'=>'تاریخ تولد'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-lock"></i>
                            </span>
                    <?php
                    $items = array(1=>'مرد',2=>'زن');
                    ?>
                    <?= $form->field($model, 'jensiat')->dropDownList($items,

                        ['prompt' => 'جنسیت ...', 'class' => 'form-control', 'style' => ['padding-top' => '0px', 'color' => '#999999']])->label(false); ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-lock"></i>
                            </span>
                    <?php
                    $items = \yii\helpers\ArrayHelper::map(\backend\models\Province::find()->all(),'province_id','province_name');
                    ?>
                    <?= $form->field($model, 'state')->dropDownList($items,

                        ['prompt' => 'استان ...', 'class' => 'form-control', 'style' => ['padding-top' => '0px', 'color' => '#999999']])->label(false); ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-lock"></i>
                            </span>
                    <?php
                    $items = array();
                    ?>
                    <?= $form->field($model, 'city')->dropDownList($items,

                        ['prompt' => 'شهر ...', 'class' => 'form-control', 'style' => ['padding-top' => '0px', 'color' => '#999999']])->label(false); ?>
                </div>
                <div class="input-group m-b-1">
                            <span class="input-group-addon"><i class="icon-lock"></i>
                            </span>
                    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true,'placeHolder'=>'کلمه عبور'])->label(false) ?>
                </div>
                <div class="input-group m-b-2">
                            <span class="input-group-addon"><i class="icon-lock"></i>
                            </span>
                    <?= $form->field($model, 'repassword')->passwordInput(['maxlength' => true,'placeHolder'=>'تکرار کلمه عبور'])->label(false) ?>
                </div>
                <div class="input-group m-b-1">
                           <a class="select-file input-group-addon btn btn-primary">انتخاب فایل</a>
                    <input type="text" disabled placeholder="انتخاب کارت شناسایی" class="select-file form-control">
                </div>
                <?= $form->field($model, 'identificationcard')->fileInput(['style'=>['display'=>'none']])->label(false) ?>
                <div class="row">
                    <div class="col-xs-6">
                        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'ارسال') : Yii::t('app', 'ویرایش'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>
                    <div class="col-xs-6 text-xs-right">
                        <a class="btn btn-link p-x-0" href="<?=\yii\helpers\Url::toRoute('site/login')?>">قبلا ثبت نام کردم</a>
                    </div>
                </div>
                <div class="error">
                    <?=$form->errorSummary($model);?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>`
and its my controller code:
`public function actionRegister(){
        if(!Yii::$app->user->isGuest)
            return $this->goHome();
        $this->layout = "register";
        $model = new User();
        if ($model->load(Yii::$app->request->post())) {

            if($model->agentcodemelli != "")
            {
                $res = User::find()->where(['agentcodemelli'=>$model->agentcodemelli])->one();
                if(!$res) {
                    $model->addError("agentcodemelli", "کد ملی معرف نامعتبر است!");
                    return $this->render('register', [
                        'model' => $model
                    ]);
                }
            }

            if($model->email != "")
            {
                $res = User::find()->where(['email'=>$model->email])->one();
                if($res) {
                    $model->addError("email", "ایمیل وارد شده قبلا توسط شخص دیگری ثبت شده است!");
                    return $this->render('register', [
                        'model' => $model
                    ]);
                }
            }

            if($model->username != "")
            {
                $res = User::find()->where(['username'=>$model->username])->one();
                if($res) {
                    $model->addError("username", "نام کاربری وارد شده قبلا توسط شخص دیگری ثبت شده است!");
                    return $this->render('register', [
                        'model' => $model
                    ]);
                }
            }

            if($model->mobile != "")
            {
                $res = User::find()->where(['mobile'=>$model->mobile])->one();
                if($res) {
                    $model->addError("mobile", "شماره موبایل وارد شده قبلا توسط شخص دیگری ثبت شده است!");
                    return $this->render('register', [
                        'model' => $model
                    ]);
                }
            }


            if($model->agentcodemelli != "" && $model->codemelli != "")
                if($model->agentcodemelli == $model->codemelli)
                {
                    $model->addError("agentcodemelli","کد ملی معرف با کد ملی وارد شده یکی است!");
                    return $this->render('register',[
                        'model'=>$model
                    ]);
                }
            $model->password_hash = Yii::$app->security->generatePasswordHash($model->password);
            $model->auth_key = Yii::$app->security->generateRandomString();
            $model->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
            $model->created_at = time();
            $model->updated_at = time();
            $model->upload();
            if($model->save())
            {
                return $this->redirect("login");
            }
        }
        return $this->render('register',[
            'model'=>$model
        ]);
    }`

**Comment by hmkhafan** [comment]
my code not work please help me!

**Comment by samdark** [comment]
We can't really get anything from the info provided. If you're sure it's framework issue — please provide a way to reproduce it so we can fix it. If not — it's better to ask questions in IRC or at forums.

**Comment by ElisDN** [comment]
@hmkhafan Perhaps your have written 'float' validator instead of 'number' in `rules()` method of your model.

**Comment by cebe** [comment]
closing until more info provided.

**Comment by newscloud** [comment]
Hi, I ran into this problem tonight. It was indeed fixed by changing "float" to "number" in rules
...
[['experience' ], 'number'],
