### ISSUE TITLE
ErrorHandler action is not invoked

### ISSUE THREAD

**Issue by pkarczmarczyk94** [yiisoft/yii2#14228]
### What steps will reproduce the problem?
In my RESTFul app I'm trying to add custom error handler but action is not invoked.
Here is my application config:
```
'components' => [
        'errorHandler' => [
            'errorAction' => 'error/error',
        ],
]
```

And my controller class
```
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class ErrorController extends Controller {

	public function actionError()
	{
		echo 'error';exit;
	}
}
```

### What is the expected result?
Action from ErrorController is executed.
### What do you get instead?
Default yii error handler is executed.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.0
| Operating system | Ubuntu 16.04

**Comment by cebe** [comment]
> Default yii error handler is executed.

do you have YII_DEBUG enabled?
