### ISSUE TITLE
Table structure in ActiveRecord Model and generating migrations from that structure

### ISSUE THREAD

**Issue by dergus** [yiisoft/yii2#14221]
I've an idea how to make migrations even easier and Model structure more explicit:

Writing table columns in model class like that:
```
class Article extends ActiveRecord 
{
    public function tableColumns(yii\db\Migration $migration): array
    {
       return [
                'id' => $migration->primaryKey(),
                'title' => $migration->string()->notNull(),
                'content' => $migration->text(),
            ];
    }
}
```
thus we can first create model and then generate migration from that model with console command:
```php yii migrate/generate --model=Article ```
If we change table structure we can do it in model class and generate new migration.

Django framework has such feature.

What do you think?

**Comment by TerraSkye** [comment]
Personaly i see it the other way arround? We generate models from the database, wich in turn are created by migrations for example. How would u deal with database changes ea new columns. Columns altering?

**Comment by samdark** [comment]
Yes, changes aren't obvious in this case.

**Comment by dergus** [comment]
@TerraSkye The idea is that you generate migrations from models, also I think it would be good to make cli command which would generate or update the tableColumns() method with current table structure.

**Comment by dergus** [comment]
@samdark which changes aren't obvious? I think it's quite the opposite

**Comment by samdark** [comment]
@dergus for example, you already have database in place created by setting `tableColumns()`. Now you need to adjust some of the columns, drop some columns, rename one of the columns keeping data so you're changing `tableColumns()`. What's happens next?

**Comment by dergus** [comment]
@samdark you call ```php yii migrate/generate --model=Article``` again and it will generate the diff migration

**Comment by samdark** [comment]
It won't be able. For example, I have a `User` model with `prefix` field and I need to rename it to `title` keeping data. I'm adjusting `tableColumns` renaming `prefix` to `title`. How should migrations generator know that rename is needed instead of dropping `prefix` and adding `title` which is valid case as well?

**Comment by dergus** [comment]
@samdark well, renaming is gonna be a problem, I've not thought about it

**Comment by dergus** [comment]
@samdark though maybe it could be solved with annotations or by specifying renamed columns in migrate/generate command

**Comment by samdark** [comment]
I think that defeats the main pro of such declaration: being simple.

**Comment by TerraSkye** [comment]
Therefore i rather write the migration and generate the model of it.
Besides you would need a stub model wich u copy. Then add the fields to the list. Generate a migration of that model. Update the model with all phpdoc/ virtual properties. 
All in all it defeats the purpose of schema first.

**Comment by samdark** [comment]
If you'll think of a way to make it both working well and simple, post here. Till then I'm closing the issue.

**Comment by sreenadh** [comment]
https://github.com/Cytracom/laravel-migration-squasher
