### ISSUE TITLE
When I configure catchAll, the page will be repeated two times

### ISSUE THREAD

**Issue by kousuutetu** [yiisoft/yii2#14229]
### What steps will reproduce the problem?
In addition to installing and configuring catchAll, no other changes have been made.

![wechatimg1](https://cloud.githubusercontent.com/assets/5842445/26550106/cca1709a-44ae-11e7-9f75-887183cd600d.jpeg)
![wechatimg2](https://cloud.githubusercontent.com/assets/5842445/26550111/d579f796-44ae-11e7-8156-87a7ffd6fcd2.jpeg)

### What is the expected result?
normally
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7
| Operating system |Mac OS

**Comment by samdark** [comment]
How did you configure it exactly?

**Comment by kousuutetu** [comment]
Details are as follows:
`composer create-project yiisoft/yii2-app-advanced soda`
`php init --env=Development --overwrite=y`
edit `frontend/config/main.php` file, and add `'catchAll' => ['site/about'],` in last, like that
<img width="344" alt="2017-05-30 8 07 30" src="https://cloud.githubusercontent.com/assets/5842445/26564084/16ab0ad8-450f-11e7-96af-aa8c948fcde5.png">

When you visit, you'll see a page rendering two times

**Comment by Alex-Code** [comment]
Do you have the debug toolbar enabled?

**Comment by kousuutetu** [comment]
Ah, I see, the second rendering of the page is debug page. thank you.
