### ISSUE TITLE
ActiveRecord link() / unlink() methods do not update model relation with saved data

### ISSUE THREAD

**Issue by bravik** [yiisoft/yii2#14233]
### What steps will reproduce the problem?
A bit modified example from official [guide](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#saving-relations)
```
$customer = Customer::find()->where(['id'=>123])->with('orders')->one();
$order = new Order();
$order->subtotal = 100;
// ...
$order->link('customer', $customer);
```
### What is the expected result?
`$customer->orders` before `link()/unlink()` have already been populated with data.
After `link()/unlink() ` the new/deleted Order should be added/removed to `$customer->orders` after saving data to DB.

### What do you get instead?
The new/delted orders is saved in database,
but `$customer->orders` are not updated.

### Additional info
Also there is a method `refresh()` which reloads AR model.
However this method doesn't update or have any option to update relations.
It just clears `$customer->orders`
So t reload it i have to introduce an unused variable... just to load related data.. like this:

```
$customer->refresh();
$orders = $customer->orders; //Not used variable

```
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2.
| PHP version      | 7.1
| Operating system | Debian

**Comment by TerraSkye** [comment]
```unset($customer->orders);``` would do, as the next time u request customer->order it reloads the relation

**Comment by bravik** [comment]
@TerraSkye, I deal with it almost the same way:
```
$customer->refresh();
$orders = $customer->orders; //Not used variable
```
But it would be better to enhance existing methods link(), unlink() and also refresh() to do as expected.

**Comment by rob006** [comment]
Related #13618?

**Comment by cebe** [comment]
> After link()/unlink() the new/deleted Order should be added/removed to $customer->orders after saving data to DB.

this should be the case: https://github.com/yiisoft/yii2/blob/17a1d91e4a517f4f15dce973bf3c50dd939dce63/framework/db/BaseActiveRecord.php#L1304-L1318

>  but $customer->orders are not updated.

are you sure? I see no way in the code I linked above that could skip modifying `$customer->orders`.

>  So t reload it i have to introduce an unused variable... just to load related data.. like this:

why do you want to reload it if you do not use it afterwards?

**Comment by bravik** [comment]
@cebe I'm very sorry to take your time. But it seems like this issue is not correct.
I've returned to my code after a couple of month and I see the following:

At the end I'm calling
`$model->refresh();`
and this function clears the populated relations.
`link` and `unlink` do the job.

I do not rememeber why was the need for that..
@samdark This issue should be closed as incorrect.

> why do you want to reload it if you do not use it afterwards?
I update the model and return all of it to frontend
