### ISSUE TITLE
Model::findOne() - performance impact without LIMIT(1) for non-primary|unique indexes

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2#14236]
I am not sure where to clarify why active record method `Model::findOne()` won't add the `LIMIT 1` clause automatically to the generated SQL query. I discovered this recently when I noticed performance degradation on large datasets. Because I perhaps might have missed some reason of why the `LIMIT 1` is not added, I am opening this issue.

### Problem summary:

[1] Following SQL is generated by `Newsletter::findOne(123)`:
`SELECT * FROM newsletter WHERE user_id=123`

[2] And following is generated by `Newsletter::find()->where(['user_id' => 123])->limit(1)->one()`:
`SELECT * FROM newsletter WHERE user_id=123 LIMIT 1`

The difference is `LIMIT 1` clause.

This may seem insignificant, but according to how indexes work, it may cause huge performance degradation on large datasets. The reason is, that SQL in [1] will not stop column scan when founds first match and will continue until whole column scanned. On tables with millions of records this has significant negative performance impact. So variant [1] works flawlessly only on columns with **primary or unique indexes**, where the **ID uniqueness is guaranteed**. It performs badly on columns with common KEY indexes because uniqueness cannot be guaranteed. However, since the method name `one()` or `findOne()` suggests it will return only one (first) match it makes no sense to continue scanning after matching first record. So by adding `LIMIT 1` it would stop scanning also on non-unique indexes and ensure optimal performance. 

Therefore method `findOne()` [1] should currently only be used on PK and UNIQUE columns, for other columns should be used second [2] variation. 

## Question:

Could this be fixed so the the method `findOne()` would automatically add `LIMIT 1` into generated SQL query? Or did i miss some reason why it may not be added? If not I guess this should be emphasized in documentation so developers would realize described performance difference.

----------------------

### What steps will reproduce the problem?

On large datasets (millions of records) execute `Newsletter::findOne(123)` and then `Newsletter::find()->where([user_id => 123])->limit(1)->one()` on columns with common `KEY index` (not primary or unique).

### What is the expected result?

Both methods should generate equal SQL & perform similarly on benchmarks.

### What do you get instead?

First [1] variant `Newsletter::findOne(123)` shows performance degradation on KEY indexed columns (or even worse non-indexed) due to full column scan, while second variant [2] `Newsletter::find()->where([user_id => 123])->limit(1)->one()` performs optimally.

### Additional info

I have seen couple of complaints about Yii2 DB performace around and this issue could be possibly related. 

| Q                | A
| ---------------- | ---
| Yii version      | any
| PHP version      | any
| Operating system |any

**Comment by klimov-paul** [comment]
Duplicates #13875

**Comment by lubosdz** [comment]
Sorry, I missed all those issues ..

So the reason would be not adding LIMIT 1 for complex queries with multiple joins & complex indexes, which might cause some databases to use temporary tables and degrade performance, right? 

however, major cases are just simple queries. 

The method should respect by default major cases and for edge cases should allow turning off automatic adding LIMIT clause. There is something wrong with current status if so many developers complain, right? :-)

**Comment by samdark** [comment]
Yes. The issue @klimov-paul refers to is open.
