### ISSUE TITLE
yii2 migrate failed : Tablespace xxxx  exists. on Win7

### ISSUE THREAD

**Issue by fbens** [yiisoft/yii2#14231]
### What steps will reproduce the problem?
I cant run migrate on Win7.

### What is the expected result?
I can run migrate on Win7

### What do you get instead?
```
$tableOptions = null;
if ($this->db->driverName === 'mysql') {
	// http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
	$tableOptions = '   ENGINE=InnoDB';
}

$this->createTable('{{%source_message}}', [
	'id' => $this->primaryKey(),
	'category' => $this->string(),
	'message' => $this->text(),
], $tableOptions);
```

*But when I use Mac OS X or centos,I can run it with `$tableOptions = null` *

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1.3
| MySql Version | 5.7
| Operating system | Win7

**Comment by cebe** [comment]
looks more like a problem with your MySQL setup than a framework issue...

**Comment by fbens** [comment]
I don't know why, now i  reinstall  MySQL SERVER to resolve this problem.
