### ISSUE TITLE
Yii2 migration confirm issue "Apply the above migrations?"

### ISSUE THREAD

**Issue by fbens** [yiisoft/yii2#14247]
### What steps will reproduce the problem?
When I use `nohup php yii migrate > ~/log.log 2>&1&` it will tips a confirm prompt, but there is no options to ignore this.

### What is the expected result?
Append a param like `-y` to ignore confirm.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1.4
| Operating system | Mac OS X / CentOS 7

**Comment by rob006** [comment]
This command has `interactive` switch: http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#using-command-line-options

**Comment by fbens** [comment]
@rob006 Thank you very much :-)
```
# migrate the migrations in a forum module non-interactively
yii migrate --migrationPath=@app/modules/forum/migrations --interactive=0
```
