### ISSUE TITLE
Nested Pjax pagination issue

### ISSUE THREAD

**Issue by vendhanparthy7** [yiisoft/yii2#14240]
``` html
<div id="nx-all-client-grid-pjax" >
    <!-- Table -->
    <div id="p0" >         
        <!-- Box Widget -->
        <div id="p0" >
         	<!-- Page Render -->
         	<div id="client-id-capture-user-pjax" >
          		<!-- Table  -->
         	</div>   
       </div>
   </div>
</div>
```

My Layout is having 4 Pjax widgets, starting with

>Table (Gridview) (id = #nx-all-client-grid-pjax)
>Box Widget (id = #p0)
>Page Render (_render) (id = #p0)
>Table (Gridview) (id = #client-id-capture-user-pjax)

while doing pagination from the child grid **(#client-id-capture-user-pjax)** , it sends the 
form data as parent pjax id **_pjax:#nx-all-client-grid-pjax** 
and parent Gridview refreshes instead of child gridview

**Need to send the respective Pjax id to gridview while doing pagination/sorting/filter**

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.06
| Operating system | Windows

**Comment by cebe** [comment]
I do not think nesting pjax and gridviews is a good idea. pjax is meant to replace the URL in case of parts of the page are changing, having multiple pjax widgets on one page will make them conflict in this.
