### ISSUE TITLE
MessageController outputs colored text when unsupported by console

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#14248]
### What steps will reproduce the problem?
Run the `php yii message <path-to-config>` console command in the Windows command prompt.

### What is the expected result?
```TXT
Extracting messages from [0m[36mC:\test\app\frontend\controllers\SiteController.php[0m...
```
### What do you get instead?
```TXT
Extracting messages from C:\test\app\frontend\controllers\SiteController.php...
```
### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.18
| Operating system | Windows 10

At the very least `MessageController` should check if console supports colorization before outputting colored strings. Alternatively, `MessageController` should always output uncolored strings.

**Comment by machour** [comment]
Interesting to see how symfony tests that:
  https://github.com/symfony/symfony/blob/2909e4b04d04653286b8d63b19e11a40157497b5/src/Symfony/Component/Console/Output/StreamOutput.php#L91

@PowerGamer1 could you provide your complete Windows version information ?
`<?= PHP_WINDOWS_VERSION_MAJOR.'.'.PHP_WINDOWS_VERSION_MINOR.'.'.PHP_WINDOWS_VERSION_BUILD ?>`

**Comment by PowerGamer1** [comment]
> @PowerGamer1 could you provide your complete Windows version information ?
 `<?= PHP_WINDOWS_VERSION_MAJOR.'.'.PHP_WINDOWS_VERSION_MINOR.'.'.PHP_WINDOWS_VERSION_BUILD ?>`

Mine is `10.0.14393` and it does not support text colorization escape sequences out of the box.

**Comment by cebe** [comment]
@machour yii has a similar function to test this: https://github.com/yiisoft/yii2/blob/cd3c6404cb658b2a0d397959c5428779d706f045/framework/helpers/BaseConsole.php#L582-L587 it just is not called in this place.
