### ISSUE TITLE
ExistValidator may not work properly in master-slave replication environment

### ISSUE THREAD

**Issue by yanhuixie** [yiisoft/yii2#14254]
### What steps will reproduce the problem?
1) works with a master-slave replication database cluster
2) for some reason disable the Transaction 
3) AR Foo has an auto increment primary key "id"
4) AR Bar has a foreign key related to Foo->id as "foo_id" and guarded by exists validator (generated by gii)
5) Save Foo first, then new a Bar bar and set bar->foo_id  = foo->id, and bar->save()
At that time my be an error occurs (OR NOT) : "Foo ID is invalid." And foo is saved but bar not.

### What is the expected result?
No exists validator error occurs, foo and bar both saved normally.

### A temporary solution
disable the exists validator of Bar.

### Additional info
I think it's not means a bug, but an announcement for the developer. Because it's unavoidable that there is a  lag between the replication process from the master node to the slave nodes. Without the guarantee of high level database transaction, the EXISTS VALIDATOR may query a "NEW" foo from an unsynchronized slave node.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.17
| Operating system | OSX or Linux

**Comment by rossoneri** [comment]
We can add an option for ExistValidator to spcify using the master db, how about that? @yanhuixie @samdark

**Comment by yanhuixie** [comment]
Thanks for your reply, @rossoneri ! I think it's a good idea. 
It's reliable that write and read the "foo" from the same db node.
What we should remind (in documentation?) is that there are some premises to do so.
1) config correctly in Yii2 'db' component (master and slaves).
2) the db nodes may NOT behind a proxy middle-ware/load balancer or config it works as read/write splitting mode, but not multi-master.

**Comment by samdark** [comment]
@rossoneri yes, that should be OK.

**Comment by rossoneri** [comment]
@samdark I will do it!
