### ISSUE TITLE
problem with save array in session in db 

### ISSUE THREAD

**Issue by mamadza69** [yiisoft/yii2#14258]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5?
| PHP version      7 or 5.6| 
| Operating system  windows 10 |

**Comment by cebe** [comment]
> 2.0.5?

please try with the latest version of Yii, which is 2.0.12

**Comment by mamadza** [comment]
is it solved in that version ? or it guess

**Comment by samdark** [comment]
No idea. Try it first.

**Comment by mamadza** [comment]
that's not solved

**Comment by mamadza** [comment]
I think it's bug
