### ISSUE TITLE
Yii2 ActiveForm suggestion.

### ISSUE THREAD

**Issue by crnimilos** [yiisoft/yii2#14250]
It would be a really nice feature if we could create same output of regular view page with ActiveForm. 

It would reduce code we need to use for these kind of cases, as we can use same view for edit and view. 

This simplifies coding specially in the case when we want to use same template for view as what we are using for forms. 

Ideally would be if we can have parameter in ActiveForm like "readOnly" which would convert whole form into text only without editable fields.

**Comment by cebe** [comment]
in a lot of cases the display of a record is significantly different from the editing form of a record. Also ActiveForm is missing information on formatting of the data that would be displayed, which is available in DetailView widget. I do not think it makes sense to try to merge these two.
