### ISSUE TITLE
yii2/log/Logger.php md5() expects parameter 1 to be string

### ISSUE THREAD

**Issue by mvkasatkin** [yiisoft/yii2#14264]
In YII_DEBUG mode it fails with "md5() expects parameter 1 to be string" on yii2/log/Logger.php in method calculateTimings, line 281, due to UrlManager sends in Yii::trace an array on line 271 (method parseRequest)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12

**Comment by mvkasatkin** [comment]
### What steps will reproduce the problem?

Problem occures when I call Yii::getLogger()->getProfiling() in web controller's action.

### What is the expected result?

expecting an array as an result of Yii::getLogger()->getProfiling();

### What do you get instead?

```
md5() expects parameter 1 to be string, array given

#0 /private/var/www/wcadmin.local/vendor/yiisoft/yii2/log/Logger.php(211): yii\log\Logger->calculateTimings('???')
#1 /private/var/www/system.local/platform/core/base/Profiler.php(46): yii\log\Logger->getProfiling()

```
Seems, yii\log\Logger::calculateTimings gets an array ['rule' => '...', 'match' => false, 'parent' => null] instead of expected string. The array was sent by UrlManager on line 271 in method parseRequest

**Comment by samdark** [comment]
Reproduced. Steps:

1. Install basic project template.
2. Enable URL manager.
3. Call `Yii::getLogger()->getProfiling()` in web controller's action.

**Comment by bizley** [comment]
I'm sorry, it's my bad. Fix coming.

**Comment by samdark** [comment]
@mvkasatkin does it happen w/o calling a method manually?

**Comment by mvkasatkin** [comment]
@samdark, no, without calling manually it is ok. My project's specified profiler use it and fails. try/catch helps as a workaround.

**Comment by samdark** [comment]
OK. It's not fixed but I guess a workaround is necessary for now.

**Comment by xf3** [comment]
With deea182 fix throwing an exception in controller causes another error:
```
An Error occurred while handling another error:
Exception: Serialization of 'Closure' is not allowed in /**/vendor/yiisoft/yii2/log/Logger.php:281
```
While without it exception is properly handled. 

To reproduce, add in controller action:
`throw new \yii\web\BadRequestHttpException();`
And in response component configuration:
```
'response' => [
    ...
     'on beforeSend' => function ($event) {
        Yii::getLogger()->getProfiling();
    },
]
```

Is this an expected behavior and exception should be handled another way?

**Comment by samdark** [comment]
@xf3 reproduced. Made a pull request fixing. Please check if it works well.

**Comment by xf3** [comment]
@samdark seems to be working fine. Thanks!
