### ISSUE TITLE
Function UniqueValidator.applyTableAlias breaks PostgreSQL compatibility

### ISSUE THREAD

**Issue by robregonm** [yiisoft/yii2#14274]
### What steps will reproduce the problem?
- Create two tables with special case or special chars (e.g "ParentTable" and "ChildTable") and add a foreign key to the child table
- Create models for both tables and add UniqueValidator and/or ExistsValidator to the foreign key in the child table.
- Try to create a record on child table and allow the model to validate the data `$model->save()`
### What is the expected result?
Everything should work smoothly. In fact, in version 2.0.11 runs fine. But this bug was introduced here: https://github.com/yiisoft/yii2/commit/921147dca5aeab59901aed16e0a9113f48a0f8bb#commitcomment-22454348
### What do you get instead?
```
[error][yii\db\Exception]
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing
FROM-clause entry for table "parenttable"
LINE 1 SELECT EXISTS(SELECT * FROM "ParentTable" WHERE ((ParentTable."id"='1'))`
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12@dev
| PHP version      | 7.1
| Operating system | Ubuntu 14.06

**Comment by SilverFire** [comment]
Please, check the commit b0148a5
I've tried to reproduce the problem, but it seems that everything is OK. Could you fix the test to make it fail?
