### ISSUE TITLE
jquery.inputmask dependency no longer available; installs failing

### ISSUE THREAD

**Issue by davidjeddy** [yiisoft/yii2#14275]
### What steps will reproduce the problem?
`composer global require "fxp/composer-asset-plugin"`
`composer install`

### What is the expected result?
Packages to be installed

### What do you get instead?
Failed to install

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      |  7.1
| Operating system | Amazon Linux / OSX

```
[227.8MB/40.89s] Your requirements could not be resolved to an installable set of packages.
[227.8MB/40.89s] 
  Problem 1
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - yiisoft/yii2 2.0.12 requires bower-asset/jquery.inputmask ~3.2.2 | ~3.3.5 -> no matching package found.
    - yiisoft/yii2 2.0.11.2 requires bower-asset/jquery.inputmask ~3.2.2 | ~3.3.3 -> no matching package found.
    - yiisoft/yii2 2.0.11.1 requires bower-asset/jquery.inputmask ~3.2.2 | ~3.3.3 -> no matching package found.
    - yiisoft/yii2 2.0.11 requires bower-asset/jquery.inputmask ~3.2.2 | ~3.3.3 -> no matching package found.
    - yiisoft/yii2 2.0.10 requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - Installation request for yiisoft/yii2 ^2.0.6 -> satisfiable by yiisoft/yii2[2.0.10, 2.0.11, 2.0.11.1, 2.0.11.2, 2.0.12, 2.0.6, 2.0.7, 2.0.8, 2.0.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
[148.4MB/40.93s] Memory usage: 148.38MB (peak: 227.89MB), time: 40.93s
bash-4.2# 

```
See https://github.com/RobinHerbots/jquery.inputmask/issues/2 the inputmask library is not longer available. From what I can tell it 'was' working due to github aliasing the package. Now the alias is released composer is failing to install.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/a3a123077f4feb3d8031a063fe7dba20d5434464#commitcomment-22458028

**Comment by petrabarus** [comment]
Would love to know if anyone has found a workaround solution regarding this.

**Comment by petrabarus** [comment]
One workaround that I've come up with is overriding the `jquery.inputmask` repository via `fxp` configuration in `composer.json`.

```json
    "config": {
        "fxp-asset": {
            "repositories": {
                "bower-asset/jquery.inputmask": {
                    "type": "bower-github",
                    "url": "https://github.com/petrabarus/jquery.inputmask"
                }
            }
        }
    }
```

**Comment by ddinchev** [comment]
Based on @petrabarus idea what solved it for me was this config:

```
  "config": {
    "fxp-asset": {
      "installer-paths": {
        "npm-asset-library": "vendor/npm",
        "bower-asset-library": "vendor/bower"
      },
      "repositories": [
        {
          "type": "bower-vcs",
          "url": "https://github.com/RobinHerbots/Inputmask.git",
          "name": "bower-asset/jquery.inputmask"
        }
      ]
    }
  },
```

**Comment by petrabarus** [comment]
@ddinchev I tried that, somewhat still not working. Have you tried in fresh clone or clear composer cache?

**Comment by ddinchev** [comment]
Yes, make sure you are using fxp asset 1.3.x as the config format has changed.

**Comment by petrabarus** [comment]
Okay, I just fixed the `fxp` asset version. This seems to be working. Thanks!

**Comment by samdark** [comment]
Package author asked github to alias to old name. Will see if that helps.

**Comment by petrabarus** [comment]
@samdark I guess, the current dependency will need change to point to new repo in 2.0.13.

**Comment by samdark** [comment]
Not if alias will be there.

**Comment by marcobiraghi** [comment]
@ddinchev it's a good workaround but it works only local (I think there's something cached, despite clearing). On a fresh VM it doesn't work yet.

**Comment by petrabarus** [comment]
@marcobiraghi what's your `composer` and `fxp/composer-asset-plugin` version?

**Comment by marcobiraghi** [comment]
@petrabarus 1.3.1

**Comment by samdark** [comment]
@petrabarus fxp doesn't matter in this case. It's package that was changed.

**Comment by cebe** [comment]
as far as I see, this could solve the issue: https://github.com/RobinHerbots/jquery.inputmask/issues/2#issuecomment-307345337

**Comment by petrabarus** [comment]
@samdark i think it's the fxp configuration format. before @ddinchev mentioned it was working in his machine, my version was below `1.4.1`. after i upgrade to `1.4.1`, it's working fine.

**Comment by iskander-g** [comment]
@petrabarus can you please say me, how to upgrade to version 1.4.1?

The latest version of composer-asset-plugin  is 1.3.1:
https://packagist.org/packages/fxp/composer-asset-plugin#v1.3.1

**Comment by pasha-pivo** [comment]
Problem 1
    - The requested package fxp/composer-asset-plugin ^1.4 is satisfiable by fxp/composer-asset-plugin[1.4.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by petrabarus** [comment]
Ah i apologize, i was mixed. The the composer was 1.4.1, and the fxp was 1.3.1. I guess yours are already correct.
In mine it's working, though.

**Comment by iskander-g** [comment]
i have same versions.

i tried your config and ddinchev's one, anyway nothing doesn't work :-(

**Comment by petrabarus** [comment]
Here's my step.
```
composer self-update 1.4.1
composer global require "fxp/composer-asset-plugin:1.3.1"
composer clean-cache
composer update
```

**Comment by zakharov-ilia** [comment]
@petrabarus , correct is "clear-cache".

**Comment by cebe** [comment]
looks like the redirect is back in place now, so that is why it's working again

**Comment by marcobiraghi** [comment]
Yes, back to work! 🎉

**Comment by pshentsoff** [comment]
I was helped by the following (maybe useful to someone):

1. [ddinchev's solution](https://github.com/yiisoft/yii2/issues/14275#issuecomment-307306269) - I'm not sure if this is necessary, but it worked
2. `$ composer global require "fxp/composer-asset-plugin:^1.2.0"`
3. `$ composer require bower-asset/jquery.inputmask`

After this composer updated all dependencies without any problems:
`$ composer update`
`Loading composer repositories with package information`
`Updating dependencies (including require-dev)`                   
`Nothing to install or update`                               
`Generating autoload files`

**Comment by hagenr** [comment]
1. `composer self-update`
2. `composer update yiisoft/yii2 yiisoft/yii2-composer bower-asset/jquery.inputmask`
3. `composer update`

worked for me with stability dev

**Comment by fehliimaa** [comment]
Run only this command in Git Bash in your project repository:

$composer self-update
$composer update yiisoft/yii2 yiisoft/yii2-composer
$composer require bower-asset/jquery.inputmask
$composer update
