### ISSUE TITLE
Using Captcha resets View::$params

### ISSUE THREAD

**Issue by selimachour** [yiisoft/yii2#14271]
I'm using View::$params to pass some css class to the main layout from the controller.
Everything has been working so far, but the client asked me to add a captcha ...

### What steps will reproduce the problem?

In the controller : Yii::$app->view->params['bodyClass'] = 'candidate'; 
In the view : <?= $form->field($mode, 'captcha')->widget(Captcha);
In view/layout/main.php : <body class="<?= $this->params['bodyClass'] ?>">

### What is the expected result?
<body class="candidate">

### What do you get instead?
<body class="">

### Additional info
If I remove the <?= $form->..captcha ?>  line, everything works as usual.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | PHP 7.0.18-0ubuntu0.16.04.1
| Operating system | LinuxMint 18.1

**Comment by klimov-paul** [comment]
Unable to reproduce.
I am also unable to find any usage of `View::$params` inside `Capctha`, `ActiveForm` or `ActiveField` classes, thus I can not imagine how such issue may appear.

**Comment by selimachour** [comment]
Ok ... I dug out a little more and I realized that Captcha calls my app\components\Controller which in the init() function does this `Yii::$app->view->params['bodyClass'] = ''` hence overwriting my variable ...

Sorry for the false alert.
