### ISSUE TITLE
Logging by url route 

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#14273]
### What steps will reproduce the problem?
Try to create logging logic of the web-application based on url hardcoded routes or based on regex. Let's say I have `/admin` (would log everything within backend side) or `/admin/bank/*` (would log everything within `bank` controller)  route and I would like to get all `_GET`, `_POST` requests happening in it. 

### What is the expected result?
I would like to be able to set up this kind of structure: 

```php 
'log' => [
    'targets' => [
        [
            'class' => 'yii\log\FileTarget',
            // 'categories' => ['backend'], 
            'urlMatch' => ['/admin/*'], // <---
            'logVars' => ['_GET', '_POST'],
            'logFile' => '@app/runtime/backend.log',
        ],
    ],
],
```
So that covers all of the requests on the `admin/*`. 

> With categories, I will need to go to each controller or model and place this category to get the loggin information, which is not very comfortable. 

If there is anything like this already, please provide a link, this will be useful. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04
| Advanced app or basic     | Advanced

**Comment by kevinobama** [comment]
It's a little useful, Should we add it?

**Comment by rob006** [comment]
`yii\log\Target::$enabled` could support closures - then you could filter logs by anything, for example all activity of users with specific role.

**Comment by samdark** [comment]
I don't think it's a particularly good idea. If the application is structured properly, a set of classes is typically used in multiple URLs so it's better to stick to categories. If you still need that, @rob006 provided a solution.

**Comment by rob006** [comment]
@samdark This is not a solution - right now `yii\log\Target::$enabled` does not support closures, so you can't use it.

**Comment by samdark** [comment]
OK. Adding closures makes sense.

**Comment by bologer** [comment]
@cebe could you briefly give an example of how to use this new addition?

**Comment by cebe** [comment]
@bologer define log targets for everything you need to be logged and configure the 'enabled' property by checking the current request for whatever you need, so it only logs things when the condition is true.

**Comment by bologer** [comment]
@cebe can be described in docs - http://www.yiiframework.com/doc-2.0/guide-runtime-logging.html ?

**Comment by cebe** [comment]
not sure, this is a very specific use case. Added an example to `setEnabled`: 9d854c0
