### ISSUE TITLE
Pjax full page refresh

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#14282]
### What steps will reproduce the problem?
updating by composer 2.0.11.2->2.0.12

### What do you get instead?
In 2.0.11 Pjax was reload gridview without page refresh, after updating to 2.0.12 it becomes refresh full page, increasing param `timeout` not helps
Assets cleared

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0
| Operating system | ubuntu

**Comment by cebe** [comment]
Could you come up with some example code that demonstrates the issue on a fresh install of the basic app?

**Comment by dynasource** [comment]
a page reload is likely the result of a PJAX call getting an Exception returned. Plz look in your debug toolbar or your Chrome toolbar history to see where it is caused.

**Comment by nicdnepr** [comment]
Clear project works fine, I checked my project, in console no errors, in network here is error
![0](https://user-images.githubusercontent.com/2581487/27815167-c5598d8e-608a-11e7-8157-8d107219ee0b.png)
jquery is from assets

**Comment by samdark** [comment]
Then it's something special about your code. Till you'll find out what it is exactly, unfortunately, we can't fix it.
