### ISSUE TITLE
problem 405 ajax post

### ISSUE THREAD

**Issue by matutef81** [yiisoft/yii2#14287]
Hi people, i have a problem with yii2, first, i must say that i am new with this framework, i read a lot of forums about yii  and documentation, ok,  i will try to write what is my problem (sorry, my english is so bad, i speak spanish)

1) my yii version is: yii-basic-app-2.0.12
2) i am Doing tests for see how to do thinks in yii
3) the view that contains the javascript is a partial view, in the head i write:
 <script src="/basic/web/assets/810b1d0f/jquery.js"></script>
 <script src="/basic/web/assets/82004868/yii.js"></script>
 <script src="/basic/web/assets/2996bc0d/js/bootstrap.js"></script> 

and in the begin the file:
use yii\helpers\URL;
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\web\AssetBundle;

4)  I created a single view with only a button:

the button call a javascript function:

  function  validardatos(){
                 $.ajax({               
                dataType: "JSON",
                Type: "POST",             
                data:{iddata:'888'},
                url:  php echo  Url::to(['site/json-prueba']);     // code in php, the editor hide  the url, left tags and ""                
                success: function(resultado){
                     alert(resultado)
                    },
                error: function(xhr){
                alert(xhr.readyState)

                }
              });              
            }

In the controller:

 public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,                      
                        'roles' => ['@'],
                    ],                     
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [  
                    'json-prueba' => ['POST'],   
                   // 'jsonprueba' => ['POST'],   camelCase is camel-case 
                    'logout' => ['post'],                 
                ],
            ],
        ];
    }

params.php

return [
    'adminEmail' => 'admin@example.com',
     
  'urlManager' => [
            'class' => 'yii\web\UrlManager',
            // Disable index.php
         

            'rules' => array(
                    '<controller:\w+>/<id:\d+>'              => '<controller>/view',
                    '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                    '<controller:\w+>/<action:\w+>'          => '<controller>/<action>',
            ),
        ],

];
public function actionJsonPrueba(){   
        
        /************************************/ 
        //$data = 'HOLAAAAAA';
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;       
        $data = Yii::$app->request->post("iddata");
        
        return  $data;
     }

appAsset

 */
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/site.css',
    ];
    public $js = [  
        
    ];
    public $depends = [
       'yii\web\YiiAsset',
       'yii\bootstrap\BootstrapAsset',       
    ];
}

well,  having said that:

when i see a debug chrome, i can read this:

GET http://localhost/basic/web/index.php?r=site%2Fjson-prueba&iddata=888 405 (Method Not Allowed)

why get?????? the method is post!!!

Request URL:http://localhost/basic/web/index.php?r=site%2Fjson-prueba&iddata=888
Request Method:GET
Status Code:405 Method Not Allowed
Remote Address:[::1]:80
Referrer Policy:no-referrer-when-downgrade

**Comment by Alex-Code** [comment]
Hard to see it clearly with the sporadic formatting but if the above was copy pasted from your code I'm guessing its because you have a capital 'T' on the request type for `$.ajax()`

```js
function validardatos(){
  $.ajax({
    dataType: "json",
    type: "POST",
    data: { iddata: '888' },
    url: <?= Url::to(['site/json-prueba']); ?>
    success: function(resultado) {
      alert(resultado)
    },
    error: function(xhr){
      alert(xhr.readyState)
    }
  });              
}
```

**Comment by matutef81** [comment]
halex code, first, thanks for your help!, i changed this and  the problem now is:  the alert return null value, the controller doesnt found the data "iddata" that i send via ajax  from the view :(
