### ISSUE TITLE
EmailTarget ignores `mail()` failures

### ISSUE THREAD

**Issue by rob006** [yiisoft/yii2#14296]
### What steps will reproduce the problem?

Disable `mail()` function in PHP config (or just ensure that it will return `false`). Use default configuration of `yii\swiftmailer\Mailer` and configure `EmailTarget` for errors. Log error.

### What is the expected result?

Warning that email can not be sent.

### What do you get instead?

Nothing. `swiftmailer` [swallows `mail()` errors and returns `false`](https://github.com/swiftmailer/swiftmailer/blob/v5.4.8/lib/classes/Swift/Transport/SimpleMailInvoker.php#L33-L37), but `EmailTarget` [ignores `send()` result](https://github.com/yiisoft/yii2/blob/ba0ab403b52124c941dbeb46fbd9efdc12252a5d/framework/log/EmailTarget.php#L85). So failures are just ignored.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      |  7.1.4
| Operating system | Linux

**Comment by bizley** [comment]
FileTarget throws InvalidConfigException only on file opening error - no warning for file write errors.
DbTarget also does not check if log is db inserted and similar story with SyslogTarget. 

How this warning message should be delivered?

**Comment by rob006** [comment]
I have no idea, didn't investigate this further. But I changed my configuration to use SMTP, and with invalid config I get nice warning in debug toolbar and log file:
```
[warning][yii\log\Dispatcher::dispatch] Unable to send log via yii\log\EmailTarget: Exception 'Swift_TransportException' with message 'Connection could not be established with host XXX [Connection refused #61]' 
```

So it looks doable.

**Comment by bizley** [comment]
But that's the point - you need another target configured to get the first target's error.

**Comment by rob006** [comment]
So what is the problem? I have another target, why hide this warning in that case?

**Comment by bizley** [comment]
Well, you are right. All targets should inform in case the logs can not be delivered.
