### ISSUE TITLE
An error in InputWidget's phpdoc?

### ISSUE THREAD

**Issue by evpav** [yiisoft/yii2#14294]
Added as a part of the [MaskedInput widget implementation](https://github.com/yiisoft/yii2/commit/249f90f5ee78cee47f6fcb990ae10d2a56d24e1a) the phpdoc of the InputWidget says that if it is associated with a data model and an attribute, the name and the value will be generated automatically. But this is only true for the MaskedInput widget itself, as far as I can see (MaskedInput::run). If it really is an error this currently misleading info should be moved into the MaskedInput's phpdoc (which curiously doesn't say anything about this feature).
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | master
| PHP version      | 
| Operating system |

**Comment by cebe** [comment]
The described behavior is implemented by choosing `Html::activeInput()` vs. `Html::input()` not sure if there is a good way to move the functionality to the base class. https://github.com/yiisoft/yii2/blob/c9347b0a5702ecd69c3a596bebac174a4dd218b4/framework/widgets/MaskedInput.php#L127-L131

**Comment by cebe** [comment]
Found a solution, see my PR.

**Comment by evpav** [comment]
seems to be a better solution, thank you @cebe

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/pull/14441#issuecomment-315127527

**Comment by samdark** [comment]
I suggest renaming to less common name... `renderInputHtml` or something alike...

**Comment by SilverFire** [comment]
Reverted for now: b0162d3a48150be2394dbd30147b3019a433b3a2
