### ISSUE TITLE
Unique validation of array of new models (validateMultiple)

### ISSUE THREAD

**Issue by esl51** [yiisoft/yii2#14291]
### What steps will reproduce the problem?
1. Create ActiveRecord model with "unique" rule of "field"
2. Create array of two new objects of model where "field" values are identical (or use loadMultiple from POST)
3. Call validateMultiple on this array

### What is the expected result?
"Not unique" error on "field" in second model

### What do you get instead?
Nothing

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.4
| Operating system | Debian 8

**Comment by Alex-Code** [comment]
Bit of an awkward one to get around.
The validator compares to existing data in the db not what might be loaded in memory.

I wonder if a transaction would work here.

```php
$transaction = Yii::$app->db->beginTransaction();
$models = [];//Array of models
$fail = false;
if (Model::loadMultiple($models, Yii::$app->request->post())) {
  foreach ($models as $model) {
    if (!$model->save()) {
      $fail = true;
      $transaction->rollBack();
      break;
    }
  }
  if (!$fail) {
    $transaction->commit();
  }
}
```

**Comment by esl51** [comment]
@Alex-Code thank you, good workaround.

**Comment by samdark** [comment]
I don't think it's possible to solve it at validator level.
