### ISSUE TITLE
Recent change in UniqueValidator.php breaks code

### ISSUE THREAD

**Issue by karpy47** [yiisoft/yii2#14304]
I've been using the workaround described in #9014 by @Faryshta to validate uniqueness of a username case insensitive. This stopped working recently and now generates an MySQL error like this...

```
Next exception 'yii\db\Exception' with message 'SQLSTATE[42000]:
Syntax error or access violation: 1064 You have an error in your SQL
syntax; check the manual that corresponds to your MySQL server
version for the right syntax to use
near '[[lower(username)]]='myname'))' at line 1
The SQL being executed was:
SELECT EXISTS(SELECT * FROM `user`
WHERE (`user`.[[lower(username)]]='myname'))' in 
```

Seems at a quick glance like the changes introduced to fix  #14161, #14150 is causing it.

Best would be if issue #9014 was solved to skip the workaround.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |   5.6.30
| Operating system | Debian

**Comment by karpy47** [comment]
Solved it by using the filter option, like this:

    public function getUsernameLowercase()
    {
        return strtolower($this->username);
    }
 
    public function rules()
    {
        return [['username'], 'unique', 'filter' => function ($query) {
            $query->orWhere(['lower(username)' => $this->getUsernameLowercase()]);
        }];
    }

Still not obvious for a use case that probably is not unusual (checking that user names are unique when case insensitive).

**Comment by samdark** [comment]
Please check if https://github.com/yiisoft/yii2/issues/14340 fixes your issue.

**Comment by karpy47** [comment]
Yes, that solved the issue. Thanks.
