### ISSUE TITLE
Prevent ArrayMap to grouping by id

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [yiisoft/yii2#14312]
### What steps will reproduce the problem?
Basically i have a data that came from query with union all query. 
The pieces of array like this 👍 
 `print_r($listNoEstimate);`
` [738] => Array
        (
            [id] => 2267
            [no_surat] => E2453
            [level] => B
        )

    [739] => Array
        (
            [id] => 2493
            [no_surat] => E2468
            [level] => A
        )

    [740] => Array
        (
            [id] => 2493
            [no_surat] => E2468
            [level] => B
        )`
### What is the expected result?
if we use arraymap like this : 
 `$mapListNoEstimate = ArrayHelper::map($listNoEstimate, 'id', function ($model, $value) {
        return $model['no_surat'] . ' - ' . $model['level'];
    });`

   `[2267] => E2453 - B
    [2493] => E2468 - B`

It seems, when ID is same, it will be converting into one element

| Q                      | A
| ---------------- | ---
| Yii version        | 2.0.?
| PHP version     |  7.0
| Operating system |

**Comment by klimov-paul** [comment]
This is expected behavior.

**Comment by ahmadfadlydziljalal** [comment]
So, What best way to prevent this grouping in Yii2 ?
