### ISSUE TITLE
The model code which gii generated  was not perfect

### ISSUE THREAD

**Issue by taobig** [yiisoft/yii2#14311]
### What steps will reproduce the problem?
(MySQL 5.7.18)Table struct:

CREATE TABLE `order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  **`name` varchar(64) NOT NULL,
  `sn` varchar(20) NOT NULL,**
  `status` int(11) NOT NULL,
  ...
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

I use gii to generate model.
See **name** and **sn** fileds as below:

### What is the expected result?
```
 public function rules()
    {
        return [
            [['status'], 'required'],
            [['name', 'sn'], 'required', 'skipOnEmpty' => true],
            [['status'], 'integer'],
            [['name'], 'string', 'max' => 64],
            [['sn'], 'string', 'max' => 20],
        ];
    }
```
### What do you get instead?
```
public function rules()
    {
        return [
            [['name', 'sn', 'status'], 'required'],
            [['status'], 'integer'],
            [['name'], 'string', 'max' => 64],
            [['sn'], 'string', 'max' => 20],
        ];
    }
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0

**Comment by bizley** [comment]
How gii should guess that you want these two attributes to be set with `skipOnEmpty`? It's up to you to modify generated files according to your needs.

**Comment by taobig** [comment]
The field is "NOT NULL", so it `can` be filled with an empty string.
