### ISSUE TITLE
Why is hasOne and hasMany array key/value order opposite?

### ISSUE THREAD

**Issue by davidjeddy** [yiisoft/yii2#14313]
### What steps will reproduce the problem?
n/a
### What is the expected result?
k/v order to be similar
### What do you get instead?
k/v order is opposite when comparing hasOne Vs hasMamany

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0+
| Operating system | Linux

```
hasOne()
* 
* public function getCountry()
* {
*     return $this->hasOne(Country::className(), ['id' => 'country_id']);
* }
*

hasMany()

*
* public function getOrders()
* {
* return $this->hasMany(Order::className(), ['customer_id' =>; 'id']);
* }
*
Notice the opposite order?
```

**Comment by bizley** [comment]
This is intended. From the [Guide](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#relational-data):
> An easy rule to remember this is, as you see in the example above, you write the column that belongs to the related Active Record directly next to it. You see there that `customer_id` is a property of `Order` and `id` is a property of `Customer`.

This actually makes it easier to remember.

**Comment by jlorente** [comment]
This isn't an Issue and maybe you should use the forums to ask this kind of things. But answering your question, the value of the array is the property of the model where you are declaring these methods and the key of the array is the property of the related model.

**Comment by davidjeddy** [comment]
I understand the implementation, just seems backwards. I was expecting a systematic approach similar to `[ThisAR->property => OtherAt->property]`. Eh, moving on.
