### ISSUE TITLE
Introduce configuration manager

### ISSUE THREAD

**Issue by sonrac** [yiisoft/yii2#14314]
### Constant definition usages
Why are you usages constants ?  It can put in a separate configuration of the application environment.

I mean, something like this
```php
/**
 * Class EnvConfig
 * Environment config for Yii constants
 */
class EnvConfig
{
    /**
     * @var null|EnvConfig
     */
    protected static $instance = null;

    protected $_configs = [
    ];

    /**
     * EnvConfig constructor.
     *
     * @param array $config Environment config variables
     */
    private function __construct($config = [])
    {
        $config = is_array($config) ? $config : [];

        $this->_configs = array_merge([
            'env'                          => 'prod',
            'debug'                      => false,
            'envProd'                   => true,
            'envDev'                    => false,
            'envTest'                    => false,
            'enableErrorHandler' => true,
        ], $config);

        foreach ($config as $name => $value) {
            $this->_configs[$name] = $value;
        }
    }

    /**
     * Get env-config instance
     *
     * @param array $config Environment config variables
     *
     * @return static
     */
    public static function getInstance($config = [])
    {
        return static::$instance ?: static::$instance = new static($config);
    }

    /**
     * Get value from config
     *
     * @param string $name    Env variable name
     * @param mixed  $default Default value for variable
     *
     * @return mixed|null
     */
    public function getValue($name, $default = null)
    {
        return isset($this->_configs[$name]) ? $this->_configs[$name] : $default;
    }

    public function setValue($name, $value)
    {
        return $this->_configs[$name] = $value;
    }

}

/**
 * Get environment config option value
 *
 * @param string $name    Env config name
 * @param mixed  $default Default value
 * @param array  $config  Initial config variables
 *
 * @return mixed|null
 */
function yiiEnv($name, $default = null, $config = [])
{
    $config = count($config) ? \yii\EnvConfig::getInstance($config) : \yii\EnvConfig::getInstance();
    return $config->getValue($name, $default);
}

/**
 * Set environment config option
 *
 * @param string $name    Env config name
 * @param mixed $value   New value
 * @param array  $config  Initial config variables
 *
 * @return mixed|null
 */
function yiiSetEnv($name, $value, $config = [])
{
    $config = count($config) ? \yii\EnvConfig::getInstance($config) : \yii\EnvConfig::getInstance();
    return $config->setValue($name, $value);
}

/**
 * Check test environment
 *
 * @return bool
 */
function yiiIsTest()
{
    return yiiEnv('envTest', false);
}

/**
 * Check development environment
 *
 * @return bool
 */
function yiiIsDev()
{
    return yiiEnv('envDev', !yiiIsProd() && !yiiIsTest());
}

/**
 * Check production environment
 *
 * @return bool
 */
function yiiIsProd()
{
    return yiiEnv('envProd', false);
}
```

So much easier to manage the application and change the environment if necessary. When using constants, this can not be done. 
From this, the meaning of boot-providers is almost lost, which sometimes should include debug-bar for developer's on production project (let's say by having cookies, or some auxiliary information other than IPs) if necessary, for example.
Is the option of changing constants the configuration of the environment? Sometimes it's very uncomfortable!

**Comment by pana1990** [comment]
I think core developers could include something like [yii2-config-kit](https://github.com/2amigos/yii2-config-kit) in yii2.1 and join basic and advanced templates in a single app.

What do you think about it?

**Comment by sonrac** [comment]
@pana1990 It does not metter which package usage. 
All that is important is to let the environment change when needed. In the case of constants, this is not possible, and you need to initialize everything before require 'vendor / yiisoft / yii2 / Yii.php';

But in this case it is worth noting that downloading in addition to vendor / autoloader.php
also Yii ... What for?
You can add some file to the autoload section, which will be automatically require from composer when autoloader.php will be required.

**Comment by klimov-paul** [comment]
> Why are you usages constants ? It can put in a separate configuration of the application environment.

Actually I don't get it: why do you need to change such things as debug mode or application environment?
Can you please provide a description of use case, which requires switching `YII_ENV` from `dev` to `prod` in runtime?

**Comment by klimov-paul** [comment]
In general we can use static fields at `yii\BaseYii` (e.g. just `\Yii`) class instead of constants, it will make thier setup to be following:

```php
Yii::$debug = true;
Yii::$env = true;
```

The drawback is you can not setup those values before loading `Yii` class, which sometimes is not desireable.

Also such policy produces a debatable practice: debug mode and environment must be a gloabl public fields, which means thier values can be changed at any time at any place, producing unexpected results.
In general: in case application is running in 'test' mode - it should remain in test mode during its whole execution.

**Comment by samdark** [comment]
In general, I think we need a configurator which could be used to read values from files, environmental variables and code bug I agree with @klimov-paul that it's not really clear why a setting like debug mode should be changed in runtime at all. @sonrac would you please clarify about your use cases?

**Comment by armpogart** [comment]
As a side suggestion it would be also very helpful to include [phpdotenv](https://github.com/vlucas/phpdotenv) in Yii 2.1 by default and parse main config values through it as it becomes very common to change application configuration through environment variables (for example in docker containers), we are heavily using this library in our Yii setups.

**Comment by sonrac** [comment]
@samdark 
I'm developer and on master project I want see debug bar for visual analyze profile data, but for another users need enable production mode. How I can do it now ?
Only define constant with some custom config before include Yii. Bootstrap Yii way does not fit. 

For most project to bypass this and restore environment with all needed settings I use custom way - configuration file and initial all constants from https://github.com/sonrac/yii2-environment-config-formatter. In component I'm does not use YII_ENV and other constant. 

> The drawback is you can not setup those values before loading Yii class, which sometimes is not desireable

**Comment by samdark** [comment]
You should not use debug toolbar in production. If you absolutely need profiling for totally tricky production-only performance issues, something like xhprof or blackfire are much better options. Debug toolbar itself changes the picture quite significantly is fine only for relatively obvious things which should not ever reach production.

**Comment by sonrac** [comment]
Require additional file `Yii` is best way too?
But without `require` and autoloading class constants are defined from it or will be does not exists otherwise. Config option use conveniently. 
And there the programmer decides further what to use, whether to change the environment - everything associated with this in the future and problems of the programmer who does this, but there can be many reasons why this may be necessary, most often due to the fast fixing of the master, on prod data that is not caught on the test and copy the database to itself for too long.

**Comment by klimov-paul** [comment]
You can declare `YII_DEBUG` and `YII_ENV` using getenv() if you want:

```php
define('YII_DEBUG', getenv(...));
define('YII_ENV', getenv(...));
```

**Comment by klimov-paul** [comment]
Relates #126

**Comment by dynasource** [comment]
its not a bad idea to have the ENV more organized in the Application templates

**Comment by SilverFire** [comment]
https://github.com/hiqdev/composer-config-plugin/

**Comment by ptheofan** [comment]
@sonrac regarding debug env on live, if you really need to go there, an easy workaround would be to

1. check your IP against $_SERVER and enable debug if it matches
2. check against some cookie you can set on your browser

However, you need to remember to
1. deploy the toolbar on live move it to require from require-dev
2. invalidate opcache if you intend to set an IP on yourwhen you change the IP in a php file

**Comment by samdark** [comment]
Closing since we're going to use composer-based configurator in 3.0.
