### ISSUE TITLE
Support for hiding html tag if empty

### ISSUE THREAD

**Issue by JoeSimsen** [yiisoft/yii2#14317]
In my site I often draw ::tags with content from php. If this content is empty, the tag should be hidden as well, which requires an extra if statement every time. 

`echo $value ? Html::tag("p", $value) : "";`

If the following is added to the tag function is changed to the following, the function itself will allow hiding the tag, while also allowing drawing empty tags:

```
public static function tag($name, $content = '', $options = [])
...
        if ($content === null || $content === false) {
            return '';
        }
...
```

**Comment by klimov-paul** [comment]
This can not accepted as empty tags can be used for some HTML elements composition. For example: Bootstrap 2 used empty tag with classes fro icon rendering:

```
<i class="icon-ok"></i>
```

**Comment by JoeSimsen** [comment]
@klimov-paul which is why, by default, this is still possible. Html::tag('i') would draw that tag, while Html::tag('i', null) would draw nothing
