### ISSUE TITLE
"afterValidateAttribute" attribute.value is empty 

### ISSUE THREAD

**Issue by sreenadh** [yiisoft/yii2#14318]
### What steps will reproduce the problem?

```javascript
$('body').on('afterValidateAttribute', "form", function(event, attribute, messages) {
    console.log(attribute.value);
});
```

### What is the expected result?
Attribute's value

### What do you get instead?
Empty value

### Additional info
afterValidateAttribute event is triggered before setting the value at line 726
attribute.value = getValue($form, attribute);

https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L705
https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L726

What about calling the trigger after setting attribute value. This would enable the checking of form.find(".has-error").length

**Comment by samdark** [comment]
It makes sense to adjust it.
