### ISSUE TITLE
Should Transaction.Commit check the return value of pdo->commit()?

### ISSUE THREAD

**Issue by shenli** [yiisoft/yii2#14322]
I found that in Tranaction.php, the return value of commit is ignored. But according to the document of pdo, commit() will return true or false. So is it right to ignore the return value?

In http://php.net/manual/en/pdo.commit.php ：
> Returns TRUE on success or FALSE on failure.

In https://github.com/yiisoft/yii2/blob/master/framework/db/Transaction.php#L157 the return value of commit() is ignored.
>  $this->db->pdo->commit();

Please let me know if I do not make it clear. Thanks!

**Comment by shenli** [comment]
Is there any update about this issue? Thanks!

**Comment by samdark** [comment]
It's planned to deal with it closer to 2.0.14 release. If you have time for a pull request with unit tests, it has a chance to get into 2.0.13.

**Comment by shenli** [comment]
@samdark I am not familiar with php. But I would like to fix it.

**Comment by cebe** [comment]
FYI: https://bugs.php.net/bug.php?id=66528

**Comment by cebe** [comment]
Not sure how we could trigger `commit()` to return false, probably need to dig into PDO source code.

**Comment by samdark** [comment]
https://stackoverflow.com/questions/23851360/pdocommit-success-or-failure

**Comment by samdark** [comment]
https://github.com/php/php-src/blob/master/ext/pdo/pdo_dbh.c#L602

**Comment by samdark** [comment]
Seems it's not a good idea to check it.
