### ISSUE TITLE
Is there a plan to support the Yar RPC framework?

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#14329]
Yar is a RPC framework which aims to provide a simple and easy way to do communication between PHP applications It has the ability to concurrently call multiple remote services.

php website: http://php.net/manual/zh/yar.examples.php

I am eager to have the perfect support for the framework, do you have the exact timetable?

**Comment by samdark** [comment]
No, there's no plan to support it by core team members. If anyone would implement it and maintain it we don't mind promoting it.
