### ISSUE TITLE
BreadCrumbs

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#14330]
### What steps will reproduce the problem?
Trying to make single breadcrumb `item` not encoded from XSS. I have HTML in `label` and I would like to display it correctly. 
 
I know there is [this property](http://www.yiiframework.com/doc-2.0/yii-widgets-breadcrumbs.html#$encodeLabels-detail), but as I understand, it turns off for encoding for all breadcrumb items (which is not the case for me).

I believe, this feature would be useful for others as well.   

### What is the expected result?
I would like to do something like the following on `views`: 
```php
// P.s. in my case generateShortSummary() contains some HTML tags
$this->params['breadcrumbs'][] = ['label' => $model->generateShortSummary(), 'encodeLabel' => false];
```

### What do you get instead?
Plain text with encoded HTML tags. 

Sample result of  `generateShortSummary()` after it was encoded breadcrumbs:
```
<span style="color: #357bfb">FROM</span> to <span style="color: #9692fa">TO</span>
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04

**Comment by samdark** [comment]
It is already supported. See http://www.yiiframework.com/doc-2.0/yii-widgets-breadcrumbs.html#$links-detail
