### ISSUE TITLE
How to override/extend yii\web\AssetBundle - DI

### ISSUE THREAD

**Issue by sreenadh** [yiisoft/yii2#14333]
How to override the function "registerAssetFiles" in yii\web\AssetBundle using dependency injection.

I've created a component named AssetBundle in backend\components\ and then added the following code in the index.php.

`\Yii::$container->set('yii\web\AssetBundle', 'backend\components\AssetBundle');`

```php
namespace backend\components;

class AssetBundle extends \yii\web\AssetBundle
{
    public function __construct()
    {
    	die('s');
    }
}
```

But it's not working. The purpose is to set filename as  "name" attribute for css and js files.

**Comment by sreenadh** [comment]
Right now I fulfilled my requirement by using classMap. Copied the yii\web\AssetBundle to components and made the customization required.

index.php:
Yii::$classMap['yii\web\AssetBundle'] = '../components/AssetBundle.php';

**Comment by samdark** [comment]
Classmap is the way to go. AssetBundle isn't used as an instance but instead is inherited so it could not be replaced via DI container.
