### ISSUE TITLE
Event beforeRequest not working

### ISSUE THREAD

**Issue by Portaflex** [yiisoft/yii2#14342]
I have this in config/web.php

```php
'on beforeRequest' => function ()
        {
            if (! Yii::$app->basePath && ! isset(Yii::$app->session['userId']))
            {
                return Yii::$app->response->redirect('/login');
            }
        },
```

### What steps will reproduce the problem?

Not redirecting.

Thanks.

| Q                | A
| ---------------- | ---
Apache/2.4.10 (Debian)
Yii Framework/2.0.12
PHP 5.6

**Comment by samdark** [comment]
Because at that stage response isn't yet created by the normal flow you have to terminate application explicitly with:

```php
```

**Comment by Portaflex** [comment]
Ok. Thanks.

**Comment by BlackstarMC97** [comment]
Hello i have the same problem, here is my code : 
`'on beforeRequest' => function (){
            $Blackstar = 'Look';
            //session_start();
            Yii::$app->end();
        },`
