### ISSUE TITLE
JOIN different quotes

### ISSUE THREAD

**Issue by VokaMut** [yiisoft/yii2#14344]
### What steps will reproduce the problem?
php:
Vendors::find()->rightJoin('actions', ['actions.vendor_id' => 'vendors.id'])
sql:
SELECT count(*) FROM \`vendors\` RIGHT JOIN \`actions\` ON \`actions\`.\`vendor_id\`='vendors.id'
result:
**0** **// Not true**

# **BUT:**
php:
Vendors::find()->rightJoin('actions', 'actions.vendor_id = vendors.id')
sql:
SELECT count(*) FROM \`vendors\` RIGHT JOIN \`actions\` ON actions.vendor_id=vendors.id
result:
**1** // Right

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6.29
| Operating system | Windows 7 x64

**Comment by Renkas** [comment]
You need to wrap the value part in `yii\db\Expression`
```php
Vendors::find()->rightJoin('actions', ['actions.vendor_id' => new yii\db\Expression('vendors.id')])
```
