### ISSUE TITLE
Can not span ActiveForm::begin()/end() calls over several content blocks

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#14354]
### What steps will reproduce the problem?

Try to have calls to `ActiveForm::begin()` and `ActiveForm::end()` in different [content blocks](http://www.yiiframework.com/doc-2.0/guide-structure-views.html#using-blocks).

In my use case I have a layout file for modals. Content for different areas can be passed as blocks to the layout file. As I have a submit button in the footer, the form tags must span the whole modal content.

```php
<?php $this->context->layout = 'modal' ?>

<?php $this->beginBlock('content-start') ?>
    <?php $form = ActiveForm::begin() ?>
<?php $this->endBlock() ?>

    <?= $form->field($model, 'lastName') ?>
    <?= $form->field($model, 'firstName') ?>

<?php $this->beginBlock('footer') ?>
    <button type="submit">Save</button>
<?php $this->endBlock('footer') ?>

<?php $this->beginBlock('content-end') ?>
    <?php ActiveForm::end(); ?>
<?php $this->endBlock() ?>
```

### What is the expected result?

It should work.

### What do you get instead?

Invalid Call – yii\base\InvalidCallException

Expecting end() of yii\bootstrap\ActiveForm, found yii\widgets\Block
1. in /var/www/vendor/yiisoft/yii2/base/Widget.php at line 115

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.16
| Operating system | Linux

Actually I don't expect an easy fix for this. But maybe I'm missing something and someone sees a workaround.

For completeness, here's the basic `modal.php` layout file:

```php
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <?= isset($this->blocks['content-start']) ? $this->blocks['content-start'] : '' ?>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>
        <div class="modal-body">
            <?= $content ?>
        </div>
        <div class="modal-footer">
            <?php if (isset($this->blocks['footer'])): ?>
                <?= $this->blocks['footer'] ?>
            <?php else: ?>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Save
                </button>
            <?php endif; ?>
        </div>
        <?= isset($this->blocks['content-end']) ? $this->blocks['content-end'] : '' ?>
    </div>
</div>
```

**Comment by klimov-paul** [comment]
Same as #11687

**Comment by mikehaertl** [comment]
@klimov-paul Thanks for the pointer. So there's no solution.

Minor nitpick, though: The issue you mentioned was about spanning `begin()` and `end()` calls over several files. That's not the case in my example. It's rather that blocks are implemented as widgets internally and thus my example results in wrongly nested widgets. Technically I don't really see a reason why you shouldn't be able to do, what I tried. But I also see no simple way how to fix this in the current framework implementation.

**Comment by klimov-paul** [comment]
This is the price for implementing #11203.
Whenever output buffer is involved - form breaks it.

I have to create another ActiveForm widget to support such functionality.
