### ISSUE TITLE
Connection isActive does not return valid value

### ISSUE THREAD

**Issue by sztyvny** [yiisoft/yii2#14359]
### What steps will reproduce the problem?
1. Make long running script that checks connection status (`Yii::$app->db->isActive`) and then tries to get something from database.
2. Make your script sleep for enought time for you to restart db server.
3. Restart db server while script is running.

### What is the expected result?
I expected `Yii::$app->db->isActive` to be false after restarting db server.

### What do you get instead?
I got true on `Yii::$app->db->isActive` and my getter from database failed with `db\Exception`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.0.20-2~ubuntu16.04.1+deb.sury.org+1
| Operating system | Linux Mint 18.1

Shouldn't `isActive` checks something more than only if pdo's object isn't null, should it?

Quote from docs.
> To establish a DB connection, set [[dsn]], [[username]] and [[password]], and then call [[open()]] to connect to the database server. The current state of the connection can be checked using [[$isActive]].

Well it is kinda confusing.

**Comment by samdark** [comment]
https://stackoverflow.com/questions/26004807/pdo-how-to-check-if-connection-is-active-for-real

**Comment by dynasource** [comment]
makes sense to me

**Comment by matias-yii** [comment]
**Proposal:** 
public function getIsActive()
    {
        if ($this->pdo == null) {
            return false;
        }
        try {
            $this->pdo->getAttribute(\PDO::ATTR_SERVER_INFO);
            return true;
        } catch (\Exception $ex) {
            return false;
        }
    }

**Comment by samdark** [comment]
That won't work because it won't throw an exception but [return a value](https://stackoverflow.com/questions/21595402/php-pdo-how-to-get-the-current-connection-status/21595506) (and that depends on the database used). We can't really detect the state reliably.

Overall I don't think we should try fixing it. See https://github.com/yiisoft/yii2/issues/12634
