### ISSUE TITLE
Suggested: Check level after exec closure of Connection::transaction

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/yii2#14357]
```php
            $result = call_user_func($callback, $this);
            if ($transaction->isActive && $transaction->level === $level) {
                $transaction->commit();
            }
```
If by chance somewhere inside the closure forget to close the transaction, it is possible that the user will receive a successful response, but nothing will be saved, in some situations this can be critical. It is suggested when you exit the closure, check the transaction level and if it is more than expected or less than 1 (the user himself could complete or roll back the transaction), throw an exception. It is expected to treat the transaction call as a separate isolated code cycle and it should not shut down transactions from the outside or close transactions created from outside.

Если случайно где то внутри  замыкания забыть закрыть транзакцию, возможна ситуация что пользователь получит успешный ответ, но ничего не сохранится, в каких то ситуациях это может быть критично. Предлагается при выходе из замыкания, проверять уровень транзакции и если он больше ожидаемого или меньше чем на 1 (пользователь сам мог завершить или откатить транзакцию), бросаем исключение. Ожидаемо воспринимать вызов transaction как отдельный изолированный цикл кода и он не должен закрывать транзакции извне или закрывать транзакции созданные извне.

**Comment by cebe** [comment]
do you mean to introduce an else branch here: 

https://github.com/yiisoft/yii2/blob/fadeb5d2b458305dc7fba390fb4478252c59b62e/framework/db/Connection.php#L730

and fail if the level does not match?

**Comment by mj4444ru** [comment]
yes. and in catch block close all transaction to begin level.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
