### ISSUE TITLE
关于updateAttributes调用问题

### ISSUE THREAD

**Issue by qq71151461** [yiisoft/yii2#14361]
有个特殊需求，相同的AR类，查找多次，并先后updateAttributes
$model1 = ModelUser::findOne(1);
$model2 = ModelUser::findOne(1);
初始的attr1字段为0
$model1->attr1 = 1;
$model1->updateAttributes(['attr1']);//执行成功

$model2->attr1 = 0;
$model2->updateAttributes(['attr1']);//执行失败

最终数据库里attr1 的值为1。

原因是updateAttributes里调用了getDirtyAttributes方法，误认为$model2里的attr1，没有修改，直接跳过。现在只能用static::updateAll()去执行，请问该如何解决更好！！

**Comment by samdark** [comment]
There's no plan to introduce identity map in the core because it may introduce a whole set of new issues. It's available as an extension though: https://github.com/yiister/yii2-mappable-ar
