### ISSUE TITLE
How customize listview pager tag?

### ISSUE THREAD

**Issue by tomoat** [yiisoft/yii2#14363]
I want to change the pager `ul>li` tag to `div>a`

![image](https://user-images.githubusercontent.com/7428698/27650236-ed1be564-5bf9-11e7-98e5-3a5d425ea3c3.png)

![image](https://user-images.githubusercontent.com/7428698/27649669-0f9b138c-5bf8-11e7-963c-c693c7823c06.png)

**Comment by dynasource** [comment]
as shown by https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php#L215, this `ul` is hardcoded
