### ISSUE TITLE
Cannot read property 'filterSelector' of undefined

### ISSUE THREAD

**Issue by swati-clarion** [yiisoft/yii2#14362]
I have a simple gridview page to list all orders. I added a checkbox column to select rows. After adding checkbox column, the search feature stopped working.

I started getting Cannot read property 'filterSelector' of undefined jquery error in console. When I comment this checkbox column , search again starts working.

Here is gridview code:
```php
<?= GridView::widget([
'dataProvider' => $dataProvider,
'filterModel' => $searchModel,
'columns' => [
	[
		'class' => 'yii\grid\CheckboxColumn', 'checkboxOptions' => function($model) {
			return ['value' => $model->id];
		},
	],
	['class' => 'yii\grid\SerialColumn',
	'contentOptions' => ['style' => 'width:20px;'],				
	],            
	[
		'attribute'=>'track_number',						
		'contentOptions' => ['style' => 'width:80px;'],				
	],  
	[
		'attribute'=>'shipping_id',
		'filter'=>$locationFilter,
		'value' => function($data) {
			$shipping = new ShippingAddress();
			$data = $shipping->getLocationDetails($data->shipping_id);
			return $locString = $data['type']."<br>".$data['name']."<br>".$data['address'];				  
		},
		'format' => 'raw',
		'contentOptions' => ['style' => 'width:220px;'],				
	], 			
	[
		'attribute'=>'order_to',
		'filter'=>$adminIds,				
		'value' => 'OrderToName',
		'contentOptions' => ['style' => 'width:140px;'],	
	],
	[
		'attribute'=>'order_email',				
		'contentOptions' => ['style' => 'width:230px;'],	
	],	         		
			 
	  
	// 'description',
	//'date_created',
	// 'date_updated',
	[
		'attribute'=>'date_created',
		'filter'=> DatePicker::widget([
			'model' => $searchModel,
			'attribute' => 'date_created',
			'template' => '{addon}{input}',
				'clientOptions' => [
					'autoclose' => true,
					'format' => 'yyyy-mm-dd',
					'style'=>'max-width: 120px;',
				]
		]),
		'contentOptions' => ['style' => 'width:120px;'],
	],
	[
		'attribute'=>'status',
		'filter'=>array("Pending"=>"Pending","Completed"=>"Completed","Cancelled"=>"Cancelled"),		
		'contentOptions' => ['style' => 'width:100px;'],				
	],

	
	$actionCol = ['class' => 'yii\grid\ActionColumn',
		'filter' => Html::a('Reset', ['/order/index'], ['class'=>'btn btn-primary'])." ".
		 Html::a('Hide Selected', [''], ['id' => 'hide_selected','class'=>'btn btn-danger']),
		'template' => '<div align="left">{view}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{cancel}</div>&nbsp;<br><div align="center">{Resend}</div>',
		'buttons' => [		
			'cancel' => function ($url, $data) {   						
				//return Html::buttonInput('Delete', ['id' => $id ,'title' => $name, 'class'=>'btn btn-danger','onclick' => 'javascript:deleteItem(this.id,this.title);' ]) ;						
				return $data->status == 'Pending' ? Html::a('Cancel', ['cancel', 'id' => $data->id], [
					'class' => 'btn btn-danger',
					'data' => [
						'confirm' => 'Are you sure you want to cancel this Order?',
						'method' => 'post',
					],
				]) : '';
			},
			'Resend' => function ($url, $data) {   						
				//return Html::buttonInput('Delete', ['id' => $id ,'title' => $name, 'class'=>'btn btn-danger','onclick' => 'javascript:deleteItem(this.id,this.title);' ]) ;						
				return Html::a('Resend Order', ['resend', 'id' => $data->id], [
					'class' => 'btn btn-warning',
					'data' => [
						'confirm' => 'Are you sure you want to place same order again to same Admin?',
						'method' => 'post',
					],
				]); 
			}
		],
	],	
	
],
]); ?>
```

Here is complete error:
Cannot read property 'filterSelector' of undefined
Uncaught TypeError: Cannot read property 'filterSelector' of undefined
    at jQuery.fn.init.applyFilter (yii.gridView.js:93)
    at HTMLInputElement.<anonymous> (yii.gridView.js:82)
    at HTMLDocument.dispatch (jquery.js:4732)
    at HTMLDocument.elemData.handle (jquery.js:4544)

**Comment by dynasource** [comment]
what happens if you set the $filterSelector property in GridView for stricter matching on the filters?

**Comment by swati-clarion** [comment]
I was going to add jquery code to get selected rows. But I have not yet added that and started getting this error on search. 

How to set the $filterSelector property in GridView for stricter matching on the filters? Can you please guide. I will try.

**Comment by dynasource** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L221

**Comment by swati-clarion** [comment]
Yes, this was a bug. Nothing i tried could make search filter and CheckboxColumn work together simultaneously. 

So, I removed the checkbox column and added my custom code to make this working. 

I added following column in gridview:
[
				'attribute'=>'is_hidden',
				'header' => Html::checkbox('select_all', false, ['id'=>'select_all','label' => false]),
				'filter'=> false,
				'value' => function($data) {
					return  Html::checkbox('is_hidden[]', false,['class'=>'checkbox1','value' => $data->id,'label' => false]);				  
				},
				'format' => 'raw',
				'contentOptions' => ['style' => 'width:20px;'],				
			], 	

And added following jquery code to get selected rows and check/uncheck all checkboxes:
<?php  $this->registerJs("		
       
		  $(document).ready(function() {
				
				//hide selected rows
				
				$('#hide_selected').click(function() {
					
				    //var keys = $(this).parents('#w0').yiiGridView('getSelectedRows');
					
					var selecteditems = [];
					$('.grid-view').find('input:checked').each(function (i, ob) { 
						selecteditems.push($(ob).val());
						//alert($(ob).val());
					});

					//alert(selected);
					$.ajax({
					   type     :'POST',
					   cache    : false,
					   url: 'index.php?r=order/hide',
					   //dataType: 'json',
					   data: {
						   arrId: selecteditems,
						},
					   success: function(data) {						  
						  $.pjax.reload({container:'#orderGrid', async:false});  //Reload GridView
					   },
					   error: function (exception) {
							alert(exception);
						}
					});				
		      });
		  
		    //select/unselect all
			$('#select_all').on('change', function() {
				if (!$(this).is(':checked')) {
					$('.checkbox1').prop('checked', false);   
				} else {
					$('.checkbox1').prop('checked', true);
				}
		   }); 

        });		
  "); 	
?>
