### ISSUE TITLE
[yii\db\SchemaBuilderTrait] timestamp precision does not seem to work

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#14367]
I am trying to do Mysql timestamp field with precision of 4

### What steps will reproduce the problem?
Create a migration with field timestamp with precision

### What is the expected result?
You get timestamp field which can hold some microseconds as well

### What do you get instead?
You get timestamp field which cannot hold any microseconds

### Additional info

Mysql version: 5.6.35

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  5.6.30
| Operating system | Ubuntu 17.04

**Comment by samdark** [comment]
What's the field type you've got?

**Comment by mikk150** [comment]
timestamp without any precision

**Comment by cebe** [comment]
can you please point to the mysql documentation related to this feature? When we implemented db layer of Yii, MySQL did not support any precision on timestamp value.

**Comment by mikk150** [comment]
https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

**Comment by cebe** [comment]
thanks, need to check if we can support that without breaking BC with old MySQL versions...

**Comment by amkoro** [comment]
I confirm this issue. In my case DATETIME(6) works only when I'm define this in raw format.
This format is not working:
`'changed' => $this->dateTime(6)->null()`
but dateTime() method accepts precision as argument
