### ISSUE TITLE
[ENH] Table Widget

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#14373]
Extract to #11415 

Support format cell to custom display: 

- [ ] Support ASCII colors.
- [ ] Support rowspan.
- [ ] Support colspan.
- [ ] Support justify text (left, center, right).
- [ ] Support Header and Footer with formatter options
- any more?

Link to help http://symfony.com/doc/current/components/console/helpers/table.html

**Comment by njasm** [comment]
the key here is to port the feature?

**Comment by samdark** [comment]
Yes. To add some features to console table widget.

**Comment by pana1990** [comment]
i am busy :(, do you want @njasm try it?

**Comment by Insolita** [comment]
Footer support(optionally), header and footer formatter options  (after implements ascii color)

**Comment by pana1990** [comment]
@Insolita added, thanks ;)

**Comment by Insolita** [comment]
hmm.. and may be first column row formatter options :-) it`s from my https://github.com/Insolita/yii2-codestat experiense

**Comment by samdark** [comment]
Won't be implemented in 2.0.
