### ISSUE TITLE
Method name same as Validator's

### ISSUE THREAD

**Issue by svit-ws** [yiisoft/yii2#14370]
### What steps will reproduce the problem?
In my search model I have rule with core validator as Closure:
```php
    public function rules()
    {
        return [
            ...
            [['phone'], 'filter', 'skipOnEmpty' => true, 'filter' => function ($value) {
                return preg_replace('/[^0-9]+/', '', $value);
            }],
        ];
    }
```
and method with the same name:
```php
    private function filter()
    {
...
    }
```

### What do you get instead?
Setting unknown property: yii\validators\InlineValidator::filter

### Additional info
If I remove rule or method - all is ok

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.18
| Operating system | Ubuntu 16.04

**Comment by dynasource** [comment]
This is caused by the `hasMethod` logic https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L211

Because this is a default validator, it's unexpected to interfere with inlineValidation, so I would expect another check on `static::$builtInValidators[$type]`
