### ISSUE TITLE
Gii 400 error after preview

### ISSUE THREAD

**Issue by nemozar** [yiisoft/yii2#14383]
hi, install basic app
`composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic` (This is Yii version 2.0.12.)

confgi `db.php` go to gii generator (http://host/gii/model) сompleted the form and click preview button.

and get error 400 with message `Unable to verify your data submission.`

![2017-07-04 09-00-49](https://user-images.githubusercontent.com/4721820/27816958-59429192-6097-11e7-9019-09887d882e53.png)

login also set error 400

**Comment by cebe** [comment]
do you have cookies enabled?

**Comment by nemozar** [comment]
yes, cookies enabled.

disabled **enableCsrfValidation** in request settings but this is not good way.

```
    'components' => [
        'request' => [
            'cookieValidationKey' => '',
            'enableCsrfValidation' => false,
        ], 
```
![2017-07-04 16-15-42](https://user-images.githubusercontent.com/4721820/27831594-0740eec4-60d4-11e7-91c0-340ecfb93aef.png)

**Comment by samdark** [comment]
Sounds like https://github.com/yiisoft/yii2/issues/14302. Do you have custom settings in php.ini regarding encodings and multibyte strings?

**Comment by nemozar** [comment]
samdark, yes **mbstring.encoding_translation = on** in my config. After set off all work succesfull.
Many thanks for the help!

**Comment by samdark** [comment]
Closing this one as duplicate then.
