### ISSUE TITLE
Using registerCssFile or registerJsFile append No timestamp

### ISSUE THREAD

**Issue by NingerJohn** [yiisoft/yii2#14382]
FYI, I already add the `'appendTimestamp'=>true` in the config file and make sure the asset file in AssetBundle has timestamp as version number. 
However there's no timestamp append for asset file with using `regiserCssFile` or `registerJsFile`

```
Yii Version: 2.0.10 ( upgrade to 2.0.12 still have the same issue )
```

Although I Found pull request about this issue as following:
[Fix #9101 resolve appendTimestamp to registerJsFile and registerCssFile ](https://github.com/yiisoft/yii2/pull/10297)

**Comment by Renkas** [comment]
You did not give any usefull information to help you. There's a template when you start a issue for a reason. Fill it out correctly

**Comment by cebe** [comment]
if you need this feature, you can either use the AssetBundle to register the files or append timestamp yourself. `regiserCssFile` or `registerJsFile` are meant to be used for simple case of managing assets yourself, if you want yii to handle it (i.e. also handle the timestamp stuff) use asset manager and asset bundles instead.
