### ISSUE TITLE
onCondition in joinWith

### ISSUE THREAD

**Issue by isudakoff** [yiisoft/yii2#14387]
### What steps will reproduce the problem?
```php
$customers = Customer::find()->joinWith([
    'orders' => function ($query) {
        $query->onCondition(['customer.somevar' => 'someWord']);
    },
])->all();
```

### What is the expected result?
```sql
SELECT * FROM customer LEFT JOIN orders ON (customer.id=order.customer_id) 
AND (customer.somevar='someWord')
```
```sql
SELECT * FROM order WHERE (id IN (1, 2, 3))
```

### What do you get instead?
```sql
SELECT * FROM customer LEFT JOIN orders ON (customer.id=order.customer_id) 
AND (customer.somevar='someWord')
```
```sql
SELECT * FROM order WHERE (id IN (1, 2, 3)) AND (customer.somevar='someWord')
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.0.20-2
| Operating system | Ubuntu 16.04.1

**Comment by Alex-Code** [comment]
Why are you referencing the parent table in the join?
Can't you do
```php
$customers = Customer::find()->joinWith([
    'orders' => function ($query) { },
])->where(['customer.somevar' => 'someWord')->all();
```

**Comment by isudakoff** [comment]
Cause the full query was like this one:
```php
$customers = Customer::find()->joinWith([
    'orders' => function ($query) {
        $query->onCondition(['customer.somevar' => 'someWord']);
    },
    'album.photos' => function ($query) {
        $query->onCondition(['customer.somevar' => 'anotherWord']);
    },
])->where(['customer.manyotherfilters' => 'fooBar'])->all();
```

**Comment by Alex-Code** [comment]
I'm with you now, I'd encountered a similar issue a while back.
The solution I came up with was to check the `primaryModel` value of the join `$query` var.

```php
$customers = Customer::find()->joinWith([
    'orders' => function ($query) {
        if ($query->primaryModel !== null) {
            $query->onCondition(['customer.somevar' => 'someWord']);
        }
    },
    'album.photos' => function ($query) {
        if ($query->primaryModel !== null) {
            $query->onCondition(['customer.somevar' => 'anotherWord']);
        }
    },
])->where(['customer.manyotherfilters' => 'fooBar'])->all();
```

This includes the extra `onCondition` when used as part of the join but ignores it when it's a `SELECT`.

**Comment by cebe** [comment]
`onCondition` is meant to be applied to both, the JOIN and the WHERE of a relational query. If you want to add additional condition to the JOIN only, you need to specify it outside as shown in https://github.com/yiisoft/yii2/issues/14387#issuecomment-312885987

**Comment by cydh** [comment]
so the solution is workaround

https://github.com/yiisoft/yii2/issues/14387#issuecomment-313031131
