### ISSUE TITLE
AuthManager->getRolesByUser($userId) not working

### ISSUE THREAD

**Issue by gvanto** [yiisoft/yii2#14393]
### What steps will reproduce the problem?
Calling `Yii::$app->authManager->getRolesByUser($userId);`
 gives ALL system roles rather than just that assigned to user.

### What is the expected result?
Only role assigned to the user to be returned.
(I have checked and in the auth_assignment table, only one record exists for my user 'admin' => user_id=3

### What do you get instead?
All roles are returned. (Have double-checked the user ID is being passed correctly to the function)

### Additional info
This is happening after running composer update (in which yiisoft package was updated to 2.0.12)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12?
| PHP version      | 5.4
| Operating system | Ubuntu

**Comment by Alex-Code** [comment]
Do you have any default roles configured?

**Comment by gvanto** [comment]
Hi Alex

Yes I have three configured in my config.

They not supported anymore?


On 5 Jul 2017 12:45 pm, "Alex-Code" <notifications@github.com> wrote:

Do you have any default roles configured?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yiisoft/yii2/issues/14393#issuecomment-313068303>, or mute
the thread

**Comment by Alex-Code** [comment]
Since this commit https://github.com/yiisoft/yii2/commit/3a4505ac08997b8b9c7a5c63d549fa9cc4201da6 default roles are included in the results of `getRolesByUser`.

**Comment by gvanto** [comment]
Oh I see thanks Alex.

Is there a way to not have them included?

I guess I can see why a default role is included. Perhaps I don't need
these default roles at all.. trying to think what purpose they serve
really...

On 5 Jul 2017 2:04 pm, "Alex-Code" <notifications@github.com> wrote:

Since this commit 3a4505a
<https://github.com/yiisoft/yii2/commit/3a4505ac08997b8b9c7a5c63d549fa9cc4201da6>
default roles are included in the results of getRolesByUser.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yiisoft/yii2/issues/14393#issuecomment-313083338>, or mute
the thread

**Comment by Alex-Code** [comment]
Not with the way it's currently done.
You'd need to extend the `DbManager` class.

**Comment by gvanto** [comment]
Thank you Alex...

Maybe I can just remove default roles from my config, any potential issues
there?

**Comment by gvanto** [comment]
Have removed it, seems OK. thanks for the help

**Comment by gvanto** [comment]
Btw this is not mentioned in the documentation

**Comment by cebe** [comment]
@gvanto can you say more concrete what is missing form the docs? If possible even send a pull request that adds what you are missing?

**Comment by Alex-Code** [comment]
I'd say it's that http://www.yiiframework.com/doc-2.0/yii-rbac-managerinterface.html#getRolesByUser()-detail doesn't mention any default roles set in the config are also returned.

**Comment by cebe** [comment]
added a note, thanks!
