### ISSUE TITLE
Stateless config in API module is giving HTTP 403 error in frontend module

### ISSUE THREAD

**Issue by akpanowo** [yiisoft/yii2#14403]
I have built an application with a frontend, backend and API module. Since my api requests are stateless i have turned session off in the API config and set loginUrl to null.

But now i cant access the frontend anymore, it raises a 403 error: You don't have authorization to view this page.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by cebe** [comment]
if changes to your API config affect your frontend, there is some problem in your application, not in Yii.
