### ISSUE TITLE
Yii2 ActiveQuery Error,Partition name has been wrapped  PARTITION(p2017,p2016)

### ISSUE THREAD

**Issue by fbens** [yiisoft/yii2#14407]
### What steps will reproduce the problem?
I want to run a query use partition like below
```
$arts = Article::find()
->from(Article::tableName(). ' PARTITION(p2017,p2016) ' )
->where(['status' => [1,2]])
->orderBy(['id' => SORT_DESC])
->limit(10);
```
Error Tips 
```
SQLSTATE[42000]: Syntax error or access violation: 1064
You have an error in your SQL syntax;
check the manual that corresponds to your MySQL server version for
the right syntax to use near 'WHERE `status` IN (1, 2)' at line 1
```

bcs sql generate 
```
SELECT COUNT(id) FROM pre_article PARTITION(p2017, `p2016)` WHERE status IN (1,2)
 ```
unless I use only one partition like `PARTITION (p2017) `.

### What is the expected result?

I hope there will be a new function to specify partition, usage like below 
```
$arts = Article::find()
->partition(['p2017','p2016'])
->where(['status' => [1,2])
->limit(10)
```
generate sql 
```
select * from pre_article partition (p2017,p2016) where status in (1,2) limit 10
```

### What do you get instead?
not resolved.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      |  7.1.4
| Operating system | Win7 X64

**Comment by cebe** [comment]
this will work:

```php
$arts = Article::find()
->from([new \yii\db\Expression(Article::tableName(). ' PARTITION(p2017,p2016) ')])
->where(['status' => [1,2]])
->orderBy(['id' => SORT_DESC])
->limit(10);
```

**Comment by fbens** [comment]
@cebe Could Yii2 add a function like `->partition(['p1','p2'])` , looks like better to understand.

**Comment by cebe** [comment]
@fbens PARTITION is MySQL specific syntax and not supported by other DBMS as far as I know, also its usage is not very common so an extra method will not be added.
