### ISSUE TITLE
[2.1] Remove supposed IIS workaround from `Request`

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#14400]
Yii's `Request` object supports getting the request URI from a header called `X-Rewrite-Url`.

It's hard to find any documentation, but I think `X-Rewrite-Url` is not even part of IIS, but of a 3rd party plugin: http://www.helicontech.com/isapi_rewrite/

https://forums.asp.net/post/5807236.aspx

In some modules like http://www.micronovae.com/ModRewrite/ref/XAddOriginalURL.html the name of the header is different.

I think this should be removed from Yii since it is out of scope for an application framework. Instead proper configuration of URL routing can solve most problems.

**Comment by ngo** [comment]
This "feature" of yii is also really useful for attackers that want to bypass url-based protections. E.g. when there is some functionality that is restricted to be used only from internal IPs via nginx or apache config.
As there is no documentation, the only way to know about this behavior is by reading the sources.

**Comment by cebe** [comment]
@ngo that problem should be solved by #13780 which is also well documented now.

**Comment by ngo** [comment]
I'm not quite sure which problem do you refer to, but  the latest version of code after the PR you mentioned still honors the header and there is still no docs about it.

**Comment by cebe** [comment]
right, I thought that header was added to secureHeaders property. It should be added.
