### ISSUE TITLE
Inconsistent Inflector::camel2id behavior

### ISSUE THREAD

**Issue by rsvasilyev** [yiisoft/yii2#14401]
I suppose it's expected that `BaseInflector::id2camel(BaseInflector::camel2id($string)) === $string`.
But it isn't true for strings that contain two or more uppercased characters in a row:
```
// That's fine
BaseInflector::camel2id('AaBbCc'); // => "aa-bb-cc"
BaseInflector::id2camel('aa-bb-cc'); // => "AaBbCc"

// However
BaseInflector::camel2id('ABC'); // => "abc"
BaseInflector::camel2id('abc'); // => "Abc"
```
### What steps will reproduce the problem?
Call `\yii\helpers\BaseInflector::camel2id('ABC')`

### What is the expected result?
`"a-b-c"`

### What do you get instead?
`"abc"`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master
| PHP version      | 7.1
| Operating system | Linux

**Comment by cebe** [comment]
there is a strict parameter you can set to `true` to get the expected behavior.
