### ISSUE TITLE
EVENT_AFTER_DELETE do not works with deleteAll 

### ISSUE THREAD

**Issue by pistol88** [yiisoft/yii2#14412]
In project some callback function listen to ActiveRecord::EVENT_AFTER_DELETE event at AR model (behavior or afterDelete method).

I try to delete row by model with 

`Image::deleteAll("id = $id");`

and

`if($model = Image::findOne($id)) $model->delete();`

I expect that callback function will run in both cases. But it's work only with delete (deleteAll will not trigger any events ).

I see note about it in documentation, but I think it's not obviously and can cause serious problems and bugs in system.

**Comment by pistol88** [comment]
I see very old topick #1404 about it. If it's design "which gives much better performance", may be rename this static method to "sqlDelete" in next major?

**Comment by cebe** [comment]
Documentation is pretty clear about what the method does and how to write code in case you need events to be triggered. renaming the method does not make it more clear that no events are triggered.
