### ISSUE TITLE
Why events and behaviors not work in updateAll or deleteAll() ?

### ISSUE THREAD

**Issue by airani** [yiisoft/yii2#14410]
Why before and after method updateAll or deleteAll in ActiveRecord, events not triggered?

**Comment by cebe** [comment]
@airani because these are executed in batch mode on the DB layer. See https://github.com/yiisoft/yii2/issues/1404#issuecomment-29676451 for a solution.

**Comment by airani** [comment]
@cebe Actually my problem with unlinkAll() that works with deleteAll() and i want to suggest change deleteAll() or updateAll() method and add event trigger

**Comment by cebe** [comment]
added a note to the docs about unlinkAll(). the docs about deleteAll() and updateAll() are pretty clear about events.
