### ISSUE TITLE
Git: fatal: Negative patterns are forbidden in git attributes

### ISSUE THREAD

**Issue by maxxdev** [yiisoft/yii2#14425]
### What steps will reproduce the problem?
After composer update when use git add * or git commit
getting error "fatal: Negative patterns are forbidden in git attributes
Use '\!' for literal leading exclamation."
Investigated which file trigger error and found 
\vendor\bower\jquery.inputmask\.gitattributes text in last string is !k4E3n2s1E1n2d3m4E!
If comment/delete this string then git works success

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |  7.x
| Operating system | windows 7

**Comment by samdark** [comment]
Please report to https://github.com/RobinHerbots/Inputmask. We can't fix it from our side.
