### ISSUE TITLE
models / class not loading in unit tests

### ISSUE THREAD

**Issue by miradnan** [yiisoft/yii2#14426]
### What steps will reproduce the problem?
I am using an advanced template version. I have lots models, so I have put them into sub-folders. I have the folder as `app\modules\administration\models\viewModels\AddUser.php`

### What is the expected result?
The models class inside the sub-folder should load.

### What do you get instead?
Error: Class not found.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.x
| Operating system | Ubuntu

**Comment by cebe** [comment]
> I am using an advanced template version

Using the `app` namespace in the advanced template does not make sense as the `@app` alias points to different locations in different application tiers. You should use `frontend`, `backend` and `common` namespace instead.


> app\modules\administration\models\viewModels\AddUser.php

**Comment by miradnan** [comment]
I have app namespace configured correctly in common/config/bootstrap.php file. Everything works well. Just this tests aren't working because the file is not auto loading.


Thanks,
Mir Adnan

**Comment by cebe** [comment]
then you need to make sure the file is included in test environment also.
