### ISSUE TITLE
RESTful API CreateAction will return text/html content type when running on the IIS

### ISSUE THREAD

**Issue by liyadongcn** [yiisoft/yii2#14430]
### What steps will reproduce the problem?
Use the default  rest CreateAction , the respone will change to text/html instead of application/json when running on the windows IIS
### What is the expected result?
should return application/json content type
### What do you get instead?
get text/html content type

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.6.6
| Operating system | windows iis

**Comment by liyadongcn** [comment]
my solution now is write a new CreateAction and remove the location setting. but i do not feel good. Any other solution?
 public function actionCreate()
	 {
	 	$model = new $this->modelClass;
	 	$model->load(Yii::$app->request->post(), '');
	 	if ($model->save()) {
            $response = Yii::$app->getResponse();
            $response->setStatusCode(201);
            $id = implode(',', array_values($model->getPrimaryKey(true)));
            //$response->getHeaders()->set('Location', Url::toRoute(['view', 'id' => $id], true));_
        } elseif (!$model->hasErrors()) {
            throw new ServerErrorHttpException('Failed to create the object for unknown reason.');
        }

        return $model;
	 }

**Comment by samdark** [comment]
What's the client you're using?

**Comment by liyadongcn** [comment]
postman and call from android are same problem.

**Comment by liyadongcn** [comment]
running on the apache it will not happen.Only on the iis it will return a text/html content with a link and json data instead of application/json type with json data body.

**Comment by cebe** [comment]
does not look like a Yii problem then. Is there any special setting on IIS that would overwrite Content-Type headers sent by yii?

**Comment by tunecino** [comment]
Yes it is IIS+FastCGI related, it overrides headers when response code is set to 201 : https://stackoverflow.com/questions/43618117/yii2-rest-api-iis-object-moved

**Comment by tunecino** [comment]
> my solution now is write a new CreateAction and remove the location setting. but i do not feel good. Any other solution?

I think the correct solution is to fix it at server level by implementing a custom module or any other solution shown here: https://stackoverflow.com/questions/12074730/w7-pro-iis-7-5-overwrites-php-location-header-solved as [201](https://httpstatuses.com/201) status code is the correct response for creations.

**Comment by cebe** [comment]
looks like there is notthing we can do about it form Yii side. Thanks @tunecino
