### ISSUE TITLE
Using custom rules with scenario

### ISSUE THREAD

**Issue by samirmember** [yiisoft/yii2#14438]
I'm using this rule in my Player model:
`[['player_file'], 'checkFiles', 'on' => 'transfer'],`
and added the function below:
`
    public function checkFile($attribute, $params)
    {
        if (($this->age < 19) && (!$this->$attribute)) {
            $this->addError($attribute, $this->getAttributeLabel($attribute)." can't be empty!");
        }
    }
`

But when I validate, my custom rule checkFile does not run.
If I change my rule and put another attribute than 'player_file'. An attribute that is in the required fields, then my function is executed. (For example `[['player_id'], 'checkFiles', 'on' => 'transfer'],` )

Is it a bug or Am I missing something in rules?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.5.12
| Operating system | Windows 10 64 bits

**Comment by berezuev** [comment]
You write checkFile**s** in rules, but checkFile in function name

**Comment by samirmember** [comment]
Yes, this is just in error while taping my code here in github.

I need to know if this is a bug or not?
