### ISSUE TITLE
schemaCache in 2.0.12 is broken

### ISSUE THREAD

**Issue by nikosid** [yiisoft/yii2#14434]
### If I use Redis to save schemaCache my page is loading very long time

I found that in new `\yii\db\Schema::getTableMetadata` is always runing `saveTableMetadataToCache()`. It doesn't save data to cache only if `$cache` is null. But in this code
```
    $cache = null;
        if ($this->db->enableSchemaCache && !in_array($name, $this->db->schemaCacheExclude, true)) {
            $schemaCache = is_string($this->db->schemaCache) ? Yii::$app->get($this->db->schemaCache, false) : $this->db->schemaCache;
            if ($schemaCache instanceof Cache) {
                $cache = $schemaCache;
            }
        }
```
we see that `$cache` is not null just if `enableSchemaCache` is set and particular schemaCache is not excluded.
In previous frameworrk version data was saved to cache only if it wasn't in cache or if it's `$refresh`. In current version even after `$this->loadTableMetadataFromCache($cache, $name);` we save cache.

I don't understand actually why it's so slow, but if I save metadata to cache once and then comment line `$this->saveTableMetadataToCache($cache, $name);` then it works fast and takes data from cache

I would move `$this->saveTableMetadataToCache($cache, $name);` into `if (!array_key_exists($type, $this->_tableMetadata[$name])) {` to lok like this
```
        if (!array_key_exists($type, $this->_tableMetadata[$name])) {
            $this->_tableMetadata[$name][$type] = $this->{'loadTable' . ucfirst($type)}($this->getRawTableName($name));
            $this->saveTableMetadataToCache($cache, $name);
        }
```

https://github.com/yiisoft/yii2/pull/14435

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.18
| Operating system | Ubuntu

**Comment by nikosid** [comment]
I don't understand actually why it's so slow, but if I save metadata to cache once and then comment line `$this->saveTableMetadataToCache($cache, $name);` then it works fast and takes data from cache

**Comment by nikosid** [comment]
I would move `$this->saveTableMetadataToCache($cache, $name);` into `if (!array_key_exists($type, $this->_tableMetadata[$name])) {` to lok like this
```
if (!array_key_exists($type, $this->_tableMetadata[$name])) {
            $this->_tableMetadata[$name][$type] = $this->{'loadTable' . ucfirst($type)}($this->getRawTableName($name));
            $this->saveTableMetadataToCache($cache, $name);
        }
```

**Comment by nikosid** [comment]
https://github.com/yiisoft/yii2/pull/14435

**Comment by cebe** [comment]
You mean current `master` and not `2.0.12` right? `saveTableMetadataToCache` does not exist in 2.0.12.

**Comment by dynasource** [comment]
nicely spotted. 

@sergeymakinen, do you remember why it is saved to cache every time? It does not seem necessary?

**Comment by sergeymakinen** [comment]
It's definitely my fault. Saving to cache should be inside of `If`.
