### ISSUE TITLE
Pass along calling model into relation

### ISSUE THREAD

**Issue by Sarke** [yiisoft/yii2#14436]
Here's a basic example that I hope explains what I am after:

```php
$author = Author::findOne(1);

$books = $author->books;  // relation

$books[0]->isRelationPopulated('author'); // false
```

Even though we already have the `$author` loaded, it does not exist in the `$books` array.

Now we could do this:

```php
$books = $author->getBooks()->with('author');
```
or
```php
$books[0]->author;
```

but they will both result in an additional database call.

It can get quite bad if there are several of these back-and-forth relations, even though the data is all there and loaded already.

So, is there a way to pass along the calling model into the relation?  If not, can we, please?

**Comment by klimov-paul** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#inverse-relations
