### ISSUE TITLE
redirect writes headers always

### ISSUE THREAD

**Issue by TheHett** [yiisoft/yii2#14445]
Its look suspecious. The code below will redirect:

```php
    public function actionIndex()
    {
        $this->redirect("/xxx");
    }
```

Method documentation says that:

```php
     * You can use it in an action by returning the [[Response]] directly:
     *
```

if response was not returned, redirect should not be

**Comment by cebe** [comment]
It modifies the Response object, if you do not reset it after calling `redirect()` the response is sent with the headers set by the redirect method.
