### ISSUE TITLE
Error : to much redirection after login in server but working fine in localhost under folder yii/

### ISSUE THREAD

**Issue by parthasarathi2015** [yiisoft/yii2#14453]
My htaccess attached.
[htaccess.txt](https://github.com/yiisoft/yii2/files/1147462/htaccess.txt)
Without login working fine but after login browser says to much redirection

[main.txt](https://github.com/yiisoft/yii2/files/1147481/main.txt)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 
| Operating system |

**Comment by cebe** [comment]
if it works locally but not on your server, its likely an issue with your server configuration. Please make sure the problem is unrelated to your custom code by debugging and searching the cause of the issue. Then report back if its really a framework bug.
