### ISSUE TITLE
Error on formatting number with asInteger() function

### ISSUE THREAD

**Issue by Bertagit** [yiisoft/yii2#14454]
I need to convert a number like 1000.00 to an integer value by using yii2 Formatter.
My hope was to obtain from 1000.00 the 1000 value but the result is 1,000 the code is:
`$f = new Formatter();
$qta = $f->asInteger($qta);`

Is it a bug or I need to set some options more?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      |  7.0.18-0
| Operating system | ubuntu0.16.04.1

Thanks for the support.

**Comment by bizley** [comment]
Have you got _intl_ extension loaded? Without it and `thousandSeparator` being not configured `thousandSeparator` is set to `,`.

**Comment by Bertagit** [comment]
Yes @bizley the problem is the intl extension with the right local settings, I considered comma as decimal separator not as separator of thousand. Sorry for the misunderstanding and thenks for the support.
