### ISSUE TITLE
How to append search_form values in kartik grid filter.

### ISSUE THREAD

**Issue by Vaishalisri** [yiisoft/yii2#14466]
I used form and grid filter together.
In form Date range field is present to get particular data on that date and in filter I used filter form
to search other than date.

When I search in filter it only send filter form data but I also want to filter the search from data.
How to append it.

grid expand button [page/all] also not working correctly in this. So Please to know how to use search form with kartik grid?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by Vaishalisri** [comment]
My issue is in kartik gridview. is there any options like requestParams in  kartik grid view as like in export manager.

**Comment by samdark** [comment]
No idea. This is not kartik repository. Ask there.
