### ISSUE TITLE
yii\filters\ContentNegotiator violates HTTP 1.1 spec

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#14467]
Upon a failed negotiation `ContentNegotiator` generates `415 Unsupported Media Type` response. According to HTTP 1.1 standard the `406 Not Acceptable` response should be generated instead:

https://tools.ietf.org/html/rfc7231#section-5.3.2
https://tools.ietf.org/html/rfc7231#section-5.3.5
https://tools.ietf.org/html/rfc7231#section-6.5.6
https://tools.ietf.org/html/rfc7231#section-6.5.13

Also, the description for `406 Not Acceptable` HTTP status code generated by `ContentNegotiator` is incorrect:

`None of your requested content types is supported.`

should be 

`None of your requested media types is supported.`

instead (there is no such thing as `content type`, there is only a `media type` and a `Content-Type` header that specifies the media type of response).

**Comment by Alex-Code** [comment]
Should the message be `None of your requested media types are supported.` for correct grammar too?

**Comment by PowerGamer1** [comment]
> Should the message be  None of your requested media types are supported.  for correct grammar too?

I think the "is" here corresponds to a singular "None" rather than plural "media types" so it should be correct.

**Comment by dynasource** [comment]
duplicates #https://github.com/yiisoft/yii2/issues/12539

**Comment by PowerGamer1** [comment]
> duplicates ##12539

My issue is indeed a duplicate of https://github.com/yiisoft/yii2/issues/12539 (sorry about that, haven't searched) but my issue have a PR attached and also explains why this must NOT be treated as BC breaking (see PR) and as such implemented in 2.0 (rather than 2.1) as soon as possible. So please make sure you don't close this one and keep the other one open with a 2.1 milestone attached.

**Comment by klimov-paul** [comment]
Resolved by commit 2e01076abc2c5d4db9edbc2043e8e9442bdfe294
