### ISSUE TITLE
Error: Call to undefined function yii\base\fnmatch()

### ISSUE THREAD

**Issue by tonygeli** [yiisoft/yii2#14462]
### What steps will reproduce the problem?
Error: Call to undefined function yii\base\fnmatch()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.0
| Operating system | Linux

**Comment by cebe** [comment]
http://php.net/manual/en/function.fnmatch.php

>  Warning: For now, this function is not available on non-POSIX compliant systems except Windows. 

Can you give more details about what system you are on?

**Comment by WalkingSun** [comment]
I get a same error message.
PHP version          :       5.6.31
Operating system :  CentOS 6.6
Yii version            ;   2.0.11.2

**Comment by cebe** [comment]
https://unix.stackexchange.com/questions/305639/centos-6-7-and-fnmatch-in-php#comment537107_305639 ?
