### ISSUE TITLE
Yii2 classMap use for rewrite, how can i extends origin class?

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2#14465]
use yii2 classMap  can rewrite php class .

if i want rewirte  ‘yii\web\Controller.php’  ， i create a new file  frontend/web/Controller.php’，

classMap config is:

```
 [
  "yii\web\Controller"=>"@front/web/Controller.php
]
```

how can : `@front/web/Controller.php` extends `yii\web\Controller.php`  ?

if i copy yii\web\Controller.php to  @front/web/Controller.php , if yii2 update  yii\web\Controller.php , i must re-copy file to @front/web/Controller.php , it is so trouble

**Comment by rob006** [comment]
Why do you want to do this for `yii\web\Controller`? Just create your own `app\web\Controller` class (which extends `yii\web\Controller`) and use it as base for your controllers.

**Comment by fancyecommerce** [comment]
if i have a software,  it have 1000  controller.php, every controller extends yii\web\Controller , 

if i create  my own app\web\Controller extends  yii\web\Controller ,  then , i must change  1000  controller extends  app\web\Controller , but i use classmap，only change classMap。

**Comment by fancyecommerce** [comment]
use  extends，  you must change code in  Call class ,  if   yii\web\Controller  was used in 10000 file, you  must change code extends   yii\web\Controller in the 10000 files,  That is a very large workload ,   but  use classMap ， you only  change classMap for one line code.

In other cases ， if you use thrid yii extensions  , code was in vendor diretory , You are not allowed to modify the calling class file , but  you can solve this problem by modifying classMap

**Comment by fancyecommerce** [comment]
but classMap  can not extends origin class ,  i must copy all code in origin class to new class,
it was bad for software update code, So I would like to ask if there is a way for classmap to extends the original class

**Comment by fancyecommerce** [comment]
my software fecshop: https://github.com/fecshop/yii2_fecshop
i want user rewrite code use classMap， but  classMap new class  can not extends origin class, So I would like to ask if there is a way for classmap to extends the original class

**Comment by rob006** [comment]
Obviously you can't extend from class that you want to replace. If you have 10000 controllers that directly extends `yii\web\Controller`, you have bad architecture of your app and you should fix it now - it will be even harder when you will have 20000 controllers.

Why do you want to modify base controller for extensions?
