### ISSUE TITLE
Removing old identity cookie --- 

### ISSUE THREAD

**Issue by ajoudeh** [yiisoft/yii2#14476]
Dears,

Kindly look at this scenario:

1. enableAutoLogin ==> true
2. autoRenewCookie ==> false
3. session ==> Database
4. logged in to the system.
5. new session row added.
6. after some idle time (no action on the webpage) the database session row is garbage OR if i delete the session row directly from table
7. refresh webpage.
8. still logged in. because the cookie is exist.
9. after refresh, the identityCookie is not exist
10. try refresh again. ==> logout (no cookie to login)

this happen because you are add this change 
Issue URL: https://github.com/yiisoft/yii2/pull/10480
Change URL: https://github.com/yiisoft/yii2/commit/ad6047e09fb91a33fd00f1b2a1790f17d84d97d9

Thanks,

**Comment by shirase** [comment]
Similar #11825

**Comment by SilverFire** [comment]
Fixed by 03299e8870eaaeb2714e53452078ca3ba2c86800
