### ISSUE TITLE
pjax strange logic: reload page if error happiens in ajax request

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14470]
It's logic is correct?

### What steps will reproduce the problem?
In the controller action separate logic
```php
        if (Yii::$app->request->isAjax && isset(Yii::$app->request->queryParams['_pjax'])) {
            exit(); //no content
        } else {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
```

### What is the expected result?
first request render page
second pjax request got no content. Any mark of no content (or may be no content with id in '_pjax') given.
No send any request again.

### What do you get instead?
first request render page
second pjax request got no content and produce reloading page. 
third request render page again.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev

**Comment by dynasource** [comment]
many duplicates exists. Please search the repo on terms like 'pjax error refresh'

ie.:
https://github.com/yiisoft/yii2/issues/8819#issuecomment-165358474

**Comment by bscheshirwork** [comment]
thx
