### ISSUE TITLE
yii\filters\ContentNegotiator should set response format even when content negotiation has failed

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#14471]
`yii\filters\ContentNegotiator` should set response format to a one defined in `formats` even when content negotiation has failed. Otherwise, in a situation when a client sends request with `Accept: text/html` and ContentNegotiator is configured with `formats = [Response::FORMAT_JSON];` it looks like this: "hey client, you requested the response in text/html but I don't support text/html since I am configured to support only application/json for this request, so here take this error response in - surprise, surprise - text/html format!"

**Comment by samdark** [comment]
Agree.
