### ISSUE TITLE
sqlite schema on HHVM is broken

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#14483]
### What steps will reproduce the problem?

See tests: https://travis-ci.org/yiisoft/yii2/jobs/254035826#L833

### What is the expected result?

Seems the code expects 'origin' to exist as array key.

### What do you get instead?

`$indexes` array returned by SQlite however seems to look like this on HHVM:

```php
Array
(
    [0] => Array
        (
            [seq] => 0
            [name] => sqlite_autoindex_T_constraints_1_2
            [unique] => 1
        )

    [1] => Array
        (
            [seq] => 1
            [name] => sqlite_autoindex_T_constraints_1_1
            [unique] => 1
        )
)
```

@sergeymakinen seems this is related to your changes. Could you take a look at it?

**Comment by sergeymakinen** [comment]
Copy. I'll fix it this week.

**Comment by sergeymakinen** [comment]
#14497 should fix this.
