### ISSUE TITLE
Dead links on http://www.yiiframework.com/doc-2.0/guide-structure-widgets.html

### ISSUE THREAD

**Issue by kjusupov** [yiisoft/yii2#14485]
### What steps will reproduce the problem?
Refer to http://www.yiiframework.com/doc-2.0/guide-structure-widgets.html
### What is the expected result?
Links "jQuery UI widgets" and "Twitter Bootstrap widgets" to display respective docs.

http://www.yiiframework.com/doc-2.0/yii-jui-widget.html
### What do you get instead?

Error
Unable to resolve the request "doc-2.0/guide-widget-jui.html".
Unable to resolve the request "doc-2.0/guide-widget-bootstrap.html".

Not sure if the intention was to provide external (http://jqueryui.com/) link or internally to extensions section respectively http://www.yiiframework.com/doc-2.0/ext-jui-index.html and http://www.yiiframework.com/doc-2.0/ext-bootstrap-index.html

Note: on http://www.yiiframework.com/doc-2.0/ext-jui-index.html page the link "jQuery UI widgets" is external to http://jqueryui.com/

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by githubjeka** [comment]
Not easy to fix because this links can be changed
http://www.yiiframework.com/doc-2.0/ext-jui-index.html
http://www.yiiframework.com/doc-2.0/ext-bootstrap-index.html

for example, this links should be work on this page too http://yiiframework.domain-na.me/doc/guide/2.0/en/structure-widgets

**Comment by cebe** [comment]
moved to https://github.com/yiisoft-contrib/yiiframework.com/issues/235
