### ISSUE TITLE
PHP 7.2: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#14489]
### What steps will reproduce the problem?

A lot of tests on PHP 7.2 are failing with

```
count(): Parameter must be an array or an object that implements Countable
```

https://travis-ci.org/yiisoft/yii2/jobs/255175595#L670

`count()` throws a warning since PHP 7.2 in case a scalar or non-countable object is passed. We rely on this behavior in many places so code needs to be adjusted.

### More info

- https://wiki.php.net/rfc/counting_non_countables
- http://php.net/manual/en/function.count.php

**Comment by tmli3b3rm4n** [comment]
same

**Comment by samdark** [comment]
https://travis-ci.org/yiisoft/yii2/jobs/283264298
