### ISSUE TITLE
Yii2 filter validator doesn't allow array.

### ISSUE THREAD

**Issue by tumdav** [yiisoft/yii2#14491]
It will be great if you add this feature

E.G
```php
  ['label', 'filter', 'filter' => ['trim', 'strtolower']]
```

**Comment by dmirogin** [comment]
You can use several consecutive validators in a row
` ['label', 'filter', 'filter' => 'trim]`
` ['label', 'filter', 'filter' => 'strtolower']`

**Comment by tumdav** [comment]
@dmirogin  I know , but it will be easy to define all filters in one array.

**Comment by samdark** [comment]
Arrays are valid callables so it's not possible to determine if it's object-method pair or two separate methods. See https://secure.php.net/manual/en/language.types.callable.php

Won't introduce it for the sake of not being ambiguous.
