### ISSUE TITLE
ActiveRecordInterface

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14496]
### What steps will reproduce the problem?
SpellChecker in IDE mark to problems lines like this:
```php
     * @param string|array $condition the conditions that will be put in the WHERE part of the UPDATE SQL.
    public static function updateAll($attributes, $condition = '', $params = [])
    {
```

### What is the expected result?
ActiveRecordInterface can except $condition as a string

### What do you get instead?
only null|array acceptable
```php
     * @param array $condition the condition that matches the records that should get updated.
    public static function updateAll($attributes, $condition = null);
```

https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecordInterface.php#L261

https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecordInterface.php#L278

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev

**Comment by cebe** [comment]
I don't really get the problem, ActiveRecordInterface allows condition to be an array. The implementation of ActiveRecord for SQL db additionally adds the option to pass a string, thats fine, because if you program against the interface, you should only pass arrays, if you program against concrete implementation (yii\db\ActiveRecord) you can pass SQL strings.

**Comment by bscheshirwork** [comment]
How to convince in this development environment, which wants the correspondence of the types of interface and implementation...

**Comment by cebe** [comment]
Sorry, I do not understand what you are trying to say...

**Comment by SilverFire** [comment]
Parameter `$condition` will be passed to Query, and `QueryInterface::where()` allows `$condition` to be either array or string. I think `ActiveRecordInterface` must be fixed.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/commit/79ad74f763229e84c298cf5f5d3c0f59f758aaf1#commitcomment-23840647
