### ISSUE TITLE
Broken link in AuthClient docs

### ISSUE THREAD

**Issue by TomaszKane** [yiisoft/yii2#14502]
### What steps will reproduce the problem?

Go to: http://www.yiiframework.com/doc-2.0/ext-authclient-index.html
Click on "Documentation is at docs/guide/README.md."

### What is the expected result?

I see documentation of AuthClient.

### What do you get instead?

404

**Comment by samdark** [comment]
@cebe is it a build error or should a link be adjusted?

**Comment by cebe** [comment]
link should be absolute as currently it only works on github but not if readme is displayed elsewhere.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-authclient/commit/b1e2c1e82a2580cfae1fc2f4690f050f2279fd81
