### ISSUE TITLE
AJAX request always sent when both enableClientValidation and enableAjaxValidation are enabled

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#14509]
From https://github.com/yiisoft/yii2/blob/fcfcdbdc34d57af74b2eb3a5d6da5a03b3dd90b1/docs/guide/input-validation.md

> When both enableClientValidation and enableAjaxValidation are set to true, AJAX validation request will be triggered only after the successful client validation.

But on empty basic app when 

```
'enableAjaxValidation' => true,
'enableClientValidation' => true,
```

**Ajax request is always being sent.** 

p.s rules 

```php
return [
            [
                [                   
                    'firstName',
                    'lastName',                  
                ],
                'required'
            ],
            ['zip', 'number'],
            [['confirmSpecs','], 'boolean'],
            [[''remarks'], 'safe'],
            ['email', 'email'],
            [
                [
                    'invoiceCompany',                   
                ],
                'required',
                'when' => function ($model) {
                    return $model->useInvoiceAddress;
                },
                'whenClient' => <<<JS
function (attribute, value) {
    return $('#$useInvoiceAddressID').prop('checked') === true;
}
JS
            ],
```

**Comment by samdark** [comment]
Verified on basic app with regular contact form without any custom rules. The only modification is form opening in `contact.php`:

```php
<?php $form = ActiveForm::begin([
        'id' => 'contact-form',
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,
]); ?>
```

**Comment by samdark** [comment]
Seems description isn't accurate. Indeed, AJAX request is only issued after successful client validation but since only one field is being validated at a time, the statement isn't about the whole form but about the field being validated.

**Comment by githubjeka** [comment]
By [history](https://github.com/yiisoft/yii2/commits/master/framework/assets/yii.activeForm.js) after this commit https://github.com/yiisoft/yii2/commit/9eaa82e15dfeca9ce0588bf75b1c000cd189deec it started
