### ISSUE TITLE
Event handler's fail handling strategy (enhancement proposal)

### ISSUE THREAD

**Issue by tekord** [yiisoft/yii2#14519]
Some event handlers may fail and throw an exception. At now if this happened then all left event handlers will never executed and there is no way to resume execution after some handler's fail. Of course, each event handler should be responsible for error catching, but many junior developers don't know about it or just forget. Currently Yii has no tools to catch handler's fail globally, but it could be useful. For example:

- Some event EVENT_CREATED has 4 handlers;
- Event triggered, 1 handler executed ok, but the 2nd one is failed and throw the DomainException and there is no try/catch block inside this handler. Application is interrupted;
- The 3rd and 4th handlers are lost.

If we could be able to catch the fail then (for example) we may serialize the event object and create queue job to execute failed handlers later.

My idea is to add FailStrategyInterface to the event system and call method `onHandlerFailed` with arguments: $event and $exception. If no strategy is provided then do what Yii do now, throw exception and interrput the application. Users can implement their own failure handling strategies.

Is it worth to implement as core feature or as an extension? Please give some feedback and I'll try to implement it.

**Comment by samdark** [comment]
1. I don't think introducing something like proposed in the core framework would be good. Events are very basic concept.
2. Seems it could be solved with https://github.com/yiisoft/yii2-queue
3. You may create a base handler class w/ try-catch to help junior developers.
