### ISSUE TITLE
Incomplete phpdoc of some functions in yii\rbac\ManagerInterface

### ISSUE THREAD

**Issue by dmirogin** [yiisoft/yii2#14513]
Now phpdoc of yii\rbac\ManagerInterface::assign and yii\rbac\ManagerInterface::revoke functions say that you must pass $role only as yii\rbac\Role, but you also can pass yii\rbac\Permission.

https://github.com/yiisoft/yii2/blob/master/framework/rbac/ManagerInterface.php#L190
https://github.com/yiisoft/yii2/blob/master/framework/rbac/ManagerInterface.php#L198

**Comment by SilverFire** [comment]
Thank you. As far as I see, we don't have tests for these methods. Would you like to create a PR?

**Comment by dmirogin** [comment]
Yes.  I would. Now we only have for Role https://github.com/yiisoft/yii2/blob/master/tests/framework/rbac/ManagerTestCase.php#L457

**Comment by dmirogin** [comment]
Could somebody give me advice how to orginize tests correctly ?
We have test for assigning Roles https://github.com/yiisoft/yii2/blob/master/tests/framework/rbac/ManagerTestCase.php#L457
But assigning Permission will be similar except replacing 
createRole -> createPermission
getRole -> getPermission 

And i suppose copying is not good way here.

And also we don't have tests (Role and Permission) for revoke function. And i guess they will be similar too.

Maybe we can change function (testAssignRule -> testAssignItem) and pass some dataProvider there.

**Comment by SilverFire** [comment]
Yes, data providers is exactly what you need.
