### ISSUE TITLE
Travis does not build some PRs

### ISSUE THREAD

**Issue by dmirogin** [yiisoft/yii2#14517]
One of CI fails in the last PR's  here https://codeclimate.com/github/yiisoft/yii2/framework/validators/DateValidator.php?from_sha=6d2e0aff&to_sha=5f201586

**Comment by cebe** [comment]
it does not really "fail" it points out possible issues. Taking Codeclimate reports as hard restrictions would slow down development significantly, as we'd need to tweak their config to fit our needs with a lot of detail first before it becomes useful, currently it contains a lot of false-positives (the example you show is a false-positive also, nothing wrong with that code). Thanks for noting though!

**Comment by dmirogin** [comment]
@cebe The problem is if codeclimate fails then travis won't launch.

**Comment by cebe** [comment]
> @cebe The problem is if codeclimate fails then travis won't launch.

that should not happen, where did you see that behavior?

**Comment by dmirogin** [comment]
@cebe https://github.com/yiisoft/yii2/pull/14498

**Comment by cebe** [comment]
thats unrelated to CodeClimate, for whatever reason travis was not notified of the PR and did not create a build for it...

**Comment by cebe** [comment]
lets see if it comes up when you push another commit.

**Comment by dmirogin** [comment]
@cebe One minute.

**Comment by dmirogin** [comment]
@cebe That is a bit weird. Made commit, codeclimat passed, but where is travis ?

**Comment by cebe** [comment]
Check on travis and found this:

>  GitHub payload is missing a merge commit (mergeable_state: "unknown", merged: false) 

Probably caused by the conflict in CHANGLOG? maybe you could try rebasing on master and force-push?

**Comment by dmirogin** [comment]
@cebe Damn, i didn't notice conflict. After resolving travis works. Sorry.
