### ISSUE TITLE
InitDbFixture isn't loaded anymore since 2.0.12

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#14525]
### What steps will reproduce the problem?
It seems that `InitDbFixture` isn't loaded anymore when loading fixtures trough the CLI. I was looking at #5442, but that doesn't seem to be the issue.

It seems that the function `getFixturesConfig()` in `console/controllers/FixtureController.php` always adds a `Fixture` to the namespace. Therefore, if you feed it `yii\test\InitDbFixture`, you will end up with `yii\test\InitDbFixtureFixture`. That class doesn't exists, so it won't load it.

Before 2.0.12, the `$globalFixtures` was `yii\test\InitDb`, and after the `getFixturesConfig()` function, it would be the expected `yii\test\InitDbFixture`.

The commit that broke this is 96dae1cebc1835a712be572fff47505085d035ea, but there is no reference to an issue or PR.

**Comment by leandrogehlen** [comment]
Related to Codeception/Codeception#4201
