### ISSUE TITLE
pjax scroll location #hash

### ISSUE THREAD

**Issue by sreenadh** [yiisoft/yii2#14537]
### What steps will reproduce the problem?
There is a pjax container at the bottom of a page(or bootstrap tab content).  
URL: controller/action?id=xx#profile (#profile is the id of the bootstrap tab pane)

do a 
$.pjax.reload({ url: "url", container: "#pjax-container" });

### What is the expected result?
no page scroll.

### What do you get instead?
will scroll the page to the hash location #profile

**Comment by dynasource** [comment]
I'm sorry to inform you that the core team has decided to stop with the support of PJAX. This implies that we are not accepting PR's for updating PJAX in the 2.0.x branch anymore. In the 2.1 branch it will be removed from the framework. 

A lot has been said on this subject. Our conclusion is that the current state of PJAX does not meet our standards to properly support in the Yii framework. For this reason, we are also not moving it into a Yii2 extension. Of course the Community is free to fill this gap, but with a warning. It is very time consuming to support and in our humble opinion, it should be completely rewritten to properly meet the many usecases developers have with it.

**Comment by sreenadh** [comment]
@samdark Is it true that Yii is dropping support for Pjax?
