### ISSUE TITLE
Duplicate migration in app\migrations

### ISSUE THREAD

**Issue by Nex-Otaku** [yiisoft/yii2#14536]
### What steps will reproduce the problem?
Create new migration in "app\migrations" namespace:
```
yii migrate/create app\migrations\test
yii migrate
```
### What is the expected result?
One new namespaced migration.
### What do you get instead?
Two new migrations, one is namespaced, other is not.
```
Total 2 new migrations to be applied:
        M170723065656Test
        app\migrations\M170723065656Test
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.0
| Operating system | Windows (OpenServer)

### P.S.

It appears only in "app\migrations" namespace. Other namespaces work correctly.

**Comment by klimov-paul** [comment]
Obviously you have setup `migrationPath` to the same folder, which contains namespaced migrations.

**Comment by samdark** [comment]
@klimov-paul shound't we check that classes are actually in the correct namespace?

**Comment by klimov-paul** [comment]
Since #14241 merged, I can not answer this question - I do not know.

**Comment by samdark** [comment]
@cebe ?

**Comment by Nex-Otaku** [comment]
This is configuration from official docs.
```
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'app\migrations', // Общие миграции для проекта
            ],
        ],
    ],
```
It is not working. So either is is a bug, or a type in documentation. 
Please check it.

**Comment by cebe** [comment]
this is unrelated to #14241, the issue happens when you configure `migrationNamespaces` to include `app\migrations` but leave  `migrationPath` as the default value, which is also `'@app/migrations'`
