### ISSUE TITLE
_csrf cookie sometimes generates invalid values which triggers ModSecurity

### ISSUE THREAD

**Issue by Mithrandil** [yiisoft/yii2#14542]
### What steps will reproduce the problem?
activate ModSecurity (always active on shared hostings providers like OVH)
include this in the controller:

public function beforeAction($action) {
        if($action->id == 'index'){
            $this->enableCsrfValidation = false;
            $cookies = Yii::$app->response->cookies;
            $cookies->remove('_csrf');
            unset($cookies['_csrf']);
        }
        return parent::beforeAction($action);
    }

and refresh the index action a few times to generate new _csrf cookies

after some refreshes (randomly) it creates a "bad cookie"

### What is the expected result?

standard index page

### What do you get instead?

403 Forbidden
You don't have permission to access / on this server. 

nor any other page, ModSecurity stops it before reaching the actual index.php file

(you get the bad cookie about once every 10 refreshes, and need to delete the cookie to start it behave normally again)

example of "bad" cookie content: "964315fe9b4ea193c9706742f641945b5e64db97e407423a84ca465195f684b1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22%EE3%3C%0B%02%9D%5C%91%5D%E4_Z%96%F9%BB%3F%CE%00%EB%B8%A5n%D6%DE%9D%98%8F%9A%1FJ%E5%60%22%3B%7D"

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.0.17
| Operating system | Linux 4.4.67-ovh-vps-grsec-zfs-classid

**Comment by samdark** [comment]
Any idea why it triggers it?

**Comment by Mithrandil** [comment]
this is one of the error log lines, but i don't really understand the problem... it's not my field...

[Thu Jul 27 08:23:23 2017] [error] [client xx.xx.xxx.xxx] ModSecurity: Access denied with code 403 (phase 2). Found 1 byte(s) in REQUEST_HEADERS:Cookie outside range: 1-255. [file "/usr/local/apache2/conf/modsecurity/base_rules/modsecurity_crs_20_protocol_violations.conf"] [line "252"] [id "960901"] [rev "2.1.1"] [msg "Invalid character in request"] [severity "WARNING"] [tag "PROTOCOL_VIOLATION/EVASION"] [tag "WASCTC/WASC-28"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE3"] [tag "PCI/6.5.2"] [tag "http://i-technica.com/whitestuff/asciichart.html"] [hostname "XXXXXX.net"] [uri "/index.php"] [unique_id "WXmG2woAV1EAAH5oQPYAAAC4"]

**Comment by samdark** [comment]
Aha. That is helpful. Thanks.

**Comment by rob006** [comment]
Why we are using binary data as csrf token instead of random string?

**Comment by samdark** [comment]
We've used to base64() the date before but few releases ago started to use raw binary date. It seemed right at that time cause browsers are fine with that.

When fixed there should be a test that ensures ASCII is written in the cookie.

**Comment by samdark** [comment]
@Mithrandil please check if ModSecurity is happy with pull request branch. Thanks.
