### ISSUE TITLE
Testing common directory problem

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#14556]
### What steps will reproduce the problem?

1. Run Codeception test in `common` directory throws exception about not having `cookieValidationKey` parameter in `common/config/main.php` or `main-local.php` in my case, as it is on local at the moment. 
2. I added the following lines to the `main-local.php` to make tests runnable in common directory: 
```php 
'request' => [
    'enableCookieValidation' => true,
    'cookieValidationKey' => 'my-cookie-validation',
],
```

However this only fixes problem with tests and breaks console part of the web-app - `php yii`. 

By running this command, it throws the followin Exception message: 
```
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::enableCookieValidation'
... 
(full stack trace can be seen below in this issue)
```

And it does not make sense why it is using `common` directory config, because it should be using separate console config file (I understood from [this](https://github.com/yiisoft/yii/issues/3488) issue).

### What is the expected result?

* `php yii` should work without any problem. 
* tests in `common` directory should work without any problems regarding `cookieValidationKey` parameter.   

### What do you get instead?

Exception while using `php yii` in the root. 

Stack trace: 
```
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::enableCookieValidation'

in /var/www/app/vendor/yiisoft/yii2/base/Component.php:201

Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/BaseYii.php(529): yii\base\Component->__set('enableCookieVal...', true)
#1 /var/www/app/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(yii\console\Request), Array)
#2 [internal function]: yii\base\Object->__construct(Array)
#3 /var/www/app/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\console\Req...', Array, Array)
#5 /var/www/app/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\console\Req...', Array, Array)
#6 /var/www/app/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#7 /var/www/app/vendor/yiisoft/yii2/console/Application.php(219): yii\di\ServiceLocator->get('request')
#8 /var/www/app/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->getRequest()
#9 /var/www/app/yii(27): yii\base\Application->run()
#10 {main}
PHP Warning:  array_map(): An error occurred while invoking the map callback in /var/www/app/vendor/yiisoft/yii2/log/FileTarget.php on line 106
PHP Stack trace:
PHP   1. yii\base\ErrorHandler->handleException() /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php:0
PHP   2. yii\log\Logger->flush() /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php:113
PHP   3. yii\log\Dispatcher->dispatch() /var/www/app/vendor/yiisoft/yii2/log/Logger.php:177
PHP   4. yii\log\Target->collect() /var/www/app/vendor/yiisoft/yii2/log/Dispatcher.php:188
PHP   5. yii\log\FileTarget->export() /var/www/app/vendor/yiisoft/yii2/log/Target.php:124
PHP   6. array_map() /var/www/app/vendor/yiisoft/yii2/log/FileTarget.php:106
```

### Additional info
[This](https://github.com/yiisoft/yii/issues/3488) somewhat related to my issue, but it was not solved, so the problem still exists.  

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04

**Comment by dynasource** [comment]
thats because your `console/config/main.php` includes your `common/config/main.php`. If you use properties that are not supported in the `console` context, you will get errors like these. 

The solution is in setting the $enableCookieValidation only in the specific tiers (frontend / backend)

**Comment by bologer** [comment]
@dynasource, not sure where you found `main.php` included in `console/config` folder: 

```php 
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'console\controllers',
    'controllerMap' => [
        'fixture' => [
            'class' => 'yii\console\controllers\FixtureController',
            'namespace' => 'common\fixtures',
        ],
        'stubs' => [
            'class' => 'bazilio\stubsgenerator\StubsController',
        ],
    ],
    'components' => [
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
    ],
    'params' => $params,
];
```

**Comment by dynasource** [comment]
@bologer, check the code at https://github.com/yiisoft/yii2-app-advanced/blob/974b233fdfccee02deaca376158c88f833bc30e7/environments/dev/yii

**Comment by bologer** [comment]
@dynasource I don't really get the way to solve it. Could you please write at least basic guidance for this issue? I think somebody have crossed it as well, however I did not find anything on the Internet.

**Comment by bologer** [comment]
@cebe, @samdark, @dynasource what is the purpose of having tests  in `common` directory when it throws exception of not having `$cookieValidationKey`, but when you add it, it throws exception in console when running `php yii`. 

I have many classes in `commond\models` that are shared between two ends and it seems to be logical to have tests in common then splitting them. 

Or is it better to have them separated (fronend/backend)?

**Comment by dynasource** [comment]
I agree this to be a side effect of using `common` configuration. Some configuration cannot simply be shared between `console` and the other web tiers such as `frontend` and `backend`.

You have a few choices here.
# Either you put `cookieValidationKey` not in the common config so that it wont be loaded by the `console`.
# You can remove certain configuration options before loading into the console application
# You choose to create an advanced `common/main.php` in which certain properties are not set in the `console` context

**Comment by Patricy** [comment]
For migrations and other yii scripts - we do not need to use cookieValidationKey, but for test reasons - we need.
As workaround:

Default test config  **common/config/test.php**:
```php
<?php
return [
    'id' => 'app-common-tests',
    'basePath' => dirname(__DIR__),
    'components' => [
        'user' => [
            'class' => 'yii\web\User',
            'identityClass' => 'common\models\User',
        ],
        'request' => [
            'cookieValidationKey' => 'test',
        ],
    ],
];
```

Working test config **common/config/test.php**:

```php
<?php
$testConfig = [
    'id' => 'app-common-tests',
    'basePath' => dirname(__DIR__),
    'components' => [
        'user' => [
            'class' => 'yii\web\User',
            'identityClass' => 'common\models\User',
        ],
    ],
];
if (stristr($_SERVER['PHP_SELF'], 'codecept')){
    $testConfig['components']['request']['cookieValidationKey'] = 'test';
}

return $testConfig;
```

**Comment by misq007** [comment]
As a side note, I want to explain why I too get:
"PHP Warning:  array_map(): An error occurred while invoking the map callback in /vendor/yiisoft/yii2/log/FileTarget.php on line 107"

I found that if you have a custom Identity and in the getId implementation you throw an exception - then the \yii\log\Target::getMessagePrefix throws it and you get array_map warning.
