### ISSUE TITLE
Cannot add new targets to component "log" in module.

### ISSUE THREAD

**Issue by sergey-program** [yiisoft/yii2#14567]
Expected that code will add new log target

```
namespace backend\modules\auth;

use backend\components\ModuleExtended;
use yii\log\Dispatcher;

class AuthModule extends ModuleExtended
{
    /**
     *
     */
    public function init()
    {
        parent::init();
        
        \Yii::configure($this, [
            'components' => [
                'log' => [
                    'class' => Dispatcher::className(),
                    'targets' => [
                        [
                            'class' => 'yii\log\FileTarget',
                            'categories' => ['auth'],
                            'levels' => ['error', 'warning', 'info'],
                            'logFile' => '@runtime/logs/module.auth.log'
                        ]
                    ]
                ]
            ]
        ]);
        
    }
}
```

1. I MUST define log->class. Otherwise exception. Strange behavior because log shoule exist on this execution in components (global config has base definition for 'categories' => 'application' (default).
2. Config\components not updated after this init. So \Yii::info('some1', 'auth'); is not working at all. But if I define this one in global config - it works. 

Is it okay? What I do wrong?

**Comment by sergey-program** [comment]
If we define in global config file in this way...

```
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'categories' => ['application'],
                    'levels' => ['error', 'warning']
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'categories' => ['auth'],
                    'levels' => ['error', 'warning', 'info'],
                    'logFile' => '@runtime/logs/module.auth.log'
                ]
            ],
        ],
```

It works as should.

PS: I'm trying to configure one module - one log file.

**Comment by cebe** [comment]
There can only be one log dispatcher attached to Yii logger. Your code will detach application Dispatcher instance and connect module Dispatcher instead. if you want to have a log target added by your module, you can add it like `Yii::$app->log->targets[] = Yii::createObject([ /* target config here */]);`

**Comment by sergey-program** [comment]
Yeah, but I thought it should be merged with global one (I mean targets). Ok, anyway ty.
