### ISSUE TITLE
Use safeUp/safeDown methods by default for migration templates

### ISSUE THREAD

**Issue by MKiselev** [yiisoft/yii2#14568]
In #13827 was added behavior to generate safe methods by default.

Maybe also add this to any migrations templates?

I think this good idea. 

Also MySQL from 8 version will be with  transnationally DDL.

https://github.com/yiisoft/yii2/blob/master/framework/views/dropTableMigration.php#L30
https://github.com/yiisoft/yii2/blob/master/framework/views/dropTableMigration.php#L42

https://github.com/yiisoft/yii2/blob/master/framework/views/dropColumnMigration.php#L32
https://github.com/yiisoft/yii2/blob/master/framework/views/dropColumnMigration.php#L45

https://github.com/yiisoft/yii2/blob/master/framework/views/createTableMigration.php#L31
https://github.com/yiisoft/yii2/blob/master/framework/views/createTableMigration.php#L44

https://github.com/yiisoft/yii2/blob/master/framework/views/createJunctionMigration.php#L31
https://github.com/yiisoft/yii2/blob/master/framework/views/createJunctionMigration.php#L73

https://github.com/yiisoft/yii2/blob/master/framework/views/addColumnMigration.php#L33
https://github.com/yiisoft/yii2/blob/master/framework/views/addColumnMigration.php#L46

**Comment by samdark** [comment]
Agree.

**Comment by MKiselev** [comment]
@samdark ok. I will fix it..
