### ISSUE TITLE
Migration: Relation to bigPrimaryKey() column fails with '150 Foreign key constraint is incorrectly formed'

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2#14561]
### What steps will reproduce the problem?
Create a migration like:

    $this->createTable('{{%payment}}', [
        'id' => $this->bigPrimaryKey(),
    ]);

In another migration, create a relation to that id column:

    $this->createTable('{{%commission}}', [
        'id' => $this->bigPrimaryKey(),
        'payment_id' => $this->integer(),
    ]);

    $this->addForeignKey('fk_commission_payment_id', '{{%commission}}', 'payment_id', '{{%payment}}', 'id', 'CASCADE', 'CASCADE');

### What is the expected result?
It should work just like `primaryKey()`. I actually swapped `bigPrimaryKey` with the normal `primaryKey` and the same migration worked flawlessly. Proof that `bigPrimaryKey` was the culprit.

### What do you get instead?
    > add foreign key fk_commission_payment_id: {{%commission}} (payment_id) references {{%payment}} (id) ...Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table `yii2-test`.`#sql-599a_435` (errno: 150 "Foreign key constraint is incorrectly formed")
    The SQL being executed was: ALTER TABLE `commission` ADD CONSTRAINT `fk_commission_payment_id` FOREIGN KEY (`payment_id`) REFERENCES `payment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE'

    in /Applications/XAMPP/xamppfiles/htdocs/yii2-test/vendor/yiisoft/yii2/db/Schema.php:636

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6.21
| DB version      | 10.1.13-MariaDB - Source distribution
| Operating system | macOS Sierra 10.12.5 running XAMPP

**Comment by Renkas** [comment]
@WadeShuler there's nothing wrong on Yii code. You need to use appropriate field types. use `bigInteger` instead of `integer`.

**Comment by WadeShuler** [comment]
omg I knew this! Sorry, I built the migration 2 weeks ago before I went on vacation. I hate leaving a project and trying to pick up where I left off...
