### ISSUE TITLE
Logs by year/month/day

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#14565]
### What steps will reproduce the problem?

Not really a problem, mostly feature request, as I did not find any requests for it. 

### What is the expected result?

Having common `logs` folder in root of the web-application with the following structure: 

```
common
backend
frontend
logs
  - 2017
  - - 07
  - - - 21
  - - - - categoryName.log
```

Maybe it could be another option in logs config such as the following:  
```php 
'log' => [
    'traceLevel' => 0,
    'dateTimeTreeView' => true,
```

Or maybe `dateTimeTreeView` can be only attached to specific targets. 

I started something already, but it is pretty raw: 

```php 
<?php 
/**
     * Possibility to ovverride file name from other controllers
     *
     * @var string
     */
    public $logFileName = 'backend';

    /**
     * Log starting sequence
     *
     * @var string
     */
    public $logPre = '----> ';

    /**
     * Array list of restricted actions.
     * For these actions, data in the _POST would not be recorded
     * @var array
     */
    public $logRestrictedActions = [];

    /**
     * Before controller runs
     *
     * @param \yii\base\Action $action
     * @return bool
     */
    public function beforeAction($action)
    {

        /**
         * Generate path
         *
         * @app by default is the root of the project according to the side (backend/frontend).
         * If controller is placed within backend, it will recognize it
         */
        $path = \Yii::getAlias('@app') . '/../log/';
        $year = date('Y') . '/';
        $month = date('m') . '/';
        $day = date('d');

        /**
         * Make the path. It consists of year, month and day
         */
        $path = $path . $year . $month . $day;


        /**
         * Create derictories
         *
         * http://www.yiiframework.com/doc-2.0/yii-helpers-basefilehelper.html#createDirectory()-detail
         */
        BaseFileHelper::createDirectory($path, 0777, true);

        /**
         * Save the file in the directory of $path + name of the log file + name of the controller ($this->id)
         *
         * @var $path
         */

        Yii::$app->log->targets[0]->logFile = \Yii::getAlias($path . '/' . $this->logFileName . '_' . $this->id . '.log');

        ...

        return parent::beforeAction($action);
    }
```

This is custom controller that extends `yii\web\Controller`. 

Now I can create logs in thefollowing format "frontend_{controllerName}.log". 

This is not the best solution, but I believe it will be useful to have for some projects. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04

**Comment by samdark** [comment]
Interesting idea and could be actually handy if you read logs without any aggregation tool. Not a priority though.

**Comment by rob006** [comment]
Did you try:

```php
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'logFile' => '@runtime/logs/' . date('Y') . '/' . date('m') . '/' . date('d') . '/app.log',
                ],
            ],
        ],

?

**Comment by bologer** [comment]
@rob006 , yeah, but in this case you need to now for sure that this folder stucture exists, othertwise it will fail. 

This is first thing. And second is that this is not handy solution if you have multiple targets, etc.

**Comment by rob006** [comment]
> yeah, but in this case you need to now for sure that this folder stucture exists, othertwise it will fail.

Are you sure about that? Directory structure should be created by target: https://github.com/yiisoft/yii2/blob/master/framework/log/FileTarget.php#L88-L91

> This is first thing. And second is that this is not handy solution if you have multiple targets, etc.

You could create own target which extends `FileTarget` and only adjusts `logFile` property.

**Comment by bologer** [comment]
@rob006 well, I thought that it does not create new directories, but as I noticed now, it does work. 

I tried to extend `FileTarget` class last time and it did not work well for me. I wil try to do it again and will write here the reuslt. 

Thanks for suggestion.

**Comment by samdark** [comment]
Closing since it works well.
