### ISSUE TITLE
Instalation error from composer

### ISSUE THREAD

**Issue by rfiedler** [yiisoft/yii2#14569]
### What steps will reproduce the problem?

vagrant@vagrant:/home/hphu/public_html$ composer global require "fxp/composer-asset-plugin:^1.3.1"

Changed current directory to /home/vagrant/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

vagrant@vagrant:/home/hphu/public_html$ composer create-project --prefer-dist yiisoft/yii2-app-basic basic
Installing yiisoft/yii2-app-basic (2.0.12)
  - Installing yiisoft/yii2-app-basic (2.0.12): Downloading (100%)
Created project in basic
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-gii 2.0.5 requires bower-asset/typeahead.js 0.10.* | ~0.11.0 -> no matching package found.
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.3 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.2 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.1 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.0 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - Installation request for yiisoft/yii2-gii ~2.0.0 -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by SilverFire** [comment]
Application template is not released yet, while documentation is already updated. Use `@dev` version to force composer use latest available code:

> composer create-project --dev --prefer-dist yiisoft/yii2-app-basic**:@dev** basic
