### ISSUE TITLE
Attributes not in scenario while be save

### ISSUE THREAD

**Issue by CuiKeng** [yiisoft/yii2#14571]
### What steps will reproduce the problem?
Step 1: Define an activeReocd
Step 2: Define scenarios with several attributes
Step 4: Set scenario
Step 3: Set all attributes 
Step 4: Save model
### What is the expected result?
Insert(Update) field in scenario, others are not.
### What do you get instead?
When use $model->setAttributes($attributes) , field not in scenario not be save. Correct!
When use $model->attribute = $attribute, field not in scenario be save. Wrong?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 
| Operating system |

**Comment by klimov-paul** [comment]
This is expected behavior.
