### ISSUE TITLE
DynamicModel inline validator

### ISSUE THREAD

**Issue by CuiKeng** [yiisoft/yii2#14572]
### What steps will reproduce the problem?
DynamicModel::validateData(compact('amount', 'num'), [
    ['amount', function ($attribute, $params) {
        $this->addError('This is error msg.');
    }]
])
### What do you get instead?
It does not work, $this is not DynamicModel

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 
| Operating system |

**Comment by klimov-paul** [comment]
It can not function as `$this` inside a `\Closure` refers to the container object, which declared Closure - not the one, which calls it.
