### ISSUE TITLE
filemtime

### ISSUE THREAD

**Issue by sergnochevny** [yiisoft/yii2#14579]
Please prepare to using filemtime() by file_exist() else it is throwing exception E_WARNING.

**Comment by sergnochevny** [comment]
Apache_php_7x64, Php 7x64, windows machine: 
![image](https://user-images.githubusercontent.com/15010230/28886536-85b5bf6e-77c2-11e7-86bb-81a06ace3d28.png)

**Comment by rob006** [comment]
You should disable [scream](http://php.net/manual/en/scream.configuration.php) in your php config.

**Comment by sergnochevny** [comment]
Please don`t use @. at all. it`s bad form.

**Comment by sergnochevny** [comment]
I haven' got this variable in config. By default Off.

**Comment by sergnochevny** [comment]
$cacheFile = $this->getCacheFile($key);
        if (file_exists($cacheFile) && (filemtime($cacheFile) > time())) {

**Comment by rob006** [comment]
This will fail anyway if file will be deleted by other process between `file_exists()` and `filemtime()` calls, so it does not fix anything. 

Check result of `phpinfo()` to make sure that you don't have `scream` enabled.
