### ISSUE TITLE
Language-specific Inflection

### ISSUE THREAD

**Issue by wapmorgan** [yiisoft/yii2#14597]
Yii2 has a special helper for inflection of nouns, but this is just for English.

### The problem
English is the most popular language, but Yii is used around the world and English is not enough.
- https://en.wikipedia.org/wiki/Languages_used_on_the_Internet
As we can see, English is used only on 1/2 of all sites in the internet (approximately).
The second language by popularity is Russian (and my native), next is Japanese, German and Spanish. These 4 languages used on ~23% sites.

### My proposition
1. Add a language-specific inflectors instead alongside with BaseInflector (and rename it to EnglishInflector).
2. Create a factory for inflection, which will returns an appropriate inflector based on current **language** settings.

### How it can be
1. `yii\helpers\BaseInflector` => `yii\inflection\EnglishInflector`
2. Create language-specific inflector with name `yii\inflection\LANGInflector`
3. Create a factory which will return an inflector like `yii\inflection\Factory::get()`

**Comment by wapmorgan** [comment]
I can take a part of implementing this. I can make `RussianInflector` with only one dependency.
If you let me, I'd create a PR with these changes to review.

**Comment by samdark** [comment]
Is there such data in the intl extension? Defining inflection rules for all languages will blow framework size too much, I think.

**Comment by wapmorgan** [comment]
1. No, such data is not present in intl.
2. Yes, framework will be big, all russian-specific rules [takes about **~302 KB**](https://github.com/wapmorgan/Morphos).
3. But now Yii2 repo takes few mb's. I think it's worth to spend 1-1.5 mb's to support at least top-10 languages.

**Comment by samdark** [comment]
I think it would be too much. English inflection rules are very simple and are used by framework itself. Other languages aren't simple and for each one there's a set of rather complicated rules.

Moreover, Morphos is available via composer so it's easy to reuse.

Therefore, I don't think it worth re-inventing the wheel in this case. We can't really make it better than it already is.

**Comment by wapmorgan** [comment]
I've created a small extension for english / russian inflection and other stuff. Can you take a look and may be mention it in your blog? :) https://github.com/wapmorgan/yii2-inflection
