### ISSUE TITLE
Enh: Compare composite key in `Query::where()`

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#14592]
Let a table has composite key or index `(a, b, c)`.

When I need to query rows next to specific one `['a' => 10, 'b' => 'foo', 'c' => 20]`
with `ORDER BY a, b, c`, I need to get condition like this:

```sql
a > 10 OR (a = 10 AND (b > 'foo' OR (b = 'foo' AND c > 20)))
```

It would be nice to do this like so:

```php
$query->where(['>', ['a', 'b', 'c'], $key]);
```

Here `$key` may be either `[10, 'foo', 20]` with values in the order 
or `['a' => 10, 'b' => 'foo', 'c' => 20]` with key=>value in any order.

This feature can be applied to operators `>`, `>=`, `<` and `<=`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12

**Comment by Vovan-VE** [comment]
Patch is ready. Tests are passing. Waiting if the feature is needed ever and, if so, version to introduce in.

**Comment by Renkas** [comment]
Can't see the pull request anywhere ...

**Comment by Vovan-VE** [comment]
I did not publish it yet.

**Comment by githubjeka** [comment]
Good work, but 👎 

You could use query builder like this:
```php
$query = new \yii\db\Query();
echo $query
    ->where('a>:a', [':a' => 10])
    ->orWhere(['AND', 'a=:a', ['OR', 'b>:b', ['AND', 'b=:b', 'c>:c']]], [':b' => 'foo', 'c' => 20])
    ->createCommand()->rawSql;

// SELECT * WHERE (a>10) OR ((a=10) AND ((b>'foo') OR ((b='foo') AND (c>20))))
//    vs                       a > 10 OR (a = 10 AND (b > 'foo' OR (b = 'foo' AND c > 20)))
```

**Comment by Vovan-VE** [comment]
@githubjeka , will you change yor opinion after reteating these code many times in refactoring migrations for example?

**Comment by githubjeka** [comment]
Can you add more info about your 

>When I need to query rows next to specific one `['a' => 10, 'b' => 'foo', 'c' => 20]`
with `ORDER BY a, b, c,` I need to get condition like this

I can not figure out whether this is often necessary in life, or it came from the project you are working on.

**Comment by samdark** [comment]
@Vovan-VE sorry, but it looks like too specific use case. Also it's achievable with regular query builder syntax as @githubjeka pointed out.
