### ISSUE TITLE
Support iterable in `QueryBuilder::batchInsert`

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#14609]
### What steps will reproduce the problem?
Pass an iterable to `QueryBuilder::batchInsert()`.

## What is the expected result?
That it works for both empty and non empty iterables.

### What do you get instead?
Empty iterables create a bad query; the snippet below will never trigger for iterables since they are objects. Same goes for things like `ArrayObject`, they behave close to an object but they are never empty according to `empty()`. 

````
        if (empty($rows)) {
            return '';
        }
````

### Additional info
This can be resolved by not checking if `$rows` is empty (one cannot check if an iterable is empty).
Instead we should just iterate over the rows and at the end check if `$values` is empty.
The overhead of this approach would be that the table schema gets initialized regardless of whether rows are empty or not.

I'm up for making a PR, just need to know if you agree with the tradeoff between usability and (theoretical) performance.

| Q                | A
| ---------------- | ---
| Yii version      | latest
| PHP version      | N/A
| Operating system | N/A

**Comment by samdark** [comment]
Can't we check if it's an array and only then check for `empty()`?

**Comment by SamMousa** [comment]
Yes we can, so then you get 2 checks, 1 before 1 after?

**Comment by samdark** [comment]
No. I mean modifying a check the following way:

```php
if (is_array($rows) && empty($rows)) {
    return '';
}
```

**Comment by SamMousa** [comment]
Yes but if it is not an array it can still be an empty iterable; so in that case we would need to check if `$values` are empty after the iteration.

**Comment by samdark** [comment]
Ah. Yes. That part won't change.

**Comment by SamMousa** [comment]
So you prefer to have 2 checks then so that we have the optimization of not creating the schema for empty arrays?

(In my opinion it is a minor / irrelevant optimization, how many people will be calling batchInsert repeatedly with empty datasets?)

**Comment by samdark** [comment]
Yes, I prefer two checks. I don't like de-optimizing our code.
