### ISSUE TITLE
Can we have option to yii migrate/up without user input?

### ISSUE THREAD

**Issue by Offout** [yiisoft/yii2#14601]
In my gilab-ci I need to run functional, and in perspective appliance Codeception tests.
Also I have deploy.sh script in production.
Now I can't run migrate/up before tests, without expect script:

`expect -c 'spawn php /www/yii migrate/up; expect "yes" {send -- "yes\r"}; expect "successfully" {send -- "\r"}'`

Can we have '-y' option to migrate without asking user input?

https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php#L181

I can implement it if you tell me what is correct way to do that.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.1
| Operating system | Doesn't matter, Linux

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L51-L54
