### ISSUE TITLE
Move Application::setContainer to Module

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#14600]
not all $container configuration covers the complete `Application` scope. Something you simply want to add container configuration in a `Module` scope.

For this reason, moving the `setContainer` logic up in the inheritance tree to `Module` sounds logical to me.

**Comment by samdark** [comment]
Agree.

@SilverFire what do you think?

**Comment by klimov-paul** [comment]
>Something you simply want to add container configuration in a Module scope.

Just how this suppose to work? `Application::setContainer()` is a simple shortcut for accessing `Yii::$container`, which is a global singleton. This method was created to simplify configuration files.

Having `setContainer()` at the module level produces ambigous code: developer would expect that DI adjustments declared at module level will affect only module internal code, while it is not true.
Unless each module will have its own DI container, I am against such change.

**Comment by samdark** [comment]
I agreed thinking about each module having its own DI container. @dynasource is that what you've meant additionally?

**Comment by SamMousa** [comment]
The trouble is that part of the module will not be aware of this new container.
For example things like AR don't really know which `Module` instance they belong to; so how will they know where to get the container?

What (I think) Laravel does for DI is to pass a sender / context in as well. That way you can actually provide different DI configuration based on who / what is instantiating something, without having multiple DI containers.

What is the issue you're solving @dynasource ? Is it module specific configuration that you do not need globally, or is it module specific configuration that is different from the global configuration?
Can you give an example?

**Comment by samdark** [comment]
What I was thinking is module specific config that isn't needed out of the module context.

**Comment by SamMousa** [comment]
Yes, but what is the Module context? Is it anything that is shipped with the module? How do those contexts actually work?

Note that from that perspective your Module is actually a Service Locator for your container. So it would be fine to register your container as a component for the Service Locator...

Then you can do `$module->get('container')->...`.

I'm not a fan of the global singleton approach, but I do not see a good alternative yet..

**Comment by samdark** [comment]
By module context I mean context of executing a module controller via accessing a moule.

**Comment by SamMousa** [comment]
Thinking about this some more, I feel moving it to Module is just going down a wrong path even further.

https://github.com/yiisoft/yii2/commit/437825be70c0bd72b582244c243cc985c11f46d6

The argument to have this in application is just to configure it via application settings... That approach dilutes the fact that the container is a global singleton.

The goal should not be to just move all configuration to application, alternatively use some other class that configures both an application object as well as the other globals like container...

**Comment by samdark** [comment]
Won't be implemented in 2.0.
