### ISSUE TITLE
CompareAttribute does not work when you change input ID to compare against

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#14604]
### What steps will reproduce the problem?
Create simple form model with attributes;
newPassword
newPasswordRepeat

make Compare attribute on top of them, so that newPasswordRepeat checks if it is the same as newPassword

on view change newPassword ID
### What is the expected result?
newPasswordRepeat should check against forms newPassword
### What do you get instead?
since it assumes that no-one changes input ID s it will never be true

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  5.6.30
| Operating system | Ubuntu 16.10

**Comment by samdark** [comment]
Makes sense.
