### ISSUE TITLE
JQuery asset is broken

### ISSUE THREAD

**Issue by zlakomanoff** [yiisoft/yii2#14619]
### What steps will reproduce the problem?
`php composer.phar create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic
`
### What is the expected result?
Hello world

### What do you get instead?
```
Invalid Parameter – yii\base\InvalidParamException

The file or directory to be published does not exist: /home/alex/www/basic/vendor/bower-asset/jquery/dist
```

### Additional info
Looks like jquery repo have no dist directory

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1.7
| Operating system | Arch Linux

**Comment by SilverFire** [comment]
There was a problem somewhere between jQuery package, Bower and asset-packagist. Today we've discovered that [the asset package on asset-packagist.org](https://asset-packagist.org/package/bower-asset/jquery) was updated to a wrong state. Re-updating solved the problem. We've tried to reproduce the problem, but failed.

**Comment by SilverFire** [comment]
In case the application installation still fails, try to run `composer clear-cache`
