### ISSUE TITLE
[3.0] Improve use of static variables.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#14614]
This is meant for a general discussion of the development direction. I'm aware that Yii currently uses the singleton pattern combined with Service Locator a lot, I'm just not sure it is the best solution in all cases where it is currently used.

Yii uses many static variables to get around the need for passing around references.
For example:
````
\Yii::$container
\Yii::$app
\Yii::$logger
\Yii::$aliases
\Yii::$classMap
````

Since most of these are actually application scoped, it makes sense to move them inside the application object and, where really needed, provide shortcuts to access it.

That way we could reduce the number of global static variables to just 1: `\Yii::$app`.

**Comment by klimov-paul** [comment]
At least following ones can not be moved to application scope anyhow:

```
\Yii::$container
\Yii::$logger
\Yii::$classMap
```

as thier existance must be ensured before application instance created.

In particular `\Yii::$classMap` is a part of autoloading which affects finding source for `yii\base\Application`.
Same for `\Yii::$container`. `\Yii::$logger` can be invoked before application is instantiated or during application instantiation.

**Comment by SamMousa** [comment]
I'm aware that they currently all have their uses; I'm just not sure they all need to be public static variables.

The autoloader for example doesn't have to be a in the `Yii` class at all, it could (should?) be a separate class according to the SRP. Depending on if we even need a classloader in Yii when we can just use `composer dumpautoload --optimize`.

The container can definitely be moved to application, it is just a choice. For example the basic template does not even use the container to create the application:
````
https://github.com/yiisoft/yii2-app-basic/blob/master/yii#L19
````
- If that is the case why even create it outside and not just have the application create and manage it? (That's just one option, not sure it is my preferred one)
- Or maybe pass the DI container to the application via its constructor.
- Or have the container instantiate the application and inject itself. Symfony does that: (http://api.symfony.com/2.7/Symfony/Component/DependencyInjection/ContainerAware.html)

There are plenty of options.

The logger is the same thing. Using it without an application will just eat memory but never flush it anywhere. When the application loads the first thing it does is initialize the log component.
The only thing creating log entries at that point is the application bootstrap code itself...

Many of these things have some kindo of circular reference thing going on with the application singleton,

**Comment by SamMousa** [comment]
`$classMap` has been removed in 3.0.

**Comment by samdark** [comment]
Others are hard to move out w/o causing much trouble. Won't do it for 3.0. Maybe future versions.
