### ISSUE TITLE
Here you need to add filter conditions such as empty strings and empty arrays

### ISSUE THREAD

**Issue by dnslj** [yiisoft/yii2#14617]
https://github.com/yiisoft/yii2/blob/af71e0fca0b8cc7ea11ce18824d3e9a7af6866ef/framework/helpers/BaseArrayHelper.php#L117

Here you need to add filter conditions such as empty strings and empty arrays

The updated code:

![tim 20170809141703](https://user-images.githubusercontent.com/2264884/29107591-78c6b13c-7d0d-11e7-863a-3b54d78c5569.jpg)

**Comment by dnslj** [comment]
Sometimes the configuration file is empty array [], with this method when the merger will be reported

**Comment by cebe** [comment]
what is the code you call the merge() method with that is causing problems? I do not see any issue with it.

**Comment by rob006** [comment]
@cebe Merging 2 empty arrays will return `null` instead of array: `array_shift()` returns `null` for empty array:

https://3v4l.org/kSNvT

**Comment by cebe** [comment]
`array_shift` is called on the arguments of the method, which are at least 2 and the while loop checks if the array is empty, I do not see how it can return null here. https://github.com/yiisoft/yii2/blob/711498f93a282b4ae54e6c0776f3f7b750f56442/framework/helpers/BaseArrayHelper.php#L119-L122

**Comment by rob006** [comment]
Right, I looked at screen from first post instead of source code... 🤦‍
