### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by ChangePlaces** [yiisoft/yii2#14616]
### What steps will reproduce the problem?

- `composer global require "fxp/composer-asset-plugin:^1.3.1"`
- `composer require yiisoft/yii2`

### What is the expected result?
happy composer installation

### What do you get instead?
`could not fetch https://api.github.com/jquery/jquery-dist, please create a Github OAuth token to go over the API rate limit...`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.0
| Operating system |ubuntu

**Comment by samdark** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by ChangePlaces** [comment]
That's great and all and I can read the full error message, but I've never had to add a Github token to install something because there are other repository managers publicly available - that's a bit of a bug.

**Comment by samdark** [comment]
With the next release there will be less queries from Composer like that because we're switching from fxp plugin to asset-packagist. Can't affect the issue more...

**Comment by ChangePlaces** [comment]
Are there any open issues on this? What release - major or minor release?

**Comment by samdark** [comment]
2.0.13
