### ISSUE TITLE
Add .off() for submit event

### ISSUE THREAD

**Issue by krab123** [yiisoft/yii2#14627]
https://github.com/yiisoft/yii2/blob/af71e0fca0b8cc7ea11ce18824d3e9a7af6866ef/framework/widgets/Pjax.php#L212

fix to: 
$js .= "\njQuery(document).**off($submitEvent, $formSelector)**.on($submitEvent, $formSelector, function (event) {jQuery.pjax.submit(event, $options);});";

**Comment by krab123** [comment]
The problem occurs if the view with pjax is loaded via ajax (for example, in tab). If you repeatedly switch tab, then several events will be generated - by the number of loads of the view.

**Comment by samdark** [comment]
Need code to reproduce it locally...
