### ISSUE TITLE
session_regenerate_id(): Session object destruction failed

### ISSUE THREAD

**Issue by shankar14** [yiisoft/yii2#14624]
i have set email and password for login.once i continuously logout above 3 times it returns this error in yii2
![logout](https://user-images.githubusercontent.com/26651852/29131780-93375dbc-7d4b-11e7-90ea-b1d4a1482694.png)

**Comment by samdark** [comment]
Are you able to reproduce it with basic application template?

**Comment by shankar14** [comment]
no am working in advanced template.could you tell me how to clear this error

**Comment by samdark** [comment]
No since I have no idea on how to reproduce it.

**Comment by shankar14** [comment]
anyway thanks man :)

**Comment by mmezzawi** [comment]
Step to reproduce : 
1 - add sleep(7) in before logout  
2- login 
3- duplicate tab ( open two tabs )
4- click logout in the first then logout in the second tab 

Result : 
session_regenerate_id(): Session object destruction failed. ID: files 
As shown above 

Thanks
