### ISSUE TITLE
[bug/feature-request] Unable share any parameters to mail layout

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii2#14637]
### What steps will reproduce the problem?

I want to add in layout mail-tail with parameters - user unsubscription link and  user personal manager contact

### What is the expected result?

that i can got it in layout with $this->params, or from custom variables 

### What do you get instead?

that it impossible by design - https://github.com/yiisoft/yii2/blob/master/framework/mail/BaseMailer.php#L299
in layout strict passed only $message and $content with template render result

### My own solution
I extend Mailer class and override render method with  params passed to template

```php

public function render($view, $params = [], $layout = false)
    {
        $output = $this->getView()->render($view, $params, $this);
        if ($layout !== false) {
            return $this->getView()->render(
                $layout,
                ['content' => $output, 'params' => $params, 'message' => $this->_message],
                $this
            );
        } else {
            return $output;
        }
    }

```

But in this method used private $_message property, So I was forced to override also  metod compose
My solution work, but it not look pretty for me. And also i don`t want repeate same code in each mail template
 
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | does not matter
| Operating system | does not matter

**Comment by klimov-paul** [comment]
This is the same behavior, which any alyout rendering applies including `Controller::render()`.
'Layout' term refers to some universal parameters-less entety. If you wish to compose any part of the result output based on particular view params you should do it inside main view, not inside layout.
If you wish to reduce code duplication, you can put 'user unsubscription link and user personal manager contact' inot a separated view file and render it inside your main views.
