### ISSUE TITLE
ActiveRecord::EVENT_BEFORE_FIND?

### ISSUE THREAD

**Issue by menapro** [yiisoft/yii2#14635]
I have seen #4652, and as the last comment says, i create a new topic. 
I miss an event just before the query is going to be executed, so we can modify.
The event `ActiveRecord::EVENT_BEFORE_FIND` could be worth in cases like this:

Example context: Shop
Item: address. 

A user can have multiple addresses, that can be retrieved by `findOne`,`findAll`,`find()`,`hasOne`,`hasMany`.

Due to access restrictions we want to filter all posible results to only those where customer is the owner.
So if we could have a behavior that adds condition `where(['user_id' => Yii::$app->user->id])` will get just the right results.

**Comment by samdark** [comment]
Shouldn't it be related to Query instead of ActiveRecord?

**Comment by klimov-paul** [comment]
Duplicates #4652

**Comment by cncap** [comment]
This is a typical application scenario in the tenant program. When I need to add ['tenant'=>'tanant_Id'] to every SELECT statement, I also encounter this problem, hoping to get attention.thanks
