### ISSUE TITLE
Simple text / plain text model errorSummary

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14648]
Is there a simple way to log a string for model->errors like  
`yii\helpers\Html::errorSummary($models)`  
without html tags?

i.e.:
```php
$errorsMessages = [];
foreach ($model->getErrors() ?? [] as $attribute => $errors) {
    $errorsMessages[] =  $model->getAttributeLabel($attribute) . ': ' . implode(', ', $errors);
}
$errorsMessage = implode('; ', $errorsMessages);
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | 7.1.8
| Operating system | alpine

**Comment by githubjeka** [comment]
```php
Yii::error(json_encode($model->errors));
```
:(

Need something more beautiful...

**Comment by bscheshirwork** [comment]
any else?

**Comment by githubjeka** [comment]
https://github.com/yiisoft/yii2/issues/7988
https://github.com/yiisoft/yii2/issues/3087
https://github.com/yiisoft/yii2/pull/12195

**Comment by bscheshirwork** [comment]
see f3776def0f022355a25a03244aa022a3a7cb9efd

I think we need customization of line separator or something like template in table widgets
