### ISSUE TITLE
Yii::$app->db->createCommand->cache() not work when i user ->query() 

### ISSUE THREAD

**Issue by champriven** [yiisoft/yii2#14647]
### What steps will reproduce the problem?
when i use:
Yii::$app->db->createCommand(sql)->cache() not work when i user ->query()->read() or ->query()->readAll()
nothing cache in redis

But when i use ->queryOne() or ->queryAll() ,data cache success
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version    | php7.1.8 
| Operating system | windows2008R2 server

**Comment by champriven** [comment]
my php code:

$res = Yii::$app->db->createCommand('SELECT rid from order where id=:id')
            ->cache(60)
            ->bindValues([
                ':id'=>$id
            ])->queryOne();

expected result : i want to cache this result 1 min in redis,i can see result in redis

1，Use queryOne() or queryAll()  will cache successful
2，But use query()->read() or query->readAll() will not work , i can't find result in redis

The above two kinds can be successfully run

you can have a try;

**Comment by Alex-Code** [comment]
[->query()](http://www.yiiframework.com/doc-2.0/yii-db-command.html#query()-detail) returns a [DataReader](http://www.yiiframework.com/doc-2.0/yii-db-datareader.html) which looks like it wraps [PDOStatement](http://php.net/manual/en/class.pdostatement.php).

I don't think this is cachable.

[Command.php#L1006](https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L1006)
[Command.php#L1034](https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L1034)

**Comment by champriven** [comment]
@Alex-Code 
but i use ->read() 

Are ->queryOne() different from ->query()->read() ?

**Comment by Alex-Code** [comment]
Yes, `->queryOne()` returns a result directly while `->query()` returns a `DataReader` object which has the `->read()` and `->readAll()` methods.

Any reason you are using `->query()`?

**Comment by cebe** [comment]
> 2，But use query()->read() or query->readAll() will not work , i can't find result in redis

this is expected, DataReader directly interacts with the DB connection so it can not be cached.
