### ISSUE TITLE
when configure multiple masters with multiple slaves, the connections object db was null

### ISSUE THREAD

**Issue by enze** [yiisoft/yii2#14641]
version Yii 2.0.12
version php5.6.30

Scene: multiple masters with multiple slaves,  split db and split table

When a database is switched in the list, a connection is lost. That is, $this->_masters is null and configured as one master with multiple slaves. There is no problem.

main.php

```php
'section' => [
			'class' => 'yii\db\Connection',
			'tablePrefix' => 'tbl_',
			'masterConfig' => [
				'username' => 'username',
				'password' => 'password',
				'attributes' => [
					PDO::ATTR_TIMEOUT => 10,
				],
			],
			'masters' => [
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
			],
			'slaveConfig' => [
				'username' => 'username',
				'password' => 'password',
				'attributes' => [
					PDO::ATTR_TIMEOUT => 10,
				],
			],
			'slaves' => [
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
			],
			
		],
```
model ar

```php
	public static function getDb() {
		$db = md5(self::$sn . self::$dataId);
		$dbNo = $db[0];

		$db = Yii::$app->get('section');
		
		if (false === empty($db->dsn)) {
			Yii::configure($db, [
				'dsn' => preg_replace('/[%|\w+?];charset=utf8/i', $dbNo, $db->dsn),
			]);
		} else {
			$dsn = [
				'master' => [],
				'slave' => [],
			];
			array_map(function ($master) use (& $dsn, $dbNo) {
				$masterDsn = preg_replace('/[%|\w+?];charset=utf8/i', $dbNo . ';charset=utf8', $master['dsn']);
				array_push($dsn['master'], ['dsn' => $masterDsn]);
			}, $db->masters);

			array_map(function ($slave) use (& $dsn, $dbNo) {
				$slaveDsn = preg_replace('/[%|\w+?];charset=utf8/i', $dbNo . ';charset=utf8', $slave['dsn']);
				array_push($dsn['slave'], ['dsn' => $slaveDsn]);
			}, $db->slaves);
			
			Yii::configure($db, ['masters' => $dsn['master'], 'slaves' => $dsn['slave']]);
		}
		
		$db->close();
        
		return $db;
	}
```

exception：

```
exception 'yii\base\InvalidConfigException' with message 'None of the master DB servers is available.' in yiisoft/yii2/db/Connection.php line 568
```

**Comment by enze** [comment]
@cebe  
thank u , 
so sorry,  i probably didn't describe the problem clearly.

my database name like db_section_0, db_section_1, ..., db_section_f.  mysql dsn was defined  in main.php like:
`mysql:host=host;dbname=db_section_%;charset=utf8;`

i want split database with md5 some id, example: md5(20) will output 98f13708210194c475687be6106a3b84
so the database name must be db_section_9. so i should be custom db configuration method like that.

when the yii2 framework was 2.0.5, all of code was normal, but at 2.0.12 the db connection have some problem.  

forgive me, i don't know if you understand what i said.

here is a Chinese description:

        我的需求是在数据库为分库分表，Yii2需要配置为多主多从的模式，但是按照原生的写法仅支持对每一个数据库写一个配置，不支持通配模式。
        因此我需要自定义数据库配置方法，即在继承ActiveRecord类生成的model中覆写getDb方法。动态的改变配置的mysql dsn格式。
        在Yii2.0.5的时候所有的都是正常的，但是升级为2.0.12后就会出现此现象。在一个列表中第一条、第二条数据是正常的，第三条开始数据就有问题了.
        检查后发现第一条、第二条时切换数据库 open(), close() 都没问题，第三条数据开始open()的时候，连接就变成null了，跟踪代码发现在 connection.php的第563行 $db = $this->getMaster();第三次执行的时候返回null.
      目前我的解决方法是采用一主多从的模式配置Yii2的数据库配置信息。

**Comment by SilverFire** [comment]
> when the yii2 framework was 2.0.5, all of code was normal, but at 2.0.12 the db connection have some problem.

Could you try [git bisect](https://git-scm.com/docs/git-bisect) to find commit, that changed behavior?

**Comment by vasily1985** [comment]
Seems like a bug with DB connection closing, that already [fixed](https://github.com/yiisoft/yii2/commit/f5e8a893199d1e0280bc7813db376fd1239840e1) in 2.0.13.
