### ISSUE TITLE
enableClientValidation bug?

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#14652]
### What steps will reproduce the problem?
```
\yii\widgets\ActiveForm::widget([
        'enableClientScript' => false,
        'enableClientValidation' => true
    ]);
```
### What is the expected result?
Load client validation script, but not load additional scripts
### What do you get instead?
Do not load client script validation at all.
### Additional info
I use webpack and all yii scripts are disabled in assets. When enableClientScript is true, yii load all scripts and crashing my webpack files that include the same yii scripts.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1
| Operating system | Win 10

**Comment by samdark** [comment]
You need to override bundles in order to solve your case. Disabling client script won't help.

**Comment by RSalo** [comment]
Thanks. I disabled scripts
```
        'assetManager' => [
            'bundles' => [
                'yii\web\YiiAsset' => false,
                'yii\validators\ValidationAsset' => false,
                'yii\web\JqueryAsset' => false,
                'yii\widgets\ActiveFormAsset' => false,
            ],
        ],
```
and make jquery globally in webpack
```
            {
                test: require.resolve('jquery'),
                use: [{
                    loader: 'expose-loader',
                    options: 'jQuery'
                }]
            }
```
It works for me.
