### ISSUE TITLE
It seems that there is a problem with the file validator for extensions  'pfx, p12', 

### ISSUE THREAD

**Issue by rafaelvaloto** [yiisoft/yii2#14657]
It seems that there is a problem with the file validator for extensions => 'pfx, p12', 'mimeTypes' => 'application / x-pkcs12', I have tried to upload with other png, jpeg and Validation has passed, but for the file with the pfx extension, p12, is not passing.

Yii version ~2.0.6

**Comment by samdark** [comment]
Are you sure these are correctly detected by `finfo_file()`?
