### ISSUE TITLE
`./yii serve` does not use `@webroot` alias as docroot

### ISSUE THREAD

**Issue by rob006** [yiisoft/yii2#14656]
`serve` command uses `@app/web` as a docroot: https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/ServeController.php#L37

Is there any practical reason for not using `@webroot` by default? Right now changing webroot name require updating `@webroot` alias and repeating the same for `serve` command.

**Comment by samdark** [comment]
It's not defined in console application.

**Comment by rob006** [comment]
It is defined in my console application. Why not use `@webroot` as default and fallback to `@app/web` if it is not defined?

**Comment by samdark** [comment]
Yes, that's doable.
