### ISSUE TITLE
Class name dynamically in hasOne not working

### ISSUE THREAD

**Issue by faizanktk** [yiisoft/yii2#14668]
public function getResource() {
        return $this->hasOne(User::className(), ['id' => 'resource_id']);
    }
this function working fine but when i use this 

public function getResource() {
    	 $model = ucfirst($this->resource_type);
        return $this->hasOne($model::className(), ['id' => 'resource_id']);
    }

its give me error "Class 'User' not found"

**Comment by cebe** [comment]
you have to use the name including namespace if you specify it dynamically.

**Comment by faizanktk** [comment]
Thanks @cebe
