### ISSUE TITLE
[Enh] add properties `$contentType` and `$encoding` to `web/JsonResponseFormatter`

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#14662]
XmlResponseFormatter has those properties so its easy to change the `Content-Type` header to

`application/hal+xml; charset=UTF-8`

But the same doesn't apply to the `json` counter part `JsonResponseFormatter` which force you to create a new class to change the `Content-Type` header to

`application/hal+json; charset=UTF-8`

as described by HAL https://tools.ietf.org/html/draft-kelly-json-hal-08#section-3

**Comment by samdark** [comment]
Agree about content type. Do not agree about encoding since JSON should be UTF-8.
