### ISSUE TITLE
Setting the same cache entry twice during the same second makes the 2nd set fail.

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#14660]
When setting the exact same cache entry during the same second, the 2nd `set()` returns false, making it seem like the set has failed, but it didn't. 

The `yii\caching\DbCache` his `setValue()` function first tries an UPDATE to update the cache, and if that fails, it tries an INSERT via the `addValue()` function. This seems fine, except that the UPDATE query returns the number of rows changed, and by default MySQL returns 0 changed rows when the UPDATE is identical to the existing value. I'm not sure what other databases do.
This causes `setValue()` to think the UPDATE has failed and tries a `addValue()` call, what throws an DUPLICATE KEY Exception since the data is already there. This is handled with a `return false` causing the calling functions to think the cache set has failed.

A fix is to set the `PDO::MYSQL_ATTR_FOUND_ROWS` attribute to `true`. This causes MySQL to return the number of found rows instead the number of changed rows in a UPDATE call.

I'm not sure if this is the correct behavior, so a better way could be to change `setValue()` to see the difference between an existing identical cache entry, or a non-existing cache entry.

### Workaround
```php
return [
    ...
    'components' => [
        ...
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=*hostname*;dbname=*database*',
            'username' => '*username*',
            'password' => '*password*',
            'attributes' => [
                PDO::MYSQL_ATTR_FOUND_ROWS => true,
            ],
        ],
    ],
];
```

### What steps will reproduce the problem?
```php
if (!Yii::$app->cache->set('key', 'value', 86400))) {
  throw new Exception("O my god, the cache set has failed. (1)");
}

if (!Yii::$app->cache->set('key', 'value', 86400))) {
  throw new Exception("O my god, the cache set has failed. (2)");
}
```
Returns:
O my god, the cache set has failed. (2)

```php
if (!Yii::$app->cache->set('key', 'value', 86400))) {
  throw new Exception("O my god, the cache set has failed. (1)");
}

sleep(1); // sleep a second, the expiry value will change

if (!Yii::$app->cache->set('key', 'value', 86400))) {
  throw new Exception("O my god, the cache set has failed. (2)");
}
```
Returns nothing.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0
| Operating system | Ubuntu 16.04

**Comment by michaelarnauts** [comment]
The only way I can think of now is do to a COUNT() query so you know if you need to UPDATE or INSERT. Is that a good approach to fix this bug?

**Comment by samdark** [comment]
Is it reproducible in a unit test (it should be)?

**Comment by samdark** [comment]
Issuing `count()` doesn't sound right to me. It hurts both performance (cache is all about it, right) and atomicity.

**Comment by michaelarnauts** [comment]
I haven't looked at the unit tests.

The only way to fix it without impacting performance (so no COUNT(*) query) seems to be to set `PDO::MYSQL_ATTR_FOUND_ROWS => true` by default then, but all databases use the same `yii\db\Connection` class, so that doesn't seem like it is the right place. Also, it might not be the behaviour what is expected. It seems okay to expect that update() returns the number of changed rows, it just seems wrong to expect that the number of changed rows means the update query was succesful.

**Comment by michaelarnauts** [comment]
@samdark I've tried running the tests locally, and it seems they are already failing.

```sh
$ phpunit -v tests/framework/caching/DbCacheTest.php
Applying compatibility patch for PHPUnit 6...
PHPUnit 4.8.34 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.14
Configuration:	/project/phpunit.xml.dist

..F...............

Time: 9.68 seconds, Memory: 6.00MB

There was 1 failure:

1) yiiunit\framework\caching\DbCacheTest::testSet
Failed asserting that false is true.

/project/tests/framework/caching/CacheTestCase.php:89
/project/vendor/phpunit/phpunit/phpunit:52

FAILURES!
Tests: 18, Assertions: 52, Failures: 1.
```

The CacheTestCase on line 89, in `testSet()`, does this:
```php
        $this->assertTrue($cache->set('string_test', 'string_test'));
```
I guess this fails because on line 77, in  the `prepare()`, it does this:
```php
        $cache->set('string_test', 'string_test');
```

I assume if this happens in the same second, the test on line 89 fails.

Are you sure that travis is running also database tests?

**Comment by samdark** [comment]
It does. These aren't excluded.

**Comment by michaelarnauts** [comment]
This test makes sure that the records are added on the same second (since the test already allows mocking the time):

This will fail:
```php
    public function testUpdateIdenticalRecord()
    {
        $cache = $this->getCacheInstance();

        static::$time = \time();
        $this->assertTrue($cache->set('update_record', 'update_record', 60));
        $this->assertTrue($cache->set('update_record', 'update_record', 60));
    }
```
When doing a `static::$time = \time()+1;` after the first assertTrue, it works fine.
