### ISSUE TITLE
Bad Request error on valid JSON request

### ISSUE THREAD

**Issue by sleepndevelop** [yiisoft/yii2#14676]
### What steps will reproduce the problem?
I have set the JSON parser in my web.php config file :
`$config = [`
`    'id' => 'basic',`
`    'basePath' => dirname(__DIR__),`
`    'bootstrap' => [ 'log' ],`
`    'components' => [`
`        'request' => [`
`            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation`
`            'cookieValidationKey' => 'xxxx',`
`            'parsers' => [`
`                'application/json' => 'yii\web\JsonParser',`
 `           ],`
`        ],`
`....`
`];`
But when i send a JSON-RPC request, i get  
`Bad Request (#400)` 

Then i have put some code to dump the request from the beginning of index.php:
`$URI = print_r($_SERVER['REQUEST_URI'],true);`
`$get = print_r($_GET,true);`
`$post = print_r($_POST,true);`
`$hdr = print_r(getallheaders(),true);`
`$body = @file_get_contents('php://input');`
`die("_GET:$get<br> Headers:$hdr<br> POST:$post<br> Uri:$URI<br> Raw Data:$body");`

It prints:

'_GET:Array`
`(`
`    [apiKey] => apikeytest`
`)`

`Headers:Array`
`(`
`    [Host] => localhost`
`    [Accept] => */*`
`    [Connection] => close`
 `   [Accept-encoding] => gzip, deflate`
`    [Content-type] => application/json`
`   [User-agent] => EHttpClient`
 `   [Content-Length] => 57`
`)`

`POST:Array`
`(`
`)`

`Uri:/new-receive-address/list?apiKey=apikeytest`

Raw Data:{"jsonrpc":"1.0","id":"123","method":"dummy","params":[]}

The raw data seems valid JSON according to an online validator site.
What am i missing?

### What do you get instead?
`Bad Request (#400)` error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.7 
| Operating system | Windows 10 Home XAMPP 3.2.2

**Comment by yyxx9988** [comment]
I guess you should try to disable `csrfValidation` like this:
```php
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        if (parent::beforeAction($action)) {
            return true;
        }
        return false;
    }
```

> Whether to enable CSRF (Cross-Site Request Forgery) validation. Defaults to true. When CSRF validation is enabled, forms submitted to an Yii Web application must be originated from the same application. If not, a 400 HTTP exception will be raised.

http://www.yiiframework.com/doc-2.0/yii-web-request.html#$enableCsrfValidation-detail

**Comment by sleepndevelop** [comment]
Thanks.
I added this in web config:
    'on beforeAction' => function ($event) {
    if(Yii::$app->request->contentType == "application/json") Yii::$app->controller->enableCsrfValidation = false;
    },
...

Now it works!
