### ISSUE TITLE
Grid renderItems

### ISSUE THREAD

**Issue by SkyTaurus** [yiisoft/yii2#14677]
Invalid position of tags when generating a table. The table is displayed correctly, but if you export to excel then the footter is displayed up to the elements.     
File `https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L342`
wrong code
`$content = array_filter([
            $caption,
            $columnGroup,
            $tableHeader,
            $tableFooter,
            $tableBody,
        ]);`

fixed
`$content = array_filter([
            $caption,
            $columnGroup,
            $tableHeader,
            $tableBody,
            $tableFooter,
        ]);`

**Comment by klimov-paul** [comment]
`GridView` does not provide any expoert to Excel.
If this expoert went wrong, you should check the code, which performs it.

**Comment by SkyTaurus** [comment]
Yes, but other extensions take the html code that is used to generate the tables and convert it to a xls file. Due to the fact that the tags are not in the right sequence, the file is displayed incorrectly.
Code genetated for xls file
`<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:x='urn:schemas-microsoft-com:office:excel' xmlns='http://www.w3.org/TR/REC-html40'>`

Next, the table code generated by the YiI2. 
table 
table thead  tfoot tbody
And in the end it is displayed incorrectly.

**Comment by rob006** [comment]
https://www.w3.org/TR/REC-html40/struct/tables.html#h-11.2.3

> TFOOT must appear before TBODY within a TABLE definition so that user agents can render the foot before receiving all of the (potentially numerous) rows of data.

HTML 5 is more forgiving in this matter and allows footer after body, but still "thead tfoot tbody" is preferred order for tables in HTML.

**Comment by SkyTaurus** [comment]
just look the file content [http://s000.tinyupload.com/index.php?file_id=58758531469791418918](http://s000.tinyupload.com/index.php?file_id=58758531469791418918)

**Comment by rob006** [comment]
I'm not sure what you want to prove. `GridView` is intended to generate a HTML table and it follows HTML spec. If you have extension that exports HTML table to Excel sheet, then this extension is responsible for conversion this HTML table to Excel-compatible format. Don't expect that `GridView` will generate table for Excel, because it's not his job.
