### ISSUE TITLE
getOldAttribute not null after $model->save()

### ISSUE THREAD

**Issue by sreenadh** [yiisoft/yii2#14680]
### What steps will reproduce the problem?

$model = new Model;
$model->attribute = $value
$model->save();
echo $model->getOldAttribute("attribute_name");

### What is the expected result?
null

### What do you get instead?
$value

https://github.com/yiisoft/yii2/blob/b7079d31df6865161d21590c6e7a24121559d507/framework/db/ActiveRecord.php#L519

Can we remove this code? Is it necessary to set old attributes on inserting new record? Seems it is required only for update.

**Comment by FabrizioCaldarelli** [comment]
Maybe could it be useful if you change some attributes in afterSave event?

**Comment by cebe** [comment]
after save, the model is in the same state as after find (in sync with the db), so old attributes are the same as the current attributes. This is expected behavior.
