### ISSUE TITLE
Trusted host config: alternative matching methods

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#14691]
@SamMousa implemented configuration for trusted hosts in #13780. The matching is currently done by regex, which caused some discussion in https://github.com/yiisoft/yii2/pull/13780#discussion_r106126378 and https://github.com/yiisoft/yii2/pull/13780#discussion_r134188182.

### Current implementation for `Request::$trustedHosts`

```php
[
    '/\.trusted\.com$/', // match a host ending in .trusted.com
    '^192\.168\.0\.\d+$', // match ip in the range `192.168.0.0/24`
]
```

### Alternatives / Problems

- we use fnmatch in other places, e.g.:
  - HostControl: https://github.com/yiisoft/yii2/blob/9e713dba29246babefaa40ef45c4792d2d620158/framework/filters/HostControl.php#L26-L29
  - AccessRule: https://github.com/yiisoft/yii2/blob/9e713dba29246babefaa40ef45c4792d2d620158/framework/filters/AccessRule.php#L99-L101
- the most common use case for whitelisting proxy would probably be via IP address, which is usually done using CIDR notation, this is currently not supported and quite hard to achieve when using regex.
- We should probably not even allow matching host names here as it is easy to fake a reverse lookup to point to a host.

Alternative to the above using fnmatch would look like this:

```php
[
    '*.trusted.com', // match a host ending in .trusted.com
    '192.168.0.*', // match ip in the range `192.168.0.0/24`
]
```

Allowing CIDR would allow this:

```php
[
    '*.trusted.com', // match a host ending in .trusted.com
    '192.168.0.0/24', // match ip in the range `192.168.0.0/24`
]
```

Decision should be made before 2.0.13 as it would probably break BC.

**Comment by samdark** [comment]
I don't think it's BC breaking. The feature wasn't released yet.

**Comment by cebe** [comment]
seems we need to figure out what we mean when applying the label :-D I attached it because the change would be BC breaking if not made before the release ;)

**Comment by rob006** [comment]
https://github.com/symfony/http-foundation/blob/master/IpUtils.php

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/blob/9e713dba29246babefaa40ef45c4792d2d620158/framework/validators/IpValidator.php#L530-L558

**Comment by rob006** [comment]
I'm for using `fnmatch()` here for consistency. The best option would be use own helper which accepts both `fnmatch()` and CIDR patterns, but it could be added after 2.0.13 release.

> We should probably not even allow matching host names here as it is easy to fake a reverse lookup to point to a host.

That is good point, we should allow only IPs here.

**Comment by SilverFire** [comment]
> We should probably not even allow matching host names here as it is easy to fake a reverse lookup to point to a host.

Very good point. Voting strictly for it.

I'm for CIDR notation and using IpValidator.

**Comment by SilverFire** [comment]
Actually, there is a totally safe case with host names: application works behind a proxy server and all requests to the application are received ONLY from the local network. However, it's a bit advanced topic and I would not like to recommend to rely on it.

**Comment by SamMousa** [comment]
Btw, don't SMTP servers often use something like reverse DNS + DNS to validate hostnames?
So I can spoof the reverse DNS, but not the normal one:
````
1.2.3.4 --reverse-dns--> very.secure.server
very.secure.server --forward-dns--> 192.168.0.1
````
In scenario's where my Yii2 application runs inside some containerized environment, chances are:
1. I do not know the IP of the web server.
2. Trusting a the whole private network is not restrictive enough
3. I can trust the forward-dns.

In that case host name matching would be very valuable; it woudl just require an extra forward lookup..

**Comment by cebe** [comment]
> Btw, don't SMTP servers often use something like reverse DNS + DNS to validate hostnames?

SMTP servers use reverse lookups to check whether the reverse matches back to the original IP or whether someone wants to fake here. They are not taking the reverse lookup only but verify the IP it points to. Basically what you linked.

Adding the overhead of that kind of validation is kind of overkill here.

> Trusting the whole private network is not restrictive enough

in which case would you not trust your own network?
