### ISSUE TITLE
Default scope missing

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#1469]
Yii1 has a function called defaultScope().
It seems that it's dropped in Yii2?
What is your suggestion to substitute this function?

Is there an other way (next to defaultScope) to define a default sort sequence for ActiveRecord's?

**Comment by paulhudson** [comment]
Seems createQuery() has now been removed.

You can now use: 

```php
 class Post extends ActiveRecord
{
    public static function find()
    {
        return parent::find()->andWhere(['published' => 1]);
    }
}
```

**Comment by karmraj** [comment]
@cebe :  I have use following code to set or apply default condition to all find() function. But in some cases i do not want to apply this condition then how can i unset this onCondtion condition in find() function. 

    public static function find()
    { 
        //return new PaymentQuery(get_called_class());
		return parent::find()->onCondition('fp_status = 0');
    }

Thanks in Advance.

**Comment by samdark** [comment]
You can't. It's a bad practice to make exceptions in this case. Either use it all the time or apply it explicitly. Else it would be hell to work with.

**Comment by faravaghi** [comment]
hi @samdark: How to use the 2 methods following a model: **default condition for all queries** and **use CustomerQuery instead of the default ActiveQuery**.
for example:
```php
public static function find()
{
	return parent::find()->where(['deleted' => false]);
	// return new CustomerQuery(get_called_class());
}
