### ISSUE TITLE
Problem with unique rule on concurrent transaction

### ISSUE THREAD

**Issue by luqmansungkar** [yiisoft/yii2#14693]
### What steps will reproduce the problem?

* Create 2 concurrent action that try to insert a record with the same value. I use 2 instance of yii2 queue worker.
* Push 2 queue job that try to insert a record with the same value.
* The 2 worker will receive the job at nearly the same time, and insert the record concurrently

### What is the expected result?

* The first job get executed and inserted the row successfully
* The latter job failed the validation rule and return false on `validate()` or `save()`

### What do you get instead?

* The first job get executed and inserted the row successfully
* The latter job pass the validation rule, but get `Integrity constraint violation: 1062 Duplicate entry` error

### Additional info

What I think is happening:

job 1 | job 2
------------|-----------
unique rule check if record already exist | unique rule check if record already exist
record is not exist yet | record is not exist yet
try to insert new row | try to insert new row
row inserted successfully | row already exist, integrity constraint violation

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.7-1 & 7.1.8-2
| Operating system | Ubuntu 16.04.2 LTS & Linux Mint 18.2

**Comment by samdark** [comment]
How would you solve the issue?

**Comment by francislavoie** [comment]
Sounds like Upsert support might fix this? https://github.com/yiisoft/yii2/issues/13879

**Comment by samdark** [comment]
Same as using try-catch and `save()`. That won't work with validation though since validation itself happens *before* actual saving and thus leaves a time span for concurrency issue to take place...

**Comment by francislavoie** [comment]
The other option would be setting up a mutex in jobs that do similar work: http://www.yiiframework.com/doc-2.0/yii-mutex-mutex.html

**Comment by samdark** [comment]
Either mutex or versioning/content merges sounds right in this case. That depends heavily on application design though and is out of scope of the framework.

**Comment by cebe** [comment]
You need to use database transactions with the appropriate isolation level to avoid this.
