### ISSUE TITLE
The db connection can not close and reopen

### ISSUE THREAD

**Issue by zengkun100** [yiisoft/yii2#14709]
### What steps will reproduce the problem?
After the db connection established,  if you close the connection manually, and open this db connection again. You'll not get a correct db connection.

I found that the close function of Connection class set _master to null,

```
    public function close()
    {
        if ($this->_master) {
            if ($this->pdo === $this->_master->pdo) {
                $this->pdo = null;
            }

            $this->_master->close();
            $this->_master = null;
        }
```

 but getMaster function use  === false

```
    public function getMaster()
    {
        if ($this->_master === false) {
            $this->_master = ($this->shuffleMasters)
                ? $this->openFromPool($this->masters, $this->masterConfig)
                : $this->openFromPoolSequentially($this->masters, $this->masterConfig);
        }

        return $this->_master;
    }
```

to check if it should make a db connection. So, If you close the connection, and reopen it, getMaster will return an null which makes getMaster only work for the first time it is called.

### What is the expected result?

Just set $this->_master = false in the close function, like what do in clone.  And this makes getMaster work correctly

 ``` 
    public function __clone()
    {
        parent::__clone();

        $this->_master = false;
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.4
| Operating system |Ubuntu 14.04.4 LTS

**Comment by cebe** [comment]
> Yii version 	2.0.12?

please try again with current master, I believe we fixed something like this recently, it will be released in 2.0.13.

**Comment by samdark** [comment]
Yes. It's fixed in master: https://github.com/yiisoft/yii2/issues/14165

**Comment by zengkun100** [comment]
@cebe

I have tried master version. It just works. Thank U
