### ISSUE TITLE
Wrong plural message in Russian translation

### ISSUE THREAD

**Issue by egorsmkv** [yiisoft/yii2#14700]
### What steps will reproduce the problem?

Model rules:

```php
public function rules()
    {
        return [
            [['title', 'category_id', 'message'], 'required'],
            [['title', 'category_id', 'message'], 'string'],
            [['title'], 'string', 'min' => 5], // <--- HERE
        ];
    }

public function attributeLabels()
    {
        return [
            'title' => 'Заголовок',
            'message' => 'Сообщение',
            'category_id' => 'Категория',
        ];
    }
```

### What is the expected result?

Must be message:

```
Значение «Заголовок» должно содержать минимум 5 символов.
```

### What do you get instead?

```
Значение «Заголовок» должно содержать минимум 5 символа.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.8
| Operating system | Kubuntu 17.04

**Comment by samdark** [comment]
1. Do you have `intl` PHP extension installed/enabled?
2. Which version of ICU data do you have?

**Comment by egorsmkv** [comment]
No, I don't. I installed `intl` extension and message shows okay.

Thanks, @samdark
