### ISSUE TITLE
Too Many Redirect with checked remember me User Login only

### ISSUE THREAD

**Issue by myomyintaung512** [yiisoft/yii2#14706]
### What steps will reproduce the problem?
I try to login with remember me checkbox checked and server show error page ERR_TOO_MANY_REDIRECTS

### What is the expected result?
ERR_TOO_MANY_REDIRECTS

### What do you get instead?
Login Successful

### Additional info
Server Error Log
__________________
[Wed Aug 23 12:52:07.086676 2017] [core:crit] [pid 17385] (13)Permission denied: [client 103.42.216.66:9749] AH00529: /home/user/public_html/yiiproject/web/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/user/public_html/yiiproject/web/' is executable

This is happen on some server only.
Is there any related server settings to change to solved this error ?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      |  5.6
| Operating system | Centos 7

**Comment by bscheshirwork** [comment]
May be anything changed in chmod on '/home/user/public_html/yiiproject/web/' ?

**Comment by myomyintaung512** [comment]
Is happening because of mod_security rule 
981243: Detects classic SQL injection probings 2/2
Disable that Rule and working fine now.

Error Logs.

Request:  GET /
Action Description:  Access denied with redirection to http://domain.com/ using status 302 (phase 2).
Justification:  Pattern match "(?i:(?:[\"']\\s*?\\*.+(?:x?or|div|like|between|and|id)\\W*?[\"']\\d)|(?:\\^[\"'])|(?:^[\\w\\s\"'-]+(?<=and\\s)(?<=or|xor|div|like|between|and\\s)(?<=xor\\s)(?<=nand\\s)(?<=not\\s)(?<=\\|\\|)(?<=\\&\\&)\\w+\\()|(?:[\"'`][\\s\\d]*?[^\\w\\s]+\\W*?\\d\ ..." at REQUEST_COOKIES:_identity.


Thanks
