### ISSUE TITLE
Documentation error in  yii\i18n\Formatter

### ISSUE THREAD

**Issue by therendstudio** [yiisoft/yii2#14707]
In the description **asDatetime()** function about the **$format** parameter it says that the default value is taken from **$dateFormat** while the correct is **$datetimeFormat**

[http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#asDatetime()-detail](url)

Yii Version: **2.0**

**Comment by cebe** [comment]
fixed, thanks for reporting!
