### ISSUE TITLE
GridView column search doesn't return any result if the current viewing page is greater than the pages returned by search

### ISSUE THREAD

**Issue by cyberinferno** [yiisoft/yii2#14712]
### What steps will reproduce the problem?

* Open GridView with at least 2 pages and has column wise search
* Go to the 2nd page in that GridView
* Use some search term that will yield a single result

### What is the expected result?

* GridView should show all the rows matching the search term

### What do you get instead?

* GridView does not show any result though there are results matching the search term

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.17
| Operating system | Ubuntu

**Comment by Alex-Code** [comment]
Are you using your own `Pagination` class?
The one included with Yii2 does compensate for pages greater than the amount of available data.

**Comment by cyberinferno** [comment]
@Alex-Code I think I know what was the issue. I had set _validatePage_ to false hence the issue arose.
