### ISSUE TITLE
Missing message in Bulgarian translation

### ISSUE THREAD

**Issue by therendstudio** [yiisoft/yii2#14735]
### What steps will reproduce the problem?
Use the compare validator for equality
### What is the expected result?
"{attribute}" трябва да е равно на "{compareValueOrAttribute}".
### What do you get instead?
{attribute} must be equal to "{compareValueOrAttribute}".

### Additional info
  '{attribute} must be equal to "{compareValueOrAttribute}".' => '"{attribute}" трябва да е равно на "{compareValueOrAttribute}".',

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Noone from core team knows Bulgarian good enough. Feel free to pull request changes and we'll merge em.
