### ISSUE TITLE
Codeception amOnRoute broken the session in Phpstorm

### ISSUE THREAD

**Issue by yujin1st** [yiisoft/yii2#14737]
### What steps will reproduce the problem?
1. Write simple functional test that logs user in and moves by pages

```
    $I->amOnRoute('/');
    $I->assertTrue(Yii::$app->user->isGuest);
    $I->amLoggedInAs(User::findUserByUsername('admin'));
    $I->assertFalse(Yii::$app->user->isGuest);
    $I->amOnRoute('/');
    $I->assertFalse(Yii::$app->user->isGuest);
```
2. Run test

### What is the expected result?
 All should be fine
### What do you get instead?
Test runs in console and fails in Phpstorm (first test in screenshot )
If you comment first line that opens the page before all tests complete without error (second test in screenshot)

![2017-08-30 12 12 12](https://user-images.githubusercontent.com/2317913/29853725-7ccb89a4-8d7c-11e7-8b1a-bd5409ad16bc.png)

### Additional info
At first i thought it ide issue, but after i discovered it appeared only if "amOnRoute" is on first string, i become concerned about yii. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1
| PhpStorm | Last EAP and stable versions
| Operating system | Mac 10.12.5

**Comment by samdark** [comment]
Looks like Codeception issue. Please report to https://github.com/Codeception/Codeception
