### ISSUE TITLE
\yii\db\Query::where(): Unable to compare two subqueries with operator format

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#14732]
### What steps will reproduce the problem?

```php
$query->where(['>', $subquery1, $subquery2]);
```

### What is the expected result?

A condition consisting of two subqueries with the operator between them, such as:

`WHERE (SELECT COUNT(*) FROM table1 ...) > (SELECT COUNT(*) FROM table2 ...)`

### What do you get instead?

>strpos() expects parameter 1 to be string, object given

In QueryBuilder line 1460

**Comment by 243083df** [comment]
$query->where(['>', new Expression($subquery1->createCommand()->rawSql), new Expression($subquery2->createCommand()->rawSql)]);

?

**Comment by vercotux** [comment]
Works like this too: 

```php
$query->where(['>',
    $subquery1->createCommand()->rawSql,
    $subquery2->createCommand()->rawSql,
]);
```

Thanks

@samdark Is there any reason why operand format shouldn't accept two `Query`s like in my original post?

**Comment by samdark** [comment]
No.
