### ISSUE TITLE
restful  404

### ISSUE THREAD

**Issue by Aibric** [yiisoft/yii2#14739]
### What steps will reproduce the problem?
```
'urlManager' => [
     'enablePrettyUrl' => true,
      'enableStrictParsing' => true,
      'showScriptName' => false,
       'rules' => [
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/user', 'v1/cate', 'v1/category', 'v1/aibric']],
        ],
]
```
### What is the expected result?

http://w.x.cc/v1/categorys 
Data can be returned correctly

### What do you get instead?
http://w.x.cc/v1/categorys 
throw exception 404

### Additional info
http://w.x.cc/v1/users   success
http://w.x.cc/v1/cates   success
http://w.x.cc/v1/categorys  error 404
http://w.x.cc/v1/aibrics  success

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  7
| Operating system | win 10

**Comment by tunecino** [comment]
The plural of `category` is `categories`. Your url should be `http://w.x.cc/v1/categories`.

If automatic pluralization does not meet your requirement you can specify what name in url  to map to controller ID as mentioned in [docs](http://www.yiiframework.com/doc-2.0/guide-rest-routing.html):
```php
'controller' => [
    'v1/user',
    'v1/cate',
    'v1/whatever' => 'v1/category',
    'v1/aibric'
]
```
**Please use forum or chat in future to ask questions. Github is for bug reports and features discuss**

**Comment by Aibric** [comment]
Thank you @tunecino
