### ISSUE TITLE
Eager loading generates multiple select statements 

### ISSUE THREAD

**Issue by nkostadinov** [yiisoft/yii2#14743]
### What steps will reproduce the problem?
I have a model MediaArticle with a relation mediaKeywordArticles. 
```
        $article = MediaArticle::find()
            ->joinWith('mediaKeywordArticles', true)
            ->andWhere('media_article.id=:id', [':id' => 12957537442])
            ->one();
        return $this->asJson($article->mediaKeywordArticles);
```

### What is the expected result?
When I look at the debug panel to see one query with join statement.

### What do you get instead?
I see 2 queries.
1. seems ok and has a join statement by selects only from primary table
```
SELECT `media_article`.* 
FROM `media_article` 
LEFT JOIN `media_keyword_article` ON `media_article`.`id` = `media_keyword_article`.`article_id` 
LEFT JOIN `media_keyword` ON `media_keyword_article`.`keyword_id` = `media_keyword`.`id` 
WHERE media_article.id=12957537442`
```

2.  The relation data is fetched with a new query - why ?
```
SELECT * FROM `media_keyword_article` WHERE `article_id`='12957537442'
```

### Additional info
According to the documentation there should be only one query when eager loading data.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12(dev-master)
| PHP version      | 7.0.0
| Operating system  | Windows 10

**Comment by cebe** [comment]
> According to the documentation there should be only one query when eager loading data.

not sure which documentation you are referring to, but this documentation explains why this is the case:

http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#lazy-eager-loading

Note the difference between joinWith() and with(). As far as I see you do not need the join.

**Comment by nkostadinov** [comment]
I refer to this part of the documentation : 

> If the $eagerLoading parameter is true, the method will also perform eager loading for the specified relations, which is equivalent to calling with() using the specified relations.

I also tried with `with('keywords')` with the same result generation multiple queries instead of one join.

**Comment by cebe** [comment]
this is expected behavior, eager loading is useful in combination with all(), for one() it makes no difference.

**Comment by klimov-paul** [comment]
You may use [yii2tech/ar-eagerjoin](https://github.com/yii2tech/ar-eagerjoin) in case you wish to use single query in join case.

**Comment by nkostadinov** [comment]
10x for the suggestion. Using all() also makes two queries. I've lost a couple of hours debugging the issue. The two queries are not the actual problem. I want to get all articles and their keywords for specific user so I do the following: 
```
$articles = MediaArticle::find()
            ->join('mediaKeywordArticles')
            ->andWhere('mediaKeywordArticles.created_by = :user_id', [':user_id' => 1])
            ->andWhere('media_article.id=:id', [':id' => 12957537442])
            ->all(); //or one() it's the same
return $this->asJson($articles) //this is an ActiveProvider but this is shorter
```
What I expect is to see is each article and their corresponding keywords in the `mediaKeywordArticles` array. Instead I get the article and ALL the keywords even for other users. This is really confusing, Is it possible with the current functionality to get only the filtered relation ?

**Comment by cebe** [comment]
```php
$article = MediaArticle::find()
            ->with(['mediaKeywordArticles' => function($query) {
                $query->andWhere('created_by = :user_id', [':user_id' => 1])
            }])
            ->andWhere('media_article.id=:id', [':id' => 12957537442])
            ->one();
```

**Comment by nkostadinov** [comment]
Well it just do what I want to. Here is the full picture :
Tables:
- article ( id, content)
- keyword(id, name)
- article_keyword (article_id, keyword_id, date, user_id) - has index on (user_id, date) !important to user this index

We are talking about very large amounts of data like 10s of millions so it is very important to use the index. I simply want to return all articles with their keywords for a user sorted by date. the relation is done via the junction table 'article_keyword '. So if I use the above solution the index is not used and the performance is degraded. If I use my solution then wrong data is returned: 
```
       $query = MediaArticle::find()
            ->joinWith('keywords', true, 'INNER JOIN')
            ->andWhere('media_keyword_article.user_id=:user_id', [':user_id' => $user_id ])
            ->orderBy(['media_keyword_article.article_date' => SORT_DESC]);
```
