### ISSUE TITLE
xSendFile() in yii2 is downloading file and returning 0 bytes Please Help!!

### ISSUE THREAD

**Issue by mjombanorman** [yiisoft/yii2#14747]
Below is the sample code that I have used in the controller and view

> Controller

` public function actionDownload($id) {

        $download = Status::findOne($id);

        $path = Yii::getAlias('@webroot') . '/uploads/status/' . $download->image_web_filename;

        if (file_exists($path)) {
                   return (Yii::$app->response->xsendFile($path));
            exit;
        } else {
            throw new NotFoundHttpException("can't find {$download->image_web_filename} file");
        }
    }`

> view

`['attribute'=>'Download',
       'format'=>'raw',
        'value' => function($data)
        {
        return
        Html::a('Download file', ['status/download','id'=>$data->id],['class' => 'btn btn-primary']);

        }
        ],`

**Comment by qulmatov** [comment]
xsendFile()
