### ISSUE TITLE
Touch `updatedAtAttribute` when use `link` method

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#14746]
### What steps will reproduce the problem?
It's necessary to touch the `updatedAtAttribute` when using `$model->link`. For example:

```php
class Order extends ActiveRecord {

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    } 

    public function getItems()
    {
        return $this->hasMany(OrderItem::className(), ['order_id' => 'id']);
    } 
}

class OrderItem extends ActiveRecord
{ ...

$model = Order->findOne(1);

$item = new OrderItem([...]) ;
$item->save();

$model->link('items', $item);// this need to change the `updated_at` from `$model`
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0

**Comment by cebe** [comment]
There may be cases where this is not desired, i.e. changing a relation may not necessarily be considered an update of a record. You can make this explicit like:

```php
$model->link('items', $item);
$model->touch('updated_at'); // this changes the `updated_at` from `$model`
```

**Comment by samdark** [comment]
I agree. Since there are cases when it's not desired behavior, I think we should not make it a default.

**Comment by leandrogehlen** [comment]
Maybe, its ncessarynto create a event for it. in my case i have the web site and a rest api then i have to replicate it in rest and web

**Comment by samdark** [comment]
You can override link method in your models:

```php
public function link($name, $model, $extraColumns = [])
{
    parent::link($name, $model, $extraColumns);
    $model->touch('updated_at');
}
```
