### ISSUE TITLE
yii2  sendFile() is giving some unrefined code instead of immediately downloading

### ISSUE THREAD

**Issue by mjombanorman** [yiisoft/yii2#14748]
Below are codes for controller and view respectively

> **## Controller**
` public function actionDownload($id) {

        $download = Status::findOne($id);

        $path = Yii::getAlias('@webroot') . '/uploads/status/' . $download->image_web_filename;

        if (file_exists($path)) {
            

            return (Yii::$app->response->SendFile($path, $download->image_web_filename)->send());
            exit;
        } else {
            throw new NotFoundHttpException("can't find {$download->image_web_filename} file");
        }
    }`
> **## View**
`%PDF-1.4 %�쏢 5 0 obj <> stream x��]K�%ECű%P4���y��.�u�@�Q �zt��P�0��_��'��gx����/3�n���zܞ���xaAR7o�s�<�;�����܈�o��w?8��]�y�/'�O�FU��@b㍤���G����͇'r����4�+B��{3���SW����'��<�������A�ǃ*x���N27r�$���V������w�_?��k�~���+�'wFr6��f! ��ȍ7�Ӡ���UG���g;=�2�j��Ǒ �oƱQƇfh�?�WҘ�0۟��/�l�E���i(�{��* ��'�W��8��T�j 2��p������\��aܵH�$�Ci��u��$j��QZ���aIk����\o���D2Y)�/FV��nġ�a����� �_ؐ��rf�� �7�*� �IN�J{�l����Cqr�D�������[�]9���E�7�����k�j���9N�\�EC��F����&ռ-����uJV����3����L!�f��x���F�����̈́��#��U����:*g��&C�ӤD��q�17�@Jg+�J����w��ߨ?M_�a���R�ݼ��zu%��\�#�7$M&���-dO"#�]�i�89�}��<��� m��04�I�bHJ �O�M��`f�Ϯ�E�{2}`���n�����.l���+cZ?�����6C��N��XZJW�ylȒ��"�D�ͧ�8s���q��o׉m��ݍx�6(��T�9Uɨ�g���x���\���'�Ͻ����BE��|���

**Comment by abigabaw** [comment]
I had the exact problem, It turned out that my link to download action was placed inside the Pjax::begin() Pjax::end() methods, so the content of the file was treated as update for the page.

My solution: add data-pjax="0" attribute to download link in your view file.

**Comment by huihuangjiuai** [comment]
verry

> I had the exact problem, It turned out that my link to download action was placed inside the Pjax::begin() Pjax::end() methods, so the content of the file was treated as update for the page.
> 
> My solution: add data-pjax="0" attribute to download link in your view file.

Great. Solved my problem!
