### ISSUE TITLE
FileCache "delete" not working

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#14744]
```php
/**
 * 'cache' => [
 *      'class' =>'\yii\caching\FileCache',
 * ],
 */

\Yii::$app->cache->set("key_name", "foo_bar");
\Yii::$app->cache->delete("key_name");
\Yii::$app->cache->get("key_name"); //return "foo_bar"
```

**Comment by cebe** [comment]
@exru there could be permission issues on the cache files. We have a test that verifies this case: https://github.com/yiisoft/yii2/blob/f866edcfbac110e396d4df7400094c55b387a4e7/tests/framework/caching/CacheTestCase.php#L245-L252
