### ISSUE TITLE
Codeception Yii2 module should use `andWhere`.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#14757]
### What steps will reproduce the problem?
Create an AR query that explicitly disables `where`.
Motivation: my AR query filters deleted records and I do not want parts of my code to intentionally or unintentionally retrieve those records.

### What is the expected result?
When I use `$this->tester->seeRecord(User::class, ['id' => 15]);` I expect it to find (or not find) the record.

### What do you get instead?
Since the connector uses `->where` instead of `->andWhere()` I get an exception.
If I implemented my code differently, the connector would still ignore any conditions I set on the query object and replace them with just the conditions passed to `seeRecord()`.

### Proposed solution
Use `andWhere` instead.

**Comment by samdark** [comment]
Makes sense. Pull request?

**Comment by samdark** [comment]
Closing it here since it belongs to Codeception itself.
