### ISSUE TITLE
hasOne hasMany class is child of ActiveQuery

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14760]
We have 2 different definition of `hasOne` and `hasMany`

in ActiveRecord
https://github.com/yiisoft/yii2/blob/9b01ca275f891c245c2e840ed93c87f715c04e70/framework/db/ActiveRecord.php#L72-L73
and in ActiveQuery here
https://github.com/yiisoft/yii2/blob/9b01ca275f891c245c2e840ed93c87f715c04e70/framework/db/BaseActiveRecord.php#L371-L373
and here
https://github.com/yiisoft/yii2/blob/9b01ca275f891c245c2e840ed93c87f715c04e70/framework/db/BaseActiveRecord.php#L406-L408

`ActiveQuery hasOne($class, array $link)` not equial `ActiveQueryInterface hasOne($class, $link)`

It is correct redefinition (weak->harder)... 

**But we need result type is equal to user-definition children of ActiveQuery.**
(Late Static Bindings?)

i.e. 
```php
class SomeClass extends \yii\db\ActiveRecord
{
    /**
     * @return AnotherClassQuery
     */
    public function getAnotherClass()
    {
        return $this->hasOne(AnotherClass::className(), ['id' => 'anotherClassId'])->inverseOf('someClass');
    }
}
```
hasOne return ActiveQuery, but excepted  AnotherClassQuery

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13-dev

**Comment by cebe** [comment]
there is no way to solve this in Yii itself.
