### ISSUE TITLE
AccessControl initializes yii\web\User too early

### ISSUE THREAD

**Issue by cronfy** [yiisoft/yii2#14766]
In my application I have:

 1. `yii2-usuario` as module `user`.
 2. `AccessControl` application's `as beforeRequest` behavior.

```
    'modules' => [
        'user' => [
            'class' => Da\User\Module::class,
        ]
    ],
    'as beforeRequest' => [
        'class' => \yii\filters\AccessControl::class,
        'rules' => [ ... ],
    ],
```

The problem is that with configuration above it does not work: `AccessControl` throws "User::identityClass must be set" exception on it's initialization phase.

From the other side, `yii2-usuario` [overrides](https://github.com/2amigos/yii2-usuario/blob/1.0.13/src/User/Bootstrap.php#L144) `yii\web\User`, configuring it with correct `identityClass` option. So, theoretically, everything should be ok, but in practice `AccessControl` initialization happens prior to `yii2-usuario`, and at that moment `identityClass` is not set yet.

I know that issue could be easily solved by configuring `user` component of the application, but I would like to avoid it and make it all happen automatically without any manual tweaks.

I see too potential issues:

 1. Either `AccessControl` initializes `yii\web\User` too early.
 2. Or a module must not configure container definitions of related components, and`yii2-usuario` does the wrong thing.

What do you think? If it's `AccessControl` issue, I think I can file a PR to refactor `$this->user` to a getter/setter in `AccessControl`, avoiding it instantiation in `init()`.

**Comment by cebe** [comment]
> From the other side, yii2-usuario overrides yii\web\User, configuring it with correct identityClass option.

are you sure bootstrap of the extension is called properly? bootstrap stage should run before AccessControl behavior is used.

Could you provide a stack trace of the error so we can see where exactly it occurs?

**Comment by cronfy** [comment]
I see that bootstrap of `yii2-usuario` is called properly. It is mentioned in vendor/yiisoft/extensions.php. And if in `AccessControl` I comment out the  ```$this->user = Instance::ensure($this->user, User::className());``` line, later execution lands in `\Da\User\Bootstrap`.

But `AccessControl::init()` is called prior to ```\yii\base\Application::init()```, and `\Da\User\Bootstrap` not even gets executed because of exception mentioned.

Here is the stacktrace:

```
Fatal error: Uncaught exception 'yii\base\InvalidConfigException' with message User::identityClass must be set.
Stack trace:
#0 /var/www/project/vendor/yiisoft/yii2/base/Object.php(107): yii\web\User->init()
#1 [internal function]: yii\base\Object->__construct(Array)
#2 /var/www/project/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
#3 /var/www/project/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\web\\User', Array, Array)
#4 /var/www/project/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\web\\User', Array, Array)
#5 /var/www/project/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#6 /var/www/project/vendor/yiisoft/yii2/di/Instance.php(164): yii\di\ServiceLocator->get('user')
#7 /var/www/project/vendor/yiisoft/yii2/di/Instance.php(137): yii\di\Instance->get(NULL)
#8 /var/www/project/vendor/yiisoft/yii2/filters/AccessControl.php(100): yii\di\Instance::ensure('user', 'yii\\web\\User')
#9 /var/www/project/vendor/yiisoft/yii2/base/Object.php(107): yii\filters\AccessControl->init()
#10 [internal function]: yii\base\Object->__construct(Array)
#11 /var/www/project/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
#12 /var/www/project/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\filters\\Acc...', Array, Array)
#13 /var/www/project/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\filters\\Acc...', Array, Array)
#14 /var/www/project/vendor/yiisoft/yii2/base/Component.php(183): yii\BaseYii::createObject(Array)
#15 /var/www/project/vendor/yiisoft/yii2/BaseYii.php(529): yii\base\Component->__set('as beforeReques...', Array)
#16 /var/www/project/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(yii\web\Application), Array)
#17 /var/www/project/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#18 /var/www/project/web/index.php(15): yii\base\Application->__construct(Array)
#19 {main}
thrown in /var/www/project/vendor/yiisoft/yii2/web/User.php on line 163```

**Comment by garizlo** [comment]
In yii 2.0.14 the same problem. 
When configuring the behavior through the config, the init behavior method is first called, then the bootstrapping of the yii.

**Comment by arollmann** [comment]
Solved it like that, in config/web.php:

'as beforeRequest' => [
        'class' => \yii\filters\AccessControl::class,
        'user' => [
		'identityClass' => \Da\User\Model\User::class   //<-- HERE
	],
	'ruleConfig' => [
		'class' => 'Da\User\Filter\AccessRuleFilter',
	],
        'rules' => [ ... ],
],

Had the idea reading doc in https://github.com/yiisoft/yii2/blob/master/framework/filters/AccessControl.php:
/**
   * Starting from version 2.0.2, this can also be a configuration array for creating the object.
   * /
public $user = 'user';

So did I.

**Comment by arollmann** [comment]
I think we can close this issue ;-)
