### ISSUE TITLE
asArray() with select undefined id

### ISSUE THREAD

**Issue by Jasurbek94** [yiisoft/yii2#14768]
### What steps will reproduce the problem?

```php
->select(['country_id'])
                ->groupBy(['country_id'])
                ->asArray()
                ->all();
```

executing this code have been producing an error undefined index: id;
vendor\yiisoft\yii2\db\ActiveRelationTrait.php line 458

### What is the expected result?

array of  array of ids
but 

```php
->select(['country_id'])
                ->groupBy(['country_id'])
                ->asArray()
                ->column();
```

it is working!

### What do you get instead?

executing this code have been producing an error undefined index: id;
vendor\yiisoft\yii2\db\ActiveRelationTrait.php line 458

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6
| Operating system | windows-7

full query

```php
 $countries_id = Moments::find()->joinWith(['addresses',], true, 'inner join')
                ->where([MomentAddresses::tableName() . '.status' => 0])
                ->select(['country_id'])
                ->groupBy(['country_id'])
                ->asArray()
                ->all();
```

as i tested the problem is asArray() is not working with select()

**Comment by Alex-Code** [comment]
Does it work if you also select the `id` column?
If you don't need the relational data in the result you can turn eager loading off.

```php
//...
$countries_id = Moments::find()->joinWith(['addresses',], false, 'inner join')
//...
```

**Comment by samdark** [comment]
It happens because when you do `all()` for AR query it returns ARs which need a primary key you're not selecting.

**Comment by Jasurbek94** [comment]
It happens because when you do all() for AR query it returns ARs which need a primary key you're not selecting.
ok! maybe this is crazy question but why it is working without asArray()?

**Comment by Jasurbek94** [comment]
**Alex-Code**  i solved my problem with ->column()  but i want to know the reason!
i use Yii2 more offen and i want to contribute to yii2 also but i think at the moment my knowledge is not enough to do this!

**Comment by samdark** [comment]
Because when using `asArray()` you won't get relations data.

**Comment by Jasurbek94** [comment]
может я не  понял вас, как  я понял вас с asArray() запрос должен работать?
без использования метода ->asArray() запрос работает с методом ->all(), он создает AR
спс за ваш внимание и ответ!

**Comment by samdark** [comment]
Поправил комментарий, ошибся в нём. asArray() заставляет вытянуть relation-ы сразу, а им требуются ключи.

**Comment by pentiumd2015** [comment]
В свое время необходимо было очищать eager подгрузку из запроса. $this->with = null не помог, поскольку еще в ключах join есть указатель подгружать ли данные связей. Написал простой метод для ActiveQuery, который помог:

`public function resetWith()
    {
        $this->with = [];

        if($this->joinWith){
            foreach($this->joinWith AS &$join){
                $join[1] = false;
            }

            unset($join);
        }

        return $this;
    }`

**Comment by pentiumd2015** [comment]
Также метод, позволяющий просмотреть весь запрос, который будет выполнен:

```
public function getRawSql()
    {
        $builder = Yii::$app->db->queryBuilder;

        $query = clone $this;
        $query->resetWith();

        return $query->prepare($builder)->createCommand()->rawSql;
    }
```

Главная особенность в том, чтобы очищать eager подгрузку, иначе будут те же ошибки с ключами

**Comment by forzi** [comment]
> **Alex-Code** i solved my problem with ->column() but i want to know the reason! i use Yii2 more offen and i want to contribute to yii2 also but i think at the moment my knowledge is not enough to do this!

I think, this is actually a bug of yii, because such way is working:

```
array_map(
    function ($val) {
                return $val->toArray(); //or may be ->toArray(['country_id'])
            },
    Moments::find()->joinWith(['addresses',], true, 'inner join')
                ->where([MomentAddresses::tableName() . '.status' => 0])
                ->select(['country_id'])
                ->groupBy(['country_id'])
                ->all();
);
```

So, asArray method needs different realization in yii.
