### ISSUE TITLE
Avoid `Html::addCssClass` array to string conversion error

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#14770]
### What steps will reproduce the problem?
When `options` is an empty array and a set of CSS classes are added as an array - the second condition in [Line 1907](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1907) is executed which wrongly in this case assigns an array instead of converting it to a string.

### What is the expected result?
CSS class setting must always be a string.

### What do you get instead?
An array instead of a string.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13 (dev)
| PHP version      | Any 
| Operating system | Any

Will submit a PR separately to correct this.

**Comment by klimov-paul** [comment]
This is not an issue as tag `class` option can be specified as array.
Following unit test passes correctly:

```php
$this->assertEquals('<a class="test1 test2"></a>', Html::tag('a', '', ['class' => ['test1', 'test2']]));
```

Same behavior applies to `data` and `style`.

There is no issue here.

**Comment by kartik-v** [comment]
Actually the issue more is in `yii\widgets\ActiveField` and have raised another issue #14773. 

`ActiveField` expects the CSS classes to be passed as a string.
