### ISSUE TITLE
BUG Extension validate don`t work 

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#14778]
Extension validate don`t work 

### What steps will reproduce the problem?
print_r([$model, $model->validate()])
### What is the expected result?
    [0]=>
    object(frontend\models\ClaimItemPhoto)#4431 (10) {
      ["claimItemClass":protected]=>
      string(25) "frontend\models\ClaimItem"
      ["file_column"]=>
      string(9) "file_path"
      ["_attributes":"yii\db\BaseActiveRecord":private]=>
      array(2) {
        ["claim_item_id"]=>
        string(2) "95"
        ["file_path"]=>
        string(17) "59b10a6f7a424.csv"
      }
      ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
      NULL

              ["_errors":"yii\base\Model":private]=>
              NULL
              ["_validators":"yii\base\Model":private]=>
              NULL
              ["_scenario":"yii\base\Model":private]=>
              string(7) "default"
              ["_events":"yii\base\Component":private]=>
              array(2) {
                ["beforeInsert"]=>
                array(1) {
                  [0]=>
                  array(2) {
                    [0]=>
                    array(2) {
                      [0]=>
                      object(common\behaviors\TimestampBehavior)#4494 (6) {
                        ["createdAtAttribute"]=>
                        string(10) "created_at"
                        ["updatedAtAttribute"]=>
                        string(10) "updated_at"
                        ["value"]=>
                        NULL
                        ["attributes"]=>
                        array(2) {
                          ["beforeInsert"]=>
                          array(2) {
                            [0]=>
                            string(10) "created_at"
                            [1]=>
                            string(10) "updated_at"
                          }
                          ["beforeUpdate"]=>
                          string(10) "updated_at"
                        }
                        ["skipUpdateOnClean"]=>
                        bool(true)
                        ["owner"]=>
                        *RECURSION*
                      }
                      [1]=>
                      string(18) "evaluateAttributes"
                    }
                    [1]=>
                    NULL
                  }
                }
                ["beforeUpdate"]=>
                array(1) {
                  [0]=>
                  array(2) {
                    [0]=>
                    array(2) {
                      [0]=>
                      object(common\behaviors\TimestampBehavior)#4494 (6) {
                        ["createdAtAttribute"]=>
                        string(10) "created_at"
                        ["updatedAtAttribute"]=>
                        string(10) "updated_at"
                        ["value"]=>
                        NULL
                        ["attributes"]=>
                        array(2) {
                          ["beforeInsert"]=>
                          array(2) {
                            [0]=>
                            string(10) "created_at"
                            [1]=>
                            string(10) "updated_at"
                          }
                          ["beforeUpdate"]=>
                          string(10) "updated_at"
                        }
                        ["skipUpdateOnClean"]=>
                        bool(true)
                        ["owner"]=>
                        *RECURSION*
                      }
                      [1]=>
                      string(18) "evaluateAttributes"
                    }
                    [1]=>
                    NULL
                  }
                }
              }
              ["_behaviors":"yii\base\Component":private]=>
              array(1) {
                [0]=>
                object(common\behaviors\TimestampBehavior)#4494 (6) {
                  ["createdAtAttribute"]=>
                  string(10) "created_at"
                  ["updatedAtAttribute"]=>
                  string(10) "updated_at"
                  ["value"]=>
                  NULL
                  ["attributes"]=>
                  array(2) {
                    ["beforeInsert"]=>
                    array(2) {
                      [0]=>
                      string(10) "created_at"
                      [1]=>
                      string(10) "updated_at"
                    }
                    ["beforeUpdate"]=>
                    string(10) "updated_at"
                  }
                  ["skipUpdateOnClean"]=>
                  bool(true)
                  ["owner"]=>
                  *RECURSION*
                }
              }
            }
          }
          ["_errors":"yii\base\Model":private]=>
          NULL
          ["_validators":"yii\base\Model":private]=>
          NULL
          ["_scenario":"yii\base\Model":private]=>
          string(7) "default"
          ["_events":"yii\base\Component":private]=>
          array(0) {
          }
          ["_behaviors":"yii\base\Component":private]=>
          array(0) {
          }
        }
      }
      ["_errors":"yii\base\Model":private]=>
      array(0) {
      }
      ["_validators":"yii\base\Model":private]=>
      object(ArrayObject)#4470 (1) {
        ["storage":"ArrayObject":private]=>
          object(yii\validators\FileValidator)#4484 (24) {
            ["extensions"]=>
            array(3) {
              [0]=>
              string(3) "png"
              [1]=>
              string(3) "jpg"
              [2]=>
              string(4) "jpeg"
            }
            ["checkExtensionByMimeType"]=>
            bool(false)
            ["mimeTypes"]=>
            array(0) {
            }
            ["minSize"]=>
            NULL
            ["maxSize"]=>
            int(2097152)
            ["maxFiles"]=>
            int(1)
            ["message"]=>
            string(48) "Загрузка файла не удалась."
            ["uploadRequired"]=>
            string(28) "Загрузите файл."
            ["tooBig"]=>
            string(118) "Файл «{file}» слишком большой. Размер не должен превышать {formattedLimit}."
            ["tooSmall"]=>
            string(118) "Файл «{file}» слишком маленький. Размер должен быть более {formattedLimit}."
            ["tooMany"]=>
            string(157) "Вы не можете загружать более {limit, number} {limit, plural, one{файла} few{файлов} many{файлов} other{файла}}."
            ["wrongExtension"]=>
            string(127) "Разрешена загрузка файлов только со следующими расширениями: {extensions}."
            ["wrongMimeType"]=>
            string(119) "Разрешена загрузка файлов только со следующими MIME-типами: {mimeTypes}."
            ["attributes"]=>
            array(1) {
              [0]=>
              string(9) "file_path"
            }
            ["on"]=>
            array(2) {
              [0]=>
              string(10) "api-create"
              [1]=>
              string(10) "api-update"
            }
            ["except"]=>
            array(0) {
            }
            ["skipOnError"]=>
            bool(true)
            ["skipOnEmpty"]=>
            bool(true)
            ["enableClientValidation"]=>
            bool(true)
            ["isEmpty"]=>
            NULL
            ["when"]=>
            NULL
            ["whenClient"]=>
            NULL
            ["_events":"yii\base\Component":private]=>
            array(0) {
            }
            ["_behaviors":"yii\base\Component":private]=>
            NULL
          }
        }
      }
      ["_scenario":"yii\base\Model":private]=>
      string(10) "api-create"
      ["_events":"yii\base\Component":private]=>
      array(1) {
        ["afterDelete"]=>
        array(1) {
          [0]=>
          array(2) {
            [0]=>
            array(2) {
              [0]=>
              *RECURSION*
              [1]=>
              string(10) "deleteFile"
            }
            [1]=>
            NULL
          }
        }
      }
      ["_behaviors":"yii\base\Component":private]=>
      array(0) {
      }
    }
    [1]=>
       bool(true)
    }
  

### What do you get instead?
validate = false

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7
| Operating system | Ubuntu

**Comment by des1roer** [comment]
model with validator

    <?php

    namespace common\models;

    use yii\helpers\FileHelper;
    use yii\db\ActiveQuery;
    use yii\db\ActiveRecord;
    use yii\web\UploadedFile;

    class ClaimItemPhoto extends ActiveRecord
    {
        protected $file_column = 'file_path';

        protected $claimItemClass = ClaimItem::class;

        public static function tableName()
        {
            return 'claim_item_photo';
        }

        public function scenarios()
        {
            return array_merge(
                parent::scenarios(),
                [
                    'api-create' => ['claim_item_id', 'file_path'],
                    'api-update' => ['claim_item_id', 'file_path'],
                ]
            );
        }

        public function rules()
        {
            return [
                ['file_path', 'file', 'extensions' => 'png, jpg, jpeg', 'maxSize' => 1024 * 1024 * 2],
                ['file_path', 'filter', 'filter' => [$this, 'filterUploadFile']],
            ];
        }

        public function getPath()
        {
            if (isset($this->claimItem)) {
                $path = $this->claimItem->claim->user->getFilesPath() . '/claims/' . $this->claimItem->claim_id;
                if (!file_exists($path)) {
                    FileHelper::createDirectory($path);
                }

                return $path;
            }

            return false;
        }

        public function getClaimItem() : ActiveQuery
        {
            return $this->hasOne(ClaimItem::className(), ['id' => 'claim_item_id']);
        }

        /**
         * Загрузка файла.
         *
         * @param mixed $value
         * @return null|string
         */
        public function filterUploadFile($value)
        {
            $name = null;
            $file = UploadedFile::getInstanceByName($this->file_column);
            if (!$file) {
                $this->addError($this->file_column, 'Не передан файл');
            } else {
                if (!$this->isNewRecord) {
                    $this->deleteFile();
                }

                $name = uniqid() . '.' . $file->extension;
                $path = $this->getPath();

                if (!$path || !$file->saveAs($path . '/' . $name)) {
                    $this->addError($this->file_column, 'Не удалось загрузить файл');
                }
            }

            return $name;
        }
    }

test

        <?php
        
        namespace tests\codeception\frontend\api;
        
        class ClaimItemPhotoTest extends \Codeception\TestCase\Test
        {
            /**
             * @var \tests\codeception\frontend\ApiTester
             */
            protected $tester;
        
            public function testCreateDelete()
            {
                //Проверяем валидацию
                $fileIn = codecept_data_dir() . 'bblogo-optim.svg';
                $post = [
                    'claim_item_id' => (string) $claim_item_id,
                ];
                $I->sendPOST('api/v3/claim-item-photo/', $post, ['file_path' => $fileIn]);
                $I->seeResponseCodeIs(422);
            }
        }

![image](https://user-images.githubusercontent.com/10970793/30210743-261980e2-94b7-11e7-924c-2685fe8ebd36.png)

correct load svg file !!!

**Comment by cebe** [comment]
what is the code of the controller action that handles the upload?
