### ISSUE TITLE
Suggestion: Add type 'date' to CompareValidator

### ISSUE THREAD

**Issue by lilmaddiekins** [yiisoft/yii2#14780]
It would be nice to be able to compare dates with this validator, to make it easy to make sure two dates form a valid range, for example.

**Comment by dmirogin** [comment]
Yeah, we have comparing for numbers and strings. And we can add this type too.
https://github.com/yiisoft/yii2/blob/master/framework/validators/CompareValidator.php#L192

I think bringing values to DateTime object in this case would be a solution.

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/10832, https://github.com/yiisoft/yii2/issues/7047, https://github.com/yiisoft/yii2/issues/3581

**Comment by cebe** [comment]
We have a case documented for comparing date values: http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#comparing-date-values not sure if it will be easy to build that into compare validator, as you need to ensure validity on the dates before you can compare them.
