### ISSUE TITLE
PR #14499 possible BC breaking

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#14782]
Follow-up to https://github.com/yiisoft/yii2/commit/8ae2223c6a50eda8534ea187357df1a167b65cdd

The updated code follows the order, described in [documentation](http://www.yiiframework.com/doc-2.0/guide-input-validation.html):

1. Built-in validator
2. Method in model or closure
3. Custom validator

But still it can break code, relied on previous not-documented behaviour.
How about mentioning it in UPGRADE.md?

**Comment by samdark** [comment]
Yes, could be mentioned.
