### ISSUE TITLE
RBAC / DbManager: not working properly if userId is (int)0

### ISSUE THREAD

**Issue by wollepetry** [yiisoft/yii2#14781]
### What steps will reproduce the problem?
1. Use DbManager and RBAC
2. Create a user with id = 0
3. assign in DB Table "auth_assignment" a role 'admin' and assign user_id = 0 to it
4. check assigned role via "Yii::$app->user->can('admin');"
### What is the expected result?
It should return true, because user_id=0 is assigned to role 'admin'

### What do you get instead?
It returns false, because a problem in DbManager.php ->
in Function "getAssignments($userId)" (Line 695):
The function "empty()" will return true for (int)0 values (see php documentation: http://php.net/manual/en/function.empty.php) and jump out of the function. The function will not assign the correct roles for the user.

Changing the userID in the user table to 1 fixed the problem, RBAC is only working with userID >0.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.9
| Operating system | Win 7 x64

**Comment by dmirogin** [comment]
Thanks! This still is not available in stable version. It was fixed in master [here](https://github.com/yiisoft/yii2/pull/14498)
