### ISSUE TITLE
Formatter::asRelativeTime always outputs "just now" when interval=0

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#14796]
### What steps will reproduce the problem?
Yii::$app->formatter->asRelativeTime($model->assigned_date, $mode->creation_date)
### What is the expected result?
Something not specific to the current time, like "instantly"
### What do you get instead?
"just now"
That makes sense when relative time is compared to the current time, but not when we supply comparison datetime in a second argument.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13-dev
| PHP version      | 7.0
| Operating system | Windows 2012

**Comment by dmirogin** [comment]
I don't see significant difference between "instantly" and "just now". If you want to use your own message, you can change translation or inherit this method.

**Comment by dryu** [comment]
The significant difference is in context. "Just now" implies current time context, and this is not desired when we do not format relative to current time.

When I create a profile page, where attributes like 'creation_date' and 'closed_date' are visible, if I want to format the relative time between these two, current output "just now" makes no sense in case creation_date = close_date. I could have created the incident 5 years ago, it does not mean that the relative time between creation and close dates is "just now". 

We need to use better wording here.

**Comment by cebe** [comment]
in that case also "in 5 years" or "5 years ago" does not make sense as an output. You might want to use `asDuration()` instead.

**Comment by dryu** [comment]
The idea is to format the difference between creation date and some other date as relative time. If both dates are equal, the formatting "just now" is incorrect when the relation basis is not the current time. 

I can use plenty of other means to do achieve the desired effect, however, this defect report is about the formatting output for zero intervals which is always semantically relative to the current time even though this is not always true. 

-A

**Comment by cebe** [comment]
"in 5 years" or "5 years ago" is also semantically relative to the current time.

**Comment by dryu** [comment]
Which also not correct and should be registered as a defect. 

-A

**Comment by cebe** [comment]
The description of the method is "Formats the value as the time interval between a date and now in human readable form." so the output is correct.

If you want to format an interval without the reference to the current time, there is asDuration().

**Comment by dryu** [comment]
That settles it then, thanks for clarifying.

-A
