### ISSUE TITLE
AR::load() - what's the point?

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#14791]
Everywhere in code I see stuff like

```
if (!$model->load($input, '') || !$model->validate()) {
            \Yii::$app->response->setStatusCode(424);
            return $model->getErrors();
        }
```
or
```
if (!$model->load($input, '') || !$model->save()) {
            \Yii::$app->response->setStatusCode(424);
            return $model->getErrors();
        }
```

BUT

load does not set error, so we end up with error without error message.

Is it safe to write code like this ?
```
$model->load($input, '');
if (!$model->save()) {
            \Yii::$app->response->setStatusCode(424);
            return $model->getErrors();
        }
```
I'm very confused with this method and its existence

regards

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7
| Operating system | Debian 9

**Comment by cebe** [comment]
> load does not set error, so we end up with error without error message.

validate() and save() will set the errors, if validation fails.

> Is it safe to write code like this ?

dependent on the context that would be okay. you need to return something if no data is sent. You may use setAttributes() instead of load() if you have no formName.
