### ISSUE TITLE
Pagination not working with findBySql?

### ISSUE THREAD

**Issue by dungvaph03374** [yiisoft/yii2#14790]
If i use find() it work like normal but when i'm using findBySql() for search page it not.
Look like offset doesn't work with findBySql, i have to set offset manually to query
What i'm missing?
```
$query = Model::findBySql("Select * from table");
$countQuery = clone $query;
$pages = new Pagination(['totalCount' => $countQuery->count(),'defaultPageSize' => 16]);
$anime = $query->offset($pages->offset)
	->limit($pages->limit)
	->all();
return $this->render('search', [
	'anime' => $anime,
	'pages' => $pages,
]);
```
```
$query = Model::find();
$countQuery = clone $query;
$pages = new Pagination(['totalCount' => $countQuery->count(),'defaultPageSize' => 16]);
$models= $query->offset($pages->offset)
	->limit($pages->limit)
	->all();
return $this->render('search', [
	'models' => $models,
	'pages' => $pages,
]);
```

**Comment by rob006** [comment]
This is known limitation of `findBySql()`. You may consider using `SqlDataProvider`.

> Note that because the SQL statement is already specified, calling additional query modification methods (such as where(), order()) on the created yii\db\ActiveQuery instance will have no effect. However, calling with(), asArray() or indexBy() is still fine.

http://www.yiiframework.com/doc-2.0/yii-db-activerecord.html#findBySql()-detail

See: https://github.com/yiisoft/yii2/issues/12205
