### ISSUE TITLE
pgsql findColumns execute too long time

### ISSUE THREAD

**Issue by shengbinxu** [yiisoft/yii2#14792]
### What steps will reproduce the problem?
when use ActiveDataProvider, it will execute yii\db\pgsql\Schema->findColumns() method, and the sql in this mehod execute more than 250ms。
![image](https://user-images.githubusercontent.com/3232275/30269686-4c3571de-971c-11e7-9791-89e85e27e071.png)

### What is the expected result?
how to avoid this slow operator?
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6
| Operating system | centos

**Comment by samdark** [comment]
What's your pgsql version?

**Comment by samdark** [comment]
In production you can enable cache for DB schema.

**Comment by samdark** [comment]
Not enough info to reproduce. Closing.
