### ISSUE TITLE
[2.1] Split ServiceLocator::has()

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#14794]
`ServiceLocator::has()` currently has a boolean argument `$checkInstance`.

According to the SRP this function should be split into 2 functions, for example:
````
public function has($id);
public function hasDefinition($id);
````

**Comment by samdark** [comment]
Makes sense to me.

**Comment by samdark** [comment]
But I doubt we need service locator at all...

**Comment by samdark** [comment]
DI container is a service locator as well...

**Comment by SamMousa** [comment]
Yes, I was thinking on proposing to split that as well; make the DI container use a service locator for singletons and a factory for the other definitions.

That way all concerns are separated:
Factory: transform definition to object.
ServiceLocator: use factory and cache result.
DI: use service locator and factory to create objects... 

I realize factory and container have some overlap; will think about it some more

**Comment by samdark** [comment]
I've meant dropping service locator as a separate class leaving container only.

**Comment by SamMousa** [comment]
I know, but it might make sense to split the container class as well..

DI is essentially something that is stateless; it creates a dependency
tree, then it instantiates the dependencies.
This instantiation could be done by a factory or service locator instead of
storing the definitions inside the container I haven't got a clear idea of
where I'm going with this yet though... :)

**Comment by samdark** [comment]
Closing since we have a separate DI package now and issue doesn't seem to be up to date.
