### ISSUE TITLE
is null condition will be unset when use addFilterWhere

### ISSUE THREAD

**Issue by lyd600lty** [yiisoft/yii2#14805]
### What steps will reproduce the problem?
````php
$query->andFilterWhere(['or',
        ['column' => null],  // ['=', 'column', null] get the same result
        ['>', 'column', 1],
])
````
### What is the expected result?
...   AND ((`column` > 1) OR (`column` IS NULL))

### What do you get instead?
AND ((`column` > 1) )

### Additional info
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryTrait.php#L258
![image](https://user-images.githubusercontent.com/2917899/30366356-5503b320-989d-11e7-8f3b-52bd461ce556.png)
I found the condition is unset here...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0
| Operating system | OSX

**Comment by klimov-paul** [comment]
This is expected behavior as `andFilterWhere()` removes conditions with empty values.
You should use `andWhere()` instead to achieve desired results.
