### ISSUE TITLE
GridView table tfoot should come after tbody

### ISSUE THREAD

**Issue by trombipeti** [yiisoft/yii2#14806]
The current order is thead, tfoot, tbody (as it was used to be done) in the GridView table element, but the new HTML 5.1 recommendation changes this: https://www.w3.org/TR/html51/tabular-data.html#tabular-data: " [...] followed optionally by a thead element, followed by either zero or more tbody elements or one or more tr elements, followed optionally by a tfoot element [...] ".
This change would also produce nicer mouse selection behaviour.

The fix would be very simple, one would have to swap two lines in yii2\grid\GridView.php, in the function renderItems().

### What steps will reproduce the problem?
Create a GridView with 'showFooter' => true and with some data.

### What is the expected result?
In the DOM tree, the order of the table children should be: thead, tbody, tfoot. (Of course with colgroup/caption etc if set).

### What do you get instead?
The tfoot element comes before tbody. This also changes the order of selected elements (try selecting the table content with the mouse and copy-pasting it into Excel, the footer will come as the second row).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.1
| Operating system | Windows 7

**Comment by rob006** [comment]
Duplicates: #14677

See https://github.com/yiisoft/yii2/pull/2801#issuecomment-37976220

**Comment by rob006** [comment]
I don't think that we should change default position of footer, but we could make it configurable.

**Comment by trombipeti** [comment]
Yes, making it configurable would be a better idea indeed (and leaving the default as it is now).
