### ISSUE TITLE
Change behaviors to use ServiceLocator tree traversal

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#14800]
In 2.0.13 we will have tree traversal, meaning, inside a module we can do `$this->get('user')` and we will either get the applications' `User` component or the modules' `User` component.

Controllers have a `module` property, behaviors have an owner.

For example, `AccessControl` has this:
````
public function init()
    {
        parent::init();
        if ($this->user !== false) {
            $this->user = Instance::ensure($this->user, User::className());
        }
        ...
    }
````

This could now be replaced by this:
````
public function init()
    {
        parent::init();
        if ($this->user !== false) {
            $this->user = $this->owner->get($this->user);
        }
        ...
    }
````

This would lose the functionality of using the DI container as a fallback ServiceLocator (which doesn't make much sense anyway). If really needed we could add it as a fall back:
````
 $this->user = $this->owner->has($this->user) ? $this->owner->get($this->user) : Instance::ensure($this->user);
````
Note that this will check the application module twice (once as the root of tree traversal, once via `Instance::get()`).

# Todo

- [ ] `ActionFilter`
- [ ] `VerbFilter`
- [ ] `base\Controller` --> uses `Yii::$appgetView()` could be: `$this->module->get('view')`, need to think about how to handle those service locator helper functions
- [ ] `CacheController`
- [ ] `HttpCache`
- [ ] `Cors`
- [ ] `HostControl`
- [ ] `PageCache`
- [ ] `RateLimiter`
- [ ] `VerbFilter`
- [ ] `AuthMethod`

**Comment by samdark** [comment]
What are the pros?

**Comment by SamMousa** [comment]
I have a module that uses a different configuration for a component, for example it has a different model for the `yii\web\User` component.
With this new tree traversal I can configure the module via configuration for example:
````
'modules' => [
    'moduleA' => [
        'components' => [
            'user' => [
                'modelClass' => NotAUser::class
            ]
        ]
    ]
]
````
This now works in my own code where I know to use the module instead of the global stuff.
However when I try to use `AccessControl` in my controller it does not use the correct component.
Instead I have to manually configure the user component in the controller:
````
public function behaviors() 
{
    return [
        'access' => [
            'class' => AccessControl::class,
            'user' => $this->module->get('user')
        ]
    ];
}
````

**Comment by samdark** [comment]
Makes sense.

**Comment by cebe** [comment]
its not necessary to do this in 2.0.13, it can be added later.

**Comment by SamMousa** [comment]
True!

**Comment by SamMousa** [comment]
Any ideas on how to handle `ServiceLocator` helper functions? 
For example, these are all resolved via the `ServiceLocator`:
- `getView()`
- `getResponse()`
- `getRequest()`

However these are defined in `Application`. If I am in a module and I need to get the `View` component I'd expect to do `$..->module->get('view')`.

**Comment by klimov-paul** [comment]
Since component tree traversal been introduced any invocation of `Yii::$app->get()` should be replaced by `Yii::$app->controller->module->get()`. Until then issues like this one will continue to appear.

**Comment by SamMousa** [comment]
@klimov-paul Your suggestion will indeed fix all code to use the tree traversal, I like it as a stop-gap solution.
Do you agree that in cases where we have a local reference to, for example, a controller we should use that instead?

**Comment by klimov-paul** [comment]
I would say that container tree traversal should not be ever applied, but since it is done there is no other choice. Invocations of `Yii::$app->get()` are now inconsistent and should all be replaced by `$currentModule->get()`.
In case module is reachable via direct reference as `$controller->module` - this reference should be used, otherwise `Yii::$app->controller->module->get()`.

Note that construction `Yii::$app->controller->module->get()` is unsafe as at some point application may have no controller instance yet (or already) and `Yii::$app->controller` result is `null`.
Thus there should be new method introduced for this:

```php
class Application extends Module
{
    public function ???($id)
    {
        if ($this->controller === null) {
            return $this->get($id);
        }
        return $this->controller->module->get($id);
    }
}
```

Some suitable name should be picked for it - `get()` is already taken.

**Comment by rob006** [comment]
Maybe introduce something like `Yii::$app->getContext()` which returns current module if available or `Yii::$app` as a fallback.

**Comment by SamMousa** [comment]
All i can do is add my 2cents. @rob006 your argument highlights a problem with the Service Locator pattern in general. 
There is no guarantee in Yii, for any module even the application itself, that a component with a specific name has a specific type. 
That said Yii has several "default" components like `user`, `request`, `db` where it is inadvisable to use these names for different components; you definitely could but some code will definitely break.

Yes you could create a module that has a `user` model that is not a subclass of `yii\web\User`, but since it is still a Yii module you should realize that that is probably a bad idea, especially since you have an almost infinite number of component names available to choose from...

The whole point of tree traversal was to reduce the need for static accessors; they should be avoided. I don't see what problem is solved by PR  #15342.

@klimov-paul could you explain why you need this?

I'll respond inline your PR as well!

**Comment by klimov-paul** [comment]
> I don't see what problem is solved by PR #15342.

Such classes as [BlameableBehavior](https://github.com/yiisoft/yii2/blob/master/framework/behaviors/BlameableBehavior.php) or [Url](https://github.com/yiisoft/yii2/blob/master/framework/helpers/Url.php) will be unable to pick up components from module otherwise.

**Comment by SamMousa** [comment]
Hmm, fair enough, AR is always an issue with static stuff like that, same goes for AR  behaviors.
And same goes for static helpers.

**Comment by rob006** [comment]
> That said Yii has several "default" components like user, request, db where it is inadvisable to use these names for different components; you definitely could but some code will definitely break.

You can say the same about every single name, this is not related only to Yii core components. I can have my own app with component named `facebookApi`, modules which have own `facebookApi` components (compatible with app's `facebookApi`)  and static helper/AR which access these components from current module. Now `favebookApi` is reserved in my app in the same way as `user` and cannot be used as component name by any 3rd party module.

Anyway, in #15342 I just pointed that it breaks BC. If I cannot use `user` as component name in my module, it should be clearly documented. But it may be better to rely on class names instead of component names - "give me implementation of `yii\web\User` for current module" instead of "give me component named `user` for current module".

**Comment by klimov-paul** [comment]
> But it may be better to rely on class names instead of component names - "give me implementation of yii\web\User for current module" instead of "give me component named user for current module".

This can not work, since particular module may have several component matching type `yii\web\User` with different names and so different meanings.

**Comment by rob006** [comment]
> This can not work, since particular module may have several component matching type yii\web\User with different names and so different meanings.

But only one should work as `Yii::$app->user` and this one should be returned in this case.

**Comment by rob006** [comment]
BTW: Exact the same problem: https://github.com/yiisoft/yii2/issues/14421

**Comment by SamMousa** [comment]
Service locators are configured, so each module should definitely document what services it requires and what names it looks for, @rob006. That's the thing about service locators.
As you mentioned, ideally you would not use it at all but instead use dependency injection everywhere; but as @klimov-paul validly states, if there's 2 database connections and your module needs 1 then it is configuration that decides which one your module uses.

All tree traversal does is allow you to override the configuration for modules.

**Comment by rob006** [comment]
> Service locators are configured, so each module should definitely document what services it requires and what names it looks for

Documentation of modules will not help that much if static helpers starts blindly picking components from modules relying only on their names. These helpers will not read documentation and will not undertand, that `user` component in my module should not be used as `Yii::$app->user`.

**Comment by klimov-paul** [comment]
Closed as won't fix.
