### ISSUE TITLE
date format 'mm/dd/yyyy' always yields '10' for day values between 13 and 19 

### ISSUE THREAD

**Issue by ignatiusabraham** [yiisoft/yii2#14809]
### What steps will reproduce the problem?
In Gridview - Editable column - Input-Widget->inputmask-
### What is the expected result?
should be able enter 1-31 as per the month.
### What do you get instead?
date format 'mm/dd/yyyy' always yields '10' for day values between 13 and 19 

### Additional info
worked prior - to composer update
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.7
| Operating system | windows

**Comment by cebe** [comment]
> Editable column

what is that? we do not have that in Yii core.

**Comment by ignatiusabraham** [comment]
Sorry I believe I posted in the wrong forum. Its from Kartik Gridview . I am closing this issue. Thank You
