### ISSUE TITLE
Multi dimension array validation

### ISSUE THREAD

**Issue by faizanktk** [yiisoft/yii2#14804]
I have this form data:
start_time:2017-09-30 01:50:00
end_time:2017-09-30 01:51:00
resources[0][resource_id]:8
resources[0][resource_type]:client
resources[1][resource_id]:1
resources[1][resource_type]:aircraft
resources[2][resource_id]:1
resources[2][resource_type]:instructor

now i want to validate the resource array. To check array is empty or not. Count value
Thanks

**Comment by dmirogin** [comment]
You should combine [yii\validators\RequiredValidator](http://www.yiiframework.com/doc-2.0/yii-validators-requiredvalidator.html) and [EachValidator](http://www.yiiframework.com/doc-2.0/yii-validators-eachvalidator.html) for validating array or use [custom validator](http://www.yiiframework.com/doc-2.0/guide-input-validation.html#creating-validators)
