### ISSUE TITLE
Allow a second operand of LIKE to be a subquery

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#14810]
Currently subquery instead of a value are supported in many places but not LIKE operator. For example:
```PHP
SomeModel::find()->where(['=', 'field', OtherModel::find()->select('field2')->where([...])]);
```
works, while the same with `LIKE` instead of `=` does not:
```PHP
SomeModel::find()->where(['LIKE', 'field', OtherModel::find()->select('field2')->where([...])]);
```
Support for subqueries must be added for LIKE operator too.

**Comment by sergeymakinen** [comment]
Sounds reasonable.

**Comment by rob006** [comment]
Related: #14732, #11218
