### ISSUE TITLE
GridView columns title depends of $provider->query->modelClass only, not use both / only $this->grid->filterModel in common case of usage

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14829]
Order of applied `ifelse` is not ideal for default-like case

https://github.com/yiisoft/yii2/blob/a86c67ddb3fe32c4269b5ed90f8837bc3daf0cff/framework/grid/DataColumn.php#L138-L173

### What steps will reproduce the problem?
1. Gii-generated CRUD: Search model + GridView::widget
2. Expand Search model with addition field - for example `name` of relation model.
order rule + search rule + join in query
3. Expand Search model attributeLabels
```php
    /**
     * @inheritDoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'relationName' => Yii::t('relation', 'Name'),
        ]);
    }
```
4. Use array-definition for column with `attribute`
```php
        'columns' => [
            [
                'format' => 'raw',
                'attribute' => 'relationName',
                'content' => \backend\views\ViewHelper::relatedName(),//function with view
            ],
        ],
```
### What is the expected result?
Table header fill from `searchModel` `attributeLabels()`

### What do you get instead?
Table header fill from `dataProvider`s model  `attributeLabels()`
case of line 147
```php
if ($provider instanceof ActiveDataProvider && $provider->query instanceof ActiveQueryInterface)...
```

and I must put unexpected additional `label`
```php
        'columns' => [
            [
                'format' => 'raw',
                'attribute' => 'relationName',
                'label' => $searchModel->getAttributeLabel('relationName'),
                'content' => \backend\views\ViewHelper::relatedName(),//function with view
            ],
        ],
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13@dev

**Comment by klimov-paul** [comment]
Duplicates #4504

**Comment by bscheshirwork** [comment]
@klimov-paul please, see changes in PR. 


I read origin thread... So... Same situation year by year. 


may be this is mark for review the opinion?

**Comment by bscheshirwork** [comment]
Data in grid not for only one model, can be from many case, generated in cascade view, etc
Search model is representation of header. Same for header. (In default case)
