### ISSUE TITLE
Merging container definitions with any class configs

### ISSUE THREAD

**Issue by 3dmaxpayne** [yiisoft/yii2#14821]
When I am trying to setup default configs for some class I cannot do it for double nesting configs. 
example:
```
'container' => [
        'definitions' => [
            zxbodya\yii2\tinymce\TinyMce::class => [
                'settings' => [
                    'height' => '500',
                ],
                'someConfig' => 'value1',
            ],
        ],
    ],
```

value for **someConfig** will apply successfully, but value for **settings** will not apply.
it because you use array_merge instead of array_merge_recursive [here ](https://github.com/yiisoft/yii2/blob/master/framework/di/Container.php#L168)

So, my propose is replace this function to array_merge_recursive 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.22
| Operating system | Ubuntu 16.04

**Comment by rob006** [comment]
Using `array_merge_recursive()` will give your wrong results when you try to override some values: https://3v4l.org/Hg6mD . 
People may also rely on this behavior, so using `ArrayHelper::merge()` will break BC.

**Comment by klimov-paul** [comment]
Duplicates #4154

**Comment by rob006** [comment]
This can be fixed in 2.1, since after #11899 we have a way to fully replace array value.

**Comment by SilverFire** [comment]
@rob006 so would you like to close #14821 or point it to 2.1?

**Comment by rob006** [comment]
@SilverFire You mean #14822? I'm fine with closing it, since it does not contain any valuable changes. Unless @3dmaxpayne wants to rewrite it with `ArrayHelper::merge()`, docs, tests and upgrade notes.

**Comment by 3dmaxpayne** [comment]
yes, I still want. for me it is actual, but I didn't get what you guys think about it?

**Comment by samdark** [comment]
Closing since new DI container doesn't seem to have it anymore.

**Comment by DrDeath72** [comment]
2.0.x still need this fix

**Comment by samdark** [comment]
If you know a way to fix it without any backwards compatibility breaks, you're very welcome to suggest it.

**Comment by DrDeath72** [comment]
maybe add some key to definition array that enable ArrayHelper::merge feature, if key not exists use old array_merge by default?

**Comment by samdark** [comment]
That could work. Want to try implementing it? If the change would not be big I think it's possible to merge it.

**Comment by DrDeath72** [comment]
https://github.com/yiisoft/yii2/pull/17436
