### ISSUE TITLE
No shortcut for createAbsoluteUrl()?

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14827]
So, `\yii\helpers\Url` not have any way to render full link?
Is it done on purpose?

### What is the expected result?
```php
\yii\helpers\Url::absoluteUrl(['/user/view', 'id' => $id]);
```
### What do you get instead?
```php
\Yii::$app->urlManager->createAbsoluteUrl(['/user/view', 'id' => $id]);
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13@dev

**Comment by dungphanxuan** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L503
about?

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseUrl.php#L204-L205

**Comment by bscheshirwork** [comment]
Thank you! 
i.e. 
```
Url::toRoute(['/user/view', 'id' => $id], '');
```
some similar function as a
```
\Yii::$app->urlManager->createAbsoluteUrl(['/user/view', 'id' => $id]);
```

But I can see error into PHPDoc now:
In this doc accept pass `null`
https://github.com/yiisoft/yii2/blob/a86c67ddb3fe32c4269b5ed90f8837bc3daf0cff/framework/web/UrlManager.php#L497-L499

In this doc
https://github.com/yiisoft/yii2/blob/a86c67ddb3fe32c4269b5ed90f8837bc3daf0cff/framework/helpers/BaseUrl.php#L204-L206

`null` not acceptable, but here:
https://github.com/yiisoft/yii2/blob/a86c67ddb3fe32c4269b5ed90f8837bc3daf0cff/framework/helpers/BaseUrl.php#L101-L103
any value is `!== true && !is_string` rise send `null` 

i.e. in `toRoute`
```
     * - `false` (default): generating a relative URL.
     * - `true`: returning an absolute base URL whose scheme is the same as that in [[\yii\web\UrlManager::$hostInfo]].
     * - string: generating an absolute URL with the specified scheme (either `http`, `https` or empty string
     *   for protocol-relative URL).
     * - `null`:  generating an absolute URL with the current request scheme
```
