### ISSUE TITLE
CSRF token validation fails in Gii

### ISSUE THREAD

**Issue by monzol** [yiisoft/yii2#14820]
### What steps will reproduce the problem?
- upgrade Yii2 to v2.0.12
- delete cookies
- Try to create a new controller, model etc. in Gii
- Fill in form and click 'Preview'

### What is the expected result?
Preview page should appear

### What do you get instead?
Bad Request (# 400)
Unable to verify your data submission

### Additional info
As a temporary workaround, you can disable CSRF validation in config:
```
$config = [
    'components' => [
        'request' => [
            // ...
            'enableCsrfValidation' => false
            // ...            
    ]
    // ...
];
```
Also, if you downgrade to 2.0.11, then use Gii (e.g. click 'Preview'), then upgrade to 2.0.12, you can continue using Gii until you delete the cookies.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6.30
| Operating system | Linux (CentOS 7)

**Comment by samdark** [comment]
Please try with code from master branch.

**Comment by monzol** [comment]
@samdark Yes, it works with code from master. Thanks!
