### ISSUE TITLE
Ability to bound dependencies in controller actions by type-hinting the parameters

### ISSUE THREAD

**Issue by Linguisto** [yiisoft/yii2#14833]
### Feature
It would be great to have an ability to bound dependencies in controller actions by just type-hinting them. In case of web/Controller, it can check if a type-hinting class implements `ActiveRecordInterface`, and if yes, it should try to call the `findOne` method with the data provided by the parameter; if `findOne` returns `null` then it just throws `NotFoundHttpException`.

### Suggested syntax

```PHP
public function actionIndex(Request $request)
```
```PHP
public function actionView(Entity $model) // Entity extends ActiveRecord
```
```PHP
public function actionSomeAction(SomeDependencyInterface $someDependency) // interface binding defined in config
```

**Comment by rob006** [comment]
> it can check if a type-hinting class implements ActiveRecordInterface, and if yes, it should try to call the findOne method with the data provided by the parameter

Which parameter?

**Comment by Linguisto** [comment]
The type-hinted one.

**Comment by klimov-paul** [comment]
Duplicates #9890
