### ISSUE TITLE
less not working on Yii2.

### ISSUE THREAD

**Issue by handysolver** [yiisoft/yii2#14839]
### What steps will reproduce the problem?
On a mac, version 10.12.4
* Installed less globally:
npm install -g less
* added path of less in configuration of AssetManager component
```
'assetManager'=>[
            'converter' => [
                'class' => 'yii\web\AssetConverter',
                'commands' => [
                    'less' => ['css', '/usr/local/bin/lessc {from} {to} --no-color'],
                ],
            ],
        ],
```
### What is the expected result?
* that my .less files are being processed into .css files
### What do you get instead?
*The following error:
```
AssetConverter command '/usr/local/bin/lessc '/Applications/MAMP/htdocs/yiiproject/backend/web/css/style.less' '/Applications/MAMP/htdocs/yiiproject/backend/web/css/style.css' --no-color' failed with exit code 127:
STDOUT:

STDERR:
env: node: No such file or directory
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0. - Yes
| PHP version      | 
| Operating system | Mac 10.12.4

**Comment by handysolver** [comment]
Also wanted to mention that both files, the .less and .css exist.

**Comment by rob006** [comment]
Does it work if you call this command manually?
```console
/usr/local/bin/lessc '/Applications/MAMP/htdocs/yiiproject/backend/web/css/style.less' '/Applications/MAMP/htdocs/yiiproject/backend/web/css/style.css' --no-color
```

**Comment by schmunk42** [comment]
From

> `env: node: No such file or directory`

Looks like `node` is not in your path.

**Comment by samdark** [comment]
Doesn't seem to be Yii issue...

**Comment by handysolver** [comment]
Hi rob006. Yes it runs from the commandline.

But, probably this is not a Yii issue.

**Comment by schmunk42** [comment]
@handysolver Do you run asset conversion on the command-line or from the web-server when you get the error?

**Comment by handysolver** [comment]
Hi @schmunk42 ,
I get the error while running from the web-server only.

**Comment by rob006** [comment]
You should adjust PATH for your webserver user. See https://askubuntu.com/questions/204159/add-path-to-path-environment-variable-for-www-data

**Comment by handysolver** [comment]
Hi @rob006, you got the issue! 
I was using MAMP and in fact managed to update the PATH variable for the server by creating a file (/Applications/MAMP/Library/bin/envvars) and adding it there.

Source: https://stackoverflow.com/questions/40767857/change-path-environment-variable-in-mamp

Thank you @rob006 and @schmunk42 for the help.

Cheers!
