### ISSUE TITLE
[2.1] Move Cubrid DBMS support out of core

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#14838]
According to the [Google Trends](https://trends.google.com.ua/trends/explore?q=cubrid,mysql,postgresql,oracle%20sql,mongo) information, the Cubrid DBMS is very unpopular:

![image](https://user-images.githubusercontent.com/4499203/30518553-ea6997f6-9b89-11e7-8ee6-0423e22e8ca7.png)

If we exclude MySQL to see the bottom part detailed, the Cubrid still has zero:

![image](https://user-images.githubusercontent.com/4499203/30518559-02a116d2-9b8a-11e7-89dc-61d4ab5c01c8.png)

**Comment by tom--** [comment]
I was partly responsible for pushing for CUBRID in Yii some years ago. I planned to use it in a big project. In the end we used Maria/Galera partly for the reason that CUBRID appeared to be losing ground.

I don't understand why Google reports absolute zero. But I strongly suspect there is little overlap between Yii and CUBRID user base.

**Comment by cebe** [comment]
Their community seems to be limited to South Korea:

![bildschirmfoto von 2017-09-17 20-47-45](https://user-images.githubusercontent.com/189796/30523867-90343c0e-9be9-11e7-86e7-8790ec582edf.png)

**Comment by yyxx9988** [comment]
Other Frameworks:
- Symfony (http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/platforms.html)
  - MySQL
  - PostgreSQL
  - Oracle
  - Sqlite
  - SQL Server
  - SAP Sybase SQL Anywhere
  - Drizzle
- Laravel (https://laravel.com/docs/5.5/database)
  - MySQL
  - PostgreSQL
  - SQLite
  - SQL Server
- CakePHP (https://book.cakephp.org/3.0/en/orm/database-basics.html)
  - MySQL 5.1+
  - SQLite 3
  - PostgreSQL 8+
  - SQLServer 2008+
  - Oracle (through a community plugin)

**Comment by samdark** [comment]
Instead of moving it out of the core I'd drop it... we aren't going to support it anyway.

**Comment by klimov-paul** [comment]
CUBRID support removed: e74fbb1b0f1e83ae43672436f090393f670ebb13

**Comment by sergeymakinen** [comment]
Thanks god…

**Comment by rugabarbo** [comment]
Check related checkbox in wiki https://github.com/yiisoft/yii2/wiki/Roadmap
