### ISSUE TITLE
select sum as alias not working in ActiveRecord

### ISSUE THREAD

**Issue by hmkhafan** [yiisoft/yii2#14835]
this query is in searh model:
`$query = Acchdr::findBySql("SELECT *,
         (select  sum(accitm.debtor)  from  [accitm] where  id_acchdr=_a.id_acchdr ) as debtorSum ,
         (select  sum(accitm.creditor)  from  [accitm] where id_acchdr=_a.id_acchdr ) as creditorSum
        FROM [acchdr] _a")->all();

        echo "<pre>";
        print_r($query->debtorSum);
        exit();`
why debtorSum  and creditorSum not in $query?

**Comment by rob006** [comment]
See http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#selecting-extra-fields
