### ISSUE TITLE
Redirect consumes the flash.

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#14841]
Hi, I got problem with flash messages, but only with them that does not use the view rendering.

Methods $this->goHome() and $this->controller->redirect(['index']); cases flash removal.

### What steps will reproduce the problem?
Controller action with code:
Yii::$app->getSession()->setFlash('success', 'You are great!');
return $this->controller->redirect(['index']);

### What is the expected result?
On next view the flash will be displayed.

### What do you get instead?
Flash is not displayed at all (on any next page).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6.31
| Operating system | Windows 10

**Comment by schmunk42** [comment]
Did you make sure that there's no layout or view rendered, which might render an `Alert` widget - before you're triggering the redirect?

**Comment by mklemarczyk** [comment]
There is no additional rendering in meantime.

**Comment by samdark** [comment]
I doubt we'll be able to reproduce it without details.
