### ISSUE TITLE
Active class is missing when using Url helper in Nav widget

### ISSUE THREAD

**Issue by emedve** [yiisoft/yii2#14846]
### What steps will reproduce the problem?
I have two menu items and I am on page http://localhost/user/index:
$menu[] = ['label' => 'Users', 'url' => Url::to(['user/index'])]; // does not have class="active"
$menu[] = ['label' => 'Users', 'url' => ['user/index']]; // works fine

### What is the expected result?
I should see **li** with **class="active"** in navbar for both items, when checking in Developer Tools.

### What do you get instead?
I see **li** with **class="active"** in navbar  only for the second case.

### Additional info
The rendered **a href** values are the same ("/user/index") in both cases.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6.12
| Operating system | Windows 10

**Comment by rob006** [comment]
Are you talking about `yii\bootstrap\Nav`?

Any specific reason why you're using `Url::to()` instead just passing array with route?

**Comment by emedve** [comment]
Yes, it is yii\bootstrap\Nav - sorry not to mention that.

I thought using Url::to() would be better idea if I would prefix the project in the future. Like http://localhost/project1/... instead of current http://localhost/...

**Comment by rob006** [comment]
It will not change anything, since `Url::to()` is called internally by this widget - it will just make code slower (finally you will have two calls of `Url::to()` instead of one). 

I'm closing this since there is no valid use case for support raw URLs for detecting active items.

**Comment by emedve** [comment]
In this case it may worth to mention in the Nav's documentation, that developer should not use Url::to() when specifying url for Nav items.

**Comment by rob006** [comment]
This is explained in `isItemActive()` docs:

https://github.com/yiisoft/yii2-bootstrap/blob/2.0.6/Nav.php#L242-L251
