### ISSUE TITLE
ENH: Allow custom null message in GridView

### ISSUE THREAD

**Issue by Eseperio** [yiisoft/yii2#14842]
It could be good if "(not set)" message could be customized in gridview column via params, like "label, format".
Sometimes you need, instead `not set` something like `not loaded`, `not ready`, `pending`.
I know you can do this with a closure, but in order to keep all code clean and having in mind that `null`can be a common thing in a gridview i see it useful.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L134-L139
https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L75-L80
