### ISSUE TITLE
Console, select (with options) return key, not value.

### ISSUE THREAD

**Issue by sergey-program** [yiisoft/yii2#14840]
```
$actionName = $this->select('You want add or remove role?', ['remove' => 0, 'add' => 1]);
var_dump($actionName)
```

expected '1' or '0' (as int), but it return raw input ('add' or 'remove' as string)

In class (vendor)

```
namespace yii\helpers;

use yii\console\Markdown as ConsoleMarkdown;

/**
 * BaseConsole provides concrete implementation for [[Console]].
 *
 * Do not use BaseConsole. Use [[Console]] instead.
 *
 * @author Carsten Brandt <mail@cebe.cc>
 * @since 2.0
 */
class BaseConsole
{
//...

    public static function select($prompt, $options = [])
    {
        top:
        static::stdout("$prompt [" . implode(',', array_keys($options)) . ',?]: ');
        $input = static::stdin();
        if ($input === '?') {
            foreach ($options as $key => $value) {
                static::output(" $key - $value");
            }
            static::output(' ? - Show help');
            goto top;
        } elseif (!array_key_exists($input, $options)) {
            goto top;
        }

        return $input;
    }

//...
}
```

This function return raw stdin(), but expect "value from options array", should it?

Is this logic correct?

**Comment by TerraSkye** [comment]
U have the options inverted?

**Comment by sergey-program** [comment]
`$input = static::sdin() // string`

Function select return $input.
$options is array [key=>value]. 

So when user input stdin - it should return value from $options by key (stdin), same way as dropdown works.

In our case we output cases for select
`        static::stdout("$prompt [" . implode(',', array_keys($options)) . ',?]: ');`
and return this key, but it should return value from options array by this key.

PS: Option inverted? Maybe, but it change nothing, because function select doesn't return "value by key" it just return "key".

**Comment by samdark** [comment]
As @TerraSkye noted, you have options inverted. Worth improving docs though.

**Comment by sergey-program** [comment]
Only docs? What? Are we looking on save code? Again look what function select return and what you input. And what it shows in console.

**Comment by sergey-program** [comment]
Tell me, where in this code is return $options "value"  ?


```
    public static function select($prompt, $options = [])
    {
        top:
        static::stdout("$prompt [" . implode(',', array_keys($options)) . ',?]: ');
        $input = static::stdin();
        if ($input === '?') {
            foreach ($options as $key => $value) {
                static::output(" $key - $value");
            }
            static::output(' ? - Show help');
            goto top;
        } elseif (!array_key_exists($input, $options)) {
            goto top;
        }
        // HERE SHOULD BE SOMETHING LIKE
       // return $options[$input]; <<<-----------------------------

        return $input;
    }
```

I see that it returns only "key" that exists in $options array.

**Comment by samdark** [comment]
`static::output(" $key - $value");`

**Comment by samdark** [comment]
$key here is what's inputed and what's used. $value is what is displayed to end user by help command.

**Comment by sergey-program** [comment]
Ok, i got it. But I thought that you did it like dropdown.
