### ISSUE TITLE
Oci Shema :get defaultSchema fail （when you use masterConfig ）

### ISSUE THREAD

**Issue by lovezhl456** [yiisoft/yii2#14859]
yiisoft/yii2/db/oci/Schema.php  #52

$this->defaultSchema = strtoupper($this->db->username);

if you use master/slave  
$this->db->username is null

**Comment by cebe** [comment]
> if you use master/slave
> $this->db->username is null

can you clarify why this is the case?

**Comment by lovezhl456** [comment]
my db config
    'emulatePrepare' => true,
    'tablePrefix' => 't_',
    'class' => 'yii\db\Connection',
    'serverRetryInterval' => 1,
    'masterConfig' => [
        'dsn' => 'xxx',
        'username' => 'xxx',
        'password' => 'xxx',
    ],
    'slaveConfig' => [
      xxxx
    ],

```
//'username' => '',
//'password' => '',
```

Because I use Master/slave config   username is not set   this is allow

**Comment by cebe** [comment]
I see, it makes sense.
