### ISSUE TITLE
Yii2 offset doesn't work correctly, always prints last page

### ISSUE THREAD

**Issue by RussellSk** [yiisoft/yii2#14867]
Yii2 offset doesn't work correctly, it always prints the last page even if there are no pages left. For example, total_count = 5, and code below return 3 records it is correct.

        $pagination = new Pagination([
            'totalCount' => $movies_count,
            'defaultPageSize' => $this->items_per_page,
        ]);

        $movies_object = $movies
            ->offset($pagination->offset)
            ->limit(3)
            ->orderBy('id DESC')
            ->all();
Then when I request page = 2, the response will be 2 record, which is correct, too. But when I request page = 3, the response must be 0 records, but ActiveRecord returns always the last page (2). The question is how to force ActiveRecord to return empty values instead of last page after no data left?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.5
| PHP version      | 7.1.7
| Operating system | Debian 7

**Comment by peeto** [comment]
Inspection of the buildLimit function indicates this is a bug in the actual database. What database are you using? Should Yii2 do work to mitigate this bug (messy and performance degrading)?

**Comment by cebe** [comment]
duplicate of https://github.com/yiisoft/yii2/issues/11582 ?

**Comment by RussellSk** [comment]
@peeto Server version: 5.7.18 - MySQL Community Server (GPL)
@cebe Yes, it is the same issue, obviously duplicate of #11582.
