### ISSUE TITLE
Missing Ability to getDirectPermissionsByRole in yii\rbac\DbManager

### ISSUE THREAD

**Issue by oduncan10** [yiisoft/yii2#14866]
### What steps will reproduce the problem?
    $auth = Yii::$app->authManager;
    $perms = $auth->getPermissionsByRole($role->name); //returns inherited permissions also, need direct child permissions only
### What is the expected result?
It would be helpful for the RBAC module I'm building to have the ability to $auth->getDirectPermissionsByRole($name)
### What do you get instead?
I get all inherited permissions instead of the only the permissions assigned directly to the role through addChild().

### Additional info
Is there a better place to bring up this situation?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13-dev
| PHP version      | 7.0.10
| Operating system | Linux

**Comment by samdark** [comment]
Extending the interface would be a BC break so it's possible to extend it in 2.1.

**Comment by oduncan10** [comment]
That is encouraging, and a timely reply! Is there anything else I can provide to help clarify? I know it's pretty straight forward.

**Comment by samdark** [comment]
It's clear what's missing. You can do a pull request against 2.1 branch if you have some time.

**Comment by cebe** [comment]
> It would be helpful for the RBAC module I'm building to have the ability to $auth->getDirectPermissionsByRole($name)

isn't this `$auth->getChildren($name)`?

**Comment by samdark** [comment]
It is.
