### ISSUE TITLE
Code refresh problem ???

### ISSUE THREAD

**Issue by makcent** [yiisoft/yii2#14868]
Yii2 code refresh problem, why does not the official solve it? When the page is loaded for the first time, the authentication code is always the same. My project also uses two refresh methods to refresh the authentication code, but this is really bad for the web pages that are constantly being initialized

**Comment by makcent** [comment]
The page is loaded, the verification code content unchanged, the expected results should be the verification code with the page constantly refresh and continue to transform, to prevent attacks, if not through the verification code page when the page loads continue to refresh, then it is not the meaning of existence, isn't it?

<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
			    @@@@'template' => '{input}{image}',
			'options' => [
				'class' => 'text_input1',
				'style' => 'width:115px;'
			],
			'imageOptions' => [
				'style' => 'vertical-align: middle;',
				'alt' => '点击图片刷新验证码',
			],
		]) ?>
		``

**Comment by makcent** [comment]
The page is loaded, the verification code content unchanged, the expected results should be the verification code with the page constantly refresh and continue to transform, to prevent attacks, if not through the verification code page when the page loads continue to refresh, then it is not the meaning of existence, isn't it?

<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
			'template' => '{input}{image}',
			'options' => [
				'class' => 'text_input1',
				'style' => 'width:115px;'
			],
			'imageOptions' => [
				'style' => 'vertical-align: middle;',
				'alt' => '点击图片刷新验证码',
			],
		]) ?>
		``

**Comment by samdark** [comment]
Not enough info to reproduce it.
