### ISSUE TITLE
Disabled profiling doesn't disable the profiling for connection opening

### ISSUE THREAD

**Issue by kashukov** [yiisoft/yii2#14877]
### What steps will reproduce the problem?

Set 'enableProfiling' to false in DB config.

### What is the expected result?

Profiling is completely disabled.

### What do you get instead?

'Opening DB connection' profiling message in log.

### Additional info

Problem is in ./vendor/yiisoft/yii2/db/Connection.php, lines 578 and 581.
Yii::beginProfile($token, __METHOD__);
Yii::endProfile($token, __METHOD__);

They don't use $profile as in ./vendor/yiisoft/yii2/db/Command.php, line 913.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.9
| Operating system | Centos 7

**Comment by njasm** [comment]
something like this would be a solution for this issue?
in vendor/yiisoft/yii2/db/Connection.php
```php
        // ...
        $token = 'Opening DB connection: ' . $this->dsn;
        try {
            Yii::info($token, __METHOD__);
            $this->enableProfiling and Yii::beginProfile($token, __METHOD__);
            $this->pdo = $this->createPdoInstance();
            $this->initConnection();
            $this->enableProfiling and Yii::endProfile($token, __METHOD__);
        } catch (\PDOException $e) {
            $this->enableProfiling and Yii::endProfile($token, __METHOD__);
            throw new Exception($e->getMessage(), $e->errorInfo, (int) $e->getCode(), $e);
        }
```

**Comment by samdark** [comment]
Yes. I'd not use logical `and` side effect for condition checking. It's better to use good old `if`.

**Comment by cebe** [comment]
`enableLogging` is documented as

> whether to enable logging of database queries.

`enableProfiling` is documented as

> whether to enable profiling of database queries.

neither the profile, nor the logging of opening the db connection are database queries. Also these do not have any relevant performance impact so I do not see why we should skip these calls.

**Comment by njasm** [comment]
according to http://www.yiiframework.com/doc-2.0/guide-runtime-logging.html#performance-profiling

> Performance profiling is a special type of message logging that is used to measure the time taken by certain code blocks and find out what are the performance bottlenecks. For example, the yii\db\Command class uses performance profiling to find out the time taken by each DB query.

> To use performance profiling, first identify the code blocks that need to be profiled. Then enclose each code block like the following

yii\db\Command uses profiling to profile DB Queries but according to the link, profiling log is intended to measure code blocks; DB Queries or not.

should we always have "Opening connection ... " code block profiling logged even when we have `enableProfiling => false`?
flushing/exporting that block does not feel right to me when the configuration explicit says 'don't do it'.

**Comment by samdark** [comment]
I think changes by @njasm make total sense.
