### ISSUE TITLE
Undefined variable: _COOKIE

### ISSUE THREAD

**Issue by rottriges** [yiisoft/yii2#14871]
Hello,

we have an issue  with apache 2.4 php 7 on a win7 64bit virtual machine. (see screenshots bellow)

![fehleryii](https://user-images.githubusercontent.com/12731068/30749126-baf3c2c6-9fb2-11e7-9d89-ee5e2d1304eb.PNG)

![screenshot-2017-9-19 yii base errorexception](https://user-images.githubusercontent.com/12731068/30749132-bf4f85bc-9fb2-11e7-9846-5da9b70ff9a8.png)

In further time the whole stuff was running on a debian-linux apache server without any trouble. But due to a change of the ERP-Database from MySql to MSSQL we moved the system on a virtual win7 machine. First the system was running for a view month and than the crashes happens regulary. After reinstalling the apache server on the windows machine the system was running again for a view months but than the periodic crashes happens again.  We tried to change the settings in the /config/web.php to:
```
$config = [
    ...
    'components' => [
        'request' => [
            'enableCsrfValidation'=>false,
            'enableCookieValidation'=>false,
        ],
        ...
```
But without access. 
Sites without a user login respectevly sites which don't use the request.php have no problem.

Regards 

| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.15
| Operating system | win7 64bit

**Comment by samdark** [comment]
Seems to Apache or PHP misconfiguration.

1. Check "variables_order" in php.ini. Make sure there's "C" in the value.
2. Check that you're using right binary (not command line one).

Anyway, it can't be fixed from within Yii so closing the issue.
