### ISSUE TITLE
Parameters were not bounded SQLSTATE[HY093]

### ISSUE THREAD

**Issue by dsergey** [yiisoft/yii2#14875]
### What steps will reproduce the problem?
```
<?php
$copyFromQuery = User::find()->where(['column' => 'some value']);
$c = Yii::$app->db->createCommand()->insert(
            User::tableName(),
            $copyFromQuery
        );
$c->execute();
```

### What is the expected result?
```
/*SQL was executed
INSERT INTO `user` (`column`, `column2`...) SELECT `column`, `column2`... FROM `user` WHERE `column` = 'some value'
*/
```

### What do you get instead?
```
/*SQL was executed
INSERT INTO `user` (`column`, `column2`...) SELECT `column`, `column2`... FROM `user` WHERE `column` = :qp0
*/
```

### Additional info
Seems to me problem in \yii\db\QueryBuilder::prepareInsertSelectSubQuery it doesn't return any params after build -> vendor/yiisoft/yii2/db/QueryBuilder.php:203

P.S. Any tips to get around this problem are very welcome

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.23
| Operating system | Ubuntu 14.04

**Comment by cebe** [comment]
> INSERT INTO `user` (`column`, `column2`...) SELECT `column`, `column2`... FROM `user` WHERE `column` = :qp0

where did you get this SQL from? This is the form of the query that is sent to PDO, which is totally fine as parameters are sent separately. Is there an error message you are getting?

We have a test to verify this works: https://github.com/yiisoft/yii2/blob/ab8c54f12a8e7e29bce4cbf62334a569857aad1f/tests/framework/db/CommandTest.php#L430-L479

**Comment by dsergey** [comment]
@cebe thanks for reply.
I attach some screenshots
![image](https://user-images.githubusercontent.com/5651161/30824917-d283f832-a239-11e7-97c9-05416b482463.png)
![image](https://user-images.githubusercontent.com/5651161/30824932-dcee597a-a239-11e7-8e33-b714337358fb.png)

Interesting this behavior in 2.0.11.2. In 2.0.13 it seems to be ok.

**Comment by dsergey** [comment]
Yep. This bug in 2.0.11.2 in 2.0.12 it already fixed
https://github.com/yiisoft/yii2/blob/2.0.11.2/framework/db/QueryBuilder.php#L164 2.0.11.2
https://github.com/yiisoft/yii2/blob/2.0.12/framework/db/QueryBuilder.php#L180 2.0.12 added $params

Sorry for false start :)
Thanks.
