### ISSUE TITLE
action's controller phpdoc suggestion

### ISSUE THREAD

**Issue by and800** [yiisoft/yii2#14882]
This is a sequel to #6518.

Currently (v2.0.12) here is the type hint for `$controller` field in `\yii\base\Action`: 

```
    /**
     * @var Controller|\yii\web\Controller the controller that owns this action
     */
    public $controller;
```

So it hints for generic properties and web properties, but does not for console properties (I personally found it by my phpstorm yelling at me for `$this->controler->stdout()`).

I don't know how to fix this _wisely_. We can add every other base controller (console and rest) to the typehint, but it may seem a bit ugly. We also can create `\yii\console\Action` which will have that typehint overridden, but it also isn't perfect.

Anyway, the current state is quite inconsistent.

**Comment by samdark** [comment]
We can add console controller to the list, I guess.

**Comment by and800** [comment]
as you wish
done in #14889
