### ISSUE TITLE
NetBeans detecting error

### ISSUE THREAD

**Issue by ashunigam** [yiisoft/yii2#14881]
### What steps will reproduce the problem?
1) Install netbeans
2) install advance yii2 application
3) Create new project with existing code in netbeans for the advance application
4) you will see following error
![composererror](https://user-images.githubusercontent.com/8490472/30903131-52111c0e-a38b-11e7-8d54-39826ed23ec9.png)

### What is the expected result?
No error
### What do you get instead?
An error

### Additional info
Above error could be a false alarm from netbeans but better to get it confirmed with experts.
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by rob006** [comment]
This is only gii template, it is fine as it is. You should probably disable reporting syntax errors in `vendor` directory, you may get many false-positives like this.
