### ISSUE TITLE
Login with LDAP - yii\web\IdentityInterface error

### ISSUE THREAD

**Issue by ednotorres** [yiisoft/yii2#14886]
Hi, everybody.
I was looking for answers about how to log in with LDAP and decided create my own solution for very particular reasons.
Well, found and customized the following code:

    public function login()
    {
/*     	// config
    	$ldapserver	= '192.168.0.10';
    	$ldapuser   = $this->user;
    	$ldappass   = $this->pwd;
    	$ldaptree   = "uid=$ldapuser,ou=uo1,ou=uo2,dc=com,dc=br";
    	$pode_acessar = false;
    	// connect
    	$ldapconn = ldap_connect($ldapserver) or die("Could not connect to LDAP server.");
    	
    	if($ldapconn){
    		// binding to ldap server
    		$ldapbind = ldap_bind($ldapconn, $ldaptree, $ldappass) or die ("Error trying to bind: ".ldap_error($ldapconn));
    		// verify binding
    		if ($ldapbind) {
    			#echo "LDAP bind successful...<br /><br />";
    			 
    			$result = ldap_search($ldapconn,$ldaptree, "(cn=*)") or die ("Error in search query: ".ldap_error($ldapconn));
    			$data = ldap_get_entries($ldapconn, $result);
    			
    			$grupos = $data[0]['memberof'];
    			
    			for($i=0;$i<count($grupos)-1;$i++){
    				if($grupos[$i] == 'group,ou=ou1,ou=ou2,dc=com,dc=br'){
    					$pode_acessar = true;
    				}
    			}
    			#print_r($grupos);
    			 
    			// SHOW ALL DATA
    			#echo '<h1>Dump all data</h1><pre>';
    			#print_r($data);
    			#echo '</pre>';
    		}
    		else{
    			$pode_acessar = false;
    		}
    	}
    	return Yii::$app->User->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 
}
# PS: there's no problem with code sintax. I did cut a little of code, but that's what I really need.

### What steps will reproduce the problem?
Just login the site.

### What is the expected result?
Authenticate in the site.

### What do you get instead?
Argument 1 passed to yii\web\User::login() must implement interface yii\web\IdentityInterface, null given, called in /opt/lampp/htdocs/portal/models/base/LoginForm.php on line 127 and defined

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.12
| Operating system | Ubuntu (development),CentOS (Running App).

**Comment by theRasesh** [comment]
- [ ] 

- 

- [ ] 

- [ ] 1. - [ ] - 1. - [ ] - 1. - [ ] - 1. - [ ] [ ] - 1. - [ ] 1. - [ ] 1. - 1. 
- [ ] 2. - [ ] - 2. - [ ] - 2. - [ ] - 2. - [ ] [ ] - 2. - [ ] 2. - [ ] 2. - 2. 
- [ ] 3. - [ ] - 3. - [ ] - 3. - [ ] - 3. - [ ] [ ] - 3. - [ ] 3. - [ ] 3. - 3. - 1.
