### ISSUE TITLE
yii2 pdo error

### ISSUE THREAD

**Issue by GGNB** [yiisoft/yii2#14880]
I just run a simple select sql.
get the error like this:
##
SQLSTATE[HY000]: General error: 7011 Proxy ERROR:join check fail
The SQL being executed was: SELECT
kcu.constraint_name,
kcu.column_name,
kcu.referenced_table_name,
kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
(
kcu.constraint_catalog = rc.constraint_catalog OR
(kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
) AND
kcu.constraint_schema = rc.constraint_schema AND
kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'portal_user' AND kcu.table_name = 'portal_user'

**Comment by FabrizioCaldarelli** [comment]
What db are using?

**Comment by GGNB** [comment]
i use mysql.distributed db.

**Comment by samdark** [comment]
Version?

**Comment by GGNB** [comment]
i use tencent cloud distributed  mysql db

**Comment by samdark** [comment]
Seems to be very special MySQL flavour. Without more details we're not able to do anything about it...

**Comment by FabrizioCaldarelli** [comment]
Are you sure that it is dued to a wrong configuration?

Try to execute "SELECT * FROM  information_schema.referential_constraints" and "SELECT * FROM information_schema. key_column_usage" to see if you can reach both tables.

**Comment by jk2K** [comment]
a similar problem, maybe tencent cloud distributed mysql db does not support `infomation_schema`, the query in [mysql/Schema.php::findConstraints()](https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/Schema.php#L127) does not work

[Active Record](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html) need to read database schema information from `infomation_schema`, so the solution is to not use `Active Record`
