### ISSUE TITLE
timestamp format in mariadb

### ISSUE THREAD

**Issue by amarox** [yiisoft/yii2#14897]
### What steps will reproduce the problem?
query builder insert with column timstamp type

### What is the expected result?
Incorrect datetime value: '1506866783' for column 'created_at' at row 1
for example auth manager (dbmanager)

### What do you get instead?
for dbmanager (for example) use FROM_UNIXTIME function
```php
/**
     * @inheritdoc
     */
    protected function addItem($item)
    {
        $time = time();
        if ($item->createdAt === null) {
            $item->createdAt = $time;
        }
        if ($item->updatedAt === null) {
            $item->updatedAt = $time;
        }
        $this->db->createCommand()
            ->insert($this->itemTable, [
                'name' => $item->name,
                'type' => $item->type,
                'description' => $item->description,
                'rule_name' => $item->ruleName,
                'data' => $item->data === null ? null : serialize($item->data),
                'created_at' => new Expression("FROM_UNIXTIME('{$item->createdAt}')"),
                'updated_at' => new Expression("FROM_UNIXTIME('{$item->updatedAt}')"),
            ])->execute();

        $this->invalidateCache();

        return true;
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.9
| Operating system | debian 8

**Comment by amarox** [comment]
it`s actual only mariadb 10.2 (current version). 
Maybe fix query builder?

**Comment by samdark** [comment]
What do you want to fix in query builder exactly? You're composing your own expression in this case and it seems to fail so you need to correct the expression, right?

**Comment by amarox** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L275 this code will be fail for all users who upgraded mariadb to 10.2.
This is problem a new problem and i'm looking a solution.

**Comment by samdark** [comment]
Why should it? These columns are integers: https://github.com/yiisoft/yii2/blob/master/framework/rbac/migrations/m140506_102106_rbac_init.php#L74

**Comment by amarox** [comment]
Yes! Sorry. In my application these columns were cutomized. 
Do you mean about other timestamp columns?

**Comment by samdark** [comment]
Then I don't quite get it. You have a columns with TIMESTAMP type, right? You're using custom expression to fill it. Then how it's connected to Yii core that the expression you're using doesn't work well?
