### ISSUE TITLE
use statements should be alphabetical, spaced, organized

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2#14890]
For readability, professionalism, and continuity, the `use` statements at the top of Yii2 files (and those generated by Gii) should be alphabetical with 1 line space between them.

Example generated from Gii:

    use Yii;
    use common\models\Question;
    use common\models\QuestionSearch;
    use yii\web\Controller;
    use yii\web\NotFoundHttpException;
    use yii\filters\VerbFilter;

Yii namespaces should be first, 1 line space between the groups for readability. This will make it easier to see which yii features are currently being used, and which custom ones are already included.

---

Based off the above, here is **how it should look** (I added some more to better showcase what I mean):

    use Yii;
    
    use yii\filters\VerbFilter;
    use yii\helpers\ArrayHelper;
    use yii\helpers\Html;
    use yii\web\Controller;
    use yii\web\NotFoundHttpException;
    
    use backend\models\Something;
    
    use common\models\Question;
    use common\models\QuestionSearch;
    
    use frontend\models\SomethingElse;
    
In events where you have a model and search model (ie: Question and QuestionSearch) the search model should follow the corresponding model, regardless of alphabetical order. The search models are bound to their parent model, and an exception to the rule.

So if we had say, QuestionAnswer, it would come between Question and QuestionSearch based on the alphabetical rule. However, they should remain together.

    use common\models\Question
    use common\models\QuestionSearch
    use common\models\QuestionAnswer

---

Plan to correct over time:

+ First, the Gii generators should be updated to follow these rules. Should be done before next release is tagged.

+ Ensure apps (basic and advanced) template files conform to these rules. Since most only include Yii and are a lot more basic, this wouldn't take long to update the app templates themselves. Should be done before next release is tagged.

+ Yii2 best practices (in docs) should clearly explain the best practices to organize the use statements at the header of the files, early on (ie: not deeply hidden in the docs so nobody can find it). Should be done before next release is tagged.

+ Then top level (commonly used) Yii2 files (Html, ArrayHelper, etc). I understand there are a lot of files, which is why I propose starting with the most commonly used files, and working down the levels. This is WIP and would be scheduled for a later release.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.*
| PHP version      | Any
| Operating system | Any

**Comment by samdark** [comment]
Your ordering is not alphabetical.

**Comment by WadeShuler** [comment]
It is alphabetical

    use Yii;
    
    use yii\filters\VerbFilter;
    use yii\helpers\ArrayHelper;
    use yii\helpers\Html;
    use yii\web\Controller;
    use yii\web\NotFoundHttpException;
    
    use backend\models\Something;
    
    use common\models\Question;
    use common\models\QuestionSearch;
    
    use frontend\models\SomethingElse;

2 exceptions: the Yii namespace comes first. Search models are attached to their corresponding model. 

It makes it so much easier to see what is already brought into the file. Is FileHelper already there? You can easily find it by going to the yii block. When you have 20 of them in a large controller, it makes life so much easier.

**Comment by samdark** [comment]
That's your personal organising preference that works for you. IDEs can't sort in such way automatically. Doing it manually is a time eater. Automatic formatting will screw all your manual formatting in no time.
