### ISSUE TITLE
Yii2 controller and dash

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [yiisoft/yii2#14903]
this bug has occurred when i use a controller with dash.

```php
class SiteController extends yii\web\Controller{
    function actionIndex(){
        return $this->render('index');
    }
}
```

goto http://example.com/web/site-
or
goto http://example.com/web/site------

error
The view file does not exist: ....\views\site-\index.php
or
The view file does not exist: ....\views\site------\index.php

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12

**Comment by samdark** [comment]
Verified. Controller is executed while it should not.
