### ISSUE TITLE
Make more clear a note regarding safeUp and safeDown in database migrations guide

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#14910]
The following note:

> Note: Not all DBMS support transactions. And some DB queries cannot be put into a transaction. For some examples,
  please refer to [implicit commit](http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html). If this is the case,
  you should still implement `up()` and `down()`, instead.

For me it is not clear whether I can, I should or I must use up() and down() in those cases, or if I can always use safeUp and safeDown and let the underlying db engine manage it.

**Comment by samdark** [comment]
Depends on if you rely on transactions or not. In general, it's safe to use `safe*` variants.

**Comment by rob006** [comment]
I think that last sentence should be removed. You can always use `safeUp()` and `safeDown()` methods, in worst case they will work as `up()` and `down()`.

**Comment by schmunk42** [comment]
I think this is very MySQL specific, since it does not support rollback for schema changes, which are mostly used in migrations.

Effectively, you can use `safeUp()` and `safeDown()` as intended only when you're just using `insert`, `update` or `delete` within them.

We are usually splitting schema and data migrations because of that.

Related: https://wiki.postgresql.org/wiki/Transactional_DDL_in_PostgreSQL:_A_Competitive_Analysis

**Comment by samdark** [comment]
It mostly is, correct.

**Comment by santilin** [comment]
The problematic sentence is this:
<code>
If this is the case, you should still implement up() and down(), instead.
</code>

The word still makes me think I have to implement both safeUp and safeDown besides up and down, while the word instead at the end makes me think of implementing just up and down. I thik you have to remove the "still" word. 

Moreover, I find the link  https://wiki.postgresql.org/wiki/Transactional_DDL_in_PostgreSQL:_A_Competitive_Analysis more informative than the other one, which is mysql specific.

**Comment by samdark** [comment]
Yes. That sentence is gone https://github.com/yiisoft/yii2/commit/1f24fd35b99d5b95b54e21ce4b5754ba7a7492ce
