### ISSUE TITLE
What is wrong with name of Cookie on getting?

### ISSUE THREAD

**Issue by papalapa** [yiisoft/yii2#14919]
### What steps will reproduce the problem?
In controller I have sent cookies like this:
`Yii::$app->response->cookies->add(new yii\web\Cookie(['name' => 'user.name', 'value' => 'Jack Black']));`
and
`Yii::$app->response->cookies->add(new yii\web\Cookie(['name' => 'user-login', 'value' => 'jack']));`

Then to get cookies in view I use code like this:
`Yii::$app->request->cookies->getValue('user.name');`
and
`Yii::$app->request->cookies->getValue('user-login');`

### What is the expected result?
I waiting for `'Jack Black'` and `'jack'`.

### What do you get instead?
I receive a `NULL` value and `'jack'`.

**Why dot symbol is not allowed in cookie on getting?**

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.4
| Operating system | Ubuntu

**Comment by samdark** [comment]
What do you have in $_COOKIES?

**Comment by dmirogin** [comment]
Cause this
`Yii::$app->response->cookies->add(new yii\web\Cookie(['name' => 'user.name', 'value' => 'Jack Black']));`
sets cookie to response. Nothing more.

**Comment by dmirogin** [comment]
And you read cookies from request.
Request cookies and response cookies are different cookie bags.

**Comment by samdark** [comment]
@dmirogin I think he actually means reading cookie in a view in the next request, not the same one. Am I right, @papalapa?

**Comment by papalapa** [comment]
@dmirogin, @samdark is right about setting and getting cookies.
The browser cookies after this manipulations has both variables: user.name and user-login, but on getting  values I have this:
var_dump(Yii::$app->request->cookies->getValue('user-login')); // jack
var_dump(Yii::$app->request->cookies->getValue('user.name')); // NULL

I think problem is in «.» symbol in cookie variable name.

**Comment by samdark** [comment]
Yes https://harrybailey.com/2009/04/dots-arent-allowed-in-php-cookie-names/

**Comment by samdark** [comment]
Not sure we should handle it.

**Comment by papalapa** [comment]
Oh, it is deeper than seems. I have never thinking about global variable names. Thank you @samdark.

**Comment by samdark** [comment]
Either we should convert dots to underscores behind the scenes or throw an exception for cookies with dots in their names.

**Comment by papalapa** [comment]
I think throwing an exception will be a better way to handle it.

**Comment by samdark** [comment]
Yes. Agree.

**Comment by klimov-paul** [comment]
> I think throwing an exception will be a better way to handle it.

Disagreed. There are many symbols, which are not allowed in the Cookie name: spaces `=`, `;` and so on. Should we check them too?

Besides PHP does not put any restriction on setting cookie with dot in the name. The only problem is that appears in `$_COOKIE` with dots been replaced by underscore.
Also this behavior may be fixed in the future PHP versions as 'register_globals' directive has been removed long ago.

I do not think any actions should be performed.

**Comment by samdark** [comment]
Makes sense.
