### ISSUE TITLE
Improvements when switching to linked assets in development

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#14913]
Continued from https://github.com/yiisoft/yii2/pull/14905#issuecomment-334139197

### What steps will reproduce the problem?

(during development)
- publish assets with `linkAssets = false`
- publish assets with `linkAssets = true`
- update source files

### What is the expected result?

- changed assets, since they should be linked

### What do you get instead?

- old published (copied) assets from first request

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x

From the thread linked above...

> I don't think that we should care about this. If you change component settings, you should also clear its cache.

So this should either be noted [in the guide](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#asset-publishing) or we also take `linkAssets` into account when generating the hash.

**Comment by samdark** [comment]
I think mentioning it in the guide should be fine. Extra checks would potentially slow down production environments.

**Comment by schmunk42** [comment]
I thought of changing https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L607 to something like

    return sprintf('%x', crc32($path . Yii::getVersion() . '|' . $this->linkAssets));

It not really an additional check, your hash paths would just change when switching the setting.

**Comment by samdark** [comment]
That sounds good. I'd not use pipe for a hash though.

**Comment by schmunk42** [comment]
The pipe is just for separating the string which is to be hash correctly. So

    /path/to/asset2.0.10

does not get confused with

    /path/to/asset2.0.11

I'd be fine with any other char, which does not occur in version.

**Comment by samdark** [comment]
Sorry, the pipe is fine. I've thought it's added to the hash itself but it's actually being fed to crc32.

**Comment by ogheo** [comment]
Hello,

I have some troubles after updating to 2.0.13 related to these modifications.

I'm using advanced app in which I have theme folder with some js & images:

frontend/themes/assets/images/favicon.ico
frontend/themes/default/assets/js/html5shiv.min.js
frontend/themes/default/assets/js/respond.min.js

in layout i get them as following:

    <link href="<?= Yii::$app->assetManager->getPublishedUrl('@frontend/themes/default/assets/') ?>/images/favicon.ico" rel="shortcut icon" type="image/x-icon">
    

If 'linkAssets' => true then those files cannot be accessed by generated url (404 not found).

**Comment by schmunk42** [comment]
How are these changes related to your issues, they "just" hash another string.

Does it work when you manually revert those changes?
Which system are you on?

**Comment by ogheo** [comment]
> How are these changes related to your issues, they "just" hash another string.

The problem is that generated url links to a folder/symlink that doesn't exist (with 'linkAssets' => true).

> Does it work when you manually revert those changes?

Yes, it works if I revert code manually to 2.0.12, it works also when 'linkAssets' => false.

> Which system are you on?

ubuntu 14.04 lts

**Comment by schmunk42** [comment]
Do you also publish the assets beforehard, according to the [docs](http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#getPublishedUrl()-detail), there is no publishing made by calling `getPublishedUrl()`.

Did you switch the setting from time to time? I am asking because I'd like to know if things "went right" for you, due to https://github.com/yiisoft/yii2/pull/14905#issuecomment-334139197

**Comment by ogheo** [comment]
> Do you also publish the assets beforehard, according to the docs, there is no publishing made by calling getPublishedUrl().

Yes, I publish assets before with command: php yii asset/compress frontend/assets/compress/config.php frontend/assets/compress/assets-prod.php

> Did you switch the setting from time to time? I am asking because I'd like to know if things "went right" for you, due to #14905 (comment)

No, I didn't switched settings since option linkAssets => true was added. 

(not sure about what is #14905, I'll take a look later)

**Comment by ogheo** [comment]
> https://github.com/yiisoft/yii2/pull/14905#issuecomment-334142493

even if we switch  linkAssets from false to true and republish them, images & js are published under a folder and work only if linkAssets are changed to false.

**Comment by schmunk42** [comment]
> `php yii asset/compress frontend/assets/compress/config.php frontend/assets/compress/assets-prod.php`

@samdark Is this equivalent to `assetManager->publish()` for compressed assets?

**Comment by samdark** [comment]
Let's continue in #15121
