### ISSUE TITLE
asset/compress needs semicolon-less JavaScripts support

### ISSUE THREAD

**Issue by tanakahisateru** [yiisoft/yii2#14929]
New released yii-pjax 2.0.7 breaks my compressed JavaScript which generated by `asset/compress` command. JS files are joined with no separators after `jquery.pjax.js`.

### What steps will reproduce the problem?
Create an Yii project, then simply use `yii asset/compress`.

### What is the expected result?
At least a semicolon should be inserted. I prefer wrapping each scripts by `function(){ ... }();`.

### What do you get instead?
<img width="457" alt="no-semicolon" src="https://user-images.githubusercontent.com/403893/31228378-48c84896-aa18-11e7-9ae5-02cc0516354e.png">

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.15, 7.1.8
| Operating system |Ubuntu, MacOS

**Comment by tanakahisateru** [comment]
I like semicolon but certain semicolon haters who can lead trends really exist -- GitHub, Twitter Bootstrap, Vue.js ...

**Comment by rob006** [comment]
Wrapping with `(function(){ ... })();` will change code behavior - some scripts are intended to work in global scope.

**Comment by tanakahisateru** [comment]
@rob006 right! I will change my PR.

**Comment by samdark** [comment]
Isn't https://github.com/yiisoft/jquery-pjax/commit/0d4cc3f479d4b7b800aefca1275a852c8d3dd3c6 fixing the problem?

**Comment by rob006** [comment]
@samdark It will fix it for pjax, but any other library can have similar issues. Compressing asset should not depend on trailing semicolon.

**Comment by samdark** [comment]
Right. Makes sense to fix that. Would checking for trailing semicolon when concatenating files and adding it if it's not there do?

**Comment by schmunk42** [comment]
Sorry for being late to the party...

@samdark The semicolon does not hurt, but shouldn't a simple *new-line* be OK for this? 
It's JavaScript 😏  http://www.bradoncode.com/blog/2015/08/26/javascript-semi-colon-insertion/

@tanakahisateru I wonder why the comments are not visible in the screenshot above. Is the source from concatenating the files with Yii or is there another tool involved?

**Comment by samdark** [comment]
@schmunk42 I can't think of a case where it won't work as expected...

**Comment by schmunk42** [comment]
Yes, after some more research, it looks like this is the right thing to do.

- https://github.com/webpack/webpack/pull/3209/files
- https://stackoverflow.com/questions/1873983/what-does-the-leading-semicolon-in-javascript-libraries-do
- https://stackoverflow.com/a/7365214/291573
- https://stackoverflow.com/questions/20253392/add-break-line-between-files-grunt-concat
- https://github.com/github/fetch/issues/420

**Comment by tanakahisateru** [comment]
@samdark Can you reopen this issue? I found the case for trailing line comment, e.g:

```js
(function($) {
})(jQuery) // trailing line comment 👻
```
... will combined and compressed with the next file as:

```js
/*** BEGIN FILE: 1st.js ***/
(function($) {
})(jQuery) // Trailing line comment 👻;
/*** END FILE: 1st.js  ***/
/*** BEGIN FILE: 2nd.js ***/
(function($) {
})(jQuery)
/*** END FILE: 2nd.js  ***/
```
  ↓
```console
$ node_modules/.bin/uglifyjs conbined.js 
(function($){})(jQuery)(function($){})(jQuery);
```

**Comment by samdark** [comment]
Would you please create a pull request? Thanks.
