### ISSUE TITLE
Url::current([10=>null]) not removing numeric key

### ISSUE THREAD

**Issue by mhoogstraten** [yiisoft/yii2#14921]
### What steps will reproduce the problem?
URL: http://127.0.0.1/yii2/?10=1

Now remove the 10 key:
\yii\helpers\Url::current([10=>null])

this also happens in case of replacing an array:
\yii\helpers\Url::current(['es'=>[]])

### What is the expected result?
URL: http://127.0.0.1/yii2/?

### What do you get instead?
URL: http://127.0.0.1/yii2/?10=1

### Additional info
Config:
`
'components' => [
..
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'suffix' => '/',
            ..
        ],
..
],
`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.4
| Operating system | WIN

**Comment by rob006** [comment]
PR with fix: #14940

**Comment by posterx** [comment]
Now if you want to unset only one nested get param like this Url::current([$model->formName() => ['status_id' => null]]) it will remove all params that were in $_GET under $model->formName()
May be it will be better to use array_replace_recursive instead of array_replace?

**Comment by samdark** [comment]
Please create a separate issue. Comments on closed issues would be lost for sure.
