### ISSUE TITLE
Gridview buttons "POST" act as "GET" after latest "jquery.pjax.js" composer update

### ISSUE THREAD

**Issue by letsjump** [yiisoft/yii2#14926]
Yesterday, after the latest  `jquery.pjax.js` update by composer (from version 2.0.6 to 2.0.7) it seems that by clicking on a `\yii\grid\ActionColumn` button of a `yii\grid\GridView`, it act as a pjax GET request also if button/link `data-method` attribute is set as POST.
So, every "delete" button, whose request needs to be "POST" by default _yii2 controller behaviour_, results as a 
> "Method Not Allowed (#405) Method Not Allowed. This url can only handle the following request methods: POST"

Gridview button html source is:
```html
<a class="btn btn-default" href="/sale/delete/167" data-pjax="1" data-method="post">
    <span class="glyphicon glyphicon-trash"></span>
</a>
```
| Q                 | A
| ----------------- | ---
| Yii2 version      |2.0.12
| PHP version       | 7.1.10-1+ubuntu16.04.1+deb.sury.org+1
| browser | Firefox 56.0
| jquery.pjax.js | 2.0.7

**Comment by SilverFire** [comment]
Reproduced, will be fixed
