### ISSUE TITLE
add yii\db\SchemaBuilderTrait::foreignKey() to create the left hand side of a foreign key

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#14922]
This is a required feature to solve the problem of declaring a foreign key on a table to a primary key on another when the types of them differ.

For example:

'''
TableA:  id => integer(10) unsigned primary key autoincrement

Table B: tablea_id =>integer(11)

As the declaration of both fields is not equivalent (one is unsigned and the oher is not), mysql complains that it can not create a foreign key. If I define all my left hand fields of foreign keys via a function, I am sure I'll never get that error.

**Comment by rob006** [comment]
`primaryKey()` should create `int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY` which is compatible with `int(11)` FK.

**Comment by santilin** [comment]
@rob006 The problem is when you are creating a foreign key to a table which defines a primarykey like this:

```
		$this->createTable('tableA', [
			'id' => $this->primaryKey(),
```

and then want to create a foreignkey in another table to reference this table:

```
        $this->createTable('tableB', [
            'id' => $this->primaryKey(),
            'tablea_id' => $this->integer(),
```
As you can't see in the migration for creating table a what is the type, signedess and width of the primary key, you might create an erroneous reference to that id and the DBMS will complain ruining your migration. As these migrations can't be into a transaction on some DBMS, usually you end up with a broken database.

**Comment by rob006** [comment]
Are you want to say that you don't known that your PK is integer?

**Comment by santilin** [comment]
Not that it is not integer, but maybe I am creating a foreign key to a table in a different module or extension and I don't know if they have created their primary keys unsigned or signed, or, in the worst of cases, I create a migration years after and I forget the signedness of the primary keys.

**Comment by rob006** [comment]
So you want to dynamically guess type in `foreignKey()` based on current DB schema? How this should work?

**Comment by santilin** [comment]
No, sorry, maybe I am not explaining this clearly. I want a function that defines a field with the same type, signedness and width that primaryKey() does, so that I dont have to guess what kind of field primaryKey() generates to match my foreign key field.

**Comment by rob006** [comment]
You already have it - it is `integer()`.
