### ISSUE TITLE
Primary keys should be created unsigned in migrations using SchemaBuilderTrait::primaryKey()

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#14928]
### What steps will reproduce the problem?

Create a migration like this:

```
		$this->createTable('tableA', [
			'id' => $this->primaryKey(),
```

### What is the expected result?

The generated table should have id defined as an unsigned integer, as discussed here:

https://stackoverflow.com/questions/26289707/should-mysqls-primary-key-be-just-integer-or-should-it-be-unsigned-integer-of

### What do you get instead?

A signed integer column.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      | any
| Operating system | any

**Comment by rob006** [comment]
Duplicates #1032.
