### ISSUE TITLE
EmailValidator declares "ex..ample@example.com" as valid

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#14933]
As the SwiftMailer can not use an address with a double dot it would reasonable to disallow an email with that. The EmailValidator should disallow it. Not sure if such an email is correct at all, but when the SwiftMailer cannot handle this, the validator should reflect it.

**Comment by rob006** [comment]
https://github.com/swiftmailer/swiftmailer/issues/239#issuecomment-8374162

**Comment by samdark** [comment]
Sounds reasonable to adjust our email validator.

**Comment by robsch** [comment]
Tried the pattern [here](https://regexr.com/3gtd0) and it actually works as it should work. So is it just a browser issue?

**Comment by rob006** [comment]
I added tests that verifies that EmailValidator works fine: #14935
