### ISSUE TITLE
namespace yii\db\ BaseActiveRecord:: populateRecord() about set priority 

### ISSUE THREAD

**Issue by murat-celik** [yiisoft/yii2#14939]
https://github.com/yiisoft/yii2/blob/f5591bb70eb9f4622ffa8b435e7d88543bcdb44a/framework/db/BaseActiveRecord.php#L1154

When i defined my property same column in database table "DetailView" not working,
Because "DetailView" read value from class property

![populate_record](https://user-images.githubusercontent.com/10754763/31307417-e2791d08-ab6c-11e7-8d64-11c0b1066609.png)

**Comment by murat-celik** [comment]
@samdark @klimov-paul @cebe

**Comment by dmirogin** [comment]
If class has public property it will not fire __get() method

**Comment by rob006** [comment]
You should not use the same name for class property and attribute. 
See #3627, http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#accessing-data

**Comment by murat-celik** [comment]
https://github.com/yiisoft/yii/blob/4e875b5e7312a246ede66858ed3180c33a8574c2/framework/db/ar/CActiveRecord.php#L1856

Yii 1.xx firstly set class property, which is the best practise @rob006

**Comment by rob006** [comment]
But why do you need property with the same name as attribute?

**Comment by murat-celik** [comment]
@rob006 i write a EntityManagerComponent for Yii 1.x.x  this read class properties with ReflectionClass and parse property comment and create new colon for my database table.
So easy update my database without migrations.

And i try write same Component for yii2 but i have problem when populate Record my models

https://github.com/murat-celik/YiiCodeFirstORM

**Comment by rob006** [comment]
Using property will most likely break dirty attributes feature. You may try to override `populateRecord()` or use events to set property, but this may be risky.
