### ISSUE TITLE
interface for yii\db\Expression

### ISSUE THREAD

**Issue by zuozp8** [yiisoft/yii2#14936]
I would like to make my active records and querying simpler when using custom-typed fields.

I propose making `yii\db\Expression` implement `yii\db\ExpressionInterface` with following definition:
```php
/**
 * @property string $expression
 * @property array $params
 */
interface yii\db\ExpressionInterface {}
```
and changing all `… instanceof \yii\db\Expression` into `… instanceof \yii\db\ExpressionInterface`

Change would be fully backward-compatybile.

### Example:
Assume I have field of type datetime in db want to have property of type `MyDateTime`. Currently I need to have behavior that performs casting between `string` ⇄ `MyDateTime` on afterFind, before/afterInsert, before/afterUpdate. There is also a lot of potential problems when calculating dirtyAttributes then.

After proposed change I would only need to make sure that `ColumnSchema` used in `ActiveRecord::populateRecord` casts the proper fields field to `MyDateTime`. Additionally i would be able to do things like `$query->andWhere(['created_at' => new MyDateTime])`

This has many uses in databases with rich types, like postgres having arrays, geometries, custom types.

**Comment by rob006** [comment]
See #14836
