### ISSUE TITLE
Undocumented use of {{tablename}} in migrations

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#14944]
I have seen in dektrium/user module:   https://github.com/dektrium/yii2-user/blob/master/migrations/m140209_132017_init.php  that some migrations use a pair of curly brackets to enclose the tablename, but I have not found any place at the documentation where this is documented.

**Comment by schmunk42** [comment]
see http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#setting-a-table-name

**Comment by santilin** [comment]
I see. The problem is that reading the docs about migrations, you can not guess that they use ActiveRecord to create the table, so you don't notice that you can use {{ }} to honor your table prefix. I thing it would be very useful to mention that in the docs. @schmunk42

**Comment by cebe** [comment]
its not tied to active record: http://www.yiiframework.com/doc-2.0/guide-db-dao.html#quoting-table-and-column-names
