### ISSUE TITLE
session lost

### ISSUE THREAD

**Issue by freeng** [yiisoft/yii2#14949]
### What steps will reproduce the problem?
1.when php.ini session.auto_start on,session_name() will not work well,when do get or set session,the php.ini session.name will be use.
2.then use  session_regenerate_id()(ex switchIdentity()),new session name will be work.follow session value will set to the new session name;
3.but the new request still with the problem 1,so session value lost.
### What is the expected result?
the base problem is 1.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.1.10
| Operating system | w10

**Comment by keangkai** [comment]
try use Yii::app()->user->setState("key", "value")

**Comment by cebe** [comment]
> try use Yii::app()->user->setState("key", "value")

this is Yii 2, not Yii 1 :)
