### ISSUE TITLE
Session Not working after redirect

### ISSUE THREAD

**Issue by rahulmishra1991** [yiisoft/yii2#14947]
### What steps will reproduce the problem?

In the Conroller:
 Yii::$app->session->setFlash('success', 'Please check the verification mail For account activation');
                return $this->redirect(['/site/login']);

In the login view file
<?php if (Yii::$app->session->hasFlash('success')): ?>
    <div class="alert alert-success alert-dismissable">
    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
    <?= Yii::$app->session->getFlash('success') ?>
    </div>
<?php endif; ?>
### What is the expected result?

Message should be print "Please check the verification mail For account activation".

### What do you get instead?

Session not working so just blank.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 5.6
| Operating system |

**Comment by keangkai** [comment]
I think try if wrong am sorry
Yii::$app->session->setFlash(['success', 'Please check the verification mail For account activation']);
return $this->redirect(['/site/login']);

**Comment by SilverFire** [comment]
Most probably you have code that gets flashes earlier than redirect occurs.
