### ISSUE TITLE
asDecimal() return wrong results

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#14950]
Different results return from `intl` and  `number_format()`

### What steps will reproduce the problem?

Yii::$app->formatter->asDecimal('18446744073709551615');

### What is the expected result?

When i have used php function `number_format()` that time return below output. so i think is a expected or not ?.  not confirm

Results : 18,446,744,073,709,551,616

### What do you get instead?
// convert using `intl`
Results :  18,446,744,073,709,600,000

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by SilverFire** [comment]
Verified

**Comment by zhukovra** [comment]
@SilverFire @samdark would not be `asDecimal` completely rewritten without using native functions like `number_format()` and `intl` extension?

**Test**

    $value = '123456789012345678901234567890';
    $this->assertSame('123,456,789,012,345,678,901,234,567,890', $this->formatter->asDecimal($value, 0));

**Output**

    Failed asserting that two strings are identical.
    Expected :123,456,789,012,345,678,901,234,567,890
    Actual   :123,456,789,012,345,677,877,719,597,056

PHP internal casting big integers to float leads to badly mistaken result.

**Comment by samdark** [comment]
Probably a good idea.
