### ISSUE TITLE
OPTIONS method error with custom Action.

### ISSUE THREAD

**Issue by ejoo** [yiisoft/yii2#14962]
I've Yii2 app in localhost and react app in localhost:3000 and I'm trying to send Login request from a React app and I get the following error:

> OPTIONS http://localhost/booking/api/web/v1/user/login 405 (Method Not Allowed)

    `public function behaviors()
      {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::className(),
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
                'Access-Control-Request-Headers' => ['*'],
                'Access-Control-Allow-Credentials' => true,
                'Access-Control-Max-Age' => 86400,
            ],
        ];
        
        $behaviors['verbs'] = [
            'class' => \yii\filters\VerbFilter::className(),
            'actions' => [
                //'index'  => ['get'],
                'login' => ['post'],
            ],
        ];

        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'only' => ['dashboard', 'index', 'create', 'update', 'delete', 'logout'],
            'except' => ['options', 'login'],
        ];
        
        return $behaviors;
    }
`

**Comment by samdark** [comment]
```php
 $behaviors['verbs'] = [
        'class' => \yii\filters\VerbFilter::className(),
        'actions' => [
            //'index'  => ['get'],
            'login' => ['post'], // <--------- this
        ],
    ];
```
