### ISSUE TITLE
yii2 batch insert with utf-8 encoding

### ISSUE THREAD

**Issue by hmkhafan** [yiisoft/yii2#14961]
i want to save multi record in database that has persian characters. i try this:

`
$actionArray = [
        [1,'تست1'],
        [2,'تست2'],
        [3,'تست3'],
        [4,'تست4'],
        [5,'تست5'],           
    ];

    \Yii::$app->db->createCommand()->batchInsert("acc_actions",['act_id','act_name'],$actionArray)->execute();`

but when it runs will save '????1' in table! is there any way to pass utf-8 to batch insert or i must insert one by one into table?
i'm using sql server 2014

**Comment by samdark** [comment]
I don't think it's batch insert itself to blame. It's something about encodings and I don't think we're touching anything about these from within Yii so check your server settings.
