### ISSUE TITLE
Make MSSQL and Oracle tests run on Travis

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#14971]
See https://github.com/yiisoft/yii2-httpclient/issues/126

According to the specified criteria any functionality, which has no proof to be running via Travis build can not be declared as supported one.

Thus either unit tests for MSSQL and Oracle should be made running on Travis or related libraries should be removed along with the docs mentioning there is a support for MSSQL and Oracle.

**Comment by rob006** [comment]
If you have spare time for unit test fix - open a PR for it.

**Comment by klimov-paul** [comment]
Sorry, I do not have any spare time - you should handle this on your own.

**Comment by samdark** [comment]
It was worked on and I agree that we should finish it. We're running [gitlab CI](https://gitlab.com/yiisoft/yii2/pipelines) and there are containers prepared for MSSQL and Oracle. We need to ensure these are executed on a regular basis.

**Comment by samdark** [comment]
@rob006 this one is rather complicated. @schmunk42 has details.

**Comment by schmunk42** [comment]
Sorry, I missed this conversation. Did anyone see a MSSQL test setup on Travis?

See also https://github.com/yiisoft/yii2/pull/15485#issuecomment-356760976 - MSSQL needs 3,5 GB of **free** RAM, on GitLab I had to create a custom runner with ~5 GB RAM to make them work.

**Comment by samdark** [comment]
MSSQL part done. Thanks, @darkdef!
