### ISSUE TITLE
FR: Introduce `FallbackUrlRule` for `UrlManager`

### ISSUE THREAD

**Issue by rob006** [yiisoft/yii2#14974]
### What steps will reproduce the problem?

Right now `UrlManager` have some fallbacks if none of rules match current request/route:

Creating URL:
https://github.com/yiisoft/yii2/blob/0199325c813526afaed464248f9d0785781f90b5/framework/web/UrlManager.php#L412-L420

Parsing request:
https://github.com/yiisoft/yii2/blob/0199325c813526afaed464248f9d0785781f90b5/framework/web/UrlManager.php#L283-L323

This not only breaks SRP and creates weird bugs for such fallbacks (#10739), but also may decrease performance: such fallback can never be cached by per-request cache (`UrlManager::getUrlFromCache()`) - `UrlManager` needs to iterate trough all rules before creating URL in format "/module/controller/action";

### Solution

Introduce `FallbackUrlRule` which will handle these fallbacks. It will be always appended to rules array, so it results of URL creation can be cached. This will make `UrlManager` simpler and performance of `createUrl()` should be improved.

**Comment by samdark** [comment]
Sounds interesting to me. Worth trying.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
