### ISSUE TITLE
Catch all application events

### ISSUE THREAD

**Issue by macklus** [yiisoft/yii2#14978]
I not sure if this is now possible, or maybe be implement nearly.

I need to catch all application events (Yii2 based and own emits). Its that possible?
Logic should be define a function who can catch all Application events, maybe like:

```
'on' => function($event) {
        
},
```

**Comment by samdark** [comment]
No, it's not possible.

**Comment by macklus** [comment]
is a design question ? tech limitation ? or maybe i ask something stupid ?

Is there any way i can implement that by develop a plugin o similar ? Please, let me know some points of entry to test that.

thanks in advance.

**Comment by samdark** [comment]
Events aren't handled in a centralized way, they could be attached to any descendant of the `Component`. You can collect all events from a concrete component but you'll need to determine and inspect all components in order to get a full set.

**Comment by macklus** [comment]
Just for info, how can i get all events for a component ?

thanks

**Comment by samdark** [comment]
Seems you can't except to query for particular event name... That could be improved.

**Comment by SamMousa** [comment]
Related to: https://github.com/yiisoft/yii2/issues/14349

The event implementation in Yii suffers from tight coupling, hardcoded invocation of static methods make it hard to change behavior.

**Comment by macklus** [comment]
Plus, just for add two use-case. I work on complex Yii project, and use lot of Events. After try-and-fail-and-try again one problem for hours, i find it was an event problem related.

I think is really ussefull (for me it is) get a debug bar plugin who shows the events and who it whould be fired, but i need to catch all events on that.

Second case, on a old project, previous developer use events, but there is no related docs on that. If i can catch all of them, i can prevent some mistakes, and get a point to work on.

**Comment by Eseperio** [comment]
A simple solution could be add a `Yii::info` In Component::trigger with message `Event triggered: {$name}

**Comment by macklus** [comment]
> Events aren't handled in a centralized way, they could be attached to any descendant of the Component. You can collect all events from a concrete component but you'll need to determine and inspect all components in order to get a full set.

@samdark , should at least possible get al events triggers with Yii::$app->trigger ?

**Comment by klimov-paul** [comment]
Obvious solution will be introducation of the event wildcard binding, which was proposed at #3250 and rejected.

**Comment by SamMousa** [comment]
The arguments give there don't specifically hold for prefix matches though; prefix matches can be done efficiently and is theoretically more efficient than registering multiple events.
Of the top of my head a simple, ugly implementation would be to register events in a deep array by splitting the keys to individual characters...

**Comment by samdark** [comment]
Radix tree could be a good structure for it.
