### ISSUE TITLE
Base phpunit classes should be extracted to yii2-phpunit package

### ISSUE THREAD

**Issue by rob006** [yiisoft/yii2#14973]
### What steps will reproduce the problem?

We have a compatibility layer for phpunit: https://github.com/yiisoft/yii2/blob/master/tests/compatibility.php

This code was copied between many (all?) of yii2 official extensions. But this code relies on assumption, that phpunit 4 does not have `PHPUnit\Framework\TestCase` class. This was changed in phpunit 4.8.35: https://github.com/sebastianbergmann/phpunit/commit/a55235c033c2dc18db631cc6b804844f6d37615a
So now some tests does not work on phpunit 4.8.35 or 4.8.36 and you need to fix it in every extension. Obviously this is a monkey job and nobody wants to do it. So we have some lazy/temporary workarounds:
* Lock phpunit to 4.8.34: https://github.com/yiisoft/yii2/commit/758f01934f180b4a4a47d36e1be103b1f979d76b#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L84
* Just disable tests on PHP 5.4, which requires phpunit 4: https://github.com/yiisoft/yii2-httpclient/commit/e61daa63eca37f21daca1f9f79888ffa3ba5836d

### What is the expected result?

DRY. There should be one package with phpunit-related classes. All potential improvements or fixes should be done there, not in each package separately.

**Comment by samdark** [comment]
Agree. https://github.com/yiisoft/yii2-phpunit

**Comment by samdark** [comment]
Not going to do it for 2.0.
