### ISSUE TITLE
Call to a member function getUniqueId() on null

### ISSUE THREAD

**Issue by adummy832** [yiisoft/yii2#14979]
I have this controller in which does have a private property on it, that will be shared with 2 different methods to create the model in the form. I have this weird thing going on. Need some help.

    <?php
    namespace app\controllers;

    use app\models\User;

    class OfficialController extends \yii\web\Controller
    {

        private $user;
        public function __construct()
        {
            $this->user = new User();

            var_dump($this->user);  # Catch it from here but when i remove var_dump() & die(), it breaks.
            die();
        }

        public function actionIndex()
        {
            return $this->render('index', [
                'model' => $this->user  # Shared Model => form
            ]);
        }

        public function actionReview()
        {
            return $this->render('review', [
                'model' => $this->user  # Shared Model => form
            ]);
        }

    }

**Comment by gevorgmansuryan** [comment]
You need to use `beforeAction` or just some getter method for this property

**Comment by adummy832** [comment]
Sir, can you show me how to properly implement this, been struggling on this for hours. Thank you very much.

**Comment by gevorgmansuryan** [comment]
```php
public function beforeAction($action)
    {
        if ($id = Yii::$app->request->get('id')) {
            $this->user = User::findOne($id);
        } else {
            $this->user = new User();
        }
        return parent::beforeAction($action);
    }
```
or much better

```php
public function actionIndex($id)
    {
        return $this->render('index', [
            'model' => $this->findModel($id)
        ]);
    }

    public function actionReview($id)
    {
        return $this->render('review', [
            'model' => $this->findModel($id)
        ]);
    }

    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
```

**Comment by ptz-nerf** [comment]
Are you sure problem with User?
You incorrectly overrides yii\web\Controller::__construct(). 
http://www.yiiframework.com/doc-2.0/yii-base-controller.html#__construct()-detail
http://www.yiiframework.com/doc-2.0/yii-base-controller.html#getUniqueId()-detail

**Comment by adummy832** [comment]
Thank you very much sir @gevorgmansuryan! You are awesome! This save me a ton of time. Struggling on this for hours, XD on how to pass an instance in 2 different methods. Thanks again! Godspeed! :-)
