### ISSUE TITLE
yii\db\Query binding not asked param to query

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#14976]
I see a strange behavior in `yii\db\Query()` because it adds a new not asked bind parameter.
 
### What steps will reproduce the problem?
```php
$query_template = [
    'select' => [
        'id',
        'foo AS bar',
    ],
    'from' => 'my_table',
    'where' => ['id' => ':my_placeholder'] // <<<<<<
];

$query = new Query();

// it just set the query clauses automatically
foreach ($query_template as $clause => $data) {
    $query->$clause($data);
}

$query->addParams([':my_placeholder' => 123);

$result = $query->createCommand($db)->queryAll();
```
### What is the expected result?
```sql
SELECT `id`, `foo` AS `bar` FROM `my_table` WHERE `id`=123
```
 
### What do you get instead?
```sql
SELECT `id`, `foo` AS `bar` FROM `my_table` WHERE `id`=:qp1      # why :qp1?
```
```php
// params Yii is trying to bind:
Array
(
    [:my_placeholder] => 123 // <<<<< should be this
    [:qp1] => :my_placeholder // <<<<< dont know where it comes from
)
```
```xml
<response>
<link type="text/css" id="dark-mode" rel="stylesheet" href=""/>
<name>Database Exception</name>
<message>
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens The SQL being executed was: SELECT `id`, `foo` AS `bar` FROM `my_table` WHERE `id`=':my_placeholder'
</message>
<code>0</code>
<type>yii\db\Exception</type>
<file>
/home/...../vendor/yiisoft/yii2/db/Schema.php
</file>
<line>595</line>
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master (installed from 3 days ago)
| PHP version      |  7.1
| Operating system | Linux Deepin 15.4.1

**Comment by slinstj** [comment]
I found the problem!
The `where` attribute should not be using `array` but only string:
```php
'where' => 'id = :my_placeholder'
```

**Comment by cebe** [comment]
or simply `'where' => ['id' => 123]`, see http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#hash-format

> Using the Hash Format, Yii internally uses parameter binding so in contrast to the string format, here you do not have to add parameters manually.

**Comment by slinstj** [comment]
Yeah, but a placeholder is required there (it is a requirement of my system).
