### ISSUE TITLE
yii2-pjax no longer wokrs?

### ISSUE THREAD

**Issue by neatstudio** [yiisoft/yii2#14987]
where i use "composer update",composer told me ：

```
The "https://bower.herokuapp.com/packages/yii2-pjax" file could not be downloaded (HTTP/1.1 410 Gone)
https://bower.herokuapp.com/packages could not be fully loaded, package information was loaded from the local cache and may be out of date
```
yii2 version > 2.0.6

**Comment by samdark** [comment]
@SilverFire, @hiqsol ?

**Comment by rob006** [comment]
https://github.com/fxpio/composer-asset-plugin/issues/309

**Comment by cebe** [comment]
closing as it is not an issue to be fixed in Yii. Sent a pull request to the asset plugin: https://github.com/fxpio/composer-asset-plugin/pull/310

**Comment by schmunk42** [comment]
Could this be hotfixed with https://github.com/fxpio/composer-asset-plugin/blob/c375f86955e53270b84c0f4cae4f541010ae1e6f/Resources/doc/index.md#usage-with-private-bower-registry ?

**Comment by cebe** [comment]
if it would not work right now I'd consider that but as the URLs are redirecting it should be fine to update the asset plugin. We can not fix existing code anyway, this is for new setups, which could then directly get the latest verison of the plugin.

**Comment by cebe** [comment]
Oh well...

> https://twitter.com/bower/status/921039231623024640
> On next Wednesday we’ll disable old registry for a full day. Please upgrade Bower to not experience any disruption: npm install -g bower

we need some announcements about this and also update the application templates.

**Comment by SilverFire** [comment]
Fixed
