### ISSUE TITLE
Tree layout of checkbox

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#14999]
I suggest to implement new kind of input form.
In order to display items in tree instead list.

### What is the expected result?
```php
$form->field($model, 'activities')->checkboxTree($rootActivities, 'childActivities');
```

### What do you get instead?
I need to implement very complex methods in view to achieve the tree layout.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6.31
| Operating system | Win 10

My current script to make a checkbox tree:

```php
<?php
function build_node($model, $attribute, $parentItem){
	$items = $parentItem->getItems()->indexBy('id')->all();
	if (count($items) > 0) {
		return '<div style="margin-left: 20px;">' . Html::activeCheckboxList($model, $attribute, $parentItem->getItems()->indexBy('id')->all(), [
			'item' => function ($index, $label, $name, $checked, $value) use ($model, $attribute, $parentItem) {
				return '<div style="display:block;">' . Html::checkbox($name, $checked, [
					'value' => $value,
					'label' => $label->name,
				]) . '</div>' . build_node($model, $attribute, $label);
			},
		]) . '</div>';
	}
	return '';
}
?>

<?= $form->field($model, 'activities')->checkboxList($rootActivities, [
	'item' => function ($index, $label, $name, $checked, $value) use ($model) {
		return Html::checkbox($name, $checked, [
			'value' => $value,
			'label' => $label->name,
		]) . build_node($model, 'activities', $label);
	},
]); ?>
```

**Comment by ptz-nerf** [comment]
I also need a submit button that looks like a pony. Then user click on it and form is valid, pony says "и-го-го". You know what I mean?

Yii privides `ActiveField::widget()` and `InputWidget` for such situations. You can place all the logic inside the widget.
Also you can use third-party solutions. http://demos.krajee.com/tree-manager-demo/tree-view-input

**Comment by cebe** [comment]
this is out of scope for Yii core and should be solved in an extension.

**Comment by mklemarczyk** [comment]
I don't want uber crazy tree view manager, only simple style that shows checkboxlist as checkboxtree. It should be easy for Yii to have such features. I do not want to implement it and care about internal stuff in Yii. Code that I write is in 70% copy from Yii library.

**Comment by ptz-nerf** [comment]
@mklemarczyk, Yii should not care about third-party ui elements. This is not a standard form element. Not even the standard bootstrap component.

**Comment by mklemarczyk** [comment]
@ptz-nerf Oh, now I see.
