### ISSUE TITLE
Pjax ending the application when rendering a widget in response

### ISSUE THREAD

**Issue by louist7** [yiisoft/yii2#14994]
We are running a widget which contains an active form, submitted within a Pjax container to an action in the controller.

Within this action we perform server side validation and attempt to save the model, should this fail to save we want to be able to rerun the widget with the same model and return the HTML to replace the Pjax container. This would therefore keep the form displayed with validation errors in place.

The problem occurs when the render is used within the widget to get the view. It appears as Pjax always ends the application, the JS required for the client side validation is not reloaded and the client side validation on the form stops working.

Is there any common practice for having an active form within a Pjax container, and rerun the form as a response should the server side validation fail, without breaking the client side validation?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.0.0
| Operating system | OS X v10.11.5

**Comment by Alex-Code** [comment]
How are you rendering in the action?

**Comment by louist7** [comment]
After debugging into the Pjax jQuery source we saw that the JS for the form validation was in fact being appended into the document, but it wasn't attached to the form.

Looking into the Pjax widget we realised there is a formSelector option which we previously had missed. Setting this to the forms ID has solved the issue for us and the form is now being validated again.

Thanks for your time
