### ISSUE TITLE
Calling unknown method: yii\web\ErrorHandler::renderException()

### ISSUE THREAD

**Issue by yanhuixie** [yiisoft/yii2#14992]
### What steps will reproduce the problem?
Just throw an Exception at the beginning of ANY controller/action, site/index for example here.
``` php
    public function actionIndex() {
        throw new \Exception("oops.."); 
        return $this->render('index');
    }
```

### What is the expected result?
get a default site/error page with message "oops..".

### What do you get instead?
get a default site/error page with message "'An internal server error occurred.'"

### Additional info
We have tried to dig into it and found out an UNEXPECTED behavior.
Instead of normally calling yii\web\ErrorHandler->renderException and show the right message, but a NEW "Calling unknown method" exception was occurred.
L111 in yii\base\ErrorHandler:
``` php
    public function handleException($exception)
    {
        if ($exception instanceof ExitException) {
            return;
        }

        $this->exception = $exception;

        // disable error capturing to avoid recursive errors while handling exceptions
        $this->unregister();

        // set preventive HTTP status code to 500 in case error handling somehow fails and headers are sent
        // HTTP exceptions will override this value in renderException()
        if (PHP_SAPI !== 'cli') {
            http_response_code(500);
        }

        try {
            $this->logException($exception);
            if ($this->discardExistingOutput) {
                $this->clearOutput();
            }
            $this->renderException($exception); //"Calling unknown method", the real time CLASS of $this is yii\web\ErrorHandler, which is shown by xdebug.
            if (!YII_ENV_TEST) {
                \Yii::getLogger()->flush(true);
                if (defined('HHVM_VERSION')) {
                    flush();
                }
                exit(1);
            }
        } catch (\Exception $e) {
            // an other exception could be thrown while displaying the exception
            $this->handleFallbackExceptionMessage($e, $exception);
        } catch (\Throwable $e) {
            // additional check for \Throwable introduced in PHP 7
            $this->handleFallbackExceptionMessage($e, $exception);
        }

        $this->exception = null;
    }
```

And the "Calling unknown method" exception is thrown by Component.php.
``` php
     public function __call($name, $params)
    {
        $this->ensureBehaviors();
        foreach ($this->_behaviors as $object) {
            if ($object->hasMethod($name)) {
                return call_user_func_array([$object, $name], $params);
            }
        }
        throw new UnknownMethodException('Calling unknown method: ' . get_class($this) . "::$name()");
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.20
| Operating system | Debian/ Windows 7, All the same

**Comment by cebe** [comment]
> $this->renderException($exception); //"Calling unknown method", the real time CLASS of $this is yii\web\ErrorHandler, which is shown by xdebug.

The method exists: https://github.com/yiisoft/yii2/blob/980cfde0f1720a9f8516f76d37afa5a5528882ca/framework/web/ErrorHandler.php#L78

Could you reproduce this problem starting from a plain basic app installation?

**Comment by yanhuixie** [comment]
Thanks, @cebe .
Yes the method is exists, and I can find it in my local vendor source file.
I have just tried a fresh BASIC installation via composer and found something new.
Anything is not modified excepts the THROW statement.
``` php
    public function actionIndex() {
        throw new \Exception("oops.."); 
        return $this->render('index');
    }
```
When the deploy config is 
``` php
// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```
then I can see the "oops.." error message normally.
but if change the deploy config to
``` php
// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');
```
I can just get the "An internal server error occurred."
So I think the issue can be reproduced.

**Comment by cebe** [comment]
> I can just get the "An internal server error occurred."

that is expected, in production environment, there are no details shown about the error.

**Comment by yanhuixie** [comment]
@cebe OK, thanks for your reply. What make me puzzled is just why a additional confusing EXCEPTION is raised... Is it necessary to have the "Calling unknown method" exception in "$this->renderException($exception)" caused?

**Comment by cebe** [comment]
I have no idea where that exception comes from. It does not happen in fresh installations so you have to look in your environment for possible causes.

**Comment by yanhuixie** [comment]
Hi @cebe , as mentioned above, I have made a fresh installations via composer and just set the "YII_DEBUG=false and YII_ENV=prod" and "throw an exception in site/index action for test" after it, then the "yii\web\ErrorHandler::renderException()" caused a "Calling unknown method" exception. So I'm not sure what is really a "fresh installations"...

**Comment by cebe** [comment]
This does not happen for me when I do the same so there must be something different on your end. Can you provide the composer.lock file? or maybe even better a complete zip file of the installation that produces the error?

**Comment by yanhuixie** [comment]
[yii2basic.tar.gz](https://github.com/yiisoft/yii2/files/1421221/yii2basic.tar.gz)
Thanks @cebe !
This is the source package on my end.

**Comment by cebe** [comment]
The only [difference between my code and yours](https://gist.github.com/cebe/7a95bdc9968e272217de301207f96d7e) is that you installed packages via https://pkg.phpcomposer.com/ but all relevant code seems identical. Also if I run your application here it does not produce such an error. I get the error page as expected:

![bildschirmfoto von 2017-10-27 10-21-54](https://user-images.githubusercontent.com/189796/32094624-b1bb16dc-bb00-11e7-9f2d-75d6f683ec1b.png)

It must be something related to your environment. No idea what to look for.

**Comment by samdark** [comment]
Closing until more info provided.

**Comment by yanhuixie** [comment]
Hi, @cebe , we can't see "Calling unknown method" exception in any UI or system log, but just in debug time.
1. throw an exception in site/index
![tim 20171027164200](https://user-images.githubusercontent.com/1049615/32095500-fb2b43de-bb35-11e7-819b-eef05cbc4d0c.png)
2. dig to L111 in yii\base\ErrorHandler
![tim 20171027164206](https://user-images.githubusercontent.com/1049615/32095515-0332cbce-bb36-11e7-8822-3dfcdebffdca.png)
3. dig to Component.php
![tim 20171027164210](https://user-images.githubusercontent.com/1049615/32095491-f3f6725a-bb35-11e7-8d84-c2bba7b3835d.png)

**Comment by samdark** [comment]
Ah... that's your debugger to blame. It's trying to access properties and calling methods.

**Comment by yanhuixie** [comment]
Yes @samdark , thanks for your help, too.
So it seems the fault of Xdebug... I know sometimes it may not work properly and without guarantee...
Thanks again you guys.
