### ISSUE TITLE
Aliases. Nested alias is unchanged after set new parent alias.

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15008]
Mechanism of `setAlias('@new', '@middle')` "translate" `middle` alias to absolute path and broke pair.
[guide](https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-aliases.md) does not say anything about it

### What steps will reproduce the problem?
```php
Yii::setAlias('@common', dirname(__DIR__));
Yii::setAlias('@commonalias', '@common/components');
$a =  Yii::getAlias('@commonalias');
Yii::setAlias('@common', dirname(__DIR__, 2)); //for test
$b = Yii::getAlias('@commonalias');
```
### Produced
for example
```php
$a is '/var/www/html/common/components';
$b is '/var/www/html/common/components';
i.e. $a === $b
```

**This is can be represented in docs!**
[guide](https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-aliases.md)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13-dev

**Comment by rob006** [comment]
See https://github.com/yiisoft/yii2/issues/10157 and https://github.com/yiisoft/yii2/pull/11620

**Comment by bscheshirwork** [comment]
@rob006 changes planed in 2.1 nice.

Docs still unchanged...
