### ISSUE TITLE
Union sort

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#15004]
### What steps will reproduce the problem?
```
        $provider = new ActiveDataProvider([
            'query' => Feed::find()->select(['createdAt'])
                ->union(Article::find()->select([
                    'createdAt'
                ])),
            'sort' => [
                'defaultOrder' => [
                    'createdAt' => SORT_DESC
                ]
            ]
        ]);
```
### What is the expected result?
```(SELECT `createdAt` FROM `feed`) UNION ( SELECT `createdAt` FROM `article`) ORDER BY `createdAt` DESC LIMIT 20```
### What do you get instead?

```(SELECT `createdAt` FROM `feed` ORDER BY `createdAt` DESC LIMIT 20) UNION ( SELECT `createdAt` FROM `article` )```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1
| Operating system | Win10

**Comment by RSalo** [comment]
Solved for me by this comment https://github.com/yiisoft/yii2/issues/7992#issuecomment-138486264

**Comment by rob006** [comment]
Duplicates  #12968
