### ISSUE TITLE
ORA-32034: unsupported use of WITH clause

### ISSUE THREAD

**Issue by frasim** [yiisoft/yii2#15016]
### What steps will reproduce the problem?
If you are using OCI to execute a query that contains a WITH clause and PAGINATION is enabled
an exception will be generated because the QueryBuilder internally wraps your SQL using another WITH to manage pagination:

> WITH USER_SQL AS (**$sql**),
>     PAGINATION AS (SELECT USER_SQL.*, rownum as rowNumId FROM USER_SQL)
> SELECT *
> FROM PAGINATION
> WHERE $filter

Actually Oracle (12c) [doesn't supports nested WITH](http://www.dba-oracle.com/t_ora_32034_unsupported_use_with_clause.htm) and if you try to execute the SQL it will return the error message 

> ORA-32034: unsupported use of WITH clause 

### Indicted file?

>  yii2/framework/db/oci/QueryBuilder.php
>  
>  Row 68
>  "buildOrderByAndLimit" method

### A possible solution?
Replace the external WITH clause with a SELECT:

> SELECT t.* FROM (
>   SELECT t.*, rownum as rowNumId FROM ($sql) t
> ) t 
> WHERE $filter

and change upper limit

> $filters[] = 'rownum <= ' . ($offset + $limit);

Complete method:

>     public function buildOrderByAndLimit($sql, $orderBy, $limit, $offset)
>     {
>         $orderBy = $this->buildOrderBy($orderBy);
>         if ($orderBy !== '') {
>             $sql .= $this->separator . $orderBy;
>         }
>         $filters = [];
>         if ($this->hasOffset($offset)) {
>             $filters[] = 'rowNumId > ' . $offset;
>         }
>         if ($this->hasLimit($limit)) {
>             //-----------------------------------------------------
>             $filters[] = 'rownum <= ' . ($limit);
>             //-----------------------------------------------------
>         }
>         if (empty($filters)) {
>             return $sql;
>         }
>         $filter = implode(' AND ', $filters);
>         //-----------------------------------------------------
>         return <<<EOD
>  SELECT t.* FROM (
>      SELECT t.*, rownum as rowNumId FROM ($sql) t
>    ) t
>   WHERE $filter
>  EOD;
>         //-----------------------------------------------------
>     }

| Q                | A
| ---------------- | ---
| Yii version      | ‌2.0.11.2
| PHP version      | 7.0.18
| Operating system |Ubuntu 16.04 LTS
| DB version |Oracle 12c

**Comment by sergeymakinen** [comment]
I confirm this. I discovered this bug while working on migration builders.

**Comment by sergeymakinen** [comment]
In this case I'd prefer to merge `WITH` clauses. It's not so easy to implement but now we have `SqlTokenizer` so I could take a look in 2.0.15/2.0.16.
