### ISSUE TITLE
PHP notice error with different locale in log/Target.php

### ISSUE THREAD

**Issue by balrok** [yiisoft/yii2#15015]
### What steps will reproduce the problem?
Throw an exception and have logging enabled

### What is the expected result?
No php error

### What do you get instead?
PHP error:
```
Notice:  Undefined offset: 1 in /var/www/myproject/vendor/yiisoft/yii2/log/Target.php on line 362
Stack trace:
  1. yii\base\ErrorHandler->handleException() /var/www/myproject/vendor/yiisoft/yii2/base/ErrorHandler.php:0
  2. yii\log\Logger->flush() /var/www/myproject/vendor/yiisoft/yii2/base/ErrorHandler.php:113
  3. yii\log\Dispatcher->dispatch() /var/www/myproject/vendor/yiisoft/yii2/log/Logger.php:177
  4. yii\log\Target->collect() /var/www/myproject/vendor/yiisoft/yii2/log/Dispatcher.php:189
  5. yii\log\EmailTarget->export() /var/www/myproject/vendor/yiisoft/yii2/log/Target.php:128
  6. array_map() /var/www/myproject/vendor/yiisoft/yii2/log/EmailTarget.php:83
  7. yii\log\Target->formatMessage() /var/www/myproject/vendor/yiisoft/yii2/log/EmailTarget.php:83
  8. yii\log\Target->getTime() /var/www/myproject/vendor/yiisoft/yii2/log/Target.php:279
```

### Additional info
The bug happens because you split the timestamp by ".".
In my locale (german) it is a ",". Maybe you can fix it with a simple strpos first or maybe you can use some yii-locale functions.
https://github.com/yiisoft/yii2/blob/614fb52c45b06077682114f2ba246399af0e9a9c/framework/log/Target.php#L362

| Q                | A
| ---------------- | ---
| Yii version      | dev-master (614fb52c45b06077682114f2ba246399af0e9a9c)
| PHP version      |  7.0.22
| Operating system | Debian 3.16.7-ckt20-1+deb8u4

**Comment by bscheshirwork** [comment]
Can we separate timestamp by 
```php
[$timestamp, $usec] = preg_split("/\D/", (string)$timestamp));
```
Or we need check any local separators? Or get separator from locale throw helper?

**Comment by cebe** [comment]
@bscheshirwork your solution would probably also work in that case but in general we have this issue in many places so imo a helper is useful here. See #15027

**Comment by bscheshirwork** [comment]
@cebe yep, the helper is more elegant
