### ISSUE TITLE
Captcha not working with PHP 7.1.4

### ISSUE THREAD

**Issue by berthojoris** [yiisoft/yii2#15014]
### What steps will reproduce the problem?
I installed fresh yii2 advanced and hosting with PHP 7.1.4 but i get error message on page `site/contact`

> Page Not Found
> An internal server error occurred.

But working fine if I downgrade to PHP 7.0.12

### What is the expected result?
Working fine with captcha

### What do you get instead?
**requirements.php** all passed

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.4
| Operating system | Linux

**Comment by bscheshirwork** [comment]
@berthojoris, all of a php extensions is same?
`requirments.php` say  "all ok"?

**Comment by berthojoris** [comment]
@bscheshirwork Yes... I only change PHP Version in my hosting

**Comment by bscheshirwork** [comment]
You can see logs from you hosting?

**Comment by berthojoris** [comment]
In my requirements.php
GD PHP extension with FreeType support status **warning**

**Comment by samdark** [comment]
Well, that explains it. You need it in order to draw CAPTCHA.

**Comment by bscheshirwork** [comment]
> requirements.php all passed

:smirk_cat: passed... or not passed...
