### ISSUE TITLE
Support \Closure for DataFilter::attributeMap

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15028]
In REST controller who use ActiveDataFilter

The property `attributeMap` (not `searchModel`) can be use (additional) to resolve alias, who we use in resources definition
```php
$filter = new ActiveDataFilter([ 
'searchModel' => \api\models\PostSearch::class,
'attributeMap' => ['aliasId' => 'realFieldId'],
]);
```
```php
class \api\models\PostSearch extends app\models\Post {
    public function fields(){
        $fields = parent::fields();
        unset($fields['realFieldId']);
        $fields['aliasId'] = function () {
            return $this->realFieldId;
        };
        return $fields;
    }
}
```

So... I think we need options to move $attributeMap from controller (definition of DataFilter) to the model `searchModel`
```php
class \api\models\PostSearch extends app\models\Post {
    public static function attributeMap(){
         return ['aliasId' => 'realFieldId'];
    }
    public function fields(){
        $fields = parent::fields();
        unset($fields['realFieldId']);
        $fields['aliasId'] = function () {
            return $this->realFieldId;
        };
        return $fields;
    }
}
```
```php
$filter = new ActiveDataFilter([ 
'searchModel' => \api\models\PostSearch::class,
'attributeMap' => [ \api\models\PostSearch::class, 'attributeMap'],
]);
```

**i.e. we need closure support of `attributeMap` property too**

@klimov-paul 
what you think?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev

**Comment by samdark** [comment]
Could be a good idea but I'd like to hear @klimov-paul.

**Comment by klimov-paul** [comment]
`IndexAction::$dataFilter` can be configured as a Closure already. If you wish it dynamically populated you can do so already.
I can see no reason for callable spport for `DataFilter::$attributeMap`, especially since this attribuye is an array type and thus its actual value can not be separated from callable in the safe way.

**Comment by bscheshirwork** [comment]
I wish separate logic (model) from routing (controller)

**Comment by klimov-paul** [comment]
The `DataFilter` itself is a model layer, which wraps arbitrary ActiveRecord.
If you wish to create "super-smart" data filter you should either create your own class extending it or specify sophisticated config. You already have all you need for the task.

**Comment by bscheshirwork** [comment]
I tell about use `data filter` with `fields` on target models. IMHO target model can be have (must have) invert of the `fields` function the `attributeMap` to propose it for external functional like `DataFilter`
