### ISSUE TITLE
"object" (in any case) can no longer be used as a class name

### ISSUE THREAD

**Issue by grikdotnet** [yiisoft/yii2#15036]
https://github.com/php/php-src/blob/php-7.2.0RC5/UPGRADING#L44

### What steps will reproduce the problem?
Install PHP 7.2

### What do you get instead?
gri@User-pk:$ php yii

Fatal error: Cannot use 'Object' as class name as it is reserved in .../vendor/yiisoft/yii2/base/Object.php on line 77

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.2.0RC5
| Operating system | Linux

**Comment by samdark** [comment]
Already fixed in master.

**Comment by cebe** [comment]
see #7936
