### ISSUE TITLE
Left-pointing double angle quotation mark in translations

### ISSUE THREAD

**Issue by mrbig00** [yiisoft/yii2#15039]
### What steps will reproduce the problem?
I've seen in serveral translations (especially in romanian transaltions) that the parameters are quoted with « and ». I think that these are pretty ugly and I don't see no benefit from quoting with it.

For example: 
`'The format of {attribute} is invalid.' => 'Formatul «{attribute}» nu este valid.',`
### What is the expected result?
`'The format of {attribute} is invalid.' => 'Formatul {attribute} nu este valid.',`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.6.30
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
It depends on the language traditions. I'm not expert in Romanian so it's better to discuss with local community. When decided, send a pull request and I'll merge it.
