### ISSUE TITLE
Definitive Guide - Getting Started missing key instruction - 'include...'

### ISSUE THREAD

**Issue by tom-berend** [yiisoft/yii2#15035]
### What steps will reproduce the problem?

I'm following the newbie instructions.  the first lesson ('hello') works, but I spent hours trying to figure out the second lesson ('form').  you didn't mention that we need to include **use app\models\EntryForm;** in the SiteController file.  
Minor documentation update.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/blob/2.0.12/docs/guide/start-forms.md#creating-an-action-

there is `use app\models\EntryForm;` in the code example.

**Comment by tom-berend** [comment]
Hi guys,

I think you should add a hint to the FORMS lesson that you need to add a 'use app\models\EntryForm'.

Someone put a LOT of effort into writing those lessons, and I am working through them (and amazed by Yii).  I am not the only person who tripped over this problem.  I did a quick search and found this.

https://stackoverflow.com/questions/25679631/yii-base-errorexception-class-app-controllers-entryform-not-found

I'm not in your league as a programmer, but I'm better than average with PHP, and persistent.  I have been getting stuck on almost every lesson so far, I work through my issue by putting "echo $something;die;" statements in the code to figure out what is happening. 

My next confusion was about the index.php file in the database example (the 'Web' directory is not at my server root, and I don't think anyone learning Yii will set it there).  So I was trying to use the index.php in the Views directory that I had just created.  I think you should NOT use 'index.php' in your example.
 
My next confusion was in the Gii example (which BTW is amazing!), that the namespace isn't obvious.  

I suspect most programmers try Yii, hit this kind of obstacle, and then give up.  They don't have any investment in Yii, and tell their friends that it is buggy.  You have done too much work on this product to let that happen.  

If you like, I will fork Yii, continue the lessons, and submit a pull with updated lesson texts (I'm not familiar with github yet, but persistent).  But I think you would prefer simply to hear what problems a newbie hits.

**Comment by cebe** [comment]
Thanks for the feedback. It would be great if you could send a pull request with enhancements that you think are helpful for others. Note however that using Yii requires some basic knowledge of how PHP namespaces work, so this guide should be an introduction to Yii and not PHP in general.
We might add a "things you need to learn before doing this" section on top of each guide to help making this more clear. Linking to the PHP docs for example to http://php.net/manual/en/language.namespaces.php

To edit files on github, you can click the edit button and github will automatically create a fork and a branch for you.: https://github.com/yiisoft/yii2/blob/master/docs/guide/start-forms.md

**Comment by tom-berend** [comment]
OK.  Assign it to me. :)  I will only make tiny changes.

Your suggestion of "What you need to know" is excellent.  I've been coding PHP for about 10 years, building custom applications and working with Joomla! and Wordpress, and have never previously used namespaces.  Surely I am not the only one.

**Comment by tom-berend** [comment]
Hi, need your wise direction.

There is a permissions problem when the programmer uses an Apache server to generate code with Gii on a Linux box.  I'm not entirely clear what is happening, but I think the code creates a directory with 755 permissions (ie: only www-data has read-write as the owner) in line 246.  This fails on the next line (the part I don't really understand), and then the directory is no longer writable with a text editor.  See image below.

Should I document how to fix the permissions with chmod?   Insist they use 'Yii server'?  Or just submit this as a new issue?   Or am I the one who is confused?


![permission](https://user-images.githubusercontent.com/11073753/32248302-99f58196-be5b-11e7-8c89-e9cc67595740.jpg)

**Comment by cebe** [comment]
Permission management on linux is a bit tricky with gii if you run nginx or apache. We should add a note and recommend using php builtin webserver instead. You can keep it in this issue, its also an improvement to make in "Getting Started" guide.
