### ISSUE TITLE
Calling unknown method: yii\db\ColumnSchemaBuilder::integer() 

### ISSUE THREAD

**Issue by FanGremlin** [yiisoft/yii2#15033]
Use command for create new table
```
php console/yii migrate/create create_article_counter_table --fields="article_id:primaryKey:integer:notNull:foreignKey(article),viewed:integer:defaultValue(0),comments:integer:defaultValue(0)"
```
result automatic generated file , include line 
```
        $this->createTable('article_counter', [
            'article_id' => $this->primaryKey()->integer()->notNull(),
            'viewed' => $this->integer()->defaultValue(0),
            'comments' => $this->integer()->defaultValue(0),
        ]);
```
after command apply migration have error
Exception: Calling unknown method: yii\db\ColumnSchemaBuilder::integer() (/data/www/YYYYY/vendor/yiisoft/yii2/base/Object.php:220)

if on hand modify this code , delete primaryKey() in createTable and add after primaryKey, this migration work now
```
        $this->createTable('article_counter', [
            'article_id' => $this->integer()->notNull(),
            'viewed' => $this->integer()->defaultValue(0),
            'comments' => $this->integer()->defaultValue(0),
        ]);
        $this->addPrimaryKey('article_counter_pkey', 'public.article_counter', ['article_id']);
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 7.0.22
| Operating system | Ubuntu 16.04.3

**Comment by kjusupov** [comment]
Gives error on PostgreSQL 9.5 as well...

I always thought/assumed that primary key can NOT be Null and must be unique...

@FanGremlin wouldn't be better to have it as below (skipping primaryKey so that table it will have dedicated primary key `id`) ?

`
yii migrate/create create_article_counter_table --fields="article_id:integer:notNull:foreignKey(article),viewed:integer:defaultValue(0),comments:integer:defaultValue(0)"
`

with generated code being

```php
    public function up()
    {
        $this->createTable('article_counter', [
            'id' => $this->primaryKey(),
            'article_id' => $this->integer()->notNull(),
            'viewed' => $this->integer()->defaultValue(0),
            'comments' => $this->integer()->defaultValue(0),
        ]);

        // creates index for column `article_id`
        $this->createIndex(
            'idx-article_counter-article_id',
            'article_counter',
            'article_id'
        );

        // add foreign key for table `article`
        $this->addForeignKey(
            'fk-article_counter-article_id',
            'article_counter',
            'article_id',
            'article',
            'id',
            'CASCADE'
        );
    }
```

**Comment by s1lver** [comment]
This is not a Yii error. 
The designer assembled the query correctly, according to the passed parameters.

Using strings as a primary key is not advisable. For a number, the index will simply be added to the end.
Therefore, it makes no sense to complement the command.

The only thing that can be done is to prevent the generation of `integer()` if pk is already selected (show the warning immediately in the console).

But, I would not waste time on it. By and large, this should fall on the shoulders of the programmer.
