### ISSUE TITLE
Session Write Failed

### ISSUE THREAD

**Issue by Knight-Yoshi** [yiisoft/yii2#15037]
### What steps will reproduce the problem?
Couldn't say this was the first time it happened and it happened only once on page reload - reloading a second time had no issue.

### What is the expected result?
Session writes to the DB

### What do you get instead?
Session write failed

### Additional info
`yii\base\ErrorException: session_regenerate_id(): Session write failed. ID: user (path: ) in /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/Session.php:295 Stack trace: #0 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/DbSession.php(103): yii\web\DbSession->regenerateID() #1 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/User.php(618): yii\web\DbSession->regenerateID() #2 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/User.php(292): app\components\User->switchIdentity() #3 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/User.php(674): app\components\User->loginByCookie() #4 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/User.php(188): app\components\User->renewAuthStatus() #5 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/User.php(343): app\components\User->getIdentity() #6 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/Component.php(132): app\components\User->getId() #7 /Users/KnightYoshi/workspace/www/site_project/modules/randimg/views/randimg/viewset.php(14): app\components\User->__get() #8 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/View.php(330): app\components\View->unknown() #9 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/View.php(250): app\components\View->renderPhpFile() #10 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/View.php(152): app\components\View->renderFile() #11 /Users/KnightYoshi/workspace/www/site_project/components/View.php(58): app\components\View->render() #12 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/Controller.php(381): app\components\View->render() #13 /Users/KnightYoshi/workspace/www/site_project/modules/randimg/controllers/RandimgController.php(158): app\modules\randimg\controllers\RandimgController->render() #14 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/InlineAction.php(57): app\modules\randimg\controllers\RandimgController->actionDisplay() #15 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/InlineAction.php:57}() #16 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams() #17 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/Module.php(523): app\modules\randimg\controllers\RandimgController->runAction() #18 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/web/Application.php(102): yii\web\Application->runAction() #19 /Users/KnightYoshi/workspace/www/site_project/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest() #20 /Users/KnightYoshi/workspace/www/site_project/web/index.php(12): yii\web\Application->run() #21 {main}`
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.6

**Comment by samdark** [comment]
Could be #9438 related.

**Comment by samdark** [comment]
Do you write any additional data into database?

**Comment by Knight-Yoshi** [comment]
It also writes the user ID to the session table on log in to be able to invalidate all of the user's sessions.

**Comment by samdark** [comment]
Try code from master along with debug mode. It will reveal real reason behind the error.

**Comment by Knight-Yoshi** [comment]
Try what from the master branch? I have looked in at the debugger. That's how I got the stack trace, because I had already refreshed. The stack trace says `session_regenerate_id()` threw an exception. I'm not sure what more I'm suppose to be able to find out, especially since it seems to have been a one-off error.

**Comment by samdark** [comment]
Well, the reason. In 2.0.12 you'll see this error. In master you may see, for example, an exception that occurred during saving values to DB with your custom handler that resulted in `session_regenerate_id()` errors. If that's not the case then it's different issue.

**Comment by Knight-Yoshi** [comment]
I use this for the the session module config to include the user ID.
```
'writeCallback' => function ($session) {
	return [
		'user_id' => Yii::$app->user->id
	];
}
```

**Comment by samdark** [comment]
I'd check if user isn't guest here first.

**Comment by Knight-Yoshi** [comment]
I've gone ahead and added a ternary to set the user ID or explicitly set null, but I'm still not sure if that's what caused the issue; since if the user is not signed in that would be null anyway.

Like I said, though. That's the first time that happened and it only happened once. So it's hard to say, but I added checking it anyway per your recommendation.

**Comment by samdark** [comment]
I'm closing the issue for now since there's not enough info to fix anything. If it will appear again, please let us know.
