### ISSUE TITLE
Important note about Bower and the asset plugin

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/yii2#15040]
In yii site a new news released: Important note about Bower and the asset plugin
but in yii2 guide in installation section link of bower assets is old
http://www.yiiframework.com/doc-2.0/guide-start-installation.html :

composer global require "fxp/composer-asset-plugin:^1.3.1"
composer create-project --prefer-dist yiisoft/yii2-app-basic basic

**Comment by SilverFire** [comment]
Thank you for your note, but the latest version `1.4.2` satisfies constraint `^1.3.1`, so everything should work smoothly.

**Comment by schmunk42** [comment]
We've [raised this to 1.4.1 a few days ago](https://github.com/yiisoft/yii2/commit/15a46441e1241879c3cff0d9422713075bdf735c).
