### ISSUE TITLE
About documents  2-1[installing Yii - Verifying the Installation]

### ISSUE THREAD

**Issue by kure2** [yiisoft/yii2#15041]
### What steps will reproduce the problem?
ORIGINAL:```Copy /requirements.php to /web/requirements.php and then use a browser to access it via http://localhost/requirements.php```

`requirements.php` to `/web/requirements.php` and  to access `http://localhost/requirements.php` is wrong.
`requirements.php` line 14:` $frameworkPath = dirname(__FILE__) . '/vendor/yiisoft/yii2'`;
If you move this file to the `web` folder,there are no `vendor` folders under the `web` folder

so `is_dir($frameworkPath)` must be the ‘false’ state  

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.9
| Operating system | windows 10 x64

**Comment by samdark** [comment]
Have you tried it?

**Comment by kure2** [comment]
![status](https://i.loli.net/2017/10/30/59f6d62f91257.jpg)

**Comment by cebe** [comment]
fixed by  yiisoft/yii2-app-basic#146, thanks for reporting!
