### ISSUE TITLE
Drop HHVM support

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#15058]
According to the latests benchmarks, PHP 7.1 gets pretty close to HHVM ([[1]](https://www.phoronix.com/scan.php?page=news_item&px=PTS-PHP-7.1-Benchmarks), [[2]](https://kinsta.com/blog/hhvm-vs-php-7/)) and sometimes even beats HHVM.

PHP 7.2 will bring even more performance, so it is possible that PHP will be faster than HHVM. Despite that fact, there are more than 230 [reported PHP5 incompatibilities](https://github.com/facebook/hhvm/issues?q=is%3Aopen+is%3Aissue+label%3A%22php5+incompatibility%22) and 71 [reported PHP7 incompatibilities](https://github.com/facebook/hhvm/issues?q=is%3Aopen+is%3Aissue+label%3A%22php7+incompatibility%22) in HHVM. It is confirmed by our tests, that are sometimes skipped for HHVM:

<img width="1339" alt="screen shot 2017-11-01 at 07 44 30" src="https://user-images.githubusercontent.com/4499203/32261623-88111878-bed8-11e7-97d7-ecd58457b5fa.png">

I suggest to stop HHVM support because:

1. PHP 7.1 performance is close to HHVM
2. HHVM contains a lot of PHP incompatibilities and theis count will grow
3. We already have things that are not compatible with HHVM and absorbing new features of PHP.

**Comment by SilverFire** [comment]
I've forgot we have already removed HHVM support for 2.1 😆 https://github.com/yiisoft/yii2/issues/13010

**Comment by cebe** [comment]
referencing this here: https://github.com/yiisoft/yii2/issues/12982#issuecomment-341025171
