### ISSUE TITLE
Use BaseYii::configure in Container::build or vice versa

### ISSUE THREAD

**Issue by vtvz** [yiisoft/yii2#15053]
These two places in framework do the same thing -- configure the object:

https://github.com/yiisoft/yii2/blob/master/framework/di/Container.php#L385-L387

https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L529-L536

Why not to use `BaseYii::configure` (Or `Yii::configure`) method in `Container::build`, or in container make function like `configureObject` and use it like this:

```php
public static function configure($object, $properties)
{
    return self::$container->configureObject($object, $properties);
}
```

I can create PR if it's necessary.

// Sorry for my bad English

**Comment by samdark** [comment]
Makes sense from DRY standpoint.
