### ISSUE TITLE
Document $generatorTemplateFiles patterns for MigrateController in guide and docs

### ISSUE THREAD

**Issue by Sarke** [yiisoft/yii2#15050]
There are a few useful migration templates that get auto created based on specific naming of the migration.  However, only the "create_table" one is documented.

```php
    public $generatorTemplateFiles = [
        'create_table' => '@yii/views/createTableMigration.php',
        'drop_table' => '@yii/views/dropTableMigration.php',
        'add_column' => '@yii/views/addColumnMigration.php',
        'drop_column' => '@yii/views/dropColumnMigration.php',
        'create_junction' => '@yii/views/createTableMigration.php',
    ];
```

**Comment by Sarke** [comment]
For example:

    ./yii migrate/create add_sometext_column_to_mytable_table --fields="sometext:text"

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#generating-migrations

**Comment by Sarke** [comment]
Well, that's embarrassing...
