### ISSUE TITLE
Got server error as 500 Internal Server Error 

### ISSUE THREAD

**Issue by Habibsalma** [yiisoft/yii2#15069]
Greetings,

Got server error as 500 Internal Server Error , Response -  <pre>PHP Notice &#039;yii\base\ErrorException&#039; with message &#039;Undefined index: User&#039; 

I am getting this error when I used Unique validator in yii2 model. 
Code
[['username'], 'unique'],

if I removed this rule then no error. If someone can help me . it will be very useful for me to learn.

Thanx Sally.

**Comment by Habibsalma** [comment]
I want to know why my question was closed.

**Comment by schmunk42** [comment]
Please see the yii-bot comment.
