### ISSUE TITLE
A question about version 2.0.13

### ISSUE THREAD

**Issue by qwerty199369** [yiisoft/yii2#15079]
### What steps will reproduce the problem?
```bash
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application

echo Yii::getVersion();
```
### What is the expected result?
2.0.13

### What do you get instead?
2.0.13-dev

### Additional info
Is that normal?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13?
| PHP version      | 7.1.8
| Operating system | win

**Comment by qwerty199369** [comment]
@samdark I do not have a `composer.json` file. just run:
```
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application
```

**Comment by samdark** [comment]
Should not happen: https://github.com/yiisoft/yii2-app-advanced/commit/712383bb764048f882f0de18dc30ed7fdfc50eb2

**Comment by rob006** [comment]
Tag for 2.0.13 is incorrect:
https://github.com/yiisoft/yii2-framework/blob/2.0.13/BaseYii.php
https://github.com/yiisoft/yii2-framework/compare/2.0.13...master

**Comment by cebe** [comment]
thanks for noting that, the tag has been fixed now. The release date in the changelog does not match on the tagged commit (it is only adjusted after that) but thats a minor thing imo and we can keep it like that.

Must have happened on that number... 2.0.**13** :-)
