### ISSUE TITLE
[Feature Request] Add Support for Laravel Style Routing

### ISSUE THREAD

**Issue by mattcdavis1** [yiisoft/yii2#15075]
Yii routing is a real pain.  All i want, as it pertains to routing, is to be able to create a simple map of url pattern => class@method.  But instead i'm forced into a naming conventions which are uneccessarily complicated and limiting.  Please add support for simpler, more flexible routing - ie:  

```
$router->any(
    'some/url/{slug}/{id}',
    [
        'uses' => 'Union\AppModule\Http\Controller\PropertiesController@detail',
        'as' => 'properties.detail',
    ]
);
```

I believe i saw a package for this somewhere but this sort of thing belongs in the core as routing is fundamental to a web framework.

**Comment by rob006** [comment]
How this would differ from `'some/url/<slug:\w+>/<id:\d+>' => 'properties/detail'`?

**Comment by samdark** [comment]
@rob006 your example should have been

```php
'some/url/<slug>/<id>' => 'properties/detail'
```

to match the topic starting one.

**Comment by mattcdavis1** [comment]
It differs because `PropertiesController` is implied from `properties` and `detailAction` is implied from `detail`.  Additionally, something like `myFooBarAction` requires a route of `my-foo-bar` (rather than `myFooBar`).  

This is all pointless and unnecessary complexity - I really dislike this.  Explicit is better than implicit in this context - it makes things easier and more flexible.  I see no value in implying `Controller`, requiring dashes for kebab names, and forcing `Action.` . The framework should just get out of the way and let people simply enter the class/method of their choice.

**Comment by cebe** [comment]
@mattcdavis1 if you only want to have the mapping of URL -> controller you are correct, we could just use the class name, however the Yii routing system is much more powerful than that, you can also create URLs give a route and therefor we have the intermediate route concept that allows you to specify a matching from URL to route and also from route to URL.

**Comment by cebe** [comment]
I see not much difference to this https://laravel.com/docs/5.5/urls#urls-for-controller-actions

```php
// laravel
$url = action('UserController@profile', ['id' => 1]);
// yii
$url = Url::to(['user/profile', 'id' => 1]);
```

https://laravel.com/docs/5.5/routing#basic-routing

```php
// laravel
Route::get('/user', 'UsersController@index');
// yii
'/user' => 'user/index',
// or to have it explicit on the http verb
'GET /user' => 'user/index',
```
