### ISSUE TITLE
New feature: Easier creation of dataProvider

### ISSUE THREAD

**Issue by awesomeguy3** [yiisoft/yii2#15078]
It's actually only one function (maybe). What I'm suggesting is that you implement a function in ActiveRecord that will automatically return ActiveDataProvider instance when chained to an ActiveRecord object.

`$dataProvider = TableName::find()->where(['column' => 'something'])->pagination();`

or maybe ->dataProvider() or any other name. Just for convinience, it can except the same parameter as ActiveDataProvider constructor would (except 'query' key in config)

**Comment by samdark** [comment]
I think it's a bad idea for the core since it will couple AR with data providers more. There's https://github.com/yiisoft/yii2-collection that you may try.
