### ISSUE TITLE
jQuery 3 - window load inside ready state will not be triggered

### ISSUE THREAD

**Issue by alexantr** [yiisoft/yii2#15086]
In #14620 I proposed to put code from POS_LOAD section to jQuery ready state. But this not working in in jQuery 3. See https://github.com/jquery/jquery/issues/3194

Need to replace `jQuery(function ($) { $(window).on('load', function () { /*code*/ }); });` with `jQuery(window).on('load', function () { /*code*/ });`

Sorry for this.

### What steps will reproduce the problem?

Register some code in POS_LOAD section.

### What is the expected result?

Code must be executed when page content fully loaded.

### What do you get instead?

Code doesn't run at all.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | *
| Operating system | *

**Comment by samdark** [comment]
Would you please make a pull request?
