### ISSUE TITLE
Yii bug in server

### ISSUE THREAD

**Issue by sodiabdullaev** [yiisoft/yii2#15096]
### What steps will reproduce the problem?
My project which created using yii1 was working perfectly on my local computer
and when I put it on server, server started showing error like "Use of undifined error - assumme 'php'"
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.16
| PHP version      | 
| Operating system |

**Comment by cebe** [comment]
you could have waited a few minutes more in IRC to get the answer. search for 'php' in your code.
