### ISSUE TITLE
Yii 2.0.13 Url::base() not return https, only http

### ISSUE THREAD

**Issue by ducquan135** [yiisoft/yii2#15094]
I has update to version 2.0.13 and Url::base() not return https, only http but my website use https

**Comment by rob006** [comment]
How do you call `Url::base()`? What returns `Yii::$app->request->isSecureConnection`?

**Comment by SilverFire** [comment]
I guess this issue may be related to [Request::trustedHosts](http://www.yiiframework.com/doc-2.0/yii-web-request.html#$trustedHosts-detail) configuration

**Comment by cebe** [comment]
> I has update to version 2.0.13 and Url::base() not return https, only http but my website use https

see https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012

**Comment by samdark** [comment]
@ducquan135 do you have PHP server behind a proxy?

**Comment by ducquan135** [comment]
Yes, i use nginx as reverse proxy, code run on apache

**Comment by samdark** [comment]
Then you should adjust configs as noted in UPGRADE.

**Comment by ducquan135** [comment]
thank you, sorry for not reading the note carefully
