### ISSUE TITLE
Yii 2.0.13 Gii broken for MSSQL

### ISSUE THREAD

**Issue by kevm256** [yiisoft/yii2#15108]
### What steps will reproduce the problem?
Go to gii model generator. Enter name of table in MSSQL database.
Click preview. 

### What is the expected result?
Preview of model is generated.

### What do you get instead?
Error:
SQLSTATE[42S02]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid object name 'pg_namespace'.
The SQL being executed was: SELECT ns.nspname AS schema_name
FROM pg_namespace ns
WHERE ns.nspname != 'information_schema' AND ns.nspname NOT LIKE 'pg_%'
ORDER BY ns.nspname

### Additional info

This appears to be an issue with protected function findSchemaNames(): https://github.com/yiisoft/yii2/blob/d0bf3cfeb4813cefbaa2e3ac0b6cbf0cbfa931c0/framework/db/mssql/Schema.php#L122-L129

As mssql doesn't doesn't store schemas in pg_namespace. The query should probably be using sys.schemas or INFORMATION_SCHEMA.SCHEMATA

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1.1
| Operating system |Windows Server 2012 R2

**Comment by sergeymakinen** [comment]
Okay, it should be fine as soon as #15111 lands.

**Comment by rafey022** [comment]
I am unable to view tables for MSSQL. Although I have added it in my config file
