### ISSUE TITLE
Swiftmailer not send mail gets Not Acceptable (#406)

### ISSUE THREAD

**Issue by mavs1971** [yiisoft/yii2#15109]
i have a app that send recorerypassword mail to client, when they forgot . i was working fine, but last week it´s start to throw a exception #406.

logs file have 
exception 'yii\web\NotAcceptableHttpException' with message '......' in \yii2-user\models\AccountRecoverPasswordForm.php:51
Stack trace:
#0 \yii2-user\controllers\RecoveryController.php(54): 
\user\models\AccountRecoverPasswordForm->recoverPassword()
#1 [internal function]:RecoveryController->actionRecoverPassword()
#2 D:\matarile\clubs\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#3 D:\matarile\clubs\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#4 D:\matarile\clubs\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('recover-passwor...', Array)
#5 D:\matarile\clubs\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('user/recovery/r...', Array)
#6 D:\matarile\clubs\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 D:\matarile\clubs\index.php(18): yii\base\Application->run()
#8 {main}

the line that send the exception it´s 

try {
				// Send Welcome Message to activate the account
				Mailer::sendRecoveryMessage($user);
			} catch (\Swift_TransportException $e) {
				throw new NotAcceptableHttpException("..... " 
		    				. Yii::$app->config->get('movil', 'administrador'));
			}

the rutine it´s

protected function sendMail($to, $subject, $view, $params = [])
		{
			$parametros = Configuration::getParam();

			if ($parametros['useTransport']==true) {
				$mailer           = Yii::$app->mail;
			} else {
				$mailer           = Yii::$app->mailer;
			}

                  
			$mailer->viewPath = '@abhimanyu/user/views/mail';

			return $mailer->compose(['html' => $view, 'text' => 'text/' . $view], $params)
				->setTo($to)
				->setFrom(Yii::$app->config->get('mail.username'), 'no@reply.com')
				->setSubject($subject)
				->send();
		}

please help... don´t kwon what happen

**Comment by mavs1971** [comment]
sorry the config file for  swiftmailer

 'mail' => 
    array (
      'class' => 'yii\\swiftmailer\\Mailer',
      'transport' => 
      array (
        'class' => 'Swift_SmtpTransport',
        'host' => 'smtp.gmail.com',
        'username' => 'wwwww@gmail.com',
        'password' => 'xxxxx',
        'port' => '465',
        'encryption' => 'ssl',
      ),
    ),

**Comment by cebe** [comment]
you should log the details of what is in `$e`, the `\Swift_TransportException` it should show you the cause of the error.
