### ISSUE TITLE
Yii2 DI Container didn't set property of object.

### ISSUE THREAD

**Issue by sjacobi** [yiisoft/yii2#15110]
### What steps will reproduce the problem?

i registered 3 components through "DI":

1)
```
$container->set('cocktail', [
    'class' => 'app\components\Cocktail',
    'name'  => 'NewFruitCocktail',
]);
```

2)
`$container->set('app\components\Banana', ['quantity' => 100]);`

3)
```
$container->set('apple', [
    'class' => 'app\components\Apple',
    'quantity' => 200,
]);
```

after this i had set dependency through "__construct" in app\components\Cocktail

```
class Cocktail extends \yii\base\Component
{
    public $banana;
    public $apple;
    public $name = 'FruitCoctail';

    public function __construct (Banana $banana, Apple $apple, array $config = []) {

        $this->banana = $banana;
        $this->apple = $apple;

        parent::__construct($config);
    }

}
```

apple class of component

```
class Apple extends Component
{
    public $quantity = 20;

    public function __construct ($config = []) {

        parent::__construct($config);
    }

}
```

banana class of component

```
class Banana extends Component
{
    public $quantity = 10;

    public function __construct ($config = []) {

        parent::__construct($config);
    }

}
```

### What is the expected result?

after this i execute this code in my controller action:

$cocktail = Yii::$container->get('cocktail');
VarDumper::dump($cocktail,10,true);

and got the result

```
'app\\components\\Apple' app\components\Cocktail#1
(
    [banan] => app\components\Banan#2
    (
        [quantity] => 100
        [yii\base\Component:_events] => []
        [yii\base\Component:_behaviors] => null
    )
    [apple] => app\components\Apple#3
    (
        [quantity] => 20
        [yii\base\Component:_events] => []
        [yii\base\Component:_behaviors] => null
    )
    [name] => 'NewFruitCocktail'
    [yii\base\Component:_events] => []
    [yii\base\Component:_behaviors] => null
)
```

### What do you get instead?

i think that property of Apple component must be set to **200**, but i got **20** as in instance class, Apple component was initialisation via DI as name alias "Apple":

$container->set('apple', [
    'class' => 'app\components\Apple',
    'quantity' => 200,
]);

in this case it is not works. Why?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.0.8
| Operating system | mac os high sierra

**Comment by cebe** [comment]
could you come up with a failing unit test? Should be easy to create from the code you have here.

**Comment by SilverFire** [comment]
> i think that property of Apple component must be set to 200, but i got 20 as in instance class

No, it should not. Let me explain why.

When DIC looks for missing arguments for constructor:
```php
    public function __construct (Banana $banana, Apple $apple, array $config = []) {
```

It creates the following dependencies list:

- Object of class `app\components\Banana`
- Object of class `app\components\Apple`

Then it tries to find definitions for the dependencies simply calling `$this->get($className)`. For object of class `app\components\Banana`, you have set the definition to override defaults:

```php
$container->set('app\components\Banana', ['quantity' => 100]);
```

But for object of class `app\components\Apple` you did not. Instead you've created alias `apple` for class `app\components\Apple` with property `$quantity = 200`.

In case you do not want to change default quantity for all objects of class `app\components\Apple`, you went in the right direction, but missed one step: you should hint `Coctail` to use that specific `apple`.

```php
$container->set('cocktail', [
    'class' => 'app\components\Cocktail',
    'name'  => 'NewFruitCocktail',
], [1 => Instance::of('apple')]);
```
