### ISSUE TITLE
Yii::$container->set() config merge problem

### ISSUE THREAD

**Issue by one-more-developer** [yiisoft/yii2#15125]
There is a `kartik\depdrop` widget for the example. It has no localization:
```
$loading = ArrayHelper::getValue($this->pluginOptions, 'loadingText', 'Loading ...');
```
To solve the problem I tried to use DI:
```
Yii::$container->set(\kartik\depdrop\DepDrop::class, [
	'pluginOptions' => [
		'loadingText' => 'Загрузка...',
	],
]);
```

However, to use the widget, you must specify pluginOptions like this:
```
$form->field($model, 'attribute_id')->widget(DepDrop::class, [
	'data' => $someData,
	'pluginOptions' => [
		'depends' => ['depend_id'],
		'url' => 'some_url_to_fetch'
	]
])
```
The configuration is merged with array_merge:
https://github.com/yiisoft/yii2/blob/d0bf3cfeb4813cefbaa2e3ac0b6cbf0cbfa931c0/framework/di/Container.php#L168

And as a result, the use of `Yii::$container->set()` for set `loadingText` inside `pluginOptions` is not effective.
To solve the problem, need to replace `array_merge()` with `ArrayHelper::merge()`.

Or how to solve this problem?

**Comment by rob006** [comment]
Duplicates #14821
