### ISSUE TITLE
Ability to translate SQL expressions between SQL servers

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#15126]
\yii\db\Expression is not SQL agnostic, so you can not write portable code between SQL servers.

If \yii\db\Expression could translate expressions, you could write 

	'value' => new \yii\db\Expression('NOW()'),

and it would be translated into 

       'value' => new \yii\db\Expression('DATETIME(\'NOW\', \'localtime\')'),

when the SQL server is sqlite3

Another option would be to change it when doing the real select, but that would be more complicated.

### What steps will reproduce the problem?

Attach the timestamp behavior to a model like this:

```
	public function behaviors()
	{
		$behaviors = [
		'timestamp' => [
				'class' => TimestampBehavior::className(),
				'createdAtAttribute' => 'created_at',
				'updatedAtAttribute' => 'updated_at',
				'value' => new \yii\db\Expression('NOW()'),
			],
		];
		return $behaviors;
```

And save a new model.

### What is the expected result?

The model is saved regardless of the SQL server.

### What do you get instead?

If the SQL server is Sqlite3, an error complaining that the NOW() function does not exist.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13-dev
| PHP version      | 7.0 
| Operating system |

**Comment by samdark** [comment]
There are hundreds SQL functions so I doubt we'll be able to support it properly.

**Comment by santilin** [comment]
Can the AttributeBehavior know the connection of the parent active record? Maybe it is something to add to the timestamp behavior

**Comment by samdark** [comment]
Yes. Behavior knows everything about AR it's attached to.

**Comment by samdark** [comment]
Closing since it would require too much effort and is not in line with current goals of the framework.
