### ISSUE TITLE
Possible issue with asset publishing

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#15121]
See https://github.com/yiisoft/yii2/issues/14913#issuecomment-342638973

**Comment by samdark** [comment]
Command is this one: https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/AssetController.php#L188

**Comment by samdark** [comment]
@ogheo I'm having trouble reproducing the problem without more details:

1. How does your `assets.php` config file that is used for `asset/compress` look like?
2. How does your `assetManager` section in regular web application config look like?
3. How does your asset bundle look like?

**Comment by ogheo** [comment]
> How does your assets.php config file that is used for asset/compress look like?

`
// In the console environment, some path aliases may not exist. Please define these:
// Yii::setAlias('@webroot', __DIR__ . '/../web');
// Yii::setAlias('@web', '/');

return [
    // Adjust command/callback for JavaScript files compressing:
    'jsCompressor' => 'java -jar frontend/assets/compress/tools/compiler.jar --js {from} --js_output_file {to}',
    // Adjust command/callback for CSS files compressing:
    'cssCompressor' => 'java -jar frontend/assets/compress/tools/yuicompressor.jar --type css {from} -o {to}',
    // The list of asset bundles to compress:
    'bundles' => [
        'frontend\assets\AppAsset',
        'frontend\assets\LazyLoadAsset'
    ],
    // Asset bundle for compression output:
    'targets' => [
        'frontend\\assets\\AllAsset' => [
            'class' => 'yii\web\AssetBundle',
            'basePath' => '@webroot/assets',
            'baseUrl' => '@web/assets',
            'js' => 'all-{hash}.js',
            'css' => 'all-{hash}.css',
        ],
    ],
    // Asset manager configuration:
    'assetManager' => [
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
    ],
];
`

**Comment by ogheo** [comment]
Here is a screen:

![project1](https://user-images.githubusercontent.com/6599359/32747906-0e230662-c8c3-11e7-815b-84e65ed919ba.jpg)

**Comment by samdark** [comment]
I've reproduced it. The issue is with configuration. You have `linkAssets` turned on in web application config but have it turned off in assets command config so hashes generated are different. In order to solve it make sure asset manager configs are identical.

**Comment by samdark** [comment]
Added that to UPGRADE guide: https://github.com/yiisoft/yii2/commit/abe47ca0a34264ff1fa734ff083a1166df018837
