### ISSUE TITLE
Feature: JsExpresion need append params

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#15131]
```php
//this is feature similar like a strtr function:
$je = new JsExpression("function(e){ 
    var calendarColors = :calendar_colors;
    return calendarColors[0]; 
}", ['calendar_colors'=>ArrayHelper::getColumn(CalColors::find()->all(), 'color')]);

```

**Comment by exru** [comment]
@samdark хотелось бы, чтобы можно было прикреплять параметры к js выражения, как например это сделано в AR, например ...->where('user_id = :user_id', ['user_id'=>25]). Очень часто приходится, экспортировать массивы и было бы не плохо задавать переменные в таком ключе. Плюс подсветка синтаксиса на уровне php, а это экономия времени.

**Comment by samdark** [comment]
strtr или sprintf помогут. Вообще это плохая практика так переменные передавать, так что я не уверен, стоит ли делать чтобы это было легко.

**Comment by exru** [comment]
@samdark Ну, тогда по желанию. Думаю опыта больше в этом вопросе.
