### ISSUE TITLE
not possible to extend core - class not found

### ISSUE THREAD

**Issue by gomonkey** [yiisoft/yii2#15137]
Hello I would like to extends BaseHtml.

I follow this [tutorial](http://www.yiiframework.com/doc-2.0/guide-helper-overview.html#customizing-helper-classes)

From tutorial:

> To customize a core helper class (e.g. yii\helpers\ArrayHelper), you should create a new class extending from the helpers corresponding base class (e.g. yii\helpers\BaseArrayHelper) and name your class the same as the corresponding concrete class (e.g. yii\helpers\ArrayHelper), including its namespace. This class will then be set up to replace the original implementation of the framework.

I try it by myself and was not work.

and of course I added the next line in entry script like explained in tutorial

```php
Yii::$classMap['yii\helpers\BaseHtml'] = '@common/components/Html.php';
```
 Then I just copyed and pasted the code that I Found in Helpers/html.php
```php
namespace yii\helpers;

/**
 * Html provides a set of static methods for generating commonly used HTML tags.
 *
 * Nearly all of the methods in this class allow setting additional html attributes for the html
 * tags they generate. You can specify, for example, `class`, `style` or `id` for an html element
 * using the `$options` parameter. See the documentation of the [[tag()]] method for more details.
 *
 * For more details and usage information on Html, see the [guide article on html helpers](guide:helper-html).
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class Html extends BaseHtml
{
}
```

That code is suppost to work but **Class 'yii\helpers\BaseHtml' not found**

**update**

I discovered just now that the error is not anymore in my onw class but in `vendor/yiisoft/yii2/helpers/Html.php` and I don't know how to go back 

It is a bug ?

Thanks in advance

**Comment by samdark** [comment]
It's not. Override Html, not BaseHtml.

**Comment by gomonkey** [comment]
I delete it my class and now is not find the original class from Helpers.

It is give me the same error, that is not find `yii\helpers\BaseHtml` but from `vendor/yiisoft/yii2/helpers/Html.php`

And yes, I have the class BaseHtml in helpers

**Comment by samdark** [comment]
```php
Yii::$classMap['yii\helpers\Html'] = '@common/components/Html.php';
```

**Comment by gomonkey** [comment]
I went back with the code, I delete the class in components and now have problem to find BaseHtml.
It is possible that something was automatically change it ? I am use phpStorm

**Comment by gomonkey** [comment]
I found the problem, maybe was PhpStorm when i did it refactoring of file.
was change line n. 190 in classes.php
`'yii\helpers\BaseHtml' => YII2_PATH . '/helpers/Html.php',`
I changed in
`'yii\helpers\BaseHtml' => YII2_PATH . '/helpers/BaseHtml.php',`

Thank you
