### ISSUE TITLE
PHP error in logger while formatting timestamp for output

### ISSUE THREAD

**Issue by Stevad** [yiisoft/yii2#15149]
You do not check situations when float timestamp value can be without microseconds (for example when log item was added at 123456.0000000)

### What steps will reproduce the problem?

1) Configure logger with flush interval = 1 and export interval = 1
2) Run next code 

```php
    $iter = 1000000;
    while ($iter-- > 0) {
        \Yii::warning('New log message');
    }
```

### What is the expected result?

Correct work without issues

### What do you get instead?

PHP undefined index in next line in Yii's `log/Target.php`:

```php
list($timestamp, $usec) = explode('.', StringHelper::floatToString($timestamp));
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1.11
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
#15081

**Comment by Stevad** [comment]
Oh, sorry. A was tried to find issue before writing this. Thank you for reply!

**Comment by samdark** [comment]
Hopefully we'll fix two more bugs and release soon. Meanwhile you can either try master or rollback to 2.0.12.
