### ISSUE TITLE
Failing tests for `DateValidator` with ICU tzdata 2017c

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#15140]
I'm not sure is it related to Yii itself or not.

### What steps will reproduce the problem?

0. Catch the fact that built-in ICU tzdata became outdated. Same timestamp with specific time zone produce different output between intl and native PHP's TZ handling.
1. Update ICU tzdata to latest [2017c](http://source.icu-project.org/repos/icu/data/trunk/tzdata/icunew/2017c/44/le/) according to [ICU manual](http://userguide.icu-project.org/datetime/timezone#TOC-Updating-the-Time-Zone-Data) linked from [Yii guide](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#setup-environment). Same things are described [here (ru)](https://habrahabr.ru/post/254789/).
2. Run Yii2 tests for validators.

### What is the expected result?

Tests passed.

### What do you get instead?

```
There were 3 failures:

1) yiiunit\framework\validators\DateValidatorTest::testIntlValidationWithTime with data set #0 ('UTC')
Failed asserting that false is true.

.../tests/framework/validators/DateValidatorTest.php:318
.../vendor/phpunit/phpunit/phpunit:52

2) yiiunit\framework\validators\DateValidatorTest::testIntlValidationWithTime with data set #1 ('Europe/Berlin')
Failed asserting that false is true.

.../tests/framework/validators/DateValidatorTest.php:318
.../vendor/phpunit/phpunit/phpunit:52

3) yiiunit\framework\validators\DateValidatorTest::testIntlValidationWithTime with data set #2 ('America/Jamaica')
Failed asserting that false is true.

.../tests/framework/validators/DateValidatorTest.php:318
.../vendor/phpunit/phpunit/phpunit:52

FAILURES!
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.0.22-0ubuntu0.16.04.1
| Operating system | Ubuntu
| libicu55 | 55.1-7ubuntu0.3

**Comment by schmunk42** [comment]
Related: https://github.com/yiisoft/yii2/issues/13750

**Comment by schmunk42** [comment]
The data format has slightly changed, I think. I just debugged this on PHP 7.2.

When changing the failing lines to:

    $this->assertTrue($val->validate('31/05/2017, 12:30'));
    $this->assertTrue($val->validate('31.05.2017, 12:30'));

Tests pass, I found this by using the formatter.
