### ISSUE TITLE
Sqlite database is created with wrong permissions

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#15148]
When you create a new sqlite3 database, it is created by the user running the yii2 application. If you create the database via the web server, you get
```
-rw-r--r-- 1 www-data www-data mydb.sqlite3
```
Later on, when you want to run migrations, you get 

```
    [2] => attempt to write a readonly database
```

The issue would be fixed if the database was created with rw-rw-rw- permissions or with a group that both the server and the cli can write to.

**Comment by cebe** [comment]
This is nothing that can be influenced from the framework, you have to set the permission and umask in dependent on your environment.
