### ISSUE TITLE
Url::current(['Orders' => ['status_id' => null]]) removes not only status_id

### ISSUE THREAD

**Issue by posterx** [yiisoft/yii2#15142]
If you want to unset only one nested get param like this `Url::current([$model->formName() => ['status_id' => null]])` it will remove all params that were in $_GET under $model->formName()
May be it will be better to use array_replace_recursive instead of array_replace?

### Additional info

| Yii version      | 2.0.13
| PHP version      | 5.6.15
| Operating system | windows 8

**Comment by 4meck** [comment]
тоже попал на это..
 
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseUrl.php#L432
- $route = array_replace($currentParams, $params);
+ $route = array_replace_recursive($currentParams, $params);
