### ISSUE TITLE
ActiveQuery Object different result if i break in two line

### ISSUE THREAD

**Issue by Lordfef** [yiisoft/yii2#15164]
Hi all, i don't know if it's my error (probably) or a bug or whatelse.
I have this code:

```
                $ass = Assortimenti::find()
                    ->where("id_vet=$id_vet")
                    ->andWhere("id_pro=".$pro->id_pro)
                    ->andWhere("state<>'ANN'");
                $ass->orderBy("id DESC")->all();

```
that give me a different result from this code:

```
                $ass = Assortimenti::find()
                    ->where("id_vet=$id_vet")
                    ->andWhere("id_pro=".$pro->id_pro)
                    ->andWhere("state<>'ANN'")
                    ->orderBy("id DESC")
                    ->all();

```
the second example give me what i need (an array object of my model), the first give me a yii\db\ActiveQuery Object incomplete

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  5.5.30 build 9200 (Windows 8 Professional Edition) i586 
| Operating system | Windows 10 Pro x64

**Comment by jakim** [comment]
Change first query to this:

```
$ass = Assortimenti::find()
             ->where("id_vet=$id_vet")
             ->andWhere("id_pro=".$pro->id_pro)
             ->andWhere("state<>'ANN'");
$ass = $ass->orderBy("id DESC")->all();
```

Now it's the same.

**Comment by cebe** [comment]
> ->andWhere("id_pro=".$pro->id_pro)

you should avoid this as it could introduce SQL incjection issue, use one of the following instead:

```php
->andWhere(["id_pro" => $pro->id_pro]) // array syntax
->andWhere("id_pro=:id_pro", ['id_pro' => $pro->id_pro]) // param binding
```
