### ISSUE TITLE
Translating a string with a parameter as NULL not working correctly

### ISSUE THREAD

**Issue by tuuling** [yiisoft/yii2#15169]
### What steps will reproduce the problem?

`
echo \Yii::t('main', '{gender} {firstname},', ['gender' => null, 'firstname' => 'Vadim']);
echo \Yii::t('main', '{gender, select, female{Уважаемая} other{Уважаемый}} {firstname},', ['gender' => null, 'firstname' => 'Vadim']);`

### What is the expected result?
`Vadim, Уважаемый Vadim,`

### What do you get instead?

`Vadim,{gender, select, female{Уважаемая} other{Уважаемый}'} Vadim,`

### Additional info

The first translate example show how a parameter with a value of NULL should be handled. In that case the placeholder is left empty.

In the second example multiple things seem to be wrong:

First of all the gender placeholder is not handled correctly. This can be fixed by giving the gender parameter a value that is not NULL. In my case I can set the default value to be "male". But it seems obvious that in case of NULL value it should use the "other" placeholder.

Second of all there seems to be an extra single quotation mark in the placeholder.
I traced it to: i18n/MessageFormatter.php:99
` $pattern = $this->replaceNamedArguments($pattern, $params, $newParams);`
It seems get confused when two curly braces are next to each other. If I were to write 
`echo \Yii::t('main', '{gender, select, female{Уважаемая} other{Уважаемый} } {firstname},', ['gender' => null, 'firstname' => 'Vadim']);` 
I get 
`{gender, select, female{Уважаемая} other{Уважаемый} } Vadim,`
The single quote is missing, but it is still not translated. I could keep the space and set the value of "gender" to something not NULL and it will work.

A possible fix would be to user "array_key_exists" instead of "isset" in: i18n/MessageFormatter.php:219
`if (isset($givenParams[$param])) {` ?

Not sure about the extra single quote

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.12-1~dotdeb+8.1
| Operating system | MacOSX running Vagrant

**Comment by SilverFire** [comment]
Resolved by #15452
