### ISSUE TITLE
Fix MariaDB 10.2 current_timestamp()

### ISSUE THREAD

**Issue by yaBliznyk** [yiisoft/yii2#15167]
Same issue like this https://github.com/yiisoft/yii/issues/4179
I dont known how fix it in Yii2)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 7+
| Operating system | any

**Comment by cebe** [comment]
https://github.com/yiisoft/yii/pull/4180

**Comment by schmunk42** [comment]
Error confirmed in build https://gitlab.com/yiisoft/yii2/-/jobs/42584302

**Comment by acs-ferreira** [comment]
Should be fixed by https://github.com/yiisoft/yii2/pull/16408
