### ISSUE TITLE
Pagination harcode pageLimit

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#15178]
### What steps will reproduce the problem?
I extend yii2/framework/data/Pagination.php

    public function setPageSize($value, $validatePageSize = false)
    {
        if ($value === null) {
            parent::setPageSize($value, $validatePageSize);
        } else {
            $value = (int)$value;

            $page = (int) $this->getQueryParam($this->pageParam, 1);
            if ($this->totalCount && $this->pageSize * $page > (int) $this->totalCount) {
                $page -= 1;
                $value = $this->totalCount - $this->pageSize * $page;
            }
            parent::setPageSize($value, false); //in this code I redefined number of model 
        }
    }

### What is the expected result?
 "perPage": 3
I wonna more control for default parameter  "perPage" and separate from $value from setPageSize

### What do you get instead?
3 - default
2 - custom
 "perPage": 2 not 3 as default

but for perPage should remain 3

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.1
| Operating system | ubuntu

**Comment by cebe** [comment]
> if (!in_array($value, $this->getPageSizeLimit())) {

what is `getPageSizeLimit()`, what does it do?

> $this->pageSize = $value;

this looks like a recursive call of the setter, or have you defined the property?

what exactly is the bug/problem in the framework. I do not get it, please explain in more detail.

**Comment by des1roer** [comment]
when I need to limit the sample, I set the parameter pageSize, but the parameter perPage also changed

**Comment by des1roer** [comment]
strong connectivity of parameters

**Comment by cebe** [comment]
`$pageSize` is the name of the poperty for the number of items per page. `per-page` is the name of the URL parameter that controls `$pageSize`. They are the same.
