### ISSUE TITLE
Migrations: allow to redo certain migration

### ISSUE THREAD

**Issue by ilyachase** [yiisoft/yii2#15174]
Or may be add 'do' action?
There are some situations when you want to redo only certain migration(s), not "last n migrations".
For now only way is to edit migrations you don't want to do (for example 'return' from them).

**Comment by samdark** [comment]
I don't think it's a good idea to support it. If migration was pushed and worked no changes should be ever made to it.

Additionally, you can do it now with `mark/down 1/up 1/mark` commands.
