### ISSUE TITLE
Problem with callable `indexBy` on relation query

### ISSUE THREAD

**Issue by vuongminh** [yiisoft/yii2#15183]
### What steps will reproduce the problem?
Execute query:

```
<?php
$downloadPages = Guest::invoke()->getDownloadPages(DownloadPage::class)->joinWith([
     'linkInfo' => function ($query) use ($linkInfo) {
          $query->andOnCondition([
              '{{link_info}}.[[id]]' => ArrayHelper::getColumn($linkInfo, 'id')
          ]);
      }])->indexBy(function (DownloadPage $model) {
      // it is a lazy loading not eager
     return $model->linkInfo->link_code;
})->all();
```

In callable use relation `linkInfo` with N queries.

### What is the expected result?

Get `linkInfo` relation with `eager loading`

### What do you get instead?

Get `linkInfo` relation with `lazy loading`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13

**Comment by Alex-Code** [comment]
Tricky one.
Indexing is done before relations are found so the relation in the callable is treated as lazy.

Only way I can see is to index it yourself after you have all records.

**Comment by cebe** [comment]
duplicate of https://github.com/yiisoft/yii2/issues/9342
