### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by GabyCheng** [yiisoft/yii2#15187]
### What steps will reproduce the problem?

I  use DetailView::INPUT_CHECKBOX_LIST Do a multi-check box

Here's the code

 [
    'attribute' =>'info_type1',
    'labelColOptions'=>['style'=>'width:11%'],
    'type'=>DetailView::INPUT_CHECKBOX_LIST,
    'items'=>$model->getCarInfo(1),
   ]
,
In the controller That's what it's worth

$model->info_type1 = array(1,2)

### What is the expected result?

I'm Do multiple check boxes, and I want him to do that by default, because it's a multi-check box, I want to pass the array, so that it can be checked by default, but it's wrong to pass the array to DetailView
Here is the wrong information:

htmlspecialchars() expects parameter 1 to be string, array given

with ActiveForm It is ok to but DetaileView This one is wrong

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by cebe** [comment]
>  'type'=>DetailView::INPUT_CHECKBOX_LIST,

this functionality is not part of Yii framework. We do not provide an option to format rows as input fields.
