### ISSUE TITLE
Cannot route /echo (yii refuses...)

### ISSUE THREAD

**Issue by RickKukiela** [yiisoft/yii2#15182]
I'm using craft3 which uses yii2 routing and I'm trying to set up a route for `www.example.com/echo` and it wont work. If I change the word to anything else besides `echo` it works fine.

### What steps will reproduce the problem?
```
        Event::on(
            UrlManager::class,
            UrlManager::EVENT_REGISTER_SITE_URL_RULES,
            function (RegisterUrlRulesEvent $event) {
                $event->rules['echo'] = 'site-dom-injector/default/index';
                $event->rules['test'] = 'site-dom-injector/default/index';
            }
        );
```

### What is the expected result?

Both /echo and /test should display the controller output.

### What do you get instead?

Only /test displays controller output, /echo returns a 404 exception.

### Additional info

| Q                | A
| ---------------- | ---
Apache/2.4.23 (Win32) PHP/7.1.0
Yii Framework/2.0.13.1

**Comment by samdark** [comment]
I think it's better to ask it in Craft Slack channel since routing in Craft, while based on Yii, is a bit different.
