### ISSUE TITLE
GridView filtering

### ISSUE THREAD

**Issue by rymkapro** [yiisoft/yii2#15188]
Hi!
I'm getting error after Chrome update. When i filter GridView which is wrapper by Pjax, i get a jquery error "Form submission canceled because the form is not connected"
I tried to change yii.GridView.js (just for interest), and chaged var $form = ....... .appendTo($grid) in line ~159 by $form = ....... .appendTo($('#my_pjax_container_id')), and error disappeared and everything works fine.
But it is not good to change smth in vendor :)

### What steps will reproduce the problem?
Described above

### What is the expected result?
Described above

### What do you get instead?
Described above

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |  7.0
| Operating system | Windows 10

**Comment by samdark** [comment]
@rymka1989 would you please provide a bit more info about reproducing the issue? Yii version, some code, how you wrap it with PJAX etc. Thanks.

**Comment by rymka1989** [comment]
Hi!
Yii 2.0.13.1

PJAX in layout

        <div class="content-wrapper">
        <?php
        Pjax::begin([
            'id' => 'content-wrapper-pjax',
            'timeout' => Yii::$app->params['pjax']['timeout'],
            'scrollTo' => 0
        ]);
        
        echo $content;
        
        Pjax::end();
        ?>
        </div>



CONTROLLER ACTION
public function actionIndex() {
        $filter_model = new CardsModel();
        $data_provider = $filter_model->getDataProvider(\Yii::$app->request->queryParams);
        $specialities = SpecialityRecord::find()->orderBy(['name' => SORT_ASC])->all();

        if (\Yii::$app->request->isAjax) {
            return $this->renderAjax('list', compact('filter_model', 'data_provider', 'specialities'));
        }
        return $this->render('list', compact('filter_model', 'data_provider', 'specialities'));
    }


GRIDVIEW in TEMPLATE
<div class="table-responsive">
    			<?php
    			echo GridView::widget([
    			    'id' => 'cards-grid',
    			    'filterModel' => $filter_model,
    			    'dataProvider' => $data_provider,
    			    'tableOptions' => [
    			        'class' => 'table table-bordered table-condensed table-hover',
    			        'style' => 'font-size: 0.9em;'
    			    ],
    			    'columns' => [
    			        [
    			            'attribute' => 'timestamp',
    			            'headerOptions' => [
    			                'style' => 'width: 80px;'
    			            ],
    			            'filter' => Html::activeInput('date', $filter_model, 'timestamp', ['class' => 'form-control']),
    			            'content' => function($model, $key, $index, $column) {
    			                return Yii::$app->formatter->asDatetime($model->timestamp);
    			            }
    			        ],
    			        [
    			            'attribute' => 'last_name',
    			            'label' => 'ФИО'
    			        ],
    			        [
    			            'attribute' => 'nationality'
    			        ],
    			        [
    			            'attribute' => 'specialities',
    			            'header' => 'Специальности',
    			            'filter' => Html::activeDropDownList($filter_model, 'specialities', ArrayHelper::map($specialities, 'id', 'name'), ['prompt' => 'Все', 'class' => 'form-control']),
    			            'content' => function($model, $key, $index, $column) {
    			                $specialities = [];
        			            foreach ($model->specialitiesConns as $conn) {
        			                $specialities[] = $conn->speciality->name;
        			            }
        			            
        			            return implode('<br>', $specialities);
    			            }
    			        ],
    			        [
    			            'attribute' => 'experience',
    			            'headerOptions' => [
    			                'style' => 'width: 60px;'
    			            ],
    			            'contentOptions' => [
    			                'class' => 'text-center'
    			            ]
    			        ],
    			        [
    			            'attribute' => 'email'
    			        ],
    			        [
    			            'attribute' => 'step',
    			            'headerOptions' => [
    			                'style' => 'width: 60px;'
    			            ],
    			            'contentOptions' => [
    			                'class' => 'text-center'
    			            ]
    			        ],
    			        [
    			            'attribute' => 'completed',
    			            'filter' => Html::activeDropDownList($filter_model, 'completed', [0 => 'Нет', 1 => 'Да'], ['prompt' => 'Все', 'class' => 'form-control']),
    			            'content' => function($model, $key, $index, $column) {
    			                return $model->completed ? 'Да' : 'Нет';
    			            },
    			            'contentOptions' => [
    			                'class' => 'text-center'
    			            ]
    			        ],
    			        [
    			            'attribute' => 'score',
    			            'headerOptions' => [
    			                'style' => 'width: 50px;'
    			            ],
    			            'contentOptions' => [
    			                'class' => 'text-center'
    			            ]
    			        ],
    			        [
    			            'class' => 'yii\grid\ActionColumn',
    			            'header' => '&nbsp;',
    			            'headerOptions' => [
    			                'style' => 'width: 50px;'
    			            ],
    			            'contentOptions' => [
    			                'class' => 'text-center'
    			            ],
    			            'template' => '{view} {print}',
    			            'buttons' => [
                                'view' => function($url, $model) {
                                    return Html::a(Html::tag('span', NULL, ['class' => 'glyphicon glyphicon-eye-open']), Url::toRoute('/card/cards/view?id=' . $model->id));
                                },
                                'print' => function($url, $model) {
                                    return Html::a(Html::tag('span', NULL, ['class' => 'glyphicon glyphicon-print']), Url::toRoute('/card/cards/print?id=' . $model->id), ['data-pjax' => 0, 'target' => '_blank']);
                                }
                            ]
                        ]
    			    ]
    			]);
    			?>
			</div>


Можно и на русском, если будет удобнее :)

**Comment by s1lver** [comment]
@rymka1989 Привет! Ошибка сохраняется в 2.0.16? 
Дело в том, что я сталкивался с этой проблемой в 2.0.15, но посчитал это проблемой реализации взаимодействия с моим кодом(сейчас работает как предполагается). 
Возможно проблема не актуальна, надо проверить, возможно вы подтвердите или опровергните наличие ошибки быстрее.

**Comment by zumek** [comment]
Hello, I was experiencing this same issue with Yii 2.0.15. The solution that worked for me was to put the widget creation code between the Pjax begin and end tags. i.e. not creating the widget in a file/variable outside the begin and end tags, as below - 

```
    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => new Program()
    ]); ?>

    <?php Pjax::end(); ?>
```

If I were to do the following, it would error -


```
    <?php 
    $grid = GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => new Program()
    ]); 
    ?>

    <?php Pjax::begin(); ?>

    <?= $grid; ?>

    <?php Pjax::end(); ?>
```

Perhaps @samdark may have some insight as to why that would be the case? Thank you.
