### ISSUE TITLE
Moving between fields does not highlight field content

### ISSUE THREAD

**Issue by yadelius** [yiisoft/yii2#15184]
### What steps will reproduce the problem?
When I move control to another field with tab-key, the cursor moves at the end, so I must use backspace to delete the field content or use mouse to highlight it.
Forms with lots of fields takes long time to edit.

### What is the expected result?
Usually when moving from a field to another with tab-key, the field content (if present) is highlighted and pressing a key the content of the field is replaced with the key value.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13-dev
| PHP version      | 5.6.30
| Operating system | windows 10/debian 8

**Comment by Renkas** [comment]
How is this a yii issue? Seems to be an issue on your frontend. You can build your frontend in any way you want. Yii is a backend framework!

**Comment by TerraSkye** [comment]
The issue isnt related to yii. But fyi this should work

```$("input").on ("focus",function (){
$(this).select ()
})
```

**Comment by TerraSkye** [comment]
The issue isnt related to yii. But fyi this should work

```
$("input").on ("focus",function (){
$(this).select ()
})
```

**Comment by Renkas** [comment]
Why are you using jQuery to mimic default behaviour in browsers? 

And in a issue of backend framework ...

**Comment by TerraSkye** [comment]
@Renkas  i missread the issue, on click it doesnt select all the contect directly. therefor i posted the solution. but in any way it is not related to Yii itself.

**Comment by cebe** [comment]
@Renkas yii has frontend components so it could be considered an issue with ActiveFrom. But I also think this should be solved in custom application javascript as proposed by @TerraSkye .
