### ISSUE TITLE
Pjax not working, reloads the entire page even though timeout is set with bigger value

### ISSUE THREAD

**Issue by m26404020** [yiisoft/yii2#15198]
I have this list view and pjax:

`Pjax::begin(['id' => 'alga-list-pjax', 'timeout' => '30000', 'enablePushState' => false, 'clientOptions' => ['method' => 'POST']]);`
`	echo ListView::widget([`
`		'dataProvider' => $model->search(Yii::$app->request->queryParams),`
`		'itemOptions' => ['class' => 'alga-item'],`
`		'layout' => "{items}",`
`		'itemView' => '_alga',`
`		'id' => 'alga-list-container',`
`		'pager' => [`
`			'prevPageLabel' => 'Prev',`
`			'nextPageLabel' => 'Next',`
`			'maxButtonCount' => 5,`
`		],`
`	]) ;`
`Pjax::end();`

It doesn't work, the whole page is reloaded. I check Chrome's network tab and found out that the status is cancelled.

**Comment by schmunk42** [comment]
Do you have a redirect or error in the response? Does the reloaded page contain the code you've expected?

**Comment by dynasource** [comment]
if it reloads the page, then you've got an error in your software. Look in your debug report for the answer.
