### ISSUE TITLE
Do we need file glossary.md?

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2#15196]
There is a file [glossary.md](https://github.com/yiisoft/yii2/blob/master/docs/guide/glossary.md) in the documentation.

But I only found one usage of it: https://github.com/yiisoft/yii2/blob/master/docs/guide-zh-CN/README.md

Do we really need file `glossary.md`?

**Comment by cebe** [comment]
There was an idea to explain terms in Yii context in that file. It was not finished, but I still think it is a good idea.
