### ISSUE TITLE
Get full URL

### ISSUE THREAD

**Issue by rahulmishra1991** [yiisoft/yii2#15205]
### What steps will reproduce the problem?
https://www.example.com/#gifts
This is my demo URL and i need to find #gifts i didn't get from $_SERVER or if i am trying with jQuery it's not exploding please help me for the same.
### What is the expected result?
$a[0]= https://www.example.com;
$a[10]=/#gifts;
### What do you get instead?

$a[0]=https://www.example.com/#gifts;
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.?
| PHP version      | 5.4
| Operating system |

**Comment by samdark** [comment]
That is normal. Browsers aren't sending to the server according to HTML standatds.
