### ISSUE TITLE
Controllers in sub folders is not visable in list commands

### ISSUE THREAD

**Issue by johndoejdg** [yiisoft/yii2#15200]
### What steps will reproduce the problem?
- cd to project folder 
- Create test folder: mkdir ./commands/test
- Create test controller in that folder ./commands/test/TestController.php:
```
<?php

namespace app\commands\test;

use yii\console\Controller;

class TestController extends Controller
{
    public function actionDo()
    {

    }
}
```
- Run yii command to see all commands: ./yii

### What is the expected result?
See test command in list
Working autocomplete
 
### What do you get instead?
Test command do not exist in list of command but callable
./yii test/test/do
And autocomplete does not suggest commands in subfolders

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.13.1
| PHP version      |  7.1.11
| Operating system |  Linux 4.13.12-1

**Comment by dmirogin** [comment]
I think worth trying controllerMap
