### ISSUE TITLE
yii migrate :  Error: Setting unknown property: yii\console\Request::cookieValidationKey

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#15209]
### What steps will reproduce the problem?
![image](https://user-images.githubusercontent.com/1888094/33167410-68332d1e-d078-11e7-9b4d-f65fe84bb1e1.png)

### What is the expected result?
我之前用 yii migrate  就直接可以把console/migrations/xxx.php  给弄到数据表里面了，但是现在不知道为什么一直报这个错

### What do you get instead?
![image](https://user-images.githubusercontent.com/1888094/33167410-68332d1e-d078-11e7-9b4d-f65fe84bb1e1.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.11
| Operating system | win10  64x

**Comment by error-500** [comment]
What the code in you migration?

**Comment by huaiguoguo** [comment]
i found the answer for the issue;
Beause  i  put the request component in common/config/main.php  and put  cookieValidationKey in the request component ;

i remove the cookieValidationKey from request component in common/config/main.php

But I don't think it's reasonable, please the official to redesign it

**Comment by bscheshirwork** [comment]
@huaiguoguo 
You use `request` component in console apps?
This make sense?
May be try set `config` with only to `web` apps `config`?

**Comment by cebe** [comment]
> May be try set config with only to web apps config?

thats the way to go, `yii\web\Request` does not make sense in console environment, there is `yii\console\Request` for that.

**Comment by bscheshirwork** [comment]
@huaiguoguo try to use
```
'request' => yii\helpers\UnsetArrayValue::class,
```
into your `console` config
