### ISSUE TITLE
can anyone tell why this kind param bind for where() not working? a bug?

### ISSUE THREAD

**Issue by 016** [yiisoft/yii2#15211]
Code:
$query = AdminUser::find()->where(['u_id'=>':uid'], [':uid'=>1])->orderBy('u_id Desc');

Error: 
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

Working one:
$query = AdminUser::find()->where('u_id = :uid', [':uid'=>1])->orderBy('u_id Desc');

anyone can tell me why the first one is not working? thx.

**Comment by Alex-Code** [comment]
If you have the `where` as an array it's treated as `column` = `value`.
So the SQL it would generate would be `WHERE u_id = ':uid'` not replacing any placeholders.

You only need, `$query = AdminUser::find()->where(['u_id'=>1])->orderBy('u_id Desc');`

**Comment by 016** [comment]
it's my fault, array don't need any param bind, case close.
