### ISSUE TITLE
Access `yii\rest\Serializer`'s requested fields within action

### ISSUE THREAD

**Issue by chervand** [yiisoft/yii2#15217]
Is there any proper way (or could be implemented) to access requested fields while action being executed without creating another instance of the serializer object? Now serializer instantiates in `yii\rest\Controller`'s `afterAction()`, so it's not accessible before this event. 

This could be handy for DB queries performance improvements, e.g. **eagerly loading related records requested via `$expandParam`**, which is configurable in `yii\rest\Serializer`.

 PS: I think it will help a lot esp. after https://github.com/yiisoft/yii2/pull/14219 merged.

**Comment by samdark** [comment]
@chervand would you please provide a few examples? Thanks.

**Comment by samdark** [comment]
Closing since no further info was provided.
