### ISSUE TITLE
Doctrine Issue after upgrading Yii2 - Ubuntu 14.04

### ISSUE THREAD

**Issue by deep12650** [yiisoft/yii2#15218]
After updating composer doctrine is giving following error:
`Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  7.1.1
| Operating system | Ubuntu 14.04

**Comment by Renkas** [comment]
How is this a Yii2 issue? Yii does not use Doctrine.

**Comment by deep12650** [comment]
It is using doctrine/lexer (See Attachment) with the latest update and It is used for Doctrine Annotations. I am getting this Type Error. Earlier it was working with the older version. 
So, I thought to put forward this issue here to be get rectified. I did 8-10 projects in Yii2 and I faced this issue the first time. Please suggest to solve it thanks. 

New Installation: 
![screen shot 2017-11-26 at 1 07 34 am](https://user-images.githubusercontent.com/12050549/33230357-f71a7b52-d246-11e7-9352-9ac4191bf36b.png)
My Current Project: 
![screen shot 2017-11-26 at 12 50 29 am](https://user-images.githubusercontent.com/12050549/33230358-009130ea-d247-11e7-8aef-d1d2fe91173f.png)

**Comment by samdark** [comment]
Closing since it's not Yii but Doctrine errors. Please report to Doctrine.

**Comment by deep12650** [comment]
I have found the issue which was related to Authorize.Net. I am closing it because it is not relevant here. As the issue is defined over here. [#issue](https://github.com/AuthorizeNet/sample-code-php/issues/99)
