### ISSUE TITLE
We need more translation for yiisoft/yii2/messages/vi/yii.php

### ISSUE THREAD

**Issue by hyquoccuong** [yiisoft/yii2#15237]
### What steps will reproduce the problem?

When I change yii application language to vi, and use 'compare' validation:

`[['newPassword' , 'newPasswordRepeat'], 'safe'],
            [
                'newPasswordRepeat', 'compare',
                'compareAttribute' => 'newPassword',
            ],`

I see this error message: 
_Lặp Lại Mật Khẩu Mới must be equal to "Mật Khẩu Mới"._
Here "must be equal to" is not translated.

When I check **yiisoft/yii2/messages/vi/yii.php**, there is no transaltion for 

` '{attribute} must be equal to "{compareValue}"`

### What is the expected result?

So please add this translation:
    `'{attribute} must be equal to "{compareValue}".' => '{attribute} phải bằng "{compareValue}"',`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.7
| Operating system | Windows 10

**Comment by Renkas** [comment]
@hyquoccuong You can always help by translating strings that need translation and create a PR so that it could be merged into the framework.

**Comment by samdark** [comment]
We don't know the language in question so can't really adjust it.

**Comment by hyquoccuong** [comment]
Could you please let me know where I can get list full of Yii system and error mesages for translation?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/translation-workflow.md
