### ISSUE TITLE
How about composer.lock?

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15230]
### What steps will reproduce the problem?
`composer install`

I can see in github yii2 repo tree page

```md
 	composer.json 	Allowed jQuery 3.2 in composer.json 	3 months ago
	composer.lock 	Make PHPUnit run on PHP 7.2 	4 months ago
```

### What is the expected result?
remove from repo/fresh version in repo

### What do you get instead?
```sh
docker-compose -f ../yii2-phpunit-docker-composition.yml run --rm --entrypoint composer php install -vvv
...
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by schmunk42** [comment]
If there is a `.lock` file it should be up-to-date IMHO. Although it's debatable if it makes sense for the framework itself.
I prefer having a lock-file, since it speeds up build times for automated testing, but on the other hand it's hard to maintain separate lock-files for ie. PHP 5 and 7.

**Comment by SilverFire** [comment]
Yes, the lockfile is mainly used by Travis to speedup builds. I don't think we should drop it. I'd rather update it in 2.1

**Comment by schmunk42** [comment]
> Yes, the lockfile is mainly used by Travis to speedup builds.

If we want to "test a `composer update`", using asset-packagist would greatly help here.

> I don't think we should drop it. I'd rather update it in 2.1

I think it should always be up-to-date, if there's a change in `composer.json` there's no reason to use an outdated lock file.

**Comment by bscheshirwork** [comment]
> I think it should always be up-to-date, if there's a change in composer.json there's no reason to use an outdated lock file.

:+1:

**Comment by cebe** [comment]
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

this should definitively be fixed, but lock file should be kept in the repo to speed up CI.
