### ISSUE TITLE
can we replace bower assets with npm ways to install?

### ISSUE THREAD

**Issue by videni** [yiisoft/yii2#15240]
bower asset is very slow in China.

**Comment by samdark** [comment]
Have you tried replacing these with npm? Is it faster?

**Comment by xutl** [comment]
你可以镜像asset-packagist.org来加速。阿里OSS 腾讯的COS都可以镜像，而且还支持Https

**Comment by samdark** [comment]
I don't think we can affect it much from our side. Mirroring asset-packagist could be a good idea especially considering the fact that it's source code is open.

**Comment by videni** [comment]
@xutl , thank you so much, very good to know.
