### ISSUE TITLE
Data is truncated when trying to write to varbinary(max) MS SQL Server

### ISSUE THREAD

**Issue by VladlinMoiseenko** [yiisoft/yii2#15245]
Sorry for my English

I write to the model with:

`base64_encode(file_get_contents($file->tempName));`

I expect to see a long line in the database, and when you save, get the source file with:

`sendContentAsFile(base64_decode($model->file), $model->file_name);`

I see in the field (varbinary(max)) 62 characters regardless of the file,
and when saving I always get a file of size 45 bytes

And with nvarchar(max) works always correctly.

I need only use varbinary(max), since the partner has already done a lot for this.

What's my mistake?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  5.6
| Operating system |  MS SQL Server

**Comment by Alex-Code** [comment]
Try converting the base64 string to binary.
http://php.net/manual/en/language.types.type-juggling.php#language.types.typecasting

or not converting it at all and just using `file_get_contents()`

**Comment by VladlinMoiseenko** [comment]
@Alex-Code Thanks for the answer

typecasting (binary) did not help

but without base64 I get an error:

> Database Exception - yii \ db \ Exception 
> An error occurred translating string for input param 1 to UCS-2

there are still thoughts?

**Comment by Renkas** [comment]
base64 is not binary!!!! It's a string.

Convert string to binary in SQL: 
https://docs.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql#converting-binary-and-varbinary-data

**Comment by VladlinMoiseenko** [comment]
@Renkas thanks for the answer

unless this code should not convert:

```
    // @see https://github.com/yiisoft/yii2/issues/12599
    if (isset($columnSchemas[$name]) && $columnSchemas[$name]->type === Schema::TYPE_BINARY && $columnSchemas[$name]->dbType === 'varbinary' && is_string($value)) {
        $phName = self::PARAM_PREFIX . count($params);
        $columns[$name] = new Expression("CONVERT(VARBINARY, $phName)", [$phName => $value]);
    }
```
from a file  `\vendor\yiisoft\yii2\db\mssql\QueryBuilder.php`

**Comment by VladlinMoiseenko** [comment]
@samdark может Вы подскажете?

**Comment by SaWey** [comment]
The problem is 
`CONVERT(VARBINARY, $phName)`
will trim to 30 characters, you have to explicitly set it to MAX
```php
$phName = $this->bindParam($value, $params);
$columns[$name] = new Expression("CONVERT(VARBINARY(MAX), $phName)", $params);
```

**Comment by samdark** [comment]
@darkdef checked it. Not an issue in master.
