### ISSUE TITLE
File input forces uploading file with every update. even thumb image value available but it gives error to thumb image is required.

### ISSUE THREAD

**Issue by nageennayak11** [yiisoft/yii2#15242]
model code :- [['thumbnail_image'], 'required', 'message' => 'Please upload an image.'],

form code :- 
$form->field($model, 'thumbnail_image')->fileInput(['accept' => 'image/*', 'onchange' => 'readURL(this)'])->label('Thumbnail Image', ['class' => 'control-label thumbnail-image-class'])

File input forces uploading 

file with every update. even thumb image value available but it gives error to thumb image is required.
-

**Comment by nageennayak11** [comment]
when I create a new record or change the attribute in update it works correctly. However when I update the record without changing the file attribute I get a javascript error 'thumb image is required' despite the file is already saved and I don't want to update it

**Comment by samdark** [comment]
Please provide code and steps to reproduce it starting with clean basic app. Thanks.

**Comment by Alex-Code** [comment]
You can use the `when` and `whenClient` options.

```php
[['attribute'], 'required', 'when' => function($model) {
  return $model->isNewRecord;
}, 'whenClient' => '() => { return !/\?id=\d+/i.test(document.location.href); }' ],
```

For server side we can check if the record is new `$model->isNewRecord`.
Client side depends on how you track records, the example above will check the url for an `id` query string, if one doesn't exist the rule applies.

**Comment by nageennayak11** [comment]
Yes its work,
thank you so much.
