### ISSUE TITLE
Why Inflector::slug in Yii2 generates wrong latin string from cyrillic?

### ISSUE THREAD

**Issue by fridary** [yiisoft/yii2#15256]
`Inflector::slug` in `Yii2` generates not correct string from cyrillic. 

Example: `автоматизация` -> `avtomatizacia`, but it must be `avtomatizaciya`; `зачислить` -> `zacislit`, but it must be `zachislit`. How to fix it?

This tool is correct https://you.tools/slugify/

I use this for SEO urls. Can this influence if search engines will not recognise the correct keyword to improve SEO results for my website?

**Comment by samdark** [comment]
Yii uses transliteration for all languages via PHP's intl. You can affect results via configuring it: https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseInflector.php#L290. Not sure how much SEO is affected though.
