### ISSUE TITLE
nodejs tests failed

### ISSUE THREAD

**Issue by dmirogin** [yiisoft/yii2#15250]
https://travis-ci.org/yiisoft/yii2/jobs/308484311
after this commit https://github.com/yiisoft/yii2/commit/7d19fce050c172c4dd0ab291f21879de246654eb

**Comment by bscheshirwork** [comment]
I can see it on 2 my latest PR

**Comment by dmirogin** [comment]
resolved by https://github.com/yiisoft/yii2/commit/1330ca9ec166d02ba1a881f1d9bdc78270743524
