### ISSUE TITLE
User "Can" when is guest

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#15267]
### What steps will reproduce the problem?
When user is guest
```
Yii::$app->getUser()->can('addDiary', ['permission' => function () {
    if (!Yii::$app->getUser()->getIsGuest()) {
        return Yii::$app->getUser()->getIdentity()->getPermission()->one();
    }
    return null;
}])
```
### What is the expected result?
Return 'false' and execute rule.
### What do you get instead?
Return 'false' but doesn't execute rule.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1
| Operating system | win10

**Comment by samdark** [comment]
Why should it execute the rule if the result is false?

**Comment by RSalo** [comment]
If we have to make some more additional checks, we need to do this in every "can", otherway we can do this in the rule. But, maybe i'm wrong...

**Comment by samdark** [comment]
If we know for sure that `can()` failed before checking the rule then checking the rules does not make sense.

**Comment by RSalo** [comment]
It's make sense for me.
