### ISSUE TITLE
Small fix

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2#15263]
https://github.com/yiisoft/yii2/blob/9a16f8fecc21e72173b1633075bd45048ad0c3aa/framework/helpers/BaseJson.php#L172

Here if (is_array($data)) change to elseif (is_array($data)), save a time is_array check.

**Comment by samdark** [comment]
It's not called thousands of times to fix it but since you've found it feel free to make a pull request. Thanks.

**Comment by MysteryDragon** [comment]
Fix is not correct. See line 156, 158.

**Comment by njasm** [comment]
indeed, this change changed behavior of the method.
This change probably introduced a bug when object is SimpleXMLElement.

**Comment by MysteryDragon** [comment]
@hiscaler @samdark so is this issue still actual?

**Comment by hiscaler** [comment]
@MysteryDragon I'm ill-considered.

**Comment by samdark** [comment]
Closing since it changes behavior as @MysteryDragon pointed out.
