### ISSUE TITLE
SQL Server max 2100 bind parameters

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#15262]
This problem has been discussed before, but it is still there and no decision has been made on it in the past. It bothers me constantly since to work it around I had to break ORM rules in ActiveRecord classes and avoid using ORM relations, so I thought I should bring it to discussions once again along with some thoughts on the potential fix.

The problem is that according to [this resource](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server) Microsoft SQL Server has a limit on the number of bind variables present in a single SQL statement - no more than 2100. If we go over that, we are hit with

```2017-11-30 11:33:13 [10.162.0.163][fbestand][o3ic1obtrcvm8532582r2urq84][error][yii\db\Exception] PDOException: SQLSTATE[IMSSP]: Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters. in C:\inetpub\wwwroot\vendor\yiisoft\yii2\db\Command.php:1032
Stack trace:
#0 C:\inetpub\wwwroot\vendor\yiisoft\yii2\db\Command.php(1032): PDOStatement->execute()
#1 C:\inetpub\wwwroot\vendor\yiisoft\yii2\db\Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#2 C:\inetpub\wwwroot\vendor\yiisoft\yii2\db\Query.php(214): yii\db\Command->queryAll()
#3 C:\inetpub\wwwroot\vendor\yiisoft\yii2\db\ActiveQuery.php(135): yii\db\Query->all(NULL)
#4 C:\inetpub\wwwroot\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(158): yii\db\ActiveQuery->all()
#5 C:\inetpub\wwwroot\vendor\yiisoft\yii2\db\BaseActiveRecord.php(288): yii\db\ActiveQuery->findFor('events', Object(dryu\nova\db\SupportTicket))
...
Next yii\db\Exception: SQLSTATE[IMSSP]: Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters.
The SQL being executed was: SELECT * FROM Events WHERE id IN (<... long list of ids ...>)
```

From ORM side it is reproduced like that: I have a "SupportTicket" model, which have a "Events" model related to it via an extra table "SupportTicketEvents":

```Support Ticket --> SupportTicketEvents --> Events```

Usually, we have around 10-200 events in the support ticket, but on a rare occasion support ticket events run over 2100, and this is the time where I cannot use ```$ticket->events``` as that will trigger the above error from SQL Server driver.

I currently work around that by avoiding using the ORM relation ```$ticket->events```, resolving this in runtime using ```Event::find()->innerJoinWith(["ticket"], false)->where(...)->all()``` where needed, but this does not allow re-usage of those ticket events via a handy relation, so I have to run SQL queries everywhere I need to access events, which degrades the performance and eliminates the benefits of having ORM relations via ActiveRecord functionality.

I tried to use ```PDO::ATTR_EMULATE_PREPARES => true``` but it has no effect on the issue.

The only way to work this around I can think of is to flatten SQL query if the parameters run over 2100, and do not use bind variables in those queries. SQL Server runs those flattened queries just fine with thousands of parameters, so we just need to avoid using bind variables, or allow user to provide a driver configuration

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.0
| Operating system | Windows 2012

**Comment by samdark** [comment]
Yes, it may make sense to use non-prepared statements in this case.

**Comment by SilverFire** [comment]
Duplicates #10371

**Comment by dryu** [comment]
As I was saying, we discussed this issue before. Nobody is doing anything about it though for years already. 

We need to agree on the solution and put this one on the roadmap. 

-A
