### ISSUE TITLE
PostgreSQL > 10.0 is not pass tests with default value of timestamp CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15265]
### What steps will reproduce the problem?
run PHPUnit test with [this](https://github.com/yiisoft/yii2/pull/15244#issue-277698421) config

```yml
  pgsql:
    image: postgres:10.1
```
and `postgres:10.0`

run tests 
```sh
vendor/bin/phpunit --filter testColumnSchema tests/framework/db/pgsql/SchemaTest.php
```

### What is the expected result?
no F in output

### What do you get instead?
```sh
$ docker-compose -f ../yii2-phpunit-docker-composition.yml run --rm --entrypoint bash php
root@6dc97aa7b2cd:/var/www/html# vendor/bin/phpunit --filter testColumnSchema tests/framework/db/pgsql/SchemaTest.php
PHPUnit 4.8.34 by Sebastian Bergmann and contributors.

F.

Time: 545 ms, Memory: 6.00MB

There was 1 failure:

1) yiiunit\framework\db\pgsql\SchemaTest::testColumnSchema
defaultValue of column ts_default is expected to be an object but it is not.
Failed asserting that 'CURRENT_TIMESTAMP' is of type "object".

/var/www/html/tests/framework/db/SchemaTest.php:485
/var/www/html/vendor/phpunit/phpunit/phpunit:52

FAILURES!
Tests: 2, Assertions: 142, Failures: 1.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14-dev
| PHP version      | 7.1.12
| Operating system | Debian (Docker)

**Comment by schmunk42** [comment]
@bscheshirwork Could you verify this again, I can't see this bug anymore with `10.1` - see also https://gitlab.com/yiisoft/yii2/-/jobs/49522413

**Comment by bscheshirwork** [comment]
@schmunk42 @samdark 
 on master I can see previous errors.
```sh
vendor/bin/phpunit --filter testColumnSchema tests/framework/db/pgsql/SchemaTest.php
PHPUnit 4.8.34 by Sebastian Bergmann and contributors.

F.

Time: 661 ms, Memory: 6.00MB

There was 1 failure:

1) yiiunit\framework\db\pgsql\SchemaTest::testColumnSchema
defaultValue of column smallint_col does not match.
Failed asserting that '1' is identical to 1.

/var/www/html/tests/framework/db/SchemaTest.php:488
/var/www/html/vendor/phpunit/phpunit/phpunit:52

FAILURES!
Tests: 2, Assertions: 32, Failures: 1.

```


 Try with half-patch...

**Comment by bscheshirwork** [comment]
error still alive
```php
vendor/bin/phpunit --filter testColumnSchema tests/framework/db/pgsql/SchemaTest.php
PHPUnit 4.8.34 by Sebastian Bergmann and contributors.

F.

Time: 644 ms, Memory: 6.00MB

There was 1 failure:

1) yiiunit\framework\db\pgsql\SchemaTest::testColumnSchema
defaultValue of column ts_default is expected to be an object but it is not.
Failed asserting that 'CURRENT_TIMESTAMP' is of type "object".

/var/www/html/tests/framework/db/SchemaTest.php:485
/var/www/html/vendor/phpunit/phpunit/phpunit:52

FAILURES!
Tests: 2, Assertions: 142, Failures: 1.

```

**Comment by GHopperMSK** [comment]
Why can't we just adapt the tests to new conditions? Something like this:

https://github.com/GHopperMSK/yii2/blob/bc60a40d0df3794501b2488dfb72d039e51d3f7b/tests/framework/db/SchemaTest.php#L495-L542

Should we have separate tests for Postgres 9.x and Postgres 10.x versions?

**Comment by batyrmastyr** [comment]
Maybe it's better to make `Expression` from any not null `defaultValue` on `date/time` columns?

**Comment by samdark** [comment]
@batyrmastyr wouldn't that be unexpected behavior?

**Comment by batyrmastyr** [comment]
@samdark for some people - definetly. But I hope there are not so many ones with `defaultValue='2019-10-16'` or any other constant date or time.

On the other hand, Yii has  [`ActiveRecord::loadDefaultValues`](https://github.com/yiisoft/yii2/blob/74c6797a4113f972a69aa30b36d1d0f3db7f9d5c/framework/db/ActiveRecord.php#L116) and code like `$model->loadDefaultValues(); $model->save();` is not expected to throw "ERROR:  invalid input syntax for type date: "CURRENT_TIMESTAMP"". Currently [`now()`](https://github.com/yiisoft/yii2/blob/74c6797a4113f972a69aa30b36d1d0f3db7f9d5c/framework/db/pgsql/Schema.php#L545) is converted to `Expression` and doesn't produce errors while usage of [13 other](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT) standard functions leads to an exception on insert. Checking all of them is not a big deal, just a bit lengthy and makes wonder "what do we do with [MariaDB's](https://mariadb.com/kb/en/library/create-table/#invisible) 'NOW() + INTERVAL 1 YEAR'?".

**Comment by samdark** [comment]
Right. Then your solution makes sense.

**Comment by terabytesoftw** [comment]
This problem is still present in pgsql v. 10.14, what would be the best way to solve it?

**Comment by samdark** [comment]
This: https://github.com/yiisoft/yii2/issues/15265#issuecomment-542075469

**Comment by terabytesoftw** [comment]
Why not use now as the default value in:

https://github.com/yiisoft/yii2/blob/38b1eb2c3e4681a4a45b757a861197a3e3366596/tests/data/postgres.sql#L146

There is no difference between using NOW () or CURRENT_TIMESTAMP and our tests do not fail on either version.

https://dba.stackexchange.com/questions/63548/difference-between-now-and-current-timestamp

**Comment by samdark** [comment]
We can do it or we can list all other standard functions in there as @batyrmastyr noted.

**Comment by terabytesoftw** [comment]
In my opinion it is better to use NOW (), since I do not modify the behavior of the tests.

**Comment by samdark** [comment]
OK, let's do it.

**Comment by terabytesoftw** [comment]
We have two solutions:

1.- Change default in postgres.sql:

```php
ts_default TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  => ts_default TIMESTAMP NOT NULL NOW()
```

2.- Make the schema return the expression for `NOW()` and `CURRENT_TIMESTAMP` timestamp functions:

```php
if (
    $column->getType() === 'timestamp' &&
    ($column->getDefaultValue() === 'now()' || $column->getDefaultValue() === 'CURRENT_TIMESTAMP')
) {
    $column->defaultValue(new Expression($column->getDefaultValue()));
```

Both solutions pass the tests.

**Comment by samdark** [comment]
I like 2nd solution more.

**Comment by bscheshirwork** [comment]
```
$column->defaultValue === 'now()'
```
what about all possible case?
```
$column->defaultValue === 'NOW()'
```

**Comment by terabytesoftw** [comment]
> ```
> $column->defaultValue === 'now()'
> ```
> 
> what about all possible case?
> 
> ```
> $column->defaultValue === 'NOW()'
> ```

Fixed.
