### ISSUE TITLE
Warning [validator.w3.org]:  The type attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by lomion69** [yiisoft/yii2#15272]
### What steps will reproduce the problem?
https://validator.w3.org/nu/?doc=https%3A%2F%2Fsko4.com%2Fevents%2Fvero--igor-glushko-at-port

### What is the expected result?
no warnins

### What do you get instead?
Warning [validator.w3.org]:  The type attribute is unnecessary for JavaScript resources.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | Yii version 2.0.14-dev
| PHP version      |  PHP 5.6.30-0+deb8u1
| Operating system | 2.6.32-openvz-042stab125.3-amd64 GNU/Linux

**Comment by bscheshirwork** [comment]
You tell about use `<script>` instead of `<script type="text/javascript">`?

**Comment by miniBB** [comment]
I could confirm this appears when <script type="text/javascript"> is used.
