### ISSUE TITLE
Dynamic Model and StringValidator

### ISSUE THREAD

**Issue by igortsev** [yiisoft/yii2#15275]
### What steps will reproduce the problem?

Make demo code

```php

$testModel = new \yii\base\DynamicModel(['test']);
$testModel->addRule('test', 'string');

$form = ActiveForm::begin();

 $form->field($testModel, 'test')->textInput()

 ActiveForm::end(); 
```

### What is the expected result?
Digits is't validate data

### What do you get instead?
String validator doesn't work dinamic model

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.1
| Operating system | Windows OpenServer

**Comment by igortsev** [comment]
https://yadi.sk/i/fd5NlG1k3QFXZN

**Comment by Alex-Code** [comment]
According to your picture it does work.
Any value from an `<input/>` will be treated as a string.

If you want to exclude numbers use the [RegularExpressionValidator](http://www.yiiframework.com/doc-2.0/yii-validators-regularexpressionvalidator.html#)
