### ISSUE TITLE
How to selectively output the log?

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2#15284]
I am not referring to the distinction between log levels, this is easy.

I want to specify the log output, only the output of the log records in their own code, do not want to log Yii2 framework also exported, which made me very troubling when checking the log.

This requirement is normal and reasonable, Log4J in the Java language will be able to achieve this selective output, I am eager to Yii2 can do it.

**Comment by samdark** [comment]
Check categories description and filtering in the guide.
