### ISSUE TITLE
use yield response Invalid Parameter – yii\base\InvalidParamException

### ISSUE THREAD

**Issue by danielesk** [yiisoft/yii2#15283]
### What steps will reproduce the problem?
in controller

$a = yield XxxxxxxxxChildList::findOne(['status'=>2]);
 
### What do you get instead?

Invalid Parameter – yii\base\InvalidParamException

Response content must be a string or an object implementing __toString().

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | advanced  2.0.10
| PHP version      |  PHP 7.0.18 (cli) ( ZTS )
| Operating system | windows 7 x64

**Comment by samdark** [comment]
What do you want to achieve with yield in action?

**Comment by Danielesk** [comment]
@samdark 

Mainly to save memory, according to business logic to process data

**Comment by samdark** [comment]
So what do you expect in this case when using yield? Should controller cause response to send data in chunks?

**Comment by kamarton** [comment]
yield + AR#findOne = totally meaningless
