### ISSUE TITLE
incorrect format `asTime` for postgres fields `timestamp with time zone`

### ISSUE THREAD

**Issue by goffyara** [yiisoft/yii2#15286]
### What steps will reproduce the problem?

formatter->defaultTimeZone = 'UTC'
formatter->timeZone = 'Etc/GMT-3'
formatter->timeFormat = 'php:H:i:s'

after version 2.0.11, incorrect format `asTime` for postgres fields `timestamp with time zone`
#13343
```php
$time = '16:22:00.44297+03';
echo Yii::$app->formatter->asTime($time);
````
### What is the expected result?
'16:22:00'
### What do you get instead?
'13:22:00'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.0.*
| Operating system | ubuntu 16.04

**Comment by schmunk42** [comment]
Did you use `formatter->defaultTimeZone === 'UTC'` (which would just return `true`) or `formatter->defaultTimeZone = 'UTC'`?

**Comment by goffyara** [comment]
fixed. Copypaste from 13343. Sorry.

**Comment by schmunk42** [comment]
Which PostgreSQL version do you use? Is this related to https://github.com/yiisoft/yii2/issues/15265?

**Comment by goffyara** [comment]
PostgreSQL version 9.6.6. But It seems to be the problem of Formatter after #13343.
