### ISSUE TITLE
Can't set email filename via fileTransportCallback in Acceptance Test

### ISSUE THREAD

**Issue by fwerner13** [yiisoft/yii2#15299]
### What steps will reproduce the problem?

In the acceptance test: 

```php
        Yii::$app->mailer->fileTransportCallback = function ($mailer, $message) {
            return 'test-message.eml';
        };
```

### What is the expected result?

That the generated email file is named `test-message.eml`.

### What do you get instead?

The file is named with a timestamp: `20171205-144101-8131-3147.eml`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1
| Operating system | Debian GNU/Linux 8 (jessie)

**Comment by bscheshirwork** [comment]
@fwerner13 try to [use this codeception Helper](https://github.com/bscheshirwork/yii2-app-advanced/blob/690a85e0797018f485fa97f874c04d51fe0ee0a1/frontend/tests/_support/Helper/Functional.php)
https://github.com/bscheshirwork/yii2-app-advanced/blob/690a85e0797018f485fa97f874c04d51fe0ee0a1/frontend/tests/_support/Helper/Functional.php#L22-L31

[configure bootstrap](https://github.com/bscheshirwork/yii2-app-advanced/blob/690a85e0797018f485fa97f874c04d51fe0ee0a1/frontend/tests/_bootstrap.php)
https://github.com/bscheshirwork/yii2-app-advanced/blob/690a85e0797018f485fa97f874c04d51fe0ee0a1/frontend/tests/_bootstrap.php#L12

and try to apply it after change in your mailer.
```php
        Yii::$app->mailer->fileTransportCallback = function ($mailer, $message) {
            return 'test-message.eml';
        };
        $I->configureMailer();
```
https://github.com/bscheshirwork/yii2-app-advanced/blob/690a85e0797018f485fa97f874c04d51fe0ee0a1/frontend/tests/functional/ContactFailCest.php#L12-L13
