### ISSUE TITLE
ActiveQuery builds duplicate joins without aliases

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#15290]
There is something fishy going on in ```ActiveQuery::buildJoinWith``` method. I can see it adds duplicate joins that do not have any aliases assigned, resulting in some queries with complicated joins fail to execute.

### What steps will reproduce the problem?
I have the following joins I want to add to an instance of active query:

```php
$relations = ["owner R1", "owner.manager R2"];
foreach ($relations as $relation) $query->joinWith([$relation]);
```

The expectation is to have all joins with their respective unique aliases.

### What is the expected result?
I expect to see 2 joins in the query:
```sql
SELECT * FROM Ticket T
    LEFT JOIN Owner R1 ON T.owner_id = R1.id
    LEFT JOIN Manager R2 ON R1.manager_id = R2.id
```
The expectation is for the framework to actually re-use the "owner" relation defined with an alias in subsequent relation processing, e.g. relation ```["owner R1"]``` should be the same as "owner" part in the next relation: ```["owner.manager R2"]```.

### What do you get instead?
I see 3 joins in the query:
```sql
SELECT * FROM Ticket T
    LEFT JOIN Owner R1 ON T.owner_id = R1.id
    LEFT JOIN Owner ON T.owner_id = Owner.id // <-- this one is a duplicate of a previous join
    LEFT JOIN Manager R2 ON R1.manager_id = R2.id
```
### Additional info
With simple query like above, MSSQL actually executes the query no questions asked, e.g. it sees a duplicate joins and ignores those. However, if we have those duplicate joins exposed on deeper relationship level other than the very first level, then MSSQL will error out:
```
SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The objects "Manager" and "Manager" in the FROM clause have the same exposed names. Use correlation names to distinguish them.
```

Looking at the framework code, there exists a logic that should filter out duplicate joins in ```ActiveQuery::buildJoinWith```

```php
        // remove duplicated joins added by joinWithRelations that may be added
        // e.g. when joining a relation and a via relation at the same time
        $uniqueJoins = [];
        foreach ($this->join as $j) {
            $uniqueJoins[serialize($j)] = $j;
        }
        $this->join = array_values($uniqueJoins);
```

But since we used an alias to modify the first relation, serialize() will produce different results for aliased and non-aliased relation, and relation will not be re-used, resulting in a duplicate join.

I'm not sure how to work this one around.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.0
| Operating system | Windows 2008

**Comment by dryu** [comment]
Actually, found a workaround as this case works:

```php
$query->joinWith(["owner R1", "owner.manager R2"]);
```
E.g. the first relation is re-used in the second relation.

This case does not work:

```php
$relations = ["owner R1", "owner.manager R2"];
foreach ($relations as $relation) $query->joinWith([$relation]);
```

E.g. the first relation is not re-used.

**Comment by bscheshirwork** [comment]
all is ok

```php
    public function testJoinWithAlias($aliasMethod)
    {
        $query = Order::find()->joinWith(['customer R1', 'customer.profile R2']);
        $raw = $query->createCommand()->getRawSql();
...
```
```
SELECT `order`.* FROM `order` LEFT JOIN `customer` `R1` ON `order`.`customer_id` = `R1`.`id` LEFT JOIN `profile` `R2` ON `R1`.`profile_id` = `R2`.`id`
```


this issue
```php
    public function testJoinWithAlias($aliasMethod)
    {
        $query = Order::find();
        foreach (['customer R1', 'customer.profile R2'] as $join){
            $query->joinWith([$join]);
        }
        $raw = $query->createCommand()->getRawSql();
...
```
```
SELECT `order`.* FROM `order` LEFT JOIN `customer` `R1` ON `order`.`customer_id` = `R1`.`id` LEFT JOIN `customer` ON `order`.`customer_id` = `customer`.`id` LEFT JOIN `profile` `R2` ON `customer`.`profile_id` = `R2`.`id`
```
same
```php
    public function testJoinWithAlias($aliasMethod)
    {
        $query = Order::find();
        foreach (['customer R1', 'customer.profile R2'] as $join){
            $query->joinWith($join);
        }
        $raw = $query->createCommand()->getRawSql();
...
```
```
SELECT `order`.* FROM `order` LEFT JOIN `customer` `R1` ON `order`.`customer_id` = `R1`.`id` LEFT JOIN `customer` ON `order`.`customer_id` = `customer`.`id` LEFT JOIN `profile` `R2` ON `customer`.`profile_id` = `R2`.`id`
```

**Comment by bscheshirwork** [comment]
All is OK with this config:
```php
        foreach (['customer R1', ['customer R1', 'customer.profile R2']] as $join){
            $query->joinWith($join);
        }
        $raw = $query->createCommand()->getRawSql();
```
```sql
SELECT `order`.* FROM `order` LEFT JOIN `customer` `R1` ON `order`.`customer_id` = `R1`.`id` LEFT JOIN `profile` `R2` ON `R1`.`profile_id` = `R2`.`id`
```
i.e. 
@dryu 
You can tell joinWith about your previous use alias. You can set another alias if join same table multiple time. 

Your example is incorrect, use syntax with one-joinWith-all-aliases

**Comment by bscheshirwork** [comment]
Also I think we can resolve aliases in chain of relation:
```php
$query = Order::find();
$query->joinWith('customer R1');
$query->joinWith('R1.profile R2');
```
not implemented now
