### ISSUE TITLE
Not compatible date format with INTL formatter

### ISSUE THREAD

**Issue by Yiivgeny** [yiisoft/yii2#15298]
### What steps will reproduce the problem?
```php
echo \Yii::$app->getFormatter()->asDatetime('now', 'php:c'), PHP_EOL;
echo date_create('now')->format('c'), PHP_EOL;
```
### What is the expected result?
```
2017-12-05T14:01:18+03:00
2017-12-05T14:01:18+03:00
```
### What do you get instead?
```
2017-12-05T14:01:18
2017-12-05T14:01:18+03:00
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.1.12
| Operating system | CentOS 7
| ICU |  50.1.2

May be use another format for https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFormatConverter.php#L330? 
```php
echo \Yii::$app->getFormatter()->asDatetime('now', 'xx'), PHP_EOL; // Empty
echo \Yii::$app->getFormatter()->asDatetime('now', 'Z'), PHP_EOL; // +0300
```

**Comment by cebe** [comment]
Unable to reproduce this on PHP 7.0.3, ICU 52.1

**Comment by cebe** [comment]
> echo \Yii::$app->getFormatter()->asDatetime('now', 'xx'), PHP_EOL; // Empty

note that it should be `xxx` not `xx`.

**Comment by Yiivgeny** [comment]
@cebe empty result for all x-like expressions
http://userguide.icu-project.org/formatparse/datetime
