### ISSUE TITLE
Model (yii\base\Model) with UniqueValidator Error On Update

### ISSUE THREAD

**Issue by bahirul** [yiisoft/yii2#15303]
### What steps will reproduce the problem?

I'm using stand alone form (yii\base\Model) instead of ActiveRecord for CRUD operation.
When using unique validator, set targetClass and targetAttribute to ActiveRecord Class.
When create new record, it work as expected. But when im update the record it reproduce error _**{attribute} has already been taken**_

### What is the expected result?

Skip validation when value attribute same as value on targetClass attribute.

### What do you get instead?

error _**{attribute} has already been taken**_

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.0.25
| Operating system | Xubuntu 16.04

**Comment by MysteryDragon** [comment]
@bahirul maybe I'm wrong, but this assertion will not work, actually:
> Skip validation when value attribute same as value on targetClass attribute.

Because in other case there will be no so many sense in such validator.

Maybe you just forget about explaining to validator, how to filter validation check? Because basically such model will not know about AR details, and it's make sense to filter by AR primary key, don't you think so?
In such case something like that may help (for example):
```
[
    ['username'],
    'unique',
    'filter' => function ($query) {
        $query->andWhere(['!=', 'id', $this->user_id]);
    },
    'targetClass' => User::className(),
    'message' => 'Это имя пользователя уже занято.',
],
```

**Comment by bahirul** [comment]
This is my form class : 

`<?php
namespace mvc\models\form;

use yii\base\Model;

class NprServerLocationForm extends Model
{
	public $name;

	public $_ar;

	public function rules()
	{
		return [
			['name','required'],
			['name','unique', 'targetClass' => 'mvc\models\base\NprServerLocation', 'targetAttribute' => 'name'],
		];
	}
}`

My Action : 

        `
        //im using this for display current value om form
        $model = $this->findOne($id);

        $model_form = new NprServerLocationForm();

        //im using this for display current value om form
        $model_form->name = $model->name;

        $post = Yii::$app->request->post();

        if ($model_form->load($post) && $model_form->validate()) {
            
        }`

How to skip current value of $model_form->name if same record as $model->name.
Currently im using my custome validator for solving this.

**Comment by MysteryDragon** [comment]
@bahirul so looks like my advice fits perfectly.

**Comment by bahirul** [comment]
I try this but not work : 

`['name','unique', 'targetClass' => 'mvc\models\base\NprServerLocation', 'targetAttribute' => 'name','filter' => function ($query) {
        $query->andWhere(['!=', 'name', $this->name]);
    },],`

**Comment by MysteryDragon** [comment]
@bahirul of course it won't. Try `$query->andWhere(['!=', 'id', $this->_ar->id])` (replace `id` with your primary key name, and adjust `$this->_ar->id` if needed).

**Comment by bahirul** [comment]
@MysteryDragon it's make me sense, it work like my custome validator.

**Comment by bahirul** [comment]
@MysteryDragon i've try that but not work ... ummm
Have you try your solution ?

**Comment by MysteryDragon** [comment]
@bahirul yep, it works in some projects in organization where I work. In past times I make such mistakes as (probably) yours, even thought about creating an issue here, yes :smiley: 
But I read source code and found out my mistake. So, honestly now I'm pretty sure in this functional.

**Comment by bahirul** [comment]
@MysteryDragon i think, i need check if $model->_ar is new record or not at first, then i can check query after that : 
`
['name','unique', 'targetClass' => 'mvc\models\base\NprServerLocation', 'targetAttribute' => 'name','filter' => function ($query) {
        			if(!$this->_ar->getIsNewRecord()){
        				$query->andWhere(['!=', 'id', $this->_ar->id]);
        			}
    			}
    		],`

**Comment by MysteryDragon** [comment]
@bahirul 
You could do this for example. In my code it works by different scenarios in most times. Or you can use `andFilterWhere` instead of `andWhere`. I just propose solution for your problem in update case, not in every case :smiley:
If problems still exists for you, I can try to help you, but this is not place for Q&A.
Look, for example, here: https://github.com/yiisoft/yii2/issues/15284#issuecomment-348883198
I can propose gitter.
Github issues only for bugs, proposing new features and such other stuff.

**Comment by bahirul** [comment]
@MysteryDragon thanks, i'm going to close this issue.
