### ISSUE TITLE
Javascript error. Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by vitorarantes** [yiisoft/yii2#15300]
### What steps will reproduce the problem?

If we get an Exception and then we click on an empty tab (`<li>`), the following javascript error occurs... see images below:

<img width="1096" alt="error1" src="https://user-images.githubusercontent.com/2787948/33614312-4cc9c17e-d9d7-11e7-9d69-9c4897f443fd.PNG">

<img width="487" alt="error2" src="https://user-images.githubusercontent.com/2787948/33614319-543a4d2a-d9d7-11e7-848e-4d46a5d1cb54.PNG">

Fix: https://github.com/vitorarantes/yii2/commit/f08e3a5d543fdf9ff652233f2fcc7d5e50e9027e

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.1.12
| Operating system | Ubuntu 16.04

**Comment by MysteryDragon** [comment]
Looks like this error really can appears:

```
<?php

namespace app\controllers;

class TestController extends \yii\web\Controller
{
    die();
}
```

![screenshot_2017-12-06_10-41-41](https://user-images.githubusercontent.com/3968363/33650245-339a80a8-da72-11e7-8796-da8a99ddd90a.png)
![screenshot_2017-12-06_10-42-12](https://user-images.githubusercontent.com/3968363/33650246-3406efc2-da72-11e7-899b-b3573f5d7d80.png)

There aren't `code-wrap` in such steps.
Explains by
https://github.com/yiisoft/yii2/blob/master/framework/views/errorHandler/callStackItem.php#L31

**Comment by MysteryDragon** [comment]
Looks like this error really can appears:

```
<?php

namespace app\controllers;

class TestController extends \yii\web\Controller
{
    die();
}
```

![screenshot_2017-12-06_10-41-41](https://user-images.githubusercontent.com/3968363/33650492-46e08774-da73-11e7-8d9d-7a900238069b.png)
![screenshot_2017-12-06_10-42-12](https://user-images.githubusercontent.com/3968363/33650493-46fc650c-da73-11e7-9266-e483d87eae72.png)

There aren't `code-wrap` in such steps.
Explains by
https://github.com/yiisoft/yii2/blob/master/framework/views/errorHandler/callStackItem.php#L31
