### ISSUE TITLE
DbCache to a PostgreSQL database

### ISSUE THREAD

**Issue by edwards-sj** [yiisoft/yii2#15302]
### What steps will reproduce the problem?

Enable `DbCache` to a `PostgreSQL` database
Turn on `enableSchemaCache` in the database connection
 
### What is the expected result?

Yii2 will use the `cache` table to cache the results of its schema description queries. 

### What do you get instead?

`yii\base\ErrorException`
`unserialize() expects parameter 1 to be string, resource given`

### Additional info

The cache database uses `bytea` to store the values, when loading these from a query you get back a stream rather than a value.

The `getValue` method of `DbCache` uses `queryScalar` which automatically checks for a stream and calls `stream_get_contents`.

The `getValues` method does a `queryAll` which does not do the check, which means the return values are streams rather than the underlying data.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.7
| Operating system | Ubuntu

**Comment by schmunk42** [comment]
@edwards-sj With which Postgres version did you test this?

**Comment by bscheshirwork** [comment]
@edwards-sj try with 9.5...

**Comment by edwards-sj** [comment]
I'm using PostgreSQL 10.0
