### ISSUE TITLE
How do I get query parameters?

### ISSUE THREAD

**Issue by i-panov** [yiisoft/yii2#15305]
There are no ways to get the optional query parameters that are passed in the link. Even in `$ _GET` - empty.

### What steps will reproduce the problem?

rout: `'article/view/all' => 'article/view-all'`
action: `ArticleController::actionViewAll()`
url: `/article/view/all?sort=name`

```
Yii::$app->request->get();
Yii::$app->request->getQueryParams();
$_GET;
```

### What do you get instead?

Empty parameters in all cases.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 5.6.23
| Operating system | Windows 7

**Comment by samdark** [comment]
What's the URL?

**Comment by i-panov** [comment]
@samdark Я же написал "/article/view/all?sort=name".

**Comment by MysteryDragon** [comment]
@i-panov it looks like error in configuration maybe. Or in code. Just look into framework code: `$_GET` is never clears by framework.
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L273
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L616
It's the only places in whole framework when `$_GET` appears. So, the question is - who clear you `$_GET`?

**Comment by samdark** [comment]
So you aren't getting `sort` in `$_GET`? As @MysteryDragon said, Yii does nothing about that by itself.

**Comment by i-panov** [comment]
It seems the problem was in the incorrect configuration of .htaccess (although it was default, ie as it was originally in the framework). When I replaced RewriteRule ^(.*)$ /index.php?/$1 [L] by RewriteRule . index.php everything worked! And by the way, I finally got a debug-panel! I wrote about the problems with it in [this](https://github.com/yiisoft/yii2-debug/issues/289) request, but I did not decide, and finally it happened!

**Comment by smelike** [comment]
> It seems the problem was in the incorrect configuration of .htaccess (although it was default, ie as it was originally in the framework). When I replaced `RewriteRule ^(.*)$ /index.php?/$1 [L]` by `RewriteRule . index.php` everything worked! And by the way, I finally got a debug-panel! I wrote about the problems with it in [this](https://github.com/yiisoft/yii2-debug/issues/289) issue, but I did not decide, and finally it happened!

I met the same problem. Thank you for save my life and time.
```
> RewriteEngine On
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> #RewriteRule ^(.*)$ /index.php?/$1 [L]
> RewriteRule . index.php
```
