### ISSUE TITLE
please fixed the this code ArrayHelper::filter line 941

### ISSUE THREAD

**Issue by hhniao** [yiisoft/yii2#15301]
A small bug. when i write this : 
    `ArrayHelper::filter(['a'=>0],['a']);`
above code will return empty array to me.
i have check on the ArrayHelper::filter line 941
i saw this code:
   `if (empty($array[$globalKey])) {
                continue;
    }`
i think it modify to follow is better:
    `if (!key_exists($globalKey, $array)) {
                continue;
     }`

**Comment by samdark** [comment]
Indeed. @hhniao would you like to make a pull request with unit tests to verify it and a fix?
