### ISSUE TITLE
Add NotExists validator

### ISSUE THREAD

**Issue by ilyaplot** [yiisoft/yii2#15311]
I want to check is **not** exists relations for my model before update is_deleted attribute. 
I created NotExistsValidator extends ExistsValidator, but methods prepareConditions, getTargetClass and applyTableAlias is private. I had to copy them.

Please, add notExistsValidator or make methods of ExistsValidator protected.

Russian:
Продублирую мое сообщение на русском, т.к. я не уверен, что правильно смог объяснить суть на английском языке.

Для обновления аттрибута is_deleted (так я помечаю удаленные записи), я создал сценарий и мне необходимо было проверить отсутствие активных зависимостей для модели. Я думал, что могу просто наследовать ExistsValidator и переопределить метод validateAttribute. Всего-то надо было исправить 2 символа. Но мне пришлось скопировать приватные методы prepareConditions, getTargetClass и applyTableAlias. Это печально, потому что я не вижу острой необходимости делать эти методы приватными.

Пожалуйста, добавьте NotExists валидатор или измените приватность методов в ExistsValidator

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.0
| Operating system | Linux

**Comment by dmirogin** [comment]
uniqueValidator?

**Comment by developeruz** [comment]
Somehow related to #13675
