### ISSUE TITLE
Does `Console::wrapText()` display correctly on Windows?

### ISSUE THREAD

**Issue by MysteryDragon** [yiisoft/yii2#15315]
I suspect a bug here: https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseConsole.php#L696
It join lines by "\n", but for Windows it's "\r\n" AFAIK. So perhaps in Windows it not displays correctly. But I can't test it, too much work for preparing suitable environment.

Maybe someone could confirm or refute it? If it's a bug, I can make PR.

**Comment by samdark** [comment]
I have Windows. Will verify it.

**Comment by MysteryDragon** [comment]
@samdark thank you!

**Comment by samdark** [comment]
![cli_windows](https://user-images.githubusercontent.com/47294/33785672-29d04f60-dc77-11e7-839e-e2de35267cfb.png)
