### ISSUE TITLE
Data (rest) filter: \yii2\rest\IndexAction::prepareDataProvider() produced wrong SORT if $requestParams not set

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15339]
### What steps will reproduce the problem?

```php
class SomeRestController extends \yii\rest\ActiveController
{
...
    public function actions()
    {
        return [
            'index' => [
                'class' => 'yii\rest\IndexAction',
                'modelClass' => $this->modelClass,
                'dataFilter' => [
                    'class' => \yii\data\ActiveDataFilter::class,
                    'attributeMap' => [
                        'redefineId' => 'originId',
                    ],
                    'searchModel' => function () {
                        return (new \yii\base\DynamicModel(['id' => null, 'redefineId' => null,  'name' => null]))
                            ->addRule('id', 'integer')
                            ->addRule('formId', 'redefineId')
                            ->addRule('name', 'trim')
                            ->addRule('name', 'string');
                    },
                ],
            ],
...
```
send query like
```php
                /** @var \yii\httpclient\Response $response */
                $response = $client->createRequest()
                    ->setMethod('get')
                    ->setData(['filter' => ['redefineId' => $this->id]])
                    ->setUrl('some-rest/index')
                    ->send();
```

### What is the expected result?
result set will be order by PK
### What do you get instead?
order by first field in the filter `where` condition 

in
https://github.com/yiisoft/yii2/blob/d44d5540b1f58b92ac1f9c6ac1ffc0036970026a/framework/rest/IndexAction.php#L89-L129

See line 116 and line 126.

And another strange: In 119-128 we pass `$requestParams` with 'filter' key to 'pagination' and 'sort'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14-dev 6345766
| PHP version      |  7.2.0
| Operating system | alpine3.6

**Comment by klimov-paul** [comment]
Unable to reproduce.
Ordering is controller by `yii\data\Sort` instance, which is a part of `DataProvider`.
Unless `Sort::$sortParam` is not present inside the `$requestParams` no order will be applied.
Check your configuration for the `Sort` instance, e.g. `Sort::$defaultOrder` or something.

Also I can not understand how following part of your report code snippent can function:

```
->addRule('formId', 'redefineId')
```

as the second argument of the `DynamicModel::addRule()` should be a validator name - not attribute.

**Comment by bscheshirwork** [comment]
>Also I can not understand how following part of your report code snippent can function:
->addRule('formId', 'redefineId')
as the second argument of the DynamicModel::addRule() should be a validator name - not attribute.

So sorry, typo. I will change it in head message.
```php
->addRule('redefineId', 'integer')
```

@klimov-paul 
> Unless Sort::$sortParam is not present inside the $requestParams no order will be applied.

... and `db` engine will be sort the request by first column in `SELECT` or `WHERE` (if select is `*`). 
**First column may be not `PK` column**.

in case filtered NOT by PK (`id`). For example by `name` only, not by `id`

```sql
SELECT * FROM `some_table` WHERE `name`='example' LIMIT 20
```
produced **different order** of 
```sql
SELECT * FROM `some_table` LIMIT 20
```

expect: adding filter will not change select sorting
```sql
SELECT * FROM `some_table` WHERE `name`='example' ORDER BY `id` LIMIT 20
```

Someone like this...

OR we need directly write all of column names in SELECT

**Comment by bizley** [comment]
AFAIK without `ORDER BY` all SQL databases return rows in arbitrary order so you can not expect you will get it sorted by PK or similar.

**Comment by bscheshirwork** [comment]
@bizley you right... But `arbitrary order` is equal to `order by pk` in my MySQL for example.

So... Additional reason for add `order by`. Just add to add non-sort-depend cases
