### ISSUE TITLE
Translating month using yii\i18n\Formatter

### ISSUE THREAD

**Issue by orien2k** [yiisoft/yii2#15344]
### What steps will reproduce the problem?
https://pastebin.com/CLQAYHET

### What is the expected result?
Portuguese: Dez 12, 2017
English: Dec 12, 2017
French: Déc 12, 2017

### What do you get instead?
Always getting: Dec 12, 2017

| Q                | A
| ---------------- | ---
| Yii version      | 2.0

**Comment by Alex-Code** [comment]
Do you have the intl extension installed?
http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#setup-environment
