### ISSUE TITLE
Executing composer --no-dev causes problem with yii command

### ISSUE THREAD

**Issue by arollmann** [yiisoft/yii2#15341]
`composer create-project --prefer-dist yiisoft/yii2-app-basic basic` installs many dev dependencies.
When I remove them with `php ..\composer.phar -vv --no-dev update`, Gii is removed, then I get an error with the yii console command : 

> Exception 'ReflectionException' with message 'Class yii\gii\Module does not exist'
> in ...\vendor\yiisoft\yii2\di\Container.php:426

Shouldn't it be possible to clean the installation with --no-dev, keeping the possibility to execute yii commands (except gii) ?

### Additional info

| Yii version      | 2.0.13.1
| PHP version      | 7.1.1
| Operating system | Windows 10 Pro

**Comment by MysteryDragon** [comment]
@arollmann it's configuration problem. Just remove `gii` from your console config.
