### ISSUE TITLE
Multiple bugs in yii\db\Query::getTablesUsedInFrom()

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#15356]
```PHP
// BUG1: Invalid result when "from" is \yii\db\Expression:
$query = (new \yii\db\Query)->from(new \yii\db\Expression('(SELECT id from user) x'));
var_dump($query->getTablesUsedInFrom()); // array(1) { ["{{id from user) x}}"]=> string(11) "{{(SELECT}}" }

// BUG2: PHP runtime error when "from" is \yii\db\Query with alias:
$query = (new \yii\db\Query)->from(['x' => (new \yii\db\Query)->from('user')]);
$query->getTablesUsedInFrom(); // Object of class yii\db\Query could not be converted to string

// BUG3: Alias and table name are not enclosed into {{ and }}:
$query = (new \yii\db\Query)->from(['x' => 'tbl']);
var_dump($query->getTablesUsedInFrom()); // array(1) { ["x"]=> string(3) "tbl" }
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.0.25
| Operating system | Windows

**Comment by vladis84** [comment]
Hello.
BUG2 expected array `['{{u}}' => '{{user}}']`

Example 2
```php
$subQuery =  new \yii\db\Query;
$subQuery ->from(['user', 'orders']);

$query = new \yii\db\Query;
$query->from(['x' => $subQuery]);

$query->getTablesUsedInFrom();
```
expected array `['{{x}}' => ['{{user}}', '{{orders}}']]`

Am i right?

**Comment by samdark** [comment]
@vladis84 2nd.

**Comment by samdark** [comment]
@vladis84 neither since there's no aliased table used.

**Comment by PowerGamer1** [comment]
I don't like how `getTablesUsedInFrom()` processes `yii\db\Expression` now. By definition `yii\db\Expression` must be treated as a black box, not analyzed or processed in any way and inserted into generated SQL as is. I think `getTablesUsedInFrom()` should just throw exception (`throw new InvalidConfigException(gettype($this->from) . ' in $from is not supported.');`) when `$this->from` is a `\yii\db\Expression`. This won't break any existing code btw, because so far neither `\yii\db\Query` nor `getTablesUsedInFrom()` worked correctly at all when `from` was `yii\db\Expression`.

**Comment by samdark** [comment]
Table names aren't used in the code generation at all.

**Comment by PowerGamer1** [comment]
> Table names aren't used in the code generation at all. Aliases only.

Currently `getTablesUsedInFrom()` analyzes the string from `yii\db\Expression` to extract the subquery alias. No framework code should ever try to look into the string of `yii\db\Expression` to try to understand it or extract its subparts, etc. The only thing the framework can do with `yii\db\Expression` must be inserting its string unmodified into generated query or to pass the whole `yii\db\Expression` object as is as parameter or return value of some other function.

**Comment by SilverFire** [comment]
Hm... I've missed this point

**Comment by samdark** [comment]
OK. That makes sense. @SilverFire would you please handle it? Too busy today and I'm afraid it will be lost.
