### ISSUE TITLE
yii\db\Query::from() must not process yii\db\Expression argument in any way

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#15355]
Instances of `yii\db\Expression` class are meant to be treated exactly as specified and inserted into generated SQL without any modification or processing. The `Query::from()` method tries to process an instance of `yii\db\Expression` (split it by comma character) which is wrong.

### What steps will reproduce the problem?
```PHP
$query = (new \yii\db\Query)->from(new \yii\db\Expression('(SELECT id,name FROM user) x'));
var_dump($query->from); // 1.
$query->one(); // 2.
```
### What is the expected result?
1) `$query->from` should stay as original instance of `\yii\db\Expression` class passed to Query::from()
2) SQL generated must be:
```SQL
SELECT * FROM (SELECT id,name FROM user) x
```
### What do you get instead?
1) Invalid value of `$query->from`:
```TEXT
array(2) {
  [0]=>
  string(10) "(SELECT id"
  [1]=>
  string(17) "name from user) x"
}
```
2) Database Exception because produced SQL is invalid:
```SQL
SELECT * FROM (SELECT id, `name from user)` `x`
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.0.25
| Operating system | Windows

**Comment by PowerGamer1** [comment]
Does this "fix" actually allow the last statement in my example (`$query->one()`) to execute without errors?

**Comment by samdark** [comment]
It should. Try it.

**Comment by PowerGamer1** [comment]
Can't try it atm, but I doubt it would work. At least `QueryBuilder::quoteTableNames()` does not expect to get `yii\db\Expression` as its first argument (which is passed as the content of `Query::$from`).

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L885

**Comment by PowerGamer1** [comment]
I just tested it and as I suspected it does not work. The error happens exactly were I suspected it would - in `QueryBuilder::quoteTableNames()`. This issue needs to be reopened and fixed properly.
