### ISSUE TITLE
Yii2 Swiftmailer got errors with 3rd smtp transport / default transport

### ISSUE THREAD

**Issue by hyquoccuong** [yiisoft/yii2#15359]
### What steps will reproduce the problem?

Today I got some problems with yii2 swiftmailer:

1 - Sending email using gmail smtp transport configuraion cause this error:

_PHP Warning – yii\base\ErrorException
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed_

My mail configuration: 

```
'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.gmail.com',
                'username' => 'email@gmail.com',
                'password' => 'psasword',
                'port' => '587',
                'encryption' => 'tls',
            ],
        ],

```
**This error happen with all versions of yii2 swiftmailer, both latest version and older versions**

2 - After that I change the configuration to:

```
'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => false,           
        ],

```
To use deault transport as I read here:
http://www.yiiframework.com/doc-2.0/yii-swiftmailer-mailer.html

> You may also skip the configuration of the \yii\swiftmailer\transport property. In that case, the default \Swift_SendmailTransport transport will be used to send emails.

But I got this error instead:

_Swift_TransportException
Process could not be started [The system cannot find the path specified.
]_

**This error gone when I backed up the old version of swiftmailer**

### What is the expected result?
 Sending email with gmail smtp or default transport successfully
### What do you get instead?
I can't send any email with both gmail smtp and default transport

### Additional info
I tried to send email by php mail() funtion in a script and email sent succesfully so my mail configuration for xampp is okay

I think that the 1st problem is not important as 2nd one.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.0.13
| Operating system | Windows 7

**Comment by schmunk42** [comment]
You may also find some more information here:
- https://stackoverflow.com/questions/30556773/how-to-fix-stream-socket-enable-crypto-ssl-operation-failed-with-code-1
- https://github.com/PHPMailer/PHPMailer/issues/368

**Comment by Emerson-Gabriel** [comment]
Hello everyone, can anyone tell me where I should assign these properties to the mailer within Yii2?

We are working with HumHub project and I am facing this tls issue.

**Comment by schmunk42** [comment]
@Emerson-Gabriel 
Which params do you want to set?
I think you need to ask about config specifics for the app at Humhub.
