### ISSUE TITLE
[RFC] Routing and URL manager

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#15363]
Routing in Yii is quite powerful but is different from other frameworks at the same time. It is criticised for the
following:

- No middleware support.
- No ability to name routes.
- No ability to map route to class/method or a callable.
- No locale support out of the box.

Let's check these and other points one by one.

## Middleware support

[Middlewares](https://github.com/yiisoft/yii2/pull/15294) are a good approach to modifying request by a chain of handlers. It's similar to our behavior-based 
`ActionFilter`. There are multiple differences though:

1. Middlewares are going to have a PSR soon and there are many ready to use ones available via packagist.
2. Middlewares could be attached to route groups and even to all routes.
3. They're attached at routing level. Though they're easy to use with callback-based route handlers while action filters
are controller-specific.

Overall it's good to have it and, I think we need it the next major Yii release.

## Abiltiy to name routes

Abiltiy to name routes is very handy when you're using callbacks as handlers. In this case it's not possible to
determine `controller/action` pair automatically so developer should name route explicitly in order to create it
later.

In case of using controllers it is a good idea to keep our current default of `controller/action` that proved itself
good.

## Abiltiy to map route to class/method or a callable

Yii 2.0 can only map route to contrller action. I've personally seen projects where standalone actions were used
extensively and controller itself was just to hold a config for these. In this case it would've been better to
map routes to actions directly and drop controller.

## Locale support out of the box

While there's codemix router for the purpose, it's still a third party extension and since i18n is core Yii feature,
supporting locales out of the box makes sense. It could be implemented through locale middleware.

## Vital features of current routing

The following current features should present in new implementation:

- Ability to create URL by route.
- Named placeholders.
- Regular expressions.
- Custom rule classes.
- URL normalization.
- HTTP methods.
- Default values.
- Mapping named arguments to handler signature.
- Route groups (see #12960).

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/15294

**Comment by lubosdz** [comment]
Please consider also performance when adding new features here. Some of new features may be used only rarely but with significant performance penalty.
