### ISSUE TITLE
Yii2和PHP7.2

### ISSUE THREAD

**Issue by AdolphGithub** [yiisoft/yii2#15365]
最近,我将环境升级到了PHP7.2,但是当我运行时发现PHP7.2将不能使用Object作为类名,是否能将Object类名修改.
yii\base\Object

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 7.2
| Operating system |Ubuntu

**Comment by dmirogin** [comment]
> Recently, I upgraded my environment to PHP 7.2, but when I run it, I found that PHP 7.2 would not be able to use Object as its class name and could modify the Object class name.
yii \ base \ Object

**Comment by dmirogin** [comment]
Yes we marked Object as deprecated and added BaseObject.
You must change Object -> BaseObject

**Comment by AdolphGithub** [comment]
thanks
