### ISSUE TITLE
cant sort groups in active query

### ISSUE THREAD

**Issue by mahsa92** [yiisoft/yii2#15378]
Hi
I need to get last purchase of each clients .It''s can be done using DESC in group by in mysql like follows : 

`SELECT * FROM purchase GROUP BY clientId DESC`

in active record it should be like this:

`Purchase::find()->groupBy('clientId DESC ')->all()`

but it throws error beacuse groupBy function not supporting it.
Please help me with this.

**Comment by Alex-Code** [comment]
Use an `Expression`
```php
Purchase::find()->groupBy(new \yii\db\Expression('clientId DESC'))->all()
```

**Comment by mahsa92** [comment]
@Alex-Code thank you so much, it worked
