### ISSUE TITLE
The ability to pass a parameter __LINE__ to Logger and Log Target

### ISSUE THREAD

**Issue by itrade24** [yiisoft/yii2#15371]
Yii2 provides a powerful logging framework that is highly customizable and extensible. But not so flexible as it may seem. In fact, it's completely incomprehensible how to transfer __LINE__ to ensure that in the final log there was not only a method but also a line number. If you set the trace level `$level` then of course you can use **debug_backtrace**, but I would like to be able to get the line number of the calling logging function with any trace level. In addition, calling **debug_backtrace** is not the best option for performance.

Because the format of the call for logging is fixed, the only way to implement something similar is to send an object or an array instead of a string as a message.

```
public static function error($message, $category = 'application')
{
	static::getLogger()->log($message, Logger::LEVEL_ERROR, $category);
}
```

```
public function log($message, $level, $category = 'application')
{
	$time = microtime(true);
	$traces = [];
	if ($this->traceLevel > 0) {
		$count = 0;
		$ts = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
		array_pop($ts); // remove the last trace since it would be the entry script, not very useful
		foreach ($ts as $trace) {
			if (isset($trace['file'], $trace['line']) && strpos($trace['file'], YII2_PATH) !== 0) {
				unset($trace['object'], $trace['args']);
				$traces[] = $trace;
				if (++$count >= $this->traceLevel) {
					break;
				}
			}
		}
	}
	$this->messages[] = [$message, $level, $category, $time, $traces, memory_get_usage()];
	if ($this->flushInterval > 0 && count($this->messages) >= $this->flushInterval) {
		$this->flush();
	}
}
```

But it is not very flexible and architecturally transparent. So... I propose to add the LINE parameter - row number - whether an array of additional parameters that can be transferred from the calling logging context, the last optional parameter - this will allow to significantly customize the fuzzection of the logging subsystem, if necessary, while maintaining backward compatibility:

```
public static function error($message, $category = 'application', $params = [])
{
	static::getLogger()->log($message, Logger::LEVEL_ERROR, $category, $params);
}
```
```
public function log($message, $level, $category = 'application', $params = [])
{
	$time = microtime(true);
	$traces = [];
	if ($this->traceLevel > 0) {
		$count = 0;
		$ts = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
		array_pop($ts); // remove the last trace since it would be the entry script, not very useful
		foreach ($ts as $trace) {
			if (isset($trace['file'], $trace['line']) && strpos($trace['file'], YII2_PATH) !== 0) {
				unset($trace['object'], $trace['args']);
				$traces[] = $trace;
				if (++$count >= $this->traceLevel) {
					break;
				}
			}
		}
	}
	$this->messages[] = [$message, $level, $category, $time, $traces, memory_get_usage(), $params];
	if ($this->flushInterval > 0 && count($this->messages) >= $this->flushInterval) {
		$this->flush();
	}
}
```

Thus, a call to logging might look like this:

`Yii::trace('start calculating average revenue', __METHOD__, ['line' => __LINE__]);`

It does not look complicated, it could be easily implemented and solved many problems.

**Comment by klimov-paul** [comment]
This is issue no longer stands since PSR/Log accepted at #14611. You may anything you want into log context, including line number if you need it.

**Comment by itrade24** [comment]
Sounds wonderful! 

But I see that the signatures of the logging functions in 2.1 remain the same:

```
public static function error($message, $category = 'application')
public static function warning($message, $category = 'application')
public static function info($message, $category = 'application')
```
without passing any context inside the logger.

What is the use expected in this case? Calling the logger directly without these static helper methods?

Thanks, @klimov-paul

**Comment by klimov-paul** [comment]
> What is the use expected in this case? Calling the logger directly without these static helper methods?

Yes.

**Comment by itrade24** [comment]
@klimov-paul, Thanks!
