### ISSUE TITLE
after upgrade - SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'order clause'

### ISSUE THREAD

**Issue by mindochin** [yiisoft/yii2#15375]
after upgrade yii the error occurred

### What steps will reproduce the problem?
```php
$model = Label::find()->joinWith('order');
$dataProvider = new ActiveDataProvider([
    'query' => $model,
    'pagination' => [
        'pageSize' => 500,
    ],
    'sort' => [
	'defaultOrder' => ['orders.date_at' => SORT_DESC]
    ],
]);
```
### What is the expected result?

SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'order clause'
The SQL being executed was: SELECT `label`.* FROM `label` LEFT JOIN `orders` ON `label`.`order_id` = `orders`.`id` ORDER BY `0` LIMIT 500

### What do you get instead?

if you comment out "defaultOrder" - it works

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  5.6.30
| Operating system |  Apache/2.2.29 (Gentoo) mod_dp/0.99.7 PHP/5.6.30-pl0-gentoo 2017-12-18 09:01

**Comment by samdark** [comment]
Would you please check if it works with code from master branch?

**Comment by mindochin** [comment]
"minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.13",

полагаю это и должен быть мастер?

**Comment by bscheshirwork** [comment]
@mindochin 

Проверьте наличие поля `date_at` в таблице `order`

Для получения версий, используйте `composer show`

**Comment by samdark** [comment]
> полагаю это и должен быть мастер?

**Comment by mindochin** [comment]
поле имеется. замена на другое на результат не влияет. 
yii2 2.0.14-dev - результат такой же
методом проб выяснилось что ошибка появляется с версии 2,0,12. до этого норм

**Comment by klimov-paul** [comment]
Unable to reproduce.
Following unit test passes successfully:

```php
class ActiveDataProviderTest extends \yiiunit\framework\data\ActiveDataProviderTest
{
    public $driverName = 'sqlite';

    public function testDefaultOrder()
    {
        $provider = new ActiveDataProvider([
            'query' => Order::find()->joinWith('customer'),
            'pagination' => [
                'pageSize' => 2,
            ],
            'sort' => [
                'attributes' => [
                    'customer.id'
                ],
                'defaultOrder' => ['customer.id' => SORT_DESC]
            ],
        ]);
        $orders = $provider->getModels();
        $this->assertEquals(2, $orders[0]->id);
    }
}
```

I can not see `Sort::$attributes` setup in your code, if it is missing you will get an error:

> Undefined index: order.id at /home/www/pklimov/yii2/framework/data/Sort.php:225

Without attributes specification such code can not function at all. Most likely you have setup `Sort::$attributes` incorrectly.

**Comment by mindochin** [comment]
`'sort' => [
            	'attributes' => [
                    'orders.date_at'
                ],
		'defaultOrder' => ['orders.date_at' => SORT_DESC],
]`
так работает. странно, логика что-ли изменилась. Undefined index ошибок не было
