### ISSUE TITLE
make functions convinient in db queries

### ISSUE THREAD

**Issue by zuozp8** [yiisoft/yii2#15377]
Imagine code like
```
SomeModel::find()
  …
  ->groupBy(user_id)
  ->andHaving('bool_and(…SOME_CONSTRAINT…)')
```
`…SOME_CONSTRAINT…` may be something simple like `due_date < '2018-01-01` or something complex with subquery.

It would be much easier if we could write something like
`->andHaving(FunctionExpression('bool_and', ['<', 'due_date', '2018-01-01']))`
`->andHaving(FunctionExpression('bool_and', ['exists', OtherModel::find()->…]))`
`->andWhere(['>', FunctionExpression('coalesce', 'amount', SomeModel::DEFAULT_AMOUNT), 100]))`
especially if you take into account that many of those

it should be easy to implement after #7640 is done

**Comment by SilverFire** [comment]
Will be resolved by #15348
