### ISSUE TITLE
razor in Yii

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#15374]
Is it possible to add [asp.net razor](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor) in yii?
specially this constructions
```
@foreach(var item in items) {
 <span>@item.Prop</span>
}

@if (foo) {
 <text>some text</text>
}
```

**Comment by samdark** [comment]
Should be possible via extension but we aren't going to work on it. See how Twig/Smarty extensions are made and try implementing it.
