### ISSUE TITLE
Quoting column name that contain dot

### ISSUE THREAD

**Issue by Horat1us** [yiisoft/yii2#15382]
### What steps will reproduce the problem?
I have table in Postgres 10 with column name contains dot:
```sql
CREATE MATERIALIZED VIEW payment AS
 SELECT p.id,
    p.paid_at AS "dates.paid";
```
And want to order by "partials.body" column:
```php
<?php

/** @var \yii\db\ActiveQuery $query */
$query->orderBy(new Expression('[[partials.body]]');
```

### What is the expected result?
I expect Postgres quotes column name
```sql
SELECT * FROM "payment" ORDER BY "dates.paid";
```

### What do you get instead?
```sql
SELECT * FROM "payment" ORDER BY "dates"."paid";
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.2?
| PHP version      |  7.2

**Comment by Horat1us** [comment]
The only solution now is to write:
```php
<?php
use yii\db\Expression;

/** @var \yii\db\Connection $connection */
/** @var \yii\db\ActiveQuery */

$query->orderBy(new Expression($connection->schema->quoteSimpleColumnName('partials.body')));
```
isn't it too complicated?

**Comment by SilverFire** [comment]
```php
$query->orderBy(new Expression('partials.body');
```

should work as expected

**Comment by samdark** [comment]
The only way is to as @SilverFire said. There's basically no way to detect if a table name with dot means a schema and a name or just a name.
