### ISSUE TITLE
Unable to custom error message of beforeDelete(ActiveRecord)

### ISSUE THREAD

**Issue by qwerty199369** [yiisoft/yii2#15384]
### What steps will reproduce the problem?
```php
public function beforeDelete()
{
      if (parent::beforeDelete()) {
           if (OrderService::find()->where(['service_id' => $this->id])->exists()) {
              $this->addError('id', 'custom  error message ...');
              return false;
            } 
           return true;
        }

    return false;
}
```
### What is the expected result?
errorMessage: `custom error message ...`
statusCode: `400`

### What do you get instead?
errorMessage: `Failed to delete the object for unknown reason.`
statusCode: `500`

### Src
DeleteAction.php https://github.com/yiisoft/yii2/blob/master/framework/rest/DeleteAction.php#L37

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13?
| PHP version      | 7.1.8
| Operating system | Linux

**Comment by samdark** [comment]
`addError` is for validation that is not triggered for deletion.

**Comment by qwerty199369** [comment]
Yes, I know that. But is there any way to custom error message ... 

> What is the expected result?
> errorMessage: custom error message ...
> statusCode: 400

> What do you get instead?
> errorMessage: Failed to delete the object for unknown reason.
> statusCode: 500

**Comment by samdark** [comment]
try-catch and re-throw exception you need.

**Comment by qwerty199369** [comment]
thanks
