### ISSUE TITLE
problem on preventDefault

### ISSUE THREAD

**Issue by RookieLittle** [yiisoft/yii2#15386]
in previous yii2 version the script i use is working but once i updated to latest version the script have error in the yii js files and once i replace it with the old version yii.js, yii.activeForm.js and yii.validation,js, it works fine again. I'm not sure the way i code is correct or not, if I did anything wrong pls tell me. :D

this script i put in main.php
<script>
	$('form#form_area').on('beforeSubmit', function(e) {
		event.preventDefault();
	
		var form = $(this);		
			swal({
					title:"Suceess", 
					text: "Proceed",
					type: "success" ,
					// showConfirmButton: false,
					closeOnConfirm:true,
					confirmButtonText:"Okay",
					timer: 10000,
				}, 
				function(isConfirm){
					if (isConfirm) form.unbind(e).submit();
				}
			);
	});
</script>

This is the error i get

![image](https://user-images.githubusercontent.com/25970139/34151293-bf2be8dc-e4e5-11e7-9759-7db2432e0ea2.png)

**Comment by Alex-Code** [comment]
You have the param `e` but are trying to access `event` which is undefined.
You'll need to change `event` to `e`.

**Comment by RookieLittle** [comment]
yes i did, the error is gone, but it doesn't prevent it submit

**Comment by tomlutzenberger** [comment]
@RookieLittle Have a look at this:
https://stackoverflow.com/questions/9347282/using-jquery-preventing-form-from-submitting

I think `.on('beforeSubmit'` is the wrong way to go.
