### ISSUE TITLE
Proposal: RequiredValidator "not" setting

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#15391]
Adding a simple `$not` boolean property to [RequiredValidator](http://www.yiiframework.com/doc-2.0/yii-validators-requiredvalidator.html) would inverse the check to only pass validation when the attribute *is* empty. Same principle as is already used with [RegularExpressionValidator::$not](http://www.yiiframework.com/doc-2.0/yii-validators-regularexpressionvalidator.html#$not-detail)

This is useful when doing conditional validation where you do not want an attribute to be set under certain conditions.

**Comment by samdark** [comment]
Would you please provide an example?

**Comment by vercotux** [comment]
Sure thing.

In your model:

```php
public function rules() {
    return [
        ['thing', 'required'],
        ['thing', 'in',
            'range' => ['car', 'bicycle', 'boat'],
        ],
        ['wheel_size', 'required',
            'not' => true,
            'when' => function($model) {
                return $model->thing == 'boat';
            },
            'message' => "Boats have no wheels, silly!",
        ],
    ];
}
```

Now you can still do this

```php
(new MyModel([
    'thing'  => 'car',
]))->validate();

(new MyModel([
    'thing'  => 'car',
    'wheel_size' => 10,
]))->validate();

(new MyModel([
    'thing'  => 'boat',
]))->validate();
```

But you will get stopped by validation if you try to do this:

```php
(new MyModel([
    'thing'  => 'boat',
    'wheel_size' => 10,
]))->validate();
```

**Comment by samdark** [comment]
Would you like to help with a pull request (code + tests)?
