### ISSUE TITLE
Feature request for Model::populateModels method

### ISSUE THREAD

**Issue by putyourlightson** [yiisoft/yii2#15403]
Craft 2 has a very useful helper method, [populateModels](https://github.com/pixelandtonic/Craft-Release/blob/master/app/models/BaseModel.php#L184), for mass-populating models based on an array of attribute arrays. One of several use cases is to create models from an array of active records, for example:

```
$myRecords = MyRecord::find()->all();
$myModels = MyModel::populateModels($myRecords);
```

Without this one must loop through each record:

```
$myRecords = MyRecord::find()->all();
$myModels= [];
foreach ($myRecords as $myRecord) {
    $myModel = new MyModel();
    $myModel->setAttributes($myRecord->getAttributes())
    $myModels[] = $myModel;
}
```

If this is a valid feature request then please consider it as one :)

Yii 2.0.0

**Comment by samdark** [comment]
Why would you populate one model with data from another model?

**Comment by putyourlightson** [comment]
You might want to populate and return a model from an active record to limit access to the database record.

**Comment by samdark** [comment]
Sounds too abstract. Would be easier to get real world example.

**Comment by putyourlightson** [comment]
Ok, say I have a database table that stores contacts. I want to send a contact model to a template or a controller, however I don't want to grant it access to change anything in the database table. In this case I fetch the contact using an active record (ContactRecord), but I want to populate and send a model (ContactModel) rather than the record. Make sense?

**Comment by samdark** [comment]
Yes. Well, usually the models you need in view are representing the view thus likely to have fields different from what's in AR.

**Comment by samdark** [comment]
So you'll need to configure what fields of AR model to map to fields of your DTO/view model.

**Comment by samdark** [comment]
Means either:

```php
$myRecords = MyRecord::find()->all();
$myModels= [];
foreach ($myRecords as $myRecord) {
    $myModel = new MyModel();
    $z = someprocessing($myModel->c);
    $myModel->setAttributes(['x' => $myRecord->a, 'y' => $myRecord->b, 'z' => $z])
    $myModels[] = $myModel;
}
```

or 

```php
$myRecords = MyRecord::find()->all();
$result = SomeClass::populateModels($myRecords, MyModel::class, function($model) {
  $z = someprocessing($myModel->c);
  return ['x' => $myRecord->a, 'y' => $myRecord->b,  'z' => $z];
});
```

**Comment by samdark** [comment]
Looks quite similar to me...

**Comment by samdark** [comment]
Note to whoever will merge it: don't squash (multiple contributors are involved).

**Comment by putyourlightson** [comment]
In my case, a model representing an active record will generally contain a subset of the record's fields, so this works perfectly:

`$myModel->setAttributes($myRecord->getAttributes());`

Meaning that in a single call I can get my models populated with the record's fields (albeit with the same names):

`$myModels = MyModel::populateModels($myRecords);`

But I see your point about mapping fields and perhaps this use case is specific to my needs. Thanks for your input and for taking this under consideration.

**Comment by samdark** [comment]
Overall, thinking about it, I prefer not to include it in the framework: simple form looks good but it too specific. Complex form is actually looks better with foreach.

For your case I suggest you to extend your ARs from a base class and add it there or add a helper that does it.

**Comment by putyourlightson** [comment]
Yes, I wlll do that. Thanks again for the discussion!!
