### ISSUE TITLE
Mysql INT type field, the data default value is 0

### ISSUE THREAD

**Issue by xutl** [yiisoft/yii2#15413]
### What steps will reproduce the problem?

Mysql INT type field, the data default value is 0, insert new data using REST, if you do not specify the value, then the default is null, not 0, which is very unfriendly in the interface communication.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.12
| Operating system | windownsNT

**Comment by SilverFire** [comment]
> the data default value is 0

Default in MySQL only? Do you have `default` validator in your model?


> which is very unfriendly in the interface communication

Generally in this case it makes sense to mark MySQL column as `NOT NULL`

**Comment by xutl** [comment]
@SilverFire Like some counter fields, I did not set the required fields.That if set in the Model validation rules, I do not know whether to circumvent this situation?

**Comment by SilverFire** [comment]
Add `['col', 'default', 'value' => 0]` to validation rules

**Comment by xutl** [comment]
@SilverFire  thx.
