### ISSUE TITLE
not needed additional queries to database when getting data from relative model

### ISSUE THREAD

**Issue by igorveremsky** [yiisoft/yii2#15425]
### What steps will reproduce the problem?
1. create relative models `Post `connected with `User` by `author_id`
2. add `author` field for `Post` model
```php
public function fields()
{
	return [
		'id',
		'author',
		'title',
		'body',
	];
}

// get author
public function getAuthor() {
	return $this->hasOne(User::className(), ['id' => 'author_id']);
}
```
3. insert 2 test users and 8 test posts with different authors to database 
4. get posts by request

### What is the expected result?
Yii execute 1 query to database for get posts authors with id=1,2

### What do you get instead?
Yii execute 8 queries to database to get author info for each post. Screenshot from yii-debug:

![screenshot_93](https://user-images.githubusercontent.com/13087365/34412959-193f5994-ebe9-11e7-8d41-9a209349667e.png)

### Additional info
For get posts i use `yii\rest\ActiveController`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.9
| Operating system | Windows 10, MacOS

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#lazy-eager-loading
