### ISSUE TITLE
Session destroy problem

### ISSUE THREAD

**Issue by ASYOU99** [yiisoft/yii2#15421]
### What steps will reproduce the problem?
After logout a have this problem
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.7
| Operating system |Win7
session_regenerate_id(): Session object destruction failed.
![image](https://user-images.githubusercontent.com/12735688/34396181-521ea2ca-eb70-11e7-867a-8fa43b3b4ab9.png)

I do not use any third-party storage. Standard advanced template settings. The error appeared probably after switching to another version of php earlier, I used version 7.0.8 (approximately so), and switched to version 7.1.7 is possible in this lies the reason before this such an unintentionally did not arise. The error only occurs when logout. It is solved by deleting the session manually or by restarting the browser.

**Comment by ASYOU99** [comment]
Allocated a small step. After the login, when the page is not finished yet, but the logout button is pressed on it and an error occurs. If the page was paged fullness then the error was unsuccessful to catch. (A long load on the local, perhaps because of faster porting on the server, such an error is not possible but on the local one is caught stably)

**Comment by ASYOU99** [comment]
When does the issue occur?
To fully display the page after the login, when you press the logout button
What do you see?
I see the error shown above in the screenshot
What was the expected result?
Logout my user
Can you supply us with a stacktrace? (optional)
A little later I'll try to lay out
Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)
```
/**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $url = Url::previous('checkout');
            $cat = Url::previous('backFromBasket');
            if(isset($url)){
                return Yii::$app->response->redirect($url);
            }elseif (isset($cat)){
                return Yii::$app->response->redirect($cat);
            }
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model              
            ]);
        }
    }
```
```
    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
```
No test

**Comment by ASYOU99** [comment]
A similar problem also arose recently with my colleague, but he did not attach importance to this as a temporary bug due to possible some kind of code problems. While I told him about the regularity of the bug I have (the steps are very similar, so I clicked the exit to the full load of the page after the login)

**Comment by samdark** [comment]
That's still quite vague. I've tried reproducing it locally but it works for me...

**Comment by samdark** [comment]
Do you have c:/ospanel/userdata/temp dir that is accessible and writeable by web server process?

**Comment by ASYOU99** [comment]
Yes I have this dir and is writebla

**Comment by samdark** [comment]
Would you please try with code from master branch instead of stable release?
