### ISSUE TITLE
Incorrect spellout while not provided translation on other than EN

### ISSUE THREAD

**Issue by xicond** [yiisoft/yii2#15430]
### What steps will reproduce the problem?

```
\Yii::$app->language='id';
\Yii::$app->sourceLanguage='en-US';
echo \Yii::t('app', '{n,spellout}', ['n' => 1000]);

// application that set default sourceLanguage='en' 
// I thought Yii should be able to spellout even without put on messages
// return ['{n,spellout}' => '{n,spellout}']

```

### What is the expected result?
```
// seribu
```

### What do you get instead?
```
// one thousand
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.12
| Operating system | OSX Sierra 10.12.6

**Comment by schmunk42** [comment]
Do you have php-intl installed and enabled?

**Comment by xicond** [comment]
@schmunk42 yes enabled correctly, coz other translation like date is correctly run

**Comment by rugabarbo** [comment]
Must be closed.

You need only formatting, **not translating**, so you should use:

```php
\Yii::$app->language = 'id';
echo \Yii::$app->i18n->format('{n,spellout}', ['n' => 1000], \Yii::$app->language);
```

Result:
`seribu`

**Comment by rugabarbo** [comment]
Also you can use: 
```php
\Yii::$app->language = 'id';
echo \Yii::$app->formatter->asSpellout(1000);
```

Result:
`seribu`
