### ISSUE TITLE
Integrate `yiisoft/di`

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#15436]
DI container from [yiisoft/di](https://github.com/yiisoft/di) should be integrated into main repo replacing old DI classes before 2.1 release.
The location and internal code of the following classes should be rewised:

- yii\di\Instance
- yii\di\ServiceLocator

Keep in mind that namespace `yii\di` is taken by `yiisoft/di` package. While Composer allows having multiple folders for the same namespace, I would like to avoid such approach as it will make code navigation difficult.

PR for ['class' keyword fallback](https://github.com/yiisoft/di/pull/4) should be considered to be handled at `yiisoft/yii` instead of `yiisoft/di`. If there will be a graceful way to provide fallback from `__class` to `class` it could be done - if not - no fallback will be provided.

**Comment by samdark** [comment]
I think we can use it via composer instead of getting it into repository directly.

**Comment by klimov-paul** [comment]
Obviously.

**Comment by samdark** [comment]
We don't need `Instance` since there's https://github.com/yiisoft/di/blob/master/src/Reference.php

**Comment by samdark** [comment]
`ServiceLocator` could be moved to `base`.

**Comment by samdark** [comment]
Another thing is that `yiisoft/di` doesn't have built-in support for factories (should not be container job, I think) that we use for widgets.

**Comment by klimov-paul** [comment]
> We don't need Instance since there's `Reference`

What about [Instance::ensure()](https://github.com/yiisoft/yii2/blob/master/framework/di/Instance.php#L111) then? It is widely used around the Yii code.

**Comment by samdark** [comment]
Yes. That's missing.

**Comment by klimov-paul** [comment]
Intermediate changeset applied, allowing usage of '__class' keyword for definitions:
b04e0e06dc0939ae0b3c822656f1114f76ee320f
d1ff652b2f0baabbfb9e8776659167508eff5632

Thus the entire code will not break after "yiisoft/di" integration.

**Comment by SilverFire** [comment]
I'd suggest to implement `__construct()` parameter support as well.

1. It is consistent with config format agreed for `yiisoft/di`
2. While `yiisoft/di` is a bit raw and not integrated in Yii 2.1, this change will help us to write configs that will work after `yiisoft/di` adoption.

**Comment by hiqsol** [comment]
Please, consider reopening: #15815

**Comment by schmunk42** [comment]
Will this be PSR-11 compatible?

**Comment by samdark** [comment]
Yes, yiisoft/di is PSR-11 compatible.

**Comment by samdark** [comment]
After several attempts to integrate yiisoft/di by me, @SilverFire and @hiqsol which took too much time and weren't really successful decided not to do it. Instead:

- [ ] Declare an interface for DI container in `yiisoft/yii2`. Make it an extension of PSR if possible.
- [ ] Port cycles in dependencies detection from `yiisoft/di`.
- [ ] Port method calls support from `yiisoft/di`.
- [ ] Remove ability to set constructor options from method signatures, move it to `__construct`.

It's all indicated in roadmap so closing this issue.
