### ISSUE TITLE
Move SL components to DIC how Singletons with SL compatibility

### ISSUE THREAD

**Issue by KoJIT2009** [yiisoft/yii2#15443]
Enhancement: Move SL components to DIC how Singletons with SL compatibility

App config
```
...
'components' => [
    'abc' => [
        'class' => Abc::class,
    ],
],
...
```
$abcSL = Yii::$app->abc;
$abcDIC = Yii::createObject['class' => 'abc'];

Equal: $abcSL and $abcDIC

**Comment by KoJIT2009** [comment]
It's not bug, but enhancement

**Comment by samdark** [comment]
So what's proposed here:

1. When components are registered they're available from DI container as singletons automatically.
2. Compatibility is kept.

I personally think it's a good move. @yiisoft/core-developers, @yiisoft/reviewers what do you think?

**Comment by rob006** [comment]
It looks like pure magic for me... :/

**Comment by klimov-paul** [comment]
For what purpose it is needed?
At the present state components are stored inside the service locator. Particular service locator can be a singleton - as `Application` is - and can be not - as `Module` is.
Thus developer may choose in which way he prevers to store components. Such change eliminates any other posibilities.
If you wish to store all your components in DI container as a singleton you are free to do so without any changes in the core. What exactly is the problem?

**Comment by KoJIT2009** [comment]
This will allow use DI in core without losing backward compatibility.

**Comment by klimov-paul** [comment]
> This will allow use DI in core without losing backward compatibility.

This does not clarifies anything. What exactly preventing you from using DI now?

**Comment by klimov-paul** [comment]
And more important: what will happen if I wish to use several instances of some class as separated components?
For example:

```php
'components' => [
    'db' => [
        'class' => yii\db\Connection::class,
        'dsn' => 'some-dsn',
    ],
    'legacyDb' => [
        'class' => yii\db\Connection::class,
        'dsn' => 'another-dsn',
    ],
    // ...
],
```

**Comment by KoJIT2009** [comment]
> This does not clarifies anything. What exactly preventing you from using DI now?

https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L267

As an example, we can remove a static call Yii::$app->getFormatter() and make a default configuration via DI
```php
'definitions' => [
    GridView::class => [
        'class' => GridView::class,
        'formatter' => Instance::of('formatter')
    ]
] 
```

> And more important: what will happen if I wish to use several instances of some class as separated components?
For example:

It will be separated singletons with defined configuration.

**Comment by samdark** [comment]
Decided not to do it in 2.0.
