### ISSUE TITLE
AttributeTypecastBehavior typecast detection fails because of the "!" prefix.

### ISSUE THREAD

**Issue by bboure** [yiisoft/yii2#15440]
### What steps will reproduce the problem?

1) Create a Model with some "unsafe" validation rules using the "!" prefix.
2) Add the `AttributeTypecastBehavior` behaviour with autodetection (leave `attributeTypes` empty)

### What is the expected result?

`AttributeTypecastBehavior` should work as expected.

### What do you get instead?

Getting an error:
`"Getting unknown property: app\\models\\Model::!attribute",`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.10
| Operating system | Ubuntu 16.04.1

Issue is around [here](https://github.com/yiisoft/yii2/blob/master/framework/behaviors/AttributeTypecastBehavior.php#L287). Prefix should be removed, using [getAttributeNames()](http://www.yiiframework.com/doc-2.0/yii-validators-validator.html#getAttributeNames()-detail).
I will open a PR to fix this if I can.

**Comment by klimov-paul** [comment]
Resolved by commit 2a742cee9fa9a22fd0a2a8eba69b3ca42fa4114b
