### ISSUE TITLE
Lacking of an option to set the database in yii fixture/load 

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#15447]
### What steps will reproduce the problem?

When you run ./yii fixture/load you can not set an option to specify a different database than the main one. In case you want to load fixtures for a testing database you might end up overwriting your production database.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 
| Operating system |

**Comment by vladis84** [comment]
Hello.
When you start the fixture from the tests, config.local.php is used.
See https://github.com/yiisoft/yii2/blob/master/tests/data/config.php

**Comment by samdark** [comment]
@vladis84 that's in Yii tests. As far as I remember, regular app uses main DB connection from regular config by default.

**Comment by vladis84** [comment]
Ok.
I will do it.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
