### ISSUE TITLE
Kartik gridview export button style.

### ISSUE THREAD

**Issue by PaheerathanSelvarasa** [yiisoft/yii2#15442]
`use yii\grid\GridView;
use kartik\export\ExportMenu;

echo ExportMenu::widget([
          'dataProvider' => $dataProvider,
          'columns' => $gridColumns,
          'dropdownOptions' => [
              'label' => 'Export',
              'class' => 'btn btn-primary'
          ],
          'columnSelectorOptions' => [],
          'showColumnSelector' => \FALSE,
          'formatter' => [
              'class' => 'yii\i18n\Formatter',
              'nullDisplay' => ' ',
          ],
          'exportConfig' => [
              ExportMenu::FORMAT_HTML => false,
              ExportMenu::FORMAT_TEXT => false,
              ExportMenu::FORMAT_EXCEL => false,
          ],
          'filename' => 'Document',
        ]);`

There are two down arrows appeared in Kartik gridview export button. How to remove one down arrow in the export button? 
Is there any styling features available?

![screenshot 221](https://user-images.githubusercontent.com/29100886/34479936-6910b8ca-efcf-11e7-871a-36bb5c2073a2.png)

**Comment by Alex-Code** [comment]
This is the issue tracker for the Yii framework.
You'll need to create an issue on Kartik's git.
