### ISSUE TITLE
QueryBuilder: orOnCondition works wrong

### ISSUE THREAD

**Issue by eLFuvo** [yiisoft/yii2#15457]
### What steps will reproduce the problem?

Add orOnCondtion to relation, like this:
```php
    /**
     * @return ActiveQuery
     */
    public function getConversationUsers()
    {
        return $this->hasMany(User::class, ['id' => 'senderId'])
            ->orOnCondition([User::tableName().'.[[id]]' => new Expression(self::tableName().'.[[recipientId]]')]);
    }
```

### What is the expected result?

Relation condition must looks like this:
```mysql
SELECT `chat_history`.* FROM `chat_history`
INNER JOIN `user` ON
(`chat_history`.`senderId` = `user`.`id`) OR (`user`.`id`=`chat_history`.`recipientId`)
```

### What do you get instead?

But looks as:

```mysql
SELECT `chat_history`.* FROM `chat_history`
INNER JOIN `user` ON
(`chat_history`.`senderId` = `user`.`id`) AND (`user`.`id`=`chat_history`.`recipientId`)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.1.12
| Operating system |  Linux 6765e0c6429e 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 GNU/Linux

**Comment by rob006** [comment]
duplicates #6985
