### ISSUE TITLE
MSSQL 2017 BIT Default value set to 1 but model default values return 0

### ISSUE THREAD

**Issue by k3bra** [yiisoft/yii2#15455]
### What steps will reproduce the problem?
When we call the method  **loadDefaultValues()** from a **Model** the default value is always **0** even if in the table schema is set as **1** .

The problem is in the **ColumnSchema::typecast()** when we try to covert  **((1))**  to **Integer** it always converts it to **0** because of the parentheses.

```PHP
    protected function typecast($value)
    {
           ...
            case 'integer':
                return (int) $value;
           ...
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version     | 7.1 
| Operating system  | Windows Server

**Comment by alexkart** [comment]
Fixed by https://github.com/yiisoft/yii2/pull/17420
