### ISSUE TITLE
abstract Action

### ISSUE THREAD

**Issue by zucha** [yiisoft/yii2#15454]
Is it possible to make yii\base\Action make abstract class with abstract run() method?

### What is the expected result?
cleaner code. more attractive.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by klimov-paul** [comment]
No.
Method `run()` of particular action may contain mandatory arguemnts, which should be populated from request. Having method run at the parent class will cause PHP E_STRICT error in this case, since overridden method does not match parent signature.
