### ISSUE TITLE
yii2 with oracle and gii error

### ISSUE THREAD

**Issue by hanswpu** [yiisoft/yii2#15468]
- Local:CentOS-7.4.1708
 - Local:PHP-7.1.11
 - Remote:Oracle 11g-11.2.0.4.0 
 - Local:oci8-2.1.8
 - Local:Nginx-1.13.8
 - Local:Yii2-2.0.13

I can connect remotely to DB with sqldeveloper. I can connect with sqlplus to DB.I can successfully run the following code and get the correct result

    <?php
    // demo.php
    $username = 'user';
    $password = 'pwd';
    
    $connectText = '//remoteip:1521/test';
    
    putenv("NLS_LANG=SIMPLIFIED CHINESE_CHINA.ZHS16GBK");
    $conn = oci_connect($username, $password, $connectText);
    if (!$conn) {
        $e = oci_error();
        echo 'Oracle connect false<br />';
        exit($e['message']);
    }
    
    echo 'Oracle cnnectted';
    
    // Prepare the statement
    $stid = oci_parse($conn, "SELECT * FROM CODE_XSB");
    if (!$stid) {
        $e = oci_error($conn);
        exit($e['message']);
    }
    
    // Perform the logic of the query
    $r = oci_execute($stid);
    if (!$r) {
        $e = oci_error($stid);
        exit($e['message']);
    }
    // Fetch the results of the query
    print "<table>\n";
    while ($row = oci_fetch_array($stid, OCI_ASSOC+OCI_RETURN_NULLS)) {
        print "<tr>\n";
        foreach ($row as $item) {
            $item = ($item !== null ? mb_convert_encoding($item, 'utf-8', 'gbk') : " ");
            print "    <td>" . $item . "</td>\n";
        }
        print "</tr>\n";
    }
    print "</table>\n";
    oci_free_statement($stid);
    oci_close($conn);

But I can't make gii to work.

    main-local.php
    'oracledb' => [
                'class' => 'yii\db\Connection',
                'dsn'=>'oci:dbname=//remoteip:1521/test;charset=utf8',
                'username'=>'user',
                'password'=>'pwd',

I got following error message:

    Database Exception – yii\db\Exception
    could not find driver
    ↵
    Caused by: PDOException
    could not find driver
    
    in /home/www/devnet/Yii2/vendor/yiisoft/yii2/db/Connection.php at line 660

**Comment by samdark** [comment]
Means either you don't have PDO driver installed/enabled in php.ini or you're specifying DSN incorrectly.
