### ISSUE TITLE
accessChecker configuration error

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#15462]
### What steps will reproduce the problem?
1) configure user component like this:
```php
'components' => [
        'user' => [
            'accessChecker' => 'app\helpers\AccessChecker',
            // ...  other params
        ],
```
### What is the expected result?
accessChecker object must instantinate in User

### What do you get instead?
`PHP Fatal Error – yii\base\ErrorException
Call to a member function checkAccess() on string
in /home/clevertoy/app/vendor/yiisoft/yii2/web/User.php line 712:`

```php
709:    if (($accessChecker = $this->getAccessChecker()) === null) {
710:        return false;
711:    }
712:    $access = $accessChecker->checkAccess($this->getId(), $permissionName, $params);
```
$this->getAccessChecker() must return object instead of string

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.0.24
| Operating system | Debian 8

**Comment by developeruz** [comment]
Confirmed. It works if one setup `accessChecker` from the code like 
```php
 $user->accessChecker = new MyAccessChecker();
```
but for the config it is impossible to give an object.
