### ISSUE TITLE
yii2 advanced

### ISSUE THREAD

**Issue by dzul2020** [yiisoft/yii2#15465]
i have problem when i try to create a looping condition

public function actionPilih($nomor_urut_pasangan)
    {
        $model = Calonpasangan::find()->where(['nomor_urut_pasangan' => $nomor_urut_pasangan])->one();
 
        // $id not found in database
        if($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');
         
        // update record
        if($model->load(Yii::$app->request->post()) && $model->save()){
	  
	$modeljumlah_perolehan_suara = $model->canGetProperty($nomor_urut_pasangan);
	$model->jumlah_perolehan_suara = $modeljumlah_perolehan_suara + '1';  	
        $model->save();
            return $this->redirect(['index']);
        }
         
        return $this->render('pilih', ['model' => $model]);
    }

as you can see, i want to make that the field of jumlah_perolehan_suara from calon table which the primary_key is nomor_urut_pasangan   can incremented 1 when actionPilih occurred

**Comment by Renkas** [comment]
This is not a support forum ... Go try Yii forums
