### ISSUE TITLE
Code syntax error in Yii2 documentation

### ISSUE THREAD

**Issue by abasit83** [yiisoft/yii2#15460]
### Documentation URL
[http://www.yiiframework.com/doc-2.0/yii-base-security.html#generatePasswordHash()-detail](url)

### What is the expected result?
Parenthesis missing

### What do you get instead?
Syntax error

### Additional info
![please correct the code](https://user-images.githubusercontent.com/6211366/34608757-b0233210-f23b-11e7-87d9-26e0758d555a.png)

**Comment by SilverFire** [comment]
Fixed by #15461
