### ISSUE TITLE
After Using DB transaction and the getPrimaryKey() return NULL

### ISSUE THREAD

**Issue by wuwugin** [yiisoft/yii2#15477]
### What steps will reproduce the problem?
```PHP
if(isset($tag))
{
	$dbTransaction = Yii::$app->db->beginTransaction();
	if($article->save())
	{
		if($tag->save()) 
		{
			$dbTransaction->commit();
			return $article;
		}
		else $dbTransaction->rollBack();
	}
	else $dbTransaction->rollBack();
}
$article = new \frontend\models\Article;
$ID = $article->getPrimaryKey();
//the output is NULL
var_dump($ID);
```
The problem is before I haven't used the dbTransaction yet, everything was fine.
And the most important part is now without using `$dbTransaction = Yii::$app->db->beginTransaction();`
**The problem continues.**
### What is the expected result?
 A newly assigned id according to AutoIncremen PK
### What do you get instead?
NULL

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.18
| Operating system |macOS 10.13 Beta (17A362a)
|Mysql version|5.6.35

I notice the related issue is #12171

**Comment by Alex-Code** [comment]
You're creating a new empty model, it won't have any data.

You'll only get the `PK` after a successful save but even then you `return` out of the function.

**Comment by wuwugin** [comment]
@Alex-Code it's true.
But by using the getPrimaryKey() and `return $this->pre_article_id = $current_article_id - 1; `, after `save()` the value in the database always  gets **-1**, which means `NULL - 1`. It never happened before.
Maybe I'll check my code again and report.

**Comment by Alex-Code** [comment]
You need to provide more code or a working example.
What you've provided doesn't match what you're talking about.

**Comment by wuwugin** [comment]
```PHP
public function postArticle()
{
	if($this->validate())
	{
                //Article model is created by gii model generator
		$article = new Article;
		$this->id = $article->getPrimaryKey();
		$article->pre_article_id = $this->id - 1;
                //ArticleTag model is created by gii model generator
                $tag = ArticleTag::findOne($this->article_tag);
                //other code...
		if($article->save()&&$tag->update())
		{
			return $article;
		}
	}
	return null;
}
```
It can be saved to database, but still like this:
<img width="629" alt="screen shot 2018-01-09 at 10 00 57 pm" src="https://user-images.githubusercontent.com/15246068/34724447-c6a1c9ac-f588-11e7-812d-bec278789f8d.png">

**Comment by Alex-Code** [comment]
I think you're getting confused on how it works.
What are you trying to do?

**Comment by wuwugin** [comment]
Ok, I git reset the previous version and find out before I used the getPrimaryKey() below the save().
I make it mess, my fault. Thank you for your time!
