### ISSUE TITLE
yii\widgets\MaskedInput scripts doesn't apply

### ISSUE THREAD

**Issue by inoise** [yiisoft/yii2#15470]
### What steps will reproduce the problem?
Append html, rendered MaskedInput on server via renderAjax to current Page.
No MaskedInput elements on this Page before that action.

### What is the expected result?
Rendered working MaskedInput Element

### What do you get instead?
Rendered plain input block

### Additional info
Problem on: 
`$view->registerJs("var {$this->_hashVar} = {$encOptions};", View::POS_HEAD);`

this way u need to use  View::POS_READY, which default parameter in registerJs method

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14 |
| PHP version |  7.1    | 
| Operating system | ANY |

**Comment by Alex-Code** [comment]
Can you provide some more code or an example.
Can't work out what issue you're having?

**Comment by inoise** [comment]
U r welcome! This is just example, not real code, but u need it for something. As i said - this is View::POS_HEAD problem. Of cause i can create my own MaskedInput and override method, but it's not only my problem, i suppose. 

**kartik-v/yii2-widget-select2** use atribute **hashVarLoadPosition** to resolve same problem

Code:

page:
`<div id="#list"></div>`

script:
```
function addRecord()
{
    $.ajax({
        url: '/url-to-masked-input-render-action',
        type: "GET",
        success: function (html) {
            $('#list').append(html);
        }
    });
}
```

action:
```

public function actionGetNewScheduleRecord()
    {
        $this->layout = false;
        Yii::$app->response->format = Response::FORMAT_HTML;
        return $this->renderAjax('_masked_input');
    }
```

_masked_input view:

```
<?= yii\widgets\MaskedInput::widget([
            'mask' => '99:99',
        ]); ?>
```
