### ISSUE TITLE
[yii\db\ActiveRelationTrait] ActiveRecord Relation Query Missing Some Data

### ISSUE THREAD

**Issue by pfdtk** [yiisoft/yii2#15482]
https://github.com/yiisoft/yii2/blob/1e0157f0acbcbb5440d3f7a1569ede48593d9098/framework/db/ActiveRelationTrait.php#L524

Why here use `array_unique($values, SORT_REGULAR)` instead of `array_unique($values)`? it cause some problem in my case. 

Two tables are designed as below:

Table A:

id  | name
---| -------
1   | 001
2   | 0001

Table B：

id  | name
---| ------
1   | 001
2   | 0001

In my case, i use the relation `hasOne` in the Table A ActiveRecord like below:

```php
public function getB() {
    $this->hasOne(TableB::className(), ['name' => 'name'])
}
```

and for a better query performance, i use function `with('b')` to reduce query times. But from the db log, i got the sql:

```sql
select * from B where name = '001'
```

not the expectant one:

```sql
select * from B where name in ('001', '0001')
```

I don`t know if this is a bug or It is intentionally.

**Comment by samdark** [comment]
Please upgrade to latest version (or master) and check if the issue is still valid.

**Comment by pfdtk** [comment]
@samdark Yes, i upgrade the version to 2.0.13.1, it still valid.

**Comment by samdark** [comment]
How do you perform the query?

**Comment by pfdtk** [comment]
@samdark This is my code

```
<?php

namespace app\controllers;

use yii\db\ActiveRecord;
use yii\web\Controller;

class SiteController extends Controller
{
    public function actionTest()
    {
        $result = TableA::find()->with('table_b')->all();
        foreach ($result as $v) {
            var_dump($v->table_b);
        }
    }

}

class TableA extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%table_a}}';
    }

    public function getTable_b()
    {
        return $this->hasOne(TableB::className(), ['name' => 'name']);
    }
}

class TableB extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%table_b}}';
    }
}
```

and the result:

```
object(app\controllers\TableB)#93 (8) {
  ["_attributes":"yii\db\BaseActiveRecord":private]=>
  array(2) {
    ["id"]=>
    int(2)
    ["name"]=>
    string(4) "0001"
  }
  ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
  array(2) {
    ["id"]=>
    int(2)
    ["name"]=>
    string(4) "0001"
  }
  ["_related":"yii\db\BaseActiveRecord":private]=>
  array(0) {
  }
  ["_errors":"yii\base\Model":private]=>
  NULL
  ["_validators":"yii\base\Model":private]=>
  NULL
  ["_scenario":"yii\base\Model":private]=>
  string(7) "default"
  ["_events":"yii\base\Component":private]=>
  array(0) {
  }
  ["_behaviors":"yii\base\Component":private]=>
  array(0) {
  }
}
NULL
```

the second `$v->table_b` return NULL

**Comment by samdark** [comment]
I confirm the bug. It is because array_unique works in a weird way:

```php
$arr = array_unique(['0001', '001'], SORT_REGULAR);
var_dump($arr);

// returns ['0001']
```

**Comment by samdark** [comment]
It's because `SORT_REGULAR`.

**Comment by pfdtk** [comment]
Yes, i found some infomation in [stackoverflow](https://stackoverflow.com/questions/14802680/array-unique-sort-regular-flag), it seems `SORT_REGULAR` is the same as an equality check with `==`

**Comment by samdark** [comment]
@cebe git blame shows that you've touched this code last. Long time ago but still, do you remember why we're doing `SORT_REGULAR`?

**Comment by cebe** [comment]
it was introduced in https://github.com/yiisoft/yii2/commit/23572c74cdd791005e79db7141405624c74de1ea#diff-cbb917fbe0fb0627cd1b6fa3ac6b2d8aR250 no reason given, but I assume it is about comparing integer `1` and string `'1'`. That should still work with `SORT_STRING` so I think its okay to change it.
