### ISSUE TITLE
Генерация Yii powered()

### ISSUE THREAD

**Issue by s1lver** [yiisoft/yii2#15481]
Всем привет!

Вообще, конечно, это не архиважный момент, но вызывает некоторые вопросы. Возможно на него уже отвечали, но все же. Почему функция `powered()` реализована именно таким образом? Почему нельзя было использовать хелпер?

**Например:**
текущая реализация:
```php
public static function powered()
    {
        return \Yii::t('yii', 'Powered by {yii}', [
            'yii' => '<a href="http://www.yiiframework.com/" rel="external">' . \Yii::t('yii',
                    'Yii Framework') . '</a>',
        ]);
    }
```

и с хелпером:

```php
public static function powered()
    {
        return \Yii::t('yii', 'Powered by {yii}', [
            'yii' => Html::a(\Yii::t('yii', 'Yii Framework'), 'http://www.yiiframework.com/', ['rel' => 'external']),
        ]);
    }
```

**Comment by samdark** [comment]
Я бы вообще перетащил это в хелпер, чтобы не засорять ядро.

**Comment by samdark** [comment]
Ну а так, тут хелпер вроде ничего особо не даёт. Так что HTML или нет тут равноценно.

**Comment by Kolyunya** [comment]
> Ну а так, тут хелпер вроде ничего особо не даёт. Так что HTML или нет тут равноценно.

It's not equivalent from the code style perspective. It's more elegant since it doesn't use string concatenation. Also if we have a convenient helper for generating HTML hyperlinks why would not we make use of it?

**Comment by Kolyunya** [comment]
Be careful asking to refactor something. It may be refactored out.

**Comment by samdark** [comment]
For the better.
