### ISSUE TITLE
QueryBuilder param binding not working in array condition

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#15493]
### What steps will reproduce the problem?
```php
Prod::find()->select('name')->where(['id' => ':id'])->params([':id' => 70])->one();
```
### What do you get instead?
Database Exception – yii\db\Exception
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
The SQL being executed was: SELECT `name` FROM `prod` WHERE `id`=':id'

### Additional info
This is working good:
```php
Prod::find()->select('name')->where('id=:id')->params([':id' => 70])->one();
```
So, binding not working only when WHERE condition is in array form.

Looking closer:
```php
$cmd = Prod::find()->select('name')->where(['id' => ':id'])->params([':id' => 70])->createCommand();
var_dump($cmd->params, $cmd->rawSql);
```
Output:
```
array (size=2)
  ':id' => int 70
  ':qp1' => string ':id' (length=3)
string 'SELECT `name` FROM `prod` WHERE `id`=':id'' (length=42)
```
So, in raw sql binding not works.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 5.6.30
| Operating system | Debian 8

**Comment by samdark** [comment]
It is expected. When you're passing an array, parameters are bound automatically:

```php
Prod::find()->select('name')->where(['id' => 70])->one();
```
