### ISSUE TITLE
problem with doc commit: apache2 htaccess, avoid scriptname in URLs

### ISSUE THREAD

**Issue by aliv** [yiisoft/yii2#15490]
@cebe , After I posted this issue i found doc is about basic template, but i don't know that how it probably works for basic and not for advanced template.

### What steps will reproduce the problem?
with https://github.com/yiisoft/yii2/commit/144ccf03443cf18d92c202ad73ecf6c482e71760 commit and putting this lines in backend/web/.htaccess file 

```
  RewriteEngine on
    # If a directory or a file exists, use the request directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Otherwise forward the request to index.php
    RewriteRule . index.php

    # if $showScriptName is false in UrlManager, do not allow accessing URLs with script name
    RewriteRule ^index.php/ - [L,R=404]
```
and
```
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
			/*
            'rules' => [
            ],
			*/
        ],
```

### What is the expected result?
commit says only for request with .index.php it throws not found.

### What do you get instead?
not found for all requests with and without .index.php

i am not expert of rewrite topic but moving  `RewriteRule ^index.php/ - [L,R=404]` under `RewriteEngine on` seems work for me. 
it seems `RewriteRule ^index.php/ - [L,R=404]` block even redirected page by `RewriteRule . index.php`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.2.1
| Operating system | centos 7

**Comment by ajmedway** [comment]
Same issue for me too. I have created a pull request because this rule utilises the `[L]` flag (i.e. last), which terminates rewriting after it is matched, which we want to do if incoming url begins with `index.php/`. We do not want to serve anything if this pattern matches, otherwise forward to the front controller for routing, if not requesting a valid file or directory on filesystem.
