### ISSUE TITLE
Multi Result Set From Stored Procedure - Mysql - nextRowset

### ISSUE THREAD

**Issue by gimox** [yiisoft/yii2#1549]
We are  tryng to display a multi Result set from a stored procedure.

We can display only the first result using queryAll().

The stored is called with this code:

```php
 $command =  \Yii::$app->db->createCommand("CALL mystored()");
 $response = $command->queryAll();
```
The result is only the first recordset. 
The same stored called inside mysql return two tables

without Yii we can do this in php using:

```php
$stmt = $db->prepare('CALL mystored()');
// read first result set
while ($row = $stmt->fetch()) {
    printf("%d\n", $row['id']);
}
$stmt->nextRowset();  // this is important 
// read second result set
while ($row = $stmt->fetch()) {
    printf("%d\n", $row['id']);
}
```

How can i  implements ```nextRowset() ``` in yii ?

**Comment by Faryshta** [comment]
what documentations ar needed here?

**Comment by SilverFire** [comment]
> You can use readAll() to get all rows in one rowset

I think it is already documented: http://www.yiiframework.com/doc-2.0/yii-db-datareader.html

**Comment by sruthidesai** [comment]
$connection = Yii::$app->db;
        $command = $connection->createCommand('{call Emp1()}');
 $query = $command->queryAll(
$dataProvider = new ActiveDataProvider([
            'query' => $query,
       ]);)
 return $dataProvider;
}
Hello,
...this is how am fetching value form Emp1 stored procedure

<?= GridView::widget([ 
        'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
         'containerOptions'=>['style'=>'overflow: auto'],
    'tableOptions' => ['perfectScrollbar'=>true],
     'floatHeader'=>true,
    'panel' => [

        'type' => 'primary',
        'heading' => "<b><center>Employee Master</center></b>",
    ],
        'beforeHeader'=>[
        [
        'columns'=>[

this is my view when i am executing am getting this error---
Invalid Configuration – yii\base\InvalidConfigException

The "query" property must be an instance of a class that implements the QueryInterface e.g. yii\db\Query or its subclasses.



please anyone help to solve this problem am using yii2 with mssql
