### ISSUE TITLE
Captcha color mess

### ISSUE THREAD

**Issue by esaesa** [yiisoft/yii2#15498]
### What steps will reproduce the problem?
Using the following captcha action config. I just revered the default fore and back colors

    public function actions()
     {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'a' : null,
                'maxLength' => 3,
                'minLength' => 1,
                'offset' => 0,
                'backColor' => '0x2040A0',
                'foreColor' => '0xFFFFFF'
            ],
        ];
    }`
### What is the expected result?
A captcha with white font and blue background
### What do you get instead?
Black background and font

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.0.8
| Operating system | Win7

**Comment by Kolyunya** [comment]
`backColor` and `foreColor` expect values of integer type, not strings. Not sure if that's the source of the problem.

**Comment by aleksbelic** [comment]
@Kolyunya is right: **backColor** and **foreColor** are just numbers ([Docs](https://github.com/yiisoft/yii2/blob/b566dd522c5190b43e1ed8345cd38b59e52b0bae/framework/captcha/CaptchaAction.php#L67)).
@esaesa just remove the quotes around the color codes.
![yii2](https://user-images.githubusercontent.com/8314231/36218601-4207a9a2-11b5-11e8-8770-242371c90865.png)
