### ISSUE TITLE
Can't reconfigure application component for a module

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii2#15492]
I try to change single property of DB component for my module as described here: http://www.yiiframework.com/doc-2.0/guide-structure-modules.html#accessing-components-from-within-modules

I'm expecting to have the same DB connection in my module as in the application but just with different table prefix

Instead I get an error "The configuration for the "db" component must contain a "class" element."

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.0
| Operating system | Windows 10

**Comment by Alex-Code** [comment]
Not sure if module specific component configs get merged with the application or not but the error says you've not specified a `class` name.

Does your main config have the class key -> value?

```php
'modules' => [
    'mymodule' => [
        'components' => [
            'db' => [
                'class' => 'yii\db\Connection',
                'tablePrefix' => 'module_',
            ],
        ],
    ],
],
```

**Comment by uaoleg** [comment]
Yes, `class` name is specified in `common/config/main.php`

    'components' => [
        'db' => [
            'class'     => \yii\db\Connection::class,
            'dsn'       => 'mysql:host=localhost;dbname=mydb',
        ],
    ]

And then in `modules\mymodule\config.php`

    'components' => [
        'db' => [
            'tablePrefix' => 'mymodule_',
        ],
    ]

Module config is loaded in this way:

    public function init()
    {
        parent::init();

        // Initialize the module with the configuration loaded from config.php
        $path = $this->basePath . '/config.php';
        if (file_exists($path)) {
            \yii::configure($this, require $path);
        }
    }

**Comment by samdark** [comment]
I don't think configs are merged.

**Comment by SilverFire** [comment]
Configs are not deeply-merged.

**Comment by uaoleg** [comment]
According to documentation it should: http://www.yiiframework.com/doc-2.0/guide-structure-modules.html#accessing-components-from-within-modules

**Comment by SilverFire** [comment]
I have misunderstood the original issue description.
This feature was introduced in PR https://github.com/yiisoft/yii2/pull/14350 by @SamMousa 

Unfortunately, the documented behavior is not tested. @uaoleg could you submit a PR with failing test?

**Comment by SamMousa** [comment]
@SilverFire my PR was not about config merging, there was a different issue for this, where I came to the conclusion that merging is not desired: https://github.com/yiisoft/yii2/issues/15089

**Comment by SilverFire** [comment]
Then what is this documentation about? https://github.com/yiisoft/yii2/pull/14350/files#diff-89d108ebaf09973620d6127f7210be31R274

**Comment by SamMousa** [comment]
It is about tree traversal, and apparently it is a bit unclear .. 
The example shows 2 partial configuration, the merging is an assumption due to forementioned unclarity.

The idea is that you can replace configuration, merging is not intended nor desired here.

I'll create a PR for the documentation soon.

**Comment by SamMousa** [comment]
@uaoleg Could you check if this is more clear for you?

https://github.com/SamMousa/yii2/blob/68795c9c94273c8e75dc6b79853e446687e38f55/docs/guide/concept-service-locator.md
