### ISSUE TITLE
Write a best Practice about how to reach vendor modul config if module is not requested

### ISSUE THREAD

**Issue by papppeter** [yiisoft/yii2#15499]
Hi,

we write a lot modules for our project, which are installed per composer, this way we can use it for multiple projects. 

What is the best practice to get a module instance inside a module, if the module itself is not requested? There is only way i think: Yii::$app->getModule('ID'). But this way the ID is static. If we have two modules using the same ID, i know there is a little chance but we won't be able to use them side by side, without rewriting one of them.

thanks Péter

**Comment by rob006** [comment]
Right now there is no convenient way to do this. See #14421.
