### ISSUE TITLE
Cant save empty record to DB

### ISSUE THREAD

**Issue by kryvel** [yiisoft/yii2#15500]
Hello! 

I have a simple model. All fields are optional - have default values set in DB.

I would like to save an empty object
`
$model = new Item();
$model->save()
`
But I get following error

`
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
The SQL being executed was: INSERT INTO ``items`` (``id``) VALUES (DEFAULT)
`

Is it expected behavior ?

Also when I try to execute this SQL directly I get the same error message:

`
mysql> INSERT INTO ``items`` (``id``) VALUES (DEFAULT);
`
`
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
`
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11?
| PHP version      | 7.0 
| Operating system | Debian 9
| MySQL | Server version: 5.7.20-18-log - Percona Server (GPL), Release '18', Revision '7ce54a6deef'

**Comment by schmunk42** [comment]
You have a primary key defined and you get the error `Duplicate entry '0' for key 'PRIMARY'`, since it's empty. Use an auto-increment value for you PK.

**Comment by kryvel** [comment]
PK has AUTO_INCREMENT, looks like this is syntax issue.
When I set any of attributes it works, this error appears only when I try to save an emtpy model.

Following also works
`
INSERT INTO `items` VALUES();
`

**Comment by schmunk42** [comment]
Can you show the schema of the table?

**Comment by kryvel** [comment]
```
CREATE TABLE `items` (
  `id` int(11) NOT NULL,
  `field1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `field2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `field3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comment` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `items`  ADD PRIMARY KEY (`id`);

```

**Comment by schmunk42** [comment]
Hmmm, I do not get an error when using 

    INSERT INTO `items` (`id`) VALUES (DEFAULT)

when I have a primary key. 

I only can reproduce the error you mentioned in the first comment, when **not** having a PK and a default value of `0`, can you confirm that? What happens when you execute the insert statement on a table with auto-increment PK?

**Comment by samdark** [comment]
Same here.

**Comment by kryvel** [comment]
I just recreate table and try again

```
CREATE TABLE `items` (
  `id` int(11) NOT NULL,
  `field1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `field2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `field3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comment` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `items`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `items`  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

```

First execution 
```
INSERT INTO `items` (`id`) VALUES (DEFAULT);
```
is Ok.  Row with (0, NULL, NULL, NULL, NULL) was inserted
Second execution of 
```
INSERT INTO `items` (`id`) VALUES (DEFAULT);
```
gives same error  - #1062 - Duplicate entry '0' for key 'PRIMARY'

But when I execute 
```
INSERT INTO `items` VALUES ();
```
row is successfuly inserted and `id` is auto incremented. so I have rows 
```
0, NULL, NULL, NULL, NULL
1, NULL, NULL, NULL, NULL
2, NULL, NULL, NULL, NULL
```

**Comment by kryvel** [comment]
Thanks @bizley . Looks very similar. So, because this is probably MySQL bug maybe it is good to create workaround ?

**Comment by samdark** [comment]
@kryvel what's the query issued by Yii?

**Comment by samdark** [comment]
I don't get why you're successfully executing `INSERT INTO `items` (`id`) VALUES (DEFAULT);` while similar SQL generated by Yii fails.

**Comment by bizley** [comment]
Isn't this the case where only first one is ok and all following are not?

**Comment by samdark** [comment]
If it fails with SQL then I don't see how we can provide workaround.

**Comment by kryvel** [comment]
Only first execuiton of  `INSERT INTO items(id) VALUES (DEFAULT);` is Ok, if table does not have PK id == 0
As workaround I suggest pass NULL instead of DEFAULT  (only for PK), because following query works fine:
```
INSERT INTO `items` (`id`) VALUES (NULL);
```
