### ISSUE TITLE
exist validator fail on string in integer field

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#15511]
### What steps will reproduce the problem?
    public function rules(): array
    {
        return [
            [
                ['id', 'parent_id'],
                'integer',
            ],
            [
                'name',
                'unique',
                'targetAttribute' => ['name', 'parent_id'],
            ],
        ];
    }

send post 
name = lol
parent_id = fff

### What is the expected result?
     correct validate
### What do you get instead?
    "name": "Database Exception",
    "message": "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"ffff\"\nThe SQL being executed was: SELECT EXISTS(SELECT * FROM \"osm_region\" WHERE (\"osm_region\".\"name\"='lol') AND (\"osm_region\".\"parent_id\"='ffff'))",

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.1
| Operating system | ubuntu

**Comment by RSalo** [comment]
Are you sure you do validate() and doesn't do save(false)?

**Comment by rob006** [comment]
You should use `[['id', 'parent_id']', 'filter', 'filter' => 'intval']`.

**Comment by mariovials** [comment]
I have the same problem, how can I solve it?
FilterValidator didn't work for me
