### ISSUE TITLE
Yii2-debug  ezyang/htmlpurifier version low

### ISSUE THREAD

**Issue by hx0930** [yiisoft/yii2#15519]
I'm sorry I can't speak English, I hope I can help others

### What steps will reproduce the problem?
unix |  mac

vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModuleManager.php 
:178  bug  class_exists case-sensitive
:86   forms  -> Forms

vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModule/Forms.php
:11  forms => Forms

### What is the expected result?
show debug page

### What do you get instead?
not found  HTMLPurifier_HTMLModule_forms

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |   PHP 7.2.1 (
| Operating system | mac  and  3.10.0-693.2.2.el7.x86_64  x86_64 GNU/Linux

**Comment by hx0930** [comment]
Upgrade ezyang/htmlpurifier  version

**Comment by samdark** [comment]
Can't reproduce. We have ` "ezyang/htmlpurifier": "~4.6",` constraint that installs latest 4.9 without problems.
