### ISSUE TITLE
Update phpunit dev-dependency

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#15512]
### What steps will reproduce the problem?

Run `phpunit`

### What is the expected result?

No errors/warnings from PHPunit.

### What do you get instead?

```
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /yii2/vendor/phpunit/phpunit/src/Util/Getopt.php on line 38
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.2
| Operating system | Debian Linux

See also https://github.com/sebastianbergmann/phpunit/issues/2887#issuecomment-348459163

Are there special reasons why this is pinned to `4.8.34`? The `platform` in `composer.json` also needs to be updated, I think. Is it `5.4`, because this is the current minimum requirement?

How do you make tests run on Travis due to this (by disabling) deprecated warnings?

**Comment by samdark** [comment]
> Are there special reasons why this is pinned to 4.8.34?

Maybe but I can't remember.

> The platform in composer.json also needs to be updated, I think. Is it 5.4, because this is the current minimum requirement?

Yes.

> How do you make tests run on Travis due to this (by disabling) deprecated warnings?

I think they just run... https://github.com/yiisoft/yii2/blob/master/tests/bootstrap.php#L8

**Comment by rob006** [comment]
See #14973

**Comment by samdark** [comment]
Alright. That is correct.

**Comment by samdark** [comment]
Won't do that because of backwards compatibility. Instead we have patching in place to make PHPUnit work well with recent versions of PHP.
