### ISSUE TITLE
difference between findOne and find()->where()->one()

### ISSUE THREAD

**Issue by mortezakhademan** [yiisoft/yii2#15515]
Hi
in yii2 difference between these lines:
ShpOrderPromotionUsage::find()->where(['and',['order_id'=>$id],'coupon_id is not null'])->one()
and 
ShpOrderPromotionUsage::findOne(['and',['order_id'=>$id],'coupon_id is not null']);
the first line is Ok but second line don't work correctly.
yii version: 2.0.11.2
--

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findOne()-detail

> Note: As this is a short-hand method only, using more complex conditions, like ['!=', 'id', 1] will not work. If you need to specify more complex conditions, use find() in combination with where() instead.
