### ISSUE TITLE
Query Builder Not like shouldn't append `%`

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#15525]
I'm looking to use QueryBuilder and it seems that when using `LIKE` or `NOT LIKE` it automatically appends wildcard characters around the passed in string. 
> ['like', 'name', 'tester'] will generate name LIKE '%tester%'

This therefore restricts the use of the wildcards.
 As they can be applied like `"%match_end"` or `"match_start%"`.

### What steps will reproduce the problem?
`->andWhere(['not like', 'SUBSTR(FIELD_ID, -3)', 'Q%'])`

### What is the expected result?

`SUBSTR(FIELD_ID, -3) NOT LIKE 'Q%'`

### What do you get instead?

`AND (SUBSTR(FIELD_ID, -3) NOT LIKE '%Q!%%' ESCAPE '!')`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.1
| Operating system | XAMPP

Do let me know if I'm mistaken or using QueryBuilder wrong. :)

**Comment by SilverFire** [comment]
Indeed `LIKE` escapes `%` by default. See [docs](http://www.yiiframework.com/doc-2.0/yii-db-querybuilder.html#buildLikeCondition()-detail), there is a way to prevent escaping:

```php
->andWhere(['not like', 'SUBSTR(FIELD_ID, -3)', 'Q%', false])
```
