### ISSUE TITLE
Сделайте стандартный json validator

### ISSUE THREAD

**Issue by alekson** [yiisoft/yii2#15524]
Который работает примерно так (проверяет что можно в массив декодировать)

```
    protected function validateValue($value)
    {
        if (!is_string($value))
            return [$this->notStringMsg, []];

        json_decode($value);

        if (json_last_error())
            return [$this->invalidJsonMsg, []];

        return null;
    }
```

Не первый раз приходится писать свой костыль, делается просто, думаю многие спасибо скажут

**Comment by SilverFire** [comment]
Да, это может быть полезно. Правда, следом за этим у нас попросят JSON Schema Validator :)
Если есть настроение – можете предложить свою реализацию и прислать нам Pull Request.

**Comment by alekson** [comment]
JSON Schema Validator - сильно Уже и сложнее, а тут именно синтаксис json проверить без логики в нем.

Это актуально когда делаешь простенький конфиг и редактируешь textarea.

К сожалению нет времени разбираться как пуллить в yii2, но пример кода я скинул :)

Буду очень благодарен за внедрение.

**Comment by samdark** [comment]
Won't implement for the reasons highlighted in #15527.
