### ISSUE TITLE
ActiveForm doesn't invoke parent init().

### ISSUE THREAD

**Issue by panchenkodv** [yiisoft/yii2#15536]
### What steps will reproduce the problem?
Call $form = ActiveForm::begin()

### What is the expected result?
Parent init() will be triggered.

### What do you get instead?
Parent init() doesn't trigger.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.12-3
| Operating system | ubuntu16.04.1

**Comment by Alex-Code** [comment]
This is the same in other widgets too.

[`Block`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/Block.php)
[`ContentDecorator`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ContentDecorator.php)
[`DetailView`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/DetailView.php)
[`LinkPager`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php)
[`LinkSorter`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkSorter.php)
[`Pjax`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php)
[`Spaceless`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/Spaceless.php)

**Comment by panchenkodv** [comment]
Added in pull request
