### ISSUE TITLE
saveAs上传完成之后，然后model->save()的时候提示错误

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#15530]
### What steps will reproduce the problem?

我用uploadFile上传图片，可以上传成功，但是在model->save() 时报错，没有找到临时文件
详看图

### Additional info
![image](https://user-images.githubusercontent.com/1888094/35193712-c8da853a-fee1-11e7-8f4d-c1f3a275f99a.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1.11
| Operating system |win10 64

**Comment by huaiguoguo** [comment]
![image](https://user-images.githubusercontent.com/1888094/35193726-155bc220-fee2-11e7-9ac2-48fb774d6c5a.png)

谢谢大家

**Comment by huaiguoguo** [comment]
![image](https://user-images.githubusercontent.com/1888094/35193736-339c8792-fee2-11e7-84d6-0b7f59ef201a.png)

**Comment by Thoulah** [comment]
I see both D:\dev\ and D:\deve\. Are they both correct?
