### ISSUE TITLE
Add Gitlab CI template

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii2#15542]
### What steps will reproduce the problem?
-
### What is the expected result?
-
### What do you get instead?
-

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 5.6
| Operating system | Debian Jessie

**Comment by schmunk42** [comment]
See also https://github.com/yiisoft/yii2/blob/master/.gitlab-ci.yml

**Comment by rustamwin** [comment]
exists for advanced template?

**Comment by schmunk42** [comment]
@cebe Can I move the issue to yii2-app-advanced?

**Comment by rustamwin** [comment]
it is possible to add there https://gitlab.com/gitlab-org/gitlab-ci-yml

**Comment by schmunk42** [comment]
Will be something for https://github.com/yiisoft/yii2-app (2.1) IMHO

**Comment by samdark** [comment]
Moved.
