### ISSUE TITLE
Enh: class="" attribute in BaseHtml::renderTagAttributes()

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#15547]
Currently `BaseHtml::renderTagAttributes()` to render `class=""` attribute in addition to
simple string `"item active"` can handle array like `["item", "active"]`, **but this behavior is not documented**.

The suggestion is:

1.  Add ability to render `class=""` attribute with associative array like [`classnames`](https://www.npmjs.com/package/classnames) does for `Object`s:

    ```php
    'class' => [
        "item",
        "active" => $x === 42,
    ],
    ```

    Here result will be either `class="item"` or `class="item active"`.

    This can improve readability and will allow to utilize things like `ArrayHelper::merge()` for `class=""` attributes too.

2.  Extract rendering for `class=""` attribute in a method (similar to `style=""`) to make in extensible.

**Comment by Vovan-VE** [comment]
Using of arrays to render `class=""` attribute is not documented, but in fact array values are using.

Methods `addCssClass()` etc. already uses array keys to identify purpose/scope (say "role"). It would be a problem. The difference between role keys `"role" => "class"` and conditional class keys `"class" => condition` can be determined by strict `bool` check for value, but isn't it a hack?

I did not found tests for both of above together when trying to discover alternative for lack of documentation. There are only test to manipulate "roled" classes and to render simple arrays in class.

**Comment by klimov-paul** [comment]
> Using of arrays to render class="" attribute is not documented

???
What is this then?
https://github.com/yiisoft/yii2/blame/master/docs/guide/helper-html.md#L78-L126

**Comment by Vovan-VE** [comment]
Sorry, I meant inline documentation for methods.

**Comment by klimov-paul** [comment]
> I meant inline documentation for methods

Then what is this?
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1935-L1943

**Comment by Vovan-VE** [comment]
Yes, but this method does not mentioned anywhere and it does not describe, how `class=""` is rendering from array.

**Comment by samdark** [comment]
Could be improved by adding some `@see` references. @Vovan-VE could you prepare a pull request adding `@see` where you think they're needed? Thanks.
