### ISSUE TITLE
[Suggestion] Combining model scenarios with behaviors

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft/yii2#15555]
This is not an issue but a suggestion/proposal

In behaviors (say \yii\base\Behavior) we can have configurable property (array|string) that says that this behaviors will only be applied if certain scenario of a model is set.

For example

```php
class Post extends \yii\db\ActiveRecord 
{
    public function behaviors()
    {
        return [
            'audit_trail_log' => [
                'class' => \bedezign\yii2\audit\Audit::class,
                'scenarios' => ['create', 'update'],
            ],
        ];
    }    
}
```

here scenarios can have string or array as
`'*'` apply this behavior to all scenarios of that model (we can set this to default)

`'!*'` don't apply this behavior to all scenarios

`['create', 'update']` apply this behavior to a model only when this model have scenario 'create' or 'update'

`['!create', '!update']` apply this behavior to a model when this model have any scenario except 'create' or 'update'

`['!import']` apply this behavior to a model when this model have any scenario except 'import'

**Comment by samdark** [comment]
Could be done in the behavior itself. Plus, not all behaviors are attached to models so it couldn't be generalized well.
