### ISSUE TITLE
\Yii::$container->set(SomeClass::class, false)

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15551]
### What steps will reproduce the problem?
```php
\Yii::$container->set(SomeClass::class, false);
```
got unexpected behavior

### What is the expected result?
same of 
```php
\Yii::$container->set(SomeClass::class, function() {return false;});
```

### What do you get instead?
 ```php
\Yii::$container->_definitions[SomeClass::class]
``` 
contain 
```php
['class' => SomeClass::class]
```
instead 
```php
false
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14 dev
| PHP version      | 7.2.1
| Operating system |alpine3.7

**Comment by samdark** [comment]
1. I don't agree that returning `false` is expected behavior.
2. There's nothing in docs about booleans are supported.
