### ISSUE TITLE
Добавьте строгую проверку на валидацию INTEGER

### ISSUE THREAD

**Issue by maxim-niko** [yiisoft/yii2#15561]
Получаю данные через API, указываю в параметрах валидации поля тип 'integer'
Мне заходит строка с миллисекундами '1516806014539'

Мой валидатор не срабатывает, потому что видит цифры!!!
Результат - ошибка при сохранении в бд

Приведение к int в данном случае возвращает 2147483647, а в бд unsigned установлен!

Добавьте pls в валидатор максимальную длину для integer и получение null или 0, если в запросе пустая строка

### Additional info

| Q                          | A
| ----------------      | ---
| Yii version             | 2.0.13.1
| PHP version          | 7.1 x86 (XAMPP)
| Operating system | Windows x64

**Comment by rgen3** [comment]
Скиньте пример валидатора, в коде свойство, которое позволяет использовать проверку только на целочисленный тип.

Это свойство, которым можно задать, что проверяем только на int
https://github.com/yiisoft/yii2/blob/eb57d4191cbc5a2d8cf5a28345bc81a13e488fa1/framework/validators/NumberValidator.php#L30

По самому коду, никаких преобразований к int нет

**Comment by maxim-niko** [comment]
Ошибка в  этом

        $intForm = new DynamicModel(['is_int']);
        $intForm->addRule(['is_int'], 'required')
            ->addRule(['is_int'], 'number', ['integerOnly' => true]);

        $mustBeNull = '';
        $tooBigForInt = '1516806014539';// max size for INT is 4294967295

        $intForm->load(['is_int' => $mustBeNull], '');
        $intForm->validate();
        echo '<pre>';
        var_dump($intForm->is_int);//string(0) "" is not INT. It is string

        $intForm->load(['is_int' => $tooBigForInt], '');
        $intForm->validate();
        var_dump($intForm->is_int);//string(13) "1516806014539". It is BigInt. Max size for INT is 4294967295
        die();


Вот пример необходимых валидаторов. Если есть возможность, добавьте их в CORE

```
use yii\validators\NumberValidator;

class IntegerValidator extends NumberValidator
{
    public $unsigned = false;

    public $skipOnEmpty = false;

    public $min = -2147483648;

    public $max = 2147483647;

    protected $unsignedMax = 4294967295;

    public function init()
    {
        parent::init();

        if ($this->unsigned) {
            list($this->min, $this->max) = $this->getUnsignedValues();
        }

    }

    protected function getUnsignedValues(): array
    {
        return [0, $this->unsignedMax];
    }

}

class TinyIntegerValidator extends IntegerValidator
{

    public $min = -128;

    public $max = 127;

    protected $unsignedMax = 255;

}

class SmallIntegerValidator extends IntegerValidator
{
    public $min = -32768;

    public $max = 32767;

    protected $unsignedMax = 65535;

}

class MediumIntegerValidator extends IntegerValidator
{

    public $min = -8388608;

    public $max = 8388607;

    protected $unsignedMax = 16777215;

}

class BigIntegerValidator extends IntegerValidator
{

    public $min = -9223372036854775808;

    public $max = 9223372036854775807;

    protected $unsignedMax = 18446744073709551615;

}

```
