### ISSUE TITLE
Undefined variable in Request::getCsrfToken

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#15568]
In Request we have function getCsrfToken()

```php
public function getCsrfToken($regenerate = false)
    {
        if ($this->_csrfToken === null || $regenerate) {
            if ($regenerate || ($token = $this->loadCsrfToken()) === null) {
                $token = $this->generateCsrfToken();
            }
            $this->_csrfToken = Yii::$app->security->maskToken($token);
        }
        return $this->_csrfToken;
    }
```
When condition ($regenerate || ($token = $this->loadCsrfToken()) === null)  is FALSE
Then variable $token is undefined in $this->_csrfToken = Yii::$app->security->maskToken($token);
I have strange situation, when this is happens.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6
| Operating system | Debian

**Comment by samdark** [comment]
Indeed, may happen in case `$this->_csrfToken === null` and `$regenerate = false`.

**Comment by developeruz** [comment]
Right now the code looks like this (was changed by [this commit](https://github.com/yiisoft/yii2/commit/0b413b0e08b402c89c6f0494f158c5700c8e98ea)):
```php
   public function getCsrfToken($regenerate = false)
    {
        if ($this->_csrfToken === null || $regenerate) {
            $token = $this->loadCsrfToken();
            if ($regenerate || empty($token)) {
                $token = $this->generateCsrfToken();
            }
            $this->_csrfToken = Yii::$app->security->maskToken($token);
        }
        return $this->_csrfToken;
    }
```
@dicrtarasov does it solve your problem?

**Comment by samdark** [comment]
It should.

**Comment by samdark** [comment]
Thanks for checking it @developeruz.
