### ISSUE TITLE
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /data/www/walle-web/vendor/yiisoft/yii2/base/Object.php on line 77

### ISSUE THREAD

**Issue by hepanming007** [yiisoft/yii2#15569]
### What steps will reproduce the problem?
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /data/www/walle-web/vendor/yiisoft/yii2/base/Object.php on line 77
### What do you get instead?
Object rename

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.2.1
| Operating system |linux 2.6.32-042stab127.2

**Comment by Thoulah** [comment]
https://github.com/yiisoft/yii2/commit/5b2101f14cc3e23c679b41b53b439f379e0ad087
