### ISSUE TITLE
How can I execute multiple sql queries in one command and catch an Exception on fail one of them?

### ISSUE THREAD

**Issue by papalapa** [yiisoft/yii2#15579]
Not possible to parse $sql string and separate it to pieces before execute. I'm trying to run all in one.

### What steps will reproduce the problem?
```$sql = 'SELECT 2; WTF!';```
```$res = Yii::$app->db->createCommand($sql)->execute();```

### What is the expected result?
I`m waiting for database exception.

### What do you get instead?
All is right.
```$res = 1```

### Additional info
Another variant:
```$sql = 'WTF!; SELECT 2';```
```$res = Yii::$app->db->createCommand($sql)->execute();```
then
```yii\db\Exception```

In search for answer to my question I found this one: [https://stackoverflow.com/questions/6346674/pdo-support-for-multiple-queries-pdo-mysql-pdo-mysqlnd](https://stackoverflow.com/questions/6346674/pdo-support-for-multiple-queries-pdo-mysql-pdo-mysqlnd), but this take same effect (if syntax of first query is OK, an Exception will not throw).

I don`t want to receive results, but I want know, that all queries was OK (ALTERING TABLES, DROPPING TRIGGERS AND others).

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04

**Comment by rob006** [comment]
Duplicates #14856

**Comment by papalapa** [comment]
Thanks!
