### ISSUE TITLE
yii2 REST API Pagination

### ISSUE THREAD

**Issue by n-osennij** [yiisoft/yii2#15576]
Is it possible to disable pagination globaly (`use yii\rest\ActiveController;`)? I realy need to get all data every time. Create ` DataProvider` with ` 'query' => MODEL::find(),` on **each** Controller it is very uncomfortable... 

```
    public function prepareDataProvider()
    {
        return new ActiveDataProvider([
            'query' => Country::find(),
            'pagination' => false,
        ]);
    }
```
Other way - query with `per-page` parameter - `http://db5b/web/countries?per-page=1000000`. But it is not good solution, I think. Can I do `'pagination' => false,` for **all** application in **one** place???

If there are no solution in 2.0.13 yii version, can I edit yii original files? I think 20 items per page - this is default, which declared in some place?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.2.0
| Operating system | windows

**Comment by phpyii** [comment]
No need to change every place. You can Rewrite the ActiveDataProvider class.
`class ActiveDataProvider extends BaseDataProvider`
bootstrap.php
Yii::$classMap['yii\data\ActiveDataProvider'] = '@common/yii/data/ActiveDataProvider.php';

**Comment by n-osennij** [comment]
@phpyii it is possible more in detail?

**Comment by phpyii** [comment]
@n-osennij Sorry, there's a more simple way to do it
api\config\bootstrap.php
```
Yii::$container->set('yii\data\Pagination', ['defaultPageSize' => 15]);
```

**Comment by n-osennij** [comment]
@phpyii I use yii2-app-basic template without modeules or etc. So i have no api\config\bootstrap.php. I have the same folders as yii2-app-basic template
