### ISSUE TITLE
PHP Compile Warning 'yii\base\ErrorException' with message 'Unterminated comment starting line 1'

### ISSUE THREAD

**Issue by riyaskp** [yiisoft/yii2#15587]
### What steps will reproduce the problem?
`php yii message config/message.php`

### What is the expected result?
Console output
`Saving messages to messages/en-US/app/error.php...
Translation saved.

Saving messages to messages/en-US/app.php...
Translation saved.

Saving messages to messages/en-US/messages.php...
Translation saved.

Saving messages to messages/en-US/yii.php...
Translation saved.

Saving messages to messages/ar-SA/app/error.php...
Translation saved.

Saving messages to messages/ar-SA/app.php...
Translation saved.

Saving messages to messages/ar-SA/messages.php...
Translation saved.

Saving messages to messages/ar-SA/yii.php...
Translation saved.`
### What do you get instead?
Console output
`Saving messages to messages/en-US/app/error.php...
Translation saved.

Saving messages to messages/en-US/app.php...
Translation saved.

Saving messages to messages/en-US/messages.php...
Translation saved.

Saving messages to messages/en-US/yii.php...
Translation saved.

Saving messages to messages/ar-SA/app/error.php...
Translation saved.

Saving messages to messages/ar-SA/app.php...
Translation saved.

Saving messages to messages/ar-SA/messages.php...
Translation saved.

Saving messages to messages/ar-SA/yii.php...
Translation saved.

PHP Compile Warning 'yii\base\ErrorException' with message 'Unterminated comment starting line 1'

in /var/www/html/Pearch-API/vendor/yiisoft/yii2/console/controllers/MessageController.php:477`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1.?
| PHP version      |  7.1
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
Does that happen in your application? If yes, could you please isolate application code that, while being parsed, causes it?

**Comment by riyaskp** [comment]
Sorry, the error is not with Yii2, But this is happening when I add `"theseer/phpdox": "@stable"` to my composer
