### ISSUE TITLE
Broken links in documentation for Swiftmailer

### ISSUE THREAD

**Issue by craiglondon** [yiisoft/yii2#15586]
### What steps will reproduce the problem?
Visit http://www.yiiframework.com/doc-2.0/yii-swiftmailer-message.html#setTo()-detail, click on the Eye icon, https://github.com/yiisoft/yii2-swiftmailer/blob/master/Message.php#L137, link is no longer valid.

### What is the expected result?
Should open https://github.com/yiisoft/yii2-swiftmailer/blob/master/src/Mailer.php#L137

### What do you get instead?
https://github.com/yiisoft/yii2-swiftmailer/blob/master/Message.php#L137

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/build/controllers/PhpDocController.php should be adjusted.

**Comment by klimov-paul** [comment]
I can not see how `PhpDocController` is related to this issue: as far as I remember it is used only while package release.
It complains on HTML generated by [yii2-apidoc](https://github.com/yiisoft/yii2-apidoc), which is simply outdated in comparison with the latest changes at `yii2-swiftmailer` and should be updated.

Any way, I have [adjusted PhpDocController](https://github.com/yiisoft/yii2/commit/ab10e431955f7ea7b55e06d60b65e5dbebe831ea) to pick up extension aliases correctly.

**Comment by phelan** [comment]
![image](https://user-images.githubusercontent.com/1064363/35717538-c53dccc4-081a-11e8-92b6-2004c3671071.png)

**Comment by rugabarbo** [comment]
Same problem as #15861
Must be moved to https://github.com/yiisoft/yii2-apidoc
`PhpDocController` already adjusted (see the comment above).

**Comment by rugabarbo** [comment]
Related https://github.com/yiisoft/yii2-apidoc/issues/164

**Comment by cebe** [comment]
dulicate of yiisoft/yii2-apidoc#164 it assumed classes are on repo root and not in /src folder.
