### ISSUE TITLE
Empty yii params in console app

### ISSUE THREAD

**Issue by Gl00mY-ZeiZ** [yiisoft/yii2#15588]
### What steps will reproduce the problem?
In console application, when I'm running **./yii test/test**, I'm getting ``` array(0) {}``` in output.

```php
<?php

namespace console\controllers;

use Yii;
use yii\console\Controller;

class TestController extends Controller
{
    public function actionTest()
    {
        var_dump(Yii::$app->params); die;
    }
}
```

### What is the expected result?
array (merged) from common and console\config\params.php and console\config\params-local.php 

### What do you get instead?
``` array(0) {}```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.0.22
| Operating system | Ubuntu 16.04.3 LTS

**Comment by zhukovra** [comment]
@Gl00mY-ZeiZ Please show how you merge params from `config/params.php` and `console\config\params.php`

**Comment by Gl00mY-ZeiZ** [comment]
No manual merging. Only by Framework:
```php
#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
```
yii - standart file

**Comment by Gl00mY-ZeiZ** [comment]
other applications (backend and frontend) - see **Yii::$app->params**

**Comment by zhukovra** [comment]
I think it is better to ask in [yii2-app-advanced](https://github.com/yiisoft/yii2-app-advanced/issues) users.

**Comment by Gl00mY-ZeiZ** [comment]
in **require(__DIR__ . '/console/config/main.php'),**:
```php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);
```

**Comment by Gl00mY-ZeiZ** [comment]
missed **'params' => $params,** in console\config\main.php
Solved!
Close please!
