### ISSUE TITLE
Set @bower alias to bower-asset

### ISSUE THREAD

**Issue by kmergen** [yiisoft/yii2#15583]
Use of pjax for example.

Error Cannot find bower directory

In ``base\Application.php`` : 

```php
public function setVendorPath($path)
    {
        $this->_vendorPath = Yii::getAlias($path);
        Yii::setAlias('@vendor', $this->_vendorPath);
        Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
        Yii::setAlias('@npm', $this->_vendorPath . DIRECTORY_SEPARATOR . 'npm');
    }
```
If I install my vendors I don't have a ``bower`` directory.
It should change to 'bower-asset'.

Some assets use this alias e.g. ``JqueryAsset.php``

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version   |  7.0.22 
| Operating system | Windows 10

**Comment by schmunk42** [comment]
This has been updated in the application templates.

Do you use *asset-packagist*  or *fxpio/composer-asset-plugin*?
Which app template do you use?

**Comment by kmergen** [comment]
Here on a project with basic app.
I use yii2-user-module and then on route /user/admin I get  the error:
![image](https://user-images.githubusercontent.com/1640101/35632987-7de2c5f0-06a8-11e8-9e46-66b6c7f3f713.png)
Here my composer.json:
![image](https://user-images.githubusercontent.com/1640101/35633074-aaa4a55e-06a8-11e8-86b7-ccd5e028561f.png)
![image](https://user-images.githubusercontent.com/1640101/35633107-be96292a-06a8-11e8-8170-2f52786997bd.png)

But in base\Application.php the alias is set to 'bower'.

**Comment by kmergen** [comment]
Sorry.
I have an older basic app without the aliases key. 
Everything works.
