### ISSUE TITLE
Forming SQL query can't handle sorting minus operator (-column)

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#15585]
MySQL and MariaDB both support using the - operator in front of a column when sorting. It's an alternative to using COALESCE to reposition NULL values at the end of a sort ascending for instance.

I don't know if Microsoft SQL supports this as well, but would be nice if query builder would accept it. At the moment it throws unknown column exception (because it places the `-` in the quotes as part of the column name)
```
Unknown column '-sort_order' in 'order clause'
The SQL being executed was: SELECT `audio`.* FROM `audio` LEFT JOIN `playlist_audio` ON `audio`.`id` = `playlist_audio`.`audio_id` WHERE (`playlist_audio`.`playlist_id`=13) AND (`audio`.`type`='PROMO') ORDER BY `-sort_order`
```

The correct syntax for MySQL and MariaDB for the query to work is
```
SELECT `audio`.* FROM `audio` LEFT JOIN `playlist_audio` ON `audio`.`id` = `playlist_audio`.`audio_id` WHERE (`playlist_audio`.`playlist_id`=13) AND (`audio`.`type`='PROMO') ORDER BY -'sort_order'
```

Notice how in the `ORDER BY` the minus `-` is outside the column name `ORDER BY -'sort_order'`

Found the original MySQL documentation on the subject if interested
https://dev.mysql.com/doc/refman/5.7/en/order-by-optimization.html
```
The query uses ORDER BY with an expression that includes terms other than the index column name:

SELECT * FROM t1 ORDER BY ABS(key);
SELECT * FROM t1 ORDER BY -key;
```

**Comment by samdark** [comment]
If you want to use expressions, wrap SQL parts with `Expression` class. We're not going to implement support for that particular case cause it's very specific (even MySQL docs refer to it as an example of expression support). Also I'm not sure how that would affect index usage so I suggest sticking to good old `ASC` and `DESC`.

**Comment by ptheofan** [comment]
Expression works like a charm! Would look prettier withought it but no complains :)

Performance wise, according to a really quick test, all result in the same optimisations.
In practice `length` and `-length` resulted in exact same execution time. `abs(length)` however took as much as 5 times longer. So by the looks of it `-` is a very clean and convenient shortcut of pushing NULL at the bottom instead of using `coalesce`.

```
explain select * from audio order by length;
explain select * from audio order by -length;
explain select * from audio order by abs(length);

1	SIMPLE	audio	ALL	NULL	NULL	NULL	NULL	55	Using filesort

```

Let's not forget SQL is not really high performant anyways when enforcing data integrity (InnoDB + relations) - however it excels at data integrity. For performance critical components I prefer to use DBs that best suit the needs of the component (ex. Mongo, Elasticsearch, Graph db, etc).
