### ISSUE TITLE
Expression not bind params

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#15589]
### What steps will reproduce the problem?
        $this
            ->search()
            ->addOrderBy(new Expression("array_position(array[:sids], sid)", [':sids' => 1111]));

### What is the expected result?
    correct query
### What do you get instead?

"name":"Database Exception","message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  function array_position(text[], integer) does not exist

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1
| Operating system |ubuntu

**Comment by Alex-Code** [comment]
What SQL are you using?

**Comment by des1roer** [comment]
Postgresql 9.6

**Comment by Alex-Code** [comment]
Would you be able to get the raw SQL.
Either through the debug toolbar if installed or using something like `$query->createCommand()->rawSQL;`

**Comment by SilverFire** [comment]
`array_position` PgSQL function can not search for integers in text array.
Cast your array explicitly:

        $this
            ->search()
            ->addOrderBy(new Expression("array_position(array[:sids]::int[], sid)", [':sids' => 1111]));
