### ISSUE TITLE
[yii\data\DataFilter] cannot use gt, lt, gte and lte on [yii\validators\DateValidator]

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#15592]
`yii\data\DataFilter` cannot use gt, lt, gte and lte on `yii\validators\DateValidator`

### What steps will reproduce the problem?
create REST api that has datetime(or date) field and uses DataFilter, and try to use gt, lt, gte or lte

### What is the expected result?
Should return results from DB since you most certanly can compare dates in DB

### What do you get instead?
`422` error, since `yii\data\DataFilter::$operatorTypes` does not allow gt, lt, gte and lte on anything other than float and integer

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  5.6
| Operating system | Ubuntu 17.04

**Comment by samdark** [comment]
That's OK to add it. We don't have time to do it ourselves though... going to release 2.0.14 (last release w/ enhancements) 10th this month. Pull request is welcome.

**Comment by mikk150** [comment]
@samdark I will see, maybe I will do it tomorrow
