### ISSUE TITLE
rest api error handler issue with request type.

### ISSUE THREAD

**Issue by desaikalpesh34** [yiisoft/yii2#15594]
### What steps will reproduce the problem?
1. [Configuration](http://prntscr.com/i9ww2a)
2. [Url Rule](http://prntscr.com/i9wyn4)
3.[Controller](http://prntscr.com/i9wz06)
i have configured regerate action with get method.
when i am acess this action with get method result is expected
[Expected](http://prntscr.com/i9x06w)
when i am acess this same action with different(post) method result is not expected
[UnExpected](http://prntscr.com/i9x0z6)

### What is the expected result?
[Expected](http://prntscr.com/i9x06w)

### What do you get instead?
[UnExpected](http://prntscr.com/i9x0z6)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.7
| Operating system | Window 7

**Comment by machour** [comment]
What is your Response format? Seems to be RAW when it should be JSON
