### ISSUE TITLE
Do not to use session for \yii\web\User

### ISSUE THREAD

**Issue by vtvz** [yiisoft/yii2#15605]
I need check `validateAuthKey` every request in `\yii\web\IdentityInterface`.

But `\yii\web\User` uses `Session` to identity user and skips `validateAuthKey` if `$idParam` in `Session` exists.

I think there is two ways to fix this problem:

1. Run `validateAuthKey` every request and store authKey in session.
2. Ability to disable of using `Session` for identification completely.

Use cases: 
* "Logout everywhere" button which change `authKey` in DB.
* Using dynamic authKey. Create new key every `getAuthKey` and store it in another table. This key can have expire time (which is doesn't work because of session)

For example:

```php
class User extends ActiveRecord implements IdentityInterface
{
    public function getAuthKey()
    {
        $key = Yii::$app->security->generateRandomString();
        
        $model = new AuthKey($key);
        $model->save();

        return $key;
    }
    
    public function validateAuthKey($authKey)
    {
        return AuthKey::find()->byKey($authKey)->exists();
    }

    /* HIDDEN CODE */
}
```

Why not? But if I delete all records from `AuthKey` table, user will not be logged out. Because of sessions

**Comment by samdark** [comment]
There is ability to disable session: https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L81

**Comment by vtvz** [comment]
@samdark `$enableSession = false` disables cookies too

**Comment by vtvz** [comment]
This line of code will never be reached:
https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L641
Because of this line of code which is interrupts the function run:
https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L616
`sendIdentityCookie` should be run. But it isn't

**Comment by samdark** [comment]
Is it the same as https://github.com/yiisoft/yii2/issues/9718?

**Comment by vtvz** [comment]
This dirty trick works for me: 
```php
// config/_components.php
    'user'          => [
        'class'           => \yii\web\User::class,
        'loginUrl'        => ['/user/login/login'],
        'identityClass'   => \app\models\user\User::class,
        'enableAutoLogin' => true,
        'enableSession'   => true,

        'on ' . \yii\web\User::EVENT_AFTER_LOGIN => function (\yii\web\UserEvent $event) {
            /** @var \yii\web\User $user */
            $user = $event->sender;
            $session = Yii::$app->getSession();

            $session->remove($user->idParam);
            $session->remove($user->authTimeoutParam);
            $session->remove($user->absoluteAuthTimeoutParam);
        },
    ],
```

It's really dirty... And I don't like it at all. But it works. Maybe.

**Comment by pistolla** [comment]
How, why closed with all this dirtness

**Comment by samdark** [comment]
Because there's https://github.com/yiisoft/yii2/issues/9718
