### ISSUE TITLE
global config parameter in application that return full home action route

### ISSUE THREAD

**Issue by igorveremsky** [yiisoft/yii2#15602]
I creating multilingual app using Yii 2.0.13, and i have a problem with correct generating home url for current application language, I think the  best way to do it is `echo \yii\helpers\Url::to(['site/index']);`. Than, I think it will be greate if `site/index` will define in global application config, i google that config have params like `homeUrl, baseUrl, defaultRoute`, but no one from them returns `site/index`, so maybe it will be good to implement new params to application config that returns full home action? Or maybe in core application class set `defaultRoute` parameter to `site/index`. Is this idea correct, great and can possible to implement, what community think about it?

**Comment by samdark** [comment]
Haven't got it...

**Comment by igorveremsky** [comment]
@samdark sorry, don`t undestand what you mean by your comment. Its idea hasn`t sence or you don`t undestand what i want to say? :)

**Comment by samdark** [comment]
I don't understand it/

**Comment by igorveremsky** [comment]
@samdark idea is to add global config param that returns action route for home page. Why? Because it helps to returns correct url to home page when you create multilingual site.

**Comment by samdark** [comment]
`Url::home()`?

**Comment by samdark** [comment]
`Yii::$app->defaultRoute` has it.

**Comment by igorveremsky** [comment]
'defaultRoute' returns 'site', Url Helper need to get 'site/index' for correct generating home url

**Comment by igorveremsky** [comment]
we can define manual `defaultRoute` parameter as `site/index` but maybe in some tasks we need only `site` value and in others `site/index` value, my suggestion resolves this problem, but i don't know for sure is it have sence, so i opened this issue

**Comment by samdark** [comment]
If there's no `/`, add `/index`,
