### ISSUE TITLE
Email field supports all special characters

### ISSUE THREAD

**Issue by AjithLalps** [yiisoft/yii2#15601]
### What steps will reproduce the problem?
open a form that containing an email field, fill the email field with special characters in the username section
### What is the expected result?
email validation error message
### What do you get instead?
validated the email address

### Additional info
![screenshot-admin ld ajith-2018 02 05-16-57-48](https://user-images.githubusercontent.com/18158025/35802433-1e167d00-0a96-11e8-83f2-881989838e0d.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.13
| Operating system | ubuntu 16.04 
| Browser  | Chromium
| Version | 64.0

**Comment by samdark** [comment]
Not a bug: http://www.regular-expressions.info/email.html

If you need these to fail, customize `$pattern` and `$fullPattern`.
