### ISSUE TITLE
Elasticsearch 6.1.2 request failed with error  code 406

### ISSUE THREAD

**Issue by mozhgan-km** [yiisoft/yii2#15600]
hello when i want to send request to elastic search i got "application x-www-form-urlencoded is not supported status:406" error 
this is my code:
Customer::find()->where(['name' => 'test'])->one();
according to https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests any request needs to set content-type. so yii queries need to set content-type please fix it.

**Comment by Alex-Code** [comment]
According to the [docs](https://github.com/yiisoft/yii2-elasticsearch#requirements) ES6 isn't supported by the extension.

**Comment by cebe** [comment]
You need to use the 2.1 branch of elasticsearch extension for elasticsearch 5.0 or higher. It is not released as a stable version yet.

**Comment by mozhgan-km** [comment]
so if i want to use stable version of elasticsearch extension. i should use elasticsearch 4.x?
