### ISSUE TITLE
Logon redirects to another app url

### ISSUE THREAD

**Issue by ednotorres** [yiisoft/yii2#15604]
Hello!
I just saw the most weird thing. I created two Yii applications in one computer: The firsrt one authenticates with username/password stored in a database.
The second one authenticates with admin/admin (default authentication in Yii applications).
When I authenticate in the first app all looks fine, but then I do authenticate with admin/admin and after press the login buttom, I'm redirected to the first app home.

### What steps will reproduce the problem?
I authenticate in the first app. Nice.
I authenticate in the second app. The app redirects me to the first app home page.

### What is the expected result?
I have to be redirected to my second app home page.

### Additional info
I think the problem happens with cookies.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12 (both cases)
| PHP version      | 7.1.1
| Operating system | Windows 10.

**Comment by samdark** [comment]
I suspect you have these on the same domain.

**Comment by ednotorres** [comment]
Actually I use both web apps in localhost, which is the machine I develop the apps. I think it should not happen even in the same domain.

**Comment by samdark** [comment]
Well, by default session/remember me cookies are same-named so they clash when on the same domain.

**Comment by samdark** [comment]
Guide has a section about shared hosting, you may get some ideas from it if you still want to use one domain for all your projects (bad idea).

**Comment by ednotorres** [comment]
No, no, no. I just develop my apps in one domain, which is localhost. The apps runs in different websites. Although the experience was weird.

**Comment by samdark** [comment]
Yes, that's what I mean. Using same domain for multiple apps is asking for trouble (you can do it with Yii but you have to configure distinct cookie names, session names etc. etc.)

**Comment by ednotorres** [comment]
Ok. Got it.
Thanks a lot.
