### ISSUE TITLE
an idea for getDb() func.

### ISSUE THREAD

**Issue by RandalTeng** [yiisoft/yii2#15607]
### What steps will reproduce the problem?
when we use multi db components like name db1 => [] and db2 => [];
if we use it to getDb() func, it will get a expect for undefined component.

### What do you get instead?
in my mind, if give getDb() a parameter $dbComponentName;
code like:
```php
public function getDb($dbComponentName = 'db') 
{
    $dbComponent = $this->get($dbComponentName);
    if (!$dbComponent instanceof \yii\db\Connection){
        throw new InvalidConfigExpection('Error DB components name: '.$dbComponentName,0);
    }
    return $dbComponent;
}
```
it just my idea for use getDb() func convenience,
it where close ide(PhpStrom) Warning,
and getDb()->beginTranslation(); will get Ide Helper;

and we call getDb() in multi db components code:
```php
$db = Yii::$app->getDb()->beginTranslation(); // get default db component and begin xa.
// ... do something
$db->commit(); // or $db->rollback();

$dbSecond = Yii::$app->getDb('db-second')->beginTranslation(); // get second db called db-second component and begin xa.
// ... do something
$dbSecond->commit(); // or $dbFirst->rollback();

```

looking forward to your reply, thx.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 7.1.12
| Operating system | windows

**Comment by Alex-Code** [comment]
So you just want code completion in the IDE?
Could you do
```php
/* @var $db \yii\db\Connection */
$db = Yii::$app->dbOther;
```
