### ISSUE TITLE
Yii2 problem with the authentication and ajax requests

### ISSUE THREAD

**Issue by dcwq** [yiisoft/yii2#15619]
### What steps will reproduce the problem?
Firefox, Yii2, dektrium\user module

### What is the expected result?
1. Login error - JSON response with errors
2. Login success - 302 redirection to dashboard page

### What do you get instead?
1. HTML response with login page (isAjax return false, method performAjaxValidation not run but X-Requested-With: XMLHttpRequest send ok)
2. 302 not working, in developer tools request send ok, first 302, then 200, but browser not redirect 

### Additional info
**All working OK on localhost env, but on production server not working (diff HTTPS).** 
**All working OK in Chrom & Safari**

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.23
| Operating system | Linux (OVH Performance 1 hosting)

**Comment by samdark** [comment]
Seems to be a problem in dektrium\user module. Please report to the module repository.
