### ISSUE TITLE
Debug panel doesn't work with pretty Url

### ISSUE THREAD

**Issue by kyrylo-permiakov** [yiisoft/yii2#15612]
### What steps will reproduce the problem?
1. Use `public $enablePrettyUrl = true;` in UrlManager
2. Enable yii2-debug panel in config
3. When you visit the page using pretty URL - debug panel doesn't appear. Seems like this is the reason:
![image](https://user-images.githubusercontent.com/8026080/35871635-6e36ecb6-0b6d-11e8-99d9-619c51af5b7e.png)
4. When you visit the page without pretty URL - debug panel is OK.
![image](https://user-images.githubusercontent.com/8026080/35871716-9e801e2e-0b6d-11e8-9182-8824649ae1da.png)

### What is the expected result?
Debug panel works fine with pretty URL.
### What do you get instead?
Debug panel doesn't work fine.

### Additional info
Yii2 advanced template.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13 |
| PHP version     | 5.6 | 
| Operating system |

**Comment by samdark** [comment]
I'm using it w/ pretty URLs daily. Something else should be the reason.

**Comment by kyrylo-permiakov** [comment]
@samdark Hello. Thank you for the answer. What info can I give you to define the reason?

**Comment by Alex-Code** [comment]
The first pic shows a redirect response.
What do your url rules look like?

**Comment by kyrylo-permiakov** [comment]
@Alex-Code 
yes, redirect
Url rules about /debug/ ?

**Comment by samdark** [comment]
The difference on the screenshot is trailing `/`.

**Comment by samdark** [comment]
Do you have URL normalizer turned on?

**Comment by kyrylo-permiakov** [comment]
@samdark yes. and I have `$suffix = '\'`;

**Comment by samdark** [comment]
Aha, that's something to check.

**Comment by samdark** [comment]
Aha, that is the reason.

**Comment by kyrylo-permiakov** [comment]
@samdark I'm sorry, I see that you created bug issue for next Yii2 milestone, but can you please advice me what to do? Any manipulations with UrlNormalizer or $suffix don't work for me. Thanks.

**Comment by samdark** [comment]
That's for next debug toolbar release. Framework itself is doing fine.

If you want it bad you can dig into the problem, fix it in debug toolbar and send a pull request. We'll review/merge it and then you'll be able to set your debug dependency to `dev-master@dev` until release is tagged.

**Comment by kyrylo-permiakov** [comment]
@samdark Hello. I noticed next thing - when I'm removing my `$suffix = '/'`; from UrlManager - debug works fine, but I need this slash. Can you please advice me what should I write special rule for debug in UrlManager to disable slash only for debug?

`'rules' => [
		// ...
		'debug/<controller>/<action>' => 'debug/<controller>/<action>',
	],` 

That feature doesn't work for me. My thanks
