### ISSUE TITLE
Inability to set custom console command description programatically

### ISSUE THREAD

**Issue by jonmixnblend** [yiisoft/yii2#15616]
I'm requesting this feature after asking if what I wanted to do was already possible via the yii channel on freenode, and being told no, and asked to open an issue here.

Basically I have a Yii 2 app , advanced template, with a bunch of console commands, quite a few of which are functionally similar. I've abstracted that functionality out to an inherited class of yii\base\Action, in this case console\components\actions\PullSyncAction, and, with some parameters that I set up on that action, I can thus configure it under the actions method of my console controller to handle multiple actions, all of which kind of do a similar. It all seems to work well.

You can see a gist of what I mean [here](https://gist.github.com/jonmixnblend/128eef767f9edf594db229d28ef4df89)

My question is, would it be possible to introduce a way to set the action description (what shows up next to the console command on the command line) programatically in the actions method array of the controller, rather than culling the description from the comment above the action.

With the current method of using the comment above the action, and with no way to set the description programatically via that actions array, I can't provide descriptions to each of my controller actions.

**Comment by samdark** [comment]
You can do so via:

- https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L428
- https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L440
- https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L450
- https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L460
- https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L482
- https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L540
