### ISSUE TITLE
Escape % on like condition

### ISSUE THREAD

**Issue by AnticDroid** [yiisoft/yii2#15610]
### What steps will reproduce the problem?
Create query:
Player::find()->where(['like', 'playername', value. '%', false]);
OR
Player::find()->where(['like', 'playername', value. '%', []]);

### What is the expected result?
will produce query
select * from player where playername like "value%"

### What do you get instead?
select * from player where playername like "%value%%"

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1
| Operating system | osx

**Comment by Alex-Code** [comment]
If you use the `LIKE` operator the value will be wrapped with the wildcard characters, you don't need to add them.
```php
$value = 'name here';
Player::find()->where(['like', 'playername', $value]);
```
will produce
```sql
select * from player where playername like "%name here%"
```
If you just want the one wildcard you can use an `Expression`
```php
$value = 'name here';
Player::find()->where(['like', 'playername', new Expression(':value', [':value' => $value . '%'])]);
```
will produce
```sql
select * from player where playername like "name here%"
```

**Comment by AnticDroid** [comment]
Thx for  quick reply.
With Expression it works

**Comment by rob006** [comment]
This is actually a bug, see #15630.
