### ISSUE TITLE
Использование di с phpstorm

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2#15613]
Я начал использовать di в yii2 и сразу заметил что phpstorm не понимает переопределение классов. Плагины на yii стоят.

Например, у меня есть такая конфигурация:
```php
'container' => [
    'definitions' => [
        'Vendor\Library\ClassA' => [
            ['class' => 'common\components\ClassB']
        ],
    ]
]
```

Test.php
```php
use Vendor\Library\ClassA;

class Test
{
    /**
     * @var ClassA
     */
    protected $classA;

    public function __construct(
        ClassA $classA
    ) {
        $this->classA = $classA;
    }
    
    public function test()
    {
        // При наборе phpstorm показывает подсказки для ClassA, а нужно для ClassB.
        $this->classA->get...
    }
}
```
Решение c [PhpStorm Advanced Metadata](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata) не подходит или я просто не смог его настроить для di. Если это возможно, было бы хорошо иметь в документации пример использования. Допускаю что я неправильно использую di в данном случае.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1

**Comment by samdark** [comment]
А он и не должен. Хинтинг происходит на интерфейс и только методы этого интерфейса можно использовать. Иначе всё это не имеет никакого смысла.

**Comment by SilverFire** [comment]
Можете предложить такое улучшение в https://github.com/nvlad/yii2support

**Comment by springimport** [comment]
@samdark Я правильно понимаю что если нужно расширять базовый класс, то нужно во всех местах в use прописывать новый класс?

**Comment by springimport** [comment]
@SilverFire По ответу @samdark теперь не уверен что это нужно. Я то привык после mageno 2 что могу сделать preference для любого класса или интерфейса на свой с дополнительными методами.

**Comment by samdark** [comment]
@springimport если нужно расширять базовый класс своими методами и использовать эти методы, что-то тут не так с точки зрения DI-контейнера. Весь его смысл в том, что мы спрашиваем определённый интерфейс. Если вдруг мы начинаем вызывать методы, которых в этом интерфейсе нет, то это сигнал, что **интерфейс** изменился.

**Comment by SilverFire** [comment]
Да, @samdark прав. Я неправильно понял первоначальный вопрос.
