### ISSUE TITLE
Yii2 Dinamic add attributes to model form join table

### ISSUE THREAD

**Issue by ak-el-a** [yiisoft/yii2#15635]
Hi!

I want to add new fields to my model from join table with language parameters.  Now I'm adding static fields in model  and use it as $model->name_ru (as example) in my code. 

```
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%country}}".
 *
 * @property integer $country_id
 * @property string $ident
 
 *
 * @property Company[] $companies
 * @property CountryDescription[] $countryDescriptions
 */
class Country extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    
    /*добавить сюда при добавлении языков*/
   public $language_id_ru; 
   public $name_ru;
   public $seo_title_ru;
   public $seo_descr_ru;
   public $seo_h1_ru;

   public $language_id_ua; 
   public $name_ua;
   public $seo_title_ua;
   public $seo_descr_ua;
   public $seo_h1_ua;
```

But when I add new languages I must add new  languages fields in my model. I want that this be automatic.

This model has relation

```
    public function getCountryDescriptions()
    {
        return $this->hasMany(CountryDescription::className(), ['country_id' => 'country_id']);
    }

```
Maybe I can to use this relation, do i can?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.
| PHP version      | 5.6

**Comment by samdark** [comment]
Sounds like too specific use case. Don't think it is a good idea to add it to framework.

**Comment by ak-el-a** [comment]
I want add fields from langueges tables to main table and use them to view or edit. 
What's bad about it? This structure give way to simple adding language into site and edit languages fields in all tables.
I can give all languages fields to edit like this
```
 <?php foreach ($langs as  $lang):?> 
        <div id="set-<?=$lang->url?>" class="tab-pane fade in <?php if (empty($active)) { echo 'active'; $active = 1;}?> lang-group lang-group-<?=$lang->url?>"> 
    	 
    	<?= $form->field($model, 'language_id_'.$lang->url)->hiddenInput(['value'=>$lang->id])->label(false) ?>
    	<?= $form->field($model, 'name_'.$lang->url)->textInput(['maxlength' => true]) ?>
        
    	</div>
    <?php endforeach;?> 
```
And save them afterSave this model.

I tried to add some code like this to model, but then  base fields not saved. 
```
private function magic($name, $value) {
        $this->$name = $value;
    }

    function __set($name, $value) {
        
            $this->magic($name, $value);
    }
```
Adding specific field - it`s bad way, but i want use $model->name_ru (as example) in my code without declare this field in model.

**Comment by rob006** [comment]
> Adding specific field - it`s bad way, but i want use $model->name_ru (as example) in my code without declare this field in model.

If you need this, you need to overwrite `__get()` and `__set()` to handle only your attributes and call `parent::__get()` and `parent::__set()` for everything else. 

But this is probably not worth it - with explicitly declared attributes you will have hints from IDE and any SCA tool, and more bulletproof code (no risk that typo in attribute name will be silently ignored).

**Comment by ak-el-a** [comment]
So, What should I do? Use somethink like this to save fields from languages table.
```
if ($model->save())
            {
            	if (Model::loadMultiple($params, Yii::$app->request->post()) )
                {
                    foreach ($params as $param) {
                        $param->save(false);
                    }
                }
                return $this->redirect(['view', 'id' => $model->product_id]);
            }
```
Or advise another way.

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/ar-variation
https://github.com/yii2tech/ar-role
