### ISSUE TITLE
Override actions in child controller

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2#15637]
Here is a code from framework (https://github.com/yiisoft/yii2/blob/2.0.13.1/framework/base/Controller.php#L219)
```php
public function createAction($id)
{
    if ($id === '') {
        $id = $this->defaultAction;
    }
    $actionMap = $this->actions();
    if (isset($actionMap[$id])) {
        return Yii::createObject($actionMap[$id], [$id, $this]);
    } elseif (preg_match('/^[a-z0-9\\-_]+$/', $id) && strpos($id, '--') === false && trim($id, '-') === $id) {
        $methodName = 'action' . str_replace(' ', '', ucwords(implode(' ', explode('-', $id))));
        if (method_exists($this, $methodName)) {
            $method = new \ReflectionMethod($this, $methodName);
            if ($method->isPublic() && $method->getName() === $methodName) {
                return new InlineAction($id, $this, $methodName);
            }
        }
    }
    return null;
}
```

What's the justification for checking `actions` first and not vice versa. Now if I have `BaseController` with some logic for all other controllers (such as default actions, behaviours...) and I have following defined in there:
```php
public function actions()
{
    return [
        'error' => [
            'class' => 'yii\web\ErrorAction',
        ],
    ];
}
```

I can't override just the `error` action with inline action in one of the child controller, and I need copy paste all the common logic. (The same applies for any action defined in parent)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | NA
| Operating system | NA

**Comment by rob006** [comment]
```php
public function actions()
{
    $actions = parent::actions();
    unset($actions['error']);
    return $actions;
}
```

?

**Comment by armpogart** [comment]
lol, sorry. I didn't think to do that the easy way)). I was trying to override the action and define action with the same name and using `InlineAction`...
