### ISSUE TITLE
Why method ActiveField::getInputId() is protected?

### ISSUE THREAD

**Issue by berosoboy** [yiisoft/yii2#15634]
I think it would be useful to consult the input id directly from the activeField object

| Q                | A
| ---------------- | ---
| Yii version      | since 2.0.7

**Comment by samdark** [comment]
What's your use case exactly?

**Comment by twisted1919** [comment]
Should't be http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#getInputId()-detail enough in case one needs to get the id ?

**Comment by berosoboy** [comment]
Yes, but the activeField can have a custom id. 
But I don't know if worth it. Just wondering.

**Comment by berosoboy** [comment]
Forget about it. Like @twisted1919  said, Html:unputId is enough
