### ISSUE TITLE
LikeConditionBuilder breaks BC

### ISSUE THREAD

**Issue by schmasterz** [yiisoft/yii2#15649]
### What steps will reproduce the problem?
ModelName::find()
                ->where([$condition])
                ->andWhere(['like', 'name', $name.'%', false]);
### What is the expected result?
SELECT * FROM `model_name` WHERE ($condition) AND (`name` LIKE '$name%')
### What do you get instead?
SELECT * FROM `model_name` WHERE ($condition) AND (`name` LIKE '%$name\\%%')"
Please note that $condition and $name are strings, and they represent a DB expression.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14-dev
| PHP version      | PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
| Operating system | Debian

**Comment by Shaeldon** [comment]
can confirm

**Comment by samdark** [comment]
I think it was fixed with https://github.com/yiisoft/yii2/commit/5e8fd58ddb9a64e7acb607fe0c89b7bc92053051. Are you trying latest master?

**Comment by schmasterz** [comment]
Yes, I can confirm that problem is fixed. Thank you
