### ISSUE TITLE
JS scripts registered with registerJs() should get their own <script> tags

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#15651]
If you register multiple JS scripts with `yii\web\View::regsiterJs()` at the same position, they will get imploded together and placed in a single `<script>` tag in the rendered HTML.

That results in a system that is generally more fragile – if any script has an error, JS will stop executing for that context. This could be as simple as forgetting to end the script with a semicolon, which can cause the JS interpreter to get confused in some cases.

Putting each script in its own `<script>` tag would be a very easy way to make the system more robust, with very little performance cost. It would also give `regitserJs()` the ability to have an `$options` argument like `registerCss()` has, which would resolve #11018.

**Comment by Renkas** [comment]
If there is an error in JS then wouldn't you want to know it ASAP? It's fastest way to spot a problem if all JS stops working. If only small part of it is not working then spotting the problem is much harder.

**Comment by brandonkelly** [comment]
I disagree, and so do browsers. It’s not like an error in one context will halt JS execution for the entire page, which seems to be what you’d want? Either way you will get a JS error in the console, so you can identify the issue.

Semantically, if you are calling `registerJs()` twice, it is for two different scripts, and separate `<script>` tags is how you communicate that to the browser, so it knows to execute them separately.

**Comment by cronfy** [comment]
Another problem is that different `registerJs()` scripts can use same variable/function names that will conflict if they are in the same scope. This is +1 pro to separate  `registerJs()` scripts from each other.

**Comment by samdark** [comment]
PRs could not be moved but I've left a link in the issue moved to yiisoft/view.
