### ISSUE TITLE
join relation override inherit where

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#15653]
### What steps will reproduce the problem?

Join a relation and override the default where condition from the relation.

```php
NavItem::find()
->select(['cms_nav_item.title', 'timestamp_update', 'update_user_id', 'nav_id'])
->joinWith(['updateUser' => function ($q) {
    $q->select(['firstname', 'lastname', 'id'])->where([]);
}, 'nav'])
->where(['cms_nav.is_deleted' => false])
->limit(10)
->orderBy(['timestamp_update' => SORT_DESC])
->asArray(true)
->all();
```

The relation inside the model:

```php
public function getUpdateUser()
{
    return $this->hasOne(User::class, ['id' => 'update_user_id']);
}
```
The find method from the User model:

```php
public static function find()
{
    return parent::find()->where(['is_deleted' => false]);
}
```

So the `$q->select(['firstname', 'lastname', 'id'])->where([]);` will override `where(['is_deleted' => false]);`.

btw: I'm sure there is also a better solution for this problem, but it was working in 2.0.13 so i thought it makes sense to report.

### What is the expected result?

Returns the array with results.

### What do you get instead?

In the current dev-master the `$q->select(['firstname', 'lastname', 'id'])->where([]);` does not override the relation where condition anymore. this will raise an exception:

```php
"SQLSTATE[42000]: Syntax error or access violation: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND (`id` IN ('1', '0'))' at line 1
The SQL being executed was: 
SELECT `firstname`, `lastname`, `id`
FROM `admin_user`
WHERE (()) AND (`id` IN ('1', '0'))"
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master
| PHP version      | 
| Operating system |

**Comment by SilverFire** [comment]
Will handle it this evening

**Comment by pistej** [comment]
I thing in all previous Yii versions `->where([...])` overwritten previously used `->where()`. You need use `->andWhere([...])` or `->orWhere([...])` to append where condition.

**Comment by nadar** [comment]
@pistej I know, but i did the overide on purpose, which does not work anymore.

**Comment by SilverFire** [comment]
Fixed, thank you for the report.

**Comment by nadar** [comment]
@SilverFire just installed the latest dev-master, works as expected. Thanks
