### ISSUE TITLE
Ошибка в документации или разворачивании пути для виджетов?

### ISSUE THREAD

**Issue by nvlad** [yiisoft/yii2#15656]
### What steps will reproduce the problem?
Создать виджет `/widgets/currency/Currency.php`
и представление для него `/themes/basic/widgets/currency/index.php` (согласно [документации](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/output-theming.md#%D0%A2%D0%B5%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2%D0%B8%D0%B4%D0%B6%D0%B5%D1%82%D0%BE%D0%B2-))
в методе run вызвать
```php
$this->render('index')
```

### What is the expected result?
рендринг представления

### What do you get instead?
ошибку "View not Found"

### Additional info
если представление переместить в `/themes/basic/widgets/currency/views/index.php` то всё работает нормально, но расходится с документацией

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | *
| Operating system | *

**Comment by bscheshirwork** [comment]
Оригинальное (не темизированое) представление у Вас существует?

**Comment by nvlad** [comment]
Нет, если оно существует, то происходит рендринг оригинального.

**Comment by nvlad** [comment]
каким образом будете решать проблему? интересуюсь для реализации поддержки представлений в yii2support

**Comment by bscheshirwork** [comment]
Любые предложения и готовые PR приветствуются.

**Comment by nvlad** [comment]
Предлагаю оставить как есть, просто поправить документацию:
1) если кто-то уже использовал темизаю для виджетов, то при обновлении фреймворка у него отвалятся темы
2) поддержка текущей версии тем для виджетов уже готова в плагине, не надо будет делать зависимость от версий Yii
3) меньше костылей вообще

Если согласны с предложением, по мере времени постараюсь в PR
