### ISSUE TITLE
HttpBasicAuth broke Session

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#15658]
Using HttpBasicAuth makes Session unusable, because PHPSESSIONID regenerates to new every request. Authentication is working fine, but session become empty.

Example, adding auth behavior.
```php
class Sync1CModule extends Module {
    public function behaviors() {
    	return [
    		'basicAuth' => [
    			'class' => HttpBasicAuth::class,
    			'auth' => function($username, $password) {
                              ... 
    			}
    		]
    	];
    }
}
```

The reason is in yii\web\User::switchIdentity()

```php
    public function switchIdentity($identity, $duration = 0)
    {
         .................
        $session = Yii::$app->getSession();
        if (!YII_ENV_TEST) {
            $session->regenerateID(true);
        }
       ..................
}
```
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7.0
| Operating system | Debian 8

**Comment by SilverFire** [comment]
```php
    			'auth' => function($username, $password) {
                              ... 
    			}
```

What's inside?

**Comment by dicrtarasov** [comment]
Not matter.... strcmp username and password.
```php
 $session = Yii::$app->getSession();
        if (!YII_ENV_TEST) {
            $session->regenerateID(true);
        }
```
destruct session anytime.

**Comment by SilverFire** [comment]
> Not matter.... strcmp username and password

No, it matters. Please, post the code here

**Comment by dicrtarasov** [comment]
Ok :))))))

```php
$user = UserModel::find()->where(['email' => $username])->one();
return !empty($user) && $user->validatePassword($password) ? $user : null;
```
So usermodel returned ok, authentication done, so how it prevent yii\web\User from 
```php
if (!YII_ENV_TEST) {
            $session->regenerateID(true);
        }
```

My workaround is to set User::$enableSession to false.

**Comment by samdark** [comment]
Would you please check if it works with 2.0.13.1?

**Comment by dicrtarasov** [comment]
Already have 2.0.13.1

**Comment by dicrtarasov** [comment]
define('YII_ENV_TEST', true) is also workaround :)))

**Comment by samdark** [comment]
Would you then please try code from master branch?

**Comment by dicrtarasov** [comment]
ok, 15 minutes, please ...

**Comment by dicrtarasov** [comment]
same result, PHPSESSIONID changes every request.
To resolve this problem temporary I have to turn session off:
```php
\Yii::$app->user->enableSession = false;
```

**Comment by dicrtarasov** [comment]
https://image.prntscr.com/image/fLdy8MalQcKL3e0mBVTL3A.png

**Comment by SilverFire** [comment]
Thank you for the report, fixed.

**Comment by SilverFire** [comment]
@dicrtarasov did the fix solve your problem?

**Comment by dicrtarasov** [comment]
Thank you very mutch. Your modification of User component completely fix this problem.
