### ISSUE TITLE
Incorrect FileTarget behavior when target is disabled

### ISSUE THREAD

**Issue by alexeevdv** [yiisoft/yii2#15662]
### What steps will reproduce the problem?
Add FileTarget to the logger targets and set `enabled` attribute to `false`

### What is the expected result?
No output is produced

### What do you get instead?
Directory for logFile is created.

### Additional info
Directory is created in `init()` method. Seems like `export()` would be more apropriate place for this.

| Q                | A
| ---------------- | ---
| Yii version      | `2.0.13`
| PHP version      | `5.*, 7.*`
| Operating system |`GNU/Linux`

**Comment by SilverFire** [comment]
Would you like to create a Pull Request?

**Comment by SilverFire** [comment]
Merged, thank you
