### ISSUE TITLE
Object of class yii\db\JsonExpression could not be converted to string using batchInsert

### ISSUE THREAD

**Issue by khvalov** [yiisoft/yii2#15661]
### What steps will reproduce the problem?

postgres field contains jsonb type, trying to make batch Insert using: createCommand()->batchInsert()->execute();

### What is the expected result?
Insert fields into DB table

### What do you get instead?
Error message: 

HP Recoverable Error – yii\base\ErrorException
Object of class yii\db\JsonExpression could not be converted to string
1. in /private/var/www/zzz/www/vendor/yiisoft/yii2/db/pgsql/QueryBuilder.php at line 466
                                        $value = 'FALSE';
                } elseif ($value === null) {
                    $value = 'NULL';
                }
                $vs[] = $value;
            }
            $values[] = '(' . implode(', ', $vs) . ')';
        }
        if (empty($values)) {
            return '';
        }
 
        foreach ($columns as $i => $name) {
            $columns[$i] = $schema->quoteColumnName($name);
        }
 
             
### Additional info

looks like _tostring pattern have to be implemented

**Comment by SilverFire** [comment]
Will handle

**Comment by khvalov** [comment]
Same issue with Command::update() method.

**Comment by samdark** [comment]
@khvalov please open new issue. Thanks.
