### ISSUE TITLE
Query select broken!

### ISSUE THREAD

**Issue by makroxyz** [yiisoft/yii2#15674]
### What steps will reproduce the problem?
```php
$query = Address::find()->select(['city', 'address'])->createCommand()->rawSql;
```
### What is the expected result?
SELECT city, address FROM tbl_address

### What do you get instead?
SELECT * FROM tbl_address

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0.25 
| Operating system | Ubuntu 16.04.3

**Comment by makroxyz** [comment]
Additional Info:
There was an imperfection in my code:
```php
$query = Address::find()->select(['city', 'address']);
// other where conditions

$query->select(['city', 'address'])->createCommand()->rawSql;
```
as you can see select is called 2 times with same colums... in this case query builder returns 
SELECT * ....

**Comment by SilverFire** [comment]
Fixed, thank tou

**Comment by makroxyz** [comment]
Thank you, please release it in 2.14.1!

**Comment by SilverFire** [comment]
Hope we'll release it a bit earlier – in 2.0.14.1 😉

**Comment by makroxyz** [comment]
Yep! :)
