### ISSUE TITLE
JsonExpression in Command::update() method

### ISSUE THREAD

**Issue by khvalov** [yiisoft/yii2#15684]
### What steps will reproduce the problem?
Update postgres table contains JSON(B) object using  $connection->createCommand()->update () method

### What is the expected result?

Updated record

### What do you get instead?

Database Exception – yii\db\Exception
Object of class yii\db\JsonExpression could not be converted to string
Failed to prepare SQL: UPDATE "object_attributes" SET "attr_value"=:qp2 WHERE "UUID" = :uuid and "attr_name"=:attr_name
↵
Caused by: yii\base\ErrorException
Object of class yii\db\JsonExpression could not be converted to string
in /private/var/www/zzz/www/vendor/yiisoft/yii2/db/Command.php at line 315

1. in /private/var/www/zzz/www/vendor/yiisoft/yii2/db/Command.php at line 263

**Comment by CSharpRU** [comment]
I faced the same thing after the update and it's really urgent for me, had to revert to 2.0.13.

**Comment by tQuant** [comment]
`yii\db\ArrayExpression` has the same error

**Comment by SilverFire** [comment]
The fix will be included in patch-release

**Comment by SilverFire** [comment]
I've created a test to verify that SQL builds successfully. See 2eba4b54f

Could anyone post exact piece of code to reproduce the problem, please?

![image](https://user-images.githubusercontent.com/4499203/36449129-86bb0184-1692-11e8-97b5-b73b4d8ee5e0.png)

**Comment by berosoboy** [comment]
I tested here, and noticed that the problem occurs when you don't wrap the value in a JsonExpression.
