### ISSUE TITLE
trace level should be changed to debug in levelMap

### ISSUE THREAD

**Issue by gogl92** [yiisoft/yii2#15687]
### What steps will reproduce the problem?
When you want to put 'debug' instead of 'trace' in the levels array of  a log target an error will be thrown.
`'levels' => ['info', 'debug', 'warning','error'],
`
### What is the expected result?
'debug' should work as 'trace'

### What do you get instead?
Unrecognized level: debug
yiisoft/yii2/log/Target.php line 200
`throw new InvalidConfigException("Unrecognized level: $level");`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0.9
| Operating system | Mac OSX El Capitan 10.11.6

static map in Target.php:187 
```
        static $levelMap = [
            'error' => Logger::LEVEL_ERROR,
            'warning' => Logger::LEVEL_WARNING,
            'info' => Logger::LEVEL_INFO,
            'trace' => Logger::LEVEL_TRACE,
            'profile' => Logger::LEVEL_PROFILE,
        ];
```
Should be changed to:
`            'debug' => Logger::LEVEL_DEBUG,
`
maybe use a refractor.

**Comment by alexeevdv** [comment]
But why? `'trace'` level is used in `Yii::debug()`

**Comment by samdark** [comment]
There's no `debug` in 2.0. 2.1 has it.
