### ISSUE TITLE
MultipartFormDataParser produces an ErrorException

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#15683]
### What steps will reproduce the problem?
Parse a request with using a `MultipartFormDataParser`.

### What is the expected result?
No errors occur.

### What do you get instead?
An `ErrorException` is being thrown:

>Only variables should be passed by reference

The exception is caused by a notices generated by [this line](https://github.com/yiisoft/yii2/blob/2.0.14/framework/web/MultipartFormDataParser.php#L323):

```php
$lastKey = array_pop(array_keys($current));
```

Should we extract `array_keys($current)` to a separate variable to fix this?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1
| Operating system | GNU/Linux

**Comment by samdark** [comment]
Please check 2.0.14.

**Comment by bscheshirwork** [comment]
link in the topic refer to the master https://github.com/yiisoft/yii2/blob/313be2a5d75951e48273c6dae04eba2ab879fba9/framework/web/MultipartFormDataParser.php#L323

**Comment by Kolyunya** [comment]
@bscheshirwork while the link indeed, refers to the `master` the very same code is still in `2.0.14`. Here's a link specifically for the [`2.0.14`](https://github.com/yiisoft/yii2/blob/2.0.14/framework/web/MultipartFormDataParser.php#L323).

**Comment by bscheshirwork** [comment]
Yes, of course. Your right.

**Comment by cebe** [comment]
Could you provide a test case or request content that produces this error?
