### ISSUE TITLE
Object of class yii\db\JsonExpression could not be converted to string in /vendor/yiisoft/yii2/db/Command.php:316

### ISSUE THREAD

**Issue by wtfmrpresident** [yiisoft/yii2#15694]
### What steps will reproduce the problem?
postgres field contains jsonb type

### What is the expected result?
update JSONB field in Postgres

### What do you get instead?
2018-02-20 11:46:46 [127.0.0.1][1][-][error][yii\db\Exception] yii\base\ErrorException: Object of class yii\db\JsonExpression could not be converted to string in /vendor/yiisoft/yii2/db/Command.php:316
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(4096, 'Object of class...', '/home/user/www/...', 316, Array)
#1 /vendor/yiisoft/yii2/db/Command.php(316): PDOStatement->bindValue(':qp0', Object(yii\db\JsonExpression), 2)
#2 /vendor/yiisoft/yii2/db/Command.php(260): yii\db\Command->bindPendingParams()
#3 /vendor/yiisoft/yii2/db/Command.php(1067): yii\db\Command->prepare(false)
#4 /vendor/yiisoft/yii2/db/ActiveRecord.php(247): yii\db\Command->execute()
....
Next yii\db\Exception: Object of class yii\db\JsonExpression could not be converted to string
Failed to prepare SQL: UPDATE "table" SET "name"=:qp0 WHERE "id"=:qp1 in /vendor/yiisoft/yii2/db/Command.php:264
Stack trace:
#0 /vendor/yiisoft/yii2/db/Command.php(1067): yii\db\Command->prepare(false)
#1 /vendor/yiisoft/yii2/db/ActiveRecord.php(247): yii\db\Command->execute()
#2 /vendor/yiisoft/yii2/db/BaseActiveRecord.php(801): yii\db\ActiveRecord::updateAll(Array, Array)

"name" attribute is JSONB field in postgres

### Additional info
[https://github.com/yiisoft/yii2/issues/15661](https://github.com/yiisoft/yii2/issues/15661)
the same, but this case is updating

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      |  7.2
| Operating system | Debian 9

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/15684
