### ISSUE TITLE
ExistValidator with targetRelation param ignore filter param

### ISSUE THREAD

**Issue by TomaszKane** [yiisoft/yii2#15692]
### What steps will reproduce the problem?
Add model validation rule:
```php
[['template_id'], 'exist', 'targetClass' => Template::class, 'targetAttribute' => ['template_id' => 'id'], 'filter' => function (ActiveQuery $query) {
    $query->andWhere(['type' => Template::TYPE_DEDICATED]);
}],

// ...

public function getTemplate()
{
    return $this->hasOne(Template::class, ['id' => 'template_id'])->inverseOf('dedicated');
}
```
works, but:
```php
[['template_id'], 'exist', 'targetRelation' => 'template', 'filter' => function (ActiveQuery $query) {
    $query->andWhere(['type' => Template::TYPE_DEDICATED]);
}],

// ...
// ...
```
not works.

### What is the expected result?

"filter" is respected.

### What do you get instead?

"filter is ignored.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.2.x
| Operating system | Kubuntu 17.10

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/pull/15701/
