### ISSUE TITLE
All console commands sent error after updating to 2.0.14

### ISSUE THREAD

**Issue by strafun** [yiisoft/yii2#15698]
### What steps will reproduce the problem?
run any of cosole actions with 'echo' inside. 
### What is the expected result?
echo text on screen
### What do you get instead?
text + Exception 'yii\web\HeadersAlreadySentException' with message 'Headers already sent in number of row with echo command.

All console controllers extend 'yii\console\Controller' controller 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version   5.6 && 7.1   | 
| Operating system linux && Windows|

**Comment by bscheshirwork** [comment]
related? #15682 

Also you can use in your code someone like this:

```php
\Yii::$app->response->data = 'output data';
```

for example
https://github.com/dektrium/yii2-user/pull/1003/files

**Comment by strafun** [comment]
Yes it is helps. Thanks. 
Yes related, but i use naked console not phpStorm and have same.
So as result all our cronjobs generate errors on prod after update. 
In YII2 guide using echo is ok... so i think it is not correct behavior. 
Hope it will be solved asap

**Comment by bscheshirwork** [comment]
so... I think we need check environment before throw error. In old php versions console pass headers after start output

**Comment by samdark** [comment]
Checked. Cannot reproduce. Tried with clean basic app and its `HelloController`. It echoes right in the action. Works well for me.

Any hints on how to get the error, @strafun?

**Comment by frontbear** [comment]
@samdark I got the same error `Headers already sent` too after upgrading to 2.0.14，and I will try to reproduce it later

**Comment by berosoboy** [comment]
@samdark I was able to reproduce it with clean basic app. When setting class of response component to yii\web\Response, rather than yii\console\Response.
```
'response' => [
    'class' => 'yii\web\Response',
],
```
I think people are doing this mistake

**Comment by berosoboy** [comment]
Plus, I suggest that \yii\web\Response::sendHeaders() should log a Yii::error(), rather than throwing a HeadersAlreadySentException

**Comment by frontbear** [comment]
reproduced. @berosoboy is right!

**Comment by samdark** [comment]
Why would one set console response to web response in a console command? That's configuration mistake, not a framework problem.

**Comment by samdark** [comment]
I mean are there cases with correct configuration that do not work?

**Comment by frontbear** [comment]
no. after fixes configuration, it works fine for me.

**Comment by SilverFire** [comment]
thank you for help

**Comment by strafun** [comment]
@samdark , @berosoboy totally right. I miss in error 'yii\web\HeadersAlreadySentException' WEB word)) 
And yes we have some issue in config. 
Now all is fine. 
Actually after .14 update we found a lot of bugs in our sysem. 
Thanks!
