### ISSUE TITLE
[Regression] Tinyint values in MySQL are being mapped to a string(1)

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#15691]
Since the upgrade to 2.0.14 (and I guess due to this change: #15203), yii2 is mapping tinyint values to a string(1). This is breaking all our validators.

### What steps will reproduce the problem?
Run gii on 2.0.14

### What is the expected result and what do you get instead?
`usage_based` is a tinyint (used as a boolean actually).
```patch
         return [
             [['name'], 'required'],
             [['description'], 'string'],
-            [['usage_based'], 'integer'],
             [['name'], 'string', 'max' => 100],
+            [['usage_based'], 'string', 'max' => 1],
         ];
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0
| Operating system | Ubuntu 16.04

**Comment by SilverFire** [comment]
@rob006

**Comment by michaelarnauts** [comment]
I just noticed that this issue is fixed in https://github.com/yiisoft/yii2-gii/issues/333 but that is not released yet. This means that all users currently upgrading to 2.0.14 will have this issue.

**Comment by samdark** [comment]
>  This is breaking all our validators.

Validators or gii?

**Comment by michaelarnauts** [comment]
The validators are refusing the data since the rules are changed, so actually only gii is broken.

**Comment by michaelarnauts** [comment]
Since yii2-gii broke due to this change in 2.0.14, I guess they should have been released together.
