### ISSUE TITLE
ActiveQuery via the getter magic function doesnt work anymore

### ISSUE THREAD

**Issue by StefanPATRICE** [yiisoft/yii2#15696]
### What steps will reproduce the problem?
Create a method that begin with *get* and that return a ActiveQuery
```php
class Dossier extends \yii\db\ActiveRecord
{
	 /**
	 * @return \yii\db\ActiveQuery
	 */
	public function getClientbis()
	{
		return Annuaire::find()
			->join('JOIN', 'annuaire_dossier', 'annuaire_dossier.id_annuaire=annuaire.id')
			->where(['actif'=>1, 'annuaire_dossier.type'=>'client', 'annuaire_dossier.id_dossier'=>$this->id]);
	}
}
```
Use this method via the getter magic method

```php
echo $dossier->clientbis->nom;
```

### What is the expected result?
Return a result of the ActiveQuery

### What do you get instead?
An error Invalid argument supplied for foreach()
in yii\vendor\yiisoft\yii2\db\BaseActiveRecord.php line 1732

### Additional info
Return a ActiveQuery without a proper hasOne() or hasMany() seem a bad practice for me, but i am not sure of that.
Still, it work well in Yii < 2.0.14.
Since this is a minor update, maybe a fix could ease the upgrade process, or a new Exception could explain the problem ?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 5.6.31
| Operating system | Windows 10

**Comment by loveorigami** [comment]
Yes, I have this bug
http://yiiframework.ru/forum/viewtopic.php?f=13&p=232604#p232604

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/pull/15702
