### ISSUE TITLE
Support sql function query result in join condition

### ISSUE THREAD

**Issue by AandD** [yiisoft/yii2#15690]
In ActiveRecord if you try to use JSON_VALUE or JSON_CONTAINS as hasOne or hasMany relation
You will recieve error Getting unknown property
|example| return $this->hasOne(ActiveRecord::className(), ['id' => 'JSON_VALUE(data, \'$.referenceField\')']);
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14-dev
| PHP version      | 7.1
| Operating system | Windows 10

**Comment by Alex-Code** [comment]
I don't think you'll be able to setup a relation like this as the framework will try matching the primary and foreign keys to model attributes.

Is the foreign key only in the JSON?

**Comment by bscheshirwork** [comment]
example of db structure please?

**Comment by AandD** [comment]
Ok  example table structure
|Table  A                                                          |
|ID (primaryKey INT) |  name(varchar)            |

|Table B                                                           |
|Id                             |  data (varchar (21000)) |
field data, could contain some `refField`, that if exists reference on table A.id.
On my opinion Its possible  add alias for such type functions
example
return $this->hasOne(ActiveRecord::className(), ['id' => ['aliasForRelation' => 'JSON_VALUE(data, '$.referenceField')']]);

**Comment by jurchiks** [comment]
Why would you ever have relation fields in DATA, and use them as such? That is terrible database design!
Extract that value into a separate column.

**Comment by jurchiks** [comment]
P.S. IMO a framework should never support terrible design.

**Comment by samdark** [comment]
I agree that it's quite bad structure. Let's close it.
