### ISSUE TITLE
HttpHeaderAuth сломали 

### ISSUE THREAD

**Issue by vyachin** [yiisoft/yii2#15693]
### What steps will reproduce the problem?
Делаем рест контроллер, добавляем 2 метода авторизации HttpBearerAuth::class, HttpBasicAuth::class. 
```
class StageTypeController extends Controller
{
    public function behaviors()
    {
        return [
            'authenticator' => [
                'class' => CompositeAuth::class,
                'authMethods' => [
                    HttpBearerAuth::class,
                    HttpBasicAuth::class
                ],
            ],
        ];
    }

```

Пытаемся авторизоваться используя Basic auth method. 

### What is the expected result?
Ожидается что, HttpBearerAuth не найдет в заголовке Authorization строку Bearer и закончит свою работу. В реальности он использует в качестве токена всю строку заголовка Authorization

### What do you get instead?
https://github.com/yiisoft/yii2/blob/master/framework/filters/auth/HttpHeaderAuth.php#L54-L61

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1 
| Operating system | ubuntu 16.4

**Comment by SilverFire** [comment]
@bboure @rob006 
Related to https://github.com/yiisoft/yii2/pull/15219
