### ISSUE TITLE
select(['*']) broken because of #15047

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#15703]
### What steps will reproduce the problem?

    /**
     * @return ActiveQuery
     */
    public function getItems()
    {
        $query = $this->hasMany(SubItem::className(), ['user_id' => 'id']);
        $query->select(['*']); // select gets unset
        $query->with(['city']); // NOTICE: Undefined index: id ... <-- relation gets broken, etc

### What is the expected result?
2.0.13 version behavior

### Additional info

#15047
The problem is here https://github.com/yiisoft/yii2/blame/2.0.14/framework/db/Query.php#L613

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/1b3526d8db208fbc834e98c8563993ec9c2c6f1a
