### ISSUE TITLE
Array field in PostgreSQL not compatible with ActiveField::checkboxList

### ISSUE THREAD

**Issue by soulhunter1987** [yiisoft/yii2#15710]
### What steps will reproduce the problem?
Create an array postgresql field. Try to use it with an ActiveForm widget checkboxList field. Field already has a value in database.

### What is the expected result?
Form is correctly displayed and checboxes are correctly checked according to array values from database.

### What do you get instead?
An exception is thrown when trying to open a form. 

### Additional info
The problem is that Html helper, when determening selected values, checks that $selection is an array or impelements Traversable, but ArrayExpression only implements ArrayAccess and Countable. So field's value is treated as a string and passed to strcmp(), which throws argument error. I think the best way would be to make ArrayExpression implement Iterable as well...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14?
| PHP version      | 7.0.27
| Operating system | Mac OS
<img width="1402" alt="2018-02-20 19 47 44" src="https://user-images.githubusercontent.com/2089893/36439959-1c034fc4-1677-11e8-865a-f325e1241f1d.png">

**Comment by soulhunter1987** [comment]
Also "each" validator is not capable of validation this field type, while it should be. First it checks only for "array" type, and second, it is not able to loop through field's values because ArrayExpression does not implement Iterable. Perhaps it would really be better to just use "array" native type for this field instead of ArrayExpression to solve those (possibly) numerous incompatibility issues?

**Comment by SilverFire** [comment]
There is a discussion in #15716 regarding reverting array casting to ArrayExpression object. Please, fell free to join. Thank you

**Comment by zhdanovartur** [comment]
I have the same problem. 
Great feature, but I think `ArrayExpression` is not a PATCH update, because it broke a lot of model getters, used before for Postgres array fields.

**Comment by soulhunter1987** [comment]
Did you also fix each validator to accept Traversable?

**Comment by SilverFire** [comment]
Nope. Could you create a separate issue, please?

**Comment by soulhunter1987** [comment]
#15760

**Comment by turboezh** [comment]
Hi, @SilverFire.
Another problem here now.
An `Array to string conversion` error happens at this line.
https://github.com/yiisoft/yii2/blob/033f2b4a13d31a5f202810eef9fad6e2c2f5e7bd/framework/helpers/BaseHtml.php#L943

![image](https://user-images.githubusercontent.com/1132740/38820676-342884e2-41a7-11e8-8a81-730e4f358a80.png)

**Comment by SilverFire** [comment]
Created a separate issue #16145
