### ISSUE TITLE
ReferenceError: attribute is not defined

### ISSUE THREAD

**Issue by memobr** [yiisoft/yii2#15711]
### What steps will reproduce the problem?
i have a bootstrap modal in it have ActiveForm without any action when open modal closed browser tells me ReferenceError: attribute is not defined
### What is the expected result?
expected no javascript errror

### What do you get instead?

```
ReferenceError: attribute is not defined
resetForm/</<
https://exchange.dev/assets/bf426f8e/yii.activeForm.js:447:25
each
https://exchange.dev/assets/2ce911ae/jquery.js:362:10
resetForm/<
https://exchange.dev/assets/bf426f8e/yii.activeForm.js:442:17
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      |  7.1
| Operating system | windows

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/15678
Will be fixed by https://github.com/yiisoft/yii2/pull/15681
