### ISSUE TITLE
Controller id is null in model

### ISSUE THREAD

**Issue by fmartiner** [yiisoft/yii2#15725]
### What steps will reproduce the problem?
I have 2 different controller and in login model i want to switch to corret db in base at controller->id

```php
class LoginModel extends \yii\db\ActiveRecord{
public static function getDb() {
		if(Yii::$app->controller->id==="controller1"){
			return Yii::$app->db1;
		} else if(Yii::$app->controller->id==="controller2"){
			return Yii::$app->db2;
		}
	}

}
```

### What's expected?
Trying to get property of non-object

Yii::$app->controller = NULL

### What do you get instead?
No exception and Yii::$app->controller->id = controller1

### Additional info

In yii2 version 2.0.7 the problem not exist.

| Q                | A
| ---------------- | ---
| Yii vesion     2.0.15-dev  |
| PHP version    5.5.17  |
| Operating system Windows Server 2008 R2 |

**Comment by samdark** [comment]
@fmartiner would you please check 2.0.13?

**Comment by samdark** [comment]
Unable to reproduce with the info given.

**Comment by samdark** [comment]
What's LoginModel?

**Comment by samdark** [comment]
Trace looks like it's debug panel, is it?

**Comment by fmartiner** [comment]
Loginmodel is a generic model who i use for switch db in base of controller id.
Other models extends Loginmodel. Any find use the getDb in loginmodel 

Yes trace is the stacktrace in the debug page
