### ISSUE TITLE
Proposal: Formatter::asPercent() able to accept a percentage

### ISSUE THREAD

**Issue by quique** [yiisoft/yii2#15721]
As of now, the value passed to Formatter::asPercent() must be a factor.  
E.g. 0.123 results in 12.30%.

I suggest adding an option so that asPercent() can also take a percentage value. 
E.g. 12.3 would result in 12.30%.

**Comment by SilverFire** [comment]
You can do it with division, no need to complicate formatter:

```php
$percent = 12.3;
$formatter->asPercent($percent/100);
```

**Comment by quique** [comment]
Yes, but in a GridView forces me to use a closure.

I admit it is not important, I just find it distracting.

Thanks.

**Comment by cebe** [comment]
whats the point in storing a percent value, if every time you want to work with it you need to think about adding `/100` to it? Its better to store the value to apply. In grid view you can add a converter:

```php
'value' => function($model) { return $model->myValue / 100; },
'format' => 'percent',
```

**Comment by quique** [comment]
Right...  In my case I don't do any calculations with those figures.  I just got them from an external program and show them.

If you think there is no need for the suggested option, it is not big deal for me to use the anonymous function.  It is just that I find it visually polluting.

Thanks for your time  :)
