### ISSUE TITLE
getUniqueColumns ignore columns keys

### ISSUE THREAD

**Issue by demenkov** [yiisoft/yii2#15728]
### What steps will reproduce the problem?

```
->select([
'prefix' => 'LEFT(name, 7)',
'prefix_key' => 'LEFT(name, 7)',
])
```

### What is the expected result?
```
[
'prefix' => 'LEFT(name, 7)',
'prefix_key' => 'LEFT(name, 7)',
]
```
### What do you get instead?

```
[
'prefix' => 'LEFT(name, 7)',
]
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14?
| PHP version      | 7.1
| Operating system | Linux

**Comment by SilverFire** [comment]
Introduced by https://github.com/yiisoft/yii2/pull/15047 /cc @dmirogin @samdark @rob006

**Comment by SilverFire** [comment]
Please see fix in https://github.com/yiisoft/yii2/pull/15730

**Comment by demenkov** [comment]
fix is worked, but i find another bug

**Comment by SilverFire** [comment]
Could you describe it?
