### ISSUE TITLE
MigrateController::optionAliases() have 2 same keys

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15724]
### What steps will reproduce the problem?

https://github.com/yiisoft/yii2/blob/3616dc5e742f1ae34f2455e4d9dfa1051e63f062/framework/console/controllers/MigrateController.php#L160-L171

| Q                | A
| ---------------- | ---
| Yii version      | 3616dc5e742f1ae34f2455e4d9dfa1051e63f062

**Comment by SilverFire** [comment]
Resolved in #15746
