### ISSUE TITLE
select() on existing ActiveQuery() returns random values

### ISSUE THREAD

**Issue by cloudcaptain** [yiisoft/yii2#15737]
### Example One
    $queryBase = Account::find()
           ->select(['one'=>'id', 'two'=>'name, 'three'=>'number'])
           ->where(['active'=1, 'archived'=0]);
    $queryData = $queryBase->select(['one'='number', 'two'=>'id']);
    $data = $queryData->createCommand()->queryAll();

### Result One
Expected : array generated from `SELECT number as one, id as two FROM ...`
Actual result : array generated from `SELECT * FROM ...`

### Example Two
    $queryBase = Account::find()
           ->select(['one'=>'a.id', 'two'=>'a.name, 'three'=>'a.number'])
           ->from(['a'=>Account::tableName()])
           ->innerJoin(['b'=>State::tableName()], 'a.state_id=b.id')
           ->where(['active'=1, 'archived'=0]);
    $queryData = $queryBase->select(['one'='a.name', 'two'=>'b.name']);
    $data = $queryData->createCommand()->queryAll();

### Result One
Expected : array generated from `SELECT a.name as one, b.name as two FROM ...`
Actual result : array generated from `SELECT b.name as two FROM ...`

### Additional info
It appears there is a problem with forming the "select" sub-array in the query object.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      |  7.0.25
| Operating system | ubuntu 16.04.1

**Comment by SilverFire** [comment]
Duplicates #15728, #15731
Will be fixed by https://github.com/yiisoft/yii2/pull/15730
