### ISSUE TITLE
Depend asset with customer register method

### ISSUE THREAD

**Issue by a761208** [yiisoft/yii2#15736]
### What steps will reproduce the problem?
**AAsset with customer register method:**
```PHP
namespace app\assets;

use yii\web\AssetBundle;
use yii\web\View;

/**
 * Class AAsset
 * @package app\assets
 */
class AAsset extends AssetBundle
{
    /**
     * @inheritdoc
     */
    public static function register($view)
    {
        $view->registerJs('var CONST_A = "123";', View::POS_HEAD, 'CONST_A');
        return parent::register($view);
    }
}
```
**BAsset depends AAsset:**
```PHP
namespace app\assets;

use yii\web\AssetBundle;

/**
 * Class BAsset
 * @package app\assets
 */
class BAsset extends AssetBundle
{
    public $depends = [
        'app\assets\AAsset',
    ];
}
```
**VIew:**
```PHP
/**
 * @var $this \yii\web\View
 */

\app\assets\BAsset::register($this);

$this->registerJs('alert(CONST_A);');
```

### What is the expected result?
The browser alert(123)

### What do you get instead?
Uncaught ReferenceError: CONST_A is not defined

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | PHP 7.0.27-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 14:12:46) ( NTS )
| Operating system | Ubuntu 16.04.3 LTS

**Comment by SilverFire** [comment]
Thank you for the report. Would you like to try to fix it and submit a pull request?

**Comment by a761208** [comment]
It seems the register method is an entry point for the asset bundle,
I'm not sure if I can take this method into the dependency relationship.

**Comment by a761208** [comment]
Or I can add another field `public $jsVars;` into AssetBundle just like the $js field.

**Comment by SilverFire** [comment]
> Or I can add another field `public $jsVars;` into AssetBundle just like the $js field.

No, it's not a good idea.

> I'm not sure if I can take this method into the dependency relationship.

Alright. We will handle this issue later.

**Comment by itma** [comment]
The problem happens because of the badly implemented AssetBundle::register() method (https://github.com/yiisoft/yii2/blob/master/framework/web/AssetBundle.php#L125). It only calls the dependency for a given asset class. It can be solved keeping the backwards compatibility like below:

Add a static variable to  yii\web\AssetBundle, for example:
`public static $deepDependency = [];`

Then changing the currenct implementaion of yii\web\AssetBundle::register() to:

`    public static function register($view)
    {
        foreach (static::$deepDependency as $dependency) {
            $dependency::register($view);
        }
        return $view->registerAssetBundle(get_called_class());
    }`

Using this may look like the below:

`class BAsset extends AssetBundle
{
    public static $deepDependency = [
        'app\assets\AAsset',
    ];

    /**
     * @inheritdoc
     */
    public static function register($view)
    {
        return parent::register($view);
    }

}`

Checked. Works enaugh good. I haven't got time to investigate it more, nevertheless I think this is the way to solve the problem.

**Comment by a761208** [comment]
I checked every Asset and call the register method manually.
```PHP
namespace app\assets;

use yii\web\AssetBundle;

/**
 * Class BAsset
 * @package app\assets
 */
class BAsset extends AssetBundle
{
    public $depends = [
        'app\assets\AAsset',
    ];

    /**
     * @inheritdoc
     */
    public static function register($view)
    {
        AAsset::register($view);
        return parent::register($view);
    }
}
```

**Comment by klimov-paul** [comment]
I am afraid his is unlikely to be ever fixed.
Keep in mind that you can configure particular Asset Bundle as `false` at `AssetManager::$bundles`, which removes its call completely.
Also note that `AssetBundle` is not meat to be 'intelegent' class - it is a 'class for data' a mere replacement for the arrays, we used previously for this purpose at Yii 1. Do not put your logic into it.

**Comment by a761208** [comment]
> Do not put your logic into it.

Got it.

**Comment by berosoboy** [comment]
You can do it:
```
class AAsset extends AssetBundle
{
    public function init()
    {
        parent::init();
        Yii::$app->getView()->registerJs('var CONST_A = "123";', View::POS_HEAD, 'CONST_A');
    }
}
```

**Comment by a761208** [comment]
@berosoboy That's a good idea.

**Comment by berosoboy** [comment]
@a761208 It's mentioned in the docs:
http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#dynamic-asset-bundles

**Comment by SilverFire** [comment]
Closing this issue then. Thank you
