### ISSUE TITLE
FileHelper::findDirectories option 'only' not working

### ISSUE THREAD

**Issue by Perino01** [yiisoft/yii2#15749]
### What steps will reproduce the problem?
$rootpath = Yii::$app->basePath . '/web/';
// in the root path there are some example sub directories eg. 3, 5
if (FileHelper::findDirectories($rootpatg, ['only' => ['4'],'recursive' => false])) {
            echo 'directory found';
        } else {
            // create directory
            echo 'directory not found';
        }

### What is the expected result?
The expected result should be nothing. In this case it would mean 'directory not found'.

### What do you get instead?
All directories within in the given path will be returned.
In this case the result is 'directory found', even the directory does not exist.

### Additional info
Maybe the filterPath($path, $options) function in BaseFileHelper is not right:
....
if (!empty($options['only']) && !is_dir($path)) {
            if (($except = self::lastExcludeMatchingFromList($options['basePath'], $path, $options['only'])) !== null) {..............
               
The exception never can be called, because with FileHelper::findDirectories, $path will always be a directory?! 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14?
| PHP version      | 
| Operating system |

**Comment by Izumi-kun** [comment]
According documentation the `only` is not valid option.
https://github.com/yiisoft/yii2/blob/4f80cda7130da5259ce93fe41eb681cbb70f30be/framework/helpers/BaseFileHelper.php#L483-L500

**Comment by samdark** [comment]
Confirmed what @Izumi-kun said.
