### ISSUE TITLE
Composer update throwing TransportException

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#15750]
### What steps will reproduce the problem?
composer update
### What is the expected result?
update tot 2.0.14 from 2.0.13
### What do you get instead?

>   [Composer\Downloader\TransportException]
>   The "https://packagist.org/p/yiisoft/yii2%2404553afe1151e11f11cfd6568909aad
>   dc790b5704fc4b6e4e859099aa971c9d5.json" file could not be downloaded (HTTP/
>   1.1 404 Not Found)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13?
| PHP version      |  5.6.21
| Operating system | windows 10

**Comment by samdark** [comment]
That's something with either packagist or your Internet connection. Can't be fixed from within Yii.
