### ISSUE TITLE
Links with target="_blank" should get rel="noopener noreferrer"

### ISSUE THREAD

**Issue by NabiKAZ** [yiisoft/yii2#15756]
## Description security bug
When using `target="_blank"` links:
```HTML
<a href="http://example.com" target="_blank">
   Example site
</a>
```
The page we're linking to gains partial access to the linking page via the `window.opener` object.
The newly opened tab can, say, change the `window.opener.location` to some phishing page:
```JS
window.opener.location = 'https://fakewebsite/facebook.com/PHISHING-PAGE.html';
```
Or execute some JavaScript on the opener-page on your behalf... Users trust the page that is already opened, they won't get suspicious.

## How to fix
Add `rel="noopener noreferrer"` to your outgoing links:
```HTML
<a href="http://example.com" target="_blank" rel="noopener noreferrer">
   Example site
</a>
```
Remember, that every time you open a new window via `window.open();` you're also "vulnerable" to this, so always reset the "opener" property:
```JS
var newWnd = window.open();
newWnd.opener = null;
```

## Refs
- https://mathiasbynens.github.io/rel-noopener/
- https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/
- https://sites.google.com/site/bughunteruniversity/nonvuln/phishing-with-window-opener
- https://github.com/danielstjules/blankshield
- https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
- https://dev.to/ben/the-targetblank-vulnerability-by-example

**Comment by NabiKAZ** [comment]
I'm working on this problem in core framework.

**Comment by samdark** [comment]
There's no such problem in the framework since it doesn't generate `target="_blank"` links at all. Always adding `noopener noreferrer` may be bad if you want to actually use referrer.

What do you plan to implement exactly?

**Comment by NabiKAZ** [comment]
I fixed.
If links contain `target="_blank"` append `rel="noopener noreferrer"` in the link, But if not contain `target="_blank"`, don't append `rel`, And so, If the user self add `rel`, so don't add rel twice.

**Comment by NabiKAZ** [comment]
Maybe can add `noopener` by default for security, but add an new option with `useOpener` boolean for don't append `noopener` in force mode, and tell to users about security alarm in manual.

**Comment by samdark** [comment]
That makes it inconsistent compared to HTML.

**Comment by definaru** [comment]
```
// https://www.example.com/images/logo.gif
echo Url::to('@web/images/logo.gif', true);
```

https://www.yiiframework.com/doc/guide/2.0/en/helper-url
https://www.yiiframework.com/doc/guide/2.0/en/helper-html

Just write a service that will inherit from URL helpers. We check if the link belongs to the site, which means it is internal, if the domain name differs from the domain of the current site, which means we add rel there, so that HTML helpers know which attributes to assign to external and internal links. Use helpers, everything is already set up and written by Yii developers — you just need to check the site domain. No match? = external link. So we add the rel attribute! 🤗😉
