### ISSUE TITLE
Exception on migration 

### ISSUE THREAD

**Issue by LyudmilaPetrova** [yiisoft/yii2#15753]
### What steps will reproduce the problem?
I have clean yii2-app-advanced and run _vagrant up_ command. 

### What is the expected result?

Migration without exeption and green tests out of the box.

### What do you get instead?

On vagrant up i've got an exeption:

shop: Migrated up successfully.
shop: Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::cookieValidationKey'
shop:
shop: in /app/vendor/yiisoft/yii2/base/Component.php:209
shop:
shop: Stack trace:
shop: #0 /app/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('cookieValidatio...', 'test')
shop: #1 /app/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\console\Request), Array)
shop: #2 [internal function]: yii\base\BaseObject->__construct(Array)
shop: #3 /app/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
shop: #4 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\console\\Req...', Array, Array)
shop: #5 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\console\\Req...', Array, Array)
shop: #6 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
shop: #7 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
shop: #8 /app/vendor/yiisoft/yii2/console/Application.php(219): yii\base\Module->get('request')
shop: #9 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->getRequest()
shop: #10 /app/yii_test(22): yii\base\Application->run()
shop: #11 {main}
shop:
shop: --> Create bash-alias 'app' for vagrant user

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | PHP 7.1.14-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  9 2018 09:33:27) ( NTS )
| Operating system | ubuntu16.04

**Comment by samdark** [comment]
Duplicated of
