### ISSUE TITLE
Pass $query as a parameter to IndexAction::prepareDataProvider()

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii2#15759]
Currently prepareDataProvider() uses $modelClass::find() to instantiate a query. But let's say that I want a little bit different query. It would be convenient if I could pass $query as a parameter to this method with default value null. In this case if it's not passed then method can use find() method to initialize a query (to keep backward compatibility).

Basically I need all functionality of prepareDataProvider() except that one line of query instantiation:
https://github.com/yiisoft/yii2/blob/master/framework/rest/IndexAction.php#L114

I could override the method prepareDataProvider() and copy/paste its whole implementation from IndexAction class or I could override find() method for used model. I think that using dependency injection pattern is better. In that case I could override method prepareDataProvider(), generate my own query inside child method and pass it to parent method.

I am also wondering if passing $requestParams as a parameter (with default value null) would also be beneficial.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14-dev
| PHP version      | 7.1.12
| Operating system | Debian 7.3.0-1

**Comment by SilverFire** [comment]
> I could override the method prepareDataProvider() and copy/paste its whole implementation from IndexAction class or I could override find() method for used model.

Or you can set a closure to `prepareDataProvider` property, that [should do](https://github.com/yiisoft/yii2/blob/master/framework/rest/IndexAction.php#L107) the thing you need.
