### ISSUE TITLE
Update jQuery to 3.3.1

### ISSUE THREAD

**Issue by gagatust** [yiisoft/yii2#15768]
It would be nice to update jQuery to the latest available version before removing jQuery from Yii2 dependencies.

https://github.com/yiisoft/yii2-gii/issues/282

**Comment by schmunk42** [comment]
Just for the record: I ran into several issues when updating jQuery from 2 to 3, especially because events fire asynchronously - in my case. In the end I went back to 2.x for existing applications.

**Comment by rugabarbo** [comment]
Branch 2.0.x is closed for enhancements. And for version 3.x there is a separate repository https://github.com/yiisoft/yii-jquery in which version 3.3.1 of jQuery is already used: https://github.com/yiisoft/yii-jquery/blob/94fcabb57c578054bda2e4f581d773a0cdff1498/package.json#L10

Moreover, this update will break BC (for frontends built on native Yii assets): https://jquery.com/upgrade-guide/3.0/ – "Upgrade Guide" is not as simple as we would like.

IMHO, this issue should be closed.
