### ISSUE TITLE
Array field in PostgreSQL not compatible with EachValidator 

### ISSUE THREAD

**Issue by soulhunter1987** [yiisoft/yii2#15760]
### What steps will reproduce the problem?
Try to use "each" validator with new PostgreSQL array field

### What is the expected result?
Validator correctly validates value

### What do you get instead?
Validator always returns false, till it is not capable of validating ArrayExpression.

### Additional info
From #15710 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 
| Operating system |

**Comment by SilverFire** [comment]
Fixed, thanks for report
