### ISSUE TITLE
BaseFileHelper::unlink() delete folder

### ISSUE THREAD

**Issue by Sensetivity** [yiisoft/yii2#15779]
I have a question if it normal behavior when method BaseFileHelper::unlink() don`t check existing file and clear whole directory instead?

How to reproduce?
Just put few files in some folder and try to run next command
> DEL /F/Q "C:/YOUR_DIRECTORY/"

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 5.6
| Operating system | Win 7x64

**Comment by samdark** [comment]
What would you expect?

**Comment by Sensetivity** [comment]
Emmm false or someelse but not clearing directory with other files.
Maybe before deleting dir, check if it empty or not?

**Comment by twisted1919** [comment]
What is worst is you assume `exec` is available everywhere and you call it at https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L419 
I think the framework should never use these functions. Same goes for `eval` which now should be avoidable.

**Comment by samdark** [comment]
Well, that's last-last resort measure if anything else didn't work. That's know issue that this is the only way to remove a symlink in non-pro versions of Windows 10 but yes, that's a good idea to check availablity first.
