### ISSUE TITLE
Update subtree yii2-framework

### ISSUE THREAD

**Issue by gagatust** [yiisoft/yii2#15774]

**Comment by frontbear** [comment]
see https://github.com/yiisoft/yii2/issues/15771

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/abb503c284ad371159244c2e7c388827a0f12fe9#commitcomment-27773170
https://packagist.org/packages/yiisoft/yii2#2.0.14.1

You're welcome
