### ISSUE TITLE
Pls update packagist to latest version

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2#15775]
Please could someone update packagist version to latest tag 2.0.14.1 so it could be installed via composer?
https://packagist.org/packages/yiisoft/yii2
Thank you.

**Comment by gagatust** [comment]
see https://github.com/yiisoft/yii2/commit/abb503c284ad371159244c2e7c388827a0f12fe9#commitcomment-27773170
Pls, don't close this issue. You are the third (including me :smile:) who noticed it.

**Comment by baldiri** [comment]
Hi people,

same topic, waiting for 2.0.14.1 as well...

**Comment by samdark** [comment]
@SilverFire is running subsplit now.

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/abb503c284ad371159244c2e7c388827a0f12fe9#commitcomment-27773170
https://packagist.org/packages/yiisoft/yii2#2.0.14.1

You're welcome

**Comment by lubosdz** [comment]
Thank you very much :-)
