### ISSUE TITLE
className is deprecated vs reflections + anonymous class

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15780]
### What steps will reproduce the problem?
https://github.com/yiisoft/yii2/blob/bd642b0a52530db532e85ba080221084eae1c915/framework/base/BaseObject.php#L79-L87
> @deprecated since 2.0.14. On PHP >=5.5, use `::class` instead. 

also I can see
https://github.com/yiisoft/yii2/blob/bd642b0a52530db532e85ba080221084eae1c915/framework/base/Model.php#L252-L259
> The "formName()" method should be explicitly defined for anonymous models

### What is the expected result?
I can use anonymous class with redefine `className` (return static string is equal at original class) as mock object now.
```php
        \Yii::$container->set(\api\common\models\SomeForm::class, function($container, $params) {
            return new class(...$params) extends \api\common\models\SomeForm {
                /**
                 * mock '' attribute (https://github.com/yiisoft/yii2/issues/15557)
                 * @return array|string[]
                 */
                public function safeAttributes()
                {
                    $scenario = $this->getScenario();
                    $scenarios = $this->scenarios();
                    if (!isset($scenarios[$scenario])) {
                        return [];
                    }
                    $attributes = [];
                    foreach ($scenarios[$scenario] as $attribute) {
                        if ((!strlen($attribute) || $attribute[0] !== '!') && !in_array('!' . $attribute, $scenarios[$scenario])) {
                            $attributes[] = $attribute;
                        }
                    }

                    return $attributes;
                }
                /**
                 * mock class name to correct map (this is same, but another is not same)
                 * @return string
                 */
                public static function className()
                {
                    return '\api\common\models\SomeForm';
                }
// ... another mock code. 
// Original code use className of this class on your business logic
            };
        });
```

### What do you get instead?

let's discuss!

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev bd642b0a52530db532e85ba080221084eae1c915

**Comment by samdark** [comment]
Do you suggest to keep `className()`?

**Comment by bscheshirwork** [comment]
`::class` look so pure like for me... But we loose some functional after massive remove already worked `className` from framework code (migrate to `::class`) 

Any opinion?

**Comment by bscheshirwork** [comment]
of course the `className()` can be the alias of `::class` like
```php
public function className()
{
    return static::class;
}
```

**Comment by samdark** [comment]
It's not an alias. Using `className()` triggers autoloading, using `::class` does not.

**Comment by bscheshirwork** [comment]
Yes of course. Also we can use `::class` in app config and class definitions w/o triggers autoloading
```php
return [
    'container' => [
        'definitions' => [
            \yii\validators\EmailValidator::class => [
                'enableIDN' => true,
            ],
...
    'components' => [
        'cache' => [
            'class' => \yii\redis\Cache::class,
            'redis' => 'redis',
        ],
...
```
```php
class FeedbackController extends Controller
{
     public $modelNameOfContactForm = \api\common\models\ContactForm::class;
}
```

**Comment by samdark** [comment]
Yes, that's why we don't want to have `className()` anymore. For static usage it's `::class` now, for dynamic it's `class_name()`.

You case with anonymous class is really weird. Is it from real usage?

**Comment by bscheshirwork** [comment]
> Is it from real usage?

this is mock object from my functional test. 

If business logic must use identification of concrete class I can use `className()` for store it (concrete class, not any children). Also I can masquerade this in test by redefine `className()`.

How to another way?

**Comment by samdark** [comment]
Yes. Typed wrong name :)

**Comment by samdark** [comment]
Why can't you return whatever you need in `className()` in your example? Why do you need to set it to a different class?

**Comment by bscheshirwork** [comment]
I must masquerade the anonymous child of class look like of the parent class.

Any usage of `::class` or `get_class()` return child class name... I can't masquerade it.

I can use current framework `::className()` I have a tool to masquerade any class to any class.

**Comment by samdark** [comment]
> I must masquerade the anonymous child of class look like of the parent class

Why? We're usually checking `instanceof` so just `extends` should work well.

**Comment by bscheshirwork** [comment]
> I can use className() for store it (concrete class, not any children)

first I can store class name.
second compare. 
see
https://3v4l.org/p6gOA
w/o `className()`
https://3v4l.org/dSISl

**Comment by xicond** [comment]
@bscheshirwork your sample, you compare $className2 with something already extended as reference, seems not practically we'r using extended one as reference to comparing, 
normally is reverted, 
what's the objective by comparing this way ?
`
$object2 instanceof $className1
`

**Comment by bscheshirwork** [comment]
@xicond this is example for mock object based on real class. 

Compare to real class name (stored in `$className1 = $object1::className()`).
this is ordinary compare.

mock compare to same (previous stored) class First (or your name `$className1`) 
```php
$className2 = $object2::className();
new First instanceof $className2;
```

**Comment by evalenzuela** [comment]
Guys, question. I am running PHP 5.6. I see className just calls get_called_class(). I am trying to add a relationship:

```
public function getAccountType() {
        return $this->hasOne(AccountType::get_called_class(), ['id' => 'account_type_id']);
    }
```
Using get_called_class it is the same, why className() is being deprecated, performance issue due autoloading?

**Comment by samdark** [comment]
Yes. It triggered autoloading when called.

**Comment by gooverdian** [comment]
@samdark
There is no possibility to get $owner class without using className() in behaviors.
Usecase for this is static config in another class indexed by className.

Well, I must admit there's a workaround for this: you can pass `static::class` to behavior config as a property.. Not possible for runtime behaviors, though.

**Comment by bscheshirwork** [comment]
How about add trait with this function? User can add it if needed/

**Comment by rob006** [comment]
> There is no possibility to get $owner class without using $this->owner::className() in behaviors.

You can use `get_class($this->owner)`.

**Comment by samdark** [comment]
I think everything is doable w/o `::className()` one way or another so unless a use case provided that shows critical functionality could not be implemented, this issue stays closed. Thanks for discussion.
