### ISSUE TITLE
Missing method setConditonClasses in \yii\db\QueryBuilder

### ISSUE THREAD

**Issue by rfontanella** [yiisoft/yii2#15792]
### What steps will reproduce the problem?
Try to configure query builder as mentioned [here](https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md) with [custom codition](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#adding-custom-conditions-and-expressions)

### What is the expected result?
To don't throw Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: yii\db\mssql\QueryBuilder::conditionClasses

### What do you get instead?
throw Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: yii\db\mssql\QueryBuilder::conditionClasses

### Additional info
The method setConditonClasses in \yii\db\QueryBuilder is missing.
The property $conditionClasses is protected but it could be public, because the init() method in QueryBuilder overrides the initial value (see line 125: $this->conditionClasses = array_merge($this->defaultConditionClasses(), $this->conditionClasses);)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0
| Operating system | *

**Comment by SilverFire** [comment]
Thank you for the report
