### ISSUE TITLE
Class \yii\db\Event not exists but is mentioned on docs

### ISSUE THREAD

**Issue by berosoboy** [yiisoft/yii2#15799]
Page http://www.yiiframework.com/doc-2.0/yii-db-connection.html mentions \yii\db\Event , but this class doesn't exists

![screen shot 2018-02-27 at 17 42 26](https://user-images.githubusercontent.com/7874200/36753692-ba5d14ca-1be5-11e8-8717-b7b2a6674d92.png)

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/Connection.php#L139

`Event` should be replaced with `[[yii\base\Event|Event]]`

**Comment by zhukovra** [comment]
@SilverFire why it should be replaced with second `|Event`?

**Comment by zhukovra** [comment]
Or it is just syntax for link to class?

**Comment by SilverFire** [comment]
The part after pipe is a link text. It will make link look shorter: [Event](#link) instead of [yii\db\Event](#link)
