### ISSUE TITLE
ActiveRecord asArray() loose column type

### ISSUE THREAD

**Issue by a761208** [yiisoft/yii2#15803]
### What steps will reproduce the problem?
```PHP
// MyModel with id int pk in mysql
// (1)
$model = MyModel::findOne(1);
var_dump($model->attributes);
// (2)
$row = MyModel::find()->asArray()->andWhere(['id' => 1])->one();
var_dump($row);
```
### What is the expected result?
Should be the same value.
### What do you get instead?
(1) Got a int id
(2) Got a string id

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | PHP 7.0.27-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 14:12:46) ( NTS )
| Operating system | Ubuntu 16.04.3 LTS

**Comment by a761208** [comment]
Affect when I use the values in JSON.

**Comment by SilverFire** [comment]
It is a new issue, or it existed before 2.0.14?

**Comment by a761208** [comment]
@SilverFire Existed in 2.0.13.1

**Comment by klimov-paul** [comment]
This is expected behavior, since attribute typecasting based on the column schema availbale only in ActiveRecord instance scope.

**Comment by koxu1996** [comment]
@klimov-paul It looks like this "issue" is preset for PHP 7, but not for PHP 8 - it is really weird.
