### ISSUE TITLE
 'InvalidArgumentException' in Postgres Array's

### ISSUE THREAD

**Issue by torchinsky** [yiisoft/yii2#15804]
First of all - sorry for my english...
### What steps will reproduce the problem?

1. Create table in postgres with two array fields.
2. In model make rule
```[['s_all', 's_uch',], 'each', 'rule' => ['default', 'value' => null] ],```
3. In View
```
                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 's_all[0]')->label('От')->textInput() ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 's_all[1]')->label('До')->textInput() ?>
                    </div>
                </div>
```
### What is the expected result?

On update expected saving data to s_all

### What do you get instead?

exception 'InvalidArgumentException' with message 'Passed variable is not an array or object, using empty array instead' in /mnt/disk/www/realty/vendor/yiisoft/yii2/db/ArrayExpression.php:189
Stack trace:
#0 /mnt/disk/www/realty/vendor/yiisoft/yii2/db/ArrayExpression.php(189): ArrayIterator->__construct(NULL)
#1 /mnt/disk/www/realty/vendor/yiisoft/yii2/validators/EachValidator.php(141): yii\db\ArrayExpression->getIterator()
#2 /mnt/disk/www/realty/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\EachValidator->validateAttribute(Object(app\modules\realty\models\RealtyBuyers), 's_uch')
#3 /mnt/disk/www/realty/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(app\modules\realty\models\RealtyBuyers), Array)
#4 /mnt/disk/www/realty/vendor/yiisoft/yii2/widgets/ActiveForm.php(418): yii\base\Model->validate(NULL)
#5 /mnt/disk/www/realty/modules/realty/controllers/BuyersController.php(197): yii\widgets\ActiveForm::validate(Object(app\modules\realty\models\RealtyBuyers))
#6 [internal function]: app\modules\realty\controllers\BuyersController->actionUpdate('3383')
#7 /mnt/disk/www/realty/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /mnt/disk/www/realty/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /mnt/disk/www/realty/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('update', Array)
#10 /mnt/disk/www/realty/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('realty/buyers/u...', Array)
#11 /mnt/disk/www/realty/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /mnt/disk/www/realty/web/index.php(24): yii\base\Application->run()
#13 {main}

But if we make in view
```
                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 's_all[0]')->label('От')->textInput() ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 's_all[1]')->label('До')->textInput() ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?= $form->field($model, 's_uch[0]')->label('От')->textInput() ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 's_uch[1]')->label('До')->textInput() ?>
                    </div>
                </div>
```
it will works fine.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      |   5.6
| Operating system | ubuntu 16.10

**Comment by SilverFire** [comment]
I think you need to change default value to `[]`

```php
[['s_all', 's_uch',], 'each', 'rule' => ['default', 'value' => []] ],
```

**Comment by torchinsky** [comment]
> I think you need to change default value to []
> [['s_all', 's_uch',], 'each', 'rule' => ['default', 'value' => []] ],

No effect. Same error. 
And it is strange idea...when we make [['s_all', 's_uch',], 'each', 'rule' => ['default', 'value' => null ] ], we expcet that each element in array by default will be NULL.
If we make [['s_all', 's_uch',], 'each', 'rule' => ['default', 'value' => [] ] ]...what this will be? Array [ [ ], [ ] ]? 

Also, when we make [['s_all', 's_uch',], 'safe'], we got another error

SQLSTATE[22P02]: Invalid text representation: 7 Error: ivalid value for integer: ""
The SQL being executed was: UPDATE "realty"."buyers" SET "id_type"=1, "s_all"=ARRAY['38', '']::int2[],  WHERE "id"=3383

Maybe we need some flag in config like ```'onEmptySaveNull' => true```?

**Comment by SilverFire** [comment]
> And it is strange idea...when we make [['s_all', 's_uch',], 'each', 'rule' => ['default', 'value' => null ] ], we expcet that each element in array by default will be NULL.

Enhm... yes, I was wrong. Need to check in details

**Comment by Tigrov** [comment]
@SilverFire I suppose it requires to check if value is `null`
This is example https://github.com/Tigrov/yii2-pgsql/blob/master/src/ColumnSchema.php#L40

**Comment by SilverFire** [comment]
@torchinsky Thank you for the report. Could you check whether your problem is fixed in `dev-master`?

@Tigrov yes, it was related to `null` handling. By the way, thank you for your `yii2-pgsql` extension. It was a good starting point for a me to implement arrays and JSON support in core. It also helped a lot of developers to work with arrays and JSON in PgSQL while support was not implemented in core.

**Comment by Tigrov** [comment]
@SilverFire you did a great job to implement support of `array` and `json` in right way. Thanks for it.
I will be glad if all the Postgres features are supported out of the box.

**Comment by Tigrov** [comment]
@SilverFire by the way, I think it's better to check if value is `null` at the first line of `ColumnSchema::dbTypecast($value)`  
https://github.com/yiisoft/yii2/blob/d5d4b8b0f5f242ded42e836a15ed885bf5daa201/framework/db/pgsql/ColumnSchema.php#L59

To avoid any Expressions for `null` values.
