### ISSUE TITLE
HeadersAlreadySentException when use mpdf 6 with Yii 2.0.14

### ISSUE THREAD

**Issue by undestroyer** [yiisoft/yii2#15816]
2.0.14 with patch #15046  made it imposiible to return PDF as action result.
mpdf 6.1.4 (not tested with 7) sets response headers itself. 
### What steps will reproduce the problem?
Add "mpdf/mpdf": "6.1.4" to your composer JSON file. Create action that returns PDF like that 
````
public function actionTestpdf() {
    $mpdf = new \mPDF('utf-8');
    $mpdf->WriteHTML('<h1>HELLO WORLD</h1>');
    return $mpdf->Output();
}
````
Before 2.0.14 this code worked fine, because framework ignored situation when something sent headers before, like mpdf did. Also this issue happends with PHPExcel, but is is abandoned.

Downgrade to 2.0.13.1 solves this problem.

### What is the expected result?
Return PDF to browser without exceptions.

### What do you get instead?
PDF returns with `HeadersAleradySentException`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.0.27 
| Operating system | Ubuntu 16.04.3 x64

**Comment by berosoboy** [comment]
I tested your steps with a basic app template and it's working fine

**Comment by schmunk42** [comment]
See also https://github.com/yiisoft/yii2/issues/15782#issuecomment-368553054 for a workaround.

**Comment by berosoboy** [comment]
I think there is no need for a workaround.
@undestroyer in your case, `$mpdf->Output()` will not return a value, it will echo the pdf directly. So you need to call `exit` after it:
```
$mpdf->Output();
exit;
```
the mPDF::Output method only returns a string when the param `$dest == 'S'`.

**Comment by berosoboy** [comment]
Another option:
```
return Yii::$app->response->sendContentAsFile($mpdf->Output('', 'S'), 'file.pdf', [
    'mimeType' => 'application/pdf',
    'inline' => true
]);
```

**Comment by samdark** [comment]
Again, it's an error that affects headers. We were not indicating it as a problem in 2.0.13 but it was still there. It's better to fix it as we @berosoboy said.
