### ISSUE TITLE
[Regression] [yii\test\ActiveFixture] throws [yii\base\InvalidConfigException] after update to 2.0.14

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#15814]
After upgrading to 2.0.14 when you have Fixture without fixture datafile, it throws now `yii\base\InvalidConfigException`

### What steps will reproduce the problem?
Create fixture without data file and try to load it
### What is the expected result?
It should truncate the table
### What do you get instead?
It throws `yii\base\InvalidConfigException` now instead

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      |  5.6.33
| Operating system | Ubuntu 16.04

**Comment by leandrogehlen** [comment]
@SilverFire, Do you can remove this exception?

**Comment by SilverFire** [comment]
It seems that nobody have checked this issue yet. First we need to find out why this exception was introduced and whether the reported behavior is expected

**Comment by leandrogehlen** [comment]
I have built this feature, and the exception was added to avoid setting invalid path for fixture data file.
The behavior is all right.

The problem is the BC. Now, it's necessary to define the `property $dataFile = false;` to avoid the execption.

**Comment by samdark** [comment]
@leandrogehlen let's remove it.

**Comment by leandrogehlen** [comment]
@samdark , I was removing the exception, but i found this code:
https://github.com/yiisoft/yii2/blob/master/framework/test/FileFixtureTrait.php#L43.

I have built a test for it: #15840, but  i can't found the problem.
