### ISSUE TITLE
 [RuntimeException]                                                                                                                                                         Failed to execute git clone

### ISSUE THREAD

**Issue by oktayaydin** [yiisoft/yii2#15819]
[RuntimeException]                                                                                                                                                      
  Failed to execute git clone --mirror 'git+ssh://git@github.com/isaacs/abbrev-js.git' '/home/sample/.composer/cache/vcs/git-ssh---git-github.com-isaacs-abbrev-js.git/'  
  Cloning into bare repository '/home/skomos/.composer/cache/vcs/git-ssh---git-github.com-isaacs-abbrev-js.git'...                                                        
  Permission denied (publickey).                                                                                                                                          
  fatal: Could not read from remote repository.                                                                                                                           
  Please make sure you have the correct access rights                                                                                                                     
  and the repository exists.

**Comment by adhayward** [comment]
Hi @oktayaydin 
I'm getting this error too trying to do a composer update - do you have any information on how you resolved it?
