### ISSUE TITLE
bindValues() with array fails when function is called directly

### ISSUE THREAD

**Issue by Blizzke** [yiisoft/yii2#15817]
As [requested](https://github.com/yiisoft/yii2/pull/15348#issuecomment-369850645), a new issue:
### What steps will reproduce the problem?
Using the `Command::batchInsert()` functionality with the deprecated array notation to specify a data type:

```php
$rows = [
   ['row1', ':value1'],
   ['row2', ':value2'],
]
$parameters = [
   ':value1' = [<somedata>, \PDO::PARAM_LOB],
   ':value2' = [<somedata>, \PDO::PARAM_LOB],
]
$db->createCommand()->batchInsert('table', ['name', 'value'], $rows)->bindValues($parameters)->execute();
```

### What is the expected result?
2 rows inserted, as the use of an array for bound values should be deprecated but still functional.

### What do you get instead?
"Array to string conversion" in `db/Command.php:219`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14

**Comment by SilverFire** [comment]
Fixed

**Comment by falkolab** [comment]
version 2.0.15.1
Is it same?
```
$params = [':slug' => new PdoValue($value, \PDO::PARAM_STR)];
\Yii::$app->db->createCommand("...", $params)->queryAll();
```
or ```\Yii::$app->db->createCommand()->setSql("...")->bindValues($params)->queryAll();
```

```
yii\base\ErrorException: Array to string conversion in .../vendor/yiisoft/yii2/db/Command.php:219
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8, 'Array to string...', '/var/www/dev/tk...', 219, Array)
#1 .../vendor/yiisoft/yii2/db/Command.php(219): strtr('WITH RECURSIVE ...', Array)
#2 .../vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->getRawSql()
```

**Comment by SilverFire** [comment]
@falkolab Please create a separate issue
