### ISSUE TITLE
Unable to limit the Page Count

### ISSUE THREAD

**Issue by ak868308** [yiisoft/yii2#15824]
I want to limit the page count. 
Suppose "$dataProvieder->pagination->pageCount" returns "465" So our pager generates 465 pages. Thats good. But here I want to limit that count to "100" means I want to generate 100 pages maximum in the pagination (i.e LinkPager). 
I never wants to paginate the user over 100. even our page count returns more than 100.
In short I want the function "setPageCount()" by which I can generates the desired pages in pagination.

I tried with something like below but not worked :( 

```
const MAX_PAGE_COUNT = 10;
$params = Yii::$app->request->queryParams;
if(($dataProvider->pagination->pageCount > self::MAX_PAGE_COUNT)){
         $dataProvider->pagination->pageCount = self::MAX_PAGE_COUNT;
}
if(key_exists('page', $params) && $params['page'] > self::MAX_PAGE_COUNT){
          $dataProvider->pagination->setPage(self::MAX_PAGE_COUNT - 1);
}

```
**Expected result :** 1,2,3,4,5,6,7,8,9,10 that's it... no more pages I want to be displayed in pagination i.e LinkPage. Here my last page should be 10th.

Note: Here my issue is different from "maxButtonCount" (I only needs maximum 10 pages while my maxButtonCount = 5)

Thanks

**Comment by SilverFire** [comment]
Create `LinkPager` class, extend it from `yii\widgets\LinkPager` and override `getPageRange()` method

**Comment by ak868308** [comment]
Thank you so much @SilverFire 
I created that class and implemented the `getPageRange()` method. It works fine :)
The main issue I am facing for next button. because in `renderPageButtons()` again the `$pageCount = $this->pagination->getPageCount();` is used.
Hence my logic is not working in this scenario. Here is the code for `getPageRange()` I implemented
```
protected function getPageRange() {
        $currentPage = $this->pagination->getPage(); //Returns the zero-based current page number.	
        $pageCount = $this->pagination->getPageCount();
        
        if (($currentPage > (self::MAX_PAGE_COUNT - 1)) || ($pageCount > (self::MAX_PAGE_COUNT - 1)) ) {
            $pageCount = self::MAX_PAGE_COUNT - 1;
        } 

        $beginPage = max(0, $currentPage - (int) ($this->maxButtonCount / 2));
        if (($endPage = $beginPage + $this->maxButtonCount - 1) >= $pageCount) {
            $endPage = $pageCount - 1;
            $beginPage = max(0, $endPage - $this->maxButtonCount + 1);
        }
        
        return [$beginPage, $endPage];
    }
```
But whenever I am hitting the next after reaching `MAX_PAGE_COUNT` it loads the next page and doesn't marking the next as "disabled" 
-------------------
Scenario:
I have totalPageCount = 100;
Only premium user can paginate over 50.

Once again thanks for your guidance.

**Comment by ak868308** [comment]
Finally Its Done :)
Also inherited the `renderPageButtons()` method and it gets resolved
```
$pageCount = $this->pagination->getPageCount();
    if($pageCount > self::MAX_PAGE_COUNT){
          $pageCount = self::MAX_PAGE_COUNT;
    }
```
Thanks
