### ISSUE TITLE
Not detaches an existing event.

### ISSUE THREAD

**Issue by rusavskiy** [yiisoft/yii2#15822]
### What steps will reproduce the problem?
Test code on 2.0.14.1:
```
    public function testBugEvents()
    {
        $obj = new DynamicModel();
        $obj->on('test', [$this, 'handler']);
        $obj->off('test', [$this, 'handler2']);
    }
```
using wrong handler - "handler2".

Result:
```
1) BugTest: Events
Test  tests/unit/BugTest.php:testEvents

[yii\base\ErrorException] Undefined index: test

#1  /data/yii2/vendor/yiisoft/yii2/base/Component.php:576
#2  /data/yii2/vendor/symfony/console/Application.php:241
#3  /data/yii2/vendor/symfony/console/Application.php:143
```
### What is the expected result?
Test code on 2.0.13 and result:
```
Common\tests.unit Tests (1)
✔ BugTest: BugEvents (0.01s)
---------------------------
```
Return bool value - 'false'.

### What do you get instead?
'ErrorException'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.1
| Operating system | ubuntu 16.04

**Comment by SilverFire** [comment]
Fixed
