### ISSUE TITLE
Update file UPGRADE.md

### ISSUE THREAD

**Issue by lav45** [yiisoft/yii2#15828]
In the file [UPGRADE.md](https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md)
```
composer global require "fxp/composer-asset-plugin:^1.4.1" --no-plugins
```
As far as this information is relevant, after [transition](https://github.com/yiisoft/yii2-app-advanced/commit/4a892a65c122bcea294fd93fc4fb860b2789dd58#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) to the https://asset-packagist.org service

**Comment by SilverFire** [comment]
Thank you for niticing it. Would you like to submit a PR?
