### ISSUE TITLE
Postgres. Querying jsonb fields is broken since 2.0.14

### ISSUE THREAD

**Issue by StalkAlex** [yiisoft/yii2#15827]
JSONB support changes made this kind of queries non-working
```php
$count = Yii::$app->db->createCommand("
            select * from documents 
            where content @>  '{\"Solution date\":\"13.01.2011\"}' 
        ")->execute();
```

Maybe syntax is not valid anymore? How to fix that? 
P.S. [disabling](https://github.com/yiisoft/yii2/issues/15716#issuecomment-368143206) new features makes it work again.

**Comment by StalkAlex** [comment]
Not sure what else I can provide, I think issue is pretty clear.  Query above returned 1 as the result, now it returns 0, but it's not correct as I want to see the same row as before.

**Comment by berosoboy** [comment]
> The execute() method should only non-query SQL statement

http://www.yiiframework.com/doc-2.0/yii-db-command.html#execute()-detail

Try to refactor it to:
```
$count = Yii::$app->db->createCommand("
    select count(*) from documents 
    where content @> '{\"Solution date\":\"13.01.2011\"}' 
")->queryScalar();
```

**Comment by SilverFire** [comment]
Added a unit test to verify that the described query works as expected: https://github.com/yiisoft/yii2/commit/66081c6187548407ab667090ce2ba6eb7bf7b0ce

The test passes, so I close this issue.

@StalkAlex in case I'm wrong – please, fix the test to match your case.

**Comment by StalkAlex** [comment]
@berosoboy count still returns 0.
@SilverFire ok, I'll try to change your test.

**Comment by berosoboy** [comment]
Very strange. I tested both queries and its working here. 
Try to output the $command->rawSql to see if there is no problem.

**Comment by StalkAlex** [comment]
Ok, guys, my fault. Thank you for help.  Forgot to change fixture data.
```php
[
    ...
    'jsonColumn' => '{*jsonString*}',
    ...
]
```
to 

```php
[
    ...
    'jsonColumn' => json_decode('{*jsonString*}'),
    ...
]
```
