### ISSUE TITLE
Пустой массив в JsonExpression

### ISSUE THREAD

**Issue by Krakozaber** [yiisoft/yii2#15837]
PostgreSQL при записи `new \yii\db\JsonExpression([],'json')` ожидается `'{}::json'`, вместо этого в БД записывается `[]`

| Yii version      | 2.0.14
| PHP version      |  5.6
| Operating system | Debian

**Comment by SilverFire** [comment]
Как записываете, какая версия постгреса, какой тип столбца?

**Comment by SilverFire** [comment]
Насколько я понимаю, вы хотите, чтобы содержимое JsonExpression принудительно приводилось к объекту, а не массиву?

**Comment by Krakozaber** [comment]
PostgreSQL 9.6
При указании значения `$attributes['var'] = [];`
в базу пишется строка `{"id":210,"schedule":"31.03.2018 23:00:00","steps":"","var":[],"end_wait_time":""}`
хотелось бы видеть 
`{"id":210,"schedule":"31.03.2018 23:00:00","steps":"","var":{},"end_wait_time":""}`

**Comment by SilverFire** [comment]
Понял. @samdark @sergeymakinen как думаете, корректно будет добавить `JSON_FORCE_OBJECT` при `json_encode()` в ArrayExpressionBuilder'e?

**Comment by Krakozaber** [comment]
в JsonExpressionBuilder'e ?

**Comment by cebe** [comment]
```
$attributes['var'] = new stdclass();
```

**Comment by sergeymakinen** [comment]
@SilverFire мне кажется, надо или добавлять переключаемый параметр в Builder (иначе всегда будут те, кому надо массив и те, кому нужен объект), или оставить как есть и использовать классический ответ от @cebe.
Я бы оставил как есть и посмотрел спрос на переключаемый параметр.

**Comment by Krakozaber** [comment]
Допустим `new stdСlass();` при записи в БД устраивает
тогда почему при получении с PostgreSQL  `{}` получается не пустой объект, а пустой массив `[]` ?

Дайте возможность определять подобное поведение.

**Comment by SilverFire** [comment]
> тогда почему при получении с PostgreSQL `{}` в Yii получается не пустой объект, а пустой массив `[]` (подобное поведение при удалнеии записи с `{"var":{}}`) ?

Сейчас JSON декодируется в массив. В PHP есть возможность декодировать JSON либо в массив, либо в объект класса `\stdClass`. Нельзя частично декодировать JSON в объект, а частично – в массив.

Что касается общего процесса декодирования, то при декодировании в массив, JSON `{}` и `[]` даёт один и тот же результат.

> надо или добавлять переключаемый параметр в Builder (иначе всегда будут те, кому надо массив и те, кому нужен объект)

Билдер – слишком обще. Такое решение нужно принимать на уровне модели, а лучше – схемы.

@Tigrov у вас были подобные запросы?

**Comment by SilverFire** [comment]
Пока переношу на 2.0.15

**Comment by Tigrov** [comment]
@SilverFire  запросов не было, но приходилось самому с этим сталкиваться.

> тогда почему при получении с PostgreSQL {} в Yii получается не пустой объект, а пустой массив []

Вопрос в том, кому как больше нравится использовать JSON в PHP. Как ассоциативный массив или как объект (с массивом работать проще).

@cebe выше дал рабочее решение, когда в БД нужен именно {}. Но в PHP будет всё тот же массив.

Бывают случаи, когда JSON нужен не в PHP, а в JavaScript. Здесь те самые отличия {} или []. В этих случаях можно отдельно приводить массив к объекту.

@Krakozaber возможно в вашем случае проще использовать `null` вместо пустого объекта/массива.
Если интересно у меня есть подобное решение https://github.com/Tigrov/yii2-pgsql-audit

**Comment by samdark** [comment]
Закрываю так как любое решение найдёт как сторонников, так и противников + есть вариант локального решения.
