### ISSUE TITLE
Database migration: PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in vendor\yiisoft\yii2\base\Object.php on line 28

### ISSUE THREAD

**Issue by aBahrami13** [yiisoft/yii2#15831]
### What steps will reproduce the problem?
install php 7.2.2 
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii2-app
php init (choose development mode = 0)
composer require mdmsoft/yii2-admin "~2.0"
define admin module in common/config/main.php: 'class' => 'mdm\admin\Module' 
define authManager component in common/config/main.php: 'class' => 'yii\rbac\DbManager'
create a database in MySql and configure it in common/config/main-local.php
yii migrate --migrationPath=@mdm/admin/migrations in CMD

### What is the expected result?
creating a proper user table for the user management

### What do you get instead?
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in vendor\yiisoft\yii2\base\Object.php on line 28

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.2.2 (using XAMPP)
| Operating system | Windows 10 (x64)

**Comment by samdark** [comment]
It's mdmsoft/yii2-admin issue. Please report there.
