### ISSUE TITLE
JSON issues in Yii 2.0.14

### ISSUE THREAD

**Issue by rockccf** [yiisoft/yii2#15839]
### What steps will reproduce the problem?
The JSON value string inserted into the DB will be enclosed by double quotes hence it's causing the internal double quotes to be escaped.

### What is the expected result?
The correct one should be
```php
[{"level":1,"id":1},{"level":2,"id":2}]
```

### What do you get instead?
```php
"[{\"level\":1,\"id\":1},{\"level\":2,\"id\":2}]"
```

### Additional info
However, I realize that If I changed the validation rule in the model class, 
From
```php
[['formula'],'string']
```
to 
```
[['formula'],'safe']
```

formula is the json column name.
The value inserted into the database is correct
```php
[{"level":1,"id":1},{"level":2,"id":2}]
```

After I changed the validation rule in the model class, and the insertion works.
I tried to do a query search based on the same JSON data but no records found.
```php
$conditionArray[] = array('level'=>1,'id'=>1);
$conditionArray[] = array('level'=>2,'id'=>2);
$condition = new JsonExpression($conditionArray);
self::find()->where(['=','formula',$condition])
```
I look at the logs, and the query being executed is
```php
SELECT * FROM `uom_formula` WHERE (`formula` = '[{\"level\":1,\"id\":1},{\"level\":2,\"id\":2}]')
```

ArrayExpression does not work either.
Expression of class `yii\db\ArrayExpression` can not be built in `yii\db\mysql\QueryBuilder`

Is this normal?
Am I doing something wrong?
Thanks.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      |  7.1.5
| Operating system | Windows 10

**Comment by SilverFire** [comment]
> However, I realize that If I changed the validation rule in the model class, 
> From 
```php
[['formula'],'string']
```
> to 
> ```
[['formula'],'safe']
```
>
> formula is the json column name.
> The value inserted into the database is correct
> ```php
[{"level":1,"id":1},{"level":2,"id":2}]
```

**Comment by SilverFire** [comment]
> However, I realize that If I changed the validation rule in the model class, 
> From 
> ```php
> [['formula'],'string']
> ```
> to 
> ```
> [['formula'],'safe']
> ```
>
> formula is the json column name.
> The value inserted into the database is correct
> ```php
> [{"level":1,"id":1},{"level":2,"id":2}]
> ```

`string` is a definitely wrong validator for the `formula` attribute. I'd suggest to use `each` validator and validate JSON schema for every formula (contains `level` and `id` attributes, etc).

**Comment by SilverFire** [comment]
The thing with search looks weird. Could you try on dev-master, please?

**Comment by rockccf** [comment]
>string is a definitely wrong validator for the JSON formula attribute. I'd suggest to use each validator and validate JSON schema for every formula (contains level and id attributes, etc).

Gii still produces the model class with the string validator though. Is it only applicable for non-array JSON column?

>The thing with search looks weird. Could you try on dev-master, please?
Yes, tested on dev-master, still the same.

```
$formula[] = array('level'=>1,'subuom'=>$uomObject2->id,'unitVolume'=>floatval($unitVolume2));
$formula[] = array('level'=>2,'subuom'=>$uomObject3->id,'unitVolume'=>floatval($unitVolume3));
$formula = new JsonExpression($formula);
$uomFormula = static::find()
                ->where(['tenantId'=>$ownerId,'uomId'=>$uomId])
                ->andWhere(['=','formula',$formula])
                ->one();
```
`SELECT * FROM `uom_formula` WHERE ((`tenantId`='1') AND (`uomId`=11)) AND (`formula` = '[{\"level\":1,\"subuom\":19,\"unitVolume\":12},{\"level\":2,\"subuom\":4,\"unitVolume\":500}]')`

**Comment by samdark** [comment]
Gii is fixed but only in master. No release was made yet.

**Comment by SilverFire** [comment]
We have tests that verify your case: https://github.com/yiisoft/yii2/blob/5fa25b331d23d4ece44a63eee77bf4ec4f27f00e/tests/framework/db/pgsql/QueryBuilderTest.php#L109-L118

Could you add a failing test?

**Comment by rockccf** [comment]
Actually I'm using MySQL. Does it matter?

**Comment by SilverFire** [comment]
> ```php
> SELECT * FROM `uom_formula` WHERE ((`tenantId`='1') 
> AND (`uomId`=11)) 
> AND (`formula` = '[{\"level\":1,\"subuom\":19,\"unitVolume\":12}, {\"level\":2,\"subuom\":4,\"unitVolume\":500}]')
> ```

What query do you expect to be generated?

**Comment by rockccf** [comment]
I expect that it would be like this.
```
SELECT * FROM `uom_formula` WHERE ((`tenantId`='1') 
AND (`uomId`=11)) 
AND (`formula` = '[{"level":1,"subuom":19,"unitVolume":12}, {"level":2,"subuom":4,"unitVolume":500}]')
```

However, when I run it in the mysql console, the query above will just return an empty set.
```
SELECT * FROM `uom_formula` WHERE ((`tenantId`='1') 
AND (`uomId`=11)) 
AND (`formula` = cast('[{"level":1,"subuom":19,"unitVolume":12}, {"level":2,"subuom":4,"unitVolume":500}]' as json)
```
I have to cast the comparison json string as JSON type and the correct results will be returned.

Thanks.

**Comment by SilverFire** [comment]
Could you check with changes in PR #15868?

**Comment by SilverFire** [comment]
Merged
