### ISSUE TITLE
Не работает поиск по JSON полю

### ISSUE THREAD

**Issue by xr0m3oz** [yiisoft/yii2#15838]
### What steps will reproduce the problem?
Пробую сделать поиск по JSON полю, но получаю пустой результат.
Используя этот код из документации
https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#arrays-in-postgresql

`$query->andWhere(['=', 'json', new ArrayExpression(['foo' => 'bar'])`

Получаю ошибку 
Expression of class yii\db\ArrayExpression can not be built in yii\db\mysql\QueryBuilder

Пробовал поменять ArrayExpression на JsonExpression
Ошибки нету, но результат пустой.

Мой кусок кода:
social_data - поле типа JSON содержит
{"vk_id": 9090909, "vk_token": "4bf867a616fa24fc6cb3f1bc06b47af59d82d2"}

```
$condition = ['vk_id' => $service->getId()];

self::find()->where(['=', 'social_data', new JsonExpression($condition)->one()
```

Я что то не так делаю?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.1
| Operating system |

**Comment by SilverFire** [comment]
Какой SQL при этом исполняется?

**Comment by berosoboy** [comment]
I think you are trying to use a postgresql feature on a mysql database

**Comment by SilverFire** [comment]
А, вижу ошибку. Вы сейчас ищите по полному совпадению поля `social_data`, а код намекает, что вам нужен был поиск по значению `vk_id`. Ознакомьтесь с документацией [MySQL по поиску в JSON](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html).

Скорее всего вам нужно что-то вроде:

```php
self::find()->where(['=', new Expression("(jsoncol->>'$.vk_id')"), '42'])->one();
```

**Comment by SilverFire** [comment]
I future Yii versions I will enhance QueryBuilder by adding support of DBMS-agnostic syntax to define JS conditions. Planning something like this:

```php
['=', 'social_data->>vk_id', $service->getId()]
```
