### ISSUE TITLE
urlManager[showScriptName] can't hide index.php

### ISSUE THREAD

**Issue by JorgeLiu** [yiisoft/yii2#15835]
i have set
urlManager' => [
            'showScriptName' => false,
]
but 
yii\helper\Url::to() => index.php/<controller>/<action>

and 
ActiveForm default action /index.php/<controller>/<action>

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.0.28
| Operating system | windows server 2016 +iis

**Comment by samdark** [comment]
http://www.yiiframework.com/forum/index.php/topic/69745-my-way-to-hide-indexphp-on-iis-7/page__p__296024__hl__ii++how+criptname#entry296024
