### ISSUE TITLE
bug? Chinese wrong output in a console action.

### ISSUE THREAD

**Issue by bzqadmin** [yiisoft/yii2#15834]
### What steps will reproduce the problem?
In a console controller I have an action 
`public function actionPromote(){
        $text = "请输入你的真实姓名";
        $encoded_text = mb_convert_encoding($text,"gbk");
        $input = $this->prompt($encoded_text);
        echo $input;
        echo "\n";
        echo $encoded_text;
    }`
as you see there some Chinese text.
### What is the expected result?
I expect the terminal (win7 64bit cmd.exe) print : 请输入你的真实姓名
(means please input your name )
and user input name, cmd.exe will print users name.
### What do you get instead?
but always the Chinese output :请输入你的真实姓名 真实姓名 彰??
not 请输入你的真实姓名
It`s something like I expect :please input your name
but I get :please input your name your name  name
It repeat the last words severl times of the text.

### Additional info
I think there are something wrong in yii\helper\baseConsole::promote().
Anybody have idea to resovle this issues?
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 7.0.10
| Operating system | win7 64bit

**Comment by larryli** [comment]
Please run on win10 or msys without mb_convert_encoding to gbk.

**Comment by bzqadmin** [comment]
@larryli maybe it`s a problem of cmd.exe ,I try again with xShell ，it works well.thanks.
