### ISSUE TITLE
JsonExpression обнуляет вложенный JsonExpression

### ISSUE THREAD

**Issue by Krakozaber** [yiisoft/yii2#15836]
Существует объект $object:

```
array (size=2)
  'id' => int 197
  'var' => 
    object(yii\db\JsonExpression)[99]
      protected 'value' => 
        array (size=1)
          1 => 
            array (size=2)
              ...
      protected 'type' => string 'json' (length=4)
```

при попытке обернуть в `new \yii\db\JsonExpression($object, 'json')` вложенный `'var' => object(yii\db\JsonExpression)` превращается в пустой `'var':{}`

| Yii version      | 2.0.14
| PHP version      |  5.6
| Operating system | Debian

**Comment by SilverFire** [comment]
Спасибо за сообщение. А какой сценарий использования такой конструкции?

**Comment by Krakozaber** [comment]
запись истории изменений через afterSave в формате JSON, один из изменяемых параметров JSON

**Comment by SilverFire** [comment]
окей, попробуем решить

**Comment by SilverFire** [comment]
Проверьте, пожалуйста, решает ли вашу проблему https://github.com/yiisoft/yii2/pull/15857

**Comment by SilverFire** [comment]
Исправлено в #15857
