### ISSUE TITLE
Running a console application in YII_ENV_TEST returns succes when it shouldn't

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#15847]
### What steps will reproduce the problem?
* Create a console controller named `TestController` with a function called `actionTest()` that throws an Exception.
* Run `./yii test/test && echo "All went fine"`
* Run `tests/bin/yii test/test && echo "All went fine"`

### What is the expected result?
I should never see **All went fine**, since an exception is throw in `actionTest()`.

### What do you get instead?
I see a "All went fine" when running the command in test-mode. The `tests/bin/yii test/test && echo "All went fine"` command still continues with the next command since the exit-code is overridden.

This is due to this line: https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L112

Is there any reason why we don't return with error code 1 when we are running in YII_ENV_TEST and an uncatched exception has occured?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
Could be something to do with PHPUnit or Codeception.

**Comment by michaelarnauts** [comment]
I just checked and Codeceptions seem to catch the exceptions as expected, so it won't reach the `handleException()`.

I commented out the if statement  to skip the `exit(1)` one the line mentioned above and it still works as expected and all 3 tests run fine.

```php
<?php

class ExceptionTest extends \Codeception\Test\Unit
{
    public function testException()
    {
        throw new Exception('Crash 1');
    }

    public function testSecondException()
    {
        throw new Exception('Crash 2 ');
    }

    public function testSucces()
    {
        return true;
    }
}
```

```
Codeception PHP Testing Framework v2.3.8
Powered by PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Unit Tests (3) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E ExceptionTest: Exception (0.00s)
E ExceptionTest: Second exception (0.00s)
✔ ExceptionTest: Succes (0.00s)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 1.03 seconds, Memory: 12.00MB

There were 2 errors:

---------
1) ExceptionTest: Exception
 Test  tests/unit/ExceptionTest.php:testException
                       
  [Exception] Crash 1  
                       
#1  /opt/app/tests/unit/ExceptionTest.php:7
#2  ExceptionTest->testException

---------
2) ExceptionTest: Second exception
 Test  tests/unit/ExceptionTest.php:testSecondException
                        
  [Exception] Crash 2   
                        
#1  /opt/app/tests/unit/ExceptionTest.php:12
#2  ExceptionTest->testSecondException

ERRORS!
Tests: 3, Assertions: 0, Errors: 2.
```


@cebe wrote this change a few years ago in 33543cbdb35622d6454412bec75bf76bb69d7929, maybe he still remembers?

**Comment by michaelarnauts** [comment]
To have a use case. I've setup my CI testing to start a test-database and do something like 

```sh
tests/bin/yii migrate && vendor/bin/codecept run unit,functional
```

Since I run this in `YII_ENV_TEST`, it is not exited with `exit(1)` when the migration fails, so codeception will run, even though the migrate has failed and it shouldn't continue.

**Comment by rob006** [comment]
See #15202
