### ISSUE TITLE
Multilingual Model Validation Errors Issue

### ISSUE THREAD

**Issue by abasit83** [yiisoft/yii2#15841]
I am using Yii 2 Basic. 

For displaying error in any form for field email, it should say
**"Email cannot be blank"** 
and in arabic
**" البريد الإلكتروني لا يمكن تركه فارغًا."**

How can I do that if I have 2 panels

- MemberPanel (where registered members can login)
- AdminPanel (where admin can login)

MemberPanel can either be in English or Arabic. (on member selection)
AdminPanel must be in English

Can anyone guide me in all steps that I would follow. Thanks

**Comment by larryli** [comment]
Try [module](http://www.yiiframework.com/doc-2.0/guide-structure-modules.html) for admin panel.

You can modify in `\app\admin\Module.php`:

```php
class Module extends \yii\base\Module
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        Yii::$app->language = 'en-US';
    }
}
```

And [Select language by user](https://github.com/samdark/yii2-cookbook/blob/master/book/i18n-selecting-application-language.md).
