### ISSUE TITLE
User should store identityClass in session

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#15849]
This is a niche security issue; it can arise from (mis)use of dynamic application configuration.

### What steps will reproduce the problem?
Have an application with 2 identity classes; for example: `Human` and `Pet`.
These are 2 totally different entities, so they have their own AR class (and table).
A human can have many pets.
Humans can log in via a page designed for humans, pets log in via their own page.
One solution to implement this would be to do host based routing and configure the identity class based on the current host:

````
'user' => [
    'identityClass' => $petHost ? 'Pet' : 'Human'
]
````
This works, but there is a security issue.

### What is the expected result?
Pets can do what they have permissions to do, Humans the same.

### What do you get instead?

Suppose I have a Human and a Pet with the same ID.
A pet logs in, gets a session cookie. The session contains the following data:
````
[
    '__id' => 1
]
````
Now it uses the cookie for a request to the domain intended for `Human`s.
Since `identityClass` is configured as `Human`, the `User` component will happily load the `Human` and grant the pet access.

### Solution
A simple solution would be to also store the class in the session:
````
[
    '__id' => 1,
    '__class' => 'app\models\Pet'
]
````
Now the user component can confirm that `$this->identityClass === $session->get('__class')` to prevent mistakes like these.

As far as I can tell this solution has no real drawbacks even if its benefits only arise in edge cases.

A valid counter argument is that according to the `IdentityInterface`:
````
 /**
     * Returns an ID that can uniquely identify a user identity.
     * @return string|int an ID that uniquely identifies a user identity.
     */
    public function getId();
````
you are in violation of the contract since apparently your IDs are not unique. (If that is the reasoning than I'll create a PR to improve documentation)

A simple workaround would be to implement the interface so that identity IDs have their class name prefixed.
This creates a downside in the case of AR though: `$user->id === $user->getId()` no longer holds. It is something that you might expect as a Yii2 developer. 

### Conclusion
While the fix is simple there are valid arguments against putting it in the core; this is something the team should decide.

**Comment by berosoboy** [comment]
I think your use case can be achieved with proper config. Something like this: 
```
'user' => [
    'identityClass' => $petHost ? 'Pet' : 'Human',
    'idParam' => $petHost ? '__pet_id' : '__human_id',
    'identityCookie' => [
        'name' => $petHost ? '_identity_pet' : '_identity_human',
        ....
    ],
    ....
]
```

**Comment by SamMousa** [comment]
Yes that's also an option! Nice one. So there are several workarounds at least :)

**Comment by berosoboy** [comment]
I think your proposed solution can be dangerous. What happens if I change the identityClass of the user component and deploy the application, while users are logged in?
The `__class` stored in user session could not long exists.

**Comment by samdark** [comment]
We should avoid serializing with `__class` name since, as @berosoboy said, it will disallow changing the class in the future. Closing the issue since:

1. Interface docs already state that ID should be unique. 
2. In default apps and most apps there's no such problem.
3. There are multiple ways of avoiding conflicts.

@SamMousa please check https://guides.github.com/features/mastering-markdown/ about code blocks ;)

**Comment by SamMousa** [comment]
Fair enough. 

@samdark what's wrong with my markdown? :d

**Comment by SamMousa** [comment]
I saw that as well in the guide... But that's not how it worked originally right? When they first added code blocks it was just 4 on start and end? Anyway, thnx :-D

**Comment by samdark** [comment]
Nope, it was three all the time :)
