### ISSUE TITLE
Broken BaseHtml::collectErrors with showAllErrors = true in 2.0.14.1

### ISSUE THREAD

**Issue by FlorinRo** [yiisoft/yii2#15858]
In a scenario where you have the same error message on multiple fields and want to display all of them BaseHtml::collectErrors will crash with 'Undefined offset' error at line 1260
https://github.com/yiisoft/yii2/blob/e63a459a18924bc1672c473c1bbeadfc1b502879/framework/helpers/BaseHtml.php#L1260

Example:
`$model->getErrors():
Array
(
    [field1] => Array
        (
            [0] => Message1
            [1] => Message2
        )
    [field2] => Array
        (
            [0] => Message1
        )
)
$model->getErrorSummary():
Array
(
    [0] => Message1
    [1] => Message1
    [2] => Message2
)`

`echo Html::errorSummary($model,['showAllErrors'=>true]);`
will throw error

Its because of line 1255:
https://github.com/yiisoft/yii2/blob/e63a459a18924bc1672c473c1bbeadfc1b502879/framework/helpers/BaseHtml.php#L1255
array_unique will preserve keys and Model::getErrorSummary produces an array where the same error message is grouped on consecutive positions. So $lines ends up like this
`Array
(
    [0] => Message1
    [2] => Message2
)`

Simple fix: `$lines = array_values($lines);` after foreach

Here is the relevant stack of the ErrorException:
`
[yii\base\ErrorException:8] yii\base\ErrorException: Undefined offset: 1 in /vendor/yiisoft/yii2/helpers/BaseHtml.php:1260
Stack trace:
#0 /vendor/yiisoft/yii2/helpers/BaseHtml.php(1260): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '...', 1260, Array)
#1 /vendor/yiisoft/yii2/helpers/BaseHtml.php(1226): yii\helpers\BaseHtml::collectErrors(Array, true, true)
#2 /vendor/yiisoft/yii2/widgets/ActiveForm.php(305): yii\helpers\BaseHtml::errorSummary(Object(...), Array)
`

**Comment by SilverFire** [comment]
Thank you very much for your report. Would you like to help us and try to submit a pull request with fix?

**Comment by FlorinRo** [comment]
ups, it seams someone already fixed this,
thx :)

**Comment by FabrizioCaldarelli** [comment]
Sorry @FlorinRo, I was working on the core so I thought to publish the pull request.

**Comment by SilverFire** [comment]
Fixed by #15859
