### ISSUE TITLE
tabular form validation does not have show red anymore

### ISSUE THREAD

**Issue by michaelnguyen547** [yiisoft/yii2#15852]
### What steps will reproduce the problem?
do a tabular form and fail the validation

### What is the expected result?
in Yii2.0.12, "has-error" class is added to the div.form-group

### What do you get instead?
in Yii2.0.14, "has-error" class is not added to the div.form-group hence the error message is not red

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 5.6.14
| Operating system | Ubuntu 14.04

**Comment by FabrizioCaldarelli** [comment]
Related to #15801

**Comment by samdark** [comment]
Looks like a duplicate.
