### ISSUE TITLE
AssetManager unnecessarily checks for writable basePath when not configured to publish any assets

### ISSUE THREAD

**Issue by monzol** [yiisoft/yii2#15850]
### What steps will reproduce the problem?
- Configure AssetManager to use assets already in web accessible folder or external assets from CDN
- Set permission on assets folder to read-only (755) (this is a standard security measure on our production servers)

### What is the expected result?
Use the configured assets without publishing or checking for writable publish path

### What do you get instead?
Invalid Configuration – yii\base\InvalidConfigException
The directory is not writable by the Web process: /var/www/htdocs/admin/assets
1. in /var/www/includes/vendor/yiisoft/yii2/web/AssetManager.php at line 215

### Additional info
My AssetManager config:
```
return [
    // Map file names to external resources
    'assetMap' => [
        'jquery.js'         => "//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.js",
        'bootstrap.css'     => "//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css",
        'bootstrap.js'      => "//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.js",
    ],

    // Do not publish Yii assets and dependencies
    'bundles' => [
        'yii\web\YiiAsset'                   => false,
        'yii\web\JqueryAsset'                => false,
        'yii\bootstrap\BootstrapAsset'       => false,
        'yii\bootstrap\BootstrapPluginAsset' => false,
    ],
];
```
My AppAsset class:
```
class AppAsset extends AssetBundle
{
    public $basePath = false;
    public $baseUrl = '@web/assets';

    public $css = [
        'bootstrap.css',
    ];

    public $js = [
        'jquery.js',
        'bootstrap.js',
        'js/yii.js',
        'js/yii.activeForm.js',
        'js/yii.captcha.js',
        'js/yii.gridView.js',
        'js/yii.validation.js',
    ];

    public $depends = [ ];
}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 5.6.31
| Operating system | Linux CentOS 7

The problem is caused by the AssetManager::init() method where the basePath is checked if it's an existing and writable directory regardless of the need for such check. 

Could this check be moved from the init() method to somewhere where it's more relevant and only perform the check when asset publishing is involved?

My workaround for now is to point the basePath to a writable directory, which is currently the yii-runtime, even though nothing gets published there. This satisfies the check in AssetManager::init(). The other workaround would be to override the init() method but I don't want that in case new functionality is added in later versions.

**Comment by SilverFire** [comment]
Thank you for the report. Would you like to try to fix this issue by submitting a pull request?

**Comment by monzol** [comment]
Sure, I'll do it. Thanks.

**Comment by rugabarbo** [comment]
@samdark 

Please, reopen. It should be fixed even if the author of this issue is not going to do it.

**Comment by monzol** [comment]
Only meant to close the pull request, sorry for the mess. 
I think it's best if somebody more experienced looks into this to save time.
Cheers
