### ISSUE TITLE
Link Gives 404 on Doc-2.0 class reference

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#15861]
on the [**`docs `**](http://www.yiiframework.com/doc-2.0/yii-swiftmailer-mailer.html) class reference the link against **Source Code** gives a 404 
https://github.com/yiisoft/yii2-swiftmailer/blob/master/Mailer.php

**Comment by cebe** [comment]
broken by moving to `src/` folder :-/

https://github.com/yiisoft/yii2-swiftmailer/commit/fc0ae4d38ec65eb4345d44b247b8cd86bb34fbb9
