### ISSUE TITLE
Auto check if assignment already exists when calling Yii::$app->authManager->assign();

### ISSUE THREAD

**Issue by Matvik** [yiisoft/yii2#15872]
At this time, when creating a new role assignment (or permission assignment ), there is no automatic check for the presence of such an assignment. Accordingly, we get an exception if this assignment already exists.
At the same time, during the removal (calling revoke() method) of a non-existent assignment such a collision does not occur.

In my opinion, it would be good to implement an automatic check of the presence of an assignment when trying to add it and do nothing in the case when it already exists. This can be useful in the case when we do not know for sure if an assignment exists already.

### What steps will reproduce the problem?
Recreating assignment which already exists
### What is the expected result?
Automatic check
### What do you get instead?
No check and exception

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.1
| Operating system | Any

**Comment by samdark** [comment]
Can't you check before actually assigining?

**Comment by Matvik** [comment]
Yes, i`m doing check now, it is only proposition.
And it can be implemented in current version because backward compatibility will not break.

**Comment by samdark** [comment]
I don't think it's a good idea. It's `assign`, not `assignOrIgnore`.
