### ISSUE TITLE
The menu widget option can not be active if is set Query params

### ISSUE THREAD

**Issue by antkaz** [yiisoft/yii2#15879]
### What steps will reproduce the problem?

```php
Menu::widget([
    'items' => [
        [
            'label' => 'Menu',
            'items' => [
                [
                    'label' => 'One',
                    'url' => '/controller/action',
                ],
                [
                    'label' => 'Two',
                    'url' => '/two-controller/action',
                ],
            ],
        ],
    ]
]);
```
1. I send a request to the address `http://site.com/controller/action`;
2. Menu item **is active**
3. Then i send a request to the address `http://site.com/controller/action?queryParams`;

### What is the expected result?

I send a request to the address `http: //site.com/controller/action?queryParams` and the menu item is expected to be active

### What do you get instead?

I send a request to the address `http: //site.com/controller/action?queryParams` and the menu item is not active

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 5.6
| Operating system | Mac OS 10.13.3

**Comment by samdark** [comment]
You need to configure `params`.
