### ISSUE TITLE
only indexBy('name')  can get the right results.

### ISSUE THREAD

**Issue by sbwfnyiiiu** [yiisoft/yii2#15870]
indexBy('name') can get 4 result, indexBy('others') can get only one result
Controller Code
......
$films = Film::find()->indexBy('name')->all();
var_dump($films);
.....

Film database table

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for film
-- ----------------------------
DROP TABLE IF EXISTS `film`;
CREATE TABLE `film` (
  `id` int(11) NOT NULL,
  `film_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of film
-- ----------------------------
INSERT INTO `film` VALUES ('1', '111', 'aaa', 'AAA');
INSERT INTO `film` VALUES ('2', '222', 'bbb', 'BBB');
INSERT INTO `film` VALUES ('3', '333', 'ccc', 'CCC');
INSERT INTO `film` VALUES ('4', '444', 'ddd', 'DDD');

**Comment by SilverFire** [comment]
You do not have `others` column in your database
