### ISSUE TITLE
Нет возможности изменить/дополнить метод setActivePlaceholder после переопределиния базового класса Html через classMap

### ISSUE THREAD

**Issue by jcakokorev** [yiisoft/yii2#15889]
Нет возможности изменить/дополнить метод setActivePlaceholder после переопределиния базового класса Html через classMap из-за строгого вызова через self внутри методов activeInput/activeTextarea.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.2
| Operating system | Ubuntu 16

**Comment by SilverFire** [comment]
@jcakokorev хотели бы попробовать решить эту проблему и прислать Pull Request?
