### ISSUE TITLE
Move migration/create to gii/migration

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#15881]
### What steps will reproduce the problem?

I wanted to create a migration file from a template without an actual DB connection. 

### What is the expected result?

It should be possible to do so.

### What do you get instead?

Access denied error (in my case) because the DB hasn't been set up yet.
While looking at the code I saw that the migration command ensures a DB-connection `beforeAction`, which is basically fine.

But this lead me to the question if it wouldn't make more sense to have a command like:

    yii gii/migration

Where the code-generator would create the migration files.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      |  7.2
| Operating system | Linux

*If such a change is made, surely only in 2.1*

**Comment by samdark** [comment]
While we could use Gii for it, there are more operations with migrations: applying, checking history, reverting, moving current migration pointer. I think it's logically correct to keep these together with creating migration.

**Comment by schmunk42** [comment]
~~~But all the operations you mentioned are carried out on the database, while creating migrations is done in the file-system only (like gii).~~~

Just noticed that `generateMigrationSourceCode` needs the database connection when creating junction tables, missed that functionality, so it's fine.
