### ISSUE TITLE
Pages with PageCache don't send CSRF cookie if no valid cached page avilable

### ISSUE THREAD

**Issue by nagyt234** [yiisoft/yii2#15892]
### What steps will reproduce the problem?

If a controller action is using yii\filters\PageCache then no _csrf cookie is sent to the client on the first time, i.e. if there is no valid cached page yet. This problem causes, that any HTTP POST from that page fails. 
1. Create a controller with PageCache. e.g.:
```php
public function behaviors()
{
  return [
    'viewCache' => [
        'class' => 'yii\filters\PageCache',
        'only' => ['view'],
        'duration' => 86400,    // 1 day
        'variations' => [
            isset($_GET['id']) ? $_GET['id'] : null,
        ],
    ],
  ];
}
```
Add in your view the meta tag:
```
 <head>
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= $this->renderDynamic('return yii\bootstrap\Html::csrfMetaTags();') ?>
    <title><?= Html::encode($this->title) ?></title>                           
    <?php $this->head()?>                                                      
 </head>                                                                        

```
2. Delete your cache on the web server, e.g. use the following command on your yii app directory (advanced yii template):
`rm -rf *end/runtime/cache/*
`
3. Remove the cookies in your browser.
4. Call the appropriate page in your browser.
5. Check your cookies in the browser. Unfortunately `_csrf` is missing.
6. Call the appropriate page in your browser again.
7. Check your cookies in the browser. `_csrf` is there.

### What is the expected result?
`_csrf`  cookie should be there on the first call already.

### Notes
1. I've tried to add the CSRF cookie in renderDynamic, but it did not change anything, i.e. somewhere the coookie will be removed:
```
<?= $this->renderDynamic('if (!\Yii::$app->response->cookies->has("_csrf")) \Yii::$app->response->cookies->add(new \yii\web\Cookie(["name" => "_csrf", "value" => \Yii::$app->request->csrfToken])); return yii\bootstrap\Html::csrfMetaTags();') ?>
```
2. If `yii\bootstrap\Html::csrfMetaTags()` called outside of `renderDynamic` it sends the CSRF cookie, but of course we will have the problem, that the CSRF meta tag wiill be the same for every client.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.1.14
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
There's already a method for it in master but it wasn't used in application templates yet (will fix it).

Replace

```php
<?= Html::csrfMetaTags() ?>
```

with

```php
<?php $this->registerCsrfMetaTags() ?>
```

in your `main.php` layout file.

**Comment by nagyt234** [comment]
Thanks. That solved the problem.
