### ISSUE TITLE
Master/slave configuration in DI cause infinite recursion

### ISSUE THREAD

**Issue by DmLapin** [yiisoft/yii2#15894]
### What steps will reproduce the problem?
Take any application like basic template. Configure DB connection using Dependency Container:
```
'components' => [
	'db' => \yii\db\Connection::class,
],
'container' => [
	'definitions' => [
        \yii\db\Connection::class => [
            'class' => \yii\db\Connection::class,
            'username' => 'user',
            'password' => 'passw',
            'charset' => 'utf8',
            'masters' => [
                ['dsn' => 'pgsql:host=localhost;dbname=masterDb']
            ],
            'slaves' => [
                ['dsn' => 'pgsql:host=localhost;dbname=slaveDb']
            ]
        ]
    ]
]
```
Now try to perform any query
```
$db = Yii::$app->db;
OR
$db = Yii::$container->get(yii\db\Connection::class);

$db->createCommand('SELECT 1')->queryScalar();
```

### What is the expected result?
Before first DB query container instantiate Connection object, which provide master or slave.

### What do you get instead?
Infinite recursion:
open() -> getMaster() -> openFromPool() -> open() -> ...

The reason is yiisoft/yii2/db/Connection.php:1126 + yiisoft/yii2/db/Connection.php:591
Connection object instantiate itself with master's DSN config, but DI append to this config defaults from 'definitions'.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.2
| PHP version      | 7.1

**Comment by ArekX** [comment]
I believe that this is just due to nature of how DI works.

Also can't you fix this simply using this?

```
'components' => [
	'db' => \yii\db\Connection::class,
],
'container' => [
	'definitions' => [
        \yii\db\Connection::class => [
            'class' => \yii\db\Connection::class,
            'username' => 'user',
            'password' => 'passw',
            'charset' => 'utf8',
            'masters' => [
                ['dsn' => 'pgsql:host=localhost;dbname=masterDb', 'masters' => [], 'slaves' => []]
            ],
            'slaves' => [
                ['dsn' => 'pgsql:host=localhost;dbname=slaveDb', 'masters' => [], 'slaves' => []]
            ]
        ]
    ]
]
```

Or am I missing something?

**Comment by samdark** [comment]
Yes, could be re-configured this way.
