### ISSUE TITLE
With tabular input, the active field  not receive the model  real attribute for adding an has-error class

### ISSUE THREAD

**Issue by DAGpro** [yiisoft/yii2#15893]
The method addErrorClassIfNeeded does not have an helper Html::getAttributeName to get the real attribute

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      |  7.2
| Operating system | windows 10

**Comment by FabrizioCaldarelli** [comment]
Duplicated  #15801

**Comment by DAGpro** [comment]
@FabrizioCaldarelli Sorry, did not check the search for this issue
