### ISSUE TITLE
docs of `yii cache/flush-schema`

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15901]
https://github.com/yiisoft/yii2/commit/b8fa37eaeb62488e2cd2e5016af733082311d9e5

tell about 

`yii cache/flush cache1 cache2`

`yii cache/flush-all`

but no one bit info about `yii cache/flush-schema`

This is important command and IMHO must be add to this chapter

**Comment by SilverFire** [comment]
@bscheshirwork would you like to submit a Pull Request, please?

**Comment by s1lver** [comment]
Maybe it's worth starting with a brief description?
