### ISSUE TITLE
Determine length for bindValues as bindParam does

### ISSUE THREAD

**Issue by xyluet** [yiisoft/yii2#15907]
so in
`
public function bindParam($name, &$value, $dataType = null, $length = null, $driverOptions = null)
`

it determine the length of the datatype which is i'm using PDO.

in bindvalues ?

I'm using oracle stored procedure with out param

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.x
| PHP version      | 5.6
| DB | Oracle

**Comment by samdark** [comment]
I don't think it's possible since PDO doesn't have `$length` for `bindValue()`.
