### ISSUE TITLE
cebe/markdown

### ISSUE THREAD

**Issue by free6k** [yiisoft/yii2#15905]
16 hours ago was be change composer.json for cebe/markdown. our ci system is degraded...
i have next errors in composer:

```
Installation request for yiisoft/yii2 2.0.12 -> satisfiable by yiisoft/yii2[2.0.12].
yiisoft/yii2 2.0.12 requires cebe/markdown ~1.0.0 | ~1.1.0 -> no matching package found.
```

ok, i read upgrade.md and got next error:

```
 The requested package cebe/markdown ~1.1.0 exists as cebe/markdown[1.2.x-dev, dev-master] but th
  ese are rejected by your constraint.
```

is it time to upgrade yii version? :)

**Comment by free6k** [comment]
now, composer see other versions cebe/markdown .... all right

**Comment by cebe** [comment]
looks like packagist somehow forgot about the versions. This should be a temproary issue.

**Comment by cebe** [comment]
See https://github.com/cebe/markdown/issues/154#issuecomment-374215978 for more details on this.
