### ISSUE TITLE
Yii Log FileTarget except does not work

### ISSUE THREAD

**Issue by rockccf** [yiisoft/yii2#15902]
### What steps will reproduce the problem?
In config,
```
'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'info'],
                    'maxFileSize' => 102400, //1024000KB - 100MB
                    'except' => [
                        'email',
                        'yii\db\*'
                    ]
                ],
            ]
        ]
```

### What is the expected result?
Expected the db queries not to be logged in app.log file

### What do you get instead?
2018-03-15 15:26:54 [::1][163][-][info][yii\db\Command::query] SELECT * FROM `auth_assignment` WHERE `user_id`='163'

DB queries still getting logged.

### Additional info
However, if I set the file target to write the logs elsewhere (other than app.log)
```
[
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'info'],
                    'maxFileSize' => 102400, //1024000KB - 100MB
                    'logFile' => '@runtime/logs/app2.log',
                    'except' => [
                        'email',
                        'yii\db\*'
                    ]
                ],
```

It will work. DB queries will not be logged in app2.log

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1.5
| Operating system | Windows 10

**Comment by SilverFire** [comment]
Added test to check the behavior. Failed to reproduce. In case I'm wrong in test – change it to reproduce your problem, please.
