### ISSUE TITLE
yii\widgets\MaskedInput removes custom classes and attributes applied via inputOptions

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#15912]
### What steps will reproduce the problem?
Using `ActiveForm` Create a Masked Input and add a class `my-control` to it via `inputOptions` in `field()` and provide a `style` attribute with `display:none` like below 
```
<?=
        $form->field($model, 'mobile_phone', [
            'inputOptions' => ['class' => 'my-control', 'useSessionFlash' => true,'style'=>'display:none'],
            'template' => '<div class="form-line">{label}{input}</div>{error}',
        ])->widget(\yii\widgets\MaskedInput::className(), [
            'mask' => '999-999-9999'
        ])->label(null, ['class' => 'form-label']);
        ?>
```

### What is the expected result?
The rendered input should have the class applied in the class attribute and should have a style attribute defined with `display:none `
```
<input id="leadform-mobile_phone" class="my-control" name="LeadForm[mobile_phone]" data-plugin-inputmask="inputmask_7b93eb48" type="text" style="display:none">
```

### What do you get instead?

The renderd input shows the default class `form-control` on the input and there isnt any `style` attribute defined where as it should have the custom class `my-control` it renders the input like below 

```
<input id="leadform-mobile_phone" class="form-control" name="LeadForm[mobile_phone]" data-plugin-inputmask="inputmask_7b93eb48" type="text">
```
If we remove he `MaskedInput` widget everything works as normal

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 5.6
| Operating system |Ubuntu

**Comment by SilverFire** [comment]
`inputOptions` in `ActiveField` are not passed to widget. Pass the options to widget directly

```php
<?=
        $form->field($model, 'mobile_phone', [
            'template' => '<div class="form-line">{label}{input}</div>{error}',
        ])->widget(\yii\widgets\MaskedInput::className(), [
            'mask' => '999-999-9999', 
            'options' => ['class' => 'my-control', 'useSessionFlash' => true,'style'=>'display:none'],
        ])->label(null, ['class' => 'form-label']);
        ?>
```

**Comment by buttflattery** [comment]
i love you @SilverFire

**Comment by SilverFire** [comment]
To achieve it, `ActiveField` should blindly try to pass its `inputOptions` to widget that is not a good idea as for me
