### ISSUE TITLE
i18n Formatter.php defaultTimeZone bug

### ISSUE THREAD

**Issue by shengbinxu** [yiisoft/yii2#15910]
### What steps will reproduce the problem?
I am in china, my php.ini  date.timezone = 'Asia/Shanghai', when I run the follow code:

        \Yii::$app->formatter->timeFormat = 'short';

        // \Yii::$app->formatter->defaultTimeZone = ini_get('date.timezone');

        echo \Yii::$app->formatter->asTime('2018-03-16 20:56');

It will output：
上午4:56
It means morning 4：56， but really it is afternoon 8:56,  the difference is 8 hours。
when I uncomment the code:

`
\Yii::$app->formatter->defaultTimeZone = ini_get('date.timezone');
`
It will output:
下午8:56
It is ok。

so I think in i18n/Formatter.php， the default value of defaultTimeZone attribute  should be set  to `ini_get('date.timezone')`

### What is the expected result?

in i18n/Formatter.php， the default value of defaultTimeZone attribute  should be set to `ini_get('date.timezone')` , not UTC

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.1
| Operating system | centos

**Comment by SilverFire** [comment]
Currently `defaultTimeZone` is `UTC` by default and can be changed by config.
We can set default to `defaultTimeZone` with `ini_get('date.timezone')`, but in case environment changes. the application logic may be messed up and (most probably nobody will notice it. I'd like to keep it as is to discourage developers from relying on environment settings.

**Comment by shengbinxu** [comment]
@SilverFire 
What you said makes sense! but this is too difficult to debug for this.
Imagine a scene like this:
In gridView columns , I hava a column like this:
`'sign_in_time:time'`
I want this column to be formatted as a time, but the result is error because of the UTC time zone, for a programer that was not familiar with yii, how hard can you imagine to debug this error ?  the programer will think that :  my locale config and time zone config all is ok , why?

**Comment by SilverFire** [comment]
Developer will go to Yii guide and read [Time zones](http://www.yiiframework.com/doc-2.0/guide-output-formatting.html#time-zones) article

**Comment by shengbinxu** [comment]
@SilverFire  Thank you for your reply, I just did not see this doc before. It's my question, thank you!
