### ISSUE TITLE
How to use setRetryHandler

### ISSUE THREAD

**Issue by Choate** [yiisoft/yii2#15924]

**Comment by Renkas** [comment]
I stumbled on this also today. I'm getting inspection error: `member has protected access but class has magic method __call`
And PHP Exception: `Calling unknown method: yii\sphinx\Command::setRetryHandler()`

My code:
```
        Yii::$app->sphinx->createCommand()
            ->delete('some_table', ['some_id' => $some_id])
            ->setRetryHandler(function (Exception $exception, $attempt) {
                return $attempt > 2 ? false : true;
            })
            ->execute();
```


I can't really see a way to actually use this functionality
