### ISSUE TITLE
yii\web\Application overwrites @web and @webroot aliases, problematic when testing

### ISSUE THREAD

**Issue by Sarke** [yiisoft/yii2#15927]
The following code overwrites aliases set in the config:

https://github.com/yiisoft/yii2/blob/1ebf951a59ab3bbbb223195f6803172be5e837bb/framework/web/Application.php#L65-L67

This can be an issue when testing, causing the `@webroot` to be set to the root directory where `codecept` is called, and not the `./web` directory that is the actual one.

I suspect this has not been an issue previously, because by default the yii2 project templates have both a `./assets` folder and a `./web/assets` folder.  The assets when testing have then been placed in the wrong folder.

This can be seen with symlinks to assets in both the `./assets` folder and the `./web/assets` folder.

However, if one has a different folder structure, the tests can error if the assets folder is not found, and it's not possible to correct it with an alias in the config (since it will be overwritten).

I would suggest checking if the aliases are set, before setting them to the default.

**Comment by cebe** [comment]
if you need assetmaanger to work in your tests, you should configure `request` component accordingly.

**Comment by Sarke** [comment]
@cebe, which setting in `request` would be relevant here?

**Comment by cebe** [comment]
as you can see from the code above, `scriptFile` and `baseUrl` properties.

**Comment by samdark** [comment]
Won't be an issue for 3.0.
