### ISSUE TITLE
yii2 multiple device login

### ISSUE THREAD

**Issue by patel28** [yiisoft/yii2#15923]
Can you please provide inbuilt support for multiple device login like facebook and google 
I want to 
##  yii2 disable multiple device login
or 
User can manage session like facebook and google 
where user can manage logged in devices 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.0
| Operating system | ALL

**Comment by Alex-Code** [comment]
Have you tried [Authclient](http://www.yiiframework.com/doc-2.0/ext-authclient-index.html)?
[Docs](https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/README.md)
