### ISSUE TITLE
Call to a member function getRoute() on null

### ISSUE THREAD

**Issue by sgh370** [yiisoft/yii2#15935]
Hi, when i open the site url, get 500 error in all pages and again when refresh it, its gone and in the ajax request i get 500 error. this error is happend:
```php
PHP Fatal Error – yii\base\ErrorException
Call to a member function getRoute() on null
in C:\xampp\htdocs\myshop\lib\vendor\yiisoft\yii2\helpers\BaseUrl.php
                      * - string: generating an absolute URL with the specified scheme (either `http`, `https` or empty string
     *   for protocol-relative URL).
     *
     * @return string the generated URL
     * @since 2.0.3
     */
    public static function current(array $params = [], $scheme = false)
    {
        $currentParams = Yii::$app->getRequest()->getQueryParams();
        $currentParams[0] = '/' . Yii::$app->controller->getRoute();  
        $route = array_replace_recursive($currentParams, $params);
        return static::toRoute($route, $scheme);
    }
```

error release in here in the function:
`$currentParams[0] = '/' . Yii::$app->controller->getRoute(); `
please help me. please help me. thanks

**Comment by sgh370** [comment]
![image](https://user-images.githubusercontent.com/25865344/37690017-be6a8bae-2cbd-11e8-85c7-637fbee8da79.png)

**Comment by sgh370** [comment]
after trace, i detect the issue is from Yii2. because when i comment out Url::current(), issue has solved. please test the last yii2 version and check this bug is exist or not

**Comment by berosoboy** [comment]
Where are you trying to call Url::current() ?
Maybe you are trying to invoke it when controller is not ready yet.
