### ISSUE TITLE
Extends yii\base\ErrorHandler.php code

### ISSUE THREAD

**Issue by macklus** [yiisoft/yii2#15936]
**Disclaimer:** I not sure if this is a bug or just system normal work. Even that, i think that base question was:

**How can i extend or modify yii response when i get error 500 or other errors than dont go to normal errorHandler?**

### What steps will reproduce the problem?

Try to extends yii\base\ErrorHandler with code:
web.php
```
'errorHandler' => [
            'class' => 'app\base\MiError',
            'errorAction' => 'site/error',
        ],
```
MiError class
```
<?php
namespace app\base;

use Yii;
use yii\base\ErrorHandler;

abstract class MiError extends ErrorHandler
{
    protected function handleFallbackExceptionMessage($exception, $previousException)
    {
        exit('funciona!');
    }
    
}

```

### What is the expected result?

Extends behaviour of yii\base\ErrorHandler (i need to modifiy error 500 code)

### What do you get instead?
```
2018/03/21 06:48:16 [error] 988#988: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught yii\di\NotInstantiableException: Can not instantiate app\base\MiError. in framework/vendor/yiisoft/yii2/di/Container.php:372
Stack trace:
#0 framework/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('app\\base\\MiErro...', Array, Array)
#1 framework/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('app\\base\\MiErro...', Array, Array)
#2 framework/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#3 framework/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('errorHandler', true)
#4 framework/vendor/yiisoft/yii2/web/Application.php(151): yii\base\Module->get('errorHandler')
#5 framework/vendor/yiisoft/yii2/base/Application.php(347): yii\web\Application->getErro" while reading response header from upstream, client: 192.168.0.69, server: erp.garrampa.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-erp.garrampa.local.sock:", host: "erp.garrampa.local"```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.2.3 
| Operating system | CentOS

**Comment by samdark** [comment]
Yii tries to catch fatals but it cannot handle all possible cases. That's PHP limitation.

**Comment by macklus** [comment]
@samdark question here is: is there any way of extends yii\base\ErrorHandler ? (or any yii base class)

**Comment by samdark** [comment]
Sure. These are all components. You can extend from it and then re-configure Yii via `components` section in the config. It's in the guide, I think.

**Comment by berosoboy** [comment]
@macklus There is no problem to extends a ErrorHandler. Your example fails because you are using a abstract class.

**Comment by ValiSum** [comment]
The solution to all this is to replace "**use yii\base\ErrorHandler**" with "**use yii\web\ErrorHandler**" because "yii\web\ErrorHandler" extends already from "yii\base\ErrorHandler". It would be like this:
````
<?php
namespace app\base;

use Yii;
use yii\web\ErrorHandler;

abstract class MiError extends ErrorHandler
{
    protected function handleFallbackExceptionMessage($exception, $previousException)
    {
        exit('funciona!');
    }
    
}
````
The rest everything the same.

**Comment by berosoboy** [comment]
@ValiSum , @macklus . You cannot instantiate an abstract class. It's a OOP rule.
A concrete class must be provided in config.
Just remove the `abstract` keyword before class definition.

**Comment by ValiSum** [comment]
Sorry @berosoboy . I forgot to remove that too. It would remain like this:
````
<?php
namespace app\base;

use Yii;
use yii\web\ErrorHandler;

class MiError extends ErrorHandler
{
    protected function handleFallbackExceptionMessage($exception, $previousException)
    {
        exit('funciona!');
    }
    
}
````
