### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by i-panov** [yiisoft/yii2#15945]
Can the [Model::validate](http://www.yiiframework.com/doc-2.0/yii-base-model.html#validate()-detail) method take a string with attributes separated by a comma? In any case, judging by the signature of the function, the attributes parameter can be a string or an array of strings. But when I tried to pass the attributes there in a row, I only got a bunch of problems. The string with attributes is not validated in any way, but returns `true`. At the same time, with the array of attributes, everything works correctly. Apparently this is a bug...

**Comment by BBrunekreeft** [comment]
I think the options are a single attribute name (string) or multiple attributes (array).

**Comment by i-panov** [comment]
@BBrunekreeft This is very unevident behavior, because in many other places they use exactly the behavior that I described. I would call it bad architecture. Do not be offended...

**Comment by cebe** [comment]
@i-panov can you point me to other places where this format is accepted? I'm not aware of any.

**Comment by i-panov** [comment]
@cebe for example [Query::select](http://www.yiiframework.com/doc-2.0/yii-db-query.html#select()-detail)

**Comment by samdark** [comment]
I think we can start requiring arrays all the time in 2.1.

**Comment by cebe** [comment]
> @cebe for example Query::select

well, that is because it supports adding plain SQL, something completely different from specifying validation rules.

I don't think it is a good idea to introduce special syntax hidden in strings when an array can specify it more explicitly.
