### ISSUE TITLE
yii\base\Security.php ->generateRandomKey -> mcrypt_create_iv 正式环境http卡死，测试环境超时

### ISSUE THREAD

**Issue by xasong** [yiisoft/yii2#15944]
运行环境
centos 6.5/6.8 ,apache 2.4.48(2.2.15正常),PHP 5.5.38 
命令行执行或者正常，通过
![image](https://user-images.githubusercontent.com/30643708/37754630-44648fb4-2ddd-11e8-9455-241156b739ea.png)
程序会卡这里

**Comment by cebe** [comment]
Sorry, I do not understand the problem. Google translate doesn't help much. Please try to explain in english.

**Comment by larryli** [comment]
@cebe 

yii\base\Security.php ->generateRandomKey -> mcrypt_create_iv http stuck on production environment, timeout on test environment

Run on:
centos 6.5/6.8 ,apache 2.4.48(2.2.15 success),PHP 5.5.38
Success or passed on cli command.
![image](https://user-images.githubusercontent.com/10723/37765869-56884da2-2e00-11e8-8f7f-8577e7783f66.png)
Stuck here.

BTW: I also don't understand what he said.

**Comment by samdark** [comment]
Well, that means that environment application runs on somehow weird. I'm afraid we cannot fix it within Yii.

**Comment by agungsijawir** [comment]
It seems your server don't have php-mcrypt extentions enabled. Please check your server php installation.

**Comment by samdark** [comment]
It would have error properly.

**Comment by agungsijawir** [comment]
sorry, yes you are right @samdark 
then, most probably about `$length` variable or reporter refer to miss refer to error stack-trace.

@xasong please provide full stack-trace error so we can help you further.
