### ISSUE TITLE
[2.1] Finally remove deprecated stuff

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2#15957]
Roadmap Wiki section: https://github.com/yiisoft/yii2/wiki/Roadmap#cleanup – (BTW: will be good to link it with this issue).

For each code marked as `@deprecated` need to do:
* rewrite dependencies
* remove documentation occurrences
* remove code

Аlready done: 
* 800574871419b99442d8be73a51e7f8e9e0d090f
* 4e15d3375633ae92eb0e91fbb0f6050de61b5d5c

**Comment by samdark** [comment]
Linked to this issue from wiki.

**Comment by rugabarbo** [comment]
All deprecations removed (last PR #15963 is waiting for the @SilverFire review). Some things can reappear after merges (2.0.x >> 2.1.x). That's why I'll wait for other 2.1 commits (and merges), then will search deprecated things again. 

Don't close this task.

**Comment by SilverFire** [comment]
Merged #15963
