### ISSUE TITLE
TimestampBehavior not working [2]

### ISSUE THREAD

**Issue by i-panov** [yiisoft/yii2#15951]
I'll duplicate [this](https://github.com/yiisoft/yii2/issues/15946) issue. I ask you not to close it! It was not a question. I'm 100% sure that your TimestampBehavior has broken! The problem arose not only with me.

**Comment by samdark** [comment]
"Not working" is too vague to be a but report. We have no idea what's wrong and thus can't fix it. If you know how exactly to reproduce it starting with a clean basic project template, post it in original issue. Thanks.
