### ISSUE TITLE
composter

### ISSUE THREAD

**Issue by acrixl** [yiisoft/yii2#15973]
### What steps will reproduce the problem?

try to install 
need composter

### What is the expected result?

non composter

### What do you get instead?

archives 404

https://github.com/yiisoft/yii2/releases/download/2.0.15/yii-advanced-app-2.0.15.tgz

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
You can get releases here: https://github.com/yiisoft/yii2/releases. Will be fixed at the website...
