### ISSUE TITLE
Why doesn't gii define the tinyint type?

### ISSUE THREAD

**Issue by gloomylad** [yiisoft/yii2#15984]
I get the latest version of Yii2-advanced through composer.(2.0.15.1)
Why doesn't gii define the tinyint type?
But it's in a separate module.(https://github.com/yiisoft/yii2-gii)
This leads to the following problems with the generated model.
For example:
the properties:
/**
 * This is the model class for table "auth_role".
 *
 * @property int $id
 * @property string $name 
 * @property string $rules
 * @property string $remark
 * @property int $status
 * @property int $sort
 * @property int $created_at
 * @property int $updated_at
 * @property int $deleted_at
 */
the rules:

    public function rules()
    {
        return [
            [['name', 'remark'], 'required'],
            [['sort', 'created_at', 'updated_at', 'deleted_at'], 'integer'],
            [['name'], 'string', 'max' => 20],
            [['rules'], 'string', 'max' => 255],
            [['remark'], 'string', 'max' => 50],
            **[['status'], 'string', 'max' => 1],**
            [['name'], 'unique'],
        ];
    }
Since tinyint is not defined, the rule for 'status' is string.

**Comment by samdark** [comment]
It's already fixed in gii. Will be there with the next release of it.

**Comment by gloomylad** [comment]
@samdark Thanks to answer
