### ISSUE TITLE
Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#15991]
### What steps will reproduce the problem?
在使用组件：2amigos/yii2-qrcode-helper  的时候，报以下bug,  please !  thanks 
### What is the expected result?
在使用组件：2amigos/yii2-qrcode-helper  的时候，报以下bug,  please !  thanks 
### What do you get instead?
![image](https://user-images.githubusercontent.com/1888094/37964711-fced5e7e-31f4-11e8-9e82-645bc76b331e.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      |  7.2.3 nts 64bit
| Operating system | win10 64bit

**Comment by rugabarbo** [comment]
Please report about it here: https://github.com/2amigos/qrcode-library/issues/new

It's problem of https://github.com/2amigos/qrcode-library library.

**Comment by cebe** [comment]
> 2amigos/yii2-qrcode-helper

this is not a bug in Yii, but in the `2amigos/yii2-qrcode-helper` package, please report to the package maintainer. As a workraound, use PHP 7.1 or 7.0 instead of 7.2.
