### ISSUE TITLE
Exception 'IntlException' with message 'Constructor failed'  PHP 7.1.12, Yii 2.0.15

### ISSUE THREAD

**Issue by dekar91** [yiisoft/yii2#15993]
Hi, all, that I did ' just change timeZone in web.php:

```
$config = [
    'id' => 'basic',
    'defaultRoute' => 'index/index',
    'timeZone' => 'Asia/Barnaul',
....
```
and use Yii::$app':formatter->asDate()

```
Exception 'IntlException' with message 'Constructor failed' 

in /var/www/kinonew/vendor/yiisoft/yii2/i18n/Formatter.php:761

Stack trace:
#0 /var/www/kinonew/vendor/yiisoft/yii2/i18n/Formatter.php(761): IntlDateFormatter->__construct('ru', -1, -1, 'Asia/Barnaul', NULL, 'd MMMM, E, H:mm')
#1 /var/www/kinonew/vendor/yiisoft/yii2/i18n/Formatter.php(629): yii\i18n\Formatter->formatDateTimeValue('2018-03-27 23:5...', 'd MMMM, E, H:mm', 'date')
#2 /var/www/kinonew/components/Formatter.php(11): yii\i18n\Formatter->asDate('2018-03-27 23:5...', 'd MMMM, E, H:mm')
...
```

- Ubuntu 16.04
- PHP 7.1.12
 - Yii 2.0.15

Does somebody know how to solve this?

**Comment by rugabarbo** [comment]
Give a result of the console command: 
`php -r "echo INTL_ICU_VERSION . \"\n\";"`

I have the same problem with ICU Version **55.1**. 
I reproduced the error by code:
`new \IntlDateFormatter('ru', -1, -1, 'Asia/Barnaul');`

**Comment by rugabarbo** [comment]
`new \IntlDateFormatter('ru', -1, -1, 'Europe/Moscow');`
is OK

**Comment by rugabarbo** [comment]
https://bugs.php.net/bug.php?id=72074 – ICU **57.1** must be OK.

Just update it.
The upgrade process not so simple for PHP 7.1 (it requires recompilation).
See example of upgrade here: https://www.yiiframework.ru/forum/viewtopic.php?t=42744#p212223

**Comment by dekar91** [comment]
@rugabarbo my ICU version is 55.1. Yes, it works perfectly well with Europe/Moscow but not with Barnaul.

**Comment by rugabarbo** [comment]
@dekar91 as I said ICU update can solve this problem. Just update it.

**Comment by julianrutten** [comment]
This is still an issue even with 57.1. For example:
php -r "var_dump(new IntlDateFormatter('ru', -1, -1, 'Europe/Kirov', NULL, 'H'));"
Only for kirov though, and it doesnt matter if you use a full locale (ru_RU) etc.

Maybe use a try catch statement when constructing the IntlDateFormatter object? Would be nasty to not return the requested time but better then the app crashing as it does not seem like something we can do anything about, Europe/Kirov is a valid timezone after all (used to work fine by the way).
Just an example of how I solved it (i just needed a function to get the current hour):

```php
        try {
            return (new \IntlDateFormatter(Yii::$app->formatter->locale, -1, -1, Yii::$app->formatter->timeZone, null, 'H'))->format(new \DateTime);
        } catch (\IntlException $e) {
            return false;
        }
`
