### ISSUE TITLE
why the 2.0 guide is still complete？官方文档还没有完成全部

### ISSUE THREAD

**Issue by zomboo** [yiisoft/yii2#16005]
for example https://www.yiiframework.com/doc/guide/2.0/zh-cn/tool-debugger is 404。
请问为什么2.0的文档没有完成，英文版只有一个api链接，也是打不开。以后还有更新么？

**Comment by itma** [comment]
I am getting the proper content under this url.

**Comment by cebe** [comment]
yeah, I just fixed it ;)
