### ISSUE TITLE
ContentNegotiator "Illegal offset type in isset or empty" error

### ISSUE THREAD

**Issue by rinchatechnology** [yiisoft/yii2#16010]
### What steps will reproduce the problem?
TestController.php:
```php
//...
public function behaviors()
{
    return [
        [
            'class' => 'yii\filters\ContentNegotiator',
            'only' => ['index'],
            'languages' => ['ru', 'en'],
        ]
    ];
}

public function actionIndex()
{
    return Yii::$app->language;
}
//...
```
Type in the browser:
http:://youhostname/test/index?_lang[test1]=foo&_lang[test2]=bar

### What is the expected result?
Skip wrong language param value without error.

### What do you get instead?
Got error: `"Illegal offset type in isset or empty" in test/vendor/yiisoft/yii2/filters/ContentNegotiator.php at line 219`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.0
| Operating system |Ubuntu

**Comment by rugabarbo** [comment]
That's because ContentNegotiator doesn't expect that GET param _lang is array:
https://github.com/yiisoft/yii2/blob/d880148fd09f827aefee2f418294a72a38579bfb/framework/filters/ContentNegotiator.php#L219

Must be fixed with additional `is_array()` check.

**Comment by rugabarbo** [comment]
I fixed it myself because the fix isn't so trivial as I thought. In case of `language` we must skip bad params but in case of `format` must not and throw an exception instead.

Such different logic for formats and languages is initially was realized in this component.
