### ISSUE TITLE
Echo in controller

### ISSUE THREAD

**Issue by melnikweb** [yiisoft/yii2#16014]
### What steps will reproduce the problem?

Adding `echo '5';` in a controller

### What is the expected result?

Output of '5' in view

### What do you get instead?
500 error:
`An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in W:\domains\yii2\controllers\BlogController.php on line 34. in W:\domains\yii2\vendor\yiisoft\yii2\web\Response.php:366
Stack trace:
#0 W:\domains\yii2\vendor\yiisoft\yii2\web\Response.php(339): yii\web\Response->sendHeaders()
#1 W:\domains\yii2\vendor\yiisoft\yii2\web\ErrorHandler.php(135): yii\web\Response->send()
#2 W:\domains\yii2\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in W:\domains\yii2\controllers\BlogController.php on line 34. in W:\domains\yii2\vendor\yiisoft\yii2\web\Response.php:366
Stack trace:
#0 W:\domains\yii2\vendor\yiisoft\yii2\web\Response.php(339): yii\web\Response->sendHeaders()
#1 W:\domains\yii2\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Response->send()
#2 W:\domains\yii2\web\index.php(16): yii\base\Application->run()
#3 {main}`
### Additional info

This happens on the Yii's version 2.0.15.1, but in Yii 2.0.13.1 it works fine. 

This error message copied from work's project, but i checked it too in clean Yii and got similar results. Both of versions installed by composer.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.7 and 5.6
| Operating system |

**Comment by rob006** [comment]
Duplicates #15816

**Comment by melnikweb** [comment]
It isn't duplicate #15816 because there is return, not echo

**Comment by Thoulah** [comment]
Don't `echo` in controller?

**Comment by melnikweb** [comment]
What do you mean? In #15816 there is return of echoing string, or I misunderstood something?

**Comment by rob006** [comment]
`$mpdf->Output()` works like echo, so this is the same situation. You should not use echo in controller, or at least call `Yii::$app->end()` to prevent further response processing.

**Comment by afashio** [comment]
Just use exit() after your code. It helped me
