### ISSUE TITLE
Будет ли расширение для firebird?

### ISSUE THREAD

**Issue by lesha724** [yiisoft/yii2#16020]
Планируется ли отдельное расширение для [firebird](https://firebirdsql.org/) на подобии [yii2-mssql](https://github.com/yiisoft/yii2-mssql)?

**Comment by rugabarbo** [comment]
Core Team точно не будет поддерживать такое расширение. Если кто-нибудь захочет, сможет создать и поддерживать такое расширение самостоятельно.

**Comment by lesha724** [comment]
@rugabarbo в том то и дело, что одному очень тяжело поддерживать такое расширение. Есть уже пара расширений, но они или брошены или очень медленно развиваются. Спасибо за ответ.

**Comment by samdark** [comment]
Нет, мы не осилим ещё одно. Напишите авторам существующих, попробуйте скоординироваться и сделать одно хорошее и поддерживать его всеми...
