### ISSUE TITLE
\yii\caching\Cache::buildKey can generate identical cache keys for different $key attribute

### ISSUE THREAD

**Issue by smsteel** [yiisoft/yii2#16028]
So method is written like this:

    public function buildKey($key)
    {
        if (is_string($key)) {
            $key = ctype_alnum($key) && StringHelper::byteLength($key) <= 32 ? $key : md5($key);
        } else {
            $key = md5(json_encode($key));
        }

        return $this->keyPrefix . $key;
    }

The problem is in passing `json_encode` output directly to `md5` function.
It can return `false` in case of error. In my case it was an SQL query with special symbols, key generated from Yii2 components itself, when i used query caching. So it returned the same md5 key and caused multiple errors (same result for different queries)

Maybe it is better to throw an exception if output of `json_encode` is `false` in this case?
And i guess i need to create another ticket for `\yii\db\Command::queryInternal`?

**Comment by smsteel** [comment]
Editing... pressed submit.

**Comment by rugabarbo** [comment]
> In my case it was an SQL query with special symbols,

Could you provide an example of the special symbols that caused the problem?

> Maybe it is better to throw an exception if output of json_encode is false in this case?

We should not only throw an exception, but also try to solve this problem. Caching should not break due to special characters.

> And i guess i need to create another ticket for `\yii\db\Command::queryInternal`?

If this is a different kind of problem, then yes. If `\yii\db\Command::queryInternal` issue is about the same problem, then no.

**Comment by smsteel** [comment]
In my specific case i'm just using non-utf8 encoding with database. It is documented that json_encode input's `all string data must be UTF-8 encoded.`.
But in method `\yii\db\Command::queryInternal` cache key is using raw sql:

    $cacheKey = [
                    __CLASS__,
                    $method,
                    $fetchMode,
                    $this->db->dsn,
                    $this->db->username,
                    $rawSql,
                ];

Currently, i monkey-patched this and using additional hash-function to encode `$rawSql` inside the `$cacheKey` array.

**Comment by smsteel** [comment]
Anyway, more relevant to the topic is that there's a lot more cases when json was not generated which will lead to unexpected behaviour of Cache component:
[json-last-error](http://php.net/manual/ru/function.json-last-error.php)

**Comment by cebe** [comment]
it should probably use `serialize` instead of `json_encode`. It was like that long time ago: https://github.com/yiisoft/yii2/commit/c08c2e8b727031248a820b682070b7a5afa8ba36#diff-939db7aecd14e2b72c04d8f878da53e3

**Comment by samdark** [comment]
Yes. Probably should be changed back. The reason for serialize -> json was performance.

**Comment by smsteel** [comment]
Maybe the best will be to try `json_encode` the `$key` first and then fallback to serialize if it fails?

**Comment by smsteel** [comment]
Hmm.
I'm trying to reproduce speed issues and actually getting complete opposite results.
`json_encode` performs 3x slower than `serialize` or even more, depending on data.
My test case is array with 3 string elements (up to 900 symbols each) and object with the same properties:

    json_encode object 2.4s
    json_encode array 2.3s

    serialize object 0.72s
    serialize array 0.73s

Running on php 7.1. With php5.6 i get about the same difference with slower overall performance.
Arrays with similar data are used by Yii2 in case of query caching, so current code seems to be actually slower for this case. I'll try to test on real project soon.

Can you remember in which case `serialize` was slower?

**Comment by cebe** [comment]
> Can you remember in which case serialize was slower?

proably measured on PHP 5.3 or something :) We should update code according to recent knowledge.

**Comment by smsteel** [comment]
So i've run some tests with Yii2 on a real project. 

First, i'ts really faster to use `serialize`. But i've learned something else, because i'd run test for complete code with query cache as well.

If i use current version of `\yii\db\Command::queryInternal` performance becomes much worse with both `json_encode` and `serialize`. It becomes worse exponentially if i increase number of calls.
So i changed `\yii\db\Command::queryInternal` to use `md5` for generating cache key:

    $cacheKey = [
        __CLASS__,
        $method,
        $fetchMode,
        $this->db->dsn,
        $this->db->username,
        md5($rawSql),
    ];

Now performance seems to be linear and there's only 20% difference between `json_encode` and `serialize`. And both functions performs much faster.

Also, i tried to reproduce performance on old php versions, i'm still getting results for `serialize` being faster. Maybe, `$key` must be specific for this to be an opposite case?

**Comment by cebe** [comment]
> It becomes worse exponentially if i increase number of calls.

if you make a lot of database calls, make sure query logging is turned off, otherwise yii will write a lot of queries to the log dispatcher.
