### ISSUE TITLE
Create "json" field  on PostgreSQL by migration Yii 2.0.14.1

### ISSUE THREAD

**Issue by titanproger** [yiisoft/yii2#16029]
Can not find proper way to create json field by migration mechanism.
Database PostgreSQL 10

### What steps will reproduce the problem?
Create migration  for 

```
$this->createTable('table_name', [
            "id" => $this->bigPrimaryKey(),
            "body" => "json",   // warning "json" generates jsonb type
        ]);
```

### What is the expected result?
Created table with field body type "json"

### What do you get instead?
Created table with field body type "jsonb"

### Additional info
According to [postges doc](https://www.postgresql.org/docs/10/static/datatype-json.html)
"In general, most applications should prefer to store JSON data as jsonb, unless there are quite specialized needs, such as legacy assumptions about ordering of object keys."

So some application need create json instead jsonb.
Jsonb just little slower for store and read and it changes keys ordering.

Please add possibilty to create json not only jsonb
Prev  [issue](https://github.com/yiisoft/yii2/pull/15560#issuecomment-378207067)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version    7.1  | 
| Database - PostgreSQL 10 |
| Operating system  Linux Debian Jessie |

**Comment by finnan444** [comment]
As I;ve already stated in previous issue,  this flag should be added to \yii\db\SchemaBuilderTrait::json() as parameter, if we call it in migration like this
```PHP
$this->addColumn('public.user', 'kyc_info', $this->json()->null());
```

**Comment by cebe** [comment]
as far as I see, this should be changed to `json` if you want jsonb you need to explicitly type the name:

https://github.com/yiisoft/yii2/blob/7b0fb14c3c9a995cebfb42e5c5f586e9f6edce72/framework/db/pgsql/QueryBuilder.php#L77

**Comment by cebe** [comment]
it will not work as it will be replaced on the lower level. Even if SchemaBuilder generates a string like `json` it will be replaced by QueryBuilder by `jsonb` again.

**Comment by SilverFire** [comment]
In case you need to create `JSON` column instead of `JSONB` I would suggest not to use schema builder and define type manually. PostgreSQL is the only engine (as far as I know) that supports two different types of JSON and considering JSONB is more flexible, we use it by default for `QueryBuilder::json()`.

**Comment by titanproger** [comment]
So how it would be possible to create json type by migration?
only manually sql command?

**Comment by samdark** [comment]
Yes.

**Comment by titanproger** [comment]
finnaly i find other way to solve this
```
$this->createTable('report', [
            "id" => $this->bigPrimaryKey(),            
            "body"        =>  " json", // <- this will generate json field not jsonb
        ]);
```
or for better 

   ```
 public function json($length = null) {
        return $this->getDb()->getSchema()->createColumnSchemaBuilder(" ".Schema::TYPE_JSON, $length);
    }
   ...............
    $this->createTable('report', [
            "id" => $this->bigPrimaryKey(),            
            "body"        =>  $this->json(),
        ]);
```

**Comment by edegaudenzi** [comment]
`(" ".\yii\db\pgsql\Schema::TYPE_JSON)` is still a working workaround nowadays.
