### ISSUE TITLE
Inaccurate result when searching by primarykey with string in number

### ISSUE THREAD

**Issue by combinator** [yiisoft/yii2#16031]
### What steps will reproduce the problem?
Seems like Yii2 auto strips off non-integer characters from integer primary keys. 
Example :
Create table and set primary key for as BIGINT, Unsigned. 
Create a record with primary key , e.g 6565 .
Search for record 
Model::findOne(6566a) ; 
REsult : Model record with ID 6566 is returned. 

### What is the expected result?
NULL . No item found.

### What do you get instead?
REsult : Model with ID 6566 is returned. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.2
| Operating system | Centos 7

**Comment by Alex-Code** [comment]
I can reproduce this in MySQL so it's not a Yii thing.
It might be the optimizer casting the value to the type of the column which trims off characters.
