### ISSUE TITLE
BaseHtml:: normalizeMaxLength private

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii2#16033]
Is there a reason because this method is private?

https://github.com/yiisoft/yii2/blob/eb198413f22d67fc2ed213b2c469633ead50c08e/framework/helpers/BaseHtml.php#L1340

I'm creating a textarea widget with used characters counter and I'd need to get max length of model attribute.

Could be useful to split this method into two, the first to return max length and the second to return the same output of subject method?

**Comment by Alex-Code** [comment]
If you use [Html::activeTextarea](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1492) you could read the `maxlength` attribute with javascript from the textarea element.

**Comment by FabrizioCaldarelli** [comment]
But If I want to implement some extra html based on maxlength of input or textarea?

**Comment by cebe** [comment]
method should be protected.

**Comment by FabrizioCaldarelli** [comment]
Anyway, If it was protected, it could not be used from other classes (that do not extend BaseHtml or Html class).

What do you think if i create a PR to create a `stringMaxLength` method and rewrite `nomalizeMaxLength` that reads value from previous new method?
