### ISSUE TITLE
Existing working model method does not working everywhere

### ISSUE THREAD

**Issue by bugToaster** [yiisoft/yii2#16032]
I create a public method to upload image name with setImageUpload(). Its working fine on old all modules controller & models file. But when I am generating new module and extend my Media model and call that method then it shows me **Call to undefined method backend\modules\media\Media::setImageUpload()** 

### What steps will reproduce the problem?
If I change method name then it works fine again. But it should not behave like this.

### What is the expected result?
work with this method without change name.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.3
| Operating system | Ubuntu

**Comment by mgrechanik** [comment]
You would better discuss your coding problems on forum
