### ISSUE TITLE
session store in db

### ISSUE THREAD

**Issue by nasserms** [yiisoft/yii2#16037]
I'm using `yii\web\DbSession` to store session in db, on login it is working fine and storing the data 

`'session' => [
          'class' => yii\web\DbSession::Class,
            'writeCallback' => function($session){
                         return [
              'user_id' => Yii::$app->user->id,
                ];
            },
]`

when I want to logout it gives me error

`Integrity constraint violation: 1048 Column 'user_id' cannot be null`

**Comment by samdark** [comment]
I guess because when you're logged out your user has no ID.

**Comment by rob006** [comment]
`Yii::$app->user->id` is `null` for guests, so you're trying to replace `user_id` from `41` to `null`.
