### ISSUE TITLE
\Yii::$app->getRequest()->getRawBody()

### ISSUE THREAD

**Issue by Auramel** [yiisoft/yii2#16045]
Hi! I work with postman and make API service. So, I send json data in "body" in postman and not found them in Request class post() get() bodyParams() queryParams() getRawBody(). 

In my controller I write 
```php
public function actionIndex(string $token)
{
    var_dump(file_get_contents('php://input'));
    var_dump(\Yii::$app->getRequest()->getRawBody());
}
```

All of this methods returned `string(0)""`

Ok. Then, I have idea, that it something with Yii core. I open my /web/index.php and add this code (upper) before (new Appliaction())->run(). And magic! It write me my body params.
I don't understand what problem is. What happened? It's bug or my stupidity?

**UPD:** For testing I create a form in browser and send some data. It working. So, it's postman bug?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system | Windows 10 PRO x64 with OpenServer 5.2.5

**Comment by Auramel** [comment]
okey, i attach screenshots. 

1. My Controller code is [http://ibb.co/jWk1nH](http://ibb.co/jWk1nH)
2. My Postman request is [http://ibb.co/g2ei1c](http://ibb.co/g2ei1c)
3. My Postman header is [http://ibb.co/dvqO1c](http://ibb.co/dvqO1c)
4. Site response is [http://ibb.co/k7it1c](http://ibb.co/k7it1c)

But! When i write like this [http://ibb.co/gUfTZx](http://ibb.co/gUfTZx)
I have a response like this [http://ibb.co/b7Eu7H](http://ibb.co/b7Eu7H)

**Comment by frontbear** [comment]
try this:
```php
public function actionIndex(string $token)
{
    var_dump(file_get_contents('php://input'));
    var_dump(\Yii::$app->getRequest()->getRawBody());
    exit;
}
```

**Comment by xyluet** [comment]
you need to add this to your config

https://www.yiiframework.com/doc/api/2.0/yii-web-jsonparser

**Comment by Auramel** [comment]
not help

**Comment by Auramel** [comment]
Of course! I would be very grateful! [https://bitbucket.org/Auramel/yii/src/f8006b5174f12762486b85016f7c54f34342e0d1/config/web.php?at=master&fileviewer=file-view-default](https://bitbucket.org/Auramel/yii/src/f8006b5174f12762486b85016f7c54f34342e0d1/config/web.php?at=master&fileviewer=file-view-default) and I add you request parser.

**Comment by livend** [comment]
\Yii::$app->getRequest()->getRawBody()
use like this
