### ISSUE TITLE
Cors filter is broken since 2.14

### ISSUE THREAD

**Issue by russianlagman** [yiisoft/yii2#16044]
### What steps will reproduce the problem?
We have some action responding to the OPTIONS calls. 
It is replying with the Access-Control-Allow-Methods set to available verbs. That is required for CORS requests to be done. 

### What is the expected result?
We see the response header.

### What do you get instead?
We have 200 status and no headers.

### Additional info
That is caused by a wrong condition in a Cors filter. 
https://github.com/yiisoft/yii2/blob/master/framework/filters/Cors.php#L109
We never get our options action running.
![image](https://user-images.githubusercontent.com/1983796/38359044-50ee2406-38f1-11e8-91f3-7be251efadec.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.15.1
| PHP version      | 7.1
| Operating system | Linux

**Comment by samdark** [comment]
Seems to be valid according to https://www.w3.org/TR/cors/#preflight-result-cache

**Comment by russianlagman** [comment]
@samdark we had not configured allowed methods
```'cors => [
    ...
    'Access-Control-Request-Method' => ['GET', 'PUT', 'DELETE', 'PATCH', 'POST', 'HEAD', 'OPTIONS'],
],
```
But instead we was sending this headers in the separate OPTIONS action.
Looks everything is working if we add all verbs to the `Access-Control-Request-Method` param.

**Comment by russianlagman** [comment]
That configuration works perfectly for me 
```
        $behaviors['corsFilter'] = [
            'class' => Cors::class,
            'cors' => [
                'Origin' => ArrayHelper::getValue(\Yii::$app->params, 'cors.origin', ['*']),
                'Access-Control-Request-Headers' => ['Authorization', 'Access-Control-Allow-Origin', 'X-Pagination-Total-Count', 'X-Pagination-Page-Count', 'X-Pagination-Current-Page', 'X-Pagination-Per-Page'],
                'Access-Control-Expose-Headers' => ['Authorization', 'X-Pagination-Total-Count', 'X-Pagination-Page-Count', 'X-Pagination-Current-Page', 'X-Pagination-Per-Page'],
            ]
        ];
```
