### ISSUE TITLE
Send new model to checkAccess in yii\rest\CreateAction and yii\rest\UpdateAction

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii2#16049]
(recreated from https://github.com/yiisoft/yii2/pull/5821 upon cebe request).

UpdateAction calls checkAccess() with existing model as a parameter. Why not to send an updated/created model as a third argument to checkAccess() (in $params)? The same goes for CreateAction.

Let's say I work with User model and property user_role can be set to "admin" by superadmin only. If regular user is trying to set that value then it's reasonable to throw Forbidden exception. I would consider checkAccess() function is a appropriate place to throw forbidden exception rather than in model validator (because user_role can have "admin" value set, it just has to be set by user with enough access permissions).

>checkAccess is used to determine whether a user is allowed to call a specific action. This may depend on an existing model that has been created.

If it may depend on existing model values then it can also depend on newly sent model values.

>Restrictions in creating a model should be covered by validation rules

As a workaround I check \Yii::$app->user in the model validation (to see whether logged in user is a superadmin - for text case described above) but \Yii::$app->user is a feature of web application and if to speak about proper layer separation it would be beneficial to decouple Model that it could be reused in console application.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      |  7.1.15-1
| Operating system | Ubuntu 14.04.5

**Comment by samdark** [comment]
@cebe it's not a bug report but a feature. Should be moved to https://github.com/yiisoft/yii2-rest. Is there a label for that?
