### ISSUE TITLE
Javascript registered in renderDynamic doesn't appear anywhere

### ISSUE THREAD

**Issue by nagyt234** [yiisoft/yii2#16051]
### What steps will reproduce the problem?
Any widget using JS will not work in renderDynamic. A simple demonstration is the following line in any view:
```
<?= $this->renderDynamic('$this->registerJsFile("https://www.google.com/recaptcha/api.js", ["async" => true, "defer" => true]);'); ?>
```
The example is silly, but it demonstrates, that the `api.js` file is included in the HTML page.

### What is the expected result?
The registered JavaScript  should appear in the HTML page.
### What do you get instead?
All Javascript registered in renderDynamic is missing.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.1.14-1+ubuntu16.04.1+deb.sury.org+1
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
Do you have the following in your layout?

- https://github.com/yiisoft/yii2-app-basic/blob/master/views/layouts/main.php#L15
- https://github.com/yiisoft/yii2-app-basic/blob/master/views/layouts/main.php#L24
- https://github.com/yiisoft/yii2-app-basic/blob/master/views/layouts/main.php#L27
- https://github.com/yiisoft/yii2-app-basic/blob/master/views/layouts/main.php#L78
- https://github.com/yiisoft/yii2-app-basic/blob/master/views/layouts/main.php#L81

**Comment by nagyt234** [comment]
Dear @samdark. Thanks for the answer. Of course I have them.
My fault, that I forgot to mention, that the JS is not registered if I use the PageCache. Otherwise the renderDynamic has no sense.
I have the following behavior in my controller:
```
            'indexCache' => [
                'class' => 'backend\components\filters\PageCache',
                'only' => ['index'],
                'duration' => 86400,    // 1 day
                'variations' => [
                    Yii::$app->locale->language->code,
                ],
                'enabled' => Yii::$app->user->getIsGuest(),
            ],
```

**Comment by s1lver** [comment]
@nagyt234 I can not reproduce your mistake. Could you please clarify the steps leading to the error?

View:
```php 
$this->renderDynamic($this->registerJsFile("https://www.google.com/recaptcha/api.js", ["async" => true, "defer" => true]));
```

Controller:
```php
/**	
* @inheritdoc
 */
public function behaviors() {
	return [
		...
		'indexCache' => [
			'class' => PageCache::class,
			'only' => ['form'],
			'duration' => 86400,
			'variations' => [
				Yii::$app->language,
			],
			'enabled' => Yii::$app->user->getIsGuest(),
		],
	];
}
```
HTML
```html
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
```

**Comment by rob006** [comment]
@s1lver Did you tried this with full page caching?

**Comment by nagyt234** [comment]
Please, RE-OPEN this bug.

I'm writing now step by step, how to reproduce the problem. It is very easy.
1. Create a YII2 system with the Basic Template and go there:
```
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
cd basic
```
2. Add the following line as line 2 in `views/site/index.php`:
```
$this->renderDynamic('$this->registerJsFile("https://www.google.com/recaptcha/api.js", ["async" => true, "defer" => true]);');
```
3. Start the simple WEB server
```
php yii serve --port=8888
```
4. Check that the api.js is included in the HTML source if you view the Home page. Click on Home, than press CTRL-U in the browser to view the source and look for the following line:
```
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
```
5. Now add PageCache to the Index action. Add the following code in the function `behaviors` in  `controllers/SiteController.php`:
```
'indexCache' => [ 
    'class' => 'yii\filters\PageCache',
    'only' => ['index'],
    'duration' => 86400,    // 1 day
    'enabled' => true,
],
```
6. Check again the Home page. The `api.js` IS NOT INCLUDED anymore.

This problem causes, that it is not possible to use any widgets in `renderDynamic` on a cached page which has JavaScript or CSS assets.
