### ISSUE TITLE
FileCache: check duration on reading to avoid touch calls

### ISSUE THREAD

**Issue by Slamdunk** [yiisoft/yii2#16050]
### What steps will reproduce the problem?

1. OS has 2 users [user : group]
    1. `code-owner`:`code-reader`
    1. `apache`:`code-reader`
1. Build the cache as `code-owner` so this user will be the owner of the files
1. Cache is built with `0770` permissions, so both users can write it
1. Try to rebuild the cache as `apache`

### What is the expected result?

`filemtime` updated accordingly to cache duration

### What do you get instead?

`filemtime` is not altered because the `touch` call here:

https://github.com/yiisoft/yii2/blob/2.0.15.1/framework/caching/FileCache.php#L152

Return the error `touch(): Utime failed: Operation not permitted`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | Linux Debian

### Solution

Instead of setting the cache duration by altering the `filemtime` in the future, we should simply use the `file_put_contents` during cache writing, and then checking on cache reading that `filemtime + $duration > time()`

**Comment by rob006** [comment]
> and then checking on cache reading that `filemtime + $duration > time()`

There is no `$duration` available on cache reading.

**Comment by Slamdunk** [comment]
Another solution is to delete and recreate the file if the touch call fails, and then retry the touch call.

A bit expandive operation, but done only:

1. if the original touch call fails
1. on cache creation

So no real performance loss

**Comment by SilverFire** [comment]
Thank you for the reported issue. Would you like to help up to fix this issue by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.

**Comment by rob006** [comment]
This is already fixed by #16120
