### ISSUE TITLE
GUIDE RFE: Please, add full core validators list at the top of page

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#16059]
There page https://www.yiiframework.com/doc/guide/2.0/en/tutorial-core-validators
was very convenient on previous version of site, when full validators list was at the top of page.
Now, we need to scroll entire page to find validator name we need.
Please, bring back the full validators list at the top of page, ex. as a page content with internal links.

**Comment by cebe** [comment]
on large screens you have them on the right side:

![bildschirmfoto von 2018-04-08 14-41-49](https://user-images.githubusercontent.com/189796/38467579-0648167c-3b3b-11e8-8e97-3d7d6caa6187.png)

on smaller screen you have the table of contents:

![bildschirmfoto von 2018-04-08 14-42-31](https://user-images.githubusercontent.com/189796/38467584-18428704-3b3b-11e8-86a6-087c0416e88e.png)
