### ISSUE TITLE
saveAs() not work

### ISSUE THREAD

**Issue by KaungZawHtet** [yiisoft/yii2#16053]
saveAs() can save only one time!

Eg.
$uploadedFile=UploadedFile::getInstance($model, 'file');
$uploadedFile2=UploadedFile::getInstance($model, 'file');

$uploadedFile->saveAs('uploads/' .$uploadedFile->name); // This first time work fine
$uploadedFile2->saveAs('uploads/' .$uploadedFile2->name);//Problem! nothing happened

/*------------------------ Or-------------------*/

$uploadedFile=UploadedFile::getInstance($model, 'file');
$uploadedFile->saveAs('uploads/' .$uploadedFile->name); // This first time work fine
$uploadedFile->saveAs('uploads/' .'AnotherFileName');//Problem! nothing happened

| ---------------- | ---
| Yii version      | 2.0.12?
| PHP version      | 7.14
| Operating system | Mac

**Comment by cebe** [comment]
if you want to use the same method twice you have to set second parameter of saveAs(), $deleteTempFile to false: .

**Comment by KaungZawHtet** [comment]
thx
