### ISSUE TITLE
Неверно работает разбор построителя запросов

### ISSUE THREAD

**Issue by gaginsgagins** [yiisoft/yii2#16057]
### Делаем простой запрос с джоином 2х таблиц.
```
Pair::find()->joinWith('source')
            ->select("CONCAT(pair.name, source.name) name, pair.id ")
            ->indexBy('id')
            ->column())
```

### При разборе получаем вот это

 SELECT CONCAT(pair.name, `source`.`name)`AS `name`, `pair`.`id` FROM `pair` LEFT JOIN `source` ON `pair`.`source_id` = `source`.`id`
![default](https://user-images.githubusercontent.com/25243076/38455515-05e65bf8-3a82-11e8-87c3-ac7c053e10f7.PNG)
апостораф, который должен закрывать  `source`.`name выносится за скобки и я получаю ошибку синтаксиса SQL

### Решается путем ручного вписывания апострафов

```
Pair::find()->joinWith('source')
            ->select("CONCAT(pair.name, `source`.`name`) name, pair.id ")
            ->indexBy('id')
            ->column())
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      | 7.0.8
| Operating system |win7

**Comment by samdark** [comment]
https://www.yiiframework.com/doc/api/2.0/yii-db-expression

**Comment by gaginsgagins** [comment]
при замене на такую конструкцию 
```
$expr = new \yii\db\Expression('CONCAT_WS(" ",pair.name, source.name) name, pair.id');

        $form->field($model,'PairID')->dropDownList(Pair::find()->joinWith('source')
        ->select($expr)
        ->indexBy('id')
        ->column()
```

на выходе получаю не результат запроса, а  само выражение 
`CONCAT_WS(" ",pair.name, source.name) name, pair.id`

**Comment by schmasterz** [comment]
Can you provide the plain query? Hint : "explain" is your best friend.

**Comment by gaginsgagins** [comment]
`        $expr = new \yii\db\Expression('CONCAT_WS(" ",pair.name, source.name) as name, pair.id');

        $form->field($model,'PairID')->dropDownList(Pair::find()->joinWith('source')
            ->select($expr)
            ->indexBy('id')
            ->column()`

![image](https://user-images.githubusercontent.com/25243076/38486811-c993d304-3be6-11e8-937b-6849462ea775.png)
