### ISSUE TITLE
Cookie method has returns wrong value when using in response

### ISSUE THREAD

**Issue by OndrejVasicek** [yiisoft/yii2#16068]
### What steps will reproduce the problem?
Add cookie

```
Yii::$app->response->cookies->add(new Cookie([
                'name' => 'test',
                'value' => 1,
            ]));
```

### What is the expected result?
When checking if the CookieCollection has the current cookie, it should return true.
`$value = Yii::$app->response->cookies->has('test')`

### What do you get instead?
`$value` is actually false.

I suppose its because in the Yii code `expire` is checked and the cookie has `expire` 0 in my case. But it's a valid value, it means 'until the browser is closed'.

```
return isset($this->_cookies[$name]) && $this->_cookies[$name]->value !== ''
    && ($this->_cookies[$name]->expire === null || $this->_cookies[$name]->expire >= time());
```

### Suggested solution
I’d updated the code like this, but I'm really not sure if it's enough and won't break anything.
```
return isset($this->_cookies[$name]) && $this->_cookies[$name]->value !== ''
    && ($this->_cookies[$name]->expire === null || $this->_cookies[$name]->expire === 0 || $this->_cookies[$name]->expire >= time());
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.4
| Operating system | Win10

**Comment by SilverFire** [comment]
Thank you for the reported issue. Would you like to help up to fix this issue by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.

**Comment by OndrejVasicek** [comment]
Of course I can make a pull request, but that’s why I wrote the issue – I’m not sure if the suggested code is ok. If it doesn’t break anything. I’m really not so self-confident about the Yii2 core.
So if you guys says “your solution is perfectly fine and bulletproof”, I’ll happily make a pull request.

**Comment by SilverFire** [comment]
It's perfectly fine for me :)
