### ISSUE TITLE
Anonymize IP in Logs

### ISSUE THREAD

**Issue by Lugat** [yiisoft/yii2#16066]
Due to the new european privacy law it would be great to have the possibility, to remove or at least anonymize the IP in the Yii logs.

**Comment by cebe** [comment]
you can configure `Target::$prefix` to customize logging of IP: https://www.yiiframework.com/doc/api/2.0/yii-log-target#$prefix-detail

**Comment by lukeyouell** [comment]
@cebe how would I go about configuring this value? I can't seem to find anything in the docs. Cheers.

**Comment by Lugat** [comment]
I am using this to remove the IP.

`'prefix' => function() {
  return null;
}`

**Comment by lukeyouell** [comment]
Cheers @Lugat I was running into some conflicts with Craft CMS, but those have now been resolved!
