### ISSUE TITLE
multiple nested modules, default parsing rules bug?

### ISSUE THREAD

**Issue by ReDev1L** [yiisoft/yii2#16071]
### What steps will reproduce the problem?
So we have 3 nested modules: admin -> parser -> deals.
Deals module has ProfileConstructorController (profile-constructor)
Controller has actionDeleteProfile (delete-profile).
and action parameter "id"=2
No routing rules, default parsing rules.
### What is the expected result?
GET: http://domain/admin/parser/deals/profile-constructor/delete-profile/2
route found, RESPONSE: 200 OK.

### What do you get instead?
GET: http://domain/admin/parser/deals/profile-constructor/delete-profile/2
route not found, response: 404, not found

### Additional info
GET: http://domain/admin/parser/deals/profile-constructor/delete-profile
route found, 400 Bad request, missing param id.(expected behavior)
GET: http://domain/admin/parser/deals/profile-constructor/delete-profile?id=2
route found, 200 OK.

If i switch deals module to root module - all works.
GET: http://domain/deals/profile-constructor/delete-profile/2
route found, RESPONSE: 200 OK.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.3
| Operating system | Ubuntu 16.04

**Comment by ReDev1L** [comment]
added to rules:
`'<module1:[\w\-]+>/<module2:[\w\-]+>/<module3:[\w\-]+>/<controller:[\w\-]+>/<action:[\w\-]+>/<id:\d+>' => '<module1>/<module2>/<module3>/<controller>/<action>',`
all works, but i still think default parsing rules have bug with named parameters

**Comment by rob006** [comment]
> No routing rules, default parsing rules.

What do you mean by this? Can you share your UrlManager config (which handles `GET: http://domain/deals/profile-constructor/delete-profile/2` correctly)?

**Comment by ReDev1L** [comment]
''urlManager'   => [
			'baseUrl'         => $baseUrl,
			'showScriptName'  => false,
			'enablePrettyUrl' => true,
			'rules'           => [], //default parsing rules, no custom rules
		],
'

**Comment by rob006** [comment]
@ReDev1L By default `UrlManager` does not handle any named params in URLs - if `http://domain/deals/profile-constructor/delete-profile/2` works for you, you probably has some custom rules (they can be inherited from common config if you merge configs). To support pretty URLs for `<module1>/<module2>/<module3>/<controller>/<action>/<id>` patters you must add rule for this in the same way as you did it for `<module>/<controller>/<action>/<id>`.

I'm not sure if we should support such URLs by default - framework should not force such convention for URLs. However this could be done as part of #14974 - default `FallbackUrlRule` will work same as now (handle only routes in path), but we could extend it and create `FallbackUrlRuleWithIdInPath` to support `<module>/<controller>/<action>/<id>` patterns with any level of nesting. Then you could add only one rule (or configure `UrlManager::$fallbackRule`) instead manually adding own rules for every level of nesting.

**Comment by ReDev1L** [comment]
@rob006 Tested again, you are right, my bad. I had rule with named param. m1/c1/a1/:id.

This fallback rule enhancement is very good idea.
