### ISSUE TITLE
composer.lock has wrong version when upgrading to 2.0.12.1

### ISSUE THREAD

**Issue by michaelnguyen547** [yiisoft/yii2#16072]
When upgrading from 2.0.12 to 2.0.12.1 using

composer require "yiisoft/yii2":"~2.0.12.1"

in the composer.lock file, the version shows "2.0.12.2"

I don't know if this will affect "composer install" so I haven't tried it on the production server yet. However, downgrade from 2.0.12.1 -> 2.0.12 will not update the composer.lock correctly (e.g. the version 2.0.12.2 still there)

### What steps will reproduce the problem?
upgrade from 2.0.12 to 2.0.12.1

### What is the expected result?
composer.lock should show "version" : "2.0.12.1"

### What do you get instead?
composer.lock shows "version" : "2.0.12.2"

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6
| Operating system | ubuntu 14.04

**Comment by rob006** [comment]
This is how `~` operator works: https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
You should use `2.0.12.0` or `2.0.12.1` (without any operators) if you want to stick  to one of this version. But I suggest to upgrade - `2.0.12.1` has some security issues.

**Comment by michaelnguyen547** [comment]
this article needs to update [https://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes]

The confusing part is it asks to "composer require "yiisoft/yii2":"~2.0.12.1"

but there is a 2.0.12.2 version as well. So I got 2.0.12.2 and i thought it was wrong.

**Comment by cebe** [comment]
2.0.12.2 is a patch applied to 2.0.12.1, to limit the BC break that comes with the security fix.

**Comment by cebe** [comment]
updated the news:

> **Update:** We have since released further patches to lower the impact of the BC break introduced by the security fix, so you get versions 2.0.15.1, 2.0.13.3 and 2.0.12.2 from the above.
