### ISSUE TITLE
FileHelper::createDirectory can throw an unexpected Exception

### ISSUE THREAD

**Issue by scottix** [yiisoft/yii2#16086]
FileHelper::createDirectory is more complicated than it should be to catch all failures.

### What steps will reproduce the problem?
If you do something like this
```php
if(FileHelper::createDirectory($someFolder) === false) {
    return false;
}
```
It is possible you may not hit all error scenarios because it can throw an exception, so the proper way is to do something like this.
```php
try {
    if(FileHelper::createDirectory($someFolder) === false) {
        return false;
    }
} catch(\Exception $e) {
    return false;
}
```

### What is the expected result?
I would expect most people will write code in the first sample not the second sample, which can lead to unexpected errors.

**Comment by marcelodeandrade** [comment]
But it is a implementation issue, not a **FileHelper** fault.

**Comment by scottix** [comment]
It is catch-able but I believe throwing an exception is kind of unnecessary. If you compare it to the php rmdir which doesn't throw an exception.

**Comment by samdark** [comment]
Yii converts all errors into exceptions so that's expected.

**Comment by scottix** [comment]
So you expect people to write code in Sample 2?

Yes Yii2 handles exceptions at a higher level, which you could still do in places you use it.

I just think diverting how core php handles mkdir and how Yii2 handles it are at odds with each other.

Anyway I can deal with it, but fundamentally having two ways to produce failures in a function just seems inconsistent and unknowingly not good. My two cents.

**Comment by rob006** [comment]
@scottix Catching all exception blindly will only make code harder to debug. If you have specific case when `createDirectory()` should not throw a exception, you should share it with us. Without it, it is only a theoretical conversation without any chance for practical changes.

**Comment by scottix** [comment]
@rob006 No problem I can be more clear about it in an example.

```php
function doImportantStuff() {

    doSomeStuff1();

    $someDir = '/somepath';
    if(FileHelper::createDirectory($someDir) === false) {
        undoSomeStuff1();
        return false;
    }
    
    return true;
}
```
There are instances where undoSomeStuff1() would not get run because an exception was thrown.

It's up to you guys how you want your philosophy of coding just when I need absolute assurance of functions, I'll either have to write my own or wrap yours on my own. Good thing for inheritance.

**Comment by rob006** [comment]
> because an exception was thrown

What exception was thrown and why?

**Comment by scottix** [comment]
There are two

When supposed path is not a directory
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L629

And

When chmod fails
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L635

Since it is recursive it could lead to other directories not being created.

To be honest the only reason I found this, when I was writing a different function using the createDirectory, it documented that it might throw an exception and that raised red flags for me.

**Comment by rob006** [comment]
@scottix That is expected - usually you really need create this directory and further processing does not make any sense if this fails (for example you can't upload a file when there is no directory for uploads). And usually this is result of app misconfiguration so throwing exception is more practical than checking method result and throwing exception manually.

**Comment by scottix** [comment]
@rob006 I think we will have to agree to disagree, I can handle it on my own, if you want to leave it as is. Just a note mis-configuration can be a problem, but also a corrupted file system can be a reason. Really it doesn't matter what the problem is, the main point I am making is, in my use case I need to handle the fallout if it does error out. I know Yii will catch the error at the top level but that is not what I want.
