### ISSUE TITLE
Illegal offset type in isset or empty in InConditionBuilder

### ISSUE THREAD

**Issue by ilgiz-badamshin** [yiisoft/yii2#16081]
### What steps will reproduce the problem?
Set one column as array to in condition:
```
MyModel::find()
->andWhere(['in', ['id'], [['id' => 1, 'name' => 'Name1'], ['id' => 2, 'name' => 'Name2']]])
->all();
```
### What is the expected result?
Return my models where id in (1, 2)

### What do you get instead?
Exception: Illegal offset type in isset or empty
```
yiisoft/yii2/db/conditions/InConditionBuilder.php  93
 $value = isset($value[$column]) ? $value[$column] : null;
```

### Some researches
In InConditionBuilder build function check count($column), normalize it by reset($column) and call buildValues.
```
public function build(ExpressionInterface $expression, array &$params = [])
...
if ($column instanceof \Traversable || ((is_array($column) || $column instanceof \Countable) && count($column) > 1)) {
    return $this->buildCompositeInCondition($operator, $column, $values, $params);
}

if (is_array($column)) {
    $column = reset($column);
}

$sqlValues = $this->buildValues($expression, $values, $params);
```
But in function buildValues $column is not normalized and equals to  `[ 0 => 'id']`
```
protected function buildValues(ConditionInterface $condition, $values, &$params)
{
    $sqlValues = [];
    $column = $condition->getColumn();
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system | Ubuntu

**Comment by Alex-Code** [comment]
According to the code a composite in condition needs more than 1 column name.
I don't know if it's a requirement so it's either a bug or you need to do something like,
```php
$data = array_column([['id' => 1, 'name' => 'Name1'], ['id' => 2, 'name' => 'Name2']], 'id');
MyModel::find()
  ->andWhere(['id' => $data])
  ->all();
```

**Comment by Alex-Code** [comment]
Ah yeh, I see it now.
`buildValues` is calling [`getColumn()`](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L89) when it should probably have the column passed to it.

**Comment by SilverFire** [comment]
Thank you for the reported issue. Would you like to help up to fix this issue by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.

**Comment by Alex-Code** [comment]
I can do a PR for this but which route would be better?

1. Changing the parameter of `buildValues` which could affect BC.
or
2. Have the same code that's in [`build`](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L57) in the `buildValues` method.

**Comment by SilverFire** [comment]
I would remove columns count check [here](https://github.com/yiisoft/yii2/blob/819e2815b83ca91499567ab9cacc0716b90c74d9/framework/db/conditions/InConditionBuilder.php#L53).

In this case for the reported issue the composite in condition will be generated, regardless it contains only one column.
