### ISSUE TITLE
Yii2 basic app - poor performance

### ISSUE THREAD

**Issue by arjuncvn** [yiisoft/yii2#16084]
I had configured yii2 basic application template in windows server (Dual core processor, 8 GB RAM) No extra code written other than just installing it.When testing with apache jmeter with 100 concurrent users in 10 min CPU usage get hit 99% and the server freezes.Normal static PHP page would work without any issues under the same test, if placed outside the framework.It only take around 2-3 percent of CPU utilisation.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by marcelodeandrade** [comment]
You can provide some more infos? 

Wich web server you are using? Apache | Nginx | IIS 
What is the version of Yii and PHP? 
Windows Server 20xx?

**Comment by arjuncvn** [comment]
Apache version: 2.4
PHP Version: 5.5
Windows Server 2012 r2

**Comment by cebe** [comment]
> and the server freezes

this is unlikely related to yii. It could be improper configuration of the apache or php process limits according to server resources.
