### ISSUE TITLE
FileHelper::removeDirectory does not return anything

### ISSUE THREAD

**Issue by scottix** [yiisoft/yii2#16087]
Seems like removeDirectory attempts to recursively remove directories. But the user has no idea if this has succeeded or not, since it doesn't return anything.

### What steps will reproduce the problem?
```php
$result = FileHelper::removeDirectory($someDir);
if($result === null) {
    echo 'My folder could still be there';
}
```
### What is the expected result?
Should return true or false

### What do you get instead?
NULL

**Comment by SilverFire** [comment]
Thank you for the reported issue. Would you like to help up to fix this issue by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.

**Comment by rob006** [comment]
In the case of failure exception should be thrown. Is there any case when directory will not be deleted without exception?

**Comment by samdark** [comment]
That's a good question. I think there are no cases like that.

**Comment by scottix** [comment]
I think I have a very different view on the approach of error handling with functions like these. It may work for Yii2 as a framework, but totally makes this function useless in my application and use cases. Good luck, I'll be writing my own.
