### ISSUE TITLE
saveAs() doesn't work at other page

### ISSUE THREAD

**Issue by KaungZawHtet** [yiisoft/yii2#16080]
I want to save a same file double time at 2 pages according to my requirement. First I try with session but nothing happened. And now I prefer to work with cache but still nothing happen.

actionOne()
{
$uploadObj= UploadedFile::getInstance($model, 'file');
$FileName = $uploadObj->name;
$url = 'uploads/' . $FileName ;
$uploadObj->saveAs($url,false); //it's work

$cache = Yii::$app->cache;
$cache->add('TestKey',$uploadObj,5);
// other codes below to go to 'two'
}

actionTwo()
{
$cache = Yii::$app->cache;
$uploadObj=$cache->get('TestKey');
$uploadObj->saveAs('uploads/new.file'); // this not work and no err

}

| ---------------- | ---
| Yii version | 2.0.12?
| PHP version | 7.14
| Operating system | Mac

**Comment by larryli** [comment]
This is a PHP feature. Please visit [PHP doc: POST method uploads](http://php.net/manual/en/features.file-upload.post-method.php)

> The file will be deleted from the temporary directory at the end of the request if it has not been moved away or renamed.

**Comment by KaungZawHtet** [comment]
already read it. I don't know what I have to do with it. It's about getting info of uploaded file. I have checked the info of uploaded file with var_dump($uploadedobj).
I still need more exact way.

**Comment by larryli** [comment]
@KaungZawHtet The file `$uploadObj->tempName`  be deleted after `actionOne()` return. So, you don't save the deleted file in `actionTwo()`. **This is a PHP feature.**

**Comment by KaungZawHtet** [comment]
Is there any good way that keep the uploaded file at storage within a time and delete it after that amount of time? Like cache concept that keep at storage instead of on RAM.

Suppose,
$cache = Yii::$app->cache;
$cache->add('TestKey',$uploadObj,5);
This code keep the cache on RAM for 5 seconds.After that, there will be automatically deleting. I want the way that work with storage instead of RAM.

You can call this "Automatic file deletion after a period". How can I get this.

**Comment by KaungZawHtet** [comment]
I will inform you back after reading some sources and making researches over this. For now, thx for your reply.

**Comment by larryli** [comment]
@KaungZawHtet 

```php
public function actionOne()
{
    $uploadObj = UploadedFile::getInstance($model, 'file');
    $FileName = $uploadObj->tempName;
    $data = file_get_content($FileName);
    $cache = Yii::$app->cache;
    $cache->add('TestKey', $data, 5);
}

public function actionTwo()
{
    $cache = Yii::$app->cache;
    $data = $cache->get('TestKey');
    file_put_content('uploads/new.file', $data);
}
```

**Comment by FabrizioCaldarelli** [comment]
@KaungZawHtet You could save base64 file data to session.

**Comment by KaungZawHtet** [comment]
@larryli 
wowwww!!! You made my day. Your code work!!!!!!!
Thx for your help. I now know more about how php handles uploaded files.

@FabrizioCaldarelli 
Thx for your good suggestion. I can use your idea in near future.
