### ISSUE TITLE
ActiveRecord: innerJoinWith('foo')->joinWith('foo.bar') = duplicate join on 'foo'

### ISSUE THREAD

**Issue by jurchiks** [yiisoft/yii2#16092]
Have the following relations defined (some obvious things ommitted for brevity):

```php
/** @property int $bar_id */
class Foo extends ActiveRecord {
    public function getBar() {
        return $this->hasOne(Bar::class, ['id' => 'bar_id']);
    }
}

/**
 * @property int $id
 * @property int $baz_id
 */
class Bar extends ActiveRecord {
    public function getBaz() {
        return $this->hasOne(Baz::class, ['id' => 'baz_id']);
    }
}

/** @property int $id */
class Baz extends ActiveRecord {}
```
Execute a query like this:

```php
Foo::find()
    ->innerJoinWith('bar')
    ->joinWith('bar.baz')
    ->all();
```

### What is the expected result?

```php
SELECT foo.*
FROM foo
INNER JOIN bar ON bar.id = foo.bar_id
LEFT JOIN baz ON baz.id = bar.baz_id
```

### What do you get instead?

```php
SELECT foo.*
FROM foo
INNER JOIN bar ON bar.id = foo.bar_id
LEFT JOIN bar ON bar.id = foo.bar_id <----- the problem
LEFT JOIN baz ON baz.id = bar.baz_id
```

I did not find a solution for this in the docs, nor did I find existing bugs that describe this. Perhaps this is already solved in some way that is simply not documented, but if so, then it is still an issue as this seemingly intuitive code just doesn't work.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.0.28
| Operating system | Windows 7 Enterprise

**Comment by jurchiks** [comment]
This works fine if you write `innerJoinWith('bar', 'bar.baz')` or its equivalent chained call, so there are some checks for duplicates, but they apparently consider the LEFT/INNER keyword, which they really shoudn't.
The only part that should signify uniqueness is the name (or alias) of the join, i.e. in this case it should be "bar" and "baz", no matter if they're LEFT or INNER.
If you were to write `innerJoinWith('bar aliasOne', 'bar.baz aliasTwo')` then the uniqueness should only check "aliasOne" and "aliasTwo", as that's what the database would check. You can make a hundred joins on the same table with LEFT/INNER/FULL joins, but as long as their aliases (or names, if no alias is specified) are unique, it doesn't matter.

**Comment by 4oXdev** [comment]
I have the same problem.

Yii version - 2.0.17
