### ISSUE TITLE
matchCallback in version 2.0.15 don't work

### ISSUE THREAD

**Issue by 1sildur** [yiisoft/yii2#16090]
After I update version of Yii to 2.0.15, matchCallback in Controllers don't work
On 2.0.14 it works perfect.
Code example:
`[
                        'actions' => ['image-upload', 'login-exist', 'reg-master', 'settings-master', 'yandex-wallet', 'review-comment',
                            'master-hide-dialog', 'master-message'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return Yii::$app->request->isAjax;
                        }
                    ],`
Function returns bool(false).
Do yo have the same issue or it's my bug?

 Yii version 2.0.15
 PHP version 7.0
Operating system Ubuntu 16.04

**Comment by Alex-Code** [comment]
If you just call one of those actions via ajax what do you get with `var_dump(Yii::$app->request->isAjax);`

**Comment by 1sildur** [comment]
Via GET var_dump(Yii::$app->request->isAjax) === bool(false)
Via AJAX var_dump(Yii::$app->request->isAjax) === bool(true)

**Comment by Alex-Code** [comment]
Could you show more of your controller like the behaviours method?

**Comment by 1sildur** [comment]
action example:
public function actionBlogComment()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $comment = new BlogComments();
        $comment->load(Yii::$app->request->post());

        if(empty($comment->blog) || empty($comment->content)) {
            return [
                'status' => 'error',
                'message' => 'Данные не могут быть пустыми'
            ];
        }
        $blog = Blogs::findOne(['id' => (int)$comment->blog]);
        if(!$blog) {
            return [
                'status' => 'error',
                'message' => 'Запись блога не найдена'
            ];
        }

        if ($comment->validate()) {
            if ($comment->save()) {
                return [
                    'status' => 'success',
                    'message' => $comment->content,
                    'id' => $comment->id
                ];
            } else {
                return [
                    'status' => 'error',
                    'message' => $comment->errors
                ];
            }
        } else {
            return [
                'status' => 'error',
                'message' => $comment->errors
            ];
        }
    }

**Comment by 1sildur** [comment]
Ajax controller:
`class AjaxController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    Yii::$app->response->statusCode = 403;
                    return [
                        'status' => 'error',
                        'message' => 'Доступ запрешен'
                    ];
                },
                'only' => ['image-upload', 'login-exist', 'reg-master', 'settings-master', 'yandex-wallet', 'review-comment',
                    'master-hide-dialog', 'master-message', 'get-master-messages', 'master-blog', 'image-resize', 'master-hide-blog-comment',
                    'blog-comment'],
                'rules' => [
                    [
                        'actions' => ['image-upload', 'reg-master', 'reg-master', 'settings-master', 'review-comment', 'master-hide-dialog',
                            'master-message', 'get-master-messages', 'master-blog', 'image-resize', 'master-hide-blog-comment', 'blog-comment'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return Yii::$app->request->isAjax;
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [

                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }`

**Comment by Alex-Code** [comment]
I don't think this rule will get called because of the one above.
```php
[
  'allow' => true,
  'matchCallback' => function($rule, $action) {
    return Yii::$app->request->isAjax;
  }
],
```

What are you trying to achieve with the callback checking for ajax?

**Comment by 1sildur** [comment]
It is ajax controller only for ajax request.
Ok, lets forgot about ajax... matchCallback don't work at all after I update yii on new version.
Another example:
```
[
                        'actions' => ['mypage', 'settings', 'notifications', 'messages', 'myalbums', 'myexhs', 'myblog', 'myreviews'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return !empty(Yii::$app->user->identity->access);
                        }
                    ],
```
In 2.0.14 that works. Here I check is user has access (he complete registration)

**Comment by 1sildur** [comment]
all behavior
```
public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    Yii::$app->session->setFlash('error', 'Доступ запрещен');
                    return $this->goHome();
                },
                'only' => ['registration', 'mypage', 'settings', 'notifications', 'messages', 'myalbums', 'myexhs', 'myblog', 'myreviews'],
                'rules' => [
                    [
                        'actions' => ['registration', 'mypage', 'settings', 'notifications', 'messages', 'myalbums', 'myexhs', 'myblog', 'myreviews'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                    [
                        'actions' => ['mypage', 'settings', 'notifications', 'messages', 'myalbums', 'myexhs', 'myblog', 'myreviews'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return !empty(Yii::$app->user->identity->access);
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }
```

**Comment by Alex-Code** [comment]
What is the error you get?

According to your rules a user wouldn't be able to access the `registration` page without being logged in.

**Comment by 1sildur** [comment]
There is no error. Rule with matchcallback just dont work.
Why you think so? You dont know logic of my app, and make quickly conclusions.
Look to rule with matchcallback there is no registration action. 

Are you from yii team?

**Comment by 1sildur** [comment]
"According to your rules a user wouldn't be able to access the registration page without being logged in." 
'registration' action is 2nd step of registration. 1st step in 'index' action

**Comment by 1sildur** [comment]
Lets talk about matchCallback and why it doesnt work not about app logic

**Comment by Alex-Code** [comment]
Ok, how do you know it's `matchCallback` that's not working?

**Comment by 1sildur** [comment]
If it works denyCallback should work out
```
'denyCallback' => function ($rule, $action) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    Yii::$app->response->statusCode = 403;
                    return [
                        'status' => 'error',
                        'message' => 'Доступ запрешен'
                    ];
                },
```
but it not

**Comment by 1sildur** [comment]
For this rule denyCallback work out
```
[
                        'actions' => ['image-upload', 'reg-master', 'reg-master', 'settings-master', 'review-comment', 'master-hide-dialog',
                            'master-message', 'get-master-messages', 'master-blog', 'image-resize', 'master-hide-blog-comment', 'blog-comment',
                            'exh-comment', 'master-hide-exh-comment'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
```
but for rule with matchCallback it don't

**Comment by 1sildur** [comment]
Tried to put rule with matchCallback 1st. That doesnt help
Thought that if first rule true others are skipped

**Comment by Alex-Code** [comment]
Is `access` a property of your `identityClass`?

**Comment by 1sildur** [comment]
I installed new project with 2.0.14 version matchCallback works

**Comment by 1sildur** [comment]
Is access a property of your identityClass?
yes

**Comment by 1sildur** [comment]
```
[
                        'actions' => ['mypage', 'settings', 'notifications', 'messages', 'myalbums', 'myexhs', 'myblog', 'myreviews'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return false;
                        }
                    ],
```
It's doesn't work too

**Comment by 1sildur** [comment]
```
[
                        'actions' => ['mypage', 'settings', 'notifications', 'messages', 'myalbums', 'myexhs', 'myblog', 'myreviews'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return true;
                        }
                    ],
```
And this dont work too. Problem not with return of function. Problem is ignoring rule with matchCallback

**Comment by 1sildur** [comment]
I found why I had problem. In every rule must be unique actions, that are not using in other actions.
Thank you for your help!
