### ISSUE TITLE
When it is a Ajax request, errorAction is not executed

### ISSUE THREAD

**Issue by leyestd** [yiisoft/yii2#16093]
code:   
`public function actionIndex() {
echo 3/0;
}`

When Ajax requests  ，output {"name":"Internal Server Error","message":"服务器内部错误。","code":0,"status":500}, Not my custom content

errorAction.php :
`    public function run()
    {
        Yii::$app->getResponse()->setStatusCodeByException($this->exception);

        if (Yii::$app->getRequest()->getIsAjax()) {          //   Do not execute it from here
            return $this->renderAjaxResponse();
        }

        return $this->renderHtmlResponse();
    }`

**Comment by larryli** [comment]
@leyestd 没看懂到底写的什么……

**Comment by leyestd** [comment]
@larryli   ajax请求的错误，执行不了自定义的错误处理errorAction.php

**Comment by larryli** [comment]
@leyestd 没有用默认的 `yii\web\ErrorAction`，你自己实现了一个 `ErrorAction.php` 么？

`yii\web\ErrorAction` 已经满足绝大部分场合了啊。再说，你都没贴出你的**自定义的错误处理**代码。上面的代码就是 https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorAction.php#L112

**Comment by leyestd** [comment]
@larryli 就算在原来的ErrorAction 上改，也不执行这方法public function run()，只要你是AJAX请求，你可以试下

**Comment by larryli** [comment]
@leyestd 还是没明白你要的是什么。

如果，你是想让错误信息返回为 `JSON` 数据，可以直接：

```php
    public function actionIndex()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        echo 3/0;
    }
```

就可以返回：

```json
{
  "name": "PHP Warning",
  "message": "Division by zero",
  "code": 2,
  "type": "yii\\base\\ErrorException"
}
```

**Comment by leyestd** [comment]
@larryli 我要的是发生错误，被错误处理者拦截处理啊

**Comment by larryli** [comment]
@leyestd 错误拦截是 `yii\web\ErrorHandler` 啊，不是 `yii\web\ErrorAction` 啊。

**Comment by larryli** [comment]
@leyestd 我帮你梳理以下 yii2 web 在错误处理上的逻辑：

`Yii:$app->errorHandler` 默认会配置为 `yii\web\ErrorHandler`，然后有一个可选配置 `errorAction` 一般会配置为 `site/error` 这是一个路由 `route`。

所以，通常会在 `app\controllers\SiteController` 里面使用 `actions` 方法配置 `site/error` 路由为 `yii\web\ErrorAction` 方法，然后又有一个可选配置 `view` 默认是 `views/site/error.php`。

好。那么：

- **请求是 html**，`yii\web\ErrorHandler` 就会转给 `yii\web\ErrorAction`（不是绝对，只是大多数情况）
  + **请求是 Ajax**，`yii\web\ErrorAction` 就不会给 `views/site/error.php` 处理
  + **请求不是 Ajax**，`yii\web\ErrorAction` 就会给 `views/site/error.php` 处理
- **请求不是 html**，`yii\web\ErrorHandler` 直接会处理

**Comment by leyestd** [comment]
但当非致命错误时，ErrorAction 的AJAX请求处理还是执行的
if (Yii::$app->getRequest()->getIsAjax()) {         
        return $this->renderAjaxResponse();
}

**Comment by larryli** [comment]
@leyestd 跟是不是致命错误没有任何关系。

在 `yii\base\ErrorHandler` 里面，不管 `handleException` 还是 `handleFatalError` 都会调用 `yii\web\ErrorHandler::renderException`。

还有两个 `handleHhvmError` 和 `handleError` 会直接 `throw $exception;`

**Comment by leyestd** [comment]
我自定义的
不是3/0这种,是正常的，
如 路由不对啥的

class ErrorAction extends Action
{
    /**
     * @var string the view file to be rendered. If not set, it will take the value of [[id]].
     * That means, if you name the action as "error" in "SiteController", then the view name
     * would be "error", and the corresponding view file would be "views/site/error.php".
     */
    public $view;
    /**
     * @var string the name of the error when the exception name cannot be determined.
     * Defaults to "Error".
     */
    public $defaultName;
    /**
     * @var string the message to be displayed when the exception message contains sensitive information.
     * Defaults to "An internal server error occurred.".
     */
    public $defaultMessage;

    /**
     * @var \Exception the exception object, normally is filled on [[init()]] method call.
     * @see [[findException()]] to know default way of obtaining exception.
     * @since 2.0.11
     */
    protected $exception;


    /**
     * {@inheritdoc}
     */
    public function init()
    {
        $this->exception = $this->findException();

        if ($this->defaultMessage === null) {
            $this->defaultMessage = Yii::t('yii', 'An internal server error occurred.');
        }

        if ($this->defaultName === null) {
            $this->defaultName = Yii::t('yii', 'Error');
        }
    }

    /**
     * Runs the action.
     *
     * @return string result content
     */
    public function run()
    {
        Yii::$app->getResponse()->setStatusCodeByException($this->exception);

        if (Yii::$app->getRequest()->getIsAjax()) {
            return $this->renderAjaxResponse();
        }

        return $this->renderHtmlResponse();
    }

    /**
     * Builds string that represents the exception.
     * Normally used to generate a response to AJAX request.
     * @return string
     * @since 2.0.11
     */
    protected function renderAjaxResponse()
    {
        $response = Yii::$app->response;
        $response->statusCode='200';
        $response->format = \yii\web\Response::FORMAT_JSON;
        $statusCode=$this->exception->statusCode;
        $code=$this->getExceptionCode();

        if ($statusCode=='403' || $statusCode=='404') {
            $response->data = ['code' => '0', 'message' => 'CODE:'.$statusCode . ' ERROR:您没有指定权限！'];
        }else {
            $response->data = ['code' => '0', 'message' => 'CODE:'.$code . '  ERROR:'.$this->getExceptionMessage()];
        }    
        
        if($statusCode!='403' && $statusCode!='404') {  
            $fff = Yii::$app->mailer->compose()   //和上面的from字段相对应  可以只写一个  
                        ->setTo("303650172@qq.com")
                        ->setSubject('Topcp错误提示')
                        ->setHtmlBody($this->exception)
                        ->send();
        }
        
        Yii::$app->end();
        
        return $this->getExceptionName() . ': ' . $this->getExceptionMessage();
    }

    /**
     * Renders a view that represents the exception.
     * @return string
     * @since 2.0.11
     */
    protected function renderHtmlResponse()
    {   
        $code=$this->exception->statusCode;

        if($code!='403' && $code!='404') {          
            $fff = Yii::$app->mailer->compose()   //和上面的from字段相对应  可以只写一个  
                        ->setTo("303650172@qq.com")
                        ->setSubject('Topcp错误提示')
                        ->setHtmlBody($this->exception)
                        ->send();
        }
        return $this->controller->render($this->view ?: $this->id, $this->getViewRenderParams());
    }

    /**
     * Builds array of parameters that will be passed to the view.
     * @return array
     * @since 2.0.11
     */
    protected function getViewRenderParams()
    {
        return [
            'name' => $this->getExceptionName(),
            'message' => $this->getExceptionMessage(),
            'exception' => $this->exception,
        ];
    }

    /**
     * Gets exception from the [[yii\web\ErrorHandler|ErrorHandler]] component.
     * In case there is no exception in the component, treat as the action has been invoked
     * not from error handler, but by direct route, so '404 Not Found' error will be displayed.
     * @return \Exception
     * @since 2.0.11
     */
    protected function findException()
    {
        if (($exception = Yii::$app->getErrorHandler()->exception) === null) {
            $exception = new NotFoundHttpException(Yii::t('yii', 'Page not found.'));
        }

        return $exception;
    }

    /**
     * Gets the code from the [[exception]].
     * @return mixed
     * @since 2.0.11
     */
    protected function getExceptionCode()
    {
        if ($this->exception instanceof HttpException) {
            return $this->exception->statusCode;
        }

        return $this->exception->getCode();
    }

    /**
     * Returns the exception name, followed by the code (if present).
     *
     * @return string
     * @since 2.0.11
     */
    protected function getExceptionName()
    {
        if ($this->exception instanceof Exception) {
            $name = $this->exception->getName();
        } else {
            $name = $this->defaultName;
        }

        if ($code = $this->getExceptionCode()) {
            $name .= " (#$code)";
        }

        return $name;
    }

    /**
     * Returns the [[exception]] message for [[yii\base\UserException]] only.
     * For other cases [[defaultMessage]] will be returned.
     * @return string
     * @since 2.0.11
     */
    protected function getExceptionMessage()
    {
        if ($this->exception instanceof UserException) {
            return $this->exception->getMessage();
        }

        return $this->defaultMessage;
    }

**Comment by larryli** [comment]
@leyestd 我知道是怎么回事了。。。

看我的这句话：

> 请求是 html，yii\web\ErrorHandler 就会转给 yii\web\ErrorAction（不是绝对，只是大多数情况）

问题就出在这个**（不是绝对，只是大多数情况）**。

https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L105

```php
$useErrorView = $response->format === Response::FORMAT_HTML && (!YII_DEBUG || $exception instanceof UserException);
```

这里有一个 `YII_DEBUG`，请在 `web/index.php` 设置：
```php
defined('YII_DEBUG') or define('YII_DEBUG', false);
```

**Comment by leyestd** [comment]
如果设置  
$response = Yii::$app->response;
$response->format = \yii\web\Response::FORMAT_JSON; 
就不跑到errorAction， 和这有关系

**Comment by SilverFire** [comment]
Sorry guys, I can't read Chinese. Could someone summarize what is going on, please?

**Comment by larryli** [comment]
@SilverFire Please close this issue.

@leyestd found that not handle the exception with the customized ErrorAction on json request/response.

As you know, `yii\web\ErrorHandler` will convert exception to something if `$response->format != Response::FORMAT_HTML`. So, the the customized ErrorAction written by @leyestd don't work.

**Comment by leyestd** [comment]
Yes, thank you guys
