### ISSUE TITLE
Gii string rule for TINYINT

### ISSUE THREAD

**Issue by 1sildur** [yiisoft/yii2#16096]
Маленькая неприятность, может поправите, как время будет, это не критично . 
Для поля в Mysql TINYINT Gii создает правило string вместо integer .

Большое спасибо за вашу работу над замечательным фреймворком!

Yii version 2.0.15.1
PHP version 7.0 
Operating system Ubuntu 16.04

**Comment by samdark** [comment]
Уже исправлено в master Gii. С релизом будет.
