### ISSUE TITLE
Registered js files is not cleared in error view.

### ISSUE THREAD

**Issue by sazo** [yiisoft/yii2#16101]
### What steps will reproduce the problem?
Register js in a view and throw Exception

```
<?php
/**
 * @var $this View
 */

$this->registerJsFile('/some.js');

throw new \Exception('I failed');
?>

<h1>Hallo</h1>
```

### What is the expected result?
An error page without the registered js file - when using fx. Webpack the css is packed with the js in development mode and breaks the error page css with stacktrace when Yii is in development mode.

### What do you get instead?
The js file is fetched when error page is loaded and css breaks the stacktrace view.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | Debian

**Comment by samdark** [comment]
Would you like to submit a pull request fixing it?

**Comment by sazo** [comment]
Sure just give me some days :)
