### ISSUE TITLE
DynamicModel Atribute Declaration 

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#16108]
As per documentation for the DynamicModel under [Adhoc Validation ](https://www.yiiframework.com/doc/guide/2.0/en/input-validation#ad-hoc-validation) example hows attributes being passed to the model as `new DynamicModel(compact('attribute_name_1','attribute_name_2'))` where as this does not work and does not declare the model attributes

### What steps will reproduce the problem?
```
$model = new DynamicModel(compact('finance_needed'));

print_r($model->attributes);
```
### What is the expected result?
it should display 
```
[
'finance_needed=>''
]
```
### What do you get instead?
It shows empty array as if no attributes were declared if i try to validate like this it throws the exception 

> Setting unknown property: yii\\base\\DynamicModel::finance_needed

### Additional info

If i change it to a normal array like below 

`new DynamicModel(['finance_needed']);`

then it works correctly and declare the attribute for the model

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15?
| PHP version      | 5.6.35-1+ubuntu14.04.1+deb.sury.org+1
| Operating system | ubuntu14.04.1

**Comment by Alex-Code** [comment]
The docs could be a bit misleading for anyone who just copy pastes the example.

It uses [`compact`](http://php.net/manual/en/function.compact.php) which will ignore any variables it can't find.

This won't work
```php
{
  $model = new DynamicModel(compact('finance_needed'));
  print_r($model->attributes);
}
```

While this will
```php
{
  $finance_needed = 'my value here';
  $model = new DynamicModel(compact('finance_needed'));
  print_r($model->attributes);
}
```

If you don't need to provide values during initialisation then just pass the attribute name as you have `new DynamicModel(['finance_needed']);`

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/033f2b4a13d31a5f202810eef9fad6e2c2f5e7bd

**Comment by samdark** [comment]
Thanks for reporting.
