### ISSUE TITLE
Incorrect SQL query generated by dropIndex in migration

### ISSUE THREAD

**Issue by nobuenhombre** [yiisoft/yii2#16104]
### What steps will reproduce the problem?

1) In database PortgreSQL create schema myproject
2) In schema create table mytable
3) In table create fields id:PKint and category_id:int
4) create index on field category_id with name myproject_categoryid_index

5) Write migration with next code

`$this->dropIndex(‘myproject_categoryid_index’, 'myproject.mytable');`

6) run php yii migrate

### What is the expected result?

must be generated SQL with schema
so it must be like this
`DROP INDEX myproject.myproject_categoryid_index RESTRICT`

and migration executed succesful

### What do you get instead?

`$this->dropIndex(‘myproject_categoryid_index’, 'myproject.mytable');`
this line of code generate SQL:
`DROP INDEX myproject_categoryid_index`

without schema!

and when executed get error:
` > drop index myproject_categoryid_index on myproject.mytable ...Exception: SQLSTATE[42704]: Undefined object: 7 ОШИБКА:  индекс "myproject_categoryid_index" не существует`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      | 7.2
| Operating system | Debian

**Comment by marcelodeandrade** [comment]
But in the error trace the schema exists! The problem is a nonexistent index on table. You check

**Comment by nobuenhombre** [comment]
Don't work
`$this->dropIndex(‘myproject_categoryid_index’, 'myproject.mytable');`

Work
`Yii::$app->db->createCommand(‘DROP INDEX myproject.myproject_categoryid_index RESTRICT')->execute();`

**Comment by nobuenhombre** [comment]
Because - 
$this->dropIndex(‘myproject_categoryid_index’, 'myproject.mytable');
this line of code generate SQL:
DROP INDEX myproject_categoryid_index

**Comment by nobuenhombre** [comment]
it use default 'public' schema in Postgre SQl but in my case i use custom 'myproject' schema
