### ISSUE TITLE
GUIDE RU: update inline validator doc for russian version

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#16103]
English version: https://www.yiiframework.com/doc/guide/2.0/en/input-validation
Inline Validators
```php
/**
 * @param string $attribute the attribute currently being validated
 * @param mixed $params the value of the "params" given in the rule
 * @param \yii\validators\InlineValidator $validator related InlineValidator instance.
 * This parameter is available since version 2.0.11.
 */
function ($attribute, $params, $validator)
```

Russian version: https://www.yiiframework.com/doc/guide/2.0/ru/input-validation
Встроенные Валидаторы
```php
/**
 * @param string $attribute атрибут проверяемый в настоящее время
 * @param array $params дополнительные пары имя-значение, заданное в правиле
 */
function ($attribute, $params)
```

**Comment by samdark** [comment]
You're more than welcome to send a pull request fixing it.

**Comment by SilverFire** [comment]
Would you like to help up to fix this issue by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.
