### ISSUE TITLE
Double `Url::to` in web controller's redirect method

### ISSUE THREAD

**Issue by t-kanstantsin** [yiisoft/yii2#16117]
In [\yii\web/Controller::redirect()](https://github.com/yiisoft/yii2/blob/master/framework/web/Controller.php#L203) used `Url::to()` method before calling `\yii\web/Response::redirect()`.
But in [\yii\web/Response::redirect()](https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L846) `Url::to()` used again.
I think `Url::to()` should be remove from `\yii\web/Controller::redirect()` method.

**Comment by rob006** [comment]
We did it once - it did not end well. :)

#13393 -> #13430
