### ISSUE TITLE
Problem with registerMetaTag

### ISSUE THREAD

**Issue by acebizant** [yiisoft/yii2#16121]
Hi,
there is a problem with  `registerMetaTag`
I can't use
Yii::$app->view->registerMetaTag(["name"=>"description","content"=>$description]);
When $description contains HTML entities like &hearts; `&hearts;`
becouse
`renderTagAttributes` does not have parameter to turn off double encode.

Instead of `registerMetaTag` i have to do:
in my base shop controller
Yii::$app->view->params['metadescription'] = $description;
and in layout
`<?php if (isset($this->params['metadescription'])) {?>
    <meta name="description" content="<?=html_entity_decode($this->params['metadescription'])?>" />
    <?php } ?>`

So, can you change it?
Thank You

**Comment by acebizant** [comment]
It's easy.  Google search preview. To make it more attractive for possible customers. For better conversion rating/more users.

**Comment by rob006** [comment]
This still not explain why you're passing `&hearts;` when you want a `♥`. Just pass decoded string to description.

**Comment by acebizant** [comment]
Becouse I can't. Our stupid ERP is working in WIN-1250 codepage. And WIN-1250 doesn't support a lot of UTF-8 characters. I get ? instead of ♥.

**Comment by SilverFire** [comment]
Hm, try to wrap it with `JsExpression()` :)
