### ISSUE TITLE
Two dimensional array validation

### ISSUE THREAD

**Issue by faizanktk** [yiisoft/yii2#16127]
I have this array
 passenger[0][name] = bell
 passenger[0][email] = myemail@test.com
 passenger[1][name] = carson123
 passenger[1][email] = carson##@test.com

to check name and email are valid
@samdark

**Comment by Deele** [comment]
Your question is very vague.

Have you tried using [EachValidator](https://www.yiiframework.com/doc/guide/2.0/en/tutorial-core-validators#each)?

Rule:
```
// checks if every passenger name and email is valid
[
    'passenger',
    'each',
    'rule' => [
        function ($attribute) {
            $passengerData = $this->{$attribute};
            $nameValidator = new \yii\validators\StringValidator([
                'min' => 3
            ]);
            if (!$nameValidator->validate($passengerData['name'], $error)) {
                $this->addError($attribute, $error);
            }
            $emailValidator = new \yii\validators\EmailValidator();
            if (!$emailValidator->validate($passengerData['email'], $error)) {
                $this->addError($attribute, $error);
            }
        }
    ],
],
```

Or you could make a custom validator as a class method, or you could load all the passenger data in simple Passenger model and validate with ordinary rules.

**Comment by samdark** [comment]
Won't have it out of the box. It is not that common and you can implement that via callback quite easily.
