### ISSUE TITLE
AssetBundle as Component to support events

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2#16129]
My app is currently working with custom-edited AssetBundle that is extending a Component ([rather than BaseObject](/yiisoft/yii2/blob/master/framework/web/AssetBundle.php#L30)), with multiple Events triggered and listened to achieve new type of Asset bundle functionality (EJS/Underscore/other templates as part of AssetBundle for a widget) without having to heavily extend and modify original AssetBundle.

What do you say about such a change, any performance issues that could happen, other? I don't have any unit tests, but I have production-working implementation that "does its job", without any sort of problems regarding backwards-compatibility and stability for more than a half-year already.

PS: I think, there should be more Event driven stuff in application, so this is a sort of an experimental solution to later implement in other parts of framework.

**Comment by samdark** [comment]
The AssetBundle could be used in two ways:

1. Dynamic evaluation and registration.
2. Static build with a console command.

Second case is hard to achieve if Asset Bundle will become less declarative and more dynamic.

**Comment by Deele** [comment]
Triggering events does not make it more dynamic, it just gives more opportunities for a developer to implement new stuff. How does he or she makes his job more hard is their own responsibility.

But what exactly is your point - Events are evil and should be used as little as possible?

**Comment by samdark** [comment]
Non-declarative assets could not be used via CLI command.

**Comment by SamMousa** [comment]
I am not a fan of having this in core; asset bundles to me are mostly objects that hold configuration and provides as little logic as possible.

**Comment by samdark** [comment]
Decided not to include it into the framework. You may define your own asset bundle that supports it.
