### ISSUE TITLE
Good News! MySQL Version 8.0.11 (Generally Available) Released.

### ISSUE THREAD

**Issue by frontbear** [yiisoft/yii2#16138]
MySQL 8.0 highlights include:

- MySQL Document Store
- Transactional Data Dictionary
- SQL Roles
- Default to utf8mb4
- Common Table Expressions
- Window Functions
- And much more...

![image](https://user-images.githubusercontent.com/35812002/39057626-4589a138-44ec-11e8-91b2-29b862cdb754.png)

[MySQL 8.0: Up to 2x Faster](https://www.mysql.com/products/enterprise/database/)

**Comment by samdark** [comment]
Good news but how's that related to Yii?
