### ISSUE TITLE
Conditional Validation

### ISSUE THREAD

**Issue by CavidM** [yiisoft/yii2#16137]
### What steps will reproduce the problem?
I have 2 attribute (A, B)
```
['A', 'required', 'when' => function ($model) {
                        return $model->B == null;
                    },

                'whenClient' => "function (attribute, value) {
                     return $('#form-B').val() == '';
                }"
],
```

### What is the expected result?
When fill B run validation for input A and remove error from A 

### What do you get instead?
When fill B doesn't run validation for input A

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.1.1
| Operating system | Windows 10

**Comment by buttflattery** [comment]
You are applying the validation rule to `A` not `B` and your attribute `A` will be required only if B is null/empty, you have to add rule for B too if you want it to be validated if `A` is empty
