### ISSUE TITLE
DbSession ignores SchemaCache

### ISSUE THREAD

**Issue by Eseperio** [yiisoft/yii2#16142]
### What steps will reproduce the problem?
Enable DbSession, Cache and set `enableSchemaCache`  true
### What is the expected result?
Schema queries should be executed once per each cache period
### What do you get instead?
Session table schema query is triggered on every request.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version   | 7.2 
| Operating system | OSX

**Comment by SilverFire** [comment]
Failed to reproduce.

Also, according to the code I see, it should not re-read cache every request https://github.com/yiisoft/yii2/blob/master/framework/db/Schema.php#L730

Could you create a unit test to reproduce an issue
