### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#16145]
Moved from #15710, originally authored by @turboezh
____

Hi, @SilverFire.
Another problem here now.
An `Array to string conversion` error happens at this line.
https://github.com/yiisoft/yii2/blob/033f2b4a13d31a5f202810eef9fad6e2c2f5e7bd/framework/helpers/BaseHtml.php#L943

![image](https://user-images.githubusercontent.com/1132740/38820676-342884e2-41a7-11e8-8a81-730e4f358a80.png)

**Comment by haohetao** [comment]
same problem

**Comment by samdark** [comment]
@haohetao would you please help with the code to reproduce it?

**Comment by haohetao** [comment]
when the postgresql table field is array,print the $selection is ArrayExpression.
$selection = array_map('strval', (array)$selection); trigger error

**Comment by samdark** [comment]
Would you please share some code for reproducing it and a stacktrace?

**Comment by haohetao** [comment]
@samdark 

> PHP Notice – yii\base\ErrorException
Array to string conversion
1. in D:\sites\git\award\vendor\yiisoft\yii2\helpers\BaseHtml.phpat line 1857
1848184918501851185218531854185518561857185818591860186118621863186418651866     * @param array $tagOptions the $options parameter that is passed to the [[dropDownList()]] or [[listBox()]] call.
     * This method will take out these elements, if any: "prompt", "options" and "groups". See more details
     * in [[dropDownList()]] for the explanation of these elements.
     *
     * @return string the generated list options
     */
    public static function renderSelectOptions($selection, $items, &$tagOptions = [])
    {
        if (ArrayHelper::isTraversable($selection)) {
            $selection = array_map('strval', (array)$selection);
        }
 
        $lines = [];
        $encodeSpaces = ArrayHelper::remove($tagOptions, 'encodeSpaces', false);
        $encode = ArrayHelper::remove($tagOptions, 'encode', true);
        if (isset($tagOptions['prompt'])) {
            $promptOptions = ['value' => ''];
            if (is_string($tagOptions['prompt'])) {
                $promptText = $tagOptions['prompt'];
2. yii\base\ErrorHandler::handleError(8, 'Array to string conversion', 'D:\sites\git\award\vendor\yiisof...', 1857, ...)
3. strval([4, 2])
4. in D:\sites\git\award\vendor\yiisoft\yii2\helpers\BaseHtml.php at line 1857– array_map('strval', ['yii\db\ArrayExpressiontype' => 'int4', 'yii\db\ArrayExpressionvalue' => [4, 2], 'yii\db\ArrayExpressiondimension' => 1])
5. in D:\sites\git\award\vendor\yiisoft\yii2\helpers\BaseHtml.php at line 911– yii\helpers\BaseHtml::renderSelectOptions(yii\db\ArrayExpression, [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], ['multiple' => true, 'pluginOptions' => ['tags' => true], 'class' => 'form-control', 'aria-required' => 'true', ...])
6. in D:\sites\git\award\vendor\yiisoft\yii2\helpers\BaseHtml.php at line 1834– yii\helpers\BaseHtml::listBox('Product[product_product_group_id...', yii\db\ArrayExpression, [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], '[<span class="string">'multiple'...')
7. in D:\sites\git\award\vendor\yiisoft\yii2\helpers\BaseHtml.php at line 1721– yii\helpers\BaseHtml::activeListInput('listBox', common\models\Product, 'product_product_group_id', [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], ...)
8. in D:\sites\git\award\vendor\yiisoft\yii2\helpers\BaseHtml.php at line 1667– yii\helpers\BaseHtml::activeListBox(common\models\Product, 'product_product_group_id', [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], ['multiple' => true, 'pluginOptions' => ['tags' => true], 'class' => 'form-control', 'aria-required' => 'true', ...])
9. in D:\sites\git\award\vendor\kartik-v\yii2-krajee-base\src\InputWidget.php at line 219– yii\helpers\BaseHtml::activeDropDownList(common\models\Product, 'product_product_group_id', [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], ['multiple' => true, 'pluginOptions' => ['tags' => true], 'class' => 'form-control', 'aria-required' => 'true', ...])
213214215216217218219220221222223224225     */
    protected function getInput($type, $list = false)
    {
        if ($this->hasModel()) {
            $input = 'active' . ucfirst($type);
            return $list ?
                Html::$input($this->model, $this->attribute, $this->data, $this->options) :
                Html::$input($this->model, $this->attribute, $this->options);
        }
        $input = $type;
        $checked = false;
        if ($type == 'radio' || $type == 'checkbox') {
            $checked = ArrayHelper::remove($this->options, 'checked', '');
10. in D:\sites\git\award\vendor\kartik-v\yii2-widget-select2\src\Select2.php at line 380– kartik\base\InputWidget::getInput('dropDownList', true)
374375376377378379380381382383384385386    {
        if ($this->pluginLoading) {
            $this->_loadIndicator = '<div class="kv-plugin-loading loading-' . $this->options['id'] . '">&nbsp;</div>';
            Html::addCssStyle($this->options, ['width' => '1px', 'height' => '1px', 'visibility' => 'hidden']);
        }
        Html::addCssClass($this->options, 'form-control');
        $input = $this->getInput('dropDownList', true);
        echo $this->_loadIndicator . $this->embedAddon($input);
    }
 
    /**
     * Parses the variable for boolean value and returns a right JS expression
     *
11. in D:\sites\git\award\vendor\kartik-v\yii2-widget-select2\src\Select2.php at line 259– kartik\select2\Select2::renderInput()
253254255256257258259260261262263264265                }
            }
        }
        $this->initLanguage('language', true);
        $this->renderToggleAll();
        $this->registerAssets();
        $this->renderInput();
    }
 
    /**
     * Initializes and render the toggle all button
     * @throws InvalidConfigException
     */
12. in D:\sites\git\award\vendor\kartik-v\yii2-widget-select2\src\Select2.php at line 206– kartik\select2\Select2::renderWidget()
200201202203204205206207208209210211212     * @throws ReflectionException
     * @throws InvalidConfigException
     */
    public function run()
    {
        parent::run();
        $this->renderWidget();
    }
 
    /**
     * Initializes and renders the widget
     * @throws ReflectionException
     * @throws InvalidConfigException
13. in D:\sites\git\award\vendor\yiisoft\yii2\base\Widget.php at line 140– kartik\select2\Select2::run()
14. in D:\sites\git\award\vendor\yiisoft\yii2\widgets\ActiveField.php at line 795– yii\base\Widget::widget(['hideSearch' => true, 'pluginOptions' => ['allowClear' => true], 'data' => [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], 'options' => ['multiple' => true, 'pluginOptions' => ['tags' => true], 'prompt' => '请选择产品分组', 'class' => 'form-control', ...], ...])
15. in D:\sites\git\award\vendor\kartik-v\yii2-widget-activeform\src\ActiveField.php at line 822– yii\widgets\ActiveField::widget('kartik\widgets\Select2', ['hideSearch' => true, 'pluginOptions' => ['allowClear' => true], 'data' => [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], 'options' => ['multiple' => true, 'pluginOptions' => ['tags' => true], 'prompt' => '请选择产品分组', 'class' => 'form-control', ...], ...])
816817818819820821822823824825826827828     */
    public function widget($class, $config = [])
    {
        if (property_exists($class, 'disabled') && property_exists($class, 'readonly')) {
            $this->initDisability($config);
        }
        return parent::widget($class, $config);
    }
 
    /**
     * Renders a static input (display only).
     *
     * @param array $options the tag options in terms of name-value pairs.
16. in D:\sites\git\award\common\components\form\ActiveField.php at line 91– kartik\form\ActiveField::widget('kartik\widgets\Select2', ['hideSearch' => true, 'pluginOptions' => ['allowClear' => true], 'data' => [4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], 'options' => ['multiple' => true, 'pluginOptions' => ['tags' => true], 'prompt' => '请选择产品分组']])
85868788899091929394959697            ],
            'data' => $items
        ], ['options' => $options], $widgetOptions);
        if (!isset($opt['options']['prompt'])) {
            $opt['options']['prompt']=t('ep', '请选择') . $this->model->getAttributeLabel($this->attribute);
        }
        return parent::widget(\kartik\widgets\Select2::class, $opt);
    }
 
    public function mapOrder($options = [])
    {
        $items = [];
        if ($this->autoPlaceholder) {
17. in D:\sites\git\award\backend\views\product\_update.php at line 71– common\components\form\ActiveField::select2([4 => '打折销售', 6 => '食品', 7 => '女装', 8 => '杂货', ...], ['multiple' => true, 'pluginOptions' => ['tags' => true]])
65666768697071727374757677            'multiple' => false,
            'options' => ['disabled' => false]
        ]) ?>
        <?php echo $form->field($model, 'product_brand_id')->select2(\common\models\Brand::getListData()) ?>
        <?php echo $form->field($model, 'product_product_group_id')->select2(\common\models\ProductGroup::getListData(),
        [
            'multiple' => true,
            'pluginOptions' => [
                'tags' => true,
            ]
        ]) ?>
        <?php echo $form->field($model, 'product_is_sale')->yesno(); ?>
        <?php echo $form->field($model, 'product_sale_count')->textInput() ?>
18. in D:\sites\git\award\vendor\yiisoft\yii2\base\View.php at line 348– require('D:\sites\git\award\backend\views...')
19. in D:\sites\git\award\vendor\yiisoft\yii2\base\View.php at line 257– yii\base\View::renderPhpFile('D:\sites\git\award\backend\views...', ['model' => common\models\Product])
20. in D:\sites\git\award\vendor\yiisoft\yii2\base\View.php at line 156– yii\base\View::renderFile('D:\sites\git\award\backend\views...', ['model' => common\models\Product], null)
21. in D:\sites\git\award\backend\views\product\update.php at line 20– yii\base\View::render('_update', ['model' => common\models\Product])
14151617181920212223242526$this->params['breadcrumbs'][] = $this->title;
$items = [
    [
        'label' => '<i class="glyphicon glyphicon-home"></i> ' . $this->title,
        'active' => true,
        'content' => $this->render('_update', [
            'model' => $model,
        ])
    ]
];
?>
<div class="product-update">
    <div class="product-form box box-primary">
22. in D:\sites\git\award\vendor\yiisoft\yii2\base\View.php at line 348– require('D:\sites\git\award\backend\views...')
23. in D:\sites\git\award\vendor\yiisoft\yii2\base\View.php at line 257– yii\base\View::renderPhpFile('D:\sites\git\award\backend\views...', ['model' => common\models\Product])
24. in D:\sites\git\award\vendor\yiisoft\yii2\base\View.php at line 156– yii\base\View::renderFile('D:\sites\git\award\backend\views...', ['model' => common\models\Product], backend\controllers\ProductController)
25. in D:\sites\git\award\vendor\yiisoft\yii2\base\Controller.php at line 386– yii\base\View::render('update', ['model' => common\models\Product], backend\controllers\ProductController)
26. in D:\sites\git\award\backend\controllers\ProductController.php at line 158– yii\base\Controller::render('update', ['model' => common\models\Product])
152153154155156157158159160161162163164                setFlash('error', $e->getMessage());
                Log::fail($model->name, $e->getMessage());
            }
        }
        $model->product_stock = $model->product_is_specs == 1 ? $model->product_stock : ProductStock::getStockQuantity($model->productSku[0]->productSkuProductStock->product_stock_id);
        return $this->render('update', [
            'model' => $model,
        ]);
    }
 
    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
27. backend\controllers\ProductController::actionUpdate('99')
28. in D:\sites\git\award\vendor\yiisoft\yii2\base\InlineAction.php at line 57– call_user_func_array([backend\controllers\ProductController, 'actionUpdate'], ['99'])
29. in D:\sites\git\award\vendor\yiisoft\yii2\base\Controller.php at line 157– yii\base\InlineAction::runWithParams(['id' => '99'])
30. in D:\sites\git\award\vendor\yiisoft\yii2\base\Module.php at line 528– yii\base\Controller::runAction('update', ['id' => '99'])
31. in D:\sites\git\award\vendor\yiisoft\yii2\web\Application.php at line 103– yii\base\Module::runAction('product/update', ['id' => '99'])
32. in D:\sites\git\award\vendor\yiisoft\yii2\base\Application.php at line 386– yii\web\Application::handleRequest(yii\web\Request)
33. in D:\sites\git\award\backend\web\index.php at line 17– yii\base\Application::run()
11121314151617    require __DIR__ . '/../../common/config/main.php',
    require __DIR__ . '/../../common/config/main-local.php',
    require __DIR__ . '/../config/main.php',
    require __DIR__ . '/../config/main-local.php'
);
 
(new yii\web\Application($config))->run();
$_GET = [
    'id' => '99',
];

$_COOKIE = [
    'php-console-server' => '5',
    'php-console-client' => 'eyJwaHAtY29uc29sZS1jbGllbnQiOjV9',
    'phpMyAdmin' => 'cv7lgphl3msdjtl7kjv3rnim98',
    'PHPSESSID' => '3r41ecsc3abr1jns31rag9jrv4',
    '_identity-backend' => 'b67afb633d93f2b0d2da91376b8c1133fb03566378c6337ceacaebfe413d4401a:2:{i:0;s:17:"_identity-backend";i:1;s:16:"[1,null,2592000]";}',
    '_csrf-backend' => 'b2cb7637a37384712c2b5bf97bfb772325619c6e953bfc6eef36ab5eef41a369a:2:{i:0;s:13:"_csrf-backend";i:1;s:32:"Lyb7vvTe77eh3eIGox0R7u3y7M7J6fDQ";}',
    'epmms2-backend' => '9c1ue3ef5f0ikp5gh9fqtpbbu3',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
    'w1-nodesel' => null,
];
Yii Framework
2020-01-09, 19:47:19

Microsoft-IIS/10.0

Yii Framework/2.0.31
![QQ截图20200109195050](https://user-images.githubusercontent.com/4592571/72065520-6599d200-3319-11ea-983c-1fc4f82ed215.png)
```sql
CREATE TABLE public.epmms_product (
  product_id INTEGER DEFAULT nextval('public.epmms2_product_product_id_seq'::text::regclass) NOT NULL,
  product_name VARCHAR(50) NOT NULL,
  product_summary TEXT,
  product_price NUMERIC(16,4) DEFAULT 0 NOT NULL,
  product_cost_price NUMERIC(16,4) DEFAULT 0 NOT NULL,
  product_market_price NUMERIC(16,4) DEFAULT 0,
......
  product_product_group_id INTEGER [] NOT NULL
) ;
```

**Comment by haohetao** [comment]
I fix the problem,change the line to 
$selection = array_map('strval', (array)$selection->getValue());

**Comment by nnrudakov** [comment]
In my case the same error appears when I try to manipulate array field just after find a model by `ActiveQuery::one()`. At that moment an array field is instance of `ArrayExpression` and `(array) $model->array_field` (or other array functions) gets an error.
And, yes, only `getValue()` helps now.
My code:
`$companies = \array_unique($this->companies instanceof ArrayExpression ? $this->companies->getValue() : (array) $this->companies);`

**Comment by haohetao** [comment]
@nnrudakov 
but my problem happen in the yii framework code

**Comment by nnrudakov** [comment]
@haohetao 
It doesn't matter. Because, helper works with models which has array field, as am I.

**Comment by hovhannesabovyan** [comment]
s

**Comment by hovhannesabovyan** [comment]
c
