### ISSUE TITLE
Unnamed parameters in query

### ISSUE THREAD

**Issue by vnikolay** [yiisoft/yii2#16144]
In Yii1 we could make  SQL query with unnamed parameters and pass array of values, like:
$cmd  = createCommand('SELECT * FROM `table` WHERE  `email`= ?;');
$user = $cmd->query(['email@rere.ru'])->read();

In YII2 documentation I found only about binding named parameters. Is it posible to make query with unnamed parameters and pass array of value? Thanks.

**Comment by SilverFire** [comment]
No, `Command` class in Yii 2 is no designed to work like this
