### ISSUE TITLE
logout is not working with Yii 2.1 packages

### ISSUE THREAD

**Issue by albertborsos** [yiisoft/yii2#16149]
### What steps will reproduce the problem?
yii2 basic template updated with Yii 2.1 packages. Log in, then log out.
I have tried to reproduce with `yii2-app` template too, but this template is not working yet.
 
### What is the expected result?
Send a post request to site/logout, and log out the user.

### What do you get instead?
Post request sent but the VerbFilter refused the request.
Error 405
Method Not Allowed. This URL can only handle the following request methods: post.

### Additional info
![kepernyofoto 2018-04-23 - 9 34 40](https://user-images.githubusercontent.com/7307145/39112710-a53192be-46d9-11e8-8520-a40c3571f2c2.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.1
| PHP version      | 7.2
| Operating system | yii2-docker

**Comment by Alex-Code** [comment]
I think this is a case sensitivity issue.
`VerbFilter` in 2.1 is case sensitive as of this commit https://github.com/yiisoft/yii2/commit/89c14b7dea259d6c78c7ca584969e426888faa80
The basic template checks for a lower-case `post` in [`SiteController`](https://github.com/yiisoft/yii2-app-basic/blob/master/controllers/SiteController.php#L35) while the browser will provide an upper-case `POST`

The app templates could be updated to have upper-case verbs without effecting BC

**Comment by albertborsos** [comment]
@Alex-Code thanks, you are right! Works with `POST` in the rule.
