### ISSUE TITLE
yii.activeForm.js multiple select validation problem

### ISSUE THREAD

**Issue by procin** [yiisoft/yii2#16158]
When you have a multiple dropDownList like:

`<?= $form->field($model, 'bla')->dropDownList(['test' => 'test', 'foo' => 'foo'], ['multiple' => 'multiple']) ?>`

And the field is validated (it is for example required)
If you go to the view containing the form, and another field is validated (changed of blurred) then this field is also validated.
This is due the getValue function in yii.activeForm.js
This function gets the value for the field as array like ["test", "foo"] (when both selected)
But in the function "validateAttribute" also in yii.activeForm.js, the old value and new value are compared like:

`if (this.value !== getValue($form, this)) {`

This will always match when arrays are compared in javascript, so the field will be always validated even when there are no changes.

**Comment by SilverFire** [comment]
Thank you for the reported issue. Would you like to help up to fix this issue by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.

**Comment by procin** [comment]
Thanks for your invitation! I'm reasonably new with Yii2, but very impressed by the quality of the code and the way the documentation is made.
So I want to make compliments to the complete team. Maybe after I have some more experience with Yii2, I will be of real use for the community.

**Comment by samdark** [comment]
Why waiting? Try it. We'll correct the pull request to make sure quality is fine.
