### ISSUE TITLE
Remove subtree split (yii2 / yii2-dev)

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#16160]
### What steps will reproduce the problem?

Have a project with dependency `yiisoft/yii2`.
Find a tiny bug, fix it and try to push it to your fork.

### What is the expected result?

Easy creation of a PR.

### What do you get instead?

```
This branch is 7469 commits ahead, 16992 commits behind yiisoft:master.
```

I need to use `yii2-dev` from the very beginning and switching within a project is hard (especially temporary). There should be only one repo for Yii2.

Change could be done in 2.1/3.0

**Comment by hiqsol** [comment]
As far as I understand yii team prefers to have all the framework (PHP files, documentation, tests and more) in single repository to be able to have single PR with everything.
But obviously users prefer only PHP files to be installed with composer.
Framework could be split into several repositories: one with source and other(s) with everything else.
But GitHub doesn't allow [single PR to multiple repository](https://stackoverflow.com/questions/5177566/github-single-pull-request-for-changes-to-multiple-repositories).

**Comment by schmunk42** [comment]
I think this is a matter of file/directory-size in vendor.

```
156K	build
4.0K	code-of-conduct.md
4.0K	composer.json
84K	composer.lock
24K	contrib
24K	cs
4.0K	Dockerfile
29M	docs
6.2M	framework
4.0K	LICENSE.md
4.0K	package.json
4.0K	phpunit.xml.dist
8.0K	README.md
8.0K	ROADMAP.md
4.2M	tests
```

You'd get additional >30 MB of docs and tests.

**Comment by cebe** [comment]
with .gitattributes we can exclude files when a zip file is created from the repo, so composer --prefer-source will install everything, --prefer-dist will only install non-dev files.

**Comment by samdark** [comment]
Let's have `.gitattributes`

**Comment by samdark** [comment]
@schmunk42 can you handle it?

**Comment by schmunk42** [comment]
I think this is also fixed by having `yiisoft/yii-core` now.
