### ISSUE TITLE
Yii2 defaultOrder Expression

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#16165]
### What steps will reproduce the problem?
   $result["defaultOrder"] = [
                new Expression('loco_priority DESC NULLS LAST'),
                'price'      => SORT_ASC,
            ];
### What is the expected result?
modify method like

    public function getOrders($recalculate = false)
    {
        $attributeOrders = $this->getAttributeOrders($recalculate);
        $orders = [];

        foreach ($attributeOrders as $attribute => $direction) {
            if ($attribute === 'expression') {
                if ($direction instanceof Expression) {
                    $orders[] = $direction;
                }
            } else {
                $definition = $this->attributes[$attribute];
                $columns = $definition[$direction === SORT_ASC ? 'asc' : 'desc'];
                if (is_array($columns) || $columns instanceof \Traversable) {
                    foreach ($columns as $name => $dir) {
                        $orders[$name] = $dir;
                    }
                } else {
                    $orders[] = $columns;
                }
            }
        }

        return $orders;
    }

and

            $result["defaultOrder"] = [
                'expression' => new Expression('loco_priority DESC NULLS LAST'),
                'price'      => SORT_ASC,
            ];

### What do you get instead?
alert in \yii\data\Sort::getOrders 

  $definition = $this->attributes[$attribute];

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1
| Operating system |ubuntu

**Comment by kidzen** [comment]
i have the same problem..

``php

        $searchModel = new OrderItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort->defaultOrder = ['order_id'=>SORT_DESC,'[[order_item]].id'=>SORT_ASC];
        //$dataProvider->sort->defaultOrder = ['order_id'=>SORT_DESC,'order_item.id'=>SORT_ASC];
        //$dataProvider->sort->defaultOrder = ['order_id'=>SORT_DESC,'order_item'.'id'=>SORT_ASC];
``

everything does not work.

What do you get instead?
alert in \yii\data\Sort::getOrders

$definition = $this->attributes[$attribute];
