### ISSUE TITLE
about joinWith

### ISSUE THREAD

**Issue by hey-onlybaby** [yiisoft/yii2#16166]
model:

```
class Profile extends ActiveRecord {

 ....
}

class User extends ActiveRecord {
...
    public function getProfile() {
        return $this->hasOne(Profile::className(), ['user_id' => 'user_id']);
    }
}
```

controller:

`
$users = User::find()->joinWith('profile')->limit(2)->all();
`

debug sql:

```
// The query has been fulfilled:
SELECT `shop_user`.* FROM `shop_user` LEFT JOIN `shop_profile` ON `shop_user`.`user_id` = `shop_profile`.`user_id` LIMIT 2;

// why it is executed:
SELECT * FROM `shop_profile` WHERE `user_id` IN ('10', '11');  // Excess
```

doc: https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#joining-with-relations

> Note: Even when using joinWith() or innerJoinWith() with eager loading enabled the related data will not be populated from the result of the JOIN query. So there's still an extra query for each joined relation as explained in the section on eager loading.

```
joinWith method When $eagerLoading = false

Equivalent to writing sql in the body of the loop

Generate sql:
SELECT * FROM `shop_profile` WHERE `user_id`=10;
SELECT * FROM `shop_profile` WHERE `user_id`=11; 
```

A bit confused, how to optimize?

Or honestly using the leftJoin method ？

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
This is for cross-database queries and overall ability to efficiently distribute entities without clustering.
