### ISSUE TITLE
PJAX with custom log target creates: Cannot send session cookie - headers already sent

### ISSUE THREAD

**Issue by gb5256** [yiisoft/yii2#16170]
Hello,

I do get an error when trying to log some custom messages to a custom logger for actions where I am using PJAX.

### What steps will reproduce the problem?
the view is just a grid view (gii) with PJAX enabled. 
The action to generate the grid is like this

    public function actionTable()
    {
        Yii::debug('Action Started', 'pim');
    
        $searchModel = new FieldSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
}`
Please note that in the first line I am adding a new message to the log.

### What is the expected result?
The error I get on sorting columns (which triggers the PJAX call) is this:
It should not throw an error about not beeing able to set the session.
Besides this, the code in the dbTagetPim in not executed.
The dbTagetPim class contains only the export function which is sending the log to a different table than the normal log (it bases this on the log cateogry, "pim" in the example above)

### What do you get instead?
`Unable to send log via frontend\components\DbTargetPIM: PHP Warning 'yii\base\ErrorException' with message 'session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/vendor/yiisoft/yii2/web/Response.php:414)' in /var/www/vendor/yiisoft/yii2/web/Session.php:137 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'session_start()...', '/var/www1/ve...', 137, Array) #1 /var/www/vendor/yiisoft/yii2/web/Session.php(137): session_start() #2 /var/www/vendor/yiisoft/yii2/web/Session.php(895): yii\web\Session->open() #3 /var/www/frontend/components/DbTargetPIM.php(36): yii\web\Session->offsetGet('customer_id') #4 /var/www/vendor/yiisoft/yii2/log/Target.php(133): frontend\components\DbTargetPIM->export() #5 /var/www/vendor/yiisoft/yii2/log/Dispatcher.php(189): yii\log\Target->collect(Array, true) #6 /var/www/vendor/yiisoft/yii2/log/Logger.php(177): yii\log\Dispatcher->dispatch(Array, true) #7 [internal function]: yii\log\Logger->flush(true) #8 {main}`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |7x 
| Operating system | Ubuntu 14.04

**Comment by SilverFire** [comment]
Probably duplicates https://github.com/yiisoft/yii2/issues/15786
This problem is always a developer's failure, check [other similar](https://github.com/yiisoft/yii2/issues?q=is%3Aissue+headers+already+sent+is%3Aclosed) issues to find an answer
