### ISSUE TITLE
Rar file type validation failed

### ISSUE THREAD

**Issue by esaesa** [yiisoft/yii2#16189]
### What steps will reproduce the problem?
Upload a file rar file while the validation rule is 

      [['attachmentFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'zip, rar,  pdf, jpg,  png'],

### What is the expected result?
Validation pass
### What do you get instead?

    Only files with these extensions are allowed: zip, rar, pdf, jpg, png.

### Additional info
I traced the problem and i found the location of cause as follow:

in FileValidator -> protected function validateExtension($file)

    $mimeType=application/x-rar
    $mimeTypes[] :  rar=>application/x-rar-compressed
    $extensionsByMimeType empty array

![image](https://user-images.githubusercontent.com/5354709/39401286-b08077ea-4b41-11e8-916d-d263e163008e.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.2
| Operating system | Win10

**Comment by SilverFire** [comment]
The mime type `application/x-rar` is not listed in [the known mimeTypes database](https://github.com/yiisoft/yii2/blob/master/framework/helpers/mimeTypes.php). We update that file regulary from this file http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=markup, so you may send a patch to apache project if you think there are mime types missing.

Or you can override the alias to default mimeType aliases file in your project. The file is used [in validator](https://github.com/yiisoft/yii2/blob/1e00a050d72c1f730b29bd4cd9fbc6108871e3f0/build/controllers/MimeTypeController.php#L47) to check for similar mimeTypes.
