### ISSUE TITLE
BaseFileHelper::unlink() returns wrong value

### ISSUE THREAD

**Issue by OndrejVasicek** [yiisoft/yii2#16183]
### What steps will reproduce the problem?
Use BaseFileHelper::unlink(), pass non-existent file.

### What is the expected result?
Return false.

### What do you get instead?
True.

### Additional info
Here is the simple code

```php
    public static function unlink($path)
    {
        $isWindows = DIRECTORY_SEPARATOR === '\\';

        if (!$isWindows) {
            return unlink($path);
        }

        if (is_link($path) && is_dir($path)) {
            return rmdir($path);
        }

        try {
            return unlink($path);
        } catch (ErrorException $e) {
            // last resort measure for Windows
            $lines = [];
            exec('DEL /F/Q ' . escapeshellarg($path), $lines, $deleteError);
            return $deleteError !== 0;
        }
    }
```

I'm on Win 10, so I pass the first condition. I also pass the second one and skip into the try section.
In the catch part, the $deleteError has value 1, which I suppose is an error.
And i think the last line is a bug. It returns true whenever the value is different than 0.
So my file isn't deleted and still the whole method returns true.

It should be like this
`return $deleteError == 0;`

Or my understanding of $deleteError is wrong, but then again - why it returns true when no file was deleted?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1.4
| Operating system | Win10

**Comment by SilverFire** [comment]
Thank you for the reported issue. Would you like to help up to fix this issue by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.

**Comment by OndrejVasicek** [comment]
Hi @SilverFire ,
I can easily “remove the one sign”. The problem isn't the realisation, the problem is figuring out what's happening there and if I'm actually telling the truth.
Because I can’t fully understand the line 
`exec('DEL /F/Q ' . escapeshellarg($path), $lines, $deleteError);`
Well I know in general, but I only assume it should return 0 in `$deleteError` if there is no error. That’s why I suggested the last line to be return `$deleteError == 0;`
But really, someone with better understanding of this has to made the final decision.

**Comment by samdark** [comment]
That's additional stat call. We can do it for `exec` path only.

**Comment by SilverFire** [comment]
> That's additional stat call.

It's a fallback scenario, a code in catch block. I think it will not be called to often to affect performance.

**Comment by samdark** [comment]
Yes. Agree.

**Comment by OndrejVasicek** [comment]
Excellent guys. Now what? It's your solution. It should be your PR right? Or should I do that to save your time?

**Comment by OndrejVasicek** [comment]
Ok, I'll do it then.

**Comment by OndrejVasicek** [comment]
I tried to test your solution before the commit and your idea does’n work.
Let’s assume my example – adding non-existent file to the method.
When I’m in the catch part, because the PHP’s unlink() function didn’t work, Yii tries to delete the file using exec (btw why would exec del worked and unlink didn’t?). But then your checking if the file exists somehow presumes “when it doesn’t exist, it had to be deleted”, which is false. If already non-existent file is passed, it can’t be deleted and it should return false.

**Comment by samdark** [comment]
Right. The check should be prior to deleting it.

**Comment by OndrejVasicek** [comment]
Something like this?

```
try {
    return unlink($path);
} catch (ErrorException $e) {
    // last resort measure for Windows
    if (is_file($path)) {
        $lines = [];
        exec('DEL /F/Q ' . escapeshellarg($path), $lines, $deleteError);

        return ???;
    }

    return false;
}
```
But here we are again how to check if the file was deleted. 
There is some workaround in the given link, but it's a cipher to me :)

**Comment by samdark** [comment]
The `DEL` command reports success regardless if file was deleted or not so I guess we have to return file_exists($path);

**Comment by samdark** [comment]
Better to use `file_exists` instead of `is_file` btw.

**Comment by OndrejVasicek** [comment]
Can I have a question, why is the "last resort" branch even there? I thought PHP's unlink() works on Win as well.

So what about this?
```php
try {
    return unlink($path);
} catch (ErrorException $e) {
    // last resort measure for Windows
    if (file_exists($path)) {
        $lines = [];
        exec('DEL /F/Q ' . escapeshellarg($path), $lines, $deleteError);

        return !file_exists($path);
    }

    return false;
}
```

**Comment by Thoulah** [comment]
unlink symlinks can be... hard on Windows

**Comment by samdark** [comment]
That's known issue that this is the only way to remove a symlink in non-pro versions of Windows 10

**Comment by samdark** [comment]
See #15779

**Comment by samdark** [comment]
and → && (code style)

The rest looks good to me.
