### ISSUE TITLE
The QueryInternal method in \yii\db\Command

### ISSUE THREAD

**Issue by drlibra** [yiisoft/yii2#16192]
Hello.
I have a two questions related to the `queryInternal` method in `\yii\db\Command`.
1) Is there any reason for `logQuery` to be `private`? This is the only private method in the whole class. We need to redefine it for some testing purposes and in this case we must copy whole `queryInternal` method just to be able to override `logQuery`.
2) Can the cache key generation be extracted to a separate protected method from the `queryInternal`? We have some key in the persistent cache that is changed when any migrations is applied. We need to copy whole `queryInternal` method once again to be able to add that key to the cache key generation.

**Comment by samdark** [comment]
1. What's your use case?
2. Yes.

**Comment by drlibra** [comment]
1. I can provide detailed information after holidays.

**Comment by drlibra** [comment]
1) We use the module that saves a log of a test. That log is used in a code review to make sure that there isn't any unnecessary queries on the page. In this case we add a sign to a db queries. That sign informs us about the db mode in which the query is executed: is it a slave mode or is it a master only mode. So we can see in the logs any 'SELECT' queries that occasionally is executed on the master server.
So we instead of this code in the `logQuery` method:
 
```
if ($this->db->enableLogging) {
    $rawSql = $this->getRawSql();
    Yii::info($rawSql, $category);
}
```

We write this code
 
```
if ($this->db->enableLogging) {
    $rawSql = $this->getRawSql();
    $message = $rawSql . ' '  . ($this->db->enableSlaves ? '(S)' : '(M)');
    \Yii::info($message, $category);
}
```

That is why we need to override `logQuery` method in the `\yii\db\Command()`

**Comment by samdark** [comment]
That makes sense as well.

**Comment by samdark** [comment]
Would you like to make a pull request?

**Comment by drlibra** [comment]
I hadn't time before to implement this features. Now I'm finally ready to do it.
I have two questions:
1) Should I split the changes I mentioned before into two pull requests?
2) Should that changes be placed under the section 2.0.16 development?

**Comment by samdark** [comment]
1. Yes.
2. No. 2.1.

**Comment by drlibra** [comment]
Ok. Should I refer to this issue in both pull requests?

**Comment by samdark** [comment]
Yep.

**Comment by drlibra** [comment]
Should I create a new issue for the extraction of the "getCacheKey" method (second item in the first message in this issue)? Or I should just create new pull request (with the "getCacheKey" method) that refer to this issue?

**Comment by samdark** [comment]
Create a new pull request right away.

**Comment by drlibra** [comment]
Hello.

Will this changes merged to yiisoft/db or I should create the pull request to that repository?

**Comment by samdark** [comment]
@drlibra better to create a pull request.
