### ISSUE TITLE
[website] Wrong placeholder text for the search field in Guide

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#16202]
### What steps will reproduce the problem?
1. Access the [guide section in website](https://www.yiiframework.com/doc/guide/2.0/en/start-installation);
2. Look at the search field. It says: "Search Guide..."
![captura de tela de 2018-05-01 10-50-44](https://user-images.githubusercontent.com/412490/39475168-a0fdfcaa-4d2d-11e8-927a-2654e56e110c.png)
3. Now, try to search a "Guide" section, maybe "Rest":
![captura de tela de 2018-05-01 10-53-33](https://user-images.githubusercontent.com/412490/39475250-f2f2259a-4d2d-11e8-8da1-e89fb8c68804.png)

### What is the expected result?
It should give us the *Guide* results.

### What do you get instead?
Everything (Api and others) except *Guide* results.

### What could be done?
Either change the placeholder text or really include Guide results on it.

### Additional info
Google Chrome [Versão 66.0.3359.139 (Versão oficial) 64 bits]
Ubuntu 18.04

**Comment by SilverFire** [comment]
Moved to https://github.com/yiisoft-contrib/yiiframework.com/issues/346
