### ISSUE TITLE
Inserting data into JSON column doesn't work

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#16205]
### What steps will reproduce the problem?
Insert an array into a JSON column.

### What is the expected result?
The data gets properly inserted.

### What do you get instead?
The JSON encoding happens twice, so I end up with a string that contains an encoded json object inside the database.

### Additional info
@SilverFire did you test the `JsonExpressionBuilder`? Am I doing something wrong?

I can get it to work by adding a `JSON_UNQUOTE`, which creates the folowing sql:
`CAST(JSON_UNQUOTE(:param) AS JSON)`

which works.

| Q                | A
| ---------------- | ---
| Yii version      | latest
| PHP version      | 7.2
| Operating system | N/A

**Comment by SilverFire** [comment]
@SamMousa Yes, there is a test

https://github.com/yiisoft/yii2/blob/master/tests/framework/db/mysql/ActiveRecordTest.php that confirms it work as it should. At least if there is no error in test 😨

**Comment by SilverFire** [comment]
Could you change a test to make it reproduce your case?

**Comment by SamMousa** [comment]
I am working on it, seems we were on 2.0.11 with one project  :-1: 
Sorry for wasting your time :|

**Comment by SilverFire** [comment]
Np, it happens :)
