### ISSUE TITLE
Problem with  findOne()

### ISSUE THREAD

**Issue by jobsrey** [yiisoft/yii2#16215]
### What steps will reproduce the problem?
Hallo, i have problem with my query use findOne() model.
i add CONCAT in array params like this
`$model = UserNpwp::findOne(['md5(CONCAT(name,user_npwp_id))'=>$id,'user_id'=>101]);`

in version 2.0.10 still good, why error come in version 2.0.15

![selection_026](https://user-images.githubusercontent.com/25948056/39597399-6e070efe-4f3f-11e8-8535-757aba241172.png)

### What is the expected result?
I Want to this function with query get work againt.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16-dev
| PHP version      | 5.6
| Operating system | Linux

**Comment by samdark** [comment]
Use find()->one()
