### ISSUE TITLE
ArrayHelper::map(). create indexed array if $from === null

### ISSUE THREAD

**Issue by zoryamba** [yiisoft/yii2#16221]
it would be great, if ArrayHelper::map() could generate indexed array in case if $from argument is null;

there is incoming array
```php
‌‌$array = [
  ['id' => '123', 'data' => 'abc', 'device' => 'laptop'],
  ['id' => '345', 'data' => 'def', 'device' => 'tablet'],
  ['id' => '345', 'data' => 'hgi', 'device' => 'smartphone'],
];
```

at the moment, if i run `ArrayHelper::map($array, null, 'device');` i get:
```php
[
  '' => 'smartphone',
]
```

expected result:
```php
[
  0 => 'laptop',
  1 => 'tablet',
  2 => 'smartphone',
]
```

**Comment by SilverFire** [comment]
Thank you for the suggestion. Would you like to help up to implement it by submitting a pull request? We have [contributors guide](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) that is a good starting point. If you need any tip – let us know.

**Comment by zoryamba** [comment]
ok, i'll try
i thing it could be a good idea to apply this behavior to `setValue` method and reuse it inside the `map` method, but it could break backward compatibility. what do you think?

**Comment by rob006** [comment]
> it would be great, if ArrayHelper::map() could generate indexed array in case if $from argument is null;

Why you're not using `getColumn()` in this case?

**Comment by zoryamba** [comment]
> Why you're not using getColumn() in this case?
maybe i gave not the best example. considering that `map` method could generate multidimensional arrays and customize values using callbacks, it could be very useful.

**Comment by rob006** [comment]
I still don't get it. You can use callbacks in `getColumn()` too. 

Can you give an example of `map()` *call* when this will be simpler than using `getColumn()`?

Also note that `map()` was designed to create "maps" - key-value pairs. If you remove keys, this is no longer a map.

**Comment by zoryamba** [comment]
i lacked this feature when i had to group array by field value and get groups as indexed arrays
```
[
  '123' => [
    0 => 'laptop'
  ],
  '345' => [
    0 => 'tablet',
    1 => 'smartphone',
  ],
]
```
at the moment i can't get this result with any of helper's method. or am I missing something?
maybe you are right and modifying `map` - not the best way to achieve this. but seems to be the easiest.

**Comment by alotacents** [comment]
zoryamba based on the docs you can do ArrayHelper::getColumn like this to get the results

```php
‌‌$array = [
  ['id' => '123', 'data' => 'abc', 'device' => 'laptop'],
  ['id' => '345', 'data' => 'def', 'device' => 'tablet'],
  ['id' => '345', 'data' => 'hgi', 'device' => 'smartphone'],
];

$result = ArrayHelper::getColumn($array, 'device');
// the result is: ['laptop', 'tablet', 'smartphone']

// using anonymous function
$result = ArrayHelper::getColumn($array, function ($element) {
    return ['device'=>$element['device']];
});
/* the result is
[
  0 => ['device' => 'laptop'],
  1 => ['device' => 'tablet'],
  2 => ['device' => 'smartphone'],
]
*/
```

Hope this helps you.

With regards to the map function I think we should make sure that the $from, and $to arguments are not null and are string otherwise throw an invalid argument exception

**Comment by GHopperMSK** [comment]
@samdark Do we still need this feature? I suppose the issue should be closed. @rob006 gave comprehensive explanations.
