### ISSUE TITLE
Codeception Bug. Don't clear breadcrumbs on change page.

### ISSUE THREAD

**Issue by rbtcr** [yiisoft/yii2#16222]
### What steps will reproduce the problem?

        $I->amOnPage(['site/contact']);
        $I->amOnPage(['site/contact']);
        $I->amOnPage(['site/contact']);
        $I->amOnPage(['site/about']);
        $I->amOnPage(['site/contact']);
        $I->amOnPage(['site/about']);
        $I->amOnPage(['site/contact']);

### What is the expected result?
$I->grabPageSource() 

result:
```
<ul class="breadcrumb"><li><a href="/index-test.php">Home</a></li>
php<li class="active">Contact</li>
</ul>

```

### What do you get instead?

$I->grabPageSource() 

result:
```
<ul class="breadcrumb"><li><a href="/index-test.php">Home</a></li>
<li class="active">Contact</li>
<li class="active">Contact</li>
<li class="active">Contact</li>
<li class="active">Contact</li>
<li class="active">About</li>
<li class="active">Contact</li>
<li class="active">About</li>
<li class="active">Contact</li>
</ul>
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |   7.1.9
| Operating system | Ubuntu 14

**Comment by samdark** [comment]
That looks like a bug of Codeception itself. Should be reported to https://github.com/Codeception/Codeception/issues
