### ISSUE TITLE
$("#grid-id").yiiGridView('getSelectedRows') not works correctly with checkbox header

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2#16238]
### What steps will reproduce the problem?
Having a gridview with a checkbox column. Checking the checkbox header for selecting all and dumping values to console.
### What is the expected result?
In console I should get an array with the values of all checkboxes.
### What do you get instead?
If I check the header checkbox, I receive an empty array, but if I uncheck it, I receive all values.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      |  7.2.5
| Operating system | openSUSE Tumbleweed with Firefox 59.0.2

**Comment by GHopperMSK** [comment]
Add to the end of `about.php` template:
```
<?php
$data = [
    ['id' => 1, 'name' => 'name 1', 'val' => true],
    ['id' => 2, 'name' => 'name 2', 'val' => false],
    ['id' => 3, 'name' => 'name 3', 'val' => false],
    ['id' => 4, 'name' => 'name 4', 'val' => true],
    ['id' => 5, 'name' => 'name 5', 'val' => false],
    ['id' => 6, 'name' => 'name 6', 'val' => true],
];
$provider = new ArrayDataProvider([
    'allModels' => $data,
    'pagination' => [
        'pageSize' => 5,
    ],
    'sort' => [
        'attributes' => ['id', 'name'],
    ],
]);
?>

<?= GridView::widget([
    'dataProvider' => $provider,
    'id' => 'grid-id',
    'columns' => [
        'id',
        'name',
        [
            'class' => 'yii\grid\CheckboxColumn',
            'checkboxOptions' => function ($model) {
                return ['checked' => $model['val'] ? true : false];
            }
        ]
    ],
]) ?>
```
Open `/site/about` url and see the grid widget with correct data in it.

When I run `$('#grid-id').yiiGridView('getSelectedRows');` in devtool`s console, it returns correct value every time! When I just open the page ([0, 2]), when I mark the header ([0, 1, 2, 3,  4]) or unmark it ([]).

**Comment by samdark** [comment]
@GHopperMSK do you mean the issue can't be verified?

**Comment by GHopperMSK** [comment]
> @GHopperMSK do you mean the issue can't be verified?

Exactly! But I had tested it only on FF verson "64.0 December 11, 2018"

**Comment by samdark** [comment]
Thanks.

**Comment by setrais** [comment]
If columns for 'class' => 'yii\grid\CheckboxColumn'  some
 how ( var key = $("#grid-id").yiiGridView('getSelectedRows') ) selected $key for each of them?
