### ISSUE TITLE
Migrations don't use custom 'templateFile'

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2#16236]
### What steps will reproduce the problem?

1. Set console config for 'controllerMap' section:
```php
  'controllerMap' => [
        'migrate' => [
            'class'          => 'yii\console\controllers\MigrateController',
            'migrationPath'  => '@common/migrations',
            'migrationTable' => 'migration',
            'templateFile'   => '@vendor/rugabarbo/package-name/console/views/migration.php',
        ],
    ],

```
2. Run console command:
`./yii migrate/create create_new_table <<< 'yes'`

### What is the expected result?

New migration based on `@vendor/rugabarbo/package-name/console/views/migration.php` file.

### What do you get instead?

A new migration, which looks like this:
```php
<?php

use yii\db\Migration;

/**
 * Handles the creation of table `new`.
 */
class m180506_115601_create_new_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('new', [
            'id' => $this->primaryKey(),
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('new');
    }
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.16
| Operating system |Ubuntu 16.04.4 LTS

**Comment by rustamwin** [comment]
should be `generatorTemplateFiles` [see](https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/MigrateController.php#L362)

**Comment by rugabarbo** [comment]
@rustamwin this variable isn't related to the problem

**Comment by rob006** [comment]
@rugabarbo It is - creating new table scenario has its own template and name `create_new_table` matches this scenario. You need to choose different name for migration or configure `$generatorTemplateFiles` to use your template also on creating tables.

**Comment by GHopperMSK** [comment]
Is the problem still exists?
#### My case
Create new template:
```
$ cp vendor/yiisoft/yii2/views/migration.php vendor/yiisoft/yii2/views/migration_new.php
$ echo '// custom template test' >> vendor/yiisoft/yii2/views/migration_new.php
```
Add to console config:
```
  'controllerMap' => [
        'migrate' => [
            'class'          => 'yii\console\controllers\MigrateController',
            'migrationPath'  => '@common/migrations',
            'migrationTable' => 'migration',
            'templateFile'   => '@yii/views/migration_new.php',
            'specialNamesRecognition' => false, 
        ],
    ],
```
Run script and check the result:
```
$ ./yii migrate/create test <<< 'yes'
$ cat migrations/m190123_145112_test.php | grep custom
// custom template test
```

**Comment by rugabarbo** [comment]
Use migration name `create_new_table`.

**Comment by GHopperMSK** [comment]
> Use migration name `create_new_table`.

Yes, I see now.

**Comment by GHopperMSK** [comment]
So, how should we take final decision? I agree with @rob006 - there is nothing to improve. In same time, I can easily force `templateFile` usage, if we take such decision.
I don't like over 700 opened issues, that is why I preffer to do somethin, at least with current one.

**Comment by samdark** [comment]
I'm for not touching it in 2.0.
