### ISSUE TITLE
Html5 input type

### ISSUE THREAD

**Issue by lesha724** [yiisoft/yii2#16233]
Предложение добавить в [BaseHtml](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php) дополнительные методы для [новых типов input в Html5](https://www.w3schools.com/html/html_form_input_types.asp)

Для типов:
- [color](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_color)
- [date](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date)
- [email](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_email)
- [month](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_month)
- [number](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_number)
- [range](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_range)
- [search](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_search)
- [time](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_time)
- [url](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_url)
- [week](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_week)

**Comment by pro100taA** [comment]
Есть метод input, в котором можно указать тип. Мне кажется нету смысла в добавлении новых методов в которых будет хардкод типа и вызов метода input.

**Comment by lesha724** [comment]
Есть методы для типа password, file, hidden которые вызывают статический метод input с конкретным типом. Можно сделать по аналогии.

**Comment by pro100taA** [comment]
Тоже самое, нету смысла в этих методах. Сложности в указании нужного типа пол и передачи ему параметром попросту нету.

**Comment by lesha724** [comment]
@pro100taA , не согласен. Я, к примеру, их использую.

**Comment by SilverFire** [comment]
Я не против

**Comment by lesha724** [comment]
@SilverFire, так же наверное нужно соответствующие методы добавить и в [ActiveField](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php)? Что бы они были доступны для и для ActiveForm

**Comment by dicrtarasov** [comment]
Для поддержания качества кода, не стоит плодить сущности без особой на то необходимости. Ведь дальше больше их тянуть для совместимости. Пусть эти file и password останутся.
http://www.machinelearning.ru/wiki/index.php?title=%D0%91%D1%80%D0%B8%D1%82%D0%B2%D0%B0_%D0%9E%D0%BA%D0%BA%D0%B0%D0%BC%D0%B0

**Comment by lesha724** [comment]
@dicrtarasov, Вы путаете святое с праведным. 

Это просто предложение упрощения новых компонентов ввода, которые включены  в стандарт Html5 и почти все браузеры их поддерживают. Если core team( @samdark , @SilverFire  ) тоже считают что это не нужно пускай закрывают задачу.

**Comment by dicrtarasov** [comment]
Вы путаете хочу и разумно.18:45, 1 июня 2018 г., Alexey <notifications@github.com>:@dicrtarasov, Вы путаете святое с праведным.
Это просто предложение упрощения новых компонентов ввода, которые включены  в стандарт Html5 и почти все браузеры их поддерживают. Если core team( @samdark , @SilverFire  ) тоже считают что это не нужно пускай закрывают задачу.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by lesha724** [comment]
@dicrtarasov, Как скажете. Еще раз повторюсь, я не настаиваю и не навязываю. Это просто предложение и его могут без проблем закрыть.
