### ISSUE TITLE
model() is not found

### ISSUE THREAD

**Issue by KaungZawHtet** [yiisoft/yii2#16249]
I am doing relational active record as the link:
https://www.yiiframework.com/doc/guide/1.1/en/database.arr
But it's showing 'Call to undefined method common\models\MyModel::model()'

### Additional info
| ---------------- | ---
| Yii version | 2.0.12?
| PHP version | 7.14
| Operating system | Mac

**Comment by KaungZawHtet** [comment]
Opp! I did't notice it. Thx. Btw, what is the way for 2.0 ?

**Comment by bizley** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/db-active-record
