### ISSUE TITLE
`yii/web/Session` regenerateID eats errors

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2#16248]
This line https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L302 eats the error produced when this could have been caught and logged as a warning making this issue much easier to track down.

### What steps will reproduce the problem?
    Do not give access to the PHP sessions folder
### What is the expected result?
    Don't eat errors log them as a warning instead or fix root cause of race condition
### What do you get instead?
    A PHP Fatal Error Using Craft 3 without proper permissions set for the PHP session storage

### Additional info

Craft 3.0.6

**Comment by samdark** [comment]
That's correct but it's there for a reason. You can find in via the link. If you know how to deal with it in a better way, let us know.

**Comment by HenryVolkmer** [comment]
can we close this?
