### ISSUE TITLE
Cloning objects should also clone their behaviors

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#16247]
Currently, Component::__clone() will null-out the `$_behaviors` array:

https://github.com/yiisoft/yii2/blob/3d96a45f6b2ded171c607e20b9f3e39a618ab9cb/framework/base/Component.php#L307-L312

I can see why this is better than leaving `$_behaviors` alone (those behaviors contain a reference to the original component instance), but I think it would be better if those behaviors were cloned to the new instance as well.

```php
public function __clone()
{
    $this->_events = [];
    $this-> _eventWildcards = [];

    if ($this->_behaviors !== null) {
        $behaviors = array_merge($this->_behaviors);
        $this->_behaviors = null;
        foreach ($behaviors as $name => $behavior) {
            $this->attachBehavior($name, clone $behavior);
        }
}
```

That way any property values set on the behavior will be maintained on the cloned instance, just like normal properties.

```php
$obj = new MyClassWithBehavior();
$obj->myBehaviorProperty = 'bar';
$obj2 = clone $obj;
echo $obj2->myBehaviorProperty; // should output 'bar'
```

(related: craftcms/cms#2857)

**Comment by samdark** [comment]
Yes. It's not backwards compatible and could be done in 2.1. Would you like to send a pull request?

**Comment by brandonkelly** [comment]
I figured it would be more of a 2.1 thing. Happy to submit a PR.

**Comment by brandonkelly** [comment]
@samdark ICYMI a PR was submitted for this (#16291).
