### ISSUE TITLE
官网不能注册，问下加密解决的题外话

### ISSUE THREAD

**Issue by ZeroCenter** [yiisoft/yii2#16250]
http://weistar.iteye.com/blog/1982979

上面是JAVA的，
整个百度搜索过，发现没有对应PHP的这种加密解决的。
这种 `publickey.key` 与openssl生成的不相同，这里面都是二进制的。
YII2 有可能加入这种功能吗？

真心希望YII2有这样的功能 。 或者作为个 扩展包。

[publickey.zip](https://github.com/yiisoft/yii2/files/1987114/publickey.zip)

**Comment by larryli** [comment]
`openssl_get_publickey("-----BEGIN PUBLIC KEY-----\n".chunk_split(base64_encode($publickey), 64,"\n").'-----END PUBLIC KEY-----')`

**Comment by ZeroCenter** [comment]
不是这种，全JAVA的那种，已经解决了。还是用的JAVA,最后发现是公钥 这些是16进制的，PHP没办法了。

**Comment by ZeroCenter** [comment]
本来想PHP有对应的类的，网上找了一大圈，发现没有。
