### ISSUE TITLE
DynamicModel should support check dynamic property.

### ISSUE THREAD

**Issue by vuongxuongminh** [yiisoft/yii2#16252]
### What steps will reproduce the problem?

Create an object of DynamicModel with dynamic attributes. Need to check attribute exist because it is `dynamic`, i use method `hasProperty` to check but currently it is not support.

### What is the expected result?

`hasProperty`, `canGetProperty`, `canSetProperty` methods should be return `TRUE` when check.

### What do you get instead?

`hasProperty`, `canGetProperty`, `canSetProperty` methods return `FALSE` when check.

### Additional info

Should we override  `canGetProperty`, `canSetProperty` to check an attribute dynamic exist?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      |  7.1
| Operating system | Windows 10

**Comment by samdark** [comment]
Yes. It sounds like a bug.
