### ISSUE TITLE
Class Yii not found in 2.1

### ISSUE THREAD

**Issue by exileed** [yiisoft/yii2#16259]
If you write `  'class' => yii\authclient\AuthAction::class,`, then Yii makes the first letter large
But
`\yii\authclient\AuthAction::class` - small and class found
`'yii\authclient\AuthAction::class'` as string - small and class found

### What steps will reproduce the problem?
`
class AuthController extends Controller
{

    public function actions()
    {
        return [
            'auth' => [
                'class' => yii\authclient\AuthAction::class,
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }
`

### What is the expected result?
Class found =)

### What do you get instead?
`Class Yii\authclient\AuthAction does not exist`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.1.x-dev
| PHP version      |  7.2
| Operating system | *nix

**Comment by agungsijawir** [comment]
AFAIK, Yii Auth Client is separate package.
Have you add the package on your composer.json and install it?

Here is the package:
https://github.com/yiisoft/yii2-authclient

**Comment by samdark** [comment]
How to reproduce it?
