### ISSUE TITLE
Required client validation don't work when checkboxlist items is an empty array.

### ISSUE THREAD

**Issue by Sadi01** [yiisoft/yii2#16253]
### Code of ClassificationForm Model:
```php
    public $class_id;
    public $students;

    public function rules()
    {
        return [
            [['class_id', 'students'], 'required'],
        ];
    }
    public function attributeLabels()
    {
        return [
            'class_id' => Yii::t('school', 'Classroom'),
            'students' => Yii::t('school', 'Students'),
        ];
    }
```
### Code of action:
```php
    public function actionClassification()
    {
        $model = new ClassificationForm();
        $students = UserStudent::find()->all();
        $classrooms = Classroom::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->validate()){
            // do classification
        }

        return $this->render('_classification_student', [
            'model' => $model,
            'students' => $students,
            'classrooms' => $classrooms,
        ]);
    }
```

### Code of view:
```php
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'students')->checkboxList(ArrayHelper::map($students, 'id', 'national_code')) ?>

    <?= $form->field($model, 'class_id')->dropDownList(ArrayHelper::map($classrooms, 'id', 'title'), [
        'prompt' => Yii::t('school', 'Choose a classroom...'),
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('school', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
```
### What is the expected result?
show client validation error for checkboxlist and prevent of post form.
![screenshot from 2018-05-09 17-38-51](https://user-images.githubusercontent.com/8774917/39816257-f93d39fc-53af-11e8-8a52-837bb3418eb3.png)

### What do you get instead?
not showing error (Students cannot be blank.), when $students is an **empty** array
![screenshot from 2018-05-09 17-27-57](https://user-images.githubusercontent.com/8774917/39815853-98bcf622-53ae-11e8-9870-4a4d3ec9fddb.png)
and allow to post form and then serverside validation return false and now show error message for checkboxlist.
![screenshot from 2018-05-09 17-29-26](https://user-images.githubusercontent.com/8774917/39815927-d72402fc-53ae-11e8-8261-9b7bbcfa59ea.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.4-1
| Operating system | Ubuntu 18.04 LTS

**Comment by samdark** [comment]
Would you like to fix it?

**Comment by Sadi01** [comment]
Yes of course, i'm not good in JS but i think it's coming from line **714** of **yii.activeForm.js** file (**updateInput** methode):
```javascript
if ($input.length) {
````
because of checkboxlist doesn't have any items, **if** statment is **0** and so don't update checkboxlist input.

**Comment by samdark** [comment]
Yes. Seems like so.
