### ISSUE TITLE
IDE auto-completion of module methods

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2#16261]
## What I'm using now

1. I created my **own component**:

```php
use yii\base\Component;
use yii\helpers\Inflector;

class ModuleAccessor extends Component
{
    private $_modules = [];

    public function __get($name)
    {
        if (!array_key_exists($name, $this->_modules)) {
            $moduleId = Inflector::camel2id($name);
            $this->_modules[$name] = \Yii::$app->getModule($moduleId);
        }

        return $this->_modules[$name];
    }
}
```

2. Added the following lines to the **app configuration**:

```php
   'components' => [
        'mod' => [
            'class' => \rugabarbo\packagename\components\ModuleAccessor::class,
        ],
   ]
```

3. Added the following lines to the **[autocompletion.php](https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md)**:

```php
/**
 * @property \rugabarbo\packagename\modules\Email\EmailModule $email
 */
class ModuleAccessor
{
}

/**
 * @property ModuleAccessor $mod
 */
abstract class BaseApplication extends yii\base\Application
{
}
```

4. And now I call **module methods** like this:

```php
\Yii::$app->mod->email->queue($to, $subject, $body, $params);
```

## Why?

Need IDE autocompletion for module methods. Using of the syntax `\Yii::$app->getModule('...')->` does not give such an opportunity. 

## What I suggest

Implement something similar to my **ModuleAccessor** at the kernel level ☺️

**Comment by samdark** [comment]
Can't we add same set of annotations to `Module` class to solve it? https://github.com/yiisoft/yii2/blob/master/framework/web/Application.php#L19

**Comment by rugabarbo** [comment]
@samdark how can it help?

**Comment by samdark** [comment]
The module would autocomplete standard set of components

**Comment by rugabarbo** [comment]
> The module would autocomplete standard set of components

I can not understand how this is related to auto-completion of module methods that are called by syntax 
`\Yii::$app->getModule('...')->`.

**Comment by rugabarbo** [comment]
@samdark, I'm sorry, but I still do not understand...

Suppose I have this method:

```php
class EmailModule extends Module
{
    public function queue($to, $subject, $body, $params)
    {

    }
}
```

Suppose I configured the module like this:

```php
'modules' => [
    'email' => [
        'class' => \namespace\for\EmailModule::class,
    ],
],
```

What annotations and where should I put in order to get an auto-completion of `EmailModule::queue()` method?

**Comment by samdark** [comment]
Right. That's custom module so it isn't possible on the framework level.  Your solution is fine but at application level. Won't be part of the framework. Check https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md as well.

**Comment by rugabarbo** [comment]
@samdark, I'm talking about the method of access to the methods of modules at the framework level. Syntax `\Yii::$app->getModule('...')->` does not allow to use annotations for autocompletion. See my first post, please.

**Comment by samdark** [comment]
I see nothing in your first post that could be done in the framework itself. In order to have IDE completion for custom modules you have to make custom property annotations so you need to edit the file making it pointless to have it in the framework distribution.

**Comment by rugabarbo** [comment]
😞

Don't know how to explain in other way that method `\Yii::$app->getModule('..')` doesn't allow write annotations for concrete modules...

**Comment by samdark** [comment]
Думаю, если так делать, придётся переделать много чего... Пока не вижу нормального способа. Твой — дублирование конфига, по сути. Не очень нравится.

**Comment by rugabarbo** [comment]
Но если мы не видим нормального способа, то это ведь не значит, что его нет. Нужно просто подумать. Я видел, что авторы модулей решают эту проблему разными кривыми способами. Или создают трейты с методом getModule() и соответствующим PhpDoc (примеры есть в issue #14421), или создают дополнительную локальную переменную:

```php
/** @var moduleClass $module */
$module = \Yii::$app->getModule('name');
$module->...
```

Всё это хаки, которые не очень удобны.

**Comment by uaoleg** [comment]
@rugabarbo why `MyModuleClass::getInstance()` can't be used?

**Comment by rugabarbo** [comment]
> @rugabarbo why `MyModuleClass::getInstance()` can't be used instead of `\yii::$app->getModule('MyModule')`?

Because it forces you to refer to a specific class. Modules can be interchangeable. As a result, you bind to a specific class, not a module.

**Comment by uaoleg** [comment]
@rugabarbo I'd agree with you regarding components, but not modules

**Comment by rugabarbo** [comment]
Calling modules using `Module::getInstance()` is bad practice. The framework has a method `\Yii::$app->getModule('MyModule')` for this.

Method `Module::getInstance()` is intended for internal use within a module. But not for calling a module from an application. Please read the docs: https://www.yiiframework.com/doc/guide/2.0/en/structure-modules

If you want to bind to specific classes of modules in your application, then **you can**. But the modules were designed differently.

For example, in my projects some modules are interchangeable and I cannot use specific classes of modules in application. Moreover, there are applications that require checking whether the concrete module is installed or not. And in this case, using the class name of a module is also cannot be used...

**Comment by samdark** [comment]
Theoretically could be solved via PhpStorm meta files but overall, that's not a framework job since it involves actually mapping these annotations to real classes. Won't implement it.

**Comment by uaoleg** [comment]
The easiest and universal (cross-IDE) way is to create a helper class, kinda facades in Laravel:

```
<?php

class ModuleFacade
{

    public static function integrationFacebook(): \frontend\modules\integration\modules\facebook\Module
    {
        return \yii::$app->getModule('integration-facebook');
    }

    public static function integrationTelegram(): \frontend\modules\integration\modules\telegram\Module
    {
        return \yii::$app->getModule('integration-telegram');
    }

}
```

You'll need a separate helper for each of your applications - frontend, backend, console, etc.

**Comment by rugabarbo** [comment]
For me the easiest way is workaround which I suggested at the beginning of the thread. I still use this method.
