### ISSUE TITLE
StringHelper::explode not trimming correctly with custom character_mask

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/yii2#16266]
### What steps will reproduce the problem?
```
$test = StringHelper::explode('0 0 512 640', ' ', '0', true);
var_dump($test);
```

### What is the expected result?
```
array(2) {
--
  | [0]=>
  | string(3) "512"
  | [1]=>
  | string(3) "64"
  | }
```

### What do you get instead?
```
array(4) {
--
  | [0]=>
  | string(1) "0"
  | [1]=>
  | string(1) "0"
  | [2]=>
  | string(3) "512"
  | [3]=>
  | string(3) "640"
  | }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.3
| Operating system | Debian 3.16.56-1~ui80+1

**Comment by Thoulah** [comment]
I am using this workaround for now:
`StringHelper::explode('0 0 512 640', ' ', function($value) { return trim($value, '0'); }, true);`

**Comment by samdark** [comment]
Would you like to fix it and send a pull request?

**Comment by Thoulah** [comment]
To be honest, I do not understand what the source of the problem is. If I follow https://github.com/Thoulah/yii2/blob/e4b559d720168b43c70233b08ca1a30514c7ed59/framework/helpers/BaseStringHelper.php#L269 correctly, $trim `'0'` is directly fed into the PHP `trim` function, which is then forced into `array_map`. Sounds fine, right?

**Comment by samdark** [comment]
Start with a test. Make sure it fails. Then try to fix it.
