### ISSUE TITLE
Rare bug-case: timestamp is not appending for some specific AssetBundle

### ISSUE THREAD

**Issue by MysteryDragon** [yiisoft/yii2#16268]
Well, it's funny bug which I firstly faced about 2 years ago :)
But when I just decided that "it's just not working well for now, will wait and continue use my reinvented wheel".
But second time I faced it few months ago, and finally found a reason. But for now I don't have so many time, and this was delayed again.
Now let me at least tell about that. :)

### What steps will reproduce the problem?
1. Create asset bundle without specifiyng `basePath` value (just omit that property).
2. Set something simple like:
```
'css' => [
    'css/site.css',
],
```
3. Enable `appendTimestamp` in AssetManager.

### What is the expected result?
Well, why not! Resources registered without troubles, so appending timestamp must work well.
So, it will be like `/css/site.css?v=1526200000`

### What do you get instead?
Nope, not for this case.

### Reasons

1. Here `basePath` sets as `null`:
https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L314

2. There aren't such file at system root directory (`/<filename>`) of course:
https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L322

### Proposals

IMO if `basePath`/`baseUrl` property definitions in asset bundle class are *actually* required then there must be thrown some exception when there aren't any value during initialization.
Or there may be announced some default values (`basePath` = `@webroot`, `baseUrl` = `@web`?).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | >=2.0.3, as I can see
| PHP version      | any
| Operating system | any

**Comment by samdark** [comment]
@MysteryDragon would you please check if https://github.com/yiisoft/yii2/commit/96cd8bcb687d66ae86fba01ac6a3e9c54687d616 fixed it?

**Comment by MysteryDragon** [comment]
@samdark will try tomorrow

**Comment by MysteryDragon** [comment]
@samdark it seems that it works well now!
