### ISSUE TITLE
Missed header X-Forwarded-For

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#16264]
### What steps will reproduce the problem?

```
$_SERVER['HTTP_X_REAL_IP'] return real ip
$_SERVER['HTTP_X_FORWARDED_FOR'] return real ip
var_dump(Yii::$app->request->headers) don't have X-Forwarded-For, have only x-real-ip
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15?
| PHP version      | 7
| Operating system | ubuntu

**Comment by samdark** [comment]
See if `$secureHeaders`, `$ipHeaders`, `$trustedHosts` are configured properly.

**Comment by nicdnepr** [comment]
Its all default values

**Comment by samdark** [comment]
That's why.

**Comment by nicdnepr** [comment]
Default settings is not workable? need setup manual?

**Comment by samdark** [comment]
Yes. Default settings are safe. Read phpdoc.
