### ISSUE TITLE
Switch to npm-asset/punycode

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#16260]
Currently Yii requires bower-asset/punycode, which comes bundled with 17M of tests.

Combine that with the fact that bower is deprecated I propose we switch to npm-asset/punycode. 

This should not break backward compatibility.

**Comment by samdark** [comment]
That would break it: if something depends on punycode from bower, it will install additional punycode instead of sharing it with the framework. That would cause it to fail because of multiple scripts loaded at the same time.

**Comment by rob006** [comment]
Where did you see these 17M of tests?

**Comment by SamMousa** [comment]
In my vendor folder

**Comment by samdark** [comment]
Won't make it into 2.0.
