### ISSUE TITLE
RBAC Migration Fails

### ISSUE THREAD

**Issue by afsolarte2** [yiisoft/yii2#16271]
### What steps will reproduce the problem?
1. configure AuthManager with DBManager
2. assign a non default db as the connection to run the migrations

### What is the expected result?
- the migration should run successully

### What do you get instead?
- getting this error 

> SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "auth_assignment" does not exist
The SQL being executed was: CREATE INDEX "auth_assignment_user_id_idx" ON "auth_assignment" ("user_id")'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

Checked the master branch and it seems that the problem persists

**Comment by rustamwin** [comment]
#16330
