### ISSUE TITLE
CSRF Not working properly 

### ISSUE THREAD

**Issue by DokoLink** [yiisoft/yii2#16283]
### What steps will reproduce the problem?
my site is created in yii2 and CSRF is enabled but when I copy full form including csrf token and create new html file outside server and submit form from outside of server it accepting my form.

### What is the expected result?
it should give permission issue

### What do you get instead?
it successfully accepting form not sure either I am missing any configuration or what

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  5.5.38
| Operating system | CentOS release 6.9 (Final)

**Comment by dhimancontact** [comment]
I am also facing the same issue

**Comment by samdark** [comment]
Do you copy CSRF token that is present in the form HTML?

**Comment by SamMousa** [comment]
This I'd expected behavior, the csrf token is copied thereby validating the request even when sent from another domain.

There are some cookie headers which prevents your cookie (also containing the csrf) from being sent.
This is not a security issue so there's no real need for a fix here..
