### ISSUE TITLE
JSON field not decoded when using DAO

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#16289]
### What steps will reproduce the problem?
Assume I have a table with columns `id(int)` and `jsonField(json)`.

```php
$db->createCommand()->insert('someTable', ['id' => 1, 'jsonField' => ['a' => 'b']])->execute();
$retrieved = (new Query())
    ->where(['id' => 1])
    ->select('jsonField')
    ->from('someTable')
    ->scalar();
```

### What is the expected result?
```php
$retrieved === ['a' => 'b'];
```
### What do you get instead?
```php
$retrieved === "['a' => 'b']";
```

### Additional info
This issue occurs because `phpTypeCast` is not called anywhere in the `Query` class. For AR this works because `phpTypeCast` is called in the `populateRecord` function.
To me it seems that the query layer should do type casting not the AR layer.

| Q                | A
| ---------------- | ---
| Yii version      | dev-master (this time I checked my composer.lock)
| PHP version      | 7.2
| Operating system | alpine

**Comment by cebe** [comment]
The query layer has no information about column types. In AR we map a table to an object so we know the types of properties. In query layer we have no information about which table a selected column came from so we have no way to convert it.
