### ISSUE TITLE
FileInput Active Form value by hidden input is empty

### ISSUE THREAD

**Issue by vitalykhy** [yiisoft/yii2#16304]
Hello, I have ActiveForm FileInput:
```
$form->field($model, 'payed_bill')->fileInput();
```
Generated HTML is:
```
<div class="form-group field-bill-payed_bill">
   <label class="control-label" for="bill-payed_bill">Оплаченный счет</label>
   <input type="hidden" name="Bill[payed_bill]" value=""><input type="file" id="bill-payed_bill" name="Bill[payed_bill]" value="assets/orders/8372c0a71fd6495ba1005259e6b5e42b.jpg">
   <div class="help-block"></div>
</div>
```
In this case, when I update the model, the value form **payed_bill** field was removed, if I do not attach a picture. I think is it wrong.

It will be fixed if from this line delete value key https://github.com/yiisoft/yii2/blob/b7b9c8ba40d65ec7c745ee639a8a6eb96e7aea75/framework/helpers/BaseHtml.php#L1355

After this, if do not attach image and update model field will be saved, but if attch image (or file) - field will be updated.

**Comment by Thoulah** [comment]
- Why are you trying to load files from fileinput from asset path? It's user input
- When no file is selected, the value is empty. Seems normal to me
- When a file is selected, it is often displayed as c:\fakepath\file.ext, which is not reusable.

**Comment by vitalykhy** [comment]
> When no file is selected, the value is empty. Seems normal to me

Example: You have an order with a bill. You need to update its status and change the manager. You go to the editing model and change the fields. Also, when editing the model, you can attach a new pdf bill. But now you do not need it. (new bill) And if you update the model without attaching an bill, bill will be lost.

> When a file is selected, it is often displayed as c:\fakepath\file.ext. AFAIK the server only receives the file itself and the file.ext part. This is not enough to fill value in any usable way and thus it is cleared.

I show HTML, that generated when I see model's update page with attached bill.

**Comment by Thoulah** [comment]
I don't think that is how fileInput is supposed to work. See https://yii2-cookbook.readthedocs.io/forms-uploading-files/: a seperate field is used to handle file upload.

**Comment by vitalykhy** [comment]
All right. Try to do the algorithm that I described above. If you do not lose the file that was loaded in the first iteration, then please explain to me what I'm doing wrong. The algorithm is as follows:
1) create a model with a text field and a file
2) fill the text field and attach the file. Save model.
3) go back to the model. Change the text box and save model
4) go back into the model again. Now you should see that the file is no longer attached.

That is, the file can be attached with any changing of the model, but if it is not done at each, it will be lost.

**Comment by Thoulah** [comment]
I understand what you are *trying* to do, but that is not what your code will do.

When you submit the form the second time, the browser *might* try to upload `assets/orders/8372c0a71fd6495ba1005259e6b5e42b.jpg`, which does not exist (from the browser upload point of view). Therefor `UploadedFile::getInstance` correctly sets the value to zero, as no valid file is uploaded.

**Comment by samdark** [comment]
It depends on your form processing code.
