### ISSUE TITLE
Codeception submitForm doesn't respect name fields when integers or "integers"

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#16308]
### What steps will reproduce the problem?
```php
$I->submitForm('#submit-form', [
     'person' => 5,
     5 => 'Yes',
     '6' => 'No',
]); 
```
### What is the expected result?
That the submitted array will maintain key value index. Especially if the index is a string, but contains integers.
### What do you get instead?
Anything that is an integer or integer represented as a string is replaced and re-indexed from 0. Using the above post, the submitted data is:
```
{...,"0":"","person":5,"1":"Yes","2":"No"}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.1
| Operating system | Windows 7

**Comment by samdark** [comment]
I think it's a general bug of Codeception. Please report to https://github.com/Codeception/Codeception/

**Comment by jonny7** [comment]
Thanks Sam will do
