### ISSUE TITLE
Is it should be possible to use Dependency Injection on Active Record classes?

### ISSUE THREAD

**Issue by mubat** [yiisoft/yii2#16306]
_Question related to Yii2 logic._
According to application configuration for Dependency Injection at [manual](https://www.yiiframework.com/doc/guide/2.0/ru/concept-configurations#using-configurations). I can write next code and `UserHelper` class should handle events:
```php
//main.php
'container' => [
        'definitions' => [
            User::class => [
                'on ' . User::EVENT_BEFORE_INSERT => [UserHelper::class, 'eventHandler'],
                'on ' . User::EVENT_BEFORE_UPDATE => [UserHelper::class, 'eventHandler'],
                'on ' . User::EVENT_BEFORE_DELETE => [UserHelper::class, 'eventHandler'],
            ]
        ],
    ],
```
But it not work because ActiveRecord classes creates at `BaseActiveRecord::instantiate()` method using simple creation.
__Can I use Dependency Injection for ActiveRecord classes or I should register event handlers at `__construct()` method?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12.2
| PHP version      | PHP Version 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
| Operating system | Linux Mint 18.3

**Comment by samdark** [comment]
You can if you'll override `instantiate()`. By default you can't cause it trashes performance significantly.
