### ISSUE TITLE
yiiActiveForm('resetForm') not working

### ISSUE THREAD

**Issue by SnitramDev** [yiisoft/yii2#16303]
### What steps will reproduce the problem?
$('#my-form').yiiActiveForm('resetForm'); -> the form isn't reset.

$('#my-form').data('yiiActiveForm'); -> shows the following info in web-browser's console (so the reference to the form is OK):
{settings: {…}, attributes: Array(1), submitting: false, validated: false, options: {…}}

### What is the expected result?
Reset the form (clear all the info).

### What do you get instead?
Form isn't reset.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.? 2.0.15.1
| PHP version      | 7.0
| Operating system | Linux Ubuntu

**Comment by Thoulah** [comment]
It clears validation data, not all entered data
