### ISSUE TITLE
targetAttribute in Exist validator does not translate to SQL syntax

### ISSUE THREAD

**Issue by VirtualRJ** [yiisoft/yii2#16307]
### What steps will reproduce the problem?
Have an exist rule in a Model with a filter:

```php
            [
                'FirstNumber', 'exist',
                'targetClass' => FirstObject::class,
                'targetAttribute' => '{{' . FirstObject::tableName() . '}}.[[number]]',
                'filter' => function ($query) {
                    /** @var ActiveQuery $query */
                    $query->joinWith('secondobject')
                        ->andWhere([
                            '{{' . SecondObject::tableName() . '}}.[[parent_id]]' => $this->parentId,
                            '{{' . SecondObject::tableName() . '}}.[[number]]' => $this->SecondObjectNumber,
                        ]);
                },
            ],
```

### What is the expected result?
The [[ and ]] in targetAttribute to be transformed to the correct SQL syntax. In this case for MySQL ``` `firstObject`.`number` ```.

### What do you get instead?
``` ... WHERE (`firstObject`.[[`number`]]='0000101') ... ```

and the following exception:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near [[\`number\`]]='0000101')

### Additional info

This worked in 2.0.12 and doesn't work in 2.0.15.1 anymore.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.0
| Operating system | Ubuntu

**Comment by cebe** [comment]
The targetAttribute is an attribute name of the targetClass, not an SQL expression. Why do you specify it in this way and not simply as the attribute name?

**Comment by cebe** [comment]
there have been some changes so that the validator ambiguates columns itself now. I think this can be closed.
