### ISSUE TITLE
[enh] Add autoIncrement() in Migrations to allow fine grained data type in PK

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#16320]
### What steps will reproduce the problem?
[This stackoverflow question](https://stackoverflow.com/questions/34117058/how-do-i-implement-auto-increment-in-a-yii2-migration-using-mysql?rq=1) demonstrates the exact problem.

In a nutshell: `primaryKey()` is the only way to set an auto increment field that is db agnostic but it is ever an `int` data type. Sometimes whe need it to be either `smallint` or `bigint`. Having a `autoIncrement()` would make it possible (`AUTO_INCREMENT` for MySQL, `IDENTITY(1,1)` for MSSQL, and so on);

**Comment by slinstj** [comment]
I just saw that there is already a `bigPrimaryKey()`. Just lacking a `smallPrimaryKey()`.

**Comment by samdark** [comment]
I'm OK adding it.

**Comment by slinstj** [comment]
I am working on it. :+1:

**Comment by slinstj** [comment]
The syntax you mentioned is pretty good really. I just did not see how would it cover primary keys. Would it accept this?

```php
$this->createTable('tableName', [
    'id' => $this->smallInt()->primaryKey(), // would it be this or something else?
    'name' => $this->string()->index('indexName'),
    'topic_id' => $this->integer()->foreignKey('indexName', 'referencedTable', 'referencedColumn'),
]);
```
Thanx.

**Comment by slinstj** [comment]
Sorry, I just saw #11638 right now. I had not perceived that the issue and the comment were in separated issues. Thnx.
