### ISSUE TITLE
POST Method not Allowed via postman until i call protected function verbs()

### ISSUE THREAD

**Issue by sudhir600** [yiisoft/yii2#16338]
Hi team, 
I am creating API using yii2 (basic).
when i tried to call any post method, i am getting error

> "Method Not Allowed. This URL can only handle the following request methods: GET, HEAD.",

after googling few article, I found a way to solve this.

```
protected function verbs() {
	   $verbs = parent::verbs();
	    $verbs =  [
			'index' => ['GET', 'POST', 'HEAD'],
			'view' => ['GET', 'HEAD'],
			'create' => ['POST'],
			'update' => ['PUT', 'PATCH']
		];
	   return $verbs;
}
```

**Now Problem is, I have to paste this code in every controller. (which is not ideal and i don't want)
So is there any way to set as global?**

**Comment by rustamwin** [comment]
what your request action

**Comment by Auramel** [comment]
Show your controller code

**Comment by sudhir600** [comment]
@rustamwin @Auramel 
My request action is POST (sending request vi POSTMAN)
Here is controller code.

```
<?php

namespace app\controllers;

use Yii;
use yii\base\Model;
use yii\rest\ActiveController;

class SessionController extends ActiveController {
	
	public $modelClass = 'app\models\Session';
      
       //when i add verb function, its work but don't want to add everytime in each controller. 
	/* 
	protected function verbs() {
	   $verbs = parent::verbs();
	    $verbs =  [
			'index' => ['GET', 'POST', 'HEAD'],
			'view' => ['GET', 'HEAD'],
			'create' => ['POST'],
			'update' => ['PUT', 'PATCH'],
			'delete' => ['DELETE'],
		];
	   return $verbs;
	} 
	*/
	public function init() {
    }
	public function actions() {
	}

	public function actionIndex($params = array()) {
		if($_SERVER['REQUEST_METHOD'] == 'POST'){
			// logic goes here
		}
	}
}
?>
```

And here is config/web.php

```
'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => true,
            'rules' => [
                [
				'class' => 'yii\rest\UrlRule', 
				'controller' => ['users', 'todo'],
				],
				'<alias:\w+>' => 'site/<alias>',
               ],
        ],

```

**Comment by rustamwin** [comment]
@sudhir600 add `session` controller to urlManager rules

**Comment by sudhir600** [comment]
I added but same error. 

'controller' => ['users', 'todo', 'session'],

**Comment by rustamwin** [comment]
so add verbs to controller
`protected function verbs() {
	   $verbs = parent::verbs();
	    $verbs['index'] =  ['GET', 'POST', 'HEAD'];
	   return $verbs;
	} `

**Comment by sudhir600** [comment]
this is already i am doing since i asked this question. 
What am i trying to get it, why i need to write verns () function in each controller?
is there any way to write at once and overright for all controller?

**Comment by Auramel** [comment]
Okay, I look into \yii\rest\ActiveController::verbs(); Here is:
```php
    /**
     * {@inheritdoc}
     */
    protected function verbs()
    {
        return [
            'index' => ['GET', 'HEAD'],
            'view' => ['GET', 'HEAD'],
            'create' => ['POST'],
            'update' => ['PUT', 'PATCH'],
            'delete' => ['DELETE'],
        ];
    }
```
So, POST method allowed by default only for `create` action. If you want add your METHOD - you should overwrite verbs() method or something else (I didn't see the documentation). 
If you don't want to write it each controller I offer create BaseActiveController with your verbs() and extends from it

**Comment by Auramel** [comment]
Maybe, someone offer a better solution...

**Comment by rustamwin** [comment]
> What am i trying to get it, why i need to write verns () function in each controller?
is there any way to write at once and overright for all controller?

create a base controller and extend other controllers

**Comment by sudhir600** [comment]
Thanks @rustamwin. your suggestiins worked (By using base controller)

Those, who are facing the same issue, use this code.
in components folder, create a file "**baseController.php**" and paste below code.

```
<?php
namespace app\components;

class BaseController extends \yii\rest\ActiveController{
	public $modelClass = ''; // no single table dependent
    
	public function init(){
        parent::init();
    }

	public function actions() {
	}
	
	protected function verbs() {
	   $verbs = parent::verbs();
	    $verbs =  [
			'index' => ['GET', 'POST', 'HEAD'],
			'view' => ['GET', 'HEAD'],
			'create' => ['POST'],
			'update' => ['PUT', 'PATCH'],
			'anyOtherAction' => ['DELETE'],
		];
	   return $verbs;
	}
}
?>
```

in **userController** (or every controller)
```
class SessionController extends \app\components\BaseController {
  // your code goes here
}
```
