### ISSUE TITLE
incorrect console Table widget render at PHPStorm script run tab

### ISSUE THREAD

**Issue by igorveremsky** [yiisoft/yii2#16339]
### What steps will reproduce the problem?
Add yii script to run/debug configuration in PHPStorm
![screenshot_287](https://user-images.githubusercontent.com/13087365/40722879-2deb1e4a-6426-11e8-9604-df4f889264e8.png)
and than run it
![screenshot_288](https://user-images.githubusercontent.com/13087365/40722904-40365b82-6426-11e8-8735-0b7e6a09221d.png)

### What is the expected result?
![screenshot_286](https://user-images.githubusercontent.com/13087365/40722749-d5384ce6-6425-11e8-9159-97c29cf85734.png)

### What do you get instead?
![screenshot_285](https://user-images.githubusercontent.com/13087365/40722742-c9124e44-6425-11e8-804e-3f79cb489ed9.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.2
| PHP version      |  7.1.9
| PHPStorm | 2018.1.3
| Operating system | Windows 10

**Comment by alexeevdv** [comment]
It is not an Yii issue. It is PhpStorm's `Run` tab terminal configuration issue. On windows it is tied to 120 symbols.
This issue can be closed
