### ISSUE TITLE
`jsonSerialize` not called on dynamic field

### ISSUE THREAD

**Issue by RdeWilde** [yiisoft/yii2#16334]
### What steps will reproduce the problem?
Psuedo
```php
class MyModel extends ActiveRecord {
    // ...

   public function fields() {
      $fields = parent::fields();
      $fields['price'] = function() {
         return $this->getPrice();
      };
      return $fields;
   }

   public function getPrice() {
      return new Price(10.00);
   }
}

class Price implements JsonSerializable {
   public $amount;
   protected $currency;

   public function __construct($amount, $currency = 'EUR') {
       $this->amount = $amount;
       $this->currency = $currency;
   }

   public function jsonSerialize() {
     $values = [
         'amount'	  => $this->amount,
         'currency'      => $this->currency
      ];
      if ($this->currency !== 'USD') {
          $values['usd_amount']  = Currency::convert($this, 'USD'); // Creates another Price in USD
      }
      return $values;
   }
}

// ..
class MyJsonController extends Rest {
   public function actionTest() {
     return new MyModel();
   }
}
```

### What is the expected result?
```json
{
  "price": {
    "amount": 10.00,
    "currency": "EUR",
    "usd_amount": {
       "amount": 8.00,
       "currency": "USD"
    }
  }
}
```

### What do you get instead?
```json
{
  "price": {
    "amount": 10.00
  }
}
```

### Additional info
The function `jsonSerialize` (as implemented by `JsonSerializable`) isn't being called on the dynamic field `price`. Instead just the public properties are being outputted/serialized.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.0
| Operating system | Ubuntu

**Comment by kamarton** [comment]
@samdark For example, if `Model` and `JsonSerializable` are both, should the output of `JsonSerializable` be considered?

**Comment by samdark** [comment]
Yes. It should be preferred.

**Comment by patacca** [comment]
I think the issue is still present.
In this particular case `Serializer::serialize(MyModel)` is called and since `ActiveRecord` implements `Arrayable` then `Serializer::serializeModel(MyModel)` is called.
At this point the model is turned into an array without serialiazing anything. In fact it is returned `$model->toArray($fields, $expand)` and the only implementation of `toArray` is inside `ArrayableTrait` and inside `ArrayableTrait::toArray` is never called serialize

**Comment by samdark** [comment]
@germanow would you please check it?

**Comment by germanow** [comment]
@samdark yes, issue is still present. I hope my new pr should finally fix it.

**Comment by germanow** [comment]
@samdark Should we also add this fix to the `yii\helpers\BaseJson`?
