### ISSUE TITLE
`yii\filters\AccessRule::matchIP()` should support `IpValidator`

### ISSUE THREAD

**Issue by vuongxuongminh** [yiisoft/yii2#16335]
### What steps will reproduce the problem?

Config ranges ip to `ips` of `AccessRule`.

### What is the expected result?

`yii\filters\AccessRule::matchIP()` return `TRUE` if guest IP in ranges.

### What do you get instead?

`yii\filters\AccessRule::matchIP()` return `FALSE` when guest IP in ranges.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.x
| Operating system | Windows

**Comment by rob006** [comment]
This issue is about using ranges (like `192.168.0.0/24`), not specific IP.

**Comment by mgrechanik** [comment]
@rob006, I see no mentioning of such syntax (192.168.0.0/24) in the documentation. Did you mean using wildcard * ?

**Comment by rob006** [comment]
It is documented in `IpValidator` - https://www.yiiframework.com/doc/api/2.0/yii-validators-ipvalidator

This issue is about to supporting the same syntax in `AccessRule`.
