### ISSUE TITLE
API search on yiiframework.com gives incomplete results

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#16341]
I'm very sure that this is the wrong place to report this but I could not find a better place.

The search box on the [API documentation page](https://www.yiiframework.com/doc/api/2.0) gives pretty poor results. For example search for `baseUrl`:

![yii_api_search](https://user-images.githubusercontent.com/675062/40767660-712e0efa-64b3-11e8-90fa-0d212faa4667.png)

Where is Theme, Request and UrlManager? They all have a baseUrl property.

**Comment by rob006** [comment]
See https://github.com/yiisoft-contrib/yiiframework.com/issues/337

**Comment by mikehaertl** [comment]
@rob006 I'm sorry, but I fail to see how this is related to my issue report here. I didn't enter whitespace. And I would assume that the API search on the website should return *all* results.

**Comment by rob006** [comment]
@mikehaertl This is explained in second (!) comment in linked issue - you need to prefix search phrase with dot to search methods or properties. And yes, it is unintuitive, I hope it will be fixed in https://github.com/yiisoft-contrib/yiiframework.com/issues/337
