### ISSUE TITLE
odd check in yii\filters\AccessRule::matchRole

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#16349]
in yii\filters\AccessRule::matchRole

```php
if (!isset($roleParams)) {
    $roleParams = $this->roleParams instanceof Closure ? call_user_func($this->roleParams, $this) : $this->roleParams;
}
```
!isset($roleParams) will is always true

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1

**Comment by rob006** [comment]
This check is inside of `foreach` - it will be `true` only for first iteration which reach this statement, but finally it may happen multiple times.

https://github.com/yiisoft/yii2/blob/292a545642eaa947a5169d7c6366a6dca486d571/framework/filters/AccessRule.php#L231-L248
