### ISSUE TITLE
No middlewares in yii2

### ISSUE THREAD

**Issue by Synida** [yiisoft/yii2#16343]
I'm sorry that I'm using this issue like a "forum", but why there are no middlewares in yii2?
When I wanna integrate a global filter then the correct solution would be to create a middleware for that. I'm worked with that in Laravel and that was pretty cool, easy to use and clean. Now I see these "filters" in yii, but if I wanna use a global one then I need a parent controller at least for every one of them :(((

**Comment by samdark** [comment]
There are in 2.1 branch (not yet released).

**Comment by Synida** [comment]
Oh, that's great!
I cant wait :)
