### ISSUE TITLE
ActiveRecord delete()/beforeDelete() 

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#16356]
Here <https://www.yiiframework.com/doc/api/2.0/yii-db-activerecord#delete()-detail> is stated that:

> This method performs the following steps in order:
>
> 1. call beforeDelete(). **If the method returns false, it will skip the rest of the steps;**
> 2. delete the record from the database;
> 3. call afterDelete().

but that's not true because the code in BaseActiveRecord.php

    public function beforeDelete()
    {
        $event = new ModelEvent();
        $this->trigger(self::EVENT_BEFORE_DELETE, $event);

        return $event->isValid;
    }

returns **$event->isValid**

In order to achieve whats stated, in beforeDelete behavior I should set `$event->isValid = false` but that does not seem ok. Currently it is irrelevant what the attached beforeDelete behavior returns.

**Comment by mgrechanik** [comment]
>  I should set $event->isValid = false but that does not seem ok. 

Using event object to pass data among event listeners is a common way to do things in this framework.

It is all over the framework, see [Model::beforeValidate](https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L382) for example

**Comment by rob006** [comment]
> In order to achieve whats stated, in beforeDelete behavior /.../

This documentation is about `ActiveRecord` class, not its behaviors. If you override `beforeDelete()` method in model and return `false`, record will not be deleted - exactly as it was explained in documentation. 

For behaviors there is a event documentation:
https://www.yiiframework.com/doc/api/2.0/yii-db-baseactiverecord#EVENT_BEFORE_DELETE-detail
