### ISSUE TITLE
grid\CheckboxColumn::$content is never called

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#16350]
### What steps will reproduce the problem?
Create a `CheckboxColumn` in a grid view and set its propertie `content` to a callable function returning, for example, a string.

### What is the expected result?
The string should be in the cell content.

### What do you get instead?
`content` return is ignored.

### Additional info
`CheckboxColumn::renderDataCellContent()` overrides the `Column::renderDataCellContent()` but, in the `CheckboxColumn`, `$this->content` is never called totally ignoring its return.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.17

**Comment by slinstj** [comment]
Right now I need to make the checkboxes compatible to Tabular Inputs but either `name` property set in `checkboxOptions` and `content` are being ignored. If I could use `content` I could make the inputs the way I need.

**Comment by lesha724** [comment]
Duplicate [#15798](https://github.com/yiisoft/yii2/issues/15798)
