### ISSUE TITLE
Classes with name object are forbidden in PHP 7.2

### ISSUE THREAD

**Issue by jianwubayiba** [yiisoft/yii2#16352]
### What steps will reproduce the problem?
throw fatal error

### What is the expected result?
ok

### What do you get instead?
change class Object to Obj

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.4
| PHP version      | 7.2.4
| Operating system | Centos7

**Comment by rustamwin** [comment]
class `Object` already changed to `BaseObject` in version 2.0.13, update your Yii version
