### ISSUE TITLE
./yii message/extract

### ISSUE THREAD

**Issue by Libertaro** [yiisoft/yii2#16366]
Hello. Im trying to extract translations to dictionary but when i call this command process freezes in console. Can you give me an advice how can I check what trouble is in?

I've made extract on this project about month ago and it worked properly. But now I meet this problem. May it be because of large amount of translations?

**Comment by samdark** [comment]
Try deleting 50% of the source code and see if it works. If yes - that's something in the part you've deleted. If no - that's something in the part that's left. Repeat that till you'll find what causes it to fail. When culprit is there, post it here so we can reproduce it.

**Comment by Libertaro** [comment]
@samdark i noticed that when i comment line "'sourcePath' => '@app'," in messages.php script of translation is running, otherwise it doesn't. But when this line is commented messages extract only in yii.php file

**Comment by Libertaro** [comment]
You can close issue, I've found problem. I added to except /web folder and now everything ok. But I don't understand why((
