### ISSUE TITLE
Добавление опции автоматической фильтрации

### ISSUE THREAD

**Issue by s1lver** [yiisoft/yii2#16365]
Доброго времени суток!

Столкнулся с проблемой перехвата события `change.yiiGridView keydown.yiiGridView` у `yiiGridView`.
Дело в том, что IE и Яндекс Браузер не корректно обрабатывают их и просто не реагируют.

Пример.
Мне в гриде не нужен функционал при котором каждое изменение фильтра ведет к отправке запроса. Хочется чтобы отправка запроса была по кнопке. Проставил все фильтры, нажал на кнопку - фильтры применились.

## Вариант1.
Используем JQuery чтобы просто отменить события.

```js
$(window).on('load', function () {
	$(document).off('change.yiiGridView keydown.yiiGridView', '#grid_id-filters input, #grid_id-filters select'
	);
	$('#grid_id-filter-control').on('click touch', function () {
		$("#grid_id").yiiGridView("applyFilter");
	});
});
```
Этот пример хорошо работает в FireFox и Chrome, IE 11 и Яндекс браузер не реагируют на него.

## Вариант2.
Используем возможности yiiGridView

```js
$(window).on('load', function () {
	jQuery('#grid_id').yiiGridView('destroy');

	$('#grid_id-filter-control').on('click touch', function () {
		$("#grid_id").yiiGridView("init", {"filterUrl":"\/index","filterSelector":"#grid_id-filters input, #grid_id-filters select"});
		$("#grid_id").yiiGridView("applyFilter");
	});
});
```
Аналогичная история. Этот пример хорошо работает в FireFox и Chrome, IE 11 и Яндекс браузер не реагируют на него.

## Вариант3.
Поскольку в гриде нет отдельной опции которая не даст произвести вызов JS
```php 
 $view->registerJs("jQuery('#$id').yiiGridView($options);");
```
, то можно написать свой виджет и переопределить метод run(). Вариант не очень хороший, но работает 100%. Дает ожидаемы эффект.

Может стоит рассмотреть возможность добавления необходимой опции?

**Comment by s1lver** [comment]
Да, сделаю

**Comment by bscheshirwork** [comment]
Логично к такой опции добавить
функцию отрисовки кнопки, по которой фильтр обновляется
или, хотя бы, пример добавления кнопки в описании опции
