### ISSUE TITLE
InvalidParamException 

### ISSUE THREAD

**Issue by gelid** [yiisoft/yii2#16360]
InvalidParamException  @deprecated since 2.0.14 Use [[InvalidArgumentException]] instead.
but
class InvalidArgumentException extends InvalidParamException

 that there is something wrong..

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version     | 7.2
| Operating system | Deepin Linux

**Comment by rob006** [comment]
This is for BC reasons, we cannot change that in 2.0.
