### ISSUE TITLE
How to add/retrieve dynamic url (product/category/id) in yii 2 REST API Basic 

### ISSUE THREAD

**Issue by sudhir600** [yiisoft/yii2#16363]
I have a url called product?category=health&id=120&something=somethingElse
I want to access this url like this - api.dev/product/health/120/abcd

I have written actionHealth function in product controller like this.

```
<?php
namespace app\controllers;

use Yii;

class ProductController extends \app\components\BaseController {

//BaseController  inherit \yii\rest\ActiveController

public function actionHealth($category, $id, $extra) {
		echo $id;
		echo '<br />';
		echo $category;
	}
```
...

in config - 'urlManager' => [
`'product/<category:\d+>/<id:\d+>/<something:\w+>' => 'product/health',`

But unfortunalty its not working.  
Here is the error  -

![image](https://user-images.githubusercontent.com/4952560/40970173-6790f722-68d7-11e8-9857-d10c32468ced.png)

**Comment by rustamwin** [comment]
> 'product/<category:\d+>/<id:\d+>/<something:\w+>' => 'product/helath',
wrong typo ?

**Comment by sudhir600** [comment]
@rustamwin Sorry, it was a typo. corrected now.

**Comment by rustamwin** [comment]
Is it working?

**Comment by sudhir600** [comment]
no, it's still not working.  suggest some others way plz.

**Comment by rustamwin** [comment]
> Here is the error - (screenshot)

there is incorrect route, should be `product/health/1/hello`

**Comment by sudhir600** [comment]
Hi @rustamwin, it's still not working.  getting same error.

**Comment by rustamwin** [comment]
change `'product/<category:\d+>/<id:\d+>/<something:\w+>' => 'product/health'` to `'product/<category:\w+>/<id:\d+>/<something:\w+>' => 'product/health'` or  `'<controller:product>/<category:\w+>/<id:\d+>/<something:\w+>' => 'product/health'`

**Comment by sudhir600** [comment]
unfortunately, both solution is not working. 
here is the whole code - 
```

'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => true,
            'rules' => [
                [
		  'class' => 'yii\rest\UrlRule', 
		  'controller' => ['users', 'todo'],
		],
		//  '<alias:\w+>' => 'site/<alias>',
               // 'product/<category:\w+>/<id:\d+>/<something:\w+>' => 'product/health'
              // '<controller:product>/<category:\w+>/<id:\d+>/<something:\w+>' => 'product/health'
	       'product/health/<id:\d+>/<user:\w+>' => 'product/health'
             // allabove three not working
            ],
        ],
```


in productController.php

```
public function actionHealth($id, $usr) {
		echo $id; exit;
	}
```

**Comment by samdark** [comment]
Please ask questions in Slack or Forum. GitHub is for issues and feature requests. Thanks.
