### ISSUE TITLE
Is it need to use ucfirst() at BaseObject::__isset() ?

### ISSUE THREAD

**Issue by mubat** [yiisoft/yii2#16371]
I use next construction at my behavior:
```php
$this->owner->models ?? $this->owner->savedDbModels;
``` 
In this code php tries to check left part with `__isset()` method. But implemented method at `BaseObject.php` try to check that `getmodels()` exist. I think, in this function   `__isset()` should check function name that use at `__get()` method.

*Proposal*:
at `BaseObject::__isset()` function use `$getter = 'get' . ucfirst($name);`.

https://github.com/yiisoft/yii2/blob/6590feef0db1e994a42ffdc3536bccbe2f737ee4/framework/base/BaseObject.php#L180

**Comment by rob006** [comment]
Method names are case insensitive in PHP - it does not have much sense if generated method name is not published in error message or stack trace.
