### ISSUE TITLE
How to validate input fields without using model in Yii2 Rest. 

### ISSUE THREAD

**Issue by sudhir600** [yiisoft/yii2#16375]
let's say i have a controller called "trendController".
in index method, there is a logic which need to save some form data which will show some output to user after validation.

Now input data is something like 
`name ` - Should be text only, 
`amount ` - Number or decimal only, 
`email` - A valid email, 
`phone` - Only number, no country code..

Remember, there is no model play any role here. so how to validate these input in proper yii2 ways.

**Comment by rustamwin** [comment]
try it [DynamicModel](https://github.com/yiisoft/yii2/blob/master/framework/base/DynamicModel.php)

**Comment by Deele** [comment]
It is called "Ad Hoc Validation" https://www.yiiframework.com/doc/guide/2.0/en/input-validation#ad-hoc-validation

It allows you to validate any single value with any yii2 validator without any models.

If you want to validate more than one or two fields, DynamicModel is preferred approach, as it has simpler syntax than multiple Ad Hoc validators. https://www.yiiframework.com/doc/api/2.0/yii-base-dynamicmodel as rustamwin already suggested

**Comment by sudhir600** [comment]
Thanks @rustamwin  @Deele 
It's working exactly what I want but how to set custom errors.

**Comment by Deele** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/input-validation#customizing-error-messages

**Comment by rustamwin** [comment]
[https://www.yiiframework.com/doc/api/2.0/yii-base-dynamicmodel](https://www.yiiframework.com/doc/api/2.0/yii-base-dynamicmodel)

**Comment by sudhir600** [comment]
In a controller file - 
```
public function actionSearch(){
  $name = 123;  // string check      (Error  - your name is invalid)
  $email = 'error_gmail.c';   // wrong email check (Error  - your email is invalid)	
  $inputArray = array('name', 'email');
	
  $model = new DynamicModel(compact('name', 'email'));
  $model->addRule(['name', 'email'], 'string', ['max' => 50], ['message'=> '?? #1])
  ->addRule('email', 'email', ['message' => "Your email format is invalid. #2"]) 
  ->validate();
	
  if ($model->hasErrors()) {
       echo 'validation fails';
       print_r($model->getErrors());
  } else {
	echo 'validation pass';
	}
}
```
`#1`   I want to set four errors (2 input X 2 type of validation) 
`#2`   worked for single attribute validation


So how to acheive this?
