### ISSUE TITLE
Internalization and validator ( comma separated number ) - URGENT- 

### ISSUE THREAD

**Issue by samuelexyz** [yiisoft/yii2#16379]
### What steps will reproduce the problem?

I18N for ITALIAN comma separated value 

my model [['liqug1'],'double'],

DB mysql column is defined as double 

When i render the form : 
<?php echo $form->field($model, 'gene4')->textInput(['type' => 'double']) ?>

I have an error for numer 111,11 ... when record was read i have the correct value but i cannot save

### What is the expected result?

field validated and stored to mysql with dot instead comma

### What do you get instead?

it's not possible to save

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | latest
| PHP version      |  7.2
| Operating system | Linux

**Comment by lubosdz** [comment]
Your code sample is confusing. You refer to i18n issue, but there is no translation formatting code in your example. Are you trying to populate input field <input type=double> with database output? There is no "type=double", only "type=number" - see https://stackoverflow.com/questions/19011861/is-there-a-float-input-type-in-html5. This most likely does not look like framework issue. In any case you can 
1. either set proper PHP locale, 
2. or set table (connection) collation,
3. or use ActiveRecord filters for converting number dots -> commas, commas -> dots.
