### ISSUE TITLE
Wrong column encapsulating when sorting by JSON attributes in PostGreSQL

### ISSUE THREAD

**Issue by juanmacias** [yiisoft/yii2#16374]
### What steps will reproduce the problem?
You have a table with a json column, for example "information".
If you want to order by "name" (inside "information" column) the syntax in PostGresql is mytable.information->>'name'
When using in ActiveDataProvider sort configuration.
   'information_name'=>
                [
                    'asc' => ["mytable.information->>'name'" => SORT_ASC],
                    'desc' => ["mytable.information->>'name'" => SORT_DESC],
                ]

### What is the expected result?
Sorted by name
### What do you get instead?
Error, is encapsulating everything in "
is generating "mytable"."information->>'name'" 
instead of
"mytable"."information"->>'name' 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.1
| Operating system |

**Comment by rob006** [comment]
Did you tried with `yii\db\Expression`?

```php
[
    'asc' => new Expression("mytable.information->>'name' ASC"),
    'desc' => new Expression("mytable.information->>'name' DESC"),
]
```

**Comment by juanmacias** [comment]
Yes, it works, thanks.
