### ISSUE TITLE
Upload vulnerability, model validation rules upload images, only js is verified, the server does not verify uploaded files

### ISSUE THREAD

**Issue by seakk** [yiisoft/yii2#16387]
doc: [https://www.yiiframework.com/doc/guide/2.0/en/input-file-upload](url)

`
   [['imageFile'], 'image', 'extensions' => 'png,jpg,gif', 'skipOnEmpty' => true,
                'minWidth' => 100, 'maxWidth' => 150,
                'minHeight' => 100, 'maxHeight' => 150,
            ],
`
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version     7 | 
| Operating system | mac os

**Comment by seakk** [comment]
我测试的就是官方文档中提供的实例代码
**https://www.yiiframework.com/doc/guide/2.0/en/input-file-upload**

model rules:

` public function rules()
    {
        return [
           [['imageFile'], 'image', 'extensions' => 'png,jpg,gif', 'skipOnEmpty' => true, 'minWidth' => 100, 'maxWidth' => 150, 'minHeight' => 100, 'maxHeight' => 150, ]
        ];
    }`

**Comment by samdark** [comment]
OK, you did. What have you found?
