### ISSUE TITLE
Error install OCI8 PHP 7.2 Debian 9 Laravel 5.6 

### ISSUE THREAD

**Issue by gaalves** [yiisoft/yii2#16388]
# I followed several tutorials to install

php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'oci8.so' (tried: /usr/lib/php/20170718/oci8.so (libmql1.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/oci8.so.so (/usr/lib/php/20170718/oci8.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

 - yajra/laravel-oci8 v5.6.3 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing fr                                                                      om your system.
    - yajra/laravel-oci8 v5.6.2 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing fr                                                                      om your system.
    - yajra/laravel-oci8 v5.6.1 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing fr                                                                      om your system.
    - yajra/laravel-oci8 v5.6.0 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing fr                                                                      om your system.
    - yajra/laravel-oci8 5.6.x-dev requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing                                                                       from your system.
    - yajra/laravel-oci8 5.6.x-dev requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing                                                                       from your system.
    - Installation request for yajra/laravel-oci8 5.6.* -> satisfiable by yajra/laravel-oci8[5.6.x-dev, v5.                                                                      6.0, v5.6.1, v5.6.2, v5.6.3].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/15-xml.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-dom.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gd.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-mysqli.ini
   ##  - /etc/php/7.2/cli/conf.d/20-oci8.ini
    - /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-simplexml.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.2/cli/conf.d/20-wddx.ini
    - /etc/php/7.2/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.2/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.2/cli/conf.d/20-xsl.ini
    - /etc/php/7.2/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by samdark** [comment]
I guess you've reported to wrong repository.
