### ISSUE TITLE
Javascript Errors on Menu

### ISSUE THREAD

**Issue by Stefan39** [yiisoft/yii2#16384]
### What steps will reproduce the problem?
I must update my old Yii2 Installation with composer to 2.0.14, before i must install the fxp/composer-asset-plugin:^1.4.1 globally. After successfully composer update, my project displays a Javascript Error in the console after click on a menu item (with submenu):

`jquery.js:1580 Uncaught Error: Syntax error, unrecognized expression: #
    at Function.Sizzle.error (jquery.js:1580)
    at Sizzle.tokenize (jquery.js:2232)
    at Sizzle.select (jquery.js:2659)
    at Function.Sizzle [as find] (jquery.js:884)
    at jQuery.fn.init.find (jquery.js:2922)
    at new jQuery.fn.init (jquery.js:3032)
    at jQuery (jquery.js:98)
    at getParent (bootstrap.js:790)
    at HTMLAnchorElement.<anonymous> (bootstrap.js:774)
    at Function.each (jquery.js:362)
Sizzle.error @ jquery.js:1580
Sizzle.tokenize @ jquery.js:2232
Sizzle.select @ jquery.js:2659
Sizzle @ jquery.js:884
find @ jquery.js:2922
jQuery.fn.init @ jquery.js:3032
jQuery @ jquery.js:98
getParent @ bootstrap.js:790
(anonymous) @ bootstrap.js:774
each @ jquery.js:362
each @ jquery.js:157
clearMenus @ bootstrap.js:773
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014`

### What is the expected result?
The menu works fine

### What do you get instead?
Nothing happens and the Javascript Error displayed in the console.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0.30
| Operating system | Mac OS 10.13.4 and also on the Live Server with Ubuntu 16.04.2

**Comment by Stefan39** [comment]
> When does the issue occur?
When you click on a menu item

> What do you see?
Nothing! If the Browser console are open, you see the javascript error above.

> What was the expected result?
The Dropdown opens

> Can you supply us with a stacktrace? (optional)
Only this, what i have posted above.

> Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)
No, what i have describe: I have update with composer (also global require fxp-asset before) and not more.

I don't know, what i shall more describe. I didn't have change anything else. The Yii version before was 2.0.6 and now i have updated to 2.0.14, nothing more.

**Comment by samdark** [comment]
It's not enough info to reproduce the issue. We don't have your project and have no idea what menu you use and how.

**Comment by Stefan39** [comment]
Hm, ok.. 

The project was developed ca. on January '18. The Menu:

`<?php
    NavBar::begin([
        'brandLabel' => Html::img('@web/img/logo.png',['title'=>Yii::t('app','Olicci Testpages'),'alt'=>Yii::t('app','Olicci Testpages')]),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-default navbar-fixed-top',
        ],
    ]);
    $items[]=['label' => Yii::t('app','Start'), 'url' => ['/site/index']];
    // Kategorien Auslesen und als Menü anzeigen
    $cats = Categories::getOrdenedCategories();
    $subitems = [];
    if(!empty($cats)){
        foreach($cats as $catid=>$cat) {
            if(!empty($cat['subcats'])&&is_array($cat['subcats'])){
                $sitems=[];
                foreach($cat['subcats'] as $scatid => $scat) {
                    $sitems[]=['label'=>$scat['label'],'url' => ['/category/index','id'=>$scatid]];
                }
	            $items[]=[
		            'label' => $cat['label'],
		            'url' => ['/category/index/','id'=>$catid],
                    'items' => $sitems
	            ];
            } else {
	            $items[]=[
		            'label' => $cat['label'],
		            'url' => ['/category/index/','id'=>$catid]
	            ];
            }
        }
    }

    if(Yii::$app->user->isGuest) {
        $items[]=['label' => Yii::t('app','Login'), 'url' => ['/site/login']];
    } else {
        //if (Yii::$app->user->can('editTemplates')||Yii::$app->user->isSuperadmin) {
	    if (User::hasPermission('editTemplates')||Yii::$app->user->isSuperadmin) {
	        $subitems=[
		        ['label'=>Yii::t('app','Kategorien'),'url'=>['/categories/index']],
		        ['label'=>Yii::t('app','Templates'),'url'=>['/templates/index']],
                ['label'=>Yii::t('app','Mandanten'),'url'=>['/clients/index']],
		        '<li class="divider"></li>',
	        ];
        }
        if (User::hasPermission('viewUsers')||Yii::$app->user->isSuperadmin) {
            $subitems[]=['label'=>Yii::t('app','Users'),'url'=>'#','items'=>\wpler\modules\UserManagement\UserManagementModule::menuItems()];
        }
	    $items[]=['label' => Yii::t('app','System'),'url'=>'#','items' => $subitems];
        $items[]=('<li>'.Html::beginForm(['/user-management/auth/logout'],'post').Html::submitButton(Yii::t('app','Logout ({user})',['user'=>Yii::$app->user->identity->username]),['class'=>'btn btn-link logout']).Html::endForm().'</li>');

    }

    echo \app\components\widgets\ClientSwitchWidget::widget([]);

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => $items,
    ]);
    NavBar::end();
    ?>`

and if i am click on a menu item with submenu, the above javascript error occured into the browser console (see screenshot).

![bildschirmfoto 2018-06-15 um 12 30 45](https://user-images.githubusercontent.com/869835/41463804-1e5001d4-7098-11e8-9970-da333e52de7a.png)

The Steps i have do:
Before on composer.json was the Yii version 2.0.6 ( "yiisoft/yii2": "2.0.6",). I have change it now to "yiisoft/yii2": "~2.0.14",

After that i do on terminal composer update, but it was failed because some dependencies are failed. Anywhere i have read, that i must update the fxp-asset-plugin, so i have do:

`composer global require "fxp/composer-asset-plugin:^1.4.1" --no-plugins`

and after that i could do composer update without any problems. But after the update this javascript errors occured and the submenu not open.
