### ISSUE TITLE
Yii2 ActiveDataProvider When the query uses the yii\db\query object,  ActionColumn bug!

### ISSUE THREAD

**Issue by seakk** [yiisoft/yii2#16395]
Yii2 ActiveDataProvider When the query uses the yii\db\query object, the resulting view of the GridView's index page has a bug in the yii\grid\ActionColumn generated link

doc: https://www.yiiframework.com/doc/guide/2.0/en/output-data-providers#active-data-provider

```php

use yii\db\Query;
use yii\data\ActiveDataProvider;

//$query = Post::find()->where(['status' => 1]); 

// The view link generated by yii\grid\ActionColumn has a bug. The generated link id is the index number of the array. The correct one should be the primary key of the record.

$query = (new Query())->from('post')->where(['status' => 1]);  

$provider = new ActiveDataProvider([
    'query' => $query,
    'pagination' => [
        'pageSize' => 10,
    ],
    'sort' => [
        'defaultOrder' => [
            'created_at' => SORT_DESC,
            'title' => SORT_ASC, 
        ]
    ],
]);
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version    7.0  | 
| Operating system | mac os

**Comment by vuquangthinh** [comment]
Why did you create $provider instanceof ActiveDataProvider by Query.
It's "Active" so you need a ActiveQuery.
You can see: https://github.com/yiisoft/yii2/blob/65f6b59b35cc63aee7f16a64aeafcec11a8dba39/framework/data/ActiveDataProvider.php#L135

**Comment by seakk** [comment]
Because I want to return an array directly instead of converting it with ModelName::find()->asArray()

**Comment by vuquangthinh** [comment]
Let's try SqlDataProvider
