### ISSUE TITLE
Moved from [yiisoft/yii2-gii#368] Incorrect result when creating migration with fields

### ISSUE THREAD

**Issue by dmirogin** [yiisoft/yii2#16394]
Original issue https://github.com/yiisoft/yii2-gii/issues/368

### What steps will reproduce the problem?

yii migrate/create add_deleted_at_column_deleted_by_column_to_accountable_person_table --migrationPath=backend/modules/accountablePerson/migrations --interactive=0 --fields="deleted_at:dateTime:notNull:defaultValue(0000-00-00 00:00:00),deleted_by:integer:foreignKey(user)" --useTablePrefix=true

### What's expected?

    /**
    * Handles adding `deleted_at`, `deleted_by` to table `accountable_person`.
    */

### What do you get instead?

    /**
    * Handles adding deleted_at_column_deleted_by to table `accountable_person`.
    */

### What's expected?

    $this->addColumn('{{%accountable_person}}', 'deleted_at', $this->dateTime()->notNull()->defaultValue('0000-00-00 00:00:00'));

### What do you get instead?

    $this->addColumn('{{%accountable_person}}', 'deleted_at', $this->dateTime()->notNull()->defaultValue('0000-00-00 00()->00()->00')());

### What's expected?

    $this->createIndex(
            'idx-accountable_person-deleted_by',
    ...
    $this->addForeignKey(
            'fk-accountable_person-deleted_by',

I'm not realy shure what to expect here but whats generated does not look OK to me. Maybe it can be  'idx-{{%accountable_person}}-deleted_by' and `fk-{{%accountable_person}}-deleted_by`

### What do you get instead?

    $this->createIndex(
            '{{%idx-accountable_person-deleted_by}}',
    ...
    $this->addForeignKey(
            '{{%fk-accountable_person-deleted_by}}',

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16-dev
| PHP version      | PHP 5.6.9

**Comment by alexkart** [comment]
@dmirogin, I don't see what's wrong with the "Issue 3".
From this

```
$this->createIndex(
        '{{%idx-accountable_person-deleted_by}}',
...
$this->addForeignKey(
        '{{%fk-accountable_person-deleted_by}}',
```

It will create index and foreign key with prefixed names `prefix_idx-accountable_person-deleted_by` and `prefix_fk-accountable_person-deleted_by`. It seems correct to me.
