### ISSUE TITLE
JS files are not published in a modal

### ISSUE THREAD

**Issue by mbraidy** [yiisoft/yii2#16398]
I have a _form.php that is rendered in a modal through a create action

```
public function actionCreate()
    {
        $model = new TimeMingaps();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $model->active = 1;
        $model->percentage = 100;
        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }
```

The views/create.php in its minimal format is as follows:
```
<div class="mingaps-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>
```
and views/_form.php in its minimal format is as follows:
```
<?php
use backend\assets\BootstrapSelectAsset;
use backend\assets\distribution\ConstraintsAsset;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

BootstrapSelectAsset::register($this);
ConstraintsAsset::register($this);
?>
<div class="mingaps-form">
    <?php $form = ActiveForm::begin(['options' => ['id' => 'PreferredSlots-form' ]]); ?>
        <?= Html::tag('p', Yii::t('app', 'District'), ['class' => 'entitylabel']) ?>
        <?= Html::dropDownList('districtID', "", ['a','b'], [
        		'title' => "Select...",
        		'class' => 'selectpicker',
        	]) ?>
        <?= Html::submitButton('Submit', ['class' => 'btn btn-success btn-sm']) ?>
	<?php ActiveForm::end(); ?>
</div>
```

ContraintsAssets.php
```
<?php
namespace backend\assets\distribution;

use yii\web\AssetBundle;
use Yii;
class ConstraintsAsset extends AssetBundle
{
    public $sourcePath = '@app/assets/distribution';
    public $css = [
     	'css/constraints.css',
    ];
    public $js = [
    	'js/constraints.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];
}
```

contraints.js
```
$(document).ready(function() {
	$(".selectpicker").selectpicker();
});
```

When launched in the modal the first time, all the assetBundles are launched properly and both Constraints.css and Constraints.js are listed in Chrome Devtools.  Moreover, the selectpicker is rendered and works properly.
However, when I dismiss the modal and launch it a second time, only the css files are listed in the DevTools and no js at all(and selectpicker is not working and the initial dropdown is not even shown)

### What steps will reproduce the problem?
Insert an assetBundle with JS file in a modal and launch the modal
### What is the expected result?
JS files are pubished
### What do you get instead?
No JS files from the Modal assets is found

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.2
| Operating system | Ubuntu 18.04- x86_64

**Comment by mbraidy** [comment]
- When does the issue occur?
> In the second launch of a modal

- What do you see?
> I can see the dropdown rendering properly and then suddenly within one second disappearing.  It is so fast I cannot check whether the JS are published.  After it disappears, I cannot see any JS file in the DevTools.

- What was the expected result?
> Change a dropdown into bootstrap-select. 

- Can you supply us with a stacktrace? (optional)
 > which one? from Yii or from DevTools?

- Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)
> First post was edited and code inserted

**Comment by mgrechanik** [comment]
in  views/create.php try to change to this:
```
<?php
Yii::$app->assetManager->appendTimestamp = true; // !!!!
?>
<div class="mingaps-create">
    <?= $this->renderPartial('_form', [   // And you hardly need second renderAjax here sinse you have one already
        'model' => $model,
    ]) ?>
</div>
```

**Comment by mbraidy** [comment]
I corrected the views/create.  It was a mere render() and not renderAjax().
Sorry about that

**Comment by mgrechanik** [comment]
Render() inside renderAjax()? It is not correct either.

I did something like what you are doing.
And saw that with ajax calls js files are not being executed second time because they are cached by browser.
You can check this by adding alert('hello') near to $(".selectpicker").selectpicker();
I solved this by adding random string to js url

```
            $this->view->registerJsFile($meta['jsfile'] . '?random=' . time(), [
                'depends' => [\yii\web\JqueryAsset::className()],
            ]);            
```

**Comment by mbraidy** [comment]
I did not get 
`$meta['jsfile']`

What is that?

**Comment by mgrechanik** [comment]
It is url of a js file.
Look for details in [docs](https://www.yiiframework.com/doc/api/2.0/yii-web-view#registerJsFile()-detail)

**Comment by mbraidy** [comment]
I still have the same problem.

**Comment by berosoboy** [comment]
@mbraidy I think that not republishing bundles is the expected behavior.

Maybe your problem is more JavaScript related. If i got it right, you need to initialize your selectpicker every time you open the modal. You can accomplish it by handling the proper event.

I suggest you to change your contraints.js file to something like that:

```js
$('#your-modal-id').on('.shown.bs.modal', function () {
    $(".selectpicker").selectpicker();
});
```
