### ISSUE TITLE
Second IF in Mysql query doesn't work

### ISSUE THREAD

**Issue by NameIvan** [yiisoft/yii2#16403]
```
        $order = \app\models\User::find()
            ->select([
                'IF (ISNULL(`users`.`nickname`), `users`.`firstname`, `users`.`nickname`) as `name1`',
                '(IF (ISNULL(`users`.`nickname`), `users`.`firstname`, `users`.`nickname`)) as `name2`'
            ])
            ->asArray()->one();
```
It is work, but if I set select via string. I get error.
```
$order = \app\models\User::find()
            ->select(
                'IF (ISNULL(`users`.`nickname`), `users`.`firstname`, `users`.`nickname`) as `name1`,
                (IF (ISNULL(`users`.`nickname`), `users`.`firstname`, `users`.`nickname`)) as `name2`'
            )
            ->asArray()->one();
```

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) as `name2` FROM `users`' at line 1
> The SQL being executed was: SELECT IF (ISNULL(`users`.`nickname`), `users`.`firstname`, `users`.`nickname`) as `name1`, (IF (ISNULL(`users`.`nickname`), `users`.`nickname`)) as `name2` FROM `users`

It is happened after update Yii2 from 2.0.14 to 2.0.15.1

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | ubuntu 16.04

**Comment by pro100taA** [comment]
$order = \app\models\User::find()
            ->select([
                'name1' => new Expression('IF (ISNULL(`users`.`nickname`), `users`.`firstname`, `users`.`nickname`))',
                    'name2' => new Expression('(IF (ISNULL(`users`.`nickname`), `users`.`firstname`, `users`.`nickname`))')
            ])
            ->asArray()->one();

**Comment by samdark** [comment]
What SQL do you expect?

**Comment by Alex-Code** [comment]
Non simple selects need to be provided in an array to avoid them being split.
See note here, https://www.yiiframework.com/doc/api/2.0/yii-db-query#select()-detail
