### ISSUE TITLE
Readonly/disabled inputs still trigger AJAX validation, even if it's explicitly disabled

### ISSUE THREAD

**Issue by jurchiks** [yiisoft/yii2#16409]
### What steps will reproduce the problem?
1. Have an ActiveForm with AJAX validation configured (in my case it's a `yii\bootstrap\ActiveForm`, but the validation attributes are in `yii\widgets\ActiveForm`, so it's likely others would be the same).
2. Add a `readonly` or `disabled` attribute to any field and disable AJAX validation for that field, e.g.:
```
<?= $form->field($user, 'name')
	->textInput([
		'readonly'               => 'readonly',
		'enableClientValidation' => false,
		'enableAjaxValidation'   => false,
	])
	->label(true) ?>
```
3. Click on that field to focus, then click away to trigger validation.

### What is the expected result?
No validation, because the field is readonly AND validation is disabled (normally, even `readonly` alone should suffice, there should be no focus/blur events for a disabled input, removing which would fix it in this case).

### What do you get instead?
AJAX request for validation still goes through.

### Additional info
The same happens if you replace `readonly` with `disabled`.
Also, in my case, the field had no rules defined, since it was taken from another model for display purposes only.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.0.28
| Operating system | Windows 7
| Browser | Google Chrome v67

**Comment by mgrechanik** [comment]
Why don't you use forums for such questions?

You need to disable validation like this:
```
                <?= $form->field($model, 'number', [
                        'enableAjaxValidation' => false,  // <------------
                    ])->textInput(['readonly' => 'readonly']); 
                
                ?>
```

**Comment by jurchiks** [comment]
It's not a question, it's a bug. Now go pester someone else.

**Comment by buttflattery** [comment]
@jurchiks  its ok, dont mind, he might be mistaken.

**Comment by mgrechanik** [comment]
[docs](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L381)
```
/*
 *@param array $options the tag options in terms of name-value pairs. These will be rendered as
 * the attributes of the resulting tag.
 */
textInput($options = [])
```
Is 'enableClientValidation' a tag attribute?

**Comment by chrisschd** [comment]
Thanks for your answers!

I can only speak for our application, these changes broken our complete Application. We used, “tinyint” for Boolean in the database since we worked with yii/yii2. This little change bring us in troubles we have to rework a huge amount of models to bring up our application in a working state. 

I think we are not the only one which will have these problems, but this was more a feature request as a bug report. Maybe it is possible to setup the Validator to support also Boolean types?  For example:

```
class NumberValidator extends Validator
{
    /**
     * @var bool whether the attribute value can only be an integer. Defaults to false.
     */
    public $integerOnly = false;
    
    public $allowBoolean = true; //NEW 
….
/*
     * @param mixed $value the data value to be checked.
     */
    private function isNotNumber($value)
    {
        return is_array($value)
            || (!$allowBoolean  && is_bool($value)) //NEW: !$allowBoolean&
            || (is_object($value) && !method_exists($value, '__toString'))
            || (!is_object($value) && !is_scalar($value) && $value !== null);
    }
…
}

```

**Comment by buttflattery** [comment]
This issue should be closed as it is a question more than a bug as the `enableClientValidation` should be provided as the `field()` parameter rather than `textInput()`.
