### ISSUE TITLE
yii basic on migration Class 'Schema' not found'

### ISSUE THREAD

**Issue by tvitcom** [yiisoft/yii2#16404]
### What steps will reproduce the problem?
(yii2 install basic-app) 
cd basic
php yii migrate
mkdir migrations
php yii migrate/create create_statistic_tbl
(edit our_migration_xxxxx.php as manner: 'id' => Schema::TYPE_BIGPK !!!)
php yii migrate
> Apply the above migration? (yes|no) [no]:yes
-> Voila!: *** applying m180614_174153_create_statistic_tbl
PHP Fatal error:  Class 'Schema' not found in /home/www/nisa/basic/migrations/m180614_174153_create_statistic_tbl.php on line

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |2.0.15.1
| PHP version      | PHP 5.6.33-0+deb8u1
| Operating system |deb8u1

**Comment by lesha724** [comment]
@tvitcom try add
```
use yii\db\Schema;
```
