### ISSUE TITLE
Pagination::getLinks() doesn't return a WHOLE set of links

### ISSUE THREAD

**Issue by ptz-nerf** [yiisoft/yii2#16418]
https://github.com/yiisoft/yii2/blob/ec937d004ac82546c77c5302086520045e976d22/framework/data/Pagination.php#L325-L332
What are these conditions for? The documentation states that all links will be returned.

**Comment by ptz-nerf** [comment]
But first and last pages always exist regardless of the current page.

**Comment by samdark** [comment]
They do. That could be considered a bug and fixed.

**Comment by samdark** [comment]
Would you like to send a pull request fixing it?

**Comment by ptz-nerf** [comment]
I'll try later when I have time.

**Comment by ptz-nerf** [comment]
@samdark в процессе стало ясно, что не все так просто, как кажется. `yii\rest\Serializer` использует его, не уверен, что там всегда должны присутствовать ссылки на первую и последнюю страницы. Не фича ли это?) Если должны, то должны ли они быть и совпадать, если всего одна страница?

**Comment by samdark** [comment]
Логически ответы на оба вопроса "да".
