### ISSUE TITLE
Cors Filter Fails with large data

### ISSUE THREAD

**Issue by gailu** [yiisoft/yii2#16415]
Problem Description: When Response data size is large then CORS filter fails to add Access-Control-Allow-Origin in the response.

### What steps will reproduce the problem?
Step 1:
Enable Cors filter in your controller 
    public function behaviors()
    {
        return [
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
            ],
        ];
    }

Step 2: Send Following POST with following headers 
Headers: 
Origin: http://localhost:8100
Referer: http://localhost:8100
Content-Type: application/json

Return the response with Following Data
Response Data:
{ "result": "success", "datalist": [ { "serial": "ss2100000001", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Bedroom Switch Board", "switches": [ { "serial": "ss2100000001", "map": 1, "name": "Master Light", "type": "switch" }, { "serial": "ss2100000001", "map": 2, "name": "Master Fan", "type": "switch" } ] }, { "serial": "se3110000490", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Black Listed", "switches": [ { "serial": "se3110000490", "map": 1, "name": "Switch-1", "type": "outlet" }, { "serial": "se3110000490", "map": 2, "name": "Switch-2", "type": "outlet" }, { "serial": "se3110000490", "map": 4, "name": "Switch-3", "type": "outlet" } ] }, { "serial": "ps1110000115", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Home AC", "switches": [ { "serial": "ps1110000115", "map": 1, "name": "BedroomAC", "type": "switch" } ] }, { "serial": "se3100000002", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Home Power Strip", "switches": [ { "serial": "se3100000002", "map": 1, "name": "TV", "type": "outlet" }, { "serial": "se3100000002", "map": 2, "name": "Set top box", "type": "outlet" }, { "serial": "se3100000002", "map": 4, "name": "Game Console", "type": "outlet" } ] }, { "serial": "ps1100000000", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Office AC", "switches": [ { "serial": "ps1100000000", "map": 1, "name": "Switch-1", "type": "switch" } ] }, { "serial": "se3110000312", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Office Power Strip", "switches": [ { "serial": "se3110000312", "map": 1, "name": "Switch-1", "type": "outlet" }, { "serial": "se3110000312", "map": 2, "name": "Switch-2", "type": "outlet" }, { "serial": "se3110000312", "map": 4, "name": "Switch-3", "type": "outlet" } ] }, { "serial": "ss2100000003", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Office Switch Board''", "switches": [ { "serial": "ss2100000003", "map": 1, "name": "Office Light", "type": "switch" }, { "serial": "ss2100000003", "map": 2, "name": "Office Fan", "type": "switch" } ] } ] }
### What is the expected result?
Response must include following header
Access-Control-Allow-Origin: http://localhost:8100

### What do you get instead?
Access-Control-Allow-Origin header is not included in the response

### Additional info
If we reduce the response data as follows then we get Access-Control-Allow-Origin header included in the response.
Response Data:
{ "result": "success", "datalist": [ { "serial": "ss2100000001", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Bedroom Switch Board", "switches": [ { "serial": "ss2100000001", "map": 1, "name": "Master Light", "type": "switch" }, { "serial": "ss2100000001", "map": 2, "name": "Master Fan", "type": "switch" } ] }, { "serial": "se3110000490", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Black Listed", "switches": [ { "serial": "se3110000490", "map": 1, "name": "Switch-1", "type": "outlet" }, { "serial": "se3110000490", "map": 2, "name": "Switch-2", "type": "outlet" }, { "serial": "se3110000490", "map": 4, "name": "Switch-3", "type": "outlet" } ] }, { "serial": "ps1110000115", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Home AC", "switches": [ { "serial": "ps1110000115", "map": 1, "name": "BedroomAC", "type": "switch" } ] }, { "serial": "se3100000002", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Home Power Strip", "switches": [ { "serial": "se3100000002", "map": 1, "name": "TV", "type": "outlet" }, { "serial": "se3100000002", "map": 2, "name": "Set top box", "type": "outlet" }, { "serial": "se3100000002", "map": 4, "name": "Game Console", "type": "outlet" } ] }, { "serial": "ps1100000000", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Office AC", "switches": [ { "serial": "ps1100000000", "map": 1, "name": "Switch-1", "type": "switch" } ] }, { "serial": "se3110000312", "fwrev": 514, "timezone": "Asia\/Kolkata", "devname": "Office Power Strip", "switches": [ { "serial": "se3110000312", "map": 1, "name": "Switch-1", "type": "outlet" }, { "serial": "se3110000312", "map": 2, "name": "Switch-2", "type": "outlet" }, { "serial": "se3110000312", "map": 4, "name": "Switch-3", "type": "outlet" } ] } ] }

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 5.5.9-1
| Operating system |  Ubuntu 14.04

**Comment by samdark** [comment]
Sounds very weird. There no checks like that in the framework.

**Comment by gailu** [comment]
Answers to additional Info:

Question: When does the issue occur?
Ans: today
Question: What do you see?
Ans: If we reduce data size in response, we see that two additional headers are included in the response as expected. These two headers are.  Access-Control-Allow-Origin and Access-Control-Expose-Header. If we increase data size  in the response these two headers are missing from response though all other information is intact.
Question: What was the expected result?
Ans: CORS header must be included in response irrespective if data size in the response
Question: Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)
Answer: Its a part of our large application not possible to share.

@samdark 
I also tried to check in the code and couldn't find any such check. I believe that something is failing that causes CORS header not to be applied instead of an intentional check

**Comment by gailu** [comment]
@samdark 
Thanks for your advice. I have added CORS header in apache2.conf as described in [https://enable-cors.org/server_apache.html](CORS on Apache) and its working now. I still believe though that is a kind of workaround. Header that was expected from framework is added by  apache2. 
I am still not sure if we need to add it in apache configuration then do we really need CORS filter in our controller.

**Comment by cebe** [comment]
Which Yii version are you using? Sounds like headers where already sent when Yii tries to send response so it can not add its own. Latest Yii version will complain with exception in this case.
