### ISSUE TITLE
Html::a data-confirm => false for disabled confirm dialog

### ISSUE THREAD

**Issue by mariovials** [yiisoft/yii2#16425]
### What steps will reproduce the problem?
```
Html::a("Text", ["url/to"], [
  'data' => ['confirm' => false ]
]);
```

### What is the expected result?
Don't should by generated a confirm dialog

### What do you get instead?
But, it generates an empty confirm dialog

With this fix, we could type code cleaner and fast, put code in the same tag.
Now we must tye two tag for disabled the confirm dialog

**Comment by Alex-Code** [comment]
If I've understood correctly this could be because the check only looks at whether `confirm` is set not at it's actual value so having `false` will still trigger the confirm dialog.
https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L475

**Comment by mariovials** [comment]
Yes, i suggest that evaluate the value before trigger confirm dialog, to improve the coding.

This would make it possible to write` 'confirm' => $confirmation`
if `$confirmation` is `false `(or `null `may be), do not trigger confirm dialog.

To make this, currently I have write twice, one for each situation

**Comment by rob006** [comment]
Doesn't this do what you want?

```php
Html::a("Text", ["url/to"], [
  'data' => ['confirm' => null]
]);
```

**Comment by mariovials** [comment]
Yes, just not generate a confirm dialog when confirm like false.
Either way, it would be nice if it worked with `''` (an empty string), `false `or `null`.
