### ISSUE TITLE
Captcha Validation can clear view params array

### ISSUE THREAD

**Issue by DanaLuther** [yiisoft/yii2#16420]
### What steps will reproduce the problem?
Create a model that uses a captcha validation rule on one of the model properties.

On the controller where the captcha/action is attached, have an init() that sets some default options for the params (e.g.,  `$this->view->params['heading'] = 'More information about '.$this->id;` )

Create a view for the form, and before starting the form, add view params (e.g., `$this->params['heading'] = 'Customized heading to replace the default for this section';` ) at the top of the file, before the form is started.

Include the Captcha field in the form as one of the inputs.

When rendering the page, with client validation enabled, the view params for heading will reset to what was in the controller init method. With client validation disabled, the view params remain properly set.

### What is the expected result?
A model validation rule should never modify the state of the application outside of the model being verified.

### What do you get instead?
The view params array is reset to the default view params array. I believe it's because we have some defaults being set in the controller init, and the Captcha Validator does a createAction when it validates?  I think we (local project) could bypass the problem by checking for if the action being run is the captcha action, do not set the dynamic defaults for the params as we are doing, but it seems like the validator should be very cautious when creating an action for validation and check/cache params??  I can think of several ways to work around or avoid this now that I know what's happening, but I think it's disingenuous for a validation rule to modify the view params inadvertently.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.15 
| Operating system | Alpine Linux

**Comment by samdark** [comment]
> I believe it's because we have some defaults being set in the controller init, and the Captcha Validator does a createAction when it validates?

Yes.

> validator should be very cautious when creating an action for validation and check/cache params?

That's not validator doing it that but controller init. Not sure how to affect it from validator side.

**Comment by samdark** [comment]
I don't think it could be adjusted efficiently.

**Comment by DanaLuther** [comment]
I worked around it by adding a static initialized value so it won’t re-init
when the validator creates the controller. I think it’s worth a note that
the validator will cause the controller init() method to be re-run when it
sets up the client validaton.

**Comment by samdark** [comment]
init() is run when any action is executed. That's how it works.

**Comment by samdark** [comment]
I understand what happens but don't see a good way not to call `init()` when running one specific action.
