### ISSUE TITLE
Problem using CSRF

### ISSUE THREAD

**Issue by sahnaseredini** [yiisoft/yii2#16434]
Hi there!
CSRF validation must be enabled by default, however, it does not work for me! 
When I manually test my code and send a request without a CSRF token to my form it does accept my request. Also, when I change the CSRF token and send the request again, programme accepts it again. It seems that CSRF validation is completely out of service in my programme. How should I fix it?

Here is my form:

```php
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <?= $form->field($model, 'img_upload')->widget(FileInput::classname(), [
        'options' => ['accept' => 'images/*'],
        'pluginOptions' => [
            'allowedFileExtensions'=> ['jpg', 'jpeg', 'png',],
            'showUpload' => false,
            'browseLabel' => '',
            'removeLabel' => '',
            'mainClass' => 'input-group-lg',
            'maxImageHeight'=> 70,
            'maxFileSize'=>1024,
            'resizeImage'=> true,
            'resizeIfSizeMoreThan'=> 1000,
            'msgInvalidFileExtension' => 'Invalid File Extension',
            'msgSizeTooLarge' => 'Size Too Large'
        ]
    ])->label(false);?>
    <?= $form->field($model, 'org_name')->textInput(['class' => 'form-control lefter input-ltr','maxlength' => 255]) ?>
    <?= $form->field($model, 'employee_full_name')->textInput(['class' => 'form-control lefter input-ltr','maxlength' => 255]) ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success left' : 'btn btn-primary left']) ?>
    </div>
    <?php ActiveForm::end(); ?>
```

Yii version: 2.0.15.1
PHP version: 7.2.4 
Operating system: Debian 9.4

**Comment by samdark** [comment]
How do you send it manually?

**Comment by AutApaCert** [comment]
I have not changed default configurations of CSRF validation of Yii2. I use "Burp Suite" to test whether it works properly or not. When I send a request to my form using "Burp Suite", I am able to change form parameters like CSRFToken. When I change or remove CSRFToken and then pass the form I expect an error to occur, however, the form will be passed and changes will be done. So, CSRF attack is possible to be done in my form.
When does the issue occur?
- In every page that contains a form (such as user information update form).
What do you see?
- The programme works irrespective of CSRFToken value.
What was the expected result?
- Bad request error (400)

**Comment by sahnaseredini** [comment]
I have not changed default configurations of CSRF validation of Yii2. I use "Burp Suite" to test whether it works properly or not. When I send a request to my form using "Burp Suite", I am able to change form parameters like CSRFToken. When I change or remove CSRFToken and then pass the form I expect an error to occur, however, the form will be passed and changes will be done. So, CSRF attack is possible to be done in my form.
When does the issue occur?
-In every page that contains a form (such as user information update form).
What do you see?
-The programme works irrespective of CSRFToken value.
What was the expected result?
-Bad request error (400)

**Comment by sahnaseredini** [comment]
Also, I ought to mention that CSRF validation for those forms which are placed in Yii default advanced project (such as SiteController) are working properly and are protected against CSRF attacks. The above issue is for those new forms that I created them using gii.

**Comment by samdark** [comment]
Do you have an idea what request is made with burp suite? Have you started with default basic application? Which form do you test?

**Comment by sahnaseredini** [comment]
Do you have an idea what request is made with burp suite?
This is my request using Burp suite. Now, if I change or even remove CSRF token, the request will be still valid.
`POST /organizations/update/1.html HTTP/1.1
Host: localhost:1234
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:1234/organizations/update/1.html
Content-Type: multipart/form-data; boundary=---------------------------31604743225288
Content-Length: 1253
Cookie: BACKSESSID=q2a6k85aolqums91lp98pro5n1; _backendCSRF=d084915b0ef623b7ee4ad4b036a6c5840876efbf8994be7d364709346c5c9898a%3A2%3A%7Bi%3A0%3Bs%3A12%3A%22_backendCSRF%22%3Bi%3A1%3Bs%3A32%3A%22fOCiPSs5hQUJJcqj0SYMatvL880wrfUI%22%3B%7D; FRONTSESSID=ij631hbfoeej4b1pm3nq9ofec5; _frontendCSRF=a507c14234f1515b78fd85dfb0f46b582c7744b58d0b0ae6cef2a3de025466f3a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_frontendCSRF%22%3Bi%3A1%3Bs%3A32%3A%22qVYtzGFaCs8ZnhzAB-J8KThlLyhL5GHh%22%3B%7D; _identity=89eb0d6b0a85f394609e12e371d596307fcf96d2cd51a5341c9a270b65670c71a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A46%3A%22%5B2%2C%22bW0ArQcwCWXMn0WP30aFMMSprJ0CY_F6%22%2C2592000%5D%22%3B%7D
Connection: keep-alive
Upgrade-Insecure-Requests: 1

-----------------------------31604743225288
Content-Disposition: form-data; name="_backendCSRF"

7T2mX8V8jEcsSIiMtG2jJuFpE5zdDt8aY57gf5Q72HyLcuU2lS__ckQZ3cb-DtJM0TpK0bx6qVZbptAI5l2NNQ==
-----------------------------31604743225288
Content-Disposition: form-data; name="Organizations[org_name]"

ORG_name1
-----------------------------31604743225288
Content-Disposition: form-data; name="Organizations[employee_full_name]"

AKBAR
-----------------------------31604743225288
`
Have you started with default basic application?
- No, I started with default advanced application.
Which form do you test?
- I want to update a user account via update form which uses _form.php. and I made them all by gii.

**Comment by larryli** [comment]
OMG, what's about `_backendCSRF` and `_frontendCSRF`? Did you reconfigure the `csrfParam` of default `yii\web\Request` in config file?

Please give your config.

**Comment by sahnaseredini** [comment]
No, I did not change default configuration files (yii\web\Request, yii\web\Controller, and etc.) at all. I just changed the name of csrfParam in {backend, frontend}\config\main.php
`'components' => [        
         'request' => [
            'cookieValidationKey' => 'XXXX',
            'csrfParam' => '_backendCSRF',
        ],
],
`

**Comment by sahnaseredini** [comment]
Worth to note that I've upgraded Yii version from 2.0.6 to 2.0.15.1 and honestly I have no idea whether CSRF token validation was working correctly before I upgraded it or not.

**Comment by samdark** [comment]
You aren't testing it properly. CSRF protection is meant to protect against cross-site requests but you're making the request from the same domain having a CSRF-token cookie in place. That's why it works.

**Comment by sahnaseredini** [comment]
Problem solved! My test environment was totally fine and the test was done correctly. I just found out that I made a mistake by overriding beforeAction method.
If you override beforeAction method like this
`
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            Yii::info(['Backend. Guest user attempt to access organizations.', 'OrganizationsController', 'failed'],'activity');
            return $this->goHome();
        }
        else{
            return Yii::$app->request->url;
        }
    }
`
You will lose CSRF validation. However, if you change "return Yii::$app->request->url;" to "return parent::beforeAction($action);" the problem will be solved.
Thank you for your consideration.

**Comment by bactv17** [comment]
Me too, when I not login, problem not occur, but when logged and post form with change csrf or remove input csrf, the request will be still success. Have you a idea for this problem? @samdark

**Comment by samdark** [comment]
@bactv17 likely that's something interfering with the filter. You need to debug it to find out.
