### ISSUE TITLE
ActiveForm::begin() encoding action parameter, after it's been built by Url::to();

### ISSUE THREAD

**Issue by maz0717** [yiisoft/yii2#16452]
### What steps will reproduce the problem?
Use multiple params when setting the action option of ActiveForm.
```php
$form = ActiveForm::begin([
    'action' => ['update', 'id'=>$id, 'type' => $type]
]);
```

### What is the expected result?
The documentation states that this value is constructed with Url::to().  I would expect the url to pass through without being encoded after being constructed with Url::to().  I expect the following output:
```php
<form action="update?id=1&type=payment">
```

### What do you get instead?
Instead I get the '&' encoded:
```php
<form action="update&id=1&amp;type=payment">
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.0.27
| Operating system | MacOS 10.13.5

**Comment by rob006** [comment]
This works as expected - `&` **should** be encoded in this way according to HTML secs.

**Comment by maz0717** [comment]
This & is not part of a variable, it is the field separator.  It should not be encoded.  It should either be fixed, or the docs should not tell you you can do it.
