### ISSUE TITLE
Fork not working with latest version

### ISSUE THREAD

**Issue by alko79** [yiisoft/yii2#16459]
### What steps will reproduce the problem?
go on github
go on yii2 githu page
click on fork
go on your forked yii2
branch it
make a commit with your modded code
tag it x.x.x
go on your composer json
add 
        {
            "type": "vcs",
            "url": "https://github.com/youraccount/yii2/"
        },
change 
    "yiisoft/yii2": "x.x.x*",
to
    "yiisoft/yii2": "dev-master", or     "yiisoft/yii2": "dev-yourbranch",

### What is the expected result?
with this same exact procedure I managed to composer update many packages for example fedemotta datatables with my own forked one
### What do you get instead?

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
  - Updating cebe/markdown (1.1.2 => 1.2.1): Loading from cache
  - Removing yiisoft/yii2 (2.0.15.1)
  - Installing yiisoft/yii2 (dev-master a481cea): Cloning a481cea from cache
    a481cea is gone (history was rewritten?)
    Failed to download yiisoft/yii2 from source: Failed to execute git checkout "a481cea" -- && git reset --hard "a481cea" --

fatal: invalid reference: a481cea

    Now trying to download from dist
  - Installing yiisoft/yii2 (dev-master a481cea): Downloading (failed)

  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/yiisoft/yii2-framework/zipball/a481cea" file could not be downloaded (HTTP/1.1
   302 Found)

### Additional info

tried this same procedure with other packages and worked fine, only not working on yii2 fork, are there additional step to adopt?

example results form same fork i made on fedemotta datatables:
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing fedemotta/yii2-widget-datatables (v1.3)
  - Installing fedemotta/yii2-widget-datatables (dev-master 0fc4fe0): Cloning 0fc4fe00f3 from cache
Writing lock file
Generating autoload files

**Comment by samdark** [comment]
Fork https://github.com/yiisoft/yii2-framework subsplit instead.
