### ISSUE TITLE
pgsql: operator does not exist: character varying = integer

### ISSUE THREAD

**Issue by semsty** [yiisoft/yii2#16461]
### What steps will reproduce the problem?

Set `emulatePrepare=true` in db component config

Execute query:

```
Model::find()->where(['title' => 1])->one()
```

Where `title` column has type string

```
db=# select column_name, data_type from information_schema.columns where table_name = 'table';
  column_name   |     data_type     
----------------+-------------------
...
 title          | character varying
...
```

### What is the expected result?

SQL Query:

```
SELECT * FROM "table" WHERE "title"='1'
```

### What do you get instead?

SQL Query:

```
SELECT * FROM "table" WHERE "title"=1
```

And exception

```
yii\db\Exception with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer
LINE 1: SELECT * FROM "table" WHERE "title"=1
                                          ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
The SQL being executed was: SELECT * FROM "table" WHERE "title"=1'
```

Every time explicitly indicate the type is inconvenient :(

### What helped

https://github.com/yiisoft/yii2/blob/master/framework/db/Schema.php#L266

```
...
'integer' => \PDO::PARAM_STR,
...
```

In overridden schema class

When searching by a string value on a numeric column, there is no error

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.2.3
| Operating system | Debian GNU/Linux 9
| PostgreSQL | 9.6.6

**Comment by Eloy-Gonzalez** [comment]
Hi, try using quote literals on value in clausule where  

Example

`$query = Model::find()->where(['title' => "1"])->one()`

**Comment by samdark** [comment]
Indeed, types matter.
