### ISSUE TITLE
Impossible to update columns from other

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2#16463]
### What steps will reproduce the problem?
1. Create migration.
2. In safeUp method add update query.

```php
$this->addColumn(
    '{{%payment_methods}}',
    'sort',
    $this->tinyInteger(3)->notNull()->defaultValue(0)
);

// I guess Migration has a special method to do it exept query + foreach.
$this->update(
    '{{%payment_methods}}',
    ['sort' => 'id'],
);
```

### What is the expected result?
| Id | Sort
| - | -
| 1 | 1
| 2 | 2
| 3 | 3

### What do you get instead?
| Id | Sort
| - | -
| 1 | 0
| 2 | 0
| 3 | 0

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | Ubuntu 17.10

**Comment by samdark** [comment]
Have you tried wrapping values with https://www.yiiframework.com/doc/api/2.0/yii-db-expression?

**Comment by springimport** [comment]
@samdark No. I just used `execute()`.
```php
$this->execute('UPDATE {{%payment_methods}} set sort = id');
```

But I tested `Expression` and it also works!
```php
$idColumnExpression = new Expression('id');
$this->update(
    '{{%payment_methods}}',
    ['sort' => $idColumnExpression]
);
```
