### ISSUE TITLE
View events

### ISSUE THREAD

**Issue by dev4yii2** [yiisoft/yii2#16472]
I'm trying to handle [View::EVENT_BEFORE_RENDER](https://github.com/yiisoft/yii2/blob/master/framework/base/View.php#L42) event exactly for `SiteController/actionIndex` pair.
Just for test I created a component named app\components\TestComponent (and I added it to components and bootstrap sections of app config file)

```php
namespace app\components;

use app\controllers\SiteController;
use yii\base\Event;
use yii\base\View;
use yii\base\Component;

class TestComponent extends Component
{
    public function init()
    {
        parent::init();
        Event::on(SiteController::className(), SiteController::EVENT_BEFORE_ACTION, function ($event) {
            if ($event->action->id==='index') {
                $event->sender->view->on(\yii\base\View::EVENT_BEFORE_RENDER, function ($e) {
                    // some code
                    var_dump($e->sender);
                });
            }
        });
    }
}
```

but code inside `$event->sender->view->on` was called twice: for view and for layout. I think this problem is in \yii\base\Controller in method renderContent. Layout render not as new instance of `View` class but in the same instance of `View` ( [here](https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L399) ).

I'm not sure but I think this is a bug.

P.S. Sorry for my english

**Comment by samdark** [comment]
As far as I remember it was made like that intentionally to share context variables between views and layouts.

**Comment by cebe** [comment]
this is expected, EVENT_BEFORE_RENDER is fired for every view file that is rendered, there could be more than only two.
