### ISSUE TITLE
Implicit conversion from data type char to varbinary(max) is not allowed

### ISSUE THREAD

**Issue by sdlins** [yiisoft/yii2#16479]
I have this RBAC migration:

```php
    public function safeUp()
    {
        /** @var \yii\rbac\DbManager $rbac */
        $rbac = \Yii::$app->get('authManagerAlteracaoDeCronograma');

        $solicitante = $rbac->createRole('solicitante');
        ...

        $rbac->add($solicitante); //error happens inside this
        ...
    }
```

That is resulting in this error:

```shell
*** applying m180704_153354_rbac_permissoes_e_regramento
Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Implicit conversion from data type char to varbinary(max) is not allowed. Use the CONVERT function to run this query.
The SQL being executed was: INSERT INTO [ALTERACAOCRONO_RBAC_ITEM] ([name], [type], [description], [rule_name], [data], [created_at], [updated_at]) VALUES ('solicitante', 1, NULL, NULL, NULL, 1530722672, 1530722672)
```

The most strange is that when I execute the sql pointed in the error right in the MSSQL manager it works fine.

I tryed to change the field `data` from the type `binary` to `string` and rerun the migration just to check the behavior and *it works fine* too. So I think that `QueryBuilder::normalizeTableRowData()` could be failing somehow that I still could not discover debugging the code.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.14
| Operating system | Win 10
| MSSQL |  2016

**Comment by samdark** [comment]
Try master.

**Comment by slinstj** [comment]
Did you mean `master` db? I didn't get you @samdark.

**Comment by samdark** [comment]
master branch of Yii instead 2.0.15.1

**Comment by slinstj** [comment]
Oh, sorry. I will try.

**Comment by slinstj** [comment]
Tried against a `dev-master` install and now the error message and the sql is different:

```shell
Exception: SQLSTATE[07002]: [Microsoft][ODBC Driver 13 for SQL Server]COUNT field incorrect or syntax error
The SQL being executed was: INSERT INTO [ALTERACAOCRONO_RBAC_ITEM] ([name], [type], [description], [rule_name], [data], [created_at], [updated_at]) VALUES (NULL, 1, NULL, NULL, CONVERT(VARBINARY, NULL), 1530815512, 1530815512) (C:\...\vendor\yiisoft\yii2\db\Schema.php:664)
```

**Comment by samdark** [comment]
Any idea what that means?

**Comment by slinstj** [comment]
Not really because I had not time to debug this time. But I will be able to debug within some minutes. I will update this answer after that.

**Comment by sdlins** [comment]
Closing since `normalizeTableRowData()` seems fixed by @marcelodeandrade.
