### ISSUE TITLE
schemeCache Does not seem to be working properly.

### ISSUE THREAD

**Issue by galieth** [yiisoft/yii2#16478]
I'm working on a Craft 3 CMS project that is built on the Yii Framework.  Locally it worked great.  We moved it to our Shared ENV and it started running really slow.  That lead me into tracking down what was taking so long in that env.   After finding these two reports of what was slowing down other's sites

https://github.com/craftcms/cms/issues/2539
Which lead to this thread: https://github.com/yiisoft/yii2/issues/15776

We enabled caching and the schemaCache which improved performance.  We have New Relic on the server and noticed that even with the schemaCache set to true it was still calling queries into the schema on every page load.  I looked into the redis Cache and I can see that the metadata is being saved but when it goes to get the data out it returns empty.  This happens because when the metadata is saved a TagDependency is being set on it.  When it runs the isChanged function on the cache object it returns that it has changed. 

```
yii\db\schema.php
Function: saveTableMetadataToCache
Line: 872
        $cache->set(
            $this->getCacheKey($name),
            $metadata,
            $this->db->schemaCacheDuration,
            new TagDependency(['tags' => $this->getCacheTag()])
        );
```

Here is an example of the two objects that are being compared in the cache object isChanged Function:

Current: Array
```
(
    [fe0eadd258c9604c6e4b21edc279977e] => 0.53279200 1530644770
)
```

Cached: Array
```
(
    [fe0eadd258c9604c6e4b21edc279977e] => 0.79131900 1530644726
)
```

The 1530644770  looks to be a timestamp, and I don't know what the first number is I didn't dive that far into it.

The code comment on CacheTag says it can be used to invalidate everything with that tag but from my experience it is invalidating on every page load which seems to be counter intuitive to what schemaCache should be doing.

Not sure if this is a bug in the CacheTag, the Dependency check, if the TagDependency shouldn't be on this metadata save, or if Craft 3 is setting the Cachetag incorrectly or too often. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.0.30-0ubuntu0.16.04.1
| Operating system | Linux

**Comment by samdark** [comment]
The only thing I can suggest for now is to take clean basic app of Yii 2, connect redis cache there and try setting cache items with TagDependency and then reading them. If that won't work it's a bug in Yii and we'll have a test case. If that would work it's a bug in Craft and @brandonkelly will take care of it, I guess.

**Comment by rob006** [comment]
This may be a redis extension bug, see https://github.com/yiisoft/yii2-redis/issues/156. Do you get the same behavior when you use different cache backend?

**Comment by galieth** [comment]
@samdark Noted I will try to get something created for a test case.

@rob006 It was also tried with Memcache with the same results.

**Comment by machour** [comment]
@galieth did you ever get to understand/fix the issue?

**Comment by galieth** [comment]
Not really. 

I know it happens on shared hosts where there are many databases on the system.  We ended up standing up a single database instance for each site to get around it.  I haven't had a chance to come back to this and look further into it.

**Comment by machour** [comment]
Ok. If you ever do, please re-open this issue.
