### ISSUE TITLE
Missleading function signature

### ISSUE THREAD

**Issue by MattRh** [yiisoft/yii2#16480]
Why do we have to pass `$row` here?
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1213
Isn't that a bug?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | any
| Operating system | any

**Comment by samdark** [comment]
For the purpose of overriding it. Single table inheritance and stuff like that.

**Comment by MattRh** [comment]
Is that "row" data or "raw" data?

**Comment by samdark** [comment]
"Row" as in database table.
