### ISSUE TITLE
Module routes not working

### ISSUE THREAD

**Issue by Quadrumkr** [yiisoft/yii2#16484]
### What steps will reproduce the problem?
add to routes
request /my-admin/blogs/
`'<module:my-admin>' => '<module>',
'<module:my-admin>/<controller>' => '<module>/<controller>',
'<module:my-admin>/<controller>/<action>' => '<module>/<controller>/<action>',
'<view:blog>/<url:[-\w]+>' => 'site/index',
'<view:landing>/<url:[-\w]+>' => 'site/index',
'/<url:[a-zA-Z0-9-/]+>' => 'site/index' //but work this rule
`

### What is the expected result?
I need work with all requests in "site/index" but without modules requests
### What do you get instead?
Can't get module by this routes
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1.
| PHP version      |  7.0.30-1+ubuntu18.04.1+deb.sury.org+1
| Operating system | Description:    Ubuntu 18.04 LTS

**Comment by RSalo** [comment]
Routes in module should be configured by bootstrapping.

**Comment by cebe** [comment]
@Quadrumkr I remember you asked about this in slack. I added tests to verify that this works: d0712e491

if something is not working that must be somehow specific to your application or config.
