### ISSUE TITLE
Move repository to yiisoft/framework

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#16482]
## Why

Since we're now following SemVer, Yii 2 version 3.0.0 sounds a bit weird. There is a way to fix it - move to yiisoft/framework [removing subsplit](https://github.com/yiisoft/yii2/issues/16160).

## How

1. Rename GitHub Repository yiisoft/yii2 to yiisoft/framework
2. Create Packagist package yiisoft/framework that should look on yiisoft/framework repository
3. In order to make existing packages that depend on yiisoft/yii2 work, subsplit yiisoft/yii2-framework and package name yiisoft/yii2 must be kept for 2.0.x versions. In 3.x versions of yiisoft/framework we must set yiisoft/yii2:self.version in "replaces" section of composer.json

**Comment by SamMousa** [comment]
Can we not use a virtual package to manage this?
IE make `yiisoft/yii2` a virtual package that depends on `yii/framework:2.0.x`?

**Comment by samdark** [comment]
No. We'll lose stats that way.

**Comment by SamMousa** [comment]
Not if you push an new tag to current repo with just the composer.json?

**Comment by samdark** [comment]
@SilverFire ?

**Comment by hiqsol** [comment]
@SamMousa what problem does your proposal solves?

**Comment by SamMousa** [comment]
No need for a subsplit I think; instead we just leave the last tag(s) in this repo with a single `composer.json` pointing to the latest 2.x version of the new repo.

**Comment by MattRh** [comment]
> In 3.x versions of yiisoft/framework we must set yiisoft/yii2:self.version in "replaces" section of composer.json
Is this only about 3.x versions or all >3.0 versions?

**Comment by rob006** [comment]
What will happen if I will have both `yiisoft/framework` and `yiisoft/yii2` in my `composer.json`?

	"require": {
		"yiisoft/yii2": "~2.0.5",
		"yiisoft/framework": "~2.0.5"
	},

AFAIK both packages will be installed independently, duplicating every class and creating namespaces conflicts.

**Comment by rob006** [comment]
> Same as you shouldn't add both yiisoft/yii and yiisoft/yii2 at a time

Why? I have app with both packages and it is working perfectly fine.

And I don't need to add `yiisoft/framework` and `yiisoft/yii2` myself. Some extensions may do this.

**Comment by hiqsol** [comment]
`yiisoft/framework` will have `replace` in composer.json so yii2 will not be installed when required from dependencies.
But I don't know exactly what will happen when you require both from single composer.json.

**Comment by samdark** [comment]
@SilverFire did tests with three points in the first post. We can wait for a week so you re-confirm it. Won't hurt.

**Comment by rob006** [comment]
I don't see `yiisoft/framework` package at packagist. How did you test it? You can create such package without actual renaming repo (which can be done after tests).

**Comment by samdark** [comment]
With a fake repo.

**Comment by rob006** [comment]
You mean this: https://github.com/peesoft ?

**Comment by samdark** [comment]
Yes.

**Comment by rob006** [comment]
Then I confirm, I want to do my own tests next week.

**Comment by rob006** [comment]
I think I found some problems which renaming package name may create and they look serious.

1. I created [`riisoft/framework`](https://packagist.org/packages/riisoft/framework) package and created new releases with new name - it should be equivalent to `yiisoft/framework`.
2. Created [`riisoft/some-extension`](https://packagist.org/packages/riisoft/some-extension) which requires `riisoft/framework: ~3.0 || ~2.0.15` - this simulates any extension, that could be compatible with both Yii 2.0 and Yii 3.0.
3. Created simple `composer.json` with dependencies:

    ```json
	{
	    "name": "riisoft/app",
	    "type": "project",
	    "require": {
		"php": ">=5.4.0",
		"yiisoft/yii2": "~2.0.14",
		"riisoft/some-extension": "^1.0.0"
	    },
	    "repositories": [
		{
		    "type": "composer",
		    "url": "https://asset-packagist.org"
		}
	    ]
	}
    ```
I would expect that only `riisoft/framework:2.0.16` will be installed, since I required `yiisoft/yii2:~2.0.14` and `riisoft/framework:2.0.16` replaces `yiisoft/yii2:~2.0.16`; and `riisoft/framework:2.0.16` is allowed by `riisoft/some-extension:1.0.0` constraints. This is how it should work. But it don't - I get `yiisoft/yii2:~2.0.15.1` and `riisoft/framework:3.0.0` installed separately:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing yiisoft/yii2-composer (2.0.7): Loading from cache
  - Installing cebe/markdown (1.1.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing riisoft/framework (3.0.0): Loading from cache
  - Installing bower-asset/jquery (3.2.1): Loading from cache
  - Installing bower-asset/yii2-pjax (2.0.7.1): Loading from cache
  - Installing bower-asset/punycode (v1.3.2): Loading from cache
  - Installing bower-asset/inputmask (3.3.11): Loading from cache
  - Installing ezyang/htmlpurifier (v4.10.0): Loading from cache
  - Installing riisoft/some-extension (1.0.0): Loading from cache
  - Installing yiisoft/yii2 (2.0.15.1): Loading from cache
    Skipped installation of bin yii for package yiisoft/yii2: name conflicts with an existing file
riisoft/framework suggests installing yiisoft/yii2-coding-standards (you can use this package to check for code style issues when contributing to yii)
Writing lock file
Generating autoload files

```

So basically I get Yii Framework installed two times with two incompatible versions: 2.0 and 3.0. Composer may load classes from random version and generating optimized autoloader generates hundreds of errors like:

```
Generating optimized autoload files
Warning: Ambiguous class resolution, "yii\filters\ContentNegotiator" was found in both "/home/robert/Poligon/yii-rename/app/vendor/riisoft/framework/framework/filters/ContentNegotiator.php" and "/home/robert/Poligon/yii-rename/app/vendor/yiisoft/yii2/filters/ContentNegotiator.php", the first will be used.
Warning: Ambiguous class resolution, "yii\filters\PageCache" was found in both "/home/robert/Poligon/yii-rename/app/vendor/riisoft/framework/framework/filters/PageCache.php" and "/home/robert/Poligon/yii-rename/app/vendor/yiisoft/yii2/filters/PageCache.php", the first will be used.
```

It seems to be related to Composer bug which makes `replace` completely unreliable. See https://github.com/composer/composer/issues/4808#issuecomment-173504192 and https://github.com/composer/composer/issues/3754

**Comment by hiqsol** [comment]
Please try what you get with * instead of self-version in replace.

**Comment by rob006** [comment]
1. Using `*` for `replace` looks definitely wrong since particular version of `riisoft/framework` does not replace all versions of `yiisoft/yii2`, but only one. If I require `yiisoft/yii2:2.0.8` it should be replaced exactly by `riisoft/framework:2.0.8` not `riisoft/framework:2.0.16` or other versions. 
2. It really doesn't matter, since `replace` info is taken from tag. So we would need to replace all existing tags to change `replace` declaration for all versions.

**Comment by SamMousa** [comment]
@rob

**Comment by rob006** [comment]
@SamMousa `conflict` should actually fix this issue if we use it correctly, but it needs to be defined in all tagged versions, so we would have to alter existing tags. Which is really nasty and could bring many other issues - tags should be permanent and you usually do not expect that they will change.

**Comment by SamMousa** [comment]
You can mark the new package as conflicting with all versions of  the old one.

**Comment by rob006** [comment]
You can mark **version** of a package as conflicting with all versions of different package. If I understand the plan correctly, we're going to rename this repo (`yiisoft/yii2`) to `yiisoft/framework` and then create package at Packagist named `yiisoft/framework` which will point to new-old `yiisoft/framework` repository. This will result in that all existing tags will be also available in new `yiisoft/framework` package. So `yiisoft/framework:2.0.8` will point to [this tag](https://github.com/yiisoft/yii2/releases/tag/2.0.8) and all `replace`/`conflict` settings should be defined in [`composer.json` of this tag](https://github.com/yiisoft/yii2/blob/2.0.8/composer.json).

**Comment by SamMousa** [comment]
Yes, but the new package can have a new tag upon release so unless people explicitly specify an existing tag with a new name, they'll get the new one which will have the conflict.

Anyone requesting the new package will get the latest stable by default so they will get proper warnings about the conflict.

**Comment by rob006** [comment]
> Anyone requesting the new package will get the latest stable by default so they will get proper warnings about the conflict.

They will get warning if their constraint cannot be resolved. But you still can get `yiisoft/framework:2.0.15.1` and `yiisoft/yii2:2.0.8` installed at the same time, since `yiisoft/framework:2.0.15.1` does not explicitly conflicts with any version of `yiisoft/yii2`.

**Comment by schmunk42** [comment]
I think this is fixed by having `yiisoft/yii-core` now.
