### ISSUE TITLE
Bug in Sort class

### ISSUE THREAD

**Issue by xunicorn** [yiisoft/yii2#16497]
Hi. I'm trying get simple grid view with complex sorting )

I'm using next code for ActiveDataProvider

```
$dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort'=> [
                //'defaultOrder' => ['date'=>SORT_DESC],
                'attributes' => [
                    'id',
                    'date',
                    'country',
                    'adCount',
                    'adDisabled',
                    'adRatio',
                ],
                'params' => ['tab' => 'ad', 'StatsSearch' => ['date' => $this->date], 'ad-sort' => ''],
                'sortParam' => 'ad-sort',
            ],
            'pagination' => [
                'pageSize' => 100,
            ],
        ]);
```
(main config in this code - Sort[params]). But when i try sort my gridView by any of specified parameter - my sort order is not changing. 
I found piece of code in Sort class, which corresponding for my issue. I'm posting result code where i commented redundant code.
**Sort class**

```
...
    public function getAttributeOrders($recalculate = false)
    {
        if ($this->_attributeOrders === null || $recalculate) {
            $this->_attributeOrders = [];
            //if (($params = $this->params) === null) {
                $request = Yii::$app->getRequest();
                $params = $request instanceof Request ? $request->getQueryParams() : [];
            //}
            if (isset($params[$this->sortParam])) {
                foreach ($this->parseSortParam($params[$this->sortParam]) as $attribute) {
                    $descending = false;
                    if (strncmp($attribute, '-', 1) === 0) {
                        $descending = true;
                        $attribute = substr($attribute, 1);
                    }
                    if (isset($this->attributes[$attribute])) {
                        $this->_attributeOrders[$attribute] = $descending ? SORT_DESC : SORT_ASC;
                        if (!$this->enableMultiSort) {
                            return $this->_attributeOrders;
                        }
                    }
                }
            }

            if (empty($this->_attributeOrders) && is_array($this->defaultOrder)) {
                $this->_attributeOrders = $this->defaultOrder;
            }
        }
        return $this->_attributeOrders;
    }
...
```
This code is redundant because method not check GET parameters if specified Sort::$params therefore sorting not happen.

Maybe i'm not understanding this logic and its not a bug - then forgive me

**Comment by rob006** [comment]
> This code is redundant because method not check GET parameters if specified Sort::$params therefore sorting not happen.

This is expected and documented:

> Parameters (name => value) that should be used to obtain the current sort directions and to create new sort URLs. If not set, $_GET will be used instead.

https://www.yiiframework.com/doc/api/2.0/yii-data-sort#$params-detail

Why you're using `params` if you want to get sort data from GET?

**Comment by xunicorn** [comment]
@rob006 I want add additional params to sorting url. But in sort class i can change only searchParam. How could i do it?

**Comment by rob006** [comment]
Merge your custom params with `$_GET`? There is a example in docs I've linked.
