### ISSUE TITLE
Doc for Filter Rule when using public function for Filter function

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii2#16494]
I think filter rule ( https://www.yiiframework.com/doc/guide/2.0/en/tutorial-core-validators#filter ) when using public function to create the filter function, must be documented with this clarification:

`['attr', 'filter', 'filter' => [$this, 'filterFunction']],`

because it can be interpret as 

`['attr', 'filter', 'filter' => 'filterFunction'],`

And it generate errors as this:
https://stackoverflow.com/questions/29493552/yii2-custom-filter-rule-without-anonymous-function

**Comment by samdark** [comment]
Agree. Do you want to fix it?

**Comment by nacesprin** [comment]
I don't know how to use GIT ¬_¬
Sorry

**Comment by cebe** [comment]
You can edit the files directly on github ;)
