### ISSUE TITLE
MySQL Schema unsafe behavior?

### ISSUE THREAD

**Issue by malsatin** [yiisoft/yii2#16498]
Is that ok to change array that we are iteration on?
https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/Schema.php#L265
May be it would be more predictable to write it to another array or to `$column->enumValues[$i]` directly? 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | any
| Operating system | any

**Comment by rob006** [comment]
It looks like bug for me. Does anyone know what is happening there?

**Comment by samdark** [comment]
It trims each value of the array. Not a bug.

**Comment by MattRh** [comment]
@samdark no, because it doesn't look like this
```php
                    foreach ($values as $i => $value) {
                        $values[$i] = trim($value, "'");
                    }
```
But in code from the issue stange overwriting is happening

**Comment by samdark** [comment]
No idea then, looks like a bug.

**Comment by samdark** [comment]
Would be great to reproduce its effects somehow.

**Comment by MattRh** [comment]
I have tested it with such code
```php
<?php

$type = "enum('pending','waiting','sold','buying','sending','sent','delivered','error')";
preg_match('/^(\w+)(?:\(([^\)]+)\))?/', $type, $matches);

var_dump($matches);

preg_match_all("/'[^']*'/", $matches[2], $values);

var_dump($values);

foreach ($values[0] as $i => $value) {
    $values[$i] = trim($value, "'");
}

var_dump($values);
```
Result is
```php
array(3) {
  [0]=>
  string(78) "enum('pending','waiting','sold','buying','sending','sent','delivered','error')"
  [1]=>
  string(4) "enum"
  [2]=>
  string(72) "'pending','waiting','sold','buying','sending','sent','delivered','error'"
}
array(1) {
  [0]=>
  array(8) {
    [0]=>
    string(9) "'pending'"
    [1]=>
    string(9) "'waiting'"
    [2]=>
    string(6) "'sold'"
    [3]=>
    string(8) "'buying'"
    [4]=>
    string(9) "'sending'"
    [5]=>
    string(6) "'sent'"
    [6]=>
    string(11) "'delivered'"
    [7]=>
    string(7) "'error'"
  }
}
array(8) {
  [0]=>
  string(7) "pending"
  [1]=>
  string(7) "waiting"
  [2]=>
  string(4) "sold"
  [3]=>
  string(6) "buying"
  [4]=>
  string(7) "sending"
  [5]=>
  string(4) "sent"
  [6]=>
  string(9) "delivered"
  [7]=>
  string卌 "error"
}
```
So, it shows, that this code actually works, but, as for me, it relies on unsafe php behavior, that it creates array copy for iteration and that may be changed in future

**Comment by samdark** [comment]
Yep. Better to rewrite it...
