### ISSUE TITLE
yii command hlep text  wordwrap  error

### ISSUE THREAD

**Issue by zxldev** [yiisoft/yii2#16509]
### What steps will reproduce the problem?
1. yii command action has ***long Chinese character*** comment
```php
   /**
     * 这是一个很长的中文注释测试这是一个很长的中文注释测试这是一个很长的中文注释测试
     * @access public
     * @return void
     */
    public function actionImport() {
    }
```
2. run ```./yii```

### What is the expected result?

run ```./yii``` will   output:

```shell
xxx/import                    这是一个很长的中文注释测试这是一个很长的中文注释测试这是一个很长的中文注释测试

```
or better

```shell
xxx/import                    这是一个很长的中文注释
                                      测试这是一个很长的中文
                                      注释测试这是一个很长的
                                      中文注释测试

```

### What do you get instead?
 output:
```shell
xxx/import                    这是一个很长的中文注释测�
                                           ��这是一个很长的中文注释�
                                           �试这是一个很长的中文注释
                                           测试

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | sine 2.0.4 
| PHP version     |  7.1
| Operating system |mac

delete the fourth paramter of ```wordwrap```  in ```\yii\helpers\BaseConsole::wrapText``` may help a little.

**Comment by samdark** [comment]
Seems to be connected to not using mb_substr and instead using substr.
