### ISSUE TITLE
Cannot send statusText anymore

### ISSUE THREAD

**Issue by ErwSim** [yiisoft/yii2#16501]
### What steps will reproduce the problem?
Set Yii::$app->response->statusText as a response of a rest request

### What is the expected result?
Response should have my value

### What do you get instead?
Response displays "OK" instead of my value

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | PHP 7.0.30
| Operating system | Debian 8

**Comment by Alex-Code** [comment]
Could you show a bit more of your action and if you use any other `Response` methods?
