### ISSUE TITLE
Will the official components consider supporting  swoole extension？

### ISSUE THREAD

**Issue by kcloze** [yiisoft/yii2#16518]
In the swoole env: initializes framework once and then handles requests/responses.
it will be  more faster and more  efficient. but the possibility of a problem is greater.
We very much hope that officials can support swoole extensions.

like this :
https://github.com/zendframework/zend-expressive-swoole

**Comment by wi1dcard** [comment]
似乎看出了中式英文的影子

**Comment by samdark** [comment]
We're going to have PSR-7 compatible request-response but I doubt we'll be able to support swoole since noone from core team uses it currently. We basically don't have any expertise and have no idea what it takes to support it. If you have an idea, let us know. Closing the issue for now.
