### ISSUE TITLE
gcSession not runing automatically

### ISSUE THREAD

**Issue by ered15** [yiisoft/yii2#16516]
### What is the expected result?
Need for yii2 to delete garbage in DB, it's suppose to  run gcSession automatically and clean expire rows on table  admin_session but it's not happening, I tried adding `Yii::$app->session->gcSession(1);` in actionIndex to test and it worked, but it should be triggerd automatically.

```
'session' => [
            'class' => 'yii\web\DbSession',
            // 'db' => 'mydb',  // the application component ID of the DB connection. Defaults to 'db'.
             'sessionTable' => 'admin_session', // session table name. Defaults to 'session'.
            'writeCallback' => function($session){
                return [
                    'user_id' => Yii::$app->user->id
                ];
            },
            'timeout' => 10,
        ],
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.0.29
| Operating system |

**Comment by rugabarbo** [comment]
gcSession method is called according to the **php.ini** settings:
* http://php.net/manual/ru/session.configuration.php#ini.session.gc-probability
* http://php.net/manual/ru/session.configuration.php#ini.session.gc-divisor

**Comment by cebe** [comment]
Note that `gc_probability` may be set to 0 in some configurations by default because sessions are cleaned up by a cronjob (e.g. on debian php installed via apt). You need to adjust PHP config for this to work.

**Comment by cebe** [comment]
Added a note to the guide.
