### ISSUE TITLE
Yii2 advanced: mode switching

### ISSUE THREAD

**Issue by skokov2006** [yiisoft/yii2#16513]
How can I switch from the dev to the prod? I am editing frontend/web/index.php:
    
    defined('YII_DEBUG') or define('YII_DEBUG', false);
    defined('YII_ENV') or define('YII_ENV', 'prod');

but debug panel is visible still...

**Comment by MattRh** [comment]
How did you configure Debug module?

**Comment by rustamwin** [comment]
`php init --environment=Production`
