### ISSUE TITLE
Yii2 Gridview not working with kartik Select2 multiselect !!!

### ISSUE THREAD

**Issue by rabdavinci** [yiisoft/yii2#16517]
Hi Dear developers!
My Yii2 Gridview not working with kartik Select2 multiselect !!!
Last item could not unselect!
Unselect all could not work too!
There is my code:
Model

`
public function rules()
    {
        return [
            [
                'multi_diet_param_id',
                'safe'
            ]
        ];
    }
if ($this->multi_diet_param_id != null && count ($this->multi_diet_param_id)>0) {
            $query->andFilterWhere( ['in', 'diet_id', $this->multi_diet_param_id ]);
}
`
Controller:
`
        $searchModel = new ItemSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
`
VIew:
`
use backend\components\grid\GridView;
use kartik\widgets\Select2;
$offerList = [1 => 'fist item', 2 => 'second item', 3 => 'third item'];
$form = ActiveForm::begin();
$panelBeforeTemplate = <div class="pull-right"><div class="btn-toolbar kv-grid-toolbar" role="toolbar"> {toolbar} </div>   </div>
    {before}
    <div class="custom-grid-filter" style="width:85%">
    <div style="width:15%;">'$form->field($searchModel, 'multi_diet_param_id')->widget(Select2::class, [
         'data' => $offerList,
         'options' => [
             'placeholder' => 'Eingetragen durch...',
             'multiple' => true
         ],
         'pluginOptions' => [
             'allowClear' => true,
         ],
     ]).'</div>
    </div>
    <div class="clearfix"></div>
    ';
echo GridView::widget([
    'id' => 'restaurant',
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'instructionRef' => 'manage,
    'panelBeforeTemplate' => $panelBeforeTemplate,
    'formatter' => [
        'class' => Formatter::class,
        'nullDisplay' => '',
    ],
    'filterSelector' =>
          ", #" . Html::getInputId($searchModel, 'multi_diet_param_id')
    ,

    'actionButtons' => [
        [
            'text' => 'Create',
            'url' => [
                'create'
            ],
            'visible' => true
        ]
    ],
    'columns' => $columnsConfig,
]) 
`

I see that last item does not disappeaer from url when i deselected lst item or unselected all:
http://admin.dh.local/item/item/index?itemSearch%5Bmulti_diet_param_id%5D%5B%5D=1

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.2
| Operating system | *

**Comment by rugabarbo** [comment]
Report about it here: https://github.com/kartik-v/yii2-widget-select2/issues/new
This is not a framework problem.

**Comment by rustamwin** [comment]
related [kartik-v/yii2-widget-select2#145](https://github.com/kartik-v/yii2-widget-select2/issues/145)

**Comment by samdark** [comment]
Please report to kartik-v/yii2-widget-select2
