### ISSUE TITLE
`resolveCallableDependencies` is not supported callable object.

### ISSUE THREAD

**Issue by wi1dcard** [yiisoft/yii2#16514]
### What steps will reproduce the problem?

1. Create a invokable class:

```php
class Foo
{
    public function __invoke()
    {
        return new \stdClass();
    }
}
```

2. Call `Yii::createObject`:

```php
$stdClassInstance = \Yii::createObject(new Foo());
```

3.  An error shows: `ReflectionFunction::__construct() expects parameter 1 to be string, object given`.

### What is the expected result?

`$stdClassInstance` is an instance of `stdClass`.

### What do you get instead?

Yii use `is_callable` to check if a param is a `callable` or not, but in `yii\di\Container::resolveCallableDependencies` function, simply use `is_array` to check the `callable` is a method or function.

In PHP Documentation, a [callable](http://php.net/manual/en/language.types.callable.php) was defined as 6 types.

So, if there was a object which has `__invoke` method, that will be a `callable` in PHP, but it's not a array.

It should be easy to fix. In my environment, I just add 2 lines in `resolveCallableDependencies` (See commented lines):

```php
        if (is_array($callback)) {
            $reflection = new \ReflectionMethod($callback[0], $callback[1]);
        // } elseif (is_object($callback)) {
        //     $reflection = new \ReflectionMethod($callback, '__invoke');
        } else {
            $reflection = new \ReflectionFunction($callback);
        }
```

That's works for me.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | >=2.0.7
| PHP version      | 7.0
| Operating system | macOS

**Comment by SamMousa** [comment]
Looks valid to me, @wi1dcard you up for making a PR with a test case?

**Comment by wi1dcard** [comment]
Added a test case and fixed this bug, TBR :D
