### ISSUE TITLE
Add boolean $alwaysTrim field to yii\data\DataFilter

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii2#16512]
Currently DataFilter takes search attribute values without trimming by default. So if I want to trim values then I need to add trim validator to search model. Value trimming is almost always needed. What about adding at least field that can be set in ActiveController:

```php
$actions['index']['dataFilter'] = [
    'class' => \yii\data\ActiveDataFilter::class,
    'alwaysTrim' => true,
```
I would think that it would be a good idea to make `$alwaysTrim = true` as default but then it will break backward compatability.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.15
| Operating system |Ubuntu 14.04.5 LTS

**Comment by samdark** [comment]
That would make ActiveDataFilter to take care of trimming that isn't its direct responsibility.
