### ISSUE TITLE
How to dynamically close a session in a module？

### ISSUE THREAD

**Issue by seakk** [yiisoft/yii2#16526]
I don't want to create a new api application, I just want to use a api module, dynamically modify the session configuration when accessing the api module has reached the session component is not enabled.
App lifecycle events:
```
'on beforeRequest' => function ($event) {
...
}
```
Viewing through debug is after the " yii\web\Session::open (Session started)" component is started.

How should I dynamically modify the app configuration in the module to reach the session component not enabled?
 
Thanks.

**Comment by mgrechanik** [comment]
@seakk  you should try forums to ask questions.
Issues is not for this !

**Comment by SamMousa** [comment]
@seakk could you not just configure a new component in the module config?
I do it in my module like this:
```php
        $this->setComponents([
            'user' => [
                'class' => User::class,
                'identityClass' => Key::class,
                'enableSession' => false,
                'loginUrl' => null
            ]
        ]);
```

**Comment by seakk** [comment]
@SamMousa  thanks, Let me try

**Comment by seakk** [comment]
```
'components' => [
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
            'enableSession' => false,
            'identityCookie' => ['name' => '_identity-frontend', 'httpOnly' => true],
        ]
]
```
The enableSession parameter is true by default, but it should be false. If you don't pay attention, when you use resful in the module, opening the session is an extra overhead. Because when you use Yii::$app->session, it automatically starts sesion
，I can only set false to disable automatic startup, I don't want to rewrite the class implementation.

**Comment by seakk** [comment]
I think I am wrong, closing enableSession will result in failure to log in, because the app configuration is public, so the problem is not solved.
