### ISSUE TITLE
Wrong order of parameters in @var in view files

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2#16524]
> ### @var
> You may use the @var tag to document the “Type” of properties, sometimes called class variables.
> ### Syntax
> @var [“Type”] [$element_name] [<description>]
> ### Examples
> ```php
> class Foo
> {
>   /**
>    * @var string $name        Should contain a description
>    * @var string $description Should contain a description
>    */
>   protected $name, $description;
> }
> ```

[phpDocumentor](http://docs.phpdoc.org/references/phpdoc/tags/var.html)

### What steps will reproduce the problem?
Open any view file in framework.

### What is the expected result?
```php
/* @var \yii\web\View $this */
/* @var \yii\gii\generators\module\Generator $generator */
```

### What do you get instead?
```php
/* @var $this yii\web\View */
/* @var $generator yii\gii\generators\module\Generator */
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1

**Comment by samdark** [comment]
Because it's not phpdoc, it's vardoc.

**Comment by springimport** [comment]
@samdark Okay, but what about moving to phpdoc syntax?

**Comment by rob006** [comment]
@springimport  At least some time ago vardoc has better IDE support. And it is still not clear whether using phpdoc in such way is valid - phpdoc should proceed structural element, which does not exist in this case.

**Comment by springimport** [comment]
@rob006
`\yii\bootstrap\Nav`, phpdoc:
```php
/** @var Widget $dropdownClass */
```
`yii\db\ActiveQuery`, vardoc:
```php
/* @var $modelClass ActiveRecord */
```
`yii\console\controllers\HelpController`, ??:
```php
/** @var $controller Controller */
```

**Comment by samdark** [comment]
As @rob006 said, neither is phpdoc. Phpdoc can't be applied to inline variables according to its specifications.

**Comment by springimport** [comment]
@samdark I think it will be good to have single format in yii.

**Comment by samdark** [comment]
Yes. Should be `/* @var $modelClass ActiveRecord */` but technically vardoc allows both. If you have some free time to burn, feel free to submit a pull request.
