### ISSUE TITLE
[DOCS] Broken/missing picture

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii2#16521]
https://www.yiiframework.com/extension/yiisoft/yii2-app-advanced/doc/guide/2.0/en/structure-environments

At the end of the page there is a broken picture:

![image](https://user-images.githubusercontent.com/542107/42735670-bc237288-8858-11e8-90d0-5e63e248c5db.png)

Looking at the repository, the image seems to be there at the expected path, so I don't know what is wrong.

**Comment by samdark** [comment]
Moved.
