### ISSUE TITLE
Database connection charset

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#16530]
Currently the `yii\db\Connection` class has DBMS specific code for setting the charset.
Instead this should be moved to the respective `Schema` classes.

```php
    protected function initConnection()
    {
        ...
        if ($this->charset !== null && in_array($this->getDriverName(), ['pgsql', 'mysql', 'mysqli', 'cubrid'], true)) {
            $this->pdo->exec('SET NAMES ' . $this->pdo->quote($this->charset));
        }
        $this->trigger(self::EVENT_AFTER_OPEN);
    }
```

A better solution would be to have the `Schema` initiate the character set, or more generic the connection. This could be done by simply initiating it in `initConnection()`:
```php
protected function initConnection()
    {
        $this->getSchema();
        $this->trigger(self::EVENT_AFTER_OPEN);
    }
```

- The schema can do any initialization needed.
- Schema object construction is cheap.
- fully BC compatible.

**Comment by samdark** [comment]
It's not connected to schema. Could be moved to specific connection classes though.

**Comment by SamMousa** [comment]
It is DBMS specific though; different DBMS can have different way of setting the charset

**Comment by SamMousa** [comment]
@samdark Currently the schema classes contain all DBMS specific code, does it not make more sense to have it in there than in the current `Connection` class?
The downside of having multiple connection classes is that the current approach of just changing the DSN no longer works. 
Specifically the DSN, username and password are often provided via external configuration, while the rest of the connection configuration is done in the code.
