### ISSUE TITLE
Formatter asDate() return wrong number

### ISSUE THREAD

**Issue by sobhan93** [yiisoft/yii2#16539]
`\Yii::$app->formatter->asDate(time(), 'php:t')` return current date.
I think formatter should return number of days in the current month.

`echo \Yii::$app->formatter->asDate(time(), 'php:t')`

### What is the expected result?
31
### What do you get instead?
20180719 09:49 PM

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.6
| Operating system | Windows 7 + XAMPP

**Comment by samdark** [comment]
`t` in PHP indeed stands for "Number of days in the given month".

**Comment by bizley** [comment]
Not supported by ICU and already [mentioned in code](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFormatConverter.php#L284).

I guess this should work as equivalent

    Yii::$app->formatter->asDate('last day of this month', 'd');

**Comment by rob006** [comment]
What is the reason of converting PHP date format to ICU?

**Comment by bizley** [comment]
To use features of `IntlDateFormatter` when `intl` is loaded. PHP date format works here as a fallback if `intl` is not available.

**Comment by rob006** [comment]
What features?

**Comment by bizley** [comment]
[Here](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L748-L772) is implementation. Locale based date parsing.

**Comment by rob006** [comment]
Any example? I still can't imagine situation where I want to specify format using `php:` prefix and use `IntlDateFormatter` features.

**Comment by bizley** [comment]
Well, I agree with you.
@samdark was it made like this for consistency?

**Comment by samdark** [comment]
@cebe implemented it...

**Comment by cebe** [comment]
you can use the PHP format if you want, but you can not use every PHP formatting feature. Intl formatter is better in formatting dates locale-aware. The format conversion is used if you use jquery data picker and similar stuff on the frontend, some use php format, jquery even has its own format, so we allow specifying the format in different ways so that backend and frontend as well as validator use the same specification.

In the case of this issue there is no point in using the Yii formatter, if you only need the number of days in the current month, you can just use `date('t')`. The formatter is meant to be used to format dates for display to users.

**Comment by rob006** [comment]
@cebe It still does not explain what is the point of converting PHP format to ICU. If someone wants to use `IntlDateFormatter` features, he will not use `php:` prefix.
And `t` is only one of many unsupported formats that does not work because of current implementation.

**Comment by sobhan93** [comment]
I need the number of days in the persian calendar.

'formatter' => [
    'locale' => 'fa_IR@calendar=persian',
    'calendar' => \IntlDateFormatter::TRADITIONAL,
],
\Yii::$app->formatter->asDate(time(), 'php:t')

**Comment by sobhan93** [comment]
@cebe
@samdark

**Comment by cebe** [comment]
> I need the number of days in the persian calendar.

it's simply not supported by intl. Not sure there is a way to add it. If anyone has ideas about how we can add it feel free to propose ideas.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
