### ISSUE TITLE
Inject Request to action params

### ISSUE THREAD

**Issue by exileed** [yiisoft/yii2#16541]
### What do you get instead?

Allows inject  Request in action method

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

Is bugfix? | no
-- | --
New feature? | yes
Breaks BC? | no
Tests pass? | yes
Fixed issues | no

Example 
  ```
 public function actionSave(yii\web\Request $request)
    {
        $params  = $request->getBodyParams();

        //
    }
```

like in Laravel https://laravel.com/docs/5.6/requests#accessing-the-request

**Comment by jomonkj** [comment]
use $model->load(Yii:$app->request->post());

**Comment by exileed** [comment]
@jomonkj I dont want to use the service locator. This is a bad practice.

**Comment by rob006** [comment]
This was already rejected, something similar is planned for 3.0: https://github.com/yiisoft/yii2/issues/13922
