### ISSUE TITLE
urlrules no works ModelSearch%5Bid%5D - [yii 3].

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/yii2#16540]
I have been working with yii 3.0 and everything works as it should, but I have not been able to make this rule work in the url which should work since the special characters are written in words.

```
urls.php:

return [
    [
        'pattern' => 'terminal/index/<ModelSearch%5Bid%5D:\d+>',
        'route' => 'terminal/index',
    ],
]

```
| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      | 7.1.17 
| Operating system | Centos 7

**Comment by rob006** [comment]
I'm not sure how this supposed to work. `ModelSearch[id]` is not a valid get param name, it will be translated as array (`['ModelSearch' => ['id' => '']]`).
