### ISSUE TITLE
Cached relatation is not used in relation through `via`

### ISSUE THREAD

**Issue by drlibra** [yiisoft/yii2#16552]
Hello.
I noticed that if relation is requested with a `via` option, there isn't any check that intermediate relation might be populated already. Consider this code of `ActiveQuery`:

            } elseif (is_array($this->via)) {
                // via relation
                /* @var $viaQuery ActiveQuery */
                list($viaName, $viaQuery) = $this->via;
                if ($viaQuery->multiple) {
                    $viaModels = $viaQuery->all();
                    $this->primaryModel->populateRelation($viaName, $viaModels);
                } else {
                    $model = $viaQuery->one();
                    $this->primaryModel->populateRelation($viaName, $model);
                    $viaModels = $model === null ? [] : [$model];
                }
                $this->filterByModels($viaModels);
            }

Maybe it would be useful to add the check that relation is populated in this manner:

            } elseif (is_array($this->via)) {
                // via relation
                /* @var $viaQuery ActiveQuery */
                list($viaName, $viaQuery) = $this->via;
                if ($viaQuery->multiple) {
                    if ($this->primaryModel->isRelationPopulated($viaName)) {
                        $viaModels = $this->primaryModel->$viaName;
                    } else {
                        $viaModels = $viaQuery->all();
                        $this->primaryModel->populateRelation($viaName, $viaModels);
                    }
                } else {
                    if ($this->primaryModel->isRelationPopulated($viaName)) {
                        $model = $this->primaryModel->$viaName;
                    } else {
                        $model = $viaQuery->one();
                        $this->primaryModel->populateRelation($viaName, $model);
                    }
                    $viaModels = $model === null ? [] : [$model];
                }
                $this->filterByModels($viaModels);
            }

**Comment by drlibra** [comment]
I can do a pull request. Can it be in 2.0 or it should be in 3.0?

**Comment by samdark** [comment]
Reverted the fix since it was breaking another thing. See https://github.com/yiisoft/yii2/pull/16588#issuecomment-419568470

**Comment by drlibra** [comment]
I didn't see that the code in Docker is not dynamic, so any changes on the host is not visible in the container. Therefore I didn't see any changes in tests after my changes of the code.
I'll try to fix it ASAP.
