### ISSUE TITLE
send post actioncontroller no works. yii 3.0.

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/yii2#16553]
### What steps will reproduce the problem?

```
Button Filter Gridview:

Html::button(
    Html::tag('i', '', ['class' => 'fas fa-filter']), 
    ['id' => 'filter-checked-btn', 'class' => 'btn bgc-blue-500 mL-2 simple text-white', 'title' => \yii::t('tadweb', 'Filter')]
),

GridView:

<?= Gridview::widget([
    'columns' => [
        'tbltb01',
        [
            '__class' => \yii\grid\CheckboxColumn::class,
        ],
    ],
    'dataProvider' => $dataProvider,
    'id' => 'grid-terminal',
]); ?>

JS:

<?php $this->registerJs("(function () {
    $('#filter-checked-btn').click(function () {
        var ids = $('#grid-terminal').yiiGridView('getSelectedRows');
        alert('Ids: ' + ids);
        $.post({
            type: 'POST',
            url: '/tadweb/terminal/index',
            data: {keylist: ids},
            dataType: 'json'	
	});
    });
})();");

```
### What is the expected result?

You should receive keylist via post controller.

Note: actionIndex: \yii::$app->controller->enableCsrfValidation = false;

$_POST is null.

| Q                | A
| ---------------- | ---
| Yii version      | 3.0.
| PHP version      | 7.1.17 
| Operating system | Centos 7

**Comment by Alex-Code** [comment]
Is the `POST` request getting sent?
Do you have an inspector/developer tool in your browser to verify.

**Comment by tecnoterabyte** [comment]
Add image firebug.

![image](https://user-images.githubusercontent.com/12988135/43134338-c023f7f0-8f0f-11e8-9705-263ae0e24e2d.png)

**Comment by Alex-Code** [comment]
Can you show your action?

**Comment by tecnoterabyte** [comment]
index

**Comment by tecnoterabyte** [comment]
Now doing several tests and using the code with form and csrf work perfect:

```
<?php $this->registerJs("
(function () {
	$('#filter-checked-btn').click(function() {
    	var ids = $('#grid-terminal').yiiGridView('getSelectedRows');
		url = '/tadweb/terminal/index';
        
		if (!ids.length) {
			alert('Please select one or more items from the list.');
			} else if (url) {
				var form = $('<form action=' + url + ' method=\"post\"></form>'),                
					csrfParam = $('meta[name=csrf-param]').prop('content'),
					csrfToken = $('meta[name=csrf-token]').prop('content');

			if (csrfParam) {
				form.append('<input type=\"hidden\" name=' + csrfParam + ' value=' + csrfToken + ' />');
			}
							
			$.each(ids, function(index, id) {
				form.append('<input type=\"hidden\" name=\"' + 'ids' + '[]\" value=' + id + ' />');
			});
        
			form.appendTo('body').submit();
		}
	});
})();
");
```

The other thing that I noticed if in the form you put POST method in upper case and in the botton is in lowercase will not work, you must match exactly both the property and its value is in both method = post or method = POST.

**Comment by rustamwin** [comment]
> $ids = \yii::$app->request->post('ids');
here should be `keylist`

**Comment by tecnoterabyte** [comment]
Although they closed the issue, it does not work, and it is verified by the CsrfValidation, they can check and see that no value passes in post.

**Comment by rustamwin** [comment]
> $.post({
            type: 'POST',
            url: '/tadweb/terminal/index',
            data: {keylist: ids},
            dataType: 'json'	
	});

send data with `csrf`
```
$.post({
            type: 'POST',
            url: '/tadweb/terminal/index',
            data: {keylist: ids, _csrf: yii.getCsrfToken()},
            dataType: 'json'	
	});
```
