### ISSUE TITLE
$query->limit(1)->one()

### ISSUE THREAD

**Issue by apomeran** [yiisoft/yii2#16561]
Hi! I would like to ask if the following 

 **$activeQuery->orderBy('id DESC')->limit(1)->one();**

results more effective than

 **$activeQuery->orderBy('id DESC')->one();**

I will later try benchmark results

**Comment by mgrechanik** [comment]
Yes, it is.

There ia a note about it in the [documentation ](https://www.yiiframework.com/doc/guide/2.0/en/db-active-record)
