### ISSUE TITLE
Lazy Dependency Injection of Class Members

### ISSUE THREAD

**Issue by bhagwatchouhan** [yiisoft/yii2#16567]
Is it possible to have lazy dependency injection of Class Members via getter methods as explained below:

1. Register the Class using set method of Container. Also register the class member and it's corresponding getter method and associate the Interface or Class to be initialized as method parameter.

2. Create the associated Object or find from already initialized singleton when the getter method called first time.

**Major Issue**:

We can have cyclic dependencies while using multiple modules via Constructor Injection and sometimes it's too heavy to provide all dependent objects via constructor.

If we have support to initialize the class members via getter dependency injection, the cyclic dependency issue can be resolved and a member can be dynamically initialized based on method signature.

**Possible Solution**:

It's somewhat similar to Spring Frameworks @Autowired in Java where we annotate a Class Member by corresponding interface/class to be initialized.

**Comment by samdark** [comment]
Not going to be solved in Yii 2.0. There's https://github.com/yiisoft/di though that has cyclic dependencies detection and will be used in Yii 3.0.

**Comment by bhagwatchouhan** [comment]
Thanks for the reply. Will wait for Yii 3.0.
