### ISSUE TITLE
TimestampBehavior docs and MySQL strict mode

### ISSUE THREAD

**Issue by KnightYoshi** [yiisoft/yii2#16560]
The docs for this mention using the Expression class to use the database's NOW function when using a _datetime_ field. 

> // if you're using datetime instead of UNIX timestamp:
> // 'value' => new Expression('NOW()'),

In non-strict mode the timestamp field will accept a UNIX timestamp.

However, when the database is in strict mode, a timestamp field will not accept the UNIX timestamp returned by the TimestampBehavior class. 

My local machine is not in strict mode and one of our test servers is. This caused inconsistent behavior and took a little while to realize what was happening.

### What steps will reproduce the problem?
MySQL 5.7 in strict mode
Have a timestamp field on a table
Use the default UNIX timestamp value returned by the TimestampBehavior class

```
UPDATE `theme` SET `featured_on`='1532025711', `rating`='3', `css`='sh: 1: sassc: not found', `review_count`=1 WHERE `id`=227
```

### What is the expected result?
I expected a database insert/update

### What do you get instead?
A database error was thrown.
```
Invalid datetime format: 1292 Incorrect datetime value: '1532025711' for column 'featured_on'
```

### Additional info
```
+---------------+--------------------------------------------+------+-----+-------------------+-----------------------------+
| Field         | Type                                       | Null | Key | Default           | Extra                       |
+---------------+--------------------------------------------+------+-----+-------------------+-----------------------------+
| featured_on   | timestamp                                  | YES  |     | NULL              |                             |
+---------------+--------------------------------------------+------+-----+-------------------+-----------------------------+
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7
| Operating system |

**Comment by samdark** [comment]
I don't see how we can document it better since it's MySQL specific and behavior is not.
