### ISSUE TITLE
Target adds invalid context message

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#16565]
### What steps will reproduce the problem?
In the `Logger` class the format of a log message is defined as follows:
```php
/**
     * @var array logged messages. This property is managed by [[log()]] and [[flush()]].
     * Each log message is of the following structure:
     *
     * ```
     * [
     *   [0] => message (mixed, can be a string or some complex data, such as an exception object)
     *   [1] => level (integer)
     *   [2] => category (string)
     *   [3] => timestamp (float, obtained by microtime(true))
     *   [4] => traces (array, debug backtrace, contains the application code call stacks)
     *   [5] => memory usage in bytes (int, obtained by memory_get_usage()), available since version 2.0.11.
     * ]
     * ```
     */
    public $messages = [];
```

However in `Target::collect()` a context message is appended:
```php
...
    if (($context = $this->getContextMessage()) !== '') {
        $this->messages[] = [$context, Logger::LEVEL_INFO, 'application', YII_BEGIN_TIME];
    }
...
```

### What is the expected result?
All messages passed to `export()` should have a proper format. (array of length 6)

### What do you get instead?
The first message has length 4.

### Proposed solution
I propose adding the missing 2 elements.

**Comment by rob006** [comment]
Related: https://github.com/yiisoft/yii2/issues/16251#issuecomment-388759422

**Comment by SamMousa** [comment]
I noticed it when creating a new target that uses the indexes given in the documentation, I got errors since the elements in the array were missing.
It's a problem in the sense that the documentation deviates from the implementation...
It's an easy fix to add the missing entries.

**Comment by samdark** [comment]
I'm fine with that.

**Comment by nkostadinov** [comment]
I also have problem with this issue. The context message bypasses the filter of messages and always adds to the DB although I have set filter by category. It is added after the filter.
