### ISSUE TITLE
Formatter->asSize.Wrong translate to russian 

### ISSUE THREAD

**Issue by zxczxc12** [yiisoft/yii2#16579]
Yii::$app->formatter->asSize(9685)

9,458 кибибайта

Что за кибибайты ???

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.3
| Operating system |CentOs 7

**Comment by lesha724** [comment]
@zxczxc12, посмотрите [здесь](https://dic.academic.ru/dic.nsf/ruwiki/965295)

**Comment by lesha724** [comment]
@zxczxc12, так же посмотрите [документацию ](https://www.yiiframework.com/doc/api/2.0/yii-i18n-formatter#asSize()-detail), там это описано. Вам нужно изменить свойство [sizeFormatBase](https://www.yiiframework.com/doc/api/2.0/yii-i18n-formatter#$sizeFormatBase-detail)

**Comment by zxczxc12** [comment]
спасибо !
