### ISSUE TITLE
Yii::$app->getRequest()->resolve() after Yii::$app->runAction($route)

### ISSUE THREAD

**Issue by letstestcode** [yiisoft/yii2#16585]
I have 2 controllers. I have done Yii::$app->runAction($route) from the action of the first controller to the action of the second controller. Then if I do Yii::$app->getRequest()->resolve() in the action of the second controller I receive the route of the action of the first controller.

**Comment by rob006** [comment]
Not a bug IMO. You didn't change request, so why `->resolve()` should return different result? The same request will be always resolved to the same controller.
