### ISSUE TITLE
MessageController (message/extract) does not delete files with removeUnused=true

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#16580]
### What steps will reproduce the problem?

1. PhpMessageSource
2. Files `messages/<language>/category/subcategory.php`:
```php
<?php
return [
    'Message' => 'Translation',
];
```
3. Source code to extract messages from does not contain anymore any messages the category `Yii::t('category/subcategory', ...)`;
4. `./yii message/extract message/config.php` so `removeUnused` is `true`

### What is the expected result?

Since there are no more messages in the category `category/subcategory`, I extect a deletion of files `messages/<language>/category/subcategory.php` (with directories becoming empty) or at least see any notice about such files or categories.

### What do you get instead?

Neither the files was deleted, nor notices are displayed.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | *
| Operating system | *

**Comment by samdark** [comment]
Indeed, deleting files isn't implemented.
