### ISSUE TITLE
BlameableBehavior defaultValue issue

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2#16584]
### What steps will reproduce the problem?
Attach `BlameableBehavior` to any model and set the `defaultValue` property
Try to save the model in console controller

### What is the expected result?
Values of `created_by` and `updated_by` should be populated with the `defaultValue` configured

### What do you get instead?
Values are set to null, and the DatabaseException on the NOT NULL fields is raised

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.7
| Operating system | CentOS 7

**Comment by evil1** [comment]
The root of the problem is that Console App does not have user component.
As a workaround I've modified default `getValue()` function in `yii\behaviors\BlameableBehavior`
The final function which currently works for me looks like this:
`protected function getValue($event)
    {
        if ($this->value === null && Yii::$app->has('user')) {
            $userId = Yii::$app->get('user')->id;
            if ($userId === null) {
                return $this->getDefaultValue($event);
            }

            return $userId;
        } elseif ($this->value === null) {
            return $this->getDefaultValue($event);
        };

        return parent::getValue($event);
    }`

**Comment by samdark** [comment]
Sounds logical. Would you please make a pull request?

**Comment by evil1** [comment]
Done.

**Comment by evil1** [comment]
I guess this one is the same issue #16505

**Comment by samdark** [comment]
Yes. Looks like so. That one wasn't merged because of lack of unit tests. Yours has the same issue ;)

**Comment by evil1** [comment]
@samdark It's my first pull request. Please give an advise where to put this test. Or any example of the same kind of test?
