### ISSUE TITLE
Why check action result not null?

### ISSUE THREAD

**Issue by Lexxtor** [yiisoft/yii2#16583]
https://github.com/yiisoft/yii2/blob/bc204e3160bc4bddf67b62dcfc174984ce0cfc2b/framework/web/Application.php#L109

```php
if ($result !== null) {
    $response->data = $result;
}
```
`$response->data` initially null, why not to write Null there again?

**Comment by cebe** [comment]
because in an action you could do:

```php
Yii::$app->response->data = 'something';
```

and then just not return anything from the action.
