### ISSUE TITLE
Unknown scenario exception

### ISSUE THREAD

**Issue by borodulin** [yiisoft/yii2#16598]
https://github.com/yiisoft/yii2/blob/001e4c5aed5c8e3ab93fe530bc96e80d83852208/framework/base/Model.php#L356-L358

Why do we need such an exception?

I have model
```php
class Contact extends \yii\db\ActiveRecord
{
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    public static function tableName()
    {
        return 'contact';
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['manager_id', 'type_id', 'ownership_id'], 'integer'],
            [['phones'], 'validatePhones', 'on' => self::SCENARIO_CREATE],
            [['manager_id'], 'validateManager', 'skipOnEmpty' => false, 'on' => self::SCENARIO_UPDATE],
        ];
    }
}
```
And I have Rest Controller
```php
class ContactController extends \yii\rest\ActiveController
{

    public $modelClass = 'common\models\Contact';

    public $createScenario = Contact::SCENARIO_CREATE;
    public $updateScenario = Contact::SCENARIO_UPDATE;`
}
```
If I need to disable validator on "manager_id" field in Contact model, then I have to remove $updateScenario from ContactController. It seems to me it is not convenient.

I wish to create a basic Controller class with predefined scenarios and use these scenarios in models whenever I want, but now it is impossible.

**Comment by mgrechanik** [comment]
> Why do we need such an exception?
because it is logical.

**Comment by borodulin** [comment]
it is not logical.

**Comment by rob006** [comment]
You want to use scenario that is unsupported by model?

**Comment by borodulin** [comment]
I think that there is no need to generate an exception if the model does not support the scenario.

**Comment by rob006** [comment]
Using unsupported feature does not make sense and should throw exception - it is usually unintended configuration error or simple typo. Ignoring this is not an option, it will hide errors and make debugging much harder. 

You can always override `scenarios()` to return all defined scenarios, even if there are not rules for the. Or just replace scenario name:

```php
const SCENARIO_UPDATE = self::SCENARIO_DEFAULT;
```
