### ISSUE TITLE
Strange behaviour with UploadedFile and FileValidator

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2#16595]
Hi.

I'm using Yii 2.0.15.1 on PHP 7.2 and I am trying to upload a file.

On ActiveRecord model, I configure the public attribute $file to be an instance of UploadeFile and I assign to it an instance of UploadedFile (file is a "file field"):
`$model->file = UploadedFile::getInstance($model, 'file');`

In the controller,  on invoking `$model->save();` goes to FileValidator and in ValidateValue, the attribute suddenly changes from UploadedFile to an empty string.

But sometimes this performance is not so; I mean, sometimes Model file attribute goes as an UploadedFile instance, but  majority goes as an empty string.

How i$file ends as string instead of Object instance?

**Comment by samdark** [comment]
By not submitting a file? Check the guide on how it should be done. There should be differences with your code.
