### ISSUE TITLE
`resetForm` does not clear inputs

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#16594]
### What steps will reproduce the problem?

 `$("#my-form").yiiActiveForm('resetForm');`

### What is the expected result?
clear the error messages and reset the input fields including the select-dropdown

### What do you get instead?
clears Messages for the form inputs but not the field values

I am submitting the form using ajax and want to clear/reset the form when the form is saved successfully but it clear the messages only. whereas in [`yii.activeForm.js`](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L437) we can see the line 

` var data = $form.data('yiiActiveForm');`

and then 

```
 window.setTimeout(function () {
      $.each(data.attributes, function () {
```
which means it iterates on all the attributes and clears the messages, can't we add the code to remove the values from the inputs too when we are clearing the messages it really looks odd to clear them manually after calling the `resetForm`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1.
| PHP version      | 5.6
| Operating system | Ubuntu

**Comment by mgrechanik** [comment]
You are supposeed to reset form like this:

`$('#formId').get(0).reset();`

**Comment by buttflattery** [comment]
@mgrechanik  i know we can use jquery for that but that would work with normal input fields, but if you have the select2 with multi and single select it does no reset them correctly and the placeholder remains there whereas the value if unset to empty string `''` which is really weird, try using it with ajax submission after the form is successfully saved  you will see that keeps showing the placeholders there but if you hit submit again with refreshing it shows you the prompt that the field cannot be empty where as the placeholder is stil there, i am ok to do a workaround but it should be supported from the Activeform.js to clear / reset the form.
