### ISSUE TITLE
PHP 7 ::class and AssetManager.bundles

### ISSUE THREAD

**Issue by shranet** [yiisoft/yii2#16607]
I don't know this bug or not!

I'm using https://github.com/froala/yii2-froala-editor in my project. If you see bellow code, jquery depends defined as '\yii\web\JqueryAsset'.

https://github.com/froala/yii2-froala-editor/blob/d88ae645f57b1aa6fccb1e87f78207e86785d0f1/src/FroalaEditorAsset.php#L46-L50

I use JqueryAsset in my project like this:

```
public $depends = [
    JqueryAsset::class
];
```

If I want to use .min version of Jquery, I need change AssetManager.bundles to (config/web.php):

```
'assetManager' => [
    'class' => 'yii\web\AssetManager',
    'bundles' => [
        '\yii\web\JqueryAsset' => [
            'js' => [
                YII_ENV_DEV ? 'jquery.js' : 'jquery.min.js'
            ]
        ]
    ]
]
```

In debug mode all works correctly, but in production mode works incorrectly.

<img width="536" alt="yii2-bug" src="https://user-images.githubusercontent.com/1712200/43676358-25d5cd42-9809-11e8-82dc-b97eb72b2107.png">

Now, to fix the error I use following code:
```
'assetManager' => [
    'class' => 'yii\web\AssetManager',
    'bundles' => [
        '\yii\web\JqueryAsset' => [
            'js' => [
                YII_ENV_DEV ? 'jquery.js' : 'jquery.min.js'
            ]
        ],
        'yii\web\JqueryAsset' => [
            'js' => [
                YII_ENV_DEV ? 'jquery.js' : 'jquery.min.js'
            ]
        ],
    ]
]
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.2.7
| Operating system | MacOS High Sierra (10.13.6)

**Comment by rob006** [comment]
Class names should be defined without leading backslash, so this is bug in `froala/yii2-froala-editor`. We may try to trim leading backslashes, but I'm not sure if it is worth the trouble.
