### ISSUE TITLE
Native soft delete support?

### ISSUE THREAD

**Issue by omzy83** [yiisoft/yii2#16616]
Are there any plans to implement native support for Soft Deletes?

I'm aware there are extensions that are doing this, e.g. https://github.com/yii2tech/ar-softdelete but really should it be necessary to have to do all of this manually? Laravel handles it so elegantly, maybe worth looking at their implementation:

https://laravel.com/docs/5.6/eloquent#soft-deleting

**Comment by rob006** [comment]
What is wrong with `yii2tech/ar-softdelete`?
