### ISSUE TITLE
BaseArrayHelper removeValue enhancement

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2#16614]
### What steps will reproduce the problem?
Create two arrays with string values. The second one should be a subset of the first one, i.e.:
```
$arrayOne = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'];
$arrayTwo = ['three', 'five', 'seven'];
```

Call `ArrayHelper::removeValue($arrayOne, $arrayTwo);`

### What is the expected result?
`$arrayOne` should look like `['one', 'two', 'four', 'six', 'eight', 'nine', 'ten'];`

### What do you get instead?
`$arrayOne` is untouched.

The suggestion is to enhance the `removeValue` method to accept an array of values, or to create a new method `removeValues` which will do the same. My opinion that semantically it is better to create a new method, but that is only my opinion.

For now I have modified an existing method `removeValue`, and it does the trick
```
    public static function removeValue(&$array, $value)
    {
        $result = [];
        if (is_array($array)) {
            foreach ($array as $key => $val) {
                if ($val === $value || (is_array($value) && in_array($val, $value))) {
                    $result[$key] = $val;
                    unset($array[$key]);
                }
            }
        }

        return $result;
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.7
| Operating system | CentOS 7 x64

**Comment by rob006** [comment]
How this would differ from `array_diff()`?

**Comment by Alex-Code** [comment]
@rob006 I thought that too but then realised `ArrayHelper::removeValue()` modifies the original array and returns a new one containing the values that were removed.

**Comment by rob006** [comment]
> and returns a new one containing the values that were removed

`array_intersect()`

I'm not sure if we need a helper which will be wrapper for 2 native PHP functions. It would make sense as readability improvement (I guess combination of `array_intersect()` and `array_diff()` is not obvious), but for me `ArrayHelper::remove*` methods were never intuitive, so this will actually decrease readability IMO.

**Comment by evil1** [comment]
So finally should I create a pull-request for this or just close the Issue?
