### ISSUE TITLE
Consider simpliying indexes / foreign key creation in migrations

### ISSUE THREAD

**Issue by omzy83** [yiisoft/yii2#16615]
The current syntax for creating indexes and foreign keys in unnecessarily long-winded. For example:

    $this->createIndex(
        'idx-post-author_id',
        'post',
        'author_id'
    );

    $this->addForeignKey(
        'fk-post-author_id',
        'post',
        'author_id',
        'user',
        'id',
        'CASCADE'
    );

Take a look at the Laravel approach:

    $table->index('user_id');

    $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');

https://laravel.com/docs/5.6/migrations#indexes

**Comment by rob006** [comment]
Related/duplicates https://github.com/yiisoft/yii2/issues/14623#issuecomment-322033250 and #13967.
