### ISSUE TITLE
preg_replace needs to be swaped with preg_replace_callback

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#16627]
The `setCookieValidationKey($root, $paths)` function inside the `init.php` file still using the `preg_replace()` function which is removed in php7 onwards and according to official Yii feed we don't need to do anything to upgrade the project from php 5.6 to php 7 , don't you think it should be fixed too?

### What steps will reproduce the problem?
`project_root/init.php`

### Proposed Change
```
$content = preg_replace('/(("|\')cookieValidationKey("|\')\s*=>\s*)(""|\'\')/', function($matches)use($key) {
    return "\\1'$key'";
}, file_get_contents($file));
```

### What do you get instead?
`$content = preg_replace('/(("|\')cookieValidationKey("|\')\s*=>\s*)(""|\'\')/', "\\1'$key'", file_get_contents($file));`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system |Ubuntu

**Comment by rob006** [comment]
> preg_replace() function which is removed in php7

`preg_replace() ` works perfectly fine on PHP7 - if you have any problems with it, make sure that it is not disabled in your `php.ini`.
