### ISSUE TITLE
Tinyint issue in generating model using GII

### ISSUE THREAD

**Issue by sri-rama-krishna** [yiisoft/yii2#16635]
### What steps will reproduce the problem?
Create any table with a field of type "tinyint" and try to generate a model through GII
### What is the expected result?
My expected result is that in the rules function i need to get that tinyint as Integer.
### What do you get instead?
I get that tinyint as string.

### Additional info
I debug that in Generator.php (vendor/yiisoft/yii2-gii/generators/model/Generator.php) generaterules function in switch case "tinyint" is missing.
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7+
| Operating system |windows

**Comment by carono** [comment]
Check the version yiisoft/yii2-gii https://github.com/yiisoft/yii2-gii/issues/335 maybe this is the problem?

**Comment by sri-rama-krishna** [comment]
https://github.com/yiisoft/yii2-gii/issues/335 is not the solution anyway it is closed.

**Comment by carono** [comment]
update yiisoft/yii2-gii to 2.0.7, and I think is will be solution

**Comment by sri-rama-krishna** [comment]
my version is latest(2.0.15)

 
![capture](https://user-images.githubusercontent.com/7912602/44323518-f0053b80-a46f-11e8-95a3-8465a4535727.PNG)

the highlighted part is missing, i added that line in my source code

**Comment by carono** [comment]
2.0.15 is `yiisoft/yii2`, and I'm talking about the generator itself, `yiisoft/yii2-gii`, just exec `composer update yiisoft/yii2-gii`
