### ISSUE TITLE
Url::to() not converting urls with query string

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#16634]
### Case 1

Either create an `ActiveForm`

```
$form = yii\widgets\ActiveForm::begin ( [ 

            'method' => 'get' ,
            'action' => ['/test/saveget','enddate'=>'1']

    ] );
?>
<?php
echo yii\bootstrap\Html::submitButton ( 'Submit' );
yii\widgets\ActiveForm::end ();
```
### Case 2
or write this line 

`echo yii\helpers\Url::to ( ['/test/save-get','enddate' => '1']);`

### Case 1

`<form id="w0" action="http://www.mysite.com/test/save-get?enddate=1" method="get">`

### Case 2
http://www.mysite.com/test/save-get?enddate=1

### Case 1

`<form id="w0" action="http://www.mysite.com/test/save-get" method="get">`

### Case 2

`http://www.mysite.com/test/saveget`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 5.6.21
| Operating system |Windows 10 Xampp

**Comment by ShaxXxboz** [comment]
In case 1 try to build url in this way:
        'action' => Url::to(['/test/saveget','enddate'=>'1']),

**Comment by buttflattery** [comment]
@ShaxXxboz  it takes both array or string, `$action` parameter will be processed by `[[\yii\helpers\Url::to()]]` by `ActiveForm` and apart from that the main problem is in the `Url::to([])` already not `ActiveForm` $action,

**Comment by paweljankowiak06** [comment]
Look at `yii\base\Html::beginForm()` there is comment.
```
// query parameters in the action are ignored for GET method
// we use hidden fields to add them back
```

Hidden inputs are created and they are submitted so your form action goes to the right place. 
This is my example:

```php
$url = ['/some/action-test', 'param' => 1];
echo \yii\helpers\Url::to($url);
$form = yii\widgets\ActiveForm::begin ([
    'method' => 'get' ,
    'action' => $url,
]);
```
And the result is:
```php
/some/action-test?param=1
<form id="w2" action="/some/action-test" method="get">
<input type="hidden" name="param" value="1">

<button type="submit">Submit</button></form>
```

**Comment by buttflattery** [comment]
@paweljankowiak06  , Hmm.. if that is so then how come it throws an error for the action specified 

> Bad Request (#400)
> Missing required parameter: enddate

i am using the same form using `get` method above and submitting the form to an action defined as 

```
public function actionSaveGet($enddate){
   echo $enddate;
}
```
when i check the url in the address bar it does contain all the fields for the model in the `querystring` but not the `enddate`? why is that so then.

**Comment by buttflattery** [comment]
Guys this isnt a bug the parameter `enddate` in the action parameter

` ['/test/saveget','enddate'=>'1']`

vanish because it was populated via a table column which i never mentioned above in the original post, (and i am sorry about that). 

The `enddate` against the specific record was `null` and if a value in the parameters is null for the `Url::to([])` then those indexes of the parameters are omitted as per these lines of code in `yii\web\UrlManager` files `createUrl()` function, starting @ Line 407

```
$cacheKey = $route . '?';
            foreach ($params as $key => $value) {
                if ($value !== null) {
                    $cacheKey .= $key . '&';
                }
            }

```

So it isnt a bug neither anything is wrong with it, i am closing this issue.
