### ISSUE TITLE
Headers already sent advanced/vendor/yiisoft/yii2/web/Response.php on line 366

### ISSUE THREAD

**Issue by akshaybande81** [yiisoft/yii2#16633]
Everything is running fine in my localhost, but when I upload files on cpanel it shows header already sent. I don't have any echo in controller. For checking the problem I have uploaded new yii2 advanced template on my website still it shows header already sent. It shows problem in vendor file, where I can't edit. Can someone help me on that? Thank you.

**Comment by chanakafit** [comment]
I got the same problem and in php.ini change output_buffering to 1 fixed the problem. 
https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

**Comment by akshaybande81** [comment]
Thank you. It worked.
