### ISSUE TITLE
yii\filters\PageCache - closure support for 'variations' and 'enabled'

### ISSUE THREAD

**Issue by C4RoCKeT** [yiisoft/yii2#16649]
When using the yii\rest\activeController, I wanted to vary the cache based on the user. While defining the behaviors, the user identity is not yet available and thus, Yii::$app->user->id always returns null.

Support of Closures would be highly appreciated.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1

**Comment by samdark** [comment]
Won't make it into 2.0.
