### ISSUE TITLE
strtolower function in BaseHtml corrupt UTF-8 strings

### ISSUE THREAD

**Issue by silberstreifen** [yiisoft/yii2#16648]
### What steps will reproduce the problem?
use yii\helpers\Html;
//Get a Model
$model = Bild::find()->one();
$field= 'bild_groß_dateiname';
echo Html::getInputId($model, $field);

A solution would be the function mb_strtolower

### What is the expected result?
bild-bild_groß _dateiname
### What do you get instead?
bild-bild_groÒ _dateiname

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.7
| Operating system | Windows 7 (Development)

**Comment by rob006** [comment]
What is the point of using `strtolower()` in this case?

**Comment by SamMousa** [comment]
IDs in the DOM are case sensitive, but they are not handled consistently across browsers. 
Having them all lowercase is an easy solution.
Alternatively we could also just use something like `base64_encode` which is available in PHP and JS...

**Comment by rob006** [comment]
> IDs in the DOM are case sensitive, but they are not handled consistently across browsers.

Does it matter? If we always use the same ID, case sensitivity should be irrelevant.

**Comment by Kolyunya** [comment]
@silberstreifen I've added some [test coverage](https://github.com/yiisoft/yii2/pull/16841) for that method but I wasn't able to reproduce the bug you described. The string `bild_groß_dateiname` was not corrupted by the current method implementation with `strtolower()`. Could you please provide a string which would break the tests?

**Comment by samdark** [comment]
@Kolyunya it actually was corrupted according to tests but in PHP 5.4 and PHP 5.5 only: https://travis-ci.org/yiisoft/yii2/builds/447569138?utm_source=github_status&utm_medium=notification

**Comment by Kolyunya** [comment]
@samdark seems like there is some issue with the `mb_internal_encoding()`? Should we force the `UTF-8` while converting to lower case?

**Comment by Kolyunya** [comment]
I was pretty sure that is going to help (tests pass now). My question was if should force encoding different from the system default.

**Comment by samdark** [comment]
I think it should be done same as in `encode()`:

```php
Yii::$app ? Yii::$app->charset : 'UTF-8'
```

**Comment by Kolyunya** [comment]
Reworked the code to select the charset like the `encode()` method does.
