### ISSUE TITLE
PostgreSQL migrate/fresh with types

### ISSUE THREAD

**Issue by carono** [yiisoft/yii2#16646]
When creating migrations, I create new types, but when calling "migrate/fresh" all foreign keys, tables are deleted, but the types remain. I understand that this is a feature of PostgreSQL, but I think this is the expected behavior.

_При создании миграций, я создаю новые типы, но при вызове "migrate/fresh" удаляются все внешние ключи, таблицы, но типы остаются. Я понимаю, что это особенность PostgreSQL, но мне кажется это ожидаемое поведение._

### What steps will reproduce the problem?
in migration create new type
`$this->execute("CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');`

clear migrations
`php yii migrate/fresh`

### What is the expected result?
migration will pass without errors

### What do you get instead?
exception `type "gender" already exists` 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | *
| Operating system | *

**Comment by HenryVolkmer** [comment]
i suggest to handle types and extension in postgresql NOT via Yii's Migration. Some Extension (e.g. ltree, ltree_gist) utilize data types too, if a Yii-Migration would purge all Datatypes, we would mess the Database's Extensions. A proper way to solve your issue would be to create and configure a postgres Database Template with all your desired Datatypes and Extensions.

**Comment by samdark** [comment]
@HenryVolkmer can I actually delete extension types?

**Comment by kjusupov** [comment]
It's an old issue, 
```sql
dev_test=# CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');
CREATE TYPE

dev_test=# drop type gender ;
DROP TYPE
```

DROP TYPE removes a user-defined data type. Only the owner of a type can remove it.

A potential workaround could be to use `drop type if exist` in `safeUp()` before executing `create type`

```php
public function safeUp()
{
    $this->execute("DROP TYPE IF EXISTS gender;");
    $this->execute("CREATE TYPE gender AS ENUM ('MALE', 'FEMALE')");
}
```

**Comment by HenryVolkmer** [comment]
can we close this?
I dont think its a good idea to purge the custom types for a Database on migrate/fresh.
