### ISSUE TITLE
Asset minification

### ISSUE THREAD

**Issue by Faboslav** [yiisoft/yii2#16652]
All assets in yiisoft/yii2/assets should be minified and used in proper asset bundles(YiiAsset, ActiveFormAsset, GridViewAsset) as minified based on the YII_DEBUG.

**Comment by samdark** [comment]
Not really. There's built-in asset processing pipeline for the purpose described in the guide.

**Comment by samdark** [comment]
Why won't it work with dots?

**Comment by Faboslav** [comment]
It's working all right with multiple dots or anything, but you still have to write one command for one specific asset, so in this case with yii, it's four commands for four specific files. Anyway it would be nice if we don't have to do that this way.

**Comment by samdark** [comment]
Why? The command is definitely able to work with multiple assets.

**Comment by Faboslav** [comment]
Let's say i want to use command on files with .js extension, i will define that command like this:
```
'js' => ['min.js', '@node_modules/.bin/uglifyjs {from} -o {to} -c']
```
So after this AssetConverter will run `convert` function and run this command on all file with .js extension. But "activeform.js" is not matched by ".js", so i need to add another special command just for "activeform.js" extension, right? Like this:
```
'activeform.js' => ['min.js', '@node_modules/.bin/uglifyjs {from} -o {to} -c']
```
So i have to do multiple commands, or don't i?

**Comment by samdark** [comment]
You don't have to: https://www.yiiframework.com/doc/guide/2.0/en/structure-assets

**Comment by Faboslav** [comment]
Can you point me to anything specific? I read that doc already multiple times.
