### ISSUE TITLE
AssetBundle / AssetManager can't have any check "file is readeble" (from web-server / from php)

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#16658]
### What steps will reproduce the problem?
```php
class TestAsset extends AssetBundle
{
    public $sourcePath = __DIR__ . '/test';
    public $js = [
        'js/code.js',
    ];
}
```
```php
\backend\assets\TestAsset::register($this);
```

`backend/assets/test` rights is `drwx------`; Owner is not a web server user and is not a php user.

### What is the expected result?
throw any error / docs about this case
### What do you get instead?
not have access to assets file from nginx. 404.
also in this case `@filemtime("$basePath/$asset")`  is false

So... I change rights
chmod -R u+rwX,go+rX,go-w backend/assets/test

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 
yiisoft/yii2                                     dev-master ade07cf Yii PHP Framework Version 2
| PHP version      | 7.2.8
| Operating system |alpine

**Comment by samdark** [comment]
Do you mean that Yii silences errors when it's not able to read asset file?

**Comment by bscheshirwork** [comment]
Yes. Also we can't publish file from asset bundle.

I see the algorithm of publish:
1. Check "file exist" for check correctly path.
2. Create symlink to dir
3. Check the touch time and write `<script url='...'>` with/without timestamp

If user `nginx` is right-less we have 404 for this url
If user `php` is right-less we can't get touch time (and publish by "copy dir"?)

may be need additional check 'is_readable'

**Comment by samdark** [comment]
I'd error explicitly in this case. Not sure why it does not now.
