### ISSUE TITLE
Replication and migrations don't work properly together

### ISSUE THREAD

**Issue by Shekhovtsovy** [yiisoft/yii2#16662]
### What steps will reproduce the problem?

If we have an app with the next conf:
```php
        'db' => [
            'masterConfig' => [
                'username' => 'username',
                'password' => 'password',
                'attributes' => [
                    PDO::ATTR_TIMEOUT => 10,
                ],
            ],
            'masters' => [
                'db1' => [
                    'dsn' => 'pgsql:host=db1.example.ru;dbname=db1',
                ],
                'db2' => [
                    'dsn' => 'pgsql:host=db1.example.ru;dbname=db2',
                ],
            ]
        ],
```
and try to use yii2 migrations (for example: php yii migrate)

### What is the expected result?

We expect that migrations should be applyed to each connection in order to keep databases structures identical.

### What do you get instead?

We get the same behaviour with a random connection during migrate perfomance. desync db structures

### Additional info

As near as figure out we get only one random  `$this->db = Instance::ensure($this->db, Connection::className());` by common app rules and then we use this connection for all BaseMigrateController functions. Probably it will be better if those fuctions follow throuh array of db dsn.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.9
| Operating system | Ubuntu 16.04.3 LTS

**Comment by Shekhovtsovy** [comment]
Yes. Providing an opportunity by config option.
I understand that structure of replicas can be different in theory but in practice it almost never happens. Now we have to init an app step by step in each environment with only one dsn and migrate commands. And only after that switch the app to work-mode with a replica config.

**Comment by samdark** [comment]
> in practice it almost never happens

I disagree. It happens and we should consider that replication itself could be two-way and could be done by a third party tool, not code.

**Comment by Shekhovtsovy** [comment]
I see. Thanks for the answers.
