### ISSUE TITLE
Using self table relation and different table relation simultaneously

### ISSUE THREAD

**Issue by dragonabv** [yiisoft/yii2#16673]
In CarrierPreferenceController :
        CarrierPreference::find()->select('category_name')->groupBy(['category_name'])->with('items', 'preferenceUser')->asArray()->all();

In CarrierPreference Model, i have self relation.

        public function getItems() {
		return $this->hasMany(CarrierPreference::className(), ['category_name' => 'category_name']);
	}

       public function getPreferenceUser() {
          return $this->hasOne(CarrierPreferenceUser::className(), ['carrier_preference_id' => 'id']);
      }

Getting this error:

`{
    "name": "PHP Notice",
    "message": "Undefined index: id",
    "code": 8,
    "type": "yii\\base\\ErrorException",
    "file": "/opt/lampp/htdocs/grabid-yii2-api/vendor/yiisoft/yii2/db/ActiveRelationTrait.php",
    "line": 494,`

**Comment by Alex-Code** [comment]
If you specify the select and have a relation you need to include the relation column.
e.g.
```php
CarrierPreference::find()->select(['id', 'category_name'])->groupBy(['category_name'])->with('items', 'preferenceUser')->asArray()->all();
```

**Comment by dragonabv** [comment]
@Alex-Code Thanks, this is working, but what if i want to show the category_name only and not the id?

**Comment by Alex-Code** [comment]
How are you using the results?
Just reference the `category_name` index directly.

**Comment by dragonabv** [comment]
@Alex-Code Above comment updated.

I want to fetch following record for current user.

`[
    {
        "category_name": "ANIMALS & LIVESTOCK",
        "items": [
            {
                "id": "32",
                "category_name": "ANIMALS & LIVESTOCK",
                "item_name": "House Pets"
            },
            {
                "id": "33",
                "category_name": "ANIMALS & LIVESTOCK",
                "item_name": "Farm and Large Horses"
            },
            {
                "id": "34",
                "category_name": "ANIMALS & LIVESTOCK",
                "item_name": "Other"
            }
        ]
    },
    {
        "category_name": "APPLIANCES & FURNITURE",
        "items": [
            {
                "id": "9",
                "category_name": "APPLIANCES & FURNITURE",
                "item_name": "Furniture"
            },
            {
                "id": "10",
                "category_name": "APPLIANCES & FURNITURE",
                "item_name": "Appliance"
            },`
