### ISSUE TITLE
unique validator client enhancement

### ISSUE THREAD

**Issue by zhcdsan** [yiisoft/yii2#16678]
### What steps will reproduce the problem?
Create a controller action with any model that need to be multiple and apply _unique_ in validation rules for some chosen attribute of model. 

### What is the expected result?
I hope the validation indicates the repeated fields in the form even if ajax validation is not enabled.

### What do you get instead?
Only works when ajax validation is enabled. Ok, i know that is not a bug and it's very well documented.

### Additional info
Looks like this

<img width="1627" alt="screen shot 2018-09-01 at 11 42 32" src="https://user-images.githubusercontent.com/20740947/44946969-5ed18580-addc-11e8-9d29-235e0dc4ebaf.png">

Think about 30 ~ 50 fields, if they have another fields and so on...
When ajax validation is enabled i need to build, load and validate all. If i use different url for validation, i'll need to do this steps a lot o times.

Why not validate in client only when ajax isn't enabled?

For now, i'm using an own validator that checks only in client side.
Note that i'm repeating in validation rules:  UniqueValidator::class and my/validator/ClientUniqueValidator::class.

<img width="616" alt="screen shot 2018-09-01 at 11 55 56" src="https://user-images.githubusercontent.com/20740947/44947094-2df25000-adde-11e8-9da7-4dc862c3ee6b.png">

and my validator looks something like this
<img width="1034" alt="screen shot 2018-09-01 at 11 55 15" src="https://user-images.githubusercontent.com/20740947/44947098-42cee380-adde-11e8-9d13-8800969c11d9.png">

I think that in this case attributes are all rendered in view and don't necessarily we need hit database to validate them.  And in most positive case, even not hit database, we're using server resources when ajax validation is enabled. 

Unique validator present in core now can be extended to this scenario. Someone agree?
this is related to #12900 but that issue is closed and i don't know if anyone still see.

I'll very grateful for your attention guys.
Thanks for great yii2 framework.

**Comment by samdark** [comment]
That's quite specific case. Of course, if you're submitting two non-unuique values (that isn't that common), we can find out error w/o accessing database but we'll need to query database anyway to make sure value is unique not only in the form itself but overall.
