### ISSUE TITLE
goBack() does not work correctly with onBeforeAction event in config

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#16679]
### What steps will reproduce the problem?
Add to your config the following configuration so that every request is logged to `returnUrl` other than `SecurityController` which has the `login` and `logout` methods

    'on beforeAction' => function (\yii\base\ActionEvent $e) {
        if($e->action->controller->id !== 'security') {
            Yii::$app->user->setReturnUrl(Yii::$app->request->url);
        }
    },

and then in the `login` method inside the `SecurityController` add the lines

```
if ($model->load(\Yii::$app->getRequest()->post()) && $model->login()) {
      $this->trigger(self::EVENT_AFTER_LOGIN, $event);
      return $this->goBack();
}

```

### What is the expected result?
I expect that if i am on a page `lead/index` and i click `logout` button which points to `security/logout` it should log me out and when i log back into the system it should take me to the `lead/index` page again.

### What do you get instead?
I get redirected to the `debug/default/toolbar?tag=5b8d0c22544a8` url instead as soon as i log-in back after logout.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system | Ubuntu 14.04

______________

### Edit ###

By further inspecting i find out that at the point of logout where I call `Yii::$app->getUser()->logout()` which calls the `yii\web\User` logout() method the statement `Yii::$app->user->getReturnUrl()` returns `/` and if i echo it before calling the `Yii::$app->getUser()->logout()` it shows the correct action-name i was on. 

This is my logout method

```
public function actionLogout()
    {
        $event = $this->getUserEvent(\Yii::$app->user->identity);

        $this->trigger(self::EVENT_BEFORE_LOGOUT, $event);

        \Yii::$app->getUser()->logout();

        $this->trigger(self::EVENT_AFTER_LOGOUT, $event);

        return $this->goHome();
    }
```

Any Ideas why it behaves like that i tried passing `true` inside the `logout()` thinking if that has to do something with the following lines
```

if ($destroySession && $this->enableSession) {
    Yii::$app->getSession()->destroy();
}
```

but it redirects me to the `defaultRoute` that i have set in my `config/main.php` file.

**Comment by SamMousa** [comment]
You have the debugger enabled. This loads pages via AJAX and you are setting the return URL on every request.
I think in your case the solution is to never update return URL for AJAX requests. Besides ignoring AJAX requests I'd also recommend only doing this for `GET` requests.

**Comment by buttflattery** [comment]
@SamMousa , Yeah,  i understand that I have the debugger enabled which sends ajax call the the specific URL to which it is redirecting me back, but it won't be happening on the production server as the debug is off, but if you have gone through the edit section of my post, don't you think if i logged out manually and then log in again it should take me back to the previous page i was on when i pressed log out rather than taking me to the `defaultRoute` specified in the `config/main.php`. Because in case if the session times out it redirect me to login page and after submitting the login it takes me back to the same page where my session expired.

**Comment by SamMousa** [comment]
That's not what you described originally.
- You go to `lead/index`.
- `beforeAction` sets the return URL to `lead/index`.
- Debugger loads.
- `beforeAction` sets the return URL to `debugger...`
- You click logout.
- You log back in
- You are sent to `debugger...`

Seems to function as expected. You are just confusing 2 concepts:
- Page you are on (URL in your browser bar)
- Page you last visited (in your example it's the AJAX fired by the debug module).

>  it should take me back to the previous page i was on when i pressed log out rather than taking me to the defaultRoute specified in the config/main.php

You never mentioned anything about sending you back to the default route?

**Comment by buttflattery** [comment]
@SamMousa 
>it should take me back to the previous page i was on when i pressed log out rather than taking me to the defaultRoute specified in the config/main.php
> 
> You never mentioned anything about sending you back to the default route?

Yes, i missed adding it in the post above sorry about that, but after turning off debugger i noticed this behavior. if Log out manually and login back it redirects to the `defaultRoute` but if session expired, then it redirects me to the correct link i was previously on.

Maybe i have to create a separate issue to report it but i thought that it should be discussed here.
