### ISSUE TITLE
Translate asDuration() to nl-NL

### ISSUE THREAD

**Issue by mhoogstraten** [yiisoft/yii2#16687]
What steps will reproduce the problem?
`Yii::$app->getFormatter()->asDuration( $time )`

### What is the expected result?
2 uur, 28 minuten

### What do you get instead?
2 hours, 28 minutes

### Additional info
Set language on "nl-NL"

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.4 (VC14 X86 32bit thread safe) + PEAR
| Operating system | Windows 10 / XAMPP Version 7.1.4

**Comment by koteq** [comment]
It seems that some translation lines are missing from [messages/nl/yii.php](https://github.com/yiisoft/yii2/blob/27a5b1e642faf9b6daa30600eac81589805977c7/framework/messages/nl/yii.php#L92-L97).
```
'{delta, plural, =1{1 day} other{# days}}'
'{delta, plural, =1{1 hour} other{# hours}}'
'{delta, plural, =1{1 minute} other{# minutes}}'
'{delta, plural, =1{1 month} other{# months}}'
'{delta, plural, =1{1 second} other{# seconds}}'
'{delta, plural, =1{1 year} other{# years}}'
```

**Comment by samdark** [comment]
Feel free to send a pull request.
