### ISSUE TITLE
Is it possible to get dependency hash? 

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#16688]
### What steps will reproduce the problem?

```php 
 $query = (new Query)
            ->select(['MAX(updated_at) upd'])
            ->from(Model::tableName());
$queryDependency new DbQueryDependency(['query' => $query]);

// For sure this will fail, as method is protected
$hash = $queryDependency->generateReusableHash();
```

However two last lines will fail cause method is protected and it can be 

> used for retrieving reusable dependency data

What about non reusable dependency? 
Could there be some method to generate a single hash, such as: 

```php
protected function generateReusableHash(){
    if($this->reusable) {
        return sha1(serialize( $reusableHash));
    } 

    return sha1(serialize($hash)); 
}
```

### What is the expected result?

Expected some method to get hash of the data. 

#### Use case: 

I have global widget, which can be cached via various methods (one of them as via `DbQueryDependency`). 

This widget being extended by child widgets. Each child widget has a wrapper from parent with link to drop the cache. 

```php
class BaseWidget extends Widget {
}
```

I have implemented a method to drop cache per specified key, but cannot find any way to get hash of the dependency.  

### What do you get instead?

~

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1
| Operating system | Mint 18

**Comment by bologer** [comment]
@samdark this isn't much of a question, but rather an implementation of the class as currently there is no way to retrieve hash of the dependency.

**Comment by samdark** [comment]
Why would you need it?

**Comment by bologer** [comment]
@samdark, as I mentioned in the issue, I have widgets and they are cached per DbQueryDependency. Each widget has link to drop its cache. The key based cache works just fine. However, I cannot get a hash of the dependency.

**Comment by samdark** [comment]
Can't you do the following?

```
ChainedDependency
    DbQueryDependency
    TagDependency
```

Then you can invalidate cache via tag.

**Comment by bologer** [comment]
@saada yes, I can. 

I just think that having method as `protected` is pointless, as sometimes it is required to get hash of the dependency outside of the class. 

What do you think about it?

**Comment by samdark** [comment]
I think that public and protected methods violate encapsulation so unless need proved, methods should stay with least visibility level.
