### ISSUE TITLE
No conversion of date type on andFilterWhere condition

### ISSUE THREAD

**Issue by dragonabv** [yiisoft/yii2#16685]
I am trying something like this. 
`delivery_pick_ups.start_time = 2018-09-06 16:30:00` and `$params['pick_date'] = 2018-09-06`

$query->andFilterWhere(['and', ["DATE(delivery_pick_ups.start_time) <= $params['pick_date"] ], [" DATE(delivery_pick_ups.end_time) >= $params['pick_date'] "] ]);

I don't know if that is possible in yii2 yet or not.

**Comment by rob006** [comment]
What kind of transformation you're expecting. From what to what?

**Comment by dragonabv** [comment]
@rob006 I want to convert database datetime to date to match a date type string variable from my php code.

**Comment by rob006** [comment]
So what is the problem? What kind of SQL query you want to achieve?

**Comment by ameyabap** [comment]
You can use `$startTime = new DateTime(delivery_pick_ups.start_time);
        $endTime = new DateTime(delivery_pick_ups.end_time);
        $query->andFilterWhere(['and', [$startTime->format('Y-m-d') <= $params['pick_date'] ], [$endTime->format('Y-m-d') >= $params['pick_date']] ]);`

Also, you can try `between` keyword. https://www.yiiframework.com/doc/guide/2.0/en/db-query-builder Look for `between` usage
