### ISSUE TITLE
Set widget options in ActiveField

### ISSUE THREAD

**Issue by dkhlystov** [yiisoft/yii2#16681]
https://github.com/yiisoft/yii2/blob/27a5b1e642faf9b6daa30600eac81589805977c7/framework/widgets/ActiveField.php#L763

Why are not 'options' set in widget config?

> $config['options'] = $this->inputOptions

**Comment by dkhlystov** [comment]
I want to see the model labels in placeholders. For this feature I set 'fieldConfig' property in ActiveForm config. There are problem when I use widget to render field.

`<?= $form->field($model, 'name', ['inputOptions' => ['placeholder' => 'one nice placeholder']]) ?>`
Generates input with placeholder

`<?= $form->field($model, 'phone', ['inputOptions' => ['placeholder' => another placeholder']])->widget(MaskedInput::className(), ['mask' => '+7 (999) 999-99-99']) ?>`
There are no placeholder

**Comment by samdark** [comment]
Because MaskedInput doesn't support it. It renders mask in the placeholder instead. I don't think we can fix it.

**Comment by dkhlystov** [comment]
It works great when I set widget placeholder directly:
<?= $form->field($model, 'phone')->widget(MaskedInput::className(), ['mask' => '+7 (999) 999-99-99', 'options' => ['placeholder' => 'Your phone here']]) ?>

The problem occurs because widget "options" not set from "inputOptions" property in "widget" function.

MaskedInput support placeholder. Mask renders only when mouse on.

The solve of this issue is in the first post.

**Comment by webinjaz** [comment]
if the $config params not include options key already this lines case error

`        foreach ($this->inputOptions as $key => $value) {
            if (!isset($config['options'][$key])) {
                $config['options'][$key] = $value;// need to add $config['options'] = [];
            }
        }`
