### ISSUE TITLE
ActiveField 'text' input with maxlength not working

### ISSUE THREAD

**Issue by omzy83** [yiisoft/yii2#16680]
### What steps will reproduce the problem?
```
public function rules()
{
    return [
         [['username'], 'string', 'min' => 3, 'max' => 15],
    ];
}

<?php echo $form->field($model, 'username')->input('text', ['maxlength' => true]); ?>
```
### What is the expected result?
It should output `maxlength="15"` to the rendered input field. 
### What do you get instead?
`maxlength=""`

However if I use `$form->field()->textInput()` instead it works as expected.

I prefer to use `$form->field()->input('text')` for consistency in my forms for different input types.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      | 7.2
| Operating system | Windows 10

**Comment by s1lver** [comment]
Hi!
The cause of the problem is the loss of the length normalization function. When you add a function, everything falls into place.

Writing options:

**Option 1:**
```php
<?= $form->field($model, 'username'); ?>
```
```html
<input type="text" id="username" class="form-control" name="Model[username]" value="Jon">
```
**Option 2:**
```php
<?= $form->field($model, 'username')->textInput(['maxlength' => true]); ?>
```
```html
<input type="text" id="username" class="form-control" name="Model[username]" value="Jon" maxlength="15">
```
**Option 3:**
```php
<?= $form->field($model, 'username')->input('text'); ?>
```
```html
<input type="text" id="username" class="form-control" name="Model[username]" value="Jon">
```
**Option 4:**
```php
<?= $form->field($model, 'username')->input('text', ['maxlength' => true]); ?>
```
```html
<input type="text" id="username" class="form-control" name="Model[username]" value="Jon" maxlength="15">
```
