### ISSUE TITLE
Yii2.0.15 reloads relation on key change but Yii2.0.13 didn't - BC break

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#16703]
New behavior is not documented in UPGRADE.md - old code could have relied on the fact that Yii never reloaded relations after the first access.

### What steps will reproduce the problem?
```SQL
CREATE TABLE `user` (`id` INT NOT NULL, PRIMARY KEY (`id`));
CREATE TABLE `project` (`id` INT NOT NULL, `manager_id` INT NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `fk1` FOREIGN KEY (`manager_id`) REFERENCES `user` (`id`));

INSERT INTO user(id) VALUES(1);
INSERT INTO user(id) VALUES(2);
INSERT INTO project(id, manager_id) VALUES(1, 1);
```

```PHP
class User extends \yii\db\ActiveRecord
{
}
class Project extends \yii\db\ActiveRecord
{
	public function getManager()
	{
		return $this->hasOne(User::class, ['id' => 'manager_id']);
	}
}
$project = new Project();
$project->manager_id = 1;
var_dump($project->manager);
$project->manager_id = 2;
var_dump($project->manager);
```
### What is the expected result?
This is Yii 2.0.13.1 output:
User object with id=1
User object with id=1
### What do you get instead?
This is Yii 2.0.15.1 output:
User object with id=1
User object with id=2

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.5
| Operating system |Windows 10

**Comment by samdark** [comment]
That was changed in 2.0.14: https://github.com/yiisoft/yii2/pull/13618
