### ISSUE TITLE
Allow configuration of the cache used by the url manager

### ISSUE THREAD

**Issue by hofrob** [yiisoft/yii2#16721]
### What steps will reproduce the problem?
* use a yii application in production with url manager cache and extensive use of the cache in general (where you can't just flush everything) 
* endpoints (actions/urls) get added/removed through the development process
* try to access the new urls
* 404 because url rules are cached

### What is the expected result?
* one should be able to flush the url manager cache only
* it should be possible to config the url manager cache (duration, dependency)

### Additional info
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L278

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
 PHP version      | 7.2.9
| Operating system | docker/alpine

**Comment by paweljankowiak06** [comment]
Same could be said about rbac DbManager. There is no possibility to clear cache only for texts categories.

**Comment by hofrob** [comment]
Now that I think about it.

In yii\rbac\DbManager you could just use the same cache with a different config:

https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L64

The cache property accepts an array as config for the cache.

And in yii\web\UrlManager you can use a dedicated cache application component. Still confusing that there are two different approaches to the same problem.

**Comment by rob006** [comment]
> And in yii\web\UrlManager you can use a dedicated cache application component. Still confusing that there are two different approaches to the same problem.

This actually should be fixed - `Instance::ensure()` should be consistently used in such cases.

We could also make `$cacheKey` public, so cache could be revalidated by changing this value. But this will break BC, so probably not an option in 2.0.

**Comment by paweljankowiak06** [comment]
There are few places where such behavior is implemented. Maybe some common trait would be a good solution.

**Comment by samdark** [comment]
About original issue. You can specify separate cache instance there:

- https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L83
- https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L132

So I don't see a problem with flushing this separate instance.
 
@mahkali what for?

**Comment by mahkali** [comment]
@samdark flushing the cache on change would indeed be more efficient as we don't require to check a dependency on every request.
