### ISSUE TITLE
Wrong ukrainian i18n default translates

### ISSUE THREAD

**Issue by dozer111** [yiisoft/yii2#16736]
#Issue:
Ukrainian default form translates stand on vendor/yii2/messages/uk/yii.php

when i change config to
`"language" => "uk"` 
System translate all to United Kingdom, not ukraine 

#How to fix
I just rename dir: "uk" => "ua" and all works correct on UA i18n version.

#P.S If this is not a bug, how can i use uk file correct?

**Comment by samdark** [comment]
`uk` is [correct language code for Ukrainian](http://www.localeplanet.com/icu/uk-UA/index.html) and translations [do match](https://github.com/yiisoft/yii2/blob/master/framework/messages/uk/yii.php). UA is the country code, not language code.

**Comment by samdark** [comment]
What exactly doesn't work for you?

**Comment by dozer111** [comment]
Sorry Alex for my stupid question. After pull this issue i wrote about it, and there was trouble because of architecture of my project, so all i done to get wroght result: change Yii::$app->language in urlManager. Once again I apologize, have a nice day and less nubes like me

**Comment by samdark** [comment]
No worries.
