### ISSUE TITLE
TimestampBehavior issue

### ISSUE THREAD

**Issue by loks15** [yiisoft/yii2#16749]
### What steps will reproduce the problem?

when updating my model

1. model validation

2. model update 

3. After model update

### What is the expected result?

echo $model->errors

no error

echo $model->modifiedAt

"2018-12-04 00:00:00"

### What do you get instead?

echo $model->errors

  [yii\db\ActiveRecord::update] 'Model not updated due to validation error.'

echo $model->modifiedAt

  yii\db\Expression Object
  (
      [expression] => NOW()
      [params] => Array
          (
          )
  
  )

### Additional info

1. save function working fine.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by koteq** [comment]
You may try to change `'value' => new Expression('NOW()')` to `'value' => function () { return date('Y-m-d H:i:s'); }'` in TimestampBehavior's configuration.

**Comment by cebe** [comment]
You should not have validation rules for fields that do not receive user input. Remove affected attributes from rules() method
