### ISSUE TITLE
Yii2 how to specify the action action, record the log

### ISSUE THREAD

**Issue by xingchunzhe111** [yiisoft/yii2#16745]
### What is the expected result?
Yii2 how to specify the action action, record the log

For example, the following two classes

SiteController.php
namespace admin\controllers;
use admin\models\Store_set;
use yii;
class SiteController extends UserController {
	public function actionUpBoot() {
	}
}

OrderController.php
namespace admin\controllers;
use admin\models\Store_set;
use yii;
class OrderController extends UserController {
	public function actionOrder() {
	}
	public function actionTest() {
	}
}
Just want to log in the OrderController.php class
Or just want to log in the actionTest method，what should I do?
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.*

**Comment by xingchunzhe111** [comment]
@larryli   @bio   @ouhman   @marsuboss

**Comment by xingchunzhe111** [comment]
@samdark

**Comment by xingchunzhe111** [comment]
this is my config 
return [
    'id' => 'admin',
    'defaultRoute'=>'index', 
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'admin\controllers',
    'components' => [
        'request' => [
            'csrfParam' => '_csrf',
            'enableCookieValidation' => true,
        ],
        'session' => [
            // this is the name of the session cookie used for login on the control
            'name' => 'create-session',
            'timeout' => 3600,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                //[
                //    'class' => 'yii\log\FileTarget',
                //    'levels' => ['error', 'warning','info'],
                //    'logVars' => ['*']
                //],
                [
                    'class' => 'yii\log\DbTarget',
                    'levels' => ['error', 'warning','info'],
                    'logVars' => ['*']
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'common/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => false,
            'suffix' => '',
            'rules' => [
            ]
        ]
    ],
    'params' => $params,
];
what should I do?

**Comment by koteq** [comment]
@xingchunzhe111 
You may attach custom behavior to your controllers. Something like this:

```php
// app/behaviors/ActionsLogBehavior.php

namespace app\behaviors;

use app\base\Controller;
use Yii;
use yii\base\ActionEvent;
use yii\base\Behavior;

class ActionsLogBehavior extends Behavior
{
    public function events()
    {
        return [
            Controller::EVENT_AFTER_ACTION => 'afterAction',
        ];
    }

    /**
     * @param ActionEvent $event
     */
    public function afterAction($event)
    {
        if (Yii::$app->request->method !== 'GET') {
            $actionUid = $event->action->getUniqueId();
            Yii::info($actionUid, __METHOD__);
        }
    }
}
```

Then attach it to your controllers' base class:
```php
class UserController extends Controller {
    public function behaviors()
    {
        return [
            'actionsLog' => 'app\behaviors\ActionsLogBehavior',
        ];
    }

    // rest of your code

}
```

Otherwise you may attach it from your config:
```php
'as actionsLog' => 'app\behaviors\ActionsLogBehavior',
```

**Comment by xingchunzhe111** [comment]
> @ xingchunzhe111
> 您可以将自定义行为附加到控制器。像这样的东西：
> 
> ```
> // app / behavior / ActionsLogBehavior.php
> 
> 命名空间 app \ behavior ;
> 
> 使用 app \ base \ Controller ; 
> 使用 Yii ; 
> 使用 yii \ base \ ActionEvent ; 
> 使用 yii \ base \ Behavior ;
> 
> class  ActionsLogBehavior  extends  Behavior
>  { 
> public function events（）    { return [ Controller :: EVENT_AFTER_ACTION => ' afterAction '，        ];     }      
> 
>         
>               
> 
> 
> 
>     / **
>       * @param ActionEvent $ event 
> * / public function afterAction（ $ event）    { if（ Yii :: $ app - > request - > method ！== ' GET '）{ $ actionUid = $ event - > action - > getUniqueId（）; Yii :: info（ $ actionUid， __ METHOD__）;         }    }}     
>       
> 
>           
>               
>             
> ```
> 
> 然后将它附加到控制器的基类：
> 
> ```
> class  UserController  extends  Controller { 
> public function behavior（）    { return [ ' actionsLog ' => ' app \ behavior \ ActionsLogBehavior '，        ];     }      
> 
>         
>               
> 
> 
> 
>     //其余的代码
> 
> }
> ```
> 
> 否则你可以从你的配置中附加它：
> 
> ```
> ' as actionsLog '  =>  ' app \ behavior \ ActionsLogBehavior '，
> ```

I just want to record sql, yii::info how to get the executed sql and record it

**Comment by xingchunzhe111** [comment]
> 只需`Yii::info()`在您的操作中调用（或调试/错误/警告）。根据您配置`log`组件的方式，消息将记录到文件中。

I just want to record sql, yii::info how to get the executed sql and record it

**Comment by larryli** [comment]
@xingchunzhe111 Please google your question. https://stackoverflow.com/a/36741997
