### ISSUE TITLE
I add google reCAPTCHA Extension in Yii framework contact form but error show like class 'yii\base\BaseObject' not found

### ISSUE THREAD

**Issue by karthigeyan15** [yiisoft/yii2#16746]
I add google reCAPTCHA Extension in Yii framework contact form but error show like class 'yii\base\BaseObject' not found
![image](https://user-images.githubusercontent.com/29995844/46191349-cc59ce80-c314-11e8-96a8-cf7fbd4ab25b.png)

**Comment by karthigeyan15** [comment]
yii 2

**Comment by karthigeyan15** [comment]
2.0.12-dev

**Comment by karthigeyan15** [comment]
kindly can you sent me to mail karthigeyan065@gmail.com what errors this

**Comment by cebe** [comment]
BaseObject is available since Yii 2.0.13: https://github.com/yiisoft/yii2/commit/69673c0c94679ba3f38829cf44cb001d9186621d#diff-b8225aff6112940ead03b5b79a4bc969
