### ISSUE TITLE
Pjax::begin doesn`t shows div tag

### ISSUE THREAD

**Issue by floor12** [yiisoft/yii2#16751]
### What steps will reproduce the problem?
Use `Pjax::begin();` in any view.

### What is the expected result?
echo `<div>` with some widget attributes and register some JS code

### What do you get instead?
Js is registred in view but div tag is not exist it final render. But Pjax::end() works fine and show closing `</div>` tag, wich is distroing dom.

### Additional info
Yesterday i updated one of my dev project and all places with Pjax was broken. I made composer update for some more of my dev-stability projects and all of then also was broken after upgrade.
After switching to stable-stability this problem done.

| Q                | A
| ---------------- | ---
| Yii version      |  latest dev version
| PHP version      |  7.1
| Operating system | Debian stretch

**Comment by samdark** [comment]
Seems to be same as https://github.com/yiisoft/yii2/issues/16753
