### ISSUE TITLE
Pjax widget broken after #16657

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#16753]
### What steps will reproduce the problem?
- The fix for Issue #16657 has caused this error
- Include a Content enclosed between `Pjax::begin` and `Pjax::end`. The `Pjax::begin` does not render the begin container markup. This is probably because the Pjax::init method is returning a markup instead of echoing it.
- The `Pjax::registerClientScript` is not run - because of a forced return in `Pjax::run` [here in this line](https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php#L151) before the registerClientScript is run - as a result the pjax jquery plugin is also never initialized

### What is the expected result?
- The `Pjax::begin` container markup must render the Pjax container markup
- The Pjax jquery client script must be registered

### What do you get instead?
Broken Pjax Widget.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |  all
| Operating system | all

**Comment by samdark** [comment]
@kartik-v could either be fixed like https://github.com/yiisoft/yii2/pull/16755 or reverted altogether. What do you think?

**Comment by kartik-v** [comment]
Thanks @samdark - I think #16755 does solve the `Pjax` part of it.  

On the reverting - if you mean reverting #16657 - I suppose it is a call that should be made considering the BC breaking changes that this fix introduces. Anyone extending the widgets would now need code changes across. Content may not get rendered because of that fix getting introduced and can break the app.

**Comment by samdark** [comment]
Right. Reverted https://github.com/yiisoft/yii2/commit/9910519aba26c96d70b7a137b1682045b0273f57

**Comment by kartik-v** [comment]
Thanks - this seems to resolve most issues now.

**Comment by kartik-v** [comment]
😄 I meant all issues are fixed prior to what the fix #16657 was intended for.
