### ISSUE TITLE
Formatter asRelativeTime() result can be off by several hours

### ISSUE THREAD

**Issue by HunWalk** [yiisoft/yii2#16775]
### What steps will reproduce the problem?
1. Set your timezone as continent/capital
2. Set your `$value` with `new Expression('NOW()');`,
3. Try to calculate the relative time with `Yii::$app->formatter->asRelativeTime($value)`
### What is the expected result?
Just now
### What do you get instead?
In an hour (Based on your difference to UTC+0)
### Possible causes
https://github.com/yiisoft/yii2/blob/ef9793bebc512245edcd9bee5565d8025ccfdb5e/framework/i18n/Formatter.php#L916-L927
What if the timezone has already been set for $timestamp?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system | macOS 10.14 Mojave

**Comment by cebe** [comment]
> Set your timezone as continent/capital

where did you set the timezone? you need to set timezone PHP and in DB server. Data in database should ideally be stored in UTC.

**Comment by HunWalk** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/structure-applications#timeZone

I did not modified the default config for php since the project I am working on is still in it's test phase. I've just wanted you to know, that in certain conditions you can encounter this kind of bug. You could still add some information in the official documentation about this.

**Comment by cebe** [comment]
You are probably using it wrong, please check the documentation at https://www.yiiframework.com/doc/guide/2.0/en/output-formatting#time-zones

I added a link to that part of the guide from the page you linked.
