### ISSUE TITLE
Suggested Extra Condition For Unique / Exist Validator Part II

### ISSUE THREAD

**Issue by yaroslavolekh** [yiisoft/yii2#16776]
It's impossible to use multi-conditions for 'filter' param in rules method:

```php
 ['host', 'unique', 'message' => \Yii::t('msg', 'This host has already been taken.'),
                'filter' => [
                    ['=','status', 'active'],
                    ['<', 'finish_date', date('Y-m-d H:i:s')]
                ]
            ]
```

### What steps will reproduce the problem?
add in a rule addition query param.

### What is the expected result?
Has to be working :)

### What do you get instead?
{"name":"PHP Warning","message":"strtoupper() expects parameter 1 to be string, array given"...

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16-dev
| PHP version      | 7.2.10
| Operating system | macOS 10.13.6

**Comment by samdark** [comment]
It accepts same syntax as Query::where(). Please refer to its docs to learn on how to specify multiple conditions at once.
