### ISSUE TITLE
How about add alias -y to migrate commands?

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#16787]
### What steps will reproduce the problem?
I must typing `--interactive=0` or confirm command each time
This keyword is not so short... 

### What is the expected result?
I expect the sugar alias options `-y` for applying migration's command

### What do you get instead?
non-autocomplited `--interactive=0` only

### Additional info
https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L51-L54

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
I like it.
