### ISSUE TITLE
Test 'mode' and test 'environment' should be separate constants/app functions

### ISSUE THREAD

**Issue by rhertogh** [yiisoft/yii2#16782]
### What steps will reproduce the problem?

#15847 and #15202

In our development flow we have 4 different environments, 'dev', 'test', 'staging' and 'production'.
In our deployment script we call `yii migrate` but when the migration fails on the 'test' environment the deployment script continues because no exception is thrown.

### What is the expected result?

An exception should be thrown to abort the deployment.

### What do you get instead?

Deployment script continues.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      |  7.0
| Operating system | CentOs 7

### Proposed solution

Use `YII_ENV_TEST` as indicator for the 'test environment' and exit the application when an exception occurs.
Add new constant `YII_TEST_MODE` for running the application in 'test mode' to continue the application after an exception. For example during the use of Codeception/PHPUnit.

**Comment by samdark** [comment]
> continue the application after an exception

I don't think it is a good idea. What's the use case for it? If it fails it fails.

**Comment by rhertogh** [comment]
@samdark As @klimov-paul described in https://github.com/yiisoft/yii2/issues/15202#issuecomment-346351890 "Enforcing exit on error will cause it to terminate PHPUnit script"

**Comment by samdark** [comment]
Yes.
