### ISSUE TITLE
Error in sp_updateextendedproperty when adding field comments

### ISSUE THREAD

**Issue by sdlins** [yiisoft/yii2#16796]
### What steps will reproduce the problem?
```php
$this->createTable('MY_TABLE', [
            'name' => $this->string(32)->notNull()
                ->comment('An unique name for this group like group_fisc or group_cash'),
...
```

### Results in
```shell
*** applying m181009_061513_modarq_init
    > create table MY_TABLE ...Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]
An invalid parameter or option was specified for procedure 'sp_updateextendedproperty'.
The SQL being executed was: 
sp_updateextendedproperty @name = N'MS_Description', 
@value = 'An unique name for this group like group_fisc or group_cash', 
@level1type = N'Table',  @level1name = [MY_TABLE], 
@level2type = N'Column', @level2name = [name] (C:\Users\...\vendor\yiisoft\yii2\db\Schema.php:664)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1
| SQL Server      |  13.0
| Operating system | Win10 64

**Comment by tourze** [comment]
same problem. has it fixed?

**Comment by samdark** [comment]
@tourze no. The issue isn't closed.

**Comment by sdlins** [comment]
I am tracing this again. 

Till now I found MSSQL has two functions: `sp_updateextendedproperty` and `sp_addextendedproperty`.
I can test wether the description already exists before update or add a description. After `add` the description an `update` doesn't generate any errors.

Hope to make a PR next weeks, according to my free time.

**Comment by sdlins** [comment]
@samdark I would appreciate your help in a question.

This would be the new `mssql\QueryBuilder::addCommentOnTable()` method:
```php
    public function addCommentOnTable($table, $comment)
    {
        $schemaName = $this->db->schema->defaultSchema;
        $comment = $this->db->quoteValue($comment);

        return <<< SQL
        -- Maybe we can simplify this later
        IF
            NOT EXISTS (
                SELECT 1
                FROM fn_listextendedproperty (
                    NULL,
                    'SCHEMA', N'$schemaName',
                    'TABLE', N'$table',
                    null, null
                )
            )
        BEGIN
            EXEC sys.sp_addextendedproperty
                @name = N'MS_description',
                @value = $comment,
                @level0type = N'SCHEMA', @level0name = N'$schemaName',
                @level1type = N'TABLE', @level1name = N'$table';
        END
        ELSE
        BEGIN
            EXEC sys.sp_updateextendedproperty
                @name = N'MS_description',
                @value = $comment,
                @level0type = N'SCHEMA', @level0name = N'$schemaName',
                @level1type = N'TABLE', @level1name = N'$table';
        END
        GO
SQL;
    }
```
Instead of:

```php
    public function addCommentOnTable($table, $comment)
    {
        return "sp_updateextendedproperty @name = N'MS_Description', @value = {$this->db->quoteValue($comment)}, @level1type = N'Table',  @level1name = {$this->db->quoteTableName($table)}";
    }
```

In my tests, `sp_(whatever)extendedproperty()` will not work without schema name. But the `mssql\Schema\defaultSchema` defaults to `null`. So, if schema name is not provided, this will generate an error. Should the docs be updated about it or do you see some other way?

**Comment by samdark** [comment]
Is it possible to get the name of default schema?

**Comment by sdlins** [comment]
I tryed to found that yesterday but I could not. Today I found :unamused:

The sql will be a bit longer yet (MS way to make things simple!)

**Comment by sdlins** [comment]
I managed to fix this issue. But I found similar problems in `dropCommentFromColumn|Table()` that I will fix too (unless I need open a new issue... but i think not). 

Those methods were created in commit d801ca3c90 that was "needing tests". 

I will provide tests too.
