### ISSUE TITLE
Improve annotations for yii\helpers\BaseArrayHelper::getColumn()

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii2#16795]
`yii\helpers\BaseArrayHelper::getColumn($array, $name, $keepKeys = true)` has annotation for $name as 
`@param string|\Closure $name`:
https://github.com/yiisoft/yii2/blob/558cd482d8a0525fceec8646ea20ccc9b7c3fdf4/framework/helpers/BaseArrayHelper.php#L512

Key in array can be also integer so I think annotation should be:
`@param int|string|\Closure $name`

I was running PhpStan and it found this issue.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15?
| PHP version      | 7.1.17
| Operating system | Amazon Linux AMI 2018.03

**Comment by samdark** [comment]
Correct.
