### ISSUE TITLE
module bootstrap will not work when  id is some with a component

### ISSUE THREAD

**Issue by sanwv** [yiisoft/yii2#16804]
### What steps will reproduce the problem?
when component and module has a some id  ,e.g.
```
'bootstrap'=>['my'],
'modules'=>['my'=>xxx:class],
'components'=>['my'=>yyy:clsss]

```
### What is the expected result?

module bootstrap can work

### What do you get instead?
```
 'bootstrap' => [function ($app) {
        $app->getModule('my')->bootstrap($app);
    }],
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
That's correct. I don't think we can fix that easily in 2.0.
