### ISSUE TITLE
Mailer Filetransport issue with Swiftmailer

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii2#16818]
### What steps will reproduce the problem?
Hi i wanted to use some plugin for CSS inlining the CSS style from an mail layout file.

E.g. this extension works good when using the Swift_SmtpTransport,
https://github.com/OpenBuildings/swiftmailer-css-inliner

    $config['components']['mailer']['transport'] = [
        'class' => 'Swift_SmtpTransport',
        'host' => getenv('SMTP_HOST'),
        'username' => getenv('SMTP_USERNAME'),
        'password' => getenv('SMTP_PASSWORD'),
        'port' => getenv('SMTP_PORT'),
        'encryption' => getenv('SMTP_ENCRYPTION'),
        'plugins' => [
            [
                'class' => 'Openbuildings\Swiftmailer\CssInlinerPlugin',
            ],
        ],
    ];

The problem in the development phase I would like to get the same result with 

    $config['components']['mailer']['useFileTransport'] = true;

And for the Filetransport no plugin could be registered because the message is saved directly in the Class BaseMailer.

https://github.com/yiisoft/yii2/blob/1342eb718b6674c6ade3f2887dcf0710d2987e3b/framework/mail/BaseMailer.php#L260-L261

The problem is that the CssInlinerPlugin hooks on  Swift_Transport_SendmailTransport::start().
So I also couldn't register the plugin like this when `useFileTransport = true` as there isn't a transport Class used at all.

    $mailer = Yii::$app->mailer;
    $mailer->getSwiftMailer()->registerPlugin(new CssInlinerPlugin());

If i look into BaseMailer the  i see that the message is directly saved in BaseMailer::saveMessage
https://github.com/yiisoft/yii2/blob/1342eb718b6674c6ade3f2887dcf0710d2987e3b/framework/mail/BaseMailer.php#L323

The message content is just saved to the file.
` file_put_contents($file, $message->toString());`

Sadly there isn't a callback function for this. So my current solution is to compose my message

    $message = $mailer->compose(['html' => $view, 'text' => 'text/' . $view], $params)
            ->setTo($to)
            ->setFrom($this->sender)
            ->setSubject($subject);

and depending on the filetransport call a extra function inlineCss
```
        if ($mailer->useFileTransport == true) {
            $this->inlineCss($message);
            return $message->send();
        } else {
            return $message->send();
        }
```

    protected function inlineCss(&$message)
    {
        $swiftMessage = $message->getSwiftMessage();

        $this->converter = new TijsVerkoyen\CssToInlineStyles\CssToInlineStyles();

        if ($swiftMessage->getContentType() === 'text/html') {
            $message->setBody($this->converter->convert($swiftMessage->getBody()));
        }

        foreach ($swiftMessage->getChildren() as $part) {
            if (strpos($part->getContentType(), 'text/html') === 0) {
                $part->setBody($this->converter->convert($part->getBody()));
            }
        }
    }

But i would be good to have a fake swiftmailer file transport instead which could use the plugins directly.
Or have a callback function in BaseMailer::saveMessage to be able to hook the css inlining before saving the file.

The purpose to inline CSS is mentioned here:
https://htmlemail.io/inline/

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.15.1
| Yii SwiftMailer version |2.1.2
| SwiftMailer version     |6.1.3
| PHP version             |7.1.4
| Operating system        | Win 10

**Comment by Bhoft** [comment]
I have used some custom class to get around this issue.
I guess a fake file email transport could be interesting but for the time being a small extend of swiftmailer also solves this problem and do the css inline before saveMessage()  is called.


    namespace app\components\swiftmailer;

    use yii\swiftmailer\Mailer as SwiftMailer;
    use TijsVerkoyen\CssToInlineStyles\CssToInlineStyles;

    class Mailer extends SwiftMailer
    {
        private $converter;

        protected function inlineCss(&$message)
        {
            $swiftMessage = $message->getSwiftMessage();

            $this->converter = new CssToInlineStyles();

            if ($swiftMessage->getContentType() === 'text/html') {
                $message->setBody($this->converter->convert($swiftMessage->getBody()));
            }

            foreach ($swiftMessage->getChildren() as $part) {
                if (strpos($part->getContentType(), 'text/html') === 0) {
                    $part->setBody($this->converter->convert($part->getBody()));
                }
            }
        }

        /* extend saveMessage function to inline CSS on filetransport */
        /* css inline is done via plugin on smtp transport */
        protected function saveMessage($message)
        {
            $this->inlineCss($message);
            return parent::saveMessage($message);
        }
    }

**Comment by samdark** [comment]
Mailer is a generic solution that isn't necessary to be used with swiftmailer so using fake file transport for swiftmailer won't work. Since there are ways to hack it well, closing.
