### ISSUE TITLE
Create index in migration

### ISSUE THREAD

**Issue by i-panov** [yiisoft/yii2#16815]
### What steps will reproduce the problem?
Create new migration and use function `$this->createIndex()`. 

### What is the expected result?
I want the fourth parameter in this function not the `$unique` flag, but the type of the index, for example `fulltext`. Because there is no other possibility to create an index (except through the `execute` method).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.2
| Operating system | CentOS 7

**Comment by samdark** [comment]
Won't be implemented in 2.0 but a good idea for 3.0.
