### ISSUE TITLE
feature required exist validator OR condition

### ISSUE THREAD

**Issue by tonykor** [yiisoft/yii2#16823]
Hello, exist validator currently using AND condition to verify existence among many fields, as far as i have found it's impossible to use OR condition in validation. I'd like user use username or email as a login to sign in and i need to verify existence of login in either username or email field.

**Comment by tonykor** [comment]
Sorry seems like it targetAttributeJunction property in the validator to specify OR|AND, but still can not validate existence among 2 attributes.

**Comment by rob006** [comment]
This could be solved by [`RequireAny`](https://github.com/yiisoft/yii2/pull/15157#issuecomment-352113254) validator.
