### ISSUE TITLE
Console Table Widget does not render correctly in combination with ANSI formatting

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#16831]
### What steps will reproduce the problem?

```php
$table = new Table();
$table->setHeaders(['test1', 'test2', Console::ansiFormat('test3', [Console::FG_RED])]);
$table->setRows([
        [Console::ansiFormat('testcontent1', [Console::FG_BLUE]), Console::ansiFormat('testcontent2', [Console::FG_YELLOW]), 'testcontent3'],
        ['testcontent1', 'testcontent2', [
            'a',
            Console::ansiFormat('b', [Console::FG_PURPLE]),
            Console::ansiFormat('c', [Console::FG_GREEN]),
        ]],
    ]);
$table->setScreenWidth(200);
echo $table;
```

### What is the expected result?

correctly rendered table.

### What do you get instead?

![bildschirmfoto von 2018-10-26 16-11-02](https://user-images.githubusercontent.com/189796/47571964-1cd74280-d93a-11e8-9ca7-0b0543870025.png)

This happens because ANSI formatting characters are considered for calculating cell width. These characters are zero-width and thus need to be removed when calculating width.

~~I will send a pull request to fix this.~~

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.1
| Operating system | Linux

**Comment by issidorov** [comment]
Screenshot for working code from #16831

![image](https://user-images.githubusercontent.com/25592330/95589101-f50d1680-0a4c-11eb-9c84-1a8e18c8c8c0.png)
