### ISSUE TITLE
hasOne()/hasMany not use Yii::createObject for related class

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#16843]
### What steps will reproduce the problem?

So... I want to use `::class` instead something like
```php
    public function getParents()
    {
        return $this->hasMany(get_class(Yii::createObject(DiRedefineClass::class)), ['id' => 'parentId'])->viaTable('{{%table_for_child}}', ['childId' => 'id']);
    }
```

But in rules I can use it directly
```php
            [['typeId'], 'exist', 'skipOnError' => true, 'targetClass' => DiRedefineClass::class, 'targetAttribute' => ['typeId' => 'id']],

```
### What is the expected result?

hasMany/hasOne can accept config for create class to use for `::find()`

### What do you get instead?

https://github.com/yiisoft/yii2/blob/8ac45fa9626c9ac12e7e1b955eec725271279621/framework/db/BaseActiveRecord.php#L449

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | 7.2.11
| Operating system |

**Comment by bscheshirwork** [comment]
upd: 
```php
  [['typeId'], 'exist', 'skipOnError' => true, 'targetClass' => DiRedefineClass::class, 'targetAttribute' => ['typeId' => 'id']],
```
can't wrk correctly to :cry:

**Comment by samdark** [comment]
What's your use case?
