### ISSUE TITLE
Date format configuration doesn't impact to GridView

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2#16849]
### What steps will reproduce the problem?
Using gridview and formater config.
```php
return [
    'components' => [
        'formatter' => [
            'dateFormat' => 'dd.MM.yyyy',
            'decimalSeparator' => ',',
            'thousandSeparator' => ' ',
            'currencyCode' => 'EUR',
       ],
    ],
];
```
```php
[
    'date' // php date object
],
```

Format configuration doesn't impact to GridView (internal formatter).

### What is the expected result?
Date in format corresponding with MM/dd/yyyy.

### What do you get instead?
Oct 16, 2018

### Additional info
https://github.com/yiisoft/yii2/blob/8ac45fa9626c9ac12e7e1b955eec725271279621/framework/grid/GridView.php#L278-L280

In a meantime, yii:$app->formatter has settings.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | ubuntu 18.04

**Comment by paweljankowiak06** [comment]
You need to tell grid view to format date with formatter 

```php
'columns' => [
    'attributeName:date',
]
```
Or 
```php
'columns' => [
    [
        'attribute' => 'attributeName',
        'format' => 'date',
    ],
]
```

**Comment by springimport** [comment]
@paweljankowiak06 Sure. Full version:
```php
[
    'value' => function($model) {
        return ...
    },
    'format' => 'date',
],
```

But is doesn't work. Like I said, GridView creates new formatter instead of using existing.

**Comment by rob006** [comment]
Grid uses app formatter if `GridView::$formatter` is `null`:

https://github.com/yiisoft/yii2/blob/8ac45fa9626c9ac12e7e1b955eec725271279621/framework/grid/GridView.php#L276-L278

Which is default setting:

https://github.com/yiisoft/yii2/blob/8ac45fa9626c9ac12e7e1b955eec725271279621/framework/grid/GridView.php#L144

New object will be created only if you pass array with object configuration. But getting a new object should not be a surprise then.

**Comment by springimport** [comment]
@rob006 Yes, I found a problem.
```php
'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
```

I rewrote it to:
```php
$formatter = clone yii::$app->formatter;
$formatter->nullDisplay = '';
...
'formatter' => $formatter,
```
