### ISSUE TITLE
Caching issue when making POST request

### ISSUE THREAD

**Issue by grrr8-rock-star** [yiisoft/yii2#16850]
I don't know if this issue belongs to yii2 or yii2-starter-kit. Hence, I've notified in both of the repositories.

I'm developing a project in Yii2 using Semantic UI for designing user interface. I'm using yii2-starter-kit, which provides a basic structure for both frontend and backend. For Semantic UI, I'm using yii2-semantic-ui package. A snippet of my frontend asset class:

![frontend-depends](https://user-images.githubusercontent.com/43202296/47765853-fd516880-dcf1-11e8-8a2a-25c902c56a1b.png)

So naturally, bootstrap files don't get loaded. But I just found out when we make a POST request, like submitting a form, then bootstrap files get loaded which breaks semantic-ui code.

Scripts included when making GET request:

![get-request](https://user-images.githubusercontent.com/43202296/47765953-72bd3900-dcf2-11e8-988e-2efbfa829d43.png)

Scripts included when making POST request:

![post-request](https://user-images.githubusercontent.com/43202296/47766028-c4fe5a00-dcf2-11e8-9ec9-32092d3998eb.png)

### What steps will reproduce the problem?
-> Make sure you've included Bootstrap in your AssetBundle class.
-> Create a bundle using npm.
-> Remove Bootstrap from AssetBundle class.
-> Also set forceCopy to true.
-> Make a POST request by submitting a form.

### What is the expected result?
Bootstrap files must not get loaded irrespective of the kind of HTTP request.

### What do you get instead?
Bootstrap files get loaded for POST request.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.2.1
| Operating system | Windows 10

**Comment by Alex-Code** [comment]
Are you using any Bootstrap widgets?

**Comment by XzAeRo** [comment]
Besides removing the asset dependencies as you already did, you should add this config in `frontend/config/web.php` or `backend/config/web.php`:

```php
'components' => [
    'assetManager' => [
        'bundles' => [
            'yii\bootstrap\BootstrapPluginAsset' => [
                'js'=>[]
            ],
            'yii\bootstrap\BootstrapAsset' => [
                'css' => []
            ]
        ]
    ],
    ...
],
```

I'm not sure if Semantic UI is a direct replacement of Bootstrap but notice that you may face some markup issues due to the fact that several Yii2 widgets follow Bootstrap html markups, and you will need to adapt them to follow the Semantic UI requirements.

**Comment by samdark** [comment]
Doesn't seem to be framework issue.
