### ISSUE TITLE
Each validator do something strange in internal logic

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#16852]
### What steps will reproduce the problem?
So... I want to get array of integer value
```php
    public function rules()
    {
        return [
            [['groups'], 'default', 'value' => [], 'skipOnEmpty' => false],
            [['groups'], 'each', 'rule' => ['integer'], 'skipOnEmpty' => false],
...
```
and put in throw setters (one or more like this)
```php
    public function setGroups($data): void
    {
        $this->_groups->inputIdList = $data;
    }
```
including case where this is nested setter in another form
```php
    public function setInputIdList($inputIdList): void
    {
        $this->_inputIdList = $inputIdList;

        $itemsIds = array_fill_keys($this->_existIdList, true);
        $inputItemIds = array_fill_keys($this->_inputIdList, true);
...
```
Also instead `array_fill_keys` may be a `\Throwable` cases ()
...

### What is the expected result?
`Each` validator don't use property of model inside. 

### What do you get instead?
Unexpected error
```
array_fill_keys() expects parameter 1 to be array, integer given
```

Validator put to a model attribute the element of array. What?! :1st_place_medal:  
```php
        foreach ($value as $k => $v) {
            $model->clearErrors($attribute);
            $model->$attribute = $v;
```
https://github.com/yiisoft/yii2/blob/91c96ff4525b498b6849abd986e9dcaad2883043/framework/validators/EachValidator.php#L141-L143

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | 7.2.11
| Operating system |

**Comment by rob006** [comment]
We should probably use `DynamicModel` here (or some dedicated class) instead of reusing real model and its setter/getters.

**Comment by rob006** [comment]
Can you propose "non-strange solution"?
