### ISSUE TITLE
Security - update database values after Logout

### ISSUE THREAD

**Issue by hra66** [yiisoft/yii2#16866]
**A security bug in yii2 - Logout function**
when user logout from yii2 project , you can change(update) databse field with "burp suite" software 

i solve this bug with change auth_key afterLogout for my project
but please check this problem and solve it for all

tnx

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.10
| Operating system | ubuntu 18.04

**Comment by samdark** [comment]
Please use https://www.yiiframework.com/security to report possible security issues. Thanks.
