### ISSUE TITLE
Request for option to override count query in ActiveDataProvider

### ISSUE THREAD

**Issue by crisps-for-breakfast** [yiisoft/yii2#16872]
### What steps will reproduce the problem?

Some of our backend GridViews are relatively rich and pull in a lot of related data from other tables or DB views, including some aggregated counts of related records

Not all of this related data affects the number of returned records

Currently the ActiveDataProvider builds the query to calculate the total number of records directly from its main query behind the scenes. This results in two heavy queries being run, instead of one heavy query for filtering, ordering, and displaying, and a slicker count query only focused on filtering

### Additional info

A relatively simple change could build this option into the basic ActiveDataProvider, here's an extension that I'm using in our project

    <?php
    
    namespace backend\components;

    use common\components\ActiveQuery;

    /** Class ActiveDataProvider */
    class ActiveDataProvider extends \yii\data\ActiveDataProvider
    {
        /** @var ActiveQuery  */
        public $countQuery = null;

        /**
         * @inheritdoc
         *
         * @throws \yii\base\InvalidConfigException
         */
        protected function prepareTotalCount()
        {
            if (isset($this->countQuery)) {
                $count = (int) $this->countQuery->count();
            } else {
                $count = parent::prepareTotalCount();
            }

            return $count;
        }
    }

Which can be used as follows

    public function search() {
        ...
        $query = Article::find();
        $query->andFilterWhere(['id' => $this->id]);

        $countQuery = clone $query;
        $query->joinWith(['commentCount']); 
       
        return new ActiveDataProvider([
            'query' => $query,
            'countQuery' => $countQuery,
            ...
        ]);
    }

Note that the the relation 'commentCount'  refers to a related DB view that counts the number of comments for each article. Overriding the count query avoids resolving this view twice

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15

**Comment by samdark** [comment]
If you need a custom query for count you can do it like the following:

```php
public function search() {
    ...
    $query = Article::find();
    $query->andFilterWhere(['id' => $this->id]);

    $countQuery = clone $query;
    $query->joinWith(['commentCount']); 
   
    return new ActiveDataProvider([
        'query' => $query,
        'totalCount' => $countQuery->count(),
        ...
    ]);
}
```

**Comment by crisps-for-breakfast** [comment]
Ah, thank you kindly!

Rather annoyed at myself for missing that..
My only qualm there would be that the two queries are potentially run at significantly different times, one during data gathering and one when the GridView is displayed

On looking at BaseDataProvider, it appears there may be a SEPARATE bug in that the function prepare(), when forcePrepare is set to true, will refresh the models and keys, but leave the count as the previous value

**Comment by crisps-for-breakfast** [comment]
Perhaps the following change to BaseDataProvider makes sense:

    public function prepare($forcePrepare = false)
    {
        if($forcePrepare) {
            $this->_totalCount = null;
        }
        if ($forcePrepare || $this->_models === null) {
            $this->_models = $this->prepareModels();
        }
        if ($forcePrepare || $this->_keys === null) {
            $this->_keys = $this->prepareKeys($this->_models);
        }
    }

Or potentially passing `$forcePrepare` down into `prepareModels()`..

**Comment by crisps-for-breakfast** [comment]
Hmm, think I'll stick with my extension.. it'll play better with `BaseDataProvider::refresh()`
