### ISSUE TITLE
Url::to function duplication in yii\web\Controlle->redirect() function

### ISSUE THREAD

**Issue by JorgeLiu** [yiisoft/yii2#16887]
### What steps will reproduce the problem?
yii\web\Controller.php
```
public function redirect($url, $statusCode = 302)
    {
        return Yii::$app->getResponse()->redirect(Url::to($url), $statusCode);
    }
```

$url has been Url::to() at ...->redirect(****)
but at yii\web\Response.php

```
public function redirect($url, $statusCode = 302, $checkAjax = true)
    {
        if (is_array($url) && isset($url[0])) {
            // ensure the route is absolute
            $url[0] = '/' . ltrim($url[0], '/');
        }
        $url = Url::to($url);
          .........
}
```

$url been Url::to()again

### What is the expected result?
none
### What do you get instead?
yii\web\Controller.php
```
public function redirect($url, $statusCode = 302)
    {
        return Yii::$app->getResponse()->redirect(Url::to($url), $statusCode);
    }
```

change
```
public function redirect($url, $statusCode = 302)
    {
        return Yii::$app->getResponse()->redirect($url, $statusCode);
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.0
| Operating system | win10+iis

**Comment by cebe** [comment]
there is a reason why it is there: https://github.com/yiisoft/yii2/issues/13430#issuecomment-274536432

do you have any issue with the current code? anything not working?
