### ISSUE TITLE
User Identity is not updated if input validation is set to false

### ISSUE THREAD

**Issue by combinator** [yiisoft/yii2#16893]
### What steps will reproduce the problem?
```
$user = new User()
$user->username = A;
$save() ; 
```

`Yii::$app->user->identity` (in debug console) shows username = A;
---
```
$user->username = B;
$user->save(false);
```

Yii::$app->user->identity still shows username as A .
However  calling 
`$user->save(); `
updates Yii::$app->user->identity to username B.

### What is the expected result?

Yii::$app->user->identity should be updated with or without validation turned on during saving of identity class

### What do you get instead?

Yii::$app->user->identity is not updated when validation is set to false (save(false) )

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.2
| Operating system | Centos7

**Comment by rob006** [comment]
How did you implemented `findIdentity()` in your `identityClass`?

**Comment by combinator** [comment]
```
 public static function findIdentity($Id = null )
    {
        return static::findOne(['Id' => $Id, 'IsActive' => self::STATUS_ACTIVE]);
      
    }
```

Replacing the code with 

```
 public static function findIdentity($Id = null )
    {
        return static::findOne($Id);
      
    }
```

fixed the problem. 
Thanks @rob006
