### ISSUE TITLE
NumberFormatter::POSITIVE_PREFIX doesn't prepend to integer with three digits or less by asInteger() function

### ISSUE THREAD

**Issue by ykawasaki683** [yiisoft/yii2#16900]
### What steps will reproduce the problem?
config/web.php code (other configs are skipped):
```
$config = [
    'components' => [
        'formatter' => [
             'numberFormatterTextOptions' => [
                 \NumberFormatter::POSITIVE_PREFIX => '+',
             ],
        ],
    ],
];
```
Then, call `Yii::$app->formatter->asInteger(10)` in view files. 

### What is the expected result?
+10

### What do you get instead?
10

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.11
| Operating system | CentOS 7.5.1804
| libicu version | 50.1.2

**Comment by cebe** [comment]
are you sure the PHP intl extension is enabled in your setup? Just created a test for it and it is working fine.

**Comment by ykawasaki683** [comment]
Sorry, this is not a bug.
The process `str_replace()` added by me causes this issue.
I apologize for making this wrong issue.
