### ISSUE TITLE
About Yii2's Testing Framework (by Codeception) 

### ISSUE THREAD

**Issue by talentant** [yiisoft/yii2#16901]
I have to say that the Yii2's testing module is very difficult to use. Is there a way to use the `phpunit` framework directly?

**Comment by cebe** [comment]
> Is there a way to use the `phpunit` framework directly?

sure, why not?

**Comment by talentant** [comment]
This directory structure looks good to me. ( Just a suggestion 😄 )
![default](https://user-images.githubusercontent.com/43669856/48891554-9e0cf100-ee76-11e8-9eeb-523774df3766.png)

 [https://github.com/yii2tech/project-template/tree/master/tests](https://github.com/yii2tech/project-template/tree/master/tests)
