### ISSUE TITLE
Add an ability to log only needed level

### ISSUE THREAD

**Issue by bobahvas** [yiisoft/yii2#16915]
Add an ability to log only needed level

For an example:
`profile_begin` and `profile_end` separetely

```
yiisoft\yii2\log\Target.php Line 187
//Add to the array
'profile_begin' => Logger::LEVEL_PROFILE_BEGIN,
'profile_end' => Logger::LEVEL_PROFILE_END,

// Change constant values
const LEVEL_PROFILE = 0x30;
const LEVEL_PROFILE_BEGIN = 0x10;
const LEVEL_PROFILE_END = 0x20;
```

### What steps will reproduce the problem?
Case 1: Set logger level `profile_begin`
Case 2: Set logger level `profile_end`
Case 3: Set logger level `profile`

### What is the expected result?
Case 1: Log only `profile_begin`
Case 2: Log only `profile_end`
Case 3: Log both `profile_begin` and `profile_end`

### What do you get instead?
Impossible

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      |  7.1.X
| Operating system | Centos 6.9

**Comment by samdark** [comment]
That's by design. It doesn't make sense to log a single profiling point w/o another one.
