### ISSUE TITLE
Validators (filters) do not work as expected

### ISSUE THREAD

**Issue by s1lver** [yiisoft/yii2#16917]
### What steps will reproduce the problem?
I have a **Test.php** model that takes values from an imported file.
I fill out the model fields like this:

```php
(new self([
    'field1' => $data[0],
    'field2' => $data[1],
    ...
]))->save();
```

The rules specify how to handle null values and trim spaces.

```php
public function rules() {
    return [
        [['field1', 'field2'], 'default'],
        [['field1', 'field2'], 'trim']
    ];
}
```
Source data:

```php 
$data = [
    '    test', ''
];
```

### What is the expected result?
I expect to get instead of writing a space - null and correct operation `trim()`.

```
field1 = test,
field2 = null
```

### What do you get instead?
However, a space and an uncirculated string are added to the database.

```
field1 =  '    test',
field = ''
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.0
| Operating system | Red Hat, Win10

**Comment by cebe** [comment]
this is expected, the order is wrong:

> https://www.yiiframework.com/doc/guide/2.0/en/input-validation#declaring-rules
> **The validation rules are evaluated in the order they are listed.**
