### ISSUE TITLE
yii\base\Controller::bindActionParams error passing $id array parameter to the action

### ISSUE THREAD

**Issue by danielemaggio** [yiisoft/yii2#16925]
have found a bug in passing an $id to the action as an array when using model with multiple attribute pKey;
( problem very similar to https://github.com/yiisoft/yii2/issues/12079 , but different case )

here a testbed example

```
class FooModel extends ActiveRecord{
    [...]
    public function primaryKey(){
        return ['site_id','key'];
    }
    [...]
}

```

```
class FooController extends yii\base\Controller{
    [...]
    public function actionView($id){

        $model = $this->findModel($id);
        [...]
    }
    [...]
    public function findModel($id){
        return FooModel::findOne($id);
    }
}
```

### What steps will reproduce the problem?

just launch http://localhost:8888/foo/view?id[site_id]=5&id[key]=test

### What is the expected result?

I should get $model as 
```
[
   'site_id'=>'5',
   'key'=>'test',
    'value'=>'example
]

```
### What do you get instead?

BadRequestHttpException -> Invalid data received for parameter "id"

### Additional info

I debugged and found the bug still present in **bindActionParams** function at line **131** (at the actual master on git on date 11/30/2018 )

```
/**
     * Binds the parameters to the action.
     * This method is invoked by [[\yii\base\Action]] when it begins to run with the given parameters.
     * This method will check the parameter names that the action requires and return
     * the provided parameters according to the requirement. If there is any missing parameter,
     * an exception will be thrown.
     * @param \yii\base\Action $action the action to be bound with parameters
     * @param array $params the parameters to be bound to the action
     * @return array the valid parameters that the action can run with.
     * @throws BadRequestHttpException if there are missing or invalid parameters.
     */
    public function bindActionParams($action, $params)
    {
        if ($action instanceof InlineAction) {
            $method = new \ReflectionMethod($this, $action->actionMethod);
        } else {
            $method = new \ReflectionMethod($action, 'run');
        }

        $args = [];
        $missing = [];
        $actionParams = [];
        foreach ($method->getParameters() as $param) {
            $name = $param->getName();
            if (array_key_exists($name, $params)) {
    ------>   if ($param->isArray()) { <------
                    $args[] = $actionParams[$name] = (array) $params[$name];
                } elseif (!is_array($params[$name])) {
                    $args[] = $actionParams[$name] = $params[$name];
                } else {
                    throw new BadRequestHttpException(Yii::t('yii', 'Invalid data received for parameter "{param}".', [
                        'param' => $name,
                    ]));
                }
                unset($params[$name]);
            } elseif ($param->isDefaultValueAvailable()) {
                $args[] = $actionParams[$name] = $param->getDefaultValue();
            } else {
                $missing[] = $name;
            }
        }
```

the if condition `if ($param->isArray()) {` refer to param :
```
object(ReflectionParameter)#97 (1) {
  ["name"]=>
  string(2) "id"
}
```

that will return always false since will never be an array since probably it was done to check params[$name]) , so i've corrected the if on the correct parameter as the below elseif
```
if (array_key_exists($name, $params)) {
   ------>   if (is_array($params[$name])) { <------
                    $args[] = $actionParams[$name] = (array) $params[$name];
                } elseif (!is_array($params[$name])) {
                    $args[] = $actionParams[$name] = $params[$name];
                } else {
```

now parameter is passed at the action also if it is an array and the action is launched

**Comment by cebe** [comment]
This line is correct, it checks whether you have declared the action param as array type:

```php
    public function actionView(array $id){
        // ...
    }
```

the above declaration allows passing an array of ids.

**please note** that passing an array like that to `::findOne($id)` is a security issue!

See https://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes#is-my-application-affected

**Comment by danielemaggio** [comment]
Thanks cebe, 
I've tried also the casting in the declaration as you shown, before submit the request but i had always BadRequestHttpException since it had not passed `if ($param->isArray()) {` anyway, don't know, probably caused by an old 2.0.6 yii version...

I agree with you for the vulnerability and to avoid every problem -> `::findOne(['site_id'=>'5','key'=>'test'])`

**Comment by cebe** [comment]
> probably caused by an old 2.0.6 yii version...

Please try with the latest version and report back if the problem still exists.
