### ISSUE TITLE
Gii imrovements

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#1692]
I was told by some Yii developers that thay need such features in Gii:

- [ ] Migration generating/applying.

I think this can be done, its useful. Also when developer for example dont have shell access for stage server, and want to check if there are some migrations applied or pending. Yes this features fo course can be solved by some CI server + shell scripts, but i think its worth to have it out of the box. 
@qiangxue whats your thoughts about it?

**Comment by samdark** [comment]
It's now in the console version. I don't think it needs to be in gii.

**Comment by michael-vostrikov** [comment]
Hello. I think the "--fields" options in console command is a little different thing. We need to write all fields manually, but there are cases when it's more convenient to generate all definitions automatically - when we have a few big tables with a lot of fields, with foreign keys, comments, indexes, etc.

For example:
I develop some separate module in my application with its own tables. I try different variants for table structure, change field definitions, and do it in some GUI tool like PHPMyAdmin or HeidiSQL. Then I select specific variant, try it in work, and only now I need to create migration which can be committed. To write all definitions manually is boring and tediously, and there is a possibility to forget something.

I have created my version of such migration generator, it supports new migration synatax.
https://github.com/michael-vostrikov/yii2-migration-generator

**Comment by schmunk42** [comment]
@michael-vostrikov That looks great. :+1:

**Comment by JulianNL** [comment]
@michael-vostrikov could you add this to packagist/composer?
