### ISSUE TITLE
Memory leek when use batch

### ISSUE THREAD

**Issue by DMGPage** [yiisoft/yii2#16937]
I opened new issue, because all other issues, related to batch and memory problems, are closed. I have problems with console task, which often runs in 90% memory usage and Linux automatically kills this process. I tested each peace of code, to find when memory is overflowed, and find out, that it happens in Query::batch. Here is my code sample:

```
$query = Logs::find();
echo "Before batch \n";
sleep(10);
echo "Batch \n";

foreach ($query->batch() as $rows) {
    echo "After Batch \n";
    sleep(10);
}
```
Before batch memory usage is around 0,4%, but when batch is called, memory usage jumps to 34,4% which is around 2711MB. I use "htop", to get memory usage by process.

Currently I use Yii 2.0.12, but I tested it with Yii 2.0.14 and did not see any differences. Even if I replace "batch" with "each" it does not change anything. Table contains about 2 million records.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6.14
| Database version      | PostgreSQL 9.3.6
| Operating system | Ubuntu

**Comment by samdark** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/db-query-builder#batch-query-mysql

**Comment by DMGPage** [comment]
I use PostgreSQL, but I guess, you want to say, it's not yii, but PDO problem? So this means, that Query::batch should not be used at all?

**Comment by samdark** [comment]
Yes, that's how PDO works. By default it fetches all data at once.

**Comment by codru** [comment]
The doc has workaround for MySQL. Do we have any for PostgreSQL? @DMGPage have you found a solution?
