### ISSUE TITLE
migration generation with prefix

### ISSUE THREAD

**Issue by Isitar** [yiisoft/yii2#16941]
is there a reason why the migration templates (createTableMigration.php, addColumnMigration.php etc.) do not have the table prefix syntax `{{%tablename}}` ?

### What steps will reproduce the problem?
php yii migrate/create add_xxx_column_to_yyy_table --fields="xxx:integer"
### What is the expected result?
```
$this->addColumn('{{%yyy}}', 'xxx', $this->integer());
```
### What do you get instead?
```
$this->addColumn('yyy', 'xxx', $this->integer());
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system |Windows

**Comment by rob006** [comment]
There is a switch for enabling prefix in generated migrations.

https://github.com/yiisoft/yii2/blob/379a2002dd8af037d86e1db1a6a1607f0775478a/framework/console/controllers/MigrateController.php#L115

 The question is why it is disabled by default and why we even need it - does adding prefix everywhere has any drawbacks?

**Comment by rob006** [comment]
I'm for changing default value of `$useTablePrefix` to `true`. We could also mark this property as deprecated, but I'm not sure if it makes any sense.
