### ISSUE TITLE
migration comment syntax  error

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#16940]
### What steps will reproduce the problem?
create migrate file in console/migrations/m130524_201442_init.php
![default](https://user-images.githubusercontent.com/1888094/49572275-62921c80-f976-11e8-92ff-c47d64534d83.png)

### What do you get instead?
![default](https://user-images.githubusercontent.com/1888094/49572245-5b6b0e80-f976-11e8-8c34-c9b26bcc36b7.png)

i  am instead with 
" ALTER TABLE `bs_pcategory` modify column `name` VARCHAR(32) COMMENT 'abc产品分类名称';   "

that's ok !!!

![default](https://user-images.githubusercontent.com/1888094/49572429-bbfa4b80-f976-11e8-8bc3-ccfa5bf3fa75.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16-dev
| PHP version      | 7.1.24
| Mysql version   | 8.0.13
| Operating system |win10 x64

**Comment by tomlutzenberger** [comment]
You can add a comment to a table using `addCommentOnTable()` since 2.0.8
Have a look at https://www.yiiframework.com/doc/api/2.0/yii-db-migration#addCommentOnTable()-detail

**Comment by Isitar** [comment]
can you tell us what your value of `$tableOptions` is?

ps: for better readability PASTE the code instead of posting a screenshot. You can easily style it using three ` (backticks) or indent it with 4 spaces

**Comment by samdark** [comment]
Is that connected with the language used?

**Comment by alexeevdv** [comment]
@samdark It looks like a bug. Generated SQL is incorrect because `COMMENT` is not allowed on `CHANGE COLUMN`. `MODIFY COLUMN` should be used instead.
Steps to reproduce:
```SQL
CREATE TABLE users (name varchar(255));
ALTER TABLE users CHANGE COLUMN name name COMMENT 'username';
```
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COMMENT 'username'' at line 1`
