### ISSUE TITLE
checkbox option accept selected instead of checked

### ISSUE THREAD

**Issue by jai3232** [yiisoft/yii2#16967]
### What steps will reproduce the problem?

` <?= $form->field($model, 'xxx')->checkbox(['value' => 1, 'checked' => 'true', 'selected' => true]) ?>`

### What is the expected result?

`<input type="checkbox" id="xxx" name="Question[xxx]" value="1" checked>`

### What do you get instead?

`<input type="checkbox" id="xxx" name="Question[xxx]" value="1" selected>`

checkbox is not checked although checked is true and selected is omitted.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.0.32
| Operating system | Oracle Linux Server 7.6

**Comment by bizley** [comment]
This is by design - active field checkbox is checked only if `$model->xxx === $value`. And `selected` as unrecognized special option for this field is just passed to renderer as-is.
