### ISSUE TITLE
The require statements need to be updated

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#16968]
The default config.php file generated has the statements 

```
$params = array_merge(
    require (__DIR__ . '/../../common/config/params.php'),
    require (__DIR__ . '/../../common/config/params-local.php'),
    require (__DIR__ . '/params.php'),
    require (__DIR__ . '/params-local.php')
);
```

which raise an error when you have php codesniffer configured

> require is a statement and not a function no parentheses are required

We might updae it accordingly.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by rob006** [comment]
Framework core does not generate anything like that. And app template was fixed long ago: https://github.com/yiisoft/yii2-app-advanced/commit/841134d005aa7fcfd7e232165254c71250117567
