### ISSUE TITLE
Improve query performance for "in" conditions

### ISSUE THREAD

**Issue by yeahcheung** [yiisoft/yii2#16976]
### What steps will reproduce the problem?
If you use the combined "in" query, "querybuilder" generates the following sql query:
`SELECT * FROM `kld_order_parts` WHERE  (`order_number`, `service_id`) IN (('20181217-4976', 60),('20181217-4976', 85))`

### What is the expected result?
`SELECT * FROM `kld_order_parts` WHERE ((`order_number` = '20181217-4976' AND `service_id` = 60) OR (`order_number` = '20181217-4976' AND `service_id` = 85))`
### What do you get instead?
rewrite buildCompositeInCondition function of vendor/yiisoft/yii2/db/QueryBuilder.php

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 7.1
| Operating system |centos

**Comment by lubosdz** [comment]
I don't think your SQL syntax is valid.
`IN` clause normally takes cardinal inputs.
I have never seen complex values (arrays) there.
What is your database?

For unusual syntax you may want to use your own custom SQL query, e.g. 

```
$rows = Yii::$app->createCommand("SELECT * FROM kld_order_parts 
WHERE (order_number, service_id) 
IN (('20181217-4976', 60),('20181217-4976', 85))")
->queryAll();
```

Yii's query builder is not a solution for everything, it is great for common SQL syntax.

https://www.w3schools.com/sql/sql_in.asp

**Comment by cebe** [comment]
Which DBMS are you using? The generated syntax is valid for MySQL:

> https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_in
> ```sql
> mysql> SELECT (3,4) IN ((1,2), (3,4));
>         -> 1
> mysql> SELECT (3,4) IN ((1,2), (3,5));
>         -> 0
>  ```

**Comment by gmastro** [comment]
@yeahcheung if you read carefully on the [https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_in](https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_in) the next paragraphs dictates;

> You should never mix quoted and unquoted values in an IN list because the comparison rules for quoted values (such as strings) and unquoted values (such as numbers) differ.....

Thus, your query should be in the following format

```sql
SELECT * FROM kld_order_parts 
WHERE (order_number, service_id) 
IN (('20181217-4976', '60'),('20181217-4976', '85'));
```

IMHO, `createCommand` has saved me more than once as it is not easy to reproduce each and every db engine specifics, especially when you are working with multiple DBs at once. Surely -though- there are some defaults in the framework which, you have to bypass and recreate them to match your preferences, but you'll learn something.

Here is an example how to make this work for you;

```sql
SET NAMES utf8 COLLATE utf8_unicode_ci;

DROP TABLE IF EXISTS `example_order_parts`;
CREATE TABLE `example_order_parts`( 
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` SMALLINT(8) UNSIGNED NOT NULL,
  `order_number` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

INSERT INTO `example_order_parts`( `order_number`, `service_id` ) VALUES
('20181217-4930', 60),
('20181217-4950', 60),
('20181217-4976', 60),
('20181217-4976', 85),
('20181217-4976', 90);

SELECT * FROM `example_order_parts` WHERE (order_number, service_id) IN (('20181217-4976', '60'),('20181217-4976', '85'));
```

Generate the model via gii, and then hack your way to get wanted output. Check the last `public method`

i.e.

```php
namespace frontend\models;

use Yii;

/**
 * This is the model class for table "example_order_parts".
 *
 * @property string $id
 * @property int $service_id
 * @property string $order_number
 */
class ExampleOrderParts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'example_order_parts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['service_id', 'order_number'], 'required'],
            [['service_id'], 'integer'],
            [['order_number'], 'string', 'max' => 32],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'service_id' => 'Service ID',
            'order_number' => 'Order Number',
        ];
    }
    
    /**
     * This will do the trick. Note that this is not safe unless if the data you provide within the values array is sanitized. In this example I've omit any type of filtering, you will have to do it yourself
     * 
     * @params: $values - array - what you are looking for
     */
    public function findByOrderNumberServiceId( $values )
    {
        $values = array_map( function( $i ) { return sprintf( "('%s')", implode( "','", $i ) ); }, $values );
        $values = implode( ',', $values );
        
        return Yii::$app->db->createCommand( "SELECT * FROM `example_order_parts` WHERE (`order_number`,`service_id`) IN( {$values} )" )->queryAll( );
        
        // or if you prefer to get that on a model
        //~ return self::find( )->where( "(`order_number`,`service_id`) IN( {$values} )" )->all( );
    }
}

```

To get your result just run somewhere in your api

```php

echo '<pre>';
VarDumper::dump( \frontend\models\ExampleOrderParts::findByOrderNumberServiceId( [ [ '20181217-4976', 60 ], [ '20181217-4976', 85 ] ] ), 10, true );
echo '</pre>';

```

Hope it helped

**Comment by yeahcheung** [comment]
> @yeahcheung if you read carefully on the https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_in the next paragraphs dictates;
> 
> > You should never mix quoted and unquoted values in an IN list because the comparison rules for quoted values (such as strings) and unquoted values (such as numbers) differ.....
> 
> Thus, your query should be in the following format
> 
> ```sql
> SELECT * FROM kld_order_parts 
> WHERE (order_number, service_id) 
> IN (('20181217-4976', '60'),('20181217-4976', '85'));
> ```
> 
> IMHO, `createCommand` has saved me more than once as it is not easy to reproduce each and every db engine specifics, especially when you are working with multiple DBs at once. Surely -though- there are some defaults in the framework which, you have to bypass and recreate them to match your preferences, but you'll learn something.
> 
> Here is an example how to make this work for you;
> 
> ```sql
> SET NAMES utf8 COLLATE utf8_unicode_ci;
> 
> DROP TABLE IF EXISTS `example_order_parts`;
> CREATE TABLE `example_order_parts`( 
>   `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
>   `service_id` SMALLINT(8) UNSIGNED NOT NULL,
>   `order_number` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
>   PRIMARY KEY(`id`)
> ) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
> 
> INSERT INTO `example_order_parts`( `order_number`, `service_id` ) VALUES
> ('20181217-4930', 60),
> ('20181217-4950', 60),
> ('20181217-4976', 60),
> ('20181217-4976', 85),
> ('20181217-4976', 90);
> 
> SELECT * FROM `example_order_parts` WHERE (order_number, service_id) IN (('20181217-4976', '60'),('20181217-4976', '85'));
> ```
> 
> Generate the model via gii, and then hack your way to get wanted output. Check the last `public method`
> 
> i.e.
> 
> ```
> namespace frontend\models;
> 
> use Yii;
> 
> /**
>  * This is the model class for table "example_order_parts".
>  *
>  * @property string $id
>  * @property int $service_id
>  * @property string $order_number
>  */
> class ExampleOrderParts extends \yii\db\ActiveRecord
> {
>     /**
>      * {@inheritdoc}
>      */
>     public static function tableName()
>     {
>         return 'example_order_parts';
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     public function rules()
>     {
>         return [
>             [['service_id', 'order_number'], 'required'],
>             [['service_id'], 'integer'],
>             [['order_number'], 'string', 'max' => 32],
>         ];
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     public function attributeLabels()
>     {
>         return [
>             'id' => 'ID',
>             'service_id' => 'Service ID',
>             'order_number' => 'Order Number',
>         ];
>     }
>     
>     /**
>      * This will do the trick. Note that this is not safe unless if the data you provide within the values array is sanitized. In this example I've omit any type of filtering, you will have to do it yourself
>      * 
>      * @params: $values - array - what you are looking for
>      */
>     public function findByOrderNumberServiceId( $values )
>     {
>         $values = array_map( function( $i ) { return sprintf( "('%s')", implode( "','", $i ) ); }, $values );
>         $values = implode( ',', $values );
>         
>         return Yii::$app->db->createCommand( "SELECT * FROM `example_order_parts` WHERE (`order_number`,`service_id`) IN( {$values} )" )->queryAll( );
>         
>         // or if you prefer to get that on a model
>         //~ return self::find( )->where( "(`order_number`,`service_id`) IN( {$values} )" )->all( );
>     }
> }
> ```
> 
> To get your result just run somewhere in your api
> 
> ```
> 
> echo '<pre>';
> VarDumper::dump( \frontend\models\ExampleOrderParts::findByOrderNumberServiceId( [ [ '20181217-4976', 60 ], [ '20181217-4976', 85 ] ] ), 10, true );
> echo '</pre>';
> ```
> 
> Hope it helped

Thank you! This is a good solution. If this can be changed from framework level, It will perfact.

**Comment by rob006** [comment]
Why do you want to change it?
