### ISSUE TITLE
yii\base\ErrorHandler.php handleFatalError(), why use exit(1)?

### ISSUE THREAD

**Issue by liuyibao** [yiisoft/yii2#16972]
```
public function handleFatalError()
    {
        unset($this->_memoryReserve);
        // load ErrorException manually here because autoloading them will not work
        // when error occurs while autoloading a class
        if (!class_exists('yii\\base\\ErrorException', false)) {
            require_once __DIR__ . '/ErrorException.php';
        }
        $error = error_get_last();
        if (ErrorException::isFatalError($error)) {
            if (!empty($this->_hhvmException)) {
                $exception = $this->_hhvmException;
            } else {
                $exception = new ErrorException($error['message'], $error['type'], $error['type'], $error['file'], $error['line']);
            }
            $this->exception = $exception;
            $this->logException($exception);
            if ($this->discardExistingOutput) {
                $this->clearOutput();
            }
            $this->renderException($exception);
            // need to explicitly flush logs because exit() next will terminate the app immediately
            Yii::getLogger()->flush(true);
            if (defined('HHVM_VERSION')) {
                flush();
            }
            exit(1);
        }
    }
```

why use exit(1)?  suggest throw exception!

### What steps will reproduce the problem?
The script stops directly， but i want log something.
### What is the expected result?
throw exception
### What do you get instead?
not

### Additional info
not
| Q                | A
| ---------------- | ---
| Yii version      | ~2.0.9
| PHP version      | php5.6.30
| Operating system | mac/ubuntu14.04

**Comment by Alex-Code** [comment]
What are you trying to log? Logs are flushed before `exit`.

Also, You're 6 versions behind! If possible I'd upgrade to see if that resolves your issue.

**Comment by liuyibao** [comment]
> What are you trying to log? Logs are flushed before `exit`.
> 
> Also, You're 6 versions behind! If possible I'd upgrade to see if that resolves your issue.

when i use phpexcel, like this:
```
try {
        $excel = \PHPExcel_IOFactory::load('file_path.xls');
        $arr = $excel->getActiveSheet()->toArray(null, true, true, true);
} catch (\Exception $e) {
        //todo log
}
```
when the xls has some format error, the catch block can not execute.

thanks.

**Comment by Alex-Code** [comment]
PHPExcel has been deprecated too, have you considered upgrading to https://github.com/PHPOffice/PhpSpreadsheet and seeing if that works.

**Comment by alexeevdv** [comment]
The problem you have is not related to Yii. It is related to PHP5. It can't handle fatal errors in catch block. You need to upgrade to 7.x in order to be able to do that.

```php
try {
    new NonExistingClass;
} catch (Error $e) {
    // This will work only for PHP 7.x
    echo 'Catched!';
}
```

**Comment by liuyibao** [comment]
> PHPExcel has been deprecated too, have you considered upgrading to https://github.com/PHPOffice/PhpSpreadsheet and seeing if that works.

Thank you, I will consider！

**Comment by liuyibao** [comment]
> The problem you have is not related to Yii. It is related to PHP5. It can't handle fatal errors in catch block. You need to upgrade to 7.x in order to be able to do that.
> 
> ```
> try {
>     new NonExistingClass;
> } catch (Error $e) {
>     // This will work only for PHP 7.x
>     echo 'Catched!';
> }
> ```

PHP7 not work too, because the function has code 'exit(1)'

**Comment by alexeevdv** [comment]
It will work in PHP7 because it can be catched in try/catch block. This error will not even get to the Yii errorHandler

**Comment by liuyibao** [comment]
> It will work in PHP7 because it can be catched in try/catch block. This error will not even get to the Yii errorHandler

You are right!
