### ISSUE TITLE
APC cache is being required by default

### ISSUE THREAD

**Issue by emuthomi** [yiisoft/yii2#16970]
### What steps will reproduce the problem?
I have updated yii2 through composer from Yii v2.0.5 to v2.0.15.1.

### What is the expected result?
I expected no major breaking issue, and my application to work as is
### What do you get instead?
```
Invalid Configuration – yii\base\InvalidConfigException
ApcCache requires PHP apc extension to be loaded.
```
 in C:\xampp71\htdocs\myapp\vendor\yiisoft\yii2\caching\ApcCache.php line 47
The offending code is: 

```
public function init()
    {
        parent::init();
        $extension = $this->useApcu ? 'apcu' : 'apc';
        if (!extension_loaded($extension)) {
            throw new InvalidConfigException("ApcCache requires PHP $extension extension to be loaded.");
        }
    }
```
My web.php config file:

```
'cache' => [
      'class' => 'yii\caching\FileCache',
 ],
```

I have tried changing the config to below but the issue couldn't be resolved:
```
'cache' => [
      'class' => 'yii\caching\ApcCache',
      'useApcu' => true,
 ],
```
The only fix that worked is to explicitly change 
``` 
public $useApcu = false;
```
in the ApcCache class to 
```
public $useApcu = true;
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      | 7.1.1
| PHP Compiler    | MSVC14 (Visual C++ 2015)
| Architecture      | x86
| Apache Version   | Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1
| Operating system | Windows 7 Professional Edition Service Pack 1

**Comment by emuthomi** [comment]
After keenly looking at the Stack Trace, turns out the issue emanates from the urlManager configuration...  when the ```enablePrettyUrl``` property is set to ```true``` , for some reason the urlManager is trying to look into the APC cache.

**Comment by emuthomi** [comment]
So the safest solution on my part now is to set ```cache``` property of urlManager to ```false```, and leave the ```ApcCache``` core class the way it was.

**Comment by Alex-Code** [comment]
I'd still search for any APC usage, `UrlManager` should just use which ever cache component you've set and not exclusively `APC`

**Comment by emuthomi** [comment]
Another thing I've noticed, any reference to ```Yii::$app->cache...``` defaults to ApcCache.

I don't have any other config files apart from the standard ones in the config folder.

**Comment by emuthomi** [comment]
> I'd still search for any APC usage, `UrlManager` should just use which ever cache component you've set and not exclusively `APC`

My huge config file had another reference of ApcCache several lines down which I had included to do some tests. Stupid me.

This issue now stands closed.
