### ISSUE TITLE
renderDynamic and Html::tag

### ISSUE THREAD

**Issue by free6k** [yiisoft/yii2#16985]
because of escaping value in html::tag renderDynamic dont work.

### What steps will reproduce the problem?
```
 Html::hiddenInput(null, $this->view->renderDynamic('return 1;'));
```

### What is the expected result?
```
<input type="hidden" value="<![CDATA[YII-DYNAMIC-0]]>">
```

### What do you get instead?
```
<input type="hidden" value="&lt;![CDATA[YII-DYNAMIC-0]]&gt;">
```

### Additional info
How fix it right? I see two possible way.

First: detect dynamic attribute in [BaseHtml::renderTagAttributes](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1933) and not escape

Second: add the escaped key to [DynamicContentAwareTrait::updateDynamicContent](https://github.com/yiisoft/yii2/blob/master/framework/base/DynamicContentAwareTrait.php#L70)

What do you think?

| Q                | A
| ---------------- | ---
| Yii version     2.0.15.1 | 
| PHP version      7.0 | 
| Operating system Debian Jessie |

**Comment by GHopperMSK** [comment]
Is it still actual?

When I add
```
<?= Html::hiddenInput(null, $this->renderDynamic('return 1;')); ?>
```
in view template, I get
```
<input type="hidden" value="1">
```
on the web page.

**Comment by samdark** [comment]
Seems it isn't. Thanks for checking.

**Comment by rob006** [comment]
I'm able to reproduce it (you need to have full page cache enabled).

Although I'm not sure if we should introduce some magic check for this case. Usually you should use `renderDynamic()` to whole whole input, not only one attribute.
