### ISSUE TITLE
Yii2 frontend session resets on every page load

### ISSUE THREAD

**Issue by TomaIvanovTomov** [yiisoft/yii2#16994]
The frontend session is reset on every reload. The backend one works fine. This is my config:
```
'session' => [
        'name' => 'advanced-frontend',
        'savePath' => __DIR__ . '/../runtime/sessions',
],
```
No file is created in the sessions folder. The backend configuration is the same ( with different session name of course ) and it works as expected. Don't know what more to provide to reproduce the problem. What can cause this behaviour ?
My Yii2 version is 2.15.0.1. I am working on Ubuntu 18 and Apache2.

**Comment by rob006** [comment]
> Don't know what more to provide to reproduce the problem.

Can you reproduce this issue on fresh advanced template? It is probably configuration issue, since it is working fine on backend.
