### ISSUE TITLE
Usage of utf8_encode() in \yii\web\Request::resolvePathInfo() makes Yii depend on the php-xml extension

### ISSUE THREAD

**Issue by MysteryDragon** [yiisoft/yii2#16991]
### What steps will reproduce the problem?
Just try to route on something like `/test%F2%FB` without mentioned extension.

### What is the expected result?
Well, 404

### What do you get instead?
Ta-daaa, 500

### Additional info

https://github.com/yiisoft/yii2/blob/572e5f6655f279df574fe4937406ec04a6852cbc/framework/web/Request.php#L902-L926

It happens because `utf8_encode()` moved in core only in PHP 7.2.

I was intrigued, so I open https://yiipowered.com, and start to test :)
First catch: https://craftcms.com/test%F2%FB

| Q                | A
| ---------------- | ---
| Yii version      | any (catched in 2.0.14)
| PHP version      | up to 7.1 (catched in 7.1)
| Operating system | catched in CentOS 7 with PHP from remi repo

P.S.: Perhaps I did a lot of grammar mistakes in my sentences. Sorry.)

**Comment by samdark** [comment]
We can instead use something like https://github.com/symfony/polyfill-php72/blob/master/Php72.php#L24

**Comment by GHopperMSK** [comment]
Clear installation. Why don't I get 500?
![screenshot_20190102_234029](https://user-images.githubusercontent.com/19670887/50611585-0b855600-0ee8-11e9-8298-a2fe96394559.png)

**Comment by samdark** [comment]
Clear installation of PHP from package manager?
