### ISSUE TITLE
No warning or error description when we use constraint name more than 64 chars

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#17002]
I am not sure if you guys would own it or leave it on MYSQL.

### What steps will reproduce the problem?
`$this->addForeignKey('FK_WEBHOOK_ID_SUBSCRIPTION_HISTORY', $this->_table, 'webhook_event_id', "{{%webhook_events}}", 'id');`

### What is the expected result?
The error on console should show a bit description about the excessive length of the foreign key exceeding 64 chars
### What do you get instead?

> .Exception: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
> The SQL being executed was: ALTER TABLE `tpsms_subscription_history` ADD CONSTRAINT `FK_WEBHOOK_ID_SUBSCRIPTION_HISTORY` FOREIGN KEY (`webhook_event_id`) REFERENCES `tpsms_webhook_events` (`id`)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.2
| Operating system | Ubuntu

**Comment by bizley** [comment]
This is DBMS specific so I don't think that Yii should throw any warnings.

Some examples [limits]:
- [MySQL](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html) [64/63],
- [PostgreSQL](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) [63]
- Oracle [128/30?]
- MSSQL [128]

**Comment by samdark** [comment]
Agree.

**Comment by buttflattery** [comment]
@bizley yes i already doubted it but this is annoying as there isnt any meaningful error string which makes the developer confused about what made this error to pop up, I wasted approx 1 hour to figure out that my constraint name is exceeding the given limit.

**Comment by rob006** [comment]
@buttflattery `FK_WEBHOOK_ID_SUBSCRIPTION_HISTORY` has 34 chars, why do you think that 64 chars limit is a problem?
