### ISSUE TITLE
QueryBuilder fails when over 1000 records

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#17015]
Hi

I am experiencing a similar issue to [this](https://github.com/yiisoft/yii2/issues/16073) and also getting:

> strtoupper() expects parameter 1 to be string, object given

at line `yiisoft\yii2\db\QueryBuilder.php:1546`

I have the following query in:

```php
VtCol::find()
          ->alias('V')
          ->innerJoinWith('site')
          //->innerJoinWith('cardNumber') -> Causes Error
          //->joinWith('pat')  -> Causes Error
          ->where(['V.DEL_DT' => null])
          ->andWhere(['<=', new Expression("TRUNC(TO_DATE(V.PRO_DATE, 'YYYYMMDD'))"), new Expression("TRUNC(TO_DATE('" . $quarterEndDate . "', 'YYYYMMDD'))")])
          ->andWhere(['V.FLWP_IND' => null])
          ->andWhere(['V.PASS_FOR_PAY' => null])
          ->andWhere(['V.SIGNED' => 'Y']) 
          ->all();
```

One of my relations looks like this:

```php
public function getCardNumber()
    {
        return $this->hasOne(CardNumber::className(), ['PARTICIPANT_ID' => 'PARTICIPANT_ID_ID'])
                    ->andOnCondition(['CARD_NUMBER.CARD_TYPE_CD' => 35])
                    ->andOnCondition(['CARD_NUMBER.DEL_DT' => null]);
    }
```

I have spent some time tracing through this. I started by limiting the rows the query returned and it runs fine if below 1000 rows. I also ran the raw query in TOAD and the whole thing returns fine, it's only looking for 1400 rows to start with.

I have noticed that it returns the first 1000 rows ok, but when it comes to build the condition for the remaining 400 rows it drops the operator and just uses the condition Objects.

The first time it runs fine

![capture](https://user-images.githubusercontent.com/6732997/50695141-3370d880-1012-11e9-8fb4-908f3c2b60de.PNG)

Expanding the $condition var:

![image](https://user-images.githubusercontent.com/6732997/50695364-cc9fef00-1012-11e9-8009-4a21aadf0901.png)

The second though, at some point there appears to be no initial operator and just the `yii\db\conditions\InCondition` object

![capture3](https://user-images.githubusercontent.com/6732997/50695187-5b603c00-1012-11e9-8540-9be9e9c2d538.PNG)

### What steps will reproduce the problem?
Trying to load relations with over 1000 rows

### What is the expected result?
That the data returns with joined results
### What do you get instead?
> strtoupper() expects parameter 1 to be string, object given

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.4
| Operating system | Windows XAMPP

**Comment by rob006** [comment]
Fix for #16073 was not released yet. Can you try `master` branch?

**Comment by rugabarbo** [comment]
Add label `Oracle`, please.

**Comment by jonny7** [comment]
Hi @rob006 

I tried this and it worked ok - :)
I didn't realise it wasn't in the latest version, just saw it was closed and assumed it was!
Good to have it in there, certainly a problem for Oracle at times :-)
