### ISSUE TITLE
pasting tab(value)number into gridview filter leads to DB Exception

### ISSUE THREAD

**Issue by SSiwek** [yiisoft/yii2#17033]
### What steps will reproduce the problem?
Pasting a number with leading tab via keyboard ^V into a filter attribut which has numbertype in db does lead to pdoexception

### What is the expected result?
tab has to be filtered before giving to sql

### What do you get instead?

PDOException: SQLSTATE[HY000]: General error: 1722 OCIStmtExecute: ORA-01722: invalid number
 (/usr/src/redhat/BUILD/php-7.0.18/ext/pdo_oci/oci_statement.c:159) in /var/www/html/intranet7/vendor/yiisoft/yii2/db/Command.php:1258
Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 1722 OCIStmtExecute: ORA-01722: invalid number
(/usr/src/redhat/BUILD/php-7.0.18/ext/pdo_oci/oci_statement.c:159)
The SQL being executed was: SELECT COUNT(*) FROM "TITEL" WHERE "TITELNR"='	8762'
Error Info: Array
(
    [0] => HY000
    [1] => 1722
    [2] => OCIStmtExecute: ORA-01722: invalid number
 (/usr/src/redhat/BUILD/php-7.0.18/ext/pdo_oci/oci_statement.c:159)
)
↵
Caused by: PDOException
SQLSTATE[HY000]: General error: 1722 OCIStmtExecute: ORA-01722: invalid number
(/usr/src/redhat/BUILD/php-7.0.18/ext/pdo_oci/oci_statement.c:159)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.0.18
| Operating system | redhat

**Comment by samdark** [comment]
Since we cannot assume type of the grid filter, we can't type-cast it by default. You can fix it in your search model.
