### ISSUE TITLE
Captcha doesn't change when I refresh the page

### ISSUE THREAD

**Issue by ava-da** [yiisoft/yii2#17036]
### What steps will reproduce the problem?
I use yii\captcha\ in active form.  the problem is, when I refresh page captcha didn't change.

I add this to my controller :
    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_DEV ? 'test' : null,
                'testLimit' => 1,
            ],
        ];
    }
and this to active form in view file:
<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
            'captchaAction' => '/contactus/frontend/captcha',
        ]) ?>
and add this rule to model:
['verifyCode', 'captcha', 'captchaAction'=>'/contactus/frontend/captcha']

### What is the expected result?
when I refresh the page I see a new Captcha
### What do you get instead?
when I refresh the page, the same Captcha appear

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  5.6.33
| Operating system | Ubuntu 14.04

**Comment by samdark** [comment]
Are you in development mode or in production mode?

**Comment by samdark** [comment]
Does it refresh when you fail to enter a value?

**Comment by ava-da** [comment]
yes, if I submit the form it changed, but if I just refresh the page it shows the same captcha

**Comment by samdark** [comment]
Is that a problem?

**Comment by ava-da** [comment]
in other applications, captcha is changed on page refresh, and my clients expect that the captcha works like others.

**Comment by samdark** [comment]
I see. Since security isn't affected, it won't be changed in the framework itself. That is actually done to make it more user friendly. You can extend from https://github.com/yiisoft/yii2/blob/master/framework/captcha/CaptchaAction.php and customize it to always refresh. Use your own action instead of default one in your controller then.
