### ISSUE TITLE
Drop a column in mssql will cause exception

### ISSUE THREAD

**Issue by tourze** [yiisoft/yii2#17035]
### What steps will reproduce the problem?

create a new migration, 

```php
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%order_entity}}', [
            'ordersn2' => $this->tinyInteger(11)->null()->defaultValue(0),
        ]);
        $this->dropColumn('{{%order_entity}}', 'ordersn2');
    }
```

Then exception info is: 

```
*** applying m181222_073214_delete_column_ordersn2
    > drop column ordersn2 from table {{%order_entity}} ...Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]The object 'DF__ims_order__order__7D63964E' is dependent on column 'ordersn2'.
The SQL being executed was: ALTER TABLE [ims_order_entity] DROP COLUMN [ordersn2] (xxxxxxxxxxxxxxxxxxxxx/vendor/yiisoft/yii2/db/Schema.php:664)
```

### What is the expected result?

no exception

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 
| Operating system |

**Comment by GHopperMSK** [comment]
MySql fails too
```
    > create table {{%order_entity}} ... done (time: 0.024s)
    > drop column ordersn2 from table {{%order_entity}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1090 You can't delete all columns with ALTER TABLE; use DROP TABLE instead
```
If there is one more column in the table, the migration goes successfully. I don't think it is a bug.

Postres works fine in any case.

**Comment by samdark** [comment]
Right. Doesn't look like it's a bug to fail while deleting the only column.

**Comment by michalwoz** [comment]
@samdark @GHopperMSK I think that there actually might be 2 different problems.

As you both noticed it can be not an issue when you try to drop last(or the only one) column in table. But I get the same exception as author when I try to drop 1 of 10 columns.

> The object 'DF__ims_order__order__7D63964E' is dependent on column 'ordersn2'.

The object is constrain(default value?) which name is generated by MSSQL and which is automatically created by MSSQL.
So actually I'm not able to drop column in Yii2 with MSSQL?

Is there any easier solution than finding constrain name and dropping it explicitly before column drop?

https://stackoverflow.com/questions/314998/sql-server-2005-drop-column-with-constraints/1171895#1171895
