### ISSUE TITLE
Custom Validation in model with attribute label and value

### ISSUE THREAD

**Issue by nitinsonawane234** [yiisoft/yii2#17042]
```php
public function rules() {
    return [
        [['ID'], 'required'],
        [['NAME', 'AGE', 'ADDRESS'], 'required', 'message' => '{attribute} is cannot blank for'.$this->ID],
    ];
}
```
Previously this code was working fine but now $this->ID return nothing.
Or tell me any other way to achieve $this->ID in error message.

**Comment by machour** [comment]
Are you seeing this when creating a new record, or editing an existing one?

**Comment by nitinsonawane234** [comment]
> Are you seeing this when creating a new record, or editing an existing one?

For creating a new record

**Comment by machour** [comment]
If ID is your primary key, and the record is new, it's supposed to be blank prior to `save()`

**Comment by GHopperMSK** [comment]
What should happen if user didn't enter ID yet? Why don't you just show that the attribute can't be blank? 

I don't think it is any problem in current behavior due to we have both [Standalone](https://www.yiiframework.com/doc/guide/2.0/en/input-validation#standalone-validators) and [Client-Side](https://www.yiiframework.com/doc/guide/2.0/en/input-validation#client-side-validation) validators. We can use these instruments to solve almost any possible scenarios, include the described one.

**Comment by nitinsonawane234** [comment]
> Why don't you just show that the attribute can't be blank

I'm using dynamic form in which ID is automatically generated when user added new row in that form. So, ID can't be blank while submitting the form.
Now come to point, I just want error message like this, "Name cannot be blank for 1".
//1 is simply ID of row in which name is blank.

**Comment by GHopperMSK** [comment]
So, what is wrong with [Client-Side](https://www.yiiframework.com/doc/guide/2.0/en/input-validation#client-side-validation) validations? You can do whatever you want, e.g.
```
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['name'], 'required', 'message' => 'error text ',
                'whenClient' => "function (attribute, value) {
                const isError = $('#city-name').val() == '';
                if (isError) {
                    setTimeout(() => {\$('.field-city-name > p').text($('.field-city-name > p').text() + $('#city-id').val())}, 10)
                }
                return isError;
            }"],
        ];
    }
```
The example isn't perfect, but I get exactly the same result as you want - concat error message with another value that I can get on JS.

**Comment by nitinsonawane234** [comment]
I got the solution using following code.

$model_clone = Yii::$app->request->post()['User'];
foreach ($model_clone as $key => $value) {
  $model[$key]->ID = $value['ID'];
}

//put this code before loadMultiple then load model

DynamicForms::loadMultiple($model, Yii::$app->request->post());
