### ISSUE TITLE
Yii::$app->db->createCommand()->bindValues() Whether the key of the middle array must be added ':'

### ISSUE THREAD

**Issue by SayHe110** [yiisoft/yii2#17041]
### What steps will reproduce the problem?
``` php
$sql = 'select * from users where id = :id';
$users = Yii::$app->db->createdCommand($sql)
       ->bindValues([
             'id' => 1,
       ])->queryAll();
```
I want to ask，add ' : ' the difference, i don't find result in google
### What is the expected result?
So parameters will also be bound

Looking forward to your reply
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |  7.0
| Operating system | mac os

**Comment by Alex-Code** [comment]
Please use the forums for questions.
This is explained in the documentation, https://www.yiiframework.com/doc/guide/2.0/en/db-dao#binding-parameters

**Comment by lubosdz** [comment]
The double dot `:` is not required inside `bindValues`, see [here](https://stackoverflow.com/questions/26234941/how-to-use-period-dot-in-marked-parameters-for-pdo-prepared-statements).
