### ISSUE TITLE
Usage of \ReflectionMethod in yii\base\Controller::createAction()

### ISSUE THREAD

**Issue by crtlib** [yiisoft/yii2#1705]
Should we really be that concerned about case-sensitivity of action names? Could you please explain what is this additional check for? Or am I just missing something important?

**Comment by klimov-paul** [comment]
I suppose this issue is outdated.
At present state check for action method naming is reliable enough.
Replacing `method_exists()` with `try...catch` block will simply decrease readability of the code.
There is nothing to do here.
