### ISSUE TITLE
Dots in the table names

### ISSUE THREAD

**Issue by hit-shappens** [yiisoft/yii2#17057]
### What steps will reproduce the problem?

Set up an active record for a table contains dots in the name (Yes, ms sqlserver table names can has a dots like this: [SRV_NAME].[DB_NAME].[SCHEMA_NAME].[TABLE.NAME.WITH.A.LOT.OF.DOTS.]). 

### What is the expected result?

Nothing too bad.

### What do you get instead?

Database Exception.

resolveTableNames method in yii\db\mssql\Schema treats every dot like qualifier delimiter.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |2.0.15.1
| PHP version      | 7.2
| Operating system |Win srv 2012 r2

**Comment by SilverFire** [comment]
Seems to be valid, but I am not sure how to deal with it in a right way.
@hit-shappens do you have any suggestions how can we fix it?

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/pull/17408#issuecomment-507680530
