### ISSUE TITLE
[pdo_sqlsrv]  Cannot insert explicit value for identity column in table 'XXX' when IDENTITY_INSERT is set to OFF.

### ISSUE THREAD

**Issue by mmta41** [yiisoft/yii2#17051]
SQLSTATE[23000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert explicit value for identity column in table 'vendor' when IDENTITY_INSERT is set to OFF.
The SQL being executed was: INSERT INTO [vendor] ([vendor_parent_id], [vendor_name], [vendor_status], [id_vendor], [vendor_level], [created_at], [updated_at]) VALUES (NULL, 'testes', 0, NULL, 0, 1547902914, 1547902914)

### What steps will reproduce the problem?
$model = new ActiveRecordSimple();
$model->save();
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.7
| Operating system | Fedora 28
| DB | SQL Server 2017

**Comment by alexkart** [comment]
This code works correct:
```php
$b = new Broker();
$b->broker_name = 'zxc';
$b->broker_type = 3;
$b->broker_status = 3;
$b->save();
```

But if you set `id_broker` to `null` explicitly you get that error:
```php
$b = new Broker();
$b->id_broker = null;
$b->broker_name = 'zxc';
$b->broker_type = 3;
$b->broker_status = 3;
$b->save();
```

So, this means that somewhere in your code `id_broker` is assigned to `null`. What you need is instead of assigning `null` unset this property:
```php
$b = new Broker();
$b->id_broker = null;
unset($b->id_broker);
$b->broker_name = 'zxc';
$b->broker_type = 3;
$b->broker_status = 3;
$b->save();
```
