### ISSUE TITLE
yii\base\View::render() removes html element if it includes colon in attribute

### ISSUE THREAD

**Issue by richard-j-c** [yiisoft/yii2#17062]
### What steps will reproduce the problem?

```
$params['html'] = '<img src="cid:ddsdfsd">';
$output = $this->getView()->render($view, $params, $this); 
echo $output; // returns nothing
```

or

```
$params['html'] = '<img src="cid:ddsdfsd"'; // remove end '>' 
echo $output; // returns nothing
```
```
$params['html'] = 'img src="cid:ddsdfsd">'; // remove opening '<' 
echo $output; // returns as expected: img src="cid:ddsdfsd">
```

### What is the expected result?
element should not be removed

e.g.
`<img src="cid:ddsdfsd">`

### What do you get instead?
nothing

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12?
| PHP version      | 7.1.23
| Operating system |OSX 10.14.2

**Comment by rob006** [comment]
Can you create unit test for this bug or complete reproducible example?

**Comment by richard-j-c** [comment]
I am embedding an inline image for emails (I am not using `Swiftmailer`). `$params['html']` would contain the entire email content; I've just put the img element in my example for making clear. The stripping occurs in the `yii2/base/View::renderPhpFile()` - which points to it being a php issue not Yii. 

Sorry, I've circumvented the issue by not using embedded image, so won't be following up with this issue.
