### ISSUE TITLE
Respose::sendFile() does not correctly generate Content-Disposition header for UTF8 filenames with character 127

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#17070]
### What steps will reproduce the problem?
Execute `Respose::sendFile()` with a filename containing US-ASCII character with code 127 (hex 7F).

### What is the expected result?
Generated response does not contain `Content-Disposition` HTTP header with a character 127.
Successful file download (no errors).

### What do you get instead?
Generated response contains `Content-Disposition` HTTP header with a character 127. This leads to Internal Server Error 500 under Apache httpd server.

For more info see https://github.com/yiisoft/yii2/issues/10563#issuecomment-457332342.

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.3.1
| Operating system | Windows 10

**Comment by GHopperMSK** [comment]
How can I create a file which filename contains 127 symbol?
Should we process such a file or just throw an exception?

**Comment by GHopperMSK** [comment]
```
$ php -r "file_put_contents('a\x7Fc.txt', '');"
$ php -r 'file_put_contents("b\x7Fd.txt", "");'
$ ls -al | grep .txt
-rw-rw-r--  1 ghopper  ghopper       0 янв 25 17:06 a\x7Fc.txt
-rw-rw-r--  1 ghopper  ghopper       0 янв 25 17:06 bd.txt
```
Now I can do nothing with these files ) My ext4 filesystem definitely doesn't want to deal with them.

**Comment by PowerGamer1** [comment]
> Now I can do nothing with these files ) My ext4 filesystem definitely doesn't want to deal with them.

Windows and NTFS have no problems with such files. Anyway, the files themselves are no needed, Yii2 just needs to properly process a string with such filename.

**Comment by alexkart** [comment]
This character is considered as invalid by Apache, there is nothing we can do about it. 
```
AH02430: Response header 'Test2' value of '-\x7f-.txt' contains invalid characters, aborting request
```
We can only just strip that character from the filename. What do you think?

**Comment by alexkart** [comment]
The reason why apache shows 500 error is that it considers this character as invalid and it is actually correctly converted to utf-8 by the Response class but the error is caused by fallback name where this character is added as is, so we need to strip it.
Here is the current value of the Content-Disposition header
```
attachment; filename="-\x7f-.txt"; filename*=utf-8''-%7F-.txt
```

And we need to change it like this:
```
attachment; filename="-_-.txt"; filename*=utf-8''-%7F-.txt
```
Then the correct filename will be used but in the end, it will get converted by the browser (at least Chrome) to "-_-.txt" after saving in any case.
