### ISSUE TITLE
Callable in model relation via junction table stop working on 2.0.16

### ISSUE THREAD

**Issue by TomaszKane** [yiisoft/yii2#17089]
### What steps will reproduce the problem?

Define two relation in some db active record model via junction table with callable:
```php
class Foo extends Article
{
    const
        FILE_RELATION_MAIN_IMAGE = 0,
        FILE_RELATION_LOGO = 1;

    public function getMainImage()
    {
        return $this->hasOne(File::class, ['file_id' => 'file_id'])->via('articleToFiles', function (ActiveQuery $query) {
            return $query->where(['relation' => self::FILE_RELATION_MAIN_IMAGE]);
        });
    }

    public function getLogoImage()
    {
        return $this->hasOne(File::class, ['file_id' => 'file_id'])->via('articleToFiles', function (ActiveQuery $query) {
            return $query->where(['relation' => self::FILE_RELATION_LOGO]);
        });
    }
}

class Article extends ActiveRecord
{
    public function getArticleToFiles()
    {
        return $this->hasMany(ArticleToFile::class, ['article_id' => 'article_id'])->inverseOf('article');
    }
}

class ArticleToFile extends ActiveRecord {}

class File extends ActiveRecord {}
```

### What is the expected result?

Database tables has:
`article`: have article_id 1
`file`: have file_id 1 and 2
`articleToFile`: have two records:
```
article_id	file_id		relation
1		1		0
1		2		1
```
Call `$foo->mainImage->file_id` return 1
Call `$foo->logoImage->file_id` return 2

### What do you get instead?

Both (and any next file relation call) return `1` (first result).
When reverse calls (logoImage, then mainImage) got double `2`.

Works after rollback to 2.0.15.1.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.2.x
| Operating system | KDE Neon

**Comment by GHopperMSK** [comment]
https://github.com/yiisoft/yii2/blob/0602b06c8dbc292e3dc5a79c84f7d44e068d65c4/framework/db/BaseActiveRecord.php#L445-L454

The problem will go away if we will clone `$this` pointer. I.e. `$query->primaryModel = clone $this;`
Are there any flaws of the solution except `ActiveRecordTes::testInverseOf()` test failing?

**Comment by samdark** [comment]
That would be different object eating extra memory and not reacting to changes.

**Comment by loscsol** [comment]
Same problem here.

There's an error with last fix for #16552 (Commit here: https://github.com/yiisoft/yii2/commit/5ee7fabbf948f3a759f5cfd9f76c72eef17694c8)

Both relations use the same _via('articleToFiles')_ so the first call to getMainImage() will populate Foo's property articleToFiles AND add a filter with $callable; the next call to getLogoImage() will find property articleToFiles already populated (framework/db/ActiveQuery.php:182 `if ($this->primaryModel->isRelationPopulated($viaName))`) and will not reset its values appending new data from second query returning just first result because we use hasOne() (so the same record).

We can fix the code using viaTable() that isn't cached like via() relations or we need a way to avoid the isRelationPopulated() check on via() relations with $callable filter

What do you think about ?

**Comment by loscsol** [comment]
Ok I found a workaround adding `$this->primaryModel->__unset($relationName);` to reset the $relationName property if there is a $callable.

db/ActiveRelationTrait.php:105 From:
`
    public function via($relationName, callable $callable = null)
    {
        $relation = $this->primaryModel->getRelation($relationName);
        $this->via = [$relationName, $relation];
        if ($callable !== null) {
            call_user_func($callable, $relation);
        }

        return $this;
    }
`

To:

`
    public function via($relationName, callable $callable = null)
    {
        $relation = $this->primaryModel->getRelation($relationName);
        $this->via = [$relationName, $relation];
        if ($callable !== null) {
            $this->primaryModel->__unset($relationName);
            call_user_func($callable, $relation);
        }

        return $this;
    }
`

Seems to work in my test env.

**Comment by rugabarbo** [comment]
See PR #17116:
1. Added failing tests
2. Reverted commit 5ee7fab

Issue #16552 should be reopen for better implementation.

**Comment by rugabarbo** [comment]
I created another PR #17117 that fixes the problem instead of reverting commit 5ee7fab. 
This is an alternative to PR #17116.

**Comment by samdark** [comment]
@TomaszKane, @loscsol please check if your issue if fixed in master.

**Comment by TomaszKane** [comment]
@samdark it works.
