### ISSUE TITLE
[yii\validators\EmailValidator] $checkDNS does not work on alpine

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#17083]
### What steps will reproduce the problem?

Fire up Yii in php container from alpine linux
Make a `yii\validators\EmailValidator` with `$checkDNS` option being `true`
validate for example `test@dfjkdfjkdf.dk`

### What is the expected result?

this email is invalid due to host not existing

### What do you get instead?

email is perfectly valid

### Additional info
`checkdnsrr()` returns true always on alpine linux even tho `dns_get_record()` returns empty array
we could check how many dns records were returned by `dns_get_record()` if `checkdnsrr()` returns true

```
$ docker run -it php:7.1-cli-alpine
Interactive shell

php > var_dump( checkdnsrr('dfjkdfjkdf.dk.', 'A') );
bool(true)
php > var_dump( dns_get_record('dfjkdfjkdf.dk.', DNS_A) );
array(0) {
}
php > 
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.26
| Operating system | Alpine linux on docker

**Comment by MysteryDragon** [comment]
Related: https://github.com/yiisoft/yii2-docker/issues/24, https://github.com/docker-library/php/issues/442

**Comment by samdark** [comment]
Looks like we cannot fix it with Alpine from our side.

**Comment by mikk150** [comment]
@samdark but I have a fix for it and it is backwards compatible? I do not see any real reason not to support alpine for this reason?

**Comment by MysteryDragon** [comment]
Btw I pointed some issues only for help with issue verification. Personally don't have any objections about proposed fix, don't know about pitfalls.

**Comment by samdark** [comment]
@mikk150 if you're sure it works for all cases, go ahead with a pull request.

**Comment by MysteryDragon** [comment]
@samdark #17086

**Comment by samdark** [comment]
Oh. Sorry. I'm losing track of things focusing on 3.0 :)

**Comment by samdark** [comment]
@mikk150 would you please take a look at @MysteryDragon comments in a pull request? Seems there are errors to be handled better...

**Comment by mikk150** [comment]
@MysteryDragon can you please make a detailed network topology, how I could reproduce your's network(do not worry, I can do anything(Except front-end, I suck at it)) what is your docker mahine host OS, what DNS server do you use?

Yes I do agree that `dns_get_record()` can return false, because it is documented but I presumed that if `checkdnsrr()` returns true, then `dns_get_record()` cannot return false

**Comment by MysteryDragon** [comment]
@mikk150 in my point of view, we must simply operate with two different functions like there are **really** two different functions. No any **undocumented** assumptions, for your own safety. :)

And about network - sorry, but there I can't tell you that much. It's my work network, we use Cisco VPN to access to internal network of our client (relatively big company). And **in this internal network** there are some DNS, which used to gain access by internal names to some internal resources.
We are not dealing with setting with scheme up, so I have actually only this information.

**Comment by MysteryDragon** [comment]
@mikk150 oh, sorry, missed "host OS" point - it's ArchLinux. Docker 18.09.2-ce
