### ISSUE TITLE
Need to return empty body in JSON response on 204 status (no content) 

### ISSUE THREAD

**Issue by xfuturomax** [yiisoft/yii2#17094]
Now, if response format is JSON (RESTfull API) and there is no content, i.e null, yii responds string 'null', and this is not right.Some software like Postman doesn't understand this.

/yiisoft/yii2/web/JsonResponseFormatter.php:121
`elseif ($response->content === null) {
            $response->content = 'null';
        }`

**Comment by samdark** [comment]
Is that true for all request types?

**Comment by GHopperMSK** [comment]
Can we just replace 'null' string to empty one for all types? What is the reason we didn't do it at very beginning?

https://github.com/yiisoft/yii2/blob/39d3b6519cf37353cf372f8370792ed4171fc780/tests/framework/web/JsonResponseFormatterTest.php#L191-L196

**Comment by samdark** [comment]
#14759

**Comment by xfuturomax** [comment]
The 204 response must respond with an empty body, this is a priority over the json format specification.

**Comment by GHopperMSK** [comment]
Only 204 or we can extend this list?
```
    protected function formatJson($response)
    {
        if ($response->data !== null) {
            $options = $this->encodeOptions;
            if ($this->prettyPrint) {
                $options |= JSON_PRETTY_PRINT;
            }
            $response->content = Json::encode($response->data, $options);
        } elseif ($response->content === null) {
            if (in_array($response->getStatusCode(), [204])) {
                $response->content = '';
            } else {
                $response->content = 'null';
            }
        }
    }
```

**Comment by samdark** [comment]
Not sending content on 204 response doesn't depend on formatter and should be done regardless in `Response::sendContent()` like:

```php
if ($this->getStatusCode() === 204) {
    return;
}
```

**Comment by samdark** [comment]
The case should be covered with a test.

**Comment by lourdas** [comment]
The null response broke yiisoft/yii2-jui's AutoComplete object. A extra null was appended in the JSON response. Downgrading to 2.0.15.1 confirmed the issue is with 2.0.16. Will apply the patch and try again.

**Comment by GHopperMSK** [comment]
Why didn't you start new issue?

As I can understand, the problem is about response content (not about AutoComplete widget, it is important). There is "null string at the end" appears somehow. So, let us see your generating code with input params.

**Comment by lourdas** [comment]
I didn't start a new issue, because I thought it's related to this issue.
