### ISSUE TITLE
scenario is set through configuration not working

### ISSUE THREAD

**Issue by kidzen** [yiisoft/yii2#17104]
```php
// scenario is set as a property
$model = new User;
$model->scenario = 'login';
var_dump($model->scenario); // result : login

// scenario is set through configuration
$model = new User(['scenario' => 'login']);
var_dump($model->scenario); // result : default
die;
```
### Additional info

| Q                | A
| ---------------- | ---
| Bug | Yes
| Enhancement | No
| Yii version      | 2.0.14, 2.0.15
| PHP version      | 7.2.11

**Comment by rugabarbo** [comment]
@kidzen show code of your `User` class.

**Comment by blupointmedia** [comment]
@kidzen I just tested this in and it is working correctly for me. Please make sure that your User Model is extending \yii\base\Model. Please find below my version, code snippet and result snippet.

**Yii Version: 2.0.15.1**

<pre>
namespace common\models;

use yii\base\Model;
class User extends Model {}
</pre>

<pre>
namespace frontend\controllers;

use common\models\User;
use yii\base\Controller;

class UserController extends Controller
{
    public function actionIndex() {
        // First Scenario
        $user = new User();
        $user->scenario = 'test';
        var_dump($user);
        var_dump($user->scenario);

        // Second Scenario
        $user = new User(['scenario' => 'test']);
        var_dump($user);
        var_dump($user->scenario);
        exit();
    }
}
</pre>

**First Scenario**
<pre>
frontend/controllers/UserController.php:14:
object(common\models\User)[78]
  private '_errors' (yii\base\Model) => null
  private '_validators' (yii\base\Model) => null
  private '_scenario' (yii\base\Model) => string 'test' (length=4)
  private '_events' (yii\base\Component) =>
    array (size=0)
      empty
  private '_eventWildcards' (yii\base\Component) =>
    array (size=0)
      empty
  private '_behaviors' (yii\base\Component) => null

frontend/controllers/UserController.php:15:string 'test' (length=4)
</pre>

**Second Scenario**
<pre>
frontend/controllers/UserController.php:18:
object(common\models\User)[79]
  private '_errors' (yii\base\Model) => null
  private '_validators' (yii\base\Model) => null
  private '_scenario' (yii\base\Model) => string 'test' (length=4)
  private '_events' (yii\base\Component) =>
    array (size=0)
      empty
  private '_eventWildcards' (yii\base\Component) =>
    array (size=0)
      empty
  private '_behaviors' (yii\base\Component) => null

frontend/controllers/UserController.php:19:string 'test' (length=4)
</pre>

@samdark I believe this issue doesn't exist, in the version stated, and can be closed if you would like.

**Comment by samdark** [comment]
Thanks, @blupointmedia for checking it.

**Comment by kidzen** [comment]
i have recheck and compare your code with mine, it seems this issue happen only if the called class extend ActiveRecords Class

**Comment by kidzen** [comment]
User Model
```php
namespace common\models;

use \yii\db\ActiveRecord;
class User extends ActiveRecord{}
```

```php
namespace frontend\models;

use yii\base\Model;
class ContactForm extends Model {}
```
Controllers
```php
namespace frontend\controllers;

use common\models\User;
use yii\base\Controller;

class UserController extends Controller
{
    public function actionIndex() {
        // First Scenario User extend Active Records
        $user = new \common\models\User();
        $user->scenario = 'test';
        // var_dump($user);
        var_dump($user->scenario); // return test

        // Second Scenario User extend Active Records
        $user = new \common\models\User(['scenario' => 'test']);
        // var_dump($user);
        var_dump($user->scenario); // return default

        // First Scenario ContactForm extend Models
        $user = new \frontend\models\ContactForm(['scenario' => 'test']);
        // var_dump($user);
        var_dump($user->scenario); // return test

        // Second Scenario ContactForm extend Models
        $user = new \frontend\models\ContactForm();
        $user->scenario = 'test';
        // var_dump($user);
        var_dump($user->scenario); // return test
        exit();
    }
}
```

Result

```
F:\Rekamy\Laragon\www\estor\estor4\frontend\controllers\ReportController.php:62:string 'test' (length=4)
F:\Rekamy\Laragon\www\estor\estor4\frontend\controllers\ReportController.php:67:string 'default' (length=7)
F:\Rekamy\Laragon\www\estor\estor4\frontend\controllers\ReportController.php:71:string 'test' (length=4)
F:\Rekamy\Laragon\www\estor\estor4\frontend\controllers\ReportController.php:76:string 'test' (length=4)
```

**Comment by blupointmedia** [comment]
Hi @kidzen,

I just tested this again in version **2.0.15.1** and it is working with your code concept.
