### ISSUE TITLE
Cache::getOrSet docs/implementation inconsistency

### ISSUE THREAD

**Issue by yuniorsk** [yiisoft/yii2#17109]
Hi guys, in `getOrSet` cache method docblock states that 

> In case $callable returns `false`, the value will not be cached.

but it looks like it's not true, so I don't know if it's a problem with documentation or implementation.

https://github.com/yiisoft/yii2/blob/fe3ae964cdd439e7f96a99cf9d625cf7d8ca2f2c/framework/caching/Cache.php#L589-L601

**Comment by samdark** [comment]
Fixed https://github.com/yiisoft/yii2/commit/03b94989f8a6ba478fa8507e69549933420ca00b. Thanks!

**Comment by rugabarbo** [comment]
See: https://github.com/yiisoft/yii2/blob/master/docs/guide/caching-data.md#cache-apis-

> Note: Do not cache a `false` boolean value directly because the [[yii\caching\Cache::get()|get()]] method uses `false` return value to indicate the data item is not found in the cache. You may put `false` in an array and cache this array instead to avoid this problem.

@samdark so, the problem is not that we cannot cache `false`. 
We can cache it, but we can't use it... :)

**Comment by samdark** [comment]
Exactly. So original comment was misleading...

**Comment by yuniorsk** [comment]
Maybe thw problem was not with the comment but with the implementation. Cos right now there is no way to indicate that I don't want to cache data. Everything that is returned from callable is cached no matter what, but it may not be sufficient in certain situations. Of course you can use `get`/`set` methods instead, but it would be nice to have this kind of option in `getOrSet` method.
