### ISSUE TITLE
echo null рисует в браузере строку null

### ISSUE THREAD

**Issue by utmstat** [yiisoft/yii2#17121]
Это код рисует в браузере строку null
```
    public function actionWebHook($hash)
    {

        echo null;
        Yii::$app->end();

    }
```

А так все ок
```
    public function actionWebHook($hash)
    {

        echo null;
        die;

    }
```
Эта проблема воспроизводится тут \yii\web\Response::sendContent с пустым \yii\web\Response::$content

Так задумано?

This is Yii version 2.0.16

**Comment by samdark** [comment]
Дубль https://github.com/yiisoft/yii2/issues/17094
