### ISSUE TITLE
Fix gitlab mirroring for yii2

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2#17138]
It seems that the mirroring at https://gitlab.com/yiisoft/yii2 stopped working:

>  The repository failed to update 5 months ago. 
Repository mirroring has been paused due to too many failed attempts, and can be resumed by a project maintainer. 

Can someone fix that? I'm interested in dockerized tests results.

**Comment by samdark** [comment]
I've invited you to that repository. You need to do manual push once in order to unstuck it.

**Comment by machour** [comment]
Tried to force an update, but that doesn't solve it since the repo is marked as diverged, and I really don't see why (never used mirroring before).

Do you think removing & setting up the github pull again might help?
![screen shot 2019-02-17 at 3 26 54 pm](https://user-images.githubusercontent.com/304450/52914436-7b994100-32c8-11e9-8ebb-c80771b2afe3.png)

**Comment by samdark** [comment]
Manuall pushing the branch will help.

**Comment by machour** [comment]
Fixed by @schmunk42 🙏
