### ISSUE TITLE
Incorrect return value of BaseFormatConverter::convertDateIcuToPhp for russian locale

### ISSUE THREAD

**Issue by nagyt234** [yiisoft/yii2#17144]
### What steps will reproduce the problem?
Use` \yii\helpers\BaseFormatConverter::convertDateIcuToPhp('medium', 'date', 'ru')
`
### What is the expected result?
The function should return "**j M Y г.**" (г = год / y = year)

### What do you get instead?
"**j M Y \г.**" - the backslash is wrong.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.25-1+ubuntu16.04.1+deb.sury.org+1
| Operating system |Ubuntu 16.04

**Comment by rob006** [comment]
Why do you think it is wrong? `date()` should interpret it correctly - backslash is standard way of escaping letters which should be displayed as is.

**Comment by nagyt234** [comment]
> Why do you think it is wrong? `date()` should interpret it correctly - backslash is standard way of escaping letters which should be displayed as is.

@rob006 You are right. The backslash is interpreted by `date()` correctly, it is not an error but unnecessary to escape any characters which are unrecognized as format character.

So I closed this issue.
