### ISSUE TITLE
DB migration: alter table add foreign key throws syntax error with 'RESTRICT' in MSSQL

### ISSUE THREAD

**Issue by Xm4Tr1X** [yiisoft/yii2#17148]
### What steps will reproduce the problem?
1. Create table migration script
2. Alter table to add constraint. 
3. set ON DELETE  RESTRICT and ON UPDATE RESTRICT.

code : 

       $this->createTable('{{%car_color}}', [
            'colorID' => $this->primaryKey()->unsigned(),
            'colorName' => $this->string()->notNull()->defaultValue(''),
            'modelID' => $this->integer()->unsigned()->notNull()->defaultValue('0'),
            'image' => $this->string()->notNull()->defaultValue(''),
            'fileSize' => $this->bigInteger()->notNull()->defaultValue('0'),
        ]);

       $this->addForeignKey('FK_car_color_1', '{{%car_color}}', 'modelID', '{{%car_model}}', 'modelID', 
       'RESTRICT', 'RESTRICT');

### What is the expected result?
Expected: successfully created constraint.
### What do you get instead?
Syntax error near 'RESTRICT'
![untitled](https://user-images.githubusercontent.com/19608968/53081606-328ff980-3521-11e9-9584-ea5c6bff3f5c.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | Win 10

**Comment by sdlins** [comment]
I could not find any option `STRICT` for `ON UPDATE` or `ON DELETE` in MsSQL documentation:

```sql
FOREIGN KEY   
        ( column [ ,...n ] )  
        REFERENCES referenced_table_name [ ( ref_column [ ,...n ] ) ]   
        [ ON DELETE { NO ACTION | CASCADE | SET NULL | SET DEFAULT } ]   
        [ ON UPDATE { NO ACTION | CASCADE | SET NULL | SET DEFAULT } ]   
```

https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-table-constraint-transact-sql?view=sql-server-2017#syntax

**Comment by samdark** [comment]
Indeed. It seems not to be supported.
