### ISSUE TITLE
Changes on NumberValidation broken Application!

### ISSUE THREAD

**Issue by chrisschd** [yiisoft/yii2#17159]
### What steps will reproduce the problem?
Method in Module:
```
  public function rules()
    {
        return [
            [[ 'finished', 'state'], 'integer'],
        		[['comment'], 'string', 'max' => 255]
        ];
    }
```

Controller Action:

```
$model->finished = true;
$model->save(); // failes!
```

### What is the expected result?
```
$model->finished = true;
$model->save(); // ok - no error!
```

### What do you get instead?

A NumberValidator error (must be integer) 

### Additional info
Change NumberValidatior method and disabled is_bool fixed the problem:
 private function isNotNumber($value)
    {
        return is_array($value)
       //     || is_bool($value)
            || (is_object($value) && !method_exists($value, '__toString'))
            || (!is_object($value) && !is_scalar($value) && $value !== null);
    }

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.2.15
| Operating system |Ubuntu

**Comment by rob006** [comment]
PR with this change: https://github.com/yiisoft/yii2/pull/16903

**Comment by samdark** [comment]
Thanks for reporting but why is it expected? It was incorrect behavior that was fixed.

**Comment by SDKiller** [comment]
I agree with @samdark 

There is a boolean validator, @chrisschd you should use it if you expect boolean value.
It can also fallback to 0/1 depending on how you configure it.

**Comment by SDKiller** [comment]
BTW, while php built-in `is_numeric()` does not always provide reliable results, it also does not consider boolean values as numbers.

So #16903 just made NumberValidator more consistent and should not be reverted, IMO.

**Comment by chrisschd** [comment]
Thanks for your answers!

I can only speak for our application, these changes broken our complete Application. We used, “tinyint” for Boolean in the database since we worked with yii/yii2. This little change bring us in troubles we have to rework a huge amount of models to bring up our application in a working state. 

I think we are not the only one which will have these problems, but this was more a feature request as a bug report. Maybe it is possible to setup the Validator to support also Boolean types?  For example:

```
class NumberValidator extends Validator
{
    /**
     * @var bool whether the attribute value can only be an integer. Defaults to false.
     */
    public $integerOnly = false;
    
    public $allowBoolean = true; //NEW 
….
/*
     * @param mixed $value the data value to be checked.
     */
    private function isNotNumber($value)
    {
        return is_array($value)
            || (!$allowBoolean  && is_bool($value)) //NEW: !$allowBoolean&
            || (is_object($value) && !method_exists($value, '__toString'))
            || (!is_object($value) && !is_scalar($value) && $value !== null);
    }
…
}

```

**Comment by SDKiller** [comment]
> I think we are not the only one which will have these problems...

I suppose you are, since you have used undocumented bug of validator as a feature :)

**Comment by rob006** [comment]
@chrisschd Using `integer` validator for boolean fields is incorrect - `integer` validator will allow saving values like `123` which may cause unexpected results.

**Comment by samdark** [comment]
The decision is to keep current behavior. Thanks for reporting anyway, @chrisschd.
