### ISSUE TITLE
prepareAllowedHeaders in Cors filter argument type wrong

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#17167]
My intellisense gave me this error:

> Expected type 'array|null'. Found 'string'.

For this line: https://github.com/yiisoft/yii2/blob/77d7a5046ef44ca9143c0633ad260b8c113b3f75/framework/filters/Cors.php#L221

` $acceptedData = array_uintersect($requestedData, $this->cors[$requestHeaderField], 'strcasecmp');`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 
| Operating system |

**Comment by GHopperMSK** [comment]
I think here is nothing wrong with Yii2 itself. The function calling `array_uintersect($requestedData, $this->cors[$requestHeaderField], 'strcasecmp');` corresponds official [documentation](http://php.net/manual/en/function.array-uintersect.php).

The problem located inside IDE. For example, in phpStorm:
```

/**
 * Computes the intersection of arrays, compares data by a callback function
 * @link http://php.net/manual/en/function.array-uintersect.php
 * @param array $array1 <p>
 * The first array.
 * </p>
 * @param array $array2 <p>
 * The second array.
 * </p>
 * @param array $_ [optional]
 * @param callback $data_compare_func <p>
 * The callback comparison function.
 * </p>
 * <p>
 * The user supplied callback function is used for comparison.
 * It must return an integer less than, equal to, or greater than zero if
 * the first argument is considered to be respectively less than, equal
 * to, or greater than the second.
 * </p>
 * @return array an array containing all the values of array1
 * that are present in all the arguments.
 * @since 5.0
 */
function array_uintersect(array $array1, array $array2, array $_ = null, $data_compare_func) { }
```

There isn't way to fix this error except the intellisense fixing.
