### ISSUE TITLE
Reset Password Breaks with $%

### ISSUE THREAD

**Issue by sharkbit** [yiisoft/yii2#17169]
A user is trying to change his password and it Includes $%,  after the % percent sigh the Form stops working.

### What steps will reproduce the problem?
Reset any users password,  enter %, Form Stops responding.

### What is the expected result?
to use % in a password

### What do you get instead?
AFU... and dead.  Reload page to try again...

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      |  7.2.15
| Operating system |  Ubuntu 18.04.1

**Comment by samdark** [comment]
Which password reset form do you mean?

**Comment by sharkbit** [comment]
we are using a pretty simple form that resets users passwords, It calls the standard models\ResetPasswordForm.  

- Issue occurs as soon as a '%' sign is entered in the password field. Once % percent is pressed the form stops working.  needin a reload to try again.

`
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = "Reset password";
$this->params["breadcrumbs"][] = ["label" => "Admin Function", "url" => ["/badge/admin-function"]];
$this->params["breadcrumbs"][] = ["label" => "User", "url" => ["index"]];
$this->params["breadcrumbs"][] = $this->title;
?>
<div class="site-reset-password">
    <div class="row">
        <div class="col-xs-12" style="padding: 10px 350px">
            <?php $form = ActiveForm::begin(["id" => "reset-password-form"]); ?>

                <?= $form->field($model, "password")->passwordInput(["autofocus" => true]) ?>
                 <?= $form->field($model, "confirm_password")->passwordInput(["autofocus" => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton("Save", ["class" => "btn btn-primary"]) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
    
</div>`

## ResetPasswordForm ##############
`use yii\base\Model;
use yii\base\InvalidParamException;
use common\models\User;

/**
 * Password reset form
 */
class ResetPasswordForm extends Model {
    public $password;

    /**
     * @var \common\models\User
     */
    private $_user;


    /**
     * Creates a form model given a token.
     *
     * @param string $token
     * @param array $config name-value pairs that will be used to initialize the object properties
     * @throws \yii\base\InvalidParamException if token is empty or not valid
     */
    public function __construct($token, $config = []) {
        if (empty($token) || !is_string($token)) {
            throw new InvalidParamException("Password reset token cannot be blank.");
        }
        $this->_user = User::findByPasswordResetToken($token);
        if (!$this->_user) {
            throw new InvalidParamException("Wrong password reset token.");
        }
        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            ["password", "required"],
            ["password", "string", "min" => 6],
        ];
    }

    /**
     * Resets password.
     *
     * @return bool if password was reset.
     */
    public function resetPassword() {
        $user = $this->_user;
        $user->setPassword($this->password);
        $user->removePasswordResetToken();

        return $user->save(false);
    }
}
`

**Comment by samdark** [comment]
I'm unable to reproduce it. Please provide a reduced test case else we cannot fix it.
