### ISSUE TITLE
Memory problems with elasticsearch after 2.0.16 update

### ISSUE THREAD

**Issue by ronskyi** [yiisoft/yii2#17172]
I'm using yiisoft/yii2-elasticsearch 2.1 branch with elasticsearch 6.3
After updating from 2.0.15.1 to 2.0.16 I've got
Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)
With 2.0.15.1 same page requires 4.8 - 5.2 MB (debug, dev)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.2
| Operating system | Windows 10 Pro (Docker: php:7.2-fpm)

**Comment by samdark** [comment]
Already fixed in master.
