### ISSUE TITLE
Yii2 Migration Transaction Error

### ISSUE THREAD

**Issue by blupointmedia** [yiisoft/yii2#17173]
### What steps will reproduce the problem?
./yii migrate

### What is the expected result?
In safeUp, if it fails it should suppress the error and rollback in safeDown.

### What do you get instead?
When adding a foreign key on column that doesn't exist, it throws and error and never rolls back. The new columns stayed in my database.

### Additional info
```use yii\db\Migration;
class m190227_152159_add_bundle_bill_structure extends Migration {
    public function safeUp() {
        $this->addColumn('bill','isBundle', 'boolean default 0 after isInstallment');
        $this->addColumn('bill','bundledBillId', 'int(11) after isBundle');
        $this->addForeignKey('bill_bill_bundleBillId', 'bill', 'bundleBillId', 'bill', 'id', 'CASCADE', 'CASCADE');
    }
    public function safeDown() {
        $this->dropForeignKey('bill_bill_bundledBillId', 'bill');
        $this->dropColumn('bill', 'bundleBillId');
        $this->dropColumn('bill', 'isBundle');
    }
}
```

Notice the misspelling of the column name, **bundledBillId.** It couldn't create the FK and therefore I would expect it to rollback, but instead it threw a SQL error and never hit my safeDown method. The columns were never dropped from my database table.

```./yii migrate
Yii Migration Tool (based on Yii v2.0.15.1)

Total 1 new migration to be applied:
m190227_152159_add_bundle_bill_structure

Apply the above migration? (yes|no) [no]:yes
*** applying m190227_152159_add_bundle_bill_structure
- add column isBundle boolean default 0 after isInstallment to table bill ... done (time: 0.109s)
- add column bundledBillId int(11) after isBundle to table bill ... done (time: 0.084s)
- add foreign key bill_bill_bundleBillId: bill (bundleBillId) references bill (id) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'bundleBillId' doesn't exist in table
The SQL being executed was: ALTER TABLE bill ADD CONSTRAINT bill_bill_bundleBillId FOREIGN KEY (bundleBillId) REFERENCES bill (id) ON DELETE CASCADE ON UPDATE CASCADE (.../vendor/yiisoft/yii2/db/Schema.php:664)
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version   | 7.2.15
|MySQL | 15.1 Distrib 10.0.38-MariaDB
| Operating system | Centos 7

**Comment by bizley** [comment]
[MariaDB](https://mariadb.com/kb/en/library/sql-statements-that-cause-an-implicit-commit/) and [MySQL](https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html) `ALTER TABLE` statement causes implicit commit so it can not be rolled back in transaction.

**Comment by blupointmedia** [comment]
Thanks for the speedy reply, @bizley. I learned something new.
