### ISSUE TITLE
Cannot use 'css' or 'js' =>['url' => ['option1'=> 'value1', ...]] format in 'components' => ['assetManager' => ['bundles' => [

### ISSUE THREAD

**Issue by auratravel** [yiisoft/yii2#17186]
### What steps will reproduce the problem?
'components' => [
        'assetManager' => [
            'bundles' => [
                'kartik\icons\FontAwesomeAsset' => [
                      'css' => ['//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.2/css/all.min.css' => ['integrity' => 'sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=', 'crossorigin' => 'anonymous']]
]

documentation suggests this format of url+options should work...

### What is the expected result?
rendering in "head"
link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.2/css/all.min.css" rel="stylesheet" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous"

### What do you get instead?
rendering in "head"
link href="/sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" rel="stylesheet" crossorigin="anonymous"

### Additional info
This seems to be the case for setting both 'css' and 'js' with the url+options format, both in $config and in AssetBundle inherited class public $js = [].

Additionally, in $config, setting 'js' or 'css' to NULL or FALSE breaks the yii code, to unset AssetBundle settings, one must assign empty array - '[]'.  It may be a good idea for the AssetBundle code to take NULL or FALSE instead...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.2.14
| Operating system | wamp64 on win10

**Comment by rob006** [comment]
> 'components' => [
> 'assetManager' => [
> 'bundles' => [
> 'kartik\icons\FontAwesomeAsset' => [
> 'css' => ['//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.2/css/all.min.css' => ['integrity' => 'sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=', 'crossorigin' => 'anonymous']]
> ]

Where did you get this syntax? According to docs it should be:

```php
'css' = =>  [
    ['//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.2/css/all.min.css', 'integrity' => 'sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=', 'crossorigin' => 'anonymous'],
];
```
