### ISSUE TITLE
Unexpect difference between the count query and the actual query for gridview

### ISSUE THREAD

**Issue by dgtal24** [yiisoft/yii2#17184]
I generated the model and crud code with gii, then i just added an andWhere inside the all function and the row count is wrong.
### What steps will reproduce the problem?
Adding an "andWhere" function to an activequery 
```
class ProfileQuery extends \yii\db\ActiveQuery
{

/**
     * {@inheritdoc}
     * @return Profile[]|array
     */
    public function all($db = null)
    {
        $this->andWhere(['type'=>'f']);
        return parent::all($db);
    }
```
### What is the expected result?
I expect the same query to be executed for the total count of the rows and the actual results.
### What do you get instead?
_Showing 1-17 of 25 elements_
If i check the queries in the debugger, the row count query is missing the type = "f" part.
While the actual query is ok.

### Additional info
I'm using gii generated code

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      |  7.3
| Operating system | windows/linux

**Comment by codespede** [comment]
If you want the condition to be present in all the queries executed, you can do like below(not tested) where it'll append the condition in all the queries executed from `ProfileQuery` including `all()` and `count()`:
```
class ProfileQuery extends \yii\db\ActiveQuery
{
    public function init(){
        $this->andWhere(['type'=>'f']);
        parent::init();
    }
}
```

**Comment by dgtal24** [comment]
Unfortunately i can't. The condition must not be included when i search just one model.
Is count another function? I could add the condition to a function and call it from both functions (all() and count().
Still, i'd expect the gridview not to show the total count. I need to hide some records for some user roles, and they must not know the total number or records.

**Comment by codespede** [comment]
Yes `count()` is another function in the `ActiveQuery` class which will be used to find the total count to be shown in the GridView by the DataProvider.

When rendering a GridView, two queries will be executed: one for the total count and one for the data items in the current page.

You can also set your own total count to be shown in the GridView summary by setting 'totalCount' to the DataProvider like this `$dataProvider->totalCount = x;` and setting this DataProvider to the GridView.

Additionally, you can customize what to be shown on the GridView's summary by setting the 'summary' property when rendering the GridView: https://www.yiiframework.com/doc/api/2.0/yii-widgets-baselistview#$summary-detail
