### ISSUE TITLE
[Regression][yii\web\Response::prepare()] populates $response parameter on 204 No Content response

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#17180]
### What steps will reproduce the problem?

On REST API send DELETE object request

If you test that in Codeception, it tells that it did not get any response even tho response was prepared

### What is the expected result?

should not get any response,
formatters are not executed
codeception is happy

### What do you get instead?

do not get any response,
formatters are executed
codeception is unhappy about response not recieved but was prepared

### Additional info

https://github.com/Codeception/Codeception/issues/5418

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      | 5.6
| Operating system | Ubuntu

**Comment by machour** [comment]
@GHopperMSK can you have a look at this one please ? It seems to be related to #17094

**Comment by GHopperMSK** [comment]
it works. I like the idea to shift content assigning into `prepare()` method.
