### ISSUE TITLE
User::identityClass must be set why

### ISSUE THREAD

**Issue by crazePhper** [yiisoft/yii2#17187]
//        'user' => [
//            'identityClass' => 'common\models\User',
//            'enableAutoLogin' => false,
//            'enableSession' => false,
//            'identityCookie' => ['name' => 'easydo_identity', 'httpOnly' => true],
//        ],

in config file ,i don't want to set user components.then it will throw InvalidConfigException, the user components is unuseful for my site.i don't need.how to config this.

**Comment by rob006** [comment]
This exception will be thrown only if `Yii::$app->user` will be used somewhere. So this component does not look unuseful in your case, since it is used somewhere.

**Comment by crazePhper** [comment]
> This exception will be thrown only if `Yii::$app->user` will be used somewhere. So this component does not look unuseful in your case, since it is used somewhere.

yes,you are right.thanks.

**Comment by 953131014** [comment]
> This exception will be thrown only if `Yii::$app->user` will be used somewhere. So this component does not look unuseful in your case, since it is used somewhere.

正解，good
