### ISSUE TITLE
AttributeTypecastBehavior causes unnecessary  update on database

### ISSUE THREAD

**Issue by itsmh** [yiisoft/yii2#17194]
### What steps will reproduce the problem?
Assume this table exists 
```sql
CREATE TABLE `activation` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `title` varchar(255) DEFAULT NULL,
 `identity_code` int(11) DEFAULT NULL,
 `is_active` tinyint(1) NOT NULL DEFAULT 0,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
```
A model with typecast behavior call it `Activation`
```php
    public function behaviors()
    {
        return [
            'typecast' => [
                'class' => AttributeTypecastBehavior::className(),
                'typecastAfterValidate' => true,
                'typecastBeforeSave' => true,
                'typecastAfterFind' => true,
            ],
        ];
    }
```

```php
    public function rules()
    {
        return [
            [['identity_code'], 'integer'],
            [['is_active'], 'boolean'],
            [['title'], 'string', 'max' => 255],
        ];
    }
```

if we try to update an existing record with the exact same values on db it causes an unnecessary update command on database
```php
//First we're gonna save a record with this data
$activation = new Activation();
$data['is_active'] = 1;
$data['identity_code']  = 1234;
$data['title']  = "some title";
$activation->load($data, '');
$activation->save();
//works fine and we assume the id is 1 which is and we try to update it later with the same data

$data['is_active'] = 1;
$data['identity_code']  = 1234;
$data['title']  = "some title";
$activation = Activation::findOne(['id' => 1]);
$activation->load($data, '');
$activation->save();
```
### What is the expected result?
`attributes` should be same as `_oldAttributes` to handle strict comparision in `getDirtyAttributes` https://github.com/yiisoft/yii2/blob/e6513a2c9ef948b99f325d751a4f2ee6627f3eae/framework/db/BaseActiveRecord.php#L629
so both `attributes` and `_oldAttributes` must be set to
```php
array (size=4)
  'id' => int 1
  'title' => string 'some title' (length=10)
  'identity_code' => int 1234
  'is_active' => boolean true
```

### What do you get instead?
`attributes` is as expected
```php
array (size=4)
  'id' => int 1
  'title' => string 'some title' (length=10)
  'identity_code' => int 1234
  'is_active' => boolean true
```
but `_oldAttributes` is not
```php
array (size=4)
  'id' => int 1
  'title' => string 'some title' (length=10)
  'identity_code' => int 1234
  'is_active' => int 1
```
and the `save` call will result in an unnesessary update call
The workaround about updating `_oldAttributes` may work by adding 
```php
if(!$this->owner->isNewRecord)
    $this->owner->setOldAttribute($attribute, $this->owner->{$attribute});
```
at the end of ```typecastAttributes``` function
https://github.com/yiisoft/yii2/blob/e6513a2c9ef948b99f325d751a4f2ee6627f3eae/framework/behaviors/AttributeTypecastBehavior.php#L241
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.15
| Operating system | Ubuntu 18.04.1 LTS 
| Database     | 10.3.10-MariaDB

**Comment by GHopperMSK** [comment]
Did you try replace `tinyint` by `boolean` in table schema?

**Comment by itsmh** [comment]
Actually it is created by the `Migration.
Here's the code 
```php
    public function safeUp()
    {
        $this->createTable('activation', [
            'id' => $this->primaryKey(),
            'title' => $this->string()->null(),
            'identity_code' => $this->integer()->null(),
            'is_active' => $this->boolean()->notNull()->defaultValue(0),
        ]);
    }
```
and trying to change the datatype using `alter` will result in the same result since mysql treats `boolean` as `tinyint` itself

**Comment by rfontanella** [comment]
I'm having the same problem... Without using AttributeTypecastBehavior but using FilterValidator instead.
You can get the same error using the provided configuration but removing behaviors and adding the following validation rule 

[['is_active'], 'filter', 'filter' => 'boolval'],
