### ISSUE TITLE
Model::validateMultiple changes empty attributes to zeros

### ISSUE THREAD

**Issue by lowap** [yiisoft/yii2#17195]
### What steps will reproduce the problem?
The use of Model::validateMultiple

### What is the expected result?
That after unsuccessful validation empty attributes remain empty.

### What do you get instead?
Instead of empty attributes I'm getting zeros back on the form after unsuccessful validation.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 5.6.25
| Operating system | Windows Server 2012 R2 Standard Edition

**Comment by GHopperMSK** [comment]
Newly installed Yii2. 

Add a member to LoginForm class:
```
public $test;
```
Add rule:
```
[['username', 'password', 'test'], 'required'],
```

Modify SiteController::actionLogin() method:
```
...
        $model = new LoginForm();

//        $model->test = 'a';
        $validationResult = Model::validateMultiple([$model], ['test']);
...
```

In this configuration `validateMultiple` works perfect - depending to the row above is commented or not,  it returns false or true. In both cases the member itself doesn't change.

How can I reproduce specifically your case?

**Comment by lowap** [comment]
Here is my Controller:

	public function actionCreate($zg_id) {
		$zgmws = [new Zgmw()];
		for ($i = 1; $i <= 10; $i++) {
			$zgmws[] = new Zgmw();
		}

		try {
			if (Model::loadMultiple($zgmws, Yii::$app->request->post()) && Model::validateMultiple($zgmws)) {
				foreach ($zgmws as $zgmw) {
					if ($zgmw->value) {
						$zgmw->save(false);
					}
				}
				return $this->redirect(Url::previous());
			}
		} catch (\Exception $e) {
			...
		}
		return $this->render('create', [
			'zgmws' => $zgmws
		]);

Form:

	foreach ($zgmws as $index => $zgmw) {
		echo $form->field($zgmw, "[$index]value")->textInput([]);
	}

Rules:

	public function rules() {
		return [
			[['value'], 'number', 'enableClientValidation' => false],
		];
	}
