### ISSUE TITLE
DB sessions not being expired

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2#17209]
### What steps will reproduce the problem?

configuration:

```
        'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'PHPSESSID',
            'class' => \yii\web\DbSession::class,
            'sessionTable' => 'session_frontend',
        ],
```

### What is the expected result?

For sessions to be cleared after 1440 seconds

### What do you get instead?

1849093 sessions that shouldn't be there, no sessions were garbage collected since project launch (3 march).

### Additional info

```
session.gc_maxlifetime => 1440 => 1440
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      | 5.6
| Operating system | Debian

**Comment by bizley** [comment]
Every `expire` column is in the past?

**Comment by machour** [comment]
yes

**Comment by rob006** [comment]
What is your `session.gc_probability` and `session.gc_divisor` ini settings.

**Comment by machour** [comment]
session.gc_probability was 0, thank you @rob006 
🤡
