### ISSUE TITLE
append rule from behavior has no effect

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#17205]
### What steps will reproduce the problem?
add rules from behavior has no effect
```php
    public function attach($owner)
    {
        parent::attach($owner);
        $validator = Validator::createValidator('safe', $owner, (array) $this->attribute); // MUST add to safeAttributes.

        $owner->validators->append($validator);
    }
```
... 
```php
        $formModel = Yii::createObject(TagForm::class, [['model' => $model]]);
        $formModel->ensureBehaviors();
        $scenarios = $formModel->scenarios();
        $safeAttributes = $formModel->safeAttributes();

```
### What is the expected result?
rules will be expand
safeAttributes will be expand

### What do you get instead?
rule adding in attach

but each next calling getValidators()
return rules from model only  

p.s.
    /**
     * @var ArrayObject list of validators
     */
    private $_validators;

separate storage from children. I try attach behavior to parent model and to child. Same result.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | 7.3.3
| Operating system |

**Comment by mgrechanik** [comment]
You do not have scenarios() in your model, do you?

**Comment by bscheshirwork** [comment]
`scenarios` is `default` 
I can't have additional scenarios
