### ISSUE TITLE
function home

### ISSUE THREAD

**Issue by ptcrank** [yiisoft/yii2#17201]
In the home method there is a mistake. [BaseUrl.php](https://github.com/yiisoft/yii2/blob/2.0.16.1/framework/helpers/BaseUrl.php)
The following should be outside of condition: Line [367](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseUrl.php#L367)
`$ url = static :: ensureScheme ($ url, $ scheme);`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16 _Latest release_
| Operating system |

**Comment by rob006** [comment]
Why? `ensureScheme()` does not support `false` as `$scheme`?
