### ISSUE TITLE
db->close() drops any custom configuration of Query Builder

### ISSUE THREAD

**Issue by garthpmurray** [yiisoft/yii2#17203]
### What steps will reproduce the problem?

Setup additional expressionBuilders/conditionClasses within the db configuration.
execute `Yii::$app->db->close()` and `Yii::$app->db->open()` within the course of the app

### What is the expected result?

Configurations designated in the config will be reinstantiated in the newly open db.

### What do you get instead?

new instance of `Yii::$app->db->queryBuilder` will have lost custom configurations and contain only default.

### Additional info

In the course of initial configuration of the db, `\yii\db\Connection::setQueryBuilder` is called which pulls a new schema and then loads it with any necessary queryBuilder configurations. Close then sets that schema to null, which when reopened and asked for again, creates a new schema which then creates a new queryBuilder instance with only default configuration.

\yii\db\Connection::close
```php
    /**
     * Closes the currently active DB connection.
     * It does nothing if the connection is already closed.
     */
    public function close()
    {
       ....
            $this->_schema = null;
       ....
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      | 7.1.26
| Operating system | Alpine 3.8

**Comment by samdark** [comment]
How would you solve it?

**Comment by SilverFire** [comment]
@garthpmurray thanks for the report, fixed
