### ISSUE TITLE
Not very clear on how to filter query via dataFilter prop in IndexAction

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#17217]
### What steps will reproduce the problem?
I have the following scenario: 
- I am using REST API by `Bearer` type of token. User is logged in, all ok. 
- Then I am trying to query certain data from db and would like to modify query to have current identitie's ID in it, so we can see only his own items

I tried to use `dataFilter` but no result, by the debugger I can see it is now passing validations phase. 

### What is the expected result?

Understand on how to filter query by `dataFilter` property in `IndexAction`. 

[This](https://github.com/yiisoft/yii2/blob/master/framework/rest/IndexAction.php#L53-L64) example is not very clear. 

### What do you get instead?
Not filtered response. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.2.x
| Operating system | Ubuntu

Could you give example and possibly add it to the [here](https://github.com/yiisoft/yii2/blob/master/framework/rest/IndexAction.php#L53-L64) and official docs if possilble. 

Thank you.

**Comment by tom-schumann** [comment]
Your controller actions method needs to look something like this:
```
	public function actions() {
		$actions = parent::actions();

		$actions['index']['dataFilter'] = [
			'class' => ActiveDataFilter::class,
			// these seem to get put into attributes of the above specified class
			'queryOperatorMap' => ['LIKE' => 'ILIKE'],
			'searchModel' => function () {
				return (new DynamicModel(['name' => null, 'description' => null]))
					->addRule(['name', 'description'], 'trim')
					->addRule(['name', 'description'], 'string');
			}
		];

		return $actions;
	}
```

But that's not enough. You also need to override prepareDataProvider:
```
	protected function prepareDataProvider() {
		$request_params = Yii::$app->getRequest()->getQueryParams();

		/**
		 * shouldn't need to do this (might be fixed in newer versions of Yii2?) but the filter argument doesn't
		 * seem to get properly converted before being passed to vendor/yiisoft/yii2/data/DataFilter.php
		 */
		if (array_key_exists('filter', $request_params)) {
			$request_params['filter'] = json_decode(stripcslashes($request_params['filter']), true);
			// put the fixed filter query parameter back into Yii2's query parameter store
			Yii::$app->getRequest()->setQueryParams($request_params);
		}

		$data_provider = parent::prepareDataProvider();
		// when $data_provider is filtering, it becomes a DataFilter for some reason
		if ($data_provider->hasProperty('sort')) {
			$data_provider->sort->enableMultiSort = true;
		}

		return $data_provider;
	}
```
This is using Yii 2.0.13.3 so maybe the last bit is no longer necessary.

**Comment by acorncom** [comment]
Filtering info got updated in https://github.com/yiisoft/yii2/pull/19357 does that address this issue?

**Comment by bizley** [comment]
It should. Thanks for the info!
