### ISSUE TITLE
yii\grid\CheckboxColumn doesn't select all if loaded via ajax request

### ISSUE THREAD

**Issue by dgtal24** [yiisoft/yii2#17213]
### What steps will reproduce the problem?
Using yii\grid\CheckboxColumn inside a GridView loaded via ajax request

### What is the expected result?
The check all checkbox should check all the checkboxes in the GridView.
### What do you get instead?
Nothing happens. Works if the gridview is loaded without ajax.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      |  7.3
| Operating system | Win 10

**Comment by alex-code** [comment]
Which `render` method are you using in your action?

**Comment by dgtal24** [comment]
> 
> 
> Which `render` method are you using in your action?

renderAjax

**Comment by alex-code** [comment]
How are you handling the ajax response? i.e. adding the content to the page.

**Comment by dgtal24** [comment]
> 
> 
> How are you handling the ajax response? i.e. adding the content to the page.
I use jquery ajax load
```
    $(this).load("{$ajaxUrl}", function() {
        $(this).removeClass("loading-animation-ring");
    });
```
It loads the content from an url into a container.

This is the code from the action
        $account = $this->findModel($id);
        
        $searchModel = new ClosedOperationSearch();
        $searchModel->not_included_extra = TRUE;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->setPagination(['pageSize'=>50]);
        $dataProvider->setSort(['defaultOrder' => ['opened_at' => SORT_ASC]]);
        
        $viewVariables = [
            'account' => $account,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ];
        
        if (Yii::$app->request->isAjax){
            return $this->renderAjax('closed_operations_selection', $viewVariables);
        } else {
            return $this->render('closed_operations_selection', $viewVariables);
        }

**Comment by dgtal24** [comment]
Sorry, that wasn't a bug. Or at least there's a way to solve it.
Assigning an id to the GridView i got it to work.
