### ISSUE TITLE
Incorrect table name(extra square brackets injected) when using SQL server table with two nonconsecutive spaces after overriding the tablename function

### ISSUE THREAD

**Issue by raymond1** [yiisoft/yii2#17219]
### What steps will reproduce the problem?
1)Create a table in sql server named [PPPPPPPP$Internet Customer Cart] with an id column.
2)Create a table in SQL server named [PPPPPPPP$Order] with an id column
3)Create a join table in SQL server named [PPPPPPPP$AtoB] with columns
cartId
orderId
4)Create a model named CartItem
5)Create a model named Order

6)Override the CartItem tablename function like so:
    public static function tableName()
    {
		return '[PARTWERX$Internet Customer Cart]'; 
    }

7)Try to create a getItems function in the Order table so that you can write
$order->items. It is impossible because of the bug. You will see something like:

SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'IN'.
The SQL being executed was: SELECT * FROM [PPPPPPP$Internet Customer [Cart]] WHERE [id] IN ('....', '...')

Notice the extra square brackets around the Cart. There should only be one square bracket around the entire table name.
### What is the expected result?

I expect that no extra square brackets appear.

### What do you get instead?
Extra square brackets appear.

### Additional info
Tested in latest version 2.0.16
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by alexkart** [comment]
Trying to investigate this issue.
@samdark could you please help me to understand what this regex is doing? https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L1334
This part `(?i:` seems incorrect to me

![34523543445](https://user-images.githubusercontent.com/8249105/61448983-a4e3f900-a95c-11e9-80b8-f1dc891641bd.PNG)

**Comment by mikehaertl** [comment]
@alexkart Not sure if you're asking about the `(?i:...)` syntax. It's explained here: https://www.php.net/manual/en/regexp.reference.subpatterns.php

**Comment by alexkart** [comment]
@mikehaertl thanks
