### ISSUE TITLE
ActiveRecord orderBy params(array)  is invalid

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#17212]
### What steps will reproduce the problem?
![image](https://user-images.githubusercontent.com/1888094/54577338-536f4000-4a36-11e9-94b6-8e4a937ddfc0.png)
![image](https://user-images.githubusercontent.com/1888094/54577344-58cc8a80-4a36-11e9-9d52-10e308caf3d6.png)

![image](https://user-images.githubusercontent.com/1888094/54577408-ae089c00-4a36-11e9-8b44-9ca0bb4b11d8.png)
![image](https://user-images.githubusercontent.com/1888094/54577413-b82a9a80-4a36-11e9-940f-8fd5c5b5476b.png)

ActiveRecord -> orderBy(['created'=>'desc'])  is   invalid
ActiveRecord -> orderBy('created desc')  is   valid

### What is the expected result?
 i hope ActiveRecord -> orderBy(['created'=>'desc'])    will valid

![image](https://user-images.githubusercontent.com/1888094/54577413-b82a9a80-4a36-11e9-940f-8fd5c5b5476b.png)

### What do you get instead?
![image](https://user-images.githubusercontent.com/1888094/54577338-536f4000-4a36-11e9-94b6-8e4a937ddfc0.png)
![image](https://user-images.githubusercontent.com/1888094/54577344-58cc8a80-4a36-11e9-9d52-10e308caf3d6.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      |  7.3.3
| Operating system | win10 64

**Comment by bizley** [comment]
While it's stated in [Guide](https://www.yiiframework.com/doc/guide/2.0/en/db-query-builder#order-by) that for array parameter `SORT_DESC` and `SORT_ASC` should be used it does not state that it's only valid option. Maybe we should mention that or allow "desc" and "asc" strings for array.

**Comment by huaiguoguo** [comment]
> While it's stated in [Guide](https://www.yiiframework.com/doc/guide/2.0/en/db-query-builder#order-by) that for array parameter `SORT_DESC` and `SORT_ASC` should be used it does not state that it's only valid option. Maybe we should mention that or allow "desc" and "asc" strings for array.

i am try this ,  but is invalid too!

**Comment by huaiguoguo** [comment]
> While it's stated in [Guide](https://www.yiiframework.com/doc/guide/2.0/en/db-query-builder#order-by) that for array parameter `SORT_DESC` and `SORT_ASC` should be used it does not state that it's only valid option. Maybe we should mention that or allow "desc" and "asc" strings for array.

i tried it, but it still invalid!

**Comment by bizley** [comment]
Are you saying that `->orderBy(['created_at' => SORT_DESC])` doesn't work?

**Comment by omentes** [comment]
I think this is a good idea. I will fix it.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/pull/17216
