### ISSUE TITLE
getOrSet in yii\di\Container

### ISSUE THREAD

**Issue by Raven0us** [yiisoft/yii2#17227]
Not an issue, more like an improvement.

It would be cool to have something like `yii\caching\Cache`'s `getOrSet` in `yii\di\Container`.

It would basically be `yii\di\Container::get()` with a normalized definition that gets saved before the object is built.

I know:
1) I can bootstrap the part in which I set the definitions or init them in the parts of my app that rely on them to be available.
2) I can just check if the definition exists, if not, set it up and it will be used whenever an instance of that will be requested via DI.

But
1) Those pile up unnecessarily, I will have definitions my application won't need in order to function. Moreover, plugging/unplugging those can lead to errors.
2) Requires more code, `getOrSet` would be a nice shortcut.

**Comment by samdark** [comment]
Thanks for proposal. For 2.x we cannot apply it since it's in bugfix-only mode for a while. For 3.0 DI container is different: https://github.com/yiisoft/di
