### ISSUE TITLE
// TODO: drop old PHP versions support

### ISSUE THREAD

**Issue by lucaantonelli** [yiisoft/yii2#17224]
Into the emailVaildator there is a todo not done (?)
 This is the code:
`private function idnToAscii($idn)
    {
        if (PHP_VERSION_ID < 50600) {
            // TODO: drop old PHP versions support
            return idn_to_ascii($idn);
        }
        return idn_to_ascii($idn, IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46);
    }`

**Comment by samdark** [comment]
It's done in 3.0.
