### ISSUE TITLE
#16681 cause error if the $config param not already include 'options' key

### ISSUE THREAD

**Issue by webinjaz** [yiisoft/yii2#17220]
#16681

```php
    public function widget($class, $config = [])
    {
        foreach ($this->inputOptions as $key => $value) {
            if (!isset($config['options'][$key])) {
                $config['options'][$key] = $value;
            }
        }
```

must be 

```php
    public function widget($class, $config = [])
    {
        foreach ($this->inputOptions as $key => $value) {
             if(!isset($config['options']){
                  $config['options'] = [];
              }
            if (!isset($config['options'][$key])) {
                $config['options'][$key] = $value;
            }
        }
```

**Comment by webinjaz** [comment]
i have this code and i get error on it

`					$form->field($model, "xs_$lang")->widget(PhotoInput::className(), [
						'form' => $form,
						'imgWidth' => 200,
						'imgHeight' => 200 * $mod->getPhotoSaveDimension('xs')['height'] / ($mod->getPhotoSaveDimension('xs')['width']?:400),
					]).`

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/a7f98964151d5894d9862fb0a1bf80040de86b69

**Comment by samdark** [comment]
Reverted. See https://3v4l.org/D988b

**Comment by s1lver** [comment]
That doesn't solve the problem
```php
<?= $form->field($model, 'test')
    ->widget(Test::class)
    ->label(false); ?>
```

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: app\components\test\Test::options
```

**Comment by samdark** [comment]
Please post code of Test class.

**Comment by rob006** [comment]
This foreach probably should be moved under `if (is_subclass_of($class, 'yii\widgets\InputWidget'))` condition - `inputOptions` should be populated only for `InputWidget` instances.

**Comment by s1lver** [comment]
I use to pass in attributes.
```php
public $model;
public $attribute;
```
If you add ```$options```, everything works. But, this worked and until 2.0.17. I'm not sure this fix should be like this

> This foreach probably should be moved under `if (is_subclass_of($class, 'yii\widgets\InputWidget'))` condition - `inputOptions` should be populated only for `InputWidget` instances.

It doesn't work.

**Comment by rob006** [comment]
@s1lver How it could not work if `InputWidget` has `options` property? You will never get `UnknownPropertyException` exception in this case.

**Comment by s1lver** [comment]
@rob006 the property is, because I added it there to avoid errors. But, why this surplus action?

**Comment by rob006** [comment]
@s1lver Sorry, I don't get your point. I'm proposing to move this:

https://github.com/yiisoft/yii2/blob/f7fcc0043e1263a281172c8e28c688e2c6e83839/framework/widgets/ActiveField.php#L766-L770

Under this condition:

https://github.com/yiisoft/yii2/blob/f7fcc0043e1263a281172c8e28c688e2c6e83839/framework/widgets/ActiveField.php#L775

You don't need add `options` property manually, since `InputWidget` already has it. And if your widget does not extend `InputWidget`, `inputOptions` will be ignored like before.

**Comment by s1lver** [comment]
> You don't need add options property manually, since InputWidget already has it. And if your widget does not extend InputWidget, inputOptions will be ignored like before.

Yes, I agree with that.

**Comment by s1lver** [comment]
I think we hurried with the correction. Looks like no problem.

**Comment by samdark** [comment]
@s1lver huh?

**Comment by s1lver** [comment]
@samdark now I can not explain more, but in #17230 is a similar situation. in the process of writing tests, I understood my mistake. not inherited from the desired class. if you look closely at the custom widget, the error is the same for everyone. we are trying to implement inputwidget without implementing all its properties. hence the problem. and this error is absolutely correct. solved by proper legacy or additional implementatio

**Comment by rhertogh** [comment]
@rob006 Wrote https://github.com/yiisoft/yii2/issues/17220#issuecomment-476234661:

> I'm proposing to move this:
> 
> [yii2/framework/widgets/ActiveField.php](https://github.com/yiisoft/yii2/blob/f7fcc0043e1263a281172c8e28c688e2c6e83839/framework/widgets/ActiveField.php#L766-L770)
> 
> Lines 766 to 770 in [f7fcc00](/yiisoft/yii2/commit/f7fcc0043e1263a281172c8e28c688e2c6e83839)
> 
>          foreach ($this->inputOptions as $key => $value) { 
>              if (!isset($config['options'][$key])) { 
>                  $config['options'][$key] = $value; 
>              } 
>          } 
> Under this condition:
> 
> [yii2/framework/widgets/ActiveField.php](https://github.com/yiisoft/yii2/blob/f7fcc0043e1263a281172c8e28c688e2c6e83839/framework/widgets/ActiveField.php#L775)
> 
> Line 775 in [f7fcc00](/yiisoft/yii2/commit/f7fcc0043e1263a281172c8e28c688e2c6e83839)
> 
>          if (is_subclass_of($class, 'yii\widgets\InputWidget')) { 
> You don't need add `options` property manually, since `InputWidget` already has it. And if your widget does not extend `InputWidget`, `inputOptions` will be ignored like before.

That would require any widget to  `InputWidget`, my suggestion would be to check if the class has a 'options' property. Please see #17231

**Comment by rhertogh** [comment]
@webinjaz Could you please have a look at #17230 and check if the workaround mentioned there solves your problem or if would still remain, which would mean you're having a different problem.

**Comment by rob006** [comment]
> That would require any widget to InputWidget, my suggestion would be to check if the class has a 'options' property.

If widget should behave as `InputWidget`, then it should extend `InputWidget`. Having `options` property in widget does not mean that it should be input options. Your PR may break BC by assuming intentions by property name.

**Comment by rhertogh** [comment]
> Having `options` property in widget does not mean that it should be input options. Your PR may break BC by assuming intentions by property name.

I agree. But that also works the other way around:
> If widget should behave as `InputWidget`, then it should extend `InputWidget`.

Aren't you then use the class `InputWidget` as an interface? If so, I think it should have it's own `InputWidgetInterface` or `ActiveFieldWidgetInterface`.

**Comment by rob006** [comment]
> If so, I think it should have it's own `InputWidgetInterface`

Technically - yes, it should be an interface. But interfaces cannot contain properties, so changing this will be too invasive for Yii2. It is rather a topic for Yii3

**Comment by s1lver** [comment]
Expected behaviour
```php
class TestCustomInputWidget extends InputWidget
{
    public $model;
    public $attribute;
}
```
or 

```php
class TestCustomInputWidget extends InputWidget
{
    public function run()
    {
        $this->model;
    }
}
```
Error-causing implementation
```php
class TesCustomWidget extends Widget 
{
    public $model;
    public $attribute;
}
```

Here I want to implement my widget, the error is logical, as **ActiveField** expects `$options`. But this is not implemented in the widget.

Therefore, I believe that this is more of a logical error in creating a widget than in **ActiveField**.
