### ISSUE TITLE
FileHelper::normalizePath() breaks custom stream wrappers

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2#17235]
While working on hosting an Yii2 application on standard environment of Google Cloud App Engine, I got into some interesting challenges that I can solve by writing a custom `AssetManager` class (will open-source it or link it to the cook-book).

For example, this should not happen:
```
var_dump(FileHelper::normalizePath('gs://bucket-name/assets/'));
string 'gs:/bucket-name/assets' (length=22)
```
Is it sensible to update the framework to detect custom wrappers or make the double-slash rule smarter?

**Comment by samdark** [comment]
Yes, it is.
