### ISSUE TITLE
datetime formatter get a wrong value on middle night

### ISSUE THREAD

**Issue by DavieLee** [yiisoft/yii2#17232]
$timestamp=1553788800;
language:zh-CN
timezone:Shanghai
date("Y-m-d H:i:s", $timestamp): 2019-03-29 00:00:00 (correct)
datetime formatter: 2019年3月29日 上午12:00:00 (wrong)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 5.5.12
| Operating system |Win 7

**Comment by samdark** [comment]
What intl/ICU versions do you have?

**Comment by rob006** [comment]
What is your timezone settings (`Yii::$app->formatter->timeZone` and `Yii::$app->formatter->defaultTmeZone`)? How you're using formatter?
