### ISSUE TITLE
RateLimiter update timestamp if rate limit exceeded

### ISSUE THREAD

**Issue by Seagull-4auKa** [yiisoft/yii2#17237]
_For discussion_
Is this behavior correct with the timestamp update, when `$allowance < 1`?
https://github.com/yiisoft/yii2/blob/e9b33916b61ecabbe7a754aac7d9f945e4699038/framework/filters/RateLimiter.php#L119-L123
### What steps will reproduce the problem?
```php
class DeviceRateLimit implements RateLimitInterface {
    //...
    public function getRateLimit($request, $action)
    {
        return [2, 120];
    }
}
```
```php
$i = 1;
$API->request();
/**
 * 200 OK
 * `$current = time();` - 1554207300
 * DeviceRateLimit::saveAllowance($request, $action, 1, 1554207300);
 */
sleep(59);

$i++; // 2
$API->request();
/**
 * 200 OK
 * `$current = time();` - 1554207359
 * DeviceRateLimit::saveAllowance($request, $action, 0, 1554207359);
 */
sleep(59);

$i++; // 3
$API->request();
/**
 * 429 Too Many Requests <=== correct behavior
 * `$current = time();` - 1554207418
 * DeviceRateLimit::saveAllowance($request, $action, 0, 1554207418);
 */
sleep(59);
$API->request();
/**
 * 429 Too Many Requests <=== correct behavior ???
 * `$current = time();` - 1554207477
 * DeviceRateLimit::saveAllowance($request, $action, 0, 1554207477);
 */
sleep(59);
while(true) {
    $i++;
    $API->request();
    /**
     * 429 Too Many Requests <=== correct behavior ???
     * `$current = time();` - 1554207300 + $i * 59
     * DeviceRateLimit::saveAllowance($request, $action, 0, $current);
     */
    sleep(59);
}
```
In this case, if you set limits [2, 120] (2 requests for 2 minutes), and send a request to the API every 59 seconds, then after the first 2 requests ALL subsequent (not only the 3rd, 6th, ...) will be with 429 code due to timestamp overwrite.
### What is the expected result?
| Request time             | Rresponse                        | allowance:timestamp(`saveAllowance`)
| ----------------------- | --------------------------- | -----------------------
| 1554207300               | 200 OK                            | 1:1554207300 
| 1554207359(+59)      | 200 OK                            | 0:1554207359
| 1554207418(+59)      | 429 Too Many Requests | 0:1554207359
| 1554207477(+59)      | 200 OK                            | 0:1554207477

First 2 response with `200 OK`, 3rd - `429 Too Many Requests`, 4th - `200 OK`
### What do you get instead?
| Request time             | Rresponse                        | allowance:timestamp(`saveAllowance`)
| ----------------------- | --------------------------- | -----------------------
| 1554207300               | 200 OK                            | 1:1554207300 
| 1554207359(+59)      | 200 OK                            | 0:1554207359
| 1554207418(+59)      | 429 Too Many Requests | 0:1554207418
| 1554207477(+59)      | 429 Too Many Requests | 0:1554207477
| 1554207536(+59)      | 429 Too Many Requests | 0:1554207536
| ... | ... | ... 

First 2 response with `200 OK`, 3rd - `429 Too Many Requests`,  4th - `429 Too Many Requests`, ...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.2
| Operating system | Ubuntu 16.04

Is this behavior correct or is it better to leave the timestamp of the last successful request?

**Comment by samdark** [comment]
Yes. That is expected. The filter is based on http://en.wikipedia.org/wiki/Leaky_bucket and 120 is the window size. It could be drawn as the following:

![img_20190402_230441](https://user-images.githubusercontent.com/47294/55432719-50c72b80-559c-11e9-800d-2125930c62a6.jpg)
