### ISSUE TITLE
Validator attribute problem since version 2.0.17

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#17233]
![image](https://user-images.githubusercontent.com/3417221/55175991-993baf00-5180-11e9-8994-28ca9f5cbcb7.png)

### What steps will reproduce the problem?

We are creating a dynamic model and use the ActiveForm widget afterwards to render the model, this seems to throw the above error since version 2.0.17, with version 2.0.16 it works.

```php
$model = new DynamicModel();
foreach ($organisation->properties as $prop) {
            $model->defineAttribute($prop->id);
            $model->addRule([$prop->id], SafeValidator::class);
            $model->{$prop->id} = ApiOrganisationPropertyValue::getValue($prop, $this->attachedContext);
}
```

Now using ActiveForm for the generate dynamic model throws the warning above (screenshot).

```php
<?= $form->field($model, $vp->id);
```

(i made a check on the `$model` to see if the attribute exists - yes it does. via `$model->hasAttribute($vp->id)`)

### What is the expected result?

No warrnings.

### What do you get instead?

The warnning screenshot

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      | 
| Operating system |

**Comment by machour** [comment]
It would be really interesting if you could use `git bisect` to pinpoint where the problem was introduced.

**Comment by nadar** [comment]
@machour i already made a pull request which addresses the bug: https://github.com/yiisoft/yii2/pull/17234 it has been introduced here: https://github.com/yiisoft/yii2/commit/33fe3476c741d9588183ac187e64c2947bbb07e1#diff-d09779f106252613703461c476a629b5R268

**Comment by machour** [comment]
Thank you for finding the culprit

**Comment by samdark** [comment]
That's a bit weird... https://github.com/yiisoft/yii2/pull/17234/files#r270233325
