### ISSUE TITLE
ActiveField Widget - Setting unknown property options

### ISSUE THREAD

**Issue by rhertogh** [yiisoft/yii2#17230]
### What steps will reproduce the problem?
1. Have a custom widget extending from `yii\base\Widget`
2. Use the widget in an activeField. E.g. `$form->field($model, 'test')->label(false)->widget(MyCustomWidget::class);`

### What is the expected result?

In the `yii\widgets\ActiveField::widget()` function description the following is written:
> Note that the widget must have both `model` and `attribute` properties.

This would imply a 'options' property is not required.

### What do you get instead?

`yii\base\UnknownPropertyException: Setting unknown property: site\widgets\MyCustomWidget::options in /var/www/vhosts/KMS/WEB/847/app/vendor/yiisoft/yii2/base/Component.php:209`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      |  7.2
| Operating system | CentOS 7

### Workaround

Add a dummy 'options' property to your custom widget: 
```php
class MyCustomWidget {

    /**
     * @var array Dummy field to prevent errors when used in ActiveField::widget().
     * For more details please see https://github.com/yiisoft/yii2/issues/17230
     * @deprecated
     */
    public $options;

    //Your other code ...
}
```

### Proposed solution

Make sure the widget has an `options` property before moving `inputOptions` to it PR #17231

**Comment by s1lver** [comment]
Please, look issue #17220

**Comment by rhertogh** [comment]
@s1lver It looks like you're having the same problem. I opened this new issue because #17220 might describe an other issue which might even be a non-issue as showed by samdark https://github.com/yiisoft/yii2/issues/17220#issuecomment-475956359

**Comment by samdark** [comment]
Closing as duplicate.
