### ISSUE TITLE
JsonResponseFormatter when i call “format” function go to line 93 appear "Cannot access self:: when no class scope is active"

### ISSUE THREAD

**Issue by vamper** [yiisoft/yii2#17245]
### What steps will reproduce the problem?
1,public function performAjaxValidation($model)
    {
        if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax && Yii::$app->request->get('ajax-validate')) {
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $b = ActiveForm::validate($model);
                echo json_encode($b);
                Yii::$app->end();
            }
        }
    }
2，go into end();
3，go into $response->send();
4，go into $this->prepare();
5，go into $formatter->format($this);
6，go into line 93 exception appear 
### What is the expected result?
no exception appear
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version    7.0  | 
| Operating system |
win10,apache

**Comment by alex-code** [comment]
There's an easier way, use the `asJson` method.

```php
public function performAjaxValidation($model)
{
  if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax && Yii::$app->request->get('ajax-validate')) {
    if ($model->load(Yii::$app->request->post())) {
      return $this->asJson(ActiveForm::validate($model));
    }
  }
}
```

**Comment by samdark** [comment]
Would you please post stacktrace? Thanks.
