### ISSUE TITLE
404 on the API DOCS ActiveField::radiolist() Link

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#17243]
if you type in google search **"Yii2 radio list"** 

![image](https://user-images.githubusercontent.com/1536454/55290651-49165400-53ef-11e9-8430-149f046dc05d.png)

it shows the following link which throws 404 
`https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.1/yii-bootstrap-activefield`

![image](https://user-images.githubusercontent.com/1536454/55290655-57fd0680-53ef-11e9-8522-e1106875cbda.png)

and if you change the search query to **"Yii2  radiolist"** 

![image](https://user-images.githubusercontent.com/1536454/55290663-6fd48a80-53ef-11e9-971e-93ac412f3b16.png)

then it shows the following link which is working correctly 
`https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.0/yii-bootstrap-activefield`

![image](https://user-images.githubusercontent.com/1536454/55290673-88dd3b80-53ef-11e9-8419-3545d76ed41a.png)

the difference between the 2 links is that the first one points to **`API DOCS V 2.1`** which throws 404, and the second one points to **`API DOCS V2.0`** which works correctly.

**Comment by samdark** [comment]
There's no 2.1 yet so I'm not sure where these links are from and what could be done about it.
