### ISSUE TITLE
I cant't specify the Class of compents.user, I want to use class extends yii\web\User 

### ISSUE THREAD

**Issue by studyzhanglei** [yiisoft/yii2#17252]
### What steps will reproduce the problem?
like title
### What is the expected result?
I can choose The class of compents.user 
### What do you get instead?
/**
     * @inheritdoc
     */
    public function coreComponents()
    {
        return array_merge(parent::coreComponents(), [
            'request' => ['class' => 'yii\web\Request'],
            'response' => ['class' => 'yii\web\Response'],
            'session' => ['class' => 'yii\web\Session'],
            'user' => ['class' => 'yii\web\User'],
            'errorHandler' => ['class' => 'yii\web\ErrorHandler'],
        ]);
    }

yii\web\User always overflow my setting
if replace array_merge to + ,Will it be better?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 5.6
| Operating system |macos

**Comment by bizley** [comment]
[This code](https://github.com/yiisoft/yii2/blob/2.0.17/framework/base/Application.php#L257-L264) should only add default `class` in case configuration of component is an array without `class`. Are you saying that this is not working as intended?

**Comment by studyzhanglei** [comment]
Yes。I want to use the components.user.class not default, it extends default class, i want to do something on logining。

**Comment by bizley** [comment]
I'm using custom user component class and it works properly. Could you share your user component configuration?

**Comment by studyzhanglei** [comment]
'user' => [
            'class'         => 'common\component\CUser',
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity', 'httpOnly' => true, 'domain' => '.xxxx.cn'],
            'loginUrl' => ['login/index'],
        ];
Thank you；

**Comment by studyzhanglei** [comment]
> I'm using custom user component class and it works properly. Could you share your user component configuration?

I'm sorry , I made a big mistake
