### ISSUE TITLE
Regression in Formatter fallback methods for very small numbers

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii2#17268]
### What steps will reproduce the problem?
```Yii::$app->formatter->asCurrency(1E-10, 'EUR');```

### What is the expected result?
```€0.00```

### What do you get instead?
```EUR 1.0E```

### Additional info
The expected result was achieved before `asCurrencyStringFallback()` was added ( https://github.com/yiisoft/yii2/pull/16879)

Related similar issue: https://github.com/yiisoft/yii2/issues/16934

I applied the following quick workaround in my project:

    /**
     * Quick workaround when formatting very small numbers.
     * @see https://github.com/yiisoft/yii2/issues/16934#issuecomment-482078758
     *
     * @inheritdoc
     */
    public function asCurrency($value, $currency = null, $options = [], $textOptions = [])
    {
        if (abs($value) < 1E-9) {
            $value = 0.00;
        }
        
        return parent::asCurrency($value, $currency, $options, $textOptions);
    }

**Comment by samdark** [comment]
Verified that the issue is there. Would you like to fix it with a pull request?

**Comment by marcovtwout** [comment]
I just found this isolated issue, but perhaps this problem applies to the other formatters as well? Maybe the original author of the fallback @bizley can take a look?

**Comment by samdark** [comment]
I took a look. It's, indeed, the fact that `normalizeNumericStringValue()` doesn't take "power" part into account.

**Comment by samdark** [comment]
Here's a fix. @marcovtwout please check if it works for your cases.

**Comment by marcovtwout** [comment]
@samdark Confirmed that this issue is solved with the referenced fix.
