### ISSUE TITLE
orderBy + joinWith is not working

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#17271]
### What steps will reproduce the problem?
               $tagQuery = ClientNestedObjectTag::find();
                $tagQuery->joinWith('clientNestedObject');
                $tagQuery->andWhere([ClientNestedObjectTag::tableName() . '.tagId' => $tag]);
                $objectIdList2 = $tagQuery
                    ->asArray()
                    ->select([ClientNestedObject::tableName() . '.' . 'clientObjectId'])
                    ->indexBy(ClientNestedObject::tableName() . '.' . 'clientObjectId')
                    ->orderBy([ClientNestedObject::tableName() . '.' . 'clientObjectId' => SORT_ASC])
                    ->column();

producet one-element array with empty key. This is last value from column.

w/o select situation is equials:

                $tagQuery = ClientNestedObjectTag::find();
                $tagQuery->joinWith('clientNestedObject');
                $tagQuery->andWhere([ClientNestedObjectTag::tableName() . '.tagId' => $tag]);
                $objectIdList2 = $tagQuery
                    ->asArray()
                    ->indexBy(ClientNestedObject::tableName() . '.' . 'clientObjectId')
                    ->orderBy([ClientNestedObject::tableName() . '.' . 'clientObjectId' => SORT_ASC])
                    ->column();

so... ok. I try to add keys from join. Same situation

                $tagQuery = ClientNestedObjectTag::find();
                $tagQuery->joinWith('clientNestedObject');
                $tagQuery->andWhere([ClientNestedObjectTag::tableName() . '.tagId' => $tag]);
                $objectIdList2 = $tagQuery
                    ->asArray()
                    ->select([
                        ClientNestedObject::tableName() . '.' . 'clientObjectId',
                        ClientNestedObject::tableName() . '.' . 'id',
                        ClientNestedObjectTag::tableName() . '.' . 'clientNestedObjectId',
                        ])
                    ->indexBy(ClientNestedObject::tableName() . '.' . 'clientObjectId')
                    ->orderBy([ClientNestedObject::tableName() . '.' . 'clientObjectId' => SORT_ASC])
                    ->column();

### What is the expected result?
column 
array within all of search result

### What do you get instead?
one value. last from search result

$tagQuery->createCommand()->getRawSql() :

SELECT `client_nested_object_tag`.*
FROM `client_nested_object_tag`
         LEFT JOIN `client_nested_object`
                   ON `client_nested_object_tag`.`clientNestedObjectId` = `client_nested_object`.`id`
WHERE `client_nested_object_tag`.`tagId` = 3
ORDER BY `clientObjectId`;

SELECT `client_nested_object`.`clientObjectId`, `client_nested_object`.`clientObjectId`
FROM `client_nested_object_tag`
         LEFT JOIN `client_nested_object`
                   ON `client_nested_object_tag`.`clientNestedObjectId` = `client_nested_object`.`id`
WHERE `client_nested_object_tag`.`tagId` = 3
ORDER BY `client_nested_object`.`clientObjectId`;

SELECT `client_nested_object`.`clientObjectId`,
       `client_nested_object`.`id`,
       `client_nested_object_tag`.`clientNestedObjectId`
FROM `client_nested_object_tag`
         LEFT JOIN `client_nested_object`
                   ON `client_nested_object_tag`.`clientNestedObjectId` = `client_nested_object`.`id`
WHERE `client_nested_object_tag`.`tagId` = 3
ORDER BY `client_nested_object`.`clientObjectId`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | yiisoft/yii2                                     dev-master ed9264b 
| PHP version      | 
| Operating system |

**Comment by bscheshirwork** [comment]
$tagQuery = ClientNestedObjectTag::find();
                $tagQuery->joinWith('clientNestedObject');
                $tagQuery->andWhere([ClientNestedObjectTag::tableName() . '.tagId' => $tag]);
                $objectIdList2 = $tagQuery
                    ->select([
                        ClientNestedObject::tableName() . '.' . 'clientObjectId',
                        ClientNestedObject::tableName() . '.' . 'id',
                        ClientNestedObjectTag::tableName() . '.' . 'clientNestedObjectId',
                        ])
                    ->indexBy(ClientNestedObject::tableName() . '.' . 'clientObjectId')
                    ->orderBy([ClientNestedObject::tableName() . '.' . 'clientObjectId' => SORT_ASC])
                    ->column();

Try w/o asArray(). Same.

Try  w/o indexBy. Worc correctly.

**Comment by rob006** [comment]
Does it work if you use `->indexBy('clientObjectId')`?

**Comment by bscheshirwork** [comment]
So... It seems NO. :memo:  I can't remember... but I try it first. Before set prefix with table name.

**Comment by bscheshirwork** [comment]
So.. I check history.
```
                $objectIdList2 = $tagQuery
                    ->asArray()
                    ->indexBy('clientObjectId')
                    ->orderBy(['clientObjectId' => SORT_ASC])
                    ->column();

```
