### ISSUE TITLE
Add init event to Component class

### ISSUE THREAD

**Issue by vuongxuongminh** [yiisoft/yii2#17278]
I suggest add an init event to `yii\base\Component`, it will make all component classes more flexible when create extensions for it. Because we can attach behaviors via `INIT_EVENT` via bootstrapping process for control events, add macro methods when init an object.

Ex:

+ We can attach behavior events, methods, properties to all component classes via it (global event).

**Comment by samdark** [comment]
Thanks for idea but I think it will be too much because events aren't free performance-wise and since everything in Yii is a component, it will affect overall performance.
