### ISSUE TITLE
Can I open a webpage using http://localhost:8000?

### ISSUE THREAD

**Issue by xingchunzhe111** [yiisoft/yii2#17279]
### What do you get instead?
Yii2 has a similar laravel framework, launch "php artisan serve" in the console, use http://localhost:8000 to open the web browsing function?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by xingchunzhe111** [comment]
yii2.0

**Comment by imanilchaudhari** [comment]
@xingchunzhe111 please use the forum to ask such a question. 

Yes, Yii2 also have that type of function. you can simply use `php yii serve --docroot="web" --port="8000"`. 

see [docs](https://www.yiiframework.com/doc/guide/2.0/en/start-installation) here

**Comment by xingchunzhe111** [comment]
thanks you
