### ISSUE TITLE
yii2 Method className is deprecated 

### ISSUE THREAD

**Issue by xingchunzhe111** [yiisoft/yii2#17276]
### What is the expected result?
use idea editor or phpstorm editor
prompt:Method className is deprecated
if use ::class
prompt:Class name constant is available in PHP 5.5 only
why?
i use php7.2
How to no longer prompt errors
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by xingchunzhe111** [comment]
Yii version    2.0.6

**Comment by rob006** [comment]
You can change PHP version for inspections in IDE settings: 
![5c86d819](https://user-images.githubusercontent.com/5972388/56274535-3003e780-60ff-11e9-9717-f55d75d322f1.png)
