### ISSUE TITLE
Login Error after signup advanced template

### ISSUE THREAD

**Issue by murraydo** [yiisoft/yii2#17289]
If you installed yii2 advanced template and you signup, you can not login because you get an error like 'incorrect username and password '.  In the model User (common folder) rules was set as default value 'self::STATUS_INACTIVE'. I have set as default value 'self::STATUS_ACTIVE', that works fine.

Don't forget to set 'self::STATUS_INACTIVE' for Production !!!!!!!!
Or set the status of your first user to '10' (as active). I think is a better solution :)
Yii 2.0 Advanced Template
PHP 7.2
LINUX

**Comment by samdark** [comment]
It is part of an email verification process. See https://github.com/yiisoft/yii2-app-advanced/blob/master/frontend/models/VerifyEmailForm.php#L49

**Comment by Gowtham-Go** [comment]
great Thanks!.

**Comment by mbindafarm** [comment]
It has worked for me thank you
