### ISSUE TITLE
[Bug] Active field widget validation error with VALIDATION_STATE_ON_INPUT

### ISSUE THREAD

**Issue by dkhlystov** [yiisoft/yii2#17299]
Because of [this check](https://github.com/yiisoft/yii2/blob/6d10d1f05df9c85ea0ca127bdc6bdc900bc9c6ba/framework/widgets/ActiveField.php#L780), `errorCssClass` added to widget input if only `options` passed in config.

### What steps will reproduce the problem?
Add validation rule to model.
Use form with `VALIDATION_STATE_ON_INPUT`.
Add field on form as widget **without config**.
```php
<?= $form->field($model, 'attribute')->widget(SomeWidget::className()) ?>
```
Submit with error.

### What is the expected result?
Error css class added to input.

### What do you get instead?
Input without error css class.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by rob006** [comment]
The issue looks valid for me. I think we should replace 

```php
            if (isset($config['options'])) {
                if ($this->form->validationStateOn === ActiveForm::VALIDATION_STATE_ON_INPUT) {
                    $this->addErrorClassIfNeeded($config['options']);
                }
                $this->addAriaAttributes($config['options']);
                $this->adjustLabelFor($config['options']);
            }
```
by
```php
            if (!isset($config['options'])) {
                $config['options'] = [];
            }
            if ($this->form->validationStateOn === ActiveForm::VALIDATION_STATE_ON_INPUT) {
                $this->addErrorClassIfNeeded($config['options']);
            }
            $this->addAriaAttributes($config['options']);
            $this->adjustLabelFor($config['options']);
```
