### ISSUE TITLE
Exception "Cannot modify header information..." when running migration

### ISSUE THREAD

**Issue by Slayvin** [yiisoft/yii2#17293]
Hello,
I've got this weird issue when I'm running a migration file I've just created. All previous migrations did run correctly, but this one won't, and I've no clue why!

### What steps will reproduce the problem?
Create a new migration file:
```php
<?php

use yii\db\Migration;

/**
 * Class m190429_111629_update_tracks_table
 */
class m190429_111629_update_tracks_table extends Migration
{

    /**
     * {@inheritdoc}
     */
    public function up()
    {
        $tracksTable = '{{%tracks}}';
        $this->addColumn($tracksTable, 'order', $this->integer()->defaultValue(0));
    }

    /**
     * {@inheritdoc}
     */
    public function down()
    {
        $tracksTable = '{{%tracks}}';
        $this->dropColumn($tracksTable, 'order');
    }
}
```
and run the console command:
~~~
php yii migrate
~~~

### What is the expected result?
Migration without exception.

### What do you get instead?
An error is thrown and the migration is not applied.
```
> add column order integer to table {{%tracks}} ...Exception 'yii\db\Exception' with message 'Cannot modify header information - headers already 
sent by (output started at /home/.../vendor/yiisoft/yii2/db/Migration.php:577)
Failed to prepare SQL:  ALTER TABLE `tracks` ADD `order` int(11)
``` 
If I run the migration with `$compact=true`, it works as expected, but I've never had to do that before...

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17-dev
| PHP version      |  7.0.33
| Operating system |Linux

**Comment by samdark** [comment]
That's super-weird. The error usually appears in web applications, not in console. Are you running wrong PHP binary?
