### ISSUE TITLE
"session_set_cookie_params()" does not handle session lifetimes correctly

### ISSUE THREAD

**Issue by ziaratban** [yiisoft/yii2#17291]
### What steps will reproduce the problem?
session_set_cookie_params php function does not handle session lifetimes correctly.
https://www.php.net/manual/en/function.session-set-cookie-params.php#100657

`web.config`
```php
'session' => [
    'class' => 'yii\web\DbSession',
    'db' => 'db',
    'sessionTable' => 'sessions',
    'cookieParams' => [
        'secure' => false,
        'httponly' => false,
        'lifetime' => time() + (365 * 24 * 60 * 60), #one year
    ],
    'timeout' => 365 * 24 * 60 * 60, #one year
],
```
### What is the expected result?
set timeout cookie

### What do you get instead?
cookie timeout not be set.(When the browser is closed, the cookie is deleted)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.18

**Comment by ziaratban** [comment]
hi

please set this config in `web.config` file
```php
'session' => [
    'class' => 'yii\web\Session',
    'cookieParams' => [
        'domain' => '.example.com',
    ],
],
```

after run -> domain `.example.com` not set!!!

i traced this problem , finally find this problem in [Session.php:404](https://github.com/yiisoft/yii2/blob/331d9971857d8c95cf1bf12b1a2f9f8fa83f1125/framework/web/Session.php#L404)
```php
session_set_cookie_params($data['lifetime'], $data['path'], $data['domain'], $data['secure'], $data['httponly']);
````
`session_set_cookie_params` return false.

**Comment by samdark** [comment]
Can you check if the session is started by the time `session_set_cookie_params()` is called?

**Comment by samdark** [comment]
I've checked and for the clean basic application it works well setting lifetime properly. btw., you have an error there. Lifetimes is number of seconds, not timestamp so there's no need to add `time()`.

**Comment by ziaratban** [comment]
yes , i edit first post.
finally find this problem.
`session_set_cookie_params` return false if you set below settings in php-fpm.
```
session.cookie_lifetime
session.cookie_path
session.cookie_domain
```

**Comment by samdark** [comment]
fpm? What do you mean? How to reproduce it?

**Comment by ziaratban** [comment]
yes. php-fpm.
in last test for this problem, i create a test.php inside index.php of yii.
test.php
```php
session_set_cookie_params(1000,'/','.example.com');
session_start();
```
after run `test.php` , `session_set_cookie_params` return `false` , so this is not a yii2 bug.
i search in settings(php,php-fpm and ...) on server and i find below setting in `mysite.conf` (is php-fpm config)

```
php_admin_value[session.cookie_lifetime] = 1500
```
if you set this php setting by `php_admin_value` flag in php-fpm , `session_set_cookie_params` return false.

**Comment by samdark** [comment]
Ah, right. That's PHP behavior defined for `php_admin_value`. If it's used, application can't change it later.

**Comment by Sport-amazon-kms** [comment]
> Ah, right. That's PHP behavior defined for `php_admin_value`. If it's used, application can't change it later.





https://valiantgoogle-chrome38.github.io/TE9NCLS9PXDBq8qUwb0aFLRPENqCQeAJkKOWLyfEMZuQu6BM7/
