### ISSUE TITLE
Automatically start session when user calls getId on Session component, while the session was not opened

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2#17290]
### What steps will reproduce the problem?
Call `Yii::$app->session->id` on closed session

### What is the expected result?
Session component would automatically start the session and return session_id()

### What do you get instead?
Empty string

### Additional info
Why not we add a call to `$this->open()` so the `getId()` method would look like this:
```
public function getId()
{
    $this->open();
    return session_id();
}
```

This will ensure that if the user tries to access the session, it will be opened automatically

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      | 7.2.16
| Operating system | CentOS 7.6 x64

**Comment by samdark** [comment]
It's done on purpose to have a way to check if session is started without starting it.

**Comment by evil1** [comment]
Woldn't it be more logical to have a `getIsOpened()` method for this purpose?
