### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by buiduongthe** [yiisoft/yii2#17296]
### What steps will reproduce the problem?
My Config 

`[
                    'class' => 'yii\rest\UrlRule',
                    'controller' => ['v2/user'],
                    'extraPatterns' => [
                        'Delete {ids}'      =>  'delete',
                        'PATCH'        => 'update'
                    ],
                ],`

My API

**PATCH**  https://api.abc.com/v1/users/147

My Controller

`public function behaviors()
    {
        $behaviors = parent::behaviors();
        $auth = $behaviors['authenticator'];
        unset($behaviors['authenticator']);
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::className(),
        ];
        $behaviors['authenticator'] = ['class' => HttpBearerAuth::className()];
        $behaviors['authenticator']['except'] = ['options'];
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['USER'],
                ],
            ],
        ];
        return $behaviors;
    }`

My Result

**GET, POST** => OK
**PATCH** : Access to XMLHttpRequest at 'https://api.abc.com/v1/users/147' from origin 'https://test.abc.com has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### What is the expected result?

I Want to Updated User 147

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.18
| PHP version      |  7.2.14
| Operating system | Centos

Thanks Everyone

**Comment by rumours86** [comment]
/**
     * @inheritdoc
     */
    public function behaviors(): array
    {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
            'cors' => [
                'Origin' => [Yii::$app->request->getOrigin()],
                'Access-Control-Allow-Credentials' => true,
            ],
        ];
        return $behaviors;
    }
