### ISSUE TITLE
default order for sort can't pass table name as prefix

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#17302]
### What steps will reproduce the problem?
So... I can add additional order
```php
        $dataProvider->sort->attributes = array_merge($dataProvider->sort->attributes, [
            'anotherModel' => [
                'asc' => [$anotherModelTable . '.name' => SORT_ASC],
                'desc' => [$anotherModelTable . '.name' => SORT_DESC],
                'default' => SORT_ASC,
            ],
            'blockFilter' => [
                'asc' => [static::tableName() . '.[[' . 'isActive' . ']]' => SORT_ASC],
                'desc' => [static::tableName() . '.[[' . 'isActive' . ']]' => SORT_DESC],
                'default' => SORT_ASC,
            ],
        ]);

```
And I wish to add default order in same format
```php
        $dataProvider->sort->defaultOrder = [static::tableName() . '.' . 'id' => SORT_DESC];
```
### What is the expected result?
Default order is a `id desc`

### What do you get instead?
SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'order clause'
https://github.com/yiisoft/yii2/blob/6d10d1f05df9c85ea0ca127bdc6bdc900bc9c6ba/framework/data/Sort.php#L222
`$attributeOrders` is a 
```php
array (
  '{{%this_table}}.id' => 3,
)
```
for case w/o default order and with sort by `blockFilter`
`$attributeOrders` is a
```
Array
(
    [blockFilter] => 4
)
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  v2.0.19-dev
| PHP version      | 7.3.3
| Operating system |

**Comment by bscheshirwork** [comment]
We can add note to docs like

w/o table prefix. In this case 'id' is key of $dataProvider->sort->attributes

**Comment by leocharrua** [comment]
Hello. I have a similar issue with version 2.0.42.1.

 ```
public function getPayroll()
 {
        return $this->hasOne(\app\models\Payrolls::class, ['id' => 'payroll_id']);
 }
```

==============

```
$query = PayrollTotals::find();

$dataProvider = new ActiveDataProvider([
            'query' => $query,
]);

$query->joinWith(['payroll']);

$dataProvider->sort = ['defaultOrder' => ['payroll.payroll_at' => SORT_DESC]];

```

And I get this error:

PHP Notice – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
**Undefined index: payroll.payroll_at**

![error_defaultsort](https://user-images.githubusercontent.com/1721923/157691164-125b939b-a532-474d-b40e-563a9f749043.jpg)

**Comment by leocharrua** [comment]
Hello. Any news about this issue? Thanks

**Comment by bizley** [comment]
Sorted attributes (and default order in sorted attributes) are using normalized versions of them so simple `payroll_at` is enough.

**Comment by leocharrua** [comment]
Thanks @bizley , but if you have to sort for attributes with the same name from differents tables?. For example: `table1.name` and `table2.name` ... in this case, you can put only `name`. Do you understand what is the problem here? Thanks

**Comment by bizley** [comment]
Yes, for that you have [attributeMap](https://www.yiiframework.com/doc/api/2.0/yii-data-datafilter#$attributeMap-detail).

**Comment by bizley** [comment]
Oh, sorry for being misleading, this is for data filter indeed, my mistake. If I remember correctly adding an [additional artificial sort attribute](https://github.com/yiisoft/yii2/blob/master/framework/data/Sort.php#L140) would be enough - just use any sufficient name for it and then configure it with proper DB identifiers like

```php
'yourVirtualSorter' => [
    'asc' => ['proper.column.name' => SORT_ASC],
    'desc' => ['proper.column.name' => SORT_DESC],
    'default' => SORT_DESC,
],
```

**Comment by leocharrua** [comment]
Nop @bizley ... with that I'm back to the original error of my post.

If I put:

`  $dataProvider->sort = ['defaultOrder' => ['projects.name' => SORT_ASC, 'jobs.name' => SORT_ASC]];
`

I get the error:

PHP Notice – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Undefined index: projects.name

Do you have any more ideas?

Thanks

**Comment by bizley** [comment]
So using `yourVirtualSorter` there does not work?

**Comment by leocharrua** [comment]
What do you mean with `yourVirtualSorter`? ... I'm doing that with this, or not?:

`$dataProvider->sort = ['defaultOrder' => ['projects.name' => SORT_ASC, 'jobs.name' => SORT_ASC]];`

Can you explain your suggestion a little more?

Thanks

**Comment by bizley** [comment]
I've mentioned it 4 comments above this one.

**Comment by leocharrua** [comment]
Ok, I understand now your suggestion... No no, I don't wanna enable sorting in the grid for a column of a relation ... that is not the problem.
I wanna define the atributtes for defaultSort of the search.

Can you help me?

**Comment by bizley** [comment]
Please check if setting this virtual sorting attribute and using it as a default one works otherwise I'm out of ideas.

**Comment by leocharrua** [comment]
If I set `yourVirtualSorter` nothing happens. 
I need set the **default order for the dataProvider**.
The dataProvider has the `sort` property, but It not works with fields with table prefix.
If you don't have more ideas, please, reopen the issue. 
Thanks

**Comment by leocharrua** [comment]
Excelent @bizley ... thank you so much. It works great!!!!

**Comment by leocharrua** [comment]
Auch!  Sorry @bizley , only one thing ... when I define `'sort' => [...` with `'attributes' => [...` part, I must enumerate all the attributes of the table, if not, I lost the sort function in the grid. Is there any workarround for that?

**Comment by leocharrua** [comment]
Sorry @bizley , I don't get it. Can you send me a example, please

**Comment by leocharrua** [comment]
Ok. Here is one method:
```
        $dataProvider->setSort([
                'defaultOrder' => [
                    'projectName' => SORT_ASC,
                    'jobName' => SORT_ASC,
                ],
                'attributes' => array_merge(
                    $dataProvider->getSort()->attributes,
                    ['projectName' => [
                        'asc' => ['projects.name' => SORT_ASC],
                        'desc' => ['projects.name' => SORT_DESC],
                        'default' => SORT_ASC,
                    ],
                    'jobName' => [
                        'asc' => ['jobs.name' => SORT_ASC],
                        'desc' => ['jobs.name' => SORT_DESC],
                        'default' => SORT_ASC,
                    ],
                ]),
        ]);
```

More help here:

https://stackoverflow.com/questions/42828987/yii2-add-related-attribute-to-sort

**Comment by mr-shing** [comment]
do this instead 
    'sort' => [
                'attributes' => [
                    'id' => [
                        'asc' => [YourModel::tableName() . '.id' => SORT_ASC],
                        'desc' => [YourModel::tableName() . '.id' => SORT_DESC],
                    ],
                ],
                'defaultOrder' => ['id' => SORT_DESC]
            ],
