### ISSUE TITLE
AssetManager appendTimestamp not updating asset parameter version after file modification

### ISSUE THREAD

**Issue by richard-j-c** [yiisoft/yii2#17304]
as #8190 

`appendtimestamp` appends the time stamp param as expected. But on modifying the asset files, the param is not updated. Manually deleting the assets folder will then show up the correct timestamp in the param.

### What steps will reproduce the problem?
Use of following in config/main.php
```
'assetManager' => [
   'appendTimestamp' => true,
],
```
And in asset bundle
```
public $sourcePath = '@app/theme/somefolder';
public $css = [
    'css/main.css',
 ];
public $js = [
    'js/main.js',
];
```

load page, get:
`https://www.someurl.com/assets/36056f5a/js/main.js?v=1557295291`

modify file.

load page, get same:
`https://www.someurl.com/assets/36056f5a/js/main.js?v=1557295291`

### What is the expected result?
Should append modified file timestamp after modification, loading new file.

### What do you get instead?
modified file does not update timestamp after modification, loads old cached file.

### Additional info
If I use the following, it functions as expected
```
public $basePath = '@app/theme/somefolder';
public $baseUrl = '@app';
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.1.25 or 7.1.23
| Operating system | OSX 10.14.4 or Amazon Linux AMI 2018.03

**Comment by evgeniy123** [comment]
same problem

**Comment by asadkhalili** [comment]
I have this problem too

**Comment by FabrizioCaldarelli** [comment]
This is not a bug, because `appendTimestamp` only add timestamp to the end of the url.

That is timestamp of target file. Files are copied from sourcePath to destination folder (inside web/assets) in these cases:
- target path does not exist;
- `forceCopy` flag is active (https://www.yiiframework.com/doc/api/2.0/yii-web-assetmanager#$forceCopy-detail).

So, after the first website load, target paths are created and filled with source files and they are never updated anymore.

Use `forceCopy` flag in development environment and remember to empty web/assets folder when deploy to production environment.

**Comment by Radon8472** [comment]
> This is not a bug, because `appendTimestamp` only add timestamp to the end of the url.
> 
> That is timestamp of target file. Files are copied from sourcePath to destination folder (inside web/assets) in these cases:
> 
>     * target path does not exist;
> 
>     * `forceCopy` flag is active (https://www.yiiframework.com/doc/api/2.0/yii-web-assetmanager#$forceCopy-detail).
> 
> 
> So, after the first website load, target paths are created and filled with source files and they are never updated anymore.
> 
> Use `forceCopy` flag in development environment and remember to empty web/assets folder when deploy to production environment.

Why ??

I would expect if the source file changes, the assets should be re-created.

**Comment by Radon8472** [comment]
> This is a very simple mechanism - `filemtime` is used. If you see `timestamp` not changed please double check whether indeed the **published** file has been modified or maybe you are looking at the original file that has not been copied yet as mentioned here earlier.

The check via filetime is the same way I would realize this, but it does not work, my source files time is changed, but the assets file is only change, when I change anything in the assets class file, but not when I change contents in my css (that is listed in the assets class).

thats my class:

```php
class LocalizedFormFieldAsset extends AssetBundle
{
    public $sourcePath = '@backend/assets_b';
    public $css = ['css/localized-form-field.css'];
    public $js = ['js/localized-form-field.js'];
    public $jsOptions = [
        'position' => View::POS_END
    ];
    public $depends = [
        'yii\web\JqueryAsset'
    ];

}
```
