### ISSUE TITLE
Yii2 validate rule problem on generated model

### ISSUE THREAD

**Issue by hyquoccuong** [yiisoft/yii2#17303]
### What steps will reproduce the problem?
When I generate model, yii generate wrong validation rule for tinyint data type

My db field:

`
  `is_active` tinyint(1) NOT NULL,
`
But in funtion rules of model generated

```
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
           ...
            [['is_active'], 'string', 'max' => 1],
           ...
        ];
    }
```
So I think it detect wrong data type for tinyint type.

### What is the expected result?
            [['is_active'], 'integer', 'max' => 1],
### What do you get instead?
            [['is_active'], 'string', 'max' => 1],
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1
| Operating system | Windows 10 Pro

**Comment by machour** [comment]
What's your database system? Have you tried with the latest version of yii and gii?

**Comment by hyquoccuong** [comment]
> What's your database system? Have you tried with the latest version of yii and gii?

I'm using mysql MariaDB 10.1.37
I will try to update yii to latest stable version

**Comment by machour** [comment]
Please also include `show create table` results
