### ISSUE TITLE
updateAllCounters unpredictable behavior with null

### ISSUE THREAD

**Issue by johnluxor** [yiisoft/yii2#17308]
### What steps will reproduce the problem?
If the value of counter I pass NULL, so the value of column set NULL instead of unchange

Hi, I don't know if it is expected behavior, if yes I think it is not clear. I think Null should be equal 0(zero) in this case to unchange value. Or throw Exception, because counter must be INT if exclude double numbers 

Current value of counter field is 10
```
Model::updateAllCounters(['counter' => null], ['id' => 1]);
````
### What is the expected result?

counter = 10

### What do you get instead?

counter = NULL

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.18
| PHP version      |  7.2.18
| MySQL | 5.7 
| Operating system |  Ubuntu 16.04 / Win10

**Comment by Thoulah** [comment]
`attribute name => increment value`

Incrementing by `null` seems odd

**Comment by samdark** [comment]
Thanks for reporting but it won't be changed. If you don't need to increment value, it makes no sense to call `updateAllCounters()` at all.
