### ISSUE TITLE
CAPTCHA image not generated (PHP 7.3 + GD)

### ISSUE THREAD

**Issue by PELock** [yiisoft/yii2#17305]
### What steps will reproduce the problem?

It seems there's a bug in CAPTCHA generation for latest PHP 7.3 (with GD) and Yii2

### What is the expected result?

CAPTCHA image generated

### What do you get instead?

2019-05-08 15:49:07 [xxx][-][m4q6qcmu49dn85iknjfncie8m5][error][yii\base\ErrorException:2] yii\base\ErrorException: imagepng(): gd-png error: cannot allocate libpng main struct
 in /home/domain/www/public_html/domain.com/vendor/yiisoft/yii2/captcha/CaptchaAction.php:311
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'imagepng(): gd-...', '/home/domain/ww...', 311, Array)
#1 /home/domain/www/public_html/domain.com/vendor/yiisoft/yii2/captcha/CaptchaAction.php(311): imagepng(Resource id #151)
#2 /home/domain/www/public_html/domain.com/vendor/yiisoft/yii2/captcha/CaptchaAction.php(256): yii\captcha\CaptchaAction->renderImageByGD('rkb')
#3 /home/domain/www/public_html/domain.com/vendor/yiisoft/yii2/captcha/CaptchaAction.php(142): yii\captcha\CaptchaAction->renderImage('rkb')
#4 [internal function]: yii\captcha\CaptchaAction->run()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.3
| Operating system | Debian Stretch

**Comment by machour** [comment]
Can you provide a phpinfo() ? I'm especially interested in the ./configure options and GD section.

**Comment by PELock** [comment]
PHP Version 7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b


GD Support | enabled
-- | --
GD headers Version | 2.2.5
GD library Version | 2.2.5
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.6.3
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 6b
PNG Support | enabled
libPNG Version | 1.6.28
WBMP Support | enabled
XPM Support | enabled
libXpm Version | 30411
XBM Support | enabled
WebP Support | enabled

Core
PHP Version	7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b
Directive	Local Value	Master Value
allow_url_fopen	On	On
allow_url_include	Off	Off
arg_separator.input	&	&
arg_separator.output	&	&
auto_append_file	no value	no value
auto_globals_jit	On	On
auto_prepend_file	no value	no value
browscap	no value	no value
default_charset	UTF-8	UTF-8
default_mimetype	text/html	text/html
disable_classes	no value	no value
disable_functions	pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,	pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
display_errors	Off	Off
display_startup_errors	Off	Off
doc_root	no value	no value
docref_ext	no value	no value
docref_root	no value	no value
enable_dl	Off	Off
enable_post_data_reading	On	On
error_append_string	no value	no value
error_log	no value	no value
error_prepend_string	no value	no value
error_reporting	22527	22527
expose_php	Off	Off
extension_dir	/usr/lib/php/20180731	/usr/lib/php/20180731
file_uploads	On	On
hard_timeout	2	2
highlight.comment	#FF8000	#FF8000
highlight.default	#0000BB	#0000BB
highlight.html	#000000	#000000
highlight.keyword	#007700	#007700
highlight.string	#DD0000	#DD0000
html_errors	On	On
ignore_repeated_errors	Off	Off
ignore_repeated_source	Off	Off
ignore_user_abort	Off	Off
implicit_flush	Off	Off
include_path	.:/usr/share/php	.:/usr/share/php
input_encoding	no value	no value
internal_encoding	no value	no value
log_errors	On	On
log_errors_max_len	1024	1024
mail.add_x_header	Off	Off
mail.force_extra_parameters	no value	no value
mail.log	no value	no value
max_execution_time	600	600
max_file_uploads	20	20
max_input_nesting_level	64	64
max_input_time	60	60
max_input_vars	1000	1000
memory_limit	600M	600M
open_basedir	no value	no value
output_buffering	4096	4096
output_encoding	no value	no value
output_handler	no value	no value
post_max_size	256M	256M
precision	14	14
realpath_cache_size	4096K	4096K
realpath_cache_ttl	120	120
register_argc_argv	Off	Off
report_memleaks	On	On
report_zend_debug	On	On
request_order	GP	GP
sendmail_from	no value	no value
sendmail_path	/usr/sbin/sendmail -t -i 	/usr/sbin/sendmail -t -i 
serialize_precision	-1	-1
short_open_tag	On	On
SMTP	localhost	localhost
smtp_port	25	25
sys_temp_dir	no value	no value
syslog.facility	LOG_USER	LOG_USER
syslog.filter	no-ctrl	no-ctrl
syslog.ident	php	php
track_errors	Off	Off
unserialize_callback_func	no value	no value
upload_max_filesize	256M	256M
upload_tmp_dir	no value	no value
user_dir	no value	no value
user_ini.cache_ttl	300	300
user_ini.filename	.user.ini	.user.ini
variables_order	GPCS	GPCS
xmlrpc_error_number	0	0
xmlrpc_errors	Off	Off
zend.assertions	-1	-1
zend.detect_unicode	On	On
zend.enable_gc	On	On
zend.multibyte	Off	Off
zend.script_encoding	no value	no value
zend.signal_check	Off	Off

**Comment by PELock** [comment]
I didn't even notice it stopped working, I have upgraded my Debian from Jessie to Stretch along with all the PHP libraries, I've tried to find the bug myself but I guess it's deeper in the GD core.

**Comment by machour** [comment]
Yep, definitely not related to Yii.

Please update this issue if you ever solve it!

**Comment by Giorgos241** [comment]
Please let me know if there was a fix to this. Using MAMP PRO with PHP 7.3.24 and I cant load the default contact page
