### ISSUE TITLE
Add ActiveQuery::getIterator() to reduce memory pressure on big data-sets.

### ISSUE THREAD

**Issue by ndobromirov** [yiisoft/yii2#17314]
### What steps will reproduce the problem?
Have a huge data-set mapped to an AR model.

When people want to process the data in a loop they will often call the Model::find()->all().
The issue is that this is not memory efficient, as it's creating a list of all the models at once, where you need them one by one for the processing.

It would be nice to have an iterator that will instantiate models one by one and feed that to the user's code. This way we are having only a single model in-memory at a time. PHP's garbage collection can handle arbitrary sized data sets at that point. We will be bound only by time. Whenever this is done usually, there are migrations and background processing scripts, where time is not that critical (as live web requests).

We've managed to solve it for ourselves by this snippet in a custom base ActiveQuery class:
This was against the MongoDB extension, but it could be useful for all AR models.
```php
    /**
     * Iterator over a given MongoDB cursor query.
     *
     * The iterator walks over a cursor, instantiating models 1 by 1, instead of
     * the Yii's default array that contains the whole result-set.
     *
     * @param Connection $db
     * @return \Generator
     */
    public function getIterator($db = null)
    {
        foreach ($this->buildCursor($db) as $document) {
            foreach ($this->populate([$document]) as $index => $model) {
                yield $index => $model;
            }
        }
    }
```

### What is the expected result?
Allow the user to process the whole data set in a loop in a consistent way (if time limits allow).

### What do you get instead?
Out of memory PHP error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      |  7.2
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
Where would you apply it in the non-Mongo case?

**Comment by ndobromirov** [comment]
I was thinking of the SQL AR classes so it is available there as well.
Iterating over a result set from SQL is not that much different (I think) .

**Comment by SOHELAHMED7** [comment]
Similar issue
https://github.com/yiisoft/yii2/issues/16953

You can use 'each' method

**Comment by samdark** [comment]
Since there's workaround and since the solution would break backwards compatibility, I'd not introduce that to Yii 2. Should be considered for 3.0 though.
