### ISSUE TITLE
jQuery 3.4 support

### ISSUE THREAD

**Issue by sanyisasha** [yiisoft/yii2#17313]
Can you upgrade yii2 composer file to able upgrading to 3.4.1?  
Currently only 3.3.*@stable in composer.  
The main reason for upgrade is **<3.4.1** is vulnerable.  
Prof: https://snyk.io/vuln/npm:jquery  
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.18
| PHP version      |  7.2.12
| Operating system | Linux

**Comment by samdark** [comment]
https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

Check if "Deprecating positional selectors and the sunset of Sizzle" causes BC breaks.

**Comment by sanyisasha** [comment]
Do you mean the 3.4 breaks the current bootstrap version?

**Comment by samdark** [comment]
Should not but should be checked.

**Comment by schmasterz** [comment]
> https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/
> 
> Check if "Deprecating positional selectors and the sunset of Sizzle" causes BC breaks.

From the same blog post:
Specifically, jQuery 3.4.0 is deprecating :first, :last, :eq, :even, :odd, :lt, :gt, and :nth. When we remove Sizzle, we’ll replace it with a small wrapper around querySelectorAll, and it would be almost impossible to reimplement these selectors without a larger selector engine.
**Upgrading**
There should be no compatibility issues if upgrading from jQuery 3.0+.

3.4.x works fine for me. JQuery roadmap for 4.x is something like Yii roadmap for version 3 - "when is done" :).
So I think that it's not a problem to add it in  2.0.19.
