### ISSUE TITLE
Use  QueryAuthparam in REST API can not get a query parameters

### ISSUE THREAD

**Issue by smelike** [yiisoft/yii2#17310]
### What steps will reproduce the problem?
```php
        public function behaviors()
	{
		$behaviors = parent::behaviors();
		
		$behaviors['authenticator'] = [
		'class' => QueryParamAuth::className(),
		'except' => ['login','logout']
		];

		return $behaviors;
	}
```

### What is the expected result?
When I pass the query parameter in the url , such as 

> http://backend.test/commons?access-token=x2qwgZPIQTW6Et-SQnDgdly6BJHJttGx

Then I will get the reponse from the controller instead of 

> "data": {
>         "name": "Unauthorized",
>         "message": "Your request was made with invalid credentials.",
>         "code": 0,
>         "status": 401,
>         "type": "yii\\web\\UnauthorizedHttpException"
>     }
> 

### What do you get instead?

use $request and $request->get print in QueryParamAuth.php.  There is 

```php
/**
     * {@inheritdoc}
     */
    public function authenticate($user, $request, $response)
    {
        print_r($request);
        print_r($request->get());
        exit;
```

> [_url:yii\web\Request:private] => /commons?access-token=x2qwgZPIQTW6Et-SQnDgdly6BJHJttGx

> Array
> (
>     [/commons] => 
> )

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | This is Yii version 2.0.18-dev.
| PHP version      |  PHP 7.1
| Operating system | Windows 7

**Comment by smelike** [comment]
This issue had been fixed. 

https://github.com/yiisoft/yii2/issues/15305#issue-280064007

> Apache - .htaccess


`RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
#RewriteRule ^(.*)$ /index.php?/$1 [L]
RewriteRule . index.php
`

**Comment by smelike** [comment]
@samdark Alexander Makarov, Tanks a lot. I have fixed it by myself.

**Comment by NingerJohn** [comment]
Thank you very much, man! you saved the rest of my day, haha
