### ISSUE TITLE
When I pass the parameter by put method, I got nothing.

### ISSUE THREAD

**Issue by smelike** [yiisoft/yii2#17311]
I use restful api, and pass the parameters by postman with put method.
But I can not get any paramters.
### What steps will reproduce the problem?

```
$request = Yii::$app->request;
if ($request->isPut) {
      var_dump($request->bodyParams);
      var_dump($request->getBodyParam('title'));
     exit;
}
```
### What is the expected result?

the passed value of title, such as title = "test".

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | Yii 2.0.18 dev.
| PHP version      |  php 7.2
| Operating system | Windows 7

**Comment by samdark** [comment]
How do you pass parameters?
