### ISSUE TITLE
if $model->load do not send the second parameter, then cannot load request

### ISSUE THREAD

**Issue by smelike** [yiisoft/yii2#17312]
### What steps will reproduce the problem?
Here is my code. It is so simple logic to manage the request and save.
```php
      $model = new TypeSet();
        if ($model->load(Yii::$app->getRequest()->getBodyParams(), '') && $model->save()) {
            $data = ['id' => $model->primaryKey, 'msg' => '创建成功'];
            return $data;
        } else {
            $validateError = $model->getFirstErrors();
	    $validateError = is_array($validateError) ? join(',', $validateError) : '';
	     throw new \yii\web\HttpException(402, $validateError);
        }
```

But if I do not set the second paramter in 

`$model->load(Yii::$app->getRequest()->getBodyParams())`

Then it return the 402 expception. The reason is $model->load() donot get nothing, if I donot set the second paramter.

### What is the expected result?

The code above can load the data.
`$model->load($request->post()) ` 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | Yii 2.1
| PHP version      | PHP 7.2
| Operating system | Windows 7

**Comment by dizews** [comment]
https://www.yiiframework.com/doc/api/2.0/yii-base-model#load()-detail

**Comment by alex-code** [comment]
How are you generating the form?
Unless you're using the `active` methods to generate the inputs you can just use `setAttributes` instead of `load`
```php
$model = new TypeSet();
$model->setAttributes(Yii::$app->getRequest()->post());
if ($model->save()) {
```
