### ISSUE TITLE
Can't check nginx X-Forwarded-Proto from $_SERVER['HTTP_X_FORWARDED_PROTO']

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#17323]
I can see http instead https on createAbsoluteUrl. I try to find source of problem...

### What steps will reproduce the problem?
server {
    listen 443 ssl;
    location / {
        proxy_pass http://some.ip:someport;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
    }
...
}
server {
    listen someport;
...
    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass   php:9000;
    }
}
where fastcgi.conf is standard nginx config

### What is the expected result?

isSecureConnection check $_SERVER['HTTP_X_FORWARDED_PROTO']

### What do you get instead?
```
var_dump(\Yii::$app->request->isSecureConnection);
var_dump(\Yii::$app->request->headers->get('X-Forwarded-Proto', null));
var_dump($_SERVER['HTTP_X_FORWARDED_PROTO']);
```
bool(false) NULL string(5) "https"

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | 7.3.5
| Operating system |

**Comment by bscheshirwork** [comment]
https://github.com/yiisoft/yii2/issues/16264

So... I can add into my config something like
```php
[
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
            'trustedHosts' => [
                '192.168.0.0/24',
            ],
        ],
...
]
```

**Comment by robsch** [comment]
Just a note when if you configure this: you may need to login and logout the user or delete the session, since the [returnUrl](https://www.yiiframework.com/doc/api/2.0/yii-web-user#$returnUrl-detail) might be stored with the wrong scheme in the session.
