### ISSUE TITLE
Add mime aliases for BMP and SVG files

### ISSUE THREAD

**Issue by cmoeke** [yiisoft/yii2#17328]
### What steps will reproduce the problem?
Upload bmp or svg file with file validation rule:
```
public function rules()
{
    return [
        [['files'], 'file', 'skipOnEmpty' => false, 'extensions' => 'bmp,svg']
    ];
}
```
### What is the expected result?
Upload should be successfull.
#### BMP
**Test file:** https://raw.githubusercontent.com/cmoeke/yii2-testfiles/master/test.bmp

test.bmp could not be uploaded.
> Not Acceptable (#406): Array ( [files] => Array ( [0] => Only files with these extensions are allowed: bmp, svg. ) ) 

FileHelper::getMimeType returns at upload for test file "image/x-ms-bmp" (https://github.com/yiisoft/yii2/blob/master/framework/validators/FileValidator.php#L403)

According to https://filext.com/file-extension/BMP the full list of mimetypes for bmp is:
> image/bmp, image/x-bmp, image/x-bitmap, image/x-xbitmap, image/x-win-bitmap, image/x-windows-bmp, image/ms-bmp, image/x-ms-bmp, application/bmp, application/x-bmp, application/x-win-bitmap

So the solution would be to add the following to the file `vendor/yiisoft/yii2/helpers/mimeAliases.php`
    
```
    'image/x-bmp' => 'image/bmp',
    'image/x-bitmap' => 'image/bmp',
    'image/x-xbitmap' => 'image/bmp',
    'image/x-win-bitmap' => 'image/bmp',
    'image/x-windows-bmp' => 'image/bmp',
    'image/ms-bmp' => 'image/bmp',
    'image/x-ms-bmp' => 'image/bmp',
    'application/bmp' => 'image/bmp',
    'application/x-bmp' => 'image/bmp',
    'application/x-win-bitmap' => 'image/bmp',
```

-----

#### SVG
**Test file:** https://raw.githubusercontent.com/cmoeke/yii2-testfiles/master/test.svg

test.svg could not be uploaded.
> Not Acceptable (#406): Array(    [files] => Array        (            [0] => Only files with these extensions are allowed: bmp, svg.        ))

FileHelper::getMimeType returns at upload for test file "image/svg" (https://github.com/yiisoft/yii2/blob/master/framework/validators/FileValidator.php#L403)

So the solution would be to add the following to the file `vendor/yiisoft/yii2/helpers/mimeAliases.php`
    
```
    'image/svg' => 'image/svg+xml',
```

-----

#### Full mimeAliases.php
> https://raw.githubusercontent.com/cmoeke/yii2-testfiles/master/mimeAliases.php

| Q                | A                | A
| ---------------- | ---| ---|
| Yii version      | 2.0.19    | 2.0.17
| PHP version      | 7.2.14    | 7.1.28
| Operating system | Mac OS X 10.13    | Debian 8.11‬

**Comment by samdark** [comment]
@cmoeke thanks for a good description. Want to do a pull request to speed things up?
