### ISSUE TITLE
Invalid argument supplied for foreach() since version 2.0.16

### ISSUE THREAD

**Issue by Discomania** [yiisoft/yii2#17326]
### What steps will reproduce the problem?
create many-many relation with ->via('hasManyRelation') in yii 2.0.15 (working)
update to 2.0.16

### What is the expected result?
get related models

### What do you get instead?
yii\base\ErrorException: Invalid argument supplied for foreach()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16 - 2.0.19
| PHP version      | 7.2.4 or higher
| Operating system | windows 10 or Centos 7

stacktrace

yii\base\ErrorException: Invalid argument supplied for foreach() in C:\wamp64\www\advanced\vendor\yiisoft\yii2\db\ActiveRelationTrait.php:525
Stack trace:
#0 C:\wamp64\www\advanced\vendor\yiisoft\yii2\db\QueryBuilder.php(227): common\models\IngressoQuery->prepare()
#1 C:\wamp64\www\advanced\vendor\yiisoft\yii2\db\ActiveQuery.php(328): yii\db\mysql\QueryBuilder->build()
#2 C:\wamp64\www\advanced\vendor\yiisoft\yii2\db\Query.php(237): common\models\IngressoQuery->createCommand()
#3 C:\wamp64\www\advanced\vendor\yiisoft\yii2\db\ActiveQuery.php(133): common\models\IngressoQuery->all()
#4 C:\wamp64\www\advanced\common\models\IngressoQuery.php(33): common\models\IngressoQuery->all()
#5 C:\wamp64\www\advanced\vendor\yiisoft\yii2\data\ActiveDataProvider.php(116): common\models\IngressoQuery->all()
#6 C:\wamp64\www\advanced\vendor\yiisoft\yii2\data\BaseDataProvider.php(101): yii\data\ActiveDataProvider->prepareModels()
#7 C:\wamp64\www\advanced\vendor\yiisoft\yii2\data\BaseDataProvider.php(114): yii\data\ActiveDataProvider->prepare()
#8 C:\wamp64\www\advanced\vendor\yiisoft\yii2\data\BaseDataProvider.php(155): yii\data\ActiveDataProvider->getModels()
#9 C:\wamp64\www\advanced\vendor\yiisoft\yii2\widgets\BaseListView.php(190): yii\data\ActiveDataProvider->getCount()
#10 C:\wamp64\www\advanced\vendor\yiisoft\yii2\widgets\BaseListView.php(158): yii\grid\GridView->renderSummary()
#11 C:\wamp64\www\advanced\vendor\yiisoft\yii2\grid\GridView.php(326): yii\grid\GridView->renderSection()
#12 C:\wamp64\www\advanced\vendor\yiisoft\yii2\widgets\BaseListView.php(135): yii\grid\GridView->renderSection()
#13 C:\wamp64\www\advanced\vendor\yiisoft\yii2\widgets\BaseListView.php(138): yii\grid\GridView->yii\widgets\{closure}()
#14 C:\wamp64\www\advanced\vendor\yiisoft\yii2\widgets\BaseListView.php(138): ::preg_replace_callback()
#15 C:\wamp64\www\advanced\vendor\yiisoft\yii2\grid\GridView.php(301): yii\grid\GridView->run()
#16 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\Widget.php(140): yii\grid\GridView->run()
#17 C:\wamp64\www\advanced\backend\views\iscritto\view.php(610): yii\base\Widget::widget()
#18 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\View.php(348): yii\web\View->unknown()
#19 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\View.php(257): yii\web\View->renderPhpFile()
#20 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\View.php(156): yii\web\View->renderFile()
#21 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\Controller.php(384): yii\web\View->render()
#22 C:\wamp64\www\advanced\backend\controllers\IscrittoController.php(168): backend\controllers\IscrittoController->render()
#23 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\InlineAction.php(57): backend\controllers\IscrittoController->actionView()
#24 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\InlineAction.php(57): ::call_user_func_array:{C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\InlineAction.php:57}()
#25 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams()
#26 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\Module.php(528): backend\controllers\IscrittoController->runAction()
#27 C:\wamp64\www\advanced\vendor\yiisoft\yii2\web\Application.php(103): yii\web\Application->runAction()
#28 C:\wamp64\www\advanced\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest()
#29 C:\wamp64\www\advanced\backend\web\index.php(17): yii\web\Application->run()
#30 {main}

**Comment by Discomania** [comment]
this is an example code (from your documentation) 

```
class Order extends ActiveRecord
{
    public function getOrderItems()
    {
        return $this->hasMany(OrderItem::className(), ['order_id' => 'id']);
    }

    public function getItems()
    {
        return $this->hasMany(Item::className(), ['id' => 'item_id'])
            ->via('orderItems');
    }
}
```

**Comment by smelike** [comment]
So what'is the matter? Is it been fixed?

**Comment by samdark** [comment]
It was not reproduced. Do you have the same error?
