### ISSUE TITLE
Mismatch in documentation for console commands

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#17331]
There's a conflicting example in the CLI documentation here:

https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-console.md#usage-

Regarding the order of options and arguments it says

> You execute a console controller action using the following syntax:
>    yii <route> [--option1=value1 --option2=value2 ... argument1 argument2 ...]

Then in the example in the next paragraph the order of arguments and options is mixed up:

>     yii migrate/up 5 --migrationTable=migrations

So the latter should be fixed. If the order does not matter it should be clearly stated.

**Comment by samdark** [comment]
Fixed. Order doesn't matter in this case.
