### ISSUE TITLE
Can't add custom HttpException class as a Logger exception

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii2#17334]
### What steps will reproduce the problem?

- Extend base `HttpException`, e.g. `AllowedOnlyForAdminsHttpException`
- Add `AllowedOnlyForAdminsHttpException` to the list of `except` for `Logger` 

### What is the expected result?

All `AllowedOnlyForAdminsHttpException` exceptions are skipped

### What do you get instead?

`AllowedOnlyForAdminsHttpException` exceptions are still logged

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15

This logic is implemented in `yii\base\ErrorHandler::logException()` method:
https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L288

**Comment by alexkart** [comment]
@uaoleg, this behavior is actually mentioned in the documentation https://www.yiiframework.com/doc/guide/2.0/en/runtime-logging

> Info: When an HTTP exception is caught by the error handler, an error message will be logged with the category name in the format of yii\web\HttpException:ErrorCode. For example, the yii\web\NotFoundHttpException will cause an error message of category yii\web\HttpException:404.

For some reason, it was decided to set a category of the log message for http exceptions in this format.

**Comment by alexkart** [comment]
You can extend your own exception class from UserException not HttpException and it will be ignored.
