### ISSUE TITLE
make keyPrefix default to $app->id for host-shared caches like Apc, Memcache

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#17352]
For shared caches, like APCu, Memcache, the defaut behaviour require to use keyPrefix, because of interpolability of hosting application, which share caches. So, defult configuration is not usabled.

I'm proposing set keyPrefix to \Yii::$app->id by default, so, the default configuration of \yii\cache\ApcCache, \yii\cache\MemCache become usable.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.20
| PHP version      | 7.2
| Operating system | debian linux

**Comment by samdark** [comment]
That would cause backwards compatibility break. Won't be done in 2.x.

**Comment by dicrtarasov** [comment]
@samdark 
lets implements it in 3.x

$app->id is the best place for Cache::keyPrefix, and the default configuration is not suitable to work because of cache intersect conflicts in multiple web-applications.
