### ISSUE TITLE
csrfMetaTags spaces between csrf-param & csrf-token

### ISSUE THREAD

**Issue by medfx** [yiisoft/yii2#17363]
Hi guys,
The csrfMetaTags function in helpers/BaseHtml.php creates 4 spaces after the new line between the csrf-param and the csrf-token.
```php
public static function csrfMetaTags()
{
    $request = Yii::$app->getRequest();
    if ($request instanceof Request && $request->enableCsrfValidation) {
        return static::tag('meta', '', ['name' => 'csrf-param', 'content' => $request->csrfParam]) . "\n    "
            . static::tag('meta', '', ['name' => 'csrf-token', 'content' => $request->getCsrfToken()]) . "\n";
    }
    return '';
 }
```
Why is that? For what are the spaces needed? The little autist in me hates that mess in the html header.
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="manifest" href="/manifest.json">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="csrf-param" content="_csrf">
    <meta name="csrf-token" content="mTuwlexo02klmCO8FIB5H4psVt9VVUTOQkmhomOrl_zycsXfqBKwUXfKVftZ-jsu_Rowijo-dYsGOujvEdjIiA==">
<title>title</title>
<link href="/resources/semantic.min.css?v=1560198475" rel="stylesheet">
<link href="/resources/style.css?v=1560350652" rel="stylesheet"></head>
<body>
...
```

Thanks for your help!

**Comment by samdark** [comment]
No special reason for it.

**Comment by alexkart** [comment]
@medfx which browser do you use? In Chrome and in Firefox I see such formatting:

![98cffdcda3942a6c2a97bde2e9346851](https://user-images.githubusercontent.com/8249105/59422963-ddcb0400-8dd9-11e9-9592-d9f90dc03589.png)

**Comment by medfx** [comment]
Looks like its my fault, because I don't indent my header content. But if I would indent it, I would use two spaces not four. Other developers would use two, four or even more. So there is no solution to satisfy everybody. Maybe we could introduce a optional parameter for how many spaces the function would create on the second line?

Sorry guys for wasting your time with this bullshit. :heart:

**Comment by alexkart** [comment]
> So there is no solution to satisfy everybody
Yes.

> Maybe we could introduce a optional parameter for how many spaces the function would create on the second line?

Maybe. Anyway, it should be consistent with or without indentation. I've made PR to remove those spaces. Now all inserted lines to the header are without indentation.
