### ISSUE TITLE
Formatter::asDecimal|Currency() different results depending on decimal part

### ISSUE THREAD

**Issue by sdlins** [yiisoft/yii2#17369]
`Formatter` behavior is different depending on the number has non zero decimal part (like `.55`) or not;

### What steps will reproduce the problem?
In a console app (in a test), run: 
```php
$v1 = \Yii::$app->formatter->asDecimal('960000.00');
$v2 = \Yii::$app->formatter->asDecimal('960000.55');

$I->assertEquals('960.000,00', $v1); // passing
$I->assertEquals('960.000,55', $v2); // failing
```

### What is the expected result?
Both tests true.

### What do you get instead?
```bash
 Fail  Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'960.000,55'
+'960,000.55'

Scenario Steps:

 2. $I->assertEquals("960.000,55","960,000.55") at tests/functional/EspecificacaoDeGarantiasCest.php:56
 1. $I->assertEquals("960.000,00","960.000,00") at tests/functional/EspecificacaoDeGarantiasCest.php:55
```
### More details
The problem also happens when using `asCurrency()` in similar situations.

My formatter configs:
```php
'formatter' => [
    'defaultTimeZone' => 'America/Sao_Paulo',
    'currencyCode' => 'BRL',
    'numberFormatterOptions' => [
        NumberFormatter::MIN_FRACTION_DIGITS => 2,
        NumberFormatter::MAX_FRACTION_DIGITS => 2,
    ],
    'numberFormatterSymbols' => [
        \NumberFormatter::CURRENCY_SYMBOL => 'R$' . (PHP_OS != 'Linux' ? ' ' : ''),
    ],
],
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.20
| PHP version      |  7.1.16
| Operating system | Linux Deepin
| ICU Version | 60.2 
| PHP Intl | Installed

**Comment by sdlins** [comment]
`Formatter::normalizeNumericValue()` cast the number using `$value = (float) $value; // line 1724`, but the cast does not work fine for non-zero decimal part value in console.

Note: in web application the problem never happens, not sure why. All locale, ICU, Intl are the same (I looked in phpinfo for both apps). The same configs for formatter and language are being used for console and web.

**Comment by samdark** [comment]
What do you mean by "not work fine"?

**Comment by sdlins** [comment]
Closing for now because in Win10 I was not able to reproduce the problem. When I am at home (linux) I will investigate a bit more and give more examples about "not working".
