### ISSUE TITLE
$inputOptions in ActiveField

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#17374]
ActiveField::checkbox() and ActiveField::radio() lost $inputOptions.

Similar as other functions do:
```php
 $options = array_merge($this->inputOptions, $options);
```
This issue was fixed for checkbox in 3.x.x:
https://github.com/yiisoft/yii2/issues/861

Please, add this simple fix to 2.x.x and radio() too...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.20
| PHP version      | 7.3
| Operating system | Linux

**Comment by alexkart** [comment]
Should `$this->inputOptions` and `$options` be merged. I think it is done intentionally. In any case, changing this behavior now will break all checkboxes and radio buttons, because `\yii\widgets\ActiveField::$inputOptions` has a default value:

```php
public $inputOptions = ['class' => 'form-control'];
```

**Comment by samdark** [comment]
Can't change it because of backwards compatibility as @alexkart explained.
