### ISSUE TITLE
Component::hasEventHandlers and Event::hasHandlers return false positives

### ISSUE THREAD

**Issue by dmitry-kulikov** [yiisoft/yii2#17377]
### What steps will reproduce the problem?

```php
var_dump(Yii::$app->request->hasEventHandlers('foobar'));
var_dump(Event::hasHandlers(new \stdClass(), 'foobar'));
```

### What is the expected result?

false, false

### What do you get instead?

true, true

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.20
| PHP version      | 7.2.19
| Operating system | Ubuntu 18.04.2

Tested in [yii2-app-basic](https://github.com/yiisoft/yii2-app-basic).
Problem since 2.0.20 and in current master. 2.0.19 is fine. Probably related with https://github.com/yiisoft/yii2/issues/17336.

**Comment by samdark** [comment]
I've verified 2.0.20 behavior is correct and added tests for your case. What you see in a basic application is because it uses debugger which events panel registers a handler for `*` to collect events. That is why any BaseObject descendant has an event.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/1c919a5ac5aa6f63405e0636ff2408ad0a0179a6

**Comment by pabloneruda1** [comment]
So for example
`yii\base\Event::hasHandlers('yii\base\View', 'non_existent_handler')`
with debugger always returns true. I get it right?

**Comment by samdark** [comment]
Yes because debugger adds event handler for everything.

**Comment by pabloneruda1** [comment]
Wildcard handlers are evil. I don't use them. I need check the existence of regular handlers - my application depends on it.
Overriding Event class is not possible, because Event::$_events is private.
How do I do that?

**Comment by samdark** [comment]
Why do you need to check existence instead of triggering/subscribing regardless?

**Comment by pabloneruda1** [comment]
Because of universality. I want to change application behavior without change the core source files.
I will try to explain using the code:
`if($this->hasEventHandlers('do_something_else')){
    $this->trigger('do_something_else');
} else {
    // do the system default process
}`

**Comment by samdark** [comment]
Instead you can trigger all the time and do a chain of handlers:

https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-events.md#event-handler-order

**Comment by pabloneruda1** [comment]
I guess I didn't understand you. My English is not good.
The default system process is processed **ONLY** if there is no "do_something_else" event.
How do I ensure this now?

**Comment by samdark** [comment]
By using `$event->handled` and making system process handler that is executed last.

**Comment by pabloneruda1** [comment]
Event(s) "do_something_else" ca be more than one and I don't know which is executed last.

**Comment by samdark** [comment]
OK. Here's how it could be achieved:

```php
class MyEvent
{
   public $handlersExecuted = false;
}

$event = new Event();
$this->trigger('do_something_else', $event);

// in the handler you're setting $event->handlersExecuted = true

if (!$event->handlersExecuted)
    // do the system default process
}
```

**Comment by litecart-cs** [comment]
Yes, this is a possible solution for me.
Do you plan to implement it in yii/base/Event ;-) ?
Thank you for your help, Yii2 is the best.

**Comment by pabloneruda1** [comment]
Yes, this is a possible solution for me.
Do you plan to implement it in yii/base/Event ;-) ?
Thank you for your help, Yii2 is the best.

**Comment by samdark** [comment]
No, there is no plan to modify yii/base/Event.
