### ISSUE TITLE
Validation on AJAX-populated select boxes is skipped

### ISSUE THREAD

**Issue by aknyazhe** [yiisoft/yii2#17376]
In commit c59df914c1f544889eafc4d8aa64132ae1337102,
the following code:

```
// pass SELECT without options
if ($input.length && $input[0].tagName.toLowerCase() === 'select') {
    if (!$input[0].options.length) {
        return true;
    } else if (($input[0].options.length === 1) && ($input[0].options[0].value === '')) {
        return true;
    }
}
```
makes it so that empty select boxes are not validated. Seems reasonable since a user can't select an option if there are no options. However, if the select box's options are populated through AJAX (or even just JavaScript without AJAX), and this is required for valid form submission, but the user does not trigger the event to populate the select box, then invalid data can be submitted.

### What steps will reproduce the problem?

1. Create an ActiveForm containing a Kartik's Select2 widget on a required field.
2. Configure the Select2 to use ajax.
3. Leave the field empty.
4. Submit the form.

### What is the expected result?

Client-side validation occurs and notifies the user that the required field is in fact, required.

### What do you get instead?

The form is submitted successfully.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16+
| PHP version      | 7.1
| Operating system | Amazon Linux

**Comment by samdark** [comment]
@GHopperMSK would you please take a look at it?

**Comment by ArtemZinenko** [comment]
I have the same problem

**Comment by devaptas** [comment]
same of https://github.com/yiisoft/yii2/issues/17147

**Comment by samdark** [comment]
Closed as duplicate.
