### ISSUE TITLE
\yii\db\Expression error on gps point update

### ISSUE THREAD

**Issue by zuicis** [yiisoft/yii2#17379]
### What steps will reproduce the problem?
a) create column with type: "point"
b) add spatial index to it 
c) at model file create public attributes: 'trackLong and trackLat'
d) at model file update beforeSave function to:
```php5
 public function beforeSave($insert){
        if (parent::beforeSave($insert)){
            //if ($insert) {
                $this -> trackCoordinates = new \yii\db\Expression("PointFromText(:point)", [
                    ':point'=>'POINT('. $this -> trackLong.' '.$this -> trackLat.')'
                ]);
           // }else{
         //   }
            return true;
        }
        return false;
    }  
```
d) try insert/update data from controller 

### What do you get instead?
On insert (first record) - everything works as it should
On update got error: "Malformed UTF-8 characters, possibly incorrectly encoded."

### What is the expected result?
Update without error about utf-8

### Additional info
| Q                | A
| ---------------- | ---
| Tested on Yii version   |  2.0.19 and 2.0.20
| PHP version      |  7.2.18
| Operating system  | Debian 9
| Database  | 15.1 / 10.3.14-MariaDB
| Column type  | point
| Column index  | spatial

**Comment by zuicis** [comment]
I added more information

**Comment by samdark** [comment]
Yii isn't dealing with encoding conversion. That means that one of values you supply contains incorrect unicode sequences.

**Comment by zuicis** [comment]
Strange, because the problem is only with update when i use Expression for mysql column with POINT type also without data  (using empty POINT(0 0)). 

 $model -> trackCoordinates = new \yii\db\Expression("PointFromText(:point)", [
    ':point'=>'POINT(0 0)'
 ]);


```php5
    public function actionUpdate($id){
        $model = GpsPoints::find()-> select([
            '*',
            'ST_X(trackCoordinates) as trackLong',
            'ST_Y(trackCoordinates) as trackLat'
        ]) ->where(['id' => $id]) ->one();
        $container = ['points-grid'];
        if (Yii::$app->request->post()) {
            $post = yii::$app -> request -> post();
            Yii::$app -> response -> format = \yii\web\Response::FORMAT_JSON;
            if ($model->load($post)){
                $connection = \Yii::$app -> db;
                $transaction = $connection -> beginTransaction();  
                try{
                    $model -> trackCoordinates = new \yii\db\Expression("PointFromText(:point)", [
                        ':point'=>'POINT(0 0)'
                    ]);
                    if ($model -> save()){
                        $transaction  -> commit();

```

**Comment by samdark** [comment]
Can you save it using SQL?

**Comment by zuicis** [comment]
Yes, from phpmyadmin insert/update works

**Comment by alex-code** [comment]
If you Google the error, `Malformed UTF-8 characters, possibly incorrectly encoded.` it all comes back as a JSON encoding issue so I'm guessing there's an error with the response.

Does the code get to your transaction commit?
Is the DB updated even though it had an error?

**Comment by kamarton** [comment]
@zuicis It seems to me that this is not related to the update event of the active record, but rather to the output generated by the response.

```php
             // ...
            Yii::$app -> response -> format = \yii\web\Response::FORMAT_JSON;      // <----------------- enable json response
            if ($model->load($post)){
                $connection = \Yii::$app -> db;
                $transaction = $connection -> beginTransaction();  
                try{
                    $model -> trackCoordinates = new \yii\db\Expression("PointFromText(:point)", [
                        ':point'=>'POINT(0 0)'
                    ]);
                    if ($model -> save()){
                        $transaction  -> commit();
              // <------- ... The exception is raised here?
```

Could you provide a stack trace for the exception?
