### ISSUE TITLE
yii\grid\GridView columns format=>html vs raw

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii2#17383]
'format' => 'html'
выдает:` <a href="#url" class="btn btn-primary">link</a>`

'format' => 'raw'
выдает: `<a href="#url" class="btn btn-primary" data-pjax="0" data-test="my-data">link</a>`

пример кода
```
echo GridView::widget([
    ...
    'columns' => [
        ...
        [
            'format' => 'html', // OR raw
            'value' => function ($model) {
                    return Html::a('link', '#url', ['class' => 'btn btn-primary', 'data-pjax'=>'0', 'data-test'=>'my-data']);
            },
        ],
    ]
]);
```

Это нормально, что с форматом html ссылка не показывает другие атрибуты тега ??

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.21
| PHP version      | 7.2
| Operating system | windows10, OpenServer

**Comment by zuicis** [comment]
Da, normalno.
'format' => 'html' = Formats the value as HTML text +  The value will be purified using yii\helpers\HtmlPurifier to avoid XSS attacks. Use asRaw() if you do not want any purification of the value.

'format' => 'raw'  -> Formats the value as is without any formatting.

https://www.yiiframework.com/doc/api/2.0/yii-grid-datacolumn#$format-detail
https://www.yiiframework.com/doc/api/2.0/yii-i18n-formatter#asRaw()-detail
https://www.yiiframework.com/doc/api/2.0/yii-i18n-formatter#asHtml()-detail

**Comment by andrtechno** [comment]
спасибо за ответ
