### ISSUE TITLE
Date validator is not working properly

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#17382]
### What steps will reproduce the problem?
Input Date: 13-Mar-19
System Format: medium `($this->format used in DateValidator)`
 
When `timestampAttribute` set that time not working. like
```
['approval_date', 'date', 'timestampAttribute' => 'approval_date', 'timestampAttributeFormat' => 'yyyy-MM-dd'],
// That Consider a date is valid but is not a valid
```
```
['approval_date', 'date']
//Working Properly
```

### What is the expected result?
Need invalid date message when configure `timestampAttribute` and `timestampAttributeFormat`.

### What do you get instead?
Date is validated

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      | 7.2
| Operating system | Ubuntu 18.04

**Comment by alexkart** [comment]
I confirm that this is incorrect behavior.
I managed to create a test case that reproduces this issue:

```php
IntlTestHelper::$enableIntl = true;
        $this->mockApplication([
            'timeZone' => 'UTC',
            'language' => 'en-US',
        ]);
        $val = new DateValidator(['format' => 'medium', 'timestampAttribute' => 'attr_date', 'timestampAttributeFormat' => 'yyyy-MM-dd']);
        $model = new FakedValidationModel();
        $model->attr_date = '13-Mar-19';
        $val->validateAttribute($model, 'attr_date');
        $this->assertTrue($model->hasErrors('attr_date'));
```

The issue caused by this code https://github.com/yiisoft/yii2/blob/master/framework/validators/DateValidator.php#L388:

```php
$formatter = new IntlDateFormatter('en-US', -1, -1, 'UTC', null, 'yyyy-MM-dd');
// ...
$formatter->setLenient(false);
$parsePos = 0;
$parsedDate = $formatter->parse('13-Mar-19', $parsePos);
```

Instead of returning false it returns negative value (-61750425600).
So, I would appreciate some advice (@samdark ) because I'm not sure how we should fix this. Just check for a negative value in the next line?

```php
        if ($parsedDate === false || $parsedDate < 0 || $parsePos !== mb_strlen($value, Yii::$app ? Yii::$app->charset : 'UTF-8')) {
            return false;
        }
```

**Comment by alexkart** [comment]
@hirenbhut93 It seems that there is a workaround for this, you can specify `min` date and it will throw an exception in this case:

```php
            ['approval_date', 'date', 'timestampAttribute' => 'approval_date', 'timestampAttributeFormat' => 'yyyy-MM-dd', 'min' => '1920-01-01'],
```

But, yes, it's confusing.

**Comment by samdark** [comment]
The negative timestamp you've got is 21.08.1918 that is super-weird. Checking for negative sounds a bit dangerous since user may actually want a date before UNIX timestamp 0 but I see no other choice.

**Comment by alexkart** [comment]
> The negative timestamp you've got is 21.08.1918
Not quite, it's just `0013-03-19` date.

Investigating it a bit more.
Validation of the date is performed based on whether the date can be parsed without an error or not and 
if ICU format is used (intl extension) ICU can parse dates that don't exactly match the format.
For example, it can parse the following dates with this format `yyyy-MM-dd`:

```
0013-03-19
13-Mar-19
13-March-19
13-03-19
13-3-19
13-003-19
0013-Mar-19
13-Mar-00019
```

Any of those dates are considered a valid date for that format by the intl formatter. So, I'm not sure whether it is a correct approach for validating dates format or not.

Alternatively, php date format is more restrictive and works better for validation.

So, @hirenbhut93 in your case it's better to use php format (if you use dates in English only):

```php
['approval_date', 'date', 'timestampAttribute' => 'approval_date', 'timestampAttributeFormat' => 'php:Y-m-d'],

```
Althou two digit year also still be valid in this case (`13-03-19`).

For strict date format validation, I have one idea that we can implement. Maybe add `$strictDateFormat` property to the `\yii\validators\DateValidator` and then add the following code after date parsing https://github.com/yiisoft/yii2/blob/master/framework/validators/DateValidator.php#L388:
```php
$checkDate = $formatter->format($parsedDate);
    if ($checkDate !== $value) {
        return false;
    }
```
It will format the parsed timestamp back to the specified format and check whether formated dated exactly match the original value, in this case for the list of dates above only this date `0013-03-19` will pass validation. What do you think?
