### ISSUE TITLE
Typo in documentation headline "Relational Query - Lazy Loadnig and Eager Loading in Yii 2.0"

### ISSUE THREAD

**Issue by khalwat** [yiisoft/yii2#17387]
There is a typo in documentation headline "Relational Query - Lazy **Loadnig** and Eager Loading in Yii 2.0" on this page:

https://www.yiiframework.com/wiki/834/relational-query-lazy-loadnig-and-eager-loading-in-yii-2-0

It should be **Loading** not `Loadnig`

Note that the slug in the URL is also wrong, and probably should be fixed, with a 301 redirect in place to catch bookmarked URLs.

**Comment by samdark** [comment]
Updated. By the way, it is a wiki so you are able to edit it as well.

**Comment by khalwat** [comment]
Thanks @samdark  I wasn't aware of that!
