### ISSUE TITLE
Correct route url but wrong rendered page in ActionColumn

### ISSUE THREAD

**Issue by moysoft** [yiisoft/yii2#17392]
### What steps will reproduce the problem?

***  _code snippet in view\temuan\index.php_  ***

```php

        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update-temuan} {view-temuan} {delete}',
            'controller' => 'surat-tugas',
            'buttons' => [
                'update-temuan' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-edit"></span>', Url::toRoute(['surat-tugas/update', 'id' => $model->suratTugas->id]), ['title' => 'Update Temuan']);
                },
               
                'view-temuan' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::toRoute(['surat-tugas/view', 'id' => $model->suratTugas->id]), ['title' => 'View Temuan']);
                },
            ],
       ],
```

***   _code snippet in  controller\SuratTugasController.php_   ***

```php
public function actionView($id)
    {

        $model = $this->findModel($id);
        $providerSuratTugasAuditor = new \yii\data\ArrayDataProvider([
            'allModels' => $model->suratTugasAuditors,
        ]);
        $providerTemuan = new \yii\data\ArrayDataProvider([
            'allModels' => $model->temuans,
        ]);
        $providerRekomendasi = new \yii\data\ArrayDataProvider([
            'allModels' => $model->temuans,
        ]);

        $temuanID = $model->temuans;

        $searchModel = new TemuanSearch();
        // $dataProvider = $searchModel->search($id);
        $dataProvider = $searchModel->searchBySuratTugasID($id);

        $searchRekomendasiModel = new RekomendasiSearch();
        // $dataProvider = $searchModel->search($id);
        $dataProviderRekomendasi = $searchRekomendasiModel->searchBySuratTugasID($id);
        
        return $this->render('view', [
            'model' => $this->findModel($id),
            'providerSuratTugasAuditor' => $providerSuratTugasAuditor,
            'providerTemuan' => $providerTemuan,
            'dataProvider' => $dataProvider,
            'dataProviderRekomendasi' => $dataProviderRekomendasi,
        ]);
    }

```
### What is the expected result?

url routed to controller  : **surat-tugas/update**
rendered page :    **surat-tugas/update**

url routed to controller  : **surat-tugas/view**
rendered page :    **surat-tugas/view**

### What do you get instead?

url routed to controller  : **surat-tugas/update**
rendered page :    **surat-tugas/update**
(no issue for update)

url routed to controller  : **surat-tugas/view**
rendered page :    **temuan/index**
(an issue for rendered view, wrong page rendered)

but when the url refreshed with reload button in browser
rendered page :    **surat-tugas/view**
(rendered page correct)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.0.33
| Operating system | Windows 10

** Correct route and correct rendered page **

![image](https://user-images.githubusercontent.com/9723401/59972113-8257fd80-95b3-11e9-9c00-61ff67703c7d.png)

** Correct route but WRONG rendered page **

![image](https://user-images.githubusercontent.com/9723401/59972121-c77c2f80-95b3-11e9-97b4-66645ce9b5fa.png)

**  After Re-load page from browser, page rendered correctly **

![image](https://user-images.githubusercontent.com/9723401/59972142-26da3f80-95b4-11e9-93fa-a4a4c39a53e3.png)

**Comment by samdark** [comment]
The code you're displaying is in the `index` view but you're rendering `view` view.

**Comment by moysoft** [comment]
> The code you're displaying is in the `index` view but you're rendering `view` view.

Yes... the second image show URL  **surat-tugas/view?id=8**    it's generated from ActionColumn in **view\temuan\index.php**  and routed correctly but render the wrong view. The correct view for that URL is the third image. 

When I refreshed the second image it displays the correct view.

**Comment by samdark** [comment]
Then I don't get the problem how the code posted is connected to it.

**Comment by moysoft** [comment]
[SOLVED]   By adding , 'data-pjax' => '0' 

```
'view-temuan' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::toRoute(['surat-tugas/view', 'id' => $model->suratTugas->id]), ['title' => 'View Temuan', 'data-pjax' => '0']);
                },
```
The code snippet in Temuan\View\Index.php 

```
...
[
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update-temuan} {view-temuan} {delete}',
            'controller' => 'surat-tugas',
            'buttons' => [
                'update-temuan' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-edit"></span>', Url::toRoute(['surat-tugas/update', 'id' => $model->suratTugas->id]), ['title' => 'Update Temuan']);
                },
               
                'view-temuan' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::toRoute(['surat-tugas/view', 'id' => $model->suratTugas->id]), ['title' => 'View Temuan', 'data-pjax' => '0']);
                },
            ],
       ],
```

Reference from [this link](https://stackoverflow.com/questions/37130701/yii2-pjax-gridview-actioncolumn-issue-with-a-view-link/37131500#37131500)
