### ISSUE TITLE
asDecimal delimiter inconsistency

### ISSUE THREAD

**Issue by Zerebokep** [yiisoft/yii2#17391]
### What steps will reproduce the problem?

1.  Make sure php intl is installed
2. Set your app's language to a language which uses comma as decimal delimiter (e.g. German)
3.

`echo Yii::$app->formatter->asDecimal("0.026199999999999998", 4);`

result: 0.0262

`echo Yii::$app->formatter->asDecimal("0.026199999999999", 4);`

result: 0,0262

As you can see "asDecimal" gets inconsistent with the delimiter as soon the decimal places exceed 15.

### What is the expected result?

0,0262

### What do you get instead?

0.0262

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.21
| PHP version      |  7.1
| Operating system | Debian Stretch

**Comment by sdlins** [comment]
Maybe #17369 is related but I still had no time to go deep in the issue.

**Comment by bizley** [comment]
This is expected behavior since your first argument after normalization to float changes its value so it falls into `asDecimalStringFallback` which [clearly states](https://github.com/yiisoft/yii2/blob/2.0.21/framework/i18n/Formatter.php#L1095-L1097) it doesn't use `intl` and not explicitly set `decimalSeparator` becomes there a dot.

To get comma set formatter's `decimalSeparator` explicitly to `,`.

**Comment by Zerebokep** [comment]
Hm is there any reason behind this? Yii 2.0.15 did that very well. It feels a little bit strange to explicitly set the separators after defining the app's language (which should do the job anyway?).

**Comment by bizley** [comment]
See #14950

**Comment by Zerebokep** [comment]
Just in case someone has the same issue, add the following to a bootstrap component:

`
$numberFormatter = new \NumberFormatter($language, \NumberFormatter::DECIMAL);

            $app->formatter->decimalSeparator = $numberFormatter->getSymbol(\NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
            $app->formatter->thousandSeparator = $numberFormatter->getSymbol(\NumberFormatter::GROUPING_SEPARATOR_SYMBOL);
`

where $language is the locale string (e.g. de-DE).
