### ISSUE TITLE
Some three level routes not working with controllers in subdirectory prefix

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#17405]
The docs state [Controller IDs](https://www.yiiframework.com/doc/guide/2.0/en/structure-controllers#controller-ids) that one can namespace a controller with a prefix and place it in the corresponding dir, like:

    namespace admin/UserController;

Then, I define the following rules:

	'class' => 'yii\web\GroupUrlRule',
	'prefix' => 'admin/',
	'routePrefix' => 'admin/',
	'rules' => [
		'<controller:\w+>/<id:\d+>' => '<controller>/view',
		'<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
		'<controller:\w+>/<action:\w+>' => '<controller>/<action>',
	],

but some routes won't work. When I head to 

    /admin/user/view/1

I get a 404 page error.

However, if I head to 

    /admin/user/view?id=1

I get a success.

**Comment by alex-code** [comment]
Does it work without the forward slashes on the prefixes?

Not sure if you need the module name in the `modules` config too.

**Comment by santilin** [comment]
I have migrated my code to modules, so this issue doesn't apply any more to me. However, I'd like to have the docs mention this issue.
