### ISSUE TITLE
composer init install error!

### ISSUE THREAD

**Issue by lizhong43403** [yiisoft/yii2#17406]
### What steps will reproduce the problem?

composer install or update, 

> The "https://bower.herokuapp.com/packages/jquery" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
The "https://bower.herokuapp.com/packages/jquery" file could not be downloaded (HTTP/1.1 502 Bad Gateway)
https://bower.herokuapp.com/packages could not be fully loaded, package information was loaded from the local cache and may be out of date

>  Installing bower-asset/punycode (v1.3.2): Downloading (failed)       
The "https://api.github.com/repos/bestiejs/punycode.js/zipball/38c8d3131a82567bfef18da09f7f4db68c84f8a3" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

Access address https://bower.herokuapp.com/packages/jquery , the response result is 
> 此Bower版本已弃用。请更新它：npm install -g bower。新的注册地址是https://registry.bower.io

### What is the expected result?
Overall update time more than 10 minutes, expect to correct where the installation libraries change

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 
| Operating system |

**Comment by Thoulah** [comment]
Looks like something in your composer setup is very old. Did you try `composer selfupdate` and `composer global update`?
