### ISSUE TITLE
Yii2 not listed in awesome applications list

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#17407]
I have stumbled upon this list of applications:

  https://github.com/unicodeveloper/awesome-opensource-apps

and found that Yii2 is not listed. 

Wouldn't it be nice to get Yii2 apps listed there?

**Comment by samdark** [comment]
Sure. Would you like to handle it?

**Comment by sihar** [comment]
I make some application list from yiipowered.com using [this PR](https://github.com/unicodeveloper/awesome-opensource-apps/pull/72).

**Comment by samdark** [comment]
Seems it did not.
