### ISSUE TITLE
 PHP Warning – yii\base\ErrorException A non-numeric value encountered

### ISSUE THREAD

**Issue by tangrunhero** [yiisoft/yii2#17415]
https://github.com/yiisoft/yii2/blob/56f639358c0951b32036e91b642526b14cb97c4f/framework/base/Security.php#L741

**Comment by tangrunhero** [comment]
only happend when i passed a number into Yii::$app->getSecurity()->maskToken();
for example:
Yii::$app->getSecurity()->maskToken(234);

**Comment by samdark** [comment]
In the method signature is is stated that the parameter should be a string. Why int was passed?

**Comment by tangrunhero** [comment]
> In the method signature is is stated that the parameter should be a string. Why int was passed?
yeah,but it  hasn't throw this warning with php5.6 and when i updated php to 7.3.6 it just occured.

**Comment by tangrunhero** [comment]
> > In the method signature is is stated that the parameter should be a string. Why int was passed?
> > yeah,but it  hasn't throw this warning with php5.6 and when i updated php to 7.3.6 it just occured.
