### ISSUE TITLE
Except log target

### ISSUE THREAD

**Issue by s1lver** [yiisoft/yii2#17416]
### What steps will reproduce the problem?
I want to limit sending to mail type of errors. Setting the config:

```php
'log' => [
	'traceLevel' => YII_DEBUG ? 3 : 0,
	'targets' => [
		[
			'class' => 'yii\log\EmailTarget',
			'levels' => ['error', 'warning'],
			'except' => [
				'yii\web\HttpException:404',
                                'yii\web\HttpException:429',
				'yii\web\ForbiddenHttpException:403',
			],
			'mailer' => 'yii\swiftmailer\Mailer'
		]	
	]
]
```
### What is the expected result?
Excluded messages should not be sent

### What do you get instead?
All messages are coming

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.19
| PHP version      | 7.3.3
| Operating system |Linux

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/17107 ?

**Comment by s1lver** [comment]
It's very similar

**Comment by s1lver** [comment]
Now I'm not sure it's a mistake. The fact is that if the constant ``YII_DEBUG`` is set to **false**, the sending does not occur. But, at the same time, if you do not handle specific exceptions, it does not work very well. 
I think it's just worth pointing it out in the documentation.

**Comment by samdark** [comment]
6 Jun?

**Comment by s1lver** [comment]
> 6 Jun?
@samdark 
https://github.com/craftcms/cms/commit/34e1fef8ee10754014ab1bc986b682ef5f0fa4a9

**Comment by samdark** [comment]
That doesn't look like a fix...

**Comment by s1lver** [comment]
this is an example)

**Comment by OndrejVasicek** [comment]
This is my config and it works as supposed to

```php
              [
                    'enabled' => !YII_DEBUG,
                    'class' => 'yii\log\EmailTarget',
                    'levels' => ['error', 'warning'],
                    'except' => [
                        'yii\web\HttpException:404',
                        'yii\web\HttpException:403',
                        'yii\web\HttpException:401',
                        'yii\debug\Module*',
                    ],
                    'message' => [
                        'from' => $params['email.error'],
                        'to' => $params['email.support'],
                        'subject' => $params['name'] . ' - error',
                    ],
                ],
```

404,403,401 really don't go over the mail.
Another thing is I created a target for every of those Exceptions like this:
```php
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                    'categories' => ['yii\web\HttpException:404'],
                    'logFile' => '@app/runtime/logs/404.log',
                ],
```
Maybe this can be the difference.

**Comment by samdark** [comment]
> Maybe this can be the difference.

No.

**Comment by samdark** [comment]
Since it's verified that it works, closing the issue. Thanks for posting, @OndrejVasicek.
