### ISSUE TITLE
BaseUrl::toRoute add module id twice when there is a module

### ISSUE THREAD

**Issue by DavieLee** [yiisoft/yii2#17428]
### What steps will reproduce the problem?
1. Create a module (e.g. name: abc) and a controller (e.g. name: def) in the module, and create an action (e.g. name index) in the controller.
2. use Url::toRoute(['abc/def/index']) create url for the action and use UrlManager::createUrl(['abc/def/index']) do the same job. We will get different result. The first result will be /abc/abc/def/index
### What is the expected result?
All of them should be /abc/def/index
### What do you get instead?
/abc/abc/def/index

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      | 5.5.38
| Operating system |CentOS 6.5

**Comment by Thoulah** [comment]
> Note that unlike yii\helpers\Url::toRoute(), this method always treats the given route as an absolute route.

`Url::toRoute(['/abc/def/index'])` probably works fine?
