### ISSUE TITLE
Error message in ActiveForm not shown

### ISSUE THREAD

**Issue by mtc-toolbox** [yiisoft/yii2#17423]
### What steps will reproduce the problem?
1. Create CRUD from gii and after that add virtual property in ActiveRecord
`protected customerData = ['FirstName' => '', 'LastName' => ''];`

And add methods:
```php
/**
     * @return array
     */
    public function getCustomerData()
    {
        return $this->customerData;
    }

    /**
     * @param $data
     */
    public function setCustomerData($data)
    {
        $this->customerData = $data;
    }
```

2. Add custom validation in rules:

```php
[['CustomerData[FirstName]'], function ($attribute, $params) {
                $this->customerData['FirstName'] = $this->customerData['FirstName'] ?? '';
                if (!strlen($this->customerData['FirstName'])) {
                    $this->addError('CustomerData[FirstName]', 'Нет имени !!!');
                }
            }, 'skipOnEmpty' => false, 'skipOnError' => false],

```

3. Add field to ActiveForm

```php
echo $form->field($model, 'CustomerData[FirstName]')->textInput(['value' => $model->CustomerData['FirstName'] ?? '', 'id' => 'tourist-name', 'class' => 'form-control'])->label('Имя');
```

4. With empty field post data to server.

### What is the expected result?
Look danger string "Нет имени !!!"

### What do you get instead?

Do not see error text

### Additional info

I think the whole thing
```php
public static $attributeRegex = '/(^|.*\])([\w\.\+]+)(\[.*|$)/u';
```

 (yii\helpers\BaseHtml)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22
| PHP version       | 7.1.17
| Operating system | Windows 10

**Comment by mtc-toolbox** [comment]
I want to add.
Problem some more deep, now we can operate JSON fields as array and every element of JSON field must has rules for check it input.

For example, I want to check this field:

`echo $form->field($model, 'CustomerData[Emails][0][Email]')->textInput(['value' => $model->CustomerData['Emails'][0]['Email'] ?? '', 'id' => 'tourist-email-0-value', 'class' => 'form-control'])->label('E-mail');
`
Any customer has some email addresses or phones.

These are real structures with which I work.

**Comment by samdark** [comment]
Does adjusting regular expression to include `[` and `]` solve your issue?

**Comment by mtc-toolbox** [comment]
> Does adjusting regular expression to include `[` and `]` solve your issue?

Hi ! I think only part of task was done.

In this case
`
var_dump($model->errors);
echo $form->field($model, 'CustomerData[FirstName]')->textInput(['value' => $model->CustomerData['FirstName'] ?? '', 'id' => 'tourist-name', 'class' => 'form-control'])->label('Имя');`

I saw:

> array (size=2)
  'CustomerData[FirstName]' => 
    array (size=1)
      0 => string 'Нет имени !!!' (length=21)
  'CustomerData[Surname]' => 
    array (size=1)
      0 => string 'Нет фамилии !!!' (length=25)

> 

But in error section for input message not found again.

**Comment by mtc-toolbox** [comment]
> Does adjusting regular expression to include `[` and `]` solve your issue?

I make one sample.

I think, for mee good idea is:
`	$attributeRegex = '/(^|.*\])([\w\.\+]+)(\[.*|$)/u';
	if (preg_match($attributeRegex, 'CustomerData[Phones][0][Number]', $matches)) {
            echo $matches[2].$matches[3].PHP_EOL;
	var_dump($matches);

        } else {
		echo "Bad";
	}
	`
We not touch any regular expression and get full name for arrays

**Comment by samdark** [comment]
So changing $attributeRegex solves the issue completely?

**Comment by mtc-toolbox** [comment]
> So changing $attributeRegex solves the issue completely?

I think, yes.

But in my last example I wasn`t change expression, because it using in BaseHtml::getAttributeValue and fetch real array elements (it works fine).

I think, good idea will be change:

`return $matches[2];`
to
`return $matches[2].$matches[3];`

in BaseHtml::getAttributeName

**Comment by samdark** [comment]
Overall it sounds like the use case is quite specific and there are enough flexibility to achieve it in your case. Closing the issue and will wait till more similar issues are created.

Thanks for reporting anyway.
