### ISSUE TITLE
ActiveQuery is not preloading ->with(), if models are of different class, but the same Interface

### ISSUE THREAD

**Issue by sankaest** [yiisoft/yii2#17429]
I have business model, what was made according to Samdark article: "Single table inheritance" 
(yii2-cookbook/book/ar-single-table-inheritance.md ).

Car [car_table](id | name | type)
|- SportCar
|- HeavyCar

Now, every car can have their own fields with own table
Car (id | name | type)
|- SportCar
-- | CarFields [sport_car_fields] (car_id | top_speed)
|- HeavyCar
-- | CarFields [heavy_car_fields] (car_id | weight)

Classes, what inherit from Car class have relations like:
SportCar:

    public function getCarFields() {
        return $this->hasOne(SportCarFields::class, ['car_id' => 'id']);
    }

    public function getTitle() {
        return $this->name . '  ' . $this->carFields->top_speed;
    }

HeavyCar:

    public function getCarFields() {
        return $this->hasOne(HeavyCarFields::class, ['car_id' => 'id']);
    }

    public function getTitle() {
        return $this->name . '  ' . $this->carFields->weight;
    }

Now, let's have list of cars via /index:
If we have been NOT preloaded related models via ->with('carFields'), there is no problem and in the table $model->title will work (as $model->carFields preloaded one by one).

ISSUE:
But if we would like to have all fields preloaded ->with('carFields'), the latter car fields will be NULL.

The reason is that during AQ->populate()
function $this->findWith($this->with, $models); is called. 
And during this function only first model is used ($primaryModel = reset($models);)

Therefore CarFields of HeavyCar will be allways NULL, as there is no records of heavy car in sport_car_fields table.

SOLVING THE PROBLEM
I successfully solved the problem by making little modification in AQ->populate():

    public function populate($rows)
    {
        ...
        
        if (!empty($this->with)) {

            $groupedModels = [];
            foreach ($models as $model) {
                $groupedModels[get_class($model)][] = $model;
            }
        
            foreach ($groupedModels as $groupedModel) {
                $this->findWith($this->with, $groupedModel);
            }
        }
        ...
    }

Now, if there is only one model (99% of cases), it preloads as usually.
In case of suggested "Single table inheritance" it uses this new modification and also preload carFields grouping models by their class.

So in GridView I can use $model->title as corresponding carFields are preloaded.

**Comment by samdark** [comment]
Sounds OK. Please do a pull request with the above modification so it runs against Yii unit tests to see if it passes.
