### ISSUE TITLE
when preflight OPTIONS request,  it is Intercepted with HttpHeaderAuth

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#17421]
### What steps will reproduce the problem?

![image](https://user-images.githubusercontent.com/1888094/60969101-495cae80-a351-11e9-8287-dc5fd0356ec3.png)

![image](https://user-images.githubusercontent.com/1888094/60969027-161a1f80-a351-11e9-9569-4b4606c83a5b.png)

![image](https://user-images.githubusercontent.com/1888094/60969047-23370e80-a351-11e9-8dc5-98c9a4ae20e2.png)

![image](https://user-images.githubusercontent.com/1888094/60969188-73ae6c00-a351-11e9-9671-aaefe65ff024.png)

### What is the expected result?
when preflight OPTIONS request,  it is Intercepted with HttpHeaderAuth

### What do you get instead?
online waiting

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22
| PHP version      |  php-7.6.3-nts
| Operating system | win10 1903

**Comment by huaiguoguo** [comment]
![image](https://user-images.githubusercontent.com/1888094/60982194-3dc9b180-a36a-11e9-8d2e-e9c1fdb5c11e.png)

![image](https://user-images.githubusercontent.com/1888094/60982254-5934bc80-a36a-11e9-990d-9924219397fe.png)

i am use it,  it's work,   

I suggest adding this judgment to the official code.

**Comment by huaiguoguo** [comment]
这种方法不好，上面的代码块有待修正，如果用户本身就不开启option请求，上面的代码块的做法是让所有option请求都通过

**Comment by huaiguoguo** [comment]
This method is not good, the above code block needs to be amended, if the user does not open the option request itself, the above code block's approach is to let all the option requests pass through.

**Comment by samdark** [comment]
You should be able to solve it by moving `cors` up above `authenticator` in behaviors.
