### ISSUE TITLE
User::loginRequired with subdomain

### ISSUE THREAD

**Issue by alex-code** [yiisoft/yii2#17424]
I've got a `Module` with some `UrlRule`'s to work with a subdomain.

e.g.
```
site.com     -> DefaultController
sub.site.com -> Module/DefaultController
```
When going to `sub.site.com` it will redirect to `site.com/login` which works fine.

The issue is the call to [`User::loginRequired()`](https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L437) only sets the relative part of the url so after logging in you get redirected back to `site.com` and not `sub.site.com`

This could be fixed by changing this line [User.php#L446](https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L446) to use the absolute url, not sure if this would cause any BC issues.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22

**Comment by samdark** [comment]
Should not cause any issues. Redirecting not back but to main domain does not make any sense.

**Comment by samdark** [comment]
@alex-code do you want to do a pull request fixing it?

**Comment by alex-code** [comment]
Yeh, I'll do a PR.
Switching from `$request->getUrl()` to `$request->getAbsoluteUrl()` should be all it needs.
