### ISSUE TITLE
FileValidator and dynamic maxFiles

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/yii2#17427]
### What steps will reproduce the problem?

1. Add validation rule to model:
`[['galleryUpload'], 'image', 'maxFiles' => (2 - $this->getGalleryFiles()->count())]`
2. Create new model with one image.
3. Update that model and try to upload second image.

### What is the expected result?

Upload and model save is success.

### What do you get instead?

Got error message `Please upload a file.`

### Additional info
Abstract: I want to have ActiveRecord model with maximum two images uploaded (and related in db).
So if model have 0 related files - can upload max 2, if model has 1 related/uploaded/saved in db file - can upload max 1...

Problem is (probably) in https://github.com/yiisoft/yii2/blob/master/framework/validators/FileValidator.php#L209: `if ($this->maxFiles != 1 || $this->minFiles > 1) {` it's **not working with multiple file upload widget** when maxFiles == 1 and minFile is empty (file upload isn't required).

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22
| PHP version      | 7.2.x
| Operating system | KDE Neon

**Comment by alex-code** [comment]
Could this be because setting `maxFiles` to `0` means unlimited?

Maybe something like this would work?
```php
public function rules()
{
  $rules = [
    //...
  ];

  if (($count = $this->getGalleryFiles()->count()) < 2) {
    $rule = [['galleryUpload'], 'image'];
    if ($count === 0) {
      $rule['maxFiles'] = 2;
    }
    $rules[] = $rule;
  }

  return $rules;
}
```

**Comment by tomaszkane** [comment]
Yes, I wrote something similar, but then must change my view layer - add some: `IF max-upload-file == 1 THEN use-single-file-upload-widget.
It's work, but it's not perfect.

**Comment by alex-code** [comment]
Are you using a widget for the file selector or `<input type="file" />`

**Comment by tomaszkane** [comment]
Kartik FileImput - it's not a bit deal to change parameter there (one IF), but this case should be handled by model/rules layer? Or not?

**Comment by alex-code** [comment]
If you're using a widget it would be up to the widget to handle a use case like this by checking the rules for the attribute.

The framework wouldn't be able to handle it as it wouldn't know how each widget works to set any options.

**Comment by samdark** [comment]
It was originally meant to use single file upload widget for the case only a single file is required. That's what condition suggests. I think it should be fixed in the widget itself.
