### ISSUE TITLE
Placeholders in the email column and name column are reversed, on the website https://www.yiiframework.com

### ISSUE THREAD

**Issue by wlnoor** [yiisoft/yii2#17439]
I found the irregularities on the https://www.yiiframework.com website to be exact on the contact form page, it looks like the placeholders in the email column and name are reversed.

Sorry if I wrote it on the issue
![image](https://user-images.githubusercontent.com/28283735/61346407-ca043900-a882-11e9-871a-4e7cd1b91c75.png)

**Comment by hirenbhut93** [comment]
Resolved by https://github.com/yiisoft-contrib/yiiframework.com/pull/452
