### ISSUE TITLE
Migration templates do not work with namespace naming convention

### ISSUE THREAD

**Issue by Isitar** [yiisoft/yii2#17437]
### What steps will reproduce the problem?
`php yii migrate/create 'common\migrations\CreateNewsTable' --fields="hello:int"`
### What is the expected result?
a migration with the create_table template
### What do you get instead?
an empty migration

### Additional info
it doesnt work because the preg_match does not work for this naming convention (line 392 onwards in MigrateController)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22
| PHP version      | 7.3 
| Operating system | Windows

**Comment by bizley** [comment]
I'm on it.

**Comment by Isitar** [comment]
@bizley do not forget the template files itself.
