### ISSUE TITLE
Release 2.0.23 offers yii-advanced-app-2.0.22.tgz (filename correct?)

### ISSUE THREAD

**Issue by jschleus** [yiisoft/yii2#17440]
Just a small observation:

Under https://github.com/yiisoft/yii2/releases I found the new release `2.0.23`. But at least for me unexpectedly the according file `yii-advanced-app-2.0.22.tgz` has the previous version in its file name (while `yii-basic-app-2.0.23.tgz` the new current version).

Additionally the member file `advanced/vendor/yiisoft/yii2/CHANGELOG.md` of `yii-advanced-app-2.0.22.tgz` contains change informations about version `2.0.23`

**Comment by samdark** [comment]
Thank you for noticing it. Fixed.
