### ISSUE TITLE
Comment on a column in a migration is at the wrong place, causing a syntax error

### ISSUE THREAD

**Issue by Manu311** [yiisoft/yii2#17449]
### What steps will reproduce the problem?
Creating a table-column with a "check" and a "comment".
Either by putting it inside of the initial creation or by adding it afterwards.
This is in a default yii-migration-class:
```php
$this->createTable('something', [ 'test' => "longtext NULL DEFAULT NULL COMMENT 'this works' CHECK(json_valid(`test`))" ]);
$this->addCommentOnColumn('something', 'test', 'this breaks');
$this->createTable('something2', [ 'test' => $this->json()->comment('this breaks') ]);
//Created Type: longtext NULL DEFAULT NULL CHECK(json_valid(`test`)) COMMENT 'this breaks'
```

### What is the expected result?
The both not working commands should create MySQL similar to the working example included above.
In the end the column should have the check and the comment.

### What do you get instead?
A Syntax error from MariaDb (and probably MySql if I used that). According to the MySql-reference, comment should be way earlier than check_constraint_definition:
https://dev.mysql.com/doc/refman/8.0/en/create-table.html

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| PHP version      | 7.3
| Operating system | Linux

**Comment by samdark** [comment]
Do you want to help by working on a pull request?

**Comment by choken** [comment]
I tried to make an pull request, but the test build script failed due to some expected  mysql-5.5 depency.
https://github.com/yiisoft/yii2/pull/17454

**Comment by samdark** [comment]
> Btw, sorry for the double commit. Should I merge the two commits to one?

No, that's fine.

**Comment by Manu311** [comment]
Sadly this doesn't work.
For some reason comments (in mysql) are added via additional alter-commands after table-creation.

I've fixed this problem locally and will create a Pull-Request that work's for me.

**Comment by YokiToki** [comment]
Also `CHECK` statement goes after `AFTER` statement
```php
$this->addColumn('table', 'column', $this->json()->null()->after('previous_column'));
```

**Comment by mtangoo** [comment]
Just stumbled upon extension that sets comment on migration and then Query tries to do it MySQL way. In PostgreSQL the comment is attached later in different statement.

Instead of 
```CREATE TABLE "oauth2_client" (
	"id" serial NOT NULL PRIMARY KEY,
	"some_column" int8 COMMENT "Some comment"
    ....
)```

it is
```CREATE TABLE "oauth2_client" (
	"id" serial NOT NULL PRIMARY KEY,
	"some_column" int8
    ....
)

COMMENT ON COLUMN some_column IS "Some comment";
````

**Comment by mtangoo** [comment]
is there a way to disable comments globally in migration?

**Comment by bizley** [comment]
There is no easy way. Looks like comments for PostgreSQL should be done separately. Could you be able to prepare a PR?

**Comment by mtangoo** [comment]
I wish I could do it. DAO and its intertwined components are a beast.
I will try to have a look at it though and see if I can try to fix it.

Do you know where the comments are actually parsed? I tried to quickly find it and I could not!

**Comment by bizley** [comment]
Right now basic `comment()` is implemented [here](https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchemaBuilder.php#L202). The trick is to extract that call to a separate SQL statement.

**Comment by mtangoo** [comment]
I checked that one but actually it was just assigning it. I wanted to get where it actually processes the comments to create the Query. Am sure there is where I can do something. but could not find. That might be because am unfamiliar on how the whole database access object works under the hood
