### ISSUE TITLE
Problem with ActiveRecord

### ISSUE THREAD

**Issue by kongoon** [yiisoft/yii2#17457]
When select data from SQL Server in record has ' or ) in the end of string but it's not show in view.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version      |  7.2
| Operating system | Windows, IIS

**Comment by kongoon** [comment]
Database string
![Image of string store in SQL Server](https://i.imgur.com/eRo8QOa.jpg)

When display in view
![Image of display view](https://i.imgur.com/d66fuXb.jpg)

**Comment by samdark** [comment]
@kongoon can you try downgrading several Yii versions to check if the issue is still there?

**Comment by samdark** [comment]
Fixed by @alexkart. Will be part of the next release.
