### ISSUE TITLE
updateAll with inner join

### ISSUE THREAD

**Issue by srsalute** [yiisoft/yii2#17455]
exists updateAll with inner join?
I need update a group of datas but some of the condition are relational with another tables.

**Comment by rhythmk** [comment]
yii version: 2.0.14.2

I want to exce SQL :
`
update ce  a  INNER JOIN  bi b  on a.project_id=b.project_id  and b.deleted=0 
 set a.ce =b.ce  ,a.noi=b.noi
`
but , i don`t find a way to user    query of yii  (left join  or inner join) .
can  you  help  me .

thanks .

**Comment by samdark** [comment]
@rhythmk at the forum yes: https://forum.yiiframework.com/
