### ISSUE TITLE
logger not working if it's set from config

### ISSUE THREAD

**Issue by ahmadasjad** [yiisoft/yii2#17469]
### What steps will reproduce the problem?
Inside any controller, put this:
```php
public function actionIndex()
{
        Yii::info('Hello World');
        return $this->render('index');
}
```

inside the config:
```php
'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'logger' => Yii::createObject('yii\log\Logger'),
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'info'],
                ],
            ],
],
```

### What is the expected result?
Log inside the `runtime/logs/app.log`

### What do you get instead?
Nothing in `runtime/logs/app.log`

### Additional info
It'll work if  `'logger' => Yii::createObject('yii\log\Logger'),` is removed

I have found location from where it's misbehaving.
**Class** : `yii\log\Logger` 
```php
public function __construct($config = [])
    {
        // ensure logger gets set before any other config option
        if (isset($config['logger'])) {
            $this->setLogger($config['logger']);
            unset($config['logger']);
        }
        // connect logger and dispatcher
        $this->getLogger();

        parent::__construct($config);
    }

```
and
```php
/**
     * Gets the connected logger.
     * If not set, [[\Yii::getLogger()]] will be used.
     * @property Logger the logger. If not set, [[\Yii::getLogger()]] will be used.
     * @return Logger the logger.
     */
    public function getLogger()
    {
        if ($this->_logger === null) {
            $this->setLogger(Yii::getLogger());
        }

        return $this->_logger;
    }

    /**
     * Sets the connected logger.
     * @param Logger|string|array $value the logger to be used. This can either be a logger instance
     * or a configuration that will be used to create one using [[Yii::createObject()]].
     */
    public function setLogger($value)
    {
        if (is_string($value) || is_array($value)) {
            $value = Yii::createObject($value);
        }
        $this->_logger = $value;
        $this->_logger->dispatcher = $this;
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version      | 7.3.7-1+ubuntu16.04.1+deb.sury.org+1
| Operating system | ubuntu16.04.1+deb.sury.org+1

**Comment by samdark** [comment]
It's by design. If you are passing pre-configred logger instance, no configuration is applied.

**Comment by ahmadasjad** [comment]
> It's by design. If you are passing pre-configred logger instance, no configuration is applied.

This sounds good. But it's not working even if I pass non-instance configuration like:
`'logger' => ['class' => 'yii\log\Logger'],`

**Comment by samdark** [comment]
What's your use case for replacing standard logger?

**Comment by ahmadasjad** [comment]
I want to add my custom Logger class inherited from `yii\log\Logger`.  My project is a hybrid of yii1 and yii2, and I want to implement my own custom logic for handling situation from both version. BTW, I haven't implemented it yet. **It's not working without my custom code even with the core class (`yii\log\Logger`)**

**Comment by vitalyzhakov** [comment]
Hello!

Reproducing for me in Yii 2.0.40.
PHP 7.3.26.
