### ISSUE TITLE
PageCache generating too many 'additional' files

### ISSUE THREAD

**Issue by jhon100** [yiisoft/yii2#17465]
I'm using PageCache on a website with approximately 10,000 pages and I received from the hosting server (shared) a warning that I was with 'high inodes usage' and that my account could be suspended.

Looking at the server I saw that in the cache folder in each subfolder there are the files containing the page content but there are also many 'additional' files containing only strings like 

> a: 2: {i: 0; i: 5; i: 1; N;} 

In a folder, for example, there are 149 files, 22 with page html and 127 with these 'additional' files. There are 256 folders in the cache folder, so this turns out to be a big problem.
![image](https://user-images.githubusercontent.com/16785000/61948876-6dd69e80-af7f-11e9-9c98-1ddb89b55de5.png)

I do not understand the need of these additional files because at the time a page cache is generated, only the page content is saved in a file. **Apparently these other files only appear in the next day** (considering a clean cache folder), so I don't think they are necessary for the cache to work properly.

The only cache setting I am using:

![image](https://user-images.githubusercontent.com/16785000/61947936-dcfec380-af7c-11e9-9911-fce16e8b23a8.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version      | 7.1.17
| Operating system |Linux

**Comment by samdark** [comment]
These smaller caches contain arrays such as:

```php
[
    0 => 5,
    1 => null,
]
```

PageCache is not likely to generate these especially considering the fact that they appear next day.

**Comment by jhon100** [comment]
@samdark You're right, I had forgotten that in my RateLimiter implementation I was saving some  information in cache. Now I have set a cronjob to delete these expired caches daily. Thank you.
