### ISSUE TITLE
Messages Translations default source * not working

### ISSUE THREAD

**Issue by rkoblev** [yiisoft/yii2#17464]
Yii I18N component overrides default source, but should respect it.
I can see that I18N::init() adds default source for "yii" and "app". I guess, it should not set defaults if configuration has "\*" as category (or any wildcard matching "yii" and "app", for example "y\*", not only "yii\*")

### What steps will reproduce the problem?
Add configuration
```php
'i18n' => [
            'translations' => [
                '*' => [
                    'class' => 'yii\i18n\DbMessageSource',
                    ...
            ]
```

### What is the expected result?
Expected that ALL translations will use DB source

### What do you get instead?
Instead "yii" and "app" categories will use yii\i18n\PhpMessageSource

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Yes, that is a special case that was added like that on purpose so `*` doesn't break default framework translations but, at the same time, there is ability to direct these into your own source by using `yii*`. Same about `app*`.

We will try to avoid such selective defaults in Yii 3 but won't change behavior for Yii 2.
