### ISSUE TITLE
Grid checkbox selection (css) not works correctly

### ISSUE THREAD

**Issue by devaptas** [yiisoft/yii2#17466]
yiisoft/yii2: 2.0.23
kartik-v/yii2-grid: v3.3.2 

![ezgif-4-f65372e5ca09](https://user-images.githubusercontent.com/36535740/61954209-b5185b80-af8e-11e9-93f2-d3313a78135b.gif)

PS: The problem happens on first render, after filter or order grid selection works correctly.

**Comment by samdark** [comment]
Seems to be kartik-v/yii2-grid specific. Please report there.

**Comment by devaptas** [comment]
@samdark I think problem was generated after this https://github.com/yiisoft/yii2/pull/17373/files/23e4f2b07898f58bb1f86c10009c7b339bdaef0b

**Comment by samdark** [comment]
Could be. Likely kartik-v widget should be adjusted.
