### ISSUE TITLE
SQL malformed in junction table

### ISSUE THREAD

**Issue by alejosv** [yiisoft/yii2#17462]
I have a relationship with two tables called workers and clients. The junction table called `workers_clients` and is formed with this fields: `worker_id` and `client_id`

The junctions work perfectly until I do click in action delete. This is my delete action:

    public function actionDelete($id)
        {
            $this->findModel($id)->delete();
            $client = $this->_getClient();
            
            $searchModel = new WorkersSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            
            return $this->renderPartial('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'client' => $client
            ]);
        }

### What steps will reproduce the problem?
Create a junction table and run delete action from index view using renderAjax from Gridview like this:

        <?php Pjax::begin([
            'id' => 'workers',
            'enablePushState' => false
        ]); ?>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    'dni',
                    'code',
                    'first_name',
                    'last_name',
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header'=>'Acción', 
                        'headerOptions' => ['width' => '110'],
                        'template' => '{edit} {delete}',
                        'buttons' => [
                            'edit' => function($url, $model, $key) {
                                return Html::a('<i class="fa fa-edit"></i>', $url, [
                                    'class' => 'btn btn-primary', 
                                    'title' => Yii::t('app', 'Editar trabajador'),
                                ]);
                            },
                            'delete' => function($url, $model, $key) {
                                if ($model->monitors) {
                                    $link = '';
                                } else {
                                    $link = Html::a('<i class="fa fa-trash-o"></i>', $url, [
                                        'class' => 'btn btn-danger', 
                                        'data-pjax' => 'w0',
                                        'data-method' => 'post',
                                        'title' => Yii::t('app', 'Eliminar trabajador'),
                                    ]);
                                }
                                return $link;
                            },

                        ]
                    ],
                ],
            ]); ?>

        <?php Pjax::end(); ?>

### What is the expected result?
Delete worker and render the Gridview

### What do you get instead?
The following error:

    Exception (Integrity constraint violation) 'yii\db\IntegrityException' with message 
    'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
    The SQL being executed was: SELECT COUNT(*) FROM `workers` LEFT JOIN 
    `workers_clients` ON `workers`.`id` = `workers_clients`.`worker_id` LEFT JOIN `clients` ON 
    `workers_clients`.`client_id` = `clients`.`id` WHERE (`id` LIKE '%c3cc98d6-1b0f-4209-9167-247dd6d6b25e%') AND (`clients`.`id`='50b14fd3-11cc-4027-aaf8-466f0bb0fc79')' 
    
    in /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/db/Schema.php:674

    Stack trace:
    #0 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...')
    #1 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT COUNT(*)...')
    #2 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
    #3 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/db/Query.php(463): yii\db\Command->queryScalar()
    #4 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/db/ActiveQuery.php(352): yii\db\Query->queryScalar('COUNT(*)', Object(yii\db\Connection))
    #5 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/db/Query.php(347): yii\db\ActiveQuery->queryScalar('COUNT(*)', Object(yii\db\Connection))
    #6 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/data/ActiveDataProvider.php(169): yii\db\Query->count('*', NULL)
    #7 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/data/BaseDataProvider.php(169): yii\data\ActiveDataProvider->prepareTotalCount()
    #8 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/data/ActiveDataProvider.php(106): yii\data\BaseDataProvider->getTotalCount()
    #9 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/data/BaseDataProvider.php(101): yii\data\ActiveDataProvider->prepareModels()
    #10 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/data/BaseDataProvider.php(114): yii\data\BaseDataProvider->prepare()
    #11 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/data/BaseDataProvider.php(155): yii\data\BaseDataProvider->getModels()
    #12 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/widgets/BaseListView.php(190): yii\data\BaseDataProvider->getCount()
    #13 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/widgets/BaseListView.php(158): yii\widgets\BaseListView->renderSummary()
    #14 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/grid/GridView.php(326): yii\widgets\BaseListView->renderSection('{summary}')
    #15 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\grid\GridView->renderSection('{summary}')
    #16 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)
    #17 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/widgets/BaseListView.php(138): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...')
    #18 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/grid/GridView.php(301): yii\widgets\BaseListView->run()
    #19 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/Widget.php(140): yii\grid\GridView->run()
    #20 /lxcshared/php/yii2/ngdosev3.git/views/workers/index.php(94): yii\base\Widget::widget(Array)
    #21 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/View.php(348): require('/lxcshared/php/...')
    #22 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/lxcshared/php/...', Array)
    #23 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/lxcshared/php/...', Array, Object(app\controllers\WorkersController))
    #24 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/Controller.php(415): yii\base\View->render('index', Array, Object(app\controllers\WorkersController))
    #25 /lxcshared/php/yii2/ngdosev3.git/controllers/WorkersController.php(388): yii\base\Controller->renderPartial('index', Array)
    #26 [internal function]: app\controllers\WorkersController->actionDelete('ec5892a6-5bda-4...')
    #27 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
    #28 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
    #29 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('delete', Array)
    #30 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('workers/delete', Array)
    #31 /lxcshared/php/yii2/ngdosev3.git/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
    #32 /lxcshared/php/yii2/ngdosev3.git/web/index.php(12): yii\base\Application->run()
    #33 {main}

### Additional info
I see the SQL omitted the name table in the statement:

    SELECT COUNT(*) FROM `workers` LEFT JOIN `workers_clients` ON `workers`.`id` = 
    `workers_clients`.`worker_id` LEFT JOIN `clients` ON `workers_clients`.`client_id` = 
    `clients`.`id` WHERE (`id` LIKE '%c3cc98d6-1b0f-4209-9167-247dd6d6b25e%') AND 
    (`clients`.`id`='50b14fd3-11cc-4027-aaf8-466f0bb0fc79')

Instead of using:

    `id` LIKE '% ...

should be:

    `workers`.`id` LIKE '% ...

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version      | 7.3.7
| Operating system | Debian 9.9

**Comment by samdark** [comment]
Can you provide WorkersSearch code?

**Comment by alejosv** [comment]
@samdark this is my WorkerSearch

```
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Workers;
use components\helpers\AccessHelper;

/**
 * WorkersSearch represents the model behind the search form of `app\models\Workers`.
 */
class WorkersSearch extends Workers
{
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'dni', 'code', 'first_name', 'last_name', 'gender', 'dob'], 'safe'],
            [['enabled', 'job_id', 'practice_id', 'created_at', 'updated_at'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        
        $session = Yii::$app->session;
        $clientId = $session->get('clientWorkersId');

        $query = Workers::find();

        $query ->joinWith([
            'clients' => function(\yii\db\ActiveQuery $query) use ($clientId) {
                $query->andWhere([
                    'clients.id' => $clientId
                ], false);
            }
        ]);

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'dob' => $this->dob,
            'enabled' => $this->enabled,
            'job_id' => $this->job_id,
            'practice_id' => $this->practice_id,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ]);

        $query->andFilterWhere(['like', 'id', $this->id])
            ->andFilterWhere(['like', 'dni', $this->dni])
            ->andFilterWhere(['like', 'code', $this->code])
            ->andFilterWhere(['like', 'first_name', $this->first_name])
            ->andFilterWhere(['like', 'last_name', $this->last_name])
            ->andFilterWhere(['like', 'gender', $this->gender]);

        return $dataProvider;
    }
}
```

**Comment by samdark** [comment]
You're doing join with `clients`:

```php
 $query ->joinWith([...
```

but not specifying which `id` is used in the filter:

```php
$query->andFilterWhere(['like', 'id', $this->id])
```

There is no way to know which `id` was meant so it's not adding anything. That's expected behavior.
