### ISSUE TITLE
[PHP 7.4 News] PDO support username & password specified in DSN

### ISSUE THREAD

**Issue by charescape** [yiisoft/yii2#17472]
https://github.com/php/php-src/commit/a7881df281f74e13cf360fd3624ef849ce747e33#diff-7748eb3bfdd3bf962553f6f9f2723c45

> The username and password can now be specified as part of the PDO DSN for
    the mysql, mssql, sybase, dblib, firebird and oci drivers. Previously this
    was only supported by the pgsql driver. If a username/password is specified
    both in the constructor and the DSN, the constructor takes precedence.

```php
new PDO("mysql:host=xxx;port=xxx;dbname=xxx;user=xxx;password=xxx");
```

**Comment by samdark** [comment]
Doesn't it currently work?

**Comment by charescape** [comment]
No, it works. It's just a new feature. Maybe one day yii2 can use it. 👍

**Comment by samdark** [comment]
I think you can use it even now. Yii supports DSN...
