### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by vitovtnet** [yiisoft/yii2#17473]
### What steps will reproduce the problem?
Query class

```
class OrderQuery extends ActiveQuery
{
 public function beforeOpeningDate(\DateTime $openingDate)
    {
        $this->andFilterWhere(['<=', new Expression('operation_date') , $openingDate->format('Y-m-d')]);
        return $this;
    }
}

```

`Order::find()->beforeOpeningDate(new \DateTime())->all();
`

And result is

```
yii\base\ErrorException
Illegal offset type in isset or empty
```

If I use query builder andFilterWhere without Expression -  everything is working fine

`
$this->andFilterWhere(['<=', operation_date , $openingDate->format('Y-m-d')]);
`
### What is the expected result?

QueryBuilde understanding  Expression 

### Additional info

Trace
```

     * @param string $name column name
     * @return string the properly quoted column name
     */
    public function quoteColumnName($name)
    {
        if (isset($this->_quotedColumnNames[$name])) {
            return $this->_quotedColumnNames[$name];
        }
        return $this->_quotedColumnNames[$name] = $this->getSchema()->quoteColumnName($name);
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version      |  7.2
| Operating system | Ubuntu 18.04

**Comment by alexkart** [comment]
@vitovtnet is it allowed to pass `Expression` as `operand1` in operator format condition?
And it's not clear what you want to achieve using this?
As you said `$this->andFilterWhere(['<=', operation_date , $openingDate->format('Y-m-d')]);` works correct and it is correct condition.

**Comment by vitovtnet** [comment]
@alexkart Expression help to use SQL in RAW format without any quotas.

`$this->andFilterWhere(['<=', operation_date , $openingDate->format('Y-m-d')]);`

SQL: ...WHERE `operation_date`<='2019-05-05'

But if I want to use, for example DATE_FORMAT fucntion or DAYS function or any other SQL function I will write my query like

`$this->andFilterWhere(['<=', new Expression("DATE_FORMAT('peation_date', '....')" , $openingDate->format('Y-m-d')]);`

**Comment by vitovtnet** [comment]
Also, I checked all mo code which written 05.04.2018 (more than a year ago), I'm everywhere used a construction like

```
 if (!empty($this->endDate)) {
            $endDate = new \DateTime($this->endDate);

            $query->andFilterWhere([
                '<=',
                new Expression('operation_booking_date'),
                $endDate->format('Y-m-d') ]);
        }
```
And it's worked

**Comment by srnden** [comment]
Same problem in LikeConditionBuilder, InConditionBuilder.

I redefined yii\db\Connection::quoteColumnName() method in my project. Maybe, is it a bad idea?

```php
public function quoteColumnName($name)
{
   if ($name instanceof ExpressionInterface) {
        return (string)$name;
   }

   return parent::quoteColumnName($name);
}
```

**Comment by samdark** [comment]
@srnden please report as separate issue with more details. Thanks.
