### ISSUE TITLE
$model - getPrimaryKey()/getLastInsertId() returns wrong value when tables has triggers

### ISSUE THREAD

**Issue by csrbrito** [yiisoft/yii2#17474]
### What steps will reproduce the problem?

```php
$model = new Model();
$model->name = 'model name';
$model->save();

/*
this should return the id of newly inserted row to Model table,
But when table has a trigger that inserts into another table,
returns the id of row inserted to that audit/historic table instead
*/
echo $model->getPrimaryKey();
echo $model->Id;
echo $model->getDb()->getLastInsertId();
```

### What is the expected result?

We expect is a newly assigned ID according to AutoIncrement PK 

### What do you get instead?

Returns the id of the row inserted to the audit/historic table.

### Additional info
We tried directly on sql server like this:

```sql
INSERT INTO table ([Name]) VALUES ('Test');
SELECT SCOPE_IDENTITY() as ScopeID, @@IDENTITY as IdentID;
```

The newly row created, ScopeID returns the correct ID and IdentID the ID of row inserted into Log table.

We checked the method lastInsertId  from PDO ( class yii2\db\mssql\PDO ), and SCOPE_IDENTITY() returns null, so maybe the connection is not the same?! so returns value from @@IDENTITY instead.

```php
   /**
     * Returns value of the last inserted ID.
     * @param string|null $sequence the sequence name. Defaults to null.
     * @return int last inserted ID value.
     */
    public function lastInsertId($sequence = null)
    {
        return $this->query('SELECT CAST(COALESCE(SCOPE_IDENTITY(), @@IDENTITY) AS bigint)')->fetchColumn();
    }
 ```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | Windows 10/Server 2012
| Sql Server | Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 

config/db.php

```php
$db = [
	'class' => 'yii\db\Connection',
	'dsn' => 'sqlsrv:Server=localhost\SQLEXPRESS;Database=DTEMP',
	
	'username' => 'usr',
	'password' => 'pwd',
	'charset' => 'utf8',
	
	'enableSchemaCache' => true,
	'schemaCacheDuration' => 12 * (60 * 60), // 12 * 1 hour
	'schemaCache' => 'schemaCache',
];
```
config/web.php

```php
$db = require __DIR__ . '/db.php';
...
$config = [
...
	'components' => [
		'db' => $db,
	...
```

**Comment by alex-code** [comment]
Could `IDENT_CURRENT` work?
https://docs.microsoft.com/en-us/sql/t-sql/functions/ident-current-transact-sql?view=sql-server-2017 although it could return an id from a different session.

**Comment by Jafarili** [comment]
I've tested it with MySQL and all three codes resulted the same and correct output :+1:

**Comment by csrbrito** [comment]
This is a issue with connection through MSSQL, not MySQL ( I dont know if happens with others than MSSQL).

IDENT_CURRENT its for global sessions, maybe for getLastInsertId() only, not suitable for getPrimaryKey() or $model->id ( this last method can't be ever)!

And in my test case, it works, so with yii2 must work like it should be.

How can i check if two queries has the same connections at yii2 active record? some variable has the connection # stream ?!

**Comment by alex-code** [comment]
https://aoeex.com/phile/working-around-scope-identity-not-working-with-pdo
Looks like you'd need to do the insert and select in the same query.

**Comment by csrbrito** [comment]
> 
> 
> https://aoeex.com/phile/working-around-scope-identity-not-working-with-pdo
> Looks like you'd need to do the insert and select in the same query.

This approach is not the best and has many problems because needs custom code for each table, and has a performance issue.

Yii2 is not using the PDO::lastInsertId, instead implemented its own way with this SELECT ISNULL approach.

https://aoeex.com/phile/working-around-scope-identity-not-working-with-pdo
https://docs.microsoft.com/en-us/sql/connect/php/pdo-lastinsertid?view=sql-server-2017

**Comment by alex-code** [comment]
Looking back through the code this has been in since Yii1.
Maybe the driver back then didn't support `lastInsertId` so it had to be queried.

If you comment out the `lastInsertId` method in `yii2\db\mssql\PDO` so it uses the built in method does it work?

**Comment by samdark** [comment]
> Maybe the driver back then didn't support lastInsertId so it had to be queried.

That was likely the case.

**Comment by csrbrito** [comment]
> 
> 
> Looking back through the code this has been in since Yii1.
> Maybe the driver back then didn't support `lastInsertId` so it had to be queried.
> 
> If you comment out the `lastInsertId` method in `yii2\db\mssql\PDO` so it uses the built in method does it work?

I tested with that method commented out and the same output.

**Comment by alex-code** [comment]
Only glanced over it but could `OUTPUT` work?
https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-2017
