### ISSUE TITLE
Unique validation exception if alias is used

### ISSUE THREAD

**Issue by WhiteLabelCoders** [yiisoft/yii2#17475]
When I use unique validator and I use query preparation to set an alias, exception appears.

### What steps will reproduce the problem?

Model:

- Rule:

```php
[['metal_id'], 'unique'],
```

- Find:
```php
public static function find(): ActiveQuery
{
        return new BaseQuery(static::class);
}
```

BaseQuery:

```php
 public function prepare($builder): Query
{
        $this->setAlias('pp');

        // ...

        return parent::prepare($builder);
}
```

### What is the expected result?

validation should work. No matter if with alias or without.

### What do you get instead?

Exception and headache...

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'product_part.id' in 'field list'
The SQL being executed was: SELECT `product_part`.`id` FROM `product_part` `pp` WHERE (`product_part`.`metal_id`='3') AND (NOT (`pp`.`product_id` IS NULL)) LIMIT 2
```

It is related to https://github.com/yiisoft/yii2/issues/14028, as I see it was fixed, but for me it is not working.

EDIT:
Checked on Yii 2.0.15 and 2.0.23.

**Comment by WhiteLabelCoders** [comment]
Any updates?

**Comment by samdark** [comment]
Not yet.

**Comment by rob006** [comment]
Why you're hardcoding alias in `prepare()` instead of `init()`?

**Comment by WhiteLabelCoders** [comment]
@rob006 Hmmm... good idea. It helped.

**Comment by samdark** [comment]
@WhiteLabelCoders do you still have an issue to be solved?

**Comment by WhiteLabelCoders** [comment]
@samdark I think that now it is ok.
