### ISSUE TITLE
Revert #17477

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#17485]
#17477 should be reverted.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/14a71984349c017ac06d4218dac8d0b4a30545bd

**Comment by rob006** [comment]
@samdark This needs changelog line.

**Comment by samdark** [comment]
Right!

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/2e0389e9ad3a8bb95144af3d8d21e0f827ed844f

**Comment by vitalyzhakov** [comment]
Добрый день!

Подскажите причину, почему откачено?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/17477
