### ISSUE TITLE
Issue in database session management, creating multiple rows for same session id in session table

### ISSUE THREAD

**Issue by badelal2007** [yiisoft/yii2#17487]
### What steps will reproduce the problem?
Just enable captcha at login page. showing captcha invalid. captch is not being refresh etc.
### What is the expected result?
It's creating a separate entry in session table for each request against same session id, this should not be happen (there should be one entry in session table against one session id)

### Note-
When I replaced two files (yii\web\DbSession and yii\web\MultiFieldSession) from old version (Yii2.0.12) then it is working fine.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.24
| PHP version      | 7.1.23
| Operating system | Linux

**Comment by raulrebane** [comment]
I have the same issue with latest Yii2 (2.0.39.3). Every click on the UI results in 12 new records in session table.

**Comment by samdark** [comment]
@raulrebane Is it reproducible with a clean basic application and minimal amount of changes?

**Comment by raulrebane** [comment]
please close for now. This takes time and I am currently busy. Maybe after month or so
