### ISSUE TITLE
Load balancer resetting the user identity while using switchIdentity

### ISSUE THREAD

**Issue by aavrug** [yiisoft/yii2#17483]
### What steps will reproduce the problem?
Create two different modules and using switch identity to access action of particular module. 
Then enable load balancer for the application. 
E:g:
 For module 1 (admin module inside vendor/mdm/yii2)
 Accessing identity like (Yii::$app->user->identity)
Setting Identity in module.php of this module
```php
        parent::init();
        Yii::$app->set('user', [
           'class' => 'yii\web\User',
           'identityClass' => 'mdm\admin\models\AdminUser',
           'enableAutoLogin' => true,
           'loginUrl' => ['appr/default/login'],
           'identityCookie' => ['name' => 'editor', 'httpOnly' => true],
           'idParam' => 'username', //this is important !
           'authTimeout' => 30
       ]);
```
For module 2 (/modules/mymodule)
Accessing identity like (Yii::$app->adminuser->identity)

In web.php (For switch identity)
```php
'adminuser' => [
            'class' => 'yii\web\User',
            'identityClass' => 'mdm\admin\models\AdminUser',
            'enableAutoLogin' => false,
            'idParam' => 'username', //this is important !
        ],
```
### What is the expected result?
Should be able to use action from one module to another.
### What do you get instead?
User identity getting reset.
i.e Yii::$app->adminuser->identity is empty when trying to access **mymodule** action

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  7.2
| Operating system | ubuntu 14.0

**Comment by samdark** [comment]
In order to fix the issue we should reproduce it first without any third party modules (since these may have bugs themselves). Is it possible to reproduce starting with basic application template?

**Comment by aavrug** [comment]
We are not getting this issue with any third party module. With Yii2 itself this issue is there might be the option is available but we are not getting in the Docs. The configurations of user is provided in the top description, additional code I am providing here so you can refer what exactly we are trying to fetch.

In one of the out side controller I am trying to use
The both lines are working fine if from the same server address where the user loggedin 
```
1. Yii::$app->user->identity
2. Yii::$app->adminuser->identity
```

If server remote address is getting changed because of load balancer then the first one is setting fine and the second one getting reset(returning blank/empty value).

**Comment by samdark** [comment]
You are using custom identity class `'identityClass' => 'mdm\admin\models\AdminUser',`. Isn't that from mdmsoft/yii2-admin?

How do you store sessions? Is it Redis / memcached?
