### ISSUE TITLE
Trying to get property 'driverName' of non-object

### ISSUE THREAD

**Issue by BaBL86** [yiisoft/yii2#17486]
### What steps will reproduce the problem?
```php
$query = MssqlModel::findBySql($sql);
foreach ($query->batch()) {
// some code...
}
```

### What is the expected result?
Iterate all MssqlModel objects.

### What do you get instead?
Exception after first iteration:

```
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property 'driverName' of non-object'

in /app/vendor/yiisoft/yii2/db/BatchQueryResult.php:168
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.24
| PHP version      | 7.4
| Operating system | Debian GNU/Linux

### Additional information
In `/vendor/yiisoft/yii2/db/Query.php:187`: `$db` is null by default and `Query` has no `$db` param to set correct value.
```php
    public function batch($batchSize = 100, $db = null)
    {
        return Yii::createObject([
            'class' => BatchQueryResult::className(),
            'query' => $this,
            'batchSize' => $batchSize,
            'db' => $db,
            'each' => false,
        ]);
    }
```

This is workaround:
```php
foreach ($query->batch(100, MssqlModel::getDb()) {
// some code
}
 ```

**Comment by BaBL86** [comment]
There is a new issue after upgrade from 2.0.20

**Comment by alexkart** [comment]
Well, that’s not a new issue, because previously you would get “no more rows” exception in this case, see https://github.com/yiisoft/yii2/issues/10023, but yes, it should be fix.

**Comment by BaBL86** [comment]
No, that another Exception, that breaks our project.

Before I catch PDOException from connection, now this is an ErrorException from php null object
