### ISSUE TITLE
Prefix for foreign keys

### ISSUE THREAD

**Issue by Isitar** [yiisoft/yii2#17498]
### What steps will reproduce the problem?
```php yii mgirate/create create_junction_table_for_xx_and_yy_table```
### What is the expected result?
a migration with prefixed tablenames and no prefixes for foreign keys
### What do you get instead?
a migration with prefixed tablenames and prefixes for foreign keys

### Additional info

this is more of a discussion point but prefixing on foreign keys does not make a lot of sense.
if you use prefixes on tablenames that's totally fine and useful but on foreign keys and indexes it is strange (at least to me). to be consistent the fieldnames should be prefixed too if the foreign-keys are prefixed. (for example with the command `php yii migrate/create create_some_table --fields=foo` it should result in a field in style `'{{%foo}}'`)

so in my opinion the prefixing should not be done.
to solve it, just remove the call to `$this->generateTableName` following line.
https://github.com/yiisoft/yii2/blob/69cf9de56b1df8456c8f2af26268537435e5d96c/framework/console/controllers/MigrateController.php#L493
and 
https://github.com/yiisoft/yii2/blob/69cf9de56b1df8456c8f2af26268537435e5d96c/framework/console/controllers/MigrateController.php#L494

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.
| PHP version      | 7.3
| Operating system | fedora

**Comment by rob006** [comment]
Are you sure that you can have multiple foreign keys with the same name in single database?

**Comment by rob006** [comment]
Related PR: https://github.com/yiisoft/yii2/pull/17422
