### ISSUE TITLE
ActiveRecord column mapping

### ISSUE THREAD

**Issue by Jafarili** [yiisoft/yii2#17492]
### What steps will reproduce the problem?
When the table columns have to be different from model attributes.
for example, in the table, we have `carId` column but in the model we need `vehicleId`.
there is no way to map `carId` to `vehicleId`
also, column mapping is needed for security reasons, for example, naming the columns meaningless (like randomly generated strings) and mapping it to a meaningful name in the application.

### What is the expected result?
an array of mapping to map for example `carId` to `vehicleId` inside the model class.
like this:
`public $columnMap = [
    'carId' => 'vehicleId'
];`

### What do you get instead?
Currently, column mapping is not supported in Yii

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.25-dev
| PHP version      | 7.3
| Operating system | Debian

**Comment by alex-code** [comment]
Could you not use getters/setters or a custom behaviour for this?

```php
class MyAR extends ActiveRecord
{
  public function getVehicleId()
  {
    return $this->carId;
  }

  public function setVehicleId($value)
  {
    $this->carId = $value;
  }
}
```

**Comment by Jafarili** [comment]
But this solution is not working when we want to cast the model object to array (for example in rest API)
Also on where condition like this:
`Vehicle::find()->where(['vehicleId', $id])`
Also, it's not omitting the carId in the object, it only makes an alias of carId in the object

**Comment by rob006** [comment]
This was discussed several times in the past and it was rejected due additional complexity: https://github.com/yiisoft/yii2/issues/9409
