### ISSUE TITLE
Codeception problems after run tests with success

### ISSUE THREAD

**Issue by prsolucoes** [yiisoft/yii2#17505]
# What steps will reproduce the problem?

After run my project tests i got error.

https://github.com/prsolucoes/yii2-app-advanced/tree/mega-update

This is the log on travis (the same locally):
https://travis-ci.com/prsolucoes/yii2-app-advanced/builds/122708900#L5424

### What is the expected result?

Only show green message and exit since all tests passed.

### What do you get instead?

```

Time: 15.97 seconds, Memory: 34.00MB

OK (25 tests, 61 assertions)
PHP Fatal error:  Uncaught Error: Call to a member function getRequest() on null in /usr/share/nginx/html/vendor/yiisoft/yii2-debug/src/panels/RequestPanel.php:59
Stack trace:
#0 /usr/share/nginx/html/vendor/yiisoft/yii2-debug/src/LogTarget.php(61): yii\debug\panels\RequestPanel->save()
#1 /usr/share/nginx/html/vendor/yiisoft/yii2-debug/src/LogTarget.php(136): yii\debug\LogTarget->export()
#2 /usr/share/nginx/html/vendor/yiisoft/yii2/log/Dispatcher.php(190): yii\debug\LogTarget->collect(Array, true)
#3 /usr/share/nginx/html/vendor/yiisoft/yii2/log/Logger.php(177): yii\log\Dispatcher->dispatch(Array, true)
#4 [internal function]: yii\log\Logger->flush(true)
#5 {main}
  thrown in /usr/share/nginx/html/vendor/yiisoft/yii2-debug/src/panels/RequestPanel.php on line 59
make: *** [test] Error 255
```

![image](https://user-images.githubusercontent.com/395096/62832648-25b6ad80-bc08-11e9-913d-e784cb85205e.png)

Thanks for any help.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | latest?
| PHP version     7.2 | 
| Operating system Linux |

**Comment by samdark** [comment]
Try turning off debug toolbar in test environment.
