### ISSUE TITLE
Incorrect guide for replacing UrlRule class

### ISSUE THREAD

**Issue by My6UoT9** [yiisoft/yii2#17509]
### What steps will reproduce the problem?
Following the guide to replace the `UrlRule` with a own class, 
It states in [guide](https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing#creating-rules):
```
'rules' => [
    // ...other rules...
    [
        'class' => 'app\components\CarUrlRule',
        // ...configure other properties...
    ],
]
```
So I did the following, I copied `yii\web\UrlRule`, add the missing namespaces in my copy. And tried to use it. 
`'class' => 'common\helpers\UrlRule',`
[UrlRule.zip](https://github.com/yiisoft/yii2/files/3506257/UrlRule.zip) (just adding my class for completeness, but its really just a copy with some extra namespace.)

### What is the expected result?
That url resolving works just like with the original class.

### What do you get instead?
It cannot resolve the urls anymore.

### Additional info
Specificying the class instead like this: `'class' => \common\helpers\UrlRule::class,` does work, it finds the Urls an everything. I also noticed while debugging - it won't even enter the `init()` method when the class is given as string. But it will still enter the `createUrl()`

| Q                | A

| ---------------- | ---
| Yii version      | 2.0.25
| PHP version      |  7.2
| Operating system | Win 10

**Comment by samdark** [comment]
That means there was an error in the class namespace somewhere because `\common\helpers\UrlRule::class` essentially generates a string.
