### ISSUE TITLE
URL issue with Security::generateRandomString

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii2#17500]
I'm using `Security::generateRandomString` to generate a token wich is used as a query parameter. In case when the last symbol of the token is `-` it's ignored by number of messangers, e.g. Skype

For example my URL is: `https://www.website.com?secret=abc123-`

Than `-` at the very end of the string will be defined as a plain text, not part of the URL. So when user clicks the link he will be redirected to `https://www.website.com?secret=abc123` which leads to the wrong `sercret` parameter

https://github.com/yiisoft/yii2/blob/efe8d48f156e9e76994a2322cdd0fb4d68bd8f6a/framework/base/Security.php#L559

**Comment by samdark** [comment]
That's the problem of Skype. I'd suggest replacing `-` with something Skype doesn't ignore.
