### ISSUE TITLE
Yii is returning 404 for two words actions and making dashes fail

### ISSUE THREAD

**Issue by jralison** [yiisoft/yii2#17507]
Yii is refusing dash character (`-`) in action ids, but it is accepting backslashes (`\`) on the other hand.

I think this is due to a possible mistake in the pattern to validate an id in method `Controller::createAction()`, line 228, as follows:

https://github.com/yiisoft/yii2/blob/efe8d48f156e9e76994a2322cdd0fb4d68bd8f6a/framework/base/Controller.php#L227-L229

The double backslashes in the pattern are matching characters in the range from `\` (93) to `_` (95), which includes `\`, `]`, `^` and `_` instead of only `-` and `_`, which I suppose was the initial intention. 

Can someone please confirm me if that is a bug or am I lacking any information?

**Comment by samdark** [comment]
Looks suspicious.

**Comment by My6UoT9** [comment]
Looks like a bug,
The current regex:
https://regex101.com/r/UHNuhL/1
https://regex101.com/r/UHNuhL/2

\, ], ^,  cannot be used, as they would not give a valid action method.

What I dont understand - this seems to have worked, or why look for dashes?
https://github.com/yiisoft/yii2/issues/1296

**Comment by samdark** [comment]
@jralison would you please help to reproduce the issue?

1. What controller/action names do you use?
2. What URL you are trying to access it with?

**Comment by jralison** [comment]
I wasn't looking for dashes, actually. But I thought it was strange to accept backslashes and refuse dashes in a url.

In my use case I have a module `AuthModule` with an `AuthController` and I needed an action `ssoAttributes` to respond to route `<apiUrl>/auth/ssoAttributes`.

My `UrlManager` is configured as:

```php
// ...
return [
    'class' => UrlManager::class,
    'enablePrettyUrl' => true,
    'enableStrictParsing' => true,
    'showScriptName' => false,
    'rules' => [
        // ...
        ['class' => WebUrlRule::class,
         'pattern' => 'auth/<action:\w+>',
         'route' => 'auth/auth/<action>'],
        // ...
    ],
];
```

My `AuthController` is as so:

```php

namespace Qstione\PlanoEnsino\Modules\Auth\Controllers;

// use ...

class AuthController extends BaseController
{
    // ...
    public function actionSsoAttributes() {
        return 'is it working?';
    }
    // ...
}
```

And, when I try to reach `<apiUrl>/auth/ssoController`, I got:

```json
{
	"name": "Not Found",
	"message": "Página não encontrada.",
	"code": 0,
	"status": 404,
	"type": "yii\\web\\NotFoundHttpException",
	"previous": {
		"name": "Invalid Route",
		"message": "Unable to resolve the request: auth/auth/ssoAttributes",
		"code": 0,
		"type": "yii\\base\\InvalidRouteException"
	}
}
```

As you can see in the previous key, my route is being treated as an Invalid Route.

When debugging I found out that the exception is thrown after the test I point out in the opening of this issue as the `createAction` method is returning `null`.

**Comment by samdark** [comment]
The action IDs are converted to dashed lowercase (that is by design that IDs are dashed-lowercase) so your URL is `<apiUrl>/auth/sso-attributes`. In order to have it as `ssoAttributes` you have to specify non-automatic rule such as:

```php
'auth/ssoAttributes' => 'auth/auth/sso-attributes'
```

**Comment by jralison** [comment]
@samdark I have tried this, also. Sorry I forgot to mention.

When I try to access `<apiUrl>/auth/sso-attributes`, I get a standard 404 error.

But in this case the code doesn't even reach the `Controller::createAction()` method and fails still in the `UrlRule::parseRequest()` method. So I thought the dash wasn't suppose to compose the url and assumed `ssoAttributes` would be the correct endpoint as it was in Yii 1.1. Seems I assumed wrong. ~(up to now)~ 😅

The test it returns false is here:
https://github.com/yiisoft/yii2/blob/efe8d48f156e9e76994a2322cdd0fb4d68bd8f6a/framework/web/UrlRule.php#L412-L414

**Comment by lubosdz** [comment]
I think `preg_match('/^[a-z0-9\\-_]+$/', $id)` should not contain double backslash at all - because:

* double backslash = explicit character `\`, means URL like `my\url` would be accepted (wrong).
* single backslash = escaping, would allow following character translated as REGEX modifier, e.g. `\-` would allow characters range up to the `-` character (wrong)

My guess is that by removing it would not break anything for first option because writing action name like `function actionMy\Action(){...}` is not possible and for the second option it would only fix unwanted buggy behaviour.

**Comment by My6UoT9** [comment]
The regex as it is really makes no sense:
This is valid: 
`asd\]^_asd`
This is not :
`asd\]^_-asd`
