### ISSUE TITLE
FileValidator  mimeType not working

### ISSUE THREAD

**Issue by nazakar** [yiisoft/yii2#17512]
### What steps will reproduce the problem?
In my model i have
  [['path'], 'file',  'skipOnEmpty' => true, 'extensions'=>'jpg, gif, png ,doc, txt, pdf ,docx ,rar ,zip ,xls ,xlsx ,rtf',
            'maxFiles' => 50,
           'checkExtensionByMimeType'=>true,

         'mimeTypes'=>'image/jpeg,image/png,
       ,application/msword doc,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/pdf,text/plain',
### What is the expected result?
If I rename some .php file to .doc or .docx  or .png then
file uploaded without error message. 

### What do you get instead?
I think file should not upload. How to solve problem?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.25
| PHP version     7.2 | 
| Operating system linux|

**Comment by alex-code** [comment]
What is the result of this on your server?
```php
echo \yii\helpers\FileHelper::getMimeType(__FILE__);
```

**Comment by nazakar** [comment]
text/x-php

**Comment by alex-code** [comment]
Can you try it on the file you're uploading?
```php
echo \yii\helpers\FileHelper::getMimeType('my-renamed-php-file.docx');
```

**Comment by nazakar** [comment]
docx return same text/x-php

**Comment by alex-code** [comment]
Can you show some of your action?
Have you set the file attribute to an instance of `UploadedFile`?
https://www.yiiframework.com/doc/guide/2.0/en/input-file-upload#wiring-up

**Comment by nazakar** [comment]
I handle manually in upload action, but the problem is that file validator not work correctly. This is Yii2 bug

**Comment by alex-code** [comment]
It's hard to diagnose without seeing your code.

**Comment by nazakar** [comment]
As you can see " samdark added this to the 2.0.26 " - I will  wait for 2.0.26

**Comment by alex-code** [comment]
> As you can see " samdark added this to the 2.0.26 " - I will wait for 2.0.26

It also has the label `status:to be verified` so if we can't reproduce we can't fix.

**Comment by samdark** [comment]
As @alex-code said, we first have to reproduce it and yes, we cannot fix it if it cannot be reproduced.

**Comment by nazakar** [comment]
My controller action is 
public function actionUpl(){

  $model=Pacienti::find()->where('pacient_userid=:pacient_userid',[':pacient_userid'=> Yii::$app->user->getId()])->one();

$query= Files1::find()->where('pac_id=:pac_id',[':pac_id'=>$model->id]);
$dataProvider = new ActiveDataProvider([
  'query' => $query,
  'sort' => [
 'defaultOrder' => [
 'created_at' => SORT_DESC,
] ],
]);
$files1 = new Files1();

 if ($files1->load(Yii::$app->request->post()) ) {

  $files = UploadedFile::getInstances($files1, 'path');
  $directory = Yii::getAlias('@webroot'). '/backend/files/';
  if ($files) {
    foreach ($files  as $file) {
      $mime = \yii\helpers\FileHelper::getMimeType($file->tempName);

        $files2 = new Files1();
        $fileName =$file->baseName.'_'. time(). '.' . $file->extension;

        $fileorig = $file->baseName . '.' .$file->extension;
        $filePath = $directory . $fileName;

      $url= Yii::getAlias('@web') .'/backend/files/'. $fileName;
      if ($file->saveAs($filePath)  ) {
         $files2->orig_name = $fileorig ;
         $files2->path = $url ;
         $files2->n_id = 0 ;
         $files2->pac_id=$model->id;
         $files2->fname=$fileName;
         $files2->creator_id=Yii::$app->user->identity->id;
         $files2->controler_name = Yii::$app->controller->id;
         $files2->save();
      }


  }
}

}

return $this->render('_files', [

   'dataProvider'=>$dataProvider,
   'model'=>$model,
   'files' => $files1,
]);
}
If i check mime type inside controller like
 if  ($mime=="image/jpeg" || $mime=="image/png"
        || $mime=='application/msword doc'
        || $mime=='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        || $mime=='application/vnd.ms-excel'
        || $mime=='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        || $mime=='application/pdf'
        || $mime=='text/plain'
       ) {....
}
renamed php file not uploading
I think that 'mimeType' validator works like 'extensions' validator?

**Comment by nazakar** [comment]
I found the problem 
'mimeTypes' in model validation must be array
'mimeTypes'=>['image/jpeg, image/png, application/msword doc, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/pdf, text/plain'],
Not like I declare as string 'mimeTypes'=>'image/jpeg, image/png, application/msword doc, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/pdf, text/plain',

**Comment by alex-code** [comment]
You've missed some bits.
The `UploadedFile::getInstances` needs to be assigned to the model and to validate you need to call `validate`.

```php
$files1 = new Files1();
if ($files1->load(Yii::$app->request->post()) ) {
  $files1->path = UploadedFile::getInstances($files1, 'path');
  if ($files1->validate()) {
    // ...
  }
}
```
https://www.yiiframework.com/doc/guide/2.0/en/input-file-upload#uploading-multiple-files

**Comment by nazakar** [comment]
I call   if ($files1->validate()) { - result is the same validates only extensions not mimetype

**Comment by alex-code** [comment]
Did you set?
```php
$files1->path = UploadedFile::getInstances($files1, 'path');
```

**Comment by nazakar** [comment]
yes - the same

**Comment by alex-code** [comment]
Can you show your updated action.
If you can wrap it with code format tags too it makes it easier to read.
e.g.

\```php
// My PHP code
\```

**Comment by samdark** [comment]
@alex-code added formatting.

**Comment by samdark** [comment]
I've re-checked validator code and did a simple application with your config exactly. As @alex-code said, you are missing some bits in handling code but the framework itself is alright. You can verify it via:

```php
$mimeType = FileHelper::getMimeType('path\to\test.docx', null, false);
var_dump($mimeType);
$extensionsByMimeType = FileHelper::getExtensionsByMimeType($mimeType);
var_dump($extensionsByMimeType);
$result = in_array('docx', $extensionsByMimeType, true);
var_dump($result);
```

For me it gives:

```
string(10) "text/x-php" array(0) { } bool(false)
```

Which means there's no allowed extensions allowed for mime type `text/x-php` and validation returns `false`.
