### ISSUE TITLE
Make yii2/rbac/DbManager more flexible

### ISSUE THREAD

**Issue by raraworks** [yiisoft/yii2#17522]
### What steps will reproduce the problem?
Adding additional info to either of the auth item tables.
### What is the expected result?
Being able to customize queries that are used in DbManager for certain [ManagerInterface](https://github.com/yiisoft/yii2/blob/master/framework/rbac/ManagerInterface.php) methods, or maybe adding property for additional constraints for retrieving assignments (i.e. https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L708), in a form of https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#where()-detail

The default implemetation has nothing wrong with it, but i just need to add extra constraints.
In my case, i need to share rbac info between multiple apps, so having a particular rbac assignment would work in only one of the systems but not all.
### What do you get instead?
Extension of class and overwriting methods used for querying rbac data (in this case assignments) from database. And [some methods](https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L1050) are private for DbManager

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.25
| PHP version      | 7.3.8-1+ubuntu18.04.1+deb.sury.org+1
| Operating system | Linux  4.15.0-58-generic Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64

**Comment by samdark** [comment]
Is making that method protected enough?

**Comment by raraworks** [comment]
> Is making that method protected enough?

For me it is fine!
