### ISSUE TITLE
yiiunit\framework\mutex\RetryAcquireTraitTest::testRetryAcquire test fail by ci.appveyor.com

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii2#17533]
### What steps will reproduce the problem?

https://ci.appveyor.com/project/samdark/yii2/builds/26985116#L161

### What is the expected result?

accept 49.97

### What do you get instead?

```bash
1) yiiunit\framework\mutex\RetryAcquireTraitTest::testRetryAcquire
Failed asserting that 49.96800422668457 is equal to 50 or is greater than 50.
```

### Additional info

Maybe the float vs integer is the problem.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.26-dev
| PHP version      | ?
| Operating system | windows

**Comment by samdark** [comment]
That is an indication that it fails with certain conditions. Any idea on what conditions these may be?

**Comment by kamarton** [comment]
At first glance, it cannot be less than 50.0, unless it is time traveler.

**Comment by samdark** [comment]
That is the issue with concurrency issues. They are very similar to time travelers.

**Comment by kamarton** [comment]
There is a bigger difference:
```
1) yiiunit\framework\mutex\RetryAcquireTraitTest::testRetryAcquire
Failed asserting that 48.61307144165039 is equal to 50 or is greater than 50.
C:\projects\yii2\tests\framework\mutex\RetryAcquireTraitTest.php:45
```

**Comment by samdark** [comment]
I don't think it is correct to ignore it in tests. I've reproduced it. Trying to understand what actually happens.

**Comment by samdark** [comment]
OMG, seems windows `usleep()` precision is awful: https://ci.appveyor.com/project/samdark/yii2/builds/27850232. It finished 2ms earlier than specified.

**Comment by samdark** [comment]
Aha. That is normal on Windows: https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep?redirectedfrom=MSDN

> If dwMilliseconds is less than the resolution of the system clock, the thread may sleep for less than the specified length of time.
