### ISSUE TITLE
Codecept run exit code 1 even for successful tests

### ISSUE THREAD

**Issue by erkib** [yiisoft/yii2#17536]
### What steps will reproduce the problem?
run tests: vendor/bin/codecept run

### What is the expected result?
When tests pass, run command should return with exit code 0 and when some fail, with exit code other than 0.

### What do you get instead?
Time: 4.81 seconds, Memory: 24.00MB

OK (21 tests, 76 assertions)

THE ERROR HANDLER HAS CHANGED!

Remaining indirect deprecation notices (4)

  3x: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.
    3x in Application::run from Codeception

  1x: The "Codeception\Event\TestEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.
    1x in Application::run from Codeception

make: *** [tests] Error 1

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.3.5
| Operating system | macOS X 10.14.6

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-basic/issues/180

**Comment by samdark** [comment]
We were not able to reproduce it both under Windows and Ubuntu. Do you have any specific details that matter to share?

**Comment by erkib** [comment]
it seems that this issue is resolved in latest Yii 2.0.x release, which also uses newer codecept library.

**Comment by katoba86** [comment]
Had the same problem
`codecept run `
No errors but in deployment (Bitbucket pipeline and Github Actions) => Deployment Failed

My solution
`codecept run && echo Success || echo Failed`

Don't know why.. but it works
