### ISSUE TITLE
StringValidator and skipOnEmpty

### ISSUE THREAD

**Issue by RSol** [yiisoft/yii2#17542]
StringValidator don't use "skipOnEmpty" for validate proccess

For this rule
`[['attribute'],'string', 'min' => 10, 'max' => 20, 'skipOnEmpty' => true],`

Empty string add error [https://github.com/yiisoft/yii2/blob/master/framework/validators/StringValidator.php#L117](https://github.com/yiisoft/yii2/blob/master/framework/validators/StringValidator.php#L117)

`$this->addError($model, $attribute, $this->tooShort, ['min' => $this->min]);` 

To fix this on [https://github.com/yiisoft/yii2/blob/master/framework/validators/StringValidator.php#L115](https://github.com/yiisoft/yii2/blob/master/framework/validators/StringValidator.php#L115) put code:

`if ($length === 0 && $this->skipOnEmpty) {
            return null;
        }`

and the same on [https://github.com/yiisoft/yii2/blob/master/framework/validators/StringValidator.php#L137](https://github.com/yiisoft/yii2/blob/master/framework/validators/StringValidator.php#L137)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.25

**Comment by alex-code** [comment]
Are you sure your attribute is empty?
What do you get for a `var_dump($myModel->myAttribute)` after any loading?

This is `true` for me.
```php
$model = new \yii\base\DynamicModel(['key' => '']);
$model->addRule(['key'], 'string', ['min' => 10, 'max' => 20, 'skipOnEmpty' => true]);
var_dump($model->validate());
```

**Comment by My6UoT9** [comment]
fyi `skipOnEmpty`  happens in the parent class,
https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L253

**Comment by RSol** [comment]
My error - in my model were data from DB
