### ISSUE TITLE
sqlite and migrate/fresh problem

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#17546]
When using my extension [yii2-sqlite3-full-support](https://github.com/santilin/yii2-sqlite3-full-support) and a sqlite database on my projects, when I run `./yii migrate/fresh`, the command drops all the foreign keys of all the tables. 
As the `yii\db\sqlite\Schema::findConstraints` method doesn't retrieve the foreign key name, the array of foreign keys is indexed by number. When `yii\db\sqlite\QueryBuilder::dropForeignKey($name, $tableName)` of my extension is called, instead of a foreign key name, it receives a number.

I can handle that and delete the foreign key by number, but the problem is that when there is more than one foreign key in a table, the `MigrateController\truncateDatabase`method calls the QueryBuilder with a sequence of keys and my method gets the keys in order: 0, 1, 2, ....

The fix could be very simple, in: `yii2\db\sqlite\Schema::findConstraints` we can just reverse the array of keys so that I receive the keys in reverse order: 2, 1, 0 and in this way the `migrate/fresh` command works fine:
```
    protected function findConstraints($table)
    {
        $sql = 'PRAGMA foreign_key_list(' . $this->quoteSimpleTableName($table->name) . ')';
        $keys = $this->db->createCommand($sql)->queryAll();
        foreach (array_reverse($keys) as $key) {
```

**Comment by samdark** [comment]
Are these keys returned ordered at all?

**Comment by samdark** [comment]
I mean, is there a guarantee that reverse order will execute in all possible cases?

**Comment by santilin** [comment]
> I mean, is there a guarantee that reverse order will execute in all possible cases?

The function `db\sqlite\Schema::findConstraints` uses sqlite3 [`PRAGMA foreign_key_list`](https://sqlite.org/pragma.html#pragma_foreign_key_list), which doesn't state in the documentation the meaning of the fields returned. However, I have tried it and the first column is an incrementing integer number: 0, 1, 2, ...

**Comment by samdark** [comment]
Then I'd not rely for it being returned in any meaningful order.

**Comment by santilin** [comment]
That's why I'm proposing to return it in that order that works for me.

**Comment by samdark** [comment]
But there is no guarantee that original order is backwards to what  you need. It's not stated anywhere and can change any moment. You should not rely on it like that.

**Comment by nicovicz** [comment]
how about delete *.sqlite file and recreate again?

**Comment by samdark** [comment]
@nicovicz that's an interesting idea :)
