### ISSUE TITLE
getDefaultRoleInstances

### ISSUE THREAD

**Issue by phrakon** [yiisoft/yii2#17553]
### What steps will reproduce the problem?

I use yii\rbac\DbManager to store auth data. I don't want to assign any newly created user to default user role. I prefer to use defaultRoles property like 

`'defaultRoles' => ['user']`

### What is the expected result?

`Yii::$app->authManager->getRolesByUser($userId)` returns additional information about default role like description and so on...

### What do you get instead?

I've got Role object with only name property

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.24
| PHP version      | 5.4.45
| Operating system | WINDOWS 8

**Comment by phrakon** [comment]
Don't you think it should be like this

    public function getDefaultRoleInstances()
    {
        $result = [];
        $query = (new Query())->from($this->itemTable)->andWhere([
            'name' => $this->getDefaultRoles(),
            'type' => Item::TYPE_ROLE,
        ]);
        foreach ($query->all() as $item) {
            $result[$item['name']] = new Role([
                'name' => $item['name'],
                'type' => $item['type'],
                'description' => $item['description'],
                'ruleName' => $item['rule_name'],
                'data' => $item['data'],
                'createdAt' => $item['created_at'],
                'updatedAt' => $item['updated_at'],
            ]);
        }
        return $result;
    }

**Comment by samdark** [comment]
We cannot change the output since it will break backwards compatibility. In order to get the info you can use `getRole()` method.
