### ISSUE TITLE
viaTable hit 2 database queries instead of doing join

### ISSUE THREAD

**Issue by greenex** [yiisoft/yii2#17558]
I have this relation on my model
```
 public function getCheckListItems()
    {
       return $this->hasMany(\common\models\ChecklistItem::className(), ['id' => 'checklist_item_id'])
        ->viaTable(AssignedChecklist::tableName(), ['assigned_id' => 'id'],
            function($query) {
                $query->andWhere(['assigned_type' => self::className()]);
            });

    }
```

and when I call 

$company->checkListItems

I notices in db log that there are 2 queries run  to get this relation items

1-
```
SELECT * FROM `assigned_checklist` WHERE (`assigned_type`='common\\models\\Company') AND (`assigned_id`=1)
```
2- 
```
SELECT * FROM `checklist_item` WHERE (`checklist_item`.`is_deleted` = 0) AND (`id` IN ('3', '4'))
```
it should be a join condition instead

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1
| Operating system |OSX

**Comment by samdark** [comment]
Have you specified relation for eager loading? https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#lazy-eager-loading
