### ISSUE TITLE
AR ->one($db) relations are not loaded from the same DB

### ISSUE THREAD

**Issue by dmftaras** [yiisoft/yii2#17557]
### What steps will reproduce the problem?
```
$db = \Yii::$app->db2;
$model = Model::find()->one($db); // works fine
var_dump($model->customers);
```

### What is the expected result?
I expect that `customers` will be loaded from the same DB that I've passed to ->one()
### What do you get instead?
Instead it is loading customers from `Customers::getDb()` database

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7.1
| PHP version      | 7.1.6
| Operating system | Ubuntu

**Comment by samdark** [comment]
Do you have customers in multiple databases?

**Comment by dmftaras** [comment]
no, but what I wanted to do is to copy models with its relations from one database to another, here's the example:
```
$models = Orders::find()->all(\Yii::$app->db2); // Order has relation "customer", and also "customer" in Order::fields() defined
foreach ($models as $model) {
    $new_model = new Orders;
    $new_model->setAttributes(ArrayHelper::toArray($model), false);
    $new_model->save();
}
```
basically Orders are copied properly, but customers aren't, since it is trying to find them in the wrong database (\Yii::$app->db instead of \Yii::$app->db2)

**Comment by alex-code** [comment]
Does it work if you specify the relation with the query?
```php
$db = \Yii::$app->db2;
$model = Model::find()->with(['customers'])->one($db); // works fine
var_dump($model->customers);
```

**Comment by samdark** [comment]
I'm not sure it conceptually should load from the same DB since cross-database relations are supported by Yii.

**Comment by samdark** [comment]
For the task you're trying to achieve I'd not rely on Active Record in the fist place. Batches and query builder suit it much better.
