### ISSUE TITLE
Yii 2.0.17 + Yiii2-mongodb ~2.1.0 Flash message does no work

### ISSUE THREAD

**Issue by webspec2012** [yiisoft/yii2#17559]
If using MongoDB as session storage, Flash messages do not work.

```php
'session' => [
            'name' => 'backend',
            'class' => 'yii\mongodb\Session',
            'sessionCollection' => 'BackendSessions',
],
```

```php
/**
     * Changing user password
     *
     * @param string $id User id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionChangePassword($id)
    {
        $model = User::findOne($id);
        if (empty($model)) {
            throw new NotFoundHttpException("User specified not found!");
        }

        $password = User::generateRandomPassword();
        $model->setPassword($password);
        $model->generateAuthKey();

        if ($model->save(false)) {
            \Yii::$app->session->setFlash('success', 'New password was set: "'.$password.'"');
        } else {
            \Yii::$app->session->setFlash('error', 'There was an error changing password!');
        }

        return $this->redirect(['view', 'id' => $id]);
    }
```

Message is list after redirect. It works if I stop storing sessions in MongoDB.

**Comment by samdark** [comment]
@webspec2012 can you check if it's https://github.com/yiisoft/yii2/commit/8bb334b9ae5760f5ad3548f449bf4fe5b9d98d22#r33018458?

**Comment by webspec2012** [comment]
The session ID changes from one page to another.

..

> db.BackendSessions.remove({});
WriteResult({ "nRemoved" : 4 })

*refresh site page by F5*

> db.BackendSessions.find().pretty();
{
	"_id" : ObjectId("5d79f9882893100f3029bfa4"),
	"id" : "3racnq6iq3gtm8ma3has4nueva",
	"data" : "__flash|a:0:{}__id|s:24:\"5a65db240a64100202b7ca65\";"
}

*refresh site page by F5*

> db.BackendSessions.find().pretty();
{
	"_id" : ObjectId("5d79f9882893100f3029bfa4"),
	"id" : "04gl55gs0ecj22q61tu3s9l475",
	"data" : "__flash|a:0:{}__id|s:24:\"5a65db240a64100202b7ca65\";"
}

*refresh site page by F5*

> db.BackendSessions.find().pretty();
{
	"_id" : ObjectId("5d79f9882893100f3029bfa4"),
	"id" : "ilcs8pkjetisbie47p0h524adb",
	"data" : "__flash|a:0:{}__id|s:24:\"5a65db240a64100202b7ca65\";"
}

...

**Comment by lubosdz** [comment]
Fixed in PR [#285](https://github.com/yiisoft/yii2-mongodb/pull/285).

CI fail not related to this PR - see [build log](https://travis-ci.org/yiisoft/yii2-mongodb/jobs/592536779) - PHP 5.5. not pre-installed (is PHP 5.5 officially supported or can this be removed?).

**Comment by samdark** [comment]
@webspec2012 can you test with `dev-master` of the yiisoft/yii2-mongo?

**Comment by webspec2012** [comment]
The `dev-master ' branch works correctly!
