### ISSUE TITLE
console action "actionS" runs twice

### ISSUE THREAD

**Issue by oleyur** [yiisoft/yii2#17568]
### What steps will reproduce the problem?
run actionS(){} as console action

### What is the expected result?
runs twice

### What do you get instead?
not using this action name in app

### Additional info

\yii\base\Controller::createAction
_protected/vendor/yiisoft/yii2/base/Controller.php:223

$actionMap = $this->actions();

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2.
| PHP version      7.0.33 | 
| Operating system |

**Comment by rob006** [comment]
`actions()` is reserved method name, you can't have `actionS()` as action method name. The only way to have action `s` is to define it inside of `actions()` as a standalone action class.

**Comment by oleyur** [comment]
> `actions()` is reserved method name, you can't have `actionS()` as action method name. The only way to have action `s` is to define it inside of `actions()` as a standalone action class.

Sure, but I did not find mention of this in the documentation

**Comment by kamarton** [comment]
@rob006 I don't really understand the relationship between the `actions` and` actionS` method names since they can be used separately as a method.

This seems more like a mistake, but if not, it's really missing from the documentation.

**Comment by samdark** [comment]
I don't think there is a good way to mention it.

**Comment by samdark** [comment]
@rob006 any suggestion?

**Comment by rob006** [comment]
As  a note in "inline actions": https://www.yiiframework.com/doc/guide/2.0/en/structure-controllers#inline-actions ?

**Comment by samdark** [comment]
@oleyur would you please provide exact code on how you are defining your action?
