### ISSUE TITLE
default url route to use pretty url and query params format together

### ISSUE THREAD

**Issue by papppeter** [yiisoft/yii2#17570]
### What steps will reproduce the problem?
my problem is i have an old api which is still working with non pretty urls. but my new api is working with pretty urls. would like to have them in same application.

### What is the expected result?
pretty urls, and non pretty urls works together

### What do you get instead?
only one is working

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.27
| PHP version      | 7.1.32
| Operating system | Linux

sollution would be to create a default UrlRule which could be added as rules in UrlManager. The Rule would look like this:

```php
class DefaultUrlRule extends BaseObject implements UrlRuleInterface
{

    /**
     * Parses the given request and returns the corresponding route and parameters.
     * @param UrlManager $manager the URL manager
     * @param Request $request the request component
     * @return array|bool the parsing result. The route and the parameters are returned as an array.
     * If false, it means this rule cannot be used to parse this path info.
     */
    public function parseRequest($manager, $request)
    {
        Yii::debug('Pretty URL not enabled. Using default URL parsing logic.', __METHOD__);
        $route = $request->getQueryParam($manager->routeParam, '');
        if (is_array($route)) {
            $route = '';
        }

        return [(string) $route, []];
    }

    /**
     * Creates a URL according to the given route and parameters.
     * @param UrlManager $manager the URL manager
     * @param string $route the route. It should not have slashes at the beginning or the end.
     * @param array $params the parameters
     * @return string|bool the created URL, or false if this rule cannot be used for creating this URL.
     */
    public function createUrl($manager, $route, $params)
    {
        return $manager->createUrl([$route] + $params);
    }
}
```

**Comment by papppeter** [comment]
Hi,

i hope i can clarify this: so i have a yii2 advanced template with one api application. My old urls looks like following:
/index.php?r=api/v1/room/1

the new ones:
/api/v2/room/1

it would be ideally be still in same yii2 application but different modules. On modules level i cannot touch the url manager (of course in this point it is already in full work) So this is the reason i need a way have them work together. As I saw in code for now it can work only one way. It should get pretty or not pretty urls. 

My solution would give a rule to urlmanager which can parse urls from non pretty format.

**Comment by samdark** [comment]
`'enablePrettyUrl' => true,` does not disable non-pretty URLs. `'enableStrictParsing' => true,` does but you haven't mentioned it so I assume you don't have it turned on.

**Comment by papppeter** [comment]
Hi,

this is my url: /index.php?r=v1/photo/check-token&XDEBUG_SESSION_START=

my urlmanager settings:
'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false,
            'showScriptName' => false,
            'rules' => [
                ['class' => UrlRule::class, 'controller' => 'v2/user'],
...

if i am looking into the code UrlManager line 330             $pathInfo = $request->getPathInfo();
this give me back an empty string (which is correct according docu above method - A path info refers to the part that is after the entry script and before the question mark (query string).) but this should hold my route. (which is coming from r=) but it does not care about the r= query param anywhere there.

any suggestion?

**Comment by samdark** [comment]
I need a reproducible test case to suggest anything. Currently I'm not sure what the problem is.
