### ISSUE TITLE
Request::getUserIP() not secure with trustedHost and ip headers

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii2#17573]
### What steps will reproduce the problem?

Processing of `Request::getUserIP()` is not secure for `trustedHost`, for example from `X-Forwarded-For`.

network:
```
client ------ > valid network endpoint (e.g. LB) -----> server (---> PHP)
1.1.1.1             2.2.2.2                        3.3.3.3
```

simple way:
- client not send X-Forwarded-For
- LB add client IP to X-Forwarded-For (`1.1.1.1`)
- PHP see `X-Forwarded-For: 1.1.1.1` / `Remote address: 2.2.2.2`

hard way:
- client send X-Forwarded-For. This is due to additional network endpoints or malicious injection. (`127.0.0.1, 8.8.8.8`)
- LB add client IP (`127.0.0.1, 8.8.8.8,1.1.1.1`)
- PHP see `X-Forwarded-For: 127.0.0.1, 8.8.8.8,1.1.1.1` / `Remote address: 2.2.2.2`

### What is the expected result?

If `trustedHost` is set to 2.2.2.2 then the `getUserIp()` is `1.1.1.1` (the address of after the last valid endpoint)

### What do you get instead?

If `trustedHost` is set to 2.2.2.2 then the `getUserIp()` is `127.0.0.1`.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
The case seems to be correct.
