### ISSUE TITLE
ToggleButtonGroup adds "form-control" class to the conatainer <div>

### ISSUE THREAD

**Issue by is7** [yiisoft/yii2#17592]
### What steps will reproduce the problem?

Output ToggleButtonGroup widget without "class" in the "options"

### What's expected?

`<div id="some-id" data-toggle="buttons" class="btn-group">`

### What do you get instead?

`<div id="some-id" data-toggle="buttons" class="form-control btn-group">`

So div can be displayed with borders and overlap buttons. 

### Additional info

It works as expected on yii2-bootstrap v2.0.9 and yii2 v2.0.16
It can be solved by passing an empty "class" to the widget options
`'options' => [
  'class' => []
]`

**Comment by samdark** [comment]
#16681

**Comment by jwlewisiii** [comment]
The code below generates the expected html, without the "form-control" class. 
``` php
\yii\bootstrap\ToggleButtonGroup::widget([
		'name'  => 'sport',
		'type'  => 'checkbox',
		'items' => [
			0 => 'Soccer',
			1 => 'Basket',
			2 => 'Tennis',
		],
		'value' => [0, 1],
	]);
```

If you are using ActiveForm to display the ToggleButtonGroup in a form the "form-control" class is the default class setting via ActiveField::$inputOptions.

**Comment by samdark** [comment]
That explains it. Options could be set for it so there's nothing to fix.
