### ISSUE TITLE
[Help] Override Application property

### ISSUE THREAD

**Issue by sanyisasha** [yiisoft/yii2#17598]
### What steps will reproduce the problem?
I was overrided the `\yii\web\User` class, because i needed custom access checking.  
Currently i want to add a custom variable to this class, what is working good (`\Yii::$app->user->variable`), but it's not suggested when i type `user->`, it's write the user variable is from `\yii\web\User`, because the Application description has the property description.
### What is the expected result?
Showing my own User class as suggestion and ability to see my custom methods/variables.  
Example:
```php
var_dump(\Yii::$app->user->test); exit;
// Here the storm not see the variable, but the var_dump dump the test variable.
```
### What do you get instead?
The default `\yii\web\User`.  

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.28-dev
| PHP version      | 7.2
| Operating system | linux mint 19 tara

**Comment by My6UoT9** [comment]
see here: https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md

**Comment by sanyisasha** [comment]
> see here: https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md

Thanks, it's worked for me! :)
