### ISSUE TITLE
PostgreSQL 12 support

### ISSUE THREAD

**Issue by MixMe** [yiisoft/yii2#17597]
Will Yii2 support PostgreSQL 12 ?

`SQLSTATE[42703]: Undefined column: 7 ERROR: column c.consrc does not exist
LINE 10: "c"."consrc" AS "check_expr"
^
HINT: Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
The SQL being executed was: SELECT
"c"."conname" AS "name",
"a"."attname" AS "column_name",
"c"."contype" AS "type",
"ftcns"."nspname" AS "foreign_table_schema",
"ftc"."relname" AS "foreign_table_name",
"fa"."attname" AS "foreign_column_name",
"c"."confupdtype" AS "on_update",
"c"."confdeltype" AS "on_delete",
"c"."consrc" AS "check_expr"
FROM "pg_class" AS "tc"
INNER JOIN "pg_namespace" AS "tcns"
ON "tcns"."oid" = "tc"."relnamespace"
INNER JOIN "pg_constraint" AS "c"
ON "c"."conrelid" = "tc"."oid"
INNER JOIN "pg_attribute" AS "a"
ON "a"."attrelid" = "c"."conrelid" AND "a"."attnum" = ANY ("c"."conkey")
LEFT JOIN "pg_class" AS "ftc"
ON "ftc"."oid" = "c"."confrelid"
LEFT JOIN "pg_namespace" AS "ftcns"
ON "ftcns"."oid" = "ftc"."relnamespace"
LEFT JOIN "pg_attribute" "fa"
ON "fa"."attrelid" = "c"."confrelid" AND "fa"."attnum" = ANY ("c"."confkey")
WHERE "tcns"."nspname" = 'public' AND "tc"."relname" = 'session'
ORDER BY "a"."attnum" ASC, "fa"."attnum" ASC

Error Info: Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column c.consrc does not exist
LINE 10:     "c"."consrc" AS "check_expr"
             ^
HINT:  Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
)

↵
Caused by: PDOException
SQLSTATE[42703]: Undefined column: 7 ERROR: column c.consrc does not exist
LINE 10: "c"."consrc" AS "check_expr"
^
HINT: Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".

in /app/vendor/yiisoft/yii2/db/Command.php at line 1290
`

` in /app/vendor/yiisoft/yii2/db/Schema.php at line 674 `

**Comment by samdark** [comment]
> Will Yii2 support PostgreSQL 12 ?

Only if someone will contribute this support.

**Comment by batyrmastyr** [comment]
This particular error is solved by replacing `"c"."consrc" AS "check_expr"` with `pg_get_constraintdef("c"."oid") AS "check_expr"`.
According to the [docs](https://www.postgresql.org/docs/8.2/functions-info.html) function exists since 8.2 at least. Query works at least in Postgresql 9.4, in any older versions.

Output is a bit different
```
"c".consrc                               ((srid > 0) AND (srid <= 998999))
pg_get_constraintdef("c"."oid")          CHECK (((srid > 0) AND (srid <= 998999)))
pg_get_constraintdef("c"."oid", true)    CHECK (srid > 0 AND srid <= 998999)
```
Plus `pg_get_constraintdef` returns definition of any constraint, for example `FOREIGN KEY (address_id) REFERENCES build_building(address_id) ON UPDATE CASCADE ON DELETE RESTRICT` instead of `null` in `consrc`.

**Comment by samdark** [comment]
Sounds like version detection is needed.

**Comment by batyrmastyr** [comment]
As far as I see, Yii itself doesn't care  definition and you can return `null` withiout breaking anything. Anyways, if somebody really relied on `consrc`'s format, it's possible to simulate it with `substr`'ing output of `pg_get_constraintdef("c"."oid")`

By the way `pg_get_constraintdef("c"."oid")` and `pg_get_constraintdef("c"."oid", true)` works perfectly in Postgresql `8.4` (the eldest found in repositories) while yii states support of `9.x` only, so version check is not required.

**Comment by batyrmastyr** [comment]
Digging into the docs:
-  `pg_get_constraintdef` is supported since `7.4` (in earlier versions it lacked functionality).
- It's possible to get `consrc` output using `pg_get_expr("c".conbin, "c".conrelid)` but [recommended](https://www.postgresql.org/docs/7.4/catalog-pg-constraint.html) way is to use `pg_get_constraintdef`.
- >  consrc is not updated when referenced objects change; for example, it won't track renaming of columns.

**Comment by samdark** [comment]
Since you're into it, do you want to prepare a pull request?

**Comment by batyrmastyr** [comment]
I'll do it.

**Comment by batyrmastyr** [comment]
Current progress: 
- no fatal errors )
- pg_get_constraintdef breaks 3 tests, I'm going to fix tests. 
- Added fetching schema on partitioned tables (introduced in Postgres 10). No tests yet.
- Postgres 12 introduced `generated as identity` columns (and `pg_attribute.attgenerated` in schema) as standarts compliant version to `sequence / serial`, so `$column->autoIncrement` returns value. Fixing it requires some kind of version detection.

Test results on [master@9.4](https://gist.github.com/batyrmastyr/41124fc40394391d38cbb581d7f0375c), [patch@9.4](https://gist.github.com/batyrmastyr/12cafcfe311655462d4b5a330d29d010), [patch@12.0](https://gist.github.com/batyrmastyr/97f6fb6416b128f8fab459f2556b312e). 
There is a regression on 9.4 in CommandTest::testQueryCache with patch, maybe it's some random bug (test run requires 30 minutes so I'll retry later).

**Comment by batyrmastyr** [comment]
- added test for schema retrieval of partitioned tables for PostgreSQL 10+
- added support for `generated as identity` columns, 
- added tests for changing `default` value on `serial` columns

I'm a bit hesistant:
- to use `Schema::resolveTableName` to get reliable sequence name
- to add `sequenceName` field to `pgsql\ColumnSchema` as PostgreSQL allows to add several auto-incremental fields on a table.
- to create and drop tables, and to change default values in test cases (the latter _may_ to be error prone). Splitting sql statements by ';' in `tests/framework/db/DatabaseTestCase::prepareDatabase` doesn't allow to create tables depending on PostgreSQL version in `postgres.sql`.

**Comment by batyrmastyr** [comment]
- fixed CommandTest::testQueryCache

All tests pass if they passed before my patch (I did nothing to fix 2 years old CURRENT_TIMESTAMP bug and so on).
