### ISSUE TITLE
Error when using old mobile browsers - assets wrong path

### ISSUE THREAD

**Issue by pablo-finamar** [yiisoft/yii2#17605]
### What steps will reproduce the problem?
Loading any action (ex. site/login) from a mobile browser like the one from iphone 5 etc. (catched using the logs, then tested with a mobile emulator)

### What is the expected result?
Css files are loaded from the assets folder

### What do you get instead?
Css files are loaded as the asset folder is in a relative path from the action.
From the logs:
... `yii\base\InvalidRouteException: Unable to resolve the request "site/login/assets/..."` ...
Happens with various assets, like _yii\jui\JuiAsset_

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.1/7.3 (same problem on production server (CentOS + Php 7.1) and test environment Windows xampp(7.3))
| Operating system | CentOS

--- EDIT: more infos

### When does the issue occur?
Whenever an user with an old smartphone browser or a robot like google bot crawler visits the site (any page, for example login page). It works fine in other cases.

### What do you see?
Missing CSS stylesheets, other than that no other visible effects. But i can see the errors in the logs file

### What was the expected result?
As i already said, i would expect the css files to be loaded from the assets folder.
Instead i get a page loaded without some important css stylesheets obviously styled in a wrong way.

### Can you supply us with a stacktrace? (optional)
```
2019-10-09 09:43:35 [51.68.11.195][-][li1uj8k7n6o4cmbkcmug51408u][error][yii\web\HttpException:404] yii\base\InvalidRouteException: Unable to resolve the request "site/login/assets/85260738/css/fontawesome-all.min.css rel=stylesheet". in /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('site/login/asse...', Array)
#1 /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Ð¡Ñ‚Ð¾Ñ€Ñ–Ð½ÐºÐ° Ð½Ðµ Ð·Ð½Ð°Ð¹Ð´ÐµÐ½Ð°. in /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/web/index.php(12): yii\base\Application->run()
#2 {main}
```

### Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)
This is one of the assets:
```
<?php

namespace app\assets;

use yii\web\AssetBundle;

class FAAsset extends AssetBundle
{
    public $sourcePath = '@vendor/components/font-awesome';

    public $css = [
        'css/fontawesome-all.min.css',

    ];

}
```

And this in the layouts/main.php (my base template)
```
use app\assets\FAAsset;
FAAsset::register($this);

```

**Comment by pablo-finamar** [comment]
This is the <head> part of the document.
```

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
        <meta name="csrf-param" content="_csrf">
    <meta name="csrf-token" content="FrgAVHuCEQ04KuTcZTV09RIccHtHBLDTWkVEnObdriR60zQxH8ZSeHdotoM6QDucf3AvPwRz4JoqAh7tha_fdg==">
        <title>Login</title>
        <link href="/assets/1d31f22/css/bootstrap.css" rel="stylesheet">
<link href="/assets/2a15aa29/css/font-awesome.min.css" rel="stylesheet">
<link href="/assets/fe349549/custom.css" rel="stylesheet">
<link href="/assets/99fb3e9b/themes/smoothness/jquery-ui.css" rel="stylesheet">
<link href="/css/site.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans|Unica+One" rel="stylesheet">
<link href="/assets/a5be4513/css/fontawesome-all.min.css" rel="stylesheet">
<link href="/assets/f68ffb43/css/bootstrap-dialog-bs3.min.css" rel="stylesheet">
<script src="/assets/f68ffb43/js/dialog.min.js"></script>
```

**Comment by alex-code** [comment]
This is a bit odd, `rel=stylesheet` is part of the request.

`2019-10-09 09:43:35 [51.68.11.195][-][li1uj8k7n6o4cmbkcmug51408u][error][yii\web\HttpException:404] yii\base\InvalidRouteException: Unable to resolve the request "`**`site/login/assets/85260738/css/fontawesome-all.min.css rel=stylesheet`**`". in /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/vendor/yiisoft/yii2/base/Module.php:537`

Can you update too, latest version is 2.0.28

**Comment by pablo-finamar** [comment]
> 
> 
> This is a bit odd, `rel=stylesheet` is part of the request.
> 
> `2019-10-09 09:43:35 [51.68.11.195][-][li1uj8k7n6o4cmbkcmug51408u][error][yii\web\HttpException:404] yii\base\InvalidRouteException: Unable to resolve the request "`**`site/login/assets/85260738/css/fontawesome-all.min.css rel=stylesheet`**`". in /var/www/vhosts/myname.co.uk/my.myname.co.uk/projectn/vendor/yiisoft/yii2/base/Module.php:537`
> 
> Can you update too, latest version is 2.0.28

I just tested all with a fresh 2.0.28 install. And i still get the rel stylesheet problem. But i'm afraid it's the iphone emulator.
With a real iphone(i get another error which i thought it was related to the 404. But probably it isn't. I will investigate then add more infos.

**Comment by samdark** [comment]
The HTML formed is correct. There are no relative URLs. Quotes are properly closed so there's not much we can do about browsers that aren't able to read correct HTML.
