### ISSUE TITLE
EmailValidator with checkDNS=true throws ErrorException on bad domains

### ISSUE THREAD

**Issue by batyrmastyr** [yiisoft/yii2#17602]
### What steps will reproduce the problem?
validate `sbdfbnd@ya2.ru` using EmailValidator with checkDNS=true
`error_reporting=E_ALL` or alike is needed to convert warning to exception in \yii\base\ErrorHandler::handleError
### What is the expected result?
validation returns false
### What do you get instead?
 PHP Warning – yii\base\ErrorException is thrown by `$mxRecords = dns_get_record($domain . '.', DNS_MX)` and `$mxRecords = dns_get_record($domain . '.', DNS_A);`;
That's due to dns_get_record return false and emits Warning on some domains

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.27 (should be since 2.0.11, issue https://github.com/yiisoft/yii2/issues/12714) 
| PHP version      | 7.3.10
| Operating system | Alpine

Suppose it should be fine to rewrite calls to `dns_get_record` this way:
```
try {
     $mxRecords = dns_get_record($domain . '.', DNS_MX);
} catch (\yii\base\ErrorException $exception) {
     return false;
}

**Comment by kamarton** [comment]
https://mxtoolbox.com/SuperTool.aspx?action=mx%3aya2.ru&run=toolpage#

> Sorry, we couldn't find any name servers for 'ya2.ru'

I don't really understand why `checkdnsrr()` doesn't work.

https://github.com/yiisoft/yii2/blob/5efe0bda8f07fc8a16ddd2f86c585a26c7c18785/framework/validators/EmailValidator.php#L114-L126

I don't really understand what the purpose of the current implementation is to get DNS records. I suggests:

```php
protected function isDNSValid($domain) {
  return checkdnsrr($domain . '.', 'MX') || checkdnsrr($domain . '.', 'A');
}
```

**Comment by kamarton** [comment]
```bash
$ php -r 'var_dump(dns_get_record("ya2.ru" . ".", DNS_MX));'
PHP Warning:  dns_get_record(): A temporary server error occurred. in Command line code on line 1
bool(false)
$ php -r 'var_dump(@dns_get_record("ya2.ru" . ".", DNS_MX));'
bool(false)
```

**Comment by batyrmastyr** [comment]
> what the purpose of the current implementation is to get DNS records

`checkdnsrr` always return `true` in Alpine. Yes, it's php bug and it isn't fixed yet (maybe it isn't reported also).

**Comment by samdark** [comment]
@batyrmastyr wrapping with try-catch + logging sounds OK. Do you want to prepare a pull request?

**Comment by batyrmastyr** [comment]
@samdark prepared pull request, but what do you meant under "logging"?

**Comment by kamarton** [comment]
> @samdark prepared pull request, but what do you meant under "logging"?

```php
try {
...
} catch(... $e) {
  Yii::error('dns_get_record() fail with message: '.$e->getMessage(), __METHOD__);
// or Yii::warning(...)
}
```
