### ISSUE TITLE
Making Url::canonical() work with pagination

### ISSUE THREAD

**Issue by ldkafka** [yiisoft/yii2#17613]
Unfortunately, the Url::canonical() method does not deal with paging which uses get parameters.

I suggest registering a controller actionParam with the page name/value inside the setPage Pagination method. This would get picked up by the canonical() method when building the url.

Insert after line 201 in https://github.com/yiisoft/yii2/blob/master/framework/data/Pagination.php#L186 a line such as:

if($this->_page) \Yii::$app->controller->actionParams[$this->pageParam] = $this->_page;

* Some extra checking may need to be done and the $params array may also need to be taken into account.

**Comment by ldkafka** [comment]
Actually, it may have been a nice thought, but it relies on the code execution order to work - ie. $this->registerLinkTag(['rel' => 'canonical', 'href' => Url::canonical()]); would need to run at the end of the code...

Is there any other higher-order way of registering paging vars? Perhaps move the canonical method to the view which gets rendered at the end after the pager is initialized?

**Comment by samdark** [comment]
What's your use case for canonical URLs with pagination? As far as I understand, it makes no sense to provide canonical URLs for it.

**Comment by ldkafka** [comment]
That's what I thought until today when I spent several hours researching current best practices... The conclusion I have drawn is that each page (ie. /widgets/?page=3) needs to be canonical. Up until now I have just made the category root canonical (ie. /widgets) but that seems to have been a mistake.

Some references: https://www.deepcrawl.com/knowledge/technical-seo-library/pagination-seo-guide, https://www.searchenginejournal.com/seo-friendly-pagination, etc...

**Comment by samdark** [comment]
> each page (ie. /widgets/?page=3) needs to be canonical

1. That would cause duplicate results. You'll have pages mixed with articles.
2. Yii 2 uses offset pagination. That means page 2 today and page 2 after you post more articles are totally different.

**Comment by ldkafka** [comment]
Yes, the page content will change (for all pages), so there should not be duplicate item entries across pages at the same point in time. This is how this works for sites be it new articles, or items out of stock, etc - the page content is not assumed to stay static. If in addition to "canonical" we insert "prev/next" links (although Google is paying less attention to this now), then the paginated pages are to be thought of as a "dataset" rather than pages of disparate items.

**Comment by samdark** [comment]
OK. That may make sense if you still want to have pages in the index.

I think you're looking for changes in https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php

**Comment by samdark** [comment]
Please check if that's easy to do via parameters/inheritance. If it's so then I'd leave current code as is since there are cases when you don't want canonical links for pages.

**Comment by rob006** [comment]
This should be possible by adding `$page` parameter in action method or by altering `Controller::$actionParams` (for example in `bindActionParams()`). Neither `LinkPager` nor `Pagination` should affect this behavior - they should be limited to read page number from controller/request, setting some global page number is not their job.

**Comment by batyrmastyr** [comment]
Moreover, there could be several tables on the page. In most cases it's stupid, but sometimes there is not other way.
