### ISSUE TITLE
Error in console/widgets/Table.php

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#17627]
### What steps will reproduce the problem?
Table with empty array as value of some ceil:
```
        $table = new Table();
        $table->setRows([['something', []]])->run();
```
### What is the expected result?
empty ceil / only dot

### What do you get instead?
```
PHP Warning 'yii\base\ErrorException' with message 'max(): Array must contain at least one element'

in /var/www/html/vendor/yiisoft/yii2/console/widgets/Table.php:333
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | yiisoft/yii2                                     dev-master 0d11a58 Yii PHP Framework Version 2
| PHP version      | 7.3.10
| Operating system |alpine

**Comment by alex-code** [comment]
I can do a PR for this.
Thought about adding an `emptyCell` property to the `Table` class that can have a default value too.

**Comment by samdark** [comment]
Why do we need a special value for empty cell? Isn't it a number of spaces all the time?

**Comment by alex-code** [comment]
My thinking, cells would be empty by default but you can specify a string to use for empty cells too.
```php
$table = new Table();
$table->setRows([['something', []]])->run();
```
Col 1 | Col2
------------ | -------------
Something | 

```php
$table = new Table(['emptyCell' => 'N/A']);
$table->setRows([['something', []]])->run();
```
Col 1 | Col2
------------ | -------------
Something | N/A

**Comment by samdark** [comment]
Let's implement it with always empty cells and see later if customizing it would be requested.
