### ISSUE TITLE
Unexpected result applying rules filters to virtual attribute

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii2#17626]
**Working Example:**

```php
private $_attr_virtual;

public function rules() {
   return [['attr_virtual'],'myownvalidator or "safe" validator']
}


public function set_attr_virtual($value)
{
   $this->_attr_virtual = $value;
}

public function get_attr_virtual()
{
  return $this->_attr_virtual . "bar";
}

public function beforeSave(){
  print_r($this->_attr_virtual); //Echoes "hello" when submitting model._attr_virtual = "hello";
}
```

**NOT Working Example:**

```php
private $_attr_virtual;

public function rules() {
   return [['attr_virtual'],'filter','filter'=>'trim']
}

public function set_attr_virtual($value)
{
   $this->_attr_virtual = $value;
}

public function get_attr_virtual()
{
  return $this->_attr_virtual . "bar";
}

public function beforeSave(){
  print_r($this->_attr_virtual); //Echoes "hellobar" when submitting model._attr_virtual = "hello";
}
```

When using "filter" rules on virtual attributes, when using $model->_attr_virtual is replaced by the value returned on get_attr_virtual(), instead of return the submitted value. A "filter" rule must work like any other rule.

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.28
| PHP version      | 7.3
| Operating system | Linux Ubuntu

**Comment by rob006** [comment]
That is because filters also set new value to filtered attribute (so they call both - getter and setter). In your case it works like `$this->_attr_virtual = trim($this->_attr_virtual)`. This unexpected result is consequence of lack of symmetry between getter and setter - I'm not sure if it could be fixed at framework level.
