### ISSUE TITLE
\MessageFormatter::format() should not be used if ICU < 4.8

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#17629]
When translating a message that contains formatted parameters, the parameters won’t be parsed correctly if the Intl extension is installed, but the ICU library is lower than v4.8.

### What steps will reproduce the problem?

1. Create an environment with ICU < 4.8 (CentOS 6 ships with 4.2.1, for example).
2. Run this:

    ```php
    echo Yii::t('category', '{first, number}-{last, number} of {total, number} {total, plural, =1{{item}} other{{items}}}', [
        first: 1,
        last: 50,
        total: 100,
        item: 'entry',
        items: 'entries',
    ]);
    ```

### What is the expected result?

The `{first, number}`, `{last, number}`, `{total, number}`, and `{total, plural, =1{{item}} other{{items}}}` parameters should be parsed and formatted.

### What do you get instead?

`{first, number}-{last, number} of {total, number} {total, plural, =1{{item}} other{{items}}}` is output instead.

This could be avoided if `yii\i18n\MessageFormatter::formatter()` were to check the installed ICU database version, and use `$this->fallbackFormat()` if it’s less than 4.8.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29
| PHP version      | n/a
| Operating system | CentOS 6

**Comment by samdark** [comment]
It was expected that user would run requirements.php to find it out: https://github.com/yiisoft/yii2/blob/master/framework/requirements/requirements.php#L75

**Comment by samdark** [comment]
Plurals aren't working correctly but other ICU features are. This change may break projects with ICU < 4.8 that aren't using plurals with placeholders.

**Comment by brandonkelly** [comment]
Ah sorry, I had missed that requirements check.

> This change may break projects with ICU < 4.8 that aren't using plurals with placeholders.

True, so do you think it’s worth making it configurable? So if you’re on a host that is stuck with an older version of ICU (let’s say older than 49 to be consistent with the requirement check), you could do this if you want to use `formatFallback()`:

```php
'components' => [
    'i18n' => [
        'messageFormatter' => [
            'useFallbackFormat' => true,
        ],
    ],
],
```

**Comment by samdark** [comment]
Yes. The name could be `forceFallbackFormat` or alike.

**Comment by samdark** [comment]
Or maybe not. There's `FallbackMessageFormatter` in tests. Alike approach could be used to specify that another class should be used,

**Comment by brandonkelly** [comment]
If we did that, shouldn’t the I18N class start automatically using that as well, if the `\MessageFormatter` class doesn’t exist, and move `formatFallback()` out of `yii\i18n\MessageFormatter`? That could be a breaking change though if anything is calling that method.

**Comment by samdark** [comment]
Yeah. It's `protected` :( Option makes sense then.

**Comment by samdark** [comment]
@brandonkelly do you still need the check? I've closed pull request because of https://github.com/yiisoft/yii2/issues/17629#issuecomment-545305761

**Comment by brandonkelly** [comment]
@samdark Sorry, got sidetracked from this. We were able to extend MessageFormatter::format() with our own check in a way that didn’t feel too hacky (craftcms/cms@eff654f21af547f2d97d89362a07053e55ee4e7a) so it’s not a huge deal, especially if the Yii requirements mention that plurals require ICU 49+. I’ll go ahead and close this.
