### ISSUE TITLE
BaseListView summaryOptions

### ISSUE THREAD

**Issue by sjaakp** [yiisoft/yii2#17631]
BaseListView's summaryOptions are not taken into account if summary is set to anything else than null, and pagination = false.

I think the return value in line 230 should be wrapped in a Html::tag, just like the other return values of renderSummary.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22
| PHP version      | 7.2.7
| Operating system | Windows 10

**Comment by samdark** [comment]
Good catch! Want to fix it and send a pull request?
