### ISSUE TITLE
Db session not work correctly with php 7.2.14

### ISSUE THREAD

**Issue by istvan0304** [yiisoft/yii2#17649]
If I use db session with php 7.2.14 the session always lost or stuck. For example the flash message stuck and even appear after many redirect. With php 7.1 or php 7.3 work correctly, file session is work with php 7.2.14 too.

db create: 

```
CREATE TABLE session
(
    id CHAR(64) NOT NULL PRIMARY KEY,
    expire INTEGER,
    data BYTEA
)
```

my config:

```
'session' => [
            'class' => 'yii\web\DbSession',
            'cookieParams' => ['lifetime' => 7 * 24 * 60 * 60],
             'sessionTable' => 'session',
        ],
```

### Additional info

Database is mysql

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.28
| PHP version      | 7.2.14
| Operating system | Windows 10

**Comment by samdark** [comment]
What do you mean by "lost or stuck"?

**Comment by istvan0304** [comment]
I set a session like this:
`$session = Yii::$app->session;
$session->set('foo', 'bar');
`
and after redirect I want to get is like this: 
`
$session = Yii::$app->session;
$session->get('foo');
`
it is return with null, so it is lost.

The flash messages stuck because stays in the session after many redirects.

**Comment by samdark** [comment]
OK. These seem to be two very different cases.

## Losing session data.

1. What's in the database table after

```php
$session = Yii::$app->session; $session->set('foo', 'bar');
```

?

2. What's in the database table after redirect?

## Stuck flash messages

1. How do you display a flash message?
2. What's in the database before setting a flash message?
3. What's in the database after setting a flash message?
4. What's in the database after displaying a message?
5. What's in the database after redirect a message?
5. What's in the database after displaying a message second time?

**Comment by istvan0304** [comment]
### Losing session data.
Session table data after set:
`__flash|a:0:{}__returnUrl|s:34:"http://hr-adminisztralo.test/site/";__id|i:1;__expire|i:1572610123;log_in|i:1572523690;`

After redirect is same, so nothing write to the session table.
`__flash|a:0:{}__returnUrl|s:34:"http://hr-adminisztralo.test/site/";__id|i:1;__expire|i:1572610218;log_in|i:1572523690;`

### Stuck flash messages
**1.** In my header view file:
`<?php
$success = Html::encode(Yii::$app->session->getFlash('success'));
$error = Html::encode(Yii::$app->session->getFlash('error'));
$this->registerJs("var flashSuccess = '{$success}';", View::POS_HEAD);
$this->registerJs("var flashError = '{$error}';", View::POS_HEAD);`

and I use sweet alert in javascript:
`if (flashSuccess !== undefined && flashSuccess !== '') {
swal("", flashSuccess, "success");
}
`

**2.** Before set flash message the session data in database:
`__flash|a:0:{}__returnUrl|s:34:"http://hr-adminisztralo.test/site/";__id|i:1;__expire|i:1572610452;log_in|i:1572523690;`

**3.** After set flash message the session data in database:
`__flash|a:1:{s:7:"success";i:-1;}__returnUrl|s:34:"http://hr-adminisztralo.test/site/";__id|i:1;__expire|i:1572610553;log_in|i:1572523690;success|s:20:"Save successful.";`

**4.** After display message is the same data:
`__flash|a:1:{s:7:"success";i:-1;}__returnUrl|s:34:"http://hr-adminisztralo.test/site/";__id|i:1;__expire|i:1572610553;log_in|i:1572523690;success|s:20:"Save successful.";`

**5.** Same data even make a redirect:
`__flash|a:1:{s:7:"success";i:1;}__returnUrl|s:34:"http://hr-adminisztralo.test/site/";__id|i:1;__expire|i:1572610675;log_in|i:1572523690;success|s:20:"Save successful.";`

**6.** And same data too after display second time:
`__flash|a:1:{s:7:"success";i:1;}__returnUrl|s:34:"http://hr-adminisztralo.test/site/";__id|i:1;__expire|i:1572610675;log_in|i:1572523690;success|s:20:"Save successful.";`

In my controller:

```
public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $model->load(Yii::$app->request->post());

            return ActiveForm::validate($model);
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Save successful.');
            
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
```
From here the flash message is always in the database session data.

**Comment by samdark** [comment]
# Losing session data

How do you redirect?

**Comment by istvan0304** [comment]
`return $this->redirect(['index']);`

**Comment by samdark** [comment]
OK. The code doesn't look suspicious. Behavior is definitely wrong. On some range of 7.2.x versions there was a bug that is currently fixed at least in 7.3. Have you tried latest 7.2.x such as 7.2.24?

**Comment by samdark** [comment]
Glad we figured it out. Since we cannot fix the bug from our side, I am closing the issue.

**Comment by My6UoT9** [comment]
I had suggest to note that somewhere, that it ain't compatible with 7.2.14.

**Comment by samdark** [comment]
We have no idea if it's session that has a bug, PDO or pdo_mysql or something else so note may be very confusing.

**Comment by samdark** [comment]
The issues are well indexed by search engines so having it here is a good thing.

**Comment by srakl** [comment]
> 
> 
> The issues are well indexed by search engines so having it here is a good thing.

@samdark are there issues with `DBsession` on php 8 too?

https://github.com/yiisoft/yii2-authclient/issues/324

**Comment by samdark** [comment]
@srakl maybe. I haven't encoutered any on my projects though.

**Comment by annaDostoevskaya** [comment]
How did you end up solving this problem?

I have a similar project going on right now.

After I authenticate the user through Google and redirect him to the main page, the session ID is reset and I can no longer get the authentication token.

However, there are no such problems with other authentication services.
