### ISSUE TITLE
Poor Framewrok

### ISSUE THREAD

**Issue by cesarhfborges** [yiisoft/yii2#17641]
this framework is poor, community weak, I don't understand why model has extends in so many ways, and anyone who needs to use eloquent or access database data or just use model to instantiate objects, just instantiate in different ways instead of losing recreating distinct models for different purposes, the object being the same. It is a pity that the company I work for insists on using this waste instead of the larvel that has a friendlier method of development, which is why the Yii2 community is small and restricted, so it does not grow. using bootstrap 3, and other past technologies and dead guidelines, and proven ineffective or overly complex methods for simple operations.

**Comment by Buliwyfa** [comment]
I agree that community is small but Yii2 has a lot to offer! even if its recent development towards version 3 has passed some difficulties (I believe we all miss Paul Klimov work )... but Yii2 still alive and being updated! (plz check https://github.com/yiisoft/yii2-bootstrap4)

Alos, here are some other opinions comparing Laravel vs Yii2 that I like from 3 parties:

http://snte-tics-educacion.blogspot.com/2017/07/comparacion-entre-laravel-y-yii-20.html
https://justcoded.com/blog/laravel-vs-yii-the-best-php-framework-in-2019/

**Comment by demonking** [comment]
>  It is a pity that the company I work for insists on using this waste instead of the larvel that has a friendlier method of development, which is why the Yii2 community is small and restricted, so it does not grow. using bootstrap 3, and other past technologies and dead guidelines, and proven ineffective or overly complex methods for simple operations.

If you think so, leave the company and find a company which use laravel?
Don't know what this issue should be ...

Someone is frustrated about a framework, which his company has choose ...
Seems for me like a spam and should be closed.
