### ISSUE TITLE
Installing via composer - still old version 2.0.26 - why?

### ISSUE THREAD

**Issue by pabloneruda1** [yiisoft/yii2#17640]
I run:
composer create-project yiisoft/yii2-app-basic basic

but still old 2.0.26 version is downloaded, why?:

LOG:
Installing yiisoft/yii2-app-basic (2.0.26)
  - Installing yiisoft/yii2-app-basic (2.0.26): Downloading (100%)
Created project in basic
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 70 installs, 0 updates, 0 removals
  - Installing yiisoft/yii2-composer (2.0.8): Downloading (100%)
  - Installing codeception/verify (0.4.0): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)
  - Installing codeception/specify (0.4.6): Downloading (100%)
  - Installing bower-asset/jquery (3.4.1): Downloading (100%)
  - Installing bower-asset/bootstrap (v3.4.1): Downloading (100%)
  - Installing bower-asset/yii2-pjax (2.0.7.1): Downloading (100%)
  - Installing bower-asset/punycode (v1.3.2): Downloading (100%)
  - Installing bower-asset/inputmask (3.3.11): Downloading (100%)
  - Installing cebe/markdown (1.2.1): Downloading (100%)
  - Installing ezyang/htmlpurifier (v4.11.0): Downloading (100%)
  - Installing yiisoft/yii2 (2.0.29): Downloading (100%)
  - Installing yiisoft/yii2-bootstrap (2.0.10): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.12.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.12.0): Downloading (100%)
  - Installing symfony/polyfill-intl-idn (v1.12.0): Downloading (100%)
  - Installing symfony/polyfill-iconv (v1.12.0): Downloading (100%)
  - Installing doctrine/lexer (1.0.2): Downloading (100%)
  - Installing egulias/email-validator (2.1.11): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v6.2.1): Downloading (100%)
  - Installing yiisoft/yii2-swiftmailer (2.1.2): Downloading (100%)
  - Installing opis/closure (3.4.1): Downloading (100%)
  - Installing yiisoft/yii2-debug (2.1.10): Downloading (100%)
  - Installing phpspec/php-diff (v1.1.0): Downloading (100%)
  - Installing yiisoft/yii2-gii (2.1.2): Downloading (100%)
  - Installing fzaninotto/faker (v1.8.0): Downloading (100%)
  - Installing yiisoft/yii2-faker (2.0.4): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing sebastian/exporter (3.1.2): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (5.0.10): Downloading (100%)
  - Installing codeception/stub (1.0.4): Downloading (100%)
  - Installing sebastian/diff (2.0.1): Downloading (100%)
  - Installing sebastian/comparator (2.1.3): Downloading (100%)
  - Installing behat/gherkin (v4.4.5): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.12.0): Downloading (100%)
  - Installing symfony/dom-crawler (v3.4.32): Downloading (100%)
  - Installing symfony/css-selector (v3.4.32): Downloading (100%)
  - Installing symfony/browser-kit (v3.4.32): Downloading (100%)
  - Installing symfony/yaml (v3.4.32): Downloading (100%)
  - Installing symfony/event-dispatcher (v3.4.32): Downloading (100%)
  - Installing psr/log (1.1.1): Downloading (100%)
  - Installing symfony/debug (v3.4.32): Downloading (100%)
  - Installing symfony/console (v3.4.32): Downloading (100%)
  - Installing symfony/finder (v3.4.32): Downloading (100%)
  - Installing ralouphie/getallheaders (3.0.3): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.6.1): Downloading (100%)
  - Installing theseer/tokenizer (1.1.3): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/environment (3.1.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (2.0.2): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.5): Downloading (100%)
  - Installing phpunit/php-code-coverage (5.3.2): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
  - Installing sebastian/global-state (2.0.0): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing webmozart/assert (1.5.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.5.1): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (4.3.2): Downloading (100%)
  - Installing phpspec/prophecy (1.9.0): Downloading (100%)
  - Installing phar-io/version (1.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.1): Downloading (100%)
  - Installing phpunit/phpunit (6.5.14): Downloading (100%)
  - Installing codeception/base (2.3.9): Downloading (100%)
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
symfony/browser-kit suggests installing symfony/process
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/event-dispatcher suggests installing symfony/http-kernel
symfony/console suggests installing symfony/lock
symfony/console suggests installing symfony/process
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
codeception/base suggests installing aws/aws-sdk-php (For using AWS Auth in REST module and Queue module)
codeception/base suggests installing codeception/phpbuiltinserver (Start and stop PHP built-in web server for your tests)
codeception/base suggests installing flow/jsonpath (For using JSONPath in REST module)
codeception/base suggests installing phpseclib/phpseclib (for SFTP option in FTP Module)
codeception/base suggests installing league/factory-muffin (For DataFactory module)
codeception/base suggests installing league/factory-muffin-faker (For Faker support in DataFactory module)
codeception/base suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
codeception/base suggests installing stecman/symfony-console-completion (For BASH autocompletion)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
> yii\composer\Installer::postCreateProject
chmod('runtime', 0777)...done.
chmod('web/assets', 0777)...done.
chmod('yii', 0755)...done.
> yii\composer\Installer::postInstall

**Comment by samdark** [comment]
Tried locally:

![image](https://user-images.githubusercontent.com/47294/67562137-db34cf80-f726-11e9-86d6-bb7b535db995.png)

Likely something is stuck in composer cache...
