### ISSUE TITLE
restful model , RateLimiter how do visitors limit access rates?

### ISSUE THREAD

**Issue by masonerQ** [yiisoft/yii2#17643]
new feature requests !!
### What steps will reproduce the problem?
\yii\filters\RateLimiter 
i can set identify user limit access rates   only  !
but how do visitors limit access rates?

### What is the expected result?
restful model  limit visitor access rate

### What do you get instead?
There is no alternative case   or   overwirte

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29-dev
| PHP version      |  7.3.4-nts
| Operating system | win10 x64  1903 18362.418

**Comment by samdark** [comment]
What's your use case for limiting anonymous user requests? Is it about DOS / DDOS? If so then it won't work as a request would still hit the application and PHP. There should be overall request limit set on lower level such as load balancer that is sufficiently high not to cause problems during normal operation but enough to cut traffic your application can not handle and send warnings about it happening.
