### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by RichWeber** [yiisoft/yii2#17651]
There is not a stable package for Yii2 requirements.

https://asset-packagist.org/package/bower-asset/inputmask

<img width="584" alt="Знімок екрана 2019-10-31 14 44 40" src="https://user-images.githubusercontent.com/1702252/67947776-159de100-fbed-11e9-8ffc-d65fe2f99a91.png">

The first stable version starts from V4.0.0

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.x-dev requires bower-asset/inputmask ~3.2.2 | ~3.3.5 -> no matching package found.
    - yiisoft/yii2 2.0.29 requires bower-asset/inputmask ~3.2.2 | ~3.3.5 -> no matching package found.
    - Installation request for yiisoft/yii2 ~2.0.29 -> satisfiable by yiisoft/yii2[2.0.29, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

**Comment by RichWeber** [comment]
A temporary solution is: `"bower-asset/inputmask": "4.0.0 as 3.3.5"`

**Comment by vadim-bulochnik** [comment]
Was fixed. Now all versions of "bower-asset/inputmask" available: https://asset-packagist.org/package/bower-asset/inputmask

**Comment by SilverFire** [comment]
![image](https://user-images.githubusercontent.com/4499203/67948815-2f402800-fbef-11e9-8621-ebc404258fb3.png)

Yes, works as should

**Comment by samdark** [comment]
I confirm that it currently cannot be reproduced.
