### ISSUE TITLE
Session not initializing until user call

### ISSUE THREAD

**Issue by csiocompany** [yiisoft/yii2#17659]
For production server commented these rows on index file:

```php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```

After that, user session become unavailable on bootstrap loading until Yii::$app->user->isGuest call.

```php
class Onload implements \yii\base\BootstrapInterface
{
	public function bootstrap($app)
	{
		$app->session->id; // Empty Session Id

		$app->user->isGuest;

		$app->session->id; // Not Empty
	}
}
```

**Comment by alex-code** [comment]
- Which session component are you using?
- How was `id` set in the session?
- Are you trying to get a user id?

**Comment by csiocompany** [comment]
Here is my session config:

```php
'session' => [
	'name' => 'session_name',
	'cookieParams' => [
		'domain' => '.domain.name',
		'httpOnly' => true,
	]
]
```

I thougt session ID must set automatically, so it does.

I am trying to get session ID.

**Comment by alex-code** [comment]
Ah, `session->id` doesn't initialise the session.
Not sure if this could be classed as a bug or not.

You can open the session yourself though.
```php
public function bootstrap($app)
{
  $app->session->open();
  $app->session->id;
}
```

**Comment by csiocompany** [comment]
I understand that call of session ID can not initialize the session, but bug is that, when these initial debug rows are present (not commented):

```php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```

the session is opens by itself.

**Comment by alex-code** [comment]
Can you show your config?
Can only guess something else is causing the session to load under debug conditions.

**Comment by samdark** [comment]
That is likely debugger triggers session start. It is by design not to start session before it is needed.
