### ISSUE TITLE
Your requirements could not be resolved to an installable....

### ISSUE THREAD

**Issue by michal-pikosz** [yiisoft/yii2#17650]
After composer create-project --prefer-dist yiisoft/yii2-app-basic basic2 i get this message
![image](https://user-images.githubusercontent.com/56221550/67947668-7117a100-fbe4-11e9-975a-34b49310ad68.png)
Usually the operation works properly, something has changed?

**Comment by SilverFire** [comment]
![image](https://user-images.githubusercontent.com/4499203/67948815-2f402800-fbef-11e9-8621-ebc404258fb3.png)

Should work fine now, could you try, please?

**Comment by samdark** [comment]
Can not reproduce with:

```
composer clearcache
composer create-project --prefer-dist yiisoft/yii2-app-basic basic2
```
