### ISSUE TITLE
feature requests: use query->indexBy for dataProvider->key

### ISSUE THREAD

**Issue by kambizzandi** [yiisoft/yii2#17655]
Hi

I have a question that could be a feature:
when I use $query->indexby(anotherField),  it is better $dataProvider using 'anotherField' as key and then $dataProvider->getKeys() returns indexed keys.

At now I use this code for covering this issue:
`$dataProvider->key = $dataProvider->query->indexBy;`
and then:
`var_dump($dataProvider->getKeys());`

Thanks for great Framework

**Comment by alex-code** [comment]
My understanding,

If the provided `ActiveQuery` has an `indexBy` set the `ActiveDataProvider` should set its `->key` property to the same `indexBy`.
