### ISSUE TITLE
Subquery support in conditional operator

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#17669]
Have an SQL:

```sql
SELECT * FROM table WHERE (select subquery) > 5
```

Let's build:
```php
(new Query())->from($table)->where(['>', $subQuery, 5]);
```
The second argument support Expression, but not QueryInterface :(

Current workaround is:
```php
$expression = new Expression('(' . $subQuery->createCommand()->rawSql . ')');
(new Query())->from($table)->where(['>', $expression, 5]);
```

I think Yii can support this wothowt workaround needs :))

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29
| PHP version      |  7.3

**Comment by samdark** [comment]
Is there a way to achieve it without breaking backwards compatibility?

**Comment by batyrmastyr** [comment]
But Yii 2.0.29 supports QueryInterface as second parameter
```
$subQuery = (new Query())->from('src')->select('bla')->limit(1);
$query = (new Query())->from('test')->where(['>', $subQuery, 5])->all();
```
produces `SELECT * FROM "test" WHERE (SELECT "bla" FROM "src" LIMIT 1) > 5`

**Comment by dicrtarasov** [comment]
> Is there a way to achieve it without breaking backwards compatibility?

it does not break comapibility, but add a new thing

**Comment by dicrtarasov** [comment]
> But Yii 2.0.29 supports QueryInterface as second parameter
> 
> ```
> $subQuery = (new Query())->from('src')->select('bla')->limit(1);
> $query = (new Query())->from('test')->where(['>', $subQuery, 5])->all();
> ```
> 
> produces `SELECT * FROM "test" WHERE (SELECT "bla" FROM "src" LIMIT 1) > 5`

yes, it worked
sorry, before I got some error when using subquery in conditionals, so decided it not supported.
sorry, please close this issue
