### ISSUE TITLE
CTE usage on ActiveRecords (mysql / mariadb)

### ISSUE THREAD

**Issue by sebathi** [yiisoft/yii2#17662]
There is no way to use Common Table Expressions with the actual Database Query implementation.

### Additional info

We should add the functionality similar to:

```php
(new Query)->addCTE(string $name, string|yii\db\Expression $cteQuery, bool $recursive)->....
```

We implemented it for our work and will make a pull request for it if you want.

**Comment by samdark** [comment]
Are CTE supported by all databases Yii provides support for?

**Comment by alex-code** [comment]
These are the min versions I could find,

MySQL 8 - https://dev.mysql.com/doc/refman/8.0/en/with.html
MariaDB 10.2.2 https://mariadb.com/kb/en/library/with/
SQLite 3.8.3 - http://www.sqlite.org/releaselog/3_8_3.html
PostgreSQL 9.4? - https://www.postgresql.org/docs/9.4/queries-with.html
Cubrid 10.1 - https://www.cubrid.org/manual/en/10.1/sql/query/cte.html
MSSQL 2005

**Comment by samdark** [comment]
@sebathi in general, enhancements aren't accepted into 2.0 anymore. How about releasing it as an extension?
