### ISSUE TITLE
Support Forwarded header (RFC 7239 section 4)

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#17665]
### What steps will reproduce the problem?
Make request through [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)
### What is the expected result?
Yii should get user IP, hostname and whether it is HTTP or HTTPS from Forwarded header
### What do you get instead?
Yii thinks that Ingress was requester, it is HTTP always

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29
| PHP version      | 7.2.24
| Operating system | Docker 7.2-fpm-alpine

https://tools.ietf.org/html/rfc7239#section-4
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded

**Comment by kamarton** [comment]
See https://www.yiiframework.com/doc/guide/2.0/en/runtime-requests#trusted-proxies

**Comment by mikk150** [comment]
> See https://www.yiiframework.com/doc/guide/2.0/en/runtime-requests#trusted-proxies

I know that, but it does not help

**Comment by samdark** [comment]
That is definitely something we want in Yii 3. Not sure it could be considered a bug not supporting it...

**Comment by mikk150** [comment]
> That is definitely something we want in Yii 3. Not sure it could be considered a bug not supporting it...

what if I told you that I am already trying to implement it

**Comment by samdark** [comment]
@mikk150 for Yii 3?

**Comment by mikk150** [comment]
> @mikk150 for Yii 3?

No, for Yii2, but it can be copied to that middleware

**Comment by samdark** [comment]
OK. If there will be no BC breaks then we'd consider it for Yii 2 as well.
