### ISSUE TITLE
SQL Command with table prefix notation on schame.tablename prefixes schema, not tablename

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#17664]
### What steps will reproduce the problem?

Create a migration like this one:

```php
	public function safeUp()
	{
                 $this->db->tablePrefix="tbl_";
		$this->createTable('{{%mychema.users}}', [
			'id' => $this->primaryKey(),
			'email => $this->string(100)->null(),
                 ]);
         }
```

### What is the expected result?

A table `tbl_users` in schema `myschema` is created.

### What do you get instead?

```sql
    > create table {{%mychema.users}} ...Exception: SQLSTATE[HY000]: General error: 1 unknown database `tbl_mychema`
Failed to prepare SQL: CREATE TABLE `tbl_mychema`.`users` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`email` varchar(100) NULL DEFAULT NULL
) (.../vendor/yiisoft/yii2/db/Command.php:264)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30-dev
| PHP version      |  7.3
| Operating system | Linux Debian 10

**Comment by rob006** [comment]
This is expected - you're using explicit quoting, so quotes are added as you requested (in place of `{{` and `}}`). Did you tried `{{%mychema}}.{{%users}}`?

**Comment by santilin** [comment]
It works like a charm :)
