### ISSUE TITLE
Javascript registered in renderDynamic doesn't appear anywhere when PageCache is used

### ISSUE THREAD

**Issue by nagyt234** [yiisoft/yii2#17673]
JS or CSS registered with registerJS, registerJSFile etc will not work in renderDynamic. This problem causes, that it is not possible to use any widgets in `renderDynamic` on a cached page which has JavaScript or CSS assets. This issue is basically #16051 re-opened with simple step-step reproducing.

### What steps will reproduce the problem?

1. Create a YII2 system with the Basic Template and go there:
```
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
cd basic
```
2. Add the following line as line 2 in `views/site/index.php`:
```
$this->renderDynamic('$this->registerJs("alert(\'JS started\')");');
```
3. Start the simple WEB server
```
php yii serve --port=8888
```
4. Go in browser to http://localhost:8888 Te alert box will appear, and you can find the following lines also in the page source:
```
<script src="<script>jQuery(function ($) {
alert('JS started')
});</script>
```
5. Now add PageCache to the Index action. Add the following code in the function `behaviors` in  `controllers/SiteController.php`:
```
'indexCache' => [ 
    'class' => 'yii\filters\PageCache',
    'only' => ['index'],
    'duration' => 86400,    // 1 day
    'enabled' => true,
],
```
6. Check again the Home page. The JS code and the alert IS NOT INCLUDED anymore.

### What is the expected result?
The registered JavaScript  should appear in the HTML page.
### What do you get instead?
All Javascript registered in renderDynamic is missing.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29
| PHP version      |  PHP 7.2.24-1+ubuntu16.04.1+deb.sury.org+1
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
@yiisoft/reviewers what do you think?

**Comment by schmunk42** [comment]
I'd not change the default behavior for Yii 2.x (as always :smiley:) - if available, it should be optional.

**Comment by samdark** [comment]
Overall it looks like a massive change in behavior so I agree it's not a good idea to solve it like that.

@nagyt234 I'm closing the issue as "won't fix" but if there's a way I can't see please let me know.

**Comment by nagyt234** [comment]
OK, I agree, that to solve this issue generally is very difficult and would decrease the effectiveness of the cache. But than at least the documentation of renderDynamic should mention, that the functions `register...` have no effect.
What could be quite easy, if we would have a 2nd set of functions, like `register...Dynamic` which could work also with placeholders and with the limitation that assets already on the cached page are not analyzed.

**Comment by samdark** [comment]
Where would you document that? Actually too many methods do not work with dynamic rendering. Basically everything except meta-tags.

**Comment by nagyt234** [comment]
@samdark I would write exactly what you wrote here in [the description of renderDynamic](https://www.yiiframework.com/doc/api/2.0/yii-base-view#renderDynamic()-detail) and probably in  [The Definitive Guide to Yii 2.0](url):

Methods that indirectly modify layout (registerJS, registerJSFile, etc.)  do not work with dynamic rendering. Basically everything except meta-tags.
