### ISSUE TITLE
header already sent

### ISSUE THREAD

**Issue by fsnightmckngbrd** [yiisoft/yii2#17674]
### What steps will reproduce the problem?
Using mpdf or tcpdf, when downloading the pdf generated. Reading the pdf file on a text editor always have an error or exception that says that headers were already sent.
### What is the expected result?
Clean pdf without error
### What do you get instead?
Pdf with inserted exception at the end of file.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29
| PHP version      | 7.0.33
| Operating system | Ubuntu 16.04.5

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/15816
