### ISSUE TITLE
Catching database connection errors fails

### ISSUE THREAD

**Issue by Geowan** [yiisoft/yii2#17682]
I would like to catch the database connection failure and handle it in a different way by throwing an error with a custom message. In my code i have added

          try {
                if (!Yii::$app->db->isActive) {
                    Yii::$app->db->open();
                }
                
            }catch (\yii\db\Exception $e){

                throw new UserException("Invalid database connection",2030);
            }

So am basically trying to catch the database connection failed and throw a message with 2030 code where i can listen for this in my vuejs(frontend) app.

The above doesnt throw the new user exception but rather throws 500 error with 
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) 
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0
| Operating system | ubuntu

**Comment by samdark** [comment]
Can you supply us with a stacktrace?

**Comment by Geowan** [comment]
This is my stacktrace

An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php:698
Stack trace:
#0 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php(698): PDO->__construct('mysql:host=loca...', 'root', '5378@Geowan5378', NULL)
#1 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php(624): yii\db\Connection->createPdoInstance()
#2 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php(1015): yii\db\Connection->open()
#3 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php(1002): yii\db\Connection->getMasterPdo()
#4 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Command.php(253): yii\db\Connection->getSlavePdo()
#5 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Command.php(1153): yii\db\Command->prepare(true)
#6 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#7 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/mysql/Schema.php(319): yii\db\Command->queryAll()
#8 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/mysql/Schema.php(125): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#9 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Schema.php(754): yii\db\mysql\Schema->loadTableSchema('users')
#10 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Schema.php(193): yii\db\Schema->getTableMetadata('{{%users}}', 'schema', false)
#11 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(435): yii\db\Schema->getTableSchema('{{%users}}')
#12 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(262): yii\db\ActiveRecord::getTableSchema()
#13 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(234): yii\db\ActiveRecord::filterValidColumnNames(Object(yii\db\Connection), Array)
#14 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(191): yii\db\ActiveRecord::filterCondition(Array, Array)
#15 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#16 /home/geowan/Desktop/devapps/envanto-projects/freelancer/models/UserIdentity.php(53): yii\db\BaseActiveRecord::findOne(Array)
#17 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/User.php(690): app\models\UserIdentity::findIdentity(1)
#18 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/User.php(192): yii\web\User->renewAuthStatus()
#19 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#20 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#21 /home/geowan/Desktop/devapps/envanto-projects/freelancer/views/layouts/main.php(44): yii\base\Component->__get('isGuest')
#22 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/View.php(348): require('/home/geowan/De...')
#23 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/geowan/De...', Array)
#24 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Controller.php(401): yii\base\View->renderFile('/home/geowan/De...', Array, Object(app\controllers\SiteController))
#25 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Controller.php(387): yii\base\Controller->renderContent('<div class="sit...')
#26 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#27 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#28 [internal function]: yii\web\ErrorAction->run()
#29 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#30 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#31 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('error', Array)
#32 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#33 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UserException))
#34 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\UserException))
#35 {main}

Next yii\db\Exception: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php:635
Stack trace:
#0 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php(1015): yii\db\Connection->open()
#1 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Connection.php(1002): yii\db\Connection->getMasterPdo()
#2 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Command.php(253): yii\db\Connection->getSlavePdo()
#3 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Command.php(1153): yii\db\Command->prepare(true)
#4 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/mysql/Schema.php(319): yii\db\Command->queryAll()
#6 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/mysql/Schema.php(125): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#7 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Schema.php(754): yii\db\mysql\Schema->loadTableSchema('users')
#8 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/Schema.php(193): yii\db\Schema->getTableMetadata('{{%users}}', 'schema', false)
#9 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(435): yii\db\Schema->getTableSchema('{{%users}}')
#10 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(262): yii\db\ActiveRecord::getTableSchema()
#11 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(234): yii\db\ActiveRecord::filterValidColumnNames(Object(yii\db\Connection), Array)
#12 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/ActiveRecord.php(191): yii\db\ActiveRecord::filterCondition(Array, Array)
#13 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#14 /home/geowan/Desktop/devapps/envanto-projects/freelancer/models/UserIdentity.php(53): yii\db\BaseActiveRecord::findOne(Array)
#15 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/User.php(690): app\models\UserIdentity::findIdentity(1)
#16 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/User.php(192): yii\web\User->renewAuthStatus()
#17 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#18 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#19 /home/geowan/Desktop/devapps/envanto-projects/freelancer/views/layouts/main.php(44): yii\base\Component->__get('isGuest')
#20 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/View.php(348): require('/home/geowan/De...')
#21 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/geowan/De...', Array)
#22 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Controller.php(401): yii\base\View->renderFile('/home/geowan/De...', Array, Object(app\controllers\SiteController))
#23 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Controller.php(387): yii\base\Controller->renderContent('<div class="sit...')
#24 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#25 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#26 [internal function]: yii\web\ErrorAction->run()
#27 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#28 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#29 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('error', Array)
#30 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#31 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UserException))
#32 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\UserException))
#33 {main}
Additional Information:

Previous exception:
yii\base\UserException: Invalid database connection in /home/geowan/Desktop/devapps/envanto-projects/freelancer/modules/api/Api.php:31
Stack trace:
#0 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/BaseObject.php(109): app\modules\api\Api->init()
#1 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#2 [internal function]: yii\base\Module->__construct('api', Object(yii\web\Application), Array)
#3 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/di/Container.php(392): ReflectionClass->newInstanceArgs(Array)
#4 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('app\\modules\\api...', Array, Array)
#5 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->get('app\\modules\\api...', Array, Array)
#6 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#7 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Module.php(586): yii\base\Module->getModule('api')
#8 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('v1/setup/databa...')
#9 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('api/v1/setup/da...', Array)
#10 /home/geowan/Desktop/devapps/envanto-projects/freelancer/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /home/geowan/Desktop/devapps/envanto-projects/freelancer/web/index.php(13): yii\base\Application->run()
#12 {main}

**Comment by Geowan** [comment]
The above code is added on the module class that is

       public function init()
       {
        parent::init();
         try {
            if (!Yii::$app->db->isActive) {
                Yii::$app->db->open();
            }
            
        }catch (\yii\db\Exception $e){

            throw new UserException("Invalid database connection",2030);
        }

        //my modules
        $this->modules =[
            'v1' => [
                'class' => 'app\modules\api\v1\V1',
            ],
        ];
    }

**Comment by Geowan** [comment]
I have realized i needed to set the response format to json that is 
 \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

And now it shows the correct code and message
