### ISSUE TITLE
Invalid rbac migration m180523_151638_rbac_updates_indexes_without_prefix

### ISSUE THREAD

**Issue by rvkulikov** [yiisoft/yii2#17685]
### What steps will reproduce the problem?

(tl;dr):
Look at the following lines:
1.  This one is good https://github.com/yiisoft/yii2/blob/943101255d938ed6aeec4578d4d6d9b3e01a61d3/framework/rbac/migrations/m140506_102106_rbac_init.php#L52
2. This is good too https://github.com/yiisoft/yii2/blob/943101255d938ed6aeec4578d4d6d9b3e01a61d3/framework/rbac/migrations/m170907_052038_rbac_add_index_on_auth_assignment_user_id.php#L45
3. **This is bad** https://github.com/yiisoft/yii2/blob/943101255d938ed6aeec4578d4d6d9b3e01a61d3/framework/rbac/migrations/m180523_151638_rbac_updates_indexes_without_prefix.php#L39-L48

---

Third migration uses **default** db component (which may be different from **authManager's** db component). And if you use 2 db components, and authManager (DbManager) uses non-default `db` component, then third migration will just fail (it is good fortune that it just drops some indexes).

Please tell if it's not clear how to reproduce the problem and I'll write more details.

**Comment by rvkulikov** [comment]
The workaround is obvious:

`~/app/config/main.php`
```php
//...
    'container' => [
        'definitions' => [
            'm180523_151638_rbac_updates_indexes_without_prefix' => [
                'class' => 'm180523_151638_rbac_updates_indexes_without_prefix',
                'db' => 'proper_db_component'
            ],
        ]
    ],
//...
```

But I think it's not good. It's better to fix migration than to override migration default in every app.

**Comment by samdark** [comment]
@rvkulikov do you want to prepare a pull request?

**Comment by rvkulikov** [comment]
@samdark OK.
