### ISSUE TITLE
Unable to determine the entry script URL when using AWS Lambda

### ISSUE THREAD

**Issue by jasonmccallister** [yiisoft/yii2#17681]
# What steps will reproduce the problem?

- Follow the instructions on setting up Yii as a micro framework
- Deploy application to Lambda using Bref.sh

### What is the expected result?

Lambda (bref) creates an endpoint to handle all traffic. When you visit the `/dev` URL you should see the endpoints that are defined by the Yii application. 

### What do you get instead?

We get the following error: 
```
Invalid Configuration – yii\base\InvalidConfigException
Unable to determine the entry script URL.
```

When executing [the following function](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L814) to get the script. It is caught in an exception as the `$_SERVER` conditions do not match.

### Temporary Solution

We can resolve this using two methods, both are not ideal:

- Adding `dev/index.php` to the request URI
- Setting `$_SERVER['ORIG_SCRIPT_NAME']` to the file, but could be cumbersome

However when exploring the `$_SERVER` output on Lambda, there are the following that point to the `index.php`

- `$_SERVER['SCRIPT_FILENAME'] => '/var/task/web/index.php'`
- `$_SERVER['REQUEST_URI'] => 'index.php'`

### Recommendation

The `getScriptUrl` should also check for the above variables when running. Happy to make a PR, but not sure which method would be preferred?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.015?
| PHP version      | 7.3.7
| Operating system | AWS Lambda/Bref

**Comment by samdark** [comment]
ORIG_SCRIPT_NAME is a fallback that is used in case SCRIPT_NAME or PHP_SELF are empty: https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L814

**Comment by samdark** [comment]
It's not possible to determine script automatically since the info is, indeed, missing (`SCRIPT_FILENAME` is about file name, not URI and it's already used in the process. `REQUEST_URI` is different as well).

How about configuring it manually?

```php
'components' => [
    'request' => [
        'scriptUrl' => 'here',
    ],
]
```

**Comment by jasonmccallister** [comment]
I’ll give that a try.. I wonder if that is swine thing we can resolve, or should resolve, with the Bref runtime?

**Comment by samdark** [comment]
I'm not sure if Bref runtime has the concept of script URI that is usually available via `SCRIPT_NAME`, `PHP_SELF` or `ORIG_SCRIPT_NAME`. Maybe @mnapoli knows...

**Comment by mnapoli** [comment]
🤔  mmh that's interesting. The goal with Bref (or rather the PHP-FPM runtime of Bref) is that your application runs in an environment that is just like any other server.

Is `$_SERVER['SCRIPT_NAME']` a variable that is always set with Apache or Nginx? If yes, we can definitely add it in Bref.

**Comment by jasonmccallister** [comment]
Pulled this from the [PHP website](https://www.php.net/manual/en/reserved.variables.server.php):

> 'SCRIPT_NAME' 
> Contains the current script's path. This is useful for pages which need to point to themselves. The __FILE__ constant contains the full path and filename of the current (i.e. included) file.

**Comment by samdark** [comment]
@mnapoli it is.

**Comment by jasonmccallister** [comment]
@samdark I feel like I am constantly in your issues inbox lately :)

I have uploaded the example code where I am walking through deploying [Yii 2 on Lambda](https://github.com/jasonmccallister/yii2-on-lambda). 

I added overrode the request component to hard code the `scriptUrl` and deployed the application here: https://b6r0dbi47k.execute-api.us-east-1.amazonaws.com/dev

No surprise, it worked with the override but wanted to provide the example app for everyone to see.

**Comment by samdark** [comment]
Cool. A tutorial about the topic would be very cool to have.

**Comment by samdark** [comment]
Seems that entry script problem is decided. Closing the issue.

**Comment by dersonsena** [comment]
@jasonmccallister Just to register here, I found a way to simulate a request with few lines. In my case, I'm creating a real Web Application to run tests with PHP Unit and a put this one in PHP Unit bootstrap file:

```php
$_SERVER['SCRIPT_FILENAME'] = __FILE__;
$_SERVER['SCRIPT_NAME'] = 'bootstrap.php';
$_SERVER['REQUEST_URI'] = 'http://localhost';
$_SERVER['PHP_SELF'] = 'bootstrap.php';
```
