### ISSUE TITLE
Having trouble using loadMultiple

### ISSUE THREAD

**Issue by fsnightmckngbrd** [yiisoft/yii2#17695]
### What steps will reproduce the problem?
Here is a sample code of what I am posting using ajax :
```javascript
var input_value;

input_value.push({
    id: field.data("value-id"),
    val: field.html()
});

data = {
   data1 : {
       _csrf: csrfToken,
       DocumentTemplateValue: input_value
   }
};
```

DocumentTemplateValue[0][id] : 50
DocumentTemplateValue[0][val] : value50
DocumentTemplateValue[1][id] : 51
DocumentTemplateValue[1][val] : value51
DocumentTemplateValue[2][id] : 52
DocumentTemplateValue[2][val] : value52
DocumentTemplateValue[3][id] : 54
DocumentTemplateValue[3][val] : value54
DocumentTemplateValue[4][id] : 55
DocumentTemplateValue[4][val] : value55

### What is the expected result?
I should get the same data that I've posted.

DocumentTemplateValue[0][id] : 50
DocumentTemplateValue[0][val] : value50
DocumentTemplateValue[1][id] : 51
DocumentTemplateValue[1][val] : value51
DocumentTemplateValue[2][id] : 52
DocumentTemplateValue[2][val] : value52
DocumentTemplateValue[3][id] : 54
DocumentTemplateValue[3][val] : value54
DocumentTemplateValue[4][id] : 55
DocumentTemplateValue[4][val] : value55

### What do you get instead?
After getting the json returned after using loadMultiple. Here is what I get:

DocumentTemplateValue[0][id] : 50
DocumentTemplateValue[0][val] : value50
DocumentTemplateValue[1][id] : 51
DocumentTemplateValue[1][val] : value51
DocumentTemplateValue[2][id] : 52
DocumentTemplateValue[2][val] : value52
DocumentTemplateValue[3][id] : 53
DocumentTemplateValue[3][val] : value54
DocumentTemplateValue[4][id] : 54
DocumentTemplateValue[4][val] : value55

As you can see, I've skipped **id: 53** when I posted but I received it in json having the value of **id: 54**. Seems like loadMultiple creates its own sequence which starts at the minimum pkey that was posted that causes my data to move when updating.

Am I correct? Is there any workaround to it? Thanks!

**Comment by samdark** [comment]
Would be great to dig a little bit further into PHP part of it. What does it receive in POST?

**Comment by fsnightmckngbrd** [comment]
Here is the PHP part after posting :

```
$transaction = Yii::$app->db->beginTransaction();
$post = Yii::$app->request->post();

$document = new Document();
$document = $document->findOne($id);

// Get all related document value
$document_value = $document->documentValue;

// Load posted data on the document value
if (Model::loadMultiple($document_value, $post['data1])) {
    foreach ($document_value as $value) {

        // Some conditions before saving that does not affect each value,
        if ($value->save()) {
            $transaction->commit();
        }
        else {
            $transaction->rollback();
        }
    }
}
```

**Comment by samdark** [comment]
I've meant var_dump($_POST);

**Comment by fsnightmckngbrd** [comment]
Here is the var_dump

![posted data (1)](https://user-images.githubusercontent.com/30925981/69864574-36378480-12da-11ea-9ae8-5df435bd4318.png)
![json returned](https://user-images.githubusercontent.com/30925981/69864575-36d01b00-12da-11ea-9617-68cec6839b3d.png)

**Comment by samdark** [comment]
Looks wrong. Can you do a reproduce-able test case? Starting with basic application template, a single table and such action in controller.

Or a unit test if you prefer so.

**Comment by alex-code** [comment]
I'm guessing because this relation
```php
// Get all related document value
$document_value = $document->documentValue;
```
returns more records than you're sending with the POST is the issue.

Using the PK as the index might work.
So index the `documentValue` relation by the PK and use that in the post too.
e.g.
```
DocumentTemplateValue[50][val] : value50
DocumentTemplateValue[51][val] : value51
DocumentTemplateValue[52][val] : value52
DocumentTemplateValue[54][val] : value54
DocumentTemplateValue[55][val] : value55
```

**Comment by fsnightmckngbrd** [comment]
> 
> 
> I'm guessing because this relation
> 
> ```
> // Get all related document value
> $document_value = $document->documentValue;
> ```
> 
> returns more records than you're sending with the POST is the issue.
> 
> Using the PK as the index might work.
> So index the `documentValue` relation by the PK and use that in the post too.
> e.g.
> 
> ```
> DocumentTemplateValue[50][val] : value50
> DocumentTemplateValue[51][val] : value51
> DocumentTemplateValue[52][val] : value52
> DocumentTemplateValue[54][val] : value54
> DocumentTemplateValue[55][val] : value55
> ```

That was my first approach. Posted data were not loaded using loadMultiple if I use PK on index of posted data.

#17654

**Comment by alex-code** [comment]
It just loads the data in the order it comes. It doesn't match on PK's.

You'd need to index the model instances you pass into `loadMultiple` too.

**Comment by samdark** [comment]
Yeah. Seems it works as designed.
