### ISSUE TITLE
ActiveRecord don't execute request if use DBExpression in the bind params section?

### ISSUE THREAD

**Issue by s1lver** [yiisoft/yii2#17690]
For example you need to get a record from a table for a specific month

### What steps will reproduce the problem?
```php
$year = $year??new Expression('YEAR(NOW())');
$test = Test::find()
            ->where('MONTH(date) = :month', [':month' => $month])
            ->andWhere('YEAR(date) = :year', [':year' => $year]);
```

### What is the expected result?
```php
var_dump($test->count()); //0
var_dump($test->one()); //NULL
```

### What do you get instead?
```php
var_dump($test->count()); //100
var_dump($test->one()); //TestModel
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30
| PHP version      | 7.3.11
| Operating system | Ubuntu 19

**Comment by alex-code** [comment]
If you need a way round this should work.
```php
$test = Test::find()
  ->where(['MONTH(date)' => $month])
  ->andWhere(['YEAR(date)' => $year ?? new Expression('YEAR(NOW())')]);
```

**Comment by samdark** [comment]
I don't think PDO is able to bind expressions.

**Comment by alex-code** [comment]
@samdark You're right, the PDO docs don't seem to mention anything explicitly but a bound string value would be quoted by PDO so an `Expression` won't work as intended.

My suggestion works, maybe we include a note on the Yii docs about named params and expressions?

**Comment by s1lver** [comment]
Does not, but is inside the SQL generation is correct. Not written anywhere, but wants to.I think maybe we should add?

**Comment by samdark** [comment]
In case of prepared statements thus values can't be part of SQL query. SQL would be

```sql
SELECT *
FROM test
WHERE MONTH(date) = :month
AND YEAR(date) = :year
```
