### ISSUE TITLE
Javascript in error page

### ISSUE THREAD

**Issue by Fr1ar** [yiisoft/yii2#17694]
Let's assume I want to render a simple view:
```
<?php
$this->registerJs('alert("Hello!")');

// And an unhandled exception is thrown during the view (or layout) rendering:
throw new Exception('Opps');
```

If YII_DEBUG is false than I see the error page rendered by yii\web\ErrorAction, but I also see a "Hello!" message, which means that JS code was included into error page. Is it supposed to be like that?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.27
| PHP version      | 7.3.11
| Operating system |CentOS 7

**Comment by alex-code** [comment]
Maybe the assets should be cleared before the error view is rendered?
Might cause an issue if any of those assets are needed to render the layout though.

**Comment by bizley** [comment]
This is similar to #16101 which I thought I've fixed a year ago...

**Comment by alex-code** [comment]
@bizley Looks like this occurs if you use the `ErrorAction` option so it's rendered differently.
```php
'errorHandler' => [
  'errorAction' => 'site/error',
],
```
