### ISSUE TITLE
use where function after where , andWhere , orWhere remove condition

### ISSUE THREAD

**Issue by hoesm** [yiisoft/yii2#17707]
use where function after where , andWhere , orWhere remove conditions

set default condition and use where on query , remove default condition

### What is the expected result?
throw hew  Exception

### What do you get instead?
 // yii\db\Query -> where function
public function where($condition, $params = [])
    {
        if($this->where)
        {
            throw new Exception('message');
         }
        $this->where = $condition;
        $this->addParams($params);
        return $this;
    }

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30
| PHP version      |  7.2.4
| Operating system | windows 10

**Comment by alex-code** [comment]
This is in the docs, https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#where()-detail
Using `->where()` will overwrite any previously set conditions.
