### ISSUE TITLE
php7.4 Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by y284663247** [yiisoft/yii2#17705]
### What steps will reproduce the problem?
layout view add the js script like 
`<?= $this->blocks['js'] ?>`
### What is the expected result?
`PHP Notice – yii\base\ErrorException
Trying to access array offset on value of type null`
![image](https://user-images.githubusercontent.com/7445875/70027751-caa52e00-15dd-11ea-9a4a-1d09cbb35707.png)
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30
| PHP version      | 7.4
| Operating system |Darwin / 18.7.0

**Comment by alex-code** [comment]
Have you created a block widget?

**Comment by samdark** [comment]
Related to #17698

**Comment by samdark** [comment]
Checked it. The error is there both in pre-7.4 and 7.4 in case block is not defined. That is expected.

**Comment by y284663247** [comment]
![image](https://user-images.githubusercontent.com/7445875/70760880-2b72fa00-1d86-11ea-9d91-b8ac59507f8e.png)
![image](https://user-images.githubusercontent.com/7445875/70760897-3f1e6080-1d86-11ea-8677-6b793c0a527f.png)
![image](https://user-images.githubusercontent.com/7445875/70760917-49d8f580-1d86-11ea-8f4a-7aeaefccf15c.png)

now php7.2 no error show

**Comment by alex-code** [comment]
https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access

Maybe the `blocks` property should be initialised by default to an empty array.

**Comment by samdark** [comment]
@alex-code then it would say that you're accessing non-existing key of an array.

**Comment by samdark** [comment]
@y284663247 do you have error reporting set to E_ALL?

**Comment by alex-code** [comment]
> @alex-code then it would say that you're accessing non-existing key of an array.

That's true 👍

**Comment by ruikc** [comment]
> @y284663247 do you have error reporting set to E_ALL?

php 8.0 have the same error; error reporting set to E_ALL;
