### ISSUE TITLE
Saving json encoded array in MySQL json column adds double quotes

### ISSUE THREAD

**Issue by chrisc0** [yiisoft/yii2#17712]
There seems to be a problem saving arrays to a MySQL json field.

### What steps will reproduce the problem?
$userArray = [100, 101, 102];
$model->arrayField = json_encode($userArray);   // 'arrayField' is a json type column in the DB
$model->save();

### What is the expected result?
In MySQL the field should be [100,101,102]

### What do you get instead?
Instead, the json column now contains "[100,101,102]", including the double quotes.  The quotes should not be in the record.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30
| PHP version      | 7.3
| Operating system | Ubuntu 19.10

**Comment by kamarton** [comment]
The data is not decoded when queried, are you sure the value in the database is incorrect?

```php
$userArray = [100, 101, 102];
$model->arrayField = json_encode($userArray); // 'arrayField' is a json type column in the DB
$model->save();

$model = AR::findOne(...);
var_dump($model->arrayField);
// string "..."
```

**Comment by alex-code** [comment]
I think the framework encodes the values for you so you don't need to do `json_encode`.
By doing that you're passing in a string.

**Comment by chrisc0** [comment]
Using ActiveRecord exclusively is not the real issue.  The problem comes when I then use DAO to access the data.  Something like this:
$sql = "SELECT arrayField FROM some_table WHERE acct_id = 23";
$data = Yii::$app->db->createCommand($sql)->queryOne();
var_dump($data['arrrayField']);   // string '"[100, 101, 102]"'

Now it shows single quotes and double-quotes.

**Comment by chrisc0** [comment]
@alex-code I think you're right but when I do it without json_encode the model shows errors "arrayField must be a string".   I think the issue is with the validation.  I have arrayField validating with a "string" rule.  Is there a rule for json fields?

**Comment by kamarton** [comment]
```php
$sql = "SELECT arrayField FROM some_table WHERE acct_id = 23";
$data = Yii::$app->db->createCommand($sql)->queryOne();
var_dump($data['arrrayField']); // string '"[100, 101, 102]"'
```

Outside ActiveRecord, it is not possible to detect what the desired output is.

**Comment by samdark** [comment]
@kamarton is right. We can't fix it.

**Comment by Commifreak** [comment]
I believe I ran into the same issue. Its about storing data inside MySQL json column which has json type. The issue happens on my side as well with Yii 2.0.38.

I assign via `$model->json = $dataArray` which results in: 
```sql
INSERT INTO `log` (`user_id`, `model`, `data`, `created_at`) VALUES (1, 'common\\models\\MasterUser', CAST('\"{\\\"id\\\":1,\\\"type\\\":\\\"update\\\",\\\"changed\\\":{\\\"noMails\\\":[\\\"0\\\"],\\\"updated_at\\\":{\\\"1605615533\\\":1605615782}}}\"' AS JSON), 1605615782)
```

Forum post: https://forum.yiiframework.com/t/yii2-mysql-json-type-saved-double-encoded-in-db/130953

Maybe Im simply doing something wrong but I dont see it - yet. :)

**Comment by Commifreak** [comment]
Solved!

That was weird: I created another field for another model with json type as well and here it was working out-of-the-box. After digging deeper, I found an overwritten afterSave function iunside the problematic model which encoded the array still as json…

So, no problem here anymore, everything is working as expected!
