### ISSUE TITLE
yii\validators\InlineValidator method di

### ISSUE THREAD

**Issue by brussens** [yiisoft/yii2#17732]
When using the Inline Validator, no dependency injection through the method. It is quite a real solution to use `$container->invoke()` instead of `call_user_func_array()` in the following way:

InlineValidator changes
```php
...
use Yii;
...
class InlineValidator extends Validator
{
    ...
    public $params = [];
    ...
    public function validateAttribute($model, $attribute)
    {
        $method = $this->method;
        if (is_string($method)) {
            $method = [$model, $method];
        }
        Yii::$container->invoke($method, [
            'attribute' => $attribute,
            'params' => $this->params,
            'validator' => $this
        ]);
    }
    ...
}
```
This approach is quite useful if you need to use some services directly during validation, for example:
```php
class LoginForm extends Model
{
    ...
    public $password;
    ...
    public function rules()
    {
        return [
            ...
            ['password', 'validatePassword']
            ...
        ];
    }

    public function validatePassword(PasswordServiceInterface $passwordService, $attribute, $params, $validator)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            if (!$user || !$user->isPasswordRelevant($this->$attribute, $passwordService)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }
    ...
}
```

What do you think about that?

**Comment by samdark** [comment]
Since validation would likely happen at every usage of `LoginForm`, isn't it better to inject into its constructor?

**Comment by brussens** [comment]
We can use the constructor, of course, until there are no other dependencies in the constructor. And besides, the form is initialized without calling validation. Besides, the code is cleaner and more logical. In fact, `PasswordServiceInterface` is only needed to inject it further into the password verification method. I suppose it shouldn't be in the very object of the form logically. Although I may not have chosen a very good example)

**Comment by samdark** [comment]
> I suppose it shouldn't be in the very object of the form logically.

Then why do you inject it in the object in question?

**Comment by brussens** [comment]
I mean, this service will not be properly injected through the constructor. Introduction through the method is a bit cleaner and more understandable.

**Comment by samdark** [comment]
@yiisoft/reviewers what do you think?

**Comment by roxblnfk** [comment]
@samdark similar to named parameters in DI. it seems we have already discussed this?

**Comment by samdark** [comment]
No, that's not named ones. That's same reflection API as used in Yii 3 action methods.

**Comment by brussens** [comment]
@samdark At the moment I use this kind of implementation in projects through di.
```php
class InlineValidator extends \yii\validators\InlineValidator
{
    public $invoke = false;
   
    public function validateAttribute($model, $attribute)
    {
        $method = $this->method;
        if (is_string($method)) {
            $method = [$model, $method];
        }
        $params  =  [
            'attribute' => $attribute,
            'params' => $this->params,
            'validator' => $this
        ];
        if ($this->invoke) {
            Yii::$container->invoke($method, $params);
        } else {
            call_user_func_array($method, $params);
        }
    }
}
```

This approach is useful when you need to tighten some dependencies in certain scenarios. Why just use the constructor to pull up dependencies when you only need them when working with certain scenarios?

**Comment by viktorprogger** [comment]
I don't think this possibility will be often used, but it will be used if it will exist. I vote for the ability to use DI in the `InlineValidator`.

**Comment by samdark** [comment]
Did a draft PR but I can say that I don't really like it...

**Comment by brussens** [comment]
@samdark Tell me, what is it you don't like? I just want to understand for myself what's wrong with it.

**Comment by samdark** [comment]
I still doubt it will be used. In my opinion, having dependencies in the class itself and using them as `$this->something` is more than enough. If you're worrying about dependencies that aren't used most of the time, likely it's an indicator of the fact that the class being validated is doing too much i.e. "form model" should be extracted.

**Comment by brussens** [comment]
But I gave an example with the same form of authentication, where, for example, if you entered the wrong username, you wouldn't have to check the password at all and therefore the object isn't needed initially. Thus, injecting some objects directly into the method can really give you a profit.

**Comment by samdark** [comment]
In your example, instantiating `PasswordServiceInterface` is very lightweight. Also, it doesn't happen in a loop so that one class instantiation per HTTP request-response cycle. Not a solid reason to introduce extra way to inject dependencies.

**Comment by samdark** [comment]
Thought more about it. Decided that it doesn't worth it.
