### ISSUE TITLE
PHP version compatibility issue 

### ISSUE THREAD

**Issue by iSarahSajjad** [yiisoft/yii2#17738]
### What steps will reproduce the problem?
 On php yii serve PHP Fatal error:  Cannot use 'Object' as class name as it is reserved, I already searched on similar issue but unable to solve it. I choose different php version but problem remain constants. Im new to Yii. can you guys guide how to resolve this issue

| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | < 7.0 
| Operating system | Windows

**Comment by kamarton** [comment]
use [`yii\base\BaseObject`](https://www.yiiframework.com/doc/api/2.0/yii-base-baseobject) instaed of [`yii\base\Object`](https://www.yiiframework.com/doc/api/2.0/yii-base-object)

**Comment by iSarahSajjad** [comment]
where to add this?

**Comment by samdark** [comment]
Likely you're using outdated Yii version.

**Comment by iSarahSajjad** [comment]
How to update it im new in it. 
composer.json have already "yiisoft/yii2": "*",

**Comment by kamarton** [comment]
1. `composer update`
2. check yii version with command: `composer info | grep yiisoft/yii2`, or in developer panel left side
3. minimum version is 2.0.13, if this is not true then any package you are using requires an older version of yii.
