### ISSUE TITLE
yii\helpers\BaseInflector::slug() doesn't shrink multiple replacement occurences to single

### ISSUE THREAD

**Issue by batyrmastyr** [yiisoft/yii2#17740]
### What steps will reproduce the problem?
Inflector::slug(' _ _ remove excess _ _ replacements_', '_');
### What is the expected result?
remove_excess_replacements
### What do you get instead?
remove_excess_____replacements

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16-2.0.30 since #15204
| PHP version      | 7.0.33
| Operating system | Debian 7

**Comment by samdark** [comment]
While it's a good change as such and definitely should be applied to https://github.com/yiisoft/strings/blob/master/src/Inflector.php, changing the way how it works is a backwards compatibility break for Yii 2.

**Comment by samdark** [comment]
@batyrmastyr thanks for a good idea for Yii 3. Won't be merged into 2.0 though. Sorry.

**Comment by samdark** [comment]
Re-considered since it's 2.0.16 regression.
