### ISSUE TITLE
Let's add some types of MySQL in The Migration component

### ISSUE THREAD

**Issue by shoomlix** [yiisoft/yii2#17742]
Could somebody tell me why we don't have in The Migration component some types of MySQL?

For example, we don't have MEDIUMTEXT.

**Comment by samdark** [comment]
All the types that present in migrations must be supported by all database engines we have. Current set is a bare minimum. If you do not plan to develop a portable solution, there's no point in having universal types, you can use strings.

**Comment by shoomlix** [comment]
> All the types that present in migrations must be supported by all database engines we have. Current set is a bare minimum. If you do not plan to develop a portable solution, there's no point in having universal types, you can use strings.

Ok. It's clear. Thank you.
