### ISSUE TITLE
ActiveDataFilter attribute mapping to multiple attributes w/ condition

### ISSUE THREAD

**Issue by raraworks** [yiisoft/yii2#17746]
### What steps will reproduce the problem?
Trying to filter ActiveRecord model by virtual attribute in search model that corresponds to multiple columns in database.

### What is the expected result?
Ability to declare multiple attributes with condition (AND|OR etc.) as mapping for a virtual attribute in search model of a ActiveDataFilter object.

### What do you get instead?
Ability to only make one -> one mapping in ActiveDataFilter::attributeMap attribute

### Additional info
I start to realize, that this is redundant functionality (because you already declare build condition types in querystring or json when sending the request), but i can not get correctly build query that would include multiple columns against which i could filter one filter attribute.

An example:
```
?filter[vehicle_model_title][like]=asd

Controller implementing yii/rest/ActiveController class:

$actions['index']['dataFilter'] = [
            'class' => ActiveDataFilter::class,
            'attributeMap' => NewPriceSearch::getAttributeMap(),
            'searchModel' => NewPriceSearch::class,
];

NewPriceSearch class
public static function getAttributeMap()
{
    return ['vehicle_model_title' => '{{vehicle_models}}.[[title]]']; // i would like to incliude also vehicle_models.code column with OR condition;
}
```
Is there a possible solution to this?

Maybe i am looking in the wrong direction.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30
| PHP version      | 7.3.10-1+ubuntu18.04.1+deb.sury.org+1
| Operating system | Linux 5.3.0-24-generic Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64

**Comment by raraworks** [comment]
After creating this issue, i came up with a workaround (in my case) with sql concatination, so i would get one summary column as a attribute map:
```
    public static function getAttributeMap(): array
    {
        return ['vehicle_model_title' => 'CONCAT({{vehicle_models}}.[[title]], \' \', {{vehicle_models}}.[[code]])'];
    }
```

**Comment by samdark** [comment]
Good you've solved it.
