### ISSUE TITLE
Incorrect mapping of default expression for MySQL >= 5.6.4 CURRENT_TIME

### ISSUE THREAD

**Issue by bizley** [yiisoft/yii2#17744]
### What steps will reproduce the problem?

Create MySQL >= 5.6.4 table with `timestamp(3)` column and `CURRENT_TIMESTAMP(3)` as default value.
Fetch this schema in Yii 2.

### What is the expected result?

```php
$column->defaultValue = new Expression('CURRENT_TIMESTAMP(3)');
```

### What do you get instead?

```php
$column->defaultValue = 'CURRENT_TIMESTAMP(3)';
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | *
| PHP version      | *
| Operating system | *

[These lines](https://github.com/yiisoft/yii2/blob/2.0.30/framework/db/mysql/Schema.php#L296-L298) are too strict now. I'll prepare PR with regex match and see if it's enough.

**Comment by alex-code** [comment]
Quick and easy would be to use `stripos` and check if it matches 0.
```php
if (($column->type === 'timestamp' || $column->type === 'datetime') &&
  stripos($info['default'], 'current_timestamp') === 0) {
  $column->defaultValue = new Expression('CURRENT_TIMESTAMP');
} elseif (isset($type) && $type === 'bit') {
```

**Comment by bizley** [comment]
Yes, if this is enough and matches all possibilities. I haven't dig into MySQL and MariaDB docs yet ;)
