### ISSUE TITLE
dispatch crash, if logtarget::collect throw \Throwable

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii2#17749]
### What steps will reproduce the problem?

1. `$target->collect()` throw `\Throwable`
2. Further targets can no longer run. the developer toolbar cannot save the log file.

https://github.com/yiisoft/yii2/blob/596bcff0b41d6c5dc074ca5c248741f1a87bbe64/framework/log/Dispatcher.php#L188-L199

### What is the expected result?

The other logs work correctly.

### What do you get instead?

After the first error, the other logs are no longer running.

### Additional info

The code below fixes the bug, but require PHP 7.0+ 
```php
                 try { 
                     $target->collect($messages, $final); 
                 } catch (\Throwable $e) { 
```

Separate try-catch block for PHP 7.0+ and PHP <7.0 can solve the problem, but need to consider whether there is a better solution.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      | 7.0+
| Operating system | -

**Comment by My6UoT9** [comment]
Just catch first Exception, then catch Throwable, should be fine, was done in other places too.

**Comment by samdark** [comment]
As far as I remember, I was testing for this case when implementing logger i.e. error in one of the targets was properly logged in the rest of the targets. If currently it's not like that, that's not desired behavior.
