### ISSUE TITLE
\yii\widgets\MaskedInput update

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii2#17759]
need update to current version, already 5th released

**Comment by samdark** [comment]
Is it compatible?

**Comment by andrtechno** [comment]
I do not know, did not check

**Comment by alex-code** [comment]
v4 has some non BC changes, https://github.com/RobinHerbots/Inputmask/blob/5.x/CHANGELOG.md#note

v4.0.2 removed an alias,
https://github.com/RobinHerbots/Inputmask/blob/5.x/CHANGELOG.md#updates-4

v5 changed a mask to do with time,
https://github.com/RobinHerbots/Inputmask/issues/1918

There may be some more non BC bits I've missed too.

**Comment by samdark** [comment]
Thanks, @alex-code. That means compatibility could be broken. @andrtechno is there any particular issue you want to fix updating the library?
