### ISSUE TITLE
Active Record: Relations subquery Exists and Not Exists 

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#1775]
Is there a way to define relations which creates subqueries to check if a table exists or not exists?

What do you think about adding a parameter to the hasOne and hasMany functions to create a subquery. This way you don't have to define the relationship twice?

My current solution looks like
```php
public static function partner($query) {
        $query->andWhere('exists (select * from tbl_vertrag where partnerID = tbl_adresse.id)');
    }
``` 
This works but isn't as elegant as it could be.

**Comment by klimov-paul** [comment]
Feature is already suported by `yii\db\QueryBuilder::buildExistsCondition()`.
