### ISSUE TITLE
Packagist release 2.0.31 contains latest commit (2.0.32-dev)

### ISSUE THREAD

**Issue by foxofinfinety** [yiisoft/yii2#17752]
### What steps will reproduce the problem?
composer require yiisoft/yii2
OR
composer create-project yiisoft/yii2-advanced-app advanced

### What is the expected result?
Yii2 is installed and reports its own version as 2.0.31

### What do you get instead?
Yii2 is installed, and reports it own version as 2.0.32-dev

### Additional info
I was working on upgrading a project ot hte latest depenencies, including Yii 2.0.31, and had been looking for a while why Composer was installing 2.0.32-dev.

Intially I though composer was resolving the depencies to the wrong versions.
but according to composer.lock, version 2.0.31 is installed.
Reading further composer.lock specifies reference b9fa3d184b41fb847aa7ae8b447d59b243c72d45 for both source and dist.
Yii 2.0.31 was released with commit 0329b2db8bbf9719b1add17d6defd2d6045b4f09.

[Yii2 commit: release version 2.0.31](https://github.com/yiisoft/yii2-framework/commit/0329b2db8bbf9719b1add17d6defd2d6045b4f09)
[Yii2 commit: prepare for next release](https://github.com/yiisoft/yii2-framework/commit/b9fa3d184b41fb847aa7ae8b447d59b243c72d45)

Looking through the changes from the 'prepare for next release' commit, that is the version I got, as CHANGELOG.md also already includes the new _2.0.32 under development_ section (which did not exist in the previous commit).

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31 (expected)
| PHP version      | 7.2.4
| Operating system | Windows 10 Version 1909 Professional 64-bit

**Comment by samdark** [comment]
Tags are done correctly:

- https://github.com/yiisoft/yii2/commit/d97a160bcea8663ecf3db051e9d92c710c8ce1d9
- https://github.com/yiisoft/yii2-app-advanced/commit/52b81754ea0425e8351142f5f4caee536dc86212

"prepare for next release" commits are made after release was tagged.

**Comment by alexantr** [comment]
I updated Yii to 2.0.31 but files inside from 596bcff instead d97a160
Looks like packagist glitch.

**Comment by samdark** [comment]
Could be. Anyway, tags are correct and I see nothing we can do to fix your issue.

**Comment by rob006** [comment]
Tag is incorrect in subsplit: https://github.com/yiisoft/yii2-framework/commits/2.0.31

**Comment by rob006** [comment]
BTW: it already happened in the past: https://forum.yiiframework.com/t/yii-2-0-18-released/125842

**Comment by samdark** [comment]
Aha!

**Comment by samdark** [comment]
Fixed https://github.com/yiisoft/yii2-framework/commits/2.0.31. Thanks!
