### ISSUE TITLE
Make yii\i18n\Formatter::formatNumber method protected or public

### ISSUE THREAD

**Issue by thecodeholic** [yiisoft/yii2#17767]
### What steps will reproduce the problem?
Override class [Formatter](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php) and override [asShortSize](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1378) method and try to call [formatNumber](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1660) from your asShortSize method.
### What is the expected result?
[formatNumber](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1660) method to be protected or even public.
### What do you get instead?
 [formatNumber](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1660) method is private and I can not call it in my overridden asShortSize method.

### Additional info
I have extended Formatter class and overrided [asShortSize](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1378) method.
The only thing I want change is **KiB**, **MiB** etc... into **K**, **M** etc... but [formatNumber](https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1660) method is private and I can not call it from my `asShortSize` method. I think making `formatNumber` method protected will not hurt anything. So this is a feature request I guess.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.30
| PHP version      | >=7.0
| Operating system | Ubuntu 18.10

**Comment by samdark** [comment]
Can't you do it via message translations?

**Comment by samdark** [comment]
But yes, issue is valid.

**Comment by samdark** [comment]
Let's make the method protected.

**Comment by thecodeholic** [comment]
I could use message translations, but if I want to show on source language, then it's a little bit tricky.
Anyway, Thank you.
I can make a fork and then pull request if that's OK for you.

**Comment by samdark** [comment]
Please do,
