### ISSUE TITLE
При каждом открытии модального окна на pjax-контейнер навешивается событие submit

### ISSUE THREAD

**Issue by armagedon007** [yiisoft/yii2#17766]
https://github.com/yiisoft/yii2/blob/b79fe7d106b8f901d3f3f2fd01eae811ce2c34ec/framework/widgets/Pjax.php#L207

На странице есть динамическая форма обернутая pjax, которая загружается при открытии модального окна.
При открытии модального окна во второй и последующие разы событие submit навешивается на этот pjax и при обновлении этого контейнера идет столько событий submit, сколько раз открывали это модальное окно. 
Т.е. при генерации pjax-контейнера надо сначала отписаться от submit

            $js .= "\njQuery(document).off($submitEvent, $formSelector).on($submitEvent, $formSelector, function (event) {jQuery.pjax.submit(event, $options);});";

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22
| PHP version      | 7.3.8
| Operating system | CentOS 7

**Comment by samdark** [comment]
@armagedon007 да, можно. Pull request сделаете? И, в следующий раз, пожалуйста, попробуйте issue сделать на английском. В команде Yii не все читают по-русски.

**Comment by webceoboy** [comment]
I also need this,becase pjax will bind many times when form in dialog(no iframe dialog)
