### ISSUE TITLE
::class is not an identical replacement for deprecated className()

### ISSUE THREAD

**Issue by lucasrothamel** [yiisoft/yii2#17764]
### What steps will reproduce the problem?

Execute this snippet:

class SomeClass
{
    public function say()
    {
        echo 'get_called_class() value: ' . get_called_class() . "\n";
        echo '::class value: ' . self::class . "\n";
    }
}

class AnotherClass extends SomeClass {

}

$c = new AnotherClass();
$c->say();

### What is the expected result?

since ::class is a replacement for deprecated className() in BaseObject - they should always return the same value.

### What do you get instead?

get_called_class() value: AnotherClass
::class value: SomeClass

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.18
| PHP version      | 7.1
| Operating system | debian

**Comment by lucasrothamel** [comment]
As a background note, i have done a search-replace for className() to class in my codebase, and quite some code stopped working correctly, due to this difference in behaviour.

**Comment by rob006** [comment]
You should use `static::class` instead of `self::class`.
