### ISSUE TITLE
Codeception failing due to parameter order

### ISSUE THREAD

**Issue by RichardPillay** [yiisoft/yii2#17777]
### What steps will reproduce the problem?
After installing a new system with the advanced template (but probably affecting the basic template as well), "codecept run" fails to run any tests:

### What is the expected result?
The tests should run, either failing or passing. Instead all you get are FATAL ERROR notices.
### What do you get instead?

`FATAL ERROR. TESTS NOT FINISHED.
Uncaught TypeError: Argument 1 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an object, string given, called in /var/www/yii/vendor/codeception/phpunit-wrapper/src/Listener.php on line 82 and defined in /var/www/yii/vendor/symfony/event-dispatcher/EventDispatcher.php:48
Stack trace:
#0 /var/www/yii/vendor/codeception/phpunit-wrapper/src/Listener.php(82): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('suite.start', Object(Codeception\Event\SuiteEvent))
`

### Additional info
I can fix the problem by changing several instances of 
`
        $this->dispatcher->dispatch('suite.start', new SuiteEvent($suite));
`
to 
`
        $this->dispatcher->dispatch(new SuiteEvent($suite), 'suite.start');
`
Should I submit a pull request with these changes, or is this merely a symptom of another change somewhere else?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32-dev
| PHP version      | 7.2
| Operating system | Ubuntu 18.04.3

**Comment by alex-code** [comment]
Can you update to the latest version?

**Comment by RichardPillay** [comment]
> Can you update to the latest version?

Later than that? That was the latest, I thought. It's a copy created on Dec 31 at 17:32 my time, about a day ago. Running composer update doesn't update anything.

**Comment by alex-code** [comment]
Oh, just in the table you have 2.0.14 so thought you were on an older version.

**Comment by RichardPillay** [comment]
My apologies. I didn't know how to properly get the version number, so I incorrectly read the version number from the composer.json file. Still on a steep learning curve. Fixed now.


Best Regards,Richard 

    On Thursday, 2 January 2020, 00:00:57 GMT+11, alex-code <notifications@github.com> wrote:  
 
 
Oh, just in the table you have 2.0.14 so thought you were on an older version.

**Comment by samdark** [comment]
Are changes you proposing part of the framework?

**Comment by RichardPillay** [comment]
Not really changes, just fixes. If you quickly create a new advanced template project and set it up following the instructions, you will find that straight out of the box all the tests fail. 
These fixes make them work again.

From my limited understanding, these broke when Symfony changed to 4.3.1, though why they would make changes that break the code, I don't know. What I do know is that it broke for other projects as well, not just Yii2.

**Comment by samdark** [comment]
OK. It would be great to have a pull request. Easier to check if the changes are fine. Thanks.

**Comment by RichardPillay** [comment]
> Are changes you proposing part of the framework?

Hi Guys,

Just realised I made a silly newbie mistake opening this issue and proposing this change. I only realised when I came to create a pull request and realised the code with the problem was part of the Codeception codebase, not Yii. 

I'll do a little more investigation to see if we are still pulling an old version of Codeception via composer, or whether I must raise a pull request there.

Newbies like myself, though, will set up a system and get very confused and frustrated when it doesn't work out of the box. Is there any way we can put something into the Readme until the issue is resolved?

Let me know how to proceed with this pull request - should we close it now and open an issue to track it until it's resolved?

**Comment by samdark** [comment]
> Let me know how to proceed with this pull request - should we close it now and open an issue to track it until it's resolved?

Yes,

**Comment by RichardPillay** [comment]
> > Let me know how to proceed with this pull request - should we close it now and open an issue to track it until it's resolved?
> 
> Yes.

Went to do that, and someone else has just opened an issue a few hours ago:

[https://github.com/yiisoft/yii2-app-advanced/issues/454](url)

It's in the app-advanced section, but I suspect it may affect the basic template as well.
