### ISSUE TITLE
BaseMigrateController::actionFresh doesn't return an exit code

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#17771]
```php
    public function actionFresh()
    {
        if (YII_ENV_PROD) {
            $this->stdout("YII_ENV is set to 'prod'.\nRefreshing migrations is not possible on production systems.\n");
            return ExitCode::OK;
        }

        if ($this->confirm(
            "Are you sure you want to reset the database and start the migration from the beginning?\nAll data will be lost irreversibly!")) {
            $this->truncateDatabase();
            $this->actionUp();
        } else {
            $this->stdout('Action was cancelled by user. Nothing has been performed.');
        }
    }
```
It would be nice if you could add `return` to the line `$this->actionUp();` sentence so that the result of applying the migrations is returned to the calling action.

**Comment by kamarton** [comment]
If there is no return value, the value `null` is cast to `0`.
https://github.com/yiisoft/yii2/blob/a636ff916ac3a06756f37c0dbfb55994394a6a55/framework/console/Application.php#L180-L181

https://github.com/yiisoft/yii2/blob/a636ff916ac3a06756f37c0dbfb55994394a6a55/framework/console/ExitCode.php#L41

**Comment by samdark** [comment]
The report is valid. Non 0 code could be returned from `actionUp()`.
