### ISSUE TITLE
Can yii2 support yar rpc framework?

### ISSUE THREAD

**Issue by shouhuori** [yiisoft/yii2#17778]
### code：
In a RpcContronller :
```php
<?php

namespace micro\controllers;

use Yii;
use yii\rest\Controller;

class RpcController extends Controller
{
    public function actionIndex()
    {
            $server = new \Yar_Server(new \micro\models\testModel()); 
            $server->handle();
    }
}
```
in Client code:
```php
 $object =  new \Yar_Client("https:domain.test/rpc/index");
 $object->foo();
```

and I use Xdebug find this Exception `yii\web\HeadersAlreadySentException: Headers already sent in  on line 0.`

### stacktrace：
```
yii\web\Response->send (/Users/chao/dev/micro-app/vendor/yiisoft/yii2/web/Response.php:336)
yii\web\Application->run (/Users/chao/dev/micro-app/vendor/yiisoft/yii2/base/Application.php:392)
{main} (/Users/chao/dev/micro-app/web/index.php:13)
```
yii2/web/Response.php ,`$this->sendHeaders();`:
```php
  /**
     * Sends the response to the client.
     */
    public function send()
    {
        if ($this->isSent) {
            return;
        }
        $this->trigger(self::EVENT_BEFORE_SEND);
        $this->prepare();
        $this->trigger(self::EVENT_AFTER_PREPARE);
        $this->sendHeaders();
        $this->sendContent();
        $this->trigger(self::EVENT_AFTER_SEND);
        $this->isSent = true;
    }
```

I noticed   #14329

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.4
| Operating system | macOS 10.14.6

**Comment by xepozz** [comment]
Please attach full stacktrace and show action's code

**Comment by shouhuori** [comment]
@xepozz  I update the problem description.

**Comment by xepozz** [comment]
If you don't want to sent any headers you just may do [`Yii::$app->response->isSent = true`](https://www.yiiframework.com/doc/api/2.0/yii-web-response#$isSent-detail) or [`Yii::$app->end()`](https://www.yiiframework.com/doc/api/2.0/yii-base-application#end()-detail) in the end of action code.

**Comment by samdark** [comment]
@xepozz is correct. Yar seems to be dealing with headers and output itself so you have to adjust Yii not to try adding headers at the time it's not possible to do.

**Comment by shouhuori** [comment]
@xepozz Thank you so much! The result code:
```php
<?php

namespace micro\controllers;

use Yii;
use yii\rest\Controller;

class RpcController extends Controller
{
    public $enableCsrfValidation = false;

    public function actionIndex()
    {
            $server = new \Yar_Server(new \micro\models\testModel()); 
            $server->handle();
            Yii::$app->response->isSent = true;
    }
}
```
