### ISSUE TITLE
Yii migrate not support MongoDB

### ISSUE THREAD

**Issue by xiaoyi510** [yiisoft/yii2#17785]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.2
| Operating system | Windows

Error :
`````````````````````
   Yii Migration Tool (based on Yii v2.0.29)

   Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: 
   common\components\MongoDb\Connection::attributes'

   in vendor\yiisoft\yii2\base\Component.php:209
`````````````````````
common\components\MongoDb extend \yii\mongodb\Collection

**Comment by bizley** [comment]
You must use [MigrateController](https://github.com/yiisoft/yii2-mongodb/blob/master/src/console/controllers/MigrateController.php) from [yii2-mongodb](https://github.com/yiisoft/yii2-mongodb) package as mentioned in [Guide](https://www.yiiframework.com/extension/yiisoft/yii2-mongodb/doc/guide/2.1/en/topics-migrations).
