### ISSUE TITLE
Overriding ActiveRecord::find() to use ActiveQuery class

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#17786]
I am in an odd situation right now, maybe i dont understand the working yet but as much docs i have read for using `ActiveQuery` class with `ActiveRecord`  i have done the same way but the behavior is different when we compare the following 2 scenarios

## Scenario 1
Generate models with active query for the `user` table, you will get the following 

- app\models\User.php
- app\models\UserQuery.php

You query using `User::find()->all()` all is good and returns the records in the database table. All good.

## Scenario 2
Now if i am using a user module via composer and it provides me a base `User` model which does not have any `find()` method override and you create a custom model which extends this `BaseUser` model, and override the `find()` method you will have the following list of files

- BaseUser.php
- app\models\User.php
- app\models\UserQuery.php

Now if i use the same query above `User::find()->all()` it returns `null` ?. which is really odd considering that the `->all()` method should return the records in the table, and even if there are no records it should return an empty array rather than `NULL` which is returned by the `->one()` instead. 

But above all why is it behaving like this? can you guys confirm that you are able to regenerate the issue.

I am using the https://github.com/dektrium/yii2-user with default installation of yii2 basic-app, you can see the [`BaseUser` model here](https://github.com/dektrium/yii2-user/blob/master/models/User.php) i am overriding the `find()` method in the user model like below

app\models\User
```
/**
     * {@inheritdoc}
     * @return BongyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }
```

app\models\UserQuery

```
<?php
namespace app\models;

use yii\db\ActiveQuery;

class UserQuery extends ActiveQuery
{

 
    public function all($db = null)
    {   
        parent::all($db);
    }

    
    public function one($db = null)
    {
        return parent::one($db);
    }
}

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.2.2
| Operating system |Windows

**Comment by samdark** [comment]
dektrium/yii2-user is complicated. Could you try reproducing it with a simpler model i.e.

1. Take basic app template.
2. Create a database and a user table, insert some records.
3. Generate User model w/o Query.
4. Extend from User model, implement custom query.
5. Try using the query.

**Comment by buttflattery** [comment]
@samdark just what i thought its the same behavior and its strange that it shows the same `null` as the output for a very basic query

`User::find()->all()`

I generated a model for the user table with the name `BaseUser` and then created a `User` model and extended the `BaseUser` which is implementing the user identity, then override the `find()` method to use `ActiveQuery` class `UserQuery`.

Another strange thing is that even if i move the `find()` to the parent class i.e `BaseUser` the result stays the same until i comment out the `find()` method

if i comment out the `find()` fr

**Comment by buttflattery** [comment]
delete the issue @samdark  i am missing the `return` statement in the `UserQuery`

```
public function all($db = null)
    {   
        parent::all($db);
    }
```

 :( this should be closed. sorry for bothering you.
