### ISSUE TITLE
Yii2 output is inconsistent with mysql execution result.

### ISSUE THREAD

**Issue by loveshenshen** [yiisoft/yii2#17780]
### What steps will reproduce the problem?
I use Yii2 for this way .
$result = $dev->select(['sum(num) num',"from_unixtime(created_at,'%m') `date`"])->groupBy('`date`');
return $dev->asArray()->all();

### What is the expected result?
Error result
```
{
    "data": [
        {
            "num": "33374.67",
            "date": "01"
        },
        {
            "num": "1078.90",
            "date": "12"
        }
    ],
    "api_code": 200
}
```
Right result
```
{
    "data": [
        {
            "num": "34453.57",
            "date": "01"
        }
    ],
    "api_code": 200
}
```
### What do you get instead?
```
        $pdo = new  \PDO(\Yii::$app->db->dsn,\Yii::$app->db->username,\Yii::$app->db->password);
        return $pdo->query($result->createCommand()->rawSql)->fetchAll(\PDO::FETCH_ASSOC);
```  
### Additional info
The same sql is right when I executed  on mysql CLI.
I guess  that method 'asArray() ' or 'all()'  has some issue,But I have not found temporarily .

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.19
| PHP version      | 7.0.33
| Operating system |  Ubuntu 16.04.7

**Comment by kamarton** [comment]
The exact query string is not known, but the `Error result` output seems correct because `group by` is based on the `date` column. Conversely, the output in `Right result` aggregates to a single` date` value.

**Comment by loveshenshen** [comment]
> The exact query string is not known, but the `Error result` output seems correct because `group by` is based on the `date` column. Conversely, the output in `Right result` aggregates to a single` date` value.
The complete query string is this
```
SELECT sum(num) num, from_unixtime(created_at,'%m') `date` FROM `company_dev_log` WHERE ((`park_id`=10) AND (`type`='1') AND (`ele_type`=0)) AND ((`created_at` > 1577808000) AND (`created_at` < 1578103856)) GROUP BY `date`
```
 Mysql Cli output
num | date |  
-- | -- | --
35158.61 | 01

But In yii2 has output 'Error result'  . When I get instead Origin PDO  make it correct.

**Comment by kamarton** [comment]
```sql
CREATE TABLE `t17780` (
  `created_at` int(11) NOT NULL,
  `num` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `t17780` (`created_at`, `num`) VALUES
(1577808001, 1),
(1578103855, 2);
```

```sql
mysql> SELECT sum(num) num, from_unixtime(created_at,'%m') `date` FROM `t17780` WHERE ((`created_at` > 1577808000) AND (`created_at` < 1578103856)) GROUP BY `date`;
+------+------+
| num  | date |
+------+------+
|    2 | 01   |
|    1 | 12   |
+------+------+
2 rows in set (0.00 sec)
```

**Comment by kamarton** [comment]
or the two environments are in different time zones.

![Epoch Converter - Unix Timestamp Converter](https://user-images.githubusercontent.com/9432032/71761063-ef374300-2ec6-11ea-89bd-04e7010eab56.png)

**Comment by loveshenshen** [comment]
> or the two environments are in different time zones.
> 
> ![Epoch Converter - Unix Timestamp Converter](https://user-images.githubusercontent.com/9432032/71761063-ef374300-2ec6-11ea-89bd-04e7010eab56.png)
When I executed your query string
```
MySQL [park]> select *  from  t17780;
+------------+-----+
| created_at | num |
+------------+-----+
| 1577808001 |   1 |
| 1578103855 |   2 |
+------------+-----+
``` 
```
MySQL [park]> SELECT sum(num) num, from_unixtime(created_at,'%m') `date` FROM `t17780` WHERE ((`created_at` > 1577808000) AND (`created_at` < 1578103856)) GROUP BY `date`
```
The result  is correct.
```
+------+------+
| num  | date |
+------+------+
|    3 | 01   |
+------+------+
```
use yii pdo
```
 $result =  \Yii::$app->db->createCommand("SELECT sum(num) num, from_unixtime(created_at,'%m') `date` FROM `t17780` WHERE ((`created_at` > 1577808000) AND (`created_at` < 1578103856)) GROUP BY `date` ")->queryAll(\PDO::FETCH_ASSOC);
       var_dump($result);
```
The result is error
```
array(2) {
  [0]=>
  array(2) {
    ["num"]=>
    string(1) "2"
    ["date"]=>
    string(2) "01"
  }
  [1]=>
  array(2) {
    ["num"]=>
    string(1) "1"
    ["date"]=>
    string(2) "12"
  }
}
```

**Comment by kamarton** [comment]
timezone problem, please execute in different environments:

```sql
SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);
```

**Comment by loveshenshen** [comment]
> timezone problem, please execute in different environments:
> 
> ```sql
> SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);
> ```
On mysql
```
MySQL [park]> SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP)
TIMEDIFF(NOW(), UTC_TIMESTAMP) |  
-- | --
08:00:00
```
On php environments 
```
 "TIMEDIFF(NOW(), UTC_TIMESTAMP)": "00:00:00"
```

**Comment by kamarton** [comment]
set timezone before execute query (example after connection) and yii works fine.

https://gist.github.com/SilverFire/6f98d2605a6574bd02f7
