### ISSUE TITLE
Wrong attributes for activeListInput

### ISSUE THREAD

**Issue by matiosfree** [yiisoft/yii2#17797]
Create an active form and add field like:
```php
<?= $form
   ->field($searchForm, 'some_attribute')
    ->checkboxList($options, ['name' => 'new_field_name', 'value' => 1]);
?>

```
### What is the expected result?
"div" tag should not have attributes "name" and "value"

### What do you get instead?
```html
<div id="searchform-some_attribute" name="new_field_name" value="1">
  <label><input type="checkbox" name="new_field_name[]" value="4"> 2835</label>
  <label><input type="checkbox" name="new_field_name[]" value="5"> 3014</label>
  <label><input type="checkbox" name="new_field_name[]" value="9"> 5050</label>
  <label><input type="checkbox" name="new_field_name[]" value="11"> 5730</label>
</div>
```

### Additional info
I think problem is here:
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1825

Here should be 
```php
$name = ArrayHelper::remove($options, 'name', static::getInputName($model, $attribute));
$selection = ArrayHelper::remove($options, 'value', static::getInputName($model, $attribute));
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31

**Comment by kamarton** [comment]
> "div" tag should not have attributes "name" and "value"

Why do I need the `name` and` value` on the `div` tag? Why don't you use `data-name` and` data-value` attributes? see more https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by alex-code** [comment]
Maybe `ArrayHelper::remove` should be used to get the options.

**Comment by samdark** [comment]
I think the intent is to have these options applied to inputs, right @matiosfree?

**Comment by matiosfree** [comment]
> 
> 
> I think the intent is to have these options applied to inputs, right @matiosfree?

Yes, but now they are applied to "div" also and that's is wrong.
We must have:
`<div id="searchform-some_attribute">`

**Comment by matiosfree** [comment]
> Why do I need the `name` and` value` on the `div` tag?

What's the problem. "div" should NOT have these 2 attributes. But now it has.

**Comment by mikehaertl** [comment]
@matiosfree I'd say this is an intentional design decision. If you want to set attributes on inputs use  `itemOptions` in your `$options` array instead:

```php
$form->checkboxList($items, ['itemOpions' => ['attrname' => 'attrvalue']]);
```
