### ISSUE TITLE
Try GitHub actions instead of Travis

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#17802]
Travis build currently takes too much time. That's, of course, mainly because our tests aren't fast but time could be cut a bit by switching to GitHub actions.

**Comment by samdark** [comment]
https://github.com/shivammathur/setup-php

**Comment by simialbi** [comment]
I prepared this once in [template](https://github.com/yiisoft/template/pull/3). Shall I prepare for yii2 too?

**Comment by samdark** [comment]
@simialbi yes, please.

**Comment by simialbi** [comment]
WIP: https://github.com/simialbi/yii2/runs/395400472

**Comment by samdark** [comment]
Any idea why 7.4 and 7.3 builds are interrupted?

**Comment by samdark** [comment]
For reference: https://github.com/rectorphp/rector/pull/2589/files

**Comment by simialbi** [comment]
> .github:1
> The job was canceled because "ubuntu-latest_7_2" failed.

**Comment by samdark** [comment]
Another one: https://github.com/Codeception/module-rest/pull/3/files

**Comment by samdark** [comment]
And your own one: https://github.com/yiisoft/template/pull/3

**Comment by samdark** [comment]
And another yours: https://github.com/simialbi/yii2-bootstrap4/blob/master/.github/workflows/phpunit.yml

**Comment by samdark** [comment]
Yii 2 build errors are related to #17708

**Comment by simialbi** [comment]
I fixed one of them: https://github.com/simialbi/yii2/runs/395421105

**Comment by simialbi** [comment]
all of the tests run to the end now

**Comment by schmunk42** [comment]
@simialbi Where or how did you fix the tests? Above links show a 404.

**Comment by simialbi** [comment]
Just one of them:
https://github.com/simialbi/yii2/runs/402852766

The other still remains #17708

**Comment by schmunk42** [comment]
I gave that another try https://github.com/yiisoft/yii2/pull/17826

**Comment by samdark** [comment]
Waiting for #17708. @schmunk42 is on it.

**Comment by schmunk42** [comment]
Test should be marked as skipped, see https://github.com/yiisoft/yii2/issues/17708#issuecomment-579484393
