### ISSUE TITLE
MSSQL drop column error: "The object 'DF__yyyyy__xxxxx__151B244E' is dependent on column"

### ISSUE THREAD

**Issue by michalwoz** [yiisoft/yii2#17816]
# What steps will reproduce the problem?
Dropping one of table columns in migration on MSSQL. table has many columns, not the onle one being dropped.

### What is the expected result?
column drop

### What do you get instead?
exception:
```
drop column xxxxx from table {{%yyyyy}} ...Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The object 'DF__yyyyy__xxxxx__151B244E' is dependent on column 'xxxxx'.
The SQL being executed was: ALTER TABLE [yyyyy] DROP COLUMN [xxxxx] (app\vendor\yiisoft\yii2\db\Schema.php:674)
```

This issue is the same as https://github.com/yiisoft/yii2/issues/17035 but I think , that it was incorrectly classified as the attempt of removing single/last column in table. The exception occurs, not because it is the only column, but because there exists DF constrain.

Ugly workaround is to find constrain name first, than remove it and finally drop the column:
```php
    $migration->execute(Yii::$app->db->getQueryBuilder()->dropDefaultValue( // on MSSQL you need to drop default constrain before dropping column
        Yii::$app->db->createCommand("select dobj.name as def_name from sys.columns col 
            left outer join sys.objects dobj on dobj.object_id = col.default_object_id and dobj.type = 'D' 
            where col.object_id = object_id(N'dbo.$table') and col.name = '$column' and dobj.name is not null"
        )->queryScalar(), $table));
    $migration->dropColumn($table, $column);
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.25
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
DF constrain = default value?

**Comment by michalwoz** [comment]
Yes, this constrain is automatically created by MSSQL for each column which has default value.

**Comment by simialbi** [comment]
It's not yii related. I always solved it like this:
```php
if ($this->getDb()->driverName === 'sqlsrv' || $this->getDb()->driverName === 'mssql' || $this->getDb()->driverName === 'dblib') {
	foreach (array_keys($fields) as $field) {
		$sql = <<<SQL
DECLARE @ObjectName NVARCHAR(100);
SELECT @ObjectName = OBJECT_NAME([default_object_id]) FROM SYS.COLUMNS
WHERE [object_id] = OBJECT_ID('[dbo].$table') AND [name] = '$field';
IF @ObjectName IS NOT NULL
EXEC('ALTER TABLE [dbo].$table DROP CONSTRAINT ' + @ObjectName);
SQL;

		$command = $this->getDb()->createCommand();
		$command->setSql($sql)->execute();
	}
}
```

**Comment by michalwoz** [comment]
@simialbi I agree to a certain extent as MSSQL creates automatically constrains for default values. On the other hand you can add column wint single command `$this->addColumn()` and you cannot drop remove it with single `$this->dropColumn();` You don't even know the name of this constrain and you have to find it like you do.

What would be the disadvantage of implementing removing this constrain on column drop in case of MSSQL?

**Comment by simialbi** [comment]
I'm not sure if it won't be confusing. Yii would do something you don't expect and did not call. 
IMHO: If I call `dropColumn` I expect dropping a column and not dropping a column **and a constraint**. What I would prefer is either a **parameter** `$dropConstraints` or `$force` or something like this or a separate method `->dropColumnAndConstraints()`.

**Comment by simialbi** [comment]
I saw there already is something like this: https://github.com/yiisoft/yii2/blob/master/framework/db/mssql/QueryBuilder.php#L193
The problem with the existing method is, you have to know the constraint name. And no one knows these `DF_xxxxxxxx_xxxxxx` names... Maybe we should add a method `dropDefaultValueFromColumn($table, $column)` to [\yii\db\Migration](https://github.com/yiisoft/yii2/blob/master/framework/db/Migration.php) which implements my sql example above? @samdark, @michalwoz what do you think?

**Comment by samdark** [comment]
`dropDefaultValue()`  should be better name. Is it possible to do in MySQL, PostgreSQL, SQLite etc.?

**Comment by simialbi** [comment]
PostgreSQL and SQLite I don't know. But I think not, because there are no corresponding methods in QueryBuilder classes. In MySQL and MariaDB I'm sure there is **no** `default constraint`.
I proposed `dropDefaultValueFromColumn` because it sounds more like the existing Migration methods (e.g.: [dropCommentFromColumn](https://github.com/yiisoft/yii2/blob/master/framework/db/Migration.php#L547))

**Comment by samdark** [comment]
OK about method name. Still, it doesn't sound right because it would likely work for MSSQL only :(

**Comment by achretien** [comment]
From Microsoft doc they use an other table to get the default constraints name of a column.

https://docs.microsoft.com/fr-fr/sql/relational-databases/system-catalog-views/sys-default-constraints-transact-sql?view=sql-server-ver15

USE AdventureWorks2012;  
GO  
SELECT d.definition   
FROM sys.default_constraints AS d  
INNER JOIN sys.columns AS c  
ON d.parent_object_id = c.object_id
AND d.parent_column_id = c.column_id  
WHERE d.parent_object_id = OBJECT_ID(N'HumanResources.Employee', N'U')  
AND c.name = 'VacationHours';


I am sure we can remove default value définition in the other db engine

https://www.w3schools.com/sql/sql_ref_drop_default.asp

The DROL DEFAULT Syntaxe is deprecated on MSSQL.
