### ISSUE TITLE
Date diff bug with php 7.3

### ISSUE THREAD

**Issue by istvan0304** [yiisoft/yii2#17814]
# What steps will reproduce the problem?

Calculate number of days between two dates.
$startDate = new \DateTime('1867-01-01');
$endDate = new \DateTime('1991-09-07');
$diff = $startDate->setTime(0,0)->diff($bornDate->setTime(0,0));

### What is the expected result?

Expected result is 45539.

### What do you get instead?

I get 45538

### Additional info

In web config file I use timezone settings:
'timezone' => 'Europe/Budapest',

The date diff is work correctly with php 7.2.
With php 7.3 is works only if I remove the timezone settings from the config file.
I tried only php without yii and I got the good result.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.27
| PHP version      | 7.3.12, 7.3.6
| Operating system  | Windows 10 Enterprise x64

**Comment by rob006** [comment]
This is not related to Yii, this was changed in PHP: https://3v4l.org/VZJCB

BTW: Are you sure that 45539 is correct? I would suspect that new value is correct and the change is bugfix.

**Comment by istvan0304** [comment]
45539 is correct! So php bufix is wrong.

**Comment by rob006** [comment]
I think you're wrong. In 1991-09-07 there was Daylight Saving Time active, so there was 1 hour shift between regular `Europe/Budapest` timezone. So difference is precisely 45538 days and 23 hours. 

You should probably explicitly specify `UTC` as timezone, to avoid such errors. See https://stackoverflow.com/a/52201850/5812455
