### ISSUE TITLE
EachValidator doesn't work with typed properties

### ISSUE THREAD

**Issue by Lisio** [yiisoft/yii2#17810]
### What steps will reproduce the problem?
Set property type, e.g.
```php
public array $dummy;
```

Validate it using each validator
```php
[
   'dummy',
   'each',
   'rule' => [
       'boolean',
   ],
],
```

### What is the expected result?
No errors

### What do you get instead?
TypeError
https://github.com/yiisoft/yii2/blob/master/framework/validators/EachValidator.php#L143

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.4.1
| Operating system | Ubuntu 16.04

**Comment by rob006** [comment]
Related: https://github.com/yiisoft/yii2/issues/16852

**Comment by ricardomm85** [comment]
Hi @Lisio 

You can prevent this error initializing the property.

`public array $dummy = [];`
