### ISSUE TITLE
Вспомогательный класс WhereConditionToDataFilter для ядра Yii2

### ISSUE THREAD

**Issue by alhimik1986** [yiisoft/yii2#17817]
Приветствую.

## Ситуация:
У нас появилась необходимость получать данные из удалённых yii2-приложений. Для этого мы сделали специальные модели, у которых ActiveQuery принадлежат расширению hiqdev/yii2-hiart. Таким образом модели получают данные даже не зная, что они получают их из удалённых серверов.

## Проблема:
Для приёма запросов используется yii\data\DataFilter.php, принимающий json-формат, который немного отличается от формата yii\db\Query->where. Чтобы сделать эти форматы совместимыми, пришлось сделать специальный конвертер.

## Предложение:
Хотелось бы поделиться своей наработкой. На данный момент она сырая и необкатанная, но вещь, как считаю, необходимая. И ещё пока не знаю, куда её воткнуть, возможно, в yii\data\WhereConditionToDataFilter.php

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by alhimik1986** [comment]
@samdark  Я создал pull request
https://github.com/yiisoft/yii2/pull/17818

**Comment by samdark** [comment]
Спасибо, но новая фича не очень укладывается в Yii 2, в который новые фичи не принимаются. Лучше будет выпустить это в виде расширения.
