### ISSUE TITLE
Weird zero returned items on PHP7.4

### ISSUE THREAD

**Issue by juanmacias** [yiisoft/yii2#17823]
### What steps will reproduce the problem?

```php
 echo Order::find()->andWhere(['<', 'shipping_label_printed_date', strtotime('yesterday')])->
        andWhere(['>', 'shipping_label_printed_date', strtotime('last month')])->andWhere(['shipping_country' => 'ES'])->
        andWhere(['provider_id' => $this->connection->provider_id])->
        andWhere(['delivery_notified' => false])->
        andWhere(['<>', 'delivery_status', [Order::DELIVERY_STATUS_PENDING]])->
        orderBy('shipping_label_printed_date asc')->limit(300)->
        count();
        echo PHP_EOL;
  echo Order::find()->andWhere(['<', 'shipping_label_printed_date', strtotime('yesterday')])->
        andWhere(['>', 'shipping_label_printed_date', strtotime('last month')])->andWhere(['shipping_country' => 'ES'])->
        andWhere(['provider_id' => $this->connection->provider_id])->
        andWhere(['delivery_notified' => false])->
        andWhere(['<>', 'delivery_status', Order::DELIVERY_STATUS_PENDING])->
        orderBy('shipping_label_printed_date asc')->limit(300)->
        count();
```

### What is the expected result?
I expect the same count in both cases, as in PHP7.1
### What do you get instead?
0 for the first query, 111 for the second.

### Additional info
Generated SQLs are the same:

```
2020-01-22 19:48:44 [-][-][-][info][yii\db\Command::query] SELECT COUNT(*) FROM `order` WHERE (`shipping_label_printed_date` < 1579561200) AND (`shipping_label_printed_date` > 1577040524) AND (`shipping_co
untry`='ES') AND (`provider_id`=19) AND (`delivery_notified`=FALSE) AND (`delivery_status` <> 'PENDING')
2020-01-22 19:48:44 [-][-][-][info][yii\db\Command::query] SELECT COUNT(*) FROM `order` WHERE (`shipping_label_printed_date` < 1579561200) AND (`shipping_label_printed_date` > 1577040524) AND (`shipping_co
untry`='ES') AND (`provider_id`=19) AND (`delivery_notified`=FALSE) AND (`delivery_status` <> 'PENDING')
```

Even more weird:
if a create a command on first query, and I execute directly the query, it returns 111.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version   7.4.1   | 
| Operating system Debian|

**Comment by samdark** [comment]
1. Can the query be simplified?
2. Does it matter what database is used? It is the same on SQLite?
3. What's the schema?
4. What's the data?
5. Can we get a dump so we can reproduce it?

**Comment by juanmacias** [comment]
Found Problem:
 andWhere(['<>', 'delivery_status', [Order::DELIVERY_STATUS_PENDING]])->
Third parameter is an array:
In PHP 7.1 works, in PHP7.4 fails with this message:

Undefined offset: 1
Failed to prepare SQL: SELECT COUNT(*) FROM `order` WHERE (`shipping_label_printed_date` < :qp0) AND (`shipping_label_printed_date` > :qp1) AND (`shipping_country`=:qp2) AND (`provider_id`=:qp3) AND (`delivery_notified`=:qp4) AND (`delivery_status` <> :qp5)

in /vagrant/vendor/yiisoft/yii2/db/Command.php

The weird thing is that:
echo Order::find()->andWhere(['<>', 'delivery_status', [Order::DELIVERY_STATUS_PENDING]])->createCommand()->rawSql;
This works.
But this fails:
        echo Order::find()->andWhere(['<>', 'delivery_status', [Order::DELIVERY_STATUS_PENDING]])->createCommand()->count();

**Comment by samdark** [comment]
What's the schema of your `order` table?
