### ISSUE TITLE
error in setting bower-asset folder

### ISSUE THREAD

**Issue by antonellomangone** [yiisoft/yii2#17841]
In the file **yii2-framework/base/Application.php**

in the following function 

    public function setVendorPath($path)
    {
        $this->_vendorPath = Yii::getAlias($path);
        Yii::setAlias('@vendor', $this->_vendorPath);
        Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
        Yii::setAlias('@npm', $this->_vendorPath . DIRECTORY_SEPARATOR . 'npm');
    }

the following code:
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower'); 

is not correct, you have to correct it in this way:
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . **'bower-asset'**);

because the folder created when downloading the dipendencies is **bower-asset**

**Comment by samdark** [comment]
Yes, it's done in application config: https://github.com/yiisoft/yii2-app-basic/blob/master/config/web.php#L11. Can't change that because before witching to current way of asset fetching, the path was correct and there are still apps following old way.
