### ISSUE TITLE
numbers in action name

### ISSUE THREAD

**Issue by ziaratban** [yiisoft/yii2#17844]
why we can access to a action with two way? is bug or feature?
in `SiteController.php` :
```php
public function actionFoo47Bar(){

}
```
`example.com/site/foo47-bar`
`example.com/site/foo-47-bar`

**Comment by alex-code** [comment]
I'd say it's more of a quirk with the way camel case works.
Numbers don't have a case so the dash won't do anything so it's effectively optional.

**Comment by samdark** [comment]
Yes, it's a quirk we can't change in 2.x because of backwards compatibility.

If the behavior is not desirable for you, you can enable strict URL parsing and provide rules for every action. Then it won't accept alternative URLs.
