### ISSUE TITLE
error checking session configuration parameter

### ISSUE THREAD

**Issue by schevgeny** [yiisoft/yii2#17843]
when checking for the presence of a parameter in the session configuration, checking in the variable $date the parameter "sameSite" comes in lower case
framework/web/Session.php 
and the exception does not work

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.33
| PHP version      | 7.2
| Operating system |

**Comment by alex-code** [comment]
Condition here [Session.php#L401](https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L401) should have lowercase key (`samesite`) for `$data` array.

**Comment by schevgeny** [comment]
> Condition here [Session.php#L401](https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L401) should have lowercase key (`samesite`) for `$data` array.

yes. now it is not working

**Comment by alex-code** [comment]
@schevgeny can you do a PR with the fix?
