### ISSUE TITLE
Won't validate empty dropdown

### ISSUE THREAD

**Issue by nilsburg** [yiisoft/yii2#17853]
Since https://github.com/yiisoft/yii2/commit/c59df914c1f544889eafc4d8aa64132ae1337102 when you have an empty dropdown that is required it passes validation (for example when it is filled with ajax results). The are comments in the commit referencing the issue https://github.com/yiisoft/yii2/commit/c59df914c1f544889eafc4d8aa64132ae1337102#r34433811 and https://github.com/yiisoft/yii2/commit/c59df914c1f544889eafc4d8aa64132ae1337102#commitcomment-33900124

https://github.com/yiisoft/yii2/blob/a3c5de3d3b4b11c452d421fceaddb89512a053de/framework/assets/yii.activeForm.js#L333

I am not sure if it is supposed to work that way...

**Comment by alex-code** [comment]
https://github.com/yiisoft/yii2/issues/17683

**Comment by nilsburg** [comment]
Ah sorry, didn't see that issue. Closing this one.

**Comment by alex-code** [comment]
Need to try and do a PR for this and learn some JS tests.
