### ISSUE TITLE
csrf token not working for multiple yii projects running on the same host

### ISSUE THREAD

**Issue by curtis18** [yiisoft/yii2#17851]
csrf tokens do not work for multiple yii projects running on the same host even set the config

Project 1 config
        'user' => [
            'identityCookie' => [
                'name' => '_project1User',
                'path'=>'/project1/web'
            ]
        ],
        'session' => [
            'name' => '_project1SessionId',
            'savePath' => __DIR__ . '/../runtime',
        ],

Project 2 config
        'user' => [
            'identityCookie' => [
                'name' => '_project2User',
                'path'=>'/project2/web'
            ]
        ],
        'session' => [
            'name' => '_project2SessionId',
            'savePath' => __DIR__ . '/../runtime',
        ],

### What steps will reproduce the problem?
1. open a browser tab and go to project 1 (https://192.168.1.11/project1/web) 
2. open a browser tab and go to project 2 (https://192.168.1.11/project2/web) 
3. go back the tab of project 1 and csrf does not work and will result in 404 when clicking logout or some links required a form to submit.

### What is the expected result?
csrf token can work among different projects under the same host

### What do you get instead?
404 not found. I tried to disable csrf and it becomes work.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29
| PHP version      | 7.2.27
| Operating system | Ubuntu 18.04

**Comment by rob006** [comment]
CSRF protection uses different cookie - you need to adjust https://www.yiiframework.com/doc/api/2.0/yii-web-request#$csrfParam-detail to be different for each project. Or disable `enableCsrfCookie`.
