### ISSUE TITLE
Fix github actions pipeline, add old PHP versions

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#17865]
1. Pipeline is currently giving errors :(
2. Older versions could be added https://github.com/shivammathur/setup-php/issues/169#event-3041922754
3. v2 enhancements could be used: https://github.com/shivammathur/setup-php/pull/177

**Comment by samdark** [comment]
@simialbi could you take a look at these?

**Comment by simialbi** [comment]
I'm on it

**Comment by simialbi** [comment]
nearby: https://github.com/simialbi/yii2/runs/450735548

**Comment by simialbi** [comment]
This is not action related any more I think:
```diff
1) yiiunit\framework\i18n\FormatterDateTest::testIntlAsDatetime
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2020-02-17T15:15:32+00:00'
+'2020-02-17T15:15:32'

/home/runner/work/yii2/yii2/tests/framework/i18n/FormatterDateTest.php:210
/home/runner/work/yii2/yii2/tests/framework/i18n/FormatterDateTest.php:169
/home/runner/work/yii2/yii2/vendor/phpunit/phpunit/phpunit:52
```

**Comment by samdark** [comment]
@simialbi yes. 5.6 seems to be action-related though...

**Comment by samdark** [comment]
The only thing left is https://github.com/yiisoft/yii2/runs/451440448#step:15:134. That's PHP 5.4 and intl/ICU related.

**Comment by simialbi** [comment]
And 5.5 is missing. I will make a new pr today bringing it back (if it works now)

**Comment by samdark** [comment]
@simialbi thanks! I think we need to wait till it's fixed. 20 minutes is too much...

**Comment by simialbi** [comment]
I agree, way too much

**Comment by samdark** [comment]
I've excluded 5.4 from that intl-dependent test so 5.4 is good now.

**Comment by samdark** [comment]
We're green ✔️ . Thank you for helping with it.
