### ISSUE TITLE
После обновления yii2 изменилась логика сравнения, с == на !==

### ISSUE THREAD

**Issue by i-coder** [yiisoft/yii2#17861]
После обновления yii2 изменилась логика сравнения, с == на !== при этом String("0") сравнивает с int(0) 

Проблема в yii\web\UploadedFile  saveAs()
[http://prntscr.com/r24urk]
[http://prntscr.com/r24vth]

Само обновление 
Enh #17729: Path alias support was added to yii\web\UploadFile::saveAs() (sup-ham)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.2
| Operating system | Windows 10

**Comment by eLFuvo** [comment]
After upgrading yii2 from 2.0.30 to 2.0.32 normal uploading files (by POST method) does not works.
I have get a error: 
> copy(/var/www/demo2.rosmintrud.ru/tmp/phpQwOV1W): failed to open stream: No such file or directory

An error occurs in this method
```
    protected function copyTempFile($targetFile)
    {
        if (!is_resource($this->_tempResource)) {
            return $this->isUploadedFile($this->tempName) && **copy**($this->tempName, $targetFile);
        }
```
I have chenged `copy` to `move_uploaded_file` and it works fine.

Q | A
-- | --
Yii version | 2.0.32
PHP version | 7.1.8
Operating system | Linux



P.S. seems as a typo.
```
    public function getHasError()
    {
        return $this->error != UPLOAD_ERR_OK;
    }
```

**Comment by dicrtarasov** [comment]
@i-coder не понятно в чем проблема - изменения логики к лучшему - это есть хорошо.
Сравнение int UploaedFile::error с int UPLOAD_ERR_OK - тоже есть хорошо.
Откуда там взялось string "0" ?

**Comment by dicrtarasov** [comment]
@samdark может быть у человека эта проблема связана вот с этим странным коммитом: https://github.com/yiisoft/yii2/commit/82b7ecbdf30f692d50f8bc658a0f698b23bf9b85

Здесь зачем-то поменяли `int` 0 в error на строку "0"..... очень странно, хотя в php у этого поля тип int....

**Comment by samdark** [comment]
@dicrtarasov может быть, а может и нет. Пока не будет ясно, что именно не так, мы не сможем 
это поправить...

**Comment by samdark** [comment]
Duplicate of #17896
