### ISSUE TITLE
Pretty url not working properly in Yii2

### ISSUE THREAD

**Issue by IntegrityFoundation** [yiisoft/yii2#17864]
Hi, I am using Yii2 basic and enable the pretty url in my application configuration. When I log into the application the user gets redirected to his dashboard page as required. He can see the menus on the side bar such as Dashboard,Role Assignments, Employee,etc.  Now when the user clicks on Empolyee menu, he can see the CRUD for Employee. Now when click on Create button from Employee, the create page is displayed. Now from create page if i click on Dashboard menu, then Not Found error id displayed. The url gets http://localhost/new_basic/web/index.php/employee/dashboard

Below is the url configuration

~~~~
'urlManager' => [
            'enablePrettyUrl' => true,
            //'showScriptName' => false,
           'rules' => [
                        'dashboard' => 'dashboard/index',
			'employee'=>'employee/index',],
        ],
~~~~

**Comment by samdark** [comment]
What's you web server? Have you configured it according to https://www.yiiframework.com/doc/guide/2.0/en/start-installation#configuring-web-servers?

**Comment by IntegrityFoundation** [comment]
I am using XAMPP web server and I am on localhost

**Comment by samdark** [comment]
1. You should have mod_rewrite enabled.
2. Your webroot should point to web directory, not several directories above.
