### ISSUE TITLE
Clear the CAT

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#17866]
### What steps will reproduce the problem?
Go to the page https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.0/yii-bootstrap-activefield#radioList()-detail
Click on the [All classes](https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.0/index.html) link on top left 
![image](https://user-images.githubusercontent.com/1536454/74652567-1bbdca80-51a8-11ea-9bc6-e9b34fe66199.png)

### What is the expected result?
The all classes list 
### What do you get instead?
![image](https://user-images.githubusercontent.com/1536454/74652594-3001c780-51a8-11ea-834e-7049b00dde5c.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/issues/386

**Comment by samdark** [comment]
Same issue. No time to fix it yet.
