### ISSUE TITLE
`\yii\helpers\BaseInflector::slug()` doesn't work with an empty string as a replacement argument.

### ISSUE THREAD

**Issue by HaruAtari** [yiisoft/yii2#17863]
### What steps will reproduce the problem?

```
Inflector::slug('text', '')
```
### What is the expected result?

```
text
```
### What do you get instead?

```
[yii\base\ErrorException] explode(): Empty delimiter
```

### Additional info

After [this commit](https://github.com/yiisoft/yii2/commit/1342eb718b6674c6ade3f2887dcf0710d2987e3b#diff-1d93dd129d9cbdd656d16f9f4716e24e) `\yii\helpers\BaseInflector::slug()` method cann't work with empty string as a `$replacement` argument. But it's needed for slugging with removing spaces.

May be it can be fixed by adding the checking like this:

```
if ($replacement) {
    $parts = explode($replacement, static::transliterate($string));
} else {
    $parts = [static::transliterate($string)];
}
```

| Q                | A
| ---------------- | ---
| Yii version      | >2.0.16?
| PHP version      | Any
| Operating system | Any

**Comment by samdark** [comment]
@HaruAtari would you please do a pull request?

**Comment by HaruAtari** [comment]
@samdark Yes, I'll try it.
