### ISSUE TITLE
Incorrect log level of \yii\db

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#17870]
`yii\db` package log low-level trace messages to `info` level:
```
2020-02-18 02:15:17 [46.146.34.244][9075][-][info][yii\web\Session::open] Session started
2020-02-18 02:15:17 [46.146.34.244][9075][-][info][yii\db\Connection::open] Opening DB
2020-02-18 02:15:17 [46.146.34.244][9075][-][info][yii\db\Command::query] SELECT * FROM `user`  
```
Default application log must not contains low level DB messages at info level, because it generates huge log files which become unusabe for important messages. There must be more important information messages at this level.

Excluding `yii\db\*` from log target by adding exception: 
```php
'except' => ['yii\db\*']
```
is not a right way for default configuration and also will disable error and warning messages from \yii\db.

There are no good workaround for this except of separate db-error.log for yii\db :(

**Comment by dicrtarasov** [comment]
From Wiki:
https://en.wikipedia.org/wiki/Syslog#Severity_level

`Info` level used for information messages such as staring/stopping jobs or business logic, ex. "use login", "order send". Dumping full SQL queries with data is a debugging level, not a info.

quote: "INFO messages correspond to normal application behavior and milestones.  You probably won’t care too much about these entries during normal operations, but they provide the skeleton of what happened.  A service started or stopped.  You added a new user to the database.  That sort of thing."

quote: "The INFO level should be used to document state changes in the application or some entity within the application. This information can be helpful during development and sometimes even in production to track what is actually happening in the system.
Concrete examples for using the INFO level are:
the application has started with configuration parameter x having the value y
a new entity (e.g. a user) has been created or changed its state
the state of a certain business process (e.g. an order) has changed from “open” to “processed”
a regularly scheduled batch job has finished and processed z items."

**Comment by samdark** [comment]
You are correct but the change may cause issues for many projects already relying on this logging level.

**Comment by rob006** [comment]
Related: https://github.com/yiisoft/yii2/issues/17750 and https://github.com/yiisoft/yii2/pull/16671.

**Comment by cebe** [comment]
The problem with changing to `trace` level is that these are excluded before being added to the logger in production environment, so you can not log SQL queries in production with a higher log level.

https://github.com/yiisoft/yii2/blob/55793471eafbcac75b0f1e0bd3ea187b9abed5fe/framework/BaseYii.php#L406-L408

**Comment by cebe** [comment]
You can disable logging these messages:
