### ISSUE TITLE
Saving of uploaded files does not works.

### ISSUE THREAD

**Issue by eLFuvo** [yiisoft/yii2#17875]
After upgrading yii2 from 2.0.30 to 2.0.32 normal uploading files (by POST method) does not works.
I have get a error: 
> copy(/var/www/site.com/tmp/phpQwOV1W): failed to open stream: No such file or directory

An error occurs in this method:
```php
class UploadedFile extends BaseObject
{
...
  protected function copyTempFile($targetFile)
  {
   if (!is_resource($this->_tempResource)) {
 ->     return $this->isUploadedFile($this->tempName) && copy($this->tempName, $targetFile);
  }
```
I have changed `copy` to `move_uploaded_file` and it works fine

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.1.8
| Operating system | Linux

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/yii2/pull/17729. @sup-ham would you please take a look?

**Comment by samdark** [comment]
@eLFuvo would you please check if https://github.com/yiisoft/yii2/pull/17877 fixes the issue?

**Comment by eLFuvo** [comment]
I have checked this fixes in real-world project. 
Works properly.

Thanks for your support!
