### ISSUE TITLE
Method MysqlMutex::acquire returns bool at version > 2.0.15

### ISSUE THREAD

**Issue by n0tm** [yiisoft/yii2#17872]
Hello! My team decided to upgrade our project based on Yii version "~ 2.0.0"
Now version of our project is 2.0.32, i read the changelog (https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md#upgrade-from-yii-2015)
and i have noticed that method acquire in class MysqlMutex NOT "no longer returns true if lock is already acquired". Method still return bool value. I've a little bit confused, am i doing something wrong? Or this is a bug?

### What steps will reproduce the problem?
Try to create instance of MysqlMutex class and try to use method acquire.
![Screenshot from 2020-02-18 15-35-34](https://user-images.githubusercontent.com/38406016/74736699-600ea080-5264-11ea-8dbd-9e19ac8caf61.png)

### What is the expected result?
Method MysqlMutex::acquire will void

### What do you get instead?
Method MysqlMutex::acquire returns bool 

I'am executing acquire method from vagrant machine.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.2.27-6
| Operating system | Linux Ubuntu 16.04.6 LTS (Xenial Xerus)

**Comment by samdark** [comment]
It does not say it won't return boolean:

> // `Yii::$app->mutex->acquire('test')` will always return `false` here, since lock is already acquired
