### ISSUE TITLE
yii\rest\Serializer should serialize arrays

### ISSUE THREAD

**Issue by patacca** [yiisoft/yii2#17886]
### What steps will reproduce the problem?
Consider the following code

```php
class MyModel extends ActiveRecord {
    // ...

   public function fields() {
      return ['id', 'test1','test2'];
   }

   public function extraFields() {
      return ['testExtra' => function ($model, $field) { return ['key' => 'value',]; };
   }
}

// ..
class MyController extends RestController {
   public function actionTest() {
       $query = MyModel::find();
       return $query->all();
   }
}
```

### What is the expected result?
```json
[
    {
        "id": 1,
        "test1": "xxx",
        "test2": "yyy",
        "testExtra" : {
           "key": "value"
        }
    }
]
```
### What do you get instead?
```json
[
    {
        "id": 1,
        "test1": "xxx",
        "test2": "yyy"
    }
]
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.33
| PHP version      | 7.4.1
| Operating system | Arch Linux (Linux 5.4.10-arch1-1  x86_64 09/01/2020)

**Comment by patacca** [comment]
I've submitted the patch on branch `17886_serialize-arrays` of my fork of yii2. I don't know how to submit patch nor pull request but if you want you can merge this commit
[https://github.com/patacca/yii2/commit/c7885985a9bd06d1ce96f0a08789a75609b74707](url)

**Comment by samdark** [comment]
Pull requested it.
