### ISSUE TITLE
Console Table renders '0' as empty string

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#17884]
# What steps will reproduce the problem?

```
echo Table::widget([
    'rows' => [
        ['Total', '0'],
    ],
]);
```
### What is the expected result?

```
╔══════════════════════╤══════╗
║ Total                │    0 ║
╚══════════════════════╧══════╝
```
### What do you get instead?

```
╔══════════════════════╤══════╗
║ Total                │      ║
╚══════════════════════╧══════╝
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      |  7.3.11
| Operating system | Debian

### Suggested fix

The rewrite of row values in `setRows()` should be modified:

```php
    public function setRows(array $rows)
    {
        $this->rows = array_map(function($row) {
            return array_map(function($value) {
                return $value ?: ' ';
            }, array_values($row));
        }, $rows);
        return $this;
    }
```

It should better use this in the inner `array_map()`:

```php
return empty($value) && $value !== '0' ? ' ' : $value;
```

**Comment by lubosdz** [comment]
perhaps simpler: `trim($value) === '' ? ' ' : $value`
