### ISSUE TITLE
Serializer should recursively serialize Models

### ISSUE THREAD

**Issue by patacca** [yiisoft/yii2#17889]
### What steps will reproduce the problem?
Consider the following test
You can put it inside test/framework/rest/SerializerTest.php

```php
class TestModel5 extends Model
{
    public static $fields = ['field3', 'field4'];
    public static $extraFields = [];

    public $field3 = 'test3';
    public $field4 = 'test4';
    public $extraField4 = 'testExtra2';

    public function fields()
    {
        $fields = static::$fields;
        $fields['testDataProvider'] = function() {
            return $this->getTestDataProvider();
        };
        $fields['testDataProviderArray'] = function() {
            return [$this->getTestDataProvider(), 'testKey' => $this->getTestDataProvider()];
        };
        return $fields;
    }

    public function extraFields()
    {
        return static::$extraFields;
    }

    public function getTestDataProvider()
    {
        return new ArrayDataProvider([
            'allModels' => [
                ['id' => 1, 'username' => 'Bob'],
                ['id' => 2, 'username' => 'Tom'],
            ],
            'pagination' => [
                'route' => '/',
                'pageSize' => 1,
                'page' => 1,
            ],
        ]);
    }
}

public function testSerializeModelComplex()
{
	$serializer = new Serializer();
	$serializer->preserveKeys = true;
	$model = new TestModel5();
	
	$this->assertEquals([
		'field3' => 'test3',
		'field4' => 'test4',
		'testDataProvider' => [1 => ['id' => 2, 'username' => 'Tom']],
		'testDataProviderArray' => [
			[1 => ['id' => 2, 'username' => 'Tom']],
			'testKey' => [1 => ['id' => 2, 'username' => 'Tom']]
		]
	],
	$serializer->serialize($model));
}

```
### What is the expected result?

It should pass the test

### What do you get instead?

It doesn't pass the test

### Additional info

The problem is that inside `Serializer::serializeModel` the model is converted to an array without considering that some of its elements might not be directly convertable to an array. `ArrayableTrait::toArray` in fact consider only these types `Arrayable`, `array` and `JsonSerializable` and for the others it just call `ArrayHelper::toArray`. If we pass a `DataProviderInterface`, as in the above test, it will not be serialized

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.33
| PHP version      |  7.4.1
| Operating system | Arch Linux (Linux 5.4.10-arch1-1 09/01/2020 x86_64)

**Comment by xepozz** [comment]
I don't think that using `DataProvider` in `Model`  and `\yii\rest\Serializer` in `\yii\base\ArraybleTrait` are good idea.

Subj:
I think it should be solved by fix `\yii\rest\Serializer`, not `\yii\base\ArraybleTrait`. Serializer should recursively serialize each element.

**Comment by patacca** [comment]
> I don't think that using DataProvider in Mode [...] are good idea.

I guess you are right, in this case maybe in the documentation it should be pointed out that `Serialzer` doesn't recurisvely serialize `DataProviderInterface` in Models


Unfortunately it's not an easy fix inside `Serializer` because the model is converted into an array (after all it extends `Arrayable`). The only way I can think of would be not relying on `toArray` and instead implement our own method to serialize Models inside `Serializer` and that is even uglier.

**Comment by samdark** [comment]
@yiisoft/core-developers, @yiisoft/reviewers any ideas?

**Comment by germanow** [comment]
I think this case is very artificial. If we serialize dataprovider in attribute, how we will do pagination? It's pointless.
