### ISSUE TITLE
Pagination Link Options

### ISSUE THREAD

**Issue by Shibon-ll** [yiisoft/yii2#17898]
Yii2 pagination is showing as 1 2 3 4 5 6 7 8 9 10 for large number of rows
Instead there an option required to show some thing like this
1 2 3 . . .5 . . 28 29 30 that will become user friendly and common behavior

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.
| PHP version      | any
| Operating system |any

**Comment by samdark** [comment]
Thanks for suggestion but we won't implement it (feature-freeze of Yii 2 happened several years ago, Yii 3 is in development). You can do it yourself starting with https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php
