### ISSUE TITLE
Version 2.0.32 breaks functional tests using attachFile method

### ISSUE THREAD

**Issue by OmgDef** [yiisoft/yii2#17896]
### What steps will reproduce the problem?
Version 2.0.32 breaks functional tests using an ```attachFile``` method.
The issue is here: https://github.com/yiisoft/yii2/blob/2.0.32/framework/web/UploadedFile.php#L178
In tests, ```$this->error``` is a string while ```UPLOAD_ERR_OK``` is an integer.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version     | 7.2.24
| Operating system| Debian

**Comment by OmgDef** [comment]
Related to #17861

**Comment by samdark** [comment]
@OmgDef need help reproducing the issue.
