### ISSUE TITLE
useTransparentSessionID doesn't work

### ISSUE THREAD

**Issue by carlb0329** [yiisoft/yii2#17892]
### What steps will reproduce the problem?
In config/main.php set the session component config as follows:
```php
'session' => [
            'name' => 'advanced-frontend',
            'useCookies'=>false,
            'useTransparentSessionID'=>true,
]
```

### What is the expected result?
Session ID should be passed as a $_GET param.

### What do you get instead?
Session ID is NOT currently passed in $_GET or anywhere else in the request.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.3.8
| Operating system | Linux

**Comment by samdark** [comment]
I confirm the issue.

**Comment by rdavidcz** [comment]
PHP can't handle trans_sid via header() redirects (used in actionLogin() in case below).
You have to append the session_name and session_id manually to redirect.

Modify your actionLogin()

```<?php
public funtion actionLogin()
{
// .... some code

$model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            return $this->redirect(['site/index', Yii::$app->session->name => Yii::$app->session->id], 302);
        }

// ... some code
}
```
This applies to all "POST-redir-GET" scenarios (login, update and delete for example).
Tested and works fine for me.

**Comment by samdark** [comment]
Seems can't be fixed from within the framework.
