### ISSUE TITLE
ClickHouse support 

### ISSUE THREAD

**Issue by Aresenka** [yiisoft/yii2#17901]
Would Yii2 support ClickHouse database out of the box? Now it is kak/clickhouse extension there, but popularity of clickhouse is grow up day by day.

So it would be perfect if Yii2 could support that awesome database.

**Comment by samdark** [comment]
Out of the box — no.

Quick googling reveals multiple extensions for it:

- https://github.com/bashkarev/clickhouse
- https://github.com/sanchezzzhak/kak-clickhouse
