### ISSUE TITLE
Error in framework/db/mysql/QueryBuilder.php // line 398

### ISSUE THREAD

**Issue by mms1989** [yiisoft/yii2#17906]
On Line 398 is:
$schemaCache = (\Yii::$app && is_string($this->db->schemaCache) ? \Yii::$app->get($this->db->schemaCache, false) : $this->db->schemaCache;

Should Be: 
        $schemaCache = (\Yii::$app && is_string($this->db->schemaCache)) ? \Yii::$app->get($this->db->schemaCache, false) : $this->db->schemaCache;

**Comment by InsaneSkull** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/db9e2fa7099fb4132f49743c9e06147daa1a33ac

**Comment by mms1989** [comment]
> Fixed in [db9e2fa](https://github.com/yiisoft/yii2/commit/db9e2fa7099fb4132f49743c9e06147daa1a33ac)

Still wrong place of this bracket.

**Comment by samdark** [comment]
I'm sleep-coding :)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/b7723aebcf4e44f9af4c1833da90ca82c9d43684
