### ISSUE TITLE
Geometry byte string must be little endian

### ISSUE THREAD

**Issue by chief725** [yiisoft/yii2#17905]
### What steps will reproduce the problem?
	$query->where ( "ST_Distance_Sphere(:point, `point`) < 1000", [
		'point' => new Expression ( "geomfromtext('POINT(103 1.3)') "),
	] );
### What is the expected result?
shoud no error. I run the sql command in phpmyadmin, no error. 

### What do you get instead?
SQLSTATE[HY000]: General error: 3055 Geometry byte string must be little endian.
The SQL being executed was: **SELECT COUNT(*) FROM `node` WHERE  (ST_Distance_Sphere(geomfromtext('POINT(103 1.3)') , `point`) < 1000)**

   Error Info: Array
    (
    [0] => HY000
    [1] => 3055
    [2] => Geometry byte string must be little endian.
    )

### Additional info
I run the code using createCommand, no error.
    $command = Yii::$app->getDb()->createCommand($query->createCommand()->rawSql);
    $result = $command->queryAll();

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | v7.3.4
| Operating system | debian 10

**Comment by alex-code** [comment]
What is the `type` of the `point` column?
Does it work with `ST_GeomFromText`?

**Comment by chief725** [comment]
> What is the `type` of the `point` column?
> Does it work with `ST_GeomFromText`?

the type is point.

I have change the query , now works fine. but not secure.

	$query->andWhere ( "ST_Distance_Sphere(point($lng,$lat), `point`) < :radius",[
		'radius'=>$this->radius
	]);

**Comment by chief725** [comment]
> What is the `type` of the `point` column?
> Does it work with `ST_GeomFromText`?

the rawsql yii2 claims have problem, runs ok if directly in mysql console.

**Comment by alex-code** [comment]
Something happens in `bindValue` with `PDO`.

**Comment by alex-code** [comment]
Looked at this again.
I think this is from `Expression`s being treated as strings when in params.
e.g.
```php
(new \yii\db\Query)
  ->from('my_table')
  ->where('NOW() = :now', [':now' => new yii\db\Expression('NOW()')])
  ->scalar());
```
Will actually execute as on MySQL (with quotes)
```sql
SELECT * FROM `my_table` WHERE NOW() = 'NOW()'
```
The DB query log on the debug toolbar causes a bit of confusion as it reports the query as (without quotes)
```sql
SELECT * FROM `my_table` WHERE NOW() = NOW()
```

**Comment by alex-code** [comment]
Should `Expression`s in params be treated differently?

Two options I can think of,
Use `strtr` on `Expression`s in params to replace placeholders or update `Command::getRawSql()` so expressions are quoted for consistency.

**Comment by samdark** [comment]
> Should Expressions in params be treated differently?

Well, actually no. It accepts parameters as a second argument already.

**Comment by alex-code** [comment]
Ok, I think `Command::getRawSql()` should quote expressions in params as it'll cause confusion as is.

**Comment by samdark** [comment]
Yes. Would be good. Would you please pull request it?
