### ISSUE TITLE
Spaces in .env.dist file

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#17908]
When building site via Yii 2 starter kit on docker on windows - issuing command `composer run-script docker:build`, the build fails with the message

Output:

> cp .env.dist .env
> docker-compose up --force-recreate -d
In file .\.env: environment variable name 'YII_DEBUG       ' may not contains whitespace.
Script docker-compose up --force-recreate -d handling the docker:start event returned with error code 1
Script @docker:start was called via docker:buil

Reason 
The default `.env.dist` file in the root directory contains environmental variables formatted/aligned with spaces, and the docker fails to parse them.
Workaround 
replace all the space characters in the environmental variables file .env.dist with no character, eg. in Notepad++ editor

**Comment by samdark** [comment]
What is "Yii 2 starter kit"? Which `.env.dist` are you talking about? Would you please post a link to the file in question?

**Comment by buttflattery** [comment]
wrong repo
