### ISSUE TITLE
\yii\i18n\Formatter::asDatetime() takes $value in application's timezone but not in default timezone

### ISSUE THREAD

**Issue by HaruAtari** [yiisoft/yii2#17911]
In PhpDoc for a `\yii\i18n\Formatter::asDatetime()` method for a `$value` argument we can read:

```
* - a string that can be [parsed to create a DateTime object](https://secure.php.net/manual/en/datetime.formats.php).
*   The timestamp is assumed to be in [[defaultTimeZone]] unless a time zone is explicitly given.
```

So it must take value in default time zone. But it doesn't. It takes it in a timezone of an application. Looks like a bug.

### What steps will reproduce the problem?

```
\Yii::$app->formatter->timeZone = 'Europe/Moscow';
\Yii::$app->formatter->defaultTimeZone = 'UTC';
var_dump(\Yii::$app->formatter->asDatetime('2020-03-03 10:00:00'));
var_dump(\Yii::$app->formatter->asDatetime('2020-03-03 10:00:00UTC'));
```

### What is the expected result?

```
string(19) "2020-03-03 13:00:00"
string(19) "2020-03-03 13:00:00"
```

### What do you get instead?

```
string(19) "2020-03-03 10:00:00"
string(19) "2020-03-03 13:00:00"
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | ANY
| Operating system | ANY

**Comment by rob006** [comment]
Why do you think that there should be difference between `Yii::$app->formatter->asDatetime('2020-03-03 10:00:00')` and `Yii::$app->formatter->asDatetime('2020-03-03 10:00:00UTC')` if default timezone is UTC?

**Comment by HaruAtari** [comment]
@rob006 Ouch, I mixed up expected and read results in a description. My fault. I updated the description.
So results should be similar, but in reality they are different.

**Comment by rob006** [comment]
@HaruAtari Can you write a test case for this? I'm not able to reproduce this - I'm getting the same value for both cases.

**Comment by HaruAtari** [comment]
It was an error in overwrited `normalizeDatetimeValue` method. There are no errros in the framework.
