### ISSUE TITLE
Response returns status code 500, when returning custom status code

### ISSUE THREAD

**Issue by DMGPage** [yiisoft/yii2#17915]
### What steps will reproduce the problem?
So, my problem occurs, when I try to return in one of my controllers custom status code for JavaScript code, which processes that response. When I return any of Response::$httpStatuses defined status codes, it works just fine. But when I'm trying to return something else, it always returns status code 500. To reproduce, just put "Yii::$app->response->statusCode = 255;" in any controller.

From StackOverflow I understand, that there is nothing wrong on returning custom status code (https://stackoverflow.com/a/11871377/6218599). So, I do not see what I'm doing wrong here.

### What is the expected result?
Status code, that I'm setting.

### What do you get instead?
I get status code 500.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.4.2
| Operating system |Ubuntu 18.04

**Comment by alex-code** [comment]
Can you show more of your action?
Putting this in an action works for me, `Yii::$app->response->statusCode = 255;`

**Comment by DMGPage** [comment]
There's really nothing more to show. I tested few my projects and 2 Yii versions and result always the same. Page is rendering correctly, but in browser I see wrong status code:

Request method:GET
Remote address:127.0.1.1:80
Status code: 500 Internal Server Error
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade

**Comment by alex-code** [comment]
What error do you get in your server log?

**Comment by My6UoT9** [comment]
Is an ajax request? Pls give more details!

**Comment by DMGPage** [comment]
Oh I found, that only way how to make it work is to set not only status code, but status text too:
```
Yii::$app->response->statusCode = 255;
Yii::$app->response->statusText = 'Form reloading';
```

Then it works fine. My only complaint now, why it does not send any error message or something, that could help me to understand problem? Or else it's just guessing, what it wants fro me. 

> What error do you get in your server log?
I checked all log files, but there are no error, related to this. I think, it just resets my status code in result.

> Is an ajax request? Pls give more details!
My goal is ajax request, but same result I get even on regular page.

**Comment by alex-code** [comment]
What server software are you using?

**Comment by DMGPage** [comment]
I have different servers. From PHP 5.6 on Ubuntu 14.04.6 to php 7.4 on Ubuntu 18.04. Even tested this on xampp with php 7.4, but result always the same. I do not understand, why you guys can't reproduce that.

**Comment by alex-code** [comment]
Are you able to reproduce if you test on the basic app template?

**Comment by samdark** [comment]
Seems to be server specific. Cannot reproduce it.
