### ISSUE TITLE
Yii::$app->security->validatePassword($password, $hash) cost 500ms+

### ISSUE THREAD

**Issue by ikraddy** [yiisoft/yii2#17912]
hei,i use Yii2.0.32,i need RestfulAPI to my app,but when i use Yii::$app->security->validatePassword() to validate user password in my api,it cost too much time to validate,is there anyone can help,develop enviroment:centos + mysql8 + php7.4,thanks

**Comment by rob006** [comment]
You can set `Security::$passwordHashCost` to lower value (the setting will affect only new passwords hashes), but this is not recommended. The whole point of modern password hashing algorithms is that they're not efficient, so it is hard to brute-force them. 500ms looks like pretty standard time for this kind of task.

**Comment by ikraddy** [comment]
> You can set `Security::$passwordHashCost` to lower value (the setting will affect only new passwords hashes), but this is not recommended. The whole point of modern password hashing algorithms is that they're not efficient, so it is hard to brute-force them. 500ms looks like pretty standard time for this kind of task.
Thanks @rob006 , Maybe I should know more about the password hashing algorithms,as you said,this should be a normal phenomenon.
