### ISSUE TITLE
fatal: failed to read object 5c7ca9836cf80b34db265332a7f2f8438eb469b9: Operation not permitted

### ISSUE THREAD

**Issue by jonatasfl** [yiisoft/yii2#17927]
### What steps will reproduce the problem?
`composer install` inside a yii2-basic project
### What is the expected result?
Install all Yii2 dependencies
### What do you get instead?

> Installing yiisoft/yii2-composer (2.0.8): Cloning 5c7ca9836c from cache
    5c7ca9836cf80b34db265332a7f2f8438eb469b9 is gone (history was rewritten?)
> [RuntimeException]
  Failed to execute git checkout '5c7ca9836cf80b34db265332a7f2f8438eb469b9' -- && git reset --hard '5c7ca9836cf80b34d
  b265332a7f2f8438eb469b9' --
> fatal: failed to read object 5c7ca9836cf80b34db265332a7f2f8438eb469b9: Operation not permitted

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | ~2.0.14
| PHP version      | 7.3.16
| Operating system | Windows 10

**Comment by samdark** [comment]
Where did you get the project from?

**Comment by jonatasfl** [comment]
@samdark It's my project. It's actually running in other environment in my work, but I'm trying to install in other PC and getting this error. 

Sorry for my bad english!

**Comment by samdark** [comment]
Is there a way for me to reproduce it somehow?

**Comment by jonatasfl** [comment]
> Is there a way for me to reproduce it somehow?

I just tested it by creating a new project with `composer create-project --prefer-dist yiisoft/yii2-app-basic basic` and the same thing happened.

**Comment by samdark** [comment]
Just tried it. Installed without issues.
