### ISSUE TITLE
ActiveRecord + DI-container bug (may be)

### ISSUE THREAD

**Issue by keeper-evil** [yiisoft/yii2#17924]
### What steps will reproduce the problem?
Simple example. User is a child class for ActiveRecord. Profile is a child class for ActiveRecord. DiProfile is a child class for Profile.
There is a method in User:
```php
    public function getProfile()
    {
        return $this->hasOne('common\models\Profile', ['id' => 'profile_id']);
    }
```
There is a code in DI-container:
```php
    /** @var yii\di\Container $container */
    $container->set('common\models\Profile', 'common\models\DiProfile');
```
I'm trying to get a user profile:
```php
    /** @var common\models\User $user */
    $user->profile;
```

### What is the expected result?
Instance of DiProfile.

### What do you get instead?
Instance of Profile.

### Additional info
Because there is a method in BaseActiveRecord:
```php
    public static function instantiate($row)
    {
        return new static();
    }
```
instead:
```php
    public static function instantiate($row)
    {
        return Yii::createObject(get_called_class());
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.2.24
| Operating system |ubuntu

**Comment by rob006** [comment]
This is intentional - AR does not use container for performance reasons. It is also debatable whether using container in this way for AR is a good idea in the first place.

**Comment by keeper-evil** [comment]
May be. This is convenient when I need to implement separate logic for a specific action. For example, when overriding [beforeSave](https://www.yiiframework.com/doc/api/2.0/yii-db-baseactiverecord#beforeSave()-detail) and [afterSave](https://www.yiiframework.com/doc/api/2.0/yii-db-baseactiverecord#afterSave()-detail).

**Comment by samdark** [comment]
You may overwrite `instantiate($row)` as you need. Won't be changed in the framework. As @rob006 said, it's intentional.

**Comment by TonisOrmisson** [comment]
It seems it also means that using constructor injection as described in documentation effectively is not working for ActiveRecord models when any ::find() call is used.
