### ISSUE TITLE
docs page not found. error 404 in the blob docs

### ISSUE THREAD

**Issue by romanown** [yiisoft/yii2#17928]
on the page on bottom 

> сконфигурировано следующим образом

[https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/rest-response-formatting.md](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/rest-response-formatting.md)
link not have the web page
[https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/concept-configuration.md](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/concept-configuration.md)
on russian and english version. correct link is
[https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/concept-configurations.md](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/concept-configurations.md)

**Comment by samdark** [comment]
Fixed. Thanks!

**Comment by romanown** [comment]
Thank and You! Спасибо и Вам.
