### ISSUE TITLE
YII_DEBUG makes a non functional page in live work

### ISSUE THREAD

**Issue by crimson-med** [yiisoft/yii2#17921]
### What is the expected result?

The page should be either working of when setting `YII_DEBUG` I should be able to see what is making the app crash.

### What do you get instead?

If my env.php file does **not** have:

```php
defined('YII_DEBUG') or define('YII_DEBUG', true); 
```

the url results to a 200 blank page:

```
<html><head></head><body></body></html>
```

if I add to my env.php file on my live server:

```php
defined('YII_DEBUG') or define('YII_DEBUG', true); 
```

Then the page appears with no errors.

I have currently set:

```php
memory_limit = -1
max_execution_time = -1
max_input_time = -1
```

I have also tried turning `display_startup_errors` and `display_errors` to `on`

for debugging purposes I have set `error_reporting = E_ALL`

I have also tried adding the following at the top of `web/index.php`

```php
error_reporting(-1);
ini_set('display_errors', true);
ini_set('display_startup_errors', TRUE);
```

and I still get blank screen

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.17
| Operating system | development: macos, deployed: Amazon Linux version 2018.03 is available.

Is it possible to know what YII_DEBUG is impacting on php that could drop the request from processing.

**Comment by samdark** [comment]
YII_DEBUG itself should not result in blank page. That's something else in the server setup.

**Comment by crimson-med** [comment]
@samdark Yii debug actually makes the page display but the live page without yii_debug lands as a 200 blank page. 

On that page there is a big list of models loaded in a select. Is it possible that yii_debug lets long execution time but when its not there yii2 forces the request to end?

**Comment by samdark** [comment]
No.

**Comment by crimson-med** [comment]
@samdark any idea why simply adding the line 

```
defined('YII_DEBUG') or define('YII_DEBUG', true); 
```

in the live website in `config/env.php`

there are no server reboots or changes. Just this line added fixes the blank page. 

I will publish a reproducible example later today or tomorrow.

But when I have the blank page on just one view I simply

```
nano /var/www/html/config/env.php
```

add the line

```
defined('YII_DEBUG') or define('YII_DEBUG', true); 
```
save the file and the blank page is gone.

Is there any list of functionalities or changes that YII_DEBUG does apart from changing the trace level for the logger?

**Comment by samdark** [comment]
No since I'm not aware of your configuration.
