### ISSUE TITLE
yii\validators\ExistValidator for attribute with array value.

### ISSUE THREAD

**Issue by vova07** [yiisoft/yii2#1792]
For example we need to check if the selected category `id`s for our post exist in `Category` table. In case when we can select more than one category, the model attribute with category ids will be an array, and it will [not](https://github.com/yiisoft/yii2/blob/master/framework/yii/validators/ExistValidator.php#L89) be validated.
We need to write our own validator or there is already some solution for this, but I didn't found it?
Thanx!

**Comment by klimov-paul** [comment]
Resolved by #8023
