### ISSUE TITLE
Can't use a model class when running migration.

### ISSUE THREAD

**Issue by singhhrpreet** [yiisoft/yii2#17925]
When using a class in migration. 
![image](https://user-images.githubusercontent.com/20049511/77245623-e3495a80-6c45-11ea-9e73-1682c3e6e9f1.png)

Which is located here
![image](https://user-images.githubusercontent.com/20049511/77245657-31f6f480-6c46-11ea-91f7-4999e2768c60.png)

Throws an error like this when running migration
![image](https://user-images.githubusercontent.com/20049511/77245614-d298e480-6c45-11ea-8605-48ee7d4c7c8f.png)

**Comment by samdark** [comment]
You should not ever use migrations like that. If the model would change in the future, old migrations will break.
