### ISSUE TITLE
client attribute id is same when multiple models on same form 

### ISSUE THREAD

**Issue by shushenghong** [yiisoft/yii2#17930]
### What steps will reproduce the problem?
simply reproduce, `$model1` `$model2` are different instance of the same model class
```php
<?= $form->field($model1, 'title')->textInput([ 'id' => 'model1', 'name' => 'model1' ]) ?>
<?= $form->field($model2, 'title')->textInput([ 'id' => 'model2', 'name' => 'model2' ]) ?>
```
![image](https://user-images.githubusercontent.com/3275714/77520050-8bb42480-6ebb-11ea-9f66-5347dc27fee7.png)

### What is the expected result?

unique id for each attribute

### What do you get instead?

same id

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.33
| PHP version      | 7.2
| Operating system | Linux

**Comment by shushenghong** [comment]
https://github.com/yiisoft/yii2/blob/e9f42c08545b3aa1a9982c72d5fd7680dff6f95e/framework/widgets/ActiveField.php#L849-L851

The reason is Line 850 use auto generated id. 

i found pull request  [11171](https://github.com/yiisoft/yii2/pull/11171) said for ajax validation, i don't think this is a good solution.

in some complicated case, we need set input id manually, the programmer need make sure the html element id unique, and the server end ajax validation also need do some change to make sure the response error message can locate the right element id.

In this case, don't use `ActiveForm::validate` `ActiveForm::validateMultiple`

https://github.com/yiisoft/yii2/blob/e9f42c08545b3aa1a9982c72d5fd7680dff6f95e/framework/widgets/ActiveForm.php#L407-L462

**Comment by samdark** [comment]
What is the use case for having the same field twice?

**Comment by shushenghong** [comment]
> What is the use case for having the same field twice?

the example code is just for reproduce the problem simply.

some complicated case like 1 : n models on same form, dynamically insert or remove  node, maybe by pjax, the input id need set manually by programmer.

**Comment by samdark** [comment]
Then the script should increment ID. Having more than a single element with the same ID is even not valid HTML.

**Comment by shushenghong** [comment]
> Then the script should increment ID. Having more than a single element with the same ID is even not valid HTML.

yes, framework `Html::getInputId` can't handle these complicated cases, programmer need make sure the html element id unique, set options id manually.

**Comment by samdark** [comment]
Sorry but I don't see it as a valid use case. It is generating invalid HTML and is generally not a good idea, in my opinion.
