### ISSUE TITLE
Broken redirects in 2.0.33

### ISSUE THREAD

**Issue by utmstat** [yiisoft/yii2#17932]
```
    public function actionCreate()
    {
        $this->layout = 'main-crud';
        $model = new CrmStatusList();
        $model->user_id = Projects::getOwnerUser()->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/crm-status-list']);
        }

        return $this->render('create', ['model' => $model]);
    }
```
При редиректе на /crm-status-list все останавливалось на белом экране по адресу /crm-status-list/create 

Откатился на 2.0.32 - все работает.

PHP 7.1.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan 11 2019 14:13:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.26-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

/etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by samdark** [comment]
1. What's in the logs?
2. Is it possible to reproduce it with basic app?

**Comment by utmstat** [comment]
1. Не могу посмотреть
2. Нет, но посмотрите что в редиректе меняли

Упало на боевом проекте где все до этого работало.

**Comment by samdark** [comment]
2. Ничего.

**Comment by utmstat** [comment]
Локально удалил файлы vendor/yiisoft
Обновил через композер до 2.0.33
Все работает.

Пока не могу воспроизвести. Но еще 2 клиента сказали о проблеме после обновления.

Если воспроизведу - дам знать.

**Comment by denfm** [comment]
Подтверждаю.
При обновлении на одном проекте аналогично сломались редиректы после сохранения различных форм и даже авторизации.

Причина в этом обновлении https://github.com/yiisoft/yii2/commit/7f88acb31377c08c2fea3b256dc91c56e3923ef4#diff-d403e4d3f440a629537a2d2aab4fa0a0L490

Чтобы повторить, достаточно добавить проверку `\Yii::$app->request->getIsAjax()`
Данный метод теперь всегда возвращает `TRUE`. Отрабатывает условие` ($origin !== null && $origin !== $this->getHostInfo())`
Далее по коду отслеживается, что проблема тут
```
 $secure = $this->getIsSecureConnection(); // возвращает всегда FALSE
 $http = $secure ? 'https' : 'http';
```

P.s. домен работает на HTTPS и серт действительный. На пред версиях проблемы с этим не было

**Comment by samdark** [comment]
Fixed.
