### ISSUE TITLE
Fatal error: Cannot use 'Object' as class name as it is reserved in /home/rotymoto/public_html/sistema/lib/Cake/Core/Object.php on line 30

### ISSUE THREAD

**Issue by rotymotos2020** [yiisoft/yii2#17951]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by kamarton** [comment]
https://cakephp.org/

**Comment by rotymotos2020** [comment]
Fatal error: Cannot use 'Object' as class name as it is reserved in /home/rotymoto/public_html/sistema/lib/Cake/Core/Object.php on line 30

**Comment by rotymotos2020** [comment]
Fatal error: Cannot use 'Object' as class name as it is reserved in /home/rotymoto/public_html/sistema/lib/Cake/Core/Object.php on line

**Comment by rotymotos2020** [comment]
como posso recupera minha senha
