### ISSUE TITLE
Yii doesn't add "has-error" class when template option is used in ActiveForm

### ISSUE THREAD

**Issue by smohadjer** [yiisoft/yii2#17956]
I need to display my form fields in a table, so I use ActiveForm's template option like this:     

```php
$form->field($user, 'user_email', [     	
    'template' => '<tr><td>{label}</td><td><div class="group-form">{input}{hint}{error}</div></td></tr>',     	
    'inputOptions' => []    
 ])->label('Email:');  
```
But then if there is an error, the class "has-error" is not set on `<div class="group-form">` by Yii. Is this a bug in Yii's ActiveForm or am I doing something wrong?

**Comment by Shifrin** [comment]
I guess you're doing it in the wrong way. The `template` key is for to align the items inside the container and the `has-error` class will be added to the container tag which is by default `div` tag & default class `form-group`. 

```
/**
* @var string the template that is used to arrange the label, the input field, the error message and the hint text.
* The following tokens will be replaced when [[render()]] is called: `{label}`, `{input}`, `{error}` and `{hint}`.
*/
public $template = "{label}\n{input}\n{hint}\n{error}";
```
You can try the following or you may try in a different way according to your HTML markup.
```
<?= $form->field($user, 'user_email', [
    'options' => [
        'tag' => 'tr'
    ],
    'template' => '<td>{label}</td><td><div class="group-form">{input}{hint}{error}</div></td>',
]) ?>
```
