### ISSUE TITLE
Using behaviors crashing the PHP with parallel module

### ISSUE THREAD

**Issue by Synida** [yiisoft/yii2#17953]
### What steps will reproduce the problem?
1. You need to compile php 7.4 with ZTS enabled(--enable-maintainer-zts on linux or --enable-zts on windows) - also required modules for Yii.
2. Compile and install the parallel module
3. Install Yii2
4. Create a random model and set a behavior - the behavior can be an empty DummyBehavior which extends the Behavior class, but you can use the TimestampBehavior class too.
5. Create and run a thread:
```
        $closure = static function () {
            // you can load the configuration in the constructor of a class - otherwise it will crash the php too
            new Autoloader();

            return ModelClass::findAll([]);
        };

        $runtime = new Runtime(<bootstrap file here>);
        $runtime->run($closure);
```

### What is the expected result?
Not getting segmentation fault error

### What do you get instead?
php is crashing with segmentation fault

### Additional info
Check out this thread for more information:
https://github.com/krakjoe/parallel/issues/132

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.4.4&7.4.3 with ZTS and parallel
| Operating system |centos 7.7 and windows 7

**Comment by samdark** [comment]
Any idea on how we can fix it from our side?

**Comment by Synida** [comment]
Tbh, I think it'll be an issue in the parallel, but I don't know how to prove it yet, so I thought that it would be better to report it here too, because it's related. If I'll have more time on it, I'll test it a bit more.

**Comment by SamMousa** [comment]
A segmentation fault is almost never the fault of user land code. User land code should be able to create segmentation faults.
Imo this is not a Yii issue.
