### ISSUE TITLE
UrlValidator returns false for http://localhost

### ISSUE THREAD

**Issue by germanow** [yiisoft/yii2#17964]
### What steps will reproduce the problem?

```php
use yii\validators\UrlValidator;

// returns false
(new UrlValidator)->validate('http://localhost');
```

### What is the expected result?

true

### What do you get instead?

false

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.4
| Operating system | Linux Mint 19.3

**Comment by samdark** [comment]
See https://github.com/yiisoft/validator/issues/4
