### ISSUE TITLE
yii\data\Pagination pageSizeLimit & per-page=0

### ISSUE THREAD

**Issue by tsvetiligo** [yiisoft/yii2#17961]
Я обнаружил такое поведение: если передать в значение pageSizeLimit массив с более чем двумя элементами, то pageSizeLimit не срабатывает вообще и есть возможность получить все записи ActiveDataProvider при указании per-page=0.
Не знаю много ли людей способно повторить это поведение, но именно так было в шаблоне который я использовал - chrisleekr/yii2-angular-boilerplate

**Comment by samdark** [comment]
Что именно вы предлагаете сделать?

**Comment by tsvetiligo** [comment]
При выставлении pageSizeLimit = false, pageSize становится равен defaultPageSize. А в случае некорректного значения pageSizeLimit типа [1,2,3], pageSize становится 0 и выводятся все записи. Я думаю что некорректное значение pageSizeLimit должно приравниваться к значению false.

**Comment by samdark** [comment]
А точно сейчас не так? https://github.com/yiisoft/yii2/blob/master/framework/data/Pagination.php#L238

**Comment by tsvetiligo** [comment]
_&& count($this->pageSizeLimit) === 2_ - лишнее

**Comment by samdark** [comment]
Сделаете pull request?

**Comment by tsvetiligo** [comment]
done
