### ISSUE TITLE
Make Yii Migrate Commands clear

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii2#17979]
Today I faced a disaster. I wanted to truncate every table in the database and start afresh so I checked if there exists such command

```

- migrate/create        Creates a new migration.
- migrate/down          Downgrades the application by reverting old migrations.
- migrate/fresh         Truncates the whole database and starts the migration from the beginning.
- migrate/history       Displays the migration history.
- migrate/mark          Modifies the migration history to the specified version.
- migrate/new           Displays the un-applied new migrations.
- migrate/redo          Redoes the last few migrations.
- migrate/to            Upgrades or downgrades till the specified version.
- migrate/up (default)  Upgrades the application by applying new migrations.

To see the detailed information about individual sub-commands, enter:

  yii help <sub-command>
```

And voila, there is `fresh`

So I ran fresh and warning was

```
$ ./yii migrate/fresh
Yii Migration Tool (based on Yii v2.0.34)

Are you sure you want to reset the database and start the migration from the beginning?
All data will be lost irreversibly! (yes|no) [no]:y
Foreign key xxxxx dropped.
Foreign key xxxx dropped.
....
```

That still sounded reseting the database which is what I wanted. Upon accepting, it dropped every single table.

Well the command `fresh` is misleading. But that could be tolerable if command explanation said exactly what is is doing, namely dropping/deleting all tables and related constraints/entities

Moreover warning in the command should clearly say that it is deleting everything (tables, constraints, everything). Data always implies rows in context of migrations. So it is very misleading.

Please make dangerous commands as explicit as possible.

**Comment by samdark** [comment]
That's very good observation. Hope it didn't delete anything irreversible. If you have extra time to fix it, that would be great. If not, I'll do it a bit later.

**Comment by samdark** [comment]
Done. Thank you for reporting it.
