### ISSUE TITLE
Prettified URL with 'enablePrettyUrl'=>false should result in error!!!

### ISSUE THREAD

**Issue by djidji01** [yiisoft/yii2#17972]
### What steps will reproduce the problem?
request to www.myapp.edu/courses/biology url resolve in a response despite that `'enablePrettyUrl'=>false`!!!

### What is the expected result?

Should get an error!

### What do you get instead?

result of site/index route

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35-dev?
| PHP version      | 7.4
| Operating system | windows 10

**Comment by Thoulah** [comment]
Confirmed, shows the default website instead of 404.

**Comment by rob006** [comment]
You should probably remove rewrite rules from `.htaccess`.

**Comment by djidji01** [comment]
My proposal would be to add a check on pathInfo at this level:

https://github.com/yiisoft/yii2/blob/a66fac3bb1700c612f1f0b80413051c82b506398/framework/web/UrlManager.php#L363
```
        try {
            if ($request->getPathInfo()!=='') {
                return false;
            }
        } catch (\Throwable $th) {
            return false;
        }catch (\Exception $e)
        {
            return false;
        }
```

**Comment by samdark** [comment]
I've read the conversation in https://github.com/yiisoft/yii2/pull/17983 and it seems that despite your proposal to be logically fine, there are cases when it may break existing applications so I prefer not to solve it in 2.0 releases.

Thanks for discussion and a pull request though and sorry these were not merged.
