### ISSUE TITLE
Your Exception class must extend from \Exception ; instead of extend from Exception

### ISSUE THREAD

**Issue by klunker** [yiisoft/yii2#17973]
The problem with `new yii\web\HttpException`.
In PHPShtorm showing error:
> Thrown object must be an instance of 'Exception' or 'Throwable'

### The problem place
OK, go step by step for extends classes and see the problem in `\vendor\yiisoft\yii2\base\UserException.php`
```
class UserException extends Exception
{
}
```

### What steps will fix the problem?
Change `Exception` on `\Exception`
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      |  7.4
| Operating system | Any

**Comment by rob006** [comment]
`yii\base\Exception` already extends `Exception`: https://github.com/yiisoft/yii2/blob/master/framework/base/Exception.php#L18

**Comment by klunker** [comment]
Hmmm..  Something went wrong with project synchronization. And this file was not on the development server.

I started the synchronization again, the file `https://github.com/yiisoft/yii2/blob/master/framework/base/Exception.php#L18` downloaded again and the error went away. Thanks you!
