### ISSUE TITLE
typo in yii2/i18n/migrations/schema-mysql.sql

### ISSUE THREAD

**Issue by auerswald** [yiisoft/yii2#17975]
unused translation-sources cannot be deleted via the console, if the message tables are created manually with the file `yii2/i18n/migrations/schema-mysql.sql`.

see https://www.yiiframework.com/doc/api/2.0/yii-i18n-dbmessagesource

> If you don't want to use migration and need SQL instead, files for all databases are in migrations directory.

### What steps will reproduce the problem?
`./yii message message.php -r`

### What is the expected result?
no errors 🙃

### What do you get instead?

_"Cannot delete or update a parent row: a foreign key constraint fails (\`message\`, CONSTRAINT \`fk_message_source_message\` FOREIGN KEY (\`id\`) REFERENCES \`source_message\` (\`id\`) ON UPDATE CASCADE)"_

#### wrong: ####
ALTER TABLE \`message\` ADD CONSTRAINT \`fk_message_source_message\` FOREIGN KEY (\`id\`) REFERENCES \`source_message\` (\`id\`) **ON UPDATE CASCADE ON DELETE RESTRICT**;

#### fix: ####
ALTER TABLE \`message\` ADD CONSTRAINT \`fk_message_source_message\` FOREIGN KEY (\`id\`) REFERENCES \`source_message\` (\`id\`) **ON UPDATE RESTRICT ON DELETE CASCADE**;

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      | 7.4
| Operating system | *nix

**Comment by samdark** [comment]
@auerswald do you have some time for a pull request?
