### ISSUE TITLE
migrationNamespaces must produce invalid config error for non-array migrationNamespaces

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#17985]
### What steps will reproduce the problem?
I try to use `migrationNamespaces` as string (like console command `yii migrate/up --interactive=0 --migrationNamespaces='yii\queue\db\migrations`)
```
$migrateController = new \yii\console\controllers\MigrateController('migrate', Yii::$app);
$migrateController->migrationNamespaces = 'yii\queue\db\migrations';
$migrateController->runAction('up', ['interactive' => 0]);
```

### What is the expected result?
throw error with correct message

### What do you get instead?
```
  [yii\base\ErrorException] Invalid argument supplied for foreach()  
                                                                     
#1  /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php:122
#2  /app/vendor/yiisoft/yii2/console/controllers/MigrateController.php:182
#3  /app/vendor/yiisoft/yii2/base/Controller.php:155
#4  /app/vendor/yiisoft/yii2/console/Controller.php:164
#5  /app/tests/fixtures/initdb.php:20
#6  /app/vendor/yiisoft/yii2/test/InitDbFixture.php:69
#7  /app/vendor/yiisoft/yii2/test/FixtureTrait.php:96
#8  /app/vendor/symfony/event-dispatcher/EventDispatcher.php:264
#9  /app/vendor/symfony/event-dispatcher/EventDispatcher.php:239
#10 /app/vendor/symfony/event-dispatcher/EventDispatcher.php:73
```

So... I thinkwe need some tests before 
https://github.com/yiisoft/yii2/blob/a96823d3abca7912ee761487b031a3b8030a4867/framework/console/controllers/BaseMigrateController.php#L122

```
            if (!is_array($this->migrationNamespaces)) {
                throw new InvalidConfigException('`migrationNamespaces` should be array.');
            }
```
or convert to array
```
            foreach ((array) $this->migrationNamespaces as $key => $value) {
                $this->migrationNamespaces[$key] = trim($value, '\\');
            }

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.? Yii Migration Tool (based on Yii v2.0.34)
| PHP version      | 7.3
| Operating system |

**Comment by bizley** [comment]
The code explicitly states this property must be an array.

But I agree that converting to array in foreach could be added especially when properties are not strongly typed.
