### ISSUE TITLE
UniqueValidator for 3 columns does not work.

### ISSUE THREAD

**Issue by kkursor** [yiisoft/yii2#17988]
### What steps will reproduce the problem?
I have ActiveRecord model with 3 fields who need to be unique together.
I write validation rule:
`            [
                [
                    'inn'
                ], 'unique', 'message' => 'Сочетание ИНН, КПП и ОГРН должно быть уникальным.', 'targetAttribute' => ['inn', 'kpp', 'ogrn']
            ],`

I tried 
`
            [
                [
                    'inn',
                    'kpp',
                    'ogrn'
                ], 'unique'
            ],` 
also.

### What is the expected result?
If combination of these 3 fields already exists in a database, validation should fail.

### What do you get instead?
Validation succeeds without errors and $model->save() fails with PostgreSQL unique constraint violation error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.2.24-0ubuntu0.18.04.4
| Operating system | Ubuntu 18.04

**Comment by samdark** [comment]
Would you please post SQL for creating a table and exact error you are receiving?

**Comment by kkursor** [comment]
CREATE TABLE organizations_schema.organizations
(
  id serial NOT NULL, -- Системный идентификатор
  ogrn text, -- Общегосударственный регистрационный номер организации
  okpo text, -- ОКПО
  short_name text NOT NULL, -- Краткое наименование организации
  full_name text, -- Полное наименование организации
  inn text, -- ИНН
  kpp text, -- КПП
  okato text, -- ОКАТО
  region text, -- Код региона
  parent_organization integer, -- Идентификатор родительской организации в интегрированной структуре
  industry_branch smallint, -- Отрасль промышленности
  okopf text, -- Код ОКОПФ
  okfs text,
  okogvu text, -- Код ОКОГВУ
  main_okved text, -- Основной код ОКВЭД
  yur_address text, -- Юридический адрес организации
  phones text, -- Телефоны
  faxes text, -- Факсы
  oksm text NOT NULL DEFAULT 643, -- Код страны-производителя
  www text, -- Сайт
  emails text, -- E-mail адреса
  is_developer boolean DEFAULT false, -- Признак того, что организация - разработчик
  is_producer boolean DEFAULT false, -- Признак организации-производителя
  is_archive boolean NOT NULL DEFAULT false, -- Признак архивности
  is_opk boolean NOT NULL DEFAULT false, -- Признак принадлежности организации сводному перечню организаций ОПК
  CONSTRAINT organizations_pk PRIMARY KEY (id),
  CONSTRAINT inn_kpp_ogrn_uniq UNIQUE (inn, kpp, ogrn),
)

Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "inn_kpp_ogrn_uniq"
DETAIL: Key (inn, kpp, ogrn)=(, , ) already exists.
The SQL being executed was: INSERT INTO "organizations_schema"."organizations" ("short_name", "full_name", "inn", "kpp", "ogrn", "okpo", "okato", "parent_organization", "industry_branch", "region", "okopf", "okfs", "main_okved", "oksm", "okogvu", "yur_address", "phones", "faxes", "www", "emails", "is_developer", "is_producer", "is_opk", "is_archive") VALUES ('', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '643', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE) RETURNING "id"

Exact rules for AR model are:
`    public function rules()
    {
        return [
            [
                [
                //    'ogrn',
                //    'okpo',
                //    'short_name',
                //    'full_name',
                //    'inn',
                //    'kpp',
                //    'okato',
                //    'region',
                ],
                    'required',
                    'message'=>'{attribute} является обязательным параметром',
            ],
            [
                [
                    'ogrn',
                    'short_name',
                    'full_name',
                    'okpo',
                    'inn',
                    'kpp',
                    'okato',
                    'region',
                    'okopf',
                    'okfs',
                    'main_okved',
                    'yur_address',
                    'phones',
                    'faxes',
                    'oksm',
                    'www',
                    'emails',
                    'okogvu',
                ], 'string',
            ],
            [
                [
                    'parent_organization',
                    'industry_branch',
                    'okopf',
                    'okfs',
                    'main_okved',
                    'yur_address',
                    'phones',
                    'faxes',
                    'www',
                    'emails',
                    'region',
                    'okato',
                    'okogvu',
                ], 'default', 'value' => null
            ],
            [
                'oksm', 'default', 'value' => 643,
            ],
            [
                ['industry_branch'],
                'integer',
            ],
            [
                ['parent_organization'],
                'safe',
            ],
            [
                [
                    'is_developer',
                    'is_producer',
                    'is_archive',
                    'is_opk',
                ], 'boolean',
            ],
            [
                [
                    'inn',
                    'kpp',
                ], 'unique', 'targetAttribute' => [
                    'inn',
                    'kpp',
                ]
            ],
            [
                ['ogrn'],
                'unique',
            ],
            [
                ['industry_branch'], 'exist', 'skipOnError' => true, 'targetClass' => NsiIndustryBranches::class, 'targetAttribute' => ['industry_branch' => 'code']
            ],
            [
                ['okato'], 'exist', 'skipOnError' => true, 'targetClass' => NsiOkato::class, 'targetAttribute' => ['okato' => 'code']
            ],
            [
                ['okfs'], 'exist', 'skipOnError' => true, 'targetClass' => NsiOkfs::class, 'targetAttribute' => ['okfs' => 'code']
            ],
            [
                ['okopf'], 'exist', 'skipOnError' => true, 'targetClass' => NsiOkopf::class, 'targetAttribute' => ['okopf' => 'code']
            ],
            [
                ['okogvu'], 'exist', 'skipOnError' => true, 'targetClass' => NsiOkogvu::class, 'targetAttribute' => ['okogvu' => 'code']
            ],
            [
                ['oksm'], 'exist', 'skipOnError' => true, 'targetClass' => NsiOksm::class, 'targetAttribute' => ['oksm' => 'code']
            ],
            [
                ['main_okved'], 'exist', 'skipOnError' => true, 'targetClass' => NsiOkved::class, 'targetAttribute' => ['main_okved' => 'code']
            ],
            [
                ['region'], 'exist', 'skipOnError' => true, 'targetClass' => NsiRegions::class, 'targetAttribute' => ['region' => 'code']
            ],
            [
                ['parent_organization'], 'exist', 'skipOnError' => true, 'targetClass' => Organizations::class, 'targetAttribute' => ['parent_organization' => 'id']
            ],
        ];

    }//end rules()
`

**Comment by samdark** [comment]
Does it error for non-empty values?

**Comment by kkursor** [comment]
hmmm... no, it returns correct error message for all 3 fields...

**Comment by samdark** [comment]
Are all three fields required? If so, how about adding `required` validator to each?

**Comment by kkursor** [comment]
We'll do a custom validator for this (they are required if country_code == 643, not required otherwise), but it's probably a bug

**Comment by XPOHOC269** [comment]
@kkursor try 
`[ [ 'inn', 'kpp', 'ogrn' ], 'unique', 'targetAttribute' => ['inn', 'kpp', 'ogrn'] ],`

**Comment by kkursor** [comment]
> @kkursor try
> `[ [ 'inn', 'kpp', 'ogrn' ], 'unique', 'targetAttribute' => ['inn', 'kpp', 'ogrn'] ],`
Tried. It does not work if the strings are empty, but not null

**Comment by XPOHOC269** [comment]
@kkursor maybe add 'skipOnEmpty'=>false ?

**Comment by samdark** [comment]
Yeah. That.
