### ISSUE TITLE
Make \yii\rest\Serializer::addPaginationHeaders() public.

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii2#17986]
I don't want to use Serializer (I am optimizing RESTful end-point by avoiding PHP loop through models) but I need to apply filters to data provider and then set pagination headers. So in RESTful controller I use a hook for prepareDataProvider and then call 

```
$pagination = $dataProvider->getPagination();
```
after that I'd like to call

```
(new \yii\rest\Serializer())->addPaginationHeaders($pagination);
```
but `addPaginationHeaders()` is not public. Probably it should also get Response as a parameter.

Maybe it makes sense to make it static and turn properties like $totalCountHeader into const.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.21?
| PHP version      |  7.1.33
| Operating system | Amazon Linux AMI 2018.03

**Comment by samdark** [comment]
It doesn't seem that using Serializer like that would save much code for you so I'd suggest to copy this piece into your own custom implementation. This is internal detail that is not meant to be exposed.

**Comment by vitalyspirin** [comment]
@samdark  It's unfortunate that WET is recommended here. It wouldn't be much work to make that function public and those pagination headers are custom Yii headers so it would be reasonable to set them up through Yii function.
