### ISSUE TITLE
IpValidator missing base namespace

### ISSUE THREAD

**Issue by hypergeneric** [yiisoft/yii2#17981]
in `framework/validators/IpValidator.php`

lines:
#219
#222
#225
#228
#231
#234
#237

all use YII's translation shortcut `Yii::t();` method -- but that uses the base class of YII and the namespace is not declared.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34 (or lower)
| PHP version      | 7+
| Operating system |

**Comment by hypergeneric** [comment]
i have tried pushing changes to a brand, but am getting permission errors.

**Comment by samdark** [comment]
Would you please elaborate about namespace? I'm not sure what was meant...

**Comment by hypergeneric** [comment]
sure -- i have a craft install, and it's probably trying to generate message warnings.  i have a local branch with all the updates necessary, but i don't seem to have permissions to push my branch and request a PR.  here is the stack trace:

`
Fatal error: Uncaught Error: Class 'Yii' not found in /..../vendor/yiisoft/yii2/validators/IpValidator.php:218
Stack trace:
#0 /..../vendor/yiisoft/yii2/base/BaseObject.php(109): yii\validators\IpValidator->init()
#1 /..../endor/yiisoft/yii2/web/Request.php(345): yii\base\BaseObject->__construct()
#2 /..../vendor/yiisoft/yii2/web/Request.php(1877): yii\web\Request->getIpValidator()
#3 /..../vendor/yiisoft/yii2/web/Request.php(1859): yii\web\Request->getSecureForwardedHeaderTrustedParts()
#4 /..../vendor/yiisoft/yii2/web/Request.php(1084): yii\web\Request->getSecureForwardedHeaderTrustedPart('proto')
#5 /..../vendor/yiisoft/yii2/web/Request.php(737): yii\web\Request->getIsSecure in /..../vendor/yiisoft/yii2/validators/IpValidator.php on line 218
`
there are 17 files in framework/validators that are affected.

**Comment by hypergeneric** [comment]
![Screenshot at Apr 19 15-22-00](https://user-images.githubusercontent.com/25310476/79701391-93b07b80-8251-11ea-8ce5-291524287f7d.png)

**Comment by samdark** [comment]
That's super-weird. We have `Yii` class imported: https://github.com/yiisoft/yii2/blob/master/framework/validators/IpValidator.php#L10

Also I don't understand your screenshot. You can't have two namespaces for a class in PHP.

**Comment by samdark** [comment]
Also IP validator is covered with a test: https://github.com/yiisoft/yii2/blob/master/tests/framework/validators/IpValidatorTest.php and that test pass.

**Comment by samdark** [comment]
Maybe it will be clean for me if I'll see the diff with you branch. There's how to do it: https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by hypergeneric** [comment]
good point about the NS -- looking ...

**Comment by hypergeneric** [comment]
when i try pushing my branch, i get this:
remote: Permission to yiisoft/yii2.git denied to hypergeneric.
fatal: unable to access 'https://github.com/yiisoft/yii2.git/': The requested URL returned error: 403

**Comment by samdark** [comment]
Please re-check the git-workflow.md document. You should push to your own fork, not to yiisoft/yii2.

**Comment by hypergeneric** [comment]
whoops -- duh.  ok so i made the changes to branch -- you can see it here:
https://github.com/hypergeneric/yii2/blob/17981-validator-base-class/framework/validators/IpValidator.php

truth be told i am not 100% what's going on.  this whole thing was part of a craft CMS update -- i was trying to reverse engineer the errors ↑ 

i see that `Yii` isn't namespaced to `\yii\` -- that said, changing `use Yii;` to `use yii\Yii;` definitely fixed craft's update process and i no longer get the error.

**Comment by samdark** [comment]
Not sure what happened with Craft update but it seems that it is craft specific.

@hypergeneric which version is that?

@brandonkelly I think you'll be interested to take a look.

**Comment by hypergeneric** [comment]
true -- it definitely could be the way craft is instantiating it.  i haven't rattled the chain that far up the code.  that said, these manual edits locally seem to have sidestepped the errors, even if just superficially.  thanks for looking into it.
