### ISSUE TITLE
Formatter: decimalSeparator does not work when currency+intl are used

### ISSUE THREAD

**Issue by XPOHOC269** [yiisoft/yii2#17993]
config:
```
        'formatter' => [
            'defaultTimeZone'        => 'Europe/Moscow',
            'locale'                 => 'ru_RU',
            'currencyCode'           => 'RUB',
            'numberFormatterSymbols' => [
                \NumberFormatter::CURRENCY_SYMBOL           => 'руб.',
            ],
            'decimalSeparator'       => '.',
            'thousandSeparator'      => ' ',
        ],
```
GridView DataColumn:
```
[
            'class'              => 'kartik\grid\DataColumn',
            'attribute'          => 'orderPlacesSum',
            'label'              => 'Сумма',
            'contentOptions'     => ['class' => 'text-center'],
            'pageSummaryOptions' => ['class' => 'text-center'],
            'format'             => 'currency',
            'pageSummary'        => true,
        ],
```
result:
![image](https://user-images.githubusercontent.com/10045926/80133861-90e1bd80-85a6-11ea-944a-d5fae9d9cf37.png)
A dot will use only if I specify NumberFormatter :: MONETARY_SEPARATOR_SYMBOL in numberFormatterSymbols
```
       'formatter' => [
            'defaultTimeZone'        => 'Europe/Moscow',
            'locale'                 => 'ru_RU',
            'currencyCode'           => 'RUB',
            'numberFormatterSymbols' => [
                \NumberFormatter::CURRENCY_SYMBOL           => 'руб.',
                \NumberFormatter::MONETARY_SEPARATOR_SYMBOL => '.',
            ],
            'decimalSeparator'       => '.',
            'thousandSeparator'      => ' ',
        ],
```
![image](https://user-images.githubusercontent.com/10045926/80134266-3006b500-85a7-11ea-91f1-93e04471864a.png)

Can You add this string in Formatter.php? this will help the problem
![image](https://user-images.githubusercontent.com/10045926/80134464-752ae700-85a7-11ea-9da7-50c8f097845c.png)

**Comment by samdark** [comment]
Is there a use case for configuring it separately from decimal separator?

**Comment by XPOHOC269** [comment]
I did not quite understand the question. My english is probably bad

**Comment by samdark** [comment]
You're setting both `GROUPING_SEPARATOR_SYMBOL` and `MONETARY_SEPARATOR_SYMBOL` to the same value. Can there be a situation when these two need to have different value?

**Comment by XPOHOC269** [comment]
1)`GROUPING_SEPARATOR_SYMBOL` used with thousandSeparator, in my case it is ' ' 
2)`MONETARY_SEPARATOR_SYMBOL` used with decimalSeparator, in my case it is '.' 
Maybe your mean `DECIMAL_SEPARATOR_SYMBOL` and `MONETARY_SEPARATOR_SYMBOL`? 
If I set `DECIMAL_SEPARATOR_SYMBOL=MONETARY_SEPARATOR_SYMBOL = '.'`
Result
```
        echo(Yii::$app->formatter->asDecimal(123.45));//123.45
        echo(Yii::$app->formatter->asCurrency(123.45));//123.45 руб.
```
Without `MONETARY_SEPARATOR_SYMBOL` result will be 
```
        echo(Yii::$app->formatter->asDecimal(123.45));//123.45
        echo(Yii::$app->formatter->asCurrency(123.45));//123,45 руб.
```

**Comment by samdark** [comment]
Yeah. I've meant that. I suspect setting these separately may be required for non-Russian language.

**Comment by samdark** [comment]
Therefore, introducing separate monetary separator sounds like a good way to handle it.

**Comment by XPOHOC269** [comment]
thanks a lot

**Comment by samdark** [comment]
@XPOHOC269 how about preparing a pull request to speed things up?

**Comment by XPOHOC269** [comment]
Ok? I will do it
