### ISSUE TITLE
Missing case in yiiunit\framework\base\SecurityTest::testGenerateRandomKey

### ISSUE THREAD

**Issue by DeryabinSergey** [yiisoft/yii2#17999]
### What steps will reproduce the problem?

On PHP version 7.1 and hi missing test case with data set 4 (array(false, true, true)) skipping, but need to check

### What is the expected result?

In `yii\base\Security` 

```
        if ($this->_useLibreSSL === null) {
            $this->_useLibreSSL = defined('OPENSSL_VERSION_TEXT')
                && preg_match('{^LibreSSL (\d\d?)\.(\d\d?)\.(\d\d?)$}', OPENSSL_VERSION_TEXT, $matches)
                && (10000 * $matches[1]) + (100 * $matches[2]) + $matches[3] >= 20105;
        }
```

make checking LibreSSL in public static method.

In tests `yiiunit\framework\base\SecurityTest::testGenerateRandomKey with data set 4 (array(false, true, true))` make a new case to checking LibreSSL and make test if ok and skip when using old library

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      | 7.4.5
| MySQL version      | 8.0.19
| Operating system | debian 10

**Comment by samdark** [comment]
Alright. Since you're into it, how about a pull request?

**Comment by DeryabinSergey** [comment]
Almost one in In `yii\base\Security` checking windows by

```
        if (function_exists('openssl_random_pseudo_bytes')
            && ($this->_useLibreSSL
            || (
                DIRECTORY_SEPARATOR !== '/'
                && substr_compare(PHP_OS, 'win', 0, 3, true) === 0
            ))
        ) {
```
and

```
        // If not on Windows, try to open a random device.
        if ($this->_randomFile === null && DIRECTORY_SEPARATOR === '/') {
```

Maybe do static method?

```
    public static function isWindows()
    {
        return 
            DIRECTORY_SEPARATOR !== '/'
            && substr_compare(PHP_OS, 'win', 0, 3, true) === 0;
    }
```

**Comment by DeryabinSergey** [comment]
@samdark tell me, for what need class [ExposedSecurity.php](https://github.com/yiisoft/yii2/blob/master/tests/framework/base/ExposedSecurity.php) used only in [SecurityTest](https://github.com/yiisoft/yii2/blob/master/tests/framework/base/SecurityTest.php#L87)

**Comment by samdark** [comment]
@DeryabinSergey it is for test only.
