### ISSUE TITLE
Postgres schema JSONB type mistake 

### ISSUE THREAD

**Issue by lutek** [yiisoft/yii2#18002]
https://github.com/yiisoft/yii2/blob/a96823d3abca7912ee761487b031a3b8030a4867/framework/db/pgsql/Schema.php#L124

on line above should be self::TYPE_JSONB not self::TYPE_JSON.

https://github.com/yiisoft/yii2/blob/a96823d3abca7912ee761487b031a3b8030a4867/framework/db/pgsql/Schema.php#L34

**Comment by samdark** [comment]
@SilverFire do you remember why it is like it is now?

**Comment by SilverFire** [comment]
It seems to be a typo. Can't find a better reason why :)

**Comment by samdark** [comment]
Seems it's not a typo...

**Comment by SilverFire** [comment]
1 hour later...

Both JSON and JSONB are actually JSON documents and are represented in PHP with the same object. The difference is only in indexing on the DBMS side, thus they can be handled the same way.

**Comment by SilverFire** [comment]
I'm closing this issue since current mapping is expected.
@lutek is something does not work as expected – don't hesitate to drop a word :)
