### ISSUE TITLE
Oracle ActiveRecord primary keys get null after Save()

### ISSUE THREAD

**Issue by mankwok** [yiisoft/yii2#18000]
### What steps will reproduce the problem?
Create a model 
```php
$myModel= new ModelClass();
$myModel->KEY_COLUMN_NAME = 'foo';
$myModel->save();

// Get the key after insert
$pk = $myModel->KEY_COLUMN_NAME; //should be foo

```

### What is the expected result?
The key attribute of `$myModel` should be `foo`

### What do you get instead?
It returns `null`

### Additional info

I found that the function ` insert($table, $columns)` in `db/oci/Schema.php`:
The `returnParams` is passed by reference when `bindParam` in `foreach` loop
After executing the statement, the `value` in `$returnParams[$phName]` is still null

I tried manually create a variable and bind it to the statement, it works fine.
```php
$command->pdoStatement->bindParam(':qp6',  $myVar, $value['dataType'], $value['size']);
if (!$command->execute()) {
            return false;
        }
// $myVar is updated and is the Pk value

```
Form the db log, the oracle sql is using returning into the param
```sql
INSERT INTO "SCHEMA"."TABLE" ("KEY_COLUMN_NAME", "A_COLUMN") VALUES ('foo',  'value') RETURNING "KEY_COLUMN_NAME" INTO :qp6
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      | 7.4.3
| Operating system | Win 10

**Comment by samdark** [comment]
Looks like a solid bug. Do you have a fix ready? How about a pull request with tests and a fix?

**Comment by mankwok** [comment]
Hi @samdark,
I discover that in line `615` of  `db/oci/Schema.php`:
```php
$returnParams[$phName] = [
                    'column' => $name,
                    'value' => null,
                ];
```
When the key `'value' ` is `null` in creating the return params
The `$command->pdoStatement->bindParam()` is unable to bind the key `'value' `  

So after executing the command. the value of `'value' `  is still null.

After that I changed the default binding value to empty string. it works fine.
The PK value is able to set back in `insertInternal()` in `ActiveRecord.php` later on

```php
$returnParams[$phName] = [
                    'column' => $name,
                    'value' => '', // set default return is empty string
                ];
```

Since this is my first time using Yii and tested only in Oracle DB, I would like to know whether I need to test on other DB?

Thanks!

**Comment by mankwok** [comment]
To wrap things up, I tried the default value of the binding variable:

1. Default value is null

```php
$myVar = null;
$command->pdoStatement->bindParam($name, $myVar, $dataType, $size);
$command->execute();
// $myVar is still null
```

2. Default value is empty string
```php
$myVar = '';
$command->pdoStatement->bindParam($name, $myVar, $dataType, $size);
$command->execute();
// $myVar is changed to the value of statement return
```

**Comment by samdark** [comment]
> Since this is my first time using Yii and tested only in Oracle DB, I would like to know whether I need to test on other DB?

If the change is in db/**oci**/Schema.php then the answer is no, you don't need to test any other DB since that's Oracle-specific.
