### ISSUE TITLE
cacheHeaders attribute not work in PageCache

### ISSUE THREAD

**Issue by haohetao** [yiisoft/yii2#18004]
### What is the expected result?
It is happen cors header exception when enabled PageCache.
I set cacheHeaders=false , the header also not updated.
I not found cacheHeaders implement code in  PageCache.php.
### What do you get instead?
variations=>[Yii::$app->request->headers->get('origin')]

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      | 7.4.5
| Operating system |ubuntu 20.04

**Comment by haohetao** [comment]
There is no corresponding code implementation for cacheHeaders, I don't understand whether this option is useful, what is the use

**Comment by haohetao** [comment]
I think we should consider whether to delete this option

**Comment by samdark** [comment]
Usage was removed in https://github.com/yiisoft/yii2/pull/12145.

**Comment by samdark** [comment]
@cebe, @sergeymakinen do you remember the reason usage was removed? Were these meant to be removed?

**Comment by sergeymakinen** [comment]
In fact, it’s used dynamically in an insert…smth method (can’t say the name as I’m writing from my phone now).

**Comment by samdark** [comment]
Thanks!

I certainly won't go this magical path with Yii 3 :)
