### ISSUE TITLE
SameSite cookie pre PHP 7.3

### ISSUE THREAD

**Issue by scottix** [yiisoft/yii2#18006]
### What steps will reproduce the problem?

Setting SameSite cookie before 7.3

### What is the expected result?

Be able to set SameSite cookie

### Additional info

There is a way to set SameSite cookie pre 7.3
https://stackoverflow.com/a/46971326/1922105

This could be a good workaround because people even on 18.04 will still be on php 7.2

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      | 7.2.24
| Operating system | 18.04

**Comment by samdark** [comment]
Interesting. I'm fine having it. Do you want to do a pull request with tests and an addition?

**Comment by scottix** [comment]
Ya I can work on it.
