### ISSUE TITLE
Yii migration tool fails migrate/create

### ISSUE THREAD

**Issue by mbunyan** [yiisoft/yii2#18008]
### What steps will reproduce the problem?
using terminal (DOS cmd)> .\vendor\bin\yii migrate\create create_dog_table

### What is the expected result?
stub created with outline migration script

### What do you get instead?
Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "db".' in P:\yii2\basic\vendor\yiisoft\yii2\di\Container.php:449

### Additional info
Fails using MySQL 5.7 and SQLite
Yii2 installation uses basic app
Web pages display data from db correctly
Gii work correctly for creation of models, etc

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      |  7.4.5
| Operating system | Windows 10

[stacktrace.txt](https://github.com/yiisoft/yii2/files/4548305/stacktrace.txt)

**Comment by samdark** [comment]
Do you have correct database configuration in `console.php`?

**Comment by rob006** [comment]
Why you're using `.\vendor\bin\yii` instead of `.\yii`? `.\vendor\bin\yii` will run command in context of framework package, while you need run it in context of your application.

**Comment by mbunyan** [comment]
Thank you @rob006 .
My mistake by reading from 'testing' guidance.
I have function working correctly now.
