### ISSUE TITLE
Allow jQuery 3.5.0 to be installed

### ISSUE THREAD

**Issue by wouter90** [yiisoft/yii2#18019]
Allow jQuery 3.5.0 to be installed

**Comment by brandonkelly** [comment]
@samdark that commit didn’t modify `framework/composer.json` so it doesn’t have any effect on the Composer package.

**Comment by samdark** [comment]
Oww... missed it :(

**Comment by samdark** [comment]
88b0abd6333c8897ffe3ca7b973252f84bad79e5
