### ISSUE TITLE
Issues in Latvian message translations

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2#18018]
In [yii](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php) message files for Latvian, there are multiple little things that I found, gathering them here.

## Wording

In [line 54](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L54), is currently used translation for the word _Galvenā_ (main), but should be instead something more close to _Sākums_ (beginning), that is more often used for links to home page.

```
'Home' => 'Sākums',
```

In [line 82](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L82), currently there is translation for _Neizdevās apstiprināt_ (could not confirm), that is invalid translation for "Unable to verify". It suggests now that verification could not begin, rather than that verification finished and results are invalid. Message is used in CSRF validation context for failed validation and should be more clear as to what happened.

```
'Unable to verify your data submission.' => 'Saņemtie dati neizturēja pārbaudi.',
```

In [line 84](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L84), _pārbaude_ is a decent translation for it, but in this case, its for CAPTCHA use, and we should use _cilvēktests_ (human) instead, as it is correct and approved translations for HIP challenge; Human Interactive Proof; Completely Automated Public Turing Test to Tell Computers and Humans Apart.

```
'The verification code is incorrect.' => 'Cilvēktesta kods bija nepareizs.',
```

In [line 85](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L85), we see _izvēle_ (choice), but we should rather see _iespēja_, because a choice, is already chosen option.

```
'Unknown option: --{name}' => 'Nezināma iespēja: --{name}',
```

In [line 140](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L140), we see _tulīt_ (in a moment), but its complete opposite of the context, as it is used in time formatter for showing interval of zero length and the expected value is closer to "something will happen in 0 seconds" and _tikko_ is a correct translation, that talks about past event. Sadly, Yii uses same "just now" for both "ago" and "in (future)".

```
'just now' => 'tikko',
```

## Quotes

In multiple lines, there is a weird use of quotes. Some translations have `”` and `„` instead uf default quotes. We should have consistency.

In [line 73](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L73)

```
'The file "{file}" is not an image.' => 'Saņemtā "{file}" datne nav attēls.',
```

Same in lines [74](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L74), [75](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L75), [76](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L76), [77](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L77), [78](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L78), [79](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L79), [80](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L80), [81](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L81), [98](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L98), [99](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L99), [103](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L103), [107](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L107), [108](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L108), [109](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L109), [110](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L110), [111](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L111), [114](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L114), [115](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L115).

Some words are quoted when in source they are not.

In [line 99](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L99)

```
'{attribute} cannot be blank.' => 'Ir jāaizpilda {attribute}.',
```

Same in lines [100](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L100), [101](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L101), [102](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L102), [104](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L104), [105](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L105), [106](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L106), [112](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L112), [113](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L113), [116](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L116), [117](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L117), [118](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L118).

## Dot at the end of the sentence

In [line 56](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L56), is currently used unnecessary dot at the end.

```
'Login Required' => 'Nepieciešama autorizācija',
```

## Invalid variables

In [line 133](/yiisoft/yii2/blob/master/framework/messages/lv/yii.php#L133), capitalized variable `{Yii}` is not compatible syntax, translated string should have the same capitalization as source string.

```
'Powered by {yii}' => 'Darbojas ar {yii}',
```

**Comment by samdark** [comment]
Good set of issues. Would you please do a pull request? I don't speak Latvian so may make mistakes when applying these.
