### ISSUE TITLE
Should condition builder operator checks be case-insensitive

### ISSUE THREAD

**Issue by alex-code** [yiisoft/yii2#18010]
I believe this only affects `InConditionBuilder` and `LikeConditionBuilder`.

Using `InCondition` if the operator is lowercase the SQL built is `column<>:qp0` instead of `column=:qp0`
```php
$params = [];
echo \Yii::$app->db->queryBuilder
    ->buildCondition(
        new \yii\db\conditions\InCondition('column', 'in', [1])
    , $params);
```
Using `LikeCondition` if the operator is lowercase an exception is raised.
```php
$params = [];
echo \Yii::$app->db->queryBuilder
    ->buildCondition(
        new \yii\db\conditions\LikeCondition('column', 'like', 'foobar')
    , $params);
```

Could be fixed by either upper casing the operator in the condition class or using case-insensitive checks in the condition builder.
I can do a PR for the preferred method.

| Q                | A
| ---------------- | --
| Yii version      | 2.0.34

**Comment by samdark** [comment]
I think it's fine to accept operator in any case. That aligns well with Yii 2 approach in general.

**Comment by samdark** [comment]
Is that a problem for these two operators only?

**Comment by alex-code** [comment]
I think so, these are the case comparisons.

`InConditionBuilder`
[InConditionBuilder.php#L42](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L42)
[InConditionBuilder.php#L79](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L79)
[InConditionBuilder.php#L85](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L85)
[InConditionBuilder.php#L96](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L96)
[InConditionBuilder.php#L196](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L196)
[InConditionBuilder.php#L217](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/InConditionBuilder.php#L217)

`LikeConditionBuilder`
[LikeConditionBuilder.php#L105](https://github.com/yiisoft/yii2/blob/master/framework/db/conditions/LikeConditionBuilder.php#L105)
