### ISSUE TITLE
Each Validation Rule bug

### ISSUE THREAD

**Issue by atsokha** [yiisoft/yii2#18015]
### What steps will reproduce the problem?
1. Create array, myarr = [1,2,3,4,5]
2. Load to model myarr, and validate it by rule:

`
    public function rules()
    {
        return [
            [['myarr'], 'each', 'rule' => ['integer']],
        ];
    }
`
### What is the expected result?
No exception 
### What do you get instead?
`Exception 'TypeError' with message 'Typed property MyPath::$myarr must be array, int used'`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34.
| PHP version      | 7.4.4
| Operating system |MacOs Mojave

**Comment by rob006** [comment]
This should be fixed by #17944. Can you try master branch and check if it works in your case?

**Comment by atsokha** [comment]
Yes, its work on master, thanks.
