### ISSUE TITLE
Use of undefined constant on - assumed 'on' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by husnain-aslam** [yiisoft/yii2#18025]
I am getting this PHP warning message in PHP 7.3 at "ON" scenario in models
`['password', 'required', on => 'create'],
`

```
PHP Warning – yii\base\ErrorException
Use of undefined constant on - assumed 'on' (this will throw an Error in a future version of PHP)

```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      |  7.3
| Operating system | linux

**Comment by samdark** [comment]
`on` should be a string.

**Comment by lauraadelia** [comment]
$getcol = explode(",",exploded[0]);
