### ISSUE TITLE
@param string $id

### ISSUE THREAD

**Issue by kerneldos** [yiisoft/yii2#18030]
https://github.com/yiisoft/yii2/blob/88b0abd6333c8897ffe3ca7b973252f84bad79e5/framework/base/View.php#L544

Please change to:
@param string|mixed $id a unique ID identifying the fragment to be cached.

**Comment by samdark** [comment]
Why? It is ID of the fragment and it is a string.

**Comment by kerneldos** [comment]
> Why? It is ID of the fragment and it is a string.

Because FragmentCache widget returns mixed type of id:
https://github.com/yiisoft/yii2/blob/8e358ff14ae78284ba7042bc61264e4346d1af7d/framework/widgets/FragmentCache.php#L160

**Comment by samdark** [comment]
That is a key, not ID, isn't it?

**Comment by kerneldos** [comment]
> That is a key, not ID, isn't it?

No, this method is used as a parameter for generating an ID:
https://github.com/yiisoft/yii2/blob/8e358ff14ae78284ba7042bc61264e4346d1af7d/framework/widgets/FragmentCache.php#L116

**Comment by samdark** [comment]
Alright. Thanks for explanation.

**Comment by rob006** [comment]
> Yes it is, but this method is used as a parameter for generating an key:

`FragmentCache` extends `Widget` and `Widget::$id` needs to be string: https://www.yiiframework.com/doc/api/2.0/yii-base-widget#$id-detail

**Comment by kerneldos** [comment]
> > Yes it is, but this method is used as a parameter for generating an key:
> 
> `FragmentCache` extends `Widget` and `Widget::$id` needs to be string: https://www.yiiframework.com/doc/api/2.0/yii-base-widget#$id-detail

`FragmentCache` uses ID as key for `CacheInterface`

**Comment by rob006** [comment]
> `FragmentCache` uses ID as key for `CacheInterface`

And string will work perfectly fine as part of cache key, but array is invalid widget ID. In your case it works only due of bit of luck and lack of type definitions in Yii (`getId()` would result type error if it would have `array` as return type).

**Comment by kerneldos** [comment]
> > `FragmentCache` uses ID as key for `CacheInterface`
> 
> And string will work perfectly fine as part of cache key, but array is invalid widget ID. In your case it works only due of bit of luck and lack of type definitions in Yii (`getId()` would result type error if it would have `array` as return type).

Ok. `FragmentCache` uses ID as key for `CacheInterface`, doesn't it? Maybe is `Widget` `ID` can be of type `mixed`?

**Comment by samdark** [comment]
Decided to keep phpdoc as is.
