### ISSUE TITLE
No support to specify `IGNORE` statement with batchInsert()

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#18038]
### What steps will reproduce the problem?
I have a csv that i am inserting and i am creating batches of 1k to insert in the database and using the query builder like below i cant find any way to specify `INSERT IGNORE INTO` instead of the default `insert into` statement.

```
$sqlCS = $db->queryBuilder->batchInsert(
                '{{%subscriber}}',
                ['campaign_id', 'subscriber_id'],
                $batch
            );
```

currently what i am doing is

```
$sqlCS = substr_replace($sqlCS,'INSERT IGNORE',0,6);
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      | 7
| Operating system |windows

**Comment by darkdef** [comment]
The syntax "INSERT IGNORE" supported only MySQL (for example, in PostgreSQL, MSSQL need usage ON CONFLICT/ON DUPLICATE KEY etc...)

**Comment by samdark** [comment]
Because it is DB-specific we have no plan to support it.
