### ISSUE TITLE
Console Table Widget width issue with colorized input

### ISSUE THREAD

**Issue by erkib** [yiisoft/yii2#18047]
### What steps will reproduce the problem?
Use colorized input data in Table Widget rows.

### What is the expected result?
Width of columns should be calculated without console colorization markers.
[Correct Table](https://github.com/erkib/yii2-issues/blob/master/correct_table_widget_output.png)

### What do you get instead?
Messed up widths.
[Incorrect Table](https://github.com/erkib/yii2-issues/blob/master/incorrect_table_widget_output.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.4.5
| Operating system | OS X 10.15.4

**Comment by cheeseq** [comment]
I've made a PR for this. Can someone have a look? #18121
