### ISSUE TITLE
Unexpected result for \yii\helpers\ArrayHelper::merge()

### ISSUE THREAD

**Issue by iz65535** [yiisoft/yii2#18046]
### What steps will reproduce the problem?

      $b = [
            10 => [2]
        ];
        $c = [
            10 => [20]
        ];
        print_r(
            \yii\helpers\ArrayHelper::merge($b, $c)
        );

### What is the expected result?
    Array
    (
        [10] => Array
            (
                 [0] => 2
                [1] => 20
            )
    )
### What do you get instead?
    Array
    (
        [10] => Array
            (
                [0] => 2
            )

        [11] => Array
            (
                [0] => 20
            )
    )

### Additional info
this fix solves the issue, but i'm totally not sure it's correct:
```diff
--- a/v2/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php       
+++ b/v2/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php    
@@ -124,14 +124,14 @@
                     unset($res[$k]);
                 } elseif ($v instanceof ReplaceArrayValue) {
                     $res[$k] = $v->value;
+                } elseif (is_array($v) && isset($res[$k]) && is_array($res[$k])) {
+                    $res[$k] = static::merge($res[$k], $v);
                 } elseif (is_int($k)) {
                     if (array_key_exists($k, $res)) {
                         $res[] = $v;
                     } else {
                         $res[$k] = $v;
                     }
-                } elseif (is_array($v) && isset($res[$k]) && is_array($res[$k])) {
-                    $res[$k] = static::merge($res[$k], $v);
                 } else {
                     $res[$k] = $v;
                 }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      |  7.3.17
| Operating system | Fedora Linux 31

**Comment by samdark** [comment]
So that's an issue for numeric keys only. For string keys it works as expected...

**Comment by samdark** [comment]
The fix, indeed, works and doesn't seem to break any tests. Also, looks OK to me.

**Comment by samdark** [comment]
@yiisoft/reviewers any implications about the change that I can't see?

**Comment by xepozz** [comment]
What is the result expected and actual for the case:
```php
$a = [[1], [2], [3]];
$b = [[4], [5], [6]];
$c = ArrayHelper::merge($a, $b);
```

Arrays has a numeric keys, but the result shouldn't be `[[1, 4], [2, 5], [3, 6]]`

**Comment by schmunk42** [comment]
I'd expect the expected result in the OP only for a string `"10"` not necessarily for an 
*integer* value of `10`, which is "just" the 10th position in an array in PHP.

I am not saying one way is fully correct or the other, but I won't change that for Yii2, there might be code which is relying on this behavior.

Although this could be done with an additional method `merge...()` to maintain BC.

**Comment by rob006** [comment]
> I'd expect the expected result in the OP only for a string `"10"` not necessarily for an
> _integer_ value of `10`,

There is no difference between integer and integer-as-string in case of array keys: https://github.com/yiisoft/yii2/issues/5081#issuecomment-55915761

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/18053#issuecomment-631411651

**Comment by samdark** [comment]
Alright. @iz65535 seems changing this behavior would break things so we can't fix it. Need to add a test for current behavior.
