### ISSUE TITLE
Need add info to UPGRADE.md from 2.0.34

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii2#18050]
### What steps will reproduce the problem?

Yii2 version 2.0.35.
Model with validator:

[
  'ids',
  'each',
  'rule' => [
    'in',
    'range' => function (self $model) {
      return $model->allowIds;
    }
  ]
],

### What is the expected result?

No errors

### What do you get instead?

TypeError
Argument 1 passed to MyForm::{closure}() must be an instance of MyForm, instance of yii\base\DynamicModel given

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      |  7.2
| Operating system | Windows 10

Problem in Yii 2.0.35 after commit https://github.com/yiisoft/yii2/commit/355ca1562ddf6b25b5db3d1b62e138aa503087a9#diff-331f73fc0a09f0f46df28de5e87f7a6a

I think need add info to UPGRADE.md from 2.0.34 about EachValidator: in anonymous function first argument instead current model use DynamicModel.

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/yii2/issues/18051
