### ISSUE TITLE
Missing $this->owner in yii\base\ActionFilter.php

### ISSUE THREAD

**Issue by tsmotta** [yiisoft/yii2#18057]
I was working with a [rest api implementation](https://github.com/tsmotta/yii2-oauth2-rest-template) and had to change line 81 in yii\base\ActionFilter.php to add a test of $this->owner. Maybe I did something wrong but maybe it's something to be added.

### What steps will reproduce the problem?

Grab the [api implementation](https://github.com/tsmotta/yii2-oauth2-rest-template), do migrations and run example curl requests. 

### What is the expected result?

Data

### What do you get instead?

Calling on() on null

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | ~2.0.14
| PHP version      | 7.3.12
| Operating system | Windows

**Comment by samdark** [comment]
Looks like the issue is reported to the wrong repository. This one if for issues of the framework itself, not third party code. If you're sure that's framework issue please provide a way to reproduce it where there's no third party code involved.
