### ISSUE TITLE
registerJsFile, registerCssFile options not working

### ISSUE THREAD

**Issue by Baleen-Y** [yiisoft/yii2#18067]
### What steps will reproduce the problem?
When registering jsfile or cssfile in the view, and  options of register have depends option. Then the position and appendTimestamp in the options do not take effect
### What is the expected result?
position and appendTimestamp in the options do take effect
### What do you get instead?
-

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.27-2.0.35
| PHP version      | 7.0.33
| Operating system | linux

**Comment by Baleen-Y** [comment]
Associated with pull request #18067

**Comment by samdark** [comment]
Related to #10725.
