### ISSUE TITLE
Active Record Transaction Issue when use DAO to change DB connection at runtime by overriding getDb method

### ISSUE THREAD

**Issue by MUHAMMADTAYYAB** [yiisoft/yii2#18064]
### What steps will reproduce the problem?
1) I had to connect a database at runtime because I have hundreds of databases so I can't hard code them in db.php

2) I have override method as following

```php
        public static function getDb() {
        $conObj = new \yii\db\Connection([
            'dsn' => 'mysql:host=localhost;dbname=' . self::$dbName,
            'username' => getenv('DB_USERNAME'),
            'password' => getenv('DB_PASSWORD'),
        ]);

        return $conObj;
    }
```

My Active Record Insert as following

```php
   $transaction = self::$getDb()->beginTransaction();
        try {
            $otest = new Test();
            $otest->name = "Dummy";
            $otest->save();
            $otest2 = new Test();
            $otest2->name = "Dummy2";
            $otest2->save();
        } catch (\Exception $e) {
            echo  $e->getMessage();
        }
**/*
Note: i have not used $transaction->commit() but it is saving record which is not correct
*/**
```

### What is the expected result?
My expectation is until and unless I use  $transaction->commit() it should not be saved.

### What do you get instead?
Without using  $transaction->commit()  it is saving record.

### Additional info
Although it is working correct when I use 

```php
             self::getDb()->createCommand()
                    ->insert('test', ['name'=>'Test'])->execute();
```

**So the issue I found when I use Active Record Query. Transaction  is not working.**
**Kindly tell me the reason so that i could use Active Record.**
Thankyou very much

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 
| Operating system |

**Comment by alex-code** [comment]
Where have you overridden the `getDb` method?

**Comment by MUHAMMADTAYYAB** [comment]
I have overridden the getDb method  in my model class.

**Comment by alex-code** [comment]
I'm guessing it's because a new connection is created each time so the transaction is lost.
I'd do something like,
```php
private $conObj;

public static function getDb()
{
  if (!$this->conObj) {
    $this->conObj = new \yii\db\Connection([
      'dsn' => 'mysql:host=localhost;dbname=' . self::$dbName,
      'username' => getenv('DB_USERNAME'),
      'password' => getenv('DB_PASSWORD'),
    ]);
  }

  return $this->conObj;
}
```

**Comment by MUHAMMADTAYYAB** [comment]
> ```
> private $conObj;
> ```

Thank you very much Alexander Makaro. I got my mistake.

**Comment by samdark** [comment]
Thank @alex-code, not me ;)

**Comment by MUHAMMADTAYYAB** [comment]
> I'm guessing it's because a new connection is created each time so the transaction is lost.
> I'd do something like,
> 
> ```
> private $conObj;
> 
> public static function getDb()
> {
>   if (!$this->conObj) {
>     $this->conObj = new \yii\db\Connection([
>       'dsn' => 'mysql:host=localhost;dbname=' . self::$dbName,
>       'username' => getenv('DB_USERNAME'),
>       'password' => getenv('DB_PASSWORD'),
>     ]);
>   }
> 
>   return $this->conObj;
> }
> ```

Thank you very much alex. I got my mistake.
