### ISSUE TITLE
Improve German Message translations

### ISSUE THREAD

**Issue by frysoer** [yiisoft/yii2#18082]
#17192 # What steps will reproduce the problem?
/messsages/de/yii.php have to translations that don't fit the good style of german language for error messages.
use the 'email' and 'range' default validator for models.

### What is the expected result? (suggested change)
    '{attribute} is not a valid email address.' => '{attribute} ist keine gültige E-Mail-Adresse.',
    '{attribute} is not in the allowed range.' => '{attribute} ist außerhalb des gültigen Bereichs.',

### What do you get instead? (current)
    '{attribute} is not a valid email address.' => '{attribute} Die E-Mail-Adresse ist ungültig.',
    '{attribute} is not in the allowed range.' => '{attribute} Die Eingabe ist außerhalb des gültigen Bereichs.',

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35

**Comment by samdark** [comment]
Do you have some time for a pull request?

**Comment by mikehaertl** [comment]
I have to disagree. If you put `{attribute}` in front you get gramatically incorrect sentences:

 * Current version: "E-Mail ist keine gültige E-Mail-Adresse"
 * Suggested: "E-Mail Die E-Mail-Adresse ist ungültig." 

I also don't really see an improvement here. It all depends a little on the attribute labels of your input fields, so better to rename them if you find the resulting message doesn't sound good.

**Comment by frysoer** [comment]
guys. You've been quicker than I can reply. thx ;)
