### ISSUE TITLE
EachValidator & InlineValidator don't work together

### ISSUE THREAD

**Issue by trombipeti** [yiisoft/yii2#18096]
https://github.com/yiisoft/yii2/issues/17810 introduced a new way of using EachValidator: it uses a new instance of DynamicModel to run the validations on. This breaks the InlineValidators that'd use $this->$attribute in an inline anonymous function.

### What steps will reproduce the problem?
Have a model with an array attribute.
Create a rule in your model with EachValidator, and as a rule set an inline function, causing an InlineValidator instance to be created. In this inline anonymous function, try checking if the members of the array are valid by accessing $this->$attribute.

### What is the expected result?
$this should be the actual object on which the function was called, $this->$attribute should be one member of the array in each call.

### What do you get instead?
$this is bound to the original Model class, and $this->$attribute is the array attribute.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.4
| Operating system | Windows

**Comment by trombipeti** [comment]
I'll make a pull request with a test for this, hopefully this can be easily fixed by using https://www.php.net/manual/en/closure.bindto.php

**Comment by bizley** [comment]
Related to #18062 #18051

**Comment by samdark** [comment]
@bizley what do you think about https://github.com/yiisoft/yii2/pull/18097?

**Comment by bizley** [comment]
This indeed fixes BC problem with validation closures :+1: 
But we still have the problem with custom validation methods in model.

**Comment by trombipeti** [comment]
Doesn't https://github.com/yiisoft/yii2/pull/18052 address that?

**Comment by bizley** [comment]
It only re-enables it. There is now problem with breaking BC with how the `$this->$attribute` behaves inside. May attempt to fix it is in #18062 waiting for a review.
