### ISSUE TITLE
__call messes up static analysis

### ISSUE THREAD

**Issue by olleharstedt** [yiisoft/yii2#18093]
### What steps will reproduce the problem?

Use Psalm to analyze any code that extends Component.

### What is the expected result?

Psalm should report an error if a method is used that does not exist.

### What do you get instead?

No error message, since Component class implement magic method __call.

### Additional information

One solution is to use `@method` in the class docblock (`@property` is already used).

**Comment by samdark** [comment]
Sounds like OK solution but there's a lot of work to do it.

**Comment by olleharstedt** [comment]
Pushed a PR to Psalm here to solve this problem: https://github.com/vimeo/psalm/pull/3578

**Comment by samdark** [comment]
Closing since we can't affect it further from Yii side.

**Comment by olleharstedt** [comment]
Sure. I'll explain in more detail on the forum later how it helps Yii development.
