### ISSUE TITLE
Allow to set urlencoding to false for certain params in Url::to()

### ISSUE THREAD

**Issue by eggnukes** [yiisoft/yii2#18092]
This is a feature request. As far as I know, option to generate dynamic/pretty URLs based on URL Manager rules and allow parameters to not be encoded does not exist.

I originally posted a comment in #3656 

> One of use cases for not encoded URL is JavaScript variables.
> For example, I have a JavaScript table that populates columns based on their configuration from JSON on client's side.
> I would like to use `Url::to(['/some/controller/action', 'id' => '${data.id}'])` to have dynamic links in the resulting table. Right now only thing I can do is `Url::to(['/some/controller/action']) . '/${data.id}'`.
> However, depending on URL rules, each new parameter can create a very different URL (/some/action?id=1 or /some/action/1 or /some/controller/1), which is hard to manage when they have to be appended manually.

Right now I need this functionality, so I have been testing various other options. Apart from adding the dynamic part to the generated URL, there is also an option to call `urldecode()` on the resulting link. This is fine until you need to pass parameters that actually need encoding, like a redirect URL, for example.
Based on these situations I think the following could work - when defining the URL, allow for this configuration 
`
['/some/controller/action', 'p1' => 'test', 'p2' => ['no_encoding', false], 'p3' => 3]
`,
where a parameter can be passed as array that contains information about encoding `[$value, $encode]`.

**Comment by rob006** [comment]
@samdark What if I have URL with 5 params and only one should not be encoded? Changing state of global URL manager does not sound neither safe nor practical.

**Comment by eggnukes** [comment]
@rob006 You are correct, arrays are valid parameters - something I had not considered. Taking that into account new type of Expression seems like the only proper solution, since, as mentioned before, there are situations where one would need to encode some and not encode other parameters in the same URL.

**Comment by samdark** [comment]
Yeah. Expression-like wrapper sounds like the best idea for this case.

**Comment by WadeShuler** [comment]
@samdark How does what @rob006 proposed work? I don't see how it can at least with the current framework code around `createUrl()`.

`Url::to()` routes through the `UrlManager` to `createUrl()`, which strips the first item in the array to use for the url/route. Then the remaining items in the array are used for the params passed to `http_build_query()` which doesn't have any support for ignoring params.

Then the route/url caching has to be accounted for as well.

@eggnukes You could create your own `CustomUrl` class extending `\yii\helpers\Url` with a static `toAdvanced()` method.

Here is a snip of `Url::to()`:

```php
public static function to($url = '', $scheme = false)
{
    if (is_array($url)) {
        return static::toRoute($url, $scheme);
    }

    // ...
}
```

Custom `app\components\CustomUrl` extends `\yii\helpers\Url`:
```php
public static function toAdvanced($url = '', $config = [], $scheme = false)
{
    if (is_array($url)) {
        $ignoredParams = [];
        if ( isset($config['ignoreEncoding'] && ! empty($config['ignoreEncoding']) && is_array($config['ignoreEncoding']) )
        {
            foreach ( $config['ignoreEncoding'] as $key ) {
                if ( isset($url[$key] ) {
                    $ignoredParams[$key] = $url[$key];
                    unset($url[$key]);
                }
            }
        }
       
        $base = static::toRoute($url, $scheme);
        return $base . implode('&', $ignoredParams);
    }

    return self::to($url, $scheme);
}
```

```php
$config = [
    'ignoreEncoding' => [
        'these', 'are', 'ignored'
    ],
];

CustomUrl::toAdvanced($url, $config);
```

Please note the code I wrote above it just for illustration purposes.

**Comment by rob006** [comment]
@WadeShuler You can replace values with placeholders, pass them to `http_build_query()` and then replace placeholders with decoded values on generated URL. So essentially something like this:

```php
$url = Url::to(['site/index', 'id' => 'my-magic-placeholder']);
$url = strtr($url, ['my-magic-placeholder' => "' + id + '"]);
echo "var url = '$url';" // var url = '/site/index?id=' + id + '';
```

> Then the route/url caching has to be accounted for as well.

I don't think it will affect cache. Any examples?

**Comment by WadeShuler** [comment]
@rob006 You can do that as well. What I proposed is a bit more complicated but is a cleaner and more reusable solution.

I didn't look deeply at the caching. I noticed it when I inspected the method there was caching on these generated URLs.

```php
$url = $this->getUrlFromCache($cacheKey, $route, $params);
```

So I don't know what affect that will have, if any.

**Comment by rob006** [comment]
@WadeShuler It does not look cleaner IMO. It is a lot more complicated (and it still does not handle some cases correctly) and it is less convenient to use.

Caching not cache actual URL, only rule that was used for generation. Params are passed to generate URL using this rule.
