### ISSUE TITLE
Yii composer  bower-asset  package size: 57MB

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2#18091]
when i download yii2, i find that package size so big, finaly,  find it:

```
[root@iZ942k2d5ezZ inputmask]# pwd
/www/web/test/fecmall-2.7.1/vendor/bower-asset/inputmask
[root@iZ942k2d5ezZ inputmask]# du -lh --max-depth=1  ./
24K	./nuspecs
8.0K	./css
57M	./.git
320K	./qunit
1.9M	./dist
828K	./js
61M	./
[root@iZ942k2d5ezZ inputmask]# 
```

bower-asset contain  `.git`  , it was so big , how can it clear it auto.

**Comment by samdark** [comment]
How do you install it? See https://github.com/yiisoft/yii2/releases/download/2.0.35/yii-basic-app-2.0.35.tgz. There's no `.git` in inputmask.

**Comment by fancyecommerce** [comment]
install  yii-2.0.15
Today I installed and tested, the size of this package is normal

thanks
