### ISSUE TITLE
Mssql Schema returns wrong array content for QueryBuilder checkIntegrity()

### ISSUE THREAD

**Issue by RenschS** [yiisoft/yii2#18110]
"yii\db\mssql\Schema.php" should be fixed, following Lines will not work together:

yii\db\mssql\Schema.php 183 - 188 
yii\db\mssql\Schema.php 598 
yii\db\mssql\QueryBuilder.php 243 

findViewNames() returns something like -> [ [0] => 'SomeView' ]
findTableNames() returns something like -> [ [0] => '[SomeView]' ]

that wont work with array diff from Querybuilder. Pls fix that so findViewNames() returns words in [ ... ] too.

**Comment by darkdef** [comment]
> Pls fix that so findViewNames() returns words in [ ... ] too.

You expect "[SomeView]" (quoted name of view) in result of function \yii\db\mssql\Schema::findViewNames ?

**Comment by RenschS** [comment]
Yep
--
Gesendet über myMail für Android Samstag, 20 Juni 2020, 09:54nachm. +02:00 von DarkDef  notifications@github.com :

**Comment by achretien** [comment]
Hi @samdark just a quick note about the fix provided, it breaks `gii` for wildcard generation.

At the line https://github.com/yiisoft/yii2-gii/blob/aa5307c827e47ea5673da9bd9214bb1c7cc118bc/src/generators/model/Generator.php#L959

We test `/^\w+$/` against `[tableName]` instead if `tableName`. So we find no tables to generate.

We also change the result of a method in function of the db provider.
