### ISSUE TITLE
Active query error generate alias date

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#18111]
### What steps will reproduce the problem?
```AR::find()->select("`id` as `Jun 12, 2020`")->all();```
### What is the expected result?
```
SELECT `id` as `Jun 12, 2020` FROM `t`
```
### What do you get instead?
```
The SQL being executed was: SELECT `id` as `Jun AS `12`, 2020` FROM `t`
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.3

**Comment by alex-code** [comment]
A string param in `select()` will be parsed, either of these will work (wrapped in array).
```php
AR::find()->select(["`id` as `Jun 12, 2020`"])->all();
AR::find()->select(['Jun 12, 2020' => 'id'])->all();
```
