### ISSUE TITLE
Sort attributes add closure

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#18124]
```
$sort = new Sort([
        'attributes' => function(){return ['attr1', 'attr2']}
    ]);
```
How about add such functional?

**Comment by nicdnepr** [comment]
From docs
```
$sort = new Sort([
        'attributes' => [
            'age',
            'name' => [
                'asc' => ['first_name' => SORT_ASC, 'last_name' => SORT_ASC],
                'desc' => ['first_name' => SORT_DESC, 'last_name' => SORT_DESC],
                'default' => SORT_DESC,
                'label' => 'Name',
            ],
        ],
    ]);
```

But this not work
```
$sort = new Sort([
        'attributes' => function(){
            return ['age',
            'name' => [
                'asc' => ['first_name' => SORT_ASC, 'last_name' => SORT_ASC],
                'desc' => ['first_name' => SORT_DESC, 'last_name' => SORT_DESC],
                'default' => SORT_DESC,
                'label' => 'Name',
            ],
        ]},
    ]);
```

**Comment by darkdef** [comment]
@nicdnepr 
What version of php are you using? In version 7.4 all work

Check this code for sorting:

    $sort = new Sort([
        'attributes' => function(){
            return ['age',
            'name' => [
                'asc' => ['first_name' => SORT_ASC, 'last_name' => SORT_ASC],
                'desc' => ['first_name' => SORT_DESC, 'last_name' => SORT_DESC],
                'default' => SORT_DESC,
                'label' => 'Name',
            ],
        ];}, // added ;
    ]);

**Comment by samdark** [comment]
@darkdef I don't see how it would work since there's no code resolving this function in `\yii\data\Sort`.

@nicdnepr would you please elaborate about use case for it?

**Comment by nicdnepr** [comment]
`yii 2.0.35`
`php 7.3.17`
example
`'attributes' => ['name']`
result
![2020-06-30-060125_1920x1080_scrot](https://user-images.githubusercontent.com/2581487/86078705-58bf9500-ba97-11ea-947d-47e0c65b746b.png)

`'attributes' => function(){return ['name'];},`
result
![2020-06-30-060321_1920x1056_scrot](https://user-images.githubusercontent.com/2581487/86078878-bfdd4980-ba97-11ea-9404-b94280dab4d2.png)

Sorting attributes not sets

**Comment by darkdef** [comment]
sorry i was wrong
it's really not working

**Comment by samdark** [comment]
@nicdnepr I don't get it. Please elaborate.
