### ISSUE TITLE
[BUG] Method ActiveRecord :: find

### ISSUE THREAD

**Issue by rafaelt88** [yiisoft/yii2#18131]
Is it my impression or is it really a terrible Framework bug?

When you use ActiveRecord :: findOne ('1') or ActiveRecord :: findOne ('a1') or ActiveRecord :: findOne ('1a').

Perform the search for the first numeric portion, which should not be if my primary key is 1.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.4.2
| Operating system | Windows 7 x64

**Comment by rafaelt88** [comment]
![image](https://user-images.githubusercontent.com/4501606/85374540-f1d43600-b502-11ea-8cf7-3fe6a8f60ad5.png)
![image](https://user-images.githubusercontent.com/4501606/85374596-044e6f80-b503-11ea-8894-c68b027db660.png)
![image](https://user-images.githubusercontent.com/4501606/85374640-13352200-b503-11ea-9124-758f5370eade.png)

**Comment by rafaelt88** [comment]
@samdark

**Comment by samdark** [comment]
Let's check it. I've put together a simple test. See the pull request.

**Comment by alex-code** [comment]
I'm on MySQL 8 and running the queries below all return the same row (Queries run direct, outside of framework).
```sql
SELECT * FROM `item` WHERE `id`='1';
SELECT * FROM `item` WHERE `id`='1a';
SELECT * FROM `item` WHERE `id`='1a1';
```

It looks like MySQL sees the column as an `INT` and only uses the first valid numerical part.

**Comment by rafaelt88** [comment]
Ok, but with my version MariaDB 10.4.11 fail.
I'm use xampp 7.4.6 exactly.

**Comment by samdark** [comment]
So overall we're not doing any special validation on the framework side and do not plan to add it. It all depends on how underlying database behaves and how it is configured.

**Comment by My6UoT9** [comment]
@rafaelt88 

read up on "Strict SQL Mode",  https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-strict

> Strict mode controls how MySQL handles invalid or missing values in data-change statements such as INSERT or UPDATE. A value can be invalid for several reasons. For example, it might have the wrong data type for the column, or it might be out of range.

**Comment by rafaelt88** [comment]
Yes it's error SQL, sorry. First time that its occured.

**Comment by rafaelt88** [comment]
Can anybody help me...
I do not understand what the hell happens with MySQL, I have tried on six
different computers including a hosting.

In all it fails = / even after deleting and installing MySQL from scratch
and without changing ANYTHING, even in ONLINE editors like https://paiza.io/
and also.


> create table if not exists Test(id integer, title varchar(100));
> replace into Test values(1, "ONE"), (2, "TWO"), (30, "Hello"), (40,
> "Hello"), (50, "Hello");
> select * from Test where id IN ('1a', 'a2','3z','400','50xyz');


[image: image.png]

**Comment by alex-code** [comment]
What is the issue you're having?
If you're wanting to block `SELECT`s on ids with letters you could use `is_numeric`
```php
if (is_numeric($id)) {
  // Do query
}
```

**Comment by rafaelt88** [comment]
Can any of you try this query.
It seems silly, but I invite you to run it and comment on the result
obtained.

create table if not exists Test (id integer, title varchar (100));
> replace into Test values (1, "ONE"), (2, "TWO"), (30, "Hello"), (40,
> "Hello"), (50, "Hello");
> select * from Test where id IN ('1a', 'a2', '3z', '400', '50xyz');

**Comment by rafaelt88** [comment]
That's right, I tried too many different things and environments, I thought
I was crazy or bad until I looked for editors online and I threw the same
output.
That behavior is terrible and I have reported this in MySQL, conceptually
it shouldn't output anything ... but it does output 2 values.
