### ISSUE TITLE
[BaseObject] why className static method deprecated?

### ISSUE THREAD

**Issue by ziaratban** [yiisoft/yii2#18143]
in doc
>  Deprecated since 2.0.14. On PHP >=5.5, use ::class instead. 

i thinks `::class` is not good response for some request.

for example `::class` can not be used in dynamic class.
```php
$myDynamicObject = new \yii\helpers\Html;
echo $myDynamicObject::Class; #PHP Compile Error > Cannot use ::class with dynamic class name
```
or
```php
$myObjects = [new class1,new class2,new classN];
#very codes is here
foreach($myObjects as $obj)
    echo $myDynamicObject::Class; #PHP Compile Error > Cannot use ::class with dynamic class name
```

**Comment by Thoulah** [comment]
```
$myDynamicClass = '\yii\helpers\Html'::class;
echo $myDynamicClass; #yii\helpers\Html
```

**Comment by alex-code** [comment]
Why do you need to?
The `$myDynamicClass` variable already has the class name in it.

**Comment by darkdef** [comment]
@ziaratban 
Wait php 8.0 
https://php.watch/versions/8.0#class-constant-on-objects

I'm don't understand - why get the className string from the className string.
Show your usage case please.

**Comment by ziaratban** [comment]
@alex-code @darkdef
i edited my example and now is my answer is `Wait php 8.0`

**Comment by tourze** [comment]
when you call \yii\base\BaseObject::className(), the composer will load the class file.
\yii\base\BaseObject::class only return the a class name string "yii\base\BaseObject".
and, use XXX::class in code / config file is better for IDE like PHPStorm understand it.
