### ISSUE TITLE
Use yii2 DI in rest module

### ISSUE THREAD

**Issue by maniakalen** [yiisoft/yii2#18148]
Right now in rest actions like CreateAction model is created with:
 `$model = new $this->modelClass([
            'scenario' => $this->scenario,
        ]);`

I believe more appropriate will be if the yii tool for initialization of objects (\Yii::createObject) is used.

Regards

**Comment by samdark** [comment]
Would you please elaborate about your use case? Thanks.

**Comment by maniakalen** [comment]
My case is a RESTful API where I have some models defined in config - > container - > definitions, to include some behaviors with 'as ....' directive, but apparently CreateAction does not use the DI and instantiates the models directly with "new". So I was wondering wether this is on purpose and if not, wouldn't it be nice to adjust it. I see this as an improvement to be done

**Comment by samdark** [comment]
Is there a mistake or models are, in fact, are in container as services?
