### ISSUE TITLE
Argument 2 of yii\db\ActiveRecord::updateAll has wrong type

### ISSUE THREAD

**Issue by olleharstedt** [yiisoft/yii2#18146]
### What steps will reproduce the problem?

Analyze your Yii2 application with Psalm.

### What is the expected result?

No error.

### What do you get instead?

> ERROR: ImplementedParamTypeMismatch - vendor/yiisoft/yii2/db/ActiveRecord.php:327:51 - Argument 2 of yii\db\ActiveRecord::updateAll has wrong type 'array<array-key, mixed>|string', expecting 'array<array-key, mixed>|null' as defined by yii\db\ActiveRecordInterface::updateAll (see https://psalm.dev/199)
    public static function updateAll($attributes, $condition = '', $params = [])

The ActiveRecord class does not exactly implement the ActiveRecordInterface.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

I did a PR to fix this bug, but it was denied. :) Maybe we can discuss a solution here?

**Comment by samdark** [comment]
Related to #18114

**Comment by samdark** [comment]
1. I don't want phpdoc to contradict types that are actually expected.
2. Yes. Relational database AR interface isn't the same as its parent in terms of types you can pass.

**Comment by samdark** [comment]
How would you solve it without adding types that aren't actually expected to phpdoc?

**Comment by olleharstedt** [comment]
> I don't want phpdoc to contradict types that are actually expected.

Then change the interface docblock to exactly correspond to the actual implementation? `array|string` instead of `array|null`.

**Comment by olleharstedt** [comment]
I did the opposite in my PR, I changed the implementation, but maybe the interface should be changed instead?

**Comment by samdark** [comment]
That would make it something like `string|array|ExpressionInterface|null`. I'm actually fine about it...

**Comment by olleharstedt** [comment]
I'm indifferent. :D As long as they're the same.

**Comment by darkdef** [comment]
IMHO type of param $condition must be - mixed.
See param condition in other functions of interface file: findOne, findAll

**Comment by samdark** [comment]
At least in the interface itself.

**Comment by olleharstedt** [comment]
Thanks, will test!
