### ISSUE TITLE
Call to a member function validateCsrfToken() on string

### ISSUE THREAD

**Issue by aliabdzad** [yiisoft/yii2#18154]
i have a problem after ((Controller::$request and $response)) change
in beforeAction when we print (( $this->validateCsrfToken() )) it returns : 'request' not an object
it seems  $this->validateCsrfToken() has not the same value as Yii::$app->getRequest()->validateCsrfToken()
and this problem stops my controllers
please resolve this

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.2
| Operating system | centos

**Comment by alex-code** [comment]
Can you confirm which version you are on?
Latest Yii2 is 2.0.35 which is 20 releases ahead of the one you listed.

If you are on **.15** can you update to **.35** and test again.

**Comment by aliabdzad** [comment]
> Can you confirm which version you are on?
> Latest Yii2 is 2.0.35 which is 20 releases ahead of the one you listed.
> 
> If you are on **.15** can you update to **.35** and test again.

updated to .35 but still the same error

**Comment by samdark** [comment]
Would you please provide full error message including file, line and stracktrace?

**Comment by aliabdzad** [comment]
> Would you please provide full error message including file, line and stracktrace?

![Screenshot (363)](https://user-images.githubusercontent.com/14314385/86565890-edd1fa80-bf7d-11ea-912d-eaa2d8ab2cf7.png)

**Comment by alex-code** [comment]
Do you have an `init();` in your `SiteController`?

If so you need to call `parent::init();`

**Comment by aliabdzad** [comment]
yes ,it seems solved
thanks

**Comment by aliabdzad** [comment]
> Do you have an `init();` in your `SiteController`?
> 
> If so you need to call `parent::init();`

true, it seems solved
thanks

**Comment by nirdrabkin** [comment]
I have the same issue, but my SiteController doesn't have an `init();`
I'm running Yii2 version 2.0.36
Is there another way to solve this issue or do I need to add an `init();` function and call `parent::init();` in there?

**Comment by alex-code** [comment]
Does your `SiteController` extend from another custom `Controller` class?

**Comment by tarx1234** [comment]
Yes. I have just found what my issue was. Thank you.

**Comment by xstnet** [comment]
> Do you have an `init();` in your `SiteController`?
> 
> If so you need to call `parent::init();`

I upgraded from 2.015 to 2.0.35 and also had this problem

Thanks, that solves my problem

**Comment by konellemhs** [comment]
I upgraded from 2.015 to 2.0.35 and also had this problem
Also i tried to call the method init() and and it doesn't work either(
Can anyone help me?

**Comment by bizley** [comment]
Please use [the Forum](https://forum.yiiframework.com/) if you have any questions.
