### ISSUE TITLE
Ajax submit result in 403 for some input data

### ISSUE THREAD

**Issue by binishprabhakar** [yiisoft/yii2#18158]
### What steps will reproduce the problem?

Submitting ActiveForm data as ajax. If the form niput has **"and"** (please note the quote) or **"or"**, ajax response is 403 Forbidden
```javascript
$.ajax({
            url: url + '/project-timesheet/check-timesheet-leave',
            type: 'post',
            async: false,
            dataType: 'json',
            data: $('.timesheet-form').serialize(),
            success: function (data) {
                setTimeout(function () {
                    hideLoader();
                }, 200);
            },
            error: function () {
                hideLoader();
                bootbox.alert('Error occured while processing the request. Please try again later.');
            }
        });
```

### What is the expected result?
json arrray

### What do you get instead?
403 Forbidden

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.1
| Ubuntu 18 |

**Comment by alex-code** [comment]
Do you have **mod security** on your server?

**Comment by binishprabhakar** [comment]
Same code is working perfectly working on QA server

**Configuration:**

1. Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1107-aws x86_64)
2. PHP 7.1.33-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 26 2019 19:28NTS )

But it is not working on Production server

**Configuration:**

1. Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1017-aws x86_64)
2. PHP 7.1.33-16+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 14 2020 08:27:11) ( NTS )

**Browser Console:**

![image](https://user-images.githubusercontent.com/7431614/86885070-40442000-c112-11ea-983d-a674ad0cb5c2.png)

**Request**

![image](https://user-images.githubusercontent.com/7431614/86885292-9dd86c80-c112-11ea-921b-57db05ecd436.png)

**Response**

![image](https://user-images.githubusercontent.com/7431614/86885342-bba5d180-c112-11ea-8bca-1187fbe42508.png)

**Comment by binishprabhakar** [comment]
@alex-code **mod security** is not enabled on both the servers

**Comment by alex-code** [comment]
What's the error in the server log?
