### ISSUE TITLE
[Feature Request] Validator for nested rules

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii2#18159]
I make validator with nested rules [vjik/yii2-rules-validator](https://github.com/vjik/yii2-rules-validator).

Main case: create group validation rules and use him in several models.

For example:

```
class MyRulesValidator extends RulesValidator
{

    public $rules = [
        ['trim'],
        ['string', 'max' => 191],
        ['validateCountry'],
    ];

    public function validateCountry($model, $attribute, $params, $validator)
    {
        if (!in_array($model->$attribute, ['Russia', 'USA'])) {
            $model->addError($attribute, 'The country must be either "Russia" or "USA".');
        }
    }
}
```

... then use this in rules:

```
public function rules()
{
    return [
        ['country', MyRulesValidator::class],
    ];
}
```

Maybe something similar will appear in Yii2?

**Comment by samdark** [comment]
It looks handy and very similar to what we have in Yii 3: https://github.com/yiisoft/validator. We're not adding complicated enhancements that may break things into Yii 2 anymore so it's better for it to stay as an extension.

You've very welcome to check if Yii 3 validator package looks good for you though.
