### ISSUE TITLE
Loading big integer into the model is loaded as a float

### ISSUE THREAD

**Issue by tsvetiligo** [yiisoft/yii2#18157]
Loading an integer of 19 digits and the rule - ['account', 'match', 'pattern' => '/^\d{19}$/'] works fine, but loading an integer of 20 digits and the rule ['account', 'match', 'pattern' => '/^\d{20}$/'] leads to an error because an integer greater than 19 digits is loaded as a float.
Is this a bug or am I doing something wrong?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.3.9
| Operating system | Linux (Docker)

**Comment by samdark** [comment]
What database do you use?

**Comment by Thoulah** [comment]
My first thought: 9,223,372,036,854,775,808 is the number of non-negative values for a signed 64-bit integer. That is 19 digits.

**Comment by tsvetiligo** [comment]
> My first thought: 9,223,372,036,854,775,808 is the number of non-negative values for a signed 64-bit integer. That is 19 digits.

Yes, indeed I forgot about it. Sorry for the stupid question.
