### ISSUE TITLE
Current behavior is like that on purpose and there's a test for it in `ViewTest.php`:

### ISSUE THREAD

**Issue by Baleen-Y** [yiisoft/yii2#18160]
Current behavior is like that on purpose and there's a test for it in `ViewTest.php`:

```php
// The timestamp setting won't be redefined because global AssetManager is used
$view = new View();
$view->registerJsFile('/assetSources/js/jquery.js', [
    'appendTimestamp' => true,
    'depends' => 'yii\web\AssetBundle',
]); // <script src="/assetSources/js/jquery.js"></script>
$html = $view->render('@yiiunit/data/views/layout.php', ['content' => 'content']);
$this->assertNotRegExp($pattern, $html);
```

Similar for CSS.

The reasoning was that while script itself changes, dependencies are likely static and to be cached. That's why options of individual script / CSS aren't propagated and instead use either config of the asset bundle itself or asset manager config.

Thank you for contributing but won't merge the pull request:

1. The behavior is correct one for some valid cases.
2. It is configurable.
3. It's covered by tests so changing it is a backwards compatibility break for the functionality developers may rely on.

_Originally posted by @samdark in https://github.com/yiisoft/yii2/pull/18068#issuecomment-653251537_

**Comment by Baleen-Y** [comment]
Thanks for replying, my english is not very good. I didn't understand the reason you said. When registerJsFile or registerCssFile have depends, the options will not work.The dependent AssetBundle option of individual script / CSS also does not work. What is the meaning of this depends.

**Comment by samdark** [comment]
The options will work but will not be passed to dependencies. That was made on purpose and is exptected.

**Comment by Baleen-Y** [comment]
> The options will work but will not be passed to dependencies. That was made on purpose and is exptected.

I know it not be passed to dependencies. But the options not work. I posted an example. Details as follows：

```
// This is AssetBundle
class ModuleAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        ['/css/style.css']
    ];
    public $js = [
        ['/js/jquery.min.js'],
        ['/js/swiper.min.js']
    ];
    public $depends = [
    ];
    public $cssOptions = ['appendTimestamp' => true];
    public $jsOptions = [
        'position' => View::POS_END,
        'appendTimestamp' => true
    ];
}
// When i use it like this,  The '/js/zui.min.js' position and timestamp are not effective.
$view->registerJsFile('/js/zui.min.js',
['depends' => [ModuleAsset::class],'position' => View::POS_HEAD,'appendTimestamp' => true]
);
```

**Comment by samdark** [comment]
Do you mean that zui.min.js itself won't get `appendTimestamp` in URL?

**Comment by Baleen-Y** [comment]
> Do you mean that zui.min.js itself won't get `appendTimestamp` in URL?

Yes. zui.min.js `appendTimestamp` and `position` are not work.

**Comment by samdark** [comment]
`position` is actually expected since taking it into account will likely cause conflict with dependencies positions.

**Comment by Baleen-Y** [comment]
> `position` is actually expected since taking it into account will likely cause conflict with dependencies positions. But `appendTimestamp` not adding timestamp to primary asset isn't correct.

Thank you for your answer.
