### ISSUE TITLE
Yii::$app->response as string

### ISSUE THREAD

**Issue by zucha** [yiisoft/yii2#18168]
### What steps will reproduce the problem?
Yii::$app->response is not the \yii\web\Response class, but string

### What do you get instead?
<response><name>Exception</name><message>Call to a member function redirect() on string</message><code>0</code><type>Error</type><file>vendor/yiisoft/yii2/web/Controller.php</file><line>242</line>

### Additional info

Downgraded to 2.035 , works fine.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.2.31-1+ubuntu16.04.1+deb.sury.org+1
| Operating system |

**Comment by alex-code** [comment]
Does your `Controller` have an `init()`?
If so you need to call `parent::init();`

https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md#upgrade-from-yii-2035

**Comment by zucha** [comment]
Just testet one more time.
Added         parent::init(); and works fine.
