### ISSUE TITLE
How to make PDO treat MySQL SIGNAL SQLSTATE properly?

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2#18162]
# What steps will reproduce the problem?

I am calling a MySQL procedure from PHP using `Yii::$app->db->createCommand()->execute()`. The `PDO` is configured to throw exceptions on errors (I can see it from Yii source code).

Procedure code (made it easier for simplicity): 

```sql
DROP PROCEDURE IF EXISTS create_account;

CREATE PROCEDURE create_account(p_client INT,
                                p_currency INT,
                                p_label VARCHAR(1024),
                                OUT r_new_tx_id INT)
BEGIN
    DECLARE `client_unknown` CONDITION FOR SQLSTATE '45000';
    DECLARE id INT;
    SELECT id
    FROM clients
    WHERE id = p_client
    INTO @id;

    IF (@id > '') THEN
        SIGNAL `client_unknown`
        SET MESSAGE_TEXT = 'Unknown client';
    END IF;
    
    INSERT INTO accounts
    (account_status,
     client_id,
     currency_id,
     account_label)
    VALUES (1,
            p_client,
            p_currency,
            p_label);
    SET r_new_tx_id = LAST_INSERT_ID();
END;

```

Here is the query I make to call procedure:

```php
CALL create_account(9999, 1, 'Some label', @insert_id);
``` 

Let's assume client `9999` does not exist (we expect to get error), currency `1` exists.

If I call this procedure from MySQL CLI, I get SIGNAL error correctly, however when I try calling it from Yii it seems to be ignoring it and proceeds until `INSERT` statement. 

At the moment when `INSERT` statement is execute, foreign constraint fires to error about unknown client id. 

What is interesting, is that PDO seems to be ignoring `SIGNAL` inside condition (when it is nested), because when I move it outside (let's say, put it on the same level as `DECLARE`) it throws exception as expected. 

Is there any solution to this issue? 

#### Sidenote

I have tried to execute the same procedure in Java, using https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#executeQuery(java.lang.String) and it was throwing exceptions properly. 

From this I can assume that there is something wrong with configuration on PDO end.

### What is the expected result?

Expect to receive exception when MySQL sends SQLSTATE SIGNAL.

### What do you get instead?

PDO ignored SIGNAL and proceeds happily.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      |  7.4
| Operating system | Ubuntu

**Comment by samdark** [comment]
Would you please try doing the same using plain PDO w/o Yii? If that doesn't work - it is a problem of PDO and should be reported to https://bugs.php.net/

**Comment by bologer** [comment]
So the issue was related to the procedure which was signaling MySQL about error. It had "SHOW ERRORS;" line inside, which caused this strange behavior. After I removed this line, PDO started to recognize signals from db.
