### ISSUE TITLE
InlineValidator now binds $method to $model in 2.0.36

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#18175]
As of b642a384fa0184c58343f1d07e3d7007639fd700, InlineValidator is now binding closures to the model being validated:

https://github.com/yiisoft/yii2/blob/700ac0270644f8c7fe7a52f67ecfe8546ef86f37/framework/validators/InlineValidator.php#L76-L78

This is a change in behavior from prior versions which was not mentioned in the upgrade notes. It can lead to PHP errors from validation methods that were registered from a different class.

For example, Craft allows event-based rule registration with an `EVENT_DEFINE_RULES` event in `craft\base\Model::rules()`:

https://github.com/craftcms/cms/blob/68d7e40efc7630fc319a27e0536426028d7baa50/src/base/Model.php#L78-L89

So now if an inline validation rule is added via that event, like this:

```php
Event::on(Entry::class, Entry::EVENT_DEFINE_RULES, function(DefineRulesEvent $e) {
    $e->rules[] = ['title', function() {
        $this->someMethod();
    }];
});
```

A PHP error will occur, since `$this` within the callable is no longer a reference to the same class that the event handler was registered in; it will be the Entry object.

### What steps will reproduce the problem?

1. Add a way for other classes to register validation rules to a model’s `rules()` method.
2. From a different class, register an inline validation rule on that model, which expects `$this` to be the rule was originally defined in.
3. Validate the model.

### What is the expected result?

`$this` references the class the rule was defined in.

### What do you get instead?

`$this` references the model’s class.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | n/a
| Operating system | n/a

**Comment by brandonkelly** [comment]
I was able to work around this by wrapping inline validators’ closures in another closure (craftcms/cms@9f4105ca265c2e778bd4c679f852dda2b18c5c9d), but the change should still at least be documented in the upgrade guide.

**Comment by cs-crewsAndCaptains** [comment]
I used inline validators and js validation, that is broken with 2.0.36.

In the class "yii\validators\InlineValidator" the method "clientValidateAttribute" has a bug. The line:
`$method = $this->method->bindTo($model);`
must be:
`$method = $method->bindTo($model);`

**Comment by brandonkelly** [comment]
@cs-crewsAndCaptains Probably worth posting that as a separate issue since it’s more of a direct bug as opposed to a gap in the documentation.

**Comment by cs-crewsAndCaptains** [comment]
> @cs-crewsAndCaptains Probably worth posting that as a separate issue since it’s more of a direct bug as opposed to a gap in the documentation.

@brandonkelly okay, if have add: #18204
