### ISSUE TITLE
Response object on controller set to string since 2.0.36

### ISSUE THREAD

**Issue by julianrutten** [yiisoft/yii2#18172]
### What steps will reproduce the problem?
Unsure, for me it is just ```$this->redirect()``` in a \yii\web\Controller instance. Since 2.0.36. If this is not a known issue (since it was just introduced) let me know I will dig some to see if there is a unique use-case going on here but I don't think so.

### What is the expected result?
302 redirect

### What do you get instead?
Call to a member function redirect() on string
Line 242 of vendor/yiisoft/yii2/web/Controller.php:
return $this->response->redirect(Url::to($url), $statusCode)

### Additional info
I can see this object was introduced in 2.0.36. See https://github.com/yiisoft/yii2/pull/18083

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.3.19
| Operating system | Ubuntu 20.04

**Comment by darkdef** [comment]
if you have function init() in your controller - read https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md
```
If you have any controllers that override the init() method, make sure they are calling parent::init() at the beginning, as demonstrated in the component guide.
```

**Comment by julianrutten** [comment]
My bad! Thanks :)
