### ISSUE TITLE
yii\web\Request::cookieValidationKey must be configured with a secret key if cookies requested in 

### ISSUE THREAD

**Issue by malsatin** [yiisoft/yii2#18174]
### What steps will reproduce the problem?
* create `AppComponent` with accessing of `identity` in the `::init`
* add `AppComponent` to `bootstrap` part of config
* authenticate
* expire your session cookie

### What is the expected result?
Everything works fine, cookie reviewed, no exceptions caught

### What do you get instead?
Exception
```
yii\base\InvalidConfigException: yii\web\Request::cookieValidationKey must be configured with a secret key. in /var/www/vendor/yiisoft/yii2/web/Request.php:1678
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/web/Request.php(1660): yii\web\Request->loadCookies()
#1 /var/www/vendor/yiisoft/yii2/web/User.php(539): yii\web\Request->getCookies()
#2 /var/www/vendor/yiisoft/yii2/web/User.php(709): yii\web\User->renewIdentityCookie()
#3 /var/www/vendor/yiisoft/yii2/web/User.php(192): yii\web\User->renewAuthStatus()
#4 /var/www/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIdentity()
#5 /var/www/common/components/AppComponent.php(21): yii\base\Component->__get('identity')
#6 /var/www/vendor/yiisoft/yii2/base/BaseObject.php(109): common\components\AppComponent->init()
```

Probably because bootstraped components are caller before `cookieValidationKey` is loaded from `main-local.php`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.3
| Operating system | Linux (Debian 9)

**Comment by darkdef** [comment]
How to reproduce the problem?

This is my component
 https://yadi.sk/i/In79aR-iHh0XRA
This config of components (user and session), for quick renew.
https://yadi.sk/i/d5_qC3NW2b5nuw

It's my frontend/main-local.php
```php
$config = [
    'bootstrap' => ['message'],
    'components' => [
        'message' => [
            'class' => 'common\components\MessageComponent',
        ],
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'IP_zstcYT6LrNZ7AsUzf_8Zz5Xt_EtX1',
        ],
    ],
];
```

**Comment by malsatin** [comment]
Sorry, was not able to reproduce.
Has been seen in the log only once for the last month.

Closed.
