### ISSUE TITLE
"when" rule is not working

### ISSUE THREAD

**Issue by ChazyTheBest** [yiisoft/yii2#18179]
### What steps will reproduce the problem?

Model rules:

```php
[['type'], 'required'],
[['type'], 'integer'],
[['type'], 'in', 'range' => [self::TYPE_PARTICULAR, self::TYPE_COMPANY]],

[['name'], 'required',
    'when' => function($model) { return $model->type === self::TYPE_PARTICULAR; },
    'whenClient' => "function (attribute, value) { return $( 'input[name=\"SignupForm[type]\"]:checked' ).val() === '" . self::TYPE_PARTICULAR . "' }"],

[['company'], 'required',
    'when' => function($model) { return $model->type === self::TYPE_COMPANY; },
    'whenClient' => "function (attribute, value) { return $( 'input[name=\"SignupForm[type]\"]:checked' ).val() === '" . self::TYPE_COMPANY . "' }"],
```

Form:

```php
<?php $form = ActiveForm::begin(['id' => 'signupform']); ?>

    <?= $form->field($model, 'type')->radioList([SignupForm::TYPE_PARTICULAR => 'Particular', SignupForm::TYPE_COMPANY => 'Company']) ?>
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'company')->textInput(['maxlength' => true]) ?>
    <?php if (Yii::$app->user->can('createStaff')) {
        echo $form->field($model, 'username', ['enableAjaxValidation' => true])->textInput(['maxlength' => true]);
    } ?>
    <?= $form->field($model, 'email', ['enableAjaxValidation' => true])->input('email', ['maxlength' => true]) ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'confirm_password')->passwordInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('form', 'b_signup'), ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>
```

### What is the expected result?

If I send the form without filling `name` or `company` the model should not be valid. Also, the JSON from the Ajax validation should return an error for one of these two attributes that should be required (after setting `type`).

### What do you get instead?

The model validates just fine, instead of returning the required error:

Request:
```
SignupForm[type] [...]
  0: ""
  1: "1"
SignupForm[name]             ""
SignupForm[company]          ""
SignupForm[email]            "a@a.a"
SignupForm[password]         ""
SignupForm[confirm_password] ""
ajax                         "signupform"
```

Response:
```json
{
    "signupform-password": ["Password cannot be blank."],
    "signupform-confirm_password": ["Confirm Password cannot be blank."],
    "signupform-email": ["This email address has already been taken."]
}
```

The response is missing the `signupform-company` field. Expected JSON:
```json
{
    "signupform-company": ["Company cannot be blank."],
    "signupform-password": ["Password cannot be blank."],
    "signupform-confirm_password": ["Confirm Password cannot be blank."],
    "signupform-email": ["This email address has already been taken."]
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.4.x
| Operating system | Arch Linux

**Comment by mikehaertl** [comment]
I think `jQuery.val()` returns a string. In your `whenClient` you have `...val() === 0`. Have you tried to use `==` instead? 

Regarding the code from the `if` that confuses you: In js you can define an anonymous closure function and immediately call that function right after. If you tear it apart it's a construct like:

```js
(
    function (text) {
        alert(text);
    }
)('some test');
```
So no bug here.

**Comment by ChazyTheBest** [comment]
@mikehaertl You're right, it returns a string. I prefer quoting the value than using `==`, now it works fine.

What about the JSON response? I just tested it and the model validates both empty attributes, meaning the `required` and `when` rules are not working.

**Comment by ChazyTheBest** [comment]
Not a big deal, but maybe this should be addressed in Yii core properly?

`'when' => function($model) { return intval($model->type) === self::TYPE_PARTICULAR; },`
