### ISSUE TITLE
since 2.0.36 yii\console\Controller additional argument filtered

### ISSUE THREAD

**Issue by vinpel** [yiisoft/yii2#18170]
### What steps will reproduce the problem?
The code : 
```php
class TacheController extends \yii\console\Controller
{
 public function actionLance(string $myNumber= null)
    {
        $arguments = func_get_args();
        print_r($arguments);exit;
  }
  }
```
In a console now : 

```bash
#With yii2 Version 2.0.36  
root@e7bdd9a760ad:/app/src# ./yii ordonnateur/lance 9 force other_argument
Array
(
    [0] => 9
)
composer update

Package operations: 0 installs, 2 updates, 0 removals
  - Downgrading bower-asset/jquery (3.5.1 => 3.4.1): Loading from cache
  - Downgrading yiisoft/yii2 (2.0.36 => 2.0.35): Loading from cache
  #Now we are in yii 2.0.35
root@e7bdd9a760ad:/app/src# ./yii ordonnateur/lance 9 force other_argument
Array
(
    [0] => 9
    [1] => force
    [2] => other_argument
)
```
### What is the expected result?

```bash
 Array
(
    [0] => 9
    [1] => force
    [2] => other_argument
)
```
### What do you get instead?
```bash
Array
(
    [0] => 9
)
```
### Additional info
I have always passing additional argument to a console controller, so i can allow the free number or argument and arrange them.
Since last release (2.0.36) only the one listed seem to be passed.
I haven't noticed information in the changelog about this change.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.1.28
| Operating system | docker  debian stretch

**Comment by riemervdzee** [comment]
I am debugging a similar problem with the `CacheController::actionFlush` function which gives us troubles since the upgrade to 2.0.36 (2.0.35 worked fine). If I add a parameter name to the function, `func_get_args` gets the passed arguments correctly again. So it seems the function-signature is taken in account since the .36 release?

What happens if you add more parameternames to your function? (or post your function signature for reference)

**Comment by samdark** [comment]
> So it seems the function-signature is taken in account since the .36 release?

Yes. That's dependency injection based on action signature.

**Comment by riemervdzee** [comment]
@samdark do you wish I create another github issue for the CacheController flush's function?

**Comment by samdark** [comment]
No, arguments should not be trimmed overall. That's valid use-case.
