### ISSUE TITLE
Yii2 advanced project template - Adding more applications

### ISSUE THREAD

**Issue by NourasHamwi** [yiisoft/yii2#18183]
### What steps will reproduce the problem?

Following this [guide](https://www.yiiframework.com/extension/yiisoft/yii2-app-advanced/doc/guide/2.0/en/topic-adding-more-apps) to create an additional application which works fine but I encountered this issue which I think it is related to "Adding more applications" since it works fine in both frontend and backend.

After adding a third application, the user identity is not working outside of SiteController.

### What is the expected result?

inside SiteController

Yii::$app->user->isGuest = false;

inside UserController

Yii::$app->user->isGuest = false;

### What do you get instead?

inside SiteController

Yii::$app->user->isGuest = false;

inside UserController

Yii::$app->user->isGuest = true;

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.3
| Operating system | mac osx

**Comment by NourasHamwi** [comment]
When does the issue occur?
A couple of days ago I attempted to add a third application to my existing project additional to Frontend and Backend.

What do you see?
isGuest is returning True in UserController and False in SiteController ( as expected )

What was the expected result?
I expected isGuest to return False in both SiteController and other controllers. User identity is working fine Frontend and Backend applications, but in the third application user identity only works in SiteController.

Can you supply us with a stacktrace? (optional)
No errors are showing but Query Count is 0 and on the same action for SiteController Query Count is 3

Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)

The same action is used in SiteController and UserController

```
public function actionIsloggedin() {
		$data = [ 'identity' => \Yii::$app->user->identity , 'isGuest' => \Yii::$app->user->isGuest];
		return \Yii::createObject([
			'class'  => 'yii\web\Response',
			'format' => \yii\web\Response::FORMAT_JSON,
			'data'   => $data
		]);
}
```

**Comment by samdark** [comment]
What's your config for new application?

**Comment by NourasHamwi** [comment]
Application name is Publicend.

```
<?php
$params = array_merge(
    require __DIR__ . '/../../common/config/params.php',
    require __DIR__ . '/../../common/config/params-local.php',
    require __DIR__ . '/params.php',
    require __DIR__ . '/params-local.php'
);

return [
    'id' => 'app-publicend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'publicend\controllers',
    'bootstrap' => ['log'],
    'modules' => [],
    'components' => [
        'request' => [
        	'baseUrl' => '',
            'csrfParam' => '_csrf-publicend',
			'parsers'   => [
				'application/json' => 'yii\web\JsonParser',
			],
			'enableCookieValidation' => FALSE,
			'enableCsrfValidation'   => FALSE,
        ],
		'response'     => [
			// ...
			'formatters' => [
				\yii\web\Response::FORMAT_JSON => [
					'class'         => 'yii\web\JsonResponseFormatter',
					'prettyPrint'   => YII_DEBUG, // use "pretty" output in debug mode
					'encodeOptions' => JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE,
				],
			],
		],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => TRUE,
			'loginUrl'        => ['sign-in'],
			'authTimeout' 	  => 10800,
			'identityCookie'  => ['name' => '_identity-publicend', 'httpOnly' => TRUE],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the publicend
            'name' => 'advanced-publicend',
			'cookieParams' => [
				'path' => '',
			],
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],

        'urlManager' => [
			'class' => 'yii\web\UrlManager',
			'enablePrettyUrl'     => TRUE,
			'enableStrictParsing' => TRUE,
			'showScriptName'      => FALSE,
			'rules'               => [
				'urlFormat' => 'path',
				''                              => 'site/index',
				'sign-in' =>  'site/index',
				'account/dashboard' =>  'site/index',
				'account/information' =>  'site/index',
				'<controller:\w+>/<action:\w+>/<token:\w>/<email:\w>' => '<controller>/<action>',
				'<controller:\w+>/<action:\w+>/<name:>' => '<controller>/<action>',
				'<controller:\w+>/<action:\w+>' => '<controller>/<action>',
				[
					'class'      => 'yii\rest\UrlRule',
					'controller' => ['site', 'user', 'store'],
				],
			],
        ],

    ],
    'params' => $params,
];

```

**Comment by samdark** [comment]
That's too much info to dig into the issue. Please try forum. If you'll find out it's a but post the issue again with more details. Thanks.
