### ISSUE TITLE
cache/flush does not accept arguments in 2.0.36

### ISSUE THREAD

**Issue by xfuturomax** [yiisoft/yii2#18181]
### What steps will reproduce the problem?

`./yii cache/flush cache`

### What is the expected result?

2.0.35 and early

`Flush above cache components? (yes|no) [no]:` 

### What do you get instead?

`Error: You should specify cache components names`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.1.33-16
| Operating system | Mint 20

**Comment by samdark** [comment]
That's already fixed in master. See #18170

**Comment by rob006** [comment]
@samdark When this fix will be released? It's been 2 weeks since this was fixed.

**Comment by samdark** [comment]
Back from short vacation. Will do it this week.
