### ISSUE TITLE
MSSQL Trigger error on insert on sql server newer than 2005

### ISSUE THREAD

**Issue by RenschS** [yiisoft/yii2#18198]
Seems like Updates from 2.0.36 that added 'OUTPUTS.*' to inserts sql commands on mssql Querybuilder , dont work with Tables which include triggers. Here is my anonymized Stacktrace :

 [yii\db\Exception] SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Für die User-Zieltabelle der DML-Anweisung dürfen keine Trigger aktiviert sein, wenn die Anweisung eine OUTPUT-Klausel ohne INTO-Klausel enthält.
The SQL being executed was: INSERT INTO [User] (<someColumns>) OUTPUT INSERTED.* VALUES (<someValues>)

#1  /var/www/html/portal-yii2/vendor/yiisoft/yii2/db/Schema.php:677
#2  /var/www/html/portal-yii2/vendor/yiisoft/yii2/db/Command.php:1293
#3  /var/www/html/portal-yii2/vendor/yiisoft/yii2/db/Command.php:1093
#4  /var/www/html/portal-yii2/vendor/yiisoft/yii2/db/mssql/Schema.php:767
#5  /var/www/html/portal-yii2/wwwroot/tests/_testdata/fixtures/common/UserFixture.php:46
#6  /var/www/html/portal-yii2/vendor/yiisoft/yii2/test/FixtureTrait.php:96
#7  /var/www/html/portal-yii2/vendor/symfony/event-dispatcher/EventDispatcher.php:264
#8  /var/www/html/portal-yii2/vendor/symfony/event-dispatcher/EventDispatcher.php:239
#9  /var/www/html/portal-yii2/vendor/symfony/event-dispatcher/EventDispatcher.php:73
#1  /var/www/html/portal-yii2/vendor/yiisoft/yii2/db/Command.php:1293
#2  /var/www/html/portal-yii2/vendor/yiisoft/yii2/db/Command.php:1093
#3  /var/www/html/portal-yii2/vendor/yiisoft/yii2/db/mssql/Schema.php:767
#4  /var/www/html/portal-yii2/wwwroot/tests/_testdata/fixtures/common/UserFixture.php:46
#5  /var/www/html/portal-yii2/vendor/yiisoft/yii2/test/FixtureTrait.php:96
#6  /var/www/html/portal-yii2/vendor/symfony/event-dispatcher/EventDispatcher.php:264
#7  /var/www/html/portal-yii2/vendor/symfony/event-dispatcher/EventDispatcher.php:239
#8  /var/www/html/portal-yii2/vendor/symfony/event-dispatcher/EventDispatcher.php:73

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.3
| Operating system | Linux

**Comment by RenschS** [comment]
A colleaque of me found that article recently :   

http://www.sql-server-helper.com/error-messages/msg-334.aspx

Maybe it's a help to  find a solution for this issue.

**Comment by samdark** [comment]
@darkdef would you please take a look at it?

**Comment by darkdef** [comment]
Received. This can be fixed by using temporary tables. I'm working on it

**Comment by darkdef** [comment]
@RenschS 
May be you try my fix?
https://github.com/yiisoft/yii2/compare/master...darkdef:output_into

**Comment by RenschS** [comment]
@darkdef 
Works like a charm to me. Tested on a table with triggers on it, updating and inserting entries.
thx! hopefully 2.0.37 will get this :)
