### ISSUE TITLE
registerJsFile with argument depends set does not use the position argument (it will always default to POS_END)

### ISSUE THREAD

**Issue by mikkelcp1** [yiisoft/yii2#18192]
### What steps will reproduce the problem?
`$this->registerJsFile('@web/js/report-cards/colpo/summary/summary-chart.js', ['position' => \yii\web\View::POS_HEAD, 'depends' => [app\assets\HighChartsHeadAsset::className()]]);`

### What is the expected result?
The file '@web/js/report-cards/colpo/summary/summary-chart.js' should be included in the head (POS_HEAD)

### What do you get instead?
The file '@web/js/report-cards/colpo/summary/summary-chart.js' is included in at the end of body (POS_END)

### Additional info

See comment on pull:
https://github.com/yiisoft/yii2/pull/16826#pullrequestreview-451928486

Fix;

```
--- ./vendor/yiisoft/yii2/web/View.php.org	2020-06-11 14:18:10.681826400 -0300
+++ ./vendor/yiisoft/yii2/web/View.php	2020-07-21 09:35:33.769180800 -0300
@@ -479,7 +479,7 @@
         $url = Yii::getAlias($url);
         $key = $key ?: $url;
         $depends = ArrayHelper::remove($options, 'depends', []);
-        $position = ArrayHelper::remove($options, 'position', self::POS_END);
+
 
         try {
             $asssetManagerAppendTimestamp = $this->getAssetManager()->appendTimestamp;
@@ -490,6 +490,7 @@
         $appendTimestamp = ArrayHelper::remove($options, 'appendTimestamp', $asssetManagerAppendTimestamp);
 
         if (empty($depends)) {
+            $position = ArrayHelper::remove($options, 'position', self::POS_END);
             // register directly without AssetManager
             if ($appendTimestamp && Url::isRelative($url) && ($timestamp = @filemtime(Yii::getAlias('@webroot/' . ltrim($url, '/'), false))) > 0) {
                 $url = $timestamp ? "$url?v=$timestamp" : $url;
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7
| Operating system |

**Comment by alex-code** [comment]
@mikkelcp1 Your solution does fix the issue.
Could you do a PR for this?
