### ISSUE TITLE
Getting PHPUnit error when using file tests/data/config.local.php

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft/yii2#18194]
### What steps will reproduce the problem?

Follow installation guide provided at https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

> Some tests require additional databases to be set up and configured. You can create tests/data/config.local.php to override settings that are configured in tests/data/config.php.

Create `tests/data/config.local.php`

Setup pgsql local config

Run `user@host:/path/to/yii2$ ./vendor/bin/phpunit group=pgsql`

### What is the expected result?

No errors at CLI

### What do you get instead?

Errors at CLI:

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PHPUnit_Framework_TestResult::addError() must be an instance of Exception, instance of Error given, called in /path/to/yii2/vendor/phpunit/phpunit/src/Framework/TestSuite.php on line 699 and defined in /path/to/yii2/vendor/phpunit/phpunit/src/Framework/TestResult.php:195
Stack trace:
#0 /path/to/yii2/vendor/phpunit/phpunit/src/Framework/TestSuite.php(699): PHPUnit_Framework_TestResult->addError(Object(PHPUnit_Framework_TestSuite), Object(Error), 0)
#1 /path/to/yii2/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#2 /path/to/yii2/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#3 /path/to/yii2/vendor/phpunit/phpunit/src/TextUI/Comma in /path/to/yii2/vendor/phpunit/phpunit/src/Framework/TestResult.php on line 195

PHPUnit 4.8.34 by Sebastian Bergmann and contributors.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37-dev
| PHP version      |  7.2 at CLI
| Operating system | Ubuntu

**Comment by samdark** [comment]
Looks like it is incompatibility of PHPUnit 4.8.34 and newer PHP versions. You can either [apply patches](https://github.com/yiisoft/yii2/blob/master/composer.json#L116) or upgrade PHPUnit version. Later is better since you're already on 7.2.
