### ISSUE TITLE
ExistValidator does not work with EachValidator anymore

### ISSUE THREAD

**Issue by bizley** [yiisoft/yii2#18195]
### What steps will reproduce the problem?

Have AR model with:

```php
public $prop = [];

public function rules(): array
{
    return [
        [['prop'], 'each', 'rule' => ['exist', 'targetAttribute' => 'id']],
    ];
}
```

### What is the expected result?

`prop` validated.

### What do you get instead?

> Error : Call to undefined method yii\base\DynamicModel::find()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35 & 2.0.36
| PHP version      | *
| Operating system | *

The reason is introducing DynamicModel in EachValidator in #17944 

You can make it work with adding `'targetClass' => static::class` in the rule config but I guess there is no easy way to make it work with relations.

I went back to EachValidator from 2.0.34 and tried to find solution for it to work with typed properties without using DynamicModel but without success. The closest was the idea of adding third argument `$value` to Validator::validateAttribute() (and its children) but this would introduce BC break in all users' custom made validators.

**Comment by samdark** [comment]
I think that we can at least document it in UPGRADE. @bizley do you have some time to handle it?

**Comment by bizley** [comment]
Yes. Should it be in the upgrade section from 2.0.34 or from 2.0.36?

**Comment by samdark** [comment]
Yes.

**Comment by bizley** [comment]
So which one? :smiley:

**Comment by samdark** [comment]
from 2.0.34
