### ISSUE TITLE
Yii2 butchers SQLSTATE error in \yii\db\Exception

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#18203]
### What steps will reproduce the problem?
```PHP
// Execute under MySQL.
try
{
	\Yii::$app->getDb()->createCommand('SELECT * FROM does_not_exist')->execute();
}
catch(\yii\db\Exception $e)
{
	var_dump($e->getCode());
	die;
}
```

### What is the expected result?
When executed under MySQL:
42S02

### What do you get instead?
42

### Additional info
SQLSTATE value is NOT an integer! It can contain letter characters! This fact is correctly handled by PHP (PDOException::getCode() returns a string):

https://www.php.net/manual/en/class.pdoexception.php#pdoexception.props.code
> *code*
>     SQLSTATE error code. Use Exception::getCode() to access it. 

https://www.php.net/manual/en/exception.getcode.php
> Returns the exception code as integer in Exception but possibly as other type in Exception descendants (for example as string in PDOException). 

But for some reason Yii2 decided it would be a good idea to just convert this string code with letters to integer completely butchering its value in the process (in yii2\db\Schema.php):
```PHP
    public function convertException(\Exception $e, $rawSql)
    {
        // ...
        return new $exceptionClass($message, $errorInfo, (int)$e->getCode(), $e);
    }
```
This needs to be fixed ASAP.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 7.4.3
| Operating system |Windows 10

**Comment by alex-code** [comment]
You can get the error code from `$e->errorInfo[1]`

```php
try {
  \Yii::$app->getDb()->createCommand('SELECT * FROM does_not_exist')->execute();
} catch(\yii\db\Exception $e) {
  var_dump($e->errorInfo[1]);
  die;
}
```

**Comment by PowerGamer1** [comment]
> You can get the error code from $e->errorInfo[1]

That does NOT give you any right or reason to render perfectly good SQLSTATE value into a broken and useless integer in the `\yii\db\Exception::getCode()`.

**Comment by samdark** [comment]
Traced it down to 2011. We're doing so at least since Yii 1.1: https://github.com/yiisoft/yii/blob/master/framework/db/CDbCommand.php#L219 :)

**Comment by samdark** [comment]
We're not relying on code anywhere but I wonder if third party code does...

**Comment by alex-code** [comment]
I think this could be down to inheritance of `Exception` which expects numeric error codes (for use with http error codes?).

If the `(int)` cast was removed you could use `$exceptionMap`.

**Comment by samdark** [comment]
https://www.php.net/manual/en/exception.getcode.php:

> Returns the exception code as integer in Exception but possibly as other type in Exception descendants (for example as string in PDOException).

So having non-int is fine.

**Comment by samdark** [comment]
Thought more about it. Decided to do it and mention it in UPGRADE.md.

**Comment by Roguyt** [comment]
It still occurs when Connection errors are thrown such as HYT00 which is being cast as 0.

It is mainly visible whenever you have timeout or internet issues between your Yii2 app and your database.

The culprit seems to be this line which still cast the code as an int: https://github.com/yiisoft/yii2/blob/079ca8f647a9592c3269e0d4dec164f3533e1409/framework/db/Connection.php#L647
