### ISSUE TITLE
maxlength not present in GridView filter on top by default.

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#18200]
### What steps will reproduce the problem?
I have a Model
I have a FindModel (not a extend of Model, search function of FindModel return DataProvider with Query for Model)
I heve a rule for FindModel [['attribute'], 'string', max=>10]
I have a index view and 
I have a GridView where used dataProvider and search model.

### What is the expected result?
Filter text field within 'maxlength' = 10 in tag
### What do you get instead?
Filter with infinity length text field

note: for ActiveField this behavior is enabled by default.
for filter I must redefine column settings:
```
            [
                'attribute' => 'attribute',
                'filterInputOptions' => ['maxlength' => true],
            ],
```
or
```
            [
                'attribute' => 'attribute',
                'filterInputOptions' => ['maxlength' => 10],
            ],

```
instead of 
```
'attribute',
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | yiisoft/yii2                        2.0.36             Yii PHP Framework Version 2
| PHP version      | 7.3
| Operating system |alpine

**Comment by samdark** [comment]
Looks like an inconsistency. Could be considered a bug. Would you like to do a pull request fixing it?

**Comment by rad8329** [comment]
I'll pick this one
