### ISSUE TITLE
\yii\db\Command::bindValues + \yii\db\ArrayExpression

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#18209]
### What steps will reproduce the problem?
```phph
Yii::$app->db->createCommand(sql, [
   ':bla' => new ArrayExpression
])->queryAll()
```

### What is the expected result?
build array and bind as param

### What do you get instead?
Object of class yii\db\ArrayExpression could not be converted to string

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37-dev

**Comment by samdark** [comment]
That won't work since majority of databases do not support arrays as values bound to prepared statements.
