### ISSUE TITLE
Fixture circular dependencies

### ISSUE THREAD

**Issue by JesseHines0** [yiisoft/yii2#18213]
When using fixtures for Codeception tests, I often find that tables have circular dependencies, or that I want a fixture to load has-many relationships as well for the tests. Eg.
```
class FooFixture extends \yii\test\ActiveFixture
{
    public $modelClass = 'app\models\Foo';
    public $depends = [
        '\app\tests\fixtures\BarFixture',
    ];
}
```
```
class BarFixture extends \yii\test\ActiveFixture
{
    public $modelClass = 'app\models\Bar';
    public $depends = [
        '\app\tests\fixtures\FooFixture',
    ];
}
```
But this gives the error:
```
[yii\base\InvalidConfigException] A circular dependency is detected for fixture 'app\tests\fixtures\FooFixture'.  
                                                                                                                     
#1  .../vendor/yiisoft/yii2/test/FixtureTrait.php:214
#2  .../vendor/yiisoft/yii2/test/FixtureTrait.php:145
#3  .../vendor/yiisoft/yii2/test/FixtureTrait.php:112
#4  .../vendor/symfony/event-dispatcher/EventDispatcher.php:230
#5  .../vendor/symfony/event-dispatcher/EventDispatcher.php:59`
```

Obviously, I can remove one of the dependencies to break to loop and/or create a third fixture that depends on both FooFixture and BarFixture. But this quickly gets unwieldy when there are multiple such cases. It's already detecting if there is a circular dependency, so couldn't it simply check if a fixture has already been loaded and if so skip it?  Why is an exception needed?

| Q                | A
| ---------------- | ---
| Yii version  | 2.0.36
| PHP version | 7.4.3
| Operating system |Ubuntu 20.04

**Comment by samdark** [comment]
Likely it can. Noone tried to implement it yet. Do you want to?

**Comment by JesseHines0** [comment]
I'm not familiar with the Yii codebase, but simply not throwing the circular dependency error in FixtureTrait seems to work just fine and the unit tests still pass. Its already checking for circular dependencies to throw the error, so we can just ignore duplicate fixtures. But that seems too simple...
I'll make a pull request for it in the morning.

**Comment by samdark** [comment]
Exception is stopping the cycle. Not doing anything will likely cause infinite loop.

**Comment by JesseHines0** [comment]
That's what I expected, but removing the exception doesn't cause any infinite loops. It just skips any fixtures that have already been loaded.
