### ISSUE TITLE
wrong checkboxList items checked

### ISSUE THREAD

**Issue by johnny-silverhand** [yiisoft/yii2#18210]
### What steps will reproduce the problem?
`echo \yii\helpers\Html::checkboxList('test', ['5.1'], ['5' => '5', '5.1' => '5.1', '5.10' => '5.10']);`

### What is the expected result?
only one checkbox are checked  (key 5.1)

### What do you get instead?
two checkboxes are checked (5.1 & 5.10)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.4
| Operating system | Linux

**Comment by johnny-silverhand** [comment]
The same behavior is observed in default selection on a dropdown and radio list

**Comment by alex-code** [comment]
If your `$selection` is a string it'll work,
e.g.
```php
echo \yii\helpers\Html::checkboxList('test', '5.1', ['5' => '5', '5.1' => '5.1', '5.10' => '5.10']);
```

When `$selection` is an array is does a different type of comparison (https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L971).

I think we'd need to change the comparison type to strict on the `ArrayHelper::isIn` call or add a new option to allow it's setting.

**Comment by johnny-silverhand** [comment]
Thanks for the answer. Unfortunately, changing $selection to string doesn't work for me. I can have multiple default values.

**Comment by alex-code** [comment]
@samdark Do you think we should make the `ArrayHelper::isIn` checks strict by default for:
`Html::checkboxList`
`Html::radioList`
`Html::renderSelectOptions`

Or have an extra option?

**Comment by samdark** [comment]
@alex-code are there any possible breaks that may be caused by it?

**Comment by alex-code** [comment]
There could be with numeric keys and selections.
```php
echo \yii\helpers\Html::checkboxList('test', 5.1, ['5' => '5', '5.1' => '5.1', '5.10' => '5.10']);
```
This wouldn't match with a strict check.
Maybe an extra option is better.

**Comment by samdark** [comment]
Yes. Agree.
