### ISSUE TITLE
Use 'whenClient' on change of form fields to starred other fields

### ISSUE THREAD

**Issue by kambizzandi** [yiisoft/yii2#18222]
Hi

In the form with model I use one field for enabling 'required' for other fields:

```
	['enable', 'boolean'],

	['other1', 'required',
		'whenClient' => "function (attribute, value) {
			return $('#formname-enable')[0].checked;
		}"
	],
	['other2', 'required',
		'whenClient' => "function (attribute, value) {
			return $('#formname-enable')[0].checked;
		}"
	],
```

So I expect if I check the [Enable], [other1] and [other2] starred for attention to the user.
I suggest use 'whenClient' on change of form fields.

Thanks

### What steps will reproduce the problem?
Check and uncheck [Enable] and look at [other1] and [other2] star indicator

### What is the expected result?
I expect if I check the [Enable], [other1] and [other2] starred for attention to the user.

### What do you get instead?
Other fields not starred on [Enable] checking

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.4.7
| Operating system | Windows 10, Centos 7

**Comment by samdark** [comment]
Would you please check code from dev-master@dev? #18204 may have fixed it.

**Comment by kambizzandi** [comment]
Ok, I check it

**Comment by kambizzandi** [comment]
#18204 fixed, but this is not act on my issue.
I'm not use inline validator in this situation.
Because addRule only works on DynamicModel and my model is not.

**Comment by samdark** [comment]
Alright. Then I need a reduced test set to reproduce it. Ideally, starting with the https://github.com/yiisoft/yii2-app-basic and doing as little changes as possible.
