### ISSUE TITLE
SQL Server The target table of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause

### ISSUE THREAD

**Issue by hoaaah** [yiisoft/yii2#18221]
### What steps will reproduce the problem?
I'm using SQL Server 2017 and my database have trigger in some table. Here is my db connection setting.
```php
[
    'class' => 'yii\db\Connection',
    'dsn' => 'sqlsrv:Server=mssql;Database=database',
    'username' => 'sa',
    'password' => 'Your_password123',
    'charset' => 'utf8',
];

```
Error occured when I try to create new data, but not occured when updating data.
```php
$model = new Model();
$model->name = 'foo';
$model->bar = 'bar';
$model->save();
```
### What is the expected result?
When ```$model->save``` executed, it supposed to save data. But database exception raised.
### What do you get instead?
Database Exception raised like this.
```
The target table model' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.The SQL being executed was: INSERT INTO model [model] ([name], [bar]) OUTPUT INSERTED.* VALUES ('foo', 'bar')
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.3
| Operating system | Windows 10 2004 using Docker Container

**Comment by samdark** [comment]
Have you tried `dev-master@dev`?

**Comment by darkdef** [comment]
@hoaaah - please see and try pr #18214

**Comment by hoaaah** [comment]
Didn't see this was closed. Work like charm! Thanks @samdark @darkdef
