### ISSUE TITLE
Need a way to disable call SET ANSI_NULL_DFLT_ON ON with PDO::dblib driver

### ISSUE THREAD

**Issue by Dimetriy** [yiisoft/yii2#18229]
#17192 # What steps will reproduce the problem?
I use PDO::dblib to connect Sybase BD Server. I have a problem with last update Yii2.
File Connection.php, String 724
` if (in_array($this->getDriverName(), ['mssql', 'dblib'], true)) {
            $this->pdo->exec('SET ANSI_NULL_DFLT_ON ON');
        }`

My database does not support this option.
I urgently need a way to disable this call

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37?
| PHP version      | 7.4.9
| Operating system | Docker php:7.4.9-fpm

**Comment by samdark** [comment]
For now either roll back to previous Yii version or provide your own custom Connection instance via config.

**Comment by samdark** [comment]
@Dimetriy is there a way to tell what DB (MSSQL or Sybase) is used via MSSQL dblib connection?

**Comment by Dimetriy** [comment]
@samdark I use Sybase via dblib connection. 
Until we returned to the old version. Let's wait for the fix.

**Comment by samdark** [comment]
Yes, I understood that. I mean I want to tell which database is used from the code.

**Comment by Dimetriy** [comment]
Как то плохо у нас понимание на английском проходит. Из кода используется Sybase через драйвер dblib
`'sybase' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'dblib:host=host;dbname=db', // Sybase Server, dblib driver
            'username' => '',
            'password' => '',
            // Вообще чарсеты не работают с сайбезом
            'charset' => 'utf8',
            'attributes' => array(
                // PDO::ATTR_TIMEOUT => 180,
                // PDO:: SQLSRV_ATTR_ENCODING=>PDO::SQLSRV_ENCODING_UTF8,
                "CharacterSet" => "UTF-8",
            ),
        ],`

А вообще в проекте 3 разных коннекта к MariaDB, MongoDB, Redis, ElasticSearch и собственно Sybase

**Comment by darkdef** [comment]
> Как то плохо у нас понимание на английском проходит. Из кода используется Sybase через драйвер dblib
Ньюанс в данной задаче - что драйвер dblib используется и для sybase и mssql. И его особенность реализации - notNull поведение для создаваемых полей, которое не совпадает со стандартом. Именно для него мы задаём ansi флаг ANSI_NULL_DFLT_ON.

Хотелось бы уточнить, нет ли у вас идеи, как после коннекта, средствами pdo (к примеру \PDO::ATTR_SERVER_VERSION) - отличить к какой из видов БД мы подключились посредством dblib - к SyBase или Sql Server

**Comment by Dimetriy** [comment]
@darkdef А никак не определить. В php 5 был отдельный драйвер php_sybase, но он и тогда был крайне нестабилен, а в текущих реалиях фактически не работает. То есть фактически остается dblib с очень аккуратным его использованием, вследствие как раз таки древности нашего Sybase. Да и будем честными - Sybase настолько непопулярная система для вэб разработки что делать полноценный драйвер для него не вижу смысла. К тому же лично у нас Sybase версии 12.5, что очень древнее.
Я думаю что было бы уместно внести в конструкцию вызов (точнее отсутствие данного вызова) call SET ANSI_NULL_DFLT_ON ON при наличии переменной в конфиге. По аналогии с тем, как это сделано для баз вида MySQL для SET NAMES. Это максимально быстро и просто, как я думаю. Ну и это даст возможность отключения данного вызова для пользователей MSSQL, кому это не нужно. Опять же например для старых версий.

Как пример
```
if (in_array($this->getDriverName(), ['mssql', 'dblib'], true) && !$this->disable_set_ansi_on) 
{ 
    $this->pdo->exec('SET ANSI_NULL_DFLT_ON ON'); 
}
```

**Comment by samdark** [comment]
@darkdef вытащить в конфиг для соединения?

**Comment by darkdef** [comment]
Мне не слишком нравится идея с добавлением флагов, использование существующего массива $attributes также может привести к сбоям.
Тем не менее, вижу сейчас три варианта развития:
1. Добавление флага 
2. Убираем 
```php
         if (in_array($this->getDriverName(), ['mssql', 'dblib'], true)) {
            $this->pdo->exec('SET ANSI_NULL_DFLT_ON ON');
        }
```
3. Вариант - я всё таки поищу, как отличить к какой БД мы подключились через DBLib. Вечером планировал как раз докер с SyBase покрутить и посмотреть

**Comment by samdark** [comment]
Второй вариант плох. По дефолту MSSQL работать не будет. Так как SyBase  - штука редкая, то я бы всё-таки ввёл флаг аля `sybase`, по умолчанию `false`.

Но вариант 3 можно покрутить ещё.

**Comment by samdark** [comment]
btw., let's switch back to English :)

**Comment by Dimetriy** [comment]
@samdark @darkdef  I suggest not to strain too much, because I am afraid that this revision is only needed by me. I have now rewritten this function and changed the class to connect. It works, but it's just awkward. With future updates possible errors.

**Comment by samdark** [comment]
@darkdef flag is the easiest option.

**Comment by darkdef** [comment]
The problem exists - and must be resolved.
I'll work out some more.

**Comment by Dimetriy** [comment]
Any querys with $this->pdo->getAttribute(PDO::ATTR_SERVER_VERSION); or SERVER_INFO call error 500 with messages:

```
PDOException: SQLSTATE[HY000]: General error: 20018 Function 'SERVERPROPERTY' not found. If this is a SQLJ function, use sp_help to check whether the object exists (sp_help may produce a large amount of output).
 [20018] (severity 16) [SELECT CAST(SERVERPROPERTY('productversion') AS VARCHAR)] in /vendor/yiisoft/yii2/db/mssql/PDO.php:81
```

Call PDO::ATTR_DRIVER_NAME returns "dblib"

**Comment by Dimetriy** [comment]
SELECT @@version returns versions and db in all databases, as i know. But this is an additional query to the database on each connection.
