### ISSUE TITLE
yii\filters\RateLimiter wont work with another user component.

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#18236]
When using a custom user component (in my case `partnerUser`) the rate limiting won't work as the recived `user` value is null.

Example of behaviors setup:

```php
$behaviors['authenticator'] = [
        'class' => CompositeAuth::class,
        'authMethods' => [
            QueryParamAuth::class,
            HttpBearerAuth::class,
        ],
        'user' => Yii::$app->partnerUser,
];

$behaviors['rateLimiter'] = [
        'class' => RateLimiter::class,
        'user' => Yii::$app->partnerUser->identity,
];
```

Since the `'user' => Yii::$app->partnerUser->identity,` will receive null when setting up rateLimiter due to the login process is not done while setting up behaviors. So i think the `user` property in RateLimiter is useless.

The only solution i came up to solve my problem and also make `user` work is another check for a user service, similar to what is done when no user is specified (https://github.com/yiisoft/yii2/blob/master/framework/filters/RateLimiter.php#L84).

Solution to make `'user' => 'partnerUser'` work:

```php
// if the user is defined as service name
if (!is_object($this->user)) { 
    $this->user = Instance::ensure($this->user)->getIdentity();
}
``` 

https://github.com/yiisoft/yii2/blob/master/framework/filters/RateLimiter.php#L86

If this is an acceptable solution, i would do a PR. If there is another solution for my problem with custom user components let me know.

**update**:

Another proposed solution might be to accept closures:

```php
if ($this->user instanceof Closure) {
    $this->user = call_user_func($this->user);
}
```

**Comment by bizley** [comment]
Is it the same problem as reported in #18227 ?

**Comment by nadar** [comment]
No, i don't think so. My problem is that the RateLimiter can recieved an identity object which holds the rate limiter interface. But when registering the behaviors the identity has not been logged in yet, as the authenticator i running on `beforeAction`.

So the actually lifecycle is:

1. Controller is running.
2. Behaviors are evaluated (At this poin, is Yii::$app->partnerUser->identity null, is authenticator is not running yet)
3. Before Action event from filters (Now Yii::$app->partnerUser would recieved the identity).

So therefore the identity object must be "lazy loaded" via service locator.

**Comment by nadar** [comment]
So, to be clear:

The main problem is that `$user` (https://github.com/yiisoft/yii2/blob/master/framework/filters/RateLimiter.php#L54) requires the Identity, which is usually not available during setting up behaviors(). So either there is a solution to achieve this during behaviors() or this never worked as expected in a "real world" application setup with a custom user component.

**Comment by bizley** [comment]
You are right, looks like `user` property should take a closure so it can be evaluated in the runtime not before.

**Comment by nadar** [comment]
So i am going to create a PR :+1:. Thanks for confirming by concerns.
