### ISSUE TITLE
Add a notice for breaking inline behavior change in the docs

### ISSUE THREAD

**Issue by Anubarak** [yiisoft/yii2#18235]
### What steps will reproduce the problem?
Your recent change of inline validators breaks my code, it's easy to fix but I think you should mention that in your docs

### What is the expected result?
When using PHPStorm with EA inspections plugin you generally receive this error, when declaring a rule that doesn't use `$this` inside the closure
![image](https://user-images.githubusercontent.com/6122122/90374012-18ca6680-e073-11ea-8be5-9f3c0c018ec4.png)
So normally I "trust" those hints and make such calls static. That's what I did for all of my projects that way.
The latest version of Yii2 binds inline validators with a scope but that's not possible with static functions so I need to adjust it.
This kinda breaking behavior is not noted in the [docs](https://www.yiiframework.com/doc/guide/2.0/en/input-validation#inline-validators)

I would like to include a hint or such.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      |  7.3.0
| Operating system | Linux

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md#upgrade-from-yii-2035 mentions changes needed but doesn't mention `static`. That should be added.
