### ISSUE TITLE
VarDumper / BaseVarDumper - Feature request - allow overriding methods

### ISSUE THREAD

**Issue by karol-haltenberger** [yiisoft/yii2#18241]
It would be nice to be able to override the currently private internal methods so one could create custom vardumpers.

Use case: 
I'm building a complex data structure and sometimes I want to dump it to check something....but certain properties contained within are HUGE and make it difficult to find what I actually want to see.

I wanted to create a custom vardumper - based on VarDumper/BaseVarDumper with overrridden dump/dumpInternal methods to exclude certain classes from being fully printed (e.g. convert them to string classname) and then pass them along.

Unfortunately the dumpInternal method (and 2 others) are private, therefore I can not override them, I have to copy the whole class to create a new dumper.

Changing the methods' visibility to **protected** would allow deriving new dumpers from these.

**Comment by samdark** [comment]
Sorry for not implementing it but for this particular case copy-pasting is preferred. You case is quite specific so I'd wait for more requests about it.
