### ISSUE TITLE
Setting timezone on DB connection

### ISSUE THREAD

**Issue by ivan-redooc** [yiisoft/yii2#18256]
### What steps will reproduce the problem?
Use a DB as a Service like Mysql where you cannot set the server timezone and alter the  DB config.

### What is the expected result?
Get localized date-time

### What do you get instead?
Get UTC (or some other TZ) date-time

### Additional info
This modify follow the steps of the `charset` attribute, setting the timezone in the `initConnection()` function.

```php
class DbConnection 
{
    // new property
    public $timezone;

    // added in this function
    protected function initConnection()
    {
        $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        if ($this->emulatePrepare !== null && constant('PDO::ATTR_EMULATE_PREPARES')) {
            if ($this->driverName !== 'sqlsrv') {
                $this->pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, $this->emulatePrepare);
            }
        }
        if ($this->charset !== null && in_array($this->getDriverName(), ['pgsql', 'mysql', 'mysqli', 'cubrid'], true)) {
            $this->pdo->exec('SET NAMES ' . $this->pdo->quote($this->charset));
        }
        // analog to charser
        if ($this->timezone !== null && in_array($this->getDriverName(), ['mysql', 'mysqli'], true)) {
            $this->pdo->exec('SET time_zone = ' . $this->pdo->quote($this->timezone));
        }
        $this->trigger(self::EVENT_AFTER_OPEN);
    }

```

The config:
```php
        'db' => [
            'class' =>  yii\db\DbConnection::class,
            'dsn'      => 'mysql:host=localhost;dbname=db;charset=utf8',
            'username' => 'database',
            'password' => 'secret',
            'timezone' => 'Europe/Rome',
        ],
```
May be a day could be embed inside the DSN
`'mysql:host=localhost;dbname=db;charset=utf8;timezone=Europe/Rome'`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.3
| Operating system | Linux

**Comment by samdark** [comment]
See https://www.yiiframework.com/doc/guide/2.0/en/db-dao:

> Tip: Sometimes you may want to execute some queries right after the database connection is established to initialize some environment variables (e.g., to set the timezone or character set). You can do so by registering an event handler for the afterOpen event of the database connection. You may register the handler directly in the application configuration like so:
```php
'db' => [
    // ...
    'on afterOpen' => function($event) {
        // $event->sender refers to the DB connection
        $event->sender->createCommand("SET time_zone = 'UTC'")->execute();
    }
],
```

**Comment by saikarthikp9** [comment]
I am trying to use the "on afterOpen" snippet and as mentioned in the docs linked above. However, when i add this on afterOpen snippet of code, I get the following error: 
CException
Property "CDbConnection.on afterOpen" is not defined.

Any advice?

**Comment by samdark** [comment]
`CDbConnection` is a sign that you're using Yii 1.1 and this is the issue tracker for Yii 2.
