### ISSUE TITLE
unable to catch the errors with createCommand()->execute() when exchanging the partition 

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#18254]
### What steps will reproduce the problem?
create an action in console controller like below 

```
public function actionTest()
    {
        try {
            $sql = <<<SQL
                ALTER TABLE `transaction_history_backup`
                PARTITION BY RANGE(TO_DAYS(created_at))
                (
                    PARTITION OLD VALUES LESS THAN (TO_DAYS('2020-08-01')),
                    PARTITION CURRENT0 VALUES LESS THAN (MAXVALUE)
                );
                CREATE TABLE transaction_h LIKE transaction_history_backup;
                ALTER TABLE  transaction_h REMOVE PARTITIONING;
                ALTER TABLE transaction_history_backup EXCHANGE PARTITION OLD WITH TABLE transaction_f; //wrong target table name
                ALTER TABLE `transaction_history_backup` REMOVE PARTITIONING;
            SQL;

            Yii::$app->db->createCommand($sql)->execute();

        } catch (Exception $e) {
            echo $e->getMessage();
        }

    }
```
### What is the expected result?
I expect that the above code should catch any exceptions or errors thrown, like on the line `ALTER TABLE transaction_history_backup EXCHANGE PARTITION OLD WITH TABLE transaction_f;` i have given incorrect table name `transaction_f` which should be `transaction_h`, and i am running the above inside a transaction block too which i have'nt added in the above code currently.

### What do you get instead?
there isnt any exception raised or caught by the try catch when i run the above code, which results in not rolling back the transaction and the backup tables are left on the databases, if i run the same sql in phpmyadmin i see
![image](https://user-images.githubusercontent.com/1536454/90973758-6f85e380-e53e-11ea-8212-6ed16bac72c0.png)

Am i doing something wrong here or is this a limitation ?.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37
| PHP version      | 7.3.17
| Operating system |windows 10

**Comment by buttflattery** [comment]
i already have added the `use Exception;` statement on top of my controller @mikehaertl its not that case.

**Comment by mikehaertl** [comment]
You have more than one command in your statement, see #9894. The recommended workaround:

```
        // Make sure, we fetch all errors
        while ($command->pdoStatement->nextRowSet()) {}
```

**Comment by buttflattery** [comment]
@mikehaertl Yes you are right here, it started catching the exceptions now. but it does not seem to rollBack the transaction as i can still see the table created ` transaction_h ` where as it should not .

**Comment by mikehaertl** [comment]
Is this on MySQL? Then you can not roll back table craete/alter statements. See here https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html
