### ISSUE TITLE
AccessControl matchCallback redirect

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#18259]
### What steps will reproduce the problem?

```php
'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['test'],
                        'allow' => true,
                        'roles' => ['@'],
                         'matchCallback' => function() {
                            if (Yii::$app->user->identity->group == User::ROLE_USER) {
                                return $this->redirect(['/site/forbidden']);
                            }
                        },
                    ],
                ],
            ],
```

### What do you get instead?

first calling `actionTest` then redirect to `forbidden`
i need redirect without calling action

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.2
| Operating system |linux

**Comment by schmunk42** [comment]
I think you should return a `boolean` from `matchCallback`. Instead of redirecting in the callback.

Although it's not explicitly mentioned in
https://www.yiiframework.com/doc/api/2.0/yii-filters-accessrule#$matchCallback-detail

**Comment by samdark** [comment]
It is mentioned explicitly:

> The callback should return a boolean value indicating whether this rule should be applied.
