### ISSUE TITLE
Request::resolvePathInfo convert %2F in path to "/"

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#18266]
I have my slug at site. And when I have `%2F` chars in path, then URLManager decode it to "/" before passing request to my URLRule.

Example URL: `/prod/2%2F3` - this is goog Url, meaning value "**2/3**" for product.

Then in UrlRule:
```php
class SlugUrlRule extends Component implements UrlRuleInterface 
{
  public function parseRequest($manager, $request)
    {
        echo $request->pathInfo; exit;
    ....
```

Print:   `prod/2/3`
So, I can't parse path parts "prod" and "2/3".

I found the source of problem. 
This is Request::resolvePathInfo():

![](https://i.imgur.com/zFXL4EF.png)

Decoding whole url is broke separate components of URL by decoding "%2F" in the muddle of part to "/", after which part of path split into 2 parts.

"prod" is one part
"2%2f3" is second part

but Request make 3 parts: "prod", "2" and "3" :(

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37
| PHP version      | 7.4
| Operating system |Linux Apache

**Comment by dicrtarasov** [comment]
Commenting out 
```$pathInfo = urldecode($pathInfo);```
in Request::resolvePathInfo solve my problem

**Comment by dicrtarasov** [comment]
created pull request #18268

**Comment by samdark** [comment]
While it is not really correct, it was intended behavior when we've created Yii 2. If changed, many projects may get broken.

**Comment by samdark** [comment]
It's better for the framework as a whole to leave it as is. Would you please fix it for your case by overriding `resolvePathInfo()` in your custom request component?
