### ISSUE TITLE
beginProfile is lost in data collecting with use events  if overfull message data array in logs

### ISSUE THREAD

**Issue by lexizz** [yiisoft/yii2#18274]
Logs are writing in a data array by 1000 (default) message, then uploaded from memory (method flush).

When I use profiling, beginProfile is goes in first thousand array messages and endProfile is goes in next array messages, but there aren't any error messages.

I catch messages and processing them, then I send them in a pinba service.
scrin1
![scrin1](https://user-images.githubusercontent.com/22645458/92411427-43cf4400-f161-11ea-9d15-80e21f875bb9.png)

These are errors, which I catch.
scrin2
![scrin2](https://user-images.githubusercontent.com/22645458/92411905-36b35480-f163-11ea-95f7-f9b211da4417.png)
scrin3
![scrin3](https://user-images.githubusercontent.com/22645458/92411922-4c287e80-f163-11ea-9906-09086c6d8bf7.png)

### What steps will reproduce the problem?
on scrin1, rows 23-26

### What is the expected result?
A data from beginProfile and endProfile with one token will be in one message array always.

### What do you get instead?
It is my hypothesis:
I think we need to create a new parameter (analogous to flushInterval), in which we can set the number of messages for profiling. Data from beginProfile and endProfile with one token are counted as one message.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.2.3
| Operating system | Manjaro Linux 20.1

**Comment by samdark** [comment]
The issue seems to be valid. A unit test reproducing it would be half way of solving it.
