### ISSUE TITLE
Validate existing file in ActiveRecord

### ISSUE THREAD

**Issue by JesseHines0** [yiisoft/yii2#18278]
`yii\validators\FileValidator` only accepts `yii\web\UploadedFile` objects. Sometimes I find that I want to create an `ActiveRecord` using an existing file, for example when testing and I want to make a model with a existing dummy file, or if I need to do some kind of processing like unzipping on the file before creating the model. Would it be possible to let FileValidator accept a filepath to an existing file? Or create a new validator that does so?
```php
// In MyModel.php
public function rules() {
    return [
        [['file'], 'file',
            'mimeTypes' => 'text/*',
            // etc...
        ],
    ];
}

// later
$model = new MyModel(["file" => "path/to/file.txt"]);
$model->validate();
// ... 
```

An alternative might be to make a `FileInterface` and make `UploadedFile` and a new `File` class implement it. Then FileValidator could accept `FileInterface`.

**Comment by bizley** [comment]
It's not a job for a validator (although you could argue that DefaultValidator is doing that and you can try to use it for that purpose you are mentioning). If you need more help with this please use the forum.
