### ISSUE TITLE
yii migration create mysql table length not working

### ISSUE THREAD

**Issue by LukyHugh** [yiisoft/yii2#18271]
### What steps will reproduce the problem?
use yii migration create mysql table
···
'id' => $this->integer(length),
···

length not working

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37
| PHP version      | 7.2.33
| Operating system | macos10.15
|DB version| mysql 8.0.21

**Comment by bizley** [comment]
What is `length` in this case?

**Comment by LukyHugh** [comment]
@bizley 
When does the issue occur?
class m200904_015218_init_operation_log_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%test}}', [
            'id' => $this->integer(10),
        ], $tableOptions);
    }
What do you see?
mysql fields length display as 0
What was the expected result?
mysql fields length display as 10

**Comment by LukyHugh** [comment]
@bizley The problem is caused by mysql8.0.21

**Comment by bizley** [comment]
I see you are still waiting for reply here (don't close the issue then next time).

MySQL's integer column length was merely there to affect the way the column is being displayed, nothing else - column size was the same no matter what you have put there. In MySQL 8.0.19 this feature has been deprecated. See [this SO answer](https://stackoverflow.com/a/60892835/3364821).
