### ISSUE TITLE
RBAC DbManager::_checkAccessAssignments can not acess

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#18281]
I want to write a new DbManager extends \yii\rbac\DbManager.

I create a new method  clone from revoke()  
```php
    public function revokeWithDomain($role, $userId , $domain)
    {
        if ($this->isEmptyUserId($userId)) {
            return false;
        }

        unset($this->_checkAccessAssignments[(string) $userId]);

        return $this->db->createCommand()
            ->delete($this->assignmentTable, ['user_id' => (string) $userId, 'item_name' => $role->name , 'domain' => $domain ])
            ->execute() > 0;
    }
```

I got error on the line `unset($this->_checkAccessAssignments[(string) $userId]);`
_checkAccessAssignments  is private,  but many exist public method use it ,
If I override an exist public method , it will also got error.
How can I access  _checkAccessAssignments ?

**Comment by bizley** [comment]
This property has been made `protected` in 2.0.38, upgrade your Yii to use it like that.
