### ISSUE TITLE
Failed to generate HMAC with hash: sha256 in Yii app intermittently

### ISSUE THREAD

**Issue by SelvamPT** [yiisoft/yii2#18280]
Our yii2 app generates this exception intermittently. The issue appears to have generated from the core framework. We are not sure why it occurs intermittently.
![image](https://user-images.githubusercontent.com/32450964/92994601-578bf900-f519-11ea-8c54-0d84a3e7f8ee.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2
| PHP version      |  7.0

**Comment by samdark** [comment]
I'd say it is a problem with the server that has no sha256 available but "intermittently" makes it interesting. Would you please collect extra data? Need values of `$this->macHash` and `$rawHash` at the moment of failure. Also, removing `@` temporarily may give extra info.

**Comment by SelvamPT** [comment]
There was no configuration or environment changes made to PHP installation. It was not working for only that day's morning session. Only very few users encounter this exception, that too rarely.

**Comment by samdark** [comment]
I see. Seems we have no idea why it doesn't work in this case and without more info we cannot reproduce/fix it.

**Comment by My6UoT9** [comment]
https://stackoverflow.com/questions/33978535/php7-unknown-hashing-algorithm-sha256
