### ISSUE TITLE
Issue with computed columns and SQL Server 2005 or later

### ISSUE THREAD

**Issue by webber2k6** [yiisoft/yii2#18287]
### What steps will reproduce the problem?
I have a table in SQL Server 2014 that has one column that is computed by a function call.
```
create table [user]
(
    ...
    computed_column AS [getValue]([id])
    ...
)
```

With Yii version 2.0.36  (Issues: #13828, #17474) the inserted date is returned by the insert statement using a temporary table and an OUTPUT clause.

### What is the expected result?
The result should not be returned when the table has computed columns with function calls. This was the default behavior before version 2.0.36.
Only the insert statement should be triggered without temporary table.

`INSERT INTO [user] (...) VALUES (...);`

### What do you get instead?
> Database Exception – yii\db\Exception
> Error message: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'inserted.computed_column' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.

The executed query was something like this:
```
SET NOCOUNT ON;
DECLARE @temporary_inserted TABLE (..., [computed_column] varchar(2) NULL, ...);
INSERT INTO [user] (...) OUTPUT INSERTED.* INTO @temporary_inserted VALUES (...);
SELECT * FROM @temporary_inserted
```

Stack Trace:
1. in /var/www/html/vendor/yiisoft/yii2/db/Schema.phpat line 677
2. in /var/www/html/vendor/yiisoft/yii2/db/Command.php at line 1298– yii\db\Schema::convertException(PDOException, 'SET NOCOUNT ON;DECLARE @temporar...')
3. in /var/www/html/vendor/yiisoft/yii2/db/Command.php at line 1093– yii\db\Command::internalExecute('SET NOCOUNT ON;DECLARE @temporar...')
4. in /var/www/html/vendor/yiisoft/yii2/db/mssql/Schema.php at line 768– yii\db\Command::execute()
5. in /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php at line 600– yii\db\mssql\Schema::insert('user', [...])
6. in /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php at line 566– yii\db\ActiveRecord::insertInternal(null)
7. in /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 678– yii\db\ActiveRecord::insert(true, null)
8. yii\db\BaseActiveRecord::save()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37
| PHP version      | 7.0.*, 7.2.*
| Operating system | Windows, Linux

**Comment by samdark** [comment]
@darkdef would you please take a look?

**Comment by darkdef** [comment]
In function getValue you use subquery?

**Comment by webber2k6** [comment]
The function selects the value from another table and in this case it also uses a subquery.
I removed the subquery from the function and only returned a plain value but the result is the same.
I think the function call is causes problem here.

**Comment by darkdef** [comment]
@webber2k6 
Please try this fix for this problem
https://github.com/darkdef/yii2/commit/016220f7837fc381066136c57c6929c2c66d95d5

**Comment by webber2k6** [comment]
Hi @darkdef 

this fix seems to work. The resulting query only selects the primary key values:

```
SET NOCOUNT ON;
DECLARE @temporary_inserted TABLE ([id] int);
INSERT INTO [user] (...)
    OUTPUT INSERTED.id INTO @temporary_inserted
    VALUES (...);
SELECT * FROM @temporary_inserted
```

**Comment by williamyiu** [comment]
The OUTPUT got SQL syntax error if the column name is MSSQL keyword e.g key. 

Please add '[]' around the "OUTPUT INSERTED.id" => "OUTPUT INSERTED.[id]"

https://github.com/yiisoft/yii2/blame/master/framework/db/mssql/QueryBuilder.php
Line 490
              $columns[] = 'INSERTED.' . $column->name;
=>
              $columns[] = 'INSERTED.' . $this->db->quoteColumnName($column->name);

**Comment by darkdef** [comment]
It's right. Need fix
