### ISSUE TITLE
How to shorten controller instantiation time?

### ISSUE THREAD

**Issue by ltqTest** [yiisoft/yii2#18294]
There is such a description in the manual:
  The application creates a controller instance to handle the request.
  According to my understanding, these repeated steps are executed for every request.
  Can these be avoided?
  I tried to join the cache, but failed.Is there any solution?

**Comment by bizley** [comment]
This is how PHP works. What is that you are trying to achieve exactly?

**Comment by samdark** [comment]
https://github.com/charlesportwoodii/yii2-app-basic-psr7
