### ISSUE TITLE
\yii\base\Model::getErrorSummary reverse order

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#18308]
### What steps will reproduce the problem?
```php
echo Html::errorSummary($model, [
	'showAllErrors' => true,
]);
```
### What is the expected result?
errors in order as in validators
### What do you get instead?
reverse order

### Additional info
getErrorSummary merge old to new, not new to old
```php
$lines = array_merge((array)$es, $lines);
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39-dev
| PHP version      | PHP 7.1.33-17+ubuntu18.04.1+deb.sury.org+1
| Operating system |

**Comment by DrDeath72** [comment]
#18309

**Comment by bizley** [comment]
While I don't see the need of having errors in any particular order, maybe indeed someone depends on it, so let's correct it.

**Comment by DrDeath72** [comment]
form summary looks ugly when fields order in form reversed in errors
