### ISSUE TITLE
yii migrate/crate after(column)

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#18303]
I'm not sure if this is a bug or а missing feature, but i'm not able to specify `after('column_name')` using the console command yii migrate/crate

### What steps will reproduce the problem?

    yii migrate/create add_base_payment_column_to_cost_center_employee_table --migrationPath=backend/modules/costCenterEmployee/migrations --fields="base_payment:decimal(10,4):notNull:defaultValue(0):after('payment')" --interactive=0

### What is the expected result?

    $this->addColumn('{{%cost_center_employee}}', 'base_payment', $this->decimal(10,4)->notNull()->defaultValue(0)->after('payment'));

### What do you get instead?

    $this->addColumn('{{%cost_center_employee}}', 'base_payment', $this->decimal(10,4)->notNull()->defaultValue(0):after('payment'));

Instead of "arrow" generator puts colon. 
However if i generate migration like this `--fields="base_payment:decimal(10,4):notNull:defaultValue(0)->after('payment')"` it is genrated correctly

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38-dev

**Comment by bizley** [comment]
As I see anything that is set after `defaultValue` is treated as a part of default value chunk. Would you like to prepare a fix for this?
