### ISSUE TITLE
Bug in formatter asDate

### ISSUE THREAD

**Issue by DimkaInc** [yiisoft/yii2#18306]
When I try use formatter in "basic" config for format date, I see different year in input and output.

### What steps will reproduce the problem?
Yii::$app->formatter->asDate('2000-01-01', 'dd.MM.Y')

### What is the expected result?
01.01.2000
### What do you get instead?
01.01.1999

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0. basic
| PHP version      |  PHP 7.4.8 (cli) (built: Jul 13 2020 16:37:16) ( NTS )
| Operating system | #1 SMP Debian 4.19.118-2~bpo9+1 (2020-05-20) x86_64 GNU/Linux

**Comment by bizley** [comment]
I would say it's possible with result `31.12.1999` because `asDate` expects first parameter to be acceptable by `DateTime` with `defaultTimeZone` assumed and result is given in `timeZone`. But here you are saying it's `01.01.1999` so it's way off. Could you provide your `defaultTimeZone` and `timeZone` configuration of Formatter component?

**Comment by DimkaInc** [comment]
I'm try format some dates:
Yii::$app->formatter->asDate('1999-12-31', 'dd.MM.Y') return correct 31.12.1999
Yii::$app->formatter->asDate('2000-01-01', 'dd.MM.Y') return uncorrect 01.01.1999
Yii::$app->formatter->asDate('2000-01-02', 'dd.MM.Y') return uncorrect 02.01.1999
Yii::$app->formatter->asDate('2000-01-03', 'dd.MM.Y') return correct 03.01.2000

Changing the defaultTimeZone does not affect the displayed result.

**Comment by bizley** [comment]
Ok, so what are your values for time zones?

**Comment by DimkaInc** [comment]
Time zone: Europe/Moscow (MSK, +0300)

Why do you think that the problem is in the time zone, if the difference in dates is not 1 day, but 1 year!

**Comment by DimkaInc** [comment]
Along the way, one more question - why on earth is the time zone involved in converting the date display? If the database says 2000-01-01, then when converting the display (showing the date of the month and year in a different order), the time zone is not important in any way. And it turns out that if the library was issued a book on January 1, 2000, and when the display is converted, it will show that it was issued on January 1, 1999, when this person did not even come to the library.

**Comment by DimkaInc** [comment]
Sorry for my bad English. In my project Formatter component not modified and not set TimeZone in program.

 public $defaultTimeZone = 'UTC';

**Comment by bizley** [comment]
I was too hasty with my previous post, indeed when you are not providing time part of a date it's not being converted between defaultTimeZone and timeZone. Anyway, I cannot replicate the result and I cannot find the reason why it is happening at your machine.

1. What is the output of `\DateTime::createFromFormat('Y-m-d|', '2000-01-01', new \DateTimeZone('UTC'))` at your machine?
2. Do you have `intl` library installed?

**Comment by bizley** [comment]
And is the result same when you call `Yii::$app->formatter->asDate('2000-01-01', 'dd.MM.y')`? (notice the small `y`)

**Comment by mikehaertl** [comment]
@bizley I can reproduce it when the `language` app config is set to `de-DE`. With a lower case `y` the year is correct.

**Comment by bizley** [comment]
ICU's `Y` generally should not be used because this is the `year of "Week of Year"` (unless of course you want that specifically). `Y` may give different result than `y` at the end/beginning of the year. I didn't expect it to just flip the year though.

**Comment by bizley** [comment]
I can reproduce it at http://sandbox.onlinephpfunctions.com/code/4a93059ceac0ea1dd0b913ec7264217b4eaeee23

**Comment by bizley** [comment]
Hm, yeah, no, flipping just the year is expected, it's just one part of date format - `o`.

**Comment by mikehaertl** [comment]
@DimkaInc Have you tried to use `php:d.m.Y` as format instead? This works for me.

**Comment by DimkaInc** [comment]
Yii::$app->formatter->asDate('2000-01-01', 'dd.MM.y') show correct date.

**Comment by DimkaInc** [comment]
Thank you. And with a big letter "Y" will work?

**Comment by Mister-42** [comment]
Is `Y` perhaps like `o` in PHP?

> ISO-8601 week-numbering year. This has the same value as Y, except that if the ISO week number (W) belongs to the previous or next year, that year is used instead. (added in PHP 5.1.0)

**Comment by bizley** [comment]
Yes, exactly.
