### ISSUE TITLE
Wrong HTTP header name

### ISSUE THREAD

**Issue by thecerber** [yiisoft/yii2#18315]
https://github.com/yiisoft/yii2/blob/3dabcdb6abae2d93e04bc220b52f5ac4cec66e40/framework/web/Request.php#L1322

Please fix it. There really is no HTTP_AUTHORIZATION header. Perhaps the header Authorization is meant here? HttpBasicAuth not working now! Method \ yii \ web \ Request :: getHeaders () if it processes the $ _SERVER array, then it cuts off the HTTP_ prefix.

**Comment by samdark** [comment]
@thecerber are you sure it doesn't work? The change is there for 3+ years.

**Comment by thecerber** [comment]
@samdark Yes, I'm absolutely sure. For the whole class, this is the only place where the \yii\web\HeaderCollection::get() method is called with a argument value that has the prefix HTTP_

**Comment by thecerber** [comment]
For example:
https://github.com/yiisoft/yii2/blob/3dabcdb6abae2d93e04bc220b52f5ac4cec66e40/framework/web/Request.php#L745
https://github.com/yiisoft/yii2/blob/3dabcdb6abae2d93e04bc220b52f5ac4cec66e40/framework/web/Request.php#L1430

**Comment by alex-code** [comment]
The comment above this line says you need a rewrite rule in your web config to pass the auth to PHP.
https://github.com/yiisoft/yii2/blob/3dabcdb6abae2d93e04bc220b52f5ac4cec66e40/framework/web/Request.php#L1322
https://github.com/yiisoft/yii2/blob/3dabcdb6abae2d93e04bc220b52f5ac4cec66e40/framework/web/Request.php#L1320

**Comment by thecerber** [comment]
@alex-code i'm tried this, but it's not working for me. Moreover, this is not a solution to the problem! Please see what the \ yii \ web \ Request :: getHeaders () method returns:
```object(yii\web\HeaderCollection)#25 (1) {
  ["_headers":"yii\web\HeaderCollection":private]=>
  array(7) {
    ["content-type"]=>
    array(1) {
      [0]=>
      string(16) "application/json"
    }
    ["authorization"]=>
    array(1) {
      [0]=>
      string(50) "Basic X1J6eVJTTk4yakQyd0YzZG1kcGdpc3JEV3U5cHptdWw="
    }
    ["content-length"]=>
    array(1) {
      [0]=>
      string(2) "45"
    }
    ["host"]=>
    array(1) {
      [0]=>
      string(12) "localhost:80"
    }
    ["connection"]=>
    array(1) {
      [0]=>
      string(10) "Keep-Alive"
    }
    ["user-agent"]=>
    array(1) {
      [0]=>
      string(38) "Apache-HttpClient/4.5.12 (Java/11.0.8)"
    }
    ["accept-encoding"]=>
    array(1) {
      [0]=>
      string(12) "gzip,deflate"
    }
  }
}


Response code: 200 (OK); Time: 37ms; Content length: 778 bytes```

**Comment by thecerber** [comment]
I have checked in two official docker images yiisoftware/yii2-php:7.4-apache and yiisoftware/yii2-php:7.4-fpm

**Comment by lubosdz** [comment]
What exactly does not work for you? Basic authentication? And you think it's because of the parameter `HTTP_AUTHORIZATION` ? I am pretty sure basic authentication supplied with framework works well with standard web servers/browsers, coz I have used it, including other out-of box authentication methods (digest, bearer token ..).

I would be more suspicious about what is your client software? From your headers I can see `Apache-HttpClient/4.5.12 (Java/11.0.8)` as user agent. Does it properly handle response headers? Don't you need some additional configuration .. ?

**Comment by thecerber** [comment]
Please, follow these steps and see for yourself:

1. Deploy a test project
```bash
git clone https://github.com/thecerber/yii2-test.git
cd yii2-test 
docker-compose up -d
docker-compose exec php bash
composer install
#yii migrate
#yii generate-leads
```

2. Comment out the method \app\components\Request::getAuthCredentials() in which I corrected just one line from the parent method

3. Try to execute requests from a file test.http (for these purposes, I personally used HTTP Client the built-in the PHPStorm)

**Comment by thecerber** [comment]
The problem is that in the method \yii\web\Request::getAuthCredentials(), the call of $this->getHeaders()->get('HTTP_AUTHORIZATION') returns a NULL

**Comment by My6UoT9** [comment]
https://github.com/yiisoft/yii2/issues/13564
