### ISSUE TITLE
[Session] Doesn't work session in PostgreSQL

### ISSUE THREAD

**Issue by Myks92** [yiisoft/yii2#18326]
### What steps will reproduce the problem?

Doesn't work session in PostgreSQL 12.2

### What is the expected result?

Authorization via session DB

Quite a strange bug, because it is simple, but however my problem is not solved... I updated the framework to 2.0.38 and switched to php74. After updating the backend application that stores sessions in files is working. But the frontend application which stores sessions in the database, refuses. Can't figure out why ... Did even direct authentication:

```php
php public function actionLogin()
{
    $user = User::findOne(261);
    Yii::$app->user->login($user,1000*60*60*24);
    
    if (!Yii::$app->user->isGuest) {
        return $this->redirect('index');
        ///return $this->redirect(Yii::$app->homeUrl);
    }
}
```

```php
php public function actionIndex()
{
    var_dump(123);
    var_dump(Yii::$app->user->identity);
    die();
    
    return $this->actionLogin();
}
```

It gets to the page. This means that he will authorize it for 1 second. And in Index it already disappears after the request. In this case, sessions in the database are created and they are not expired.

Config for session component

```php
'session' => [
    'class' => 'yii\web\DbSession',
    'timeout' => intval(@$params['sessionTimeout']) ?: 180 * 60, // 180 мин
    'sessionTable' => '{{%auth_session}}',
    'writeCallback' => function ($session) {
        $loginTime = null;
        if (!Yii::$app->user->isGuest) {
            $loginTime = Yii::$app->user->identity->getLastLogin();
        }
        return [
            'user_id' => Yii::$app->user->id ?: 0,
            'ip' => Yii::$app->request->userIP,
            'login_time' => $loginTime,
        ];
    }
], 
```

[This](https://github.com/yiisoft/yii2/blob/d341bf02b4a4215e58e1315a6cbee1dca1924cbb/framework/web/DbSession.php) file works. [This](https://github.com/yiisoft/yii2/commit/4283f29a5ab2ba0c012d1d10d3590253f66cf970) commit breaks my functionality.

### What do you get instead?

Logout in one second

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.4
| Operating system | CentOS

**Comment by Myks92** [comment]
[This](https://github.com/yiisoft/yii2/commit/4283f29a5ab2ba0c012d1d10d3590253f66cf970) commit breaks my functionality

**Comment by samdark** [comment]
What's the schema of your session table?

**Comment by Myks92** [comment]
```sql 
create table auth_session
(
    id         varchar(60)  default ''::character varying not null
        constraint auth_session_pk
            primary key,
    expire     integer      default 0,
    data       text         default ''::text,
    user_id    integer      default 0,
    login_time timestamp(0),
    ip         varchar(255) default ''::character varying
);
```

**Comment by samdark** [comment]
Aha. Seems the issue is likely about data structure. Here's current one:

https://github.com/yiisoft/yii2/blob/master/framework/web/migrations/schema-pgsql.sql

**Comment by Myks92** [comment]
Changed the type, but it didn't solve the problem

```sql 
create table auth_session
(
    "id"  varchar(256) not null,
    "expire" integer,
    "data"   bytea,
    "login_time" timestamp(0),
    "ip" varchar(255)
     primary key ("id")
);
```

**Comment by Myks92** [comment]
How to reproduce the error?

1. Install Yii2 Advanced for [documentation](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md)
2. Select web server Nginx and setting configuration from documentation
3. Install PostgreSQL 12.2
4. run command in console: `php yii migrate --migrationPath=/var/www/yii2-test/vendor/yiisoft/yii2/web/migrations`
5. config main.php: 
```php 
return [
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'session' => [
            'class' => DbSession::class,
            'timeout' => 180 * 60, // 180 мин
            'sessionTable' => '{{%session}}',
        ],
    ],
];
```
6. Login user

```php
public function actionLogin()
    {
        var_dump(Yii::$app->user->identity);

        $identity = User::findOne(261);
        Yii::$app->user->login($identity);

        die();
    }
```
The first page update will return null, and the second should return the authorized user, but in my case it also returns null

**Comment by samdark** [comment]
Alright. It is highly likely it is a valid bug. We need to reproduce it now and it seems we have all the prerequisites.

**Comment by Myks92** [comment]
Very well! How can I help?

**Comment by samdark** [comment]
Right now you can't. We need to allocate some time to do the actual test locally, do git bisect to find the commit in question etc.

**Comment by alex-code** [comment]
Can you show your `User` class.

**Comment by Myks92** [comment]
I using User model from Yii advanced template.

**Comment by samdark** [comment]
@Myks92 I've tried it with instructions in https://github.com/yiisoft/yii2/issues/18326#issuecomment-708053477:

1. Got advanced app template.
2. Initialized it with dev environment.
3. Pointed DB to a Postgres instance.
4. Adjusted config to use DbSession.
5. Applied migrations (both application and session table ones).
6. `./yii serve --docroot frontend/web/`.
7. Opened frontend in the browser.
8. Registered a user.
9. Activated it.
10. Logged in keeping "remember me" off.
11. Got to other pages. Session is valid, application works well.

So overall I cannot reproduce the issue. It must be either something in your application or server config or extra options that you haven't provided.
