### ISSUE TITLE
yii migrate/to error code not returned correctly

### ISSUE THREAD

**Issue by haohetao** [yiisoft/yii2#18339]
### What steps will reproduce the problem?
yii migrate/to
### What is the expected result?
It is impossible to determine whether execution succeeds or fails in batch processing(CI/CD)
### What do you get instead?
My fix code in BaseMigrateController
![图片](https://user-images.githubusercontent.com/4592571/96338305-9c2e2580-10bf-11eb-8659-cef832ca4370.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by bizley** [comment]
Could you prepare PR for this?

**Comment by haohetao** [comment]
Why is nothing happening?

**Comment by haohetao** [comment]
I have submitted the PR

**Comment by bizley** [comment]
We kindly ask to add unit tests covering the change.
