### ISSUE TITLE
Mistake in guide

### ISSUE THREAD

**Issue by anipalary** [yiisoft/yii2#18345]
There is a mistake in russian version of guide on this page:
https://www.yiiframework.com/doc/guide/2.0/ru/input-forms
![image](https://user-images.githubusercontent.com/60285472/96868729-1e7b6880-1477-11eb-865e-ee1b29d293c9.png)
There is no mistake on english version

**Comment by githubjeka** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/input-forms.md

havent this mistake

**Comment by bizley** [comment]
Yes, looks like it appears only in rendered version.

**Comment by samdark** [comment]
@cebe any idea on why it may happen?

**Comment by cebe** [comment]
this renders fine in plain cebe/markdown, seems to be a bug in the extended version in yii2-apidoc or the website itself.

**Comment by WinterSilence** [comment]
error fixed in PhpHightlight
