### ISSUE TITLE
Typo in documentation (french) 

### ISSUE THREAD

**Issue by Pixelisator** [yiisoft/yii2#18349]
https://www.yiiframework.com/doc/guide/2.0/fr/runtime-requests#http-headers

There is a typo on title "Enntêtes HTTP", it should be "Entêtes HTTP" instead.

**Comment by bizley** [comment]
Could you prepare PR fixing it? Thanks.

**Comment by Pixelisator** [comment]
> Could you prepare PR fixing it? Thanks.

https://github.com/yiisoft/yii2/pull/18350 is that okay? (First time doing this actually)

**Comment by bizley** [comment]
Yes, it is. Thanks!
