### ISSUE TITLE
Сorrect behavior of activerecord relations in uncommitted transaction

### ISSUE THREAD

**Issue by dshashkov** [yiisoft/yii2#18357]
After upgrading app from yii 2.0.2 to yii 2.0.35 there is a problem with getting relation via junction table in uncommitted transaction

Example 3 tables with Active Records "A B C"

AR "A" has releation with AR "C" via AR "B"

    AR "A" has method 
    
        public function getC() {
              $this->hasMany(C::class, ['id' => 'c_id'])->via(self::R_B);
        }

there is a example code 

        $dbTransaction = A::getDb()->beginTransaction();

        try {
            // record in junction table "B" not exist 
            $c = $a->getC();                // null in both versions because B record not exist
            $c->link('a', $a, ['is_set' => 1]);
            // record in juction table "B" created

            // from this moment different behavior
            $c = $a->getC();          // 2.0.2 return instance of C
                                     // 2.0.35 return null 

            $dbTransaction->commit();

            $c = $a->getC() instance of C in both versions
        } catch (Exception $e) {
            $dbTransaction->rollBack();
        }

I didnt find the difference in changelog or upgrade guide. Which one behavior is correct?
Is it possible to make yii 2.0.35 same behavior like 2.0.2?

**Comment by samdark** [comment]
There are many versions between 2.0.2 and 2.0.35. Is it possible to use binary search to find out what change exactly broke it? https://en.rmcreative.ru/blog/finding-bug-with-binary-search/

**Comment by dshashkov** [comment]
> There are many versions between 2.0.2 and 2.0.35. Is it possible to use binary search to find out what change exactly broke it? https://en.rmcreative.ru/blog/finding-bug-with-binary-search/

Well i am not mighty sure about "bug nature" of this behavior in yii2.0.35. For now i want to know which one of is correct 2.0.2 or 2.0.35

**Comment by bizley** [comment]
A bit raw guess but for me the 2.0.35 version is right. You shouldn't get junction data before it's created.

**Comment by alex-code** [comment]
Does it work with a `$a->refresh()`?
