### ISSUE TITLE
Query class infinity cycle

### ISSUE THREAD

**Issue by ilyaplatov** [yiisoft/yii2#18352]
### What steps will reproduce the problem?
Add limit to query class in method one, like: 
```
public function one($db = null)
{
    return parent::limit(1)->one($db);
}
```
And run updateCounters method. 
### What is the expected result?
Update.
### What do you get instead?
Have error _Maximum function nesting level of 'x' reached_

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.0.33
| Operating system | Linux

**Comment by bizley** [comment]
You are creating an infinite recursion of method calls here. This is not a proper way of doing OOP nor the bug in Yii.
