### ISSUE TITLE
Error after upgrade composer to release 2.0.4

### ISSUE THREAD

**Issue by samuelexyz** [yiisoft/yii2#18363]
After upgrade composer to the latest version, when i try to launch 

php composer.phar update

i got 👍 The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "fxp/composer-asset-plugin" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2[dev-master, 2.0.36, ..., 2.0.38] require bower-asset/jquery 3.5.*@stable | 3.4.*@stable | 3.3.*@stable | 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> found bower-asset/jquery[3.5.1] in lock file but not in remote repositories, make sure you avoid updating this package to keep the one from lock file.
    - yiisoft/yii2[2.0.32, ..., 2.0.35] require bower-asset/jquery 3.4.*@stable | 3.3.*@stable | 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> found bower-asset/jquery[3.5.1] but it does not match the constraint.
    - yiisoft/yii2 2.0.x-dev is an alias of yiisoft/yii2 dev-master and thus requires it to be installed too.
    - Root composer.json requires yiisoft/yii2 ~2.0.32 -> satisfiable by yiisoft/yii2[2.0.32, ..., 2.0.x-dev (alias of dev-master)].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

### What steps will reproduce the problem?

upgrade composer and launch composer update 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version    |  7.4.10  
| Operating system | MacOs

**Comment by samuelexyz** [comment]
I solved it by disabling fpx-asset in composer.json

"config": { "process-timeout": 1800, "discard-changes": true, "fxp-asset": { "enabled": false } },

**Comment by schmunk42** [comment]
https://github.com/fxpio/composer-asset-plugin/issues/334

**Comment by gongkepop** [comment]
first composer self-update --1

**Comment by gongkepop** [comment]
Plugin API version ("^1.0")
composer --version
