### ISSUE TITLE
Auto generate placeholder not work

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#18366]
### What steps will reproduce the problem?
```<?= $form->field($model,'name')->textInput(['class' => 'form-control'])->label(false); ?>```
### What is the expected result?
```<input type="text" id="name" class="form-control" name="name" placeholder="value from attribute label" value="">```
### What do you get instead?
```<input type="text" id="name" class="form-control" name="name" value="">```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.2
| Operating system |

**Comment by bizley** [comment]
Why do you expect placeholder to be generated? IIRC it's not working like that...

**Comment by samdark** [comment]
You need to enable this behavior explicitly:

```php
<?= $form->field($model,'name')->textInput(['class' => 'form-control', 'placeholder' => true])->label(false); ?>
```
