### ISSUE TITLE
Psalm MethodSignatureMismatch error when extending ActiveQuery

### ISSUE THREAD

**Issue by stevekr** [yiisoft/yii2#18368]
I get Psalm MethodSignatureMismatch method has fewer parameters than parent method error.

### What steps will reproduce the problem?
```php
<?php
class TestQuery extends yii\db\ActiveQuery {}
```
### What is the expected result?
No error
### What do you get instead?
ERROR: MethodSignatureMismatch - src/TestQuery.php:2:7 - Method TestQuery::one has fewer parameters than parent method yii\db\ActiveQuery::one

### Additional info
Don't know if something could be done with ActiveQuery or is this Psalm error.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.4.5
| Operating system |MacOS 10.15.7

**Comment by bizley** [comment]
`ActiveQuery::one()` accepts an argument - `$db` (default `null`) so if you extends this method the signatures must match.

**Comment by stevekr** [comment]
How can the signature be different if I don't override this method? And even if I copy this method from ActiveQuery I still get the same error.

**Comment by bizley** [comment]
Oh, sorry, I thought that the given code is just for a general idea but it's the whole thing. So it's empty and still Psalm states error? Looks like Psalm issue TBH. But at the same time when I add the same case at https://psalm.dev/r/9aad4f413f (at least I hope it's the same) it does not show that error. Is your Psalm up-to-date?

**Comment by stevekr** [comment]
Everything is up-to-date. I also thaught this is Psalm issue, but couldn't figure out what's causing this to make sample code for bug report. If I extend `yii\db\Query` directly instead of `yii\db\ActiveQuery` then there is no error.

**Comment by stevekr** [comment]
Finally figured it out. ActiveRelationTrait was causing this error.
