### ISSUE TITLE
ActiveController ( REST api) and POINT column

### ISSUE THREAD

**Issue by DmitryBay** [yiisoft/yii2#18364]
When I used POINT column in DB (MySQL) and try to get GET:ITEMS via REST ActiveController, I get next error: 
"name": "Exception",
"message": "Malformed UTF-8 characters, possibly incorrectly encoded.",

### What steps will reproduce the problem?
Field - 
'lnglat'=>'point not null',
  

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39-dev
| PHP version      |  7.2.33
DB MySQL - image: mysql:5.7

**Comment by DmitryBay** [comment]
When does the issue occur?
in yii\rest\ActiveController, on GET request. 
when one of  DB field is POINT (NOT NULL)

What do you see?
next response:
`{
    "name": "Exception",
    "message": "Malformed UTF-8 characters, possibly incorrectly encoded.",
    "code": 5,
    "type": "yii\\base\\InvalidArgumentException",
    "file": "/app/vendor/yiisoft/yii2/helpers/BaseJson.php",
    "line": 133,
    "stack-trace": [
        "#0 /app/vendor/yiisoft/yii2/helpers/BaseJson.php(67): yii\\helpers\\BaseJson::handleJsonError(5)",
        "#1 /app/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(119): yii\\helpers\\BaseJson::encode(Array, 320)",
        "#2 /app/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(104): yii\\web\\JsonResponseFormatter->formatJson(Object(yii\\web\\Response))",
        "#3 /app/vendor/yiisoft/yii2/web/Response.php(1079): yii\\web\\JsonResponseFormatter->format(Object(yii\\web\\Response))",
        "#4 /app/vendor/yiisoft/yii2/web/Response.php(337): yii\\web\\Response->prepare()",
        "#5 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Response->send()",
        "#6 /app/frontend/web/index.php(17): yii\\base\\Application->run()",
        "#7 {main}"
    ]
}`

What was the expected result?
Array of items.  When I delete in 
Model::fields()  'POINT' column, I get good result with list of items.

**Comment by samdark** [comment]
Would you please provide table schema, a model and some code from where you make a query?

**Comment by DmitryBay** [comment]
Please clone this repository, I added some notes into readme.md.
https://github.com/DmitryBay/restbug

**Comment by mbunyan** [comment]
My reading of Yii2 RESTApi, json and ActiveModel suggests that a response does not handle binary or objects returned by the database, unless the data is converted to string or integer by SQL script. As far as I can tell, the Yii2 api's do not support geoJSON. (Though someone will correct me).

Thus an action in your controller to get the string values will provide data that can be converted to json. No doubt there are better methods to handle similar problems.
```php
public function actionTest()
    {
        $query = new \yii\db\Query;
        $query->select('id, name, ST_X(latlng) as lat, ST_Y(latlng) as lng')->from('place');
        $rows = $query->all();
        return array('status' => true, 'data' => $rows);
    }
```

There are a couple of extensions that may help:
[Yii2 Geometry Extension](https://github.com/gustarus/yii2-extension-geometry)
and
[yii2-spacial](https://github.com/sjaakp/yii2-spatial)
