### ISSUE TITLE
DI Container behavior seems to have changed since version 2.0.39

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#18373]
Since version 2.0.39 the following exception occurs. I have a DynamicModel with a Recaptcha Validator:

```
[['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator3::class, 'threshold' => 0.5],
```

https://github.com/himiklab/yii2-recaptcha-widget/blob/master/src/ReCaptchaValidator3.php => https://github.com/himiklab/yii2-recaptcha-widget/blob/master/src/ReCaptchaValidator3.php#L33 it seems this is resolved different then before?

Of course it might be a problem/adjustment needed with the 3rd party library, but since it worked before i would say its BC.

The yii2-httpclient is installed by composer `Installing yiisoft/yii2-httpclient (2.0.12): Loading from cache`. This library has no new release since over 1 year, which means its still the same code, not a problem from a recent update. The package does have a lot of installations (https://packagist.org/packages/himiklab/yii2-recaptcha-widget/stats) so i don't think i am the only one receiving this exception in near future

![image](https://user-images.githubusercontent.com/3417221/98695509-02cafa00-2373-11eb-9f06-29edbd34087f.png)

~~The requested class from the Exception starts with`Yii...` capital letter, but its `yii\httpclient\Request $httpClientRequest = null,` in the code, but not sure whether this is case sensitive or not.~~

Switch back to 2.0.38 and it works again, so regarding changelog i could be something with:

+ Enh #18285: Enhanced DI container to allow passing parameters by name in a constructor (vjik)
+ Enh #18304: Add support of constructor parameters with default values to DI container (vjik)

PHP 7.4.3 
YII 2.0.39

**Comment by nadar** [comment]
@vjik Maybe you know something regarding this?

**Comment by samdark** [comment]
@nadar is it possible to somehow get a test that reproduces it or a simple app or at least some hints about how the confuration is made?

**Comment by nadar** [comment]
The problem is because of missing `\` which is of course wrong in the library, but it worked before version 2.0.39 it seems.

Does not work:

```
class TestValidator extends Validator
{
    public function __construct(yii\httpclient\Request $httpClientRequest = null, $config = [])
    {
        parent::__construct($config);
    }
}
```

works:

```
class TestValidator extends Validator
{
    public function __construct(\yii\httpclient\Request $httpClientRequest = null, $config = [])
    {
        parent::__construct($config);
    }
}
```

To run:

```
class TestController extends \luya\web\Controller
{
    public function actionIndex()
    {
        $model = (new DynamicModel(['foo']))
            ->addRule('foo', TestValidator::class);

        $model->load([]);
    }
}
```

**Comment by samdark** [comment]
@nadar would you please check if @vjik PR fixes the issue?

**Comment by nadar** [comment]
@samdark Yes it does :+1: 

Patch release would be very nice :-)

**Comment by samdark** [comment]
Yes, will tag it.
