### ISSUE TITLE
Get cache entry only if not older than some time

### ISSUE THREAD

**Issue by patacca** [yiisoft/yii2#18372]
I think it would be useful to have a `$notOlderThan` parameter in the `ActiveQuery::cache` function that invalidate the cache entry if the entry is older than some time. It's similar to the cacheDuration but it works in the other direction.
Consider this example

```php
class SlowController extends Controller
{
	// This action is executed once every second
	public function actionSlowAction()
	{
		// Here we would like to have cached data not older than 60s
		$models = SimpleModel::find()->cache(60)-all();
		return $models;
	}
}


class FastController extends Controller
{
	// This action is executed once every 0.1s
	public function actionFastAction()
	{
		// Here we need the latest results from database so 
		// we would like to have cached data not older than 1s
		$models = SimpleModel::find()->cache(1)-all();
		return $models;
	}
}
```

When running these two actions with the specified timing what happens is that the slowAction will cache the data for 60s and during that time in the fastAction we will get the cached data even though we do not want it.
What I would like is something like this

```php
// The function cache is declared like this:
// public function cache($cacheDuration, $notOlderThan, $cacheDependency)

class SlowController extends Controller
{
	// This action is executed once every second
	public function actionSlowAction()
	{
		// Here we would like to have cached data not older than 60s
		$models = SimpleModel::find()->cache(3600, 60)-all();
		return $models;
	}
}


class FastController extends Controller
{
	// This action is executed once every 0.1s
	public function actionFastAction()
	{
		// Here we need the latest results from database so 
		// we would like to have cached data not older than 1s
		$models = SimpleModel::find()->cache(3600, 1)-all();
		return $models;
	}
}
```

In this case inside slowAction the cache entry is set to expire in 1 hour but is invalidated if has not been updated after 60s
Inside the fastAction the entry is set to expire in 1 hour but is invalidated if has not been updated after 1s

Maybe we could implement that behaviour with a TimeDependency that invalidate a cached entry if is older than some time

**Comment by bizley** [comment]
I'm not sure about that idea. Do you try to cache the same query but in two different scenarios? Is it the case? Can't you resolve it by using data query or by adding dependency to db query?

**Comment by patacca** [comment]
I don't think the scenario changes how the query are cached. If that is the case it's undocumented. I am going to try though.
The only solution I found is to use simple data caching like this

```php
class SlowController extends Controller
{
	// This action is executed once every second
	public function actionSlowAction()
	{
		// Here we would like to have cached data not older than 60s
		$models = Yii:$app->cache->getOrSet('someKey_60s', function() { return SimpleModel::find()->all(); }, 60);
		return $models;
	}
}


class FastController extends Controller
{
	// This action is executed once every 0.1s
	public function actionFastAction()
	{
		// Here we need the latest results from database so 
		// we would like to have cached data not older than 1s
		$models = Yii:$app->cache->getOrSet('someKey_1s', function() { return SimpleModel::find()->all(); }, 1);
		return $models;
	}
}
```

That would work but is less readable and a bit dirty because even though the data cached it's the same I have to use different keys. If for example in the SlowController I want data not older than 3s I end up having one query every second for the fastAction and one every 3 seconds for the slowAction but ideally I just need one every second because the slowAction could just use the already cached data

**Comment by bizley** [comment]
I mean "scenario" literally and not in Yii 2 way like in rules. You have here the same query to be cached, but in one case you want the result to be cached for 60 seconds and in the second for one second. For me it looks like not the query should be cached (or rather - not only the query) but rather the specific action result.

**Comment by patacca** [comment]
Well in the real case scenario I have the same query but I am using the results in different ways, hence the different caching durations. I will try to explain better the situation.
In my web application I've got a table in the database with a list of profiles, a model named `Profile` and there are several controller actions that are calling `Profile::find()->all()`. It's not possible to cache the entire page because the actions are doing a lot of things and need up to date results (only for some queries), fragment caching it's not an option either.
Since there are just a few actions that really need to have the up to date result of `Profile::find()->all()` I was hoping to cache that sql query result and having to re-query it only when some action needs a more recent result.
In my code I am currently using the getOrSet method as I've shown before but it's not really solving the problem

Why not having a TimeDependency so we could do
```php
$dep = new TimeDependency(60); // Invalidate cache if older than 60 seconds
SimpleModel::find()->cache(3600, $dep);
```

**Comment by bizley** [comment]
Well, exactly, as I said before - why not? `Dependency` class is extendable.

**Comment by patacca** [comment]
I didn't notice there was an abstract class Dependency, I am going to do as you say.
Are you interested in merging my code in the master branch? Otherwise we can just close this issue

**Comment by bizley** [comment]
Since this is more of a rare use case I would keep it out of core so let's close it. When such requirement will be more frequent we can always come back here.

Thanks for sharing concerns.
