### ISSUE TITLE
Container tries to instantiate class even when dependency is nullable

### ISSUE THREAD

**Issue by hustlahusky** [yiisoft/yii2#18378]
### What steps will reproduce the problem?

Got this error after upgrade from version 2.0.38 to 2.0.39.1, when resolving class that depends on queue from DI container.

```
                                                                          
  [yii\di\NotInstantiableException] Can not instantiate yii\queue\Queue.  
                                                                          
#1  /var/www/html/vendor/yiisoft/yii2/di/Container.php:407
#2  /var/www/html/vendor/yiisoft/yii2/di/Container.php:169
#3  /var/www/html/vendor/yiisoft/yii2/di/Container.php:561
#4  /var/www/html/vendor/yiisoft/yii2/di/Container.php:405
#5  /var/www/html/vendor/yiisoft/yii2/di/Container.php:169
```

IntegrationService constructor:

```php
class IntegrationService
{
    /**
     * @var Queue
     */
    private $queue;

    public function __construct(?Queue $queue = null)
    {
        $this->queue = Instance::ensure($queue ?? 'queue', Queue::class);
    }
}
```

### What is the expected result?

Expected to pass default value or `null` for nullable parameter when container cannot resolve dependency

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.1
| PHP version      | 7.2
| Operating system | Linux

**Comment by vjik** [comment]
I can't reproduce bug.
Can you show config for `IntegrationService` and full error stack?

**Comment by samdark** [comment]
@hustlahusky would you please try with https://github.com/yiisoft/yii2/pull/18379?

**Comment by hustlahusky** [comment]
@samdark @vjik seems working. Error gone after changes after applying the changes from PR

**Comment by samdark** [comment]
OK. I'm going to do a patch release then.

**Comment by SamMousa** [comment]
This patch release breaks the DI container, now all class typed dependencies are interpreted as optional..

**Comment by samdark** [comment]
Thanks for pointint it out. After the fix I'll tag another patch release.
