### ISSUE TITLE
UrlValidator can not validate for http://localhost

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#18376]
Please look at this picture. When I typed the url, it showed an error in the browser. This is not server validation because I did not click the submit button.

![image](https://user-images.githubusercontent.com/1013744/98783840-25bde280-2435-11eb-951b-1d530d1e9b81.png)

example code in Model

```php
    /**
     * @return array the validation rules.
     * 
     * @see https://www.yiiframework.com/doc/guide/2.0/en/tutorial-core-validators
     */
    public function rules()
    {

        return [
            [['name' , 'redirect_uri' , 'status'], 'required'],
            ['redirect_uri' , 'url'],
        ];
    }
```

example code in view

```php
        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'redirect_uri')->textInput(['maxlength' => true]) ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.4.11
| Operating system | WSL2 run yii2-docker

**Comment by bizley** [comment]
Not going to be changed. See https://github.com/yiisoft/validator/issues/4

**Comment by Radon8472** [comment]
> Not going to be changed. See [yiisoft/validator#4](https://github.com/yiisoft/validator/issues/4)

It seems that this effects not only localhost.
For me it seems the every local domain name (without a dot) seems to be declared as invalid.

Could you add an optional config param e.g. `allowLANdomains` with default-value to false, what would allow to disable / enable the support for simple lang domains and/or localhost?
