### ISSUE TITLE
RBAC's PhpManager generates PSR12 non-compliant file

### ISSUE THREAD

**Issue by perlexed** [yiisoft/yii2#18383]
### What steps will reproduce the problem?

Run PHP_Codesniffer with the PSR-12 ruleset against file generated by `yii\rbac\PhpManager`:

`php vendor/squizlabs/php_codesniffer/bin/phpcs --standard=PSR12 ./app/config/rbac/items.php`

### What is the expected result?

No errors or warnings

### What do you get instead?

```
FILE: ...\app\config\rbac\items.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | [x] Header blocks must be separated by a single blank
   |       |     line
 1 | ERROR | [x] End of line character is invalid; expected "\n" but
   |       |     found "\r\n"
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 16.63 secs; Memory: 28MB
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.4.6
| Operating system | Microsoft Windows 10 Pro 10.0.19042 N/A Build 19042

**Comment by samdark** [comment]
It's not working any worse but could be adjusted.

**Comment by perlexed** [comment]
> 
> 
> It's not working any worse but could be adjusted.

I've made the pull request https://github.com/yiisoft/yii2/pull/18384 but it's PR builds failed smh
