### ISSUE TITLE
PHP 8 - "There is no active transaction" when transaction is autocommitted

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#18406]
As of PHP 8, `PDO::commit()` and `rollBack()` will throw a `There is no active transaction` PDOException if the transaction had been autocommitted, as MySQL will do whenever a schema change is made. Previously they would fail silently.

The change was made in this commit: https://github.com/php/php-src/commit/990bb34891c83d12c5129fd781893704f948f2f4

### What steps will reproduce the problem?

1. Connect to a MySQL database
2. Call `Yii::$app->db->beginTransaction()`
3. Make a schema change, such as add a new column to a table (the transaction will be autocommitted in the process)
4. Call `Yii::$app->db->commit()`

### What is the expected result?

PHP would move along to the next line of code, regardless of whether the app is running on PHP 5, 7, or 8.

_(Note: it could be argued that an exception should in fact be thrown here in Yii 3, but I think it’s best to avoid a BC break in Yii 2.)_

### What do you get instead?

A PDOException is thrown with the message `There is no active transaction` when running PHP 8.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.3
| PHP version      | 8.0.0RC3
| Operating system | Ubuntu 20.04.1 LTS

**Comment by twisted1919** [comment]
@samdark - could this be pushed to 1.1.x as well?

**Comment by samdark** [comment]
@twisted1919 it could. Someone just needs to prepare a pull request. I don't currently have time for it. Busy with Yii 3.

**Comment by twisted1919** [comment]
@samdark - i've opened https://github.com/yiisoft/yii/issues/4339 to have it there as well

**Comment by dioncodes** [comment]
Had the same issue with PHP 8 in general, but when calling `$db->setAttribute(PDO::ATTR_AUTOCOMMIT, 0);` before the `beginTransaction()` it works.

**Comment by alexandre-leng** [comment]
i had the same bug
