### ISSUE TITLE
Support fixed binary columns

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#18409]
### What steps will reproduce the problem?

Create a column like this in a migration: `$this->binary(16)`.

### What is the expected result?
Initially I expected it would create a column type `binary`.

### What do you get instead?
I get a blob column; I then tried to manually specify the column like this: `"binary(16)"`, but due to `getColumnType()` implementation this still becomes a blob column.

Note that I realize we shouldn't change the way `binary()` works, but we should support a different method of creating a fixed binary string.

### Workaround
By looking at the way `getColumnType()` uses regexes I came up with a workaround:
```php
// Note the space before the column type
$this->db->createCommand()->createTable('{{%test}}', ['id' => ' binary(16)']);

```

This issue is here so others might find it if they run into the same issue; that's valuable even if we don't implement the feature in Yii2.

**Comment by My6UoT9** [comment]
Is this not related to other supported databases not having that datatype?

**Comment by SamMousa** [comment]
I think every database has that time.

**Comment by bizley** [comment]
What engine is this?

**Comment by SamMousa** [comment]
mysql

**Comment by bizley** [comment]
As I can see in Yii MySQL column mapping binary is blob. I'm not sure why it was done like that though. I guess it's because blob doesn't have binary's size restrictions? Anyway, the question is - is blob not good?

**Comment by SamMousa** [comment]
Yeah, blob require additional management for things like indexes. Also blobs are often not stored in the record but outside it and therefore have different performance characteristics.

**Comment by My6UoT9** [comment]
If I am not mistaken, sqllite does not have binary datatype,
https://www.sqlite.org/datatype3.html#affinity_name_examples

**Comment by SamMousa** [comment]
For sqlite it should indeed map to `blob`. 

> I think every database has that type.

I'll weaken this statement; most databases have this type...

**Comment by samdark** [comment]
The change may result it a serious backwards compatibility break in the apps, right?

**Comment by SamMousa** [comment]
No, I'm not proposing to change any existing behavior

**Comment by SamMousa** [comment]
If we implement this support, which I'm not even saying we should, then we could do it by adding a new helper function..

I'm also fine documenting the workaround above.. The mere fact it only comes up now means it is not very common anyway.

**Comment by samdark** [comment]
> a new helper function

`->realBinary()`?

**Comment by SamMousa** [comment]
Or `fixedLengthBinary`

**Comment by samdark** [comment]
`fixedLengthBinary` even looks alright. That might work overall.

**Comment by My6UoT9** [comment]
As long as they same code can be used with any underlying database..

**Comment by samdark** [comment]
Yes, sure.
