### ISSUE TITLE
mssql: list foreignkeys, missing schema information

### ISSUE THREAD

**Issue by rauwebieten** [yiisoft/yii2#18401]
I'm using the yii\db\schema component with SQL-server (sqlsrv driver) to query all foreign keys. My database has several schema's with relations between them.

The foreignKeys property on the table schema does not provide any information on the schema of the target table.

### What steps will reproduce the problem?

I have a db with two schema's:
dbo.example
dbo2.sometable
with foreign key relations between them.

        /** @var Connection $db */
        $db = Yii::$app->get('db');

        /** @var Schema $schema */
        $schema = $db->getSchema();

        /** @var TableSchema $tableSchema */
        $tableSchema = $schema->getTableSchema('dbo.example');

        var_dump($tableSchema->foreignKeys);

### What is the expected result?

I except to receive not only the target table, but also the target schema in the result.

### What do you get instead?

only the target table name:

```
array(1) {
  ["FK_NAME"]=>
  array(2) {
    [0]=>
    string(8) "TARGET_TABLENAME"
    ["column_name"]=>
    string(11) "target_column_name"
  }
}
```

### Additional info

According to this link: https://www.mssqltips.com/sqlservertip/1151/identify-all-of-your-foreign-keys-in-a-sql-server-database/
the info can be queried.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.1
| Operating system | Window 10
| SQL server | Microsoft SQL Server 2005 - 9.00.3042.00 (Intel X86)

**Comment by lubosdz** [comment]
What's the MS SQL version?

**Comment by rauwebieten** [comment]
Microsoft SQL Server 2005 - 9.00.3042.00 (Intel X86)

**Comment by lubosdz** [comment]
I am not sure whether such ancient server version is still officially supported anywhere. There have been [8 major releases](https://en.wikipedia.org/wiki/History_of_Microsoft_SQL_Server) since 2005 and schemas differ significantly from version to version AFAIK. It would cost enormous time to investigate (setup environment, emulate error ..) for this one specific issue - if there are no other reports for similar issue.

**Comment by rauwebieten** [comment]
Yes true, thanks anyway.
