### ISSUE TITLE
Improving Request::getPreferredLanguage

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#18410]
Problems with current implementation of `Request::getPreferredLanguage`:
1. Inconsistent return values in case "negotiation failed":
 a) user requests langs [A, B], app supports langs [C, D] -> negotiation failed due to no match -> return value is `$languages[0]`.
 b) user requests langs [A, B], app supports [] -> negotiation failed due to no match -> return value is `$app->language`.
2. No way to distinguish the "negotiation failed" scenario in the caller code (such distinction is needed to run additional custom language selection code).
3. Function is dependent on `$app` for no good reason.

The `getPreferredLanguage(array $languages = [])` should be changed to `getPreferredLanguage(array $languages = [], $fallbackLanguage = null)` and return $fallbackLanguage in all "negatiation failed" scenarios.
This solves problems above:
1. a) has same return value as b).
2. "negotiation failed" is reported as null return value.
3. No dependency on `$app`.

BC break is easy to fix:
before:
`$langs = [...]; $result = getPreferredLanguage($langs);`
should be changed to
`$langs = [...]; $result = getPreferredLanguage($langs, $langs[0]);`

**Comment by bizley** [comment]
But `getPreferredLanguage` is not used for language negotiation. This meant to be only for presenting the list of languages that user may choose from.

**Comment by My6UoT9** [comment]
>  * Returns the user-preferred language that should be used by this application.
>      * The language resolution is based on the user preferred languages and the languages
>      * supported by the application. The method will try to find the best match.

**Comment by bizley** [comment]
I'm referring to the content negotiation. Please correct me if I'm mistaken about this somehow.

**Comment by My6UoT9** [comment]
I think I do misunderstand.
I understand the function `Request::getPreferredLanguage` as such that it does parse the users preferred languages.
The information from this can be used for content negotiation.
As such, there is a `ContentNegotiator::negotiateLanuguage` which increases my confusion.

The current implementation of  `Request::getPreferredLanguage` does not allow differ if the returned language is a default, or preferred by the user. I think that is what the OP is referring to.

**Comment by PowerGamer1** [comment]
@bizley
> But `getPreferredLanguage` is not used for language negotiation. This meant to be only for presenting the list of languages that user may choose from.

What? To "present the list of languages that user may choose from" you only need the `$languages` array passed as the first argument to `getPreferredLanguage` and don't need the `getPreferredLanguage` function at all. What `getPreferredLanguage` actually does is try to select a SINGLE language best matching the user preferences specified in `Accept-Languages` HTTP request header which is part of a "language negotiation" process I referred to in my original post.

As for the `ContentNegotiator::negotiateLanuguage` (which I didn't know existed tbh) - it just reimplements the code from `getPreferredLanguage` again (which is already a bad design) with additional functionality of using GET parameter for language selection. But passing the language in GET parameter is only one of the possibilities (it can be passed in cookies, as part of URL path, etc) which makes it not suited for all situations. And when `ContentNegotiator::negotiateLanuguage` is not sufficient you will have to implement your own based on `Request::getPreferredLanguage`.

**Comment by bizley** [comment]
Maybe I'm confused by the [documentaion](https://www.yiiframework.com/doc/guide/2.0/en/runtime-requests#http-headers). Anyway optional parameter there would be good but I'm not sure how can you prevent BC break without calling `Yii::$app->language` inside. As I understand you would like to correct this method and use it in `ContentNegotiator`?

Could you prepare PR for this so we can discuss the solution?

**Comment by PowerGamer1** [comment]
> Maybe I'm confused by the documentation.

Not sure what has confused you in the documentation or how that documentation contradicts anything I said so far.

> Anyway optional parameter there would be good but I'm not sure how can you prevent BC break without calling Yii::$app-language inside.

I think I pretty clearly stated in my original post that there WILL be BC break and to deal with it users will have to modify the code *calling* `getPreferredLanguage` function.

> As I understand you would like to correct this method and use it in ContentNegotiator?

As I said, at the time I was posting this issue I didn't know about existence of `ContentNegotiator`. I don't use it atm and I don't plan to use it in the future for now. I only need the fixed `getPreferredLanguage` function. Of course, ideally at the very least `ContentNegotiator` needs to be modified to call `getPreferredLanguage` too (to avoid duplication of code that does the same thing) but this is beyond the scope of my current needs.

> Could you prepare PR for this so we can discuss the solution?

If it is not obvious to you how `getPreferredLanguage` should be modified then here it is:

```PHP
	/**
	 * Returns the user-preferred language that should be used by this application.
	 * The language resolution is based on the user preferred languages and the languages
	 * supported by the application. The method will try to find the best match.
	 * @param array $languages a list of the languages supported by the application.
         * @param array $fallbackLanguage the value to return when none of the languages in $languages matched
	 * any of the user preferred languages.
	 * @return mixed the language that matched the best or $fallbackLanguage if no match was found.
	 */
	public function getPreferredLanguage(array $languages, $fallbackLanguage = null)
	{
		// The first if is removed here.
		foreach ($this->getAcceptableLanguages() as $acceptableLanguage) {
			// No changes inside this loop.
		}

		return $fallbackLanguage;
	}
```

P.S. Also, I wouldn't call this issue a bug per se, its just a bad design.

**Comment by bizley** [comment]
I'm considering bad design to be a bug. Anyway...
I'm sensing that you are somehow attacking me all the time and I'm not sure what I did to deserve this. I'll step aside from this issue to allow others to take it from here.

**Comment by PowerGamer1** [comment]
> I'm sensing that you are somehow attacking me all the time and I'm not sure what I did to deserve this. I'll step aside from this issue to allow others to take it from here.

Well, it was not my intention to attack you and you were polite but I did had to explain a lot of things that I think were stated pretty clearly and should have been obvious at the first glance to someone claiming to be a maintainer to the Yii2 engine ... (not sure if you are a maintainer but that was an impression you made on me).

**Comment by My6UoT9** [comment]
why not keep old code path?
```
/**
	 * Returns the user-preferred language that should be used by this application.
	 * The language resolution is based on the user preferred languages and the languages
	 * supported by the application. The method will try to find the best match.
	 * @param string[] $languages a list of the languages supported by the application.
         * @param string|null $fallbackLanguage the value to return when none of the languages in $languages matched
	 * any of the user preferred languages.
	 * @return string|null the language from $languages that matched the best or $fallbackLanguage if no match was found.
	 */
	public function getPreferredLanguage(array $languages, $fallbackLanguage = null)
	{
		// The first if is removed here.
		foreach ($this->getAcceptableLanguages() as $acceptableLanguage) {
			// No changes inside this loop.
		}

		return null === $fallbackLanguage ? reset($languages) :  $fallbackLanguage;
	}
```
While ugly u can pass false as second param.
Or from my point of view, implement a new function, as it seems `getPreferredLanguage` is not used otherwise in yii code.

**Comment by PowerGamer1** [comment]
> return null === $fallbackLanguage ? reset($languages) :  $fallbackLanguage;

So you pass `null` in `$fallbackLanguage` to signal that the actual fallback language is the first language in `$languages` array. And you can pass `false` if you want to find out if the match was found or not. While technically this would work this is ugly indeed while still being a BC breaking change (when called with empty first array: `getPreferredLanguage([])`).  So I see no reason to do it like this.

> Or from my point of view, implement a new function, as it seems getPreferredLanguage is not used otherwise in yii code.

That function should be used in `ContentNegotiator::negotiateLanuguage` - I don't know why it wasn't in the first place. And I think implementing a new version of a function (aka `getPreferredLanguageEx` like in WinAPI or similar) is not the Yii2 way of doing things. Personally I would reimplement existing `getPreferredLanguage` properly and since I don't think it I used all too often the BC break won't be a big deal anyway.

**Comment by My6UoT9** [comment]
Basically u pass null when u want the behaviour of the old code, thus not causing BC.

Well I did not post a complete function, for not causing BC, the original function's return value on a empty `$languages` array should be preserved, e.g. return Yii::$app->languages.

```
 /**
     * Returns the user-preferred language that should be used by this application.
     * The language resolution is based on the user preferred languages and the languages
     * supported by the application. The method will try to find the best match.
     * @param array $languages a list of the languages supported by the application. If this is empty, the current
     * application language will be returned without further processing.
     * @param string|bool|null $fallbackLanguage the value to return when none of the languages in $languages matched 
     * any of the user preferred languages. 
     * @return string|bool|null the language from $languages that matched the best or $fallbackLanguage if no null and no match was found. If $fallbackLanguage is null it will return the first avaialable language from the $language array, or if that is empty, it will return the default application language.
     */
    public function getPreferredLanguage(array $languages = [], $fallbackLanguage = null)
    {
        if (empty($languages)) {
            return null === $fallbackLanguage ?  Yii::$app->language; :  $fallbackLanguage;
        }
        foreach ($this->getAcceptableLanguages() as $acceptableLanguage) {
            $acceptableLanguage = str_replace('_', '-', strtolower($acceptableLanguage));
            foreach ($languages as $language) {
                $normalizedLanguage = str_replace('_', '-', strtolower($language));

                if (
                    $normalizedLanguage === $acceptableLanguage // en-us==en-us
                    || strpos($acceptableLanguage, $normalizedLanguage . '-') === 0 // en==en-us
                    || strpos($normalizedLanguage, $acceptableLanguage . '-') === 0 // en-us==en
                ) {
                    return $language;
                }
            }
        }

        return null === $fallbackLanguage ? reset($languages) :  $fallbackLanguage;
    }
```

**Comment by PowerGamer1** [comment]
@My6UoT9
Even the existing implementation of `getPreferredLanguage` is hard to understand at first glance and from judging just the function prototype without reading its description (i.e. you'd never guess just from the prototype that the function can return completely different things depending on the content of `$languages` and one of those things is a value from different not directly related place - `Yii::$app`). Yet you want to complicate matters even further just to keep the BC. IMO it is not a good call. The BC breaking design I propose IMO is much better in this regard.

Actually, that design can be simplified even further (documentation phrasing to be improved if needed):
```PHP
/**
  * Returns one of the languages supported by the application that matches the best a list of user-preferred
  * languages specified in Accept-Languages HTTP header of this request. If no match is found null is returned.
  * @param string[] $languages a list of the languages supported by the application.
  * @return string|null the language from $languages that matched the best or null if no match was found.
  */
public function getPreferredLanguage(array $languages)
{
  // The first if is removed here.
  foreach ($this->getAcceptableLanguages() as $acceptableLanguage) {
    // No changes inside this loop.
  }

    return null;
}
```
Which in user code would be used like: `$lang = $request->getPreferredLanguage([...]) ?? 'en';`

**Comment by My6UoT9** [comment]
@PowerGamer1 I prefer ur implementation too but think about the many people which might rely on the previous behavior.
Yet I totally agree, in 5 years people would not even know without visiting this issue, to figure out - the function is so complex only to prevent BC. 
And yii2 introduced some more difficult to solve BC, e.g. the `parent::init()` comes to my mind :)

**Comment by mikehaertl** [comment]
I want to add two remarks here:

* I think there was an agreement, that there will be no more BC breaks in Yii 2 a long time ago.
* I don't agree that the problem that the OP reported is a bug or even a misbehaviour. In my opinion it's rather that the documentation is a bit vague. If you look at the implementation it becomes quite obvious, that the whole purpose of this method was to *always* return a valid language that can be used as app language. I would even say, that you can interpret the docs in that direction.

Given that I'm against any change. If you are not happy with the behavior, it's very simple to extend your own `Response` class and add a method there that does what you want.

**Comment by PowerGamer1** [comment]
> I think there was an agreement, that there will be no more BC breaks in Yii 2 a long time ago.

If you think so take a look at https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md. BC is being broken left and right all the time.

> I don't agree that the problem that the OP reported is a bug or even a misbehaviour.

I never claimed it was a bug, I even explicitly stated that I do not think it should be labeled so.

> the whole purpose of this method was to always return a valid language that can be used as app language

The problem is this "purpose" is fulfilled badly - you can't influence the "fallback" choice this function does for you and the choice it does is surprising to say the least. Those issues are among those I wanted to improve in the first place.

> Given that I'm against any change. If you are not happy with the behavior, it's very simple to extend your own Response class and add a method there that does what you want.

Yes, and soon you will find yourself extending the engine code left and right instead of improving it for everybody's benefit, reducing your own code size, making the interface of engine classes easier to understand, behave closer to user expectations and the code of engine implementation easier to maintain.

So, as I already stated I do not consider this BC break to be anything significant due to the low probability of this function being used by a lot of people and the fact that all affected people would have used this function a single time in a single place anyway making upgrade extremely trivial.

**Comment by samdark** [comment]
That's tricky one. I've checked it in detail and decided that while the current behavior is, indeed, far from ideal, it should not be changed in Yii 2. From my experience, the method is widely used as https://github.com/vietpn/gameid/blob/6042bbd6bb82b9d36244fb674139680919012a8d/backend/components/LanguageSelector.php#L22
