### ISSUE TITLE
AssetManager appendTimestamp not working

### ISSUE THREAD

**Issue by Isitar** [yiisoft/yii2#18414]
### What steps will reproduce the problem?
asset-config:

	'app\assets\BootstrapAsset' => [
		'basePath' => '@webroot',
		'baseUrl' => '@web',
		'css' => ['css/site.min.css'],
	],

web.php

    'components' => [
    ...
		'assetManager' => [
			'appendTimestamp' => true,
			'bundles' => require(__DIR__ . '/asset-bundles.php'),
		],

### What is the expected result?
the site.min.css with the query parameter `v=time()`
`<link href="/my-project/web/css/site.min.css?v=123" rel="stylesheet">`

### What do you get instead?
no timestamp:

`<link href="/my-project/web/css/site.min.css" rel="stylesheet">`

### Additional info

this happens because of Line 495 in View.php (https://github.com/yiisoft/yii2/blob/master/framework/web/View.php#L495) it adds `@webroot` to the url. But the Url comes from the AssetManager (newly introduced `getActualAssetUrl` method (https://github.com/yiisoft/yii2/blob/c46d209b56fda9aca05a9cc7fc858ce2fe25477d/framework/web/AssetManager.php#L643))
which already includes the `@webroot` (or other baseUrl) in the url.

The error occours now because the AssetBundle calls this new Method which is the url without the timestamp. In earlier versions the timestamp was alredy included in the $url and no errors occoured.

Possible fixes:
- Either call the old `getAssetUrl` method in the AssetBundle
- Or do not append `@webroot` in front of the url.

Btw: is there a unit test checking the appendTimestamp behavior?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39
| PHP version      | 7.4
| Operating system | Windows / Linux, happens on both

**Comment by bizley** [comment]
Might be what was already reported in https://github.com/yiisoft/yii2/issues/18402

**Comment by Isitar** [comment]
yes but my issue contains the actual error to reproduce.

**Comment by nomelodic** [comment]
Я с английским не дружу, но надеюсь, что разработчики поймут. Я столкнулся с аналогичной проблемой: в версии Yii Basic 2.0.38 всё работает, с версии Yii Basic 2.0.39 перестает. PHP 7.3.

Настройки сайта, да и вообще код не меняется, т.е. делаю даунгрейд до 2.0.38 - работает, следом делаю апгрейд до 2.0.39.3 - перестает работать.

В попытках найти проблему я наткнулся на очень интересную вещь: у меня проблема проявляется только тогда, когда сайт лежит в подпапке, т.е. в `config/web.php` не пустой `baseUrl`:
```
'components' => [
    'request' => [
        'baseUrl' => '/subdomain/site',
        ...
```

Магия происходит в файле `yiisoft\yii2\web\View.php` в функции `registerFile()` в этой части кода (строки 495-497):
```
if ($appendTimestamp && Url::isRelative($url) && ($timestamp = @filemtime(Yii::getAlias('@webroot/' . ltrim($url, '/'), false))) > 0) {
    $url = $timestamp ? "$url?v=$timestamp" : $url;
}
```

В случае с подпапкой эта часть `Yii::getAlias('@webroot/' . ltrim($url, '/'), false)` возвращает путь в таком виде:
`G:/XAMPP7/htdocs/subdomain/site/web/subdomain/site/css/custom.css`

Т.е. `baseUrl` прописывается дважды: в `@webroot` и отдельно в относительном пути к файлу.

**Comment by Mister-42** [comment]
Спасибо за дополнительную информацию. Наверняка в ближайшее время это исправят :smile:

**Comment by nomelodic** [comment]
> 
> 
> Спасибо за дополнительную информацию. Наверняка в ближайшее время это исправят 😄

Будем надеяться, что нам остаётся :)

**Comment by samdark** [comment]
> Будем надеяться, что нам остаётся :)

Исправить и сделать pull request.

**Comment by Isitar** [comment]
Added a pullrequest, maybe you can have a look at it?
It works for me with sites hosted on the root-url (`localhost`) and sites hosted in subfolders (for example `localhost/my-site/something-deep`

**Comment by g-rodigy** [comment]
I have same issue

Project structure (advanced based)
````
app
-- backend
-- frontend
vendor
.htaccess
...
`````
Backend config:
````
'components' => [
	'request' => [
		'baseUrl' => '/admin',
	],
	'assetManager' => [
		'appendTimestamp' => true,
	],
	...
````
.htaccess
````
<IfModule mod_rewrite.c>
    # если /admin, то в backend
    RewriteCond %{REQUEST_URI} ^/(admin)
    RewriteRule ^admin/(.*)$ app/backend/web/$1 [L]
    RewriteCond %{REQUEST_URI} !^/backend/web/
    RewriteCond %{REQUEST_URI} ^/(admin)
    RewriteRule ^.*$ app/backend/web/index.php [L]
    ....

````

Asset Bundles or files included like registerJsFile('@web/...') has't timestamp param
Yii2 version 2.0.39.3

**Comment by Isitar** [comment]
@g-rodigy this was fixed in 2.0.40 please update and try again

**Comment by g-rodigy** [comment]
@Isitar  thanks, this works, have timestamps, but i am still getting files from assets cache when use `registerJsFile`
What is the mechanism for updating the cache correctly?
