### ISSUE TITLE
Insert pb because of INSERTED.column when non conventional column name

### ISSUE THREAD

**Issue by achretien** [yiisoft/yii2#18416]
### What steps will reproduce the problem?

Create a table with a column named 'order'.

Try to insert data in the table.

### What is the expected result?

row inserted successfully

### What do you get instead?

Error:

```
Next yii\db\Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'order'.

The SQL being executed was: 
SET NOCOUNT ON;
DECLARE @temporary_inserted TABLE ([id] int , [order] int NULL);
INSERT INTO [table_test] ([order]) OUTPUT INSERTED.id,INSERTED.order INTO @temporary_inserted VALUES (0);
SELECT * FROM @temporary_inserted
```

### Additional info

In 

https://github.com/yiisoft/yii2/blob/c46d209b56fda9aca05a9cc7fc858ce2fe25477d/framework/db/mssql/QueryBuilder.php#L490 we need to quote `$column->name`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.3
| PHP version      | 7.4.13
| Operating system | Ubuntu in docker

**Comment by alligator77** [comment]
same problem with column name group
