### ISSUE TITLE
Undefined Variable in BatchQueryResult with ModgoDB

### ISSUE THREAD

**Issue by Dimetriy** [yiisoft/yii2#18428]
Using yii2-mongodb and Yii2 2.0.39.3

### What steps will reproduce the problem?
Promo::find();
            $promo_query->where(['status' => 1, 'id' => $promo_ids]);
            foreach($promo_query->each() as $promo){
                $promos[$promo->id] = $promo;
            }

### What is the expected result?
return Model

### What do you get instead?
Undefined variable: row in
/var/www/bileter/bileter.ru/vendor/yiisoft/yii2-mongodb/src/BatchQueryResult.php:150

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38-2.0.39.3
| PHP version    | 7.4.11-7.4.13
| Operating system | Debian 10, docker from php:7.4.11-fpm

**Comment by Dimetriy** [comment]
I don`t understand how it be possible
`
$row = $this->_iterator->current();
            if ($row === null) {
                break;
            }
`
and how $row may be not undefined. But this
`
$row = $this->_iterator->current();
            if (empty($row)) {
                break;
            }
`
fix the problem

**Comment by Dimetriy** [comment]
I dont understand how it be possible 
```
$row = $this->_iterator->current();
if ($row === null) {
break;
}
```
and how $row may be not undefined. But this
```
$row = $this->_iterator->current();
if (empty($row)) {
break;
}
```
fix the problem

**Comment by farmani** [comment]
I have same issue get totally confused

**Comment by bizley** [comment]
@Dimetriy is it possible to identify the change that causes this issue?

**Comment by Dimetriy** [comment]
@bizley i dont know. I update Yii2 from 2.0.38 to latest stable version and php from 7.4.11 to 7.4.13

**Comment by bizley** [comment]
`yii2-mongodb` is 2.1.10 in both cases?

**Comment by Dimetriy** [comment]
@bizley No. Before update version 2.1.9

**Comment by bizley** [comment]
Hmm, could you downgrade `yii2-mongodb` to 2.1.9 and keep the Yii 2 with latest version to check which package is causing it?

**Comment by Dimetriy** [comment]
@bizley I downgrade yii2-mongodb to 2.1.9 and i  still get this error. Yii 2.0.39.3 + yii2-mongodb 2.1.9

**Comment by bizley** [comment]
Ok, thanks, looks like it's Yii 2 main package problem.

**Comment by Dimetriy** [comment]
@bizley New info. I downgrade Yii to 2.0.38 and still get this error on php-fpm 7.4.13. 
Now I will rebuild for an earlier version PHP. 7.4.11 and 7.4.12

**Comment by Dimetriy** [comment]
@bizley I try to downgrade php. On php 7.4.10 + Yii 2.0.39.3 all works, but from version php 7.4.1 all crashes with this error with any version Yii2

**Comment by bizley** [comment]
Oh, that is a surprise... Thank you for that investigation, it definitely helps.

Is your MongoDb PHP driver up to date?

**Comment by Dimetriy** [comment]
@bizley php mongodb drivers installing in docker container via Dockerfile and  I think they are updating.

```
FROM php:7.4.13-fpm
MAINTAINER Dmitriy Anisimov <d.an@mail.ru>

ENV TERM=linux
ENV TZ=Europe/Moscow
RUN /bin/ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update \
     && apt-get upgrade -y \
     && apt-get install -y apt-utils \
     && apt-get install -y \
        mc less vim-nox redis-tools net-tools git \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        freetds-dev \
        libpq-dev \
        libcurl4-openssl-dev \
        libxml2-dev \
        libsybdb5 \
        libxslt1-dev \
        libssl-dev \
        libzip-dev \
        locales \
        msmtp-mta \
        libonig-dev \
     && apt-get clean

RUN docker-php-ext-install -j$(nproc) \
        gettext \
        mbstring \
        opcache \
        mysqli pdo_mysql \
        pgsql pdo_pgsql \
        soap \
        sockets \
        xmlrpc xsl \
        zip \
        pcntl

RUN docker-php-ext-configure gd --with-freetype --with-jpeg\
        && docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-configure pdo_dblib --with-libdir=/lib/x86_64-linux-gnu \
        && docker-php-ext-install -j$(nproc) pdo_dblib
RUN pecl install mongodb && docker-php-ext-enable mongodb
RUN pecl install redis && docker-php-ext-enable redis
RUN pecl install mcrypt && docker-php-ext-enable mcrypt


COPY config/zzz-www.conf.ini /usr/local/etc/php/conf.d/
RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
COPY config/msmtp.conf /etc/msmtp.conf
```

**Comment by bizley** [comment]
Just to be sure check with `php -i`. Anyway I'll need help with this one.

**Comment by Dimetriy** [comment]
php 7.4.10 
```
/usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini,
mongodb
libmongoc bundled version => 1.17.0
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
libmongoc compression zstd => disabled
libmongocrypt bundled version => 1.0.4
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value
```

PHP 7.4.13
```
/usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini,
mongodb
libmongoc bundled version => 1.17.2
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
libmongoc compression zstd => disabled
libmongocrypt bundled version => 1.0.4
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value
```

**Comment by Dimetriy** [comment]
@bizley I try more options and build and i see this problem. Yii crashes in any version of PHP with latest version of MongoDB driver 1.9.0 and 1.9.0RC1. With previously driver version 1.8.9 all work with all versions of PHP.
In changelog mongodb driver i see
```
** New Feature
* [PHPC-1691] - Iterator implementation for MongoDB\Driver\Cursor
```
I update my Dockerfile with 
```
RUN pecl install mongodb-1.8.2 && docker-php-ext-enable mongodb
``` 
and problem was gone. But its a problem =)

**Comment by bizley** [comment]
Ah, yes, the same was already reported here https://github.com/yiisoft/yii2-mongodb/issues/327

**Comment by bizley** [comment]
Looks like I fixed it (at least I hope I did). Please take a look at linked issue.
