### ISSUE TITLE
How are all options requests released?

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#18421]
### What steps will reproduce the problem?
restful api
How are all options requests allowed?

```
"OPTIONS, POST"=>"login" 
"OPTIONS, POST"=>"register" 
"OPTIONS, POST"=>"xxx1" 
"OPTIONS, POST"=>"xxx2" 
"OPTIONS, POST"=>"xxx3" 
......
```

### What is the expected result?
restful api
How are all options requests allowed?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?  latest version（2.0.39.3）
| PHP version      |   7.4
| Operating system | win10 20H  x64

**Comment by bizley** [comment]
Are you using `yii\rest\UrlRule` for defining those?
