### ISSUE TITLE
\yii\db\Query()->scalar() docs - incomplete list of return types

### ISSUE THREAD

**Issue by flight643** [yiisoft/yii2#18424]
### What steps will reproduce the problem?
Execute scalar query on column of integer type, e.g:
```
        $query = new \yii\db\Query();
        $result = $query->select(new Expression('1'))->scalar();
        var_dump($result);
```
### What is the expected result?
The result type corresponds to one of the types described in the scalar() method documentation: string | null | false.
### What do you get instead?
int

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.3
| PHP version      | 7.2 
| Operating system | Linux

**Comment by samdark** [comment]
Correct. Do you want to do a pull request fixing it?

**Comment by flight643** [comment]
Yes, just made a PR
