### ISSUE TITLE
PHP Notice 'Uninitialized string offset: 0' in `yii\widgets\Menu`

### ISSUE THREAD

**Issue by stevekr** [yiisoft/yii2#18426]
Get notice`Uninitialized string offset 0 in /vendor/yiisoft/yii2/widgets/Menu.php:309` when using `''` as a url. Since PHP 8 has `E_ALL` turned on by default, it will be a problem.

### What steps will reproduce the problem?
```php
echo Menu::widget([
    'items' => [
        ['label' => 'Some Label', 'url' => ['', '#' => 'someid']]
    ]
]);
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.3
| PHP version      | 7.4, 8.0
| Operating system | Linux, MacOS

**Comment by bizley** [comment]
How come? This is a valid array syntax with offset 0. And there is the check in line 307 anyway.

**Comment by Mister-42** [comment]
308: `$route = Yii::getAlias($item['url'][0]);`
309: `$route[0]`

Isn't that a `[0]` too many?

**Comment by stevekr** [comment]
It's similar to #9754

**Comment by bizley** [comment]
Oh, right, lol, totally missed that, cheers. Yes, looks like old "using string as an array".

**Comment by My6UoT9** [comment]
Shouldn't that be, `substr($route,0,1) !== '/'`, while Yii::getAlias can return `string|bool`
```php
if (false !== $route && '/' !== substr($route,0,1) && Yii::$app->controller) {
```

**Comment by bizley** [comment]
Yes, it should. And I think we can skip `false !== $route` since with the way `getAlias()` is called it will never be `false`.
