### ISSUE TITLE
Wrong set requirments of YII

### ISSUE THREAD

**Issue by mdziczkowski** [yiisoft/yii2#18431]
I want to report that requirments for Yii are set wrongly and they dosn't allow the framework to work.

For example, in many requirments is set an unnessecary set a fixed versions or a upper limits of it.

To fix this issue, please replace in the requirments that instead of fixed ones were fixed a actual version and above ( for example: >= 1.0) or that it would allow any version ("*")

Please add into the standard above requirment, plus that the notification of "^", "~", "<", "<=" won't be used anymore to preventing that Yii stop to become usable after it's components updates, with would become excluded by the limiting the version rules

**Comment by schmunk42** [comment]
Please refer to specfic problems in eg. `composer.json` files.

**Comment by mdziczkowski** [comment]
> Please refer to specfic problems in eg. `composer.json` files.

I was attempting to download thru composer the avaliable templates (basic and advanced) and I had recieved errors, like for example the one, that my version of PHP (8.0) is above the set version limit (<8.0).

When I had downloaded it as archives, I had recieved the same errors when I tryed to download requirments thru composer

**Comment by bizley** [comment]
I've checked Yii main package and both basic and advanced templates, all require just the minimum version of PHP, not limiting the maximum one. This most probably comes from one of the additional dependencies, the question is which one. Please provide the composer message you see when trying to install dependencies.

**Comment by mdziczkowski** [comment]
I paste a dump of whole download process, that you can see the whole situation from the begining to the end: [pastebin dump](https://pastebin.com/X2D0M0CC)

**Comment by Mister-42** [comment]
So that's https://github.com/Codeception/module-yii2

**Comment by mdziczkowski** [comment]
that's too, but the main problem is the line above it

> codeception/module-yii2[1.0.0, 1.0.1, 1.1.0, 1.1.1] require php >=5.6.0 <8.0 -> your php version (8.0.0) does not satisfy that requirement.

with probably block it's download. See in this line that there someone has (unessecary) set a upper limit for PHP, with blocks Yii from working after the PHP got updated to version 8

**Comment by Mister-42** [comment]
That's what I am referring to as well. That is https://github.com/Codeception/module-yii2.

They have a [php8 version](https://github.com/Codeception/module-yii2/tree/php8) in development.

**Comment by mdziczkowski** [comment]
the question is, why there is no info on the download page that the actual version won't work with php8? if there would be one then the issue wouldn't become reported in the first place

**Comment by Mister-42** [comment]
You're still barking up the wrong tree. Please report to https://github.com/Codeception/module-yii2
Also PR https://github.com/Codeception/module-yii2/issues/17 has been created yesterday.

**Comment by samdark** [comment]
The Yii itself works well with PHP 8. Codeception does not yet.

**Comment by samdark** [comment]
Since the issue can't be solved from within Yii, closing.
