### ISSUE TITLE
setDefinitions yii\web\Request

### ISSUE THREAD

**Issue by vladimirovii** [yiisoft/yii2#18436]
```
 $container->setDefinitions([
            'yii\web\Request' => [
                'class' => 'yii\web\Request',
                'trustedHosts' => [
                    '*' => [
                        'X-Forwarded-Proto',
                    ]
                ]
            ],
        ]);
```
@see https://www.yiiframework.com/doc/api/2.0/yii-di-container#setDefinitions()-detail

### 
VarDumper::dump(\Yii::$app->request->trustedHosts);

### 
[]

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37
| PHP version      | 7.3
| Operating system | ubuntu

**Comment by My6UoT9** [comment]
its missing a closing `'`

**Comment by vladimirovii** [comment]
> its missing a closing `'`

ошибка "копи-паста"

**Comment by bizley** [comment]
Is there the same problem when you use `$container->set()`?

**Comment by vladimirovii** [comment]
> Is there the same problem when you use `$container->set()`?

yes

**Comment by bizley** [comment]
I guess you should set the component instead of its class when you call the component. Like: `$container->set('request', [/*...*/])`.

**Comment by vladimirovii** [comment]
> I guess you should set the component instead of its class when you call the component. Like: `$container->set('request', [/*...*/])`.
A class definition requires a "class" member.
Why is ершы issue closed, should I create a new issue?

**Comment by bizley** [comment]
So you didn't place `class` in the array?

**Comment by vladimirovii** [comment]
ok, I checked
if you put the code in ../config/bootstrap.php
it works
in my case i put the code in .../bootstrap/SetUp.php (class SetUp implements BootstrapInterface)
and include to main.php 'bootstrap' section ('...\bootstrap\SetUp')
and it doesn't work

**Comment by bizley** [comment]
The thing is to make sure it's configuration is set up before you call the component. Maybe in the second case it's done after.
