### ISSUE TITLE
[Yii::t + DbMessageSource] Rework

### ISSUE THREAD

**Issue by YouraHalloween** [yiisoft/yii2#18433]
Perhaps there was already such a task
### What steps will reproduce the problem?
Add a table with **language**
id
code -> ru, en, fr
locale -> ru-Ru, en-En, en-Us, fr-Fr ...
name -> Русский, English, USA, France
status -> use or not use

This table is needed to enable the user to select the language. In fact, now it needs to be hardcoded.

Change the table accordingly **message**
alter **language** on **language_id**

It is possible, but not necessary to modify the source_message table. Add category table and add **Key** to source_message table. 
Where is the **Key**, this is the **Key** for the **message** field. 
Let's say there is a long text, it is contained in the **message** field:
"_Address sold jointure wicket supported home drift. Tried rest among long elinor the. Pleased polite resolve perpetual. Terminated full green seven ought instantly belonging some uncommonly absolute rejoiced nor the. Barton supposing engaged ferrars denote secure dwelling daughter._ "
And the key to this text may be the first few words:
```php
Yii::t('frontend/main', '...Address sold jointure wicket...')
```
Let's say to indicate a key, you can frame it with three dots.

I will try to implement it myself. But it would be nice to have it in the standard delivery of the framework.
Thank you!

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.
| PHP version      | 7.4
| Operating system | Windows

**Comment by YouraHalloween** [comment]
> Perhaps there was already such a task
> 
> ### What steps will reproduce the problem?
> Add a table with **language**
> id
> code -> ru, en, fr
> locale -> ru-Ru, en-En, en-Us, fr-Fr ...
> name -> Русский, English, USA, France
> status -> use or not use
> 
> This table is needed to enable the user to select the language. Now it needs to be hardcoded.
> 
> Change the table accordingly **message**
> alter **language** on **language_id**
> 
> It is possible, but not necessary to modify the source_message table. Add category table and add **Key** to source_message table.
> Where is the **Key**, this is the **Key** for the **message** field.
> Let's say there is a long text, it is contained in the **message** field:
> "_Address sold jointure wicket supported home drift. Tried rest among long elinor the. Pleased polite resolve perpetual. Terminated full green seven ought instantly belonging some uncommonly absolute rejoiced nor the. Barton supposing engaged ferrars denote secure dwelling daughter._ "
> And the key to this text may be the first few words:
> 
> ```
> Yii::t('frontend/main', '...Address sold jointure wicket...')
> ```
> 
> Let's say to indicate a key, you can frame it with three dots.
> 
> I will try to implement it myself. But it would be nice to have it in the standard delivery of the framework.
> Thank you!
> 
> ### What is the expected result?
> ### What do you get instead?
> ### Additional info
> Q	A
> Yii version	2.0.
> PHP version	7.4
> Operating system	Windows

**Comment by YouraHalloween** [comment]
And in the **source_message** table, instead of @@ add the **status** field
status -> use or not use
Or date_delete field

**Comment by bizley** [comment]
I'm not sure what would you like to add exactly. The first table you are talking about depends in total on the business logic of your application so it should not be a part of framework. As for the "shortened" key for the message you can use it like that already if I'm not mistaken (please correct me if so) - just use some arbitrary unique string in `Yii::t()` for it and force app to translate it with [forceTranslation](https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageSource.php#L34) set to `true`.

**Comment by YouraHalloween** [comment]
forceTranslation - As far as I know it works for PhpMessageSource
For example:
```php
return  [
'NAV_ITEM_USERS' => 'Users',
    'NAV_ITEM_ROLES' => 'Roles',
    'NAV_ITEM_REF' => 'Lists',
];

Yii::t('app', 'NAV_ITEM_USERS');
```

**Comment by bizley** [comment]
`DbMessageSource` (like `PhpMessageSource`) extends `MessageSource` where this is defined.

**Comment by samdark** [comment]
As @bizley said, one part of the issue is about application logic, another is possible by forcing translation and using keys instead of source messages in `Yii::t()`.
