### ISSUE TITLE
Problem on insert with 'Desc' field name

### ISSUE THREAD

**Issue by Mohsen6558** [yiisoft/yii2#18440]
Hi
on new version of Yii 2.0.39.3 
when I want insert into SQL Server database error if have field with 'Desc' name.

![tempsnip](https://user-images.githubusercontent.com/65843645/102641014-a5477b80-4170-11eb-98cb-71d16042fd24.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by chanakafit** [comment]
**Desc** is a reserved word of MySQL for order by descending order. Rename the column name.

**Comment by Mister-42** [comment]
> **Desc** is a reserved word of MySQL for order by descending order. Rename the column name.

Your reply is not wrong, but I would like to add it is an SQL keyword. Not just MySQL, or MSSql as @mohsen6558 uses.
https://www.w3schools.com/sql/sql_ref_keywords.asp

**Comment by Mohsen6558** [comment]
I use this code for 3 years!!! and this happened on new release.
are you think we must change field name after each release?

**Comment by darkdef** [comment]
@Mohsen6558 

On you screnshots - INSERTED.AddresCode - without quotes.
You use not version 2.0.39.3 ?


In release 2.0.39.3 - i see this code, with quoted name of columns.
Please, show me file framework/db/mssql/QueryBuilder.php
lines from 482 to  492

```php
foreach ($schema->columns as $column) {
                if ($column->isComputed) {
                    continue;
                }
                $quoteColumnName = $this->db->quoteColumnName($column->name);
                $cols[] = $quoteColumnName . ' '
                    . $column->dbType
                    . (in_array($column->dbType, ['char', 'varchar', 'nchar', 'nvarchar', 'binary', 'varbinary']) ? "(MAX)" : "")
                    . ' ' . ($column->allowNull ? "NULL" : "");
                $columns[] = 'INSERTED.' . $quoteColumnName;
            }
```

**Comment by Mohsen6558** [comment]
I'm sure 
used 2.0.39.3  in project
after update I see this error on save model

**Comment by darkdef** [comment]
@Mohsen6558 please, show me lines 482 to 492 from you productiion file framework/db/mssql/QueryBuilder.php

**Comment by darkdef** [comment]
I'm test insert with field [Desc] 
and getted correct sql code, with quoted field name on section INSERTED
``` sql
SET NOCOUNT ON;DECLARE @temporary_inserted TABLE ([id] int , [stringcol] varchar(32) NULL, [Desc] varchar(32) NULL);
INSERT INTO [test_trigger] ([stringcol], [Desc]) OUTPUT INSERTED.[id],INSERTED.[stringcol],INSERTED.[Desc] INTO @temporary_inserted VALUES (:qp0, :qp1);
SELECT * FROM @temporary_inserted

**Comment by Mohsen6558** [comment]
yes you right.
I think we have problem with composer
I removed yii directory and copy it 
fixed
