### ISSUE TITLE
Fire an event rather than calling overridable callback for actions

### ISSUE THREAD

**Issue by erickskrauch** [yiisoft/yii2#18446]
Hello. I have an action, written as a separate class. It's finalized, so I can't override it. I was expected to be able to customize response via `afterRun` event, but I just found, that the current implementation doesn't fires an event, but just simply calls overridable callback:
https://github.com/yiisoft/yii2/blob/b8f495809223cf4b5b690f7fa87239402666b40d/framework/base/Action.php#L93-L95

How I expect to use it:
```php
public function actions(): array {
    return [
        'itunes-receipt' => [
            'class' => MyCustomAction::class,
            'configParam' => 'configValue',
            'on afterRun' => function(ActionEvent $event): void {
                // Modify $event->result and return it
            },
        ],
    ];
}
```

------

I can submit a PR but I see the following difficulties:
1. The signature of the `afterRun` must be changed to `afterAction(mixed $result): mixed`.
2. I can see how to trigger these events on the controller and modules, but is this necessary?

**Comment by samdark** [comment]
Action is always part of controller so `Controller::AFTER_ACTION` should serve the purpose well. Changing Action's code like that would be major BC break and I'm afraid we can not do it.
