### ISSUE TITLE
Vendor does not support Chinese fields

### ISSUE THREAD

**Issue by yoyo0926** [yiisoft/yii2#18458]
Special requirements require a database in Chinese, including Chinese and English parentheses, as well as underscores and underscores，It is no problem to use GII to generate crud，But in form, parenthesized fields appear to be blocked

Attribute name must contain word characters only.

### What steps will reproduce the problem?
1、Create a database
2、Create a data table named:项目施工_变更、签证、洽商、索赔汇总表
3、The fields are:
时间属性
地域(单位)属性
序号
合同编码
合同名称
项目代码
项目名称
标段编号
监理单位名称
变更、签证、洽商提出单位
相应变更、签证、洽商编号
变更、签证、洽商理由及主要内容
变更、签证、洽商造价
监理单位意见
建设单位意见
索赔工期
是否取得批复

### What is the expected result?

The curd generated by GII can be created, edited, etc.

### What do you get instead?

Report an error and the result is：
Invalid Argument – yii\base\InvalidArgumentException
Attribute name must contain word characters only.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36
| PHP version      | 7.2.34
| Operating system | Linux

**Comment by bizley** [comment]
While testing [this line](https://github.com/yiisoft/yii2/blob/2.0.40/framework/helpers/BaseHtml.php#L2217) with random sample from provided ones I see some of them pass and some don't. Maybe it's just the matter of adjusting the regex pattern. Could you narrow it down to the character that is causing the problem?

**Comment by bizley** [comment]
By giving it the second thought - adding non-word characters (like commas, spaces, etc.) in column (or tables) names is really weird and unnecessary. Current implementation allows Chinese characters with no problems.

If your client requires such setup I'll make a raw guess that this is for someone to look at the table data directly so maybe creating a database view for them is the solution - they can see the data labelled as they want and your application is using reasonable scheme to work with.

**Comment by yoyo0926** [comment]
Thank you for your reply, but may I suggest that you can configure whether the field name needs to be detected in the config configuration item?

**Comment by yoyo0926** [comment]
My initial positioning is the verification problem that arises in this field：地域(单位)属性，It should be due to the error caused by Chinese plus English parentheses. I have no problem trying to change English parentheses into Chinese parentheses. At present, in government agencies, there are more scenes using Chinese fields.

**Comment by bizley** [comment]
You mean to exclude certain fields from being added to generated forms? It's possible but as someone already mentioned Gii's configs are already too bloated.
But with the current implementation is the Chinese parenthesis allowed (while English one is not)?

**Comment by yoyo0926** [comment]
With regard to the Chinese field, I tried to communicate with the leader and suggested that if the name is changed into Chinese, then it is best to use Chinese from parentheses to punctuation marks. The leader means that almost all Chinese field names are uniformly stipulated, and the configuration of GII can not be added. Can you add configuration items in the config file?

**Comment by bizley** [comment]
Maybe with custom template/generator you can do it, not sure though. But the main question is still the same - do you need to have these non-word characters in field names? And if so, can you get away with this using db view?

**Comment by yoyo0926** [comment]
That seems to be the case. View also reported errors, which is too difficult. We need to correct vendor one by one in order to achieve the goal, so that vendor can not be updated.

**Comment by samdark** [comment]
It depends very much on database used:

1. Unicode in field and database names may be not supported or may have limited support.
2. `(` and `)` do have a special meaning in SQL so these should be escaped and escaping depends on database used.
3. We have a wide range of DBs supported and can't implement the support for just a single DB but leave it as is for others.

If you're willing to dig into this and implement it for all DB engines we support then you're welcome to do so and prepare a pull request. For us it's very low priority issue so we'll unlikely to invest time into implementation and testing it.
