### ISSUE TITLE
"Json::encode" different between version 2.0.38 and version 2.0.40

### ISSUE THREAD

**Issue by JimChenWYU** [yiisoft/yii2#18461]
### What steps will reproduce the problem?

build two project, example `yii2-2.0.38` and `yii2-2.0.40`

Model.php
```php
namespace App;

class Model extends \yii\base\Model implements \JsonSerializable
{
	protected $class;

	public $r;

	public function __construct(array $r)
	{
		parent::__construct([
			'r' => $r
		]);
	}

	public function jsonSerialize()
	{
		$class = $this->class;
		return array_map(function ($r) use ($class) {
			return new $class($r);
		}, $this->r);
	}
}
```

InterestTestTopicListVo.php
```php
namespace App;

class InterestTestTopicListVo extends Model
{
	protected $class = InterestTestTopicVo::class;
}
```

InterestTestTopicVo.php
```php
namespace App;

class InterestTestTopicVo extends \yii\base\Model
{
	public $id;
	public $question;
	public $answer;

	public function __construct($config = [])
	{
		parent::__construct([
			'id' => $config['id'],
			'question' => $config['question'],
			'answer' => new InterestTestTopicAnswerListVo($config['answer']),
		]);
	}
}
```

InterestTestTopicAnswerListVo.php
```php
namespace App;

class InterestTestTopicAnswerListVo extends Model
{
	protected $class = InterestTestTopicAnswerVo::class;
}
```

InterestTestTopicAnswerVo.php
```php
namespace App;

class InterestTestTopicAnswerVo extends \yii\base\Model
{
	public $no;
	public $text;
	public $score;
}
```

index.php
```php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$array = [
	[
		'id' => 1,
		'question' => 'abc',
		'answer' => [
			[
				'no' => 'A',
				'text' => 'hahaha',
				'score' => 3
			],
			[
				'no' => 'B',
				'text' => 'hahaha',
				'score' => 5
			],
		]
	],
	[
		'id' => 2,
		'question' => 'abcdefg',
		'answer' => [
			[
				'no' => 'A',
				'text' => 'hahaha',
				'score' => 3
			],
			[
				'no' => 'B',
				'text' => 'hahaha',
				'score' => 5
			],
		]
	]
];

var_dump(\yii\helpers\Json::encode(new \App\InterestTestTopicListVo($array)));
```
### What is the expected result?

in 2.0.38
`string(227) "[{"id":1,"question":"abc","answer":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]},{"id":2,"question":"abcdefg","answer":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]}]"`

in 2.0.40
`string(227) "[{"id":1,"question":"abc","answer":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]},{"id":2,"question":"abcdefg","answer":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]}]"`

### What do you get instead?

in 2.0.38
`string(227) "[{"id":1,"question":"abc","answer":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]},{"id":2,"question":"abcdefg","answer":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]}]"`

in 2.0.40
`string(239) "[{"id":1,"question":"abc","answer":{"r":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]}},{"id":2,"question":"abcdefg","answer":{"r":[{"no":"A","text":"hahaha","score":3},{"no":"B","text":"hahaha","score":5}]}}]"`

Different in attribute 'answer', in 2.0.38 is a json array but in 2.0.40 is a json object.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38, 2.0.40
| PHP version      | php7.3
| Operating system | MacOS

**Comment by bizley** [comment]
Hmm, this may be because of https://github.com/yiisoft/yii2/pull/18437

**Comment by schmunk42** [comment]
@JimChenWYU Could you try with 2.0.37 and see if it is the same result as 2.0.40?

**Comment by JimChenWYU** [comment]
@schmunk42 No, same as 2.0.38.

**Comment by bizley** [comment]
I'm out of ideas how to fix that. Some wants `Arrayable` to take precedence, some wants `JsonSerializable`. There won't be an easy way out.

@JimChenWYU some semi-temp solution for you might be to add

```php
public function toArray(array $fields = [], array $expand = [], $recursive = true)
{
    return parent::toArray($fields, $expand, false);
}
```

in `InterestTestTopicVo` class.

**Comment by JimChenWYU** [comment]
@bizley Thanks. In fact, I had solved my problem. Just In Base 'Model.php' add 
```php
public function toArray(array $fields = [], array $expand = [], $recursive = true)
{
	return $this->jsonSerialize();
}
```
But I'm not sure it's a bug or not. If it's not a bug, it maybe was told in CHANGELOG.md or UPGRADE.md.

**Comment by bizley** [comment]
Yes, it should be mentioned in the UPGRADE but somehow we neglected it when merging. I'll keep this open to remember to add it.

**Comment by JimChenWYU** [comment]
@bizley Thanks more, I think your solution is better than me. :smiley:
