### ISSUE TITLE
Error Exception: PhpMessageSource strpos(): Empty needle

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#18464]
### What steps will reproduce the problem?

Since latest version we can see an exception which did not happen before. All i can say is that we have not made any changes since 2. december at this time all those tests where passing successful (https://github.com/luyadev/luya-module-admin/actions/runs/396120340) but now they don't:

https://github.com/luyadev/luya-module-admin/runs/1649901902?check_suite_focus=true

```
yii\base\ErrorException: strpos(): Empty needle

/home/runner/work/luya-module-admin/luya-module-admin/vendor/yiisoft/yii2/i18n/PhpMessageSource.php:111
```

The following commit made changes in that file using strpos:

https://github.com/yiisoft/yii2/commit/b8f495809223cf4b5b690f7fa87239402666b40d#diff-4760f44ad00c338e01b42b4a7a6f27c802fbb6df5049b028275b6824014332f1

It seems the Problem only exists on PHP Version 7.1 - 7.4 as PHP 8.0 seems to pass successful.

### Additional info

I have not made a deep research yet, maybe the test scenarios are not built correctly. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 7.1 - 7.4, PHP 8 works
| Operating system | Ubuntu Latest

**Comment by bizley** [comment]
Looks like the previous versions were resilient to `language` being set to `null` like in your case and the update changed that, I'm very sorry about that.
