### ISSUE TITLE
restful UrlRule there are serious performance issues

### ISSUE THREAD

**Issue by haohetao** [yiisoft/yii2#18474]
### What steps will reproduce the problem?
hello world,no route
28ms 1673rps
hello world,restful
261ms 189rps
### What is the expected result?
Severe performance degradation caused by RESTful, which would put me off using RESTful
### What do you get instead?
disable restful,refactoring the url rule,use C language to implement URL rule,Provides a simler but performance-enhancing implementation of UrlRule

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 8.0.1
| Operating system | docker
| url rule number | 600+
| controllers number | 70+

**Comment by haohetao** [comment]
I ended up using GroupPurlRule to solve the problem for free, but it was still much slower than not using RESTful

**Comment by samdark** [comment]
Do you have any suggestions on how to both improve it and not break backwards compatibility?

**Comment by haohetao** [comment]
@samdark 
Use a separate URLRule for each Controller and avoid using a global URLRule

**Comment by haohetao** [comment]
Using this definition，array key lookup is much faster than rule matching
```php
<?php
return [
    'products' =>[
        'class' => 'yii\web\GroupUrlRule',
        'routePrefix' => 'product',
        'rules' => [
            [
                'class' => 'yii\rest\UrlRule',
                'controller' => 'product',
                'extraPatterns' => [
                    'tag' => 'tag',
                    'GET goods-view-save/{id}' => 'goods-view-save'
                ]
            ]
        ]
    ],
    ‘banks’  => [
        'class' => 'yii\web\GroupUrlRule',
        'routePrefix' => 'bank',
        'rules' => [
            [
                'class' => 'yii\rest\UrlRule',
                'controller' => 'bank'
            ]
        ]
    ],
];
```

**Comment by haohetao** [comment]
I'm going to create the URLRule dynamically at bootstrap based on the URL prefix

**Comment by bizley** [comment]
I was trying to improve routing process last week and was able to make it faster only in a few cases while simultaneously degrading it in all others so I gave up. The biggest problem was to keep everything BC compatible. Anyway...

Having 600+ rules in the app indicates the problem more serious than routing itself so I think @haohetao should refactor it first. But while I think this was only a showcase to point some obvious bottleneck in the framework, the later comments (suddenly somehow more specific and down to earth) made me wonder why `rest\UrlRule` is not handling the `prefix` the same way as `GroupRule`. I've read through #14996 and while agreeing that rest rule not necessarily need to follow group rule in terms of handling the prefixes, I think that parsing the request could be significantly improved if we could add simple

```php
$pathInfo = $request->getPathInfo();
if ($this->prefix !== '' && strpos($pathInfo . '/', $this->prefix . '/') !== 0) {
    return false;
}
```

at the beginning of [parseRequest()](https://github.com/yiisoft/yii2/blob/master/framework/rest/UrlRule.php#L219).

**Comment by samdark** [comment]
@bizley any drawbacks?

**Comment by bizley** [comment]
I though there might be a problem if user has GroupRule set with prefix and inner REST rule also with prefix but test shows it's not the case. I'll prepare PR.

**Comment by haohetao** [comment]
If using prefix as the route cache key can greatly improve route cache performance
