### ISSUE TITLE
xdebug 3x and base\ErrorException.php

### ISSUE THREAD

**Issue by My6UoT9** [yiisoft/yii2#18477]
### What steps will reproduce the problem?
Install latest xdebug, 3x.
Enable xdebug debugging in php.ini with:
`xdebug.mode=debug`

### What is the expected result?
Error trace, output info.

### What do you get instead?
The error msg in `vendor\yiisoft\yii2\base\ErrorException.php:50`.
Line 50 is: ` $xDebugTrace = array_slice(array_reverse(xdebug_get_function_stack()), 1, -1);`
`Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop'`
```php
   /*
     * @param \Throwable|\Exception $previous [optional]
     */
    public function __construct($message = '', $code = 0, $severity = 1, $filename = __FILE__, $lineno = __LINE__, $previous = null)
    {
        parent::__construct($message, $code, $severity, $filename, $lineno, $previous);
 
        if (function_exists('xdebug_get_function_stack')) {
            // XDebug trace can't be modified and used directly with PHP 7
            // @see https://github.com/yiisoft/yii2/pull/11723
            $xDebugTrace = array_slice(array_reverse(xdebug_get_function_stack()), 1, -1);
            $trace = [];
            foreach ($xDebugTrace as $frame) {
                if (!isset($frame['function'])) {
                    $frame['function'] = 'unknown';
                }
 
                // XDebug < 2.1.1: http://bugs.xdebug.org/view.php?id=695
                if (!isset($frame['type']) || $frame['type'] === 'static') {
                    $frame['type'] = '::';
```

### Additional info
![image](https://user-images.githubusercontent.com/22345162/104316822-5675d300-54dd-11eb-9299-9b47b46f7b03.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 7.4.3
| Operating system | win 10

**Comment by bizley** [comment]
I haven't checked it before - is it possible to detect the selected mode?

**Comment by ventoh** [comment]
Same problem here.
xdebug 3.0.1
Yii 2.0.40

**Comment by My6UoT9** [comment]
Some solution in the wild: https://github.com/rollbar/rollbar-php/blob/de772a73b87ff5abbe18d54e40a6e1f41c701d35/src/DataBuilder.php#L1110

**Comment by samdark** [comment]
The fix pointed by @My6UoT9 should be alright.
