### ISSUE TITLE
Feature request: db event names in yii\log\Logger and yii\debug\panels\DbPanel

### ISSUE THREAD

**Issue by atiline** [yiisoft/yii2#18483]
### Feature request

Hi!

I am using Doctrine ORM with Yii2.
Now I want to add SQL logging to Yii2 default Logger and Debug panel. I create own Doctrine SqlLogger and use `\Yii::beginProfile()` and `\Yii::endProfile()` to create profiling.

I want SQL events to be displayed in the default Debug panel (in DB section) and Logs.

By default, `yii\log\Logger` and `yii\debug\panels\DbPanel` have similar functions to find out if an event is from DB category or not:

`yii\log\Logger`:
```php
public function getProfileLogs()
{
    return $this->getLogMessages(Logger::LEVEL_PROFILE, ['yii\db\Command::query', 'yii\db\Command::execute']);
}
```

and

`yii\debug\panels\DbPanel`:
```php
public function getDbProfiling()
{
    $timings = $this->getProfiling(['yii\db\Command::query', 'yii\db\Command::execute']);
    $count = count($timings);
    $time = 0;
    foreach ($timings as $timing) {
        $time += $timing['duration'];
    }
    return [$count, $time];
}
```

To overwrite these methods I have to create my own classes and add them to DI container or Debug module settings.
It is not very flexible as there is no way to add any other event to this list (`['yii\db\Command::query', 'yii\db\Command::execute']`).

I suggest adding to both classes public property like

```php
/**
 * @var array of db commands names
 */
public $dbCommandsNames = ['yii\db\Command::query', 'yii\db\Command::execute'];
```

and use them in functions:

```php
public function getProfileLogs()
{
    return $this->getLogMessages(Logger::LEVEL_PROFILE, $this->dbCommandsNames);
}
```

and

```php
public function getDbProfiling()
{
    $timings = $this->getProfiling($this->dbCommandsNames);
    $count = count($timings);
    $time = 0;
    foreach ($timings as $timing) {
        $time += $timing['duration'];
    }
    return [$count, $time];
}
```

This will allow to add own event names to this list using the DI container or the Debug module settings (without creating own classes).

**Comment by samdark** [comment]
In case you don't mind having 'yii\db\Command::query', 'yii\db\Command::execute' while using Doctrine, in your own class you can trigger events with `Yii::beginProfile($rawSql, 'yii\db\Command::query');`

**Comment by atiline** [comment]
I think it is not entirely correct, since the class name of `yii\db\Command` will be used in Doctrine events (or other ORM systems).

**Comment by samdark** [comment]
Well, yeah. Just offered it as a hack :) Are you sure it's just `yii\log\Logger` and `yii\debug\panels\DbPanel`? No other places where these are hardcoded?

**Comment by atiline** [comment]
Yep, I have found only these 2 classes (in yiisoft vendor path).

**Comment by samdark** [comment]
OK. Let's try it. Do a pull request please.

**Comment by atiline** [comment]
Done. All checks have passed.
