### ISSUE TITLE
Creating URL for REST w/o GET verb does not work

### ISSUE THREAD

**Issue by karelvasicek** [yiisoft/yii2#18487]
### What steps will reproduce the problem?

Related to ("fixed" and reverted) #4829

Using `Url::to(['/v1/users/login', 'mode' => 'test'])` does not work correctly together with
```
 'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'prefix' => '<mode:[a-zA-ZäöåÅÄÖ0-9_-]*>/api',
        'pluralize' => false,
        'ruleConfig' => [
            'class' => 'yii\web\UrlRule'
            'normalizer' => [
                'class' => 'yii\web\UrlNormalizer'
                'action' => null,
            ],
        ],
        'controller' => [
            'v1/users',
        ],
        'extraPatterns' => [
            'POST login' => 'login',
        ],
    ],
],
```
API config.

It's caused by 
https://github.com/yiisoft/yii2/blob/be6fa8764272d8e797f7e3806d5c61bc8aa1ddfe/framework/rest/UrlRule.php#L208-L210
as `GET` verb is not defined for `login` action in API rules.

### What is the expected result?

`/test/api/v1/users/login` URL created. We use the URL for server-side API request using `curl`. Why is the `GET` verb considered the only one for which an URL can be created?

### What do you get instead?

`/test/v1/users/login` (as it's handled by some other URL rule).

### Additional info

```
'extraPatterns' => [
    'GET,POST login' => 'login',
],
```
settings can be used as a workaround, but we would prefer _not_ to allow `GET` for the `login` action.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.2.33
| Operating system | Fedora 30

**Comment by karelvasicek** [comment]
I updated the bug report, `What is the expected result?` section - incorrect `/test/api/v1/login` URL was used originally, correct expected URL should have been `/test/api/v1/users/login`.

**Comment by bizley** [comment]
@samdark is the reason for this stated in https://github.com/yiisoft/yii2/issues/4829#issuecomment-53610874 still valid? We have now [caching in UrlManager](https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L421).

**Comment by samdark** [comment]
@bizley [caching was added in 2015](https://github.com/yiisoft/yii2/commit/ebc089e6c26ba85642e5b32eaae017c6b637be79) so theoretically it should solve the problem but I'm not entirely sure it solves the problem in question.

**Comment by samdark** [comment]
Two benchmarks, before/after are needed to decide on it.

**Comment by bizley** [comment]
Ok, my benchmarks below:

Tested change is: [these lines](https://github.com/yiisoft/yii2/blob/2.0.40/framework/rest/UrlRule.php#L208-L210) are commented out.

issue case:
```php
$manager = new \yii\web\UrlManager(
    [
        'scriptUrl' => '',
        'enablePrettyUrl' => true,
        'rules' => [
            new \yii\rest\UrlRule(['controller' => 'user', 'extraPatterns' => ['POST login' => 'login']])
        ]
    ]
);
$result = $manager->createUrl(['user/login']);
```
| | original | changed |
|-|-|-|
| `$result ==` | `/user/login` | `/users/login` |

All times in seconds. Debug mode on.

## Positive match / single rule

UrlManager config:
```php
[
    'cache' => new \yii\caching\ArrayCache(), // or null when not cached
    'scriptUrl' => '',
    'enablePrettyUrl' => true,
    'rules' => [new \yii\rest\UrlRule(['controller' => 'user'])],
]
```
Tested pattern: `['user/view', 'id' => 1]`
Expected result: `/users/1`
Average time for 1 000 000 iterations:

| cached | original | changed |
|-|-|-|
| yes | 1.0067E-5 | 1.0368E-5 |
| no | 0.8548E-5 | 0.8680E-5 |

## Negative match / single rule

UrlManager config:
```php
[
    'cache' => new \yii\caching\ArrayCache(), // or null when not cached
    'scriptUrl' => '',
    'enablePrettyUrl' => true,
    'rules' => [new \yii\rest\UrlRule(['controller' => 'user'])],
]
```
Tested pattern: `['diff/view', 'id' => 1]`
Expected result: `/diff/view?id=1`
Average time for 1 000 000 iterations:

| cached | original | changed |
|-|-|-|
| yes | 4.7399E-6 | 4.8223E-6 |
| no | 4.9347E-6 | 4.8816E-6 |

## Positive match / multiple rules

UrlManager config:
```php
[
    'cache' => new \yii\caching\ArrayCache(), // or null when not cached
    'scriptUrl' => '',
    'enablePrettyUrl' => true,
    'rules' => $rules,
]
```
rules:
```php
$rules = [];
$chars = range('a', 'z');
foreach ($chars as $c1) {
    foreach ($chars as $c2) {
        $rules[] = new \yii\rest\UrlRule(['controller' => $c1 . $c2]);
    }
}
$rules[] = new \yii\rest\UrlRule(['controller' => 'user']);
```

Tested pattern: `['user/view', 'id' => 1]`
Expected result: `/users/1`
Average time for 100 000 iterations and 677 rules:

| cached | original | changed |
|-|-|-|
| yes | 1.0044E-5 | 1.0339E-5 |
| no | 1.0024E-5 | 1.0440E-5 |

## Negative match / multiple rules

UrlManager config:
```php
[
    'cache' => new \yii\caching\ArrayCache(), // or null when not cached
    'scriptUrl' => '',
    'enablePrettyUrl' => true,
    'rules' => $rules,
]
```
rules:
```php
$rules = [];
$chars = range('a', 'z');
foreach ($chars as $c1) {
    foreach ($chars as $c2) {
        $rules[] = new \yii\rest\UrlRule(['controller' => $c1 . $c2]);
    }
}
```

Tested pattern: `['diff/view', 'id' => 1]`
Expected result: `/diff/view?id=1`
Average time for 100 000 iterations and 676 rules:

| cached | original | changed |
|-|-|-|
| yes | 0.0012 | 0.0012 |
| no | 0.0013 | 0.0013 |

## conclusion

Slightly longer after the change but it looks negligible. To be honest it looks negligible without a cache as well so either it should not be made like that from the very beginning or this benchmark is missing something.

**Comment by samdark** [comment]
I don't see any significant difference and the difference isn't in favor of changed variant.

**Comment by bizley** [comment]
Why? The change isn't affecting the time and it allows to create URLs for verbs other than GET.

**Comment by samdark** [comment]
Yes, I mean performance difference is not a problem. We can have the change.

**Comment by karelvasicek** [comment]
Thanks @bizley and @samdark
