### ISSUE TITLE
Yii 2.0.40 db transaction commit not taking affect

### ISSUE THREAD

**Issue by bedarren** [yiisoft/yii2#18485]
### What steps will reproduce the problem?
1. Use composer upgrade to 2.0.40
2. Create a migration with name "m0001_create_table_testTran.php" with saveUp() function below:
```
public function safeUp(){
	$this->createTable('testTran', [
		'id'   => $this->primaryKey(),
		'code' => $this->string(2)->notNull(),
	]);
}
```
3. Execute command:
```php yii migrate```
### What is the expected result?
- Table testTran must be create
- m0001_create_table_testTran must be insert into `migration` table
- Must throw exception or write log
### What do you get instead?
- Table testTran not create
- m0001_create_table_testTran not insert into `migration` table
- Does not throw exception and write log
### How to resolve
- Downgrade yii from 2.0.40 to 2.0.38
- Or use `$this->db->pdo->commit();` without `$this->db->trigger(Connection::EVENT_COMMIT_TRANSACTION);`
### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      |  7.2.28 
| Operating system | Amazon Linux AMI 2017.09
| Database| Microsoft SQL Server 2016 on AWS
|SqlServer Driver| unixOCDB - ODBC Driver 13 for SQL Server

**Comment by samdark** [comment]
Try dev-master. Likely it is already fixed.

**Comment by kongoon** [comment]
I have same problem when using Yii::$app->db->beginTransaction/commit with SQL Server, data not save to database.
And files[] multiple input, it's return array to string conversation error.

**Comment by samdark** [comment]
@kongoon does master work for you?

**Comment by bizley** [comment]
@bedarren @kongoon Guys, it would be really helpful if you could tell us if dev-master works for you.

**Comment by samdark** [comment]
Closing since it's fixed in master.
