### ISSUE TITLE
Transactions are not committed using the dblib driver

### ISSUE THREAD

**Issue by BBrunekreeft** [yiisoft/yii2#18480]
### What steps will reproduce the problem?
Create database handle by using de dblib driver, using the following parameters:
```
[
    'class'               => 'yii\db\Connection',
    'dsn'                 => 'dblib:version=7.2;host=myHost;dbname=myDB',
    'username'            => 'myUsername',
    'password'            => 'myPassw0rd',
];
```

excute the following code:
```
$transaction = Yii::$app->db->beginTransaction();;
var_dump(Yii::$app->db->pdo->inTransaction());
$transaction->rollback();
```

### What is the expected result?
`true`

### What do you get instead?
`false`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 7.4
| Operating system | CentOS

Fix https://github.com/yiisoft/yii2/commit/cafe8e315cc9410e1116141b8256e22b1d1834dc broke transactions completely for database connections using the dblib driver.
There is a check for an active transaction now:https://github.com/yiisoft/yii2/blob/0781b02cc355b171e2eb544bc7897bc458ec56d8/framework/db/Transaction.php#L168
But since `inTransaction` returns false for dblib connections, no commit will be done, resulting in an automated rollback.

The reason for `inTransaction` to return false is that the transaction is not started with `beginTransaction` but with the SQL command 'START TRANSACTION` (see https://www.php.net/manual/en/pdo.intransaction.php#125087)

I've tested this by commenting out the `beginTransaction` method in de mssql pdo component: 
https://github.com/yiisoft/yii2/blob/0781b02cc355b171e2eb544bc7897bc458ec56d8/framework/db/mssql/PDO.php#L34
With this method commented out (thus using the native pdo beginTransaction), `inTransaction` correctly returns true now.
The comment at this method states "_It is necessary to override PDO's method as MSSQL PDO driver does not natively support transactions._" 
I wonder if this is still true, because the native pdo beginTransaction just seems to work fine.

**Comment by bizley** [comment]
Is the case only with dblib (regarding MSSQL) or are other drivers affected as well? Do you have maybe a solution for this?

**Comment by BBrunekreeft** [comment]
The sqlsrv doesn't have this problem.
But I don't want to use that driver because that driver doesn't support multiple uses of bind parameters with the samen name in a query.
Maybe I can create an altered PDO driver for dblib.

**Comment by BBrunekreeft** [comment]
Created a pull request.
