### ISSUE TITLE
The need of having indexBy() parameter included in select()

### ISSUE THREAD

**Issue by OndrejVasicek** [yiisoft/yii2#18499]
In the docs here https://www.yiiframework.com/doc/guide/2.0/en/db-query-builder#indexing-query-results there is a sentence

> only those column names can be used that have been part of SELECT in your query

And it's true, you need to select the column you use in `indexBy()`. BUT - it doesn't apply for `column()` method.
I accidently forget to add my `id` column to `select()` and when using the `column()` method - it still worked.
I looked into the `column()` method source code and yep, there is a specific code which includes the `indexBy()` parameter into the `select()`, which is quite handy actually.

So the question is - is this behaviour a bug? 
If it's a feature, why

- it's not documented (there is no info in https://www.yiiframework.com/doc/api/2.0/yii-db-query#column()-detail
- why it doesn't work the same with the `all()` method - it would be nice

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 7.4.13
| Operating system | Win10

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/7515

**Comment by samdark** [comment]
> why it doesn't work the same with the all() method - it would be nice

Yeah. I think so.

**Comment by OndrejVasicek** [comment]
Ok, I'd like to help, but I really don't feel like making a PR on a thing I don't fully understand.
Let's try it at least in comments - 

If I look at the commit https://github.com/yiisoft/yii2/commit/aead65f2d22e8b675cf4a1f2f50ee8ba8ef7f2a1 by qiangxue, could we just edit the all() method in similar manner?
Instead of this

```php
if ($this->emulateExecution) {
    return [];
}
$rows = $this->createCommand($db)->queryAll();
return $this->populate($rows);
```

I made small changes to this: 

```php
if ($this->emulateExecution) {
    return [];
}

if (is_array($this->select) && !in_array($this->indexBy, $this->select)) {
    $this->select[] = $this->indexBy;
}

$rows = $this->createCommand($db)->queryAll();
return $this->populate($rows);
```

I changed the condition a bit to suit a better to the spirit of all(). It works as expected on my personal test, but I can't be sure it will work in many other real-life scenarios.
Maybe you with your in depth knowledge can see if this solutions has some obvious catch.

**Comment by samdark** [comment]
Yes, I think it's a good plan.

**Comment by OndrejVasicek** [comment]
Soooo... should I make a PR with this code? Because as I said - I'm really not sure if it doesn't break anything else. 
I (maybe naively) thought you would see it's a save update.

**Comment by samdark** [comment]
Yes. Do it. PRs are in continuous integration, it will run framework test set so we'll know if it breaks something covered by one of the tests at least.

**Comment by samdark** [comment]
AR is a complex part of the framework so it's hard to be sure nothing is broken.

**Comment by OndrejVasicek** [comment]
Well, I tried my best. I did some another changes based on the current state of `Query::column()`.
It worked on my different test examples - nothing in select, duplicities in select, custom alias, etc. It worked.
As I'm writing in the PR, it this PR is accepted, we should probably add some info into docs.

**Comment by samdark** [comment]
It didn't broke any existing tests. That's great. A test for new behavior would be really great. And docs, of course.

**Comment by OndrejVasicek** [comment]
I could make a PR for changes in the docs, but my English isn't really sufficient. Someone would have to correct my typos. So is it desirable? Should I do it? 
About the test ... ups - I can't write them :( Sorry. One of my skeleton in a closet.

**Comment by samdark** [comment]
> Someone would have to correct my typos

I will do it. Way easier to correct typos than writing docs from scratch.

**Comment by OndrejVasicek** [comment]
I tried to write some docs. I wasn't sure about the PHPDoc. Info about indexBy() is scattered across three methods.
My commit is linked via the message, but what should I do to "connect" it properly to this issue? Should I do another PR? Or is it enough to commit to my original branch as I just did?
Or should I have create a completely new branch and PR? I din't find it in the guide - https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by samdark** [comment]
Ideally, a new branch and PR are preferred. Alternatively, you can PR from your fork's master. The drawback in this case is that you won't be able to do more than a single pull requset from the master branch.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#3-create-a-new-branch-for-your-feature-based-on-the-current-yii-master-branch

**Comment by OndrejVasicek** [comment]
Ok, I prepared a second branch (call it branch B) created from the original branch (call it branch A). The B brach contains every changes made in branch A.
If I create a PR v from branch B, part of it will be redundant with the first PR, wont it?

Another strange thing to me - if I look here on my original PR https://github.com/yiisoft/yii2/pull/18513/commits , the new commit with the docs draft is part od the original PR. I suppose it's because the PR is updated based on my A branch. Isn't that a better way? Because the docs aren't new issue, it's part of the original one.

So what should I do now? PR from my branch B https://github.com/OndrejVasicek/yii2/tree/18499-docs-draft ?
Or is that updated PR enough?

I'm really sorry occupying your time witch such basic stuff.

**Comment by samdark** [comment]
The PR is a branch. Push more commit to it and these will end up in the PR. One PR (if that's up to date) is enough.

**Comment by OndrejVasicek** [comment]
That makes sense this way. Very handy. 
Then this commit https://github.com/yiisoft/yii2/pull/18513/commits/e654dedbb4f1d1d1b84d2bd04830bf2ec4d7a226 adds the docs draft. Can you check it if it's ok and fix typos?

**Comment by samdark** [comment]
Alright. How about some unit tests meanwhile?

**Comment by OndrejVasicek** [comment]
I'm planning to learn the whole workflow properly, begin on one of my projects, but it’s no way a matter of following weeks ☹
I’m afraid I can’t help here further. Will do my best making my next contribution being more useful.
