### ISSUE TITLE
request support json-rpc

### ISSUE THREAD

**Issue by haohetao** [yiisoft/yii2#18491]
JSON-RPC has higher performance than RESTful, supports batch requests, and is more flexible to use

**Comment by samdark** [comment]
We're not going to implement it. There are ready to use extensions for it:

- https://github.com/studio451/yii2-json-rpc-2.0-api
- https://github.com/nizsheanez/yii2-json-rpc
- etc.

**Comment by haohetao** [comment]
Are these extensions safe to use with very few commits and stars?

**Comment by samdark** [comment]
I don't know. Try it.
