### ISSUE TITLE
int is returned as string

### ISSUE THREAD

**Issue by viplike** [yiisoft/yii2#18506]
Hello! I don't know is it a bug or a feature, maybe this info will be useful. I'm working with REST API. 
```php
// validation rule: ['int_value','integer']

// create a new instance
$model = new SomeClass();
$model->int_value = '1';
if($model->save()){
  return $model;
}

// => success, 'int_value' will be saved to db as integer
// => but using api in the same action, we will get back '1' in model attributes (as string)
```

==
it can be fixed of course on the stage of populating the value:

```php
$model->int_value = (int)Yii::$app->request->post('int_value');
```

but despite of that it can be a reason of some confusion

**Comment by bizley** [comment]
It's because `integer` validator is an alias for `number` validator with `integerOnly` option set to `true` so it only checks if value is a number, in this case integer-ish. It's not a type-checking feature.
