### ISSUE TITLE
Invalid index columns order for pgsql

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii2#18507]
https://github.com/yiisoft/yii2/blob/master/framework/db/pgsql/Schema.php#L235

This line provides invalid index column order

### What steps will reproduce the problem?
Create Table
```php
$this->createTable('{{%my_table}}',
            [
                'id' => $this->bigPrimaryKey(),
                'post_id' => $this->bigInteger()->notNull(),
                'author_id' => $this->integer()->notNull(),
                'message' => $this->json()->notNull()->defaultValue('{}'),
                'created_at' => $this->integer()->notNull(),
            ]);
```
 Create index 
```php
$this->createIndex('my_index', '{{%my_table}}', ['created_at', 'post_id']);
```
### What is the expected result?
`$this->db->getSchema()->getTableIndexes('my_table')`
should contains IndexContraint with columnNames ['created_at', 'post_id']
### What do you get instead?
IndexContraint with columnNames ['post_id', 'created_at']

pg_index.indkey contains column indexes that take part in query [5,2] for the current example , 
in pg_attribute table column attnum already contains order number in index  1 for create_id, 2 for post_id 
condition ""ia"."attnum" = ANY ("i"."indkey")" make result wrong

Valid query for me is
```php
        $sql = <<<'SQL'
SELECT
    "ic"."relname" AS "name",
    "ia"."attname" AS "column_name",
    "i"."indisunique" AS "index_is_unique",
    "i"."indisprimary" AS "index_is_primary"
FROM "pg_class" AS "tc"
INNER JOIN "pg_namespace" AS "tcns"
    ON "tcns"."oid" = "tc"."relnamespace"
INNER JOIN "pg_index" AS "i"
    ON "i"."indrelid" = "tc"."oid"
INNER JOIN "pg_class" AS "ic"
    ON "ic"."oid" = "i"."indexrelid"
INNER JOIN "pg_attribute" AS "ia"
    ON "ia"."attrelid" = "i"."indexrelid"
WHERE "tcns"."nspname" = :schemaName AND "tc"."relname" = :tableName
ORDER BY "ia"."attnum" ASC
SQL;
```
### Additional info

| Q                | A
| ---------------- | ---
| Version          |2.0.40
| PHP version      |  7.4
| Posrges | 12.3

**Comment by Insolita** [comment]
SQLFiddle with error http://sqlfiddle.com/#!17/d691a/1
SQLFiddle with valid http://sqlfiddle.com/#!17/d691a/2

Reproduced even on postgres 9.3

**Comment by bizley** [comment]
Would you be willing to provide PR fixing this?

**Comment by Insolita** [comment]
sure, ASAP
