### ISSUE TITLE
ArrayHelper::getColumn() param type should be extended

### ISSUE THREAD

**Issue by leealex** [yiisoft/yii2#18501]
https://github.com/yiisoft/yii2/blob/9c370a6ccfe959a2cd1560ff2dfe2ffadb1c02ed/framework/helpers/BaseArrayHelper.php#L523

Second parameter `$name` accepts array as well as `int|string|\Closure`.
PhpStorm inspection highlights this param when I'm passing array.

![2021-02-01-20-24-45(1)](https://user-images.githubusercontent.com/8910097/106471303-ae479e80-64cb-11eb-9a90-5d01ac84faf9.png)

**Comment by bizley** [comment]
True. Could you prepare PR for this?

**Comment by leealex** [comment]
> True. Could you prepare PR for this?

Sure )

**Comment by leealex** [comment]
PR https://github.com/yiisoft/yii2/pull/18502
