### ISSUE TITLE
[secure] yii\rest\UrlRule::$only is not effect when request using default URL parsing logic

### ISSUE THREAD

**Issue by pfdtk** [yiisoft/yii2#18503]
https://github.com/yiisoft/yii2/blob/59358f4e5bd40a99987c6e381a06684a1c8d4bd5/framework/rest/UrlRule.php#L90

For example:

```
[
        'class' => 'yii\rest\UrlRule',
        'pluralize' => false,
        'controller' => [
            'test' => 'test/index',
        ],
        'only' => ['create'],
    ]
```

in this rule, we expect that only action `create` is allowed to touch by url `POST /test`

but if the request is make with `DELETE /test/index/delete?id=1`, it will touch the action `delete` definded in ActiveController.

it`s not safe enough.

**Comment by bizley** [comment]
What do you mean by "touch" and why it's not safe?

**Comment by pfdtk** [comment]
> What do you mean by "touch" and why it's not safe?

@bizley When a controller extends `yii\rest\ActiveController`, it also extends the actions definded in `ActiveController::actions()`

we also need to defind a rest url rule like:

```
[
        'class' => 'yii\rest\UrlRule',
        'pluralize' => false,
        'controller' => [
            'test' => 'test/index',
        ],
        'only' => ['create'], // here mean only action create is allow to request
    ]
```

but if i make the request like `DELETE /test/index/delete?id=1`

it dose not match the url rule, so the request will use the default URL parsing logic

 and the request `DELETE /test/index/delete?id=1` is exactly run the action `delete` logic, not the expect only create

**Comment by bizley** [comment]
The URL rule is to create a pattern (alias) that the request will be parsed with, nothing else. It is not made for a purpose of securing the access to certain endpoints. Instead you should use [access control filters](https://www.yiiframework.com/doc/guide/2.0/en/structure-filters#access-control) or other specially made features.
In the case you are presenting here you should simply override the `actions()` method of extended controller and leave there only `create` action like:

```php
    public function actions()
    {
        return [
            'create' => [
                'class' => 'yii\rest\CreateAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
                'scenario' => $this->createScenario,
            ],
        ];
    }
```

or

```php
    public function actions()
    {
        $actions = parent::actions();

        unset($actions['index'], $actions['view'], $actions['update'], $actions['delete'], $actions['options']);

        return $actions;
    }
```
