### ISSUE TITLE
PHP 7.4 "Trying to access array offset on value of type" after update Yii 2.0.15 to 2.0.40

### ISSUE THREAD

**Issue by atmanegara** [yiisoft/yii2#18512]
I checked Yii's update history, supported PHP 7.4 in Yii 2.0.31, I did the update by deleting the vendor folder, creating a new vendor folder, and "composer update" and it worked but there was an error "Trying to access array offset on type value" on
![gambar](https://user-images.githubusercontent.com/9096711/107192336-72ab5800-6a28-11eb-839e-47d1e913c32d.png)
same error at https://github.com/yiisoft/yii2/issues/17705

 but in my project that just installed 2.0.40, no problem, 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      |  7.4
| Operating system | Centos 7

**Comment by bizley** [comment]
It's not necessary to delete vendor folder in order to update composer dependencies. Anyway... `Query`'s `one()` can return `false` when no result has been found so everything looks good to me. You should check the value of `$eukom` before trying to access it.

**Comment by atmanegara** [comment]
but in PHP version 7.2 it went well, initially the PHP 7.2 server was updated by 7.4, I also updated the old project (2.0.15) because in version 2.0.31 Yii already supports 7.4, but why is there still an error

**Comment by My6UoT9** [comment]
see here https://3v4l.org/gWiTo
accessing the boolean as array did not throw a notice before.
