### ISSUE TITLE
The $route parameter contains encoded URL in Module->createController

### ISSUE THREAD

**Issue by vkrapotkin** [yiisoft/yii2#18516]
During moving to another server I upgraded to last versions of YII2, PHP, Bootstrap, Composer etc.
My app is using the nemmo/yii2-attachments module, based on bootstrap-fileinput but after upgrade it stopped to work.
I get error 404 not found "<mysite>?r=attachments%2Ffile%2Fupload".
I investigated the reason and found that specified route goes directly to module yiisoft/yii2/base/Module.php->runAction($route) then to createController($route), which method failed.
Method's code expects that route is already decoded and %2f replaced with '/' so it can't find the proper controller.

My fix was to insert urldecode to 
yiisoft/yii2/base/Module.php
   ```
 public function createController($route)
    {
---->  $route = urldecode($route);
```
The problem is gone after that.

My php skills are not so strong, so I can imagine that the problem has another reason/solution, but it looks like in case of dynamically added controller the routing chain fails as described.

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 8.0.2
| Operating system | Windows 10x64 / Ubuntu 20.04

**Comment by bizley** [comment]
Decoding is done already in [Request](https://github.com/yiisoft/yii2/blob/2.0.40/framework/web/Request.php#L943) object. I would check first if this extension has something to do with that problem, we have not received reports of such issue regarding framework itself.

**Comment by bizley** [comment]
Closing for now. Let us know if the problem lies on our side and not on the package's.
