### ISSUE TITLE
Setting unknown property: yii\console\Response::formatters. 

### ISSUE THREAD

**Issue by Adxamjon097** [yiisoft/yii2#18517]
My console/controllers/UniversalController : 

```
<?php

namespace console\controllers;
use common\models\main\CtoCompany;
use Yii;
use yii\console\Controller;
use yii\helpers\ArrayHelper;
use yii\helpers\Console;

class UniversalController extends Controller
{

    public function actionInit(){
        $ctoCompany = CtoCompany::find()->all();

        $transaction = Yii::$app->db2->beginTransaction();
        $today = date("Y-m-d");

        try {
            echo "begin...\n";
            foreach ( $ctoCompany as $ctoCom){
                if($ctoCom->parent_id === null){
                    $ids = ArrayHelper::getColumn(CtoCompany::findAll(['parent_id' => $ctoCom->ID]), 'ID');
                }
                $ids[] = $ctoCom->ID;
                echo "+";
                $FM_ALL = \common\models\main\CtoFmList::find()->where(['in', 'CTO_COMPANY_ID', $ids])->count();

                $FM_PAYED_ALL = \common\models\main\PayLog::find()
                    ->innerJoin('FM_LIST', 'FM_LIST.ID = PAY_LOG.FM_LIST_ID')
                    ->where(['FM_LIST.CTO_COMPANY_ID' => $ids])
                    ->andWhere(['>=', 'PAY_LOG.EXPIRY_DATE', new yii\db\Expression("TO_DATE('$today', 'yyyy-mm-dd')")])->count();


                $ctoCom->FM_COUNT_ALL = $FM_ALL;
                $ctoCom->FM_COUNT_PAYED = $FM_PAYED_ALL;

                if(!$ctoCom->save()){
                    echo "error";
                }
            }
            $transaction->commit();

            echo 'saved';


        } catch (\Exception $e) {
            $transaction->rollBack();
            echo 'ERROR!';
        }

    }

}
```
```
**php yii universal/init**

and console output this errors : 
```
ERROR!Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Response::formatters'

in /var/www/adhamjon/vendor/yiisoft/yii2/base/Component.php:209

Stack trace:
#0 /var/www/adhamjon/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('formatters', Array)
#1 /var/www/adhamjon/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\console\Response), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/adhamjon/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/adhamjon/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('yii\\console\\Res...', Array, Array)
#5 /var/www/adhamjon/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->get('yii\\console\\Res...', Array, Array)
#6 /var/www/adhamjon/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#7 /var/www/adhamjon/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('response', true)
#8 /var/www/adhamjon/vendor/yiisoft/yii2/console/Application.php(228): yii\base\Module->get('response')
#9 /var/www/adhamjon/vendor/yiisoft/yii2/console/Application.php(152): yii\console\Application->getResponse()
#10 /var/www/adhamjon/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /var/www/adhamjon/yii(23): yii\base\Application->run()

```

| Yii version      | 2.0.14
| PHP version      | 7.3

**Comment by Adxamjon097** [comment]
Please help

**Comment by bizley** [comment]
Console version of Response component does not have `formatters` (but web version does). Most probably you have the configuration for web app copied in your console app when some of the options should be separated (as you can see).
