### ISSUE TITLE
DbCache doesn't working using MSSQL/SqlServer

### ISSUE THREAD

**Issue by aidanbek** [yiisoft/yii2#18526]
### What steps will reproduce the problem?
Here I used basic template https://github.com/yiisoft/yii2-app-basic
According to https://www.yiiframework.com/doc/api/2.0/yii-caching-dbcache#$cacheTable-detail:

1. Create cache table
```
create table test_cache
(
    id     char(128) not null primary key,
    expire int,
    data   varbinary(max)
)
```
I used `varbinary(max)` instead of `blob`, cause script failing with error: '`Cannot find data type blob`'.

2. In db.php:
```
return [
    'class' => Connection::class,
    'dsn' => 'sqlsrv:Server=<server>;Database=<db>',
    'username' => '<user>',
    'password' => '<pass>',
    'charset' => 'utf8',
]
```
3. In web.php:
```
'cache' => [
    'class' => yii\caching\DbCache::class,
    'cacheTable' => 'test_cache'
],
```

4. In SiteController, in method actionAbout:
```
$cache = Yii::$app->cache;

return $cache->getOrSet('testKey', function () {
    return 122;
});
```

### What is the expected result?
On page '122' and the cache table row with key 'testKey'

### What do you get instead?
On page '122' and no rows in cache table

In the app.log found this:

`2021-02-24 18:05:05 [127.0.0.1][-][-][warning][yii\caching\DbCache::setValue] Unable to update or insert cache data: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.
The SQL being executed was: MERGE [test_cache] WITH (HOLDLOCK) USING (VALUES ('testKey', 0, 'a:2:{i:0;i:14884;i:1;N;}')) AS [EXCLUDED] ([id], [expire], [data]) ON ([test_cache].[id]=[EXCLUDED].[id]) WHEN MATCHED THEN UPDATE SET [expire]=[EXCLUDED].[expire], [data]=[EXCLUDED].[data] WHEN NOT MATCHED THEN INSERT ([id], [expire], [data]) VALUES ([EXCLUDED].[id], [EXCLUDED].[expire], [EXCLUDED].[data]);
    in C:\Users\kalymbekov\Desktop\yii2-cache-test\controllers\SiteController.php:130`

### Additional info
This issue may be related to https://github.com/yiisoft/yii2/issues/16479

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version   | 7.4.14 nts x64
| Operating system | Windows 10 (1909)

**Comment by naboo** [comment]
Did you ever solve or create a workaround for this @aidanbek?

Having the exact same issue running version 2.0.40 with PHP 7.4.x.

Could using a different field type solve it?

**Comment by samdark** [comment]
That could be related with #18448. @darkdef would you please take a look?

**Comment by naboo** [comment]
Amazing work people!

I'm asking becasue I'm not familiar with the release schedule but is that milestone estimated to be released anytime soon or can we that need this fix somehow use it right now without having to hotswap files in core? :)

**Comment by samdark** [comment]
@naboo you can temporarily switch to `dev-master@dev`. Releases are usually done with a month or two interval and the last one was March 3.
