### ISSUE TITLE
Unknown column 'activeYmodels.0.ycolumn' in 'field list' when use indexBy with hasMany relation

### ISSUE THREAD

**Issue by VladislavSkripnichenko** [yiisoft/yii2#18525]
After https://github.com/yiisoft/yii2/commit/d1037db68dbd3d1fd5ee098ff802e3fe2fe4f45b

```php
$res = Xmodel::find()
            ->select([Xmodel::tableName().".*"])
            ->joinWith('activeYmodels')
->indexBy('activeYmodels.0.ycolumn')->all()
```

query throw exception 

### What is the expected result?

```php
$res = Xmodel::find()
            ->select([Xmodel::tableName().".*"])
            ->joinWith('activeYmodels')
            ->all()
$res = ArrayHelper::index($res, 'activeYmodels.0.ycolumn');
```

result like in this case

### What do you get instead?

```
DB Exception Unknown column 'activeYmodels.0.ycolumn' in 'field list
SELECT xmodel.*, activeYmodels.0.ycolumn FROM xmodel....
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.3
| Operating system | Windows 10

**Comment by bizley** [comment]
Hmm, was it working before like that at all? I suspect that column in `indexBy` was ignored and results were not indexed at all (although yes, the results were returned). If this was the case - it was wrong, and it is fixed now. If not, we need to investigate.

**Comment by samdark** [comment]
The select there isn't empty. It is basically `*` prefixed by table name.

**Comment by bizley** [comment]
I'm not saying it's empty. I'm saying that I'm wondering if previously `->indexBy('activeYmodels.0.ycolumn')` had the same result as for example `->indexBy('hsfjhsfdgjhsdfghjdsgfsjdghfjhsdgfjshd')`.

**Comment by samdark** [comment]
A unit test can tell us.

**Comment by bizley** [comment]
Yup, I can confirm the problem. #18499 needs to be corrected. I'll try to fix it.
