### ISSUE TITLE
PageCache and Cors filter conflict

### ISSUE THREAD

**Issue by haohetao** [yiisoft/yii2#18523]
### What steps will reproduce the problem?
1. enable PageCache and Cors
2. Use a different domain name to visit the website
### What is the expected result?
A CORS error occurred,the Access-Control-Allow-Origin header is wrong,alwasy is first domain.
### What do you get instead?
I want to whitelist CacheHeaders, excluding CORS headers from the cache

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 8.0.2
| Operating system | docker

**Comment by samdark** [comment]
You need to configure `variations` to include domain name.

**Comment by haohetao** [comment]
@samdark 
This can lead to excessive memory consumption and is not an ideal solution

**Comment by bizley** [comment]
No, you will have pages cached for each domain. And anything can result in DDoS, this is a way DDoS works.

**Comment by haohetao** [comment]
This will make DDoS attacks easier，as long as you change the Orgin header for each request, a new cache will be created, and if the response data size is 1MB, that means 1MB of memory will be consumed

**Comment by haohetao** [comment]
And wasting more memory is not desirable.

**Comment by samdark** [comment]
Well, you can use `$cacheHeaders` if you don't want to have more cache.

**Comment by haohetao** [comment]
@samdark 
The ```$cacheHeaders``` is not work.

**Comment by samdark** [comment]
How exactly it doesn't work?

**Comment by haohetao** [comment]
![图片](https://user-images.githubusercontent.com/4592571/108974379-5f52ea80-76c0-11eb-942e-76b3ff388a52.png)
There's no code.

**Comment by bizley** [comment]
@haohetao This is yet another issue you are posting that is a simple "how to do" question disguised as a bug report. Please ask questions at [the forum](https://forum.yiiframework.com/).

The "nonexistent feature" (as you named it) is implemented [here](https://github.com/yiisoft/yii2/blob/2.0.40/framework/filters/PageCache.php#L271) and [tested](https://github.com/yiisoft/yii2/blob/2.0.40/tests/framework/filters/PageCacheTest.php).

**Comment by haohetao** [comment]
@bizley 
thanks
