### ISSUE TITLE
AssetManager::appendTimestamp not working with non-relative web path

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#18529]
### What steps will reproduce the problem?

1. Ensure that `AssetManager::$appendTimestamp` is `true`.
2. Register an asset bundle whose `$baseUrl` is set to an absolute URL (starting with `http`/`https`) or an alias that will result in an absolute URL. (It’s important that the URL is not root-relative (starting with `/`).)

### What is the expected result?

Resulting JS/CSS URLs get timestamps appended (`?v=XXXXXX`).

### What do you get instead?

No timestamp.

### Additional info

Looks like this bug was introduced by 7ff516063de41a9f75ee7ac01c5c7c364e5b10d4.

AssetBundle::registerAssetFiles() now calls `$manager->getActualAssetUrl()` instead of `getAssetUrl()`, but the timestamp was being appended from `getAssetUrl()`.

https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/framework/web/AssetBundle.php#L156-L159

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | n/a
| Operating system | n/a

**Comment by bizley** [comment]
Hmm, we have tests for this. So it's either something wrong with the tests or there is a specific configuration used not covered there. Could you provide an example to check?

**Comment by brandonkelly** [comment]
The only two tests I can find that test `appendTimestamp` are:

- [AssetBundleTest::testRegisterFileAppendTimestamp()](https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/tests/framework/web/AssetBundleTest.php#L522) – which goes through `View::regsiterJsFile()` and `View::registerCssFile()`, which has its own timestamp logic in the event that `$options['depends']` is empty (which is the case in this test):

  https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/framework/web/View.php#L499-L502

- [AssetBundleTest::testCustomFilePublishWithTimestamp()](https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/tests/framework/web/AssetBundleTest.php#L539), which calls `AssetManager::publish()` → `AssetManager::publishFile()`, which has its own timestamp logic:

  https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/framework/web/AssetManager.php#L507-L509

Neither of those cover asset bundles registered via [AssetBundle::register()](https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/framework/web/AssetBundle.php#L123) / [View::registerAssetBundle()](https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/framework/web/View.php#L283).

**Comment by bizley** [comment]
I've prepared some additional tests (see #18530) and for me it looks like it works as expected. When asset file exists (and can be a subject of `filemtime`) timestamp is added. Otherwise it's skipped. Are we missing something here?

**Comment by brandonkelly** [comment]
@bizley Your test works because `TestSimpleExistingAsset::$baseUrl` begins with `@web`, which `ViewTest::setUpAliases()` is setting to `/`:

https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/tests/framework/web/ViewTest.php#L157

Thus, the resulting URL will pass this `Url::isRelative()` check here:

https://github.com/yiisoft/yii2/blob/ea8fe8dcc1ddff5cf0155860ada50c7feb40401d/framework/web/View.php#L495

On an actual web request, `@web` will be set to the requested scheme + host name + base URI (e.g. `https://example.com/`), so the URL will no longer be considered relative.

Easiest way to reproduce is to set `TestSimpleExistingAsset::$baseUrl` to `http://example.com/assetSources/js`.

Again, this did work as expected before 7ff516063de41a9f75ee7ac01c5c7c364e5b10d4, because `AssetBundle::registerAssetFiles()` was calling `$manager->getAssetUrl()` instead of `getActualAssetUrl()`, which was adding the timestamp _before_ the URL ever made its way to `View::registerJsFile()` / `registerCssFile()`.
