### ISSUE TITLE
Cookie::$sameSite must be set by default

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#18535]
https://github.com/yiisoft/yii2/blob/2774f3ea6c739c4bb5e24caab211172bd685b9bd/framework/web/Cookie.php#L80 It's MUST be replaces to
`public $sameSite = self::SAME_SITE_LAX;`
and fix PhpDoc in any case because `Response::sendCookies()` contain:
~~~php
if (PHP_VERSION_ID >= 70300) {
    setcookie($cookie->name, $value, [
        'expires' => $cookie->expire,
        'path' => $cookie->path,
        'domain' => $cookie->domain,
        'secure' => $cookie->secure,
        'httpOnly' => $cookie->httpOnly,
        'sameSite' => !empty($cookie->sameSite) ? $cookie->sameSite : null,
    ]);
} else {
    // Work around for setting sameSite cookie prior PHP 7.3
    // https://stackoverflow.com/questions/39750906/php-setcookie-samesite-strict/46971326#46971326
    if (!is_null($cookie->sameSite)) {
        $cookie->path .= '; samesite=' . $cookie->sameSite;
    }
    setcookie($cookie->name, $value, $cookie->expire, $cookie->path, $cookie->domain, $cookie->secure, $cookie->httpOnly);
}
~~~
Why MUST? Because browsers now generate a warning(security) and will block cookies without the `sameSite` attribute in future + we don't have tech troubles to do it.

**Comment by samdark** [comment]
Which browsers? I don't see any warnings at https://www.yiiframework.com/ in latest Chrome.

**Comment by bizley** [comment]
I can see Firefox (86, Linux) is setting `sameSite` to `None` when it's not set manually (although docs say it should be autoset to `Lax` in that case).

![Screenshot from 2021-03-01 10-43-19](https://user-images.githubusercontent.com/8577314/109479797-106bd300-7a7b-11eb-9aa5-ceffe3ce632f.png)

![image](https://user-images.githubusercontent.com/8577314/109480160-7e17ff00-7a7b-11eb-8fcf-c1add03b6879.png)

IIRC Chrome has the policy of setting `Lax` when `sameSite` is not set so it looks like having `Lax` on default should be save.

**Comment by WinterSilence** [comment]
@samdark Chrome v77.0 https://user-images.githubusercontent.com/4179018/66724429-9edea680-edeb-11e9-9e00-8c0e3a2b06fe.png
