### ISSUE TITLE
Inconsistent rounding in Formatter

### ISSUE THREAD

**Issue by wolfgangzwiauer** [yiisoft/yii2#18543]
### Description

`Yii::$app->formatter` does not round values If the `intl` extension is loaded. This can lead to unexpected results.

```php
>>> Yii::$app->formatter->asDecimal(4.65, 1);

# with `intl` loaded (locale `de_DE`)
=> "4,6"

# without `intl`
=> "4,7"
```

yii2-formatter uses PHP's [NumberFormatter](https://www.php.net/manual/en/class.numberformatter.php) if the `intl` extension is loaded, which does not seem to round the value by default.

`number_format()` is used as fallback if the `intl` extension is not loaded (which always rounds the value correctly).

This affects (at least) the follwing methods: `asDecimal`, `asInteger`, `asCurrency`,  `asPercent`

### Suggestion
Round all values to the specified `$decimals` before formatting

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1, 2.0.17
| PHP version      | 7.3, 7.4
| Operating system | Linux, Mac

**Comment by lubosdz** [comment]
I doubt this can be uniquely implemented, since introducing [rounding modes](https://www.php.net/manual/en/function.round.php) - `PHP_ROUND_HALF_UP`, `PHP_ROUND_HALF_DOWN`, ..
IMHO developer should take care of proper rounding before passing variable to formatter.

**Comment by marcovtwout** [comment]
Here's a test case to reproduce:

```php
$f = new NumberFormatter('nl', NumberFormatter::PERCENT);
var_dump($f->format($value)); // gives "63%"
var_dump(round($value, 2)); // gives "62%"
var_dump(number_format($value, 2)); // gives "62%"

$f->setAttribute(NumberFormatter::ROUNDING_MODE, NumberFormatter::ROUND_HALFUP);
var_dump($f->format($value)); // gives "62%"
```

It depends on the rounding mode, which for PHP's NumberFormatter defaults to `ROUND_HALFEVEN`. I would argue that for Yii's formatter `ROUND_HALF_UP` is a more sensible default, but use cases may vary.

You can set the rounding mode in your application config like this:

```php
'formatter' => [
    'numberFormatterOptions' => [
        NumberFormatter::ROUNDING_MODE => NumberFormatter::ROUND_HALFUP,
    ],
],
```

**Comment by samdark** [comment]
Thanks for clarification. I think that we should not change defaults.
