### ISSUE TITLE
Broken queries after 2.0.41 (Enh #18499)

### ISSUE THREAD

**Issue by sartor** [yiisoft/yii2#18549]
Working queries in version 2.0.40 became with syntax error after upgrading to 2.0.41

The problem in `$query->indexBy()` and `$query->all()`

Example:
```php
$rows = (new Query())
    ->select([
        'r.id',
        'r.value',
        'r.created_at',
    ])
    ->from(['u' => 'users'])
    ->innerJoin(['r' => 'requisites'], 'r.user_id = u.id')
    ->indexBy('id')
    ->all($this->db);
```

produces invalid query where `r.id` in select section became `u.id`

**Comment by samdark** [comment]
Yes, already fixed in master. Patch release will follow soon.

**Comment by sartor** [comment]
Thank you!
