### ISSUE TITLE
Errors caused by indexBy changes in 2.0.41

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#18545]
The changes made to address #18499 (d1037db68dbd3d1fd5ee098ff802e3fe2fe4f45b + d1037db68dbd3d1fd5ee098ff802e3fe2fe4f45b) are causing a couple problems.

First, it assumes that the `indexBy` column is going to be in the primary `from` table, which may not be the case.

Example: Take this table schema:

```
┌────────────────┐  ┌────────────────┐
│    elements    │  │ elements_sites │
├────────────────┤  ├────────────────┤
│ - id           │  │ - id           │
│                │  │ - elementId    │
│                │  │ - siteId       │
└────────────────┘  └────────────────┘
```

And this query:

```php
$result = (new Query())
    ->select(['e.id', 's.siteId'])
    ->from(['e' => '{{%elements}}'])
    ->innerJoin(['s' => '{{%elements_sites}}'], '[[s.elementId]] = [[e.id]]')
    ->indexBy('siteId')
    ->all();
```

The resulting SQL will now be:

```sql
SELECT `e`.`id`, `e`.`type`, `s`.`siteId`, `e`.`siteId`
FROM `elements` `e`
INNER JOIN `elements_sites` `s` ON `s`.`elementId` = `e`.`id`
```

Which will result in the following error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.siteId' in 'field list'
The SQL being executed was: SELECT `e`.`id`, `e`.`type`, `s`.`siteId`, `e`.`siteId`
FROM `elements` `e`
INNER JOIN `elements_sites` `s` ON `s`.`elementId` = `e`.`id`
```

Second, it assumes that the `from` and `select` properties have already been set, which may not always be the case. In Craft’s case for example, many queries aren’t fully fleshed out until within `prepare()`.

If `from` hasn’t been set by the time `all()` is called, then `Query::getTablesUsedInFrom()` will return an empty array, and the `indexBy` column will just be added without a table prefix at all, which could result in an integrity constraint violation due to an ambiguous `siteId` column.

See this failed build for a real-world example: https://travis-ci.com/github/craftcms/cms/jobs/487920954

This could possibly be mitigated if the new code was added to `Query::prepare()` rather than `all()` – but then it will be run for all queries, not just `all()`, so not sure that’s great either, and still doesn’t solve the first issue.

Seems like this whole thing is more trouble than it’s worth, for the very small amount of value #18499 was trying to bring.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41
| PHP version      | n/a
| Operating system | n/a

**Comment by ereminmdev** [comment]
Error when using column alias in indexBy().

Example:
Employee::find()->select(['fio' => 'last_name', 'id'])->indexBy('fio')->all();

Error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'employee.fio' in 'field list'
The SQL being executed was: SELECT `last_name` AS `fio`, `id`, `employee`.`fio` FROM `employee` ORDER BY `employee`.`last_name`

**Comment by bizley** [comment]
Hm, yes, overall it was not worth it. Let's reverse it.

**Comment by samdark** [comment]
Done. Please try with master. Going to tag release soon.

**Comment by brandonkelly** [comment]
Awesome, thanks! Just verified it’s solved on master.
