### ISSUE TITLE
#18499 enhancement doesn't take care string keys in select

### ISSUE THREAD

**Issue by aywan** [yiisoft/yii2#18547]
#18499 

For example I have bunch of queries like:
```php
A::find()
    ->innerJoin(['b' => 'B'], 'a.b_id = b.id')
    ->select(['key' => new Exprepression('b.key || b.id')])
    ->indexBy('key')
;
```
As a result got query:
```sql
SELECT b.key || b.id as "key", a.key
FROM "A" a INNER JOIN "B" b ON a.b_id = b.id
```
This causes `Undefined column` SQL exception, because a.key not exists.

I think it will be enough to check `indexBy` inside `yii\db\Query::all` not only by `select` items, but also as `select` keys, if `indexBy` is string.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41
| PHP version      |  7.2

**Comment by bizley** [comment]
It's already [reversed](https://github.com/yiisoft/yii2/pull/18546), new version will be released soon.
