### ISSUE TITLE
Url route with prefix not recognized in 2.0.41

### ISSUE THREAD

**Issue by petr-panek** [yiisoft/yii2#18548]
Bug related to v2.0.41.
Very probably caused by new feature "Faster request parsing for REST UrlRule with prefix handling."

### What steps will reproduce the problem?
Note:  I use it in REST API, that are setup based on Yii documentation. I will not describe here whole setup, only the important part.

1. Set rules in config/main.php 
```
'rules' => [
                [
                    'controller' => ['rules' => 'v1/app'],
                    'pluralize' => false,
                    'class' => UrlRule::class,
                    'prefix' => 'v1/shop/<shopUid:\d+>/app/<appUid:\d+>/',
                    'extraPatterns' => [
                        'OPTIONS <action:[\w\-]+>' => 'options',
                        'GET' => 'get-rules',
                        'PUT' => 'set-rules',
                    ],
                ],
//...
],

```

2. Request url  {{baseUrl}}/shop/100001/app/100002/rules

### What is the expected result?
Url is recognized and request processed.

### What do you get instead?
404 Not Found

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41
| PHP version      |  8.0.2
| Operating system | MacOS 11.2.2

**Comment by bizley** [comment]
Prefix for REST rule works now like in group rule which means that it cannot contain tokens (it should go to the pattern part). I admit that it's unforeseen BC break, I didn't expect prefix is somewhere used with tokens.

**Comment by petr-panek** [comment]
Please any documentation / recommendation how can I transfer my rule to new format?
Or wait for fix?

**Comment by bizley** [comment]
Fix incoming.

**Comment by petr-panek** [comment]
I use this logic with prefixes becuase I was not able to achieve my goal with patterns only.
Maybe I'm just not skilfull enough with Yii or there is "white spot" in documentation. Then I found somewhere this "hack" with prefixes and it works.

Please is there any way to achieve the same result without prefixes (in 2.0.41)?
(I know this is bug report, not Q&A, but it's related to context.)

**Comment by bizley** [comment]
I expected all tokens to be in patterns section so in your case using it in the prefix part was a smart way of writing less code but unfortunately I broke it. Without that you would have to copy that token part in every used pattern (for each verb). After the fix it will work like before (only downsize will be that this particular rule will not use faster parsing mechanic but it should not be a problem).

**Comment by samdark** [comment]
Fixed in master. Works for you?

**Comment by petr-panek** [comment]
How can I install "refreshed" master?
Composer still downloading not-fixed version (I checked the code in patched UrlRule.php)

**Comment by bizley** [comment]
`"yiisoft/yii2": "dev-master"`

**Comment by samdark** [comment]
> I checked the code in patched UrlRule.php

It it alright? If so, I'll tag a release.

**Comment by petr-panek** [comment]
OK. It's working now.
