### ISSUE TITLE
ActiveDataProvider for ElasticSearch broken since v2.0.41

### ISSUE THREAD

**Issue by rhertogh** [yiisoft/yii2#18557]
### What steps will reproduce the problem?

In yii2-elasticsearch run `ActiveDataProviderTest::testQuery`
This will try to instantiate a new `ActiveDataProvider` with the `db` property set to a `yii\elasticsearch\Connection`.

### What is the expected result?

A new `ActiveDataProvider` provider is instantiated.

### What do you get instead?

yii\base\InvalidConfigException: Invalid data type: yii\elasticsearch\Connection. yii\db\Connection is expected.

/home/runner/work/yii2-elasticsearch/yii2-elasticsearch/vendor/yiisoft/yii2/di/Instance.php:157
/home/runner/work/yii2-elasticsearch/yii2-elasticsearch/vendor/yiisoft/yii2/data/ActiveDataProvider.php:91
/home/runner/work/yii2-elasticsearch/yii2-elasticsearch/vendor/yiisoft/yii2/base/BaseObject.php:109
/home/runner/work/yii2-elasticsearch/yii2-elasticsearch/tests/ActiveDataProviderTest.php:57
/home/runner/work/yii2-elasticsearch/yii2-elasticsearch/vendor/phpunit/phpunit/phpunit:52

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41
| PHP version      |  - 
| Operating system | -

The `ActiveDataProvider` forces `db` to be a `yii\db\Connection` on line 91.
It looks like that #18472 (fixed in #18473, #18475 and #18476) introduced this behavior.

**Comment by rhertogh** [comment]
Test results can be found at yiisoft/yii2-elasticsearch/pull/299

**Comment by bizley** [comment]
I wonder how this wasn't the problem earlier? `ensure` was there earlier as well...

**Comment by rhertogh** [comment]
> I wonder how this wasn't the problem earlier? `ensure` was there earlier as well...

Yes, but earlier the `ensure` as only executed when the `db` property was a string. So in the case of ElasticSearch it was actually never ensured.
