### ISSUE TITLE
SqlDataProvider not replace my `ORDER BY` in `sql` property after sorting

### ISSUE THREAD

**Issue by delikates-nsk** [yiisoft/yii2#18552]
### What steps will reproduce the problem?
1. Create SqlDataProvider in SearchModel with query `SELECT "f"."rid" AS "id", "f"."ris_deleted" AS "is_deleted", "f"."ris_ready" AS "is_ready", "f"."ris_org" AS "is_org", "f"."rname" AS "name", "f"."rown_square" AS "own_square", "f"."rownerdoc_id" AS "ownerdoc_id", "f"."rownershipdoc_id", "f"."rown_percent" AS "own_percent", "f"."rown_fraction" AS "own_fraction", "f"."rattrs_list" AS "attrs_list", "f"."rstreet_id" AS "street_id", "f"."rbuilding_id" AS "building_id", "f"."rappart_id" AS "appart_id", "f"."rstreet" AS "street", "f"."rhouse" AS "house", "f"."raddress" AS "address", "f"."rappart" AS "appart", "f"."rdoc_no" AS "doc_no", "f"."rdoc_date" AS "doc_date", "f"."rdoc_org" AS "doc_org", "f"."rappart_square" AS "appart_square", "f"."rappart_num" AS "appart_num", "f"."rappart_letter" AS "appart_letter", "f"."rmeeting_name" AS "meeting_name", "f"."rmeeting_num" AS "meeting_num" FROM sh_sosedi.f_owners_list('{"user_id":4,"meeting_id":160}') f ORDER BY "f"."rappart"`
2. Use this SqlDataProvider in GridView
3. Click on column is_deleted

### What is the expected result?
1. Error in sql-query with TWO `ORDER BY` instructions - `ORDER BY "f"."rappart" ORDER BY "f"."ris_deleted" DESC LIMIT 25`

### Research
1. Error in `SqlDataProvider->prepareModels()` method
2. Do not understand why pattern `/\s+order\s+by\s+([\w\s,\.]+)$/i` not work correctly
3. When i'm add `preg_match_all($pattern, $sql, $matches); var_dump($matches); die();` after `$pattern = '/\s+order\s+by\s+([\w\s,\.]+)$/i';` line and refresh page i see empty `$matches` array

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41.1
| PHP version      | 7.4.10 
| Operating system | Ubuntu 18.04.5 LTS

**Comment by bizley** [comment]
From [the Guide](https://www.yiiframework.com/doc/api/2.0/yii-data-sqldataprovider):
> Like other data providers, SqlDataProvider also supports sorting and pagination. It does so by modifying the given $sql statement with "ORDER BY" and "LIMIT" clauses.

Which means that you must not provide `ORDER BY` and `LIMIT` in the query itself.

**Comment by bizley** [comment]
Hmm, wait. You expect error? Not sure if I understood that correctly...

**Comment by delikates-nsk** [comment]
Здравствуйте, Bizley.

Вы писали 5 марта 2021 г., 15:38:17:

> Hmm, wait. You expect error? Not sure if I understood that correctly...

1) Create searchModel
2) Use SqlDataProvider inside it
3) Point it to a sql query containing the ORDER BY
4) Pass this SqlDataProvider to Gridview
5) Click on the GridView column to sort
6) Get an error in the sql query where TWO ORDER BY will be indicated - yours and added by SqlDataProvider

For instance:
SELECT f.field1, f.field2 FROM my_func () f
I call 

-> ORDERBY (['f.field1' => SORT_ASC]) and get the SQL query

SELECT f.field1, f.field2 FROM my_func () f

I pass this request to the GridView - I click on the field2 column and I see the error 

SQLSTATE [42601]: Syntax error: 7 ERROR: syntax error (approximate position "ORDER")
f ORDER BY "f". "field1" ORDER BY "...

After which I display the entire built sql-Query and see in it

SELECT f.field1, f.field2 FROM my_func () f ORDER BY "f"."field1" ORDER BY "f"."field2"

In fact, the check in the SqlDataProvider.php file in the prepareModels () function does not work for you. 
Namely the search pattern in the following code

        if ($ sort! == false) {
            $ orders = $ sort-> getOrders ();
            $ pattern = '/\s+order\s+by\s+((\w\s,\.†+)$/i';
            if (preg_match ($ pattern, $ sql, $ matches)) {
                array_unshift ($ orders, new Expression ($ matches [1]));
                $ sql = preg_replace ($ pattern, '', $ sql);
            }
        }

And unfortunately I don't understand why. As far as my knowledge of regular expressions is enough, this pattern is correct. 


P.S sorry for bad english. if you have Russians in your team, I could explain to them in more detail in my native language
-- 
With best regards

**Comment by bizley** [comment]
Your English is perfectly understandable, no need to apologize. Indeed, the pattern here is not enough for all the identifiers.

**Comment by delikates-nsk** [comment]
As I understand it, the pattern does not work because the fields in the ORDER BY statement are enclosed in double quotes ("f". "field1"). If you add a check for them to the pattern, then everything works.

`$pattern = '/(\s+)order(\s+)by(\s+)([\w\s\",\.]+)/i';`

**Comment by bizley** [comment]
Yes, see the linked PR where this is already fixed and waiting for review.
