### ISSUE TITLE
The DbSession class always falls back to 'db' if strict mode used for sessions

### ISSUE THREAD

**Issue by Mignar** [yiisoft/yii2#18574]
### What steps will reproduce the problem?
For your projects config, set any other value than db in the session. Example:
```php
'session' => [
    'class' => 'yii\web\DbSession',
    'db' => 'dbApp2'
],
```

### What is the expected result?
The DbSession should use that specified db

### What do you get instead?
The DbSession falls back to 'db' for the database.

### Solution
I already found the issue to this.
In the function [openSession](https://github.com/yiisoft/yii2/blob/master/framework/web/DbSession.php#L103) the function call ->exists() could accept a parameter which is $db.
Currently the db is not not passed to the exists() function, therefore it always falls back to 'db' 

If you approve I'll create a PR for this.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41.1
| PHP version      |  7.4.3
| Operating system | Ubuntu 20.04

**Comment by bizley** [comment]
Go for it. I think this is the only place where that is missing.
