### ISSUE TITLE
Question about deterministic ActiveDataProvider pagination when sorting

### ISSUE THREAD

**Issue by beroso** [yiisoft/yii2#18587]
### What steps will reproduce the problem?

I suspect that the ActiveDataProvider pagination is not deterministic when using order by. 
Maybe we can add a tiebreaker criteria on Sort component. 

### Additional info

https://stackoverflow.com/questions/11904766/strange-ordering-bug-is-it-a-bug-when-ordering-two-columns-with-identical-val

https://www.percona.com/blog/2017/04/07/non-deterministic-order-select-limit/

**Comment by bizley** [comment]
Since this depends entirely on the table columns setup it should be done by a developer if needed.
