### ISSUE TITLE
ActiveForm::validateMultiple returns invalid JSON payload, yii.activeForm.js doesn't find error

### ISSUE THREAD

**Issue by czzplnm** [yiisoft/yii2#18582]
### What steps will reproduce the problem?

Create a form that uses two models and  use ajaxValidationUrl and return ActiveForm::validateMultiple($models)

Do not use clientSideValidation, the clientSideValidation messages will merge the messages from the backend and solve this problem.

This is the current yii.activeForm.js code:
 ```
 var attrHasError = function ($form, attribute, messages) {
        var $input = findInput($form, attribute),
            hasError = false;

        if (!$.isArray(messages[attribute.id])) {
            messages[attribute.id] = [];
        }

        if ($input.length) {
            hasError = messages[attribute.id].length > 0;
        }

        return hasError;
    };
```

### What is the expected result?

The resulting JSON can be applied to the front end model.

`{"addinvformmodel-inverter_label":["Name cannot be blank."],"addpanelformmodel-num_strings":["Number of Strings must be no less than 1."]}`

### What do you get instead?

Front end doesn't think there is errors, it will try to match the messages with the attributes but there attribute ID is different.

`{"addinvformmodel-0-inverter_type_id":["Model cannot be blank."],"addinvformmodel-0-inverter_manufacturer":["Manufacturer cannot be blank."],"addpanelformmodel-1-panel_type_id":["Model cannot be blank."],"addpanelformmodel-1-num_strings":["Number of Strings must be no less than 1."]}`

The ActiveForm::validateMutliple is adding this integer to the keys. Removing "[$i]" from below fixes my current code.

```
 public static function validateMultiple($models, $attributes = null)
    {
        $result = [];
        /* @var $model Model */
        foreach ($models as $i => $model) {
            $model->validate($attributes);
            foreach ($model->getErrors() as $attribute => $errors) {
                $result[Html::getInputId($model, "[$i]" . $attribute)] = $errors;
            }
        }

        return $result;
    }
```

You can see in the screen shot the front end code is using the input ID to find the error in the JSON payload, but it will not be found because the JSON contains an integer.

![Screenshot from 2021-03-26 15-43-09](https://user-images.githubusercontent.com/5511418/112700019-6fd6bc00-8e4a-11eb-95d0-2c180ac335d1.jpg)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41.1.
| PHP version      |  7.2
| Operating system | Ubuntu

**Comment by toir427** [comment]
Hello @czzplnm. Can you give an example of your code? controller and view files

**Comment by toir427** [comment]
try this [example](https://www.yiiframework.com/doc/guide/2.0/en/input-tabular-input) maybe it will be useful

**Comment by alex-code** [comment]
`ActiveForm::validateMultiple` is for tabular forms.
`ActiveForm::validate` accepts an array of models which won't have the numeric indexed results.
```php
ActiveForm::validate($model1, $model2, ...);
```

**Comment by czzplnm** [comment]
> `ActiveForm::validateMultiple` is for tabular forms.
> `ActiveForm::validate` accepts multiple models which won't have the numeric indexed results.
> 
> ```
> ActiveForm::validate($model1, $model2, ...);
> ```

Thats confusing, seems ActiveForm::validate is doing two things at once

**Comment by czzplnm** [comment]
> `ActiveForm::validateMultiple` is for tabular forms.
> `ActiveForm::validate` accepts multiple models which won't have the numeric indexed results.
> 
> ```
> ActiveForm::validate($model1, $model2, ...);
> ```

Works. Should be its own method this is messy imo

**Comment by samdark** [comment]
Yeah. Likely you're right but we can not change it at this point since it will break backwards compatibility.
