### ISSUE TITLE
Html::img with empty src returns img tag with current route as src

### ISSUE THREAD

**Issue by jseliga** [yiisoft/yii2#18583]
### What steps will reproduce the problem?

Considering current uri `/example/uri`.

```php
yii\helpers\Html::img('');
```

### What is the expected result?

```html
<img src="" alt="">
```

### What do you get instead?
```html
<img src="/example/uri" alt="">
```

As a consequence, rendered page is loaded twice (or more).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41.1
| PHP version      | 7.4.16
| Operating system |Linux 5.11.10-200.fc33.x86_64

**Comment by bizley** [comment]
Since providing image without a source is not a default thing to do, the "instead" part of your report is actually the "expected" one - the `$src` argument is [passed](https://github.com/yiisoft/yii2/blob/2.0.41.1/framework/helpers/BaseHtml.php#L451) to `Url::to()` and `''` means "use the current route". If you want to generate image tag with an empty source use i.e. `Html::tag()`.

**Comment by Mister-42** [comment]
Even more specific, the expected code above is invalid and should not be used.

https://www.w3.org/TR/2014/CR-html5-20140429/embedded-content-0.html#the-img-element

>The src attribute must be present, and must contain a valid non-empty URL potentially surrounded by spaces referencing a non-interactive, optionally animated, image resource that is neither paged nor scripted.

**Comment by jseliga** [comment]
> Since providing image without a source is not a default thing to do, the "instead" part of your report is actually the "expected" one - the `$src` argument is [passed](https://github.com/yiisoft/yii2/blob/2.0.41.1/framework/helpers/BaseHtml.php#L451) to `Url::to()` and `''` means "use the current route". If you want to generate image tag with an empty source use i.e. `Html::tag()`.

No, I don't want to generate the image tag with an empty source. In my case it happened by accident when i was generating image source dynamically ‒ yes, I should have checked the final value. But it created strange behavior with multiple page loads, which was hard to debug.

> Even more specific, the expected code above is invalid and should not be used.
> 
> https://www.w3.org/TR/2014/CR-html5-20140429/embedded-content-0.html#the-img-element
> 
> > The src attribute must be present, and must contain a valid non-empty URL potentially surrounded by spaces referencing a non-interactive, optionally animated, image resource that is neither paged nor scripted.

Then I think there should be an exception/warning, when you are trying to generate an image with empty source.

**Comment by bizley** [comment]
That's the thing - image tag is not generated with empty string in that case - it uses the current route.

**Comment by jseliga** [comment]
Yes, you are right. But conversion in this case (empty string to current route), which is done by `Url::to()`, doesn't make much sense.

**Comment by Mister-42** [comment]
You might be right about that, but changing that now is not an option. People might rely on current behaviour.

**Comment by dyonis** [comment]
I also think that multiple requests to the current page (via image src attribute) is not the right way.
It's better to leave src empty or generate some warning message.
