### ISSUE TITLE
problem composer update

### ISSUE THREAD

**Issue by toir427** [yiisoft/yii2#18584]
### What steps will reproduce the problem?
Problem is appearing while `composer update`

![image](https://user-images.githubusercontent.com/19358691/112826430-68abea00-90a6-11eb-83a1-c46265ae9bcf.png)

Maybe I'm wrong but this is a problem that happens after cloning. without any change, this problem is happening

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41
| PHP version      |  7.1
| Operating system | Windows 10

**Comment by bizley** [comment]
So you are cloning yii2 and then updating composer dependencies in it? What version of composer are you using?
I've just did exactly that and everything is ok.

**Comment by My6UoT9** [comment]
`composer update -vvv` for verbose output

**Comment by toir427** [comment]
![image](https://user-images.githubusercontent.com/19358691/112831138-f094f280-90ac-11eb-971e-fda0debd0dc6.png)

**Comment by toir427** [comment]
> So you are cloning yii2 and then updating composer dependencies in it? What version of composer are you using?
> I've just did exactly that and everything is ok.

Yes, Just clone and composer update. It also happens with php7.2

![image](https://user-images.githubusercontent.com/19358691/112831391-4c5f7b80-90ad-11eb-9603-a208eb065237.png)

**Comment by My6UoT9** [comment]
You might need to install git, so you have patch

**Comment by toir427** [comment]
> You might need to install git, so you have patch

yes maybe that's why

**Comment by WinterSilence** [comment]
@ toir427 use git-bash instead cmd

**Comment by toir427** [comment]
The above results from git-bash. I solved these problems. I hadn't installed composer but OpenServer had composer and I installed composer directly and it worked

**Comment by WinterSilence** [comment]
@toir427 https://github.com/yiisoft/yii2-gii/issues/442
