### ISSUE TITLE
Ability to turn the sorting off for a clicked column in GridView with multisort

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#18599]
When the `GridView` is configured with `Sort` object having `enableMultiSort` property set to `true` there is no way for the user to disable/turn off sorting by one of the `GridView` columns by clicking that column header.

I.e. currently each click by column header changes the sort direction like this:
asc -> desc -> asc -> desc .... 
Should be: 
asc -> desc -> off -> asc -> desc -> off ... (unless this is the last column in `GridView` currently sorted by).

**Comment by acorncom** [comment]
This may be fixed by https://github.com/yiisoft/yii2/issues/19731 ?
