### ISSUE TITLE
UrlManager with enablePrettyUrl and zero rules spams "Unable to use cache for URL manager"

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#18590]
When `UrlManager` is configured with enablePrettyUrl = true and has zero parsing rules the `UrlManager::cache` should never be accessed at all (if ruleset is empty UrlManager will never end up filling cache with anything but will try to read from it which it shouldn't and all those code places should be fixed by checking if ruleset is empty and if so there is no need to access cache at all).

Yet in such a case (`enablePrettyUrl` = true and empty ruleset) a warning "Unable to use cache for URL manager" is spammed in the logs. This is not good and should have been handled in one of the following ways:

1. Make UrlManager::cache = null by default. When enablePrettyUrl = false (which is also a default) or rulseset is empty (which it so happens is also a default) then having UrlManager::cache = null by default would be a perfectly fine and maximally optimal configuration setting.
Then, if `UrlManager::cache` is not null/false during `init()` and is not valid produce an ERROR unconditionally (alternatively do nothing and let an actual unchecked access to cache produce some PHP error exception later in the code). Yes, this is BC break, document it in the UPGRADE.md as was done in Yii2 2.0.33 !

2. At least produce a warning only when the cache is being actually accessed (which in turn should only ever happen when ruleset is not empty).

Related to https://github.com/yiisoft/yii2/issues/17933 and https://github.com/yiisoft/yii2/pull/17940.

**Comment by bizley** [comment]
Cache is also used when creating the URL and it can be done without any rules. Do you have some proposal how to reduce the spam?

**Comment by PowerGamer1** [comment]
> Cache is also used when creating the URL and it can be done without any rules.

Can you please provide an example and a place in the `UrlManager` code that illustrates the need and actual use of cache in such a case?

**Comment by bizley** [comment]
Oh, my bad, it's inner cache, not an actual cache. Yes, indeed, this seems like could be optimized.
