### ISSUE TITLE
Unable to exclude a table model attribute/column before its being saved. Forexample: column of datatype timestamp

### ISSUE THREAD

**Issue by charmy93** [yiisoft/yii2#18606]
### What steps will reproduce the problem

1. Create table user(id int not null, name varchar(10) not null, email_address varchar(10) not null, timestamp timestamp)
2. Try inserting values into above table using yii2 method
3. $model =$connection->createCommand()->insert('user', ['name' => 'xyz', 'email_address' => 'something@gmail.com'])->execute();
### What is the expected result?

1. The expected result should try to insert the value for only those 2 columns whose values are being passed forexample: just insert value for column name and email_address and exclude column timestamp from insert statement.

### What do you get instead?
Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by bizley** [comment]
This is because of the DB itself, and not because of Yii. https://stackoverflow.com/questions/10262426/sql-server-cannot-insert-an-explicit-value-into-a-timestamp-column
As I understand you could try to use `'timestamp' => new Expression('DEFAULT')`.
