### ISSUE TITLE
Ability to invalidate only the translation related cache

### ISSUE THREAD

**Issue by OndrejVasicek** [yiisoft/yii2#18605]
When using `DbMessageSource` and the `DbMessageSource::$enableCaching` is set to `true`, the system behaves helpfully and caches my translations based on the `DbMessageSource::$cachingDuration`.

But there are common real life situations, when translation is changed/added/deleted and the cache needs to be invalidate/redone before `cachingDuration` expires.
Invalidating the whole cache is overkill – you don’t want to delete your other cache entries, which could take a lot of time to recreate again.

I see two solutions, they can be even realized both, they both would be helpful.

1. Using `TagDependency` for all translation cache entries. Then invalidating only the specific translation related cache entries is a piece of cake with `TagDependency::invalidate()`.
2. Make a public method returning cache key for a specific translations (category/language combination) – now the cache key for such a set of translations is hardcoded like this:
    ```php
    $key = [
                __CLASS__,
                $category,
                $language,
            ];
    ```
    If I wanted I could easily use this code in my app and invalidate the specific cache entry, but when the Yii changes that piece of code, I’m screwed. So I believe the public method would be a cleaner solution.

Both of the solutions should be pretty easy to do and I’m ready to make a PR (without tests, sorry) if you consider my proposal helpful. 
What do you think?

**Comment by samdark** [comment]
You can set a separate cache instance via `cache` property and clean that cache alone.

**Comment by OndrejVasicek** [comment]
Let's say I set a config array to https://www.yiiframework.com/doc/api/2.0/yii-i18n-dbmessagesource#$cache-detail with a different keyPrefix. 

1. Does it mean that two cache object will be running? Isn't that bad performnace wise.
2. How can I access the cache object to invalidate the cache then? It's not in an Yii::$app->i18n anywhere.

**Comment by samdark** [comment]
> Does it mean that two cache object will be running?

Yes.

> Isn't that bad performnace wise.

Not really.

> How can I access the cache object to invalidate the cache then?

You add it as `i18nCache` component and access it as `Yii::$app->i18nCache->...`.
