### ISSUE TITLE
Detaching the AFTER_FIND behavior of afterFind

### ISSUE THREAD

**Issue by dmitrybukhonov** [yiisoft/yii2#18601]
### After initializing the method in the model
    public function afterFind() 
    {
        parent::afterFind();
        
        $this->testData = $this->test;
    }

### How is it possible to cancel initialization afterFind, when use find()?

    Article::find()->all();

### Find is expected to be used, without initializing the afterFind method

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 7.2
| Operating system | any

**Comment by dmitrybukhonov** [comment]
class Author extends ActiveRecord
    {
        public $socialNetworkData;
        
        public function afterFind() 
        {
            parent::afterFind();
            
            $this->socialNetworkData = $this->socialNetwork;
        }
        
        public function getSocialNetwork()
        {
            return$this->hasMany(AuthorSocialNetwork::class, ['author_id' => 'id']);
        }
    }

## When use find()
I want the afterFind behavior reassigned in the model not to work

    Author::find()->all();

**Comment by dmitrybukhonov** [comment]
class Author extends ActiveRecord
    {
        public $socialNetworkData;
        
        public function afterFind() 
        {
            parent::afterFind();
            
            $this->socialNetworkData = $this->socialNetwork;
        }
        
        public function getSocialNetwork()
        {
            return$this->hasMany(AuthorSocialNetwork::class, ['author_id' => 'id']);
        }
    }

## When use find()
I want the afterFind behavior reassigned in the model not to work

    Author::find()->all();

**Comment by samdark** [comment]
I see. There's no way to do it except behavior itself allows it via a flag or something.

**Comment by samdark** [comment]
You can try `$this->detachBehavior('myBehavior1')` but I don't recomment using such behavior by default at all.
