### ISSUE TITLE
[Regression] do not modify Cookie::$path on Response::sendCookies()

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#18619]
### What steps will reproduce the problem?

1. Make codeception tests that test sending form data(get CSRF token and submit form)
2. see it fail

### What is the expected result?
I should be able to test my beautiful form

### What do you get instead?
It fails because codeception does not get CSRF cookie any more since `Cookie::$sameSite` is appended to `Cookie::$path`, and now path validation fails

### Additional info
https://github.com/Codeception/module-yii2/issues/47

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      |  5.6.x, 7.0.x, 7.1.x, 7.2.x, 7.3.x
| Operating system | Docker(really does not matter)

**Comment by samdark** [comment]
Awesome 👍
