### ISSUE TITLE
Grid: Relation over 2 vias produce weird results

### ISSUE THREAD

**Issue by Commifreak** [yiisoft/yii2#18612]
### What steps will reproduce the problem?
I have a grid with a column which has a anonymous function for its `value`-field. In this field, I access a relation of the given model.

Let me start by posting my needed relations for my "given" model `projekt`:

```php
	public function getKooperationen() {
		return $this->hasMany( Kooperation::class, [ 'projekt_id' => 'id' ] );
	}

	public function getKooperationsPartner() {
		return $this->hasMany( Kooperationspartner::class, [ 'kooperation_id' => 'id' ] )->via( 'kooperationen' );
	}

	public function getExterneKooperationsPartner() {
		return $this->hasMany( MasterOrganisation::class, [ 'id' => 'organisation_id' ] )->via( 'kooperationsPartner' );
	}
```

So, the source Model is `Projekt` which has these relation definitions. When I call `externeKooperationsPartner` is will load this via `kooperationsPartner` and that will load via `kooperationen`.

So, the function for the column looks as follows:

```php
                  'value' => function($model) {
                    $out = [];
                    $partners = $model->externeKooperationsPartner;
                          foreach ( $partners as $partner ) {
                             $out[] = $partner->name;
                    }
                    return implode("<br />", $out);
                 },

```

So, we assume, we have 3 projekt results for that whole grid. All of them have a specific `MasterOrganisation::class` but it is not always displayed!

The results looks like this:

![grafik](https://user-images.githubusercontent.com/87267/115822948-b4338880-a405-11eb-8b28-7867d841534a.png)

But this is not true! Example: `Company 19` is in ALL of these three results available! But `externeKooperationsPartner` offers no more data in this round.

If I go a level higher and use `kooperationsPartner` instead of `externeKooperationsPartner`:

```php
			        'value' => function($model) {
				        $out = [];
				        $partners = $model->kooperationsPartner;
				        foreach ( $partners as $partner ) {
					        if($partner->organisation) {
						        $out[] = $partner->organisation->name;
					        }
				        }
				        return implode("<br />", $out);
			        },
```

I get:

![grafik](https://user-images.githubusercontent.com/87267/115823547-c6fa8d00-a406-11eb-9c3e-1c0d5c97d207.png)

which is the actual case (regardless of the sense that some are assigned multiple times :) ).
(`if($partner->organisation) {` = The ->organisation is a relation from the `kooperationsPartner` model which points to `MasterOrganisation::class`)

Am I using it wrong/Bad practice? DId I miss something?

Thanks in advance

### What is the expected result?
The same result, but without my extra `if($partner->organisation) {`

### What do you get instead?
See above

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41.1
| PHP version      | 7.4.16
| Operating system | Ubuntu 18.04

**Comment by bizley** [comment]
I guess this is because of the nature of this relation and the way Yii populates it as models. You could verify it by calling raw SQL built from the given methods and see the results. Most probably you will get duplicates, and these are removed when data is being populated as a model. The solution would be to craft the queries to meet the expectations like maybe adding specific `on` conditions or maybe just calling the relation tables directly instead of using `via`. Anyway, unless you can find something not working in Yii, we cannot really help here. I'm closing it, feel free to write here if anything new develops.
