### ISSUE TITLE
`BaseActiveRecord`: method `primaryKey()` is `static` and defined in `ActiveRecord`

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#18613]
need replace `$this->primaryKey();` and `static::primaryKey();` to `array_keys($this->primaryKey)` or move that's method to `BaseActiveRecord`

https://github.com/yiisoft/yii2/blob/ad2ce6ad4f6a17bde1d30a0fa44926df9ee62fdf/framework/db/ActiveRecord.php#L457
https://github.com/yiisoft/yii2/blob/ad2ce6ad4f6a17bde1d30a0fa44926df9ee62fdf/framework/db/BaseActiveRecord.php#L1155
https://github.com/yiisoft/yii2/blob/ad2ce6ad4f6a17bde1d30a0fa44926df9ee62fdf/framework/db/BaseActiveRecord.php#L1596

**Comment by WinterSilence** [comment]
@samdark `BaseActiveRecord::primaryKey();` not exists, we must define `abstract public function primaryKey();`

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/pull/18614#issuecomment-826293939
