### ISSUE TITLE
broken link docs (uk)

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2#18627]
### Additional info
https://github.com/yiisoft/yii2/blob/master/docs/guide-uk/intro-yii.md#%D0%BF%D0%BE%D1%80%D1%96%D0%B2%D0%BD%D1%8F%D0%BD%D0%BD%D1%8F-yii-%D0%B7-%D1%96%D0%BD%D1%88%D0%B8%D0%BC%D0%B8-%D1%84%D1%80%D0%B5%D0%B9%D0%BC%D0%B2%D0%BE%D1%80%D0%BA%D0%B0%D0%BC%D0%B8

**Comment by bizley** [comment]
What exactly is broken?

**Comment by Arhell** [comment]
> What exactly is broken?
Leads to the wrong page
I will correct soon

**Comment by Arhell** [comment]
@bizley  link fixed https://github.com/yiisoft/yii2/pull/18630
