### ISSUE TITLE
different code for English and Russian (and other) docs

### ISSUE THREAD

**Issue by romanown** [yiisoft/yii2#18632]
https://www.yiiframework.com/doc/guide/2.0/en/tutorial-yii-integration#using-both-yii2-yii1

```
spl_autoload_unregister(array('YiiBase','autoload'));
spl_autoload_register(array('Yii','autoload'));

Yii::$classMap = include($yii2path . '/classes.php');
// register Yii 2 autoloader via Yii 1
Yii::registerAutoloader(['yii\BaseYii', 'autoload']);
```

https://www.yiiframework.com/doc/guide/2.0/ru/tutorial-yii-integration#using-both-yii2-yii1

```
Yii::$classMap = include($yii2path . '/classes.php');
// регистрация автозагрузчика Yii 2 через Yii 1
Yii::registerAutoloader(['Yii', 'autoload']);
```
different code for manн languages
различается код для многих языков

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Yeah. Translation is a bit outdated. Need someone to take care of it since I'm a bit busy with Yii3.

**Comment by romanown** [comment]
I am ready to make corrections to all the options if you specify which one is correct.

**Comment by samdark** [comment]
English is always the correct source.

**Comment by romanown** [comment]
thanks. i tested the Russian variant and it work. not need correct.
