### ISSUE TITLE
Http Basic Auth doesn't work

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/yii2#18648]
### What steps will reproduce the problem?
Http Basic Auth doesn't work if the server uses a special configuration where PHP is not loaded as module...

References
#13654
#18315

### Additional info
In the yii\web\Request::getAuthCredentials()
```
/*
 * Apache with php-cgi does not pass HTTP Basic authentication to PHP by default.
 * To make it work, add the following line to to your .htaccess file:
 *
 * RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
 */
$auth_token = $this->getHeaders()->get('HTTP_AUTHORIZATION') ?: $this->getHeaders()->get('REDIRECT_HTTP_AUTHORIZATION');
```
**The problem is that HTTP_AUTHORIZATION and REDIRECT_HTTP_AUTHORIZATION are not HEADERS, but environment variables!** 

In the yii\web\Request::getHeaders() HTTP headers parsed by
`getallheaders()`
or
`http_get_request_headers()`
or
custom expression `(strncmp($name, 'HTTP_', 5) === 0)` - will not return REDIRECT_HTTP_AUTHORIZATION as a header.

In the tests/framework/web/RequestTest.php
```
testHttpAuthCredentialsFromHttpAuthorizationHeader()
$request->getHeaders()->set('HTTP_AUTHORIZATION', 'Basic ' . $secret);
$request->getHeaders()->set('REDIRECT_HTTP_AUTHORIZATION', 'Basic ' . $secret);
```
It's not correct to set headers! You must set ENV variables!

### Solution
1. Get auth data from 'Authorization' header not from env vars, replace
```
$auth_token = $this->getHeaders()->get('HTTP_AUTHORIZATION') ?: $this->getHeaders()->get('REDIRECT_HTTP_AUTHORIZATION');
```
with
`$auth_token = $this->getHeaders()->get('Authorization');`

2. Update custom headers parser and add expression for 'REDIRECT_HTTP_' prefix:
`(strncmp($name, 'HTTP_', 5) === 0 || strncmp($name, 'REDIRECT_HTTP_', 14) === 0)`

**Comment by bizley** [comment]
If I understand that correctly this requires correcting [this part](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L375) to allow `REDIRECT_HTTP_AUTHORIZATION` and then updating the tests to properly set the $_SERVER variables, right?

**Comment by olegbaturin** [comment]
> If I understand that correctly this requires correcting [this part](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L375) to allow `REDIRECT_HTTP_AUTHORIZATION` and then updating the tests to properly set the $_SERVER variables, right?

yes

And [this](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L1330) must be replaced with 
`$auth_token = $this->getHeaders()->get('Authorization');`
because [here](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L376) header will became 'authorization' and not 'HTTP_AUTHORIZATION' or 'REDIRECT_HTTP_AUTHORIZATION'.

**Comment by olegbaturin** [comment]
And don't forget skip 14 (not 5) symbols for 'REDIRECT_HTTP_' prefix [here](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L376)

**Comment by bizley** [comment]
Ok, we could see the PR fixing this. Would you like to contribute?

**Comment by olegbaturin** [comment]
> Ok, we could see the PR fixing this. Would you like to contribute?

Next week be ok?

**Comment by bizley** [comment]
Any time is fine 👍🏻
