### ISSUE TITLE
broken docs/guide-pl/intro-yii.md team link

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2#18644]
https://www.yiiframework.com/doc/guide/2.0/pl/intro-yii#jak-wyglada-porownanie-yii-z-innymi-frameworkami
![1](https://user-images.githubusercontent.com/26163841/117878007-f1c15e00-b2ad-11eb-8b0b-0161729fdfbd.png)

**Comment by samdark** [comment]
Syntax should be \[title\]\(link\).
