### ISSUE TITLE
Dynamic create object for action injection

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#18668]
I have a suggestion

I create an issue before #18566

At the beginning I used Laravel Route Model binding as an example

I think if I need to implement a lot of Route Model Binding injection, I must write a lot of definitions

Is it possible to provide a DynamicInjectionInterface for dynamically creating objects to reduce writing definitions?

The following code is my idea , So I don't need write defintion code in config file.

```php
interface DynamicInjectionInterface  {
    public static function buildInjectionInstance();
}

class Book extend ActiveRecord implement DynamicInjectionInterface   {
    public static function buildInjectionInstance(Request $request){
        return self::findOne($request->getParam('id'));
    }
}
```

**Comment by samdark** [comment]
Would you please elaborate? Can't get the idea :(
