### ISSUE TITLE
secondary urlManager creating wrong url when showScriptName is true

### ISSUE THREAD

**Issue by e-frank** [yiisoft/yii2#18665]
app on "myapp.com", 
myapp\config\main.php:

        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName'  => false,
            ...
        ],
        'urlManagerFrontend' => [
            'class'           => 'yii\web\urlManager',
            'baseUrl'         => 'https://example.com',
            'enablePrettyUrl' => true,
            'showScriptName'  => true, // <-- here it is
            ...
        ],

Yii::$app->urlManagerFrontend->baseUrl:
`https://example.com`

`Yii::$app->urlManagerFrontend->createAbsoluteUrl(['xxx/view']);`

expected:
`https://example.com/xxx/view`

output:
`https://myapp.com/xxx/view`

workaround:
setting `showScriptName` to `false` fixes the links.

remarks:
i wanted to generate links in mails generated from backend app "myapp.com" to public frontend "example.com"

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | 7.3.28, 8.0.6
| Operating system | W10

**Comment by bizley** [comment]
With `showScriptName` set to `true` you must set `scriptUrl` or `hostInfo` because `baseUrl` is omitted then.
