### ISSUE TITLE
Migration templates do not work with namespaced migrations when migration name does not include namespace

### ISSUE THREAD

**Issue by antichris** [yiisoft/yii2#18660]
This is an almost-duplicate of #17437.

## Repro

1. Create a simple namespaced console application.

    - <details><summary>composer.json</summary>

        ```json
        {
            "name": "foo/bar",
            "require": {
                "yiisoft/yii2": "2.0.42.1"
            },
            "autoload": {
                "psr-4": {
                    "foo\\bar\\": "."
                }
            },
            "repositories": [
                {
                    "type": "composer",
                    "url": "https://asset-packagist.org"
                }
            ]
        }
        ```

        </details>
    - <details><summary>main.php</summary>

        ```php
        #!/usr/bin/env php
        <?php

        use yii\console\controllers\MigrateController;
        use yii\db\Connection;

        require_once __DIR__ . '/vendor/autoload.php';
        require_once __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

        $application = new yii\console\Application([
            'id' => 'foo-bar',
            'basePath' => __DIR__,
            'aliases' => [
                '@foo/bar' => '@app',
            ],
            'components' => [
                'db' => [
                    'class' => Connection::class,
                    'dsn' => "sqlite:foo-bar.db",
                    'charset' => 'utf8',
                ],
            ],
            'controllerMap' => [
                'migrate' => [
                    'class' => MigrateController::class,
                    'migrationNamespaces' => [
                        'foo\bar',
                    ],
                    'migrationPath' => null,
                ],
            ],
        ]);
        exit($application->run());
        ```

        </details>

2. Create a migration that ought to generate from a template, e.g. create table:

    ```sh
    php main.php migrate/create --interactive=0 CreateQuxTable
    ```

### What would you expected to happen?

<details><summary>A migration is generated using the appropriate template (e.g. <code>views/createTableMigration.php</code>).</summary>

```php
<?php

namespace foo\bar;

use yii\db\Migration;

/**
 * Handles the creation of table `{{%qux}}`.
 */
class M210517181920CreateQuxTable extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%qux}}', [
            'id' => $this->primaryKey(),
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%qux}}');
    }
}
```

</details>

### What do you get instead?

<details><summary>Migration is generated using the plain, generic <code>views/migration.php</code> template.</summary>

```php
<?php

namespace foo\bar;

use yii\db\Migration;

/**
 * Class M210517181920CreateQuxTable
 */
class M210517181920CreateQuxTable extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "M210517181920CreateQuxTable cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "M210517181920CreateQuxTable cannot be reverted.\n";

        return false;
    }
    */
}
```

</details>

### Cause

https://github.com/yiisoft/yii2/blob/b33f1a7ecb71bef0f2cd1b68f0b770980a8ef39c/framework/console/controllers/MigrateController.php#L410-L412

When `$params['namespace']` is non-empty and there are no backslashes in `$name`,

1. `strrpos($name, '\\')` evaluates to `false` and, when that is +1'ed, PHP ~~sucks~~ silently casts it to integer `0`, and
2. that causes `substr()` to remove the first character from `$name`,
3. which later prevents `preg_match`ing the `$name` to any of the template-able patterns.

Quite the mouthful, but it is what it is.

### Patch

The issue is fully mitigated by checking whether the `$name` does actually contain a backslash before taking a substring of it.

```diff
diff --git a/framework/console/controllers/MigrateController.php b/framework/console/controllers/MigrateController.php
index aa2625ea0..2cd652474 100644
--- a/framework/console/controllers/MigrateController.php
+++ b/framework/console/controllers/MigrateController.php
@@ -407,8 +407,9 @@ class MigrateController extends BaseMigrateController
         $foreignKeys = $parsedFields['foreignKeys'];
 
         $name = $params['name'];
-        if ($params['namespace']) {
-            $name = substr($name, strrpos($name, '\\') + 1);
+        $lastBackslash = strrpos($name, '\\');
+        if ($params['namespace'] && $lastBackslash !== false) {
+            $name = substr($name, $lastBackslash + 1);
         }
 
         $templateFile = $this->templateFile;
```

### Analysis

ISTM the tests don't catch the bug because the logic of

https://github.com/yiisoft/yii2/blob/b33f1a7ecb71bef0f2cd1b68f0b770980a8ef39c/framework/console/controllers/BaseMigrateController.php#L682-L688

<details><summary>actually has three execution paths, the last of which is an implied empty `else`,</summary>

```php
if (strpos($name, '\\') !== false) {
    $namespace = substr($name, 0, strrpos($name, '\\'));
    $name = substr($name, strrpos($name, '\\') + 1);
} else {
    if ($this->migrationPath === null) {
        $migrationNamespaces = $this->migrationNamespaces;
        $namespace = array_shift($migrationNamespaces);
    } else {
        // do nothing
    }
}
```

</details>

but only two of those execution paths are tested by https://github.com/yiisoft/yii2/blob/b33f1a7ecb71bef0f2cd1b68f0b770980a8ef39c/tests/framework/console/controllers/MigrateControllerTest.php#L110-L119

and the `($this->migrationPath === null)` execution path remains untested.

I can't even the fun you're going to have rethinking tests to cover this.

### Versions

| Q                | A
| ---------------- | ---
| Yii version      | v2.0.42.1
| PHP version      |  7.4.14
| Operating system | Alpine Linux v3.11.7

**Comment by bizley** [comment]
Hm, wow, nice analysis :) Anyway, as [stated in the docs](https://github.com/yiisoft/yii2/blob/2.0.42.1/framework/console/controllers/BaseMigrateController.php#L617):

> In order to generate a namespaced migration, you should specify a namespace before the migration's name.

**Comment by antichris** [comment]
Indeed it is. Yet the lines https://github.com/yiisoft/yii2/blob/b33f1a7ecb71bef0f2cd1b68f0b770980a8ef39c/framework/console/controllers/BaseMigrateController.php#L685-L687 also exist, effectively making that statement ring empty.

If the docs were the sole source of truth, those lines (or at least the https://github.com/yiisoft/yii2/blob/b33f1a7ecb71bef0f2cd1b68f0b770980a8ef39c/framework/console/controllers/BaseMigrateController.php#L687 one for sure) would be absent.

Additionally:
1. regardless of the context, cutting off a string up to the `$characterPosition+1`th character without checking for the actual presence of the character is a very obvious bug,
2. namespace elision is ergonomic and desirable feature, and, subjectively, it should've been there all along — it even kind of was, just a little bit borked,
3. one could also pick at docs saying "should" (not "must" or "have to") in line with the code that works around the absence of an explicit namespace.

**Comment by bizley** [comment]
This is mostly because of the BC and the fact that namespaced migrations were not a thing at the beginning, but it might be confusing indeed.
I agree with (1) for sure. Would you mind preparing a fix?
