### ISSUE TITLE
action IDs 404 link

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2#18670]
https://www.yiiframework.com/doc/guide/2.0/en/intro-upgrade-from-v1#url-management
**action IDs**

**Comment by bizley** [comment]
Yup, `.md` is there and breaks it. Could you fix it, please?

**Comment by Arhell** [comment]
@bizley sure

**Comment by Arhell** [comment]
I looked, in the .md file
[controller IDs] (structure-controllers.md#controller-ids) and [action IDs] (structure-controllers.md#action-ids)

are the same, but for some reason **[action IDs] (structure-controllers.md#action-ids)** is not displayed correctly.
I can make a direct path or a link, example
[about_yii]: http://www.yiiframework.com/about/

How to do it better?

**Comment by samdark** [comment]
Link to where?

**Comment by Arhell** [comment]
> Link to where?

https://www.yiiframework.com/doc/guide/2.0/en/intro-upgrade-from-v1#url-management
![1](https://user-images.githubusercontent.com/26163841/120228333-93a3ed00-c253-11eb-9c1d-709ed0a80fe7.png)

**Comment by arogachev** [comment]
It's yii2-apidoc issue. Duplicate of https://github.com/yiisoft/yii2-apidoc/issues/197.
