### ISSUE TITLE
DBCache doesn't work with custom cache table name on MSSQL/SqlServer

### ISSUE THREAD

**Issue by aidanbek** [yiisoft/yii2#18678]
### What steps will reproduce the problem?
Here I used basic template https://github.com/yiisoft/yii2-app-basic
According to https://www.yiiframework.com/doc/api/2.0/yii-caching-dbcache#$cacheTable-detail:

1. Create cache table
```
create table test_cache
(
    id     char(128) not null primary key,
    expire int,
    data   varbinary(max)
)
```

2. In db.php:
```
return [
    'class' => Connection::class,
    'dsn' => 'sqlsrv:Server=<server>;Database=<db>',
    'username' => '<user>',
    'password' => '<pass>',
    'charset' => 'utf8',
]
```
3. In web.php:
```
'cache' => [
    'class' => yii\caching\DbCache::class,
    'cacheTable' => 'test_cache'
],
```

4. In SiteController, in method actionAbout:
```
$cache = Yii::$app->cache;

return $cache->getOrSet('testKey', function () {
    return 122;
});
```
### What is the expected result?
On page '122' and the cache table row with key 'testKey'

### What do you get instead?
Error page with:
```
PHP Notice – yii\base\ErrorException
Trying to get property 'columns' of non-objectPHP Notice – yii\base\ErrorException
Trying to get property 'columns' of non-object
```
in C:\inetpub\wwwroot\aidan\web-test2\vendor\yiisoft\yii2\caching\DbCache.php
on line 308 at: 
```
$this->db->getTableSchema('cache')->columns['data']->dbType === 'varbinary';
```
I think it should be:
```
$this->db->getTableSchema($this->cacheTable)->columns['data']->dbType === 'varbinary';
```
cause it uses default cache table name
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1?
| PHP version      | 7.3.27 nts x64
| Operating system | Windows Server 2016 (14393 )

**Comment by bizley** [comment]
Yes, this is exactly what you said. Would you mind preparing a PR with a fix?

**Comment by aidanbek** [comment]
done #18679
