### ISSUE TITLE
TypeError NumberFormatter 

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#18674]
### What steps will reproduce the problem?

```php
Yii::$app->formatter->asCurrency(
  '10000',
  'EUR',
  [
    NumberFormatter::MAX_FRACTION_DIGITS => 0,
    NumberFormatter::GROUPING_SIZE => 3,
    NumberFormatter::GROUPING_SEPARATOR_SYMBOL => '_'
  ]
);
```

### What is the expected result?

10_000 €

### What do you get instead?

TypeError
NumberFormatter::setAttribute(): Argument #2 ($value) must be of type int|float, string given

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1.
| PHP version      | 8.0.6
| Operating system |

**Comment by bizley** [comment]
Yes, it is a problem on php 8. Untill we fix it please don't use `NumberFormatter::GROUPING_SEPARATOR_SYMBOL => '_'` the way you did. Instead you can set it like:

    Yii::$app->formatter->thousandSeparator = '_';

or

    Yii::$app->formatter->numberFormatterSymbols[NumberFormatter::GROUPING_SEPARATOR_SYMBOL] = '_';

**Comment by bizley** [comment]
I've realized that this is not a bug. You should use `$textOptions` instead of `$options` for that kind of a setting.

But since that is not really clear I think we can make it more user-friendly by adding better messages for the exceptions.

**Comment by tsanchev** [comment]
If I use `NumberFormatter::GROUPING_SEPARATOR_SYMBOL => '_'` in `$textOptions` instead of `$options` I don't get the desired result. The currency symbol get changed instead of the thousands separator.

This works:

    Yii::$app->formatter->thousandSeparator = '_';

But this doesn't:

    Yii::$app->formatter->numberFormatterSymbols[NumberFormatter::GROUPING_SEPARATOR_SYMBOL] = '_';

**Comment by bizley** [comment]
Hmm, yes, when we set `thousandSeparator` we set internally

```
$formatter->setSymbol(NumberFormatter::GROUPING_SEPARATOR_SYMBOL, $this->thousandSeparator);
$formatter->setSymbol(NumberFormatter::MONETARY_GROUPING_SEPARATOR_SYMBOL, $this->thousandSeparator);
```

so both would have to be set, better to just use `thousandSeparator`, that's what it's for.

**Comment by tsanchev** [comment]
Also in order for `Yii::$app->formatter->thousandSeparator = '_';` to work, i also have to set `NumberFormatter::GROUPING_SEPARATOR_SYMBOL => 1`
I don't really know what this 1 is doing but it does the job 😃 
Otherwise i don't get any separation symbol at all.

**Comment by bizley** [comment]
You mean `NumberFormatter::GROUPING_USED`? Hmm, should we set it as well?

**Comment by tsanchev** [comment]
No, i mean `NumberFormatter::GROUPING_SEPARATOR_SYMBOL`
The reason I've tried to put an integer there in the first place is because of the error. I've tried putting **`0`** - no separator is displayed. Then tested with **`1`** and a space appeared as thousands separator (without actually specifying any value for `Yii::$app->formatter->thousandSeparator`)

**Comment by bizley** [comment]
What is your locale value?

**Comment by tsanchev** [comment]
> What is your locale value?

'bg'

**Comment by bizley** [comment]
I've tested it without Yii ( https://3v4l.org/a0nDu ) and looks like in case of currencies attributes are just ignored but most probably it all depends on the ICU version you have installed. I'm afraid we cannot do much about that apart from taking care of the proper error handling which is in my PR.
