### ISSUE TITLE
PHP 8 check on GitHub currently not required

### ISSUE THREAD

**Issue by rhertogh** [yiisoft/yii2#18686]
Since Yii >= 2.0.38 officially supports PHP 8 I think it would be good to make the build be required in the GitHub checks.

![image](https://user-images.githubusercontent.com/1292337/120015997-5a197a80-bfe4-11eb-8d4f-e0f64bbd3f17.png)

**Comment by bizley** [comment]
IIRC it's in settings > branches > branch protection rules. I don't have access to it.

**Comment by samdark** [comment]
Added.
