### ISSUE TITLE
Email validator accepts wrong email format

### ISSUE THREAD

**Issue by jmar1998** [yiisoft/yii2#18689]
### What steps will reproduce the problem?
I create a permalink from phpliveregex with the regex used for email validations
https://www.phpliveregex.com/p/Az1
As you can see, if we use some special characters on the prefix of the email, the regex is accepting that email
### What is the expected result?
Follow the normal format for emails
https://help.xmatters.com/ondemand/trial/valid_email_format.htm#:~:text=A%20valid%20email%20address%20consists,the%20left%20of%20the%20%40%20symbol.&text=For%20example%2C%20in%20the%20address,com%22%20is%20the%20email%20domain.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
All emails in your example are valid according to https://datatracker.ietf.org/doc/html/rfc5322
