### ISSUE TITLE
No checks in BaseArrayHelper::getColumn if $array - is array?

### ISSUE THREAD

**Issue by wispoz** [yiisoft/yii2#18691]
### What steps will reproduce the problem?
$columns = ArrayHelper::getColumn(null,'test');
### What is the expected result?
$columns = [];
### What do you get instead?
Invalid argument supplied for foreach()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | 7.3.14
| Operating system | linux

**Comment by wispoz** [comment]
#18690

**Comment by bizley** [comment]
I don't think it is necessary to add guards for arguments that are not mentioned in the documentation. Unfortunately this is not typed PHP here. WDYT @samdark ?

**Comment by wispoz** [comment]
> I don't think it is necessary to add guards for arguments that are not mentioned in the documentation. Unfortunately this is not typed PHP here. WDYT @samdark ?

its mentioned in phpdoc, see
[https://github.com/yiisoft/yii2/blob/7966fe47e6cbf0e87bb552ab60be173e9dd30d2a/framework/helpers/BaseArrayHelper.php#L526]

**Comment by bizley** [comment]
Yes, and `array` does not mean you can put `null` there because it would be `array|null`. And yes, I know we tend to omit the `null` in other places where it can go ;)

**Comment by wispoz** [comment]
getValue method have this checks, i think behaviour must be the same (expected)

**Comment by bizley** [comment]
Hmm, no, it does not have that check.

**Comment by wispoz** [comment]
> Hmm, no, it does not have that check.

yes sorry, my mistake. getValue dont have that check.

**Comment by rob006** [comment]
I would rather "fix" `getValue()` to throw exception if `null` is passed as `$array`, than support `null` in every case where we expect an array.

**Comment by wispoz** [comment]
> I would rather "fix" `getValue()` to throw exception if `null` is passed as `$array`, than support `null` in every case where we expect an array.

Nope, it will not work, because getColumn iterates array (foreach) then getValue. And this method fall if $array is not itterable.

**Comment by rob006** [comment]
And that is fine, because you should not pass `null` when array/iterable is expected. While it is debatable whether `getValue()` should accept `null` (it make sense in some way, since it supports default value), I'm pretty sure we should not add special support for non-iterables in methods like `getColumn()` or `index()` - just respect types specified in phpdoc.

**Comment by wispoz** [comment]
> And that is fine, because you should not pass `null` when array/iterable is expected. While it is debatable whether `getValue()` should accept `null` (it make sense in some way, since it supports default value), I'm pretty sure we should not add special support for non-iterables in methods like `getColumn()` or `index()` - you should respect types specified in phpdoc.

I think its not fine, because its throw error and not Exception, phpdoc its good but we have real life, and i think getColumn must handle use-case when $array is null
1. Throw Exception (mb best solution)
Or
2. Return $default if $array is not itterable.

**Comment by rob006** [comment]
> I think its not fine, because its throw error and not Exception

What difference does it make? Normally you would have `array` type for parameter in method signature (instead of phpdoc), but then PHP would throw `TypeError` (so not `Exception`) if you would try pass non-array.

**Comment by wispoz** [comment]
> > I think its not fine, because its throw error and not Exception
> 
> What difference does it make? Normally you would have `array` type for parameter in method signature (instead of phpdoc), but then PHP would throw `TypeError` (so not `Exception`) if you would try pass non-array. 

Normally yes, but now method signature getColumn($array,...)
But must be
getColumn(array $array,...) or similar

**Comment by rob006** [comment]
That is the limitation of required PHP version (5.4) - phpdoc is the best what framework could use right now. You should simply respect phpdoc and fix your code if you have scenarios where `null` could be passed to `getColumn()`.

**Comment by rob006** [comment]
Shouldn't we close this? AFAIK consensus from #18690 was that only arrays/iterables are supported and anything else should throw an error.
