### ISSUE TITLE
Email format with -@

### ISSUE THREAD

**Issue by SayChi** [yiisoft/yii2#18693]
Sorry if the description isn't very clear. I'm using Yii indirectly, so it's challenging to formulate it correctly

### What steps will reproduce the problem?
Setting an email to something with a hyphen before the \@. So something like: example-@domain.com

### What is the expected result?
If [this wiki page](https://en.wikipedia.org/wiki/Email_address#Examples) is to be believed, i would expect it to be accepted. (that and the fact that we've had multiple users with such format email adres)

### What do you get instead?
Invalid email notification

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | 7.4.12
| Operating system | Windows 10

**Comment by samdark** [comment]
What validator settings do you use?

- Are any of the patterns customized?
- What are values of allowName, checkDNS and enableIDN?

**Comment by SayChi** [comment]
I'm trying to gather up the relevant validation rules, i believe this is the complete list:
```
'trim', 'skipOnEmpty' => true
'email', 'enableIDN' => true
'string', 'max' => 255
'required'
```

I can't give much in-depth information, as I didn't implement these myself. I'm using CraftCMS, which uses Yii, which makes it hard for me to judge the line between Craft related code and Yii

**Comment by samdark** [comment]
With these settings it should be valid. @brandonkelly would you please clarify about validator options used in Craft?

**Comment by SayChi** [comment]
I just tried with a different install, and there i was able to use such a mail adres. I updated the install that this question was relevant to, and now it seems to work too

I don't understand how, before the update it was already running the same version of Yii. And i checked when the user validation rules in Craft were last changed, and that's been a while

So it somehow seems to be resolved, sorry for the wasted time, i should have just updated clearly

**Comment by samdark** [comment]
Glad it's solved.

**Comment by brandonkelly** [comment]
Ah strange. Sorry, should have tested locally before suggesting you post here. Maybe IDN related? We started supporting IDN in Craft 3.5.16 (released November 24, 2020).
