### ISSUE TITLE
Yii2 request and DI

### ISSUE THREAD

**Issue by andrew-svirin** [yiisoft/yii2#18694]
Когда получал через DI в конструкторе реквест, то получил наполненый даннными реквест в  тестах и пустой реквест на живом сервере.

Очень хотелось бы иметь доступ к DTO модели реквеста в екшене запроса, но на DI в екшене стоят ограничения. 

----------
Hi!

When took by DI in construct-method request model took filled by POST data request instance in codeception tests, but on live- server request always was empty.

Will be good t o have access to DTO model in Controller::action, but now are some restrictions on allowed injection in action.

Thanks!

----------
Yii version 2.0.42.1

**Comment by bizley** [comment]
Could you provide a test case?

**Comment by andrew-svirin** [comment]
Some mystic is in Content-Type application/json

All invocations are from Controller::action()
```php
$request1 = Yii::createObject(DTORequest::class, [$this->request]);
```
Filling DTO


```php
$request2 = $request2 = Yii::$container->get(DTORequest::class);
```
Empty DTO

File DTORequest:

```php
use yii\web\Request as WebRequest;
...
public function __construct(WebRequest $webRequest, $config = [])
```

**Comment by samdark** [comment]
The information provided isn't enough to reproduce the issue. Ideally we'd like to have a unit test but minimal test-case starting with a clean basic app would do as well.

**Comment by andrew-svirin** [comment]
@samdark Just make 3 steps

![image](https://user-images.githubusercontent.com/16819743/120456425-41bbae00-c39e-11eb-8115-7ee2b0bb4a5b.png)

**Comment by andrew-svirin** [comment]
In opposite
![image](https://user-images.githubusercontent.com/16819743/120456787-99f2b000-c39e-11eb-9825-c2cb2afca510.png)

**Comment by andrew-svirin** [comment]
And also this is what I did and had a bug.

![image](https://user-images.githubusercontent.com/16819743/120457144-e4742c80-c39e-11eb-8f44-a2e6a9e9b378.png)

**Comment by andrew-svirin** [comment]
![image](https://user-images.githubusercontent.com/16819743/120458626-1afe7700-c3a0-11eb-9b71-62e928a0c654.png)
This is strange that parsers array is empty.

**Comment by samdark** [comment]
Would you please provide a POST request you make?

**Comment by andrew-svirin** [comment]
I doing it from codeception.
By test like this:
```php
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendPOST(
            sprintf('chats/%s/messages/send', 1111),
            [
              'user_id' => 11111,
              'body' => 'Any message',
            ]
        );
```
If I will send without `$I->haveHttpHeader('Content-Type', 'application/json');` then data will parsed well.

**Comment by andrew-svirin** [comment]
Temporary solution will be to have settings in config file:
```php
...
'container' => [
  'definitions' => [
     Request::class => [
        'class' => Request::class,
         'parsers' => [
           'application/json' => JsonParser::class,
         ],
  ],
],
```
But it is very strange:
1. to bind parser this way when allowed headers.
2. to have 2 instances of Request in singleton %)

**Comment by andrew-svirin** [comment]
Modified class
```php
use yii\web\Request as WebRequest;

...

public $attr1;
public $attr2;

public function __construct($config = [])
{
  $this->webRequest = Yii::$app->request;
  parent::__construct($config);
}

public function init()
{
  parent::init();
  $this->loadAttributes();
}

protected function loadAttributes()
{
  $this->setAttributes([
    'attr1' => $this->webRequest->get('attr1'),
    'attr2' => $this->webRequest->getBodyParam('attr2'),
  ]);
}

**Comment by samdark** [comment]
So... is the issue solved?

**Comment by andrew-svirin** [comment]
@samdark I think it behave like it was designed. But in concept it is incorrect to have 2 instances of requests. One in `Yii::$app` and second in `Yii::$container`. Entity from `Yii::$app` section should be alias on entity in container.

My expectations were to take the same entity by `Yii::$app->request` and `Yii::$container->get(Request::class)` at least i do not see reasons to distinguish these 2 sections.

**Comment by samdark** [comment]
Yeah. That's a global thing in Yii 2 that container in some cases isn't the same as components configured but I don't see a way to fix it without breaking backwards compatibility. There's a single container in Yii 3.
