### ISSUE TITLE
Class 'backend\models\user\User' not found

### ISSUE THREAD

**Issue by asger777** [yiisoft/yii2#18706]
On first fresh install, backend module contains wrong main.php params.

its 

`
'user' => [
'identityClass' => 'backend\models\user\User',
'enableAutoLogin' => true,
'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
],
`
here should be  'identityClass' => 'common\models\User'

because there is no any backend models User class on fresh install

**Comment by bizley** [comment]
I'm not sure where did you get that config but [backend main config](https://github.com/yiisoft/yii2-app-advanced/blob/master/backend/config/main.php) contains `common\models\User` for a long time.
