### ISSUE TITLE
Query:count must return int instead of string

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#18708]
QueryInterface::count declare integer result:
```php
@return int number of records.
```

But Query::count implementation return string instead:
```php
@return int|string number of records.
```

So, when using, PhpStorm says that type cast is redudant here:
```php
function getCount(): int 
{
    return (int)$this-query->count();
}
```

but without typecast result is Error:
```Return value must be of type int, string returned```

| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      |  8.0

**Comment by dicrtarasov** [comment]
OK, then return type of QueryInterface::count must be changed to actual int|string instead of int.

**Comment by bizley** [comment]
Yes, it should be compatible.

**Comment by dicrtarasov** [comment]
Is there any conditions, when Query::count return int ? :) Or it always return string, not just when big integer values. In MySQL never see there int values :)

**Comment by bizley** [comment]
In MySQL it's always string apparently, yes. I think in PostgreSQL it's int for example.

**Comment by dicrtarasov** [comment]
created pull request https://github.com/yiisoft/yii2/pull/18713

**Comment by bizley** [comment]
Closed via https://github.com/yiisoft/yii2/commit/e2b90b5f3eb6395f404112d115c285a6fde7d0e1
