### ISSUE TITLE
Number Validator with max and value with decimal places doesn't work

### ISSUE THREAD

**Issue by 1Luc1** [yiisoft/yii2#18702]
### What steps will reproduce the problem?
A model `AnnualRate` with a defined rule for the `percentage` property.

```
public function rules()
    {
        return [
            [['percentage'], 'required'],
            [['percentage'], 'number', 'min' => 0, 'max' => 100, 'numberPattern' => '/^\s*[-+]?[0-9]*[,]?[0-9]+([eE][-+]?[0-9]+)?\s*$/', 'message' => Yii::t('app', 'The number ({value}) has to be in the format (12345,67)')],
            ['percentage', 'filter', 'filter' => function ($value) {
                $value = str_replace(',', '.', $value);
                return $value;
            }]
        ];
    }
```
The `percentage` property has to be an the format 12,34 if decimal places are provide. Note: comma (,) instead of point (.).

The form to input the percentage is defined as follow:
```
<div class="add-annual-rate-form">
    <?php $form = ActiveForm::begin(['id' => 'annual-rate-form', 'enableAjaxValidation' => true]); ?>
    <?= $form->field($model, 'percentage')->textInput(['value' => FormatHelper::getNumberValue($model->percentage)]) ?>
    <?php ActiveForm::end(); ?>
</div>
```

` FormatHelper::getNumberValue`
```
class FormatHelper {
    public static function getNumberValue($value) {
        return empty($value) ? '' : str_replace('.', '', Yii::$app->formatter->asDecimal($value, 2));
    }
}
```

### What is the expected result?
No validation error.

### What do you get instead?
Validation fails and returns Standard Message: "Percentage cannot be greater than 100."
![grafik](https://user-images.githubusercontent.com/25635952/121024903-f0982980-c7a4-11eb-8e93-7f39c2658500.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | 8.0.6
| Operating system | Manjaro (latest)

### Additional Note
With PHP version v7.0.33-0ubuntu0.16.04.9 and Yii 2.0.42.1 this problem **doesn't** exist.

**Comment by bizley** [comment]
The quickest way of fixing it is to replace the order of `number` and `filter` rules so the `filter` goes first and then removing `numberPattern` setting from `number` rule.

This is happening because PHP 8 change the way it handles string numbers - previously `"22,76" > 100` would yield `false` - in PHP 8 it's `true`.

Changing the order of the rules makes sure that input is normalized before being validated.

We need to think if that validator needs some adjustments or not.

**Comment by 1Luc1** [comment]
Thanks for the fast reply.

Trying your quick fix, let the number 23.45 work, but 23,45 shows the error defined within in the number rule.
So I guess your next info would fix that ...
> Changing the order of the rules makes sure that input is normalized before being validated.

Can you give me an hint on how to "normalized" the value?

**Comment by bizley** [comment]
```
['percentage', 'filter', 'filter' => function ($value) { // this line first
    return str_replace(',', '.', $value);
}],
[['percentage'], 'number', 'min' => 0, 'max' => 100],
```

First value is normalized by replacing comma with dot. Then it's validated.

**Comment by bizley** [comment]
Hmm, exactly? Have you removed `'numberPattern' => '/^\s*[-+]?[0-9]*[,]?[0-9]+([eE][-+]?[0-9]+)?\s*$/', 'message' => Yii::t('app', 'The number ({value}) has to be in the format (12345,67)')`?

**Comment by 1Luc1** [comment]
Yep.

```
  public function rules()
  {
      return [
          [['percentage'], 'required'],
          ['percentage', 'filter', 'filter' => function ($value) {
              return str_replace(',', '.', $value);
          }],
          [['percentage'], 'number', 'min' => 0, 'max' => 100],
      ];
  }
```
Results in
![grafik](https://user-images.githubusercontent.com/25635952/121078771-a7160180-c7d9-11eb-868b-af7ee3971b66.png)
and
![grafik](https://user-images.githubusercontent.com/25635952/121078975-ddec1780-c7d9-11eb-8841-a4f70eb0feee.png)

And if i change the rule order the results are the same.

**Comment by bizley** [comment]
Oh, totally forgot about client validation. Please check if this is the case. Unfortunately there is no fast way of applying `filter` to a client validation unless it's `trim` there. You would have to disable client validation.

**Comment by bizley** [comment]
Hm, on the other hand, it worked on PHP 7 before... I'm not sure what is going on here.

**Comment by bizley** [comment]
I have prepared myself a form with that field and rules and I can confirm it works as described by me. You only have to set `enableClientValidation` to `false` as I mentioned. It works then with both server and ajax validation. Client validation is only thing that stops it so I assume you did not switched it off.

**Comment by 1Luc1** [comment]
thanks for your attempts. You are right, it works now with the clientValidation disabled.
Also inserting a number like 23.34 will validate, but thats just ok with me.
thanks again.
