### ISSUE TITLE
When using function updateAll in AR to update a field but value including zero-width space，it fail and no error message.

### ISSUE THREAD

**Issue by mysticzhong** [yiisoft/yii2#18700]
### What steps will reproduce the problem?
a table like this : 
```
CREATE TABLE `detail` (
  `detail_id` int(11) NOT NULL AUTO_INCREMENT,
  .......
  `pro_sno` varchar(128) NOT NULL DEFAULT '',
  `pro_fagent` varchar(128) NOT NULL DEFAULT '',
  .......
  `list_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`detail_id`) USING BTREE,
  KEY `pro_sno` (`pro_sno`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
```

and field pro_sno in table is including zero-width space, like `&lrm; `, `&rlm;`  or `&#8203;` . 
（http://114.xixik.com/character/    see at 【 markup-significant and internationalization characters】 ）.

When I remove zero-width space from old value to new value, then update the new value into table by funtion  updateAll ();
It return 0 mean update fail, also no exception throw or log.
like ：
`Detail::updateAll(['pro_sno'=>$pro_sno], ['detail_id' => $getParams['data_id']]);   // return 0;`

However, when I thinking out and used a new way, it success!
Just like this:

```
$rand_str = rand(10000,99999)."_RANDSTR";
Detail::updateAll(['pro_sno'=>$rand_str], ['detail_id' => $getParams['data_id']]);
Detail::updateAll(['pro_sno'=>CTrim::trim($obj->pro_sno)], ['detail_id' => $getParams['data_id']]);
```

Before update the new value, I update a rand string first. It solve it.
I don`t know why and how to fix it, so I submit a issue. Come on, please help me!

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  5.6 or 7
| Operating system | Ubuntu or Centos

**Comment by mysticzhong** [comment]
function CTrim::trim is about remove zero-width space from old value to new value. 
The code is below:

<?php
use Yii;

/**
 * Class CTrim
 */
class CTrim
{
    private static $_specialChars = [
        ' ' => ' ',
        ' ' => ' ',
        '　' => ' ',
        '' => ' ',
    ];


    private static $_specialMerged = false;


    public static function trim($val = '')
    {
        if (false === self::$_specialMerged) {
            self::$_specialChars = array_merge(self::$_specialChars, self::_specialChar1());
            self::$_specialMerged = true;
        }

        $val = str_replace(
            array_keys(self::$_specialChars),
            array_values(self::$_specialChars),
            $val
        );

        $val = trim($val);

        $characterMask = implode('', Yii::$app->params['ickey_trim_char']);

        return trim($val, $characterMask);
    }

    private static function _specialChar1()
    {
        $bytesBlack = [239, 187, 191];
        $bytesZeroWidth = [226, 128, 142];
        $equivalentStr = '';

        return [
            self::bytes2str($bytesBlack) => $equivalentStr,
            self::bytes2str($bytesZeroWidth) => $equivalentStr,
        ];
    }

    public static function bytes2str(array $bytes)
    {
        $str = '';
        foreach ($bytes as $ch) {
            $str .= chr($ch);
        }

        return $str;
    }

    public static function str2bytes($str)
    {
        $bytes = [];

        $len = strlen($str);
        if (0 === $len) {
            return $bytes;
        }

        for ($i = 0; $i < $len; $i++) {
            $bytes[] = ord($str[$i]);
        }

        return $bytes;
    }
}

**Comment by mysticzhong** [comment]
Function CTrim::trim is about remove zero-width space from old value to new value.
The code is in links [https://github.com/mysticzhong/phppractice/blob/master/src/CTrim.php]( https://github.com/mysticzhong/phppractice/blob/master/src/CTrim.php)

**Comment by bizley** [comment]
Does it work when you set charset to `utf8mb4`? Or `utf8mb4_zh_0900_ai_ci`?

**Comment by mysticzhong** [comment]
Yeah, it work in utf8mb4 and return 1. Yesterday in utf8 it can't work.

**Comment by bizley** [comment]
Because `utf8` is an alias for `utf8mb3` which cannot store all Unicode characters available nowadays. Ok, so it was MySQL thing. Glad it's resolved.

**Comment by mysticzhong** [comment]
Yeah, thank you.
