### ISSUE TITLE
fix info block on uk lang

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2#18710]
information block is displayed incorrectly
en v https://www.yiiframework.com/doc/guide/2.0/en/start-hello#creating-action 
uk v https://www.yiiframework.com/doc/guide/2.0/uk/start-hello#creating-action

**Comment by bizley** [comment]
`Info` tag should not be translated.

**Comment by Arhell** [comment]
block is displayed incorrectly
![1](https://user-images.githubusercontent.com/26163841/121802073-64be4b80-cc43-11eb-9fdc-7c080f9591ad.png)
![2](https://user-images.githubusercontent.com/26163841/121802075-67b93c00-cc43-11eb-8ca5-98bc72fc2338.png)

**Comment by bizley** [comment]
Yes, keep `Info` as `Info` and not `Інформація` and it will be fine.

**Comment by Arhell** [comment]
> Yes, keep `Info` as `Info` and not `Інформація` and it will be fine.

Ok
