### ISSUE TITLE
building cache key does not normalize input

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#18717]
### What steps will reproduce the problem?

1. Make a cache element that is an array where one member is numeric value from ActiveRecord (or even boolean)
2. Try to fetch same element using said record(but now that member is string)

### What is the expected result?
Since `serialize((int) 1) !== serialize((string) 1)` it will fail

### What do you get instead?
Every array member should be cast to something common, so things are easier to manage

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42
| PHP version      |  7.4
| Operating system | Docker

**Comment by samdark** [comment]
@mikk150 would you please provide a few `$cache->set()` calls with example values?

**Comment by mikk150** [comment]
For example, if I make
```
$cache->set(['array', 'member', 'number', 42], 'array_cache_key_with_integer');
```
In ActiveRecord itself(where numeric value is a number)

and try to get it in some other part of code using 
```
$cache->get(['array', 'member', 'number', '42']);
```
where 42 is fetched from DB but since everything fetched from DB is string, it fails



I actually made this issue to upstream code that has been working in production for over a year

**Comment by mikk150** [comment]
I now understand what the underlying issue is... I presumed(wrongly) that anything that came from DB was a string, but looking at [ActiveRecord::populateRecord()](https://github.com/yiisoft/yii2/edit/master/framework/db/ActiveRecord.php#L512) I can see how this assumption was wrong...

Now if we use `ActiveRecord::load()` from `POST` it becomes a string, so I invalidate using a string, and later I check for cache dependency using an int(they are not same datatype), it breaks.

I tried to fix it by doing
![image](https://user-images.githubusercontent.com/4953629/125774354-67d7378c-a2be-460b-90ee-cbc96a21cb6f.png)

but I think I cannot do it this way, because we can do
```
$model = new yii\db\ActiveRecord();
$model->test = new yii\db\Expression('NOW()');
```

and these obviously cannot be typecasted to PHP objects

so I think my only way is to refresh object from DB before I do cache invalidation

**Comment by samdark** [comment]
Yes, seems so. So... closing PR and issue?
