### ISSUE TITLE
Application Structure pre code block

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2#18723]
Different languages have different display of 1 block, you need to bring to a single style

example
https://www.yiiframework.com/doc/guide/2.0/en/start-workflow#application-structure
https://www.yiiframework.com/doc/guide/2.0/pl/start-workflow#application-structure

**Comment by bizley** [comment]
I'm sorry, what is the issue here?

**Comment by Arhell** [comment]
> I'm sorry, what is the issue here?

I want to bring the block to a single display style, example
**en** 
![1](https://user-images.githubusercontent.com/26163841/122881507-e7ca5a80-d343-11eb-9cdd-fdc15b70eca5.png)
**pt**
![2](https://user-images.githubusercontent.com/26163841/122881537-f0bb2c00-d343-11eb-913a-fa4d2b8b6404.png)

**Comment by bizley** [comment]
It's `pl` ;) But I'm not sure what you mean - is it about the colors?

**Comment by Arhell** [comment]
> It's `pl` ;) But I'm not sure what you mean - is it about the colors?
Yes

**Comment by bizley** [comment]
Ok, go for it although I'm not sure if this can be fixed ;)
