### ISSUE TITLE
Argument 1 of yii\web\Session::offsetGet expects int, string provided

### ISSUE THREAD

**Issue by white43** [yiisoft/yii2#18733]
### What steps will reproduce the problem?

Analyze a Yii2-based project with `Psalm`. The project needs explicitly to write/read something to/from session via `yii/web/Session`

### What is the expected result?
No error

### What do you get instead?

```
ERROR: InvalidScalarArgument - somewhere.php - Argument 1 of yii\web\Session::offsetGet expects int, "verifyCode" provided (see https://psalm.dev/012)
                $verifyCode = $this->getSession()['verifyCode'];
```
### Additional info

The `$offset` argument has integer type for `offsetGet` and `offsetSet`, while it is mixed for `offsetExists` and `offsetUnset`. We could use `int` and `string` union for all of these offset methods and give more information for static analyzers like `Psalm`. Or even make it more strict as it was done in Yii3 Session service.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | any
| Operating system | any

**Comment by samdark** [comment]
The type isn't correct. Should be `int|string`.

**Comment by mariosimao** [comment]
I have created a PR for this issue
