### ISSUE TITLE
indexBy('a') for select(['a', 'b'])

### ISSUE THREAD

**Issue by frcstc** [yiisoft/yii2#18755]
yii2-advanced 
### What steps will reproduce the problem?
 (new \yii\db\Query())->from("table")
        ->select(['a', 'b'])
        ->indexBy("a")
        ->column();
result: array(3) { [1]=> string(6) "草稿" [2]=> string(9) "已发布" [3]=> string(9) "已归档" } 
it's work 

**but if:**
 (new \yii\db\Query())->from("table")
        ->select(['b', 'a'])
        ->indexBy("a")
        ->column();
i just change order select(["b","a"])
it's not work 
result:array(3) { [1]=> string(1) "1" [2]=> string(1) "2" [3]=> string(1) "3" 

### What is the expected result?
i expected result :
array(3) { [1]=> string(6) "草稿" [2]=> string(9) "已发布" [3]=> string(9) "已归档" } 
### What do you get instead?
file: yiisoft\yii2\db\Query.php
public function column($db = null){}
![图片](https://user-images.githubusercontent.com/30496778/124898149-81b32800-e011-11eb-9456-8288bf8735f8.png)

i edit:
![图片](https://user-images.githubusercontent.com/30496778/124898318-a7d8c800-e011-11eb-8246-1815293ca3a7.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.2
| Operating system | ubuntu 18.04

**Comment by bizley** [comment]
It's because `column()` returns **first** column of the result as stated in the documentation.

**Comment by frcstc** [comment]
@bizley yeah, you are right, i was not see the documentation.
