### ISSUE TITLE
Rest Serializer Events

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#18777]
### What steps will reproduce the problem?

There are situations where you like to interact with a model, based on an controller/action context with a given active data provider, for example:

MyController

```php
public function indexAction()
{

 // maybe i have some where important context in this action
 $veryImportentContextId = 4;
return new ActiveDataProvider(['query' => FooBarModel::find()]);
}
```

Now i am **unable** to pass `$veryImportentContextId` informations from `MyController` action into the `FooBarModel`, for example an extraField() which accept/requires this  $veryImportentContextId param.

As long as i like to use the super nice comfy benefits of ActiveDataProvider, i am unable to interact with those rows.

### Solution

The Rest Serializer should have events, for example here: https://github.com/yiisoft/yii2/blob/master/framework/rest/Serializer.php#L299 (in combination of https://github.com/yiisoft/yii2/blob/master/framework/rest/Controller.php)

```php
public function indexAction()
{

 // maybe i have some where important context in this action
 $veryImportentContextId = 4;
 $this->on(self::EVENT_AFTER_MODEL_SERIALIZE, function(ActiveRecord $model) use ($veryImportentContextId) {
   $model->addFieldXyz($veryImportentContextId)
});

return new ActiveDataProvider(['query' => FooBarModel::find()]);
}
```

Maybe it's also a more generic question on how to certain model rows/fields/extraFields could interact with action $context. The only solution, which seems to be bad, is to use a Component and store informations there, and receive them in the model - but this does not sound like a good approach (or to not use ActiveDataProvider - but this should not be a solution)

Maybe i explained my problem not very good - let me know please. Maybe (hopefully) there is already a nice solution for my problem?

If there could be an events solution, i would send a PR.

**Comment by samdark** [comment]
How about model events?

```php
Event::on(FooBarModel::class, ActiveRecord::EVENT_AFTER_INSERT, function ($event) use ($veryImportentContextId) {
    $model = $event->sender;
    $model->addFieldXyz($veryImportentContextId);
});
```

**Comment by nadar** [comment]
I am going to test that, if this works, perfect :+1: Does not look very sexy, but seems to consistent. I am still "voting" for a bind method in ActiveQuery to bind that into the Active Record, like `User::find()->bind(['foo' => 'bar'])` where `foo` could be a property or a setter.

Thanks for your reply on this @samdark
