### ISSUE TITLE
yii.activeForm.js IE11 compatibility error

### ISSUE THREAD

**Issue by procin** [yiisoft/yii2#18772]
assets/yii.activeForm.js line 332:

var disabled = $input.toArray().reduce((result, next) => result && $(next).is(':disabled'), true);

Is not Internet Explorer 11 compatible, while the rest of Yii2 is as far as I can see.
This line of code gives a console error in IE11, making the rest of the scripts stop.

**Comment by bizley** [comment]
Duplicates #18650
It was [fixed](https://github.com/yiisoft/yii2/pull/18650/commits/fdc6e98411f54fc4a4d5e3f5894d84349ef0af05) already but it awaits release.
