### ISSUE TITLE
DropDownList item callback

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii2#18778]
не возможно реализовать подобной dropdownlist  http://prntscr.com/1f3srg4

может стоит сделать такой же метод как в radioList или checkboxList -> "item" callback

```
<select>
<option value=".." data-image="..">text</option>
...
</select>
```
а то реализовать подобный дропдавн как указан на скрине, через текущий BaseHtml::dropDownList не возможно

**Comment by samdark** [comment]
@andrtechno можно скриншот прямо в GitHub запостить? По ссылке не открывается сайт.

**Comment by andrtechno** [comment]
![Без названия](https://user-images.githubusercontent.com/6948026/127123663-804add8f-12ac-4b87-a2e5-02c466b8a1ca.png)

**Comment by samdark** [comment]
Вроде возможно через `options`: https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#dropDownList()-detail

**Comment by andrtechno** [comment]
@samdark да можно, но почему тут не через callback сделано? 
массив в items еще и в options свой массив, лучше бы сделать как в radioList и checkboxlist = callback

**Comment by samdark** [comment]
Да, наверное, можно было бы. Pull request примем, но сами править пока не сможем. Заняты Yii 3...
