### ISSUE TITLE
Boolean validator inconsistency and native PHP true and false values

### ISSUE THREAD

**Issue by PELock** [yiisoft/yii2#18786]
Yii2 2.0.41

Boolean validator is pretty useless from the PHP programming point of view:

Field declaration within the form class

```php
public $rename_variables = true;
```

Form rule for this field:

```php
[["rename_variables"], "boolean"],
```

HTML field:

```html
<td><?= $form->field($model, 'rename_variables')->checkbox()->label('Zmień nazwy zmiennych na losowe ciągi znakowe'); ?>
```

The result is either '0' or '1' string. This is fine, weird but fine.

When I change the form rules to 

```php
[["rename_variables"], "boolean", 'falseValue' => false, 'trueValue'=> true ],
```

The resuts are the same,  either '0' or '1' string. Still weird, but ok.

Why isn't the results a native PHP boolean ```true``` or ```false```?

If I have a form with 30 of those fields I could just drop the boolean validator from the form rules and do what I need to do anyways - convert it:

```php
$real_value1 = boolval($this->rename_variables);
$real_value2 = boolval($this->rename_variables2);
$real_value3 = boolval($this->rename_variables3);
$real_value4 = boolval($this->rename_variables4);
$real_value5 = boolval($this->rename_variables5);
```

Yii2 form rules and validators don't make things easier in this case because I have to convert to boolean type anyway myself.

A proposal is to make it easier for PHP devs, to get either ```true``` or ```false``` directly from the form field by introducing an extra flag into the validator

```php
[["rename_variables"], "boolean", 'boolval'=> true ],
```

Setting a ```boolval``` to true, would run a ```boolval()``` function on the form submission data and store it in the form field result.

**Comment by bizley** [comment]
What you need is `[['rename_variables'], 'boolean', 'falseValue' => false, 'trueValue'=> true, 'strict' => true]`.

**Comment by PELock** [comment]
No, that doesn't work, because the HTML form fields doesn't have true/false values. Try it.

**Comment by bizley** [comment]
Yes, and that is why this validator uses strings for that reason. I'm not sure what you want to do here, you said you wanted to get booleans but then admitted that HTML cannot produce them. Validator takes any boolean-ish value and loosly compare it to `true`/`false` (unless you set it to `strict` mode). If you want some non-standard values as `true`/`false` you set it as well. That's it.

**Comment by PELock** [comment]
It's useless from the PHP programming point of view, I want booleans returned not strings '1' and '0', the form members are booleans, the rules expect booleans, but the returned values are strings! Booleans in PHP are true or false, simple as that, is Yii2 a PHP framework or not? Why not make it easier for developers and return true or false or force them to add artificial conversions with boolval() for every boolean expected form field???

**Comment by bizley** [comment]
What do you mean by "returned"? HTML form produces strings and a validator should not modify the value of the data that is a subject of validation (of course `FilterValidator` is not a real validator).

**Comment by PELock** [comment]
No? How about string validator that trims the white spaces? It modifies the output.

Can't you see the inconsistency in this particular validator?

I mean, double validator makes sure the number is double, integer validator makes sure the value is in fact an integer, but boolean validator makes sure the returned values are STRINGS!

**Comment by My6UoT9** [comment]
Are u sure this also also '0' and '1'? From reading source it shouldn't.

`[["rename_variables"], "boolean", 'falseValue' => false, 'trueValue'=> true ],`

**Comment by samdark** [comment]
```php
['rename_varianles', 'boolval'],
```

That would convert your values.

**Comment by bizley** [comment]
@PELock I'm not sure why you are so upset about this, there is no need for screams here. `string` validator is not trimming values, `trim` does but this is `FilterValidator` which is not a validator in reality. `integer` validator is in fact a `NumberValidator` with `integerOnly` option set to `true` (this behaves almost like `strict` in `BooleanValidator`) and `number` validator itself works on strings as well.

`BooleanValidator` has been created to handle validation of data coming from HTML forms and we already agreed that you cannot use `true` and `false` there. You should not expect to get `true` when you send `"1"`. At the same time this validator can handle real boolean values coming from 3rd party API for example and you should set it with `strict` option in that case.

As samdark mentioned you can add a filter "validator" in your rules that will handle the input the way you want.

As this is becoming longer and longer let's continue the discussion at the forum if you would like to continue it at all.

**Comment by PELock** [comment]
The `strict` flag doesn't enforce conversion in boolean validator, it enforces the HTML field values try it.

I mean, I would like Yii2 be as friendly and usable as possible, why not make it easier for PHP devs?

**Comment by PELock** [comment]
> ```
> ['rename_variables', 'boolval'],
> ```
> 
> That would convert your values.

Would that run along the boolean validator?

**Comment by bizley** [comment]
Just put at before the line with `boolean` rule, it will convert the input values (since it's not real validator as I said).

**Comment by PELock** [comment]
Meh, ok, but I thought an extra flag to boolean validator would be better than a separate 'filter' validator, just like trim validator for strings... anyway thnx guys.
