### ISSUE TITLE
update composer asset plugin link

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2#18792]
### What steps will reproduce the problem?
https://www.yiiframework.com/doc/guide/2.0/en/structure-extensions#dependencies
in docs https://github.com/francoispluchino/composer-asset-plugin
### What is the expected result?
https://github.com/fxpio/composer-asset-plugin

**Comment by bizley** [comment]
Closed via https://github.com/yiisoft/yii2/commit/88e942821c0dcfd70438814b4222c6569807c673
