### ISSUE TITLE
fix core framework code style link

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2#18801]
### What steps will reproduce the problem?
https://www.yiiframework.com/doc/guide/2.0/en/structure-extensions#releasing
Now https://github.com/yiisoft/yii2/wiki/Core-framework-code-style

### What is the expected result?
https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md

**Comment by bizley** [comment]
Closed via https://github.com/yiisoft/yii2/commit/ca50dd0bc7813a193878920c1db25375e59783a8
