### ISSUE TITLE
Why should `CHANGELOG.md` be updated manually, although there are methods that do it automatically?

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#18815]
Class `build/controllers/ReleaseController` have `*Changelog` methods, why need update manually `CHANGELOG.md`?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | any
| Operating system | any

**Comment by bizley** [comment]
Because it is more reliable that depending on the commit message or anything like that done prior to the changelog update.

**Comment by WinterSilence** [comment]
@bizley `ReleaseController` runs on release. If it's not useful why it's not removed?

**Comment by bizley** [comment]
ReleaseController does a bunch of things and it's definitely useful.

**Comment by WinterSilence** [comment]
@bizley 
> ReleaseController does a bunch of things and it's definitely useful.

I told about `*Changelog` methods.

I'm can add job to workflow to auto update `CHANGELOG.md` (if PR don't do it) on merge PR.

**Comment by bizley** [comment]
It sorts changelog lines according to the agreed schema. And what kind of auto updates in the changelog do you propose?

**Comment by WinterSilence** [comment]
@bizley [release action](https://github.com/marketplace/actions/changelog-ci)

Action on merge PR:
~~~yml
on pull_request_review:
  types:
    - submitted
  branches:
    - master
jobs:
  update-changelog:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved' }}
    steps:
      - name: Adds PR info, if record not found in CHANGELOG.md
        run:  |
           build/update-changelog
~~~

**Comment by samdark** [comment]
Where would it take changelog text from?

**Comment by WinterSilence** [comment]
@samdark `"{$pr->type} #{$pr->id}: {$pr->title} ({$pr->author})"`, `$pr->type = in_array('type:bug', $pr->labels) ? 'Bug' : 'Enh';`

**Comment by samdark** [comment]
Not bad. If it would check for line existence and won't modify it, that may work.

**Comment by WinterSilence** [comment]
@samdark 
~~~php
$log = file_get_contents($this->getFrameworkChangelog());
preg_match_all('/^-\s+(Chg|Enh|Bug|New)\s+#(\d+)/ium', $log, $ids, PREG_SET_ORDER);
$ids = array_column($ids, 2);
if (!in_array($pr->id, $ids)) {
   // add PR to changelog
}
~~~

**Comment by bizley** [comment]
I disagree. It will require updating the line anyway when the original title become obsolete during the discussion on the PR. As I said it should NOT depend on the commit (or PR title).

**Comment by samdark** [comment]
Well, yes. Thinking about it more. This description is better to be done with some extra thinking.

**Comment by WinterSilence** [comment]
@bizley message appended:
- only if it not defined in PR
- on merge PR to `master` branch
- we can add part "Changelog message" to PR template

> As I said it should NOT depend on the commit (or PR title).

In most cases, log message similar PR title. It's optional tool for lazy devs like me (:

**Comment by samdark** [comment]
We won't accept lazy messages anyway :)

**Comment by WinterSilence** [comment]
@samdark you already accept such messages and not only mine:

> Enh #18724: Allow jQuery 3.6 to be installed (marcovtwout)

PR title:
> Allow jQuery 3.6.0 to be installed

**Comment by samdark** [comment]
That's an example of a good message and a good title from a core team member. Usually it's like https://github.com/yiisoft/yii2/pull/18803

**Comment by WinterSilence** [comment]
@samdark no matter, PR title copied to changelog "as is". Some PRs contains complex changes and you can`t declare it all in short message. If users want explore it, they can find details in PR description and code diff.

**Comment by samdark** [comment]
It matters. Currently changelog is pretty much readable without going to each PR for details and reading the code. I don't want to lose that.

**Comment by WinterSilence** [comment]
@samdark It's don't do it less readable and you can do more readable PR's titles.
