### ISSUE TITLE
YII_TEST_ENV breaks the test

### ISSUE THREAD

**Issue by mootensai** [yiisoft/yii2#18810]
### What steps will reproduce the problem?
- Set YII_ENV to 'test'.
- run acceptance test by Codeception

### What is the expected result?
Run the application normally with test development.

### What do you get instead?
```
Exception 'yii\base\ExitException' with message '' 

in myFolder/vendor/yiisoft/yii2/base/Application.php:666

Stack trace:
#0 myFolder/vendor/yiisoft/yii2/base/Application.php(404): yii\base\Application->end(0, NULL)
#1 myFolder/web/index.php(15): yii\base\Application->run()
#2 {main}
```

### Additional info

It's working normally after I comment these lines in https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L665
```
if (YII_ENV_TEST) {
    throw new ExitException($status);
}
```
I checked the `$status`, and the value is `0`. It should be normal.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42
| PHP version      |  7.4.21
| Operating system | Mac OS Big Sur 11.5

**Comment by bizley** [comment]
So everything was ok untill you commented out the `if` statement? So why did you do it?

**Comment by samdark** [comment]
@bizley it's other way around it seems.

**Comment by samdark** [comment]
@mootensai was it a tests set of basic/advanced app template or something else?
