### ISSUE TITLE
when kill the BD connection yii\db\Connection  getIsActive still return true

### ISSUE THREAD

**Issue by jiangyixiang** [yiisoft/yii2#18827]
### What steps will reproduce the problem?
if i kill the BD connection 
yii\db\Connection  getIsActive()  
still return true

### What is the expected result?
return false

### What do you get instead?
return true

### Hope
if throw yii\db\Exception  and message is 'MySQL server has gone away'
should close()  to set pdo null

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | 7.2.31
| Operating system | centOS 7

**Comment by samdark** [comment]
Connection could be killed for different reasons and by different sides. If we're going to implement that, the check should issue a real query and catch exception in order to determine if connection is alright.

**Comment by samdark** [comment]
@yiisoft/reviewers what do you think?

**Comment by samdark** [comment]
My opinion is still the same — we should not try to do it.
