### ISSUE TITLE
Quoting the column name "to" does not seem to work

### ISSUE THREAD

**Issue by shamsmm** [yiisoft/yii2#18836]
### What steps will reproduce the problem?
- Create a table with a column named `to`
- Populate that `to` column with some numbers
- Using ActiveRecord/Query or anything get MAX of that column for instance:
`(new \yii\db\Query())->from('table_name')->max('[[to]]')`

### What is the expected result?
Get the maximum number

### What do you get instead?
A Database Exception – yii\db\Exception
```
The SQL being executed was: SELECT MIN(to) FROM `table_name`
```

### Additional info
_Notice: the `MAX` was changed onto `MIN` for an unknown reason & `to` was unquoted._
This problem doesn't happen with other keywords like `on`, `child` etc.. It only happens with `to`.
I tried absolutely everything, running raw query, using quoteColumn methods and everything but without any success.

Code used:
```
var_dump((new \yii\db\Query())->from('t_campaign')->max("[[to]]"));
```

Error produced:

![Screenshot from 2021-08-15 16-13-41](https://user-images.githubusercontent.com/40241456/129481424-0d8a44f3-ed64-4ae0-8a9f-78f08c7bdec5.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | 7.4.19
| Operating system | Fedora 34

**Comment by samdark** [comment]
> Notice: the MAX was changed onto MIN for an unknown reason & to was unquoted.

Are you absolutely sure you change code in a right place? Try changing table name to `absolute_garbage` and post the error please.

**Comment by shamsmm** [comment]
> > Notice: the MAX was changed onto MIN for an unknown reason & to was unquoted.
> 
> Are you absolutely sure you change code in a right place? Try changing table name to `absolute_garbage` and post the error please.

Unfortunately the error would relate that this table is not in my database, before producing an error due to the syntax and not quoting. I will update my issue now with the real code with the real error attached as an image.
