### ISSUE TITLE
Method ReflectionType::getName() not supported in PHP 8.0

### ISSUE THREAD

**Issue by bichomen** [yiisoft/yii2#18842]
In vendor/yiisoft/yii2/base/Controller:

![image](https://user-images.githubusercontent.com/20316285/129767121-9889f38a-8108-446e-95d3-1855facbcac6.png)

getName undefined

In the PHP documentation:
https://www.php.net/manual/en/class.reflectiontype.php

the second comment indicates that in PHP 8.0 it does not exist **getName()**

Yii version 2.0.43
PHP 8.0 
Ubuntu 20

**Comment by bizley** [comment]
In most cases it does not break things since `ReflectionType` is `ReflectionNamedType` but it will in case of union types. Needs to be addressed.
