### ISSUE TITLE
The Logger is impossible to configure

### ISSUE THREAD

**Issue by lexizz** [yiisoft/yii2#18840]
If `YII_DEBUG` is `true`, the `yii2/log/Logger.php` is impossible to configure.

1. In `Application::bootstrap()` `Yii::debug()` is called and is creating a default `Logger` w/o settings. Then it writes it into `BaseYii::$_logger`. 
2. Next, Logger isn't overwritten and it's used everywhere.

![image](https://user-images.githubusercontent.com/22645458/129612034-0b6249e7-319b-4a28-b4a8-0b9315ec339e.png)

### What steps will reproduce the problem?

You have to configure a log inside an application's configuration and set `'profilingAware' => true,`
![image](https://user-images.githubusercontent.com/22645458/129608642-c0baa1d2-f758-40cb-a173-f110cd133995.png)

### What is the expected result?
If we configure the Logger, it will be used in the entire application.

### What do you get instead?
Inside `yii2/log/Dispatcher.php`, in the moment of call `setLogger`, you have to add `Yii::setLogger($value);`.
![image](https://user-images.githubusercontent.com/22645458/129612288-5bd4b31f-e5a5-4eec-84ae-e9ff266d33c9.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4.20
| Operating system | Linux 5.13.8-1-MANJARO x86_64

**Comment by lexizz** [comment]
I  solved this issue, but I couldn't push my edits.
![image](https://user-images.githubusercontent.com/22645458/129626954-f2adcd1d-801c-41b3-b7ee-8ebeadb8d2d3.png)

**Comment by samdark** [comment]
@lexizz you need a fork. See https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md
