### ISSUE TITLE
Call to undefined method ReflectionUnionType::isBuiltin()

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#18859]
### What steps will reproduce the problem?
```php
class SomeController extends Controller {
      public function actionSomething(null | string | bool $var = false): string
      {
          
      }
}
```

### What do you get instead?
Exception: `Call to undefined method ReflectionUnionType::isBuiltin()`
In
https://github.com/yiisoft/yii2/blob/83b4191e6c3e818c1853ed2ed76852222998d0eb/framework/web/Controller.php#L180

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      |  8.0.9
| Operating system | Docker Alpine

Seems to be an equal issue as https://github.com/yiisoft/yii2/issues/18624

**Comment by bizley** [comment]
Also (semi)related to #18842

**Comment by tomaszkane** [comment]
This problem still occurs.
I have route: `'GET media/<id:[\w\.-{}]+>/thumbnail' => 'file/file/get-thumbnail',`
and controller action:
```
public function actionGetThumbnail($id, int $w = null, int $h = null, int $q = null, bool $a = false, bool $u = false): Response { /* ... */ }
```
and it works, but after add type for first argument:
```
public function actionGetThumbnail(int|string $id, int $w = null, int $h = null, int $q = null, bool $a = false, bool $u = false): Response { /* ... */ }
```
got
```
Error
Call to undefined method ReflectionUnionType::isBuiltin()
in /var/www/alterpress/vendor/yiisoft/yii2/web/Controller.php:148
```

@bizley

**Comment by bizley** [comment]
@tomaszkane please check if my solution fixes the problem.

**Comment by tomaszkane** [comment]
> @tomaszkane please check if my solution fixes the problem.

Yes, after adding this IF no error occurs.
https://github.com/yiisoft/yii2/pull/19849/files#diff-376f28d474557f6379aec29487ba11c2f08fc153822735d7a31e417bbc13c330R144
