### ISSUE TITLE
CheckboxColumn: check-all checkbox must be checked on page load if all row checkboxes are checked 

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#18867]
```PHP
<?= \yii\grid\GridView::widget([
    'columns' => [
        [
		'class' => \yii\grid\CheckboxColumn::class,
		'checkboxOptions' => function () { return ['checked' => true];},
	],
        // ...
    ],
]) ?>
```
In the example above when the page is loaded all checkboxes in the table will be checked except the master "check-all" checkbox in table header. This checkbox must be checked too.

The best (or at least the simplest) solution in my opinion would be to just check the check-all checkbox using JS on page load. Could be implemented in assets\yii.gridView.js as follows:

Original code:
```PHP
        setSelectionColumn: function (options) {
            // ...
            initEventHandler($grid, 'checkRow', 'click.yiiGridView', inputsEnabled, function () {
                var all = $grid.find(inputs).length == $grid.find(inputs + ":checked").length;
                $grid.find("input[name='" + options.checkAll + "']").prop('checked', all).change();
            });
        },
```
Fixed code:
```PHP
        setSelectionColumn: function (options) {
            // ...
            var handler = function () { // Handler code is the same.
                var all = $grid.find(inputs).length == $grid.find(inputs + ":checked").length;
                $grid.find("input[name='" + options.checkAll + "']").prop('checked', all).change();
            };
            initEventHandler($grid, 'checkRow', 'click.yiiGridView', inputsEnabled, handler);
            handler(); // Simply call the original handler on page load.
        },
```

**Comment by PowerGamer1** [comment]
The solution I proposed in my original post fails some tests. This should be handled by someone more knowledgeable in JavaScript and GridView mechanics.

**Comment by AndreyPootMay** [comment]
Let me check

**Comment by PowerGamer1** [comment]
I pushed new PR. The tests are now properly fixed. Additionally, another issue with checkboxes in GridView is fixed: clicking checkboxes will not trigger "change" event for other checkboxes that do not change their state.

**Comment by PowerGamer1** [comment]
There was yet another issue with "check all" checkbox when some data row checkboxes are disabled - it was not being checked when last non-checked data row checkbox is clicked. This is also fixed now in my PR.
