### ISSUE TITLE
`yii\base\Controller::createAction()`  ignores dynamic inline actions

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#18875]
### What steps will reproduce the problem?
Add behavior with inline action(`public function actionBehavior()`) to controller(`$controller`).
Create action: `$action = $controller->createAction('behavior');`

### What is the expected result?

`$action` is `InlineAction('behavior', $controller, 'actionBehavior')`;

### What do you get instead?

`$action` is `null`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | any
| Operating system | any

**Comment by samdark** [comment]
Do you really add actions via behaviors? Initially behaviors were not created for that. They are mainly to handle events.

**Comment by samdark** [comment]
If you want actions like that, can't it be done via traits instead?

**Comment by WinterSilence** [comment]
@samdark In my case uses only magic/dynamic actions, for example: `actionCreate` have alias `actionAdd` for compatible with old api. Why do you limit developers to scope of your/my applications?

**Comment by WinterSilence** [comment]
@samdark https://github.com/yiisoft/yii2/pull/18876/files

**Comment by bizley** [comment]
We could have it added but also it would have to be included in console actions detection.

**Comment by WinterSilence** [comment]
@bizley console commands extends `yii\base\Controller`

**Comment by bizley** [comment]
Yes. I'm referring to [that feature](https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/HelpController.php#L76).

**Comment by WinterSilence** [comment]
@bizley You can talk about this with @samdark - he is disagree to add common methods for this. https://gist.github.com/WinterSilence/6079451c719bdc49d5aea2578e37feaf
