### ISSUE TITLE
[Not sure it's bug] Affecting wrong name parameter in URL - HTML::a() method.

### ISSUE THREAD

**Issue by Bikiio** [yiisoft/yii2#18891]
### What steps will reproduce the problem?
I tried to CRUD on a "Post" model class (blog article-like).
Post identifier is named "post-id", is integer, primary key, auto-incremented in MariaDB.

1) Generate model and CRUD scripts using Gii.
2) Create a new post.
3) Click on "modify" button on the refreshed post view.

### What is the expected result?
To be on the "modify" post view.

### What do you get instead?
"400 Bad request - Missing required parameters: post_id"

### Additional info
view.php file generated by Gii
```
<div class="posts-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'post_id' => $model->post_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'post_id' => $model->post_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'post_id',
            'post_title',
            'post_content:ntext',
            'author_id',
        ],
    ]) ?>

</div>
```
The URL generated by this view : 

> http://localhost:8080/web/index.php?r=post%2Fupdate&id=4

We can see that it's the wrong parameter name here. If I change 'id' to 'post_id' I get the good view.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4.23 
| Operating system | Fedora 34

**Comment by samdark** [comment]
Are you sure that `<?= Html::a('Update', ['update', 'post_id' => $model->post_id], ['class' => 'btn btn-primary']) ?>` is generating the link you're clicking?

**Comment by Bikiio** [comment]
> Are you sure that `<?= Html::a('Update', ['update', 'post_id' => $model->post_id], ['class' => 'btn btn-primary']) ?>` is generating the link you're clicking?

Not hundred percent sure. I actually test this framework but I guess it is. 
You can easily reproduce this by yourself using Gii to generate all the scripts I have on my workstation. If you do this let me know if it works fine by your side.

**Comment by samdark** [comment]
Well, the code

```php
<?= Html::a('Update', ['update', 'post_id' => $model->post_id], ['class' => 'btn btn-primary']) ?>
```

Is very unlikely to generate an URL with `id` instead of `post_id` as a parameter.

**Comment by Bikiio** [comment]
Yes, I think so. I'll investigate about this tomorow morning then I'll come back there. Thank you for helping.

**Comment by Bikiio** [comment]
Ok so I'm actually investigating around GridView, ActionColumn, etc... It's probably a misunderstanding on my side. I stay tuned.

**Comment by Bikiio** [comment]
I finally found what I wanted to. It's not a Gii bug. I didn't know how to set up the good parameters to `GridView::Widget`.
With the good combination of `buttons` and `urlCreator` and a bit of research I did it well. 
Thank you @samdark for helping and sorry guys for calling it a bug.
