### ISSUE TITLE
csrf validation not working when use isPost 

### ISSUE THREAD

**Issue by PouriaDiesel** [yiisoft/yii2#18893]
### What steps will reproduce the problem?

Hi.When we use `if(Yii::$app->request->isPost)` in controllers like below, in this block Csrf Token not validated automatically and you must validate it manually.   

    if (Yii::$app->request->isPost){    
          /*csrf not validated here automatically by framework in this code block*/ 
          if ($params = Yii::$app->request->post()) {
             /*manual validation*/
            if (!Yii::$app->request->validateCsrfToken($params['_csrf'] ?? ''))
                    throw new ForbiddenHttpException('invalid request');
            ...
           return '200,ok';
          }
          else
            throw new BadRequestHttpException('post parameters couldnt be empty');
    }else
        throw new MethodNotAllowedHttpException('only post allowed');

I want to see is there a better way to write this code without manual csrf validation or not? 
### What is the expected result?

I must get #400,Bad Request.

### What do you get instead?

In my ajax request I enter`_csrf: 1234`  then I got `200,ok`!;

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4
| Operating system | windows 7

**Comment by bizley** [comment]
I'm not sure if I understand - why do you think it should be validated automatically in that block?

**Comment by PouriaDiesel** [comment]
> I'm not sure if I understand - why do you think it should be validated automatically in that block?

I understand your feel about this issue and I know it isn't a real issue but I'm only suggest that Yii must validate post requests before calling isPost and similar properties and functions then checks isPost and if post request isn't valide throw 400 or 403 automatically.

**Comment by bizley** [comment]
I disagree. This is a matter of business logic whether to validate CSRF or not when checking if request method is POST and we cannot force it. You have the tools prepared for that check and you are using them in your example.
