### ISSUE TITLE
Minor: wrong PHPDoc info for getBodyParams()

### ISSUE THREAD

**Issue by troncz** [yiisoft/yii2#18908]
_This is very minor but it threw me off track for a bit. It made me believe it was not possible to directly get JSON data from a REST request as an object. I converted to objects in my code adding an unnecessary step._

### Description of the problem?

The return type for the `yii\web\Request` method `getBodyParams()` in the PHPDoc is `array`. However, the 'yii\web\JsonParser' can be configured (property `asArray`) to return objects instead of arrays. This works fine but contradicts the PHPDoc for the `getBodyParams()` method.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      |  7.4
| Operating system | Mac OSX

**Comment by samdark** [comment]
Yeah, should be fixed. Would you please make a pull request?

**Comment by mariosimao** [comment]
I've created a pull request for this doc issue.
