### ISSUE TITLE
MessageSource::getMessageFilePath() - filename injection 

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii2#18912]
Yii::$app->language can contain any string, and this string is directly passed into MessageSource::getMessageFilePath() and used in filename without any validation:

https://github.com/yiisoft/yii2/blob/435b6dc732d768ca25430b2059ca724a99f3102e/framework/i18n/PhpMessageSource.php#L135

That could be a potetial security issue:

`The message file for category 'yii' does not exist: /var/www/app/vendor/yiisoft/yii2/messages/"><script >alert(String.fromCharCode(88,83,83))</script>/yii.php Fallback file does not exist as well: /var/www/app/vendor/yiisoft/yii2/messages/">/yii.php`

**Comment by bizley** [comment]
Is there any place where end user could provide the language directly and that message would pop up? I cannot find such case.

**Comment by WinterSilence** [comment]
Yii don't have "fools protection"

**Comment by uaoleg** [comment]
@bizley the case is any website that provides language selection on UI
@WinterSilence it's not obvious at all that I have to escape somehow the language name

**Comment by WinterSilence** [comment]
@uaoleg you must escape ANY user data - it's contained in ANY security guide

**Comment by uaoleg** [comment]
@WinterSilence no, I should not. For example if user has name `O'Reilly` I won't escape it to save in DB, I will save it as is.

**Comment by WinterSilence** [comment]
@uaoleg read more about second-order SQL injection
I don't know if I translated it correctly, it's called in Russian: SQL-инъекция второго порядка

**Comment by bizley** [comment]
> the case is any website that provides language selection on UI

Since the framework is not using that value (I mean "provided by user") directly we rely on the developer to validate it when passing to the component.

**Comment by uaoleg** [comment]
@bizley it's not obvious that this property is used as a part of filepath. I'll create a simple PR which will fix this issue

https://github.com/yiisoft/yii2/blob/435b6dc732d768ca25430b2059ca724a99f3102e/framework/base/Application.php#L116

**Comment by bizley** [comment]
Hm, ok, please do. Maybe we need to add some more clarification for that.

**Comment by samdark** [comment]
We should escape it. Something like `preg_replace('/[^\w_-]/', '_', $language)` should be sufficient.

**Comment by uaoleg** [comment]
Created a PR https://github.com/yiisoft/yii2/pull/18913

**Comment by WinterSilence** [comment]
@samdark class must generate error instead escape: `if (preg_match('/[^a-zA-Z_-]/', $language) === 1) { throw new ... }`

**Comment by samdark** [comment]
Agree 👍

**Comment by samdark** [comment]
@uaoleg would you please adjust the pull request? It should throw `\InvalidArgumentException`.

**Comment by uaoleg** [comment]
@samdark done
