### ISSUE TITLE
dateFormat - weird problem with September

### ISSUE THREAD

**Issue by omzy** [yiisoft/yii2#18915]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4
| Operating system | Linux

In my `web.php` config file I set up `formatter` as follows:

```
$config = [
    'language' => 'en-GB',
    'timeZone' => 'Europe/London',

    'formatter' => [
        'class' => 'yii\i18n\Formatter',
        'dateFormat' => 'dd MMM y',
        'datetimeFormat' => 'dd MMM y HH:mm',
        'defaultTimeZone' => 'Europe/London',
    ],
];
```
In my view file I output the date as follows:

`<?php echo Yii::$app->formatter->asDateTime('now'); ?>`

This SHOULD output as `29 Sep 2021 23:00`

Instead, it outputs as `29 Sept 2021 23:00` (4 letters for month).

This ONLY happens with September. Here is another example in GridView:

![image](https://user-images.githubusercontent.com/8927010/135355448-331a93c2-51b2-45dc-b20e-ce75de21e52a.png)

The same issue occurs if I use the `php:` prefix for specifying the format, however if I use the native PHP `date` function:

`<?php echo date('d M y H:i'); ?>`

I get the correct 3 letter month.

Interestingly, this only happens on a shared hosting server, which indicates it could be to do with the build of PHP / Intl. But with it being a shared hosting server, there isn't much I can do on a server level.

This wouldn't generally be an issue, but I am using `DateValidator::TYPE_DATE` for input validation and when I enter "Sep", it fails validation unless I change it to "Sept".

**Comment by bizley** [comment]
Interesting. All I could find about that is only [one case at SO](https://stackoverflow.com/questions/17087112/php-date-formatting-can-i-use-sept-instead-of-sep). This might be the thing with the ICU version that you happened to have. Just to make sure you could check direct call to `IntlDateFormatter` and see what is the output for `MMM` but for sure Yii is not doing anything with that on its own.
