### ISSUE TITLE
Problems with `Module::getControllerPath()`

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#18960]
`Module::getControllerPath()` return path based on namespace, it's not correct in some cases:

- PSR module, for example, module controllers in `src/controllers/`
- Module defined in application, for example, developer not set path alias for module

We can't set controller's path for module directly.
I vote to fix `getControllerPath()`:
- method return new public property `Module::$controllerPath`
~~~php
private $_controllerPath;

public function getControllerPath()
{
      if ($this->_controllerPath === null) {
           $this->_controllerPath = parent::getControllerPath();
      }

      return $this->_controllerPath;
}

public function setControllerPath($path)
{
      $realpath = Yii::getAlias($path);
      if (!is_dir($realpath)) {
            throw new InvalidArgumentException("Controller path '$path' not exists")
      }
      $this->_controllerPath = $realpath;
}
~~~
**or**
- if path alias based on namespace not found, then method return path based on directory of module class:
~~~php
public function getControllerPath()
{
      $path = Yii::getAlias('@' . str_replace('\\', '/', $this->controllerNamespace), false);
      if ($path === false) {
           $path = dirname($this->getReflection()->getFilename()) . DIRECTORY_SEPARATOR . 'controllers';
      }

      return $path;
}
~~~

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | any
| Operating system | any

**Comment by samdark** [comment]
So the behavior stays the same unless `Module::$controllerPath` is defined explicitly?

**Comment by WinterSilence** [comment]
@samdark no second version change behavior, see code in issue
