### ISSUE TITLE
The MailerInterface is too restrictive for Psalm

### ISSUE THREAD

**Issue by olleharstedt** [yiisoft/yii2#18998]
### What steps will reproduce the problem?

Changing any property of the mailer module, like

```php
            \Yii::$app->mailer->htmlLayout = false;
```

Using this config

```
        'mailer' =>
            defined('YII_ENV') && YII_ENV == 'test' ?
                ['class' => 'DummyMailer'] :
                ['class' => 'yii\swiftmailer\Mailer'],
```

But the faulty part is the docblock in Yii application class:

    * @property-read \yii\mail\MailerInterface $mailer The mailer application component. This property is                                                                                                       

Changing MailerInterface to BaseMailer fixes the error.

### What is the expected result?

Psalm says it's OK

### What do you get instead?

Psalm error, interfaces have no properties (which is true, the Yii 2 phpdoc is too restrictive, or the interface is too restrictive and doesn't allow changing any property or config).

**Comment by WinterSilence** [comment]
@olleharstedt nope, generate stub for your application classes

**Comment by mikk150** [comment]
There are many more mailers existent in the universe, some that really do not have `htmlLayout`, but have other properties, what would you do then?
Interfaces only describe what implementations HAVE to implement

what do you do when we have multiple mailers
1. where you have properties to change
2. where you do not have properties to change?


Long story short - do not do what you are doing now, do not use DummyMailer in tests, you can use Swiftmailer perfectly fine in tests, just in test you have to configure not to send emails out(tho it really should be default in development and testing envs anyway, so comparing `YII_ENV` constant should not even be nessecary

**Comment by olleharstedt** [comment]
> There are many more mailers existent in the universe, some that really do not have htmlLayout, but have other properties, what would you do then?

Well, obviously the interface should provide a way to inject a config data object, or at least have a "setConfig()" method. The interface is waaay too thin as defined now, you can't do anything with it.

**Comment by mikk150** [comment]
> > also do not change mailer config programmatically.. If you do need different layouts, I would suggest different mailer components
> 
> Yeah, this is the only solution available to us now. neutral_face

Why I would not do that is that what if I need to send multiple mails, you now need to set the config back to what it was before in order to be in known state.. even with `setConfig()` you have to change things back to known state.

**Comment by olleharstedt** [comment]
Wait, compose already takes an array to define the view, like ['text' => 'text_template'], which would work for us. I'll close this issue.

**Comment by mikk150** [comment]
> Wait, compose already takes an array to define the view, like ['text' => 'text_template'], which would work for us. I'll close this issue.
> 
> So in a sense, there's already an implied MailerConfig object. ;) But with arrays.

nope, that is a template not layout

**Comment by olleharstedt** [comment]
Gah
