### ISSUE TITLE
Unexpected Url::to() behaviour when path contains double slashes.

### ISSUE THREAD

**Issue by briedis** [yiisoft/yii2#19014]
### What steps will reproduce the problem?

`\yii\helpers\Url::to('/some-path/?redirectUrl=://attacker.com', 'https');`

### What is the expected result?

`https://my-domain/some-path/?redirectUrl=://attacker.com`

### What do you get instead?

`https://attacker.com`

### Additional info

The issue is how ensureScheme method parses the url. It looks for double slashes anywhere in the url, which could be in the query parameters added there by an attacker.

`\yii\helpers\BaseUrl::ensureScheme`

```

  if (($pos = strpos($url, '://')) !== false) {
            if ($scheme === '') {
                $url = substr($url, $pos + 1);
            } else {
                $url = $scheme . substr($url, $pos);
            }
        }
```

A typical attack scenario would be when you want to generate an absolute URL from a path that comes from the user. (e.g. a redirect URL after a successful login)

The solution would be to maybe parse the url natively, using parse_url(), so it is split up in correct components - host, scheme, query, etc.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      |  8.0

**Comment by WinterSilence** [comment]
you pass wrong link, query data must be encoded, see [RFC3986](http://www.faqs.org/rfcs/rfc3986)

**Comment by virtual-designer** [comment]
@briedis You should use `urlencode()` like this:

```php
\yii\helpers\Url::to('/some-path/?redirectUrl=' . urlencode('://attacker.com'), 'https');
```

And the issue should be gone.

**Comment by samdark** [comment]
Actually yes, the URL parameter value isn't encoded properly when set. Thanks, @WinterSilence, @virtual-designer.
