### ISSUE TITLE
ActionColumn wrong primary key

### ISSUE THREAD

**Issue by migmam** [yiisoft/yii2#19018]
ActionColumn creates wrong urls If the primary key of the table is not named "id"

The source code (ActionColumn.php) shows:

```
public function createUrl($action, $model, $key, $index)
    {
        echo $key;
        echo $index;
        print_r($model);
        if (is_callable($this->urlCreator)) {
            return call_user_func($this->urlCreator, $action, $model, $key, $index, $this);
        }

        $params = is_array($key) ? $key : ['id' => (string) $key];
        $params[0] = $this->controller ? $this->controller . '/' . $action : $action;

        return Url::toRoute($params);
    }
```

So the line $params = is_array($key) ? $key : [**'id'** => (string) $key]; is always creating url with id as parameter.

The workaround that worked for me is:

```
if( isset($model->primaryKey) )
            $params = is_array($key) ? $key : [$model->primaryKey => (string) $key];
 else
            $params = is_array($key) ? $key : ['id' => (string) $key];
```

**Comment by WinterSilence** [comment]
https://github.com/yiisoft/yii2-gii/blob/aceea1b0acf9c838a93da5ff6f33fd195e8bf78e/src/generators/crud/default/views/index.php#L69

**Comment by bizley** [comment]
Yes, as WinterSilence mentioned you can use `urlCreator` to provide your logic for this but indeed IMO we should not hardcode `id` here.

**Comment by softark** [comment]
Because of this issue, **Guide > Getting Started > Generating Code with Gii > Generating CRUD Code** will produce a code that doesn't work. The mentioned section of the Guide uses a sample model that has the primary key named **'code'**.

It's a tragedy for a beginner who follows the tutorial faithfully.

Guide:
https://www.yiiframework.com/doc/guide/2.0/en/start-gii#generating-crud

A forum thread:
https://forum.yiiframework.com/t/bad-request-400-getting-started-tutorial/133341

**Comment by WinterSilence** [comment]
@softark it's fixed in `master` 1 month ago.

**Comment by samdark** [comment]
I'll make a tag as soon as we'll be ready for release.

**Comment by RK-RAJAN** [comment]
what is the solution for it? How to generate PRIMARY KEY instead of ID ?

**Comment by WinterSilence** [comment]
@RK-RAJAN something like this https://github.com/yiisoft/yii2-gii/blob/aceea1b0acf9c838a93da5ff6f33fd195e8bf78e/src/generators/crud/default/views/index.php#L69
