### ISSUE TITLE
 [Composer\Downloader\TransportException]   curl error 60 while downloading https://repo.packagist.org/p2/yiisoft/yii2.json: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jose1894** [yiisoft/yii2#19024]
### What steps will reproduce the problem?

I tried to run composer command composer update 

### What is the expected result?

Install repositories

### What do you get instead?

 [Composer\Downloader\TransportException]
  curl error 60 while downloading https://repo.packagist.org/p2/yiisoft/yii2.json: SSL certificate problem: unable to get local issuer certificate

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |  7.2.25
| Operating system | Windows 10 X64

**Comment by bizley** [comment]
This is not an Yii issue. Read more at https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate and other places.
