### ISSUE TITLE
Cookies are not set on redirect

### ISSUE THREAD

**Issue by Alexysche** [yiisoft/yii2#19026]
This code does not work as expected, cookies are not set.

```php
public function actionTestRedirect()
{
	$cookie =
	[
		'name' => 'name',
		'value' => 'value',
		'expire' => time() + 365 * 24 * 3600,
		'domain' => '.' . $domain
	];

	Yii::$app->response->cookies->add(new Cookie($cookie));

	return $this->redirect('https://site.com/test');
}
```

In the Response class, in the **sendHeaders()** method, sending the cookie goes at the end (call $this->sendCookies()). In the case of a redirect, the **header()** method (in the code above) will be executed and the cookies will not be sent. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 5.6
| Operating system | Windows 7

**Comment by bizley** [comment]
Hm, should the cookie be sent in that case anyway? I'm not sure if it was meant to work like that.

**Comment by WinterSilence** [comment]
`$this->getResponse()->redirect('https://site.com/test')->send();`

**Comment by samdark** [comment]
How do you test it? Do you check headers via curl? Localhost redirect doesn't work with cookies as well as another domain (in some browsers): https://stackoverflow.com/questions/4694089/sending-browser-cookies-during-a-302-redirect
