### ISSUE TITLE
BaseHtml/ActiveField: problem with css classes

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#19022]
1. Methods like as `ActiveField::input*()`  merge classes in wrong order: general classes (`$inputOptions['class']`) appended to user's classes (`$options['class']`) and replaces user's styles.
2. you cant pass `$options['class']` as  `['widget' => ['foo', 'bar']]`
3. if  `$inputOptions['class'] = ['widget' => ' bar foo']` and  `$options['class'] =  'foo baz'`, than generates list with duplicates: `foo baz bar foo`

**Comment by bizley** [comment]
Is this related to #19012 ?

**Comment by WinterSilence** [comment]
@bizley these are 4 different problems, I'm just too lazy to creates separate issues for each

**Comment by bizley** [comment]
Well, you have to. Please do.

**Comment by WinterSilence** [comment]
@bizley 👍🏻 I already wrote that I will not do it, but I'm send fix #19013
