### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by sartor** [yiisoft/yii2#19034]
No there are many deprecations and errors. Is there any plans to fix it for PHP 8.1?
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 8.1
| Operating system | Linux

**Comment by bizley** [comment]
We will try to fix everything as soon as possible. Are there any problems now that cause problems using Yii?

**Comment by sartor** [comment]
`PHP Fatal error:  During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of yii\caching\Cache::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/sartor/projects/an/vendor/yiisoft/yii2/caching/Cache.php:523`

**Comment by sartor** [comment]
And there is another problem with `codeception/module-yii2`, it requires only php 8.0 now (<8.1)

**Comment by sartor** [comment]
I've create minor PRs with added attributes:
https://github.com/yiisoft/yii2/pull/19037
https://github.com/yiisoft/yii2/pull/19038

**Comment by achertovsky** [comment]
> `PHP Fatal error: During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of yii\caching\Cache::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool`

facing the same now.

**Comment by samdark** [comment]
Watch https://github.com/yiisoft/yii2/pull/19041.
