### ISSUE TITLE
Captcha client-side validation

### ISSUE THREAD

**Issue by sm2017** [yiisoft/yii2#19033]
Yii generates a hash code that can be used for client-side validation. is it safe?
A hacker can easily check the hash code and find the captcha in client-side by brute-forcing and bypass the captcha

**Comment by bizley** [comment]
Depends on the level of safety you are looking for. Like with everything else.

**Comment by sm2017** [comment]
@bizley how can I hide the hash code to the client side?

**Comment by bizley** [comment]
How is it exposed in your case? Because it should not be.

**Comment by sm2017** [comment]
@bizley if it is not exposed, How the client validate the captcha?

**Comment by bizley** [comment]
You can switch off client validation. Remember that captcha should not be treated as an ultimate safety precaution.
