### ISSUE TITLE
ORM, save/insert/update methods not throws PDOException for mssql 

### ISSUE THREAD

**Issue by xpohoc69** [yiisoft/yii2#19040]
I use mssql, version 14.0.3223.3. My config ```'dsn' => 'dblib:version=7.2;host=10.199.??.???;dbname=web_trunk;charset=utf8'```, ```'driverName' => 'mssql'```
Code for example
![image](https://user-images.githubusercontent.com/10045926/142874222-2a1f5d7a-f96e-4931-9e83-dd3fe736b63c.png)
IframeAnalytics has fk constraint. In example I set not exists value for iframe_key. I must get PDOException "Foreign key violation". But it is not thrown.
![image](https://user-images.githubusercontent.com/10045926/142874726-ba2194ca-bf5a-4fed-8cd7-7ecd51577c83.png)
I tried to rewrite code to query builder. And it worked.
![image](https://user-images.githubusercontent.com/10045926/142875432-01033ec3-5cb4-44d3-8919-a84fdec17d3e.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4.13
| Operating system | Windows 10, docker container, php:7.4-fpm

**Comment by darkdef** [comment]
Try change mode of PDO::ATTR_EMULATE_PREPARES in your connection

**Comment by xpohoc69** [comment]
> Try change mode of PDO::ATTR_EMULATE_PREPARES in your connection

@darkdef not, it does not work

**Comment by WinterSilence** [comment]
@xpohoc69 https://github.com/yiisoft/yii2/blob/17aa0e40c1af579ac2ee348ffce59a201185c109/framework/db/Connection.php#L259 + you skip validation

**Comment by xpohoc69** [comment]
@WinterSilence how I said before -- emulatePrepare did not help in my case. And validation is not a problem

**Comment by WinterSilence** [comment]
@xpohoc69
> how I said before

I'm did not know how you tried set `PDO::ATTR_EMULATE_PREPARES`
> And validation is not a problem

QueryBuilder use temp table: https://github.com/yiisoft/yii2/blob/17aa0e40c1af579ac2ee348ffce59a201185c109/framework/db/mssql/QueryBuilder.php#L506
query not generate exception because fk constraints aren't enforced on temporary tables

**Comment by xpohoc69** [comment]
@WinterSilence problem because ```OUTPUT INSERTED.*``` example:
![image](https://user-images.githubusercontent.com/10045926/143553135-fc39c713-b13a-4c3f-9237-6de6ac71f20e.png)

```OUTPUT INSERTED``` is used inside ORM, then it calls insert() method of yii\db\mssql\Scheme class

**Comment by WinterSilence** [comment]
@xpohoc69 you grab part of current SQL - it's not right. I think there were reasons for using temporary tables.  why you don't want use validation for check data?

**Comment by xpohoc69** [comment]
@WinterSilence I dont want to rely only on validation. I want to be sure, if I forgot some validation my DB return me exception and my code will stop to execute

**Comment by WinterSilence** [comment]
@xpohoc69 no problem, find solution how get "last insert id" without temp table and worked at parallel process/queries

**Comment by samdark** [comment]
@xpohoc69 does it work with earlier releases of Yii2?

**Comment by samdark** [comment]
As @WinterSilence explained, it can't be fixed unless we choose another way to do inserts with "last insert id".

**Comment by xpohoc69** [comment]
@samdark I don't know solution for now. I will try to find it after new year
