### ISSUE TITLE
Arrow function(=>) in "yii.activeForm.js" cause syntax error in IE11

### ISSUE THREAD

**Issue by russeljo** [yiisoft/yii2#19056]
vendor/yiisoft/yii2/assets/yii.activeForm.js

`var disabled = $input.toArray().reduce((result, next) => result && $(next).is(':disabled'), true);`

please, change it to compatible variant

```
var disabled = $input.toArray().reduce(
                    function(result, next){ return (result && $(next).is(':disabled')) }
                    ,true);
```

**Comment by bizley** [comment]
It was already [fixed](https://github.com/yiisoft/yii2/pull/18650) and released. Update your Yii.
