### ISSUE TITLE
Session id is regenerated at every request

### ISSUE THREAD

**Issue by ventoh** [yiisoft/yii2#19067]
I have a problem similar to #17649 . The session id is regenerated every time and the session is lost when the user is guest.  Is it related to #18646 ? The issue appeared in 2.0.44 and not is present in 2.0.43. Same codebase downgrading to 2.0.43 working.

**Comment by bizley** [comment]
What do you mean by 2.0.44? It has not been released yet - do you mean current master?

**Comment by ventoh** [comment]
current dev-master

**Comment by samdark** [comment]
Do you use databse storage for session as well?

**Comment by burakcomer** [comment]
We have a this problem. Now changed composer yii version to 2.0.43. Now project is stable and bug fixed.

**Comment by samdark** [comment]
@burakcomer Do you use databse storage for session?

**Comment by ventoh** [comment]
@samdark . I have tried both: db session and default file session.

**Comment by samdark** [comment]
Got it. So to reproduce it with a clean basic application template I need just to store something in a session without logging in and do refresh? No extra configuration needed?

**Comment by burakcomer** [comment]
> Got it. So to reproduce it with a clean basic application template I need just to store something in a session without logging in and do refresh? No extra configuration needed?

We are use database.

**Comment by ventoh** [comment]
> Got it. So to reproduce it with a clean basic application template I need just to store something in a session without logging in and do refresh? No extra configuration needed?

I'm not sure about that. I will try to reproduce in a basic template.

**Comment by samdark** [comment]
@ventoh that would be very helpful. Thanks.

**Comment by ventoh** [comment]
Sorry, I haven't been able to reproduce in basic template. I have a custom web identity file and need some custom work.I will try again when I have a little more time.

**Comment by samdark** [comment]
@tsanchev would you please help with a way to reproduce the issue?

**Comment by tsanchev** [comment]
@samdark install with composer:
composer create-project --prefer-dist --stability=stable yiisoft/yii2-app-advanced D:\web\www\yii2test\app
then
init --env=Development --overwrite=All
and then print the session in any view
<?= Yii::$app->session->id ?>

**Comment by samdark** [comment]
@bizley would you please look into this one?

**Comment by bizley** [comment]
Reproduced. I'm looking into this.

**Comment by bizley** [comment]
Caused by https://github.com/yiisoft/yii2/commit/c94d7049c51343c1512772b321005cfeb83e1746
