### ISSUE TITLE
Can't build Actor classes

### ISSUE THREAD

**Issue by GrytsenkoAndrey** [yiisoft/yii2#19083]
### What steps will reproduce the problem?
Create new project
`composer create-project yiisoft/yii2-app-basic ./`
also added
`composer require codeception/module-phpbrowser`
file **acceptance.suite.yml**
```
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
              url: http://localhost/
```
after command
`vendor/bin/codecept build`
I got error:

_Fatal error: Type of Codeception\Module\PhpBrowser::$client must not be defined (as in class Codeception\Lib\InnerBrowser) in /var/www/vendor/codeception/module-phpbrowser/src/Codeception/Module/PhpBrowser.php on line 81_

### What is the expected result?
report about build
### What do you get instead?
_Fatal error: Type of Codeception\Module\PhpBrowser::$client must not be defined (as in class Codeception\Lib\InnerBrowser) in /var/www/vendor/codeception/module-phpbrowser/src/Codeception/Module/PhpBrowser.php on line 81_

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4
| Operating system | Ubuntu 21.04 64
| Codeception | 4.1.23
| codeception/module-phpbrowser | 2.0

**Comment by samdark** [comment]
Looks like Codeception issue. Please report to the Codeception project. Thanks.

**Comment by GrytsenkoAndrey** [comment]
Thanks, I will!
