### ISSUE TITLE
`isConsoleRequest()` may return erroneously when testing a Web application in Codeception

### ISSUE THREAD

**Issue by michaelrog** [yiisoft/yii2#19096]
I recently encountered a weird [issue](https://github.com/TopShelfCraft/New-Relic/issues/7) where the Request throws an Exception during route resolution, when testing in Codeception.

The relevant logic is in a branch where `isConsoleRequest()` returns `true`, so my code is expecting to be dealing with `yii\console\Request` in that branch... Problem is, the app being tested is a Web application, and therefore uses a `yii\web\Request`, leading to a `yii\web\NotFoundHttpException`.

It doesn't make sense to see a `yii\web\...` Exception here, since `isConsoleRequest()` is true.

The confounding factor seems to be that, by default, `isConsoleRequest()` only uses `PHP_SAPI` to test its situation — which of course will reflect that we're running in the console, because we're in Codeception. But it's not _actually_ a console request; `isConsoleRequest()` has seemingly returned erroneously.

Is there a way Yii could avoid tripping over this? — For example, maybe `yii\web\Request` could explicitly set `setIsConsoleRequest(false)` at init?

---

### What steps will reproduce the problem?

1. Spin up a web app with a `yii\web\Request`.
2. Include some problematic code:
   ```php
   if (Yii:app()->getRequest()->getIsConsoleRequest()) {
   	$route = ($request->resolve())[0];
   }
   ```
3. Bootstrap the app in a Codeception test.

### What is the expected result?

`getIsConsoleRequest()` should return `false`, and this branch should never execute in the first place, because we're dealing with a _web_ app, with a _web_ request component.

### What do you get instead?

Request throws `yii\web\NotFoundHttpException`.

### Additional info

Yii 2.0.43
PHP 7.4

**Comment by WinterSilence** [comment]
you must set `Yii:$app->request->setIsConsoleRequest(Yii:$app->request instanceof yii/console/Request);` in test bootstrap

**Comment by samdark** [comment]
@michaelrog would you please check @WinterSilence solution? Thanks.

**Comment by michaelrog** [comment]
Yes — Setting `isConsoleRequest` in the test bootstrap _does_ "solve" this, in the sense that it addresses this issue with testing. 

Still, I wonder if the current implementation of `isConsoleRequest()` is correct in the first place. The value of `PHP_SAPI` seems to answer the question: "In what context is the app running?"

In contrast, `isConsoleRequest()` should answer a different question: "What kind of Request object is this?"

From that perspective, it seems like `yii\web\Request` and `yii\console\Request` should each define their `$isConsoleRequest` explicitly, independently of `PHP_SAPI`...

**Comment by WinterSilence** [comment]
@michaelrog in theory, you can create `class CliRequest extends \yii\base\Request` without `resolve()`,  so you must checks request by class:
~~~php
if (Yii:$app->getRequest() instanceof \yii\console\Request) {
	$route = ($request->resolve())[0];
}
~~
