### ISSUE TITLE
yii2 update greater than 2147483647

### ISSUE THREAD

**Issue by nanrenlei** [yiisoft/yii2#19109]
i use yii2,the code like this
```
$dd=aa::find()->where(['id' => 2147483648])->one();
$dd->updatetime= date('Y-m-d H:i:s');
$dd->save();
```
it doesn't work and effects 0 rows,the generated sql like this
`UPDATE `aa` SET `updatetime`='2021-12-23 16:02:02' WHERE `id`=2147483648;`
I change the sql like 
`UPDATE `aa` SET `updatetime`='2021-12-23 16:02:02' WHERE `sha1`='0CE791813EEC4D3F826352C827CC720D6B8EDBD8';`
It works
I think the id 3213470849 what's greater than the maximum value of int 2147483647 caused.
![image](https://user-images.githubusercontent.com/7868103/147219068-0d28c8f7-0c8d-4c06-9cc6-5bf0b4115d15.png)
How do I make it work with id? 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.5
| Operating system |centos 7

**Comment by bizley** [comment]
This is because of the database int column limit of 32-bit size, not because of Yii. Change this column to unsigned int or bigint if you need more than 2147483647.

**Comment by nanrenlei** [comment]
> This is because of the database int column limit of 32-bit size, not because of Yii. Change this column to unsigned int or bigint if you need more than 2147483647.

the database struct
CREATE TABLE `aa` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `updatetime` timestamp NULL DEFAULT '1990-01-01 00:00:00',
  `sha1` char(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
) ENGINE=InnoDB
the id is a bigint

**Comment by bizley** [comment]
What do you get when you call `echo PHP_INT_MAX;` in your PHP script? If 2147483647 that means that your system is 32-bit and cannot handle bigger numbers.

**Comment by nanrenlei** [comment]
> What do you get when you call `echo PHP_INT_MAX;` in your PHP script? If 2147483647 that means that your system is 32-bit and cannot handle bigger numbers.

![image](https://user-images.githubusercontent.com/7868103/147228703-2034dfc9-7ea8-4de7-88f3-2a322a546515.png)
it's a 64-bit system

**Comment by bizley** [comment]
Hmm, I'm not sure what is causing it then, sorry. I would recommend to update PHP and Yii 2 to more recent versions though.

**Comment by nanrenlei** [comment]
> Hmm, I'm not sure what is causing it then, sorry. I would recommend to update PHP and Yii 2 to more recent versions though.

You may try current php and yii,is it right?if right，show me your php and yii version

**Comment by bizley** [comment]
I'm not sure what you are asking for but current Yii 2 is 2.0.43 and current PHP versions are 7.4.27, 8.0.14, and 8.1.1.
