### ISSUE TITLE
yii2 cache 

### ISSUE THREAD

**Issue by sasha-marker** [yiisoft/yii2#19119]
2021/12/29 16:08:01 [error] 17054#0: *44 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Return type of yii\caching\Cache::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/var/www/semenov/sushisell-api/vendor/yiisoft/yii2/caching/Cache.php on line 529PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of yii\caching\Cache::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/var/www/semenov/sushisell-api/vendor/yiisoft/yii2/caching/Cache.php:529
Stack trace:
#0 /usr/local/var/www/semenov/sushisell-api/vendor/yiisoft/yii2/caching/Cache.php(54): yii\base\ErrorHandler->handleError(8192, 'Return type of ...', '/usr/local/var/...', 529)
#1 /usr/local/var/www/semenov/sushisell-api/vendor/yiisoft/yii2/BaseYii.php(293): include('/usr/local/var/...')
#2 /usr/local/var/www/semenov/sushisell-api/vendor/yiisoft/yii2/caching/FileCache.php(27): yii\BaseYii::autoload('yii\\caching\\Cac...')
#3 /usr/local/var/www/semenov/sushisell-api/vendor/yiisoft/yii2/BaseYii.php(293): include('/usr/local/var/...')
#4 [internal function]: yii\BaseYii::autoload('yi...PHP message: PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught yii\base\ErrorException: Return type of yii\web\HeaderCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/var/www/semenov/sushisell-api/vendor/yiisoft/yii2/web/HeaderCollection.php:37

**Comment by samdark** [comment]
Please try https://github.com/yiisoft/yii2/pull/19041

**Comment by sartor** [comment]
fixed in https://github.com/yiisoft/yii2/pull/19037
