### ISSUE TITLE
PHP Deprecated strpos(): Passing null to parameter 

### ISSUE THREAD

**Issue by pamparam83** [yiisoft/yii2#19117]
### What steps will reproduce the problem?
add in file web/index.php `error_reporting(E_ALL);`
and open contact page 

### What do you get instead?
/web/Request.php  at line 574 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 8.1
| Operating system | ubuntu

**Comment by githubjeka** [comment]
#19041
