### ISSUE TITLE
Array Data Cache Dependency

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#19120]
## What is my Problem

I am not sure, but i assume there is very simple cache key dependency missing. Assuming the following:

```php
$model = MyModel::find()->where(['x' => 'z'])->cache(0)->all();
```

now the `cache()` method will store that query result in the database forever. That's great, but what if i want to invalidate the cache with a certain key. In my example, a previous stage of the code has already evaluated a timestamp i can use to invalidate (f.e. the value of updated_at). 

So in general caching situations i would use the `$lastUpdateAt` key within the cache key, like:

```php
Yii::$app->set(['fooBarKey', $lastUpdatedAt], 'mysupercontent')
```

But the ActiveQuery method `cache` does not allow to use a cache key for the given query (of course, makes sense as the query itself is the cache key). So my only solution is to use `DbDependency` again to invalidate that cache. But i have already evaluated that `$lastUpdateAt` value in my application earlier. So a simple array data based cache dependency is missing.

## What could be a solution

I think it would be very easy to create a new `ArrayDataDependency` which is similar to the cache key behavior. If the data changes, the cache mus be evaluated again, so my example would look like:

```php
$model = MyModel::find()->where(['x' => 'z'])->cache(0, new ArrayDataDependency(['key' => $astUpdatedAt]))->all();
```

Or is there any other dependency to fix that problem? Afaik, i don't think so. If this is a suitable solution, i would make a PR.

**Comment by bizley** [comment]
What about TagDependency?

**Comment by nadar** [comment]
TagDependency requires you to invalidate the cache with the previous "cache key"/tag:

```
Yii::$app->cache->set('user_42_profile', '', 0, new TagDependency(['tags' => 'user-123']));
Yii::$app->cache->set('user_42_stats', '', 0, new TagDependency(['tags' => 'user-123']));

// invalidating all keys tagged with "user-123"
TagDependency::invalidate(Yii::$app->cache, 'user-123');
```

So for my described use case above, i would need to store the previous `$lastUpdateAt` value in order to check whether to invalidate tags or not, which makes no sense i would say.

**Comment by nadar** [comment]
I just tested again, i can not make to it work with TagDependency

![image](https://user-images.githubusercontent.com/3417221/147690519-f0cf6dcd-2be2-49ea-ba55-384f854ba6f5.png)

Even when i call invalidate it does not work :smile: strange

My example looks like this, and its always return data from cache even when i change the tag name to "XYZ":

```php
TagDependency::invalidate(Yii::$app->cache, $this->evalHttpCache($id));
        
$item = Model::find()
    ->joinWith(['item'])
    ->andWhere([...])
    ->cache(0, new TagDependency(['tags' => $this->evalHttpCache($id)]))
    ->one();
```

**Comment by fl0v** [comment]
You should call `TagDependency::invalidate(Yii::$app->cache, $tag);` whenever you change data that is relevant to the queries that use that tag.

Right now you add an extra layer of complexity by running your timestamp check before calling your queries.

Also have in mind that for each different tag you have in your app a small permanent record is kept in your cache that will never expire, usually this is not an issue.

**Comment by bizley** [comment]
@nadar I've just checked it with TagDependency on a fresh project and it works properly - invalidating tag dependency forces cache to be refreshed and query to be made.

**Comment by nadar** [comment]
Thanks @bizley i am going to make some more tests. 

@fl0v thanks for your  reply:

> Right now you add an extra layer of complexity by running your timestamp check before calling your queries.

I don't think this is true, because the timestamp is evaluated in earlier stage by another behavior, so making 2 querys for the same usage sounds look the worse solution. But whenever possible, i agree with you.

> Also have in mind that for each different tag you have in your app a small permanent record is kept in your cache that will never expire, usually this is not an issue but using timestamp as a tag is not a good ideea.

Yes, thats something i also had in mind, but does DbDependency fix that, i don't think so? Am i wrong?

**Comment by nadar** [comment]
@bizley back to the topic: i think TagDependency does not what i described is possible with cache keys, its not the same approach. I sill believe there should be an ArrayDataDependency in order to have the option to set cache keys for query caching.

**Comment by bizley** [comment]
Yes, it did when I invalidated that tag before calling the command but if I understand correctly you want this to be done automatically. In that case you need to use dependency that is applicable in your case. As I understand ExpressionDependency should be good? If not maybe you need to prepare a custom one. I'm not sure if we need to add something in the core to take care of it but, again, maybe I just don't grasp your idea here. If so please explain a bit more, maybe a use case and an example would be handy.

**Comment by nadar** [comment]
Ok i try again, sorry for the bad explenation, thanks for your time:

Yii cache has the following option:

```php
$variable = 'whatever';
Yiii::$cache->set(['users', $variable], function() {
   return 'hello bizley';
}, 0);
```

This will cache `hello bizley` until i change the value from `$variable` to something else. This is **not possible** with the [cache()](https://www.yiiframework.com/doc/api/2.0/yii-db-query#cache()-detail) function in Query Buidler.

You can only invalidate the Query Builder cache by using a dependency, but none of the dependecy cache options match the above example. Or can you provide me the above solution with [cache()](https://www.yiiframework.com/doc/api/2.0/yii-db-query#cache()-detail) function, if yes, how?

**Comment by bizley** [comment]
Please try

```
MyModel::find()
    ->where(['x' => 'z'])
    ->cache(0, new ExpressionDependency(['expression' => '$variable === \'whatever\'']))
    ->all();
```

**Comment by nadar** [comment]
This won't work, as the statement just eval's true, but i need to change the cache key in order to force a recache. Your example with ExpressionDependency requires me to store the previous state somewhere in a database, which makes no sense.

I think ExpressionDependency is more for examples like `ExpressionDependency(['expression' => 'time() >= strtotime('yesterday')])` which either evals true or false.

I am just looking for an option to add another cache key to the automatically build cache key (trough the statement), its often called as `variation` in other caching contexts of Yii Framework.

I still believe i have a common problem, where a simple solution would be available, but i am going to close this because:

- either i am really bad in explain my problem :smile:
- there is no interest in such a feature, because of .... i dunno
- `... you have in your app a small permanent record is kept in your cache that will never expire` is a reasonable reason to not implement such a feature
