### ISSUE TITLE
Language code with digits (e.g. "en-150") triggers Invalid Argument error in yii2/i18n/PhpMessageSource.php

### ISSUE THREAD

**Issue by assertzero** [yiisoft/yii2#19138]
### What steps will reproduce the problem?

set language code to any value containing digits, e.g. "en-150", "en-001", "es-419"

### What is the expected result?

no error

### What do you get instead?

`getMessageFilePath()` in `yiisoft/yii2/i18n/PhpMessageSource.php` returns an InvalidArgumentException.

That is because the `preg_match()` in line 137 returns false – regular expression `^[a-z_-]+$/i` doesn't match digits

It should probably be changed to `^[a-z0-9_-]+$/i`

### Additional info

ISO language codes can contain digits, see for example

https://www.w3.org/International/articles/language-tags/
https://www.ctrl.blog/entry/en-001.html

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 7.4.27
| Operating system | Ubuntu 20 LTS

<img width="1458" alt="Screen Shot 2022-01-05 at 12 02 56 PM" src="https://user-images.githubusercontent.com/34266521/148283447-73ba9063-b578-4a28-9a5d-b88deb4b2d54.png">

**Comment by samdark** [comment]
Oh. Wow. What's your use case for it?

**Comment by assertzero** [comment]
I am developing a new website in Craft CMS for a client – a company with subisidies in Europe and other parts of the world, but they aren't doing (much) business in the US. Their main language of communication is "international English", with British spelling and European formatting, but they are not British. en-150 is exactly matching for them (similarly, their Spanish website is mainly geared towards South America in general, which would call for es-419.)

I'd like to make use of the more specific "en-150" instead of just "en" because there is a chance that we will expand the website with a localized "en-US" version in the future. It's not a huge deal, but it would be nice to use the correct language codes since they were created exactly for this kind of situation.

**Comment by samdark** [comment]
That is totally valid. Would you please submit a pull request adjusting it? I'll merge it into master and it will be in the next release.

**Comment by lubosdz** [comment]
Full list of current codepages - https://www.localeplanet.com/icu/iso639.html. There are 5-6 with numeric code.

**Comment by kaspar-allenbach** [comment]
Was this already released into an update? This bug got me as well. Can't find anything in the changelog

**Comment by bizley** [comment]
It's not released yet. It's on current master though.
