### ISSUE TITLE
PHP 8.1 Cast decimals to string on sqlite

### ISSUE THREAD

**Issue by longthanhtran** [yiisoft/yii2#19144]
### What steps will reproduce the problem?
Run the phpunit test with command 
```shell
./vendor/bin/phpunit --verbose --exclude-group oci,wincache,xcache,zenddata,cubrid,mssql
```
From [another project](https://github.com/doctrine/dbal/pull/4818), this issue also identified and fixed

### What is the expected result?
The tests with sqlite's CommandTest should pass.

### What do you get instead?
```shell
1) yiiunit\framework\db\sqlite\CommandTest::testMultiStatementSupport
Failed asserting that Array &0 (
    0 => Array &1 (
        'intcol' => 41
        'textcol' => 'foo'
    )
    1 => Array &2 (
        'intcol' => 42
        'textcol' => 'bar'
    )
) is identical to Array &0 (
    0 => Array &1 (
        'intcol' => '41'
        'textcol' => 'foo'
    )
    1 => Array &2 (
        'intcol' => '42'
        'textcol' => 'bar'
    )
).

/var/www/tests/framework/db/sqlite/CommandTest.php:87
/var/www/vendor/phpunit/phpunit/phpunit:52
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 8.1.1
| Operating system | Ubuntu 20.04

**Comment by longthanhtran** [comment]
One option to have the test pass is to specify sqlite PDO attributes via tests/data/config.php like this
```php
...
        'sqlite' => [
            'dsn' => 'sqlite::memory:',
            'fixture' => __DIR__ . '/sqlite.sql',
            'attributes' => [
                \PDO::ATTR_STRINGIFY_FETCHES => true,
            ],
        ],
...
```
However, there should be another way to resolve.

**Comment by longthanhtran** [comment]
I think we should use the way of informing the user about the attributes with sqlite to be set before application with Yii2 can be started. This way we don't have to add an extension just to handle the type casting.

In addition, by using native PDO sqlite attributes, we can rely on the underlying driver to correctly handling as usual.

What do you think?

**Comment by samdark** [comment]
Can we add this attribute by default?

**Comment by longthanhtran** [comment]
I think, might be can do this via [Connection#initConnection](https://github.com/yiisoft/yii2/blob/e353835cc57afacb18475edd33e53eddf9509e8d/framework/db/Connection.php#L731) but let try this approach first

**Comment by longthanhtran** [comment]
[Pull request](https://github.com/yiisoft/yii2/pull/19147) is made, hope this resolve the issue
