### ISSUE TITLE
Undefined array key error in ActiveRelationTrait:526

### ISSUE THREAD

**Issue by stevekr** [yiisoft/yii2#19148]
`ActiveRelationTrait` line [526](https://github.com/yiisoft/yii2/blob/e353835cc57afacb18475edd33e53eddf9509e8d/framework/db/ActiveRelationTrait.php#L526) throws `Undefined array key` error when `$attribute` is not a key in `$model` array.

Related to this error I got a question if there is any need for `findWith()` when `asArray()` is used in [ActiveQuery:224](https://github.com/yiisoft/yii2/blob/e353835cc57afacb18475edd33e53eddf9509e8d/framework/db/ActiveQuery.php#L224)?
I tested `if (!empty($this->with) && !$this->asArray) {` to get around above error, but didn't have time to see if this messes up something else.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 8.0.14
| Operating system | Linux

**Comment by samdark** [comment]
Is it possible to put together a unit test for it?

**Comment by stevekr** [comment]
I selected only a few columns from multiple joined tables without including columns used in relation links and had forgotten to disable eager loading.
