### ISSUE TITLE
php 8.1  error 5032#5032

### ISSUE THREAD

**Issue by peter-peng-87** [yiisoft/yii2#19153]
5032#5032: *1375 FastCGI sent in stderr: "PHP message: PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught yii\base\ErrorException: Return type of yii\web\HeaderCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable

**Comment by bizley** [comment]
Thank you for the report. It's already mentioned [here](https://github.com/yiisoft/yii2/pull/19041).
