### ISSUE TITLE
Bug with viaMap

### ISSUE THREAD

**Issue by mgrechanik** [yiisoft/yii2#19161]
### What steps will reproduce the problem?
For my AR model I have a relation based on via()
It works for the model all right.
### What is the expected result?
But when I request a bunch of these models in dataProvider and there is only one model in the result, in this code:
yii\db\ActiveRelationTrait::mapVia()
```
    private function mapVia($map, $viaMap) {
        $resultMap = [];
        foreach ($map as $key => $linkKeys) {
            foreach (array_keys($linkKeys) as $linkKey) {
                $resultMap[$key] = $viaMap[$linkKey];
            }
        }
        return $resultMap;
    }
```
### What do you get instead?
$viaMap is **null** and so I have a notice.

I propose to add some checks to fix this situation.

p.s. when there are two models in the result $viaMap  is not null

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | last
| PHP version      | 7.4
| Operating system | linux

**Comment by mgrechanik** [comment]
PHP notice is this:

_Trying to access array offset on value of type null_

**Comment by mgrechanik** [comment]
Well, some very rare condition led to this bug.

I have some joinWith
, and query which is builded is correct
, but attempt to eager loading the models for one of relations, which is default behavior, is not ok somehow.

Debug of the problem led to no success, you can close the issue

**Comment by samdark** [comment]
OK. I hope we will find the issue and PR if we'll face the issue again. Sorry that we're not merging your PR this time and thank you for contributing.
