### ISSUE TITLE
ActiveRecord: LeftJoin: Name Field not reachable

### ISSUE THREAD

**Issue by strtob** [yiisoft/yii2#19160]
### What steps will reproduce the problem?

My Search Class (excerpt):

```
 public function search($params)
    {
        $query = InvOfferHasProperty::find()
                ->leftJoin('tbl_Inv_offer', 'tbl_Inv_offer.id = tbl_Inv_offer_has_property.tbl_INV_offer_id');
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
```
Both tables have a column called name.

### What do you get instead?

```
Array
(
    [0] => app\models\InvOfferHasProperty Object
        (
            [_rt_softdelete:app\models\base\InvOfferHasProperty:private] => Array
                (
                    [deleted_by] => 1
                    [deleted_at] => 2022-01-12 05:57:13
                )

            [_rt_softrestore:app\models\base\InvOfferHasProperty:private] => Array
                (
                    [deleted_by] => 0
                    [deleted_at] => 2022-01-12 05:57:13
                )

            [_d] => 
            [_saved:protected] => Array
                (
                )

            [_attributes:yii\db\BaseActiveRecord:private] => Array
                (
                    [id] => 3
                    [isActive] => 1
                    [tbl_INV_offer_id] => 3
                    [name] => Offer 2000         <<<<<<<<<<<< tbl_Inv_offer.name instead of tbl_Inv_offer_has_property.name
                    [tbl_property_id] => 
                    [tbl_basis_investment_profile_id] => 
                    [tbl_basis_asset_type_id] => 4
...
```

Wrong: the field name of object app\models\InvOfferHasProperty show the name field of  tbl_Inv_offer table, other fields are correct.

It seems that field will not mapped correctly. Any ideas how to fix the problem? 

The next problem is, I get the data like it would be a right join - only ids from tbl_Inv_offer entries will be shown.

Thanks a lot!

Toby

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45-dev
| PHP version      | 8.0.14
| Operating system  |Debian 11

**Comment by samdark** [comment]
Try naming the joined table:

```php
 public function search($params)
    {
        $query = InvOfferHasProperty::find()
                ->leftJoin('tbl_Inv_offer as invoffer', 'invoffer.id = tbl_Inv_offer_has_property.tbl_INV_offer_id');
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
```

**Comment by strtob** [comment]
Thanks, I've tried with alias, unfortunately without success. 

It's strange, the attribute name of app\models\InvOfferHasProperty will be filled by tbl_inv_offer.name :-( all other attributes of InvOfferHasProperty are filled correctly

**Comment by mgrechanik** [comment]
@strtob , try to add

`find()->select('tbl_Inv_offer_has_property.*');`

**Comment by strtob** [comment]
Hi guys,

First of all, thank you for the very quick help!

I walk through the classes and found out, that the InvOfferHasProperty is extended of sjaakp/yii2-spatial 

This package is great, but have problems with joints and I found the fork: dzandrey/yii2-spatial which has fix the problem.

Now it works!

All the best!
Tobyi
