### ISSUE TITLE
Pagination & Bootstrap

### ISSUE THREAD

**Issue by konapaz** [yiisoft/yii2#19179]
Pagination for GridView::widget doesn't styled by Bootstrap 4

### Additional info

I checked the html output

```
<ul class="pagination">
<li class="prev"><a href="..." data-page="1">«</a></li>
<li><a href="..." data-page="0">1</a></li>
<li><a href="..." data-page="1">2</a></li>
....
```
Bootstrap 4 requires  class="page-item" and class="page-link" to li and a elements respectively

```
<ul class="pagination">
<li class="page-item"><a class="page-link" href="#">Previous</a>«</li>
<li class="page-item"><a class="page-link" href="#">1</a></li>
<li class="page-item"><a class="page-link" href="#">2</a></li>

```

https://getbootstrap.com/docs/4.0/components/pagination/

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      |  7.3.30
| Operating system | Win10

**Comment by simialbi** [comment]
@konapaz try using the bs4 one:
```php
<?= GridView::widget([
    'pager' => [
        'class' => 'yii\bootstrap4\LinkPager'
    ]
]); ?>
```
For using this widget you have to add `yiisoft/yii2-bootstrap4` to the `require` section of your `composer.json`

**Comment by konapaz** [comment]
Although I had a new yii2 installation and generated crud I expected to work without any extra configuration

Anyway, it works, thanks! :)
