### ISSUE TITLE
PageCache storing headers in lower format

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#19187]
### Discussed in https://github.com/yiisoft/yii2/discussions/19186

<div type='discussions-op-text'>

<sup>Originally posted by **nadar** January 23, 2022</sup>
We are using PageCache to cache a REST response, it seems that headers are always returned as lowercase chars afterwards, but the original input is case sensitive.

https://github.com/yiisoft/yii2/blob/master/framework/filters/PageCache.php#L281

Whats the reason for this behavior? The default active data provider headers are f.e `X-Pagination-Page-Count` but when cached it returns `x-pagination-total-count` afterwards.</div>

**Comment by nadar** [comment]
Thanks @bizley, very nice!
