### ISSUE TITLE
Enhancement for class ActionColumn

### ISSUE THREAD

**Issue by rackycz** [yiisoft/yii2#19183]
Hi all. Method createUrl() in class ActionColumn uses hardcoded column name "id". But it is not always wanted as some tables might have different PK column name (For example table auth_item which is part of Yii migrations - try to create CRUD using Gii and you will reproduce this problem). I believe that this row:
```
$params = is_array($key) ? $key : ['id' => (string) $key];
````
Could be replaced with this code:
```
$params = [];
foreach ($model->primaryKey() as $pkColName) {
  $params[$pkColName] = (string) $model->$pkColName;
}
```
What do you think?

**Comment by samdark** [comment]
Yes, could be done, I think.

**Comment by WinterSilence** [comment]
@rackycz 
> try to create CRUD using Gii and you will reproduce this problem). 

[it's fixed 3 month ago](https://github.com/yiisoft/yii2-gii/blob/2fa057da21a5472887ddf73fa8e5dbb355096f85/src/generators/crud/default/views/index.php#L69)

**Comment by samdark** [comment]
Yes, seems so. @rackycz please update.
