### ISSUE TITLE
Problems with web/BadRequestHttpException

### ISSUE THREAD

**Issue by Dmitrijlin** [yiisoft/yii2#19191]
### What steps will reproduce the problem?
I'm trying to throw BadRequestHttpException and as third parameter ($previous) I put Throwable|null variable and got 
`Wrong parameters for yii\\web\\BadRequestHttpException([string $message [, long $code [, Throwable $previous = NULL]]])`

### What is the expected result?
Throw exception without parameters problems
### What do you get instead?
`Wrong parameters for yii\\web\\BadRequestHttpException([string $message [, long $code [, Throwable $previous = NULL]]])`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      | 7.3
| Operating system | Unix (Inside Docker container)

**Comment by Dmitrijlin** [comment]
![image](https://user-images.githubusercontent.com/10600576/150946587-22dc0a73-9fa4-4be1-a19d-f340db671e0b.png)
Also provide example where I do it

**Comment by bizley** [comment]
Yes, it should be updated to accept Throwable.
