### ISSUE TITLE
Replication and Read-Write Splitting 

### ISSUE THREAD

**Issue by shenboran** [yiisoft/yii2#19199]
### What steps will reproduce the problem?
When we set [Replication and Read-Write Splitting ], [Connections] will read the cache and know whether the current state is healthy. [serverstatuscache] specifies which cache component to read. What if the cache component is the [DB] itself? A 502 error will appear and the exception cannot be caught

### What is the expected result?
throw exceptions let we know，set 【serverstatuscache】false，It can also solve this problem, but it is not pefect！

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 7.3
| Operating system | win10

**Comment by samdark** [comment]
Storing cache in DB in this case is a very bad idea. Would you please point the changes you want in the code? Maybe a pull request?

**Comment by WinterSilence** [comment]
@samdark Redis too DB 🤓
