### ISSUE TITLE
\yii\helpers\Inflector::camel2words incorrectly handles numbers in a string.

### ISSUE THREAD

**Issue by rincha** [yiisoft/yii2#19204]
\yii\helpers\Inflector::camel2words incorrectly handles numbers in a string.

### What steps will reproduce the problem?

Run the following code:

```php
echo \yii\helpers\Inflector::camel2words('Order4OtherPhones');
```

### What is the expected result?

Output:

`Order 4 Other Phones`

or

`Order4 Other Phones` (as it was in the previous version Yii 2.0.43)

### What do you get instead?

Output:

`Order4other Phones`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 
| Operating system |

**Comment by bizley** [comment]
I see two bugfixes made to this method in 2.0.44 - #18832 and #18898 - but I don't see how those could affect it, could you check what change is causing it?

**Comment by longthanhtran** [comment]
Looks like test cases of camel2words doesn't cover the case with number as a separate word. In my opinion, the string `Order4OtherPhones` should be converted / splitted to `Order 4 Other Phones`. Hence, with a minor (regex) tweak like this

```php
$label = preg_replace('/(?<=[\p{Ll}0-9])[\p{Lu}0-9]|(?<=[\p{L}0-9])[\p{Lu}0-9](?=\p{Ll})/u', ' \0', $name);
```

should handle the specific case.
