### ISSUE TITLE
Cyclic db calls since #19158

### ISSUE THREAD

**Issue by achretien** [yiisoft/yii2#19202]
### What steps will reproduce the problem?

Load a model with a relation  with empty foreign key.

```php
    public function actionTest(): void
    {
        Invitation::find()->id(45)->with(['acceptedBy'])->one();
    }
```

### What is the expected result?

Don't request db calls with WHERE 0=1

<img width="726" alt="Capture d’écran 2022-02-01 à 13 56 35" src="https://user-images.githubusercontent.com/5468508/151972536-04d11057-11d3-4653-89fd-70931fc1da06.png">

### What do you get instead?

Cyclic load of 20 db calls for the same model

<img width="726" alt="Capture d’écran 2022-02-01 à 13 56 22" src="https://user-images.githubusercontent.com/5468508/151972575-f2b1e5a7-35a7-4eb1-b17b-be7c05ac84bf.png">

### Additional info

If I rollback the following MR everything is back to normal #19158.

Méthode: `\yii\db\ActiveRelationTrait::filterByModels`
Lines 531:

```patch
diff --git a/framework/db/ActiveRelationTrait.php b/framework/db/ActiveRelationTrait.php
--- a/framework/db/ActiveRelationTrait.php	(revision 9a96e196608b090c9ad38f0c7dd83136e21bbb7a)
+++ b/framework/db/ActiveRelationTrait.php	(date 1643720461400)
@@ -528,8 +528,7 @@
             // single key
             $attribute = reset($this->link);
             foreach ($models as $model) {
-                $value = isset($model[$attribute]) ? $model[$attribute] : null;
-                if ($value !== null) {
+                if (($value = $model[$attribute]) !== null) {
                     if (is_array($value)) {
                         $values = array_merge($values, $value);
                     } elseif ($value instanceof ArrayExpression && $value->getDimension() === 1) {
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45-dev
| PHP version      |  8.x
| Operating system |  Unbuntu

**Comment by samdark** [comment]
#19158

**Comment by samdark** [comment]
@stevekr would you please look into it?

**Comment by stevekr** [comment]
Can you share more code like how the relation is defined and what you have in that id() method? I can't replicate this bug with my own code.

**Comment by achretien** [comment]
I tried with a short portion of code and it seems that the error is on our side sorry for the time.

We overwrote the ActiveRecord with some custom methods and one of them seems to have a wrong behavior.
