### ISSUE TITLE
andFilterWhere does not translate conditions correctly from array format

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2#19203]
I have a search model where i am trying to add condition in the existing query 

### What steps will reproduce the problem?
add a condition like following in your search model 

```
$query->andFilterWhere(
                [
                    'AND',
                    ['>=','created_at', $this->date_from],
                    ['<', 'created_at', new Expression("DATE_ADD({$this->date_to}, INTERVAL +1 DAY")]
                ]
            );
```

### What is the expected result?
Pasting query related to my model 

```
SELECT
  COUNT(*)
FROM
  `campaign_subscriber`
  LEFT JOIN `subscriber` `subscriber` ON `campaign_subscriber`.`subscriber_id` = `subscriber`.`id`
WHERE
  (`subscriber`.`user_id` = 2)
  AND (`campaign_id` = '1')
  AND (
    (`campaign_subscriber`.`created_at` >= '2022-02-01')
    AND (
      `campaign_subscriber`.`created_at` < DATE_ADD('2022-03-02', INTERVAL + 1 DAY)
    )
  )
```
Notice the last condition after the `AND (campaign_id='1')` 
```
 AND (
    (`campaign_subscriber`.`created_at` >= '2022-02-01')
    AND (
      `campaign_subscriber`.`created_at` < DATE_ADD('2022-03-02', INTERVAL + 1 DAY)
    )
  )
```
it has the closing `)` for the outer `AND`

### What do you get instead?
```
SELECT
  COUNT(*)
FROM
  `campaign_subscriber`
  LEFT JOIN `subscriber` `subscriber` ON `campaign_subscriber`.`subscriber_id` = `subscriber`.`id`
WHERE
  (`subscriber`.`user_id` = 2)
  AND (`campaign_id` = '1')
  AND (
    (`campaign_subscriber`.`created_at` >= '2022-02-01')
    AND (
      `campaign_subscriber`.`created_at` < DATE_ADD('2022-03-02',  INTERVAL + 1 DAY)
    )
  
```
Missing the closing `)` in the end 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | PHP 7.3.31
| Operating system | Ubuntu

**Comment by bizley** [comment]
It's a missing bracket on your side. You have:

 > new Expression("DATE_ADD({$this->date_to}, INTERVAL +1 DAY")

and should be:

> new Expression("DATE_ADD({$this->date_to}, INTERVAL +1 DAY)")

Notice the closing bracket after `+1 DAY`.

**Comment by buttflattery** [comment]
Sorry guys for being a stupid i didnt notice that for an hour and then added the issue here @bizley . closing now

**Comment by bizley** [comment]
No worries, honest mistake, can happen to anyone. Cheers.
