### ISSUE TITLE
Question: use CURRENT_TIMESTAMP instead of TimestampBehavior?

### ISSUE THREAD

**Issue by sandor-molnar-s-web** [yiisoft/yii2#19212]
I wonder if the `yii\behaviors\TimestampBehavior` is has any benefits over `CURRENT_TIMESTAMP`?
Migration example:
```php
'created_at' => $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP"),
'updated_at' => $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP")->append('ON UPDATE CURRENT_TIMESTAMP'),
```
I used this method without a problem, so I wonder if there any good reason to use the behavior instead?

**Comment by bizley** [comment]
Not every DB is using CURRENT_TIMESTAMP and you don't always want CURRENT_TIMESTAMP to be set in TimestampBehavior.
