### ISSUE TITLE
$model->save() generating value for id column

### ISSUE THREAD

**Issue by skills-up** [yiisoft/yii2#19214]
I'm facing a lot of varying issues specially during saving data to MySQL database. All the issues are coming from duplicate or invalid values for the id column. This column has been defined in the migration as:
```
'id' => $this->bigPrimaryKey(),
```
The corresponding column definition in the table is:
```
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
```

The corresponding error is typically:
```
SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1
The SQL being executed was: INSERT INTO `product` (`sku`, ..., `id`) VALUES (NULL, ..., 0)
```

Please note that `id` column is included in the resultant SQL and it's value is set to 0. Sometimes, it's set to a value similar to the id of an existing record and then I get duplicate key error.

I don't understand why the `id` column is being included at all in the generated SQL command?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 7.4.22
| Operating system | Mac OS

**Comment by bizley** [comment]
It is included only when you provide a value for it that is why I suspect that this might be a cause of your problem.

**Comment by skills-up** [comment]
Here is the code that I'm using:
```
$product = new Product();
$product->hsn = 'hsn-value';
... // Few more assignments but not id
$product->save();
```

That's why inclusion of id in the resultant command is surprising.

**Comment by skills-up** [comment]
Here is the exact code in case it helps:
```
$product = Product::findOne(['wc_product_id' => $data->id]) ?: new Product();
$product->sku = $data->sku ?: null;
$product->name = $data->name;
$meta = array_column($data->meta_data, 'value', 'key');
$product->hsn_code = $meta['_hsn_number'] ?? null;
if ($product->isNewRecord) {
    $product->quantity = $data->stock_quantity ?? 0;
    $product->wc_product_id = $data->id;
}
$product->save();
```

Here is the latest error generated for it:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `product` (`sku`, `name`, `hsn_code`, `quantity`, `wc_product_id`, `version`, `created_at`, `updated_at`, `created_by`, `updated_by`, `id`) VALUES (NULL, 'Custom Cards', NULL, 0, 490, '0', NOW(), NOW(), 3, 3, 2)
```

**Comment by bizley** [comment]
Since no one else is reporting such problem this might be something related to your DB / app. If not, we would need to get a minimal reproducible example to recreate it. In both cases please try it on the fresh project and let us know the results.

**Comment by bizley** [comment]
Sounds about right. Still we need minimal reproducible case to work on it, otherwise we can only guess what is on your side.

**Comment by lubosdz** [comment]
@skills-up  But the code sample you provided is not a batch insert. Check out [documentation](https://www.yiiframework.com/doc/api/2.0/yii-db-command#batchInsert()-detail).

**Comment by skills-up** [comment]
It's not a batch insert code, because the API call is not for a batch insert. The API is called once for each product, and depending on whether a record exists in Yii2 app database, an insert/update is made. Anyway, the issue I've raised is regarding inclusion of `id` column in the generated SQL command for an insert operation. Curiously, I don't have this issue in an older Yii2 version (about 3 yrs old) used in a different app.

**Comment by alex-code** [comment]
Do you have any `rules()` on the `Model` that could be adding the `id`?

**Comment by skills-up** [comment]
Here is the complete set of rules on the model:

```
    public function rules()
    {
        return [
            [['wc_product_id', 'initial_quantity', 'adjusted_quantity', 'to_order_quantity', 'version', 'created_by', 'updated_by'], 'integer'],
            [['name', 'initial_quantity', 'adjusted_quantity'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['sku', 'name'], 'string', 'max' => 255],
            [['hsn_code'], 'string', 'max' => 15],
            [['wc_product_id'], 'unique'],
            [['sku'], 'unique'],
            [['version'], 'default', 'value' => '0'],
            [['version'], 'mootensai\components\OptimisticLockValidator']
        ];
    }
```

As you an see there is no rule corresponding to `id`.

However, that makes me think: perhaps the following is the reason:
```
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new \yii\db\Expression('NOW()'),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            'uuid' => [
                'class' => UUIDBehavior::className(),
                'column' => 'id',
            ],
        ];
    }
```

I'll remove the `uuid` behavior and report back if that solves the issue.

**Comment by skills-up** [comment]
Removing the `uuid` behavior did solve the issue.
I'm sorry about taking so much of your time. Thanks for all your help.
