### ISSUE TITLE
yii2.0.44 Model.php PHP Fatal error:  During inheritance of IteratorAggregate 

### ISSUE THREAD

**Issue by nathanwang** [yiisoft/yii2#19218]
### What steps will reproduce the problem?
new project use " composer create-project --prefer-dist yiisoft/yii2-app-advanced qywf" 

`PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught yii\base\ErrorException: Return type of yii\base\Model::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/wangjie/www/qywf/vendor/yiisoft/yii2/base/Model.php:998`

### What is the expected result?
./init
./yii

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 8.1.2
| Operating system | macos

**Comment by bizley** [comment]
Already taken care of https://github.com/yiisoft/yii2/pull/19041
