### ISSUE TITLE
Return null hasOne relation in model

### ISSUE THREAD

**Issue by Sadi01** [yiisoft/yii2#19224]
After this commit https://github.com/yiisoft/yii2/commit/67ea4cf968df26c709fb1e1c369795a99b6699a7, all relations that I created on model defined properties (not on database table fields) don't work anymore.

### What steps will reproduce the problem?
```php
/**
 * This is the model class for table "my_model".
 *
 * @property int $id
 * @property json $add_on
 * /
class MyModel extends \yii\db\ActiveRecord
{
    public ?int $test_id = null;

    public static function tableName()
    {
        return 'my_model';
    }

    public function getTest()
    {
        return $this->hasOne(Test::class, ['id' => 'test_id']);
    }

    public function afterFind()
    {
        $this->test_id = $this->add_on['test_id'];
        parent::afterFind();
    }
}
```
### What is the expected result?
```
Test model
```
### What do you get instead?
```
null
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      |  8.0.8
| Operating system | Linux

**Comment by bizley** [comment]
@stevekr could you check it? A fixed property is used here for the relation instead of AR attribute.

**Comment by stevekr** [comment]
Didn’t know this kind of relation was even possible.  I’m away for a while so can’t test this myself, but if suggested change works then great.

**Comment by Sadi01** [comment]
> Didn’t know this kind of relation was even possible. I’m away for a while so can’t test this myself, but if suggested change works then great.

Yes I test it and it's work.

**Comment by bizley** [comment]
Well, so far it fails in tests.

**Comment by WinterSilence** [comment]
`MyModal::$test_id` defined as null and don't changed in current code, maybe you want write `$this->test_id = $this->add_on['test_id'];`? any case it's can't work because JSON not decoded by default.

**Comment by Sadi01** [comment]
@WinterSilence yes, I corrected it.

**Comment by WinterSilence** [comment]
@Sadi01 worked by bug because `MyModal::$test_id` is not **attribute**, `ActiveRecord` attributes - table columns
~~~php
/**
 * ...
 * @param array $link the primary-foreign key constraint. The keys of the array refer to
 * the attributes of the record associated with the `$class` model, while the values of the
 * array refer to the corresponding attributes in **this** AR class.
 * ...
 */
public function hasOne($class, $link)
~~~

**Comment by WinterSilence** [comment]
HowTo:
~~~php
<?php
namespace app\models;

use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\JsonExpression;

class MyModel extends ActiveRecord
{
    public static function tableName(): string
    {
        return 'my_model';
    }

    public function rules(): array
    {
        return [
            ['add_on', 'safe'],
        ];
    }

    // correct access
    public function getTest(): ActiveQuery
    {
        return Test::find()->where(['id' => $this->testId]);
    }

    // incorrect access, but it's work - other bug (:
    public function getTest2(): ActiveQuery
    {
        return $this->hasOne(Test::class, ['id' => 'testId']);
    }

    public function getTestId(): int
    {
        return (int) $this->add_on['test_id'] ?? 0;
    }

    public function setAddOn(array $value)
    {
        $this->setAttribute('add_on', new JsonExpression($value));
    }

    public function getAddOn()
    {
        return $this->getAttribute('add_on') ?? [];
    }
}
~~~

**Comment by Sadi01** [comment]
@WinterSilence So, how can I create relation on MySQL json columns? may I use virtual column and create relation on that, e.g. add_on is a json column and test_id is part of add_on, so I have to create virtual column for test_id, now I can create relation on test_id.

**Comment by WinterSilence** [comment]
@Sadi01
> how can I create relation on MySQL json columns?

🤦🏻‍♂️ see [HowTo](https://github.com/yiisoft/yii2/issues/19224#issuecomment-1039702657)

you try create relation to value IN json column, it's not same.

**Comment by WinterSilence** [comment]
@Sadi01
> Your getTest relation is not a real relation

your property `$test_id` not attribute, but it's not confuse you..

**Comment by Sadi01** [comment]
@WinterSilence your getTest relation is right to create relation on part of json column?

**Comment by WinterSilence** [comment]
@Sadi01 it's work in some cases, if you use mysql use [`->` syntax](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-inline-path) to get property of object containing in json column

**Comment by samdark** [comment]
1. Virtual columns in general can't work with `joinWith()` because there's no data to join on.
2. Virtual columns can't work on the far part of any relation i.e. `User hasOne Profile via User.profileId`, `User->profiles` is possible if `profileId` is virtual column but the same isn't possible for `User hasOne Profile via Profile.userId` if `userId` is virtual column.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/19231 case is valid.

**Comment by samdark** [comment]
Closing this issue as https://github.com/yiisoft/yii2/issues/19231 description is a bit cleaner.
