### ISSUE TITLE
yii2-debug PHP 8.1 incompatible

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#19226]
yii2-debug use incompatible Opis\Closure library.
ErrorException in console while loading /debug/default/toolbar?tag=<tag>:

```
Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.1
| Operating system |Linux

**Comment by bizley** [comment]
Looks like already taken care of in https://github.com/yiisoft/yii2-debug/pull/472
