### ISSUE TITLE
String default value in FilterValidator breaks BC

### ISSUE THREAD

**Issue by rvkulikov** [yiisoft/yii2#19238]
### What steps will reproduce the problem?

```php
<?php

use yii\base\Model;

class FormModel extends Model
{
    public ?int $entityId = null;
    
    public function rules(): array
    {
        return [
            ['entityId', 'filter', 'filter' => [$this, 'filterEntity']]
        ];
    }

    public function filterEntity($value)
    {
        if($value === null){
            return 0;
        }
        
        return $value;
    }
}

$model = new FormModel();
$model->validate();
```

### What is the expected result?
Literally no output.

### What do you get instead?
Exception 'TypeError' with message 'Cannot assign string to property FormModel::$entityId of type ?int'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45?
| PHP version      | 8.0.3
| Operating system | Alpine Linux 3.13

### Where is the problem
https://github.com/yiisoft/yii2/commit/1271bc419ffaa2ac0e4db7d2eabea349ac5e4ace#diff-c8c247659cc4089ae846b735568a4c6d0fa09b949e3f8bb78dc621a39ec6609dR78

It should be `null` fallback instead of `string`

**Comment by a-tomal** [comment]
Same problem.

**Comment by samdark** [comment]
See comments in https://github.com/yiisoft/yii2/pull/19239
