### ISSUE TITLE
Broken relations

### ISSUE THREAD

**Issue by Krakozaber** [yiisoft/yii2#19231]
In Yii 2.0.45 a property that does not exist in the database has been added to the model. According to similar properties, the relation stopped working. In the rules, this property is specified. In Yii 2.0.44 everything worked.

```
class ProjectProcess extends ActiveRecord {
  public $userByAdminId;
...
  public function getUserByAdmin(): ActiveQuery {
      return $this->hasOne(User::class, ['id' => 'userByAdminId']);
  }
...
}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.0.15
| Operating system | Debian

**Comment by bizley** [comment]
Related to https://github.com/yiisoft/yii2/issues/19224

**Comment by WinterSilence** [comment]
public your function `rules()` + example generating this error, `['userByAdminId', 'safe']`?

**Comment by WinterSilence** [comment]
@Krakozaber 
> Note: The Active Record attributes are named after the associated table columns in a case-sensitive manner. Yii automatically defines an attribute in Active Record for every column of the associated table. You should NOT redeclare any of the attributes.
https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#accessing-data

**Comment by Krakozaber** [comment]
@WinterSilence I did not repeat it, this attribute is not in the database

**Comment by WinterSilence** [comment]
@Krakozaber 
1. it's not attribute
2. focus on _attributes are named after the associated table columns_ i.e. AR attributes is table columns. you can use virtual columns, but it's not so easy as as relation by foreign key.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/issues/19224#issuecomment-1039941096

**Comment by samdark** [comment]
Seems we don't have tests for this case. That's the first step to fix it and ensure it's not broken again.

**Comment by samdark** [comment]
So overall plan:

1. Add tests.
2. Add a note explaining https://github.com/yiisoft/yii2/issues/19231#issuecomment-1039952654 to relation guide and corresponding methods.

**Comment by samdark** [comment]
Likely fixed with https://github.com/yiisoft/yii2/commit/adadbefe885589ea1a409346c6f36d6bc20e863b. Please check if that's true.

**Comment by Krakozaber** [comment]
It`s work

**Comment by bizley** [comment]
Perfect, thank you. Closing.
