### ISSUE TITLE
Why is EVENT_AFTER_SEND actually triggers before send?

### ISSUE THREAD

**Issue by PlsHelpMeWithThisIssue** [yiisoft/yii2#19249]
### What steps will reproduce the problem?
Create \yii\rest\Controller and EventHandler class with following code

```php
<?php


namespace app\controllers;


use Exception;
use Yii;

use yii\web\Response;

class EventHandler {
	public static function handle() {
		throw new Exception('I am dead');
	}
}

class SomeController extends \yii\rest\Controller {

	public function actionIndex() {
		Yii::$app->response->on(Response::EVENT_AFTER_SEND, [EventHandler::class, 'handle']);

		return 'hello world';
	}
}
```
When action "index" is called static function "handle" of class EventHandler sets as event handler, and then returning a 'hello world' string.
Function "handle" just throws the exception 

### What is the expected result?
I expected that when i called this action from for example postman i get 'hello world' string and then EVENT_AFTER_SEND function will be called and then exception will be throw.

### What do you get instead?
I get an Exception throwed from handle function but not get an 'hello world' string.

### Comment
This trigger fired in response->send() method but i think this trigger should called outside this method and after header("Connection: close");?

### Additional info
| Yii version      |  "~2.0.14"
| PHP version      | 8.08
| Operating system | Ubuntu 18.04.5 LTS x86_64

**Comment by WinterSilence** [comment]
you can run your code directly in `beforeAction()` or bind your handlers in `init()` or `__construct()` after executing parent method (`parent::init()` or `parent::__construct()`).

**Comment by WinterSilence** [comment]
or in [application config](https://www.yiiframework.com/doc/guide/2.0/en/concept-configurations#configuration-format)

**Comment by Nwors** [comment]
> you can run your code directly in `beforeAction()`/`afterAction()` or bind your handlers in `init()` or `__construct()` after executing parent method (`parent::init()` or `parent::__construct()`). [controller lifecycle](https://www.yiiframework.com/doc/guide/2.0/en/structure-controllers#controller-lifecycle)

No matter where i bind my handlers i've tried bind handler in __construct() after parent::init() method

`<?php


namespace app\controllers;


use Exception;
use Yii;

use yii\web\Response;

class EventHandler {
	public static function handle() {
		throw new Exception('I am dead');
	}
}

class SomeController extends \yii\rest\Controller {

	public function __construct($id, $module, $config = [])
	{
		parent::__construct($id, $module, $config);
		Yii::$app->response->on(Response::EVENT_AFTER_SEND, [EventHandler::class, 'handle']);
	}

	public function actionIndex() {
		return 'hello world';
	}
}`

and run my code directly in after action, following the Yii docs

> This method is invoked right after an action is executed. The method will trigger the [EVENT_AFTER_ACTION](https://www.yiiframework.com/doc/api/2.0/yii-base-controller#EVENT_AFTER_ACTION-detail) event. The return value of the method will be used as the action return value.

afterAction() result will be used as the action return value. 
I always get the same result, exception was throwed but i dont get 'hello world' string. I need to execute my code after all data is sent to the client, EVENT_AFTER_SEND looks exactly what i looking for but the way it works confuses me.

**Comment by PlsHelpMeWithThisIssue** [comment]
> you can run your code directly in `beforeAction()`/`afterAction()` or bind your handlers in `init()` or `__construct()` after executing parent method (`parent::init()` or `parent::__construct()`). [controller lifecycle](https://www.yiiframework.com/doc/guide/2.0/en/structure-controllers#controller-lifecycle)

No matter where i bind my handlers i've tried bind handler in __construct() after parent::init() method

```
<?php


namespace app\controllers;


use Exception;
use Yii;

use yii\web\Response;

class EventHandler {
	public static function handle() {
		throw new Exception('I am dead');
	}
}

class SomeController extends \yii\rest\Controller {

	public function __construct($id, $module, $config = [])
	{
		parent::__construct($id, $module, $config);
		Yii::$app->response->on(Response::EVENT_AFTER_SEND, [EventHandler::class, 'handle']);
	}

	public function actionIndex() {
		return 'hello world';
	}
}
```

and run my code directly in after action. Following the Yii docs

> This method is invoked right after an action is executed. The method will trigger the [EVENT_AFTER_ACTION](https://www.yiiframework.com/doc/api/2.0/yii-base-controller#EVENT_AFTER_ACTION-detail) event. The return value of the method will be used as the action return value.

afterAction() result will be used as the action return value. 
I always get the same result, exception was throwed but i dont get 'hello world' string. I want to execute code after all data is sent to the client, EVENT_AFTER_SEND looks exactly what i looking for but the way it works confuses me.

**Comment by WinterSilence** [comment]
@PlsHelpMeWithThisIssue look to `yii\base\Controller::afterAction()` and `yii\web\Response::send()`
Response body not sending: your exception throws at sending response, because all response events triggering in `send()`.
bind event `Application::EVENT_AFTER_REQUEST` in config file: `['on ' . Application::EVENT_AFTER_REQUEST] => [EventHandler::class, 'handle'];

**Comment by PlsHelpMeWithThisIssue** [comment]
i add the folowing string in my config file.
```php
[
    ...
    'on ' . Application::EVENT_AFTER_REQUEST => [EventHandler::class, 'handle'],
    'params' => $params,
];
```
Events triggers but i still not getting any response before exception.

In code of yii\base\Application.php i found that EVENT_AFTER_REQUEST triggers right after controller handle request but before sned() method called. EVENT_AFTER_SEND called in send() method wich goes after EVENT_AFTER_REQUEST am i wrong?
![image](https://user-images.githubusercontent.com/52002834/154911062-61eb144c-be31-4659-9620-04f393329b1d.png)

**Comment by WinterSilence** [comment]
@PlsHelpMeWithThisIssue my fail, i looked modified class... You can try throw http exception like as [yii\web\NotFoundHttpException](https://www.yiiframework.com/doc/api/2.0/yii-web-notfoundhttpexception) What's reason to throw uncatched exception in handler?

**Comment by PlsHelpMeWithThisIssue** [comment]
I actually don't want to throw exception i want to execute code on this place (it is test example). I throw exception because THIS exception as i expected should be throwed AFTER client get his response, thats mean it's server side exception, all work with client done (response is sent), and he shouldn't know nothing about it, but instead of it i didn't get my response i get a my throwed exception, that's mean server don't send anything to client before EVENT_AFTER_SEND handler is done in result i get a my Exception in response and status 500 but not my response string and status 200.

**Comment by WinterSilence** [comment]
@PlsHelpMeWithThisIssue how you check response?

**Comment by PlsHelpMeWithThisIssue** [comment]
i send requests to my controller via postman 
![image](https://user-images.githubusercontent.com/99964955/154928203-c6785865-8796-4180-a7e0-beb5a3a6970a.png)

**Comment by WinterSilence** [comment]
as i can see, headers sended normally. You use wrong application, change yii\web\Application and not http exception.

**Comment by PlsHelpMeWithThisIssue** [comment]
@WinterSilence what do you mean by change yii\web\Application? As i imported something wrong? as for exception it's not matter, replace exception for while(true) loop.

**Comment by bizley** [comment]
Thank you @WinterSilence for looking into it but it seems to be a developer issue. Please @PlsHelpMeWithThisIssue take it to forum for example to be handled since this is an issue tracker, thank you.

**Comment by PlsHelpMeWithThisIssue** [comment]
@bizley The fact that no one got into this case does not mean that this is a developer's problem, but in any case, thanks for the help and spended time.

**Comment by bizley** [comment]
Well, if this is a bug let's reopen this. Is it?

**Comment by PlsHelpMeWithThisIssue** [comment]
@bizley I think this is a bug because the event doesn't do what it's name says. It's called EVENT_AFTER_SEND, but it's not called after the actual send, it's called before it.

**Comment by PlsHelpMeWithThisIssue** [comment]
in vanilla php if you want to send something after RESPONSE is sent to client you can use the following code

```php
<?php
ignore_user_abort(true);//not required
set_time_limit(0);

ob_start();
// do initial processing here
echo 'response'; // send the response
header('Connection: close');
header('Content-Length: '.ob_get_length());
ob_end_flush();
@ob_flush();
flush();
fastcgi_finish_request();//required for PHP-FPM (PHP > 5.3.3)


throw new Exception('i am died');
// now the request is sent to the browser, but the script is still running
// so, you can continue...

die(); //a must especially if set_time_limit=0 is used and the task ends
```
it worked as expected.

**Comment by bizley** [comment]
The only problem here as I can see it is that you think it works different than what you expect - as the doc states:
> an event that is triggered at the end of send()

and that's it. It's not "after response", it's "after send". If I'm not mistaken (please someone correct me on this) Yii is not offering "after response" event out-of-the-box.

**Comment by PlsHelpMeWithThisIssue** [comment]
@bizley Okay, if that's how it was meant to be, then there's no problem with that, thanks again, keep it closed, but I think it's some kind of flaw.
