### ISSUE TITLE
Extension validation for uploaded file always failed with PHP 8.1

### ISSUE THREAD

**Issue by tanakahisateru** [yiisoft/yii2#19243]
### What steps will reproduce the problem?

Use FileValidator with `extensions`.

```php
class UploadForm extends Model
{
    public function rules()
    {
        return [
            ['user_file', 'file', 'extensions' => "jpg,jpeg,png.gif"],
        ];
    }
```

### What is the expected result?

Validate extensions and MIME type correctly.

### What do you get instead?

Any upload files are not accepted.
To avoid this, I set `checkExtensionByMimeType` to false:

```php
 ['user_file', 'file', 'extensions' => "jpg,jpeg,png.gif", 'checkExtensionByMimeType' => false],
```

This problem occurs with only Yii 2.0.45 and PHP 8.1.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.1
| Operating system | Docker official PHP

FileValidator uses `FileHelper::getMimeType` :

```php
    protected function validateExtension($file)
    {
        $extension = mb_strtolower($file->extension, 'UTF-8');

        if ($this->checkExtensionByMimeType) {
            $mimeType = FileHelper::getMimeType($file->tempName, null, false);     // <------ here
            if ($mimeType === null) {
                return false;
            }
```

This method was changed not to use real `finfo_open` (instead file name based detection) for PHP 8.1:

```php
        if (PHP_VERSION_ID >= 80100) {
            return static::getMimeTypeByExtension($file, $magicFile);
        }

        $info = finfo_open(FILEINFO_MIME_TYPE, $magicFile);
```

But actually, uploaded file temp name has no extension like as `/tmp/php12AB45`.

I suggest a choice:

- Ignore checkExtensionByMimeType when PHP 8.1.
- Save getMimeType method compatibility.

**Comment by alex-code** [comment]
Original issue: https://github.com/yiisoft/yii2/issues/19145
PR: https://github.com/yiisoft/yii2/pull/19146

Couldn't see anything in the PHP changelog that would change the functionality of `finfo_open` to need the PR.

**Comment by My6UoT9** [comment]
https://www.php.net/manual/en/function.finfo-open.php

This is just a misconfiguration, nothing to do with PHP 8.1.

> magic_database
> Name of a magic database file, usually something like /path/to/magic.mime. If not specified, the MAGIC environment variable is used. If the environment variable isn't set, then PHP's bundled magic database will be used.
> 
> Passing null or an empty string will be equivalent to the default value.

And there is an error, `"jpg,jpeg,png.gif"` should be  `"jpg,jpeg,png,gif`"`
So if png or gif was tested, it didn't work anyway.

**Comment by samdark** [comment]
@longthanhtran is it possible to have a test that fails for the case that was fixed originally?

**Comment by longthanhtran** [comment]
@samdark this case I was struggling for awhile when dealing with it as gh actions always failed until I choose the way to fallback to call `getMimeTypeByExtension` on PHP 8.1.

This case, as mentioned above by @My6UoT9, the rule seems incorrectly set `"jpg,jpeg,png.gif"` (use `.` instead of `,`).

To have a test that fails previous fix, I think it could be like this (FileHelperTest.php)

```php
...
public function testGetUploadedImageMimeTypes()
    {
        $ds = DIRECTORY_SEPARATOR;
        $phpunitPath = Yii::getAlias('@yiiunit');
        $runtimeLocation = Yii::getAlias('@yiiunit/runtime');
        $resourceSourceLocation = "{$phpunitPath}{$ds}framework{$ds}validators{$ds}data{$ds}mimeType";

        $pngFile = "{$runtimeLocation}{$ds}php1234";
        copy("{$resourceSourceLocation}{$ds}test.png", $pngFile);

        $this->assertEquals('image/png', FileHelper::getMimeType($pngFile));

        $jpgFile = "{$runtimeLocation}{$ds}php4567";
        copy("{$resourceSourceLocation}{$ds}test.jpg", $jpgFile);

        $this->assertEquals('image/jpeg', FileHelper::getMimeType($jpgFile));
    }
...
```

**Comment by sviluppo** [comment]
> Original issue: #19145 PR: #19146
> 
> Couldn't see anything in the PHP changelog that would change the functionality of `finfo_open` to need the PR.

Could not be better use `mime_content_type` instead? 

```
        if (PHP_VERSION_ID >= 80100) {
            return mime_content_type($file);
        }
```
Because `$magicFile` is always empty anyway on php 8.1.
In this way it's not necessary to use `'checkExtensionByMimeType' => false`.
