### ISSUE TITLE
doc: Garbled text in russian documentation (and other langs?)

### ISSUE THREAD

**Issue by rawtaz** [yiisoft/yii2#19248]
### What steps will reproduce the problem?

- Go to https://www.yiiframework.com/doc/guide/2.0/ru and (or directly) download https://www.yiiframework.com/doc/download/yii-docs-2.0-ru.tar.gz .
- Extract the downloaded file and open the guide-README.html file in your browser (I tried Safari and Chrome, same result).
- Notice how (with UTF-8 set as the encoding in the browser) the menu to the left is properly written out, but the main column's russian text is all garbled.

### What is the expected result?

Properly written out russian text in the main column.

### What do you get instead?

Garbled russian text in the main column. Screenshot:

![russian](https://user-images.githubusercontent.com/825204/154589223-9d317488-642d-4121-a625-455f52473efe.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | yii-docs-2.0-ru
| PHP version      | N/A
| Operating system | macOS 10.14.6, tested with both Safari 12.1.2 and Chrome 97.0.4692.99

---

Presumably the cause of this is the wrong encoding being used somewhere in the data source or along the lines of generating this documentation. If it's all UTF-8 it should be correct in the end, I think. FWIW, the person reporting this problem to me said it was happening in other languages too.

**Comment by samdark** [comment]
Fixed in apidoc, docs will be re-generated soon.
