### ISSUE TITLE
problem with the size of the log[yii2/log/FileTarget]

### ISSUE THREAD

**Issue by stu2162583** [yiisoft/yii2#19259]
### What steps will reproduce the problem?
The log is full and concurrent

### What is the expected result?
The log should be full

### What do you get instead?
some logs are too small

![image](https://user-images.githubusercontent.com/14155947/155095766-c8a3f61b-80c8-497f-877e-59dedf590baa.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 7.2.6
| Operating system | windows

same as #19079 

hello, I'm back again, after our testing, The problem is due to rotateFiles and concurrency

**config**
```
'log' => [
	'targets' => [
		[
			'class' => 'yii\log\FileTarget',
			'categories' => ['open'],
			'logVars' => [],
			'maxFileSize' => 100, //for better display of errors
			'maxLogFiles' => 5,
			'logFile' => '@root/runtime/logs/open.log',
		]
	],
],
```

**code**
```
$request = Yii::$app->request;
$header = $request->getHeaders();
$get = $request->get();
$body = $request->bodyParams;
$method =  $request->method;
Yii::info([
	'header' => $header,
	'get' => $get,
	'body' => $body,
	'method' => $method,
], 'open');
```

test with ab
```
ab -n1000 -c10 http://example.com/path1/path2
```

You will see that some logs are very small
------------------------------------------------------------------------

By the way, I don't think it's a good idea to attach an application log when logvar is not empty, preferably something that can be controlled.

```
'logVars' => ['_GET', '_POST'],

// will hava
... category: application ....
```

**Comment by bizley** [comment]
Hmm, does it work if you set `rotateByCopy` to `false`?

**Comment by stu2162583** [comment]
> `rotateByCopy`

thanks！

Under Windows, same result, and when rename, there is an error. [yii\log\Dispatcher::dispatch] Unable to send log via yii\log\FileTarget: Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Unable to append to log file: F:/codes/szy/ ycs/runtime/logs/open.log'

**Comment by stu2162583** [comment]
> Hmm, does it work if you set `rotateByCopy` to `false`?

thanks！

Under Windows, same result, and when rename, there is an error. [yii\log\Dispatcher::dispatch] Unable to send log via yii\log\FileTarget: Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Unable to append to log file: F:/codes/szy/ ycs/runtime/logs/open.log'

**Comment by virtual-designer** [comment]
What about file permissions? Are those log files writable by PHP?

**Comment by stu2162583** [comment]
> What about file permissions? Are those log files writable by PHP?

**Comment by stu2162583** [comment]
> What about file permissions? Are those log files writable by PHP?

Permissions are Windows default permissions. These logs are written by php

**Comment by virtual-designer** [comment]
> > What about file permissions? Are those log files writable by PHP?
> 
> Permissions are Windows default permissions. These logs are written by php

Then no idea. The owners of the repo need to check everything.

**Comment by stu2162583** [comment]
> > > What about file permissions? Are those log files writable by PHP?
> > 
> > 
> > Permissions are Windows default permissions. These logs are written by php
> 
> Then no idea. The owners of the repo need to check everything.

ok，thanks！

**Comment by WinterSilence** [comment]
just try lock after clear cache and get file size
~~~php
if ($this->enableRotation) {
    // clear stat cache to ensure getting the real current file size and not a cached one
    // this may result in rotating twice when cached file size is used on subsequent calls
    clearstatcache(false, $this->logFile);
    $fileSize = filesize($this->logFile) ?: 0;
}
$fp = fopen($this->logFile, 'a');
if ($fp === false) {
    throw new InvalidConfigException("Unable to append to log file: {$this->logFile}");
}
flock($fp, LOCK_EX);
if ($this->enableRotation && $fileSize > ($this->maxFileSize * 1024)) {
~~~
and clear file by 'w' mode
~~~php
private function clearLogFile($rotateFile)
{
    $fp = fopen($rotateFile, 'w');
    if ($fp !== false) {
        fclose($fp);
    }
}
~~~

**Comment by stu2162583** [comment]
> 

Thank you, after testing, there are still some problems.

I tested a rotateByCopy=true before, and the data in the source code was changed to:

```
if ($this->enableRotation && @filesize($this->logFile) > $this->maxFileSize * 1024) {
	@flock($fp, LOCK_UN);
	@fclose($fp);
	$this->rotateFiles();
```
It was changed to prevent windows from reporting errors.
```
if ($this->enableRotation && @filesize($this->logFile) > $this->maxFileSize * 1024) {
	$this->rotateFiles();
	@flock($fp, LOCK_UN);
	@fclose($fp);
```

It seems possible.

**Comment by stu2162583** [comment]
> 

Thank you, after testing, there are still some problems.

I tested a rotateByCopy=true before, and the data in the source code was changed to:

```
if ($this->enableRotation && @filesize($this->logFile) > $this->maxFileSize * 1024) {
	@flock($fp, LOCK_UN);
	@fclose($fp);
	$this->rotateFiles();
```
It was changed to prevent windows from reporting errors.
```
if ($this->enableRotation && @filesize($this->logFile) > $this->maxFileSize * 1024) {
	$this->rotateFiles();
	@flock($fp, LOCK_UN);
	@fclose($fp);
```

It seems possible.

**Comment by WinterSilence** [comment]
@stu2162583 you must unlock file before do something with him

**Comment by stu2162583** [comment]
> @stu2162583 you must unlock file before do something with him

What is this for? Are you afraid of affecting the file handle?
The operation after the lock was changed in version 2.16, and the previous versions were operated before the lock was released.
And if you don't operate in locks, will there be a problem of concurrent rotate?

**Comment by bizley** [comment]
@stu2162583 could you point the change in 2.0.16 that is the cause of that?

**Comment by stu2162583** [comment]
> @stu2162583 could you point the change in 2.0.16 that is the cause of that?

https://github.com/yiisoft/yii2/pull/3563

2.0.16 https://github.com/yiisoft/yii2/blob/2.0.16/framework/log/FileTarget.php
2.0.15.1 https://github.com/yiisoft/yii2/blob/2.0.15.1/framework/log/FileTarget.php

**Comment by bizley** [comment]
So the only thing is that previously file was rotated and then lock was released, after the change it's the other way around. And the change is [here](https://github.com/yiisoft/yii2/commit/25e6cd45c5936cbfa487e1844a436d0b68f2bf1e) made because of [that comment](https://github.com/yiisoft/yii2/pull/3563#issuecomment-425630598) by @nadirvishun

**Comment by WinterSilence** [comment]
@stu2162583 need use `flock($fp, LOCK_EX | LOCK_NB);` or unlock before do something with file.

**Comment by stu2162583** [comment]
@bizley

Yes, he mentioned that the file must be renamed and then closed, but only if it is in a windows environment and rotateByCopy=false.

so, what to do next

**Comment by stu2162583** [comment]
@WinterSilence

Sorry, I don't know much about lock, what is the reason for doing this

**Comment by bizley** [comment]
Looks like we could adjust the process based on the selected options if this is only a matter of type of rotating and the OS.

**Comment by stu2162583** [comment]
> Looks like we could adjust the process based on the selected options if this is only a matter of type of rotating and the OS.

It looks like this, after your testing, make sure.

Waiting for good news.

We are now self-adjusting to no longer limit the number of logs, and we have changed the lock position, and now the log appears to be full.

**Comment by mikehaertl** [comment]
> Sorry, I don't know much about lock, what is the reason for doing this

@stu2162583 See this note in the PHP manual on [flock()](https://www.php.net/manual/en/function.flock.php#refsect1-function.flock-notes):

> flock() uses mandatory locking instead of advisory locking on Windows.

For the difference check e.g. [this](https://bryansoliman.wordpress.com/2011/07/04/mandatory-file-locks-vs-advisory-file-locks-in-oss):

> With the mandatory file-locking mechanism implemented, once a process acquires an exclusive lock, the operating system will prevent any other process from access the locked file. With such mechanism in place, the operating system will prevent access to the locked file until the exclusive lock is released.

> On the other hand, an advisory mechanism provided by the operating system allows processes to find the status of locks and decide what to do. With such mechanism it is up to the process to ensure that the file lock is appropriately acquired and released.

That's why the behavior is different on Linux/Windows. IMO we should check the OS and use the apropriate logic accordingly.

**Comment by stu2162583** [comment]
> > Sorry, I don't know much about lock, what is the reason for doing this
> 
> @stu2162583 See this note in the PHP manual on [flock()](https://www.php.net/manual/en/function.flock.php#refsect1-function.flock-notes):
> 
> > flock() uses mandatory locking instead of advisory locking on Windows.
> 
> For the difference check e.g. [this](https://bryansoliman.wordpress.com/2011/07/04/mandatory-file-locks-vs-advisory-file-locks-in-oss):
> 
> > With the mandatory file-locking mechanism implemented, once a process acquires an exclusive lock, the operating system will prevent any other process from access the locked file. With such mechanism in place, the operating system will prevent access to the locked file until the exclusive lock is released.
> 
> > On the other hand, an advisory mechanism provided by the operating system allows processes to find the status of locks and decide what to do. With such mechanism it is up to the process to ensure that the file lock is appropriately acquired and released.
> 
> That's why the behavior is different on Linux/Windows. IMO we should check the OS and use the apropriate logic accordingly.

thanks, i'll take a look

**Comment by mikehaertl** [comment]
@stu2162583 Is this a site with heavy load? If that's the case then it's probably another (parallel) process that locks the file immediately after your current process released the lock. That's why the file can neither be moved nor truncated.

**Comment by WinterSilence** [comment]
@mikehaertl it can be parallel process

**Comment by mikehaertl** [comment]
Ok I would say that we should *never* release any lock before rotation. This will always cause concurreny issues. A fix should probably:

* Keep `flock()` active until writing + rotation is done
* Disable `rotateByCopy` for Windows systems and make it `true` there by default

**Comment by WinterSilence** [comment]
@mikehaertl solution from PHP manual:

> Because flock() requires a file pointer, you may have to use a special lock file to protect access to a file that you intend to truncate by opening it in write mode (with a "w" or "w+" argument to fopen()).

or by using `flock()` parameter `$would_block`
> The optional third argument is set to 1 if the lock would block (EWOULDBLOCK errno condition).

**Comment by mikehaertl** [comment]
> solution from PHP manual:

That was my second suggestion above.

> or by using flock() parameter $would_block

This has nothing to do with it. We already block execution until the lock file is released by the other process. It's the logic when/what to lock/unlock that is flawed.

**Comment by WinterSilence** [comment]
@mikehaertl 
> This has nothing to do with it.

why? we try re-lock file if `$would_block === 1` or use LOCK_NB: `flock(LOCK_EX | LOCK_NB);`

**Comment by mikehaertl** [comment]
See the linked SO answer that I linked in my last comment above. `$would_block` is basically just a flag that indicates that something is seriously going wrong when accessing the lock file. This is not related to our problem.

And we already use the default of blocking mode. That's fine because we want a 2nd process to wait a (hopefully) short amount of time until the 1st process will release the lock. `LOCK_NB` is not what we want.

**Comment by stu2162583** [comment]
> @stu2162583 Is this a site with heavy load? If that's the case then it's probably another (parallel) process that locks the file immediately after your current process released the lock. That's why the file can neither be moved nor truncated.

Yes, there is still some load.
Thank you for your reply.

**Comment by stu2162583** [comment]
In addition, this problem can also be reproduced in the linux production environment, but I am using the windows development environment, and I do not have a linux test environment locally.

Maybe the problem on linux can be solved by modifying the lock position.

**Comment by mikehaertl** [comment]
Both [suggested fixes](https://github.com/yiisoft/yii2/issues/19259#issuecomment-1049710928) come with a cost (BC break). But I would vote for option 2:

* Fix too early release of lock file
* Drop `rotateByCopy` and make it the default (otherwise locking is still broken as the lock remains on the now renamed file)

Option 1 of using a separate lock file (e.g. `app.log.lck`) would require us to copy the logic from FileMutex or to create an instance of it. It could also lead to problems if that file can not be written to the log directory due to some restrictions.

@samdark @bizley What do you think? It's a bit surprising that this bug exists for many years now. It's also a somewhat sensitive part of the framework so I'm a bit hesitant with any changes there.

**Comment by bizley** [comment]
I agree with option 2 as well. @samdark ?

**Comment by bizley** [comment]
@samdark since this would introduce BC-break we need your approval.

**Comment by samdark** [comment]
Dropping `rotateByCopy` seems to be OK. Needs to be mentioned in UPGRADE though.
