### ISSUE TITLE
ArrayHelper::getValue() ignores default-value on Objects

### ISSUE THREAD

**Issue by HenryVolkmer** [yiisoft/yii2#19267]
### What steps will reproduce the problem?

see [UnitTest in PR](https://github.com/yiisoft/yii2/pull/19266/files#diff-00b01a1a50a01e447580fbd52f7984a1d5180a7520a00f40773c275427c40eb7R825-R833).

**Comment by bizley** [comment]
Closing as mentioned in https://github.com/yiisoft/yii2/pull/19266#issuecomment-1048645034
