### ISSUE TITLE
FileCache's expire duration

### ISSUE THREAD

**Issue by stu2162583** [yiisoft/yii2#19265]
### What steps will reproduce the problem?
$cache->set($key, $value);

### What is the expected result?
expired after 1 year

### What do you get instead?
should never expire

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      |  7.2.26
| Operating system | windows

Our customers have been using our products for more than a year. After investigation, it was found that the cache was missing, and only then did they know the problem.

So is this a bug? Or do I need to explicitly set the duration.

Can it be done forever?

i see source code `vendor\yiisoft\yii2\caching\FileCache.php - setValue()` 

The default value is 0

```
if ($duration <= 0) {
	$duration = 31536000; // 1 year
}
```

**Comment by bizley** [comment]
Indeed this is the implementation for the file cache, I assume it was done like that because it uses touch time, @samdark could you confirm? I think there is no way to make it truly "forever" with that type of caching but you could set duration to a higher value.

**Comment by stu2162583** [comment]
> Indeed this is the implementation for the file cache, I assume it was done like that because it uses touch time, @samdark could you confirm? I think there is no way to make it truly "forever" with that type of caching but you could set duration to a higher value.

It's okay, I haven't encountered such a problem before, so if I'm sure this is OK, I can only manually specify a longer number.

In fact, I have an immature idea, whether to set the file mtime to the time when the yii framework was created or some other important time, so that it can not only have the significance of the times, but also can judge whether it is permanent based on this time, after all, no matter how old it is The users of the yii framework are nowhere near as long.

**Comment by kamarton** [comment]
https://github.com/yiisoft/yii2/blob/7d8507dea8cb390d7f6464093137a628d4a909c6/framework/caching/FileCache.php#L134

Since I think that it cannot be set indefinitely, it should be corrected to 1 year in the documentation.

Cache vs permanent storage: In terms of use, the use of infinite time no longer falls under the concept of cache.

**Comment by samdark** [comment]
Yes, agree.

**Comment by bizley** [comment]
Doc corrected in https://github.com/yiisoft/yii2/pull/19623
