### ISSUE TITLE
unable to set binary column to null

### ISSUE THREAD

**Issue by fullflash** [yiisoft/yii2#19292]
in activerecord we set default to null in rules
also tried manually set field to null in beforeSave action

yii2 debuger shows that in update sql query instead of  field=NULL it s always field=""

**Comment by fullflash** [comment]
awesome support ))

**Comment by terabytesoftw** [comment]
> awesome support ))

I think it's a rude answer, this is open source where we all collaborate to maintain a project, you can go to the telegram or discord channel and ask the question there, or in github discussions and someone can answer, thanks

**Comment by terabytesoftw** [comment]
> thanks for reply. but it was not a how to question. it look like a bug . yii2 ignores null value of field and generates empty string value instead of NULL

If it is a bug, the logical thing is that you write the code that produces it and the error, stack error, the version of yii2, and so, version php, version dbms.
