### ISSUE TITLE
yii message does not get strings with slash Yii (\Yii)

### ISSUE THREAD

**Issue by skiiiks** [yiisoft/yii2#19305]
I have last Yii 2.0.44 December 30, 2021

When I use "./yii messages config.php" to get all the strings to translation system, the files containing this works:
Yii::t('zone', 'Texto');

but the ones containing this does not work (they are not loaded in the messages files after script runs):
\Yii::t('zone', 'Texto');

I never use "use Yii" in any file, and all is working, all loads perfectly. I don't know if there's something related to that.

Obviously, if I change all files and I remove the "\" it will work, but I hope I don't have to change all files because I have both ways in many files ;-)

Is there any way to solve this easily ?

In the config.php I use for the script I have:
`'translator' => ['Yii::t', '\Yii::t'],`

Thank you

P.D. This is something new since I updated Yii ... I can assure this did not happen 2 or 3 months ago. I have all my strings in messages files ... since I updated Yii, now I have all strings defined as \Yii::t() dissapeared from messages files :-(

**Comment by bizley** [comment]
This should be addressed in https://github.com/yiisoft/yii2/pull/18988 - please update to 2.0.45 and recheck.

**Comment by skiiiks** [comment]
2.0.45 fixed the problem Thank you
