### ISSUE TITLE
OCI PHP 8.1: trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by Arkeins** [yiisoft/yii2#19327]
### What steps will reproduce the problem?

Using Yii2 oci with PHP 8.1

### What is the expected result?

No error.

### What do you get instead?

`trim(): Passing null to parameter #1 ($string) of type string is deprecated`

**Comment by wa1kb0y** [comment]
It seems issue is still there
![Screenshot 2022-05-03 at 21 56 53](https://user-images.githubusercontent.com/5966172/166523484-445007fe-3d71-4759-8a12-65e9cf4ea507.png)

**Comment by bizley** [comment]
2.0.46 is not released yet. Check the master.

**Comment by wa1kb0y** [comment]
Im using yii-dev it should contain 2.0.46 chages, but issue in db/Query not fixed yet

**Comment by bizley** [comment]
Ok, that's different. Please open a separate issue, and if you could be so kind it would be great to get a fixing PR for that.

**Comment by srakl** [comment]
i'm still getting this

`trim(): Passing null to parameter #1 ($string) of type string is deprecated`

on 

```
    /**
     * {@inheritdoc}
     */
    public function validateAttribute($model, $attribute)
    {
        $value = $model->$attribute;
        if (!$this->skipOnArray || !is_array($value)) {
            $model->$attribute = call_user_func($this->filter, $value);
        }
    }
 
```

**Comment by victorspfv** [comment]
I have the version 2.0.47 of Yii2 and I'm still getting this

trim(): Passing null to parameter #1 ($string) of type string is deprecated

```
public function validateAttribute($model, $attribute)
    {
        $value = $model->$attribute;
        if (!$this->skipOnArray || !is_array($value)) {
            $model->$attribute = call_user_func($this->filter, $value);        //The error occurred in this line.
        }
    }
```

**Comment by atmanegara** [comment]
same error , Yii 2.0.47 , php 8.1.9 , using $model->validate()
![image](https://user-images.githubusercontent.com/9096711/227764692-1987496a-86b5-4153-b6b4-40ceac3786c1.png)

**Comment by bizley** [comment]
You need to add skipOnEmpty = true if you expect input value to be null so it will be not checked using the selected validator. Also filter with trim can be replaced with the new trim validator that is null safe.
