### ISSUE TITLE
Why FilterValidator change the default value `null` to string `''`

### ISSUE THREAD

**Issue by pfdtk** [yiisoft/yii2#19322]
https://github.com/yiisoft/yii2/blob/7cc45f75f5b68709e86d7f92ec8a51d3eed543ca/framework/validators/FilterValidator.php#L78

if `$value` is null，after validate, it change to string `''`，it case some bug in my program.

**Comment by bizley** [comment]
It's because FilterValidator is not really a validator, it's a filter and as it description says:

> FilterValidator converts the attribute value according to a filter

If you don't want the `null` to be changed consider setting `skipOnEmpty` to `true`.

**Comment by pfdtk** [comment]
@bizley it`s not compatible with lower version (2.0.43),

**Comment by bizley** [comment]
Hmm, you are right, not all filter functions require value to not be `null`, this need to be corrected.
