### ISSUE TITLE
Want a checkbox filter for grid CheckboxColumn

### ISSUE THREAD

**Issue by sharkbit** [yiisoft/yii2#19347]
### What steps will reproduce the problem?
the filter function is currently not written for the CheckboxColumn

### What is the expected result?
would love a simple filter option (Checkbox) to select all the check boxes below.

### What do you get instead?
CheckboxColumn::Filter  not found

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | all
| PHP version      | any
| Operating system | any

**Comment by WinterSilence** [comment]
already exist
https://github.com/yiisoft/yii2/blob/ad1fd84f39c55b265daf19060d9272bdeb297f4a/framework/grid/CheckboxColumn.php#L108

**Comment by sharkbit** [comment]
Works nice BUT Why is that in the header?  Shouldn't it be in the Filter Area,  I want / need the Header so they know why they are clicking.

**Comment by WinterSilence** [comment]
@sharkbit it's not filter

**Comment by sharkbit** [comment]
they you have no column Header just a random checkbox,  `
	'header'=>'Bulk Delete',
	'format' => 'raw',
	'contentOptions' => ['style' => 'text-align: center;'],
	'filter' => ' <input type="checkbox" id="del_sel_all" name="del_sel_all">',
	'value'=>function($model) {return 
		'<input type="checkbox" name="selection[]" value="'.$model->calendar_id.'"onchange="$(this).parent().parent().toggleClass(&quot;danger&quot;);" />'; },
,
`

With some javascript to properly handel it.

`document.getElementById("del_sel_all").addEventListener("click", function(event){
  event.preventDefault();
  
  var checkboxes = document.getElementsByName('selection[]');
    for (var checkbox of checkboxes) {
      checkbox.checked = this.checked;
	  checkbox.parentNode.parentNode.className="danger";
    }
});`

**Comment by WinterSilence** [comment]
@sharkbit look to dictionary and read what's "filter"

**Comment by bizley** [comment]
@sharkbit what kind of filtering would you like to have on that column?

**Comment by sharkbit** [comment]
- If you look at the basic function of this Column, with a Header that toggles all the boxes On or Off,  You would probably also have a button like 'Bulk Delete'.  This is how I would like to use it.  but since I cant use the Filter field, I have to use a normal field mad make my own checkbox field. 
- The Filter field is pretty pointless if you are using the check boxes as bulk delete.   If you are using the Checkbox field as something else, Wouldn't you want an actual Header that made sense.

![image](https://user-images.githubusercontent.com/979670/163570587-b1790777-31c9-4c7d-b167-2dd637d3a3f8.png)

**Comment by sharkbit** [comment]
> 

Not really filtering, just move the check all - check none to that block so I can use the header.

**Comment by bizley** [comment]
As WinterSilence said we already have what is needed to make it work with "check all" functionality. It's not in the "filter" area probably because of the traditional place where this is put usually (but I'm not sure, I wasn't there when it was added). Anyway we would rather not make a change for this placement so I can only recommend overwriting it in your own class in your app. Thanks for the suggestion though, I'm closing it for now.

**Comment by WinterSilence** [comment]
@sharkbit "filters" needs to filter displaying data i.e. this is fields using to generate `WHERE ...` part of SQL query. It's not mass actions.
