### ISSUE TITLE
composer install error：Could not apply patch! Skipping...

### ISSUE THREAD

**Issue by huangyuxine** [yiisoft/yii2#19345]
### What steps will reproduce the problem?
composer install
### What do you get instead?
  - Installing phpunit/phpunit-mock-objects (2.3.8): Extracting archive
  - Installing phpunit/php-file-iterator (1.4.5): Extracting archive
  - Installing phpunit/phpunit (4.8.34): Extracting archive
  - Applying patches for phpunit/phpunit-mock-objects
    https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch (Fix PHP 7 and 8 compatibility)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch

In Patches.php line 326:

  Cannot apply patch Fix PHP 7 and 8 compatibility (https://yiisoft.github.io
  /phpunit-patches/phpunit_mock_objects.patch)!

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.4
| Operating system | macos

**Comment by samdark** [comment]
@marcovtwout would you please take a look?

**Comment by marcovtwout** [comment]
@huangyuxine I cannot reproduce this issue, and both relevant files haven't changed in years. Could be something wrong with your installation, I suggest deleting vendor folder and composer.lock, then reinstall.

If that doesn't solve your problem please provide a full minimal test case that reproduces this issue.

**Comment by spo0okie** [comment]
@marcovtwout same thing
Environment:
Windows 10
git version 2.37.3.windows.1
composer version 2.4.2 2022-09-14

comands to reproduce:
git clone https://github.com/yiisoft/yii2.git .
composer install
got same error

also tested on
Debian 10.13
git 2.20.1
composer 1.8.4
got no error

reproduce on clean windows7 install
+ .net 4.8
+ powershell 5.1
+ chocolatey
commands in powershell:
choco install git
choco install composer (that also installed php 8.1.11)
git clone https://github.com/yiisoft/yii2.git .
composer install

got same error
  - Installing phpspec/prophecy (v1.10.3): Extracting archive
  - Installing phpunit/phpunit (4.8.34): Extracting archive
  0/48 [>---------------------------]   0%
  6/48 [===>------------------------]  12%
 15/48 [========>-------------------]  31%
 22/48 [============>---------------]  45%
 25/48 [==============>-------------]  52%
 29/48 [================>-----------]  60%
 41/48 [=======================>----]  85%
 47/48 [===========================>]  97%
 48/48 [============================] 100%
  - Applying patches for phpunit/phpunit-mock-objects
    https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch (Fix PHP 7 and 8 compatibility)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch

In Patches.php line 326:

  Cannot apply patch Fix PHP 7 and 8 compatibility (https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch)!


looks like it OS dependant error

**Comment by marcovtwout** [comment]
@spo0okie Rerun `composer install` with option `vvv` to get more debug info. Patching is supplied through another composer plugin, see here for a possible list of causes: https://github.com/cweagans/composer-patches/issues?q=cannot+apply+patch

**Comment by bizley** [comment]
I see a lot of mentions at https://github.com/cweagans/composer-patches/ that windows powershell makes it unusable so maybe this is the problem, if you could try windows bash or something similar it would be great.

**Comment by spo0okie** [comment]
@bizley i tried cmd and powershell shells - no luck, then i used linux subsystem for windows to get job done. Just mention that instruction for building test environment (i followed https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/test-environment-setup.md) not working for windows

**Comment by spo0okie** [comment]
@marcovtwout 
```
> post-package-install: cweagans\Composer\Patches->postInstall
> post-package-install: cweagans\Composer\Patches->postInstall
> post-package-install: cweagans\Composer\Patches->postInstall
Downloading https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch
Executing command (CWD): patch "-p1" --no-backup-if-mismatch -d "C:\Joker\Works\yii2.vanilla\vendor/phpunit/phpunit-mock-objects" < "C:\Users\revia\AppData\Local\Temp/633b0c214acf0.patch"
Executing command (CWD): patch "-p0" --no-backup-if-mismatch -d "C:\Joker\Works\yii2.vanilla\vendor/phpunit/phpunit-mock-objects" < "C:\Users\revia\AppData\Local\Temp/633b0c214acf0.patch"
Executing command (CWD): patch "-p2" --no-backup-if-mismatch -d "C:\Joker\Works\yii2.vanilla\vendor/phpunit/phpunit-mock-objects" < "C:\Users\revia\AppData\Local\Temp/633b0c214acf0.patch"
Executing command (CWD): patch "-p4" --no-backup-if-mismatch -d "C:\Joker\Works\yii2.vanilla\vendor/phpunit/phpunit-mock-objects" < "C:\Users\revia\AppData\Local\Temp/633b0c214acf0.patch"
Downloading https://packagist.org/downloads/
[201] https://packagist.org/downloads/

In Patches.php line 326:

  [Exception]
  Cannot apply patch Fix PHP 7 and 8 compatibility (https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch)!


Exception trace:
  at C:\Joker\Works\yii2.vanilla\vendor\cweagans\composer-patches\src\Patches.php:326
 cweagans\Composer\Patches->postInstall() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:200
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:142
 Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:410
 Composer\Installer\InstallationManager::Composer\Installer\{closure}() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:425
 Composer\Installer\InstallationManager->executeBatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:334
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:242
 Composer\Installer\InstallationManager->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:786
 Composer\Installer->doInstall() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:283
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/InstallCommand.php:144
 Composer\Command\InstallCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:1028
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:299  Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:370
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:138
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:88
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:29
```
if composer install not suposed to work in windows just mention it in https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md
no problem

**Comment by marcovtwout** [comment]
@spo0okie It normally works fine on Windows, most likely a problem with your environment. If you want to debug further you could try from cmd/powershell:

1. Is the patch command found and a recent version?
```patch -v```

2. Manually download https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch and then try manually patching:
```
patch "-p1" --no-backup-if-mismatch -d "vendor/phpunit/phpunit-mock-objects" < phpunit_mock_objects.patch
```

Our patch file still looks fine, if you have further questions I suggest to create a ticket upstream: https://github.com/cweagans/composer-patches/

**Comment by spo0okie** [comment]
@marcovtwout there was no patch in my environment. Somehow composer says very clear when missing some php module, but says uninformative errors when whole soft/tool missing.
Next i instal patch with choco pkg manager ang get version 2.5.9 (looks like this is last compiled for windows. cant find any newer)
And it drops error on patching:
```
patch "-p1" --no-backup-if-mismatch -d "vendor/phpunit/phpunit-mock-objects" < phpunit_mock_objects.patch
patching file src/Framework/MockObject/Generator.php
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
```
in linux subsystem (WSL) i have patch 2.7.6 and it get job done with no error
so may be problem in patch 2.5.9?

**Comment by marcovtwout** [comment]
@spo0okie Could be a problem with patch, the "assertion failed" is also mensioned here in the last paragraph with likely causes and solutions: https://stackoverflow.com/a/23909171/729324

But that confirms our patch is fine, so I'm gonna keep this issue closed.

**Comment by marcovtwout** [comment]
Also see https://github.com/cweagans/composer-patches/issues/400 about the composer plugin giving a more useful feedback message.

**Comment by olegbaturin** [comment]
Use v2.0 of composer-patches, it's beta for now.

`"cweagans/composer-patches": "^2.0@dev",`
