### ISSUE TITLE
set_error_handler ignore the error_reporting ini setting

### ISSUE THREAD

**Issue by tanqinwang** [yiisoft/yii2#19352]
php.ini
error_reporting = E_ALL & ~E_NOTICE

Because set_error_handler([$this, 'handleError']) ignore the second paramter.
As [set_error_handler](https://www.php.net/manual/en/function.set-error-handler.php) error_levels says:
Without this mask set **the callback will be called** for every error regardless to the setting of the [error_reporting](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting) setting.

If a script have many E_NOTICE generated, each time it will call the callback and have some lower performance.

Maybe we should replace it with  set_error_handler([$this, 'handleError'], error_reporting()) ???

**Comment by WinterSilence** [comment]
https://github.com/yiisoft/yii2/blob/ad1fd84f39c55b265daf19060d9272bdeb297f4a/framework/base/ErrorHandler.php#L231

**Comment by tanqinwang** [comment]
Maybe should avoid calling the callback function instead of processing them in the callback function.
https://github.com/php/php-src/blob/PHP-7.4.29/Zend/zend.c#L1322
https://github.com/php/php-src/blob/PHP-7.4.29/Zend/zend.c#L1380

**Comment by WinterSilence** [comment]
then you can't manipulate error level in application
