### ISSUE TITLE
SQLSTATE[HY000]: General error: 2014

### ISSUE THREAD

**Issue by easydowork** [yiisoft/yii2#19361]
### What steps will reproduce the problem?
when i set db attributes :
```php
PDO::ATTR_EMULATE_PREPARES => false,
PDO::ATTR_STRINGIFY_FETCHES => false,
```
the api return type of data is same in mysql data type
but in yii2 Transaction nesting whill be error:
```php
//'SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
The SQL being executed was: SAVEPOINT LEVEL1',
```
when setting MYSQL_ATTR_USE_BUFFERED_QUERY is true i, i get the same error
but is not have error when php >= 7.4 version in this setting.
### What is the expected result?
no error when i use Transaction nesting 
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | php7.3
| Operating system |centos

**Comment by WinterSilence** [comment]
`truncate` and `alter table` as well as other DDL queries are called in mysql [implicit commit](https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html).

A commit (or rollback), whether explicit or not, immediately releases all declared savepoints.  After that, Yii which does not take into account such a surprise, receives a natural error when working with an already deleted savepoint.

**Comment by easydowork** [comment]
> 

so what shoud I do when i write code

**Comment by easydowork** [comment]
> `truncate`以及在 mysql[隐式提交](https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html)`alter table`中调用其他 DDL 查询。[](https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html)
> 
> 提交（或回滚），无论是否显式，都会立即释放所有声明的保存点。之后，没有考虑到这种意外情况的 Yii 在处理已删除的保存点时会收到一个自然错误。

so what shoud I do when i write code

**Comment by WinterSilence** [comment]
at first show you model (or code generated error)

**Comment by alex-code** [comment]
If it works in PHP 7.4+ then using a new version would be the better option.
PHP 7.3 is end of life since Dec 21.

**Comment by easydowork** [comment]
> If it works in PHP 7.4+ then using a new version would be the better option. PHP 7.3 is end of life since Dec 21.

Only when php8.1 does not configure the pdo attribute, the php data is the same as the database type, and the windows system php7.4 and php8.0 cannot do it. By the way, my database is installed on a remote linux system.

**Comment by WinterSilence** [comment]
@easydowork 
> so what shoud I do when i write code

don't executes implicit commits in transaction. in common cases, implicit commit is `truncate`, then you can replace it to delete statement

@bizley it's not pdo/framework error, just user try rollback irreversible changes
