### ISSUE TITLE
`yii\widgets\ListView` ignores the pagination initialization

### ISSUE THREAD

**Issue by maximal** [yiisoft/yii2#19360]
While investigating into [@charlesportwoodii/yii2-psr7-bridge#9](https://github.com/charlesportwoodii/yii2-psr7-bridge/issues/9) I found out that the `yii\widgets\ListView` widget doesn’t initialize its `->pager->pagination` class with the passed properties.

### Steps to reproduce the problem
My view file:
```php
<?php
/** @var $dataProvider */
echo \yii\widgets\ListView::widget([
	'layout' => "<div>{items}</div><br /><br /><div>{pager}</div>",
	'dataProvider' => $dataProvider,
	'itemView' => 'item',
	'pager' => [
		'pagination' => [
			// Not filled in the pagination instance
			'params' => ['type' => 'some_type', '#' => 'asdf'],
			// Should fail due to setting unknown property, but it won’t
			'inexistent_property' => 'dummy',
		],
		// Fails as expected if uncommented
		//'inexistent_property' => 'dummy',
	],
]);
```

### The expected result
`->pager->pagination->params` is filled by the passed array, passing `inexistent_property` throws an exception.

### What do you get instead?
All the initialization properties are ignored.

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.1
| Operating system | Ubuntu / MacOS

**Comment by bizley** [comment]
As stated in the documentation if dataProvider's pagination is `false` or there are no items in the collection, pager is not rendered and its config is ignored.

**Comment by bizley** [comment]
Well, you cannot blame me for assuming data you did not provide. Anyway - `pagination` of the pager is also taken from the `dataProvider`s `pagination` and overwrites any provided in the `pager` config:

https://github.com/yiisoft/yii2/blob/master/framework/widgets/BaseListView.php#L45

> Note that the widget must support the `pagination` property which will be populated with the
  [[\yii\data\BaseDataProvider::pagination|pagination]] value of the [[dataProvider]] and will overwrite this value.

**Comment by maximal** [comment]
@bizley, not blaming you, of course ❤️
I didn't know about this overwriting. Thanks, it helps!
