### ISSUE TITLE
 Return type of yii\web\SessionIterator::current() should either be compatible with Iterator::current()

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#19398]
```
yii\base\ErrorException: During inheritance of Iterator: Uncaught yii\base\ErrorException: Return type of yii\web\SessionIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/eurotools/public_html/vendor/yiisoft/yii2/web/SessionIterator.php:60

Stack trace:
#0 /home/eurotools/public_html/vendor/yiisoft/yii2/web/SessionIterator.php(16): yii\base\ErrorHandler->handleError()
#1 /home/eurotools/public_html/vendor/yiisoft/yii2/BaseYii.php(293): include('...')
#2 /home/eurotools/public_html/vendor/yiisoft/yii2/web/Session.php(667): yii\BaseYii::autoload()
#3 /home/eurotools/public_html/vendor/yiisoft/yii2/base/Component.php(139): yii\web\Session->getIterator()
```

### Additional info
This is because of missed return types of `SessionIterator implements \Iterator`:
```
public function current()
```

But `\Iterator` declare:
```
public function current(): mixed;
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      |  8.1
| Operating system | debian

**Comment by WinterSilence** [comment]
Hm.. I'm test it and can't find any problems https://3v4l.org/7ldOG#v8.1.6

**Comment by dicrtarasov** [comment]
This is the syntax error, it can not be no problem definitely.

**Comment by WinterSilence** [comment]
@dicrtarasov no syntax or any other errors are not detected. Extended class can omit parent's types.

**Comment by dicrtarasov** [comment]
Yes, generally children methon can make return type narrow, but not wider. When no return type specified, it assume "mixed", which is widelly, then Iterator.

**Comment by dicrtarasov** [comment]
You can test it :) Parent -> child:
mixed -> Iterator - Ok
Iterator -> mixed - Error

Child can return only subclass of parent type compatibility.

**Comment by dicrtarasov** [comment]
As you can see, Error in this report is real. Try to google it.

**Comment by dicrtarasov** [comment]
PHP 8.1

**Comment by WinterSilence** [comment]
@dicrtarasov can you add tests to detect your error?
> When no return type specified, it assume "mixed", which is widelly, then Iterator.

> Большинство неокончательных внутренних методов теперь требуют переопределяющих методов для объявления совместимого возвращаемого типа, в противном случае во время проверки наследования выдаётся уведомление об устаревании возможности. В случае, если тип возвращаемого значения не может быть объявлен для метода переопределения из-за проблем совместимости версий PHP, можно добавить атрибут #[ReturnTypeWillChange], чтобы заглушить уведомление об устаревании.
https://www.php.net/manual/ru/migration81.incompatible.php

**Comment by dicrtarasov** [comment]
Атрибут #[ReturnTypeWillChange] решит эту проблему.

**Comment by WinterSilence** [comment]
@dicrtarasov
https://github.com/yiisoft/yii2/blob/6599713d2bcf4440190cec2b950b1738d7ddfae4/framework/web/SessionIterator.php#L62

**Comment by dicrtarasov** [comment]
Yii 2.0.45

**Comment by WinterSilence** [comment]
@bizley can be close, already fixed

**Comment by bizley** [comment]
Great.
