### ISSUE TITLE
migrate doesn't work after migrate/down and editing the migration file

### ISSUE THREAD

**Issue by sprngLf** [yiisoft/yii2#19393]
ran 
```
php yii migrate/down
```` 
works fine.

---
modified the migration file e.g. `m220514_022156_create_user_table`
ran
```
php yii migrate
```` 
error:
```
Total 1 new migration to be applied:
        m220514_022156_create_user_table

Apply the above migration? (yes|no) [no]:yes
*** applying m220514_022156_create_user_table
...
...
0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

This should let me `migrate` after `migrate/down` and modified migration file.

---
### Found the problem:
`migrate/down` doesn't delete the `version` entry in `migrations` table e.g., `m220514_022156_create_user_table`.

`migrate/down` should delete `m220514_022156_create_user_table` from `migrations` table
so I will be able to `migrate` after `migrate/down` and modifying the migration file.

**Did I miss something? Is this the intended behavior of `migrate/down`?**

---

### Environment Info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      |  8.1.2
| Database     | mysql  Ver 15.1 Distrib 10.4.22-MariaDB, for Win64
| Server | xampp/apache
| Operating system | Windows 10

**Comment by bizley** [comment]
No, `migrate/down` deletes the entry in `migrations`. I don't know why it didn't work in your case but since this is the first report about the problem please check your side throughout.

I'm not sure as well if it did not indeed deleted the entry since you provided us with error text where it states that migration will be applied - if this entry would not be deleted, you would not see that text.

**Comment by sprngLf** [comment]
> No, `migrate/down` deletes the entry in `migrations`. I don't know why it didn't work in your case but since this is the first report about the problem please check your side throughout.
> 
> I'm not sure as well if it did not indeed delete the entry since you provided us with error text where it states that migration will be applied - if this entry would not be deleted, you would not see that text.

It now works fine. My bad I may have messed something up but I cannot reproduce the problem anymore.

**Comment by bizley** [comment]
Ok, no problem. I'll close it for now, if anything new develops please write here and we will open it again.
