### ISSUE TITLE
some widgets are incompatible with the default bootstrap 4 package (namely LinkPager)

### ISSUE THREAD

**Issue by Lumethys** [yiisoft/yii2#19410]
### What steps will reproduce the problem?
Follow the start guide or use gii to render a view page with pagination

### What is the expected result?
the pagination section should have it CSS styling via bootstrap 4

### What do you get instead?
the pagination section have no CSS styling

### Additional info
the LinkPager widget still use the bootstrap 3 syntax:

```
<ul class="pagination">
  <li><a href="#">Previous</a></li>
  <li><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#">Next</a></li>
</ul>
```

instead of bootstrap 4 syntax:

```
<ul class="pagination">
  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
  <li class="page-item"><a class="page-link" href="#">1</a></li>
  <li class="page-item"><a class="page-link" href="#">2</a></li>
  <li class="page-item"><a class="page-link" href="#">Next</a></li>
</ul>
```

To be more precise, the `LinkPager` Widget missing the `"page-item"` class for the `<li>` element and `"page-link"` class for the `<a>` element (additionally, the `<span>` element for disabled button still need the `"page-link"` class to display its css styling)

The default bootstrap folder generated by the `yii create-project` command is bootstrap 4, so I think other templates should conform to this. The fix is relatively easy, just need to add `"page-item"` to the following:

```
public $firstPageCssClass = 'first';
public $lastPageCssClass = 'last';
public $prevPageCssClass = 'prev';
public $nextPageCssClass = 'next';
```

to

```
public $firstPageCssClass = 'first page-item';
public $lastPageCssClass = 'last page-item';
public $prevPageCssClass = 'prev page-item';
public $nextPageCssClass = 'next page-item';
```

For the `"page-link"`, just need to add `$disabledItemOptions['class'] = 'page-link';` and `$linkOptions['class'] = 'page-link';` in the `RenderPageButton` function

**(This is just my quick fix, I don't know if this is the best approach)**

Additionally, 1 more suggestion, the active page (current page) should also be set as a disabled button, as a link to current page is generally useless

| Q                           | A
| ------------------- | ---
| Yii version             | 2.0.45
| PHP version          |  7.4.29
| Operating system | windows 10

**Comment by bizley** [comment]
Isn't the case that you are using LinkPager from the core package (`yii\widgets\LinkPager`) instead of the one from the B4 package (`yii\bootstrap4\LinkPager`)?

**Comment by Lumethys** [comment]
> Isn't the case that you are using LinkPager from the core package (`yii\widgets\LinkPager`) instead of the one from the B4 package (`yii\bootstrap4\LinkPager`)?

I use the gii feature, if gii used the wrong widget, then this is a gii bug

**Comment by bizley** [comment]
I'm not sure if Gii has been updated to generate code with BS4 but if you are using the newest one than obviously not. This would be nice feature to add there but since this is not a bug we will not do anything in the Yii core for now.
