### ISSUE TITLE
PHP 8.1 Gii Error in Model Preview & Generation

### ISSUE THREAD

**Issue by gthaka** [yiisoft/yii2#19421]
### What steps will reproduce the problem?
1. Open Gii Code Generator.
2. Go to Model Generator.
3. Select desired table and click Preview.
An issue similar to #19380 

### What is the expected result?
Preview and Generate Model File
### What do you get instead?
**```trim(): Passing null to parameter #1 ($string) of type string is deprecated```**

![image](https://user-images.githubusercontent.com/6692971/171065423-7fd42f64-89d4-4280-bf19-0180bc2ae71f.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 8.1
| Operating system | Linux

**Comment by rhertogh** [comment]
@gthaka I think this is already fixed with https://github.com/yiisoft/yii2-gii/pull/502. It's not released yet so could you please try it with the latest development version (`"yiisoft/yii2-gii": "dev-master"` in composer.json).

**Comment by PendalF89** [comment]
Still have this problem at Yii2 2.0.46, PHP 8.1.9, MacOS.

**Comment by samdark** [comment]
Yes. I'll tag Gii release soon.

**Comment by Tahiaji** [comment]
Released and fixed: https://github.com/yiisoft/yii2-gii/releases/tag/2.2.5
