### ISSUE TITLE
Security Issues of Codeception used by Yii2.

### ISSUE THREAD

**Issue by codyng** [yiisoft/yii2#19439]
Hi there,

I found that Codeception used by Yii2 is very old which create security vulnerabilities.
That Codeception replies on very old library libreoffice 6.x.x which suffers the security vulnerabilities and should be upgraded to the latest version. 

Is Yii2 not safe enough?? As it says it is fast, secure and efficient in the main page.

Can we safely remove it for production use??

Thank you.

**Comment by bizley** [comment]
What do you mean? Codeception that is used in the app template? This is only for project skeleton, and indeed waiting for a long due update. Anywho:
1. Codeception is for the tests and should not be present on the prod.
2. App template is just a skeleton and you are free to modify it as you wish.
3. Yii core does not depend on Codeception in any way.
4. You should not have ANY `require-dev` dependencies on the prod.

**Comment by nadar** [comment]
Its a bit off topic, but it really seems that they don't care to much about "latest technology", docker images seems to be php 7.4 (https://github.com/Codeception/Codeception/issues/6465, https://github.com/Codeception/Codeception/issues/6472)
