### ISSUE TITLE
Error at install by Composer

### ISSUE THREAD

**Issue by lesha724** [yiisoft/yii2#19449]
After clone repository by git and run `composer install`:
![1](https://user-images.githubusercontent.com/8524434/174150920-5a6cb0fd-80aa-4ff0-80cc-3589546df7de.PNG)

This only Windows when run in phpstorm terminal, in git bash all works , same [issue ](https://github.com/yiisoft/yii2-gii/issues/442)

**Comment by lubosdz** [comment]
What PHP version do you use in HTTP mode and what version in CLI (console) mode?

**Comment by lesha724** [comment]
@lubosdz, 7.4.26

**Comment by MarkoNV** [comment]
Can confirm, both PHP 7.4 and PHP 8.1 on Windows.

**Comment by bizley** [comment]
This has been reported already. Your Windows environment does not have the `patch` package. See https://github.com/yiisoft/yii2/issues/19345 . Unfortunately we cannot help here (but maybe we can add some warning, let me look into this).
