### ISSUE TITLE
PostgreSQL nested transactions

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#19442]
### What steps will reproduce the problem?
```php
		$transaction = $this->db->beginTransaction();
		try {
			foreach ($data as $row) {
				$checkpoint = $this->db->beginTransaction();
				try {
					// some code
					$checkpoint && $checkpoint->isActive && $checkpoint->commit();
				} catch (Throwable $e) {
					$this->error($e->getMessage());
				} finally {
					$checkpoint && $checkpoint->isActive && $checkpoint->rollBack();
				}
			}
			$transaction && $transaction->isActive && $transaction->commit();
		} catch (Throwable $e) {
			$this->error($e->getMessage());
		} finally {
			$transaction && $transaction->isActive && $transaction->rollBack();
		}
```
### What is the expected result?
$checkpoint in finally inactive and don't rollback after $checkpoint commit 

### What do you get instead?
$checkpoint in finally active and rollback $transaction, $transaction inactive when try to commit and in finally

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46-dev
| PHP version      | 7.4.29
| Operating system |

**Comment by bizley** [comment]
It doesn't work like that - if you want to depend on the `isActive` you need to also check if the transaction's own level is the current  transactions' stack level (like [here](https://github.com/yiisoft/yii2/blob/f72310c398759841a0f8b52e1aba7990086c0d9c/framework/db/Connection.php#L818)).
