### ISSUE TITLE
ErrorHandler - Wrong php doc for $exception property

### ISSUE THREAD

**Issue by tjura** [yiisoft/yii2#19458]
### What steps will reproduce the problem?
When you do a mistake in code like this:
```php
$string = 'example';
array_key_exists($string , 10);
```
You got https://www.php.net/manual/en/class.typeerror.php that implements Throwable and is not extended by \Exception
So if you implementing errorHandler `Yii::$app->errorHandler->exception` you got wrong hints
That's lead to wrong code usage like this `public ?Exception $exception`

Its most important in PHP 8.x because newest version of php allow you to easily catch all `\Throwables`
See my exception catch tests: https://onlinephp.io/c/cca6a

### What is the expected result?
Line 43 in ErrorHandler.php
```php
    /**
     * @var \Throwable|null the exception that is being handled currently.
     */
    public $exception;
```

Line 113 in ErrorHandler.php
```php
/**
     * Handles uncaught PHP exceptions.
     *
     * This method is implemented as a PHP exception handler.
     *
     * @param \Throwable $exception the exception that is not caught
     */
    public function handleException($exception)
```

### What do you get instead?
Line 43 in ErrorHandler.php
```php
    /**
     * @var \Exception|null the exception that is being handled currently.
     */
    public $exception;
```

Line 113 in ErrorHandler.php
```php
/**
     * Handles uncaught PHP exceptions.
     *
     * This method is implemented as a PHP exception handler.
     *
     * @param \Exception $exception the exception that is not caught
     */
    public function handleException($exception)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.1.7
| Operating system | Docker php:8.1-fpm

**Comment by bizley** [comment]
The docs for that have been already corrected, please try the latest master until the release.
