### ISSUE TITLE
Yii2 still lose PDOConnection error codes on some functions

### ISSUE THREAD

**Issue by Roguyt** [yiisoft/yii2#19454]
Following up my comment from here : https://github.com/yiisoft/yii2/issues/18203#issuecomment-1163184592

Similarly to what used to happens on SQL queries, https://github.com/yiisoft/yii2/blob/079ca8f647a9592c3269e0d4dec164f3533e1409/framework/db/Connection.php#L647 and https://github.com/yiisoft/yii2/blob/079ca8f647a9592c3269e0d4dec164f3533e1409/framework/db/Command.php#L272 are still casting the SQL error code to an INT which loses data in case of DB timeout.

### What steps will reproduce the problem?

Generating any Connection error will result in this behaviour (Internet loss, timeout, etc)

### What is the expected result?

HYT00

### What do you get instead?

0

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 8.0
| Operating system | MacOS

**Comment by samdark** [comment]
Do you have some time to prepare a pull request fixing it?

**Comment by Roguyt** [comment]
@samdark Sure, I can make a PR later this week.
