### ISSUE TITLE
ClientValidation broken with script tag in attribute label

### ISSUE THREAD

**Issue by luke-** [yiisoft/yii2#19462]
### What steps will reproduce the problem?

- Create a form and model with attribute label e.g. `Test Label<script>alert("1")</script>`
- Without `enableClientValidation` the attribute label is properly encoded
- With `enableClientValidation` a script alert is shown and broken HTML appears

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.latest
| PHP version      | any
| Operating system | any

**Comment by bizley** [comment]
Please provide the code used to place the label in the view.

**Comment by luke-** [comment]
Here a example:

Model:

```php
class Example extends ActiveRecord
{
    public function attributeLabels()
    {
        return [
            'newPassword' => Yii::t('base', 'New password').'<script>alert("1")</script>',
        ];
    }
   // ...
}
```


View: 

```php
    <?php $form = ActiveForm::begin(['enableClientValidation' => true]); ?>
    ...
    <?php echo $form->field($model, 'newPassword')->passwordInput(['maxlength' => 45]); ?>
```

**Comment by bizley** [comment]
Hmm, I can see that label is not encoded by default. It was long time ago last time I checked this but isn't it by design?  `enableClientValidation` has nothing to do with it.

**Comment by luke-** [comment]
Hmm, here attribute lables seems to by encoded by default. Screenshot of the example code: 
![image](https://user-images.githubusercontent.com/4736168/176664844-8c602687-d86d-4911-8723-6871da61a6be.png)


![image](https://user-images.githubusercontent.com/4736168/176665211-260a4fd0-167e-4da7-9af4-6b1042f257c9.png)

**Comment by bizley** [comment]
Oh, I see, so the label is placed as is as a part of client validation JS code.

**Comment by bizley** [comment]
I can confirm labels are indeed encoded but apparently not when used inside the JS.

**Comment by samdark** [comment]
We should encode them for JS as well.
