### ISSUE TITLE
Mutated camel2words broke existing apps

### ISSUE THREAD

**Issue by Eseperio** [yiisoft/yii2#19467]
The change introduced in cf1600411cbf71d1c28f81b64430b6319eef5f6e has broke all our REST apps which use `v1/...` as endpoint since we were using camel2words to build url patterns. The same will happen in all other apps which use `Inflector::camel2words` and `Inflector::slug` to generate url or tokens.

A change to a so older function should be done with a parameter or a warning in upgrade notes. I suggest adding a warning to upgrade notes.

### What steps will reproduce the problem?
Having a module named `v1`, create patterns for url from classes namespaces and the use of `Inflector::camel2words` and `Inflector::slug` to convert, i.e; `v1/customerOrders/index` to `v1/customer-orders/index`.

### What is the expected result?
`v1/default/index` returns `DefaultController::actionIndex`
### What do you get instead?
The action is not being resolved by real controller, because the patterns generated are `v-1/customer-orders/index`, but only fails on POST requests.
```
{"name":"Method Not Allowed","message":"Method Not Allowed. This URL can only handle the following request methods: GET, HEAD.","code":0,"status":405,"type":"yii\\web\\MethodNotAllowedHttpException"}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.0
| Operating system | MacOS

**Comment by samdark** [comment]
Thanks for an issue. Need to update UPGRADE. Reverting it will break apps again.

**Comment by Eseperio** [comment]
There is still one behavior to investigate, but i´m lack of time. Why it only happens when request is POST and not GET

**Comment by handcode** [comment]
I don't think this is "just a documentation issue" as the change in cf1600411cbf71d1c28f81b64430b6319eef5f6e has some other "strange" side effects if number in $name is  is preceded by `_` or `-`

Example:
```
echo Inflector::camel2words('pic_3_url');
echo Inflector::camel2words('pic-3-url');
```

Result: `pic  3 url` (2 whitespaces before 3)
Expected: `pic 3 url`

Of course, one could say that camel2words is used incorrectly here (for this input), but this is exactly what is used in various places. For example: in the [gii model generator to create the labels](https://github.com/yiisoft/yii2-gii/blob/master/src/generators/model/Generator.php#L389).

**Comment by WinterSilence** [comment]
@samdark #19204 is break BC and must be rollback

**Comment by samdark** [comment]
@WinterSilence it was already released so rollback is another BC break.

**Comment by WinterSilence** [comment]
@samdark and what's now? rewrite existing applications? I think these changes will break more old apps than new ones at rollback.

**Comment by Eseperio** [comment]
It was a mistake, but @WinterSilence is right. The less harmful way to do it is reverting the change. I think there are less applications up to date, so it will be less hours of work reverting it on an easy way, like introducing a param to enable parsing numbers as words.

**Comment by samdark** [comment]
Alright. Let's revert it.

**Comment by WinterSilence** [comment]
2beers2@Eseperio
