### ISSUE TITLE
ActiveRecord::insert(). When insert row, it does not write fields.

### ISSUE THREAD

**Issue by alexeyp0708** [yiisoft/yii2#19483]
PHP 7.4
Yii 2.0.45
The problem showed up when I created an empty model and tried to make a new entry.
The record was created, but the fields were not written.

Migration
```php
<?php

use yii\db\Migration;

class m220725_134053_test extends Migration
{

    public function safeUp()
    {
        $this->createTable('{{%test}}', [
            'id' => $this->primaryKey(),
            'field'=>$this->char(100),
            'field2'=>$this->boolean()->defaultValue(true)
    }


    public function safeDown()
    {
        $this->dropTable('{{%test}}');
    }

}
```

Controller

```php
<?php

namespace app\controllers;

use app\models\MyModel;
use yii\web\Controller;

class TestController extends Controller
{
    public function actionIndex()
    {
        $model=new MyModel();
        $model->insertData();
    }
}
```
Model
```php
<?php


namespace app\models;

use yii\db\ActiveRecord;

class MyModel extends ActiveRecord 
{
    public string $field='';
    public bool $field2=true;
    public static function tableName()
    {
        return '{{test}}';
    }
    public function rules()
    {
        return [
            [['field', 'field2'], 'required'],
        ];
    }
   
    public function insertData()
    {
        $model=new static();
        $model->setAttributes(['field'=>'test','field2'=>false]);
        //or 
        //$model->field='test'; $model->field2=false; 
        $model->insert();
    }
}
```
result for route `test/`
Writing to the database

| id | field | field2 |
| --- | --- |---|
| 1 | null |  true |

### How to solve the problem successfully.
In the model, it is necessary to exclude the declaration of properties / attributes

```php
<?php


namespace app\models;

use yii\db\ActiveRecord;

class MyModel extends ActiveRecord 
{
    //public string $field='';
    //public bool $field2=true;
    public static function tableName()
    {
        return '{{test}}';
    }
    public function rules()
    {
        return [
            [['field', 'field2'], 'required'],
        ];
    }
    public function insertData()
    {
        $model=new static();
         $model->setAttributes(['field'=>'test','field2'=>false]);
        $model->insert(); 
    }
}
```
| id | field | field2 |
| --- | --- |---|
| 1 | null |  true |
|2|test|false|

the problem occurs because the private property BaseActiveRecord::_attributes
https://github.com/yiisoft/yii2/blob/8f2e182872af94685c6bb4fc524a362f797b88ae/framework/db/BaseActiveRecord.php#L88
empty.
 This property uses the BaseActiveRecord::getDirtyAttributes method
 https://github.com/yiisoft/yii2/blob/8f2e182872af94685c6bb4fc524a362f797b88ae/framework/db/BaseActiveRecord.php#L627
  to
create a list of fields for the method
ActiveRecord::insertInternal which makes the recording
https://github.com/yiisoft/yii2/blob/8f2e182872af94685c6bb4fc524a362f797b88ae/framework/db/ActiveRecord.php#L598

Perhaps somewhere the logic of adding attributes is broken.
or maybe BaseActiveRecord::getDirtyAttributes
must not be used in ActiveRecord::insertInternal

**Comment by alexeyp0708** [comment]
As an alternative solution
```php
<?php


namespace app\models;

use yii\db\ActiveRecord;


class Model extends ActiveRecord
{
    protected function reflectFields(array $fields=null)
    {
        if(is_null($fields)){
            $fields=$this->attributes();
        }
        foreach ($fields as $key) {
            if(property_exists($this,$key)){
                $this->__set($key,$this->$key);
            }
        }
        return $this;
    }
}
```

```php

<?php


namespace app\models;



class MyModel extends Model 
{
    public string $field='';
    public bool $field2=true;

    public static function tableName()
    {
        return '{{test}}';
    }
    public function rules()
    {
        return [
            [['field', 'field2'], 'required'],
        ];
    }
   
    public function insertData()
    {
        $model=new static();
        $model->field2=false; 
        $model->field='tessdfsfdst';
        $model->reflectFields()->insert(); // reflect the model fields in the hidden properties of ActiveRecord
    }
}
```

**Comment by bizley** [comment]
You should not define the properties in the ActiveRecord model the same as the mapped DB columns as mentioned in [the Guide](https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#accessing-data).

> Note: The Active Record attributes are named after the associated table columns in a case-sensitive manner. Yii automatically defines an attribute in Active Record for every column of the associated table. You should NOT redeclare any of the attributes.

**Comment by alexeyp0708** [comment]
@bizley https://www.yiiframework.com/doc/guide/2.0/en/structure-models

**Comment by alexeyp0708** [comment]
@bizley https://en.wikipedia.org/wiki/Active_record_pattern
If "Magic" is implemented in the class, then it should reflect the behavior of the Pattern. Otherwise, this behavior is unpredictable. The programmer must intuitively understand how this or that component is implemented, and does not study the entire dock and code to figure out what is wrong.
Refer to other modern frameworks where ActiveRecord is implemented and understand that it is better to make the object transparent in behavior

**Comment by alexeyp0708** [comment]
But judging by how quickly you close the Topic, then you probably do not have a goal to develop your product.

**Comment by bizley** [comment]
Why so salty? I'm just saying that this way of Active Record implementation is well established in Yii 2 and for a quite long time. I wasn't there when it was created, and I'm aware of better ones existing already elsewhere. I'm just pointing to the documentation where the expected (by Yii 2) way is stated to help you with your code.
As for the developing Yii 2 - there is [Yii 3](https://forum.yiiframework.com/c/yii-3-0/63) on its way, where the development is rolling currently.

**Comment by alexeyp0708** [comment]
@bizley
 -Why so salty?
- because I had to sweat.

---
Yii 3 is being created for a long time.
---
I was just looking for a problem in my code, but it turned out that I had nothing to do with it.
In this situation, I proceeded from the fact that the Model Class describes the data structure as an entity (Entry). If you explicitly describe the model, then the code is quite transparent, both for me and for other programmers, and for this you do not need to study the structure of the tables.
Further, the ActiveRecord class inherits the yii\base\Model class, which implies the use of the behavior of this class as an entity.

It turned out that it is necessary to assign attributes only with the help of "magic".

**Comment by alexeyp0708** [comment]
not to flood other topics.
How to deal with this trouble*?
Table  
| id  | field | field2 |   
| --- | --- | --- |   
| 100 | Hello | false |   

```php
<?php


namespace app\models;

use yii\db\ActiveRecord;

class MyModel extends ActiveRecord
{
    /**
     * @property string $field
     * @property bool $field2
     */
    
    public static function tableName()
    {
        return '{{test}}';
    }
    public function rules()
    {
        return [
            [['field', 'field2'], 'required'],
        ];
    }
   

    public function updateData()
    {
        $model=new static();
        $model->id=100;// Logically, when specifying a primary key, the model should be updated.
        $model->field='qwerty';
        $model->field2=false;
        $model->save();//       method tries to insert instead of update  and throw an error
        // or $model->update(); // not update. return false
    }
}
```
result
``` 
Integrity constraint violation – [yii\db\IntegrityException](http://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html)
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '100' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `food_providers` (`id`, `name`, `is_enabled`) VALUES (100, 'qwerty', 0)
```
```
To hack this behavior, you have to do this.
```php 
<?php


namespace app\models;

use yii\db\ActiveRecord;

class MyModel extends ActiveRecord
{
    /**
     * @property string $field
     * @property bool $field2
     */
    
    public static function tableName()
    {
        return '{{test}}';
    }
    public function rules()
    {
        return [
            [['field', 'field2'], 'required'],
        ];
    }
   

    public function updateData()
    {
        $model=new static();
        $model->id=100;
        $model->field='update_qwerty';
        $model->field2=false;
        // hack
        $old_attributes=$model->getOldAttributes();
        foreach($model->primaryKey() as $key){
            $old_attributes[$key]=$model->$key;
        }
        $model->setOldAttributes($old_attributes);
        //---
        $model->save();//       success update
        // or $model->update(); //   success update
    }
}
```
I understand that you can come up with something else and get around the situation. Then Yii ActiveRecord is not completely an ActiveRecord pattern, but is some kind of similarity.
