### ISSUE TITLE
Debug crashes

### ISSUE THREAD

**Issue by matias-yii** [yiisoft/yii2#19484]
### What steps will reproduce the problem?
run an action that fails using a rest controller
### What is the expected result?
Enter to debug and see what did it fail?
### What do you get instead?
and error that  crash debug panel:

PHP Warning – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Trying to access array offset on value of type null
file: /yiisoft/yii2-debug/src/views/default/panels/request/summary.php
line 9:  $statusCode = $panel->data['statusCode'];
### Additional info
Proposal:  change line 9 with this:
$statusCode = isset($panel->data['statusCode']) ? $panel->data['statusCode'] : Null;

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      |  8.1.2
| Operating system | Linux (Distro: Ubuntu 22.04 LTS)

**Comment by bizley** [comment]
You already reported it https://github.com/yiisoft/yii2-debug/issues/491

**Comment by bizley** [comment]
PR fixing it is more than welcome though ;)
