### ISSUE TITLE
getAuthKey() method in User class called even though enableAutoLogin is set to false

### ISSUE THREAD

**Issue by twintrigger** [yiisoft/yii2#19494]
### What steps will reproduce the problem?
User component configuration:
```
'user' => [
    'identityClass' => 'app\models\User',
    'enableAutoLogin' => false,
    'loginUrl' => null,
],
```
The `getAuthKey()` method from `app\models\User`:
```
public function getAuthKey()
{
    throw new NotSupportedException('"getAuthKey" is not implemented.');
}
```

### What is the expected result?
User should be able to log in without issue using the proper credentials.

### What do you get instead?
The `NotSupportedException` is thrown.

The `getAuthKey()` method should not be called when `enableAutoLogin` is set to false. The `switchIdentity()` method in `yii\web\User` doesn't check for `enableAutoLogin` before the `authKeyParam` is added to the session.

Original (line 664 of `yii\web\User`):
```
$session->set($this->authKeyParam, $identity->getAuthKey());
```
Should be something comparable to:
```
if ($this->enableAutoLogin) {
    $session->set($this->authKeyParam, $identity->getAuthKey());
}
```

### Additional info

| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.1
| Operating system |Ubuntu 20

**Comment by bizley** [comment]
If I understand correctly `enableAutoLogin` is for cookies, with `authKey` the session is "signed" so when the `enableSession` is true it can be used to validate session.

**Comment by samdark** [comment]
@bizley is correct.
