### ISSUE TITLE
relation eager loading not working

### ISSUE THREAD

**Issue by spo0okie** [yiisoft/yii2#19507]
### What steps will reproduce the problem?

There is 3 entity
  * Service - some Soft installed on VM (may be instaleld on many VMs for clustered services)
  * Comp - VM which running Service 
  * Arm - Physical PC/Laptop which runs VMs (may run many) which runs services

Tables is like
services:
  * id 

comps_in_services:
  * id
  * comps_id
  * services_id

os:
  * id
  * arms_id

arms:
  * id

so i wish to know which physical PCs involved in clustered service stability:
```
class Services extends \yii\db\ActiveRecord
{
    ...
	public function getComps()
	{
		return static::hasMany(Comps::class, ['id' => 'comps_id'])
			->viaTable('{{%comps_in_services}}', ['services_id' => 'id']);
	}
	
	public function getArms()
	{
		return static::hasMany(Arms::class, ['id' => 'arm_id'])
			->via('comps');
	}
    ...
}

class ServicesSearch extends Services
{
    ....
    public function search($params)
    {
        $query = Services::find()
        ->joinWith([
            'arms', //here is the bug comes!!!
        ]);

        $this->load($params); //filter nothing

        return new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);
}

$searchModel = new ServicesSearch();
$dataProvider = $searchModel->search([]);
var_dump($dataProvider->query->createCommand()->getRawSql());
var_dump($dataProvider->models[3]);
```

### What is the expected result?
same result on accessing arms field on services objects with or without eager loading of arms relation

### What do you get instead?
all works nice without usage of joinWith or with eagerload=false set
but if use joinWith (with eagerload enabled by default) or use "with" - some sevices loaded with empty arms field

dumped Query is same and correct in both cases
but loaded ActiveRecords objects differs (WTF???)

Without EagerLoading (columns Service,Comp,Arm): 
![image](https://user-images.githubusercontent.com/16677823/185743764-f2e0640f-77f7-49ce-8c51-d1ca6d5207aa.png)

With EagerLoading:
![image](https://user-images.githubusercontent.com/16677823/185743787-99df526a-abe6-4738-b4f9-11f7104e3a85.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 7.3
| Operating system | Windows

**Comment by WinterSilence** [comment]
hasMany() не статичный метод - getComps() и getArms() не регистрируют связи в данной модели. хз как у тебя этот код вообще работает без сообщений об ошибке.

**Comment by spo0okie** [comment]
Действительно налажал в этом месте, жаль что ошибку не выбрасывает. Но поменял static::has* -> $this->has* (по всему проекту) и это не изменило ситуацию описанную в issue (на первый взгляд вообще ничего не изменило).
Ровно тот же сценарий воспроизведения ошибки. Только код в части relation-ов корректный, с $this->hasMany как положено.

**Comment by WinterSilence** [comment]
@spo0okie cудя по твоей схеме отсутствует поле services.arm_id

**Comment by spo0okie** [comment]
@WinterSilence дык оно же ->via('comps') это релейшн через промежуточную модель.
т.е. сервис запущен на виртуалках, а виртуалки на железных серверах.
в самом сервисе нет указаний на железные сервера, только на виртуалки.
я хочу косвенно знать на каких железных серверах крутится сервис.

**Comment by WinterSilence** [comment]
@spo0okie 1. я не вижу как между собой связаны comps и arms
2. ->via('comps') скорее всего вяжет тебя с comps_in_services т.к. getComps() не связывает с comps напрямую

**Comment by spo0okie** [comment]
@WinterSilence , как не вяжет напрямую, все по инструкции. Я через hasMany указываю comps, а через viaTable указываю промежуточную таблицу
https://www.yiiframework.com/doc/api/2.0/yii-db-activequery#viaTable()-detail

С точки зрения SQL запросы формируются правильные и совершенно идентичные независимо от включения eagerLoad (я сравнивал через diff)

```
SELECT `services`.* 
  FROM `services` 
  LEFT JOIN `comps_in_services` ON `services`.`id` = `comps_in_services`.`services_id` 
  LEFT JOIN `comps`  ON `comps_in_services`.`comps_id` = `comps`.`id` 
  LEFT JOIN `arms` ON `comps`.`arm_id` = `arms`.`id` 
```

```
class Comps extends \yii\db\ActiveRecord
{
      ...
	public function getArm()
	{
		return $this->hasOne(Arms::class, ['id' => 'arm_id']);
	}
     ...
}

class Services extends \yii\db\ActiveRecord
{
    ...
	public function getComps()
	{
		return $this->hasMany(Comps::class, ['id' => 'comps_id'])
			->viaTable('{{%comps_in_services}}', ['services_id' => 'id']);
	}
	
	public function getArms()
	{
		return $this->hasMany(Arms::class, ['id' => 'arm_id'])
			->via('comps');
	}
    ...
}
```

В целом обращаю внимание что проблема не в самом построении релейшенов/связей. Все работает как надо и строит правильные формы с правильными данными. Проблема именно в eagerLoad.
Ткните хоть носом в какие методы какого класса поглядеть чтобы быстрее разобраться как работает eagerLoad. Может и на моей стороне косяк, но с виду я все сделал по мануалам, а результат не такой как там написано.

**Comment by WinterSilence** [comment]
насколько я понимаю у тебя должно быть несколько запросов т.к. тебе нужно выбрать по несколько записей из других таблиц для каждого сервиса. тебе нужно смотреть в сторону `withQuery()` и/или подзапросов возвращающих значение столбца либо использовать `with()`вместо `joinWith()`
нужно либо вытаскивать эти данн
`->with('arms');`

**Comment by spo0okie** [comment]
@WinterSilence, @samdark  В общем нашел я как мне кажется баг:
ActiveRelationTrait->populateRelation в случае relation через промежуточные объекты строит там карту (map) связей.
В случае последовательных via эти карты как бы связываются друг с дружкой чтобы получить итоговую карту связи объектов через множественные via. Делается это через ActiveRelationTrait->mapVia($map,$viaMap)
и код таков:
```
private function mapVia($map, $viaMap) {
        $resultMap = [];
        foreach ($map as $key => $linkKeys) {
            foreach (array_keys($linkKeys) as $linkKey) {
                $resultMap[$key] = $viaMap[$linkKey];
            }
        }
        return $resultMap;
    }
```
Обратите внимание что в во вложенном цикле мы просто переназначаем итоговый элемент $resultMap[$key] столько раз, сколько у нас в карте ссылок на объекты. Это неправильно, это даже по логике бессмысленно.
Должно быть так (и у меня это заработало):
```
private function mapVia($map, $viaMap) {
        $resultMap = [];
        foreach ($map as $key => $linkKeys) {
            $resultMap[$key]=[];
            foreach (array_keys($linkKeys) as $linkKey) {
                $resultMap[$key] += $viaMap[$linkKey];
            }
        }
        return $resultMap;
    }
```

**Comment by spo0okie** [comment]
Guys?

**Comment by samdark** [comment]
Yes? We've requested some tests for the pull request.

**Comment by spo0okie** [comment]
Sorry, i'm not a pull request master and no team work experience. I see only automated unit tests and they complete automaitcaly in 20min after pull request sumbit (or after update). Any tests more?

**Comment by bizley** [comment]
Yes, if you are adding a change new/updated test is required to check it.

**Comment by spo0okie** [comment]
What kind of test i need do more?
(sorry for inconvenience, my first time)

**Comment by bizley** [comment]
You need to prepare test that will check if your fix is indeed working. Test should be based at least on the case you stated that has a bug and could be build similar to [this one](https://github.com/yiisoft/yii2/blob/master/tests/framework/db/ActiveRecordTest.php#L205).

**Comment by spo0okie** [comment]
Ok it is clear now. I prepare a test.

**Comment by spo0okie** [comment]
@bizley look please: https://github.com/yiisoft/yii2/compare/master...spo0okie:yii2:19507-nested-relation-eager-load
Is that what I was supposed to do?
testing i made was
```
php vendor/bin/phpunit --group=db --filter 'ActiveRecordTest::testJoinWithEager' -v
```
before patch i got errors and after patch - no errors

**Comment by spo0okie** [comment]
@bizley do i need close previous pull request and create new with unit tests from link above?

**Comment by bizley** [comment]
No, just push to the same branch.

**Comment by spo0okie** [comment]
done
