### ISSUE TITLE
Rest API basic authentication always returns 401

### ISSUE THREAD

**Issue by cwongwpp** [yiisoft/yii2#19517]
### What steps will reproduce the problem?
Making api call with basic auth.
Call compositeAuth in Module:

```
public function behaviors() {
    return [
    ....
        [
            'class' => CompositeAuth::className(),
            'except' => [
                    .....
                ],
            'authMethods' => [
                [
                        'class' => HttpBasicAuth::className(),
                        'auth'  => function ($username, $password) {
                               // do something
                       },   
                ],
                [
                      'class' => MyCustomizedAuth::className(),
                ],
            ],
        ],
    ];
}
```

### What is the expected result?
It will authenticate with the right credential - supplied as basic auth in header.

### What do you get instead?
Returns 401 with message "Your request was made with invalid credentials."

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 8.1.9
| Operating system | Ubuntu 20.04

After some digging, it's caused by this fix - https://github.com/yiisoft/yii2/commit/f72310c398759841a0f8b52e1aba7990086c0d9c

Commenting out the if condition added in this fix, it's authenticated correctly.

**Comment by bizley** [comment]
This was done to respect `only` and `except` options. What is in your `except` configuration?

**Comment by cwongwpp** [comment]
```
'except' => [
    'controller1/index',
    'submodule1/*',
    'submodule2/*',
],
```

**Comment by bizley** [comment]
So are those rules preventing the filter to work, which is the reason, or those or not firing here and something is wrong with the CompositeAuth now?

**Comment by cwongwpp** [comment]
The issue I'm having is not to do with except and only config. The issue is trying to do basic auth but the authentication function wasn't called because of the if statement added by this fix: https://github.com/yiisoft/yii2/blame/f72310c398759841a0f8b52e1aba7990086c0d9c/framework/filters/auth/CompositeAuth.php#L73

The if statement doesn't meet ($this->owner is null), the authenticate function doesn't get called, hence the authentication always fails. If line 73 and 78 commented out, it gets authenticated.

Downgrade to Yii V2.0.45 and it works.

**Comment by cwongwpp** [comment]
> @cwongwpp `$this->owner` can't be null, but `action` property(`$this->owner->action`) not defined in `Module`

Sorry, I don't understand this. What action needs to be defined? This has been working and breaks after upgrading to V2.0.46.

**Comment by WinterSilence** [comment]
@cwongwpp #19418 is BC break because this changes support attaching only to controllers: `yii\base\Module` don't have `action` property.

**Comment by h0rseduck** [comment]
If using `CompositeAuth` via config file then `$this->owner` is an instance of `yii\web\Application` and it has no `action`

```
'as authenticator' => [
    'class' => CompositeAuth::class,
    'authMethods' => [
        ['class' => HttpBearerAuth::class],
    ]
],
```

**Comment by WinterSilence** [comment]
@h0rseduck no matter via config or not, `Application` extends `Module`

**Comment by h0rseduck** [comment]
@WinterSilence 
Of course.  I just described another case

**Comment by AleMercadal** [comment]
Sorry, i have the same problem. I was declaring the authenticator behavior into the behaviors function of the module. It is suposed to apply to every controller into that module but as @h0rseduck said `$this->owner` (in this case) is an instance of yii\web\Application and it don't have action property.

So instead of declaring the behavior into every controller, i came ahead with this temporary solution. Into my module `init` i do:
```
Yii::$app->on('beforeAction', fn() => Yii::$app->controller->attachBehavior('authenticator', [
    'class' => CompositeAuth::class,
    'authMethods' => [
        HttpBearerAuth::class,
    ],
]));
```

Now everything works properly. Please anyone can tell me if this is correct to do? Or should i declare the behavior into every controller instead?

**Comment by WinterSilence** [comment]
@AleMercadal also, you can do it via config(`$config['container']['definitions']`)
> Or should i declare the behavior into every controller instead?

Right way is create your base web controller extends by module controllers:
~~~php
abstract class BaseController extends Controller
{
  /**
   * @var string[]|true
   */
  public $publicActions = true;

  public function behaviors()
  {
      $behaviors = parent::behaviors();

      if ($this->publicActions !== true) {
          $behaviors['auth'] = [
              'class' => CompositeAuth::class,
              'except' => $this->publicActions,
              'authMethods' => [...]
          ];
      }

      return $behaviors;
  }
}
~~~

**Comment by AleMercadal** [comment]
Perfect! Thanks for your help

**Comment by papppeter** [comment]
thanks for the fix we had the same problem. i hope it will be released soonish

**Comment by neoacevedo** [comment]
I have Yii 2.0.47 and I'm getting the same response. I have set the behaviors function in my controller like:

```php
class SiteController extends \yii\rest\Controller
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        
        $behaviors['contentNegotiator']['formats']['application/json'] = Response::FORMAT_JSON;
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::class,
            'only' => ['logout'],
            'authMethods' => [
                // ['class' => HttpBasicAuth::class],
                // ['class' => HttpBearerAuth::class],
                ['class' => QueryParamAuth::class, 'tokenParam' => 'access-token'],
            ],
        ];

        return $behaviors;
    }
...
}
```
