### ISSUE TITLE
UniqueValidator has a bug in version 2.0.46

### ISSUE THREAD

**Issue by r-simlinger** [yiisoft/yii2#19536]
Since the release of the version 2.0.46 the error messages will not be added to all "targetAttribute"s anymore.
So this block from the documentation of the UniqueValidator is not true anymore:
```
 * // a1 and a2 need to be unique together, and they both will receive error message
 * [['a1', 'a2'], 'unique', 'targetAttribute' => ['a1', 'a2']]
```

### What steps will reproduce the problem?
I have an ActiveRecord class
with these rules:
```
            [['ref_report_id'], 'integer'],
            [['ref_report'], 'integer', 'max' => 127],
            [['ref_report', 'ref_report_id'], 'unique', 'targetAttribute' => ['ref_report', 'ref_report_id']],
```

### What is the expected result?
I'm getting these errors from the validation:
```
[
            'ref_report' => ["The combination \"{$ref_report}\"-\"{$ref_report_id}\" of Ref Report and Ref Report ID has already been taken."],
            'ref_report_id' => ["The combination \"{$ref_report}\"-\"{$ref_report_id}\" of Ref Report and Ref Report ID has already been taken."]
]
```

### What do you get instead?
I'm getting this now (only the first, because of this skipOnError==true):
```
[
            'ref_report_id' => ["The combination \"{$ref_report}\"-\"{$ref_report_id}\" of Ref Report and Ref Report ID has already been taken."]
]
```

### Additional info

Commit: https://github.com/yiisoft/yii2/pull/19409/files/1f4ac6647fb95ab97de73492d897e9782b3af372

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 7.4
| Operating system | Debian

**Comment by bizley** [comment]
Yes, documentation needs to be updated but this works as intended now.

**Comment by luke-** [comment]
Just had the same problem:

```
 * // a1 and a2 need to be unique together, and they both will receive error message
 * [['a1', 'a2'], 'unique', 'targetAttribute' => ['a1', 'a2']]
 ```

Minor note: If the behavior changes here, wouldn't it be better that `a1` (first attribute) gets the error instead of `a2`. Currently always the last attribute seems to get the error message.

**Comment by bizley** [comment]
First attribute without an error gets a new message when `skipOnError` is set to `true` (default).
