### ISSUE TITLE
dropDownList without "strict" has new behavior in 2.0.46

### ISSUE THREAD

**Issue by martynenko-dmitry** [yiisoft/yii2#19534]
Correction for issue https://github.com/yiisoft/yii2/issues/19324 causes new issue for dropDownList()

We have some dropDownList in search forms with both "empty string value" and "zero value", like this
```
<form action="..." method="get">
<select>
<option value="">- select -</option>
<option value="0">House handed over</option>
<option value="2022">2022 Year</option>
...
</select>
</form>
```

**Strict** parameter is not set for dropDownList().

First render of form we get no one option with "selected" attribute.

In Yii 2.0.46 after form submit and page reload **without choosing any option** in this `<select>` we get "zero value" option selected `<option value="0" selected>`

Before Yii 2.0.46 we get no one option selected, without strict => true
In Yii 2.0.46 we have to set strict => true to reproduce previous behavior. 

Is this a bug or a feature?
Now we need to fix a lot of fields in many forms to fix the problem.

| Yii version | 2.0.46
| PHP version | 7.4
| Operating system | Ubuntu

**Comment by canreo** [comment]
I'm having the same issue.  This completely messed up my Select2 gridview filters.

**Comment by samdark** [comment]
@bizley would you please take a look at this isssue?

**Comment by bizley** [comment]
This is the same as in https://github.com/yiisoft/yii2/issues/19508 isn't it?

**Comment by samdark** [comment]
Maybe. @martynenko-dmitry please try `master` branch.

**Comment by martynenko-dmitry** [comment]
@samdark Nothing changed. 
Problem locates in renderSelectOptions() of helpers/BaseHtml.php

Previous condition was 
`$attrs['selected'] = $selection !== null && (!ArrayHelper::isTraversable($selection) && !strcmp($key, $selection)) ...`

Now condition is
`$attrs['selected'] = $selection !== null && (!ArrayHelper::isTraversable($selection) && ($strict ? !strcmp($key, $selection) : $selection == $key) ...`

Before submit $selection == null, after submit $selection == "".
$key for `<option value="0">` has numeric zero value.
Comparision $selection == $key, that is 0 == "" get result "true" for PHP 7, and "false" for PHP 8.

**Comment by martynenko-dmitry** [comment]
> This is the same as in #19508 isn't it?

@bizley I think it the same issue

**Comment by WinterSilence** [comment]
behavior changed in #19324

**Comment by papppeter** [comment]
we have the same issue.

if i am right it will be fixed in https://github.com/yiisoft/yii2/pull/19524 @WinterSilence

**Comment by WinterSilence** [comment]
@papppeter nope, it's cant be fixed, only rollback. #19524 fixed issue #19522

**Comment by WinterSilence** [comment]
@papppeter @canreo @martynenko-dmitry vote in #19580

**Comment by papppeter** [comment]
could you maybe release this as a fix? 2.0.46.1? we could not switch to 2.0.46 because of this and https://github.com/yiisoft/yii2/issues/19581

**Comment by samdark** [comment]
Would it be fixed if we'll change `strict` default value?

**Comment by martynenko-dmitry** [comment]
> Would it be fixed if we'll change `strict` default value?

Yes, it will help for PHP 7.x in our case - for numeric and string values in selects.

But we don't use boolean values for selectors (https://github.com/yiisoft/yii2/issues/19324). I can't say anything about how "strict" will affect in their case.
