### ISSUE TITLE
My Website Problem

### ISSUE THREAD

**Issue by MofazzalNCAA** [yiisoft/yii2#19542]
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 7043

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 2172

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 7043

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 2172

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 7043

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 2172

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 7043

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/todaylive/24fighting.com/wp-includes/functions.php on line 2172

Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/todaylive/24fighting.com/wp-includes/formatting.php on line 2782

Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/todaylive/24fighting.com/wp-includes/formatting.php on line 2782

Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/todaylive/24fighting.com/wp-includes/formatting.php on line 2782

**Comment by virtual-designer** [comment]
Looks like this error is coming from wordpress (wp-includes), are you sure you're using Yii2 Framework and getting the error?

**Comment by samdark** [comment]
That's definitely not Yii2 issue since you're using WordPress.
