### ISSUE TITLE
Session id is regenerated at alomst every request IN "dev" ENVIRONMENT

### ISSUE THREAD

**Issue by sohep** [yiisoft/yii2#19545]
**NOTE: This problem happen when using rest Api.
**NOTE: This problem does not happen when running the app in "prod" ENVIRONMENT.

### What steps will reproduce the problem?
Just set the app to run in dev environment, and check the session id which sent back to the browser.

### What is the expected result?
Getting the same session by every request even in den environment

### What do you get instead?
I get diffrent session by every request.

### Additional info
Possible check point:
https://github.com/yiisoft/yii2/commit/12763a146ebc550963b5d368633539701e7884ec
https://github.com/yiisoft/yii2/commit/12763a146ebc550963b5d368633539701e7884ec#r62888201
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 7.4.30
| Operating system | Ubuntu 20.04

**Comment by samdark** [comment]
@bizley do you remember if @SamMousa created an issue for it?

**Comment by sohep** [comment]
**Following up:

I think this issue has nothing to do with this repo, but with the "Debug Extension for Yii 2" repo.
While debugging i found out that the UserPanel model cause this issue after it get loaded.

https://github.com/yiisoft/yii2-debug/blob/master/src/Module.php#L480

**Comment by bizley** [comment]
@sohep  Could you elaborate?
