### ISSUE TITLE
Use of className() in framework/rest/Controller.php

### ISSUE THREAD

**Issue by monta990** [yiisoft/yii2#19573]
https://github.com/yiisoft/yii2/blob/60dec4008bff11e8bcdde702d033f4fbf3663965/framework/rest/Controller.php#L52

https://github.com/yiisoft/yii2/blob/60dec4008bff11e8bcdde702d033f4fbf3663965/framework/rest/Controller.php#L59

https://github.com/yiisoft/yii2/blob/60dec4008bff11e8bcdde702d033f4fbf3663965/framework/rest/Controller.php#L63

https://github.com/yiisoft/yii2/blob/60dec4008bff11e8bcdde702d033f4fbf3663965/framework/rest/Controller.php#L66

**Comment by bizley** [comment]
What kind of spam is this? We are using `className()` because Yii 2 can be run on PHP 5.4 where is no `::class`.

**Comment by samdark** [comment]
@bizley it's not a spam :) But yes, it won't be changed.
