### ISSUE TITLE
Error reporting in to the BaseArrayHelper::getValue()

### ISSUE THREAD

**Issue by lav45** [yiisoft/yii2#19589]
### What steps will reproduce the problem?

error_reporting | strrpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
-- | --
line | 209
code | 8192
file | /var/www/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 8.1
| Operating system | Linux

**Comment by rob006** [comment]
In what scenario you're getting such error? `getValue()` does not accept `null` as `$key`.

**Comment by lav45** [comment]
and who forbids doing this? 
It may be worth throwing out the default value right away, so as not to provoke a similar problem in the `keyExists()` method

```php
    public static function getValue($array, $key, $default = null)
    {
        if (empty($key)) {
            return $default;
        }
    }
```

**Comment by rob006** [comment]
> and who forbids doing this?

It does not matter. Yii cannot use types in method signature due to supported PHP versions range, but it does not mean we should add guards for every possible misuse of any method in framework. If phpdoc does not allow to pass `null` as `$key`, then it is on you if you decide to ignore it and pass `null` anyway.

**Comment by samdark** [comment]
In this case I think a safeguard would not hurt.

**Comment by rob006** [comment]
> In this case I think a safeguard would not hurt.

It may hide potential errors. That is the point why PHP started to emit deprecation for such cases. By adding bling guards Yii negates progress made by PHP. And if we're fine with that and decide that `null` is valid key, it should be reflected by phpdoc and probably fixed in `keyExists()` too.
