### ISSUE TITLE
DbQueryDependency loop

### ISSUE THREAD

**Issue by stovesy** [yiisoft/yii2#19607]
Trying to cache a result of a sum of an order total, with a dependency on the number of items in the order list.  
I'm not sure if this is an error in my usage or configuration.

```
		$dependency = new DbQueryDependency([
			'query' => (new Query())
				->select('count(*)')
				->from('purchase_order_item')
				->where(['purchase_order' => $this->order_number]) // A ->nocache() here works as expected.
		]);
		return yii::$app->db->cache(function () {
			$orderTotal = (new Query())
				->from('purchase_order_item')
				->where(['purchase_order' => $this->order_number])
				->sum('price_each * qty');
			return $orderTotal;
		}, 3600, $dependency);
```

### What is the expected result?
db->cache function return the the order total

### What do you get instead?
Infinite loop unless a ->nocache() is added the the dependency query.
The executeQuery routine causes the loop unless a nocache() is added. Why would a dependency query be cached anyway ?

### Additional info

```
    /**
     * Executes the query according to [[method]] specification.
     * @param QueryInterface $query query to be executed.
     * @param mixed $db connection.
     * @return mixed query result.
     */
    private function executeQuery($query, $db)
    {
        if ($this->method === null) {
            $query->nocache() // This change works too.
            return $query->one($db);
        }
        if (is_string($this->method)) {
            return call_user_func([$query, $this->method], $db);
        }

        return call_user_func($this->method, $query, $db);
    }

```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47-dev
| PHP version      | 8.1.10
| Operating system |ubuntu

**Comment by alex-code** [comment]
Which DBMS are you using?
Can you show your cache settings?

**Comment by stovesy** [comment]
db is pgsql
cache 'class' => yii\redis\Cache::class,
'redis' => [
	'class' => yii\redis\Connection::class,
	'hostname' => 'localhost',
	'port' => 6379,
	'database' => 0,
],

**Comment by alex-code** [comment]
Could you show your db settings?
Just to see the cache options for that too.

**Comment by stovesy** [comment]
return [
	'class' => yii\db\Connection::class,
	'dsn' => 'pgsql:host=',
	'username' => '',
	'password' => '',
	'enableLogging' => $dbData,
	'enableProfiling' => $dbData,
//	'enableSchemaCache' => true,
	'enableQueryCache'  => true,
//	'schemaCacheDuration' => 3600,
//	'schemaCache' => 'cache',
];

**Comment by stovesy** [comment]
I can see what it is. I've not set the $db property so the test.. 
`        if (!empty($db->enableQueryCache)) {
`
fails.
