### ISSUE TITLE
Module Migration failing

### ISSUE THREAD

**Issue by TheFox** [yiisoft/yii2#19611]
### What steps will reproduce the problem?

I created a simple Module under `modules\dsr_setup` namespace. I also created a Migration under that modules namespace for migrations, using `yii migrate/create modules\\dsr_setup\\migrations\\Mailer`.

I mapped the namespace in the Controller Map.

```
return [
    ...
    'controllerMap' => [
        'migrate' => [
            ...
            'migrationNamespaces' => [
                'modules\dsr_setup\migrations',
            ],
            ...
        ],
    ],
    ...
];
```

When I want to enable the module using `yii module/enable dsr-setup` the Migrations fail.

### What is the expected result?

I expect that the migrations are working while enabling the module.

### What do you get instead?

Error Message

```--- Modul aktivieren: dsr-setup ---Yii Migration Tool (based on Yii v2.0.46-dev)

Total 1 new migration to be applied:
	M221006094347Mailer

*** applying M221006094347Mailer
Exception 'yii\di\NotInstantiableException' with message 'Failed to instantiate component or class "M221006094347Mailer".'

in /app/protected/vendor/yiisoft/yii2/di/Container.php:509

Caused by: Exception 'ReflectionException' with message 'Class "M221006094347Mailer" does not exist'

in /app/protected/vendor/yiisoft/yii2/di/Container.php:507

Stack trace: ...
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46-dev
| PHP version      |  8.1.10
| Operating system | Debian 11

**Comment by bizley** [comment]
What is the namespace of the M221006094347Mailer class?

**Comment by TheFox** [comment]
@bizley `namespace modules\dsr_setup\migrations;`

**Comment by bizley** [comment]
Does it work when you add to the migrate config `'migrationPath' => null`?

**Comment by TheFox** [comment]
That does not make any difference.

**Comment by bizley** [comment]
I'm not sure what does `module/enable` do? Does the migration work if you run it using `yii migrate`?

**Comment by WinterSilence** [comment]
~~~php
'controllerMap' => [
    // Application migrations:
    'migrate' => [
        'class' => yii\console\controllers\MigrateController::class,
        'migrationPath' => null,
        'migrationNamespaces' => ['modules\dsr_setup\migrations'],
    ],
    // Yii migrations:
    'yii-migrate' => [
        'class' => yii\console\controllers\MigrateController::class,
        'migrationPath' => [
            '@yii/web/migrations',
            // Note: update component's configuration before uncomment next migrations
            // '@yii/rbac/migrations',
            // '@yii/caching/migrations',
            // '@yii/i18n/migrations',
            // '@yii/log/migrations',
        ]
    ],
]
~~~

**Comment by bizley** [comment]
If so I'm afraid you must take it to the HumHub for help. I'm closing this, please let me know if I can help with anything regarding Yii itself.

**Comment by TheFox** [comment]
@bizley Ok I see. Thank you for your help.

@WinterSilence There is an alias for that. When I use a namespace in a module the migration Class Name begins with an capital letter M.

**Comment by WinterSilence** [comment]
@TheFox as I'm already told, you can use syntax like as yii migrate/create modules\\dsr_setup\\migrations\\createMailerTable`. Look PHPDoc to `actionCreate`
https://github.com/yiisoft/yii2/blob/0b4741ea6aa2fa58866c4eb65ef17c0b8d03323a/framework/console/controllers/BaseMigrateController.php#L619
