### ISSUE TITLE
```yii\web\JsonParser::parse()``` doesn't work with JSON comments

### ISSUE THREAD

**Issue by khasandesign** [yiisoft/yii2#19627]
I have been documenting my RestAPI in Postman in following way:
```
{
  "key": "value" // Comment
}
```
JSON seems valid, but when I send request I get Bad Request 400 (Invalid JSON data in request body: Syntax error). If I remove comments it works. Other ways of commenting in JSON also lead to the same problem.

### What steps will reproduce the problem?
Create test POST request with some JSON, add JSON comment.

### What is the expected result?
Ignoring comment blocks and responding with right result.

### What do you get instead?
Bad Request 400 (Invalid JSON data in request body: Syntax error)

**Comment by bizley** [comment]
I'm not sure how this could be Yii issue. Please make sure that Postman sends proper JSON.

**Comment by khasandesign** [comment]
> I'm not sure how this could be Yii issue. Please make sure that Postman sends proper JSON.

Yeah, of course first I thought I did smth wrong, but here is the example
![With comment](https://user-images.githubusercontent.com/88556798/196112295-22ddd536-b010-40a6-b0c7-3842b19456d2.png)
![Without comment](https://user-images.githubusercontent.com/88556798/196112309-af1a2d1d-efe0-4ac1-b4ba-34dcca1e6f13.png)

And it happens in all requests.

**Comment by DeryabinSergey** [comment]
JSON not support any type of comments https://www.rfc-editor.org/rfc/rfc8259
This is not valid JSON:
```JSON
{
  "key": "value" // Comment
}
```
