### ISSUE TITLE
Incorrect check of date field by DateValidator in PHP 8.2RC3

### ISSUE THREAD

**Issue by knoppixmeister** [yiisoft/yii2#19635]
### What steps will reproduce the problem?
Incorrect check of date field by DateValidator

### What is the expected result?
with following rule for validator date filed must be validate correctly

['date', 'date', 'format' => 'php:d-m-Y', 'message' => 'Invalid date format'],

### What do you get instead?
Add check whether $errors variable is of type bool or array in parseDateValuePHP function (approx 445 line)

I fixed it for myself as code below:

if (
	    !empty($errors)
	    && (
		$date === false 
		|| $errors['error_count']
		|| $errors['warning_count']
		|| ($this->strictDateFormat && $date->format($format) !== $value)
	    )
)
{
     return false;
}

### Additional info

| Q                 | A
| ---------------- | ---
| Yii version            | 2.0.46
| PHP version         | PHP 8.2.0RC3 (fpm) (built: Sep 29 2022 22:31:18) (NTS) (ppa:ondrej / deb.sury build)
| Operating system | Ubuntu 22.04.01

**Comment by bizley** [comment]
Could you prepare PR with the fix?
