### ISSUE TITLE
ActiveRecord delete() ruturns null when using MySQL even on success

### ISSUE THREAD

**Issue by developedsoftware** [yiisoft/yii2#19661]
### What steps will reproduce the problem?

Call delete() method on a model 

### What is the expected result?

int of 1 to be returned as per the documentation found here https://www.yiiframework.com/doc/api/2.0/yii-db-activerecord#delete()-detail

### What do you get instead?

null

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 8.1.12
| Operating system | Red Hat Enterprise Linux release 8.6 (Ootpa) 
| MySQL Version      | 8.0.19 - MySQL Community Server - GPL

**Comment by developedsoftware** [comment]
This makes it very difficult to make decisions based on whether a delete has been successful. 

We have a project that does some stuff post delete (like tidy up some indexes etc) and its not running because null is returned. We can obviously make our checks strict against false `if($model->delete() !== false)` but we was not expecting null to be returned in any situation?

**Comment by My6UoT9** [comment]
Are u sure the issue is in Yii?  The delete statement ultimately calls execute in ActiveRecord, which returns a row count (int).

**Comment by developedsoftware** [comment]
My apologies, we had extended deleteAll from ActiveRecord and not returned its parent value!! DOH!

Only spotted when we realised delete() does indeed call deleteAll()

Sorry for wasting your time!
