### ISSUE TITLE
[yii\grid\DataColumn] does not allow to remove filter on when `format` is `boolean`

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#19664]
### What steps will reproduce the problem?
1. Create gridview with one column being `fieldname:boolean`
2. Select `Yes` as filter
3. Select ` ` (Placeholder) as filter

### What is the expected result?
1. It should not filter
2. It should show ` ` (Placeholder) as filter value

### What do you get instead?
1. It does not filter
2. It shows `No` as filter value

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 7.4.30
| Operating system | Docker

**Comment by luke-** [comment]
Should be fixed here: https://github.com/yiisoft/yii2/pull/19509

Related: https://github.com/yiisoft/yii2/issues/19534

**Comment by mikk150** [comment]
yes, it is same as https://github.com/yiisoft/yii2/issues/19534
