### ISSUE TITLE
PHP 8 help console controller issue

### ISSUE THREAD

**Issue by jarrus90** [yiisoft/yii2#19675]
### What steps will reproduce the problem?
Simply run php yii.php
### What is the expected result?
Get list of available commands
### What do you get instead?

#0 [internal function]: yii\\base\\ErrorHandler->handleError() 
#1 \\website\\vendor\\yiisoft\\yii2\\base\\Module.php(261): str_replace() 
#2 \\website\\vendor\\yiisoft\\yii2\\console\\controllers\\HelpController.php(245): yii\\base\\Module->getControllerPath() 
#3 \\website\\vendor\\yiisoft\\yii2\\console\\controllers\\HelpController.php(240): yii\\console\\controllers\\HelpController->getModuleCommands() 
#4 \\website\\vendor\\yiisoft\\yii2\\console\\controllers\\HelpController.php(172): yii\\console\\controllers\\HelpController->getModuleCommands() 
#5 \\website\\vendor\\yiisoft\\yii2\\console\\controllers\\HelpController.php(192): yii\\console\\controllers\\HelpController->getCommands() 
#6 \\website\\vendor\\yiisoft\\yii2\\console\\controllers\\HelpController.php(292): yii\\console\\controllers\\HelpController->getCommandDescriptions() 
#7 \\website\\vendor\\yiisoft\\yii2\\console\\controllers\\HelpController.php(67): yii\\console\\controllers\\HelpController->getDefaultHelp() 
#8 [internal function]: yii\\console\\controllers\\HelpController->actionIndex() 
#9 \\website\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array() 
#10 \\website\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams() 
#11 \\website\\vendor\\yiisoft\\yii2\\console\\Controller.php(180): yii\\base\\Controller->runAction() 
#12 \\website\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\console\\Controller->runAction() 
#13 \\website\\vendor\\yiisoft\\yii2\\console\\Application.php(180): yii\\base\\Module->runAction() 
#14 \\website\\vendor\\yiisoft\\yii2\\console\\Application.php(147): yii\\console\\Application->runAction() 
#15 \\website\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\console\\Application->handleRequest() 
#16 \\website\\yii.php(28): yii\\base\\Application->run() 
#17 {main}
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 8.1
| Operating system | Debian, Windows

**Comment by samdark** [comment]
What is the error itself?

**Comment by jarrus90** [comment]
str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated. I've created merge request already

**Comment by jarrus90** [comment]
There were 2 errors, first with str_replace, next in help controller when is_dir got null in response, they both are fixed with https://github.com/yiisoft/yii2/pull/19676

**Comment by bizley** [comment]
How is your controllerNamespace null at that point? Isn't it the case when you have custom module and don't call parent init?

**Comment by jarrus90** [comment]
Application is splitted in modules, some of them dont have any console commands, so no console commands namespace passed, then help controller runs over all modules and trying to get controllers. And yes, i`ve noticed that there is missing parent::init() call, otherwise this problem occures only in php8*, lower versions dont write about problem.

**Comment by jarrus90** [comment]
Yes, i have fixed in my side, so dont know what to do with pull request
