### ISSUE TITLE
FileHelper::getExtensionByMimeType return jfif for image/jpeg

### ISSUE THREAD

**Issue by mihob** [yiisoft/yii2#19683]
It looks like FileHelper::getExtensionByMimeType returns jfif as extension for files of mime type image/jpeg. Is probably not really a bug, however jpg or jpeg would be the more common extension

### What steps will reproduce the problem?

Call FileHelper::getExtensionByMimeType with a file of mime type image/jpeg

### What is the expected result?

The function returns jpeg

### What do you get instead?

The function returns jfif

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 8.1.11
| Operating system | Linux 5.15.49-linuxkit

**Comment by samdark** [comment]
That's because `jpg` goes later than `jfif` in `mimeTypes.php` and both match `image/jpeg` mime type. I agree `jpg` is what's expected.

**Comment by samdark** [comment]
Do you have time for a fix? Note that `mimeTypes.php` is generated by `build/controllers/MimeTypeController`.

**Comment by rhertogh** [comment]
@mihob @samdark There doesn't seem to be a function `FileHelper::getExtensionByMimeType` only the function `FileHelper::getExtensionsByMimeType` (note the plural "Extensions") exists. Which is logical since one mime type can have multiple extensions.
@mihob Are you using a custom function?
