### ISSUE TITLE
Error summary always visible with CSP header

### ISSUE THREAD

**Issue by skepticspriggan** [yiisoft/yii2#19691]
### What steps will reproduce the problem?

1. Add CSP headers

`Yii::$app->response->headers->add(
    'Content-Security-Policy',    
    "default-src 'self'"
);`

2. Create form with error summary

`<?= $form->errorSummary($model); ?>`

### What is the expected result?

The error summary remains hidden until the form has errors.

### What do you get instead?

An empty error summary is always shown.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 7.4
| Operating system | Debian

The browser console shows the following error message:

`Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='), or a nonce ('nonce-...') is required to enable inline execution.`

The [errorSummary()](https://github.com/yiisoft/yii2/blob/64adbd73c626b66e13208a11a0456157954915b4/framework/helpers/BaseHtml.php#L1279) function in the class BaseHtml uses inline style to hide the summary. This is not allowed by CSP.

**Comment by skepticspriggan** [comment]
The problem can be solved by using a `hidden` CSS class which contains the `display: none` instead of specifying this inline. Are there any issues with this? 

I would be willing to create a pull-request to fix this issue.

**Comment by samdark** [comment]
Where should be a CSS style for that class?
