### ISSUE TITLE
Eager load with() has one bug when relation dynamic className

### ISSUE THREAD

**Issue by awebc** [yiisoft/yii2#19709]
Eager load with() has one bug when relation dynamic className

table_like
id,class_name,object_id
1,\App\Post,1
2,\App\Post,2
3,\App\Comment,3
4,\App\Comment,4

Model:
Like extends ActiveRecord{
	
	public function getLikeEntity(){
		return $this->hasOne($this->class_name,['id'=>'obj_id']);
	}
}

Now query:

$items = Like::find()->with('likeEnity')->all();

queryBuilder will generate sql like:

select * from `post` where id in(1,2,3,4)

comment not query ! 

$items[0]->likeEntity is post model
$items[1]->likeEntity is post model
$items[2]->likeEntity is null
$items[3]->likeEntity is null

Right sql may be like this:
select * from `post` where id in(1,2)
select * from `comment` where id in(3,4)

foreach($items as $item){
	//$items[0]->likeEntity is post model
	//$items[1]->likeEntity is post model
	//$items[2]->likeEntity is comment model
	//$items[3]->likeEntity is comment model
}

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47?
| PHP version     8.1 | 
| Operating system | ubuntu 22.04

**Comment by MarkoNV** [comment]
This was never supported nor intended way of using it. Your first issue is database design - while this approach can be acceptable for some issues, especially if modularity is required, in this case separate nullable columns would be better approach, with two relations. For convenience you can have getter getLikeEntity() which would return one or other. 

It would work is posts and comments are in same table, with type column and method:

`
public static function instantiate($row)
{
    return ($row['type'] == 'comment') ? new Comment() : new Post();
}
`

**Comment by bizley** [comment]
Exactly like @MarkoNV said this is not an intended way it should work hence you cannot claim it's a bug. This is out of scope of the framework and will not be supported and you have to figure it out on your own.
