### ISSUE TITLE
Date validator breaks with php 8.2

### ISSUE THREAD

**Issue by solobot2** [yiisoft/yii2#19718]
### What steps will reproduce the problem?
Update php version to 8.2. It seems like there are unmentioned return type change in php docs. Method DateTime::getLastErrors() now returns false if there was no errors instead of array with empty error values. This breaks DateValidator::parseDateValuePHP()
method (line 445) 

### What is the expected result?
Expected validator to validate params

### What do you get instead?
php error ''array offset used on boolean value'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      |  8.2
| Operating system | MacOS Ventura

**Comment by Krakozaber** [comment]
resolved in https://github.com/yiisoft/yii2/issues/19635
