### ISSUE TITLE
PHP 8.2 deprecate dynamic properties

### ISSUE THREAD

**Issue by DeryabinSergey** [yiisoft/yii2#19711]
Hi all.

What do you think about this? https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties
`BaseObject` `Model` and etc will always generate deprectated Exception 

Just use `#[\AllowDynamicProperties]` attribute or something else?

**Comment by samdark** [comment]
`#[\AllowDynamicProperties]` looks like the only option.

**Comment by rob006** [comment]
> `BaseObject` `Model` and etc will always generate deprectated Exception

Why? AFAIK Yii 2 does not use dynamic properties.

**Comment by bizley** [comment]
Yes, everything will be fine. Furthermore all classes extending BaseObject will throw exception on unknown property creation.
