### ISSUE TITLE
Negative exclusion option does not work in `BaseFileHelper::findFiles`?

### ISSUE THREAD

**Issue by ezoterik** [yiisoft/yii2#19722]
I want to find all project files except excluding `/vendor` directory, but not `/vendor/yiisoft/yii2-bootstrap` subdirectory.

### What steps will reproduce the problem?

Following [the documentation](https://www.yiiframework.com/doc/api/2.0/yii-helpers-basefilehelper#findFiles()-detail), I try to specify the following parameters:

```php
BaseFileHelper::findFiles(ROOT_APP_PATH, ['except' => [
    '/vendor',
    '!/vendor/yiisoft/yii2-bootstrap'
]])
```

### What is the expected result?

Get files from `/vendor/yiisoft/yii2-bootstrap` directory but not get all other files in `/vendor` directory

### What do you get instead?

I do not get the contents of the `/vendor/yiisoft/yii2-bootstrap` directory

### Additional info

I'm not sure if this is a bug. Maybe I misunderstood the documentation. Just in case, I will create a pull request with a test that reproduces the problem

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 7.4, 8.2
| Operating system | Ubuntu 20.04 LTS

**Comment by samdark** [comment]
Yes. The docs state that it should work:

> An optional prefix `!` which negates the pattern; any matching file excluded by a previous pattern will become included again. If a negated pattern matches, this will override lower precedence patterns sources.

**Comment by samdark** [comment]
Do you have a solution fixing the problem?

**Comment by ezoterik** [comment]
I can try to fix this by completing my pull request.

The problem is in this piece of code:

```php
if (static::filterPath($path, $options)) {
    if (is_file($path)) {
        $list[] = $path;
    } elseif (is_dir($path) && (!isset($options['recursive']) || $options['recursive'])) {
        $list = array_merge($list, static::findFiles($path, $options));
    }
}
```

As a result, the check of the excluded subdirectory does not reach due to the fact that the parent directory is discarded at the stage of checking the `/vendor` pattern, then this directory is not analyzed recursively. This means that we must recursively check all directories even if the root of the directory falls under some kind of exception.

This can clearly degrade performance in the general case when searching through large directory nestings. I could think of only one crude way to avoid unexpected load for most users. At the beginning, check if there is at least one pattern in the options that starts with the "!" sign. If there is, then turn on the full scan mode, otherwise leave the code to work as it worked before. My understanding is that most users don't use negative exceptions (because the current issue has been around for a very long time) and I think my approach should not create any nasty surprises for the vast majority of users.

My user case, by the way, is the internationalization setting. I wanted the entire `/vendor` directory to be excluded from the scan, but some libraries still need to be scanned. And in this case performance is not critical.

If my idea sounds acceptable, then I will add the code in my pull request.

**Comment by samdark** [comment]
Sounds alright. The check could be improved by actually lookg for this exact case: exclusion pattern within regular pattern.

**Comment by ezoterik** [comment]
I'm very sorry, but this is not a bug.

Having studied the sources in more detail, I saw that the functionality with filtering by pattern was copied from the git sources. The `lastExcludeMatchingFromList` function has a comment:
> Based on last_exclude_matching_from_list() from dir.c of git 1.8.5.3 sources.

After that, I realized that the `except` parameter meant the `gitignore` file format. At the end of [the gitignore documentation](https://git-scm.com/docs/gitignore/en) there is an example of how to make exceptions for nested directories. Based on this documentation, here is a working example:

```php
BaseFileHelper::findFiles(ROOT_APP_PATH, ['except' => [
    '/vendor/*',
    '!/vendor/yiisoft',
    '/vendor/yiisoft/*',
    '!/vendor/yiisoft/yii2-bootstrap'
]])
```

It might be worth adding a link to the gitignor documentation to the description of the parameter, or at least indicating that this format is implied, but in fact everything works as it should.

**Comment by samdark** [comment]
Oh! Thanks for further digging. Would you please do a pull request with the link added?

**Comment by ezoterik** [comment]
@samdark I fixed the test with a working example (as documentation, it might be helpful) and added a link to the format description in phpdoc. Not sure if I did the right thing adding to my last PR, if I understand correctly you can do a squash if needed

**Comment by samdark** [comment]
Yes, multiple commits isn't an issue. Thank you.
