### ISSUE TITLE
Lack of "zh" message folder, when I try to set language to "zh-HK". 

### ISSUE THREAD

**Issue by chief725** [yiisoft/yii2#19720]
### What steps will reproduce the problem?
Set yii language to "zh-HK", [error][yii\i18n\PhpMessageSource::loadFallbackMessages] The message file for category 'yii' does not exist
### What is the expected result?
The message folder only have "zh-TW" and "zh-CN", "zh-HK" not found and  try to locate the "zh" folder, but not exist. 

### What do you get instead?
The message folder only have "zh-TW" and "zh-CN", "zh-HK" not found and  try to locate the "zh" folder, but not exist. 

### Additional info
I try to make a simple link from "zh-CN" to "zh" , problem fixed. So please add the "zh" message folder.
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
We can probably move  "zh-CN" to "zh".

**Comment by uaoleg** [comment]
@samdark done https://github.com/yiisoft/yii2/pull/19832
