### ISSUE TITLE
Filter "trim" Passing null to parameter  string is deprecated 

### ISSUE THREAD

**Issue by pamparam83** [yiisoft/yii2#19732]
### What steps will reproduce the problem?
 rule
```php
[['name','email'], 'filter', 'filter' => 'trim']
```
### What is the expected result?
the filter  needs to work.

### What do you get instead?
`Passing null to parameter #1 ($string) of type string is deprecated in .../vendor/yiisoft/yii2/validators/FilterValidator.php:81 `

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 8.1
| Operating system | Ububntu

**Comment by bizley** [comment]
This filter works, it is rather you that needs to make sure that value passed to the filter is not null, for example by setting it as required.

**Comment by pamparam83** [comment]
I have optional fields
are you suggesting default values?
and if using the rule

`[['name','email'],  'trim']`
no error

**Comment by DeryabinSergey** [comment]
For optional fields you can use

```php
[['name','email'],  'trim', 'skipOnEmpty' => true]
```
or
```php
[['name','email'],  'trim', 'skipOnEmpty' => true, 'skipOnError' => true]
```
