### ISSUE TITLE
Ability to turn the sorting off for a clicked column in GridView with multisort ignores defaultOrder

### ISSUE THREAD

**Issue by spapad** [yiisoft/yii2#19731]
If a field is set at the ```defaultOrder``` of a ```Sort``` specification with a ```SORT_DESC``` ordering, and ```enableMultiSort``` is set to ```true```, the sort link is always generated the same and sorting in ```SORT_ASC``` order is not possible. 

### What steps will reproduce the problem?
Enable multisort and set defaultOrder on a property with SORT_DESC, i.e.
```php
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'enableMultiSort' => true,
                'defaultOrder' => [
                    'date' => SORT_DESC
                ]
            ],
        ]);
```

### What is the expected result?
After https://github.com/yiisoft/yii2/pull/18826 
changing the sorting of the designated field would be expected in the order:
DESC -> off -> ASC -> DESC ... 

### What do you get instead?
The sort link generated by $sort->link() is repeatedly setting sorting to OFF, due to the fact that the default ordering sets the order to DESC.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.2.0
| Operating system | Ubuntu 22.04.1 LTS (Jammy Jellyfish) 64-bit

**Comment by samdark** [comment]
@ditibal, @bizley would you please take a look?

**Comment by bizley** [comment]
I've added more tests to check the `link()` in https://github.com/yiisoft/yii2/pull/19733
I see no problems here. It's true that for multisort expected order is DESC -> off -> ASC -> DESC but in case there are no current sort params we use defaultOrder so for that param this will start with `off` and not `DESC`. Maybe I'm missing something from your description, please let me know.

**Comment by spapad** [comment]
Thank you for taking the time to look into it! I must say that this is not actually a bug, but does allow for this weird scenario. Please let me try to describe the observed result. 

Following the example above, where sort is configured like this
```
'sort' => [
    'enableMultiSort' => true,
    'defaultOrder' => [
        'date' => SORT_DESC
    ]
],
```
a GridView using the dataprovider will sort by default on the ```date``` field in descending order.
*As expected*, the corresponding sort link for that date column will have an empty ```sort``` query param. 
For example ```.../index.php?r=ga%2Findex&sort=```

Clicking this link, which *as expected* does not provide a sort query param, will result in displaying the page again with the defaultOrder (that is the GridView will sort again by default on the ```date``` field in descending order). 
Thus we will not be able to sort in ascending order.

This only applies when sorting with the denoted field alone.

**Comment by bizley** [comment]
Oh, I get it. Currently we cannot distinguish "no sort" from "desc sort switched off" resulting in default sorting applied in both cases automatically. Let me think about possible solution...

**Comment by bizley** [comment]
Ok, this should fix the problem without BC breaks.
