### ISSUE TITLE
Memory leaks due to `str_pad()` in `yii\base\ErrorHandler::register()`

### ISSUE THREAD

**Issue by maximal** [yiisoft/yii2#19738]
Hi there!

I’m using Yii2 with [RoadRunner](https://roadrunner.dev/) through `charlesportwoodii/yii2-psr7-bridge` package (https://github.com/charlesportwoodii/yii2-psr7-bridge).

I had set `memprof` extension (https://github.com/arnaud-lb/php-memory-profiler/) to dump memory profile every 1000 processed requests and got some interesting results:

![image](https://user-images.githubusercontent.com/980679/211791322-0ab9d0f4-6544-4a66-a699-1ef7bfc31a7f.png)

Almost all memory leaks are caused by `yii\base\ErrorHandler::register()` method which internally uses `str_pad()` to reserve some merory for fatal error handling:

![image](https://user-images.githubusercontent.com/980679/211789777-3b55a0d0-0395-4c3b-9f0f-e32acd55155e.png)

It works perfect in classic (but not performant) PHP short-living application approach but behaves badly in long-running approach where one application instance responses to many requests.

Any ideas on how we can fix this?

### What steps will reproduce the problem?
1. Use RoadRunner through `charlesportwoodii/yii2-psr7-bridge`.
2. Set `memprof` with some `memprof_enable()` and `memprof_dump_callgrind()` calls.
3. Open callgrind profile file in KCachegrind.

### What is the expected result?
`yii\base\ErrorHandler::register()` reserves memory for fatal exception handler only once and not for every request. (?)

### What do you get instead?
`yii\base\ErrorHandler::register()` reserves memory for fatal exception handler for every request.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.2
| Operating system | Debian 11.6 ×64

**Comment by samdark** [comment]
The memory reserved should be freed if the object is destroyed. I guess the bridge package could solve it by killing the app instance and de-registering error handler.

**Comment by samdark** [comment]
Anyway, that's not the framework issue but likely an issue of the bridge package. If not, please feel free to submit a pull request with a fix.

**Comment by maximal** [comment]
@samdark, I think, the whole idea of RoadRunner-based approach is **not** to kill an application instance with every request, so that the framework can process long-living request-response loop. And, I suppose, the framework could handle its memory consumption here.

Anyway, I guess, I should open an issue in that bridge repository. Thanks for the reply!

**Comment by cebe** [comment]
Not sure how RoadRunner handles PHP memory limit but if memory limit exception handling works without the trick we use here you can set the size of errorHandling reserve to 0.
