### ISSUE TITLE
PageCache variations as callable

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#19740]
In order to access the `Yii::$app->user` inside a PageCache variation situation, the variations needs to be a callable. Imagine this situation:

```php
public function behaviors()
{
    return [
        'authenticator' => [
            'class' => CompositeAuth::class,
        ],
        'pageCache' => [
            'class' => PageCache::class,
            'variations' => [
                Yii::$app->user->identitly->prop_user_id,
            ]
        ]
    ];
}
```

This will throw an exception, since `Yii::$app->user->identitly->prop_user_id` is evaulated at runtime while configure the behaviors. But since the Authenticator is running before the pageCache behavior, the user id would be available. In order to fix that `variations` should allow a closure:

```php
public function behaviors()
{
    return [
        'authenticator' => [
            'class' => CompositeAuth::class,
        ],
        'pageCache' => [
            'class' => PageCache::class,
            'variations' => function() {
                return Yii::$app->user->identitly->prop_user_id,
            }
        ]
    ];
}
```

If https://github.com/yiisoft/yii2/blob/master/framework/filters/PageCache.php#L315 `calculateCacheKey` would not be protected, i could at least override the PageCache with my own implementation, but its protected. So i assume the above integration of checking for a closure/callable is the only solution.

If there is another solution to allow full page cache based on the current user, let me know. Afaik, there is no solution, otherwise this would be resolved https://github.com/yiisoft/yii2/issues/19120

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

 I would send a PR if its accepted.

**Comment by samdark** [comment]
Having a callable there makes sense to me.

**Comment by nadar** [comment]
So i'll send a PR.
