### ISSUE TITLE
How to get data come from getRawBody() Because i have string not Object

### ISSUE THREAD

**Issue by chegue2009** [yiisoft/yii2#19756]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

Hello how to use data come from getRawBody() ? Because i just see after send request the data like a string
`"{\r\n    \"data\": [\r\n    618,\r\n    606,\r\n    603,\r\n    597,\r\n    593,\r\n    586,\r\n    585,\r\n    581,\r\n    574,\r\n    554,\r\n    537,\r\n    534,\r\n    529,\r\n    528,\r\n    515,\r\n    511,\r\n    509,\r\n    497,\r\n    479,\r\n    482,\r\n    475,\r\n    473,\r\n   ]\r\n}\r\n   "`

this is the Json i send : 
`{
    "data": [
    618,
    606,
    603,
    597,
    593,
    586,
    585,
    581,
    574,
    554,
    537,
    534,
    529,
    528,
    515,
    511,
    509,
    497,
    479,
    482,
    475,
    473
    ]
}`

this option no work just send empty `Yii::$app->request->post('data')` but `getRawBody()` send string can i get a solution please. I want to get datas come from getRawBody()

**Comment by lubosdz** [comment]
Not enough information to judge. You should show code sending the request, or at least what is `$_POST` / `$_GET` content. 
Also [this](https://github.com/yiisoft/yii2/issues/16045) might be helpful. Why do you need specifically `rawBody` ? There are other useful [ways](https://www.yiiframework.com/doc/guide/2.0/en/runtime-requests) to retrieve `Request` data.

**Comment by notaidea** [comment]
try this config,
and then：Yii::$app->request->post('data')

'request' => [
    // other configs

    'parsers' => [
        //json输入
        'application/json' => 'yii\web\JsonParser',
    ],
],
