### ISSUE TITLE
swiftmailer/swiftmailer is an abandoned package -> replace ?

### ISSUE THREAD

**Issue by jokamax** [yiisoft/yii2#19751]
Hi just to note that : 

### What steps will reproduce the problem?
swiftmailer/swiftmailer is an abandoned package and no longer maintained (2021)

### What do you get instead?
The author suggests using the/symfony/mailer package instead

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45

**Comment by bizley** [comment]
https://github.com/yiisoft/yii2-symfonymailer
