### ISSUE TITLE
PHP 8.1 Warning

### ISSUE THREAD

**Issue by SmitSLK** [yiisoft/yii2#19757]
### What steps will reproduce the problem?
An error occurs when trying to write to the log
`FastCGI sent in stderr: "PHP message: PHP Warning:  Attempt to read property "enabled" on array in /vendor/yiisoft/yii2/log/Dispatcher.php on line 190PHP`
### What is the expected result?

After changing code `if (!$target->enabled) {` to `if (!$target->getEnabled()) {`
warning disappears

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.1
| Operating system |Ubuntu 22.04

**Comment by schmunk42** [comment]
Can you post a call-stack?
Is `$target` called by your application in a very early state before the `LogTarget` is fully initialized, eg. `bootstrap` or config?

**Comment by SmitSLK** [comment]
<details>
<summary>stack</summary>
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)

#1 /vendor/yiisoft/yii2/base/ErrorHandler.php(154): yii\log\Logger->flush(true)

#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\di\NotInstantiableException))

#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#1 /vendor/yiisoft/yii2/base/ErrorHandler.php(154): yii\log\Logger->flush(true)
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\di\NotInstantiableException))
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#1 /vendor/yiisoft/yii2/base/ErrorHandler.php(154): yii\log\Logger->flush(true)
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\di\NotInstantiableException))
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#1 /vendor/yiisoft/yii2/base/ErrorHandler.php(154): yii\log\Logger->flush(true)
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\di\NotInstantiableException))
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, false)
#1 /vendor/yiisoft/yii2/log/Logger.php(137): yii\log\Logger->flush()
#2 [internal function]: yii\log\Logger->yii\log\{closure}()
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, false)
#1 /vendor/yiisoft/yii2/log/Logger.php(137): yii\log\Logger->flush()
#2 [internal function]: yii\log\Logger->yii\log\{closure}()
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, false)
#1 /vendor/yiisoft/yii2/log/Logger.php(137): yii\log\Logger->flush()
#2 [internal function]: yii\log\Logger->yii\log\{closure}()
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, false)
#1 /vendor/yiisoft/yii2/log/Logger.php(137): yii\log\Logger->flush()
#2 [internal function]: yii\log\Logger->yii\log\{closure}()
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#1 [internal function]: yii\log\Logger->flush(true)
#0 vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#1 [internal function]: yii\log\Logger->flush(true)
#0 vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#1 [internal function]: yii\log\Logger->flush(true)
#0 /vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#1 [internal function]: yii\log\Logger->flush(true)
</details>

<details>
<summary>config</summary>
    
       <?php
        $params = array_merge(
        require(__DIR__ . '/../../common/config/params.php'),
        require(__DIR__ . '/../../common/config/params-local.php'),
         require(__DIR__ . '/params.php'),
        require(__DIR__ . '/params-local.php')
        );
    return [
    'id' => '',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'api\controllers',
    'components' => [
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'agielks\yii2\log\json\FileTarget',
                    'levels' => ['error', 'warning'],
                    'decodeMessage' => true,
                    'includeContext' => true,
                    'logVars' => ['_GET', '_SERVER', '_POST'], // Disable logging of _SERVER, _POST, etc.
                    'except' => [
                        'yii\web\HttpException:*',
                    ],
                    'logFile' => '@app/runtime/logs/app.json',
                    //'enabled' => false,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                    'enabled' => true,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error'],
                    'categories' => ['issue'],
                    'logFile' => '@app/runtime/logs/issues.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                    'enabled' => true,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning','info'],
                    'categories' => ['reward', 'event_history'],
                    'logFile' => '@app/runtime/logs/rewards.log',
                    'logVars' => ['_GET', '_POST'],
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                    'enabled' => true,
                ],
            ],
        ],
        'request' => [
            'enableCsrfValidation' => false,
        ],
        'response' => [
            'format' => yii\web\Response::FORMAT_JSON,
            'formatters' => [
                \yii\web\Response::FORMAT_JSON => [
                    'class' => 'yii\web\JsonResponseFormatter',
                    'prettyPrint' => YII_DEBUG,
                ],
            ],
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => false,
            'rules' => [
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ],
        ],

     ],

    'params' => $params,
    ];

</details>

The problem was in the class `agielks\yii2\log\json\FileTarget`
after installing this extension the error disappears
In PHP7.4 there was no such behavior, an error about a missing class was written to the log
in 8.1 after adding `!$target->getEnabled()`, such a log entry starts to appear

**Comment by schmunk42** [comment]
Is your application running in `YII_ENV_PROD`? If yes, do get an exception in `YII_ENV_DEV`?

I assume we can close this, since it's no Yii issue, but a missing class/package.

**Comment by SmitSLK** [comment]
Both options have the same behavior. Without an installed extension, an error is written to the logs nginx `FastCGI sent in stderr: "PHP message: PHP Warning:  Attempt to read property "enabled" on array in /vendor/yiisoft/yii2/log/Dispatcher.php on line 191"`
@schmunk42 I agree, we can close
