### ISSUE TITLE
PHP8.2 changes PK from string to integer

### ISSUE THREAD

**Issue by nikdow** [yiisoft/yii2#19753]
### What steps will reproduce the problem?
Upgrade PHP to 8.2
access database records using Yii activequery where the mysql table has an integer PK

### What is the expected result?
under PHP8.0 PK presented in Yii2 models is a string even though is integer in the database (mysql). 

### What do you get instead?
Without changing the version of Yii2 (2.0.47), under PHP8.2 the PK is returned as integer. 

### Additional info
also tested using branch php82, same issue.
behaviour seems to depend only on PHP version, not on Yii.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.2
| Operating system |  both Linux and Windows show this issue

**Comment by nikdow** [comment]
I've now also found that non-PK fields are being presented as integer in PHP8.2, previously (PHP8.0) as string.
In mysql we represent a boolean using tinyint. Previously Yii model -> asArray() would return "1" or "0", now returning integer 0 or 1.

**Comment by nikdow** [comment]
I've given up testing 8.2 until I can install it via composer.
Meanwhile, we've gone live with PHP8.1 and the integerisation problem exists between 8.0 and 8.1.
A whole lot of database fields, typically PKs and FKs that were previously presented as strings are now showing up as integers. 
I should also add our serializer uses asArray() in all queries. Hence everything was string, but in PHP8.1 any field which is integer  in the db schema is turning up as an integer in the serializer and thence in the browser.  This is causing havoc with filters and lookups!

**Comment by PowerGamer1** [comment]
This is a change for the better in PHP and should NOT be worked around back to a worse state in Yii. This issue should be closed.

@nikdow  If your old code can't handle proper types simply use PDO::ATTR_STRINGIFY_FETCHES attribute in your Yii database config.

**Comment by nikdow** [comment]
thanks for confirming it's a PHP change. Would that be in the PDO code?
Our code is updated to cast all PKs and FKs to (int) now. So we don't care what PHP, PDO or mySQL do in future.
But it took a long time to find all the places that needed updating and I'm disappointed it doesn't seem to be documented anywhere.

**Comment by nikdow** [comment]
BTW running on PHP8.2 now that Yii2 has provided a compatible update.  All good.
