### ISSUE TITLE
Cannot set pageSize=0

### ISSUE THREAD

**Issue by mozart77** [yiisoft/yii2#19763]
### What steps will reproduce the problem?
Make REST query with "per-page" param set to 0
### What is the expected result?
Get ALL records from table
### What do you get instead?
Got only 1 record

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.1
| Operating system |FreeBSD, Ubuntu

Hi. A sample code I use for getting all users from table:
```php
public static function indexUsers()
  {
     $query = Users::find()
      ->alias('u')
      ->select(['u.*', 'b.title branch', 'GROUP_CONCAT(ai.description SEPARATOR "\n") roles'])
      ->leftJoin('branches b', 'b.id = u.branches_id')
      ->where(['<>', 'state', Users::STATE_DELETED])
      ->groupBy('u.id');

    $q = new ActiveDataProvider([
      'query' => $query,
    ]);

    Yii::debug(Yii::$app->request->getQueryParam('per-page'));
    Yii::debug($q->pagination->pageSize);

    return $q;
  }
```
When I make request like `https://myapp/api/users?sort=-id&page=1&per-page=0` I get only 1 record from table. Meanwhile  other numbers in per-page param work well.
In debug I see following:

![2023-02-10_17-36-16](https://user-images.githubusercontent.com/6299334/218119010-d59b0451-85fb-4175-9cc3-fe8e42219a69.png)

Any ideas what I'm doing wrong?

**Comment by bizley** [comment]
Does it help of you set https://github.com/yiisoft/yii2/blob/master/framework/data/Pagination.php#L125 to false?

**Comment by mozart77** [comment]
> Does it help of you set https://github.com/yiisoft/yii2/blob/master/framework/data/Pagination.php#L125 to false?

Yes, it does. Also helps to pageSize explicitly in code like:
```php
$q = new ActiveDataProvider([
      'query' => $query,
       'pagination' => [
        'pageSize' => 0,
      ] 
    ]);
```
