### ISSUE TITLE
JSON helper does not properly support empty generator

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#19766]
### What steps will reproduce the problem?
Serializing an empty generator returns `{}` instead of `[]`.

### What is the expected result?
A generator should be interpreted as a list of results not a dictionary.

### What do you get instead?
Because `BaseJSON::processData()` applies special handling to objects and generators are objects this special handling is applied.

The relevant code is this part:
```php
/*
 * $data type is changed to array here and its elements will be processed further
 * We must cast $data back to object later to keep intended dictionary type in JSON.
 * Revert is only done when keepObjectType flag is provided to avoid breaking BC
 */
$revertToObject = static::$keepObjectType;

$result = [];
foreach ($data as $name => $value) {
    $result[$name] = $value;
}
$data = $result;

// Avoid empty objects to be returned as array (would break BC without keepObjectType flag)
if ($data === []) {
    $revertToObject = true;
}
```
So if the generator is empty then the result is an empty array and it is cast to an object. 
I believe that similar to other specific objects:
```php
if ($data instanceof JsExpression) {
                $token = "!{[$expPrefix=" . count($expressions) . ']}!';
                $expressions['"' . $token . '"'] = $data->expression;

                return $token;
            }

            if ($data instanceof \JsonSerializable) {
                return static::processData($data->jsonSerialize(), $expressions, $expPrefix);
            }

            if ($data instanceof \DateTimeInterface) {
                return static::processData((array)$data, $expressions, $expPrefix);
            }

            if ($data instanceof Arrayable) {
                $data = $data->toArray();
            } elseif ($data instanceof \SimpleXMLElement) {
                $data = (array) $data;

                // Avoid empty elements to be returned as array.
                // Not breaking BC because empty array was always cast to stdClass before.
                $revertToObject = true;
            } 
```
Special handling should be added for a generator.
I'm willing to implement a PR for this.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.latest
| PHP version      | N/A
| Operating system | N/A

**Comment by lubosdz** [comment]
Can you not simply test in your code e.g. `if ( !$generator ) { ... }` ? This could be a BC with performance impact.

**Comment by SamMousa** [comment]
Of course, but since the generator might be part of a nested structure I'd be essentially re-implementing the helper.
Also, internal things like the response formatter use this encoder, so I'd be forced to reimplement a lot of related classes as well.

Any bugfix will be a BC break, by definition. I don't think it has a performance impact, a type check in PHP is not expensive.

Can you think if any case where you want an non-empty generator to return `['item1', 'item2']` and an empty generator to return `{}`? I cannot imagine a situation where this is desired behavior.

**Comment by bizley** [comment]
Yes, I think we can add generator handling here, it shouldn't be a problem.
