### ISSUE TITLE
Add pcntl to (non-mandatory) requirements

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#19779]
### What steps will reproduce the problem?

Running into weird problem with `yii2-queue`, eg. non-terminating child-processes, etc..

### What is the expected result?

"Correct", unix-style process handling.

### What do you get instead?

Weird errors :)

### Additional info

Related:
- https://github.com/yiisoft/yii2-queue/pull/229
- https://github.com/yiisoft/yii2-queue/issues/439

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 8.x
| Operating system | Docker Debian

I think it should be checked for `pcntl` in RequirementsChecker and I'd also recommend to add this to the minimal Docker images.

**Comment by samdark** [comment]
Yes, I think it is a good idea to add it to requirements checker as optional dependency.

**Comment by schmunk42** [comment]
Should be fixed in #19780.
