### ISSUE TITLE
MysqlMutex using DB-Expressions in param binding

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#19770]
### What steps will reproduce the problem?

Use `MysqlMutex` without a `keyPrefix`

### What is the expected result?

Mutex names prefixed with database name.

### What do you get instead?

Literal prefix for every mutex `DATABASE()....`

Default prefixes were introduced in https://github.com/yiisoft/yii2/pull/19603/files
Related issue: https://github.com/yiisoft/yii2/issues/19316

AFAIK param binding does not work when using an expression as the param value.
Maybe we could use a hash of the DSN instead?

There's even a test for expressions: https://github.com/yiisoft/yii2/pull/19603/files#diff-03b85638c9569a6ea11d1599940f6fd0a87ef06c60942f9a9e43644c9c66a650R63-R64
But the expressions are also different as strings.

If Expressions as params would work; there should be a test with two Expressions `1+1` and `1*2` to see if both evaluate to `2`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.x
| Operating system | Debian (Docker)

CC: @rob006 @samdark @kamarton @sanwv @handcode @eluhr @amk0

**Comment by kamarton** [comment]
> If Expressions as params would work; there should be a test with two Expressions 1+1 and 1*2 to see if both evaluate to 2.

Test result is **FAIL**.

> AFAIK param binding does not work when using an expression as the param value.

I haven't been actively working on the yii2 project for a while now, so I'm a bit puzzled by the `\yii\db\Expression` class. Based on the generated query, if the `Expression` is used as a parameter, it is compiled into a string for the query.

```sql
SELECT GET_LOCK(SUBSTRING(CONCAT('1+1', 'adc8de6b036aed3455b44abc62639e708d3ffe'...
```

It seems to me that if the `Expression` is used as a parameter, it will receive a string cast, which will result in the value of the Expression being converted to a string.

https://github.com/yiisoft/yii2/blob/f388ca71b08b89e940f1ffbe4afa19ae9d5e115f/framework/db/Expression.php#L62-L65

Is this the correct behavior?

**Comment by handcode** [comment]
The "problem" here is, how the query is build.

```php
            return (bool) $db->createCommand(
                'SELECT GET_LOCK(SUBSTRING(CONCAT(:prefix, :name), 1, 64), :timeout)',
                [':name' => $this->hashLockName($name), ':timeout' => $timeout, ':prefix' => $this->keyPrefix]
            )->queryScalar();
```

In PDO the value for the `:prefix` param is only a string  (PDO does not know anything about Yii2 expressions, how could it?) and therefore it is escaped and put in quotes. And if `$this->keyPrefix` is not an Expression, this is also exactly what we want (keyprefix can be something like `"what -- 'ever'"`).

As far as I can see in the PDO code (I'm not a C hacker ;-), if no explicit `PDO_PARAM_TYPE` is specified, the type from the php internal ZVAL is used and then only distinguishes between INT, BOOL or string.
https://github.com/php/php-src/blob/master/ext/pdo/pdo_stmt.c#L252

So if query is build this way, IMHO we must check if `keyPrefix` is an instance of Expression and if yes inject the value without param binding.

```php
    protected function acquireLock($name, $timeout = 0)
    {
        return $this->db->useMaster(function ($db) use ($name, $timeout) {

            /** @var \yii\db\Connection $db */
            if ($this->keyPrefix instanceof Expression) {
                return (bool) $db->createCommand(
                    'SELECT GET_LOCK(SUBSTRING(CONCAT(' . $this->keyPrefix .', :name), 1, 64), :timeout)',
                    [':name' => $this->hashLockName($name), ':timeout' => $timeout]
                )->queryScalar();
            }

            return (bool) $db->createCommand(
                'SELECT GET_LOCK(SUBSTRING(CONCAT(:prefix, :name), 1, 64), :timeout)',
                [':name' => $this->hashLockName($name), ':timeout' => $timeout, ':prefix' => $this->keyPrefix]
            )->queryScalar();
            
        });
    }
```
Of course this must also be changed in `releaseLock`.

But maybe someone has a better way to create the command with yii2 query builder magick ;-)

**Comment by kamarton** [comment]
> So if query is build this way, IMHO we must check if keyPrefix is an instance of Expression and if yes inject the value without param binding.

A similar workaround works. However, it is still not clear to me why the yii2 command builder does not handle `Expression` within its own scope.

**Comment by schmunk42** [comment]
> However, it is still not clear to me why the yii2 command builder does not handle Expression within its own scope.

I think that's because Query Params are handled by PDO and not the framework.

**Comment by kamarton** [comment]
> I think that's because Query Params are handled by PDO and not the framework.

- `$db` -> `yii\db\Connection`  Yii provided class
- `createCommand()` -> Yii provided method

The question is whether it is intentionally not supported or if there has never been a need for it. I haven't looked at the code, but it might be more practical to implement Expression support rather than ad-hoc solutions like the one above. What do others think about this?

**Comment by rob006** [comment]
There should be at least warning when `Expression` is passed as parameter in this scenario. The fact that expression is silently cast to string and treated as literal value is massive footgun.

**Comment by handcode** [comment]
Maybe my expectations are wrong, but if plain SQL with a params array is passed to `Connection::createCommand` like here, then I think that's ok if it behaves as if I would create the same statement directly with PDO.

Anyway: if a check of the passed params is added in `Connection::createCommad`, resp. `Command::bindValues`, please don't check for ExpressionInterface, because e.g. PdoValue is completely valid.

**Comment by kamarton** [comment]
> Maybe my expectations are wrong, but if plain SQL with a params array is passed to Connection::createCommand like here, then I think that's ok if it behaves as if I would create the same statement directly with PDO.

Converting a `\yii\db\Expression` to a string is meaningless when binding the value, and it's a complete "footgun".

**Comment by handcode** [comment]
(sql) expression as a param for a prepared statement is wrong usage, because one of the main purposes of a prepared statement with bind params is to prevent SQL injections, but that's exactly what you want.

But we are going in circles.

**Comment by kamarton** [comment]
fixed, reviewable https://github.com/yiisoft/yii2/pull/19772/files
