### ISSUE TITLE
PHP Warning – DateValidator:445

### ISSUE THREAD

**Issue by qstart-soft** [yiisoft/yii2#19776]
<img width="1789" alt="Screen 2023-02-25 в 13 31 57" src="https://user-images.githubusercontent.com/60501939/221352300-063349bd-adc9-4a3c-a8a9-cd684868c0df.png">

### Additional info

| Q                             | A
| ------------------ | ---
| Yii version              | 2.0.47
| PHP version           | 8.2.3
| Operating system | MacOs

**Comment by dkduyanh** [comment]
resolved in https://github.com/yiisoft/yii2/issues/19635
