### ISSUE TITLE
Should a DB slave that is behind the master be able to serve outdated data

### ISSUE THREAD

**Issue by developedsoftware** [yiisoft/yii2#19786]
We are using https://www.yiiframework.com/doc/guide/2.0/en/db-dao#read-write-splitting to ensure masters are only used to writes and slaves for reads. Its working very well however sometimes if a slave falls behind the master in terms of replication we get old data returned during reads.

Is there anything that checks the SECONDS_BEHIND_MASTER property of the slave? 

I am aware Yii tracks whether the slave is online/offline but is it able to check if the slave is up to date? 

How would one handle such a situation?

### What steps will reproduce the problem?

Create a transaction
Perform X queries
Commit Transaction
Immediatly fetch from one of the tables that you updated in "Perform X queries" 

### What is the expected result?
The committed data to be returned

### What do you get instead?
Old data from the slave (its replication has not caught up with master)

### Additional info

We are getting around this by setting `enableSlaves` to false when we begin a transaction. But this seems a "hacky" workaround. Ideally it would be nice to have yii track whether a slave is up to date and ready to serve read requests (and if not fall back to the master like we do when we set `enableSlaves` to false)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.1.16
| Operating system | x86_64-redhat-linux-gnu

**Comment by My6UoT9** [comment]
If SECONDS_BEHIND_MASTER only has seconds, this won't be reliable.

I would recommend to simply use the master to reread content, this way you can still use both, instead of enforcing only one.
```php
$success = $model->save();
if (false === $success) {
	$error = $model->getErrors($attr);
} else {
	//reload data from db, in case the db itself altered the value
	$value = \Yii::$app->db->useMaster(function($db) use ($model, $attr) {
		$model->refresh();
		$value = $model->{$attr};
		return $value;
	});
}
```

**Comment by developedsoftware** [comment]
Thats much better, thanks!
