### ISSUE TITLE
JsonHelper tests require conditional flow for PHP 5.4

### ISSUE THREAD

**Issue by bizley** [yiisoft/yii2#19796]
https://github.com/yiisoft/yii2/blob/master/tests/framework/helpers/JsonTest.php#L102

This line must be without `$name =>` for PHP 5.4.

**Comment by rhertogh** [comment]
@bizley Generators are only supported since PHP 5.5 (https://www.php.net/releases/5_5_0.php#:~:text=Added%20generators%20and%20coroutines.).

I've created a PR (https://github.com/yiisoft/yii2/pull/19798) that completely skips this test step for PHP < 5.5.
