### ISSUE TITLE
Pagination bootstrap CSS broken in yii\widgets\LinkPager starting Bootstrap 4

### ISSUE THREAD

**Issue by alexnas77** [yiisoft/yii2#19797]
Greetings.

I have discovered that during usage standard LinkPager widget there is a CSS break.

![image](https://user-images.githubusercontent.com/18441119/228188097-8be1063e-4589-495f-bd53-58afd1819cb9.png)

It suppose to look like this.

![image](https://user-images.githubusercontent.com/18441119/228187898-b6bafea9-4528-44ff-ae41-7209711da452.png)

To fix this issue i had to do such modifications.

https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php

# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/widgets/LinkPager.php
+++ b/widgets/LinkPager.php
@@ -45,12 +45,12 @@
      * @var array HTML attributes which will be applied to all link containers
      * @since 2.0.13
      */
-    public $linkContainerOptions = [];
+    public $linkContainerOptions = [ 'class' => "page-item" ];
     /**
      * @var array HTML attributes for the link in a pager container tag.
      * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
      */
-    public $linkOptions = [];
+    public $linkOptions = [ 'class' => "page-link" ];
     /**
      * @var string the CSS class for the each page button.
      * @since 2.0.7
@@ -245,10 +245,10 @@
         }
         if ($disabled) {
             Html::addCssClass($options, $this->disabledPageCssClass);
-            $disabledItemOptions = $this->disabledListItemSubTagOptions;
-            $tag = ArrayHelper::remove($disabledItemOptions, 'tag', 'span');
+            //$disabledItemOptions = $this->disabledListItemSubTagOptions;
+            //$tag = ArrayHelper::remove($disabledItemOptions, 'tag', 'span');
 
-            return Html::tag($linkWrapTag, Html::tag($tag, $label, $disabledItemOptions), $options);
+            //return Html::tag($linkWrapTag, Html::tag($tag, $label, $disabledItemOptions), $options);
         }
         $linkOptions = $this->linkOptions;
         $linkOptions['data-page'] = $page;

 The result was
![image](https://user-images.githubusercontent.com/18441119/228187503-27d608cf-538d-4c41-ac88-d4c786842f01.png)

**Comment by alexnas77** [comment]
[LinkPager.zip](https://github.com/yiisoft/yii2/files/11087575/LinkPager.zip)

My version of this file.

**Comment by monta990** [comment]
i fix it wirh this code in my config file.

    'container' => [
        'definitions' => [
        \yii\widgets\LinkPager::class => \yii\bootstrap5\LinkPager::class,
        ],
    ],

**Comment by samdark** [comment]
As @monta990 suggested, you need to override it like in the above config.
