### ISSUE TITLE
DateValidator Issue : Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by massikage** [yiisoft/yii2#19791]
### What steps will reproduce the problem?
Hello everyone,
When I try to validate my model which has a date, on the controller at the line where I do: if ($model->validate())
Model
![Capture d’écran 21-03-2023 11 02 51](https://user-images.githubusercontent.com/57631388/226573820-87a79082-0650-46b7-9914-7ea1a9df619c.png)

Controller
![Capture d’écran 21-03-2023 11 05 11](https://user-images.githubusercontent.com/57631388/226574327-f33b994f-2732-40e3-9b2d-55c1e5c80650.png)

it gives me this error from DateValidator: "Trying to access array offset on value of type bool"

![Capture d’écran 21-03-2023 10 43 02](https://user-images.githubusercontent.com/57631388/226573221-ba69868b-38e4-4990-98d8-cf8f53f8175e.png)

In fact, on line 444 of DateValidator.php, the variable $errors === false, and the following line, we call: $errors['error_count'], hence this error

being a beginner in yii and php, I don't know if I should touch vendor code, or solve this problem otherwise
Thank you for your help

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.2
| Operating system | Windows 10

**Comment by bizley** [comment]
Already fixed in https://github.com/yiisoft/yii2/pull/19713 , awaits release.
