### ISSUE TITLE
Bug? HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by peter844** [yiisoft/yii2#19795]
### What steps will reproduce the problem?
https://your_yii2_site.com////bin///wcm///search///gql.json;%0aa.html

### What is the expected result?
HTTP 404 Not Found

### What do you get instead?
HTTP 500 Internal Server Error

### Additional info

93.188.161.159 - - [28/Mar/2023:01:25:27] "GET ///bin///wcm///search///gql.json;%0aa.html?pathPrefix&query=type:base%20limit:..1 HTTP/1.1" 500 10726 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36"

[28-Mar-2023 01:25:27] PHP Warning:  Header may not contain more than a single header, new line detected in /var/www/framework/yii/2.0.34/yiisoft/yii2/web/Response.php on line 374

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.34
| PHP version      |  7.4
| Operating system | Linux

**Comment by bizley** [comment]
The error indicates this is because of your code or the server misconfiguration. Please provide us with a minimal reproducible code and then we can take a look.

**Comment by peter844** [comment]
> The error indicates this is because of your code or the server misconfiguration. Please provide us with a minimal reproducible code and then we can take a look.

try your yii2 site with ////bin///wcm///search///gql.json;%0aa.html

for example https://www.humhub.com/////bin///wcm///search///gql.json;%0aa.html

**Comment by bizley** [comment]
I've tested it on one of my sites and I can see 404. As I said, please provide a minimal reproducible example, we don't have access to the websites you mentioned earlier.

**Comment by bizley** [comment]
Ok, this looks like a case when routing is set to redirect to that url. We should fix it.

**Comment by samdark** [comment]
Why are there multiple headers in this case?

**Comment by bizley** [comment]
`%0A` decoded as a new line character. This is one of the common attack vectors but PHP took care of it some time ago. I'm asking because we are already throwing exception there anyway, so I'm not sure if we should intercept this warning somehow and throw 400 or something.

**Comment by samdark** [comment]
I think we should do it. It is at least a way to spam logger.
