### ISSUE TITLE
Erro when use date validor with format option

### ISSUE THREAD

**Issue by caio-brendo** [yiisoft/yii2#19799]
### What steps will reproduce the problem?
```
 $model = new \yii\base\DynamicModel(['date' => '29/03/2023']);
        $model->addRule(['date'], 'date', ["format" => "php:d/m/Y"])->validate();

        if ($model->hasErrors()) {
            echo 'error';
        } else {
            echo 'success';
        }
```

### What is the expected result?
show success

### What do you get instead?
i received "PHP Warning – yii\base\ErrorException Trying to access array offset on value of type bool" exception.

yiisoft\yii2\validators\DateValidator.php:445

but when i put ini_set('error_reporting', '~E_ALL') bofore validate() mthod wroks. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.2.1
| Operating system | windows

**Comment by bizley** [comment]
It's fixed already in https://github.com/yiisoft/yii2/pull/19713 and waiting for release.
