### ISSUE TITLE
with() joinWith() and join - makes extra query

### ISSUE THREAD

**Issue by brain2xml** [yiisoft/yii2#19802]
I have 2 models Material and Data. And Material has relationship with Data

```
public function getData()
{
        return $this->hasOne(Data::className(), ['id' => 'id']);
}
```

echo  $material->data->title;  makes 2 queries

SELECT * FROM "pgvk_material" WHERE "pgvk_material"."id"=417974
SELECT * FROM "pgvk_data" WHERE "id"=417974

now I try use with() and joinWith() and still have two queris

```
SELECT "pgvk_material".*, "pgvk_data".* FROM "pgvk_material" LEFT JOIN "pgvk_data" ON "pgvk_material"."id" = "pgvk_data"."id" WHERE "pgvk_material"."id"=417974
SELECT * FROM "pgvk_data" WHERE "id"=417974
```

even if I use join

```
$material = \app\models\Material::find()
            ->select('"pgvk_material".*,  "pgvk_data".*')
            ->innerJoinWith(
                'data',
                'pgvk_material.id = pgvk_data.id')
            ->where(['pgvk_material.id'=> 417974])
            ->one();
```

I still have two queris

```
SELECT "pgvk_material".*, "pgvk_data".* FROM "pgvk_material" INNER JOIN "pgvk_data" ON "pgvk_material"."id" = "pgvk_data"."id" WHERE "pgvk_material"."id"=417974
SELECT * FROM "pgvk_data" WHERE "id"=417974
```

I don't know why? If first query has all data

Yii 2.0.12

**Comment by bizley** [comment]
Please try the newest version if this is still a problem and if so come back to us.

**Comment by notaidea** [comment]
yes,it will run 2 queries.

this sql :`SELECT "pgvk_material".*, "pgvk_data".* FROM "pgvk_material" LEFT JOIN ......` is to populate the `Material`
this sql:`SELECT * FROM "pgvk_data" WHERE "id"=417974` is to populate the `Data`
if you get an extra filed from the main-model `Material`,it will call the related-model `Data`

for more detail,see ActiveRecord.__get()

**Comment by notaidea** [comment]
if you really wanna only run one query,you need to add a field in the main-model `Material`:

`class Material extends ActiveRecord
{
    // this filed must not conflict with the material table
    public $title;
}`

// dom't use with()
$material = Material::find()->joinWith(xx)->one();
echo $material->title;
