### ISSUE TITLE
https://github.com/yiisoft/yii2/issues/19797

### ISSUE THREAD

**Issue by alexnas77** [yiisoft/yii2#19803]
https://github.com/yiisoft/yii2/issues/19797#issuecomment-1487168834

With all do respect this is a workaround.

Instead of fix the project you advise to new users to take this fix for themselves.

Do we really need to drop standard class in Yii2 framework and replace to something else?

**Comment by bizley** [comment]
Please don't start a new issue to post a comment. Core LinkPager widget is meant to be stylized by a developer hence the comment there. Core should not force users to use Bootstrap.
