### ISSUE TITLE
Execute update SQL syntax without updating data

### ISSUE THREAD

**Issue by harusakura924** [yiisoft/yii2#19829]
### What steps will reproduce the problem?

Table Schema:
| name | type | info |
| -- | -- | -- |
| `id` | int(11) | PRIMARY, AUTO_INCREMENT |
| `type` | int(11) |  |
| `name` | varchar(50) |  |
| `status` | char(1) |  |

Table Value:
| id | type | name | status |
| -- | -- | -- | -- |
| 2 | 1 |  ANABELLE | 1 |

And use GII to generate the CRUD of the data table.

In edit mode, don't change any information and just press save.

### What is the expected result?

Does not execute any update SQL syntax.

### What do you get instead?

It still executes the following nonsensical syntax while running.

```sql
UPDATE `ContactTest` SET `type`=1 WHERE `id`=2
```

![2023-05-08 12_17_42-Clipboard](https://user-images.githubusercontent.com/60030937/236733144-9c5c5e8f-8432-4aa7-8f4c-2a89545c8b86.png)

### Additional info

| Q  | A |
| --- | --- |
| Yii version | 2.0.47|
| PHP version  |  5.4.16 |
| Operating system | Linux 3.10.0 |

**Comment by bizley** [comment]
All values coming from the form fields are strings. What you need here is https://www.yiiframework.com/doc/api/2.0/yii-behaviors-attributetypecastbehavior
