### ISSUE TITLE
Typed property app\models\form\user\LoginForm::$email must not be accessed before initialization

### ISSUE THREAD

**Issue by deale** [yiisoft/yii2#19839]
https://github.com/yiisoft/yii2/blob/0a811cbd0d373f7a24d110ffc837d27f3112193a/framework/helpers/BaseHtml.php#LL2280C37-L2280C37

**Comment by samdark** [comment]
Which PHP version do you have?

**Comment by bizley** [comment]
This is not about part of the code provided by Yii, right? I don't see that class anywhere, so I guess it's yours. Don't define properties with PHP 8 like that:

```
public string $email;
```

if you don't initialize it immediately. Do that for example:

```
public ?string $email = null;
```

**Comment by deale** [comment]
Добавьте пожалуйста проверку isset($model->$attribute) перед ее использованием. Спасибо.

**Comment by deale** [comment]
property to be initilized в момент использования. Если необходимо проверить существование свойства перед его использованием, достаточно isset($model->$attribute)

**Comment by NikitaLednev** [comment]
Привет! Я могу вручную проверять существование любых переменных, но вот писать свой валидатор для форм на основе yii\base\Model так себе уже затея. Это я к тому, что при указании типов переменных в формах при валидации она постоянно вылетает. Ставить значения по умолчанию в формы не катит, поскольку не всегда могу из реквеста прокинуть в форму все переменны, что в ней есть и тогда это значение по умолчанию может залететь в основную запись

Может кто знает как обойти такую ерунду?
