### ISSUE TITLE
compatibility bower-asset/jquery 3.7

### ISSUE THREAD

**Issue by itgenolife** [yiisoft/yii2#19841]
### What steps will reproduce the problem?
try to update jquery
### What is the expected result?
install compatibility bower-asset/jquery 3.7 version
### What do you get instead?
fail to update

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      |  8.2.6
| Operating system | CentOS 7.9

**Comment by bizley** [comment]
What is your error?

**Comment by itgenolife** [comment]
Hi, mean it´s not a funcionalliry issue, if for add compatibility for jquery 3.7

https://github.com/yiisoft/yii2/blob/0fcd434c97a4c7bc8cd002303078945d872106e9/composer.json#L78
