### ISSUE TITLE
Ampersands in links result encoded in canonical tags

### ISSUE THREAD

**Issue by inwoker** [yiisoft/yii2#19858]
Possible bug or absence of feature in $app->view->registerLinkTag or maybe there should be a separate function for canonical tag

### What steps will reproduce the problem?
```php
$url = 'http://site.com/books?type=paper&publisher=oreilly';
Yii::$app->view->registerLinkTag([
    'rel' => 'canonical',
    'href' => $url,
]);
```

### What is the expected result?
either `<link rel='canonical' href='http://domain.com/books?type=paper&publisher=oreilly'>` or being able to do that with some function parameters or other function

### What do you get instead?
`<link rel='canonical' href='http://domain.com/books?type=paper&amp;publisher=oreilly'>`
& changes to `&amp;` which screws up some SEO

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.48
| PHP version    |  8.2
| Operating system | ubuntu linux

**Comment by samdark** [comment]
It can't screw up any SEO and is correct. `href` is HTML attribute and as per HTML spec `&` should be properly escaped in values. `&` in attribute values isn't correct and should be always `&amp;`.
