### ISSUE TITLE
error beforeSave create UUID

### ISSUE THREAD

**Issue by atmanegara** [yiisoft/yii2#19862]
### What steps will reproduce the problem?
1. code my model beforeSave
 
`public function beforeSave($insert)
{
        if($this->isNewRecord){
                $this->myfieldKey = new \yii\db\Exception('UUID()');
        return parent::beforeSave($insert);
        }
}`
<img width="455" alt="image" src="https://github.com/yiisoft/yii2/assets/9096711/1892c929-b230-46e6-a7c3-ce97ee95f310">

2. in controller save()
<img width="683" alt="image" src="https://github.com/yiisoft/yii2/assets/9096711/94b0e869-37da-42a4-aa8e-177afabb9bb5">

get error

![image](https://github.com/yiisoft/yii2/assets/9096711/597b76a2-18bf-49bd-9937-7039502bcac2)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.48.1
| PHP version      |  8.1.9
| Operating system | win 11 (22H2)

**Comment by samdark** [comment]
What's the exception message?

**Comment by samdark** [comment]
You should use Expression, not Exception.
