### ISSUE TITLE
Yii debug (Object of class Symfony\Component\Mime\Header\Headers could not be converted to string)

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#19860]
Yii debug have error when open mail info with symfonymailer
SwiftMailer do not have this troubles

### What steps will reproduce the problem?
1) Open Yii-debug panel
![Screenshot 2023-06-07 142716](https://github.com/yiisoft/yii2/assets/1358236/9e805e9d-fdf7-4d4c-8a8c-07c2158304a7)

2) Open query with mail
![Screenshot 2023-06-07 142750](https://github.com/yiisoft/yii2/assets/1358236/616bd9d3-0b73-4f4b-81c4-7077fe0d1aed)

3) Open mail tab
![screencapture-local-debug-default-view-2023-06-07-14_01_51](https://github.com/yiisoft/yii2/assets/1358236/f53b1bf2-65f7-4f35-be25-c70d293539f8)

### What is the expected result?
Show debug panerl

### What do you get instead?
Error

### Additional info
I think, problen in Symfony\Component\Mime\Header\Headers
Is need **toString()** method

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.48.1
| PHP version      | 8.2
| Operating system | Docker

**Comment by wartur** [comment]
The problem in
vendor/yiisoft/yii2-debug/src/views/default/panels/mail/_item.php

it need remove headers from
```php
echo DetailView::widget([
    'model' => $model,
    'attributes' => [
        //'headers', // ALL OK
        'from',
        'to',
        'charset',
        [
            'attribute' => 'time',
            'format' => 'datetime',
        ],
        'subject',
        [
            'attribute' => 'body',
            'label' => 'Text body',
        ],
        [
            'attribute' => 'isSuccessful',
            'label' => 'Successfully sent',
            'value' => $model['isSuccessful'] ? 'Yes' : 'No'
        ],
        'reply',
        'bcc',
        'cc',
        [
            'attribute' => 'file',
            'format' => 'html',
            'value' => Html::a('Download eml', ['download-mail', 'file' => $model['file']]),
        ],
    ],
]);
```

But Yii debug mail componetn currently not work fine as with swiftmailer
![Screenshot 2023-06-07 153517](https://github.com/yiisoft/yii2/assets/1358236/5fdf9113-8b77-4330-b0b8-0f3ed8530f33)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-debug/issues/507
