### ISSUE TITLE
ICU 72 breaks formatter tests (Debian 12, PHP 8.1, 8.2)

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#19868]
### What steps will reproduce the problem?

Run Docker builds for 8.1 and 8.2 images.

### What is the expected result?

No errors.

### What do you get instead?

``` 
1) yiiunit\framework\helpers\FormatConverterTest::testIntlIcuToPhpShortFormTime
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'g:i A'
+'g:i A'
``` 

Failing tests with "strings (not) equal", eg. https://github.com/yiisoft/yii2-docker/actions/runs/5301478845/jobs/9615471441#step:10:406

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | all
| PHP version      | PHP 8.1, 8.2
| Operating system | Docker Debian

Underlying issue is a different Debian version, which leads to different ICU versions:
- 8.0 -> Debian 11, ICU 67
- 8.1/8.2 -> Debian 12, ICU 72

From the changelog:
> In many formatting patterns, ASCII spaces are replaced with Unicode spaces (e.g., a "thin space").

https://icu.unicode.org/download/72

### Possible "fixes"

- change tests, would break all builds `<=8.0`, but 8.0 [reaches EOL in 5 months](https://www.php.net/supported-versions.php), we might remove them altogether anyway
- test according to ICU version, more work (logic in tests, but we do this already AFAIR)
- test with a regex-pattern (use `\s` instead of ` `)

**Comment by samdark** [comment]
I'd prefer testing with a regex-pattern or with something like we do with a`ssertEqualsWithoutLE()`.

**Comment by schmunk42** [comment]
@samdark See PR if this would be OK.

I am still getting this one:

```
There was 1 failure:

1) yiiunit\framework\i18n\FormatterDateTest::testIntlAsDatetime
Failed asserting that 'Jun 20, 2023, 11:58:43 AM' matches PCRE pattern "~Jun 20, 2023,? 11:58:43 AM~".

/yii2/tests/framework/i18n/FormatterDateTest.php:181
/yii2/tests/framework/i18n/FormatterDateTest.php:169
/yii2/vendor/phpunit/phpunit/phpunit:52
/yii2/vendor/bin/phpunit:120
```

I don't really understand what's broken here?!

**Comment by schmunk42** [comment]
And ... should `assertSameAnyWS` only look after strings?

**Comment by bizley** [comment]
Maybe some non-breaking space in there?

**Comment by schmunk42** [comment]
@bizley See updated "ugliness" :) 

https://github.com/yiisoft/yii2/pull/19869/files
