### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by ale94lko** [yiisoft/yii2#19863]
### What steps will reproduce the problem?
Navigate to https://www.yiiframework.com/doc/guide/2.0/es/security-auth-clients

### What is the expected result?
The related documentation 

### What do you get instead?
A Not Found (#404) error

### Additional info
![imagen](https://github.com/yiisoft/yii2/assets/47539231/3295618b-9421-4290-b60a-ae4350170b6b)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 
| Operating system |

**Comment by bizley** [comment]
Hm, weird, this chapter is marked with TBD. @samdark some website issue?

**Comment by samdark** [comment]
Fixed.
