### ISSUE TITLE
Able to Inherit web\User.php

### ISSUE THREAD

**Issue by konapaz** [yiisoft/yii2#19874]
### What steps will reproduce the problem?
Extend  the yiisoft\yii2\web\User.php
### What is the expected result?
Access to $_identity
### What do you get instead?
No access to $_identity due to protected

### Additional info
In case someone want to extend the User logic may want to access of $_identity
For example I want to add extra logic to getIdentity method (so I extend the web\User ) due a SPA project and 
set $this->_identity = false in some logic cases. But in yiisoft\yii2\web\User.php  the variable is private, so programmer cannot inherit and access it

`private $_identity = false;`

It should be protected like this

`protected $_identity = false;`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by bizley** [comment]
How come it's impossible for you to work around this in your extended User component? This property is used only in the getter and the setter so it should not be a problem to override them and use your own property.

**Comment by konapaz** [comment]
> How come it's impossible for you to work around this in your extended User component? This property is used only in the getter and the setter so it should not be a problem to override them and use your own property.

You are right, but in this case I was confusing about $this->_Identity = null OR false. For a reason getIdentity check if equal (===) with false and not null. I cannot use setIdentity(false) but only setIdentity(null) (I dont know what is the distinct meaning between false and null in this logic). If its ok, I will use setIdentity(null) and thas all.

**Comment by bizley** [comment]
False is only the default prior to a first read or in case of an error, you should not set it to false otherwise. Glad we could solve it then, cheers.
