### ISSUE TITLE
Non-associative array values in AR aren't considered different

### ISSUE THREAD

**Issue by kyliemsauter** [yiisoft/yii2#19872]
I think there's a still a bug with this, isValueDifferent() is sorting the arrays if they aren't associative when it's supposed to be sorting them when they ARE associative. https://github.com/yiisoft/yii2/blob/85171844cfbfe755feb44b8ffedb1e1006cd0730/framework/db/BaseActiveRecord.php#L1766

_Originally posted by @kyliemsauter in https://github.com/yiisoft/yii2/issues/19743#issuecomment-1613767506_

**Comment by samdark** [comment]
Doesn't look right. Do you have time for a pull request with unit tests (so it doesn't break again ever) and a fix?

**Comment by eegusakov** [comment]
Hi! I would like to fix it

**Comment by olegbaturin** [comment]
[isValueDifferent](https://github.com/yiisoft/yii2/blob/81f3033087b5568442ca4013ce2b6149336722bb/framework/db/BaseActiveRecord.php#L1781) not works for arrays like

```
['', 0, ''],
['', '', 0],
```
values are considered as equal
