### ISSUE TITLE
Suggest ActiveRecord::link() and ActiveRecord::unlink() improvements

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#1990]
First suggestion is to change signature for `ActiveRecord::link()` from:

```
public function link($name, $model, $extraColumns = [])
```

to

```
public function link($name, $models, $extraColumns = [])
```

Use case:

```
$tags = [$tag1, $tag2, tag3];
$post->link('tags', $tags);
```

Effective `batchInsert` can be used there.

Second suggestion is to change signature for `ActiveRecord::unlink()` from:

```
public function unlink($name, $model, $delete = false)
```

to 

```
public function unlink($name, $models, $delete = false)
```

Use case:

```
$tags = [$tag1, $tag2, tag3];
$post->unlink('tags', $tags);
```

Third suggestion is to change signature for `ActiveRecord::unlink()` from:

```
public function unlink($name, $models, $delete = false)
```

to

```
public function unlink($name, $models = [], $delete = false)
```

Use case:

```
$post->unlink('tags'); //mean unlink all tags from post
```

@qiangxue Without that changes its really painful to write something like:

```
$this->owner->getDb()
    ->createCommand()
    ->delete($pivot, [key($relation->via->link) => $this->owner->getPrimaryKey()])
    ->execute();
```

while developing extensions. Also as you see all cases can be used at app level.

**Comment by Faryshta** [comment]
what happened with this issue? its been ready for adoption for 6 months

**Comment by cebe** [comment]
time for someone to pick it up I think ;) Go right ahead.

**Comment by Faryshta** [comment]
I will prepare a PR during the weekend.

For the `extraColumns` parameter. How will it behave? For example if I have an extra column for a date.

```php
$groupLeader->link('proyects', Proyect::find()->all(), ['2010-01-01')]);
```

Will it associate `2010-01-01` date to all the extra fields, thats clear, but how about

```php
$groupLeader->link('proyects', Proyect::find()->all(), [[new Expression('NOW()')], ['2010-01-01']]);
```

would be allowed? how would it behave?

**Comment by codeskull** [comment]
I think we should make two options here:
1) One set of extra field data for all relations like in first @Faryshta's example.
2) An array of the sets for every relation. It would just simply throw an exception in case of unmatched sizes of `$models` and `$extraColumns`.

**Comment by Faryshta** [comment]
@cebe what do you think about that? also another option I just though would be to make a callable function.

```php
function ($relation, $model) {
    return ['now()']
};
```

**Comment by cornernote** [comment]
I made a behavior to do `linkAll()`
https://github.com/cornernote/yii2-linkall-behavior

Handles linking the new models and optionally unlinking the old models.

Would be great to have something like this built into `ActiveRecordBase`.

**Comment by alexjose** [comment]
why no progress on this?

**Comment by samdark** [comment]
Third party solutions are there, noone is willing to work on it, core team is busy with other things.

**Comment by cebe** [comment]
The PR discussion shows that there are a lot of things stopping this from making it a reliable feature.
If someone has a doable solution, feel free to provide it here and we are happy to reopen the issue.
See also https://github.com/yiisoft/yii2/pull/2070#issuecomment-263831480

**Comment by alexjose** [comment]
Laravel Eloquent provides `sync `and `syncWithoutDetaching` which is very much useful. Something like that will be very much appreciated.

**Comment by cebe** [comment]
@alexjose that is a different issue: #8072
