### ISSUE TITLE
Warming some cache in grid after deploy?

### ISSUE THREAD

**Issue by Eugentis** [yiisoft/yii2#19943]
Hi!

I have some simple gridview in my system with column filters and multiselect checkboxes for bulk operations. It's a part of simple admin in my system built by Gii CRUD.

After each deploy on prod my users hit the problem that first grid usage don't allow to filter records in table.
After filling filter field and pressing Enter no search starts. After 2-3 page refresh it works in normal way.

It seems like some page cache should be warmed on deploy stage.

Could you give me advice how I can fix it? Should I use some console command or smth like this to fix this behaviour?

Similar behaviour I've hit on using kartik specific fileds like color inputs in forms.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.0
| PHP version      |  8.2

**Comment by machour** [comment]
Thank you for your question.
In order for this issue tracker to be effective, it should only contain bug reports and feature requests.

We advise you to use our community driven resources:
* [The support forum](http://www.yiiframework.com/forum/)
* [The IRC chat room](http://www.yiiframework.com/chat/)
* [The Gitter chat room](https://gitter.im/yiisoft/yii2)
* [The Definitive Guide to Yii](http://www.yiiframework.com/doc-2.0/guide-index.html)

If you are confident that there is a bug in the framework, feel free to provide information on how to reproduce it. This issue will be closed for now.

**Comment by schmunk42** [comment]
@Eugentis Check if your assets are deployed correctly (Browser console, look for 404 or js errors).
