### ISSUE TITLE
FileTarget removes trailing "\n" from log entry

### ISSUE THREAD

**Issue by nd4c** [yiisoft/yii2#19947]
### What steps will reproduce the problem?
Save two log entries.
```
Yii::error('Log Entry 1');
Yii::error('Log Entry 2');
```
### What is the expected result?
Note that there is an EOL after the "---" at the end of each log entry separating it from the next log entry:

```
2023-09-02 09:39:06 [127.0.0.1][..user..][error][application] Log Entry 1

$_SERVER = [
    'REQUEST_URI' => '/'
]
---
2023-09-02 09:39:06 [127.0.0.1][..user..][error][application] Log Entry 2

$_SERVER = [
    'REQUEST_URI' => '/'
]
---
EOF

```
### What do you get instead?
Note that there is no EOL after the "---" at the end of each log entry:
```
2023-09-02 09:39:06 [127.0.0.1][..user..][error][application] Log Entry 1

$_SERVER = [
    'REQUEST_URI' => '/'
]
---2023-09-02 09:39:06 [127.0.0.1][..user..][error][application] Log Entry 2

$_SERVER = [
    'REQUEST_URI' => '/'
]
---EOF

```

### Additional info
I believe the problem is in the "export()" method of the FileTraget.php file.
```
public function export()
    {
        $text = implode("\n", array_map([$this, 'formatMessage'], $this->messages)) . "\n";
        $trimmedText = trim($text);

        if (empty($trimmedText)) {
            return; // No messages to export, so we exit the function early
        }
...
        $writeResult = @fwrite($fp, $trimmedText);
...

```

Possible solution:

```
...
        $writeResult = @fwrite($fp, $trimmedText . "\n");
...

```

Another possible solution:

```
public function export()
    {
        $text = implode("\n", array_map([$this, 'formatMessage'], $this->messages));
        $trimmedText = trim($text);

        if (empty($trimmedText)) {
            return; // No messages to export, so we exit the function early
        }

        $trimmedText .= "\n";

```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49
| PHP version      | 8.2.10
| Operating system | Linux Mint 21.2 with Kernel: Linux 6.2.0-31-generic running Apache/2.4.57 (Ubuntu)

**Comment by terabytesoftw** [comment]
use master branch https://github.com/yiisoft/yii2/blob/671fbefe8457568ea1b83750f8a98a60bc62d9cd/framework/log/FileTarget.php#L133
