### ISSUE TITLE
File Log writer without newline

### ISSUE THREAD

**Issue by tafid** [yiisoft/yii2#19940]
[https://github.com/yiisoft/yii2/blob/master/framework/log/FileTarget.php#L110](https://github.com/yiisoft/yii2/blob/master/framework/log/FileTarget.php#L110)

BC File Log writer. `trim` of the message causes a line without newline to be written to the file.

### What steps will reproduce the problem?

Log file

### What is the expected result?
a newline character will be added to the end of the line

### What do you get instead?
The line without newline

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49
| PHP version      | any
| Operating system | any

**Comment by terabytesoftw** [comment]
You can do a PR with the correction.
