### ISSUE TITLE
Query builder: groupBy(null) causing PHP 8.1 trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii2#19950]
### What steps will reproduce the problem?

`(new \yii\db\Query)->groupBy(null)`

### What is the expected result?

GROUP BY is cleared

### What do you get instead?

Error trim(): Passing null to parameter #1 ($string) of type string is deprecated

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49?
| PHP version      |  8.1

**Comment by uaoleg** [comment]
Fixed https://github.com/yiisoft/yii2/pull/19949

**Comment by terabytesoftw** [comment]
Close completed.
