### ISSUE TITLE
log filter \n 

### ISSUE THREAD

**Issue by liujihaozhy** [yiisoft/yii2#19954]
\yii\log\FileTarget::export

$text = implode("\n", array_map([$this, 'formatMessage'], $this->messages)) . "\n";
$trimmedText = trim($text) ;

麻烦修复下：

$text = implode("\n", array_map([$this, 'formatMessage'], $this->messages)) . "\n";
$trimmedText = trim($text) . "\n";

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by terabytesoftw** [comment]
use master branch https://github.com/yiisoft/yii2/blob/671fbefe8457568ea1b83750f8a98a60bc62d9cd/framework/log/FileTarget.php#L133

related https://github.com/yiisoft/yii2/issues/19940

**Comment by liujihaozhy** [comment]
> use master branch
> 
> https://github.com/yiisoft/yii2/blob/671fbefe8457568ea1b83750f8a98a60bc62d9cd/framework/log/FileTarget.php#L133
> 
> related #19940

What I mean is that this code uses trim(), which will cause the \n at the end of each line to be lost. After looking at the master branch, there is still a problem.

**Comment by terabytesoftw** [comment]
Here is the tests: 

https://github.com/yiisoft/yii2/blob/30b491dfdf2cf047ddcbec39c2533d1837699c4e/tests/framework/log/FileTargetTest.php#L115

It generates each line with "\n", if you can add a test where it fails, i will be happy to solve it, 

Only $trimmedText is used for early return.

**Comment by liujihaozhy** [comment]
> Here is the tests:
> 
> https://github.com/yiisoft/yii2/blob/30b491dfdf2cf047ddcbec39c2533d1837699c4e/tests/framework/log/FileTargetTest.php#L115
> 
> It generates each line with `"\n"`, if you can add a test where it fails, i will be happy to solve it,
> 
> Only `$trimmedText` is used for early return.
> 
> https://github.com/yiisoft/yii2/blob/30b491dfdf2cf047ddcbec39c2533d1837699c4e/framework/log/FileTarget.php#L112

thank you

**Comment by liujihaozhy** [comment]
Our development team rewrote this method in
if (empty($trimmedText)) {
     return; // No messages to export, so we exit the function early
}
A new line of code was added at the end:
$trimmedText = trim($text) . "\n";

**Comment by liujihaozhy** [comment]
> Our development team rewrote this method in if (empty($trimmedText)) { return; // No messages to export, so we exit the function early } A new line of code was added at the end: $trimmedText = trim($text) . "\n";

If you do not add the following code:
$trimmedText = trim($text) . "\n";
Will cause all logs to be written on one line:

**Comment by terabytesoftw** [comment]
If you check the code in the master branch you will see that $trimmedText is only used in the early return, for the rest $text is used which has "\n".

```
    public function export()
    {
        $text = implode("\n", array_map([$this, 'formatMessage'], $this->messages)) . "\n";
        $trimmedText = trim($text);

        if (empty($trimmedText)) {
            return; // No messages to export, so we exit the function early
        }

        if (strpos($this->logFile, '://') === false || strncmp($this->logFile, 'file://', 7) === 0) {
            $logPath = dirname($this->logFile);
            FileHelper::createDirectory($logPath, $this->dirMode, true);
        }

        if (($fp = @fopen($this->logFile, 'a')) === false) {
            throw new InvalidConfigException("Unable to append to log file: {$this->logFile}");
        }
        @flock($fp, LOCK_EX);
        if ($this->enableRotation) {
            // clear stat cache to ensure getting the real current file size and not a cached one
            // this may result in rotating twice when cached file size is used on subsequent calls
            clearstatcache();
        }
        if ($this->enableRotation && @filesize($this->logFile) > $this->maxFileSize * 1024) {
            $this->rotateFiles();
        }
        $writeResult = @fwrite($fp, $text);
        if ($writeResult === false) {
            $error = error_get_last();
            throw new LogRuntimeException("Unable to export log through file ({$this->logFile})!: {$error['message']}");
        }
        $textSize = strlen($text);
        if ($writeResult < $textSize) {
            throw new LogRuntimeException("Unable to export whole log through file ({$this->logFile})! Wrote $writeResult out of $textSize bytes.");
        }
        @fflush($fp);
        @flock($fp, LOCK_UN);
        @fclose($fp);

        if ($this->fileMode !== null) {
            @chmod($this->logFile, $this->fileMode);
        }
    }
```

**Comment by liujihaozhy** [comment]
> If you check the code in the master branch you will see that `$trimmedText` is only used in the early return, for the rest `$text` is used which has "\n".
> 
> ```
>     public function export()
>     {
>         $text = implode("\n", array_map([$this, 'formatMessage'], $this->messages)) . "\n";
>         $trimmedText = trim($text);
> 
>         if (empty($trimmedText)) {
>             return; // No messages to export, so we exit the function early
>         }
> 
>         if (strpos($this->logFile, '://') === false || strncmp($this->logFile, 'file://', 7) === 0) {
>             $logPath = dirname($this->logFile);
>             FileHelper::createDirectory($logPath, $this->dirMode, true);
>         }
> 
>         if (($fp = @fopen($this->logFile, 'a')) === false) {
>             throw new InvalidConfigException("Unable to append to log file: {$this->logFile}");
>         }
>         @flock($fp, LOCK_EX);
>         if ($this->enableRotation) {
>             // clear stat cache to ensure getting the real current file size and not a cached one
>             // this may result in rotating twice when cached file size is used on subsequent calls
>             clearstatcache();
>         }
>         if ($this->enableRotation && @filesize($this->logFile) > $this->maxFileSize * 1024) {
>             $this->rotateFiles();
>         }
>         $writeResult = @fwrite($fp, $text);
>         if ($writeResult === false) {
>             $error = error_get_last();
>             throw new LogRuntimeException("Unable to export log through file ({$this->logFile})!: {$error['message']}");
>         }
>         $textSize = strlen($text);
>         if ($writeResult < $textSize) {
>             throw new LogRuntimeException("Unable to export whole log through file ({$this->logFile})! Wrote $writeResult out of $textSize bytes.");
>         }
>         @fflush($fp);
>         @flock($fp, LOCK_UN);
>         @fclose($fp);
> 
>         if ($this->fileMode !== null) {
>             @chmod($this->logFile, $this->fileMode);
>         }
>     }
> ```

Oh, I see
