### ISSUE TITLE
Implement Yii3 Caching System as base for Yii 2.2 cache

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii2#19979]
An Experiment (Yet) to replace underlying Yii2 cache to use Yii3 libraries, as part of grand experiment for Yii2/3 bridge aka Yii 2.2
I will be updating progress below with each step.

All help and ideas are welcome

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.2
| PHP version      |  8.0+
| Operating system | N/A

**Comment by mtangoo** [comment]
Replace ArrayCache with Yii3 cache library as a base
https://github.com/yiisoft/yii2/pull/19980

**Comment by xicond** [comment]
@bizley @mtangoo can close ?

**Comment by mtangoo** [comment]
Yeah sure. I forgot to close this one.
Closed. Thanks!
