### ISSUE TITLE
MaskedInput Widget javascript update request

### ISSUE THREAD

**Issue by ldkafka** [yiisoft/yii2#19988]
Please update the MaskedInput Widget javascript version - the bundled one is version Version: 3.3.11 from 2017. Current one is 5.0.8 from 2023.

I am not sure if there are any breaking changes, but a lot of bugs have been fixed - including datetime extension formatting (which is how I figured out the bundled version is too old).

Also, the alias configuration is very ambiguous - the Widget uses the $aliases array to supposedly register aliases, but that in fact is never used - aliases have to be configured in the clientOptions directly.

Thank you!

**Comment by bizley** [comment]
Hi, is there a chance you could prepare a PR fixing this?

**Comment by stovesy** [comment]
After this update I'm getting ...
Uncaught SyntaxError: expected expression, got '<'[jquery.inputmask.bundle.js:1:3](https:/xxxxxx/xxxxx/xxxx/jquery.inputmask.bundle.js)
Uncaught TypeError: jQuery(...).inputmask is not a function

**Comment by ldkafka** [comment]
That is because jquery doesn't load fast enough... I'm seeing this quite a
bit from CDNs lately. The other code should be wrapped in onLoad so it only
runs when jquery is ready.

**Comment by stovesy** [comment]
class MaskedInputAsset extends AssetBundle
{
public $sourcePath = '@bower/inputmask/dist';
public $js = [
'jquery.inputmask.js',
];
public $depends = [
'yii\web\YiiAsset',
];
}

Fixes it for me, but I've no experience with this sort of thing.

**Comment by terabytesoftw** [comment]
@rob006 In the new version, change the name of the asset to:

`'jquery.inputmask.bundle.js'` to `'jquery.inputmask.js'`

What is the best way to solve it, checking if the file exists, or deleting the old constraint, and leaving the older version.

**Comment by rob006** [comment]
I don't know. IMO it shouldn't be part of the framework in the first place, so maybe extract this to separate package (which could have multiple versions targeting specific major version of inputmask plugin) and add it to `require` section of framework?
