### ISSUE TITLE
Logger from Yii::info sometimes writes without line breake

### ISSUE THREAD

**Issue by elmys** [yiisoft/yii2#19983]
### What steps will reproduce the problem?
Just use: 
`Yii::info('NEED_FOR_UPDATE_ON_MSC', LOG_SIMPLE_LOG);`
`Yii::$app->cache->set(NEED_FOR_UPDATE_ON_MSC . $contract->id, 1);`
`$contract->save()`
`Yii::info('$contract->save status | ' . Json::encode($contract->status), LOG_SIMPLE_LOG);`

### What is the expected result?
2023-09-28 14:20:52 [158.160.10.5][-][-][info][simple] $contract->save
    in /var/www/project/modules/api/modules/v2/controllers/ContractController.php:198
2023-09-28 14:24:04 [158.160.10.5][-][-][info][simple] NEED_FOR_UPDATE_ON_MSC
    in /var/www/project/modules/api/modules/v2/controllers/ContractController.php:195

### What do you get instead?
2023-09-28 14:20:52 [158.160.10.5][-][-][info][simple] $contract->save
    in /var/www/project/modules/api/modules/v2/controllers/ContractController.php:1982023-09-28 14:24:04 [158.160.10.5][-][-][info][simple] NEED_FOR_UPDATE_ON_MSC
    in /var/www/project/modules/api/modules/v2/controllers/ContractController.php:195

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49
| PHP version      | 7.4
| Operating system | Ubuntu 22

**Comment by terabytesoftw** [comment]
related https://github.com/yiisoft/yii2/issues/19940
