### ISSUE TITLE
yii\validators\DateValidator - Issue with parseDateValuePHP method on PHP 8.2

### ISSUE THREAD

**Issue by de-salvatierra** [yiisoft/yii2#19993]
Affected Version: Yii2 2.0.47
**Issue Summary:**
In the `yii\validators\DateValidator` class, the `parseDateValuePHP` method uses DateTime::getLastErrors() to check for errors when parsing a date. However, starting from PHP version 8.2, `DateTime::getLastErrors()` returns `false` when there are no errors, whereas in earlier PHP versions, it always returns an array.

**Steps to Reproduce:**

1. Use PHP 8.2.
2. Create a `yii\validators\DateValidator` instance.
3. Attempt to validate a date using the validator.

**Expected Result:**
The validation should work as expected with PHP 8.2.

**Actual Result:**
The validation may fail due to incorrect error handling in the `parseDateValuePHP` method.

**Proposed Solution:**
Modify the code in the `parseDateValuePHP` method to handle the change in behavior of `DateTime::getLastErrors()` in PHP 8.2. Specifically, check if `DateTime::getLastErrors()` returns false to indicate no errors on PHP 8.2 and adjust the logic accordingly.

```
$errors = DateTime::getLastErrors();
if (
    $date === false
        ||
    ($errors !== false && ($errors['error_count'] || $errors['warning_count']))
        ||
    ($this->strictDateFormat && $date->format($format) !== $value)
) {
    return false;
}
```

**Additional Information:**
PHP 8.2 introduced changes to `DateTime::getLastErrors()` behavior: https://www.php.net/manual/en/datetime.getlasterrors.php

This issue should address the compatibility issue with PHP 8.2 in the `yii\validators\DateValidator` class.

**Comment by bizley** [comment]
It should be already fixed, please check the latest version.
