### ISSUE TITLE
2.0.49.1 has wrong version set in BaseYii

### ISSUE THREAD

**Issue by particleflux** [yiisoft/yii2#19999]
No idea why or how, but with 2.0.49.1 installed, the debug toolbar renders `2.0.50-dev`, and the `BaseYii` class has the same

### What steps will reproduce the problem?

Install 2.0.49.1

```
composer require yiisoft/yii2:=2.0.49.1
```

Observe `\yii\BaseYii::getVersion()` or the version shown in the debug toolbar, which is set to `'2.0.50-dev'`.

### What is the expected result?

Version is set to the version actually installed, in this case `2.0.49.1`.

### What do you get instead?

Version `2.0.50-dev`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.1
| PHP version      | 8.2
| Operating system | Linux

```
$ composer info yiisoft/yii2 | head -4
name     : yiisoft/yii2
descrip. : Yii PHP Framework Version 2
keywords : framework, yii2
versions : * 2.0.49.1
```

```
$ grep getVersion -A3 vendor/yiisoft/yii2/BaseYii.php 
    public static function getVersion()
    {
        return '2.0.50-dev';
    }
```

**Comment by bizley** [comment]
Hm, yes, I wasn't aware this needs to be updated manually apparently. We'll release new 2.0.49.2 with corrections.

**Comment by cebe** [comment]
@bizley it's been a long time since I did that so things might have changed. There is/was a release command that should do the version change for you:

https://github.com/yiisoft/yii2/blob/bd296ebe04c17b0c27973fbd8431b2ff60568a8b/build/controllers/ReleaseController.php#L990-L996

**Comment by bizley** [comment]
Yes, it looks like tags/commits were not properly updated on my machine hence the problem. I'll release 2.0.49.2 today.
