### ISSUE TITLE
New-Line bug with FileTarget log

### ISSUE THREAD

**Issue by dtatarnikov** [yiisoft/yii2#19991]
https://github.com/yiisoft/yii2/blob/2.0.49/framework/log/FileTarget.php#L109-L110

Problem with this part of code. You add  new line at the end of `$text` variable, but then trim this character. And later flush `$trimmedText` without new line.
 It very clear to see with `Logger::flushInterval=1` .

Suggested fix is

```php
$text = implode("\n", array_map([$this, 'formatMessage'], $this->messages));
$trimmedText = trim($text);

if (empty($trimmedText)) {
    return; // No messages to export, so we exit the function early
}

$trimmedText .=  "\n";
```

### What steps will reproduce the problem?
Use FileTarget for logging.

### What is the expected result?
All log messages should be on new line.

### What do you get instead?
The last flushed message in batch will have no new line.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49
| PHP version      | N/A
| Operating system | N/A

**Comment by rob006** [comment]
It is already fixed in https://github.com/yiisoft/yii2/pull/19941

@bizley Can we release this fix? It is quite significant regression, fixed over a month ago, and still without a release. Maybe as 2.0.49.1?

**Comment by bizley** [comment]
Yes, will do today.

**Comment by terabytesoftw** [comment]
done.
