### ISSUE TITLE
Outdated IRC link/metadata on packagist.com

### ISSUE THREAD

**Issue by particleflux** [yiisoft/yii2#19998]
The IRC on [packagist](https://packagist.org/packages/yiisoft/yii2) still links to freenode

Since [2.0.49.1](https://github.com/yiisoft/yii2/blob/2.0.49.1/composer.json#L62) seems to have the correct data in composer.json, maybe someone just needs to trigger a refresh of the metadata on packagist?

**Comment by bizley** [comment]
It should be updated automatically. Does someone know how to trigger it?

**Comment by samdark** [comment]
Interesting. I've triggered the update but it's still freenode :(

**Comment by samdark** [comment]
Sent a mail to packagist team about it.

**Comment by particleflux** [comment]
Seems fixed
