### ISSUE TITLE
Inputmask net::ERR_ABORTED 404 (Not Found) in 2.0.49.2

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#20013]
After update to 2.0.49.2 i see this bug
http://localhost/assets/f393ce73/min/jquery.inputmask.bundle.min.js net::ERR_ABORTED 404 (Not Found)

### What steps will reproduce the problem?
Download last version 2.0.49.2

Use maskedinput out of box
![image](https://github.com/yiisoft/yii2/assets/1358236/7066d1ed-a2d5-42b5-80af-c4e005ee4086)
![image](https://github.com/yiisoft/yii2/assets/1358236/53c069c0-faa3-4cbc-b110-eb01a58eabe9)

### What is the expected result?

All ok widget is worked out of box

### What do you get instead?

```
http://localhost/assets/f393ce73/min/jquery.inputmask.bundle.min.js net::ERR_ABORTED 404 (Not Found)
```

### Additional info
in ~3.3.5
![image](https://github.com/yiisoft/yii2/assets/1358236/08719e44-de65-4d55-aac1-1174c2e42be1)

In ~5.0.8
![image](https://github.com/yiisoft/yii2/assets/1358236/43d0e23d-7a76-46c7-af1b-f601034ace7b)

It need to fix Inputmask
vendor/yiisoft/yii2/widgets/MaskedInputAsset.php
![image](https://github.com/yiisoft/yii2/assets/1358236/4c242546-aad9-4a1d-b9c2-a9d1e47a889c)

Now I fix it by downgrade lib in composer.json in my project
![image](https://github.com/yiisoft/yii2/assets/1358236/40f2ec78-36c6-4429-b7c9-3a8452a44e38)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.2
| PHP version      | 8.2
| Operating system | Docker

**Comment by terabytesoftw** [comment]
related #19986, #19988.

use `dev/master` branch, while the next release is being prepared.

**Comment by bizley** [comment]
2.0.49.3 was released.
