### ISSUE TITLE
Method instantiate() in BaseActiveRecord does not reflect injected behaviors

### ISSUE THREAD

**Issue by rackycz** [yiisoft/yii2#20010]
Hello.
When I inject a behavior to "MyModel" via the container in web.php, I need to instantiate such a model using Yii::createObject() in order to apply the injection. If I call new MyModel() or new static(), injected stuff is ignored. And exactly this is happening in method instantiate() in BaseActiveRecord.

If I then access MyModel via a relation $someOtherModel->relationToMyModel, Yii calls method instantiate() so my behavior is not available in MyModel.

Solution was to override method instantiate() like this:

```
public static function instantiate($row)
{
    return Yii::createObject(static::class);
}
```
Could this situation be handled directly in Yii? I believe the framework should always use Yii::createObject(). If this is due to some performance issues, we could have a way to force usage of Yii::createObject() if needed.

Thanks you for reading and considering!

**Comment by rob006** [comment]
See https://github.com/yiisoft/yii2/issues/16306

**Comment by rackycz** [comment]
Thanks for the hing. In that case let's only use the last sentence from by ticket:

> If this is due to some performance issues, we could have a way to force usage of Yii::createObject() if needed.

Would it be possible to add a parameter somewhere, for example to method find($enableDi=false) in ActiveRecord or to ActiveQuery? It would solve the situation without debugging the code and discovering the reason.
