### ISSUE TITLE
BUG: In the translation files, some lines are `LF` and some are `CRLF`

### ISSUE THREAD

**Issue by NabiKAZ** [yiisoft/yii2#20023]
When run this command:
`yii message/extract messages/config.php`
Translation files created in `Windows` look something like this:

![notepad++_6WKwJb1RiG](https://github.com/yiisoft/yii2/assets/246721/1bfd3d19-6cb3-4c51-8da4-d25dc3b5d8de)

As you can see, the end of some lines is `LF` and some is `CRLF`.
(It is not a problem in `Linux` because it is `\n` by default and the same is used in the code)

This problem causes us to get a warning when committing, even if the file has not changed, and this is committed to the repository.

![notepad++_yLgiG96inR](https://github.com/yiisoft/yii2/assets/246721/5899ccd1-0a7a-4042-a27f-eeae0f03656e)

I tracked down the source of the problem. One of the two must be done:
1. In the `MessageController.php` file, wherever heredoc syntax is used, Replace `PHP_EOL` with `\n`.
2. In the `BaseVarDumper.php` file, all `\n` should be changed to `PHP_EOL`.

My suggestion is the second option.
If you announce your opinion and policy. I can work on this and do it.

**Comment by xicond** [comment]
I thought MessageController.php already use \n
possible you use git autocrlf true
if change to PHP_EOL, programmer that has different platform will cause trouble at the end

**Comment by bizley** [comment]
Yes, please verify what @xicond said, we are not using PHP_EOL here.

**Comment by NabiKAZ** [comment]
I first wrote this code and added it to `BaseStringHelper.php`:

```PHP
    /**
     * When using Heredoc Syntax, the end of line is PHP_EOL and it is operating system dependent,
     * so it needs to be converted to a single character.
     *
     * @param string $value the value to normalize.
     * @return string
     * @since 2.0.50
     */
    public static function normalizeHeredoc($value)
    {
        return str_replace(PHP_EOL, "\n", (string) $value);
    }
```

But then I saw this link:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows

It seems that a step up from `git config --global core.autocrlf true` is adding `eol=lf` to the `.gitattributes` file.
With this, the initiative is in git's hands, and regardless of what is in the repository or the developer's system settings; It ensures that the same setting is used on all developers' systems.
Doing so seems necessary.

I think this should be done first to check again whether the above function is needed or not.

**Comment by NabiKAZ** [comment]
It seems that the main problem was solved. I got a new clone on Windows and I didn't get that old warning anymore and all the files were `LF`.
But there is another problem that txt files that have an extension other than the one defined in the `.gitattributes` file are not affected. Like nameless files with `.` they start, or `.dist` and `.lock` and...
So I defaulted to it:
```
# Auto detect text files
* text=auto eol=lf
```
Please check.
