### ISSUE TITLE
BUG: CSRF Cookie Generated

### ISSUE THREAD

**Issue by aizuddinfakhri** [yiisoft/yii2#20027]
The CSRF Cookie that is Generated and Stored are Unmasked Token, instead of Masked Token.

Yii2 Request Class validateCsrfToken() function does an Unmasked function on the token and compares.

Since the CSRF Cookie is already stored as Unmasked, it runs the unmasked function again on the value of the CSRF Cookie when the validateCsrfToken is executed, resulting in the value to be corrupted and not the same. Hence submission cannot be verified.

Below is what i've updated in Request.php for a quick fix:

public function getCsrfToken($regenerate = false)
{
    if ($this->_csrfToken === null || $regenerate) {
        $token = $this->loadCsrfToken();
        if ($regenerate || empty($token)) {
            $token = $this->generateCsrfToken();
        }
        //$this->_csrfToken = Yii::$app->security->maskToken($token);
        $this->_csrfToken = $token;
    }

    return $this->_csrfToken;
}

protected function generateCsrfToken()
{
    //$token = Yii::$app->getSecurity()->generateRandomString();
    $token = Yii::$app->security->maskToken(Yii::$app->getSecurity()->generateRandomString());
    if ($this->enableCsrfCookie) {
        $cookie = $this->createCsrfCookie($token);
        Yii::$app->getResponse()->getCookies()->add($cookie);
    } else {
        Yii::$app->getSession()->set($this->csrfParam, $token);
    }

    return $token;
}

### What steps will reproduce the problem?

Validating CSRF Cookie.

1. Retrieve the CSRF Cookie Value 
2. Run the Value Check with Request::validateCsrfToken()

### What is the expected result?

Expected Result to Return As Verified Submission

### What do you get instead?

Result Returned as Not Verified Submission

### Additional info

| Yii version      | 2.0.49
| PHP version: 8.x | 
| Operating system: Linux |

**Comment by bizley** [comment]
This is weird, I don't remember changes done there recently and we did not hear about problems with that functionality. Could you provide a quick way to reproduce your issue on a clean application?

**Comment by samdark** [comment]
Closing because of no response.
