### ISSUE TITLE
 Increased response time when increasing the value in ErrorHandler::memoryReserveSize

### ISSUE THREAD

**Issue by antonshevelev** [yiisoft/yii2#20030]
### What steps will reproduce the problem?
Set ErrorHandler to high ErrorHandler::memoryReserveSize.

### What is the expected result?
Response time does not change.
  

### What do you get instead?
Increased response time.

### Additional info
yii\base\ErrorHandler::register
```
if ($this->memoryReserveSize > 0) {
	$this->_memoryReserve = str_repeat('x', $this->memoryReserveSize); //was in 2.0.45

	//at high values ​​MemoryReserveSize is slower than via str_repeat
	//Eg. MemoryReserveSize = 100000000 (100 MB), just for visible result
	$this->_memoryReserve = str_pad('', $this->memoryReserveSize, 'x'); //became starting from 2.0.46
}
```
upgrade from 2.0.45 to 2.0.48
10 MB reserved. memoryReserveSize =  10000000. 
![image](https://github.com/yiisoft/yii2/assets/10631259/b46f4884-969a-4b71-b40d-109e79075f56)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.48
| PHP version      |  8.1.17
| Operating system |

**Comment by samdark** [comment]
Any idea why?

**Comment by rob006** [comment]
It was introduced by https://github.com/yiisoft/yii2/pull/19402, and using `str_pad()` was supposed to be faster. But I just tested this and it is 10-20 times slower than `str_repeat()`.
