### ISSUE TITLE
MaskedInputAsset picking wrong name after update

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii2#20041]
### What steps will reproduce the problem?
1. Set composer to `"yiisoft/yii2": "^2.0.49"`
2. Run Composer update
3. use any widget that uses masked input like https://github.com/kartik-v/yii2-number/

### What is the expected result?
Widget should work correctly

### What do you get instead?
`GET <URL>/assets/9a3e2b0/jquery.inputmask.bundle.js net::ERR_ABORTED 404 (Not Found)`

### Additional info
It seems somehow masked input  version was changed and bower no longer installs `jquery.inputmask.bundle.js` but rather `jquery.inputmask.min.js`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by mtangoo** [comment]
The problem is rather fixed in master but the current stable version is unusable for projects that depends on maskedInput widget. I cannot find yet the commit that introduced such change but we can find a way to fix only this issue and release new version to make it usable again

**Comment by mtangoo** [comment]
`2.0.49.1` works fine, so the change seems to be introduced in `2.0.49.2`

**Comment by terabytesoftw** [comment]
It's fixed in the master, the change was here.

https://github.com/yiisoft/yii2/pull/20009

**Comment by bizley** [comment]
https://github.com/yiisoft/yii2/issues/20013 
@terabytesoftw Should we release 2.0.49.3 with all currently made changes to fix this?

**Comment by terabytesoftw** [comment]
yes

**Comment by rob006** [comment]
I would rather revert https://github.com/yiisoft/yii2/commit/20a4b7eff9a4046a5c25bc206a8f085f2cab951c for 2.0.49.3. If `2.0.49.x` is supposed to be LTS, then I would avoid such change in this line and keep it only in 2.0.50 (which will also increase required PHP version).

**Comment by terabytesoftw** [comment]
> I would rather revert [20a4b7e](https://github.com/yiisoft/yii2/commit/20a4b7eff9a4046a5c25bc206a8f085f2cab951c) for 2.0.49.3. If `2.0.49.x` is supposed to be LTS, then I would avoid such change in this line and keep it only in 2.0.50 (which will also increase required PHP version).

good idea.

**Comment by mtangoo** [comment]
I agree with @rob006 
No need to introduce any change for just js library

**Comment by bizley** [comment]
I've discussed some options to release 2.0.49.3 with only this revert, but we don't have a safe solution for it. What do you think about releasing all the things we have merged so far as 2.0.49.3?

**Comment by rob006** [comment]
I think it is too much for a patch release. What do you mean by "we don't have a safe solution for it"?

**Comment by mtangoo** [comment]
>but we don't have a safe solution for it
What about creating a tag to a commit same commit as 2.0.49.1 and just change version?
That will reverse the issue as minor release as well as allow the release of current change to major version

**Comment by bizley** [comment]
Let's move to the [discussion](https://github.com/yiisoft/yii2/discussions/20053), I explained more there.

**Comment by bizley** [comment]
2.0.49.3 was released.
