### ISSUE TITLE
Bug: X-Pagination-Total-Count is always 0

### ISSUE THREAD

**Issue by Psyopus** [yiisoft/yii2#20055]
Hi, 

After this commit #https://github.com/yiisoft/yii2/commit/3014fa22e55dee30099475506370f87cec404eb2 X-Pagination-Total-Count header is always 0. So it breaks pagination. I believe it happens because pagination headers are set before real totalCount calculated.

```
if (($pagination = $dataProvider->getPagination()) !== false) {
       $this->addPaginationHeaders($pagination);
}
```

### What steps will reproduce the problem?

Any /index GET queries returns X-Pagination-Total-Count=0

### What is the expected result?

Total Count of models

### What do you get instead?

0

**Comment by microinginer** [comment]
some problem

**Comment by schmunk42** [comment]
Should be covered by a new test also.

**Comment by rideau-nostalgia** [comment]
Looks like it was caused by this commit:
https://github.com/yiisoft/yii2/commit/3014fa22e55dee30099475506370f87cec404eb2

Pagination headers are now set before prepareModels() is called, which is the trigger to calculate the total count
