### ISSUE TITLE
Yii::$app->request->post() empty result

### ISSUE THREAD

**Issue by adyoi** [yiisoft/yii2#20069]
### What steps will reproduce the problem?
```
 public function actionTest() {

        $get = Yii::$app->request->get();
        $post = Yii::$app->request->post();

        $result = ['get' => $get, 'post' => $post];

        return $result;
    }
```
### What is the expected result?
get post from form-data

### What do you get instead?
empty result Yii::$app->request->post();

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.49
| PHP version      | 8.2.9
| Operating system | Almalinux 8

**Comment by adyoi** [comment]
![untitled](https://github.com/yiisoft/yii2/assets/6408640/5268167c-431b-4215-a162-d3a15bcdbf9b)

**Comment by adyoi** [comment]
File Controller :
```
namespace backend\controllers;
class ApiController extends ActiveController {}

**Comment by schmunk42** [comment]
Have you tried another variable key than `test`, which is the same in GET and POST?

**Comment by adyoi** [comment]
same result

![2](https://github.com/yiisoft/yii2/assets/6408640/ff870d07-922c-4b09-addb-74d25ebc8bcf)

**Comment by adyoi** [comment]
same result
![2 (1)](https://github.com/yiisoft/yii2/assets/6408640/5448e935-6e3e-43e9-aa1d-5309997eecdc)

**Comment by schmunk42** [comment]
I'd recommend to debug this with Yii's debug panel, to see what is received on the server side.

**Comment by My6UoT9** [comment]
Most likely there is redirect happening, so u keep the get, but loose the post data.

**Comment by adyoi** [comment]
this issue when the server force HTTPS, thanks for advise @My6UoT9

**Comment by xicond** [comment]
you might have redirection from POST to https GET, that's why client only bring GET queryString, as Postman also follow redirection
