### ISSUE TITLE
Can't upgrade to PHP 8.3 - ezyang/htmlpurifier

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2#20080]
### What steps will reproduce the problem?

Try to update your project to PHP 8.3

### What is the expected result?

I'm able to upgrade

### What do you get instead?

```
  Problem 1
    - ezyang/htmlpurifier v4.16.0 requires php ~5.6.0 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (8.3.0) does not satisfy that requirement.
    - yiisoft/yii2 2.0.49.3 requires ezyang/htmlpurifier ^4.6 -> satisfiable by ezyang/htmlpurifier[v4.16.0].
    - yiisoft/yii2 is locked to version 2.0.49.3 and an update of this package was not requested.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.3
| PHP version      |  8.3
| Operating system | macOs

**Comment by schmunk42** [comment]
A temporary fix would be using  `ezyang/htmlpurifier: dev-master as 4.99`

**Comment by machour** [comment]
Issue solved, was caused by phpoffice/phpspreadsheet, thank you @schmunk42 !
