### ISSUE TITLE
add attribute on generated <script> tag

### ISSUE THREAD

**Issue by shinedira** [yiisoft/yii2#20087]
### What steps will reproduce the problem?
```php
<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

    <?= $form->field($model, 'date_posted')->widget(DatePicker::classname()) ?>

    <div class="form-group">
        <?= Html::submitButton('Save') ?>
    </div>

<?php ActiveForm::end(); ?>
```

and it generated <script> tag for initiation of the widget component
### What is the expected result?
but what I want is to add an attribute on the generated <script> tag,
for example <script attribute="here-the-new-attribute">

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.37
| PHP version      |  7.3.20
| Operating system | Windows 11

**Comment by samdark** [comment]
What's your use-case?

**Comment by shinedira** [comment]
need an attribute to tag script for content security policy (csp)
`<script nonce="key">`

> What's your use-case?

**Comment by skepticspriggan** [comment]
I have the same problem while integrating CSP. I am working on a pull request to address this.
