### ISSUE TITLE
Missing BaseActiveRecord methods mentioned in documentation

### ISSUE THREAD

**Issue by astwinioenergy** [yiisoft/yii2#20086]
Documentation 
https://www.yiiframework.com/doc/api/2.0/yii-db-baseactiverecord#loadRelations()-detail
says about
```
/yii/db/BaseActiveRecord::loadRelations() //(since 2.0.49)
/yii/db/BaseActiveRecord::loadRelationsFor() //(since 2.0.49)
```
methods, none of which exists in source code after installing via

`composer require yiisoft/yii2`
or
`composer require --prefer-source yiisoft/yii2`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49

**Comment by samdark** [comment]
Version there is specified incorrectly. Should be 2.0.50.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/dffb4c7529fba471a063260ae3149a02d14b7bd4

Thanks for reporting.
