### ISSUE TITLE
SQS issue with new AWS sdk

### ISSUE THREAD

**Issue by mahran419** [yiisoft/yii2#20082]
### What steps will reproduce the problem?
after upgrading AWS SDK the SQS Queue TTR will received only as a string and the SQS driver in yii is sent as an integer.

### What is the expected result?
Error: The provided type for `MessageAttributes -> TTR -> StringValue` value was `integer`. The modeled type is `string`.

### Additional info
must be casting the TTR value as a string to prevent the exception in **pushMessage** function in yiisoft/yii2-queue/src/drivers/sqs/Queue.php or override the class and make your changed 

`$request = [
            'QueueUrl' => $this->url,
            'MessageBody' => $message,
            'DelaySeconds' => $delay,
            'MessageAttributes' => [
                'TTR' => [
                    'DataType' => 'Number',
                    'StringValue' => (string)$ttr,
                ],
            ],
        ];`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49
| PHP version      | 8.1
| Operating system |ubuntu 
| AWS SDK | 3.293.8

**Comment by rhertogh** [comment]
@mahran419 This seems to be an issue with the [yii2-queue](https://github.com/yiisoft/yii2-queue) package and I think it's the same issue fixed here: https://github.com/yiisoft/yii2-queue/pull/502
Could you please try with the "dev-master" version (`"yiisoft/yii2-queue": "dev-master"` in your `composer.json` file).

**Comment by mahran419** [comment]
@rhertogh Yes the same issue was fixed on version ("yiisoft/yii2-queue": "dev-master"
thank you @rhertogh
