### ISSUE TITLE
ActiveReccord save, attributes issue

### ISSUE THREAD

**Issue by mishagodovanuk** [yiisoft/yii2#20085]
Hello, im tried to save Active reccord model as a new one, with data from post request, but everytime i saw that all data is empty.

After some investigation i find that in `vendor/yiisoft/yii2/db/BaseActiveRecord::getDirtyAttributes()  line 643` in uses array_flip and my original post data was flipped. (I just comment it and it's works)

**My question is:   Is that correct behaviour, or i made something wrong.**

![image](https://github.com/yiisoft/yii2/assets/22371590/00d43933-36ec-435d-afa0-3188e4fdae7d)
![image](https://github.com/yiisoft/yii2/assets/22371590/e99a579a-8fd6-427a-90b0-9c88cf66b2ee)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.3?
| PHP version      | 7.4
| Operating system | ubuntu 20.04

**Comment by samdark** [comment]
What was the input in POST? Would you please provide code for your model and controller?

**Comment by mishagodovanuk** [comment]
@samdark Hello, there is my data

`<?php

namespace app\models\user;

use yii\db\ActiveRecord;

class User extends ActiveRecord implements \yii\web\IdentityInterface
{
/*    public $id;
    public $username;
    public $password;
    public $image;
    public $email;
    public $userType;
    public $updatedAt;
    public $authType;
    public $createdAt;
*/

    public static function tableName()
    {
        return 'users';
    }

    public function rules()
    {
        return [
            [['username', 'email', 'password'], 'required'],
            ['email', 'email'],
            ['email', 'unique'],
            [['username', 'email', 'password'], 'string', 'max' => 100],
            ['created_at', 'default', 'value' => date('Y-m-d H:i:s')],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'Id',
            'username' => 'User name',
            'password' => 'Password',
            'email' => 'User email',
            'userType' => 'User type',
            'authType' => 'authType',
            'image' => 'User image',
            'created_at' => 'Created at',
            'updated_at' => 'Updated at'
        ];
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($auth_key)
    {
        return $this->auth_key === $auth_key;
    }
}
`

![image](https://github.com/yiisoft/yii2/assets/22371590/1afc0d67-e26b-4f11-9735-c1efe27ae773)

![image](https://github.com/yiisoft/yii2/assets/22371590/344cf0e7-1538-4da2-9379-5ac47468f46e)
![image](https://github.com/yiisoft/yii2/assets/22371590/085ac425-d57c-4eee-aa4d-dd8db6b0237b)

**Comment by mishagodovanuk** [comment]
@samdark Hi, sorry for delay everything work perfectly i just figure out. Thank you for reply
