### ISSUE TITLE
Broken asArray when creating new models

### ISSUE THREAD

**Issue by kirya-dev** [yiisoft/yii2#20104]
### What steps will reproduce the problem?
Post table:
```sql
create table post (content text, created_at set default NOW());
```

Example:
```php
$post = new Post(['content' => 'lorem ipsum']);
var_dump($post->asArray());
```

### What is the expected result?
```
array(2) {
  ["content"]=>
  "lorem ipsum"
  ["created_at"]=>
  null
}
```

### What do you get instead?
```
array(1) {
  ["content"]=>
  "lorem ipsum"
}
```

### PS. I know sollution
```php
$post->refresh();
```
But i expect empty field 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49
| PHP version      |  7.4
| Operating system | Ubuntu

**Comment by Webkadabra** [comment]
I'd close the issue as author seems to have misconceptions about technologies being used
