### ISSUE TITLE
Setting YII_DEBUG=false in humhub 1.15.2 leads to internal server error

### ISSUE THREAD

**Issue by ukaeufe** [yiisoft/yii2#20112]
### What steps will reproduce the problem?

Setting YII_DEBUG=false in index.php in humhub root directory quickly leads to internal server error.

### What is the expected result?

Humhub should operate normal and in production mode.

### What do you get instead?

Internal server error, which is resolved immediately when setting YII_DEBUG back to true.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | Yii v2.0.50-dev
| PHP version      |  8.2
| Operating system | Linux ae93c 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
| Env | Netcup webhosting / plesk

**Comment by ArchBlood** [comment]
Full context;
https://github.com/humhub/humhub/issues/6846

**Comment by samdark** [comment]
I don't think there's anything to fix in the framework itself regarding the error encountered.
