### ISSUE TITLE
How should I use Yii2 version 2.0.42.1 in my project

### ISSUE THREAD

**Issue by Pet36** [yiisoft/yii2#20155]
How should I use Yii2 version 2.0.42.1 in my project
I need help. I just started Yii2 development. I need to use the specified version of Yii2 (2.0.42.1) to build my project, but I don’t know how to get the specified version of Yii2. So what should I do?

**Comment by samdark** [comment]
Specify exactly that version in your `composer.json` and do `composer update`.

**Comment by Pet36** [comment]
I can't use composer to get 2.0.42.1. Can you teach me how to achieve it in detail?

**Comment by schmunk42** [comment]
You can download the source from here: https://github.com/yiisoft/yii2/releases/tag/2.0.42.1

or

`git checkout 2.0.42.1`
