### ISSUE TITLE
Wrong `columnQuoteCharacter` default in Schema for sqlite3

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#20150]
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.50
| PHP version      | 8.2.18
| Operating system | linux

The default quote char for columns in [sqlite3 is double quote](https://www.sqlite.org/lang_keywords.html).

From the docs:
    "keyword"		A keyword in double-quotes is an identifier.
    `keyword`		A keyword enclosed in grave accents (ASCII code 96) is an identifier. This is not standard SQL. This quoting mechanism is used by MySQL and is included in SQLite for compatibility.

Should it be changed?

In my extension yii2-sqlite3-full-support I have changed it to the correct value.

**Comment by Tigrov** [comment]
The proposal makes sense. Decided that it is not worth changing in Yii2, since it would be incompatible for already working code.

But this can be changed in Yii3 https://github.com/yiisoft/db-sqlite

**Comment by santilin** [comment]
I have tested it in Yii2 and the table quote character must be double quote or the queries will fail. This needs testing in Yii3.
