### ISSUE TITLE
 soft delete need official support.

### ISSUE THREAD

**Issue by ooing** [yiisoft/yii2#20166]
Although there are other ways, he won't update it.  
example
* https://github.com/yiithings/yii2-softdelete                 committed           7 years ago       
* https://github.com/yii2tech/ar-softdelete    This repository has been archived by the owner on Jan 11, 2022. It is now read-only.
  

  Other frameworks are built-in, because this is also a core function, which is handed over to a third party. I don't know how to make it compatible in the later stage.

**Comment by mtangoo** [comment]
Yii2 is practically in [feature freeze](https://www.yiiframework.com/news/156/yii-2-1-and-yii-2-0-feature-freeze). DO not expect any major feature like this one to be added.  You can pick the repo and maintain it yourself. If you think you can make a case, the best for Yii2 is to raise issue at [Yii2 extensions](https://github.com/yii2-extensions/extensions/issues?q=is%3Aissue+is%3Aclosed). If one convinced of a need and ready to maintain, one of those repos will be maintained. Else download the files change namespace and maintain it as part of your code

I will close this one. Feel free to reopen if you think it should be open
