### ISSUE TITLE
Динамическое изменение сценария мадели в поведении

### ISSUE THREAD

**Issue by badtiger** [yiisoft/yii2#20177]
Каким образом можно изменить или добавить новый сценарий к модели из поведения.
Существует модель User c определенными сченариями
```php
public function scenarios(): array
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_IMPORT] = ['username', 'first_name', 'last_name', 'middle_name', 'phone', 'email',
            'roleNames', 'pass_number'];
        $scenarios[self::SCENARIO_CREATE] = ['username', 'first_name', 'last_name', 'middle_name', 'phone', 'email',
            'roleNames', 'userPositions', 'workUserPeriods', 'userStages', 'userSkills', 'phones', 'emails',
            'common_id', 'pass_number', 'userWages', 'card', 'payment_by_card'];
        $scenarios[self::SCENARIO_UPDATE] = ['username', 'first_name', 'last_name', 'middle_name', 'phone', 'email',
            'roleNames', 'userPositions', 'workUserPeriods', 'userStages', 'userSkills', 'phones', 'emails',
            'common_id', 'pass_number', 'userWages', 'card', 'payment_by_card'];
        $scenarios[self::SCENARIO_UPDATE_PASSWORD] = ['new_password', 'verify_new_password'];
        return $scenarios;
    }
```

К ней подключено поведение InternationalPhoneBehaviors, в котором к модели добавляются поля:
```php
    public string $internationalPhone;
    public string $internationalCode;
```
В форме User эти поля определены и имеют значения, однако при методе $model->load() они не добавляются к модели так как не определены сценарием. В этом суть пробемы.

Вариант прописать у всех моделей в сценариях свойства не подходит.
Так же не могу отлавливать эти поля через запрос вроде:
`Yii::$app->request->post($model->formName());`
так как может передаваться массив телефонов, а не один.

Спасибо за любую помощ

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.3
| PHP version      | 8.1

**Comment by samdark** [comment]
Решения сходу не придумалось. Попробуйте в чатах спросить и на форумах.
