### ISSUE TITLE
Changing the boolean logic of tag attributes

### ISSUE THREAD

**Issue by s1lver** [yiisoft/yii2#20198]
Maybe it's worth changing the logic for working with boolean when creating tag attributes?

### What steps will reproduce the problem?

```php
echo Html::submitButton(
    'Test',
    [
        'disabled' => true,
    ]
);
```

```html
<button type="submit" disabled="">Test</button>
```

For `disabled` attribute it is correct https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

Let's take this example:
```php
echo Html::submitButton(
    'Test',
    [
        'name' => 'Test[test1]',
        'value' => true,
        'disabled' => false,
    ]
);
```
```html
<button type="submit" name="Test[test1]" value="">Test</button>
```
For this option it will no longer work correctly (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#value)

### What is the expected result?
```html
<button type="submit" name="Test[test1]" value="1">Test</button>
```
or

```html
<button type="submit" disabled="1">Test</button>
```
### What do you get instead?
```html
<button type="submit" name="Test[test1]" value="">Test</button>
```
or

```html
<button type="submit" disabled="">Test</button>
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.*
| PHP version      |  >= 5.*
| Operating system | All

**Comment by samdark** [comment]
Good idea. Do you have time for a pull request.

**Comment by s1lver** [comment]
ok, ill do it

**Comment by brandonkelly** [comment]
This is a breaking change that is causing issues like https://github.com/craftcms/cms/issues/15231. Please revert!

**Comment by samdark** [comment]
Done.

**Comment by s1lver** [comment]
> This is a breaking change that is causing issues like [craftcms/cms#15231](https://github.com/craftcms/cms/issues/15231). Please revert!

How did this impact? Are all your empty values ​​boolean values?

**Comment by brandonkelly** [comment]
The PR changes the meaning of `false`. Previously (like `null`), `false` could be used to indicate that the attribute should **not** be added:

https://github.com/yiisoft/yii2/blob/52e4a3e645eaece47c3f9dddac7c1771a5bd7804/framework/helpers/BaseHtml.php#L2014-L2017

You can’t just arbitrarily change the purpose of setting an attribute to `false` in a point release.
