### ISSUE TITLE
MaskedInput

### ISSUE THREAD

**Issue by alxlnk** [yiisoft/yii2#20211]
### What steps will reproduce the problem?
Upgrade Yii to 2.0.50 version

### What is the expected result?
Masked input with regex must work

### What do you get instead?
MaskedInput initialization throws error

### Additional info
jquery: 3.6.4
inputmask: 5.0.8

https://jsfiddle.net/4jx0pqgw/

Need to add the `regex` parameter to required list in initialization.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.50
| PHP version      | 7.4.27
| Operating system | Windows

**Comment by marcovtwout** [comment]
@alxlnk Could you clarify: was this still working on 2.0.49 and is this a regression? Or was it already broken?

**Comment by alxlnk** [comment]
@marcovtwout My last update Yii is from `2.0.49.3` to `2.0.50`. `2.0.49.3` version require `"bower-asset/inputmask": "~3.2.2 | ~3.3.5"` and regex with alias works in MaskedInput widget, but `2.0.50` require `"bower-asset/inputmask": "^5.0.8 "` and it broken my previous widget config.

**Comment by alxlnk** [comment]
PR #20212 already merged and resolve configuration issue.

**Comment by alxlnk** [comment]
To work correctly in version `2.0.50` you need to use the following widget configuration:
```
[
    'aliases' => [
        'regex' => [
            'regex' => '^.*$',
        ],
    ],
    'clientOptions' => [
        'alias' => 'regex',
    ],
]
```
but more simplify and valid is
```
[
    'clientOptions' => [
        'regex' => '^.*$',
    ],
]
```
