### ISSUE TITLE
Data providers perform unnecessary COUNT queries that negatively affect performance

### ISSUE THREAD

**Issue by sleptor** [yiisoft/yii2#20213]
### What steps will reproduce the problem?

Check the debug panel on any page containing GridView.

### What is the expected result?

Single COUNT query

### What do you get instead?

Multiple identical COUNT queries 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.51-dev
| PHP version      |  8.1
| Operating system | Debian Buster

The problem is in this function:
https://github.com/yiisoft/yii2/blob/master/framework/data/BaseDataProvider.php#L165 and related to the changes made in this commit https://github.com/lav45/yii2/commit/bcc499bfaf01124e730b90748eb32d817424a0c1

It is expected to implement caching, but due to a bug/typo it always calls $this->prepareTotalCount().

The correct code has to be the following:

```
  public function getTotalCount()
    {
        if ($this->_pagination === false) {
            return $this->getCount();
        }
        if ($this->_totalCount !== null) {
            return (int)$this->_totalCount;
        }
        return $this->_totalCount = $this->prepareTotalCount();  // <---
    }
```

**Comment by lav45** [comment]
@sleptor 
> So, the cache definitely does not work, which affects performance notably.

Usually `getTotalCount()` is called once when creating a paginated navigation.
If several identical queries are running in your case, then use caching.

```php
User::getDb()->queryCache = new \yii\caching\ArrayCache();
```

**Comment by sleptor** [comment]
@lav45 getTotalCount() is being called multiple times during GridView rendering. It's normal.
To avoid duplicated COUNT queries, its result is cached in $this->_totalCount. 

However,  due to the bug, $this->_totalCount is never initialized, so it's always null.

**Comment by lav45** [comment]
This caching method breaks this test
https://github.com/yiisoft/yii2/blob/master/tests/framework/data/ActiveDataProviderTest.php#L215

**Comment by rob006** [comment]
@lav45 This is a new test, which is not even released and changes behavior that existed in framework since the beginning (and probably breaks BC in some cases) - I think it is fine to drop it if it creates any problems.

In general problems started with #20070 (preceded by #20007) and each attempt to fix them created even more problems and regressions. I suggest to revert all changes to state before #20070 or #20007 and start again from there. Messing with pagination and data provider cache looks like a dead end to me.

**Comment by marcovtwout** [comment]
What is needed to solve the immediate issue here? Can we revert all the mensioned changes so we can release 2.0.50.1? 2.0.50 is now very much broken in this regard and has been for a few weeks. It would be good to solve the release first, and then re-address the solution for this ticket.

**Comment by samdark** [comment]
@terabytesoftw is on rolling back the changes.

**Comment by terabytesoftw** [comment]
[Remove cache \yii\data\ActiveDataProvider::prepareTotalCount()[]()](https://github.com/yiisoft/yii2/pull/20206)

I think it should be added.

**Comment by terabytesoftw** [comment]
I also think that testing needs to be improved.

**Comment by terabytesoftw** [comment]
> @lav45 This is a new test, which is not even released and changes behavior that existed in framework since the beginning (and probably breaks BC in some cases) - I think it is fine to drop it if it creates any problems.
> 
> In general problems started with #20070 (preceded by #20007) and each attempt to fix them created even more problems and regressions. I suggest to revert all changes to state before #20070 or #20007 and start again from there. Messing with pagination and data provider cache looks like a dead end to me.

I think we should also revert this PR: https://github.com/yiisoft/yii2/issues/20002

**Comment by terabytesoftw** [comment]
All changes were reverted:

- https://github.com/yiisoft/yii2/pull/20226 

Thks.

**Comment by terabytesoftw** [comment]
@rob006 Fixed, thks.

**Comment by schmunk42** [comment]
Hi guys, sorry for being late to the party :) 

JFTR, we were also affected by this bug.
Maybe next time we should move such a PR to the 2.2 branch.
