### ISSUE TITLE
BaseActiveRecord save method - php docs do not state possible throwing of exception

### ISSUE THREAD

**Issue by mandano** [yiisoft/yii2#20235]
### What steps will reproduce the problem?
- go to vendor/yiisoft/yii2/db/BaseActiveRecord.php
- check [at]throws attribute in php docs
- check insert() method php docs in ActiveRecord.php, 
- check update() method php docs in BaseActiveRecord.php

### What is the expected result?
- expected to contain [at]throws StaleObjectException, Exception or 
Throwable as update(), insert() methods could throw these
- in case save() should not throw an exception, catch needed for update(), insert() methods

### What do you get instead?
- no [at]throws statement stated
- or missing catch statements in save()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.4
| PHP version      | 
| Operating system | Linux

save() method - BaseActiveRecord
![grafik](https://github.com/user-attachments/assets/1f53cb33-4f76-4426-9a35-8165a45b2059)

insert() method - ActiveRecord
![grafik](https://github.com/user-attachments/assets/b4ddacdd-d6f5-46f4-ac53-da1fd65641cf)

update() method - BaseActiveRecord
![grafik](https://github.com/user-attachments/assets/048af306-864b-4033-9345-209145ebdb80)

**Comment by samdark** [comment]
Should be added to phpdoc, indeed. Do you have time for a pull request?

**Comment by mandano** [comment]
> Should be added to phpdoc, indeed. Do you have time for a pull request?

hey! i have time for a pr.
Btw what do you think about catching the exceptions inside of save(). as otherwise each user of save() needs to create a try catch, which bloats up that abstraction layer unnecessarily?

**Comment by handcode** [comment]
for phpdoc see https://github.com/yiisoft/yii2/pull/20146

about catching the exceptions inside of save():
I think this should/can not be done, as exceptions thrown within save() can be (or are) used to handle use cases like https://github.com/yiisoft/yii2/issues/8392 or https://github.com/yiisoft/yii2/issues/20253

**Comment by samdark** [comment]
Seems there's nothing left to do. Closing. Thanks, @handcode for looking into it.

**Comment by mandano** [comment]
ok, thank you.
