### ISSUE TITLE
Model modification data failed

### ISSUE THREAD

**Issue by 2723659854** [yiisoft/yii2#20234]
### What steps will reproduce the problem?

//Business code
```php
$service = Service::findOne(1);
//$service['news'] = 0;
$service["last_reply_at"] = time();
$service["news"] = 1;
$service["status"] = 9;
$service->save();
```
Other attributes have already been modified, such as `last_reply_at ` and ` status`. But the field  `news` can sometimes be changed to 1, but sometimes it is still 0 and has not been modified.

### What is the expected result?
Attributes can be modified correctly，The correct value in the database should be 1, not 0。
```php
//$service['news'] = 1;
```

### What do you get instead?

please fix this bug.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.3
| PHP version      | 8.2.9
| Operating system | LINUX

**Comment by samdark** [comment]
What's returned from `->save()`?

**Comment by 2723659854** [comment]
> What's returned from `->save()`?

sorry ,It was other operations that modified the data.And thank you very much，It's my mistake.

**Comment by 2723659854** [comment]
thank you
