### ISSUE TITLE
[Feature Request] Streaming responses Support

### ISSUE THREAD

**Issue by qwerty199369** [yiisoft/yii2#20263]
Streaming responses are very common in some AI API scenarios, and it is expected that the Yii framework will support this feature

**Comment by samdark** [comment]
Yii3 already supports it. Are you sure Yii2 doesn't?

**Comment by qwerty199369** [comment]
I'm not really sure, I just can't find it in the documentation. https://www.yiiframework.com/doc/guide/2.0/en/runtime-responses

**Comment by bizley** [comment]
Of course it is supported. See https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L144 
I guess it's not documented in the Guide.
