### ISSUE TITLE
Bug: "bower-asset/punycode": "^2.2" dependency is not valid

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/yii2#20283]
Since 2.0 "mathiasbynens/punycode.js" is a commonJS lib and can't be used in the browser.

```
module.exports = punycode;
```

#20009 

To reproduce an error configure the `email` validator for the form field like this
```
['email', 'email', 'enableIDN' => true],
```

and try to open the page with the form
![image](https://github.com/user-attachments/assets/ed8bc713-cf98-4123-9046-58b266897061)

**Comment by mtangoo** [comment]
Does it go away if `'enableIDN' => false`?

**Comment by samdark** [comment]
@mtangoo yes, likely as in this case the lib isn't used.

**Comment by samdark** [comment]
We can force using older version.

**Comment by mtangoo** [comment]
I have found this, which no longer appears on README.
https://github.com/mathiasbynens/punycode.js/pull/118/commits/28de93e6d772b95a49a36bb7ebec585911a58165

>This project provides a CommonJS module that uses ES6 features and an ES6 module, which work in modern Node >versions and browsers. For the old version that offers the same functionality in a UMD build with support for older pre-ES6 >runtimes, including Rhino, Ringo, and Narwhal, see [v1.4.1](https://github.com/bestiejs/punycode.js/releases/tag/v1.4.1)

Am not sure why it is no longer there.

**Comment by mtangoo** [comment]
After checking releases page I found this:

[v2.0.0](https://github.com/mathiasbynens/punycode.js/releases/tag/v2.0.0)
This release drops support for old environments. Punycode.js v2.0.0 targets Node.js v6+ and nothing else. For the old version that offers the same functionality with broader support, including Rhino, Ringo, Narwhal, and web browsers, see [v1.4.1](https://github.com/bestiejs/punycode.js/releases/tag/v1.4.1).

**Comment by mtangoo** [comment]
Looks like we have to pin the version to exactly 1.4.x

**Comment by mtangoo** [comment]
@olegbaturin can you test https://github.com/yiisoft/yii2/pull/20284 if the issue is fixed?

**Comment by olegbaturin** [comment]
> @olegbaturin can you test #20284 if the issue is fixed?

with 1.4.1 it works fine
