### ISSUE TITLE
yii\web\Session with useCookies = false breaks on PHP 8.3.14

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#20292]
### What steps will reproduce the problem?

Upgrading from PHP 8.3.7 to 8.3.14 breaks `yii\web\Session` when used with useCookies = false.

Breaking Change in PHP: https://github.com/php/php-src/commit/7cdd1302c380dfaeb62ac926c94a2e2850d25411 (https://github.com/php/php-src/issues/16385)

Error: 

```
[error][yii\base\ErrorException:2] yii\base\ErrorException: session_set_cookie_params(): Session cookies cannot be used when session.use_cookies is disabled in /var/www/layer5-live/vendor/yiisoft/yii2/web/Session.php:429
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/layer5-live/vendor/yiisoft/yii2/web/Session.php(429): session_set_cookie_params()
#2 /var/www/layer5-live/vendor/yiisoft/yii2/web/Session.php(147): yii\web\Session->setCookieParamsInternal()
#3 /var/www/layer5-live/vendor/yiisoft/yii2/web/Session.php(699): yii\web\Session->open()
```

### What is the expected result?

 `yii\web\Session` should not set cookie params when useCookies is false.

### What do you get instead?

See error above.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.49.3
| PHP version      | 8.3.14
| Operating system | Debian Linux

**Comment by cebe** [comment]
related to #20287

**Comment by samdark** [comment]
I'll check remaining issues this week.
