### ISSUE TITLE
What is the correct way to write 'bindValues'+'where in'?

### ISSUE THREAD

**Issue by terranc** [yiisoft/yii2#20301]
```php
$sql = 'select * from users where user_id in (:user_ids)';
Yii::$app->db->createCommand($sql, [
	':user_ids' => [1,2,3]
]);
```
The above code is wrong and will only filter out data with user_id = 1.
If there is an in conditional query in sql, how should we combine bindValues to implement params binding?

**Comment by bizley** [comment]
This component is basically just a wrapper for PDO, so it's not directly possible like that. Use Yii's query builder if you don't want to worry about array binds.
