### ISSUE TITLE
Resetting after fileCache expires cannot immediately obtain values

### ISSUE THREAD

**Issue by luguohuakai** [yiisoft/yii2#20300]
### What steps will reproduce the problem?

```php
$rs = Yii::$app->cache->set('k', 'v', 5);
var_dump($rs);
var_dump(Yii::$app->cache->get('k'));
```

### What is the expected result?

bool(true)
string(1) "v"

### What do you get instead?

bool(true)
bool(false)

### Additional info

The first execution returned no problem. When k was reexecuted after 5 seconds expired, the returned result was wrong and I couldn't get the value immediately.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.50
| PHP version      | 8.1.27
| Operating system | openEuler

**Comment by bizley** [comment]
What kind of cache is it?

**Comment by samdark** [comment]
Is it file, DB, memcache, Redis?

**Comment by luguohuakai** [comment]
> What kind of cache is it?

file

    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache'
        ],
    ]

**Comment by luguohuakai** [comment]
> Is it file, DB, memcache, Redis?

file

**Comment by bizley** [comment]
I confirm this. Problem lies in the internal caching of file stats. Cache get returns previous cached set time which can yield false if duration is really short and cache is called immediately as in this case.

To be honest I'm not sure if this is worth fixing.
1. Short-lived file cache is pointless as file accessing is slow.
2. We could unlink the file but it adds overhead.
3. We could clear stats cache but again it adds overhead.

I recommend just adding the warning in the docs so it can be taken care of by the developer if that short duration on file cache is really necessary.

**Comment by rob006** [comment]
> We could clear stats cache but again it adds overhead.

We only need `clearstatcache()` call in `setValue()`, I don't think that overhead should be noticeable comparing to already existing logic in this method.

Also, I don't think that this is related to cache duration. You should get such behavior always when you have consecutive `set()` and `get()` calls for expired cache.

**Comment by bizley** [comment]
> Also, I don't think that this is related to cache duration

What do you mean? I logged set timestamp and received filemtime and it was always showing previous set value on rapid calls.

**Comment by rob006** [comment]
I assumed this happens when:
1. cache expired, but file still exists with mtime from the past.
2. you call `get()` which caches mtime by PHP for that file.
3. you call `set()` which overwrites file ad its mtime.
4. you call `get()` which uses mtime cached in step 2. and detects cache as expired.

**Comment by bizley** [comment]
In my tests it showed:

fresh cache set to X (timestamp)
cache get before X - success

next spin:
cache set to Y
cache get before Y but returns X - fail

**Comment by rob006** [comment]
I can confirm it works like described in https://github.com/yiisoft/yii2/issues/20300#issuecomment-2565243249 and `clearstatcache()` fixes this problem.

```php
var_dump(Yii::$app->cache->get('__METHOD__'));
Yii::$app->cache->set('__METHOD__', 'test2', 10);
var_dump(Yii::$app->cache->get('__METHOD__'));
Yii::$app->cache->set('__METHOD__', 'test3', 10);
clearstatcache();
var_dump(Yii::$app->cache->get('__METHOD__'));
```

result:

```
bool(false)
bool(false)
string(5) "test3"
```

**Comment by rob006** [comment]
PR: https://github.com/yiisoft/yii2/pull/20304
