### ISSUE TITLE
Document fixtures usage in basic and advanced app tests

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#2035]
This issue is based on p1 of [this](https://github.com/yiisoft/yii2/issues/1956#issuecomment-32638755) comment:

> For codeception tests, should we need to develop a base test class which has the fixture management feature like the unit test class? How do functional tests make use of fixtures?

@DavertMik said:

> @Ragazzo @qiangxue Sure, fixtures can be applied to any tests. And the test-dump is not the one and not the best choice. 
> 
> As I see usage of AR in functional tests may look like:
> 
> ``` php
> $user_id = $I->haveRecord('User', array('name' => 'Yii'));
> $I->haveRecord('Category', array('name' => 'Testing')');
> ```
> 
> This can be improved to use fixtures as well:
> 
> ``` php
> $I->haveFixture('UserProfile', 'user1');
> ```
> 
> And yes, it means that Yii2 module should handle AR interactions as well. So it would allow testing the database as well as responses.
> 
> Also I think fixture trait may be used in Helper classes and Group classes. Something like, to load a common set of fixtures for a specific group of tests.

@Ragazzo said:

> as for @DavertMik approach, i would rather vote for second:
> $I->grabFixture('UserProfile', 'user1');
> 
> Need more thinking here of course.

**Comment by dynasource** [comment]
enough information on this subject at http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html
