### ISSUE TITLE
Fixture support for NoSQL DBs

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii2#2053]
With the new test fixture framework (https://github.com/yiisoft/yii2/blob/master/docs/guide/test-fixtures.md), we need to develop base fixture classes for NoSQL DBs to simplify creating fixtures for these DBs. We mainly need to develop `ActiveFixture` by extending `BaseActiveFixture` for each of the following extensions:

- [x] mongodb
- [ ] redis
- [x] elasticsearch
- [x] sphinx

**Comment by klimov-paul** [comment]
For the Sphinx fixture support can be provided only for 'runtime' indexes. Regular Sphinx indexing process is unable to be controlled from PHP.

**Comment by klimov-paul** [comment]
Sphinx covered by https://github.com/yiisoft/yii2-sphinx/commit/9e27bbe0c7ecfaa24bbb604355de8b1903e1b88b

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-redis/issues/10
