### ISSUE TITLE
GII Model Generator - Generate ActiveQuery Class

### ISSUE THREAD

**Issue by lucianobaraglia** [yiisoft/yii2#2109]
http://www.yiiframework.com/forum/index.php/topic/50832-gii-and-new-query-classes/page__pid__236155

I you are too busy, I could try it, but show me a basic skeleton of a class and how the model class should be updated also...

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-gii/pull/30

**Comment by klimov-paul** [comment]
Resolved by https://github.com/yiisoft/yii2-gii/pull/30
