### ISSUE TITLE
ActiveRelation: support custom Scopes

### ISSUE THREAD

**Issue by nizsheanez** [yiisoft/yii2#2146]
`$this->hasOne(Report::className(), ['fk_goal' => 'id'])->myScope()->one();`
have exception
`Calling unknown method: yii\db\ActiveRelation::myScope()`
I must to redeclare createActiveRelation ?

Now i solve i like:

```php
class Report extends ActiveRecord {

    public static function createQuery()
    {
        return new ReportQuery(['modelClass' => get_called_class()]);
    }

    public static function createActiveRelation($config = [])
    {
        return new ReportRelation($config);
    }

}

//scopes
trait ReportScopes
{
    public function myScope() {
        return $this;
    }
}

//apply scopes to query
class ReportQuery extends ActiveQuery
{
    use ReportScopes;
}

//apply scopes to relations
class ReportRelation extends ActiveRelation
{
    use ReportScopes;
}
```

**Comment by Gcaufy** [comment]
@qiangxue 
class Post extends ActiveRecord
{
    public static function scopeVisible($query)
    {
        $query->andWhere(['visible' => 1]);
    }
}

Post::find()->visible()->all();


is this working now in current yii2?

**Comment by cebe** [comment]
no, scopes are only supported in custom query classes.

**Comment by AleksandrIvin** [comment]
is this tutorial for scopes in relations correct? 
from http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#scopes

You can also use scopes when defining relations. For example,

class Post extends \yii\db\ActiveRecord
{
    public function getActiveComments()
    {
        return $this->hasMany(Comment::className(), ['post_id' => 'id'])->active();

    }
}

I have a problem: 
Calling unknown method: yii\db\ActiveQuery::active()

Thanks

**Comment by SamMousa** [comment]
I know this has been discussed in depth, but i'm unclear what's the argument against the example code by @qiangxue ..

This example query basically implements support for this feature without breaking anything else.


        class TestQuery extends ActiveQuery {
            public function __call($name, array $arguments) {
                // Check if this is a scope.
                $method = 'scope' . ucfirst($name);
                array_unshift($arguments, $this);
                if (method_exists($this->modelClass, $method)) {
                    $result = forward_static_call_array([$this->modelClass, $method], $arguments);
                } else {
                    $result = parent::__call($name, $arguments);
                }
            }
        }


This code has little overhead and as far as I can tell does not break BC. The argument against having different names for scopes in an ActiveQuery class vs scopes in an ActiveRecord class is not valid in my opinion. The added ease of use of this code outweights the "inconsistency" in my opinion.

Obviously I can and do implement this in my base ActiveQuery / ActiveRecord classes, but I think it would improve the framework to include this.

**Comment by klimov-paul** [comment]
This sounds interesting.
However instead of composing method name with prefix 'scope' it is better to check if the method is static  using reflection. This can lead us back to original implementation, where static methods of Active Record class serve as a scopes.

**Comment by SamMousa** [comment]
Making all static methods a scope automatically seems bad to me. If we use reflection we could go as far as to check the signature to see if it is a scope. However for me this adds no real benefit.

I like having the scope prefix in my ActiveRecord class and I like not having to use the scope prefix when running the query. 

Also there are some static methods that are never scopes (like getDb, createQuery, tableName) I'd rather not have to think about these possible collisions; also for BC the prefix is safer since I can easily verify that any existing static methods don't start with "scope"; it is harder for me to verify that any static methods I have defined will not pass the check for being interpreted as a scope.

What is bad about the prefix method? Is it bad practice?

**Comment by klimov-paul** [comment]
Using the prefix for scopes method introduces special magic. Also not everyone may actually like it.
For example: I prefer to declare scope methods in format 'where...':
```php
public static function whereActive($query)
{
    ...
    return $query;
}
```
This way scope methods looks pretty both while declaring and while applying.

Also originally (back at 'beta' version) Active Record declared its scopes in this way - just a static methods without any prefix.

**Comment by klimov-paul** [comment]
It is obvious we are running circles around here.
I have reread the entire conversation and found final resolution reference:
https://github.com/yiisoft/yii2/issues/2016#issuecomment-32629793

Change does not make sense.

**Comment by SamMousa** [comment]
Ok, clear on the final arguments. Will consider releasing this as a separate module. Thanks for the input!
