### ISSUE TITLE
'yii\base\Behavior' and model scenarios.

### ISSUE THREAD

**Issue by vova07** [yiisoft/yii2#2309]
Maybe it's not a bug, more like improvement, however I'll post this here.
We have a simple behavior `MyBehavior` with following code:

``` php
class MyBehavior extends Behavior
{
    public $myAttr;

public function attach($owner)
{
    parent::attach($owner);
    $validator = Validator::createValidator('validatorType', $owner, ['myAttr']);
        $owner->validators[] = $validator;
}
```

with this behavior we add `$myAttr` in all needed models.
How can we add this attribute in model `scenarios` for mass assignements, just using our `behavior` ?
I mean that our `$owner` has more than one `default` scenario.
For this case I think `Model::scenarios` must be a `getter/setter` like `validators`.

UPD: The same thing with `attributeLabels`, for `$myAttr`.

**Comment by dynasource** [comment]
if you use scenarios() than you choose for a rigid implementation in which flexible behaviors won't work anymore. Either you override $scenario's or let the scenario's be created by model->scenarios()
