### ISSUE TITLE
AR: Implement Class Table Inheritance

### ISSUE THREAD

**Issue by alpharder** [yiisoft/yii2#2319]
While Single Table Inheritance (STI) can be easily implemented by framework end-users (http://www.yiiframework.com/wiki/198/single-table-inheritance/), fully functional Class Table Inheritance (CTI) implementation requires in-depth knowledge of how AR internals work. Moreover, I'm not sure it is possible to implement CTI as an extension or behavior.
In this way, it would be great if AR support CTI out-of-box.

What is CTI:
http://www.martinfowler.com/eaaCatalog/classTableInheritance.html
http://css.dzone.com/articles/practical-php-patterns-class
http://www.slideshare.net/billkarwin/practical-object-oriented-models-in-sql (19 slide)

Doctrine 2 CTI:
http://docs.doctrine-project.org/en/2.0.x/reference/inheritance-mapping.html#class-table-inheritance

Rails CTI:
https://github.com/mhuggins/multiple_table_inheritance

Unsuccessful attempts to implement CTI:
http://www.yiiframework.com/forum/index.php?/topic/5803-my-multi-table-inheritance-approach/
http://www.yiiframework.com/forum/index.php/topic/12978-class-table-inheritance/
http://www.yiiframework.com/forum/index.php?/topic/11131-inheritance-extending-a-model

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/ar-role

**Comment by dynasource** [comment]
CTI is a nice to have as an extension

**Comment by senguttuvang** [comment]
> I also do not see real benefits for creating applications in this approach.

@cebe If you consider any enterprise scale applications, you'll likely to come across many data models that would require table inheritance hierarchy and it is very common. I came across party data model for tracking people and organisations. Recently, I was doing an HRMS application, where I track user's leave across the hierarchy. They should be not just common, but are an efficient way to abstract details and will help us to write maintainable code.

@klimov-paul I did look at ar-role, but it doesn't look "natural".

**Comment by klimov-paul** [comment]
> I did look at ar-role, but it doesn't look "natural".

Sorry - it is all I can do for you. Note that ActiveRecord pattern itself does not suite for such kind of tasks - so implementation will always be not "natural". If you have an idea of improvement - open an issue.
