### ISSUE TITLE
DB NoSQL: manual index tables in framework ?

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#2338]
I use Apache Cassandra and it's having hard time using non-PK columns in WHERE, and also puts some weird restrictions on key use order.

This forces to create tables to use as manual indexes, this approach is recommended by vendor.

Is it possible to make indexes in framework, have them auto-updated on record change, and used in queries with WHERE on manual-indexed columns ?

Even if dev team will reject this, please give an advice on how to implement this myself and what are hook points.

**Comment by dynasource** [comment]
this issue will be closed because of its age, few stakeholders and the absence of progress. Please do a vote if you want it to be reopened again.
