### ISSUE TITLE
Debug Panel should have information about cache

### ISSUE THREAD

**Issue by dilip-vishwa** [yiisoft/yii2#2365]
If the cache is used in page, then we should get some informative information about the cache component used in particular view, query, fragment, or page, etc. It should also show the content of the particular cache.

**Comment by kidol** [comment]
Anyone in favor for the event based approach? In yii 1 one had to parse though the log to figure out cache hits/misses. With events, the debug toolbar can listen for class-level events I think:

```php
Event::on(Cache::className(), Cache::EVENT_SET, function ($event) {
    // Collect all results for later
    // $event->sender can be used to figure out cache backend
    // $event might provide: $cacheKey, $success (whether get, set, etc. succeeded)
});
```

Normal logging like in yii 1 should still be added I guess?

Also a simplified version of the idea
> expiration settings and it's duration till now

is possible if cache does store expire timestamp within the cache data (serialize, like with dependency). Then we could see when cache item expires. It could be an optional feature, disabled by default.
