### ISSUE TITLE
Table alias for joinWith needed 

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#2377]
For tables with two (or more) foreign keys referencing the same related table you need a way to define an alias. The ```joinWith()```function doesn't have this ability. 
So there is no way to handle ambiugate column names for the related table.

**Comment by Gcaufy** [comment]
is this implemented  by yii2 now?

**Comment by cebe** [comment]
no, as you see in this issue, the milestone is set for 2.0.3, I am going to work on that for this milestone and if all goes well it should be released with it.

**Comment by Gcaufy** [comment]
currently I'm doing it like this, let me know when it would be released
<pre>
public static function with($r, $t = null) {
        $relations = array();
        if (is_array($r)) {
            foreach ($r as $v => $tn) {
                $i = strripos($v, '.');
                $alias = $v;
                if ($i != false)
                    $alias = substr($alias, $i + 1);
                $relations[$v] = function ($q) use ($tn, $alias) { $q->from($tn . ' ' . $alias); };
            }
        } else {
            $alias = $v;
            if ($i != false)
                $alias = substr($alias, $i + 1);
            $relations[$r] = function ($q) { $q->from($t . ' ' . $alias); };
        }
        return static::find()->from(static::tableName() . ' t')->joinWith($relations);
    }

    public static function find() {
        return parent::find()->from(static::tableName() . ' t');
    }
</pre>

**Comment by callmez** [comment]
😢

**Comment by cebe** [comment]
@callmez I am sorry but my time is limited. I'd love to work on this but it turns out there is more to be done in the background than it looks like on first sight.

**Comment by callmez** [comment]
it's ok, still thanks for you work.

**Comment by rahulsinh** [comment]
@cebe SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'title' in where clause is ambiguous
can you help me:
  if (!$this->validate()) {
            // uncomment the following line if you do not want to any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }
       
        $query ->joinWith('location');
        $query ->joinWith('programCategory');
        $query ->joinWith('duration');
        $query ->joinWith('airport');
        $query->andFilterWhere([
            'program_id' => $this->program_id,
       
        ]);

        $query->andFilterWhere(['like', 'title', $this->title])
          ->andFilterWhere(['like', 'location.city', $this->location_id])
            ->andFilterWhere(['like', 'program_category.program_category_name', $this->category_id])
            ->andFilterWhere(['like', 'duration.type', $this->duration_id])
            ->andFilterWhere(['like', 'airport.city', $this->airport_id]);
                
           

        return $dataProvider;
    }
}

**Comment by cebe** [comment]
@rahulsinh this is not related, please use the forum to ask questions.

**Comment by MaXL-ru** [comment]
As I understand in Yii 2.0.3, I must write next code:

```php
$query = Billing::find()
  ->joinWith([
    'state'
  ]);

$query->andFilterWhere([
  Billing::tableName() . '.id' => $this->id
]);
```

if table related to `Billing` AR and table related to `state` relation have column `id` ?

**Comment by mklemarczyk** [comment]
:+1:  @MaXL-ru It is always the problem when you extend SearchModel.
I often use a table prefix and I need to use tableName function many times.

```php
    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Employee::find()
			->innerJoinWith('user', false)
			->innerJoinWith('company', false);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id' => $this->id,
            [...]
            'company_id' => $this->company_id,
            'user_id' => $this->user_id,
        ]);
		// Here I must use tableName function
		$query->andFilterWhere(['like', User::tableName() . .firstname', $this->user_firstname]);

        return $dataProvider;
    }
```

**Comment by lynicidn** [comment]
@mklemarczyk: you should configure `sort` property of dataProvider.
see `ActiveDataProvider::setSort()`

**Comment by mklemarczyk** [comment]
Thank you @lynicidn, I miss it. But now I also need to reorganize all methods that use joinWith in my EmployeeQuery class.

I think that, instead of modifying joinWith method we should resolve relation names in other methods?
Using aliases can join may times the same table in our Query.

**Comment by igorbelikov** [comment]
+

**Comment by MaXL-ru** [comment]
Not in 2.0.4 :-1:

**Comment by petrabarus** [comment]
Hope this will be supported in 2.0.5

**Comment by dynasource** [comment]
am I correct when assuming that the use of the same junction table is not supported yet?
Ie.:
```php
$query = Article::find();
$query->joinWith('category.article');
```

Gives:
* Not unique table/alias: 'article_x_article_category'

Because:
* article joins category by article_x_article_category
* category joins article by article_x_article_category

Resulting in SQL:
```sql
SELECT `article`.* 
FROM `article` 
LEFT JOIN `article_x_article_category` ON `article`.`id` = `article_x_article_category`.`owner_id`
LEFT JOIN `article_category` `category` ON `article_x_article_category`.`category_id` = `category`.`id`
LEFT JOIN `article_x_article_category` ON `category`.`id` = `article_x_article_category`.`owner_id`
LEFT JOIN `article` ON `article_x_article_category`.`category_id` = `article`.`id` 
WHERE `article`.`id`=10948
```

**Comment by Koudy** [comment]
+

**Comment by avinashz** [comment]
+1 :+1:

**Comment by onedevlink** [comment]
+

**Comment by disem** [comment]
+

**Comment by StagnantIce** [comment]
+

**Comment by Yiivgeny** [comment]
+1

**Comment by neotrouz** [comment]
+1

**Comment by JavierCabezas** [comment]
I would love this functionality!

**Comment by pun4drunk** [comment]
+1

**Comment by keeprock** [comment]
Me too, but, guys, instead of waiting - take a look of other frameworks implementations on this.

**Comment by SilverFire** [comment]
It is already in work: https://github.com/yiisoft/yii2/issues/10253

**Comment by cebe** [comment]
PR is merged.
