### ISSUE TITLE
Yii2 extension repository

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#2395]
Continued from http://www.yiiframework.com/forum/index.php/topic/39669-composer-support/

@qiangxue @samdark @cebe What are your plans regarding http://www.yiiframework.com/extensions/ for Yii2?

Theoretically this could be done via the Packagist API, just by filtering `type=yii2-extension` but there are some limitations at the moment (eg. limited search, fuzzy matching), which would have to be solved on the packagist side.

Or will you maintain a copy of this data or your even own data?

**Comment by dynasource** [comment]
its unclear to me what needs to be done here. If this still is an important issue or feature request, please open a new ticket with a proper description.

**Comment by samdark** [comment]
It will be part of https://github.com/yiisoft-contrib/yiiframework.com/ so could be tracked there.
