### ISSUE TITLE
pjax add more documentation

### ISSUE THREAD

**Issue by gimox** [yiisoft/yii2#2414]
built in support for pjax is somethink good, but need more documentation about integrating it in forms and link.
Add some example about form or link please.

**Comment by samdark** [comment]
http://blog.neattutorials.com/yii2-pjax-tutorial/

**Comment by Faryshta** [comment]
@samdark where is the doc needed? where can i submit a pr?

**Comment by samdark** [comment]
If it's one or two examples — phpdoc of Pjax widget. If it's more, it worth creating new document in the guide.
