### ISSUE TITLE
Common AR behaviors idea (just for reference)

### ISSUE THREAD

**Issue by lucianobaraglia** [yiisoft/yii2#2484]
Based on discussion in https://github.com/yiisoft/yii2/pull/2360, some ideas to behaviors to implement.

- [x] `AttributeStampBehavior`
- [x] `TimestampBehavior`
- [x] `BlameableBehavior`
- [ ] `VersionableBehaior`
- [ ] `SoftDeleteBehavior`
- [ ] `TranslatableBehavior`
- [x] `SluggableBehavior`

**Comment by sensa-ua** [comment]
As I can see actually AR has save and delete methos protected with Transaction:
....
$result = $this->deleteInternal();
if ($result === false) {
      $transaction->rollBack();
} else {
      $transaction->commit();
}

so if we have DB engine with transactions ability turnet on, I don't see a straightforward way to implement soft delete at all. As soon as false returned from beforedelete() event handler all changed managed to DB will be rolled back. There is no way to manage this until it workaround in framework code.

**Comment by Faryshta** [comment]
How about a `CascadeBehavior` ?

When deleting or updating an `ActiveRecord` it will seek the relation of said record and execute predefined actions

Example

```
Class Author
{
    public function behaviors()
    {
        return [
            'cascade' => [
                'class' => CascadeBehavior::className(),
                // List of keys that when updated or deleted will trigger this behavior
                // by default this are the primary keys
                'updateKeys' => ['id'],
                // this will be called when the primary key gets updated.
                'update' => [
                    // this relations will be updated using the attributes provided
                    // when on the `getBooks` method
                    'cascade' => ['books', 'sagas', 'compilations'],
                    // a null value will be sent to replace the value of this relation
                    'nullify' => ['sales'],
                    // if this relation is not empty, then the update stops.
                    'block' => ['payments'],
                ],
                 // this will be called when the model gets deleted.
                'delete' => [
                    // this relations will be updated using the attributes provided
                    // when on the `getBooks` method
                    'cascade' => ['books', 'sagas', 'compilations'],
                    // a null value will be sent to replace the value of this relation
                    'nullify' => ['sales'],
                    // if this relation is not empty, then the update stops.
                    'block' => ['payments'],
                ],
           ],
        ];
    }
}
```

**Comment by sensa-ua** [comment]
I would suggest to stop attack on AR delete() and 'EVENT_BEFORE_DELETE' couple. They are simple enough and complete functions.

I'd rather suggest to expose an extra method via the behavior called SotfDelete();
This should have create transaction safe block, manage the simple attribute update manipulations, and broadcast via host model 'EVENT_BEFORE_SOFT_DELETE' and 'EVENT_AFTER_SOFT_DELETE'. Later these event can be used by more recent behaviors.

**Comment by samdark** [comment]
Translateable: https://github.com/creocoder/yii2-translateable

**Comment by fernandezekiel** [comment]
@sensa-ua  although that is what i do because most of my models have soft delete implementations, i think their goal is to make soft-deletion transparent from the controller point of view or whatever is invoking the model's deletion

**Comment by fernandezekiel** [comment]
also that suggests that your behavior would introduce events, is that possible?

**Comment by sensa-ua** [comment]
@fernandezekiel There are couple points against this behavior in the current shape:
1) Deletion isn't recoverable process, but soft-deletion does - part of functionality related to restoration is remains out of scope with this solution.
2) It makes such mess in the normal event flow, I believe It can lead to many complicated side effects

Instead, I propose to wrap full-functional implementation into behavior, this easy to use and it's transparrent for existing functionality.

And yes, it's easy to broadcat events.

I've put some draft version here:
https://github.com/sensa-ua/yii2-softdelete

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/ar-softdelete

**Comment by LAV45** [comment]
Translateable: https://github.com/LAV45/yii2-translated-behavior
