### ISSUE TITLE
AssetBundle should not publish .less or .coffee files

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#2511]
When converting .less or .coffee files it should run command like this:

`lessc app/assets/main.less web/assets/123456/main.css`

Current implementation makes all the less files public in asset folder and runs converter command afterwards.

**Comment by PommeVerte** [comment]
To add to what @mikehaertl already said. The workaround he gives is a pain but can be worked with. But in the case of using an import of a third party library installed via composer... Well you simply can't. 
If you install:
```
composer 'bower-asset/foundation' '*'
```

Well you're stuck not being able to import any of those files. For such sutuations you're forced to copy the files to your own assets folder and not use composer

**Comment by SamMousa** [comment]
I just ran into the same problem.
Currently the AssetBundle logic is as follows:
1. Check if asset is publicly accessible.
2. If not publish.
3. Check if asset needs conversion.
4. Convert asset
5. Return converted asset path.

I think the issue can be resolved by implementing this flow instead:

1. Check if asset needs conversion.
2. Convert asset
3. Check if converted asset path is publicly accessible.
4. If not, publish converted asset.
5. Return path of published & converted asset.

Advantages:
1. Asset manager can compare published compiled file with unpublished compiled file (allowing for compilation outside the publish cycle).
2. Asset converter can do proper caching / checking for changes.

The following code is an improvement but:
- It does not solve the @include in less files problem.
- It publishes files individually

        public function publish($am)
        {
            if (isset($this->basePath, $this->baseUrl)) {
                return;
            }

            if (($converter = $am->getConverter()) !== null) {
                foreach ($this->js as $i => $js) {
                    if (Url::isRelative($js)) {
                        $this->js[$i] = $converter->convert($js, $this->sourcePath);
                        $am->publish($this->sourcePath . '/' . $this->js[$i], $this->publishOptions);
                    }
                }
                foreach ($this->css as $i => $css) {
                    if (Url::isRelative($css)) {
                        $this->css[$i] = $converter->convert($css, $this->sourcePath);
                        $this->css[$i] = $am->publish($this->sourcePath . '/' . $this->css[$i], $this->publishOptions)[1];
                    }

                }
            } else {
                list($this->basePath, $this->baseUrl) = $am->publish($this->sourcePath, $this->publishOptions);
            }
        }

**Comment by beowulfenator** [comment]
Can this problem be solved by introducing a `beforePublish` method to `AssetBundle`? This function can have some code to prepare the resulting files in, say, `dist` folder which then will be published normally.

**Comment by Faryshta** [comment]
isn't this already supported since 2.0.6? #8566

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
Thanks!
