### ISSUE TITLE
Yii2 RBAC with MongoDB

### ISSUE THREAD

**Issue by z010107** [yiisoft/yii2#2541]
Hello everyone. I have one project where I use MongoDB. Current version RBAC is not support Mongo DbManager. That is why I make MongoDbManager.php.

Code here:
https://github.com/z010107/yii2_rbac_mongodb
Usage:

Put this class into /framework/rbac/MongoDbManager.php
And change config

```php
$config = [
	...
	'components' => [
		...
		'mongodb' => [
            'class' => '\yii\mongodb\Connection',
            'dsn' => 'mongodb://localhost:27017/dbname',
        ],

        'authManager' => [
            'class' => 'yii\rbac\MongoDbManager',
            'defaultRoles' => ['guest'],
        ],
		...
	],
	...
];
```

**Comment by klimov-paul** [comment]
Resolved by
https://github.com/yiisoft/yii2-mongodb/pull/110
