### ISSUE TITLE
Gii extension generator enhancements

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#2555]
continued from https://github.com/yiisoft/yii2/pull/2411#issuecomment-35986454

- [ ] LICENSE file creation with license content
- [ ] Optional "root" directory. Now in composer.json namespace is relates to "". It is not always convenient, especially when your have many files like CHANGELOG.md, README.md, LICENSE, composer.json, composer.lock, .gitignore, .travis.yml, .scrutinizer.yml, helpers for IDE, test environment, etc. In NodeJS usually used "lib" directory, in C++ "src". Yii2 extensions could use something like that.
- [ ] Optional tests directory structure: phpunit or codeception
- [ ] Additional types (yii2-application, yii2-theme, freetext?)
- [ ] Custom licenses (freetext?)

**Comment by Faryshta** [comment]
shouldn't @yii-bot close this and pass it to gii?

**Comment by samdark** [comment]
I think there's nothing to be done about it.
