### ISSUE TITLE
Non-strict asset bundle dependencies

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#2618]
Currently it's not possible to conveniently handle the following:

```
page1
  bundleA
page2
  bundleB
page3
  bundleA
  bundleB
```

In the above `bundleB` can be used without `bundleA` but when both are used `bundleA` has priority and its assets should be registered before assets of `bundleB`.

It can be solved by intoroducing non-strict dependencies that are taken into account if both bundles are registered but do not trigger bundle registration itself.

What do you think?

**Comment by klimov-paul** [comment]
Such situation is unlikely to happen.
Still if appears it can be easily resolved via extra asset bundle creation. You will need to declare some `BundleAB`, which will be empty itself, but will have `depends` specified in correct order:
```php
class BundleAB extends AssetBundle
{
    public $depends = [
        'BundleA',
        'BundleB',
    ];
}
```
