### ISSUE TITLE
[PROPOSAL] berkeley DB & Amazon  Dynamo DB

### ISSUE THREAD

**Issue by gimox** [yiisoft/yii2#2626]
Anyone use this db.
They are NOSQL intensive data db, used specially for logging ( mongo is somethink more commercial).

I like if there was a official extension for yii2.

**Comment by dynasource** [comment]
nice to have. Feel free to do a PR.

**Comment by samdark** [comment]
I'd prefer these as extensions.

**Comment by dynasource** [comment]
agreed. Feel free to create an yii2 extension.
