### ISSUE TITLE
Provide HttpClient

### ISSUE THREAD

**Issue by iodragon** [yiisoft/yii2#2953]
There is a similar issue of yii (https://github.com/yiisoft/yii/issues/313), not update for one year.

I find a simple wrapper of curl in authclient/BaseOAuth.php,  any further plan for a HttpClinet described in that issue ?

**Comment by hightman** [comment]
@DaSourcerer Whether to consider use PHP built-in functions, such as `file_get_contents()` or other stream wrappers. It can support any kinds of HTTP request by customizing the third parameter.

I think this seems lightweight and efficiently without cURL requires.  At least, I hope it can be included as an option.

**Comment by klimov-paul** [comment]
Draft implementation created at:
https://github.com/klimov-paul/yii2-httpclient

@yiisoft/core-developers, I need someone create a corresponding repository under 'yiisoft', so I can push this code there.
After it is done, we may procced to further disscussion inside it.

**Comment by zelenin** [comment]
@klimov-paul dumb question but... Is PSR-7 compatible? ) async? Cookie support?

**Comment by klimov-paul** [comment]
> Is PSR-7 compatible?

What do you mean?

> async?

Only in case of `TransportCurl` usage.

> Cookie support?

Yes, both ways: for the request and for the response.

**Comment by takobell** [comment]
@klimov-paul http://www.php-fig.org/psr/psr-7/

**Comment by klimov-paul** [comment]
no

**Comment by zelenin** [comment]
The word "bicycle" used in the English? Because Guzzle is.
It's big work but useless I think.

**Comment by samdark** [comment]
There have to be advantages over existing implementations in order to have it in framework. If there are none, it's better to create an interface or document officially about which HTTP client to use.

**Comment by samdark** [comment]
@klimov-paul https://github.com/yiisoft/yii2-httpclient

**Comment by klimov-paul** [comment]
Thanks, @samdark.

**Comment by klimov-paul** [comment]
I need 'httpclient' one way or another in order to refactor https://github.com/yiisoft/yii2-authclient to solve multiple issues related to this functionality such as https://github.com/yiisoft/yii2-authclient/issues/27 and https://github.com/yiisoft/yii2-authclient/pull/33

**Comment by klimov-paul** [comment]
@samdark, it seems I don't have a permsissions for writing the `yiisoft/yii2-httpclient`. Please check the permissions schema.

**Comment by samdark** [comment]
@klimov-paul I don't have enough permissions :( @qiangxue need your assistance.

**Comment by qiangxue** [comment]
Not sure why, since samdark is an admin.  I added the core rev team to this repo anyway.

**Comment by klimov-paul** [comment]
OK, I have filled up the repository.
Still I have no access to its settings and thus unable to setup any web hook - Travis should be enabled at least.

I'll keep this issue open, since it could be we actually will deny this feature in the end.
Issue can be closed after 'yii2-httpclient' will have the first stable release.

**Comment by samdark** [comment]
Added travis.

**Comment by samdark** [comment]
Personally I think that PSR-7 is quite a good writing and could actually be a good guideline for HTTP clients i.e. we can have an interface in the code and implementation in extension like we do for mailer.

**Comment by armpogart** [comment]
Maybe instead of separate extension use [HTTPlug](https://github.com/php-http/httplug) in core as client interface and leave the choice of library used on developer?

**Comment by klimov-paul** [comment]
`yii2-httpclient` released:
https://github.com/yiisoft/yii2-httpclient
