### ISSUE TITLE
Performance problem when reading bigger amount of rows with joined table

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#3072]
Running query to read a large amount of data results in huge differeces in speed depending on the strategy you're using. 
The following 6 examples runs against table tblrechnung with about 4000 rows and a related table tblrechpos with about 5500 rows. 

``` php
$test1 = Rechnung::find()->all();
$test2 = Rechnung::find()->with('rechpos')->all();
$test3 = Rechnung::find()->joinWith('rechpos')->all();
$test4 = Rechnung::find()->with('rechpos')->asArray()->all();
$test5 = Rechnung::find()->joinWith('rechpos')->asArray()->all();
$test6 = (new \yii\db\Query())
    ->from('tblrechnung r')
    ->innerJoin('tblRechpos p', 'p.re_lfd = r.re_lfd')
    ->all(); 
// test7 - retrieve data in batches 
 foreach (Rechnung::find()->with('rechpos')->each(100) as $row) {
// and that's the only logic executed to run thru the result set 
foreach ($testn as $row) {
    $counter1 ++;  
     $counter2 += count($row['rechpos']);
}
```

| Test | Time | Memory | DB calls | DB time | comment |
| --- | --: | --: | --: | --: | --- |
| 1 | 8200 | 69.6 | 4115 | 1667 | Huge amount of db calls |
| 2 | 4950 | 56.5 | 9 | 680 | with() reads rechpos only once |
| 3 | 6320 | 61.1 | 9 | 1040 | Surprise! Why is joinwith() so expensive? |
| 4 | 2230 | 40.6 | 5 | 697 | No creation of class instances saves a lot of execution time |
| 5 | 2232 | 45.1 | 7 | 718 | joinwith() costs only a bit of memory. Compare with example 3. |
| 6 | 310 | 37.8 | 4 | 116 | Why is pure SQL so fast compared to examples 4 + 5? You just get a bit different array structure. |
| 7 | 3390 | 13.3 | 50 | 117 | Batch saves memory, not time. |

I wonder why preparing an array as in example 4 and 5 is so much slower than in example 6. 

Is there a way to use active record with something similar to asArray() but with same functionality (and speed)  as in example 6?

Why is example 3 so slow compared to example 2?

**Comment by m8rge** [comment]
I recommend @twinni use xhprof to profile code.

**Comment by dynasource** [comment]
this benchmark is expired. Please feel free to redo benchmarks with the current state of the software.
