### ISSUE TITLE
possibility to show all error messages in activeForm

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#3087]
current implementation of client and server validation only show the first error message for an input. We have already control for this in model when setting `skipOnError` so if I set `skipOnError` in model I expect the error message to appear in the form.

It should be possible to configure/enable this behavior in ActiveForm.

**Comment by thiagotalma** [comment]
Any news here?
It does not make sense to show only the first error...

**Comment by thiagotalma** [comment]
@cebe @qiangxue  @samdark 

What do you think about creating an option to catch all errors that way?

helpers\BaseHtml.php
```PHP
public static function errorSummary($models, $options = [])
{
    $header = isset($options['header']) ? $options['header'] : '<p>' . Yii::t('yii', 'Please fix the following errors:') . '</p>';
    $footer = ArrayHelper::remove($options, 'footer', '');
    $encode = ArrayHelper::remove($options, 'encode', true);
    unset($options['header']);

    $onlyFirst = isset($options['onlyFirst']) ? $options['onlyFirst'] : true;
    unset($options['onlyFirst']);

    $lines = [];
    if (!is_array($models)) {
        $models = [$models];
    }
    foreach ($models as $model) {
        /* @var $model Model */
        if ($onlyFirst === true) {
            $errors = $model->getFirstErrors();
        } else {
            $errors = [];
            $allErrors = $model->getErrors();
            array_walk_recursive($allErrors, function ($error) use (&$errors) {
                $errors[] = $error;
            });
        }
        foreach ($errors as $error) {
            $lines[] = $encode ? Html::encode($error) : $error;
        }
    }

    if (empty($lines)) {
        // still render the placeholder for client-side validation use
        $content = '<ul></ul>';
        $options['style'] = isset($options['style']) ? rtrim($options['style'], ';') . '; display:none' : 'display:none';
    } else {
        $content = '<ul><li>' . implode("</li>\n<li>", $lines) . '</li></ul>';
    }
    return Html::tag('div', $header . $content . $footer, $options);
}
```

**Comment by samdark** [comment]
How about client validation?

**Comment by samdark** [comment]
From the usability point of view it may be not desired to show all errors at once for the field.

**Comment by thiagotalma** [comment]
> From the usability point of view it may be not desired to show all errors at once for the field.

So it's a non-default option.

**Comment by Faryshta** [comment]
```php
$onlyFirst = ArrayHelper::remove($options, 'onlyFirst', false);
```

**Comment by nestorvanz** [comment]
Why this framework let you add many of errors with `addErros($array)` function if only will show one?
I have the same problem, I'm doing n validations for passwords and can't display all the errors found in validator.

**Comment by Faryshta** [comment]
Why was this moved to 2.1.x? this is not bc-break

**Comment by cebe** [comment]
no idea, could be in 2.0.x if it is configurable and default behavior does not change.

**Comment by developeruz** [comment]
@samdark It seems that this issue can be closed because `$showAllErrors` was introduced in #12193

**Comment by samdark** [comment]
Indeed. Thanks for pointing it out.

**Comment by cebe** [comment]
this is not about errorSummary but about inputs in activeform.
