### ISSUE TITLE
Create a demo module

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#3146]
There should be a demo section to illustrate different UI elements and their options. This was one of the frequently requested features in Yii 1.

Some thoughts:
- Make it an extension module to have the examples available locally if desired
- Host it somewhere on the yii site
- Examples should show source code, created HTML markup and rendered result
- Markdown would be nice, but we may need a customized version to help with PHP code integration

As an example, here's something we've built before our ActiveForm was integrated to yii2-bootstrap:

http://codemix.github.io/yii2-bs3activeform/

It's still missing a good way to organize the code snippets, though.

**Comment by dynasource** [comment]
how to organize a module really depends on what you want to do with, really. There are many implementations thinkable. For those who want to have inspiration, take a look at different Yii modules at https://github.com/yiisoft, like:
* https://github.com/yiisoft/yii2-gii
* https://github.com/yiisoft/yii2-debug

If you want info about how a structure could be setup, please take a look at the guide http://www.yiiframework.com/doc-2.0/guide-structure-modules.html
