### ISSUE TITLE
Fetching CLOB data with Query on Oracle 11g

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#3167]
I'm having trouble figuring out how do I indicate a CLOB type for one of the columns in a SELECT query. Ignoring that returns the data as a Resource - how do we actually get to its underlying data?

stream_get_contents($data) actually retrieves the data, but it produces weird results - e.g. if I loop the query results, and read the CLOB data using stream_get_contents(), the data from the last row of the result set is read everywhere.

**Comment by fdo36** [comment]
@wenbin1989 that solution will handle the clobs as varchar2(4000). It's useless when you are facing datas that MUST be inserted in a CLOB column (like a TEXT in MySQL). 

the bugs is still on

**Comment by pedroip** [comment]
https://www.php.net/manual/es/function.oci-fetch-array.php

`$result = oci_fetch_array($this->_sth, OCI_BOTH + OCI_RETURN_NULLS + OCI_RETURN_LOBS );`

**OCI_RETURN_LOBS** | Devuelve el contenido de los LOB en lugar de los descriptores de los mismos.

**Comment by bizley** [comment]
Closing. Anyone looking for a workaround solution will be pointed here by a search engines.
