### ISSUE TITLE
RBAC: cache items

### ISSUE THREAD

**Issue by evgen-d** [yiisoft/yii2#3168]
Caching auth items and etc.
Discussion - #3166

**Comment by RomeroMsk** [comment]
@cebe wrote:
> Another use case for calling checkAccess() multiple times is building a navigation where most of the links need permission check to ensure user is allowed to access the corresponding action.
> Current implementation I have results in about 100 db queries to build the navigation.

What about this case? Why not to cache assignments in memory to avoid duplicated queries in one request? I understand, why we can't use cache engine for this by default, but saving results of `SELECT * FROM auth_assignment WHERE user_id='...'` in instance is must have: now Yii2 generates this query N times for N `Yii::$app->user->can()` calls on the page (when building navigation, for example).
