### ISSUE TITLE
Handling multiple models with a single form

### ISSUE THREAD

**Issue by marciocamello** [yiisoft/yii2#3306]
Possible use in actionCreate?

```php
public function actionUpdate()
    {
        $settings = Setting::find()->indexBy('id')->all();

        if (Model::loadMultiple($settings, Yii::$app->request->post()) && Model::validateMultiple($settings)) {
            foreach ($settings as $setting) {
                $setting->save(false);
            }

            return $this->redirect('index');
        }

        return $this->render('update', ['settings' => $settings]);
    }
```

**Comment by githubjeka** [comment]
Probably It can will be closed.

https://github.com/yiisoft/yii2/blob/master/docs/guide/input-multiple-models.md

**Comment by sieulog** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/input-multiple-models.md

This document don't have example with create new.

**Comment by StagnantIce** [comment]
What about dinamic count of each model? It is posible?

**Comment by cebe** [comment]
@sieulog @StagnantIce please open new issues for this including more detailed description about your case.

**Comment by StagnantIce** [comment]
In controller:

    public function actionCreate()
    {
        $model = new LearnQuestion();
        // http://www.yiiframework.com/doc-2.0/guide-input-tabular-input.html
        $count = count(Yii::$app->request->post('LearnQuestionPart', []));
        $partModels = [new LearnQuestionPart()];
        for($i = 1; $i < $count; $i++) {
            $partModels[] = new LearnQuestionPart();
        }
        $post = Yii::$app->request->post();
        if ($model->load($post) && Model::loadMultiple($partModels, $post) && $model->save()) {
            $error = false;
            foreach ($partModels as $partModel) {
                $partModel->question_id = $model->id;
                if (!$partModel->save()) {
                    $model->delete();
                    $error = true;
                    break;
                }
            }
            if (!$error) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('create', [
            'model' => $model,
            'partModels' => $partModels
        ]);
    }

In view:

			<? foreach($partModels as $index => $partModel): ?>
			<tr>
				<td>
				    <?= $form->field($partModel, '['.$index.']description')->label(false)->textInput();?>
				</td>
				<td>
		    		<?= $form->field($partModel, '['.$index.']answer')->label(false)->checkbox([], false);?>
		    	</td>
		    </tr>
		    <? endforeach; ?>

$(function(){

    $.fn.addRow = function() {
        var $table = $('table tbody', $(this));
        var $tr = $table.find('tr:last');
        var index = $table.find('tr').length - 2;
        var rowHtml = $tr.html().replace(/LearnQuestionPart\[\d+\]/, "LearnQuestionPart[" + (index + 1) + "]");
        $table.append('<tr>' + rowHtml + '</tr>');
    }
});

Not user friendly.
