### ISSUE TITLE
How to use across subdomains

### ISSUE THREAD

**Issue by marciocamello** [yiisoft/yii2#3411]
How to use across subdomains? with advanced application, I tried this way 

/common/main-local.php

``` php
'session' => [
     'savePath' => '\mypath\common\session',
     'cookieParams' => [
           'path' => '/',
          'domain' => '.mydomain.com',
     ]
],
'user' => [
     'identityClass' => 'common\models\User',
     'enableAutoLogin' => true,
     'identityCookie' => [
          'name' => '_mydomain',
          'domain' => '.mydomain.com',
          'path' => '/',
     ]
],
```

This example for 
mydomain.com
submain1.mydomain.com
subdomain2.mydomain.com
etc

All applications, need get user sessions/cookies, etc.

Any idea?

**Comment by robregonm** [comment]
I also tried this setup but It worked again when I removed the `session` block.

**Comment by m0zhgan** [comment]
i add this code and i can login to subdomains of site but cant login to site.
 for example i login to submain1.mydomain.com but cant login to mydomain.com

**Comment by Sammaye** [comment]
Use different identifiers for the cookies in session component

**Comment by m0zhgan** [comment]
i need to login in both backend and frontend so i cant use different identifiers for the cookies in session component

**Comment by Sammaye** [comment]
If I remember right I used the same PHPSESSID but different Yii cookie
names and it worked

**Comment by dynasource** [comment]
issue seem to be solved
