### ISSUE TITLE
GII CRUD: flash messages after actions

### ISSUE THREAD

**Issue by lucianobaraglia** [yiisoft/yii2#3428]
I think it would be nice having flash messages in crud after common actions were performed.
For example, after deleting something, I would expect to read: "The item was successfully deleted", and after creating or updating: "The item was created/updated successfully".

Or something like that.

**Comment by lukBarros** [comment]
Ok the idea seems very good , I manually do it in my projects.

As I have familiarity with gii and made a simple extension that helps you in it to the core do it for you .

https://github.com/lukBarros/legba-gii

I will try to work it in the appropriate design for such it is:

https://github.com/yiisoft/yii2-gii

Keep informed if progress in this encoding.

**Comment by pana1990** [comment]
duplicated https://github.com/yiisoft/yii2-gii/issues/26

**Comment by samdark** [comment]
@pana1990 thanks!
