### ISSUE TITLE
FileMutex is not reliable

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#3460]
Just implemented a cron script that should only run in one instance at a time.
Simple command:

```php
class ReportController extends Controller
{
	public function actionIndex()
	{
		$mutex = new FileMutex();
		if (!$mutex->acquire('cron.reports')) {
			echo "lock exists, exiting\n";
			return 1;
		}

		sleep(10);

		$mutex->release('cron.reports');
		echo "done.\n";
	}
}
```

I can run many processes in parallel on my system without the lock preventing it.

Citing the flock docs: http://php.net/manual/en/function.flock.php

> On some operating systems flock() is implemented at the process level. When using a multithreaded server API like ISAPI you may not be able to rely on flock() to protect files against other PHP scripts running in parallel threads of the same server instance!

**Comment by samdark** [comment]
It was already handled by @klimov-paul in 9e320da.
