### ISSUE TITLE
Yii2 - Bootstrap Tabs

### ISSUE THREAD

**Issue by mar22** [yiisoft/yii2#3502]
When I try disabled tab to click

<code>'linkOptions'=>['class'=>'disabled','data-toggle'=>""]</code>

data-toggle is override in Tabs class. I think that there should be

<code>
if(!isset($linkOptions['data-toggle'])){
                        $linkOptions['data-toggle'] = 'tab';
}
</code>

**Comment by samdark** [comment]
Fixed by https://github.com/yiisoft/yii2-bootstrap/pull/92
