### ISSUE TITLE
Add IP validator

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#3506]
I think it would be useful to add `ip` validator. Possible solution is provided by @samdark in this [gist](https://gist.github.com/samdark/3752870).

**Comment by SilverFire** [comment]
will do

**Comment by SilverFire** [comment]
Have a question to dispute. The core of the validator should be a `filter_var` or regex-based. 
Here is a benchmark http://3v4l.org/T4mko and it shows that `filter_var` is up to 3 times faster than regex, so decision for PHP is obvious. But what about client-side JS validation? There is not `filter_var` or something like that, except external libraries to validate IP address, which is really unreasonable. May I use regexp to validate client-side and `filter_var` to validate server-side?

**Comment by cebe** [comment]
@SilverFire to ensure client and server side work the same I think they should both use the same regex.

**Comment by SilverFire** [comment]
4e2fde1 is the first version without JS validation yet. Your thoughts?

**Comment by samdark** [comment]
Could be useful to be able to specify range of IPs accepted such as https://gist.github.com/samdark/3752870

**Comment by SilverFire** [comment]
@samdark yes, it's the next step. Want to add options to do something like `$range = ['accept' => ['192.168.1.0/24'], 'except' => ['192.168.5.0/28]]`.

**Comment by cebe** [comment]
I think it would be better to have two properties: `$acceptRange` and `$excludeRange` sub array configuration is uncommon in yii.

**Comment by SilverFire** [comment]
Currently I have a problem with calculation of IPv6 as a result of int length limitation in PHP.

Here is a part of code: https://gist.github.com/SilverFire/d03d7f6cc132fcd16680
Does anybody have a good workaround to calculate IPv6 mask?

**Comment by samdark** [comment]
https://stackoverflow.com/questions/7951061/matching-ipv6-address-to-a-cidr-subnet

**Comment by SilverFire** [comment]
New changes in commit 243eb11 

There is a debatable test case on `IpAddressValidatorTest.php:117`
```
$validator->allowedRanges = ['10.0.1.0/24'];
$this->assertTrue($validator->validate('10.0.1.1/22')); // bad test
```

When the validating value is a subnet, do we need to check, whether the subnet belongs to the other subnet?
