### ISSUE TITLE
Query Builder not quoting table names correctly (?)

### ISSUE THREAD

**Issue by rawtaz** [yiisoft/yii2#3533]
The code `$rows = (new Query())->select('[[Item Name]]')->from('{{Foo Bar}}')->all();` correctly quotes the column name, but not the table name. The resulting query is `SELECT "Item Name" FROM {{Foo "Bar}}"`, instead of the expected `SELECT "Item Name" FROM "Foo Bar"`.

Manually quoting the table name works; `$rows = (new Query())->select('[[Item Name]]')->from('"Foo Bar"')->all();` yields `SELECT "Item Name" FROM "Foo Bar"`.

I take it this is not intentional?

**Comment by dynasource** [comment]
expired. Please notify if somebody encounters this again.
