### ISSUE TITLE
Multiple update: set scenario

### ISSUE THREAD

**Issue by pavlinter** [yiisoft/yii2#3602]
<pre>
if (Yii::$app->request->isPost) {

    foreach ($models as $model) {
        $model->scenario = 'massUpdate';
    }
    if (Model::loadMultiple($models,Yii::$app->request->post()) && Model::validateMultiple($models)) {
        foreach ($models as $model) {
            $model->save(false);
        }
        return $this->refresh();
    }
}
</pre>

I worry about this code. Unnecessary loop.

<pre>
    foreach ($models as $model) {
        $model->scenario = 'massUpdate';
    }
</pre>

Maybe existence other way? If not, I offer add new parameter!

<pre>
Model::loadMultiple($models,Yii::$app->request->post(),'massUpdate');
</pre>

**Comment by dynasource** [comment]
duplicate https://github.com/yiisoft/yii2/issues/12015#issuecomment-257305514
