### ISSUE TITLE
registerJs code depends or Widget Event

### ISSUE THREAD

**Issue by pavlinter** [yiisoft/yii2#3657]
My inputWidget work with $.fn.yiiActiveForm and widget init between
ActiveForm::begin and ActiveForm::end().
I need registerJs code init after  jQuery('#w0').yiiActiveForm({.....

I can set 

<pre>
$view->registerJs("jQuery('" . $btn . "')....",View::POS_LOAD);
</pre>

or
create own ActiveForm only for init js code after $.fn.yiiActiveForm

Maybe can add Widget Event? ( Widget::AFTER_RUN )

**Comment by dynasource** [comment]
if one wants to have specific order in which JS is to be called, he should follow the dependency mechanism. This could mean that you have to create an asset for every single JS and connect them with the use of $depends.
