### ISSUE TITLE
Best practice for using $form->field($model, 'fieldname')->checkboxList with relations models

### ISSUE THREAD

**Issue by tamvodopad** [yiisoft/yii2#3660]
I have two models:
- Posts
- Categories

All posts are may have more categories. 

In Post edit view file i'm used this code:

<?= $form->field($post_categories, 'category_id')->checkboxList(ArrayHelper::map($categories, 'id', 'title')) ?>

Where $post_categories - Categories model

How i can pre-select categories for edited post?

if i used this code, we see pre-seleceted data not correct:
<?= $form->field($model, 'postCategories')->checkboxList(ArrayHelper::map($categories, 'id', 'title')) ?>

where postCategories is a relation data model for Post 

I have not found the proper use checkboxList with related models in documentation.

**Comment by thassan** [comment]
related discussion, with useful code in posts 10 and 11
http://www.yiiframework.com/forum/index.php/topic/52592-handling-many-to-many-relation/

**Comment by KrunalHingu** [comment]
Hello friends, i am new in Yii. anybody please guide me ? i want  put check boxes with all users email id. whole code is as under:
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\widgets\DatePicker;
use app\models\User;
use kartik\file\FileInput;
use kartik\widgets\Select2;
use dosamigos\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model app\models\News */
/* @var $form yii\widgets\ActiveForm */

$user = User::find()->all();

 
?>

<div class="news-form">

    <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]);?>
     
     
     
  <?php  $form->field($model, 'user_id')->checkBoxList() ?>
    <?= $form->field($model, 'message')->textInput(['maxlength' => 500]) ?>
      <?= $form->field($model, 'mail_from')->textInput(['maxlength' => 500]) ?>

    <?= $form->field($model, 'mail_body')->widget(CKEditor::className(), [
           'options' => ['rows' => 6],
           'preset' => 'full',
		    
       ])?>
 
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Send' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

**Comment by antonior14** [comment]
Hi guys!
I'm trying to build a web application with yii2

I would to manage Category and CategoryDescription (using category_id as an 1:N).
How can I create it using both select list and text field in a related form with ActiveForm or what you suggest?

Thank you very much

**Comment by dynasource** [comment]
this is quite clear http://www.yiiframework.com/doc-2.0/yii-bootstrap-activefield.html#checkboxList()-detail

Feel free to do a PR if you want to further improve @docs on this.

**Comment by calepsol** [comment]
How to add the default value in widget CKEditor?
