### ISSUE TITLE
pjax 更新时引入js css 文件问题

### ISSUE THREAD

**Issue by pk8est** [yiisoft/yii2#3680]
1、pjax.js 获取到后台数据后，用 jqery.parseHTML 对数据进行了解析，
其中，context 包括 后台返回的body与及 不包括src属性的script标签(比如：jQuery('#w1').yiiGridView(...))；scripts包括有src属性的script标签(如 jqery.js, yii.js, yii.gridView.js)。
2、把context的内容插入到要更新的容器内
3、把scripts内的文件插入到document.head（已经加载过的会过滤掉）
4、因为第3步在第2步后面执行，导致第2步时context 中的代码找不到第3步中要加载的文件（虽然js代码都是放在jQuery(document).ready(...) 内，但因为这是通过ajax请求内容，返回内容后ready已经生效，而我们的页面是通过js插入页面的。所以在插入的同时会触发所有在ready内的代码，我是这样想的，不知道对不对）。
比如：先加载 jQuery('#w0').yiiGridView(...)，然后才是加载 yii.gridView.js，
最后导致TypeError: jQuery(...).yiiGridView is not a function.
5、而且。因为是异步的问题，就算第3步比第2步先执行，也有可能出现上述问题

**Comment by leeyawen** [comment]
what ？

**Comment by lynicidn** [comment]
@samdark так и есть, что при рендере pajax вернутся и скрипты, просто обработчики надо вешать на https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php#L86
т.е. ты получаешь контент и к нему обработчики, а live кстати надо проверить, по идее он должен обрабатывать контент

**Comment by llfm** [comment]
I could only understand some part of @qiansen1386 said. But maybe this is related to this [issue](https://github.com/yiisoft/yii2/issues/6655)

**Comment by leeyawen** [comment]
匪夷所思

**Comment by leeyawen** [comment]
值得学习  ，顶

**Comment by SilverFire** [comment]
Хлопці, що тут коїться? :laughing:

**Comment by SilverFire** [comment]
Duplication in #8616, #8540, #4814, #6655

**Comment by SilverFire** [comment]
Should be fixed by https://github.com/yiisoft/jquery-pjax/pull/30
