### ISSUE TITLE
Error on queryOne after execute

### ISSUE THREAD

**Issue by karlex** [yiisoft/yii2#3695]
When I run the following code:
```php
$db = \Yii::$app->getDb();
$cmd = $db->createCommand('SET @tmp1 = 1; SET @tmp2 = 2;');
$cmd->execute();

$result = $db->createCommand('SELECT @tmp1, @tmp2;')->queryOne();
```
I get the error:
> SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
The SQL being executed was: SELECT @tmp1, @tmp2;

But when I use:
```php
$db->createCommand('SET @tmp1 = 1; SET @tmp2 = 2;')->execute();
```
or
```php
$cmd = $db->createCommand('SET @tmp1 = 1;')
$cmd->execute();
$cmd = $db->createCommand('SET @tmp2 = 2;')
$cmd->execute();
```
It works fine.

**Comment by klimov-paul** [comment]
I am unable to reproduce this.
Perhaps this issue depends on particular version of PDO or MySQL.
@karlex, try to adjust `Command::execute()` code manually adding `$this->pdoStatement->closeCursor()`. Does it solves your problem?

**Comment by klimov-paul** [comment]
Closed, since there is no response from the author.
