### ISSUE TITLE
ActiveForm ajaxValidation stops working when the page is not reloaded after posting the form

### ISSUE THREAD

**Issue by sieppl** [yiisoft/yii2#3726]
Scenario:
- enableAjaxValidation:true,
- enableClientValidation:false
- form submit is handled by own jquery, e.g.

```
    $(document).on('submit', '#my-form', function(event) {
        var $form = $(this);

        $.ajax( {
            type: 'POST',
            data : $form.serialize(),
            async: false,
            cache : false,
            dataType:'json',
            success : function(data) {
                    ...
            }
        });
        event.preventDefault();
    });
```

When the form is submitted, in yii.activeform.js is storing the state "submitting" in a data field. After this the submitting state remains and due to this all further attributes changes are triggered, but not handled, because the submitting states prevents this.

My current workarround is to do this in the $.ajax.success callback:
```
$('#my-form').data().yiiActiveForm.submitting = false;
```

I think resetForm should also reset states like submitting, shouldn't it?

**Comment by SilverFire** [comment]
Currently works as expected
