### ISSUE TITLE
Activeform, multiple models with same name attributes not validating via ajax

### ISSUE THREAD

**Issue by Nafania** [yiisoft/yii2#3794]
I have activeform for multiple models with ajax only validation.
There two models which have same name attributes, i.e

```
class Model1 extends Model {
public $id;
}

class Model2 extends Model {
public $id;
}

```

and form 

```
echo $form->field($model1, '$id')->textInput();
echo $form->field($model2, '$id')->textInput();
```

Generated code of Activeform use field name as key for attributes, i.e.

```js
jQuery('#some-form').yiiActiveForm({"pk":{"enableAjaxValidation":1,"id":"model1-pk","name":"pk","validateOnChange":true,"validateOnType":false,"validationDelay":200,"container":".field-model1-pk","input":"#model1-pk","error":".help-block"},
```

so second model will not be validated, cause it has same property name.

Suggest:
use full field name including model name as key, so all attributes will be in attributes hash of yiiActiveForm and all be validated correctly.

**Comment by dynasource** [comment]
this issue will be closed because of its age, few stakeholders and the absence of progress. Please do a vote if you want it to be reopened again.

**Comment by Erebril** [comment]
is there any workarround?

**Comment by cebe** [comment]
@Erebril please create a new issue describing the problem in more detail. I do not get the issue from what is described here.
