### ISSUE TITLE
No Activeform Validation on using Fragment Caching

### ISSUE THREAD

**Issue by dilip-vishwa** [yiisoft/yii2#3802]
This is my view, In this I have used Fragment Cache with enabled.

``` php
$id = 't';
$this->registerJs(" alert('asdfgh'); ", View::POS_READY, "showloc");
if ($this->beginCache($id, ['enabled' => Yii::$app->request->isGet])) {
    $form = ActiveForm::begin([
                'id' => 'event-form',
                'enableClientValidation' => true,
                'enableAjaxValidation' => false,
                'validateOnSubmit' => true,
                'validateOnChange' => true,
                'validateOnType' => true,
                'validationDelay' => 500,
    ]);
    echo $form->field($model, 'name')->textInput(); ?>
        <?php echo $form->field($model, 'rules')->textarea(); ?>
    <div class="btn-toolbar">
        <button type="submit" class="btn btn-primary">Event</button>
    </div>
    <?php
    ActiveForm::end();
    $this->endCache();
}
?>
```

On the first load, the validation works. But after next reload, the validation doesn't work.
The form gets submitted succesfully.
Only the problem of validation is there.
Checked the console for any error, but there is no js error.
All other js code in the page works fine.
After submitting wrong form, It shows validation error for that field.
That means client side validation is not working.

**Comment by tongtoanbs** [comment]
is there any way solve this issue?

**Comment by samdark** [comment]
Could be related to https://github.com/yiisoft/yii2/pull/12145

**Comment by dynasource** [comment]
in the current architecture, you cannot expect widgets 
* to run, and at the same time, not to run.

Either you cache the whole page with the assets in place, or you cache he small parts. That is whats supported at the moment. 

If you want to solve this issue yourself. 
As it is your choice not to execute the asset registering of the widget. you should manually load the assets, outside the fragments.
