### ISSUE TITLE
rest api login

### ISSUE THREAD

**Issue by appcodr** [yiisoft/yii2#3808]
Hi,

I am starting to use yii2 and I am providing a REST Api from the web app.  I could not find any documentation on how to provide login functionality using yii2 REST api. Previously in yii, we used to have an action called actionLogin which takes in a username and password and authenticate it(with User model). Is that the same approach still with yii2? Like in UserController have an actionLogin method with GET request type and once authenticated successfully return User object(with access token for subsequent calls?) ?

**Comment by SamMousa** [comment]
http://www.yiiframework.com/doc-2.0/guide-rest-authentication.html

This can be closed.
