### ISSUE TITLE
BindingFormat

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#3973]
i think is necessary to create the databinding concept.

My idea is something like:

``` php
class Order extends Model {

    public $date;
    public $total;

    public function bindingFormats()
    {
        return [
            'date' => ['format' => 'dd/mm/yyyy', 'dataType' => 'date'],
            'total' => ['format' => '0,00', 'dataType' => 'float']
        ];
    }

}
```

on load attributes should consider this configuration to converter the value.

reference: http://grails.org/doc/latest/guide/theWebLayer.html#dataBinding

**Comment by dynasource** [comment]
we should not do this for performance reasons. Yii's magic functions are one of the mostly called functions in the application and type casting is rarely necessary. If you want values to be casted correctly, you can do this on the fly.

**Comment by dynasource** [comment]
or use http://www.yiiframework.com/doc-2.0/yii-behaviors-attributetypecastbehavior.html

**Comment by joeyblack835** [comment]
Guys, sorry for such a late commenting. Just found this post.
Many times in the comments it is mentioned that the proposed method isn't the responsibility of AR.
Probably, you are right.
But isn't it you (developers of this wonderful framework), who opened the Pandora's box, making validation the responsibility of AR? Now we are trying to fit anything into this model. That's how I see what's happening. Or did I miss something?
I will be grateful for the answer. Thanks.

**Comment by Ragazzo** [comment]
@joeyblack835 whats your question? :) you can use form models to validate input data, not needed to put every validation to AR

**Comment by joeyblack835** [comment]
@Ragazzo Thank you for the reply. The question is about a better practice. Where should we do validation, filtering, type casting, converting SQL values to form values (if they differ) and back, etc.? Should we do this in AR or somewhere else? I'm not asking where we should do this in principle, but in Yii only.
Sorry for referencing your "not a responsibility of AR" again.

**Comment by Ragazzo** [comment]
@joeyblack835 validation should be done in form models, AR only responsibility here is to keep data consistency in terms of database. I think it is covered somewhere in Yii guides, you can ask @samdark for a link

**Comment by joeyblack835** [comment]
@Ragazzo thank you so much for your reply. I will contact @samdark. Just a small remark. Talking about the separation of responsibilities between form models and active records in the context of the Yii is not entirely correct. All guides, as well as a Yii book, contain examples where the active records are form models. With exceptions when there is no database table for a form or a form is complex. @samdark would you be so kind to judge us. It will be enough to read 4 comments above to understand the essence of the matter.
Please tell me if it is better to create a new issue.

**Comment by samdark** [comment]
Using separate form models is fine if it makes sense. I have no objections doing so.

**Comment by joeyblack835** [comment]
@samdark Thank you so much for clarification.
