### ISSUE TITLE
Skeleton application: a fully fledged skeleton suitable for big applications

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii2#40]
The skeleton should contain multi-tier directory structure (something similar to http://www.yiiframework.com/wiki/155/the-directory-structure-of-the-yii-project-site).

It should contain tools supporting environment switching, deployment, etc.

It should contain a ready-to-use backend, and a nearly empty frontend.

TODO:

- [x] rename `backstage` → `backend`

**frontend**

- [ ] Login/signup via Facebook (extension?)
- [x] Signup.
- [x] Password reset.

**backstage**

- [ ] Backstage layout.
- [ ] RBAC-controller controller permissions.
- [ ] Ability to generate frontend URLs.
- [ ] Error log viewer.

**console**

- [ ] Ability to generate frontend URLs.

**Comment by schmunk42** [comment]
Just adding this one for reference https://github.com/dmstr/yii2-adminlte-asset

**Comment by tsvetkovpro** [comment]
Что с этим вопросом ? никак не пойму почему не закрывают баг?

**Comment by samdark** [comment]
It's more or less done. Closing since it's a meta-issue.
