### ISSUE TITLE
At exception page links to private methods are generated while these aren't in API docs

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#4113]
For example,

http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#removeDuplicatedModels%28%29-detail

**Comment by dynasource** [comment]
@samdark, this is from 2014. Is it solved already?

**Comment by samdark** [comment]
No. Here it is: https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L209
