### ISSUE TITLE
Menu widget enh. pass item as raw text

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#4128]
It would be great to have ability to pass an item in menu as simple raw text or html, currently all items need to be arrays and this cant be done with it. The use-case is for using `yii\widgets\Menu` widget with custom input like dropdowns and other (bootstrap was not chosen as a solution).

**Comment by ejsexton82** [comment]
Does this need to be implemented?

It seems that the same effect could be achieved by setting the `encodeLabels` property to `false`, and then passing your raw text or HTML as a label:

~~~~
echo Menu::widget([
  'encodeLabels' => false, 
  'items' => [
    ['label' => 'Raw Text or <strong>HTML</strong>']
  ]
]);
~~~~

**Comment by samdark** [comment]
I think it's OK to do as @ejsexton82 suggested.
