### ISSUE TITLE
Implement RBAC management module

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii2#42]

**Comment by githubjeka** [comment]
@samdark I altered icon by bricks :santa:

**Comment by samdark** [comment]
Looks much better.

**Comment by githubjeka** [comment]
:coffee:
My thoughts at the moment.

I tried to use a real project using the [current code](https://github.com/githubjeka/gui-rbac-yii2) (demo - https://basic-rbac-githubjeka.c9.io/basic/web/index.php?r=rbac):
![http://i.imgur.com/OmhXNl2.jpg](http://i.imgur.com/OmhXNl2.jpg)


In real project uses 238 roles and permission. In the same uses **654!** links of roles and permissions.
When using square angles for connections, then we get ocean overlaps and intersections.
![](http://i.imgur.com/UNwJTj8.jpg)
![](http://i.imgur.com/w6a7EWj.jpg)

I used my code that invented himself. Now I read about some algorithms - http://en.wikipedia.org/wiki/Graph_drawing . I tried Sugiyama algoritm ([1](http://en.wikipedia.org/wiki/Layered_graph_drawing), [2](http://en.wikipedia.org/wiki/Directed_acyclic_graph))

Received such images:
![](http://i.imgur.com/qO3iIDR.jpg)
![](http://i.imgur.com/utTru1W.jpg)

Not much better than my. :lollipop: 

At this point, I think my original offer the best.

![](http://i.imgur.com/BtWx9Gd.jpg)
![](http://i.imgur.com/sIxskXm.jpg)

Plus huge that connected nodes are as close to each other and connection are easy to read when huge number of links.

:coffee: ended gl hf

**Comment by samdark** [comment]
Hmm. I don't think it's even possible to visualize such a number of connections in a readable way. Probably it's a good idea to highlight all connections for a node when node is selected.

**Comment by cebe** [comment]
A tool for editing rbac rules visually does not need to scale up to that amount of items and connections imo. Imo it should work well for the simple case and maybe change display methods if the number of nodes is greater than a certain threshold. I like the first way of displaying:

![](https://camo.githubusercontent.com/a2ddf92c4787215476c30842c48f396fab6eb0eb/687474703a2f2f692e696d6775722e636f6d2f4f6d68584e6c322e6a7067)

but if that does not scale for large number of items you can implement a threshold value that will use another rendering method if more nodes need to be displayed.

**Comment by samdark** [comment]
Or provide a way to choose visualization method. Same as PhpStorm does for diagrams.

**Comment by hscstudio** [comment]
hem... I think if creator yii2-admin join discussion in here.. it will be amazing.. :)

**Comment by patlecat** [comment]
I also think that this visual tool is better at viewing the objects than for creating RBAC rules. A category-based/sorted table with an instant-seach field would do much better for that and also be still usable with a high amount of objects.

**Comment by dynasource** [comment]
agree with @patlecat.

- use graphs for understanding
- use tables for editing

**Comment by githubjeka** [comment]
I use table for assign role to user only. This module for others. But no time for update interface...

**Comment by Faryshta** [comment]
I have a PR open #6872 so far it has passed all the unit testing, I don't know whats needed for merging

**Comment by missjewel** [comment]
how install this module for template advanced yii2? 
And have interface it?

**Comment by githubjeka** [comment]
https://github.com/githubjeka/gui-rbac-yii2#use-on-local

**Comment by missjewel** [comment]
and please how executo o run this module? the route. I have prettyURL then controller/action.

**Comment by githubjeka** [comment]
https://github.com/githubjeka/gui-rbac-yii2/blob/master/config/web.php#L10\

`index.php?r=rbac`

**Comment by githubjeka** [comment]
Added new features. [[repo]](https://github.com/githubjeka/gui-rbac-yii2)
See [demo](https://basic-rbac-githubjeka.c9.io/basic/web/index.php?r=rbac)

**Comment by patlecat** [comment]
When I double-click to delete/modify a node I cannot get out of the delete-mode anymore. Nothing worked.

**Comment by githubjeka** [comment]
Hmm..
When you dbclick on node then node selected to form. Push red delete button.

The moment of CRUD implemented via form isn't perfect. I don't like it myself. But so far I haven't heard how best to do it.

**Comment by patlecat** [comment]
No man, how can I leave the delete-mode **without** deleting anything?

**Comment by githubjeka** [comment]
Push white `reset-form` button

**Comment by githubjeka** [comment]
New features. :seedling:
Added new search block. Now you can search roles and permissions by name.
Added style to a marked node.

**have fun**
![image](https://cloud.githubusercontent.com/assets/874234/7066958/0a660a7c-ded0-11e4-8484-608cfc59b573.png)

**Comment by samdark** [comment]
Great!

**Comment by nkostadinov** [comment]
Guys this is nice but it looks over complicated.

**Comment by githubjeka** [comment]
than what?

**Comment by samdark** [comment]
@nkostadinov any concrete suggestions?

**Comment by nkostadinov** [comment]
The RBAC system is very flexible but in real life, no one will want to arrange these graphs while setting permissions. My current RBAC implementation has only one group per user and this group holds the permissions(like "yes"/"no") - simple as that. There is no inheritance, no complex graphs ... It's working on a very large scale at one of the biggest telco's in Bulgaria and is doing it's job perfectly.

I'm currently working on something like this for yii2 but it's not ready yet. The idea is to have a basic user extension, and to add "plugins" implementing different functions. I just like to keep it simple :)

Anyway I'm not saying nothing bad about this, just discussing here.

**Comment by samdark** [comment]
Complexity of RBAC permissions graph depends very much on the nature of the project. If it is about community and is something like StackOverflow where you're getting more permissions and moving towards the top of the hierarchy depending on your actions, the graph could be quite complex.

The RBAC management extension discussed here is able to visualize it nicely so one could get a good overview and fix some bugs.

Of course, if you know that simpler hierarchy is OK for the project and you're quite sure that it's not gonna change, UI could and should be simplified.

**Comment by githubjeka** [comment]
I have one idea - auto create a migration for every action CRUD ` yii\rbac\Item`.
What you think? Can somebody show me example file with simple rbac migration?

**Comment by samdark** [comment]
Yep, that could work.

```php
<?php

use yii\db\Schema;
use yii\db\Migration;

class m150910_204507_init_blog_rbac extends Migration
{
    public function up()
    {
        $auth = Yii::$app->authManager;

        $manageBlog = $auth->createPermission('manageBlog');
        $manageBlog->description = 'Manage blog';
        $auth->add($manageBlog);

        $admin = $auth->createRole('admin');
        $admin->description = 'Administrator';
        $auth->add($admin);
        $auth->addChild($admin, $manageBlog);
    }

    public function down()
    {
        Yii::$app->authManager->removeAll();
    }
}
```

**Comment by samdark** [comment]
Won't be implemented in the core since it's to flexible to have a universal UI.

**Comment by yasseralmofaalani** [comment]
how to assign roles to users

**Comment by SilverFire** [comment]
RTFM: http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#generating-rbac-data
