### ISSUE TITLE
yii2 android app guide

### ISSUE THREAD

**Issue by Asetss** [yiisoft/yii2#4203]
I think such an application need. It will be convenient to read on the road. 
I have a basic development experience android, but not enough time.

yii1 app https://play.google.com/store/apps/details?id=com.yurkiy.yiiclassreference

**Comment by johnss** [comment]
Why should be an app ?  I think there should be no app for this purpose, if android app exist there will be same requests for iOS and Windows 10 mobile.

Dev should consider an universal docs and should not create app just for specific os, yii should make html download available [3267](https://github.com/yiisoft/yii2/issues/3267) , so android user can view it offline using the stock browser, or there are already exists few android app that can view markdown.

**Comment by samdark** [comment]
https://play.google.com/store/apps/details?id=com.akramhossain.yii2definitiveguide
