### ISSUE TITLE
Error Page Display Issues

### ISSUE THREAD

**Issue by nsanden** [yiisoft/yii2#4208]
Anything that can be done about this? This is my nemesis when debugging.

![7 3 2014 6 40 12 pm jpg 13664603](https://cloud.githubusercontent.com/assets/2072064/3489417/f7087600-052b-11e4-8447-9f34fa4c448e.png)

Side note: Seeing the post/get/session etc variables has been a huge time saver.

**Comment by pana1990** [comment]
duplicated #4763

**Comment by cebe** [comment]
thanks, @pana1990!
