### ISSUE TITLE
Polymorphic relations in ActiveRecord ?

### ISSUE THREAD

**Issue by Nymerea** [yiisoft/yii2#4218]
Hello every body,

At my work we use Laravel's ORM (Eloquent) because it is stand-alone.
This ORM Follow ActiveRecord Pattern (like Yii's ActiveRecord). Laravel implements polymorphic relations and it's very usefull, why yii don't implements it ?

Implements the many to many polymorphics relation would be a good thing !

See laravel doc, for more details : http://laravel.com/docs/eloquent#polymorphic-relations

**Comment by yang-he** [comment]
+1. Would be awesome if Yii2's ActiveRecord can support Polymorphic Relations, so that I don't need to implement something like state design pattern on my own --- saving a lot of time by avoiding creating a bunch of class files.

**Comment by rrussell** [comment]
+1 will be so useful ! Actually on Laravel works so good!

https://laravel.com/docs/5.2/eloquent-relationships#polymorphic-relations

**Comment by Faryshta** [comment]
which would be the proposed syntax for yii2?

```php
class Like extends ActiveRecord
{
   public static function morphMap()
   {
        return [
            'post' => Post::className(),
            'comment' => Comment::className(),
        ];
   }

   public static function getMorphClass($type)
   {
         static $map = null;
         if ($map === null) {
             $map = self::morphMap();
         }

         if (class_exist($type) && is_subclass($type, self::className())) {
             return $type;
         }

         return empty($map[$type]) ? null : $map[$type];
   }

   public static function instantiate($row)
   {
         if (!empty($row['type']) && null !== $class = self::getMorphClass($row['type'])) {
             return new $class;
         }

         return new static;
   }
}
```

instantiate is an already existing method so the implementation would be easy without needing to define extra methods for the morph.

**Comment by samdark** [comment]
@Faryshta yes. Probably it's better idea to create a recipe in https://github.com/samdark/yii2-cookbook and link to it from AR guide.

**Comment by Faryshta** [comment]
@samdark the only question I have is how would the eager loading work since they will point to different tables?

```php
class LikePost extends ActiveRecord
{
    public function getLiked()
    {
        return $this->hasOne(Post::className(), ['id' => 'liked_id']);
    }
}
```

and

```php
class LikeComment extends ActiveRecord
{
    public function getLiked()
    {
        return $this->hasOne(Comment::className(), ['id' => 'liked_id']);
    }
}
```

how would `->with('likes.liked')` work?

**Comment by samdark** [comment]
I have no idea. Try it.

**Comment by dynasource** [comment]
this really is a nice enhancement. We'll keep it in mind for the future. Feel free to add your usecases as a comment.

**Comment by cebe** [comment]
HumHub has an implementation of polymorphic relations: https://github.com/humhub/humhub/blob/master/protected/humhub/components/behaviors/PolymorphicRelation.php

**Comment by Zerebokep** [comment]
Is there any official solution for polymorphic relations?

**Comment by FabrizioCaldarelli** [comment]
I think that it is not a good idea, because this breaks right database design. You could not have data integrity. I prefer to have many id fields in the table to match all joined tabled (and guarantee data integrity).

So my 'likes' table would have: post_id, comment_id, ..., so i can have constraint for every foreign keys.

**Comment by joanlopez** [comment]
I'm sorry @FabrizioCaldarelli but I'm not agree with you.

Your proposal derives in a non-extensible system.
Each time you need to add a new morphism you will need to make an ```ALTER TABLE```. 
Did you think about what will happen when you try to ALTER a table with X millions of registers?

IMHO, I prefer manage the data integrity with other techniques than compromise the extensibility of the system.
