### ISSUE TITLE
Feature: add before controller render event

### ISSUE THREAD

**Issue by giovdk21** [yiisoft/yii2#4271]
Hello,
right now we can attach an handler to the `yii\web\View::EVENT_BEFORE_RENDER` event but this is triggered every time a view is requested ("regular" view, partial or layout).

I think it might be also useful to have a similar one that is triggered when using the render method from a controller (`\yii\base\Controller->render($view, $params = [])`)

In this way we have an event that is usually triggered once per page load that is in between beforeAction and afterAction but it is actually triggered inside the action just before rendering the page.

A practical example: you load some content from the database in your controller through your model and you want to set your current page title in the view / theme. You also then want to have a method that automatically takes your title and populate some open graph or twitter cards tags. The event will then fire before rendering the page allowing the event handler to populate the meta tags based on the information set in the action before calling the render method.

Let me know if it makes sense, thanks :)

**Comment by rtwent** [comment]
+1

**Comment by Faryshta** [comment]
is there any behavior or component that might use that feature? otherwise it might be simpler to overwrite the `render()` method.

```php
public function render($view, $params)
{
    // before render
    return parent::render($view, $params);
}
 ```
