### ISSUE TITLE
Integer attributes always marked as dirty

### ISSUE THREAD

**Issue by tvdavid** [yiisoft/yii2#4284]
Consider a model "Person" with two attributes: "name" (varchar) and "age" (int).

Open up the update view for an existing model with name="John" and age=10. Don't change either of the fields and submit the form.

Yii will now consider the "age" attribute as dirty, and thus a sql UPDATE command will be ran, and afterSave() will receive this attribute in $changedAttributes. As this only happens for integer columns, I suspect it has something to do with the typecasting between form input (string) and database (integer).

**Comment by auxww** [comment]
Bug reproduced in yii2

```
    //Model

    public function rules()
    {
        return [
            [['salary_min', 'salary_max', 'type_id', 'education_id', 'experience_id', 
            ], 'integer', 'min' => 0],
        ];
    }

   //Controller
  if ($model->load(Yii::$app->request->post())) {
            echo '<pre>';
            $dirty = $model->getDirtyAttributes();
            foreach ($dirty as $key => $value) {
                echo $key . ': ' . $value . ' ' . $model->getOldAttribute($key) . ' 2' . ($value == $model->getOldAttribute($key) ? 'Y' : 'N') . ' 3' . ($value === $model->getOldAttribute($key) ? 'Y' : 'N') . "\n";
            }
            echo '</pre>';
            die();
            //$model->save();
        }
```

yii\validators\NumberValidator didn't cast

![image](https://cloud.githubusercontent.com/assets/19860919/26354079/ce069d6c-3fcb-11e7-89cc-e9d9b3de5787.png)

**Comment by auxww** [comment]
It depends, whether default NULL or 0. More accurate would be the next, it removes extra spaces, verifies the +-\d regular expression, sets null or 0 for empty strings and finally converts the result to the appropriate mapping type, i. e. INT:
```
['age', 'trim'],
['age', 'integer', 'integerOnly' => true, 'min' => 0],
['age','default', 'value' => null], //or 0
['age', 'filter', 'filter' => function($value) {
    return is_null($value) ? null : intval($value);
}],
```

> ['age', 'filter', 'filter' => 'intval'],
intval('') and intval(null) is 0, the attribute new value after filter becomes 0, old attribute value by default NULL as it's usually set in a database schema, yii will mark this attribute as dirty (INT 0 === NULL null) and save it.

Best wishes,
auxww

**Comment by cebe** [comment]
@auxww you can set `skipOnEmpty` to true on the filter so it would not convert a null value.

**Comment by cebe** [comment]
added an example to the guide.
