### ISSUE TITLE
Template inheritance

### ISSUE THREAD

**Issue by tvdavid** [yiisoft/yii2#4296]
I think Yii should support and recommend/document a method for template (view) inheritance.

I've been playing with a method here: https://gist.github.com/tvdavid/c888a73e5c8eb8c12b86. Any thoughts?

See also: http://mark-story.com/posts/view/view-inheritance-in-cakephp (although I like this solution a lot less, if I see it correctly this doesn't allow you to specify default content for when a section is not overridden)

**Comment by dynasource** [comment]
view file inheritance is kind of an anti pattern. PHP is object oriented. We should use it that way.

**Comment by samdark** [comment]
It's not really anti-pattern. It works well but requires pre-processing and is already supported via Twig integration, for example.
