### ISSUE TITLE
API: File upload support (RC)

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#4477]
follow up on #303

**Comment by Faryshta** [comment]
how do you want to have the file upload feature? i managed to do it extending the `yii\rest\CreateAction` class, i rewrote the `run()` method and added at line https://github.com/yiisoft/yii2/blob/master/framework/rest/CreateAction.php#L49 a call or the  `UploadedFile::getInstanceByName()` method.

we can add an option `fileAttributes` on the `yii\rest\CreateAction` class something like 

```php
foreach ($this->fileAttributes as $attribute) {
    $model->$attribute = UploadedFile::getInstanceByName($attribute);
}
```

**Comment by Faryshta** [comment]
any update on this request? @cebe @samdark 

can i make a pr based on my proposal for a `CreateAction::fileAttributes` proposal?

**Comment by klimov-paul** [comment]
I am solving such task at model behavior level
https://github.com/yii2tech/ar-file/blob/master/FileBehavior.php#L410-L426

**Comment by cebe** [comment]
I am unsure what this issue is actually about. There are many ways to upload files in a REST API, I do not see concrete requirements to be implemented in YIi for this. I'd vote for closing this issue unless someone can come up with a concrete need for an implementation.

@Faryshta it is not about enhancing `CreateAction` or `UpdateAction` but more about PUT /files/myfile.txt requests which contain the file content.
