### ISSUE TITLE
yii\base\Formatter // ability to shorten text or ntext or better maybe closure support?

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#4495]
It would be nice to be able to short text within the Formatter or be able to set any format you want to via a closure.

like
`
'format'=>'ntext:200', //first 200 would be displayed
`

or adding closure support to Formatter.

usecase...
Im using kartik\detail\DetailView to have the ability to edit the fields directly in the detail view.
http://demos.krajee.com/detail-view-demo

Now if you have huge textfields there is no way to shorten the text without changing the value field to a shorter version.

other usecases for closures
any format you wish without a huge impact.

**Comment by klimov-paul** [comment]
I am unsure: there are several ways to trim the text: you can use `StringHelper::truncate()` or `StringHelper::truncateWords()` - switching between those will require extra parameter.

> other usecases for closures any format you wish without a huge impact.

I don't get it. `DetailView` and `GridView` you can specify value of the attribute directly, using any format you want.
Extra formats can be easily added to `Formatter` using behavior mechanism.

**Comment by ItsReddi** [comment]
`you can specify value of the attribute directly, using any format you want.`
yes you can but is cutting the value intended for that use? feels not good.
AND
if youre using the grid as a form you cannot trim the value directly.. because you will save the trimmed value after that.

`Extra formats can be easily added to Formatter using behavior mechanism.`
Yes. But why this overhead if you simply could write for example.
`function($value){ return $theValueInBeatutiful; }`

**Comment by SamMousa** [comment]
@klimov-paul Would you merge a PR that adds support for closures?
It would not break BC since currently the `format` function takes either a `string` or an `array` as the format parameter.

It changes at most 5 lines of code.

If not, can you close this? :)

**Comment by samdark** [comment]
I think closure support makes sense.

**Comment by cebe** [comment]
can you show an example on how you would use closure in formatter?

**Comment by SamMousa** [comment]
Anytime I pass a closure into the `value` key for a grid column it could as well be specified as a format. Which more clearly illustrates the fact that I'm just formatting and not creating a new value.

**Comment by cebe** [comment]
implemented by #14326

**Comment by SamMousa** [comment]
Does it not make sense to pass the formatter object to the closure as well?
So that the closure has the option to (re)use it? 
It's often convenient to have the caller of the closure available similar to what the DI container does when calling a closure.

**Comment by cebe** [comment]
good point, will add it.
