### ISSUE TITLE
Exclude assets from rendering

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#4522]
Hello.
I have this case:
On `page1` there is Bootstrap Modal which content is loading via ajax from `page2`. To not include header and footer into `page2` I'm using renderAjax in page2 controller. But I need to exclude some assets which are loading automatically: for example, Bootstrap offset. I have two reasons for this:
1. These assets are already loaded in parent document (`page1`) and I don't need unnecessary network requests for these CSS and JS files.
2. On `page1` I'm using my own css file which overrides some Bootstrap styles. And when modal content is loaded, styles of `page1` are overriding by bootstrap.css.

So I'm looking for a way to exclude specified assets from rendering (by renderAjax, as minimum).

P.S. renderPartial is not a solution, beacuse in case of using it inline JS registered by widgets are missing.

**Comment by diamont2003** [comment]
Insert this code before render ))
Yii::$app->assetManager->bundles = [
'yii\bootstrap\BootstrapPluginAsset' => false,
'yii\bootstrap\BootstrapAsset' => false,
'yii\web\JqueryAsset' => false,
];

**Comment by Nellrider** [comment]
> Romero, I didnt say that before rendering worked. EVENT_AFTER_RENDER is the one you need. To help you out with an example. Put this anywhere in your code:
> 
> ```
> \yii\base\Event::on(\yii\web\View::className(), \yii\web\View::EVENT_AFTER_RENDER, function ($e) {
>   $e->sender->assetBundles = [];
> });            
> ```

This works! Thank you!
