### ISSUE TITLE
Filters for query results

### ISSUE THREAD

**Issue by moicirk** [yiisoft/yii2#4555]
Hello everybody. I am writing here for the first time, but using Yii and Yii2 for a long time already. I did implement the idea by myself in own projects and now I want to ask You to add it in the core.

I extended Query class and added filter() method to change the output result. That`s how it looks like

```
$orders = (new app\core\MyQuery)->from('orders')->filter(function($model){

    $model->createdAt = Yii::$app->format->asDate($model->createdAt);
    $model->createdAt = Yii::$app->format->asDate($model->createdAt);
    return $model;

})->all();
```

An argument for closure is a one model from result or an array is 'asArray' flag set. all() and one() methods of Query class return this

```
return $this->applyFilters($result);
```

now.

What do You think?

**Comment by moicirk** [comment]
Of course you can but doesn't this
``` 
$orders = (new app\core\MyQuery)->from('orders')->filter(function($model){
	//Do something with result...
	return $model;
})->all();
```

then this ?
```
$orders = (new app\core\MyQuery)->from('orders')>all();
$orders = array_filter($orders, callback());
```

Looks more in Yii style

**Comment by omnilight** [comment]
@moicirk You are right, that is more in Yii style. And I think it would be great if filter callback can be used with `each()` and `batch` methods of `Query`.
