### ISSUE TITLE
Functional testing & $_FILES

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#4567]
@devs,

I'm having trouble with the functional testing of a upload function. There seems to be a problem with $_FILES not being loaded correctly in yii\web\UploadFile::loadFiles().

I guess its because the Request was already executed and filled. It is filling itself with a static property. A solution that works is adding 'empty(self::$_files)' but I am wondering if there is another solution (as the tests that will follow will fail eventually)?

Is there something in the Yii2 & Codeception integration that cleans the Request for files?

```php
//possible solution
private static function loadFiles()
   if (self::$_files === null || empty(self::$_files)) {
//etc
   }
} 



//Codeception functional test
// uploadCept.php
$I = new dmn\yii2\modules\file\tests\codeception\TestGuy($scenario);
$I->amOnPage('index-test.php?r=file%2Ffile%2Fcreate');
$I->see('Create File');
$path = "//input[@type='file']";
$I->seeElement($path);
$I->attachFile($path, 'Tulips.jpg'); 
$I->click("//button[@class='btn btn-primary start']");

**Comment by dynasource** [comment]
@samdark: this issue can be closed when \yii\web\UploadedFile::reset() is included in https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Connector/Yii2.php

**Comment by Ragazzo** [comment]
@dynasource how this will solve problem since as i remember it was about `move_uploaded_file` and `rename` functions in php to handle this situation? You still will not be able to save file where you need it

**Comment by dynasource** [comment]
well, today doing 2 functional tests in a row with attachFile didnt work correctly, because of the first file being remembered instead of being overridden by next tests. After including the reset in the Yii2 connector, the tests behaved correctly.

**Comment by Ragazzo** [comment]
I see , yes your issue is valid however it does not have anything related with this one . I think your fix is valid and can be applied in `Yii2` `Codeception` module , can you submit PR in `Codeception` ?

**Comment by dynasource** [comment]
my mistake not looking thoroughly to my initial post. Sorry for that. I will look at it tomorrow.

**Comment by ilyachase** [comment]
Sorry for necroposting but there is more nice and clean workaround:
put this to the `` file
```
