### ISSUE TITLE
Fixtures autoloading into DB

### ISSUE THREAD

**Issue by topazas** [yiisoft/yii2#4613]
Based on this guide (http://www.yiiframework.com/doc-2.0/guide-test-fixture.html) i generated simple fixture for unit test.
in my test class
```
class UserTest extends DbTestCase
{
...
```
i use: 
```
 public function fixtures()
    {
        return ['users' => UserFixture::className() ];
    }
```
where UserFixture:
```
class UserFixture extends ActiveFixture
{
    public $modelClass = 'app\models\User';
}
```
Fixture data file is generated with 2 records and in place. Then i try unit testing:
```
$model = new User;
        $query = new Query;
        $this->specify('Model validation should FAIL in first scenario', function () use ($model, $query){
            expect('Should be 2 users in DB',  $query->from($model->tableName())->count() )->equals(2);
        });
```
And is failing: 0 records instead of 2.
Question: should'n fixtures autoloaded into DB before each test?

**Comment by klimov-paul** [comment]
Closed, unless more infromation arrives.
