### ISSUE TITLE
Docs update: Fixtures - Acceptance & Functional tests

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#4635]
As Ragazzo stated, if things are unclear about Testing, please commit. Well, in this case I am having troubles with finding information about using fixtures for Acceptance & Functional testing.

At this section https://github.com/yiisoft/yii2/blob/master/docs/guide/test-fixtures.md, information about Fixtures is purely about:
* Load fixtures in Unit tests
* Load fixtures by console

According to the Codeception manual http://codeception.com/docs/09-Data, fixtures are also to be used 
with Acceptance & Functional tests. A clear implementation is not given. The same goes for the Yii2 docs.

So my question is. How should it be done for Cept & Cest classes. What is the convention? 
Do we have to use _bootstrap for this  like this?:
```php
$fixture = new UsergroupFixture;
$fixture->dataFile = '@tests/codeception/_data/fixtures/data/usergroup.php';
$fixture->load();    
```

**Comment by mklemarczyk** [comment]
@Ragazzo With this difference that ```setUp``` and ```tearDown``` work.
But _after never will be called when test fail or error. (In fact it should be called)

Like you comment says this (SignupCest.php, from advanced template):
```php
    /**
     * This method is called before each cest class test method
     * @param \Codeception\Event\TestEvent $event
     */
    public function _before($event)
    {
    }

    /**
     * This method is called after each cest class test method, even if test failed.
     * @param \Codeception\Event\TestEvent $event
     */
    public function _after($event)
    {
    }

    /**
     * This method is called when test fails.
     * @param \Codeception\Event\FailEvent $event
     */
    public function _fail($event)
    {
    }
```

**Comment by Ragazzo** [comment]
@mklemarczyk yes, it can be that they changed the name, feel free to submit PR. Is there any question you want to ask or i dont understand your message?

**Comment by mklemarczyk** [comment]
@Ragazzo There is confusion with _after method. Codeception do not invoke it at fail and error.

In yii doc is:
```
This method is called after each cest class test method, even if test failed.
```

**Comment by Ragazzo** [comment]
@mklemarczyk yes, the docs was written long time ago, in that times it was called, however later it was decided to remove this feature, feel free to submit PR for docs
