### ISSUE TITLE
Using parameterized relation and AR::with()

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#4670]
I have not found in docs any mention on how to use parameterized relation `with` eager loading, for example as in `AR` docs let say we have:

``` php
class Customer extends \yii\db\ActiveRecord
{
    public function getBigOrders($threshold = 100)
    {
        return $this->hasMany(Order::className(), ['customer_id' => 'id'])
            ->where('subtotal > :threshold', [':threshold' => $threshold])
            ->orderBy('id');
    }
}
```

how to specify in `with` the `$threshold` ? Afaik in Yii 1 we can make this simple with array specifying in relations in `with` to pass the parameters in. Note that i am not asking for scope that can be solved by callback in `with` but for passing parameter to relation in eager loading

``` php
Customer::find()->with(['bigOrders' => ???? ])->all();
```

**Comment by ceovishnu** [comment]
@qiangxue  it's really not working.

It would be very useful if we could pass arguments to relation getter using with

if u have any solution.

**Comment by Ragazzo** [comment]
@ceovishnu it is not implemented yet

**Comment by ezze** [comment]
Hi guys!
I also really need parameterized relations being supported. It's very frequent task for eager loading. At the moment I have to specify conditions outside the relation method each time, and it doesn't seem very good and handy.

**Comment by CedricYii** [comment]
On some occasion, I found useful to define a fix relation to define a parameter as a workaround, like:
````php
// fake relation
public function getThousandOrders()
{
   return $this->getBigOrders(1000);
}
````
So at least you don't have to care about what's into it (especialy when you have complex queries from several parents and need to change something). And then use:
````php
Customer::find()->with('thousandOrders')->all();
````

Or you can try to hack with global variables.

**Comment by dynasource** [comment]
For now, you should either:
* override ActiveQuery
* use Events
* or use callbacks

Please look at: http://www.yiiframework.com/doc-2.0/yii-db-activequerytrait.html#with()-detail
