### ISSUE TITLE
Pjax update forces blur from document.activeElement 

### ISSUE THREAD

**Issue by aguidrevitch** [yiisoft/yii2#4677]
We have some dynamic gridview which reloads as you type something in the form, that makes work with form impossible. Right now I must return focus to the same input field after each reload. Can you make this behavior configurable ?

**Comment by kiqeri** [comment]
Same issue here. I was thinking about setting the focus after the Pjax update. Is there any way to know that the Pjax has finished updating?

**Comment by SilverFire** [comment]
Fixed
