### ISSUE TITLE
Cache Busting for CSS and JS (AssetBundle)

### ISSUE THREAD

**Issue by 6pblcb** [yiisoft/yii2#4710]
As far as I understand, currently not easy way to do versioning for resources (js/css).
```html
<link rel="stylesheet" href="file.css?v=1.1" />
<script src="/js/file.js?v=1.2">
```
Possible solution: add a "special" option (version) in an array of options.
```php
//View
$this->registerJsFile('url', [], ['version' => '1.1']);
//AppAsset
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $jsOptions = ['version' => '1.1'];
    public $js = [
        'js/foo.js',
        'js/bar.js'
    ];
}
```

**Comment by almirb** [comment]
Hello,

It's safe to use this caching options? I'm a little worried about the "?" character... PageSpeed says It's bad idea:
https://gtmetrix.com/remove-query-strings-from-static-resources.html

What do you think about that?

Thanks!

**Comment by samdark** [comment]
If you're using squid it could be a bad idea. If not, you're safe.

**Comment by almirb** [comment]
I'm using UFW (Uncomplicated Firewall) on Ubuntu 14.04... then I think It's ok.
Thanks!
