### ISSUE TITLE
Docs about User login improvements

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#4717]
I think it would be good to enh. docs about user login managment, what would be great to see in docs
- [ ] identity implementation for rest and other api;
- [ ] how to login and why by `authToken`
- [ ] what data to use and what to do in `beforeLogin` and `afterLogin` same for logout, i mean some examples would be handy
- [ ] some schema on how user is logged in application with `autologin` and some `absoluteTimeout` features examples
- [ ] regeneration of `auth_token` and where it is needed (after each user logout)
- [ ] multi login on different devices example (store auth_token in separated table basing on some info about browser, password and platform)

I made it with checkboxes since some data can be covered in other topics, for example API or can be not covered, correct me if i am wrong

**Comment by dynasource** [comment]
enough information in the guide at this topic http://www.yiiframework.com/doc-2.0/guide-security-authentication.html
