### ISSUE TITLE
yii command bash autocompletion

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#475]
I created one for yii1.1 yiic for a specific case. Will try to work on a generic solution.
https://gist.github.com/cebe/1141050
Why? because bash is only fun when it helps you typing less as much as possible ;)

**Comment by MetalGuardian** [comment]
hi
i create bash completion script for yii2 console commands. it can complete commands and options of the commands now. 
is it possible to add some more actions to the help command (in core), witch will return structured and formatted data?

**Comment by cebe** [comment]
nice! yep, output of structured information should be added to help command.

**Comment by dynasource** [comment]
3 years have passed with little progress so Im closing this one. It is a nice to have and if somebody wants to have this in core, please feel free to do a PR.

**Comment by cebe** [comment]
I have added a very basic implementation for completion of commands in #12959.

**Comment by cebe** [comment]
3 years but finally did it ;)
