### ISSUE TITLE
Definition of Switching point - Frontend vs Backend

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#4771]
Sorry to come back on it again: a subject on which already a lot has been said. There are examples of use, examples of advantages and arguments like '@samdark: that there couldnt be one single way of use'.

Either way, I am still not satisfied with the current documentation & discussions about it. Its too vague:
* http://www.yiiframework.com/wiki/33/
* https://github.com/yiisoft/yii2/issues/40#issuecomment-18370903
* https://github.com/yiisoft/yii2/issues/3647
* https://github.com/yiisoft/yii2/issues/1520

Now, after 2 months of development, I keep on being confronted with the same architecture design issues - over and over again. 
* whether to use module splitting in backend & frontend?
* whether to separate actions between backend & frontend?
* should a userend have its own tier?
* etc etc

The same questions keep on coming back. What exactly is the real advantage for me. Is it about structure? About convention? About consistency? About making stuff easier? About easier design?
Whats the focus? Is it about users v.s. administrators? But what if users can also manager their own content. etc. etc. 

Current discussions & wiki's don't give an answer on this question, apart from the example of the advantage of 'different servers'. Therefore this thread. To make it different from other discussions, I would like to focus it on one specific definition: 
* at what point should one switch to the separation of frontend and backend

This definition would be of great value for the docs and people new to this subject (and for me, because I still havent got one single definition). I dont like vague scenarios, I prefer 100% solid proof definitions. Since you have the choice to use this separation or not, it means that there must be a important criterium to switch. Which is it or which are these?

**Comment by jasonhai** [comment]
Please help me with back-end path issue ...  I can't access to back-end module in my project :-s .... 

My backend project link like this: http://calcart.axeo.net/backend

**Comment by lynicidn** [comment]
@jasonhai  use forum. U have problem with web server configure

**Comment by jasonhai** [comment]
@lynicidn : I also dont understand your mean. Please ping me via skype: pmhai90. Thanks so much

**Comment by jasonhai** [comment]
@lynicidn Thanks all for your help !!!

**Comment by BAWES** [comment]
Let's say I want to build an e-commerce with front-end for customers, backend for admin, another backend for suppliers, and one more backend for delivery companies.

So I keep the shared models in common folder, but how to create the other backends with their own user type login? Whats the correct process for each section? Modules? Extensions? Application instances (tier)?

**Comment by samdark** [comment]
By copy-pasting backend directory. It's nothing more than separate apps with their own entry points.

**Comment by BAWES** [comment]
@samdark Thanks! Will try this out

**Comment by Sammaye** [comment]
Make sure you make a eploy target for them else you will find you have to
constantly copy your ./init files around

**Comment by BAWES** [comment]
@Sammaye Can you please explain or point to where I can find how to do that

**Comment by gauravparashar12** [comment]
@samdark @Sammaye  @qiangxue  I am using mdmsoft module (for Rbac ) in the advanced application and separated frontend for website and backend for admin panel.In this case in the mdmsoft module routes of frontend app  visible in frontend app and routes of backend app visible in backend app but here superadmin wants to see all the routes at same place.
As per the current situation we need to go frontend app as well as backend app to manage the permissions. But we think that a common platform to manage permission will be more better. 

As per my project requirement there will be a admin panel accessed by multiple type of admin users with different permissions needs to manage main website and a superadmin will manage the permissions of few registered  users of website and admin users both.

Please suggest us a whether we use advance app or a basic one and how.

**Comment by dynasource** [comment]
So, two years further, I can conclude that its very useful to expand an app by more tiers. However, the developer should be careful though. The more tiers, the more complexity you will add to your configuration files. This is the largest setback. Another thing that makes it more complex is the deployment. The more tiers you have, the more deployment settings you can have. Also, the more tiers you have, the more difficult is to optimally test your project. If you are running a multi thread testing environment, you have to allocate your CPU's to the tiers which has consequence.

With respect to the advantages. There are many. Code is better organized. Config is better organized. Theming is easier. Performance is better. Risks are lower and its even possible to deploy by tier.
