### ISSUE TITLE
Testing part 2 unit

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#4785]
Currently working on unit tests [guide](https://github.com/yiisoft/yii2/blob/master/docs/guide/test-unit.md) . What should be covered in guide

- [ ] `Yii2` advanced application template `User` features with plain php file;
- [ ] showing `tests first` approach;
- [ ] showing how to switch between steps size in testing;
- [ ] add note about fixtures and how to use them. What fixtures are provided by `Yii2`, very brief overview since there is a guide for it;
- [ ] info about avoiding `LikeIHood` testing;
- [ ] mocks and stubs, and their difference; When you should mock and why you should avoid it by default, same for stubs;
- [ ] using IoC as a solution of decoupling code and DI container usage in testing.

Can one mark it with docs ? By default testing framework to run examples will be `Codeception`

**Comment by Ragazzo** [comment]
@samdark i am closing this issue in favor of book [`Yii2 Learning Testing`](https://www.packtpub.com/web-development/learning-yii-testing) , is it ok ?

**Comment by samdark** [comment]
Yes.
