### ISSUE TITLE
Ability to dynamically prepend behavior to current behaviors

### ISSUE THREAD

**Issue by tebazil** [yiisoft/yii2#4843]
Right now you can only append behavior, so it's priority is the last - since the recently attached one is the last in the chain.

It should be nice to prepend behavior, so that it immediately becomes first in the chain.

It could be needed, for example, to attach the access control behavior, which should be run first, and since `ensureBehaviors` ensures that behaviors defined in the behaviors() method go first, there is no way to do so that your dynamically attached behaviors are added to the top.

**Comment by dynasource** [comment]
> Behavior mechanism assumes each behavior is independent and self-contained, so their attach order should not matter.

From a architectural perspective, this way of looking at behaviors is leading.
If you want to have an integration in place, you should manually create a Component for this.
