### ISSUE TITLE
Yii2-sphinx multiple server handling

### ISSUE THREAD

**Issue by tibee** [yiisoft/yii2#4849]
Hello,

since yii2-sphinx extends yii2 db handling capabilities, it does already support multiple master and multiple slave servers for load balancing and read-write separation.

However, since Sphinx does not support replication, cannot be configured that way as for example, MySQL replication. So, if I need to run multiple servers for load balancing, I have to set up multiple servers (as logigal masters, without logical slaves), and I would need to write in every master.

My component config would be:
```php
 'sphinx' => [
        'class' => 'yii\sphinx\Connection',
        'masters' => [
            ['dsn' => 'mysql:host=192.168.1.20;port=4300'],
            ['dsn' => 'mysql:host=192.168.1.21;port=4300'],
        ],
        'masterConfig' => [
            'username' => '',
            'password' => '',
        ],
    ],
```

The current implementation chooses only one master on a write operation, causing inconsistency.
A feature request would be the high-level support of multiple servers, meaning a loop would do the write operations on ALL masters.

Thank you.

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-sphinx/issues/42
