### ISSUE TITLE
URL Management preg_match(): Compilation failed: two named subpatterns...

### ISSUE THREAD

**Issue by kirsenn** [yiisoft/yii2#4857]
I have module structure in my Yii 2.0 application, so I need to call things like

    "module/controller/action"

But 90% of modules and controllers have the same names, for example it looks like

    "news/news/index"
    "support/support/index",
    "profile/profile/update"

It looks not good, I'd like to see just "profile/update"... Then I create the following rules in UrlManager:

    "<module:[a-z]+>/<id:\d+>" => "<module>/<module>/view",
    "<module:[a-z]+>/" => "<module>/<module>/index",
    "<module:[a-z]+>/<action:[a-z-]+>" => "<module>/<module>/<action>",
    "<module:[a-z]+>/<action:[a-z-]+>/<id:\d+>" => "<module>/<module>/<action>",

This gets me the error: "preg_match(): Compilation failed: two named subpatterns have the same name at offset 35"

I don't want my config file has several rules for tens modules. Also I do not want name all controllers with same names, like DefaultController.
I found that PCRE supports [?J modifier](http://php.net/manual/en/reference.pcre.pattern.modifiers.php)  that allows duplicate names for subpatterns.
For example this pattern was automatically generated by Yii won't work with "news/news/view/"

    "#^(?P<module>[a-z]+)/(?P<module>[a-z]+)/view$#u"

But this pattern will

    "#^(?J)(?P<module>[a-z]+)/(?P<module>[a-z]+)/view$#u"

All we need is to add "(?J)" to route rule. I did it manually in yii/web/UrlRule line 197:

    $this->_routeRule = '#^(?J)' . strtr($this->route, $tr2) . '$#u';

What if include support for duplicate names for subpatterns to default Yii.

**Comment by klimov-paul** [comment]
Feature rejected.
