### ISSUE TITLE
Rest an ActiveForm

### ISSUE THREAD

**Issue by DrMabuse23** [yiisoft/yii2#4860]
Hi,

i build an RestApi with ActiveController and i need a suggestion for my Problem

Here the working example tested with postman :
http://screencast.com/t/ypfMKZNsQW

Here when i'am using the ActiveForm:
http://screencast.com/t/ZYHir7tyep

return [{"field":"language_id","message":"Language ID cannot be blank."},{"field":"user_id","message":"User ID cannot be blank."}]

My Form Code:

https://gist.github.com/DrMabuse23/1472a6d39fbcd351f1b5

Would be nice if anyone show me my mistake thx

**Comment by mdmunir** [comment]
:+1:
IMO Its because input use name like `[formName]attribute`.
@samdark How if `ActiveField` has ability to use normal name for input field.
```php
// class ActiveField

    public function input($type, $options = [])
    {
        $options = array_merge($this->inputOptions, $options);
        if($this->useNormalName && !isset($options['name'])){
            $options['name'] = Html::getAttributeName($this->attribute);
        }
        $this->adjustLabelFor($options);
        $this->parts['{input}'] = Html::activeInput($type, $this->model, $this->attribute, $options);

        return $this;
    }

```

**Comment by dynasource** [comment]
I assume this issue has been fixed by https://github.com/yiisoft/yii2/pull/11171
