### ISSUE TITLE
How can RESTful Web app implements sub-resource route?

### ISSUE THREAD

**Issue by wenbin1989** [yiisoft/yii2#4873]
like:
- GET /tickets/12/messages- Retrieves list of messages for ticket 12
- GET /tickets/12/messages/5- Retrieves message 5 for ticket 12
- POST /tickets/12/messages- Creates a new message in ticket 12
- PUT/PATCH /tickets/12/messages/5- Updates message 5 for ticket 12
- DELETE /tickets/12/messages/5- Deletes message 5 for ticket 12

**Comment by RSalo** [comment]
Issue is actual for now?

**Comment by samdark** [comment]
Not really.
