### ISSUE TITLE
FixtureController adjustments

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#4878]
Due to this [discussion](https://github.com/yiisoft/yii2/issues/4792#issuecomment-53725344) fixture controller format should be changed. Also some `indexAction()` that will output all available fixtures would be helpful 
- [ ] change format to `yii fixture/load-all` / `yii fixture/unload-all` 
- [ ] `yii fixture/list` add functionality to see all available fixtures in particular namespace (`yii fixture` will output fixtures list, similar as `indexAction` in console `CacheController`) 
- [ ] add [help](https://github.com/yiisoft/yii2-framework/commit/d8206209c461fab027f41fdc36b11c01dfea0f37#commitcomment-8820383) to index default action

**Comment by dynasource** [comment]
expired
