### ISSUE TITLE
Bootstrap ButtonGroup vertical variation

### ISSUE THREAD

**Issue by stevekr** [yiisoft/yii2#4916]
Hardcoded `btn-group` class in `yii\bootstrap\ButtonGroup` breaks [vertical button group](http://getbootstrap.com/components/#btn-groups-vertical) rendering when using 
```php
'options' => ['class' => 'btn-group-vertical']
```

**Comment by klimov-paul** [comment]
Resolved by https://github.com/yiisoft/yii2-bootstrap/pull/52
