### ISSUE TITLE
Provide queue component

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#492]
Useful for background jobs and all projects processing relatively large amounts of data.

Implementation can be designed the same way as cache i.e. base API + drivers such as:

- "immediate execution" (for local development)
- db
- http://aws.amazon.com/sqs/

Proposed base API:

```php
abstract class Queue {
  // add job to the queue. $data will be passed as an argument to $callback and should be serializable
  public function push($callback, $data)
  {
  }

  // get a job and lock it queue for further processing
  public function get()
  {
  }
}
```

**Comment by sergebezborodov** [comment]
http://kr.github.io/beanstalkd/ is good solution for small-medium size projects. Has full control on tubes and tasks, really fast.
Here is my old implementation https://github.com/sergebezborodov/beanstalk-yii2

**Comment by lubosdz** [comment]
+1 if this can support concurrent/parallel jobs

Just a hint on possible implementation details:
* [Cooperative multitasking via generators by Nikita Popov](https://nikic.github.io/2012/12/22/Cooperative-multitasking-using-coroutines-in-PHP.html)
* [PHP multithreading](http://stackoverflow.com/questions/70855/how-can-one-use-multi-threading-in-php-applications)

**Comment by samdark** [comment]
It's now managed in https://github.com/yiisoft/yii2-queue

**Comment by nineinchnick** [comment]
@samdark I guess I should start splitting and moving my #2378 PR there too

**Comment by samdark** [comment]
@nineinchnick check what's there first.
