### ISSUE TITLE
Console command in separate Action with options

### ISSUE THREAD

**Issue by vladqa** [yiisoft/yii2#4925]
Hi. We have an Console::options() method in which you can declare the parameters for console command. But if we create actions in separate classes:

``` php
use yii\console\Controller;
class TestCommand extends Controller
{
    public function actions()
    {
        return [
            "some-action" => SomeAction::className(),
        ];
    }
} 

class SomeAction extends Action
{
    public $param1;
    public $param2;

    public function run()
    {
     // some code
    }
}
```

We cannot use named params for them: ./yii test/some-action --param1=10 --param2=20
I think it's inconvenient. If I have complex logic in actions with own arguments, I'd like to use it as named parameters in separate console action classes.

**Comment by cebe** [comment]
This is a very rare use case, we will not work on this ourselfs. If you want to send a PR, feel free to do so. I am closing this issue for now.
