### ISSUE TITLE
inputOptions not merged to field options in ->checkbox() 

### ISSUE THREAD

**Issue by maxxer** [yiisoft/yii2#4979]
I was playing with _->field()_ method and _tabindex_. For default text fields it's written this way:

``` php
$form->field($model, 'user', ['inputOptions' => ['tabindex' => '2']])
```

for _->passwordInput()_ works the same

``` php
$form->field($model, 'password', ['inputOptions' => ['tabindex' => '2']])->passwordInput()
```

while for checkboxes this won't work

``` php
$form->field($model, 'password', ['inputOptions' => ['tabindex' => '2']])->checkbox()
```

and must be specified this way

``` php
$form->field($model, 'rememberMe')->checkbox(['tabindex' => '4'])
```

Why is this behavior not consistent thru methods? Quickly having a look at ActiveField.php it seems one of the few methods without an `$options = array_merge($this->inputOptions, $options);` on the top (along with _radio_).
Is this by design? If so maybe it should be worth mentioning it in the documentation?
Thanks

**Comment by dynasource** [comment]
although this could look strange at first hand, you will encounter usecases in which this flexibility is useful.
