### ISSUE TITLE
Can we add a "module" option to AccessRule?

### ISSUE THREAD

**Issue by trntv** [yiisoft/yii2#4999]
And a "matchModule" check, to provide a way to apply rule to all controllers in module.
Use case: I`ve created a behavior that is configured in app config and uses a AccessFilter inside. it provides access filtering across the whole app. "module" option is lacking. 
Something like that

```
protected function matchModule($controller)
    {
        return empty($this->modules) 
            || $controller->module instanceof Application
            || in_array($controller->module->uniqueId, $this->modules, true);

    }
```

Thanks

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/pull/5025#issuecomment-263095769 - should be implemented as partial matching on controller imo.
