### ISSUE TITLE
Could the gii crud labels reduce?

### ISSUE THREAD

**Issue by funson86** [yiisoft/yii2#5003]
In file: yiisoft\yii2-gii\generators\crud\default\views\create.php

```php
$this->title = <?= $generator->generateString('Create {modelClass}', ['modelClass' => Inflector::camel2words(StringHelper::basename($generator->modelClass))]) ?>;
```

So, in the tranlate file, I should define the "Create Post" "Create Comment", and the "Update Post" "View Post" "Update Comment" "View Comment" 

If the code change to:

```php
$this->title = <?= $generator->generateString('Create') ?> . <?= $generator->generateString('{modelClass}', ['modelClass' => Inflector::camel2words(StringHelper::basename($generator->modelClass))]) ?>;
```

I only define the "Create" "Update" "View" "Post" "Comment", and the "Create" "Update" "View" is common for all view files.

Maybe the Space between "Create Post" is a problem. Any other solutions?

**Comment by klimov-paul** [comment]
Translation message like "Create {modelClass}" makes no sense. Different languages may require different syntax for such phrase. Also you will have to translate `modelClass` as well, otherwise it does not make sense.
