### ISSUE TITLE
Routing: Support for camelCase action names in controllers

### ISSUE THREAD

**Issue by manquer** [yiisoft/yii2#5029]
If you have say the following controller structure
````
<?php
namespace app\controllers;
use yii\web\Controller;
class TestController extends Controller
{
    public function actionMyaction(){
       ...  //action logic
    }
    public function actionMyAction(){
       ...  //action logic
    }
}
````
The first route can be accessed using the path ````app-root/test/myaction````

The second route in Yii 1.x would be accessible from the path ````app-root/test/myAction```` 
in Yii2.x routing is by hyphenated structure and the action is accessible only from ````app-root/test/my-action``

This breaks all link backward compatibility, links of course all spread over the web, in mails sent previously etc while an app can be rewritten those links cannot be changed. 

Can there be a provision to provide the compatibility in the core? or else at least this should be included in the migration guide for people considering migrating to 2.

**Comment by spikyjt** [comment]
Mentioning it in the main docs would be a good start!

**Comment by samdark** [comment]
Should be added to https://github.com/yiisoft/yii2/blob/master/docs/guide/runtime-routing.md

**Comment by psihius** [comment]
Adding this to docs is definitely a must. I just had to consult people on why their camelCase action does not work and luckily I had remembered something about that and the "-" from reading dev posts and following the Yii 2 development in general. If you just read the Guide  - y'r screwed, have to google it and pray :)

**Comment by samdark** [comment]
And mentioned in upgrade guide https://github.com/yiisoft/yii2/blob/master/docs/guide/intro-upgrade-from-v1.md

**Comment by ApXaHgheJI** [comment]
Now I'm using the latest versions...
its was really "brain-f@ck" with this routing names and camel cases...
even the routing ( action name ) must be lower case...
disappointed... why ? if developer wants to use CamelCase or other one...

**Comment by cebe** [comment]
it is coved in the docs here: http://www.yiiframework.com/doc-2.0/guide-start-hello.html#creating-an-action
and also in http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html#controller-ids and http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html#action-ids
