### ISSUE TITLE
init command enhancement

### ISSUE THREAD

**Issue by maxmirazh33** [yiisoft/yii2#5034]
Situation: I create project and run `init` command with `--env=Development`. After, I change config files in  app config (not environment). After, I run `init` command with `--env=Production` and deploy app on test server. Now I want get back my dev config for development new features. I run `init` with `--env=Development`, but my config not returned, it's config from environments/dev folder.
Suggestion: before overwriting config files copy current active config in his environment folder (with question about overwrite in console)?

**Comment by samdark** [comment]
Closing since suggestion was already implemented.
