### ISSUE TITLE
Gii generates wrong relation method for one-to-many relation with compound primary key

### ISSUE THREAD

**Issue by uniqby** [yiisoft/yii2#5098]
```sql
CREATE TABLE IF NOT EXISTS `office` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `employee` (
  `id` INT NOT NULL,
  `office_id` INT NOT NULL,
  `name` MEDIUMTEXT NULL,
  `sign_img` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`, `office_id`),
  INDEX `fk_employees_office_idx` (`office_id` ASC),
  CONSTRAINT `fk_employees_office`
    FOREIGN KEY (`office_id`)
    REFERENCES `crm_moika`.`office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;
```

gii generates

```php
class Office extends \yii\db\ActiveRecord
{
  //...

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(Employee::className(), ['office_id' => 'id']);
    }
}
```

but should be 

```php
    public function getEmployees()
    {
        return $this->hasMany(Employee::className(), ['office_id' => 'id']);
    }
```

**Comment by nineinchnick** [comment]
Currently gii incorrectly assumes that hasOne fks may be created only on primary key columns. Instead, it should check if all fk columns form an unique index.

This requires that all schemas implement `findUniqueIndexes`. The following schema does not:

* cubrid by @cebe 
* mssql by @resurtm 
* oci by various authors

pgsql by @lucianobaraglia extracts column names from expressions, which could produce invalid results. Should it be reported as a separate issue?

I can handle fixing pgsql and implementing oci but I don't have access to mssql and cubrid databases.

**Comment by nineinchnick** [comment]
On a second though, unique indexes needs to be checked along with primary key so if `findUniqueIndexes` is not implemented it could be assumed there are no unique keys.
