### ISSUE TITLE
Add handy out-of-the-box ways to filter request

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#5099]
Sometimes (very often indeed) you need to retrieve only one or two `$_POST` / `$_GET` variables.
Introdusing model for that purpose is unnesessary overhead.

Would be nice to have something like this:

```
$somevar = Yii::$app->request->post('somevar', null, ['int', 'max' => 100];
```

```
$somevar = Yii::$app->request->get('somevar', null, ['int', 'max' => 100];
```

Or in controller:

```
public function actionDosomething($id) 
{
    $id = Yii::filter($id, 'int', null, ['max' => 100]);
    ...
}
```

**Comment by asped** [comment]
Maybe the first step could at least be to implement a basic filter to the current functionality of the Request object:

    $id = $request->get('id');   
    // equivalent to: $id = isset($_GET['id']) ? $_GET['id'] : null;

which could work similar to the extenstions which were used in Yii 1.1.x
http://www.yiiframework.com/extension/input/

**Comment by dynasource** [comment]
this looks like too much magic and complexity. Less arguments to functions is better.
