### ISSUE TITLE
if i set attribute in scenario and do not use any validators this attribute become safe

### ISSUE THREAD

**Issue by taral14** [yiisoft/yii2#5112]
Title in russian - Поля прописанные в сценарии стают safe если на них нет валидаторов
Examle
``` php
public function rules() {
    return [
        ['name', 'string']
    ];
}
public function scenarios() {
    return [
        'test' => ['name2']
    ];
}
```
Examle 2
if i use when in validation to attribute and do not use any other validators it become safe
in russian - Поле name2 проставляется через load и setAttributes и по сути стает safe. Хотя на него нет валидатора ни одного.
``` php
public function rules() {
    return [
        [['name'], 'string', 'when' => function(){ return false; }],
    ];
}
```
attribute name become safe

**Comment by mdmunir** [comment]
I hope we have unsafe validator :disappointed:

**Comment by cebe** [comment]
> Topic starter want logic to rules, which will do unsafe attribute if it uses when return falseand this attribute is not found anywhere else in the rules.

This is not possible because `when` is evaluated after the model has been populated with data.

> I hope we have unsafe validator :disappointed:

@mdmunir you can prefix an attribute with `!` in scenario definition to have validation enabled for it but do not allow mass assignment. http://www.yiiframework.com/doc-2.0/yii-base-model.html#scenarios%28%29-detail

> we should *NOT* be adding this attribute to the active attributes, right?

@acorncom please check the guide here: http://www.yiiframework.com/doc-2.0/guide-input-validation.html#declaring-rules

> Determine which attributes should be validated by getting the attribute list from yii\base\Model::scenarios() using the current scenario. These attributes are called active attributes.

active != massively assignable, these are called safe attributes.

**Comment by mdmunir** [comment]
@cebe of course i know. I just hope we can simplify `unsafe` attribute in one place.

**Comment by cebe** [comment]
can you give and example on how this may look like?

**Comment by mdmunir** [comment]
```php
    public function rules()
    {
        return [
            [['status'], 'default', 'value' => self::STATUS_DRAFT],
            [['supplier_id', 'branch_id', 'date', 'items'], 'required'],
            [['supplier_id', 'branch_id', 'status', 'created_by', 'updated_by'], 'integer'],
            [['status', 'created_by', 'updated_by'], 'unsafe'],
        ];
    }
```

**Comment by mdmunir** [comment]
Yii1 have unsafe validator
http://www.yiiframework.com/doc/api/1.1/CUnsafeValidator

**Comment by cebe** [comment]
@mdmunir can you open a new issue with short explaination? Do not want to reopen it here because it is too much discussion about unrelated code.
