### ISSUE TITLE
Possibly make way to batch active record without batching the query

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#5142]
I ran into this one just now, whereby I ran an order summary screen which shows all orders for the day along with their products.

I joined, naturally, with orders and products so that I got all orders and their products back in a single query:

```
Order::find()->joinWith('products')
```

After which I use `each()` which gives me the problem of actually getting duplicate orders back since an order might break batch halfway through its products.

One solution is, yes, to get products separately when I display the order, like so:

```
    $products = $order->getProducts()->joinWith(['product', 'product.title'])->all();
```

But this hits into a wall. The whole reason I am doing batching is because of memory. I do not wish my script to exceed 134MB RAM for just 1067 orders (for example) but the only way is via batching the active record models (since that is what takes all the memory). Doing these separately in the foreach seems to cause a slow but sure memory leakage (I am currently looking into how to properly destruct the `products` var).

Even doing it this way (which does work) causes much higher memory usage than if I could just do:

```
Order::find()->joinWith('products')
```

What would be good is a way to get the query all in one and store it in RAM (most servers can allow like 50K results to be stored in RAM) but batch the active model.

What do you think?

**Comment by Sammaye** [comment]
I just found this as looking back, somehow I overlooked it sorry.

Since this page no longer exists in this form on my site I cannot actually test it now, but that does sound like the reason, so I will say that, as you noted in the tags, the doc probably just need updating on the subject a little.

**Comment by bizley** [comment]
Closing since resolved with `distinct` and documentation of framework query builder should rather not try to show how to solve SQL problem, but what tools are available to solve it.
