### ISSUE TITLE
How use existing min versions of some js libraries, combine it, but not recompress

### ISSUE THREAD

**Issue by macklay** [yiisoft/yii2#5186]
My current project has a lot of bower assets, witch already contains good compressed js files

Im include them like manual said:

```
'yii\web\JqueryAsset' => [
    'js' => [
        YII_ENV_DEV ? 'jquery.js' : 'jquery.min.js'
    ]
],
```

When Im combine and compress my assets bundle by "php yii assets..." cli command, such bowers libs from bundles depends compressed twise and such double compress is not correct(client scripts was broken)

How use existing min versions of some js libruares, combine it, but not recompress by closure compiler?

**Comment by dynasource** [comment]
seem to be solved by https://github.com/yiisoft/yii2/issues/10593#issuecomment-243415321
