### ISSUE TITLE
Problem with combine/compress assets with CDN link

### ISSUE THREAD

**Issue by macklay** [yiisoft/yii2#5194]
Im customize Jquery Asset Bundle in config/main.php like manual said:
```
assetManager' => [
            'bundles' => [
                'yii\web\JqueryAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'js' => [
                        '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js',
                    ]
```

But after combine and compress by "php yii assets..." cli command, in combine js file i see code from jquery lib.

If Im add "custom Jquery Asset Bundle" section from  config/main.php in asset template config, and run asset combine command, i see this:

```
Collecting source bundles information...
Creating output bundle 'webmasters\assets\AllAssets':
  Compressing JavaScript files...
PHP Warning 'yii\base\ErrorException' with message 'file_get_contents(///ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js): failed to open stream: No such file or directory'
```

How use Jquery CDN and did not receive second jquery in common js file all-{hash}.js ?

**Comment by klimov-paul** [comment]
Issue resolved by commit 94f702f
