### ISSUE TITLE
Suggestion for New Ordering Appoarch of Shutdown Functions

### ISSUE THREAD

**Issue by IndeedPlusPlus** [yiisoft/yii2#5219]
It is known that nested `register_shutdown_function` calls can cause problem under HHVM and there were no fix for this currently. The official PHP document does not guarantee that any sub-sequence calls of `register_shutdown_function` can be made during shutdown.

I suggest another approach to arrange the order of executions of shutdown functions by making use of the standard SplPriorityQueue class. Here is a simple example illustrating how this method works.
```php
<?php
function register_shutdown_callback(callable $c, $weight = 0)
{
    static $queue = null;
    if ($queue === null) {
        /* The queue will not be created and register_shutdown_function will not be called */
        /* if the function is not used. */
        $queue = new SplPriorityQueue();
        /*we need the weight as the only parameter for the shutdown callback, so extracting both.*/
        $queue->setExtractFlags(SplPriorityQueue::EXTR_BOTH); 
        register_shutdown_function(function() use ($queue)
        {
            while ($queue->valid()) {
                $arr  = $queue->current();
                $callback = $arr['data'];
                $priority = $arr['priority'];
                call_user_func($callback, $priority);
                $queue->next();
            }
        });
    }
    $queue->insert($c, $weight);
}

/* Some examples. */
register_shutdown_callback(function($weight)
{
    echo 'Hello, world!' . PHP_EOL;
    register_shutdown_callback(function($weight)
    {
        echo 'Hello again.' . PHP_EOL;
    }, $weight - 1);
});

/* This function is ensured to be called at last. */
register_shutdown_callback(function($weight)
{
    echo 'FINAL callback.' . PHP_EOL;
}, -INF);
```
... and the output
```
Hello, world!
Hello again.
FINAL callback.
```

**Comment by klimov-paul** [comment]
We can introduce `Yii::registerShutDownFunction()`, which will use single call of plain `register_shutdown_funtion()`, while all registered callbacks will be stored at static variable (something similar to the original example).
Priority also may make sense, allowing session and logger shutdown callbacks always executed in correct order.

**Comment by samdark** [comment]
What about third party callbacks?

**Comment by klimov-paul** [comment]
Of course we can not cover third party callbacks. But I don't think it is a thing we should worry about.
We can at least make Yii compatible with HHVM at this point and have other already mentioned benefits.
We can add a docs suggesting developers to use `Yii::registerShutDownFuntion()` instead of plain `register_shutdown_funtion()`. This will not affect independent libraries, but at least Yii itself will be more reliable.

**Comment by IndeedPlusPlus** [comment]
Actually, the Facebook guys fixed the nested shutdown function problem about one year ago.
facebook/hhvm#2981 (closed)

**Comment by samdark** [comment]
@IndeedPlusPlus they are reverting their fixed from time to time so I'm not sure it's fixed in current master.

**Comment by IndeedPlusPlus** [comment]
@samdark The fix is in both the current stable version and the dev master, and it had been included long ago. I don't think their have any reason reverting it.
