### ISSUE TITLE
Sphinx facet

### ISSUE THREAD

**Issue by FireDemonsu** [yiisoft/yii2#5234]
How can i get multi result sets from sphinx query?

**Comment by pahanini** [comment]
It's a brilliant idea to add multi result sets and facet option to sphinx\active queury. It seems threre are to main things to do:

- inroduce addFacet function in sphinx\Query, here is a code draft https://github.com/pahanini/yii2-sphinx/commit/cb303a96c7a8a7c3c698f5f211267108b1886425
- create special dataProvider to obtain facet results along with main set result

The first one is simple, but saves a lot of time for all developers who use facet feature.

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2-sphinx/pull/2

**Comment by pahanini** [comment]
Looks great!

By the way `show meta` sphinx command provides less resourceful way to get total number of rows rather then ActiveDataProvider::prepareTotalCount() uses. But disadvantage of this method is SHOW META should ony be called after main query.

**Comment by klimov-paul** [comment]
Resolved by https://github.com/yiisoft/yii2-sphinx/pull/2

**Comment by klimov-paul** [comment]
@pahanini, see https://github.com/yiisoft/yii2-sphinx/pull/3
