### ISSUE TITLE
migration subdirectories

### ISSUE THREAD

**Issue by VinceG** [yiisoft/yii2#5293]
This is a suggestions and maybe a discussion. Currently there is one migration directory where all migrations reside, for large applications the amount files in that folder can grow quickly (i have now little over 300 files in that directory). Since we can't delete them what i did was extend the migration class and new migrations created are created under migrations/Y_m sub directories. (ie migrations/2014_09, migrations/2014_10) this allows a smaller number of files per sub directory which is easier to navigate, search etc..

This might not be an important feature or something a lot of developers will use, just a thought i had and a suggestion. not sure if it's a core feature or an extension that should have this.

Thanks.

**Comment by klimov-paul** [comment]
Resolved by namespaces usage. See #12511
