### ISSUE TITLE
Flash messages improvements (Alert widget)

### ISSUE THREAD

**Issue by TomaszKane** [yiisoft/yii2#5298]
Hi, I have some idea to improve [Alert widget](https://github.com/yiisoft/yii2/blob/master/apps/advanced/frontend/widgets/Alert.php):
I want add new Flash message like that:
```php
// succes (default)
Alert::add(Yii::t('msg', 'Operation completed successfully.'));
// error/danger
Alert::add(Yii::t('msg', 'Operation failed.'), Alert::TYPE_ERROR);
// few errors
Alert::add(['Error 1', 'Error 2'], Alert::TYPE_ERROR);
// ActiveRecord validate errors
Alert::add($model->getErrors(), Alert::TYPE_ERROR);
```
not like that:
```php
Yii::$app->getSession()->setFlash('success', Yii::t('msg', 'Operation completed successfully.'));
Yii::$app->getSession()->setFlash('error', Yii::t('msg', 'Operation failed.'));
Yii::$app->getSession()->setFlash('error', ['Error 1', 'Error 2']);
// ...
```

Main goals is:
1. easy print ActiveRecord errors as bootstrap alerts
2. add new flash message via "write less do more"
3. avoid to write strings like "success" / "error" as message type (use const)
4. alert message can be: string, array or multidimensional array

I make some ugly fork to do that in my private project [here](https://github.com/TomaszKane/yii2/blob/master/apps/advanced/frontend/widgets/Alert.php) maybe someone have time to improve it (made more correct in Yii terms)?

PS. Yes, its minor priority :-)

**Comment by njitram** [comment]
I too am missing the properties inside a model for success messages. We do have error messages but not a success message(s) for a particular model.

    $model->getErrors() //we have
    $model->getSuccess()

**Comment by cebe** [comment]
@njitram if model validation succeeds there should be no need for any messages. Note that validation error messages are completely unrelated with flash messages.

About this issue: I think this is an application specific thing and should be implemented per application as needed.
