### ISSUE TITLE
HasMany via two relations

### ISSUE THREAD

**Issue by angelcoding** [yiisoft/yii2#5341]
I have the following tables and fields (simplified a bit here) and associated AR models

```
tbl_account
id, plan_id, name

tbl_user
id, name

tbl_plan
id, name

tbl_account_user
id, account_id, user_id, type
```

The FK's are obvious.

Basically ...
An account has one plan.
User and account is many to many.
A plan can belong to many accounts and therefore be related to many users.

I want to get all users that are related to a plan so I have setup the following relations in the Plan model ...

```
public function getAccounts()
{
   return $this->hasMany(Account::className(), ['plan_id' => 'id']);
}
public function getAccountUsers()
{
    return $this->hasMany(AccountUser::className(), ['account_id' => 'id'])->via('accounts');
}
public function getUsers()
{
    return $this->hasMany(User::className(), ['id' => 'user_id'])->via('accountUsers');
}
```

If I call $planModel->accountUsers I get the expected models but calling $planModel->users returns no results.

I have done some digging and have found the problem is that the user models are correctly fetched from the db but they are indexed by the account_id rather than the user_id so are not found when populating the relation.

Is this expected behavior?
Should I be doing something differently in this scenario?

I know this is probably a rare case and I'm most likely doing something stupid but I couldn't find any docs or examples anywhere for setting up these types of multi-level relations so it would be very useful to know where I'm going wrong.

**Comment by cebe** [comment]
> @qiangxue if what I have just written in the test did not pass I'd consider this a major issue with AR relations that prevents release, as the test passes I am fine with postponing it.

this test passes because all tables share the same name of the primary key `id` and accidentally the tested pks match the expected result :-/

I have changed the primary keys in the test data and now that test fails. See also #7625 for another failing test.

**Comment by cebe** [comment]
too much work to fix this in 2.0.9, set for 2.0.10

**Comment by whuhacker** [comment]
After 2+ years I just run into the same situation in my project. so when will this problem be fixed?

**Comment by cebe** [comment]
As the label says: "complexity:hard" ;) so it is not likely to be fixed very soon. This needs a rewrite of the bucket matching algorithm in eager loading implementation of AR which is quite complex already and might get even more complex when fixing this.

**Comment by SamMousa** [comment]
If this is complex and no one is working on it yet, should the milestone be removed?

**Comment by cebe** [comment]
I am planning to work on this soon.

**Comment by Erkebulan69** [comment]
I've met with this problem a while ago, and I hope that you'll fix it asap

**Comment by darkphase01** [comment]
I have encountered this one too. Hope there's someone who can patch this. Thanks :)

**Comment by DavidPrada** [comment]
I have encountered the same problem as them. Have anyone found a fix?

**Comment by TiaraMF** [comment]
Do you have a time frame as to when we can expect this to be fixed? Needing ASAP. Thank you!

**Comment by samdark** [comment]
Nope. Hopefully @carsten will have enough time to prepare it for the next release. You can speed things up significantly by implementing it yourself and making a pull request.

**Comment by TiaraMF** [comment]
Thank you for getting back so quick! That is awesome. When is the next release?

**Comment by samdark** [comment]
In a month or so if everything will go well.

**Comment by TiaraMF** [comment]
Great! Thank you.

**Comment by rebill** [comment]
@samdark Look forward to your good news.

**Comment by juffin-halli** [comment]
I encountered this problem. In my case the problem is: eager loaded records has typecasted attributes, but junction rows attributes are just raw strings and this valus gives different serialized keys. So as quick fix is it possible to typecast junction rows?

**Comment by TiaraMF** [comment]
Hello Alexander,

I am just looking for an update on when I might expect this fix to be
implemented? Can I please get an update?

Thank you kindly,

Tia

On Wed, Jun 28, 2017 at 8:59 AM, Alexander Makarov <notifications@github.com

**Comment by samdark** [comment]
It's planned for 2.0.14 unless someone will take care of it earlier.

**Comment by TiaraMF** [comment]
Just to clarify, do you mean February 2nd, 2018?

**Comment by TiaraMF** [comment]
I meant Feb 2018 - or are you talking about a version number?

**Comment by samdark** [comment]
Sure we're OK merging PR earlier.

**Comment by TiaraMF** [comment]
Hello, 

I am just looking for am update, as GitHub shows this is one month past due.

Any update would be much appreciated.

Thank you,

Tia

**Comment by samdark** [comment]
2.0.13 is in the making and this issue won't be solved there.

**Comment by eknowlton** [comment]
I keep running into this issue as well. Any plans to solve this in the future, or is hasMany through not a fully working feature?

**Comment by shirase** [comment]
@lebedev19xx Yes it fixed and already merged.
