### ISSUE TITLE
Gii: overriding default ActiveRecord methods

### ISSUE THREAD

**Issue by etki** [yiisoft/yii2#5412]
Hi.
We've run into scenario today that made Gii will override default ActiveRecord method (table `attribute` => `getAttributes()` has overriden default `\yii\db\ActiveRecord::getAttributes()` method), and Gii could not create CRUD because of strict standards that prevent from dwindling method signature. This, of course, is not a bug (Gii is working just as expected), but, i guess, Gii should prevent users whenever they are going to override a method they probably don' want to override.

**Comment by Faryshta** [comment]
I think @yii-bot should move this to yii2-gii and this seems like an easy fix.
