### ISSUE TITLE
Making validation rules adjustable for behaviors

### ISSUE THREAD

**Issue by dapatrese** [yiisoft/yii2#5438]
Hi!

I'd like to suggest a small enhancement to make validation rule handling more flexible, e.g. for behaviors:

I'm looking for a way to make certain validation rule sets reusable for frequently recurring model properties within a project, using model behaviors.

Assuming a SlugBehavior (different from `yii\behaviors\SluggableBehavior`) being applied to a model to operate on its property "slug". Besides some other things, this behavior should ensure that certain rules for an UniqueValidator and a MatchValidator will be added (generated by the behavior). 

``` php
// class \common\models\SomeModel 
{
    public function behaviors()
    {
        return [
            'slug' => [
                'class' => SlugBehavior::className() ,
                'titleField' => 'title',
                'slugField' => 'slug',
            ],
        ];
    }
```

A rather clumsy solution might simply merge those manually (that would mean for each behavior and for each affected model):

``` php
// class \common\models\SomeModel 
{   
    public function rules()
    {
         return ArrayHelper::merge( $this->getRulesFromSlugBehavior() , [
            [ /* my normal rules for this model */ ]
         ]);
    }
}
```

Otherwise the event `BaseActiveRecord::EVENT_BEFORE_VALIDATE` could be used, like in `yii\behaviors\SluggableBehavior::validateSlug()`. In that case the validator must be constructed manually without using `\yii\base\Model::createValidators()` and thus loosing compatibilty (or doubling functionality) regarding array syntax and object construction.

I cannot find a good entry point where `Model::rules()` could be modified by behaviors without extending core classes. But as far as I could see, `Model::rules()` is used only in `Model::createValidators()`, so it might be easy to establish an intermediate step here:

``` php
// class \yii\base\Model
{
    /**
     * leave this method for derived classes, as usual
     */
    public function rules()
    {
        return [];
    }

    /**
     * intermediate step
     */
    public function getFinalRules()
    {
        $rules = $this->rules();

        // offer method to post-process $rules via model behaviors using something like events 
        return $this->applyMagicTo( $rules );
    }

    /**
     * use getFinalRules() step instead of rules()
     */
    public function createValidators()
    {
        $validators = new ArrayObject;
        foreach ($this->getFinalRules() as $rule) {
            [ /* ... */ ]
    }
```

Does that make sense?
THX

(edit: paste error)

**Comment by klimov-paul** [comment]
Possible solution may be introducation of the new event called 'onValidatorCreate', which can be triggered here:
https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L415

**Comment by dynasource** [comment]
> Appending validators to $owner->validators seems to work well for both model validation and mass assignment.

**Comment by timkelty** [comment]
> Possible solution may be introduction of the new event called 'onValidatorCreate', which can be triggered here:

This would be ideal for what I'm trying to do.

**Comment by davidhirtz** [comment]
@klimov-paul's proposal is a very good solution, because `Model::getValidators()` is not automatically called when attaching the behavior to a model (like in the other solutions above).
