### ISSUE TITLE
Codeception FixtureHelper does not unload Fixtures before suite

### ISSUE THREAD

**Issue by viilveer** [yiisoft/yii2#5441]
There seems to be problem when
- you have unit tests before acceptance tests 
- you have dependant fixtures with MySQL foreign key constraint (RESTRICT)

Because fixtures are unloading at `setUp()` in unit tests. FixtureHelper module calls only `loadFixtures()` in `_beforeSuite()`. That causes delete in wrong order (dependant fixtures are not deleted before called fixture) and MySQL finishes with "Integrity constraint violation". I suggest that `unloadFixtures()` should called in `_beforeSuite()` before `loadFixtures()`

I'm using Yii2 RC with latest 2.0.6 codeception.

**Comment by dynasource** [comment]
see @https://github.com/yiisoft/yii2/issues/5442
