### ISSUE TITLE
ActiveFixture does not delete actual data in unload() method

### ISSUE THREAD

**Issue by viilveer** [yiisoft/yii2#5442]
ActiveFixture unload does not call `resetTable()` in `unload()` and this causes trouble when you have dependant fixtures with foreign key constraints. As ActiveFixture tries to `loadFixtures()`, which calls `resetTable()` it fails as the dependant data is not deleted. The issue description is related with #5441

**Comment by tom--** [comment]
I have one ActiveFixture that depends on another. I'm using Codeception and following the Guide and taking hints from yii2-app-advanced.

If there's a fatal error during a test then the rows are left in the table. Re-running the test errors thus:

    yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`spinitron2`.`persona`, CONSTRAINT `persona_fk_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`))
    The SQL being executed was: DELETE FROM `user`

I guess because unloading the fixtures in `yii\codeception\TestCase::setUp()` does not respect the fixture dependencies.

The fix (thanks CeBe) was to add to each of my fixture classes:

    public function unload()
    {
        $this->resetTable();
        parent::unload();
    }

**Comment by xVismutx** [comment]
you can even trigger unload methom instead of resetTable in load method... If you chose this way...

**Comment by klimov-paul** [comment]
I can see no other option but having `resetTable()` at both `load()` and `unload()`.

> but we already have yii fixture/unload-all or simple yii fixture/unload

As far as I see these commands are useless now, since `ActiveFixture::unload()` does not deletes data from table.

Yet another solution can be moving `resetTable()` to `unload()` and modify `FixtureTrait::loadFixtures()` to always call `FixtureTrait::unloadFixtures()`:
```php
public function loadFixtures($fixtures = null)
{
    $this->unloadFixtures($fixtures);
    ...
}
```

**Comment by mklemarczyk** [comment]
Hi, If you want unload fixture in load function you should care about depends.
I read documentation that says unload remove all fixture data.

Take a look at: https://github.com/yiisoft/yii2/blob/master/framework/test/FixtureTrait.php#L33

You should clean up this thing, because you implement a lot of ways to do the same thing.
* Order in fixtures() on FixtureTrait
* depends property in  yii/test/Fixture

And still it does not WORK! Do you want provide reliable solution OR NOT?

**Comment by slinstj** [comment]
The `resetTable()` workaround cited by @tom-- does not work for me.

This is my **mysql** workaround and should be added to each fixture model that has some dependant table:

```php

<?php
namespace tests\codeception\common\fixtures;

use yii\test\ActiveFixture;

class VariationFixture extends ActiveFixture
{
    public $modelClass = 'common\models\Variation';

    public function beforeLoad() {
        parent::beforeLoad();
        $this->db->createCommand()->setSql('SET FOREIGN_KEY_CHECKS = 0')->execute();
    }

    public function afterLoad() {
        parent::afterLoad();
        $this->db->createCommand()->setSql('SET FOREIGN_KEY_CHECKS = 1')->execute();
    }
}
```

**Comment by githubjeka** [comment]
@slinstj thank you for your crutch. :)

**Comment by slinstj** [comment]
@githubjeka :+1:

**Comment by akaSStalkALEX** [comment]
Is there same solution for Postgres?

**Comment by kossmoss** [comment]
What do you think about adding one more field to Fixture (public $unloadFirst = [] or something like that) which will contain links to all the **dependent** fixtures. Using this field it will be not too complicated to build unloading mechanism actually clearing all the tables in proper order and without any foreign key violations.

We don't need any hard changes in loading fixtures - just add check if we need to unload data in any dependent tables.

For example, fixture **OrdersFixture** is dependent of **UserFixture**. In database schema we also have foreign key not allowing us to have Orders not belonging to any User. We could build these fixtures like that:

```
class OrderFixture extends ActiveFixture
{
    public $modelClass = 'common\models\Order';
    public $depends = ['tests\codeception\unit\fixtures\UserFixture'];
}

class UserFixture extends ActiveFixture
{
    public $modelClass = 'common\models\User';
    public $unloadFirst = ['tests\codeception\unit\fixtures\OrderFixture'];
}
```

Case 1: We call UserFixture->load, it will check it's own **$unloadFirst** array and perform clearing data for all fixtures there **before** calling resetTable() in UserFixture. This will unload OrderFixture prior to any actual user data loading. So after this we'll have data in table_user and empty table_order table.

Case 2: We call OrderFixture->load, it will check it's own $depends, will call UserFixture->load, which will do all the same as described in Case 1 (unload orders, load users). And after that will load it's own orders data as expected - into already emptied table. Both fixtures loaded and no any problems with foreign key violations.

Can we enhance Fixture this way or I missing something? This also can be used to make more complex depedencies (inherited dependencies, multiple dependencies). I see the only one significant consequence - it can make difficult the tracking of fixture loading/unloading order. But I don't think it's too complicated for developers who knows how to use foreign keys in their database. Those who don't use foreign keys with restrictions, may continue to use $depends field only.

**Comment by Kolyunya** [comment]
ActiveFixture is basically unusable in current state because of this issue. More than 2 years passed since the original post. Can we do something about it?

**Comment by dynasource** [comment]
There are many opportunities to improve the architecture around fixtures. Fact is that focus lies on other topics. With respect to the Fixture topic and testing. A good alternative is to create records right before you are using them. This is less error prone and easier to understand. In terms of performance, it doesnt really matter but in terms of debugging during tests, a lot of time is saved.

**Comment by StalkAlex** [comment]
@Kolyunya  what do you mean? We're using fixtures with depedences and everything seems fine.

**Comment by leandrogehlen** [comment]
Does not make send that `resetTable` happens on `load` method, it's necessary to move to `unload`.
I did understand why is not possible todo this change?

**Comment by samdark** [comment]
@leandrogehlen how about failed tests? Unload won't happen and everything would stuck, right?

**Comment by leandrogehlen** [comment]
Exactly, i did this change https://github.com/Codeception/Codeception/pull/4016, but this was not enought,
Because resetTable does not happens on `unload` method

**Comment by leandrogehlen** [comment]
>  how about failed tests?
```php
class CategoryFixtrue extends ActiveFixture 
{
     public $modelClass = 'app\models\Category';
}

class ProductFixtrue extends ActiveFixture 
{
     public $modelClass = 'app\models\Produto';
     public $depends = ['app\tests\fixtures\CategoryFixtrue'];
}
```
How the `unload` method don't execute `resetTable` after tests the tables will have records,
in the next execution, the `resetTable` will happens on `load` method and the first command will be:
```
`delete from `category``

if table `product` have fk we will have fk constraint exception

**Comment by nurbeknurjanov** [comment]
Hey guys
I spent hours confusing why unload doesn't work.
If you gonna consider that unload is useless then you should take of that from documentation.
It saying that unload clear data, but in fact it doesn't. It really confuses and lost energy thinking that I did wrong test.

**Comment by leandrogehlen** [comment]
> I would edit documentation myself if u let me to prevent other developers from that confusing.

@nurbeknurjanov , i think that the problem is the feature and not the documentation.
I think that edit the documentation does not solve it

**Comment by nurbeknurjanov** [comment]
@leandrogehlen 
This issue is from 2014. Still is not solved. And is not going to be solved soon. And untill this is not solved people are reading the documentation and trying to implement this function. Off course it is not working, and we think that we did something wrong in fact that documentation feeds us not correct information. 
Or it would be solved, but I doubt it would be soon, so untill that moment documentation I guess should have some note information letting us to know, that this function is not prepared.

**Comment by leandrogehlen** [comment]
I have started the work to solve this issue, then i found https://github.com/yiisoft/yii2/blob/master/framework/test/InitDbFixture.php that must be used when we have DB-related tests.

I will open the PR with necessary changes to work without `yii\test\InitDbFixture`

I don't know what decision will be chosen:
- Accept the PR and  remove `yii\test\InitDbFixture`
- Change docs to clarify how to use Fixtures with DB-related tests

**Comment by StalkAlex** [comment]
@leandrogehlen we're using InitDbFixture it's quite helpful in part of turning off foreign checks and removing it is definitely BC.

**Comment by lenrsmith** [comment]
As of https://github.com/yiisoft/yii2/pull/14001 fixtures are broken for us. If a test errors out, unload() does not get called and the data remains in the DB for the next test. This is causing Integrity Constraint violations. Leaving resetTable() in the load() method solves the problem.

**Comment by leandrogehlen** [comment]
Can you show an example how this error happens?

**Comment by lenrsmith** [comment]
I can give you the scenario. By example, are you wanting to see code?

We setup a test with the appropriate fixtures to add data to the DB. Not all of the PKs are auto generated and some columns have a unique index. When the first test runs, the fixture data is loaded into the DB, but the test produces an error (any error that is not fatal to the app but it interrupts the test). The subsequent test gets loaded with the fixture data still loaded into the DB which causes the Integrity Constraint issues. Reviewing the DB after the test run, fixture data is still present in the DB.

**Comment by leandrogehlen** [comment]
I can't see the problem this way, and if you pay attention, the unload method is invoked before load
this way the first thing to happens before a test is to clean data.

Maybe you can build a small project with this scenario to show the problem

**Comment by lenrsmith** [comment]
@leandrogehlen Found the heart of the problem. We have a sizeable project with quite a few tests still using yii2-codeception. Since it is deprecated, changes are not propagating back to the old extension thus breaking our tests.

This wouldn't be a big deal if the documentation didn't rely on the extension: http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html

**Comment by cebe** [comment]
please open a new issue if there is a problem that needs to be fixed.
