### ISSUE TITLE
CORS bug when preflight OPTIONS request sent

### ISSUE THREAD

**Issue by YuriyPobezhymov** [yiisoft/yii2#5457]
Hello.
I have angular.js based app. It uses "application/json; charset=utf-8" content type when make POST request through CORS. When I use text/plain there are no preflight OPTIONS, but with "application/json; charset=utf-8" it occurs.

Bug is that preflight request finished, but POST not happends; Google Chrome outputs:
Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

Here is described how and when preflight sends: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

I found bug in Yii2 core yii\filters\Cors.
I did add after some researching this code in prepareHeaders method:
```PHP
if (isset($requestHeaders['Access-Control-Request-Headers'])) {
   $responseHeaders['Access-Control-Allow-Headers'] = implode(', ', $this->cors['Access-Control-Request-Headers']);
}
```
after those lines:
```PHP
if (isset($requestHeaders['Access-Control-Request-Method'])) {
  $responseHeaders['Access-Control-Allow-Methods'] = implode(', ', $this->cors['Access-Control-Request-Method']);
}
```
then it started working correctly.

Thanks, Yuriy.

**Comment by kirill-konshin** [comment]
Bug still exist... I had to override the base Cors class's prepareHeaders() method and add what @YuriyPobezhymov has proposed in first comment. So far it works for me, but this definitely has to go in framework.

**Comment by askobara** [comment]
I have the same bug.
@YuriyPobezhymov thanks for your research!

**Comment by Larzans** [comment]
@YuriyPobezhymov +1 for the fix
@qiangxue when will this be included, or is there a downside to this solution?

**Comment by qiangxue** [comment]
I reviewed the code. It seems the current code should be working fine. If you still have problem, please give details about how you use this filter and what are the request and response headers you have.

**Comment by askobara** [comment]
Hello, @qiangxue 
I have angularjs app which use Yii2 as backend.
There are headers when I dont use @YuriyPobezhymov patch

Request Headers
```
OPTIONS /auth/validate_token HTTP/1.1
Host: api.dev
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: GET
Origin: http://localhost:3000
Access-Control-Request-Headers: expiry
Accept: */*
Referer: http://localhost:3000/
```
Response Headers
```
HTTP/1.1 200 OK
Server: nginx/1.6.2
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/5.6.1
Access-Control-Allow-Origin: http://localhost:3000
```
And I have error in browser console
```
XMLHttpRequest cannot load http://api.dev/auth/validate_token. Request header field expiry is not allowed by Access-Control-Allow-Headers.
```

After applying patch the response headers look like this:

Response Headers
```
HTTP/1.1 200 OK
Server: nginx/1.6.2
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/5.6.1
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Headers: expiry
```

There is my cors config:
```php
'cors' => [
    // restrict access to
    'Origin' => ['http://localhost:3000'],
    'Access-Control-Request-Methods' => ['GET', 'POST', 'OPTIONS', 'DELETE', 'PUT'],
    'Access-Control-Request-Headers' => ['expiry'],
]
```

**Comment by qiangxue** [comment]
Your cors config should use `'Access-Control-Request-Headers' => ['Expiry']`

**Comment by askobara** [comment]
yep, you are totally right!
I never thought that it may be case sensitive, because angular src doesn't contains any capital letters.

**Comment by kirill-konshin** [comment]
Per http://www.w3.org/Protocols/rfc2616/rfc2616.html: Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

**Comment by askobara** [comment]
So what about using `ucfirst` in Cors filter to avoid this behaviour?

**Comment by kirill-konshin** [comment]
It has to be all lower case (Content-Type is a valid header name as well as content-type)

**Comment by qiangxue** [comment]
It should be fine now. Could you please confirm it? Thanks.

**Comment by askobara** [comment]
yeah! now it's work with any values!
@qiangxue thank you!
