### ISSUE TITLE
non-linear jsClientValidation triggered using  yii\widgets\ActiveField::checkboxList 

### ISSUE THREAD

**Issue by devivan** [yiisoft/yii2#5459]
I use a yii\widgets\ActiveForm having:
enableClientValidation => true, 
beforeValidate'         => 'function(a,e,m){ console.log("BefValid"); }'
'validateOnChange' => true,

Inside the form an  yii\widgets\ActiveField::checkboxList with 4 elements.

My function is triggered if the element is lowest unselected checkBox. So 
- if I check the 4th, 3th, 2nd and 1st checkbox is works well
- if I check the 2nd the 3rd and 4th won't work, but if then I check the 1st works

**Comment by dynasource** [comment]
it looks like this is fixed by commit https://github.com/yiisoft/yii2/commit/418b27326c8753e1224080a958930550ff4d11ac
