### ISSUE TITLE
file validator and mimeTypes by mask

### ISSUE THREAD

**Issue by dizews** [yiisoft/yii2#5469]
Hello.
I need to upload images and pdf files therefore I can't use image validator and I need to use file validator.
My proposal is to add checking ```mimeTypes``` by mask similar on html5 client validator of input tag.

example: ```'accept' => 'image/*,.pdf'```

**Comment by kirsenn** [comment]
can implement this feature if need

**Comment by SilverFire** [comment]
Thank you, go ahead!
I think it should be done only for `mimeTypes` property, `extensions` logic should stay untouched.
Also we need to take care about JS client-side validation.

**Comment by kirsenn** [comment]
https://github.com/yiisoft/yii2/pull/10393

**Comment by SilverFire** [comment]
Merged with adjustments https://github.com/yiisoft/yii2/commit/7aef67187285ba43d8a07707d623c0bf8aef992b

Thank you
