### ISSUE TITLE
Pjax - ScrollTo option

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#5479]
In the docs:

#### $scrollTo public property
```boolean|integer $scrollTo = false```

> How to scroll the page when pjax response is received. If false, no page scroll will be made. Use a number if you want to scroll to a particular place.

But in reality, you can't set it to true to automatic scrollTop, it needs to be setted to 1.

**Comment by SilverFire** [comment]
From [docs](https://github.com/yiisoft/jquery-pjax/blob/master/README.md)

key | default | description
----|---------|------------
`scrollTo` | 0 | vertical position to scroll to after navigation. To avoid changing scroll position, pass `false`.
