### ISSUE TITLE
Enhance reusability of external actions within the controller

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#5481]
Currently you can call `$this->runAction($id, $params = [])`, but this method does not accept constructor arguments for action. 

`\yii\base\Controller::createAction` accepts only `$id`, 
while `\yii\base\Action::__construct($id, $controller, $config = [])` method has also `$config` argument.

So if you need to pass action config in constructor - you need to create action object explicitly and then call it's `run()` method. 
But if you call `run()` directly - `beforeAction` and `afterAction` are not fired automatically.

Would be nice something like this:

```
$this->runAction($id, $params = [], $config = [])
```

**Comment by smartmafia** [comment]
how to create object other controller in another controller in yii2 framework

**Comment by sculover** [comment]
Hi Qiang,
I think I have a trouble related to this topic. The scenario is I need to use runAction in one module. but I  also need to pass an array as the action parameter. like $module->runAction($route,$parameters);but the $parameters can not be accepted in the specified action. 
could you please point out the issue? Thanks.

**Comment by dynasource** [comment]
@SDKiller, from a architectural pespective, its not logical to add config to runAction(). If its done, it should be createAction().  I think it is even more useful to enable configuration for actions in a $actions property in Controller. How about that?

**Comment by SDKiller** [comment]
@dynasource 

It's pretty much time since that issue and I cannot recall now why I needed such shorcut to create actions on-the-fly.
You may close it.
