### ISSUE TITLE
Modules and layouts

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2#5529]
In my module I've a controller who extends another controller(which isnt in any module), who has standalone actions.
Those actions change theirs layouts (who isnt in any module).

In my module file, I need to add this in init() function
```php
$this->setLayoutPath('@app/views/layouts')
```

this is normal?
For what I've done with the framework, the normal behavior for me would be setting
```php
public $layoutPath = ...
```
but this doesnt work, it keeps saying I want the layout in $viewPath

And, if I dont specify any layout config in module (that would be nice) it throws the same error, because of $viewPath

(Yes, the default goes to layout root application. But I've lines in my controllers who change their layouts, and then, I get the error)

Summary: 

When using modules, controllers who has some actions or other controllers who change layout (which isnt in the same module) break the $layoutPath variable in module config file (eg module.php)

**Comment by klimov-paul** [comment]
Closed since there is no response from the author.
