### ISSUE TITLE
GridView Javascript method of yii.getQueryParams

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2#5546]
If i have inner array in GET request, method yii.getQueryParams ignore all subarray values except last. For example, query string is:
"document/index?Document[statusGroup]=&Document[statusGroup][]=1&Document[statusGroup][]=2&Document[statusGroup][]=3&Document[statusGroup][]=4&Document[showTechnical]=0&Document[showTechnical]=1&dateInFrom-document-dateinfrom=&Document[dateInFrom]=&dateInBefore-document-dateinbefore=&Document[dateInBefore]="

but what i looking in firebug:
Document[dateInBefore]  ""
Document[dateInFrom]    ""
Document[showTechnical] "1"
Document[statusGroup]   ""
Document[statusGroup][]     "4"
dateInBefore-document-dateinbefore  ""
dateInFrom-document-dateinfrom  ""

For fast test in debugger:
yii.getQueryParams("document/index?Document[statusGroup]=&Document[statusGroup][]=1&Document[statusGroup][]=2&Document[statusGroup][]=3&Document[statusGroup][]=4&Document[showTechnical]=0&Document[showTechnical]=1&dateInFrom-document-dateinfrom=&Document[dateInFrom]=&dateInBefore-document-dateinbefore=&Document[dateInBefore]=")

P.S. sorry for bad english

**Comment by dynasource** [comment]
cannot reproduce. If someone can, please let us know. Well open it again.
