### ISSUE TITLE
Controller->goBack/returnUrl with shared hosting (under the same domain)

### ISSUE THREAD

**Issue by chris68** [yiisoft/yii2#5551]
My feeling is that the returnUrl is set only when a session is created. And that causes a funny behavior in certain situations.

Suppose you have two applications on a dev system like

http://localhost/yii-application-test/frontend/web/
http://localhost/yii-application-test/backend/web/

With the standard config they share their cookies on the domain _localhost_. So if you login/logout in backend and then switch to frontend and login you will be redirected to backend afterwards. Reason: the returnUrl has been remembered when the session was created and that was directly after the logout in backend.

So if you do not want to have this you need to use different sessions for frontend and backend (e.g. http://webtips.krajee.com/different-backend-frontend-sessions-yii-advanced-app/)

Maybe, that should be added to the documentation since most beginners start with local scenarios and such things will drive them guys crazy.

(issue created from comments in https://github.com/yiisoft/yii2/issues/4343)

**Comment by dynasource** [comment]
fixed by https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-shared-hosting.md
