### ISSUE TITLE
MongoDB guide

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#5556]
Guide has it in table of contents but it's currently missing.

https://github.com/yiisoft/yii2/tree/master/extensions/mongodb

**Comment by alexandernst** [comment]
Why did this get closed? I can't see it here http://www.yiiframework.com/doc-2.0/guide-db-mongodb.html

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/README.md#working-with-databases

**Comment by samdark** [comment]
It will be rendered to the website with next release.
