### ISSUE TITLE
How to access Fixture Objects inside Acceptance Test

### ISSUE THREAD

**Issue by rptts** [yiisoft/yii2#5575]
Hi there,

I'm using Codeception to write some tests, and I've reached a situation where I need to load some fixtures into DB and use it to assert some condition...

I have configured the suite to use `FixtureHelper`, and things are being loaded into DB just fine.

However, I cannot access the fixture object like explained in the docs (http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html)

	...
	...
	// returns the UserProfile model corresponding to the data row aliased as 'user1'
	$profile = $this->profiles('user1');
	...
	...

The above does not work. Neither does `$I->profiles('user1');`
If I call `$I->fixtures()` it just returns me the configuration array, which is of no use... I need to either access the row data or the ActiveRecord model!

How can I access the fixture data when on an Acceptance or Functional Test?

Thanks in advance!!

**Comment by TriAnMan** [comment]
I've made a workaround for this issue. Reviews are welcome: https://github.com/yiisoft/yii2-app-advanced/pull/63
