### ISSUE TITLE
Error in Formatter normalizeDateTimeValue

### ISSUE THREAD

**Issue by Erik-r** [yiisoft/yii2#5577]
I got the following Error:
![formatter_error](https://cloud.githubusercontent.com/assets/2463365/4648670/f140d97c-5483-11e4-9241-13fad6ffb5a9.JPG)
I found out that `$timestamp` is a DateTime object which causes the error. The source come from `normalizeDateTimeValue`
![formatter_cause](https://cloud.githubusercontent.com/assets/2463365/4648707/2859c108-5484-11e4-8bea-bba609a79226.JPG)
IfI format the DateTime object to a timestamp with `->format('U')` then it works. See:
![formatter_correction](https://cloud.githubusercontent.com/assets/2463365/4648737/5935a68e-5484-11e4-98bb-0822c3b401dc.JPG)
I think that Intl's format function expects a number.

**Comment by cebe** [comment]
Well, we are actually skipping these tests for INTL on 32bit systems: https://github.com/yiisoft/yii2/blob/master/tests/unit/framework/i18n/FormatterDateTest.php#L203
We may use PHP as the fallback for date ranges >= 2038 and < 1902
