### ISSUE TITLE
GridView::filterSelector  not flexible

### ISSUE THREAD

**Issue by mitalcoi** [yiisoft/yii2#5597]
I want to set filter selector:
```php
"$id input :not([type='checkbox']), #$id select"
```
but I cannot do it without overriding GridView::getClientOptions(). Maybe GridView::filterSelector will not append the default selector("#$id input, #$id select"), but replace it with?

**Comment by xemware** [comment]
You can close this, I see in the code filterSelector is APPENDED to the base/default selector.
