### ISSUE TITLE
yii\rest + AngularJS $resource = 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#5599]
I try to save JS objects via AngularJS $resource, it calls server with given URL intact not appending any action names, supposing what action will be chosen by server based on HTTP verb (POST, GET etc.).

On the Yii side, this goes to index action since no extra URL part given, and it only does **filter**, not **choose**, action by verb.

By what exact definitions of REST ( RPC ? Just looked to guide - no quick answer ) are the Yii2 and Angular built ? What side is more broken and so should be bent to the standart ?

What and where should i change to make Yii select action by verb, not only filter ?

**Comment by tunecino** [comment]
this may also help if using apache & `libapache2-mod-php5filter` instead of `libapache2-mod-php5` : 
http://serverfault.com/questions/341869/apache2-and-php5-module-or-filter

**Comment by cebe** [comment]
this issue contains multiple problems and it is not clear what exactly is needed to change in the framework. Docs about pluralization have been updated to be more clear some time ago. Closing. If there is still an issue, please open a new issue with clear description of what needs to change.
