### ISSUE TITLE
MongoDB, MongoId & ArrayHelper::toArray()

### ISSUE THREAD

**Issue by AstRonin** [yiisoft/yii2#5624]
Hi all.

If we have MongoId object in some field (not _id) for relation then after `toArray` we obtain an array such as
```php
'_id' => [
     '$id' => 'asdf7sdf87s8f7sdf80hdf8s7f'
]
```
instead of normal MongoId object.
Can we add condition
```php
if ($object instanceof \MongoId) {
     return $object;
}
```
or something like that?

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/issues/79#issuecomment-205757039

**Comment by cebe** [comment]
@klimov-paul any idea what to do about it in yii core? I do not see a way.

**Comment by klimov-paul** [comment]
The only possible solution is add eplicit check for the `\MongoId` instance inside `ArrayHelper::toArray()`:

```php
if ($object instanceof \MongoId) {
    return $object->__toString();
}
```

It will work fine even if no `MongoId` class is defined.

If it is not acceptable, then issue should be closed with resolution 'wont fix'.

**Comment by cebe** [comment]
I agree with @qiangxue here, that it should not be part of the core to handle mongoId stuff. @yiisoft/core-developers other opinions?

**Comment by SilverFire** [comment]
Agree with @cebe

**Comment by samdark** [comment]
Also agree with @cebe

**Comment by klimov-paul** [comment]
One of the possible solution, which does not involve direct class name check, can be following:
in case class declares method `__toString()` (e.g. it is convertable to string) and its array representaion is less then 2 elements - use `__toString()` result instead.

Such approach produce better results for such classes as `yii\web\JsExpression` for example.
