### ISSUE TITLE
gii: moduleClass option should be automaticaly generated following conventions

### ISSUE THREAD

**Issue by mplescano** [yiisoft/yii2#5633]
I remember yii/gii1.1 put the generated modules inside the folder ../protected/modules
So, in this case should be almost the same, moduleClass option can be generated in conventional way as follows:
"app\modules\". {moduleID} . "\" . upperCapital({moduleID}) . "Module"

Thanks

**Comment by samdark** [comment]
Agree with @mdmunir.
