### ISSUE TITLE
Active record linking via table

### ISSUE THREAD

**Issue by enigmatix** [yiisoft/yii2#5658]
I have found it inconvenient to explicitly declare column values when using the link method involving a linking table, especially as these values are defined within the model for the linking table as defaults within the model rules.

If I ever change these rules, I then have to review all instances of the "link" method. Not very efficient. 

I propose to pass an object of the link table model so that these defaults can be applied.  I have a way to do this that would be backwards compatible,  and not interfere with existing setups that don't use the link table model. 

If you agree, I will complete a pull request with details of my proposed change.

**Comment by enigmatix** [comment]
Pull request made:

https://github.com/yiisoft/yii2/pull/6812

**Comment by dynasource** [comment]
Thanks for you usecase. Its is becoming clear taht the problem with the current link method is that there are too many usecases thinkable. The more arguments a method gets, the less manageable the code becomes and the less OO we will get. 

Linking 2 models seems to be a complete architecture on itself. There are things involved: models, attributes, relations, junctiontables, existing records, non existing records. Its too complex to cover with a method only and too error prone. A solution must be found from a complete architectural perspective. 

Thanks for helping us to get to this understanding!
