### ISSUE TITLE
Data-params suggestion

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#5663]
Is this possible to use additional data attribute with any elements which contain 'data-method' attribute? I need to send additional data via POST when i use elements with 'data-method'.

**Comment by hardsetting** [comment]
+1

**Comment by mdmunir** [comment]
:+1: 
According with this issue. About this [line](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L161), i cannot posting form to other url. E.g. I open `user/index` but i want posting form here to `user/create` or `user/update` (in case single page application). Is it discussed yet?

**Comment by qiangxue** [comment]
This is reported in https://github.com/yiisoft/yii2/issues/6661.
