### ISSUE TITLE
Setting an initial gridview filter

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#5668]
Just like `defaultOrder` to set a default sort .... is there a recommended way to set an initial default filter to the gridview?  

I am trying to do this dynamically before rendering the grid by changing attribute values in `filterModel` and passing the updated `filterModel`. While it sets the initial value ... it does not adjust the QUERY or filter the grid records. Is this an expected behavior and something else needs to be done to trigger the initial filter action?

**Comment by rallin** [comment]
Try use
```php
        if (!(($this->load($params) || $this->load($this->getDefaultParams(), '')) && $this->validate())) {
            return $dataProvider;
        }
```
where getDefaultParams() is like:
```php
    protected function getDefaultParams()
    {
        return []; // Here put default filter params
    }
```

**Comment by inamjung** [comment]
Thank U verymuch  But! i dose work  , it work  if  press ENTER

**Comment by handrei** [comment]
cebe commented on 20 Oct 2014

you have to set the initial filter value before the query is created, i.e. before you call the search() function.

@inamjung this worked for me

**Comment by rubenheymans** [comment]
This works for me too
Cleaner code:
`$get = Yii::$app->request->get($this->formName());    
if ($get && !($this->load($params) && $this->validate())) { ...`  
Do we have an other/better solution now?
