### ISSUE TITLE
Procedure to switch from development to the procedure

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#5685]
In a documentation given two-mode development environment : development and production 

How good procedure to switch/migrate from development to the procedure, if only just to change the web / index like :
```php
//change from

//defined('YII_DEBUG') or define('YII_DEBUG', true);
//defined('YII_ENV') or define('YII_ENV', 'dev');

//to

defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');
```

Or repeat the initialization [`init`] in command prompt to production ?
Maybe this is  must added in documentation

**Comment by professor93** [comment]
c0:4a:00:26:83:41
