### ISSUE TITLE
Suggest make \yii\rbac\ActiveDbManager

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#570]
Which will work with models representing db tables. Why we need this. For example we have grid:

```
id | name | role
--------------------------------
1 | qiang | repo collab
2 | samdark | repo collab
3 | creocoder | coder
4 | cebe | repo collab
```

Now we want to sort users by role. Models for db auth manager tables will be ineresting to make relations from User model to it and get rbac data.

**Comment by Faryshta** [comment]
I worked on a way to use ActiveRecords on the rbac module.

https://github.com/Faryshta/yii2/compare/yiisoft:master...Faryshta:activeRecordRBAC

So far I have created the modules and I am rewritting the `DbManager` class

**Comment by Faryshta** [comment]
I am checking the `ManagetInterface`. The docs mention the Item, Rule, Assignment, Role and Permission objects. But doesn't mention on which namespace they belong (at least not explicitly) and the php code doesn't actually use dependency injection so I think we can rewrite the `DbManager` to completely ignore the `yii\rbac\Item|Rule|Assignment|Role|Permission` objects and use the models I created instead completely cutting out an step to build the `DbManager`

https://github.com/yiisoft/yii2/blob/master/framework/rbac/ManagerInterface.php 

Cases like this one won't be affected by skipping this objects https://github.com/yiisoft/yii2/blob/master/docs/guide/security-authorization.md#building-authorization-data

So I propose to avoid using those objects on the `DbManager`

**Comment by sashaaro** [comment]
What about separate interfaces, like https://github.com/yiisoft/yii2/issues/8424

**Comment by samdark** [comment]
Re-considered it. It's a bad idea since it would result in using RBAC AR directly which should be avoided. Instead we may extend interface to be OK for various control panels.
