### ISSUE TITLE
phpdoc fix

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#5741]
Several classes like `User` model in `yii2-advanced` are using `inherit-doc` feature of php-doc, however their syntax is incorrect according to php-doc manual, it should be [`{@inheritdoc }`](http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html) . Will submit PR if needed

**Comment by dynasource** [comment]
duplicate https://github.com/yiisoft/yii2/issues/11635
