### ISSUE TITLE
what should I paste for using Yii2 with yii?

### ISSUE THREAD

**Issue by rifaideen** [yiisoft/yii2#5776]
I have followed the instruction on http://stuff.cebe.cc/yii2docs/guide-tutorial-yii-integration.html#using-yii-2-with-yii-1 they told me to paste the contents of YiiBase.php into newly created class like the below

``` php
class Yii extends \yii\BaseYii
{
    // copy-paste the code from YiiBase (1.x) here
}
```

but I don't know what to paste. does somebody post the example content inside this class.

**Comment by dynasource** [comment]
please visit our upgrade section http://www.yiiframework.com/doc-2.0/guide-intro-upgrade-from-v1.html
