### ISSUE TITLE
yii\base\ActionFilter::$only behavior

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#5796]
in methode `yii\base\ActionFilter::isActive()` to check active action should use `$this->only === null` instead of `empty($this->only)`. So when we set `$only` to `[]` its mean no action will active. Current implementation, when we set `$only` to `[]` its mean all action is active.

``` php
return !in_array($id, $this->except, true) && (empty($this->only) || in_array($id, $this->only, true));
```

should change to

``` php
return !in_array($id, $this->except, true) && ($this->only===null || in_array($id, $this->only, true));
```

**Comment by dynasource** [comment]
@mdmunir, 2 years have passed. Whats your current view on your request?

**Comment by mdmunir** [comment]
As i said above. I used it when developing (but all my project under development now :D). Instead of remark all behavior i just want to remark `only` section.
FYI, Currently we can use `except = ['*']` to avoid all action. But still better if we check `$only === null` instead of `is_empty($only)`.

**Comment by dynasource** [comment]
alright. Its debatable with respect to consistency and unfortunately also a BC break. Lets close this one for now, perhabs we will reassess in future releases. Thanks!
