### ISSUE TITLE
Add MongoDate validator

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#5802]
Really, since most dates in MongoDB should be `MongoDate`s I think a MongoDate validator should be added to the MongoDB extension.

Possibly one that works on the current date validator but spits out its value as a `MongoDate` object.

Unless I am mistaken in thinking that is not currently the case?

**Comment by klimov-paul** [comment]
Fixed:
https://github.com/yiisoft/yii2-mongodb/tree/master/validators

**Comment by cebe** [comment]
Validators are meant to be used for user input, how can a mongoID be user input?

**Comment by klimov-paul** [comment]
If you fetch ActiveRecord from database it already contains `MongoId` instance.
If you write `$ar->save()` it runs validation. So it could be a situation, where validated attribute contains `MongoId` instance.
Still `MongoIdValidator` mainly serves to validate plain string, which may be a MongoId.

**Comment by cebe** [comment]
what if there is an error added by the validator? there is no field to display it to the user...

**Comment by klimov-paul** [comment]
> there is no field to display it to the user

Why? It is. It is an attribute, which value is validated.

**Comment by cebe** [comment]
well yeah, maybe I am not familiar enough with mongodb.
