### ISSUE TITLE
Bower alias not being set and findJunctionRows does not exist

### ISSUE THREAD

**Issue by smks** [yiisoft/yii2#5812]
1)
Invalid Parameter – yii\base\InvalidParamException
Invalid path alias: @bower/bootstrap/dist

2) yii\db\ActiveQuery::findJunctionRows() does not exist

My composer.json currently:

...

    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "kartik-v/yii2-widgets": "dev-master",
        "dektrium/yii2-user": "0.7.0",
        "yiisoft/yii2-redis": "*",
        "symfony/finder": "2.6.*@dev",
        "nesbot/Carbon": "*",
        "phpoffice/phpexcel": "1.8.0",
        "kartik-v/yii2-grid": "*",
        "yiisoft/yii2-bootstrap": "*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "fzaninotto/faker": "1.2.*@dev",
        "codeception/codeception": " 2.0.*",
        "codeception/specify": " *",
        "codeception/verify": " *"
    },
    "suggest": {
        "codeception/codeception": "Codeception, 2.0.* is currently works well with Yii.",
        "codeception/specify": "BDD style code blocks for PHPUnit and Codeception",
        "codeception/verify": "BDD Assertions for PHPUnit and Codeception"
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::setPermission",
            "yii\\composer\\Installer::generateCookieValidationKey"
        ]
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        },
        "writable": [
            "runtime",
            "web/media",
            "web/assets"
        ],
        "executable": [
            "yii"
        ],
        "config": [
            "config/web.php"
        ]
    }
}

**Comment by klimov-paul** [comment]
Closed, since there is no response from the author.
