### ISSUE TITLE
Facilitate customary binary prefixes when formatting 1024^n values.

### ISSUE THREAD

**Issue by MatthewDaize** [yiisoft/yii2#5818]
Right now the formatter only works in 1000 and 1024 options however the later option has two possible prefixes (IEC & Customary)

Can we please get the Formatter class to facilitate customary binary prefixes for size formatter when using 1024^n values? Right now, the formatter when using 1024 is rigid in that it only supports IEC where it's common practice in the telecommunications industry to use the customary prefix rather than IEC when communicating bandwidth consumption.

Details are available here:
http://en.wikipedia.org/wiki/Binary_prefix#Specific_units_of_IEC_60027-2_A.2_and_ISO.2FIEC_80000

**Comment by SilverFire** [comment]
Hello. As you see, nobody have posted "+1" in this issue for 2+ years. It means that base 1000 and 1024 cover most of use cases and we don't want to over-complicate code for some rare ones. You always can override formatter in your project locally. Thank you!
