### ISSUE TITLE
Request Scrutinizer data security audit tracking

### ISSUE THREAD

**Issue by acorncom** [yiisoft/yii2#5827]
The Scrutiziner team released a data security tool a few days ago that allows auto-auditing of user data:
https://scrutinizer-ci.com/blog/performing-security-audit-of-request-data-for-php-applications

Toward the bottom they mention that they would be happy to add additional "request data abstraction" systems.  Someone in the Laravel community has already filed a request here: https://github.com/scrutinizer-ci/php-analyzer/issues/457

Could we open a request for Yii2 as well?  I'm not that familiar with the Yii2 Request system yet, so thought it might be better to have a Yii core developer open the issue instead ...

**Comment by dynasource** [comment]
How do we look at this topic now after 2 years? Is it useful & implementable?

**Comment by samdark** [comment]
I've requested it from them. No need to track it via ticket.
