### ISSUE TITLE
Rename the rbac migration to a normal class name and for including it in a project

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#5846]
I have several migration from several extension. How to `migrate/down` just one migration without change/apply other migration. Here is my migration history

```
    (2014-10-28 04:14:30) m141018_105939_create_table_upload
    (2014-10-28 04:14:30) m140624_050135_create_table_accounting
    (2014-10-28 04:14:30) m140624_050114_create_table_sales
    (2014-10-28 04:14:30) m140624_050056_create_table_inventory
    (2014-10-28 04:14:30) m140624_050030_create_table_purchase
    (2014-10-28 04:12:13) m140622_165356_create_table_master
    (2014-09-29 03:11:52) m140602_111327_create_menu_table
    (2014-09-29 03:11:52) m140527_084418_auto_number
    (2014-09-29 03:11:52) m140506_102106_rbac_init
    (2014-09-29 03:11:52) m130524_201442_init
```

How do `migrate/down` or `migrate/redo` only `auto_number` migration.

**Comment by cebe** [comment]
related #384

**Comment by Faryshta** [comment]
#8202 could help

**Comment by dynasource** [comment]
closed in favor of #8202

**Comment by cebe** [comment]
> Thinking about something like renaming the rbac migration to a normal class name and make including it in a project by extending it in the concrete migration.

this is something I'd like to do.

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/issues/13918

Will be namespaced
