### ISSUE TITLE
Datepicker and normalizeDatetimeValue

### ISSUE THREAD

**Issue by mfrsousa** [yiisoft/yii2#5857]
I think there is bug when using some date formats in jui Datepicker
I'm using language in pt, so the correct format for dates is  dd/mm/yyyy.
When a value is submitted from the input field/datepicker and value is something like 01/03/2014, when value is returned is like 03/01/2014.
I think is because of Formatter->normalizeDatetimeValue and DateTime object understands the format as American month, day and year, so the returned date as inverted day and month

**Comment by benmadin** [comment]
Are you suggesting we need to do this in every model that has a date value? That's going to be tedious... 

This seems odd, I would have presumed the default behaviour could be inferred from the formatter, vis if config has 

```php
formatter' => [
    'dateFormat' => 'dd/MM/yyyy',
 etc
```
it should resolve any ambiguity over what a date is meant to be?

cheers

Ben

**Comment by cebe** [comment]
the formatter is meant to turn a machine readable unambiguous date format into a human readable format. For parsing a date from human input and turning it into a machine readable format the date validator should be used. The problem with the postgres format you described can be solved by allowing to specify a different format than unix timestamp for the machine readable format. This will be possible when #5053 is ready.

**Comment by ddinchev** [comment]
I can't agree that solving it via validator is the best way. I have a case where in specific database fields the data format is "yyMMdd" and I'm totally fine to see those in the `DatePicker` input field after selecting a date.

Maybe `normalizeDatetimeValue` should allow input format to be specified as parameter (maybe as last param, with default value whatever date format is set to the `formatter`). Currently `DatePicker` submits the date in the proper `yyMMdd` format, the `DateValidator` validates that successfully and if another form field validation fails, the user would see the form with messed up date as `normalizeDatetimeValue` has expected the default `formatter` date. 

Obviously I don't want to change the global date format to be `yyMMdd` and I'd prefer not to translate dates around just so I can get a properly rendered DatePicker if other field fails...

**Comment by cebe** [comment]
@ddinchev your case does not work with the date validator because it is not able to handle your format correctly. This is due to limitations in the PHP datetime parser and intl datetime parser.

If you see a way to fix this in yii, please open a new issue.
