### ISSUE TITLE
$enableClientScript for GridView

### ISSUE THREAD

**Issue by tvdavid** [yiisoft/yii2#5872]
I sometimes use GridView without the need for any of the javascript (filtering/sorting/etc) capabilities, in which case the gridview.js and jQuery init code are unnecessarily loaded.

How about a $enableClientScript - just like ActiveForm has - that would simply skip everything in GridView::run()?

**Comment by dynasource** [comment]
if you want to change the working of GridView, you should either:
* override it by your own class
* or use the events of \yii\web\View to disable client scripts

These workarounds fit well to this rare usecase.
