### ISSUE TITLE
Ignore remove duplicated for ActiveQuery and joinWith

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#5878]
I have 2 tables
table `product` with attribute 'id', 'name' and
table `price` with attribute 'product_id', 'category', 'price'.
`Product` to `Price` is hasMany

when i do this

``` php
$product_prices = Product::find()
    ->select(['product.*','price.category','price.price'])
    ->joinWith('prices')
    ->asArray()
    ->all();
```

Returned value always unique per product. If product have more than one price, always return one product. Can we ignoring 'remove duplicated' when we use `asArray()`

**Comment by InteLigent** [comment]
My design, simple solution for this case:

$index = 0;
$product_prices = Product::find()
    ->select(['product.*','price.category','price.price'])
    ->joinWith('prices')
    ->asArray()
    ->indexBy(function ($row) use(&$index){
           return ++$index;
    })
    ->all();

**Comment by lynicidn** [comment]
relation as `hasMany` ?

**Comment by cebe** [comment]
@mdmunir to get what you need you could just join from prices on product to get all prices including the product name. This way it sounds more logical to me.

**Comment by mdmunir** [comment]
like this?
```php
$product_prices = Price::find()
    ->select(['product.*','price.category','price.price'])
    ->joinWith('product')
    ->asArray()
    ->all();
```
OK.
When we use `joinWith()` without `asArray()` we can access all prices via relation.
```php
foreach($product_prices as $product){
     // ...
    foreach($product->prices as $price){ 
        
    }
}
```
but how do it when use `asArray()`. If we can access via `$product['prices']` , its more better.

**Comment by StagnantIce** [comment]
+1
I have same problem #10492

**Comment by dynasource** [comment]
@mdmunir, are you still supporting this topic, and if so, formulate detailed criteria for us to be able to take action on?

**Comment by mdmunir** [comment]
I dont know when. But, this issue was solved :D

**Comment by dynasource** [comment]
excellent
