### ISSUE TITLE
Different behavior of activeCheckboxList on AJAX validation

### ISSUE THREAD

**Issue by taxp** [yiisoft/yii2#5881]
I have model News with required field 'categoryIds':

``` php
class News extends \yii\db\ActiveRecord {
//...
public $categoryIds = [];
public function rules()
    {
        return [
            [['categoryIds'], 'required'],
            //...
        ];
    }
//...
}
```

When I create activeCheckboxList on ActiveForm with no items it validates fine:
$form->field($news, 'categoryIds')->checkboxList([]);

But validation does not pass if I change wrapper tag of group of checkboxes:
$form->field($news, 'categoryIds')->checkboxList([],  ['tag' => 'span']);

I found out that there is hardcoded tag name of wrapper in function findInput at /assets/yii.activeForm.js:598

Maybe it need to check input[type=checkbox] or input[type=radio] directly, not the wrapper tag name?

**Comment by yiifans** [comment]
i set selectors property
'selectors'=>['input'=>"#$inputId input"];

**Comment by yiifans** [comment]
强哥在吗

**Comment by samdark** [comment]
Won't be implemented in 2.0.

**Comment by huiyang** [comment]
Hi, may i know what is the reason this issue will not be fixed?
Customize the selector will solve the issue but it is not a nice method as it need hardcoded id

**Comment by samdark** [comment]
Because it is enhancement and Yii 2.0 is feature-frozen.

**Comment by huiyang** [comment]
Alright, thanks for reply.
