### ISSUE TITLE
Implement Form Builder

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii2#59]
What are the pros and cons of the form builder in 1.1?
What enhancements should we provide?

**Comment by spikyjt** [comment]
We use CForm extensively in our Yii 1 projects. Porting our core app to Yii2 without it is proving very painful. Unfortunately, I was too busy with large Yii 1 projects to make any input to the Alpha/RC stage of Yii2. As this feature is essential for me, I would definitely like to see it continue in Yii2. I will be developing a suitable class to match the configuration format of the old CForm, with updates where appropriate, and will submit it as a PR if wanted. It will use ActiveForm for the rendering of course.

**Comment by dynasource** [comment]
this discussion is expired
