### ISSUE TITLE
这两个文件的设置是不是矛盾了

### ISSUE THREAD

**Issue by qiuer** [yiisoft/yii2#5905]
![image](https://cloud.githubusercontent.com/assets/8002631/4897957/522250fe-640b-11e4-9e70-d9f7aa4a6f37.png)

**Comment by tonydspaniard** [comment]
@qiangxue seems that Imagine has updated its transparency checking on GMagick too: https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Gmagick/Imagine.php#L82 

Will review and update asap.

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-imagine/issues/7
