### ISSUE TITLE
Parameters for QueryBuilder::batchInsert(), ex. INSERT IGNORE

### ISSUE THREAD

**Issue by stepanselyuk** [yiisoft/yii2#5917]
Hello,
I have a problem with `QueryBuilder::batchInsert()`. When I try to add some data to the table (with unique keys), I get DB-error, since I can't specify `INSERT IGNORE` in result SQL-query. 

https://dev.mysql.com/doc/refman/5.6/en/insert.html

Please add a basic params for INSERT statement: `[LOW_PRIORITY | DELAYED | HIGH_PRIORITY] [IGNORE]`

Now I doing it like:

``` php
$sql = $builder->batchInsert( MailingNewsLinkProfile::tableName(), $columns, $values );
$sql = 'INSERT IGNORE' . mb_substr( $sql, strlen( 'INSERT' ) );
```

**Comment by samdark** [comment]
Won't be implemented in 2.0.
