### ISSUE TITLE
Error: QueryBuilder::batchInsert() while inserting boolean value in PostgreSQL

### ISSUE THREAD

**Issue by dovgart** [yiisoft/yii2#5977]
According to manual
http://www.postgresql.org/docs/9.3/static/datatype-boolean.html
SQL query can't be executed because datatype mismatch.

>table(
>    field1 => integer
>    field2 => boolean
>)

For example:
>'INSERT INTO table VALUES (48,1)' - wrong
but
>'INSERT INTO table VALUES (48,"1")' - can be executed
>'INSERT INTO table VALUES (48,TRUE)' - can be executed

Quick fix:

yii\db\QueryBuilder lines 197-198

> } elseif ($value === false) {
>    $value = 0;

should be

> } elseif ($value === false) {
>    $value = '0';
> } elseif ($value === true) {
>    $value = '1';

I don't know what about other RDBMS. So it's need to find out.

**Comment by klimov-paul** [comment]
Duplicates #6526
