### ISSUE TITLE
Activefield->checkbox() causes browser to link label to wrong input

### ISSUE THREAD

**Issue by particleflux** [yiisoft/yii2#5984]
__Yii Version__ 2.0.0
__Browser__ Firefox 31.2.0 on Linux

Activefield->checkbox() generates, with the default behaviour, a hidden input additionally to the checkbox input. 

The label for the checkbox input though isn't connected via _for_, but by enclosing the input by the label tag. What follows is a label linked to a hidden input (well, at least it isn't linked to the visible one, I think ff just takes the first input tag):

View code:

    <?=$form->field($model, 'ignoreWeakPassword')->checkbox() ?>

Generated HTML:

    <div class="checkbox">
	<label>
		<input type="hidden" value="0" name="SignupForm[ignoreWeakPassword]">
		<input type="checkbox" value="1" name="SignupForm[ignoreWeakPassword]" id="signupform-ignoreweakpassword">
		Ignore Weak Password
	</label>
	<p class="help-block help-block-error"></p>
    </div>

**Comment by cebe** [comment]
Fixed, thanks for reporting!
