### ISSUE TITLE
Specifying "template" as an alias for apidoc command

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii2#5990]
Currently, the `template` option for `apidoc` command takes a string which is used to form the renderer class like below

```php
        $rendererClass = 'yii\\apidoc\\templates\\' . $template . '\\ApiRenderer';
```

This requires a theme to be placed within the `apidoc` extension directory, which makes custom theme not very maintainable. Can we support specifying `template` as a path alias so that custom themes can be placed under arbitrary directory? The above render class resolution code can rewritten as:

```php
        $rendererClass = Yii::getAlias($template) . '\\ApiRenderer';
```

**Comment by cebe** [comment]
this is already implemented: https://github.com/yiisoft/yii2-apidoc/blob/master/commands/GuideController.php#L129-L132
