### ISSUE TITLE
Ability to manually update ActiveForm error messages on client-side

### ISSUE THREAD

**Issue by tahirm** [yiisoft/yii2#5991]
I am facing problem regarding manually adding error msgs to form. In my case I don't have any problem with ajax validation. I have two scenarios in rules. one is 'default' and one is 'login' like this

```php
public function rules() {
    return [
      // email and password are both required
      [['email', 'password' ], 'required' ],
      ['email', 'email' ],
      // email is validated by validateEmail()
      ['email', 'validateEmail', 'on' => 'login' ],
      // password is validated by validatePassword()
      ['password', 'validatePassword', 'on' => 'login' ],
    ];
  }

```
I am using default scenario for ajax validation on blur and change and it is being handled fine with ajax validation. The problem is with 'login' scenario, I want to validate using 'login' scenario only when user clicks on submit button. To achieve this I attached 'beforeSubmit' event like this

```javascript

$('body').on('beforeSubmit', 'form#loginForm', function() {
    var form = $(this);
    if (form.find('.has-error').length) {
      return false;
    }

    $.ajax({
      url: form.attr('action'),
      type: 'post',
      data: form.serialize(),
      success: function(errors) {
        // How to update form with error messages?
      }
    });

    return false;
  });

```

Now above event is working fine and it sends the ajax request to server when user clicks on submit button and I validate the fields with 'login' scenario and return the errors in json if there are any otherwise redirect the user to some other page. 

Now the problem is if I get validation errors in return at this point I can not show those errors in form to user using ```yii.activeForm.js```, because [updateInputs] (https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L474) is not accessible publicly. Or is there another way to update the form error messages manually?

And the reason I have this 'login' scenario is because I want to validate email and password together in database only when user clicks on submit button.

**Comment by mdmunir** [comment]
:+1: Agree

**Comment by nkovacs** [comment]
I have a similar problem. I want to submit a form using ajax, but sometimes that submission can fail, and in that case I'd like to use updateInputs and updateSummary to display the errors manually.
I cannot just use ajax validation, because there are some things I cannot validate.
E.g. I'm using an api to register a user which will either register the user or return an error, e.g. that the username is already in use. It can't tell me if the username is already in use before registering, so I can't check that with ajax validation.

**Comment by Blizzke** [comment]
I would be very happy with this functionality as well... I regularly have forms that validated data-wise but failed to submit further along the flow (service not available or so). It would be nice being able to integrate error reporting with the already existing functionality. Now I have to manually add things.

**Comment by ksideks** [comment]
:+1:

**Comment by thejahweh** [comment]
:+1:

**Comment by t-kanstantsin** [comment]
:+1:

**Comment by tahirm** [comment]
Thank you very much for adding this support.
