### ISSUE TITLE
Wrong documentation http://www.yiiframework.com/doc-2.0/

### ISSUE THREAD

**Issue by eresik** [yiisoft/yii2#6031]
For example:
at page http://www.yiiframework.com/doc-2.0/yii-db-activerecord.html
as described: ActiveRecord magic methods __get and __set defined in yii\base\Component
  but actually: ActiveRecord magic methods __get and __set defined in yii\db\BaseActiveRecord

Seeming as minor issues, but I had a sleepless night because trust documentation.

**Comment by CedricYii** [comment]
It seems to be working correctly now, shouldn't this issue be closed ?

**Comment by samdark** [comment]
Thanks for confirming it.
