### ISSUE TITLE
Add support for array type styles.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#6043]
Currently the Html functions interpret the style option as a string.
In reality a css string is a set of key value pairs.
Currently BaseHtml::renderTagAttributes makes an exception for the data attribute and json encodes that  if it is an array.
I propose to add similar functionality for the style attribute:
- If it is an array simply iterate over the keys and values and create the css string.

**Comment by klimov-paul** [comment]
You can use `Html::cssStyleFromArray()`

**Comment by SamMousa** [comment]
If there already is a helper it's even easier to implement. I can make a PR if you want.

**Comment by klimov-paul** [comment]
This is not so simple for both 'style' and 'class' attributes.
There are methods `Html::addCssStyle()` and `Html::removeCssStyle()`, `Html::addCssClass()` and `Html::removeCssClass()`. These methods accepts `$options` array by reference intending to fill corresponding keys with string(!) value.
Switching to arrays here may break a BC.

**Comment by SamMousa** [comment]
The only BC break is that code that normally would throw an array to string
conversion error won't anymore.

I doubt people are generating logic based on that behavior.

I could just normalize http options by checking if the value for key 'CSS'
is array and if so convert it? I don't see the issue wrt BC.

**Comment by SamMousa** [comment]
Also I can update the helper function to respect the syntax of the options array.

**Comment by klimov-paul** [comment]
See #8458
