### ISSUE TITLE
Issue with unique validator

### ISSUE THREAD

**Issue by sitchaka** [yiisoft/yii2#6044]
I can't create an user with unique username when i'm using the UniqueValidator class. 
Error: after submitting the form, I'm not redirected to the view page. I see a blank page on browser, and user was not created. it doesn't work even if I enter a username that doesn't yet exist in the database.

```php
 public function rules()
    {
        return [
            [['username', 'email', 'password'], 'required'],
            [['username', 'email'],'unique'],
            [['email'],'email'],
            [['profil_picture', 'sexe', 'show_birthday', 'show_email'], 'integer'],
            [['signup_date', 'birthday'], 'safe'],
            [['biography'], 'string'],
            [['username'], 'string', 'max' => 64],
            [['email', 'password'], 'string', 'max' => 128]
        ];
    }
```

**Comment by klimov-paul** [comment]
Closed unless more information arrives.

**Comment by wwebdevelop** [comment]
I'm having the same problem .

See the problem context .

It occurs when I set the validator "unique " , " exist" or even when I do a custom function to do the validation .

When I submit the form, simply the page is blank. There is no error diaparado by Yii or browser console.

This same problem is occurring in both systems I'm developing in Yii .

Follows the code :

public function rules()
    {
        return [
            [['IDEXERCICIO', 'IDMES', 'IDORIGEMRECEITA', 'VALOR'], 'required'],
            [['IDEXERCICIO', 'IDMES', 'IDORIGEMRECEITA'], 'integer'],                       
            [['VALOR'], 'double', 'integerOnly'=>false, 'numberPattern'=>'/^\s*(?:[1-9]\d{0,2}(?:\.\d{3})*|0)(?:,\d{1,2})?$/'],
            [['OBSERVACAO'], 'safe'],
            [['IDORIGEMRECEITA'], 'unicaOrigem'],
            //[['IDORIGEMRECEITA'], 'unique', 'filter'=>'ATIVO=1'],
            //[['IDORIGEMRECEITA'], 'exist'],
        ];
    }

public function unicaOrigem($attribute, $params)
    {
         $origem = self::find()->where( "IDORIGEMRECEITA = $this->IDORIGEMRECEITA AND ATIVO= 1")->one();
                                    
         if($origem != NULL)
         {
             $this->addError('IDORIGEMRECEITA', 'record already exist' );
         }        
    }

**Comment by cebe** [comment]
the problem in your case is controller logic: you have one case that exists the action without printing anything.

change it to the following should work, this way you catch the case of failing validation by displaying the form with errors:

```php
public function actionCreate()
{
    $model = new RECEITA();

    if($model->load(Yii::$app->request->post()))
    {            
        $model->IDUSUARIO = Yii::$app->user->identity->IDUSUARIO;            
        $model->DATASISTEMA = Util::geraData();                

        if ($model->save()) 
        {                 
            return $this->redirect(['view', 'id' => $model->IDRECEITA]);
        }
    }

    return $this->render('create', [
        'model' => $model,
    ]);
}
```

**Comment by wwebdevelop** [comment]
Cebe, thank you for your answer. You are absolutely right.

Indeed, if the save () fails is not rendered anything;

I changed the code generated via CRUD Gii and not hearken to me that speaks of semantics.

Many thanks again.

**Comment by MilinkoDragovic** [comment]
Hello guys,

I'm trying to make unique mobile number on registration.
So, I'm using Ajax validation. But I got blank page when I click on button save.
Can you help me :)

**Model:**
  public function rules()
    {
        return [
            [['clicnic_idclicnic'], 'required'],
            [['clicnic_idclicnic','day','month','year'], 'integer'],
            [['birthday', 'first_login_date', 'last_login_date'], 'safe'],
            [['first_name', 'last_name', 'street', 'plc', 'city', 'phone', 'mobile', 'email'], 'string', 'max' => 45],
            [['mobile'],'unique'],
			
        ];
    }

**View**
 <?php $form = ActiveForm::begin([
        'enableAjaxValidation'=>true,
    ]); ?>
.....
<?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>

**Controller
**
  public function actionCreate()
    {
        $model = new Patient();
        
        
        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }
        $year[] = null;
        for ($i=1950; $i <= date("Y"); $i++) { 
            $year[$i] = $i;
        }
        $day[] = null;
        for ($i=1; $i <= 31; $i++) { 
            $day[$i] = $i;
        }
        $month[] = null;
        for ($i=1; $i <= 12; $i++) { 
            $month[$i] = $i;
        }
        if ($model->load(Yii::$app->request->post()) ) {
            $model->birthday = $model->year.'-'.$model->month.'-'.$model->day;
            if ($model->save()) {
                return $this->redirect(['appointment/index','phonenum'=>$model->mobile]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'clinic' => Clinic::find()->all(),
                'day' => $day,
                'month' => $month,
                'year' => $year,
            ]);
        }
    }

**Comment by SilverFire** [comment]
What is the status-code of that blank page?

**Comment by MilinkoDragovic** [comment]
Redirect to this link:
http://localhost:8080/klijent/web/index.php?r=patient%2Fcreate
And Its blank.
Confirm Form Resubmission
"This webpage requires data that you entered earlier in order to be properly displayed. You can send this data again, but by doing so you will repeat any action this page previously performed.
"

**Comment by SilverFire** [comment]
I think you are getting a blank page when `save()` failed. Check you controller's action code, there is no logical branch with `return`, when `$model->save()` is false.

> 
```php
          if ($model->load(Yii::$app->request->post()) ) {
             $model->birthday = $model->year.'-'.$model->month.'-'.$model->day;
             if ($model->save()) {
                 return $this->redirect(['appointment/index','phonenum'=>$model->mobile]);
             }
         } else {
```
