### ISSUE TITLE
functional tests not using test db

### ISSUE THREAD

**Issue by ThePeach** [yiisoft/yii2#6073]
I'm playing around functional tests and fixtures in order to test a user REST controller.

I have created a test db and configured it in `tests/codeception/config/config.php`

I have then created a fixture file in `tests/codeception/fixtures/fixtures.php` where I do wipe everything off the db and create a new user with a set password, and did a `require dirname(__FILE__) . "/../fixtures/fixtures.php";` at the beginning of my CEPT user test.

When running the CEPT test, the user gets created and the password is set in the test db as expected.

But when in the test I'm doing a PUT to the user to update the password, it changes the one in the default db, not the test one.

Is there anything I'm missing here?

**Comment by Ragazzo** [comment]
hi, happy new year you too ) nope , still dont have enough time, will do my best to check it on weekend, since you are writing a book for `Yii2` testing. Feel free to contact me on email if needed.

**Comment by jvalecillos** [comment]
I'm having the same problem. No matter what, REST calls run against the app default database instead of test database

**Comment by Ragazzo** [comment]
@ThePeach @jvalecillos can you recheck please that your tests actually calling `index-test.php` and not simple `index.php` ?

**Comment by jvalecillos** [comment]
No, I tested writing an error on that file but nothing happens. I think that the test doesn't create an instance with those config files at all, it just call the web server with its default config.

**Comment by Ragazzo** [comment]
can you show your config ? You are not using `Yii2` and `PhpBrowser` together ?

**Comment by ThePeach** [comment]
Hey @Ragazzo REST requests are not using the `index-test.php`, all the other tests are fine.
If you clone and run my repo you can see that for yourself immediately from the first test:
https://github.com/ThePeach/yii2-tests/blob/master/basic-dev/tests/codeception/functional/UserAPICept.php

the output of that test is the following:
```
Trying to test the user REST API (UserAPICept)                                                          
                                                 
Scenario:
* I get fixture "user"
* I am going to authenticate to search for my own user
* I am http authenticated "user","something"
* I send get "users/search/user"
  [Request] GET http://basic-dev.yii2.sandbox/v1/users/search/user
  [Response] {"name":"Unauthorized","message":"You are requesting with an invalid credential.","code":0,
"status":401,"type":"yii\\web\\UnauthorizedHttpException"}
  [Headers] {"Date":["Sat, 24 Jan 2015 11:05:44 GMT"],"Server":["Apache"],"X-Powered-By":["PHP/5.4.20-pl
0-gentoo"],"Content-Length":["149"],"Content-Type":["application/json; charset=UTF-8"]}
  [Status] 401
* I see response code is 200
 FAIL 
```
As you can see I'm explicitly loading a fixture that is available only in the test DB, which highlights the problem.
The configuration is as per manual and you can review it in the repo.

**Comment by ThePeach** [comment]
I might dare to say that this seems very oddly close to the series of other problems going around the REST module of CodeCeption as seen in Codeception/Codeception#1622 but I don't know much about the internals to state this with confidence.

**Comment by Ragazzo** [comment]
@ThePeach does the downgrade of `Codeception` version and `PhpUnit` works for you in this case as you mentioned [here](https://github.com/Codeception/Codeception/issues/1652#issuecomment-71310805) ?

**Comment by ThePeach** [comment]
@Ragazzo that is correct, just tried it.

@jvalecillos if your app has `"minimum-stability": "dev"`, see if updating your `composer.json` with the following will solve the problem:

```json
        "codeception/codeception": "~2.0.0@stable",
        "phpunit/phpunit": "~4.4.0@stable",
```

Please confirm before I close the issue.

**Comment by jvalecillos** [comment]
It doesn't work for me. I don't know if it has something to do with the fact I'm using a vagrant machine. But every test runs against the default app database. BTW, I'm working on the advanced yii2 template.

**Comment by ThePeach** [comment]
@jvalecillos can you please double check the configuration of the test DB is effectively correct? 
Do unit tests work against the test DB?

**Comment by branimirborisov** [comment]
Hi guys,

I thinks I have been strugling with the same issue and following the comments for quite some time.
To me the problem was that when running functional test they were still using the index.php not index-test.php. 
What I found though is that this might be causing the problem:
/tests/codeception/bin/yii.php

```php
require_once(YII_APP_BASE_PATH . '/vendor/autoload.php');
require_once(YII_APP_BASE_PATH . '/vendor/yiisoft/yii2/Yii.php');
require_once(YII_APP_BASE_PATH . '/common/config/bootstrap.php');

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');
```

Shouldn't the define YII_ENV and YII_DEBUG lines be called before the require_once? When swapped places it seems to work fine? Can you check if this does fix the issue for you too? Would this break something else?

```php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require_once(YII_APP_BASE_PATH . '/vendor/autoload.php');
require_once(YII_APP_BASE_PATH . '/vendor/yiisoft/yii2/Yii.php');
require_once(YII_APP_BASE_PATH . '/common/config/bootstrap.php');
```

It seems that when requiring Yii.php if no YII_ENV is set , it is automatically set to "prod"? Does this make sense? The strange thing is that is how it is in the Advanced App Template?!
https://github.com/yiisoft/yii2-app-advanced/blob/master/tests/codeception/bin/_bootstrap.php

**Comment by samdark** [comment]
Seems to be already fixed in master.

**Comment by ThePeach** [comment]
Thanks @samdark. Just checked and can confirm. Thanks!
