### ISSUE TITLE
Form validation strange behavior, SQLSTATE[23000] error

### ISSUE THREAD

**Issue by nikolaykovenko** [yiisoft/yii2#6126]
Hello.

I have simple mysql table:

```
CREATE TABLE IF NOT EXISTS `categories` (
`id` int(10) unsigned NOT NULL,
  `rate` int(11) NOT NULL DEFAULT '0',
  `static` varchar(255) NOT NULL,
  `caption` varchar(255) NOT NULL,
  `skills_matrix` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=14 ;
```

And default generated by CRUD Model, Controller and Views without any changes. Model has these validation rules:

```
/**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rate', 'skills_matrix'], 'integer'],
            [['static', 'caption'], 'required'],
            [['static', 'caption'], 'string', 'max' => 255],
            [['static'], 'unique']
        ];
    }
```

When I'm trying to create new category item without filling rate field, Yii throws exception:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'rate' cannot be null
The SQL being executed was: INSERT INTO `categories` (`rate`, `static`, `caption`) VALUES (NULL, '123', '222')
```

[Screenshot](https://yadi.sk/i/j330G90xcpZPb)

I think this is very strange. Do the rate field should init default value before saving to DB, don't it?

**Comment by dynasource** [comment]
out of the yii scope. If you want to ensure a attribute has a specific value, you should set a default value by Yii http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#default
