### ISSUE TITLE
Mysql longblob / longtext as resource

### ISSUE THREAD

**Issue by KJLJon** [yiisoft/yii2#613]
I think we should allow support for importing resources into longblob or longtext columns

I think it makes sense to have longblob and longtext as a resource because you can run into max_packet_size limits with mysql if it isn't a resource.

See: <a href="https://github.com/yiisoft/yii/issues/2634">Yii issue/2634</a>

**Comment by cebe** [comment]
seems this is not possible due to PDO bug. Closing this for now.
