### ISSUE TITLE
Html::name2id

### ISSUE THREAD

**Issue by aleksanderd** [yiisoft/yii2#6131]
Hi!

What about to add to Html something like:
~~~
    public static function name2id($name)
    {
        return str_replace(['[]', '][', '[', ']', ' '], ['', '-', '-', '', '-'], $name);
    }
~~~

It is very useful in writing complex widgets, etc. Also it can be used as universal tool in places like here: https://github.com/flyiing/yii2/blob/master/framework/helpers/BaseHtml.php#L1912

What you think?

**Comment by klimov-paul** [comment]
I am unsure: docs for `camel2id()` says 'Converts a CamelCase name into an ID in lowercase', which means it expects argument containing alphanumeric string without any brackets.
Removing any not valid character can be done via `Inflector::slug()`, which can be invoked before running `camel2id()`.

**Comment by SilverFire** [comment]
Seems to be outdated. Agreed with @klimov-paul

**Comment by SilverFire** [comment]
https://github.com/flyiing/yii2/blob/master/framework/helpers/BaseHtml.php#L1958-L1972
