### ISSUE TITLE
Client side yiiActiveForm('validate')

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#6160]
Currently does not possible to invoke the method `validate` unless when i will submitting the form.

Ex: 
```javascript
if (('#myform').yiiActiveForm('validate')) {
    //busness logic
    $('#myform').submitForm();
}

```

**Comment by sebathi** [comment]
+1

**Comment by Faryshta** [comment]
also is there a way to be able to do single attributes validations using js?

I am trying to make a form with this http://vadimg.com/twitter-bootstrap-wizard-example/ right now i am stuck that I need to trigger js validation of the fields when I switch steps which as @leandrogehlen said, is only possible when the form is submitted.

**Comment by samdark** [comment]
@Faryshta yes. `$('form').yiiActiveForm('validateAttribute', 'contactform-name')`.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/1422

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md

**Comment by samdark** [comment]
```javascript
$('#contact-form').data('yiiActiveForm').submitting = true;
$('#contact-form').yiiActiveForm('validate');
```

**Comment by cyanoboy** [comment]
@samdark how can I know if validation manually triggered returns errors? I'm developing a wizard in which a form is divided in steps and every time the "next" button is clicked I need to trigger validation and change step only if no validation errors occurs. 
With
```
$('form').yiiActiveForm('validateAttribute', 'contactform-name')
```
I can't control validation result.

**Comment by Faryshta** [comment]
@cyanoboy i am doing the same. https://github.com/Faryshta/yii2-bootstrap-wizard
