### ISSUE TITLE
Save object in user session with DbSession and PostgreSQL fails

### ISSUE THREAD

**Issue by scblack** [yiisoft/yii2#6173]
I'm using DbSession with PostgreSQL for session storage in Yii 2.0.1-dev. When I attempted to store an object in the session, I get the error "Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bytea",

## Test Case
**Table in PostgreSQL:**
```sql
CREATE TABLE public.session_frontend ( 
	id                   varchar(40)  NOT NULL,
	expire               integer  ,
	data                 bytea  ,
	CONSTRAINT pk_session_frontend UNIQUE ( id ) 
 );

CREATE INDEX idx_session_frontend_expire ON public.session_frontend ( expire );
```

**In common/config/main.php:**
```php
    'components' => [
            ...
	    'session' => [
		    'class' => 'yii\web\DbSession',
	    ],
            ...
    ],
```
**In frontend/config/main.php:**
```php
    'components' => [
        ...
        'session' => [
            'sessionTable' => 'session_frontend',
        ],
        ...
    ],
```
**Create a test class**
```php
class TestObject extends \yii\base\Object
{
    public $name;
}
```

**Create object and attempt to save it to the session**
```php
        $test = new TestObject();
        $test->name = 'This is the name of the object';
        Yii::$app->session->set('test', $test);
```
**Result:**
The object is not saved to the session. ``` print_r($_SESSION)``` results in:
```pre
Array
(
    [__flash] => Array
        (
        )

    [test] => common\models\TestObject Object
        (
            [name] => This is the name of the object
        )

)
1Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bytea
The SQL being executed was: UPDATE "session_backend" SET "data"='__flash|a:0:{}test|O:24:"common\models\TestObject":1:{s:4:"name";s:30:"This is the name of the object";}', "expire"=1416641743 WHERE "id"='hdj5648ufpk6d7mjtrh37l5io1'' 
```
## Possible Solution
I was able to resolve this by changing``` 'data' => $data``` to ``` 'data' => base64_encode($data)``` in yii\web\SessionDb::writeSession and ``` return $data === false ? '' : $data;``` to ``` return $data === false ? '' : base64_decode($data);``` in yii\web\SessionDb::readSession. I hesitated to submit a pull request with the change because I don't know how it would affect other database engines.

Also I don't know why it's necessary to convert it to plain text in order for Yii to insert it into a bytea field. #2853 may be related.

**Comment by wallysalami** [comment]
How is the status in this issue? I found the exact same problem here, and the possible solution is not working.

**Comment by SilverFire** [comment]
Until now the issue was not verified.

The problem is related to PgSQL bytea data type and I think we should fix it.
As far as I see, we can deal with the problem by introducing the additional boolean property `encodeSession` to `yii\web\DbSession` and encode/decode the payload when the property is set to true.

**Comment by wallysalami** [comment]
It is one possible solution. Two observations here:

-- We had this problem in Yii 1 and we changed the `data` column to `TEXT` type. That didn't work in Yii 2.
-- Maybe you could check the database type and, if it is PostgreSQL, you would apply encode/decode. But it would be interesting to check which databases have that problem.

A `encodeSession`is probably a good solution, anyway. Just make a friendly explanation in the documentation.

**Comment by SilverFire** [comment]
In this case i'd prefer configuration over convention.

I don't like the idea of autodetecting because it creates an unobvious behavior, breaks the encapsulation of a DB driver (`yii\web\Session` must be DBMS-agnostic and use only abstract interfaces) and breaks the BC.

**Comment by wallysalami** [comment]
You are right.
