### ISSUE TITLE
Incorrect logic for rest CreateAction

### ISSUE THREAD

**Issue by maxlapko** [yiisoft/yii2#6184]
The action returns incorrect model because does not work Location header.
We must call `Yii::$app->end()` when "Location" header is set.

Example: my Fake model has fields(id, name (required), email, created_at, updated_at)
call POST /api/fakes body name: 'Fake name'

Response: 
{"id": 1, "name" => "Fake name"}

When I use GET /api/fakes/1 
Response: 
{"id": 1, "name" => "Fake name", "email": null, "created_at": null, "updated_at": null}

**Comment by dynasource** [comment]
@maxlapko, what is the status of your issue. Have you found a solution yet?

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
