### ISSUE TITLE
yiiActiveForm ajax submit

### ISSUE THREAD

**Issue by aleksanderd** [yiisoft/yii2#6185]
What about to add some method to send the form via ajax? I mean something like this: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L310

I know about external plugins like http://malsup.com/jquery/form/ and it is not too hard to write custom js, but I think it will not be too excess in yiiActiveForm.

My use case: form have two submit buttons: "Save"(ajax submit, without leaving the form or reloading the page) and "Save and close"(usual submit).

**Comment by mdmunir** [comment]
:+1: Agree
could not use pjax because sometimes we need to submit to another url. pjax can not handle this.

**Comment by cebe** [comment]
How could we introduce it in activeform? ajax is custom thing which you can do easily with the following code in view file:

```php
// your form here

    $this->registerJs(<<<'JS'

        var $form = $('#comment-form');
        $form.on('beforeSubmit', function() {
	        var data = $form.serialize();
            $.ajax({
                url: $form.attr('action'),
                type: 'POST',
                data: data,
                success: function (data) {
// handle success
                },
				error: function(jqXHR, errMsg) {
// handle error
					alert(errMsg);
				}
            });
            return false;
        });
JS
```

Please provide some suggestions how this could be done easier with activeform...

**Comment by Alex-Code** [comment]
Can't see why `pjax` can't be used.
I'm sure it handles redirects so on a save and close just do a redirect.

**Comment by mdmunir** [comment]
@cebe Ya, you right. But much better if its become part of activeform :D.
```javascript
{
        init: function (attributes, options) {
            return this.each(function () {
                ...
                if (settings.validateOnSubmit) {
                    $form.on('mouseup.yiiActiveForm keyup.yiiActiveForm', ':submit', function () {
                        $form.data('yiiActiveForm').submitObject = $(this);
                    });
                    $form.on('submit.yiiActiveForm', methods.submitForm);
                }
                if (settings.ajaxSubmit) {
                    $form.on('submit.yiiActiveForm', function(){
                          $(this).yiiActiveForm('ajaxSubmit');
                    });
                }
            });
        },
        ajaxSubmit:function(opt){
            ...
            $.ajax(...);
        }
```
usage
```javascript
$('#myform').yiiActiveForm('ajaxSubmit',{
    url:'url/to/create',
});
```

@Alex-Code 
I am not sure, pjax can handle submit to another url or not. E.g. i am from action `user/index` and want to submit to `user/create`.

**Comment by samdark** [comment]
@mdmunir it can via `url`:

```javascript
$.pjax({url: url, container: '#pjax-container'})
```

**Comment by dynasource** [comment]
see https://github.com/yiisoft/yii2/issues/4985#issuecomment-55687472
