### ISSUE TITLE
No italic typeface in docs, please

### ISSUE THREAD

**Issue by softark** [yiisoft/yii2#6195]
The issue is about the rendering implementation of markdown.

This is **not** an urgent issue, but I would be happy if you would consider it when you would want to  publish the translated definitive guides in Yii's own website.

In general, italic typeface doesn't look good for Chinese and Japanese characters. For these kinds of broad and square characters, italic typeface has no emphasizing effect. It only makes them look weaker and less easy to read. So italic typeface is especially a bad choice for emphasis. 

For example, the following text uses `*...*` for emphasis, and will be rendered using italic typeface:
~~~
(A) ログメッセージをさまざまな *重大性レベル* と *カテゴリ* で記録する。
~~~
(A') ログメッセージをさまざまな *重大性レベル* と *カテゴリ* で記録する。

Bold typeface is rather preferable. For example, the following text uses `**...**`:
~~~
(B) ログメッセージをさまざまな **重大性レベル** と **カテゴリ** で記録する。
~~~
(B') ログメッセージをさまざまな **重大性レベル** と **カテゴリ** で記録する。

Or, is it okay to use `**...**` in the translation in place of `*...*` ?

I would also like to hear the opinion from other people, especially Chinese and other non-western people.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/commit/1c97fc12eee0073e955b41b342444e9b54ec4c3a
