### ISSUE TITLE
Pass `$params` by reference to yii\web\UrlRuleInterface::createUrl()

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#6229]
Now it is not possible to change signature of custom `urlRule::createUrl()` to pass `$params` by reference because:

```
Declaration of common\components\CatalogUrlRule::createUrl() must be compatible with yii\web\UrlRuleInterface::createUrl($manager, $route, $params)
```

With your custom `urlRule` you may pass special `$params` to build pretty url.
Some of them you may need to unset before you return result to `UrlManager` - because if custom rule was not satisfied for some reason you don't want this params to be passed by `UrlManager` to `http_build_query()`  ( https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L329 ).

For example: to build seo-links you may want to pass `Products` and `Category` objects to you custom `urlRule::createUrl()` 
(to avoid in `urlRule` duplicate database trips to retrieve data you already have).

Example of link created by `urlManager` after `urlRule` failed:

```
catalog/product/view?category[path]=tele-video-audio%2F010-televizory-ot-15-do-28
```

Here `category[path]=tele-video-audio%2F010-televizory-ot-15-do-28` was part of `Category` object and `UrlManager` passed it to `http_build_query()` after custom `urlRule` was not satisfied.

For that case I could prefer to unset `Category` object, leaving in params only `category_id` to be processed by `UrlManager`.

Note: BC-breaking changes (see https://github.com/yiisoft/yii2/pull/6220/files )

**Comment by klimov-paul** [comment]
I agreed with @qiangxue.
