### ISSUE TITLE
Inconsistency between docs and Advanced App example

### ISSUE THREAD

**Issue by vincent-dm** [yiisoft/yii2#6230]
I am confused whether I should insert the @ sign when defining an alias.

According to [the documentation](http://www.yiiframework.com/doc-2.0/guide-concept-aliases.html) I should include @ signs:
```php
Yii::setAlias('@foo', '/path/to/foo');
Yii::setAlias('@foo/bar', '/path2/bar');
```

But the Advanced Application example contains this in [its bootstrap.php file](https://github.com/yiisoft/yii2-app-advanced/blob/master/common/config/bootstrap.php):
```php
Yii::setAlias('common', dirname(__DIR__));
Yii::setAlias('frontend', dirname(dirname(__DIR__)) . '/frontend');
Yii::setAlias('backend', dirname(dirname(__DIR__)) . '/backend');
Yii::setAlias('console', dirname(dirname(__DIR__)) . '/console');
```

So my question is: what is Yii's idiom about including the @ sign?

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/b439f75d9ed06b2789e20b6296508393fee62cc8
