### ISSUE TITLE
PDO (mysql) return raw BIT value instead of strings '0' and '1'

### ISSUE THREAD

**Issue by stepanselyuk** [yiisoft/yii2#6233]
Hello,
I have strange behavior (with cloudlinux php): for a BIT mysql field, PDO return '\0' for 0 and '' for 1. With native PHP (there is php-selector) I got normal expected result. I can't find info about that.

I mean when Yii try in `(bool) $value` for phpType `boolean`, it give a wrong result:
```php
(bool) "\0" // true
(bool) "" // false, but actual value in the model field is `true`.
```
I think in that case PDO returned a Raw BIT value:
```php
$pdo = \Yii::$app->db->pdo;

$rows = $pdo->prepare( 'SELECT * FROM `ss_profiles` LIMIT 1' );
$rows->execute();

while ($a = $rows->fetch( \PDO::FETCH_ASSOC )) {
      return ord($a[ 'deleted' ]);
}
// 1 for BIT 1
// 0 for BIT 0
// var_dump( (bool) chr(0) ); // true
// var_dump( (bool) chr(1) ); // true
```

**Comment by SerjRamone** [comment]
I have a similar problem
