### ISSUE TITLE
Inline validator improvement

### ISSUE THREAD

**Issue by grachov** [yiisoft/yii2#6242]
What do you think about passing the validator instance (`$this`) to the `InlineValidator::$method` call? It will provide access to the `Validator`'s common methods like `addError` or `isEmpty`. The first one should be important, because it provide some routine for preparing error message.

**Comment by SilverFire** [comment]
Changing order of attributes is a BC-break, but the use case seems to be valid

**Comment by dynasource** [comment]
I agree. It is not logical to have an inline validator not having access to the InlineValidator class. @grachov , are you willing to do a PR for this?
