### ISSUE TITLE
CORS Filter and authenticator s bug

### ISSUE THREAD

**Issue by xrjxs** [yiisoft/yii2#6254]
## the authenticator will broken the CORS Filter when did the ajax request with rest api.

the code:
```

    public function behaviors()
    {
        $behaviors = ArrayHelper::merge(parent::behaviors(), [
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
            ]
        ]);

        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => 
                  HttpBasicAuth::className(),
                  HttpBearerAuth::className(),
                  QueryParamAuth::className(),
                ]
            ];
    
        return $behaviors;
    }
```

and then do the ajax call with Bearer auth, if the access token match, everything is working nice.
if the access token is wrong, the browser like Chrome will show error and return a canceled status (it means the ajax can not get the response json data):
XMLHttpRequest cannot load Origin “xxx” is not allowed by Access-Control-Allow-Origin.

the bugs was in the code 'beforeAction' of the classes Http****Auth, it will return false or null when the access token was wrong. but the return false or null also stop the CORS Filter class, the header 'Access-Control-Allow-Origin' will not sent. (maybe the invoked order issue of the external actions).

the bug was shown under yii2 RC.

**Comment by hanski07** [comment]
As @fernandezekiel suggested, my problem was HttpBearerAuth trying to authenticate the preflight request which shouldn't send a bearer token or any other form of authentication. My workaround was to add an `actionPreflight` to my controller, and routed all my OPTION requests to this action so I could avoid authenticating that action, and just not return anything so the headers would be sent to the client verifying my server supports CORS. Seems hackish, but I couldn't think of a better way of doing that , and I needed to get moving quickly on my project.

**Comment by OmgDef** [comment]
The same problem. Workaround
```php
$behaviors['authenticator'] = [
    'class' => HttpBearerAuth::className(),
    'except' => ['options'],
];
```

**Comment by lanmower** [comment]
DarwinIsGod's option worked, I initially never tried because I thought routing to the already available options action would fix it, and when it didn't never tried making my own.

+1

**Comment by riverlet** [comment]
This is a bug, Maybe

see: http://stackoverflow.com/questions/26296779/chrome-v37-38-cors-failing-again-with-401-for-options-pre-flight-requests

``` According to the CORS specification when a user agent (thus, a browser) preflights a request(requests with OPTIONS HTTP method), it MUST exclude the user credentials (cookies, HTTP authentication...) so any OPTIONS request cannot be requested as authenticated. The browser will request as authenticated the actual request (the one with the requested HTTP method like GET, POST...), but not the preflight request.
So browsers MUST not send the credentials in OPTIONS request. They will do in actual requests. If you write withCredentials = true the browser should do what I say. ```

**Comment by tunecino** [comment]
I think the reason why this issue is happening here is because the `authenticator` filter is getting treated before the `corsFilter`. 

check the content of `parent::behaviors()` [here](https://github.com/yiisoft/yii2/blob/4a3a94346d76e2aaac577065b159735c5b8db870/framework/rest/Controller.php#L46). `authenticator` is defined but not `corsFilter`, so any attempt to merge an array with named keys `authenticator` and `corsFilter` will just override the first and push the second (`corsFilter`) to the bottom of the array. reason why CORS are only working if authentication succeed and never reached otherwise.

to confirm this please any one try to rename `$behaviors['authenticator'] =` to just `$behaviors[1] =` or to define no keys like :
 
```php
return \yii\helpers\ArrayHelper::merge([
    [
        'class' => Cors::className(),
        'cors' => [ ... ],
    ],
    [
        'class' => HttpBearerAuth::className(),
    ],
], parent::behaviors());
```

If it work then a solution to this would be by simply defining `corsFilter` just before `authenticator` inside `yii\rest\Controller::behaviors()` :
```php
...
'corsFilter' => [
      'class' => Cors::className(),
],
'authenticator' => [
...
```

Cors filter is needed by most people using rest any way and its default configs should work for any one I guess (see [this](https://github.com/yiisoft/yii2/blob/4a3a94346d76e2aaac577065b159735c5b8db870/framework/filters/Cors.php#L81)). the other option would be removing 'authenticator' from `parent::behaviors()` and let developper define both inside his controller in the order he choose.

**Comment by tunecino** [comment]
one more thing. the `authenticator` should be defined this way :
```php 
[
    'class' => \yii\filters\auth\HttpBearerAuth::className(),
    'except' => ['options'],
],
```
in order to OPTIONS to work.

**Comment by viyancs** [comment]
this code work for me

[
    'class' => \yii\filters\auth\HttpBearerAuth::className(),
    'except' => ['options'],
],

thanks, but i think core team should be fix this , because api rest and authentication + cors filter is huge needed.

**Comment by viyancs** [comment]
This issue still come after sometimes run, then i try to separating check cors by adding manually function.

```javascript
function cors() {

        // Allow from any origin
        if (isset($_SERVER['HTTP_ORIGIN'])) {
            header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
            header('Access-Control-Allow-Credentials: true');
            header('Access-Control-Max-Age: 86400');    // cache for 1 day
        }

        // Access-Control headers are received during OPTIONS requests
        if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {

            if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
                header("Access-Control-Allow-Methods: GET, POST, OPTIONS");         

            if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
                header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

            exit(0);
        }
    }
```
//call by 
```javascript
public function behaviors()
    {
        $this->cors();

        $head = [
            [
                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                ]
            ],

            [
                'class' => \yii\filters\auth\HttpBearerAuth::className(),
                'except' => ['options'],
            ],
        ];
        
        return \yii\helpers\ArrayHelper::merge($head, array());        
        
    }
```

i think any something wrong when check cors using yii function.but i dont know where is it.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2/pull/8626

**Comment by ydatech** [comment]
this code works for me :
`public function behaviors()
		{
			$behaviors = parent::behaviors();
			unset($behaviors['authenticator']);
			$behaviors['corsFilter'] = [
			'class' => Cors::className(),
			];
			$behaviors['authenticator'] = [
			'class' =>  HttpBearerAuth::className(),
			'except' => ['options'],
			
			];
			return $behaviors;
			
		}`
