### ISSUE TITLE
Js Validation doesn't work properly for couple same models in one <form>

### ISSUE THREAD

**Issue by serginnios** [yiisoft/yii2#6285]
Let's say a have one form where I want to modify Physical and Billing addresses using one form. Both addresses are entities of one class 'Address' which has one property 'Street' (required). To show name for both of them I'm using the same view where I have:

<?= $form->field($address, 'street')->textInput('name' => "Address[$index][street]"]) ?>

Here I have 2 problems:
1. In result on one page I will have two inputs with the same 'id'.
2. When I clear the street for the Physical address validation highlights also the street for Billing address but it's not correct as Billing address has the street.

To violate the first problem I can do:
<?= $form->field($address, 'street', ['inputOptions' => ['id'=>'name_'.$index])->textInput('name' => "Address[$index][street]"]) ?>

But in this case js validation does not work at all. The reason is  that two inputs have the wrapper (div) with the same 'class' = 'field-address_name'

As I see the problem is in ActiveField class (lines 207 and 726):

$inputID = Html::getInputId($this->model, $this->attribute);

For me works the following: 

$inputID = isset($this->inputOptions['id']) ? $this->inputOptions['id'] : Html::getInputId($this->model, $this->attribute);

**Comment by dynasource** [comment]
solved by https://github.com/yiisoft/yii2/pull/11171
