### ISSUE TITLE
Column definition format for GridView

### ISSUE THREAD

**Issue by omnilight** [yiisoft/yii2#6293]
I think it would be very nice if we could define columns for grid view in the following form:

``` php
[
    'attribute' => function($data) {
        return $data->someValue;
    }
]
```

where callback is used for cell value (simillar to 'value' property of the existed form).

This is very usefull when you want to change just value shown in the grid cell, and is much shorter than currently used form (of couse support of it should not be removed).

I can make pull request for this.

**Comment by dynasource** [comment]
see Cebes comment
> you can already assign a closure to 'content' to achive this.

Its already possible. Allowing more ways to do the same thing is not a good practice and will lead to confusion.
