### ISSUE TITLE
bootstrap ActiveField config not applied

### ISSUE THREAD

**Issue by Stevad** [yiisoft/yii2#6312]
What I try to do: 
1) create own ActiveField class with changed `template` and `horizontalCssClasses`

```php
namespace app\components;
class ActiveField extends \yii\bootstrap\ActiveField
{
    public $template = "{label}\n{beginWrapper}\n{input}\n{error}\n{hint}\n{endWrapper}";

    public $horizontalCssClasses = [
        'offset' => 'col-sm-offset-3',
        'label' => 'col-sm-3',
        'wrapper' => 'col-sm-6',
        'error' => '',
        'hint' => '',
    ];
}
```

2) then I use my class in ActiveForm:

```php
<?php $form = ActiveForm::begin([
        'fieldClass' => 'app\components\ActiveField',
        'layout' => 'horizontal'
    ]); ?>
...
```

But if I dump some field like `$form->field($model, 'name')` I see that `template` and `horizontalCssClasses` not changed (their values are default from native `\yii\bootstrap\ActiveField`).

Dump: 
```
object(app\components\ActiveField)[136]
  public 'template' => string '{label}
{beginWrapper}
{input}
{error}
{endWrapper}
{hint}' (length=58)
  public 'horizontalCssClasses' => 
    array (size=5)
      'offset' => string 'col-sm-offset-3' (length=15)
      'label' => string 'col-sm-3' (length=8)
      'wrapper' => string 'col-sm-6' (length=8)
      'error' => string '' (length=0)
      'hint' => string 'col-sm-3' (length=8)
  public 'inline' => boolean false
  public 'inputTemplate' => null
...
```

instead of

```
object(app\components\ActiveField)[136]
  public 'template' => string '{label}
{beginWrapper}
{input}
{error}
{hint}            <-- hint before endWrapper
{endWrapper}' (length=58)
  public 'horizontalCssClasses' => 
    array (size=5)
      'offset' => string 'col-sm-offset-3' (length=15)
      'label' => string 'col-sm-3' (length=8)
      'wrapper' => string 'col-sm-6' (length=8)
      'error' => string '' (length=0)
      'hint' => string '' (length=0)          <-- hint value must be empty
  public 'inline' => boolean false
  public 'inputTemplate' => null
...
```

I think this is error in `\yii\bootstrap\ActiveField` class.

**Comment by bizley** [comment]
I'm sorry for going necro on this one but I've just spent some time on the same problem and I really don't see the point of this special overriding requirement.
```horizontalCssClasses``` can only be changed during instance configuration now and it looks like exception from the rest od framework functionality (or maybe not? Are there other cases like this?). Anyway - I strongly believe one should be allowed to override this attribute as-is.

This can be fixed by adding:

    if (!empty($this->horizontalCssClasses)) {
        $cssClasses = ArrayHelper::merge($cssClasses, $this->horizontalCssClasses);
    }

before 

    if (isset($instanceConfig['horizontalCssClasses'])) {
        $cssClasses = ArrayHelper::merge($cssClasses, $instanceConfig['horizontalCssClasses']);
    }

in https://github.com/yiisoft/yii2-bootstrap/blob/master/ActiveField.php#L374

**Comment by cebe** [comment]
could that break other use cases?

**Comment by bizley** [comment]
It should not. ```$instanceConfig['horizontalCssClasses']``` is merged after ```$this->horizontalCssClasses``` in my fix so default functionality is the same and you can still override this array during instance configuration.

**Comment by cebe** [comment]
can you send a pull request?

**Comment by mikehaertl** [comment]
@cebe Could you wait a little before merging any PR? As the original author I'd like to think this through again. There probably was a reason why it was implementet this way - but I have to study the code first.

I'd report back here.

**Comment by bizley** [comment]
Ok, waiting for green light.

**Comment by mikehaertl** [comment]
Ok, I think the change makes sense. My idea was, that you'd never have to extend `ActiveField` and instead create your custom `ActiveForm` classes like:

```php
class SlimActiveForm extends \yii\bootstrap\ActiveForm
{
    public $layout = 'horizontal';
    public $fieldConfig = [
        'enableLabel' => false,
        'template' => '{beginWrapper} {input} {endWrapper} {error}',
        'horizontalCssClasses' => [
           'offset' => '',
           'label' => '',
           'wrapper' => 'col-sm-6',
           'error' => 'col-sm-6',
           'hint' => '',
        ],
    ];
}
```

But I agree, that each class should be extensible, so we should fix this. It's possible that you don't want to share the same field configuration for all fields, but override the `fieldClass` with your custom `class` in `$options` when calling `field()`. I didn't have this case in mind.

@bizley If I don't miss anything, I think you don't need another array merge. Instead you could simply replace line 367 with this:

```php
$cssClasses = $this->horizontalCssClasses!==null ? $this->horizontalCssClasses : [
    'offset' => 'col-sm-offset-3',
    ...
```

**Comment by mikehaertl** [comment]
@bizley Actually we could even move the defaults in line 367 to the top and set them as default values for the `public $horizontalCssClasses` to make them even more obvious. The code would then simplify to:

```php
$cssClasses = $this->horizontalCssClasses;
if (isset($instanceConfig['horizontalCssClasses'])) {
    $cssClasses = ArrayHelper::merge($cssClasses, $instanceConfig['horizontalCssClasses']);
}
```

**Comment by bizley** [comment]
@mikehaertl I was about to write the same thing ;)
So, since you are the author would you like to prepare PR or should I do it?

**Comment by mikehaertl** [comment]
@bizley Can you test my PR?

**Comment by bizley** [comment]
@mikehaertl Tested, perfect.

**Comment by mikehaertl** [comment]
@cebe Ok, if it looks good to you, feel free to merge.
