### ISSUE TITLE
ErrorHandler onException event

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#6354]
I'd like to log errors and exceptions to [errbit](https://github.com/errbit/errbit).
Yii 1 had onError and onException events. Yii 2 does not. I have to extend both \yii\web\ErrorHandler and \yii\console\ErrorHandler, and override the logException method to send the exception to errbit. It'd be more convenient if I could just attach a behavior to handle an event to both error handlers.

**Comment by klimov-paul** [comment]
Relates #7305

**Comment by klimov-paul** [comment]
`Logger::log()` allows message not only as string but also "more complex data structure". So we may consider allowing entire `Exception` object logging.

**Comment by samdark** [comment]
That would be handy and isn't breaking BC.

**Comment by cebe** [comment]
looks like it is as simple as this https://github.com/yiisoft/yii2/pull/8436, not finally sure about BC though...

**Comment by omgnull** [comment]
Because of this change I got spammed with
```
[Wed May 20 15:43:23 2015] PHP Warning:  var_export does not handle circular references in /var/vendor/yiisoft/yii2/helpers/BaseVarDumper.php on line 187
[Wed May 20 15:43:23 2015] PHP Stack trace:
[Wed May 20 15:43:23 2015] PHP   1. yii\log\Logger->flush() /var/vendor/yiisoft/yii2/log/Logger.php:0
[Wed May 20 15:43:23 2015] PHP   2. yii\log\Dispatcher->dispatch() /var/vendor/yiisoft/yii2/log/Logger.php:173
[Wed May 20 15:43:23 2015] PHP   3. yii\log\Target->collect() /var/vendor/yiisoft/yii2/log/Dispatcher.php:183
[Wed May 20 15:43:23 2015] PHP   4. yii\log\DbTarget->export() /var/vendor/yiisoft/yii2/log/Target.php:112
[Wed May 20 15:43:23 2015] PHP   5. yii\helpers\BaseVarDumper::export() /var/vendor/yiisoft/yii2/log/DbTarget.php:70
[Wed May 20 15:43:23 2015] PHP   6. yii\helpers\BaseVarDumper::exportInternal() /var/vendor/yiisoft/yii2/helpers/BaseVarDumper.php:147
[Wed May 20 15:43:23 2015] PHP   7. var_export() /var/vendor/yiisoft/yii2/helpers/BaseVarDumper.php:187
```

**Comment by omgnull** [comment]
Reproduction:
```
$ composer global require "fxp/composer-asset-plugin:~1.0.0"
$ composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic
```

change logger target to db
```php
// config/web.php
'log' => [
    'traceLevel' => YII_DEBUG ? 3 : 0,
    'targets' => [
        [
            'class' => 'yii\log\DbTarget',
            'levels' => ['error', 'warning'],
        ],
    ],
],
```

throw UnauthorizedHttpException
```php
// controllers/SiteController.php
public function actionIndex()
{
    throw new \yii\web\UnauthorizedHttpException();
}
```

run server
```
$ cd basic/web
$ php -S localhost:8080
```

see logs
```
$ curl http://localhost:8080/index.php
```

**Comment by klimov-paul** [comment]
Relates #8723

**Comment by cebe** [comment]
fixed, thanks for reporting!

**Comment by cursesun** [comment]
vendor/yiisoft/yii2/helpers/BaseVarDumper.php on line 187

**Comment by dmarcos89** [comment]
Hey, i just found this thread, hope anyone can help me with this. 
I am currently working on a yii1.1 project and integrated Sentry to it. The thing is that as mentioned earlier the log() methods receives a message as a string even if an exception, hence, i cannot use the $sentry->captureException... 

I did the following in the base controller:
```
