### ISSUE TITLE
Quoted DB expression when used in param

### ISSUE THREAD

**Issue by klevron** [yiisoft/yii2#6382]
Hello

DB Expression is quoted when used in param, e.g. 

```php
MyModel::deleteAll("expire < :expire", [':expire' => new Expression('NOW()')]);
```

This will make the following query :
```sql
DELETE FROM `expire` WHERE expire < 'NOW()';
```

Be careful, debug tool will log the correct one :
```sql
DELETE FROM `expire` WHERE expire < NOW();
```

http://stackoverflow.com/questions/27312579/odd-behavior-of-now-and-db-expression-in-yii2-mysql

**Comment by bionoren** [comment]
I suspect this is because yii\db\mysql\QueryBuilder:183 is looking for Expression in the current namespace (\yii\db\mysql), but the class actually exists in \yii\db, so that instanceof check always fails. Can somebody fix that to either fully qualify Expression or use it?

**Comment by cebe** [comment]
@bionoren why do you write undera totally unrelated issue? please report a new on next time. This has been fixed by https://github.com/yiisoft/yii2/pull/8596 already.
