### ISSUE TITLE
pjax doubles the target content

### ISSUE THREAD

**Issue by bdart** [yiisoft/yii2#6384]
Hi there is a little problem with the pjax addon.
With the following, pjax doubles the `<div>` box on submit so that I get a second `<div>` box but without my `class="site-index"`

``` html
<div class="site-index" id="marker">
</div>
<?php Pjax::begin(['id'=>'marker', 'linkSelector'=>'.slider_inner_slide a']); ?>
<?php Pjax::end(); ?>
```

generates this browser code:

```
<div class="site-index" id="marker">
  <div class="body-content">...</div>
</div>
<div id="marker">
  <div class="body-content">...</div>
</div>
```

But when I bind it to the class like that `Pjax::begin(['class'=>'site-index', 'linkSelector'=>'.slider_inner_slide a']);` it works properly also when I add the `id="marker"`

So my problem is solved and I can change the bindings but why is it doubling the div? Maybe I oversee something in my understanding.

**Comment by dynasource** [comment]
this is expected behavior as you have created two containers with the same ID.
