### ISSUE TITLE
Bootstrap Asset dependencies

### ISSUE THREAD

**Issue by dirtyman** [yiisoft/yii2#6385]
The layout needs:
```php
public $depends = [
'yii\web\YiiAsset',
'yii\bootstrap\BootstrapAsset',
'yii\bootstrap\BootstrapPluginAsset',
'app\web\assets\thirdparty\ThirdPartyAsset', ];
```

The thirdparty needs:
```php
public $depends = [
'yii\bootstrap\BootstrapPluginAsset', ];
```

Everything is ok, until I need to make a ajax request to a page who requires the thirdparty asset.
But when I call the thirdparty, it will call BootstrapPluginAsset, loading the js files and the css files.
The reloaded of the css files breaks the layout. So, removing this [line](https://github.com/yiisoft/yii2/blob/master/extensions/bootstrap/BootstrapPluginAsset.php#L26) solves my problem. 

Is this [line](https://github.com/yiisoft/yii2/blob/master/extensions/bootstrap/BootstrapPluginAsset.php#L26) necessary for all cases in Yii 2? Because it can override the css file when doing a ajax request when you need the bootstrap js file.

**Comment by klimov-paul** [comment]
Should be resolved by https://github.com/yiisoft/jquery-pjax/pull/30
