### ISSUE TITLE
Improve the documentation for yii\widgets\BaseListView - minor issue

### ISSUE THREAD

**Issue by eresik** [yiisoft/yii2#6391]
I think that would be good idea to inform in the documentation (phpdoc to the method) that the property $pager->pagination (class yii\widgets\BaseListView) uses the configuration of the $dataProvider->pagination, and can not be overriden by the yii\widgets\BaseListView configuration.

For example:

```php
        $provider=new ActiveDataProvider([
              'pagination'=>[
                    'pageSize'=>10  // <=== HAS EFFECT 
              ]
        ]);

        echo \yii\widgets\ListView::widget([
            'dataProvider'=>$provider,
            'pager'=>[
                'pagination'=>[                                
                    'pageSize'=>10, // <=== HAS NOT EFFECT
                ]
            ],
```

The reason: https://github.com/yiisoft/yii2/blob/master/framework/widgets/BaseListView.php#L228

**Comment by githubjeka** [comment]
**It is necessary to describe this situation more clearly.**

http://yiiframework.ru/forum/viewtopic.php?f=19&t=43520&p=217443#p217441

**Comment by samdark** [comment]
It is good as is.

**Comment by githubjeka** [comment]
>  the property $pager->pagination (class yii\widgets\BaseListView) uses the configuration of the $dataProvider->pagination, and can not be overriden by the yii\widgets\BaseListView configuration.

**can not be overriden** - it's main. Now the documentation doesn't talk about it.

**Comment by samdark** [comment]
> Note that the widget must support the `pagination` property which will be populated with the
> [[\yii\data\BaseDataProvider::pagination|pagination]] value of the [[dataProvider]].

**Comment by samdark** [comment]
That's from current phpdoc.

**Comment by githubjeka** [comment]
will be populated != can not be overriden
