### ISSUE TITLE
SphinxSearch uint / bigint bad convertion with the where clause of the Query : bug ? 

### ISSUE THREAD

**Issue by nozostan** [yiisoft/yii2#6397]
Hi,

I use the sphinx extension ant I have an index containing an attribute with the type "uint".

I try to build a Sphinx Query using the  "andFilterWhere" function with my attribute as parameter.
But when this query is executed (thanks to an ActiveDataProvider), the SQL command is generated with the where clause " AND `myAttribute` = 'value' ". So the value is automaticly converted into string even if the schema type is considered like an integer and I get the error "PDOException [...] unsupported filter type 'string' on int column".

After some investigations, I found it seems that the "getColumnPhpType" function of the Schema Class is responsible of this convertion, especially this piece of code : 
[...]
if ($column->type === 'bigint') {
                return PHP_INT_SIZE == 8 ? 'integer' : 'string';
            } elseif ($column->type === 'integer') {
                return PHP_INT_SIZE == 4 ? 'string' : 'integer';
[...]

When I trace the PHP_INT_SIZE value, I get "4". 
When I trace the types of my attribute into the loadColumnSchema function thanks to : 
         Yii::trace("TYPE HERE : ".$column->name." | ".$column->type." | ".$column->phpType);
I get : 
         TYPE HERE : state | integer | string

I tried to do an ugly hack and I modify the Yii code as following : 
[...]
                return PHP_INT_SIZE == 4 ? 'integer' : 'integer';
[...]
and it worked. My SQL command was generated with an integer syntax : " AND `myAttribute` = value "

My code to build the query is the following : 
[...]
$query->select('id')
           ->from($this->index)
           ->match($criteria)
           ->andFilterWhere([$attr=>$value]);
[...]

So is this a bug or is it something I do not understand or I do wrong ?

Thanks a lot by advance for your answer ^^

**Comment by elim051** [comment]
I think it is a bug since yii2 2.04 or 2.03, this bug only appear on windows system, both 32bit and 64bit. hope to fix it... many thanks.

**Comment by klimov-paul** [comment]
Resolved by commit bcdb53cb990a34319229c50127cb6b327279d1e7
