### ISSUE TITLE
HttpCache - $_SERVER['HTTP_IF_MODIFIED_SINCE']) is not set

### ISSUE THREAD

**Issue by indicalabs** [yiisoft/yii2#6418]
I am using the below stack.
Server : nginx
Browser: Firefox 33.1
OS : Mac
PHP: 5.6
The <code>$_SERVER['HTTP_IF_MODIFIED_SINCE'])</code> is not set which is why the HttpCache is not working as expected.

**Comment by samdark** [comment]
Closing since nginx environment config beyond basics is out of framework scope.
