### ISSUE TITLE
Remove $_SERVER from default logVars in Target

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#6419]
I noticed that a log `Target` displays the $_SERVER variables [by default](https://github.com/yiisoft/yii2/blob/master/framework/log/Target.php#L61).

I suggest to remove this default because more and more applications store their credentials in environment variables, which are also often available in $_SERVER. 

And i.e. a misconfigured log route or YII_ENV setting could expose settings to an end-user when getting an exception.

I know that this should not happen in a correct configured environment, none the less I think the risk could be minimized through this change.

**Comment by schmunk42** [comment]
To be more specific here...

These values should be at least customizeable: https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L298

And I'd propose to remove _ENV and _SERVER by default from a **web** exception.

Any thoughts?

**Comment by samdark** [comment]
Making values customizable is fine.

**Comment by schmunk42** [comment]
What's about the defaults?

**Comment by samdark** [comment]
Could be turned off, I guess. It won't break anything at least.

**Comment by nirvana-msu** [comment]
+1 for turning it off by default. It is often the most convenient way to store sensitive config in environmental variable.

**Comment by nirvana-msu** [comment]
I don't actually mind logging `$_SERVER`, if only there was a way to exclude all the environmental variables.

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/c651dbb798b3ff4735fc64b3f0779810ee965b31
Thank you

**Comment by timaschew** [comment]
It has been enabled again, see https://github.com/yiisoft/yii2/blob/master/framework/log/Target.php#L61
and the docs: https://www.yiiframework.com/doc/guide/2.0/en/runtime-logging#message-formatting

**Comment by samdark** [comment]
It was removed from displaying these in error screen, not from logging. See https://github.com/yiisoft/yii2/commit/7ac2bc13f70589e133958814383f8a6d364ec429
