### ISSUE TITLE
Problems with the method goBack()

### ISSUE THREAD

**Issue by sowich** [yiisoft/yii2#6431]
How can I return to the page where the logout button was clicked?  The ```goBack()``` method always returns to the home page.  ```setReturnUrl``` doesnt work here too.

**Comment by klimov-paul** [comment]
Unable to reproduce.

At some action:
```php
Yii::$app->user->setReturnUrl(Yii::$app->request->url);
````

At logout action:
```php
Yii::$app->user->logout(false);
return $this->redirect(Yii::$app->user->getReturnUrl());
```

Works fine.
