### ISSUE TITLE
Relation with yii\mongodb\ActiveRecord return empty []

### ISSUE THREAD

**Issue by MaslennikovYV** [yiisoft/yii2#6436]
class Page extends yii\mongodb\ActiveRecord {
...
}

class Website extends \yii\db\ActiveRecord
{
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPages()
    {
        return $this->hasMany(Page::className(), ['website_id' => 'id']);
    }
}

Website::find()->with('pages') Attribute  'pages' always empty.

**Comment by klimov-paul** [comment]
What is DB type of `Website::id`?

**Comment by MaslennikovYV** [comment]
MySQL

**Comment by klimov-paul** [comment]
What type: integer, bigint, unsigned?

**Comment by MaslennikovYV** [comment]
In db INT(11) UNSIGNED NOT NULL,
in yii model marcked as integer
```
public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer'],
```

**Comment by klimov-paul** [comment]
Duplicates #2424
