### ISSUE TITLE
problem when using MEDIUMINT UNSIGNED type in mysql

### ISSUE THREAD

**Issue by noghteh** [yiisoft/yii2#6441]
I had problem when using MEDIUMINT UNSIGNED type in mysql. I think it is a bug so I made some changes in yii\db\Schema class , in "getColumnPhpType" method (line 501) : 
```
if ($column->type === 'bigint') {
    return PHP_INT_SIZE == 8 && !$column->unsigned ? 'integer' : 'string';
} elseif ($column->type === 'integer' && stripos($column->dbType, 'mediumint') === false) {
    return PHP_INT_SIZE == 4 && $column->unsigned ? 'string' : 'integer';
} else {
    return $typeMap[$column->type];
}
```
but I think it could be solved in a better way.

**Comment by klimov-paul** [comment]
MySQL 'mediumint' converted to absrtact schema type 'integer' correctly.
Maximum valude of 'unsigned mediumint' exceeds PHP_INY_SIZE at 32-bit systems, so string is used for them.
You should use 64-bit system in order to manipulate such values as integers.
