### ISSUE TITLE
Make mkdir more verbose in debugging

### ISSUE THREAD

**Issue by bryglen** [yiisoft/yii2#6442]
![screen shot 2014-12-10 at 3 09 49 pm](https://cloud.githubusercontent.com/assets/875604/5372108/ac99afe8-807e-11e4-936c-fdd9299f2d27.png)

I got mkdir(): File exists, but what kind of directory is trying to create? please make it more verbose to how the `$path` to help us in debugging

**Comment by klimov-paul** [comment]
Resolved by #7939
