### ISSUE TITLE
is it possible to use same keys in listBox array

### ISSUE THREAD

**Issue by antokara** [yiisoft/yii2#6445]
Perhaps I am missing something.

I want to create a:

```
$field->listBox([
'val1'=>'label1',
'val1'=>'label1',
'val2'=>'label2',
])
```

Note that I want to have "val1" more than once, since there are cases where I need the same key to be in the list many times, especially on multiple select. Using pure HTML and PHP I can create a select with the same val option more than once and successfuly POST those on PHP as distinct array entries... So it is possible.

The problem is that arrays cannot have the same Key more than once, so how can I implement this with an active form field?

Same issue applies to all field types that have the $items parameter I believe...

**Comment by qiangxue** [comment]
This is not currently possible. The fix is not trivial.

**Comment by antokara** [comment]
Yes, I understand that due to the current functionality, its difficult, if not impossible to make the same function backwards compatible. Plus this affects all field types that use the $items array parameter...
Not sure how this could be resolved elegantly without B/C.

**Comment by dynasource** [comment]
like you both are stating: this is hard in the current architecture. A lot of parts have to be rewritten for this rare usecase. It would be easier to fix this with a trick. You assign random numbers to the keys beforehand (perhabs after an underscore) and after rendering you remove the these numbers with a regex.
