### ISSUE TITLE
\yii\filters\auth\HttpBasicAuth

### ISSUE THREAD

**Issue by mbischof** [yiisoft/yii2#6449]
cannot get this to work, error as follows:
exception 'yii\web\UnauthorizedHttpException' with message 'You are requesting with an invalid credential.' in ...\vendor\yiisoft\yii2\filters\auth\AuthMethod.php:73

can anybody give a working example?

**Comment by RomeroMsk** [comment]
@mbischof, did you set `auth` property of `HttpBasicAuth`? Without it filter will try to find user by access_token:
https://github.com/yiisoft/yii2/blob/master/framework/filters/auth/HttpBasicAuth.php#L76

**Comment by connected** [comment]
I confirm. Basic auth. filter doesn't pop out default credentials dialog no matter what. Only if you comment out yii2\filter\auth\AuthMethod.php:56

**Comment by RomeroMsk** [comment]
@connected, I'm not confirming this. Everything is fine for me: dialog appears. But I couldn't use username+password from AR User model before setting correct callback in `HttpBasicAuth::auth` (by default it will try to use auth by access_token instead of username+password).

**Comment by connected** [comment]
Yes, You are right! The problem was in the overridden error action. Error action must RETURN value! I had echo statement there, so "WWW-Authenticate" header wasn't sent.

**Comment by samdark** [comment]
Closed since @connected and @RomeroMsk confirmed that it works.
