### ISSUE TITLE
Request::loadCookies not loading cookies

### ISSUE THREAD

**Issue by ivokund** [yiisoft/yii2#6465]
Hi,

I'm having a strange issue on a test server that "just broke" some time ago, everything's fine on other environments, so it should be a configuration/server issue.

Basically, the problem is that CSRF validation does not work, because Yii2 does not seem to be able to retrieve the _csrf cookie. No errors, warnings or anything, just the cookies are not loaded.

I've traced it to `yii\web\Request::loadCookies`. The cookies are present in `$_COOKIE`:

```
array(2) {
  ["PHPSESSID"]=>
  string(26) "mgpl2kfhu20i7lhqr9gkmkpqb5"
  ["_csrf"]=>
  string(104) "bcaf5fc8563a9bb83294d5db31e7103b32082d51b48727a95301d1f9c1986caes:32:"pDHU7yR7dMArTtn8g99-nAZqq9ychtQH";"
}
```

but at the end of the method, `$cookies` array is empty.  It seems that the `Yii::$app->getSecurity()->validateData($value, $this->cookieValidationKey)` check returns false and so the cookies don't get set. I have `cookieValidationKey` set and haven't customized anything related to cookies. Also, `validateData` returns false with the same input on other servers, so I'm guessing the data already in `$_COOKIE` is corrupt somehow. 

How should I begin to debug something like this or are there any "probable causes" for this kind of behavior?

Test code:

``` php
$value = Yii::$app->getSecurity()->validateData('bcaf5fc8563a9bb83294d5db31e7103b32082d51b48727a95301d1f9c1986caes:32:"pDHU7yR7dMArTtn8g99-nAZqq9ychtQH";', 'jQWhJIOXCiBp_R7M1GW2w_gzDt6myphG');
var_dump($value); // returns false
```

Thanks!

**Comment by Eseperio** [comment]
I have the same problem. I´m using advanced template. And [loadCsrfToken](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L1298) returns an empty value, so each time the page is reloaded the _csrf is new. But if i define a custom csrfParam it works well. Also keeps creating a cookie with name _csrf, so i have both, and no one of them changes after reload.

**Comment by cebe** [comment]
This sounds like a conflict with backend and fronted part of the advanced app, which has been solved by introducing different cookie names in the default config: https://github.com/yiisoft/yii2-app-advanced/commit/ec1148c4f62e12098a3eb650f8e66fe6c23a6323 https://github.com/yiisoft/yii2-app-advanced/commit/bb35a7543aa5b718b01d6cd576d78da9e4193249

closing this issue unless there is a way to reproduce it. Please provide further info or even a failing unit test if you know how to reproduce it.
