### ISSUE TITLE
Problem with 'enableAjaxValidation' option for ActiveField

### ISSUE THREAD

**Issue by tahirm** [yiisoft/yii2#6466]
I am trying to enable ajax validation only for one field in form not for the whole form. So to do that I am using [enableAjaxValidation](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#$enableAjaxValidation-detail) option of ```ActiveField```.
Following is an example of such implementation:
````php
<div class="col-lg-5">
  <?php 
    $form = ActiveForm::begin(['id' => 'form-signup']); 
    $form->enableAjaxValidation = false;
  ?>
  <?= $form->field($model, 'date', ['enableAjaxValidation' => true]) ?>
  <?= $form->field($model, 'name') ?>
  <div class="form-group">
    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button' ]) ?>
  </div>
  <?php ActiveForm::end(); ?>
</div>

````
Now I am facing very specific problem while doing this.
As you can see from code that ajax validation is enabled only for ```date```field. Now after loading the form if I click and edit ```date```field FIRST then for some strange reasons ajax validation is enabled for all other form fields as well and form sends an ajax validation request even when I change something in ```name```field, which by default didn't have ajax validation enabled.

On the other hand, after loading the form if I click and edit ```name```field FIRST then everything works fine and form doesn't send ajax validation request for ```name```but only for ```date```.

**Comment by pana1990** [comment]
The problem may be in you implemented the server side.

please, can you show controller?

**Comment by tahirm** [comment]
I have checked it again after updating to 2.0.2 and proper server implementation and it seems to work fine now.
