### ISSUE TITLE
Log targets append context message on every occasion

### ISSUE THREAD

**Issue by clipworks** [yiisoft/yii2#6470]
The collect function of the \yii2\log\Target class does a context message append just before exporting. However it does this after the messages have been filtered and it does not filter again. 

What happens is every single log target gets this application info-level contextmessage appended, even though the categories and/or except rules this target has tell it not to include them.

It's being done regardless of anything:
$this->messages[] = [$context, Logger::LEVEL_INFO, 'application', YII_BEGIN_TIME];

This way I can't set up log targets that exclude these messages and thus every log target get's polluted by this even though I tell them not to.

**Comment by qiangxue** [comment]
If you do not want such message for a particular target, you can simply configure its `logVars` to be an empty array.
