### ISSUE TITLE
How about translate phrase of `Yii::t` out of framework directory?

### ISSUE THREAD

**Issue by NabiKAZ** [yiisoft/yii2#6474]
How about translate phrase of `Yii::t` out of framework directory?
Now there are some messages in `extensions`, `tests` directories, But when use `yii message` just provide messages of `framework` directory.
Do you thinks the `yii message` command must be customize for search in one level before of `framework` directory? or for that directories must create self `message` directory and put array of phrase in here for translate it?
![yii-messages](https://cloud.githubusercontent.com/assets/246721/5396124/8ccb9b2c-8164-11e4-9e9f-8ff712432585.png)

**Comment by klimov-paul** [comment]
Sinse extensions are maintained as separated repositories now, issue no longer make sense.
