### ISSUE TITLE
problems with URL's when running the command "yii asset" in windows

### ISSUE THREAD

**Issue by ageeweb** [yiisoft/yii2#6484]
paths use / and \ in the same path
windows used "\" linux, mac and Yii use "/" and for css "/" is also not a problem.

I had some sort of error as in "https://github.com/yiisoft/yii2/issues/4881#issuecomment-66674145", 
I use windows too. 
```
$inputFilePath = str_replace('\\', '/', $inputFilePath);
$outputFilePath = str_replace('\\', '/', $outputFilePath);
```
only works for css, not for js
after this I found another 3 errors):

this are the problems and solutions I found:
1>
I have changed: `protected function buildTarget($target, $type, $bundles)
$tempFile = str_replace(['/','\\'],DIRECTORY_SEPARATOR, ( $target->basePath . DIRECTORY_SEPARATOR . strtr($target->$type, ['{hash}' => 'temp'])));`
I use DIRECTORY_SEPARATOR so it works on windows and on linux/mac.

and also for every input file I do the same:
`$inputFiles[] = str_replace(['/','\\'],DIRECTORY_SEPARATOR, ( $bundles[$name]->basePath . DIRECTORY_SEPARATOR . $file ));`

2>
after this changes I get an error from the compiler.jar --js, and found that there are errors with this compiler (see "http://stackoverflow.com/questions/17482405/symfony2-asseticdump-filenotfoundexception" so use older version as in link is aswered "Just use 2.4.7 : https://github.com/yui/yuicompressor/downloads (the .jar is on the "build" folder).", and it is fixed.

3>
after that I get problems with css, relative paths in my config file "Yii::setAlias('@webroot', DIR . '/../../web');" this give problems in css. Paths are being combined, and so I end up with string like 'drive:/path/basic/assets/compress/../../web'.

in the assetcontroller I add a new function:
```
protected function deleteRelativePathParts( $FilePath, $dirSep = '/' ) { 
        if (!(strpos( $FilePath, $dirSep.'..'.$dirSep )>0)) {
            return $FilePath; //nothing todo skip function
        }
        $FilePathParts = explode($dirSep, $FilePath);
        $FilePathPartsCount = count($FilePathParts);
        $dirBackCount=0;
        for ( $i=$FilePathPartsCount-1; $i>0; $i-- ) {
          if ( $FilePathParts[$i] === ".." ) {
            $dirBackCount++;
          } else {
              if ( $dirBackCount > 0 ) { //prev found ../../...
                for ( $t=0; $t<$dirBackCount; $t++ ) {
                    unset($FilePathParts[$i+$t+1]);
                    unset($FilePathParts[$i-$t]);
                    $FilePathPartsCount -= 2;
                }
                $i -= ($dirBackCount*2);
                $dirBackCount=0;
              } 
            }
        }
        return implode($dirSep, $FilePathParts);    //make new path
    }
```
and in build target I add a line :
```
$tempFile = $this->deleteRelativePathParts( $tempFile, DIRECTORY_SEPARATOR );
before:
        if ($type === 'js') {
            $this->compressJsFiles($inputFiles, $tempFile);
        } else {
            $this->compressCssFiles($inputFiles, $tempFile);
        }
```
By me it's now working fine, I hope that I help someone to add this here.

**Comment by klimov-paul** [comment]
Relative path handling has been already fixed by 63e434b
