### ISSUE TITLE
Incorrect 'beforeCopy' callback in Assets guide section 

### ISSUE THREAD

**Issue by nirvana-msu** [yiisoft/yii2#6487]
Hi,

Assets guide has the following section to illustrate how 'beforeCopy' can be used to filter assets that are published:
```
class FontAwesomeAsset extends AssetBundle 
{
    public $sourcePath = '@bower/font-awesome'; 
    public $css = [ 
        'css/font-awesome.min.css', 
    ]; 
    
    public function init()
    {
        parent::init();
        $this->publishOptions['beforeCopy'] = function ($from, $to) {
            $dirname = basename(dirname($from));
            return $dirname === 'fonts' || $dirname === 'css';
        };
    }
}
```

However this callback code does not work. BaseFileHelper::copyDirectory would iterate through files/directories, and it will call the function with `$from = ...bower\font-awesome\css`. After applying `basename(dirname($from))`, `$dirname` would simply contain `font-awesome`, and `css` directory will not be published.

You could e.g. do the following instead (I guess you can come up with something simpler that that, though):
```
$path = str_replace(realpath(Yii::getAlias('@bower') . '\font-awesome'), '', $from);
return
    (0 === strpos($path, DIRECTORY_SEPARATOR.'fonts'))
    || (0 === strpos($path, DIRECTORY_SEPARATOR.'css'))
```

**Comment by spikyjt** [comment]
Please view https://github.com/yiisoft/yii2/issues/7307#issuecomment-75513119 for an alternative work around. However, neither of these solutions are complete. What if the file you only want to publish is 3 or more levels deep? Or using the method above, what if the complete path contains 'fonts' or 'css' somewhere else?

Ideally, `BaseFileHelper::copyDirectory()` would additionally traverse contents, if `$options['beforeCopy']` is set, even if `$options['beforeCopy']` returns false on the current directory.

**Comment by klimov-paul** [comment]
Duplicates #7307
