### ISSUE TITLE
Bootstrap Collapse widget is missinig possibility to swap panel-body with list-groups

### ISSUE THREAD

**Issue by skullcrasher** [yiisoft/yii2#6495]
As the title states, the collapse widget is missing the possibility to swap the content from "panel-body"  container to "list-groups", as in the official bootstrap documentation. http://getbootstrap.com/javascript/#collapse

**Comment by pana1990** [comment]
@cebe @skullcrasher check my PR https://github.com/yiisoft/yii2/pull/7153 please

**Comment by pana1990** [comment]
moved to https://github.com/yiisoft/yii2-bootstrap/issues/29
