### ISSUE TITLE
yii2/authclient redirect forever after click cancel when facebok asking permission

### ISSUE THREAD

**Issue by relaxpor** [yiisoft/yii2#6510]
i'm following the guideline here and it works like charm...
However, the stage of asking permission, if the user click "cancel"
the page caught in forever redirect loop to this url

"http://EXAMPLE.com/site/auth?authclient=facebook&error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied"

I've no idea what is the proper way to set cancelCallback or errorCallback since the tutorial doesn't provide this.

Please kindly advise or should it update tutorial or something?

Best Regards,

**Comment by klimov-paul** [comment]
Issue resolved by commit e0b206a
