### ISSUE TITLE
Typecasting in batchInsert

### ISSUE THREAD

**Issue by OmgDef** [yiisoft/yii2#6526]
I'm trying to insert data in the table

``` php
        Yii::$app->db->createCommand()->batchInsert(
            self::DB_CITY_TABLE_NAME,
            ['id', 'name', 'region_id', 'latitude', 'longitude'],
            $cities
        )->execute();
```

`$cities` is array 

``` php
array (size=1012)
  1 => 
    array (size=5)
      0 => string '1' (length=1)
      1 => string 'Хмельницкий' (length=22)
      2 => int 1
      3 => string '49.416668' (length=9)
      4 => string '27.000000' (length=9)
  2 => 
    array (size=5)
      0 => string '2' (length=1)
      1 => string 'Каменец-Подольский' (length=35)
      2 => int 1
      3 => string '48.683334' (length=9)
      4 => string '26.583332' (length=9)
  3 => 
    array (size=5)
      0 => string '3' (length=1)
      1 => string 'Нетишин' (length=14)
      2 => int 1
      3 => string '50.346695' (length=9)
      4 => string '26.633587' (length=9)
```

DB column type is `DOUBLE NOT NULL`
And error is:
![2014-12-15 14 10 28](https://cloud.githubusercontent.com/assets/6762337/5434584/59015a68-8464-11e4-8283-fd353f13b8af.png)

**Comment by nineinchnick** [comment]
Related to #5977

**Comment by klimov-paul** [comment]
`QueryBuilder::batchInsert()` does not use param binding.

**Comment by klimov-paul** [comment]
I believe this is a reason of this issue as well as #5977.
What was the reason of not using bound params for `batchInsert()`?

**Comment by cebe** [comment]
> What was the reason of not using bound params for batchInsert()?

looking at the code I asked myself the same question some days ago. I think it should use param binding.

**Comment by cebe** [comment]
first commit was https://github.com/yiisoft/yii2/commit/a39638515fe67fd27087a8a14f1266cf4c535e17 as far as I see, @qiangxue do you remember the reason for this implementation?

**Comment by qiangxue** [comment]
The main reason for not using parameter binding is because batch insert could potentially insert many rows of data. I'm not sure if PHP could support that many parameters (in the order of 1000+), and if so what is the performance impact. We should do some basic test to check it.

**Comment by Leammas** [comment]
I've tried to test it out. Perfomance affected badly.

Using microtime() to measure running time of actual execute() on batch inserting 10000 rows in `customer`.
Took ~0.40 sec in current implementation and over 70 sec with placeholding in batchInsert() in the way it done in usual insert().

**Comment by Leammas** [comment]
Sorry for the mess with references. Back to the original issue (not touching another escape problems). I've written the test and fix for the case. The other side of the fix is that all `float\double` on the way to db are `strings` now.
