### ISSUE TITLE
Add timestamp example to DateValidator

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#6530]
Within the Docs of the DateValidator it was mentioned that the class also validates timestamps. Because this common type of validation wasnt listed in the examples, it looked like it would work directly out of the box, but I did not.

Therefore I would suggest to add the example about validating timestamps:
* [['start_at','end_at'], 'date','format'=>'php:U'],

**Comment by cebe** [comment]
well, this is kind of wrong usage, the validator can already convert the value to a timestamp for you:

```
[['start_at'], 'date', 'format'=>$format, 'timestampAttribute' => 'start_at'],
[['end_at'], 'date', 'format'=>$format, 'timestampAttribute' => 'end_at'],
```

**Comment by cebe** [comment]
> it looked like it would work directly out of the box, but I did not.

@dynasource what exactly was the problem in your case? We have a unit test that verifies this: https://github.com/yiisoft/yii2/blob/a8c000ca9aff207ae06df2d6be814de9e1821c0f/tests/unit/framework/validators/DateValidatorTest.php#L88-89
