### ISSUE TITLE
ArrayHelper::getValues

### ISSUE THREAD

**Issue by aleksanderd** [yiisoft/yii2#6546]
Hi!

What about to add subj or modify getValue to accept arrays as key and def.value params?
It is useful to get sub-array for certain keys.

use example:

``` php
$params = ArrayHelper::getValues(Yii::$app->request->queryParams, ['p1', 'p2', ...], [
  'p1' => 'def4p1',
  'p2' => 'def4p2',
  ...
]);
```

thnx

**Comment by klimov-paul** [comment]
I can't see much sense of such addition. Its just wraps a simple `foreach`. besides what about default values for the retrieved data?

**Comment by cebe** [comment]
defaults are covered by the proposed implementation here: https://github.com/yiisoft/yii2/pull/6600/files#diff-c5ab028029554c59da3b92c6a49d8ac6R199 not sure if it is really needed though...

**Comment by dynasource** [comment]
this is too abstract and usecases are unclear. Closing this feature corresponding https://github.com/yiisoft/yii2/pull/6600#issuecomment-67735733
