### ISSUE TITLE
DateValidator return valid for date "2012-12-12foo"

### ISSUE THREAD

**Issue by pgrzelka** [yiisoft/yii2#6553]
There is an error in DateValidator using Intl extension.
When I provide wrong string having valid date validator should return "not valid".
Example value: 
2012-12-12foo is valid but it shouldn't

PHP: 5.5.9-1ubuntu4.5, ICU: 52.1

**Comment by massimilianomancini** [comment]
Don't know if related but I also have problem with ICU date format. In rules() I have:

`
['lBirthDate', 'date', 'format' => 'dd/mm/yyyy'],
`
that wrongly accepts dates in format dd/mm/yyy without any error (as far I can see the validator just try to calculate the timestamp, if it succedeed then the it returns true)

while using
`
['lBirthDate', 'date', 'format' => 'php:d/m/Y'],
`
the validator works correctly

Tested on windows 7, 64bit, php 5.6.5, yii 61fc0f0

**Comment by cebe** [comment]
@massimilianomancini can you give some example input that produces the problem?

**Comment by massimilianomancini** [comment]
`
<?= $form->field($model, 'lBirthDate', ['enableAjaxValidation' => true])->widget(DatePicker::classname(), ['options' => ['placeholder' => 'gg/mm/aaaa'],'pluginOptions' => ['autoclose'=>true]])?>
`

**Comment by massimilianomancini** [comment]
`use kartik\widgets\DatePicker;`

`<?= $form->field($model, 'lBirthDate', ['enableAjaxValidation' => true])->widget(DatePicker::classname(), ['options' => ['placeholder' => 'gg/mm/aaaa'],'pluginOptions' => ['autoclose'=>true]])?>`

**Comment by cebe** [comment]
I mean a date value that you enter in the text field.

**Comment by massimilianomancini** [comment]
I tried with different dates in short italian format dd/mm/yy for example 07/10/74 or 12/07/69
