### ISSUE TITLE
Possibility to omit container tag for BaseListView and derivative classes 

### ISSUE THREAD

**Issue by yujin1st** [yiisoft/yii2#6581]
Now there is a possibility to omit an item container class for yii\widgets\ListView by setting `[itemOptions['tag']=>false]` while running the widget.
But there is no ability to skip the wrapper of whole widget - it's always set to `div`, if undefined. 
I suggest a little improvement that allows to omit container tag by setting the `[options['tag']=>false]` like it's done with items of ListView.

**Comment by pana1990** [comment]
@samdark  @yujin1st  this issue is fix in #10764
