### ISSUE TITLE
Just for clarification in Testing environment setup.

### ISSUE THREAD

**Issue by nakarin4350** [yiisoft/yii2#6585]
I am a very newby and have a very hard time to setup testing environment.I think in https://github.com/yiisoft/yii2/tree/master/apps/basic/tests ,at the line  
"Build the test suites: codecept build".
The document should mention  "In the test directory execute the following: Build the test suites:
codecept build".I think this will make another newby like me can get start with the framework a lot easier.

**Comment by dynasource** [comment]
codeception scope.
