### ISSUE TITLE
FileValidator: array keys changed after validation in multiple files case

### ISSUE THREAD

**Issue by timmy78** [yiisoft/yii2#6588]
Hi

I make something like this in my form : 

```
...
<?= $form->field($model, 'file[custom1]')->dropDownList($items1) ?>
<?= $form->field($model, 'file[custom2]')->dropDownList($items2) ?>
...
```

After recuperating the UploadedFile instance and before validating the form, my _file_ attribute is like that : 

```
[
    'custom1' => yii\web\UploadedFile ...
    'custom2' => yii\web\UploadedFile ...
]
```

But, for some reason, after validating my model attribute, the keys of my _file_ attribute changed : 

```
[
    0 => yii\web\UploadedFile ...
    1 => yii\web\UploadedFile ...
]
```

I looked in FileValidator.php and the reason is at the [line 183](https://github.com/yiisoft/yii2/blob/master/framework/validators/FileValidator.php#L183) : 

```
public function validateAttribute($model, $attribute)
{
    ...
    $model->$attribute = array_values($files);
    ...
}
```

Is it normal ? How to pass through ?

Thanks

**Comment by qiangxue** [comment]
The assumption of validating multiple files is that the files are indexed by integers. In your case, you should validate each individual file upload separately.

**Comment by timmy78** [comment]
I don't understand what is wrong with custom indexes.
And if I use integer indexes like you say, the problem is still here

```
...
<?= $form->field($model, 'file[5]')->dropDownList($items1) ?>
<?= $form->field($model, 'file[9]')->dropDownList($items2) ?>
...
```
Will become after validation : 
```
[
    0 => yii\web\UploadedFile ...
    1 => yii\web\UploadedFile ...
]
```
I don't want attributes _file_custom1_ and _file_custom2_, I need an array.

**Comment by vtvz** [comment]
@timmy78, totally agree with you. Its... Vary annoying. Why should it be like this?
As an option, you can save state before validation and restore it thereafter

**Comment by dynasource** [comment]
This behavior is questionable indeed. I checked the current tests (FileValidatorTest) and these do not cover this particular part of the code https://github.com/yiisoft/yii2/blob/master/framework/validators/FileValidator.php#L200
