### ISSUE TITLE
Strange behavior of $magicFile parameter in FileHelper::getMimeType()

### ISSUE THREAD

**Issue by SeynovAM** [yiisoft/yii2#6591]
Logic of $magicFile in FileHelper::getMimeType() destroys my brain :)
Source of this method:

``` php
public static function getMimeType($file, $magicFile = null, $checkExtension = true)
{
    if ($magicFile !== null) {
        $magicFile = Yii::getAlias($magicFile);
    }
    if (!extension_loaded('fileinfo')) {
        if ($checkExtension) {
            return static::getMimeTypeByExtension($file, $magicFile);
        } else {
            throw new InvalidConfigException('The fileinfo PHP extension is not installed.');
        }
    }
    $info = finfo_open(FILEINFO_MIME_TYPE, $magicFile);
    if ($info) {
        $result = finfo_file($info, $file);
        finfo_close($info);
        if ($result !== false) {
            return $result;
        }
    }
    return $checkExtension ? static::getMimeTypeByExtension($file, $magicFile) : null;
}
```

In one case $magicFile is a path to finfo magic file `finfo_open(FILEINFO_MIME_TYPE, $magicFile);`, but if finfo_file returns false, than $magicFile willl be used as path to php file that returns mime types array `static::getMimeTypeByExtension($file, $magicFile)`.

May be another $finfoMagicFile parameter must to be here. Something like this:
`public static function getMimeType($file, $magicFile = null, $checkExtension = true, $finfoMagicFile = null)`
And, may be, public static property $finfoMagicFile must to be. It will be used as default when param $findoMagicFile === null.

**Comment by dynasource** [comment]
this looks quite logical to me
