### ISSUE TITLE
basic app acceptance tests against PhantomJS all return a blank page

### ISSUE THREAD

**Issue by ThePeach** [yiisoft/yii2#6610]
I'm a bit torn whether this should be reported upstream, so I'll start from here and we'll see.

I've got all the default acceptance tests working without problems using Selenium WebDriver.

I've seen PhantomJS being recommended by CodeCeption's @DavertMik and I wanted to give it a shot: I've got version 1.9.8 installed right now, but all the tests fail immediately:

```
../vendor/bin/codecept run acceptance AboutCept.php
Codeception PHP Testing Framework v2.0.9
Powered by PHPUnit 4.6-g827d10a by Sebastian Bergmann and contributors.

Acceptance Tests (1) ----------------------------------------------------------------------------------------------------------------
Trying to ensure that about works (AboutCept)                                                                                   Fail
-------------------------------------------------------------------------------------------------------------------------------------


Time: 3.26 seconds, Memory: 10.75Mb

There was 1 failure:

---------
1) Failed to ensure that about works in AboutCept (/mnt/workspace/test/yii2composer/basic-dev/tests/codeception/acceptance/AboutCept.php)
Couldn't see "About","h1":
Element located either by name, CSS or XPath 'h1' was not found on page.

Scenario Steps:
2. I see "About","h1"
1. I am on page "/index-test.php/about"


FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

and the screenshot saved in the `_optput` folder are empty and the markup contains only the following:

```html
<html><head></head><body></body></html>
```

The configuration I've got is the following:
```jaml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
    config:
        WebDriver:
            host: 192.168.56.1
            url: 'http://basic-dev.yii2.sandbox'
            browser: phantomjs
            restart: true
            window_size: 1024x768
```

which worked without issues with Selenium WebDriver.

Any idea why this isn't working as expected?

**Comment by cebe** [comment]
is this issue still existing for you?

**Comment by shssoichiro** [comment]
Not sure about OP, but I ran into this issue as well. It's most likely a Codeception bug--I'm testing a Laravel app and found this issue page trying to find a solution.

**Comment by cebe** [comment]
thanks for the info. please report this issue to Codeception then. You may link here for reference when doing so. Thanks!
