### ISSUE TITLE
Count queries should not issue order clause from a relationship

### ISSUE THREAD

**Issue by chris68** [yiisoft/yii2#6611]
At least in postgres you are not allowed to execute such an statement (raises 42803, while MYSQL seems to allow it).

```
SELECT COUNT(*) FROM "tbl_users"  LEFT JOIN .... ORDER BY "tbl_users"."id";
```

Such an statement is automatically generated by Yii whenever one uses some kind of ordering in a one to many relationship.

```
    public function getUsers()
    {
        return $this->hasMany(Users::className(), ['user_id' => 'id'])->orderBy('tbl_users.id');
    }
```

Therefore, order clauses should not be issued when count is used!

**Comment by qiangxue** [comment]
What's your PHP code that will trigger this problem?

**Comment by chris68** [comment]
Sorry for the late response - was in vacation....

The code is based on a standard model with crud generated using gii based on the standard application template. It is as follows, the two vital thinks marked with ``// Here: ...``

```
/**
 * This is the model class for table "{{%emailentity}}".
 *
 * @property integer $id
 * @property integer $owner_id
 *
 * @property Emailmapping[] $emailmappings
 */
class Emailentity extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function find()
    {
        return new EmailentityQuery(get_called_class());
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmailmappings()
    {
        // Here: This orderBy will create the problem!
        return $this->hasMany(Emailmapping::className(), ['emailentity_id' => 'id'])->orderBy('{{%emailmapping}}.emailarea_id');
    }
}


/**
 * This is the model class for table "{{%emailmapping}}".
 *
 * @property integer $id
 * @property integer $emailentity_id
 * @property integer $emailarea_id
 *
 * @property Emailentity $emailentity
 */
class Emailmapping extends \yii\db\ActiveRecord {
}

/**
 * EmailentityController implements the CRUD actions for Emailentity model.
 */
class EmailentityController extends Controller
{
    public function actionTest()
    {

        $searchModel = Emailentity::find();
        $dataProvider = new \yii\data\ActiveDataProvider([
            // Here; This joinWith then creates the problem!!
            'query' => Emailentity::find()->joinWith('emailmappings')->andWhere("{{%emailentity}}.owner_id = :owner", [':owner' => \Yii::$app->user->id]),
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}
```

Works fine without the ``joinWith``. With the ``joinWith`` the resulting sql error is

```
Database Exception – yii\db\Exception
SQLSTATE[42803]: Grouping error: 7 ERROR: column "tbl_emailmapping.emailarea_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...d" WHERE "tbl_emailentity".owner_id = $1 ORDER BY "tbl_email...
^
The SQL being executed was: SELECT COUNT(*) FROM "tbl_emailentity" LEFT JOIN "tbl_emailmapping" ON "tbl_emailentity"."id" = "tbl_emailmapping"."emailentity_id" WHERE "tbl_emailentity".owner_id = 102 ORDER BY "tbl_emailmapping".emailarea_id

Error Info: Array
(
    [0] => 42803
    [1] => 7
    [2] => ERROR:  column "tbl_emailmapping.emailarea_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...d" WHERE "tbl_emailentity".owner_id = $1 ORDER BY "tbl_email...
                                                             ^
)

↵
Caused by: PDOException
SQLSTATE[42803]: Grouping error: 7 ERROR: column "tbl_emailmapping.emailarea_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...d" WHERE "tbl_emailentity".owner_id = $1 ORDER BY "tbl_email...
^
```

Seems like somewhere in building up the count sql the order by statement is included again at a very late stage. Because as already commented above an order by added early (like e.g. using the sorter in the grid) will be handled correctly. Only when the orderby is coming out of the join things crash...

**Comment by robregonm** [comment]
IMHO, A way to fix it could be to loop through the included `with` relations and get rid of `orderBy` items before `count()`

**Comment by klimov-paul** [comment]
I can't see a good way to solve this.
The problem appears because `joinWith` is processed by `ActiveQuery::prepare()`, which is called by `QueryBuilder::build()`. This means `joinWith` is processed just when you call `all()`, `one()` or `count()` and it overrides order specified at `Query` itself.

> a way to fix it could be to loop through the included with relations and get rid of orderBy items before count()

The problem is 'ORDER BY' clause is not forbidden for the 'COUNT()'. It actually may be necessary to have a proper 'ORDER BY' for the fetching the correct agregation result sometimes. This means we can not just strip it off automatically.

The walk around for this issue could be:

1) declare separate relation without `order`:
```php
class Emailentity extends \yii\db\ActiveRecord
{
    public function getEmailmappingsPure()
    {
        return $this->hasMany(Emailmapping::className(), ['emailentity_id' => 'id']);
    }

    public function getEmailmappings()
    {
        return $this->getEmailmappingsPure()->orderBy('{{%emailmapping}}.emailarea_id');
    }
}
```

2) Calculate `totalItemCount` for the data provider manually by separated query.

**Comment by spikyjt** [comment]
There is a further angle to this. The way `ActiveDataProvider` handles the count, by removing the order clause, breaks if you need to bind parameters to the order clause. This is an edge case I know, but it is valid. e.g.:

```php
$query->orderBy( [ '(title LIKE :o1)' => SORT_DESC ] )->params( [ ':o1' => '%' . $term . '%' ] );
```

which works fine by itself, but breaks `prepareTotalCount` because there are extra parameters bound to the query.

Isn't the original problem fixed by the fact that `queryScalar()` now uses a sub query?
https://github.com/yiisoft/yii2/blob/master/framework/db/Query.php#L388
Should this line also check if `orderBy` is empty?

Modifying `ActiveDataProvider::prepareTotalCount()` to remove `->orderBy([])` works for me, so presumably `count()` will also work with postgres.

**Comment by chris68** [comment]
@klimov-paul 

I agree that you need the order by for all() and one(). But I disagree for count. 

A query like this ``select count(*) from tbl_userlog order by id`` is nonsense. Hard to believe that only postgres is giving you an error here...

**Comment by chris68** [comment]
I could assume my problem is solved by #12772. I will test it as soon as the new release is out...

**Comment by samdark** [comment]
@chris68 thanks for keeping track of it. Validation of the fact will save us time.

**Comment by dynasource** [comment]
@chris68, are you ready to give us an update?

**Comment by chris68** [comment]
@dynasource 

It tested it. The new trick seem to wrap it into a subselect is nice. Works smoothly. Here a sample sql generated which caused errors before. 

SELECT COUNT(*) FROM (SELECT "tbl_emailentity".* FROM "tbl_emailentity" LEFT JOIN "tbl_emailmapping" ON "tbl_emailentity"."id" = "tbl_emailmapping"."emailentity_id" WHERE ("emaildomain_id"=101) AND ("tbl_emailentity".owner_id = 102) AND ("tbl_emailmapping".emailarea_id < 255) ORDER BY "tbl_emailmapping"."emailarea_id") "c"

Thanks for fixing it. Continue your great work. I close the issue.
