### ISSUE TITLE
Bootstrap Collapse widget ignores parent option passed to clientOptions

### ISSUE THREAD

**Issue by nterms** [yiisoft/yii2#6614]
According to the Bootstrap docs [here](http://getbootstrap.com/javascript/#collapse) the `parent` option is used to determine whether to hide others when some panel is opened. However, setting this with `clientOptions` would not give the expected behavior, because of the line 133 on widget.

```php
'data-parent' => '#' . $this->options['id']
```

This is important specially if you want to stop panels collapsing when you expand others. Simply when you want to keep two or more panels opened.

**Comment by fabioaccetta** [comment]
I too need panels not automatically collapsed when others are expanded.
