### ISSUE TITLE
Row options for empty GridView

### ISSUE THREAD

**Issue by x25** [yiisoft/yii2#6635]
At the moment, there is no way to change the options of the TR tag in GridView with no rows. Perhaps there should be used "GridView::rowOptions" or something like "GridView::emptyRowOptions":

https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L437

**Comment by adamasantares** [comment]
How about method $this->renderEmptyRow() ?
See https://github.com/adamasantares/yii2/blob/master/framework/grid/GridView.php#L435

**Comment by klimov-paul** [comment]
You can use `emptyTextOptions` for this:
```php
`emptyTextOptions` => ['tag' => 'span'],
```

**Comment by adamasantares** [comment]
ok
