### ISSUE TITLE
Confirm dialog on submit button is fired twice

### ISSUE THREAD

**Issue by viilveer** [yiisoft/yii2#6642]
I created a submit button using following markup:
```
Html::submitButton(
   Yii::t('admin-game', 'Delete'), 
   [
      'class' => 'btn',
      'data-confirm' => Yii::t('yii', 'Are you sure you want to delete selected items?'),
   ]
),
 ```

Now yii.js fires when I click the button and handleAction triggers the form submit again. If this is triggered the confirm popup will be also triggered.

yii.js line 173
```
$form.trigger('submit');
```

**Comment by pana1990** [comment]
Hi,

I am trying to create a hidden input before submitting the form, i not think it's the best solution but it fix issue.

i replace : 

```javascript
if ($button.length) {
     $button.click();
} else {
// no submit button in the form
     $form.submit();
}
```

with : 

```javascript
if ($button.length) {
    $('<input>').attr({
          type: 'hidden',
          name: $button.prop('name'),
          value: $button.prop('value')
     }).appendTo($form);
}

$form.submit();
```

@qiangxue  think about it.

**Comment by pana1990** [comment]
Hi,

I am trying to create a hidden input before submitting the form, i not think it's the best solution but it fix issue.

i replace : 

```javascript
if ($button.length) {
     $button.click();
} else {
// no submit button in the form
     $form.submit();
}
```

with : 

```javascript
if ($button.length) {
    $('<input>').attr({
          type: 'hidden',
          name: $button.prop('name'),
          value: $button.prop('value')
     }).appendTo($form);
}

$form.submit();
```

@qiangxue  think about it.

**Comment by pana1990** [comment]
Hi,

I'm trying to add a hidden input before submitting the form, i do not think that is the best solution but i think it fix issue.

Replace 
```javascript
if ($button.length) {
                    $button.click();
                } else {
                    // no submit button in the form
                    $form.submit();
                }
```

with
```javascript
 if ($button.length && $button.prop('name')) {
        $('<input>').attr({
                type: 'hidden',
                name: $button.prop('name'),
                value: $button.prop('value')
         }).appendTo($form);
}

$form.submit();
```

@qiangxue think about it.

**Comment by cicsolutions** [comment]
I side-stepped this issue by using CSS positioning.  I placed the delete button just outside the active form widget, but still in side the form container div.  Then I set the form container div to have positioning relative and the delete button to be positioned absolute to the bottom right of the form container div.  This approach may not work for everyone, depending on their page structure and layout, but it was a quick solution that worked for my needs.

**Comment by Faryshta** [comment]
I think its much easier than that http://api.jquery.com/unbind/ the first
click unbinds the click event and no need to do anything else

2015-01-19 17:52 GMT-06:00 Caleb Crosby <notifications@github.com>:

**Comment by Faryshta** [comment]
Correction, unbind is deprecated, the correct functionality is
http://api.jquery.com/off/ since 1.7

2015-01-19 18:18 GMT-06:00 Faryshta <angeldelcaos@gmail.com>:

**Comment by Faryshta** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L301
the line that attach the events is here. i tried everything i could think
of to dettach an event on my yii2 instalation to no avail.

sorry

2015-01-19 19:29 GMT-06:00 Faryshta <angeldelcaos@gmail.com>:

**Comment by pana1990** [comment]
@Faryshta try this : 

Replace in https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L498
```js
if ($button.length) {
    $button.click();
} else {
    // no submit button in the form
    $form.submit();
}
```
with
```js
if ($button.length && $button.prop('name')) {
    $('<input>').attr({
        type: 'hidden',
        name: $button.prop('name'),
        value: $button.prop('value')
     }).appendTo($form);
}

$form.submit();
```

**Comment by jonvargas** [comment]
Facing the same issue here, just subscribed to this thread to track the resolution efforts.

**Comment by matias-yii** [comment]
@pana1990 Your code works!!! Thanks!!!

**Comment by pana1990** [comment]
@matias-yii  This is a small patch , developers should seek a more elegant solution, any idea?

**Comment by xskif** [comment]
Facing the same issue in the GridView delete link.

**Comment by pana1990** [comment]
https://github.com/yiisoft/yii2/issues/7231

**Comment by francisberesford** [comment]
I think pana1990's solution is good, it also solves a problem where the name attribute of the button does not get submitted when clicked using the current code.

My question is there any important reason the current code is attempting to do ```js $button.click(); ``` rather than just ```js $form.submit() ```?  I believe any javascript click() events would require ```js $button.trigger('click');``` to trigger any javascript click events attached to the button, so that can't be the reason can it?

**Comment by francisberesford** [comment]
I think pana1990's solution is good, it also solves another problem where the name attribute of the button does not get submitted when clicked using the current code.

My question is there any important reason the current code is attempting to do ```js $button.click(); ``` rather than just ```js $form.submit() ```?  I believe any javascript click() events would require ```js $button.trigger('click');``` to trigger any javascript click events attached to the button, so that can't be the reason can it?

**Comment by pana1990** [comment]
@francisberesford it will make sure the value of the button input is submitted together with the form.

**Comment by francisberesford** [comment]
@pana1990 If that's what it's supposed to do it doesn't work. At least in Firefox or Chrome. Your code does work however.

**Comment by pana1990** [comment]
@francisberesford it work without data-cofirm option. I could trying send pull request with my solution but i think that it is not the best way.

**Comment by francisberesford** [comment]
I traced the problem with the name attribute not posting with data-confirm to yii.js line 157
```javascript
            if (method === undefined) {
                if (action && action != '#') {
                    window.location = action;
                } else if ($e.is(':submit') && $form.length) {
                    $form.trigger('submit');
                }
                return;
            }
```
it is using ``` $form.trigger('submit'); ``` and not a $button.click() in this case (maybe for good reason?)

You'll see that they use your technique in this file quite frequently e.g.

```javascript
$form.append('<input name="_method" value="' + method + '" type="hidden">');
```

I see no problem with your solution and it fixes two issues. I think you should do a pull request.

**Comment by pana1990** [comment]
@francisberesford  done!

https://github.com/yiisoft/yii2/pull/7872

**Comment by francisberesford** [comment]
@pana1990 {insert thumbs up emoticon}

**Comment by abassanini** [comment]
Hello
The same behavior using DetailView and/or GridView as mentioned by @xskif 
I tried @pana1990 solution, and worked in GridView, but it messed up DetailView.  Now the delete button does not delete the record, but nicely ask just once :)

I wish I could help more than just reporting
By the way, using kartik\grid\GridView and kartik\detail\DetailView

**Comment by francisberesford** [comment]
@abassanini I could not replicate this problem. I have put my GridView inside an ActiveForm and the delete link in yii\grid\ActionColumn does not fire twice. Also it still deletes the record with the old code and the new provided by @pana1990 

Could it be specific to the kartik extension?.

**Comment by xskif** [comment]
@abassanini, disable client validation on the tabular form solve the issue.

**Comment by abassanini** [comment]
Sorry for asking this, but enableClientValidation property is not in <a href="http://www.yiiframework.com/doc-2.0/yii-widgets-detailview.html">DetailView</a> nor <a href="http://demos.krajee.com/detail-view">Krajee DetailView</a>

Certainly, I'm in the wrong direction :|

**Comment by abassanini** [comment]
@francisberesford using DetalView from <a href="http://demos.krajee.com/detail-view">Krajee</a> not Kartik (sorry the misspelling)

view.php:
<code>
use kartik\detail\DetailView;

    echo DetailView::widget([
		'model' => $model,
		'attributes'=>$attributes,
        'hover'=>true,
        'mode'=>Yii::$app->request->get('edit')=='t' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
        'panel'=>[
        		'heading'=>$this->title,
        		'type'=>DetailView::TYPE_INFO,
        ],

    		'deleteOptions'=>[
        		'url'=>['delete', 'id' => $model->mac_address],
        		'data'=>[
        			'confirm'=>Yii::t('app', 'Confirm Deleting'),
        			'method'=>'post',
        		],
    		],
    ]);
</code>

**Comment by xskif** [comment]
@abassanini , try to explore request/response by browser debugger, it's may be internal error.
This issue about form button confirmation dialog, not just button with confirmation of action.

**Comment by jotapeserra** [comment]
I could revolve this by doing:

`
$confirmTxt = 'confirmation text';
echo Html::hiddenInput('afterSubmit');
echo Html::button('submit',
    [
	'class' => 'btn btn-warning',
	'onclick'=>"if(confirm('".$confirmTxt."')){
	     $('input[name=\"afterSubmit\"]').val(\"delete\");
	     $('form#toolbarProductosForm').submit();
	}",
   ]);
`

**Comment by dhimancontact** [comment]
I am still facing same issue with 2.0.6 version

**Comment by cebe** [comment]
@dhimancontact the latest version is 2.0.10, please try that one and also dev-master, to provide a useful report.

**Comment by yupe** [comment]
Have same issue on 2.0.10 gridview with delete buttons is inside the ActiveForm

**Comment by samdark** [comment]
@yupe please open a separate issue w/ details.

**Comment by cebe** [comment]
please open a new issue and describe what you are doing in more detail please.
