### ISSUE TITLE
Add saveAll feature in active record

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#6664]
I'm sorry to give some references from other framework

http://book.cakephp.org/2.0/en/models/saving-your-data.html#model-saveall-array-data-null-array-options-array

http://www.rijalasepnugroho.com/blogs/view/Membuat%20Form%20Master%20Detail%20dengan%20CakePHP

``` php
$this->SomeModel->saveAll($data, array(
    'fieldList' => array(
        'SomeModel' => array('field_1'),
        'AssociatedModel' => array('field_2', 'field_3')
    )
));
```

The saveAll function is just a wrapper around the saveMany and saveAssociated methods. it will inspect the data and determine what type of save it should perform. If data is formatted in a numerical indexed array, saveMany will be called, otherwise saveAssociated is used.

**Comment by mootensai** [comment]
https://github.com/mootensai/yii2-relation-trait

**Comment by dynasource** [comment]
this is covered mostly by updateAll(). With respect to saving links, this is already covered with #3224 and #1990
