### ISSUE TITLE
MongoDB Extension, not currect sample for findAndModify 

### ISSUE THREAD

**Issue by Lynnworld** [yiisoft/yii2#6665]
In "Yii 2.0.1 release doc" there is :
<code>
User::find()->where(['status' => 'new'])->modify(['status' => 'processing']);
</code>

Actually it should use $set, or you will miss all columns except status.
<code>
User::find()->where(['status' => 'new'])->modify(['$set'=>['status' => 'processing']]);
</code>

**Comment by klimov-paul** [comment]
I can not find any explicit example of `Query::modify()` usage at the docs. Where exactly you have found these?

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/extensions/mongodb/ActiveQuery.php#L172

**Comment by klimov-paul** [comment]
I know such method exist. But there is no docs of its usage, which you complain on,

**Comment by Lynnworld** [comment]
http://www.yiiframework.com/news/82/yii-2-0-1-is-released/

**Comment by klimov-paul** [comment]
Can you answer the question where you get this:
> In "Yii 2.0.1 release doc" there is :
User::find()->where(['status' => 'new'])->modify(['status' => 'processing']);

**Comment by klimov-paul** [comment]
This is not a docs, this is just the news article.

**Comment by cebe** [comment]
@klimov-paul I think we should adjust the news anyway, what would be the correct syntax for it?

**Comment by klimov-paul** [comment]
Instead of
```php
User::find()->where(['status' => 'new'])->modify(['status' => 'processing']);
```
Should be
```php
User::find()->where(['status' => 'new'])->modify(['$set'=>['status' => 'processing']]);
```

Note: I have no access to the yiiframework.com, so I am unable to adjust anything there.

**Comment by cebe** [comment]
@klimov-paul updated the news. If you want to have access, just ask @qiangxue to grant it.
