### ISSUE TITLE
NavBar class not easily extendable due to html in the init function

### ISSUE THREAD

**Issue by kanyuga** [yiisoft/yii2#6689]
The init function of the `\yii\bootstrap\NavBar` class has several lines of code that output html. Since every widget class should contain a call to `parent::init()`, this class cannot be easily extended since the html in the init function will also sent to the output. I encountered this problem while trying to extend the NavBar class to remove the `div` that wraps the individual menus.

A proposed solution is to move the bulk of the code in the init function into a separate function.

**Comment by dynasource** [comment]
see https://github.com/yiisoft/yii2/issues/11915

**Comment by samdark** [comment]
So it seems it's fixed in 2.1, right?

**Comment by dynasource** [comment]
seems not, see https://github.com/yiisoft/yii2-bootstrap/blob/2.1/NavBar.php and the comment of @cebe https://github.com/yiisoft/yii2/issues/11915#issuecomment-231377682
