### ISSUE TITLE
yii\helpers\Url enhance.

### ISSUE THREAD

**Issue by callmez** [yiisoft/yii2#6697]
```php
// /index?r=site/index
echo Url::to(['site/index']);

// /index?r=site/index&src=ref1#name
echo Url::to(['site/index', 'src' => 'ref1', '#' => 'name']);

// the currently requested URL
echo Url::to();

// /images/logo.gif
echo Url::to('@web/images/logo.gif');

// images/logo.gif
echo Url::to('images/logo.gif');

// http://www.example.com/images/logo.gif
echo Url::to('@web/images/logo.gif', true);

// https://www.example.com/images/logo.gif
echo Url::to('@web/images/logo.gif', 'https');
```
The current `Url` support the above url style. 
some times I got new issue like.
```php
// add c parameter
// /index?r=site/index&src=ref1&a=b
echo Url::to(['c' => 'd']);
// get: /index?r=site/index&src=ref1&a=b&c=d

// just remove c parameter
// /index?r=site/index&src=ref1&a=b&c=d
echo Url::to(['c' => null]);
// get: /index?r=site/index&src=ref1&a=b
```
  Can possible to implement it?

**Comment by qiangxue** [comment]
If we want to support this, it's better to be done in a new method instead of further complicating the usage of `to()` and `toRoute()`.

**Comment by samdark** [comment]
I disagree:

1. I can't come up with any good name for new method.
2. Logically it's the same.

**Comment by creocoder** [comment]
Agree with @samdark

**Comment by lynicidn** [comment]
route supported as `alias` if i want relate route to default action u must use:
```php
Yii::setAlias('@site_index', '/site/defaultAction');
Url::to(['@site_index']);
```

**Comment by qiangxue** [comment]
> I can't come up with any good name for new method.
> Logically it's the same.

It's not a good design because the proposed behavior is quite different from the existing one while such a difference relies on the variation of the input parameter values. You can't tell the difference at all by looking at the function signature.

A separate method such as `toCurrent(array $params = [], $scheme = false)` (or a better name) is more self-explanatory and concise. When a value in `$params` is `null`, it will "unset" the corresponding value in `$_GET` (note that this is another major reason why it's inappropriate to implement this in `toRoute()`).

**Comment by samdark** [comment]
We already have "current route" behavior when leaving route as empty.

**Comment by qiangxue** [comment]
> We already have "current route" behavior when leaving route as empty for both to and toRoute.

but here you are introducing yet another "current route" representation, and in this new representation `$params` is interpreted differently from the other one.

**Comment by samdark** [comment]
Yes, that's true. Probably `current` isn't a bad idea.

**Comment by qiangxue** [comment]
@samdark I made some changes. `current()` would work with the currently requested GET parameters, not just the bound action parameters.

**Comment by samdark** [comment]
OK. That's even better.

**Comment by makroxyz** [comment]
Just tried Url::current() but it doesn't work inside module. 
I need to add "/" to Url::current function 'cos of Url::normalizeRoute adds moduleid to route
```php
$currentParams[0] = "/" . Yii::$app->controller->getRoute();
```
