### ISSUE TITLE
href with <a> tag for modal toggle button

### ISSUE THREAD

**Issue by gwelr** [yiisoft/yii2#6713]
Ok This is a minor issue. 
Today I wrote the below code: 
````php
Modal::begin([
	'header' => 'modal header',
	'toggleButton' => [
           'tag' => 'a', 
           'label' => Yii::t('category', 'toggle text'), 
           'href'=>'#'
]]); 
````
The reason why there is a href tag is that otherwise, the mouse icon above the link is a vertical bar instead of being the usual mouse icon for link. To my surprise, when adding the href attribute to the toggle button, the 'data-target' attribute from the link became missing.... Removes the href from the toggleButton and the data-target is back. 

The reason for this is that if statement by the end of the initOption method of the Modal widget: 
````php
if (!isset($this->toggleButton['data-target']) && !isset($this->toggleButton['href'])) {
````
I don't get the reasons behind the second isset check. The link enclosed in the href is never fired anyway, so what's the deal? 

@SonicGD , I'm tagging you here because github is blaming you for that line of code. 

My workaround is to explicitely define an ID for the modal and then adding this id to both href and data-target (which is not necessary). 
````php
Modal::begin([
	'id' => 'fake_id',
	'header' => 'modal header',
	'toggleButton' => [
           'tag' => 'a', 
           'label' => Yii::t('category, 'toggle text'), 
           'href'=>'#lfake_id, 'data-target'=>'#lfake_id'
]]); 
?>

**Comment by cebe** [comment]
I'm not sure what the real problem here is but to solve the problem with the link mouse icon you can set a css rule for that to change the icon.

```css
a {
    cursor: pointer;
}
```

**Comment by gwelr** [comment]
@cebe Thanks for answering me. This is probably a very minorl issue here and workarounds exist (as you also pointed). The only thing is I don't get why there is a "  !isset($this->toggleButton['href'] " check in the code when data-target is not set (which will not be set most of the time). Although it has a really minor impact, I don't get why, is there any reason for it?

**Comment by fosales** [comment]
This is an accessibility issue. Some screen readers doesn't understand a link tag without "href" attribute. From this point of view, it's a major issue.

**Comment by cebe** [comment]
@fosales can you please report that to https://github.com/yiisoft/yii2-bootstrap ?

**Comment by fosales** [comment]
@cebe off course! I will do it. Thanks!!
