### ISSUE TITLE
urlManager problem with empty string url rule

### ISSUE THREAD

**Issue by Lexxtor** [yiisoft/yii2#6717]
In config I have:
```php
'defaultRoute' => '/front/view/index',
```
Default start page have gridView with sorting and pagination, whos links are like:
```php
/front/view/index?sort=date
/front/view/index?page=2
```
But I want them to be like:
```php
/?sort=date
/?page=2
```
So I try to add URL rules like:
```php
'' => '/front/view/index',
// OR
'/' => '/front/view/index',
```
But they does not work, links still starts with `/front/view/index`. I think this may be a bug.
Also, I found a tricky solution:
```php
'<s:$>' => '/front/view/index',
```
This make links as I wanted `/?page=2`, but it make excess "s" parameter, that is not good for clean coding.

**Comment by cebe** [comment]
Looks like a bug as it seems to be working for `'' => 'front/view/index',` but not for `'' => '/front/view/index',`.

**Comment by cebe** [comment]
Fixed, thanks for reporting!

**Comment by cebe** [comment]
> And what is the best way to disable /front/view/index, so that index Action can anly be accessed via / url, and accessing /front/view/index will output 404 error?

You can achive this by enabling strict parsing, then you need to define rules for all possible urls however.
