### ISSUE TITLE
bower packages named with first uppercase name produce composer error

### ISSUE THREAD

**Issue by uran1980** [yiisoft/yii2#6718]
I have an error when download bower package named with first uppercase style throu composer.

**How to reproduce**
in composer.json file:
```
...
"require": {
    ...
    "php": ">=5.4.0",
    "yiisoft/yii2": "*",
    ...
    "bower-asset/Noisy": "*"      <---- bower packages with uppercase name produce error
}
...
```
Composer Error:
![2015-01-01-15-30](https://cloud.githubusercontent.com/assets/1616795/5592237/1140861c-91cb-11e4-95f6-19f99893d530.png)

PS
I am try to add this package: https://github.com/DanielRapp/Noisy/blob/master/bower.json

Is this bug related to Yii2 bower asset or to composer-asset-plugin?

**Comment by cebe** [comment]
I think it is composer-asset-plugin, @francoispluchino can you please take a look?

@uran1980 are you using the latest version of composer and composer-asset-plugin?

**Comment by samdark** [comment]
https://github.com/francoispluchino/composer-asset-plugin/issues/70

**Comment by uran1980** [comment]
Thanks @samdark 

I am change composer.json file to this:
```
...
"require": {
    ...
    "php": ">=5.4.0",
    "yiisoft/yii2": "*",
    ...
    "bower-asset/noisy": "*"
}
"extra": {
    "asset-installer-paths": {
        "npm-asset-library": "vendor/npm",
        "bower-asset-library": "vendor/bower"
    },
    "asset-repositories": [{
        "name": "bower-asset/noisy",
        "type": "bower-vcs",
        "url": "https://github.com/DanielRapp/Noisy.git"
    }]
}
```
but nothing changes, error the same(
and yes @cebe I use latest versions composer and composer-asset-plugin

**Comment by samdark** [comment]
It's not fixed yet. See the issue I've linked to. Yii team can't do anything about it so we have to wait.

**Comment by uran1980** [comment]
ok thanks
