### ISSUE TITLE
Not expose params details in yii\web\Controller::bindActionParams if not in debug mode

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#6723]
When not in debug mode - not to expose detailed info for security reasons:

![qip shot - screen 465 02 01 15](https://cloud.githubusercontent.com/assets/2150916/5594136/945d55ec-924e-11e4-8974-82525a13447d.png)

```
Bad Request (#400)
Missing required parameters: secret
```

Now the attacker knows that the param he needs is `secret`.
Thow he may not succeed in bruteforcing it - but its better if he does not know what to bruteforce, IMO.

**Comment by qiangxue** [comment]
It is arguable that we should hide the actual error message. Imagine if this is the response of a RESTful API. It would be very desirable to see what is the actual cause of the problem.
So the current behavior worries you, I think you may customize the `error` view.

**Comment by SDKiller** [comment]
UPD

This is not `Controller` fault but caused by `\yii\web\ErrorAction`

```
        if ($exception instanceof UserException) {
            $message = $exception->getMessage();
        } else {
            $message = $this->defaultMessage ?: Yii::t('yii', 'An internal server error occurred.');
        }
```

As `BadRequestHttpException` is instance of `UserException` - complete error message is shown.

**Comment by qiangxue** [comment]
Yes, this is expected. As I said, more explicit message like `Missing required parameters: secret` is preferred in situations such as RESTful APIs where the API consumer may want to know better what he does wrong.
