### ISSUE TITLE
Render yii\bootstrap\ButtonDropdown without items as button only

### ISSUE THREAD

**Issue by Hommer101** [yiisoft/yii2#6725]
Suggestion; make the ButtonDropDown render as a normal button if supplied with an empty item list. That makes it easier to switch functionality with conditional item list. Without items in the list the dropdown is useless but is still rendered.

**Comment by samdark** [comment]
I don't think it's a good idea to mix different widgets like that. Better use `if` and pass data to different widgets. If needed, create your own wrapper.
