### ISSUE TITLE
yii\base\InvalidParamException problem

### ISSUE THREAD

**Issue by bcubrilo** [yiisoft/yii2#6726]
I have problem with my website.I am using yii 2 basic template, on my localhost everything works but on shared hosting i got following error :
Uncaught exception 'yii\base\InvalidParamException' with message 'The directory does not exist: C:\HostingSpaces\zerguttnalog\zergutt.com' in C:\HostingSpaces\zerguttnalog\zergutt.com\vendor\yiisoft\yii2\base\Module.php:224 Stack trace: #0 C:\HostingSpaces\zerguttnalog\zergutt.com\vendor\yiisoft\yii2\base\Application.php(358): yii\base\Module->setBasePath('C:\\HostingSpace...') #1 C:\HostingSpaces\zerguttnalog\zergutt.com\vendor\yiisoft\yii2\base\Application.php(223): yii\base\Application->setBasePath('C:\\HostingSpace...') #2 C:\HostingSpaces\zerguttnalog\zergutt.com\vendor\yiisoft\yii2\base\Application.php(202): yii\base\Application->preInit(Array) #3 C:\HostingSpaces\zerguttnalog\zergutt.com\wwwroot\index.php(12): yii\base\Application->__construct(Array) #4 {main} thrown in C:\HostingSpaces\zerguttnalog\zergutt.com\vendor\yiisoft\yii2\base\Module.php on line 224. What it could be?

**Comment by lynicidn** [comment]
check access for web server user. 
p.s. use forum for ask question
