### ISSUE TITLE
Design issues with yii2/framework/base/View.php

### ISSUE THREAD

**Issue by tahpot** [yiisoft/yii2#6730]
Hi,

I am wanting to build a View object that loads templates from a database, however this is proving very difficult. There appears to be an assumption in yii2/framework/base/View.php that templates are only ever going to be loaded by a file. It would be much better if there was a TemplateLoader class that could be implemented to load templates from other data stores. The way twig does this works well.

At the very least, I was hoping to override a "renderTemplate" method or similar. renderFile() is the closest, however that methods starts with code looking up templates and localisation information before invoking events and the renderers. I can hack around it, but it's pretty ugly.

Cheers.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/6252

**Comment by tahpot** [comment]
Thanks, I didn't see that.
