### ISSUE TITLE
ActiveField: Setting the `id` for an input field does not change the `id` for the validation js

### ISSUE THREAD

**Issue by kanyuga** [yiisoft/yii2#6734]
I had a situation where I was using an `ActiveForm` instance for a batch input form and needed to change the fields to use custom `ids`. The initial javascript generated per input was as follows:

```javascript
jQuery('#w0').yiiActiveForm([{
    "id": "vehicle-type_id",
    "name": "[]type_id",
    "container": ".field-vehicle-type_id",
    "input": "#vehicle-type_id",
    "validate": function(attribute, value, messages, deferred) {
        yii.validation.required(value, messages, {
            "message": "Type cannot be blank."
        });
        yii.validation.number(value, messages, {
            "pattern": /^\s*[+-]?\d+\s*$/,
            "message": "Type must be an integer.",
            "skipOnEmpty": 1
        });
    }
}, {
```
This resulted in all the `type_id` fields being validated together since the `id`s were the same.

On changing the code to include the id as follows:

```php
$form->field($model, '[]type_id')->dropdown($items, ['id' => 'mycustomid']);
```

the validation javascript was unchanged.

**Comment by kanyuga** [comment]
I solved the problem but I am not sure my solution is without side effects.

I narrowed down the problem to the following parts:

1) [`$inputID`](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L728) in `ActiveField::getClientOptions()`  is generated using `Html::getInputId()`. I solved this by creating a custom function `ActiveField::getInputId()` that checked whether a custom id had been set and then replacing all the calls to `Html::getInputId()` with this function.

```php
    protected function getInputId() {
        return (isset($this->inputOptions['id']) && $this->inputOptions['id']) 
                ? $this->inputOptions['id'] 
                : Html::getInputId($this->model, $this->attribute);
    }
```
2) The `inputOptions` have to be set manually. I tried to add this to the field function but had to include the default class `form-control` e.g.
```php
$form->field($model, 'type_id', ['inputOptions' => [
                'class' => 'form-control','id' => 'myCustomId'
        ])->dropdown($items, ['id' => 'mycustomid']);
```
I bypassed this by altering the `ActiveField::dropDownList()` to save the result of the merge of `ActiveField::inputOptions` and the `$options` passed into the function as `ActiveField::inputOptions`

```php
public function dropDownList($items, $options = [])
    {
        $this->inputOptions = array_merge($this->inputOptions, $options);
        $this->adjustLabelFor($this->inputOptions);
        $this->parts['{input}'] = Html::activeDropDownList($this->model, $this->attribute, $items, $this->inputOptions);

        return $this;
    }
```

3. `ActiveField::getClientOptions()` was being called before the merging of `ActiveField::inputOptions`. I therefore moved the following code from `ActiveField::begin()` to `ActiveField::end()`:

```php
if ($this->form->enableClientScript) {
            $clientOptions = $this->getClientOptions();
            if (!empty($clientOptions)) {
                $this->form->attributes[] = $clientOptions;
            }
        }
```

**Comment by cebe** [comment]
When you set an ID yourself, you have to configure the selectors property of the field accordingly: http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#$selectors-detail

**Comment by kanyuga** [comment]
@cebe I encountered another problem. When i use the following input
``` php
$form->field($model, '[]type_id', ['selectors' => 
    ['input' => '#mycustomid', 'container' => '.field-mycustomid']
])->dropdown($items, ['id' => 'mycustomid']);
```
the javascript produced is 

``` javascript
jQuery('#w0').yiiActiveForm([{
    "id": "vehicle-type_id",
    "name": "[]type_id",
    "container": ".field-vehicle-type_id",
    "input": "#mycustomid",
    "validate": function(attribute, value, messages, deferred) {
        yii.validation.required(value, messages, {
            "message": "Type cannot be blank."
        });
        yii.validation.number(value, messages, {
            "pattern": /^\s*[+-]?\d+\s*$/,
            "message": "Type must be an integer.",
            "skipOnEmpty": 1
        });
    }
}, {
```
The problem is to do with the `id` being obtained using `Html::getInputId()`. I replaced both instances where it is called with a function that checked for the existence of `selectors[input]` first and used this if found.

**Comment by kanyuga** [comment]
Sorry for the many commits, was having issues syncing my master.

**Comment by cebe** [comment]
looks like you forgot to send a pull request, did that for you: https://github.com/yiisoft/yii2/pull/6810 is this correct?

**Comment by kanyuga** [comment]
I was waiting for some confirmation before I sent it.

**Comment by cebe** [comment]
@kanyuga discussion and feedback about code is always done in the pull request so you have to send it directly ;)

**Comment by cebe** [comment]
@kanyuga can you answer the questions in https://github.com/yiisoft/yii2/pull/6810#issuecomment-69374407 ?

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/13fca3bc54e22e9e89f9b86eeedbfb87a248d750
