### ISSUE TITLE
Log in by cookie error 

### ISSUE THREAD

**Issue by kakalos12** [yiisoft/yii2#6742]
Hi all, 
I posted the error here. Do you have any solution for this ? 
http://www.yiiframework.com/forum/index.php/topic/60797-login-by-cookie-error-when-using-mongodb/page__gopid__270753#entry270753

Thanks,
Dong

**Comment by coldice4** [comment]
The reason for this error is that $id is an array when it comes from the cookie. You can fix this by overriding the LoginByCookie function and by adding this line
$id = $id['$id']
before the $id gets used. But I don't know why this only happens when MongoDB is used.

**Comment by klimov-paul** [comment]
You need to typecaset `\MongoId` object into a string at your `Identity::getId()`.
There is already note about `\MongoId` specifics:
https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/usage-mongoid.md

**Comment by zorobabel** [comment]
Hi guys.

@kakalos12, @coldice4 is right, the **id** value coming from the cookie is an array, not a single value! Something like this:

```php
array(3) {
  [0]=>
  array(1) {
    ["$id"]=>
    string(24) "568823f5900293c818000029"
  }
  [1]=>
  string(32) "6aeL770pSq5J8m-Q5oTJQoGZVHya1iUe"
  [2]=>
  int(2592000)
}
```
From **[here](https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L280)** to **[here](https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L292)** you can see the root of the problem.

I am having a headhache with and had to add the following piece of code after [line 292](https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L292):

```php
if (is_array($id)) {
    $id = $id[0];
}
```
"It works" but It seems I am not logged in:

![nir](https://cloud.githubusercontent.com/assets/12666007/12076506/370b5a7c-b17b-11e5-8a8e-81f793c937c4.png)

@samdark, @klimov-paul any idea? Can you fix it? Thanks.

**Comment by zorobabel** [comment]
I've changed the actionLogin() on SiteController:

```php
        ...
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            // return $this->goBack();
            return $this->render('login', [
                'model' => $model,**
            ]);
        } else {
        ...
```
I dunno why commentig $this->goBack() makes It "works":

![cxv](https://cloud.githubusercontent.com/assets/12666007/12082160/bd3b2f88-b25b-11e5-90ef-39d37e97e7fd.png)

But after clicking on Contact, for example, kaput session!

![jbq](https://cloud.githubusercontent.com/assets/12666007/12082169/f7735e64-b25b-11e5-9381-be372fb5c656.png)

Please, I need help on this. I lost a lot of time trying to debug it.

**Comment by df2** [comment]
@zorobabel shouldn't it be

```php
if (is_array($id)) {
    $id = $id[0]['$id'];
}
```

**Comment by zorobabel** [comment]
@df2 no, it should be (correcting the above code I posted):

```php
if (is_array($id)) {
    $id = $id['id'];
}
```

**Comment by zorobabel** [comment]
BTW, this is my environment:

Windows 8.1 64 bit
Apache 2.4.9 64 bit
MongoDB 3.2.0 64 bit
PHP 5.5.12 64 bit

**Comment by kidol** [comment]
Based on the array you posted this is not correct...

> it should be

Well did you verify `$id['id']` equals `string(24) "568823f5900293c818000029"` ??

**Comment by zorobabel** [comment]
@kidol, yes

**Comment by df2** [comment]
@zorobabel please share the result of this:

```php
if (is_array($id)) {
    var_dump($id);
    exit;
    //$id = $id['id'];
}
```

**Comment by zorobabel** [comment]
@kidol, I copied it above:

```php
  array(1) {
    ["$id"]=>
    string(24) "568823f5900293c818000029"
  }
```

**Comment by df2** [comment]
@zorobabel ok. Notice the dollar sign in the index. You need to use single quotes to get it:

```php
if (is_array($id)) {
    $id = $id['$id'];
}
```

**Comment by zorobabel** [comment]
@df2, oh! thanks, I see it

**Comment by df2** [comment]
@zorobabel you bet!

**Comment by zorobabel** [comment]
@df2 haha! :+1:

**Comment by zorobabel** [comment]
My "fix" does not work

**Comment by zorobabel** [comment]
Is the forum alive?

http://www.yiiframework.com/forum/index.php/topic/69154-yii2-advanced-template-login-with-yii2-mongodb-doesnt-work/

**Comment by samdark** [comment]
That forum branch isn't.

**Comment by zorobabel** [comment]
Ok, someone could move it to the right place?

I would like to see this issue in status resolved

Thx!

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/6742#issuecomment-91513690 ?

**Comment by zorobabel** [comment]
But I did it =D

**Comment by samdark** [comment]
When cookie is created User component uses `getId()` method of the identity to fetch the value that would be put into the cookie: https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L541

Having non-string in a cookie is a clear sign that you didn't override `getId()` of the identity to return scalar value.

**Comment by zorobabel** [comment]
Ok, I know it but the login with MongoDB is not working, is it hard to understand?

**Comment by samdark** [comment]
Have you properly overridden `getId()` of the identity? 

Without overriding `getId()` it's not expected to work. That's documented as @klimov-paul noted above when closing the issue.

**Comment by zorobabel** [comment]
Let me check it, I need to dust off my code, thanks

**Comment by samdark** [comment]
Made an improvement to docs: https://github.com/yiisoft/yii2-mongodb/commit/b1b718ad3d6bf1dae220c51f445bdfd2869fa2d0

**Comment by zorobabel** [comment]
@samdark Excellent!
