### ISSUE TITLE
File validation disabled when JavaScript  File Object is not defined?

### ISSUE THREAD

**Issue by hafeyang** [yiisoft/yii2#6745]
when I check yii.validation.js ,I found:

```
//...
    function getUploadedFiles(attribute, messages, options) {
        // Skip validation if File API is not available
        if (typeof File === "undefined") {
            return [];
        }
//..
```
according to  http://caniuse.com/#search=File  ,File API is not supported in IE6/7/8/9, that means yii\validators\FileValidator  is not suported in those browsers.

but in fact ,we can get input[type=file] value in old IE and we can validate file extension in browser.

is it a bug ? or won't support in future?

**Comment by samdark** [comment]
Without file API you can't get mime type and size so validation becomes incomplete. Compatibility with old IE could be improved but it's definitely not a priority. If you have time you can submit a pull request.

**Comment by qiangxue** [comment]
> Compatibility with old IE could be improved ...

What kind of improvement?

**Comment by hafeyang** [comment]
```
//in old IE
var localPath = $("#file").val();// like /var/www/a.txt
if(/.txt$/g.test(localPath)){
    // valid extension
}
```

**Comment by samdark** [comment]
@qiangxue well, it can validate file extension with old IEs. Currently it's relying on file API for it.

**Comment by SDKiller** [comment]
@hafeyang 

https://github.com/modernizr/modernizr/wiki/HTML5-Cross-Browser-Polyfills#file-api

**Comment by SilverFire** [comment]
[Microsoft recently announced](https://support.microsoft.com/en-us/gp/microsoft-internet-explorer) all Internet Explorer versions 10 and lower will no longer be supported beginning January 12th, 2016.

**Comment by hafeyang** [comment]
@SDKiller 
really great resources! Thx
