### ISSUE TITLE
How to catch an exception in SwiftMailer

### ISSUE THREAD

**Issue by nicib83** [yiisoft/yii2#6746]
when i try to produce a simple Swift Mailer exception i can't seem to catch it.

```
        try {
            $r = Yii::$app->mailer->compose('contact/html', ['contactForm' => array()])
                /*->setFrom('mail@from.com')
                ->setTo('to@mail.com')
                ->setSubject('Hi to')*/
                ->send();

            
        } catch (Exception $e) {

        }
```

here Swift_TransportException is thrown because parameters are commented out. Similar exceptions are thrown on server errors, i can't seem to catch them in yii2

**Comment by nicib83** [comment]
use Swift_SwiftException;

seems to do the trick

**Comment by sirinibin** [comment]
Use this:
 try {
            $r = Yii::$app->mailer->compose('contact/html', ['contactForm' => array()])
                /*->setFrom('mail@from.com')
                ->setTo('to@mail.com')
                ->setSubject('Hi to')*/
                ->send();


        } catch (\Exception $e) {

        }
