### ISSUE TITLE
reset password link not working

### ISSUE THREAD

**Issue by evercode1** [yiisoft/yii2#6748]
Did a fresh install of Yii 2 advanced application today.  The purpose of the install was to verify that the link generated by the request rest password is not returning a valid url.  This is what I got:

http://yiifresh.com/index.php?r=3Dsite%2Freset-password&amp;token==3Db4n2OQmr4mdhrDrGiqQs-i5u09_dpxmX_1420392550

Response in the broswer:

Not Found (#404)
Unable to resolve the request "3Dsite/reset-password".

I am testing this in development mode.  I did confirm that the password token is being set, so the process is breaking with the format of the url, from what I can tell.  Obviously there is no 3Dsite controller.  Also, 3D as the first two characters of the token does not match what's in the DB, however the rest of the token matches.

**Comment by cebe** [comment]
Looks like this is a problem with the plain text version of the HTML mail that is generated automatically and thus contains HTML encoded parts. Can you paste the source text of the email? You may grep the .eml file from the debug toolbar for this.

**Comment by evercode1** [comment]
Here is the content of the .eml file:

<script src="https://gist.github.com/evercode1/fc8fa6ce87dd39a45818.js"></script>

It looks like it is broken in both the plain text and html version.

**Comment by qiangxue** [comment]
Can you show the content of `passwordResetToken.php`?

**Comment by evercode1** [comment]
Sorry, I don't see a file by that name.  I do have requestPasswordResetToken.php in frontend/views/site:

https://gist.github.com/evercode1/2d86680f26c69d2af10e

This is from a fresh install today, not modified in any way.

**Comment by qiangxue** [comment]
It's `common/mail/passwordResetToken.php`. This is the template file for generating the mail.

**Comment by evercode1** [comment]
this what I have for passwordResetToken.php:

https://gist.github.com/evercode1/d6658b64423808cf85ff

**Comment by qiangxue** [comment]
Seems it's caused by MIME encoding which is expected to encode `=` into `%3D`. But in your pasted eml, they are encoded as `=3D`.

**Comment by evercode1** [comment]
When I changed the url manually in the browser, the rest of the process worked perfectly, so I think the encoding issue is the only issue.

**Comment by evercode1** [comment]
Small email providers may not support html email correctly, so it's probably vital to have a text version at minimum.

**Comment by qiangxue** [comment]
A bit strange: `Html::encode($resetLink)` shouldn't cause the problem described in this issue when it is converted into text.

**Comment by cebe** [comment]
@evercode1 we always have the text fallback the problem is that it is broken ;)
@qiangxue why not? if you encode an URL that contains `&` you will have `&amp;` instead and the URL is invalid when represented as plain text.

**Comment by qiangxue** [comment]
True, but the problem reported here is about `=3D`, which is strange.

**Comment by cebe** [comment]
This is the encoded URL:

It is encoded 2 times:
1. Html::encode()
2. MIME quoted-printable

```
http://yiifresh.com/index.php?r=3Dsite%2Freset-password&amp;token=
=3Db4n2OQmr4mdhrDrGiqQs-i5u09_dpxmX_1420392550
```

decoding the MIME will give us:

```
http://yiifresh.com/index.php?r=site%2Freset-password&amp;token=b4n2OQmr4mdhrDrGiqQs-i5u09_dpxmX_1420392550
```

What is left is the HTML encoding which we now need to revert too.

**Comment by qiangxue** [comment]
I see. I think we should provide a text version then.

**Comment by cebe** [comment]
> We could check if we can enhance the html->text converter or provide a text only template or both.

Made some improvements in this direction in  	05cc9ae

**Comment by evercode1** [comment]
I tested with a fresh install of the advanced template, yii 2.0.2.  The url still does not work.  Here is the url I got for the token:

http:=
//yii2start.com/index.php?r=3Dsite%2Freset-password&token=3DgiKTi2IsBvzAIJH=
TeHI6vNLA6d7eMBI9_1421266109

Once I strip out the #D and the extra = sign, the rest of the process works perfectly.

**Comment by cebe** [comment]
which email program are you using to read it?

**Comment by cebe** [comment]
> http:=
> //yii2start.com/index.php?r=3Dsite%2Freset-password&token=3DgiKTi2IsBvzAIJH=
> TeHI6vNLA6d7eMBI9_1421266109

This is obviously MIME encoded so it looks like your mail program does not decode it correctly.

**Comment by evercode1** [comment]
I was just checking the application mail folder under frontend/runtime.  That url is from the plain text section of the email, so my understanding was that it should not be encoded.

**Comment by cebe** [comment]
the plain text section of an E-Mail is mostly MIME encoded at least when the email has more than one part or an attachment you can be sure it is.
Here is the header that tells you about encoding: https://gist.github.com/evercode1/fc8fa6ce87dd39a45818#file-emfrmf-db-L13

**Comment by evercode1** [comment]
Ok, I'll assume it's working then, and let you know if I have a problem when I move into production, thanks.

**Comment by cebe** [comment]
you can open the .eml file with an email program like thunderbird to check how the email looks like.

**Comment by evercode1** [comment]
Thanks I'll check it out.
