### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by MohammadHeydari** [yiisoft/yii2#6749]
an under this warning header is this not : yii\web\Request::cookieValidationKey must be configured with a secret key.
what should i do ?

**Comment by MohammadHeydari** [comment]
i did it , i edit the request.php in line 130 and turned off validation cookie with make it false;
i mean this (( public $enableCookieValidation = false;))

**Comment by cebe** [comment]
you have to configure the request component in your application config like this: https://github.com/yiisoft/yii2/blob/master/apps/basic/config/web.php#L12

**Comment by MohammadHeydari** [comment]
thanks but mine is working and error is gone , you think shouldn't make CookieValidation to false ?

**Comment by MohammadHeydari** [comment]
all right then i'mgonna do it

**Comment by chegie** [comment]
ok, thanks
