### ISSUE TITLE
Yii2: How to set data to textfield from other models when updating? 

### ISSUE THREAD

**Issue by yzner12** [yiisoft/yii2#6751]
In gridview action column.. there's 3 action (view,update,delete) ,

when you click the UPDATE button.. it will go to update form and the textfield is filled with data from database..
my problem is.. i have other models in 1 form.. i want to set their data too in the added textfield when i click the update button... 

here are the 2 models,

evr_tbl:
(evr_id,username_service_order_no,years_in_service)

&&

evr_informants_tbl: 
(evr_id,name,position,phone_number)

any idea?
thanks!

**Comment by qiangxue** [comment]
Please use our forum to ask questions like this.

You should configure `buttons` to create buttons that contain additional parameters you need to pass.

**Comment by yzner12** [comment]
Ok sorry..
