### ISSUE TITLE
Enh: yii\caching\DbCache. Add auto create table.

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#6752]
https://github.com/sangkil/application/blob/master/app/components/SqliteCache.php#L45-L47

**Comment by qiangxue** [comment]
We do not plan to support this. This is better done via an offline script.

**Comment by mdmunir** [comment]
OK. If that so, its better add db migration for this like rbac migration.

**Comment by qiangxue** [comment]
Agree.
