### ISSUE TITLE
sourceLanguage can be changed only once?

### ISSUE THREAD

**Issue by gengshenghong** [yiisoft/yii2#6754]
I've read this article (for yii1.0 though):
http://www.yiiframework.com/wiki/243/how-to-translate-and-do-the-translations-the-easy-way/

and I know it is possible to define "sourceLanguage" as something invalid like "00" to make sure even English can be translated/replaced. I think this may be useful when there are a big paragraph to translate (example: license? terms of service?). So, I've tested as below:
app.php for en-US:
<?php

return [
  'hello' => 'This may be a long text...example, license? Terms of Service?',
];

app.php for zh-CN:
<?php

return [
  'hello' => '你好',
];

and in the View file:
// "Translate" 'hello' based on app.php in en-US, which is "This may be a long text...example, license? Terms of Service? "
Yii::$app->language='en-US';
Yii::$app->sourceLanguage='00'; // Note: make it a invalid language!
echo Yii::t('app', 'hello');

// Just display 'hello'
Yii::$app->language='en-US';
Yii::$app->sourceLanguage='en-US';
echo Yii::t('app', 'hello');

The result is:
This may be a long text...example, license? Terms of Service?This may be a long text...example, license? Terms of Service?

And if I exchange the above code, it will display 2 "hello", which means, the setting of sourceLanguage property seems to be have effect only for the first time, is this by design? or a bug? It is strange.

By the way, the language property can be set many times and take effect.

Thanks,
Shenghong

**Comment by qiangxue** [comment]
You can configure `MessageSource::forceTranslation` to be true in 2.0.

**Comment by gengshenghong** [comment]
@qiangxue Thank you for the information, this will be a workaround. But at least, I think this special rule need to be documented somewhere, from the above test, "source language" can only be set once.

I guess translateMessage() can also workaround my issue, and this is more similar to above code, which take effect for a local scope instead of global -> does not affect the other behaviour of Yii::t().

If I just need to force it to be translated for all messages, I can easily configure source language in web.php and it works for me. :)

Thanks,
Shenghong
