### ISSUE TITLE
AuthClient error id

### ISSUE THREAD

**Issue by nik4152** [yiisoft/yii2#6758]
Hi,
need help
the after install AuthClient for yii2
do not access users/registration

ERRiOR
=======
Invalid Configuration – yii\base\InvalidConfigException
Missing required parameter "id" when instantiating "yii\authclient\AuthAction".
=======

config file add
======
```php
'clients' => [
    'facebook' => [
        'class' => 'yii\authclient\clients\Facebook',
        'clientId' => 'secret',
        'clientSecret' => 'secret',
    ],
],
```

Controller add
========
```php
public function actions()
{
    return [
        'auth' => [
            'class' => 'yii\authclient\AuthAction',
            'successCallback' => [$this, 'successCallback'],
        ],
    ];
}
```

```php
public function actionRegistration()
{
    $model = new Shopuser();
    return $this->render('registration');
}
```

```php
public function successCallback($client)
{
    $attributes = $client->getUserAttributes();
    // user login or signup comes here
}
```

view file add
=========
```php
<?= yii\authclient\widgets\AuthChoice::widget([
'baseAuthUrl' => ['users/registrations']
]) ?>
```

Tell me what I not so made

Тhanks!

composer add
==========
```
"yiisoft/yii2-authclient": "2.0.*@dev"
```

**Comment by klimov-paul** [comment]
Unable to reproduce.
@nik4152, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by cebe** [comment]
please post the full stack trace of the error

**Comment by nik4152** [comment]
already working need to be removed config file
========
'authClientCollection' => [
			'class' => 'yii\authclient\Collection',
			'clients' => [
				'facebook' => [
					'class' => 'yii\authclient\clients\Facebook',
					'clientId' => 'xxxxxx',
					'clientSecret' => 'xxxxxx',
				],
			],
		],
==========
and through time back and it worked
glitch )
I do not know why but it works thanks

**Comment by Skit** [comment]
but i need solution. I dont see that it's work

**Comment by SilverFire** [comment]
@Skit what are you talking about? Можно по-русски

**Comment by Skit** [comment]
Не смог разобраться почему получаю исключение: Missing required parameter "id" when instantiating "yii\authclient\AuthAction". Всё как у ТС
Спасибо, за ответ.

**Comment by SilverFire** [comment]
Не смог воспроизвести. Есть есть способ воспроизвести на чистой установке - пожалуйста, поделитесь.

**Comment by Skit** [comment]
Спасибо за совет! Поставил на чистую, хотя была тоже, фактически чистая.
Оказалось, что я просто do insert in this section
```php
public function behaviors()
    {
        return [
```
и get error!  А нужно insert in action method
```php
    public function actions()
    {
        return [
```
So good works!

Спасибо!
