### ISSUE TITLE
How do I use select in with

### ISSUE THREAD

**Issue by stromknight** [yiisoft/yii2#6765]
If my code is such：
     $data = $row->joinWith( [ 'schedulingVenue' => function($query) {$query->select('venueName'); }]  )->asArray()->all();

    the $data is empty;

but if my code is such :
     $data = $row->joinWith( [ 'schedulingVenue' => function($query) {$query->select('venueName'); }]  )->asArray()->all();

I can  get the rows.

**Comment by a-komarev** [comment]
I'm sorry, but you provided 2 exactly same examples of code. Recheck it, please.

**Comment by mdmunir** [comment]
Use Yii forum for asking.
