### ISSUE TITLE
ContactForm from address to be predefined.

### ISSUE THREAD

**Issue by Venu85** [yiisoft/yii2#6766]
The default "from" email address in the "advanced/frontend/models/ContactForm.php" is user entered address. Though it is logically correct, I think we need to change it as in the PasswordResetRequestForm, and configuring ReplyTo address with the user entered address.
This is because, when we use some email services like AWS SES, we need to verify the from address upfront.

**Comment by cebe** [comment]
What is the change you propose? I did not really get the issue. In ContactForm there can be a not logged in user so he has to enter his email address. What kind of upfront verification do you need?

**Comment by samdark** [comment]
Closed since it's application specific.
