### ISSUE TITLE
Error when splitting columns in function yii\db\Query::addSelect()

### ISSUE THREAD

**Issue by konrin53** [yiisoft/yii2#6767]
$q = new Query();
...
$q->addSelect('TRUNCATE(avg(t5.rating)**,** 1) as rating'); -> TRUNCATE(avg(t5.rating), **\`1)\`** AS \`rating\`

Syntax error!

This is because inside the function addSelect is erroneous separation columns:

$columns = preg_split(**'/\s*,\s*/'**, trim($columns), -1, PREG_SPLIT_NO_EMPTY);

**Comment by klimov-paul** [comment]
You should use `yii\db\Expression` in this case.

**Comment by qiangxue** [comment]
Use array to list every column.
