### ISSUE TITLE
Css class "active" for bootstrap\Nav not works.

### ISSUE THREAD

**Issue by pasmanp** [yiisoft/yii2#6768]
Active item in the Nav widget is not highlighted. 

yii 2.0.1, basic app template improved

**Comment by cebe** [comment]
Unable to reproduce with a fresh install, please give more details about the problem and how you adjusted the code.

**Comment by pasmanp** [comment]
Hi.
After fresh install, add the code to the layouts/main.php (before breadcrumbs)

```php
<?php echo yii\bootstrap\Nav::widget([
    'items' => [
        ['label' => 'Index','url' => ['/site/index']],
        ['label' => 'About','url' => ['/site/about']],
    ],
]);
?>
```

To highlighting active item one ought to add nav-tabs or nav-pills class:

```php
<?php echo yii\bootstrap\Nav::widget([
    'items' => [
        ['label' => 'Index','url' => ['/site/index']],
        ['label' => 'About','url' => ['/site/about']],
    ],
    'options' => ['class' =>'nav-pills'],    
]);
?>
```

It is not a bug, but this example should be added to documentation, I think.

**Comment by cebe** [comment]
okay, got it, added a css class to the example according to http://getbootstrap.com/components/#nav

thanks!
