### ISSUE TITLE
How do I use select in  function with()

### ISSUE THREAD

**Issue by stromknight** [yiisoft/yii2#6772]
I'm sorry for the last question.

now, I have 2 model.

schedulingModel, schedulingVenueModel

                 `class schedulingModel extends Model {

                        public function getSchedulingVenue() {
                             return $this->hasMany(SchedulingVenueModel::className(), ['sid' => 'id']);
                        }
                 } 

The following is my data acquisition methods

         function getRow () {
           
                $model = new SchedulingModel;
                $row     = $model->find()->with( [ 'scheduling' => function($query) { $query->select();}  ])->asArray()-all();
          
           }
 but  the $row  is empty.
I  can't use $query->select(), i don't know why, please help me.  thanks!

**Comment by mdmunir** [comment]
Go to http://www.yiiframework.com/forum/ or https://www.facebook.com/groups/yiitalk/ for asking.
