### ISSUE TITLE
search the filter from gridview it's submit the whole page and page reload

### ISSUE THREAD

**Issue by ceovishnu** [yiisoft/yii2#6774]
I have one form and gridview within same form tag, but when i search from the gridview filter then it's post the whole form and page relaod.

Anyone has any idea about same.

**Comment by lynicidn** [comment]
ask question [here](http://yiiframework.com/forum)

**Comment by ceovishnu** [comment]
http://www.yiiframework.com/forum/index.php/topic/60873-post-the-form-when-search-the-filter-in-gridview/

**Comment by ceovishnu** [comment]
@lynicidn any update?
i have already post this issue in yii forum.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.gridView.js#L42

**Comment by ceovishnu** [comment]
hello @lynicidn ,
thanks for your suggestion

I have tried with "afterfilter" and "beforefilter" event but after this event form is summited with page reload.

It's not working.

if u have any other solution then update me.

**Comment by ceovishnu** [comment]
hello @lynicidn any update for same
