### ISSUE TITLE
Make clearer in docs how to group css files for compression

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#6777]
Following on from: https://github.com/yiisoft/yii2/issues/6775 whereby I found that my CSS combining was actually exceeding a limit for IE of 4095 selectors within my CSS I sought to figure out how to write to CSS files by a limit of 4095.

So I looked at the docs: http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#using-the-asset-command and even though it does talk about using targets to group it never actually explains how to group the `bundles` property into different, possibly, split files.

Can some examples and/or further explanation be added to the doc page?

**Comment by Sammaye** [comment]
Another good one to explain is different CSS/JS targets. i.e. following on I want all my CSS targets chunked (which I have been able to figure out) but I want all my JS to go to the same file.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/AssetController.php#L70

**Comment by klimov-paul** [comment]
Duplicates #6203
