### ISSUE TITLE
Namespace question

### ISSUE THREAD

**Issue by ujovlado** [yiisoft/yii2#6778]
Hi,

I know that namespaces are case-insensitive, but have simple question.

Why there's definition of namespace as `namespace yii` and then usage as `use Yii`?

Is it because of simpler `BaseYii` class recognition?

Thx.

**Comment by trntv** [comment]
`Yii` is a class name under global namespace, not the yii namespace itself.

**Comment by ujovlado** [comment]
@trntv oh, I didn't notice, thx. :+1:
