### ISSUE TITLE
Yii 2.0.1 installation through Compoer,  (github  2 Factor Authentication, never send SMS)

### ISSUE THREAD

**Issue by lawipac** [yiisoft/yii2#6784]
I tried to installed latest Yii through composer , as described in 
"http://www.yiiframework.com/download/"

when running: 
$  composer create-project yiisoft/yii2-app-basic basic 2.0.1

it asks input github username/password, and then asking for SMS code for 2factor authentication.

however, I never receive any sms, and thus the installation cannot proceed. 

the only workaround is I temporarily disabled 2FA from github.

Anyone have similar issues? (I can login github using 2FA using webbrowser without any problem)

PS: my  Composer version 1.0-dev (c58b7d917c65692eeb00c22b2fbaaa251cb390dc) 2015-01-05 16:31:16

**Comment by samdark** [comment]
That's not Yii issue but github's. Please report to them.
