### ISSUE TITLE
Ordering of compressed assets all wrong

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#6787]
I have this compression spec:
```php
<?php
/**
 * Configuration file for the "yii asset" console command.
 * Note that in the console environment, some path aliases like '@webroot' and '@web' may not exist.
 * Please define these missing path aliases.
 */

Yii::setAlias('@webroot', realpath(__DIR__ . '/../web'));
Yii::setAlias('@web', '/');

return [
	// Adjust command/callback for JavaScript files compressing:
	'jsCompressor' => 'java -jar compiler.jar --js {from} --js_output_file {to} --warning_level QUIET',
	// Adjust command/callback for CSS files compressing:
	'cssCompressor' => 'java -jar yuicompressor.jar --type css {from} -o {to}',
	// The list of asset bundles to compress:
	'bundles' => [
		'frontend\assets\AppAsset',
		'common\widgets\FontAwesomeAsset',
		'common\widgets\QtipAsset',
		'common\widgets\ProdigalAsset',
		'yii\widgets\ActiveFormAsset',
		//'common\widgets\ColorpickerAsset',
	],
	// Asset bundle for compression output:
	'targets' => [

		'widgets' => [
			'class' => 'yii\web\AssetBundle',
			'basePath' => '@webroot',
			'baseUrl' => '@web',
			'js' => 'js/widgets-{hash}.js',
			'css' => 'css/widgets-{hash}.css',
			'depends' => [
				'yii\widgets\ActiveFormAsset',
				'common\widgets\FontAwesomeAsset',
				'common\widgets\ProdigalAsset',
				'common\widgets\QtipAsset',
			]
		],
		'base' => [
			'class' => 'yii\web\AssetBundle',
			'basePath' => '@webroot',
			'baseUrl' => '@web',
			//'js' => 'js/base-{hash}.js',
			'css' => 'css/base-{hash}.css',
			'depends' => [
				'yii\bootstrap\BootstrapAsset',
			]
		],
		
		'all' => [
			'class' => 'yii\web\AssetBundle',
			'basePath' => '@webroot',
			'baseUrl' => '@web',
			'js' => 'js/all-{hash}.js',
			'css' => 'css/all-{hash}.css',
			'depends' => [
				'frontend\assets\AppAsset',
				'yii\web\YiiAsset',
				'yii\web\JqueryAsset',
				'yii\bootstrap\BootstrapPluginAsset',
			]
		],

	],
	// Asset manager configuration:
	'assetManager' => [
		'basePath' => '@webroot/assets',
		'baseUrl' => '@web/assets',
		'bundles' => [
			'yii\bootstrap\BootstrapAsset' => [
				'basePath' => '@webroot',
				'baseUrl' => '@web',
				'sourcePath' => null,
			],
			'yii\bootstrap\BootstrapPluginAsset' => [
				'basePath' => '@webroot',
				'baseUrl' => '@web',
				'sourcePath' => null,
			]
		]
	],
];
```

Which after much trial and error prints out this config:
```php
<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-01-08 10:41:06
 */
return [
    'widgets' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            'js/widgets-e0e053f6684aa1249951e5e6ea0bd2a4.js',
        ],
        'css' => [
            'css/widgets-b9443e330a39feb0dd06b78b9ed0f167.css',
        ],
    ],
    'base' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [],
        'css' => [
            'css/base-f3096e47d13209538755ad6d57f7b5e8.css',
        ],
    ],
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            'js/all-d53dc176ed9c417093ce62da3d1697c9.js',
        ],
        'css' => [
            'css/all-9b8619eaf646fbf8caca8b970a1435d9.css',
        ],
    ],
    'common\\widgets\\FontAwesomeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'widgets',
        ],
    ],
    'common\\widgets\\QtipAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'widgets',
        ],
    ],
    'common\\widgets\\ProdigalAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'widgets',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'widgets',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'base',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'all',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'all',
        ],
    ],
];
```

As you can see `'frontend\\assets\\AppAsset'` depends on `'yii\\bootstrap\\BootstrapAsset'` which depends on `base` as such base should come before app asset in my HTML however, in reality what I am getting (can nothing seems to solve it) is my all asset coming last causing my CSS to break.

It is always the same order, cannot make it respect `depends` order.

**Comment by klimov-paul** [comment]
> As you can see 'frontend\\assets\\AppAsset' depends on 'yii\\bootstrap\\BootstrapAsset' which depends on base as such base should come before app asset in my HTML however, in reality what I am getting (can nothing seems to solve it) is my all asset coming last causing my CSS to break.

This does not make any sense. You are telling "base asset" should come <b>before</b> "app asset", but "all asset" coming last, which means <a>after</b> "base asset". These phrases contradict each other.

**Comment by Sammaye** [comment]
Sorry, multiple phrases being said.

Ok so my file above shows three compressed assets:

widgets:
```php
    'widgets' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            'js/widgets-e0e053f6684aa1249951e5e6ea0bd2a4.js',
        ],
        'css' => [
            'css/widgets-b9443e330a39feb0dd06b78b9ed0f167.css',
        ],
    ],
```

base:
```
    'base' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [],
        'css' => [
            'css/base-f3096e47d13209538755ad6d57f7b5e8.css',
        ],
    ],
```
Which ONLY contains Bootstrap CSS.

and all:
```php
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            'js/all-d53dc176ed9c417093ce62da3d1697c9.js',
        ],
        'css' => [
            'css/all-9b8619eaf646fbf8caca8b970a1435d9.css',
        ],
    ],
``` 

which is basically everything else.

The order that these are placed in the HTML is:

- all
- base
-widget

The order they should go in is:

- base
- widget
- all

Now, to explain why I believe they should go into that order in that file: The very first asset to be loaded in my layout, before anything is the `AppAsset`:
```php
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'all',
        ],
    ],
```

As you can see that depends on `'yii\\bootstrap\\BootstrapAsset',` which is registered in the `base` compressed asset as such `base` should come befiore `all` since `all` depends on `base`:
```php
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'base',
        ],
    ],
```

**Comment by Sammaye** [comment]
I do notice now that the `widget` asset can actually appear after all. I am still working on how to order them since if I try and do it directly I get an error out from Yii of course.

**Comment by klimov-paul** [comment]
This shound weird.
However, you may try avoiding the problems specifying direct dependency for the compressed assets: you may modify `depends` array of 'all' including 'base' inot it.
```php
    'all' => [
        ...
        'depends' => [
            'base',
        ],
    ],
```
At least this should work for now.

**Comment by Sammaye** [comment]
When I do that this happens when I run assets command:

``bash
xxxxxx@ubuntu:/media/xxx_ws/webapp$ sudo ./yii asset frontend/config/assets.php frontend/config/assets_compressed.php
Loading configuration from 'frontend/config/assets.php'...
Collecting source bundles information...
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: base'

in /media/nhbs_ws/webapp/vendor/yiisoft/yii2/console/controllers/AssetController.php:304

Stack trace:
#0 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/console/controllers/AssetController.php(304): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/media/nhbs_ws/...', 304, Array)
#1 [internal function]: yii\console\controllers\AssetController->yii\console\controllers\{closure}('base', 'yii\\web\\JqueryA...')
#2 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/console/controllers/AssetController.php(309): usort(Array, Object(Closure))
#3 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/console/controllers/AssetController.php(178): yii\console\controllers\AssetController->loadTargets(Array, Array)
#4 [internal function]: yii\console\controllers\AssetController->actionCompress('frontend/config...', 'frontend/config...')
#5 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#6 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#7 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#8 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#9 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('asset', Array)
#10 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('asset', Array)
#11 /media/nhbs_ws/webapp/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(console\components\Request))
#12 /media/nhbs_ws/webapp/yii(27): yii\base\Application->run()
#13 {main}
```

**Comment by klimov-paul** [comment]
No. Not before running compress command, but after. Just modify the results of produced config.

**Comment by Sammaye** [comment]
Ok that could be possible though it means I have to break my build script to stop automation of this.

But that could be a way to fix the ordering currently, thanks.

**Comment by klimov-paul** [comment]
There is no issue here.
Your `frontend\assets\AppAsset` depends on `yii\web\YiiAsset`, which depends on `all`. So when loading `frontend\assets\AppAsset` `all` asset should come first. Only after its dependency resolved `yii\bootstrap\BootstrapAsset` will be loaded.
You may try to switch order of `yii\web\YiiAsset` and `yii\bootstrap\BootstrapAsset` in your `frontend\assets\AppAsset` dependency:
```php
    'frontend\\assets\\AppAsset' => [
        ...
        'depends' => [
            'yii\\bootstrap\\BootstrapAsset', // bootstrap goes first, so 'base' goes first
            'yii\\bootstrap\\BootstrapPluginAsset',
            'yii\\web\\YiiAsset',
        ],
    ],
```
