### ISSUE TITLE
ActiveQuery::where() problem,a field can not be set 'IS NULL' and equal a value at the same time.

### ISSUE THREAD

**Issue by alexsunxl** [yiisoft/yii2#6788]
![2b2f72d3-c661-42ce-97f7-6affd97be8ed](https://cloud.githubusercontent.com/assets/4388158/5661184/a1396656-9763-11e4-8abd-82b367e75bbc.png)

I want to get the last line with code 
```javascript
$query = MessageText::find()
    ->joinWith(['message'=>function($query)use($user_id){
        $query->andWhere(['or',['receive_id'=>null],[''receive_id'=>$user_id]]);
        //or use andfilterWhere
    }],true,'LEFT JOIN');

```
but I just get this.

![1234](https://cloud.githubusercontent.com/assets/4388158/5661545/141d6664-9768-11e4-93c1-94655a6096ab.jpeg)

I know that I can post a string not a array like this.
```javascript
$query->andWhere("receive_id is null or receive_id=" . $user_id)
```
but post a string directly is very ugly  and hard to maintain, how can i use the [key=>value] get the sql?

**Comment by yurii-github** [comment]
everythings was fine for me.

migration schema like this

    public function safeUp()
    {
    	$this->createTable('message', [
    		'message_text_id' => 'INT PRIMARY KEY',
    		'message_type' => 'INT',
    		'receive_id' => 'INT'
    	]);
    	
    	$this->createTable('message_text', [
    		'message_text_id' => 'INT  PRIMARY KEY',
    		'msg' => 'VARCHAR(200)'
    	]);
    	
    	$this->batchInsert('message', ['message_text_id','message_type', 'receive_id'], [
    		[1, 1, null],
    		[2, 2, 2],
    		[3, 3, 3],
    	]);
    		
    	$this->batchInsert('message_text', ['message_text_id','msg'], [
    		[1, 'message 1'],
    		[2, 'message 2'],
    		[3, 'message 3']
    	]);
    }

made 2 models

	class Message extends ActiveRecord
	class MessageText extends ActiveRecord
	{
		public static function tableName() { 	return 'message_text';	}
		public function getMessage() { return $this->hasOne(Message::className(), ['message_text_id' => 'message_text_id']);	}
	}

and dummy controller action with code

		$user_id = 3;
		$q = MessageText::find()->select('message_text.*, receive_id')->where('message_type in (1,2,3)')->
		joinWith([
			'message'=> function($q) use($user_id) {
				/* @var $q \yii\db\Query */
				$q->where(['or', [ 'receive_id'=>null], ['receive_id'=>$user_id ]]);
			}], true, 'left join');
		/* @var $c \yii\db\Command */
		$c = $q->createCommand();
		var_dump($c->queryAll(), $c->rawSql);
		die;

it produces good sql and returns 2 records

	array (size=2)
	0 =>
	array (size=3)
	'message_text_id' => string '1' (length=1)
	'msg' => string 'message 1' (length=9)
	'receive_id' => null
	1 =>
	array (size=3)
	'message_text_id' => string '3' (length=1)
	'msg' => string 'message 3' (length=9)
	'receive_id' => string '3' (length=1)
	string 'SELECT `message_text`.*, `receive_id` FROM `message_text` left join `message` ON `message_text`.`message_text_id` = `message`.`message_text_id` WHERE (message_type in (1,2,3)) AND ((`receive_id` IS NULL) OR (`receive_id`=3))' (length=224)

**Comment by alexsunxl** [comment]
ohhhhhh
I see , it should be used where() rather than andfilterWhere().

**Comment by tentruycapcuaban** [comment]
get data: find,where,andwhere,joinwith with yii2

hi all 
how to fix it
i have two table
![image](https://cloud.githubusercontent.com/assets/17898925/16000392/5c27e44e-3176-11e6-92dc-ec141d443771.png)
![image](https://cloud.githubusercontent.com/assets/17898925/16000408/7dccdd84-3176-11e6-8770-97c8ae57881b.png)
it link via: ID and phone_stock_id
 $obCampaignPhonestock = ObCampaignPhonestock::find()
            ->where(['=', 'id_campaign', $this->ID])
            ->andWhere(['=', 'status', CodeMst::GROUP_PHONESTOCK_CALL_STATUS_AVAILABLE])
            ->andWhere(['IS', 'complete_date', null])
            ->joinWith(['ob_phone_stock'],true,'INNER JOIN')
            ->where(['ob_phone_stock.ID'='ob_campaign_phonestock.phone_stock_id'])
            ->orderBy('RAND() limit 100000'); // tung 16/12/2015 tang toc do get customer random
//            ->orderBy(['ID' => SORT_ASC]);
//        ->andWhere(['last_call_time' => null])
//        ->andWhere(['=', 'number_of_call', 0])
        //$obCampaignPhonestock1=$obCampaignPhonestock->all();
but show data to test=> not show
        var_dump($obCampaignPhonestock1);
        exit;
any help ???? tks all

**Comment by alexsunxl** [comment]
@tentruycapcuaban  
 i think you should open a new issue, so others can see.....hahah
