### ISSUE TITLE
add MIME types 'image/pjpeg' and 'image/x-png' for ie

### ISSUE THREAD

**Issue by djfly** [yiisoft/yii2#6794]
https://github.com/yiisoft/yii2/blob/master/framework/helpers/mimeTypes.php

some tests Result:
firefox image/jpeg image/bmp image/gif image/png

ie 6 image/pjpeg image/bmp image/gif image/x-png

ie 7 image/pjpeg image/bmp image/gif image/x-png

ie 8 image/pjpeg image/bmp image/gif image/x-png

ie 9 image/jpeg image/bmp image/gif image/png

**Comment by klimov-paul** [comment]
This is not implementable: `mimeTypes.php` file structure does not allow several mime types for the same file extension. It can not hold both `jpg => 'image/jpeg'` and `jpg => 'image/pjpeg'`.

**Comment by cebe** [comment]
We are not maintaining our own version of the mime file, this is taken from http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=markup

please report to the apache project if you want to change mime types.
