### ISSUE TITLE
Something wrong with class loader ?

### ISSUE THREAD

**Issue by Rikcon** [yiisoft/yii2#6795]
Hello everyone, i have an issue with yii2 class loader.
The problem is it somehow messes up class name, i get following error when i edit config/web.php to show debug toolbar for my ip :

Class Aii\debug\Module does not exist

So the problem is it REPLACES first letter of class name from Yii to Aii, i did fresh install with composer several times, on two independent hardware (vagrant VM and my VPS). 
It will replace ANY first letter.

I can provide any info about my setup if you ask.

Here is what i added to config/web.php : 
(lines i added surrounded by *)

    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';
    *$config['modules']['debug']['allowedIPs'] = ['*'];*
    $config['bootstrap'][] = 'gii';    
    $config['modules']['gii'] = 'yii\gii\Module';
    *$config['modules']['gii']['allowedIPs'] = ['*'];*

If i add $config['modules']['gii']['allowedIPs'] = ['*']; the same error appears but for gii class.

**Comment by mdmunir** [comment]
```php
$config['modules']['debug'] = [
    'class'=>'yii\debug\Module',
    'allowedIPs'=>'*'
];
```

**Comment by Rikcon** [comment]
Thank you, but yii expects allowedIPs to be an array. 
So working code look like this 

    $config['modules']['debug'] = [
        'class'=>'yii\debug\Module',
        'allowedIPs'=>['*']
    ];

**Comment by sau00** [comment]
Same to me, how could it be fixed?

**Comment by sau00** [comment]
Same happens when I'm trying to load gii module.

Class Aii\gii\Module does not exist

**Comment by mdmunir** [comment]
@sau00 do you read the comments?

**Comment by sau00** [comment]
@mdmunir aww, sry, I've fixed it for Debug, but haven't fixed it for Gii module.

Thanks.

**Comment by Sir-Magic** [comment]
the 'AllowedIPs' is not the thing what's wrong

Add the class to the modules => `['class']`
```
// configuration adjustments for 'dev' environment
$config['bootstrap'][] = 'debug';
$config['modules']['debug']['class'] = 'yii\debug\Module';
$config['modules']['debug']['allowedIPs'] = ['*'];
$config['bootstrap'][] = 'gii';    
$config['modules']['gii']['class'] = 'yii\gii\Module';
$config['modules']['gii']['allowedIPs'] = ['*'];
```

**Comment by pragmas** [comment]
Thx Sir-Magic. Basic and advanced templates should be updated accordingly!
