### ISSUE TITLE
sphinx extension: escapeMatchValue is cause wrong query

### ISSUE THREAD

**Issue by UncleCoder** [yiisoft/yii2#6796]
I try to use `escapeMatchValue` according to Sphinx extension documentation, but query contains unnecessary `\` simbol:
```php
$sphQuery->from('content_main,content_delta')->match(new Expression(':match', [':match' => '@(content) ' . \yii::$app->sphinx->escapeMatchValue($model->query)]));
```

If `$model->query` is `one NEAR/3 two` than SQL is 

```sql
SELECT COUNT(*) FROM `content_main`, `content_delta` WHERE MATCH('@(content) one NEAR\\/3 two');
```
and does not work. Is it a bug? Original sphinx's function `EscapeString` returns `NEAR\/3` in that case. 

(Also, I guess that the colon is missing in the documentation before the second `match`:  `new Expression(':match', ['match' ...`)

**Comment by klimov-paul** [comment]
What do you mean 'does not work'?

**Comment by UncleCoder** [comment]
I meant this query returns wrong result. This is because the query contains an extra backslash in the 'match'.

In your case 'match' expression is value of parameter (string), which is additional quoted in `Command::getRawSql()` and got this redundant backslash

**Comment by klimov-paul** [comment]
I don't get this, why you are trying to escape match operator?
You should escape only the matching content:
```
$sphQuery = new \yii\sphinx\Query;
$rows = $sphQuery
    ->from('content_main,content_delta')
    ->match(new Expression('@(content) :first NEAR/2 :second', [
        'first' => \yii::$app->sphinx->escapeMatchValue($model->firstQuery), // 'one',
        'second' =>\yii::$app->sphinx->escapeMatchValue($model->secondQuery), //  'three',
    ])
)->all();
```
Of course any special symbols and operators are escaped by `escapeMatchValue()`, so user input can not break the query.

**Comment by UncleCoder** [comment]
Ok, I understood. I was confused by example in the documentation. It uses user input which then escaping. I thought this method will properly escaping string to pass operators to "match". But it escapes all punctuations, slashes include used as operators' part. Now I use this approach:
```php
try {
    $sphQuery->match(new Expression(':match', [':match' => '@(content) ' . $_POST['search']]));
    $rows = $sphQuery->all();
} catch (Exception $e) {
//exception is threw if  $_POST['search'] contains wrong match operator (ex. near/2 instead of NEAR/2)
    $sphQuery->match(new Expression(':match', [':match' => '@(content) ' . \yii::$app->sphinx->escapeMatchValue($_POST['search'])]));
    $rows = $sphQuery->all();
}

**Comment by klimov-paul** [comment]
There is no issue here.
