### ISSUE TITLE
GridView assets are not registered

### ISSUE THREAD

**Issue by AidasK** [yiisoft/yii2#6798]
When grid view is created with `GridView::begin` instead of `GridView::widget`, no assets are registered.
This is convenient, because you don't have to write all html in the template.
```php
<?php $grid = GridView::begin([
...
]);?>
<section class="scrollable wrapper w-f w-bh">
                    <section class="panel panel-default">
                        <div class="table-responsive results-table" id="results-table">
                            <?= $grid->renderItems(); ?>
                        </div>
                    </section>
                </section>
                <footer class="footer bg-white b-t">
                    <div class="row text-center-xs">
                        <div class="col-md-6 hidden-sm">
                            <?= $grid->renderSummary(); ?>
                        </div>
                        <div class="col-md-6 col-sm-12 text-right text-center-xs">
                            <?= $grid->renderPager(); ?>
                        </div>
                    </div>
                </footer>
...

**Comment by qiangxue** [comment]
You have to call `$grid->run()` then.

**Comment by AidasK** [comment]
It won't work, because `GridView::end()` echo'es the gridview and I want to echo certain parts manually.

I tried setting layout to empty string, but  `GridView::end()` still echoed an empty div tag.

It seems there are mo methods left to use, which would register gridview assets without echoing the grid it self.

**Comment by qiangxue** [comment]
Right, `end()` won't work. You may consider overriding `GridView::run()` to skip rendering to support your very special usage.
