### ISSUE TITLE
Relations 

### ISSUE THREAD

**Issue by aram88** [yiisoft/yii2#6799]
Please add the Yii 1 relation code style.
It is much better here  are the reasons
1. I can fast find all model relations in one method  (public function relations(){.......} )
2. One developer has worked to the model, then second developer has worked, then other, other ... 
they can add same relation by the different name, because sometimes developer do not have much to review the model code. And developer write new one with different name and code became  large and not good writing.
3. Model is changing about 6 months one relation is written in this line (56-62) other (125-138) other (255-260) and so on 

Here yii 1 example   which  is pretty nice

public function relations()
	{
		return array(
		    'albums' => array(self::HAS_MANY, 'Album', 'user_id'),
		    'userLocation' => array(self::HAS_ONE, 'UserLocation', 'user_id'),
		    'userFrom' => array(self::HAS_MANY, 'UserMessage', 'from_id'),
		    'userTo' => array(self::HAS_MANY, 'UserMessage', 'to_id'),
		);
	}

And here is yii 2 relation which has  written in different lines ((56-62)  (125-138)  (255-260) This is just an example  which  show from real code )

/**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Category::className(), ['id' => 'parent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['parent_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobs()
    {
        return $this->hasMany(Job::className(), ['category_id' => 'id']);
    }

**Comment by qiangxue** [comment]
This has been discussed before. We will stick to the current style.

**Comment by lynicidn** [comment]
$model->getJobs()->count()
->active()
