### ISSUE TITLE
REST application CORS error after create

### ISSUE THREAD

**Issue by a-komarev** [yiisoft/yii2#6804]
I'm creating a REST API for ajax application based on `yii\rest\ActiveController`.
`data/index` & `data/view` are working well, but `data/create` rising CORS error in browser console despite the fact that data is creating. This error rising only in case when header `Location` is setting up after successful model saving.

CORS error in FireFox:
>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at `http://api.int/v1/data`. This can be fixed by moving the resource to the same domain or enabling CORS.

CORS error in Chromium:
>XMLHttpRequest cannot load `http://api.int/v1/data`. The request was redirected to `'http://api.int/v1/data/41'`, which is disallowed for cross-origin requests that require preflight.

Here is my behavior in controller, CORS filter added:
```
    public function behaviors()
    {
        return ArrayHelper::merge([
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
            ],
        ], parent::behaviors());

    }
```

Current create action code from `yii\rest\CreateAction`:
```
public function run()
    {
        if ($this->checkAccess) {
            call_user_func($this->checkAccess, $this->id);
        }

        /* @var $model \yii\db\ActiveRecord */
        $model = new $this->modelClass([
            'scenario' => $this->scenario,
        ]);

        $model->load(Yii::$app->getRequest()->getBodyParams(), '');
        if ($model->save()) {
            $response = Yii::$app->getResponse();
            $response->setStatusCode(201);
            $id = implode(',', array_values($model->getPrimaryKey(true)));
            $response->getHeaders()->set('Location', Url::toRoute([$this->viewAction, 'id' => $id], true));
        } elseif (!$model->hasErrors()) {
            throw new ServerErrorHttpException('Failed to create the object for unknown reason.');
        }

        return $model;
    }
```

So, I've commented out this row and everything work the same way, but without errors:
```
$response->getHeaders()->set('Location', Url::toRoute([$this->viewAction, 'id' => $id], true));
```

As I understood - it's mostly browsers bug, because they aren't doing CORS handshake after redirect. Maybe another status codes needed in this case to tell browser about changing location?
For example `100 Continue` or other ones:
```
301 => 'Moved Permanently',
307 => 'Temporary Redirect',
308 => 'Permanent Redirect',
303 => 'See Other',
```

What this redirect for?

**Comment by a-komarev** [comment]
I found additional information how to write JS in case of Location header in response:
http://www.aaron-powell.com/posts/2013-11-28-accessing-location-header-in-cors-response.html

But still can't understand, why we need to redirect user to another location if script will anyway return a model in current location?

**Comment by cebe** [comment]
@a-komarev can you check whether this is cause by the order of the behaviors? please show a dump of the resulting behaviors returned by your `behaviors()` method.

See also https://github.com/yiisoft/yii2/commit/7ba631b4ae3a40206e752fded8775b65491d1bcb#diff-25ce342a16184c86f64860485740f500R91 for a correct implementation with ActiveController.

**Comment by a-komarev** [comment]
@cebe Sorry, issue was raised at one of my previous clients services, and I don't have access to it anymore.

**Comment by cebe** [comment]
closing this then.
