### ISSUE TITLE
Problem with DIC and BaseActiveRecord::instantiate()

### ISSUE THREAD

**Issue by tahirm** [yiisoft/yii2#6808]
Im using PHP callbacks to register my dependencies in DIC. Now it works fine and all dependencies are resolved fine when i use ```Yii::$container->get()```. Problem comes in when models are created internally by Yii using ```BaseActiveRecord::instantiate()``` method. 

Suppose I have a Car model that depends on an another class Fuel. I can easily inject Fuel into Car using something like following and I can easily access Fuel within Car later:

````php
\Yii::$container->set('Car', function($container, $params, $config) {
  $car =  new Car();
  $car->fuel = $container->get('Fuel');
  return $car;
});
````

Problem happens when I retrieve some record from model and it return new instance of that model, now I don't have access to Fuel anymore because Car's dependencies are not resolved and following code give error at third line.

`````php
$car = Yii::$container->get('Car');
$carRecord = $car->find()->one();
$carRecord->fuel->price;
`````
Although, ```$carRecord```is an instance of Car but its instantiated by ```BaseActiveRecord::instantiate()``` thats why its dependencies are not resolved from DIC.

So how can I define my dependencies so that they are resolved by ActiveRecord for every new instance of the model? Or I'm doing something wrong anywhere else?

Please let me know if something is not clear or you need more code examples.

**Comment by qiangxue** [comment]
This is for performance reason, `BaseActiveRecord::instantiate()` is using `new` to directly create new instances without using DIC (because potentially you may create many such instances). To work around the problem, you may override this method and call DIC to instantiate the record.
