### ISSUE TITLE
Add application-wide cache duration parameter

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#6809]
I think it could be implemented for convenience.

As of now it falls back to `0 means never expire` if value is not specified when calling `set` - thow this value is not practical.
Setting it each time on each `set` is tedious, while overriding core classes only just for it...

To keep BC it may be set 0 by default in `\yii\caching\Cache`

```
    public function set($key, $value, $duration = null, $dependency = null)
    {
        if ($duration === null) {
             $duration = $this->defaultDuration;
        }
        ...
        return $this->setValue($key, $value, $duration);
    }
```

**Comment by dynasource** [comment]
having a customizable default other than 0 seems quite useful to have, @SDKiller, can you create a PR for it?

**Comment by samdark** [comment]
I think such default could be very confusing for people who get used the fact that it is always 0.

**Comment by dynasource** [comment]
it can still be 0 as default? Its also useful in local development environments in which 0 in not always favorable

**Comment by samdark** [comment]
OK.

**Comment by SDKiller** [comment]
@dynasource 
I'm on vacation for the next 7 days, I can prepare a PR when I return back home.
