### ISSUE TITLE
Something wrong with 2.0.2 release and composer?

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#6823]
```
    "require": {
        ...
        "yiisoft/yii2": "2.0.2",
        ...
```
>
```
  Problem 1
    - The requested package yiisoft/yii2 2.0.2 could not be found.
```

Another attempt

```
    "require": {
        ...
        "yiisoft/yii2": "@stable",
        ...
```
>
```
  - Removing yiisoft/yii2 (dev-master 390b347)
  - Installing yiisoft/yii2 (2.0.1)
    Downloading: 100%
```

And I see 2.0.2 is not available on https://packagist.org/packages/yiisoft/yii2

**Comment by cebe** [comment]
2.0.2 is not officially out yet, please wait for the news on http://www.yiiframework.com/

It always takes hours after creating the tag for all subsplits to get synced.

**Comment by SDKiller** [comment]
Thanks.
Sorry for my impatience ;-D
