### ISSUE TITLE
yii2-pjax prevents updating to Yii2 2.0.2 stable

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#6827]
Could not change project `miminum-stability` to `stable` because of

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Removal request for bower-asset/yii2-pjax == 2.0.2.9999999-dev
    - Removal request for bower-asset/yii2-pjax == 9999999-dev
    - Installation request for bower-asset/yii2-pjax * -> satisfiable by bower-asset/yii2-pjax[2.0.2.x-dev, dev-master].
```

Only by adding `"bower-asset/yii2-pjax": "dev-master",` to root `composer.json` I succeeded intall Yii2 2.0.2

Btw: 
is `yii2-pjax` extension along with buggy `pjax.js` so nesessary in the core? 
Why not move it along with `Pjax` widget and asset to separate extension and put in `suggest` section.

Fore example more widely used `bootstrap`, `jui`, etc. are not included in framework's `composer.json` but go as separate extensions.

**Comment by cebe** [comment]
can you show you composer.json? Also which version of the composer asset plugin are you using?

**Comment by SDKiller** [comment]
Initially it was with `"minimum-stability": "dev"` for about a week:

```
{
    "name": "myproject",
    "description": "My Yii 2 project",
    "type": "project",
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-debug": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

After 2.0.2 was released I tried to change it to `stable` and got the abovementioned error with `yii2-pjax`.
Had to explicitly add `"bower-asset/yii2-pjax": "dev-master"` to it.

Now this works:

```
{
    "name": "myproject",
    "description": "My Yii 2 project",
    "type": "project",
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-debug": "*",
        "bower-asset/yii2-pjax": "dev-master"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

Globally is installed composer asset plugin `dev-master`

**Comment by SDKiller** [comment]
Upd2

Removed `composer.lock` and `vendor` directory - did not help.

**Comment by cebe** [comment]
> Could not change project miminum-stability to stable because of

I now see where the problem is, this is a feature of the composer asset plugin to improve speed dramatically: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#disable-the-import-filter-using-the-installed-packages

The only drawback of this is that you can not downgrade packages, which is the case when you switch from dev to stable. You will have to remove composer.lock and vendor dir afaik and run composer install again.

**Comment by SDKiller** [comment]
@cebe 

Thanks for explanatory answer, indeed https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#disable-the-import-filter-using-the-installed-packages could be the case 
(while at the moment I'm a bit tired and ran out of time playing around with `composer` to verify it - maybe I'l try to reproduce it sometimes later).


What with the second point - moving `Pjax` out of the core - like `bootstrap` and `jui`?

Does it make sense to keep extension which is not mandatory and very much specific in the core?

And does it make sense to open an appropriate issue?

**Comment by cebe** [comment]
Of course you can open an issue about this to start a discussion. I do not have an opinion on that right now, need to think about it.
