### ISSUE TITLE
YII 2 BUG in ResetPasswordForm Model Advance Template and how to fix it

### ISSUE THREAD

**Issue by woshka** [yiisoft/yii2#6829]
Hello,

There is a bug in ResetPasswordForm.php which has a problem for reseting a new password that will not work

The following Code in this model must be changed

    public function resetPassword()
    {
        $user = $this->_user;
        $user->password = $this->password;
        $user->removePasswordResetToken();

        return $user->save();
    }

Correct form is as the following:

        public function resetPassword()
    {
        $user = $this->_user;
        $user->password = $user->setPassword($this->password);
        $user->removePasswordResetToken();

        return $user->save();
    }

**Comment by a-komarev** [comment]
Tested it couple of times. Resetting password is working without this changes well.

**Comment by woshka** [comment]
It isn't working for me and Logical t shouldn't
if you don't change it to what I mentioned it won't use the setPassword function for encryption and the password wont be working

**Comment by lynicidn** [comment]
$user->password = $this->password;
or
$user->setPassword($this->password);
via magic

**Comment by a-komarev** [comment]
In other words, because property `password` not exist in model magic method __set calling setPassword(). `\yii\db\BaseActiveRecord`
More information about magic methods: http://php.net/manual/en/language.oop5.overloading.php#object.set

**Comment by woshka** [comment]
if the User Table has a property password then the "property does not exist" wont happen that is an error other than this scope

**Comment by a-komarev** [comment]
But by default there is no `password` field (there is only `password_hash` field) and if you will call a method setPassword manually password will be hashed twice.

**Comment by woshka** [comment]
Please take a look at the SignupForm.php
the signup Method has this

public function signup()
    {
        if ($this->validate()) {
            $user = new User();
            $user->username = $this->username;
            $user->email = $this->email;
            $user->setPassword($this->password);
            $user->generateAuthKey();
            $user->save();
            return $user;
        }

        return null;
    }


if a user would signup using this form the reseting must use setPassword for assigning new password
otherwise it wont work

**Comment by a-komarev** [comment]
Yes, but you showed another way to define this value:
```
$user->password = $user->setPassword($this->password);
```
So, I'm talking only about it.

**Comment by woshka** [comment]
You are right
the password property is extra and it is only the password_hash that is needed and needs to be checked against login

**Comment by woshka** [comment]
The correct form should be this

   public function resetPassword()
    {
        $user = $this->_user;
        $user->setPassword($this->password);
        $user->removePasswordResetToken();

        return $user->save();
    }

**Comment by samdark** [comment]
It is OK as is.
