### ISSUE TITLE
Bug :cannot adding static column in Query

### ISSUE THREAD

**Issue by AmineMx** [yiisoft/yii2#6830]
i can't add static column in query like Model::find()->->addSelect(" 'Str' as column")->all()

because it will quoted like this `` `'Str'` AS `column` ``
and i get error of Column not found

**Comment by mdmunir** [comment]
```php
->addSelect(['column'=>new yii\db\Expression("'Str'")])
```
Or (i dont know it will work or not)
```php
->addSelect(['column'=>new yii\db\Expression(':static_val',[':static_val'=>'Str'])])
```
