### ISSUE TITLE
query->andWhere

### ISSUE THREAD

**Issue by flarpy** [yiisoft/yii2#6832]
$query = new Query();
				$query->where('id = 1');
				$query->andWhere('x = 2');
				$query->andWhere('y = 3');

gives SELECT * WHERE ((id = 1) AND (x = 2)) AND (y = 3)

but should give

SELECT * WHERE ((id = 1) AND (x = 2) AND (y = 3))

**Comment by Alex-Code** [comment]
Not a framework issue, http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/

`$query->where(['id' => 1, 'x' => 2, 'y' => 3]);`

**Comment by flarpy** [comment]
Are you saying this is expected behaviour?

**Comment by mdmunir** [comment]
Ya, its expected behavior.

**Comment by fernandezekiel** [comment]
if you want to create the condition you just said, you need this:
```php
$query = new Query();
$query->where([
    'and',
    ['id' => 1],
    ['x' => 2],
    ['y' => 3]
]);
```

**Comment by flarpy** [comment]
Thanks, that I have done. 

However, this is misguiding (http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html)

If you are building parts of condition dynamically it's very convenient to use andWhere() and orWhere():

$status = 10;
$search = 'yii';

$query->where(['status' => $status]);
if (!empty($search)) {
    $query->andWhere(['like', 'title', $search]);
}

**Comment by cebe** [comment]
There is no difference in logic between `((id = 1) AND (x = 2)) AND (y = 3)` and `((id = 1) AND (x = 2) AND (y = 3))`, AND is [associative](http://en.wikipedia.org/wiki/Associative_property).
