### ISSUE TITLE
Question about action function name

### ISSUE THREAD

**Issue by kurrata** [yiisoft/yii2#6833]
Hi

I am talking with yii2-admin module dev and we need to confirm something about yii2 style(https://github.com/mdmsoft/yii2-admin/issues/119)

Are actions names like this allowed?

```php
public function actionVsaa_import() {
//...
}
```

**Comment by klimov-paul** [comment]
@kurrata, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by a-komarev** [comment]
Better to name it like:
`actionVsaaImport()` it will be represented as `/vsaa-import`

**Comment by mdmunir** [comment]
@klimov-paul It is not "question", it is about Yii style.
https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#43-methods
Are actions names like this allowed?
```php
public function actionVsaa_import() {
//...
}
```

**Comment by samdark** [comment]
No.

**Comment by qiangxue** [comment]
It's actually allowed. This is the expression checking action ID: `preg_match('/^[a-z0-9\\-_]+$/', $id)`.

**Comment by mdmunir** [comment]
prefer using `actionVsaaImport()` for standarisation :D
