### ISSUE TITLE
question about models

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#6837]
i was caught today by models

in **yii\db\ActiveRecord** you should declare attributes in phpdoc with '@property', if declared in class as public you lose access to data from database for  column with same name, as object will always return data from declared attribute. so, you MUST NOT  declare attributes in class

in **yii\base\Model** you MUST declare attributes in class instead, because otherwise you will get unknown property error on access.

**yii\db\ActiveRecord** extends **yii\base\Model** but behave differently.

should it throw an error that it is not allowed or something? because this thing just silently break code if database attribute equals to declared one in class.

---------------

i used php5.6 x64 on windows

example of code below. php ignores getter if public attribute was declared

	class A
	{
		public $a = 'a';
		private $b = 'b';
		
		function __get($n)
		{
			return 'd';
		}
		
		function __set($n,$v)
		{
			$this->$n = $v;
		}
	}
	
	$aa = new A();
	$aa->c = 'c';
	
	var_dump($aa, $aa->a, $aa->b, $aa->c);

	object(A)[1]
	  public 'a' => string 'a' (length=1)
	  private 'b' => string 'b' (length=1)
	  public 'c' => string 'c' (length=1)
	string 'a' (length=1)
	string 'd' (length=1)
	string 'c' (length=1)

to extend with code like (not sure about impact on perfomance though)

	class A
	{
		public $a = 'a';

		function __construct()
		{
			if(property_exists(get_called_class(),'a')) {
				throw new Exception('[a] declaration is not allowed');
			}
		}

**Comment by samdark** [comment]
This is normal PHP behavior so I don't think there should be any warnings.
