### ISSUE TITLE
Suggestion: Is any chance to see in Yii2 the following useful console commands like Symfony2 has?

### ISSUE THREAD

**Issue by uran1980** [yiisoft/yii2#6841]
**Suggestion:** Is any chance to see in Yii2 the following useful console commands like Symfony2 has?

for example like this from Symfony2:
```
help                Display help for a command
list                Lists all registered console commands
assetic:dump        Dumps all assets to the file system
cache:clear         Clear the cache
cache:warmup        Warms up an empty cache
route:debug         Dysplay current routes for an application
(route:dump-apache   Dumps all routes as Apache rewrite rules)
route:match         Helps debug routes by simulating a path info match
(server:run          Run PHP built-in web server)
(translation:update  Updates the translation file)
```

**Comment by Faryshta** [comment]
Yii2 uses controllers for the commands so I think we can create a `HelpController` that simply reads the phpDoc.

`yii help migrate/create`

Would read the phpDoc of `MigrateController` class and `actionCreate` method

**Comment by cebe** [comment]
@Faryshta have you tried to run that command, it already works that way ;)
@uran1980 many of the mentioned commands are already available. Which exactly do you miss?

**Comment by cebe** [comment]
```
$ ./yii

This is Yii version 2.0.3-dev.

The following commands are available:

- asset     Allows you to combine and compress your JavaScript and CSS files.
- cache     Allows you to flush cache.
- fixture   Manages fixture data loading and unloading.
- help      Provides help information about console commands.
- message   Extracts messages to be translated from source files.
- migrate   Manages application migrations.

To see the help of each command, enter:

  yii help <command-name>

```

**Comment by Faryshta** [comment]
thats very cool, i didn't knew the existance of help command or any of the others, we need a section of available commands on the docs

http://www.yiiframework.com/doc-2.0/guide-tutorial-console.html

**Comment by callmez** [comment]
And i think list all sub commands on top view is will good to use.
Like 
```
$ ./yii

This is Yii version 2.0.3-dev.

The following commands are available:

- asset     Allows you to combine and compress your JavaScript and CSS files.
	- asset/compress (default): Combines and compresses the asset files according to the given configuration.
	- asset/template: Creates template of configuration file for [[actionCompress]].


- cache     Allows you to flush cache.
	- cache/flush: Flushes given cache components.
	- cache/flush-all: Flushes all caches registered in the system.
	- cache/flush-schema: Clears DB schema cache for a given connection component.
	- cache/index: Lists the caches that can be flushed.


- fixture   Manages fixture data loading and unloading.
	- fixture/load: Loads the specified fixture data.
	- fixture/unload: Unloads the specified fixtures.


- gii       This is the command line version of Gii - a code generator.
	- gii/controller: Controller Generator
	- gii/crud: CRUD Generator
	- gii/extension: Extension Generator
	- gii/form: Form Generator
	- gii/index
	- gii/model: Model Generator
	- gii/module: Module Generator


- help      Provides help information about console commands.


- message   Extracts messages to be translated from source files.
	- message/config: Creates a configuration file for the "extract" command.
	- message/extract: Extracts messages to be translated from source code.


- migrate   Manages application migrations.
	- migrate/create: Creates a new migration.
	- migrate/down: Downgrades the application by reverting old migrations.
	- migrate/history: Displays the migration history.
	- migrate/mark: Modifies the migration history to the specified version.
	- migrate/new: Displays the un-applied new migrations.
	- migrate/redo: Redoes the last few migrations.
	- migrate/to: Upgrades or downgrades till the specified version.
	- migrate/up: Upgrades the application by applying new migrations.

To see the help of each command, enter:
```

**Comment by samdark** [comment]
Good idea @callmez. Want to work on adding it?

**Comment by callmez** [comment]
ok, will try to PR later

**Comment by qiangxue** [comment]
In the real world, it's likely you will have tens of commands. Expanding the subcommands by default will result in a super long list of output.

**Comment by qiangxue** [comment]
Imagine the real use scenario: when you want to execute a command, you first want to find out which kind of command you want to execute, then you will identify which sub-command to execute. Expanding all sub-command together will make the first step more difficult.

**Comment by cebe** [comment]
even though the list is long what you really want is the subcommand that is available so that you can run it. The current list of main commands is not very helpful as you may run them in some cases and in some cases not. This is not obvious from the current list. To actually run a command you currently always have to run the help two times to be sure what command you want to run. When all are listed you get your goal right away. I am for adding sub commands in the list.

**Comment by callmez** [comment]
In fact most web apps doesn't have tens of commands, developers just want to know what command can  be use

**Comment by Faryshta** [comment]
commands available can be tricky because since the commands are controllers they can be added in modules, apps or by other packages and libraries installed with composer.

for example in production environment `gii` is not available. I think it would be better if `./yii` is simply a shortcut for `./yii help`

**Comment by samdark** [comment]
I think long list is OK. Console buffer is long enough usually so you can scroll to read it.
