### ISSUE TITLE
gii能否提供app创建工具

### ISSUE THREAD

**Issue by c4ys** [yiisoft/yii2#6848]
希望gii能够提供创建工具，比如创建frontend,backend,api。

**Comment by a-komarev** [comment]
If you can translate this text in english - more people can help you out. Thank you.

**Comment by lichunqiang** [comment]
@a-komarev 

He hope gii support app generation tools.

For example: via gii to create api app like frontend & backend app in advanced apps.

**Comment by diwms** [comment]
Why gii? Composer is great for this task

**Comment by lichunqiang** [comment]
@diwms 

But after created advanced project via composer, how to create a new site app.

**Comment by cebe** [comment]
Creating a new app inside a project highly depens on the directory structure and can basically be done by copying existing folders and renaming some files. I do not think we can provide a generic enough generator in gii.
