### ISSUE TITLE
Ucfirst in Yii2 for createAction

### ISSUE THREAD

**Issue by IgnacioAular** [yiisoft/yii2#6851]
Hello everybody! 

Please how can I save data using ucfirst in Yii2, I have this:

$model = new Employee();
$model->first_name = ucfirst($model->first_name)  // Don't work

I have this too:

$model = new Employee();
$model->first_name = ucfirst(Yii::$app->request->post('first_name')); // Don't work

Thank you very much in advance!

Best regards!!

**Comment by Alex-Code** [comment]
Please use the forums for this issue, http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/

Git is for reporting framework bugs.
