### ISSUE TITLE
Validate multiple on create

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#6855]
I think necessary, show in documentation, how to proceed with the loadMultiple the create action.

Currently, i am using the code below:

```php
public function actionCreate()
{
        $settings = []
        for ($i = 0; $i < count(Yii::$app->request->post('Setting')); $i++){
            $settings[] =  new Setting()
         }
         ...
}
```
I don't think elegant this code, maybe, we can adds one method to `Model`:

```php
    $count =  count(Yii::$app->request->post('Setting'));
    $settings = Setting::createMultiple($count, $scenario);
```

**Comment by SilverFire** [comment]
Already present http://www.yiiframework.com/doc-2.0/guide-input-tabular-input.html#creating-a-dynamic-set-of-new-records
