### ISSUE TITLE
LocalStorage ActiveRecord Support

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii2#6858]
Hi,

as I'm currently working on a project where the client is not always online - a feature to support local storage within the framework as if it is like a real database would be very helpfull - do you have any plans to implement localStorage? 

As I can see the debugToolbar uses this feature to check if it's maximized or not;)

Thanks and regards Philipp

**Comment by cebe** [comment]
what about sqlite?

**Comment by cebe** [comment]
Inventing a complete storage and DB engine is out of the scope of the framework.

**Comment by philippfrenzel** [comment]
sorry, isn't sqlite not only on the server accessible?

**Comment by samdark** [comment]
Yes, it is. Using localStorage from PHP is kinda weird. What's the use case exactly?

**Comment by philippfrenzel** [comment]
btw: started using depot.js if someone is interested in this issue :)

**Comment by samdark** [comment]
Yep, that's much better. Such a library is out of scope of PHP framework.

**Comment by a-komarev** [comment]
@philippfrenzel Thanks for information. It will be great to have an extension with assets loading this script.

**Comment by philippfrenzel** [comment]
will write an extension;) And as the "offline" storage is getting more and more important;)
