### ISSUE TITLE
Serialization logic in REST ActiveControllers

### ISSUE THREAD

**Issue by belerophon** [yiisoft/yii2#6859]
Hi there,

I've come to a problem when adding a new action into a controller descending from `yii\rest\ActiveController`:
- that action returns an array of `ActiveRecord`, on which no pagination is required. From what I could see, the `Controller` `afterAction` function sends  the that action return value into the function `serialize()`:
  
  ```
  public function serialize($data)
  {
      if ($data instanceof Model && $data->hasErrors()) {
          return $this->serializeModelErrors($data);
      } elseif ($data instanceof Arrayable) {
          return $this->serializeModel($data);
      } elseif ($data instanceof DataProviderInterface) {
          return $this->serializeDataProvider($data);
      } else {
          return $data;
      }
  }
  ```

As such, the result gets returned immediately on the `else` part.
The problem is that, later, this makes the app throw an **Unable to resolve the relative route: view. No active controller is available.** because of the `Url::to()` call inside the `ActiveRecord` models that make up the array.

**How can I prevent this?**

This happens after this: (`yii\base\Module`; line 456)

```
$result = $controller->runAction($actionID, $params);
Yii::$app->controller = $oldController;
```

where `$result` is still an array and $oldController is null, and because of this:(`yii\web\XmlResponseFormatter`; line 77)

```
    protected function buildXml($element, $data)
    {
        if (is_object($data)) {
            $child = new DOMElement(StringHelper::basename(get_class($data)));
            $element->appendChild($child);
            if ($data instanceof Arrayable) {
                $this->buildXml($child, $data->toArray());
            } else {
```

where `toArray()` is called, thus the model's `getLinks()` is called, and the `Url::to()` fails because `$oldController` (and the current `Yii::$app->controller` is now null).

**Am I doing something wrong when adding a new action to an ActiveController??**

Thanks in advance!

**Comment by belerophon** [comment]
Also, it seems that, because a simple `Array` is not processed by the `serialize` method of `yii\rest\Serializer`, we also loose all the functionality related to the "fields" and "extraFields" configuration... 


Should I wrap that return value into something else, like a _DataProvider_ of some sort?

**Comment by belerophon** [comment]
Well, something like this:

                $ret = [...]
		return new ArrayDataProvider([
		    'allModels' => $ret,
		    'sort' => false,
		    'pagination' => false,
		]);

seems to do the job... 

But this, should probably go to the docs, if it really is the correct way to deal with these cases.

**Comment by dynasource** [comment]
closed in favor of https://github.com/yiisoft/yii2/issues/6844
