### ISSUE TITLE
bower path incorrect?

### ISSUE THREAD

**Issue by JackyChan** [yiisoft/yii2#6861]
I use composer to manage yii2 dependency. The assets file are downloaded to vendorPath/bower-asset directory, but set the @bower alias to vendorPath/bower.

**Comment by qiangxue** [comment]
Make sure you have this file: https://github.com/yiisoft/yii2/blob/master/apps/advanced/.bowerrc

**Comment by JackyChan** [comment]
No. Thanks.

**Comment by cebe** [comment]
I guess it is more about having https://github.com/yiisoft/yii2/blob/master/apps/basic/composer.json#L49 in your composer.json
