### ISSUE TITLE
behaviors protected / private methods

### ISSUE THREAD

**Issue by KJLJon** [yiisoft/yii2#6862]
On behaviors private / protected methods will attempt to be called but fail.  For example, if I have SluggableBehavior added as a behavior and I have another behavior with a public function getValue() it will return error because SluggableBehavior::hasMethod('getValue') returns true even though the ActiveRecord can't access the protected method.

Reflection is probably too slow to fix it.  A possible solution is to maintain a list of unavailable methods that are inside behaviors so hasMethod() return true for public methods and false for private/protected methods.

In the SluggableBehavior it can be defined something like so:
```php
public function hasMethod($name)
{
    $inaccessibleMethods = [
        'validateSlug',
        'generateUniqueSlug',

        //could be added to AttributeBehavior
        'getValue', 
    ];
    return in_array($name, $inaccessibleMethods) ? false : parent::hasMethod($name);
}
```

Even though this problem is in Object and applies to everything, I think it is typically only an issue with mixins since the method could potentially be defined in one of the other behaviors.

**Comment by SDKiller** [comment]
Related, I think

https://github.com/yiisoft/yii2/issues/5133

**Comment by cebe** [comment]
yeah right, @SDKiller thanks for pointing to that.
