### ISSUE TITLE
Exclude demo app classes from list of subclasses in docs

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#6863]
Look for example at

- http://www.yiiframework.com/doc-2.0/yii-base-controller.html

The list of subclasses is very long. So long that it's hard to find what might be interesting because it's cluttered up with all the controllers from the demo apps. I don't think the demo app classes should be here because they are not part of the Yii API.

**Comment by SDKiller** [comment]
+1

**Comment by cebe** [comment]
@qiangxue must be a problem on the website, can you check it.

**Comment by qiangxue** [comment]
Fixed. Thanks for reporting.
