### ISSUE TITLE
Codeception Yii2 Module 'cleanup' of multiple DB connections and multiple requests in Functional Tests

### ISSUE THREAD

**Issue by jkovacs618** [yiisoft/yii2#6865]
This issue is a request for an enhancement of the Codeception Yii2 Module for Functional Testing. The module includes a 'cleanup' option to use a DB Transaction for the main 'db' connection, but is missing some functionality that I am expecting.  The module needs to handle DB Transactions for multiple DB connections, as well as persist the DB connections and their open transactions across multiple Application Requests within one functional test.

I have come up with a solution and provide code examples below for anyone else who needs this, but I would also like to have a discussion on best practices, @DavertMik, and request that the concept be integrated into the Codeception Yii2 Module.

I found this Blog post on the Codeception site for Unit Testing with Database:
http://codeception.com/06-28-2014/unit-testing-with-database.html
The post indicates to use DB Transactions around Unit and Functional Tests for automatic rollback of DB changes for repeatable tests, rather than re-initializing the database (slow).  There are some examples, but the documentation, configuration, and best practices for Functional Tests are lacking.  Also, the Codeception Yii2 Module page is missing documentation on the 'cleanup' config option that is available in code.

I am using Yii2 Advanced app template and Codeception to write Functional Tests for an application.  Our project has multiple DB connections (db, db_log, etc) and has a large database, so re-initializing during testing with dump.sql scripts is not a good solution.  I like the idea of DB Transactions to speed up testing and keep the database data clean.  I was hoping the Yii2 Module would support multiple connections out of the box, but found this wasn't the case.

Additionally, I am writing Functional Tests using Cest classes such that one test function makes several calls to amOnPage and submitForm in sequence to simulate and fully test a business process. These pages/forms will insert DB data that a subsequent page/form requires, so there are dynamic data prerequisites between pages within one test.  To use the DB Transaction concept for automatic rollback of data, I understand this must be done at the test level, requiring that all parts of the test (multiple page calls) are done together.  This functionality is not currently available in the Codeception Yii2 Module.

While investigating the Codeception Yii2 Module and Yii2 Client code, I found that the Yii2 module _before function creates $this->app in the module using $this->client->startApp(), and begins a transaction on $this->app->db.  The _after function rolls back this transaction.  However, when doRequest is called many times in a test, $this->client->startApp() is called many times, creating multiple $app objects, and thus many separate db connections that do not have the original transaction enabled.  Thus, the DB records added by functional tests with multiple requests are not rolled back.  If every request did its own DB transaction, then the DB records added/updated by one page request could not be seen by another page request in the same test.

The solution found was to begin a DB Transaction on each of the application's DB Components, save the references to those $dbs in the module to rollback later, pass $dbs into the Yii2 $client, have the $this->client->startApp() function create a new $app and replace all of the DB components with the original ones that have active transactions.  I chose to leave the transactions at the Test level, instead of moving it up to the Suite, so that rollbacks occur sooner.  Then uncommitted DB changes won't carry over across tests when there are a large number of tests to run that have no dependencies.  This may cause a problem for multiple tests with DB data dependencies, but is not a requirement at this time.

Here are some links to public Github Gist files with working code:
1. Extended Codeception Yii2 Module:
https://gist.github.com/jkovacs618/50f171b709ab13f36437
2. Extended Codeception Yii2 Client:
https://gist.github.com/jkovacs618/31041c41a455374cddc8

Please look these over, see if there is a better solution to achieve this functionality, and let me know if I am missing something about functional testing.  Consider integrating this concept into the base Yii2 Module and Yii2 Client classes so that the extended classes are not needed.  Thank you.

**Comment by Ragazzo** [comment]
It was discussed long time ago with me and @qiangxue if we should start and rollback transactions for `Yii` testing , we agreed that it should be developer issue, since note this cases:

- developer can commit transactions due to application runtime;
- it becomes very hard to check what actually rolled back since see p1, and it can leave database or other persistence in inconsistent state.

Dont think that it should be implemented in `Yii2` module for `Codeception`, note that you always can implement your own helper and catch `_before / _after` events to make your own transaction or other cleanup

**Comment by cebe** [comment]
thanks for your comment, @Ragazzo, closing this then.

**Comment by jkovacs618** [comment]
@Ragazzo: The Codeception Yii2 Module already supports a config 'cleanup' flag (optional), and when set to true will start a Transaction.  This configuration flag is undocumented though.  I suppose this is only meant for Test function uses of $I->haveRecord() to create DB data and roll back that data, not the data produced in project code being tested.

I see how this feature should be up to the developer according to your points above, and not default functionality.  However, there is little information on best practices in testing with Yii2 and Codeception.  The Dbh module doesn't integrate well with Yii2, or is not well documented how to do so.  It doesn't seem too far fetched that the Yii2 Module could support this with optional configuration settings.

**Comment by Ragazzo** [comment]
> The Codeception Yii2 Module already supports a config 'cleanup' flag (optional), and when set to true will start a Transaction.

Yeah, i know, it was added long time ago by @DavertMik when he was using `Yii2`, yet i was against that change. Later it was ported ot other fw modules.

>However, there is little information on best practices in testing with Yii2 and Codeception. 

yes , my fault , i am currnetly a little bit busy , but i will try to add more docs before end of January.

>The Dbh module doesn't integrate well with Yii2, or is not well documented how to do so

The point here is that you should use fixtures that are `Yii2` feature, see how they are used in `FixtureHelper` in `yii2-avanced`. With fixtures and `cests` if neeed it becomes very easy to manipulate for cleanup, since each fixture actually knows what it should cleanup and you dont need to worry about inconsistencies.
