### ISSUE TITLE
UrlManager regression for unspecified GET parameters in pretty urls?

### ISSUE THREAD

**Issue by web-melt** [yiisoft/yii2#6866]
In Yii 1.1  one could create a route and parameters not explicitly specified in the route could still be attached to the URL in path format.

Config Example (1.1):

    'urlManager'=>array(
        'urlFormat'=>'path',
        'rules'=>array(
            '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
        ),
        'showScriptName' => false,
    ),

This made it possible to add as many GET parameters (Format: paramName/value) 
to the URL w/o specifying their parameter names upfront in the route.

Ex.
controllerName/actionName/foo/bar would result in

    echo $_GET['foo'];  #bar

In Yii2 that feature seems to be missing, instead an error is thrown:

>No matching URL rules. Using default URL parsing logic.
>Route requested: 'controllerName/actionName/foo/bar
>exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "controllerName/actionName/foo/bar".

Was this feature dropped or is there an alternative way to achieving the same result?

General Info:
PHP 5.4.36
Yii 2.0.2

**Comment by cebe** [comment]
this feature is not implemented in yii2, see #2047

**Comment by mezlad** [comment]
Why close this when a lot of developers who are comfortable with this feature from yii 1.1 is missing in yii2?
