### ISSUE TITLE
Provide parent [[activeCssClass]] with no visible childrens

### ISSUE THREAD

**Issue by RaSeR** [yiisoft/yii2#6868]
I have Menu::widget(), with one level. I want to have [[activeCssClass]] on them even if i have not only one route to determine it is active. For example routes:
```php
[
'news' => 'news/index',
'news/<category>' => 'news/category',
'news/<category>/<slug>' => 'news/view',
],
```
They are should set menu item 'Articles' as 'active' without having submenus.

How can i do this or its impossible for now?

**Comment by cebe** [comment]
> even if i have not only one route to determine it is active

what does that mean?

> They are should set menu item 'Articles' as 'active' without having submenus.

You did not show menu item 'Articles' in your example code!?

**Comment by RaSeR** [comment]
```php
$menu = [
                    'items' => [
                            ['label' => 'Main page', 'url' => Yii::$app->homeUrl],
                            ['label' => 'Articles', 'url' => ['/news/news/index'], 'items' => ['label' => '1', 'url' => ['/news/news/view']], ['label' => '2', 'url' => ['/news/news/category']]],
                        ],
'submenuTemplate' => null,
                        'activateParents' => true,
                        'labelTemplate' => '<span>{label}</span>',
                        'options' => [
                            'id' => 'nav',
                            'class' => 'right side-nav grey-text'
                        ]
                    ];
                    echo Menu::widget($menu);
```

so i used 
```php
'submenuTemplate' => null,
```
to keep them in menu array, but not render them on page. cause if i set visible => false it's unset from array. is it good?
i wanted ability to have an array of routes that determinate menu item as active, like:
```php
'items' => [
['label' => 'Articles', 'url' => ['/news/news/index'], 'routes' => ['/news/news/index', '/news/news/view']]
]
```
sorry for bad language

**Comment by RaSeR** [comment]
Any info?

**Comment by lynicidn** [comment]
may be set `activeCssClass` as 'child_item_hide'

**Comment by cebe** [comment]
Looks like you only want to mark an item as active on different condition than the default.
You can do this by setting `active` option yourself, e.g.:

```php
'active' => Yii::$app->requestedRoute == 'news/news/index' || Yii::$app->requestedRoute == 'news/news/view' || ...,
```

**Comment by RaSeR** [comment]
@cebe okay, thanks.
