### ISSUE TITLE
Feature request: ActiveRecord::findEach()

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#6874]
Find all is very useful and it gets the job done but its sub optimal and requires a lot of memory space.

Internally it loads all the reponses on and pour them as a big array.

I see it on three possible ways to do it

1. Create a method called `findEach` that imitates the behaviour of `findByCondition` and turns into a shortcut of `find()->andWhere($condition)->each()`

2. Create `ActiveRecord::RETRIEVE_ALL`, `ActiveRecord::RETRIEVE_ONE` and `ActiveRecord::RETRIEVE_EACH` and modify `findByCondition($condition, $one)` method to `findByCondition($condition, $retrieve)` with the last parameter having the value of one of the constants created before.

3. Create a magic method or a set of methods, in a way that `findXyz($condition)` internally behaves like `find()->andWhere($condition)->xyz()` we can rewrite the method `findByCondition($condition, $retrieve)` but instead let the last param be the method we are gona use to retrieve the data.

The last solution is the best in my opinion since it allows more flexibility and more shortcuts like `findScalar`

**Comment by qiangxue** [comment]
We do not have plan to introduce this and other similar shortcut methods for the following reasons:

* `findOne()` is provided because it is very commonly used. For completeness, `findAll()` is also provided.
* `findXyz()` is not complete functionally (e.g. you can't specify `order by`, etc.)
* `findEach()` is far less commonly used than `findOne()`
* too many shortcut methods increase the learning curve

**Comment by Faryshta** [comment]
i think its a nice to have feature. shortcuts are not complete functional i agree, they are shortcuts not the full funciton.

I can submit a patch and we can contemplate to include it for 2.1 as a new feature, by then new features will be easier to learn

**Comment by cebe** [comment]
adding a new function here will add no value because it is already possible to achieve what you want with existing methods. adding more ways to do the same thing will complicate the API.
