### ISSUE TITLE
RBAC migration SQLServer cascade problem

### ISSUE THREAD

**Issue by hardsetting** [yiisoft/yii2#6876]
When I try to run the auto-generated SQLServer script for RBAC migration, SQLServer gives me the following error:

```
-- The auto generated migration script
create table [auth_item_child]
(
   [parent]               varchar(64) not null,
   [child]                varchar(64) not null,
   primary key ([parent],[child]),
   foreign key ([parent]) references [auth_item] ([name]) on delete cascade on update cascade,
   foreign key ([child]) references [auth_item] ([name]) on delete cascade on update cascade
);
```
```
The error:
Introducing FOREIGN KEY constraint 'FK__auth__child__7D0E9093' on table 'auth_item_child' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
```

We figured the reason for such error could be that SQLServer takes in account the case in which an auth_item is parent of itself, so updating/deleting the auth_item leads to 2 different cascade paths.
Is my assumption correct?

Is there any possible solution other than deleting one of the on update/delete cascade? (not really applicable)

Thank you in advance

**Comment by undefinedstudio** [comment]
Also interested in this one.
I see that the framework has methods to deal with cascade behaviors with databases that do not support cascade operations. Maybe that can be a solution?

**Comment by williamyiu** [comment]
any updates?

**Comment by samdark** [comment]
I don't have MSSQL to deal with it. Anyone could help?

**Comment by nineinchnick** [comment]
You can probably use [sqlfiddle](http://sqlfiddle.com/#!6).

**Comment by fourteenmeister** [comment]
It seems one solution - triggers
[stackoverflow](http://stackoverflow.com/questions/5100525/sql-server-2008-multiple-cascading-fks-do-i-need-a-trigger)

**Comment by thejahweh** [comment]
Tested on SQL Server 2014 and it works :tada:

**Comment by samdark** [comment]
@thejahweh, @fourteenmeister could you update it so it could be applied to latest master code?
