### ISSUE TITLE
Bad pemission on init

### ISSUE THREAD

**Issue by germanigortcev** [yiisoft/yii2#6878]
ENV - DEV 
Yii 2.0.2
PHP 5.6
Advanced template

Mailer
'useFileTransport' => true or false

Have error
mkdir - Permission denied

Permission denied for directory backend/runtime/debug/mail

Why?
When we ran init the script set permission 'chmod 0777 backend/runtime' but it's not recursive and directory backend/runtime/debug.

**Comment by cebe** [comment]
you should run init before doing anything else so runtime should be empty at that point...

**Comment by klimov-paul** [comment]
Seems to be incorrect usage.
