### ISSUE TITLE
[ENH] Model global errors 

### ISSUE THREAD

**Issue by lucianobaraglia** [yiisoft/yii2#6879]
Hi people!
What do you guys think about introducing the concept of "global errors" in the `Model` class.
Sometimes I need to run some validation (in a form) that doesn't feet with any model attribute showed.
I want to show the error in screen, and I know I could check it in the controller and show it using a flash message, but I think it would be more natural to use something like `symfony 1.4` does (for example):

View file:
```php
<?php $form = ActiveForm::begin(); ?>

<?php foreach ($model->globalErrors as $error): ?>
    <div class="global-error"><?= $error ?></div>
<?php endforeach; >

// rest of the form
// ...
// ...

```

and/or simply provide a way out of the box with simple markup:

```php
<?= $model->displayGlobalErrors() ?>
```

Thanks for your time! :smiley:

**Comment by cebe** [comment]
Can you give an example for a global error?

**Comment by lucianobaraglia** [comment]
@cebe ok!
For example, I have a model with 3 `attributes`: `a`, `b`, and `c`, and its form that has 2 inputs: `b` and `c`.
So in the screen I only show `b` and `c`, but let's say when I validate the input I encounter an error referred to `a` (for any reason).
Then I could show the error with a flash message, but if we have `globalErrors` it would be simpler and more transparent.

Maybe I am complicating the explanation...

A real case I have right now:
I have a `PrintRequest` model with a related model collection `PrintRequestFile[]`.
In the last step of the print-request stuff, the comerce has to check a `checkbox` representing the ID of each related `PrintRequestFile` (showing the original name of the uploaded files by the user).
Then I run a validation in my `form model class` checking that the comerce checked ALL checkboxes, and don't want to show an error below each file name, but show only one error in the top of the form...

Sorry if it's hard to understand because I explain it bad...

**Comment by klimov-paul** [comment]
You can invoke `Model::addError()` for any attribute including not actually existing ones:
```php
$model->addError('unexistingAttribute', 'Some error');
$model->addError('global', 'Some error');
```
and then get them for your flash message:
```php
$model->getFirstError('unexistingAttribute');
$model->getFirstError('global');
```

Also there is suc thing as `Html::errorSummary()` and `ActiveForm::errorSummary()`, which can display all errors at once no matter if there is an input for particular attribute or there is not.

Thus, I can't see any reason to introduce any special 'global' errors.

**Comment by lucianobaraglia** [comment]
@klimov-paul thanks, didn't know that!
It's kinda weird (for me) adding errors to no existing attributes, but I guess it will work! :smiley:
