### ISSUE TITLE
Why is ErrorHandler->logException() protected?

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2#6883]
Hi.

I have this case when I want to silently ignore an external component of the application like sphinxsearch. 
In my model search() I call sphinx Query but I want to catch any exception, **log** it and return an empty result set instead of an exception.
Currently this cannot be done without extending the ErrorHandler and I think this is an overkill..

Thank you for your great work!
Razvan

**Comment by samdark** [comment]
Can't you wrap it with

```php
try {
  // your code
} catch (Exception $e) {
  // log exception
}
```

?

**Comment by razvanphp** [comment]
Of course that's what I did, but I can't log the exception using the ErrorHandler in the catch block because of the protected method. Sorry if that was not clear from my post.

**Comment by samdark** [comment]
Aha. Makes sense. @yiisoft/core-developers opinions?
