### ISSUE TITLE
Change doc to Optimistic Locking guide inActiveRecord.

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#6884]
Hmm, 
I open update form in IE and Chrome.

# **IE**
![image](https://cloud.githubusercontent.com/assets/874234/5772495/7bb7d686-9d64-11e4-8bd0-dce4db91276d.png)

# **Chrome**
![image](https://cloud.githubusercontent.com/assets/874234/5772501/949413ea-9d64-11e4-8090-590ab81c94ce.png)

 And I tried same https://github.com/yiisoft/yii2/issues/6311#issue-50420639 and I get 

For IE: 
![image](https://cloud.githubusercontent.com/assets/874234/5772512/ee7383a0-9d64-11e4-9e85-5e7b7e403084.png)

```
UPDATE `project` SET `status`=1, `comments`=NULL, `updated_at`='1421390688', `updatedVersion`='17' WHERE (`id`=157) AND (`updatedVersion`='16')
```

For Chrome: 
![image](https://cloud.githubusercontent.com/assets/874234/5772540/493c30de-9d65-11e4-9b36-4197961e8a70.png)

```
UPDATE `project` SET `status`=5, `comments`='test', `updated_at`='1421390849', `updatedVersion`='18' WHERE (`id`=157) AND (`updatedVersion`='17')
```

There are no collisions.

**Comment by githubjeka** [comment]
Omg I skrinshot it so much. I doesn't add `'updatedVersion'], 'required'],` because it doesn't described in https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#optimistic-locks , but described  in comment for method. Please add info to guide.

**Comment by samdark** [comment]
@githubjeka can you help with a pull request? I'm not sure how to word it and where it's suitable to add it. Thanks.

**Comment by githubjeka** [comment]
It fixed. 
https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#optimistic-locks- (item 3)
> In the Web form that takes user inputs, add a hidden field to store the current version number of the row being updated. Be sure your version attribute has input validation rules and validates successfully.
