### ISSUE TITLE
Extraparams (additional variables in widget) in gridview?

### ISSUE THREAD

**Issue by manojsinghadha** [yiisoft/yii2#6887]
How to use extraparams (additional variables in widget) in gridview?

**Comment by cebe** [comment]
I do not understand the question, please elaborate more.

**Comment by manojsinghadha** [comment]
additional variables means that are not part of dataProvider object, 
i needs to pass some custom variables in gridview to process/show in DataColumns area

**Comment by samdark** [comment]
It's possible by using `use` in anonymous functions: http://php.net/manual/en/functions.anonymous.php#example-186

**Comment by manojsinghadha** [comment]
Thanks
