### ISSUE TITLE
HtmlResponseFormatter always forcing content type

### ISSUE THREAD

**Issue by Blizzke** [yiisoft/yii2#6889]
In the docs it says that the Html output format will set the content type to text/html *if not already set* but yet in https://github.com/yiisoft/yii2/blob/master/framework/web/HtmlResponseFormatter.php#L37 the `getHeaders()->set()`-function is used instead of the expected `setDefault`? Small oversight?

**Comment by qiangxue** [comment]
Where did you see this doc `Html output format will set the content type to text/html if not already set`?
Using `set()` is correct because that's why you use `HtmlResponseFormatter`.

**Comment by Blizzke** [comment]
[Here](http://www.yiiframework.com/doc-2.0/yii-web-response.html#$format-detail):
> FORMAT_HTML: the data will be treated as the response content without any conversion. The "Content-Type" header will set as "text/html" if it is not set previously.
So it's either the docs that are wrong or the code :)

I ended up using `FORMAT_RAW` and setting the content-type myself, the documentation just implied you could use HTML..
