### ISSUE TITLE
Deploy: The use statement with non-compound name 'Yii' has no effect

### ISSUE THREAD

**Issue by dirtyman** [yiisoft/yii2#6897]
I've no problems testing my application in __localhost__.
When I tried to get my webapp working in a __shared host__ I always get the error exception in the __title__. 

My code:
```php
<?php
use Yii;
....
?>

html code
```
I know that this is redundant, but I like to see what I'm _using_ in the file. 

The framework is using this too, in some files.
But __never__ in a php file with html code (e.g. yii basic application).

There's a specific reason for this? (Or why in the world I get this error (which breaks my app) in the server but not in localhost).

**Comment by cebe** [comment]
`use Yii;` is necessary when you want to use the name `Yii` inside of a namespace, this does not make sense when used in a file that has no namespace.

**Comment by dirtyman** [comment]
Thanks for the fast reply!

But this _[uses](https://github.com/yiisoft/yii2-app-basic/blob/master/views/site/contact.php#L16)_ are necessary because you want to use them.
If not, why just Yii doesn't make sense in a view file?

~ Do you know why I don't get this error in my localhost? (php config?)

**Comment by suralc** [comment]
`Yii` is in the global namespace. The `use` keyword is used to import(well, alias) a class into the current namespace. PHP will warn you (or fatal with certain names) if you try to import a global class into the global namespace for example in a view context (which doesn't make sense):

Example:
http://3v4l.org/K0D61#v530

**Comment by cebe** [comment]
> ~ Do you know why I don't get this error in my localhost? (php config?)

you may have set error_reporting to a lower level, it is recommended to show all errors to write clean code and do not get surprised when something behaves weird just because you did not see the warning.

**Comment by dirtyman** [comment]
Really, really thank for both of you!

@suralc nice example, I get it now.
@cebe I added all possible errors now.
