### ISSUE TITLE
Combining assets from console 

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#6899]
First of all really great work on creating the `asset` utility for combining assets from console. Congrats to the development team who thought through and built this. Though, it is mentioned in the docs that `grunt` can be used to achieve the same, I find the yii inbuilt `asset` command to be even better. Its because it integrates and parses Yii AssetBundles (and its dependent asset files) automatically unlike `grunt` and can be thus used multiple times in the development cycle to test and form the right assetbundle groups for production.

One enhancement that I wish to suggest or explore. Its about giving an option to eliminate sub directories after processing and retaining only those that are used in URL rewriting (especially for the CSS minifier). 
- The URL rewrite does happen - but if we could have an option where we could delete all the generated asset files and sub directories and only retain the directories used in CSS URL (e.g. `font` / `img` folders). 
- If we could have another option to automatically merge the above folders (e.g. combine folder named `img` used in 2 different asset files - and overwrite if the user chooses to with the command).

**Comment by TerraSkye** [comment]
the problem you would face here is if the images have the same name?

**Comment by kartik-v** [comment]
Yes... but its an option (a parameter to `asset` command) -- which I recommend that can be set by the developer. He can choose whether he wishes to merge and overwrite. Else, the the folders are created like `img1`, `img2` etc.

**Comment by klimov-paul** [comment]
Rejected: overcomplication of the code for such feature is not justified.
