### ISSUE TITLE
Ivalid captcha when open two or more forms

### ISSUE THREAD

**Issue by mohammadhosain** [yiisoft/yii2#6900]
When I open two or more forms that have captcha, if one of forms submited, other forms captcha are invalid.

**Comment by lynicidn** [comment]
it expected behavior https://github.com/yiisoft/yii2/blob/master/framework/captcha/CaptchaAction.php#L189

**Comment by cebe** [comment]
@mohammadhosain if you want to use independent captchas in different forms you need to create one captcha action for each form.
