### ISSUE TITLE
Remove core js loaded twice

### ISSUE THREAD

**Issue by MUTOgen** [yiisoft/yii2#6902]
Hello!
Is there any way to remove js script from renderAjax, which is already loaded?

First of all I mean this:
```
<script src="/assets/.../jquery.js"></script>
<script src="/assets/.../yii.js"></script>
```

In Yii1 i could play with Yii::app()->clientScript->scriptMap['jquery.js'] = false;
But what about right way with bundles? Maybe there is an option to avoid this globally in the app?

**Comment by pana1990** [comment]
You should use foro for this questions.

Try : 

'components' => [
        'assetManager' => [
            'bundles' => [
                'yii\web\JqueryAsset' => false,
            ],
        ],
    ],

See  https://github.com/yiisoft/yii2/blob/master/docs/guide/structure-assets.md for more details.

**Comment by MUTOgen** [comment]
Ok, thanks. I did like this

```
Yii::$app->assetManager->bundles['yii\web\JqueryAsset'] = false;
Yii::$app->assetManager->bundles['yii\web\YiiAsset'] = false;
```
And it works now

**Comment by llfm** [comment]
The js files [aren't](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L305) loaded twice (or more).
