### ISSUE TITLE
Doc request: please document a strategy to handle migrations without console access

### ISSUE THREAD

**Issue by realtebo** [yiisoft/yii2#6904]
A lot of use, included myself, one day or other must develop a webapp in a shared host situatio.

We're good enough to install every thing,the code, but, what is the preferred strategy to create migrations in development environment (whre you have console access and can simply apply them in classic way) and then deploy into a server where you cannot access via console / ssh?

I'm trying since one whole week to use \yii\console\controllers\MigrationController from inside a standard webapp action (advanced template). I'm of course not able to do this. 

Help we all, please, add someting to the official doc or at least a step-by-step newbie-ready post into the wiki.

Note: i cannot run exec and similar from php, them has been disabled from server admin.

**Comment by cebe** [comment]
You could try doing something like this: https://github.com/yiisoft/yii2/issues/6853

**Comment by realtebo** [comment]
I'm gently requesting a working example. I'm really not able to understand what must I try. You've linked me an issue, so, if it's not working, why moust I try it?

Also, the user is trying to run a commabd action inside a command action, or something of similar.

I need to invocke a standard web action and execute the full migration code, up or down. 

Please, this situation, a stupid shared host, it's so common. Help us giving us a working example. Please !

**Comment by realtebo** [comment]
About this: https://github.com/stepanselyuk
I'm asking to @stepanselyuk  how to use his helper in a web controller action

**Comment by stepanselyuk** [comment]
@realtebo please see https://gist.github.com/stepanselyuk/c7b3ca03755eb5788ce5 - `ConsoleAppHelper::runActionOld` this method without using `exec`, but as I've figured out, it work only cgi-like modes, ex. `fcgid`. But not working with in systems where is php as Apache module (don't know why). So I use `ConsoleAppHelper::runAction` with `exec`.

**Comment by cebe** [comment]
@realtebo it is currently not supported but I linked that issue because there something similar has been tried. By defining the missing constants it may already work but you have to try yourself. We'll look into this when we find the time for it.

**Comment by cebe** [comment]
when running a console application in web context at least the following things have to be considered:

- keep the web app instance as creating the console app will overwrite `Yii::$app`.
- the console application will register its own errror handler and overwrite the previously registered one
- if a logger is enabled in console application, this may affect what `Yii::getLogger()` refers to
- the `@app`, and `@runtime` alias will be overwritten
- same for `@vendor`, `@bower`, `@npm` but these are usually equal.
- `date_default_timezone_set()` will be called if console app has timezone configured.

**Comment by machour** [comment]
Is it fine to mention https://github.com/samdark/yii2-webshell in the guide? (given that it's not under yiisoft/)

**Comment by samdark** [comment]
Yes. That's OK.

**Comment by samdark** [comment]
Proven extensions could be mentioned freely. Mine is considered to be OK despite having some issues.
