### ISSUE TITLE
Fragment caching conflicting with assets publishing

### ISSUE THREAD

**Issue by ThePeach** [yiisoft/yii2#6905]
Occurred to me just yesterday and had to do a bit of trial and error to find out what was wrong and thought it was worth reporting it:

I've got two templates that are outputted in the `<head>` portion of my main layout.
These two templates use fragment caching (they're basically Open Graph meta tags).
The rest of the page does not use any other kind of caching.
If I render the templates (within the `<head>`) _after_ `<?php $this->head() ?>` no asset is going to be included in the `<head>`, 
if I render _before_ it, no problems whatsoever.

**Comment by dynasource** [comment]
please take in mind that Assets have to be published at all times (unless you also cache the rendered output). So if caching is going on, asset published will of course be affected.
