### ISSUE TITLE
loadMultiple for new rows

### ISSUE THREAD

**Issue by harlangray** [yiisoft/yii2#6906]
I'm having a problem with 
Model::loadMultiple($items, Yii::$app->request->post())
assume I am posting 5 new items here (5 rows in view). I create 5 new models ($items).
If my POST is not indexed from zero (0,1,2,3,4), loadMultiple does not load the items properly to $items.

**Comment by cebe** [comment]
this is expected, you have to create models so that their keys match what is in POST. This is to ensure correct changes on update where you could index the input fields using the models primary key.

**Comment by harlangray** [comment]
thanks.
