### ISSUE TITLE
Bad Request (#400) - Unable to verify your data submission

### ISSUE THREAD

**Issue by sredXNY** [yiisoft/yii2#6907]
HI, while I'm trying to upload multiples files I got this error, I followed this guide:" http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html " I got exactly the same thing but still the same error, even when I have "  <?= Html::csrfMetaTags() ?>" in the main layout

I disabled csrf validation but nothing happened. in the controller I have:

public function actionUpload()    {
		
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstances($model, 'file');
            
            if ($model->file && $model->validate()) {
                foreach ($model->file as $file) {
                    $file->saveAs('uploads/' . $file->baseName . '.' . $file->extension);
                }
            }
        }

        return $this->render('upload', ['model' => $model]);
    }

//==================in The View================================
 <?php
$form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);
?>

<?= $form->field($model, 'file[]')->fileInput(['multiple' => true]) ?>

    <button>Submit</button>

<?php ActiveForm::end(); ?>

//===================in The Model=========================
class UploadForm extends Model
{
    /**
     * @var UploadedFile|Null file attribute
     */
    public $file;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['file'], 'file', 'maxFiles' => 10], // <--- here!
        ];
    }
}

**Comment by BlindGenius** [comment]
I have just encountered this issue too.
But this seems not to be related to the max files, but more multiple file upload
testing scenario
1) Uploading 1 File works fine, POST data includes _csrf and form model data. body includes required file data.
2) multiple  files upload from the same form fails with 400 error, Post data missing _csrf token AND model data.  Body does contain multipart file data including _csrf token but it is different to the session _csrf token. 

Used Yii debugger to find this info.
Hope this helps find the issue

As a workaround limit uploads to 1 at a time ;(

**Comment by sredXNY** [comment]
exactly, I got the same too, single uploads works fine, but not when I changed the code to work with mutiples files

**Comment by pasmanp** [comment]
i have this issue after uploading single file >8Mb.

**Comment by dmitriy-krista** [comment]
You all should check your php and web server configs. Make sure your limits are correct.
php options: **post_max_size, upload_max_filesize, max_input_time**
web server: nginx - **client_max_body_size** , apache - **LimitRequestBody**
if you dont exceed the limits, you should not receive the bad request.

**Comment by yonifine** [comment]
The same issue was happening for me when i upload one file. the issue was related to file size. i changed the settings as per @dmitriy-krista suggestion and it worked. thanks

**Comment by samdark** [comment]
Yep, seems to be issue with trimming POST. Can't be solved by framework.

**Comment by arpyhd** [comment]
I found that is mising a / in the end of input , ex:
    <input type="hidden" name="_csrf" value="bWs1ZlJSeGYiHG0xNThVNgBYBzY8FAI5PS4CVn8lJzMeIkAgKgU0Ig==">
    working input is:
    <input type="hidden" name="_csrf" value="bWs1ZlJSeGYiHG0xNThVNgBYBzY8FAI5PS4CVn8lJzMeIkAgKgU0Ig==" /> in my
    case:
    I modified yiisoft/yii2/helpers/BaseHtml
    public static function tag($name, $content = '', $options = [])
    {
        if ($name === null || $name === false) {
            return $content;
        }
		if ($name=="input") {$html = "<$name" . static::renderTagAttributes($options) . '/>';}
		else {$html = "<$name" . static::renderTagAttributes($options) . '>';      }
		
        return isset(static::$voidElements[strtolower($name)]) ? $html : "$html$content</$name>";
    }

**Comment by narmail** [comment]
This issue is due to post_max_size = 8M in php.ini file.You can increase it to solve the issue
