### ISSUE TITLE
Problem With Pjax

### ISSUE THREAD

**Issue by nicovicz** [yiisoft/yii2#6910]
hey guys, i have problem with pjax. Is this bug?

// in controller
```php
public function actionIndex()
{
  return $this->render('index');
}

public function actionView()
{
  return $this->render('view');
}
````
in view index.php
```php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

Pjax::begin(['id'=>'pjax-container']);

echo Html::a('To Index', Url::to(['/site/index']), [
	'data-pjax'=>'1',
]);

echo Html::a('To View', Url::to(['/site/view']), [
	'data-pjax'=>'1',
]);
Pjax::end();
```
if you click To Index link, pjax will work (not refreshing page)
if you click To View link, pjax will NOT work (refreshing page)

but if the actionView use $this->renderPartial(), it will work (not refreshing page) but the javascript will not work.
any solution?
thx

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for bug reports.

**Comment by derekisbusy** [comment]
Use `$this->renderAjax()` instead.
