### ISSUE TITLE
Yii2 advanced structure(need another application like frontend/backend)

### ISSUE THREAD

**Issue by marius1992** [yiisoft/yii2#6911]
I've started recently working with yii2. Using the basic app is easy but what I need to do now is to create an advanced template which has more than frontend and backend. I need it to also have midend and one more component(same as frontend/backend folders).I have been trying to search on the internet but I did not find anything usefull.

Thanks for your help,
Marius

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for issues and feature requests.
