### ISSUE TITLE
twig and breadcrumbs. Problem with url

### ISSUE THREAD

**Issue by nepster-web** [yiisoft/yii2#6912]
I use twig and breadcrumbs:
```
{% set breadcrumbsLinks = [
{
    'label': 'my label',
    'url': ['/controller/default/index'],
    },
    {
    'label': 'my label',
    'url': ['/controller/default/view'],
    }
] %}
```

It work. And I want add parameters to url:

```
{% set breadcrumbsLinks = [
{
    'label': 'my label',
    'url': ['/controller/default/index'],
    },
    {
    'label': 'my label',
    'url': ['/controller/default/view', {'id' : 1}],
    }
] %}
```
Breadcrumbs generate: /myurl?1[id]=1

I haven't found a way to solve this problem. Maybe it's a bug ?

**Comment by cebe** [comment]
The PHP equivalent for the last URL would be: `'url' => ['/controller/default/view', 'id' => 1],` so I guess the extra `{}` around id are wrong.

**Comment by nepster-web** [comment]
```'url': ['/matrix/default/index', 'id' : 1],```
An array element must be followed by a comma. Unexpected token "punctuation" of value ":" ("punctuation" expected with value ",") in "view.twig" at line 19

Maybe I tried all ways

**Comment by lynicidn** [comment]
it
`{{ path({'0': 'site/index', 'ud': '123'}) }}`
generate
`/site/index?ud=123 `

**Comment by nepster-web** [comment]
yes. this work. Thank you. 

But it is too difficult. Later to fix it ?

**Comment by lynicidn** [comment]
object should have key. It no problem.

**Comment by nepster-web** [comment]
I assumed that this array. Thank you again for info.
