### ISSUE TITLE
SluggableBehavior slug naming restrictions

### ISSUE THREAD

**Issue by a-komarev** [yiisoft/yii2#6916]
There is no way to restrict to name slugs as controller actions. If model title will be called as it's action - you wouldn't have an access to it.

urlManager config:
```
'urlManager' => [
    'class' => 'yii\web\UrlManager',
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'rules'=> [
        ['pattern'=>'post', 'route'=>'post/index'],
        ['pattern'=>'post/create', 'route'=>'post/create'],
        ['pattern'=>'post/<slug>', 'route'=>'post/view-by-slug'],
        ['pattern'=>'post/update/<slug>', 'route'=>'post/update-by-slug'],
    ]
],
```

For example if `$model->title = "Create"` we will get a slug `/post/create`. And right after post creation you will be redirected back to post creation :D
It's not critical, but what is a best way to solve it?
- Restrict in model using `rules()` method for `title` attribute
- Restrict in `SluggableBehavior` by adding additional option
- Always use mappings for controller with another name in urlManager (`/posts/<slug>`)

Any enhancement ideas?

**Comment by samdark** [comment]
I think restriction via model validation rules is the best way. I don't think it can be easily automated.
