### ISSUE TITLE
Should Pjax be always registering javascript?

### ISSUE THREAD

**Issue by nirvana-msu** [yiisoft/yii2#6917]
Spent quite a bit of time debugging an issue today. I was rendering a partial view in response to pjax request using `renderPartial()` and was surprised to see that some inline javascript was registered. Turned out this is because `Pjax` widget always executes `$view->endBody();` and other similar `View` methods. Sometimes you may want to handle javascript on your own, especially for ajax updates of complex `ListView` widgets. I think it would be useful if it was possible to choose whether javascript should be registered during pjax request or not, just like you can choose so by using `renderPartial()` / `renderAjax()` during a normal ajax request

**Comment by Alex-Code** [comment]
Are you registering the inline javascript?

You could move the `registerJs()` calls below the `Pjax` widget in the view as `Pjax` calls `Yii::$app->end();`

**Comment by nirvana-msu** [comment]
The problem is in the 3rd party code (widgets) that I do not have control of. They generate both inline javascript and register additional script files, which I ideally would like to avoid.

**Comment by nunomaduro** [comment]
I have the same problem. I use 3rd party code widgets and i would like to avoid register js for every case :s

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/jquery-pjax/pull/30

**Comment by nirvana-msu** [comment]
@SilverFire does it really fix this issue? I looked briefly through the commit / discussion, but it seems to be mostly related to the order of script execution. Whereas this issue is about having an option to avoiding loading scripts altogether. How does this patch help me achieve such a behaviour?

**Comment by SilverFire** [comment]
@nirvana-msu Sorry, it seems I didn't get you idea correctly from the first read.

The patch does the following:
 - allows JS loading from `<script src="...">` tags in PJAX response
 - cares about loading of the those scripts only one time
 - manages the order of load to prevent `<script>...</script>` execution before the loading of dependent JS sources

**Comment by SilverFire** [comment]
@nirvana-msu  Following best practices, inline scripts should only initialize plugins, loaded in separated resource files and affect only the block, you load dynamically.
It's not OK to render in AJAX response something like `$(document).on('click', 'a', function () { alert(1); });`, you know.

I'll fix the problem with multiple loading of scripts, but I think we should do nothing special to inline JS - it should be just executed.

**Comment by SilverFire** [comment]
Since now JavaScripts load through PJAX will be processed by `jQuery.ajaxPrefiler` https://github.com/yiisoft/jquery-pjax/commit/7a47df7b36d1031fbd576929e040ebab588b207b
Could you check, please?
