### ISSUE TITLE
Wrong namespace in advanced app backend unit test classes

### ISSUE THREAD

**Issue by ivokund** [yiisoft/yii2#6919]
Sorry if I'm mistaken (haven't done anything test-related in a while now), but shouldn't these be in a namespace `tests\codeception\backend\unit`?

https://github.com/yiisoft/yii2-app-advanced/blob/master/tests/codeception/backend/unit/TestCase.php
https://github.com/yiisoft/yii2-app-advanced/blob/master/tests/codeception/backend/unit/DbTestCase.php

**Comment by Ragazzo** [comment]
can be moved for consistency however works now since there is a `backend` namespace

**Comment by ivokund** [comment]
There is a `backend` namespace, but the files I mentioned are not in namespaces that correspond to their location. That means that autoload will not be able to find them.

**Comment by Ragazzo** [comment]
`yii2 - advanced` is currently being used on travis . Feel free to submit PR
