### ISSUE TITLE
yii\grid\GridView: support filters with multiselect

### ISSUE THREAD

**Issue by katzz0** [yiisoft/yii2#6923]
I tried to use multi select and got a weird results. You can try select with simple multi attribute or take for example this jQuery plugin https://select2.github.io/ The filter mark 'selected' some option and ignore others options. I found  some funny code after examination yii.gridView.js. Method applyFilter construct data object and then use it for form submission. But if we have some values with identical names then the previous value overrides others.

Alternatively we can use data as array of objects.

<pre><code>
applyFilter: function () {
            var $grid = $(this), event;
            var settings = gridData[$grid.prop('id')].settings;
            var data = {};
            $.each($(settings.filterSelector).serializeArray(), function () {
                data[this.name] = this.value;
            });

            $.each(yii.getQueryParams(settings.filterUrl), function (name, value) {
                if (data[name] === undefined) {
                    data[name] = value;
                }
            });

            var pos = settings.filterUrl.indexOf('?');
            var url = pos < 0 ? settings.filterUrl : settings.filterUrl.substring(0, pos);

            $grid.find('form.gridview-filter-form').remove();
            var $form = $('<form action="' + url + '" method="get" class="gridview-filter-form" style="display:none" data-pjax></form>').appendTo($grid);
            $.each(data, function (name, value) {
                $form.append($('<input type="hidden" name="t" value="" />').attr('name', name).val(value));
            });
            
            event = $.Event(gridEvents.beforeFilter);
            $grid.trigger(event);
            if (event.result === false) {
                return;
            }

            $form.submit();
            
            $grid.trigger(gridEvents.afterFilter);
        }
</code></pre>

**Comment by Faryshta** [comment]
i suggested a similar enhancement on #7014

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/d3cfb87ba67a328d197d1a9e52dbb12a7bf8476b, #10302
