### ISSUE TITLE
yii2-twig url function works uncorrect.

### ISSUE THREAD

**Issue by 3jIo** [yiisoft/yii2#6924]
I tried to get absolute url by my schema, but it doesn't work. It happened after update yii 2.0.1 to 2.0.2.

**Comment by Alex-Code** [comment]
Can you provide some samples?
Expected output vs Actual output.

**Comment by 3jIo** [comment]
Example:
I use mdmsoft/admin. And I have CategoriesManagerController and i have configs when i map my controller:    
     'modules' => [
        'admin' => [
            'class' => 'mdm\admin\Module',
            'layout' => 'left-menu',
            'controllerMap' => [
                'categories' =>  'backend\controllers\admin\CategoriesManagerController',
            ],
        ],
And when i perform 
    $create = Url::to('categories/create', true);
whitin the controller (in test action) it return 'http://localhost/categories/create' but before update it return absolute url.

**Comment by samdark** [comment]
`http://localhost/categories/create` is absolute URL, isn't it?

**Comment by 3jIo** [comment]
Yes. But i mean that it return uncorrect url. Before update was http://localhost/american_eshop/yii-application/backend/web/admin/categories/create after update become http://localhost/categories/create.  
In russian: То есть функция не возвращает путь по маршруту categories/create а просто конкатенирует localhost с маршрутом.

**Comment by samdark** [comment]
It was never working otherwise. Use it properly:

```php
Url::to(['categories/create'], true);
```

**Comment by 3jIo** [comment]
Maybe it that but twig compile {{ use('categories/create', true) }} to Url::to('categories/create', true). (twig 2.0.2)

**Comment by 3jIo** [comment]
Exactly $this->env->getExtension('yii2-twig')->url("categories/create")

**Comment by samdark** [comment]
OK, will check twig.

**Comment by 3jIo** [comment]
Sorry for deleting comments. I thought that i did something wrong.... thanks

**Comment by 3jIo** [comment]
Maybe it fix the problem?
filde yii2-twig\Extension.php

 public function url($path, $args = [])
    {
        if ($args !== []) {
            $path = array_merge([$path], $args);
        }
        return Url::to($path, true);
    }

rewrite to 

public function url($path, $args = [])
    {
        if ($args !== []) {
            $path = array_merge([$path], $args);
        }
        return Url::to(array($path), true);
    }

**Comment by Alex-Code** [comment]
Won't that create `[['/path']]`

Should it be,
```
public function url($path, $args = [])
{
    $path = (array)$path;
    if ($args !== []) {
        $path = array_merge($path, $args);
    }
    return Url::to($path, true);
}
```

**Comment by 3jIo** [comment]
Fixed. Yes, Alex-Code's code are more elegantly.

**Comment by samdark** [comment]
It's because https://github.com/yiisoft/yii2/issues/6464

**Comment by samdark** [comment]
Not sure how to solve it because we can't really tell if it's path or route.

**Comment by samdark** [comment]
I don't see a way to support both. Prefer #6494 to stay solved rather than reverting it.

**Comment by tanakahisateru** [comment]
@samdark Please reopen this issue to review my PR #7624.
