### ISSUE TITLE
Class JqueryAsset does not exist

### ISSUE THREAD

**Issue by saidbakr** [yiisoft/yii2#6925]
Applying the following code regarded in the document to register an external Js file in the advanced application template frontend contact view of yii 2.0.2 leads to this error: "Class JqueryAsset does not exist"

```
$this->registerJsFile('http://example.com/js/main.js', ['depends' => [JqueryAsset::className()]]);
```

**Comment by saidbakr** [comment]
The regarded document path: docs/guide/output-client-scripts.md

**Comment by samdark** [comment]
It should be imported using `use` statement. See PHP namespaces: http://php.net/manual/en/language.namespaces.basics.php

**Comment by saidbakr** [comment]
I'm talking about uncompleted information in the official documentation, am I not? @samdark

**Comment by cebe** [comment]
This is quite basic PHP knowledge which is implied by the guide. You have to know PHP to work with yii.

**Comment by saidbakr** [comment]
@cebe  Do you think that it is suitable to declare namespace `yii\web` in the view `frontend\views\site\contact.php`? What is if the view needed another class from another namespace? This is a solution.

Another solution is to use it `use yii\web\JqueryAsset` in the view file i.e contact.php.

What I mean "It is named a guide" the guide should expect and respect all the levels of users. It should offers hints and snippets ready to use. Indeed, you are talking here about languages basics, right, but this is not an independent basic point, finally, it depends on a path or a way should be defined by the guide. For example, take in count any guide that describes a usage of a Windows application, that guide may repeat steps known as basics for any Windows user. i.e Click on Start Button, type application Name, hit Enter and so on.

**Comment by saidbakr** [comment]
To clarify the issue, I, mainly, report an issue of the documentation not in the framework source.

**Comment by samdark** [comment]
I'll see what I can do to make it clear in the example.
