### ISSUE TITLE
Yii::$app->formatter->asTimestamp

### ISSUE THREAD

**Issue by Yarisrespect** [yiisoft/yii2#6926]
$date = "01.01.15" // d.m.y
Yii::$app->formatter->asTimestamp($date);
works incorrectly, because it try to create DateTime object from format Y-m-d H:i:s!
How change this format?
Maybe add parameter $format?
public function asTimestamp($value, $fromFormat='Y-m-d H:i:s' ) {
 ....
}

**Comment by cebe** [comment]
formatter is for displaying dates that are already in machine readable form, if you want to process input you can use DateValidator.

**Comment by Yarisrespect** [comment]
How convert date (d.m.y) to UNIX, use php func date() or DateTime()?

**Comment by a-komarev** [comment]
You can use standard PHP function [strtotime()](http://php.net/manual/en/function.strtotime.php)
