### ISSUE TITLE
ActionColumn buttons css with data filtering

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#6928]
![buttons](https://cloud.githubusercontent.com/assets/6473565/5804117/0347f2a8-a00c-11e4-9db9-0dee15c29c93.png)

When enabling grid filtering buttons are not displayed in 1 row, and columns input like generated_coupon take too much width ?

**Comment by samdark** [comment]
Which buttons aren't displayed?

**Comment by samdark** [comment]
If there's not much space it tries to scale. You can adjust it with CSS if you want it behave differently.
