### ISSUE TITLE
db/Query should check Object configuration

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#6931]
When supplying an object config to https://github.com/yiisoft/yii2/blob/master/framework/db/Query.php it takes several values eg. as string, although they should be an array according to the docs.

The problem is, that this is only working partially. Eg. if you use `addSelect()` on a `Query` which has a `string` value set as `$select`; you'll get an array-to-string conversion or array_merge() error. While using it directly without modification seems to work fine.

What's about adding an `Object::validateConfig()` method to call, which uses Reflection to validate the config options?

**Comment by qiangxue** [comment]
The properties of `Query` are provided so that you can directly access them when necessary. When doing so, you have to follow strictly what says in the API doc. I don't think we should introduce `validateConfig()`.
