### ISSUE TITLE
realize setAttributes on ActiveRecord

### ISSUE THREAD

**Issue by zry656565** [yiisoft/yii2#6938]
When I used yii2 to create my website, I used gii to create CRUD. And I found that `setAttributes` would be called when calling `$model->load()`, but setAttributes had not been realized in `yii\db\ActiveRecord`.

I don't know if it is necessary to realize `setAttributes` by myself like this:
```
public function setAttributes($values) {
	foreach ($values as $key => $value) {
		$this->setAttribute($key, $value);
	}
}
```

Or should I provide this realization in a pull request for this?

**Comment by samdark** [comment]
It uses `setAttributes` from base class `\yii\base\Model`: https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L656

**Comment by zry656565** [comment]
I misunderstood the structure before. lol
