### ISSUE TITLE
problem with bundles depends with CDN links after compressing

### ISSUE THREAD

**Issue by macklay** [yiisoft/yii2#6939]
In my project I have custom JQuery bundle with only CDN links.
Some project bundles have this custom JQuery bundle in his depends.

All js files compressed(by yii asset tool) in AllAsset bundle, but in autogenerated assets config AllAsset bundle has not depends section with my JQuery CDN bundle 
and file all-xxxxxxxxxx.js, with jquery code, loaded first and i have a lot of errors about not founded JQuery.

current falied assest autogenerated config:
```php 
return [
    'webmasters\\assets\\AllAssets' => [
        'class' => 'webmasters\\assets\\AllAssets',
        'basePath' => '@webroot/compressed',
        'baseUrl' => '@web/compressed',
        'js' => [
            'all-48f691c87801478f2cfa8f8dfcfc4baf.js',
        ],
        'css' => [
            'all-d41d8cd98f00b204e9800998ecf8427e.css',
        ],
    ],
...
```
needed code:
```php 
return [
    'webmasters\\assets\\AllAssets' => [
        'class' => 'webmasters\\assets\\AllAssets',
        'basePath' => '@webroot/compressed',
        'baseUrl' => '@web/compressed',
        'js' => [
            'all-48f691c87801478f2cfa8f8dfcfc4baf.js',
        ],
        'css' => [
            'all-d41d8cd98f00b204e9800998ecf8427e.css',
        ],
        'depends' => [
            'common\\bundles\\JqueryAsset' // this is bundle with CDN links
        ]
    ],
...
```

**Comment by klimov-paul** [comment]
There is a unit test, which covers this situation:
https://github.com/yiisoft/yii2/blob/master/tests/unit/framework/console/controllers/AssetControllerTest.php#L318

It passes fine.

There must be some error at your side or extra conditions you not mentioned.

**Comment by macklay** [comment]
This unti test check depends for ExternalAsset and RegularAsset but problem with ALL  assets bundle target, wich defined in assets config:

```php
    'webmasters\assets\AllAssets' => [
        'basePath' => '@webroot/compressed',
        'baseUrl' => '@web/compressed',
        'js' => 'all-{hash}.js',
        'css' => 'all-{hash}.css',
    ],
```

Oher assets work fine

**Comment by klimov-paul** [comment]
Here is the check that generated 'all' assets still depends on external one:
https://github.com/yiisoft/yii2/blob/master/tests/unit/framework/console/controllers/AssetControllerTest.php#L377
