### ISSUE TITLE
Using functions in yii\data\Sort

### ISSUE THREAD

**Issue by henrikhj** [yiisoft/yii2#6942]
At the moment, it seems that the Sort class can only be used to structure sorting according to fields and ASC/DESC.
It would be great to have the option of using SQL functions in the sorting, such as the [FIELD function](http://dev.mysql.com/doc/refman/5.0/en/string-functions.html#function_field).
This would make it possible to set up non-default sorting of strings and integers, ie:
```SQL
ORDER BY FIELD(`id`, 1, 2, 4, 0);
```

**Comment by mdmunir** [comment]
```php
$query->orderBy([new Expression('FIELD([[id]], 1, 2, 4, 0)')])
```

**Comment by henrikhj** [comment]
Ah of cause! 
How obvious is this. 
Thanks.

**Comment by henrikhj** [comment]
Hm, I might have been a bit too quick on the keys there.
It doesn't seem like the Sort class is able to accept an instance of Expression.
I'm using the ActiveDataProvider to build data for a REST API, and want to set up some sorting rules using its sort field and the Sort class.
Also, when using orderBy() directly on the query, the following query is generated, which results in SQL syntax errors:
```SQL
SELECT * FROM `table` ORDER BY FIELD(`id`, `0`, `1`, `2`, `3`, `1)` LIMIT 20
```
Take note of the misplaced ` just after the closing parenthesis.

**Comment by mdmunir** [comment]
> Also, when using orderBy() directly on the query, the following query is generated, which results in SQL syntax errors:
```sql
SELECT * FROM `table` ORDER BY FIELD(`id`, `0`, `1`, `2`, `3`, `1)` LIMIT 20
```

Are you sure? What your code?

**Comment by henrikhj** [comment]
The code is as simple as can be:
```PHP
return new ActiveDataProvider([
            'query' => Account::find()->orderBy(new Expression("FIELD([[status]], 0, 3, 4, 2, 1)")),
//            'sort' => ['defaultOrder' => new Expression('FIELD(`status`, 0, 3, 4, 2, 1)')],
        ]);
```

**Comment by mdmunir** [comment]
use as array
```php
->orderBy([new Expression("FIELD([[status]], 0, 3, 4, 2, 1)")])
```

**Comment by henrikhj** [comment]
Ah yes. My mistake.
This takes care of orderBy(), but if I want to use it with the yii\data\Sort class, for a more dynamic solution, it still seems that it's not parsing it correctly. Neither as an object to 'defaultOrder' or wrapped in an array. It's simply ignored by ActiveDataProvider.

Thanks for your help, by the way.

**Comment by mdmunir** [comment]
I am not sure, try this
```php
new ActiveDataProvider([
    ...
    'sort' => [
        'attributes' => [
            'status' =>[
                'asc' => [new Expression("FIELD([[status]], 0, 3, 4, 2, 1)")],
                'desc' => ....
            ]
        ],
        'defaultOrders' => ['status'=>SORT_ASC]
    ],
   
]);
```

**Comment by henrikhj** [comment]
You sir, are an absolute hero!
Not the most beautiful solution in the world, but it works perfectly.
Thank you very much.
