### ISSUE TITLE
How to clear memory of ActiveRecord object

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#6943]
For example when we create AR object with data
$object = new SomeARModel::find()->one(1);
this object fill some amount of memory? and when we make
unset($object);
memory don't clearing.

How to clear memory so fully as it possible?

**Comment by samdark** [comment]
Do you have YII_DEBUG = false?

**Comment by xVismutx** [comment]
Yes

**Comment by xVismutx** [comment]
With "YII_DEBUG = false" memory leaking less, than with "YII_DEBUG = true", but still large.
The problem, than we need to create thousands of AR objects in foreach cycle, and after each unset($object); a lot capacity of memory is leaking...
on 1000 objects leaking 2mb

**Comment by samdark** [comment]
Hmm.

1. It could be that object is referenced by something. Could be checked by `debug_zval_dump($model)`. Look for `refcount` that > `1`.
2. It could be that garbage collector isn't firing (at least immediately). Try forcing collection with ` gc_collect_cycles()`.

**Comment by samdark** [comment]
Are you creating these 1000 objects one by one or all at once?

**Comment by samdark** [comment]
Have you tried http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#batch-query?

**Comment by xVismutx** [comment]
one by one, and unseting after each one. Memory was growing.
Yes, we used batch, but even in one by one creating memory leaks)

**Comment by samdark** [comment]
OK. Please try checking https://github.com/yiisoft/yii2/issues/6943#issuecomment-70651234 and report results.

**Comment by mdmunir** [comment]
@xVismutx can you show me how you do (your code)?
I want to try it in my local.

**Comment by xVismutx** [comment]
we simplified code to this, and made some tests.
In this tests with "YII_DEBUG = false" no memory leaking was detected
So, now we will check logic, and if we will have problems i wiil ask.

Now in simplified code we don't have memory leaking, all good.

$start = memory_get_usage();
 for($i = 0; $i < 10000; $i++){
      $r = MailerRecipients::find()->limit(10)->offset($i)->all();
      unset($r);
}
var_dump(memory_get_usage() - $start);

**Comment by samdark** [comment]
Closing the issue until more info is provided poing to the issue in framework code.

**Comment by cebe** [comment]
memory should be cleared after php garbage collector has run, this will not be on each unset call but when memory is needed to be freed.
