### ISSUE TITLE
Table alias with "joinWith"

### ISSUE THREAD

**Issue by belerophon** [yiisoft/yii2#6946]
Hi there,

I have a relation declared as:

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccount()
    {
        return $this->hasOne(Account::className(), ['id' => 'social_account_id']);
    }

The `Account` model has a table named _**social_account**_.

When doing some queries on the same model where the above relation is declared:

    Model::find()->joinWith('account')->where(['account.user_id' => 666])->one();

it results on:

    SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "account"
        LINE 1: ..."social_account_id" = "social_account"."id" WHERE "account"....
        ^
        The SQL being executed was: SELECT "access_token".* FROM "access_token" LEFT JOIN "social_account" ON "access_token"."social_account_id" = "social_account"."id" WHERE "account"."user_id"=1

Of course, when I change `'account.user_id'` to `'social_account.user_id'`:

    Model::find()->joinWith('account')->where(['social_account.user_id' => 666])->one();

it works.

I thought one could, on the `where` part, reference the columns of relation using the relation name.
Shouldn't it be that way?

Thanks in advance!

**Comment by mdmunir** [comment]
#2377
