### ISSUE TITLE
"Pretty" URLs restricted to PATH_INFO.

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#6949]
If UrlManager is configured with `$enablePrettyUrl = true`, UrlManager and UrlRule each call Request::getPathInfo() to determine the requested path/URI. However there are other ways an application may wish to allow the route to be defined, which should also be candidates for having "pretty" URLs:

- A query string parameter (e.g. index.php?path=the/requested/path)
- A console argument, in the event that the application is meant to act like a web application in a console environment

There should be a clean way for applications to specify what the requested path is. Currently the only way to do it is to override Request::getPathInfo(), but then the function loses its meaning, and you have to add something like a "getRealPathInfo()" in case any code does need to know the actual path info.

**Comment by cebe** [comment]
Can you show a real use case where you need this?

**Comment by brandonkelly** [comment]
I described our use case here: https://github.com/yiisoft/yii2/pull/6947

That specific enhancement got shut down by @qiangxue but I stil feel that the issue is valid.

**Comment by brandonkelly** [comment]
Some servers aren't actually configured to support PATH_INFO and will 404 if you try to route to index.php/some/path, which is why the .htaccess rule that we ship Craft with a rewrite rule that just adds the path to a `p` query string param, which is always safe.

**Comment by klimov-paul** [comment]
Provided use cases are too uncommon, while implementation will produce a confusing code.
