### ISSUE TITLE
Yii2 GridView show display tree category ?

### ISSUE THREAD

**Issue by tiger0350** [yiisoft/yii2#6952]
How display the category tree? $listCategory
// Controller 
$model = New Category();
$listCategory = $model->getListCategory();

// Module
public function getListCategory($page = 1, $limit = NORMAL_LIMIT){
        $parents = $this->getListChildrenCategory($page, $limit, 0);
        foreach($parents as $parent){
            $arr_result[$parent->id]['parent'] = $parent;
            $children = $this->getListChildrenCategory($page, $limit, $parent->id);
            if(!$children) continue;
            else {
                $arr_result[$parent->id]['child'] = $children->getModels();
            }
        }
        return $arr_result;
    }

    public function getListChildrenCategory($page = 1, $limit = NORMAL_LIMIT, $parent_id = 0){
        $searchModel = new CategorySearch();
        $searchModel->parent_id = $parent_id;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        return $dataProvider->getModels();
    }

**Comment by mdmunir** [comment]
https://www.facebook.com/groups/yiitalk/

**Comment by cebe** [comment]
please use the forum to ask questions, github is a bug tracker. http://www.yiiframework.com/forum/
