### ISSUE TITLE
Jui composer require fails because of ".DS_Store" Files

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#6954]
I have some trouble because we use a Windows environment with a `.DS_Store` File restriction.

If I run the command:
> composer require --prefer-dist yiisoft/yii2-jui "*"`

There are errors like:
> ZipArchive::extractTo(Z:/xyz/basic/vendor/composer/2f9ab2a7/components-jquery/ui-3967814/ui/.DS_Store): failed to open stream: Permission denied

I've got no Problem with the Yii2 Installation, because there is a `.gitignore` File. Would it be possible to put a `.gitignore` File in the Jui repository?

**Comment by sensorario** [comment]
Mmmmm I think is bettere to add .DS_Store to your global gitignore.

**Comment by cebe** [comment]
The error is about `jquery-ui` package, not `yii2-jui` so it should be reported there and maybe that directroy should be removed from their repo.
