### ISSUE TITLE
Controller Generator uppercase

### ISSUE THREAD

**Issue by trinkity** [yiisoft/yii2#6955]
This module not check that Controller Class is in uppercase mode.
After yii2 have a  not found page.
I test on gii advanced template.

**Comment by samdark** [comment]
Which generator? What data was entered? Which error generated?

**Comment by trinkity** [comment]
if i write into gii module Controller Generator:
Controller Class field 
frontend\controllers\testController

Action IDs field
index

View Path
@app/views/test

Press Generate Button and gii generate the files.... but when i call url
http://testyii.local/index.php?r=test/index
browser show me not found page !!!

The error was into Controller Class field gii Controller Generator

frontend\controllers\testController

You must check and validate the field Controller Class.
It must be uppercase . i must write
frontend\controllers\TestController
and not
frontend\controllers\testController

**Comment by samdark** [comment]
OK. I guess additional validation can be added.

**Comment by mdmunir** [comment]
@samdark 
Again and again, i remained on my opinion. Prefer using controller id instead of controller class name.
More simple and more intuitif. #6367

**Comment by mdmunir** [comment]
For your consideration, my comment here https://github.com/yiisoft/yii2/issues/6367#issuecomment-65534307
Current implementation.
```
./yii gii/crud --modelClass=common\\models\\User --controllerClass=backend\\controllers\\UserController --viewPath=@backend/views
```
Cros:
  * Potentially typo (type a long text)
  * Potentially set wrong view path #6674

Vs
```
./yii gii/crud --modelClass=common\\models\\User --controllerID=user --moduleID=backend
```

**Comment by samdark** [comment]
What about advanced app where controller could be generated via frontend Gii for backend app?

**Comment by samdark** [comment]
What about custom controllerNamespace?

**Comment by mdmunir** [comment]
> What about advanced app where controller could be generated via frontend Gii for backend app?

To generate controller for other application, we should define module for that application.
```php
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
    
    $config['modules']['backend'] = [
        'class' => 'yii\base\Module',
        'basePath' => '@backend',
        'controllerNamespace' => 'backend\\controllers',
   ];
```

> What about custom controllerNamespace?

I am not sure about this question. Do you mean, how if we change `Module::$controllerNamespace` at runtime?
If custom controllerNamespace is set via config, no problem.
