### ISSUE TITLE
How to set the js with modulewise in yii2 and how to call within render view file

### ISSUE THREAD

**Issue by ceovishnu** [yiisoft/yii2#6957]
How can we added JS OR CSS file with modulewise in Yii2 and how to add it in render file

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for issue reports.

**Comment by ceovishnu** [comment]
@qiangxue have u any idea for same

**Comment by ceovishnu** [comment]
@samdark http://www.yiiframework.com/forum/index.php/topic/61230-how-to-set-the-js-with-modulewise-in-yii2-and-how-to-call-within-render-view-file/
