### ISSUE TITLE
Yii2 fails to find mongodb classes

### ISSUE THREAD

**Issue by Rytiss** [yiisoft/yii2#6958]
I am trying MongoDB integration with Yii2. I tried following the instructions at https://github.com/yiisoft/yii2-mongodb but I can't seem to get it to work:

    public function actionSearch($sku) {
        $query = new Query;
        // compose the query
        $query->select()
            ->from('products')
            ->where(['skus.sku' => $sku]);
        $product = $query->all();
     
        return $this->render('product', $product);
    }

My use declarations are as follows:

    namespace app\controllers;
    
    use Yii;
    use yii\mongodb\Query;
    use yii\filters\AccessControl;
    use yii\web\Controller;
    use yii\filters\VerbFilter;
    use app\models\LoginForm;

The above results in:

    Class 'yii\mongodb\Query' not found

There is also an error trying to just get the collection:

    $collection = Yii::$app->mongodb->getCollection('products');

The above results in:

    Class yii\mongodb\Connection does not exist

This seems as if yii2-mongodb has failed to install, but I see the files in vendor/yiisoft/yii2-mongodb, and composer did not report any errors.

**Comment by samdark** [comment]
Have you installed fxp/composer-asset-plugin globally? http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer

**Comment by cesao** [comment]
I have this same problema, I'm trying to do a test with MongoDB and I followed this tutorial https://github.com/yiisoft/yii2-mongodb, bun when I try to access the database with it code

$collection=Yii::$app->mongodb->getCollection("teste");

I receive the following error:
Class \yii\mongodb\Connection does not exist

**Comment by cebe** [comment]
is the mongodb php extension installed correctly also on console?

**Comment by cesao** [comment]
I use lampp and I installed the mongodb php extension.

**Comment by samdark** [comment]
Is it available at console?

**Comment by Rytiss** [comment]
Basic PHP script works fine both in terminal and through Apache, so PHP extension is correctly installed.

**Comment by cebe** [comment]
try running 
```
php -i |grep mongo
```
on console. if it does not give an output, the mongodb extension may not  be enabled in console env.

**Comment by Rytiss** [comment]
Like I said, it is enabled as it works in non-yii2 script. Here is the output of the command you gave me:

mongo
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 1 => 1
mongo.ping_interval => 5 => 5

**Comment by klimov-paul** [comment]
There is no point on arguing about PHP Mongo extension sinse here is a complain on `yii\mongodb\Connection` class missing, which does not belong there.
Please check if `yii-mongodb` extension is present inside your 'vendor' directory.
Perhaps you should try performing dry run of 'composer install' for your application.

**Comment by Rytiss** [comment]
I tried 'composer install' before - it does not find anything to install or update.

The extension is present in vendor/yiisoft/yii2-mongodb directory.

**Comment by klimov-paul** [comment]
Try clearing vendor directory and run 'composer install' again.

**Comment by Rytiss** [comment]
Output:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing yiisoft/yii2-composer (2.0.2)
    Loading from cache

  - Installing bower-asset/jquery (2.1.3)
    Loading from cache

  - Installing bower-asset/jquery.inputmask (3.1.57)
    Loading from cache

  - Installing bower-asset/punycode (v1.3.2)
    Loading from cache

  - Installing bower-asset/yii2-pjax (v2.0.2)
    Loading from cache

  - Installing cebe/markdown (1.0.1)
    Loading from cache

  - Installing ezyang/htmlpurifier (v4.6.0)
    Loading from cache

  - Installing yiisoft/yii2 (2.0.2)
    Loading from cache

  - Installing yiisoft/yii2-mongodb (2.0.2)
    Loading from cache

Generating autoload files


End result: no change, still missing classes.

**Comment by cebe** [comment]
@Rytiss you may also check `composer show -i` to see if it is installed correctly.

**Comment by Rytiss** [comment]
@cebe 'composer show -i' reports:
bower-asset/jquery           2.1.3
bower-asset/jquery.inputmask 3.1.57 jquery.inputmask is a jquery plugin which create an input mask.
bower-asset/punycode         v1.3.2
bower-asset/yii2-pjax        v2.0.2
cebe/markdown                1.0.1  A super fast, highly extensible markdown parser for PHP
ezyang/htmlpurifier          v4.6.0 Standards compliant HTML filter written in PHP
yiisoft/yii2                 2.0.2  Yii PHP Framework Version 2
yiisoft/yii2-composer        2.0.2  The composer plugin for Yii extension installer
yiisoft/yii2-mongodb         2.0.2  MongoDb extension for the Yii framework

**Comment by cebe** [comment]
@Rytiss can you reproduce this with a fresh install of the basic app, with minimal changes?

**Comment by cesao** [comment]
@cebe 
I ran these commands on console:
php -i | grep mongo
/etc/php5/cli/conf.d/20-mongo.ini,
mongo
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 1 => 1
mongo.ping_interval => 5 => 5

and lampp's php
/opt/lampp/bin/php -i | grep mongo
mongo
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 1 => 1
mongo.ping_interval => 5 => 5

I checked the yii2-mongodb's directory in vendor.
I cleaned the yii2-mongodb's directory and run "composer installl".
I intalled old version, but I get the same error!

**Comment by Rytiss** [comment]
Did a clean install, the same error.

**Comment by samdark** [comment]
Hmm.

1. Make sure the file is there at `vendor/yiisoft/yii2-mongodb/Connection.php` and content inside is OK.
2. Note if there are any differences in your main `composer.json` from what's in the application template you're using. Especially `extra`, `autoload`.
3. Make sure you're specifying version correctly or just try `*`.
4. Check that your `vendor/extensions.php` is OK. It should contain `yiisoft/yii2-mongo`.

**Comment by Rytiss** [comment]
Bingo, application composer.json (basic/composer.json) did not contain the '"yiisoft/yii2-mongodb": "*"' line in the require section. Adding it and running 'composer update' worked.

**Comment by samdark** [comment]
Glad it's solved :)
