### ISSUE TITLE
yii2.0 'yii\db\Exception' with message 'could not find driver'

### ISSUE THREAD

**Issue by zoushuai518** [yiisoft/yii2#6959]
using the Linux crontab call yii console:

crontab:
 *    *     *     *     *  php yii example/create 1 >> /runtime/logs/runtime.log 2>&1 

The operation results：
yii2.0 'yii\db\Exception' with message 'could not find driver'

Can you tell me why

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for bug reports. Thanks!
