### ISSUE TITLE
authclient api fileupload

### ISSUE THREAD

**Issue by belerophon** [yiisoft/yii2#6961]
`OAuth2` class defines the `composeRequestCurlOptions` function:

    protected function composeRequestCurlOptions($method, $url, array $params)
    {
        $curlOptions = [];
        switch ($method) {
            case 'GET': {
                $curlOptions[CURLOPT_URL] = $this->composeUrl($url, $params);
                break;
            }
            case 'POST': {
                $curlOptions[CURLOPT_POST] = true;
                $curlOptions[CURLOPT_HTTPHEADER] = ['Content-type: application/x-www-form-urlencoded'];
                $curlOptions[CURLOPT_POSTFIELDS] = http_build_query($params, '', '&', PHP_QUERY_RFC3986);
                break;
            }
            case 'HEAD': {
                $curlOptions[CURLOPT_CUSTOMREQUEST] = $method;
                if (!empty($params)) {
                    $curlOptions[CURLOPT_URL] = $this->composeUrl($url, $params);
                }
                break;
            }
            default: {
                $curlOptions[CURLOPT_CUSTOMREQUEST] = $method;
                if (!empty($params)) {
                    $curlOptions[CURLOPT_POSTFIELDS] = $params;
                }
            }
        }

        return $curlOptions;
    }

I'm using `UploadedFile::getInstanceByName` to get a hold on a `UploadedFile` in a REST API. However, the cURL options defined for the _POST_ in the function above **don't** allow me to upload a file. 

If, however, I change the cURL options to following:

        case 'POST': {
                $curlOptions[CURLOPT_POST] = true;
                $curlOptions[CURLOPT_POSTFIELDS] = $params;
                break;
        }
**the file upload works as expected.**

Am I working with REST file uploads in the wrong way? Or is `authclient` simply not intended to support file uploads?

Thanks!

**Comment by klimov-paul** [comment]
Have you ever reda this?
https://github.com/yiisoft/yii2/tree/master/extensions/authclient#external-api-usage

It says rather clear:
> this method is very basic and it may be not enough to access full external API functionality

**Comment by belerophon** [comment]
Yes I've read it, but it sure is not clear or assertive. On the **opposite**: it is vague, what is "full external API functionality" ? ....

Anyway, I'd like to ask you _1)_ if this functionality will ever be supported and _2)_ if there are any **obvious** complications with the modifications I introduced above **??**

Thank you!!

**Comment by klimov-paul** [comment]
There is a feature proposal at #4531, which if accepted may be then used as a part of `authclient` and thus support file upload as well. However, it is still in consideretion.
At the present state if you with more sophisticated API client you should use `Guzzle` based solution.

**Comment by smorocho** [comment]
This is solved with this pull request https://github.com/yiisoft/yii2-authclient/pull/33
