### ISSUE TITLE
Rbac an query multiple exec

### ISSUE THREAD

**Issue by zinzinday** [yiisoft/yii2#6967]
![untitled](https://cloud.githubusercontent.com/assets/441560/5849051/970b92e4-a212-11e4-8862-c101fb20bf51.jpg)

I use rbac to check permision to edit, delete article, comment.
on debug i see multiple exec with an query.
why we not cache result by role name, rule name?

**Comment by githubjeka** [comment]
You must do it yourself.

**Comment by pana1990** [comment]
duplicated https://github.com/yiisoft/yii2/issues/3168
