### ISSUE TITLE
Suggestion/Ideia: yii.activeForm validateOnType

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#6975]
I don't know if it's a valid point or if it's better to keep the things cleaner.
When a field has validateOnType and the user _moves_ the cursor with the _arrows_, (a lot of people do that) a request is [made](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L410).

```javascript
if (attribute.validateOnType) {
    $input.on('keyup.yiiActiveForm', function () {
    //Any key pressed.
    if (attribute.value !== getValue($form, attribute)) {
        validateAttribute($form, attribute, false, attribute.validationDelay);
}
```

Perhaps it would be nice (if it's worth it) to do something like [this](http://stackoverflow.com/questions/3977642/how-to-know-if-keyup-is-a-character-key-jquery/12511097#12511097) or check the arrow keycode.

```javascript
$("#input").keyup(function(event) {
    var searchText = $.trim($("#input").val());
    
    var c= String.fromCharCode(event.keyCode);
    var isWordCharacter = c.match(/\w/);
    var isBackspaceOrDelete = (event.keyCode == 8 || event.keyCode == 46);

    if((isWordCharacter || isBackspaceOrDelete) && searchText.length > 2) { 
        ...
    }
}
```

**Comment by samdark** [comment]
Makes sense.

**Comment by slinstj** [comment]
Can I adopt this too, @samdark?

**Comment by samdark** [comment]
Yes.

**Comment by slinstj** [comment]
@samdark (or anyone else), I need help here, please.

I can see how yii.activeForm.js works. I understand the `init`, `validate` and `watchAttribute`. I see the `keyup.yiiActiveForm` custom event. But I could not find *where in the world* that custom event is triggered (or the real keyup event is handled) in the code. I also looked for yii.js and yii.validation.js

I am studying that code for about 4 or 5 hours or so! This should probably be something stupidly simple. (Would be really more productive (i.e., faster, easyer) if the code was well commented, specially for newcomers like me).

Could you help me? 
Thanks in advance.

**Comment by cebe** [comment]
the binding happens here:
https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L174-177
by calling watchAttribute()

Here is the regisering of the handler function:
https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L418-423

**Comment by slinstj** [comment]
@cebe, thank you so much! You are always helping! But perhaps I could have been more clear in my question... Sorry, I will try again.

As I said earlier, I see how the `watchAttribute` works. It iterates over attributes *binding* the proper custom events on them using the jquery's `.on()` function. What I really need to find is where it is *triggered* (jquery's  `.trigger()` function). AFAIK, each custom event in a ".on()" function should have a ".trigger()" function for it (right?). 

So, if we have `attr.on('myCustomEvent', function(){})` where would it to be triggered? It would be triggered where we put `attr.trigger('myCustomEvent')`.

In this issue case, I need to know where my real keyboard 'keyup' event is being handled. There should be a trigger to the 'keyUp.activeForm' custom event.

Why I need to find this? 

1. Because keyup may not work the same way for some keys in all keyboards. So I want to test a keypress variation;
2. Because this hurts my honor! LOL

**Comment by slinstj** [comment]
@llfm, how have you got to the conclusion that the arrows keys are triggering requests?? Are you using ajax validation? I could not find any request nor even some validation event being dispatched when pressing arrows keys.

(when samdark marked this like `enhancement`, I thought that this supposed behavior somehow it had already been confirmed)

**Comment by samdark** [comment]
I was assuming behavior described in the first post exists and could be enhanced.

**Comment by samdark** [comment]
@slinstj the issues is about `validateOnType` mode. Enhancement is about preventing validation when arrow keys are pressed without changing the value.

**Comment by slinstj** [comment]
@samdark, I know. Thanks anyway.

**Comment by samdark** [comment]
These event names are event namespaces: http://api.jquery.com/on/. So event is still triggered at key up and the first part of the name is namespace which could be used to remove this event only.

**Comment by slinstj** [comment]
@samdark, that is exactly I was looking for! Thank you! I did not know about those 'namespaces' that allow us to mix default and custom events.

**Comment by slinstj** [comment]
@llfm, now I see. It is really dispatching events when pressing arrow keys.

**Comment by slinstj** [comment]
Sorry for the delayed fix (if it is really fixed). I am a full time worker/husband besides help here. :v:

**Comment by samdark** [comment]
No worries. Have you tested it?

**Comment by slinstj** [comment]
Yeah, ActiveFormTest is passing.

**Comment by samdark** [comment]
I mean in various browsers. I don't think there's test for the case.

**Comment by slinstj** [comment]
Only FF and Chrome. I dont have windows (thanks God) to test on IE. Although should work ok since that jQuery normalizes the events and `$.inArray()` is jQuery too.

**Comment by samdark** [comment]
Yep. OK. I'll merge it before release.

**Comment by samdark** [comment]
Thank you!

**Comment by slinstj** [comment]
Very glad to help here. :v:
