### ISSUE TITLE
Dependency Injection Container not reset when destroying application in functional tests

### ISSUE THREAD

**Issue by ivokund** [yiisoft/yii2#6978]
I use `\Yii::$container` to override some classes during unit tests. Functional tests run after unit tests and fail, because `\Yii::$container->get` still returns the temporary PHPUnit Mock objects rather than the real classes. 

Should not `\yii\codeception\TestCase::destroyApplication` also clear the Dependency Injection Container like this? 

```php
    /**
     * Destroys the application instance created by [[mockApplication]].
     */
    protected function destroyApplication()
    {
        Yii::$app = null;
        Yii::$container = new \yii\di\Container()
    }
```
I can provide a pull request if this is the correct way of solving this.

**Comment by samdark** [comment]
It should, I think.

**Comment by ivokund** [comment]
Added a fix via: https://github.com/yiisoft/yii2/pull/6981
