### ISSUE TITLE
ViewContextInterface is it needed?

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#6979]
I watched [history](https://github.com/yiisoft/yii2/commits/master/framework/base/Widget.php)  and after `Commits on May 9, 2013 Moved "framework" to "iii". ` https://github.com/yiisoft/yii2/commit/0d814fa5236f2a7c708acfeea30f8a05f1f268fe base Widget began to use ViewContextInterface, although the class Widget implements it initially. 

If class [implements it](https://github.com/yiisoft/yii2/blob/master/framework/base/Widget.php#L202) by default, why do we need an interface? Don't you want overload or?

**Comment by cebe** [comment]
ViewContextInterface is implemented by Widget and Controller and used by View to ensure it has the necessary methods, what exactly is the problem?

**Comment by githubjeka** [comment]
> ViewContextInterface is implemented by Widget and Controller 

**implemented** by base class now. I mean all written in the base class already all written in the base class and child have it always. Why to need interface? To eliminate overload?

**Comment by samdark** [comment]
Implemented by two separate base classes:

- https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L443
- https://github.com/yiisoft/yii2/blob/master/framework/base/Widget.php#L202

**Comment by samdark** [comment]
View doesn't care if it's Controller or Widget. Also you can pass your own context via `render` method in order to customize view path location algorithm.

**Comment by githubjeka** [comment]
Может я на англ. не правильно выразился. Я имел ввиду, что метод `public function getViewPath()` создан в классах `Controller.php#L443` и `Widget.php#L202` и если убрать интерфейс, то ничего не изменится. Всё будет по-прежнему работать. Обязательный метод из интерфейса уже в базовых классах реализован. Интерфейс в данном случае только не позволяет в классах наследниках перезагружать сигнатуры. Так ли это "непозволение" нужно - вот в чём вопрос. Если не нужно, то можно удалить файл ViewContextInterface.

**Comment by samdark** [comment]
Интерфейс в данном случае даёт понять, с чем работает View и что нужно реализовать в своём классе контекста, если что. Технически можно и удалить, да. То есть сделать вместо интерфейса просто описание в phpdoc. Но как-то это не очень...

**Comment by githubjeka** [comment]
Хорошо, если "не очень", то оставляйте. У меня "не очень" сейчас :)

**Comment by lynicidn** [comment]
а чем мешает интерфейс я чтото не пойму, как он мешает перекрыть если не нарушать структуру

**Comment by githubjeka** [comment]
Перекрыть его можно только создав новый интерфейс с другой сигнатурой. Но это ты создашь свой интерфейс - тем самым нарушив декларативность. И применишь только к своим классам, классы фреймворка останутся только со своей сигнатурой `getViewPath()` . Александр говорит, что нужно быть уверенным в этой декларативности.

**Comment by lynicidn** [comment]
а ну так это тоже связано с https://github.com/yiisoft/yii2/issues/6252
ну да, не доконца продумано, а только что вьюха это файл

**Comment by samdark** [comment]
Нужно потому как View работает именно с методами, описанными в интерфейсе и именно таким образом. Единственное, технически это нигде не проверяется...

**Comment by lynicidn** [comment]
вместо getView надо hasView и renderView

**Comment by githubjeka** [comment]
> Единственное, технически это нигде не проверяется.

Так это и есть плюс в использовании интерфейса. Не нужно никаких проверок.

Всё. Прошу прощения за хлопоты. Нашёл - https://github.com/yiisoft/yii2/blob/master/framework/base/View.php#L178 . 

Интерфейс нужен.
