### ISSUE TITLE
On submit form with action='get' generate invalid hidden input

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#6982]
the code bellow 

```php
<?= Html::beginForm('', 'get') ?>
    <?= Html::textInput('rules', 'test'); ?>
    <?= Html::submitButton('send'); ?>
<?= Html::endForm() ?>
```
each time to submit form, renders n+1 hidden input "rules"

**Comment by cebe** [comment]
I did not really understand, can you paste the output this generates?

**Comment by leandrogehlen** [comment]
First time
![first_time](https://cloud.githubusercontent.com/assets/1750751/5874279/d460d42c-a2e6-11e4-80ed-b57ca4635997.png)

Second time
![second_time](https://cloud.githubusercontent.com/assets/1750751/5874310/40d096ba-a2e7-11e4-9c2a-c4027ee5d4cc.png)

**Comment by cebe** [comment]
well, this preserves the GET parameters when the form is sent because when your route is empty you tell yii that you want to send the form to the currently opened url, in this case including the rules parameter.

**Comment by cebe** [comment]
To only get the current route without any params, use 

```php
<?= Html::beginForm([''], 'get') ?>
```
