### ISSUE TITLE
Duplicate rows after ActiveRecord::link execution

### ISSUE THREAD

**Issue by Emig0** [yiisoft/yii2#6986]
Problem explained at the title. If I link two models multiple times I have duplicated rows on the DB. How can I fix that?

**Comment by samdark** [comment]
Why do you link it multiple times?

**Comment by Emig0** [comment]
Why not? It is possible that user will create that many-many relation. I think that in the system must be validations/checks for that

**Comment by Emig0** [comment]
Maybe can I fix that and do pull request?

**Comment by cebe** [comment]
How did you declare your table? normally there should be a duplicate primary key error be thrown in this case...

**Comment by Emig0** [comment]
Yeap, it throws an exception. But how to ignore that exception and redirect (for example) back to previous page?

**Comment by cebe** [comment]
> If I link two models multiple times I have duplicated rows on the DB

This does not sound like an exception ;)
You can use try {} catch {} http://php.net/manual/en/language.exceptions.php
