### ISSUE TITLE
Pager should be able to reference owner (widget) instance

### ISSUE THREAD

**Issue by nirvana-msu** [yiisoft/yii2#6988]
Suppose you are trying to write a pager class wrapping a javascript plugin that implements custom content handling logic (e.g. scrolling for `ListView`). In such a case, pager needs to know e.g. `id` of parent widget to correctly initialize default selectors. Without knowing owner `id` it is impossible to guarantee that several scripts on the same page would not conflict. Forcing a user to explicitly specify owner `id` through pager configuration is obviously not desirable. And in general, pager needs to know configurable widget html markup properties, such as container class and tag names.

**Comment by dynasource** [comment]
there are a lot of settings you can use on http://www.yiiframework.com/doc-2.0/yii-widgets-linkpager.html to ensure that elements can communicate without conflict. You can set IDs, classes or add wrappers. I dont see why Pager object should get more 'smart' in OO terms than it already is.
