### ISSUE TITLE
Usage of InlineValidator is not consistent with other validators, and not documented properly.

### ISSUE THREAD

**Issue by hiltonjanfield** [yiisoft/yii2#6992]
Took me some time to figure this out, as the docs at http://www.yiiframework.com/doc-2.0/guide-input-validation.html#inline-validators do not mention this in any way.

The link above specifies an inline method signature as:
```php
/**
 * @param string $attribute the attribute currently being validated
 * @param array $params the additional name-value pairs given in the rule
 */
function ($attribute, $params)
```

Obviously, we can pass parameters to our inline validator. That's great, except the implementation of that is the same as other validators, and its use is not documented.

With most validators, you put all the parameters in the same array:
```php
['name', 'string', 'length' => [5, 20]],
['version', 'integer', 'min' => 0, 'max' => 1000],
// etc.
```

With Inline Validators, that will get you nowhere. You instead have to specify a `params` parameter and nest all your parameters in another array.
```php
['status', 'myStatusValidator', 'params' => ['custom' => 'parameters', 'go' => 'here']],
```

Suggestions:
Either make this distinct functionality CLEAR in the docs (at present it is completely unmentioned), or modify the behaviour so it is consistent across all validators. The latter could be accomplished in Validator::createValidator by not using $params to hold the object parameters.
```php
    public static function createValidator($type, $model, $attributes, $params = [])
    {
        $objectParams['attributes'] = $attributes;

        if ($type instanceof \Closure || $model->hasMethod($type)) {
            // method-based validator
            $objectParams['class'] = __NAMESPACE__ . '\InlineValidator';
            $objectParams['method'] = $type;
            $objectParams['params'] = $params;
        } else {
            $objectParams = array_merge($params, $objectParams);
            if (isset(static::$builtInValidators[$type])) {
                $type = static::$builtInValidators[$type];
            }
            if (is_array($type)) {
                $objectParams = array_merge($type, $objectParams);
            } else {
                $objectParams['class'] = $type;
            }
        }

        return Yii::createObject($objectParams);
    }
```

Usage example with the modified code:
```php
public function rules() {
    return [
        /* ... */
        ['map', 'validateClassName', 'class' => 'StarsNT\Ruleset\MapRules'],
 //was: ['map', 'validateClassName', 'params' => ['class' => 'StarsNT\Ruleset\MapRules']],
        /* ... */
    ];
}

public function validateClassName($attribute, $params) {
    if (get_class($this->$attribute) !== $params['class']) {
        $this->addError($attribute, 'Object is of wrong class.');
    }
}

```

**Comment by qiangxue** [comment]
The proposed fix has the issue that `$objectParams` doesn't contain all possible properties supported by `InlineValidator`. It also breaks BC.

Considering the fact that you seldom need to pass extra parameters and also for BC consideration, I checked in the doc fix instead.
