### ISSUE TITLE
NOT WORKING - Using Yii in Third-Party Systems

### ISSUE THREAD

**Issue by marciocamello** [yiisoft/yii2#6995]
Example

```php

//index.php
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$yiiConfig = require(__DIR__ . '/config/yii/web.php');
new yii\web\Application($yiiConfig); // Do NOT call run() here

$model = new \app\models\Contact();
echo $model->name;

//models/Contact.php
namespace app\models;

use yii\base\Model;

class Contact extends Model
{
    /**
     * @inheritdoc
     */
    public $name = 'test';
}

```

Setup return Yii instance, but don't run Models, ActiveForm, only somthings thinks in Yii2.

**Comment by marciocamello** [comment]
I am use this 

composer global require "fxp/composer-asset-plugin:1.0.0-beta4"
composer require "yiisoft/yii2:*"
composer install

Don't works, and I try install with composer.json from yii2-basic template, and work's fine.
I don't understand this, but I believe this error ocurred because autoload don't run something components, bower, etc.

**Comment by marciocamello** [comment]
But this not work

```php
$form = \yii\widgets\ActiveForm::begin();
echo $form->field($model, 'name');
\yii\widgets\ActiveForm::end();
```

**Comment by qiangxue** [comment]
What problem do you meet? Note that it is expected you cannot use widgets like you do above because widgets may register css/js files which are rendered through a view rendering lifecycle and requires proper template.

**Comment by marciocamello** [comment]
Thanks, I see this, but is necessary fix docs for Third Part-Systems, only this

composer global require "fxp/composer-asset-plugin:1.0.0-beta4"
composer require "yiisoft/yii2:*"
composer install

Don't works, is necessary install full yii2-basic vendor folder.

**Comment by qiangxue** [comment]
Please explain what is not working. Installing `yii2-basic` is not the right way.

**Comment by Faryshta** [comment]
there is a post-create-command option on the composer.json, it doesn't run if you use `composer install`

you are meant to do `composer create-proyect`

**Comment by cebe** [comment]
@Faryshta quite sure this is not related, if you use Yii in a third party system, you should not run `composer create-project`

**Comment by Faryshta** [comment]
yii would still require to configure the folters runtime/ assets/ folders post install which is done by the post-create-command option on composer.json so then i figure maybe those folders are not being configured correctly

**Comment by cebe** [comment]
There is no need to if you use only a part of the yii functionality e.g. database layer.
Closing this issue as there is too much confusion and no clear issue.
