### ISSUE TITLE
[REST API] PUT method and UploadedFile

### ISSUE THREAD

**Issue by Claud** [yiisoft/yii2#6996]
Hello.
If used for data update "PUT" method, then UploadedFile does not work.

**Comment by fernandezekiel** [comment]
what Content-type are you using for your request?

**Comment by Claud** [comment]
multipart/form-data

**Comment by fernandezekiel** [comment]
multipart/form-data only works with POST

**Comment by fernandezekiel** [comment]
https://bugs.php.net/bug.php?id=55815

**Comment by klimov-paul** [comment]
Depends on #12463

**Comment by klimov-paul** [comment]
Solution proposed at #12466

**Comment by klimov-paul** [comment]
Resolved by commit  4e59607
