### ISSUE TITLE
Fixture console show exception 'The dir argument must be a directory'

### ISSUE THREAD

**Issue by deerawan** [yiisoft/yii2#6997]
I got error when I execute Yii fixture console command

**Environment**
PHP: 5.5.19
Yii: 2.0.3-dev
OS: OSX Yosemite 10.10.1

**How to reproduce it**
1) Download basic app
2) Composer install --prefer-dist
3) ./yii fixture *
4) Exception occurred

**Complete error**
> ./yii fixture/load User
Exception 'yii\base\InvalidParamException' with message 'The dir argument must be a directory.'
in /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:368

> Stack trace:
#0 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/console/controllers/FixtureController.php(400): yii\helpers\BaseFileHelper::findFiles('/Users/masbugan...', Array)
#1 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/console/controllers/FixtureController.php(110): yii\console\controllers\FixtureController->findFixtures(Array)
#2 [internal function]: yii\console\controllers\FixtureController->actionLoad('User')
#3 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#4 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#5 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('load', Array)
#6 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('load', Array)
#7 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('fixture/load', Array)
#8 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('fixture/load', Array)
#9 /Users/masbugan/Sites/opensource/yii2/apps/basic/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /Users/masbugan/Sites/opensource/yii2/apps/basic/yii(23): yii\base\Application->run()
#11 {main}

To solve this, need to add "codeception" into test alias inside **config/console.php**

old
```php
Yii::setAlias('@tests', dirname(__DIR__) . '/tests');
```

new
```php
Yii::setAlias('@tests', dirname(__DIR__) . '/tests/codeception');
```

**Comment by Ragazzo** [comment]
yes , fix is valid , forgot about it . Can you submit PR ?

**Comment by deerawan** [comment]
@Ragazzo yes, I can submit PR for solving this issue

**Comment by Ragazzo** [comment]
Can you also rechek this issue for `yii2 - advanced` since this commit was made https://github.com/yiisoft/yii2/commit/8af62ee97b1525dbc323a1850fef0619c51f5a54 ?

**Comment by cebe** [comment]
@Ragazzo are you sure this is correct? isn't namespace and autoloading for the tests namespace bound to this?

**Comment by deerawan** [comment]
@Ragazzo I'm on it

**Comment by cebe** [comment]
all other definitions of `@tests` alias point to `/tests` directory, not `/tests/codeception`.

**Comment by Ragazzo** [comment]
@cebe as for `yii2 - basic` i think it is ok, as for `yii2 - advanced` looked like i am lost in a lot of configs, first i looked where `@tests` is [defined](https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/frontend/_bootstrap.php) than i looked again and found it in other [place](https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/bin/_bootstrap.php) . I guess this should be clarifed and uneeded `@tests` removed. Currently dont have enough time for that to recheck, maybe you can clarify this ?

**Comment by Ragazzo** [comment]
@deerawan lets not doing anything to `yii2 - advanced` for now, since it is ok , i was in hurry to say it is wrong. Should be rechecked.

**Comment by cebe** [comment]
I have checked all declarations of `@tests` they look fine. Need to figure out the real cause of the issue.

**Comment by Ragazzo** [comment]
Ok , will loot at this one tomorrow since i don think it is a big issue. 
@deerawan what is your `User` namespace, is it [`tests\codeception\fixtures`](https://github.com/yiisoft/yii2/blob/master/apps/basic/tests/codeception/bin/yii#L22) or what ?

**Comment by deerawan** [comment]
@cebe yes, my solution is not enough. I also found that only **yii fixture/load User** can run successfully but not **yii fixture ***

@Ragazzo yes correct, I use "tests\codeception\fixtures"

**Comment by Ragazzo** [comment]
@deerawan can you take `*` in quotes and see what will be ?

**Comment by cebe** [comment]
yeah, `yii fixture *` can not work because the shell will replace * with all the files and folders in the current directory. In the docs it is already with quotes: `yii fixture "*"`

**Comment by Ragazzo** [comment]
@cebe yeah , was discovered long time ago and discussed with @qiangxue we decided to let it be as is and mentione it in docs and make it with quotes in docs
