### ISSUE TITLE
Wrap items in `ListView` into e.g. `div` container by default

### ISSUE THREAD

**Issue by nirvana-msu** [yiisoft/yii2#6999]
It was very convenient in yii1 that all items in `ListView` were wrapped in a `div` container. [Infinite-Scroll](https://github.com/paulirish/infinite-scroll), for example, works by appending fetched items to the end of matched content object using `appendContent`. In the current `ListVew` implementation it is simply not possible, since we have to add items between children of the content object and not to the end (i.e. after items that are already loaded, but before pagination, assuming default layout).

I know it is possible to do that by configuring `layout` property of `ListView`, but it would be much more convenient (if I were to distribute this as an extension) if this extra `div` was generated by `ListView` out of the box.

**Comment by cebe** [comment]
you can configure the layout property to include a container tag:

`{summary}\n<div id="..." class="items">{items}</div>\n{pager}`

**Comment by nirvana-msu** [comment]
I thought I would get this reply, that's what my last paragraph was aiming to address:

>I know it is possible to do that by configuring `layout` property of `ListView`, but it would be much more convenient (if I were to distribute this as an extension) if this extra `div` was generated by `ListView` out of the box.

I do want to publish an extension with this so everyone could use it, but it seems silly to force everyone who wants to use it to configure this `layout` property of a parent widget.

Ideally, I want it to work even if you just specify:
```php
'pager' => [
        'class' => InfiniteScrollPager::className(),
]
```

**Comment by cebe** [comment]
All the things have to be configured in one place so having instructions like this does not look to comlicated to me:

```php
'layout' => "{summary}\n<div id=\"scroll-items\">{items}\n{pager}",
'pager' => [
        'class' => InfiniteScrollPager::className(),
        'listSelector' => '#scroll-items' , // you'll want to add this anyway for maximum flexibility
]
```

**Comment by nirvana-msu** [comment]
Ok, your call. Thanks anyway)
