### ISSUE TITLE
Ask About Required Token in Github?

### ISSUE THREAD

**Issue by hscstudio** [yiisoft/yii2#7004]
About Token in Github
=======================
1) When we install Yii via composer, sometimes required github account,
sometimes no required, why?
2) When we install Yii via composer, sometimes show error invalid token,
sometimes no error
3) About point 2, I have read about invalid token, where we can fix it..
with:
https://github.com/settings/applications
- Register new application ( https://github.com/settings/applications/
new )
- we will get token,
- copy it
and then via terminal:
composer config --global github-oauth.github.com <paste token here>
4) In https://github.com/settings/applications , we see too about personal
access token
https://github.com/settings/tokens/new
What is difference this token with token that resulted from poin 3?
Thank for Your advance

**Comment by samdark** [comment]
It's Composer. If you're using it too much in a day GitHub asks you your credentials in order to push the limit. https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by phpmongodb** [comment]
You can create Token open bellow link and create your token
https://github.com/settings/tokens/new
