### ISSUE TITLE
Gii Crud Generator: Wrong Namespace for Backend Controllers in Advanced Template

### ISSUE THREAD

**Issue by alexjose** [yiisoft/yii2#7012]
The Gii CRUD generated controller throws exception **Unknown Class – yii\base\UnknownClassException**. This is due to the incorrect namespace mentioned in the Gii generated controller.

Code generated

```php
namespace app\controllers;
   
use Yii;
 ...
```
Code Expected:

```php
namespace backend\controllers;

use Yii;
 ...
````

**Comment by samdark** [comment]
Can you provide data that you're entering to Gii CRUD generator form?

**Comment by alexjose** [comment]
**Gii Url:** backend/web/index.php?r=gii%2Fdefault%2Fview&id=crud
**Model Class:** common\models\Artist
**Search Model Class:** app\models\ArtistSearch
**Controller Class:** app\controllers\ArtistController
**Base Controller Class:** yii\web\Controller

Gii Ver: 2.0.3
Yii Ver: 2.0.3

**Comment by samdark** [comment]
Well, you've asked Gii to generate `app\controllers\ArtistController` it did it exactly as instructed. I see no issue there.

**Comment by p2made** [comment]
I just experienced this same problem (& found this issue on asking Google for solutions). I used inputs after the same pattern as alexjose through following the suggestions in the popover help withing Gii. Perhaps changing that help would help.

**Comment by duynguyen0511** [comment]
I've tested several inputs and found out the below will create a User Controller under backend, using the User model from "common" and create "views" file correctly under backend

**Gii Url:** http://backend.localhost/index.php?r=gii%2Fdefault%2Fview&id=crud
**Model Class:** common\models\User
**Search Model Class:** common\models\UserSearch
**Controller Class:** backend\controllers\UserController
**View Path:** @backend/views/user

**Comment by samdark** [comment]
@duynguyen0511 can you report it separately? Thanks.

**Comment by duynguyen0511** [comment]
@samdark sorry if I confused you. My comment was to show how to set it up correctly. It was not a bug report.

**Comment by samdark** [comment]
OK :)

**Comment by m4jeed** [comment]
i have problem at crud generator in model class can't access but have notification "form Class 'common\models\Artikel' does not exist or has syntax error." why? help me please...
