### ISSUE TITLE
How to search with relations?

### ISSUE THREAD

**Issue by IC7K** [yiisoft/yii2#7015]
the Prodlist model have:
    
public function getTovar()
    {
       return $this->hasOne(Tovar::className(), ['id' => 'prodTovarID']);
    }      

need:
            $goodsSearchModel = new ProdlistSearch(['zakID'=>0, 'tovar.tovPostav'=>1]);

where zakID is a field of Prodlist, and tovPostav is a field of Tovar

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for bug reports and feature requests.

**Comment by IC7K** [comment]
ok! sorry but solve

            $goodsDataProvider = new ActiveDataProvider([
                'query' => Prodlist::find()->where(['zakID'=>0])->innerJoin('tovar c', 'prodTovarID = c.id AND c.tovPostav LIKE :postavid', [':postavid' => '%'.$zakaz->zakPostavID.'%']),
                'pagination' => false,
            ]);
