### ISSUE TITLE
Example from Guide/Working with Databases doesn't work : ( 

### ISSUE THREAD

**Issue by bautrukevich** [yiisoft/yii2#7017]
PHP Fatal Error – yii\base\ErrorException
Class 'yii\models\Country' not found

What's problem in this tutorial?

http://cl.ly/image/1Q1h2L0E1S0C

**Comment by Faryshta** [comment]
1) which name space you use for the controller?

2) Did you saved the Country model? if so where and in which namespace?

**Comment by bautrukevich** [comment]
1. For the controller I'm use namespace app\controllers; 

2. My Country model saved here: models/Country.php and contains:
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Country extends ActiveRecord
{
}

**Comment by cebe** [comment]
you have added `use yii\models\Country;` to your controller class, it must be `use app\models\Country;` instead.

**Comment by bautrukevich** [comment]
Thank you! It's work : )

But it (use yii\models\Country;) was in tuttorial. Please, correct them.

**Comment by cebe** [comment]
@bautrukevich where did you find that? as far as I see there is no such thing in the guide...

**Comment by bautrukevich** [comment]
Now it's correct, thank you.
