### ISSUE TITLE
Model::loadMultiple mismatch indices

### ISSUE THREAD

**Issue by QuPsi** [yiisoft/yii2#7021]
I'm using Model::loadMultiple and I'm noticing that the indices are not matching up.  loadMultiple begins indexing at 0, whereas my form POST indexes from 1. This causes the first model in loadMultiple to be left empty, and the last input from the POST to be discarded.

Perhaps a way to tell loadMultiple where to start reading data from? Or have loadMultiple automatically load the first data into index 0 and go from there?

**Comment by cebe** [comment]
both, models and POST are passed to `loadMultiple()` from your code so you have to adjust the creation of models in your code.
