### ISSUE TITLE
`run()` interface for Widget

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#7022]
See https://github.com/yiisoft/yii2/commit/756308d2d9898e64235d8f9b0420ecb34347697d#commitcomment-9411721

**Comment by cebe** [comment]
why do we need an interface for a widget?

**Comment by githubjeka** [comment]
Just refactor to remove it :
```php
/**
     * Executes the widget.
     * @return string the result of widget execution to be outputted.
     */
    public function run()
    {
    }
```

and add declarative to method `run`

**Comment by cebe** [comment]
I don't get why this is needed or what the benefits are, can you please elaborate on why current implementation is bad and what the benefits are when it is changed to using an interface? Also how should this interface be used? class Widget needs to be abstrace then?

**Comment by githubjeka** [comment]
yes - `Widget ` wiil be abstract, because is base class with require method. I support the declarative to implement. Then to the novices not arise misunderstanding what they need for proper implementation.

**Comment by qiangxue** [comment]
A widget requires not just a `run()` method. It also needs `begin()`, `end()`. I  don't think we should introduce an interface here.

**Comment by githubjeka** [comment]
:mans_shoe: oh

**Comment by githubjeka** [comment]
`end()` require `run()`

**Comment by samdark** [comment]
I think it's useful to have it since widgets are what people implement often.

**Comment by qiangxue** [comment]
An interface is needed if you want to implement a widget that does NOT extend from `Widget`. This use case is very rare.

**Comment by cebe** [comment]
Implementing a Widget that does not extend from Widget will not be part of the Widget Stack and not have the auto ID increment. I do not see any usecase for this.
