### ISSUE TITLE
Label option 'for' is not passed to label function via checkbox function

### ISSUE THREAD

**Issue by mirrorps** [yiisoft/yii2#7026]
Hi guys,

I've been up to the following scenario and found out that in this case there is no option to set the 'for' property of the html label control:

Scenario:
echo yii\helpers\BaseHtml::checkbox('', true,[
                'label' => 'My label', //--- 'My label' is dynamically loaded from DB
                'labelOptions' => ['class' => 'checkbox-inline', 'for' => 'another-input-field-text'],
            ]);

echo $form->field($model, "MyClassProperty")->textarea(['id' => 'another-input-field-text'])->label(false);

From the Yii source (yii\helpers\BaseHtml):

//--- here the $for option is hardcoded set to null 
(line 694) $content = static::label(static::input('checkbox', $name, $value, $options) . ' ' . $label, null, $labelOptions);

// --- at line 415 the 'for' option passed trough $options is overwritten with null value
public static function label($content, $for = null, $options = [])
    {
(line 415)        $options['for'] = $for;
        return static::tag('label', $content, $options);
    }

**Comment by adamasantares** [comment]
Hi.
I'm not understand, how this is must to view?
```html
<div class="group">
   <label for="textarea_id">My label</label>
   <input type="checkbox" name="xxx" checked/>
</div>
<div class="group">
   <textarea id="textarea_id"></textarea>
</div>
```
Hmm?

**Comment by mirrorps** [comment]
Hi adamasantares,

Yes, the final html will look like the one you posted. The uncommon approach here is that the label 'My label' is loaded from a static db table and there is no class property to hold that label name, that's why I used yii\helpers\BaseHtml::checkbox instead of ActiveField::checkbox.

**Comment by adamasantares** [comment]
To be honest, I do not understand exactly how the result of your code should look in the browser...
May be you need something like this?
```
[ checkbox ]  Label for text
+---------------------------------------------+
|   textarea                                  |
+---------------------------------------------+
```
So this is more simple way:
```php
echo '<div>' . yii\helpers\BaseHtml::checkbox('', true, [])
    . '<label for="another-input-id" class="checkbox-inline">'
    . $labelFromDB . '</label></div>';
echo $form->field($model, "MyClassProperty")->textarea(['id' => 'another-input-id'])
    ->label(false);
```
Why not use the html in "view"?

**Comment by mirrorps** [comment]
Hi adamasantares,

Yes, this is the exact way the code should look in the browser, you visualized it perfectly. 
In a matter of fact this scenario is a common way to fill some message (textarea) according to a user choice (checkbox).

I know the templates are holding the html, but creating the entire html using Yii functions and to use html directly only for this sort of textarea management breaks the coding style. 

Long story short, changing line 415 to the following one will eliminate the problem: 

public static function label($content, $for = null, $options = [])
{
//(line 415) $options['for'] = $for; // Original
(line 415) if($for !== null) $options['for'] = $for; // suggested one
   return static::tag('label', $content, $options);
}

Another way around is to avoid passing hardcoded null values for the label param, when checkbox function is called internally:

//--- original call:
(line 694) $content = static::label(static::input('checkbox', $name, $value, $options) . ' ' . $label, null, $labelOptions);

//--- suggested call:
(line 694) $content = static::label(static::input('checkbox', $name, $value, $options) . ' ' . $label, isset($options['for'] ? $options['for'] : null), $labelOptions);

By using the suggested approach(es) the overall performance of the framework will be not decreased and the 'for' option of the label html tag will be always accessible.

**Comment by adamasantares** [comment]
Ok, I'll try to make PR with fix.

**Comment by mirrorps** [comment]
Tanks a lot.

**Comment by Faryshta** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

"A label element can have both a for attribute and a contained control element, as long as the for attribute points to the contained control element."

What you try to do is against the HTML specifications and will produce unexpected results depending on the browser and version

**Comment by adamasantares** [comment]
@Faryshta you are right, I forgot that the ActiveField always placed a input elements inside label tag.
@mirrorps I think that my example https://github.com/yiisoft/yii2/issues/7026#issuecomment-71672323 is more correct solution.

**Comment by mirrorps** [comment]
@Faryshta I agree with you. I've checked the docs again to be sure that this kind of call encapsulates the checkbox with the label element which may cause unexpected behaviour. Looks like the framework's code is properly set and the only solution here will be the one proposed by @adamasantares.
