### ISSUE TITLE
getItem is protected yii\rbac\ManagerInterface

### ISSUE THREAD

**Issue by ahb360** [yiisoft/yii2#7027]
I have an rbac item name and I want to get its type.
Currently there is no way to get the item type or create item object directly from its name. 
I have to know the type to use `getPermission`, `getRole` or `getRule`.
There is a `getItem` method in `DbManager` and `PhpManager` classes but it is protected and 
I can't use it.
Is there an alternative to this method?

**Comment by cebe** [comment]
duplicate of #6790
