### ISSUE TITLE
Cache namespacing and wild card delete. (Feature Request)

### ISSUE THREAD

**Issue by mfrancis107** [yiisoft/yii2#7028]
It would be great if we could somehow use wild cards to clear cache.

This would make it much easier to clear portions of the cache without having to flush all cache.

For example

```
Yii::$app->cache->set("user.id.1.cart");
Yii::$app->cache->set("user.id.1.someother_data");
Yii::$app->cache->delete("user.id.1.*"); //Clears all data for this user.
```

**Comment by Alex-Code** [comment]
Something like this would be better implemented by extending whichever cache component you're using.

Couple reasons,
Not all caching systems might support wildcards.
The key could be converted to an md5 hash under certain circumstances so wildcards become useless.

**Comment by cebe** [comment]
This is not possible because most of the cache systems do not support deleting key ranges. You should consider to use different cache components for different kind of data and cache dependencies to invalidate certain cache values.

**Comment by ua0leg** [comment]
`
$categories = Yii::$app->cache->getOrSet('categories', function () {
  return Category::find()->all();
}, 3600, new TagDependency([
  'tags' => 'category_list'
]));

// delete
TagDependency::invalidate(Yii::$app->cache, 'category_list');
`

**Comment by ivan-redooc** [comment]
@ua0leg you can try to look at some cache that implements [PSR-6](https://www.php-fig.org/psr/psr-6/) 

example:
https://symfony.com/doc/current/components/cache/cache_invalidation.html#cache-component-tags
