### ISSUE TITLE
Class name first in <title> on API doc pages

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#7031]
This is a suggestion for the website.

My browser often looks something like this:

![browser](https://i.imgur.com/yXtVirU.png)

The text in the tab headings is not useful. But it could be if you brought the class name (sans namespace) to the first place in the `<title>` tag.

**Comment by samdark** [comment]
Noted.

**Comment by cebe** [comment]
done: 3d510fb, keeping this open to do the same for the guide.

**Comment by tom--** [comment]
Regressed

**Comment by cebe** [comment]
?

**Comment by tom--** [comment]
Now we have lost any useful information from page titles. It's not just less helpful for me, it's bad SEO.

**Comment by cebe** [comment]
hm weird, will check what has happended there...

**Comment by cebe** [comment]
It is fixed on http://stuff.cebe.cc/yii2docs/index.html now. Automatic docs generation was broken since we moved extensions out of main repo.

@qiangxue can you fix it on yiiframework.com?

**Comment by Faryshta** [comment]
it looks fixed to me now.
