### ISSUE TITLE
Adding to the documentation, how?

### ISSUE THREAD

**Issue by apyii** [yiisoft/yii2#7032]
I'm developing a project using Yii2 and am running into a few beginner problems in getting acquainted with the architecture. In doing this I'm having to read a lot of the documentation and go through the core code to figure out what is going on.

There are a few things I'd like to add to the documentation here and there to help people avoid some of the problems I've encountered and spare them several hours of searching. Where and what is the best way for me to go about this. Should I add things to the Class Documentation, Inline Documentation, Guide. etc.

**Comment by samdark** [comment]
Anywhere you think necessary. Separate pull requests per topic please small enough to review quickly.

https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md
