### ISSUE TITLE
dropDownList optgroup label

### ISSUE THREAD

**Issue by aktec** [yiisoft/yii2#7036]
Если я использую в dropDownList список с группами, а в опциях передаю параметр 'groups' с label для каждой группы,то они все равно не выводятся.

Проблема вот здесь: https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1565
после того, как применяются настройки, переданные в массиве groups, 'label' перезаписывается ключом из $items

решается конечно, элементарно:
-$groupAttrs['label'] = $key;
+if (!isset($groupAttrs['label']))
+$groupAttrs['label'] = $key;

может это и не баг. Но иногда labels удобнее передавать через опции, чем формировать правильный массив $items

**Comment by resurtm** [comment]
This seems to be a valid issue. IMHO this should be merged into upstream.

@aktec, can you handle this and publish fixing PR? In case "no", I can do it myself.

**Comment by lynicidn** [comment]
где вы там чего увидили? нет там groups, нет там того кода что вы пишите

**Comment by aktec** [comment]
@resurtm  you can do it yourself)

**Comment by klimov-paul** [comment]
Resolved by commit 8c81a15
