### ISSUE TITLE
AssetController. css relative image path isn't parsed correctly on compressing

### ISSUE THREAD

**Issue by ruskid** [yiisoft/yii2#7037]
Seems like a bug and i think it was mentioned before, but still. When i want to combine in my case css files with yii asset console command I get the following structure:
img/bee.png
css/all-XXX.css
js/all-XXX.js

My css file **before** compressing contained this relative path to the image.
```css
background: url(../img/bee.png);
```

**After** compressing it the path was like this. It was searching for /css/img/bee.png
```css
background: url(img/bee.png);
```

This path worked for me.
```css
background: url(/img/bee.png);
```

**Comment by klimov-paul** [comment]
Issue resolved by commit 5bda2fe
