### ISSUE TITLE
"composer update" failing after upgrading to 2.0.2

### ISSUE THREAD

**Issue by kalpitpandit** [yiisoft/yii2#7041]
Yesterday i have ran composer update and it has downloaded Yii 2.0.2 and dependency packages successfully. 

Today when i am running composer update to download other libraries via composer its giving me following error. 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2].

This what i am getting when i am running "composer diagnose" to check version and other common problems.

Checking composer.json: FAIL
require.yiisoft/yii2 : unbound version constraints (*) should be avoided
require.yiisoft/yii2-bootstrap : unbound version constraints (*) should be avoided
require.yiisoft/yii2-swiftmailer : unbound version constraints (*) should be avoided
require.yiisoft/yii2-mongodb : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: OK
Checking disk free space: OK
Checking composer version: OK

**Comment by cebe** [comment]
are you sure you have installed composer asset plugin correctly? Try installing it again:

```
composer global require "fxp/composer-asset-plugin:1.0.0"
```
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer
