### ISSUE TITLE
Guide structure: Getting Data from Users

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#7042]
I have updated the guide on forms and tabular input and found that it may need some restructuring.

- https://github.com/yiisoft/yii2/issues/7040
- 55196dc869d9af1391492cda3cd2f8c1bdde2843
- 97e3df1626bf4aa3047e42385b37f0f127d3ad3d

Currently there is the following structure:

- Working with Forms
  - general intro about how to use ActiveForm
  - handling tabular input
- validation
- file upload
- Getting Data for Multiple Models

The main problem is in the first part which covers creation of forms without handling validation but  already talks about tabular input.
I suggest to change it to something like this:

- Working with Forms
  - general intro about how to use ActiveForm
- validation
- file upload
- handling tabular input
- Getting Data for Multiple Models

@yiisoft/core-developers opinions?

**Comment by samdark** [comment]
Agree.

**Comment by qiangxue** [comment]
Yes, the `input-*.md` (except `input-validation.md`) sections all need further improvement. It's good to see you start this effort. :)
