### ISSUE TITLE
static vs. $this in /** @return */ docblock tag

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#7045]
I got very confused about the meaning of `/** @return static */` in the class reference. A long and confusing discussion ensued on the #yii channel. In the end we agreed that the docs are inconsistent and it is probably for the best to adopt the convention specified by [phpDocumentor](http://www.phpdoc.org/docs/latest/guides/types.html), specifically:

> The PHPDoc Standard also describes several keywords that are not native to PHP but are found to be often used or are representations of situations that are convenient to describe.

>    - **static** An object of the class where this value was consumed, if inherited it will represent the child class. (see late static binding in the PHP manual).
>    - **$this** This exact object instance, usually used to denote a fluent interface.

[For those unfamiliar with these terms, *late static binding* is using the `static` keyword other than for declaring a static member. *Fluent interfaces* means chaining methods, e.g. `$query->from()->limit()->where()`.]

It turns out that PhpStorm understands things this way too. You can try this for yourself. If you let PhpStorm automatically write the docblocks for the following two methods, this is the result

```php
<?php

class Foo
{
    /**
     * @return $this
     */
    public function bar()
    {
        return $this;
    }

    /**
     * @return static
     */
    public function baz()
    {
        return new static();
    }
}
```

And, tbh, I just find it hard to get my head around the idea of $this being static.

I propose:

1. Yii 2.0 adopt the convention as specified on www.phpdoc.org and quoted above
2. Reiterate it in the style guide wiki
3. Consider adding to the front page of the (highly formal) Class Reference a section called "Document conventions" where various things like this can be explained to readers.
4. Update docblocks in the framework code to conform to this convention

**Comment by samdark** [comment]
At the time we've added it `$this` support among IDEs was inconsistent and incomplete. Need to check how it is now.

**Comment by tom--** [comment]
Better wording for the definition of static and $this keywords is in the [draft PSR-5 "standard"](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md) right at the very end.

**Comment by samdark** [comment]
If I remember correctly, NetBeans wasn't supporting `$this` at all.

**Comment by tom--** [comment]
NetBeans give me gas.

**Comment by Faryshta** [comment]
I use vim. I am making a patch using grep mostly. I have a question. Should I change

     * @return static the model itself
to
     * @return $this the model itself
or
     * @return $this

The first one seem redundant this `$this` is the object itself

**Comment by Faryshta** [comment]
@samdark isn't this fixed already?

**Comment by samdark** [comment]
Yes. Thanks.
