### ISSUE TITLE
GridView column sortLinkOptions

### ISSUE THREAD

**Issue by AntonYu** [yiisoft/yii2#7048]
I want to put a custom sorting label like this:
```php
'columns' => [
    [
        'attribute' => 'name',
        'label' => 'Player',        
        'format' => 'raw',
        'value' => function ($model) {
            return Html::a(Html::encode($model->name), $model->getUrl());
        },
        'enableSorting' => true,
        'sortLinkOptions' => [
            'class' => 'orderby',
            'label' => 'Player <span class="arr">↓</span>',
        ],
    ],
],
```

But it doesn't work - attribute label overwrites it. Is this an expected behavior or not?
If I swap array_merge values in https://github.com/yiisoft/yii2/blob/master/framework/grid/DataColumn.php#L142 - everithing is ok for me.

**Comment by cebe** [comment]
you have to set the label of the column, as you did already above, not in sortLinkOptions.
