### ISSUE TITLE
Implement OAuth2 server

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#7050]
OAuth2 using many project.
create oauth server and client .
please add OAuth2

**Comment by Borales** [comment]
@EngRajabi check this extension first https://github.com/yiisoft/yii2/tree/master/extensions/authclient#authclient-extension-for-yii-2

**Comment by samdark** [comment]
Since we have client I've renamed issue title to mention server.

**Comment by cebe** [comment]
I think this is out of the scope of the framework, there are already plenty of OAuth server implementations.

**Comment by samdark** [comment]
I tend to think the same... decided then.

**Comment by EngRajabi** [comment]
why oauth2 out of the scope of the framework???

**Comment by EngRajabi** [comment]
mr samdark 
The implementation of OAuth2 server is mandatory in the large-scale projects

**Comment by mikehaertl** [comment]
> The implementation of OAuth2 server is mandatory in the large-scale projects

This may be the case, but this doesn't mean, that a framework has to duplicate each and every possible service if there already are good implementations. Have a look here for OAuth servers in PHP:

https://github.com/thephpleague/oauth2-server
https://github.com/bshaffer/oauth2-server-php

**Comment by lichunqiang** [comment]
agree with @mikehaertl
