### ISSUE TITLE
Cookie Validation

### ISSUE THREAD

**Issue by pavimus** [yiisoft/yii2#7051]
Current implementation of cookie validation in yii\web\Request and in yii\web\Response protects cookie values from change, but doesn't protect from name change. For example, application sets two cookies: 
1) name1=protected_value1
2) name2=protected_value2

If somebody exchanges cookies values (name1=protected_value2, name2=protected_value1) they still pass validation. In some cases this can produce vulnerability in applications.

**Comment by samdark** [comment]
@qiangxue you've implemented signature check for cookies. Any idea how to make it count the order?

**Comment by pavimus** [comment]
May be good decision is include cookie name in value. For example

$value = Yii::$app->getSecurity()->hashData(serialize($value), $validationKey);

in yii\web\Response replace with

$value = Yii::$app->getSecurity()->hashData(serialize([$cookie->name,$value]), $validationKey);

**Comment by qiangxue** [comment]
That's a good find. Thanks!
