### ISSUE TITLE
Implement OAuth2 server 

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#7058]
this link 
https://github.com/yiisoft/yii2/issues/7050
OAuth2 using many project.
create oauth server and client .
please add OAuth2
The implementation of OAuth2 server is mandatory in the large-scale projects
why oauth2 out of the scope of the framework???
why close issue??

**Comment by creocoder** [comment]
http://oauth2.thephpleague.com/

**Comment by creocoder** [comment]
> why oauth2 out of the scope of the framework???

To not reinvent too many wheels :)

**Comment by nvthaovn** [comment]
You can try yii2-authclient for OAuth client. Of course, it is very popular. But i nothing that OAuth 2.0 server is too.
There are lot of OAuth 2.0 library for experiment or study But OAuth 2.0 for large-scale projects is a very big problem. It is out of the scope of the framework.

**Comment by samdark** [comment]
It'

**Comment by zinzinday** [comment]
This supported OAuth 2.0, Please read guide for usage

On Wed, Jan 28, 2015 at 6:07 PM, Alexander Makarov <notifications@github.com
