### ISSUE TITLE
Use select to return a null value in the with

### ISSUE THREAD

**Issue by stromknight** [yiisoft/yii2#7059]
# Use select to return a null value in the with

### code

   	$model->find()->with(['detailmodel' 
   					=> function($query){
   						$query->select('someFieldName');
   					}
   	])->all();
   	
### return 

	$model => array(
		'attributes' => [
			'filedName1' => 'fieldValue1',
			'filedName2' => 'fieldValue2',
		]
		'related' => [
			'detailmodel'=> [] //is empty
		]
	
	);

#### This is a bug or can't use select in here?

**Comment by cebe** [comment]
you did not include primary and foreign keys in the select so yii can not populate relations correctly.

**Comment by stromknight** [comment]
sorry, I did not understand.Where should I load the primary key and foreign key.
please write a example code?
thank you very mach

**Comment by cebe** [comment]
This line:                     `$query->select('someFieldName');` 
you have to include the foreign and primary key of that table.
