### ISSUE TITLE
Tabindex -1 in bootstrap dropdown causes wrong behavior when dropdown inside form

### ISSUE THREAD

**Issue by semir-karic** [yiisoft/yii2#7062]
When you insert a ButtonDropdown::widget inside an active form, pressing Enter in one of the form text fields will not submit form, but will open up a first dropdown inside it since their links have tabindex set to "-1". Also you cannot override tabindex in linkoptions since it is coded in line 92 in Dropdown.php file as  $linkOptions['tabindex'] = '-1';

**Comment by dmitriy-krista** [comment]
There is nothing wrong with dropdown that you use. Behavior is not wrong. If you want to prevent opening dropdown (when you press Enter),  just add option 'type' => 'button' . Here is an example:
```php
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <?= ButtonDropdown::widget([
                'label' => 'Action',
                'dropdown' => [
                    'items' => [
                        ['label' => 'DropdownA', 'url' => '/'],
                        ['label' => 'DropdownB', 'url' => '#'],
                    ],
                ],
                'options' => [
                    'type' => 'button'
                ]
            ]);?>
            <div class="form-group">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
```
