### ISSUE TITLE
Captcha refresh doesn't work from module

### ISSUE THREAD

**Issue by pavlinter** [yiisoft/yii2#7063]
I want get captha from root router site/captcha!?
Current url /index.php?r=module/controller/action
<pre>
...
echo $form->field($model, 'verifyCode')->widget(Captcha::className(), [
   'captchaAction' => '/site/captcha' //error in first slash, refresh doesn't work
]);
...
</pre>

**Comment by cebe** [comment]
> refresh doesn't work

in which way does it not work? what are you expecting it to do and what does it do?

**Comment by pavlinter** [comment]
Sorry, when refresh image, client validation always show error.
[settings.hashKey](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.captcha.js#L55) == yiiCaptcha//site/captcha 
[options.hashKey](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.validation.js#L242)  == yiiCaptcha/site/captcha

**Comment by dynasource** [comment]
I dont have any errors with the captcha component
- nor when loading from modules
- nor with a captcha run as a custom module. 

If you have errors, there is a great chance that the captcha is validated twice and therefore reset.

**Comment by deofly** [comment]
I meet the same problem. When I click the captcha image to refresh verify code, client validation always show error. But when I refresh the page without clicking the captcha image, everything is ok. My captcha action is 'passport/account/captcha'.

**Comment by samdark** [comment]
Closed since no further infor provided.
