### ISSUE TITLE
Should gii use ClassName::tableName() when generating viaTable relations

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#7064]
When generating a `model` with `gii` that has a pivot table the `viaTable` method has the table name hard coded.
Would this be better if it used `Model::tableName()` instead?

**Comment by fernandezekiel** [comment]
maybe the presumption is that pivot tables are not something that has a model

**Comment by Alex-Code** [comment]
That's a good point.
I do have models for my pivot tables to help with certain things but guess not everyone will.

**Comment by mdmunir** [comment]
Should use `via` instead of `viaTable`.

**Comment by qiangxue** [comment]
As explained by @fernandezekiel, the model for the join table may not exist.

**Comment by mdmunir** [comment]
@qiangxue 
> As explained by @fernandezekiel, the model for the join table may not exist.

Of course ya. But, sometimes gii ignoring existence of model when define relation. E.g. I have 2 tables `order` and `item`. When i generate model only for table `order`, model `Order` has line
```php
public function getItems()
{
    $this->hasMany(Item::className(),[...]);
}
```
event no model `Item` created. So, why we not use same approach for pivot table.

```php
public function getProducts()
{
    $this->hasMany(Product::className(),[...])->via('items');
}
```

Sorry for my english. I hope you understand my word :D.

**Comment by qiangxue** [comment]
Makes sense in this case.

**Comment by nineinchnick** [comment]
This could be conditional. Table name should be used instead of model class name because when junction tables does not hold any data (contains only fk columns) the model is not used.

**Comment by LAV45** [comment]
@mdmunir , @qiangxue 
I already implemented viaTable() => via() https://github.com/LAV45/yii2-gii/commit/6c5ecb817c31b854d69408ed1567e66995cbbf89
