### ISSUE TITLE
ActiveForm ajax validation callback

### ISSUE THREAD

**Issue by MUTOgen** [yiisoft/yii2#7065]
Hi!
Is there any way to get errors after ajax validation in js?
I need to create some custom modals with errors info. So i think i need some sort of callback function...

**Comment by cebe** [comment]
there is afterValidate event on the form, is that what you need? or something different?

**Comment by MUTOgen** [comment]
@cebe i can't find any info here http://stuff.cebe.cc/yii2docs/yii-widgets-activeform.html

**Comment by lynicidn** [comment]
it js object event https://github.com/yiisoft/yii2/blob/fa0a3aefaef9c1932036cb25ea8aa9441a65624e/framework/assets/yii.activeForm.js#L49

**Comment by MUTOgen** [comment]
@lynicidn thank you! Looks great, i think this is what i'm looking for.

**Comment by jpodpro** [comment]
hi there! any chance one of you can give an example of how to attach these events? 

manythanks!

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md
