### ISSUE TITLE
checkboxColumn options

### ISSUE THREAD

**Issue by dub34** [yiisoft/yii2#7067]
Hi. Is it possible to add checkbox options in header of CheckboxColumn like checkboxOptions property in  renderDataCellContent method? If i need to add my html class to checkbox in colum i can use  
[
            'class' => 'kartik\grid\CheckboxColumn',
            'checkboxOptions'=>['class' => 'myClass']
        ],
but it not used for "SelectAll" checkbox in column header. In code i find 
return Html::checkBox($name, false, ['class' => 'select-on-check-all']);

**Comment by samdark** [comment]
kartik classes aren't framework ones. Please ask extension author instead. Thanks.

**Comment by dub34** [comment]
It`s not kartik code. This code i find in yii2/grid/CheckboxColumn. protected function renderHeaderCellContent() line 93 you can find hardcoded class for selectAll checkbox.
protected function renderDataCellContent($model, $key, $index) line 111 - checkbox with checkboxOptions from config

**Comment by cebe** [comment]
you can set the header cell content yourself:

```php
[
'class' => 'kartik\grid\CheckboxColumn',
'header' => Html::checkBox('selection', false, ['class' => 'select-on-check-all yourClass'])
],
```

**Comment by dub34** [comment]
thank you
