### ISSUE TITLE
Codeception post request

### ISSUE THREAD

**Issue by Koudy** [yiisoft/yii2#7068]
On my site I have links, which created with this parameter:
```'linkOptions' => ['data-method' => 'post']```.
And in controller I check if it is post:
```
'verbs' => [
	'class' => VerbFilter::className(),
	'actions' => [
		'block' => ['post'],
	],
],
```
Now I need the test which will be able to open the pages which are on these links, in other words I need send post request. I know I can use $I->click(); but I want to test  situation when there's no links like this on a site. For example: someone trying to block already blocked user.

If it was not necessary to check post request or not, I would do this:
```
$blockUserPage = BlockUserPage::openBy($I, [
	'id' => $I->getFixture('user')['blockedUser']['id']
]);
```
How can I open page via post?

**Comment by Ragazzo** [comment]
If you are using `[Yii2](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/InnerBrowser.php#L605)` module or you can use `submitForm`  on `Yii2` module or `WebDriver`

**Comment by Koudy** [comment]
@Ragazzo I have no form, I even have no link.

**Comment by Koudy** [comment]
sendAjaxPostRequest don't work, mb because I use redirect:
```
if ($user->isBlocked) {
	return $this->redirect(['view', 'id' => $user]);
}
```
And I think there's shouldn't be ajax.

**Comment by nsanden** [comment]
I ended up doing this as a unit test and POST with curl. Probably not the best way but it worked.

**Comment by Ragazzo** [comment]
@Koudy you can grab needed attributes from element that contains `data-...` attributes and send `postAjaxRequest`, but don't forget to grab `csrf` token too . 

>And I think there's shouldn't be ajax.

For `data-method = post` and so on `Yii2` use ajax to make a request

**Comment by Koudy** [comment]
@Ragazzo, looks like it not, example in advanced ```data-method = post``` set on logout link and it not ajax.

**Comment by onedevlink** [comment]
I have this test case:

```PHP
$I->wantTo('ensure that users block functional on unactivated user don\'t works');
$notActivatedUser = $I->getFixture('user')['notActivateUser'];

/**
 * Login administrator on site
 * — We get yii2 user administrator session.
 */
$I = new UserSteps($scenario);
$I->login(UserFixture::USER_ADMINISTRATOR);

/**
 * Show user management page
 * — He is unblocked and page don't have buttons to block him by right design 
 * (We can't click buttons by $I->click(), therefore we need a distinct POST request)
 */
$I->amOnPage(Yii::$app->urlManager->createUrl(['users/view', 'id' => $notActivatedUser['id']]));
$I->expectTo('see unblock status');
$I->see(Yii::t('backend', '<tr><th>Blocked</th><td>No</td></tr>'));
$I->dontSee(Yii::t('backend', 'Block'), 'a');

/**
 * Send POST request to block this user by sendAjaxPostRequest. 
 * We testing that if user is unactivated then can't block him.
 * — REST unsuitable, we need yii2 user administrator session
 */
$url = Yii::$app->urlManager->createAbsoluteUrl(['users/block', 'id' => $notActivatedUser['id']]);
$I->sendAjaxPostRequest($url);

/**
 * Show user management page again, seek blocked status
 */
$I->amOnPage(Yii::$app->urlManager->createUrl(['users/view', 'id' => $notActivatedUser['id']]));
$I->expectTo('see user is don\'t blocked');
$I->see(Yii::t('backend', '<tr><th>Blocked</th><td>No</td></tr>'));
```

In users/block controller return is:
```PHP
return $this->redirect(['view', 'id' => $id]);
```
Yeah, redirect on Ajax request is wrong, but on website this is POST request.
**— I want to test this case: return redirected content on POST request by codeception when website don't have buttons on which can click**.

In functional.suite.yml:
```
PhpBrowser:
   url: 'http://localhost'
      curl:
         CURLOPT_RETURNTRANSFER: true
```

Question: Does it make sense to expect from sendAjaxPostRequest return redirected page content, or it should return only JSON and others direct data?

**Comment by Koudy** [comment]
@Ragazzo, any ideas?

**Comment by dynasource** [comment]
This isnt a Yii topic, but a Codeception topic.

@Koudy, @Ragazzo already gave the answer. 
1) Use the submitForm is you want to simulate a POST
2) If you dont have a form, use sendAjaxPostRequest
3) If that is still not working in your specific scenario, use Webdriver instead of functional testing with Yii.

**Comment by onedevlink** [comment]
@dynasource, sendAjaxPostRequest don't return redirect content. This is the question of this issue: should be sendAjaxPostRequest return redirect content or not.

Webdriver is useless on this scenario, submitForm too.

**Comment by dynasource** [comment]
thats a Codeception thing in which you doing your own rewrite of https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/InnerBrowser.php#L605

**Comment by dynasource** [comment]
@Koudy, @onedevlink, I dived into it for you

To see if a redirect is triggered, look at:
```php 
\Codeception\SuiteManager::$modules['Yii2']->client->headers['x-redirect']
```

If you want to look at returned content, use:
```php
\Codeception\SuiteManager::$modules['Yii2']->client->getResponse();
```

If you want the history of requests:
```php
\Codeception\SuiteManager::$modules['Yii2']->client->getHistory()
```

Getting the content of a redirected page with Ajax is then still problematic, but when you load the page of the redirect with a normal $I->amOnPage like:
```php
$I->amOnPage(\Codeception\SuiteManager::$modules['Yii2']->client->headers['x-redirect'][0]);
$I->see('Something you wanted to see on this page');
```

Hope this will get you further

**Comment by Ragazzo** [comment]
@Koudy so far there was various suggestions, last one by @dynasource but i dont understand now main issue, since it was mentioned any `redirect` issues. If you want to see content of page to which you are being redirected through `ajax` request then you can do it by overriding symfony browser kit and add check there for `X-Redirect` header similar as it is done already in browser kit for `Location` header

**Comment by YasserHassan** [comment]
>Now I need the test which will be able to open the pages which are on these links, in other words I need send post request. I know I can use $I->click(); but I want to test situation when there's no links like this on a site.

Add the `REST` module to your test suite configuration and use `$I->sendPOST('requested_url')`. I think this is what you want.

**Comment by afunix** [comment]
Did anyone have a success with sendPOST()?
Per logs I confirm that request is sent and processed, but assertions (see(), dontSee()) fail.
I also checked that '.fail.html' file contains correct data, so I don't know why see()/dontSee() fail...

By the way, sendPOST() is not a suitable substitution for click() which can make "POST".
I have to generate the link by hand for sendPOST() while click() parses the HTML output.
So I don't see why this bug is closed..

**Comment by sky003** [comment]
The main problem is in the CSRF. So I use this solution.
```php
<?php
namespace Codeception\Module;

class PhpBrowserHelper extends PhpBrowser
{
    /**
     * Open page via POST
     *
     * @param string $page
     */
    public function amOnPageViaPost($page)
    {
        $this->crawler = $this->client->request('POST', $page, ['_csrf' => $this->crawler->filterXPath('//meta[@name="csrf-token"]')->attr('content')]);
        $this->forms = [];
        $this->debugResponse();
    }
}
```
