### ISSUE TITLE
Documentation: Long navbar

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#7069]
The classname and namespace are being displayed in the navbar.

Resolution 1440x900
![tt](https://cloud.githubusercontent.com/assets/8844652/5944369/9e1bec14-a70d-11e4-98be-b7110c21c7c7.png)

**Comment by samdark** [comment]
Verified. Doesn't matter which resolution it is. `<title` tag should start with it but header should not.

**Comment by cebe** [comment]
Oh, oops :)

**Comment by cebe** [comment]
fixed, thanks for reporting! should be online in a few hours
