### ISSUE TITLE
Bug in ArrayDataProvider, last element is sliced when pageSize=0

### ISSUE THREAD

**Issue by kirsenn** [yiisoft/yii2#7074]
Hello. So we have Pagination class with property $_pageSize and it says:
*If it is less than 1, it means the page size is infinite, and thus a single page contains all items.*
Ok, then we do:
```php
$dataProvider = new ArrayDataProvider();
$dataProvider->allModels = [....]
$dataProvider->pagination->pageSize = 0;
```

when the GridView access the data provider:
```php
protected function prepareModels()
{
...
if (($pagination = $this->getPagination()) !== false) {
    $pagination->totalCount = $this->getTotalCount();
    $models = array_slice($models, $pagination->getOffset(), $pagination->getLimit());
}
...
```

so the question is - why do we need to slice the array of models when the page is infinite? What's going on here in array_slice we have $pagination->getLimit():

```php
return $pageSize < 1 ? -1 : $pageSize;
```

$pageSize is equals to 0, but it slices the last element, why?

**Comment by qiangxue** [comment]
Thanks!
