### ISSUE TITLE
`yii fixture/load` truncate user table on production db.

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#7078]
Yii-advanced app for `test` envirement uses `test db`

```php
// \yii2-app-advanced\tests\codeception\config\config.php
'db' => [
            'dsn' => 'mysql:host=localhost;dbname=test-db',
            'username' => 'test-db',
            'password' => '1',
            'charset' => 'utf8',
        ],
```
`console` envirement uses `prod-db`

```php
// \ yii2-app-advanced\environments\dev\common\config\main-local.php
  'controllerMap' => [
        'fixture' => [
            'class' => 'yii\faker\FixtureController',
            'templatePath' => '@tests/codeception/common/templates/fixtures',
            'fixtureDataPath' => '@tests/codeception/common/fixtures/data',
            'namespace' => 'tests\codeception\common\fixtures',
        ],
    ],
  'components' => [
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost;dbname=prod-db',
            'username' => 'readonly',
            'password' => 'pass',
            'charset' => 'utf8',
        ],
    ],
```

When i run `php yii fixture/load "*"` with this configuration then I expect that will use the test database. But no:
![image](https://cloud.githubusercontent.com/assets/874234/5956172/ac973704-a7bb-11e4-872d-c54fa4736d6b.png)

How can I change this behavior?

**Comment by Ragazzo** [comment]
if you run it from application directory it will not use `Codeception` config , you should instead run it from `tests\codeception\bin` so it will read needed configs

**Comment by githubjeka** [comment]
Thank you

**Comment by Ragazzo** [comment]
for any other case see [this](https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/bin/yii) and this [one](https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/config/config.php)

**Comment by pptyasar** [comment]
I could not find tests\codeception\bin

**Comment by githubjeka** [comment]
Now it's here https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/dev/yii_test
