### ISSUE TITLE
Use of i18n\Formatter dateFormat in ActiveRecords

### ISSUE THREAD

**Issue by bpetheo** [yiisoft/yii2#7079]
When custom dateFormat/datetimeFormat/timeFormat are set, ActiveRecords are still using the yyyy-mm-dd format. I'm trying to set/get input fields in a dd/mm/yyyy format.
At the moment I've set up custom converters in afterFind() and beforeValidate() functions but I think it should natively support this feature.
GridView also doesn't support converting for ex. datetime to date format if I use a custom format like that.
My config:
```php
  'components' => [
    'formatter' => [
      'class' => 'yii\i18n\Formatter',
      'dateFormat' => 'dd/MM/yyyy',
      'datetimeFormat' => 'dd/MM/yyyy HH:mm:ss',
      'timeFormat' => 'HH:mm:ss',
    ]
  ],
```

**Comment by bpetheo** [comment]
![screenshot - 2015-01-29 - 11 10 09](https://cloud.githubusercontent.com/assets/8666715/5956210/90ff8650-a7ab-11e4-83d5-f1d8e39461e4.png)
![screenshot - 2015-01-29 - 11 11 38](https://cloud.githubusercontent.com/assets/8666715/5956211/9102bd7a-a7ab-11e4-981e-cc3d36cc36eb.png)

**Comment by cebe** [comment]
To parse input data you should use the datevalidator instead of the formatter, formatter is for output only and the values it formats should be already in machine readable format.
