### ISSUE TITLE
Bug #1568 about JsonSerializable still reproduces

### ISSUE THREAD

**Issue by fproject** [yiisoft/yii2#7084]
Bug #1568 still reproduces when I test with the latest version of Yii 2.0.
I use an ActiveController to make a RESTful that returns JSON Data.

In the model class that extends ActiveRecord I use this code:

```php
class MyModel extends \app\models\base\MyModel  implements \JsonSerializable
{
    public function jsonSerialize() {
         return ['startTime'=>'2012-12-12T00:00:00'];
    }
}
```

Expectation:
---------------------
The GET method of active controller returns a JSON object of which _startTime_ field is hard code to '2012-12-12T00:00:00'

Actual:
---------------------
The value of _startTime_ field of returned JSON object is NOT '2012-12-12T00:00:00'

**Comment by cebe** [comment]
What exactly is the problem wih that model? how do you use it and what do you get?

**Comment by fernandezekiel** [comment]
@fproject  what are you expecting in response?

**Comment by fernandezekiel** [comment]
i also don't see the necessity to use `JsonSerializable` in your model,
also `ActiveController` already implements a response serializer and what your models just have to do if you want to customize it is to override `fields()`

**Comment by fproject** [comment]
Actually I want to response all date-time fields serialized with ISO8601 instead of the default format.

And I hope that I can do that by implement JsonSerializable.

But it seems that the yii\helpers\Json doesn't use my jsonSerialize() method.

**Comment by cebe** [comment]
can you show the code of controller action and how you configured the response formatter?

**Comment by fproject** [comment]
The controller:

```php
class MyController extends ActiveController
{
    public $modelClass = 'app\models\MyModel ';

    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];
}
```

That's all.

**Comment by fproject** [comment]
@fernandezekiel : can you suggest me a solution (or workaround) for this problem?

**Comment by creocoder** [comment]
@cebe There is no issue at all. That issue should be solved via standart `Model::fields()` method.

@fproject Please read guide how to do what you want inside Yii 2: http://www.yiiframework.com/doc-2.0/guide-rest-resources.html#overriding-fields

**Comment by creocoder** [comment]
Example:

```
public function fields()
{
    return [
        'your_date_time' => function ($model) {
            return $model->your_date_time; // in any format you want, for example ISO8601
        },
    ];
}
```

**Comment by fproject** [comment]
Thank you @creocoder.

**Comment by fproject** [comment]
@creocoder : What should I do if I want all date-time fields in all model classes always be serialized as ISO8601?

I dont want to repeat that code in Model::fields() every where :(

**Comment by creocoder** [comment]
@fproject Create base model with `fields()` inside.

**Comment by cebe** [comment]
Added a test case to verify behavior. its all fine as far as I see.

**Comment by fernandezekiel** [comment]
php can't magically determine which of your fields are the date time and the ones that has to be converted into ISO8601, you will have to do it manually
