### ISSUE TITLE
IP address behind a proxy

### ISSUE THREAD

**Issue by o-rey** [yiisoft/yii2#7085]
Current implementation of getUserIP uses only REMOTE_ADDR as a source.

``
return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : null;
``

This leads to incorrect results if the server is behind a reverse proxy.
Probably it should respect HTTP_X_REAL_IP, which can be set as a proxy param in nginx.

**Comment by fernandezekiel** [comment]
@o-rey  it might not make sense anymore if we're going to extract it from something that is nginx specific, 
if we are going to look at `HTTP_X_REAL_IP`
we might as well look at 
`HTTP_X_FORWARDED_FOR`
etc..

**Comment by o-rey** [comment]
Sure. 

Btw it's not a problem to use these headers in application, but, as I can see, getUserIP is used in some core classes, for example, AccessRule::allows.

**Comment by cebe** [comment]
We can not generally rely on external headers because they could be faked and not be trusted to do IP based access control. If you have an environment where you can trust the header you can set `$_SERVER['REMOTE_ADDR']` in your init script or extend the request class.

**Comment by fernandezekiel** [comment]
you can override it based on how is your server and network is configured

**Comment by arboshiki** [comment]
+1
