### ISSUE TITLE
swiftMailer: .eml files created in runtime/debug/mail folder, but..

### ISSUE THREAD

**Issue by talovicnedim** [yiisoft/yii2#7086]
Hi everyone,

This is my common/config/mail-local.php

```
'mail' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
             'transport' => [
                    'class' => 'Swift_SmtpTransport',
                    'host' => 'smtp.gmail.com',
                    'username' => 'xxxx@gmail.com',
                    'password' => 'xxxx',
                    'port' => '465',
                    'encryption' => 'ssl',
                ],
 ],
```

This is my code:
```
 Yii::$app->mailer->compose()
          ->setFrom('xxxx@gmail.com')
          ->setTo("xxxx@gmail.com")
          ->setSubject("Exception Warning")
          ->setTextBody('Plain text content')
          ->send();
```

Files in api/runtime/debug/mail are created. But I did not receive any mail!  Can someone help me, please?

Best regards.
Nedim

**Comment by fernandezekiel** [comment]
can you see anything in your sent items in your mailing account in gmail?

**Comment by talovicnedim** [comment]
Sent Mail is empty. 

Actually, I'm using Google Apps for Work, but it doesn't matter. I am successfully logged in at gmail.com.

**Comment by dapatrese** [comment]
Could it be a problem with "mail" vs. "mailer"?

<code>
'mail' => [ ...
</code>

<code>
Yii::$app->mailer->compose()...
</code>

**Comment by cebe** [comment]
@dapatrese thanks for pointing that out. Quite sure this is the problem.

**Comment by fernandezekiel** [comment]
sure looks like the problem

**Comment by talovicnedim** [comment]
That was the problem. Thanks everyone.
