### ISSUE TITLE
Allow debug toolbar to work on different web roots

### ISSUE THREAD

**Issue by realtebo** [yiisoft/yii2#7087]
I succesfully installed advanced template app in a very complex situation.

I followed this guide: http://www.yiiframework.com/wiki/755/how-to-hide-frontend-web-in-url-addresses-on-apache/

There is a first problem with the debug toolbar (the test environment is 100% identical to production env, but has DEBUG on). It's not loaded because of this line of code [178 on actual version] into the file `yiisoft/yii2-debug/Module.php` [https://github.com/yiisoft/yii2-debug/blob/2.0.2/Module.php#L178]

    $url = Url::toRoute(['/' . $this->id . '/default/toolbar',
            'tag' => $this->logTarget->tag,
        ]);

I must change the `'/'` to `'/www/frontend/web/'` to make it run, but of course it's a very bad way, we must not modify vendor modules, because after upgrading our changes will be lost.

It could be very usefull to allow to detect the new webroot .

Actually I've this `.htaccess` file into my webroot

```
Options -Indexes

<IfModule mod_rewrite.c> 
	RewriteEngine on
	
	RewriteCond %{REQUEST_URI} !^public
	RewriteRule ^(.*)$ 	www/frontend/web/$1 [L]

</IfModule>

# Deny accessing below extensions
<Files ~ "(.json|.lock|.git)">
Order allow,deny
Deny from all
</Files>

# Deny accessing dot files
RewriteRule (^\.|/\.) - [F]
```

And this into `www/frontend/web/.htaccess` 

```
Options +FollowSymLinks
IndexIgnore */*

RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule . index.php
```

And I setup this into `www/frontend/config/main.php`

```
'urlManager' => [
            'baseUrl' => '/',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
        ]
```

Everything is working, even pretty url, so I was happy, until I discovered that debug toolbar cannot work because trying to load itself from  `http://www.domain.tld/www/frontend/web/debug/default/toolbar?tag=54ca47dbc69a2`

Now, I need your developer toolbar working, so, for today, I patched the .php source directly, but what about the future?

**Comment by samdark** [comment]
`toRoute` argument is correct. It's internal route, not URL.

**Comment by qiangxue** [comment]
The original code is correct. Your problem should be caused by your Web server configuration which is causing incorrect result of `yii\web\Request::getBaseUrl()`.

**Comment by aftavwani** [comment]
how can i open backend if i use this unable to open backend

**Comment by realtebo** [comment]
@aftavwani : did you find any solution?
