### ISSUE TITLE
i18n, many

### ISSUE THREAD

**Issue by nepster-web** [yiisoft/yii2#7093]
Проблема появилась с русским языком, поэтому есть смысл написать issue на русском. 

Идем в доки:
https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/tutorial-i18n.md#%D0%9C%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5-%D1%87%D0%B8%D1%81%D0%BB%D0%BE

Копируем вот эту строку и ставим n равно 6:
```
      echo \Yii::t(
            'app',
            'На диване {n, plural, =0{нет кошек} =1{лежит одна кошка} one{лежит # кошка} few{лежит # кошки} many{лежит # кошек} other{лежит # кошки}}!',
            ['n' => 6]
        );
```

Я вижу:
```
На диване лежит 6 кошки!
```

intl присутствует:
```
intl
Internationalization support	enabled
version 	1.1.0
ICU version 	51.2
ICU Data version 	51.2

Directive	Local Value	Master Value
intl.default_locale	no value	no value
intl.error_level	0	0
intl.use_exceptions	0	0
```

**Comment by Borales** [comment]
@nepster-web подтверждаю, по какой-то причине начало игнорироваться условие "many" (хотя раньше кажется не было такой проблемы).
icu @54.1_0 (active)
php55-intl @5.5.20_0 (active)

**Comment by nepster-web** [comment]
Я порылся в поиске, добавил в композер вот такую штуку:
```
"ext-intl": "*"
```
Не помогло. 

Потом порылся еще, и где-то нашел упоминания про:

```
    'sourceLanguage' => 'ru-RU',
```

И только тогда все заработало. Хотя я до сих пор не понял, зачем sourceLanguage ?

**Comment by nepster-web** [comment]
@Borales у вас работает с sourceLanguage ? Причина действительно в нем ?

**Comment by tecnologiaterabyte** [comment]
http://php.net/manual/es/intl.installation.php

**Comment by Borales** [comment]
@nepster-web `sourceLanguage` - это язык сообщений, которые пишутся непосредственно в коде (тоесть "с какого переводить"). Смена sourceLanguage ничем не помогла

**Comment by samdark** [comment]
Добавил тест. Всё работает. Вы просто используете русский в исходных строках и `sourceLanguage` у вас не `ru`. То есть логика форматирования у вас используется не та.

Посмотрите на тест, который я добавил.

**Comment by Borales** [comment]
@nepster-web можете проверить у себя https://github.com/yiisoft/yii2/commit/7e868555c5f177de15f8c5a751c8e8968cc78fa3#commitcomment-9525792 ?

**Comment by nepster-web** [comment]
@Borales без установленного ```sourceLanguage``` не работает. Только с ним.

**Comment by samdark** [comment]
Ну всё правильно: https://github.com/yiisoft/yii2/commit/7e868555c5f177de15f8c5a751c8e8968cc78fa3#commitcomment-9528528

**Comment by nepster-web** [comment]
Получается это не баг, это фича. =) 
Большое спасибо за объяснение.
