### ISSUE TITLE
asArray() seems wrong when use the data in json_encode. The numeric data was added double quote.

### ISSUE THREAD

**Issue by kamote** [yiisoft/yii2#7096]
Using asArray()
```
$staffs = Staff::find()->asArray()->all();
echo json_encode($staffs);
```
Wrong OutPut field `id` is numeric
```
[{"id":"1","branch_id":"2","first_name":"Kahoy Na","last_name":"Kamote","email":"jigs@sample.com","phone":"09263599006"}];
```

Using ArrayHelper to conver the object data
```
$staffs = Staff::find()->all();
echo json_encode(ArrayHelper::toArray($staffs));
```
Output w/ a quote
```
[{"id":1,"branch_id":2,"first_name":"Kahoy Na","last_name":"Kamote","email":"jigs@sample.com","phone":"09263599006"}];


Yii version: 2.0.3-dev
```

**Comment by dmitriy-krista** [comment]
According to ActiveRecord's documentation:
>...When using asArray the result will be returned as a simple array with no typecasting performed so the result may contain string values for fields that are integer when accessed on the active record object.

So your output doesn't seem wrong.

**Comment by creocoder** [comment]
All fine with output. If you need integers iinstead of strings you should use `fields()` method and explicitly convert types.

**Comment by kamote** [comment]
@dmitriy-krista thanks!
