### ISSUE TITLE
Updating grid with ajax

### ISSUE THREAD

**Issue by rberet** [yiisoft/yii2#7099]
Hi there,

this is my Text Input and Submit Button:

```
echo Html::textInput("InspectionCaseSearch[case_number]"]);
echo Html::submitButton('Search', ['class' => 'btn btn-primary', 'id' => 'search-btn']);
```
How could I pass these additional data (case_number) and filter the grid? Text input is outside of the grid/form.

Best regards.
rberet

**Comment by githubjeka** [comment]
Use common `$model->search()` and please use forum for your questions. Best regards.
