### ISSUE TITLE
Random 'Trying to get property of non-object' Error when DB Schema Cached with memcache

### ISSUE THREAD

**Issue by IndeedPlusPlus** [yiisoft/yii2#7100]
My OS is Ubuntu 14.04.1 LTS. PHP is working as a module of apache2.
PHP version is 5.5.9-1ubuntu4.5

The problem is that an error 8 'Trying to get property of non-object' will randomly raise if table schema is cached with MemCache. Here is how to reproduce it.

Firstly, let's create the project under the document root. To keep it simple, I use the basic template.
For me the document root is `/home/indeed/public_html`
`$ composer create-project --prefer-dist yiisoft/yii2-app-basic basic`

Then create a model, a page for example.
```php
<?php
namespace app\models;

use yii\db\ActiveRecord;

/**
 * Class Page
 * @package app\models
 * @property $id
 * @property $title
 * @property $content
 */
class Page extends ActiveRecord
{

}

```
And the view, as simple as displaying the content of a Page instance.
`basic/views/site/page.php`
```php
<?php
use app\models\Page;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $page Page */

$this->title = $page->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-page-<?= $page->id ?>">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= Html::encode($page->content); ?>
</div>

```
Then the action.
`basic/controllers/SiteController.php`
```php
/* ... */
    public function actionPage($id)
    {
        $id = intval($id);
        $page = Page::findOne($id);
        if ($page === null)
            throw new NotFoundHttpException('Page not found.');
        return $this->render('page', ['page' => $page]);
    }
/* ... */
```
Next we create schema and insert one line of data. I use MySQL here.
```sql
CREATE TABLE IF NOT EXISTS `page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `page` (`id`, `title`, `content`) VALUES
(1, 'How To Start An Argument Easily', 'State that PHP is the best programming language in the world.');

```
A neat page will be displayed when accessed by URL. Here we make some setup.
We enable the schema cache in `basic/config/db.php`
```php
<?php

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=localhost;dbname=yii2basic',
    'username' => 'yii2basic',
    'password' => '',
    'charset' => 'utf8',
    'enableSchemaCache' => true,
];
```
Then MemCache in `basic/config/web.php`
```php
<?php

$params = require(__DIR__ . '/params.php');

$config = [
/* ... */
        'cache' => [
            'class' => 'yii\caching\MemCache',
        ],
/* ... */
]
```
Now please browse to the page with id=1, restart memcached, go back to browser and press F5 repeatedly, things work fine most of time but sometimes you will get an error like that.
```
exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in /home/indeed/public_html/basic/vendor/yiisoft/yii2/db/ActiveRecord.php:320
Stack trace:
#0 /home/indeed/public_html/basic/vendor/yiisoft/yii2/db/BaseActiveRecord.php(101): yii\db\ActiveRecord::findByCondition()
#1 /home/indeed/public_html/basic/controllers/SiteController.php(102): yii\db\BaseActiveRecord::findOne()
#2 /home/indeed/public_html/basic/vendor/yiisoft/yii2/base/InlineAction.php(55): app\controllers\SiteController->actionPage()
#3 /home/indeed/public_html/basic/vendor/yiisoft/yii2/base/InlineAction.php(55): ::call_user_func_array()
#4 /home/indeed/public_html/basic/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams()
#5 /home/indeed/public_html/basic/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction()
#6 /home/indeed/public_html/basic/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction()
#7 /home/indeed/public_html/basic/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest()
#8 /home/indeed/public_html/basic/web/index.php(12): yii\base\Application->run()
#9 {main}
```
Later I use burden test tool against it only to see Apache causing segment faults. The error log shows something like that. A pity that I did not see any core dumps, probably because I am not using the debug version of the Apache package.
```
[Fri Jan 30 18:00:21.681939 2015] [core:notice] [pid 11240] AH00051: child pid 1807 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Fri Jan 30 18:02:20.778842 2015] [core:notice] [pid 11240] AH00051: child pid 1809 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Fri Jan 30 18:10:46.185427 2015] [core:notice] [pid 11240] AH00051: child pid 3163 exit signal Segmentation fault (11), possible coredump in /etc/apache2
```
The problem can be solved by turning schema cache off or use another cache approach. So I am quite sure the problem is caused by usage of memcache extension or the extension itself.

Do you have any idea what might go wrong?

**Comment by IndeedPlusPlus** [comment]
Reproduced with the docker image version of Ubuntu 14.04.

**Comment by klimov-paul** [comment]
What version of MemCache server do you use?
Which PHP extension you are using: 'memcache' or 'memcached'? Which version?

**Comment by IndeedPlusPlus** [comment]
The problem disappeared when I switch to memcached extension from the default memcache extension.(set `'useMemcached' => 1`)

memcache extension: Version	3.0.8	$Revision: 329835 $
memcached extension: Version	2.1.0 libmemcached version	1.0.8
memcached package version: 1.4.14-0ubuntu9

**Comment by IndeedPlusPlus** [comment]
Tried on CentOS 7 (php 5.4.16, same memcache extension version, no memcached extension), The bug cannot be reproduced. Maybe it was the memcache extension that went wrong after all.

**Comment by IndeedPlusPlus** [comment]
Tried to compile PHP 5.5.21 with memcache extension from source. The problem can be reproduced. I think there is compatibility problem between PHP 5.5 and memcache extension.

**Comment by IndeedPlusPlus** [comment]
Well, I think this is not Yii but the PHP or the extension maintainers' fault. I hope if someone else encounter such problem they may be able to get to this page after some Google searching. :)
