### ISSUE TITLE
Object::className() to have a flag whether to return a FQCN or just a base name

### ISSUE THREAD

**Issue by turboexe** [yiisoft/yii2#7101]
Currently ``yii\base\Object::className`` only returns FQCN. It's great such a method exists, but would be even better if there'd be a way to get just the base class name. Check out the following usecase:
```php
$form = new EntityForm(['scenario' => EntityForm::SCENARIO_CREATE]);
$request = Yii::$app->request;

$requestData = $request->post(StringHelper::basename(EntityForm::className()));
```
As you can see, I'm urged to use StringHelper to truncate the FQCN to just a base name. In the example above I could just use a string 'EntityForm' instead of calling ``::className()``, but I like autocompletion and stuff very much. And yii2 has greately improved itself in this if you compare with yii1.

Imagine renaming the EntityForm to something else in a modern IDE. If you use a string, it won't pick up and autorename it, but since I use ``::className()``, it'll just work as it should.

It's a pretty easy feature to implement, I'll make a pull request soon.

**Comment by turboexe** [comment]
pull request #7102

**Comment by klimov-paul** [comment]
Why don't use `Model::formName()`?
```php
$requestData = $request->post($form->formName());
```
Or `Model::load()`?
```php
$form->load($_POST);
```

**Comment by turboexe** [comment]
@klimov-paul 
Thanx, didn't know ``Model::formName()`` exist. So if we have this code already for models, why won't we have it for any object? in order to make it backwards compatible, we can leverage the new flag of  ``::className()`` method within ``->formName()`` method like this:
```php
public function formName()
{
    return self::className(true);
}
```

**Comment by klimov-paul** [comment]
> So if we have this code already for models, why won't we have it for any object?

Because it does not make any sense. Unless there is a sugnificant use case for it, which I can not see by now, there is no need for extra logic around `Object::className()`.

> In regards of $form->load($_POST): yii2 is trying to be the on the edge of technologies, why would anyone use $_POST instead of a built-in framework request component like we're still in php4?

This was just a quick example, you can use `Request::post()` or `Request::getBodyParams()`:
```php
$form->load($request->post());
```
