### ISSUE TITLE
validate unique together (two column)

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#7107]
example 
unique together column user_id and column post_id
note : user_id and post_id together primarykey
array[ 'user_id,post_id' , 'unique' ]

**Comment by samdark** [comment]
@EngRajabi please elaborate what's the issue?

**Comment by lynicidn** [comment]
кстати вчера мучал тоже такую валидацию, и ошибка всегда вылетает на 2 поля, хоть и есть там спец параметр я его не завел, пробовал и ['a1', 'exist', 'targetAttribute' => ['a1', 'a2']] и просто
[['a1','a2'], 'exist'].
п.с. и еще не стал заводить ишью, но перестала рработать такая выборка лейблов
Model::find()->select(['a1','a2'])->indexBy('a2')->column() еще с полгода назад работало и было удобно без arrayhelper'a

**Comment by EngRajabi** [comment]
Sometimes want two or .....  column together all unique validate
example
tbl_user column name,password,email,date
rules  : 
array('name,email','unique');
means name and email user together unique validate

**Comment by mdmunir** [comment]
Is this what you mean?
http://www.yiiframework.com/doc-2.0/yii-validators-uniquevalidator.html
```php
[['name', 'email'], 'unique', 'targetAttribute' => ['name', 'email']]
```

**Comment by EngRajabi** [comment]
i dont know but like Extensions to yii 1
link : http://www.yiiframework.com/extension/unique-multiple-columns-validate/

**Comment by lynicidn** [comment]
u have problem or u don't know how use it?

**Comment by qiangxue** [comment]
@EngRajabi Please read the API doc for UniqueValidator. This is already supported.
