### ISSUE TITLE
Multi Controller Name for an Url Rule?

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#7108]
I want to use like this url rule:
www.example.com/{CategoryName}
www.example.com/{NewsName}

Then i added into frontend/config/main.php;
'\<seo:[\w\-]+\>' => 'news/index',
'\<seo:[\w\-]+\>' => 'category/index',

But this isn't working that's normal, I know, but i need this, i have to do, do you know about this something? How can i do?

Thanks for everything.

**Comment by samdark** [comment]
It works as expected so there's no issue. Please post questions to the forum. Thanks!

**Comment by Faryshta** [comment]
there is no way to give support for that on php

'<seo:[\w-]+>' => 'news/index',
'<seo:[\w-]+>' => 'category/index',

the second one rewrites the first one, so its like if you had never wrote the first entry at all.

what you have to do is create a new controller SeoController with an index method and there you choose if the route provided is a news or a category

**Comment by lynicidn** [comment]
array with dublicate key ?

**Comment by lynicidn** [comment]
reverse russian topic http://yiiframework.ru/forum/viewtopic.php?f=19&t=21819&p=129539&hilit=2+%D1%80%D0%BE%D1%83%D1%82%D0%B0#p129539

**Comment by serhatozles** [comment]
I solved such;
main.php
		['pattern' => '\<seo:[\w\-]+\>', 'route' => 'category/index'],
		['pattern' => '\<seo:[\w\-]+\>', 'route' => 'news/index'],
and then added CategoryController.php
	if (is_null($CategoryDetails)) {
	    $News = Yii::$app->createControllerByID('news');
	    return $News->actionIndex($seo,$ref);
	    throw new NotFoundHttpException('Sayfa Bulunamadı.');
	}

Thanks for everything.

**Comment by sieulog** [comment]
But If you have multiple category - gallery, post, video, product. It is bad solutions
