### ISSUE TITLE
Call bower in separate vendor directory

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#7112]
Hello I want to ask something
I create the multiple advance yii2 template, after being separated the directory like

-htdocs
---advancedyii2application1
---advancedyii2application2
------backend
------common
------console
------environtments
------frontend
------and other
---yii2
------vendor
------composer.json
------and other

I setting the vendor in common\config\main.php and change the vendor to directory like this :
```php
'vendorPath' => dirname(dirname(__DIR__)) . '/../yii2/vendor',
```

but for (example) FontAwesomeAsset the vendor when I call
```php
public $sourcePath = '@vendor/fortawesome/font-awesome';
```

Give the **"The file or directory to be published does not exist: C:\xampp\htdocs\advancedyii2application2\vendor\....."** Error

How to configure "@vendor" alias, to get the separated @vendor or @bower like structure like I write above
Sorry for my stupid question and description

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for bug reports and feature requests. Thanks!

**Comment by adiramardiani** [comment]
I think this is important to add in AppAssets Documentation...

**Comment by cebe** [comment]
what do you think is missing in the documentation?
