### ISSUE TITLE
DB connection in yii2

### ISSUE THREAD

**Issue by Nishatkauser** [yiisoft/yii2#7114]
I simply overwrite the getDb() in model like that

 public static function getDb() {
     
        $ip=Yii::$app->session['dns'];
		$dbuser = Yii::$app->session['dbuser'];
		$dbpassword= Yii::$app->session['dbpassword'];
		
		$dns= 'mysql:host='.$ip.';dbname=db';
	 $connection =  new Connection([
    'dsn' =>$dns,
    'username' => $dbuser,
    'password' => $dbpassword,
	 
]);
 

  return $connection;
}

It really taking so much time to complete the request as compare to use Yii::$app->db;
when I debug the request I saw 140 times It access the database and 
	10:55:16.741	1251.1 ms	yii\db\Connection::open	Opening DB connection: mysql:host=199.168.190.91;dbname=vos3000db
2	10:55:17.992	452.0 ms	yii\db\Command::query	SELECT COUNT(*) FROM `e_cdr`
3	10:55:18.447	1298.1 ms	yii\db\Connection::open	Opening DB connection: mysql:host=199.168.190.91;dbname=vos3000db
4	10:55:19.745	449.0 ms	yii\db\Command::query	SHOW FULL COLUMNS FROM `e_cdr`
5	10:55:20.200	444.0 ms	yii\db\Command::query	SHOW CREATE TABLE `e_cdr`
6	10:55:20.647	1306.1 ms	yii\db\Connection::open	Opening DB connection: mysql:host=199.168.190.91;dbname=vos3000db
7	10:55:21.954	438.0 ms	yii\db\Command::query	SELECT * FROM `e_cdr` LIMIT 20
8	10:55:22.394	1343.1 ms	yii\db\Connection::open	Opening DB connection: mysql:host=199.168.190.91;dbname=vos3000db
9	10:55:23.738	450.0 ms	yii\db\Command::query	SHOW FULL COLUMNS FROM `e_cdr`
10	10:55:24.192	442.0 ms	yii\db\Command::query	SHOW CREATE TABLE `e_cdr`
11	10:55:24.636	1263.1 ms	yii\db\Connection::open	Opening DB connection: mysql:host=199.168.190.91;dbname=vos3000db
12	10:55:25.900	420.0 ms	yii\db\Command::query	SHOW FULL COLUMNS FROM `e_cdr`

like that please help me what should I do ???????????????????????

**Comment by mdmunir** [comment]
:-1: 
- Click `Preview` before posting.
- Use official forum or fb page fo asking.
- For your case, it because new connection always be created when call `getDb()`. Connection should be create once.
```php
private static $_connection;
public static function getDb()
{
    if(self::$_connection === null){
        $ip=Yii::$app->session['dns'];
        $dbuser = Yii::$app->session['dbuser'];
        $dbpassword= Yii::$app->session['dbpassword'];

        $dns= 'mysql:host='.$ip.';dbname=db';
        self::$_connection =  new Connection([
            'dsn' =>$dns,
            'username' => $dbuser,
            'password' => $dbpassword,
        ]);
    }
    return self::$_connection;
}
```
