### ISSUE TITLE
endPage call stops CSRF cookie being set

### ISSUE THREAD

**Issue by dickoms** [yiisoft/yii2#7115]
Using version 2.0.2, php 5.5.11

Problem: I'm getting "Bad Request (#400) - Unable to verify your data submission" when I submit a login form.

Bottom of my main layout looks like this:

```php
...
<?= $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>
```

The current `endPage` looks like this:

```php
public function endPage($ajaxMode = false)
    {
        $this->trigger(self::EVENT_END_PAGE);

        $content = ob_get_clean();

        echo strtr($content, [
            self::PH_HEAD => $this->renderHeadHtml(),
            self::PH_BODY_BEGIN => $this->renderBodyBeginHtml(),
            self::PH_BODY_END => $this->renderBodyEndHtml($ajaxMode),
        ]);

        $this->clear();
    }
```

Performing an `echo` in `endPage` causes the headers to be set so future calls to `headers_sent` will return `true`. This is a similar issue to this one https://github.com/yiisoft/yii2/issues/541

The `sendHeaders` method looks like this:

```php
protected function sendHeaders()
    {
        if (headers_sent()) {
            return;
        }

       // other headers sent here, removed for clarity

        $this->sendCookies();
    }
```

Unfortunately since `endPage` is called before `sendHeaders` the csrf cookie is never set.

If I remove the `endPage` call then csrf cookie is set correctly.

For reference this is a standard login controller & view. Included below for completeness:

```php
public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
```
```php
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="block clearfix">

            <div class="content-block">
                <h1>Login</h1>
                <div class="line4"></div>

                <p>Please fill out the following fields to login:</p>

                <div class="row">
                    <div class="col-md-12">
                        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                            <?= $form->field($model, 'email') ?>
                            <?= $form->field($model, 'password')->passwordInput() ?>
                            <?= $form->field($model, 'rememberMe')->checkbox() ?>
                            <div style="color:#999;margin:1em 0">
                                If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                            </div>
                            <div class="form-group">
                                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                            </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

**Comment by samdark** [comment]
Why `endPage` is called before `sendHeaders` for you?

**Comment by dickoms** [comment]
I've no idea. It's the standard `SiteController`, I've not made any changes to it.

**Comment by qiangxue** [comment]
The `render()` method will start an output buffer, which should prevent the headers from being sent when `echo` is called in `endPage()`. Please check if you `echo` something before `actionLogin()` is called. Also verify if this problem occurs to the standard installation of the basic app (it shouldn't happen because otherwise many people would complain about this problem).

**Comment by dynasource** [comment]
same problem over here after a composer update. Dont no yet what is causing it.

**Comment by dynasource** [comment]
after setting enableCookieValidation to false (I hadnt set this variable at forhand) for the test environment, tests work again.

**Comment by dickoms** [comment]
@qiangxue stepping through the code I've put a watch on `headers_sent()`. Before I step over:

```php
 echo strtr($content, [
            self::PH_HEAD => $this->renderHeadHtml(),
            self::PH_BODY_BEGIN => $this->renderBodyBeginHtml(),
            self::PH_BODY_END => $this->renderBodyEndHtml($ajaxMode),
        ]);
```

`headers_sent()` is returning `false`. As soon as I step over the echo  `headers_sent()` returns `true`

To temporarily fix the problem I've set `enableCsrfCookie` to `false`

**Comment by qiangxue** [comment]
@dynasource There's a commit recently which changes the way of how cookies are protected from tampering. This may cause CSRF validation failure once. If you retry it, it should be fine. Let me know if you can still reproduce the issue.

@dickoms As I said, this `echo` is enclosed within an output buffer started by the `render()` method. You may insert code before `echo` to double check if there is an active output buffer.

**Comment by dynasource** [comment]
@qiangxue: that is correct. I had it once when logging in with the Browser. After that, no issues.
Hower, my Codeceptions tests fail with this setting on true.

**Comment by sreenadh** [comment]
@qiangxue  "There's a commit recently which changes the way of how cookies are protected from tampering. This may cause CSRF validation failure once. If you retry it, it should be fine"

The csrf cookie is not generated when my login form is rendered first. when I submit form, form submission fails, csrf cookie is generated and I've to again submit the form. how can I force the csrf cookie generation?

**Comment by qiangxue** [comment]
Please check if your login form contains a hidden field for csrf token. If so, the CSRF cookie should be sent (done via `yii\web\Request::getCsrfToken()`)

**Comment by TriAnMan** [comment]
Looks that I have the same issue with functional tests but not with acceptance tests. This issue appears after upgrading yii from 2.0.2 to 2.0.4
I'll try to investigate the source of it.

**Comment by TriAnMan** [comment]
Looks that there is a lot of missing headers including `SetCookie`:
```
# ../vendor/bin/codecept run functional LoginCept.php -vvv
Codeception PHP Testing Framework v2.0.13
Powered by PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Frontend.functional Tests (1) ----------------------------------------------------------------------
Modules: Filesystem, Yii2, FixtureHelper, ExceptionHelper, Asserts
---------------------------------------------------------------------------------------------------
Ensure login page works (LoginCept)
Scenario:
* I am on page "/index-test.php/login"

  [Response] 200
  [Page] http://frontend/index-test.php/login
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I am going to submit login form with no data
* I fill field "input[name="LoginForm[email]"]",""
* I fill field "input[name="LoginForm[password]"]",""
* I click "login-button"
  [Uri] http://frontend/index-test.php/login
  [Method] POST
  [Parameters] {"_csrf":"N2hWMHMwUXR.GSRYPF85GVkRNwEFXhInQzxkAQZ9KTVyGDlEFEEkAw==","LoginForm":{"email":"","password":"","rememberMe":"1"},"login-button":null}
  [Response] 400
  [Page] http://frontend/index-test.php/login
  [Cookies] {"_csrf":"159542daf754d8b29296634afe2d56e15a1caaeb909f4b24641e56077b886a22s:32:"IqrhOohmnya1vnCStT21uMxAEpotgquw";"}
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I expect to see validations errors

```

**Comment by cebe** [comment]
@TriAnMan please open a new issue and describe the problem in more detail. It is hard to tell whether this is really the same thing or not. starting from a clean report makes it easier to find the cause.
