### ISSUE TITLE
Database Connection Problem

### ISSUE THREAD

**Issue by abhi1693** [yiisoft/yii2#7118]
I have programmatically setup the database connection

```php
Yii::$app->set('db', [
						'class'    => 'yii\db\Connection',
						'dsn'      => $dsn,
						'username' => $username,
						'password' => $password,
						'charset'  => 'utf8'
					]);

try{
     Yii::$app->db->open();
}catch(Exception $e){
     print_r('error');
}
```

According to the above values, if the the connection is successful, a new file is generated which contains the `db` config as follows:

```php
return array(
		'components' =>
			array(
				'db' =>
					array(
						'class'    => 'yii\\db\\Connection',
						'dsn'      => 'mysql:host=localhost;dbname=starter-kit',
						'username' => 'abhimanyu',
						'password' => '',
						'charset'  => 'utf8',
					),
			),
	);
```

The connection works fine but I have to open the connection everytime I have to work with the database. Is there any solution to this? Thanks

**Comment by lynicidn** [comment]
conection be closed after work php script

**Comment by abhi1693** [comment]
How can I keep the connection alive? As in without re-opening it everytime.

**Comment by samdark** [comment]
Google for PDO persistent connection. Closing as it's not Yii issue.
