### ISSUE TITLE
blockquote types in the guide (e.g. "Note", "Info", "Tip" and "Warning")

### ISSUE THREAD

**Issue by softark** [yiisoft/yii2#7120]
In the guide for Yii 1, we have the following features for block-quoted paragraphs:

1. Different Icons for different types
2. Different background colors for different types
3. Syntax for translating types ... `<Type>|<Translation>:`

Do you have a plan to implement the same features for the Yii 2 guide?

**Comment by cebe** [comment]
yes, I have this planned.

**Comment by softark** [comment]
Thank you. It's nice to know that.

**Comment by cebe** [comment]
fixed by https://github.com/yiisoft/yii2-apidoc/commit/08fc88ab18e223fa0d0392f9d15b67625a779c2d
