### ISSUE TITLE
Why is `name` attribute required for `Jui` widgets?

### ISSUE THREAD

**Issue by nirvana-msu** [yiisoft/yii2#7127]
What is the point of forcing users to specify a value for `name` attribute of `Jui` widgets, e.g. `AutoComplete`? From what I can tell this is not being used anywhere apart from passing it to `Html::textInput`, which, btw, accepts `null` value.

P.S. I'm obviously considering the case where `model` is not set.

**Comment by cebe** [comment]
Removed the check. It is now possible to leave it empty.

**Comment by nirvana-msu** [comment]
Thanks!
