### ISSUE TITLE
intercooler.js as addition or alternative to pjax

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii2#7129]
Hi,

how do you like the idea of adding an additional lib like pjax to handle ajax request without js?

see: http://intercoolerjs.org/

Thanks Philipp

**Comment by creocoder** [comment]
@philippfrenzel Thanks for sharing! Its awesome :+1:

**Comment by tecnologiaterabyte** [comment]
+1 👍

**Comment by samdark** [comment]
It clearly does the same thing as PJAX. Do you have experience using it? How good it's when dealing with multiple fragments and browsers history?

**Comment by dynasource** [comment]
Interesting framework. Seems to have more functionality with still being unobtrusive.

**Comment by philippfrenzel** [comment]
Is mentioned in German php magazin ;) more details there!

**Comment by usualdesigner** [comment]
IMO Intercooler looks more rich and functionality than PJAX

**Comment by dynasource** [comment]
PJAX is nice but has its deficiencies (parts of these already acknowledged by the maker):
- loss of current form post after inline pjax calls
- redirect handling 
- error catching 
- empty page returns
- flexibilty on attaching

Apart from the nice features/examples of intercooler, if it performs better on the examples above, I will make the switch soon.

**Comment by samdark** [comment]
I've checked intercooler in detail. While it's quite interesting, there's declarative way of dealing with things only. While it's great for many cases, it doesn't work if you want to trigger loading fragments from JavaScript that's not acceptable.

**Comment by samdark** [comment]
So overall it cannot replace PJAX.
