### ISSUE TITLE
ActiveForm validation errors

### ISSUE THREAD

**Issue by MUTOgen** [yiisoft/yii2#7133]
Hello!
Is there any way to clear field's error on focus event?
My validation works on submit with ajax, so i need to clear error after user focus field.

**Comment by cebe** [comment]
as far as I see, there is not: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L161

**Comment by dynasource** [comment]
this is something you have to code yourself manually. Feel free to create PR with a solution though.
