### ISSUE TITLE
Unable to find 'frontend\controllers\RegionController' in file: C:\xampp\htdocs\advanced/frontend/controllers/RegionController.php. Namespace missing?

### ISSUE THREAD

**Issue by franzcisq** [yiisoft/yii2#7134]

**Comment by franzcisq** [comment]
any help please???

**Comment by samdark** [comment]
Please use forums for questions. Thanks!

**Comment by mdmunir** [comment]
@samdark 
I am not using windows, so i cannot reproduce this issue. But i often receive the same question.
Its because code `dirname(__DIR__)` sometimes return using `slash`, sometimes using `backslash`.
So, what Yii solution about this issue?

**Comment by samdark** [comment]
@mdmunir it should not matter. Windows can deal with both `/` and `\` in paths.

**Comment by mdmunir** [comment]
Sorry, i dont get your answers.
It become problem for this case.
```php
Yii::setAlias('mypath',dirname(__DIR__)); // C:\xampp\htdocs

Yii::setAlias('otherpath','@mypath/sub/path'); // C:\xampp\htdocs/sub/path
```
I am not sure `C:\xampp\htdocs/sub/path` is a right path.

**Comment by cebe** [comment]
> I am not sure C:\xampp\htdocs/sub/path is a right path.

PHP can correctly resolve that to `C:\xampp\htdocs\sub\path`
