### ISSUE TITLE
attribute alias for active record

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#7136]
I think i found a way to give support to alias for attributes in active record.

I am thinking on a syntax `alias => attribute` like this

```php
public function attributes()
{
    return array_merge(parent::attributes(), [
        'categoryId' => 'category_id',
        'categoryName' => 'category.name',
    ]);
}
```
The attributes will be available to write and read by:

```php
$producto = Producto::find()->joinWith('category')->where(['id' => $id])->one();
echo $product->categoryId;
// if joinWith('category') is not executed this will return null
echo $product->categoryName;
```
I find it mostly useful because the column names in tables tend to be in the under_score style and the object properties in php tend to be in camelCase.

I think the only class to change is the `yii\db\BaseActiveRecord` class which has a private `_attributes` property.

Is this a huge change?

**Comment by cebe** [comment]
We had this discussion before, even if it is possible to be implemented we decided to not do it because there is confusion of one attribute having two names, if you write plain SQL in WHERE you would have to use real name while with array syntax you would use the alias.

**Comment by Faryshta** [comment]
yeah, i started to prepare a branch and stopped when I though on the same and its when i decided to make this issue.

**Comment by xeoshow** [comment]
Is it still the final decision till now (2018.07.27) ? Thanks!`

**Comment by samdark** [comment]
Yes.
