### ISSUE TITLE
Bug in join like

### ISSUE THREAD

**Issue by nepster-web** [yiisoft/yii2#7138]
I read doc
https://github.com/yiisoft/yii2/blob/master/docs/guide/db-query-builder.md:

```
like: operand 1 should be a column or DB expression, and operand 2 be a string or an array representing the values that the column or DB expression should be like. For example, ['like', 'name', 'tester'] will generate name LIKE '%tester%'. ...
```

I built my query:
```php
        $name = Yii::$app->request->get('name');
        $categories = Category::find()
            ->joinWith([
                't' => function ($query) use ($name) {
                    $query->where(['like', 'name', $name]);
                },
            ])
            ->asArray()
            ->all();
```

This code generates a sql:
```sql
SELECT `product_categories`.* FROM `product_categories` LEFT JOIN `product_category_translates` ON `product_categories`.`category_id` = `product_category_translates`.`category_id` WHERE `name` LIKE '%Электро%''
```

The problem is that  the end query has '', but must be '. 
Why this happen?

My error:
```
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
The SQL being executed was: SELECT `product_categories`.* FROM `product_categories` LEFT JOIN `product_category_translates` ON `product_categories`.`category_id` = `product_category_translates`.`category_id` WHERE `name` LIKE '%Электро%'' 
```

**Comment by lynicidn** [comment]
The problem is that the end query has '', but must be '. 
1 кавычка - это вы лгун

**Comment by nepster-web** [comment]
Я вас не понял, но и возможно меня никто не понял с мои топорным английским. Момент в том, что в запросе в конце лишняя кавычка. Откуда она ?

**Comment by lynicidn** [comment]
вот именно - откуда она? показывайте весь код, а телепатов битва по тнт идет

**Comment by nepster-web** [comment]
это и есть весь код

**Comment by lynicidn** [comment]
а чему $name равен?

**Comment by lynicidn** [comment]
я распарсил у вас ошибка в передаваемых параметрах, вы не указали, что вы их передаете - лгун?

**Comment by lynicidn** [comment]
и кавычка идет от Exception

**Comment by lynicidn** [comment]
она не выполняется в sql

**Comment by nepster-web** [comment]
![1](https://cloud.githubusercontent.com/assets/5681979/6008051/4be2d192-ab27-11e4-9066-6268c8199ada.png)

**Comment by lynicidn** [comment]
1. return goBack
2. u have function getT() ?

**Comment by lynicidn** [comment]
u have relation `t` ?

**Comment by nepster-web** [comment]
1) fix
2) Yes:
```
    public function getT($langId = null)
    {
        $langId = $langId ? $langId : Yii::$app->dbTranslator->getLanguage('lang_id');

        return $this->hasOne(CategoryTranslates::className(), ['category_id' => 'category_id'])
            ->where('lang_id = :lang_id OR (lang_id = :default_lang_id)', [
                    ':lang_id' => $langId,
                    ':default_lang_id' => Yii::$app->dbTranslator->getDefaultLanguage('lang_id')
                ]
            );
    }
```

**Comment by nepster-web** [comment]
the problem is in quotes. If you remove it, it works.

this works:
```sql
SELECT `product_categories`.* FROM `product_categories` LEFT JOIN `product_category_translates` ON `product_categories`.`category_id` = `product_category_translates`.`category_id` WHERE `name` LIKE '%Электро%'
```

**Comment by lynicidn** [comment]
poreblem here
```php
 ->where('lang_id = :lang_id OR (lang_id = :default_lang_id)',
```

**Comment by lynicidn** [comment]
вообщем попробуй разбить на orWhere

**Comment by nepster-web** [comment]
там специально так должно быть, если разбить на orWhere, но чуть другой результат выходит. Это я думаю это большая багачина с кавычками. Нужно подождать Александра, он что-то придумает.

**Comment by lynicidn** [comment]
>Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
вот проблема, т.е. кол-во биндиных параметров не соответствует расставленным флагам

**Comment by nepster-web** [comment]
@lynicidn проблема именно на стороне Yii2. 
Я только что использовал этот же код, в другом контексте:
```php
        $category = Category::find()
            ->orderBy('rand()')
            ->joinWith('t')
            ->one();

        print_r($category->t->name);
```

Все отлично работает.

**Comment by lynicidn** [comment]
а ты не путаешь с innerJoin?

**Comment by lynicidn** [comment]
или right join тебе нужен

**Comment by nepster-web** [comment]
не смотрите на join вообще. 
Суть такая, что стилистически код записан верно. По частям и в определенных контекстах он работает верно. Проблема только в том, что при определенном вызове (указанном выше) рисуется дополнительная кавычка. Не важно где она рисуется, она рисуется самим yii2, можете попробовать кинуть в меня камень, но я делаю ставку на баг.

**Comment by lynicidn** [comment]
хорошо, но откуда такая ошибка, вы жее и скопипастили:
>Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

**Comment by lynicidn** [comment]
log тоже выделяет фразу в кавычку, возможно вы ее там увидели и наводите шорох :)

**Comment by nepster-web** [comment]
Нет, я думаю в этом нет смысла. Я просто нашел нестыковку и хочу помочь сделать yii2 лучше. 

Еще раз, специально для Вас. 
```php
    public function actionSelectCategory()
    {
        $name = 'Электро';

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            $categories = Category::find()
                ->joinWith([
                    't' => function ($query) use ($name) {
                        // $query->where(['like', 'name', $name]);
                    },
                ])
                ->asArray()
                ->all();

            return $categories;
        }

        return $this->goBack();
    }
```

Весь код экшина, отлично работает. Обратите внимание я закомментировал like. 

*** Он отлично работает. Реляция вызывается. Все хорошо. ***

Как только раскомментировать вот эту строку:
```php
$query->where(['like', 'name', $name]);
```
Выходит ошибка с ковычкой. Я только что перепроверил, и действительно вы правы, если если убрать where в реляции или или заменить эту строку на:

```php
$query->andWhere(['like', 'name', $name]);
```

**Все будет работать**

Тоесть по сити проблема решена. Можно закрывать обращение. 

Но с другой стороны, все-же при использовании просто where (еще раз обратите внимание синтаксис верный) появляется еще 1 кавычка. Конечно можно закрыть на это глаза и не обращать внимания. А можно перепроверить и выяснить истинную причину. 

Возможно Александр перепроверит и объяснит почему так происходит.

**Comment by lynicidn** [comment]
покажите Exception который вылетает...

**Comment by lynicidn** [comment]
и квери надо возвращать
return $query->where

**Comment by lynicidn** [comment]
вам не нравится слово return ? )

**Comment by samdark** [comment]
@nepster-web нужна схема БД и немного данных, чтобы это воспроизвести.

**Comment by nepster-web** [comment]
@samdark без проблем, я подготовлю все необходимые данные и сброшу вам.

**Comment by nepster-web** [comment]
@samdark я попробовал не сэкономить Ваше время и сделал полностью пример с демонстрацией: https://cloud.mail.ru/public/97f69173fcbc/bugTest.rar

**Comment by samdark** [comment]
Verified that it's not a bug.

1. Extra `'` is from exception message i.e. `Exception 'yii\db\Exception' with message '...'`.
2. You're setting `where` in `Category.getT()` and binding extra paramers. Later you're overriding `where` but parameters from `Category.getT()` are still there. Thus the error.
