### ISSUE TITLE
PHPIDS problem to install with Yii2

### ISSUE THREAD

**Issue by p4scu41** [yiisoft/yii2#7139]
I am trying to install <a href="https://github.com/PHPIDS/PHPIDS" target="_blank">PHPIDS</a> in Yii2 Basic, but the problem is that yii2 requiere htmlpurifier 4.6.* and PHPIDS require htmlpurifier dev-master.

How can I fix this problem ???

<img src="https://cloud.githubusercontent.com/assets/1633236/5924958/993ec510-a625-11e4-92cd-95b24daae46f.png" alt="error" style="max-width:100%;">

**Comment by cebe** [comment]
It is not a good idea to require `dev-master` in general. In case the master could be understood as `4.6.x-dev` you can ask htmlpurifier to define a branch alias in composer.json: https://getcomposer.org/doc/articles/aliases.md#branch-alias
