### ISSUE TITLE
oldAttributes same as new ones in AR afterSave() method

### ISSUE THREAD

**Issue by a-komarev** [yiisoft/yii2#7140]
I've found that in `afterSave()` method parameter `$this->oldAttributes` are always just duplicating `$this->attributes`. What am I doing wrong? I need to update another models only after successful saving of current one.
P.S. `beforeSave()` method is working well.

```php
public function afterSave($insert,$changedAttributes)
{
    var_dump($this->oldAttributes['post'], $this->attributes['post']); // they are equals
    parent::afterSave($insert, $changedAttributes);
}
```
Should I use `$changedAttributes` only for this? I've got checks for some properties which aren't always changing, but could be. And it's enlarge my code a lot. Like:
```php
if (isset($changedAttributes['secondary_id'])) {
    $secondaryId = $changedAttributes['secondary_id'];
} else {
    $secondaryId = $this->attributes['secondary_id'];
}
```

**Comment by lynicidn** [comment]
u do save afterSave ?

**Comment by a-komarev** [comment]
What do you mean?

**Comment by a-komarev** [comment]
It's related issue i suppose: https://github.com/yiisoft/yii2/issues/4086

**Comment by cebe** [comment]
`$changedAttributes` is what you need.

**Comment by a-komarev** [comment]
And if I need unchanged attributes too? I just can't understand why `beforeSave()` method got oldAttributes and `afterSave()` already haven't got it.

**Comment by lynicidn** [comment]
u change attributes afterSave and u should do save after this

**Comment by a-komarev** [comment]
I'm not changing any attributes of current model in `afterSave()`. I need to send old previous attributes to another model.

**Comment by cebe** [comment]
@a-komarev in afterSave() the record is already saved just as it is in controller code after you called save(). This is necessary to allow chaging the record and updating it again in afterSave. You have `$changedAttributes` to see what changed.

**Comment by a-komarev** [comment]
@cebe okay, but it's a code duplicating. When you are trying to fetch all data which were before saving. Is there any easy way to do it not manually assigning?
1 idea: get `$this->attributes` array and replace it with keys from `$changedAttributes`. But not sure it's a best way.

**Comment by cebe** [comment]
You already have your solution posted above, what is the problem?

**Comment by a-komarev** [comment]
No problem, just tried to find out best solution and consult with team to not create bycicles.
Maybe somebody who will faced with same task will find it useful:
```php
public function afterSave($insert,$changedAttributes)
{
    parent::afterSave($insert, $changedAttributes);
    $oldAttributes = array_merge($this->getOldAttributes(), $changedAttributes);
}
```
Then `$oldAttributes` array will have all data as it was before model saving.
