### ISSUE TITLE
Add Parsedown as a Markdown flavor in BaseMarkdown

### ISSUE THREAD

**Issue by takobell** [yiisoft/yii2#7142]
It looks like @cebe has [already started](https://github.com/yiisoft/yii2/issues/47#issuecomment-33595306) the groundwork for it on the Parsedown side.

One of its main benefits is how fast it is: http://kzykhys.com/blog/benchmarked-markdown-parsers-written-in-php/

**Comment by cebe** [comment]
Well, I have not done much to parsedown as it is still hard to get pull requests accepted for intransparent reasons. If the only reason for your proposal is that it is beeing fast, cebe/markdown is [just as fast as parsedown](https://github.com/kzykhys/Markbench#readme). Are there any other reasons to add support for it in the framework? Note that you can easily use it without the Markdown wrapper.

**Comment by takobell** [comment]
The main reason is for its code syntax support.  i.e.:

    ```php
    $test = 1;
    ```

Ends up as:

    <pre><code class="language-php">$test = 1;</code></pre>

It doesn't look like any of the other flavors support that feature.

**Comment by cebe** [comment]
It is supported by github flavored markdown as well as markdown extra: https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseMarkdown.php#L31 `gfm` should be exactly the same as parsedown.
