### ISSUE TITLE
Ajax Validation for Signle field

### ISSUE THREAD

**Issue by tahirm** [yiisoft/yii2#7146]
I have a active form where ajax validation is enabled only for one field and is disabled for all other fields and form itself as well. I am experiencing some strange behaviours and want to confirm if they are expected.

Is it normal for active form to send the whole form data for ajax validation when ajax validation is enabled only for one field of the form?

Also, ajax validation is triggered even when I submit the form and again whole form data is sent for validation even when `enableAjaxValidation` is set to `false` for the form.

Are these behaviours expected? If yes, then is there any way to have only client side validation on form submit in above scenario?

**Comment by anhuy1989** [comment]
We can disable load captcha image when validate by ajax to fix above issue.
Check validate() function in this file: vendor/yiisoft/yii2/captcha/CaptchaAction.php

So we can override this file by something like that:

<?php

namespace app\modules\core\captcha;

use Yii;
use yii\base\Action;
use  yii\captcha\CaptchaAction as YiiCaptchaAction;

class CaptchaAction extends YiiCaptchaAction
{
    public function validate($input, $caseSensitive)
    {
        $code = $this->getVerifyCode();
        $valid = $caseSensitive ? ($input === $code) : strcasecmp($input, $code) === 0;
        $session = Yii::$app->getSession();
        $session->open();
        $name = $this->getSessionKey() . 'count';
        $session[$name] = $session[$name] + 1;
        if ($valid || $session[$name] > $this->testLimit && $this->testLimit > 0) {
            
            if(\Yii::$app->request->isAjax == false) {
                 $this->getVerifyCode(true);
            }
            
        }

        return $valid;
    }
}

**Comment by klimov-paul** [comment]
Such behavior of AJAX validation is expected.
Although it may looks inrational, but improvement on this matter does not worth it.
