### ISSUE TITLE
Timestamp problem

### ISSUE THREAD

**Issue by germanigortcev** [yiisoft/yii2#7147]
'SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "1422912540.7317" The SQL being executed was: INSERT INTO "system_log" ("level", "category", "log_time", "prefix", "message") VALUES (4, 'yii\db\Connection::open', 1422912540.7317, '[app-backend][/log/index]', 'Opening DB connection: pgsql:host=localhost;dbname=development')'

incorect in 'class' => 'yii\log\DbTarget', - time for insert is "1422912540.7317" 
incorect time stamp от debug/logs - 22:37:29.421 - gridVew

echo time() is normal format - 1422953326 

PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**Comment by cebe** [comment]
where did you get this query from? what is the code that generates it and what is the stack trace of the errror?

**Comment by ismorodin** [comment]
Try to use 
$expression = new Expression('NOW()');

**Comment by germanigortcev** [comment]
This qwery genereate by DbTarget class

'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                'db'=>[
                    'class' => 'yii\log\DbTarget',
                    'levels' => ['error', 'warning', 'info'],
                   // 'except'=>['yii\web\HttpException:*', 'yii\i18n\I18N\*'],
                    'prefix'=>function(){
                        $url = !Yii::$app->request->isConsoleRequest ? Yii::$app->request->getUrl() : null;
                        return sprintf('[%s][%s]', Yii::$app->id, $url);
                    },
                    'logVars'=>[],
                    'logTable'=>'{{%system_log}}'
                ]
            ],
        ],

**Comment by klimov-paul** [comment]
It is clear the table for the log storage has been created incorrectly: field `log_time` should be float - not integer.
See the migration for the log table:
https://github.com/yiisoft/yii2/blob/master/framework/log/migrations/m141106_185632_log_init.php#L68
