### ISSUE TITLE
FormatConverter doesn't support ICU-formatted escaped text

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#7150]
The [ICU Date/Time Format Syntax](http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax) specifies that it’s possible to escape text by placing it within single quotes, and that two consecutive single quotes should result in one single quote. However, FormatConverter::convertDateIcuToPhp() and ::convertDateIcuToJui() do not respect those syntaxes.

Example:

```php
$formatter = new IntlDateFormatter('en_US', IntlDateFormatter::FULL, IntlDateFormatter::FULL);
$pattern = $formatter->getPattern();
echo \yii\helpers\FormatConverter::convertDateIcuToPhp($pattern)."\n" .
     \yii\helpers\FormatConverter::convertDateIcuToJui($pattern);
```

Expected output:

    l, F j, Y \a\t g:i:s a T
    DD, MM d, yy 'at' ::  

Actual output:

    l, F j, Y 'at' g:i:s a T
    DD, MM d, yy 't' ::  

(The expected jQuery output is admittedly a little weird in this example, since jQuery UI’s Datepicker doesn't support time formats, but it still illustrates the issue.)

Tested in Yii 2.0.2.

**Comment by maddoger** [comment]
There is a one big problem: str_split does not work properly with UTF-8 characters. 
For example: the "medium" format in ru-RU is 'dd MMM y 'г'.'. Its become 'd M Y \�\�.'

**Comment by samdark** [comment]
@maddoger would you please report it as a separate issue? Thanks!

**Comment by maddoger** [comment]
done #7603
