### ISSUE TITLE
Doc missing: How you input multiple models in complex forms?

### ISSUE THREAD

**Issue by herzmut** [yiisoft/yii2#7152]
Hello.

How do you input multiple models in complex forms? The doc doesn't contain anything. https://github.com/yiisoft/yii2/blob/master/docs/guide/input-multiple-models.md

Thanks!

**Comment by lynicidn** [comment]
http://www.yiiframework.com/forum/index.php/topic/54567-yii2-form-multiple-items-validation/

**Comment by cebe** [comment]
@lynicidn what you have linked is tabular input as far as I see: https://github.com/yiisoft/yii2/blob/master/docs/guide/input-tabular-input.md

**Comment by jgrasta** [comment]
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
    'id' => 'login-form',
    'options' => ['class' => 'form-horizontal'],
]) ?>

is it possible to have multiple id

**Comment by dynasource** [comment]
our Definative Guide contains a great example about how to deal with multiple models in forms:
* http://www.yiiframework.com/doc-2.0/guide-input-multiple-models.html
