### ISSUE TITLE
Formatter::asDate not working with timestamp attribute loaded from db

### ISSUE THREAD

**Issue by diogobd** [yiisoft/yii2#7154]
When an timestamp attribute  is loaded from database, and it is necessary to format with ```Formatter::asDate()```, and ```timeZone``` 
does not is the default, the wrong result is returned

example: 

```php
$user = User::findOne($id);
//consider $user->updated_at = 2015-01-26 00:00:00
echo  Yii:$app->formatter->asDate($user->updated_at) //result in 25/01/2015 
```

```config/web.php``` : 

```php
$config = [
    'id' => 'basic',
    'timeZone' => "America/Sao_Paulo",
    ...
```

**Comment by cebe** [comment]
this is expected, `2015-01-26 00:00:00 UTC` is `2015-01-25 22:00:00 America/Sao_Paulo`.

```php
$ php -r '$d = new Datetime("2015-01-26 00:00:00 UTC"); $d->setTimeZone(new DateTimeZone("America/Sao_Paulo")); echo $d->format("Y-m-d H:i:s");'
2015-01-25 22:00:00
```

**Comment by cebe** [comment]
Note: If you give input to the formatter that includes time, it will adjust the timezone correctly. If your input does not include time it will not do timezone conversion.

```
$user = User::findOne($id);
//consider $user->updated_at = 2015-01-26
echo  Yii:$app->formatter->asDate($user->updated_at) //result in 26/01/2015 
```
