### ISSUE TITLE
Url::canonical action params problem

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#7157]
Hi,
I want to get url canonical without page number link, but Url::canonical(); getting all url.
I'm thinking, This may be something like this?
```
public function canonical($options = []) {
	$params = Yii::$app->controller->actionParams;

	if (count($options) > 0):
	    foreach ($params as $key => $param):
		if (!in_array($key, $options)):
		    unset($params[$key]);
		endif;
	    endforeach;
	endif;

	$params[0] = Yii::$app->controller->getRoute();

	return Yii::$app->getUrlManager()->
			createAbsoluteUrl($params);
    }

Url::canonical(['seo']);
```
Just "seo" param accepting..??

**Comment by klimov-paul** [comment]
Unable to reproduce.
`Url::canonical()` picks only those request params bound to the controller action. Unles paramters `page` or `per-page` are mentioned among action method argument they do not appear at canonical URL.
