### ISSUE TITLE
Merging Two ActiveQuery like Yii1 CDbCriteria::mergeWith

### ISSUE THREAD

**Issue by petrabarus** [yiisoft/yii2#7158]
One thing that I think is pretty useful in Yii1 is `CDbCriteria::mergeWith()` 
http://www.yiiframework.com/doc/api/1.1/CDbCriteria#mergeWith-detail

Is this feature already implemented in Yii2 as well. I couldn't seem to find it in the source code.

**Comment by Faryshta** [comment]
The ways to 'merge' ActiveQuery's have changed. Check

http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#joining-with-relations

http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#joinWith%28%29-detail

Also you can use yii2 subqueries to call a query within another one.

if what you want is to 'merge' the conditions you can do

```php
$activeQuery->andWhere($activeSubQuery->where);
```

**Comment by cebe** [comment]
@petrabarus can you give a use case for that in yii2? In Yii1 it was mainly used to apply more criteria to already defined queries, in Yii2 you normally just call the methods of the query to adjust it.

**Comment by petrabarus** [comment]
Never mind, I don't really think it's a big deal, though. The current `andWhere`, `addSelect`, etc still cover all of my use cases.

I still don't have a concrete use case. At first, I was thinking something instead of

```php
static function fooMethod($param, $query){
    $query->addSelect(['col'])->andWhere('test = :test', ['test' => $param]);
}
//
$query = Book:find();
Foo::fooMethod($param, $query);
$book = $query->one();
```
it's better

```php
function fooMethod($param){
    return Book::find()->select(['col'])->where('test = :test', ['test' => $param]);
}
//
$book = Book:find()->merge(Foo::fooMethod($param))->one();
```

I think both are reusable. But the second one will need to create more objects than the first one, although the method chaining is pretty tempting.

But not really a big deal, though.

**Comment by cebe** [comment]
Going to close this then, as current API covers it well, we should not introduce too many ways to do the same thing.
