### ISSUE TITLE
Need to have an option to specify the scheme for secure links (https) in navigation links

### ISSUE THREAD

**Issue by sinaru** [yiisoft/yii2#7160]
When using NarBar we use Nav class to specify the list of items for the navigations.
Each item has the 'url' option to specify the desired path. 
http://www.yiiframework.com/doc-2.0/yii-bootstrap-nav.html#$items-detail

After reviewing the code, I found that Nav class uses Html::a( ) method to create the link. 
https://github.com/yiisoft/yii2/blob/master/extensions/bootstrap/Nav.php#L183

And inside Html::a( ) it uses, Url::to( ) method to create the URL. 
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L358

For Url::to( ) , as second parameter we can specify the scheme('http', or 'https').

So I think it would be great if we can use this scheme paramter to create secure links in Nav items. 
For example we can have an option called 'scheme' when creating an item.

This is useful and easy when we are creating secure links for sensitive actions such as login, account management pages.

Personally, right now I'm directly using Url::to( ) method to create the expected secure link and assign it to the item 'url' option and it seems to be bit ugly. 
...
'url' => Url::to(['/site/login'],'https')
...

**Comment by cebe** [comment]
Not sure if this is really a problem. Using Url::to() directly is a pretty valid usage and most explicitly shows what is going on. If we add an extra parameter it will be more hidden what is going on.

**Comment by qiangxue** [comment]
`'url' => Url::to(['/site/login'],'https')` is the expected way. It's not common to specify scheme for internal URLs. So we should not further complicate the format of the `url` option.
