### ISSUE TITLE
[Feature request] Model::attributeHints method

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#7162]
An `ActiveField` allows to set a hint when filling a form using the `hint()` method. I propose to have a method to set the hints for an attribute from the model

```php
public function attributeHints()
{
    return [
        'telephone' => 'include area code, eg: 5551234567',
        'shipping_address' => 'if left blank the package will be sent to your registered address',
    ];
}
```
We might also require an `BaseHtml::activeHint($model, $attribute, $options)` method to render it more easily.

**Comment by petrabarus** [comment]
+1

**Comment by Faryshta** [comment]
@samdark what do you think about the `BaseHtml::activeHint` method?

**Comment by samdark** [comment]
I think it's a duplicate of #1468
