### ISSUE TITLE
Codeception stops with Yii::$app->end()

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#7167]
hi Qiang, 

I am having issues with redirection + ending the application + codeception.

I saw an update in Application.php:
```php
       if (YII_ENV_TEST) {
            throw new ExitException($status);
        } else {
            exit($status);
        }
```

Still, Codeception throws an error because of this ExitException. Is there something I am missing? How should I handle redirects as last part of the current script lifecycle?

thanx

**Comment by cebe** [comment]
what is the error you see? This should normally just end the request.

**Comment by dynasource** [comment]
this:
```php
        \Yii::$app->controller->redirect($returnUrl);
        \Yii::$app->end();
```

will lead to 
```php
Couldn't send ajax post request "/dmn/yii2/core/frontend/web/index-ftest.php?r=event%2Fevent%2Fdelete&id=3&status=-7",{"_csrf":"UnhsU3ZQa2EZJx0ZPWUjNBo.Dzo9Py8nCC0gKQwWCgADTxsyOR88FQ=="}:
yii\base\ExitException: 

Scenario Steps:
3. I send ajax post request "/dmn/yii2/core/frontend/web/index-ftest.php?r=event%2Fevent%2Fdelete&id=3&status=-7",{"_csrf":"UnhsU3ZQa2EZJx0ZPWUjNBo.Dzo9Py8nCC0gKQwWCgADTxsyOR88FQ=="}
                             
[yii\base\ExitException]   
```

**Comment by Ragazzo** [comment]
`Yii2` module for `Codeception` does not handle this exception, you can write your own exception handler to catch it and use it in tests

**Comment by dynasource** [comment]
the ExitException was mainly developed for the tests environment? Why isnt the Yii2 Module catching it? It shouldnt break tests? Or am I missing something.

**Comment by Ragazzo** [comment]
>Why isnt the Yii2 Module catching it?

yes , you are free to submit PR for `Codeception` repo to `Yii2` module , that would be great

**Comment by dynasource** [comment]
I will look at it. Thanx.

**Comment by dynasource** [comment]
it seems that this has been fixed by bixuehujin https://github.com/Codeception/Codeception/commit/e8c2c5d635b687e5b46a24026cbf7773df0dbeec
