### ISSUE TITLE
Dynamic arguments in Url::to

### ISSUE THREAD

**Issue by dirtyman** [yiisoft/yii2#7168]
The actual implementation of Url::to is:
```php
echo Url::to(['site/index', 'src' => 'ref1', '#' => 'name']);
```

What happens if you have the url but the parameters can be dynamic? Or vice-versa.
The way I found was:
```php
$name = $this->getName();
$params = ['src' => 'ref', '#' => $name];
echo Url::to(array_merge(['site/index'], $params));
```

But this seems ugly and perhaps not very good at performance, if you are using this a lot.

**Comment by qiangxue** [comment]
That's how it is designed. We will not make changes because it would break BC.
