### ISSUE TITLE
add docco style parser for "unstructured" documents

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#7171]
### yii2-apidoc

With [docco](http://jashkenas.github.io/docco/) it is very easy to document source code files like configurations, views or even javascript.

It would be nice if we could add a parser which does a similar thing.
Or include HTML-files generated by docco (a custom docco-template could be needed)

It's basically extracting `//` comments from the source...

![bildschirmfoto 2015-02-04 um 23 55 46](https://cloud.githubusercontent.com/assets/649031/6051554/67474f96-acc9-11e4-99d6-96dd353648d1.png)

**Comment by samdark** [comment]
Interesting idea.

**Comment by schmunk42** [comment]
Would make the application documentation pretty complete.
You can use Markdown syntax with docco, eg. for headlines - could come handy when linking to source code.

**Comment by schmunk42** [comment]
This could be helpful: https://github.com/rossriley/phrocco

**Comment by dynasource** [comment]
its unclear in this topic how the framework could benefit from docco. Please describe a detailed usecase on the advantages & disadvantages of this tool for Yii.

**Comment by schmunk42** [comment]
It's not in the scope of Yii core I think. Maybe for Apidocs or as an extension.
