### ISSUE TITLE
EmailValidator won't validate domain in the email address with name with checkDNS=true

### ISSUE THREAD

**Issue by nbogol** [yiisoft/yii2#7172]
Imagine email: `Ivan Petrov <ipetrov@gmail.com>`
Try to validate with `checkDSN = true`. On my Fedora20 linux server it fails, 
because preg_match() by default is greedy and will not correctly parse the domain out of the 
email address with name. Domain name will be like `gmail.com>`.
Need to change regex to  `/^(.*?<?)(.*)@(.*?)(>?)$/` 
in `\yii\validators\EmailValidator::validateValue($value)`
I had to add additional `?` after quantifiers `*` before `<` and `>` in order to make it non-greedy. Then it worked for both email types with and without name.

**Comment by samdark** [comment]
@nbogol could you help creating unit test for it?

**Comment by nbogol** [comment]
I will create a pull request to update current:
`yii2/tests/unit/framework/validators/EmailValidatorTest.php`
right?

**Comment by samdark** [comment]
Yes.
