### ISSUE TITLE
dropDownList validator

### ISSUE THREAD

**Issue by ph1ex0n** [yiisoft/yii2#7173]
i have
```php
...
`<?= $form->field($model, 'filters[]')->dropDownList([0=>'Mobile',1=>'Brow',2=>'Win'] ,['class'=>'form-control chosen-select','multiple'=>true,'size'=>3] ) ?>`
...
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
  <script src="http://mydomain.com/chosen/chosen.jquery.js" type="text/javascript"></script>
  <script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }
  </script>`
```

java script works fine
but if i do update then i got error
![1](https://cloud.githubusercontent.com/assets/2778052/6053665/135cd172-ad04-11e4-9a1c-40b9192ed91b.png)

rules() contains that [['filters'], 'string', 'max' => 1024]

i want to have multiple select saved in db, how i can get it?

**Comment by ph1ex0n** [comment]
i change rules() so
`[['filters'], 'filter', 'filter' => function ($value) {return json_encode($value);}]
`
now i can save my array
but how i can return my array from db?

**Comment by cebe** [comment]
please use the forum to ask questsions, github is a bug/feature tracker.
