### ISSUE TITLE
DateValidator add support for time values

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#7177]
DateValidator sets the time part to 00:00:00 when inserting the timestamp into timestampAttribute, because [here](https://github.com/yiisoft/yii2/blob/58becaceab5cf3f7896d7934de715cecfd95c210/framework/validators/DateValidator.php#L133) the `$timetype` argument is set to `IntlDateFormatter::None`.
It doesn't help if you use `Yii::$app->formatter->datetimeFormat` as a format, because both `Yii::$app->formatter->datetimeFormat` and `Yii::$app->formatter->dateFormat` are "medium", so DateValidator doesn't know if you want to keep the time or not.

The other problem is that even though it cuts off the time part, it still accepts input that contains a time part.

**Comment by cebe** [comment]
DateValidator is not designed to work with time values currently.

**Comment by nkovacs** [comment]
I did some more testing. It works fine if you specify a format in php syntax.
If you use the ICU syntax and specify a time component, it won't cut off the time. But if the format does not contain a time component, it will still accept values that contain a time.

So as a workaround, you can either use `IntlDateFormatter::getPattern` with an appropriately constructed formatter to fix the first bug, or `\yii\helpers\FormatConverter::convertDateIcuToPhp(Yii::$app->formatter->datetimeFormat)` to fix both, but the latter can't convert some special formats.

**Comment by cebe** [comment]
> But if the format does not contain a time component, it will still accept values that contain a time.

this should now be fixed by #6553

**Comment by nkovacs** [comment]
I made an extension that fixes this: https://github.com/nkovacs/yii2-datetimepicker/blob/master/DateTimeValidator.php

Of course there would be no need to convert the short format to a full pattern if implemented in Yii's validator, but I had to do it so I wouldn't have to reimplement all the code in it.

**Comment by cebe** [comment]
should be fixed by #5053 (d60445c066003cab78fb16458e7234fae5db4765)

**Comment by cebe** [comment]
hm okay, not really.

**Comment by nkovacs** [comment]
Not entirely. If you use an intl short format (which is the default), the validator still uses IntlDateFormatter::NONE for the time value: https://github.com/yiisoft/yii2/commit/d60445c066003cab78fb16458e7234fae5db4765#diff-32236b8409f422c4a80339d1ef6466e0R167

**Comment by cebe** [comment]
yep, just seen that while reading the related issue.

**Comment by cebe** [comment]
resolved by  2ac17dd...00d506c
