### ISSUE TITLE
AR relations with variable on conditions

### ISSUE THREAD

**Issue by sebucando** [yiisoft/yii2#7178]
Hey there,

I have some problems with a simple relation between my project tables:

table: project
id, name, ...

junction table: rel_project_projects
project_id_from, project_id_to, type, active

The only way I know to set up additional on conditions is to use the callback function:

    public function getDependentProjects($type = NULL){

		if( $type == NULL ){
			return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
				->viaTable('servers.rel_project_projects', ['project_id_from' => 'id']);
		}
		else{
			return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
				->viaTable('servers.rel_project_projects', ['project_id_from' => 'id'], function($query){
					global $type;
					return $query->onCondition(['type' => $type]);
				}
			);
		}
    }

BUT, I lose my variable $type inside the callback function and can't bypass it, so I get this query:

SELECT * FROM `servers`.`rel_project_projects` WHERE (`project_id_from`=3) AND (`type` IS NULL)

Same issue if I want to get all active/inactive relations which are stored in column 'active' of my junction table.

Possible Solution:

    public function getDependentProjects($type = NULL){

		if( $type == NULL ){
			return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
				->viaTable('servers.rel_project_projects', ['project_id_from' => 'id']);
		}
		else{
			return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
				->viaTable('servers.rel_project_projects', ['project_id_from' => 'id']	)->onCondition(['type' => $type, 'active' => 1]);
		}
    }

**Comment by mdmunir** [comment]
I am not sure. try this
```php
public function getDependentProjects($type = NULL){

    if( $type == NULL ){
        return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
            ->viaTable('servers.rel_project_projects', ['project_id_from' => 'id']);
    }
    else{
        return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
            ->viaTable('servers.rel_project_projects', ['project_id_from' => 'id'], function($query) use($type){
                return $query->onCondition(['type' => $type]);
            }
        );
    }
}
```
or use
```php
public function getDependentProjects($type = NULL){

    if( $type == NULL ){
        return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
            ->viaTable('servers.rel_project_projects', ['project_id_from' => 'id']);
    }
    else{
        return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
            ->viaTable('servers.rel_project_projects', ['project_id_from' => 'id'])
            ->onCondition(['type' => $type]);
    }
}
```

**Comment by Faryshta** [comment]
```php
return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
    ->viaTable('servers.rel_project_projects', ['project_id_from' => 'id'])
    ->andFilterWhere(['type' => $type]);
```

http://www.yiiframework.com/doc-2.0/yii-db-querytrait.html#filterWhere()-detail

What you try to apply is not a condition, its a filter.

**Comment by dynasource** [comment]
have you tried the onCondition like mdmunir suggested?

**Comment by sebucando** [comment]
public function getDependentProjects($type = NULL){

    if( $type == NULL ){
        return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
            ->viaTable('servers.rel_project_projects', ['project_id_from' => 'id']);
    }
    else{
        return $this->hasMany(Project::className(), ['id' => 'project_id_to'])
            ->viaTable('servers.rel_project_projects', ['project_id_from' => 'id'], function($query) use($type){
                return $query->onCondition(['type' => $type]);
            }
        );
    }
}

works! thx for that mdmunir!

2nd suggestion did'nt work, but I wished the syntax would be like this!

**Comment by sebucando** [comment]
As the query is correct now, it shows up twice from the exect same place in my view/controller on every page view:

SELECT * FROM `servers`.`rel_project_projects` WHERE (`project_id_from`=3) AND (`type`='FULL')
   .../modules/servers/views/project/view.php (88)
   .../modules/servers/controllers/ProjectController.php (128)

SELECT * FROM `servers`.`rel_project_projects` WHERE (`project_id_from`=3) AND (`type`='FULL')
   .../modules/servers/views/project/view.php (88)
   .../modules/servers/controllers/ProjectController.php (128)

SELECT * FROM `servers`.`rel_project_projects` WHERE (`project_id_from`=3) AND (`type`='PART')
   .../modules/servers/views/project/view.php (71)
   .../modules/servers/controllers/ProjectController.php (128)

SELECT * FROM `servers`.`rel_project_projects` WHERE (`project_id_from`=3) AND (`type`='PART')
   .../modules/servers/views/project/view.php (71)
   .../modules/servers/controllers/ProjectController.php (128)

Is this really necessary?

Part of Controller:

    public function actionView($id)
    {
    	$model = $this->findModel($id);

        return $this->render('view', [
            'model' => $model,
            'dataProviders' => [
				'servers' => [
					'full' => new ActiveDataProvider([
				    	'query' => $model->getServers('FULL'),
    				]),
					'part' => new ActiveDataProvider([
				    	'query' => $model->getServers('PART'),
    				]),
				],
	        	'projects' => [
					'full' => new ActiveDataProvider([
			            'query' => $model->getDependentProjects('FULL'),
		        	]),
		        	'part' => new ActiveDataProvider([
			            'query' => $model->getDependentProjects('PART'),
		        	]),
				],
			]
        ]);
    }
