### ISSUE TITLE
Make \yii\base\ArrayableTrait::toArray truly recursive.

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7179]
Or how can i make it myself and stay with framework guidelines and future plans ?

Example:

``` php
class SevereDisasterController extends \yii\rest\Controller {

    public function actionGetAllHands($customerId) {
        $allHands = Customer::find($customerId)
            ->with([
                'arContract',
                'arContract.obDepartment',
                'arContract.obDepartment.arJobPosition',
                'arContract.obDepartment.arJobPosition.obWorker',
                'arContract.obDepartment.arJobPosition.obWorker.arNotifyChannel',
            ])
            ->one();
        return $allHands->toArrayRecursive(); // Hypothetic
    }

} 
```

Expected: sheer tree of objects, all with limitations and renames defined in `fields()` and `extra_fields()`.

Observed: no more than one level of nesting if called like `->toArray([],$arWith,true)`. This level is given w/o limitations in `fields()`.

**Comment by mcd-php** [comment]
Here it is - not covered with tests, maybe buggy, but works in my narrow case:

https://gist.github.com/mcd-php/e5236dd6150ea144b1da

**Comment by dynasource** [comment]
if this is a bug, shouldnt this be fixed in BaseArrayHelper::toArray()?

**Comment by cebe** [comment]
duplicate of #6844?
