### ISSUE TITLE
Add boxing (for validation and filtering) to \yii\web\Controller::bindActionParams ?

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7181]
Use case:

```php
class PostController extends Controller {
    public function actionEdit( UUIDParam $postId, HtmlPurifierParam $text ) {
        // ...
    }
}
```
Somewhere in `bindActionParams()`:
```php
if ( $paramClass ) {
    $boxedParam = new $paramClass($rawParam);
}
```
And in constructors of boxed parameters, I can do whatever I want - filter, validate, throw exceptions, even pre-load model by ID and check logical rights on it given the current user.

What will be an advice from core team for me to implement it, if I decide to ?

**Comment by mcd-php** [comment]
Here's my draft - not covered with tests, project-biased etc: https://gist.github.com/mcd-php/a0d3f73b64c5de38ce22

Usage example:
```php
class SomeController extends Controller {
    use ActionParamsBoxingTrait;
    public function actionSave(UUIDParam $id, HtmlPurifierParam $text) {
        // If UUID is bad, by this time the exception is already thrown
    }
}
```

**Comment by SilverFire** [comment]
Could be done with DI via action method signature.
See https://github.com/yiisoft/yii2/commit/2505e7ef63b7d802833457c896ee2418f83d8763,
