### ISSUE TITLE
ActiveRecord extraFields returns null

### ISSUE THREAD

**Issue by ventayol** [yiisoft/yii2#7182]
I've read the documentation and it says that **yii\db\ActiveRecord** returns all the relations as default in the **extraFields**.

I've a model that has some relations but the **extraFields** returns null.

I've debugged some of the Yii code and I've seen that the _related property is null for the class.

**Comment by Faryshta** [comment]
http://www.yiiframework.com/doc-2.0/yii-base-arrayabletrait.html#extraFields()-detail extraFields is meant for you to extend it. It returns an extra set of field when you are using the `asArray` method to turn an `ActiveRecord` to array.

To get the relations on an active record first you need to preload them, them invoke `getRelatedRecords()`

```php
$employee = User::find()->where(['id'=>$id])->with(['projects', 'company', 'company.manager']);

return $employee->getRelatedRecords();
// will return the projects and the company, the company will have the manager preloaded
```

**Comment by ventayol** [comment]
But here is what the Guide says when working with a Rest API:

>**Overriding extraFields()**
By default, yii\base\Model::extraFields() returns nothing, while yii\db\ActiveRecord::extraFields() returns the names of the relations that have been populated from DB.

I though that when creating a Rest Controller the extraFields will be automatically populated so I can use the **?expand** parameter in my api calls.

**Comment by Faryshta** [comment]
really? where does it says that? it sounds like a documentation issue

**Comment by ventayol** [comment]
It's here:
http://www.yiiframework.com/doc-2.0/guide-rest-resources.html

**Comment by Faryshta** [comment]
Ohh I get it now.

By default `extraFields()` return an empty array, and the `ActiveRecord` doesn't have any relation populated.

When turning the object to array the `extraFields` method specify which relations should be populated and added to the array.

I am not good at explaining. Can you provide the code of your model?

**Comment by ventayol** [comment]
I've created the model using the `Gii` model generator.
In this code I've hardcoded the **extrafields**.

What I was hopping is that by default, using the `ActiveController` my restful endpoints will be able to use the expand without any need to add the fields to the **extrafields**. I want to avoid to go to all my models and add all the relations to the **extrafields**.

```php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "candidate".
 *
 * @property integer $id
 * @property string $driving_license
 * @property integer $car
 * @property double $height
 * @property double $size
 * @property double $foot_size
 * @property integer $hair_color_id
 * @property integer $weight
 * @property string $time_monday
 * @property string $time_tuesday
 * @property string $time_wednesday
 * @property string $time_thursday
 * @property string $time_friday
 * @property string $time_saturday
 * @property string $time_sunday
 * @property string $created_at
 * @property string $updated_at
 *
 * @property User[] $user
 * @property ActivityCandidate[] $activityCandidates
 * @property ActivityMessage[] $activityMessages
 * @property HairColor $hairColor
 * @property CandidateBook[] $candidateBooks
 * @property CandidateLanguage[] $candidateLanguages
 * @property CandidateWorkPosition[] $candidateWorkPositions
 */
class Candidate extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'candidate';
    }

    /**
    * TimestampBehavior
    */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id', 'car', 'hair_color_id', 'weight'], 'integer'],
            [['height', 'size', 'foot_size'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['driving_license', 'time_monday', 'time_tuesday', 'time_wednesday', 'time_thursday', 'time_friday', 'time_saturday', 'time_sunday'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'driving_license' => Yii::t('app', 'Driving License'),
            'car' => Yii::t('app', 'Car'),
            'height' => Yii::t('app', 'Height'),
            'size' => Yii::t('app', 'Size'),
            'foot_size' => Yii::t('app', 'Foot Size'),
            'hair_color_id' => Yii::t('app', 'Hair Color ID'),
            'weight' => Yii::t('app', 'Weight'),
            'time_monday' => Yii::t('app', 'Time Monday'),
            'time_tuesday' => Yii::t('app', 'Time Tuesday'),
            'time_wednesday' => Yii::t('app', 'Time Wednesday'),
            'time_thursday' => Yii::t('app', 'Time Thursday'),
            'time_friday' => Yii::t('app', 'Time Friday'),
            'time_saturday' => Yii::t('app', 'Time Saturday'),
            'time_sunday' => Yii::t('app', 'Time Sunday'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public function fields()
    {
        $fields = parent::fields();

        // remove fields that contain not useful information
        unset($fields['created_at'], $fields['updated_at']);
        $fields["user"] = function($model){
            return $model->user;
        };

        return $fields;
    }

    public function extraFields ()
    {
        return ["user","candidateWorkPositions","hairColor","candidateLanguages","candidateBooks"];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActivityCandidates()
    {
        return $this->hasMany(ActivityCandidate::className(), ['candidate_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActivityMessages()
    {
        return $this->hasMany(ActivityMessage::className(), ['candidate_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHairColor()
    {
        return $this->hasOne(HairColor::className(), ['id' => 'hair_color_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidateBooks()
    {
        return $this->hasMany(CandidateBook::className(), ['candidate_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidateLanguages()
    {
        return $this->hasMany(CandidateLanguage::className(), ['candidate_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCandidateWorkPositions()
    {
        return $this->hasMany(CandidateWorkPosition::className(), ['candidate_id' => 'id']);
    }
                                                                    
}
```

**Comment by Faryshta** [comment]
You are using `'user'` twice, first as a field, then as an extra field my advice is to delete

```php
        $fields["user"] = function($model){
            return $model->user;
        };
```

Besides that it looks pretty much right. Are you getting any error? whats the output?

**Comment by ventayol** [comment]
As it's now it works, but if I remove the `extrafields` I cannot use the expand options in the restful endpoint.

Having the `user` twice is a small trick I've found to expand this field always, no matter it's in the expand query or no, as this resource doesn't make sense if there's no user.

**Comment by Faryshta** [comment]
> By overriding fields() and/or extraFields(), you may specify what data, called fields, in the resource can be put into its array representation. The difference between these two methods is that the former specifies the default set of fields which should be included in the array representation, while the latter *specifies additional fields which may be included in the array if an end user requests for them via the expand query parameter*.

So thats the expected behavior. If the relation is not in extra field, then it will not be populated or shown.

**Comment by ventayol** [comment]
Then the guide documentation should be wrong.

**Comment by Faryshta** [comment]
the documentation states exactly that. which part is it wrong?

**Comment by ventayol** [comment]
The Yii2 Guide when it says:

>**Overriding extraFields()**
By default, yii\base\Model::extraFields() returns nothing, while yii\db\ActiveRecord::extraFields() returns the names of the relations that have been populated from DB.

Here:
http://www.yiiframework.com/doc-2.0/guide-rest-resources.html

**Comment by Faryshta** [comment]
that is factually truth. The values returned on extrafield gets populated on the ActiveRecord when you invoke  the `toArray` method that is used by the rest api to turn the model into json.

the rest api by default won't show you the relations populated with extraFields unless you request them using `enhance` on the url.

The process is like this

- The rest api find the model
- The rest api invokes the  `toArray` method.
- `toArray` gets the fields of the active record using the `fields` method and the relations using the `extraFields` method and attach them to the `ActiveRecord` object
- `toArray` passes this result to the rest api
- The rest api reads the `enhance` parameter to decide which information it will return to the browser.

The last part is probably where your issue is. `enhance` doesn't communicate with the database, by the time it is called the `ActiveRecord` object doesn't exist anymore, it has been turned into an array.
