### ISSUE TITLE
URL rules for `directory/` (with trailing slash) for controllers inside a directory.

### ISSUE THREAD

**Issue by petrabarus** [yiisoft/yii2#7185]
I met this issue on my app, and I don't know whether this is intended or not.

I tried creating new project from fresh `yii2-app-advanced`.

And then I tried creating new `TestController` inside a directory `frontend/controllers/directory`.

```php
<?php

namespace frontend\controllers\directory;

class TestController extends \yii\web\Controller {

        public function actionIndex(){
                echo "Hello World";
        }
}

```

I tried accessing `http://localhost/directory/test/index` and `http://localhost/directory/test`, it obviously worked.

But when I tried accessing `http://localhost/directory` and `http://localhost/directory/` it showed 404. I want when user access that `/directory` segment, it could go to the default controller instead of showing 404. So I tried adding the rule below.

```php
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                'directory' => 'directory/test/index'
            ]
        ],
```
with that rule, `http://localhost/directory` will open the `TestController`, I made. But the `http://localhost/directory/` still shows 404.

I tried adding another rule

```php
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                'directory/' => 'directory/test/index'
                'directory' => 'directory/test/index'
            ]
        ],
```

This also doesn't work.

The only workaround I can do is adding a `DirectoryController`.

```php
<?php

namespace frontend\controllers;

class DirectoryController extends \yii\web\Controller {

        public function actionIndex(){
                return $this->redirect(['directory/test/index']);
        }
}
```

**Comment by samdark** [comment]
Yes, that's intended.
