### ISSUE TITLE
Add post-processing to \yii\db\Query

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7187]
Please add the capability to post-process query results in methods like `\yii\db\Query::all()`, `one()` etc. , or give a hint how should I do it for myself keeping with framework design guidelines.

Reason: Database engine has limited ORDER BY, no GROUP BY or HAVING.

Usage example:
```php
class SomeModel extends ActiveRecord {
    public function getDetails() {
        return $this->hasMany(/*..*/)
            ->ppGroupBy(new MyCrazyGroupReduceDescriptor([
                //
            ]))
            ->ppOrderBy('sort_weight')
        ;    
    }
}
```

**Comment by samdark** [comment]
```php
$results = Post::find()-...->all();
// do your post-processing here
```

**Comment by mcd-php** [comment]
Oops, you are so cruel ... I'm now hastily coding post-processing, since I have multi-level nested `->with()` and sorting every sub-branch in every controller will be combinatory explosion of copy-paste headache (this is exactly why the example was in relation, not in controller).

**Comment by samdark** [comment]
That makes it a bit different. Are you sure you need PHP to process it?

**Comment by klimov-paul** [comment]
In this case you should create your own `Query`, `ActiveQuery` and so on classes, which should emulate missing order or having features.
If your database engine is so specific - you should create specific extension for its usage like it is done for MongoDB, Redis and so on.
For the regular `yii\db\*` postprocessing feature makes no sense.

**Comment by mcd-php** [comment]
I just implemented my post-processing, will the Yii2 core team (how to mention ??) look and merge it, so should I cleanse it of project/company specific stuff and make a PR or module ?

@klimov-paul Yes, I do have `mycompany\yii2\db\cassandra`, but the `ActiveQueryPostProcessTrait` will go into just `mycompany\yii2\` since it's in no way Cassandra-specific.

**Comment by klimov-paul** [comment]
> but the ActiveQueryPostProcessTrait will go into just mycompany\yii2\ since it's in no way Cassandra-specific.

I don't get. At first you say you need post-processing because you lack 'group' and 'having' features at Cassandra. Next, I advise you place post processing, which will emulate 'group' and 'having' inside your `cassandra\Query` so it will be consistent with regular `db\Query`. And now you are telling such emulation has nothing to do with Cassandra.
If this feature does not belongs to your `cassandra\Query` class as you say, why it should belong to `db\Query` then?

**Comment by dynasource** [comment]
@mcd-php, you could use the event \yii\base\View::EVENT_BEFORE_RENDER and update your (dataprovider) queries

**Comment by mcd-php** [comment]
@klimov-paul It is inspired by Cassandra deficiency but is not tied to Cassandra - if someone will use my trait in any other subclass of `Query`, it will work OK even without `mycompany\yii2\db\cassandra` - all it needs are `parent::all()` and `parent::one()`.

**Comment by klimov-paul** [comment]
`yii\db` layer is designed to retrieve the data from the database, not to process it.
If you need to process query result further you should do it at the other place. Allowing `Query` to do so will inspire bad programming practice.
Still, you are free to publish your trait as extension.
