### ISSUE TITLE
Object with __toString() as query parameter = PDO error, string looks OK.

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7192]
Right after implementing #7181 I stumbled on a trange error:

Then I pass the boxed object as query parameter (`SomeModel::find()->where(['id'=>$someId])`), Cassandra PDO tells me `CQLSTATE[HY000] [2] Invalid STRING constant (a11...4df) for "id" of type uuid`. (The UUID is perfectly the same)

If I put `(string)` (typecast) before `$someId`, everything works.

But `__toString()` is being called on it anyway, from `\yii\db\Command::bindPendingParams` at `pdoStatement->bindValue()` - if I set breakpoint on __toString(), stack trace tells me so !

Adding typecast to `\yii\db\Command::bindPendingParams` as `$this->pdoStatement->bindValue($name, (string)$value[0], $value[1]);` does not help at all.

What can it be - some creepy misfeature or bug in PHP, PDO, Cassandra PDO driver ? I see where's likely not framework bug, but maybe you do know how to fight it or where to escalate ?

**Comment by cebe** [comment]
Please try to reproduce it with plain PDO and report it to PDO/Cassandra if it is possible.

**Comment by mcd-php** [comment]
Fixed in my private Cassandra library, it was [https://github.com/Orange-OpenSource/YACassandraPDO/issues/64]
