### ISSUE TITLE
suggestion feature captcha once

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#7194]
Is it an idea to implement the feature that if a user has done the captcha right for a form once, it wont have to be typed again for the same form session? It adds to the userfriendlyness.

**Comment by qiangxue** [comment]
That means once a spammer has passed captcha once, he has full freedom to spam.

**Comment by klimov-paul** [comment]
You may implement this behavior on your own.
This is mainly matter of the model validation then captcha widget or action.

**Comment by dynasource** [comment]
Why should a user redo a captcha every time he fails a other validator? If you still dont believe it is human, the captcha is wrong in itself?

**Comment by cebe** [comment]
you can add a flag in the session if your form passes validation and skip the validator if flag is present. This is all possible with current features of yii.

**Comment by dynasource** [comment]
alright. Thanks.
