### ISSUE TITLE
BaseActiveRecord::fields() not working with relations.

### ISSUE THREAD

**Issue by joni-jones** [yiisoft/yii2#7197]
I have the `User` model with specified `fields()` method:

``` php
class User extends ActiveRecord
{
    public function fields()
   {
       $fields = parent::fields();
       unset($fields['access_token'], ...); //unset all sensative fields
   }
}
```

Also I have the `Notification` model, which related to `User`:

``` php
class Notification extends ActiveRecord
{
    public function getSender()
    {
        return $this->hasOne(User::className(), ['id' => 'sender_id']);
    }

   public static function getInbox($userId)
    {
        return static::find()
            ->joinWith('sender')
            ->where(['receiver_id' => $userId])
            ->orderBy(['send_time' => 'ASC'])
            ->asArray()
            ->all();
    }     
}
```

If call `Notification::getInbox($someUserId)`, when each instance of `sender` will be contain sensative fields from `User` model, which should be removed by `fields()` method.

**Comment by Faryshta** [comment]
`fields` method is only used by the `toArray` method, which is when you want to turn an `ActiveRecord` to an array.

If you want to change the attributes returned by your example you have to either turn the active records to array or use the `select` on your active query

**Comment by joni-jones** [comment]
@Faryshta thanks for explanation. `select` not will be works as expected in this case. It will be return all specified columns, but all fields from `sender` entity also will be presented.

In my code I also use `asArray()` method. I think if call this method it should call `toArray()` for each ActiveRecord instance.

**Comment by Faryshta** [comment]
asArray will turn the ActiveQuery to an array directly without ever creating an ActiveRecord.

What I suggested was an extra step, very slow and resource demanding.

Before doing that. lets try this.

1) Modify your active query to use select

    return static::find()
            ->select([
                'sender_name' => 'sender.name'
                'sender_email' => 'sender.email'
               // etc
            ])
            ->joinWith('sender')
            ->where(['receiver_id' => $userId])
            ->orderBy(['send_time' => 'ASC'])
            ->asArray()
            ->all();
   
Execute it on local with the debug toolbar activated.

then check the database trace to see which is the exact querry being executed.

**Comment by joni-jones** [comment]
Event if you specify only some columns in `select()`, `sender` property will be contain all fields.
```
array (size=12)
      'id' => int 28
      'sender_id' => int 3
      'receiver_id' => int 1
      'message' => string 'Some message' (length=36)
      'subject' => string 'Some subject' (length=17)
      'priority' => int 2
      'status_id' => int 1
      'send_time' => int 1390929775
      'read_time' => null
      'sender_name' => string 'user' (length=4)
      'sender_email' => string 'test@gmail.com' (length=26)
      'sender' => 
        array (size=12)
          'id' => int 3
          'email' => string 'test@gmail.com' (length=26)
          'username' => string 'user' (length=4)
          'auth_key' => string '****************************' (length=32)
          'access_token' => string '**********************************' (length=32)
          'reset_token' => string '                                ' (length=32)
          'status_id' => int 1
          'is_online' => boolean true
```

**Comment by Faryshta** [comment]
did you got the query that is being executed?

**Comment by joni-jones** [comment]
This is query for previous output:
```sql
SELECT "notifications".*, "users"."username" AS "sender_name", "users"."email" AS "sender_email"
FROM "notifications"
LEFT JOIN "users" ON "notifications"."sender_id" = "users"."id"
WHERE "receiver_id"=1 ORDER BY "send_time"
```

**Comment by Faryshta** [comment]
there is something weird here. i had the impresion that  https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L154 `prevented table.*` from being used

**Comment by joni-jones** [comment]
UPD: I found way to get needed result without sensative fields:
```php
public static function getInbox($userId)
{
    return static::find()
        ->joinWith([
            'sender' => function($query) {
                $query->select(['id', 'username']);
            }
        ])
        ->where(['receiver_id' => $userId])
        ->orderBy(['send_time' => 'ASC'])
        ->asArray()
        ->all();
} 
```

**Comment by dynasource** [comment]
> I found way to get needed result

issue seems to be resolved

**Comment by Jakupov** [comment]
Hello
I have same issue with some difference: I don't have fields to unset, but have additional fields, calculated in model itself. As those fields missing in table itself, I cannot use '$query->select()'. 
And I cannot access calculated fields directly because I'm using query results in js, not php.

**Comment by Jafarili** [comment]
> UPD: I found way to get needed result without sensative fields:
> 
> ```
> public static function getInbox($userId)
> {
>     return static::find()
>         ->joinWith([
>             'sender' => function($query) {
>                 $query->select(['id', 'username']);
>             }
>         ])
>         ->where(['receiver_id' => $userId])
>         ->orderBy(['send_time' => 'ASC'])
>         ->asArray()
>         ->all();
> } 
> ```

this is not working when we have multiple joins with a table.
for example: (when `sender` and `user` are joining with the same table)
```
static::find()
        ->joinWith([
            'sender' => function($query) {
                $query->select(['id', 'username']);
            },
            'user' => function($query) {
                $query->select(['id', 'username']);
            },
        ])
        ->where(['receiver_id' => $userId])
        ->orderBy(['send_time' => 'ASC'])
        ->asArray()
        ->all();
```
