### ISSUE TITLE
urlManager['showScriptName'] value data type inconsistent.

### ISSUE THREAD

**Issue by davidjeddy** [yiisoft/yii2#7205]
ENV: CentOS 7
PHP 5.4.16
httpd 2.4.6
Yii2 advanced setup

	'urlManager' => [
            ...
            'showScriptName' => 'false',
        ],

however changing the showScriptName to a boolean like so

	'urlManager' => [
            ...
            'showScriptName' => false,
        ],

causes 404's. The value of showScriptName should be allowed to be a boolean like every other boolean option parameter in the main.php

On OSX 10.10.x this does not appear to cause an issue.

**Comment by nvthaovn** [comment]
String 'false' or any value is not empty is equivalent to true value.
So
``
'showScriptName' => 'false'
``
equivalent to
``
'showScriptName' => true
``
It means that you catch "404 not found" when showScriptName is off. This is not a bug. 
Let check your htacess file, then your rules.
