### ISSUE TITLE
Change access-token to access_token of yii2/filters/auth/QueryParamAuth.php ?

### ISSUE THREAD

**Issue by funson86** [yiisoft/yii2#7207]
While using RESTful api for the Android and iOS development, the access-token can not reflect to variable or object in Android and iOS.  Currently I use a class extending QueryParamAuth and change "public $tokenParam = 'access-token';"  to "public $tokenParam = 'access_token';". It works fine.

Could the access-token change to access_token easy to the Android and iOS developers to use?

**Comment by fernandezekiel** [comment]
there's probably a way for Android or iOS to work around this, also you don't have to extend the QueryparamAuth just to change the param, just change it when declaring the behavior

**Comment by samdark** [comment]
What's the problem with Android and iOS about `access-token` name exactly?

**Comment by samdark** [comment]
What's the problem with Android and iOS about `access-token` name exactly? As I know, there's no problem with any parameter names.

**Comment by fernandezekiel** [comment]
he probably is trying to map some kind of request object wherein the query string parameters are the object properties, and since there is a hyphen on `access-token` it can't be straightforward

**Comment by samdark** [comment]
I see. It's public property so could be adjusted as needed.

**Comment by funson86** [comment]
For example. In Android,  I use one line to parse result to object Token as the following code. In the class Token, It's not allowed to define `String access-token;`, I have to define `String access_token` it could not convert access-token to access_token automatically.
On the other side. when i POST/GET/PUT, I need to convert access_token to access-token in url manually.


```
	Token token  = JSONObject.parseObject(responseInfo.result, Token.class);
```


```
package com.example.m0;

import java.io.Serializable;

public class Token implements Serializable{

	private static final long serialVersionUID = 1218240460162235821L;
	private String result;
	private String access_token;
	public String getResult() {
		return result;
	}
	public void setResult(String result) {
		this.result = result;
	}
	public String getAccess_token() {
		return access_token;
	}
	public void setAccess_token(String access_token) {
		this.access_token = access_token;
	}
}
```

Currently I use the following code:
```
<?php

namespace api\components;

/**
 * QueryParamAuth for iOS and Android variable
 */

class QueryParamAuth extends \yii\filters\auth\QueryParamAuth
{
    public $tokenParam = 'access_token';
}
```

**Comment by aotd1** [comment]
@funson86, as @samdark already said, you don't need to extend QueryParamAuth, you can change  $tokenParam value in behavior init of your controller class:
```php
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
                'class' => QueryParamAuth::className(),
                'tokenParam' => 'access_token',
        ];
        return $behaviors;
    }

**Comment by funson86** [comment]
Got it. Thank you very much!
