### ISSUE TITLE
How to change no-cache header of assets?

### ISSUE THREAD

**Issue by gb5256** [yiisoft/yii2#7208]
Hi, 
I am using yii2 advanced template and I would like to change the header of the assets that are published with an asset bundle. I am in dev mode.
I am aware how to set the header inside a controller, but this does not affect the header of the assets that are loaded by that controller.

Any ideas?
gb5256

**Comment by samdark** [comment]
What do you mean by header of assets?

**Comment by gb5256** [comment]
If I look into firebug, I can see that my browser is downloading all the assets with every reload of a page again and again. Looking into firebug/net you can view the headers that are sent together with all the assets coming in. I can see that the header is always (no-cache). Or is this something I have to set on my server?

**Comment by Alex-Code** [comment]
Sounds like a server config issue.
You'd only be able to set headers for asset files if you used the framework to serve them but that adds unnecessary overhead.

**Comment by gb5256** [comment]
Ok, thanks for the info. I will check my Apache config, maybe there is an error.
Thanks for the quick replies. 
gb5256
