### ISSUE TITLE
[Ask/Enh] Adding a new guide page for working with form fields

### ISSUE THREAD

**Issue by joshijitendra** [yiisoft/yii2#7214]
How about adding a new guide page for working with form fields such as dropdownList, checkboxList and radiobuttonList along with Active Record including sample code. 
I can work on creating this page if you feel this might be useful.

**Comment by samdark** [comment]
You mean extending http://www.yiiframework.com/doc-2.0/guide-input-forms.html with more examples?

**Comment by joshijitendra** [comment]
Yes, extending http://www.yiiframework.com/doc-2.0/guide-input-forms.html 
or adding a new page under "Getting Data from Users" section.

**Comment by samdark** [comment]
I'm for extending existing one with more examples.

**Comment by joshijitendra** [comment]
Great! I am fine with extending existing http://www.yiiframework.com/doc-2.0/guide-input-forms.html
to add example for DropdownlLst, CheckboxList and RadiobuttonList with ActiveRecord implementation.

I will get started and make Pull requests when ready.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/02a85445b1c75a3575aaef50ce65cc068606dea2, https://github.com/yiisoft/yii2/commit/164bfd25f57ccf6fdac8bd4c07dd21ecbef39e1d
