### ISSUE TITLE
Incorrect response format type for CaptchaAction. Captcha not refreshing by click on it.

### ISSUE THREAD

**Issue by InteLigent** [yiisoft/yii2#7218]
Problem in line
https://github.com/yiisoft/yii2/blob/master/framework/captcha/CaptchaAction.php#L124

Because action return already formatted data at json. In summary, data twice encode in formatter JsonResponseFormatter.

Simple solution add code:

```php
Yii::$app->response->format = Response::FORMAT_RAW;
```
before line https://github.com/yiisoft/yii2/blob/master/framework/captcha/CaptchaAction.php#L124

**Comment by qiangxue** [comment]
Thanks!
