### ISSUE TITLE
Yii debuger toolbar in rtl page

### ISSUE THREAD

**Issue by mohammadhosain** [yiisoft/yii2#7222]
Yii debuger toolbar is not displayed properly when use dir='rtl' for body.

**Comment by johonunu** [comment]
Hi @mohammadhosain! 
Can you check if my pull request fixes your problem and if I need to fix something more?
I am not RTL user just trying to help.

**Comment by mohammadhosain** [comment]
Fixed for me by adding 'direction=ltr' to toolbar.css .

**Comment by samdark** [comment]
You mean by applying https://github.com/yiisoft/yii2/pull/7242?

**Comment by mohammadhosain** [comment]
No. I change 
```
#yii-debug-toolbar {
    padding: 0;
    font: 11px Verdana, Arial, sans-serif;
    text-align: left;
....
```
to
```
#yii-debug-toolbar {

    padding: 0;
    font: 11px Verdana, Arial, sans-serif;
    text-align: left;
