### ISSUE TITLE
Remove wrapper tag using yii\bootstrap\ ActiveForm

### ISSUE THREAD

**Issue by hoa2ng** [yiisoft/yii2#7225]
Hello,

I use 

```php
echo $form->field($model, 'type', [
                            'wrapperOptions' => []
                        ])->hiddenInput(['value' => 1])->label(false);
```
but I can't disable ( remove ) wrapper tag around input tag
Thanks

**Comment by fernandezekiel** [comment]
this is where you use `Html::activeTextInput()`

**Comment by mdmunir** [comment]
What you trying to do?
Why dont use `Html::activeHiddenInput($model,'type')` ?
Second, use yii forum for asking.

**Comment by hoa2ng** [comment]
Hi,
sorry I will use yii forum for asking, I use yii\bootstrap\ ActiveForm because most of the rest of the form need wrapper tag, only one of them is without

Thanks

**Comment by Faryshta** [comment]
I still think that `ActiveField::hidenInput()` should return no wrapper, label or errors since they are never meant to be used after all.

**Comment by samdark** [comment]
- https://github.com/yiisoft/yii2/issues/6750
- https://github.com/yiisoft/yii2/issues/2990
- https://github.com/yiisoft/yii2/issues/2391
- https://github.com/yiisoft/yii2/issues/735
- https://github.com/yiisoft/yii2/issues/641

**Comment by samdark** [comment]
@hoa2ng try using `Html::activeHiddenInput`.
