### ISSUE TITLE
Cache Dependencies - Help

### ISSUE THREAD

**Issue by wilsonfalai** [yiisoft/yii2#7229]
I have the following code using AR

$site = Yii::$app->cache->get($key);
if ($site === false) {
          $site = Site::find()
                    ->where(['dominio' => $dominio])
                    ->with('cliente','siteTelefones','sitePaginas')
                    ->one();
         Yii::$app->cache->set($subdominio, $site,600);
}

How i use Cache Dependency in my code?

*On the site table and cliente table i have created_at and updated_at
*site hasOne cliente, site hasMany siteTelefones and sitePaginas

**Comment by mdmunir** [comment]
Read this http://www.yiiframework.com/doc-2.0/guide-caching-data.html#cache-dependencies.
Use official [forum](http://www.yiiframework.com/forum/) for asking.
