### ISSUE TITLE
ADD: Methods to compose DB query conditions

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7234]
Was: `$condition = ['and', $condition, $viaRelation->where];`
Propose: `WhatClassQ::composeConditionsAnd($condition1,$condition2)`

Reason: To be capable to hook condition composition in one place and simplify gradually as it grows, converting AND/OR on the same columns into set intersection or addition.

**Comment by qiangxue** [comment]
Will not support this as it doesn't add any benefit.
