### ISSUE TITLE
Display uploaded images

### ISSUE THREAD

**Issue by AlexMerser21** [yiisoft/yii2#7235]
Hello. I am new in Yii. I use advanced application. There is an article about file uplopading in the wiki, but there is not any information how to display uploaded in frontend and backend. So I want to display uploaded image(by form) both in frontend and backend. I'll be gald to see exmaples

**Comment by Alex-Code** [comment]
Please refer to the forums for questions, http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/
Git is for issues regarding the framework.

**Comment by AlexMerser21** [comment]
Solved by adding frontend url to params
