### ISSUE TITLE
What's the minimum icu version needed?

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/yii2#7236]
My server env:
```
php 5.5.21
intl version is 1.1.0
icu version is 4.2.1
```
I try [doc](https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-i18n.md#plurals), the plurals and Selections example can not run.

there throw exception:

```
PHP Warning – yii\base\ErrorException

MessageFormatter::__construct(): msgfmt_create: message formatter creation failed
```
at yiisoft/yii2/i18n/MessageFormatter.php line 102.

regards

**Comment by samdark** [comment]
49: https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-i18n.md#setting-up-your-php-environment-

**Comment by lichunqiang** [comment]
@samdark Thanks~

regards
