### ISSUE TITLE
'catchAll' component not working when configured with a 'yii\web\ViewAction' action

### ISSUE THREAD

**Issue by telmochan** [yiisoft/yii2#7237]
the ViewAction is always trying to find the view from '$viewParam' value in the url or the $defaultView of the ViewAction when url doesn't contain a '$viewParam' value.
Based on the reasons above, none of the catchAll config below works:
1.
'catchAll' => ['site/page', 'view'=>'about']
2.
'catchAll' => ['site/page?view=about']
3.
'catchAll' => ['site/page#view=about']

I think there is no need to config a new action for catchAll, because normally the catchAll is used for displaying a static page. So a single ViewAction would be enough to include all the pages and the catchAll page

**Comment by samdark** [comment]
That's logical use case. I'd expect it to work.

**Comment by qiangxue** [comment]
According to the API doc for `catchAll`: 

>  The configuration is an array whose first element specifies the route of the action.
    The rest of the array elements (key-value pairs) specify the parameters to be bound
     to the action. For example,

So this won't work for the `ViewAction` because the action doesn't use action parameter binding. You will need to create an action explicitly in order to support this.

**Comment by telmochan** [comment]
I know the api, it's just a proposal

发自我的 iPhone
