### ISSUE TITLE
route with module

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#7238]
after adding module and moving to it, route breaks for native application controllers by adding its module name into path even if we produce layout from application

app/
---layouts
--------myalyout.php                <---- here we define Url::toRoute(['site/index'])
modules
---abc
--------controllers
-------------DefaultController.php     <---- here we stand rendering its index view using mylayout.php

before adding module "abc"
Url::toRoute(['site/index'])  ----->  ?r=site/index

after adding module "abc" and moving to it  ( ?r=abc )
Url::toRoute(['site/index'])  ----->  ?r=abc/site/index

possible workaround 
Url::toRoute(['//site/index']);

is it proper behavior and i just must add double slash?

regards

**Comment by lynicidn** [comment]
/absolute/path/ (with any module or without it)
relative/path (relative with current module)

**Comment by lynicidn** [comment]
```quote
A route may be either absolute or relative. An absolute route has a leading slash (e.g. /site/index), while a relative route has none (e.g. site/index or index). A relative route will be converted into an absolute one by the following rules:

    If the route is an empty string, the current [[\yii\web\Controller::route|route]] will be used;
    If the route contains no slashes at all (e.g. index), it is considered to be an action ID of the current controller and will be prepended with [[\yii\web\Controller::uniqueId]];
    If the route has no leading slash (e.g. site/index), it is considered to be a route relative to the current module and will be prepended with the module's [[\yii\base\Module::uniqueId|uniqueId]].
```
(c) https://github.com/yiisoft/yii2/blob/master/docs/guide/helper-url.md#creating-urls-

**Comment by samdark** [comment]
That's expected as @lynicidn pointed out.
