### ISSUE TITLE
Relational query hasMany() not return Active Query as document cailmed 

### ISSUE THREAD

**Issue by mathed4all** [yiisoft/yii2#7240]
i am working on a content-tag system using yii2.

I have a Content(PK:id) table, I have a Tag(PK:id) table, and I have a junction table called Content_Tag (PK:content_id, tag_id). 

now i want to show all content with same keywords in a grid view (sortable, searchable just as content index page) on keyword view page.

i'm using `via` in keywords Class according to the documentation as following:

     /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent() 
    {
        return $this->hasMany(Content_Tag::className(), ['content_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContents()
    {
        return $this->hasMany(Tag::className(), ['tag_id' => 'tag_id'])->viaTable('content_tag', ['content_id' => 'id']);
    }

and modify the controller in action view

    public function actionView($id)
    {
        $query=$this->findModel($id)->problems;
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

Now the error log shows `$query` in controller in ActiveQuery Class.
> The "query" property must be an instance of a class that implements the QueryInterface e.g. yii\db\Query or its subclasses.

**Comment by Faryshta** [comment]
In which class you have the `getContent` and `getContents` methods declared?

**Comment by serhatozles** [comment]
query=$this->findModel($id)->problems;
-------------
->problems => What's that??
-------------
This is variable. You have to use class method for ActiveDataProvider.
Then you can use like this for it;
$query=$this->findModel($id);
------------
And you have to use "joinWith" function for Relations table.

**Comment by mdmunir** [comment]
use
```php
$model->getContents()
```
instead of 
```php
$model->contents;
```

**Comment by mathed4all** [comment]
retre
