### ISSUE TITLE
Request::getScriptUrl  return wrong path

### ISSUE THREAD

**Issue by luffyfly** [yiisoft/yii2#7245]
I run yii2 basic  with nginx and fastcgi and the chrome browser can't load css and js, return 404.
I dig into the source code and found that Request::getScriptUrl  method returns the full path of the asset file, not the relative url.
I think, this method should return the url relative to the document root if the document root value exists in the $_SERVER.

New code may like this :https://github.com/luffyfly/yii2/blob/51d586ea34157df4a33ca0eddace034fdcec3234/framework/web/Request.php#L591

**Comment by samdark** [comment]
Could you provide steps to reproduce the issue?

**Comment by cebe** [comment]
@luffyfly can you show the content of `$_SERVER`?

**Comment by samdark** [comment]
Closed since no additional info provided.

**Comment by luffyfly** [comment]
Sorry for replying so late.
$_SEVER dump:
array(34) {
  ["USER"]=>
  string(3) "www"
  ["HOME"]=>
  string(9) "/home/www"
  ["FCGI_ROLE"]=>
  string(9) "RESPONDER"
  ["QUERY_STRING"]=>
  string(0) ""
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["CONTENT_TYPE"]=>
  string(0) ""
  ["CONTENT_LENGTH"]=>
  string(0) ""
  ["SCRIPT_NAME"]=>
  string(33) "/home/www/dashboard/web/index.php"
  ["REQUEST_URI"]=>
  string(1) "/"
  ["DOCUMENT_URI"]=>
  string(10) "/index.php"
  ["DOCUMENT_ROOT"]=>
  string(23) "/home/www/dashboard/web"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["SERVER_SOFTWARE"]=>
  string(11) "nginx/1.6.2"
  ["REMOTE_ADDR"]=>
  string(12) "112.64.94.65"
  ["REMOTE_PORT"]=>
  string(5) "58605"
  ["SERVER_ADDR"]=>
  string(13) "121.40.62.235"
  ["SERVER_PORT"]=>
  string(2) "80"
  ["SERVER_NAME"]=>
  string(21) "xxx.xxxx.com"
  ["REDIRECT_STATUS"]=>
  string(3) "200"
  ["SCRIPT_FILENAME"]=>
  string(33) "/home/www/dashboard/web/index.php"
  ["PATH_INFO"]=>
  string(0) ""
  ["PATH_TRANSLATED"]=>
  string(33) "/home/www/dashboard/web/index.php"
  ["HTTP_HOST"]=>
  string(21) "dashboard.donever.com"
  ["HTTP_CONNECTION"]=>
  string(10) "keep-alive"
  ["HTTP_CACHE_CONTROL"]=>
  string(9) "max-age=0"
  ["HTTP_ACCEPT"]=>
  string(74) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  ["HTTP_USER_AGENT"]=>
  string(120) "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(19) "gzip, deflate, sdch"
  ["HTTP_ACCEPT_LANGUAGE"]=>
  string(47) "en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2"
  ["HTTP_COOKIE"]=>
  string(36) "PHPSESSID=jodqrc5oth63tblv83pu2t1k04"
  ["PHP_SELF"]=>
  string(33) "/home/www/dashboard/web/index.php"
  ["REQUEST_TIME_FLOAT"]=>
  float(1426577901.5179)
  ["REQUEST_TIME"]=>
  int(1426577901)
}

**Comment by samdark** [comment]
Could you post nginx config as well?
