### ISSUE TITLE
PHP Fatal Error (warrning) in TestCase.

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#7246]
In my unit test appeared warrning. Stretches from here.
![image](https://cloud.githubusercontent.com/assets/874234/6163240/6222543e-b2a0-11e4-9e08-f217193fb46d.png)
In `\yii\codeception\DbTestCase`, there is no warning.
![image](https://cloud.githubusercontent.com/assets/874234/6163304/53c757a8-b2a1-11e4-8912-ed9aa29b6d3c.png)

Test working fine. But how to get rid of the warning?

**Comment by samdark** [comment]
Looks like IDE bug.
