### ISSUE TITLE
Internationalization doesn't mention yii message command

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#7252]
In http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#message-translation the command isn't mentioned. That leads to confusion about how to get messages and how to work with these. Need to describe full workflow there.

**Comment by machour** [comment]
This have been done on March 20: https://github.com/yiisoft/yii2/commit/21599fad8a81dbd6a838640808922f15cf89eb2b
Issue can be closed

**Comment by SilverFire** [comment]
Thank you
