### ISSUE TITLE
Sorting and paginating request parameters not described in docs

### ISSUE THREAD

**Issue by kamil-zielinski** [yiisoft/yii2#7253]
Hello,

I search the docs while implementing ActiveController for information about 'per-page' parameter send with request and couldn't find anything. Same with 'sort'. I had to look in the code to see how it works. Sort is quite tricky with this minus sign for order.
You should improve docs here
- yii2/docs/guide/output-sorting.md
- yii2/docs/guide/output-pagination.md

**Comment by dynasource** [comment]
both of your questions are well described at:
* http://www.yiiframework.com/doc-2.0/guide-output-pagination.html
* http://www.yiiframework.com/doc-2.0/guide-output-sorting.html
