### ISSUE TITLE
Bug when using mongodb for user auth storage

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#7256]
I have noticed that the MongoDB Yii2 extension saves the $id of the user model within the cookie as an array.

I thought about modding getId() of the active record to return only a string, but I was unsure if it had hidden usage else where, whereby it would have been preferable to have the object back.

When logging in via cookies from MongoDB the code fails on line 306 of the User.php component due to not being able to convert array to string.

Am I supposed to change the getId() or is this a bug?

**Comment by klimov-paul** [comment]
See #2129
