### ISSUE TITLE
Tabs widget dont save the render action update

### ISSUE THREAD

**Issue by andreymecheva** [yiisoft/yii2#7257]
Hi,

I have a tabs widget, in this one tab render action controller:
<code>$this->render('action', ['model' => $model])</code>
but, when i try save this model, dont work

**Comment by samdark** [comment]
Please provide more details about the issue.\

**Comment by andreymecheva** [comment]
the widget
<code>
echo Tabs::widget([
    'items' => [
        [
            'label' => 'One',
            'content' => $this->render('update', ['model' => $model]),
            'active' => true
        ]
    ],
]);
</code>
the actionController
<code>
 public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ide_pro]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
</code>
and the view is the same by default gii

**Comment by samdark** [comment]
Are you submitting it to update action?

**Comment by andreymecheva** [comment]
yes

**Comment by samdark** [comment]
Does it work if you move it our of the tab widget i.e.

```php
<?= $this->render('update', ['model' => $model]) ?>
```

?

**Comment by andreymecheva** [comment]
no

**Comment by samdark** [comment]
Then it's not connected with tabs. Check logs in order to find out what's the problem. Most probably you're submitting to wrong action. Anyway, it doesn't look like framework issue so closing the ticket.
