### ISSUE TITLE
Filter Model Not Working

### ISSUE THREAD

**Issue by mathed4all** [yiisoft/yii2#7262]
i am working on a content-tag system using yii2.

I have a Content(PK:id) table, I have a Tag(PK:id) table, and I have a junction table called Content_Tag (PK:content_id, tag_id). 

now i want to show all content with same keywords in a grid view (sortable, searchable just as content index page) on keyword view page.

i'm using `via` in keywords Class according to the documentation as following:

     /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent() 
    {
        return $this->hasMany(Content_Tag::className(), ['content_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContents()
    {
        return $this->hasMany(Tag::className(), ['tag_id' => 'tag_id'])->viaTable('content_tag', ['content_id' => 'id']);
    }

and modify the controller in action view

    {
        $searchModel = new ContentSearch();
        $dataProvider = $searchModel->search([Yii::$app->request->queryParams, 'keyword_id'=>$id]);
        
        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

And modify the ContentSearch Model As following:

    public function search($params)
    {
        $query = ProblemRecord::find();
        if(isset($params['keyword_id']))
        {
            $query = KeywordRecord::findOne($params['keyword_id'])->getContents();
        }else{
            $query = ProblemRecord::find();
        }
    ...

the keywords/view.php file as following

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'level',
            ],
        ],
    ]) ?> 

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute'=>'type_id',
                'value'=>function ($data) {
                    return $data->typeOptions[$data->type_id];
                    },
                'filter'=> ProblemRecord::getTypeOptions(),
            ],
            [
                'attribute'=>'status_id',
                'value'=>function ($data) {
                    return $data->statusOptions[$data->status_id];
                    },
                'filter'=> ProblemRecord::getStatusOptions(),
            ],
            [
                'attribute'=>'question',
                'value'=>function ($data) {
                    return $data->questionHtml;
                    },
                'format'=> 'html',
            ],
            [
                'attribute'=>'keywords',
                'value'=>function ($data) {
                    return $data->keywordsHtml;
                    },
                'format'=>'html',
            ],
            'author.username',

            ['class' => 'yii\grid\ActionColumn'],

        ],
    ]); ?>
Now the gridview works, and sorting works, but the filters not work.

the js in the html code as following

    jQuery(document).ready(function () {
    jQuery('#w0').yiiGridView({"filterUrl":"/math2/backend/web/index.php?ProblemSearch%5Btype_id%5D=&ProblemSearch%5Bstatus_id%5D=&ProblemSearch%5Bquestion%5D=not&ProblemSearch%5Bauthor.username%5D=&r=keywords%2Fview&id=85&sort=-author.username","filterSelector":"#w0-filters input, #w0-filters select"});
    });

**Comment by mdmunir** [comment]
```php
$searchModel = new ContentSearch();
$params = Yii::$app->request->queryParams;
$params['keyword_id'] = $id;
$dataProvider = $searchModel->search($params);
```

**Comment by lynicidn** [comment]
```
$params = Yii::$app->request->queryParams;
$params['keyword_id'] = $id;
```
need add scope $model->formName

**Comment by mathed4all** [comment]
@mdmunir seems no difference with my version?

**Comment by mathed4all** [comment]
i see～

**Comment by krushn** [comment]
I solved this issue by adding field in model rule list to mark it safe.
