### ISSUE TITLE
extend bootstrap Tabs with urls (non-ajax content)

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#7264]
The issue:

Bootstrap has two tab styles:
 - css  http://getbootstrap.com/components/#nav-tabs
 - js http://getbootstrap.com/javascript/#tabs

The current \yii\bootstrap\Tabs focuses on the JS version. This means you can not have the best of two worlds. Sometimes I dont want a Tab to be loaded by Ajax, but to be at a separate page. Reasons:
- you need a tab content to be on a different page because of loading JS/AJAX
- you need a tab content to be on a different page because of your specific route architecture

On this separate page you are linking back with a CSS style Tab.

Therefore I would like to suggest to enable the acception of an URL. This would extend the functionality of current Tabs Besides, it would also enable the bootstrap CSS styled Tab, improving disambiquity on this matter.

This is a minor addon, I can do a submit for this.

**Comment by samdark** [comment]
Nav tabs isn't tabs widget but `Nav` one.

**Comment by dynasource** [comment]
1) its not a trigger, its a (menu) link
2) it is a tab widget as both ajax & links are both possible
3) using multiple nav-menu is ugly and unnecessary
4) the solution is (too) easy without disadvantages
5) it has multiple advantages

**Comment by dynasource** [comment]
Pull request
https://github.com/yiisoft/yii2-bootstrap/pull/11

**Comment by dynasource** [comment]
pull request from the Yii2 repo:
https://github.com/yiisoft/yii2/pull/7284

**Comment by cebe** [comment]
fixed by https://github.com/yiisoft/yii2-bootstrap/commit/554c3ccf04ee0c5ae699615d2866d8a6826d1ffb
