### ISSUE TITLE
Make \yii\db\Query::all(), one() etc. hookable by EVENT_ROWS_POST_PROCESS

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7268]
Example:

``` php
trait QueryPostProcessTrait {
    public function postProcessRows($rows) {
        $e = new Event();
        $e->data = $rows;
        $this->trigger('EVENT_ROWS_POST_PROCESS',$e);
        return $e->data;
    }

    public function all( $db = null ) {
        $rows = parent::all($db);
        return $this->postProcessRows($rows);
    }

    public function one( $db = null ) {
        $rows = [parent::one($db)];
        return $this->postProcessRows($rows)[0];
    }
}
```

I now have _two_ uses for this, group/order (https://github.com/yiisoft/yii2/issues/7187) and calling `toArrayRecursive()` (https://github.com/yiisoft/yii2/issues/7179) on result, be it array or object. So it grew worth separating in it's own trait ;)

I believe this will beneficial for user-programmers in many ways !

**Comment by samdark** [comment]
Related to #4555

**Comment by dynasource** [comment]
lets wait for more people to vote on this feature. Then we know that there are usescases enough to evaluate if the framework is to be extended with this Event. Till that time we keep it on hold because of its drawback on performance.
