### ISSUE TITLE
Migration and new folders

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#7269]
Where am run `yii migrate/up --migrationPath="@yii\rbac\migration"` or do typo in word `migrations` this create new folders - it not correct behavior if action not `create`

**Comment by lynicidn** [comment]
i think true way throw invalid config (param) exception `folder not exists`. Now if migrations not found in folder - be created new folder and try apply migrations from default folder

**Comment by lynicidn** [comment]
По русски:
Если применяем миграцию, и ошиблись в migrationPath то будет создана папка соответствующая алиасу migrationPath, но список миграций отобразиться из дефолтной папки app/migrations, но при применении выскочит ошибка, что в ново созданной папке нет этой миграции. Отсюда 2 предложения -  создавать папку только при migrate/create и разобраться почему если миграции не найдены в папке (в новь созданной) выдается список из дефолтной папки - ведь это ошибка, сразу известно что пути не сойдутся. Вообщем там какоето неадекватное сейчас поведение

**Comment by samdark** [comment]
Agree. Can you work on a pull request?

**Comment by samdark** [comment]
Behavior for create action shold stay as it is now.

**Comment by lynicidn** [comment]
постараюсь, только на выходных, сейчас чуточку загружен

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/pull/7344
