### ISSUE TITLE
populateRecord being called on parent class ignoring object class returned by instantiate

### ISSUE THREAD

**Issue by jlorente** [yiisoft/yii2#7271]
Method populateRecord its being called after instantiate, but ignoring the class instance returned by instantiate. I think populateRecord should be called on the class instance returned by instantiate to allow specific population even querying on a parent class.
I will give an example:
```php
class Person extends \yii\db\ActiveRecord {
    public static function instantiate($row) {
        if ($row['type'] === 'ADMIN') {
            return new Admin();
        } else {
            return new User();
        }
    }
}
class User extends Person {
    public static function populateRecord($record, $row) {
        ///do something
    }
}
class Admin extends Person {
    public static function populateRecord($record, $row) {
        ///do something
    }
}
```
When you call Person::find()->all() for example, a collection of Admin and User objects will be returned but the overwritten method populateRecord won't be called on this objects.

I have found this problem on the following classes methods:

yii\db\ActiveQueryTrait::createModels()
yii\elasticsearch\ActiveRecord::get()
yii\elasticsearch\ActiveRecord::mget()
yii\mongodb\file\ActiveQuery::one()
yii\redis\ActiveQuery::one()
yii\sphinx\ActiveQuery::one()
And the code in it looks like this:
```php
$model = $class::instantiate($row);
$class::populateRecord($model, $row);
```
In my opinion it should be like this
```php
$model = $class::instantiate($row);
$class = get_class($model);
$class::populateRecord($model, $row);
```

**Comment by qiangxue** [comment]
As API doc writes, `populateRecord()` is an internal method. You should NOT override it.
You should put your record initialization logic in `instantiate()` instead.

**Comment by Faryshta** [comment]
@qiangxue question, lets say I have an instantiate method like this

```php
public function instantiate($row)
{
    $this->password = md5($row['password']);
}
```
Wouldn't populate override my custom password?

**Comment by qiangxue** [comment]
Makes sense.

**Comment by Faryshta** [comment]
I just noticed my example makes no sense

```php
public static function instantiate($row)
{
    $model = new static;
    $model->password = md5($row['password']);

    return $model;
}
```

Is a better example.
