### ISSUE TITLE
Some times redirect_uri should not POST in Google OAuth2

### ISSUE THREAD

**Issue by farhad2161** [yiisoft/yii2#7274]
According to google developer document some times we should not POST redirect_uri. But OAuth2 class always set it and this cause a problem.

public function fetchAccessToken($authCode, array $params = [])
    {
        $defaultParams = [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'code' => $authCode,
            'grant_type' => 'authorization_code',
            'redirect_uri' => $this->getReturnUrl(),
        ];
...
    }

public function getReturnUrl()
    {
        if ($this->_returnUrl === null) {
            $this->_returnUrl = $this->defaultReturnUrl();
        }
        return $this->_returnUrl;
    }

And here is google document : 
https://developers.google.com/accounts/docs/CrossClientAuth

Just search below lines in above link:

Android app obtains offline access for web back-end
When the web component exchanges the code for tokens, it should not include the redirect_uri argument in the POST request.

Thanks.

**Comment by klimov-paul** [comment]
You can unset any automatically appeneded paramter passing it with the `null` value:
```php
$client->fetchAccessToken($code, ['redirect_uri' => null]);
```
This way 'redirect_uri' value will not appear at the POST request.
