### ISSUE TITLE
Gii and Debug password protection

### ISSUE THREAD

**Issue by mohammadhosain** [yiisoft/yii2#7275]
Hi!
If the shared internet is used, `$allowedIps` is not enough for security in debug and gii extensions and anyone can access debug and gii.
Please add login with username and password for debug and gii extensions.

**Comment by samdark** [comment]
What do you mean by "shared internet"?

**Comment by mohammadhosain** [comment]
Sorry for my poor English!
If I access the Internet from a local network (LAN) in my home or office, it is possible that I share an IP address with other users.

**Comment by lynicidn** [comment]
see settings of you router

**Comment by mdmunir** [comment]
https://github.com/mdmsoft/yii2-action-filter

**Comment by cebe** [comment]
gii and debug toolbar should only be used in develop environment, which should not be exposed to public internet.

**Comment by mohammadhosain** [comment]
If I want to see debug details when site is in public internet, I need to access to debug !

**Comment by cebe** [comment]
okay, may be useful for debug. for gii there is no reason to add it imo.

**Comment by a-komarev** [comment]
Gii is useless in public internet. But about debugging i thought to add some $_GET parameter listener which will set cookie to current session and allow access to Debug panel.

Like if you will pass param with password `&debug_pass=JuhB4jNs` app will create cookie with this password which will display a panel all the time.

**Comment by mdmunir** [comment]
Try this https://github.com/mdmsoft/yii2-action-filter :D
Usage
```php
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        'as access' => [
            'class' => 'mdm\filter\EnterCode',
            'validationCallback' => function ($pass) {
                return $pass === 'rahasia';
            },
            'except' => [
                'default/toolbar', // actions
            ]
        ],
    ];

```

**Comment by mohammadhosain** [comment]
My idea : 
1.Add ```actionLogin``` to ```yii\debug\controllers\DefaultController```
2.In ```beforeAction``` check if debug session is not setted, redirect to login page.
username , password and session name should be setted in config file.

**Comment by klimov-paul** [comment]
I am unsure how password protection can be applied to 'debug' module as we need to check whether to display debug toolbar at the bottom at the page. At which stage you assume to ask a password for this?

**Comment by samdark** [comment]
Good catch :)

**Comment by mohammadhosain** [comment]
In localhost toolbar is displayed, but when site in Internet, it only is displayed after login with username and password.

**Comment by samdark** [comment]
But where/how to require login? Each page?

**Comment by mohammadhosain** [comment]
In ```beforeAction``` method checks:
 if session is not set and action is not ```toolbar``` redirect to login page. 
 if session is not set and action is  ```toolbar``` does not show toolbar.

**Comment by samdark** [comment]
OK but when and how to ask for password? Won't it be asked from normal users each time they visit website?

**Comment by mohammadhosain** [comment]
If user IP is in ```$alloewIPs``` that is set in config file , then user redirect to login page else 404 page is shown for login page.

**Comment by samdark** [comment]
But then that's not about debug toolbar overall but about protecting everything with password if IP matches X. Still, I think it's a terrible idea because you may have non-developer users at that IP. For example, if a large university works with a single external IP and does so with their website, all students will be requested a password each time which is useless for them and ruins their experience.

**Comment by mohammadhosain** [comment]
Password is not requested for every page of site. Password only is requested if user try to access debug pages.

**Comment by mdmunir** [comment]
I am neutral :D.
@mohammadhosain Read my comment above. For current implementasion, you can use my [extension](https://github.com/mdmsoft/yii2-action-filter) to protect your debug page.

**Comment by mohammadhosain** [comment]
Example : 
adding this code to yii\debug\Module 
```php
    public $username='';
    public $password='';
    public $session='debug-session';
```  
adding this to yii\debug\controllers\DefaultController
```php
public function beforeAction($action){
		if(parent::beforeAction($action) && $this->module->beforeAction($action)){
			if($action->id === 'login'){
				return true;
			}
			if(Yii::$app->getSession()->has($this->module->session)){
				return true;
			}
			if($action->id === 'toolbar'){
				return false;
			}
		}
		return $this->redirect(['default/login']);
	}
	public function actionLogin(){
		$loginForm=new LoginForm();
		if($loginForm->load(Yii::$app->request->post()) && $loginForm->login($this->module->username,$this->module->password)){
			Yii::$app->getSession()->set($this->module->session,true);
			return $this->redirect(['index']);
		}
		return $this->render('login',['model'=>$loginForm]);
	}
	public function actionLogout(){
		Yii::$app->getSession()->remove($this->module->session);
		return $this->redirect(['login']);
	}
```
creating LoginForm 
```php
<?php
namespace yii\debug\models;

use yii\base\Model;
class LoginForm extends Model{
	public $username;
	public $password;
	public function rules() {
		return [
				[['username','password'],'required']
		];
	}
	public function login($username,$password) {
		if(parent::validate()){
			if($this->username === $username && $this->password === $password){
				return true;
			}
			$this->addError('username','username or password is incurrect.');
		}
		return false;
	}
}
```
creatin login view 
```php
<?php
$this->title = 'Login';
?>
<div style="text-align: center;margin: 100px auto;width: 30%;">
    <?php $form = ActiveForm::begin([
        'id' => 'login-form',

    ]); ?>
    <?= $form->field($model, 'username') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>
```
and in config file 
```php
$config['modules']['debug'] = ['class'=>'yii\debug\Module','username'=>'user','password'=>'pass'];
```
also need to add logout link in debug layout.

**Comment by samdark** [comment]
@mohammadhosain what about toolbar itself?

![qip shot - screen 202](https://cloud.githubusercontent.com/assets/47294/7114365/36ab235c-e1e5-11e4-8897-f7a9540d90e6.png)

That's not what non-developers should ever see.

**Comment by mohammadhosain** [comment]
In my example ,toolbar is not seen before developer login.

**Comment by samdark** [comment]
So even if you're developer you'll never see the toolbar?

**Comment by klimov-paul** [comment]
@samdark, tollbar appearance can be bound to the session using following algorithm: if successful password check indicator is present in the session - show toolbar, if not - do not show, but do not ask for password either.
Password will be asked only when accessing debug module pages, route to which developer should write by hands, since he whould be able to see the toolbar until he entered password.
So this still may work.

**Comment by samdark** [comment]
Makes sense.

**Comment by samdark** [comment]
Not a priority though. @mohammadhosain want to work on a pull request?

**Comment by mohammadhosain** [comment]
https://github.com/yiisoft/yii2-debug/pull/12

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-debug/issues/88

**Comment by samdark** [comment]
#1266

**Comment by dynasource** [comment]
dont see why this problem is not solved with a .htpasswd

**Comment by samdark** [comment]
Because of different servers, I guess...

**Comment by dynasource** [comment]
are we not going into too much detail here? The usecases ares rare and there are enough other solutions for a developer to lock his application.

**Comment by samdark** [comment]
Anyway, this is per-module thing and exists in module issues already: https://github.com/yiisoft/yii2-debug/issues/88
