### ISSUE TITLE
Data Caching Bug with too large of data

### ISSUE THREAD

**Issue by nsanden** [yiisoft/yii2#7278]
Works fine when $total is 500 but errors when $total is 1000 (or greater)

using FileCache

```php
        //Yii::$app->cache->delete('test_data');
        $total = 500;
        if(!$data = Yii::$app->cache->get('test_data'))
        {
            for($i=0; $i < $total; $i++)
            {
                $data[] = [
                    'test1' => 'test1',
                    'test2' => 'test2',
                    'test3' => 'test3'
                ];
            }
        }
        Yii::$app->cache->set('test_data', $data);
```

![yii base errorexception](https://cloud.githubusercontent.com/assets/2072064/6193239/1843c5cc-b36e-11e4-8d34-6a4274159cba.png)

**Comment by qiangxue** [comment]
You should check the underlying cache storage limit.

**Comment by nsanden** [comment]
@qiangxue i'm just using the default FileCache - is there a limit there? i have plenty of disk space

**Comment by qiangxue** [comment]
Please check the generated cache file size. Yii doesn't enforce such kind of size limit.

**Comment by kartik-v** [comment]
The error could be also due to some bad character (UTF8) which serialize cannot parse.

You can try to encode the characters at serialize and decode at unserialize
```php
//to safely serialize
$safe_string_to_store = base64_encode(serialize($multidimensional_array));

//to unserialize...
$array_restored_from_db = unserialize(base64_decode($encoded_serialized_string));
```

**Comment by nsanden** [comment]
Sorry, was my bad. I thought I was working on a project that used FileCache, turned out i'm working on one thats using DbCache and the "blob" field wasn't big enough for this case.
