### ISSUE TITLE
Make Widget::getId() auto generate unique id 

### ISSUE THREAD

**Issue by callmez** [yiisoft/yii2#7281]
sometimes  two(or more) widgets can not work at page (widget load with ajax, `static::$counter` is not good solution for ajax). 
could make it auto generate unique id as default? thanks.

**Comment by qiangxue** [comment]
We have discussed this before and we decided to keep the current design.

**Comment by callmez** [comment]
related to #4749

**Comment by callmez** [comment]
Although it is not good idea,  but sometimes it can solve the problem. 
could set it as optional?

**Comment by qiangxue** [comment]
As suggested, you simply manually configure `id` with the value of `uniqid()`.

**Comment by callmez** [comment]
ok... thanks
