### ISSUE TITLE
question of the request parameters passing

### ISSUE THREAD

**Issue by kaybinwong** [yiisoft/yii2#7286]
hi there.
i have the parameter to pass to all the a tag in the page, for example, when i visit the url: xxxx.com/a.php?vt=1, how could i pass the parameter vt to a tag in the page of a?
thx

**Comment by mdmunir** [comment]
`$_GET['vt']`

**Comment by kaybinwong** [comment]
@mdmunir you might mistake. i say passing by means the parameter pass to all the a tag automaticly(through configuring the parameter)，but not manual operation such as 
Yii::$app->urlManager->createUrl(['open/index', 'type' => 'new', 'vt'=> $_GET['vt']]).

@qiangxue any idea?
thx any way.

**Comment by kaybinwong** [comment]
if i want to replace all the a tag before response, what should i do, does anything like java  intercept?
