### ISSUE TITLE
unique validator is not working

### ISSUE THREAD

**Issue by ajkosh** [yiisoft/yii2#7287]
model
 public function rules()
    {
        return [
            [['user_id', 'status', 'is_primary','is_delete'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['title'], 'unique'],
        ];
    }
controller
 public function actionCreate()
    {
        $model = new EmailUser();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
----------------------------------------------------
view
in view this only field i have
        <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>  
      
what is issue ,i did not find?

**Comment by mdmunir** [comment]
unique validator has no client validator. It is working only on server.

PS: Please read this https://guides.github.com/features/mastering-markdown/ before posting

**Comment by ajkosh** [comment]
why this is closed ,i ddi nt get you.
always there are issue related to unique validator,those are still opened
mdmunir plz you should read what you post before ,there is nothing related to my issue.
kind of ur info i know it has no client validator,and it is server side ,wat it is not working server side also
i think i should create again,if you guys dont solve then tell us we will not create issue here,

**Comment by qiangxue** [comment]
@ajkosh Please try to give more details to explain what is the problem you encountered. You only mentioned the validator is not working, but you didn't really explain how it is not working.

**Comment by ajkosh** [comment]
then you should ask ,you did nt get wat i told you
if email is unique then simply it should trigger error,i defined into model rule but still it is not working,when i submit form it is not showing any error but record also not saving into database,
here problem is unique is working but it is not showing any error

**Comment by ajkosh** [comment]
i think with declare in model rule with unique validator ,it should work

**Comment by qiangxue** [comment]
So you are complaining that when you entered a non-unique title, the form doesn't display any unique error message while the record is not saved either?

Please make sure that your css style is not hiding the error message. Also do some debugging to find the content of `$model->errors` (it must have some content because as you said the record is not saved).

I was closing the issue because the report is not following the rules as described in https://github.com/yiisoft/yii2/blob/master/docs/internals/report-an-issue.md. When all the information are ready, we can reopen the issue.

**Comment by ajkosh** [comment]
ok i try
if i m saving email first time ,it is saving,that is ok,example i m saving a@gmail.com
but second time when again i try to save a@gmail.com ,it should give error like a@gmail.com is already exist,but it is not giving me any error.
it is not saving record becoz it is duplicate ,so that is ok but why it is not showing error.

**Comment by ajkosh** [comment]
i put more rule on email
this is my code
 public function rules()
    {
        return [
            [['user_id', 'status', 'is_primary','is_delete'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['title'], 'required'],
            [['title'], 'email'],
            [['title'], 'unique'],         
        ];
    }

here required and email validators are working properly but unique is not working,why it is not working

**Comment by qiangxue** [comment]
Please print out the value of `$model->errors`.

**Comment by ajkosh** [comment]
it is not showing any thing array is coming empty

**Comment by qiangxue** [comment]
Please try to debug why `save()` returns false then (it could be that you have `beforeSave()` returning false, etc.)

**Comment by ajkosh** [comment]
no i simply generate from gii and put title as unique,i have no beforesave()

**Comment by mdmunir** [comment]
how about `$form->errorSummary()`; any error message here?

**Comment by ajkosh** [comment]
no errorsummary is not showing anything

**Comment by mdmunir** [comment]
open `firebug`, go to `network` tab, then klik submit. make sure your page is posted.

**Comment by ajkosh** [comment]
yes form is posting.
![screenshot from 2015-02-15 09 59 48](https://cloud.githubusercontent.com/assets/8582472/6202101/7006791c-b4f9-11e4-8e51-72e28660ddbd.png)

**Comment by ajkosh** [comment]
can anyone solve this

**Comment by mdmunir** [comment]
Do it by your self. Do it for us. If its Yii bug, posting what you get here. If its your application bug, save it for your self.
Split your `if` structure
```php
if($model->load(Yii::$app->request->post())){
    Yii::trace('posted');
    if($model->validate()){
        Yii::trace('validated');
        if($model->save(false)){
            Yii::trace('saved');
            return $this->redirect(...);
        }else{
            Yii::trace('not saved');
        }
    }else{
        Yii::trace('not validated');
    }
}else{
    Yii::trace('not posted');
    return $this->render(...)
}
```
Check your model. is any behavior attached. If you want to ask more, go to official Yii forum.

**Comment by ajkosh** [comment]
i found error ,i dont know why this is happening if you guys can help me
when i m using this create function,then unique is working
public function actionCreate()
{
$model = new EmailUser();
       if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->id]);
    } else {
        return $this->render('create', [
            'model' => $model,
        ]);
    }
}
but if i m using this it is not showing error
public function actionCreate()
{
$model = new EmailUser();

    if ($model->load(Yii::$app->request->post())) {
            $model->user_id=Yii::$app->user->identity->id;
             $model->email_otp=Yii::$app->getSecurity()->generateRandomString(8);
          if(  $model->save()){
        return $this->redirect(array('useremail/index'));
}else{
 return $this->redirect(array('useremail/index'));
    } else {
        return $this->render('create', [
            'model' => $model,
        ]);
    }
}

what same thing idid in other models ,there it is working fine so wat is error

**Comment by CthulhuDen** [comment]
@ajkosh you have an extra else block which prevents the correct fork from happening.

**Comment by ajkosh** [comment]
CthulhuDen :-i dont think so it is else problem,i removed else and using simple condition and saving model after that,but it is not working,i did nt get if i m saving model after passing some parameters it is not working if i m load and save model together then it is working

public function actionCreate(){
$model = new EmailUser();
if ($model->load(Yii::$app->request->post())) {
$model->user_id=Yii::$app->user->identity->id;
$model->email_otp=Yii::$app->getSecurity()->generateRandomString(8);
$model->save();
  return $this->redirect(array('useremail/index'));
    } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

**Comment by CthulhuDen** [comment]
@ajkosh  Now you are not checking save results.. try this:

``` php
public function actionCreate(){
    $model = new EmailUser();
    if ($model->load(Yii::$app->request->post())) {
        $model->user_id=Yii::$app->user->identity->id;
        $model->email_otp=Yii::$app->getSecurity()->generateRandomString(8);
        if ($model->save()) {
            return $this->redirect(array('useremail/index'));
        }
    }
    return $this->render('create', [
        'model' => $model,
    ]);
}

**Comment by ajkosh** [comment]
thnku ,i got but i did nt get it was in if condition so if it is not saving then it should go to else and form should stay there if error occurs

**Comment by satyawanshinde** [comment]
Try this

if (!$model->validate()) {
     print_r($model->getErrors());
}

this works for me.
