### ISSUE TITLE
Query builder can't create a query with nested join  

### ISSUE THREAD

**Issue by devivan** [yiisoft/yii2#7290]
At the moment YII allows only to do sub-query, but SQL also allows nested joins.
A common use is a chain of "INNER JOIN" depending on a "LEFT JOIN".

Document reference: 
- (MySql Join syntax)[http://dev.mysql.com/doc/refman/5.0/en/join.html]
- (Nested join optimization)[http://dev.mysql.com/doc/refman/5.0/en/nested-join-optimization.html]

The snippet of documentation showing nested join concept:

> This is a conservative extension if we consider each comma in a list of table_reference items as equivalent to an inner join. For example:
> 
> ```
> SELECT * FROM t1 LEFT JOIN (t2, t3, t4)
>                ON (t2.a=t1.a AND t3.b=t1.b AND t4.c=t1.c)
> ```
> 
> is equivalent to:
> 
> ```
> SELECT * FROM t1 LEFT JOIN (t2 CROSS JOIN t3 CROSS JOIN t4)
>                  ON (t2.a=t1.a AND t3.b=t1.b AND t4.c=t1.c)
> ```

**Comment by qiangxue** [comment]
This is not SQL standard...

**Comment by devivan** [comment]
As far I know, in this form, is SQL standard but still not generable:  
SELECT * FROM t1 
LEFT JOIN (t2 INNER JOIN t3 INNER JOIN t4)
ON (t2.a=t1.a AND t3.b=t1.b AND t4.c=t1.c)

**Comment by cebe** [comment]
the validator you linked complains about syntax error when I enter the SQL above...

**Comment by devivan** [comment]
Sorry, my fault, I mean the first SQL:
```
SELECT * FROM t1 LEFT JOIN (t2 CROSS JOIN t3 CROSS JOIN t4) ON (t2.a=t1.a AND t3.b=t1.b AND t4.c=t1.c)
```

**Comment by cebe** [comment]
What is the difference between your SQL and

```sql
SELECT * FROM t1 LEFT JOIN t2 CROSS JOIN t3 CROSS JOIN t4 ON (t2.a=t1.a AND t3.b=t1.b AND t4.c=t1.c)
```

?

as far as I see they are equivalent...

**Comment by devivan** [comment]
Well, two kind of problem:
for MySql this is a syntax error because **ON** can't follow a **CROSS JOIN**:
```
SELECT * FROM t1 CROSS JOIN t3 CROSS JOIN t4 LEFT JOIN t2 ON (t2.a=t1.a AND t3.b=t1.b AND t4.c=t1.c)
```

This other form (should be the same) has performance issue (always on MySql)
```
SELECT * FROM t1 CROSS JOIN t3 CROSS JOIN t4 LEFT JOIN t2 ON (t2.a=t1.a AND t3.b=t1.b AND t4.c=t1.c)
```

**Comment by dynasource** [comment]
these type of queries look rather rare to me. If you'd ask me, I would focus on simplicity, unless more people vote for integration in the framework.

**Comment by cebe** [comment]
In such cases I suggest to go for plain SQL, it is too complicated to provide this grouping syntax in querybuilder and use cases seem rare to me.
