### ISSUE TITLE
Why it case sensitive?

### ISSUE THREAD

**Issue by uran1980** [yiisoft/yii2#7294]
I want to override yii2 core message console command. When I set **controllerMap** in ```console\config\main.php```config like this:
![01](https://cloud.githubusercontent.com/assets/1616795/6200601/89949470-b488-11e4-9221-d7da470331f5.png)
the override **not work**.

When I set config like this:
![02](https://cloud.githubusercontent.com/assets/1616795/6200604/944ccb8a-b488-11e4-8955-28b773a6ba0d.png)
then override **start working**.

**Is any seriuos reason for this? Why it case sensitive?**

**Comment by samdark** [comment]
Because there's no reason for it to be case insensitive.

**Comment by lynicidn** [comment]
@samdark может это изза тире которое проставляется
?r=-message
