### ISSUE TITLE
Documentation error: unknown method

### ISSUE THREAD

**Issue by Aestu** [yiisoft/yii2#7295]
Method addCondition() referenced in this example:

http://www.yiiframework.com/wiki/621/filter-sort-by-calculated-related-fields-in-gridview-yii-2-0/#hh10

doesn't exist for this class:

Calling unknown method: app\models\ProcedimientoSearch::addCondition()

**Comment by samdark** [comment]
It is a community wiki article, not official documentation. Please report to article author. Thanks!

**Comment by cebe** [comment]
That is a wiki and not part of the official framework docs but user contributed, feel free to fix it or mention it in the comments.

**Comment by alejosv** [comment]
I have the same issue, my question is, if this method not part of the official framework, why is in the documentation this? not is the same method?
[http://www.yiiframework.com/doc-2.0/yii-debug-models-search-base.html#addCondition()-detail](http://www.yiiframework.com/doc-2.0/yii-debug-models-search-base.html#addCondition()-detail)

**Comment by cebe** [comment]
the method is part of `yii\debug\models\search\Base` class which is part of the debug extension.

**Comment by bankchart** [comment]
remove addCondition method, it's ok. i dont know ....why is in the documentation this?
