### ISSUE TITLE
Guide "Auth Clients" - Error in Example Code

### ISSUE THREAD

**Issue by EvilKarter** [yiisoft/yii2#7297]
I've just copied the onAuthSuccess($client) function in the yii2 user guide. 

I have tried to signup with google. Below the example response

    array (size=9)
        'id' => string 'https://www.google.com/accounts/o8/id?id=Example' (length=80)
        'namePerson/first' => string 'Max' (length=3)
        'namePerson/last' => string 'Mustermann' (length=7)
        'pref/language' => string 'de' (length=2)
        'contact/email' => string 'max.mustermann@gmail.com' (length=21)
        'first_name' => string 'Max' (length=3)
        'last_name' => string 'Mustermann' (length=7)
        'email' => string 'max.mustermann@gmail.com' (length=21)
        'language' => string 'de' (length=2)

The copied example code are some mistakes I think.
The code proofs in the "else //signup" if the attribute "$attributes[username]" is set and a few rows below it tries to get "$attributes[login]".

Both entries are not in the google response above. 

And something is wrong I think. The if condition in the else //signup part 

    if (isset($attributes['email']) && isset($attributes['username']) && User::find()->where(['email' => $attributes['email']])->exists()) {

The third condition should be 

     && !User::find()->where(['email' => $attributes['email']])->exists()) {

And the else blog is missing. So if the User does exist try to login or throw exception or do somthing like this.

**Comment by klimov-paul** [comment]
This is an example, it can not work in all cases.
