### ISSUE TITLE
Error: Sphinx find json and ActiveDataProvider

### ISSUE THREAD

**Issue by diaskooo** [yiisoft/yii2#7298]
Sphinx json find

```
SELECT *, ANY(x.model='LG' FOR x IN catalogs.model) as models FROM index WHERE matchy = 1
```

```php
$model = Catalog::find()->select(['*', new Expression("ANY( x.model = 'LG' FOR x IN catalogs.model) AS models")])->where('models = 1');

$provider = new ActiveDataProvider([
      'query' => $model,
      'pagination' => [ 'pageSize' => 30 ]
]);
$data = $provider->getModels();
```

causes an error:
```
Database Exception – yii\db\Exception

SQLSTATE[42000]: Syntax error or access violation: 1064 index idx_db: no such filter attribute 'models' 
The SQL being executed was: SELECT COUNT(*) FROM `idx_db` WHERE models = 1
```

**Comment by klimov-paul** [comment]
Try to type 'matchy' instead of 'models' at `where()` call:
```
->where('matchy= 1');
```

**Comment by diaskooo** [comment]
match is not suitable for functional.
you need to use search sphinx on zhson
for example:
```sql
SELECT *, 
ANY(x.model='LG' and x.screen='1280x800' and x.lte=1 FOR x IN catalogs.model) as models 
FROM index WHERE matchy = 1 
```

**Comment by klimov-paul** [comment]
I don't understand your question.
You have a clear error message telling:
"no such filter attribute 'models' 
The SQL being executed was: SELECT COUNT(*) FROM `idx_db` WHERE <b>models</b> = 1"
What does this do with json?

**Comment by diaskooo** [comment]
>ALL()
ALL(cond FOR var IN json.array) function was introduced in 2.2.1-beta. It applies to JSON arrays and returns 1 if condition is true for all elements in array and 0 otherwise. 'cond' is a general expression which additionally can use 'var' as current value of an array element within itself.
SELECT ALL(x>3 AND x<7 FOR x IN j.intarray) FROM test;
ANY()
ANY(cond FOR var IN json.array) function was introduced in 2.2.1-beta. It works similar to ALL() except for it returns 1 if condition is true for any element in array.

```sql
SELECT *, ANY(x.model='LG' FOR x IN catalogs.model) as models FROM idx_db WHERE models = 1
```

**Comment by klimov-paul** [comment]
It seems you don't pay attention.
Look to your query carefully:
```
SELECT *, ANY(x.model='LG' FOR x IN catalogs.model) as models FROM idx_db WHERE models = 1
```
Here you paste `WHERE models = 1`. Do you know, which conditions can be placed under 'WHERE' statement? You should either use a field here like `WHERE my_field = 1` or use 'HAVING' statement: `HAVING models = 1`

**Comment by diaskooo** [comment]
The query is executed as planned
>except for it returns 1 if condition is true for any element in array
```sql
SELECT *, ANY(x.model='LG' FOR x IN catalogs.model) as models FROM idx_db WHERE models = 1 
```

The error occurs when trying to perform ActiveDataProvider
vendor/yiisoft/yii2/db/Query.php
```php
public function count($q = '*', $db = null) {
    return $this->queryScalar("COUNT($q)", $db);
}
```

**Comment by klimov-paul** [comment]
You should calculate total query result count manually by abother query and set `DataProvider::totalCount` explicitely.
