### ISSUE TITLE
Fix _identity cookies for MongoDB

### ISSUE THREAD

**Issue by Dotrox** [yiisoft/yii2#7300]
When using MongoDB it stores user id in ```_identity``` cookie in this format: ```{"$id":"54dd687b378d8f4b2a8b4571"}```
This causes many errors while authorization by cookies.

@im-kulikov proposed use ```MongoId()``` in function ```findIdentity``` (https://github.com/yiisoft/yii2/issues/6506#issuecomment-73411038),  but it causes error after session is expired.

My solution is to rewrite function ```getPrimaryKey``` to store id in clean form when using MongoDB:

```php
public function getPrimaryKey($asArray = false){
        $keys = $this->primaryKey();
        if (count($keys) === 1 && !$asArray) {
            if($keys[0] == '_id'){
                return isset($this->attributes[$keys[0]]) ? $this->attributes[$keys[0]]->{'$id'} : null;
            } else {
                return isset($this->attributes[$keys[0]]) ? $this->attributes[$keys[0]] : null;
            }            
        } else {
            $values = [];
            foreach ($keys as $name) {
                if($name == '_id'){
                    $values[$name] = isset($this->attributes[$name]) ? $this->attributes[$name]->{'$id'} : null;
                } else {
                    $values[$name] = isset($this->attributes[$name]) ? $this->attributes[$name] : null;
                }
            }

            return $values;
        }
    }
```
I am using this in my ```User``` model, so I use ```$this->attributes``` instead of ```$this->_attributes``` as it is in ```BaseActiveRecord``` class.

And we still need to use ```'_id'``` instead of ```'id'``` in function ```findIdentity``` as name of id parameter as proposed @im-kulikov, because in this format it uses MongoDB.

**Comment by klimov-paul** [comment]
See #2129
