### ISSUE TITLE
i18n relativeTime format problem with icu <=4.8

### ISSUE THREAD

**Issue by sidtj** [yiisoft/yii2#7301]
Hi,

I have this in my gridview:
```php
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ...
            [
                'attribute' => 'created_at',
                // 'value' => 'created_at:relativeTime' does not work too so I tried this:
                'value' => function ($data) {
                    return Yii::$app->formatter->asRelativeTime($data->created_at);
                },
                'contentOptions' => ['style' => 'width:12%'],
            ],
            ...
        ],
    ]); ?>
```

It works ok locally, but on server, it does not work properly. Instead of to see something like '1 hour ago', i see exactly this: `{delta, plural, =1{há 1 hora} other{há # horas}}` (my language is pt-BR).

I have already checked the requirements.php (mysite.com/requirements.php) and `intl` is installed and working. I also tryed to use `Yii::$app->formatter->asRelativeTime($value)` but with the same problematic result.

Is this some type of specific-server-or-server-configuration-bug? If isn't, where should I look for the problem?

Thank you so much!
And guys, this framework is really awesome. I use it since 2010 in my projects! Congratulations!

**Comment by tecnologiaterabyte** [comment]
Check locales configuring i18n in your hosting, server or computer localhost.

**Comment by sidtj** [comment]
@tecnologiaterabyte, when locale is not set yii uses language to set that config: `You can configure the locale property of the formatter for this. If not configured, the application language is used as the locale.` (from the guide).

So, is there another locale config I could check? Could you say me what?

Thank you.

**Comment by tecnologiaterabyte** [comment]
This code checks the codes of languages ​​supported by your server and verifies that the language code is correct.

    <?php
        function list_system_locales(){
            ob_start();
            system('locale -a');
            $str = ob_get_contents();
            ob_end_clean();
            return split("\\n", trim($str));
        }
        $a=list_system_locales();
        var_dump(a$);
    ?>

**Comment by sidtj** [comment]
I ran `locale -a` on server cli and this is what got:
https://gist.github.com/sidtj/a06a559ce99266999872

It seems that everything is ok concerning to pt_BR locale.

**Comment by lynicidn** [comment]
run and show
`dpkg -l |grep intl`

**Comment by lynicidn** [comment]
also 
`locale` and `locale -ck LC_MESSAGES`

**Comment by lynicidn** [comment]
also u must try reconfigure it `dpkg-reconfigure locales`

**Comment by sidtj** [comment]
I dont have dpkg in my shared host.

$ locale:
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

$ locale -ck LC_MESSAGES
LC_MESSAGES
yesexpr="^[yY]"
noexpr="^[nN]"
yesstr=""
nostr=""
messages-codeset="ANSI_X3.4-1968"

**Comment by lynicidn** [comment]
need run `sudo dpkg -l |grep intl`

**Comment by lynicidn** [comment]
>messages-codeset="ANSI_X3.4-1968"
need utf-8

try reconfigure it

**Comment by lynicidn** [comment]
`sudo apt-get install dpkg`

**Comment by sidtj** [comment]
It is jailshell, i dont have sudo, nor apt-get, nor dpkg. Sorry.

**Comment by sidtj** [comment]
BUT... intl is installed as I said in first comment. I saw in requirements.php

**Comment by lynicidn** [comment]
may be it help for u http://lh.2xlibre.net/locale/pt_BR/

**Comment by lynicidn** [comment]
or it http://perlgeek.de/en/article/set-up-a-clean-utf8-environment

**Comment by tecnologiaterabyte** [comment]
Seems your settings all right, try putting in the configuration of the formatter,

        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'locale' => 'pt-BR', // or 'pt_BR'
            'defaultTimeZone' => 'America/Sao_Paulo'
        ],

**Comment by sidtj** [comment]
I tryed set the formatter configs and use Yii::$app->formatter->asRelativeTime('2015-02-22 10:30:00') one more time, but it results the same problem I have pointed in the first message, and worse, results in english, not pt_BR.

**Comment by cebe** [comment]
@sidtj can you tell me which version of intl and ICU you are using?

Just run the following PHP script and give me the output:

```php
<?php
echo "PHP: " . PHP_VERSION . "\n";
echo "ICU: " . INTL_ICU_VERSION . "\n";
```

@lynicidn all the stuff regarding locale and dpkg should not be necessary as intl does not depend on these.

**Comment by lynicidn** [comment]
@cebe i think problem with locales, need set utf-8

**Comment by lynicidn** [comment]
in other way - problen in server config

**Comment by sidtj** [comment]
@cebe:
PHP: 5.4.37
ICU: 4.2.1

**Comment by cebe** [comment]
The syntax used in the translation message for relative time is only supported by ICU version 4.8 or higher. In general we recommend using icu 4.8 or higher to be used with yii. We may consider adding a fallback but that has not high priority...

**Comment by sidtj** [comment]
Thanks for your explanations. I saw it right now in http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html. BTW, I am using standard dates for a while. No problem about this.

What about implement ICU version checking on requirements.php just for warning? It seems that would be very simple.

**Comment by cebe** [comment]
can you do it and send a pull request?

**Comment by sidtj** [comment]
Sure, I will.

**Comment by sidtj** [comment]
PR: https://github.com/yiisoft/yii2/pull/7407

**Comment by githubjeka** [comment]
I have a problem with plural in `ICU v.52.1` for `ru`. It's not working. 
http://yiiframework.ru/forum/viewtopic.php?f=19&t=22495

Had to use

```php
<?= MessageFormatter::formatMessage("be", // or "uk", no "ru" ... ?>
```

**Comment by cebe** [comment]
@githubjeka this does not look related, please open a new issue.

**Comment by cebe** [comment]
@githubjeka added more tests: db37d03e32f9642998431e3c2a0e845d9cc44a71 it is unlikely a bug. but rather something with your config.

**Comment by yujin1st** [comment]
@cebe, same issue as @githubjeka... tried different combination without success.

**Comment by githubjeka** [comment]
@yujin1st try https://github.com/yiisoft/yii2/issues/7430

**Comment by yujin1st** [comment]
@githubjeka, thanks. didn't see that issue before.
