### ISSUE TITLE
non-existing inline validator causes apache server crash

### ISSUE THREAD

**Issue by alexander-suter** [yiisoft/yii2#7302]
Hey guys.

I have definied following rule:

```php
['date_url_wikipedia_de_date', 'save']
```
I thought save is the correct name for the "SaveValidator". But you and I know - i should it call "safe".
So it was treated as an Inline-save validator. But i didn't created one.
The result was, that apache server crashed.

I would preferer, if i define a rule which goes to an non-existing inline validator, to get an exception.

What do you think?

**Comment by qiangxue** [comment]
Well, `save()` is an existing method and it will trigger validation again, which results in indefinite recursion. I don't think we will do anything to this because it's very uncommon and the cost for the complete fix is non-trivial.
