### ISSUE TITLE
Feature request: Enhancement on the Yii configuration

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#7303]
This is mostly meant for the 2.1 release since it will change a bit of the configuration syntax some classes might get a benefit from a rewrite. Yet it will be backwards compatible for those that doesn't get rewritten.

1) Merge keys and values when configuring arrays.
https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L518

Change it for something like

``` php
if (is_array($value) && isset($property->$name) {
     $property->$name = ArrayHelper::merge($property->$name, $value);
} else {
    $property->$name = $value;
}
```

Lets take for example `yii\widgets\ActiveForm` it contains `fieldClass` and `fieldConfig` yes they are very self explanatory but it would be simplier and more easy to extend if they only contained an array to be passed for the `Yii::createObject` method.

```
$field = ['class' => 'yii\widget\ActiveField'];
```

Its simplier to have just one attribute to generate the field object than to have two attributes right now.

It will also simplify all the `$objectOptions`-like properties some classes have like `ActiveField::inputOptions`, `ActiveField::errorOptions`, `ActiveField::labelOptions`, `ActiveField::hintOptions`

2) Being able to configure the element inside an array using a shortcut like the ones ussed in attributes.

``` php

'fieldConfig.options.class' => 'field-form'

// equivalent of
'fieldConfig' => ['options' => ['class' => 'field-form']]

// or in case you also liked the first suggestion the shortcut would be
'field.options.class' => 'field->form'
```

**Comment by dynasource** [comment]
Createobject is one of the most used functions during a run. Wouldnt merge go at cost of performance?

**Comment by Faryshta** [comment]
@dynasource thats a good point. Right now cases like the `fieldClass` and `fieldConfig` example are merged before calling `Yii::createObject` but the performance cost is negible.

Maybe it would be good to check the unit testing after the change and see how different it gets.

**Comment by samdark** [comment]
Performance test is definitely necessary in this case.

**Comment by dynasource** [comment]
I do like this kind of configuration

**Comment by Faryshta** [comment]
Is there a method to know if a property in a `yii\base\Object` is readable?

I just noticed if there is a write-only property then this would throw an exception while configuring the object.

```php
Yii::createObject(Security::className(). ['keys' => ['asdf', 'qwer', 'zxcv']]);
```

If `Security::$keys` is protected or private and there is a public method `setKeys` then the `createObject` won't throw any error as it is right now. But if we try to merge the current value of `keys` with a new one an exception will be thrown.

**Comment by dynasource** [comment]
@Faryshta, Ive looked in to your 2 suggestions.

Firstly, I have looked into my xdebug report in which Ive tested my whole application.
Yii::configure is in the 10 called Yii functions (and in the top 20 of all functions including PHP). If something like a merge is in there and it is called most of the time, this will be a problem.

Secondly, I like the way how deep arrays can be tackeled. This is very useful for several large config arrays I am using right now. 
```
$process =[
  [
     'phase'=>[
            'form'=>[
                  'elements'=>[
                       'User'=>[
                              'name'=>'test'
                        ]
                  ]
            ]
      ]
  ]
]
```

will become:
```
'process.phase.form.elements.user.name'=>'test'
```

The dots in the attributes can be checked optimally, but it does mean this dot has to be reserved for this scenario and cannot exist in configuration arrays anymore if not implemented otherwise.

**Comment by Faryshta** [comment]
I agree with the dots issue, specially when dealing with attributes.

A recursive solution I can think is that `Yii::createObject` passes the raw name with dots included, this will trigger the magic `__set` method like this `Object::__set('process.phase.form.elements.user.name', 'test')`

then the object will decide what to do with it. By default it will turn it to an array:

`$process['phase.form.elements.user.name'] = 'test'`

then it will be responsibility of the `process` object or configuration to deal with it.

**Comment by dynasource** [comment]
I am not a great lover of magic methods, they're slow and magic. 
I should be implemented in the class in which configurations are parsed. Even better will be a custom Configurator class in which this logic is parsed

**Comment by githubjeka** [comment]
Once again

By default
```php
\yii\bootstrap\ActiveForm::options = ['role' => 'form'];
```
To save default value user can use merge
```php
    $form = \yii\bootstrap\ActiveForm::begin();
    $form->options = ArrayHelper::merge($form->options, ['data-pjax' => 1,  'autocomplete' =>"off" ]);
```

Result will be
```html
<form role="form" autocomplete="off" data-pjax=>"1">
```

Now user want add autocomplete to all forms  by  DI container in config
```php
yii\bootstrap\ActiveForm::class => [ 'options' => ['autocomplete' => 'off']],
```
and 
```php
    $form = \yii\bootstrap\ActiveForm::begin();
    $form->options = ArrayHelper::merge($form->options, ['data-pjax' => 1]);
```

Result will be 
```html
<form autocomplete="off" data-pjax=>"1">
```

**Problem: Default value is missed**

To fix it @Faryshta propose use `ArrayHelper::merge` in metods `init()` of Widgets

IMHO `ArrayHelper::merge` not compleate fix to this issue

If I use config all ` yii\widgets\ActiveForm` , not only `yii\bootsrap\ActiveForm`
```php
   yii\widgets\ActiveForm::class => [ 'options' => ['autocomplete' => 'off']],
```
and 
```php
    $form = \yii\bootstrap\ActiveForm::begin();
    $form->options = ArrayHelper::merge($form->options, ['data-pjax' => 1]);
```

Result will be 
```html
<form role="form" data-pjax=>"1">
```

**Problem: configuration by DI does not include inheritance**

**Comment by samdark** [comment]
Closing since DI container changed it slightly.
