### ISSUE TITLE
Passing by reference list of attributes to be validated to beforeValidate function

### ISSUE THREAD

**Issue by iamwebdesigner** [yiisoft/yii2#7304]
I am not sure whether this feature was requested before or not, so I have decided to create this issue. I am not sure that is would be logically correct, but I think it can be very comfortable for developers. So I want to suggest to pass the list of attributes that are to be validated, to `beforeValidate` function, so it was easier to skip attributes when taking the list by reference (looping foreach and checking values for some statements and unset attribute if not necessary for validating). I know all this actions are possible to manage with `scenarios` function, but we do not have list of attributes to be validated, inside that function.

**Comment by samdark** [comment]
What's your use case for it? Why not using scenarios?

**Comment by iamwebdesigner** [comment]
I have tens of attributes in my table and before validation, for example I want to do like this:  
```
    public function beforeValidate(&$attributes)
    {
        foreach($attributes as $attribute)
        {
                if($attribute == 'some_attr' && $attributes[$attribute] == 'some_exception_value')
                    unset($attributes['attribute_c']);
               // other actions are here
        return true;
    }
```
However I dont want to create `n` different scenarios for `n` cases. Also I want to have list of attributes for validation on hands.

**Comment by samdark** [comment]
You can probably use validation filter to achieve it.

**Comment by qiangxue** [comment]
Your example problem can be solved using conditional validation: http://www.yiiframework.com/doc-2.0/guide-input-validation.html#conditional-validation

We will not support the proposed usage because it won't work for the client-side validation.
