### ISSUE TITLE
yii console error when env=Production.

### ISSUE THREAD

**Issue by maxmirazh33** [yiisoft/yii2#7306]
Advanced app template.
Why in console/config/main.php set bootstrap gii?
`'bootstrap' => ['log', 'gii'],`

If our environment=Production then gii not installed and when i try `php yii migrate`, i get `Error: Unknown bootstrapping component ID: gii`.
May be it need set in console/config/main-local.php?

**Comment by fernandezekiel** [comment]
Gii is not supposed to be enabled on production

**Comment by maxmirazh33** [comment]
@fernandezekiel of course, but gii always added in bootstrap.

**Comment by fernandezekiel** [comment]
you answered your question already, just set it on your console's main-local.php

**Comment by maxmirazh33** [comment]
@fernandezekiel, I know solution, I don't understand why it set in main config in official app template.

**Comment by samdark** [comment]
I guess it's a bug. Need to verify it. @maxmirazh33 would be great if you can submit a pull request fixing it.
