### ISSUE TITLE
File upload behaves strange when updating a record

### ISSUE THREAD

**Issue by iamwebdesigner** [yiisoft/yii2#7308]
I am using file upload input with model and when I try to update a record without uploading a file, values respective to file inputs in the record are lost. I managed to solve this problem, after I made a little change in framework code.  
File: framework/helpers/BaseHtml.php  
Changed (in line 1212):  
**from:**  
```
    public static function activeFileInput($model, $attribute, $options = [])
    {
        // add a hidden field so that if a model only has a file field, we can
        // still use isset($_POST[$modelClass]) to detect if the input is submitted
        return static::activeHiddenInput($model, $attribute, ['id' => null, 'value' => ''])
            . static::activeInput('file', $model, $attribute, $options);
    }
```
**to:**
```
    public static function activeFileInput($model, $attribute, $options = [])
    {
        // add a hidden field so that if a model only has a file field, we can
        // still use isset($_POST[$modelClass]) to detect if the input is submitted
        $options['value'] = '';
        return static::activeHiddenInput($model, $attribute, ['id' => null])
            . static::activeInput('file', $model, $attribute, $options);
    }
```
I guess, if there is another solution without changing a framework source, it is necessary to include it in the documentation.

**Comment by iamwebdesigner** [comment]
Any suggestions on this issue?

**Comment by samdark** [comment]
Please show your controller code.

**Comment by iamwebdesigner** [comment]
**Controller**  
```php			
$fields = $model->fileAttributes();
$model->load(Yii::$app->request->post());
if($fields!=[])
{
	foreach($fields as $field)
	{
		if($file = UploadedFile::getInstance($model,$field))
			$model->$field = $file;
	}
	$model->on($model::EVENT_AFTER_VALIDATE, function (Event $e) {
		foreach($e->data as $field)
			if($e->sender->$field)
				$e->sender->$field->saveAs(Yii::getAlias('@root/uploads/') . time() . '_' . $field . '.' . strtolower($e->sender->$field->extension));
	}, $fields);
}

if($model->save())
{
	Yii::$app->session->setFlash('success','Successfully');
	$this->redirect(['admin/view']);
}
```
**View**  
```php
$form = ActiveForm::begin([
		'options' => ['enctype' => 'multipart/form-data'],
]);
echo $form->field($model,'catalogue_en')->fileInput();
echo $form->field($model,'catalogue_ru')->fileInput();
```

**Comment by samdark** [comment]
It's doing exactly what's requested:

```php
if($file = UploadedFile::getInstance($model,$field))
            $model->$field = $file;
```

You're overwriting model field with either `UploadedFile` instance if file was uploaded or `null` if it's not. When model is saved the field is saved as well. It's not a framework issue.

**Comment by iamwebdesigner** [comment]
However when I tried to dump model after load the file attributes were empty string. Also if I don't upload a file `UploadedFile::getInstance($model,$field)` returns null and condition fails, so assigning of `$file` variable to attribute fails. I want the attribute to be overidden when I upload a file, but if I don't upload a file I want previous values stay the same.

**Comment by samdark** [comment]
Overall it's a bad idea to assign UploadedFile instance to AR field before it's validated.

**Comment by iamwebdesigner** [comment]
Followed the guide which says:  
```php
if (Yii::$app->request->isPost) {
  $model->file = UploadedFile::getInstance($model, 'file');
  if ($model->validate()) {
    $model->file->saveAs('uploads/' . $model->file->baseName . '.' . $model->file->extension);
  }
}
```
Assigning comes before validation.

**Comment by samdark** [comment]
Yes but if you look at the model in the guide, `file` is not a field bound to database but a class property.
