### ISSUE TITLE
i18n Time format problem.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#7311]
Hi, I have a problem with the format of the time is not displayed correctly.

My Config:

PHP: 5.4.37. 
ICU: 50.1.2.
timezonedb:
    - Alternative Timezone Database: enable.
    - Timezone Database Version: 2015.1

My Code example:

    Yii::$app->formatter->locale = 'es-ES'; 
    Yii::$app->timeZone = 'America/Caracas';
    echo (Yii::$app->formatter->asTime('12:41:00', 'short'));
    // show 08:11
    echo (Yii::$app->formatter->asTime('30-11-2014 12:41:00'));
    // Show 08:11
    echo (Yii::$app->formatter->asTime(1412599260));
    // show 08:11

Thks,

**Comment by cebe** [comment]
strange... can you try the same thing with 13:41:00?

**Comment by tecnologiaterabyte** [comment]
hi, try 13:41:00 show 09:11.

Thks,

**Comment by cebe** [comment]
ahh, so America/Caracas is -4h of UTC, right? What's the problem then?

**Comment by cebe** [comment]
Input timezone is UTC, check the guide: http://www.yiiframework.com/doc-2.0/guide-output-formatter.html#time-zones

**Comment by tecnologiaterabyte** [comment]
(UTC-04:30) Caracas.

**Comment by tecnologiaterabyte** [comment]
Solved with defaulTimezone.

Thks,
