### ISSUE TITLE
i18n Formatter Problem Locale 

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#7315]
My Config:

PHP: 5.4.37. 
ICU: 50.1.2.
timezonedb:
- Alternative Timezone Database: enable.
- Timezone Database Version: 2015.1

Config Formatter:
    
    'components' => [
        'formatter' => [
            'locale' => 'es-ES',
            'dateFormat' => 'dd/MM/yyyy',
            'timeFormat' => 'short',
            'defaultTimeZone' => 'America/Caracas'
        ],
    ]

Example Code:

    $fecha = date('l', strtotime('16-02-2015'));
    
    // Show string(6) "Monday"
    
    // Should Show string(5) "Lunes"

Thks,

**Comment by lynicidn** [comment]
try: `es_ES`

**Comment by tecnologiaterabyte** [comment]
No working 'es', 'es-Es', 'es_ES', 'es_ES.utf8', I've tried every combination that accepts my server and nothing seems a bug.

**Comment by lynicidn** [comment]
```bash
# dpkg-reconfigure locales
```

**Comment by tecnologiaterabyte** [comment]
thanks for your answer, use centos 6.6:

    locale -a

    Show:

    es_ES
    es_ES@euro 
    es_ES.iso88591
    es_ES.iso885915@euro
    es_ES.utf8

    sudo nano /etc/sysconfig/i18n

    Config:

    LANG="es_ES

    source /etc/sysconfig/i18n

    echo $LANG

    Show:

    es_ES

I think this perfect settings,

Thks,

**Comment by lynicidn** [comment]
ahhh u use `date('l', strtotime('16-02-2015'));`
try: `$formatter->asDate`

**Comment by tecnologiaterabyte** [comment]
excuse my ignorance, can you explain how to use Yii :: $ app-> formatter-> asDate to obterner day of the week, in the guide does not appear.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L437
see `format` param

**Comment by tecnologiaterabyte** [comment]
Solved:

    Yii::$app->formatter->asDate(strtotime('2015-02-16'), 'php:l');

It should better document the formatter with several examples.

Thks,

**Comment by lynicidn** [comment]
u see it https://github.com/yiisoft/yii2/blob/master/docs/guide/output-formatter.md ? )))
