### ISSUE TITLE
hasOne Relations with empty string relation ids

### ISSUE THREAD

**Issue by wilwade** [yiisoft/yii2#7321]
Might be a touch larger than this, but this is the place I can easily reproduce.

If I have a pair of tables say: 

alphabet
id, name

letter
id, name, alphabet_id

And alphabet_id can be null.

If in the Letter model alphabet_id = "" instead of null (say If I load a form into the Letter model with alphabet_id in the post data set to "") And then try to call the Letter->getAlphabet() relation, it will throw a database exception for PostgreSQL (PostgreSQL only?).

This is because it sets the query to be SELECT * FROM alphabet where "id" = ''; This fails with SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "".

The issue appears to start on this line:
https://github.com/yiisoft/yii2/blob/2.1/framework/db/ActiveRelationTrait.php#L458

It checks if it is !== null, but in this case the empty string is just as invalid.

Current work arounds are to refresh the model after loading, or checking for empty strings on the foreign keys and replacing them with null.

**Comment by cebe** [comment]
if you fill the value from a form you should add a default value validator that sets the value to null if it is empty. The check has to appear in that place instead of ActiveRelationTrait because empty string is just wrong for an ID.
