### ISSUE TITLE
Proposal Template: local files to folder local

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#7322]
Id like to propose a subfolder for local environment files:
- /config/main-local to /config/local/main
- /config/params-local to /config/local/params

Why?
Within the last year, I guess I have had to click the correct file for more that 5000 times, which is in my opinion not optimal with these two files. Why?:
- names start equal
- main-local is grayed out because of its git ignore, making it harder to read.

Therefore I would propose to put the local files in their own folder. They aren't used that often, are grouped together on type and I dont get bothered by their git color. 

Besides, Id rather save my concentration for more important stuff then picking the right files.

**Comment by qiangxue** [comment]
Well, then you may get confused when working with `/config/main.php` and `/config/local/main.php` because they have the same name.

**Comment by dynasource** [comment]
they are hidden in their own folder so I am not disturbed by them anymore. It is not that my eyes are triggered by a folder name "local"

when talking about having these files open in the IDE, I am not so afraid. The local files are not used that often.

**Comment by qiangxue** [comment]
If you are accustomed to using keyboard shortcuts to open files instead of using mouse to choose which file to open, you won't have this problem. But anyway, this is personal preference, and I don't see there will be a unanimous solution. We will keep the current solution as is. You can adjust the file location yourself, if you prefer.

**Comment by dynasource** [comment]
I will, thanks
