### ISSUE TITLE
File Exists but getting reflection

### ISSUE THREAD

**Issue by rajanishtimes** [yiisoft/yii2#7325]
Hi 

My file exists in 

api\actions\entity\affiliate\SearchAction.php 

i am getting

ReflectionException
Class api\actions\entity\affiliate\SearchAction does not exist

    1. in /var/www/html/whatshot/vendor/yiisoft/yii2/di/Container.php at line 411

**Comment by lynicidn** [comment]
u should set alias for `api`

**Comment by rajanishtimes** [comment]
where i should create aliias

**Comment by lynicidn** [comment]
find `bootstrap.php` in config folders

**Comment by rajanishtimes** [comment]
aliias for api is already created

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-autoloading.md

**Comment by a-komarev** [comment]
Check class `SearchAction.php` namespace?

**Comment by rajanishtimes** [comment]
thanks issue resolved ,This issue is  due if we are creating any action other than index,view,create,update then existing folder name must be as it is
