### ISSUE TITLE
$model->load doesnt work anymore in 2.0.2

### ISSUE THREAD

**Issue by tracid** [yiisoft/yii2#7327]
Hi,

since upgrading to 2.0.2 i have a strange behavior:
$model->load doesnt work anymore and $model->errors is just empty.
In 2.0.1 everything works fine... (i checked the Changelog from 2.0.2 January 11, 2015 but i found nothing useful).

I have no clue whats going on...

Heres the Action:

    public function actionLogin()
    {
        $model = new LoginForm;

        if ($model->load(Yii::$app->request->post(), 'Login') && $model->login()) {
            return ['url' =>  '/index'];
        } else {
            return ['error' => $model->errors];
        }
    }

The Model LoginForm is from the newest Advanced Package...

Thanks :)

**Comment by Borales** [comment]
@tracid you should recheck the given app code here https://github.com/yiisoft/yii2/blob/master/apps/advanced/frontend/controllers/SiteController.php#L80

Try this:

```php
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
```

**Comment by tracid** [comment]
Hi,

oh haha, gues what, my "question" was the solution ;)

The original Problem was:

public function actionLogin()
{
    $model = new LoginForm;

    if ($model->load(Yii::$app->request->post('Login'), false) && $model->login()) {
        return ['url' =>  '/index'];
    } else {
        return ['error' => $model->errors];
    }
}



I took a look at jii2/Model.php:

public function load($data, $formName = null)
    {
        $scope = $formName === null ? $this->formName() : $formName;
        if ($scope === '' && !empty($data)) {
            $this->setAttributes($data);
            return true;
        } elseif (isset($data[$scope])) {
            $this->setAttributes($data[$scope]);
            return true;
        } else {
            return false;
        }
    }

It changed...

I will use $model->setAttributes() instead...


But thank you very much!

**Comment by miradnan** [comment]
I'm still facing issues with $model->load() method. It works fine for the required fields, but not for other fields which are not listed in rules method.

```php
if ($model->load(Yii::$app->request->post()) && $model->update()) {
        Yii::$app->session->setFlash('success', 'Updated');
        return $this->goBack();
}
```

**Comment by SilverFire** [comment]
Please, create a separated issue for your problem with detailed description and exact steps to reproduce it.
