### ISSUE TITLE
How to in yii-advanced application RBAC table auth_assignment not define User_id it define user type

### ISSUE THREAD

**Issue by rahulsinh** [yiisoft/yii2#7329]
@samdark Hii i want to give permission to create,update and delete according to user type
for example user type is customer so there are many customer are there so i am not given permission according User_id if user type is customer then he can not create ,update or delete so auth_assignment table define type and use type for permisssion.

**Comment by samdark** [comment]
There's no need to store type in user table. Your type is a `Role` in terms of RBAC and permissions are `Permission`. Hierarchy would be the following:

```
Customer
  Create
  Update
  Delete
Admin
  Customer
  ViewStats
```

Then you're just assigning either `Customer` or `Admin` to your users [using RBAC API](http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#building-authorization-data).

**Comment by rahulsinh** [comment]
@samdark  how to use yii2-user extension in yii advanced application because there are already signup and login property how to replace with yii2-user extension.

**Comment by samdark** [comment]
@rahulsinh I don't know. I've never used yii2-user.

**Comment by rahulsinh** [comment]
@samdark thanks for Your response
