### ISSUE TITLE
urlManager not working when add in common\config\main.php

### ISSUE THREAD

**Issue by phunsanit** [yiisoft/yii2#7330]
i add 
	'components' => [
...
		'urlManager' => [
			'class' => 'yii\web\UrlManager',
			'showScriptName' => false,
			'enablePrettyUrl' => true,
		],
...
	],
to common\config\main.php but can't used PrettyUrl in backend it return first page all time.

but it work when add to backend\config\main.php

**Comment by samdark** [comment]
Check your webserver config.
