### ISSUE TITLE
Proposal for Model, setter method for attributes

### ISSUE THREAD

**Issue by adamasantares** [yiisoft/yii2#7331]
Hi all.

I've create and tested this method for class /vendor/yiisoft/yii2/base/Model.php

```php
    /**
     * Sets the attribute value by calling it as setter method
     * By default the attributes work as this:  $model->attributeName = value; $mode->save();
     * But this overload allow to use like this:  $model->setAttributeName(value)->setAnotherAttr(value2)->save();
     * @param string $name
     * @param array $attributes
     * @return mixed
     */
    public function __call($name, $attributes)
    {
        if (!empty($attributes) && (is_numeric($attributes[0]) || is_string($attributes[0]))) {
            foreach ($this->attributes() as $attr) {
                $setter = 'set' . ucfirst($attr);
                if ($name == $setter) {
                    $this->$attr = $attributes[0];
                    return $this;
                }
            }
        }
        // default overload from Component class
        return parent::__call($name, $attributes);
    }
```

I think this method is good solution, with it you can set values for different attributes in one line.
But I really  have not time for make a PR.

**Comment by samdark** [comment]
What's the benefit exactly?

**Comment by adamasantares** [comment]
Now I must write:

```php
$user->email = 'aa@bb.cc';
$user->phone = '8888888888';
$user->save();
```

totally 3 time uses of $user.

With this method I can write

```php
$user->setEmail('aa@bb.cc')->setPhone('8888888888')->save();
```

I'd like that style more.

It can be without prefix 'set', just ```$user->email('value');``` but in this case may be problem with methods which has same names.

**Comment by klimov-paul** [comment]
Whay don't simply use `setAttributes()` then?

**Comment by adamasantares** [comment]
@klimov-paul good question... :)
Try to compare

```php
$model->setAttributes(['email' => 'aa@bb.cc', 'phone' => '8888888888']);
$model->save();
```

or

```php
$user->setEmail('aa@bb.cc')->setPhone('8888888888')->save();
```

well, last style more compact and nothing more...

**Comment by lynicidn** [comment]
solve:
```php
function setPhone($phone)
{
$this->setAttribute('phone', $phone);
return $this;
}
```

**Comment by dynasource** [comment]
I like the idea of saving a value in 1 line, but I dont think you have thought about the huge performance loss. 

__call is one of the most called functions in Yii2. If its not optimal, it shouldnt be altered

**Comment by samdark** [comment]
I don't think we want it in the framework:

1. Performance issue.
2. More ways to do the same thing isn't good.

**Comment by samdark** [comment]
Leaving it open for discussion.

**Comment by slavcodev** [comment]
+1 I like the idea

**Comment by qiangxue** [comment]
I don't think we should spend time discussing about this further for the following reasons:

1. No obvious benefit other than a slight (and still arguable) syntax sugar.
2. Similar proposals for other classes will naturally follow, which puts `__call()` implementation everywhere.

**Comment by lynicidn** [comment]
it's bad idea. Very many magic. U should create it if need for u. I use setters for other.

**Comment by lynicidn** [comment]
p.s. и это еще не берем в расчет ide что помимо объявления аттрибутов надо еще и методы вверху класса описывать, у нас каментарии будут на тыщи строк

**Comment by n1k88** [comment]
-1 ^^
it's not necessary

**Comment by adamasantares** [comment]
@qiangxue I think you are right...

**Comment by adamasantares** [comment]
@lynicidn тема уже закрыта, но я не совсем понял насчет комментариев для методов.
(https://github.com/yiisoft/yii2/issues/7331#issuecomment-74870505)
Каким таким методам?

**Comment by lynicidn** [comment]
@adamasantares  phpdoc надо описывать, если методов не существует, а юзаются они через __call http://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.method.pkg.html

**Comment by adamasantares** [comment]
@lynicidn Понятно, но разве это не справедливо и для свойств? Ведь сейчас например IDE мне не подсказывает по свойствам модели (сгенерированной через GII). Честно сказать это действительно неудобно, когда нет посказок при вводе.

В любом случае спасибо за ответ ;) я не знал что магические методы можно описывать в phpdoc

**Comment by lynicidn** [comment]
gii описывает аттрибуты https://github.com/yiisoft/yii2/blob/master/apps/advanced/common/models/User.php#L18

**Comment by slavcodev** [comment]
@lynicidn а методы не может да?

**Comment by lynicidn** [comment]
@slavcodev Слав, прочитай все мои каменты, я писал что будет много строк с таким подходом

**Comment by dynasource** [comment]
I still see value in setting a value in one line. This could be achieved by extending the setAttribute(s) functions which in the current situation simply return void but could also simply return $this:

```php
    public function setAttribute($name, $value)
    {
        if ($this->hasAttribute($name)) {
            $this->_attributes[$name] = $value;
        } else {
            throw new InvalidParamException(get_class($this) . ' has no attribute named "' . $name . '".');
        }
    }
```
to:
```php
    public function setAttribute($name, $value)
    {
        if ($this->hasAttribute($name)) {
            $this->_attributes[$name] = $value;
           return $this;
        } else {
            throw new InvalidParamException(get_class($this) . ' has no attribute named "' . $name . '".');
        }
    }
```

This gives extra functionality to end-users like:
```php
$model->setAttribute('name','new_name')->save();
```

In this scenario the in this thread mentioned contra-arguments about performance wont apply:
