### ISSUE TITLE
Not informative ReflectionException

### ISSUE THREAD

**Issue by sintanial** [yiisoft/yii2#7333]
Hello all.
When i run application, i catch not informative error, which took a lot of my time.

When in components.php set session component like this: 

``` php
    'session' => [
        'class' => 'yii\web\CacheSession'
    ]
```

and missing "cache" component, then yii2 throw this error:
https://docs.google.com/file/d/0B93SvIJkBgcwaDlUdFlDVWhSZ1E/edit

Yii2 try to create class "cache", but normaly yii2 should show an error about missing component !!!

**Comment by samdark** [comment]
So instead of `Class cache does not exist` you want `'cache' component isn't defined`?

**Comment by sintanial** [comment]
yes
When i remove component 'db', then yii2 throw me error like "Undefined component ID: db" - it is more informative than "Class 'cache' does not exist'

**Comment by dynasource** [comment]
I've also encountered this one a few times. If possible, it would be nice to give the developer more clues about such a problem.
