### ISSUE TITLE
cache expiration when view content is changed

### ISSUE THREAD

**Issue by mohammadhosain** [yiisoft/yii2#7334]
Is it not better that `$view->beginCache()` adds view file to file dependency automatically to expire cache when view content(or fragment) is changed!

**Comment by klimov-paul** [comment]
> Is it not better that $view->beginCache() adds view file to file dependency automatically

It does NOT so. What is the problem?

**Comment by qiangxue** [comment]
Even if the view file is changed, it is likely the cache is still valid. You can add it to the dependency yourself if you think necessary.
