### ISSUE TITLE
Not need to encode for src attribute

### ISSUE THREAD

**Issue by katzz0** [yiisoft/yii2#7336]
BaseHtml::renderTagAttributes() method encoded all not null attributes. If it is use with 'src' attribute this will produce wrong link, for example for link http://api-maps.yandex.ru/2.1/?lang=ru-RU&load=package.full it will produce http://api-maps.yandex.ru/2.1/?lang=ru-RU&amp;load=package.full

**Comment by samdark** [comment]
It should be encoded i.e. `&amp;` is expected.

**Comment by samdark** [comment]
https://stackoverflow.com/questions/3705591/do-i-encode-ampersands-in-a-href
