### ISSUE TITLE
Bootstrap asset is still published, even though disabled in AssetManager

### ISSUE THREAD

**Issue by spikyjt** [yiisoft/yii2#7338]
Because my module provides my own versions, I've disabled jQuery and Bootstrap asset bundles in my AssetManager config as follows:
```
'assetManager' => [
    'bundles' => [
         'yii\web\JqueryAsset' => false,
         'yii\bootstrap\BootstrapAsset' => false,
    ],
],
```
jQuery isn't published to the asset directory, but Bootstrap still is.

**Comment by PapaStifflera** [comment]
Disable also yii\bootstrap\BootstrapPluginAsset.

**Comment by spikyjt** [comment]
Thanks. I see now that is used in NavBar, Dropdown and Widget, all of which I am using.

Sorry this should have been a forum post!
