### ISSUE TITLE
static Model::formName()

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#7342]
I know it was asked about before but not sure if the previous reasons against still apply?
I don't think this is valid any more due to the way objects are initialised, https://github.com/yiisoft/yii2/issues/3362#issuecomment-42211279

`formName` could be changed to static and use `get_called_class()`.
Any existing code should still work as php allows an instantiated class to call a static method.
e.g. `$model->formName()`

**Comment by lynicidn** [comment]
formName must be generated with scenario

**Comment by cebe** [comment]
what change do you propose and why do you think it is needed?

**Comment by Alex-Code** [comment]
It would allow you to get the form name without needing to create an object.

`Yii::$app->request->post((new Model)->formName())`
Could be done as
`Yii::$app->request->post(Model::formName())`

Just feels a bit cleaner than creating/initialising a model object.

**Comment by lynicidn** [comment]
Where need get model data without create model instance?

**Comment by qiangxue** [comment]
The design of `formName()` is that the same model class can have different instances, each with a different form name (imagine you have two forms of the same model class on the same page).

**Comment by Alex-Code** [comment]
Been a long day and I know it'll be obvious when I see it but how can separate instances of the same model return different values in `formName`

**Comment by Faryshta** [comment]
@Alex-Code for example a `User` model can have a signup form and a login form handled by the same class with different validators.
