### ISSUE TITLE
support save format data types (date, time and numeric).

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#7348]
First I apologize for my bad English, I do not write in Spanish because maybe many do not understand, I read all matters relating to the management of data types (date, time, numeric), yii2 framework should be able to offer support to indicate in the model format in which the data is stored in the following example, the development of a control application time and attendance and payroll, number of fields of this type is large and becomes a very cumbersome handling thereof, and to be implemented for each model, a method afterSave, beforesave  and behavior to save the data in the correct format.

We are also losing GII powerful generator, as in these cases, the model generates GII, modify, and therefore, any changes we have to do is not only modify the code model, but also of the view.

I propose should generally be a global setting or a method in the model where you can define how data is stored, you should start with the simplest forms is that php does not offer much support for this, but I think that is the development the frame is there are many extensions as yii2-DateControl (@Kartik-v) and yii2-format-converter (@mdmunir) that can do this job, but I think whether to apply a native solution yii2- frame.

Sorry if this is not the right place for this, it is only a proposal for if in the future can be considered this issue and many others earlier that call for a solution to this problem.

**Comment by cebe** [comment]
Sorry, I do not understand your request, please try to give a usage example or show some code.

> yii2 framework should be able to offer support to indicate in the model format in which the data is stored

we already have type information from db and AR casts data in aftersave...

> We are also losing GII powerful generator, as in these cases, the model generates GII, modify, and therefore, any changes we have to do is not only modify the code model, but also of the view.

What exactly are you trying to do here?

**Comment by tecnologiaterabyte** [comment]
Ok, basically what the date would be resolved, DateValidator::timestampAttribute should have a format #5053, would be interesting to do the same for the type time and numerical formats, so we would not have to have beforesave or behaviors for the conversion of the data.
