### ISSUE TITLE
apc.so

### ISSUE THREAD

**Issue by jcaruso001** [yiisoft/yii2#7349]
I'm getting this error every 5+ mins or so on a Godaddy Server

![2-18-2015 9-14-19 pm](https://cloud.githubusercontent.com/assets/4194148/6261428/70b99d9a-b7b4-11e4-951f-d823e24acade.png)

**Comment by c-butcher** [comment]
We've gone through and made sure that APC wasn't being used, and that dev and prod environment were using FileCache.

**Comment by samdark** [comment]
That's Godaddy problem with server setup.

**Comment by fullflash** [comment]
just turn off apc i got same problem with shneider host too.
