### ISSUE TITLE
Assets warmup

### ISSUE THREAD

**Issue by mitalcoi** [yiisoft/yii2#7351]
I think it would be a great feature to have an ability to create assets files in console(smth like cache:warmup in Symfony2). For example, we deploy a large project with a lot of assets files. We clean up web/assets and then our application will have no any assets for a couple seconds(or minutes!), until it is copied. Maybe you have any suggestions or ideas to implement this feature?

**Comment by klimov-paul** [comment]
For the large project, you should use `asset` command and combine your asset files. All necessary files will be published in the process.
