### ISSUE TITLE
Dump and die Laravel style.

### ISSUE THREAD

**Issue by akireikin** [yiisoft/yii2#7352]
In Yii developers often write
```
var_dump($var);
die();
```
while debugging. It is exhausting. In Laravel we can simply write
```
dd($var);
```
Why not to do the same thing in Yii?

**Comment by klimov-paul** [comment]
Use `VarDumper::dump()`.
You can wrap it in whatever you want if you need it.

**Comment by akireikin** [comment]
@klimov-paul I know it, but write
```
use yii\helpers\VarDumper;
VarDumper::dump($var);
```
or even
```
yii\helpers\VarDumper::dump($var);
```
is also overkill.

Much more characters than in Laravel's `dd()`.
http://laravel.com/docs/4.2/helpers#miscellaneous

Surely I forced to wrap `yii\helpers\VarDumper::dump($var)`. Thought, a lot of developers do the same. May be it will be better to add the alias to Yii's core like it's done in Laravel?

**Comment by klimov-paul** [comment]
Who does prevent you to declare your own function?
```php
function dd($var)
{
    \yii\helpers\VarDumper::dump($var);
    exit();
}
```
Name it as you like and use for your good.
Where is "overkill" here?

**Comment by samdark** [comment]
1. Create `functions.php`.
2. Include it just before `run()` in `index.php`.
3. Define `hh()` there:

```php
function hh($data)
{
    yii\helpers\VarDumper::dump($data, 10, true);
    Yii::$app->end();
}
```

**Comment by akireikin** [comment]
@klimov-paul @samdark As I wrote before, I already do it. There is no problem to write a function for me. I want to have it out of the box like in Laravel. Just proposed a feature, that can be useful for many of  Yii's users.

**Comment by klimov-paul** [comment]
It does not make sense.
It is better for developers to declare this function on thier own, with the name they like and any further adjustments.

**Comment by a-komarev** [comment]
It could be reflected in documentation section, like: `Adding global helper functions`. And just to have couple of examples of such cases.

**Comment by samdark** [comment]
Yep. I'll handle docs.

**Comment by creocoder** [comment]
@klimov-paul 

> It does not make sense.

Ofcourse it make sence. From team development point of view. Having official shortcuts much more better than having personal home grown shortcuts per team.

**Comment by mikehaertl** [comment]
-1
I tend to agree to klimov-paul. At least I don't agree to @samdarks suggestion with an extra `functions.php` file. Not everyone is using the official base or advanced app templates, so this solution would not work for everyone (leading to confusion). If done right, this should be part of YiiBase.php or at least be included from there.

**Comment by lynicidn** [comment]
may be need remove namespace for VarDumper ?

**Comment by dynasource** [comment]
+1 (of course!). I havent seen anything more ugly than the function VarDumper::dump() (well apart from Codeception having  \Codeception\Util\Debug::debug() ;)

The whole thing about dumping is **fast debugging** (the faster the process, the faster the bug found / solution).  Having to remember + type something like 'VarDumper::dump()' is a bit silly in my option (I even have it in my cheatsheet). So dd() will save an enormous amount of time (over time).

> It does not make sense.
how could something like a standard + short cut not make sense. Its standardization and optimization ? @akireikin is showing a use case with is implemented in another big framework. 

> It is better for developers to declare this function on thier own, with the name they like and any further adjustments.
exactly

Another handy usecase is pre():
```php
function pre($mixed){
echo '<pre>';
print_r($mixed);
echo '</pre>';
}
```

giving wonderful output like:
Array
(
    [0] => foo
    [bar] => boo
)

**Comment by samdark** [comment]
@mikehaertl I'm not for adding it to the framework app templates, I'm for documenting the possibility of doing it yourself.

**Comment by a-komarev** [comment]
Adding global methods in core framework is not a best solution because there could be conflicts in names with additional extensions.

**Comment by creocoder** [comment]
If introduce shortcuts officialy it should be done for every helper, for every method... Conflicts can be solved by additinal checking:

```php
if (!function_exists('url_to')) {
    function url_to(...) {
        \yii\helpers\Url::to(...);
    }
}
```

This is how this works in Laravel. And ofcourse it much more usable than import `\yii\helpers\Url` at top of view (which is pain) and than write `Url::to()`. Just simple example for simple helper. We have lots of helpers with lots of methods. Little pain become heavy pain. To be honest very often when i write inside view something like `ArrayHelper::something()` i cleanly understand that something WRONG with Yii at this point.

**Comment by creocoder** [comment]
> documenting the possibility of doing it yourself

Will lead to next generation of "the inventors of the wheel". From companies point of view its better to have official helpers or do not have it at all.

**Comment by dynasource** [comment]
> If introduce shortcuts officialy it should be done for every helper, for every method
Its not so bad Idea to shortcut a top X of the most used functions.

**Comment by a-komarev** [comment]
@creocoder checks with `function_exists` is a good idea.
What about naming convention? Helper functions naming should be standartized as other functions (camelCase)?

**Comment by dynasource** [comment]
a naming convention related to Yii software wouldnt be so bad either:

yTag() -> \yii\helpers\Html::tag()
yUrl() -> \yii\helpers\Url::to()
yDump() -> \yii\helpers\Vardumper::dump()

Benefits:
- super short
- easy to remember
- functions as an alias (for future naming changes)
- still has some indication to Yii because of its Y
- this is very likely not to interfere with other functions because of the y-prefix

**Comment by creocoder** [comment]
> What about naming convention? Helper functions naming should be standartized as other functions (camelCase)?

CamelCase for methods. For function there is already naming conventions inside php itself and its underscore. Also such helpers is natural for php. For example: `date_create_from_format()` as helper for `DateTime::createFromFormat()`. Laravel go php language way by introducing shortcuts for its helpers.

**Comment by mikehaertl** [comment]
> I'm not for adding it to the framework app templates, I'm for documenting the possibility of doing it yourself.

@samdark I see now. Makes perfect sense to me. The discussion here already shows, that it's hard to find a consensus. So IMO this should really be solved on a per-team basis and not be part of the framework itself.

**Comment by a-komarev** [comment]
@creocoder Thats a good point.
I've found this [listing of naming conventions of other frameworks & CMS](http://programmers.stackexchange.com/a/149321).

[Here is a PHP naming convention](http://git.php.net/?p=php-src.git;a=blob_plain;f=CODING_STANDARDS;hb=HEAD)
Note section: `User Functions/Methods Naming Conventions`

```
Function names for user-level functions should be enclosed with in
the PHP_FUNCTION() macro. They should be in lowercase, with words
underscore delimited, with care taken to minimize the letter count.
Abbreviations should not be used when they greatly decrease the
readability of the function name itself::

Good:
'mcrypt_enc_self_test'
'mysql_list_fields'
```

**Comment by dynasource** [comment]
perfect

**Comment by johonunu** [comment]
http://www.yiiframework.com/wiki/793/debuging-variables-in-yii2/

**Comment by marcoantoniooliveira** [comment]
@akireikin that is already possible with a extension 'Kint', it is the same using on Laravel.

Just add it to your composer. For further informations access: http://raveren.github.io/kint/

**Comment by akireikin** [comment]
@marcoantoniooliveira nice extension. Thank you.

**Comment by pana1990** [comment]
Imho this feature should be include in core framework, it encourage clean code and it will make developers happy :)

**Comment by briedis** [comment]
For anyone wanting a nice var-dumper, I suggest including the same as in Laravel - symphony var dumper (http://symfony.com/doc/current/components/var_dumper/introduction.html)

1. Add composer dependency: `"symfony/var-dumper": "~2.6"`
2. Define dd() function:
```
function dd()
    {
        array_map(function ($x){
            $dumper = 'cli' === PHP_SAPI ? new CliDumper : new HtmlDumper;
            $dumper->dump((new VarCloner)->cloneVar($x));
        }, func_get_args());
       die;
    }
```
...and enjoy ;)

It's just a pitty, that Yii's philosophy isn't about making coding fun, easy, convenient, Laravel is so much better at this.

**Comment by samdark** [comment]
Can be done w/o using external components:

```php
function dd()
{
    array_map(function ($x){
        echo \yii\helpers\VarDumper::dump($x, 10, true);    
    }, func_get_args());
}
```

**Comment by klimov-paul** [comment]
Just to think about: maybe we should introduce `Yii::dump()`? It can cover this pupular demand and will have short enough name.

**Comment by briedis** [comment]
@samdark Symfony dumper is more pleasant to use - expandable, etc. 

If I wan't to browse a model, view attributes, etc, dump a model instance:

Yii dumper: https://ziedlejas.lv/screenshots/img.2015.06.04.OvKENP.jpg (couldn't fit in the screen)
Symfony dumper: https://ziedlejas.lv/screenshots/img.2015.06.04.wMDl8V.png

**Comment by a-komarev** [comment]
@briedis There is an error if function only defined, but no libraries used.

>Class 'HtmlDumper' not found

Before `function dd()` add
```php
use Symfony\Component\VarDumper\Dumper\HtmlDumper;
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\CliDumper;
```

Or write something like this:
```php
function dd()
{
    array_map(function ($x){
        $dumper = 'cli' === PHP_SAPI ? new \Symfony\Component\VarDumper\Dumper\CliDumper :
                                       new \Symfony\Component\VarDumper\Dumper\HtmlDumper;
        $dumper->dump((new \Symfony\Component\VarDumper\Cloner\VarCloner)->cloneVar($x));
    }, func_get_args());
    die;
}
```

**Comment by briedis** [comment]
@a-komarev 

Sorry, yeah, I had them imported, and forgot to copy that part.

To avoid already defined function, one can use `function_exists` function.
```php
if(!function_exists('dd')){
   function dd(){
      ...
   }
}
```

**Comment by dynasource** [comment]
I rethought my mind. I agree this functionality to be covered by an external library like ie. Kint http://raveren.github.io/kint/

**Comment by samdark** [comment]
I think it's better to leave it to developers. Not going to suggest and "official" way of achieving it.

**Comment by DenisAlliswell** [comment]
@briedis thanks. 

For anyone who wants the same styles as in Laravel var-dumper, just replace $styles array data in HtmlDumper class with the following:
```
protected $styles = array(
    'default' => 'background-color:#fff; color:#222; line-height:1.2em; font-weight:normal; font:12px Monaco, Consolas, monospace; word-wrap: break-word; white-space: pre-wrap; position:relative; z-index:100000',
    'num' => 'color:#a71d5d',
    'const' => 'color:#795da3',
    'str' => 'color:#df5000',
    'cchr' => 'color:#222',
    'note' => 'color:#a71d5d',
    'ref' => 'color:#a0a0a0',
    'public' => 'color:#795da3',
    'protected' => 'color:#795da3',
    'private' => 'color:#795da3',
    'meta' => 'color:#b729d9',
    'key' => 'color:#df5000',
    'index' => 'color:#a71d5d',
);
```

**Comment by gr33k01** [comment]
If you're a sublime user and want a more consistent, framework-agnostic experience: https://gist.github.com/gr33k01/4d8ee334f38db027acc3360b2c3e988f

**Comment by schmunk42** [comment]
Someone could create an extension for this and developers could place it into `require-dev` 😺

**Comment by vladyslavstartsev** [comment]
@schmunk42 there is `composer require larapack/dd 1.*`

**Comment by tristondeadbeat** [comment]
> Can be done w/o using external components:
> 
> function dd()
> {
>     array_map(function ($x){
>         echo \yii\helpers\VarDumper::dump($x, 10, true);    
>     }, func_get_args());
> }





https://phps.space/questions/adjusting-color-in-yii-by-utilizing-html
