### ISSUE TITLE
Update yii\web\Link object to support latest JSON-HAL spec

### ISSUE THREAD

**Issue by cwt137** [yiisoft/yii2#7353]
As of this writing, the latest spec is [draft-kelly-json-hal-06](https://tools.ietf.org/html/draft-kelly-json-hal-06.) In it, there is a new link object property that is not in yii\web\Link. The "deprecation" property should be added to the PHP object.

**Comment by cebe** [comment]
Not sure if it is a good idea to add this at this state. the document you linked is a draft and may change in the future. We can not change yii code for BC reasons afterwards. I think we should wait for the document to become official.

**Comment by klimov-paul** [comment]
We have already a disscussion about HAL support here #5912
Conclusion: Yii supports HATEOS for REST.
If you with HAL support - it is up to your code.
