### ISSUE TITLE
FilterValidator|trim doesn't work on client side

### ISSUE THREAD

**Issue by Koudy** [yiisoft/yii2#7361]
Why?

**Comment by Alex-Code** [comment]
Would help if you gave more detail.
What you're expecting and what actually occurs.

**Comment by Koudy** [comment]
@Alex-Code,
```
MyModel::rules()
{
	return [
		['email', 'trim'],
		['email', 'email'],
	];
}
```
![f8db64e190b2eec3c102b4ddf868d9bc](https://cloud.githubusercontent.com/assets/4976467/6267897/45bdf212-b859-11e4-8f83-579aceb9f85c.png)

**Comment by lynicidn** [comment]
trim it's a callable method it's not validator.

**Comment by Koudy** [comment]
@lynicidn, ok, but what happens is the wrong way, isn't it? What to do? Write js by myself?

**Comment by lynicidn** [comment]
u must create trim validator if needed, as simple example:
```php
class TrimValidator extends FilterValidator
{
    public $filter = 'trim';
    public function clientValidateAttribute($model, $attribute, $view)
    {
        //write js logic
    }
}
```

**Comment by Koudy** [comment]
@lynicidn, why not to add it to a framework?

**Comment by Koudy** [comment]
@lynicidn, I think that should be in the framework.

**Comment by lynicidn** [comment]
hm it's `filter` validator - how he know what is filter be applied ? trim, count, md5 or your have do client validate equal for all ?
p.s.: add in bootstrap: 
```php
yii\validators\Validator::$builtIn['trim'] = 'TrimValidator';
```

**Comment by Koudy** [comment]
@lynicidn, I mean to add the TrimValidator to a framework about which you speak.
Or at least write about it in the documentation. Because when I use it in this way:
```
['email', 'trim'],
```
it is expected that this will work on the client side.

**Comment by creocoder** [comment]
There is filters inside `rules()`, there is validators inside `rules()`. Filter is NOT validator. Filters should not work on client side.

**Comment by Koudy** [comment]
Thanks!

**Comment by Koudy** [comment]
@qiangxue, now trim works, but after it I still get error:
![5a0b0e90459763b706dddfa64a780d5b](https://cloud.githubusercontent.com/assets/4976467/6638311/d32f0832-c995-11e4-93b2-cd9385334871.png)

Can be done so that it runs before the other validators?

**Comment by creocoder** [comment]
@Koudy You can control that by correct validators order inside model.

**Comment by Koudy** [comment]
@creocoder, no, this does not work.

```
public function rules()
{
	return [
		[['email', 'password'], 'required'],
		['rememberMe', 'boolean'],

		[['email'], 'trim'],
		['email', 'email'],
		...
	]
}
```

**Comment by creocoder** [comment]
@Koudy Yes, its not work for you since you have incorrect validators order inside model.

**Comment by creocoder** [comment]
@Koudy Try this

```php
public function rules()
{
    return [
        // ...
        ['email', 'trim'],
        ['email', 'required'],
        ['email', 'email'],
        // ...
    ];
}
```

**Comment by Koudy** [comment]
@creocoder, doesn't work.

**Comment by creocoder** [comment]
@Koudy I think its better to create separate issue for that.

**Comment by ageeweb** [comment]
when you add into vendor\yiisoft\yii2\assets\yii.validation.js line 192
" value = value.trim();  "
it's working. is there a separate issue?

**Comment by cebe** [comment]
@ageeweb thats not the point of the issue, trim is meant to be a filter that can be added when needed, not the default behavior.

**Comment by ageeweb** [comment]
if you add a space after the email and trim is on (it trims the space of immediately) then you cannot remove the space, you must re-enter the email address before you can submit the form.

**Comment by cebe** [comment]
Why do you need to re-enter the email? What exactly is the problem?

**Comment by ageeweb** [comment]
if you check email with :    
return [
        // ...
        ['email', 'trim'],
        ['email', 'required'],
        ['email', 'email'],
        // ...
    ];

on mobile (android and iphone) when you start typing email you can auto fill your email address, but it adds a space to type second word. that space gives an error that email is not valid. (you can simulate this to type email, and add a space) for the email check it will not trim first. After enter you can not see the space, (Trim is working)  but for the check its not gone? if you check te value in javascript trace, you can see there is a space, that you cannot remove (its not in your fill in box).

test this and you see what I mean:
"fill in email address and add a space and then enter"

**Comment by cebe** [comment]
can you please open a new issue for this?

**Comment by ageeweb** [comment]
added https://github.com/yiisoft/yii2/issues/8882
