### ISSUE TITLE
Accessing model name from $model object

### ISSUE THREAD

**Issue by johonunu** [yiisoft/yii2#7362]
How can I access model name from $model object? or Active Record?
I know that this is more forum type question, but I need core developers opinion. Right now, I use this in model class, to get model name:

```
public function getAlias() {
    return  (new \ReflectionClass($this))->getShortName();
 }
```
Is there better way(or is this good) and is there core functionality implemented for this?

**Comment by Alex-Code** [comment]
In the docs here, [formName](http://www.yiiframework.com/doc-2.0/yii-base-model.html#formName()-detail)

**Comment by qiangxue** [comment]
There's no such concept as model name. Use `Model::className()` or `formName()` like @Alex-Code suggested.
