### ISSUE TITLE
Loading of AppAsset is wrong

### ISSUE THREAD

**Issue by gerald27** [yiisoft/yii2#7364]
Hi I followed the documentation about the AppAsset but when I run my application, there's a problem about the arrangement of js file. 

This is my AppAsset

![appasset](https://cloud.githubusercontent.com/assets/9834829/6270810/761c04f6-b897-11e4-9e58-e124dccc68f9.png)

This is the output

![console](https://cloud.githubusercontent.com/assets/9834829/6270825/96392b60-b897-11e4-8915-f4f5757dc7d9.png)

**Comment by dynasource** [comment]
can you complete your question by adding what you were expecting?

**Comment by gerald27** [comment]
the bootstrap should be loaded after the yii.js but it's loading last

**Comment by dynasource** [comment]
if that is what you want to achieve, do:
- override \yii\bootstrap\BootstrapAsset with ie. \app\BootstrapAsset
- put a depends on \yii\\web\YiiAsset in this class
- put your new class in AppAsset (remove the 2 in your pic)

**Comment by gerald27** [comment]
It's strange sir because on my previous projects I haven't encountered this.

**Comment by dynasource** [comment]
depends works with a depencyloader, there is logic behind it. If you want to have it perfect, you must follow this logic, otherwise you bound yourself to the luck of having these in the correct order (which can be changed by other assets)

**Comment by samdark** [comment]
There's no guarantee of the order if dependencies aren't specified.

**Comment by yujin1st** [comment]
This specific issue with bootstrap js is solving by using BootstrapPluginAsset  instead of BootstrapAsset, as the last one doesn't inlcude js, thus it looks like js is not required for your assets.

**Comment by wartur** [comment]
confirm. It is necessary to properly use the Property AppAsset :: depends
