### ISSUE TITLE
Feature request: yii migrate/mark all

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii2#7367]
Similar to Rails migrations, I have a structure.sql (always the latest structure) and incremental migration files.

When I create a new database and import my schemadump, I still need to mark existing migrations as applied. Maybe if I could run something like..
```
yii migrate/mark all
```
..this would update migration history, without having to look for the latest migration timestamp myself?

**Comment by lynicidn** [comment]
```bash
mysqldump -u USER -pPASSWORD DATABASE > /path/to/file/dump.sql
yii migrate/up all
mysql -u USER -pPASSWORD DATABASE < /path/to/dump.sql
```

**Comment by samdark** [comment]
Hmm... migrations info is stored in the database so when its dump imported migration table should be imported as well, shouldn't it?

**Comment by cebe** [comment]
@marcovtwout as @samdark said, when you dump the schema, just dump the migration table too.
