### ISSUE TITLE
Yii 2Flexible Routes With Unlimited Get Parameters

### ISSUE THREAD

**Issue by mezlad** [yiisoft/yii2#7368]
As advised by @cebe i should create an issue for the following: 

Suppose there exists a scenario where you enter controller:w+/action:w+/page/page:+d/limit/limit:+d but you would like the rule to be flexible to accept controller:w+/action:w+/limit/limit:+d/page/page:+d without setting two rules, how would you achieve this?

I remember in yii 1.1 this could be achieved by either using controller:w+/action:w+/\* or controller:w+/action:w+?(/page/page:+d)?(/limit/limit:+d)?

**Comment by mezlad** [comment]
Any progress or changes on this?

**Comment by qiangxue** [comment]
I don't understand the necessity of supporting this. You want two forms of URL formats and you only want a single rule? Yii 1.1 can't solve this problem either.

**Comment by mezlad** [comment]
Urls are not flexible in the pretty url format where a parameter can exist any where after the url pattern. You might have a pattern where you may not know all the parameters that are required initially and later on add additional ones so instead of changing the URL rule itself, the rule is flexible in a manner to accept additional params immediately. 

I am yet to find out how to configure this manner of flexibility in YII2 where in Yii 1 all that had to be done was setup the parameter rule with a /* for arguments sake.

Some of us developers have transitioned from using the url query characters in our url and would like to use the pretty url format throughout our applications and this is why it is a necessity.

**Comment by qiangxue** [comment]
Allowing multiple forms of URL to point to the same resource is a bad idea for SEO. You should use GET parameters in this case. That's why Yii2 dropped the support of `/*`. You also won't find such support in other modern frameworks.

**Comment by mezlad** [comment]
Ok, so converting a yii 1 application with this implemented would require redevelopment then. For the other form of optional parameters using the ?(/page/page:+d)? in yii 1.1, is this also bad for SEO because this isnt supported either in yii 2.

**Comment by qiangxue** [comment]
I don't think Yii 1.1 supports optional parameters. This is a new feature implemented in Yii 2 (not specified in this format though).

**Comment by mezlad** [comment]
I have set out URLs in my yii 1.1 application that follow the ?(/<country>)?(/<code>)? pattern where the url does not have to accept a country param or code param. In Yii2 when i use the optional parameter and say i have a pattern like this
[
'pattern' => '<module:\w+>/<controller:\w+>/edit/limit<limit:\d+>/mode/<mode:\d+>',
'route' => '<module>/<controller>/edit',
'defaults' => ['limit' => "",'mode'=>""],                     
],

if I have no limit but I have a mode and I set only the mode in the URL I get a 404 page not found error but to achieve this I would have to setup an additional rule and that's where I find the flexibility with URL parameters more convenient in yii 1.1 compared to yii2.

I am just curious though, having ?page=1&limit=2 compared to /page/1/limit/2
and ?limit=2&page=1 compared to /limit/2/page/2 Why do I have to setup 2 different rules to achieve the pretty URL format where it does not matter when using the original query parameter string?

**Comment by dynasource** [comment]
> Allowing multiple forms of URL to point to the same resource is a bad idea for SEO. You should use GET parameters in this case. That's why Yii2 dropped the support of /*. You also won't find such support in other modern frameworks.

I agree with Qiang. With respect to the given arguments, I dont see the necessity to extend the framework for this.

**Comment by Havismat** [comment]
It's simple functionality, and I think Yii2 need this.
