### ISSUE TITLE
add linkForeignKeys for ActiveRecord (not for via relation)

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#7369]
@samdark Тут бы на русском объяснить, не то что на английском :)
Суть такова, есть модель, в которой аттрибут slug обязателен, SlugableBehavior генерирует его перед валидацией, это поведение по умолчанию, и в моем случае этот аттрибуте еще участвует в валидации на уникальность в паре с категорией, т.е. я не могу генерировать его перед сохранением. Проблема начинается, когда я создав новую модель пытаюсь пролинковать ее, но метод link сохраняет новую модель https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1418

-=-=-1 вариант - линк, затем лоад
$model = new my\Model;
$model->validate(['slug']); //чтобы сгенерировать его - аттрибут обязателен
$model->link(....); //do save
$model->load(....);
$model->save();
Вот тут собственно поведение странное, мне нужна только линковка ключа, мне не надо сохранять модель, так как я буду в нее load еще делать, а там и slug может измениться, т.е. валидировал я его тупо чтобы субд не кинула ошибку, что колонка обязательна

-=-=-2 вариант - сначал лоад, потом линк
$model = new my\Model;
$model->load(....);
$model->validate(....); //error linkFk is required|not exists
$model->link(....); //do save, but errors not cleared
Тут тоже поведение не очень хорошее, т.к. validate выдаст ошибку на связной ключ обязательный, который проставить должен link
Если возиться самому с fk - исключать из валидации или устанавливать самому минуя load, то спрашивается зачем link - только для простых моделей

Предложения: 
1. добавить параметр в метод link который бы влиял на сохранять модель или нет, да даже хотябы валидировать или нет
2. добавить новый метод который бы просто проставлял ключи и все (т.е. линк разбить на растановку ключей и сохранение)

Суть проблемы в поведениях модели, которые завязаны на beforeValidate и link который не делает validate. Вопрос - что вначале надо делать - линк или валидейт?

**Comment by Alex-Code** [comment]
Could you provide an English translation, Not sure if this is similar to something I've done.

**Comment by lynicidn** [comment]
of corse, only later

**Comment by lynicidn** [comment]
move to #7375
