### ISSUE TITLE
add active class for radio and checkbox

### ISSUE THREAD

**Issue by swordream** [yiisoft/yii2#7370]
radio will generate 
"&lt;label&gt;&lt;input type='radio' checked name='xxxx'&gt;&lt;label&gt;" 
when checked is ture,
maybe adding adctive class to label tag  would be easier selected by css3. for example:
"&lt;label class='active' &gt;&lt;input type='radio' checked name='xxxx'&gt;&lt;label&gt;"
 my soluation is add

if($checked == true){
	$labelOptions['class'] = 'active';
}

in HtmlHelper::raido.

**Comment by cebe** [comment]
not sure I go what you are trying to do, please elaborate.

**Comment by samdark** [comment]
Closed since no further info provided.
