### ISSUE TITLE
REST: recognize format for ContentNegotiator from suffix

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#7371]
Some APIs use suffix as one of the ways to define response format: `GET /posts.xml`, `GET /posts/123.json`. I think, it can be implemented in Yii2 REST as an optional feature.

**Comment by samdark** [comment]
What's the usage for it?

**Comment by RomeroMsk** [comment]
There are no REST API standards, so we are using so called best practices. And there are different ways to tell API what format client wants in response (you can find all of them in various API implementations from various companies/services):
1. `Accept` header (already have this in Yii2).
2. GET-parameter (already have).
3. Suffix (don't have, but can be implemented by modifying `\yii\rest\UrlRule::parseRequest()`, I think).

**Comment by RomeroMsk** [comment]
Let's call it "another acceptable pattern".

**Comment by creocoder** [comment]
:+1: for that

**Comment by RomeroMsk** [comment]
I've tried to implement this by changing `patterns` of `UrlRule`. This is working good: `'GET,HEAD {id}.{_format}' => 'view'`. But I don't know how to make a pattern for `index` (problem is in slash after resource name). So, I think `\yii\rest\UrlRule::parseRequest()` may be better place for implementing this. But I don't know, how to deal with `ContentNegotiator` from this method (to get `$formatParam` in situation when it was set to something different from `'_format'`).

**Comment by klimov-paul** [comment]
You can specify URL rule for REST controller to cover that:
```php
<controller:\w>/<action:\w>.<format:\w> => 'controller/action'
```

**Comment by RomeroMsk** [comment]
@klimov-paul, what pattern you will use to make `GET /resource` works (instead of https://github.com/yiisoft/yii2/blob/master/framework/rest/UrlRule.php#L120).

**Comment by creocoder** [comment]
I though this issue not about elementary information about `UrlManager` and how to reach issue goals to make feature work. It obvious how to make it works by setting up right rules. I think we talk about how to enhance `ContentNegotiator`.

**Comment by klimov-paul** [comment]
> I think we talk about how to enhance ContentNegotiator.

I don't think there should be any adjustments. `ContentNegotiator` extracts all necessary data from `Request`. If there is a proerly named parameter inside requst object it will be extracted. What else do you expect there?

**Comment by Ragazzo** [comment]
This was already discussed several times in previous issues

**Comment by RomeroMsk** [comment]
@Ragazzo, you mean this whole issue or last comments? What was the decision?

**Comment by Ragazzo** [comment]
https://github.com/yiisoft/yii2/issues/2034

**Comment by samdark** [comment]
Overall I think two existing methods of requesting content-type are covering all possible clients out there. I don't think another one is really needed.

**Comment by creocoder** [comment]
@Ragazzo How this related to this one? This one about suffixes only.

**Comment by creocoder** [comment]
@samdark 

> I don't think another one is really needed.

Ofcourse its needed. Because using suffixes currently lead to:

```
'GET,HEAD v1/projects/<id:\d+>.<format>' => 'v1/project/view',
```

inside real applications.

**Comment by RomeroMsk** [comment]
@samdark, not all :) They are covering *most* of them. If this feature will be easy to implement, so why not cover more cases?

**Comment by Ragazzo** [comment]
@creocoder same issue, making output formatter by suffix, it was really discussed long time with @qiangxue also and he issued to github that uses headers for that, afaik that issue was closed, so this one also can be. There is nothing in this one except "beauty" of url.

**Comment by samdark** [comment]
@RomeroMsk do know any client that's not able to send HTTP headers and/or URL parameters?

**Comment by Ragazzo** [comment]
i also think that simple url param like `?format=...` or `?xml=true`, `?json=true` is fine. So far being working with a lot of API i see no difference at all if it allow to control it in easy way, so url param or `.xml / .json` does not really matter

**Comment by creocoder** [comment]
> They are covering most of them.

Disagree about most. Suffixes is widely used. And this important case is not covered.

@samdark 

> do know any client that's not able to send HTTP headers and/or URL parameters?

Sorry, but this is wrong question. It does not matter. Sometimes there is **clean** RESTful service spec and suffixes must be here.

We can enhance `yii\rest\UrlRule`:

```php
[
    'class' => 'yii\rest\UrlRule',
    'controller' => [
        'v1/user',
        'v1/project',
    ],
    'suffix' => ['json', 'xml'],
],
```

**Comment by Ragazzo** [comment]
@RomeroMsk and i was talking about this one https://github.com/yiisoft/yii2/issues/303#issuecomment-36602255 i think @samdark remember that discussion

**Comment by RomeroMsk** [comment]
@samdark, I'm talking about different patterns, not about clients abilities.

**Comment by RomeroMsk** [comment]
@creocoder, I've thought about this way too. But I don't know how to implement this.

**Comment by RomeroMsk** [comment]
@Ragazzo, yes, I see your suggestion there. And I see that some devs are against supporting another pattern. But if we will find an easy and beatiful way to implement this, why not? It will be good feature.

**Comment by Ragazzo** [comment]
@RomeroMsk i am not against, i am just pointing that it was rejected that time not sure if this time it will be accepted, as you can see nothing new here ) I am fine with header or url in truth there is nothing wrong with them, `Symfony2` approach with suffixes or `Rails` one is also great of course

**Comment by RomeroMsk** [comment]
@Ragazzo, I didn't tell that **you** are against :) I understand your point, let's see...

Django REST [has it too](http://www.django-rest-framework.org/api-guide/format-suffixes/).

**Comment by Ragazzo** [comment]
Ok )

**Comment by RomeroMsk** [comment]
@creocoder, do you have any thoughts on how to play with response format inside `yii\rest\UrlRule` using `suffix`?

**Comment by creocoder** [comment]
@RomeroMsk Fixing `yii\rest\UrlRule` is just about url manager rules. It should not play with response format. But this is where fix should start.

**Comment by samdark** [comment]
@RomeroMsk, @creocoder I think if suffix is absolutely required it could be achieved by overriding `yii\rest\UrlRule` so it will set request argument (probably via defaults). Don't think it should be at negotiator level.

**Comment by RomeroMsk** [comment]
Ok, we can set a `_format` parameter from `yii\rest\UrlRule::parseRequest()`. But if `$formatParam` was set to another string (in `Controller::behaviors()`) - how can we get this?

**Comment by samdark** [comment]
We can assume that the one specified in URL takes priority.

**Comment by RomeroMsk** [comment]
We will not specify parameter in URL, we will use suffix only.
If I will set another value of `formatParam` (in bootstrap or in `Controller::behaviors()`), this will not work. So we need somehow to link this two places.

**Comment by creocoder** [comment]
@RomeroMsk Looks like fixing only `yii\rest\UrlRule` is enough:

```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'formatSuffix' => ['json', 'xml'],
        // 'formatParam' => '_format',
    ],
```

**Comment by creocoder** [comment]
As alternate suggestion:

```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'suffix' => ['json', 'xml'],
        // 'format' => '_format',
    ],
],
```

There is already string `UrlRule::$suffix`, we can extend it to array and reuse it for that feature needs.

**Comment by RomeroMsk** [comment]
@creocoder, I understand your idea - that's good.
We don't need to use `UrlRule::$suffix`, because it will be assigned to `yii\web\UrlRule::suffix` (we don't want to change it too, yes?) Also array in this property will be a problem for `createUrl()`.

**Comment by creocoder** [comment]
@RomeroMsk We need replay `Url::$suffix` role because it will become excess property. I do not see any troubles with `createUrl()`.

**Comment by RomeroMsk** [comment]
... or we can use different rules for various formats:
```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'suffix' => 'json',
        // 'formatParam' => '_format',
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'suffix' => 'xml',
        // 'formatParam' => '_format',
    ],
],
```
According to fact that one of these formats will be used by default (when header is not used), some devs can use only one rule - for XML ony, for example.

**Comment by RomeroMsk** [comment]
@creocoder, see here:
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlRule.php#L335
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlRule.php#L219
1. You will need to make changes for this class too.
2. You will need to play with `suffix` array, because you don't know which of two or more elements to use when creating an URL.

**Comment by creocoder** [comment]
@RomeroMsk 

```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'suffix' => 'json',
        // 'formatParam' => '_format',
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'suffix' => 'xml',
        // 'formatParam' => '_format',
    ],
],
```

This is joke? Dublicate 90% every time where new format needed? `UrlRule::$suffix` should be array, because syntax much more important that any possible implementation troubles. All implementation troubles can be solved in that case.

**Comment by creocoder** [comment]
End of each rules when suffix used will looks like `.(json|xml)`. There no any troubles with `createUrl()`.

**Comment by RomeroMsk** [comment]
What will you do in places which I mentioned above? What string suffix will you use when creating an URL inside `yii\web\UrlRule` (for example, when generating URL by `Url::toRoute(...)`)?

**Comment by creocoder** [comment]
@RomeroMsk We can override that methods, but OK. We can introduce `\yii\rest\UrlRule::$formatSuffix` and `\yii\rest\UrlRule::$formatParam` as it was inside original suggestion and ofcource `\yii\rest\UrlRule::$formatSuffix` should be array because dublicating all rules for new suffix is really ugly and painful :)

**Comment by RomeroMsk** [comment]
In case of separate property (`formatSuffix`) it must be an array, of course. My suggestion about duplicating rules was just to play with string type of `suffix`.

**Comment by creocoder** [comment]
@RomeroMsk In general play around `suffix` looks more interesting. This will require more complex fix, but probably it worth it. How i see that: Probably its good idea to introduce `suffixParam` instead of `formatParam`. This will give us possibility to make BC fix. There are possible cases:

1) `suffix` is string and `suffixParam` is null
Everything works like it works now.
2) `suffix` is string or array and `suffixParam` is string
Thats mean that `suffix` value go to `suffixParam`. To create url you should explicitly set that param.

@samdark What you think around it? Introducing `formatSuffix` looks non consistent. There is already property and its smart to reuse it.

**Comment by RomeroMsk** [comment]
@creocoder, the main problem of using array in `suffix` is in creating of an URL. Now when you calling `Url::toRoute()` or similar methods, Yii will look for a `suffix` value to add it to created URL. But in your case the value will be an array. What suffix you want to add to the URL - first element?

**Comment by qiangxue** [comment]
The problem described by @RomeroMsk is the main difference between the suffix and the parameter.

**Comment by creocoder** [comment]
@RomeroMsk Does ANY **constant** suffix make sence for RESTful service routing needs? No. Is that excess property in general when we talk about RESTful services? Yes. Lets make this property somehow useful.

> What suffix you want to add to the URL - first element?

As i said before:

> To create url you should explicitly set that param.

By saying **that** param i mean `suffixParam`. Simple example:

```
'suffix' => ['xml', 'json'],
'suffixParam' => 'format',
```

By using `Url::to([..., 'format' => 'xml']);` you can create. If `suffix` is string and `suffixParam` is null everything works as before for BC. When `suffixParam` is string `suffix` come to that param.

**Comment by RomeroMsk** [comment]
@creocoder, now I understand your idea. Need to think about it.

**Comment by RomeroMsk** [comment]
Sorry, had no time. Agree with @creocoder ideas. Conclusion:
1. Add new property `suffixParam` to `yii\rest\UrlRule`.
2. Change `yii\rest\UrlRule::createUrl()` method to get suffix from `$params` (according to `suffixParam` value) and add it to the end of URL.
3. Change `yii\rest\UrlRule::parseRequest()` to get a suffix from URL and put it into queryParams (to pass it to `ContentNegotiator`).
@creocoder, didn't I miss something?

**Comment by creocoder** [comment]
@RomeroMsk Hi. Everything correct. As alternate variation i recommend consider `formats` with `formatParam`. Probably it will simplicity implementation. In that case `suffix` is always constant. Probably this variation even more consistent with current design.

**Comment by RomeroMsk** [comment]
@creocoder, sorry, didn't understand this.

**Comment by creocoder** [comment]
@RomeroMsk There is 2 suggestions:

```
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'formats' => ['json', 'xml'],
        // 'formatParam' => '_format',
    ],
],
```

and 

```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/user',
            'v1/project',
        ],
        'suffix' => ['json', 'xml'],
        // 'suffixParam' => '_format',
    ],
],
```

I think 1st is more consistent with current framework design. It make `suffix` not usable in case when `formats` used, but probably its fine. Suffix is still usable for other cases. So i'm personally rethink my mind and now think that 1st variation better. Also it consistent by used terms and simplier by implementation.

**Comment by RomeroMsk** [comment]
Oh, understand now - it's about [this](https://github.com/yiisoft/yii2/issues/7371#issuecomment-75239419).
Good, but I think we need to use another name to emphasize that it is about suffix. Because if somebody looks at this `formats` param and didn't read this topic, he will not understand its purpose.
`formatSuffix` and `suffixParam` are fine for me. What do you think?

**Comment by creocoder** [comment]
@RomeroMsk In that case better go 2nd way. Since `suffixParam` has nothing related to `suffix` and there second controversial `formatSuffix`. I think it will lead to little mess ) While `suffix` and `suffixParam` is clean enough.

**Comment by RomeroMsk** [comment]
Ok.

**Comment by mtangoo** [comment]
Yii2 is now feature freeze. Closing this
