### ISSUE TITLE
Link new model with behaviors

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#7375]
i have model:
```php
class Field extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'label',
                'immutable' => true,
            ],
        ];
    }
    public function rules()
    {
        return [
            [['slug', 'label', 'form_name'], 'required'],

            [['slug', 'label', 'default'], 'string', 'max' => 255],

            ['form_name', 'exist', 'targetClass' => Form::className(), 'targetAttribute' => 'name'],
            ['slug', 'unique', 'targetAttribute' => ['slug', 'form_name']],
            ['label', 'match', 'pattern' => '/[\w\s]+/isU'],
        ];
    }
    public function getForm()
    {
        return $this->hasOne(Form::className(), ['name' => 'form_name']);
    }
}
```

---

and action for add new model `Field` into model `Form`:
```php
    public function actionCreate($form_name)
    {
        $form = $this->module->findForm($form_name);
        $model = new Field();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // next logic...
        }
        $model->link('form', $form);
    }
```
I get error `form_name` is required in `validate()` or if model not loaded - i get mysql error `slug` column can't be empty.

---

Problem: SlugBehavior generate `slug` in event `beforeValidate`, but `link` not validate model before save

---

May need add new method `linkForeignKeys` or add new param for `link` method $save|validate = true ?

**Comment by lynicidn** [comment]
analog situations for standard advanced app:
```php
$model = new User;
if ($model->validate()) {
    $model->save(); 
/*throw error:
 password_hash column can't be empty 
https://github.com/yiisoft/yii2/blob/master/apps/advanced/console/migrations/m130524_201442_init.php#L20 */
}
```

it's not correct behavior - if model validated then her should be saved.

As variant add unsafe param in validator.
```php
['password_hash', 'required', 'unsafe' => true]
```

**Comment by creocoder** [comment]
@lynicidn You have absoluttely wrong rules for `slug` attribute.

@samdark Probably this one is for enhance documentation.

**Comment by lynicidn** [comment]
@creocoder why?

**Comment by lynicidn** [comment]
@creocoder problem in link

**Comment by lynicidn** [comment]
i think need as `'/[\w\s\-\_]+/isU'`, but it not problem

**Comment by creocoder** [comment]
@lynicidn There is two issues. Wrong `slug` rules does not related to original issue and this is just mark for @samdark about enhanced documentation for `SluggableBehavior`. About `link()` method. By design it do not make validation. Just make validation and use `link()` **after that**.

**Comment by lynicidn** [comment]
@creocoder how i can validate FK before `link` ?

**Comment by creocoder** [comment]
@lynicidn Same way as validating any other attribute.

**Comment by lynicidn** [comment]
@creocoder: i can write as:
```php
$relation = $field->getRelation('form');
$attributes = array_diff($field->attributes, $relation->link);
if ($form->load($post) && $form->validate($attributes)) {
$field->link('form', $form);
}
```
but i think should be easy way

p.s. i don't test it, but this should work

**Comment by lynicidn** [comment]
@creocoder извини, что по русски, с английским, как ты уже понял, у меня туго, может мы не допонимаем друг друга. Но зачем городить костыли, когда можно `link` разделить, на простановку ключей (для hasOne) и сохранение. Не вижу тут трудностей или нарушения обратной совместимости, просто выделится еще 1 метод, просто для простановки ключей.
Вернусь к `save` в `link`, а что если я создал только что модель Field, и я хочу указать для вьюхи, что ее родитель Form, сейчас я делаю так:
```php
    public function setForm($form)
    {
        if ($this->isNewRecord) {
            $this->form_name = $form->name;
            $this->populateRelation('form', $form);
        } else {
            $this->link('form', $form);
        }
    }
```
Метод link на сегодняшний день практически бесполезен для связей-родителей (где hasOne не может вернуть null)

**Comment by lynicidn** [comment]
добавьте хотябы `except` для `validate`, как тут
https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L629

**Comment by creocoder** [comment]
@lynicidn `link()` делает ровно то что у него в описании, проставляет FK и сохраняет модель без валидации и справляется с этим на отлично. Править `link()` и как то разделять его не получится по причине BC, а также потому что не понятно что с ним всётаки не так. Сделайте более детальное описание проблемы.

**Comment by lynicidn** [comment]
@creocoder ну я же написал, как мне провалидировать foreign keys перед link он же будет пустым, исключать его из валидации - это разве не костыль?

**Comment by creocoder** [comment]
@lynicidn Валидировать foreign key нужно только в том случае, когда он поступает от пользователя или из недоверенного источника. В этом случае foreign key не будет пустым на этапе валидации. И это **единственный** случай когда валидация FK имеет смысл. Во всех остальных случаях валидация FK абсолютно бессмысленна. Если у вас FK пустой перед link,  это значит что FK не поступает извне и его валидация не нужна.

**Comment by creocoder** [comment]
@lynicidn 

У вас в правилах есть:

```
['form_name', 'required'],
['form_name', 'exist', 'targetClass' => Form::className(), 'targetAttribute' => 'name'],
```

У вас реально такое поле есть в форме? Если да, то на этапе валидации оно будет заполнено и проблем с его валидацией не будет. Если ситуация обратная и такого поля нет, то просто прекратите валидировать атрибуты, которые не требуют какой либо валидации и всё будет отлично.

**Comment by samdark** [comment]
@lynicidn может лучше с вопросами на форум, а не сразу в issue?

**Comment by lynicidn** [comment]
@creocoder спасибо
@samdark хорошо :) но вначале было предложение разделить простановку ключей и сохранение

**Comment by creocoder** [comment]
@lynicidn Что значит разделить простановку? Простановка это простой код плана:

**Comment by lynicidn** [comment]
@creocoder бывает составной первичный ключ, и для реюзабельности кода не охота привязываться к конкретному аттрибуты, так то и link логику можно реализовать через populateRelation, ручную простановку ключей и save

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1407
вот эту логику предлагал вынести в отдельный метод

**Comment by creocoder** [comment]
@lynicidn Вообще идея простановки FK она на самом деле хороша, но её не нужно реализовывать отдельным методом. Как мне кажется наиболее оптимально это будет работать таким образом:

```php
$model->relation = $relation;
```

При этом если есть сеттер для relation, то пользователь решил использовать свою логику.

**Comment by lynicidn** [comment]
ну да или так, собственно сейчас я и пишу сеттер, который и проставляет ключи, ну плюс еще делает populateRelation
