### ISSUE TITLE
AR:: validate and save

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#7378]
Situations for standard advanced app:
```php
$model = new User;
if ($model->validate()) { //https://github.com/yiisoft/yii2/blob/master/apps/advanced/common/models/User.php#L50
    $model->save(false); 
/*throw error:
 password_hash column can't be empty 
https://github.com/yiisoft/yii2/blob/master/apps/advanced/console/migrations/m130524_201442_init.php#L20 */
}
```

it's not correct behavior - if model validated then her should be saved.

As variant add `unsafe` param in validator.
```php
['password_hash', 'required', 'unsafe' => true]
```

**Comment by mdmunir** [comment]
To create new user, you must use `frontend\models\SignupForm` model.
`common\models\User` not designed for create or update user.
CMIIW

**Comment by lynicidn** [comment]
@mdmunir `frontend` ? u lost `back`, `api`, `console`
and how i should do documents for follow programmers ?

**Comment by lynicidn** [comment]
it field required, but her not add in rules ? why ?

**Comment by lynicidn** [comment]
$model->save() should return result, but in current behavior it throw exception

**Comment by mdmunir** [comment]
The point is, dont use `common\models\User` directly. Its used only for `yii\web\User::$identity`.
Create your own model for create, update or delete user.
After all, i am neutral :D ...

**Comment by samdark** [comment]
@lynicidn do you have time to submit a patch?

**Comment by lynicidn** [comment]
@samdark i think need discus for it. Many peoples says that it correct behavior

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/rest/CreateAction.php#L55
rest actiob not cover it situation. need add try...catch

**Comment by tom--** [comment]
what i'm interested in here is the validation rules for a model that takes no form input. it looks like an internal assertion to me (to ensure that a User with an meaningless state value is not saved to db). should demo code be using validation rules for internal assertions? would not beforeSave be a better place for such an assertion?

**Comment by samdark** [comment]
@tom-- the model would be used out of forms context anyway so I think it worth adding validation rules.

**Comment by lynicidn** [comment]
as example http://guides.rubyonrails.org/active_record_validations.html :
`
1.1 Why Use Validations?

Validations are used to ensure that only valid data is saved into your database.
`

**Comment by lynicidn** [comment]
Need test, but `scenarios` and `!attr` should solve it. I test it and wrtite here...

**Comment by lynicidn** [comment]
Yes it work for me. 
@samdark Need do PR for add rules in User model?
