### ISSUE TITLE
Incorrect timestamp inserted when using \yii\log\DbTarget with default log table schema on mysql

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#7384]
Values are rounded when sql is prepared

```
            $command->bindValues([
                ':level' => $level,
                ':category' => $category,
                ':log_time' => $timestamp,
                ':prefix' => $this->getMessagePrefix($message),
                ':message' => $text,
            ])->execute();
```

![qip shot - screen 569 22 02 15](https://cloud.githubusercontent.com/assets/2150916/6316139/0006ff14-ba2c-11e4-9566-cd886051bda0.png)

Dumping time shows that `$timestamp` passed to `bindValues` is correct - something like `1424554418.4581`

MySQL 5.5.41
mysqlnd 5.0.10

**Comment by samdark** [comment]
Which column type `log_time` is?

**Comment by samdark** [comment]
I think it's not only logging issue but behavior of PDO in general it couldn't properly bind float values so we should either use `PDO::PARAM_STR` or convert values to strings before binding.

**Comment by samdark** [comment]
@SDKiller can you check if the following helps?

```php
  ':log_time' => (string) $timestamp,
```

**Comment by SDKiller** [comment]
@samdark 

Converted `log_time` to `varchar` and casted `$timestamp`  to string - this helps.

**Comment by creocoder** [comment]
@SDKiller 

> Converted log_time to varchar

For what? This is bad idea.

**Comment by SDKiller** [comment]
@creocoder 

If you leave column type `float` - they are rounded anyway.

**Comment by samdark** [comment]
@creocoder this is PDO bug. It can't properly bind float values.

**Comment by qiangxue** [comment]
@samdark The original table schema was using INTEGER to store timestamp, which doesn't have this problem.

**Comment by creocoder** [comment]
@qiangxue I've checked all schemas now. It use `float`.

**Comment by creocoder** [comment]
For example:

```sql
drop table if exists `log`;

create table `log`
(
   `id`          bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `level`       integer,
   `category`    varchar(255),
   `log_time`    float,
   `prefix`      text,
   `message`     text,
   key `idx_log_level` (`level`),
   key `idx_log_category` (`category`)
) engine InnoDB;
```

**Comment by qiangxue** [comment]
I meant the code before this commit: https://github.com/yiisoft/yii2/commit/b8cb5e2a28ccbd60235eeded97838cc75063a386

**Comment by SDKiller** [comment]
@qiangxue 

But `log` operates `microtime`.
With `integer` precision will be lost.

**Comment by qiangxue** [comment]
True, but we are using integer in 1.1 and no one has complained about precision problem.

**Comment by creocoder** [comment]
So need to revert schemas like it was before.

**Comment by samdark** [comment]
No, we should not revert it. Half a second is very important for profiling.

**Comment by samdark** [comment]
I think correct fix is to add `double` to `Schema::getPdoType`:

```php
public function getPdoType($data)
{
    static $typeMap = [
        // php type => PDO type
        'boolean' => \PDO::PARAM_BOOL,
        'integer' => \PDO::PARAM_INT,
        'double' => \PDO::PARAM_STR,
        'string' => \PDO::PARAM_STR,
        'resource' => \PDO::PARAM_LOB,
        'NULL' => \PDO::PARAM_NULL,
    ];
    $type = gettype($data);

    return isset($typeMap[$type]) ? $typeMap[$type] : \PDO::PARAM_STR;
}
```

**Comment by samdark** [comment]
Hmm, according to `Command::bindValues()` implementation `double` PHP type should be bound as `PDO::PARAM_STR`.

**Comment by samdark** [comment]
I'd consider using `DECIMAL`.

**Comment by mikehaertl** [comment]
Could someone remind me, why `DATETIME` hast never been used for any timestamps? I mean, we talk about, well, date and time, and seem to avoid the obvious first choice.

**Comment by samdark** [comment]
Timezones.

**Comment by mikehaertl** [comment]
> timezones 

That never really convinced me. You're basically saying, that `DATETIME` is flawed and should not be used at all. Whereas I think, if the DBMS is configured to UTC you get pretty much the same result - using a datatype that is optimized to store date+time. To mit that `int` thing always felt like trying to solve a problem that really has to be solved in the DB layer.

**Comment by samdark** [comment]
That's too many IFs. It's not part of user application so we can't really force anyone to configure DB server to use UTC. In may cases it's not even possible.

**Comment by SDKiller** [comment]
Precision is important not only for profiling but also to order records.
I think that storing microtime as string is not a problem for the purpose of further processing of log records - with `fileTarget` we also have string values.

While storing it as `datetime` results additional conversions later, especially cumbersome if we have to operate microseconds.

**Comment by tecnologiaterabyte** [comment]
This would solve if we have a component that would specify what format the data will be saved in the database, many will say that is not the task of AR, but if we review all open issues of formatter most are cases of conversion.

**Comment by samdark** [comment]
I think column should be of double precision type. It's not currently there but I've pull requested adding it: https://github.com/yiisoft/yii2/pull/7446

**Comment by qiangxue** [comment]
Have you verified that using double would solve this problem?

**Comment by samdark** [comment]
@qiangxue yes.

**Comment by samdark** [comment]
@SDKiller fixed. You need to change column type to double.

**Comment by SDKiller** [comment]
@samdark 

I'll test it with `double` type in another environment a few hours later. 

As of now `varchar` column type works good enough for my purposes, no wish to make changes in almost finished project ;)
