### ISSUE TITLE
Feature update jquery-ui to jquery-ui-bootstrap.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#7385]
It would be interesting to update the widgets based on jquery-ui to jquery-ui-bootstrap which has better development and more updates also be designed on twitter bootstrap, used by default yii2-framework.

http://jquery-ui-bootstrap.github.io/jquery-ui-bootstrap/

Thks,

**Comment by samdark** [comment]
Yes but it's out of the core framework scope.

**Comment by tecnologiaterabyte** [comment]
Thanks for your reply, thought yii extension jui It was part of yii2-framework

**Comment by samdark** [comment]
JUI is but jQuery UI Bootstrap isn't JUI.
