### ISSUE TITLE
GridView Icons Broke After Rendering ActiveForm (Opera 12.16)

### ISSUE THREAD

**Issue by re1naldo** [yiisoft/yii2#7387]
I tried to render simple ActiveForm inside a Bootstrap modal and update GridView (on the same page) after user submits the form.

This is how I call Boostrap modal:

```
<?= Html::a('Create Car', '#', [
     'class' => 'btn btn-success',
     'onclick'=>"
            $('#car-modal').modal('show');
                
            $.ajax({            
                 type: 'POST',
                 cache: false,
                 url: '" .Yii::$app->urlManager->createUrl(['car/create']). "',     
                 success  : function(response) {                        
                     $('#car-modal .modal-body').html(response);
                }
            });
            return false;
    ",
]) ?>
```

Code for the form:

```
<?php $form = ActiveForm::begin(['id' => 'car-form']); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 150]) ?>

    <?= Button::widget(['label' => 'Submit', 'options' => ['class' => 'btn btn-success', 'id' =>'submit-button']]) ?>

<?php ActiveForm::end(); ?>

```

Form was rendered using renderAjax() method (from controller). When I tested it in Chrome, Firefox, IE, and Safari, it worked fine. However, the icons in GridView broke after the modal dialog was opened (ActiveForm was rendered) in Opera 12.16. Please see [this picture](http://rn0163.0fees.net/opera.png) for details (sorting icon disappeared, update & delete icons looked strange).

Is this Yii or Boostrap issue? Did I do anything wrong in rendering the form inside modal dialog?

Yii: 2.0.2
PHP: 5.5.11
Component: yii\widgets\ActiveForm

**Comment by SDKiller** [comment]
@re1naldo 
I had similar issues with images and bootstrap in FF.
Try to set image size explicitly in css - it may help.

**Comment by re1naldo** [comment]
@SDKiller
Thanks for the suggestion. Tried to set size for the glyphicon, but still got no luck. Sorting icon  disappeared, update & delete icons changed into strange form (like Chinese character).

**Comment by samdark** [comment]
Stange characters means no icon font loaded.

**Comment by re1naldo** [comment]
How to fix this issue? After the page was loaded, those icons still looked fine (which means icons were loaded at first). They broke after a modal dialog (with ActiveForm inside it) was opened.

My temporary solution is changing glyphicons in GridView with image. It seems to work without problem as far as I can see. Hopefully there is a better solution here.

**Comment by samdark** [comment]
Was the URL changed?

**Comment by re1naldo** [comment]
No, the URL was not changed.

**Comment by tecnologiaterabyte** [comment]
Your use pjax ?

**Comment by re1naldo** [comment]
@tecnologiaterabyte 
Yes, but the result was still the same after I removed Pjax. Things went normal when I removed the ActiveForm or replaced glyphicons with regular image.

**Comment by tecnologiaterabyte** [comment]
Check that this loading css files and order with firebug, it seems a problem with your AssetsBundles

**Comment by re1naldo** [comment]
CSS files were loaded when the page was opened at the first time. When opening the modal dialog, I only saw “yii.validation.js” and “yii.activeForm.js” in Network tab beside the request to the form. No additional CSS was loaded.

**Comment by tecnologiaterabyte** [comment]
On that page you load the AssetBundle Bootstrap.css in main.php ?

**Comment by re1naldo** [comment]
Like the other CSS files on that page, Bootstrap.css was loaded when the page was opened. I think they were published automatically by `AppAsset::register($this)`.

**Comment by re1naldo** [comment]
It's a shame, but I didn't realize how old my Opera was (I use Ubuntu repository and usually it will automatically update the softwares).

Anyway, just upgraded Opera to version 27 and the problem went away. Thanks for your time, everyone. Apologize for my foolishness.
