### ISSUE TITLE
limit() not work with hasMany() when using ActiveDataProvider

### ISSUE THREAD

**Issue by mathed4all** [yiisoft/yii2#7388]
view file as follows:
   
             <?= GridView::widget([
                    'dataProvider' => new ActiveDataProvider([
                        'query' => $user->getProblems()->limit(10),
                    ]),
                    'columns' => [
                    'id',
                    ]
                ]); ?>

Model file as follows:

    public function getProblems()
    {
        return $this->hasMany(ProblemRecord::className(),['created_by'=>'id']);
    }

the gridview works but the limit not worked.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/data/Pagination.php#L210

**Comment by mathed4all** [comment]
adding
                        'pagination' => false,
solve the problem, i think it's a bug.

**Comment by cebe** [comment]
If you want to use a fixed number of records you have to disable pagination which otherwise would choose the limit for you. This is expected behavior.

**Comment by Trimod** [comment]
If you still want to paginate limited data, you can use ArrayDataProvider instead.

 return new yii\data\ArrayDataProvider([
            'allModels' => $query->limit(5)->all()
        ]);

**Comment by cebe** [comment]
the better solution would be to set the totalCount of records manually.

**Comment by Trimod** [comment]
I tried, but in my case it only changes the total count in response headers, but not the amount of data returned.
