### ISSUE TITLE
Yii2-authclient, Google client: "Missing required parameter: refresh_token"

### ISSUE THREAD

**Issue by ufocoder** [yiisoft/yii2#7389]
I use Google client class, but after my Google token is expired Yii2-authclient extension try to refresh it but it get a error in
@vendor/yiisoft/yii2-authclient/BaseOAuth.php  at line 205 

```php
Exception – yii\authclient\InvalidResponseException

Request failed with code: 400, message: {
    "error" : "invalid_request",
    "error_description" : "Missing required parameter: refresh_token"
}
```

**Comment by klimov-paul** [comment]
How exactly have you attempted to refresh the token?
How you compose argument for `BaseOAuth::refreshAccessToken()`?

Note: If you save access token somewhere inside database, you should save all its params, amoung which there are those needed for token refreshing.

**Comment by klimov-paul** [comment]
Sinse no response have come, I suppose my suggestion was correct.

**Comment by burlakko** [comment]
emmm.. @klimov-paul I suppose it wasn't.
Here is a request to refresh access token https://developers.google.com/identity/protocols/OAuth2WebServer#refresh
```
    POST /oauth2/v3/token HTTP/1.1
    Host: www.googleapis.com
    Content-Type: application/x-www-form-urlencoded
   
   client_id=8819981768.apps.googleusercontent.com&
   client_secret={client_secret}&
   refresh_token=1/6BMfW9j53gdGImsiyUH5kU5RsR4zwI9lUVX-tqf8JXQ&
   grant_type=refresh_token
```
It seems that google returns refresh_token parameter only after first login from current application.
So $client->refreshAccessToken() method will fetch a valid refresh_token to request only after the first login.
I see two possible solutions here.
1. Save refresh_token in database after the first login, but not in session.. or not only in session.
2. Comment refreshing part in restoreAccessToken():
```
protected function restoreAccessToken()
    {
        $token = $this->getState('token');
        //if (is_object($token)) {
        //    /* @var $token OAuthToken */
        //    if ($token->getIsExpired()) {
        //        $token = $this->refreshAccessToken($token);
        //    }
        //}
        return $token;
    }
```
and check token validity manually:
```
$accessToken = $client->getAccessToken();
if (!is_object($accessToken) || !$accessToken->getIsValid())
    // send user to google login
```
