### ISSUE TITLE
Formatter->asCurrency() not support netheir config['language'] nor config['formatter']['locale']

### ISSUE THREAD

**Issue by hungtrieu** [yiisoft/yii2#7391]
I want to format the price, i.e: 150.000 đ; The yii\i18n\Formatter is very helpful, but it has a minor issue: it alway put the currency code before the number, so I only get đ 150.000 when call it. Please modify this function to make currency code display depend on config['language'] or config['formatter']['locale']. I don't want to use raw php function or hack the core in my case :)

Thanks.

**Comment by cebe** [comment]
how did you set locale? and to which value? Note that for currency to work correctly you have to include a country code, language is not enough.

**Comment by hungtrieu** [comment]
I found the problem. 

I had not install php-intl extension, so the Formatter->asCurrency() goes to else case of ($this->_intlLoaded) (see in https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L906 for more detail)

The else calse return this: $currency . ' ' . $this->asDecimal($value, 2, $options, $textOptions); (https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L930) That's why I alway receive "đ 150.000,00" instead of "150.000,00 đ"

I've installed php-intl extension then everything is fine. With this config:
'formatter' => [
            'dateFormat' => 'dd.MM.yyyy',
            'decimalSeparator' => ',',
            'thousandSeparator' => '.',
            'currencyCode' => 'VND',
       ],

the Formatter->asCurrency() return "150.000,00 đ" like I need.

Thanks.
