### ISSUE TITLE
Minify registerJs and registerCss input

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#7393]
Would this be worth a PR?

I'm thinking something like [JSMin](https://code.google.com/p/minify/source/browse/min/lib/JSMin.php) could be used to minify inline scripts.

As `registerJs` uses a key to store the script in the `View` array this key could be used as the name of the cached file.

**Comment by samdark** [comment]
I don't think it worth doing. Registered chunks of JavaScript are usually quite small and won't affect loading time much, especially if page is GZipped.
