### ISSUE TITLE
Foreign key column name in relation treated as string

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#7398]
Having a relation defined as in the following example the column name **journalID** will be quoted with '' instead of  `` and therefore handled by the database handled as a string.   

```php
public function getBuchungen()
    {
        return $this->hasMany(Buchung::className(), ['finanzkontoID' => 'id'])
        ->join('INNER JOIN', Journal::tableName(), ['journal.id' => 'journalID']);
    }
```

**Comment by Alex-Code** [comment]
Try
```
public function getBuchungen()
    {
        return $this->hasMany(Buchung::className(), ['finanzkontoID' => 'id'])
       ->join('INNER JOIN', Journal::tableName(), ['journal.id' => new \yii\db\Expression('journalID')]);
    }
```

**Comment by twinni** [comment]
Your suggestion sets the quotes now correct. I'm wondering what the rules are treating a string as a column name or as an string. This behaviour looks strange to me.

**Comment by cebe** [comment]
@twinni what you are specifying in the third argument of join() is a condition which is according to its documentation `'key' => 'value'` where value is a column name and value a value (string) to compare with.
