### ISSUE TITLE
Behaviors cannot override __get and __set for values in an ActiveRecord Model

### ISSUE THREAD

**Issue by synatree** [yiisoft/yii2#7400]
I think this is probably a bug.

If I create a trivial behavior, as such:
```php
use Yii;
use yii\base\Behavior;
class TrivialBehavior extends Behavior
{
    public $owner;
    private $attribute = 'notinmodel';

    public function canGetProperty($name, $checkVars = true)
    {
        return true;
    }

    public function __get($name)
    {
        if ($name == $this->attribute) {
            return "Fake Value";
        }
        return "Real Value Plus Extra Stuff " . parent::__get($name);
    }
}
```

I would expect that I would be able to decorate a real value from the model, but in fact, this never happens.  If an attribute exists in the model, the behavior canGetProperty and __get will never be fired.

**Comment by cebe** [comment]
how do you try to access the property?

**Comment by synatree** [comment]
From controller:
```php
$model = $this->findModel($id);
$model->ensureBehaviors();
Yii::info($model->notinmodel);
Yii::info($model->realvalue);
```

**Comment by creocoder** [comment]
@synatree Do you have `realvalue` inside owner?

**Comment by synatree** [comment]
realvalue is an attribute in the activerecord, yes.  Behavior is bound to activerecord via behaviors().

**Comment by cebe** [comment]
__get() is to catch non existing properties, it will only be called when the attribute does not exist.

**Comment by synatree** [comment]
isn't the purpose of canGetProperty to tell which attributes are to be retrieved from behavior?

**Comment by cebe** [comment]
yes but only those who do not exist in the main class can be overridden by behaviors. Yii is using __get() for this and __get() only gets called on non-existing properties.

**Comment by synatree** [comment]
Is there another mechanism I should be using to change values coming from the model transparently?

**Comment by cebe** [comment]
depends on what you want to do, currently it is not possible to overwrite setting and getting of normal attributes via behavior.

**Comment by creocoder** [comment]
> currently it is not possible to overwrite setting and getting of normal attributes via behavior.

Moreover wish to make is possible is wrong )

**Comment by synatree** [comment]
I don't know about that.  My use case was to create a behavior that would protect a model from being updated after a particular value was set.  I wanted to make the model read-only, in other words.  My implementation works (thanks to @cebe and @creocoder for your help), though not the way I initially intended it to work, because of the limitations.

https://github.com/synatree/yii2-readonly-behavior
