### ISSUE TITLE
new advanced app

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#7402]
![Ibug install](http://storage1.static.itmages.ru/i/15/0223/h_1424724318_5272614_51e94a8ba4.jpeg)

**Comment by Faryshta** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-installation.html

**Comment by samdark** [comment]
Have you installed fxp plugin globally?

**Comment by a-komarev** [comment]
That hapenned yesterday massively.
In console run:
```
composer global require "fxp/composer-asset-plugin:1.0.0"
```
delete all data in `./vendor` folder and run again:
```
composer update
```

**Comment by lynicidn** [comment]
@samdark yes, it's not first project, but basic (not dev) installed correctly.

**Comment by cebe** [comment]
working fine for me here with basic and advanced app. Which composer version are you using?

**Comment by lynicidn** [comment]
@cebe thx for answer, i solve problem: `rm -rf ~/.composer/cache`. I don't understand it behavior, but it work

**Comment by lynicidn** [comment]
use `composer clearcache`. If u remove ~/.composer/cache u should reinstall `fxp/composer-asset-plugin:1.0.0`

**Comment by yokoshima1** [comment]
what made it work for me is in fact:
`composer global require "fxp/composer-asset-plugin:~1.4"`

I then removed composer directory and composer.lock

then rerun `composer install`
