### ISSUE TITLE
[ENH] TYPE_PK and TYPE_BIGPK constant

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#7403]
Here : 

https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L25

Primary key should be unsigned because it will never be negative.

Same case in oci, mssql, cubrid and sqlite.

**Comment by Faryshta** [comment]
#1032 here is the yii2 position about it. I didn't agreed at first but I agree now

**Comment by pana1990** [comment]
Of course, thanks @Faryshta  ;)
