### ISSUE TITLE
BaseActiveRecord::findOne and phpdoc

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#7404]
why here https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L97 write that return static, may be need fix to static|null ?

**Comment by cebe** [comment]
fixed, thanks!

**Comment by lynicidn** [comment]
@cebe thx for you

**Comment by ShNURoK42** [comment]
@cebe, after this fix, autocompled in my code not work.

```php
$model = Model::findOne(['id' => $id]);
$model->name = $someName;
```
$model->name defind as error in PhpStorm 8.0.3 1139.1348

Only I have this error? If i delete "|null" it's works ok.

**Comment by lynicidn** [comment]
yes, accept. self|null fix it

**Comment by lynicidn** [comment]
and apparently so was such a comment

**Comment by ShNURoK42** [comment]
In my case "self|null", not fix this.

**Comment by cebe** [comment]
which version of PHPStorm are you using?

**Comment by lynicidn** [comment]
@cebe 8.0.1
in current case `static|null`
```php
$model = my\Model::findOne($id);
$model->[here autocomplete to current controller]
```

**Comment by lynicidn** [comment]
http://blog.jetbrains.com/phpstorm/2014/07/phpstorm-8-eap-138-1161/

```
Fluent-style chaining type loss with return this/static fixed, and many other PHP language related issues are resolved
```

**Comment by ShNURoK42** [comment]
@cebe PhpStorm 8.0.3 1139.1348 it's a last build.

**Comment by lynicidn** [comment]
@ShNURoK42 u have analog behavior https://github.com/yiisoft/yii2/issues/7404#issuecomment-75837170 ?

**Comment by ShNURoK42** [comment]
@lynicidn yes, with ```static|null``` autocomplete show current controller.

**Comment by Faryshta** [comment]
does yii2 has official support for IDE's or errors found on IDE's?

**Comment by cebe** [comment]
This looks like a bug in PHPStorm then, can you report an issue over there?

**Comment by lynicidn** [comment]
i think it https://youtrack.jetbrains.com/issue/WI-24216

**Comment by lynicidn** [comment]
as i write https://youtrack.jetbrains.com/issue/WI-19953#comment=27-606838 it work for me
