### ISSUE TITLE
Optional authentication in REST

### ISSUE THREAD

**Issue by a-komarev** [yiisoft/yii2#7405]
I've faced situation when single action should be available to guest users and to authenticated users.
What is a best way to solve it?
First idea - implement new attribute `optional`:
```
'authenticator' => [
    'class' => CompositeAuth::className(),
    'optional' => ['feed', 'feed-item'],
    'authMethods' => [
        HttpBearerAuth::className(),
    ],
],
```
Methods `actionFeed` and `actionFeedItem` will perform Bearer authentication if header is passed. Otherwise authentication should be ignored and no errors should be raised.
Thats needed because application's pages for guest & authenticated users are nearly same, excluding a bit of additional data for authenticated guys.

**Comment by fernandezekiel** [comment]
@a-komarev  does your specific action handle authenticated and guest users differently?

**Comment by a-komarev** [comment]
@fernandezekiel authenticated users gets additional data in results.
```
[
    {
        "message": {
            "body": "First message",
            "favorite": true,
            "created_at": "2015-02-23 00:23:52"
        }
    },
]
```

Guest users are getting `favorite` attribute 'false' all the time, and authenticated users will get this value accordingly state in database.

**Comment by fernandezekiel** [comment]
i see, i think though we can upgrade that to callable that has `$action` in the argument
```
'optional' => function ($action) {

}
```

**Comment by a-komarev** [comment]
@fernandezekiel how will it help us?

**Comment by fernandezekiel** [comment]
@a-komarev  sorry just throwing ideas out there,

**Comment by jpodpro** [comment]
same situation here - it's a very simple scenario: a public page shows a list accessible to anyone. however the user is considered a guest even though they sent the bearer token. shouldn't yii process the token if it is sent? how else does a user remain "logged in" through out public and private pages on the site?

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/035a9ce0a8642dc1218f4b5d587dfde4daa382f2
