### ISSUE TITLE
Depends for behaviors

### ISSUE THREAD

**Issue by sensa-ua** [yiisoft/yii2#7406]
I want to be able to specify dependency list in Behavior - inherited class, so at first it will look from the 
declared behaviors, and if no match found it will attach unnamed behavior. Second - I will sure that behaviors will be initialized in proper sequence, so one behavior can rely on dependent behaviour features which was properly initialized before. Normally behavior has required params, and I should be able to specify desired configuration in the dependency list. So I will have ability to reuse code of behaviors from other behaviors without need to duplicate code.

An example:
class Product has behaviors:

CleanRelated:  'managedRelations' => ['productTranslations', 'tags', 'options', 'prices']
it will automatically cleanup all relations specified with public property

Localized: 'localizedRelations' => [['productTranslations' => 'i18n'],]
it will genereate virtual relation 'i18n' which will select one record from productTranslations based on language.

Sluggable => [sluggableAttribute: productTranslations.name]
it will take attribute from the config and generate slug based on field 'name' from productTranslations relation. It will also provide virtual Relation called 'slugs' and link it with 'manageRelations' relations list: $owner->manageRelations[]= 'slugs'. To make it possible need to ensure that CleanRelated attached before Sluggable.
It will also add 'slugs' to localizedRelations by $owner->localizedRelations[]=['slugs'=>'slug_i18n'], so we need to ensure that Localized relation will be attached if it's not in the list, and will generated in proper sequence so we don't need to care about sequence.

I think adding this feature will thremendously extend Behavior driven metaprogramming capabilities of the YII2 framework.

**Comment by samdark** [comment]
Are you adding behaviors dynamically?

**Comment by klimov-paul** [comment]
Behaviors are ment to be independent, and should not have a coupling between each other.
Code duplication can be reduced using regular class extending or traits.
Since behavior usually have some configuation parameters, creating dependency between them will go nowhere: how correspondence of the parameters should be maintained then?
