### ISSUE TITLE
CompositeAuth::authenticate bug

### ISSUE THREAD

**Issue by m8rge** [yiisoft/yii2#7409]
Error in following code while executing "bug/a" route

```php
<?php

namespace api\modules\v1\controllers;


use yii\filters\auth\HttpBearerAuth;
use yii\rest\Controller;

class BugController extends Controller
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator']['authMethods'] = [
            HttpBearerAuth::className(),
        ];
        return $behaviors;
    }

    public function actionA()
    {
        $this->runAction('b');
    }

    public function actionB()
    {}
}
```

In `runAction('b')` `CompositeAuth::authenticate` trying to create objects from `CompositeAuth::authMethods` configs, but after `actionA()` they contains objects.

> php5.6, yii2.0.2

**Comment by fernandezekiel** [comment]
is this actually an issue? this is expected because `actionB` is running in the same controller instance as `actionA`

**Comment by m8rge** [comment]
@fernandezekiel when I execute `runAction`, I expect to run action, not to fail in exception =)

**Comment by fernandezekiel** [comment]
let me try on mine

**Comment by fernandezekiel** [comment]
yeah you're right, the solution looks easy though, `CompositeAuth::authenticate` should just check if the auth objects already have been instantiated

**Comment by samdark** [comment]
@fernandezekiel do you have time to work on a unit test and a pull request for it?

**Comment by fernandezekiel** [comment]
@samdark  sure i'll make one this week
