### ISSUE TITLE
Get rid of configuration properties of behavior in host component

### ISSUE THREAD

**Issue by sensa-ua** [yiisoft/yii2#7411]
Behaviors should declare public properties for configuration purposes. Later all public properties and methods became available from main component. 90% of the properties ARE NOT SUPPOSED to become exposed. Please limit the ability of extension of Components functionality by only publc methods. Then the public properties will be exposed in traditional way by definition getXXX() and setXXX() public methods.

**Comment by samdark** [comment]
Any examples?

**Comment by sensa-ua** [comment]
I have just recently exposed https://github.com/sensa-ua/yii2-softdelete repository.
The public properties 

public $attributes = [];
public $deletedAttribute = 'deleted';.

serve only for cunfiguration purposes, I don't want to garbage host model with them.
I propose to change Componet's code to prevent exposion of properties of behaviors at all.

It is still possible to use get/set methods to implement virtual properties.

**Comment by qiangxue** [comment]
Sorry, we will not make this change as it not only breaks BC but also lacks sufficient argument in doing so.

**Comment by sensa-ua** [comment]
There are no way to control visibility scope of variable defiened from the behavior. If 2 variables in different behaviors has name conflict, publically accessible 1) one from model, 2) the one from first behavior in list. Later on, new behavior could be added, or the name will later added to the original model - this will change behavior of the composite object and require debugging and fixing of the code. 

Guys, what you're doing is Model Attribute Naming Hell.

**Comment by sensa-ua** [comment]
If this problem would be fixed in the behavior code - I would just fork the behavior hierarchy from the top in my project, framework support the very few behaviors and it's easy to move them in the project. BUT this problem can be fixed in only Component code ((( and this is deeply integrated into the framework.

**Comment by qiangxue** [comment]
We do not want to differentiate properties defined via getter/setter and member variable.

Yes, the current implementation does make *all* properties and methods of behaviors to be "injected" into the owner component. This is a known issue. It is so because we don't want to sacrifice performance. I just came up with an idea that could solve this problem nicely. Will see if it is true or not.

**Comment by sensa-ua** [comment]
By reducing the number of lookups (elimination for lookup for attributes) performance definitelly should not degrade - I believe it should even grow up slightly.

**Comment by creocoder** [comment]
Behaviors can be complettely replaced by traits in 100% cases. So since we can't change anything inside 2.0 due to BC i suggest to eliminate this old approach and replace it with traits. Yes i know that when Yii 2 fastly move from 5.3 to 5.4 it was not done, moreover there was opinion that behaviors can't be replaced by traits. Now its clean thats its possible.

**Comment by cebe** [comment]
@creocoder how would you detach a trait on runtime?

**Comment by creocoder** [comment]
@cebe There is **lot** of approaches how to do that. What is detaching? Technically its unsuscribe handlers from events. Thats all. This can be done begining from call trait method and finish with other techniques which detach Trait handlers from events.

**Comment by creocoder** [comment]
@cebe Simple example:

```
$this->detachNestedSets(); // special method name by convention, simplest method
$this->detach('NestedSetsTrait'); // more complex solution
```

**Comment by qiangxue** [comment]
@creocoder Please see discussion here: https://github.com/yiisoft/yii2/issues/1053

**Comment by creocoder** [comment]
@qiangxue I read it carefully. And main thing is

> The issue of name conflict in traits is much more severe than that in behaviors, which almost makes traits not truly usable. For example, if trait A and B both define private property $a but with different default values, you will not be able to use both A and B in the same class because PHP will report an error. The deeper issue is that A and B are likely to interfere with each other without actually knowing that. Please correct me if I understand traits incorrectly.

Sorry, but you come to wrong conclusions. First of all traits **should never** contains any properties. There is another approach for configuring. Look Laravel approaches for example. There is no behaviors and traits everywhere and everybody happy. I'll show approach in short:

```php
class NestedSetsBehavior extends Behavior
{
    public $leftAttribute = 'lft';
    public $rightAttribute = 'rgt';
}
```

become

```php
trait NestedSetsTrait {
    public function leftAttribute()
    {
        return 'lft';
    }

    public function rightAttribute()
    {
        return 'lft';
    }
}
```

Second, methods conflicts make behaviors unusable too. But in case of traits we have native php error in that case. But main thing with strong guide about traits building conflicts is just fantastic case.

And third, just compare behavior VS trait by speed. Last time i made comparsion it shows it 5+ times faster on concrette behavior => trait transformation. Moreover... 10 behaviors VS 10 traits and we can talk about dramatical perfomance increase.

Forth. Attaching and detaching is about events only and it possible with traits. It depends on event system implementation. Moreover traits just kill behaviors in that aspect too. One method inside `init()` vs manual `events()` configuring. Traits subscribe itself just by call its method. Such methods have simple and reliable conventions. Like `attachTraitNameHandlers()`. Same thing with detaching.

After php 5.4 out nobody in PHP world use approach like behaviors more expect us. Please consider to think about that again with correct conclusions. There is always solutions and traits kill behaviors in each aspect: 1) perfomance, 2) event handling, 3) configureability, 4) IDE autocomplete.

**Comment by creocoder** [comment]
@qiangxue I need to explain more about traits **configureability* and why it works. For example:

```php
trait NestedSetsTrait {
    public $leftAttribute = 'lft';
    public $rightAttribute = 'rgt';
}
```

```php
Category extends ActiveRecord {
    use NestedSetsTrait;

    public $leftAttribute = 'my_lft';
    public $rightAttribute = 'my_rgt';
}
```

This will lead to **php fatal error** and this is correct. Everything works like excepted. Traits was born for other configuring approach and its:

```php
trait NestedSetsTrait {
    public function leftAttribute()
    {
        return 'lft';
    }

    public function rightAttribute()
    {
        return 'rgt';
    }
}
```

```php
Category extends ActiveRecord {
    use NestedSetsTrait;

    public function leftAttribute()
    {
        return 'my_lft';
    }

    public function rightAttribute()
    {
        return 'my_rgt';
    }
}
```

Everything works like a charm! This is how that should be done.

**Comment by creocoder** [comment]
@qiangxue As bonus (small on background of others huge bonuses) traits complettely solved troubles described in that issue due to it configuring approach. If you still see troubles when traits can't replace behaviors I'll be very surprised )

**Comment by qiangxue** [comment]
@creocoder If you read carefully about that issue, you should find I'm not a proponent of behaviors. So you don't need to convince me. I drew the conclusion mainly because many users still want Yii1 behaviors and we couldn't find a way to replace it using traits. If you find such a way, please feel free to propose a "complete" solution and code example.

BTW, regarding your conclusion "First of all traits should never contains any properties", I think it's too arbitrary. When implementing some complex traits, inevitably you would need to have some variables shared among different methods (just like normal class members).

**Comment by sensa-ua** [comment]
I'm not very familiar with traits feature, but on my opinion behaviors have way much higher potential of code reuse comparable to traits.

**Comment by SamMousa** [comment]
Wouldn't it be possible to override canGetProperty and related methods in the behavior?

        public function canGetProperty($name, $checkVars = true)
        {
            return false;
            // Original:
            return parent::canGetProperty($name, $checkVars); 
        }

**Comment by dynasource** [comment]
@SamMousa shows the answer to the original problem. If you do not want to expose behaviors logic, you can use the canGetProperty & canSetProperty methods.
