### ISSUE TITLE
Concatenation vs templating

### ISSUE THREAD

**Issue by tsvetann** [yiisoft/yii2#7413]
I see a lot of concatenation in the code such as:

``` php
echo " done (time: " . sprintf('%.3f', microtime(true) - $time) . "s)\n";
```

I find the above code not easy to read. Why don't we use the available templating provided by (s)printf such as

``` php
printf(" done (time: %.3f s)\n", microtime(true) - $time);
```

This way we eliminate the `echo` and the exact string is more readable

**Comment by klimov-paul** [comment]
I assume you refer to `yii\db\Migration` and `yii\mongodb\Migration`.
I suppose `echo` at these classes should be removed indeed, but in different way. Like we did at #4791.

**Comment by tsvetann** [comment]
Yes the copy is from those classes but examples may exist elsewhere too. So my point is more general one.

Thanks for your prompt reply @klimov-paul

**Comment by samdark** [comment]
Regarding the rest it should be checked in each individual case.
