### ISSUE TITLE
Consider adding client side validation filter

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#7415]
> We may consider adding `filter` and `filterClient` to `Validator`.
> https://github.com/yiisoft/yii2/commit/57c298a5237c36efe8b2d435d8fc1fc400d61399#commitcomment-9883682

**Comment by lowap** [comment]
Hi, I'm looking forward to be able to use this! :)

**Comment by samdark** [comment]
Won't be implemented in 2.0.
