### ISSUE TITLE
Could not read image from resource Imagine.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#7416]
Simple Example yii\imagine\Image:

    <?php

        use yii\imagine\Image;

        Image::thumbnail(Yii::getAlias('@webroot/imagenes/usuarios/profile/30/perfil_google.jpg'), 120, 120)
        ->save(Yii::getAlias('@webroot/imagenes/usuarios/profile/30/thumb-test-photo.jpg'), ['quality' => 80]);
    ?>

![error_imagine](https://cloud.githubusercontent.com/assets/4957021/6349135/85e198fa-bbf9-11e4-987c-f833d351e3db.png)

Note: Work Fine Linux, Not Works Windows.

**Comment by cebe** [comment]
looks more like a problem with Imagine than with yii... Are you sure all necessary php extensions are installed?

**Comment by tecnologiaterabyte** [comment]
hi @cebe i install imagik, gd.

Work Captcha con Imagine.

![web_01](https://cloud.githubusercontent.com/assets/4957021/6349407/509362ca-bbfc-11e4-841c-24ea6aa9bcb6.jpg)

![imagick](https://cloud.githubusercontent.com/assets/4957021/6349428/88571e40-bbfc-11e4-952a-d37458e331e1.jpg)

Would fail to install another extension.

**Comment by tecnologiaterabyte** [comment]
Solved , add jpg support.
