### ISSUE TITLE
Common layouts in the advanced template

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#7418]
Hello,

I'm trying to use common layouts with the advanced template. I can do this in the controller:
```php
public $layout = 'layoutName';

public function init()
{
   $this->module->layoutPath = 'risos';
}
```
But it would be nice to just do: `public $layoutPath = 'risos';`.

**Comment by cebe** [comment]
How do you expect a module's property to change when you set it in controller?

**Comment by llfm** [comment]
I want to tell the controller, that my `$layout` isn't in the folder that it [think](https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L478) it's.

**Comment by llfm** [comment]
Options:
- add new var + change the way the controller reads the layout path.
  - Controller with a custom layout path.
- check if `$layout` contains a full path.
  - Multiple custom layout paths.

---
The `Module` already does something like this: `$this->setLayoutPath(..)`. Somewhat related to [this](https://github.com/yiisoft/yii2/issues/5529) in the terms that it shouldn't be a property in order to make it more "easy".

**Comment by lynicidn** [comment]
`@app/view/layouts/main` should work for all app https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L359

**Comment by qiangxue** [comment]
>  want to tell the controller, that my $layout isn't in the folder that it think it's.

Use path alias then.

It doesn't make sense to add `layoutPath` to controller in general because `layoutPath` is usually a concept at a level higher than individual controllers.

**Comment by llfm** [comment]
Agree. I missed [this](https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L473) line. Thanks.
(Perhaps add to some doc, that a alias is required to change the `layoutPath`)
