### ISSUE TITLE
Why we should use Events?

### ISSUE THREAD

**Issue by airani** [yiisoft/yii2#7421]
Hi everyone,

I have a question about Events concept. Why we should use Events while we can override methods like afterSave() or afterDelete() .

Or when we should use Events? if you may describe more to me about this concept in Yii2.

**Comment by klimov-paul** [comment]
@airani, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
