### ISSUE TITLE
DataProvider items are showing wrong with hasMany joinWith

### ISSUE THREAD

**Issue by relaxpor** [yiisoft/yii2#7424]
Let says, I have 2 tables `ItemBook` and `ItemBookTags`.
`ItemBook` has relation one-to-many with `ItemBookTags`.

User can search keyword from `itemBook` anad `ItemBookTags` so, in my `ItemBookSearch` class, i implement this method.

```
public function searchBookNameOrAuthorOrIsbnAndTag($params){
        $query = ItemBook::find()->joinWith(["itemBookTags"]);
        /* @var $query \yii\db\ActiveQuery */
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        die(var_dump($dataProvider->count));
}
```

However, from this method, the output is show 17 on page 1
and show 20 on page 2
and show 12 on my last page.

This is my `ItemBookTags` Table data.
![image](https://cloud.githubusercontent.com/assets/2979072/6352372/b5248188-bc74-11e4-8eca-f30ea2fe6da9.png)

I think there must be a problem with counting the left join has many relation ship.
Should it show 10 items on page 1?

**Comment by fernandezekiel** [comment]
don't forget to add a `groupBy` clause when you are dealing with something like this

**Comment by relaxpor** [comment]
Okay... groupBy is work like magic... Sorry for my mistake.

**Comment by BenasPaulikas** [comment]
How does groupBy help in this case ?

**Comment by dhruten** [comment]
May be group by like below could help :
$query = ItemBook::find()->joinWith(["itemBookTags"])->groupBy(['item_id']);
