### ISSUE TITLE
How to remove the filter in GridView header

### ISSUE THREAD

**Issue by p4scu41** [yiisoft/yii2#7426]
Hello.

I want to remove the filter from the header in GridView. I am trying with: 'layout' => "{summary}\n{items}\n{pager}", but it doesn't work.

 
![9666db3bbf1fb83f935b0f25c6968039](https://cloud.githubusercontent.com/assets/1633236/6355798/680b86ae-bc1e-11e4-8a52-161e5900dc89.png)

**Comment by llfm** [comment]
Just remove it. http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#filtering-data
Use Yii forum for asking questions.

**Comment by chitwarnold** [comment]
Just hide omit the filterModel config item from your gridview constructor

	<?= GridView::widget([
			    'dataProvider' => $dataProvider,
			    // 'filterModel'  => $searchModel,
			    'columns'      => [
					.....
				]
			]);
		?>

**Comment by koderium** [comment]
sdf

**Comment by chirag-prajapati-2705** [comment]
You shoud hide the filter model than your filter will be remove.Please check the below code
 <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'post_id',
            'post_title',
            'post_description:ntext',
            'user_id',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

**Comment by MissSahito** [comment]
I was also searching for this. thanks I just removed it.
