### ISSUE TITLE
Asset bundles behind load balancer with CDN

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#7441]
This seems to be a vey lightly touched scenario,however, I am dealing with multiple Yii2 servers behind a load balancer topped off with a CDN which caches the contents of each node.

I am finding that I am actually getting problems due to how the asset manager uses mtime to name asset folders, this is causing the compressed assets (css and js) on each server to not match due to having different text in them and so errors occuring on caching of some servers at times causing degraded user experience.

I cannot control the CDN to cache over a specific connection, it just calls up the static file straight from the load balancer when it is requested.

After quite a bit of searching around this scenario seems to not really be thought about when developing the assets. The closest I have found is some having made a version based asset manager that you need to manage manually.

What has been decided on this subject? Should I implement my own asset manager which most likely stores a common key between the servers based upon the first server in the group or has there been some thinking of supporting this within Yii2 core?

**Comment by samdark** [comment]
Are you referring to asset console command? It uses md5 hash, not modification time.

**Comment by klimov-paul** [comment]
Using Amazon Cloud you should consider uploading compressed CSS and JS files to the single CDN server instead of relying on EC2 instances for this.
Then you should modify the compression target assets to use CDN URL as `baseUrl`.

**Comment by Sammaye** [comment]
No the asset console command is related but what I am taking about is the:

    /assets/456gfd/

folder path that actually goes into the css and js files

**Comment by Sammaye** [comment]
@klimov-paul  Ok Kool thanks. Of course the system I use is slightly different.

It essentially caches my data by request.

So for example I have a file in my CSS of:

    ../assets/45/glyphicons.woff

and when I call:

    cdn.site.com/assets/45/glyphicons.woff

it actually caches the first url.

It is not a CDN I have control over as such.

**Comment by klimov-paul** [comment]
The only good way is usage of the central server like Amazon S3 for the asset files storage along with the corresponding modifications at asset bundles configuration.
I am unsure if we can make something to resolve problems related to load balancer usage.

**Comment by Sammaye** [comment]
Indeed, it seems I will have to make this relatively customised. Any kind of work around is probably too custom for Yii2 core really

**Comment by Sammaye** [comment]
Since this comes very high on Google search result, if not first, for this problem I will describe how I ended up using Yii here.

The way I did it was to actually have the load balancer/a control server prepare the Yii site by doing the asset compression and init commands etc and then just copy the files onto each of the app servers.

This meant that as my CDN, which is request based, went to find a file behind the load balancer it wuld alwasy get the same file over and over and not a file uniquely identified for that app sever under the load balancer.

**Comment by samdark** [comment]
Could be related: http://yii2-cookbook.readthedocs.org/structure-asset-processing-with-grunt/

**Comment by Sammaye** [comment]
Indeed similar though it doesn't propogate to multiple app servers, it is mostly a deploy script for a singular server. I used phing to solve to sovle my problem

**Comment by samdark** [comment]
@Sammaye it depends on how you configure it. Example if for a single server but you could do virtually anything in such way.

**Comment by klimov-paul** [comment]
Relates #9245
