### ISSUE TITLE
Why do we have constants in index.php

### ISSUE THREAD

**Issue by tsvetann** [yiisoft/yii2#7442]
I can see the following constants in index.php:
```php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```

I assume because of these constants index.php is put into .gitignore file? Is there a compelling reason not to move these constants into config/bootstrap.php and require config/bootstrap.php on top?

**Comment by samdark** [comment]
You mean advanced application template? Yes, index files are in ignore because of constants mainly.

**Comment by samdark** [comment]
What's the problem with it? These can't be used w/o running init once anyway because of missing config files.

**Comment by mikehaertl** [comment]
@tsvetann I had the same concerns like you. Having these constants there doesn't feel right to me either, as most real life apps `index.php` will life in your repository, so you can't easily override `YII_DEBUG` without the danger of accidentally committing the changed `index.php`. I've created my [own app template](https://github.com/mikehaertl/yii2-base-app) that adresses these issues. It's a mix between yii2's base app (too simple) and advanced app (way to complex for my taste). Maybe it's an option for you.

**Comment by tsvetann** [comment]
@mikehaertl I am just starting with Yii2 so don't want to make architectural experiments at this point.

@samdark what about including the local files as part of composer create-project. What is the actual added value of the init script? Just to copy the files? They can be already there with the same success as they are not changed by the init script. :)

**Comment by samdark** [comment]
init script initializes your app either with development or production defaults. That's it. As far as I know, we can't tell composer's create-project which of these defaults we need.

**Comment by tsvetann** [comment]
If constants live in bootstrap then init is redundant! local files will be moved to the actual instance by default. I just have the feeling that when working in a team with lots of people and the deploy process is not that simple the init adds lots of overhead to the process and potential for errors.

**Comment by mikehaertl** [comment]
@tsvetann Not sure what you mean by "architectural experiments" - but the app templates provided by Yii are just examples. You don't need to follow them and can build whatever app structure you want.

@samdark So the idea is, that you use composer to deploy the application in production? Sounds pretty weird to me. In my world (and I think that's pretty common) I use one and the same application code for both, development and production and only configure additional debug parameters in development.

**Comment by samdark** [comment]
@tsvetann yes but **which** local files? Currently there are two sets of these called `environments`: production and development. The difference isn't only in `index.php` but in configs as well.

**Comment by samdark** [comment]
@mikehaertl no but I'm using Composer to set up application at production initially.

**Comment by tsvetann** [comment]
@samdark The only instance-wise difference I can see in the config files is:
```php
if (!YII_ENV_TEST) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    ..........
}
```

So if we are saving efforts to automagically have the above 6-7 lines (I am not sure if everybody uses them) at the price of running init script on each dev's PC and the different server instances...for me this is value taken not added! I hope I am missing the point of init script here!

**Comment by samdark** [comment]
It is the difference initially. In the process of app development one can add more stuff to local files for production and development i.e. different cache backends, different logging etc.

This is viable both to team newcomers and when adding new servers.

**Comment by Faryshta** [comment]
@samdark how about creating a new config file dev.php

```php
if (YII_ENV_TEST) {
    // configuration adjustments for 'dev' environment
    $config = ArrayHelper::merge($config, require(__DIR__ . '/dev.php');
}
```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/wiki/Ideas-for-2.1
