### ISSUE TITLE
Как сделать ActiveLabel вычисляемым

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#7444]
Бился над документацией так и не смог понять, как вставить теги в label без экранирования?
Кучакода:
<?php 
                    $field = $form->field($user, 'terms');
                    $field->template = "{input}{label}\n{error}";
                    echo $field->checkbox();
?>
Результат: теги отображаются как текст

**Comment by cebe** [comment]
> теги отображаются как текст

what do you mean with that? you see them printed like this `<div ...>... <input ...></div>` ?

**Comment by samdark** [comment]
Yeah, he means labels are escaped.

**Comment by cebe** [comment]
So this is about label beeing encoded or the whole field tags?

**Comment by samdark** [comment]
label.

**Comment by lynicidn** [comment]
@cebe :+1: молодец

**Comment by klimov-paul** [comment]
Duplicates #4039
