### ISSUE TITLE
Could not use unicode symbols in Html::activeDropDownList()

### ISSUE THREAD

**Issue by yapi68** [yiisoft/yii2#7449]
I think sometimes we need to use unicode symbols like "&amp;mdash;" in Html::activeDropDownList(). Can you add this option?

**Comment by samdark** [comment]
What prevents you from using these currently?

**Comment by anton-p-ivanov** [comment]
@samdark They always encoded by Html::encode() function in Html::renderSelectOptions() in line 1575.

**Comment by samdark** [comment]
OK. Do you want to make a pull request?

**Comment by yapi68** [comment]
@samdark Ok.

**Comment by yapi68** [comment]
Pull request done, but i cant fix tests.

**Comment by yapi68** [comment]
As said by @qiangxue `encodeSpaces` should be stay in code for BC. I will fix this later.
