### ISSUE TITLE
Consider PhpRedis backend for redis

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#745]
#743 

> Maybe Yii2 should support Pecl Redis (PhpRedis)?
> http://pecl.php.net/package/redis

> http://alekseykorzun.com/post/53283070010/benchmarking-memcached-and-redis-clients

**Comment by jasonhancock** [comment]
+1

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-redis/issues/45
