### ISSUE TITLE
[Docs Request] activeCheckboxList example with a relation

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#7456]
`activeCheckboxList` lets say i have a `Meeting` active record, there i can select which users will be invited to the meeting. The best way i can imagine to do it simply is to have a checkbox list of all the users (or maybe a list of all users in a department) and simply check the ones i want to attend the meeting.

The invited people are stored on a pivot table and accesed on the relation `$meeting->assitants`. So it won't be stored on one of the `$meeting` table attributes

I think it would be a good idea to have a documented example about how to do it on yii2.

**Comment by Faryshta** [comment]
@samdark hi, any update on this?

**Comment by samdark** [comment]
It sounds like a good fit for tutorial or cookbook article but not for the guide.

**Comment by Faryshta** [comment]
why not? i think its perfect for the 'working with relations' part of the 'active record' guide. since this will be a graphic representation of a relation and how to easily add/remove elements to it. i can write it if you want

**Comment by samdark** [comment]
Please do. If it won't be used in the guide, I'll put it into cookbook. OK?

**Comment by Faryshta** [comment]
ok i will do it. And do please put it on the guide. Usually when dealing with cases like the one described on the issue the developers use google to search 'yii2 multiple select' (there are many stackoverflow threads already)

then they are told to use checkboxList instead. Then they are back on square one when they can't know and there are not examples on the internet

**Comment by romdim** [comment]
Hello everyone! Is there any update on this?
I was using an explode, implode technique to save ids as text for another table to show at a checkboxlist and now that I have implemented a junction table I need to make the same.
My problem is showing let's say 8 default values that can be checked or unchecked and 2 of them are already checked as can be retrieved from the junction table.
An example on this would be very helpful!

**Comment by dynasource** [comment]
the guide is updated with examples for lists. Doing this with relations should be easy for the developer to understand https://github.com/yiisoft/yii2/pull/12922/files#diff-c1465cdd387077fc3722c86ddcd84e39R145
