### ISSUE TITLE
Upgrade Imagine to solve problem on Windows 7

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#7458]
Hi, I have a strange problem with yii2-imagined just gives error ERR_CONNECTION_RESET, I tried it and it is not the library imagick () is the extension.

My Config: imagick install correct support all formats.

![imagick](https://cloud.githubusercontent.com/assets/4957021/6382921/0404d352-bd1f-11e4-84b4-91be1e97a3a4.jpg)

My Code-Yii2-Imagine: (Not Works Windows 7 Ultimate N X64 Error: ERR_CONNECTION_RESET)

    <?php
        use yii\imagine\Image;
        Yii::setAlias('@images', dirname(dirname(__DIR__)) . '/frontend/web/imagenes/usuarios/profile');
        Image::thumbnail('@webroot/perfil_google.jpg', 100, 100)
        ->save(\yii::getAlias('@images/thumb-test-photo-1.jpg'), ['quality' => 80]);
    ?>

My Code-Imagick(): (Work Perfect)

    <?php 
        Yii::setAlias('@images', dirname(dirname(__DIR__)) . '/frontend/web/imagenes/usuarios/profile');
        $im = new Imagick();
        $im->readImage(\yii::getAlias('@webroot/perfil_google.jpg'));
        $im->thumbnailImage(100, 100);
        $im->writeImage(\yii::getAlias('@images/thumb-test-photo.jpg'));
        $im->destroy();
     ?>

Server Config:

1.- Apache 2.4.12-x64. download: http://www.apachelounge.com/download/.
2.- PHP 5.6.6 x64-ts-VC11. download: http://www.apachelounge.com/download/.
3.- Imagick ImageMagick-6.9.0-7-Q16-x64-dll. download: http://www.imagemagick.org/script/binary-releases.php#windows
4.- OS: Windows 7 Ultimate N X64.

**Comment by samdark** [comment]
Anything in logs?

**Comment by tecnologiaterabyte** [comment]
/backend/runtime/logs/app:

    2015-02-25 07:03:51 [192.168.1.101][3][-][error][Imagine\Exception\RuntimeException]

**Comment by samdark** [comment]
And that's it? Is there a trace or mention of what this RuntimeException is?

**Comment by tecnologiaterabyte** [comment]
No mention anything, I have the tracelevel => 3

**Comment by samdark** [comment]
Well, it's something internal about Imagine. Can't tell more w/o logs. Try adding try-catch and getting message from exception caught.

**Comment by tecnologiaterabyte** [comment]
I think I found the problem if placed to view the content:

the problem is in the open:

    Debug:

    var_dump(self::$_imagine);

    show: object(Imagine\Imagick\Imagine)#153 (0) { }

    echo ($filename);

    Show: C:/webs/intracheck/backend/web/perfil_google.jpg

    echo ($box):

    Show: 100x100 px

    Code BaseImage.php in (Vendor/yiisoft/yii2-imagine).

    Line 157:

    $img = static::getImagine()->open(Yii::getAlias($filename));

    // In Windows //
    var_dump($img);

    Show: ERR_CONNECTION_RESET

    // in Linux Work Fine//

    Show: object(Imagine\Imagick\Image)#155 (2) { ["imagick":"Imagine\Imagick\Image":private]=> object(Imagick)#154 (0) { } ["layers":"Imagine\Imagick\Image":private]=> object(Imagine\Imagick\Layers)#156 (4) { ["image":"Imagine\Imagick\Layers":private]=> *RECURSION* ["resource":"Imagine\Imagick\Layers":private]=> object(Imagick)#154 (0) { } ["offset":"Imagine\Imagick\Layers":private]=> int(0) ["layers":"Imagine\Imagick\Layers":private]=> array(0) { } } }

I hope this information you a clue about the problem.

Thks,

**Comment by samdark** [comment]
It's not. It's Imagine internals, not Yii wrapper so I guess it should be reported to [Imagine issue tracker](https://github.com/avalanche123/Imagine/issues).

**Comment by tecnologiaterabyte** [comment]
Solved add update image/imagine "imagine/imagine": "0.6.2" the last version.

Thks,

**Comment by tecnologiaterabyte** [comment]
@samdark 

You can add yii2-imagine the updated library "imagine / Imagine": "0.6.2", that functions with the new library imagick.

Thks,

**Comment by samdark** [comment]
`0.6.*` aren't backwards compatible with `0.5.*` we're currently using. Set milestone to 2.1 where we can safely update it.

**Comment by ItsReddi** [comment]
https://github.com/yiisoft/yii2/issues/6014 - https://github.com/yiisoft/yii2/pull/7070

**Comment by samdark** [comment]
Closed in favor of https://github.com/yiisoft/yii2-imagine/issues/7
