### ISSUE TITLE
Composer update Yii 2.0.2 dev

### ISSUE THREAD

**Issue by loveorigami** [yiisoft/yii2#7461]
I am read https://github.com/yiisoft/yii2/issues/6537#issuecomment-75466568 and problem not fixing.
* update composer global require "fxp/composer-asset-plugin:1.0.0"
* composer self-update
* clear cache
![2015-02-26_9-53-57](https://cloud.githubusercontent.com/assets/98164/6387398/1787fca8-bda4-11e4-993e-8eac7bbff468.jpg)

**Comment by lynicidn** [comment]
try:
```bash
$ rm -rf ~/.composer
$ composer global require "fxp/composer-asset-plugin:1.0.0"
```

**Comment by loveorigami** [comment]
I am use Windows 7 (x32 and x64) as localhost 
and did
* https://getcomposer.org/doc/03-cli.md#clear-cache
problem not fixed

**Comment by lynicidn** [comment]
try delete `c:\users\YOU\.composer\cache`

**Comment by lynicidn** [comment]
>Cache on windows 7 is : C:\Users\YOU\AppData\Local\Composer\files.

**Comment by loveorigami** [comment]
This is the same
All folder is empty
![222](https://cloud.githubusercontent.com/assets/98164/6388725/8458edb2-bdb6-11e4-8c9c-415f822413c0.jpg)

**Comment by pana1990** [comment]
Use min-stability stable

**Comment by SDKiller** [comment]
@loveorigami 

From what version of `yii` are you updating?

Have you added to your `composer.json` `"extra"` section
```
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
```
if it was not present there?

**Comment by a-komarev** [comment]
Try to cleanup `./vendor` folder contents. That solved issue for me:
https://github.com/yiisoft/yii2/issues/7402#issuecomment-75649429

**Comment by loveorigami** [comment]
@a-komarev thanks.
after delete vendor folder problem is fixed.
