### ISSUE TITLE
UploadedFile::saveAs doesn't support alias

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#7462]
The docs doesn't mention it should support it but i think it would make uploading / downloading files more easily

**Comment by qiangxue** [comment]
This was discussed before. We will not support it. Aliases are primarily supported for configurable properties.

**Comment by Faryshta** [comment]
What do you mean?

What i want is to do Something like `$file->saveAs('@pdf/' . $file->baseName . '.pdf')`

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/6289

**Comment by amlopezalonso** [comment]
Before this change I had:

In `params-local.php`:

     `return ['myRoot' => '@web/myroot'];`

...and in `controller`:

`$fullPath = Yii::$app->params[$myRoot] . '/myLast';`
` FileHelper::createDirectory($fullPath);`

and had no trouble with it. Now I got:

`FileHelper::createDirectory(Yii::getAlias($fullPath));`

And it throws: 

Exception – yii\base\Exception
Failed to create directory '/web': mkdir(): Permission denied

Any ideas?
Antonio

**Comment by SilverFire** [comment]
@amlopezalonso please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](http://www.yiiframework.com/forum/), on [IRC](http://www.yiiframework.com/chat/) (#yii on freenode), or [Gitter](https://gitter.im/yiisoft/yii2).


> Failed to create directory '/web': mkdir(): Permission denied

The user that runs the script does not have enough permissions to create a directory.
