### ISSUE TITLE
Logger: make possible to add new -targets- dynamically (proposal)

### ISSUE THREAD

**Issue by tekord** [yiisoft/yii2#7464]
As far as I understand the logger configuration must be defined before app will be initialized. App creates the logger instance with predefined targets. Now I need to add new logger's target on *module initialization*, but I didn't found any methods to register new target. Also it is impossible to add something directly to logger's configuration because logger is already initialized (before my module init()). Is there any solution for this? Or am I missing something?

**Comment by samdark** [comment]
You need to call `init` once additional target added.
