### ISSUE TITLE
activeCheckbox is unusable if attribute value is an array

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#7466]
I can't use activeCheckboxlist because I want the label tag to be next to the input, not around it. So I tried to use activeCheckbox, but since the value is an array, the checkbox will never be checked (https://github.com/yiisoft/yii2/blob/2.0.2/framework/helpers/BaseHtml.php#L1328), and I can't override it either.

**Comment by qiangxue** [comment]
You can use `item` option to do arbitrary layout.
