### ISSUE TITLE
ActiveForm Core Validator 'string' never utilizes 'message' in rule.

### ISSUE THREAD

**Issue by bajabob** [yiisoft/yii2#7472]
I don't know if this is a bug, but more of an inconsistency. All other validators utilize the ```message``` attribute but ```string``` does not seem to support it. Instead we must use ```tooLong``` or ```tooShort``` and ```message``` has no effect on the rule. I was unable to find anything regarding these two characteristics in the documentation.

More on the issue: http://stackoverflow.com/questions/28747679/form-validation-rule-does-not-render-custom-message

**Comment by cebe** [comment]
From the docs:

> User-defined error message used when the value is not a string
> http://www.yiiframework.com/doc-2.0/yii-validators-stringvalidator.html#$message-detail

For other cases there are other messages which you can define:
`tooShort`, `tooLong`, `notEqual`.

**Comment by bajabob** [comment]
Thanks for clarifying @cebe! Is there a way I can add this to the example code in the docs to help someone else find it in the future?

**Comment by cebe** [comment]
I have just pushed an update to make the documentation more clear.
