### ISSUE TITLE
Composer Update broken

### ISSUE THREAD

**Issue by cannycookie** [yiisoft/yii2#7478]
When updating we now get:-
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - Installation request for yiisoft/yii2 2.0.2 -> satisfiable by yiisoft/yii2[2.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

Have tried `composer self-update --rollback` but still the same.
Have also added this plugin `composer global require "fxp/composer-asset-plugin:1.0.0"`
Also deleted the cache and vendor as suggested in other post.  Help!!!

**Comment by inblank** [comment]
I have the same error while updating.
Maybe due to the fact that inputmask update version on 3.1.**62-3**

**Comment by a-komarev** [comment]
Try to cleanup ./vendor folder contents. That solved issue for me:
https://github.com/yiisoft/yii2/issues/7402#issuecomment-75649429

**Comment by inblank** [comment]
@a-komarev thanks.
I had old version fxp/composer-asset-plugin (v1.0.0**-beta4**). 
After updating `composer global require "fxp/composer-asset-plugin:1.0.0` 
command `composer update` running without errors.

**Comment by cannycookie** [comment]
Yes.  Cleared out vendor again and working.  Thanks all for prompt replies.

**Comment by TimNZ** [comment]
This is incredibly painful when you have a lot of requires, composer update is sooooo slow for an update.

After a clearcache and clearing vendor directory, I'm doing a composer install instead.

Please Yii guys, figure out why this happening and tell us how to avoid in a less painful way.

**Comment by samdark** [comment]
@TimNZ it's slow because of getting bower assets via fxp plugin. Can't do anything about it in 2.0.x.

**Comment by pareekbhagu** [comment]
@samdark , Isn't it possible to get rid of composer-asset-plugin in anyway? lots and lots of time has been wasted on this. I think a developer would rather happy to install packages through bower and npm rather than depending on this weird plugin, which yes, solved problems in the past but now it wastes more time than actually helping dev's? sorry if my opinion is subjective! What's yours?

**Comment by devmustafa** [comment]
@pareekbhagu You can get rid of reading patches:
`"extra": {
    "asset-installer-paths": {
      "npm-asset-library": "vendor/npm",
      "bower-asset-library": "vendor/bower"
    },
    "asset-pattern-skip-version": "(-patch)"
  },`

**Comment by samdark** [comment]
https://asset-packagist.org/
