### ISSUE TITLE
QueryBuilder does not allow to support array types for PostgreSQL

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/yii2#7481]
PostgreSQL supports array types and I was trying to do supporting for that types in my project.
To do this, I created child classes `Schema` and `ColumnSchema`. And I implemented type conversion `ColumnSchema::dbTypecast()` and `ColumnSchema::phpTypecast()`.
But I was faced with the problem: when I assign array values to AR attributes and then save, it causes an error by the line https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L271

Because `QueryBuilder` skips `dbTypecast` for array values:
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L151
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L192
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L252

I had to create another child class `QueryBuilder` and remove `!is_array($value)` from conditions. After that it works successfully.

I do not know whether this affects the operation of the system elsewhere. But it looks a bit limiting.

**Comment by nineinchnick** [comment]
Does anybody know why only non-arrays are typecasted? I can't figure it out from the sources.

**Comment by cebe** [comment]
array syntax is used to append a PDO typehint to a value.
https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L304-L306

This turns out to be problematic now when dbms support array type natively...

**Comment by nineinchnick** [comment]
This isn't the code mentioned by @Tigrov, the other `is_array` checks just skips `dbTypecast()`.

**Comment by nineinchnick** [comment]
@Tigrov array values are reserved by `Command::bindValues` as a way of attaching the PDO type metadata to the real value (ex. `['string', \PDO::PARAM_STR]`). You could put your array values inside such arrays.

@cebe maybe a special class should be created and used instead of such arrays? This would break BC so probably it could make into 2.1. I could prepare a PR now.

**Comment by Tigrov** [comment]
@nineinchnick I use ActiveRecord model
```php
$model->field = [1,2,3,4];
$model->save();
```
It's not possible to use wrap array e.g. ```$model->field = [[1,2,3,4], \PDO::PARAM_STR];```

"a special class ... instead of such arrays" it will be best way.

**Comment by dynasource** [comment]
closed in favor of https://github.com/yiisoft/yii2/issues/7640

**Comment by Tigrov** [comment]
I made an extention to fix it
https://github.com/Tigrov/yii2-pgsql
