### ISSUE TITLE
Relation link using db expression

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#7483]
I need to create a join using a substring funtion to get an sql command like this. 

```code
select * from finanzkonto 
left join bank b on b.blz = substr(iban,5,8)
``` 

Usecase is getting banking information based on the international bank account number (IBAN).

When I define the relation in a model using a db expression
```php
 public function getBank() {
   return $this->hasOne(Bank::className(),
           ['blz' => new \yii\db\Expression('substr(iban,5,8)')]);
 }
```

and access this relation in a view by
```php
echo $model->bank->bankname;
``` 
 the following error will be thrown:
**Getting unknown property: frontend\models\Finanzkonto::substr(iban,5,8)**

Is this a bug or what is the right way to solve this request?

**Comment by cebe** [comment]
a relation has to be defined on real existing table columns otherwise things like eager loading would not work. In your case you could just return a normal query instead of a realtion.

**Comment by twinni** [comment]
@cebe, thanks. It works nearly like a normal relation. For those who are looking for a solution here is how it looks now:
In model:
```php
public function getBank()
    {
        return Bank::findOne(['blz' =>substr($this->iban,4,8)]);
    }
```
and in view
```php
echo $model->bank->bankname;
```
