### ISSUE TITLE
TimestampBehavior with Expression overrides the model attribute

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#7484]
If you use an Expression in the TimestampBehavior like this:
```php
public function behaviors()
{
	return [
		[
			'class' => TimestampBehavior::className(),
			'attributes' => [
				ActiveRecord::EVENT_BEFORE_INSERT => ['created', 'updated'],
				ActiveRecord::EVENT_BEFORE_UPDATE => ['updated'],
			],
			'value' => new Expression('GetDate()'), // MSSQL datetime
		],
	];
}
```

And do a `update` or `touch` and then want do use the new value like this:
```php
$model->touch('updated');
var_dump($model->updated); // Returns the Expression
```

**It just overrides the attribute and you have to reload your model. I think that should not be the expected behavior.**

My current approach is to avoid `Expression` and do it like this:
```php
'value' => function ($event) {
    return date('Y-m-d H:i:s'); // MSSQL datetime
}
```

It would also be nice if the `value` would accept a `function($event, $attribute)` then some fancy things like this would be possible:
```php
'value' => function ($event, $attribute) {
    if ($this->$attribute instanceof DateTimeAttribute) {
        $this->$attribute->setTimestamp(time());
        return $this->$attribute->getDatabaseString();
    }
    return date('Y-m-d H:i:s');
}
```

**Comment by cebe** [comment]
yii does not reload the model automatically because that means a database request that may not be needed. if you need the value from DB afterwards you should run `$model->refresh()` yourself.
