### ISSUE TITLE
DetailView widget selects table twice 

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#7485]
Having this function in a model which return an other model (not query!) 
```php
 public function getBank()
    {
        return Bank::findOne(['blz' => substr($this->iban, 4, 8)]) ;
     }
```
and using it in a detailView widget like this
```php
 <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
           'iban',
           'bank.bankname',
         ],
    ]) ?>
```
then the bank table will be selected twice.
This is not the case when I just use
```php
$model->bank->bankname;
``` 
It's not really important as I have to implement the singelton pattern anyway but might be a hint to avoid some db calls.

**Comment by SilverFire** [comment]
Use eager loading http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#lazy-eager-loading
