### ISSUE TITLE
 Local configs for Codeception tests of Advanced app. template are stored in repository

### ISSUE THREAD

**Issue by vojtech-horak** [yiisoft/yii2#7487]
Codeception tests in Advanced application template contains some files with local parameter that are stored into repository:

There is an absolute URL in these config files:
https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/backend/acceptance.suite.yml
https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/backend/codeception.yml
https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/frontend/acceptance.suite.yml
https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/frontend/codeception.yml

And there is a DB connection:
https://github.com/yiisoft/yii2/blob/master/apps/advanced/tests/codeception/config/config.php

I'd suggest to either mark these files as untracked or create "local" configs as in the application itself. Both would require copying files during the init.

I've already raised this topic in the forum:
http://www.yiiframework.com/forum/index.php/topic/61861-local-config-for-codeception-tests-in-advanced-application/

**Comment by samdark** [comment]
Tests should be performed on a test database so DB connection is OK to be similar for all instances. I don't like the idea of adding these to environments since it will complicate template too much.

**Comment by vojtech-horak** [comment]
@samdark Thank you for the consideration. I'll post my solution on the forum just in case somebody faces this issue.

**Comment by samdark** [comment]
Great. Thanks!
