### ISSUE TITLE
Record level access filter

### ISSUE THREAD

**Issue by fernandezekiel** [yiisoft/yii2#749]
something like this extension for yii1: http://www.yiiframework.com/extension/acl/
it would provide us filtering in the records itself not just the controller-actions
it would also give a more complex way of accessing records by applying groups not just the typical 'owner id' column per table

**Comment by fernandezekiel** [comment]
it's alright, this kind of feature is probably too application specific to write a generic implementation for Yii, however if a design can be suggested i can help work on it

**Comment by dynasource** [comment]
agreed. Feel free to create your own extension in github. Perhabs one day it will be published as a yii-extension. For now its out of the cores scope.
