### ISSUE TITLE
Undefined class constant 'TYPE_DOUBLE' (\vendor\yiisoft\yii2-gii\generators\model\Generator.php)

### ISSUE THREAD

**Issue by nexusevgeniy** [yiisoft/yii2#7490]
GII Model Generator - MySQL - error in table field by "double" type
PHP Fatal Error – yii\base\ErrorException
Undefined class constant 'TYPE_DOUBLE'

case Schema::TYPE_DOUBLE: 

 (\vendor\yiisoft\yii2-gii\generators\model\Generator.php)

missing constant const TYPE_DOUBLE = 'double' in \vendor\yiisoft\yii\db\Schema.php

**Comment by cebe** [comment]
have you possibly installed a dev version of gii but not the latest dev version of yii2 itself?

**Comment by nexusevgeniy** [comment]
two hours ago I was cleaning vendors folder. And run composer update (befor it i have problem with composer update command).

**Comment by cebe** [comment]
can you paste your composer.json and run `composer show -i` and paste the output?

**Comment by nexusevgeniy** [comment]
bower-asset/bootstrap               v3.3.2             The most popular fr...
bower-asset/jquery                  2.1.3
bower-asset/jquery.inputmask        3.1.61             jquery.inputmask is...
bower-asset/punycode                v1.3.2
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Application Template",
    "keywords": ["yii2", "framework", "advanced", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.2",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "kartik-v/yii2-widgets": "*",
        "kartik-v/yii2-grid": "*",
        "kartik-v/yii2-helpers": "dev-master",
        "kartik-v/yii2-mpdf": "dev-master",
        "creocoder/yii2-nested-sets": "dev-master"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}




bower-asset/typeahead.js            v0.10.5
bower-asset/yii2-pjax               dev-master b7491ae
cebe/markdown                       dev-master f89dc1d A super fast, highl...
creocoder/yii2-nested-sets          dev-master ac447e9 The nested sets beh...
ezyang/htmlpurifier                 v4.6.0             Standards compliant...
fzaninotto/faker                    dev-master 40426f7 Faker is a PHP libr...
kartik-v/bootstrap-fileinput        dev-master c996522 An enhanced HTML 5 ...
kartik-v/bootstrap-star-rating      dev-master c015b2b A simple yet powerf...
kartik-v/dependent-dropdown         dev-master cbab8a3 A multi level depen...
kartik-v/mpdf                       dev-master a9d6960 A PHP class to gene...
kartik-v/yii2-grid                  dev-master cc22f71 Yii 2 GridView on s...
kartik-v/yii2-helpers               dev-master 2334250 A collection of use...
kartik-v/yii2-krajee-base           dev-master 62fa801 Base library and fo...
kartik-v/yii2-mpdf                  dev-master cd6afdc A Yii2 wrapper comp...
kartik-v/yii2-widget-activeform     dev-master b73b4ec Enhanced Yii2 activ...
kartik-v/yii2-widget-affix          dev-master b376ccb A scrollspy and aff...
kartik-v/yii2-widget-alert          dev-master 1fdb285 A widget to generat...
kartik-v/yii2-widget-colorinput     dev-master 58e3ef0 An enhanced Yii 2 w...
kartik-v/yii2-widget-datepicker     dev-master dde4d46 Enhanced Yii2 wrapp...
kartik-v/yii2-widget-datetimepicker dev-master 319394f Enhanced Yii2 wrapp...
kartik-v/yii2-widget-depdrop        dev-master 655bac5 Widget that enables...
kartik-v/yii2-widget-fileinput      dev-master d1d89f2 An enhanced FileInp...
kartik-v/yii2-widget-growl          dev-master 1ee0111 A widget to generat...
kartik-v/yii2-widget-rangeinput     dev-master 900347a An enhanced Yii 2 w...
kartik-v/yii2-widget-rating         dev-master 48e9158 A Yii2 widget for t...
kartik-v/yii2-widget-select2        dev-master 3564f61 Enhanced Yii2 wrapp...
kartik-v/yii2-widget-sidenav        dev-master 33063d5 An enhanced side na...
kartik-v/yii2-widget-spinner        dev-master f993a8e A widget to render ...
kartik-v/yii2-widget-switchinput    dev-master e2bc893 A Yii2 wrapper widg...
kartik-v/yii2-widget-timepicker     dev-master a537e6b Enhanced Yii2 wrapp...
kartik-v/yii2-widget-touchspin      dev-master 036d936 A Yii2 wrapper widg...
kartik-v/yii2-widget-typeahead      dev-master 346f792 Enhanced Yii2 wrapp...
kartik-v/yii2-widgets               dev-master ec147a7 Collection of usefu...
phpspec/php-diff                    dev-master 30e103d A comprehensive lib...
swiftmailer/swiftmailer             dev-master db95cfa Swiftmailer, free f...
yiisoft/yii2                        2.0.2              Yii PHP Framework V...
yiisoft/yii2-bootstrap              dev-master 84ad12b The Twitter Bootstr...
yiisoft/yii2-codeception            dev-master 0b0b80b The Codeception int...
yiisoft/yii2-composer               dev-master 12e9db0 The composer plugin...
yiisoft/yii2-debug                  dev-master f2165a6 The debugger extens...
yiisoft/yii2-faker                  dev-master 4690e71 Fixture generator. ...
yiisoft/yii2-gii                    dev-master f58a672 The Gii extension f...
yiisoft/yii2-swiftmailer            dev-master a37f9db The SwiftMailer int...

**Comment by cebe** [comment]
>  yiisoft/yii2 2.0.2 Yii PHP Framework V...
>  yiisoft/yii2-gii dev-master f58a672 The Gii extension f...

As I said, you have the dev version of gii and only 2.0.2 of the framework. You have to downgrade gii or upgrade the framework.

**Comment by nexusevgeniy** [comment]
Thank you very much))) I just starter user yii2 and make my first project on this beautiful framework.
