### ISSUE TITLE
xcache bug hinders multisite support

### ISSUE THREAD

**Issue by chris68** [yiisoft/yii2#7491]
If you are using xcache together with yii2 you will face severe problems when running multiple sites on one machine in different subdirectories. Only the first site you access will be accessible. Even when you call the second site the first site will appear.

Reason is a bug in xcache, where ``__DIR__`` is cached incorrectly (see http://xcache.lighttpd.net/ticket/348). The consequences in Yii2 is that the whole paths are then totally incorrect, e.g. even when accessing site A the  scripts of site B will be called due to the incorrectly cached ``__DIR__`` in the bootstrap/autoloader script!

Not a fault of Yii2. But should be maybe mentioned nevertheless in the documentation.

**Comment by chris68** [comment]
Just for reference if somebody else stumbled upon this issue.
* http://xcache.lighttpd.net/ticket/337 is another xcache ticket which describes to xcache bug even better. 
* It also states some workaround (Which I did not test, though. I simply threw xcache out of my servers)

**Comment by samdark** [comment]
Any idea where to mention it better?

**Comment by cebe** [comment]
I do not think yii documentation should contain information about bugs in third party software. XCache bug has to be fixed and users should use the latest version. we can not keep track of all the external issues in official yii docs.

**Comment by qiangxue** [comment]
:+1:
