### ISSUE TITLE
Yii2 GridView widget. Ajax to delete data

### ISSUE THREAD

**Issue by dungphanxuan** [yiisoft/yii2#7493]
Hello, now i want to delete data by ajax. Simply, when i delete data on GridView, then page will reload. So now i want to using ajax to delete data. How can i use ajax in GridView to delete data.\
Thank for help!

**Comment by Faryshta** [comment]
Are you using an `ActionColumn` ?

**Comment by dungphanxuan** [comment]
@samdark  Yes!. this is my code
 <?php

            Pjax::begin();
            echo GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'summary' => '',
                'tableOptions'=>['class' => 'table table-striped table-hover table-bordered'],
                'columns' => [
                    [
                        'attribute'=>'id',
                        'format' => 'raw',
                        'contentOptions'=>['style'=>'width:90px;text-align:center'],
                    ],
                    [
                        'attribute' => 'name',
                        'header' => 'Tên file',
                        'filter'=>true,
                        'format' => 'raw',
                        'value' => function ($data) {
                            return Html::tag('strong',$data->name);
                        },
                    ],
                  .......                   
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header' => 'Manager',
                        'template'=>'{update}{delete}{test}',
                        'contentOptions' => ['style' => 'width:80px;text-align:center'],
                    ],
                ]
            ]);
            Pjax::end();

**Comment by dungphanxuan** [comment]
Hello, i solve this problem on override  Pjax class. I add some javascript on registerJS method. Then my app run, Pjax will render my js to delete data. Thank!
