### ISSUE TITLE
Conditional Validation not working with select or checkbox

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii2#7496]
Conditional validation doesn't seem to work if what it is checking against is an active checkbox or active select. 

It also doesn't seem to work with client validation if the active field (regardless of type) has an ID set. i.e.     
```
['id'=>'SomeId']
```
here are a couple post on the forum about it

http://www.yiiframework.com/forum/index.php/topic/62132-conditional-validator-always-returns-required/page__gopid__275390#entry275390

http://www.yiiframework.com/forum/index.php/topic/61938-having-trouble-with-conditional-validation/page__p__274682__fromsearch__1#entry274682

It would also be nice if it reset the field that had the conditional validation if the item triggering the condition changed.

i.e.
```
['date', 'required', 'when' => function($model) {
return $model->type== 1;
}],
```
If "type" was set to 1 it would make the "date" field required. 

If you click the "date" field and the conditional client validation (client code not listed above) kicks in saying it's now a required field and this is as expected.  

If the user changes the "type" from "1" to "2" the "date" still has the error saying it's required in fact it is no longer required because "type" now equals "2" not "1". 

The error will go away upon submitting of the form but it will show the error until then. If the user doesn't know that it's not required it is very confusing.

**Comment by cebe** [comment]
You have to specify `whenClient` option to provide the JS code for the when condition.

**Comment by pkjoshi** [comment]
Hi Cebe I am also facing this issue.
With ur suggestion to specify `whenClient` option It is working partly like
here `discharge_date` is date field and `discharged` is checkbox

Working
   ```
    ['discharge_date', 'required', 'when' => function($model) {               
                return $model->discharged ==1;                 
            }, 'whenClient' => "function (attribute, value) {
                return $('#patient-detail-discharged').val() == 1;
            }"],
```
This is not working 
```
['discharged', 'required', 'when' => function($model) {              
                return $model->discharge_date != Null;                 
            }, 'whenClient' => "function (attribute, value) {
                return $('#patient-detail-discharge_date').val() != Null;
            }"],
```
why is it so? Actually what I am trying is if either of these two fields value is changed the other is required, by default the value of `discharged` is 0 and `discharge_date` is Null

**Comment by skworden** [comment]
As I stated in the original post the when client code isn't provided but is used (I erite these from my phone and don't remembe the proper syntax).

Even If you have it with whenclient it dosent work.

**Comment by skworden** [comment]
With radio

**Comment by skworden** [comment]
I feel with all if the client validation issues that are open this should be looked into.   Also what about if you set the Id of the item being validated it keeps it from doing clientValidation

**Comment by cebe** [comment]
are you sure that `null` is the correct value to check against in javascript? normally the value of a text field is an empty string...

**Comment by pkjoshi** [comment]
I have set the default value as null for `discharge_date` . I have also checked with this variation, but none seems to be working
```
['discharged', 'required', 'when' => function($model) {              
                return $model->discharge_date > 0;                 
            }, 'whenClient' => "function (attribute, value) {
                return $('#patient-detail-discharge_date').val() > 0;
            }"],
```
and 
```
['discharged', 'required', 'when' => function($model) {              
                return $model->discharge_date !=' ';                 
            }, 'whenClient' => "function (attribute, value) {
                return $('#patient-detail-discharge_date').val() !=' ';
            }"],
```

**Comment by skworden** [comment]
@cebe Try a conditional validator using radio button and see if it works for you.  I know a few people who tried and couldn't get it to work.   Also, try adding an ID to your fields and see if it works.  

If you get it to work with a radio can you please post your code.

**Comment by EugenyHo** [comment]
Yes, I confirm that conditional validation doesn't seem to work if what it is checking against is an active select. Yii 2.0.5

Have field in ActiveForm:
<pre> 
...
                <?= $form->field($model, 'category_dtp')->dropDownList(
                     [0=>'Наезд',1=>'Столкновение'],         
                     ['prompt'=>'Select accident category ...']
                                                                 ); 
                ?>
...
</pre>

and rule at model (I set always return "false", in this way my field must always pass validation):

<pre>
public function rules() {
	return [
           ...
	    ['ts_b_catalog_id', 'required', 'when' => function($model) { return false; }],
           ....
	];
}
</pre>

As result validation is not pass.

**Comment by skworden** [comment]
The only thing i can do to get it to fire correctly is something like
    <?=
    $form->field($model, 'class')->radioList($items,[
    'onclick' => "$(this).val($('input:radio:checked').val());"
    ])
    ?>

**Comment by SilverFire** [comment]
Maybe i'm missing something, but I failed to reproduce the problem. My code bellow is a patch to yii2 basic app contact form. I am listing only new lines of code:

model: ContactForm.php
```php
    public $urgent;
    public $expire_date;

    public function rules()
    {
        return [
            [['urgent'], 'boolean'],
            [['expire_date'], 'date'],
            [['expire_date'], 'required', 'when' => function ($model) {
                return $model->urgent;
            }, 'whenClient' => new JsExpression("
                function (attribute, value) {
                    return $('#contactform-urgent').is(':checked');
                }
            ")],
        ];
    }
```

view: contact.php
```php
                <?= $form->field($model, 'urgent')->checkbox() ?>
                <?= $form->field($model, 'expire_date') ?>
```

**Comment by moysoft** [comment]
Just add  'enableClientValidation' => false in form like this :
$form = ActiveForm::begin([
    'id' => 'login-form',
    'enableClientValidation' => false
]) ?>
