### ISSUE TITLE
open_basedir restriction in effect

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2#7497]
Hello, I use latest version dev in production hosting and in the last update this error show first time and with refreshing the page every thing is OK.

This work without error in local, Error just occur in hosting.

This line generate error:
file_exists('/dev/urandom')
when because open_basedir is not allowed this error shows. I think because file_exists() we should to check open_basedir is enable or not to prevent from warning message.

 09:36:34 [46.34.184.112][1][-][error][yii\base\ErrorException:2] exception 'yii\base\ErrorException' with message 'file_exists(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/home/jafaripu:/usr/lib/php:/usr/php4/lib/php:/usr/local/lib/php:/usr/local/php4/lib/php:/tmp)' in /home/vendor/yiisoft/yii2/base/Security.php:453
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_exists(): ...', '/home/jafaripu/...', 453, Array)
#1 /home/vendor/yiisoft/yii2/base/Security.php(453): file_exists('/dev/urandom')
#2 /home/vendor/yiisoft/yii2/base/Security.php(503): yii\base\Security->generateRandomKey(32)
#3 /home/vendor/yiisoft/yii2/web/Request.php(1292): yii\base\Security->generateRandomString()
#4 /home/vendor/yiisoft/yii2/web/Request.php(1260): yii\web\Request->generateCsrfToken()
#5 /home/vendor/yiisoft/yii2/helpers/BaseHtml.php(275): yii\web\Request->getCsrfToken()
#6 /home/frontend/views/layouts/main.php(25): yii\helpers\BaseHtml::csrfMetaTags()
#7 /home/vendor/yiisoft/yii2/base/View.php(325): require('/home/jafaripu/...')
#8 /home/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/jafaripu/...', Array)
#9 /home/vendor/yiisoft/yii2/base/Controller.php(382): yii\base\View->renderFile('/home/jafaripu/...', Array, Object(frontend\controllers\AdverController))
#10 /home/vendor/yiisoft/yii2/base/Controller.php(368): yii\base\Controller->renderContent('<div class="row...')
#11 /home/frontend/controllers/adver/Index.php(23): yii\base\Controller->render('index', Array)
#12 [internal function]: frontend\controllers\adver\Index->run()
#13 /home/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#14 /home/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array)
#15 /home/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('index', Array)
#16 /home/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction('adver/index', Array)
#17 /home/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /home/frontend/web/index.php(20): yii\base\Application->run()
#19 {main}

**Comment by samdark** [comment]
@tom-- any ideas on a good fallback in this case?

**Comment by lynicidn** [comment]
@jafaripur it's freebsd?

**Comment by lynicidn** [comment]
@jafaripur what is distr?

**Comment by jafaripur** [comment]
@lynicidn The latest Yii2, Updated with composer and "minimum-stability": "dev" option.

**Comment by lynicidn** [comment]
@jafaripur 
```bash
cat /etc/release_[debian|other]
```

**Comment by lynicidn** [comment]
also run:
```bash
ls -la /dev/urandom
```

**Comment by a-komarev** [comment]
Done it this way on a CentOS. In virtual host of Apache:
```
php_admin_value open_basedir "/var/www/my_project:/dev/urandom"
```

**Comment by jafaripur** [comment]
@a-komarev  Maybe sharing hosting don't allow to use this for security reason. I think fallback should be consider in code.

**Comment by cebe** [comment]
is it possible to test `is_readable` with openbasedir?

**Comment by jafaripur** [comment]
We should to check open_basedir is enable or not:
if (strlen( ini_get( 'open_basedir' ) ) > 0 && file_exists('/dev/urandom')) {
...
}
if (strlen( ini_get( 'open_basedir' ) ) > 0 && php_uname('s') !== 'Linux' && file_exists('/dev/random')) {
..
}

**Comment by lynicidn** [comment]
http://stackoverflow.com/questions/3690273/did-i-understand-dev-urandom

**Comment by tom--** [comment]
How about @ ?

:/

**Comment by tom--** [comment]
@lynicidn yes, i think i understand urandom. 

http://www.2uo.de/myths-about-urandom/ 

http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/

https://marc.info/?t=142475987200001&r=1&w=2

**Comment by jafaripur** [comment]
With this issue, Yii2 can't run in shared hosting! A fallback should be define for this purpose to use open_ssl instead /dev/random

**Comment by samdark** [comment]
@tom-- any issues if we'll use `is_readable` to check for `/dev/urandom` and `/dev/random` instead of `file_exists`? This way it will gracefully fall back to `openssl_random_pseudo_bytes`.

**Comment by samdark** [comment]
The only way to fix it is to silence `file_exists` checks with `@`.

**Comment by samdark** [comment]
@tom-- any objections?

**Comment by SDKiller** [comment]
At list put `open_basedir` check in `requirenments`

**Comment by SDKiller** [comment]
And IMO as this change may break BC in some circumstances - framework at least till `2.1.0` could be distributed with `SecurityLegacy` component to allow just easily switch them in `config`.
Otherwise some users may have situation when they will be stuck to old versions not having the benefits of other updates.

**Comment by tom--** [comment]
@samdark The algorithm *expects* failure to read from those devices under certain conditions. What I hadn't taken into account is all the conditions in which *trying* to read them triggers an error. So whatever technique works best to silence those is good.

**Comment by tom--** [comment]
@SDKiller That's correct. The conditions under which someone will experience BC failure, I imagine, are very rare. But it's possible.

There is no great pressure to replace Mcrypt in 2.0.3. We should get to it soon but it's not actually urgent.

There has been some discussion on php-internals that's got me thinking and I'm curious about perhaps adding support for the [Fernet](https://github.com/fernet/spec/blob/master/Spec.md) protocol. I'm thinking the design currently exposes too much of OpenSSL when we could completely hide it and thus make changes such as this one, or adding new ciphers, easier in future.

So I'm inclined to push this into 2.1 and take some time to think about these things and look at possible designs.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/4fffd8fcef4c4b38393ed27cba6772c9c1de1dcd

**Comment by samdark** [comment]
I like what we have as is. For 2.1 we may adjust it.

**Comment by jafaripur** [comment]
@samdark php_uname() is disabled in some of shared hosting for security reason, also this need to add @  for prevent from warning!

**Comment by creocoder** [comment]
Previous implementation with `mcrypt` does not contains read from '/dev/urandom' or `phpuname()`. Last one used wrong since php manual clean about what to do if you just need OS name. Also previous implementation was much more cleaner. I think we need revert it back to `mcrypt` (whole php world live with that and **nobody** complain).

**Comment by lynicidn** [comment]
how u solve problem don't know distribution? i think he have freebsd or other not linux dist (it's not classic way for home path - `/home/vendor/yiisoft/yii2/base/Security.php:453`) - read about alternative http://en.wikipedia.org/?title=/dev/random#EGD_as_an_alternative. I am repeat question:
what show command?
```bash
ls -la /dev/urandom
```

**Comment by creocoder** [comment]
@lynicidn Simple example from people who care about multi-platforms: https://github.com/laravel/framework/blob/5.0/src/Illuminate/Encryption/Encrypter.php#L248

**Comment by samdark** [comment]
@creocoder https://github.com/yiisoft/yii2/commit/d7346cbfafbb0de0e66d37485d4be1f8b55545c2

**Comment by samdark** [comment]
@creocoder mcrypt isn't supported for too long. And people [complained strong enough](https://twitter.com/ircmaxell/status/564919926700658689).

**Comment by tom--** [comment]
If you want to get rid of the second attempt, reading `/dev/random` on non-Linux, thus avoiding the uname test, it should be fine. Most other Unix-like systems (I don't know about all) have `/dev/urandom` for Linux compat. So there can't be many systems that will fail the first attempt but will succeed the second. Furthermore, the consequences of needing to use the third attempt, OpenSSL, is by no means disastrous. It's just that there are reasons to [prefer the system](http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/).

Since I pushed this version, a [proposed patch for PHP 7](https://github.com/php/php-src/pull/1119/files) has been published corresponding to a new RFC [Easy User-land CSPRNG](https://wiki.php.net/rfc/easy_userland_csprng). They have started using `/dev/arandom` which is not widely implemented yet. It comes from OpenBSD but it seems other systems are going to adopt the same. At this stage I'm not sure it's worth following this logic but maybe in a year or so.

**Comment by johnss** [comment]
does it will still add up the error in error_log file if we silence it using @ ? If yes, i think yii should add option to tell if the web app are in shared hosting or not via config, should add in the security Manager component add a property like `isSharedHost` to true if in shared host false if in VPS

**Comment by johnss** [comment]
@samdark in php 5.5.0 you may already know there are password_hash() so there is no need to read urandom which will be inacessible by shared hosting, i hope yii next major ver / 2.1 will use it
(http://php.net/manual/en/function.password-hash.php)

**Comment by tom--** [comment]
@johnss [2.0 uses it](https://github.com/yiisoft/yii2/blob/2.0.0/framework/base/Security.php#L531). And we need random data for various things besides password salts.

**Comment by johnss** [comment]
@tom--
what are example of thoose `various things` ?
there many ways of generating secure random values but the most popular ses to be urandom, there are alternatives such as openssl, there are no reason that urandom is a must
http://serverfault.com/questions/6440/is-there-an-alternative-to-dev-urandom

**Comment by tom--** [comment]
Encryption keys, pads, initialization vectors, nonces, auth keys, generating random passwords and shared secrets, lots of stuff...

There are actually very few ways to obtain random numbers in a reasonably safe way. And history shows how easy it is to screw up even if you know what you're doing. For PHP scripts that need to be portable the problem is more severe. Until PHP 7.0 it has actually been impossible to obtain them in all runtime configurations. This is why Yii will sometimes fail to return a random number when asked.

**Comment by johnss** [comment]
@samdark and to all yii dev team maybe already know that in php 7 there are random_bytes() future yii version must use this func
<http://php.net/manual/en/function.random-bytes.php>

**Comment by tom--** [comment]
@johnss I mentioned `random_bytes()` here [in February](https://github.com/yiisoft/yii2/issues/7497#issuecomment-76562066). When available, it's clearly the right thing to use.

I'm preparing a PR but with PHP 7.0's release scheduled for mid November it's not super urgent.

**Comment by johnss** [comment]
i think openssl pseudo random are sufficient as laravel use it, there are no other alternative via native func, WordPress generate secret key by using api via https://api.wordpress.org/secret-key/1.1/salt/ maybe this can be used in yii or use other online key generator

**Comment by samdark** [comment]
@johnss online key generator isn't an option. Yii is widely used for high-security projects where internet connection isn't an option at all.

**Comment by tom--** [comment]
@johnss i wish you would check your facts. once again you're asking for Yii to do something it [already does](https://github.com/yiisoft/yii2/blob/2.0.6/framework/base/Security.php#L490).

but yii uses openssl's rng as a last resort. i'm really comfortable with using it at all and i think we should remove it in 2.1. read what [Thomas Ptacek has to say](http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/) about user space rngs in general and openssl's in particular.

wordpress is certainly no guide to security techniques. neither is laravel for that matter, although it has improved recently. pointing at what other projects do is an argument that doesn't work.

**Comment by johnss** [comment]
@tom-- I know yii already use openssl, i only want to know if there are issues with openssl, but if you are not satisfied with openssl you should cite an credible source instead of amateur blog post

**Comment by tom--** [comment]
@johnss Thomas Ptacek is no amateur.

**Comment by samdark** [comment]
More than 15 years in security of which almost 10 he was running his own security-oriented company. Definitely not amateur :)
