### ISSUE TITLE
Add REPL support

### ISSUE THREAD

**Issue by callmez** [yiisoft/yii2#7498]
is there possible to extension psysh as  feature or offical extension。its really useful for developers。
like Rails Console or Laravel tinker.  thanks

**Comment by samdark** [comment]
Could you elaborate? I'm not using any of the tools mentioned...

**Comment by samdark** [comment]
Ah, interactive shell.

**Comment by samdark** [comment]
What Yii specific features do you want?

**Comment by callmez** [comment]
yes，for example i can use it test some function from command line without code file ， watch the data changed and more

**Comment by cebe** [comment]
@callmez can you give some links that describe how these work in other frameworks?

**Comment by callmez** [comment]
http://blog.enge.me/post/tinkering-with-tinker-like-an-artisan 
is this ok?

**Comment by callmez** [comment]
and you can get the psysh repository from https://github.com/bobthecow/psysh

**Comment by bobthecow** [comment]
I think this is a great idea :)

For a few examples of projects that already do this:

 * [artisan tinker for Laravel](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/TinkerCommand.php)
 * [eZ Debug Shell for eZ Publish](https://github.com/lolautruche/ezsh)
 * [drush-psysh for Drupal](https://github.com/grota/drush-psysh)
 * [magerun console command for Magento](https://github.com/netz98/n98-magerun/blob/develop/src/N98/Magento/Command/Developer/ConsoleCommand.php)
 * And tons for Symfony: [sf1-psysh-bootstrap](https://github.com/varas/sf1-psysh-bootstrap), [sf2-psysh-bootstrap](https://github.com/varas/sf2-psysh-bootstrap), [symfony-repl](https://github.com/luxifer/symfony-repl), [psymf](https://github.com/navitronic/psymf)

FWIW, [PsySH is working on a plugin architecture](https://github.com/bobthecow/psysh/issues/166), and it would prolly be ideal for projects to use that in addition to a shell wrapper (like Laravel's `artisan tinker` or `ezsh` or whatever). We're also interested in ways we can make creating a framework- or library-specific bespoke REPL a better experience, so if you have thoughts, let us know!

**Comment by cornernote** [comment]
Seems there is a way to do this in Yii1, havent tried it yet but will do so soon and report back as to how it works with Yii2:

https://gist.github.com/mrdziuban/7c3cffc52c41f0bb7577

**Comment by cornernote** [comment]
Yep, works a treat on Yii2:
https://gist.github.com/cornernote/ccf7e62d965497369185

**Comment by svkurowski** [comment]
For the record, I have created an minimal extension wrapping psysh with a Yii 2 Console command.
After installing the [extension](https://github.com/svkurowski/yii2-shell) using composer you can run the REPL by typing `./yii shell` in your command line.
No further setup is needed, you will have access to all your classes and your dependencies.

**Comment by pana1990** [comment]
@callmez @samdark  can you please check my pr?

**Comment by pana1990** [comment]
@callmez https://github.com/yiisoft/yii2-shell chek extension please 

@cebe @samdark @SilverFire can you please close this issue?

**Comment by svkurowski** [comment]
@pana1990 @SilverFire From the `README.md` and the `Bootstrap.php` files it seems like you copied from my extension and it would have been really great if you had forked my repository or at least mentioned me.

**Comment by samdark** [comment]
@svkurowski yep, seems like so. Can you send a pull request adding missing credits?

**Comment by pana1990** [comment]
@svkurowski yep, i based in your extension and ```artisan tinker``` from laravel, sorry for not naming you, my bad :(

**Comment by cebe** [comment]
@samdark @svkurowski I have made a PR fixing obvious things, let me know if there is anything missing. https://github.com/yiisoft/yii2-shell/pull/2
