### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sredXNY** [yiisoft/yii2#7503]
Hi, I'm developing a yii2 web page with a friend, we have our repository in bitbucket, the situation is the next: the application works fine in his pc, then he pushed the changes on the repository but when I do a pull  the application doesn't work to me, the web/index load a white page, then in the navigator console I got an error 500 internal server. it's the second time it happens, the first time I just copied manually the folder because we didn't found the error.
why it happens? How I fix it?

**Comment by cebe** [comment]
github is an issue tracker, please use the [forum](http://www.yiiframework.com/forum/) to ask questions.

**Comment by Faryshta** [comment]
you should activate the php errors and if possible the debug panel, a lot of things can happen.

different php versions, different server configurations, different folder settings. without knowing the exact php error its impossible to help you.

you mentioned you copied the code. That means you didn't used composer to install it? there is a post-create command that you didn't ran then
