### ISSUE TITLE
yii2 authclient linkedin giving invalid redirect_uri response

### ISSUE THREAD

**Issue by evercode1** [yiisoft/yii2#7506]
I keep getting invalid redirect_uri for linkedin when I try to use the yii2 authclient widget . The repsonse says this value must match a URL registered with the API Key.  I have registered the  OAuth 2.0 Redirect URLs: using the format of:

http://www.mydomain.com/site/auth?authclient=linkedin

The above url is what I see when I mouse over the widget link.

I have tried just supplying just the domain:

http://www.mydomain.com

But that doesn't work either.

the response from linkedin in the url is:

https://www.linkedin.com/uas/oauth2/authorization?client_id=759hyvmnnfll2d&response_type=code&redirect_uri=http%3A%2F%2Fyii2start.com%2Fsite%2Fauth%3Fauthclient%3Dlinkedin&xoauth_displayname=My%20Application&scope=r_basicprofile%20r_emailaddress&state=2c0308fc50b0042cc0954341b3401e195109c5d5

Is there some format I should be following that I'm not doing correctly?

I am following the config from the guide precisely.  And my actions and onAuthSuccess methods are working as expected.

So far I have successfully integrated Facebook, Github, and Twitter.  Had a problem with Google and put in a separate issue for that.

**Comment by klimov-paul** [comment]
Unable to reproduce: authentication via LinkedIn works fine.
Make sure you have setup redirectUri at LinkedIn control panel correctly. Ensure you have provided it at field for 'OAuth 2.0' not for 'OAuth 1.0a'!

**Comment by evercode1** [comment]
Ok, thanks for looking into that.  The problem was that I had more than one default scope selected, and I did not catch that since it was telling me the problem was the return uri.  I will check into the google configuration and see if there is a similar problem there.  Thanks again.

**Comment by vaibhav-ranosys** [comment]
Can you tell me the controller function and the redirect uri at linkedin portal? I am experiencing the same issue.

**Comment by gaikwadbhagyashri** [comment]
I am experiencing same issue. Url I am using is :https://www.linkedin.com/uas/oauth2/authorization?response_type=code&client_id=77plxpppupqbh2&client_secret=IQvZYDZTlYV7PtoI&redirect_uri=http://ws-100945:9080/ArtisWeb/index.html&scope=r_basicprofile 
I recheck everything but, still experiencing same error as:
invalid redirect_uri. This value must match a URL registered with the API Key.

Could anyone guide me on same please?

**Comment by vaibhav-ranosys** [comment]
https://github.com/yiisoft/yii2-authclient/issues/25 check on this. It might help you

**Comment by gaikwadbhagyashri** [comment]
its working nw..thnks

**Comment by gaikwadbhagyashri** [comment]
Hi, however, i am not able to generate access token .i tried with url:https://www.linkedin.com/uas/oauth2/accessToken?grant_type=authorization_code&code=AQTDWQcXqfD_t_cfZnGcmZhiPoySFL3wlk1h81xnhyhoILagmX6CzxDcn4MZR502hJdITOg2n5amFI1ypUy1T0ARgLroyqRLc6Kh-cbjgWEORtAwL4s&redirect_uri=http%3A%2F%2Fintranet-pretest.atradiusnet.com%2Findex.html&client_id=773399jir4el96&client_secret=JAvLR0Q5k8pZIi9k
Also, i have used code immediately as someone suggested me ,but no luck.

**Comment by vaibhav-ranosys** [comment]
Provide the website link and the some details of the code here

**Comment by gaikwadbhagyashri** [comment]
Hi,

website link is:http://intranet-pretest.atradiusnet.com/index.html
,its intranet website.

I didn't coded anything now, generated code using get method and now
,url requesting for generating access token.


Thanks and Regards,
Bhagyashri Gaikwad.

**Comment by gaikwadbhagyashri** [comment]
my issue is resolved,code i have used have very short lifespan of only 10secs.so,need to use it in same routine ,else it will expire

Thanks anyways....
