### ISSUE TITLE
ActiveRecord::find()->indexBy()->column() not indexing as expected

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#7515]
Given the documentation of `select()`, `indexBy` and `column()` I expected

```php
Book::find()->select('title')->indexBy('isbn')->column()
```

to return an associative array of book titles indexed by ISBN. It returned instead a numeric array of titles. The following produced the same result.

```php
Book::find()->select(['title', 'isbn'])->indexBy('isbn')->column()
```

In other words, for the above two cases `indexBy()` doesn't do anything. 

The following returned an array of Book models indexed by ISBN but if `indexBy` is only supposed to work with certain getters like `all()` then the documentation for `indexBy()` should say so.

```php
Book::find()->indexBy('isbn')->all()
```

If `indexBy()` is really just an option for `all()` then shouldn't it be a parameter of that method rather than a property of `Query`.

**Comment by lynicidn** [comment]
acept it - https://github.com/yiisoft/yii2/issues/7107#issuecomment-72256210

**Comment by samdark** [comment]
That's more of design decision. @qiangxue is it expected or should be fixed?

**Comment by qiangxue** [comment]
This is currently working as expected as `column()` uses the native PDO column fetch mode.
But I think we can consider enhancing `column()` in this case.

**Comment by lynicidn** [comment]
it worked before

**Comment by tom--** [comment]
@samdark what does "status:ready for adoption" mean?

**Comment by samdark** [comment]
Means that it is OK to improve it so it could be worked on.

**Comment by yapi68** [comment]
I have same issue. @samdark @qiangxue when it will be adopted? This issue allows to save proccessing time and forget about ArrayHelper::map().

**Comment by samdark** [comment]
You can speed things up by working on a pull request.

**Comment by sergey-rud** [comment]
It's really good news, if select(['id', 'name']), indexBy('id') and column('name') will return result:
array(id=>name)

**Comment by lynicidn** [comment]
column($db = null)

column fetch first column, i use it
```php
MyModel::find()->select('name', 'id')->indexBy('id')->column()
```

**Comment by sergey-rud** [comment]
Anyway it's more useful, than use ArrayHelper for this simple need.

**Comment by MelleDijkstra** [comment]
Is there already an easier way instead of using ArrayHelper to get the following result:
~~~
[id => name]
~~~
All I'm getting is (`->select(id,name)->indexBy(id)->all()`):
~~~
[id => [id, name]]
~~~

**Comment by tom--** [comment]
@MelleDijkstra try `->select('name')->indexBy('id')->column()`

**Comment by MelleDijkstra** [comment]
@tom-- I'll give it a try!
