### ISSUE TITLE
Question about memcached and ActiveDataProvider

### ISSUE THREAD

**Issue by sowich** [yiisoft/yii2#7516]
My configuration file:

``` php
'cache' => [
    'class' => 'yii\caching\MemCache',
    'useMemcached' => true
],
```

In the controller:

``` php
if (!$uidDataProviderQuery = \Yii::$app->cache->get('uidDataProviderQuery')) {
    $uidDataProviderQuery = StatsSearch::find()
        ->with(['uidCommentContent'])
        ->excluded()
        ->select('COUNT(`uid`) AS count, `uid`')
        ->groupBy('uid')
        ->orderBy(['count' => SORT_DESC])
        ->limit(\Yii::$app->config->get('GENERAL.ACTIVE_PER_PAGE'));

         \Yii::$app->cache->set('uidDataProviderQuery', $uidDataProviderQuery, 3600);
}

$uidDataProvider = new ActiveDataProvider([
    'query' => $uidDataProviderQuery,
    'pagination' => false,
]); 
```

The cache is placed like, but quickly disappears. As this kind of cache requests that they can be subsequently used in ActiveDataProvider? Want that query the database!

**Comment by samdark** [comment]
You're caching query object, not results.

**Comment by sowich** [comment]
How to cache the results so that you can manipulate them in ActiveDataProvider?

**Comment by samdark** [comment]
ActiveDataProvider issues different queries for different pages so caching the whole data provider isn't really possible if you're not caching the whole data set. If you want it, use ArrayDataProvider.

**Comment by sowich** [comment]
And what of the species with links (->with()) and:
```php
public function getIpCommentContent()
    {
        return $this->hasOne(Comment::className(), ['ip' => 'ip']);
    }
```

In ArrayDataProvider will be empty!

**Comment by samdark** [comment]
Use `with()` so it will be filled.

**Comment by sowich** [comment]
In the model, there is a method
```php
getFilterUrl()
```

How, then access it through ArrayDataProvider or all of the results of helper methods as you need to pass separately?

**Comment by samdark** [comment]
It seems we need an example in docs on "how to cache active data provider".

**Comment by samdark** [comment]
@yiisoft/core-developers any good examples?

**Comment by z-avanes** [comment]
how can cache SqlDataProvider?

**Comment by dynasource** [comment]
there are many different possibilities, perhabs good to put into the guide

**Comment by stesifrancesco** [comment]
Hi @samdark ,
I'm tring to cache ActiveDataProvider in this way:

`self::getDb()->cache(function() use ($dataProvider) {
            $dataProvider->prepare();
            //$dataProvider->query->all();
        },36000);
        return $dataProvider;`

I have not errors but It does not work.
Any improvements about "good examples" ?
