### ISSUE TITLE
Illegal string offset 'is_nullable'  in /vendor/yiisoft/yii2/db/pgsql/Schema.php

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#7521]
Illegal string offset 'is_nullable'  in
/vendor/yiisoft/yii2/db/pgsql/Schema::loadColumnSchema($info)

Error in cache block like this, on executing query

            $db = LanguageTranslate::getDb();
            $translations = $db->cache(
                function ($db) use ($attributesForTranslate) {
                    /* @var Connection $db */
                    /** @var LanguageTranslate[] $translations */
                    $translations = LanguageTranslate::find()
                        ->where([
                            'object_table' => $this->owner->tableName(),
                            'object_id' => $this->owner->getPrimaryKey(),
                            'language' => yii::$app->language,
                            'attr_name' => $attributesForTranslate
                        ])
                        ->all($db);
                    return $translations;
                },
                yii::$app->params['cacheDuration']['LanguageTranslate']
            );

**Comment by samdark** [comment]
Can you provide SQL to create tables involved?

**Comment by xVismutx** [comment]
It's seems like my cache broke after yii update
After flushing it, all normolised
