### ISSUE TITLE
csrf validation doesn't work in functional tests in 2.0.3

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#7523]
* composer create-project --prefer-dist yiisoft/yii2-app-basic basic
* cd basic
* composer require --dev codeception/codeception codeception/specify codeception/verify --prefer-dist
* cd tests
* set urls in codeception.yml and codeception/acceptance.yml
* ../vendor/bin/codecept build
* ../vendor/bin/codecept run

All tests pass.

* open tests/codeception/config/functional.php, set enableCsrfValidation to true, and uncomment the domain setting

Ensure that contact works (ContactCept): Fail
Ensure that login works (LoginCept): Fail

Both tests succeed with Yii 2.0.2. This is the commit that broke it: 0a6cd6190b851db89120572259ae8ca0ade9c2cb

**Comment by samdark** [comment]
https://travis-ci.org/yiisoft/yii2/jobs/52722632 it includes functional tests.

**Comment by nkovacs** [comment]
csrf validation is disabled by default in functional tests.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/b829d9d45a18c3c6ee242473dd3c5f28b81424b4/apps/advanced/tests/codeception/config/functional.php#L8

**Comment by nkovacs** [comment]
It should still work.

**Comment by lynicidn** [comment]
i think u need add csrf cookie in manual mode, also set it in session

**Comment by lynicidn** [comment]
@Ragazzo ?

**Comment by Ragazzo** [comment]
@qiangxue can you check what was the reason of currently failing tests in the [commit](https://github.com/yiisoft/yii2/commit/0a6cd6190b851db89120572259ae8ca0ade9c2cb) that @nkovacs pointed ?

**Comment by klimov-paul** [comment]
Does this issue is still stands?
Currently all tests for 'basic' and 'advanced' project templates are passing successfully.

**Comment by nkovacs** [comment]
Do they pass without `'enableCsrfValidation' => false`?

**Comment by andrewnester** [comment]
@nkovacs @klimov-paul just tried to run tests with Yii 2.0.6 - all tests are passed both for `enableCsrfValidation => false` and `enableCsrfValidation => true`

I guess this issue is connected with #8460

**Comment by dynasource** [comment]
like @andrewnester I have reproduced the above steps to create a new fresh install of 2.0.6. 
I dont get any errors. Whether enableCsrfValidation is true or false, all tests pass.

With respect to the age of this issue and nkovacs as the only reporter, this does not seem to be a deal breaker for 2.0.7. When other people get it, it could be opened again.
