### ISSUE TITLE
Getting error messages or logging errors in the Swiftmailer extension.

### ISSUE THREAD

**Issue by germansokolov13** [yiisoft/yii2#7524]
Swiftmailer `send` function returns false. But there are no error messages in any logs or object properties I can find. Swiftmailer docs say there is a logger plugin to do logging for Swiftmailer but I have no idea how to configure it with Yii configs. How do I get any status info or error messages out of swiftmailer in Yii? The guide and the docs say nothing regarding the error handling at all.

**Comment by lynicidn** [comment]
need more info - config

**Comment by lynicidn** [comment]
function `mail` in php should have `from` header as required or need configure it in server

**Comment by germansokolov13** [comment]
I am trying to use SMTP. Maybe the configuration is wrong but what I expect is that Swiftmailer returns at least something. Shouldn't it somehow return some error messages? Or some log or something.
Here is a piece of my config:
```
return [
    //...

    'components' => [
        //...

        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'my.host.com',
                'username' => 'noreply@my.host.com',
                'password' => 'pass',
                'port' => '25',
                'encryption' => 'tls',
            ],
        ],
```

**Comment by lynicidn** [comment]
u need check config for ur mail server, try setup gui client and test it.

**Comment by lynicidn** [comment]
if u use gmail u need configure account for it

**Comment by germansokolov13** [comment]
Thanks but this has nothing to do with the subject of the issue. I am looking for a way to get error messages. It seems most probably the Logger plugin should do it. But how do I properly configure Logger plugin in the Yii configs?

**Comment by lynicidn** [comment]
http://swiftmailer.org/docs/plugins.html#logger-plugin

**Comment by germansokolov13** [comment]
Yes, it should be possible to do it the way it's written there but how do I put it into the `plugins` key of the swiftmailer config? Yii docs say I need to somehow put plugins initialization into the 'plugins' key.

**Comment by germansokolov13** [comment]
This page refers to configuring plugins with the 'plugins' config key:
http://www.yiiframework.com/doc-2.0/yii-swiftmailer-mailer.html
Should I use it to configure the Logger or should I just directly do it with `Yii::$app->mailer`?

**Comment by lynicidn** [comment]
use forum

**Comment by sidtj** [comment]
Hi all,

@samdark, it seems that yii-swiftmailer has no logger plugin. Could I try to implement it (yet not today)? Is there some special rule that I should know or follow in this case?

Sure I will first investigate this a bit more.

I would like to help. I think a logger would really to be very useful.
Waiting.

**Comment by samdark** [comment]
@sidtj it will be definitely useful to have errors logged or displayed.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by sidtj** [comment]
@samdark, thanks for the link. I have already been using those guidelines. I was meaning something more specific for this case but I think it there is not. Thanks again :v:

**Comment by sidtj** [comment]
@samdark,
I think it could be marked as a **bug** in the swiftmailer extension because:
~~~[php]
            'useFileTransport' => true,
            'transport' => [
                'class' => 'Swift_MailTransport',
                'plugins' => [
                    [
                        'class' => 'Swift_Plugins_Loggers_EchoLogger',
                    ],
                ],
            ],
~~~
This config makes the extension to create `Swift_Plugins_Loggers_EchoLogger` and pass it to `$transport->registerPlugin()` method, BUT, this method requires a `Swift_Events_EventListener` object that `Swift_Plugins_Loggers_EchoLogger` does not implements.

In a 'pure' php code, it would be done this way:
~~~[php]
$logger = new Swift_Plugins_Loggers_EchoLogger();
$plugin = new Swift_Plugins_LoggerPlugin($logger); //this 'decorates' the logger, implementing the required interface
$mailer->registerPlugin($plugin); //now the $logger can be passed 'inside' the 'decorator'
~~~

I resolved this in not much confortable way (not for me, smells inconsistent), but I really would appreciate any insights after I have made the PR.

I will run the tests and maybe update them. But i have no more time today. Will PR the changes tomorrow.

**Comment by klimov-paul** [comment]
Note: at present state `yii\swiftmailer\Mailer` allows registering plugins for the transport, but not for the mailer itself.
I suppose we can advance method `getSwiftMailer()` to be consistent with `getTransport()` allowing its advanced configuration.

**Comment by germansokolov13** [comment]
@sidtj, currently for `Swift_Plugins_Loggers_EchoLogger` to work you need to configure it like this:
```
            'useFileTransport' => true,
            'transport' => [
                'class' => 'Swift_MailTransport',
                'plugins' => [
                    [
                        'class' => 'Swift_Plugins_LoggerPlugin',
                        'constructArgs' => [new Swift_Plugins_Loggers_EchoLogger],
                    ],
                ],
            ],
```
`Swift_Plugins_LoggerPlugin` is the corresponding plugin class and then you need to feed the logger class of your choice to its constructor.

The only preexisting loggers are the EchoLogger that just echos everything it gets to the standard output and the ArrayLogger that just lets you gather messages inside a variable. Another logger can be created via implementing an interface. I think the Yii Swiftmailer extension should implement its own logger to somehow integrate logging into the framework.

**Comment by sidtj** [comment]
@germansokolov13, thank you so much! I didn't know that I could instantiate a class in the constructArgs.

What about invoke the logger to get/save its results? Looking to the code I couldn't find a way, so that I had implemented it. Is there a built-in way?

**Comment by sidtj** [comment]
@klimov-paul, plugins registrations are delegated to transport (see below). So, I think there is no problem with actual implementation of the extension. See:
~~~[php]
    //Swift/Mailer.php
    public function registerPlugin(Swift_Events_EventListener $plugin)
    {
        $this->_transport->registerPlugin($plugin);
    }
~~~

I implemented a way to check if the plugin is of the 'special' type logger. If it is, I put it in a internal $_logger and the user can make a getLogger() this way:

~~~[php]
$mailer = Yii::$app->mailer; //first, we get the mailer, cause it is not singleton
$sent = $mailer->compose() //do the job
        ->setFrom($from)
        ->setTo($to)
        ->setHtmlBody($body)
        ->setSubject($subject)
        ->send();

$mailer->getLogger()->dump(); //here we can retrieve the logger
~~~
What do you think?

**Comment by klimov-paul** [comment]
I don't think extra getter should be added here.
I suppose, method `send()` should check if there is any logged error and convert them into exception.

**Comment by sidtj** [comment]
I see two problems in thrown an exception:

1. Since logs are not necesseraly problems but information, we could not see those informations, just critical problems (errors, etc);
2. I dont see how we could log those info (errors, or not) into db (maybe in a production server or whatever).

**Comment by sidtj** [comment]
3.EchoLogger dumps on real time, so that we could not get its datas, unless we use ob_* functions (more complication).

So, dump() function will still be useful for the ArrayLogger.

~~~[php]
// from swift mailer docs:

// Dump the log contents
// NOTE: The EchoLogger dumps in realtime so dump() does nothing for it
echo $logger->dump();
~~~

**Comment by sidtj** [comment]
How to use:

~~~[php]
// in configs

'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            ...
            'useFileTransport' => false, //NOTE: if true, the swiftmailer extension will not be used
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'plugins' => [
                    [
                        'class' => 'Swift_Plugins_LoggerPlugin',
                        'constructArgs' => [new Swift_Plugins_Loggers_ArrayLogger], //thanks @germansokolov13
                        // it could also be any Swift_Plugins_LoggerPlugin (e.g., the EchoLogger)
                    ],
                ],
            ],
        ],


// in controller:

$from = 'from@mail.com';
$to = 'to@mail.com';
$subject = 'My Subject';
$body = 'My Body';

$mailer = Yii::$app->mailer;
$return = $mailer->compose()
        ->setFrom($from)
        ->setTo($to)
        ->setHtmlBody($body)
        ->setSubject($subject)
        ->send();

$logger = $mailer->getLogger(); 
$logger->dump(); // could save it in a file, db, etc
~~~

**Comment by germansokolov13** [comment]
Any Swift_Plugins_Logger, not any Swift_Plugins_LoggerPlugin, a typo?

It still doesn't provide any default logging. I think there should be a default Yii-specific logger that would be possible to override.

**Comment by sidtj** [comment]
Why a yii-specif logger? Any advantages? I think Swift_Plugins_Logger does the job.

**Comment by germansokolov13** [comment]
Because you normally expect to be able to see the logs and/or errors out of the box without implementing anything. Currently the extension enforces you to implement the logger, so I think there should be a default preexisting one.

**Comment by sidtj** [comment]
It seems a good idea. But, since it would probably need to alter some standard config, I would like to hear @samdark.

**Comment by samdark** [comment]
Which config are you talking about?

**Comment by sidtj** [comment]
I am talking about commom/config/main.php that will be this:

        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_MailTransport', // standard php mail() function
                'plugins' => [
                    [
                        'class' => 'Swift_Plugins_LoggerPlugin',
                        'constructArgs' => [new Swift_Plugins_Loggers_ArrayLogger],
                    ],
                ],
            ],
        ],

It could also be in main-local.php. In this case, it would be necessary change localy on production servers.

**Comment by sidtj** [comment]
But a `Yii::error||info($message);` in send() would be useful for degub.

**Comment by sidtj** [comment]
Should the proposed in my last comment to be implemented? 
Or maybe this issue could be closed. It seems already excessively discussed, considering the problem's weight and solution.

**Comment by samdark** [comment]
Don't close it till https://github.com/yiisoft/yii2/pull/7558 is merged/

**Comment by sidtj** [comment]
And since i had **no** answer about my last question, i won't change the code.

**Comment by samdark** [comment]
Which question are you referring to? `Yii::info($message);` in `send()`? I think it's not that useful. Probably with trace level it could be.

What could improve it overall are additional docs.

**Comment by sidtj** [comment]
Makes sense. I will use `trace` instead of `info` and update the extension docs this weekend.

**Comment by sidtj** [comment]
@samdark, let me know if you think we need make some more changes. I have availability.

**Comment by samdark** [comment]
Ideally http://www.yiiframework.com/doc-2.0/guide-tutorial-mailing.html should be modified as well as readme. https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-mailing.md

**Comment by sidtj** [comment]
`docs/guide/tutorial-mailing.md` and `extensions/swiftmailer/README.md` are now updated concerning to logs.

**Comment by samdark** [comment]
Great. I think it's ready. @klimov-paul would be great if you'll take a look.

**Comment by slinstj** [comment]
@samdark, news here?

**Comment by samdark** [comment]
it is assigned to @klimov-paul so he'll merge it.

**Comment by klimov-paul** [comment]
I need to investigate this matter further.
I am unsure about #7558 approach.

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-swiftmailer/issues/4

**Comment by klimov-paul** [comment]
Merged manually
