### ISSUE TITLE
Calling unknown method: yii\db\Connection::apc()

### ISSUE THREAD

**Issue by offline-online** [yiisoft/yii2#7525]
I would like to use both file cache and apc cache in my application. Of course, somewhere I would use apc and somewhere file. I am not sure how to configure application to use two drivers, so I have this error when I try to use apc one.

My config file:

```
'cache' => [
    'class' => 'yii\caching\FileCache',
],
'apc' => [
    'class' => 'yii\caching\ApcCache',
],
```

Code where I want to use apc:

```
$result = self::getDb()->apc(function ($db) {

            return self::find()->with('post')->all();

}, 3600);

return $result;

```

This code gives me error Calling unknown method: yii\db\Connection::apc()

Am I doing something wrong? Maybe I misunderstood documentation ? Maybe something else is wrong ?

**Comment by offline-online** [comment]
If I change 

```
'cache' => [
    'class' => 'yii\caching\FileCache',
],
```

to 

```
'cache' => [
    'class' => 'yii\caching\ApcCache',
],
```

I get this error: Call to undefined function yii\caching\apc_fetch()

**Comment by samdark** [comment]
Use it as `Yii::$app->apc->get()`

**Comment by offline-online** [comment]
Where I should put that here ? 

```
$result = self::getDb()->apc(function ($db) {

            return self::find()->with('post')->all();

}, 3600);

```

**Comment by samdark** [comment]
Ah! You're trying to use it with DB connection. It should be like the following:

```php
$connection = self::getDb();
$connection->queryCache = 'apc';
$result = ->cache(function ($db) {
            return self::find()->with('post')->all();
}, 3600);
```

**Comment by offline-online** [comment]
Thanks, you made a mistake, so it is like this:

$connection = self::getDb();
$connection->queryCache = 'apc';
$result = $connection->cache(function ($db) {
            return self::find()->with('post')->all();
}, 3600);

I am getting some weird errors, and my apache crash. It seems that my APC is not installed properly
