### ISSUE TITLE
Loading assets in ajaxRender

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2#7526]
Hello,

Before appendTimestamp feature in AssetManager, Rendering with renderAjax add time to url in loading js, css. But after appendTimestamp feature again this time added in ajax loading! If we exclude this time to add to url in AjaxRender browser can use cached assets. For example look at this Url:
http://localhost:8080/frontend/web/assets/c3698bca/yii.validation.js?v=1425243821&_=1425304902310
if we exclude the latest timestamp (&_=1425304902310) browser can use cached asset.
when appendTmestamp is enabled in assetManager, We can exclude this params from url in AjaxRender and output in the final: http://localhost:8080/frontend/web/assets/c3698bca/yii.validation.js?v=1425243821

**Comment by creocoder** [comment]
Looks like serious issue.

**Comment by qiangxue** [comment]
I don't quite understand the problem. `renderAjax()` doesn't add timestamp to css/js URLs. And why enabling `appendTimestamp` would cause problem (and what is the problem?)?

**Comment by jafaripur** [comment]
enabling appendTimestamp is not cause problem. renderAjax() add timestamp to asset, Actualliy don't need to this time append. Because appendTimestamp do this.

**Comment by cebe** [comment]
where does this timestamp come from? this is not done by yii by default.

**Comment by qiangxue** [comment]
There is no code in Yii that would add the timestamp you mentioned.

**Comment by jafaripur** [comment]
I don't know, It's show for me!! I don't change anything and always use latest yii2

**Comment by samdark** [comment]
@jafaripur we need complete code to reproduce the problem. Can you come up with it starting from basic application template and adding as little changes as possible?

**Comment by SDKiller** [comment]
Maybe its `jQuery` timestamp if `ajax` was set up with `cache: false`

**Comment by jafaripur** [comment]
@SDKiller I use fancybox ajax loading.

**Comment by friek108** [comment]
This may be related to this issue encountered here (refer to the answer, not so much the question):
http://stackoverflow.com/questions/24639335/javascript-console-log-causes-error-synchronous-xmlhttprequest-on-the-main-thr

If you load html content using ajax AND that view contains javascript files, jQuery will make a call to load those files **synchronously** - and it seems to do it using `cache: false` 

Perhaps registering assets in a view that is loaded via ajax should use `jQuery.getScript()` or something similar.  It may solve both issues (of not caching and the synchronous calls) if indeed someone else is able to replicate.

**Comment by adamdry** [comment]
@friek108 do you know if there is a specific yii2 issue open for this? We are having this problem and can't think of a nice solution to avoid the problem!

**Comment by SilverFire** [comment]
@friek108 is right. http://stackoverflow.com/questions/16057546/using-jquery-if-we-append-a-script-element-why-is-the-files-url-added-with

AFAIS it's out of Yii scope

**Comment by adamdry** [comment]
Yeah fair play. Hopefully jQuery will fix. Or someone will write a plugin.

**Comment by SilverFire** [comment]
I've reproduced your problem and 
It occurs just here: https://github.com/jquery/jquery/blob/2.2-stable/src/manipulation.js?ts=4#L192

`_evalUrl` function had `cache: true` in [1.12 branch](https://github.com/jquery/jquery/blob/1.12-stable/src/manipulation/_evalUrl.js#L12), but it does not have it in [2.2 stable branch](https://github.com/jquery/jquery/blob/2.2-stable/src/manipulation/_evalUrl.js#L10)

It was added by [this commit](https://github.com/jquery/jquery/commit/15f4dec7894f1e00adbfb9bce4f870441a527bd6), and later removed by [this one](https://github.com/jquery/jquery/commit/ea2f10c104e4cf3ada1c0da12ebf4fac0d2801ca)

I think the only right way to you is to override default `_evalUrl` function in your project and add `cache: true`. [See howto](http://stackoverflow.com/questions/4536788/override-jquery-functions)

**Comment by ajoudeh** [comment]
@jafaripur add $.ajaxSetup({'cache':true}); before ajax call & the _= will be removed
