### ISSUE TITLE
Saving multiple models doesn't work properly

### ISSUE THREAD

**Issue by XzAeRo** [yiisoft/yii2#7528]
I'm reading data from an uploaded Excel file via PHPExcel, and when I try to save the data (1 model per row), Yii only saves the first one in the database.
This is what I'm doing:

In UploadController.php, I have something like this:
```php
public function actionProducts()
{
    // PHPExcel file load and sheet selection stuff
    // ...

    //  Get worksheet dimensions
    $highestRow = $sheet->getHighestRow(); 
    $highestColumn = $sheet->getHighestColumn();

    //  Loop through each row of the worksheet in turn (except the header)
    for ($row = 2; $row <= $highestRow; $row++){ 
        // New model each iteration
        $model = new \common\models\Product;

        //  Set the data to each attribute
        $model->name = $objPHPExcel->getActiveSheet()->getCell('A'.$row)->getValue();
        $model->price = $objPHPExcel->getActiveSheet()->getCell('B'.$row)->getValue();
        // Etc...

        $model->save();
    }
}
```

When that code is executed, only the first iteration of the for-loop is being saved in the database.

Now, I've debugged showing what has been setted each iteration, and also verifying that each iteration is actually happening (and not breaking). Also, the logs don't show anything abnormal.

Anyone with similar behaviours in v2.0.3?

**Comment by creocoder** [comment]
It can be caused by not valid model. Check your validation rules first or try `save(false)` to understand situation better.

**Comment by XzAeRo** [comment]
I already tried this solution, because as soon as I use `save(false)`, it works perfectly. In the model and in the database, everything except a timestamp (in unix format), are strings, and the model is ok. Also, the model was created using the Gii generator.

It's really wierd.

**Comment by creocoder** [comment]
> I already tried this solution, because as soon as I use save(false)

Great, than this is sign that you model is non valid for some cases. Now its obvious where is troubles, now make something like `VarDumper::dump($model->errors)` after `$model->save()` and you'll see concrette validation errors.

> Also, the model was created using the Gii generator.

It does not matter, Gii generate only model template, you should tune rules manually.

**Comment by Faryshta** [comment]
>   $highestRow = $sheet->getHighestRow(); 

...

>  $model->name = $objPHPExcel->getActiveSheet()->getCell('A'.$row)->getValue();

Maybe the `$sheet` used on the first line isn't the same as the used on the second one, try debugging `$higgestRow`

**Comment by cebe** [comment]
@XzAeRo please use the forum for questions, github is an issue tracker.
