### ISSUE TITLE
Include separated interface in to the frontend?

### ISSUE THREAD

**Issue by abc4IT** [yiisoft/yii2#7538]
Dear Community,

I'm using the Yii2 advanced application (v.2.0.2). I have all my data in the frontend and backend folder and i would like to create a separated folder in the base of Yii. In this separated folder i have different subfolder with an ActiveRecord class, form class and a view. The idea behind separating this files is to have products for my shop, which contains different work processes. This processes could also include Python scripts or others.

Is it possible to create a controller in this separated folder and then just switch from the frontend to this subfolder controller?

Overall the most Important is that this files need to be separated!

best regards
abc4IT

**Comment by creocoder** [comment]
@abc4IT You have better answer chances on official forums. This is issues tracker only.

**Comment by Sammaye** [comment]
Can you explain a litle more, how do you expect the python scripts to interact with Yii2, or for that matter PHP? It sounds like you are just asking for logical folder structuring

**Comment by abc4IT** [comment]
I want to redirect from the frontend SiteController to the created ProductController in my separated subfolder.

Folders:

-frontend
--assets
--config
--controller
--models
--runtime
--views
--web
--widgets

-subfolder
--ProductClass.php
--ProductController.php
--ProductForm.php
--ProductView.php

**Comment by Sammaye** [comment]
Normally you would use the `common` folder for this and extend the common controller into the frontend and backend allowing you to redirect on both sides.

**Comment by Sammaye** [comment]
So yeah, this does not seem to be a lacking feature

**Comment by klimov-paul** [comment]
@abc4IT, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
