### ISSUE TITLE
Support for Controller::missingAction()

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2#7541]
Please could you add support for missing action into Yii2 just like in Yii1?
It was already requested in #754.

Here's use case from our current project:

* we have CMS static pages in database, that are added by a customer. Customer adds HTML + link identifier, e.g. link="privacy-terms"
* we never know, what static page will customer add, but we always want to have pretty URL, like www.site.com/privacy-terms
* we cannot add rule into /config/web.php because there is lots of static pages and we cannot update server any time.
* our current solution is to catch missing route in "actionError" do database check and if we have database match against $_GET['action'], we will return HTML content from DB. The problem is, headers always set 404 - page not found, even though HTML output is corrent. If database no match, we will run error. Here is modified error handler:
~~~
public function actionError()
{
	// check whether we have any searched term (slug)
	$slug = empty($_GET['action']) ? '' : htmlspecialchars($_GET['action']);
	$exception = Yii::$app->errorHandler->exception;
	if($exception instanceof \yii\web\NotFoundHttpException && $slug){
		// we have missing page, let's try to find static content
		$page = StaticPage::findOne(['slug' => $slug]);
		if($page){
			// OK, found static page
			return $this->render('static', ['model' => $page]);
		}
	}
	return (new \yii\web\ErrorAction('error', $this))->run();
}
~~~
* if we could check the database BEFORE throwing error, that would be best solution for us. No need to modify error handler, and no 404 headers.

Or can you suggest how to implement this in a proper way without missingAction support?
Thank you very much.

**Comment by klimov-paul** [comment]
it is better to create single custome URL rule, which will seek your database for the custome pages and always use single 'controller/action' to process them.

**Comment by Alex-Code** [comment]
I also have dynamic pages generated from the db so I created a new `UrlRule` class to catch any url's not already matched by previous static rules.

**Comment by klimov-paul** [comment]
See:
https://github.com/yiisoft/yii2/blob/master/docs/guide/runtime-routing.md#creating-rule-classes-

**Comment by lubosdz** [comment]
OK, guys, it's not that straightforward as it was in Yii1, but it works.
Thank you.
