### ISSUE TITLE
[ENH] fresh command

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#7542]
hi,

it would be nice to include a fresh command in Laravel to remove models, controllers , ... created by default in basic and advanced templates.

For example : 
// execute command in basic template
php yii fresh

it remove the following files in folders:
 * assets/*
 * commands/*
 * controllers/*
 * mail/layouts/*
 * models/*
 * tests : 
   * tests/codeception/acceptance/*  
   * tests/codeception/functional/*
   * tests/codeception/unit/models/*  
 * views : 
   * view/si1te/*
   * layouts/main.php
 * web : 
   * web/favicon.ico
   * css/*
 
 this folders should be custom in config/console.php

**Comment by samdark** [comment]
Isn't it better to create empty application template?

**Comment by klimov-paul** [comment]
This does not make any sense. New application template should be created for this.

**Comment by SDKiller** [comment]
I think it makes sense for crackers - to break someone site by one command :)

**Comment by pana1990** [comment]
Laravel has fresh command and it seems nice for yii... but it is not priority, i close issue.

Thanks for comments :)
