### ISSUE TITLE
Make active record function attributes() static

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#7543]
The attributes() function calls the static getTableSchema function. So it seems there is no need to instantiate the model tho get the attribute names.  

```php
public function attributes()
    {
        return array_keys(static::getTableSchema()->columns);
    }
```

Background: I want copy some rows of wihtin a table and need to exclude the autoincrement column from the list of saved columns.

**Comment by klimov-paul** [comment]
Duplicates #3651
