### ISSUE TITLE
change url

### ISSUE THREAD

**Issue by rahulsinh** [yiisoft/yii2#7545]
@samdark http://local.xyz.com/site/default/view/?id=2&alias=x+y+z+Program  i have following url i want to change using url manager in yii2 into http://local.xyz.com/Programs/2-x-y-z-Program how to rewrite url.

**Comment by samdark** [comment]
```php
'Programs/<id>-<alias>' => 'site/default/view'
```

Please use forums next time since issue tracker is for framework bugs and feature requests.

**Comment by rahulsinh** [comment]
thanks @samdark let me know how to  remove + between x+y+z+Program

**Comment by samdark** [comment]
Don't specify it in URL.

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/yii-behaviors-sluggablebehavior.html

**Comment by rahulsinh** [comment]
@samdark  how to remove ?alias
 http://local.advance.com/programdetail/?alias=Child+Care+Volunteering+Program
