### ISSUE TITLE
Client validation should be disabled if 'when' is used

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#7546]
I suggest to skip clientside validation for an input field, when the following conditions are met:
- A `when` callback is set on a rule AND
- no `whenClient` is configured

Because if you use `when` you obviously only want to validate under certain conditions - otherwhise you'd not use it. But (without a `whenClient` function) the validation is still always performed on the clientside. So `when` practically has no effect at all.

As a workaround I now always have to set `['enableClientValidation' => false]` in the field options, which is quite inconvenient.

**Comment by samdark** [comment]
What are use cases for specifying `when` but not specifying `whenClient`?

**Comment by mikehaertl** [comment]
Your question implies, that you can't think of a valid use case. Even if that was the case, then the above change wouldn't hurt you, as the condition would never be met for you.

The use case for me is:

I have a dependend validation: A field is only required if certain form values match a condition that I can only check against the database. Yes, you could add some js code that does an AJAX request - but that's tedious and you may simply want to rely on server validation as a fallback. Still I want all other fields to do clientside validation where possible.

I should not have to touch any view files, just because I added some more validation logic.

**Comment by SilverFire** [comment]
For the future: `enableClientValidation` may differ from the `whenClient` in ajax validation.

whenClient | enableClientValidation | Result
------------ | ------------- | ------------
`null|true`  | `true` | JS+AJAX client validation
`false` | `true` | AJAX-only client validation
`null|true` | `false` | Neither JS nor AJAX client validation

**Comment by mikehaertl** [comment]
Coming back to this rather old issue: I still thinks it's valid.

Let me try to phrase it better:

If you define `when` but not `whenClient`  this means: Whether the validation rule should be applied is decided on the server side on form submission. So on the client side you don't know, whether the rule should be applied or not. In that case there must not be any client validation as this would assume, that the rule **is always** applied - which is wrong.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
