### ISSUE TITLE
ActiveForm - initiate without start - end form tags

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2#7547]
Hi,

Is there any way to initiate ActiveForm without actually rendering start - end tags inside view?
This should be optional probably for ajax requests (or generally).

In Yii1 there was possibility to return captured output and eventually throw it away.
In Yii2 widgets (=also ActiveForm) are always returned and rendered.

Here's use case:
We need to inject into existing HTML form 3 partial views (subviews) via ajax request.
Each subview renders couple of form input fields that belong to ActiveForm.
However, when I initiate ActiveForm in subview, it always injects also start - end tags into returned HTML. We only need what is exactly inside `<form> . . . </form>` tags.

I did not find any example on this situation anywhere, therefore ability to initiate ActiveForm without rendering tags could be useful in general.
Or did I miss something how to render part of ActiveForm without opening - closing form tags?
Thank you.

**Comment by samdark** [comment]
I don't think it's possible now. How are you dealing with client validation in this case?

**Comment by Alex-Code** [comment]
Might be possible using blocks.

```
$this->beginBlock('start');
$form = ActiveForm::begin();
$this->endBlock();

echo $form->field(...);

$this->beginBlock('end');
ActiveForm::end();
$this->endBlock();
```

**Comment by omnilight** [comment]
Or simply usign `ob_start(); ... ob_end_clean()`

**Comment by lubosdz** [comment]
@samdark Client validation will work OK without `<form> ..</form>` tags because it will be rendered by renderAjax view and parsed into DOM in browser. Returned HTML will be attached into some <div> container.

@Alex-Code 
Does not work - i receive exception
~~~
Expecting end() of yii\bootstrap\ActiveForm, found yii\widgets\Block
~~~

@omnilight 
Does not work, widgets are stacked and rendered at one time at the end of view rendering.
There's no direct output into output buffer from widgets.

**Comment by omnilight** [comment]
@lubosdz 
No, when you call `ActiveForm::begin()` or `ActiveForm::end()` it's rendres opening and closing tags directly at the moment of calling this methods.

So you can use it in the following way
```php
<?php ob_start(); $form = ActiveForm::begin(); ob_get_clean(); ?>

Your code

<?php ob_start(); ActiveForm::end(); ob_get_clean(); ?>
```

**Comment by lubosdz** [comment]
@omnilight That worked. Actually I tested this solution before, but used incorrect function `ob_end_clean()` instead of `ob_get_clean()`.

Thanx a lot.

**Comment by samdark** [comment]
Since it's quite specific and there's workaround I prefer not to do anything about it in the core framework.

**Comment by farooqv** [comment]
@omnilight 
<?php ob_start(); $form = ActiveForm::begin(); ob_get_clean(); ?>
Your code
<?php ob_start(); ActiveForm::end(); ob_get_clean(); ?>

It clean/remove all the form fields :(

**Comment by gooverdian** [comment]
Workaround listed here is not working, when used inside a view.
Here is another one, I'm using now:
```php
/* @var $formId Some form id attribute received via ajax */
$form = new ActiveForm();
$form->field($model, '['.$model->id.']comment')->textarea();
foreach($form->attributes as $attribute) {
    $jsonAttribute = \yii\helpers\Json::htmlEncode($attribute);
    $this->registerJs("jQuery('#$formId').yiiActiveForm('add', $jsonAttribute);");
}
```
It's working, but you got to use `ActiveForm::$attributes`, which is `@internal`.

As for the issue itself, it's use case is dynamic forms, inputs of which is added on the fly to the form. Using `attributes` eases the process of the validation rules creation picking them from the model itself.

Is there any other easier way of doing that maybe?

**Comment by gooverdian** [comment]
@samdark 
Just in case you didn't see previous comment, because I edited it to include your tag, I'll post another one (and only), so you can see and possibly answer it.

**Comment by samdark** [comment]
It's from 2015 so I can't really remember what's the issue was about immediately. Get to Slack: https://join.slack.com/t/yii/shared_invite/MjIxMjMxMTk5MTU1LTE1MDE3MDAwMzMtM2VkMTMyMjY1Ng It's better to discuss there or at the forums.
