### ISSUE TITLE
Timestamp and Blameable Behaviors Same value for update and create.

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii2#7548]
[
            'class' => TimestampBehavior::className(),
            'createdAtAttribute' => 'create_time',
            'updatedAtAttribute' => 'update_time',
            'value' => new Expression('NOW()'),
        ],

will add the same value in create and update.  It makes no sense to fill update on create. They are separated for a reason.  I think they should be kept that way.  or at lease give us the options to set it on update and create not just assume we want that to happen. 

I have to do date compares to see if items have updated. Blameable does the same thing as well.   I don't want to set update to false either because i need it to put a value into update when im actually updating not creating.

 if (empty($this->attributes)) {
$this->attributes = [
BaseActiveRecord::EVENT_BEFORE_INSERT => [$this->createdAtAttribute, $this->updatedAtAttribute],
BaseActiveRecord::EVENT_BEFORE_UPDATE => $this->updatedAtAttribute,
];
}

should be 

 if (empty($this->attributes)) {
$this->attributes = [
BaseActiveRecord::EVENT_BEFORE_INSERT => $this->createdAtAttribute,
BaseActiveRecord::EVENT_BEFORE_UPDATE => $this->updatedAtAttribute,
];
}

**Comment by SDKiller** [comment]
I've already raised this issue - this won't be changed

https://github.com/yiisoft/yii2/issues/4952#issuecomment-54808416

**Comment by creocoder** [comment]
> It makes no sense to fill update on create.

This is by design. It absoluttely make sense to fill update on create in 99% real world application cases. If you need different behavior, you have to specify attributes.

**Comment by SDKiller** [comment]
Actually it isn't.

With initial update attribute is `null` it is more simple and efficient (you dont have to compare dates):

1) to select records that were updated after creation;
2) to select record that never been updated

I don't know about 99% real world applications (but know several which take more than 1% ;) ).

**Comment by creocoder** [comment]
@SDKiller

```
1) to select records that were updated after creation;
2) to select record that never been updated
```

Both can be solved by simple SQL queries.

For all other cases having updated === created for newly created records have **significant** advantages. This is why it by design and by default. Its better for both experienced and not experienced developers. There is only 1% cases when you may want updated is NULL for newly created records and you should take full responsibility for the decision. This is why you have change attributes property for that.

**Comment by samdark** [comment]
It was discussed before it was implemented. Indeed it's a design decision and defaults will stay as is.

**Comment by skworden** [comment]
@creocoder  just curious what are the significant advantages?  


@SDKiller 

I just created a new behavior to solve my problem it's exactly the same as the other ones except for the following:

i added public var:
````
$saveUpdateOnCreate =TRUE;
````
and change the problem line to: 
````
 BaseActiveRecord::EVENT_BEFORE_INSERT => (!$this->saveUpdateOnCreate)?[$this->createdAtAttribute, $this->updatedAtAttribute]:$this->createdAtAttribute,
````
````
then use it like:
[
'class' => TimestampBehavior::className(),
'createdAtAttribute' => 'create_time',
'updatedAtAttribute' => 'update_time',
'value' => new Expression('NOW()'),
'saveUpdateOnCreate'=>false,
],
````
I did this for both Timestamp and Blameable.

**Comment by samdark** [comment]
Instead of subclassing you can configure it while attaching:

```php
public function behaviors()
{
    return [
        [
            'class' => TimestampBehavior::className(),
            'attributes' => [
                BaseActiveRecord::EVENT_BEFORE_INSERT => $this->createdAtAttribute,
                BaseActiveRecord::EVENT_BEFORE_UPDATE => $this->updatedAtAttribute,
            ],
        ],
    ];
}
```

**Comment by creocoder** [comment]
@skworden 

> just curious what are the significant advantages?

For example content sorting.

@samdark Additional friendly property like `saveUpdateOnCreate` probably make sense!
