### ISSUE TITLE
SluggableBehavior do not work

### ISSUE THREAD

**Issue by offline-online** [yiisoft/yii2#7553]
I have defined this behavior as per documentation instructions.

```
public function behaviors()
{
    return [
        TimestampBehavior::className(),
        [
            'class' => SluggableBehavior::className(),
            'attribute' => 'title',
        ],
    ];
}
```
In my config url manager I have defined custom rule that will give me clean urls like this: ```example.com/article/1```

```
'urlManager' => [
    'class' => 'yii\web\UrlManager',
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'rules' => [
        'article/<id:\d+>' => 'article/view',
    ],
],

```

I would like to output my article title in url like this: ```example.com/article/1/My-first-post```

But I am not getting title in URL. 

My view action is:

```
public function actionView($id)
{
    return $this->render('view', [
        'model' => $this->findModel($id),
    ]);
}
```

What is wrong ? Thanks

**Comment by creocoder** [comment]
Please use official forums to ask questions. You have wrong rules. If you expect title in url you have to make corresponding rule for such case.

**Comment by offline-online** [comment]
Sorry, I thought that since I did everything that documentation says, that something must be wrong. But I do not understand what I have to do. What do you mean by this ```If you expect title in url you have to make corresponding rule for such case.```

**Comment by samdark** [comment]
You should pass slug instead of URL:

```php
article/<slug>' => 'article/view',
```

```php
public function actionView($slug)
{
    return $this->render('view', [
        'model' => $this->findModel($slug),
    ]);
}
```
