### ISSUE TITLE
PSR-3: yii\log\Logger refactoring proposal

### ISSUE THREAD

**Issue by kop** [yiisoft/yii2#7555]
Hi guys.

This is related to #1660 and #1676.

I'm developing an extension to integrate Monolog with Yii2 logger - I believe it would be really cool to have all Monolog handlers supported by Yii2. And I came to an idea already how to make it 100% Yii-compatible and add all Monolog features. But I have another big problem now: PSR-3.

I know, it's decided that Yii2 logger will not support PSR-3, but current implementation does not allow even to extend it, and add such support in the extensions - interfaces mismatch:

PSR-3 requires:
`log($level, $message, array $context = [])`

while Yii2 has:
`log($message, $level, $category = 'application')`

I think we could try to make a small refactoring in order to make it possible for people who needs PSR-3 to have it working:

1. Rename class `yii\log\Logger` to `yii\log\BaseLogger`;
2. Rename method `yii\log\BaseLogger::log()` to `yii\log\BaseLogger::logInternal()`;
3. Create class `yii\log\Logger` extends `yii\log\BaseLogger` that will implement method `log()`:
```
public function log($message, $level, $category = 'application')
{
    $this->logInternal($message, $level, $category);
}
```

Such approach will allow to keep an existing API - no one will even notice changes. In the same time it will allow extension-makers to extend `yii\log\BaseLogger` and implement any of their dirty fantasies :)

**Comment by RomeroMsk** [comment]
@kop, :+1: 
I can use this for better and cleaner way of logging to GrayLog.

**Comment by RomeroMsk** [comment]
@kop, will you try to implement this with adapter, as @creocoder mentioned in PR?

**Comment by kop** [comment]
Hi, @RomeroMsk. Yes, I will definitely implement this idea soon. Just had no time to work on this yet.

**Comment by RomeroMsk** [comment]
@kop, ok, thank you, will wait.

**Comment by klimov-paul** [comment]
> current implementation does not allow even to extend it

You can extend `yii\log\Logger` or write your own. You can setup another logger usage via `Yii::setLogger()`:
```php
Yii::setLogger(Yii::createObject('MyLogger'));
```

Since discussion at #7556 proves proposed refactoring inconsistent. I can't see any issue here.

**Comment by RomeroMsk** [comment]
@klimov-paul, can you please explain where exactly we can use `Yii::setLogger`? I've found only one place: before `$application->run();` in entry script. Maybe there is another way, not in git-ignored script?

**Comment by klimov-paul** [comment]
It is up to you you can invoke it whenever after 
```php
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
```

You may also use `Application::boostrap` for this purpose.

**Comment by RomeroMsk** [comment]
But I can't use it in `common/config/bootstrap.php`, as I wish. I'm getting blank page with ho errors in this case.

**Comment by RomeroMsk** [comment]
@klimov-paul, can you show a detailed working example of extended `yii\log\Logger`?
What I did:
1. Created `common\components\Logger` which extends `yii\log\Logger` (nothing inside, just dummy class).
2. Added this line to entry script, right before `$application->run();`:
```php
Yii::setLogger(Yii::createObject('common\components\Logger'));
```
What I've got:
All logs which was writen after this line are missed. For example, if I look into debug toolbar, I see only first three framework traces:
![image](https://cloud.githubusercontent.com/assets/4639951/9306840/49edae52-4514-11e5-9f60-be36924ebd2d.png)
Also I tried to add this line to my controller action before sending log message, just to see the difference. And I've got almost the same result (15 log messages instead of 3 and no logs after that).

**Comment by klimov-paul** [comment]
> Added this line to entry script, right before $application->run();:

This is too late. `Yii::setLogger()` should be invoked before `Application::__construct()`.
Another way will be set `logger` explicitely to the `yii\log\Dispatcher` in the application config:
```
return [
    'components' => [
        'log' => [
            'logger' => new MyLogger()
        ],
    ],
];
```

**Comment by RomeroMsk** [comment]
@klimov-paul, and this variant I tried too. Blank page.

**Comment by klimov-paul** [comment]
Well, I can not debug your program for you.
Enable error reporting at the earaly beginning of the program, set `display_errors = on` and see what is causing the problem.

**Comment by RomeroMsk** [comment]
Sorry, got this. I need to use another name for my class, not `Logger`.
Now I have no errors, but also no logs.
```php
return [
    'components' => [
        'log' => [
            'logger' => new common\components\ExtLogger(),
            // Config of dispatcher: targets, traceLevel, etc.
        ],
    ],
];
```
```php
<?php
namespace common\components;

class ExtLogger extends \yii\log\Logger
{
}
```
That's all I have. Did you try this way for yourself?

**Comment by klimov-paul** [comment]
Look, this is not a forum - and I have other things to do, so I give you the last advice:
you should set `Yii::setLogger()` one way or another in order `Yii::log()` to use you logger instead of standard one. `Disptatcher::logger` is used to specify which logger should be used as a source.

**Comment by RomeroMsk** [comment]
I understand, how it must work, but it is not working. That's why I asked if you tried this for yourself.
You closed this issue telling that Yii2 have another way for logger extending, but there are no docs for this functionality and no working example for now.

**Comment by klimov-paul** [comment]
> I understand, how it must work, but it is not working.

Why so helpless? It is a shame to have a problem invoking single method at the correct place.

> You closed this issue telling that Yii2 have another way for logger extending, but there are no docs for this functionality and no working example for now.

Fine, here you go:
```php
<?php

error_reporting(E_ALL);
ini_set('show_errors', true);

// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

class MyLogger extends \yii\log\Logger
{
    public function log($message, $level, $category = 'application')
    {
        parent::log($message, $level, 'OVERRIDDE!!!');
    }
}

$logger = new MyLogger();
Yii::setLogger($logger); // ATTENTION HERE!!!

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'debug'],
    'modules' =>[
        'debug' => [
            'class' => 'yii\debug\Module',
            'allowedIPs' => ['*'],
        ]
    ],
    'components' => [
        'request' => [
            'enableCookieValidation' => false,
        ],
        'user' => [
            'identityClass' => 'app\models\User',
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
    ],
];

(new yii\web\Application($config))->run();
```

> there are no docs

Try to use your head instead! Documentation will NEVER cover EVERYTHING. There will be always some use cases, which are not described expliciltely.

**Comment by RomeroMsk** [comment]
Why so nervous? Not everyone has so broad experience. Don't know where my mistake was in variant with Dispatcher config, but `Yii::setLogger()` is working fine right now, after revision of my code with help of your example. Thanks, that's what I need.
And about documentation. I meant that there is nothing about `Yii::setLogger()`: how to use it and where to place it.

**Comment by cebe** [comment]
@RomeroMsk github is for issue and feature tracking. please use the forum, stackoverflow or IRC for such questions.
