### ISSUE TITLE
pretty url action params not work on Camel case module or controller name

### ISSUE THREAD

**Issue by monochrome-yeh** [yiisoft/yii2#7557]
controller  class OneAndTwo
controller id will be one-and-two

but pretty url not work,when my action have params

example:
public fucntion actionTest($id) {}
yii's any url create tool will return one-and-two/test?id=xxxxxxxxxxx

if my controller not a camel case
url create tool will return oneandtwo/test/xxxxxxxx

how can i fix it ?

**Comment by samdark** [comment]
How do you create URLs?

**Comment by creocoder** [comment]
@samdark 

>if my controller not a camel case
>url create tool will return oneandtwo/test/xxxxxxxx

Where is trouble?

> how can i fix it ?

@samdark There is nothing to fix.

**Comment by samdark** [comment]
Hmm... right. If controller action isn't camel-cased it should not return camel cased URL. If you need it, use URL manager.

**Comment by monochrome-yeh** [comment]
ok

i found my problem

in my urlManager config

rule => [
        '<controller:one-and-two>/<action:test>/<id:\w+>' => 'one-and-two/test'
]

and when i use camel case controller name (OneAndTwo)

yii's any url create will return 
        one-and-two/test?id=xxxxxx

that's different to

rule => [
        '<controller:one-and-two>/<action:test>/<id:\w+>' => '<controller>/<action>'
]

url tool will return
        one-and-two/test/xxxxxx

if i havent use camel case controller name (Nocamel)

rule => [
        '<controller:nocamel>/<action:test>/<id:\w+>' => 'nocamel/test'
]

return
        nocamel/test/xxxxxx
