### ISSUE TITLE
memcache problem - Michael

### ISSUE THREAD

**Issue by oasmichael** [yiisoft/yii2#7564]
There is a issue in yii/caching/MemCache.php.When you publish your yii2 application,if memcache server is in another server,there will be a problem with the timestamp in that php class,i suggest to use seconds when you set up the cache time less than or equal 30 days accordding to the php extension memcached.so.Because the two servers may have time difference.
pls.I am a yii fan(a php manager of 5 people in a Chinese company).My team members are all focus on yii2 applications since it comes out.I hope to join your github team to develop some code to improve myself.

**Comment by cebe** [comment]
How do you think yii could solve this issue? Normally you should use something like ntp to synchronize server times.

**Comment by oasmichael** [comment]
there is a way to solve the problem like this.
$expire = $duration > 0 ? ($duration > 60 * 60 * 24 * 30 ? ($duration + time()) : ($duration)) : 0;

**Comment by oasmichael** [comment]
so we can ignore some small time difference when publish the code

**Comment by oasmichael** [comment]
without using ntp

**Comment by samdark** [comment]
I don't think it's a good idea. It's viable to be able to be precise when specifying caching time. Any rounding isn't really acceptable.

As @cebe suggested, you should properly set up ntp so your servers are in sync timewise.

btw., welcome to GitHub, feel free to work on any issues and send pull requests ;)
