### ISSUE TITLE
yii2-pjax version number is 2.0.2 on new install of yii2

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#7565]
On new install:
```
   ...
  - Installing bower-asset/yii2-pjax (v2.0.2)
   ...
  - Installing yiisoft/yii2 (2.0.3)
   ...
```   

Or `yii2-pjax` will no more follow framework version number?

**Comment by qiangxue** [comment]
Yes, this is expected since `yii2-pjax` is a pure js library independent of Yii 2.0. There is no change since its 2.0.2 release.
