### ISSUE TITLE
Change message for CompareValidator to consider compareAttribute

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#7566]
When using `compareValue`, the message for non-equal operators is ok:
`{attribute} must not be equal to "{compareValue}"`
But when using `compareAttribute` message must be like this:
`{attribute} must not be equal to {compareAttribute}`.

For example, when we comparing `begin` (with value 90) and `end` (with value 100) with operator '<' we will get something like this:
`Begin must be less than "100"`
But this will be more clear for user:
`Begin must be less than End`.

**Comment by samdark** [comment]
Agree. @yiisoft/core-developers opinions?

**Comment by cebe** [comment]
:+1:

**Comment by qiangxue** [comment]
Fine with me.

**Comment by sidtj** [comment]
@samdark, can I work on this next week?

**Comment by samdark** [comment]
Sure. It's yours.

**Comment by slinstj** [comment]
It seems we have some other similar problems:

In a Model:
~~~[php]
    public function rules() {
        return [
            [['attr3'], 'compare', 'compareAttribute' => 'attr2'],
        ];
    }
~~~
My model:
~~~[php]
$model->attr2 = 2;
$model->attr3 = 3;
~~~
`validate()` results in:
~~~[php]
[
    'attr3' => [
        0 => 'Attr3 must be repeated exactly.'
    ]
]
~~~
Shouldn't this result in ...
~~~[php]
[
    'attr3' => [
        0 => 'Attr3 must be equal to Attr2.'
    ]
]
~~~
... or have I missed something?

**Comment by slinstj** [comment]
I will update the tests, but this is what we have now:
User can still use `compareValue` or `compareAttribute` like placeholders, but the default messages will use a new `compareInternal` placeholder. The actual content of it will be decided in runtime.

**Comment by slinstj** [comment]
Tests updated. It seems good now. @samdark?

**Comment by slinstj** [comment]
@samdark?

**Comment by RomeroMsk** [comment]
@samdark, are you going to merge this soon?

**Comment by cebe** [comment]
thanks for poiting it out, the PR was not set for a milestone. will check it.
