### ISSUE TITLE
Column alias in select() not working in my case.

### ISSUE THREAD

**Issue by myc0210** [yiisoft/yii2#7570]
i have two table one is `app` table the other is `user` table both has column named `name`.
now i run following code:
```
$query = User::find()->select(['user.name','app_name' => 'app.name', 'user.create_time', 'app_id'])->innerJoinWith('app')->where(['permission_level' => 0, 'parent_id' => $id])->andWhere(['LIKE', 'user.name', $uname])->andWhere(['LIKE', 'app.name', $aname])->all();
```
The $query only has 3 columns which is name, create_time, app_id. why the app_name column is missing? can anyone help me. Thank you.

**Comment by myc0210** [comment]
I replace above code with this one utilizing query only, the result is what i want as four columns appears correctly. Anyone can tell me what's wrong with my above code. Thank you.
```
$query = (new Query)->select(['uname' => 'user.name', 'aname' => 'app.name', 'user.create_time', 'app_id'])->from('user')->innerJoin('app', 'user.app_id = app.id')->where(['permission_level' => 0, 'parent_id' => $id])->andWhere(['LIKE', 'user.name', $uname])->andWhere(['LIKE', 'app.name', $aname])->all();
```

**Comment by mdmunir** [comment]
try use `asArray()->all()`

**Comment by myc0210** [comment]
Thanks mdmunir. Your solution also works. Do you know why this happens?

**Comment by cebe** [comment]
if you select a column name that does not exist in the model, you have to create a property in the model for it.

**Comment by Faryshta** [comment]
@myc0210 http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#selecting-extra-fields i hope this helps to explain how you can handle extra columns.

**Comment by ddimitrov899** [comment]
Documents::find()->select(['title' => 'Title', 'Redirect', 'RedirectClass'])->all(); 

return only Redirect and RedirectClass.
but if delete title returns all.
any suggestions?
