### ISSUE TITLE
PHPStorm support for ActiveRecord methods

### ISSUE THREAD

**Issue by katzz0** [yiisoft/yii2#7572]
Since 2.0.3 I have problem with type hint at the PHPStorm 8. It considers the return type of method findOne() is 'null|static' (real @return static|null but PHPStorm detects null|static) and hence don't hint real model type. In previous versions the return type was just 'static' and all works fine. It is strange the return type static|null because of for empty of object null is the normal case.

I know that Yii core team use different IDEs and PHPStorm also. How you solve this problem? Thanks.

**Comment by lynicidn** [comment]
dublicate https://github.com/yiisoft/yii2/issues/7404
