### ISSUE TITLE
DB: Need to modify Command in ActiveRecord::{insert,update}

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7573]
I try to insert into Apache Cassandra data what are short-lived (authentication tokens etc.). For this reason, it has TTL option in it's syntax: [INSERT](http://www.datastax.com/documentation/cql/3.0/cql/cql_reference/insert_r.html), [UPDATE](http://www.datastax.com/documentation/cql/3.0/cql/cql_reference/update_r.html).

But in Yii2's ActiveRecord insert and update methods, where's no way to modify Command.

Will the core team implement this, or should I do it for myself ?
What is the best way ? Make the Command accept some extra parameters or ActiveRecord itself ? Trigger events around createCommand() and/or execute() in ActiveRecord, so the SQL can be modified or some extra methods called on my subclassed Command ?

**Comment by cebe** [comment]
You will have to extend it yourself, when you build the AR layer for Cassandra, you can override the insert method and add options like it is done for elasticsearch here: https://github.com/yiisoft/yii2/blob/master/extensions/elasticsearch/ActiveRecord.php#L418

**Comment by mcd-php** [comment]
Overriding here will mean copypasting long methods and watching them for changes in original, to avoid discrepancies as framework evolves.

Maybe add `$options` to `ActiveRecord::insert()/update()` and `Command` in core framework and simply not use it for MySQL, only for alternatives ?

**Comment by cebe** [comment]
what we could do is to create a `createCommand()` method that you can override to set additional params on the command. Would that help you?

**Comment by mcd-php** [comment]
Now I edited `yii2` in `vendor` and implementing hot-patch system for this ( https://github.com/composer/composer/issues/1193#issuecomment-77341582 ), I will be able to propose patch/PR and  discuss then my project feature will work.

**Comment by samdark** [comment]
Could be useful for MySQL:

```sql
SELECT id FROM queue WHERE is_run = 0 ORDER BY date_task ASC LIMIT 1 FOR UPDATE
```

**Comment by nineinchnick** [comment]
`FOR UPDATE` is also [supported by PostgreSQL](http://www.postgresql.org/docs/9.0/static/sql-select.html).

**Comment by mcd-php** [comment]
Here's my changes - at least, my application works with them. If you are interested or if this is required for full understanding, I may share the Cassandra library part.

I'm looking forward for solution on upstream side - patches are not a good way to go.

Now I can't say it taking any obligation, but at first glance I think your idea with `createCommand()` is quite good:
```php
class ActiveRecord extends Model {
    public function createCommand() {
        /* ... */
        $command->setOptions($this->getCommandOptions());
        return $command;
    }
}

class \myvendor\yii2\db\cassandra\Command extends \yii2\db\Command {
    public function insert($table, $columns) {
        $params = [];
        $queryBuilder = $this->db->getQueryBuilder();
        $queryBuilder->setOptions($this->getOptions());
        $sql = $queryBuilder->insert($table, $columns, $params);
        return $this->setSql($sql)->bindValues($params);
    }
}

class \myvendor\yii2\db\cassandra\QueryBuilder extends \yii\db\QueryBuilder {
    public function update($table, $columns, $condition, &$params) {
        $sqlUpdate = parent::update($table, $columns, $condition);
        if ( $this->hasOptions('using') ) {
            $strUsing = $this->buildUsing($this->getOptions('using'),$params);
            $sqlUpdate = str_replace(' SET',' ' . $strUsing . ' SET',$sqlUpdate);
        }
        return $sqlUpdate;
    }
}
```

The only thing remaining is to give it consistent name all through the call stack - since "options" is just like "object", it is near "anything"

**Comment by mcd-php** [comment]
After big thinking I decided that yours is better than mine - `createCommand()` allows custom logic and setting multiple kinds of domain-specific options upon subclassed `Command`, while passing `$options` through calls just proliferates parameters (smell!) and puts restrictions on expressiveness since `$options` is mere array.

So I think you should extract `createCommand()` method in `{Base}ActiveRecord` (if I do so, I may overlook something and introduce bugs out of ignorance) and I will override it and convert my application.

I see it having only one line in default version:
```php
class ActiveRecord {
    public function createCommand() {
        return static::getDb()->createCommand();
    }
}
```

**Comment by mcd-php** [comment]
Oops, we also have `\yii\db\BaseActiveRecord::link()`, it is deep as abyss and where's no idea on how to bring engine-specific options into it in generic way.

Any thoughts on breaking it up into small logic 'atoms' what can be precisely overridden or swapped via DI ?

For the sake of upcoming weekend, I will now create ad-hoc relation manager in domain model, but again it's not a good way to go ...

**Comment by mcd-php** [comment]
Will this ever be implemented ?

Should I implement `ActiveRecord->createCommand()` to replace direct `$db->createCommand()`, in what places ? Only in `\yii\db\ActiveRecord()` ? Should I cover it with tests, and what to test ?

I now live with patch, it's lot of pain.

**Comment by nineinchnick** [comment]
This could be loosely related to #7674.

**Comment by klimov-paul** [comment]
Such feature is not generic.
For full Cassandra support you should develop a solid solution as it is done for the Sphinx:
https://github.com/yiisoft/yii2-sphinx

**Comment by grikdotnet** [comment]
There is no way to alter the SQL for INSERT/UPDATE after genering it.
Overriding ActiveRecord::insertInternal() and updateInternal() is difficult and requires diving deep into guts of TableSchema.
This makes problems for converting autoincrement IDs to binary UUIDs when one has to alter the insert query with ` VALUES (unhex($UUID),...) `

A generic for yii "who cares" ideology.
