### ISSUE TITLE
Undefined class constant 'TYPE_DOUBLE'

### ISSUE THREAD

**Issue by mydesign** [yiisoft/yii2#7574]
PHP Fatal Error – yii\base\ErrorException
Undefined class constant 'TYPE_DOUBLE'
1. in /basic/vendor/yiisoft/yii2-gii/generators/model/Generator.php at line 236
2. yii\base\ErrorHandler::handleFatalError()

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/7490
