### ISSUE TITLE
Composer Broken in Yii2

### ISSUE THREAD

**Issue by osCMattiFinn** [yiisoft/yii2#7575]
I have the latest version of Yii2 Advanced installed.

I have tried to install JUI and Bootstrap using composer and the install fails each time.

The errors are always as follows:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stabl
e -> no matching package found.
    - Installation request for yiisoft/yii2 == 2.0.3.0 -> satisfiable by yiisoft
/yii2[2.0.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-installation.html:

```
composer global require "fxp/composer-asset-plugin:1.0.0"
```
