### ISSUE TITLE
Yii 2.0 extension template

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#7577]
Could be useful to provide a dummy repo similar to https://github.com/thephpleague/skeleton

**Comment by samdark** [comment]
https://github.com/2amigos/yii2-extension-skeleton

**Comment by schmunk42** [comment]
Why not use the existing skeleton generator?
Or a combination of both?

**Comment by samdark** [comment]
I'm not against it.

**Comment by klimov-paul** [comment]
This does not seems logical since Gii has an 'extension' generator already.

**Comment by schmunk42** [comment]
What could be interesting for the docs is a chained usage of the code-generator.
See also http://phundament.com/docs/44-extension-development.md and http://phundament.com/docs/41-code-generation.md

**Comment by samdark** [comment]
Could you help with adding it?

**Comment by schmunk42** [comment]
Will try to ... sorry, for my unresponsiveness, working on too much stuff at the moment.

**Comment by samdark** [comment]
Everything's fine. Your contributions are very valuable.
