### ISSUE TITLE
yii.activeForm - previous input value is passed to afterValidateAttribute handler

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#7578]
As it is said:

```
* The signature of the event handler should be:
*     function (event, attribute, messages)
* where
*  - event: an Event object.
*  - attribute: the attribute being validated. Please refer to attributeDefaults for the structure of this parameter.
*  - messages: an array to which you can add additional validation error messages for the specified attribute.
```

I expected that current value of input field is pased with `atrribute` object to make some postprocessing after validation.

But `atrribute` object passed to my function keeps _previos_ input value which makes absolutely no sense.

For example - previos input value was 1, you change it to -1.  In `attribute.value` you see 1

Simple check:

``` js
    $('#myForm').on('afterValidateAttribute', function (event, attribute, message) {
         console.log(attribute);
    });
```

The same happens both for `validateOnType` enabled and disabled.

![yii_error](https://cloud.githubusercontent.com/assets/2150916/6491223/de721c28-c2bc-11e4-9a63-07beee1ed956.png)

Messages passed are correct and refer to current input value.
Client validation itself works correct.

http://youtu.be/EaAaI2EsLNQ

**Comment by gigi** [comment]
I think ```afterValidateAttribute``` event should be triggered after attribute value is set ```attribute.value = getValue($form, attribute);```

Seems moving this string [Line 705](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L705) before ```return hasError;``` [Line 728](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L728) is enough.

@SDKiller, as temporary dirty solution you can use something like this
```
form.on('afterValidateAttribute', function(e, attribute, errors) {
    setTimeout(function() {
        console.log(attribute)
    }, 100);
});
```

**Comment by SilverFire** [comment]
Checked, currently it works as it was expected.
