### ISSUE TITLE
RangeValidator: allow callback as range

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#7581]
In some situations will be useful to pass a callback to `range` param of `RangeValidator`.
Rule configuration array can be set like this:
```php
['city_id', 'in', 'range' => function ($model) use ($cities) { return $cities[$model->country_id]; }]
```
Now to pass value of another attribute of model (via `$this`) we need to use InlineValidator:
```php
['city_id', function ($attribute, $params) use ($cities) {
    if (!in_array($this->$attribute, $cities[$this->country_id])) {
        $this->addError($attribute, Yii::t('app', '{attribute} is not a valid city for specified country.', [
            'attribute' => $this->getAttributeLabel($attribute),
        ]));
    }
}],
```

**Comment by lynicidn** [comment]
1. u can use exists validator
2. ['attr', 'in', 'range' => array_keys($this->attrLabels)]
```php
public function getAttrLabels()
{
    return \yii\helpers\ArrayHelper::map($this->relId->all(), 'id', 'label');
}
```

**Comment by RomeroMsk** [comment]
1. `exist` is for table columns. But when you have cached array of objects, it will not work.
2. It's not working. Just try to get value of attribute in method, which is called from rule and you will see.
```php
['attr', 'in', 'range' => $this->test()],
```
```php
public function test()
{
    Yii::info(var_dump($this->attr2, true));
    return [];
}
```

**Comment by lynicidn** [comment]
if u write:
```php
$form->field($model, 'attr')->dropDonwList($model->attrLabels)
```
need validate allow data:
```php
array_keys($this->attrLabels);
```
`attrLabels` here equals for render and validate

**Comment by RomeroMsk** [comment]
I showed you an example of code where retreiveng the model attribute value is not working inside method called from validation rule.

**Comment by lynicidn** [comment]
i use it many time for all and it work for me.
it don't work if u use `disabled` for dropdown items and it deny for validate only.

**Comment by RomeroMsk** [comment]
My case is not about forms, I'm working with validation in REST now.
And your example is not actually the same case (I don't know what is `relId` and if it is depend on another loaded attributes).

**Comment by creocoder** [comment]
:+1: Use case is absoluttely valid.

**Comment by mikehaertl** [comment]
+1 good idea

**Comment by RomeroMsk** [comment]
Please review the PR.
