### ISSUE TITLE
I need Help

### ISSUE THREAD

**Issue by Jsaiao** [yiisoft/yii2#7590]
Hello friends would aid downloaded a web app done in Yii but do not know how to install it on my server is also staying here (https://github.com/hunyoboy/instastrm) someone could help me with his installation?
Did not know the Yii framework to see this application. I thank everyone's attention!

**Comment by samdark** [comment]
Please use forums for questions. It's a bug tracker.

**Comment by Jsaiao** [comment]
Hello friend apologize for the inconvenience is that I'm new on Github. ;)

**Comment by samdark** [comment]
http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/

**Comment by lynicidn** [comment]
it's Yii 1.x

**Comment by Jsaiao** [comment]
Thanks for your help, do not know the version of the application but it is available at: https://github.com/hunyoboy/instastrm

**Comment by samdark** [comment]
Well, ask it's authors. We aren't them.
