### ISSUE TITLE
ActiveRecrod load hasMany from Post

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#7591]
is possible to load hasMany relation by POST

example:

```php
class Customer extends \yii\db\ActiveRecord
{
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['customer_id' => 'id']);
    }
}
```

```php
$customer = new Customer();
$customer->load(Yii:$app->request->post());

$customer->load('order',  Yii:$app->request->post());
```

or maybe is necessary to change `load`method for load automatic way

**Comment by samdark** [comment]
Yes, why not?

**Comment by leandrogehlen** [comment]
Currently does not exists this feature

**Comment by samdark** [comment]
Well, it will look a bit different. You have to load `Order` then save it, then use `Customer`'s link method. I don't think an ability to load relation in such way saves much trouble.

**Comment by mdmunir** [comment]
try this :D 
https://github.com/mdmsoft/yii2-ar-behaviors/#relationbehavior

**Comment by lynicidn** [comment]
it don't use in `create` case. U must not `link` new models
