### ISSUE TITLE
ActiveRecord relations operates only with static data, so can be converted to static

### ISSUE THREAD

**Issue by sensa-ua** [yiisoft/yii2#7592]
When investigate relation life cycle - it can be defined before the concreate instance of class created. So in fact this functionality can be moved to static functions.

little refactoring required in ActiveRecord to manage:

getRelation()
hasOne()
hasMany()
_behaviors 
as static members.

The customer - relation definitions will be changed to static as well:

public static function getCategory()
{
    return static::hasOne(Category::className(), ['id' => 'main_category_id']);
}

As result if we need to access relation data in static context we don't need to instantiate a dumb object to obtain relational data.

**Comment by cebe** [comment]
it can not, creating a relational query needs an AR instance: https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L378

**Comment by sensa-ua** [comment]
Can't it be  '$query->primaryModel = new $modelClass;' where $modelClass=get_calling_class(); or something?

**Comment by cebe** [comment]
if you run a relational query, you need not only an instance of the record but the one that has this relation including its attributes. e.g. to get relations for user 1, you need exactly this instance.

**Comment by sensa-ua** [comment]
in this particular situation, the all of the relational data is aggregated in the _relations member which collect the relational data. It use 'getXXX' method just to get the definition, and linking can be done on later stage. IE:

ConcreateAR
{
public static $_relations;
public $__relations;

public static function getXXX(){
return new ActiveQuery()->with_some_conditions();
}
}

when we instantiate class
1) we scan for all of the relations and populate static $_relations member -  this is something like cache - because happen only once per concreate AR subclass.
2) per user access to relation like $a->xxx
we obtain apropriate ActiveQuery instance, clone it, then initialize with primary record with $this, execute query and ->pupulateRelation(with_the_query_result); The real place where we need to bind query with primary model is here. On the phase 1) real instance is doesn't matter until all schema info is static.

**Comment by cebe** [comment]
I we do this, and we allow calling the relation method statically, the result of that method call is undefined. The case where you call `$post->getIAuthor()->where(...)->one()` needs a non static call to create the correct query. `Post::getAuthor()->where(...)->one()` is missing a context.
