### ISSUE TITLE
Validation - At least one attribute

### ISSUE THREAD

**Issue by thiagotalma** [yiisoft/yii2#7593]
What do you think of a core validation to ensure that, given an array of fields, at least one field is filled?

**Comment by Faryshta** [comment]
at the moment something like that happens. Lets assume you have a model with an attribute `name` if there is no validation for `name`, then the automatic/massive assignation methods like `Model::load` won't work on it.

**Comment by cebe** [comment]
Just to avoid confusion, you mean a situation like this:

attributes: phone_number, email, post_address
valitate that at least one of them is filled out so that there is at least one way to contact me.

Where would you put the error message for that?

**Comment by thiagotalma** [comment]
@cebe Exactly this situation.

The message can be displayed in all fields.

**Comment by sidtj** [comment]
@cebe, can I work on this next week?

**Comment by cebe** [comment]
sure, go ahead!

**Comment by mikehaertl** [comment]
+1 But please make it configurable, which attribute should get the error message. It's not always the case, that the error should be added for *all* attributes.

I've done a similar implementation for Yii 1 as inline validation method:

```
    // in rules():
    array('phone','compositerequired', // Pseudo attribute 'phone' receives error message
        'oneOf'=>array('phoneNo','mobileNo'),
        'message'=>'Please fill in either phone number or mobile phone number',
    ),

   /**
     * Validator: Requires a combination of attributes
     * 
     * One of the attributes specified in 'oneOf' param must not be empty
     */
    public function compositerequired($attr,$params)
    {
        $valid=false;
        foreach($params['oneOf'] as $required)
            if ($this->$required!==null && trim($this->$required)!=='')
                $valid=true;

        if (!$valid) {
            $this->addError($attr,$params['message']);
            foreach($params['oneOf'] as $required)
                $this->addError($required,'');
        }
    }
```

The above is taylored towards my use case. I think it should be more configurable:

 * Which attributes should receive the error message?
 * Which attributes should only be marked with an empty error message?

The latter is useful if some elements should only be marked with the CSS error class, but without showing the error message text.

**Comment by slinstj** [comment]
@cebe, there is a problem related to Yii 2 (since 1) design.

When we give a list of attributes to be validated like in `[['attr1', 'attr2', 'attr3'], 'require']`, they are validated individually, i. e., the validator (`require` here) will validate against `attr1`, put its erros, finish, and a new process will start for `attr2`, and so on. We dont have a way to send *all the attributes* in one time so that the validator could receive them and make something with all of them at the same time (maybe it could be implemented in Yii 2.x).

Because this, for this moment, the way I found to create this validator is something like:

~~~[php]
//in rules
[['attr1'], 'atLeastOne', 'validateWith' => ['attr2', 'attr3'], 'errorAttributes' => ['attr1', 'attr2']],
~~~
But I would like to hear you here, please.

**Comment by slinstj** [comment]
@mikehaertl, it seems good to have a way to specify the attributes to receive the error. I will include this if the core members dont disagree. Thanks!

**Comment by fernandezekiel** [comment]
the way you declare the declaration might be the tricky one here, but i'd like to see if what we can come up with
i was thinking if we can support a syntax wherein let's say a validation can declare as its dependencies:
```php
['attributes' => ['foo', 'bar', 'haz'], function () {....}]
```
in this way we can run the `function()` without executing it per declared attribute but the declaration will make them safe

**Comment by slinstj** [comment]
Hi @fernandezekiel 

What that technique would differ from the current besides the fact that the `function()` would not be reusable? 

The core validators have already a function to validate the attribs or you can use your own validator function (method) in your model or you can create your own validator class.

Could you give a real use case example?

**Comment by slinstj** [comment]
@cebe, would like to hear you here, please. If the code is ok, I can make the clientSide validation and the docs. If no, let me know, plz. :v:

**Comment by mikehaertl** [comment]
> We dont have a way to send all the attributes in one time so that the validator could receive them and make something with all of them at the same time (maybe it could be implemented in Yii 2.x).

@slinstj I don't think, this is easy to change. So you *always* will need another key where you list all the attributes. If you look at my example, you see that the normal attributes are not validated at all. They are only used to add the error message. This way you don't need another property to list the error attributes.

I also thought, whether we should make the min number of required attributes configurable. So how about this:

```
[['a','b'], 'multirequire', 'attributes' => ['x', 'y', 'z'], 'min' => 2]
```

 * At least 2 of the attributes listed in `attributes` must not be empty (without 'min' default would be 1)
 * Attributes 'a' and 'b' are *not* required
 * If there's an error, both, 'a' and 'b' receive the error message

This way you can also add the error message to the same attributes again:

```
[['a','b'], 'multirequire', 'attributes' => ['a', 'b']]
```

**Comment by slinstj** [comment]
@mikehaertl,
> They are only used to add the error message. This way you don't need another property to list the error attributes.

This has *nothing* to do with I've meant.

Your approach seems plus one interesting option although. But for me, validate `['x', 'y', 'z']` and put its errors in `['a', 'b']`seems strange and a make this out of the standard. Yii 2 validator put their erros in attributes being validate. This is why (IMO) the 'validateWith' give a more intuitive way to workaround this situation. One more *optional* param `errorAtributes` does not hurt and makes the things more clear too. But when some core developer arrive here, we can hear their arguments. My code is just a initial draft to actually be discussed. :v:

The `min` param is definitely very interesting! (And I would have to rename the core validator).

Lets wait some core developer to appear here cause I could make many changes and they would not be accepted at all.

**Comment by mikehaertl** [comment]
> This has nothing to do with I've meant.

@slinstj I know, that's why I brought it up ;). 

> This is why (IMO) the 'validateWith' give a more intuitive way to workaround this situation.

I kind of disagree here. It's not more intuitive to me, at least. No matter how we do it, we will always again have the same problem, which you already identified:

> We dont have a way to send all the attributes in one time so that the validator could receive them and make something with all of them at the same time (maybe it could be implemented in Yii 2.x).

So it will always be kind of unintuitive. The drawback with my solution is, that it will be called several times, if you list more than 1 attribute in the beginning of the array, which is not nice either.

Honestly, I can't really think of a really clean approach here.

**Comment by slinstj** [comment]
> Honestly, I can't really think of a really clean approach here.

Me too, not without some structural changes. This is why I was thinking in to be done perhaps for a 2.1 version.

Lets wait. :V:

**Comment by slinstj** [comment]
@cebe, news here?

**Comment by PrplHaz4** [comment]
Thanks for looking into this guys - ran across this problem immediately when starting with Yii2.  My solution was to put everything clientside, but clearly that is only part of a real solution.

**Comment by slinstj** [comment]
@mikehaertl, I have added your `min` suggestion.

Some params names have been simplified.

**Comment by jazielcarballo** [comment]
@slinstj how can I use this validator?, I don't understand in what folder must be. I have yii2 too I don't see validators folder.

**Comment by slinstj** [comment]
You can't. It isn't available yet. It's being discussed here and under
development.
Em 13/04/2015 18:04, "Jaziel Aarón Carballo Tadeo" <notifications@github.com>
escreveu:

**Comment by lukos** [comment]
This is perhaps difficult because you are levelling it wrongly. The current validator design is based on validators per-field and this is not that.

A potential solution is to create something called ValidationGroup which could be rendered onto a view and be given a name. A rule could then be created in the model for the group based on whatever you want (including custom rules and built-in rules) and if this fails, the error is written to the group element rather than to all the fields or some ad-hoc definition of which ones to add it to.

The group could be used either to achieve this kind of stuff or otherwise to allow sets of validation errors to be displayed in a single place, perhaps after 4 fields that all relate to the same thing (and it would also allow only one message to be displayed at a time for multiple fields).

**Comment by slinstj** [comment]
Briner, when I started this I had enough time (and disposition) to work
here. Now the things has changed. So, go ahead and make your changes and
make a PR. Maybe your collaboration will be used in some moment.



2015-05-17 18:24 GMT-03:00 Luke Briner <notifications@github.com>:

**Comment by Faryshta** [comment]
www.yiiframework.com/doc-2.0/yii-validators-existvalidator.html how about this for sending the multiple attributes?

`['telephone', 'atLeastOne', 'targetAttribute' => ['telephone', 'email']]`

will check if 'telephone' or 'email' ar set and put an error on 'telephone' if neither of them are.

**Comment by massimans** [comment]
i like the group validation idea even if the feature looks more like form validation rule with the error message displaying in the beginning of the form. form level validation nice enhancement to yii2.

**Comment by slinstj** [comment]
If anyone is interested I decided to make my own validator [slinstj/yii2-at-least-validator](https://github.com/slinstj/yii2-at-least-validator). 
Although, I can do a PR here (at least one more time) if some yii core developer feel necessary and give a feedback. Till there, it can be an option.

**Comment by slinstj** [comment]
Sorry, just updating the new final address, now in our github org: [code-on-yii/yii2-at-least-validator](https://github.com/code-on-yii/yii2-at-least-validator)

**Comment by SilverFire** [comment]
Ok, thank you. I'm closing this issue then
