### ISSUE TITLE
renderAjax won't bind client side validators for ActiveForm

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2#7600]
Rendering view by method renderAjax() returns HTML + JS registered in a view.
Unfortunatelly, validators for validating ActiveForm will not bind.

Here's scenario:
- I have HTML form via normal GET request. The form consists of 5 steps where each steps depends on previous step. For example if user chooses in step 1 certain payment method, then ajax loads in step2 fields relevant only for selected method.
- step 2 returns HTML + javascripts. They are attached into DOM structure of existing form. The only problem is, that Yii2 validators for new fields are not added to ActiveForm and will not apply.

Is there any way to achieve binding validators for newly loaded fields via ajax?

Here's example of returned response. Please note, that other JS code works fine (e.g. `$("#ade-step-2").find("[title]").tooltip();` will convert tooltips) except  `jQuery('#AdeWizard').yiiActiveForm` part.

```
<script src="/assets/ace7e76b/jquery.min.js"></script>
<script src="/assets/dada41eb/yii.js"></script>
<script src="/assets/dada41eb/yii.validation.js"></script>
<script src="/assets\dada41eb/yii.activeForm.js"></script>\n

<script type="text\/javascript">$(function () {

'use strict';

$("#calendar-wrapper-endDatetime .glyphicon-calendar").parent().off().on("click", function(){
    $("#adewizard-enddatetime").datetimepicker("show");
});

$("#ade-step-2").find("[title]").tooltip();   <=== this works fine

jQuery('#AdeWizard').yiiActiveForm([    <=== this block will not bind

    {"id":"adewizard-eventname",     <=== element "adewizard-eventname" will not validate :-(
     "name":"eventName",
     "container":".field-adewizard-eventname",
     "input":"#adewizard-eventname",
     "error":".help-block.help-block-error",
     "enableAjaxValidation":true,
     "validate":function (attribute, value, messages, deferred, $form) {
        yii.validation.required(value, messages, {"message":"Required field"});
        yii.validation.string(value, messages, {"message":"Event name must be a string.","max":25,"tooLong":"Event name should contain at most 25 characters.","skipOnEmpty":1})
    ;}},

    {"id":"adewizard-enddatetime",
     "name":"endDatetime",
     "container":".field-adewizard-enddatetime",
     "input":"#adewizard-enddatetime",
     "error":".help-block.help-block-error",
     "enableAjaxValidation":true,
     "validate":function (attribute, value, messages, deferred, $form) {
        yii.validation.required(value, messages, {"message":"Required field"});
    }},

    ], []);

</script>"
```

Also I have questions:
- how to ensure that JS script links will not get loaded via renderAjax(), because loading them causes unbinding and re-binding events and causes unexpected behaviours.

Thank you.

**Comment by lubosdz** [comment]
After analyse, i guess the reason for not applying validators of newly added fields is, that fields won't register into form when processing ajax response. Solution would be, that returned JS would register new fields if not registered yet:
~~~
jQuery('#AdeWizard').yiiActiveForm.add({
	'id' : 'newfieldId1',
	'id' : 'newfieldName1',
	//.. etc respecting the properties for current ActiveForm
});
~~~
Is this correct and can that be fixed?

**Comment by cebe** [comment]
that is correct, not sure if yii could do that automatically

**Comment by lubosdz** [comment]
There is already method for adding new field into yiiActiveForm dynamically.
Application also knows all current settings for formular so it is probably not an issue to render additional JS to inject field dynamically. The issue might be how to make API clear - when it should be generated and when not. May be some additional method like "**addFieldIfNotExists**" used only by renderAjax() would alleviate the issue.

BTW - I had really difficulties to find some examples on handling activeForm elements via JS since properties have been removed from PHP ActiveForm object and moved directly into JS. A few officially documented examples on dynamically **adding/removing error messages**, **adding/removing form attributes** would be very useful.

**Comment by lubosdz** [comment]
FYI - this issue (not binding dynamically validators on ajax) is pretty common.

See e.g.:
* http://www.yiiframework.com/forum/index.php/topic/62449-dynamic-form-generation-and-auto-save-ajax/page__gopid__276389#entry276389
* http://stackoverflow.com/questions/27805133/yii2-how-to-use-custom-validation-function-for-activeform
* http://stackoverflow.com/questions/25899576/dynamically-adding-input-fields-in-yii2

I tried to inject validation rules, or attach errors, but no luck so far.
Could you please advise on this?
Or is this a bug to be fixed, or expected behaviour so we have to find solution ourselves?
Thank you.
