### ISSUE TITLE
joinWith() not working as expected

### ISSUE THREAD

**Issue by joni-jones** [yiisoft/yii2#7601]
I have two models `User` and `Group`. User has two roles: `Manager` and `Employee`.
If user is `Manager` it can create group(one manager can create only one group), if it is `Employee` - it can be abble to be assigned to only one group.
This is user group relation in user AR:
```php
public function getGroup()
{
    switch ($this->role_id) {
        case Role::ROLE_MANAGER:
            return $this->hasOne(Group::className(), ['manager_id' => 'id']);
        default:
            return $this->hasOne(Group::className(), ['id' => 'group_id'])
                ->viaTable('groups_has_users', ['user_id' => 'id']);
    }
}
```

For example, I want to get all users (if user is manager - the group should be instance of group created by manager and if employee - group should be instance of assigned to employee group).
```php
User::find()
    ->joinWith('group')
    ->where(['in', User::tableName().'.id', [2, 3])
    ->asArray()
    ->all();
```
But for manager group property will be empty (for employees the group is correct). That's why because this query will be generated:
```sql
SELECT "users".* 
FROM "users" 
LEFT JOIN "groups_has_users" ON "users"."id" = "groups_has_users"."user_id" 
LEFT JOIN "groups" ON "groups_has_users"."group_id" = "groups"."id" 
WHERE "users"."id" IN (2, 3)
```
So I found what, when yii call `getGroup()` to create relations, the `$this->role_id` property is empty and default condition of switch is executed.

**Comment by cebe** [comment]
You can not define one relation to be through different keys. How would you translate that into one SQL query? You have to create two relations wich will then result in the correct join query for each type of user.

**Comment by joni-jones** [comment]
Sorry, I not understand, why do you mean by `different keys`?
`$manager = User::findOne(2)->group` and `$employee = User::findOne(3)->group` works correctly, because in this case `$this->role_id` is not empty and `switch()` works correctly.

**Comment by cebe** [comment]
for lazy loading on one record this will work but it is not possible to use it in joinWith() i.e. eager loading, because it is not possible to create an SQL query from it.

**Comment by joni-jones** [comment]
Thanks for explanation.
