### ISSUE TITLE
Dropdown with data-method attribute submits form only on every second change event

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#7604]
According to the documentation in `yii.js`, all form elements are attached with a handler and can make use of the following feature:

> This method recognizes the `data-method` attribute of the element. If the attribute exists, the method will submit the form containing this element.

I've tried this with a simple form like this:

```php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$opts = [1=>'one', 2=>'two', 3=>'three'];
?>
<div class="well">
    <?php $form = ActiveForm::begin([
        'action' => ['site/form'],
        'method' => 'get',
        'enableClientValidation' => false,
    ]) ?>
        <?= $form->field($model, 'status')->dropdownList($opts, ['data-method' => 'get']) ?>
        <?= Html::submitButton('test') ?>
    <?php ActiveForm::end(); ?>
</div>
```

I've left out the model code as it's not relevant - it's a standard form model with nothing special in it.

The form is only submitted on every second change event of the dropdown list. So the flow is like:

 1. I load the page, `one` is selected
 2. I select `two` - nothing happens (expected: form should get submitted)
 3. I select `three` - form is submitted as expected, page reloads
 4. I select `two` - nothing happens
 ...

I've observed this in Google Chrome 41.0.2272.76 (64-bit) and on Firefox 36.0.

UPDATE: I've also tested with `'data-method' => 'post'` with the same result.

**Comment by SilverFire** [comment]
Verified that works as expected now.
