### ISSUE TITLE
Unique validator fail with float number

### ISSUE THREAD

**Issue by AntoineGermain** [yiisoft/yii2#7611]
Hi,

I'm able to save a float number several times even if declared as unique.

```
[['mynumber'], 'number'],
[['mynumber'], 'unique']
```

```
$testfloatval = new Tabletest;
$testfloatval->mynumber = 0.3;
if($mynumber->save()){

}else{
  print_r($mynumber->getErrors());
}
```

Any errors on my code or real issue ?

Thank you !

**Comment by cebe** [comment]
how is the database column defined?

**Comment by AntoineGermain** [comment]
As a float

**Comment by cebe** [comment]
sounds like a simple float comparison issue. Need to introduce an epsilon to decide for equality of numbers. not sure if it is a good idea to define unique on a float.

**Comment by AntoineGermain** [comment]
Here is the real table : 

```
CREATE TABLE `match_odd` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `match_id` int(11) NOT NULL,
  `bookmaker_id` int(11) NOT NULL,
  `type` varchar(255) NOT NULL,
  `odd_1_name` varchar(255) NOT NULL,
  `odd_1_value` float NOT NULL,
  `odd_2_name` varchar(255) NOT NULL,
  `odd_2_value` float NOT NULL,
  `odd_3_name` varchar(255) NOT NULL,
  `odd_3_value` float NOT NULL,
  `odd_4_name` varchar(255) NOT NULL,
  `odd_4_value` float NOT NULL,
  `odd_5_name` varchar(255) NOT NULL,
  `odd_5_value` float NOT NULL,
  `best_odd_1` tinyint(1) NOT NULL,
  `best_odd_n` tinyint(1) NOT NULL,
  `best_odd_2` tinyint(1) NOT NULL,
  `created_at` int(11) NOT NULL,
  `updated_at` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `match_id` (`match_id`),
  KEY `bookmaker_id` (`bookmaker_id`),
  CONSTRAINT `match_odd_ibfk_1` FOREIGN KEY (`match_id`) REFERENCES `match` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `match_odd_ibfk_2` FOREIGN KEY (`bookmaker_id`) REFERENCES `bookmaker` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

The use case is simple, i store all odds for a bet every minute. For every football match in the world, it's a lot of odds. So i try to avoid duplicate entry.

I can do this with simple php comparaison, but could be prettier and global with unique validator.

Could you explain why : "not sure if it is a good idea to define unique on a float at all though." ?

**Comment by cebe** [comment]
> Could you explain why : "not sure if it is a good idea to define unique on a float at all though." ?

http://www.floating-point-gui.de/errors/comparison/

**Comment by AntoineGermain** [comment]
Got it, thank you ! :)

**Comment by qiangxue** [comment]
It's theoretically a bad idea (due to representation precision problem) to compare the quality of two floating numbers. If you really want to do so, use a decimal column so that the comparison in terms of strings instead of floating numbers.  Closing this as it has nothing to do with unique validator.

**Comment by AntoineGermain** [comment]
Nice tip, thank you everyone !
