### ISSUE TITLE
Css and Js copy to assets folder equal in yii 1

### ISSUE THREAD

**Issue by wilsonfalai** [yiisoft/yii2#7612]
In Yii 1 i use:
$cs->->registerCssFile('/css/foto.css');

when I register a css or js file, the file was copied to a folder in assets. Whenever I edited the file, it was copied to a new folder in assets
Ex:
/assets/8e71dd73/foto.css

Yii2 uses AssetBundle. How can I make the js and css files behave as in yii 1. I need them to be copied to assets folder. Thus, I have never problems with cache

**Comment by wilsonfalai** [comment]
in yii1:
$cs->registerCssFile(Yii::app()->assetManager->publish(/css/name.css", false, -1, YII_DEBUG));

the file is copied to : /assets/8e71dd73/name.css

**Comment by cebe** [comment]
this should be what you need: https://github.com/yiisoft/yii2/blob/a8bffdf03616dfdf244e434e16842f6a22bfcf8a/docs/guide/structure-assets.md#cache-busting-

**Comment by wilsonfalai** [comment]
Great! Thaks!
