### ISSUE TITLE
Problems in backend in advanced template

### ISSUE THREAD

**Issue by lzv** [yiisoft/yii2#7624]
Hello.
I use Ubuntu 14.04, Apache 2.4.7 and Yii 2.0.3.
I installed advanced template and make settings in Apache: frontedn to "yii_adv.tt", backend to "admin_yii_adv.tt". Not subdomain, two different domains. In frontend is all ok. In backedn not showing debug panel, and "logout" link send data in GET (not POST).
I removed all code. I installed Yii only. Then I make frontedn part manually. Everything works well. I copy frontedn to backend, replacing text "frontend" to "backend" where necessary.
But the situation has not changed.
Both parts must be same. I have no idea why backend not working.

**Comment by sidtj** [comment]
Hi,

What happens if you access `localhost/path-to-your-app/frontend/web' and `localhost/path-to-your-app/backend/web'?

**Comment by lzv** [comment]
I not use "localhost" name.
In your case, it will be the same domain. But advanced template should work on different domains, is not it?

**Comment by lzv** [comment]
I make an experiment. I renamed "frontend" folder to "backend", and "backend" to "frontend", and changed namespaces in source code.
"yii_adv.tt" now is backend, but debug panel is working. "admin_yii_adv.tt" is frontend, but still not working. 
How can this be?

**Comment by lzv** [comment]
I changed "admin_yii_adv.tt" to "adyii_adv.tt", but no difference.

Apache settings: 

<VirtualHost *:80>
      ServerName yii_adv.tt
      ServerAlias yii_adv.tt
      AssignUserID username username
      DocumentRoot /home/username/www/yii_adv.tt/frontend/web
</VirtualHost>

<VirtualHost *:80>
      ServerName adyii_adv.tt
      ServerAlias adyii_adv.tt
      AssignUserID username username
      DocumentRoot /home/username/www/yii_adv.tt/backend/web
</VirtualHost>

**Comment by lzv** [comment]
I changed "frontend" to "userzone", and "backend" to "adminzone" - folders, namespaces, settings. I cleared the cache in the browser, assets folder, runtime folder. 
But the situation has not changed! "yii_adv.tt" is working, "adyii_adv.tt" is not.
I totally no idea.

**Comment by sidtj** [comment]
Is it so hard for you to test without virtual hosts, just localhost or 127.0.0.1?

I don't have idea what is your problem but, somehow, it seems related to yours VH. This is the reason for test.

**Comment by lzv** [comment]
I changed ""adyii_adv.tt" to "admin.yii_adv.tt" and everything was working well. In localhost will be same. However, "admin.yii_adv.tt" and "yii_adv.tt" is same domain. But advanced template should work on different domains. 
One installation Yii can not work in different domains. This is an obvious bug.

**Comment by samdark** [comment]
It's not. I have advanced app set up using two different hosts http://yii2-af.local/ and http://yii2-ab.local/. Works well. So I think it's something about how apache was set up.
