### ISSUE TITLE
Some parts of DbManager aren't cached

### ISSUE THREAD

**Issue by Rakovskiy** [yiisoft/yii2#7626]
DbManager cache isn't used for the following methods:

* getItems ()
* getRolesByUser ()
* getPermissionsByRole ()
* getPermissionsByUser ()
* getAssignment ()
* getAssignments ()
* hasChild ()
* getChildren ()

Would be great to have these cached as well.

**Comment by samdark** [comment]
@qiangxue is there a reason for it?

**Comment by cebe** [comment]
> getAssignment ()
> getAssignments ()

caching assignments could be problematic as these grow with the size of user table. These could be cached in a local variable for the current request though.

> getItems ()
> getRolesByUser ()
> getPermissionsByRole ()
> getPermissionsByUser ()
> hasChild ()
> getChildren () 

It is not common to call this in every request so caching does not really make sense. These are used for maintaining the RBAC structure.

**Comment by Rakovskiy** [comment]
Sorry, I can not write in English!

Если ввели кеширование, то думаю оно должно быть полным, а не частичным. При update или remove очищать кеш, почему это сделано в getItem(),  checkAccess а в остальных методах нет?

**Comment by samdark** [comment]
@Rakovskiy перевожу что написал @cebe:

> getAssignment ()
> getAssignments ()

с этими методами проблема так как assignment-ов становится всё больше с ростом количества пользователей. Все они в кеш рано или поздно не поместятся. Их можно кэшировать локально в переменной.

> getItems ()
> getRolesByUser ()
> getPermissionsByRole ()
> getPermissionsByUser ()
> hasChild ()
> getChildren () 

Эти методы практически не вызываются каждый запрос, поэтому кэшировать нет смысла.

**Comment by qiangxue** [comment]
@cebe has explained why cache is not used in the listed methods, and that's exactly the reason behind. Thanks.
