### ISSUE TITLE
gridview pjax search stopped working

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2#7629]
I just updated my libraries via composer and `bower-asset/yii2-pjax` updated from v2.0.2 to v2.0.3

gridview was wrapped within pjax widget and its filters were working fine, now they stopped working and following error appears in firbug console:
```js
ReferenceError: stripPjaxParam is not defined       jquery.pjax.js (line 366, col 2)
```

**Comment by zelenin** [comment]
https://github.com/yiisoft/jquery-pjax/commit/3f61e52d11451444a83465dd8a2472aa9ad17fa9#diff-256b2e7d3ffe31142c00fa086e15d3a6L562
https://github.com/yiisoft/jquery-pjax/commit/3f61e52d11451444a83465dd8a2472aa9ad17fa9#diff-256b2e7d3ffe31142c00fa086e15d3a6R366

**Comment by hesna** [comment]
@zelenin :+1:

**Comment by samirmember** [comment]
I have exactly the same issue.
I can see in the @zelenin links that there was an updates on pjax. But how can I resolve this?

**Comment by angelcoding** [comment]
@samirmember 
Not sure how correct this is but should work as a temp workaround until fix is released ...
change vendor\bower\yii2-pjax\jquery.pjax.js line 366 
from 
`options.url = stripPjaxParam(options.url);` 
to 
`options.url = stripInternalParams(options.url);`

**Comment by mbezhanov** [comment]
As a temporary workaround, I personally downgraded to version 2.0.2 of the yii2-pjax package, so you can try this as well @samirmember

**Comment by samdark** [comment]
Fixed.

**Comment by xiandalisay** [comment]
I have exactly the same issue.

**Comment by samirmember** [comment]
@xiandalisay  This bug is fixed and you should run `composer update`
