### ISSUE TITLE
Minor updates on yii\web\Request

### ISSUE THREAD

**Issue by miraage** [yiisoft/yii2#7637]
I love the way how you validate CSRF token. It is very similar to Rails 4.2.
But here is some things, imho, that might be improved:

1) `getCsrfTokenFromHeader` should read `static::CSRF_HEADER`, not `self::CSRF_HEADER`. It will be very flexible.

2) I think that would be great to have public method to validate CSRF token.

Something like

```php
public function isValidToken($token)
{
    $trueToken = $this->loadCsrfToken();

    return $this->validateCsrfTokenInternal($token, $trueToken);
}
```

**Comment by qiangxue** [comment]
Modified the constant usage. I didn't add `isValidToken()`. Please describe your use case for this method, and I will consider it. Thanks.

**Comment by miraage** [comment]
Situation is very similar between yii1 vs yii2 and rails 4.1 vs rails 4.2.
Both frameworks updated CSRF validation from const CSRF value to XORed.

As AngularJS user, I have found the way to validate CSRF token without modification of any client code. 
- set `XSRF-TOKEN` cookie in `beforeAction`
- override/extend validation method

Even the cookie value is XORed and constant, it validates perfectly. But in yii2 we need tons of modifications because lack of public verification method.

```ruby
# Rails 4.1 ApplicationController
def verified_request?
  super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
end

# Rails 4.2 ApplicationController
def verified_request?
  super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
end
```

**Comment by miraage** [comment]
Yes, I can use custom `CSRF_HEADER`, but some projects are still on jQuery and new parts are developed via AngularJS.

**Comment by miraage** [comment]
Thanks you so much.

https://github.com/yiisoft/yii2/blob/739f6358cd75885f8d9a12bd105ff3583a6b9959/framework/web/Request.php#L1370

I think `$trueToken` should be used there instead of yet another method call.
