### ISSUE TITLE
"Array to string conversion" in BaseOAuth

### ISSUE THREAD

**Issue by DirtyB** [yiisoft/yii2#7639]
When getting an error from external API (VKontakte) 'error' field of response is not a string but array. That causes the line in BaseOAuth::processResponse
https://github.com/yiisoft/yii2/blob/master/extensions/authclient/BaseOAuth.php#L275
to throw  'yii\base\ErrorException' with message 'Array to string conversion'

**Comment by klimov-paul** [comment]
Issue resolved by commit https://github.com/yiisoft/yii2-authclient/commit/cec2d454c528ba9861e77cfe874e6cd1bf9ad40e
