### ISSUE TITLE
Ability to work with postgres arrays.

### ISSUE THREAD

**Issue by joni-jones** [yiisoft/yii2#7640]
Postgres can store arrays in columns. I think it would be cool if yii will be support postgres array operators, like `@>` in `where()` method.

**Comment by cebe** [comment]
can you give a link to the documentation that describes these?

**Comment by joni-jones** [comment]
http://www.postgresql.org/docs/9.3/static/functions-array.html. Now I have few implementations of `@>` operator for `integer` and `text` arrays, but I need time to write tests.

**Comment by cebe** [comment]
you can already use them: `where('<@', 'col1', 'col2')`

**Comment by joni-jones** [comment]
Sorry, but `where()` receive only one parameter, i can create this query similar to this:
```php
->where('id @> ARRAY[2,3,4]')
```
But, in this case need to manually escape column and values and also implode array elements.

**Comment by cebe** [comment]
oh, sorry. should be `where(['<@', 'col1', 'col2'])`

**Comment by nineinchnick** [comment]
Possibly related to #7481

**Comment by joni-jones** [comment]
@cebe, your example not working, if executte this code:
```php
where(['<@', 'id', 'ARRAY[2,3]'])
```
we will get database error: `	exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR: array value must start with "{" or dimension information' in /var/www/yii2/framework/db/Command.php:822`

Because expression `ARRAY[2,3]` will be quoted to `"ARRAY[2,3]"` and result query looks like this:
```sql
SELECT COUNT(*) FROM "events" WHERE "id" <@ 'ARRAY[2,3]'
```

**Comment by cebe** [comment]
you have to use a `yii\db\Expression` object to wrap the argument

**Comment by joni-jones** [comment]
Yes, but values escaping not working as expected:
```php
$expression = new \yii\db\Expression('ARRAY[:id]', [':id' => [2, 3]]);
...->where(['<@', 'id', $expression]);
```
Generate query similar to:
```sql
SELECT COUNT(*) FROM "events" WHERE "id" <@ ARRAY[2]
```

**Comment by cebe** [comment]
`->where(['<@', 'id', new \yii\db\Expression('ARRAY[2,3]')])`

**Comment by joni-jones** [comment]
But in this case, also needed manual escaping for values.

**Comment by joni-jones** [comment]
This PR allow to use filter similar to `in` operator. Few examples:
```php
where(['in integer array', 'id', [2, 3]])
```
Will generate `where "id" @> ARRAY[2, 3]::integer[]`
```php
where(['in text array', 'name', ['alex', 'john']])
```
Will generate - `where "name" @> ARRAY['alext','john']::text[]`

**Comment by EagleMoor** [comment]
How use with for insert or custom function like a 

```sql
CREATE OR REPLACE FUNCTION my_function(my_vars character varying[])
```

**Comment by joni-jones** [comment]
@EagleMoor, this PR allow to create filters for pg arrays. If you want use php arrays as params in postgres procedure - you need to convert them manually.

**Comment by Tigrov** [comment]
I made an extention to store `array` and `json` types
https://github.com/Tigrov/yii2-pgsql

**Comment by EagleMoor** [comment]
Nice, but no test...

**Comment by v0lume** [comment]
Hi guys! Do you have any new suggestions for this issue?

**Comment by samdark** [comment]
@v0lume try @Tigrov extension.

**Comment by SilverFire** [comment]
Closing in favor of https://github.com/yiisoft/yii2/pull/14819

**Comment by GlyphDataServices** [comment]
I do this:
$query->andFilterWhere(['@>', 'array_field', '{'.$this->arrayFieldSearch.'}']);
where arrayFieldSearch is a model property disambiguated from the array field, because I'm using kossmoss\PostgresqlArrayField behavior to automatically populate postgres array fields into model properties.

**Comment by mirkhamidov** [comment]
how use `?|` operator? (https://www.postgresql.org/docs/9.4/static/functions-json.html)
I got error
<img width="1134" alt="2018-03-09_19-45-24" src="https://user-images.githubusercontent.com/2736223/37218743-6fba2f9e-23d2-11e8-8c4a-73b25a40180c.png">

tried:
```
$q->andWhere(['?|', $colName, new Expression("array['$_arr']")]);
```
and 
```
$q->andWhere("$colName ?| array['$_arr']");
```

**Comment by SilverFire** [comment]
```sql
$q->andWhere(['?|', $colName, new ArrayExpression($_arr)]);
```

**Comment by mirkhamidov** [comment]
Error not in Expression (by the way, `JsonExpression` did not help), in operator `?|` which converts to `$1`

<img width="1134" alt="2018-03-09_19-45-24" src="https://user-images.githubusercontent.com/2736223/37223947-24969f96-23e3-11e8-851e-c883eafaee18.png">

**Comment by SilverFire** [comment]
@mirkhamidov create a separate issue, please.

**Comment by mirkhamidov** [comment]
@SilverFire done #15873
