### ISSUE TITLE
AssetController - css compression - issues relative image paths and symlinks 

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#7641]
The current implementation of the AssetController-css-compression doesnt seem to handle symlinked assetfolders correctly.

My scenario:
1) a css file with:

@font-face {
    font-family: 'TitilliumText22LThin';
    src: url('../fonts/TitilliumText22L001.otf');
    font-weight: normal;
    font-style: normal;
}

2)  /domain.php/releases/public_html/assets - in which assets is a symlink to 3)
3)  /domain.php/shared/assets

The problem
The resulting css contains the folder /shared/ in alle relative CSS urls like:
* url('../../../../../shared/assets/7651ebcc/fonts/TitilliumText22L001.otf')

which should be
* url('assets/7651ebcc/fonts')

Of course this should never be exposed as it is not part of the URL structure.

The issue lies within https://github.com/yiisoft/yii2/blob/5bda2fe0733c0eaa97c5f47d4f581b004c4c4115/framework/console/controllers/AssetController.php#L587 . The folder structure for relative CSS does not take the symlink into account and determines the relative URL purely on difference between $inputFilePathParts[$i] == $outputFilePathParts[$i].

**Comment by Sammaye** [comment]
Can you show your assets.php file? Make sure you are using realpath() on aliases etc

**Comment by dynasource** [comment]
assets-local:

```php

<?php
/**
 * Configuration file for the "yii asset" console command.
 */

// In the console environment, some path aliases may not exist. Please define these:
Yii::setAlias('@webroot', __DIR__ . '/../../../frontend/web');
Yii::setAlias('@web', '/');

return [
    // Adjust command/callback for JavaScript files compressing:
    'jsCompressor' => 'java -jar /var/bin/compiler.jar --js {from} --js_output_file {to}',
    //'jsCompressor' => 'java -jar /home/customers/domains/bin/compiler.jar --js {from} --js_output_file {to}',
    // Adjust command/callback for CSS files compressing:
    //'cssCompressor' => 'java -jar /home/customers/domains/bin/yuicompressor-2.4.7.jar --type css {from} -o {to}',
    'cssCompressor' => 'java -jar /var/bin/yuicompressor-2.4.7.jar --type css {from} -o {to}',
    // The list of asset bundles to compress:
    'bundles' => [
         //'app\assets\AppAsset',
        
        'yii\web\YiiAsset',
        'yii\web\JqueryAsset',
        'frontend\views\layouts\main\assets\Asset',
        'frontend\views\site\assets\FrontpageAsset',
        'frontend\views\layouts\visitor\assets\VisitorAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'yii\widgets\PjaxAsset',
        
    ],
    // Asset bundle for compression output:
    'targets' => [
        'all' => [
            'class' => 'yii\web\AssetBundle',
            'basePath' => '@webroot/assets',
            'baseUrl' => '@web/assets',
            'js' => 'all.js',
            'css' => 'all.css',
        ],
    ],
    // Asset manager configuration:
    'assetManager' => [
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
    ],
];
```

**Comment by Sammaye** [comment]
try with:

   Yii::setAlias('@webroot', realpath(__DIR__ . '/../../../frontend/web'));

**Comment by dynasource** [comment]
I tried your solution (thanks), unfortunately it still generates the 'shared' folder in the path.

 It looks like AssetController is incomplete on this matter. It could also use improvements on code readibility by the way.

**Comment by klimov-paul** [comment]
I am afraid this issue is unlikely to be solved at `AssetController`.
The reason it appear is that bundle 'basePath' is resolved using `reapath()` function, while publishing at `AssetManager`:
https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L406
`AssetController` is unable to find out if such resolve took place or not.

@dynasource, in order to solve your problem you should abandon manual symlinking of your 'assets' folder. You should use abilit of the `AssetManager` publishing instead, setting `AssetManager::linkAssets` to 'true'.
https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L113

In case your 'shared' folder may vary you should consider creating path alias for it somewhere at application config:
```php
Yii::setAlias('@shared', '/domain.php/shared/assets')
```
And then use this alias at `AssetBundle::sourcePath`.

**Comment by dynasource** [comment]
thanks for your detailed anwser. I am overriding it now till I have the time to look at your solution. Will report.
