### ISSUE TITLE
Sending $params to $user->can() in AccessRule

### ISSUE THREAD

**Issue by alagodich** [yiisoft/yii2#7643]
Hi

Should not we have a way to send params to access rules when configuring them as a controller's behaviour?

For example in your [guide] (http://www.yiiframework.com/doc-2.0/guide-security-authorization.html) you are creating `updateOwnPost` rule which is expecting `postId` param. But we don't have a way to send this param when configuring rules this way:
```PHP
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['update'],
                        'allow' => true,
                        'roles' => ['admin', 'updatePost', 'updateOwnPost'],
                    ],
```
In `AccessRule` class we just [call] (https://github.com/yiisoft/yii2/blob/master/framework/filters/AccessRule.php#L152) `can()` method without any params.
So `updatePost` will not resolve with `updateOwnPost` as we cannot send `postId`.

Is it a bad practice and i have to use the following right in the action?
```PHP
if (\Yii::$app->user->can('updatePost', ['post' => $post])) {
    // update post
}
```
I would prefer to keep all access assigning in one place.

**Comment by cebe** [comment]
I am currently doing it like that:

```php
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
				[
					'actions' => ['create', 'quick-create'],
					'allow' => true,
					'matchCallback' => function($rule, $action) {
						return Yii::$app->user->can('task:create', ['project' => $action->controller->findProject()]);
					},
				],
...
```

**Comment by alagodich** [comment]
Right, i can use that, thank you.
