### ISSUE TITLE
How to use 'as access' filter to set access rules for Yii2 modules?

### ISSUE THREAD

**Issue by uran1980** [yiisoft/yii2#7644]
**How to use 'as access' filter to set access rules for Yii2 modules?**

For example:

I have ```Profile``` module and I want to restrict access to that module from unautorized users. On [stackoverflow](http://stackoverflow.com/questions/26739623/grant-access-to-module-in-yii2) I found some answer that I can use ```'as access'``` filter:

```
'modules' => [
    'roles' => [
        'class' => frontend\modules\profile\Module::className(),
        'as access' => [
            'class' => 'yii\filters\AccessControl',
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                ],
            ],
        ],
]
```

Ok, but I cant find anithing about ```'as access'``` usage in oficial yii2 guide( 

**Where can I finde more info about that?**

**And how to set this rules not in config file but in Module class itself? Is it possible?**

I can't finde doc about this also.

Thanks.

**Comment by qiangxue** [comment]
It's here (in the last paragraph): http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html#attaching-behaviors
