### ISSUE TITLE
Yii2 js router?

### ISSUE THREAD

**Issue by tsvetann** [yiisoft/yii2#7649]
Are there any plans or is there already something like JS router in Yii2 (meaning generating url routes with javascript)?

**Comment by samdark** [comment]
No, there's nothing like that currently.

**Comment by samdark** [comment]
What's use case for it?

**Comment by lichunqiang** [comment]
You can generate the url in php, and get it in javascript.

**Comment by tsvetann** [comment]
For instance if I have to generate url in js script what is the best way to do it without knowing if pretty urls are on or not?

**Comment by kartik-v** [comment]
Current options:

- If you are generating the JS via PHP then you can use yii's PHP methods (e.g. Url helper) to generate the Url and use it in your client script. e.g.
```php
$view->registerJs('$("#input-id").plugin({url:' . Url::to(['/site/test']) . '});');
```

- If you want to use URL at runtime in javascript... one way is to store the URL in HTML5 data attributes via PHP again:
```php
<input id="input-id" data-url='<?= Url::to(['/site/test']) ?>'>
```
then in your javascript
```js
function doSomething() {
    var vUrl = $("#input-id").data('url'), vData;
    $.ajax({
        url: vUrl,
        type: 'post',
        data: vData
    });
```

**Comment by samdark** [comment]
Well, thoretically Rules could be converted to JS but I'm not sure how to deal with custom ones, rest ones etc.

**Comment by tsvetann** [comment]
Initially, I went with @kartik-v first option but was wondering if there is a slimmer solution. It is much nicer when you have a single Asset class for your client script. In either the first or the second options I have to register js separately from the Asset file and it is not that nice. Anyway thanks @kartik-v @samdark

**Comment by axelson** [comment]
+1

I'd love to see something like Rails js-routes: https://github.com/railsware/js-routes

Trying to pass all sorts of urls and routes to javascript doesn't work well with an angular single page application.

**Comment by Mirocow** [comment]
+1 
Like this 
Yii.app.createUrl('admin/device/deleteDeviceCategory')
Yii.app.createUrl({path: 'admin/device/deleteDeviceCategory', id: 100})

**Comment by timmy78** [comment]
+1

**Comment by juanmacias** [comment]
In case you want to navigate based on a select value, you need to generate de Url in JavaScript.

I have this approach in JS:
<script>
url='<?=Url:to(["controller/action","param1"=>"param1_value"])?>;
url_res=url.replace('"param1_value", encodeURIComponent($('#select_control_id').val()));
 window.location.href = url_res;
</script>

Url is generated on server, and values on client javascript.
