### ISSUE TITLE
Yii 2 not follow PSR-2 while coding style document says otherwise

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#7650]
From core code style document https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md

> Overall we're using PSR-2 compatible style so everything that applies to PSR-2 is applied to our code style as well.

This is not entirely accurate. Yii 2 is not PSR-2 compliance. From PSR-2 document https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#42-properties

> Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

Please correct wiki and remove PSR-2 to not confuse contributors and newcomers.

**Comment by cebe** [comment]
> Property names SHOULD NOT be prefixed

means the following:

> www.ietf.org/rfc/rfc2119.txt
> 4. SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.

We have made this decision carefully so we comply with PSR-2.

**Comment by creocoder** [comment]
@cebe Please reread that phrase

> Overall we're using PSR-2 compatible style so everything that applies to PSR-2 is applied to our code style as well.

Keyword is **everything**. And after that phrase there is list where we can find

> Property names MUST start with an initial underscore if they are private.

Don't you think that its slightly controversial with everything? )

**Comment by cebe** [comment]
well, it would be quite inconsistent if we would decide on the underscore for every single private property by case so it makes sense to write that. Feel free to propose a rephrase that makes it more clear that there are special decisions made on the things where PSR-2 allows choice. Imo that is not really important.
