### ISSUE TITLE
I18N ADD: Pluggable user language detector

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7651]
It should try:
* Preference from user session/model, if logged in and configured by project user-programmer
* Accept-Language header
* GeoIP
* Cookie, if site has no public logins
* Any other method the user-programmer may come up with

I don't ask for immediate implementation of everything, just describe interface I can code to.

**Comment by cebe** [comment]
I think this should be an extension, I have already seen some of them. It is a very application specific thing that needs to be done differently in many cases. I do not think this belongs to the core.
