### ISSUE TITLE
Wrong date validation in CoreValidators

### ISSUE THREAD

**Issue by amlopezalonso** [yiisoft/yii2#7652]
Dear developers,

Date validation in CoreValidators as in:

```
public function rules()
    {
        return [
             ....
             [['myDate'], 'date', 'format' => 'yyyy-mm-dd'],
             ....
    ];
}
```

does not check out wrong day numbers (i.e. February 30th, April 31th,...) so those dates are stored in DB as 0000-00-00.

Regards,
Antonio

**Comment by cebe** [comment]
do you have intl extension enabled?

**Comment by amlopezalonso** [comment]
Yes as per:

Internationalization support	enabled
version 	1.1.0 
ICU version 	52.1 
ICU Data version 	52.1

**Comment by amlopezalonso** [comment]
I would propose an option to validate dates with zero month and/or day, as MySQL may use them to store plain years (i.e. 1978-00-00).

**Comment by cebe** [comment]
if you want to validate `yyyy-mm-dd` without the support for i18n date formats, you can use PHP validator for it: `php:Y-m-d` and configure `timestampAttribute` and `timestampAttributeFormat` to override current value with the corrected one.
