### ISSUE TITLE
Integer overflow in ActiveRecord with Oracle

### ISSUE THREAD

**Issue by ercling** [yiisoft/yii2#7659]
I have Oracle database with number(38) field and an ActiveRecord model. My property is string:

``` php
$prop = '412200100268153';
```

When I'm trying to save this property I have 2147483647 value in my db.

The problem is in **db/oci/Schema.php** in:

``` php
protected function extractColumnType($column, $dbType)
    {
        $column->dbType = $dbType;

        if (strpos($dbType, 'FLOAT') !== false) {
            $column->type = 'double';
        } elseif (strpos($dbType, 'NUMBER') !== false || strpos($dbType, 'INTEGER') !== false) {
            if (strpos($dbType, '(') && preg_match('/\((.*)\)/', $dbType, $matches)) {
                $values = explode(',', $matches[1]);
                if (isset($values[1]) && (((int) $values[1]) > 0)) {
                    $column->type = 'double';
                } else {
                    $column->type = 'integer';
                }
            } else {
                $column->type = 'double';
            }
        } elseif (strpos($dbType, 'BLOB') !== false) {
            $column->type = 'binary';
        } elseif (strpos($dbType, 'CLOB') !== false) {
            $column->type = 'text';
        } else {
            $column->type = 'string';
        }
    }
```

I wrote this solution for myself:

``` php
protected function extractColumnType($column, $dbType)
    {
        $column->dbType = $dbType;

        if (strpos($dbType, 'FLOAT') !== false) {
            if (strpos($dbType, '(') && preg_match('/\((.*)\)/', $dbType, $matches)) {
                $values = explode(',', $matches[1]);

                if(isset($values[0]) && (int)$values[0] < 10) {
                    $column->type = 'double';
                }else{
                    $column->type = 'string';
                }

            } else {
                $column->type = 'double';
            }
        } elseif (strpos($dbType, 'NUMBER') !== false || strpos($dbType, 'INTEGER') !== false) {
            if (strpos($dbType, '(') && preg_match('/\((.*)\)/', $dbType, $matches)) {
                $values = explode(',', $matches[1]);

                if(isset($values[0]) && (int)$values[0] < 10) {
                    if (isset($values[1]) && (((int) $values[1]) > 0)) {
                        $column->type = 'double';
                    } else {
                        $column->type = 'integer';
                    }
                }else{
                    $column->type = 'string';
                }

            } else {
                $column->type = 'double';
            }
        } elseif (strpos($dbType, 'BLOB') !== false) {
            $column->type = 'binary';
        } elseif (strpos($dbType, 'CLOB') !== false) {
            $column->type = 'text';
        } else {
            $column->type = 'string';
        }
    }
```

But maybe someone can implement this checks in a better way?

Thank you!

**Comment by qiangxue** [comment]
What about using `double` when the db type is either `FLOAT` or `NUMBER`, regardless their precision?

**Comment by nineinchnick** [comment]
I've been fixing that yesterday in #7868. If I remember correctly from the manual, only the `BINARY_FLOAT` and `BINARY_DOUBLE` are true floating point types and should be matched to `double` in PHP. Any other `NUMBER` is either an integer (with scale <= 0) or a decimal, that should be stored as `string` in PHP.

**Comment by samdark** [comment]
Correct.

**Comment by nineinchnick** [comment]
@ercling are you using 32 bit PHP? Could you check if the same problem persists when using 64 bit PHP?

**Comment by smsteel** [comment]
Confirm on this problem. Current realisation of `\yii\db\oci\Schema::extractColumnType` just doesn't use $precision parameter. For example, type `NUMBER(17,0)` in Oracle will overflow `integer` in PHP.

**Comment by smsteel** [comment]
I think, `PHP_INT_SIZE` can be used here, since `integer` in PHP can keep Oracle's `NUMBER(18,0)` and `NUMERIC(18, 0)` on 64 bit and `NUMBER(9, 0)`, `NUMERIC(9, 0)`. Anything larger must be in different type. And `NUMBER`, `NUMERIC`, `DEC`, `DECIMAL` can contain floats. And $scale is actually a number of digits after a decimal, but being using incorrect in `\yii\db\oci\Schema::extractColumnType` if i understand right:

            if ($scale !== null && $scale > 0) {
                $column->type = 'decimal';
            } else {
                $column->type = 'integer';
            }

Currently at work and made a quick-fix for myself, maybe can create a pull-request later.

**Comment by samdark** [comment]
That will be quite inconsistent and may result in serious issues. For example, API clients may rely on the fact that value is a string and when switched to 64bit system it will start returning integer and crash the app.

**Comment by smsteel** [comment]
So, it's must be just correct type check assuming i have 32-bit system?

**Comment by samdark** [comment]
I think so.
