### ISSUE TITLE
composer can't install when use --stability=dev

### ISSUE THREAD

**Issue by ilovintit** [yiisoft/yii2#7666]
[Composer\DependencyResolver\SolverProblemsException]                                                    
    Problem 1                                                                                              
      - yiisoft/yii2 dev-master requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.  
      - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.   
      - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.x-dev, dev-master].     
  Potential causes:                                                                                        
   - A typo in the package name                                                                            
   - The package is not available in a stable-enough version according to your minimum-stability setting   
     see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.         
  Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by samdark** [comment]
Do you have composer asset plugin of latest version installed?

**Comment by ilovintit** [comment]
thanks,the problem is resolved
