### ISSUE TITLE
Allow user to override Command without overriding Connection

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#7674]
I want to be able to extend the Command class to add shortcut commands like: 
- copyTable()

The problem is that Connection::createCommand() has the Command class hardcoded.
A simple solution would be to use a variable like used elsewhere: Connection::$commandClass.

**Comment by klimov-paul** [comment]
Why don't use `CommandBuilder` ?

**Comment by SamMousa** [comment]
Because then I have to override a class for each database backend. 
Furthermore it is not about the solution to implement a copyTable function; that's just an example.

Basically there should be no hard coded class names when we can use configuration instead.

Gridview has $dataColumnClass;
BaseMailer has $messageClass;
User has $identityClass;

**Comment by klimov-paul** [comment]
All shortcut methods at `Command`, such as 'insert', 'update' and so on, are just a wrapper around `QueryBuilder` methods.

> Because then I have to override a class for each database backend. 

Perhaps you will just have to do so. It is very likely different database engines have different syntax for this or even some of them don't have a support for it.

Still request make sense to me. Lets wait for other opinions.

**Comment by SamMousa** [comment]
There could obviously be efficient tricks for doing it in some backends. But any composition of existing functions should be in Command..
For example, regenerateIndex could be done by dropIndex and createIndex (efficiency is not the point here, but an implementation that works everywhere is; this could then be optimized by mysql\Command or pgsql\Command in case they have more efficient alternatives..

**Comment by SamMousa** [comment]
#10740

**Comment by santilin** [comment]
https://github.com/yiisoft/yii2/issues/9740
