### ISSUE TITLE
Custom MultiLanguage Behavior (Recursion issue)

### ISSUE THREAD

**Issue by maykinayki** [yiisoft/yii2#7675]
![test](https://cloud.githubusercontent.com/assets/5925737/6603601/93d27368-c83c-11e4-9819-28928d96ed63.jpg)

I've created custom MultiLanguage Behavior. As it seems it works properly. But When I'm debugging the result set. I see *Recursion*. That is the only issue. Is there any problem or not?

**Comment by samdark** [comment]
No, it's not a problem.
