### ISSUE TITLE
yii\db\Connection::transaction() is not safe for nested transaction usage

### ISSUE THREAD

**Issue by fsateler** [yiisoft/yii2#7680]
Nested transactions as documented in the long way works as expected:

```php
$outerTransaction = $db->beginTransaction();
try {
    $db->createCommand($sql1)->execute();

    $innerTransaction = $db->beginTransaction();
    try {
        $db->createCommand($sql2)->execute();
        $innerTransaction->commit();
    } catch (Exception $e) {
        $innerTransaction->rollBack();
    }

    $outerTransaction->commit();
} catch (Exception $e) {
    $outerTransaction->rollBack();
}
```

If inner transaction fails or outer transaction is rolled back, nothing is commited.

However, using `transaction()` doesn't work:

```php
$db->transaction(function ($db) {
    // outer transaction
    
    $db->transaction(function ($db) {
        // inner transaction
    });
});
```

Because the transaction object is not passed into the closure, one must use `$db->transaction`. The problem is that this object will always (as far as I can see) point to the outer transaction. Therefore committing explicitly the inner transaction will result in committing to the database even if the outer transaction is then rolled back.

I am not sure what is the best way to solve this problem.

**Comment by qiangxue** [comment]
This is not true. There is only a single transaction object. We record the nesting level in this transaction object. When in an inner transaction, savepoint (if it is supported) is used to do the commit/rollback.

**Comment by fsateler** [comment]
On 26 March 2015 at 09:43, Qiang Xue <notifications@github.com> wrote:

> There is only a single transaction object. We record the nesting level in
> this transaction object. When in an inner transaction, savepoint (if it is
> supported) is used to do the commit/rollback.
>

I filed this issue after having the problem, so I don't think this is true.
Upon calling `$con->transaction->commit()` the entire transaction is
commited, not only the latest savepoint. This does not occur if using
`$trans = $db->beginTransaction()` and calling `$trans->commit()`


-- 

Saludos,
Felipe Sateler

**Comment by qiangxue** [comment]
You shouldn't call `commit()` in your transaction callback because it is implicitly called after your callback.

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
