### ISSUE TITLE
AR and attributes

### ISSUE THREAD

**Issue by Rathil** [yiisoft/yii2#7681]
God day.
I had a interesting question about the AR in Yii2.
When working with attributes, like:
$model = new User();
$model->id = 55;
it is not the same as:
$model->setAttribute('id', 55);

In code to work with the AR, practically not used methods setAttribute(), setAttributes(), getAttribute(), getAttributes(), but direct access to the variable $_attributes
And loss of control with these attributes for further control of the mechanism.
There is no possibility to override a method and gain control get attributes, if I want to extend or something specific to do.
Possible should rewritten mechanism working with attributes?

**Comment by Rathil** [comment]
Even when filling out the data from the database, model is not filled through these methods

**Comment by dynasource** [comment]
please look into our Definitive guide for the Yii way to do it http://www.yiiframework.com/doc-2.0/guide-structure-models.html
