### ISSUE TITLE
PostgreSQL: bad type conversion for bit type

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/yii2#7682]
Postgres returns bit as a string, e.g. '101'
but current type conversion makes integer 101, it's not correct.
The same problem with insert, integer is not correct for postgres bit type.

http://www.postgresql.org/docs/current/static/datatype-bit.html
http://www.postgresql.org/docs/current/static/datatype.html#DATATYPE-TABLE

I think it needs to add one more abstract type into `Schema` class

``` php
const TYPE_BIT = 'bit';
```

And then convert the type for php `bindec()` and for db `decbin()`

**Comment by Yiivgeny** [comment]
This conversion also thrown ```String data, length mismatch: 7 ERROR:  bit string length 4 does not match type bit(8)```, for data zero-leading ('00001111') values on bit columns.

**Comment by Yiivgeny** [comment]
May be using ```'bit' => self::TYPE_STRING``` in ```typeMap``` as lightweight fix? Not ideal, but not cause error or read\write fully incorrect data?

**Comment by Tigrov** [comment]
I made an extention to fix it
https://github.com/Tigrov/yii2-pgsql
