### ISSUE TITLE
Url: allow foreign sites ? 

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7684]
Then I tried to put raw link into layout menu (`'url' => ['https://oauth2server.mycompany.com/signup']`), I got it glued to original website base url: `https://oneofmyservices.mycompany.com/https://oauth2server.mycompany.com/signup`.

Had to create `SiteController::actionSignup()` for one-line redirect.

**Comment by samdark** [comment]
Don't use `[]` for external URLs.
