### ISSUE TITLE
error display problem

### ISSUE THREAD

**Issue by jomonkj** [yiisoft/yii2#7686]
I am using 18.5  inch monitor . 

![yii2 error screen](https://cloud.githubusercontent.com/assets/11212888/6617020/ef769e7c-c8d9-11e4-8552-7d5e498a872f.JPG)

**Comment by samdark** [comment]
That's known problem. Can't find exact issue number now but I think it's reported already.

**Comment by jomonkj** [comment]
Is it solved issue?

**Comment by samdark** [comment]
No.

**Comment by klimov-paul** [comment]
Duplicates #4763
