### ISSUE TITLE
Elasticsearch http_address 

### ISSUE THREAD

**Issue by djfly** [yiisoft/yii2#7690]
config
```
 'components' => [
        'elasticsearch' => [
            'class' => 'yii\elasticsearch\Connection',
            'nodes' => [
                ['http_address' => '127.0.0.1:9200'],
                // configure more hosts if you have a cluster
            ],
        ],
    ]
````

error
````
Elasticsearch Database Exception – yii\elasticsearch\Exception

Elasticsearch request failed: 7 - couldn't connect to host
Error Info: Array
(
    [requestMethod] => PUT
    [requestUrl] => http://192.168.1.103:9200/issue2s/issue2/1?op_type=create
    [requestBody] => {}
    [responseHeaders] => Array
        (
        )

    [responseBody] => 
)
````

why it is http://192.168.1.103:9200/, i'm set 127.0.0.1:9200 in config

**Comment by Borales** [comment]
@djfly that's because of `autodetectCluster` (https://github.com/yiisoft/yii2/blob/master/extensions/elasticsearch/Connection.php#L107)

Try to set `autodetectCluster` to `false` and check it again.

**Comment by cebe** [comment]
In case you have this on your dev machine when you switch networks, you have to restart elasticsearch because it needs to detect new envirnoment.

**Comment by djfly** [comment]
set autodetectCluster to false is ok
