### ISSUE TITLE
Feature request: findone with where

### ISSUE THREAD

**Issue by horizons2** [yiisoft/yii2#7691]
Some Feature Request
Would it be possible to make this functional?
```
$model = DataProjectLevel::findOne($id)->where(['project_id'=>3]);
```
Because i wanted to add some searchcritera additional to the primary key and doesn't want to have the "name" of the primary key in the code like below. (code part from the findModel function in the controller generated by gii)
```
if (($model = DataProjectLevel::findOne(['level_id' => $id, 'project_id'=>3]))  !== null) {
or
if (($model = DataProjectLevel::find()->where(['level_id' => $id, 'project_id'=>6])->one()) !== null) {
```

Also I didn't like to have this code just to get the name of the primary key into the code dynamically.
```
$searchModel= new DataProjectLevel;
if (($model = DataProjectLevel::findOne(array_merge([$searchModel->primaryKey()[0] => $id], $othersearchOptions))) !== null) {
```

Background I have a Controller which is project specific and only displays and allows to open database entries for the current project which is selected by the url path.
so with the url /project/3/projectlevels/update?id=5 the model shouldn't be returned by the findModel function in the controller and should just throw an error, which would be if the select doesn't return a result.

regards Horizons

**Comment by qiangxue** [comment]
Nope, we will not support this because it breaks BC and is against the original intention of introducing `findOne()`. You should be able to implement this feature in your own base AR class.
