### ISSUE TITLE
Bad Request (#400) - Unable to verify your data submission

### ISSUE THREAD

**Issue by ipppinto** [yiisoft/yii2#7692]
SInce I update to yii 2.0.3 I have this error but there are intermittent. Sometimes appears and sometimes the forms work well.  
I have <?= Html::csrfMetaTags() ?> in my main.php.

I have Advanced Application Template

There is any configuration more?

**Comment by ipppinto** [comment]
Any comment?

**Comment by samdark** [comment]
Need more data about how to reproduce it else we can't fix it.

**Comment by ipppinto** [comment]
Hi,

What data you nedd? View? COntroller? Model? Any command?

Thank you

**Comment by lichunqiang** [comment]
I think you can track it by log

**Comment by ipppinto** [comment]
How can I track it by log? What I have to do in my code?

**Comment by ipppinto** [comment]
What data you need? View? COntroller? Model? Any command?

**Comment by ipppinto** [comment]
Any comment?

**Comment by ipppinto** [comment]
I work hours without any problem. I create, update my forms very well. But without reason I have this error. Ctrl+F5 many times and work well again. No change code, nothing.

**Comment by samdark** [comment]
I cannot reproduce it locally so I have no idea what may cause it.

**Comment by ipppinto** [comment]
There are any configuration of csrfMetaTags that I don't have? Or session data?

**Comment by ipppinto** [comment]
I have the error again. I have this in my meta:

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-param" content="_csrf">
    <meta name="csrf-token" content="OWU3cXNTQnV3Lk9DNiUMAmwVBjMEKiYwUixcNB0CIDxuFXU/RgMJNw==">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

**Comment by samdark** [comment]
Well, it looks that token is registered. So you're not missing this part at least. Do you have any custom config related to cookies? Using subdomains maybe?

**Comment by ipppinto** [comment]
Yes I have my app (I have Advanced Application Template) in a subdomain.

In main-local I have this:

<?php

$config = [
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'r3FfZpLvy8p_64xgc35SrBfx7ngg7AUp',
        ],
    ],    
];

if (!YII_ENV_TEST) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}

return $config;

**Comment by samdark** [comment]
Do you have frontend and backend on separate subdomains or it's the same domain?

**Comment by ipppinto** [comment]
I have frontend and backend in same subdomain.

I have this in backend/frontend->htaccess:
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule . index.php

I have different in other htaccess:

Options -Indexes
<IfModule mod_rewrite.c> 
  RewriteEngine on
  RewriteCond %{REQUEST_URI} !^public
  RewriteRule ^(.*)$ frontend/web/$1 [L] 
</IfModule>
# Deny accessing below extensions
<Files ~ "(.json|.lock|.git)">
Order allow,deny
Deny from all
</Files>
# Deny accessing dot files
RewriteRule (^\.|/\.) - [F]

My frontend main.php:

<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

use \yii\web\Request;
$baseUrl = str_replace('/frontend/web', '', (new Request)->getBaseUrl());

return [
    'id' => 'app-frontend',
    'name'=>'Intranet - Câmara Municipal de Condeixa',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],    
    'controllerNamespace' => 'frontend\controllers',
    //'bootstrap' => ['gii'],
    'modules' => [
//        'gii' => [
//          'class' => 'yii\gii\Module', //adding gii module
//          'allowedIPs' => ['127.0.0.1', '5.196.16.34', '::1'],  //allowing ip's 
//        ],
    ],    
    'components' => [
        'request' => [
            'baseUrl' => $baseUrl,
        ],        
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'view' => [
            'theme' => [
                'pathMap' => ['@frontend/views' => '@frontend/themes/cmc/views'],
                'baseUrl' => '@web/themes/cmc',

             ],
        ], // here demo is your folder name        
        'urlManager' => [
            'baseUrl' => $baseUrl,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => []
        ],
        'assetManager' => [
            'bundles' => [
                // não incluí o jquery da yii      
                'yii\web\JqueryAsset' => [
                    'js' => [] 
                 ],
                'yii\bootstrap\BootstrapAsset' => [
                    'css' => [],
                ],
            ],
         ],       
    ],
    'as AccessBehavior' => [
       'class' => '\frontend\components\AccessBehavior'
    ],    
    'params' => $params,
];

**Comment by samdark** [comment]
Your issue is that CSRF keys are clashing between frontend and backend. See http://www.yiiframework.com/doc-2.0/guide-tutorial-shared-hosting.html#deploying-an-advanced-application

**Comment by ipppinto** [comment]
Thank you.
I read and I'm worried because I have all my file structure in public_html/subdomain. 

My application is insecure for that?

**Comment by samdark** [comment]
Well, it's not what advanced app was intended for but it could work this way with some tuning.

**Comment by ipppinto** [comment]
Ok. Have I to change my main.php to separate session and cookies, right?

**Comment by samdark** [comment]
Yes.

**Comment by ipppinto** [comment]
There are any examples for my case?

**Comment by ipppinto** [comment]
Can you help me with this?

If I have in my main.php (backend) this:

        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
            'identityCookie' => [
                'name' => '_backendIdentity',
                'path' => '/sessioncookies',
                'httpOnly' => true,
            ],            
        ],
        'session' => [
            'name' => 'BACKENDSESSID',
            'cookieParams' => [
                'path' => '/sessioncookies',
            ],
        ],
        'request' => [
            'csrfParam' => '_backendCSRF',
            'csrfCookie' => [
                'httpOnly' => true,
                'path' => '/sessioncookies',
            ],
        ], 

Where I have to put the folder sessioncookies? The file htaccess is important?

common
    config/      
    mail/        
    models/      
console
    config/      
    controllers/ 
    migrations/  
    models/      
    runtime/     
backend
    assets/      
    config/      
    controllers/ 
    models/      
    runtime/     
    views/       
    web/         
frontend
    assets/      
    config/      
    controllers/ 
    models/      
    runtime/     
    views/       
    web/         
    widgets/     
vendor/
sessioncookies (where?)

**Comment by samdark** [comment]
It's not a directory. It's cookie path.

**Comment by ramasamykasi** [comment]
Me also had same problem. But I fixed this by doing following,

Have same value for the field **_cookieValidationKey_** in both front and backend main-local.php config file.

**Comment by dynasource** [comment]
@samdark, shouldnt this section be part of the guide? https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-shared-hosting.md#adjust-sessions-and-cookies

**Comment by samdark** [comment]
@dynasource keys are different by default so there should not be a conflict.

**Comment by arpyhd** [comment]
I found that is mising a / in the end of input , ex:
    <input type="hidden" name="_csrf" value="bWs1ZlJSeGYiHG0xNThVNgBYBzY8FAI5PS4CVn8lJzMeIkAgKgU0Ig==">
    working input is:
    <input type="hidden" name="_csrf" value="bWs1ZlJSeGYiHG0xNThVNgBYBzY8FAI5PS4CVn8lJzMeIkAgKgU0Ig==" /> in my
    case:
    I modified yiisoft/yii2/helpers/BaseHtml
    public static function tag($name, $content = '', $options = [])
    {
        if ($name === null || $name === false) {
            return $content;
        }
		if ($name=="input") {$html = "<$name" . static::renderTagAttributes($options) . '/>';}
		else {$html = "<$name" . static::renderTagAttributes($options) . '>';      }
		
        return isset(static::$voidElements[strtolower($name)]) ? $html : "$html$content</$name>";
    }
