### ISSUE TITLE
problem with activecheckbox,checkbox

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#7697]
i have problem with the template of the checkbox im trying make this

< label class="inline">
                        < input type="checkbox" class="ace" />
                        < span class="lbl"> Recordarme< /span>
                    < /label>
but i obtain this

< label>< input type="checkbox" id="loginform-rememberme" name="LoginForm[rememberMe]" value="1" checked=""> Recordarme< /label>

how can make <span class="lbl">Recordarme</span> ? using the attribute template,inputTemplate,etc

added..

im trying this < ?= $form->field($model, 'rememberMe')->checkbox(['class' => 'ace','labelOptions' => ['template' => '< span>{label}< /span>']]) ?>

and i receive this...

< input type="checkbox" id="loginform-rememberme" name="LoginForm[rememberMe]" value="1" checked=""> Recordarme

reading the file yii\helpers\basehtml i see this code

public static function checkbox($name, $checked = false, $options = [])
    {
        $options['checked'] = (bool) $checked;
        $value = array_key_exists('value', $options) ? $options['value'] : '1';
        if (isset($options['uncheck'])) {
            // add a hidden field so that if the checkbox is not selected, it still submits a value
            $hidden = static::hiddenInput($name, $options['uncheck']);
            unset($options['uncheck']);
        } else {
            $hidden = '';
        }
        if (isset($options['label'])) {
            $label = $options['label'];
            $labelOptions = isset($options['labelOptions']) ? $options['labelOptions'] : [];
            unset($options['label'], $options['labelOptions']);
            $content = static::label(static::input('checkbox', $name, $value, $options) . ' ' . $label, null, $labelOptions);
            return $hidden . $content;
        } else {
            return $hidden . static::input('checkbox', $name, $value, $options);
        }
    }

in special this lane
 $content = static::label(static::input('checkbox', $name, $value, $options) . ' ' . $label, null, $labelOptions);

how can add the custom template if this cant work with custom template :S

**Comment by SilverFire** [comment]
The issue seems to be already fixed. Closing
