### ISSUE TITLE
Does Yii2 Mongodb support 'elemMatch' feature provided by natively Mongodb

### ISSUE THREAD

**Issue by samfreelancer** [yiisoft/yii2#7698]
Sorry, i don't know whether it is an issue or not. But it's difficult for me to figure this out as i have searched a lot on this but couldn't find anything. I am stuck in a situation. Consider the below mentioned Mongodb document for example and i want to find out if a user tring to reset his/her password have the exact reset password code, which is not used so far and not even expired. So, all these conditions should be fulfilled by one single embedded document.
{
	"_id" : ObjectId("550039ec239016843c8b4568"),
	"name" : "Sameer Arora",
	"username" : "",
	"password" : "8f1327ad7a0a3c430bc2a2a31dc64b1f",
	"email" : "",
	"authKey" : "",
	"accessToken" : "",
	"created" : "",
	"modified" : "",
	"status" : 1,
	"resetPassword" : [
		{
			"code" : "0a469cc448ee21151ee2da8cee09a56d",
			"created" : "2015-03-12 07:42:20.0.67806100",
			"isUsed" : 0,
			"usedDate" : "",
			"isExpired" : 0,
			"expireDate" : "2015-03-13 07:42:20"
		},
		{
			"code" : "49fe7924d467597648b363005d46b393",
			"created" : "2015-03-12 07:43:29.0.32031300",
			"isUsed" : 1,
			"usedDate" : "2015-03-12 07:44:36",
			"isExpired" : 0,
			"expiryDate" : "2015-03-13 07:43:29"
		}
	]
}

I can use the following native Mongodb feature to get the result 

db.collection.find({ "resetPassword" : { "$elemMatch" : { "code" : '49fe7924d467597648b363005d46b393', "isUsed" : 1, 'isExpired' : 0} } })

It gives me exact result i want. But i want to use the same in Yii2. Is there any way i can achieve this in Yii2.

**Comment by klimov-paul** [comment]
Should be:
```php
use yii\mongodb\Query;

$query = new Query();
$query->from('customer')
    ->where([
        'resetPassword' => [
            '$elemMatch' => [
                'code' => '49fe7924d467597648b363005d46b393',
                'isUsed' => 1,
                'isExpired' => 0,
            ],
        ],
    ]);
$rows = $query->all();
```

**Comment by bhavikac** [comment]
is there any update query to update only matched element by $elemMatch
