### ISSUE TITLE
batch() / each()

### ISSUE THREAD

**Issue by longmayar** [yiisoft/yii2#7701]
Microsoft SQL Server, PDO driver.
PHP 5.6.5.
Yii2 last (Composer)

I need to select batches by 10 at time (from 1000000+ rows)
```php
foreach (Song::find()->batch(10) as $songs) {

    // var_dump($songs);      <-- array 10 object(app\models\Song)

    foreach ($songs as $song) {
        var_dump($song->id);
    }
}
```
It takes 10 objects, but it doesn't take next 10. How can i do it?

**Comment by longmayar** [comment]
Russian forum discussion link: http://yiiframework.ru/forum/viewtopic.php?f=19&t=22850

**Comment by longmayar** [comment]
```php
    var_dump(Song::find()->count()); 
```
string(6) "265747"

```php
    foreach(User::find()->each(2) as $model) {
        echo '<p>' . $model->id . '</p>';
    } 
```

var_dump(__METHOD__) in BatchQueryResult class:

string(31) "yii\db\BatchQueryResult::rewind"
string(30) "yii\db\BatchQueryResult::reset"
string(29) "yii\db\BatchQueryResult::next"
string(34) "yii\db\BatchQueryResult::fetchData"
string(30) "yii\db\BatchQueryResult::valid"
string(32) "yii\db\BatchQueryResult::current"
1

string(29) "yii\db\BatchQueryResult::next"
string(30) "yii\db\BatchQueryResult::valid"
string(32) "yii\db\BatchQueryResult::current"
2

string(29) "yii\db\BatchQueryResult::next"
string(34) "yii\db\BatchQueryResult::fetchData"
string(30) "yii\db\BatchQueryResult::valid"
string(35) "yii\db\BatchQueryResult::__destruct"
string(30) "yii\db\BatchQueryResult::reset"

**Comment by longmayar** [comment]
If i do:
```php
$query = (new Query)->from('song');
foreach ($query->batch(10) as $song) {
    var_dump($song);
}
```
it's ok, but i need ActiveRecord

**Comment by klimov-paul** [comment]
Unit test for bacth query result passes correctly:
https://github.com/yiisoft/yii2/blob/master/tests/unit/framework/db/BatchQueryResultTest.php

Sinse you are able to retrieve all data you need using plain `Query` this is also not MSSQL or PDO specific.

Most likely you have made some modifications of the ActiveQuery returned by `Song::find()`: setup of extra conditions, limit or something.
