### ISSUE TITLE
Assets publishing with 'forceCopy' on Win+Vagrant causes redundant trailing characters

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#7702]
Environment: `Windows 8` + `Vagrant (Ubuntu 14.04)`
Web-server: `nginx 1.4.6` + `php-fpm 5.5.9`

When I have added to the `main-local.php` next config:
```
       'assetManager' => [
            'class' => 'yii\web\AssetManager',
            'forceCopy' => true,
        ],
```
and started to develop my JS asset. Before that, I removed `web/assets/<hash>` each time I wanted to check my code. At first force-copy after the config modification I found, that my JS was crashed with the error: `Uncaught Syntax Error: Unexpected Token ILLEGAL`

I opened the JS file in the new tab and found this:
![Trailing characters](http://savepic.ru/6763943.png)

The first what I checked in the original file was line breaks and encoding - and they was correct: `LF`
and `UTF-8`. Also, both of the files have the same MD5 hash:

```
$ md5sum assets/js/myScript.js web/assets/5bb2af66/js/myScript.js 
f86602ecb7ca0fb06a0c68bd2c4648ff  assets/js/myScript.js
f86602ecb7ca0fb06a0c68bd2c4648ff  web/assets/5bb2af66/js/myScript.js
```

Here if the hexdump of the tail of the file (and it if the same with the original file):
```
$ hexdump -C web/assets/5bb2af66/js/myScript.js | tail
00000b60  7d 2c 0a 09 09 09 6f 6e  43 68 61 6e 67 65 3a 20  |},....onChange: |
00000b70  66 75 6e 63 74 69 6f 6e  20 28 65 29 20 7b 0a 09  |function (e) {..|
00000b80  09 09 09 72 65 74 75 72  6e 20 66 61 6c 73 65 3b  |...return false;|
00000b90  0a 09 09 09 7d 2c 0a 09  09 09 73 6f 6d 65 54 65  |....},....someTe|
00000ba0  73 74 45 76 65 6e 74 3a  20 66 75 6e 63 74 69 6f  |stEvent: functio|
00000bb0  6e 20 28 65 29 20 7b 0a  09 09 09 09 63 6f 6e 73  |n (e) {.....cons|
00000bc0  6f 6c 65 2e 6c 6f 67 28  27 79 65 61 68 21 27 29  |ole.log('yeah!')|
00000bd0  3b 0a 09 09 09 7d 0a 09  09 7d 0a 09 7d 29 3b 0a  |;....}...}..});.|
00000be0  7d 29 3b 0a                                       |});.|
00000be4
```

I found, that the `�` characters appears at the end only if I am adding the text to the JS file.
I've found the only way to fix this:

in the yii\helpers\BaseFileHelper.php:279 before `copy($from, $to)` add this:
```php
                    if (is_file($to)) {
                        unlink($to);
                    }
```

*I have found, that this bug reproduces only in the shared with Windows folders!*
If i move the project out of shared with the host folder, the problem does not appears.

So, the way to reproduce:

* start the Vagrant WM with the web-server and shared with the host folder;
* put the gist https://gist.github.com/SilverFire/1ee2fa3734571153cb1c
* put the file `test.js` near to the php file;
* run the app, check in the web-browser, if the JS in `test_copy.js` is OK;
* add some lines to the `test.js`;
* run the app again, find the `�` characters at the end.

WTF?!

**Comment by SilverFire** [comment]
Maybe post this to the https://github.com/mitchellh/vagrant/issues ?

**Comment by SilverFire** [comment]
Or even this:

```
vim test.js (add some lines)
cp test.js test2.js
vim test.js (add some lines again)
cp test.js test2.js
```

Will result in a fail!

**Comment by klimov-paul** [comment]
This issue is out of framework scope. We can not bypass it.

**Comment by SilverFire** [comment]
The solution was found and added to the vagrant docs: https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
