### ISSUE TITLE
"Unable to resolve the relative route: editorial/view. No active controller is available."

### ISSUE THREAD

**Issue by dhiman252** [yiisoft/yii2#7703]
I am using the YII2 rest API's. 
In my active record i have implemented the following code.

namespace app\models;

use Yii;
use yii\web\Link;
use yii\web\Linkable;
use yii\db\ActiveRecord;
use yii\helpers\Url;

/**
 * This is the model class for table "editorial".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $user_id
 * @property integer $created
 * @property integer $updated
 *
 * @property ApiUser $user
 * @property EditorialComments[] $editorialComments
 * @property EditorialDislikeData[] $editorialDislikeDatas
 * @property EditorialLikeData[] $editorialLikeDatas
 */
class Editorial extends ActiveRecord implements Linkable
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'editorial';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'user_id', 'created', 'updated'], 'required'],
            [['description'], 'string'],
            [['user_id', 'created', 'updated'], 'integer'],
            [['user_id'], 'exist', 'targetClass' => 'app\models\User', 'targetAttribute' => 'id' ],
            [['title'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'user_id' => 'User ID',
            'created' => 'Created',
            'updated' => 'Updated',
        ];
    }
    
    public function fields() {
        return [
            'id',
            'title',
            'description',
            'user_id' => function(){
                return $this->user;
            },
            'created' => function(){
                return date('Y-m-d H:i:s',  $this->created);
            },
            'updated' => function(){
                return date('Y-m-d H:i:s',  $this->created);
            }
        ];        
    }
    
    public function beforeValidate() {
        if($this->isNewRecord){
            $this->created = time();
            $this->updated = time();
        } else {
            $this->updated = time();
        }
        return parent::beforeValidate();
    }

    public function getLinks(){
        return [
            Link::REL_SELF => Url::to(['editorial/view', 'id' => $this->id], true)
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEditorialComments()
    {
        return $this->hasMany(EditorialComments::className(), ['editorial_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEditorialDislikeDatas()
    {
        return $this->hasMany(EditorialDislikeData::className(), ['editorial_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEditorialLikeDatas()
    {
        return $this->hasMany(EditorialLikeData::className(), ['editorial_id' => 'id']);
    }
}

I am getting th<?php

namespace app\models;

use Yii;
use yii\web\Link;
use yii\web\Linkable;
use yii\db\ActiveRecord;
use yii\helpers\Url;

/**
 * This is the model class for table "editorial".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $user_id
 * @property integer $created
 * @property integer $updated
 *
 * @property ApiUser $user
 * @property EditorialComments[] $editorialComments
 * @property EditorialDislikeData[] $editorialDislikeDatas
 * @property EditorialLikeData[] $editorialLikeDatas
 */
class Editorial extends ActiveRecord implements Linkable
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'editorial';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'user_id', 'created', 'updated'], 'required'],
            [['description'], 'string'],
            [['user_id', 'created', 'updated'], 'integer'],
            [['user_id'], 'exist', 'targetClass' => 'app\models\User', 'targetAttribute' => 'id' ],
            [['title'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'user_id' => 'User ID',
            'created' => 'Created',
            'updated' => 'Updated',
        ];
    }
    
    public function fields() {
        return [
            'id',
            'title',
            'description',
            'user_id' => function(){
                return $this->user;
            },
            'created' => function(){
                return date('Y-m-d H:i:s',  $this->created);
            },
            'updated' => function(){
                return date('Y-m-d H:i:s',  $this->created);
            }
        ];        
    }
    
    public function beforeValidate() {
        if($this->isNewRecord){
            $this->created = time();
            $this->updated = time();
        } else {
            $this->updated = time();
        }
        return parent::beforeValidate();
    }

    public function getLinks(){
        return [
            Link::REL_SELF => Url::to(['editorial/view', 'id' => $this->id], true)
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEditorialComments()
    {
        return $this->hasMany(EditorialComments::className(), ['editorial_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEditorialDislikeDatas()
    {
        return $this->hasMany(EditorialDislikeData::className(), ['editorial_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEditorialLikeDatas()
    {
        return $this->hasMany(EditorialLikeData::className(), ['editorial_id' => 'id']);
    }
}

In my controller action i have

public function actionCreate()
    {        
        $model = new Editorial();        
        $model->attributes = Yii::$app->request->post();
        if ($model->validate() && $model->save()) {
            return [
                'response'  => $model
            ];
        } else {
            return [
                'response' => Inflector::sentence(array_map( function($val){ return rtrim($val,'.'); }, $model->getFirstErrors()))
            ];
        }
    }

when i hit the controller action(editorial/create) i get the following error
{
"name": "Exception",
"message": "Unable to resolve the relative route: editorial/view. No active controller is available.",
"code": 0,
"type": "yii\\base\\InvalidParamException",
"file": "/home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/helpers/BaseUrl.php",
"line": 129,
"stack-trace": [
"#0 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/helpers/BaseUrl.php(91): yii\\helpers\\BaseUrl::normalizeRoute('editorial/view')",
"#1 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/helpers/BaseUrl.php(202): yii\\helpers\\BaseUrl::toRoute(Array, true)",
"#2 /home/bestwebrv7/public_html/smatt/api/models/Editorial.php(95): yii\\helpers\\BaseUrl::to(Array, true)",
"#3 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/base/ArrayableTrait.php(124): app\\models\\Editorial->getLinks()",
"#4 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/helpers/BaseJson.php(94): yii\\base\\Model->toArray()",
"#5 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/helpers/BaseJson.php(111): yii\\helpers\\BaseJson::processData(Object(app\\models\\Editorial), Array, '5502b99a9d708')",
"#6 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/helpers/BaseJson.php(37): yii\\helpers\\BaseJson::processData(Array, Array, '5502b99a9d708')",
"#7 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(53): yii\\helpers\\BaseJson::encode(Array)",
"#8 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(41): yii\\web\\JsonResponseFormatter->formatJson(Object(yii\\web\\Response))",
"#9 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/web/Response.php(932): yii\\web\\JsonResponseFormatter->format(Object(yii\\web\\Response))",
"#10 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/web/Response.php(312): yii\\web\\Response->prepare()",
"#11 /home/bestwebrv7/public_html/smatt/vendor/yiisoft/yii2/base/Application.php(381): yii\\web\\Response->send()",
"#12 /home/bestwebrv7/public_html/smatt/api/index.php(12): yii\\base\\Application->run()",
"#13 {main}"
]
}

if i change the line ('response'  => $model) to $model->attributes it works well but when i make a change to Editorial::findOne($model->id) i still get the above error

**Comment by n1k88** [comment]
Change the route from ``editorial/view`` to ``/editorial/view``

**Comment by dhiman252** [comment]
Yes, Its working. Thanks Buddy :)

**Comment by little-bit-shy** [comment]
so good

**Comment by lp994141990** [comment]
Nice
