### ISSUE TITLE
FilterValidator|trim works incorrectly on client side

### ISSUE THREAD

**Issue by Koudy** [yiisoft/yii2#7707]
Here is my Model::rules:
```
public function rules()
{
    return [
        [['email', 'password'], 'required'],
        ['rememberMe', 'boolean'],

        [['email'], 'trim'],
        ['email', 'email'],
        ...
    ]
}
```

When I insert "     test@mail.com" trim works, but I still get error:
![d32f0832-c995-11e4-93b2-cd9385334871](https://cloud.githubusercontent.com/assets/4976467/6640880/4c68359c-c9ab-11e4-8726-1f4245c69a51.png)

**Comment by nkovacs** [comment]
getValue reads the value once here: https://github.com/yiisoft/yii2/blob/2.0.4/framework/assets/yii.activeForm.js#L294, and all the validators use this value. The trim validator changes the input's value, but the other validators use the outdated value passed by yii.activeform.js.
