### ISSUE TITLE
Problem with combining assets

### ISSUE THREAD

**Issue by balajigans** [yiisoft/yii2#7708]
I'm trying to combine all the js & css under only one asset bunde named "AppAsset.php" as shown below.

#### AppAsset.php
    <?php
    namespace app\assets;
    use yii\web\AssetBundle;
    class AppAsset extends AssetBundle
    {
        public $basePath = '@webroot';
        public $baseUrl = '@web';
        public $css = [
            'css/common.css',
            'css/fontawesome.css',
            'css/fonts.css',
            'css/stylesheet.css',
        ];
        public $js = [
            'js/libs/support.js',
            'js/libs/imagesloaded.js',
            'js/libs/cycle.js',
            'js/utils.js',
            'js/script.js',
        ];
        public $depends = [
            'yii\web\JqueryAsset',
        ];
    }

#### CombineConfig.php
    <?php
    Yii::setAlias('@webroot', __DIR__ . '/../web');
    Yii::setAlias('@web', '/');
    return [
        'jsCompressor' => 'java -jar compiler.jar --js {from} --js_output_file {to}',
        'cssCompressor' => 'java -jar yuicompressor.jar --type css {from} -o {to}',
        'bundles' => [
            'app\assets\AppAsset'
        ],
       'targets' => [
            'all' => [
                'class' => 'app\assets\AppAsset',
                'basePath' => '@webroot',
                'baseUrl' => '@web',
                'js' => 'static/{hash}.js',
                'css' => 'static/{hash}.css',
            ],
        ],
        'assetManager' => [
            'basePath' => '@webroot/assets',
            'baseUrl' => '@web/assets',
        ],
    ];

#### Result
And when i run the **asset** command using the above config file, I receive the following output which results in cyclic dependency,

    <?php
    /**
     * This file is generated by the "yii asset" command.
     * DO NOT MODIFY THIS FILE DIRECTLY.
     * @version 2015-03-13 15:52:28
     */
    return [
        'all' => [
            'class' => 'app\\assets\\AppAsset',
            'basePath' => '@webroot',
            'baseUrl' => '@web',
            'js' => [
                'static/a73ac9d5706ebe0a70da3a90c5fc805f.js',
            ],
            'css' => [
                'static/6db80aad81056824af8d39cadd5e07a2.css',
            ],
        ],
        'yii\\web\\JqueryAsset' => [
            'sourcePath' => null,
            'js' => [],
            'css' => [],
            'depends' => [
                'all',
            ],
        ],
        'app\\assets\\AppAsset' => [
            'sourcePath' => null,
            'js' => [],
            'css' => [],
            'depends' => [
                'yii\\web\\JqueryAsset',
                'all',
            ],
        ],
    ];

#### Help
Can some one tell me where I'm going wrong or is it a bug in Yii 2?

**Comment by klimov-paul** [comment]
You should not use class name of your existing bundle for the compression target:
```php
'targets' => [
        'all' => [
            'class' => 'app\assets\AppAsset', // Here is your mistake
```
