### ISSUE TITLE
Get all the relations of a model

### ISSUE THREAD

**Issue by balajigans** [yiisoft/yii2#7710]
In Yii 1 all the relations of a model can be fetched by,

	foreach(Modelname::model()->relations() as $relation){
	// Code to do something
	}

How do i replicate this action in Yii 2?

**Comment by cebe** [comment]
this is not possible because relations are defined as getter methods.

**Comment by balajigans** [comment]
Is there any way this option can be added to Yii 2?

**Comment by cebe** [comment]
I do not see any. You could iterate over defined getters using php reflection and check annotated return type but that is not 100% reliable. What is your use case for this?

**Comment by dapatrese** [comment]
there are some code examples for iterating over getters in #1282

**Comment by balajigans** [comment]
In all my websites, I normally keep the deleted records in database for a month before clearing them out from  MySQL. So i run a cron job to delete the records & its relations for more than one table. 

For e.g, I store all my images in a table called "images". In Yii 1.0, I run the following script at the end of every month to delete the unwanted images from disk & mysql,

	$images = Images::model()->findAll('DATE(timestamp) > date_sub(now(), interval 1 month)');
	foreach($images as $i){
		$flag = 0;
        foreach(Images::model()->relations() as $key=>$value){
            if(!empty($i->$key))
               $flag++;
        }
		if($flag == 0){
			$i->delete();
			@unlink('path to original image');
			@unlink('path to thumb image');
			@unlink('path to resized image');
			$c++;
		}
	}

Similarly i perform the delete operations on other tables too.

**Comment by cebe** [comment]
you can define ON DELETE CASCADE in the foreign keys to let the database do this job for you.
also note that relations may be in other directions, as far as I see from your code if you have an author relation from the image to a user the user will get deleted too...

**Comment by winternet-studio** [comment]
Sorry to bring this up again, but isn't a good use case for this (which was also asked for in #9857) the ability to check for any related models before deleting a given model (when cascade delete is disabled)? This is a very common scenario - which I'm struggling with right now...
