### ISSUE TITLE
Support for ordering results using the keyset method

### ISSUE THREAD

**Issue by lourdas** [yiisoft/yii2#7712]
Markus Winand describes in his web site how to order results effectively. His [article] (http://use-the-index-luke.com/no-offset) describes this method.

A short summary is this: When you have to page through many results (hundreds or thousands and even more), the more deep you go (select previous pages), the more work the database has to do, because it has first to sort all the results and then use the offset and limit clauses to fetch the rows of interest. The keyset method that Markus describes uses the same principles, but in addition uses the pk id to limit the results (something like `WHERE id > ? ORDER BY col LIMIT pagesize`). Using this extra condition (`id > ?`) the database can limit the rows for sorting by using the primary key index to discard unneeded records, which is a fast procedure. So, using this keyset method, the database does not have to fetch rows that it would discard anyway (the records that appear in the first pages).

Of course, the keyset method has its cons. You have to somehow store the pk id to fetch the next page. In case the user changes the sort order (clicks on another column in the grid), the last stored pk id becomes invalid and it has to be "calculated" from scratch. But I think that in the long run, the gains are important (fast -small response time- grids when paging).

Thank you.

**Comment by samdark** [comment]
Have you verified performance improvements personally?

**Comment by lourdas** [comment]
Not yet, but I intend to do so using PostgreSQL. I will report the results here.

**Comment by samdark** [comment]
No feedback for quite a long time. Closing.

**Comment by lourdas** [comment]
I see that the keyset method has been implemented in the data package (Yii 3), see https://github.com/yiisoft/data/issues/1. Could we perhaps see a Yii2 implementation?

Thanks!

**Comment by lourdas** [comment]
Thank you @samdark. I am not aware of the implementation status for this method in other frameworks and Yii 3 is a winner just for this one.
