### ISSUE TITLE
UrlManager additional get parameters

### ISSUE THREAD

**Issue by kdietrich** [yiisoft/yii2#7714]
I am trying to use UrlManager with additional get parameters the original route does not contain. See the following example: I've created a controller (SiteController) containing the action "pages" for displaying static pages (\yii\web\ViewAction).

When I open domain.com/site/pages?view=foo the url works perfectly. Now I am trying to rewrite my url so that domain.com/bla rewrites to the aforenamed url (the important part is that the parameter in the url ("bla") is not the same as the parameter passed as the get variable view ("foo"). My url rule looks like the following:

    'bla' => 'site/pages?view=foo'

But this is not working. [yii\web\HttpException:404] exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request: site/pages?view=foo' in...

How can I fix that? Basically I want to have additional or other $_GET params in url route.

//EDIT: This has worked in Yii 1.1 perfectly.

//EDIT2: I could use "defaults" for that ('defaults'=>['view'=>'foo']), but this would not work in the following use-case that worked in Yii 1.1:

    'bla/<action>' => 'site/pages?view=bla/<action>'

**Comment by cebe** [comment]
for simple cases you can use defaults, if you need to append the action you should use either two variables and combine them in controller or exted UrlRule class and add the functionality you need.
