### ISSUE TITLE
AR MongoDb insert/update - prepare of data before insert/update

### ISSUE THREAD

**Issue by Rathil** [yiisoft/yii2#7718]
https://github.com/yiisoft/yii2-mongodb/blob/master/Collection.php#L379
https://github.com/yiisoft/yii2-mongodb/blob/master/Collection.php#L437
and other such places should do something like this:
\yii\helpers\ArrayHelper::toArray(<b>$data</b>)

use \yii\helpers\ArrayHelper;
$this->tryResultError($this->mongoCollection->insert(ArrayHelper::toArray(<b>$data</b>), $options));

This will help to correct the insert or update data when transferred to an object or an array of objects. Also to gain control over the data before inserting in Mongo.

**Comment by klimov-paul** [comment]
This does not make sense. If you with the data be processed by `ArrayHelper::toArray()` you are able to so in your code.
Such feature is a redundant.
