### ISSUE TITLE
Yii2 Get all controllers name and actions

### ISSUE THREAD

**Issue by dungphanxuan** [yiisoft/yii2#7719]
Hello, i have app. So now i want to get all controller name and actions in each controller to manager. So how can i do.
Thank!!

**Comment by mdmunir** [comment]
https://github.com/mdmsoft/yii2-admin/blob/master/controllers/RouteController.php#L196

**Comment by dungphanxuan** [comment]
Hi thanks  @mdmunir

**Comment by syrakozz** [comment]
it return empty

**Comment by SilverFire** [comment]
@syrakozz if you have a problem and you are pretty sure that it's a bug - please, open a new issue with the clear way for its reproducing
