### ISSUE TITLE
Yii2 AssetBundle. Remover jquery v2.1.3 and replace jquery v1.11.0

### ISSUE THREAD

**Issue by dungphanxuan** [yiisoft/yii2#7721]
Hello, i have create widget (editor widget). In my widget can run on jquery v1.11.0. But yii2 load jquery v2.1.3.
So i recive result "Uncaught TypeError: undefined is not a function". That problem will solve when i remover v2.1.3 in web/assets folder

But my app must run jquery v2.1.3 in another action so i can't remover it in config. So now i want remover   2.1.3 in my widget and replace by v1.11.0. 

How can i do!
Thanks!

**Comment by creocoder** [comment]
You need this: http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#customizing-asset-bundles
