### ISSUE TITLE
Create table if not exist

### ISSUE THREAD

**Issue by CyanoFresh** [yiisoft/yii2#7722]
Hello. How I can do 
```
CREATE TABLE IF NOT EXISTS `table`
```
in migrations?

**Comment by MattDalm** [comment]
There might be a better way but you can use the execute function in migration
for example
    	$this->execute('CREATE TABLE IF NOT EXISTS `table`...');

**Comment by cebe** [comment]
this is not possible and we do not have plans to implement it, you can do a check as described here: https://github.com/yiisoft/yii2/issues/2055#issuecomment-32708263
