### ISSUE TITLE
how can i get the asset files by javascript

### ISSUE THREAD

**Issue by yxdj** [yiisoft/yii2#7723]
I have an asset,frontend/myasset/*:
----------------------------

```
TestAsset.php
js/
    test.js
css/
    test.css
image/
    a.jpg
    b.jpg
    ...
other/
```

TestAsset.php
-------------
```php
namespace frontend\myasset;

use yii\web\AssetBundle;

class TestAsset extends AssetBundle
{
    public $sourcePath = '@frontend/myasset';
    public $css = [
		'css/test.css',
	];
	public $js = [
        'js/test.js',
    ];	
	
	
    public $depends = [
		//'frontend\assets\Test2Asset',
    ];
}

```

How can i get the images path by javascript.
css relative path is css file--that's ok.
but js relative path is index.php,

i know:
```php
$test= \frontend\myasset\TestAsset::register($this);
print_r($test);

//return:
//[basePath] => G:\WWW\ME\yuan37.com\frontend\web\assets\d084f866
//[baseUrl] => /assets/d084f866
```

I can set baseUrl in javascript:
```php
$this->registerJs('window.asset_myasset="'.$test->baseUrl.'"',static::POS_HEAD);
```
then,I can get base url like:
```javascript
var url = window.asset_myasset+'/image/a.jpg';
```

The bad,
1.Often do it, redundant.

2.if the assets have depends,I can't get more message about depends.

I want yii do it auto when the assets be register.

I can get it in javascript like this: 

```javascript
var url = yii.asset.myasset.webpath;
```

thanks!
--------

**Comment by klimov-paul** [comment]
This is uncommon practice. Also ability to get asset bundle base URL already present.
Extra JS code will be redundant at other cases.
