### ISSUE TITLE
A way to seed database is required

### ISSUE THREAD

**Issue by dhampik** [yiisoft/yii2#7726]
Hello! I see the issue #2069.
The thing is what described there is not seeding and for sure it's better to do with migrations.
What seeding is - it is filling database with fake data. This can be done for demonstration, for example.
And this mechanism is needed. It's important to understand what seeding is, because it's often mixed up.

Take a look at how rails works: it has a command for applying migrations `rake db:migrate` and a command for applying seed data `rake db:seed`. I think we need something similar here.

**Comment by samdark** [comment]
We have a way to do it using faker: https://github.com/yiisoft/yii2/tree/master/extensions/faker#faker-extension-for-yii-2

**Comment by SensitiveLab** [comment]
Fake is a way to seed database.
But is there a mean  and a dedicated place to do this in Yii2 ?
I search ... but seems no .

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-faker/blob/master/docs/guide/README.md

**Comment by samdark** [comment]
What do you mean by "mean and a dedicated"?

**Comment by SensitiveLab** [comment]
I found information in your link.
My wonder was to separate processing of testing and processing of seeding.
And reading test chapter led me to misundertsand. I thought that in fixture was only possible when fetching tests.
And it seems that I could call it in a separate way fixture/generate users

so everything was ok
