### ISSUE TITLE
Truncate method

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2#7727]
Hi - 

Using the trucate method from StringHelper and maintaining html gives wrong results in following case
For example 
StringHelper::truncate($post['content'], 500, "", false, true);

If my $post['content'] end up in a middle of a list 
(<ul><li></li><li></li></ul>) 

at character 500 then it will remove the content of the list but keep the bullet points which will be displayed empty.

--Matt

**Comment by klimov-paul** [comment]
Use `truncateHtml()` instead.

**Comment by MattDalm** [comment]
Hi Paul - 

The method truncateHtml is protected which is why I am using truncate which has following signature:

string truncate( $string, $length, $suffix = '...', $encoding = null, $asHtml = false )

In my example above I have set the last parameter to True so checking the code I am actually using the truncateHtml one:

 public static function truncate($string, $length, $suffix = '...', $encoding = null, $asHtml = false)
{
if ($asHtml) {
return self::truncateHtml($string, $length, $suffix, $encoding ?: Yii::$app->charset);
}

I do think there is an error in the code somehwere. 
Let me know if you need more details.

Thank you

--Matt

**Comment by klimov-paul** [comment]
Provide exact HTML code, which produces unexpected result.

**Comment by MattDalm** [comment]
So 
Controller:

```php
  public function actionTest(){
    $original = '<p>This is a test</p><ul><li>bullet1</li><li>bullet2</li><li>bullet3</li><li>bullet4</li></ul><p><br></p>';
    $summary = StringHelper::truncate($original, 22, "...", false, true);
   return $this->render('test', ['original' => $original, 'summary' => $summary]);
}
```

View (test.php):

```html
<style>
	li {
		list-style-type: circle;
	}
</style>


<div class="container">
	<div class="row post">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<?=$original?>
		</div>
	</div>
	<div class="row post">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<?=$summary?>
		</div>
	</div>
</div>
```

Resulting HTML:

```html
<div class="container">
	<div class="row post">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<p>This is a test</p><ul><li>bullet1</li><li>bullet2</li><li>bullet3</li><li>bullet4</li></ul><p><br></p>		</div>
	</div>
	<div class="row post">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<p>This is a test </p><ul><li>bullet1 </li><li></li><li></li><li></li></ul>...		</div>
	</div>

</div>
```

As you can see in the results empty ```<li></li>``` are maintained which causes the issues with empty bullets being displayed.

Hope this help.

thx

--Matt

**Comment by Alex-Code** [comment]
You could hide the empty bullets
```
<style>
li:empty {
  display: none;
}
</style>
```

**Comment by mahowlett** [comment]
I would expect this behaviour, the function doesn't imply that it will remove empty tags after the truncated content tag to me, so I would expect this to pass.

```php
$this->assertEquals('<p>This is a <span>test</span><span>s</span><span></span></p>', StringHelper::truncate('<p>This is a <span>test</span><span>sentance</span><span>with extra tags</span></p>', 16, null, null, true));
```

Which it does, whereas I think you are saying you would expect this test to pass

```php
$this->assertEquals('<p>This is a <span>test</span><span>se</span></p>', StringHelper::truncate('<p>This is a <span>test</span><span>sentance</span><span>with extra tags</span></p>', 16, null, null, true));
```
There does seem to be an issue regardless of that though, additional spaces seem to be being inserted and counted toward the string position to truncate to. The above test actually returns

```html
<p>This is a  <span>test </span><span>  </span><span></span></p>
```
Notice the space added after the word 'test' and also another before the word 'sentence' which has been entirely truncated.

**Comment by mahowlett** [comment]
I've also noticed there seems to be a problem with the suffix, I would expect it to append the suffix on the non html content that has just been concatenated not on the end of the content as a whole.

so 

```php
$this->assertEquals('<p>This is a test<span>se...</span></p>', StringHelper::truncate('<p>This is a test<span>sentance</span></p>', 16, '...', null, true));
```

Should pass but it returns

```html
<p>This is a test <span>s </span></p>...
```

Again the additional space but also the ellipsis is on the end.

**Comment by mahowlett** [comment]
OK I have a fix for the spaces issue, truncateHtml in the string helper seems to be adding spaces for no apparent reason, but fixing that, also forced me to fix the unit tests for it as they allow for the additional spaces. So I'll wait to see if the issue is confirmed before making a pull request.

current unit test

```php
$this->assertEquals('<span>This is a test </span>...', StringHelper::truncate('<span>This is a test sentance</span>', 14, '...', null, true));
        $this->assertEquals('<span><img src="image.png" />This is a test </span>...', StringHelper::truncate('<span><img src="image.png" />This is a test sentance</span>', 14, '...', null, true));
```

'fixed' unit test

```php
$this->assertEquals('<span>This is a test</span>...', StringHelper::truncate('<span>This is a test sentance</span>', 14, '...', null, true));
        $this->assertEquals('<span><img src="image.png" />This is a test</span>...', StringHelper::truncate('<span><img src="image.png" />This is a test sentance</span>', 14, '...', null, true));
```
