### ISSUE TITLE
Generating csrf meta tags

### ISSUE THREAD

**Issue by v0lume** [yiisoft/yii2#7728]
Hello!
If we call \yii\helpers\Html::csrfMetaTags() two times, 4 meta-tags will be rendered (csrf-param and csrf-token for each call).

Maybe it's better to register csrf-param csrf-token in Html::csrfMetaTags() through Yii::$app->view->registerMetaTag()?

 For prevent duplicate rendering, we can pass as a second param unique id of meta-tag (for example "csrf-param" and "csrf-token", like it's names)

Thanks!

**Comment by zelenin** [comment]
:thumbsup:

**Comment by samdark** [comment]
OK but why do you have it called two times?

**Comment by v0lume** [comment]
@samdark 
Difficult question :)
For example, if somebody don't seen calling `csrfMetaTags()` in standard layout

The main reason why i created issue is that there is `registerMetaTag()` method in `View` for meta tags (with prevent duplicating), but in helper it's generated through own method (without prevent duplicating).

And the minor reason - i'm creating extension for working with meta tags. 
https://github.com/v0lume/yii2-meta-tags

I create method that register all necessary meta tags in one call (also with csrf meta tags). But i can't auto identify whether to generate csrf tags or not (now it's setting manually in component config).
I think we can simplify life for developers, am i right? ;)

**Comment by samdark** [comment]
Well, it's OK to me to reuse View in this case if it won't break backwards compatibility.

**Comment by AnikanovD** [comment]
A few calling `csrfMetaTags()` is not normal.
May be issue is not actual.

**Comment by samdark** [comment]
Thought about it more and I agree with @AnikanovD.
