### ISSUE TITLE
Gridview and pjax, load of the page

### ISSUE THREAD

**Issue by contrerasjose** [yiisoft/yii2#7729]
I'm new yii, I'm learning and I love it. My English is not very good, I'm from Chile my name is Joseph, the problem I have is I want to use Pjax, but just when loading the page should load the data with ajax this is my code:

	<?php Pjax::begin();?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
		'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'code',
            'name',
            'population',
            'status',
            'details',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
	<?php \yii\widgets\Pjax::end(); ?>
</div>

thx.

**Comment by klevron** [comment]
Did you try to modify timeout ? 
```php
<?php Pjax::begin(['timeout'=>2000]);?>
```

**Comment by cebe** [comment]
what is the issue? sounds more like a question to me, please use the forum for questions, github is for issue tracking.

**Comment by contrerasjose** [comment]
is solved with the timeout, thank you very much
