### ISSUE TITLE
allow omitting surrounding div in \yii\widgets\ListView

### ISSUE THREAD

**Issue by KPEMATOP** [yiisoft/yii2#7730]
If you attempt to disable the output of the surrounding block by setting the properties of 'options' => ['tag' => false], to receive  \<id = "w0"\> (here is my html) </>, problem was solved by redefining the method yii \ widgets \ BaseListView
/ **
     * Runs the widget.
     * /
    public function run ()
    {
        if ($ this-> showOnEmpty || $ this-> dataProvider-> getCount ()> 0) {
            $ Content = preg_replace_callback ("/ {\\ w +} /", function ($ matches) {
                $ Content = $ this-> renderSection ($ matches [0]);

                return $ content === false? $ Matches [0]: $ content;
            }, $ This-> layout);
        } Else {
            $ Content = $ this-> renderEmpty ();
        }
        $ Tag = ArrayHelper :: remove ($ this-> options, 'tag', 'div');
        echo Html :: tag ($ tag, $ content, $ this-> options); // here wrote a check value tag if false, it is required to return the content
    }

**Comment by cebe** [comment]
omitting tag is currently not supported.

**Comment by pana1990** [comment]
@cebe @KPEMATOP  this issue is fix in #10764
