### ISSUE TITLE
screen.css increase width

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#7731]
hi all. is there simply method to increase screen.css width of working area? or may be set percentage instead of pixels. may be there is already fixed file screen.css?

**Comment by gephaest** [comment]
Define your own CSS file and rewrite rules there.

**Comment by nicdnepr** [comment]
yes, but it's a bit hard for me. i guess any ready solution must be?

**Comment by samdark** [comment]
Please use forums for questions.
