### ISSUE TITLE
yii2-composer error when using an array for psr-4 autoloading

### ISSUE THREAD

**Issue by wichura** [yiisoft/yii2#7735]
Hi guys,

We've run into a problem with composer when trying to use an array of strings for namespace location, as per https://getcomposer.org/doc/04-schema.md#autoload. We'd like to use this mechanics to overwrite models defined in a yii2-extension inside of an app application. The relevant section of our composer.json looks like this: 

```json

 "autoload": {
        "psr-4": {
            "matacms\\post\\": ["frontend/models/overwrites/post/", ""]
        }
    }

```

and the error when doing composer update: 

```                                                      
  [ErrorException]                                        
  substr() expects parameter 1 to be string, array given  
                                                          
Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Util/Filesystem.php:392
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 substr() at phar:///usr/local/bin/composer/src/Composer/Util/Filesystem.php:392
 Composer\Util\Filesystem->isAbsolutePath() at /Users/wichura/Sites/MATA-app/vendor/yiisoft/yii2-composer/Installer.php:125
 yii\composer\Installer->generateDefaultAlias() at /Users/wichura/Sites/MATA-app/vendor/yiisoft/yii2-composer/Installer.php:85
 yii\composer\Installer->addPackage() at /Users/wichura/Sites/MATA-app/vendor/yiisoft/yii2-composer/Installer.php:56
 yii\composer\Installer->update() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:172
 Composer\Installer\InstallationManager->update() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:578
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:225
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:84
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25
```

Could you please advise if this is a bug? I feel yii2-composer should be a transparent layer on top of composer, but perhaps the design is different? 

Thanks,
Marcin

**Comment by cebe** [comment]
The problem with this is that the yii autoloader is based on path aliases and does not support one alias to point to multiple paths. It should however just ignore this case then and leave it up to the composer autoloader.

**Comment by cebe** [comment]
Should be fixed by fecdf1a. @wichura can you try installing it by using `"yiisoft/yii2-composer": "*@dev",` in your composer.json?

**Comment by wichura** [comment]
Hi @cebe,

Thanks for the prompt fix, and sorry for the radio silence in the past days - I was away from my computer. 

I've seen fecdf1a5f77155a9aa4290c01a358053a545b9d6 and it seems that you simply ignore multiple search paths, which does not work for our particular application. 

I made some headway with refactoring yii\composer\Installer and yii\base\Application to work with arrays, albeit I can see it is a limitation of Yii::setAlias() when it comes to setting the same key. One might argue though that setting one alias (be it the first or the last one) is better than ignoring them altogether? 

Also, funnily enough, if I comment out alias part in /vendor/yiisoft/extensions.php, I achieve the required functionality, i.e. I can overwrite individual files without modifying them in vendor folder. It's possible as autoloading relies on contents of autoload_psr4.php which supports multiple paths, as per the document I mentioned earlier. 

What are your thoughts around this issue? Would it help if we provide you with a sample application you could have a look at? 

Thanks again for troubleshooting this for us, much appreciated
Marcin

**Comment by wichura** [comment]
On reflection, Yii::setAlias() used in the way I suggested would introduce non-deterministic behavior into Yii -- please ignore my comment above. 

Your fix works well, we'll try to refactor our application to play along. 

Regards,
Marcin

**Comment by cebe** [comment]
thanks for checking.
