### ISSUE TITLE
Docs for bower

### ISSUE THREAD

**Issue by nsanden** [yiisoft/yii2#7736]
I would really like to know the best way to add a bower package such as https://github.com/HubSpot/shepherd to my project. I read the documentation here: http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#bower-and-npm-assets but it doesn't seem complete, or i'm missing something. Part 1 is what's confusing me. Part 2 is simple enough.

For part 1, bower packages are not composer packages, so how/why would I add a "bower-asset/sheperd" to my composer.json? If I do, composer just tells me it can't find the package.

**Comment by Sammaye** [comment]
Hmm it could probably do with some actual pointers:

> Modify the composer.json file of your application or extension and list the package in the require entry. You should use bower-asset/PackageName (for Bower packages) or npm-asset/PackageName (for NPM packages) to refer to the library.

Maybe just adding an example like:

After you have added a bower or npm package to your composer the required section will look something like:

	"require": {
		"bower-asset/PackageName": "*",
	},

**Comment by Sammaye** [comment]
> If I do, composer just tells me it can't find the package.


What is the exact message? It seems you understand what should be done

**Comment by samdark** [comment]
Do you have asset plugin installed globally?

**Comment by nsanden** [comment]
@Sammaye
I added:
```
"bower-asset/shepherd": "*"
```
to composer.json requre and I get:
...
  Problem 1
    - The requested package bower-asset/shepherd could not be found in any version, there may be a typo in the package name.
...

i'm just guessing the package name is "sheperd" going off https://github.com/HubSpot/shepherd/blob/master/bower.json

@samdark - Yes I do

**Comment by Sammaye** [comment]
Hang on let me try

**Comment by Sammaye** [comment]
Fascinating doesn't work for me either, let's try their main

**Comment by Sammaye** [comment]
Nope, that doesn't work either

**Comment by Sammaye** [comment]
Sorry my bad, spelling mistake, shepherd works, I spelt sheperd lol

**Comment by Sammaye** [comment]
Try running 

    php ./composer.phar require bower-asset/shepherd

**Comment by nsanden** [comment]
Strangely, both:
```"bower-asset/shepherd.js": "*"```
and:
```composer require bower-asset/shepherd.js```
are working for me but these do not:
```"bower-asset/shepherd": "*"```
```composer require bower-asset/shepherd```

Oh well, glad its working at least. thanks for the help @Sammaye !

Not sure if docs should explain this better or not, #1 makes sense to me now that I understand the composer asset plugin is handling the bower-asset/shepherd.js - its just a little strange at first

**Comment by Sammaye** [comment]
I still think this may be a bug but not with Yii2, I think bower asset manager is not identifying the latest version correctly in some messed up way from the composer file.

Might be worth opening an issue here: https://github.com/francoispluchino/composer-asset-plugin you never know
