### ISSUE TITLE
Execute doesn't return right result

### ISSUE THREAD

**Issue by johnluxor** [yiisoft/yii2#7738]
I execute sql query

```php
function afterSave($insert, $changedAttributes) {
    parent::afterSave($insert, $changedAttributes);

    Yii::$app->db->createCommand("UPDATE table SET points=1 WHERE id=:id")->bindValue(':id', $this->id)->execute()

    return true;
} 
```

The query was executed and data was changed in db, but it's returned 0

Why?

**Comment by samdark** [comment]
You mean `execute()`? Are you sure data was changed? Which database was used? Can you provide data and schema to reproduce the issue?

**Comment by johnluxor** [comment]
Yes, I mean ```execute()```
Yes, I'm sure that data was changed. Database is MySQL 5.6.17 and 5.5.38

The structure is simple
```
'id' => 'pk'
'user_id' => Schema::TYPE_SMALLINT,
'image' => Schema::TYPE_STRING
'is_approved' => Schema::TYPE_SMALLINT
'points'=> Schema::TYPE_SMALLINT
```

**Comment by johnluxor** [comment]
Today I tried to update a lot of rows in cycle in other table 

```
if (($handle = fopen(\Yii::getAlias('@app') . '/csv/activity.csv', "r")) !== false) {
            while (($data = fgetcsv($handle, 1000, ",")) !== false) {
                if (\Yii::$app->db->createCommand("UPDATE users SET is_unsubscribe=1 WHERE email=:email LIMIT 1")->bindValues([':email' => $data[1]])->execute()) {
                    echo $this->ansiFormat("Email: " . $data[1] . " was unsubscribed \n", Console::FG_GREEN);
                } else {
                    echo $this->ansiFormat("Email: " . $data[1] . " was not unsubscribed \n", Console::FG_RED);
                }
            }
            fclose($handle);
        }
```

and some rows were updated but 
```
\Yii::$app->db->createCommand("UPDATE users SET is_unsubscribe=1 WHERE email=:email LIMIT 1")->bindValues([':email' => $data[1]])->execute();
```
returned 0

**Comment by cebe** [comment]
note that the return value is 0 if data was the same as before, so it will only be 1 if data really changed. In any case this is unlikely an issue with yii because yii will return the value that is returned by PDO.

you check in the if condition seems wrong, you will say "was unsubscribed" if number of updated rows is 0.

**Comment by johnluxor** [comment]
But I checked that -  data in db table was changed. I changed data manually and run script again. And it's return 0, but data was changed

**Comment by qiangxue** [comment]
Try manually run the update SQL and see how many rows are affected.

**Comment by lynicidn** [comment]
try $model->refresh or change $this->id to $this->primaryKey

**Comment by klimov-paul** [comment]
Closed, unless explicit way to reproduce the problem appears.
