### ISSUE TITLE
Timestamp behaviour works incorrectly

### ISSUE THREAD

**Issue by dhiman252** [yiisoft/yii2#7739]
I have implemented the Timestamp Behavior as following

```php
public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created','updated'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated'],
                ],
                #'createdAtAttribute' => 'created',
                #'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
```

when i create a new record it automatically fills the values but when i update the record it again fills both the values instead of filling out only one value i.e. updated attribute only

**Comment by pana1990** [comment]
@dhiman252 

what do you use dbms?

please, can you show schema table?

**Comment by dhiman252** [comment]
this is the table structure i am using

CREATE TABLE `quiz` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `created` TIMESTAMP,
 `updated` TIMESTAMP,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

**Comment by pana1990** [comment]
i had this error in mysql, i fixed create created_at and updated_at how null column.

For more detailts : 
http://stackoverflow.com/questions/18962757/when-is-a-timestamp-auto-updated

**Comment by RedDog-BY** [comment]
@dhiman252 this is the mysql feature. You didn't specify a default value for the `created` column, that's why it  has the current timestamp for its default value and is automatically updated to the current timestamp.
For more detailts : 
http://dev.mysql.com/doc/refman/5.5/en/timestamp-initialization.html

**Comment by pana1990** [comment]
@RedDog-BY :+1:

**Comment by samdark** [comment]
@dhiman252 if issue is solved, please close it. If not, provide more details.

**Comment by dhiman252** [comment]
If i want to use this Timestamp Behavior provided by YII the what should be the datatype of the column ?

**Comment by samdark** [comment]
I guess it should be `NOT NULL`.
