### ISSUE TITLE
ActiveForm fieldConfig options tag=>false will render class attribute without any tag

### ISSUE THREAD

**Issue by alexjose** [yiisoft/yii2#7741]
I was trying to get rid of the div around the input field. I set the tag option for fieldConfig to false to disable the div. But the result was the default class was render without any tag. 

Given below is the code I used.
```php
    <?php
    $form = ActiveForm::begin([
                'fieldConfig' => [
                    'options' => [
                        'tag' => false,
                    ],
                ],
    ]);
    ?>

    <?= $form->field($movie, 'name') ?>

    <?php ActiveForm::end(); ?>
```

And the rendered form was 

```html
<form id="w0" action="###" method="post">
<input type="hidden" name="_csrf" value="#####">
   < class="field-movie-name required">
<label class="control-label" for="movie-name">Name</label>
<input type="text" id="movie-name" class="form-control" name="Movie[name]" value="">

<div class="help-block"></div>
</>
    </form>
```

Note the **< class="field-movie-name required">** and the **</>** just above the form closing tag. I think this is a bug and when the tag is set to false, the input field should be rendered without and wrapping tags.

**Comment by SDKiller** [comment]
@alexjose 

I'm afraid you'll have to override `\yii\widgets\ActiveField` - it's `begin()` and `end()` methods do not suppose 'getting rid' of tag.

ActiveForm `js` also relies on tag - it sets 'error' and 'success' css classes for container, not for field itself.

**Comment by pana1990** [comment]
this issue is resolve here https://github.com/yiisoft/yii2/issues/10764

@SilverFire how can we validate on client when tag is false?

**Comment by SilverFire** [comment]
Actually there is no way to do it. Feature to shoot yourself in the foot :)

**Comment by pana1990** [comment]
@SilverFire ;) thanks you very much
