### ISSUE TITLE
model method unsetAttributes() like Yii1

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#7742]
how model method unsetAttributes() note exist?!!

**Comment by samdark** [comment]
What's your use case for it?

**Comment by EngRajabi** [comment]
In many projects, there are some forms that are needed to get empty after submitting the form (to load the same form page again). 
There was a function in Yii 1 ( unsetAttributes() ) which could do this task, but we have to do it manually in Yii 2.
example Yii 2 : $model->setAttributes(['name'=>'','family'=>'','password'=>'','email'=>'','birthdate'=>'','phone_number'=>'']);
example Yii1 : $model->unsetAttributes();

**Comment by cebe** [comment]
why would you need it? in yii2 a newly created model instance has empty attributes itself. In yii1 we loaded default values by default.

**Comment by slinstj** [comment]
Could be there something related to the model (runtime added) that would be lost using a `new` model (maybe runtime added behaviors, events, counters, etc)? If so, I think we should have an `unsetAttributes()`. *Although I just can`t remember anything now, not even a single real case*.

**Comment by samdark** [comment]
Closing it until valid use case provided.

**Comment by EngRajabi** [comment]
after submite form (ajax or submit) need not direct but clear attributes but Yii2 work hard

**Comment by lubosdz** [comment]
+1 for this method.

Use case:
* I have a singleton form held in DI container (means constructor loads once per request from session persistent data into form). The form consists of cca 5 sub-steps and collects various data from a user.
* Once all data entered we will send data somewhere else (e.g. webservice), but still we must keep the object, this time with empty attributes saved into session.
* I could do workaround (write my own function with foreach ... ) but it comes clumsy to me.

UnsetAttributes that existed in Yii1 would be ideal in this case.

**Comment by samdark** [comment]
@EngRajabi what prevents you from doing it as @cebe described?

@lubosdz if you need to keep what was submitted for further analysis you can't really discard attributes and overwrite data. If you don't need it, why not to remove data instead?

**Comment by lubosdz** [comment]
@samdark  Where's no will, there's no way :-)

**Comment by lynicidn** [comment]
:+1: 
if i have rewrite attributes
$model = new my\Model(['attributes' => ['a' => 1, 'b' =>2]]);
if i set new attributes ['a' => 3] it expect ['a' =>3, 'b' => 2] me need set attribute `b` as empty.
i solve it via `loadDefaultValues(false)`
