### ISSUE TITLE
Cache RBAC assignments

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#7743]
Save `SELECT * FROM auth_assignment WHERE user_id='...'` results in `User` component property to avoid duplicate DB queries on one page.
[See comment here](https://github.com/yiisoft/yii2/issues/3168#issuecomment-76709786).

**Comment by RomeroMsk** [comment]
Any thoughts?

**Comment by williamyiu** [comment]
I ran into the same issue as well.

**Comment by juban** [comment]
:+1: 
I also think this is a major performance issue in some scenarios.
I'm maybe off topic here (sorry), but here is a very simple workaround :

```php
class DbManagerEx extends DbManager
{
    private $_assignments = [];
    
    public function getAssignments($userId)
    {
        // Avoid multiple queries per request
        if(!isset($this->_assignments[$userId]))
            $this->_assignments[$userId] = parent::getAssignments($userId);
        return $this->_assignments[$userId];
    }

}
```

**Comment by acuom** [comment]
@samdark did this ever get done? 

as I am getting hundreds of 

`SELECT `b`.* FROM `auth_assignment` `a`, `auth_item` `b` WHERE ((`a`.`item_name`=`b`.`name`) AND (`a`.`user_id`='91')) AND (`b`.`type`=1)`

On some pages 👎

**Comment by samdark** [comment]
Not yet. Scheduled for next release though.

**Comment by acuom** [comment]
@samdark ahh ok, any tips how the above problem could be solved in the meantime?

**Comment by samdark** [comment]
Try using file storage instead.
