### ISSUE TITLE
Specify correct minimum framework version for extensions on release

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#7747]
https://github.com/yiisoft/yii2/issues/7734#issuecomment-81306021

**Comment by samdark** [comment]
We should not bump version too much though. If 2.0.0 is OK for extension, it should require `~2.0.0`.

**Comment by cebe** [comment]
sure

**Comment by cebe** [comment]
I have checked all the extensions, at least those who have unit tests. they are passing on all yii versions so there is no need to adjust requirements right now. In the future we should think about this when writing new featues.
