### ISSUE TITLE
Normal error message in \yii\helpers\BaseFileHelper::createDirectory

### ISSUE THREAD

**Issue by mougrim** [yiisoft/yii2#7748]
If function mkdir make warning in \yii\helpers\BaseFileHelper::createDirectory, I see next warning:
```
PHP Warning – yii\base\ErrorException
mkdir(): Permission denied
```

But in warning no info about directory path.
It introduces confusion.
Please, fix it, this fix make development easier.

Enviroment:
Ubuntu 14.04
php 5.5.9
yii 2.0.3

**Comment by cebe** [comment]
duplicate of #6442
