### ISSUE TITLE
How to filter data from kartik gridview using select2/ depdrop items, they're outside of the gridview

### ISSUE THREAD

**Issue by fwroman** [yiisoft/yii2#7751]
Hi everyone, I need to filter data from a kartik gridview when I choose one item of a select2 and a depdrop respectively but not inside the gridview as a column, select2 and depdrop are outside of it...

Could someone show me a way to do this?

**Comment by samdark** [comment]
Please use forums for questions. Espectially if questions aren't about official framework but about extensions.

**Comment by fwroman** [comment]
Ok I'm sorry
