### ISSUE TITLE
Yii2 active record + sphinx = count error

### ISSUE THREAD

**Issue by vov4ik08** [yiisoft/yii2#7752]
Hello. I try to use this code:
```
 $model = new RtContentModel();
$query=$model->find()
            ->match(new Expression(':match',['match' => \Yii::$app->sphinx->escapeMatchValue($params['query'])]));
$provider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'pageSize' => 10,
                ]
            ]);
```

Display this error:
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 index rt_content: invalid schema: Count(*) or @count is queried, but not available in the schema
The SQL being executed was: SELECT COUNT(*) FROM `rt_content` WHERE MATCH(:'asf as fas')' 

in /var/www/car/vendor/yiisoft/yii2-sphinx/Schema.php:527

Please help me. Thank you

**Comment by coderlight** [comment]
jhj

**Comment by cui-liang** [comment]
I encountered the same problem, I have upgraded sphinx to version 2.2.8 resolved the problem.

**Comment by vov4ik08** [comment]
i have this problem only real time indexes

**Comment by cui-liang** [comment]
What is your current sphinx version? I used the sphinx 2.0 have same problem with you.

**Comment by vov4ik08** [comment]
Sphinx 2.2.8-id64-release (rel22-r4942)

**Comment by klimov-paul** [comment]
Unable to reproduce
