### ISSUE TITLE
how to save actual value of dropdown

### ISSUE THREAD

**Issue by rahulsinh** [yiisoft/yii2#7753]
<?= $form->field($model, 'availability')->dropDownList(
             ['prompt' => 'Select Availability','YES','NO'
             ]
             ) ?>

Hii all,
I want to save dropdown value yes and no but database save '0' or '1' how to save selected value using dropdown anybody help me.

**Comment by cebe** [comment]
you are passing wrong parameters, check the api doc: http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#dropDownList%28%29-detail

**Comment by rahulsinh** [comment]
@cebe i can not understand

**Comment by cebe** [comment]
@rahulsinh you are using it wrong, please read the documentation carefully. If there are further questions, please use the forum, github is for bug tracking.

**Comment by rahulsinh** [comment]
can you tell me  
<?= $form->field($model, 'duration_id')->dropDownList(
            ArrayHelper ::map(Duration::find()->all(),'duration_id','type'),
             ['prompt' => 'Select Duration']
             ) ?>
how to save type of duration 2week 3 week instead of duration id dropdown show 2week 3 week when i have save the form value then it stored duration id.
