### ISSUE TITLE
ActiveRecord where LIKE in array

### ISSUE THREAD

**Issue by anders-akero** [yiisoft/yii2#7756]
I have not found a good way to create a query  as WHERE `column` LIKE '%term1%' OR `column` LIKE '%term2%' Maybe I have missed something or maybe it is not supported in the way I would like it to be.

I propose a change in how ActiveRecord is building up mysql queries with LIKE when passed an array.
My suggestion is that LIKE works similar to IN when passed an array.
An small example:
```
    $q = ['google','yii'];
    Server::find()->select('id')->where(['LIKE', 'domain', $q])->all();
```
The code above would result in a query like:
```
    SELECT `id` FROM `servers` WHERE `domain` LIKE '%google%' AND `domain` LIKE '%yii%'
```
My sugestion is that it instead would return a query like:
```
    SELECT `id` FROM `servers` WHERE `domain` LIKE '%google%' OR `domain` LIKE '%yii%'
```
Separating the WHERE LIKE with OR instead of AND.
I have been thinking about it for a while and I can not see any scenario when anyone would like to search with AND on same column?

What do everyone else think about this suggestion?

**Comment by Alex-Code** [comment]
Think this is already covered, see docs here
http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#where
`or like: similar to the like operator except that OR is used to concatenate the LIKE predicates when operand 2 is an array.`

**Comment by anders-akero** [comment]
Thanks. I don't know how I missed that. This is exactly what I was looking for.
My suggestion remain. That we set this as a default behaviour.

**Comment by anders-akero** [comment]
I realize now that there is scenarios when you do would want AND so I will close this. Thanks for quick response.
