### ISSUE TITLE
unzip yii-basic-app-2.0.3.tgz error in Windows 8.1

### ISSUE THREAD

**Issue by donhuvy** [yiisoft/yii2#7762]
I try many solutions, but can't unzip successful, really.

Use WinRAR:
![capture](https://cloud.githubusercontent.com/assets/1328316/6690292/61363aba-ccf2-11e4-894a-6ffb10165b56.PNG)

or 7zip:
![2](https://cloud.githubusercontent.com/assets/1328316/6690333/961a3038-ccf2-11e4-9232-123acc4c52c3.PNG)

**Comment by Alex-Code** [comment]
I can't reproduce this on Windows 8.1 (using 7zip)
If you have another drive could you try extracting on that?

**Comment by samdark** [comment]
Re-dowmnload. Archives are OK.

**Comment by donhuvy** [comment]
Please check again. In Windows, I cann't unzip. Please use zip format, don't use *.tgz . I also try use composer, but still error.

![capture](https://cloud.githubusercontent.com/assets/1328316/6706939/bfbbd1f6-cd94-11e4-84a7-6b23a15d7a15.PNG)

**Comment by cebe** [comment]
from the error message it looks like you are not allowed to create symlinks because of missing privileges, make sure you have necessary permissions to write to the directory you are trying to unzip to.

**Comment by donhuvy** [comment]
I have been checked the folder, full permission. But error.
![g](https://cloud.githubusercontent.com/assets/1328316/6708229/f03b3bee-cda0-11e4-9692-4955c1d05bc0.PNG)

![g2](https://cloud.githubusercontent.com/assets/1328316/6708233/f7c2618a-cda0-11e4-92a2-285c1cba45b0.PNG)

**Comment by samdark** [comment]
Do you use FAT or NTFS as your file system? Symlinks aren't supported in FAT (which is quite outdated) and not used by default.

**Comment by donhuvy** [comment]
I use NTFS.
