### ISSUE TITLE
ArrayHelper::toArray() not passing $recursive to Arrayable::toArray()

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#7764]
If you pass an Arrayable object into yii\helpers\ArrayHelper::toArray(), the $recursive argument should be passed on to the object’s toArray() method, but it’s not.

Example:

```php
class Foo extends \yii\base\Model
{
    public $date;
}

$foo = new Foo();
$foo->date = new DateTime();

$fooArray = \yii\helpers\ArrayHelper::toArray($foo, [], false);
\yii\helpers\VarDumper::dump($fooArray, 10, true);
```

Expected result (and what `$foo->toArray([], [], false)` will give you):

```
[
    'date' => DateTime( ... )
]
```

Actual result:

```
[
    'date' => [
        'date' => '2015-03-17 10:45:58.000000'
        'timezone_type' => 3
        'timezone' => 'America/Los_Angeles'
    ]
]
```

**Comment by lynicidn** [comment]
it's expected behavior - toArray prepare data `to array` - why u expect 'data' => $object?
recursice work with inner objects

**Comment by brandonkelly** [comment]
@lynicidn Are you saying you don’t think that this should be true for Arrayable objects?

```php
$object->toArray([], [], $recursive) === ArrayHelper::toArray($object, [], $recursive)
```

(That test is true when $recursive = true, but not when $recursive = false.)

Maybe I’m missing something, but considering ArrayHelper::toArray() actually calls the Arrayable object’s toArray() method internally (if it is one), and considering that they both have “$recursive” arguments, expected behavior for me was that they would both behave the same when $recursive = false.

Currently I’m doing the following workaround (until my patch makes it in):

```php
if ($object instanceof Arrayable) {
    $arr = $object->toArray([], [], false);
} else {
    $arr = ArrayHelper::toArray($object, [], false);
}
```

I certainly hope I can simplify that to this line when Yii 2.0.4 comes out:

```php
$arr = ArrayHelper::toArray($object, [], false);
```

**Comment by lynicidn** [comment]
look herehttps://github.com/brandonkelly/yii2/blob/ef8925618f316d7324cd7898f006163550b8e2af/framework/helpers/BaseArrayHelper.php#L96

**Comment by lynicidn** [comment]
u have problem here?

**Comment by brandonkelly** [comment]
@lynicidn [As I said when you pointed out the same line in the commit comment](https://github.com/brandonkelly/yii2/commit/ef8925618f316d7324cd7898f006163550b8e2af#commitcomment-10283075), the problem is, by the time line 96 is executed, the damage described here has already been done:
https://github.com/yiisoft/yii2/blob/befd42f46ad324e003be30fa2e5cbfd760d05bad/framework/helpers/BaseArrayHelper.php#L87-L88

To clarify, because $recursive isn’t passed to the Arrayable object’s toArray() method, toArray() will end up recursively turning all nested items into arrays (such as nested DateTime properties, as in the example I gave above). So by the time line 96 is called, it doesn't matter if $recursive is false anymore - everything has already been recursively turned into an array at that point.

**Comment by lynicidn** [comment]
write fail test for bad situation

**Comment by lynicidn** [comment]
ur code break all, see here https://github.com/brandonkelly/yii2/blob/ef8925618f316d7324cd7898f006163550b8e2af/framework/helpers/BaseArrayHelper.php#L96

**Comment by lynicidn** [comment]
u test ur pr ?

**Comment by brandonkelly** [comment]
Yes

**Comment by lynicidn** [comment]
accept it not break, only current code also work correctly (i add new test)
```php

class Post4 extends Object
{
    public $id = 55;
    public $subObject;

    public function init()
    {
        $this->subObject = new Post3();
    }
}
```
```php
$object = new Post4();
        $this->assertEquals(get_object_vars($object), ArrayHelper::toArray($object, ['id' => 55], false));
        $this->assertEquals([
            'id' => 55,
            'subObject' => [
                'id' => 33,
                'subObject' => [
                    'id' => 123,
                    'content' => 'test',
                ],
            ],
        ], ArrayHelper::toArray($object));
```
and run it on master and patch-6:
```bash
lynicidn@debian:~/sites/bran$ git branch 
  master
* patch-6
lynicidn@debian:~/sites/bran$ phpunit tests/unit/framework/helpers/ArrayHelperTest.php 
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /home/lynicidn/sites/bran/phpunit.xml.dist

............................

Time: 77 ms, Memory: 4.75Mb

OK (28 tests, 78 assertions)
```
```bash
lynicidn@debian:~/sites/bran$ git branch 
  master
* origin/master
  patch-6
lynicidn@debian:~/sites/bran$ phpunit tests/unit/framework/helpers/ArrayHelperTest.php 
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /home/lynicidn/sites/bran/phpunit.xml.dist

............................

Time: 93 ms, Memory: 4.75Mb

OK (28 tests, 78 assertions)
```

**Comment by brandonkelly** [comment]
Post4 doesn't implement yii\base\Arrayable, so that’s not a valid test. And the $properties argument you're passing into ArrayHelper::toArray() in the first assertion isn’t even a [supported format](http://www.yiiframework.com/doc-2.0/yii-helpers-basearrayhelper.html#toArray()-detail).

Here:

```php
use yii\base\Object;
use yii\base\Arrayable;
use yii\base\ArrayableTrait;
use yii\helpers\ArrayHelper;

class Post3 extends Object
{
    // ...
}

class Post4 extends Object implements Arrayable
{
    use ArrayableTrait;

    public $id = 55;
    public $subObject;

    public function init()
    {
        $this->subObject = new Post3();
    }
}
```

```php
$object = new Post4();

$this->assertEquals(
    ['id' => 55, 'subObject' => $object->subObject],
    ArrayHelper::toArray($object, [], false)
);
```

**Comment by lynicidn** [comment]
write ur test where break current behavior for `toArray`

**Comment by brandonkelly** [comment]
Not sure I understand what you just said. Are you saying the test shows that the current ArrayHelper::toArray() behavior is broken? That’s the point. It will currently fail, and my pull request will fix it.

**Comment by lynicidn** [comment]
need add tests for Arrayable objects wich broken current behavior

**Comment by brandonkelly** [comment]
There’s nothing wrong with Arrayable/ArrayableTrait. The problem is that ArrayHelper::toArray() isn't telling Arrayable::toArray() whether or not it should be recursive.

**Comment by lynicidn** [comment]
it's current recursice, i posted link https://github.com/brandonkelly/yii2/blob/ef8925618f316d7324cd7898f006163550b8e2af/framework/helpers/BaseArrayHelper.php#L96

**Comment by brandonkelly** [comment]
You’ve posted that link 4 times now, but I keep saying that it's not the problem! Have you tried running my test? It clearly demonstrates that `$recursive = false` is **not** being respected, due to the `$object->toArray();` call on [line 88](https://github.com/yiisoft/yii2/blob/befd42f46ad324e003be30fa2e5cbfd760d05bad/framework/helpers/BaseArrayHelper.php#L88).

**Comment by lynicidn** [comment]
if recursive is false, why we need run toArray with `recursive= false`?

**Comment by brandonkelly** [comment]
Because Arrayable requires the toArray() to specify a $recursive argument, set to `true` by default (https://github.com/yiisoft/yii2/blob/master/framework/base/Arrayable.php#L89).

If ArrayHelper::toArray()’s $recursive value isn’t passed to Arrayable::toArray(), then Arrayable::toArray() will recursively turn the object into an array, regardless of what you told ArrayHelper::toArray() to do.

**Comment by lynicidn** [comment]
`ArrayHelper::toArray($model, [], false);`
why inner `toArray` we should run toArray($model, [], false) ?

**Comment by brandonkelly** [comment]
Because you told ArrayHelper::toArray() you don’t want it to convert the object to an array recursively. It doesn’t matter why - that’s up to the application logic to decide.

**Comment by brandonkelly** [comment]
Looks like this wasn’t fixed in Yii 2.0.4. Any word? Seems like a pretty straightforward bug to me. @qiangxue

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/7765

**Comment by brandonkelly** [comment]
:+1:
