### ISSUE TITLE
On line 554 of advanced/vendor/yiisoft/yii2/base/module.php preg_match is incorrect

### ISSUE THREAD

**Issue by sefy98** [yiisoft/yii2#7767]
On line 554 of advanced/vendor/yiisoft/yii2/base/module.php preg_match is set to:
if (!preg_match('%^[a-z][a-z0-9\\-_]*$%', $className)) {

This does not match camel cased controller classes, and will always return null.

**Comment by zelenin** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/structure-controllers.md#controller-class-naming-

**Comment by sefy98** [comment]
Do you happen to know the reasoning behind the -'s in url, but camel case in controller?
