### ISSUE TITLE
yii2 sphinx - Matching modes

### ISSUE THREAD

**Issue by vov4ik08** [yiisoft/yii2#7769]
Hello. How i can use Matching modes:
SPH_MATCH_ALL, matches all query words;
SPH_MATCH_ANY, matches any of the query words;
SPH_MATCH_PHRASE, matches query as a phrase, requiring perfect match;
and other? If in php use only php i use SetMatchMode(SPH_MATCH_EXTENDED)

**Comment by rmrevin** [comment]
I would add more functionality sorting [`setSortMode`](http://php.net/manual/ru/sphinxclient.setsortmode.php)
link to [`setMatchMode`](http://php.net/manual/ru/sphinxclient.setmatchmode.php)
and, in addition, I would like a method to [`setRankingMode`](http://php.net/manual/ru/sphinxclient.setrankingmode.php) (I know about the `options`)

**Comment by klimov-paul** [comment]
Read the official Sphinx docs about compoistion of the complex MATCH statement:
http://sphinxsearch.com/docs/current.html#extended-syntax
http://sphinxsearch.com/docs/current.html#boolean-syntax

**Comment by sowich** [comment]
The documentation states that you need to use *SPH_MATCH_EXTENDED*
> The following special operators and modifiers can be used when using the extended matching mode

As in that case, and indicate the mode?
