### ISSUE TITLE
Inconsistent fallback time formats

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#7770]
The fallback for 'short' uses 24 hour format, the rest use 12 hour format.
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFormatConverter.php#L31

**Comment by nkovacs** [comment]
Also, 'long' and 'full' have no space before AM/PM, medium has. The ICU default for en-US has a space before AM/PM in all three.

**Comment by cebe** [comment]
not sure where I got these from but I think it was part of an ICU version that I had installed when I implemented this. A change will break BC so I set the milestone to be 2.1.
Created a test case for this, need to match that against multiple ICU versions later.
