### ISSUE TITLE
Patch release 2.0.3.1?

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#7771]
As #7529, which is quite an issue, got fixed and also a lot of docs have been written since the release of 2.0.3, could you release a patch version 2.0.3.1?

**Comment by samdark** [comment]
Docs as updated automatically independent of releases.

It's @qiangxue decision to release or not to release 2.0.3.1.

**Comment by qiangxue** [comment]
This time we will still follow our original release plan which is to release 2.0.4 about a month from today. Starting from 2.0.4, for each 2.0.x release we will create a maintenance branch 2.0.x so that it can be used as release vehicles to make patch releases like this.
