### ISSUE TITLE
optimization method className()

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#7772]
```php
$start = microtime(true);
for($i=0; $i < 1000000; $i++) {
//    User::className(); // 0.81278204917907715
    User::class; // 0.065196990966796875
}
$stop = microtime(true);

echo($stop - $start);
```
This option is 12 times faster
But the method class available since at php 5.5
When do you plan to abandon support for php 5.4?

**Comment by samdark** [comment]
Not in 2.0.x.

**Comment by LAV45** [comment]
Then php 5.4 you can delete from here? https://github.com/yiisoft/yii2/blob/2.1/.travis.yml

**Comment by samdark** [comment]
It wasn't decided yet about 2.1 PHP version.

**Comment by Faryshta** [comment]
I think this one got solved already

**Comment by SilverFire** [comment]
Yeah, it is decided to use `::class`. Thank you @Faryshta
