### ISSUE TITLE
Cache - Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by longmayar** [yiisoft/yii2#7773]
I'm trying to cache simple query. Artist hasMany Song, Song->getArtist (with condition).

```php
        $mainArtist = Yii::$app->cache->get('get-main-artist-of-song_id-'.$this->id);

        if ( $mainArtist === false ) {
            $mainArtist = Artist::find()
                ->innerJoin('artist_song', 'artist_song.song_id = '.$this->id)
                ->one();

            Yii::$app->cache->set('get-main-artist-of-song_id-'.$this->id, $mainArtist);
        }
```
Result: Exception - Serialization of 'Closure' is not allowed

For "Query cache" i need to use DbDependency.

```php
        $dependency = new DbDependency;
        $dependency->sql = '**????**';
        
        $mainArtist = Artist::getDb()->cache( function($db) {
            return Artist::find()
                ->innerJoin('artist_song', 'artist_song.song_id = '.$this->id)
                ->one();
        }, null, $dependency);
```
What dependency do i need to use?

**Comment by samdark** [comment]
Anything that doesn't have closure.

**Comment by longmayar** [comment]
samdark, where is closure in my code?

Give me please example of dependency in my case.

```php
$dependency->sql = '**????**';
```

**Comment by samdark** [comment]
```php
$mainArtist = Artist::getDb()->cache( function($db) {  <---- here
```

Closure == anonymous function. These could not be serialized in PHP.

**Comment by longmayar** [comment]
Ok, but i'm trying to set cache this data:
```php
            $mainArtist = Artist::find()
                ->innerJoin('artist_song', 'artist_song.song_id = '.$this->id)
                ->one();

            Yii::$app->cache->set('get-main-artist-of-song_id-'.$this->id, $mainArtist);
```
There is no anonymous functions in my code, but i have got Exception - Serialization of 'Closure' is not allowed.

**Comment by cebe** [comment]
there might be a problem with the AR instance being cached. Could be that there is a closure bound as an event handler. @longmayar can you show your AR code? do you have any behaviors declared in the active record class?

**Comment by longmayar** [comment]
```php
class Artist extends ActiveRecord
{
...
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => 'created_at',
                    ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
                ],
                'value' => function() { return date('Y-m-d H:i:s'); }
            ]
        ];
    }
...
}
```

May be it's  'value' => function() { return date('Y-m-d H:i:s'); } ?

**Comment by klimov-paul** [comment]
Yes it is.
Convert this anonymous function into the model internal method.

**Comment by longmayar** [comment]
```php
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => 'created_at',
                    ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
                ],
                'value' => DateTimer::now()
            ]
        ];
    }
```

Great! 
samdark, cebe, klimov-paul, thanks a lot!

**Comment by longmayar** [comment]
Oh.. this time i got warning on create new Artist:

call_user_func() expects parameter 1 to be a valid callback, function '18.03.2015 14:36:12' not found or invalid function name

**Comment by samdark** [comment]
Specify it as `[$this, 'getNow']` and create a method `getNow` in the class.

**Comment by longmayar** [comment]
It works! Thx

**Comment by lucasemanuel8** [comment]
> Yes it is.
> Convert this anonymous function into the model internal method.

I had the same problem, and the @klimov-paul solution solved
