### ISSUE TITLE
View File not found with CamelCase Controller name

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii2#7775]
Hi i have created a Controller named ```frontend\controllers\TestUpperCaseController``` with the Gii crud Generator.
I didn't set any viewpath in the generator so the default view path is used ```@app/view/test-upper-case```.

I know open the Controller with the url ```/test-upper-case``` and everything works.
I use the url  ```/testuppercase``` and the same Controller TestUpperCaseController is called and i get a view not found.

I only have UrlManager setup with pretty Urls and my Development machine is Windows.
I am not 100% sure if this is a windows lower/upper case problem which won't exist on linux.
But nevertheless i guess this should be fixed.

I knew that i can modify getViewPath to just return so that the correct view path "test-upper-case" is used.

```
public function getViewPath() {
        return "@app/views/test-upper-case";
}
```

So why isn't there something like below where the className must be of course without the namespace path and 'Controller'.

```
public function getViewPath() {return $this->module->getViewPath() . DIRECTORY_SEPARATOR . Inflector::camel2id(ClassHelper::getClassname($this));
}
```
Where the function getClassname is something like:
```
public static function getClassname($obj, $without_type = true)
    {
        $classname = get_class($obj);
        if ($without_type) {
            if (preg_match('@\\\\([\w]+)(Controller|Action)$@', $classname, $matches)) {
                $classname = $matches[1];
            }
        } else {
            if (preg_match('@\\\\([\w]+)$@', $classname, $matches)) {
                $classname = $matches[1];
            }
        }
        return $classname;
    }
```

Or why can we just not set it with a public variable which is used when it is set?
```
public $viewPath = "@app/views/test-upper-case";
```

Because then the correct view path is used for both url requests (with and without -).
As i have written above I am not 100% sure if the Url without "-" would even get the same Controller class or would just return a 404, but as on Window this is the case i guess this should be fixed anyhow.

**Comment by klimov-paul** [comment]
> I am not 100% sure if this is a windows lower/upper case problem which won't exist on linux.

Indeed your 'problematic' controller is loaded because of Windows case insensitive file system. For Windows files 'TestUpperCase.php' and 'testuppercase.php' are the same, as well as for PHP classes 'TestUpperCase' and 'testuppercase' are also the same.

> Or why can we just not set it with a public variable which is used when it is set?

Controller composes its view path using its `$id` field. You may enforce it to be `test-upper-case`, but you should do it at `init()` method:
```php
public function init()
{
    $this->id = 'test-upper-case';
    parent::init();
}
```

I am unsure if this issue can be fixed, at least without BC break. To solve t we need to normalize controller id using actual class name before setting it at `Module::createControllerByID`. But same issue may appear for the module as well.
Need to thik about this.

**Comment by Bhoft** [comment]
So why don't you make a string comparison on the function createControllerByID in the yii2\base\Module.php like below where you do a Binary safe string comparison which is case sensitive and return null if the Classname is not correct.
E.g. in my case 
frontend\\controllers\\TestuppercaseController would return null and only if the ClassName is correct frontend\\controllers\\TestUpperCaseController the correct Controller will be called.

The result will be a 404 on Windows like it is also on Linux.

```
public function createControllerByID($id)
{
...
  if (is_subclass_of($className, 'yii\base\Controller')) {
            $object=Yii::createObject($className, [$id, $this]);
            if (strcmp($object->className(), $className)!== 0) {
                return null;
            } else {
                return $object;
            }
            //return Yii::createObject($className, [$id, $this]);
        }
}
```

**Comment by cebe** [comment]
I see now drawbacks from this but should be checked in detail.

**Comment by x8core** [comment]
omg, i kill a hour to resolve why my tracksController not found and why i get an error.

it's all about that fix

return get_class($controller) === $className ? $controller : null;
