### ISSUE TITLE
Validation: provide something like a hook for a rule

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#7779]
I'd like to log something if a validation rule fails.  E.g. If there is a 'default' validation rule I would like to track if the substitution has taken place or not. I would than log a warning.

But it could be regarded more general. My suggestion is (example rule in `Model::rules()`):

    ['myAttribute', 'someValidator',
        
        'action' => function ($attribute, $success) {
            //$success is true or false
            Yii::trace("Attribute $attribute succeeded: " . ($success ? 'yes' : 'no') . ".");
        },
        
        // and/or
        
        'success' => function ($attribute) {
            Yii::trace("Attribute $attribute is okay.");
        },
        'fail' => function ($attribute) {
            Yii::warning("Attribute $attribute is not okay.");
        },
    ],

A smaller improvement, of course.

**Comment by lynicidn** [comment]
use afterValidate and $this->errors or afterSave and $changedAttributes

**Comment by robsch** [comment]
@lynicidn  That's an option. But it could be also part of a validator itself that you may could use in different places.

**Comment by klimov-paul** [comment]
I don' think this make any sense. Model is a logical aggregation of attributes, model validation is an atomic business operation. You may need to track down if its entire validation fails, which is already possible, but tracking failure of the particular validation rule seems odd.
This is too specific to be inside the core. You may acheive your goal extending particular validator and overriding its `validateValue()` method:
```php
protected function validateValue($value)
{
    $result = parent::validateValue($value);
    if ($result === null) {
        // success
    } else {
        // failure
    }
}
```
