### ISSUE TITLE
enablePrettyUrl on Yii2 Advanced Shared Server

### ISSUE THREAD

**Issue by nunorbatista** [yiisoft/yii2#7785]
Hi,

I'm running a Yii2 Advanced Application on a Shared Server and I'm trying to enable the Pretty URL's / remove index.php.
I followed the guide: https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-shared-hosting.md to setup the application on the shared server and everything went right except for the part of the UrlManager.

I did moved the contents of the /frontend/web to the root (public_html), changed the index.php and all went ok. I also enabled the prettyURL's on the frontend config file and it's working ok, so in the frontend I have: www.mywebsite.com/login (for ex.) working fine.

The problem comes in the backend: 

I created the folder /admin inside public_html and moved the /backend/web contents there. I followed the guide and the backend is working on mywebsite.com/admin but without the pretty urls, for ex: https://mywebsite.com/admin/index.php?r=sandbox.

Now the problem: When I enable the prettyUrls's in the backend config file, I get 404.

Here's the content of the .htaccess on the root (public_html):

```
Options +FollowSymLinks
IndexIgnore */*

RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule . index.php
```

And this is the contents of the config file that is working on frontend but not on backend:

```
        'urlManager' => [
                'class' => 'yii\web\UrlManager',
                //'enablePrettyUrl' => true,
                'showScriptName' => false,
            ],
```

I suspect this is something related with .htaccess but there's no information on that matter in the guide.

Thanks in advance for reviewing this issue.

**Comment by samdark** [comment]
Try putting another `.htaccess` with exactly the same content into backend directory.

Closing the issue since it's not related to framework but is a configuration issue

**Comment by QuadDamage** [comment]
It worked, thanks.

Perhaps it would be good to edit the guide I followed to include the pretty URL configuration:
https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-shared-hosting.md

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/commit/7e1d96ac055fbb0ee51521ec5edc2dd9d87dc324
