### ISSUE TITLE
About github commit problem

### ISSUE THREAD

**Issue by navinova** [yiisoft/yii2#7786]
Hi, 

We developed an app with yii2 advanced template. When we tried to commit all files to github:

        modified:   vendor/cebe/markdown (modified content)
        modified:   vendor/fzaninotto/faker (modified content)
        modified:   vendor/swiftmailer/swiftmailer (modified content)
        modified:   vendor/yiisoft/yii2 (modified content, untracked content)
        modified:   vendor/yiisoft/yii2-bootstrap (modified content, untracked content)
        modified:   vendor/yiisoft/yii2-debug (modified content)
        modified:   vendor/yiisoft/yii2-gii (modified content)

These files & folders cannot be committed. 

I know, they re installing with composer. 

But when i tried to composer update or composer install this folders cant be installed. so our project cant run on server.

any idea?

thanks

**Comment by klimov-paul** [comment]
This is not Yii issue.
Most probably you (or git tool you use) have removed or miss-edited `.gitignore` file or added some files manually.

**Comment by navinova** [comment]
We didnt add or remove sth from  swift mailer, markdown, faker, gii and others. we just wrote code and commit.

**Comment by lynicidn** [comment]
check record https://github.com/yiisoft/yii2/blob/master/apps/advanced/.gitignore#L19

**Comment by navinova** [comment]
thank you, @lynicidn  i think this is the solution.
