### ISSUE TITLE
"Expected \yii\db\string, got string" warning

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2#7787]
I'm using PhpStorm and getting warnings in models about 

```
	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getArticles()
	{
		return $this->hasMany(Article::className(), ['category_id' => 'id']);
	}
```

On ```Article::className()``` that ```Expected \yii\db\string, got string```.

It is because ActiveRecord class contains phpdoc statement (```ActiveRecord ::hasMany()```) ```@method ActiveQuery hasMany(string $class, array $link)...``` ([ActiveRecord.php#L72](https://github.com/yiisoft/yii2/blob/bb4a0c70a1b7f2e4f94ef064b0dcaebb29c46b6c/framework/db/ActiveRecord.php#L72)) and it resolves "string" as class name in specific namespace. It should be "\string". The same issue is with ```ActiveRecord ::hasOne()``` ([ActiveRecord.php#L73](https://github.com/yiisoft/yii2/blob/bb4a0c70a1b7f2e4f94ef064b0dcaebb29c46b6c/framework/db/ActiveRecord.php#L72)).

I like to see phpstorm "green status" for all my files, but those white notifications bugs me.

**Comment by cebe** [comment]
you can not use scalar type hint in PHP < 7.0,  remove the string from $class.

**Comment by cebe** [comment]
fixed, thanks for reporting.
