### ISSUE TITLE
Unknown Property Exception after adding column? 

### ISSUE THREAD

**Issue by zohaibhassan** [yiisoft/yii2#7788]
Hi 
1- i have added New Column to the database table
2- added field to rules in model
            [['country', 'city', 'number'], 'required'],
            [['company_name', 'country', 'city'], 'string', 'max' => 50],
            [['number'], 'string', 'max' => 25],

3- added to attribute labels
            'id' => 'ID',
            'company_name' => 'Company Name',
            'country' => 'Office Country',
            'city' => 'Office City',
            'number' => 'Office Phone',

4- added to form (field type doesnt matter)
<?= $form->field($model, 'company_name')->textarea(['rows' => 9]) ?

but nothing works with the following error
Getting unknown property: app\modules\hrm\models\Offices::company_name

Any Idea?
Thank You

**Comment by Alex-Code** [comment]
If you have a caching component set try clearing it's cache.

**Comment by mdmunir** [comment]
I have a good idea. How if you ask in yii official forum.

**Comment by zohaibhassan** [comment]
Thanks Alex it was caching Problem.Just Commented out my configuration for cache in web.php and after that it was fine.
Although it was strange though.

**Comment by Alex-Code** [comment]
Yii will cache the table schema so if you change the table you need to clear the cache.
