### ISSUE TITLE
TimestampBehavior problem when using expression

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#7791]
Hello.

This is problem: "NOW()"

![screenshot from 2015-03-19 19 08 06](https://cloud.githubusercontent.com/assets/1358236/6734823/61a126c0-ce6b-11e4-8d1c-7713feff4aee.png)
I think that the correct conclusions empty field. Or old value.

### To Reproduce
```php
<?php

namespace app\models\activeOverride;

use Yii;
use yii\behaviors\TimestampBehavior;

class Agency extends \app\models\activeRecords\Agency
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'active'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
        ];
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            TimestampBehavior::className() => [
                'class' => TimestampBehavior::className(),
                'value' => new \yii\db\Expression('NOW()')
            ],
        ]);
    }
    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert)) {
            // update some relation models
            $this->addError('active', 'error update relations');
            return false;  // I think this is the right work with the framework. Right?
        }
    }
}
```

UPDATE: add my rules and comment

**Comment by lynicidn** [comment]
beforeSave always return result as `boolean`

**Comment by mikehaertl** [comment]
You should not add errors in `beforeSave()` because it's assumed that validation succeeded at that point. Use `afterValidate()` or something.

**Comment by wartur** [comment]
@lynicidn it's my megastyle =)). but it's not about this bug.

@mikehaertl why?
I think that validation - a single process, and save the associated data is a different process. At each stage, errors may occur. Am I wrong?

If I am right, then generate an error on maintaining a completely normal situation.

How should I handle the situation that I wrote on the guide of the framework?

**Comment by lynicidn** [comment]
@wartur it's code error. 
```php
    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert)) {
            $this->addError('active', 'my error');
            return false;  // I think this is the right work with the framework. Right?
        }
    }
```
need always return result. U return only `false`, but only in good case

**Comment by wartur** [comment]
@lynicidn no. it's for example.
off cource in real code i'm use somethink like this
```php
    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert)) {
            // my magic
            return true;  // I think this is the right work with the framework. Right?
        }
        // yea I like php for weakly typed =)
    }
```
or this
```php
    public function beforeSave($insert)
    {
        if(!parent::beforeSave($insert)) {
            return false;
        }
        // my magic
        return true;
    }
```


but I'm repeat. IT'S not about THIS bug. =)))

**Comment by lynicidn** [comment]
timestamp behavior don't validate value, and add ur value beforeSave - if u do validate ur field don't have `NOW` as value - https://github.com/yiisoft/yii2/blob/master/framework/behaviors/TimestampBehavior.php#L97

**Comment by mikehaertl** [comment]
@wartur You should not do it because you get into exactly the trouble you are now. Behaviors like the TimestampBehavior expec, that on the beforeSave event, we are almost writing to DB now and can do last-minute changes to the record. Yes, they could stop the save, but that should not be because of validation errors at this point.

> PS: afterValidate can't stop save process.

Of course you can. Just add an error.

And there's no reason why you could not replace beforeSave with afterValidate. You can use `$this->isNewRecord` to find out, if it's an insert.
