### ISSUE TITLE
all Integer Fields are marked as Dirty each Form post even if not changed

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii2#7792]
Hi,
I have just seen, that all "numerical" DB columns are marked as dirty on each form submit.
This is clear because on the form post the type is (string) and not (int)

It can also be checked 
```
$model = MODEL::findOne(1);
$model->integer_colum=$model->integer_colum;
// no change in getDirtyAttributes

$model->integer_colum=12;  // if 12 is the value in the database
// no change in getDirtyAttributes

$model->integer_colum=(int)'12';  // if 12 is the value in the database
// no change in getDirtyAttributes



$model->integer_colum='12';  // if 12 is the value in the database
// Column is marked as dirty
```
the column has the rule 
```
   [['integer_colum'], 'integer'],
```

And this will be for every numerical db column on each form submit.
```
$model->load(Yii::$app->request->post())
```
Guess you have some === check somewhere. 
Don't know if we can cast the form values somehow with some rule before the setAttributes call.

**Comment by klimov-paul** [comment]
Duplicates #4284

**Comment by Bhoft** [comment]
I really hoped that something like this is added to the NumberValidator functions which will solve this 
for all. Of cause after the validations mit preg_match, so only the type is changed if the field is indeed a number.

```
if (is_string($value)) {
    $this->integerOnly ? settype($value, 'integer') : settype($value, 'float');
}
```

i haven't looked for closed issues, and thought that this should be fixed.

**Comment by Bhoft** [comment]
forgot to set the value back after the type change
https://github.com/Bhoft/yii2/commit/38efa6ce1e9f295bee1b1ee3018bdb17c0278cb4
