### ISSUE TITLE
Bootstrap ActiveField checkbox ignores label option

### ISSUE THREAD

**Issue by smichae** [yiisoft/yii2#7794]
The Bootstrap version of ActiveField checkbox function seems to ignore anything passed in on the label option and is always using the attribute label from the model.

```php
use yii\bootstrap\ActiveForm;
$form = ActiveForm::begin();
echo $form->field($model, 'a_checkbox')->checkbox(['label' => 'This should display but does not.'])
ActiveForm::end();
```

I have worked around it using the following as suggested in some other issues, but I would imagine that others will probably have the same issue as Yii2 starts to be used more often.

```php
echo $form->field($model, 'a_checkbox')->checkbox()->label('This should display and it does.')
```

Looking at some other related issues, I can't tell if this is intended behavior or not.  If it is the correct behavior, the docs should probably be updated to not inherit the non-Bootstrap ActiveField checkbox function description, as that makes it seem like passing in the label should work.

**Comment by pana1990** [comment]
I confirm this issue.

@cebe  What is the expected behavior for radio/checkbox button with label option?

**Comment by mikehaertl** [comment]
@pana1990 It should work, of course. 

As a sidenote, there's a little difference between `label()` and passing `label` as option:

 * `label()` will create a full `<label for ="...">` tag (for checkboxes and radios: only if `enclosedBylabel` is `false`)
 * passing `label` option will use the raw string as label and not create a `<label>` tag

**Comment by pana1990** [comment]
@mikehaertl @samdark radio and checkboxes of bootstrap extension have not same behavior that radio and checkbox of widgets

I think to it should be documented the methods. Currently it has inheritdoc.

what do you think about it?

**Comment by mikehaertl** [comment]
@pana1990 right. I'll go over all the methods in ActiveField and add apropriate docs.

**Comment by mikehaertl** [comment]
@pana1990 After some more thinking, I'm not really sure, if the method is so much different. What exactly are you missing?

**Comment by pana1990** [comment]
when checkbox() or radio() function uses label method(), it has behavior different,

for example : 

```php
<?= $form->field($model, 'subject')->checkbox(['label' => 'TestOption'], true)->label('TestLabel') ?>
<?= $form->field($model, 'subject')->checkbox([], true)->label('TestLabel') ?>
```

it generated with yii\bootstrap\ActiveForm : 
![bootstrap](https://cloud.githubusercontent.com/assets/6630197/6972484/6a8e3bf0-d984-11e4-93c3-b73bc54bf247.png)
and with yii\widgets\ActiveForm : 

![widgets](https://cloud.githubusercontent.com/assets/6630197/6972499/7d0185a8-d984-11e4-92fe-76e8785a49e0.png)

**Comment by mikehaertl** [comment]
@pana1990 I would say that the former is not really relevant use case (mixing `label` option with `label()` method). And the second rather looks like something that probably needs fixing in `yii\widgets\ActiveField`.

**Comment by fortex** [comment]
Sorry for "Hijacking", but I think my issue fits too. It seems there is no way to add HTML options to a label when using checkboxes with a custom template.

The following works in my scenario:
```php
<?= $form->field($model, 'myAwesomeField')
                 ->label('Awesome Label', ['class' => 'awesome-label']);
                 ->checkbox(); // Works ?>
```

But since I'm controlling the labels via attributeLabels() I don't really want to do that. And I don't want to repeat the options again and again.

This - so I thought - should work too.
```php
<?php 
$form->fieldConfig['horizontalCheckboxTemplate'] =  "{beginWrapper}\n<div class=\"checkbox\">\n<label class=\"st-checkbox\">\n{input}\n<span></span>\n</label>\n</div>\n{endWrapper}{label}\n<div class=\"row\">{hint}</div>\n<div class=\"row control-error\">{error}</div>";
$form->fieldConfig['labelOptions'] = ['class' => 'awesome-label']; 
?>
<?= $form->field($model, 'myAwesomeField')
                 ->checkbox(); // Does not work ?>
```

If I pass **$enclosedByLabel** as false for **checkbox()** it works, but my **horizontalCheckboxTemplate** is not used, instead **template** is used (of course now I've found out about it, by writing this post.)

So using "template" solves my problems. My only point is now, **please document this kind of stuff**. It really is frustrating. I basically have to read through core code to understand stuff like this, because it is not written anywhere, or maybe not easy to find.

Sorry again for hijacking. :)

**Comment by pana1990** [comment]
@mikehaertl  you right, thanks for you comment

**Comment by mikehaertl** [comment]
@fortex For now you can find many examples here: http://codemix.github.io/yii2-bs3activeform/index.html. This project was the predecessor of `yii\bootstrap\ActiveForm` and `ActiveField`, before it was merged into the official code base. So most of the examples are still valid. 

I agree that something like this should be included in the Yii 2 documentation. I'm just not sure who's responsible.
