### ISSUE TITLE
command->queryAll() on not supported DBMS 

### ISSUE THREAD

**Issue by makroxyz** [yiisoft/yii2#7795]
I'm trying to query an AS/400 DB2 database using Command object.

My select command has one parameter and I bind it with $command->bindValue('name', $value, \PDO::PARAM_STR) in order to avoid reading an unsupported Schema.

Anyway $command->queryAll(), at the end, calls $this->db->quoteValue() which needs DB Schema... and it throws yii\base\NotSupportedException

Is there any way to skip quoteValue() call??

**Comment by klimov-paul** [comment]
No, there is not.
You should declare the Schema for your DBMS. It could be done by extending existing one.

**Comment by mdmunir** [comment]
@klimov-paul 
How to add new schema to `Connection::$schemaMap`?

**Comment by klimov-paul** [comment]
Just like any other property:
```php
'db' => [
    'class' => 'yii\db\Connection',
    'schemaMap' => [
        'myschema' => 'app\my\custom\Schema'
    ],
],
```

**Comment by mdmunir** [comment]
It will remove previous map.
```php
'db' => [
    'class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=localhost;dbname=yii2app',
//    'dsn' => 'mysql:host=localhost;dbname=yii2app',
//    'dsn' => 'db2:host=localhost;dbname=yii2app',
    'schemaMap' => [
        'db2' => 'app\my\custom\Schema'
    ],
],
```
Not easily to change only dsn. IYKWIM

**Comment by klimov-paul** [comment]
So... you need to have several(!) dns maps for the single(!) db connection? Are sure this is necessary?
