### ISSUE TITLE
ActiveRecord::findByCondition $condition explanation in comments

### ISSUE THREAD

**Issue by codeskull** [yiisoft/yii2#7796]
Hello everyone.
I wanted to look into` ActiveRecord::findAll`  `$condition` parameter to find out what options it has and kinda failed.
I'd jump into the source of `BaseActiveRecord`:
```php
/**
 * @inheritdoc
 * @return static[] an array of ActiveRecord instances, or an empty array if nothing matches.
 */
public static function findAll($condition)
{
    return static::findByCondition($condition)->all();
}
```
Okay, It's calling `findByCondition`:
```php
/**
 * @param mixed $condition please refer to [[findOne()]] for the explanation of this parameter
```
But `findOne` doesn't say anything:
```php
/**
 * @inheritdoc
 * @return static ActiveRecord instance matching the condition, or `null` if nothing matches.
 */
public static function findOne($condition)
```
I hope my explanations are clear. Thanks.

**Comment by codeskull** [comment]
Oh, there was an interface, I'm sorry.

**Comment by githubjeka** [comment]
Yes  but interface is implemented but in this case with a pitfall. Documentation is not a clear.
https://github.com/yiisoft/yii2/issues/7888#issuecomment-86744208
