### ISSUE TITLE
Issue with yii2 mongodb not equal operator

### ISSUE THREAD

**Issue by samfreelancer** [yiisoft/yii2#7798]
This is my mongodb condition in yii2 
['_id' => [ '$ne' => $this->_id ], $attribute => $this->{$attribute} ]

I don't give the desire result. When i dig deep into the library code. I identified that it is not converting $this->_id parameter that i am providing above into the MongoId. The code responsible to do this is function buildHashCondition($condition) under mongodb collection class. So, either my query condition is wrong or there is some issue with the mongodb collection class function.

Any body can help me on this.

**Comment by lynicidn** [comment]
use forum and read about yii\db\Expression

**Comment by samfreelancer** [comment]
Got that working by myself. I changed my condition
Before:
['_id' => [ '$ne' => $this->_id ], $attribute => $this->{$attribute} ]

After
['_id' => [ '$ne' =>  new \MongoId($this->_id) ], $attribute => $this->{$attribute} ]

Hope this will help others.

**Comment by klimov-paul** [comment]
Relates:
https://github.com/yiisoft/yii2-mongodb/pull/14

**Comment by klimov-paul** [comment]
Added support for 'NOT' condition 6156f4f
