### ISSUE TITLE
Install codeception globally?

### ISSUE THREAD

**Issue by tsvetann** [yiisoft/yii2#7802]
Any specific reason why we are recommended to install codeception globally as per http://www.yiiframework.com/doc-2.0/guide-test-environment-setup.html?

**Comment by cebe** [comment]
this way you can put it in your PATH to have a `codeception` command in your bash. whats wrong with that?

**Comment by creocoder** [comment]
@cebe Wrong part is that nowadays applications requre test suites locally. For example: https://github.com/thephpleague/climate/blob/master/composer.json#L18 . And recommend to install globally is wrong and bad practice.

@tsvetann No point at all unless you want troubles with testsuites which can be incompatible with globally installed version :)

**Comment by lynicidn** [comment]
yii2 package also must installed globaly :)

**Comment by tsvetann** [comment]
@cebe following the linked documentation a developer would think that s/he has completed codeception installation which is false. After you start generating some test classes you notice that all Codeception classes cannot be found as they are expected locally! I think this is confusing and should be noted in the linked documentation somehow

**Comment by samdark** [comment]
@tsvetann what do you mean? I have it installed globally and all classes are successfully found.

**Comment by tsvetann** [comment]
@samdark I had it installed globally only and the following trait couldn't load for me `use \Codeception\Specify;` After local installation it loaded successfully! Maybe I missed a step?

**Comment by samdark** [comment]
Have you installed codeception/specify?

**Comment by tsvetann** [comment]
Yes as per the linked documentation. The Specify.php was indeed in the global composer folder. To be more specific: `/home/vagrant/.composer/vendor/codeception/specify/src/Codeception/Specify.php`

**Comment by Ragazzo** [comment]
it was a long discussion with me and @samdark about that, i was strongly against global install and i think it should be removed, because it can affect other projects that you are working on

**Comment by tsvetann** [comment]
@Ragazzo good point!

**Comment by samdark** [comment]
I prefer leaving it as is.

**Comment by klimov-paul** [comment]
Docs adjusted: e7ce2ce
