### ISSUE TITLE
mongodb Cross-Database Relations not on _id

### ISSUE THREAD

**Issue by bdart** [yiisoft/yii2#7805]
Is this a bug or correct that I cannot link the mongodb's `_id` field within my CDR?
This is the snippet in my ActiveRecord class.
```
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleContent()
    {
        return $this->hasOne(MongoArticle::className(), ['_id' => 'storage_id']);
    }
```

I can work around by adding an extra field within the mongo insert but this is redundant. Also when I want to access this field while saving I have to get the insert id with this:
```
$storage_id = MongoArticle::findOne(['title_clean' => $tmp_title])->_id->{'$id'};
```

This at the end is quite messy.

**Comment by klimov-paul** [comment]
Typecasting of the `MongoId` value into a string is a common problem, which you have been warned about:
https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/usage-mongoid.md
