### ISSUE TITLE
\yii\widgets\MaskedInput no generates special data attributes "data-plugin-name" and "data-plugin-options"

### ISSUE THREAD

**Issue by wbraganca** [yiisoft/yii2#7808]
The error is in the method "run". The call to "registerClientScript" should be before creating the "input".

Change it:

```php
public function run()
{
    if ($this->hasModel()) {
        echo Html::activeTextInput($this->model, $this->attribute, $this->options);
    } else {
        echo Html::textInput($this->name, $this->value, $this->options);
    }
    $this->registerClientScript();
}
```

To

```php
public function run()
{
    $this->registerClientScript();
    if ($this->hasModel()) {
        echo Html::activeTextInput($this->model, $this->attribute, $this->options);
    } else {
        echo Html::textInput($this->name, $this->value, $this->options);
    }
}
```

**Comment by lynicidn** [comment]
read about `position for register client scripts`

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/View.php#L409
default as `pos_ready` it's correct in other case

**Comment by wbraganca** [comment]
Note that the function "hashPluginOptions" values: https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L139

```php
$this->options['data-plugin-name'] = self::PLUGIN_NAME;
$this->options['data-plugin-options'] = $this->_hashVar;
```

The options will never be added to the input because the input is created before: https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L125

**Comment by lynicidn** [comment]
options register in head https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L145

plugin lib register in ready

where problem ?

**Comment by wbraganca** [comment]
@lynicidn the current code generates the following output:

```html
<input type="text" id="example-year" class="form-control" name="Example[year]">
```

The correct output would be:

```html
<input type="text" id="example-year" class="form-control" name="Example[year]" data-plugin-name="inputmask" data-plugin-options="inputmask_fea305f5">
```

See the attributes "data-plugin-name" and "data-plugin-options" are not being added to the input. This is because the variables are set after the generation of the "input".

https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L125

https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L175

**Comment by lynicidn** [comment]
if u want add this variable for input u should add in config
```php
::widget([
    'clientOptions' => [
        'data' => [
            'plugin-options' => ....
        ],
    ],
]);
```
it's other way to register plugin via data attributes

**Comment by wbraganca** [comment]
I was very objective in the problem description. The widget code adds two "data" attributes ("data-plugin-name" and "data-plugin-options"), see here: https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L143

The current implementation does not add the "data" attribute to the "input" because they were created later. I believe that this feature has been added for @kartik-v

**Comment by lynicidn** [comment]
what is problem u have?
exist 2 way register plugins:
1. via data attributes
2. via plugin "constructor"
masked use second way. all ways is correct

**Comment by lynicidn** [comment]
```
Define your masks:

$(document).ready(function(){
   $(selector).inputmask("99-9999999");  //static mask
   $(selector).inputmask("mask", {"mask": "(999) 999-9999"}); //specifying fn & options
   $(selector).inputmask({"mask": "99-9999999"}); //specifying options only
   $(selector).inputmask("9-a{1,3}9{1,3}"); //mask with dynamic syntax 
});

or via data-inputmask attribute

<input data-inputmask="'alias': 'date'" />
<input data-inputmask="'mask': '9', 'repeat': 10, 'greedy' : false" />
<input data-inputmask="'mask': '99-9999999'" />
```
(c) https://github.com/RobinHerbots/jquery.inputmask

**Comment by qiangxue** [comment]
Thanks @lynicidn for the explanation.

**Comment by wbraganca** [comment]
@qiangxue If the code is correct, this is not in conformity with the documentation displayed in the `hashPluginOptions` method.


![masked-input](https://cloud.githubusercontent.com/assets/1946359/7347354/405ba1fe-ecbe-11e4-9e77-80ee75b81c80.jpg)




Changing the code as suggested the beginning of this issue. We get the output as described in doc comment of `hashPluginOptions` method.



![saida-masked](https://cloud.githubusercontent.com/assets/1946359/7347292/858ad912-ecbd-11e4-8b08-81511586aff0.jpg)

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L183

**Comment by kartik-v** [comment]
I understand @wbraganca 

- the input markup should have valid values for attributes `data-plugin-name` and `data-plugin-options`. This will enable developers to read them via additional javascript for easily getting the input mask plugin options.

- for this to happen these attributes must be setup in `MaskedInput::options` before rendering the input

**Comment by rabraganca** [comment]
I changed the widget code on my PC as suggested by @wbraganca. And there is really a problem as described.

It doesn't make sense to have the lines [143](https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L143) and [144](https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php#L144), since these options are never added to the "html input field".

**Comment by qiangxue** [comment]
Thanks @wbraganca and everyone for clarification.

**Comment by luandiego7** [comment]
hello @wbraganca, good evening. 
i have a issue, like this.. can you help me? 
the kartik daterangepicker and the maskinput just work in first row.
but i saw that when i save the form, same without the masks, on the update the masks works.
Well, when i add a new row, it does not work, if i save same like this, the masks works after.
Are you brasilian, right? my english is veryyy poor, i'm sorry. can we speak in portugue? haha
