### ISSUE TITLE
Changing signature of parent class constructor by adding dependency to be injected from DI container: sequence of arguments is critical

### ISSUE THREAD

**Issue by M0on75e1l** [yiisoft/yii2#7811]
To simplify, my class looks like:
```php
class MyClass extends \yii\base\Object
{
    protected $user;

    public function __construct($config = [], User $user) {
        $this->user = $user;
        parent::__construct($config);
    }
}
```
`\yii\base\Object` class constructor:
```php
public function __construct($config = [])
{
    if (!empty($config)) {
        Yii::configure($this, $config);
    }
    $this->init();
}
```
That leads to exception like: `User` class object expected, `array` was given. Appending a new argument to the end of arguments list seemed so logical to me, that I've don't even guessed to swap them places - thought it was a bug. After half an hour debugging of recursive functions I've realized what I need to do since I've found that line:
https://github.com/yiisoft/yii2/blob/3d403ad074b555dd3966ab41e5099d4e7e8bb468/framework/di/Container.php#L371

Later I found this like `.text-muted` in docs:
> Info: The [[yii\di\Container::get()]] method takes its third parameter as a configuration array that should be applied to the object being created. If the class implements the [[yii\base\Configurable]] interface (e.g. [[yii\base\Object]]), the configuration array will be passed as the last parameter to the class constructor; otherwise, the configuration will be applied after the object is created.

So all I want to mention is that there may be a need to change a few words in that paragraph. Maybe something like:
> ..., the configuration array will be passed as the last parameter to the class constructor, so all dependencies arguments MUST be placed before configuration array;

It's little unclear when explaining only in terms of DI Container methods and other class interfaces. I think that fact's actual consequence which directly affects developer's working process, worth of brief clear mentioning. Or maybe I was too tired.

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/yii-base-configurable.html

**Comment by klimov-paul** [comment]
Your class should satisfy `yii\base\Configurable` interface, which declares object config should always(!) be the last parameter of the constructor otherwise `yii\di\Container` is unable to instantiate it correctly.

**Comment by M0on75e1l** [comment]
My simplification didn't worked, my real class is far away from directly extending `yii\base\Object`. So when I just wanted to use DI container with my class, I didn't even knew about framework's core interface, which I should satisfy. I've started to think in another direction, especially since I am new to Yii2 and DI container concept. Now I see that there are phpdocs comments and examples about overriding constructor in `yii\base\Object` and `yii\base\Configurable`, but that fact makes even more clear to me, that there is a need to add that information in main docs, not only in comments to framework's core classes. I am sure that all information can be found by examining framework's code and reading all the comments, but such a critical condition should be clearly explained.
P.S. `yii\base\Configurable` itself actually does not defines any rules that I should satisfy since PHP interfaces can not define such condition. It just has some comments. Sequence of arguments is critical.

**Comment by samdark** [comment]
There's an interface you can implement: https://github.com/yiisoft/yii2/blob/master/framework/base/Configurable.php There's no need to extend from Object. Docs are mentioning it: https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-di-container.md#setter-and-property-injection-

**Comment by samdark** [comment]
Yeah, technically the interface doesn't enforce anything so it's more like a written contract.
