### ISSUE TITLE
QueryBuilder: problem with dbTypecast() returned Expression

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/yii2#7813]
When I return ```\yii\db\Expression``` from ```ColumnSchema::dbTypecast()``` it doesn't work.
This problem for ```QueryBuilder::insert()``` and ```QueryBuilder::update()```.

Because the returned value from ```ColumnSchema::dbTypecast()``` assigned as binding parameter:
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L252

It skips checking ```\yii\db\Expression``` the above:
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L244

The proposal would change the conversion type above:
```php
            if (!($value instanceof Expression)) {
                $value = !is_array($value) && isset($columnSchemas[$name]) ? $columnSchemas[$name]->dbTypecast($value) : $value;
            }

            if ($value instanceof Expression) {
                $lines[] = $this->db->quoteColumnName($name) . '=' . $value->expression;
                foreach ($value->params as $n => $v) {
                    $params[$n] = $v;
                }
            } else {
                $phName = self::PARAM_PREFIX . count($params);
                $lines[] = $this->db->quoteColumnName($name) . '=' . $phName;
                $params[$phName] = $value;
            }
```

**Comment by samdark** [comment]
Could you provide some code to reproduce the issue as a user.

**Comment by Tigrov** [comment]
I use it for complex types like array or json.
It related with other problem #7481 
My example will not work without it.

**Comment by klimov-paul** [comment]
`ColumnSchema::dbTypecast()` should NOT return `\yii\db\Expression`.
rerurn doc tag for it is rather clear:

> @return mixed converted value. This may also be an array containing the value as the first element
 and the PDO type as the second element.
