### ISSUE TITLE
Wrong entries in log files

### ISSUE THREAD

**Issue by Urkman** [yiisoft/yii2#7815]
I created a custom log file like this:

    'log' => [ 
    // ...
    'targets' => [
        [
            'class' => 'yii\log\FileTarget',
    // ...      
        ],
    // ... 
       [
            'class' => 'yii\log\FileTarget',
            'levels' => ['info'],
            'categories' => ['foo'],
            'logFile' => '@app/runtime/logs/foo.log',
       ],

Then I want to write to this log:
`Yii::info($message, 'foo');`

But I always have a "application" entry in my log file like this:
`2015-03-16 09:25:01 [-][-][-][info][foo] test log...`
`2015-03-16 09:24:01 [-][-][-][info][application] $_SERVER = [ ... ]`

But there should be only the 'foo' entries in the log file...

Here you can find a forum thread for this:
http://www.yiiframework.com/forum/index.php/topic/62614-wrong-entries-in-log-files/

**Comment by samdark** [comment]
Not a bug. Answered at the forum.
