### ISSUE TITLE
Few questions about forms ajax and validation. (how to refresh form validation and how to serialize data with fileinput)

### ISSUE THREAD

**Issue by butteff** [yiisoft/yii2#7817]
hello. I have got the form. I was created it with ActiveForm class. I blocked standart submit with preventDefault(); And afterValidate I submit the form with ajax:

```javascript
$('#form').on('afterValidate', function () {
    var url = $('#form').attr('action');
        var data = $('#form').serialize();
        $.ajax({
            type: "POST",
            url: url,
            data: data,
        });
 });
```

All works good. But only first time, second submit is not working with another data. How I can reset validation of the form after every submit for this good form working with ajax, like I want to see?

And one more question about ajax submit. I submitted the form with the same code, but if I using enctype = 'multipart/form-data' it's not working, yii gives error to me: 

>PHP Fatal Error 'yii\base\ErrorException' with message 'Call to a member function saveAs() on a non-object

How I can serialize the data with fileinput too?

Thank you

**Comment by butteff** [comment]
I found the solution, how to send with filesinput form with ajax:
```javascript
$.ajax({
      url: url,
      type: 'POST',
      data: new FormData( this ),
      processData: false,
      contentType: false,
      success:function(src) {
         $('.profile-photo').attr('src', src); 
      }
    });
```

but how to refresh validation - I don't know yet

**Comment by samdark** [comment]
What do you mean by refresh validation?

**Comment by butteff** [comment]
Thanks for your attention.
I mean, that I want to start validate the form again on frontend side. How I can call that?
If I click on the button again, 'afterValidate' trigger is not work.

**Comment by samdark** [comment]
Have you tried the following?

```javascipt
$('#form-id').yiiActiveForm('submitForm');
```

**Comment by butteff** [comment]
I rewrite code and with 'beforeSubmit' trigger all works, what I want to see.
It's not the same, but works. I also think, that your code will do what I wanted and I close this issue. Thank you so much for your attention and help.
