### ISSUE TITLE
Allow Html error messages in addError and addErrors

### ISSUE THREAD

**Issue by devypt** [yiisoft/yii2#7819]
Some times in need to add html links or tags inside the error messages, i believe this worth to be added.

**Comment by lynicidn** [comment]
use template https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L55

'<div class = "my">{error}</div>'

**Comment by lynicidn** [comment]
also u can deny encode 
'errorOptions' => ['encode' => false]

**Comment by devypt** [comment]
<?php $form = ActiveForm::begin(['encodeErrorSummary' => false]); ?>

this worked fine.

Thanks.
