### ISSUE TITLE
UniqueValidator::$targetAttribute array is back-to-front, or something

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#7820]
Say I have a form model `$form` with an input attribute `'name'`. I need to validate that `$form->name` is not already a taken `realname`, `nick` or `altname` in my `User` AR model. So I try to write a rule according to the [docs for `UniqueValidator::$targetAttribute`](http://www.yiiframework.com/doc-2.0/yii-validators-uniquevalidator.html#$targetAttribute-detail) and it ends up as nonsense:

``` php
['name', 'unique', 'targetClass' => User::className(), 'targetAttribute' => [
    'name' => 'realname',
    'name' => 'nick',
    'name' => 'altname',
]]
```

I think this is an unnecessary limitation in the design of this API. I understand that one might want to check one form attribute against multiple target class attributes or check multiple form attributes against arbitrary target attributes. Hence the use of a hash here cannot work for all use cases. But this is back to front. First I specify `name`, the form attribute to validate, in the first position of the rule and then I defeat it in the targetAttribute array. :-O Even if I omit the keys, I defeat the initial spec. >8-O

Moreover I think the numeric array case is wasted in the current design. This:

``` php
['name', 'unique', 'targetClass' => User::className(), 'targetAttribute' => ['realname', 'nick', 'altname']]
```

should mean (and in fact obviously does mean, unless you have managed to understand the docs*): check that the value of `$form->name` doesn't appear in `realname`, `nick` or `altname` in the `User` AR model's table. As it stands I have to do this with:

``` php
['name', 'unique', 'targetClass' => User::className(), 'targetAttribute' => 'realname'],
['name', 'unique', 'targetClass' => User::className(), 'targetAttribute' => 'nick'],
['name', 'unique', 'targetClass' => User::className(), 'targetAttribute' => 'altname'],
```

In my real use case, there are four of these and each has the same message, on and when. It's not pretty.

(\* "The array values are the attributes that will be used to validate the uniqueness, while the array keys are the attributes whose values are to be validated." Um...)

**Comment by amlopezalonso** [comment]
I also think doc for targetAttribute is rather confusing IMHO.
