### ISSUE TITLE
ArrayHelper map method problem with float type key problem

### ISSUE THREAD

**Issue by ngleich** [yiisoft/yii2#7821]
Hello, there is some unwanted behavior with the ArrayHelper::map method when the $from key is a float number type.

When you have an array of object with a float number type (like price) and you call the this method with this field as the $form, the returned array will truncate this value to an integer.
So, not only the key will be different from the field value, but if there are to instance with the same floor($value) it will only return the latest one in the array.

This issue is base on the php behavior on arrays http://php.net/manual/en/language.types.array.php ( Floats are also cast to integers, which means that the fractional part will be truncated. E.g. the key 8.7 will actually be stored under 8.) so I don't really know if this should be a Yii bug or it should work like this, but I don't thinks it's an appropriate way to work.

If this is not consider a bug, but someone need to work with this floating values as key you can convert them to string with a Closure:
```php
function($model) { return (string)$model->price; }
```
If its consider a bug it could be fix by adding
```php
if(is_int($key)) {
   $result[$key] = $value;
} else {
    $result[(string)$key] = $value;
}
```
to the map method.

What do you think?

**Comment by lynicidn** [comment]
```
 Additionally the following key casts will occur:

    Strings containing valid integers will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
    Floats are also cast to integers, which means that the fractional part will be truncated. E.g. the key 8.7 will actually be stored under 8.
    Bools are cast to integers, too, i.e. the key true will actually be stored under 1 and the key false under 0.
    Null will be cast to the empty string, i.e. the key null will actually be stored under "".
    Arrays and objects can not be used as keys. Doing so will result in a warning: Illegal offset type.
```
http://php.net/manual/en/language.types.array.php

**Comment by qiangxue** [comment]
Could you please use a piece of code to show the error?

**Comment by ngleich** [comment]
Sure, lets have the product class
```php
class Product extends Object {
    public $price;
    public $name;
}
```
And the following instances
```php
$obj1 = new Product([
    'price'=>1.2,
    'name'=>'Product 1'
]);
$obj2 = new Product([
    'price'=>1.5,
    'name'=>'Product 2'
]);
$obj3 = new Product([
    'price'=>3,
    'name'=>'Product 3'
]);
```

So when we call
```php
ArrayHelper::map([$obj1,$obj2,$obj3], 'price', 'name');
```
We get
```php
[
  1 => 'Product 2'
  3 => 'Product 3'
]
```
instead of 
```php
[
  1.2 => 'Product 1',
  1.5 => 'Product 2',
  3 => 'Product 3'
]
```

This last one its not a valid php array (due to the float as key) so maybe a better solution to the return may be the float key cast to string like this:
```php
[
  '1.2' => 'Product 1',
  '1.5' => 'Product 2',
  '3' => 'Product 3'
]
```
This last result can be obtained calling the map method with 

```php
ArrayHelper::map([$obj1,$obj2,$obj3], function($model) { return (string)$model->price; }, 'name');
```

So I'm not sure if this should be consider a bug or just the way php works.

**Comment by SDKiller** [comment]
Not sure `ArrayHelper::map` should force typecasting of keys silently - one may want instead natural php behavior.
As it is said in manual:
> ...
> Strings containing valid integers will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
Floats are also cast to integers, which means that the fractional part will be truncated. E.g. the key 8.7 will actually be stored under 8.
Bools are cast to integers, too, i.e. the key true will actually be stored under 1 and the key false under 0.
Null will be cast to the empty string, i.e. the key null will actually be stored under "".
...
> 

Proposed in https://github.com/yiisoft/yii2/issues/7821#issue-63446562 fix overrides this behavior with on chance to opt out.

**Comment by SDKiller** [comment]
And btw will lead to less informative error messages in last case

> Arrays and objects can not be used as keys. Doing so will result in a warning: Illegal offset type.

Instead of `Illegal offset type` it will produce `method __toString is not implemented` or `array to string conversion`

**Comment by qiangxue** [comment]
I agree with  @SDKiller. We should leave it as is. You can use a callback to achieve what you want. Forcing keys to be strings is not always desirable. In fact, it is more likely you want integer-based keys.
