### ISSUE TITLE
behavior access only ajax

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#7823]
hi, i have a question

how can block in the behavior for give access to the action ONLY by ajax ?

any idea or i need create a custom filter for this case

for example
public function behaviors()
    {
        return [  
            'ajax' => [
                'class' => AjaxFilter::className(),
                'only' => ['action1','action2'],  
            ]
        ];
    }
 and if you try enter with URL like (http://localhost/controller1/action1 you get 403

**Comment by SDKiller** [comment]
Check for `Yii::$app->request->isAjax`

**Comment by spiritdead** [comment]
@SDKiller  i know but is better if we can assign this in the behavior no ?

**Comment by SDKiller** [comment]
Something like this may work

```php
class AjaxFilter extends \yii\base\ActionFilter
{
    public function beforeAction($action)
    {
        if (Yii::$app->request->isAjax) {

            return parent::beforeAction($action);
        }

        throw new BadRequestHttpException();
    }
}
```

**Comment by spiritdead** [comment]
that will be work, i can suggest add a standard filter for yii2 respect this ?

**Comment by spiritdead** [comment]
well if any need this is my class

<?php

namespace common\components\filters;

use Yii;
use yii\base\ActionEvent;
use yii\base\ActionFilter;
use yii\web\Controller;
use yii\web\User;
use yii\di\Instance;
use yii\web\ForbiddenHttpException;

class AjaxAccess extends ActionFilter
{
    /**
     * @var User User for check access.
     */
    private $_user = 'user';

    public $defaultUrl = ['site/index'];

    /**
     * Declares event handlers for the [[owner]]'s events.
     * @return array events (array keys) and the corresponding event handler methods (array values).
     */
    public function events()
    {
        return [Controller::EVENT_BEFORE_ACTION => 'beforeAction'];
    }

    /**
     * Get user
     * @return User
     */
    public function getUser()
    {
        if (!$this->_user instanceof User) {
            $this->_user = Instance::ensure($this->_user, User::className());
        }
        return $this->_user;
    }
    /**
     * Set user
     * @param User|string $user
     */
    public function setUser($user)
    {
        $this->_user = $user;
    }

    /**
     * @param ActionEvent $event
     * @return boolean
     * @throws MethodNotAllowedHttpException when the request method is not allowed.
     */
    public function beforeAction($event)
    {
        $user = $this->getUser();
        $action = $event->controller->id .'/' . $event->id;
        if (Yii::$app->request->isAjax)
            return parent::beforeAction($action);
        else
            $this->denyAccess($user);
    }

    /**
     * Denies the access of the user.
     * The default implementation will redirect the user to the login page if he is a guest;
     * if the user is already logged, a 403 HTTP exception will be thrown.
     * @param Yii\web\User $user the current user
     * @throws Yii\web\ForbiddenHttpException if the user is already logged in.
     */
    protected function denyAccess($user)
    {
        if ($user->getIsGuest()) {
            $user->loginRequired();
        } else {
            $this->ajaxOnly();
        }
    }

    public function ajaxOnly()
    {
        if ($this->defaultUrl !== null) {
            $defUrl = (array)$this->defaultUrl;
            if ($defUrl[0] !== Yii::$app->requestedRoute)
                return Yii::$app->getResponse()->redirect($this->defaultUrl);
        }
        throw new ForbiddenHttpException('Only ajax!');
    }
}

and in the behavior add

'ajax' => [
                'class' => AjaxAccess::className(),
                'only' => ['list']
            ]

**Comment by spiritdead** [comment]
my suggestion is, add a AjaxFilter for define what actions only work in Ajax, can configure in main.php and create a standard for yii2 well is only a idea @qiangxue @samdark 

thx for read this suggestion

**Comment by maximal** [comment]
`AjaxFilter` would be useful, I think. Writing an `if` operator each time the AJAX filtering is needed is a little bit verbose.

**Comment by spiritdead** [comment]
@maximal i know, :P i show a sample in this case

**Comment by Faryshta** [comment]
i propose to use the two already existing filters instead of creating a new one.

```php
'access' => [
    'class' => \yii\filters\AccessControl::className(),
    'only' => ['create', 'update'],
    'rules' => [
        // allow only AJAX requests using the post Method
        [
            'allow' => true,
            'ajax' => true,
            'verbs' => ['POST']
        ],
    ],
]
```

**Comment by sauron918** [comment]
`AjaxFilter` would be really useful
+1

**Comment by ev4ern** [comment]
+1

**Comment by tunecino** [comment]
`beforeAction` can do the trick specially when you also need to do extra stuff with ajax requests like changing the response format:
```php
private $_ajaxOnlyActions = ['create-api'];

public function beforeAction($action) {
    if (!parent::beforeAction($action)) return false;
    foreach ($this->_ajaxOnlyActions as $action) {
        if ($this->action->id === $action) {
            if (Yii::$app->request->isAjax === false)
                throw new \yii\web\BadRequestHttpException();
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        }
    }
    return true;
}
```

**Comment by dynasource** [comment]
limiting access to calls either ajax or non-ajax can be useful. Its so generic that usecases can be thought of. Imagining:
* some pages should not be called without ajax 
* some pages should be called by ajax only

**Comment by MKiselev** [comment]
My solution, just check isAjax in `matchCallback`.

```php
public function behaviors()
{
    return [
        'access' => [
            'class' => 'yii\filters\AccessControl',
            'only' => ['buy-validate', 'buy'],
            'rules' => [
                // allow only AJAX requests using the post Method
                [
                    'allow' => true,
                    'verbs' => ['POST'],
                    'matchCallback' => function () {
                        return Yii::$app->request->getIsAjax();
                    },
                ],
            ],
        ],
    ];
}
```

**Comment by MKiselev** [comment]
Because for use `yii\filters\AccessControl` need user component and in some use case this component was may not be, you must write your filter like this => https://github.com/yiisoft/yii2/issues/4793#issuecomment-292174430
