### ISSUE TITLE
yii\grid\ActionColumn generate url assume primary column to "id" 

### ISSUE THREAD

**Issue by ryusoft** [yiisoft/yii2#7826]
```PHP
    public function createUrl($action, $model, $key, $index)
    {
        if ($this->urlCreator instanceof Closure) {
            return call_user_func($this->urlCreator, $action, $model, $key, $index);
        } else {
            $params = is_array($key) ? $key : ['id' => (string) $key];
            $params[0] = $this->controller ? $this->controller . '/' . $action : $action;
            return Url::toRoute($params);
        }
    }
```

this line:
$params = is_array($key) ? $key : ['id' => (string) $key];

will it be good to get the primary columns name instead of hard coded it?

**Comment by cebe** [comment]
this is in line how gii generates the parameter name for an action. if it is a single primary key the action parameter name will be 'id'. If it is a composite key, the name will be like the models key names.

**Comment by ryusoft** [comment]
what is the primary key column is not "id" for example "code", and is not composite key
