### ISSUE TITLE
yiisoft/mongodb SASL Authentication 

### ISSUE THREAD

**Issue by xiandalisay** [yiisoft/yii2#7827]
I got an error
Caused by: MongoConnectionException
Failed to connect to: localhost:27017: SASL Authentication failed on database 'local': Authentication failed.

I explicitly declared the database name 'local' to be used for the connection.
I inserted the session component into the backend\config\main.php.
I tried to test the connection using MongoDB shell AdminUIs. The connection works and the database was accessed.

![capture](https://cloud.githubusercontent.com/assets/7392803/6768809/d99b5dd4-d0ba-11e4-89dd-55b0b2291a64.PNG)

**Comment by klimov-paul** [comment]
@xiandalisay, can you successfully connect to your database using plain PHP mongo extension?

**Comment by xiandalisay** [comment]
Yes, I can connect to my database. I am using WAMP windows. and rockmongo for UI.

![capture](https://cloud.githubusercontent.com/assets/7392803/6779127/c11e5a2a-d193-11e4-8528-e7671c54c95b.PNG)

**Comment by xiandalisay** [comment]
i used the following code. from the issue 5303 mongodb\Connection not understand dsn

'mongodb' => [
            'class' => 'yii\mongodb\Connection',
            'dsn'=> 'mongodb://localhost/database?connectTimeoutMS=300000',
            'defaultDatabaseName' => 'database', // Avoid autodetection of default database name
        ],

it works now. But the code on the docs, for the dbconnection does not work. Why is that?

**Comment by klimov-paul** [comment]
Issue about parameters in DSN has been resolved long ago: #5303
Which version of 'yii2-mongodb' you are using?

**Comment by klimov-paul** [comment]
What exactly your problematic DSN is?

**Comment by xiandalisay** [comment]
The issue is now solved. Thank you.

**Comment by tangniyuqi** [comment]
How do you solve？
