### ISSUE TITLE
Remove jquery composer package

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#7828]
https://github.com/yiisoft/jquery isn't used and could be removed.

**Comment by cebe** [comment]
thats not really true: 52 installs today. https://packagist.org/packages/yiisoft/jquery

**Comment by cebe** [comment]
should be marked as abandoned on packagist for some time and then removed.

**Comment by samdark** [comment]
52 installs... weird.

**Comment by samdark** [comment]
@qiangxue can you mark it as abandoned?

**Comment by qiangxue** [comment]
Done.
