### ISSUE TITLE
apps and extensions deleted from the repo

### ISSUE THREAD

**Issue by softark** [yiisoft/yii2#7829]
Probably by a sheer mistake.

**Comment by softark** [comment]
Ah, ok. I was wrong.
They have been divided to the individual repos.

**Comment by softark** [comment]
But you have to exclude the unit tests for the extensions from the main repo.

**Comment by samdark** [comment]
Yes, it's in the plan.

**Comment by cebe** [comment]
@softark see #7812

**Comment by softark** [comment]
Oh, I didn't notice that.
Thank you
