### ISSUE TITLE
Schema detects tables without explicit order

### ISSUE THREAD

**Issue by nineinchnick** [yiisoft/yii2#7831]
The `pgsql\Schema.findTables`, `pgsql\Schema.findConstraints` and possibly `Schema` for other databases does not fetch table names with explicit order. Since the default order may change randomly, gii would produce different results for relations where numbers are appended to the name.

**Comment by cebe** [comment]
how is this a problem? you would not keep the name like that anyway, would you?

**Comment by nineinchnick** [comment]
I hurried a bit with creating the issue, I'm going to verify it more thoroughly and reopen if necessary.

**Comment by nineinchnick** [comment]
You got a point that relation methods should be corrected manually, but I still think it is an issue and table names should be returned sorted and consistent.

**Comment by nineinchnick** [comment]
I found a bug in `findConstraints` where composite fkeys would be randomly assigned to table columns. This should be probably fixed for other schemas, not only PostgreSQL.

**Comment by nineinchnick** [comment]
Found another one in `mssql` schema, composite fks are not supported at all. Should I try to fix it? I could only run it on sqlfiddle.
