### ISSUE TITLE
Schema support for views

### ISSUE THREAD

**Issue by nineinchnick** [yiisoft/yii2#7833]
Should `Schema.findTableNames` also return views? In PostgreSQL, [simple views are updatable since 9.3](http://www.postgresql.org/docs/9.3/static/sql-createview.html#SQL-CREATEVIEW-UPDATABLE-VIEWS), but even read-only ones could have models.

If yes, then also foreign tables should be supported.

**Comment by samdark** [comment]
Yes, it should.

**Comment by nineinchnick** [comment]
I could look into other databases to have everything in one PR.

**Comment by samdark** [comment]
Yeah, that would be great.

**Comment by nineinchnick** [comment]
I've updated my PR. I've added support for views for pgsql, mssql and oci. Mysql, cubrid and sqlite already listed views.

**Comment by nineinchnick** [comment]
@samdark done with tests, see PR comments for more info.
