### ISSUE TITLE
Inconsistent namespaces for backend unit tests

### ISSUE THREAD

**Issue by juan88** [yiisoft/yii2#7835]
Hi, I've seen that there is an inconsistency of namespaces in the yii2-advanced app template.

in tests/codeception/backend/unit/TestCase.php and tests/codeception/backend/unit/DbTestCase.php the namespace defined is backend\tests\unit whereas in the the same section but for frontend tests the namespace is defined as tests\codeception\frontend\unit.

And I cannot use that class in my backend/unit/TestXXX, the following error is displayed when running codecept run for that test

PHP Fatal error:  Class 'backend\tests\unit\TestCase' not found in /vagrant/tests/codeception/backend/unit/TestXXX

Hope this helps! Thanks!

**Comment by nestorvanz** [comment]
Is this bug solved? You don't mention nothing about it in the milestone.

**Comment by lynicidn** [comment]
tests in vargant folder not exists

**Comment by samdark** [comment]
The extension was deprecated so if the issue is still valid when using http://codeception.com/for/yii then it should be reported once again.
