### ISSUE TITLE
Yii::$app null when trying to access ActiveRecord functionality from a Unit test

### ISSUE THREAD

**Issue by juan88** [yiisoft/yii2#7836]
Hi!
I'm writing a unit test for a class that needs some validation to be done against the database (fetching a record) and the following is happening to me when running the codeception run test command.

PHP  19. common\models\Product::findOrCreateByCode() /vagrant/backend/models/ProductFileForm.php:59
PHP  20. yii\db\ActiveQuery->one() /vagrant/common/models/Product.php:119
PHP  21. yii\db\Query->one() /vagrant/vendor/yiisoft/yii2/db/ActiveQuery.php:285
PHP  22. yii\db\ActiveQuery->createCommand() /vagrant/vendor/yiisoft/yii2/db/Query.php:243
PHP  23. yii\db\ActiveRecord::getDb() /vagrant/vendor/yiisoft/yii2/db/ActiveQuery.php:305

Fatal error: Call to a member function getDb() on a non-object in /vagrant/vendor/yiisoft/yii2/db/ActiveRecord.php on line 133

It seems that Yii::$app is null. No additional configuration has been applied except the one that came by default from the yii2-advanced template and what is recommended in the README.md in the test folder.

I think it should be expected this to not be null, or if that's the case there should be a way to config it in an easy way. Plus, I could not find much documentation on how to achieve this.

Thanks!

**Comment by lynicidn** [comment]
check test config

**Comment by samdark** [comment]
In case of unit tests it's your responsibility to create application instance.

**Comment by juan88** [comment]
Thanks for the quick reply. 
Is it something not expected to be done or is common practice to create an app instance? And in that case, could you give me some directions on how to do so in this case? Thanks again.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L36

**Comment by fernandezekiel** [comment]
https://github.com/yiisoft/yii2/blob/master/tests/unit/TestCase.php#L54
this is what Yii uses, you can base it here
