### ISSUE TITLE
IsAjax of request

### ISSUE THREAD

**Issue by Heddy147** [yiisoft/yii2#7838]
Hi,

I have a question about the property "isAjax" of the "Request"-object.

I use AngularJS to build my view including the routing and templates. When Angular send a request to get the template, the property "isAjax" of "Request" doesn't contain true but false.

What should I do to get the right value?

Thanks.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L307
