### ISSUE TITLE
Undefined offset: 0 error in yii2/db/Command.php at line 318

### ISSUE THREAD

**Issue by olivebranches** [yiisoft/yii2#7840]
for($i=1;$i<=$this->total_semesters;$i++)
         {
          $program_sem_ay->open_sem_date = $this->open_sem_date[$i];
            $program_sem_ay->close_sem_date = $this->close_sem_date[$i];
            $program_sem_ay->final_exam = $this->final_exam_date[$i];
            $program_sem_ay->final_exam_results_date = $this->final_exam_results_date[$i];
 
            if($program_sem_ay->save()){}
        }

Here open_sem_date, close_sem_date are array variables in model file. The form is rendered from view and the user gets to enter the form.  I am getting following error

public function bindValues($values)
    {
        if (empty($values)) {
            return $this;
        }
 
        foreach ($values as $name => $value) {
            if (is_array($value)) {
                $this->_pendingParams[$name] = $value;
                $this->params[$name] = $value[0];  //error comes from this line
            } else {
                $type = $this->db->getSchema()->getPdoType($value);
                $this->_pendingParams[$name] = [$value, $type];
                $this->params[$name] = $value;
            }
        }
 
        return $this;
    }

Where am I wrong?

**Comment by samdark** [comment]
Do you have `0` index in the array used?

**Comment by arjunweb** [comment]
array(2) {
  [0]=>
  array(0) {
  }
  [1]=>
  array(1) {
    [0]=>
    object(frontend\models\Questions)#130 (8) {
      ["_attributes":"yii\db\BaseActiveRecord":private]=>
      array(10) {
        ["id"]=>
        int(1)
        ["lesson_id"]=>
        int(2)
        ["question"]=>
        string(13) "what is jav.?"
        ["answer"]=>
        string(1) "A"
        ["options"]=>
        string(90) "high level programming language,low level language,assembley level language,normal languag"
        ["grade"]=>
        int(2)
        ["created_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["created_by"]=>
        int(25)
        ["updated_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["updated_by"]=>
        int(25)
      }
      ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
      array(10) {
        ["id"]=>
        int(1)
        ["lesson_id"]=>
        int(2)
        ["question"]=>
        string(13) "what is jav.?"
        ["answer"]=>
        string(1) "A"
        ["options"]=>
        string(90) "high level programming language,low level language,assembley level language,normal languag"
        ["grade"]=>
        int(2)
        ["created_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["created_by"]=>
        int(25)
        ["updated_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["updated_by"]=>
        int(25)
      }
      ["_related":"yii\db\BaseActiveRecord":private]=>
      array(0) {
      }
      ["_errors":"yii\base\Model":private]=>
      NULL
      ["_validators":"yii\base\Model":private]=>
      NULL
      ["_scenario":"yii\base\Model":private]=>
      string(7) "default"
      ["_events":"yii\base\Component":private]=>
      array(0) {
      }
      ["_behaviors":"yii\base\Component":private]=>
      array(0) {
      }
    }
  }
}

**Comment by arjunweb** [comment]
getting undefined offset 0
yii2


array(2) {
  [0]=>
  array(0) {
  }
  [1]=>
  array(1) {
    [0]=>
    object(frontend\models\Questions)#130 (8) {
      ["_attributes":"yii\db\BaseActiveRecord":private]=>
      array(10) {
        ["id"]=>
        int(1)
        ["lesson_id"]=>
        int(2)
        ["question"]=>
        string(13) "what is jav.?"
        ["answer"]=>
        string(1) "A"
        ["options"]=>
        string(90) "high level programming language,low level language,assembley level language,normal languag"
        ["grade"]=>
        int(2)
        ["created_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["created_by"]=>
        int(25)
        ["updated_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["updated_by"]=>
        int(25)
      }
      ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
      array(10) {
        ["id"]=>
        int(1)
        ["lesson_id"]=>
        int(2)
        ["question"]=>
        string(13) "what is jav.?"
        ["answer"]=>
        string(1) "A"
        ["options"]=>
        string(90) "high level programming language,low level language,assembley level language,normal languag"
        ["grade"]=>
        int(2)
        ["created_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["created_by"]=>
        int(25)
        ["updated_at"]=>
        string(19) "2018-02-19 12:31:49"
        ["updated_by"]=>
        int(25)
      }
      ["_related":"yii\db\BaseActiveRecord":private]=>
      array(0) {
      }
      ["_errors":"yii\base\Model":private]=>
      NULL
      ["_validators":"yii\base\Model":private]=>
      NULL
      ["_scenario":"yii\base\Model":private]=>
      string(7) "default"
      ["_events":"yii\base\Component":private]=>
      array(0) {
      }
      ["_behaviors":"yii\base\Component":private]=>
      array(0) {
      }
    }
  }
}
how to solve this...!
please any ideas..?
