### ISSUE TITLE
RBAC & Data Permissions

### ISSUE THREAD

**Issue by saada** [yiisoft/yii2#7845]
Is there a suggested way to protect data using RBAC.
For example, I want Managers and Customers to have the same permission, let's call it "ViewOrder". Now I want a group of customers to view that order but not other orders. 

- How do I setup a rule to handle that case? 
- What if I want to add more people to that group of customers?
- What if I want some users to view ALL orders?
- Do I need to create my own tables to handle this or can RBAC help somehow?

Is there a suggested way to do this?

**Comment by samdark** [comment]
RBAC is able to handle all that. Ask at the forum and you'll get answers. Github is for issue reports and feature requests.

**Comment by saada** [comment]
Forum post:
http://www.yiiframework.com/forum/index.php/topic/62730-rbac-data-permissions/
