### ISSUE TITLE
set_locale() and db/ColumnSchema decimal bug while using comma as a decimal separator with DECIMAL columns

### ISSUE THREAD

**Issue by bviolier** [yiisoft/yii2#7847]
We are currently working on a multilingual website with Yii2. Everything is great except that we are running into some database issues when using setlocale(LC_ALL, $language). 

The problems occur when we are using a locale that uses the comma as decimal seperator (nl_NL for instance). The problems do not occur when a country is used that has a point as decimal seperator. For example:

````php
// The BAD
setlocale(LC_ALL, 'nl_NL');

$model = new Model();
$model->decimal_column = 0.1; // DECIMAL(9,8)
$model->save();

$model->refresh();

var_dump($model->decimal_column); // 0.00000000
````

VS

````php
// The GOOD
setlocale(LC_ALL, 'en_US');

$model = new Model();
$model->decimal_column = 0.1; // DECIMAL(9,8)
$model->save();

$model->refresh();

var_dump($model->decimal_column); // 0.10000000
````

The problem seems to be that db/ColumnSchema->phpTypecast is using (string) to cast a DECIMAL MySQL column.

/vendor/yiisoft/yii2/db/ColumnSchema.php:97
````php
        // $this->type = 'decimal'
        // $this->phpType = 'string'

        switch ($this->phpType) {
            case 'resource':
            case 'string':
                return is_resource($value) ? $value : (string) $value;
            case 'integer':
                return (int) $value;
            case 'boolean':
                return (bool) $value;
            case 'double':
                return (double) $value;
        }
````

When the save is called on an activerecord, the db/ColumnSchema->phpTypecast parses a column that needs to be DECIMAL with (string). The value coming out of the STRING parse is directly used in the MySQL INSERT (or UPDATE). When 0.1 is parsed as string when en_US is the locale, the result is 0.1 - which MySQL processes corretly, but when nl_NL is used as the locale, the result is 0,1 - which MySQL processes as 0. So data is corrupted. See:

````php
setlocale(LC_ALL, 'en_US');
var_dump((string) 0.1); // 0.1

setlocale(LC_ALL, 'nl_NL');
var_dump((string) 0.1); // 0,1
````

Is this expected behaviour and shouldn't I use set_locale()? Or is this a bug that needs to be fixed.
PS. This is before the refactoring of ColumnSchema->setType()

**Comment by nineinchnick** [comment]
This does look like a bug, but when I was thinking about how to properly cast numbers to string when there is precision/scale defined for them in the db I thought you shouldn't store numbers with fixed precision as doubles in PHP in the first place. In some corner cases they will have to be rounded to the fixed precision.

**Comment by nineinchnick** [comment]
After quick googling it looks like all DB's expect numbers with a dot as a decimal separator, regardless of locale. 

I was thinking about using `number_format()` when `scale` is set but following (PostgreSQL docs on numeric)[http://www.postgresql.org/docs/9.1/static/datatype-numeric.html] there can be `NUMERIC` db type without scale. In other cases the db performs rounding and typechecking itself, so it's not necessary to be too precise here.

So it's just about casting to string with a constant dot decimal separator.

**Comment by bviolier** [comment]
Your findings seem indeed to be correct. Thanks for researching the issue.
A temporary fix for us would be to check if the $this->type === 'decimal' and then do a str_replace(",", "." $value) after the (string).

And I'm not sure I following your PostgreSQL comment. Wouldn't it be possible to always use number_format according to the scale variable? In the case of a numeric without scale, the decimal count would be 0.

**Comment by nineinchnick** [comment]
It's not only decimal. All numeric types needs to be detected properly. I think a str_replace() is sufficient here.

From the PostgreSQL manual:

> Specifying: `NUMERIC` without any precision or scale creates a column in which numeric values of any precision and scale can be stored, up to the implementation limit on precision. A column of this kind will not coerce input values to any particular scale, whereas numeric columns with a declared scale will coerce input values to that scale. (The SQL standard requires a default scale of 0, i.e., coercion to integer precision. We find this a bit useless. If you're concerned about portability, always specify the precision and scale explicitly.)


So I'd say we shouldn't do any kind of rounding and leave it to the db.
