### ISSUE TITLE
Call to undefined method Swift_Mailer::newInstance()

### ISSUE THREAD

**Issue by alexberriman** [yiisoft/yii2#7848]
This is during a recent composer update with a minimum stability of dev. I believe it's because swiftmailer recently moved to the 6.x-dev branch, which removes the newInstance() methods:

https://github.com/swiftmailer/swiftmailer/commit/5a0199b1ac8409791086098557da53b1cc92fc04

Instead of calling the newInstance() method, you just have to instantiate the class:

```return new \Swift_Mailer($this->getTransport());```

I'll try to fork it and issue a pull request if I get time throughout the day and it hasn't been resolved.

**Comment by samdark** [comment]
Duplicate of https://github.com/yiisoft/yii2-swiftmailer/pull/2.
