### ISSUE TITLE
Proposal: yii\base\Widget visible option

### ISSUE THREAD

**Issue by disem** [yiisoft/yii2#7852]
As widgets used mostly for partial content it will be great to have an option for enabling/disabling widgets without writing own if/switch wrappers, i think new public ```$visible``` should be introduced. It could take boolean or callable as an value and should be checked in ```widget()``` method before executing ```run()```. 

```php
<?php echo ProfileCompletion::widget([
    'visible' => !empty($model) ? true : false,
]); ?>
```

```php
public $allowedControllers = ['profile', 'etc'];
/**
* Managing visibility depending on something
*/
public function init()
{
    $this->visible = in_array($this->view->context->controller->id, $this->allowedControllers);
   // or
    $this->visible = function() {
       return app\models\SomeModel::someFunction();
    }
}
```

**Comment by samdark** [comment]
Personally I prefer `if`s.

**Comment by lynicidn** [comment]
hm, imho not needed:
```php
if (empty($model)) {
    echo ProfileCompletion::widget([]);
}
```

**Comment by disem** [comment]
I agree that described case can be used with simple if, but it was given for example only.
Case that caused me to propose this option more complex. I have sidebar that placed on every website page with lot of widgets which should be visible or not depending on users role and controller/action.
Now i need wrap every widget with complex if cases or rewrite all widgets to add needed checks, but with this option that will be part of widget configuration. It will be easier to understand and support code if visability is part of configuration, not wrapper.

**Comment by lynicidn** [comment]
best way enter `role` property as access rule, for rbac check

**Comment by disem** [comment]
Access rules used for preventing access to actions, but there could be same pages for all roles with some diferences like widgets. I don't think it will be good solution to make all variations of pages for diferent roles.

**Comment by lynicidn** [comment]
> I don't think it will be good solution to make all variations of pages for diferent roles.

what? i don't write it

**Comment by lynicidn** [comment]
role is also bad idea accept it

**Comment by lynicidn** [comment]
@disem in ur case need do it before init only - next cases can containts errors, also script register is confuse. How cancel run method in init?

**Comment by lynicidn** [comment]
я тут узнал, что беседуют русскоговорящие, изложу по русски
duplicate (translate from upper comment):
Смысл что виджет запускается 2 точками init и run, в твоем предложенном варианте, мы не должны отображать виджет, но поймем мы это только в инит, следовательно скрипты js, css будут зарегистрированы - но зачем? и как нам прервать инит, чтобы не было проблем с "недостаточностью" входных данных, которые повлияли на visible?

мое мнение: ничего менять не стоит, ifы справляются на отлично, как с логической стороны, так и со стороны нагромождения кода - оно минимально

**Comment by cebe** [comment]
You can add this option to your sidebar widget yourself but it does not seem to be a general enough concept to introduce this in the framework.
