### ISSUE TITLE
PHP Warning – yii\base\ErrorException  register_shutdown_function(): Invalid shutdown callback '' passed

### ISSUE THREAD

**Issue by JiangYahui** [yiisoft/yii2#7855]
register_shutdown_function(): Invalid shutdown callback '' passed
1. in /usr/local/nginx/tcms/vendor/yiisoft/yii2/log/Logger.php

    /**
     * Initializes the logger by registering [[flush()]] as a shutdown function.
     */
    public function init()
    {
        parent::init();
        register_shutdown_function(function () {
            // make sure "flush()" is called last when there are multiple shutdown functions
            register_shutdown_function([$this, 'flush'], true);
        });
    }
 
    /**
     * Logs a message with the given type and category.
     * If [[traceLevel]] is greater than 0, additional call stack information about
     * the application code will be logged as well.
     * @param string|array $message the message to be logged. This can be a simple string or a more
     * complex data structure that will be handled by a [[Target|log target]].
     * @param integer $level the level of the message. This must be one of the following:

**Comment by JiangYahui** [comment]
php version : 5.4.30

**Comment by lynicidn** [comment]
it's recursie ?

**Comment by lynicidn** [comment]
register_shutdown_function into register_shutdown_function

**Comment by cebe** [comment]
unable to reproduce, also no problem here: http://3v4l.org/4KB60

please provide more information about environment and stack trace.

**Comment by JiangYahui** [comment]
I don't know what is wrong ， tcms.127n.com 

system: centOS 6 
php: v5.4.30

**Comment by lynicidn** [comment]
how u detect php version ? php can have other version then php-cli

**Comment by cebe** [comment]
@JiangYahui stacktrace would be very helpful

**Comment by qvink** [comment]
@cebe I have the same problem. 
system : centOS 6.3 
php 5.4.39 (yum install)

**Comment by samdark** [comment]
@qvink stacktrace?

**Comment by qvink** [comment]
debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS) result :
Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/base/Object.php
    [line] => 107
    [function] => init
    [class] => yii\log\Logger
    [type] => ->
)


Array
(
    [function] => __construct
    [class] => yii\base\Object
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 366
    [function] => newInstanceArgs
    [class] => ReflectionClass
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 151
    [function] => build
    [class] => yii\di\Container
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 340
    [function] => get
    [class] => yii\di\Container
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 364
    [function] => createObject
    [class] => yii\BaseYii
    [type] => ::
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/log/Dispatcher.php
    [line] => 115
    [function] => getLogger
    [class] => yii\BaseYii
    [type] => ::
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/log/Dispatcher.php
    [line] => 87
    [function] => getLogger
    [class] => yii\log\Dispatcher
    [type] => ->
)


Array
(
    [function] => __construct
    [class] => yii\log\Dispatcher
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 372
    [function] => newInstanceArgs
    [class] => ReflectionClass
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 151
    [function] => build
    [class] => yii\di\Container
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 344
    [function] => get
    [class] => yii\di\Container
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/ServiceLocator.php
    [line] => 133
    [function] => createObject
    [class] => yii\BaseYii
    [type] => ::
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/base/Application.php
    [line] => 302
    [function] => get
    [class] => yii\di\ServiceLocator
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/web/Application.php
    [line] => 63
    [function] => bootstrap
    [class] => yii\base\Application
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/base/Application.php
    [line] => 267
    [function] => bootstrap
    [class] => yii\web\Application
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/base/Object.php
    [line] => 107
    [function] => init
    [class] => yii\base\Application
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/base/Application.php
    [line] => 206
    [function] => __construct
    [class] => yii\base\Object
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/backend/web/index.php
    [line] => 17
    [function] => __construct
    [class] => yii\base\Application
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/base/Object.php
    [line] => 107
    [function] => init
    [class] => yii\log\Logger
    [type] => ->
)


Array
(
    [function] => __construct
    [class] => yii\base\Object
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 366
    [function] => newInstanceArgs
    [class] => ReflectionClass
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 151
    [function] => build
    [class] => yii\di\Container
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 340
    [function] => get
    [class] => yii\di\Container
    [type] => ->
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 364
    [function] => createObject
    [class] => yii\BaseYii
    [type] => ::
)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php

**Comment by qvink** [comment]
@samdark  

and debug_backtrace() result : 

Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/base/Object.php
    [line] => 107
    [function] => init
    [class] => yii\log\Logger
    [object] => yii\log\Logger Object
        (
            [messages] => Array
                (
                )

            [flushInterval] => 1000
            [traceLevel] => 0
            [dispatcher] => 
            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
        )

)


Array
(
    [function] => __construct
    [class] => yii\base\Object
    [object] => yii\log\Logger Object
        (
            [messages] => Array
                (
                )

            [flushInterval] => 1000
            [traceLevel] => 0
            [dispatcher] => 
            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
            [0] => Array
                (
                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 366
    [function] => newInstanceArgs
    [class] => ReflectionClass
    [object] => ReflectionClass Object
        (
            [name] => yii\log\Logger
        )

    [type] => ->
    [args] => Array
        (
            [0] => Array
                (
                    [0] => Array
                        (
                        )

                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 151
    [function] => build
    [class] => yii\di\Container
    [object] => yii\di\Container Object
        (
            [_singletons:yii\di\Container:private] => Array
                (
                )

            [_definitions:yii\di\Container:private] => Array
                (
                )

            [_params:yii\di\Container:private] => Array
                (
                )

            [_reflections:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => ReflectionClass Object
                        (
                            [name] => yii\web\ErrorHandler
                        )

                    [yii\web\Request] => ReflectionClass Object
                        (
                            [name] => yii\web\Request
                        )

                    [yii\log\Dispatcher] => ReflectionClass Object
                        (
                            [name] => yii\log\Dispatcher
                        )

                    [yii\log\Logger] => ReflectionClass Object
                        (
                            [name] => yii\log\Logger
                        )

                )

            [_dependencies:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\web\Request] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Dispatcher] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Logger] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                )

            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
            [0] => yii\log\Logger
            [1] => Array
                (
                )

            [2] => Array
                (
                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 340
    [function] => get
    [class] => yii\di\Container
    [object] => yii\di\Container Object
        (
            [_singletons:yii\di\Container:private] => Array
                (
                )

            [_definitions:yii\di\Container:private] => Array
                (
                )

            [_params:yii\di\Container:private] => Array
                (
                )

            [_reflections:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => ReflectionClass Object
                        (
                            [name] => yii\web\ErrorHandler
                        )

                    [yii\web\Request] => ReflectionClass Object
                        (
                            [name] => yii\web\Request
                        )

                    [yii\log\Dispatcher] => ReflectionClass Object
                        (
                            [name] => yii\log\Dispatcher
                        )

                    [yii\log\Logger] => ReflectionClass Object
                        (
                            [name] => yii\log\Logger
                        )

                )

            [_dependencies:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\web\Request] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Dispatcher] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Logger] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                )

            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
            [0] => yii\log\Logger
            [1] => Array
                (
                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 364
    [function] => createObject
    [class] => yii\BaseYii
    [type] => ::
    [args] => Array
        (
            [0] => yii\log\Logger
        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/log/Dispatcher.php
    [line] => 115
    [function] => getLogger
    [class] => yii\BaseYii
    [type] => ::
    [args] => Array
        (
        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/log/Dispatcher.php
    [line] => 87
    [function] => getLogger
    [class] => yii\log\Dispatcher
    [object] => yii\log\Dispatcher Object
        (
            [targets] => Array
                (
                )

            [_logger:yii\log\Dispatcher:private] => 
            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
        )

)


Array
(
    [function] => __construct
    [class] => yii\log\Dispatcher
    [object] => yii\log\Dispatcher Object
        (
            [targets] => Array
                (
                )

            [_logger:yii\log\Dispatcher:private] => 
            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
            [0] => Array
                (
                    [traceLevel] => 3
                    [targets] => Array
                        (
                            [0] => Array
                                (
                                    [class] => yii\log\FileTarget
                                    [levels] => Array
                                        (
                                            [0] => error
                                            [1] => warning
                                        )

                                )

                        )

                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 372
    [function] => newInstanceArgs
    [class] => ReflectionClass
    [object] => ReflectionClass Object
        (
            [name] => yii\log\Dispatcher
        )

    [type] => ->
    [args] => Array
        (
            [0] => Array
                (
                    [0] => Array
                        (
                            [traceLevel] => 3
                            [targets] => Array
                                (
                                    [0] => Array
                                        (
                                            [class] => yii\log\FileTarget
                                            [levels] => Array
                                                (
                                                    [0] => error
                                                    [1] => warning
                                                )

                                        )

                                )

                        )

                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/Container.php
    [line] => 151
    [function] => build
    [class] => yii\di\Container
    [object] => yii\di\Container Object
        (
            [_singletons:yii\di\Container:private] => Array
                (
                )

            [_definitions:yii\di\Container:private] => Array
                (
                )

            [_params:yii\di\Container:private] => Array
                (
                )

            [_reflections:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => ReflectionClass Object
                        (
                            [name] => yii\web\ErrorHandler
                        )

                    [yii\web\Request] => ReflectionClass Object
                        (
                            [name] => yii\web\Request
                        )

                    [yii\log\Dispatcher] => ReflectionClass Object
                        (
                            [name] => yii\log\Dispatcher
                        )

                    [yii\log\Logger] => ReflectionClass Object
                        (
                            [name] => yii\log\Logger
                        )

                )

            [_dependencies:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\web\Request] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Dispatcher] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Logger] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                )

            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
            [0] => yii\log\Dispatcher
            [1] => Array
                (
                )

            [2] => Array
                (
                    [traceLevel] => 3
                    [targets] => Array
                        (
                            [0] => Array
                                (
                                    [class] => yii\log\FileTarget
                                    [levels] => Array
                                        (
                                            [0] => error
                                            [1] => warning
                                        )

                                )

                        )

                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/BaseYii.php
    [line] => 344
    [function] => get
    [class] => yii\di\Container
    [object] => yii\di\Container Object
        (
            [_singletons:yii\di\Container:private] => Array
                (
                )

            [_definitions:yii\di\Container:private] => Array
                (
                )

            [_params:yii\di\Container:private] => Array
                (
                )

            [_reflections:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => ReflectionClass Object
                        (
                            [name] => yii\web\ErrorHandler
                        )

                    [yii\web\Request] => ReflectionClass Object
                        (
                            [name] => yii\web\Request
                        )

                    [yii\log\Dispatcher] => ReflectionClass Object
                        (
                            [name] => yii\log\Dispatcher
                        )

                    [yii\log\Logger] => ReflectionClass Object
                        (
                            [name] => yii\log\Logger
                        )

                )

            [_dependencies:yii\di\Container:private] => Array
                (
                    [yii\web\ErrorHandler] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\web\Request] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Dispatcher] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                    [yii\log\Logger] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                )

            [_events:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => 
        )

    [type] => ->
    [args] => Array
        (
            [0] => yii\log\Dispatcher
            [1] => Array
                (
                )

            [2] => Array
                (
                    [traceLevel] => 3
                    [targets] => Array
                        (
                            [0] => Array
                                (
                                    [class] => yii\log\FileTarget
                                    [levels] => Array
                                        (
                                            [0] => error
                                            [1] => warning
                                        )

                                )

                        )

                )

        )

)


Array
(
    [file] => /home/dev/yii2/vendor/yiisoft/yii2/di/ServiceLocator.php
    [line] => 133
    [function] => createObject
    [class] => yii\BaseYii
    [type] => ::
    [args] => Array
        (
            [0] => Array
                (
                    [traceLevel] => 3
                    [targets] => Array
                        (
                            [0] => Array
                                (
                                    [class] => yii\log\FileTarget
                                    [levels] => Array
                                        (
                                            [0] => error
                                            [1] => warning
                                        )

                                )

                        )

                    [class] => yii\log\Dispatcher
                )

        )
)

....need more info ?

**Comment by lynicidn** [comment]
>....need more info ?

https://help.github.com/enterprise/11.10.340/user/articles/markdown-basics/

**Comment by qvink** [comment]
I found the problem.  eAccelerator not compatible with anonymous function . After disabled eAccelerator, everything go well.

**Comment by samdark** [comment]
That explains it.
