### ISSUE TITLE
Duplicated config file for i18n

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#7857]
The files `framework/messages/config.php` and `framework/views/messageConfig.php` look too similar and I suspect one of them isn't needed.

Also, they slightly differ on some lines; it's like one of them is an "old" version of the other one.

**Comment by lynicidn** [comment]
first it file for grub yii-core translates, secondary for generate standard template. It's correct.

**Comment by samdark** [comment]
Wrong. `framework/views/messageConfig.php` is template for creating your own config file. `framework/messages/config.php` is actual config for translating framework messages.

**Comment by alexandernst** [comment]
@samdark @lynicidn Yes, that I understand. But what I'm not really sure is why they differ on some lines. I mean, shouldn't the template have all the options that the "normal" config file has?

**Comment by samdark** [comment]
What's missing?

**Comment by alexandernst** [comment]
@samdark `messages/config.php` is missing `messageTable` and `catalog` entries.

**Comment by samdark** [comment]
`messages/config.php` is a real config that doesn't use database. There's no need to have these in it.
