### ISSUE TITLE
Problem sending files witn \yii\web\Response::xSendFile

### ISSUE THREAD

**Issue by m-jimlittle** [yiisoft/yii2#7858]
I think that xSendFile should set the response format to FORMAT_RAW as do the sendFile, sendContentAsFile and sendContentAsFile methods.

The current implementation does not respect the mime type of the file being send as the "Content-Type" response header is always set to "text/html" since the default response format is set to FORMAT_HTML.

**Comment by samdark** [comment]
It's a bug in 2.0.3 that's already fixed in master.

**Comment by yapi68** [comment]
@samdark It does not seems to be fixed. Response format still "html". I have latest version 2.0.3. Please check function `xSendFile` in `\yii\web\Response` (line 684) - function returns Response object, but `$this->format = self::FORMAT_RAW` does not set.

**Comment by samdark** [comment]
Have you checked if it is actually broken?

**Comment by samdark** [comment]
As I've commented, 2.0.3 has this bug. It is already fixed and will be released with 2.0.4.

**Comment by yapi68** [comment]
@samdark Ok, no problem. Thanks.
