### ISSUE TITLE
Automatic assets compress

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#7860]
I'm reading http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#combining-and-compressing-assets and while using the way described in the guide lets you do pretty much anything you want, I'm missing the "Yii way" in it (aka "the easy way). 

It would be nice if the assets manager could detect the right order/dependency of each asset registed by the view of the current request and then compile/compress everything into a single file (1 file for every registered `.css` and 1 file for every registered `.js`).

That way the request "A" (which depends on assets I, J and K), would get `asset-A.IJK.js` and `asset-A.IJK.css` and the request "B" (which depends on assets Y and Z), would get `asset-B.YZ.js` and `asset-B.YZ.css` in a completely transparent way for both the end user and the developer.

**Comment by Sammaye** [comment]
Wouldn't that mean a compression per view, maybe even request if the code is user dependant?

**Comment by alexandernst** [comment]
No for the "per request". A view will always have the same registered assets. Say for example the view of a blog post (typical blog-app example). The view of a blog post would probably depend on `global.css`, `fonts.css` and `post.css` for the CSS files, and `post.js` and `global.js` for the JS files. That won't change per request, only per view (the view of a list of posts for example would have different assets).

Anyways, even if the assets changed per request basis, the developer would still need to do "a lot of" :tm: stuff, instead of just saying to Yii "Hey, take care of all the assets for each view".

**Comment by klimov-paul** [comment]
Such way is unefficient, it requires extra computing per each request processing.
If your application always uses the same set of asset bundles per each request without any variation.
You can declare your `AppAsset` to be depending on them all and then run compress command specifying it as an only source - all dependent assets will be loaded automatically.
