### ISSUE TITLE
BaseVarDumper::exportInternal() may seem to have a problem

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#7861]
I think there is something wrong in this method. 

__In short:__ I suspect that for case 'object' `var_export(serialize($var), true)` causes an error when the serialized object contains callbacks.

I've got problems with logging and the debug toolbar caused by validation errors. In my log file I've got no logging at all for the request and the debug toolbar is replaced by warning:

    ( ! ) Warning: array_map(): An error occurred while invoking the map callback in /var/www/html/misc/c3integration/vendor/yiisoft/yii2/log/FileTarget.php on line 106
    Call Stack
    #	Time	Memory	Function	Location
    1	0.0778	4585328	yii\base\ErrorHandler->handleException( )	../ErrorHandler.php:0
    2	0.1114	4975160	yii\log\Logger->flush( )	../Logger.php:0
    3	0.1114	4975472	yii\log\Dispatcher->dispatch( )	../Logger.php:170
    4	0.1114	4975920	yii\log\Target->collect( )	../Dispatcher.php:183
    5	0.1122	4986752	yii\log\FileTarget->export( )	../Target.php:111
    6	0.1122	4987288	array_map ( )	../FileTarget.php:106

Is it possible that whenever a validation rule of a model contains a callback the serialization fails? 

If Model::$_errors contains something (because of validation errors, of course) this leads to logging which in turn call the exportInternal() method with that model object. And the model object has $_validators which holds in its arrays somewhere a callback function, for example for the 'when' Validator property.

**Comment by samdark** [comment]
It's expected since callbacks could not be serialized in PHP.

**Comment by robsch** [comment]
Hm.... IMHO it's a bug. Debug extension and logging doesn't work with such validation rules, which are quite common. 

The not serializable callbacks might be expected, but that parts oft Yii don't work anymore is unexpected.

Shouldn't I use callbacks in rules?

**Comment by robsch** [comment]
Couldn't you just remove the serialization in that place? It's 'just' the VarDumper...

**Comment by lynicidn** [comment]
http://php.net/manual/en/class.serializable.php

**Comment by samdark** [comment]
Yes, it's not serializable but indeed debugger and logger should try to avoid crashing even for the case.

**Comment by lynicidn** [comment]
may be add serializable for yii\base\Component and check properties on callable?

**Comment by samdark** [comment]
How would that help?

**Comment by lynicidn** [comment]
@samdark on serialize will be return array without callable properties

**Comment by lynicidn** [comment]
check only public

**Comment by klimov-paul** [comment]
Resolved by commit f2f211f
