### ISSUE TITLE
[legba] Gii Advanced Template Set in core project

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#7862]
Hello guys!

I have seen that the gii from the yii1.x today, even improved in yii2, is weak in some advanced points.

I in my turn, I began a template advanced set, not giving override in a generator class mine, that I use the native, just using the template set files for modules, controllers and models.

Recently I published, along with my team, the project as open source (GNU), but even so I am still not sure if this should be an extension or could be incorporated into the core of the GII on Yii2 project. That way we could have natively 2's template set, leaving the user the choice of which to use, a more basic and enchuto or other more advanced.

If so, would appreciate the feedback, to prepare, along with my team a pull request the change in core project.

Thanks for listening! Yii1.x was incredible, Yii2 is amazing!

**Comment by lukBarros** [comment]
Link Project Legba Gii https://github.com/id5/legba-gii

**Comment by samdark** [comment]
I don't think everything from the legba-gii will fit the core. For example, print button is very project specific. I think for most projects it's not actually required.

**Comment by samdark** [comment]
btw., Gii issues are now to be reported at a separate project: https://github.com/yiisoft/yii2-gii/issues

**Comment by samdark** [comment]
Reviewed the rest of the features. All these are nice but not generic enough.

**Comment by lukBarros** [comment]
Ok Sam obrigado pelo retorno, mesmo assim irei reportar no projeto indicado, podemos não incorporar tudo, mas podemos aproveitar algo que melhoramos e incorporar ao core.
