### ISSUE TITLE
Extending Module

### ISSUE THREAD

**Issue by nkostadinov** [yiisoft/yii2#7865]
I have the following issue. I have Module1 with controllerA and ControllerB. I want to extend the module with MyModule with Controller C. But here is the problem - I expect that the final Module should have contollers A,B and C but this doesn't happen. If I use $controllerMap there is still problem with different view paths for each controller. How can we extend modules by keeping their original controllers and adding new ones ?

**Comment by lynicidn** [comment]
u can use alias

**Comment by nkostadinov** [comment]
how this will solve my problem? I have controllers from two modules and they need to have different viewPath

**Comment by lynicidn** [comment]
in controller
```php
$this->render('@myAlias/to/viewName', []);
```

**Comment by nkostadinov** [comment]
Yes, but I'm extending another extension`s module and don't won`t to edit its source.

**Comment by lynicidn** [comment]
u get controller from other module? it's bad practice. And in controller (if it extension) need write all view pathes via alias - @vendor/myVendor/extName/views/myView

**Comment by samdark** [comment]
Overall I don't think it's a good idea to use modules like that. Let's get into forums to discuss on how to achieve what you want to.
