### ISSUE TITLE
REST unset create but not delete

### ISSUE THREAD

**Issue by bdart** [yiisoft/yii2#7873]
I can unset actions create like the following:

```
    public function actions()
    {
        $actions = parent::actions();

        // disable the "delete" and "create" actions
        unset($actions['create'], $actions['update']);



        return $actions;
    }
```

Now I can add into the same Controller file a new `public function actionCreate()` and he recognise it.

But the same does not work for `actionUpdate($id)` or `actionDelete($id)`. I want to know why because it would be quite more easier and fast to adjust the actions on the fly.

**Comment by fernandezekiel** [comment]
@bdart  what do you mean by "doesn't work"?

**Comment by bdart** [comment]
For example:
```
    public function actionDelete($id)
    {
        if (\Yii::$app->getRequest()->getMethod() === 'DELETE') {
            $this->findMongoModel($id)->delete();
[...]
```
There is a custom rule that it shall find the Model not via the `id` either via `title_clean` in the `$this->findMongoModel`
When I try it via REST Call
`/web/v1/articles/10` with DELETE and `unset($actions['delete'])` I get:
```
{
    "status": 0,
    "error_code": 400,
    "message": "Bad request"
}
```

When I try via my `title_clean` it looks like `/web/v1/articles/here-is-some-unique-text` I get 404 Error.
So I can confirm that he unset's it but it is not behaving the way like it does with my `public function actionCreate()` where everything is running

**Comment by dapatrese** [comment]
Did you adjust REST UrlRule to accept strings for parameter `$id`?

https://github.com/yiisoft/yii2/blob/master/framework/rest/UrlRule.php#L105

**Comment by fernandezekiel** [comment]
yeah, show us your rest rules

**Comment by bdart** [comment]
I commented two lines out because I played around with it but it didn't change anything. It is easy to make the URL listen to: `web/v1/articles/delete?id=...` But this not how it should supposed to be with REST

```
['class' => 'yii\rest\UrlRule', 'controller' => 'v1/article', 'extraPatterns' => [
    'POST,OPTIONS showme' => 'showme',
    //'PUT,PATCH update/<id>' => 'update',
    //'DELETE /<id>' => 'delete',
    'GET magazin' => 'magazin',
]],
```

**Comment by bizley** [comment]
Closing since this is a clear example of misconfiguring URL rules and controller's actions code.
