### ISSUE TITLE
Remove PK from generating a form field in gii crud create/update form for mongodb

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii2#7874]
Obviously if the pk field is on the form it will just save it as "" (empty / or whatever someone types in it) if you don't set it. New people might not understand this or understand that the yii2 mongo will generate ids for them.

So it works for the first record however will throw an error on record 2+. 

So when new people use this, it would be confusing.  It confused me why I was getting a mongodb duplicate id field for a couple minutes on default crud.  

I think it would just be better to tell the mongo crud not to generate a pk form field.

**Comment by lynicidn** [comment]
default gii generate only model for mongo https://github.com/yiisoft/yii2-mongodb/tree/master/gii

**Comment by lynicidn** [comment]
need remove issue

**Comment by skworden** [comment]
It generates everything correctly and works fine (crud). Just think it should leave the pk filed off of the from by default to avoid the issue I stated above.

**Comment by lynicidn** [comment]
if u issue is correct need create controller template for yii2-mongo/gii

**Comment by klimov-paul** [comment]
I am afraid such fix is too uneasy: it will produce unnecessary complex code at Gii templates.
You should ensure '_id' attribute is unsafe at your mongodb model, then it will not appear in generated form.
