### ISSUE TITLE
RegularExpressionValidator js unicode

### ISSUE THREAD

**Issue by bizley** [yiisoft/yii2#7875]
Since javascript has got issues with unicode we cannot use features like \p{L} in "match" validator with enableClientValidation set to true because "non-ascii" letters are always returning validation error.
Are there any plans to cover this problem? There are libraries like https://github.com/mathiasbynens/regexpu or http://xregexp.com/plugins/
Or are we waiting for ES6?

**Comment by bizley-code** [comment]
Looks like the only way is to create custom validation method.

**Comment by MariusRumpf** [comment]
Just tried to validate name and surname in a project:
```php
    public function rules()
    {
        return [
            [['name', 'surname'], 'match', 'pattern' => '/^[\p{L}]+(-[\p{L}]+)?$/u'],
        ];
    }
```
If enableClientValidation is on I can never submit that form. So same problem here.

**Comment by cebe** [comment]
a workaround can be to disable client validation for a single attribute.

**Comment by MariusRumpf** [comment]
Thanks @cebe fixed it temporary like you suggested with `'enableClientValidation' => false`.
```php
    <?= $form->field($profile, 'name', [
        'enableClientValidation' => false,
     ]) ?>
    <?= $form->field($profile, 'surname', [
        'enableClientValidation' => false, 
     ]) ?>
```

**Comment by bizley-code** [comment]
Usually here things like that are sent back to yii forum. Anyway...

I'm using for this custom validation method like:

    public function validateUsername($attribute)
    {
        if (!$this->hasErrors()) {
            if (!preg_match('/^[\p{L}][\w\p{L}]{2,254}$/u', $this->username)) {
                $this->addError($attribute, Yii::t('app', 'Username must start with a letter, contain only letters, digits and underscores, and be at least 3 characters long.'));
            }
        }
    }

**Comment by cebe** [comment]
@bizley-code forum is for questions. This issue describes a limitation of yii which we may want to improve somehow so this is the right place for it.

**Comment by bizley-code** [comment]
@cebe speaking of improving instead of "workarounding" - can someone address this issue? It's been 4 months...

**Comment by bizley** [comment]
Closing since browsers support unicode tokens now.
