### ISSUE TITLE
add property yii\widgets\ActiveField::renderContent = null

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#7877]
here https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L156 we do render without args - i propose add new property for active field with `null` value as default.
Bonus: we can configure default behavior for generate `label`, `hint` and `input` of `template` `parts`

``` php
'fieldConfig' => [
    'renderContent' => function($field) {
        if (!isset($field->parts['{input}'])) {
            $field->parts['{input}'] = myLogicForGenerateInputAsDefault($field->model, $field->attribute, $field->inputOptions);
        }
        return strtr($field->template, $field->parts);
    }
]
```

now it need do for every attribute:

``` php
$form->field($model, 'attr')->inputText()->render(function($field){/*...*/});
//or
$form->field($model, 'attr')->render(function($field){/*...*/});
```

**Comment by cebe** [comment]
why would you need this?
We have template https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L55
and parts https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L144
which lets you control everything already.

**Comment by lynicidn** [comment]
@cebe i want change default behavior for generate input part of template in extension. Without it i should extend yii\bootstrap\ActiveField and yii\widgets\ActiveField
with this changes i can write extension unknowing what user is use

**Comment by lynicidn** [comment]
@cebe also with it i can set function only one place in code

**Comment by lynicidn** [comment]
problem in bootstrap extension - i can't write extensions for form or write for concrete bootstrap or yii\widgets

**Comment by lynicidn** [comment]
reopen it please and mark as `under discussion`

**Comment by lynicidn** [comment]
may be it help:
```php
use myVendor\form\ActiveField;

/**
 * @group form
 */
class ActiveFieldTest extends \yii\codeception\TestCase
{
    use \Codeception\Specify;

    public $appConfig = '@tests/codeception/config/console/unit.php';
    /**
     * @var \UnitTester
     */
    protected $tester;

    public $htmlOptions = ['class' => 'html'];
    public $label = 'label';
    public $labelOptions = ['class' => 'label'];
    public $hint = 'hint';
    public $hintOptions = ['class' => 'hint'];

    /**
     * @var \yii\widgets\ActiveForm
     */
    protected $form;
    /**
     * @var \yii\base\Model
     */
    protected $model;
    /**
     * @var \yii\widgets\ActiveField
     */
    protected $field;
    /**
     * @var array
     */
    protected $fieldOptions;

    public function setUp()
    {
        parent::setUp();
        $this->form = new \yii\widgets\ActiveForm([
            'fieldClass' => ActiveField::classname(),
        ]);
        $this->model = new \yii\base\DynamicModel(['var']);
        $this->field = $this->form->field($this->model, 'var')->hint($this->hint, $this->hintOptions)->label($this->label, $this->labelOptions);
        $this->fieldOptions = [
            'htmlOptions' => $this->htmlOptions,
            'label' => $this->label,
            'labelOptions' => $this->labelOptions,
            'hint' => $this->hint,
            'hintOptions' => $this->hintOptions
        ];
    }

    /**
     * @group input
     * @covers ActiveField::textInput
     */
    public function testInput()
    {
        $options = $this->fieldOptions;
        $this->specify('::textarea', function() use ($options) {
            $options['render'] = ['textarea'];
            $original = $this->field->textarea($this->htmlOptions);
            $field = $this->form->field($this->model, 'var', $options);
            verify('default render', $original)->equals($field);
            verify('manual render', $original)->equals($field->textarea());
        });
    }
}
```

**Comment by lynicidn** [comment]
ok. why we always use `textInput`, why not `textarea` ?

**Comment by lynicidn** [comment]
i think user should set default input type for ActiveField

**Comment by lynicidn** [comment]
or do it as here - https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1186 
if string <= 32 - textInput, other - textarea

**Comment by lynicidn** [comment]
Вообщем решать вам, но имхо подход на корню неверный, почему разрабочик не может повлиять на формирования филда по умолчанию. И раз уж на то пошло, то объект филд должен иметь свойство `тип` и методы аля textInput должны просто устанавливать этот `тип`, по умолчанию он text, но никак не генерировать налету html код - это не ооп подход, т.к. повлиять уже на сгенерированный код нельзя. Второй проблемой является то что написав свой филд вы должны выбрать расширяться от бутстрап или от дефолтного - следовательно забываем про расширения для форм, т.к. охватить оба варианта не получится.

**Comment by cebe** [comment]
can you show a concrete use case? why can't you extend ActiveField class to adjust its behavior?

**Comment by lynicidn** [comment]
@cebe i write extension for ActiveField - what is class i should extend - yii\bootstrap\ActiveField or yii\widgets\ActiveField ?
I purpose case not break BC and it solve problem with override logic for generate field as default
If now i should render every field as:
```php
echo $form->field($model, 'name')->render($function);
echo $form->field($model, 'altname')->render($function);
```
vs
```php
echo $form->field($model, 'name');
echo $form->field($model, 'altname');
```
i don't think that use anonymous function in view it good idea. I purpose move it in property and allow configure it via ActiveForm::fieldConfig.
simple example case:
```php
'fieldConfig' => [
    'renderContent' => function($field) {
        if (!isset($field->parts['{input}'])) {
            $field->parts['{input}'] = myRenderLogic($field);
        }
        return strtr($field->template, $field->parts);
    }
]
```
in `myRenderLogic` i can generate field based on validators or other logic instead of use textInput for all. I want write universe extension for bootstrap and classic widgets. More example: i want add support `hint` in Model via `attributeHints()` - now i should create 2 classes - for bootstrap and for classic.
Also i don't think that generate html code on fly for input part of template is OOP style. I mean that textInput, textarea and other methods should set `field type` property - as example fileInput should add multipart/form for form (DRY), but we generate html in `init`.

**Comment by lynicidn** [comment]
More example: i want create field types instances as in symfony
```php
'fieldConfig' => [
    'renderContent' => function($field) {
        if (!isset($field->parts['{input}'])) {
            $instance = $field->model->getFieldTypeInstance($field->attribute);
            $field->parts['{input}'] = $instance->render();
        }
        return strtr($field->template, $field->parts);
    }
]
```

**Comment by cebe** [comment]
can you give a link to the symfony documentation?

**Comment by lynicidn** [comment]
hm, i don't read guid :) i read code 
types here https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Form/Extension/Core/Type

**Comment by lynicidn** [comment]
http://symfony.com/doc/current/reference/forms/types.html

**Comment by lynicidn** [comment]
also am find cookbook http://symfony.com/doc/current/cookbook/form/index.html

**Comment by Insolita** [comment]
I think it will be good feature for autobuilding forms, and add more flexibility ...
