### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by jcfiorenzano** [yiisoft/yii2#7881]
I have a form generated by yii and when I go to send the information to the server then the browser show a Bad Request message, I have the csrf input, why this happen

**Comment by samdark** [comment]
Could you provide full message shown?

**Comment by jcfiorenzano** [comment]
It is more complicated this is the code of the form:
```php
<?php  $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form data',"id"=>"form_road"]]);?>
  
            <?= $form->field($signalModel, 'width')->textInput(["id"=>"road_with"]) ?>
        
            <?= $form->field($signalModel, 'height')->textInput(["id"=>"road_height"]) ?>
        
  
                 <?= $form->field($signalModel, 'img')->fileInput(["id"=>"image_input"]); ?>
            <a class="btn btn-primary" onclick="validate()"><?php echo Yii::t("frontend","Save Road")?>
<?php ActiveForm::end(); ?>
```

but this part not send the bad request, the bad request is because of this code:

``` php
<?php
    foreach ($elements as $element)
    {
          echo " <a href='#'><img  onclick='getRoadData(".$element->id.")' class='element_stored' width='100' height='100' src='../../frontend/web/". $element->img . "'></a>";
    }
   ?>
```
when I remove the code above the bad request message dissapear but i don't understand why this happened?? The code above isn't part of the form. This is in the backend application

**Comment by dbsparkle** [comment]
Putting aside the implementation itself (which is quite questionable),
it seems like your single and double quotes are messed up in this line:

```
 echo " <a href='#'><img  onclick='getRoadData(".$element->id.")' class='element_stored' width='100' height='100' src='../../frontend/web/". $element->img . "'></a>";
```

Read more about quotes here: http://www.trans4mind.com/personal_development/phpTutorial/quotes.htm

**Comment by klimov-paul** [comment]
I can say for sure that following code
```php
echo " <a href='#'><img  onclick='getRoadData(".$element->id.")' class='element_stored' width='100' height='100' src='../../frontend/web/". $element->img . "'></a>";
```
produces invalid HTML:
```html
<a href='#'><img  onclick='getRoadData(someId)' class='element_stored' width='100' height='100' src='../../frontend/web/some-image.jpg'></a>";
```
First of all tag attributes should be quoted by double quotes `"` instead of  single one `'`.
Secondly, I am unsure if your 'onclick' will be composed as valid JS.

Closed, unless more coherit way to reproduce the issue arraives.

**Comment by CthulhuDen** [comment]
What are you talking about? Single quote is fine for HTML.

**Comment by dbsparkle** [comment]
@CthulhuDen yah, but you`re using php and html... so the single and double quotes there are just... messed up.
