### ISSUE TITLE
Using relation without selecting link column

### ISSUE THREAD

**Issue by ageusz** [yiisoft/yii2#7882]
I noticed oakward behavior. I have models `Message` and `User` with following relation in `Message` class:
```
public function getUser() {
    return $this->hasOne(User::className(), ['id' => 'id_user']);
}
```
Then I build query like this: 
```
protected function getMessages() {
        return Message::find()->with(['user' => function($query) {
                                $query->select(['name', 'surname', 'display_name']);
                            }])->asArray()->all();
            }

        }
```
When there are more than one `Message` objects then I got error as a result: `Undefined index: id` (in ActiveRelationTrait, line 495).
If I add `id` in `select` it works fine, but I don't wan't the `id` to be selected.
Do I have to select it with the id and then manually remove `id` columns from `user`?

**Comment by samdark** [comment]
You have to select primary key. That's how AR works.
