### ISSUE TITLE
about error handler

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/yii2#7884]
Hi, I have a question.

in index.php, configuration as bellow:
```
defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');
```

when occured 500 error in the page, log system will track the error message into the file.

But, when there is an ajax request, if occured 500 error, will not track log into the file.

Here is my test code:
```
function actionTest()
{
    var_dump($arr['test']);
}
```
and for ajax:

```
function actionTest()
{
    Yii::$app->getResponse()->format = Response::FORMAT_JSON;
    var_dump($arr['test']);
}
```

my log targets configuration:

```
...
[
    'class' => 'yii\log\FileTarget',
    'levels' => ['warning'],
    'logFile' => '@runtime/logs/warning.log',
],
[
    'class' => 'yii\log\FileTarget',
    'levels' => ['error'],
    'logFile' => '@runtime/logs/error.log',
],
...
```

What should i do? Or some suggestion to me? I want to track error and warning message in production env..

**Comment by samdark** [comment]
Sounds like a bug but needs to be verified by someone else.

**Comment by lichunqiang** [comment]
thanks, @samdark

**Comment by lynicidn** [comment]
u should return array for FORMAT_JSON

**Comment by lichunqiang** [comment]
@lynicidn I know, Here just a test for throw exception, and It will be write log or not.

**Comment by lynicidn** [comment]
u get invalid json string - 500?

**Comment by lichunqiang** [comment]
- -!! 
The code will throw exception. 
```
var_dump($arr['test']);
```
$arr is undefined

**Comment by lichunqiang** [comment]
@samdark 

Sorry, I had found the reason. It's not Yii's bug.

I try to inherit the yii\web\ErrorHandler, but I missing some dependence.

Closed!
