### ISSUE TITLE
AR::findOne($condition) transformed into IN

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#7888]
The code 
```php
User::find()->where(['email'=>2, 'auth_key'])->one()
```
performed to 
>exception 'yii\base\InvalidParamException' with message 'Operator 'AUTH_KEY' requires two operands

Ok.

The code
```php
User::findOne(['email'=>2, 'auth_key'])
```
produce
```sql
SELECT * FROM `user` WHERE `id` IN (2, 'auth_key')
```

Strange. I came across this when I wanted to run
```php
User::findOne(['email'=>2, new \yii\db\Expression('username IS NOT NULL')
```

and get 
```sql 
SELECT * FROM `user` WHERE `id` IN (2, username IS NOT NULL)
```

p.s I know about need run
```php
User::find()->where(['email'=>2])->andWhere(new Expression('username IS NOT NULL'))->one()
```
But `findOne` behaves strangely in the case. And I didn't find the description of this behavior in any documentation.

**Comment by githubjeka** [comment]
Hmm..
```php
User::findOne(['AND', ['email'=>2], [new \yii\db\Expression('username IS NOT NULL')]]);
```

```sql
SELECT * FROM `user` WHERE `id` IN ('AND', NULL, NULL)
```

**Comment by lynicidn** [comment]
Жека ну ты чего
['email'=>[2, 'auth_key']]

**Comment by lynicidn** [comment]
['and', 'a' => 'A', 'b' => 'B']

**Comment by lynicidn** [comment]
а вру, согласно гайду
```

// returns customers whose ID is 100, 101, 123 or 124
// SELECT * FROM `customer` WHERE `id` IN (100, 101, 123, 124)
$customers = Customer::findAll([100, 101, 123, 124]);

```

**Comment by githubjeka** [comment]
Там не `['email'=>[2, 'auth_key']],` а `['email'=>2, 'auth_key']`
и ['and', 'a' => 'A', 'b' => 'B'] не работает,  - https://github.com/yiisoft/yii2/issues/7888#issuecomment-86646980, ой там 

```php
User::findOne(['AND', ['email'=>2], [new \yii\db\Expression('username IS NOT NULL')]]);
```

Но даже, если правильно
```php
User::findOne(['AND', ['email'=>2], new Expression('username IS NOT NULL')]
```
то возвращается:
```sql
SELECT * FROM `user` WHERE `id` IN ('AND', NULL, username IS NOT NULL)
```
для 
```php
find()->where((['AND', ['email'=>2], new Expression('username IS NOT NULL')])
```
работает как надо:
```sql
SELECT * FROM `user` WHERE (`email`=2) AND (username IS NOT NULL)
```

**Comment by githubjeka** [comment]
After all, this code should be executed the same. Am I right?

```php
User::findOne(['AND',['email'=>2], new Expression('username IS NOT NULL')]);
User::find()->where(['AND',['email'=>2], new Expression('username IS NOT NULL')])->one();
```

```sql
SELECT * FROM `user` WHERE `id` IN ('AND', NULL, username IS NOT NULL) //findOne
SELECT * FROM `user` WHERE (`email`=2) AND (username IS NOT NULL) //find->one()
```

**Comment by cebe** [comment]
> User::find()->where(['email'=>2, 'auth_key'])->one()

this syntax looks completely wrong, where do you get that from?



> User::findOne(['email'=>2, new \yii\db\Expression('username IS NOT NULL')

this is not valid syntax, you can either use associative array OR compose where with operators. Not both in one array.

However the example in your last comment looks like a bug.

**Comment by qiangxue** [comment]
`User::findOne(['email'=>2, 'auth_key'])` is because the array is not a full associative array. So it is considered to be an array of values that the primary key should be in. Note that `findOne()` is not the same as `find()->where()`.

**Comment by githubjeka** [comment]
Ok, it is necessary to describe in comments here - http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findOne()-detail
And now there is:
```php
// find the first customer whose age is 30 and whose status is 1
$customer = Customer::findOne(['age' => 30, 'status' => 1]);
// the above code is equivalent to:
$customer = Customer::find()->where(['age' => 30, 'status' => 1])->one();
```

"equivalent" makes it clear that everything is the same.
