### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#7889]
It could be a good idea to have something like Symfony or Laravel installer: http://symfony.com/blog/introducing-the-new-symfony-installer

The basic idea is to download prepared set of archives first time instead of waiting for Composer to resolve dependencies.

**Comment by lynicidn** [comment]
не знаю будет полезно или нет, просто сегодня наткнулся, да и вообще на хабре пошла маничка с докерами - http://habrahabr.ru/sandbox/92771/

**Comment by pana1990** [comment]
:+1:

**Comment by vchenin** [comment]
It's not exactly about this subject, but maybe it will be useful for somebody.
I was create [script](https://github.com/vchenin/yii2/blob/getcomposer/getcomposer.sh), which simplify process of composer installation.
You can install composer globally:
`sudo sh getcomposer.sh -g`
or locally:
`./getcomposer.sh -l`
or with specified options:
`./getcomposer.sh -o --filename=composer --version=1.0.0-alpha8`

**Comment by pana1990** [comment]
@vchenin it would be like this https://github.com/laravel/installer

**Comment by pana1990** [comment]
@samdark i created extension for this feature https://github.com/pana1990/yii2-installer 

do you would like to migrate this extension to oficial extension?

**Comment by samdark** [comment]
Most probably yes.

**Comment by pana1990** [comment]
@samdar How can I help to migrate ?

**Comment by samdark** [comment]
I've created a repo https://github.com/yiisoft/yii2-installer. You can submit a pull request there. We'll review code and if it's OK, merge it, update docs etc.

**Comment by pana1990** [comment]
@samdark check pr https://github.com/yiisoft/yii2-installer/pull/1

Thanks very much ;)

**Comment by dynasource** [comment]
discussion moved to https://github.com/yiisoft/yii2-installer/issues
