### ISSUE TITLE
yii migrate/mark m000000_000000_base not working

### ISSUE THREAD

**Issue by lorinczelod** [yiisoft/yii2#7890]
I want to mark the very first, "0. migration" command, but is not working. It is a bug or feature? (I think it's bug). How can i "delete" other way the first (1.) migration?
(The error message is: Error: Unable to find the version 'm000000_000000_base'.)

**Comment by mdmunir** [comment]
There are no *phisically* `m000000_000000_base` migration.
@cebe 
Like `migrate/down all`,IMO we should have `migrate/mark-down all`

**Comment by cebe** [comment]
`m000000_000000_base` is an entry in the history table so this should somehow work.

**Comment by cebe** [comment]
Fixed, thanks for reporting!
