### ISSUE TITLE
generate code with gii but keep customization

### ISSUE THREAD

**Issue by lorinczelod** [yiisoft/yii2#7891]
I made my model generator, because the existing one not keep my changes in model class, if I regenerate the model for example after a table structure changing.

1. The first idea is, that we make two class instead of one:
First class:
```php
<?php
namespace app\models\db\core;
/**
 * This is the model class for table "article".
 * @property integer $id
 * @property string $title
 * ......
 */
 
class CoreArticle extends \yii\db\ActiveRecord {
    /** @inheritdoc */
    public static function tableName()   {
        return 'article';
    }
 // ......
 }
 ```
Second class:
```php
<?php
namespace app\models\db;
/** This is the override model class for table "article". */
class Article extends \app\models\db\core\CoreArticle
{ 
}
```
This second class is empty at the beginning, but here will come the customization, and never will be regenerated.

2. The second idea is that these model classes from tables we put e.g. to "db" subdirectory, and "core" sub-subdir respectively

**Comment by cebe** [comment]
code generated by gii is never meant to be used as is, it is a template to speed up development, your usage is not and will not be officially supported because that would mean that gii must be perfect in guessing things. This is not possible for many things like naming and validation rules.

**Comment by hmphu** [comment]
Hi,

I'm confused. Should I create a "core" models like @lorinczelod  and create other models file extend "core" models to add modifications or should I generate and modify directly apply diff when regenerate them?

Thanks

**Comment by cebe** [comment]
> I generate and modify directly apply diff when regenerate them

this.

**Comment by hmphu** [comment]
Thank for your reply @cebe. I did it before but my app is in development and tables is changed a lots, so when I regenerate them It is hard to diff and merge code and I think @lorinczelod idea is better than. How do you think?

**Comment by cebe** [comment]
Well, my answer (https://github.com/yiisoft/yii2/issues/7891#issuecomment-86749228) still applies. Gii can not be used for creating relyable base classes because in most cases generated classes need adjustment.

**Comment by hmphu** [comment]
Yay, thank you very much @cebe. I'm clear now :+1:
