### ISSUE TITLE
Setting  config/db.php 'attributes' to PDO::CASE_LOWER causes Yii to not work

### ISSUE THREAD

**Issue by devalphabeta** [yiisoft/yii2#7892]
in config/db.php I am setting 'attributes'. 
   'attributes' => [
        \PDO::ATTR_CASE=>\PDO::CASE_LOWER,
        ]

in /home/devalp5/public_html/yii2basic/vendor/yiisoft/yii2/base/Component.php at line 143

throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);

Also, gii creates an empty model with PDO::CASE_LOWER

**Comment by mdmunir** [comment]
What error and how you do that (write config)?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/7868

**Comment by klimov-paul** [comment]
Are you using MySQL?
Provide your DDL and model code.

**Comment by samdark** [comment]
It should be fixed now. See #7868.
