### ISSUE TITLE
Sending response sets invalid code when exception thrown

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii2#7893]
I have posted this on the forums too, but i got absolutely no response and i can't seem to figure out how to make this work properly so i think the below behavior is a bug somewhere.

I following: http://www.yiiframework.com/doc-2.0/guide-rest-error-handling.html and in my config i have:
```php
'response' => [
            'class'  => 'yii\web\Response',
            //'format' => \yii\web\Response::FORMAT_JSON,        
            'on beforeSend' => function ($event) {
                $response = $event->sender;
                //$response->formatters['html'] = 'yii\web\JsonResponseFormatter';
                $output   = Yii::$app->request->get('output');
                if (in_array($output, [$response::FORMAT_JSON, $response::FORMAT_JSONP, $response::FORMAT_XML])) {
                    $response->format = $output;
                }
                $response->data = [
                    'success' => $response->isSuccessful,
                    'data'    => $response->data,
                ];
                $response->setStatusCode(200);
            },
        ],        
```

and in my rest controller, i am using the yii\filters\auth\HttpBearerAuth as:
```php
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class'  => 'yii\filters\auth\HttpBearerAuth',
            'except' => ['login', 'create'],
        ];
        return $behaviors;
    }
```

Now the thing is that if i access a url that requires authentication, i get the response i expect:
```php
<response>
<name>Unauthorized</name>
<message>You are requesting with an invalid credential.</message>
<code>0</code>
<status>401</status>
<type>yii\web\UnauthorizedHttpException</type>
</response>
```

BUT the headers i get:
```php
HTTP/1.1 401 Unauthorized
Date: Wed, 25 Mar 2015 13:39:37 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.6
X-Powered-By: PHP/5.6.6
Www-Authenticate: Bearer realm="api"
Content-Length: 231
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/xml; charset=utf-8
```
So why do i get a 401 Unauthorized when i specified that i want a 200 code for all cases ?

If i access a page that does not exists, i get back:
```php
<response>
<success/>
<data>
<name>Error</name>
<message>An internal server error occurred.</message>
<exception>
<NotFoundHttpException>
<statusCode>404</statusCode>
<xdebug_message>...</xdebug_message>
</NotFoundHttpException>
</exception>
</data>
</response>
```

And the headers:
```php
HTTP/1.1 200 OK
Date: Wed, 25 Mar 2015 13:52:28 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.6
X-Powered-By: PHP/5.6.6
Content-Length: 4519
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/xml; charset=utf-8
```

**Comment by cebe** [comment]
have you configured error handler in your application configuration? if yes, please show how.

**Comment by twisted1919** [comment]
Hey,

The error handler is the default that comes with yii, didn't do anything special to it.
Here's how it looks:
```php
'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets'    => [
                [
                    'class'  => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
```

Anyway, i have tracked the issue down to the ```www-authentication``` header, if i do:
```php
'response' => [
            'class'  => 'yii\web\Response',
            'format' => \yii\web\Response::FORMAT_JSON,        
            'on beforeSend' => function ($event) {
                $response = $event->sender;
                $response->getHeaders()->remove('www-authenticate'); // THIS
                $response->formatters['html'] = 'yii\web\JsonResponseFormatter';
                $response->data = [
                    'success' => $response->isSuccessful,
                    'data'    => $response->data,
                ];
                $response->setStatusCode(200);
            },
        ],      
```
Then i get:
```
[root@localhost ~]# curl -i -H "Accept: application/json; q=1.0, */*; q=0.1" "http://api.domain.io/v1/users/922"
HTTP/1.1 200 OK
Date: Fri, 27 Mar 2015 11:45:44 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.6
X-Powered-By: PHP/5.6.6
Content-Length: 149
Content-Type: application/json; charset=UTF-8

{"name":"Unauthorized","message":"You are requesting with an invalid credential.","code":0,"status":401,"type":"yii\\web\\UnauthorizedHttpException"}
```
So it's fine as far as i remove that header. Now the question is, why is this happening?

**Comment by klimov-paul** [comment]
This is done by web server automatically: it overrides status header to 401 on 'WWW-Authenticate: Bearer realm="api"' without match given.
This can be reproduced by plain PHP:
```php
if (!isset($_SERVER['PHP_AUTH_USER'])) {
    header('WWW-Authenticate: Bearer realm="My Realm"');
    // no status code setup !
    echo 'Canceled';
    exit;
} else {
    echo "<p>Hello {$_SERVER['PHP_AUTH_USER']}.</p>";
}

```

**Comment by twisted1919** [comment]
Why did you close this, what is the fix in this case ?

**Comment by klimov-paul** [comment]
There is no fix, at least in framework scope.
Perhaps there is some settings in your Apache/NJinx/etc config, but tha does not relates to Yii.

**Comment by twisted1919** [comment]
Okay, in this case, can we at least have a note in the code related to this behavior?
It made me go nuts till i figured it out, at least we can spare other people the misery, shall we ?
Thanks.

**Comment by klimov-paul** [comment]
Well, I am unsure.
In this issue you have abused HTTP Bearer authentication, which dictates particular status code on invalid response. Such practice is unlikely to be widely used.
Adding note about it is just like adding note that your effots on setup 'X-Powered-By' header will have no effect if 'expose_php' is enabled in your 'php.ini'.

**Comment by twisted1919** [comment]
Right, you see, this is the problem because i have followed what you guys have suggested at http://www.yiiframework.com/doc-2.0/guide-rest-error-handling.html and i believe that article is pretty much right, i don't think we have abused by this header at all actually.

**Comment by klimov-paul** [comment]
This article is about setup your response status code.
The cause of your problem is usage of `HttpBearerAuth` filter, which actually does not allows that.
Don't mess hings up.

**Comment by twisted1919** [comment]
I don't think you are right, please read the initial issue again.
P.S: I'll drop this conversation now, so feel free to do what you feel right.
Thanks.

**Comment by klimov-paul** [comment]
this is quote from your original issue description:

> and in my rest controller, i am using the yii\filters\auth\HttpBearerAuth as

The problem you have faced does not caused by Yii, not even by PHP.
There plenty of pitfalls around differnt things, we can not mention them all in the docs.
