### ISSUE TITLE
Yii2: arrayDataProvider and pagination offset

### ISSUE THREAD

**Issue by ptz-nerf** [yiisoft/yii2#7905]
I think there is a bug. When you call $arrayDataProvider->getTotalCount() or $arrayDataProvider->totalCount first time and $arrayDataProvider->getPagination()->getOffset(), then pagination doesn't work. 
Example:
```php
#controller
public function actionTest() {
	$dataProvider = new \yii\data\ArrayDataProvider([
		'allModels' => [1,2,3,4,5,6,7,8,9],
		'pagination' => ['defaultPageSize' => 5],
	]);
		
	return $this->render('test', ['dataProvider' => $dataProvider]);
}

#view
if($dataProvider->totalCount) {   //try $dataProvider->count - it works
	echo $dataProvider->totalCount . "<br>";
	echo $dataProvider->getPagination()->getOffset() . "<br>";
	
	
	foreach ($dataProvider->getModels() as $num) {
		echo "$num<br>";
	}
}
echo yii\widgets\LinkPager::widget([
	'pagination' => $dataProvider->getPagination(),
]);
```
Note: Something weird... If you use $arrayDataProvider->count first, then pagination work. Yii v2.0.3

**Comment by klimov-paul** [comment]
This is expected.
`Pagination::getOffset()` depends on `Pagination::totalCount`, which is up to data provider to be filled.
`BaseDataProvider::getTotalCount()` automatically sets `Pagination::totalCount` value to the calculated one.

**Comment by ptz-nerf** [comment]
I don't understand. 
1) `getTotalCount()` doesn't set `Pagination::totalCount`, but `getCount()` sets.
In example above `$dataProvider->getPagination()->totalCount` is empty, but `$dataProvider->totalCount` is called in IF statement.
2) Why `$dataProvider->getPagination()->getOffset()` breaks pagination. Without this all works fine.
