### ISSUE TITLE
hole?

### ISSUE THREAD

**Issue by ph1ex0n** [yiisoft/yii2#7906]
I have basic yii2, after the user enters the password his ip stored in a logs.
In the logs appear ips of spiders of Google and Yandex.
How can it be explained?

**Comment by samdark** [comment]
Umm... you have google ips in your localhost server that isn't accessible from outside?

**Comment by ph1ex0n** [comment]
это типа юмор?
я говорю, что ко мне в админку каким-то образом залезают боты гугла и яндекса, там, где проход только после ввода пароля
может и гугл-перевод зловредничает?)
вот факты
=====
6 марта
IP	66.249.64.14
Хост:	crawl-66-249-64-14.googlebot.com
=====
16 марта
IP	66.249.67.2
Хост:	crawl-66-249-67-2.googlebot.com
=====
25 марта
IP	66.249.79.18
Хост:	crawl-66-249-79-18.googlebot.com
=====
26,27,28 марта
IP	5.255.253.214
Хост:	spider-5-255-253-214.yandex.com
=====

**Comment by cebe** [comment]
@ph1ex0n depends on your code, you should check if it is possible to log in with a wrong username and password. Without your code, we can not help much, you have to show how you make sure that no annonymous user logs in

**Comment by ph1ex0n** [comment]
models/User.php

    private static $users=['100'=>['id'=>'100','username'=>'admin','password'=>'mypass','authKey'=>'test100key','accessToken'=>'100-token']];

views/site/login.php

    	  <script type="text/javascript">
	  	function call(){<?= mail('q@gmail.com','subj','login '.$_SERVER['HTTP_X_REAL_IP']) ?>}
		</script>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['onmouseup'=>'call()','class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

**Comment by omnilight** [comment]
@ph1ex0n What is that?

**Comment by ph1ex0n** [comment]
logging

**Comment by samdark** [comment]
Hmm... I know that yandex bot was using metric to get to admin parts but heard no such thing of google bot. Overall, if you've secured your admin part it should not be able to get there.

**Comment by ph1ex0n** [comment]
и тем не менее...
кстати, бот яндекса сегодня два раза уже отметился
как бот может нажимать на кнопки?

**Comment by omnilight** [comment]
Вы вставляете вывод php-кода, который будет выполнен при генерации страницы, в тело Javascript-функции. 
Боту не надо никуда кликать,  отправка писем происходит сразу при загрузке страницы

**Comment by samdark** [comment]
1. Слогируйте URL.
2. Попробуйте зайти на этот URL браузером. Если никак — всё нормально в плане безопасности со стороны Yii и надо исправлять что-то в вашем коде.

**Comment by ph1ex0n** [comment]
2omnilight
я вставил php-код, который вызывается при запуске js-функции, что может произойти только после нажатия на кнопку
с каких пор функции, а особенно код, находящийся внутри них, запускаются сами?

**Comment by ph1ex0n** [comment]
2samdark
стесняюсь спросить, а что такое "Слогируйте URL"?

дело в том, что в одной из групп fb была поднята аналогичная тема, поэтому меня это и тревожит

**Comment by samdark** [comment]
Можно ссылку на ту группу FB?

**Comment by samdark** [comment]
1. Значит надо узнать, какие URL гуглебот посетил и в каком порядке.

**Comment by samdark** [comment]
И ещё вопросы:

1. Используется ли яндекс метрика?
2. Используется ли Google analytics?
3. Используются ли какие-либо плагины для браузера от Google или яндекс?

**Comment by CthulhuDen** [comment]
@ph1ex0n You might wanna reconsider you opinion about what onmilight said. You seem have somewhat mistaken understanding of how php and javascript interact. http://it-ebooks.info/book/2083/ here is a book for you.

**Comment by omnilight** [comment]
@ph1ex0n Весь php код будет выполнятся во время генерации страницы, то что Вы обрамили его Javascript - функцию ничего не меняет, в реальности телом вашей функции будет просто стоковая константа или вообще оно будет пустым

**Comment by ph1ex0n** [comment]
всем спасибо, похоже это старая общая проблема - https://toster.ru/q/5726

я так и не понял как это решить, я еще подумаю

в этой группе https://www.facebook.com/groups/yiitalk/ вроде видел, но сейчас не могу найти

плагины и счетчики не использую

**Comment by lynicidn** [comment]
@omnilight :+1: you are right
