### ISSUE TITLE
Expose the method to get the maxlength

### ISSUE THREAD

**Issue by thiagotalma** [yiisoft/yii2#7907]
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1183
It would be helpful if it were a public method. We could reuse it.

**Comment by cebe** [comment]
what do you need it for?

**Comment by thiagotalma** [comment]
Using widgets.

I created a method that does exactly the same process. If you create the method in the framework, more people could use.

**Comment by SilverFire** [comment]
The method name does not belong to `HtmlHelper` desired responsibility, so I'm against making it public.
