### ISSUE TITLE
Does yii/swiftmailer able to add custom mail header?

### ISSUE THREAD

**Issue by relaxpor** [yiisoft/yii2#7909]
I have use mandrill as my smtp server.
And they work great.
One feature that i want to use in my site is the mail tagging feature.
It will help me to read the report easier.

However, to tag mail, they need to add custom header while sending mail.

I was wondering, is yii/swiftmail is able to do this?

Please kindly advise.

Thank you.

**Comment by samdark** [comment]
Please ask for swiftmailer specific fetures at https://github.com/yiisoft/yii2-swiftmailer. Thanks!
