### ISSUE TITLE
Auto convert AR arrays to Postgres array

### ISSUE THREAD

**Issue by exru** [yiisoft/yii2#7911]
Имеется БД на Postgres:
```sql
create table banners(
id serial,
/*....*/
platfrom int[]
);
```
Имеется форма где одно поле "platfrom" представлено в виде мультиселекта.
Однако при попытке сохранить модель в БД выпадает ошибка:

Database Exception – yii\db\Exception

SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА: значение массива должно начинаться с "{" или указания размерности
The SQL being executed was: UPDATE "banners" SET "priority"=NULL, "time_form"=NULL, "time_to"=NULL, "platfrom"='1', "views_static"=, "clicks_static"=, "enabled"=1 WHERE "id"=1
Error Info: Array
(
    [0] => 22P02
    [1] => 7
    [2] => ОШИБКА:  значение массива должно начинаться с "{" или указания размерности
)
↵
Caused by: PDOException

Я так понимаю PDO старается передать массив такого вида [[...], [...]] ,а надо такого {{...},{...}}
как подружить Postgres и AR?

**Comment by klimov-paul** [comment]
Duplicates #7640

**Comment by exru** [comment]
Да это не то я сохранить пытаюсь а не выборку сделать!

**Comment by joni-jones** [comment]
@exru, я сейчас как раз дописываю функционал, который позволит работать с `integer[]` и `text[]` postgres массивами. php массив будет конвертировать в эквивалентный postres массив.
