### ISSUE TITLE
Memory limit exceeded on DB query

### ISSUE THREAD

**Issue by ominds** [yiisoft/yii2#7913]
I'm having this error message show up every hour or so in my PHP log files

[30-Mar-2015 08:37:52 UTC] PHP Fatal error:  Allowed memory size of 335544320 bytes exhausted (tried to allocate 83 bytes) in /var/www/htdocs/yaqut/yii-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php on line 1048

As you can see, I raised the limit from 192 MB to 320 MB and still getting the same problem. And on the same line of code. From the stack trace, here's the relevant code information from my file that's ultimately causing this

    public static function highlightsByUserAndBook($userprofile_id, $book_id, $wheres = []) {
        $highlights = self::find()->where(['userprofile_id' => $userprofile_id, 'book_id' => $book_id]);
        
        foreach ($wheres AS $where) {
            $highlights->andWhere($where);
        }
        
        $highlights_result = $highlights->all(); // This is the line that crashes!!!
        
        $highlights_array = [];
        
        foreach ($highlights_result AS $highlight) {
            $highlights_array[] = $highlight->mapAttribs(['serverId' => 'id', 'bookId' => 'book_id', 'fromOffset', 'toOffset', 
            'color' => 'markColor', 'noteText' => 'displayText', 'deleted']);
        }
        
        return $highlights_array;
    }

Here's the Table Schema for Highlights

    CREATE TABLE `yqt_highlights` (
      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
      `userprofile_id` bigint(20) NOT NULL,
      `book_id` int(10) unsigned NOT NULL,
      `fromOffset` int(11) unsigned NOT NULL,
      `toOffset` int(11) unsigned NOT NULL,
      `markColor` int(11) unsigned NOT NULL,
      `displayText` varchar(150) DEFAULT NULL,
      `accessType` smallint(5) unsigned NOT NULL,
      `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
      `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
      `modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`),
      KEY `userprofileId` (`userprofile_id`,`book_id`),
      KEY `IDX_yqt_highlights_deleted` (`deleted`)
    ) ENGINE=InnoDB AUTO_INCREMENT=54659975 DEFAULT CHARSET=utf8

Finally, here's the query that's happening

    SELECT * FROM `yqt_highlights` WHERE ((`userprofile_id`=193821) AND (`book_id`=987)) AND (`modified` >= '2015-03-25 21:30:15')

And the call signature

    193821, 987, [['>=', 'modified', '2015-03-25 21:30:15']]

I think that covers it. I'm not sure what the problem is and why it's happening. It doens't happen every time, so it's not repeatable. But I can find it happening every hour or so in the error logs. Let me know if there's anything else I can do to help you track it.

**Comment by samdark** [comment]
How many records the query returns?

**Comment by klimov-paul** [comment]
Memory limit error is not necessary caused by the piece of code your provide. Your application may allocate most of the used memory at other places - this is just a 'last drop'.

If you facing this problem while running some long-run script you should ensure garbage collection at your code:
http://php.net/manual/en/function.gc-collect-cycles.php

If you are attempting to fetch high amount of records from database, you should consider using `Query::batch()`, otherwise you'll never have enough memory.

**Comment by ominds** [comment]
You are totally correct. Something's wrong that's causing this query to return near 100000 records when it should be no more than 10 for this query. Thanks for pointing me in the right direction.

**Comment by fernandezekiel** [comment]
what was the SQL generated?

**Comment by samdark** [comment]
@fernandezekiel it's in the first post.

**Comment by fernandezekiel** [comment]
maybe you should try calling `count` and see how many records are actually being returned...
