### ISSUE TITLE
ActiveRecord::find throws database exception on wrong datetype with MSSQL

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#7914]
I use a `MSSQL-DB`, which throws an exception if it gets the wrong datetype in a where condition.

This is the case if you use the find method of the ActiveRecord-Class like me:

``` php
$customerID = Yii::$app->request->get('customerID');
$customer = Customer::findOne($customerID);
```

If the GET param `customerID` isn't an `integer` it throws a database exception:

``` mssql
SQLSTATE[22018]: [Microsoft][SQL Server Native Client 10.0][SQL Server]
Conversion failed when converting the nvarchar value 'test' to data type int.
The SQL being executed was: SELECT * FROM [customer] WHERE [id]='test'
```

I would rather expect to get null, because no `customer` with the ID `test` was found.

**Comment by nineinchnick** [comment]
Casting the param read from request is your responsibility as part of the data validation process.

**Comment by nineinchnick** [comment]
Maybe you mean that `findOne()` should cast the value based on pk column type? It is done in some other places AFAIR.

**Comment by darkdef** [comment]
I'm tried add cast in sql query - and getted trown exception (this correct behavior of sql server)
SQLSTATE[22018]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value 'test' to data type int.

IMHO cast type not needed if value correct.
See examples on image:
[https://yadi.sk/i/pJJoScAABG4jZQ](url)
