### ISSUE TITLE
Add ability to set currency symbol in formatter config

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#7915]
I want to use `&#8381;` (Russian Ruble sign) instead of `руб.` when formatting currencies (`yii\i18n\Formatter::asCurrency()`).
I don't see the way to set it.

**Comment by cebe** [comment]
Just tried to do that with plain intl number formatter. Did not manage to set the currency symbol.
http://php.net/manual/en/class.numberformatter.php

There is `NumberFormatter::CURRENCY_SYMBOL` and `NumberFormatter::INTL_CURRENCY_SYMBOL`. First has no effect at all, second throws an error if I pass them to setSymbol()...

Can you try to make it work with plain intl number formatter? I can introduce it in yii if we found out how it works.

**Comment by RomeroMsk** [comment]
This code works for me:
```php
$fmt = new \NumberFormatter('ru_RU', \NumberFormatter::CURRENCY);
$fmt->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '&#8381;');
echo $fmt->format(1234567.89);
```

**Comment by cebe** [comment]
what about formatCurrency() ? http://php.net/manual/en/numberformatter.formatcurrency.php

**Comment by cebe** [comment]
Ahh, I see the problem now...

**Comment by RomeroMsk** [comment]
Checked, works. Thanks a lot!

**Comment by Fisher-mast** [comment]
Settings 
```
'formatter' => [
            'dateFormat' => 'dd.MM.yyyy',
            'decimalSeparator' => ',',
            'thousandSeparator' => ' ',
            'currencyCode' => 'RUB',
            'numberFormatterOptions' => [
                NumberFormatter::MIN_FRACTION_DIGITS => 0,
                NumberFormatter::MAX_FRACTION_DIGITS => 2,
            ],
            'numberFormatterSymbols' => [
                NumberFormatter::CURRENCY_SYMBOL => '₽',
            ]
        ],
```
but CURRENCY_SYMBOL not working for me, show .руб instead my symbol. php 7.1, intl ext installed

**Comment by cebe** [comment]
@Fisher-mast please open a new issue for this.

**Comment by auxww** [comment]
**duplicates https://github.com/yiisoft/yii2/issues/13629**

You should not set 'currencyCode' => 'RUB', then it will be well done.

config
```
'formatter' => [
            //'currencyCode' => 'RUR',
            'numberFormatterOptions' => [
                NumberFormatter::MIN_FRACTION_DIGITS => 0,
                NumberFormatter::MAX_FRACTION_DIGITS => 0,
            ],
            'numberFormatterSymbols' => [
                NumberFormatter::CURRENCY_SYMBOL => '&#8381;',
            ],
        ],
```

formatter call
```
<?= Yii::$app->formatter->asCurrency(Yii::$app->user->balance) ?>
```

output
```
200 000 ₽ 
```

look inside the yii\i18n\Formatter
```
    public function asCurrency($value, $currency = null, $options = [], $textOptions = [])
    {
            //...
            $currency = $currency ?: $this->currencyCode;
            if ($currency && !isset($textOptions[NumberFormatter::CURRENCY_CODE])) {
                $textOptions[NumberFormatter::CURRENCY_CODE] = $currency;
            }
            $formatter = $this->createNumberFormatter(NumberFormatter::CURRENCY, null, $options, $textOptions);
            //die(print_r($textOptions, 1));
            //die($formatter->getSymbol(\NumberFormatter::CURRENCY_SYMBOL));
            if ($currency === null) {
                $result = $formatter->format($value);
            } else {
                $result = $formatter->formatCurrency($value, $currency);
            }
            //...
```

When you setting up a currency code value in Yii config, it creates NumberFormatter with additional options: $textOptions = [5 => 'RUR'], then calls formatCurrency($value, $currency) and results as 'р.'. 
```
$result = $formatter->formatCurrency($value, $currency);
```

Otherwise it creates calls NumberFormatter with an empty $textOptions = [], calls format($value) and NumberFormatter::CURRENCY_SYMBOL is applied, this results as '₽'.
```
$result = $formatter->format($value);
```
This works on both windows/mac notebook and frebsd/centos (or any other) server, with 7 or 5.4 php.

As for me, It's not, a little bit, usable, but it works if you wanna.

Best wishes,
auxww

**Comment by auxww** [comment]
You can do it
