### ISSUE TITLE
Pjax widget suggestion

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#7918]
Suggestion one: If we using pjax widget in the loop - there are too many useless js code. For exapmle, we need handle only one click on the button per iteration. Is this possible to make $linkSelector and $formSelector oprional? In the case above we should disable $formSelector and it would reduce the generated code twice.

Suggestion second: it would be great to define ability to have only one handler for the same operation. For example, we have list of the items and there is only one button in the each item. I want update only item's block when i click to the button. But in this case i should define the same handler for each item's button.

**Comment by Alex-Code** [comment]
The javascript could be simplified, [Pjax Docs](https://github.com/defunkt/jquery-pjax#pjaxclick)
Instead of attaching to a single named container we could find it on the click event.

```javascript
$(document).on('click', 'a[data-pjax]', function(event) {
  var container = $(this).closest('[data-pjax-container]')
  $.pjax.click(event, {container: container})
}).on('submit', 'form[data-pjax]', function(event) {
  var container = $(this).closest('[data-pjax-container]')
  $.pjax.submit(event, container)
});
```

**Comment by usualdesigner** [comment]
PR [https://github.com/yiisoft/yii2/pull/7925](https://github.com/yiisoft/yii2/pull/7925)

**Comment by samdark** [comment]
Why do you need to use widget in this case? pjax global handler could be registered via just JS.

**Comment by usualdesigner** [comment]
@samdark it will be useful if you just need one handler (only for links or only for forms inside the widget). In this case part of the js code won't generated.

**Comment by samdark** [comment]
But why do you need a widget in this case?

**Comment by usualdesigner** [comment]
By default widget is generating two default selectors - the one for links and another one for forms. Often I'm using only links with Pjax. So, in this case i don't want clog my code redundant selectors (form selectors in this case).

**Comment by samdark** [comment]
Ah, so you're OK with 20 selectors but don't want 40?

**Comment by usualdesigner** [comment]
@samdark Something like that)))
