### ISSUE TITLE
Down migration by apply time.

### ISSUE THREAD

**Issue by PaVeL-Ekt** [yiisoft/yii2#7924]
Good day!
I have some troubles with migrations.
I've created new migrations m150115_test1 and m150210_test2 and applied them like m150210_test2 and then m150115_test1.
When I'm trying to migrate them down (yii migrate/down), I see the suggestion to roll back m150210_test2 migration.
How can I roll back the last migration according to its application time or name?

**Comment by nineinchnick** [comment]
I'd very like to have such option in my config how migrations are sorted by default. I could cook up a PR if everybody thinks it's a good idea.

**Comment by samdark** [comment]
Why do you apply migrations in a wrong order?

**Comment by samdark** [comment]
In general I think it's a bad idea to have this option. Migration relies on changes made by previous ones so order should be respected at all times.

**Comment by nineinchnick** [comment]
Yes but it should be the order they've been applied, not the order from their names.

**Comment by klimov-paul** [comment]
Migrations order determined by thier name, which already contains date. It is not a normal situation, when migration created ealier has been applied later.

We can of course add an extra column to store migration actual apply date, but I am usure it is actually worth it.Following the describes use case, it may produce the situation, when migration order is different at different copies of the application (e.g. dev and production). While in your copy order of migration is unnatural in other copy it will be normal, so migrating down 1 step for your 'dev' copy and 'production' copy will produce different results, which may be not desirable.

**Comment by mikehaertl** [comment]
@samdark Wrong order is very likely to happen in bigger teams, where features are developed in their own branches. New migrations can be added in different feature branches.

During tests or while merging some features into a development branch, only the migrations from the branch that gets tested or merged into development are applied - even though there may be "older" migrations in other branches. Sometimes you want to rollback, and this can get pretty ugly from a certain point.

The suggested feature could improve the situation here and give another tool to fix above problems. Of course, it would be optional.

@klimov-paul I think, application time is already stored in the `migrations` table. So it would be easy to implement.

**Comment by nineinchnick** [comment]
And it's about the dev environment mostly, I don't migrate down on production. Currently, if I mix up migrations I can't down them manually.

**Comment by fakegod** [comment]
Our team have the same problem

**Comment by PaVeL-Ekt** [comment]
I used temporary solution: 
 - new MigrateController extended from yii\console\controllers\MigrateController was created in namespace console\controllers and getMigrationHistory method was overridden. 
 - in console/config/main.php I added:
    'controllerMap' => [
        'migrate' => [
            'class' => 'console\controllers\MigrateController',
        ]
    ]

**Comment by samdark** [comment]
I wonder what could break if we'll change `getMigrationHistory` to `->orderBy('apply_time DESC')`...

**Comment by klimov-paul** [comment]
There should not be any difference in common flow.

**Comment by fakegod** [comment]
Add public property `orderBy` to controller?
If needed, config will be:
```php
return [
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'orderBy' => 'apply_time DESC',
        ],
    ],
];
```

**Comment by samdark** [comment]
I'm thinking about changing it to `apply_time` by default and not exposing any way to configure it.

**Comment by fakegod** [comment]
@samdark it's ok too

**Comment by klimov-paul** [comment]
Fix for MongoDB:
https://github.com/yiisoft/yii2-mongodb/commit/2f53c7dad9d412a7285a044b256b788433ab4b2c
