### ISSUE TITLE
save country name instead of location_id in database

### ISSUE THREAD

**Issue by rahulsinh** [yiisoft/yii2#7926]
Hii @samdark i want to save country name instead of location_id in database how to save name. 

 <?= $form->field($model, 'location_id')->dropDownList(
             ArrayHelper ::map(Location::find()->all(),'location_id','country'),
             ['prompt' => 'Select Country']
             ) ?>

**Comment by Alex-Code** [comment]
Please use the forums for questions. [Yii 2.0 Forum](http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/)

**Comment by rahulsinh** [comment]
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
      
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'program_id',
            'title',
            'location_id',
            'short_desc',
            'description:ntext',
            // 'actual_price',
            // 'discount_price',
            // 'discount',
            // 'activity_list:ntext',
            // 'availability',
            'duration_id',
            // 'supplier',
            // 'arrival_date',
            // 'departure_date',
            // 'facilities:ntext',
            'airport_id',
            // 'service:ntext',
            // 'itenary:ntext',
            // 'airport_pickup',
            // 'airport_drop',


            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
I want to show this data without gridview any body help me i am new at yii2 framwork please help.
