### ISSUE TITLE
validateAttribute in yii.activeForm

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2#7927]
I'm trying to validate some attributes and then execute some action. The problem is that the validation of `validateAttribute` of `yii.activeForm` is async. I've tried some deferred and promises from jquery without success.

```
for (var key in values) {
  $('form').yiiActiveForm('validateAttribute', key);
}
```

The behavior of `validateAttribute` seems different from `submitForm`, which calls all validations. The way it is, I can wait for that `setTimeout` in `validateAttribute` (so then, I can wait for the validation)?

**Comment by dynasource** [comment]
the correcy use of validateAttribute() should be fixed in https://github.com/yiisoft/yii2/issues/7137
