### ISSUE TITLE
Duplicated while using via (viaTable)

### ISSUE THREAD

**Issue by shcherbanich** [yiisoft/yii2#7933]
[English translation](https://github.com/yiisoft/yii2/issues/7933#issuecomment-88176724)

Например есть у меня в проекте 3 таблицы, связь многие ко многим: 
tbl_company (компании), tbl_actions (акции) и tbl_company_actions (таблица для связи).

Я хочу используя RESTful API сделать выборку сразу из всех таблиц, связав их ( например мне необходимо получить список всех компаний, которые участвуют в определенной акции ).
Создаю контроллеры и модели. 

В модели Actions прописываю связи:

```php
public function getCompanyActions()
{
        return $this->hasMany(CompanyActions::className(), ['id' => 'id_action']);
}

public function getCompanies()
{
        return $this->hasMany(Company::className(), ['id' => 'id_company'])->via('companyActions');
}
```

И добавляю в extraFields:

```php
public function extraFields()
{
        return ['companies'];
}
```

в результате при запросе < URL >/v1/actions?expand=companies 
получаю верный результат, но количество запросов равно количеству ресурсов *2:

```
SELECT * FROM `tbl_company_actions` WHERE `id_company`=1
SELECT * FROM `tbl_company` WHERE `id`=1
```

Такие запросы дублируются ровно столько раз, сколько есть записей в таблице.
Такая проблема возникает только при использовании via и viaTable

**Comment by samdark** [comment]
Например есть у меня в проекте 3 таблицы, связь многие ко многим: 
tbl_company (компании), tbl_actions (акции) и tbl_company_actions (таблица для связи).

Translation below:

I want to get data from multiple tables using RESTful API. For example, it's a list of compaines that are participating in particular promo action.

I'm creating controllers and models. 

In `Actions` models I'm defining relations:

```php
public function getCompanyActions()
{
        return $this->hasMany(CompanyActions::className(), ['id' => 'id_action']);
}

public function getCompanies()
{
        return $this->hasMany(Company::className(), ['id' => 'id_company'])->via('companyActions');
}
```


And `extraFields`:

```php
public function extraFields()
{
        return ['companies'];
}
```

As a result when accessing `< URL >/v1/actions?expand=companies` I'm getting correct data but there are (number of resources * 2) SQL queries.

```
SELECT * FROM `tbl_company_actions` WHERE `id_company`=1
SELECT * FROM `tbl_company` WHERE `id`=1
```

Such queries are repeated as many times as there are records in the table. The problem appears only when using via and viaTable.

**Comment by cebe** [comment]
Can you show the complete action code for `/v1/actions`ß

**Comment by samdark** [comment]
I guess it's just using default `\yii\rest\Action`.

**Comment by shcherbanich** [comment]
Немного упрощенная версия контроллера:

```
namespace app\modules\v1\controllers;
use Yii;
use yii\rest\ActiveController;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBearerAuth;

class ActionsController extends ActiveController {

    public $modelClass = 'app\modules\v1\models\Actions';

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                HttpBearerAuth::className(),
            ],
        ];

        $behaviors['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [
                'text/html' => \yii\web\Response::FORMAT_JSON,
                'application/json' => \yii\web\Response::FORMAT_JSON,
                'application/xml' => \yii\web\Response::FORMAT_XML,
            ],
        ];
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::className(),
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
                'Access-Control-Request-Headers' => ['*'],
                'Access-Control-Allow-Credentials' => true,
                'Access-Control-Max-Age' => 86400,
            ],
        ];
        return $behaviors;
    }

    public function checkAccess($action, $model = null, $params = [])
    {

    }
}
```
Все исключительно по документации, но запросы начинают дублироваться. Код модели такой же простой, так что проблему легко воспроизвести

**Comment by klimov-paul** [comment]
What your controller actions then? I can't see any.
If you claim query fetching 'companies' is executed per each 'Action' this means they are fetched via lazy loading. Have you attempted to use eager loading (using `with()`) for them?

**Comment by samdark** [comment]
@klimov-paul it's `ActiveController`.

**Comment by shcherbanich** [comment]
@klimov-paul, on this request  < URL >/v1/actions?expand=companies , ActiveController is using default action \yii\rest\IndexAction

**Comment by klimov-paul** [comment]
Then it is obvious.
Here is a creation of the data provider for your action:
https://github.com/yiisoft/yii2/blob/master/framework/rest/IndexAction.php#L61
Of course there is no eager loading for your 'companies' here.
You should specify `IndexAction::prepareDataProvider` with the desired `with()` calls:
```php
function() {
    return new ActiveDataProvider([
        'query' => Actions::find()->with('companies'),
    ]);
}
```

**Comment by lynicidn** [comment]
hm, if i use `expand` i should write prepare callback? Also need check $_GET['expand'] into?

**Comment by shcherbanich** [comment]
@klimov-paul, зачем мне каждый раз связывать все таблицы в ActiveDataProvider? А если у меня например там 10 других таблиц, а связь в конкретном запросе нужна только одна? 

@samdark, прошу помочь с переводом. 

не согласен с закрытием, так как предложенный @klimov-paul подход не решит данный вопрос

**Comment by klimov-paul** [comment]
I am afraid there is nothing we can do.

`Serializer` expands fields only by thier name without knowing if they are realtions or they are not.
In fact ActiveRecord does not even provide any ability to check if field is relation or not.

You are providing `extraFields()` method at your model, don't you?
If you wish this all works automatically for all your relations, you will need it to be dynamic as well.

Just as well as you specify `extraFields()` for your model, you should specify extra eager loading for the data provider created at the 'index' action. That is of course, if you want to save performance here - the action produces correct results anyway.

**Comment by shcherbanich** [comment]
@klimov-paul, maybe we can do something like that:
```
public function extraFields(){
    return [
        'table1',
        'table2' => [  
             'together' => true  // default: 'together' => false
        ]
   ];
}
```

**Comment by klimov-paul** [comment]
It will not help. `extraFields()` are called upon models, whic are already fetched from DB. At this satge it is already too late to adjust the query, which have done this fetching.

**Comment by lynicidn** [comment]
@shcherbanich вообщем тебе надо расшириться от IndexAction и переделать логику подготовки датапровайдера, в зависимости от $_GET['expand'] и не with юзай а joinWith

**Comment by shcherbanich** [comment]
@lynicidn, ну собственно я так уже и сделал, только вот мне кажется, что такое поведение должно быть по умолчанию, может быть оставить вопрос на обсуждении?

**Comment by lynicidn** [comment]
@shcherbanich да мне тоже так кажется, раз заявлено что это поддерка рест и юзаешь ты экшены конкретно рест

**Comment by shcherbanich** [comment]
in \yii\rest\IndexAction:
```
protected function prepareDataProvider()
    {
        if ($this->prepareDataProvider !== null) {
            return call_user_func($this->prepareDataProvider, $this);
        }

        /* @var $modelClass \yii\db\BaseActiveRecord */
        $modelClass = $this->modelClass;

        $query = $modelClass::find();

        $expand = explode(',', Yii::$app->request->get('expand'));

        $expand = $model->resolveExtraFields($expand);

       foreach($expand as $v){
           $query->joinWith($v);
       }

        return new ActiveDataProvider([
            'query' => $query,
        ]);
    }
```
in \yii\db\BaseActiveRecord:

```
public function resolveExtraFields(array $fields){

        $expandFields = $this->extraFields();

        foreach($fields as $k=>$v){
            if(!in_array($v, $expandFields)){
                unset($fields[$k]);
            }
        }

        return $fields;
}
```

**Comment by lynicidn** [comment]
это \yii\db\BaseActiveRecord не нужно трогать? что оно вам даст?

**Comment by shcherbanich** [comment]
@lynicidn, ошибочка, надо было в ArrayableTrait добавить, сейчас исправлю. Там нет метода подобного, только resolveFields, который делает больше, чем нужно в данной ситуации
