### ISSUE TITLE
VarDumper::export not unserializing objects correctly

### ISSUE THREAD

**Issue by PrplHaz4** [yiisoft/yii2#7935]
Discovered this by logging a variable:
`Yii::info($order, 'payments');`

Output is:
`2015-03-31 10:55:25 [192.168.4.102][-][-][info][payments] unserialize('O:13:"Stripe\\Charge":5:{s:8:"' . "\0" . '*' . "\0" . '_opts";O:26:"Stripe\\Util\\RequestOptions":2:....`

easily reproduced where `order` is an AR model:
`echo VarDumper::export($order);`

Traced it to something wrong here, but that's as far as I made it...
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseVarDumper.php#L182

**Comment by cebe** [comment]
what exactly is wrong with the output? if you log an AR object you will get the serialized version of it...

**Comment by PrplHaz4** [comment]
It's good as is.  The export facilitates an easy copy/paste to get the object back.  To see the structure of an AR object in your logs, you can log `$object->attributes` instead.
