### ISSUE TITLE
Twig widgets issue

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#7944]
I've faced with some trouble. When i tried to use the next code

```
{% set favoriteButtonOptions = {'class': 'btn btn-default spec''} %}
{{ html.addCssClass(favoriteButtonOptions, 'btn-primary') }}
```

i got an error https://www.dropbox.com/s/55h033tiy9i19ec/Screenshot%202015-04-01%2011.43.45.png?dl=0

Seems like variable passed not as reference.

**Comment by samdark** [comment]
Please report Twig issues to https://github.com/yiisoft/yii2-twig. Thanks!
