### ISSUE TITLE
createUrl outputing non-relative URL

### ISSUE THREAD

**Issue by andreCatita** [yiisoft/yii2#7948]
Hey guys,

My createUrl is outputting absoluteUrl's, in a particular circumstance.

I delved into the url rules so that I can dynamically generate frontend rules based on inputted domains in the backend from a client.

Imagine this situation in particular, two domains, to show exactly the same version and language of a website.

Example: www.core.com and www.test.com

Here is a sample of my dynamically generated rules:

```
$frontendUrlRules = [
    ['host' => 'http://www.test.com', 'pattern' => '<placeholder:(contacts)>', 'route' => 'site/contact', 'defaults' => ['lang' => 'en']],
    ['host' => 'http://www.core.com', 'pattern' => '<placeholder:(contacts)>', 'route' => 'site/contact', 'defaults' => ['lang' => 'en']],
];
```

When accessing the website, the parser from urlManager does his job correctly, meaning if I access the website through test.com, he shows me the correct hostInfo.

However, when using 'host' and defaults, 'lang' in the url configurations, urlManager->createUrl() doesn't output me a relative URL, thus returning me the first rule that matches my specifications:

Example:

```
\Yii::$app->urlManager->createUrl('site/contact', 'placeholder' => 'contacts', 'lang' => 'en');
```

And it returns me: http://www.test.com/contacts even if I accessed the website through http://www.core.com, and the createAbsoluteUrl doesn't change anything, because the createUrl is already returning full URLs.

**Comment by andreCatita** [comment]
If this is not a bug, and was intended as a feature somehow, we should a setHostInfo, that createUrl uses.
Otherwise, we can't have two domains, showing the same content and language of the website.

**Comment by andreCatita** [comment]
Here is my temporary fix, that is to take the host into attention, in UrlRule.php

```
        // fix duplicated rule per host
        if (!empty($this->host) && \Yii::$app->urlManager->getHostInfo() != $this->host)
            return false;
```

**Comment by dynasource** [comment]
please look at the guide for host based rules http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#rules-with-server-names

**Comment by andreCatita** [comment]
Hello,

I don't remember this when I first started using Yii2 Url Rules.
However, the specific UrlRule (http://www.yiiframework.com/doc-2.0/yii-web-urlrule.html) host property, shouldn't it be respected?

As in, 

	['host' => 'http://www.website.com', 'pattern' => '<slug:(search)>', 'route' => 'products/search', 'defaults' => ['lang' => 'en']],
	['host' => 'http://www.website.fr', 'pattern' => '<slug:(search)>', 'route' => 'products/search', 'defaults' => ['lang' => 'fr']],
	
Why when routing to products/search, inside website.fr, I get redirected to website.com? That's my question. 	Is it on purpose? If it is, then I'll just keep my solution around. 
But seems weird to me that it stops at the first rule without looking up at the host.

**Comment by dynasource** [comment]
thanks for your quick reply. With respect to your usecase, can you point us to the source code in which you think a bug is occurring?

**Comment by andreCatita** [comment]
yii2\web\UrlRule.php @ 2.0.10 (for example)

If you take a look at createUrl here, it doesn't validate the 'host' even if it's set. There was a guide (or is somewhere) with an example, with explicit hosts in the rules. I like it this way, it's clearer.

Hence why I added the following: 

        if (!empty($this->host) && \Yii::$app->urlManager->getHostInfo() != $this->host)
            return false;

**Comment by rob006** [comment]
> Hence why I added the following:

This change is invalid. It make impossible to create URL to different domains than current one, for example create URL to backend (admin.example.com) from frontend (example.com).

> Otherwise, we can't have two domains, showing the same content and language of the website.

This works perfectly fine: #13351

**Comment by samdark** [comment]
Closed since there's valid use case @rob006 provided tests for.

**Comment by andreCatita** [comment]
Instead of adding params, why not just have createUrl check the host? It's an already existent parameter.

**Comment by rob006** [comment]
https://github.com/yiisoft/yii2/issues/7948#issuecomment-271158049

>  It make impossible to create URL to different domains than current one, for example create URL to backend (admin.example.com) from frontend (example.com).

If you don't care about that, you can use custom URL manager or URL rule class.
