### ISSUE TITLE
 safe validator on condition 

### ISSUE THREAD

**Issue by pkjoshi** [yiisoft/yii2#7951]
I am trying to use this rule in my model, but it's not working.
I mean it always remains safe even if select other option.

I have no other rules setup for this attribute.

```
[['dhanwantri_bill_number'], 'safe', 'when' => function($model) {               
                return $model->bill_type =='d';                 
            }, 'whenClient' => "function (attribute, value) {
                return $('#opdtestbill-bill_type').val() == 'd';
            }"],
```
Am I doing anything wrong?

**Comment by fernandezekiel** [comment]
@pkjoshi  afaik this isn't possible this way, the safeness of the attribute is determined on the assignment,
`when` is something that executed ON the `validate()` call

**Comment by pkjoshi** [comment]
Does that mean I am reading the docs wrong? which say that `when` is available as callable on `safe` validator. if `when` is available on `safe` validator, how it can be used if not in the way I have mentioned.
Thanks.

**Comment by fernandezekiel** [comment]
not exactly, what i'm saying is that safe and unsafe validators are the exception to the case, because their role only is to dictate if the attribute can be overwritten on the massive-assignment or not. Even though the safe validator has the `when` property, it has no use in for it

**Comment by cebe** [comment]
> @pkjoshi afaik this isn't possible this way, the safeness of the attribute is determined on the assignment,
> when is something that executed ON the validate() call

exactly.

@pkjoshi when is available on the safe validator class but the safe validator itself does not perform any validation. It is used to determine in which scenario an attribute should be changed. It is not a realy validator so when has no effect on its validation.
