### ISSUE TITLE
Rename:  basic/advanced application template → basic/advanced project template

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#7956]
I propose renaming basic/advanced *application* template to basic/advanced *project* template. The reason is advanced one which contains multiple tiers which are applications in Yii terms. So overall now it's confusing that application contains 2 applications.

No code changes required, it's just terminology.

**Comment by samdark** [comment]
@yiisoft/core-developers thoughts?

**Comment by qiangxue** [comment]
Fine with me.

**Comment by klimov-paul** [comment]
Make sense.

**Comment by samdark** [comment]
Done.

**Comment by cebe** [comment]
:+1:
