### ISSUE TITLE
Attempt to assign property of non-object

### ISSUE THREAD

**Issue by constant0924** [yiisoft/yii2#7960]
Run the project，
appear：
PHP Warning – yii\base\ErrorException
Attempt to assign property of non-object

Wrong location in /Users/Rio-hl/Documents/project/tmsheji/vendor/yiisoft/yii2/log/Dispatcher.php   Line127

View the source code：

public function setLogger($value)
    {
        $this->_logger = $value;
        $this->_logger->dispatcher = $this;    //This out of an error
    }

When I comment the bank code：

public function setLogger($value)
    {
        $this->_logger = $value;
        //$this->_logger->dispatcher = $this;    //This out of an error
    }

Program to run normally！How to solve this problem? For help

**Comment by mdmunir** [comment]
?
How you use the `log` (how your code)?

**Comment by constant0924** [comment]
I'm just a simple installation process, after installation, direct returns this error message, my 5.5.14 PHP version

**Comment by constant0924** [comment]
@mdmunir I'm just a simple installation process, after installation, direct returns this error message, my 5.5.14 PHP version

**Comment by mdmunir** [comment]
app-basic or app-advanved?

**Comment by constant0924** [comment]
app-advanved

**Comment by mdmunir** [comment]
have you do `init` aplication? are you sure not add or cange something code?
Please provide your error trace.

**Comment by constant0924** [comment]
already init aplication！
![dbd54657-131f-4f70-af2a-f9823859e476](https://cloud.githubusercontent.com/assets/3156863/6959495/5390c63a-d94c-11e4-9caf-b44da2ed4c52.png)

**Comment by mdmunir** [comment]
Click `Log` button in `Yii Debuger Toolbar`. Scroll the page, find log error. copy and paste error maessage here.

PS: better you ask this in Yii forum or Yii facebook page.

**Comment by constant0924** [comment]
Direct access to http://localhot:8080 has been this error, no debugger toolbar button

**Comment by mdmunir** [comment]
Are you sure not make any changing in your code. What tutorial that you are using for install.

**Comment by constant0924** [comment]
Didn't do any change, use the  ```composer```  for installation

**Comment by samdark** [comment]
Install clean advanced app and try running it. Anyone?

**Comment by constant0924** [comment]
@samdark Now I'm just a man，Have reinstall many times, the same problem still appear, can is a PHP version problem??

**Comment by mdmunir** [comment]
@samdark 
I install clean advanced app a minute ago. Its going OK.

@constant0924 
Of course. actually isnt problem if you get `a problem`. a truly problem is, if you dont know how to resolve the problem. Improve your programing skill.
Scroll your page, you will see when `Dispatcher::setLogger()` called.

**Comment by bhavuksuthar** [comment]
I am having same issue but i am not working on new project.
I just restarted the PC and start the php server 
and i got this error

any idea what could have caused this?

**Comment by constant0924** [comment]
@bhavuksuthar So far I don't know what causes, but my solution is to find an error location, change the line of code.
After a long time, I once again return to the original code, but won't appear the problem!

**Comment by bhavuksuthar** [comment]
but i didnt do any changes
my JetBrains was causing problem with debugging so i was making changes in php.ini file
and suddenly my project stopped working

The copy i downloaded from live web server stopped working on my local environment
and this is happening with every yii2 projects
yii1 projects in my localhost is still working fine

**Comment by bhavuksuthar** [comment]
here is my php.ini 
not that it should affect yii2 framework but still

`zend_extension = "C:\xampp\php\ext\php_xdebug.dll"`
`xdebug.profiler_append = 1`
`xdebug.auto_trace = 1`
`xdebug.collect_assignments = 1`
`xdebug.profiler_enable = 1`
`xdebug.profiler_enable_trigger = 0`
`xdebug.profiler_output_dir = "C:\xampp\tmp"`
`xdebug.profiler_output_name = "cachegrind.out.%t-%s"`
`xdebug.remote_enable = 1`
`xdebug.remote_enable=true`
`xdebug.remote_host=localhost`
`xdebug.remote_port=9000`
`xdebug.remote_handler=dbgp`

**Comment by constant0924** [comment]
@bhavuksuthar Has nothing to do. I think that with PHP ini configuration. Have you ever try to debug and modify? This problem can't not yet found the cause is

**Comment by bhavuksuthar** [comment]
Xdebug is not working right now in my pc so i dont know any other way to debug this right now except the default error page i am getting right now

**Comment by rossoneri** [comment]
meet same problem, just change the code in Dispatcher class to:
```
$value->dispatcher = $this;
$this->_logger = $value;
```
then the error disappeared!

And the error only occurs when i enable xdebug, so I think it's about xdebug, anyone can explain this?
