### ISSUE TITLE
Maybe StringValidator should also have a list of acceptable characters?

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#7962]
Even though this can be easily done with another validator (RegexValidator) it would be kinda cool for code reduction to have this functionality all in one validator me thinks.

It is also quite logical since you want to define a set of acceptable characters for a string.

**Comment by cebe** [comment]
what is the use case for allowing certain characters only?

**Comment by Sammaye** [comment]
Most commonly: usernames

**Comment by qiangxue** [comment]
This is better to be done by separate rules for separate of concerns. Otherwise you can say the same thing for nearly all other kinds of string-based validation (such as date/number inputs in strings).
