### ISSUE TITLE
UniqueValidator should take a action param so it can client side validate

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#7963]
Would be good if we can add client side unique validation by adding a `action` param to the validator which returns a standardised response of whether the field is unique or not, especially helpful for username validation.

**Comment by mdmunir** [comment]
Why not using ajax validation?

**Comment by Sammaye** [comment]
What do you mean? You mean code it myself? Yes that is what I am actually doing but would be good if the validator had an action param so that it could do AJAX validation itself within it's own runtime

**Comment by mdmunir** [comment]
I mean, with set `ActiveForm::$enableAjaxValidation` to true.

**Comment by Sammaye** [comment]
Ah I see now, that seems to be it actually thanks
