### ISSUE TITLE
i18n source language fallback should not search for a message file

### ISSUE THREAD

**Issue by EagleMoor** [yiisoft/yii2#7964]
```
192.168.100.111][-][-][error][yii\i18n\PhpMessageSource::loadMessages]
The message file for category 'yii' does not exist:
/srv/www/jtapp-dev.wayjournal.com/vendor/yiisoft/yii2/messages/en/yii.php
```
on

```php
public function fields()
    {
        return [
            'start_dt' => function() {
                return \Yii::$app->formatter->asDatetime($this->date_time);
            }
        ];
    }
```

config/web.php
```php
...
    'sourceLanguage' => 'en-US',
    'language' => 'en',
    'components' => [
        'formatter' => [
            'datetimeFormat' => 'yyyy-MM-dd HH:mm:ssZ',
            'dateFormat' => 'yyyy-MM-dd',
            'thousandSeparator' => ''
        ],
    ]
...
```

**Comment by EagleMoor** [comment]
Just add yii2/messages/en/yii.php

```php
<?php return [];
```

**Comment by cebe** [comment]
How did you configure i18n component?

**Comment by lynicidn** [comment]
related https://github.com/yiisoft/yii2/issues/7883 ?

**Comment by cebe** [comment]
@lynicidn not related, but I see the problem now, it is trying to translate from `en-US` to `en` but that does not work because we have no files for en because it is the source language...
A similar problem arises when you change source language of the app to `en-GB`, which will then try to translate from `en-GB` to `en-US`. Maybe the check there can be more intelligent.
However it may be desireable to translate from source `de-DE` to `de-AT` or `de-CH` so consideration needs to be made carefully.

**Comment by EagleMoor** [comment]
i18n global config default, but config for module - 

```php
<?php
/**
 * Created by PhpStorm.
 * User: EagleMoor
 * Date: 16.01.15
 * Time: 15:31
 */

namespace app\modules\obd;

use yii\helpers\VarDumper;
use yii\i18n\MissingTranslationEvent;

class Module extends \yii\base\Module
{

    //public $controllerNamespace='api\modules\v1\controllers';

    public function init()
    {
        parent::init();
        $this->registerTranslations();
    }

    public function registerTranslations()
    {
        \Yii::$app->i18n->translations['modules/obd/*'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'basePath' => '@app/modules/obd/messages',
            'sourceLanguage' => 'en',
            'forceTranslation' => true,
            'fileMap' => [
                'modules/obd/alarm' => 'alarm.php',
                'modules/obd/track' => 'track.php'
            ],
            'on missingTranslation' => function(MissingTranslationEvent $event) {
                if ($event->language != \Yii::$app->sourceLanguage) {
                    $event->translatedMessage = \Yii::t($event->category, $event->message, [], \Yii::$app->sourceLanguage);
                }

                \Yii::info("@MISSING: {$event->category}.{$event->message} FOR LANGUAGE {$event->language} @", 'translate');
            }
        ];
    }

    public static function t($category, $message, $params = [], $language = null)
    {
        return \Yii::t('modules/obd/' . $category, $message, $params, $language);
    }
}
```

Maybe it's forceTranslation ? But i add this config not for all i18n.

**Comment by thejahweh** [comment]
Here is a workaround
```php
'i18n' => [
	'translations' => [
		'yii' => [
			'class' => 'yii\i18n\PhpMessageSource',
			'sourceLanguage' => 'en',
			'basePath' => '@yii/messages'
		],
	],
]
```

It just sets the `sourceLanguage` for yii to `en`, so if the language is set to `en-US` and there is no en-US file it does the fallback to en, which is the source language and does not require a language file.

**Comment by EagleMoor** [comment]
@thejahweh i try any variation. With ```forceTranslation``` i18n try translate all time, but he can't find yii2 translate messages with ```en```

**Comment by MaXL-ru** [comment]
@cebe why you can not add yii2/messages/en/yii.php file, which return empty array, as @EagleMoor offered ?

In my case, $lagnuage = 'en-GB' in Yii application, and there lot of trash in application logs:
> The message file for category 'yii' does not exist: ...vendor/yiisoft/yii2/messages/en-GB/yii.php Fallback file does not exist as well: ...vendor/yiisoft/yii2/messages/en/yii.php

**Comment by SDKiller** [comment]
Got similar problem - numerous `The message file for category 'yii' does not exist` when setting app language to `en` instead of default `en-US`

@cebe 
> ...it is trying to translate from en-US to en but that does not work because we have no files for en because it is the source language...
... Maybe the check there can be more intelligent...
+1

**Comment by EagleMoor** [comment]
If we set forceTranslate problem return. Need include translate on en (en-US) file to project. It's help to write translate for other language too

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/8057

**Comment by SilverFire** [comment]
Fixed
