### ISSUE TITLE
Problems of validation AR

### ISSUE THREAD

**Issue by shcherbanich** [yiisoft/yii2#7968]
Create table 
```
CREATE TABLE  tbl_test (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  is_required int(10) unsigned  DEFAULT '0',
PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='test' AUTO_INCREMENT=1 ;
```

and use this validation rules in ActiveRecords model : 

```
public function rules()
{
        return [
            [['is_required'], 'required'],
        ]
}
```
rules don't work because AR set default value  is_required = 0.

**Comment by samdark** [comment]
What do you mean by don't work?

**Comment by qiangxue** [comment]
The validator works as expected. Its your responsibility to clear the default value of `is_required` if you don't want it.

**Comment by shcherbanich** [comment]
It's not correct because this rules for certain situation. Framework shouldn't use table default values in this case

**Comment by samdark** [comment]
How should it know in which case you need default values and in which you don't?

**Comment by shcherbanich** [comment]
loadDefaultValues()
