### ISSUE TITLE
Add \yii\web\Controller::bindActionParams from all request types, not only GET

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7969]
Had a hard time and big upset finding why it throws "Missing parameter" exception while parameter was clearly visible in browser debugger.

Had to add this somewhere deep in my additions to Yii2:
```php
namespace myvendor\yii2\mvc;
use yii\base\InlineAction;
trait ActionParamsBoxingTrait {
    public function bindActionParams($action, $params) {
        $request = \Yii::$app->getRequest();
        $params = array_merge($params,$request->getBodyParams());
        /* ... */
    }
}
```

P.S. By the way, what's with #7181 ?

**Comment by cebe** [comment]
these are explicitly only from GET. http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html#action-parameters

**Comment by mcd-php** [comment]
OK, so I have to live with it.

But what is exact reasoning behind making it GET-only ? I want to understand this in full - what if I'm making a mistake adding POST, and will regret it later.

**Comment by samdark** [comment]
Mixing URL parameters with form parameters is generally bad practice that could lead to security issues.

**Comment by mcd-php** [comment]
Aha, got it. But how do you see the solution for removing parameter extraction and validation code from actions, for all HTTP methods.

I now have:
```php
public function actionShootInFoot(DbIdParam $foot_id) {
/* ... */
}
```
and just added POST to auto-boxing. ( *Param classes have filters, validators and throw "bad request" exceptions if bad argument ).

How should I rework it to have no security issues and PR it into Yii2, so getting rid of extra parts ?

**Comment by samdark** [comment]
To have no security issues you should not mix parameters from GET and POST.

**Comment by cebe** [comment]
this looks a lot like magic, which imo should not be introduced at this point.
