### ISSUE TITLE
MessageFormatter does not work properly in PHP 5.6.7

### ISSUE THREAD

**Issue by anton-p-ivanov** [yiisoft/yii2#7971]
When trying translate a plural message like:

```
\Yii::t('app', 'Notice: currently {n, plural, =0{no location} =1{1 location} other{# locations}} selected.', ['n' => 100]);
```

error message thrown: 

```
PHP Fatal Error: Unsupported operand types
```

Error located in /var/www/assist/vendor/yiisoft/yii2/i18n/MessageFormatter.php (line 403)

PHP 5.6.7 (Debian 7), Yii 2.0.3

**Comment by samdark** [comment]
Can you post full stacktrace?

**Comment by samdark** [comment]
Which intl version do you have?

**Comment by yapi68** [comment]
I got it! I have no php5-intl extension installed. Install it with 

    apt-get install php5-intl 

to fix the problem.

**Comment by cebe** [comment]
still looks like  a bug in the fallback implementation...

**Comment by nkovacs** [comment]
I was unable to reproduce this. @yapi68 you probably have a translation that's different than what's in the Yii::t call you've posted, and that may be causing the bug. Could you post the translation please?

**Comment by uaoleg** [comment]
Fallback implementation doesn't work properly for such call:

```
<?= \yii::t('app', '{n, plural, =0{No members yet} =1{# member} other{# members}}', ['n' => $invite->team->members]) ?>
```

Stacktrace:

```
1. in /var/www/myproject/vendor/yiisoft/yii2/i18n/MessageFormatter.php at line 403
394395396397398399400401402403404405406407408409410411412 
                    if ($i == 1 && strncmp($selector, 'offset:', 7) === 0) {
                        $offset = (int) trim(mb_substr($selector, 7, ($pos = mb_strpos(str_replace(["\n", "\r", "\t"], ' ', $selector), ' ', 7)) - 7));
                        $selector = trim(mb_substr($selector, $pos + 1));
                    }
                    if ($message === false && $selector == 'other' ||
                        $selector[0] == '=' && (int) mb_substr($selector, 1) == $arg ||
                        $selector == 'one' && $arg - $offset == 1
                    ) {
                        $message = implode(',', str_replace('#', $arg - $offset, $plural[$i]));
                    }
                }
                if ($message !== false) {
                    return $this->fallbackFormat($message, $args, $locale);
                }
                break;
        }
 
        return false;
2. yii\base\ErrorHandler::handleFatalError()
```

**Comment by nkovacs** [comment]
It happens if `n` is something that can't be added to an integer, e.g. an array:

<?= \yii::t('app', '{n, plural, =0{No members yet} =1{# member} other{# members}}', ['n' => [1, 2]]) ?>

intl does something strange in this case, probably converts the array pointer to an int:
"140038165285992 members"

**Comment by uaoleg** [comment]
@nkovacs, you are right, I had NOT integer in my case.

**Comment by MattRh** [comment]
Is there any sence in this issue, as modern yii versions will not support php <7.1?

**Comment by samdark** [comment]
Probably not.
