### ISSUE TITLE
issue with wrong using substr() result

### ISSUE THREAD

**Issue by veyselsahin** [yiisoft/yii2#7975]
when i was wrote code like this image
![screenshot_1](https://cloud.githubusercontent.com/assets/2998379/6977250/6ae8c6f4-d9c2-11e4-895a-65c1a08a6f07.png)

the result was like that. i cannot find error and debugger pane or phpstorm debugger not working.
after mistake page result is like below img evertime.
![screenshot_2](https://cloud.githubusercontent.com/assets/2998379/6977259/a22c2d2c-d9c2-11e4-87b4-062380a33e47.png)

**Comment by samdark** [comment]
What's in logs?

**Comment by mdmunir** [comment]
use `==` or `===` instead of `=`.

PS: better you asking in forum or FB page.

**Comment by veyselsahin** [comment]
i know i must use == or === instead of =. but if i use this style(error) i cannot see exception or php error on page. i just see page which i was sent with second screenshot.

**Comment by samdark** [comment]
Could it be reproduced with simpler code?

**Comment by veyselsahin** [comment]
yes i was reproduced my code and just this line causes error.

**Comment by samdark** [comment]
OK. Could you take the line and somhow move it to basic app so it's reproduced?

**Comment by veyselsahin** [comment]
yes i will and write again.Thanks @samdark.

**Comment by klimov-paul** [comment]
Unable to reproduce.
Following code:
```php
$p = 'test';
        $sid = 'some';
        if (substr($p, 0, strlen("s" . $sid)) = "s" . $sid) {
            ;
        }
```
produces correct exception page saying "Can't use function return value in write context".
