### ISSUE TITLE
Custom URL with parameters in yii2

### ISSUE THREAD

**Issue by herisetiyawan** [yiisoft/yii2#7977]
hai all, 
how change this url 
<pre>
index.php/dev/index?id=2
</pre>
to
<pre>
index.php/custom-own-url
</pre>

 in yii2 ?
Thank you

**Comment by samdark** [comment]
By using http://www.yiiframework.com/doc-2.0/yii-web-urlrule.html#$defaults-detail:

```php
[
    'route' => 'dev/index',
    'pattern' => 'custom-own-url', 
    'defaults' => [
        'id' => 2,
    ],
]
```

Or by using a slug if you need to support multiple URLs.

btw., please use forum for questions that aren't bugs or feature requests.

**Comment by herisetiyawan** [comment]
Thank you so much @samdark ,I 've asked this question in the forums and facebook before , but I have not the right answer for this case

<pre>http://www.yiiframework.com/forum/index.php/topic/62952-how-create-custom-url-in-yii2/page__p__277954#entry277954</pre>
and 
https://www.facebook.com/groups/yii.indonesia/
https://www.facebook.com/groups/yiitalk/
