### ISSUE TITLE
DRY in rbac DBManager

### ISSUE THREAD

**Issue by Sepuka** [yiisoft/yii2#7980]
Am using 2.0.4-dev Yii version and probably code is duplicated:
in func getItem() do

```
if (!isset($row['data']) || ($data = @unserialize($row['data'])) === false) {
  $row['data'] = null;
}
return $this->populateItem($row);
```

than in populateItem() func code

```
if (!isset($row['data']) || ($data = @unserialize($row['data'])) === false) {
  $data = null;
}
```

**Comment by miraage** [comment]
As I see, this `populateItem` is also used by `getRolesByUser`, `getPermissionsByRole`, `getPermissionsByUser`, `getChildren` and `loadFromCache`.
Could you please read code better next time? :)

**Comment by Sepuka** [comment]
What has chanded if i remove the above lines in getItem() ? populateItem() do all work
