### ISSUE TITLE
theme, problem defaultExtension and twig

### ISSUE THREAD

**Issue by nepster-web** [yiisoft/yii2#7984]
I use a theme and Twig.

yii2 can not find the twig file in the my theme because this code:

/vendor/yiisoft/yii2/base/View.php:

```
        if ($this->defaultExtension !== 'php' && !is_file($path)) {
            $path = $file . '.php';
        }
```

always changing extension twig on the php.

More details on the Russian forum:
http://yiiframework.ru/forum/viewtopic.php?f=19&t=23340&p=139418#p139418

**Comment by samdark** [comment]
Please report to https://github.com/yiisoft/yii2-twig. Thanks!

**Comment by nepster-web** [comment]
but controversial code is in the file /vendor/yiisoft/yii2/base/View.php.
it relates to the theme.

**Comment by samdark** [comment]
It's about fallback when using any template, not about twig itself. Yii tries "php" file in theme instead of template's one.

**Comment by nepster-web** [comment]
Александр, если позволите, я попробую объяснить максимально подробно на русском. А то возможно мой топорный английский не понятен. 

К примеру мы используем твиг и храним все виды в следующей папке: 
frontend\modules\site\views\default.  

Рассмотрим пример на файле frontend\modules\site\views\default\index.twig

Все работает все хорошо. 

Теперь наша задача использовать тему, мы создаем файл index.twig в папке с темой:
frontend\themes\modules\site\views\default\index.twig. 

И это тоже работает. Тема успешно подхватывает файл. 

А вот дальше мы понимаем, что файл frontend\modules\site\views\default\index.twig нам не нужен, так как мы используем тему. Поэтому мы его удаляем и оставляем только файл из папки темы. 

А вот тут получается проблема.
Так как yii2 функцией !is_file($path) не находит файл 
frontend\modules\site\views\default\index.twig. 

Он меняет расширение twig на php и только потом тема пытается найти 
frontend\themes\modules\site\views\default\index.php, которого нет (в место него есть index.twig).

И получается что если файлов в нужно месте нет и они не .php, то темизация не работает.

**Comment by lynicidn** [comment]
try rename file to `*.twig.php`
