### ISSUE TITLE
yii2 can encrypt javascript assets ?

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#7987]
well, i have this dude, yii2 can encrypt the javascript in the assets ? for increase the security of the applications ?

**Comment by lynicidn** [comment]
http://en.wikipedia.org/wiki/Bug_tracking_system

**Comment by samdark** [comment]
No, it can't.

**Comment by spiritdead** [comment]
@samdark but before closing the card could not be regarded as one improvement for future versions?

**Comment by samdark** [comment]
I don't think "encrypting" JavaScript is any helpful regarding security. If you need your scripts turn into unreadable mess before actually served to the client it could be done with `asset/compress` command.
