### ISSUE TITLE
Console model errorSumary()

### ISSUE THREAD

**Issue by manquer** [yiisoft/yii2#7988]
`\yii\helpers\Html::errorSummary()` does a good job of parsing error data and rendering it for Html rendering,

however there is no similar functionality for console applications, i.e. formatted error Output from model errors in  console application , It would useful addition to the Console helper tools

**Comment by cebe** [comment]
can you explain in more detail how you use model validation on console?

**Comment by manquer** [comment]
Typically I write bulk import /file processing operations in my console actions. 

It is useful to do this using console application as for large uploads / bulk imports  it is better to do the processing( when it make take  few minutes or more etc) asynchronously rather than while the request is made . 

1. In this scenario Initial request on the web is made , the object is queued for processing and then console action does the actually processing ( via scheduled cron / long running worker process listening to a queue etc ). 

2. Validations are performed when save() ic called as is usual. 

3. All the errors are piped to file and/or sent as an email to the uploading user. Here un-formatted or text formatted output is better than only HTML formatted output.

Another slightly different use case is throwing validation errors in REST actions, HTML validated output just comes in the way of parsing the errors. Array output is required ( Although models->getErrors() is basically an array an custom function has to be written anyway to parse a group of models )

Currently I use couple of hack helpers functions extending HTML::errorSummary to handle this, However it would be nice to have other errorSummary formats like for un-formatted text, formatted for stderr, and  json output etc
