### ISSUE TITLE
Errors in "how-to-contribute"

### ISSUE THREAD

**Issue by pabloassembler** [yiisoft/yii2#7991]
In Yii2 repository, there is a **readme.md** citing a ***"how to participate"*** pointing to **getting-started.md** *( text link tells about a composer package )*. In **getting-started.md** there are some instructions and an ask to refer to ***"Git workflow for Yii 2 contributors"***. There, you will find more complete instructions.

All these instructions are different one anuther. I could not understand how is the recommended way to start contributing. I think someone should review this quickly because this is just preventing more help to come.

**Comment by cebe** [comment]
I do not see the difference, can you point it out in more detail or describe what is unclear?

**Comment by pabloassembler** [comment]
OK. Let's go:

* 1 . In [readme.md] (https://github.com/yiisoft/yii2/blob/master/README.md#how-to-participate), in a section called ***"how to participate"*** there is a link exactly reproduced here:

     >In order to make it easier we've prepared [special `yii2-dev` Composer package.](https://github.com/yiisoft/yii2/blob/master/docs/internals/getting-started.md)
  * 1.1. The text on the link tells about a ***"special yii2-dev Composer package"***, but the links point to a page instructing to **git clone** the repo and run some commands. The text tells *the commands runs composer on background*. Is this text correct? Is it the way to work on **yii2-dev** composer package ?
* 2 . In the **getting-started.md** page stated above ([link](https://github.com/yiisoft/yii2/blob/master/docs/internals/getting-started.md)), just before **Unit tests**, there is a phrase with a link:

 >Please refer to [Git workflow for Yii 2 contributors](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) for details about creating pull requests.
  * 2.1. I though this last document would be the most complete available about the ***"contributing workflow"***. Curiously, this document only deals with git commands. There is no *cli* commands between **git clone** and **git add remote upstream**.
* 3 . Last, after seeing some inconsistency in these instructions, I felt lost in directory structure.

Please let me know if the docs are all correct and it's only me not getting the point.

**Comment by cebe** [comment]
I see the confusion now, will try to improve the instructions to be more clear.
