### ISSUE TITLE
Use of SUBSTRING in SQL statement creates invalid SQL

### ISSUE THREAD

**Issue by chrisb34** [yiisoft/yii2#7994]
The following statement generates SQL with quotes in the wrong places;

 Donation::find()->select("donation.*,  SUBSTRING(donation.description, {$rand},1) AS randcharx")

generates

    SELECT `donation`.*, SUBSTRING(donation.description, `9`, `)` AS `randcharx` FROM `donation`
    // corrected version note order of quotes in substring
    SELECT `donation`.*, SUBSTRING(donation.description, `9`, `1`) AS `randcharx` FROM `donation` 

But why quote the numerals in SUBSTRING anyway?

**Comment by nineinchnick** [comment]
Could you edit this issue and use code tags, so the quotes would be visible?

**Comment by nineinchnick** [comment]
Also, can you test what'd be the output when using Yii's quoting?

~~~php
$query = "donation.*, SUBSTRING(donation.[[description]], {$rand},1) AS [[randcharx]]";
Donation::find()->select($query)
~~~

**Comment by chrisb34** [comment]
Yes, Yii's quoting works OK.

**Comment by klimov-paul** [comment]
Duplicates #3078
