### ISSUE TITLE
Relation without ActiveRecord

### ISSUE THREAD

**Issue by nkostadinov** [yiisoft/yii2#7995]
Is it possible to have a table joined to an AR instance without having AR class. I am creating an extension which manages tags(in external table) and this table doesn't have a corresponding AR class. I want to achieve something like this:

```
$posts = Post::find()->with('properties')->one();
//and then accessing properties like this
echo $posts->properties['name'];
```

Is this possible ?

**Comment by klimov-paul** [comment]
Relations can not queried without an ActiveRecord class, which declares them. This is obvious.
