### ISSUE TITLE
MongoDB, call fetchRows() without $indexBy

### ISSUE THREAD

**Issue by AstRonin** [yiisoft/yii2#7997]
Hi all,

In `yii\mongodb\ActiveQuery` we have method all():
```php
public function all($db = null)
{
    $cursor = $this->buildCursor($db);
    $rows = $this->fetchRows($cursor);

    return $this->populate($rows);
}
```

Why we don't use `indexBy` as it used in `yii\mongodb\Query`? For example:
```php
public function all($db = null)
{
    $cursor = $this->buildCursor($db);
    $rows = $this->fetchRows($cursor, true, $this->indexBy);

    return $this->populate($rows);
}
```

**Comment by klimov-paul** [comment]
Because there is no need for it.
It will be applied at `createModels()`:
https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQueryTrait.php#L119
