### ISSUE TITLE
Controller::getView always get Yii::$app->view

### ISSUE THREAD

**Issue by onman** [yiisoft/yii2#7999]
If yii\base\Controller::view is not specifically set it will always get Yii::$app->getView().
When the controller belongs to a module it seems more logical to first try to get the view component from the module.

yii\base\Controller:

public function getView()
{
...if ($this->_view === null) {
......if ($this->module->has('view') {
.........$this->_view = $this->module->get('view')
......} else {
.........$this->_view = Yii::$app->getView();
......}
...}

...return $this->_view;
}

**Comment by cebe** [comment]
why do you need a view component on the module?

**Comment by onman** [comment]
I am developing a module which has a different theme than the rest of application. 



Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Carsten Brandt <notifications@github.com> </div><div>Datum:07-04-2015  01:03  (GMT+01:00) </div><div>Aan: yiisoft/yii2 <yii2@noreply.github.com> </div><div>Cc: onman <o.rijkers@chello.nl> </div><div>Onderwerp: Re: [yii2] Controller::getView always get Yii::$app->view (#7999) </div><div>
</div>why do you need a view component on the module?

**Comment by qiangxue** [comment]
Module doesn't have `view` component by default. For your use, you should create a new base controller class and implement the `getView()` method as you want.

**Comment by onman** [comment]
I already went that way, but I'll have to adjust third party modules to do the same. I was hoping to avoid that, 'cause I need to do that each time such a module is updated.

Aside from my specific situation I figured it would be more logical to use a module's component over an application's one (if it is defined, of course).


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Qiang Xue <notifications@github.com> </div><div>Datum:07-04-2015  14:23  (GMT+01:00) </div><div>Aan: yiisoft/yii2 <yii2@noreply.github.com> </div><div>Cc: onman <o.rijkers@chello.nl> </div><div>Onderwerp: Re: [yii2] Controller::getView always get Yii::$app->view (#7999) </div><div>
</div>Module doesn't have view component by default. For your use, you should create a new base controller class and implement the getView() method as you want.

**Comment by qiangxue** [comment]
If your goal is only to use a different theme, there are other ways to achieve your goal rather than relying on a view component replacement. For example, in your module's `init()` method you can customize the application view's theme.

**Comment by onman** [comment]
I know, I've already resolved it for my own code, but I'm still running into the problem that I need to change third party code to use my own base controller or base module (if I would change the Module::createController() to set the controller's view property) .




Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Qiang Xue <notifications@github.com> </div><div>Datum:07-04-2015  15:18  (GMT+01:00) </div><div>Aan: yiisoft/yii2 <yii2@noreply.github.com> </div><div>Cc: onman <o.rijkers@chello.nl> </div><div>Onderwerp: Re: [yii2] Controller::getView always get Yii::$app->view (#7999) </div><div>
</div>If your goal is only to use a different theme, there are other ways to achieve your goal rather than relying on a view component replacement. For example, in your module's init() method you can customize the application view's theme.

**Comment by qiangxue** [comment]
Nope, my last suggestion wasn't about using your base controller. Instead, I was suggesting you customize the theme in your module's `init()` method.

**Comment by onman** [comment]
Yes, I understand that, but If I'm using a third party module I would still need to edit that module's code to use my custom theme.


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Qiang Xue <notifications@github.com> </div><div>Datum:08-04-2015  04:00  (GMT+01:00) </div><div>Aan: yiisoft/yii2 <yii2@noreply.github.com> </div><div>Cc: onman <o.rijkers@chello.nl> </div><div>Onderwerp: Re: [yii2] Controller::getView always get Yii::$app->view (#7999) </div><div>
</div>Nope, my last suggestion wasn't about using your base controller. Instead, I was suggesting you customize the theme in your module's init() method.

**Comment by lynicidn** [comment]
module not only for web app, also for console. console have not support theme

**Comment by cebe** [comment]
@lynicidn in that case you can check if `Yii::$app` is an instance of web application

**Comment by lynicidn** [comment]
@cebe i think need yii\base as common and yii\web for web - yii\web\Module

**Comment by onman** [comment]
In my own base module I've just implemented a more generic solution which may be an option for yii2 as well.

I've redefined the module's get() and has() methods as follows:
1. Check if current module has the service/component defined. If so, return it. 
2. Else return $currentModule->module->get (...) ; i.e. the parent module's get() 
3. Controllers always request/get() a 'service' from their own  module. If that module does not have the service defined it will automatically fall back to It's parent's module (which eventually is the application).

I realise this may not be 100% backwards compatible, but maybe you can give it a thought for a future release.

Of course right now it doesn't change my issue with third party extensions.


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Carsten Brandt <notifications@github.com> </div><div>Datum:08-04-2015  10:44  (GMT+01:00) </div><div>Aan: yiisoft/yii2 <yii2@noreply.github.com> </div><div>Cc: onman <o.rijkers@chello.nl> </div><div>Onderwerp: Re: [yii2] Controller::getView always get Yii::$app->view (#7999) </div><div>
</div>@lynicidn in that case you can check if Yii::$app is an instance of web application

**Comment by onman** [comment]
@lynicid: the console and web applications usually have their own config files. Therefore Application components and module services won't be mixed or exchanged between the two. 


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: lynicidn <notifications@github.com> </div><div>Datum:08-04-2015  11:04  (GMT+01:00) </div><div>Aan: yiisoft/yii2 <yii2@noreply.github.com> </div><div>Cc: onman <o.rijkers@chello.nl> </div><div>Onderwerp: Re: [yii2] Controller::getView always get Yii::$app->view (#7999) </div><div>
</div>@cebe i think need yii\base as common and yii\web for web - yii\web\Module

**Comment by lynicidn** [comment]
@onma i know it, am answer on 

>check if Yii::$app is an instance of web application
