### ISSUE TITLE
Choose layout in view

### ISSUE THREAD

**Issue by wangchj** [yiisoft/yii2#8000]
This is more of a feature request rather than an issue.

I think the layout used by a view should be a property of the view class, instead of a property of the controller. At least, a view should be able to choose it's layout file.

For example, I have actions `site/index`, `site/contact`, `site/login` (in my controller `site`). For my view `index`, I may want to have a more fancy layout, but for views `contact` and `login` I may want to have a simpler layout.

Do you think letting a view to have the ability to choose layout is a good idea?

**Comment by unclead** [comment]
Why dont u set layout inside an anction? In my code i set custom layout for login page like that
```php
    public function actionLogin($back_url = '/')
    {
        if (!Yii::$app->user->isGuest) {
            $this->redirect($back_url);
        }

        $this->layout = '@common/views/layouts/blank';
        ...
        return $this->render('login', ['model' => $model]);
    }
```

**Comment by wangchj** [comment]
Hm that's a good idea
