### ISSUE TITLE
manifest.appcache served by Yii2 not recognized as such by browsers

### ISSUE THREAD

**Issue by IvoRe** [yiisoft/yii2#8004]
I want to serve a dynamic HTML5 manifest.appcache.

I can do this succesfully with a simple php script in my webroot (see http://www.openbook.pub/manifest.appcache.php). So we know my server is not the problem.

When I route this through Yii2, I can generate the exact same response (see http://www.openbook.pub/manifest.appcache). When I look both responses in Fiddler, I can not see any difference.

But for some reason, the browser will not accept Yii2's response as an appcache. To verify, point Chrome to openbook.pub and check `chrome://appcache-internals/`.

I have tried many configurations in Yii2. Here is the latest manner in which I serve the `manifest.appcache`:

~~~
$manifest = $this->assembleManifest();
header('Last-Modified: '.gmdate('D, d M Y H:i:s \G\M\T', time()-3600));
header("ETag: \"2e2-51312d1828aa4\"");
header('Accept-Ranges: bytes');
header("Content-length: ". strlen($manifest));
header('Cache-Control: no-cache, private');
header('Expires: '.gmdate('D, d M Y H:i:s \G\M\T', time()));
header('Content-Type: text/cache-manifest');

Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
return $manifest;

~~~
(Also: http://stackoverflow.com/questions/29485868/dynamically-generated-html5-appcache-does-not-want-to-play)

**Comment by samdark** [comment]
I don't think Yii has to do anything with it.

Try dumping 2 responses and comaring these using a diff tool. There should be something different.

**Comment by IvoRe** [comment]
How could I dump the responses? Fiddler won't let me do that...

**Comment by samdark** [comment]
For example, by using curl:

```
curl -i http://example.com/test
```
