### ISSUE TITLE
Features Assets Dependent of Bower.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#8007]
Hi, good practice would be placed in sourcepath = '@vendor/bower' all assets that depend bower, for a single asset default folder is created, and prevent loads several times the same code in different folders assets.

I know that I can configure in the Asset Manager but it would be great if it came by default,

Thanks in advance,

**Comment by samdark** [comment]
I don't think so. One may want to publish just a single dir or file out of bower package.
