### ISSUE TITLE
Submitting ActiveForm using a link with data-method defined ignores data-params

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#8015]
## Expected

When form is submitted using a link with `data-method` defined, params specified in `data-params` should be submitted as well.

## Actual

In case of plain form everything is OK but in case of ActiveForm, params aren't submitted.

Also there's issue #8014 is fixing.

## To reproduce

Start with basic app, define dummy model:

```php
<?php
namespace app\models;

use yii\base\Model;

class DummyModel extends Model
{
    public $name;
}
```

Create test controller:

```php
<?php
namespace app\controllers;

use app\models\DummyModel;
use yii\web\Controller;

class TestController extends Controller
{
    public function actionIndex()
    {
        $model = new DummyModel();
        return $this->render('index', [
            'model' => $model,
        ]);
    }
}
```

And a view:

```php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>

<?php
if (Yii::$app->request->isPost) {
    \yii\helpers\VarDumper::dump(Yii::$app->request->post());
}
?>

<h2>ActiveForm</h2>

<?php

$form = ActiveForm::begin([
    'enableClientValidation' => false, // it's not related to client validation
    //'enableClientScript' => false, // but related to yii.activeForm.js
])?>
    <?=$form->field($model, 'name')?>
    <?= Html::a('Submit', ['test/index'], [
        'data' => [
            'method' => 'post',
            'params' => [
                'action' => 'createNew'
            ]
        ]
    ])?>
<?php ActiveForm::end() ?>

<h2>Plain form</h2>

<?= Html::beginForm(); ?>
    <?= Html::input('text', 'name', 'test')?>

    <?= Html::a('Submit', '', [
        'data' => [
            'method' => 'post',
            'params' => [
                'action' => 'createNew'
            ]
        ]
    ])?>
<?= Html::endForm(); ?>
```

### Why it happens

In `yii.js` before submitting the form we're adding hidden inputs based on `data-params` and after submitting the form https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L206 we're deleting these in case submit was via AJAX and there was no HTML refresh.

In `yii.activeForm.js` we're handling submit in a special way: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L357. `data.validated` is false initially so we're asking for validation and then resubmitting the form. Before these two events `yii.js` is clearing hidden form fields resulting in missing `data-params` in POST.

**Comment by disem** [comment]
Is there an ETA for this task?

**Comment by nxnx** [comment]
2.0.5 - воспроизводится, 2.0.6 - нет, 2.0.7 - нет

**Comment by samdark** [comment]
@nxnx thanks for verifying that.
