### ISSUE TITLE
How can I validate "_csrf" in Ajax Request.?

### ISSUE THREAD

**Issue by p4scu41** [yiisoft/yii2#8016]
I am using jQuery Ajax to make a request, but in the action I want to check the _csrf, but It doesn't work.

This is my code:

JavaScript Function 
```js
$.ajax({
    url: urlAjax,
    type: 'POST',
    data: {"id": 1, "_csrf": yii.getCsrfToken()},
    dataType: 'json',
}).done(function (response) {
    console.log(response);
});
```

PHP Controller 
```php
public function actionTest($id)
{
    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

    $request = Yii::$app->request;
    $response = [
        'error' => false,
        'msg' => '',
    ];
    
    if (!$request->validateCsrfToken()) {
        $response = [
            'error' => true,
            'msg' => 'Error CSFR'
        ];

        return $response;
    }

    if ($request->isAjax) {
        try {
            $model = $this->findModel($id);
            ....
        } catch (Exception $exc) {
            $response['error'] = true;
            $response['msg'] = 'ERROR';
        }
    } else {
        $response['error'] = true;
        $response['msg'] = 'OK';
    }

    return $response;
}
```
I have set enableCsrfValidation = true, but the function $request->validateCsrfToken() always return true.

**Comment by mdmunir** [comment]
> but the function $request->validateCsrfToken() always return true.

because your token is valid. What the matter?

**Comment by p4scu41** [comment]
The problem is when I don't send the value of _csrf, even the function return true, or when I send incorrect value of _csrf, It always return true.

**Comment by touqeershafi** [comment]
make sure you use <?php echo Yii::$app->request->csrfParam ?>: '<?php echo Yii::$app->request->csrfToken; ?>' in your ajax data get the exact csrfParam with it's value don't put static string _csrf.

Secondly yii-controller verifies the _csrf by default if you have set $enableCsrfValidation = true; so you don't need to verify _csrf again.

**Comment by mdmunir** [comment]
csrf token also send via request header. Check it to.

**Comment by samdark** [comment]
Closed since it's not issue report but a question. Should be asked via forums.

**Comment by PouriaDiesel** [comment]
I had this problem.I write below function by Yii2 internal `Yii::$app->request->validateCsrfToken` code:
```
function validate_csrf($secret){
        $security = Yii::$app->security;
        $trueToken = Yii::$app->request->csrfToken;
        return $security->compareString($security->unmaskToken($secret), $security->unmaskToken($trueToken));
} 
```
