### ISSUE TITLE
Can not work connection hasMany(self::className(), ['id'=>'leader_id'])

### ISSUE THREAD

**Issue by maxyc** [yiisoft/yii2#8019]
question from https://toster.ru/q/208102

There is a table of users. Each user can be a leader
id, leader_id and blah blah blah

I want to display all users who have a leader I
```php
public function getTeam () {
      return $ this-> hasMany (self :: className (),  ['id'=>'leader_id']);
}
```
Connection is empty. The following data in the database
![picture](https://habrastorage.org/files/a99/b32/3c2/a99b323c26b54c068785ed2b7fb1a3d3.png)

i use 
```php
<?php

				$model = \app\models\User::find()->where(['id' => 1])->one();

			?>
			<?print_r($model->team); // is empty?>
```

**Comment by maxyc** [comment]
if i write
```php
public function getTeam () {
      return $ this-> hasOne (self :: className (),  ['leader_id'=>'id']);
}
<...>
<?php
$model = \app\models\User::find()->where(['id' => 1])->one();

print_r($model->team); // all good. first user from command
?>
```

**Comment by maxyc** [comment]
```php
	public function getTeam(){
		return self::find()->where(['leader_id'=>1])->count();
		//$this->hasMany(User::className(), ['id'=>'leader_id']);
	}
```
return 5;

**Comment by klimov-paul** [comment]
@maxyc, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
