### ISSUE TITLE
how get currency symbol by locale?

### ISSUE THREAD

**Issue by wilsonfalai** [yiisoft/yii2#8022]
how get currency symbol by locale?
Ex: '$' or 'R$'

and thousands separator and decimal separator by locale?

**Comment by mdmunir** [comment]
you can get it via [yii official forum](http://www.yiiframework.com/forum/) or [yii FB page](https://www.facebook.com/groups/yiitalk/)

**Comment by klimov-paul** [comment]
@wilsonfalai, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for issue reports.

**Comment by wilsonfalai** [comment]
ok
