### ISSUE TITLE
sendEmail Array to string conversion error

### ISSUE THREAD

**Issue by pappleton** [yiisoft/yii2#8024]
Hi 

I am just trying out Bryglen / yii2-sendgrid 

And it throws an error 'Array to string conversion' at:
 curl_setopt($ch, CURLOPT_POSTFIELDS, $form);

this is because $form=>from is an array

I have made a change in the Yii2 advanced application at:
PasswordResetRequestForm-> sendEmail()
 
 //                ->setFrom([\Yii::$app->params['supportEmail'] => \Yii::$app->name . ' robot'])
                   ->setFrom(\Yii::$app->params['supportEmail']) // not array - fixed

I know this does not allow the alternate name format but I cant find a better option I have reported it to the author Bryglen 
but I'm not sure where the fix is best made.

Great work on the Yii2 I have just started using it.

**Comment by klimov-paul** [comment]
This is not Yii issue.

**Comment by pappleton** [comment]
OK Fair point, thanks for the quick reply.
