### ISSUE TITLE
Wrong setting of quotes around variables using query builder 

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#8025]
I'm struggling on how to set or avoid quotes around variables while building a sub-query.

This statement 
```php
$model1 = Zaehlerstand::findBySql(
            'select * from ' . self::tableName() 
            . ' where zaehlerID = ' . $this->zaehlerID 
            . ' and ablesedatum = (select max(ablesedatum) from ' . self::tableName()
            . " where zaehlerID = $this->zaehlerID" 
            . " and ablesedatum < '$this->ablesedatum')")
            ->one();
 ```
generates the following correct sql statement.
```
select * from zaehlerstand where zaehlerID = 101 and
 ablesedatum = (select max(ablesedatum) from zaehlerstand
 where zaehlerID = 101 and ablesedatum < '2015-04-08')
``` 
Please note that there are **no** quotes around **$this->zaehlerID** and **single** quotes around
**$this->ablesedatum**.

To use the query builder I tried the next two examples. Both of them failed due to wrong setting of quotes.

```php
 $model2 = Zaehlerstand::find()
            ->where ([
                'zaehlerID' => $this->zaehlerID,
                'ablesedatum' => "(select max(ablesedatum) from ". self::tableName()
            . " where zaehlerID = $this->zaehlerID "
            . " and ablesedatum < '$this->ablesedatum')"]) // quotes will be escaped 
            ->one();
```
returns this sql statement:
```
SELECT * FROM `zaehlerstand` WHERE (`zaehlerID`='101') AND 
(`ablesedatum`='(select max(ablesedatum) from zaehlerstand 
where zaehlerID = 101  and ablesedatum < \'2015-04-08\')')
```
 ```php
$model3 = Zaehlerstand::find()
            ->where ([
                'zaehlerID' => $this->zaehlerID,
                'ablesedatum' => "(select max(ablesedatum) from ". self::tableName()
            . " where zaehlerID = $this->zaehlerID "
            . " and ablesedatum < $this->ablesedatum)"]) // no quotes 
            ->one();
```
returns this sql statement:
```
SELECT * FROM `zaehlerstand` WHERE (`zaehlerID`='101') AND 
(`ablesedatum`='(select max(ablesedatum) from zaehlerstand
 where zaehlerID = 101  and ablesedatum < 2015-04-08)')
```

**Comment by klimov-paul** [comment]
You should use PDO param binding.

**Comment by twinni** [comment]
@klimov-paul, thanks for your quick response.
To use param binding it's required to use the **string format**  instead of the **hash format**. So you've an additional 'andWhere()' function.

On the other hand I don't see why you're escaping quotes within a string passed as a value to the hash format. 
If there is a reason please add a comment to the documentation which currently says:   
Hash format is best used to specify multiple AND-concatenated sub-conditions each being a simple equality assertion. It is written as an array whose keys are column names and values the corresponding values that the columns should be.

**Comment by klimov-paul** [comment]
You have quoted docs yourself:

> whose keys are column names and values the corresponding values that the columns should be.

The value in the array will be the value of column. That is what you received in the end - direct matching of the column to the value you provided:

> `ablesedatum`='(select max(ablesedatum) from zaehlerstand
 where zaehlerID = 101  and ablesedatum < 2015-04-08)'

You should use `yii\db\Expression` if you wish use SQL statement as a column value.
