### ISSUE TITLE
PHP Core Warning

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2#8026]
PHP Core Warning – yii\base\ErrorException

PHP Startup:
2. yii\base\ErrorHandler::handleFatalError()
$_GET = [
    'productId' => '6',
];

$_SERVER = [
    'PROCESSOR_ARCHITEW6432' => 'AMD64',
    '_FCGI_X_PIPE_' => '\\\\.\\pipe\\IISFCGI-b2b9817d-5511-42cd-8d00-36d21ece6e52',
    'PHP_FCGI_MAX_REQUESTS' => '100',
    'ALLUSERSPROFILE' => 'C:\\ProgramData',
    'APPDATA' => 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming',
    'APP_POOL_CONFIG' => 'C:\\inetpub\\temp\\apppools\\admin.example.com\\admin.example.com.config',
    'APP_POOL_ID' => 'admin.example.com',
    'CommonProgramFiles' => 'C:\\Program Files (x86)\\Common Files',
    'CommonProgramFiles(x86)' => 'C:\\Program Files (x86)\\Common Files',
    'CommonProgramW6432' => 'C:\\Program Files\\Common Files',
    'COMPUTERNAME' => 'CLOUD2012R2',
    'ComSpec' => 'C:\\Windows\\system32\\cmd.exe',
    'FP_NO_HOST_CHECK' => 'NO',
    'LOCALAPPDATA' => 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local',
    'NUMBER_OF_PROCESSORS' => '2',
    'OS' => 'Windows_NT',
    'Path' => 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;',
    'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
    'PROCESSOR_ARCHITECTURE' => 'x86',
    'PROCESSOR_IDENTIFIER' => 'Intel64 Family 6 Model 44 Stepping 2, GenuineIntel',
    'PROCESSOR_LEVEL' => '6',
    'PROCESSOR_REVISION' => '2c02',
    'ProgramData' => 'C:\\ProgramData',
    'ProgramFiles' => 'C:\\Program Files (x86)',
    'ProgramFiles(x86)' => 'C:\\Program Files (x86)',
    'ProgramW6432' => 'C:\\Program Files',
    'PSModulePath' => 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
    'PUBLIC' => 'C:\\Users\\Public',
    'SystemDrive' => 'C:',
    'SystemRoot' => 'C:\\Windows',
    'TEMP' => 'C:\\Windows\\TEMP',
    'TMP' => 'C:\\Windows\\TEMP',
    'USERDOMAIN' => 'WORKGROUP',
    'USERNAME' => 'CLOUD2012R2$',
    'USERPROFILE' => 'C:\\Windows\\system32\\config\\systemprofile',
    'windir' => 'C:\\Windows',
    'ORIG_PATH_INFO' => '/backend/web/index.php/product/products/update',
    'URL' => '/backend/web/index.php',
    'SERVER_SOFTWARE' => 'Microsoft-IIS/8.5',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'SERVER_PORT_SECURE' => '0',
    'SERVER_PORT' => '80',
    'SERVER_NAME' => 'admin.example.com',
    'SCRIPT_NAME' => '/backend/web/index.php',
    'SCRIPT_FILENAME' => 'C:\\www\\shopping\\backend\\web\\index.php',
    'REQUEST_URI' => '/backend/web/index.php/product/products/update?productId=6',
    'REQUEST_METHOD' => 'GET',
    'REMOTE_USER' => '',
    'REMOTE_PORT' => '33449',
    'REMOTE_HOST' => '183.16.11.63',
    'REMOTE_ADDR' => '183.16.11.63',
    'QUERY_STRING' => 'productId=6',
    'PATH_TRANSLATED' => 'C:\\www\\shopping\\backend\\web\\index.php\\product\\products\\update',
    'PATH_INFO' => '/product/products/update',
    'LOGON_USER' => '',
    'LOCAL_ADDR' => '113.156.88.151',
    'INSTANCE_META_PATH' => '/LM/W3SVC/2',
    'INSTANCE_NAME' => 'ADMIN.example.COM',
    'INSTANCE_ID' => '2',
    'HTTPS_SERVER_SUBJECT' => '',
    'HTTPS_SERVER_ISSUER' => '',
    'HTTPS_SECRETKEYSIZE' => '',
    'HTTPS_KEYSIZE' => '',
    'HTTPS' => 'off',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'DOCUMENT_ROOT' => 'C:\\www\\shopping',
    'CONTENT_TYPE' => '',
    'CONTENT_LENGTH' => '0',
    'CERT_SUBJECT' => '',
    'CERT_SERIALNUMBER' => '',
    'CERT_ISSUER' => '',
    'CERT_FLAGS' => '',
    'CERT_COOKIE' => '',
    'AUTH_USER' => '',
    'AUTH_PASSWORD' => '',
    'AUTH_TYPE' => '',
    'APPL_PHYSICAL_PATH' => 'C:\\www\\shopping\\',
    'APPL_MD_PATH' => '/LM/W3SVC/2/ROOT',
    'WEBSOCKET_VERSION' => '13',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36',
    'HTTP_REFERER' => 'http://admin.example.com/backend/web/index.php/product/products/view?productId=6',
    'HTTP_HOST' => 'admin.example.com',
    'HTTP_COOKIE' => '_csrf=2b3434234324ab0063e2b77e34431c51d31822de78c1ea91cd68f91cc0301s%3A32%3A%221TjkPqHPnKMijg3w9gxObOhP96TZl9X9%22%3B; PHPSESSID=rdmkac6o8drisn6n2o3149rp36; _identity=59a3b73809125c63e16544b22f634343331b2da472b87b3438b36784s%3A46%3A%22%5B1%2C%229LgXir2wv24Jq_6HtrQhfUM8LiwfKs9N%22%2C2592000%5D%22%3B',
    'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'HTTP_CONNECTION' => 'keep-alive',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/backend/web/index.php/product/products/update',
    'REQUEST_TIME_FLOAT' => 1428595390.705915,
    'REQUEST_TIME' => 1428595390,
];

$_COOKIE = [
    '_csrf' => '2bf14cc74ab0063e2b77e4ed31434343ea91cd68f91cc0301s:32:"1TjkPqHPnKMijg3w9gxObOhP96TZl9X9";',
    'PHPSESSID' => 'rdmkac6o8dri344d23d23d33149rp36',
    '_identity' => '59a3b73809125c63e34343d3fa6f331b2da34344s:46:"[1,"9LgXir2wv24Jq_6HtrQhfUM8LiwfKs9N",2592000]";',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
    'tenant.id' => '1',
    'tenant.name' => 'example',
    'tenant.language' => 'zh-CN',
    'tenant.timezone' => 'PRC',
    'tenant.dateFormat' => '',
    'tenant.timeFormat' => '',
    'tenant.datetimeFormat' => '',
    'tenant.domainName' => 'example.com',
    'tenant.role' => '1',
    'tenant.userRule' => '0',
];
Yii Framework
2015-04-10, 00:03:11

Microsoft-IIS/8.5
Yii Framework/2.0.2
=======================================================
is not alway this error, when i refresh will be disappear.
This error in my developer machine and vps server both had.

**Comment by samdark** [comment]
Can't get anything useful from it.

**Comment by hiscaler** [comment]
Need config file or ?

**Comment by samdark** [comment]
Need a way to reproduce it.
