### ISSUE TITLE
Regarding yii2/framework/assets/yii.validation.js giving error

### ISSUE THREAD

**Issue by rajanishtimes** [yiisoft/yii2#8029]
Hi

when submitting the form 
yii2/framework/assets/yii.validation.js giving error

TypeError: $form is undefined
http://cmh.timescity.com/assets/2f95536a/yii.validation.js
Line 237

this piece of code  in yii2/framework/assets/yii.validation.js 

 trim: function ($form, attribute, options) {
            var $input = $form.find(attribute.input);
            var value = $input.val();
            if (!options.skipOnEmpty || !pub.isEmpty(value)) {
                $input.val($.trim(value));
            }
        },

Please check and suggest

**Comment by samdark** [comment]
1. What's Yii version?
2. Can you reproduce it using basic app and as less changes as possible?

**Comment by rajanishtimes** [comment]
Version is 2.0.4-dev

**Comment by rajanishtimes** [comment]
Unable to reproduce 

i have not taken form name , may it will creating this problem

**Comment by samdark** [comment]
OK. Closing it till reproduced.

**Comment by rajanishtimes** [comment]
I am able to reproduce using basic app

**Comment by samdark** [comment]
How?

**Comment by rajanishtimes** [comment]
My form code start with

<?php $form = ActiveForm::begin(); ?>

html generted is

<form id="w3" action="/venue/venue/update?id=48881" method="post">

This does not contains form name

**Comment by samdark** [comment]
?

**Comment by rajanishtimes** [comment]
below is my form code


<?php
use common\component\AppActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\adminUi\widget\Row;
use yii\adminUi\widget\Column;
use yii\adminUi\widget\Collapse;
use yii\adminUi\widget\Box;
use kartik\widgets\DepDrop;
use kartik\widgets\TimePicker;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\adminUi\assetsBundle\AdminUiTimePickerAsset;
use yii\adminUi\assetsBundle\AdminUiwysihtmlEditorAsset;
use common\modules\media\widgets\MediaUpload;
use yii\adminUi\widget\DynamicField;
use yii\adminUi\widget\Daterange;
use yii\adminUi\widget\InputAddon;
use yii\adminUi\widget\WorkflowButtons;
use common\models\Source;

AdminUiTimePickerAsset::register($this);

/* @var $this yii\web\View */
/* @var $model common\models\Venue */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="venue-form">

    <?php $form = ActiveForm::begin(); ?>
    <?php
    Row::begin();
    Column::begin([
        'grid' => [
            [
                'type' => Column::TYPE_DESKTOP,
                'size' => Column::SIZE_FULL,
            ]
        ],
        'options' =>[
            'class' => 'col-md-12'
        ]
    ]);
    ?>
    <p><h4 class="box-title">Basic Details</h4></p>  
        <?php 
  echo $form->field($model, 'venuetype_id')->dropDownList(ArrayHelper::merge(['' => 'Select'], ArrayHelper::map(\common\models\VenueType::find()->andWhere(['status' => 1])->All(), 'id', 'name')));
  echo $form->field($model, 'name')->textInput(['maxlength' => 255]);
  ?>
<p><h4 class="box-title">Contact Details</h4></p>
    <?php
        echo $form->field($model, 'contactName')->textInput(['maxlength' => 255,'value'=>$model->getContact()]);
        echo $form->field($model, 'email')->textInput(['maxlength' => 255,'value'=>$model->getEmailvenue()]);
                        
                        #############################################################
                       $phdata=$model->getPhonedata();
                       
                                 echo (is_array($phdata) && count($phdata)) ?
                        $form->field($model, 'phone',['options'=>['id'=>'multiphone','class'=>'multiphone','value'=>$phdata[0]]])->widget(DynamicField::className(), [
                            'name' => $model->formName().'[phone][]',
                            'clientId' => 'multiphone',
                            'form' => $form,
                            'options' => [
                                'model' => $model,
                                'models' => $phdata,
                            ],
                        ])
                        :
                        $form->field($model, 'phone',['options'=>['id'=>'multiphone','class'=>'multiphone']])->widget(DynamicField::className(), [
                            'name' => $model->formName().'[phone][]',
                            'clientId' => 'multiphone',
                            'form' => $form,
                        ]);
                        
                                 $modata=$model->getMobiledata();
                              echo  (is_array($modata) && count($modata)) ?
                        $form->field($model, 'mobile',['options'=>['id'=>'multimobile', 'class'=>'multimobile','value'=>$modata[0]]])->widget(DynamicField::className(), [
                            'name' => $model->formName().'[mobile][]',
                            'clientId' => 'multimobile',
                            'form' => $form,
                            'options' => [
                                'model' => $model,
                                //'form' => $form,
                                'models' => $modata,
                            ],
                        ])
                        :
                        $form->field($model, 'mobile',['options'=>['id'=>'multimobile', 'class'=>'multimobile']])->widget(DynamicField::className(), [
                            'name' => $model->formName().'[mobile][]',
                            'clientId' => 'multimobile',
                            'form' => $form,
                        ]);
                       
                   
    ##########################################################################
    
    
    
    ?>
<p><h4 class="box-title">Location Details</h4></p>
    <?php
    
   echo $form->field($model, 'city_id')->dropDownList(ArrayHelper::merge(['' => 'Select'], ArrayHelper::map(\common\models\City::find()->andWhere(['status' => 1])->All(), 'id', 'name')));
                        
echo $form->field($model, 'zone_id')->widget(DepDrop::classname(), [
    'options'=>['id'=> strtolower($model->formName()).'-zone_id'],
    'data'  => ArrayHelper::merge(['' => 'Select'], ArrayHelper::map(\common\models\Zone::find()->andWhere(['status' => 1,'city_id'=>$model->city_id])->All(), 'id', 'name')),
    'type' => DepDrop::TYPE_SELECT2,
    'pluginOptions'=>[
        'depends'=>[strtolower($model->formName()).'-city_id'],
        'placeholder'=>'Select Zone',
        'url'=>Url::to(['/zone/zone/autosuggest'])
    ]
]);
                        echo $form->field($model, 'locality_id')->widget(DepDrop::classname(), [
                                                                            'options'=>['id'=>'venue-locality_id'],
                                                                            'data'  => ArrayHelper::merge(['' => 'Select'], ArrayHelper::map(\common\models\Locality::find()->andWhere(['status' => 1,'city_id'=>$model->city_id])->All(), 'id', 'name')), 
                                                                            'type' => DepDrop::TYPE_SELECT2,
                                                                            'pluginOptions'=>[
                                                                            'depends'=>[strtolower($model->formName()).'-city_id',strtolower($model->formName()).'-zone_id'],
                                                                            'placeholder'=>'Select Locality',
                                                                            'url'=>Url::to(['/locality/locality/autosuggest'])
                                                                            ]
                                                                          ]);
                       echo $form->field($model, 'address')->textInput(['maxlength' => 255]);
                        
                        echo $form->field($model, 'landmark')->textInput(['maxlength' => 255]);
                       echo  $form->field($model, 'latitude')->textInput();
                       echo $form->field($model, 'longitude')->textInput();
    
    
    ?>
        <p><h4 class="box-title">More Details</h4></p>
    <?php
                               echo $form->field($model, 'description')->textarea(['rows' => 6]);
    ?>

<div class='bootstrap-timepicker'>
                    <?php echo $form->field($model, 'checkin')->widget(InputAddon::className(),[
                        'options' => ['class' => 'timepicker'],
                        'icon'=> 'fa-clock-o'
                    ]);?>    
    </div>
    
    <div class='bootstrap-timepicker'>
                    <?php echo $form->field($model, 'checkout')->widget(InputAddon::className(),['options' => ['class' => 'timepicker'],'icon'=> 'fa-clock-o']);?>    
    </div>

<?php if($model->scenario == 'create' || $model->checkin == ''){ $this->registerJs('$("#venue-checkin, #venue-checkout").val("")'); }?>
    <?php
                            //echo $form->field($model, 'facility')->listBox(ArrayHelper::merge([0 => 'Select'], ArrayHelper::map(\common\models\Features::find()->andWhere(['status' => 1,'flag'=>1])->All(), 'id', 'name')),['id'=>'facility','multiple'=>'multiple']);
                           echo $form->field($model, 'website')->textInput(['maxlength' => 100,'placeholder' => 'Type a valid url ex: http://timescity.com']);
                           echo $form->field($model, 'facebook_url')->textInput(['maxlength' => 100,'placeholder' => 'Type a valid url ex: http://facebook.com']);
                          
                           echo $model->multipleFormField('tag',$model->getTagData());
    ?>
     
    
      <p><h4 class="box-title">Images</h4></p>
     
         <?php
     echo MediaUpload::widget([
                                'data'  => $model->media['images'],
                                'previewurl' => yii::$app->params['imagepreviewurl'],
                                'path'  => 'venue',
                                'options' => [
                                    'addRemoveLinks' => true,
                                    'inputparam' => $model->formName().'[media][]',
                                ],                                
                            ]);
     ?>
    <p>&nbsp;</p>
    <?php
        if(!$model->isNewRecord && $model->source_id == Source::FB_SOURCE_ID && !$model->verified_flag){
    ?>
    <div class="callout callout-info">
        <h4>Venue Verification</h4>
        <p>
            This Venue is not verified by WhatsHot yet, thus you must need to verify this Venue prior to publish it.<br/>
            <div class="checkbox">
                <?= $form->field($model, 'verified_flag')->checkbox(array('label'=>'I have verified this venue')); ?>
            </div>
        </p>
    </div> 
    <?php 
        }
    ?>
    <p>&nbsp;</p>
     
    <?php
    
    echo WorkflowButtons::widget([
        'view' => $this,
        'model' => $model,
    ]);
    
    Column::end();
    Row::end();
  ?>
    <?php ActiveForm::end(); ?>

</div>

**Comment by samdark** [comment]
I don't have any of your custom models so can not reproduce the issue.

Can you reproduce it using basic app and as less changes as possible instead of posting code from your app?

**Comment by samdark** [comment]
No info received for a long time. Closing.
