### ISSUE TITLE
Pleacheholder problem in Text Field in Yii2

### ISSUE THREAD

**Issue by ankurgarg36** [yiisoft/yii2#8031]
Hii

I am facing a new problem in my project. When i write something in text filed it shows 
"You forgot to add placeholder attribute!"

This is the first screen no problem
![1](https://cloud.githubusercontent.com/assets/8677133/7085516/f9a430e0-df94-11e4-81c1-b28700479768.png)

when i try to write something it shows
![2](https://cloud.githubusercontent.com/assets/8677133/7085521/0bd65b12-df95-11e4-83f8-2fa4ca5e2aa0.png)

I have also add the placeholder but the problem is not resolved. 
Please get me rid of it.

**Comment by samdark** [comment]
It seems it's project specific. Can't reproduce it.

**Comment by ankurgarg36** [comment]
Means there is no solution of this problem.

**Comment by samdark** [comment]
Means there's problem in your project but it's not related to Yii.
