### ISSUE TITLE
yii session is not active when log message to file

### ISSUE THREAD

**Issue by tlanyan** [yiisoft/yii2#8036]
Hi,
I find that yii session component is inactive when the work flow process to log messages. In file yii/web/log/Target.php, line 286:

     $sessionID = $session && $session->getIsActive() ? $session->getId() : '-';

The asset $session->getIsActive() always returns false and thus sessionID is '-' in the log files. Where in controllers, function getIsActive returns true. I guest that session component calls close() method before logger logs messages.

**Comment by SDKiller** [comment]
I can confirm it with `dbTarget`:

![qip shot - screen 626 11 04 15](https://cloud.githubusercontent.com/assets/2150916/7102544/b782e132-e08b-11e4-8d99-3b0ccdb6bb72.png)

**Comment by klimov-paul** [comment]
Unable to reproduce.
Creating and accessing following controller action:
```php
public function actionLog()
{
    Yii::$app->session->open();
    Yii::error('testlog');
    return 'logged';
}
```
produces valid log results:
```
2015-04-24 13:47:53 [91.232.178.13][-][juiqkaoo19h7ogis0lpafd2325][error][application] testlog
```

**Comment by klimov-paul** [comment]
No, issue confirmed.

**Comment by klimov-paul** [comment]
See #8174
