### ISSUE TITLE
How to pass variable to relation in yii2

### ISSUE THREAD

**Issue by nadeemse** [yiisoft/yii2#8037]
I want to pass to_date to relation so i can get the values on to_Date condition. can anyone know how we pass the "$to_date" to relational function. 

This is my code that currently producing error due to second variable.

 $history = Advance::find()
                ->with(['advanceHistory' => function  ($query, $to_date) {
                        $query->where(['<=', 'date', $to_date]);
                    }
                ])
                ->where(['status' => Advance::APPROVED, 'user_id' => $user_id])
                ->all();

**Comment by zelenin** [comment]
https://php.net/manual/en/functions.anonymous.php
You should read the docs instead ask the question. This is a issue tracker.
