### ISSUE TITLE
Yii2 check captcha value with php after submitting the form

### ISSUE THREAD

**Issue by ArtInCode** [yiisoft/yii2#8040]

**Comment by klimov-paul** [comment]
Use `yii\captcha\CaptchaValidator`

**Comment by ArtInCode** [comment]
How to call the value to compare with the post

**Comment by ArtInCode** [comment]
How to get this in a valiable so that I could compare with post

**Comment by klimov-paul** [comment]
@ArtInCode, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
