### ISSUE TITLE
Yii 2 Contact form after submitting got the error msg mkdir permision ....

### ISSUE THREAD

**Issue by ArtInCode** [yiisoft/yii2#8041]
I found that I must create folder resized , yet dont know where in wich folder to create so

**Comment by cebe** [comment]
I can not tell anything without more information, please provide the whole error message including a stack trace and describe in detail what you are trying to do.
Also a folder named "resized" is not part of yii itself so this sounds unrelated.

**Comment by klimov-paul** [comment]
Closed unless more information arrives.
