### ISSUE TITLE
How i can set module parameters, and then get them after ajax-request to controller of module?

### ISSUE THREAD

**Issue by sanex3339** [yiisoft/yii2#8043]
How i can set module parameters, and then get them after ajax-request to controller of module?

I want call module multiple times in different actions and controllers, and each time with different parameters, so, setting module parameters in yii config (or module config file) not help with my problem. 
If i set parameters through module method, after ajax request parameters will empty.

I found temporary solution: when i call module in controller, i put all parameters into session and later after ajax request get them from session, but i dont like this method.

**Comment by cebe** [comment]
if this is a feature request, please describe in more detail what you suggest and I'll reopen it. If it is a question, please use the forum instead. Github is for bug and feature tracking.
