### ISSUE TITLE
Ajax request to Yii2 not working

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2#8047]
Hello,

I've got a curious situation.
I want to send data to my Yii2 application from Javascript part of which is shown below;

```javascript
var cUrl = window.location.pathname.substring(1);
$.ajax({ url: cUrl,
data: {action: 'RESIZE',_currWidth: $(window).width()},
type: 'post',
contentType: "application/json; charset=utf-8",
dataType: "json",
success : function (result) {},
error : function () {alert("error");}
});
```

Note that that variable cUrl contains "listing/lab" which is a valid route in the application. 

I'm assuming that this route is the entry point for Ajax to Yii2 so on the server side I have the following code in the listing Controller;

```javascript
public function actionLab() {
        echo 'alert("Step 1")';

        if(isset($_POST['action']) && !empty($_POST['action'])) {

            echo 'alert("Step 2")';

            $action = $_POST['action'];
            unset($_POST["action"]);

            if ($action == 'RESIZE') {

                echo 'alert("Step 3")';

                $w = $_POST["_currWidth"];
                unset($_POST["_currWidth"]);

		...

	}
```

Somehow execution never gets to actionLab() - none of the PHP code above is executed. On investigation I see that the Javascript console has the following error:

```
POST> http://admin.incredible.local/listing/listing/lab 404 (Not found)
```

Of course there's no "listing/listing/lab", the URL provided to Ajax is "listing/lab" and works ordinarily

So my question is how on earth did "listing/lab" become "listing/listing/lab" after the Ajax request?
Any help to understand what is going on or fix this will be appreciated.

Thanks in Advance!

**Comment by mdmunir** [comment]
>So my question is how on earth did "listing/lab" become "listing/listing/lab" after the Ajax request?

Are you sure this is Yii fault, not your fault?
Check in your firebug what value of `cUrl`.
```javascript
var cUrl = window.location.pathname.substring(1);
console.log(cUrl);
$.ajax({ url: cUrl,
...
```

Last, USE [YII FORUM](http://www.yiiframework.com/forum/) FOR ASKING!

**Comment by samdark** [comment]
You're sending request to `http://admin.incredible.local/listing/listing/lab` which gives you 404 means it's not there. It's expected.

Note that internal Yii route !== URL. JavaScript or any other client has no idea about Yii routes so you have to form URLs properly.

**Comment by dbd5** [comment]
Thanks guys, this is sorted now. 

Sam's clue that Yii route !== URL pointed me in the right direction and I changed the URL for Ajax to:

url: '<?=yii\helpers\Url::toRoute("listing/ajax")?>',
