### ISSUE TITLE
how to pass variables to view dynamically?

### ISSUE THREAD

**Issue by tlanyan** [yiisoft/yii2#8049]
Hi, 
I want to pass some specific parameters(such as static base url) to all the views. After searching apis, I find that only the method yii\web\View::beforeRender can meet my requirement. I use $this->params[key] = value in the beforeRender to pass values to all view. But the passed variables can only be accessed in the form of $this->params[key].

I want the passed variables can be available in the direct form: $key. I notice that the parameters of beforeRender is $viewFile and $params.  The second parameter $params is the local variables available among view files. However $params is declared as passed by value, so I can't use $params[key]=value to add variables dynamically.

Is there another api which can meet my need? Many thanks!

**Comment by mdmunir** [comment]
you can not

**Comment by samdark** [comment]
Correct. There's no such feature. What's your use case?

**Comment by kmergen** [comment]
If you need a static variable in all your views you can extend ```yii\web\view```

**Comment by cebe** [comment]
> But the passed variables can only be accessed in the form of $this->params[key].
> 
> I want the passed variables can be available in the direct form: $key.

why do you need it this way? You can use http://php.net/manual/en/function.extract.php to turn params into variables.

**Comment by tlanyan** [comment]
For example, the base url of static files should passed to all the view. The view files are written in Smarty. I just want all the passed parameters are the same for the front end. I know there is an api called View::setVar in the Phalcon framework. You can always use it to pass variables, and the passed variables are the same with call render

**Comment by cebe** [comment]
I still do not see why `$this->params` does not work, you can even configure it in the application config...

**Comment by tlanyan** [comment]
The problem is not $this->params does not work(actually it works well in my project). The problem is that front end must use {$this->params.key} to get the value in the smarty syntax and it's weird for the front end. 

What I want is that is there an approach to pass variables to the view just like passed in the View::render method?

**Comment by kmergen** [comment]
How I can understand you have a few variables that you need in all your views. And therefore I would extend the the yiew class with all your needed variables and than you can set them in your controller or view and use them in your view with ```$this->variable```

**Comment by tlanyan** [comment]
I wish these variables can be added or removed dynamically in the configure file, rather than they are property of some class...

While it's ok that view class does not support this feature...

**Comment by samdark** [comment]
I don't think we're going to support it. That's not really common request and I doubt it will be used often.

**Comment by eacevedof** [comment]
To solve this i have extended base/Controller:  

**namespace common\masters;
use Yii;
use yii\web\Controller;
class CommonController extends Controller**
{
    private $arViewVars = [];
    public function init()
    {
        //echo "CommonController .init() 1.0.0 Running...";        
        parent::init();
    }//init

    protected function addToView($sVarName,$mxVarVal)
    {
        $this->arViewVars[$sVarName] = $mxVarVal;
    }//addToView

    protected function render($view,$params = array()) 
    {
        $params = array_merge($this->arViewVars,$params);
        return parent::render($view,$params);
    }//render

}CommonController 

all my controllers extend my CommonController:

**//@file: \frontend\controllers\SiteController.php 1.0.0
use common\masters\CommonController;
class SiteController extends CommonController**
{
    public function init()
    {
        //echo "SiteController .init() 1.0.0 Running...";        
        parent::init();
    }//init

    public function index()
    {
        $sVar = "hello world";
        $this->addToView("myVar",$sVar);
        return $this->render("view_index");
    }//init

}//SiteController 

i hope it helps

**Comment by mdmunir** [comment]
How about this
```php
namespace app\classes;

class View extends \yii\web\View
{
    public $localVars = [];
    public function renderFile($viewFile, $params = [], $context = null)
    {
        if(!empty($this->localVars)){
            $params = array_merge($this->localVars, $params);
        }
        parent::renderFile($viewFile, $params, $context);
    }
}
```
Then in config
```php
'components' => [
    'view' => [
        'class' => 'app\classes\View',
        'localVars' => [
            'foo' => 'bar',
            'm_id' => 3426,
        ]
    ]
]
```
