### ISSUE TITLE
i think you can use password_compat replace crypt

### ISSUE THREAD

**Issue by bjdgyc** [yiisoft/yii2#8051]
I think you can use password_compat replace crypt in the `yii\base\Security`  class.
So, we donot care it. it always `Security` by password_hash.
You can consult https://github.com/ircmaxell/password_compat.
I do this by `www.iciba.com`,3ks!

**Comment by Sammaye** [comment]
I think this ext is backwards compat for non-namespace PHP installs isn't it? Since Yii2 is not cmpatible with those I am unsure how useful it would be to change Yii2 to use this ext.

**Comment by Sammaye** [comment]
Oh nvm PHP had namespaces since 5.3

**Comment by nineinchnick** [comment]
@Sammaye you're right, Yii 2 requires at least PHP 5.4

**Comment by nineinchnick** [comment]
Oh nvm password_hash is available since 5.5.0 :-)

**Comment by Sammaye** [comment]
Though that's a good point it does say in the readme:

> The reason for this is that PHP prior to 5.3.7 contains a security issue with its BCRYPT implementation. Therefore, it's highly recommended that you upgrade to a newer version of PHP prior to using this layer.

So if that security hole isn't there now it could be just adding bloat

**Comment by klimov-paul** [comment]
I have a feeling we have disscussed this already...

**Comment by klimov-paul** [comment]
Yes found it: #3946

**Comment by Sammaye** [comment]
https://github.com/yiisoft/yii2/pull/4052 or more specfically: https://github.com/yiisoft/yii2/pull/4052#issuecomment-47275426

**Comment by bjdgyc** [comment]
3ks
