### ISSUE TITLE
How can I fire the unit tests?

### ISSUE THREAD

**Issue by jepster** [yiisoft/yii2#8052]
Hello guys,

in

yii2/tests/unit/framework/console/controllers/AssetControllerTest.php

I have a unit test. How can I fire it via PHPUnit?

Background is, that I would like to implement an new component into Yii and integrate it properly test-driven.

Thank you guys

**Comment by cebe** [comment]
you can run phpunit inside of the repository base directory and give the file path as an argument:

```
vendor/bin/phpunit tests/unit/framework/console/controllers/AssetControllerTest.php
```

**Comment by jepster** [comment]
It seems that this isn't working properly. I'm getting

Configuration read from /Users/jepster/Sites/yii2/phpunit.xml.dist

EESS.................

Time: 548 ms, Memory: 6.50Mb

There were 2 errors:

1) yiiunit\framework\console\controllers\AssetControllerTest::testActionTemplate
yii\base\UnknownMethodException: Calling unknown method: yiiunit\framework\console\controllers\AssetControllerMock::getCommandDescriptions()

I've tried some other testfiles and they're all failing.

**Comment by cebe** [comment]
this is working for me...

```
$ vendor/bin/phpunit tests/unit/framework/console/controllers/AssetControllerTest.php
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /home/cebe/dev/yiisoft/yii2/phpunit.xml.dist

......................

Time: 169 ms, Memory: 6.00Mb

OK (22 tests, 41 assertions)
```

are you running the tests on a clean installation of yii2 and have you run composer update before?

**Comment by jepster** [comment]
Which Yii version and repo do you have?

**Comment by cebe** [comment]
yii 2.0 master

**Comment by cebe** [comment]
starting from scratch assuming composer is installed:

```
git clone https://github.com/yiisoft/yii2
cd yii2
composer update
vendor/bin/phpunit tests/unit/framework/console/controllers/AssetControllerTest.php
```

**Comment by jepster** [comment]
Works like a charme. Thank you!

**Comment by jepster** [comment]
I would like to run a single test? I wanted to run

phpunit /yii2/tests/unit/framework/log/FileTargetTest.php

But then I get only

Fatal error: Class 'yiiunit\TestCase' not found in /Users/jepster/Sites/yii2/tests/unit/framework/log/FileTargetTest.php on line 18

Call Stack:
    0.0032     297144   1. {main}() /Applications/phpunit-3.7.10.phar:0
    0.0435     700392   2. PHPUnit_TextUI_Command::main() /Applications/phpunit-3.7.10.phar:523
    0.0435     701016   3. PHPUnit_TextUI_Command->run() phar:///Applications/phpunit-3.7.10.phar/PHPUnit/TextUI/Command.php:129
    0.0497     944504   4. PHPUnit_Runner_BaseTestRunner->getTest() phar:///Applications/phpunit-3.7.10.phar/PHPUnit/TextUI/Command.php:150
    0.0497     944576   5. PHPUnit_Runner_BaseTestRunner->loadSuiteClass() phar:///Applications/phpunit-3.7.10.phar/PHPUnit/Runner/BaseTestRunner.php:104
    0.0504     968128   6. PHPUnit_Runner_StandardTestSuiteLoader->load() phar:///Applications/phpunit-3.7.10.phar/PHPUnit/Runner/BaseTestRunner.php:168
    0.0519    1055640   7. PHPUnit_Util_Fileloader::checkAndLoad() phar:///Applications/phpunit-3.7.10.phar/PHPUnit/Runner/StandardTestSuiteLoader.php:77
    0.0520    1055832   8. PHPUnit_Util_Fileloader::load() phar:///Applications/phpunit-3.7.10.phar/PHPUnit/Util/Fileloader.php:76
    0.0532    1088560   9. include_once('/Users/jepster/Sites/yii2/tests/unit/framework/log/FileTargetTest.php') phar:///Applications/phpunit-3.7.10.phar/PHPUnit/Util/Fileloader.php:92

I can only run the phpunit.xml.dist.

**Comment by jepster** [comment]
Since this issue is closed and my topic went more specified, I've created an new issue at https://github.com/yiisoft/yii2/issues/8097
