### ISSUE TITLE
suggest i18n feacture

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#8056]
hi all

how i can implement in the URL the lenguage of the application for example

http://localhost/frontend/ES
or
http://localhost/frontend/EN
or 
http://localhost/frontend <---- default lenguage EN

this can be a enhacement ?

http://www.yiiframework.com/forum/index.php/topic/56027-yii2-multilingual-website-url-rules/
https://github.com/codemix/yii2-localeurls

exist the option for add this feacture in the CORE of Yii2 ?

**Comment by cebe** [comment]
this should do what you need: https://github.com/codemix/yii2-localeurls

**Comment by spiritdead** [comment]
@cebe  i know but the idea is can access this feactures in yii2 and not in a extension

**Comment by cebe** [comment]
whats the problem with the extension?

**Comment by spiritdead** [comment]
@cebe  the extension localeurls is not official for this reason, and if the framework can incorporate these improvements could improve i18n module, taking in mind that a framework the more extensive and has more features, but users could use

if you look on the internet there are many doubts about the i18n

**Comment by cebe** [comment]
> the extension localeurls is not official for this reason

thats not an argument for not using it, it is well documented and the code should be understandable, we can not have everything in the core, our time is limited. Especially if there is a good extension it should be used instead of duplicating effort.
