### ISSUE TITLE
AssetBundle in view file

### ISSUE THREAD

**Issue by wangchj** [yiisoft/yii2#8062]
I'd like to put a simple asset class, like the one below, in my one of my view file. The asset bundle has only one file `home.css`, which is stored in `app/views/site`.

```
class HomeAsset extends AssetBundle
{
    public $basePath = '@app/views/site';
    public $css = [
        'home.css',
    ];
    public $js = [];
    public $depends = [];
}

HomeAsset::register($this);
```

The problem is, the url for `home.css` is rendered as `/home.css`, which is unexpected since I've set `$basePath = '@app/views/site'`

**Comment by samdark** [comment]
You're confusing `basePath` and `baseUrl`.

**Comment by wangchj** [comment]
Changed to `baseUrl` and still give me incorrect url to `home.css`. My question is does asset bundle have to be in the `app/assets` directory?

**Comment by samdark** [comment]
No. It doesn't matter. Your CSS file has to end up in web-accessible directory. Either it's already there in `web/something` or you're publishing it into `web/assets` by specifying `sourcePath`.

**Comment by wangchj** [comment]
Yes that is what I expected. However, when I put my bundle (`HomeAssets.php`) in my `app\views\site` directory, and do `HomeAsset::register($this);` in my view, it appears that

1. The assets (my `home.css`) is not copied to `web/assets/xyz`.
2. In my rendered page, the url of my asset `home.css` is `/home.css`, which is completely wrong. It should be `web/assets/xyz/home.css`.

As mentioned before, my asset bundle class (`HomeAssets.php`) is in the same php file as my view, maybe that's why it's freaking out. I put the class in the same file for simplicity reasons, so that I don't have to open another file just to modify the assets, which are only used by one view.

For completeness, the following is current content of my file `app/views/site/home.php`.

```
<?php

use yii\helpers\Url;
use yii\web\AssetBundle;
//use app\views\site\HomeAsset;

class HomeAsset extends AssetBundle {
    public $basePath = '@app/views/site';
    public $css = ['home.css'];
    public $js = [];
    public $depends = [];
}

HomeAsset::register($this);
?>
<nav id="w1" class="navbar" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#w1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">CountUp</a>
        </div>
        <div id="w1-collapse" class="collapse navbar-collapse">
            <ul id="w2" class="navbar-nav navbar-right nav">
                <li><a href="<?=Url::to(['site/logout'])?>" data-method="post">
                    <img src="<?=\Yii::$app->user->identity->picture?>" width="40px" class="img-circle" style="opacity:100%">
                    <?=\Yii::$app->user->identity->forename?>
                </a></li>
            </ul>
        </div>
    </div>
</nav>
```

**Comment by cebe** [comment]
>     public $basePath = '@app/views/site';

this should be:

>     public $sourcePath = '@app/views/site';

**Comment by wangchj** [comment]
Yes that worked. Sorry for the false alarm.
