### ISSUE TITLE
ActiveForm does not work on this situation

### ISSUE THREAD

**Issue by shnwqshnwq** [yiisoft/yii2#8063]
```php
<?php
$form=ActiveForm::begin([
	'id' => 'paypass-form',
	'action'=>'',
	'enableClientValidation'=>true,
	'enableAjaxValidation'=>true,
	'validateOnSubmit'=>true,
]);
?>

    <?=$form->beginField($user, 'old_paypass');?>
    <tr>
      <td class="left">old pass：</td>
      <td class="center"><?=Html::activePasswordInput($user, 'old_paypass', ['class'=>'text160'])?></td>
      <td class="right"><?=Html::error($user, 'old_paypass')?><a href="<?=Url::toRoute('retrievePaypass')?>" class="lan">forgotten ? </a></td>
    </tr>
    <?=$form->endField()?>

<?php ActiveForm::end()?>
```

am i missing something? it's not working while ajax return the right data:
{"userpaypass-old_paypass":["old paypass cannot be blank."]}

**Comment by samdark** [comment]
What do you mean by not working?

**Comment by mdmunir** [comment]
I am not sure. try this
```php
<?=Html::error($user, 'old_paypass',['class' => 'help-block'])?>
```

**Comment by shnwqshnwq** [comment]
@samdark  i click submit, then no any reaction, ajax triggered, but it won't show any error message.

@mdmunir  yes, i tried, still not work

**Comment by shnwqshnwq** [comment]
i doubt if any html tags contained in the field block, it won't work

**Comment by cebe** [comment]
have not checked any code but afaik ActiveField has to be used to register client validation and ajax validation js on the fields, this does not work with fields added by the Html Helper.

**Comment by shnwqshnwq** [comment]
@qiangxue

**Comment by shnwqshnwq** [comment]
if i code like this
<?=$form->field($user, 'old_paypass')->passwordInput(['class'=>'text160'])?>
it works ok, but while code like beginField and endField, it's won't work, may be tags <tr> <td>
lead the error

**Comment by shnwqshnwq** [comment]
it looks like that a field set cannot include table tags

**Comment by mdmunir** [comment]
@shnwqshnwq It work ok for me.
my test code
```php
<?php

use yii\base\DynamicModel;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

$model = new DynamicModel(['nama', 'password']);
$model->addRule(['nama', 'password'], 'required')
    ->addRule(['password'], function()use($model) {
        if ($model->password != 'pass') {
            $model->addError('password', 'Invalid');
        }
    });

if ($model->load(Yii::$app->request->post())) {
    if (Yii::$app->request->isAjax) {
        Yii::$app->response->format = 'raw';
        Yii::$app->response->getHeaders()->add('content-type', 'application/json');
        $this->context->layout = false;
        echo json_encode(ActiveForm::validate($model));
        return;
    }
    if ($model->validate()) {
        echo "Sukses <br>";
    }
}
?>
<?php
$form = ActiveForm::begin([
        'id' => 'test7',
        'enableAjaxValidation' => true,
    ]);
?>
<?= $form->field($model, 'nama'); ?>

<?= $form->beginField($model, 'password'); ?>
<tr>
    <td class="left">Password：</td>
    <td class="center"><?= Html::activePasswordInput($model, 'password', ['class' => 'text160']) ?></td>
    <td class="right"><?= Html::error($model, 'password',['class'=>'help-block']) ?></td>
</tr>
<?= $form->endField() ?>

<?= Html::submitButton(); ?>
<?php
ActiveForm::end();
```
![screenshot from 2015-04-14 13 10 10](https://cloud.githubusercontent.com/assets/5828252/7131336/2e8d6f36-e2a8-11e4-9136-42144d5b571a.png)

**Comment by shnwqshnwq** [comment]
@mdmunir  Yes, i tried again, i found if i remove the &lt;table&rt; tag , it works find, if add table tag again , it won't work

**Comment by mdmunir** [comment]
try this
```php
<table>

<?= $form->beginField($model, 'password',['options'=>['tag'=>'tr']]); ?>
    <td class="left">Password：</td>
    <td class="center"><?= Html::activePasswordInput($model, 'password', ['class' => 'text160']) ?></td>
    <td class="right"><?= Html::error($model, 'password',['class'=>'help-block']) ?></td>
<?= $form->endField() ?>

</table>
```

**Comment by shnwqshnwq** [comment]
@mdmunir  still not working, i give up using ActiveForm, instead of using jquery validate plugin for a replacement

**Comment by shnwqshnwq** [comment]
I know the reason why, a &lt;div&gt;  tag should not be included in a &lt;table&gt;  tag, it should be in a &lt;td&gt; tag,  so , if i run $form->beginField , it will create a div tag automaticly.
but , can we just use beginField only create a series of attributes? not a tag, that can be used as below:
&lt;table&gt; 
&lt;tr <?=form->beginField($model, 'password')? >&gt;
&lt;/tr <?=form->endField()?>&gt;
&lt;/table&gt;

**Comment by mdmunir** [comment]
```php
<?php
$form = ActiveForm::beginWigdet([
    ...
    'fieldConfig' => ['options'=>['tag'=>'tr']],
]);
?>

<?= $form->beginField($model, 'password'); ?>
```

**Comment by samdark** [comment]
The issue is about using HTML. Doesn't really related to Yii.
