### ISSUE TITLE
Bug with menu container when tag set to false

### ISSUE THREAD

**Issue by kirsenn** [yiisoft/yii2#8064]
Hi.
I've got a custom menu extended from basic yii\widgets\Menu
In the widget we have $options array with tag option:

> * - tag: string, defaults to "ul", the tag name of the item container tags. Set to false to disable container tag.

Okay, then what we do in our new widget:

```
$this->options['tag'] = false;
```

But now we see "<>" string in page at the begining of menu widget, what's going on? Let's have a look in parent widget:

```
echo Html::tag($tag, $this->renderItems($items), $options);
```

No conditions about $tag is equal to false, so it renders  '<>' right before widget layout

**Comment by samdark** [comment]
Have you tried with code from master?

**Comment by kirsenn** [comment]
@samdark Yes, just tried, the issue still exists

**Comment by samdark** [comment]
Do you want to work on a fix and then send a pull request?

**Comment by kirsenn** [comment]
@samdark Yes, I'll get it
