### ISSUE TITLE
Problem with UTF-8 domains in \yii\helpers\BaseUrl::to()

### ISSUE THREAD

**Issue by Lexxtor** [yiisoft/yii2#8066]
I have the following code:
```php
Html::a($site, $site);
```
If `$site` have utf-8 domain, like `http://www.быстроном.рф`, then it produce wrong URL:
```html
<a href="">http://www.быстроном.рф</a>
```

I expect to get:
```html
<a href="http://www.быстроном.рф">http://www.быстроном.рф</a>
```
or
```html
<a href="http://www.xn--90awcdbjgi3f.xn--p1ai">http://www.быстроном.рф</a>
```

**Comment by cebe** [comment]
Unable to reproduce, added unit test, which passes: 17011e4
Can you reproduce it in a clean basic app?

**Comment by dbsparkle** [comment]
@Lexxtor Are you sure that `$site` is returning anything?

Tried it in an advanced template - no problem.

**Comment by Lexxtor** [comment]
Sorry. Bug was in an old version.
Now:
```php
<?=Yii::getVersion()?>
<?=Html::a('http://www.быстроном.рф', 'http://www.быстроном.рф')?>
```
make:
```html
2.0.3-dev
<a href="http://www.быстроном.рф">http://www.быстроном.рф</a>
```

**Comment by cebe** [comment]
can you tell which version that was?

**Comment by Lexxtor** [comment]
By the looking file dates, that version was not older than January 2015.

**Comment by cebe** [comment]
thanks, ran the test against 2.0.0, 2.0.1, 2.0.2 and 2.0.3 and it passes on all of them.
