### ISSUE TITLE
I18N: Proliferation of translation sources. How to cope ?

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#8067]
My application is from advanced template. So it has 3 potential categories: 'common', 'frontend' and 'backend'. Also I have 2 Yii2-related libraries: generic additions/overrides and storage-specific for Apache Cassandra.

I do not want that much categories, I want only two: controlled by me and by Yii2 team. I hate to have to remember from what of my-controlled sources does the particular translation come.

How to solve this ?

What is the best way to compose translations ? Command-line task after every change ? Refactor `*MessageSource` classes, or write my own `CompositeMessageSource` ? Make fake PHP source files including all the real ones with `array_merge()` ?

Or is where any good reason against doing so, and for keeping separate categories per application facet and per composer package ?

**Comment by samdark** [comment]
How do you intend to resolve conflicts between different sources? Translation of the same source string can vary depending on context (extension).

**Comment by mcd-php** [comment]
I will resolve conflicts by making longer key string and bulk replace. For example, if I was so foolish to make key `LC_MIN`, I will split it to `LC_MATH_MINIMUM_SHORT_3` and `LC_TIME_MINUTE_SHORT_3`. The same for omonyms, translator false friends, slippery terms etc.

Or do you foresee different strings for perfectly the same pieces of meaning ?

**Comment by samdark** [comment]
IT seems you're using IDs instead of strings as message keys and forcing English translation. Am I correct?

**Comment by mcd-php** [comment]
Yes, I use abstract descriptive strings. Not sure what you mean in 'forcing English translation', in my translation files English is not privileged and is translated from key strings as usual. I set `'sourceLanguage' => 'sys_NONHUMAN',` for `PhpMessageSource` in my app config.

**Comment by samdark** [comment]
Makes sense. Well, in this case you could have conflicts but in general it's easier to avoid em. Not sure if what you want is a common enough thing. We could probably support turning on such behavior via config.

**Comment by samdark** [comment]
A straightforward solution is to have several `include` and `array_merge` in the file where messages are read from. Message command should be configured not to overwrite the file but to fill the ones included instead.

**Comment by klimov-paul** [comment]
I am unsure if I understand this correctly. But as far as I see you problem can be solved using 'missingTranslation' event.
You need to declare your 'universal' message source with 'missingTranslation' event handled in the way it searches missing message at some another 'fallback' message source:

```php
use yii\i18n\MissingTranslationEvent;

class TranslationEventHandler
{
    public static function handleMissingTranslation(MissingTranslationEvent $event)
    {
        $fallbackMessageSource = Yii::$app->i18n->getMessageSource('fallback');
        $event->translatedMessage = $fallbackMessageSource->translate($event->category, $event->message, $event->language);
    }
}
```
