### ISSUE TITLE
I18N: Translations are not alphabetized until something changed.

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#8070]
Expected: after running command line tool, all translations are alphabetized by their key, untranslated sit atop.

Observed: I add new keys, translate them in category PHP file, they remain at top no matter how many times I run the tool. After adding dummy `Yii::t('mycategory','LC_OOPS');` the new untranslated message sits atop, and older ones finally are shaked down.

Please, change it the way so all translated are sorted no matter how long ago they were translated !

P.S. Strings are stored in PHP.

**Comment by klimov-paul** [comment]
The general policy of the `MessageCommand` is not touch the message source unless it is needed.
If there are no changes detected for the file it will not be rewritten.
I prefer to keep things that way.

**Comment by mcd-php** [comment]
@klimov-paul For what reason ? "Don't touch if it works" attitude is good for humans since they are error-prone. Computers do things same way all the time, so the "Data must be in once promised condition" attitude is much better. Seeing the promise broken makes user think the program didn't run, or is buggy, or something bad happened.

**Comment by mcd-php** [comment]
@klimov-paul More than just "ordnung muss sein" point, delayed sorting makes unnecessary changes in VCS history. Exported, translated, committed - OK. Exported one more, translated, committed - oops, not only new translation added, but old ones turned red at the top and inserted as green at their alphabetic places. This just puts extra noise in change review !

**Comment by klimov-paul** [comment]
Resolved by commit adb0460
