### ISSUE TITLE
Phone number formatter 

### ISSUE THREAD

**Issue by dbsparkle** [yiisoft/yii2#8075]
Currently the **Data Formatter** has `asEmail` or `asUrl` hyperlink specific formats... 
So it would be nice if it would also have a support for other hyperlink types as  `tel:` (and maybe even for `callto:` as well).

(Sorry, if I am duplicating  an issue - I tried to search if someone else submitted this proposal, but couldn't find anything relevant to it.)

**Comment by samdark** [comment]
What do you expect to pass for it as input?

**Comment by dbsparkle** [comment]
Phone number as a string, so it would render in a similar manner as `asUrl` does:

`<a href="tel:[PHONE-NUMBER]">[PHONE-NUMBER]</a>`

Errata: `callto` has been discarded by [rfc3966](http://tools.ietf.org/html/rfc3966), _because URI schemes locate a resource and do not specify an action to be taken_ .

Also, there is an internationally accepted [E.164 ](http://en.wikipedia.org/wiki/E.164) recommendation by [ITU-T](http://www.itu.int/en/ITU-T/publications/Pages/recs.aspx), but I guess it would be "kinda too much" for a **Data Formatter**. 

What do you think?

**Comment by samdark** [comment]
That's not really a formatter than. Let's keep it as is. Creating a link with callto is easy with anonymous function + raw format.

**Comment by dbsparkle** [comment]
Then what about adding it to HTML helper? http://www.yiiframework.com/doc-2.0/guide-helper-html.html#hyperlinks

Considering that we all are shifting to a mobile web domination, and because the hierarchical part `tel:` is as standard as `mailto:` - it was accepted 10 years ago in [rfc3986](http://tools.ietf.org/html/rfc3986#section-1.1.2) and registered in [IANA](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml).

Another reason is to preserve consistency and to provide users with a convenient method
for generating links like <?= Html::tel('Call Now', 'some-phone-number') ?>

**Comment by samdark** [comment]
<?php Html::a('call now', 'tel:some-phone-number') ?> isn't any worse.

**Comment by dbsparkle** [comment]
Haha, nice. Try it and then check what you'll get :)

**Comment by samdark** [comment]
I've meant `<?=`, of course, not `<?php`.

**Comment by dbsparkle** [comment]
I got it, I mean you'll have to do extra work before you are able to dial that number.
Besides your argument is also supposing that `mailto` helper should be deprecated for the sake of consistency. Anyways I give up - going to write my own component

**Comment by samdark** [comment]
Which extra work?

**Comment by dbsparkle** [comment]
### Case 1
Contains a  _space_ after `tel:` and written with full-width characters and your OS doesn't have Japanese language installed. 

`Html::a('call now', 'tel: ０８０１ー１１１ー１１１１')`

1. Chrome (desktop OS X) browser:  Won't react to this format;
2. Safari  and Firefox ( both are desktop OS X) browsers: will popup with "Facetime" app;

### Case 2
No _space_ and written with half-width characters.

`Html::a('call now', 'tel:08011111111')`

1. Chrome (desktop OS X) browser:  will popup with a "Facetime (phone call mode)" app;
2. Safari (desktop OS X) browser:  will popup with a "Facetime (phone call mode)" app;
3. Firefox (desktop OS X) browser: will still react with "Facetime" app;


### Case 3
No _space_ , written with half-width characters and digits are separated with dots.

`Html::a('call now', 'tel:0.801.111.1111')`

1. Chrome (desktop OS X) browser:  will popup with a "Facetime" app;
2. Safari (desktop OS X) browser:  will popup with a "Facetime (phone call mode)" app;
3. Firefox (desktop OS X) browser: will still react with "Facetime" app;

### Case 4
A _space_ after `tel:`, written with half-width characters and digits are separated with dots.

`Html::a('call now', 'tel: 0.801.111.1111')`

1. Chrome (desktop OS X) browser:  will not react;
2. Safari (desktop OS X) browser:  will popup with a "Facetime (phone call mode)" app;
3. Firefox (desktop OS X) browser: will still react with "Facetime" app;

And with the mobile browsers it gets even more quirky... Anyways, currently the bulletproof format is to write `tel:01234567890` - half-width characters, no separators and no space after `tel:`. :-/

Read more about phone number formatting here:

* http://www.lunametrics.com/blog/2014/01/16/phone-numbers-clickable-trackable-mobile-devices-javascript-google-tag-manager/
* https://developers.google.com/web/fundamentals/device-access/click-to-call/click-to-call?hl=en
* https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html

#### Reference images:
(Facetime app - phone calling mode) 
![banners_and_alerts](https://cloud.githubusercontent.com/assets/417757/7140849/b7782376-e308-11e4-9bd9-8dc3520e5e0f.png)

(Facetime app - video idle mode)
![screenshot_4_15_15__00_39](https://cloud.githubusercontent.com/assets/417757/7140853/be8bdf72-e308-11e4-9ad4-1a168cbf4d56.png)

**Comment by samdark** [comment]
Are full-width characters that common for phones?

**Comment by samdark** [comment]
Also https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L385 doesn't have any whitespace trimming or incorrect email processing.

**Comment by dbsparkle** [comment]
In Chinese, Japanese and Korean languages _half-width_ **is a rare thing** and usually used for specific purposes. Most of the times we type alphanumeric characters in a _full-width_ mode (phone or desktop - doesn`t matter).

Reference: http://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by dbsparkle** [comment]
> Also https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L385 doesn't have any whitespace trimming or incorrect email processing.


That`s why I thought that it`s more related to "Data Formatter" than "HTML Helper" itself (considering the localization issues etc).

**Comment by samdark** [comment]
Full-width chars issue changes everything.

**Comment by samdark** [comment]
I think both formatter and Html method could be added.

**Comment by dbsparkle** [comment]
So this is what initially I was going to propose:

1. [RFC2396] states that phone numbers **MAY contain** visual separators.


	> *A URI often needs to be remembered by people, and it is easier for people to remember a URI when it consists of 	meaningful components.*


   
2. The same document declares that `tel:` URIs **MUST NOT use spaces** in visual separators to avoid excessive escaping.

I guess that's why Chrome strictly follows the recommendation and doesn't recognise a string as a phone number if there is ANY space used after `tel:` part.


#### Proposed enhancements:

1. Trailing space trimming (after `tel:`, and maybe the same for other types like `mailto:` etc)
2. Format the string with half-width chars
3. Add `$options` for:
	* visual separator pattern (default is no separators)
	* visual separator character (default: `HYPHEN` other option `DOT`)
4. And maybe even a [type juggling (value to string)](http://php.net/manual/en/language.types.string.php#language.types.string.casting)


#### $options

Eg.: 

```
'template' => [2,4,4], // digits here define the char count after which the separator should be inserted. 
'separator => 'hyphen' // or 'dot'

``` 

The result of example above would be returned as 01-1234-1234...

**Comment by samdark** [comment]
I don't think we should modify the text itself. Normalizing link so it's undestood by browsers is enough.

**Comment by samdark** [comment]
I think what all separators and spaces could be removed:

```
+7 (939) 38-23-333 -> +79393823333
```

So it's a regex:

```
$phone = preg_replace('~[^+0-9]+~', '', $phone);
```

Not sure how to replace full-width chars with full-width ones. Is there any proven/standard method for it?

**Comment by dbsparkle** [comment]
Then we should keep digits only (you left "+" in your example).

Full-width to half-width conversion may be done with [mb_convert_kana()](http://php.net/manual/en/function.mb-convert-kana.php)

**Comment by samdark** [comment]
@dbsparkle `+` is meaningful character. It indicates international country code. Skype requires it to present in the phone string in order to pre-fill it into the client. If it's omitted i.e. href is `tel:7945445454`, it just opens dial-pad w/o any number pre-filled.

**Comment by samdark** [comment]
Which params should be passed to `mb_convert_kana()`?

**Comment by dbsparkle** [comment]
```
$original_string = '０−１００−１２３４−５６７８';
$converted_string  = mb_convert_kana($original_string, 'a', 'UTF-8');
$trimmed_string = preg_replace('~[^+0-9]+~', '', $converted_string);

// output check
echo $original_string;
echo $converted_string;
echo $trimmed_string;
```
result:

```
０−１００−１２３４−５６７８
0-100-1234-5678
010012345678
```

**Comment by vchenin** [comment]
i think it's better remove all characters except numbers and then add plus sign before:
```php
$trimmed_string = '+' . preg_replace('~[^0-9]+~', '', $converted_string);
```

**Comment by WadeShuler** [comment]
This hasn't been added yet? Seems pretty simple and straight forward... Should I create a pull request?

**Comment by SilverFire** [comment]
Rejected. See [this comment](https://github.com/yiisoft/yii2/pull/11882#issuecomment-260145718), please
