### ISSUE TITLE
Named param is not populated in AR where() in operator format

### ISSUE THREAD

**Issue by psihius** [yiisoft/yii2#8079]
Original query, where the problem occurred looks like this
```php
Companies::find()->where(
    [
        'and', 
        ['lang' => 'ru'], 
        [
            'or', 
            'original_id = :param',
            ['like', 'name', ':param']
        ]
    ],
    [':param' => $param]
);
```
The problem is in ['like', 'name', ':param'] - the named parameter is not processed, hence is not populated. The query is generated with the
```sql
SELECT COUNT(*) 
FROM `companies` 
WHERE (`lang`='ru') AND ((original_id="ЭКСТРАКТ") OR (`name` LIKE '%:param%'))
```

Either was overlooked, or intentional :)

**Comment by samdark** [comment]
`and` currently supports 2 operands. 3 supplied so 3rd is ignored.

**Comment by samdark** [comment]
PDO which we're based on can't reuse parameter twice in a query:

> You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on.

https://php.net/manual/en/pdo.prepare.php
