### ISSUE TITLE
Migration bug

### ISSUE THREAD

**Issue by zabaz** [yiisoft/yii2#8080]
the first field type TYPE_TIMESTAMP in migration, automatically add CURRENT_TIMESTAMP by default value on update in MySql

![jfjg8vt](https://cloud.githubusercontent.com/assets/6939391/7141142/48d2b2fe-e2d8-11e4-949b-fe0a88aebb8a.png)

**Comment by zabaz** [comment]
code :  $this->createTable('coupon', [
            'id' => Schema::TYPE_PK,
            'created_by' => Schema::TYPE_INTEGER,
            'created_at' => Schema::TYPE_TIMESTAMP,
            'updated_by' =>  Schema::TYPE_INTEGER,
            'updated_at' =>  Schema::TYPE_TIMESTAMP,
            'status' =>  Schema::TYPE_BOOLEAN,
            'limit' =>  Schema::TYPE_INTEGER,
            'expire_date' =>  Schema::TYPE_TIMESTAMP,
            'start_date' =>  Schema::TYPE_TIMESTAMP,
            'user_id' =>  Schema::TYPE_INTEGER,
            'site_id' => Schema::TYPE_INTEGER,
            'count' => Schema::TYPE_INTEGER
        ]);

**Comment by klimov-paul** [comment]
This is MySQL issue, not Yii.
See: https://dev.mysql.com/doc/refman/4.1/en/timestamp.html
It tells:

> The first TIMESTAMP column in table row automatically is set to the current timestamp when the record is created if the column is set to NULL or is not specified at all.

**Comment by zabaz** [comment]
Thanks a lot
