### ISSUE TITLE
Don't working convert() method from class AssetConverter on hosting

### ISSUE THREAD

**Issue by grandemeister** [yiisoft/yii2#8088]
Hi, all!
Please, anybody help me. I have compiled css files from .less on local computer - that's nice working. Local configuration - Ubuntu 14.04. Upload on remote hosting - less-files don't compiling :(
Hosting - FreeBSD. Lessc installed and working from bash. But yii app don't running converter.
I tried to write full path to lessc - same problem (not working), i tried to run lessc in php script in functions exec, also proc, which use in AssetConverter class, - it works! From application - don't working :( And at the same time debug log haven't no one mentions about AssetConverter and convert method. 
Please hint me, where to look?

**Comment by klimov-paul** [comment]
Does other assets, which have no less or other compllining involved, are published correctly?

**Comment by grandemeister** [comment]
Yes, exactly right. 
Debug toolbar - Asset bundles 5, and in log: Total 5 asset bundles were loaded.
bootstrap.css, normalize css, etc are loaded correctly. 
Don't working only convert method and only on hosting. More differences:
php 5.6 vs 5.5 on local comp
Can i try to run this method from app directly, not in web.php? For catch.

**Comment by klimov-paul** [comment]
Trace you program, see if actually calls `AssetConverter::runCommand()`.
If it does check the status code and target files existance just after that.

**Comment by grandemeister** [comment]
I found this mention very careful :)
On local comp it written, in logs on hosting - missing

**Comment by klimov-paul** [comment]
So which status does `proc_close()` return?

**Comment by klimov-paul** [comment]
Enable `YII_DEBUG` if haven't already.

**Comment by grandemeister** [comment]
YII_DEBUG enabled, i see logs.
protected function runCommand($command, $basePath, $asset, $result)
{
...
}
from yii\wev\AssetConverter don't running totally!
I tried specially write wrong command in web.php, as "'less' => ['css', 'lessc1234 {from} {to} --no-color']," and re-started application - don't show anyone errors or warning. But, if i write "'class' => 'yii\web\AssetConverter1234'," - app show error :)

**Comment by grandemeister** [comment]
Ok, i can just copy compiled css on the hosting... but really very interesting bug. May be close issue, if have not methods for catch this?

**Comment by klimov-paul** [comment]
Trace `AssetBundle::publish()`.
Does conditions `(isset($this->basePath, $this->baseUrl) && ($converter = $am->getConverter()) !== null)`, `Url::isRelative($css)` are passing or not?

**Comment by grandemeister** [comment]
I'm sorry, please tell me, where i must write "AssetBundle::publish()" and trace it? Have not enough knowledges for this :(

**Comment by klimov-paul** [comment]
It seems we are not going anywhere here.
I am closing this, unless more coherit information arrives.
