### ISSUE TITLE
GridView applyFilter reduce Array to only one Element

### ISSUE THREAD

**Issue by ToSchC** [yiisoft/yii2#8089]
# Problem
By using an Array Value (e.g. checkboxList) the apply-Filter-Function of GridView reduces elements to last one.
# File
[yii2/framework/assets/yii.gridView.js](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.gridView.js#L84)
```javascript
applyFilter: function () {
     var $grid = $(this), event;
     var settings = gridData[$grid.attr('id')].settings;
     var data = {};
     $.each($(settings.filterSelector).serializeArray(), function () {
          data[this.name] = this.value;
     });
```
# Example
## before applyFilter function
'example' => [ 
     0 => 'value1'
     1 => 'value2'
     2 => 'value4' 
]
## after applayFilter function
'example' => [
     0 => 'value4'
]

**Comment by Ganesch** [comment]
I need a solution, too

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/d3cfb87ba67a328d197d1a9e52dbb12a7bf8476b, #10302
