### ISSUE TITLE
ldap search not working 

### ISSUE THREAD

**Issue by shorif2000** [yiisoft/yii2#8090]
I am trying to do ldap_search but it is not working

error i recieve is 

 PHP Warning – yii\base\ErrorException
ldap_search(): Search: No such object

I have tried using normal php ldap and the plugin https://github.com/ccottet/ldap

**Comment by klimov-paul** [comment]
How does this realted to Yii?
Most probably you haven't installed 'LDAP' PHP extension.

**Comment by shorif2000** [comment]
yes it is intalled because i am trying to ugrade yii1.x application which uses the same code and works
