### ISSUE TITLE
StringHelper::truncateHtml

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#8091]
$string = '<p>Hello</p>';
$count = 150;
$suffix = '...';
$asHtml = true;

it converts to <p>Hello</p>...

It should not add ... because it does not meet 150 characters.

**Comment by cebe** [comment]
documentation is quite clear about this:
>      * @param integer $length How many characters from original string to include into truncated string.
>     * @param string $suffix String to append to the end of truncated string.

this means that if you want a maximum of 150 including `...` you have to specify 147 for the $length.
