### ISSUE TITLE
Feature request ExistValidator for relations

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#8092]
To check the referential integrity one might define the exist validator specifying the  'targetClass'  and 'targetAttribute'. Based on this information a new query will be generated and executed. 
But usually there is already such an query defined by a a hasOne relation.

So it would be great to do something like 

``` php
 ['ableseartID', 'exist', 'ableseart'],

 public function getAbleseart()
    {
        return $this->hasOne(Ableseart::className(), ['id' => 'ableseartID']);
    }
```

instead of 

``` php
 ['ableseartID', 'exist', 'targetClass' => Ableseart::className(), 'targetAttribute' => 'id'],
```

**Comment by dynasource** [comment]
@twinni, are you willing to create PR with your feature?

**Comment by cebe** [comment]
could be `targetRelation` which overrides `targetClass` and `targetAttribute` it is set.

**Comment by SamMousa** [comment]
I don't get the implementation part though?
If this is about referential integrity would it not make more sense to use the relation definition instead of the value?

Something like
````
public function rules() {
    return [
        [['owner'], QueryCountValidator::class, 'query' => $this->getOwner()]
    ];

}

````

This way you don't have to use relation names as strings and you can use it no matter how heavy the model, since you can just run a count instead of actually instantiating it.
Furthermore, if it is about referential integrity it should check the state of the database not the state of the PHP code, where, for example, I can just set the value of a relation in PHP code.

For the current use case, it would already be sufficient to just use a `RequiredValidator`:
````
[['owner'], RequiredValidator::class]
````
As far as I can tell would lead to the same result.

**Comment by SamMousa** [comment]
I've been looking into this.
When implementing `validateAttribute` I noticed that validating a relation doesn't really make sense when validating attributes.
A relation already contains the attributes and therefore specifying it again at the attribute doesn't make much sense.

Would it be okay to just ignore the passed attribute parameter?
````
public function validateAttribute($model, $attribute)
{
// Ignore the attribute since we have a relation / query object that already defines the relation.
}
````

**Comment by SamMousa** [comment]
usage wise, one of these syntaxes might make more sense:
````
public function rules() {
    return [
        [['id'], 'number', ...],
        $this->getCustomer()->createValidator(), // Downside, contamination, query object is not about validation
        Validator::fromRelation($this->getCustomer()),
        new RelationExistValidator($this->getCustomer()))
    ];
}
````

This is a generic limitation of the way we do validation, same as that we can't properly specify multiple attributes per validation rule..

**Comment by twinni** [comment]
I suggest to create and execute a query like this:
```php
select exists (select 1 from %tablename% where %column% = %foreignKey%);
```
This is very fast and the related model don't need to be instantiated. 

Any syntax using the function instead of a string would be fine.

**Comment by SamMousa** [comment]
Your original point was that it should use the relation definition.
The original definition is a `Query` object which we can execute without instantiating the related model.

My question regarding syntax has more to do with (not) defining the attributes you're validating.
Consider I have a model `Car` and a model `User`, and `Car` belongs to `User` via the field `owner_id`.
The definition will look like this:
````
public function getOwner() {
return $this->hasOne(User::class, ['id' => 'owner_id']);
}
````

When validating the `Car` model, I just want to specify that it should have an owner without specifying that the `owner_id` field needs to be validated.
Instead I can use the relation definition to define a proper configuration, which is something that could be implemented using the syntaxes I described above.

**Comment by twinni** [comment]
@SamMousa, in most cases validation is not required and no rule should be defined. But in certain scenarios you might restrict valid values only to a subset of values that exists in the related table. It's up to the developer if he / she defines a rule or not.

The query object should be build on the relation definition. But instead of 
```php
select '*'
````  
I suggest to use
```php 
select 1
```
DB will answer the request in most cases by reading the index without a row lookup.
`LIMIT 1` will decrease response times an extra bit.

The additional `exists` wrapper just makes sure that you get a boolean and don't have to deal with an null or empty dataset . 
I'm sure you know about this already. Of course the 'normal' `query` object will do the same job.

**Comment by SamMousa** [comment]
@twinni I never said I would use the query object and execute it as is, that would be really inefficient.
Instead I can just wrap it in a count query that way it'll 100% of the time. 
Note that for array values we need to do more than check if 1 record exists, we need to know the count.
Regardless, your comments are not related to the questions I posed, they are related to how you think i'm implementing the actual validation.
I suggest you give me those comments after there is an actual implementation to comment on...

**Comment by twinni** [comment]
@SamMousa, I think I've answerd your question.  

> in most cases validation is not required and no rule should be defined. But in certain scenarios you might restrict valid values only to a subset of values that exists in the related table. It's up to the developer if he / she defines a rule or not.

The rest of my answer had additional hint's on how a query could be build. If you need to count the result then it's ok. If not it's a waste of ressources.

**Comment by SamMousa** [comment]
> Feature request ExistValidator for relations
Your whole post is about needing a validator...

To use this validator you would need to define a rule...
The rule specifies which validator to use on which attribute(s), if a developer does not specify a rule this whole discussion is not relevant since whatever implementation we make will not get called.

**Comment by twinni** [comment]
Maybe I don't got your point.
Of course the developer has to define an `exists` rule and specify which relation definition has to be used. Based on this rule a query should be created and executed. 
I don't see a reason to do any additional validation.

Only when a developer declares additional rules they must be executed.

**Comment by SamMousa** [comment]
I have not mentioned the word additional, i'm only talking about the `exists` rule.
Suppose that validator is built, and it does stuff... How would you define it in your `rules()` function, can you give me an example? :)

**Comment by twinni** [comment]
Your example with car and carOwner might be declared like this:
```php
['ownerID', 'exist', 'targetRelation' => $this->getOwner()],
```
The validator might modify the `query` object before execution (e.g. Select 1). To validate call the `count()` method or - this would be my choice - add the `limit 1` condition, wrap the query with the sql `exists` function and call the `one()` method.

**Comment by SamMousa** [comment]
Ah, we're getting closer to my point! :D
Your code:
````
['ownerID', 'exist', 'targetRelation' => $this->getOwner()],
````

This attribute that you specify, `ownerID`, is redundant. It is already specified as part of the relation.
If you change it in one place but not the other stuff will break.

So my point was ideally I'd want that part to be auto generated somehow:
````
[Validator::fromRelation($this->getOwner()]
````
Which could then return the correct array configuration where it extract the attribute name, `OwnerID` from the link in the relation.

And then there's the problem, what if the relation is based on 2 fields, how do we handle that?

**Comment by twinni** [comment]
>This attribute that you specify, ownerID, is redundant. It is already specified as part of the relation.
If you change it in one place but not the other stuff will break.

That's right.  Avoid duplication.

When more than on field is involved nothing changes. All fields are also declared in the relation definiton. Derived from this example in the docs.
> // a1 and a2 need to exist together, only a1 will receive error message
    ['a1', 'exist', 'targetAttribute' => ['a1', 'a2']],

we can use this syntax
```php
 [null, 'exist', 'targetRelation'=>($this->getOwner()]
```
The first element can be use to define which field receives the error message (if not the first one). 
```php
  ['a2', 'exist', 'targetRelation'=>($this->getOwner()]
```

**Comment by OndrejVasicek** [comment]
Shouldn't there be some info in guide? I'd create something, but I suck at english.

**Comment by samdark** [comment]
@OndrejVasicek you can create it as you can and we'll adjust it together correcting English.

**Comment by OndrejVasicek** [comment]
Ok @samdark . I've made my best :) I'm afraid you have to clean it a lot, but hope it helped at least.
