### ISSUE TITLE
Maybe the possibility of partial AJAX validation for active forms?

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#8093]
So I have an active form on my site which, using javascript, I made into two forms so that you must click one button to move onto the next part of the form.

The immediate problems I see is that you cannot simply hook into this active form validate function, especially if it is ajax. so for example I have a "continue" button. Every time the button is press I wanna run validation (again) along with some custom function like location finding and then if it validates pass onto the next page.

The next problem I see is that in the JS you cannot validate by a part of the form, only by the whole.

Has there been any thought into JS based multi page forms that are actually one form within the PHP code?

**Comment by unclead** [comment]
> The next problem I see is that in the JS you cannot validate by a part of the form, only by the whole.

You can use different scenario for every step on the form. 
For example you can add hidden field with name **scenario** and when user submit the form you able to set it value using beforeValidate event

In model class you can set which attributes needs to validate in every scenario

**Comment by Sammaye** [comment]
Can you provide some sample JS code for Ajax Validation with your proposal?
I cannot seem to understand that from the code

**Comment by unclead** [comment]
Something like this, but this is only an example
**Model**

```php
class WizardForm extends Model
{
    const SCENARIO_STEP_1 = 'scenario.step1';
    const SCENARIO_STEP_2 = 'scenario.step2';

    public $name;

    public $email;

    public function rules()
    {
        return [
            ['name', 'required', 'on' => [self::SCENARIO_STEP_1]],
            ['email', 'required', 'on' => [self::SCENARIO_STEP_2]]
        ];
    }

    public function scenarios()
    {
        return [
            self::SCENARIO_STEP_1 => ['name'],
            self::SCENARIO_STEP_2 => ['email'],
        ];
    }
}
```

**View**

```
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin([
                'id' => 'wizard-form',
                'enableAjaxValidation' => true,
                'enableClientValidation' => false
            ]); ?>
            <?= $form->field($model, 'name')->textInput() ?>
            <?= $form->field($model, 'email')->textInput() ?>
            <?= Html::hiddenInput('scenario', null, ['id' => 'wizard-scenario']) ?>
            <div class="form-group">
                <?= Html::submitButton('Step 1', ['id' => 'wizard-submit',   'class' => 'btn btn-primary', 'data-scenario' => WizardForm::SCENARIO_STEP_1]) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    <?php $this->beginBlock('JS');?>
        $(document).on('beforeValidate', '#wizard-form', function() {
            $('#wizard-scenario').val($('#wizard-submit').data('scenario'));
        });
    <?php $this->endBlock();?>
    <?php $this->registerJs($this->blocks['JS']);?>
</script>

```

**Controller**

```
    public function actionWizard()
    {
        $model = new WizardForm();
        $request = Yii::$app->getRequest();
        $scenario = $request->post('scenario', WizardForm::SCENARIO_STEP_1);
        $model->setScenario($scenario);

        if ($request->isPost && Yii::$app->getRequest()->post('ajax') !== null) {
            $model->load(Yii::$app->request->post());
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        return $this->render('wizard', [
            'model' => $model
        ]);
    }
```

**Comment by llfm** [comment]
A simple way of doing this is to read all the attributes of the step and validate only them with `validateAttribute`. (Perhaps it conflict with [this](https://github.com/yiisoft/yii2/issues/7927) issue)

**Comment by Sammaye** [comment]
It does seem like I am gonna have to take away the stuff from Yii2 core cos I need to know when validation is done, so it seems more and more that I need to manually control the form as unclead does, but that way does seem like a temporary winner, though would be good to be able to just call validate with a scenario in it in JS and use promises to get the result and then act on it

**Comment by Sammaye** [comment]
unclead works almost but no matter what I want to call validate when the first step button is pressed, this kinda relies on the form already being validated, I would prolly add a bit of code to check for error class on any of the inputs and not allow for the form to be submitted if there are any but that will open UI holes and make it seem a bit shoddy to the end user. This is a two step signup form so it has to transition perfectly.

**Comment by unclead** [comment]
@Sammaye tyou're right, my example hi=ust shows how you can work with scenarios. As i understood you wanna have some custom validation logic for every input on client side before whole form will be submitted. I havent tried it. The most simple way is using your own function in beforeValidate and if form has errors this function can return false what will stop further form validation

**Comment by Sammaye** [comment]
Hmm, I can use beforeSubmit probably since this is single logic for the step. Providing 

My scenario is that when the user clicks "next step" it needs to ping a geocoding web service and make sure that the place they have entered exists. If it does then it will carry on the form and fill in two fields: lat and long.

If I couple that event with scenarios I might just be able to do something...maybe
