### ISSUE TITLE
Package yiisoft/jquery is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by Lordfef** [yiisoft/yii2#8094]
Hi all, i update Yii2 (basic) with composer (just updated).
First i have this error:
Problem 1
      - yiisoft/yii2 dev-master requires bower-asset/jquery.inputmask 3.1.* -
  > no matching package found.
      - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery.inputmask 3.1.* ->
   no matching package found.
      - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii
  2[2.0.x-dev, dev-master].

So i read in another issue to try to update the composer asset plugin. I did it:
  - Removing fxp/composer-asset-plugin (v1.0.0-beta3)
  - Installing fxp/composer-asset-plugin (v1.0.0)

when i re-launch yii2 update with composer i have now this error:
Package yiisoft/jquery is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files

What can i do? 
Thank's

**Comment by samdark** [comment]
Remove vendor dir and try again.

**Comment by qRoC** [comment]
```
composer clear-cache
rm -rf vendor
composer update
```

**Comment by asimzeeshan** [comment]
@samdark I am getting the same error

    Package yiisoft/jquery is abandoned, you should avoid using it. No replacement was suggested.

Removed vendor folder and reran composer but same error appears again! any help?

**Comment by samdark** [comment]
Have you installed global composer plugin as mentioned in docs? http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer

**Comment by asimzeeshan** [comment]
@samdark of course, I tried doing it again but same error
also self-updated the composer

**Comment by cebe** [comment]
please paste your composer.json in full.

**Comment by kmergen** [comment]
I get also this error but only on my linux machine not on windows.
here my composer.json

```json
{
	"name": "Hundekauf.de",
	"description": "Yii 2 Basic Application hundekauf.de",
	"keywords": ["hundekauf", "Anzeigenmarkt", "Kleinanzeigen", "Welpen und Hunde kaufen und verkaufen"],
	"homepage": "http://www.hundekauf.de/",
	"type": "project",
	"license": "Privat",
	
	"minimum-stability": "dev",
	"require": {
		"php": ">=5.4.0",
		"yiisoft/yii2": "*",
		"yiisoft/yii2-bootstrap": "*",
		"yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-imagine": "*",
        "kmergen/yii2-widgets": "dev-master",
		"kartik-v/yii2-date-range": "*",
        "kmergen/yii2-feed": "dev-master"
	},
	"require-dev": {
		"yiisoft/yii2-codeception": "*",
		"yiisoft/yii2-debug": "*",
		"yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
	},
	 "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
	"config": {
		"process-timeout": 1800
	},
	"extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

```

**Comment by kmergen** [comment]
In my case I have solve the problem.
I have run composer as sudo and than the lock file owner is root.
You should run composer without sudo so that all file owner is logged in user.

**Comment by tamvodopad** [comment]
I have this problem too. Global composer plugin installed. composer.json from yiisoft/yii2-app-basic basic installation.

**Comment by ardar** [comment]
any more resolution for this same error, i also got this error, and cannot fix it for serveral days?

**Comment by boultra** [comment]
I also have the same problem.How to solve it?

**Comment by Faryshta** [comment]
@kmergen @Lordfef you have an outdated version of the composer plugin asset, run 

`composer global require "fxp/composer-asset-plugin:~1.0.0"`

The 1.0.0 at the end is the most important part.

**Comment by tof06** [comment]
Same problem for me. 
Removed vendor & composer.lock, re-ran composer, and  
`Package yiisoft/jquery is abandoned, you should avoid using it. No replacement was suggested.`

Isn't it because yiisoft/jquery-pjax [depends on](https://github.com/yiisoft/jquery-pjax/blob/master/composer.json#L13) yiisoft/jquery ?

**Comment by samdark** [comment]
No. Seems you're missing composer asset plugin: https://github.com/yiisoft/yii2/issues/8094#issuecomment-121707254

**Comment by tof06** [comment]
Hmm, I have the composer asset plugin... I even updated it to v1.1.1 to avoid deprecated warnings.

If I remove `yiisoft/jquery-pjax` from my composer.json, I don't have the warning message anymore.

**Comment by Faryshta** [comment]
@samdark if you check https://packagist.org/packages/yiisoft/jquery-pjax you will notice that indeed if you load pjax from composer it will ask you to install `yiisoft/jquery`

@tof06 if you require to use pjax I advice to install it using bower adding

`"bower-asset/yii2-pjax": "*"`

to your composer.json

**Comment by tof06** [comment]
@Faryshta Thanks, works fine now!

**Comment by samdark** [comment]
@Faryshta thanks! https://github.com/yiisoft/jquery-pjax/commit/593b9d694b80e6832ca1fcbcd34627372b689329

**Comment by kirill-konshin** [comment]
Why the heck should `yiisoft/jquery` and `yiisoft/jquery-pjax` be installed if I use Yii as a RESTful API? Maybe you should consider moving all UI stuff out?

**Comment by samdark** [comment]
Absolutely. It's already planned for next major versions.

**Comment by kirill-konshin** [comment]
Will it be Yii 3.x or 2.x?

**Comment by samdark** [comment]
2.1.x or 2.2.x.
