### ISSUE TITLE
Impossible object method call: Unique validator filter

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2#8095]
#### e.g.

The `filter` validator and the `when` option allows a callable. Like [this](https://github.com/yiisoft/yii2/issues/4883#issuecomment-54029353).
#### Unique validator filter

The same doesn't happen [here](https://github.com/yiisoft/yii2/blob/master/framework/validators/UniqueValidator.php#L103).

``` php
...
/* @var string|array|\Closure */
...
if ($this->filter instanceof \Closure) {
    call_user_func($this->filter, $query);
} elseif ($this->filter !== null) {
    $query->andWhere($this->filter);
}
```

This is useful when you want to serialize the model, reuse the filter or organize the function.
#### Solutions

To avoid BC as the filter allows an array:
- Change `instanceof \Closure` for `is_callable`.
- Check for `method_exists`.
- Check if the first element of the array is a string.

**Comment by klimov-paul** [comment]
I suppose changing to `is_callable`should be safe. It is unlikely `filter` value meant to be passed to `Query::andWhere()` will ever match such check.

**Comment by samdark** [comment]
`is_callable` will make it possible to pass PHP function names and various other things. Need to be verified that it's safe.

**Comment by klimov-paul** [comment]
We are talking of the validation rule, which is set up by developer - not got from user or something.

Of course construction like `['DateTime', 'format']` will be a callable, but it is unlikely to be a filter.

**Comment by klimov-paul** [comment]
Although we may enforce `filter` to be not scalar, avoiding plain function calls, just in case.
