### ISSUE TITLE
Using ArrayHelper::getValue() for Yii::$app->request->get() and Yii::$app->request->post()

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#8100]
There is built-in way to access nested array properties via `ArrayHelper::getValue()` using dot notation, for example:

```php
use yii\helpers\ArrayHelper;

$array = [
    'property1' => [
        'property2' => [
            'property3' => 'value',
        ],
    ],
];

$value = ArrayHelper::getValue($array, 'property1.property2.property3');
```
Maybe add shortcut for `Yii::$app->request->get()` and `Yii::$app->request->post()`?

Example:

```php
$value = Yii::$app->request->post('property1.property2.property3');
```

instead of:

```php
$value = ArrayHelper::getValue(Yii::$app->request->post(), 'property1.property2.property3');
```

Maybe it's better to check second parameter with `strpos` for dot existence first and then apply `ArrayHelper::getValue()` call. What do you think?

**Comment by bethrezen** [comment]
:+1:

**Comment by qiangxue** [comment]
I'm against this. This is abusing the dot notation because you can say the same thing for every place like `post()`.

**Comment by ScottHuangZL** [comment]
Agree Qiang's point.
