### ISSUE TITLE
Twig tag cannot get resolved inside nav_widget tag

### ISSUE THREAD

**Issue by kafuton** [yiisoft/yii2#8101]
Code is as below:

{{ nav_widget({
                'options': {
                    'class': 'navbar-nav navbar-right',
                },
                'items': [
                    { 'label': "Welcome, {{ app.user.identity.username }}", 'items': [ { 'label': 'Logout', 'url': '/site/logout', 'linkOptions': { 'data-method': 'post' } } ] }
                ]
            }) }}

If the logged in username is 'James', but what displayed on web is still {{ app.user.identity.username }}. Thus the twig tag {{ app.user.identity.username }} is not resolved in such case.

Any suggestion?

**Comment by vitalik74** [comment]
Use `"Welcome, " ~ app.user.identity.username`. See doc http://twig.sensiolabs.org/doc/templates.html#other-operators
