### ISSUE TITLE
Calling unknown method: yii\db\mysql\Schema::getSchemaNames()

### ISSUE THREAD

**Issue by DenisOgr** [yiisoft/yii2#8103]
I have updated composer packages and have got this problem, when I tried  generate model with Gii
I have never got same problem with Gii
comoser.json
```
................
"require": {
		"php": ">=5.4.0",
		"yiisoft/yii2": "*",
		"yiisoft/yii2-bootstrap": "*",
		"yiisoft/yii2-swiftmailer": "*",
.............
      },
........
```
```./yii```  ->   ```This is Yii version 2.0.4-dev.```

I could not find this function in framework, but I found calling in vendor/yiisoft/yii2-gii/generators/model/Generator.php:344 :
```
            $schemaNames = $db->getSchema()->getSchemaNames();
```

**Comment by SDKiller** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/Schema.php#L205

**Comment by klimov-paul** [comment]
Most likely it is a same issue as #5060

**Comment by cebe** [comment]
this is a problem with dependencies between dev versions of gii and yii2. the latest version of gii requires yii 2.0.4-dev after a certain commit. will be solved when 2.0.4 is released. We should adjust the composer.json of gii extension.

**Comment by cebe** [comment]
see also https://travis-ci.org/yiisoft/yii2-gii/builds/58326763

**Comment by DenisOgr** [comment]
@SDKiller   I have ran composer update, I went to /vendor/yiisoft/yii2/   and ran ```git log ``` I have seen 
```
commit 0dc97c82cc4c5c9427695030575d9fcfe4bd5f9d
Author: Qiang Xue <qiang.xue@gmail.com>
Date:   Sun Mar 15 01:26:06 2015 -0400

    Finished AR guide [skip ci]
```
It is not last commit.

**Comment by DenisOgr** [comment]
@cebe Should I wait for the next release?

**Comment by cebe** [comment]
if you want to use a dev version of gii you have to use the latest dev version of yii2 too.

**Comment by cebe** [comment]
should be fixed by https://github.com/yiisoft/yii2-gii/commit/32f02ba882018698d488e64bd0cf12da4ce2febc
