### ISSUE TITLE
Memcache Expire Regression

### ISSUE THREAD

**Issue by wilwade** [yiisoft/yii2#8104]
https://github.com/yiisoft/yii2/commit/fcf2d0a3f2e4371be6fe09d9aa435fd006bed07b#diff-f9f025d17dc839d144e378e0dda1414cL202

Memcached uses timestamp expiration, while Memcache uses seconds (this is only for set however. For add it uses expiration)

http://php.net/manual/en/memcache.set.php
http://php.net/manual/en/memcached.expiration.php

I'll get a pull request in

**Comment by qiangxue** [comment]
PHP manual says "Expiration time of the item. If it's equal to zero, the item will never expire. You can also use **Unix timestamp** or a number of seconds starting from current time, ..."
