### ISSUE TITLE
How should work function ArrayHelper :: index for documentation, when the key value has null?

### ISSUE THREAD

**Issue by InteLigent** [yiisoft/yii2#8106]
In the doc:
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L236
written that If a key value is null, the corresponding array element will be discarded and not put in the result, but it is not work.

Example:
```php
$array = [
     ['id' => '123', 'data' => 'abc'],
     ['id' => '345', 'data' => 'def'],
  ];
$result = ArrayHelper::index($array, function ($element) {
return null;
});
echo \yii\helpers\VarDumper::dumpAsString($result, 10, true);

'' => [
        'id' => '345'
        'data' => 'def'
]
```

**Comment by quantum13** [comment]
@SilverFire was changed and fixed in https://github.com/yiisoft/yii2/pull/10846

**Comment by SilverFire** [comment]
@quantum13 thank you
