### ISSUE TITLE
not standar name action in Standalone Actions 

### ISSUE THREAD

**Issue by rahif** [yiisoft/yii2#8107]
if you have one controller, for example siteController with Standalone Actions :

    public function actions()
    {
        return [
            'two-words' => [
                'class' => 'yii\web\ViewAction',
                'viewPrefix' => 'page',
            ],
            'twoWords' => [
                'class' => 'yii\web\ViewAction',
                'viewPrefix' => 'extend',
            ],
        ];
    }

Link works with action two-words ..../index.php?r=site/two-words&page=index 
Link works with action twoWords ..../index.php?r=site/twoWords&page=extend works

This is different to the criteria of In-line Actions, it's not very important but i think its better to have one general case.

**Comment by cebe** [comment]
these are two different things, `two-words` is the action ID, while `twoWords` would be the name of the method defining the action. In `actions()` all actions should be indexed by their ID. `twoWords` is not a valid ID so it will not work.

**Comment by rahif** [comment]
Thanks. Its clear now.
By the way, great work with the framework
