### ISSUE TITLE
Why has yiiform JS file got a messages param in beforeValidate?

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#8108]
Right here: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L32 Are there really messages to be had in before validate?

It always logs as empty to me

**Comment by cebe** [comment]
it would be logical if one could add some messages there to do some custom validation.

**Comment by Sammaye** [comment]
Ah ok, probably not what I am looking for though, but sounds reasonable
