### ISSUE TITLE
Yiiform JS events could do with being promise compatible

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#8109]
I need to call an external webservice on `beforeValidate` within my active form's JS however, even when using `return $.when()` in `beforeValidate()` it does not seem to work.

Would be good if before validate was compatible with promises.

**Comment by unclead** [comment]
As i see in doc activeFrom should support deferred:
https://github.com/yiisoft/yii2/blob/2.0.3/framework/assets/yii.activeForm.js#L34
https://github.com/yiisoft/yii2/blob/2.0.3/framework/assets/yii.activeForm.js#L306

have you tried it?
I didnt use it in my app, but i think it can help you

**Comment by Sammaye** [comment]
Ah hang on I think late last night I misread it, I might still have a point
but let's see

**Comment by Sammaye** [comment]
Aye, should have read better last night. Thanks for the link it works perfect :)

**Comment by unclead** [comment]
@Sammaye may be you can write an article about promises and activeForm in [yii2-cookbook](https://github.com/samdark/yii2-cookbook)? I think it can be useful

**Comment by Sammaye** [comment]
I prolly should or make a pull request to the doc, even with the full doc it was confusing a little how and why the used resolve etc, took a bit of debugging and console logging to actually see what was going on and code around it
