### ISSUE TITLE
add microseconds in logging

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#8112]
i would like to profile performance, but 1 second is not enough, i don't see anything
how can i get microseconds w/o extending logger or target?

regards

**Comment by SDKiller** [comment]
`\yii\log\Logger::log` operates `microtime`

If you use DbTarget and precision is lost - probably ou need to change column type - see this issue

https://github.com/yiisoft/yii2/issues/7384

**Comment by yurii-github** [comment]
i used file target

that's how logging looks like

\Yii::beginProfile('reflection', 'config');
\Yii::endProfile('reflection', 'config');

2015-04-17 12:26:17 [::1][-][-][profile begin][config] reflection
2015-04-17 12:26:17 [::1][-][-][profile end][config] reflection

there's no option microtime

**Comment by klimov-paul** [comment]
For `DbTarget` it is so indeed.
However `FileTarget` saves timestamp as a date in format 'Y-m-d H:i:s'.

**Comment by klimov-paul** [comment]
@yurii-github you may use `DbTarget`, its 'log_time' field will contain time in microseconds

**Comment by klimov-paul** [comment]
We may introduce `yii\log\Target::timeFormat` field to be used inside `yii\log\Target::formatMessage()` instead of hardcoded one, but such option will be redundant for some log targets.

**Comment by SDKiller** [comment]
> introduce yii\log\Target::timeFormat field to be used inside yii\log\Target::formatMessage() instead of hardcoded one

:+1: 
For BC `'Y-m-d H:i:s'` could be used as default

**Comment by yurii-github** [comment]
i see. i found this 'Y-m-d H:i:s' in base Target class. function formatMessage() looks suspicious.. does it mean that in dbTarget datetime is duplicated in message field?

**Comment by klimov-paul** [comment]
No, `DbTarget` does not use `formatMessage` at all.

**Comment by yurii-github** [comment]
i dig a bit and i got the chain
Logger::log() -> [timestamp] -> FileTarget::formatMessage() -> [TIME]+[message format]

looks ok but  Logger gives precision loss(left):
Logger's microtime(true) VS microtime()
1429269595.0678  VS 0.06783400 1429269595
1429269595.0681 VS 0.06812600 1429269595
1429269807.9862 VS 0.98618200 1429269807
1429269807.9863 VS 0.98634200 1429269807
so, it gives mili instead of micro

 to use my own extended Logger i had to declare public $targets = []; somehow it fails w/o it.
Error goes away, but targets in config are not used.

the way i'm going to use it
<b>components\Logger::log()</b>
new param : with_precision 
- $time = microtime(true);
+ $time = $this->with_precision ? explode(' ', microtime()) : microtime(true);

<b>components\FileTarget::formatMessage()</b> (declared in Target::formatMessage)
new param: with_microtime 
+ $usec = 0; $sec = 0;
+ if (is_array($timestamp)) {
+	list($usec, $sec) = $timestamp;
+ } else {
.....
- return date('Y-m-d H:i:s', $timestamp) ...
+ return (date('Y-m-d H:i:s', $sec) . ($this->with_microtime ? (':'.floor($usec*1000000)) : '')) ...

**Comment by yurii-github** [comment]
yii\log\Logger is hardcoded in BaseYii :: getLogger() as
return self::$_logger = static::createObject('yii\log\Logger');

so Logger looks like final and targets are in dispatcher. what will happen after Dispatcher extend? 

regards

**Comment by SDKiller** [comment]
> Logger's microtime(true) VS microtime()

It's just two ways to represent the same value.

> but Logger gives precision loss

It's because of default precision value in php.ini, you may increase it

https://php.net/manual/en/ini.core.php#ini.precision

Extend `FileTarget` with your own class, override in it `formatMessage()` function, put you custom class in config

```
    'components' => [
        ...
        'log' => [
            'targets' => [
                [
                    'class'      => 'my\custom\FileTarget',
                    ...
                ],
            ],
        ],
```

**Comment by yurii-github** [comment]
+2 to precision made the deal. so i don't need to change to text microtime.

 thanks
