### ISSUE TITLE
CompareValidator fails on equality

### ISSUE THREAD

**Issue by bhagwatchouhan** [yiisoft/yii2#8117]
When we pass the attribute value and compareValue to check whether both are not equal, the validator fails.

[ '<attribute>', 'compare', 'on' => '<scenario>', 'type' => 'number', 'compareValue' => 10, 'operator' => '!=', 'message' =>  'attribute must be equal to 10.' ]

Ex:

attribute value: 10
compareValue: 10
operator: !=

Result:
It shows the validation error.

Expected Result:
It must not show error when values are same.

**Comment by bhagwatchouhan** [comment]
We have made temporary solution which works as expected:

<pre>
	public function validateStatus( $attribute, $params ) {

		$status = $this->$attribute;

		if( $status != 10 ) {

			$this->addError( $attribute, 'attribute must not be equal to 10.' );

			return false;
		}

		return true;
	}
</pre>

**Comment by bhagwatchouhan** [comment]
It seems the validator is working fine. The below mentioned fix resolves the issue. It both values are equal, it won't throw error.

[ '', 'compare', 'on' => '', 'type' => 'number', 'compareValue' => 10, 'operator' => '==', 'message' => 'attribute must be equal to 10.' ]

**Comment by mdmunir** [comment]
:grinning:
