### ISSUE TITLE
Detach behavior by class name

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#8118]
Detaching named behavior is easy and covered in docs [here](http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html#detaching-behaviors).

But if no name given, we have to loop through `behaviors()` configurational array and compare classes until they match. It's not a big problem, but I think it will be better if framework have support of detaching by class name.

**Comment by mdmunir** [comment]
If you have plan to detach a behavior, you have to named it :D

**Comment by arogachev** [comment]
What if it's inside some extension? And detaches there? Force user to name it?

**Comment by klimov-paul** [comment]
Such feature does not make sense. Behaviors are attached or detached as an objects, not a classes.
Same component may have several behaviors of the same class attached.
