### ISSUE TITLE
debug toolbar broken when showScriptName is set to false

### ISSUE THREAD

**Issue by zhangster** [yiisoft/yii2#8123]
the error displayed is:

Not Found
The requested URL /debug/default/toolbar was not found on this server.

I tried several urlRules, none are working

**Comment by samdark** [comment]
Cannot reproduce:
![](https://cloud.githubusercontent.com/assets/47294/7220496/9bf11424-e6d1-11e4-996b-d229091bdb04.png)

**Comment by cebe** [comment]
@zhangster make sure you have a proper rewrite configured in .htaccess or nginx config.

**Comment by zhangster** [comment]
Thanks!  That worked
