### ISSUE TITLE
Could do with an easy way to change redirect URL in AuthClient extension

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#8132]
There are a couple of ways to make the redirect URL change, specifically for the JS redirect, not just a normal redirect away, but they all require more work than this scenario (which is probably quite common) seems to merit.

Say for example I have a two step account creation process:

- The user clicks the social login icon
- They are redirected to a signup step 2 page which asks for a little more info before signing them up
- If they are not new log them straight in 

This could be really common and I am surprised I have not ran into it already.

The way to do this currently is you either extend the AuthAction and change the logic a bit to allow a dynamically set url or change the logic of authSuccess a bit to allow a response of a URL to add to the JS redirect, currently only response is allowed and that causes a redirect within the auth window.

What do you think?

**Comment by Sammaye** [comment]
It is good to note that I do not know the redirect action URL until the action is finished processing

**Comment by Sammaye** [comment]
Created this:

```php
<?php
namespace common\components;

class AuthAction extends \yii\authclient\AuthAction
{
	protected function authSuccess($client)
	{
		if (!is_callable($this->successCallback)) {
			throw new InvalidConfigException('"' . get_class($this) . '::successCallback" should be a valid callback.');
		}
		$response = call_user_func($this->successCallback, $client);
		if ($response instanceof Response) {
			return $response;
		}
		return $this->redirectSuccess($response);
	}
}
```

Seems to work

**Comment by bwoester** [comment]
I needed the same workflow. My solution was to configure the action's successCallback, and to handle the redirect logic in the controller providing the authAction. This way, there's no need to extend another class from the action.

https://github.com/iw-reload/iw/blob/master/frontend/controllers/SiteController.php#L64

**Comment by Sammaye** [comment]
The only problem is that that only works if you already know, before the
logic in the action what you wish the success url to be right?

**Comment by Sammaye** [comment]
Oh wait I see now, the action is actually pulled into the scope of the
AuthAction class, didn't know that thanks

**Comment by klimov-paul** [comment]
I can't see any problem: `AuthAction::successCallback` allows returning of the `Response` instance, which can handle whatever you want, redirects included.
https://github.com/yiisoft/yii2-authclient/blob/master/AuthAction.php#L84

If you with to invoke `AuthAction::redirect()` instead of `Controller::redirect()`, you may use following code:
```php
public function onAuthSuccess($client)
{
    $attributes = $client->getUserAttributes();
    // ...
    return $this->action->redirect($myURL);
}
```

**Comment by Sammaye** [comment]
> I can't see any problem: AuthAction::successCallback allows returning of
the Response instance, which can handle whatever you want, redirects
included.

The problem I found is here:
https://github.com/yiisoft/yii2-authclient/blob/master/AuthAction.php#L216
it doesn't actually do that. It handles a normal request but of course
won't handle a JS redirect on return. But yes, I agree, it is easy enough
when the code is in the scope of the action.
