### ISSUE TITLE
Custom Validation not working in yii2

### ISSUE THREAD

**Issue by olivebranches** [yiisoft/yii2#8135]
Following code for custom validation in yii2 model is not working at all. What is wrong in this code?

    public function rules()
    {
         return [
                       [ ['file_url'], 'new_required',  'skipOnEmpty'=> false ],
                   ];
    }

    public function new_required($attribute, $params)
    {
            if (empty($this->file_url))
           {
               $this->addError($this->file_url,  'Cannot be empty');
               return false;
            }
            return true;
    }

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for bug reports and feature requests.

**Comment by unclead** [comment]
@olivebranches you have to use the following code
```
$this->addError('file_url',  'Cannot be empty');
```

**Comment by olivebranches** [comment]
@unclead  Still not working

**Comment by unclead** [comment]
@olivebranches it works for me. 
```
    public function new_required($attribute, $params)
    {
        if (empty($this->$attribute))
        {
            $this->addError('file_url',  'Cannot be empty');
        }
    }
```
btw you have to use forum as samdark said
