### ISSUE TITLE
强哥，问一个小问题

### ISSUE THREAD

**Issue by niefufeng** [yiisoft/yii2#8136]
gridview（好吧，是search模型）有个统计，看下sql，是

```
SELECT COUNT(*) FROM `user`
```

为啥不`统计主键`呢？

**Comment by lichunqiang** [comment]
这个可以自定义吧， count * 是默认的

**Comment by IndeedPlusPlus** [comment]
It make no sense to specify columns when counting records.

**Comment by fatrbaby** [comment]
会把COUNT(*)当成一个常量处理，性能更好。

**Comment by panique** [comment]
@str2code Can you please add a english translation to your comment ? Thanks!

**Comment by ScottHuangZL** [comment]
His question is: Why not count the key column to get best performance if compare to count(*)?

**Comment by str2code** [comment]
@panique look up!!!see @ScottHuangZL comment!

**Comment by azhun** [comment]
有些特殊时候，有些表格是没有主键字段的

**Comment by fatrbaby** [comment]
@azhun Innodb engine table had better have a primary key.

**Comment by lichunqiang** [comment]
![image](http://img12.jiuxian.com/bill/2015/0701/ee4d6b8a1e784753b566e80269a7c527.jpg)

**Comment by dynasource** [comment]
closing in favor of https://github.com/yiisoft/yii2/issues/10055
