### ISSUE TITLE
[discussion] Dependency Injection

### ISSUE THREAD

**Issue by freezy-sk** [yiisoft/yii2#8137]
Hello
At first sorry for my bad english.

I would like to start discussion about current implementation of DI.
I was wondering how to achieve injecting of instanciated application components through their class or interface in `__construct` (like in Laravel or Symfony) and without calling them by their alias.

Right now when I want to have some service which uses configured database, it must be done like this:
```php
public function __construct($config = [])
{
    parent::__construct($config);
    $this->db = Yii::$app->get('db');
}
```

How it should be done:
```php
public function __construct(\yii\db\Connection $db, $config = [])
{
    parent::__construct($config);
    $this->db = $db;
}
```

The questions is if it needs some big changes in DI Container or it can be done easily.
If it is not that hard to make it, would it be in one of next minor releases?

Thanks
Marek

**Comment by samdark** [comment]
You can do it either way. Yii supports both.

**Comment by freezy-sk** [comment]
@samdark It doesn't doing it right
When I want instanciated database connection through DI in construct param, I just get new instance without configuration of running application
```php
public function __construct(\yii\db\Connection $db, $config = [])
{
    parent::__construct($config);
    var_dump($db, Yii::$app->get('db'));
}
```
```
$db

object(yii\db\Connection)#222 (32) {
["dsn"]=> NULL
["username"]=> NULL
["password"]=> NULL
["attributes"]=> NULL
["pdo"]=> NULL
...
} 
```

```
Yii::$app->get('db')

object(yii\db\Connection)#69 (32) {
["dsn"]=> string(32) "mysql:host=localhost;dbname=test"
["username"]=> string(4) "test"
["password"]=> string(4) "test"
["attributes"]=> NULL
["pdo"]=> object(PDO)#73 (0) { }
...
} 
```

**Comment by samdark** [comment]
Well, these are two different connections. In Yii you can define multiple connection components i.e `db` for MySQL primary database, `analyticsdb` for legacy MSSQL database etc. If you want to provide defaults per class you can use

```php
\Yii::$container->set('yii\db\Connection', [ /* config here */ ]);
```

**Comment by freezy-sk** [comment]
@samdark yes, I know. Database connection was chosen just for example. There are many other application components (like Session, Request or User) which in basic use don't have multiple instances.
So I want to use them with DI the right way.
I don't want to make overhead with defining default configurations in some bootstraping part of application because it not the clear way.
That's the reason why I started this discussion.

**Comment by cebe** [comment]
@freezy-sk you are mixing up two concepts here, Yii has [dependency injection](http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html) via `Yii::$container` and a [service locator](http://www.yiiframework.com/doc-2.0/guide-concept-service-locator.html) via Yii::$app.

In the service locator you have configuration per service/component which has a name. In the DI container you define configuration by class name.

**Comment by freezy-sk** [comment]
@cebe thank you for clarification.
Could you please give me some hints how to connect these two approaches for core components like database, session, request and user?

This are just my thoughts so please correct me if I'm going wrong. :)

Extending application and assigning services to their classes or interfaces just after bootstrap?
This will be enough?

**Comment by cebe** [comment]
first you should read through the two guide pages linked above. They should contain all you need, if still something is unclear, let us know so we can improve the guide.

You can set up DI container in index.php or included config files.

**Comment by freezy-sk** [comment]
thanks a lot :)
