### ISSUE TITLE
ENH: Unsafe Validator

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#8139]
Now, to exclude some attribute from mass assigned. We must override method `Model::scenarios()`. For me, its not simple and potentially mistake. E.g, we add new attribute and forgot to add it to `Model::scenarios()`, the attribute will never be validate.
For simplify, i hope we have unsafe validator. Such as yii1 has. http://www.yiiframework.com/doc/api/1.1/CUnsafeValidator

**Comment by cebe** [comment]
we already have `SafeValidator` so we could add unsafe as well...

**Comment by mdmunir** [comment]
Of course i can submit PR for this.

**Comment by cebe** [comment]
sure, go ahead.

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/pull/8145#issuecomment-158827726

**Comment by cebe** [comment]
reopening as there is still discussion going on in the PR.

**Comment by cebe** [comment]
A different solution is in #10234

**Comment by SilverFire** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/da82ff3fb1625597706d9da3c76ca5a0a1ee7ad5
