### ISSUE TITLE
ActiveQuery max() function does not quote column name

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#8141]
I use MySQL. ActiveQuery method named max fails SQL query, because 
query is 
```sql
SELECT MAX(on) FROM `computer` WHERE `type`=1
```

it should be
```sql
SELECT MAX(`on`) FROM `computer` WHERE `type`=1
```

I use on word as shortcut from words order number.

**Comment by cebe** [comment]
This is expected and documented:

http://www.yiiframework.com/doc-2.0/yii-db-query.html#max%28%29-detail
> The column name or expression. Make sure you properly quote column names in the expression.

**Comment by mklemarczyk** [comment]
Are you kidding me? My application must work on MySQL and MS SQL databases. These database systems have different quotation.

**Comment by samdark** [comment]
```php
->max('[[on]]')
```

**Comment by mklemarczyk** [comment]
Thank you so much @samdark, you should attach it to documentation.

**Comment by cebe** [comment]
done.
