### ISSUE TITLE
 Priority in migrations

### ISSUE THREAD

**Issue by boscobass** [yiisoft/yii2#8142]
This week I had to create multiple migrations where there were several FKs between them. The problem is that the execution order is the name sometimes a migration was performed before the creation of the table to which the FK makes reference.

My question:

A feature would be interesting to sort and make a migration is performed only after another?

Ps.: Sorry for my English :)

**Comment by cebe** [comment]
which version of yii are you using? normally the migration application order is by the time of creation, however there was an issue with this in the dev version 2.0.4-dev. which has been fixed a few days ago.

**Comment by boscobass** [comment]
I have the latest version.
My suggestion is a form of a migration call another, cascading. So do not would depend on the order of creation. In my view it would be more robust

**Comment by boscobass** [comment]
This week I had a problem with that, I made several migrations related but because of the creation of order gave error.
I know that if I had created in the right order, nothing would have gone wrong
but I believe it to be depending only on the creation of order leaves everything very flawed

**Comment by cebe** [comment]
when you create a migration you base it on the current state and apply some sql to change that state resulting in a well defined state of the schema again. How could you mess that up?

**Comment by samdark** [comment]
@cebe it could possibly happen if heavy branching is used and merge to branch happens rarely.

**Comment by samdark** [comment]
But I don't see a good way to solve it automatically.

**Comment by cebe** [comment]
if you get another migration from merging branches each of them do not know about each other so you do not have defined any relation between them.

**Comment by samdark** [comment]
Yep.
