### ISSUE TITLE
DataProvider overiding prepareTotalCount() is not playing nice with pagination.

### ISSUE THREAD

**Issue by dmill-bz** [yiisoft/yii2#8143]
Hey guys. I've noticed that when overriding `SqlDataProvider::prepareTotalCount()` the pagination `$totalCount` is not updated correctly. This seems like incorrect behavior. Here's how to reproduce:

Create a custom dataprovider:

``` php
class CustomSqlDataProvider extends SqlDataProvider
{
    protected function prepareTotalCount()
    {
        return 5;
    }
}
```

(The idea behind this is to allow us to use a custom query for counting)
Here's an example of use:

``` php

$dataProvider = new CustomSqlDataProvider([
    'sql' => 'SELECT * FROM user',
    'sort' => [
        'attributes' => [
            'age',
            'name'
        ],
    ],
    'pagination' => [
        'pageSize' => 2,
    ],
]);

echo $dataProvider->pagination->totalCount; // returns 0;
echo $dataProvider->getTotalCount(); // returns 5;
echo $dataProvider->pagination->totalCount; // returns 0
echo $dataProvider->getCount(); // returns 2 (pageSize)
echo $dataProvider->pagination->totalCount; // returns 5
```

As we can see from above, `CustomSqlDataProvider::getCount()` updates `Pagination::$totalCount` properly, but `CustomSqlDataProvider::getTotalCount()` doesn't. This doesn't seem like the proper behavior.

**Comment by jamband** [comment]
@PommeVerte Please try the following code:
```php
$dataProvider = new CustomSqlDataProvider([...]);
$dataProvider->prepare(true); // add this line
echo $dataProvider->pagination->totalCount; // returns 5;
```
Link: [yii\data\BaseDataProvider::prepare()](http://www.yiiframework.com/doc-2.0/yii-data-basedataprovider.html#prepare()-detail)

**Comment by PommeVerte** [comment]
@jamband Thanks for that but it's quite simple to set the totalCount when overriding anyways. I mostly reported this because it felt like it wasn't the expected behavior.

**Comment by jamband** [comment]
> it wasn't the expected behavior

@PommeVerte I agree with you :)
