### ISSUE TITLE
[Enh] Implement ORDER BY CASE in QueryBuilder

### ISSUE THREAD

**Issue by unclead** [yiisoft/yii2#8146]
Sometimes i need to use more complex sorting than `column => direction`
Thats why QueryBuilder doesnt support it i have to do the following

``` php
    /**
     * Sorting by chat status
     *
     * @param $order
     */
    protected function prepareOrderByChatStatus($order)
    {
        $case = [];
        foreach ($order as $i => $status) {
            $case[] = 'WHEN ' . $status . ' THEN ' . ($i + 1);
        }
        $column = '(CASE chat_status ' . implode(' ', $case) . ' END)';
        $this->query->addOrderBy([$column => SORT_ASC]);
    }
```

It would be great to have this feature out of box

Some links from stackoverflow:
- http://stackoverflow.com/a/20097116
- http://stackoverflow.com/a/13339625
- http://stackoverflow.com/a/6427418

**Comment by golovanov** [comment]
There're two syntaxes: **Simple CASE** and **Searched CASE**.

------
### Simple CASE syntax
The simple CASE function compares an expression to a set of simple expressions to determine the result.
```sql
CASE search-expression
    WHEN expression [, expression [ ... ]] THEN
        statements
    [ WHEN expression [, expression [ ... ]] THEN
        statements
    ... ]
    [ ELSE
        statements ]
END
```
The simple form of CASE provides conditional execution based on equality of operands.
The search-expression is evaluated (once) and successively compared to each expression in the WHEN clauses.
If a match is found, then the corresponding statements are executed, and then control passes to the next statement after END CASE.
If no match is found, the ELSE statements are executed; but if ELSE is not present, then must be returned a **NULL** value.

------
### Searched CASE syntax
The searched CASE function evaluates a set of Boolean expressions to determine the result.

```sql
CASE
    WHEN boolean-expression THEN
        statements
    [ WHEN boolean-expression THEN
        statements
    ... ]
    [ ELSE
        statements ]
END
```
The searched form of CASE provides conditional execution based on truth of boolean expressions.
Each WHEN clause's boolean-expression is evaluated in turn, until one is found that yields true.
Then the corresponding statements are executed, and then control passes to the next statement after END CASE.
If no true result is found, the ELSE statements are executed; but if ELSE is not present, then must be returned a **NULL** value.

------
### Reference Manuals:
* MySql: http://dev.mysql.com/doc/refman/5.0/en/case.html
* Postgresql: http://www.postgresql.org/docs/8.4/static/plpgsql-control-structures.html#PLPGSQL-CONDITIONALS
* Oracle: http://docs.oracle.com/cd/B19306_01/server.102/b14200/expressions004.htm
* Microsoft Sql Server: http://msdn.microsoft.com/en-us/library/ms173318.aspx
* Sqlite: http://www.sqlite.org/lang_expr.html

**Comment by dynasource** [comment]
this is quite rare. Please use http://www.yiiframework.com/doc-2.0/yii-db-expression.html for these rare usecases
