### ISSUE TITLE
[Enh] Implement ability to add comment on table and column via migration

### ISSUE THREAD

**Issue by unclead** [yiisoft/yii2#8148]
I think it can be useful have methods for adding comments on table and column
```php
addCommentOnColumn($column, $comment)
addCommentOnTable($table, $comment)
```
I know that i able to achieve this using method `execute()` but it would be great to have this feature out of box

**Comment by nineinchnick** [comment]
I agree, I use comments and manually quoting them for `execute()` is tedious. This could include adding them via `createTable`.

**Comment by dbsparkle** [comment]
`'start_date' => Schema::TYPE_DATE . " NULL COMMENT 'The date contract has been activated'",`

**Comment by samdark** [comment]
That's when you're creating a field. But what if you need to add comment to existing one?

**Comment by unclead** [comment]
@dbsparkle does all databases support this sql style?

**Comment by unclead** [comment]
@samdark it would be nice to be able to pass an array of columns to the method. e.g.
```
$this->addcommentOnColumn('{{%table}}', [
   'column1' => 'comment',
   ...
])
```

**Comment by samdark** [comment]
That should be a separate method in this case called `addComments`

**Comment by unclead** [comment]
@samdark i agreed. I just wrote another one use case
There is my implementation for psql
```php
   /**
     * Добавляет комментарий для столбца таблицы.
     *
     * @param string $table
     * @param string $column
     * @param string $comment
     * @return void
     */
    public function addCommentOnColumn($table, $column, $comment)
    {
        $table = $this->db->quoteTableName($table);
        $column = $this->db->quoteColumnName($column);
        $comment = $this->db->quoteValue($comment);

        $this->execute("COMMENT ON COLUMN $table.$column IS $comment;");
    }

    /**
     * Добавляем комментарии к колонкам таблицы.
     *
     * @param string $table имя таблицы
     * @param array $comments массив в формате колонка - комментарий
     */
    public function addCommentOnColumns($table, $comments)
    {
        if (ArrayHelper::isAssociative($comments)) {
            foreach ($comments as $column => $comment) {
                $this->addCommentOnColumn($table, $column, $comment);
            }
        }
    }
```
but this is only for achieve my own aims and in the yii core it should be more generally

**Comment by dbsparkle** [comment]
@samdark you can do it:

`$this->alterColumn($this->tableName, 'start_date',
                Schema::TYPE_DATE . " NULL COMMENT 'update comment'");`

But I love the idea about having method `addComment()` - kudos!

**Comment by vaseninm** [comment]
Guys, i want try to enhance it. But i am working only with postgresql and i need sql commands or links on documentation for adding and dropping comment on column and table.

**Comment by samdark** [comment]
MySQL was already implemented in https://github.com/yiisoft/yii2/pull/9089.

**Comment by unclead** [comment]
@samdark this issue about implement methods for add comment to existing columns. You gave link to issue about schemaBuilder which use only for creating new table. Or i'm wrong?

**Comment by samdark** [comment]
You've asked about SQL to add comments. It's in that pull request if we're talking about MySQL.

**Comment by unclead** [comment]
@vaseninm 
Mysql: you can find info here http://stackoverflow.com/questions/2162420/alter-mysql-table-to-add-comments-on-columns
Cubrid: it will be something similar because it has similar syntax with mysql
Mssql: http://stackoverflow.com/questions/9018518/how-to-add-a-comment-to-an-existing-table-column-in-sql-server
Oracle: e.g. https://community.oracle.com/message/2627956#2627956

**Comment by vaseninm** [comment]
@samdark @unclead it`s problem with mysql. If we use $this->addCommentOnColumn(), we must know current type to change description.

**Comment by unclead** [comment]
@vaseninm when i worked on #8152 i faced with this problem. You can see my implementation see^ https://github.com/unclead/yii2/blob/8152-extend-migration-class/framework/db/mysql/QueryBuilder.php#L97

I moved some logic in new method `getColumnDefinition` but unfortunally my PR was so dirty and i decided to close it

**Comment by unclead** [comment]
also the similar problem with cubrid. I tried to implement method `getColumnDefinition` for this DB but i dont know it is correct or no. See: https://github.com/unclead/yii2/blob/8152-extend-migration-class/framework/db/cubrid/QueryBuilder.php#L52

but i dont like my implementation. I think it would be great use only one regex for matching column definitions

**Comment by vaseninm** [comment]
@unclead it one extra query for every operation. I think that it good idea. @samdark, what you think?

**Comment by unclead** [comment]
This extra query already used in `renameColumn` method: https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L54
I just moved in to the separate method.

**Comment by vaseninm** [comment]
ok, thank

**Comment by samdark** [comment]
For schema queries it doesn't really matter if it's one query or 10 queries. It happens once in a lifetime.

**Comment by ilyachase** [comment]
Also, Cyrillic symbols in comment won't work for some reason.
What I mean:
'date_created'      => $this->dateTime()->notNull()." COMMENT 'Creation date'", // Will apply

but

'date_created'      => $this->dateTime()->notNull()." COMMENT 'Дата создания заявки'", // Will apply WITHOUT comment

**Comment by SilverFire** [comment]
@ilyachase One problem - one issue. Could you, please, create a separated issue and describe the problem more detailed? What DBMS do you use, what query was generated and what error was returned?

**Comment by ilyachase** [comment]
@SilverFire Seems the problem is no longer relevant. Just did reverted all the migrations and then applied them again. After that comments for columns applied.

**Comment by SilverFire** [comment]
Implemented in https://github.com/yiisoft/yii2/commit/fde8aa6bcbb902aaea10f02f07fa87e11e5d2d17
