### ISSUE TITLE
updateCounters throws yii\base\ErrorException on newly created Active Record instance

### ISSUE THREAD

**Issue by bizley-code** [yiisoft/yii2#8149]
To reproduce create Active Record model with counter column then create new instance of it, save without setting this column's attribute and call updateCounters for the column.

    /**
     * Example model
     *
     * @property integer $id
     * @property string $username
     * @property integer $views counter column
     */
    $model = new Example;
    $model->username = 'test';
    $model->save();

    $model->updateCounters(['views' => 1]);

Column views is incremented by 1 but yii\base\ErrorException is thrown because updateCounters is trying to set: 

    $this->_attributes[$name] += $value;

when ```$this->_attributes[$name]``` is not set. updateCounters now is:

    public function updateCounters($counters)
    {
        if ($this->updateAllCounters($counters, $this->getOldPrimaryKey(true)) > 0) {
            foreach ($counters as $name => $value) {
                $this->_attributes[$name] += $value;
                $this->_oldAttributes[$name] = $this->_attributes[$name];
            }
            return true;
        } else {
            return false;
        }
    }

I would like to propose two solutions:

**1) Updating the attribute only when it's set. This attribute wouldn't be available anyway without reloading the model.**

    public function updateCounters($counters)
    {
        if ($this->updateAllCounters($counters, $this->getOldPrimaryKey(true)) > 0) {
            foreach ($counters as $name => $value) {
                if (isset($this->_attributes[$name])) {
                    $this->_attributes[$name] += $value;
                    $this->_oldAttributes[$name] = $this->_attributes[$name];
                }
            }
            return true;
        } else {
            return false;
        }
    }

**2) Refreshing the whole model after counter update. Additional db query required.**

    public function updateCounters($counters)
    {
        if ($this->updateAllCounters($counters, $this->getOldPrimaryKey(true)) > 0) {
            return $this->refresh();
        } else {
            return false;
        }
    }

**Comment by klimov-paul** [comment]
I don't this should be fixed.
You should manually call `ActiveRecord::refresh()` before attempting to update its counters.

It could be, for example, that you have a 'DEFAULT' value set on your 'views' column, which sets it to 1 for new record. This will not apply automatically after you call `save()` too.

As you have noticed the only way to aviod such problems is refreshing Active Record instance automatically at some point, which costs extra query to be performed, while in common situation it is not needed.

It is actually rather strange that you insert new row and then(!) update a counter for it inside the single program flow. It is better to calculate and set your 'views' value before inserting the row.

**Comment by bizley-code** [comment]
I understand but I still think this should be addressed - every other attempt to modify ```$this->_attributes[$name]``` checks if it's set first.

**Comment by klimov-paul** [comment]
Resolved by commit 6d96d3c

**Comment by bizley-code** [comment]
Thank you for this fast action but the fix will set the wrong attribute value (until reloading) in case the default db column value is bigger than 0

**Comment by cebe** [comment]
I think a comment should be added to the method.
