### ISSUE TITLE
Exception 'yii\db\Exception'

### ISSUE THREAD

**Issue by irfan03** [yiisoft/yii2#8150]
my application working fine, but when i try to execute action of console folder using terminal like - [root@prodbam abc]# php yii mail/schedule-mail
it throws exception - Exception 'yii\db\Exception' with message 'could not find driver'
in /var/www/html/abc/vendor/yiisoft/yii2/db/Connection.php:534

in my application frontend and backend both are working fine.
plz help.

**Comment by klimov-paul** [comment]
Most probably you have different php.ini for web and console PHP mode.

**Comment by irfan03** [comment]
thanks
