### ISSUE TITLE
REST API with 2 controllers extra patterns fail. 

### ISSUE THREAD

**Issue by rrhyne** [yiisoft/yii2#8153]
I have 2 controllers in my API. Each has extra patterns defined. All of my actions work properly except the user login, which is defined in extra patterns.

``` php
    <?
    'urlManager' => [
        'enablePrettyUrl' => true,
        'enableStrictParsing' => true,
        'showScriptName' => false,
        'rules' => [
            [
                'class' => 'yii\rest\UrlRule',
                'controller' => [ 'v1/item', 'v1/user'], 
                'tokens' => [
                    '{id}' => '<id:\\w+>', //commenting out this token allows login to return
                    '{type}'=>'<type:\\w+>'
                ],
                'extraPatterns' => [
                    'POST {id}/image/{type}' => 'image', //from the item controller
                    'GET login' => 'login' // from the USER controller
                ]
            ]

        ],
    ],
```

user/login errors as so. Note it's looking for the v1/user/view action

``` javascript
     {
        "name": "Not Found",
        "message": "Page not found.",
        "code": 0,
        "status": 404,
        "type": "yii\\web\\NotFoundHttpException",
        "previous": {
            "name": "Invalid Route",
            "message": "Unable to resolve the request: v1/user/view",
            "code": 0,
            "type": "yii\\base\\InvalidRouteException"
        }
    }
```

If I comment out the ID token in the urlManager, the user/login action works, but my other routes fail.

Additionally, shouldn't the extraPatterns be associated with their respective controllers?  ow does Yii know the login pattern belongs with the user controller?

**Comment by rrhyne** [comment]
Of course I solved it moments after posting by creating a separate URL rule for each controller. 

The documentation is a bit confusion where takes the shortcut of defining several controllers in a single array. That works for the standard actions, but once you start extending, you need to separate into a rule for each.

**Comment by philippfrenzel** [comment]
would you mind posting a sample, need it too? Thx

**Comment by anilkonsal** [comment]
This happened to me as well and the cause I found was 'token' and 'extraParameters' cannot be grouped in one array, so I needed to make two arrays. Here is mine code:

    [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'v1/user',
                    'pluralize' => false,
                    'extraPatterns' => [
                        'GET search' => 'search',
                        'POST signup' => 'signup',
                        'POST signin' => 'signin',
                        'POST forgot-password' => 'forgot-password',
                        'GET,POST settings/<id:\d+>' => 'settings',
                        'DELETE logout/<id:\d+>' => 'logout',
                        'PUT,PATCH change-password/<id:\d+>' => 'change-password'
                    ],
                ],
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'v1/user',
                    'only' => ['signup', 'signin', 'logout', 'forgot-password','settings'],
                    'pluralize' => false,
                    'tokens' => ['{id}' => '<id:\\w+>'],
                ],

**Comment by qiangxue** [comment]
Are you using the latest code?

**Comment by anilkonsal** [comment]
Yes, latest code.

**Comment by Agrumas** [comment]
https://github.com/yiisoft/yii2/commit/631d0ffb664aacf4d5c29b4f2c1123fc1428bc29 patch was intended to fix such issue. Maybe you are using stable version... Could you provide commit hash (reference) of version you are using? composer.lock file contains it, just search for ```https://github.com/yiisoft/yii2-framework.git```

**Comment by cebe** [comment]
`composer show -i` will show it too.

**Comment by Sitronik** [comment]
I have same trouble. But I fixed it.
This code dosen't work: 

`                  [    
            
                    'class'         => 'yii\rest\UrlRule',
                    'controller'    => 'v1/comments',
                    'pluralize'     => false,
                    'extraPatterns' => [
                        'GET {translit}' => 'view-translit',
                        'GET moderation' => 'moderation',
                    ],
                    'tokens'        => [
                        '{id}'  => '<id:\d+>',
                        '{translit}' => '<translit:[a-zA-Z0-9\\-]+>',
                    ],
                ],`

If I try get v1/comments/moderation

`{

            "success": false,
             "status": 404,
             "data": {
             "name": "Not Found",
             "message": "Object not found: moderation",
             "code": 0,
             "status": 404,
            "type": "yii\\web\\NotFoundHttpException"
        }
 }` 

So I changed line ''GET moderation' => 'moderation'," position as below:

`[
                   
                    'class'         => 'yii\rest\UrlRule',
                    'controller'    => 'v1/comments',
                    'pluralize'     => false,
                    'extraPatterns' => [
                        'GET moderation' => 'moderation',
                        'GET {translit}' => 'view-translit',
                    ],
                    'tokens'        => [
                        '{id}'  => '<id:\d+>',
                        '{translit}' => '<translit:[a-zA-Z0-9\\-]+>',
                    ],
                ],`

And this works for me.

**Comment by Faryshta** [comment]
related #13968

**Comment by vishnudutttest** [comment]
facing same problem. Please find the issue
