### ISSUE TITLE
Yii2 load balancers and assets

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2#8154]
Hi,

I'm currently trying to develop using Yii2 for an application which is load balanced across x amount of servers.
On the most part this works great but I am running into issues with the global assets (Yii, Bootstrap, etc).

On each server it creates the folders required as expected but because the files are copied to each server one at a time the filemtime on each server is different resulting in different folder hashes.

Is there a way I can override the folder destination to be something like @webroot/assets/bootstrap and @webroot/assets/yii instead of @webroot/assets/##HASH##?
Alternatively, have I been looking at this problem from the wrong angle?
Is there another way to get round this problem?

I have been spending far too long looking through the documentation to try and find a way to achieve this.

Thanks in advance.

**Comment by samdark** [comment]
There's another way for sure: https://github.com/samdark/yii2-cookbook/blob/master/book/structure-asset-processing-with-grunt.md

**Comment by klimov-paul** [comment]
Duplicates #7441

**Comment by garyrutland** [comment]
That definitely looks like it is along the right lines of what I want to do.

The documentation you provided isn't very clear on how to use custom assets though which extend the AssetBundle class.
More specifically, dealing with requests that have css/js that only apply to them and are not global.

Also, the example given didn't seem to actually include the bootstrap.less file.
Tried a few different variations but something isn't quite working as expected.

Is there any other documentation about that might help me?

**Comment by samdark** [comment]
If you're using grunt, forget about AssetBundles...

**Comment by garyrutland** [comment]
Ok, I thought as much.
So what is the alternative for that then?
Is there even an alternative, or do I have to re-think things to allow for global everything?

**Comment by garyrutland** [comment]
So yii\web\View::registerJsFile() or yii\web\View::registerCssFile()?

**Comment by samdark** [comment]
Nope. Not even these.

**Comment by samdark** [comment]
You're configuring grunt once and it handles everything for you.

**Comment by samdark** [comment]
W/o Yii.

**Comment by garyrutland** [comment]
Ok, I guess I need to figure out the workings of Grunt then.
Thanks.

**Comment by samdark** [comment]
Yep. There's more popular solution nowadays called gulp with works the same way but I haven't worked with it yet so can't provide any detailed recipe,

**Comment by eric-tucker** [comment]
Am I reading this correctly?  The only solution is to generate the assets in advance via Grunt or some other build tool?

Why is there not simply an option exposed to ensure that the generated folder structure under /web/assets is the same regardless of where the server runs?

This seems like a HUGE oversight for the Yii team to omit - deploying to a load balanced environment where any server can handle any request from any client.

**Comment by samdark** [comment]
No. Check 2.0.6 release notes. There's now an ability to generate custom hashes which could be made static if needed.

**Comment by eric-tucker** [comment]
I found the release notes.  Can you provide an example?  We have about 8 directories so how do we control the names for each to be static across all servers?

**Comment by samdark** [comment]
There's an example exactly of that.

**Comment by eric-tucker** [comment]
Ahh so the example is actually an example of modifying it.  I found the documentation here:

http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#$hashCallback-detail

By default I see now it uses something based on modified time of the file which explains why we're seeing different paths on our two web servers.  Simply returning a hash of the path (like in the example/docs) should return the same value on both web servers then, correct?

**Comment by samdark** [comment]
Yes.

**Comment by Tomino2112** [comment]
AM I doing this right? I have this in my config:

```
    'assetManager' => [
            'class' => 'yii\web\AssetManager',
            'bundles' => [
                'hashCallback' => function ($path) {
                    return hash('md4', $path);
                }
            ]
        ],
```

But see no effect. Whatever I try to put in the callback function has no effect at all.

**Comment by samdark** [comment]
No. Move hashCallback out of bundles. It's assetManager property.

**Comment by Tomino2112** [comment]
Thanks,

This bit in documentation

```
'assetManager' => [
    'bundles' => [
        // you can override AssetBundle configs here
    ],
]
```

really isn't clear...
