### ISSUE TITLE
Need ability to provide sorting of data in default IndexAction when using REST Controllers

### ISSUE THREAD

**Issue by anilkonsal** [yiisoft/yii2#8155]
Hi,

I have been developing RESTful APIs on Yii2 for Mobile Apps. Almost all the times users have a requirement that the last entry of any CRUD should be shown on Top in list i.e list should be fetched in descending order. I realize that currently there is no option in Yii2 REST to specify the sorting (field and order) for index action.

So the rest request will be like:

    http://api.domain.com/event?sort_field=id&sort_order=desc

Can you please accept this request to incorporate in next release?

Anil

**Comment by mdmunir** [comment]
`http://api.domain.com/event?sort=-id` ?

**Comment by qiangxue** [comment]
You should configure `IndexAction::prepareDataProvider` to return an active data provider which specifies what fields can be sorted.

**Comment by anilkonsal** [comment]
I needed to overwrite the inbuilt IndexAction for each of my Controllers.

    public function actionIndex() {
        return new ActiveDataProvider([
            'query' => Event::find(),
            'sort'  =>  [
                'defaultOrder'  =>  [
                    'id'    =>  SORT_DESC
                ]
            ]
        ]);
    }

But Can you explain a bit more how can I configure IndexAction::prepareDataProvider?

**Comment by anilkonsal** [comment]
Ok, I figured it out. The code is to be used like:

    public function actions() {
        $actions = parent::actions();
        $actions['index']['prepareDataProvider'] = function () {
            return new ActiveDataProvider([
                'query' => Event::find(),
                'sort'  =>  [
                    'defaultOrder'  =>  [
                        'id'    =>  SORT_DESC
                    ]
                ]
            ]);
        };
      return $actions;
    }

Thanks @qiangxue!
