### ISSUE TITLE
Validator isEmpty() is inconsistent

### ISSUE THREAD

**Issue by llfm** [yiisoft/yii2#8157]
#### From Validator.php

> A value is considered empty if it is null, an empty array, or the trimmed result is an empty string.
> ...
> return $value === null || $value === [] || $value === ''';

#### The trim

The `$value` isn't trimmed, should it be simple `trim($value) === ''` or like the [old](https://github.com/yiisoft/yii2/commit/b51c3bc77c86e9e4617b5093d8e4e4c0f2f02d44#diff-d09779f106252613703461c476a629b5R253) implementation (or even not trimmed at all):
```php
return $value === null || $value === array() || $value === '' || $trim && is_scalar($value) && trim($value) === '';
```

**Comment by klimov-paul** [comment]
Trimming of the value is handled by `FilterValidator` and should be applied manually if it is needed.
But I admint that docs are incorrect.

**Comment by klimov-paul** [comment]
Resolved by 4672a8c

**Comment by llfm** [comment]
Ok, but...

The only "problem" that I see is that if the attribute is a CHAR, an extra rule to trim will be needed always (if you want the "default" behavior).

**Comment by cebe** [comment]
you can adjust isEmpty behavior by setting $isEmpty property of the validator.
