### ISSUE TITLE
How do I create activerecord field through relational model (Yii2)

### ISSUE THREAD

**Issue by mhashimmaqbool** [yiisoft/yii2#8160]
I have a class 'Question'. It has hasMany relation with 'Answer' class

class Question 
{
     public function getAnswer()
    {
        return $this->hasMany(Answer::className(), ['question_id' => 'id']);
    }
}

in my _form.php file if I use the 'Answer' model attribute through 'Question' model:
<?= $form->field($model, 'answer.answer1', [
            'addon' => ['prepend' => ['content'=>'<input type="radio" name="Question[correct]">']]
  ]); ?>

OR

<?= $form->field($model->answer, 'answer1', [
            'addon' => ['prepend' => ['content'=>'<input type="radio" name="Question[correct]">']]
  ]); ?>

it displays following error:
Call to a member function formName() on array

Please suggest where I'm doing mistake.

Thanks

**Comment by cebe** [comment]
this is not possible in this way. please use the forum to ask questions, github is for bug tracking.

**Comment by lynicidn** [comment]
getAnswer[b]S[/b]
hasMany
