### ISSUE TITLE
data-method,How does not affect the form

### ISSUE THREAD

**Issue by liyunfang** [yiisoft/yii2#8161]
$form = ActiveForm::begin([
                                //'id' => 'login-form-horizontal', 
                                'options' => ['role'=> "form"],
                            ]); 

                             echo Html::a('delete', ['site/foobar'], [
                                    'data' => [
                                         'method' => 'post',
                                         'confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                         'pjax'=> '0',
                                     ],
                                ]);
                           
In the form, if you use the method and confirm, can automatically validate form. How does not affect the form

**Comment by samdark** [comment]
Can you elaborate?

**Comment by liyunfang** [comment]
![Uploading QQ截图20150423164033.png . . .]()
data-method="post" in the form will automatically validate the form. How does not validate the form submission

**Comment by samdark** [comment]
You don't want to validate form at all?

**Comment by liyunfang** [comment]
Yes, I want to post without affecting the form submission

**Comment by samdark** [comment]
Can you move the button out of the form?

**Comment by liyunfang** [comment]
This is just an example. I use kartik\detail\DetailView, delete button does not change the position of  
 Link:https://github.com/kartik-v/yii2-detail-view/

**Comment by samdark** [comment]
Currently a link with `data-method` acts like a submit button if it's located within a form: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L113. It's intentional behavior.

**Comment by samdark** [comment]
Any suggestions on how it could be solved?

**Comment by Alex-Bond** [comment]
Well, i has similar problem but i fix it like this:
```
$('input[name="PaymentForm[type]"]').change(function () {
                var form = $(this).closest('form');
                form.yiiActiveForm("destroy");
                form.append('<input type="hidden" name="countryUpdate" value="1" />');
                form.submit();
            });
```
Im my case i just need to submit form on change select option. 
In your case you can track click on this link and destroy ActiveForm.

**Comment by liyunfang** [comment]
My advice. I do not know whether it is feasible.
yii.js:
        handleAction: function ($e) {
            var method = $e.data('method'),
                $form = $e.closest('form'),
                action = $e.attr('href'),
                params = $e.data('params'),
                newform = $e.data('newform');     //add data-newform 

            ...
            var newForm = !$form.length || newform;
            if (newForm) {
            ...

**Comment by maxlapko** [comment]
Last changes killed "data-post" functionality. When we put link into the form, the form submits with original action.

**Comment by samdark** [comment]
Shouldn't it?

**Comment by maxlapko** [comment]
@samdark I found these changes https://github.com/yiisoft/yii2/commit/7031020c63f481a84ad23945b88128497cdda0de#diff-f433792b516845f488519deb1a72741a

What reason for these changes?

**Comment by liyunfang** [comment]
@maxlapko  form of internal  data-method="post"   will create a new form

**Comment by maxlapko** [comment]
@liyunfang sure, but now it does not happen

**Comment by liyunfang** [comment]
@maxlapko  To do so,The a tag can't as a submit button?

**Comment by samdark** [comment]
@maxlapko https://github.com/yiisoft/yii2/commit/e224568b49d8fbe024a387e7b9bf6b92ce268533 should not be related.

Reason for https://github.com/yiisoft/yii2/commit/7031020c63f481a84ad23945b88128497cdda0de#diff-f433792b516845f488519deb1a72741a seems to be https://github.com/yiisoft/yii2/issues/6661 but I can't tell for sure, it wasn't done by me.

**Comment by maxlapko** [comment]
@liyunfang yes, now the link has behavior similar with submit button (link.href != form.action), it is not correct

**Comment by liyunfang** [comment]
@maxlapko  Maybe you're right.

**Comment by maxlapko** [comment]
@samdark @qiangxue 
My situation: I have link in error message, it's behavior similar with submit button now. And it is not correct, this link does not depends on form
form.method = post
link.data-method = post
link.href != form.action
![login](https://cloud.githubusercontent.com/assets/495263/7316127/f7f284ac-ea7c-11e4-8699-5a9acbb886db.png)

**Comment by liyunfang** [comment]
@maxlapko  
Temporary solution: In my JS,Override handleAction in yii.js 
if(yii !== undefined && yii.handleAction !== undefined){
   yii.handleAction = function ($e) {
       ...
    };

**Comment by vbelogai** [comment]
The reason for this link's behavior is use of setTimeout() in yii.ActiveForm.js.
When we click on link inside form, yii.js temporary replaces form's action to link's href, triggers submit and then restores original action :

   (yii.js:  handleAction )

            if (action && action != '#') {
                oldAction = $form.attr('action');
                $form.attr('action', action);
            }

            $form.trigger('submit');

            if (oldAction != null) {
                $form.attr('action', oldAction);
            }

But  yii.ActiveForm.js intercepts submit action for validating, where starts actual submit:
   (yii.ActiveForm.js: validate )

                 if (data.submitting) {
                    // delay callback so that the form can be submitted without problem
                    setTimeout(function () {
                        updateInputs($form, messages, submitting);
                    }, 200);

Delayed submit is performed after form's action restoring (to original form's action)

Replacing setTimeout to direct call restore link's functionality (but perhaps breaks something else)

**Comment by vbelogai** [comment]
$.ajax() validation in yii.activeForm.js brings the same problem;
yii.js pattern 

       "set-attribute ; do-action; restore-attribute" 

should not be used with asynchronous actions like setTimeout() or $.ajax()

**Comment by klimov-paul** [comment]
Issue confirmed

**Comment by klimov-paul** [comment]
Proposed solution si #8368

**Comment by DarthLegiON** [comment]
I have the same problem at Yii v2.0.10. Here is my code:
`
<?= $form->field($orderForm, 'acceptOfferta')->checkbox(['label' => 'Принимаю и соглашаюсь с условиями <a href="' . Url::to(['/user/offerta']) . '" target="_blank">публичной оферты</a>'])->label(false) ?>
    <br>
    <?php echo Html::submitButton(Html::mIcon('done') . 'Активировать', ['class' => 'btn btn-success btn-raised']);
    echo Html::a(Html::mIcon('clear') . 'Отмена', ['cancel-order', 'id' => $order->id, 'returnPage' => 'index'], ['class' => 'btn btn-primary', 'data-method' => 'post']);
    ActiveForm::end();
    ?>
`
If I press second link and checkbox is not activated, error appears and link submission is broken. I can disable client validation here, but it is a temporary solution. What you recommend? Was this issue really fixed in 2.0.5 and I'm doing smth wrong, or not?

**Comment by samdark** [comment]
Check code from master. If there's still an error, create new issue describing how to reproduce the problem.

**Comment by auzadventure** [comment]
Yes I confirm that data-method will still trigger client validation. If the a is inside a activeform tag. 

A solution is to avoid data-method and use a simple url link with params 
Html::a('next page',['url','param1'=>x,'params2'=y])
