### ISSUE TITLE
Add context and locations to the documentation

### ISSUE THREAD

**Issue by patlecat** [yiisoft/yii2#8162]
I often noticed that you don't mention where a piece of code should be added or can be found nor under which conditions this is true or wrong. This is a very important part of the docs for anyone except the Yii-Gurus, but then they don't need them ;)

Also can you please add all the options/arguments for any class and widget in the docs? Especially those that go as PHP Arrays, because of lack of IDE support and documentation this information is almost impossible to guess.

**Comment by samdark** [comment]
Any concrete suggestions about adding context info?

As for methods, these are in the API docs: http://www.yiiframework.com/doc-2.0/index.html

**Comment by patlecat** [comment]
I feared you would ask me for this. It's practically everywhere, the list would be huge. Yes the methods of documented classes are there in the reference manual.

Example for location/context: http://www.yiiframework.com/doc-2.0/guide-runtime-sessions-cookies.html

Example for missing PHP Array options/attributes: http://www.yiiframework.com/doc-2.0/yii-bootstrap-navbar.html

**Comment by patlecat** [comment]
Or here lacking location and has no complete code example only snippets which are probably meant for Gurus.
https://github.com/samdark/yii2-cookbook/blob/master/book/cookies.md

**Comment by samdark** [comment]
You could open or close session or work with cookies basically anywhere and most of the time you don't need to. That's why nothing is suggested regarding it. Or do you talk about configs?

http://www.yiiframework.com/doc-2.0/yii-bootstrap-navbar.html seems to be apidoc bug. `items` should be there. @cebe can you check it?

**Comment by patlecat** [comment]
See? Why not add exactly this information to the docs? I have no idea where to put certain calls, so that info is important. And maybe even though you can put them everywhere (really?) there is a place where it should be used for best practice.

Write everything down, don't leave anything to the fantasy of the reader, unless you're writing fiction ;) hehehe

**Comment by samdark** [comment]
As for cookies, yes, you can call it anywhere but if you ask about best practice I would recommend putting it into controller since it's request/response data. Good catch.

Do you have more examples? I'm kinda blind about it and you seem to see such issues clearly.

**Comment by patlecat** [comment]
It's hard, it might take me days to list all the doc pages lacking those things. Can you think of a more efficient way to browse over it?

**Comment by patlecat** [comment]
Maybe you could recruit a couple of technical writers for the project to take care of such things and the docs in general?

**Comment by samdark** [comment]
Yeah, I understand it's hard and I can't force you doing it, of course. Time is pricey.

Do you know any good technical writers who could handle it?

**Comment by patlecat** [comment]
No sorry, don't know anybody. But you have a huge community and lots of visitors on your website, why not advertise it there? I'm sure you'll have a couple of good applicants within days!

**Comment by samdark** [comment]
Cookies recipe in cookbook: https://github.com/samdark/yii2-cookbook/commit/0b05cf54a8ccb5f023d62223c8e0b81a680e1ca5

Cookies in guide: https://github.com/yiisoft/yii2/commit/929d802059bc184cd8c7ec0ad6608c705b9eaa58


Thanks for suggesting it.
