### ISSUE TITLE
HTML:a with data method POST enabled inside ActiveForm submit's wrapping form

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8169]
Here is problematic code 

https://gist.github.com/anonymous/b5adea698d297d8cc8ca

The same code was working on another project. (Maybe problem occurred because of update). The problem is HTML:a with data method POST inside ActiveForm submits wrapping form. After moving tis part out of wrapping form all works.

https://gist.github.com/anonymous/daa2d3bba0ea0f0fe8e6

Question is, why a submits wrapping form?

**Comment by klimov-paul** [comment]
Duplicates #8161
