### ISSUE TITLE
Wrong view rendering on catchAll option

### ISSUE THREAD

**Issue by ajesamson** [yiisoft/yii2#8175]
Whenever catchAll is set in the configuration, default view is rendered twice on the web page.

**Comment by klimov-paul** [comment]
Unable to reproduce

**Comment by cebe** [comment]
could be related to the debug toolbar ajax request, which will then be caught by the catchall request.

**Comment by ajesamson** [comment]
Thanks cebe. You are right. After changing the YII_ENV to production, the duplicate rendering was corrected.
