### ISSUE TITLE
[Proposal] ActiveRecordCollection

### ISSUE THREAD

**Issue by xskif** [yiisoft/yii2#8185]
It would be nice if `ActiveQuery` returns `ActiveRecordCollection` instead of Array. Example:

```php
/* Order has many OrderItems */
/* OrderItems has many Items */
$order->items->add($item);
/*OR*/
$order->items->build($post);

foreach($order->items->each() as $item) { /*do some with collection item*/ }
```

UPD: by customizing  the collection class, developers will have opportunity to create own collection methods

UPD2: we can achive that without breaking compatibility by `asCollection` method in the `ActiveQuery` class. Example:
```php
return $this->hasMany(Product::className(), ['catalog_id' => 'id'])
                  ->asCollection(ActiveRecordCollection $optionalCollectionClassThere);
/* OR */
Product::find()->asCollection()->all();
```

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/data/BaseDataProvider.php#L101

**Comment by xskif** [comment]
@lynicidn
This is not the same.

Collection class can help avoid code like this:
```php
$catalog = Catalog::findOne($catalogId);
$product = new Product;
$product->load($post);
$product->link('catalog', $catalog);
```
instead of:

```php
$catalog = Catalog::findOne($id);
$catalog->products->build($post);
```

like in Rails.

**Comment by Ragazzo** [comment]
https://github.com/yiisoft/yii2/issues/2423

**Comment by mdmunir** [comment]
https://github.com/mdmsoft/yii2-ar-behaviors/blob/master/RelationBehavior.php

```php
$catalog = Catalog::findOne($catalogId);
$catalog->product = $post;
```

**Comment by xskif** [comment]
@mdmunir , it's almost the same but only for one use case - adding new elements.
Collections provide more flexible solution. One more example:

```php
$product->images->deleteAll();
$product->images->buildMultiple($post);
$catalog->products->updateMultiple($post);
$cart->lineItems->remove($lineItemId);
```

it's `Repository Pattern`, not just behavior of `Strategy`.
Also we can use ArrayAccess with collections.

@Ragazzo thx, but this is not really the same proposal.

I'm still waiting for @qiangxue or @samdark to discuss.

**Comment by Sammaye** [comment]
What would be the benefits?

**Comment by xskif** [comment]
@Sammaye
I'm already provide examples.
Purpose is to encapsulate relations inside of domain logic and provide simpler the relations interaction interface.
Also this can help with database interaction, improve speed of application, and show how to do right.

**Comment by xskif** [comment]
> Just the ability to add multiple functions? Most of this is handled by DB queries that are custom to the PHP logic

No, look at Rails.

**Comment by mdmunir** [comment]
```php
// delete all items
$order->items = [];

// build multiple
$order->items = [$item1, $item2, $item3];

// add new item
$items = $order->items;
$items[] = $item4;
$order->items = $items;

// remove 1 item
$items = $order->items;
unset($items[1]);
$order->items = $items;
```

**Comment by xskif** [comment]
@mdmunir thx for examples, but i still can't add some custom logic, because this is not OOP. Also i can't incapsulate logic.

**Comment by samdark** [comment]
Closing since there's #10806 w/ active discussion.
