### ISSUE TITLE
AssetManager appendTimestamp, working as intended?

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#8190]
I am using `appendTimestamp` of `assetManager` component

    'assetManager' => [
        //append time stamps to assets for cache busting
        'appendTimestamp' => true,
    ],
    'cache' => [
        'class' => 'yii\caching\FileCache',
    ],
It correctly adds the timestamp after each asset as shown: <link href="/frontend/web/assets/7b3fec74/css/arabic.css?v=1428761706" rel="stylesheet">

However when I make changes to that CSS file, the timestamp does not update. Is this because of the FileCache?

Every time I wish to test my new changes, I currently need to clear the contents of my web/assets folder

Am I required to delete the contents of the assets folder every time I wish to test my new assets?

**Comment by xskif** [comment]
Do you have the following code in the web/index.php file?

```php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```

**Comment by BAWES** [comment]
Hello @xskif , I do have that on top of the file.
Is there any PHP extension or configuration required for this to work?

**Comment by xskif** [comment]
> Is there any PHP extension or configuration required for this to work?

No, it's core functionality.

**Comment by cebe** [comment]
@BAWES which operating system are you using and what is the filesystem of the disk you store your files on?

**Comment by BAWES** [comment]
@cebe I'm using latest update of Yosemite on iMac 5K and a Macbook Pro. Format: Mac OS Extended (Journaled)

**Comment by SilverFire** [comment]
Failed to reproduce

**Comment by 13DaGGeR** [comment]
To those who have same trouble:
Make sure paths in asset bundle don't start with '/':
**WRONG**:
```
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        '/css/style.min.css',
    ];
    public $js = [
        '/js/scripts.min.js',
    ];
}
```
**RIGHT**:
```
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/style.min.css',
    ];
    public $js = [
        'js/scripts.min.js',
    ];
}
```
