### ISSUE TITLE
How to get absolute base url?

### ISSUE THREAD

**Issue by maykinayki** [yiisoft/yii2#8193]
I have a file in frontend/web/uploads/filename.ext. I want to create an absolute download url for this file. I Only can do it by relative url

**Comment by mdmunir** [comment]
`Url::to($route,true)`

Use yii forum for asking.

**Comment by klimov-paul** [comment]
@maykinayki, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
