### ISSUE TITLE
Suggest add setBehaviors method in yii\base\Component.

### ISSUE THREAD

**Issue by netyum** [yiisoft/yii2#8195]
在1.x中我可以通过配置文件，设置组件的行为。在2.x中设置不了，因为在
yii\base\Component中，只有getBehaviors,并没有对应的setBehaviors
而behaviors属性的描述，说要在子类继承！在如果我动态通过配置。

如果我在设置一个application的before request事件，我还是在new出apllication后，用attachBehaviors或attachBehavior附加行为，（我现在看只有web/index.php中加，并没有更好的一个点，来加入这行代码），如果我能在配置文件中用behaviors => []直接配置，是不是会更优雅些。

**Comment by netyum** [comment]
Suggest add setBehaviors method in yii\base\Component.

In 1.x, I can lead a configuration file to load a set of behaviors.
But in 2.x, I do not!

For example, I want to yii\base\Application::EVENT_BEFORE_REQUEST attach behavior, I think it can only increase the current in the web/index.php in

```php

namespace backend\behaviors;

use Yii;
use yii\base\Behavior;
use yii\base\Application;

/**
 * Class ApplicationBehavior
 * @package backend\behaviors
 * @author Song Yeung <netyum@163.com>
 * @date 4/26/15
 */
class ApplicationBehavior extends Behavior
{

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
    }

    public function events()
    {
        return [
            Application::EVENT_BEFORE_REQUEST => 'beforeRequest',
            Application::EVENT_AFTER_REQUEST => 'afterRequest'
        ];
    }

    public function beforeRequest($event)
    {

    }

    public function afterRequest($event)
    {

    }
 }
```

and use the ApplicationBehavior in index.php

```php
...

$application = new yii\web\Application($config);
$application->attachBehaviors([
    'application' => [
        'class' => 'backend\behaviors\ApplicationBehavior'
    ]
]);
$application->run();
```

or extends application was MyApplication

But i think this code is not elegant and should not have a better place to put this line of code, right?

If I can use behaviors in the configuration file, it will be better.

e.g. main.php

```php
return [
    'id' => 'app-backend',
    ...
    'modules' => [
        ...
    ],
    'behaviors' => [
        'application' => [
            'class' => 'backend\behaviors\ApplicationBehavior',
        ]
    ],
    'components' => [
        ...
```

Of course, not limited to this use, in short, can not find a suitable location to write behavior, but you do not want to inherit, so to use it

**Comment by mdmunir** [comment]
repost https://github.com/yiisoft/yii2/issues/157

**Comment by netyum** [comment]
Thanks ，
```php
    'as application' => [
        'class' => 'backend\behaviors\ApplicationBehavior',
    ],
```

If there is more than one, I feel very long-winded. But generally attach a behavior.

**Comment by cebe** [comment]
here is the documentation about it: http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html#configuration-format
