### ISSUE TITLE
Provide a handy method to render block in the view, which would replace a repetitive if (isset($var)) check

### ISSUE THREAD

**Issue by dbsparkle** [yiisoft/yii2#8199]
It would be nice to have a convenient way to nest the blocks (render child block in the parent if child exists) in the views, maybe something like `renderBlock()`

```
<?php $this->beginBlock('blockChild'); ?>

...content of blockChild...

 $this->endBlock(); ?>

...

 $this->beginBlock('blockParent'); ?>

...content of blockParent...

 $this->endBlock(); ?>

<?php $this->beginBlock('blockChild') ?>
// blablabla
<?= $this->renderBlock('blockParent') ?>
// some more blablabla
<?php $this->endBlock() ?>
```

Otherwise now you have to do something like:
`<?= isset($this->blocks['blockName']) ? $this->blocks['blockName'] : null; ?>`

Which may get waay too confusing, if you have more than four blocks in the view (especially for beginners, frontend or designers).

I am not sure if `renderBlock` is a right name, but I am talking about a method
which would do the check logic part:

```
if (isset($var)) {
    return $var;
} else { 
    return null;
}
```

Ref: http://www.yiiframework.com/doc-2.0/guide-structure-views.html#using-blocks

**Comment by samdark** [comment]
I like the idea. Do you have more ideas for the name?

**Comment by dbsparkle** [comment]
`nestBlock()` maybe?

**Comment by samdark** [comment]
To make it clear, do you propose an alternative for the following?

```php
<?php $this->beginBlock('block1'); ?>
    <?php if (isset($this->blocks['block1'])): ?>
        <?= $this->blocks['block1'] ?>
    <?php else: ?>
        ... default content for block1 ...
    <?php endif; ?>
<?php $this->endBlock(); ?>
```

That is:

```php
<?php $this->beginBlock('block1') ?>
    <?= $this->renderBlock('block1') ?>
    ... default content for block1 ...
<?php $this->endBlock() ?>
```

Correct?

**Comment by klimov-paul** [comment]
I don't understand how this is "a convenient way to nest the blocks'?
I am unsure that avoiding conditions `isset($this->blocks['blockName'])` actually make sense.
Here is a common example of block usage:
```php
<?php if (isset($this->blocks['block1'])): ?>
    <?= $this->blocks['block1'] ?>
<?php else: ?>
    ... default content for block1 ...
<?php endif; ?>
```
The sugnificant thing here is defiing fallback content for the case block is missing.

`renderBlock()` eliminates such ability.

**Comment by klimov-paul** [comment]
And such construction suppose to eliminate the developer confusion?
```
<?php $this->beginBlock('block1') ?>
    <?= $this->renderBlock('block1') ?>
    ... default content for block1 ...
<?php $this->endBlock() ?>
```
I doubt it will.

**Comment by samdark** [comment]
Yeah, thinking a bit more about it, it doesn't really make the concept less complex.

**Comment by dbsparkle** [comment]
@klimov-paul I guess you mean this: 
```
<?php $this->beginBlock('block2') ?>
    <?= $this->renderBlock('block1') ?>
    ... default content for block1 ...
<?php $this->endBlock() ?>
```

And yeah, I admit, my example is a bad one. 
There are two problems I am trying to solve and I guess they should be tackled separately:

1) How to nest multiple blocks? (let's say block1 goes into block2 which goes into block3)
2) How to simplify if...isset part and provide a simple way to output main and alternative contents.

Because doing it the way we do it now is not easy.

I mean there should be something similar to twig approach:
http://twig.sensiolabs.org/doc/tags/extends.html

**Comment by klimov-paul** [comment]
> 1) How to nest multiple blocks? (let's say block1 goes into block2 which goes into block3)

I can't see any problem here.
Note: there is no need to perform `if (isset($this->blocks['block1']))` checks if you are sure 'block1' always exists.
There is no way to automate block nesting: you still have to choose the place for actual outut of the nested block:
```php
$this->beginBlock('nested'); ?>
...content of nested...
 $this->endBlock(); ?>

<?php $this->beginBlock('main') ?>
// blablabla
<?= $this->blocks['nested'] ?>
// some more blablabla
<?php $this->endBlock() ?>
```

> 2) How to simplify if...isset part and provide a simple way to output main and alternative contents.

I can't see any good way.
We can of course provide method with signature like:
```php
class View
{
    public function renderBlock($name, $defaultContent = '') {}
}
```
But its usage will be a pain if your default content is a complex HTML or even block, which should be composed by some PHP involved logic.

I can't see any convincing arguments here.
