### ISSUE TITLE
ActiveRecord findAll() without condition

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#8200]
Sometimes we need to find all models of certain ActiveRecord (order is not important) and for example do something with them with the loop.

`Post::findAll()` - why condition is required?

I think `Post::findAll()` call should be shortcut to `Post::find()->all()` without specifying condition, order and other parts of the query.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/8144

**Comment by arogachev** [comment]
Didn't see that, but I think it's logical to set `$condition = null` in parameter and add if it's null - don't apply condition.

**Comment by samdark** [comment]
It'd done intentionally because usually find all w/o condition is a mistake.

**Comment by cebe** [comment]
duplicate of #6780

**Comment by arogachev** [comment]
Could you explain why it's mistake? If I just have a small set of data and want to use it in loop regardless of condition, order, etc.

**Comment by samdark** [comment]
I said "usually". In the case you really want it you can do it via `find()->all()`.

**Comment by arogachev** [comment]
So you are against of modifying shortcut. OK, I will use `find()->all()` as used it before.

**Comment by cebe** [comment]
as #6780 is still open we are considering to allow this. this issue is closed as a duplicate.

**Comment by arogachev** [comment]
OK, thanks for explanation.
