### ISSUE TITLE
Reload only Gridview on delete action when gridview loaded inside ExpandRowColumn

### ISSUE THREAD

**Issue by maheshtc** [yiisoft/yii2#8201]
I am using kartik\grid\GridView and kartik\grid\ExpandRowColumn. Inside ExpandRowColumn, another Gridview is loaded.  

On Delete of row from inner grid, inner grid need to be reloaded, not whole grid.
How to do this? Please help to resolve issue

I am trying to reload gridview using following.
$.pjax({container: '#addon-grid-<?= $model->wp_section_id?>'});
but it reloads main grid also. That should not be happened.

**Comment by klimov-paul** [comment]
Report this to the extension repository, you are using.
