### ISSUE TITLE
Rule with more that 1 defaults

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2#8208]
Hi -

Not sure if this is the expected behavior but I think this is an issue.

Let's say I have the following rule in my main.php 

```php
               [
                'pattern' => '<language>/<slug>',
                'route' => 'site/index',
                'defaults' => ['language'=>'en', 'slug'=>'index']
                ],
```

Now if I use the URL::to to generate an URL

```php 
URL::to(['site/index', 'language' => 'en', 'slug' => 'test']]) ?>
```

I get 
```html
http://<domain.com>/test 
```
instead of 
```html
http://<domain.com>/en/test
```
because en is the default language. The problem is it is causing issue with my controller when I try to get the parameters. 
I checked in YII debugger and I see that it is calling the correct route site/index with language = test and slug = ''

As a workaround I have duplicated the rule and put it before this one without the defaults

--Matt

**Comment by alexandernst** [comment]
+1

**Comment by klimov-paul** [comment]
This is expected behavior. Default parameters with default values are stripped from URL. If you with them always to be present, you should not use `defaults`.

**Comment by alexandernst** [comment]
I'm not sure stripping parameters is a good idea. Having a default ones and then seeing them when forming URLs is precisely what one would expect. @klimov-paul

**Comment by klimov-paul** [comment]
Such "expectation" ruins the SEO: it will produce 2 different URLs pointing to the same page.

**Comment by alexandernst** [comment]
@klimov-paul `example.com/test` and `example.com/en/test` are to completely different pages. Even further, Google's bot actually understands language params in URLs and uses them when searching.

On the other hand, `URL::to` should respect the order of parameters, so there won't be any situation in which you'll end up with `example.com/test/en` instead of `example.com/en/test`.

**Comment by MattDalm** [comment]
@klimov-paul question is, how can I have ```URL::to``` generate this hyperlink then ```http://<domain.com>/en/test ```
