### ISSUE TITLE
Multiple patterns in a url rule

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#8209]
Currently I have a url that looks like this: [http://site.com/public/123456/123456/slug-slug-slug-slug](http://site.com/public/123456/123456/slug-slug-slug-slug). I'm able to remove the controller from the url, which leaves me with this: [http://site.com/123456/123456/slug-slug-slug-slug](http://site.com/123456/123456/slug-slug-slug-slug).

If I want to match both urls to one single action, I must create the following rules:

```
[
    'pattern' => 'public/<category_id:\d{6}>/<product_id:\d{6}>/<slug:.*?$>/',
    'route' => 'public/product',
    'defaults' => [
        'seo_url' => ''
    ]
],
[
    'pattern' => '<category_id:\w{6}>/<product_id:\w{6}>/<slug:.*?$>/',
    'route' => 'public/product',
    'defaults' => [
        'seo_url' => ''
    ]
]
```

If there was a way to add more than 1 pattern per rule, I'd be able to write this:

```
[
    'pattern' => [
        '<category_id:\w{6}>/<product_id:\w{6}>/<slug:.*?$>/',
        'public/<category_id:\d{6}>/<product_id:\d{6}>/<slug:.*?$>/'
    ],
    'route' => 'public/product',
    'defaults' => [
        'seo_url' => ''
    ]
]
```

which extremely reduces the amount of code required to  match urls and improves readability.

**Comment by samdark** [comment]
```php
[
    'pattern' => '(?:public/)?<category_id:\d{6}>/<product_id:\d{6}>/<slug:.*?$>/',
    'route' => 'public/product',
    'defaults' => [
        'seo_url' => ''
    ]
],
```

**Comment by alexandernst** [comment]
@samdark  My example was, well, just an example. I can think about something more complex that would require a huge regex with a `|` in the middle, if you want me to.

**Comment by alexandernst** [comment]
@samdark Also, that doesn't work (just tried it).

**Comment by samdark** [comment]
Which rule do you expect to be used when forming URLs?

**Comment by alexandernst** [comment]
I'd expect Yii to try to match the current request with each element from the array `pattern` of each rule, and if a match is found, go to that rule's `route`.

**Comment by alexandernst** [comment]
Ah, I see your question. Indeed... haven't thought about that one.

**Comment by alexandernst** [comment]
I'd ask another question. In your previous example (maybe-matching a group), how would that form a URL? Will it use the ignored group part? What if I have a few ignored groups? Will it used them or ignore them?

Anyways, regardless the amount of items in the `pattern` array, the `Url::to()` should just pick the first one and form a URL with that one, as all items will, by all means, point to the same action. So, imho, a good approach would be to allow an array instead of a string for `pattern` and make it clear in the docs that if an array is used, the first item from the array will be used for URL forming. 

What do you think @samdark ?

**Comment by samdark** [comment]
My example was wrong. It won't work as you've already found out. It won't be able to form URL exactly because it's not clear how to. That's why currently 2 rules are required.

**Comment by alexandernst** [comment]
Yeah, that is why I suggested having an array with patterns and make the url forming pick the first one. It's not a bad idea imho, as having multiple rules for the same action will do pretty much the same, aka, it will pick the first rule and use it. @samdark

**Comment by samdark** [comment]
So functionality-wise it will be the same except syntax. Need to think about it.

**Comment by alexandernst** [comment]
Even the syntax would be the same as pattern could be either a string or an
array.

**Comment by samdark** [comment]
So the benefit is not repeating route part. Hmm...
