### ISSUE TITLE
Via relation issue

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#8210]
Is there way to define relation via other 'via' relation?

**Comment by cebe** [comment]
yes, just as you do with normal relations.

**Comment by usualdesigner** [comment]
And the same for 'viaTable' ? I'll try to describe my issue below:

I have next models:

```php
class Product extends \yii\db\ActiveRecord
{
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
}
```

```php
class User extends \yii\db\ActiveRecord
{
    public function getShop()
    {
        return $this->hasOne(Shop::className(), ['shop_id' => 'shop_id'])
            ->viaTable('{{%shop_users}}', ['user_id' => 'id']);
    }
}
```

I need to define 'getShop()' in the Product model. It should works via User relation. For now I implement it like that:
```php
class Product extends \yii\db\ActiveRecord
{
    public function getShop()
    {
        return Shop::find(ArrayHelper::getColumn($this->getUser()->one(), 'id'));
    }
}
```

and it works fine, but I want to implement it as relation.

**Comment by cebe** [comment]
can you show the tables you have or show ERR diagram? I do not see the logical structure from the model.

**Comment by usualdesigner** [comment]
Not actual for now. This was my mistake in relation's link.
