### ISSUE TITLE
Code could be more simpler and looking pretty

### ISSUE THREAD

**Issue by sohelamin** [yiisoft/yii2#8211]
Since, I like yii framework very much for it's powerful features especially CRUD generator and security concern I would like to to make it more popular.
Laravel is popular only for simplicity or developer choice. In Yii2 there could be made code more simple codes even than laravel to make a better position.

**Comment by cebe** [comment]
what do you mean with more simple code? can you give examples?
Laravel is mainly popular because of good marketing. We are working on a new website to keep up on this side.

**Comment by sohelamin** [comment]
Yes I agree with you that laravel do marketing.
But if you could minimize the code on later version that will be great for us.
I don't against yii. I just said that it could be more simpler.
As a Yii family member or fan few things I can suggest for now.

1. Documentation could be on a better looking interface so anyone will should like to reading the codes.
2. Need to minimize the comments on code so it look smaller lines of code and looking code.
3. Can be smaller command to install the yii. eg: composer create-project yii/yii2 
4. Easy define route instead of url manager for every route.
5. Can be put every configuration in a small single line without a large array.
6. Post array can be simpler Yii::$app->request->post() like Request::input();
And much more. It's enough for now can't remember all.
My main idea will be if you releasing next version then do a better documentation interface with better looking font and keep little amount of comments.
Hope Yii2 will rock soon among all php framework.
Best wishes for Yii from me.

Thanks Cebe

**Comment by mdmunir** [comment]
1. No comment. I never read doc :D.
2. Comment block is used for IDE intelegent. I dont need to go out IDE if i want to know about property or method.
3. Yii has 2 type application (3 if you count in app-benchmark). Laravel only has 1.
4. 
    - In Yii, route is optional.
    - What which more easy for you?
    ```php
    Route::request('page/{view}','SiteController@page');
vs
    [
        'page/<view:\w+>' => 'site/page',
    ]
    ```
5. .
6. `Facade` is good concept. I give :+1: for this. But he come with a big trouble for it. no IDE intelegent.
If i type `Route::`, there are no autocompletion what come after it.

.

PS: For point no. 6. If we can attach method to `Yii` it must be cool fiture.
```php
Yii::attachMethod('input',function(){
    return Yii::$app->request->post();
});

var_dump(Yii::input());
```
Sory for rip english.

**Comment by TerraSkye** [comment]
3. realy? u think 1 line of code you only use @the start of a new project is a big of a deal? u can create your own batch script for it.
4. i like the composition of the Yii routes vs laravel. its easy to understand. and u have it all together vs all the places laraval can have it routes placed.
6. can be done trough behaviors. or traits and u can do this yourself. by extending current classes. (it just requires a different config on your part.

**Comment by sohelamin** [comment]
Thank you both @mdmunir  @TerraSkye  for nice explanation.
I did not tell to do to it must. I just shared my idea or suggestion. 
If I need to reconfigure it in my own way then I think there also many developer should have to do this for their simplicity. But if yii do it or a better simple codes or configuration for us then it will saves thousands of developer's time.
I think you got my point.
And we can close the issue here.

**Comment by cebe** [comment]
> PS: For point no. 6. If we can attach method to Yii it must be cool fiture.

you can already have your own version of the Yii file, thats why it is completely empty and extends from YiiBase.

**Comment by cebe** [comment]
also you can define your own shortcuts if you want.
For example, create a file which you include in index.php:

```php
<?php

function a($text, $url = null, $options = []) {
    return Html::a($text, $url, $options);
}

function post($name = null, $defaultValue = null){
    return Yii::$app->request->post($name, $defaultValue);
}

// feel free to add more whatever you like...
```
