### ISSUE TITLE
relation join issue 

### ISSUE THREAD

**Issue by xaadi** [yiisoft/yii2#8213]
i have table name post_skills relation with posted..

 $query = PostSkills::find()
->jonWith('postSkills')
 ->all();

when i write this code found this error..

--------						
code: 0
file: "/.../xxxxxxx/vendor/yiisoft/yii2/base/Component.php"
line: 143
message: "Getting unknown property: api\common\models\Posted::"
name: "Unknown Property"

PS: post_skills relation is also defined in posted model

**Comment by mdmunir** [comment]
http://www.yiiframework.com/forum/

**Comment by klimov-paul** [comment]
Looks like usage error.
@xaadi, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a>
