### ISSUE TITLE
Linking from backend to frontend application

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#8216]
I have setup a separate urlManager for linking to front-end as follows:

    'urlManagerFrontend' => [
            'class' => 'yii\web\UrlManager',
            'baseUrl' => '/a/frontend/web',
            //'enablePrettyUrl' => true, //add these to prod
            //'showScriptName' => false, //add these to prod
        ],

Now when I execute the following:
`echo Yii::$app->urlManagerFrontend->createAbsoluteUrl(["register/index"]);`

I get the following link, which isn't linking to frontend
`http://localhost/~BAWES/myproject/backend/web/index.php?r=register%2Findex`

However, when I uncomment `enablePrettyUrl` and `showScriptName` I get the following link, which is correctly linking to the frontend
`http://localhost/a/frontend/web/register/index`

I wish to link to front-end with `enablePrettyUrl` set to `false` and `showScriptName` set to `true` - yet it doesn't seem to allow that

**Comment by klimov-paul** [comment]
You should setup `UrlManager::scriptUrl` for that.
