### ISSUE TITLE
Date time with .ffffff  (ms)

### ISSUE THREAD

**Issue by EagleMoor** [yiisoft/yii2#8217]
We have table on pgsql with time_stamp (yyyy-MM-dd HH:mm:ss.ffffff)

```sql
CREATE TABLE gps_log
(
    id SERIAL PRIMARY KEY NOT NULL,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    time_stamp TIMESTAMP DEFAULT now() NOT NULL,
    token VARCHAR,
    speed REAL,
);
```

Rows Example 

```
... "2015-04-28 10:06:15.000000" ...
```

Try to format ```Yii::app->format->asDateTime($time_stamp, 'yyyy-MM-dd HH:mm:ssZ')``` return "2015-04-28 06:06:15+0400", but ```Yii::app->format->asDateTime(substr($time_stamp, 0, 10), 'yyyy-MM-dd HH:mm:ssZ')``` return normal "2015-04-28 14:06:15+0400"

**Comment by cebe** [comment]
unable to reproduce, added a Unit test to verify it.
