### ISSUE TITLE
请问个urlmanager的问题

### ISSUE THREAD

**Issue by wuxing164** [yiisoft/yii2#8220]
在yii1中用 'urlFormat' => 'path',可以让key/value/key2/value2这样排下去
怎么在yii2没有功能了,如果一个网站有很多不同的key如page id date....等等,那不是都要写个rule出来,
这个问题很头疼,在yii2中有解决方案么

**Comment by lichunqiang** [comment]
Pls translate to english and will be get more reply

**Comment by qiangxue** [comment]
yii2取消了这个功能，因为它对SEO是有害的。如果你实在需要这个功能，你需要自己写一个UrlRule类来实现。
