### ISSUE TITLE
GET request to /app/model/PostSearch::search()

### ISSUE THREAD

**Issue by louisseb** [yiisoft/yii2#8221]
When calling  /app/model/ModelSearch::search() from a form (post request), the form datas are loaded via /yii/base/Model::load($params, $formName). The data are inside the array $params['ModelSearch'] , and they are parsed inside the search object thanks to $this->setAttributes($data[$scope]).

But, when calling  /app/model/ModelSearch::search() from an url (a GET request), the params datas can't be loaded, because they are not inside a table  $params['ModelSearch'], but directly inside $params.

The load function accept a second parameter for this case : $formName, wich if empty, call $this->setAttributes($data). BUT, the logic of /app/model/ModelSearch::search() , as generated by GII, don't give any way to provide this second parameter to the load function. 

Here what it does :

public function search($params)
{
...
   $this->load($params);
}

The /app/model/ModelSearch::search() should accept a second parameter to parse to load function, or should check $params['ModelSearch'] is empty.

Here the fix I propose :

public function search($params)
{
...
  if(isset$params['ModelSearch'])
   {
      $this->load($params);
   }
   else
   {
     $this->load($params, '');
   }

}

**Comment by mdmunir** [comment]
do it by your self

**Comment by louisseb** [comment]
I did it by my self, of course...
And I also writed a tip on the wiki :
http://www.yiiframework.com/wiki/811/building-a-search-get-request-with-scenarios-calling-a-searchmodel-from-urls/

And I also suggest you to modify the GII code generator to inclued the
snipet inside app\models\ModelSearch::find().





2015-04-29 15:41 GMT+02:00 Misbahul D Munir <notifications@github.com>:

**Comment by louisseb** [comment]
but maybe you mean that I should change by myself the Gii code and submit the modification ? 
why not...

**Comment by klimov-paul** [comment]
Gii generates only the basic code. If you require additional functionality, you should adjust it yourself or create your own CRUD template.
