### ISSUE TITLE
yii2 active field ajax validation call back

### ISSUE THREAD

**Issue by saifabbasi** [yiisoft/yii2#8223]
I have to display error on element 1, based on a function which checks value of element 1 and element2 are already saved in db or not, this needs to done on blur of element1 and element 2, and is working successfully on element1 blur event, but when i trigger ajax validation on element 2, it seems there is no success call back for active field ajax validation, so i can get back error or success return and apply it on elemnt1, Any help?

**Comment by SilverFire** [comment]
I can't understand the problem. Closing the issue as low-quality one.
