### ISSUE TITLE
REST Serializer and custom fields with ActiveDataProvider

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii2#8224]
Hi, 

I'm trying to return a ActiveDataProvicer on a REST-Call which has "calculated" fields that aren't existing in the database. 

I extended my Model with a getField() method to return the value of the calculated field. What ever I tried, it's not returning the "field" within the ActiveDataProvider so it's missed inside my result:(

How can I fix this?

Thanks Philipp

**Comment by mikehaertl** [comment]
Have you added a [fields()](http://www.yiiframework.com/doc-2.0/yii-base-model.html#fields()-detail) method to your models, where you also list your custom fields?

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/guide-rest-resources.html#overriding-fields

**Comment by philippfrenzel** [comment]
Hi, I added the fields to the controller... so i need to move it to model?

**Comment by philippfrenzel** [comment]
Juhu, this solved it! Pls. can you make this more "clear" within the docs, that this needs to be changed within the model?! Thanks!!!

**Comment by cebe** [comment]
> By default, yii\base\Model::fields() returns all model attributes as fields, while yii\db\ActiveRecord::fields() only returns the attributes which have been populated from DB.

can it be more clear that this is a method of the model? :)

**Comment by philippfrenzel** [comment]
you are right ... but as I'm not really a "developer" - to be honest, I can't actutally read the classes... so I'm pretty bad in reading the class docs... next time i try to figure out the class methods first - thanks you are doing an awesome job!

**Comment by cebe** [comment]
this was a citation from the guide that was linked above :)
