### ISSUE TITLE
CSRF validation fails when enableCookieValidation is set to false

### ISSUE THREAD

**Issue by miraage** [yiisoft/yii2#8228]
```php
var_dump(
    $this->getCsrfTokenFromHeader(),
    $trueToken,
    $this->validateCsrfTokenInternal($this->getCsrfTokenFromHeader(), $trueToken)
);
```

```
string(32) "hxcVQZaKExsPsmCiKPWZb7B0J4qJSEZT"
string(32) "hxcVQZaKExsPsmCiKPWZb7B0J4qJSEZT"
bool(false)
```

**Comment by miraage** [comment]
Looks like `validateCsrfTokenInternal` should simply compare strings if `enableCookieValidation` is set to `false`.

**Comment by miraage** [comment]
Can I create pull request to ensure that issue will be closed before 2.0.5?

**Comment by samdark** [comment]
It's not verified yet by us but pull request sounds helpful. So do it if it doesn't take too much of your time.

**Comment by samdark** [comment]
Added a test that verified that it works: https://github.com/yiisoft/yii2/commit/372ff87ee4c850feb0e95f149d905ef5ac43192a

**Comment by miraage** [comment]
@samdark, `$request->validateCsrfToken()` always returns true on GET/HEAD/OPTIONS request. :)

**Comment by samdark** [comment]
Yes but that's expected since for these request types there's nothing to protect you from.
