### ISSUE TITLE
Secondary use of {summary} in GridView layout

### ISSUE THREAD

**Issue by idMolotov** [yiisoft/yii2#8231]
When in 'controller view'
I try to config 'layout' template for GridView
using in layout '{summary}' several times
and setting custom 'tag' for '{summary}'

then, within second '{summary}' block I will always have 'div' tag.

```php
$gridConfig = [
    ...
    'layout' => '
      <div class="mailbox-controls clearfix">
          <div class="pull-right">
              {summary}
              {pager}
          </div>
      </div>
      <div class="table-responsive mailbox-messages">
          {items}
      </div>
      <div class="mailbox-controls">
           <div class="pull-right">
              {summary}
              {pager}
          </div>
      </div>
    ',
    ...
    'summaryOptions' => [
        'tag' => false, // or any other non "DIV" tag
    ],
    ...
];


GridView::widget($gridConfig);
```

It looks like in this line on the first call we remove custom tag and on the next call this attribute is NULL.
https://github.com/yiisoft/yii2/blob/cd0093f7bd01de39ef9d1fe1dcfbec070ad0a839/framework/widgets/BaseListView.php#L179
```php
$tag = ArrayHelper::remove($this->summaryOptions, 'tag', 'div');
```

It seems to me, that if we replace it to  the
```php
$tag = ArrayHelper::getValue($this->summaryOptions, 'tag', 'div');
```
the issue will be fixed.

**Comment by cebe** [comment]
Fixed,thanks for reporting!
