### ISSUE TITLE
Passwords exposed in logs by $_POST  

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#8232]
I want to point out a risk in the logs, when people put in passwords in forms and ie. a HTTP error occurs. The password is stored in the POST variable which is exposed by the logs in either the DB / logfile based on ones settings.

**Comment by cebe** [comment]
this is normal, you have to configure logging to not include POST if you want to avoid this.

**Comment by TomaszKane** [comment]
From Yii 2.0.9 it's possible to ignore defined keys in global arrays, like POST['password'].
http://www.yiiframework.com/doc-2.0/yii-log-target.html#$logVars-detail
