### ISSUE TITLE
TimestampBehavior do not insert proper time in database, and customizing how it does do not work ( as per guide instructions )

### ISSUE THREAD

**Issue by Black-Room-Boy** [yiisoft/yii2#8234]
I have created_at and updated_at fields in my table. I am using TimestampBehavior in my model:

`public function behaviors()`
`{`
    `return [`
        `TimestampBehavior::className(),`
    `];`
`}` 

When I insert or update a record with AR I can see that time output is 2 hours behind the real one.
For example it says that update time of some record ( 'updated_at:dateTime' ) is 8:33 but it is 10:33.

Then I found instructions here: http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html about how to customize the way the timestamp is calcualted. When I put this code in my model:

`public function behaviors()`
`{`
    `return [`
        `[`
            `'class' => TimestampBehavior::className(),`
            `'createdAtAttribute' => 'create_time',`
            `'updatedAtAttribute' => 'update_time',`
            `'value' => new Expression('NOW()'),`
        `],`
    `];`
`} `

I get this error :

`ReflectionException    
Class created_at does not exist    `

If I remove created and updatedAtAttribute I will get this error:      

`Invalid Configuration – yii\base\InvalidConfigException      
Unsupported configuration type: object      `

Is this a bug ? Or maybe you know what may be the problem ? I am using yii 2.0.3

**Comment by cebe** [comment]
for the first issue, your db server seems to have a different timezone than the application.
The second error does not seem related, please paste the full stack trace of the error.

**Comment by Black-Room-Boy** [comment]
Invalid Configuration – yii\base\InvalidConfigException
Unsupported configuration type: object

    1. in /var/www/html/test/vendor/yiisoft/yii2/BaseYii.php at line 350
    341342343344345346347348349350351352353354355356357358359

            } elseif (is_array($type) && isset($type['class'])) {
                $class = $type['class'];
                unset($type['class']);
                return static::$container->get($class, $params, $type);
            } elseif (is_callable($type, true)) {
                return call_user_func($type, $params);
            } elseif (is_array($type)) {
                throw new InvalidConfigException('Object configuration must be an array containing a "class" element.');
            } else {
                throw new InvalidConfigException("Unsupported configuration type: " . gettype($type));
            }
        }
     
        private static $_logger;
     
        /**
         * @return Logger message logger
         */
        public static function getLogger()

**Comment by Faryshta** [comment]
can you copy the `behaviors` method? I have seen that error, i think you missed one opening/close square brackets.

**Comment by thejahweh** [comment]
Try this from the guide

http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html#using-timestampbehavior

```php
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }
```

**Comment by latteo** [comment]
I saw your log
It seems to me you have error in your controller
Can you show the controller action code?

**Comment by klimov-paul** [comment]
Closed unless more information arrives.

**Comment by keeprock** [comment]
I've got the same issue. Try this:

`
return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'start_date',
                'updatedAtAttribute' => 'update_date',
                'value' => new Expression('NOW()'),
            ]
        ];
`

**Comment by twdragon** [comment]
Without 'timestamp' wrapping array, should I consider the issue as the trying to create an object with the same class name  as an attribute? Does the API documentation need renewal?

**Comment by dynasource** [comment]
@keeprock: can you supply more details about your issue?
@twdragon: classname as an attribute??

**Comment by guisilveirabatista** [comment]
I had the same issue. thejahweh's solution did the trick for me.
