### ISSUE TITLE
Bug with form action in yii.js handleAction

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#8236]
I have a form and anchor with `data-method` inside. When clicking on this anchor, form is submitting with wrong action (not from `href` of anchor). It seems that setting old `action` is happening earlier than submitting. Everything is ok, if you comment this line:
```javascript
$form.attr('action', oldAction);
```

**Comment by qiangxue** [comment]
I guess the form is being submitted asynchronously and thus the statements after the submit event are executed before the form is actually submitted. Need to verify this.

**Comment by RomeroMsk** [comment]
I just logged submitting of a form and see that it repeats after `handleAction` is done:

1. Submit from [here](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L206).
2. Restore `action` from `oldAction`.
3. Submit from somewhere else (can't figure it out).

So the problem is not in this method, as I thought before.

**Comment by RomeroMsk** [comment]
Second submit is calling because of [this](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L349).

**Comment by vbelogai** [comment]
[Duplicate 8161] (https://github.com/yiisoft/yii2/issues/8161)

**Comment by samdark** [comment]
Any idea how to solve it?

**Comment by vbelogai** [comment]
I think code in yii.js should be like this:

        set-form's-action-from-link's-href
        submit-form
        $.when($form).then(restore-original-form's-action)

and activeForm should implement .promise() method

This approach preserves default behavior (without activeForm) and implements async pattern for activeForm

**Comment by samdark** [comment]
@vbelogai do you have time to submit a pull request?

**Comment by RomeroMsk** [comment]
Temporary solution, while bug is present, is to turn off all client validation.

**Comment by vbelogai** [comment]
Pull request is ready (https://github.com/yiisoft/yii2/pull/8368)

**Comment by klimov-paul** [comment]
Duplicates #8161
