### ISSUE TITLE
Related data in ActiveFixture

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#8237]
Is there any posibility to make related fixtures.
When we make main fixture data and can use it primeryKey values in relateted data
example;
Users Data
```php
'user1' => [
    'name' => 'random_name'
]
```

Posts Data
```php
'post1' => [
   'user_id' => UsersFixture->user1->id
   'post' => 'random_text'
]
```

**Comment by cebe** [comment]
why don't you define primary key explicitly in this case?

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
