### ISSUE TITLE
Logging cache calls

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2#8238]
Currently trying to optimise some of the requests being made to our project and specifically the healthcheck that needs to return a 200 response.
I can see that our healthcheck is calling memcache get and set somewhere but having a hard time pin pointing it.

I was looking into events and was hoping to do something with the config along the lines of:
'on get' => function($event) {
    Yii::info('memcache get');
},

Is there a way of debugging this in a similar way to the DB debugging tool?
I've tried xdebug but before but it returned some very odd results, lots of function names which were being listed as numbers (perhaps I set this up wrong).

Thanks.

**Comment by klimov-paul** [comment]
Duplicates #2365
