### ISSUE TITLE
Gii model creation fails for pgsql tables that have (unique) functional index(es)

### ISSUE THREAD

**Issue by jurgenvandulst** [yiisoft/yii2#8239]
PHP: 5.4
OS: Win 7
Webserver: Apache 2.2
Yii: 2.0.3

When using Gii to generate a model from a pgsql table, the call will throw a fatal error if the table uses a (unique) functional index. In my case the functional index was "lower(email::text)". Should be very easily reproduced.

Workaround for now is to remove the index and re-apply it after generation. Unique constraints will have to be added to the model manually.

Call stack:
\htdocs\vendor\yiisoft\yii2-gii\generators\model\Generator.php at line 624
2. in \htdocs\vendor\yiisoft\yii2-gii\generators\model\Generator.php – yii\base\ErrorHandler::handleError(2, 'Invalid argument supplied for foreach()', '...', 624, ...) at line 624
3. in \htdocs\vendor\yiisoft\yii2-gii\generators\model\Generator.php – yii\gii\generators\model\Generator::isColumnAutoIncremental(yii\db\TableSchema, 'email') at line 269
4. in \htdocs\vendor\yiisoft\yii2-gii\generators\model\Generator.php – yii\gii\generators\model\Generator::generateRules(yii\db\TableSchema) at line 173
5. in \htdocs\vendor\yiisoft\yii2-gii\controllers\DefaultController.php – yii\gii\generators\model\Generator::generate() at line 45
6. yii\gii\controllers\DefaultController::actionView('model')

**Comment by cebe** [comment]
thanks for the callstack but what is the error message? :)

**Comment by jurgenvandulst** [comment]
Oops, Invalid argument supplied in foreach(). 

It's trying to foreach a string value (in my case, it was a column name, instead of an array of column names)
