### ISSUE TITLE
Foreign key violation while unload related fixtures 

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#8240]
I have such fixtures
```php
namespace app\tests\codeception\unit\fixtures;

use yii\test\ActiveFixture;

class CrmFixture extends ActiveFixture
{
    public $modelClass = 'app\modules\frontend\modules\webtool\modules\crm\models\Crm';
}
```
```php
namespace app\tests\codeception\unit\fixtures;

use yii\test\ActiveFixture;

class CrmUsersFixture extends ActiveFixture
{
    public $modelClass = 'app\modules\frontend\modules\webtool\modules\crm\models\CrmUsers';
    public $depends = ['app\tests\codeception\unit\fixtures\CrmFixture'];
}
```
and declaretion in test
```php
    public function fixtures()
    {
        return [
            'crmUsersFixture' => CrmUsersFixture::className(),
            'crmFixture' => CrmFixture::className(),
        ];
    }
```
and got such error
[yii\db\IntegrityException] SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "crm" violates foreign key constraint "crm_users_fk" on table "crm_users"
DETAIL:  Key (id)=(2) is still referenced from table "crm_users".
The SQL being executed was: DELETE FROM "crm"

**Comment by cebe** [comment]
you have to disable foreignkey checks when unloading fixtures. which dbms are you using?

**Comment by xVismutx** [comment]
postgre
This is from doc
*The dependency also ensures, that the fixtures are loaded and unloaded in a well defined order. In the above example UserFixture will always be loaded before UserProfileFixture to ensure all foreign key references exist and will be unloaded after UserProfileFixture has been unloaded for the same reason.*

**Comment by xVismutx** [comment]
Is there all good in unload method of FixtureTrait?

**Comment by xVismutx** [comment]
https://github.com/yiisoft/yii2/issues/8278
