### ISSUE TITLE
UnitTests: 'rm' is not recognized as an internal ... in WinOS

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#8241]
system Win8.1, php-5.6.5-nts-Win32-VC11-x64

this file uses 2 functions available only under Linux, in windows it fails with error
yiiunit\framework\console\controllers\AssetControllerTest
removeDir() and createAssetController()

as solution i did for myself

    private $is_win = false;
    public function setUp() 
    {
        $this->is_win = strncasecmp(PHP_OS, 'WIN', 3) === 0 ? true : false;
     ...
    }

    protected function removeDir($dirName)
    {....
        	if ($this->is_win) {
        		exec("rmdir /Q /S \"{$dirName}\"");
        	} else {
        		exec("rm -rf {$dirName}");
        	}
    }

    protected function createAssetController()
    { ....
        $assetController->jsCompressor = $this->is_win ? 'copy {from} {to}' : 'cp {from} {to}';
        $assetController->cssCompressor = $this->is_win ? 'copy {from} {to}' : 'cp {from} {to}';
    }

regards

p.s.
also at first it tries to delete 1 folder that does not exist and fires "E" in test. hm

also spams "Undefined index: oci"
%\tests\framework\db\DatabaseTestCase.php:20
66) yiiunit\framework\db\oci\OracleCommandTest::testConstruct
Undefined index: oci

also some tests failed for formatters i18n. i'll try to check what's up

**Comment by yurii-github** [comment]
also writes "Undefined index: oci"
also some tests failed for formatters i18n. i'll try to check what's up

**Comment by yurii-github** [comment]
p.s.
looks ok from git bash as it has rm method.

**Comment by klimov-paul** [comment]
bc735bb
