### ISSUE TITLE
Can we dynamic to instance the class

### ISSUE THREAD

**Issue by winds1983** [yiisoft/yii2#8242]
I want to dynamic instance the class, the code as below:
namespace app\components\compress;
use app\components\compress\ZipAdapter;
......
$adapter = ucfirst(strtolower($fileExtension)) . 'Adapter';
return new $adapter($this->file, $this->to);
......

but I still get this error:
PHP Fatal error:  Class 'ZipAdapter' not found in /***/components/compress/CompressAdapter.php on line 81
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'ZipAdapter' not found'

in /***/components/compress/CompressAdapter.php:81

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

but I use the flowing code, it will works fine.
return new ZipAdapter($this->file, $this->to);

and I move this without Yii2, it still works fine.

Can you help me?

Advance thanks.

**Comment by samdark** [comment]
Try full namespaced class name. Overall, it's general PHP thing, not Yii-specific issue.
