### ISSUE TITLE
yii2-dev and yii2

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#8243]
"minimum-stability": "dev",
	"require": {
		"php": ">=5.4.0",
		"fxp/composer-asset-plugin": "^1.0.0",
		"yiisoft/yii2-dev": "~2.0.0",
		"yiisoft/yii2-swiftmailer": "~2.0.0",
		"yiisoft/yii2-bootstrap": "~2.0.0",
		"yiisoft/yii2-jui": "~2.0.0",
		"yiisoft/yii2-imagine": "~2.0.0"
	},
	"require-dev": {
		"phpunit/phpunit": "4.4.*",
		"yiisoft/yii2-gii": "~2.0.0",
		"yiisoft/yii2-debug": "~2.0.0"
	}

with this composer.json i get what i wanted - unit tests for yii2. also it included framework. But i also see yii2 folder with framework (aka yiisoft/yii2). I want to have framework with unit tests so i can test it in my environment but not duplicate it, with ability to modify and test. how can i achieve it? regards

>composer update --dry-run
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating yiisoft/yii2 (dev-master 8b74825) to yiisoft/yii2 (dev-master 205fa13)
  - Updating yiisoft/yii2-bootstrap (dev-master 554c3cc) to yiisoft/yii2-bootstrap (dev-master 37b1b59)
  - Updating yiisoft/yii2-dev (dev-master 029edee) to yiisoft/yii2-dev (dev-master 543daf0)

note: yii2 is used in application, and yii2-dev/framework is only used in tests

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/getting-started.md#getting-started-with-yii2-development

**Comment by yurii-github** [comment]
closed? is it a joke, right?
i don't want to make forks. i want to test it and use it.
if i require yiisoft/yii2 i don't have tests.
if i require yiisoft/yii2-dev i get yiisoft/yii2 and yiisoft/yii2-dev with tests and framework duplication (used only for tests). so if i change in yiisoft/yii2 and will not be able to test it w/o copy-paste

this link is not an answer

**Comment by cebe** [comment]
seems there is a problem with composer.json after extension have been moved.

**Comment by cebe** [comment]
should be fixed now.
