### ISSUE TITLE
Relation definition format change?

### ISSUE THREAD

**Issue by ScottHuangZL** [yiisoft/yii2#8245]
The User class like below
```
class User extends ActiveRecord implements IdentityInterface
```
And then in one of my model, I add below relation.
```
class ApprovalTree extends \kartik\tree\models\Tree
{
...
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id'])->one();
    }
...
}
```
Then I can use below code to get username
```
$userNode->getUser()->username
```
**However, there will pop up issue if I remove "->One()" from relation code.  
As I remember, the relation definition no need "->one()", right?  (Even according latest online guide)
Any change for the relation definition recently? Or it is right since my model derive from one extension/module.**

Btw, I use v2.0.3 dev version.

**Comment by mdmunir** [comment]
You dont need `->one()`

**Comment by ScottHuangZL** [comment]
I think so too. However, my yii2 will show error if I remove ->one().

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#accessing-relational-data
If you define realtion as `getUser()` you may access it as `$model->user`.

**Comment by cebe** [comment]
moved the rather hidden note a bit to be more visible and added an example code:

https://github.com/yiisoft/yii2/commit/b4062ab246595a01c9e0de32b963ac04ca5951a6#diff-e9e5f516d52124c69f3ca4a0374943d3R767
