### ISSUE TITLE
cant define class in the nav (secundary menu)

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#8257]
im trying define the class in the second UL of the nav::widget() but i cant

i see this
in the file yii\bootstrap\Dropdown
```php
 public function init()
    {
        parent::init();
        Html::addCssClass($this->options, 'dropdown-menu');
    }
```

and the subclass
```php
   if ($url === null) {
                    $content = $label;
                    Html::addCssClass($itemOptions, 'dropdown-header');
                } else {
                    $content = Html::a($label, $url, $linkOptions);
                }
            } else {
                $submenuOptions = $options;
                unset($submenuOptions['id']);
                $content = Html::a($label, $url === null ? '#' : $url, $linkOptions)
                    . $this->renderItems($item['items'], $submenuOptions);
                Html::addCssClass($itemOptions, 'dropdown-submenu');
            }
```
why is static the className ? and the secundary class like "dropdown-header", i think this need a improve for add dynamic names

note:

the class Nav,Dropdown in the [namespace yii\bootstrap] need multiple improvements

for example:
- in the dropdown this var is useless foreach ($items as $i => $item) $i never used

-in the nav protected function renderDropdown($items, $parentItem) $parentItem never used

-cant define the class when i select a item in the dropdown only for default "active" in the <li> parent

my suggestions, check this 2 class and add support for add the class for the dropdown in the nav like "dropdownClass" or other word

**Comment by spiritdead** [comment]
@cebe @qiangxue @samdark

**Comment by cebe** [comment]
there is no need to explicitly mention core team members here, we get notified about all issues anyway.

**Comment by spiritdead** [comment]
@cebe sorry man

**Comment by klimov-paul** [comment]
'dropdown-menu' is required for correct (hidden) display of the items in dropdown.
You can always add extra class(es) to the conteiner 'ul' using `Dropdown::options['class']`. Why it is not working for you?
Same is for 'dropdown-header' and 'dropdown-submenu'.
Why it is crucial for you to remove them entirely?

**Comment by klimov-paul** [comment]
Resolved by https://github.com/yiisoft/yii2-bootstrap/pull/52
