### ISSUE TITLE
lost data tag in DetailView widget

### ISSUE THREAD

**Issue by ivantree** [yiisoft/yii2#8259]
```
<?=DetailView::widget([
        'model' => $model,
        'attributes' => [
            'attribute' => 'name',
            'format' => 'html',
            'value' => Html::a('link text',['index'],['data'=>['url'=>Url::to(['index'])],'class'=>'btn'])
        ]
    )];
?>
```
output html 
<td><a class="btn" url="index">link text </a></td>
"data-url" tag not output 

'value' => Html::a('link text',['index'],['data-url'=>Url::to(['index']),'class'=>'btn'])
error still

**Comment by cebe** [comment]
> 'format' => 'html',

format HTML means that the output will be filtered by HtmlPurifier. If you want the link as is, you have to use format 'raw'

**Comment by ivantree** [comment]
Thank a lot!
