### ISSUE TITLE
controllers and actions 分离问题

### ISSUE THREAD

**Issue by wenziyelang** [yiisoft/yii2#8263]
controllers and actions 分离后，在CreateAction里面不能使用return $this->redirect

目录结构是这样的：
controllers
           ContentController.php
           content
                   CreateAction.php
                   UpdateAction.php
                   IndexAction.php
                   DeleteAction.php

**Comment by wenziyelang** [comment]
我知道了强哥，谢谢

**Comment by haoliangxxx** [comment]
怎么个前因后果, `你就知道了强哥,谢谢`？

**Comment by wenziyelang** [comment]
我的controllers 和actions 是分离开的，就是action不在controller里面写，比如CreateAction.php，新建对应ContentController.php对应的content文件夹，在content里面新建CreateAction.php，当我在CreateAction.php中的run方法里面试图return $this->redirect就报错，找不到redirect方法，原因很简单我调用的不对，应该用 return $this->controller->render
