### ISSUE TITLE
url 

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/yii2#8264]
Hi, I have a question, why in urls when an action have tow world, like actionCreateUser in BaseUserController
this action link auto change to : baseuser/create-user 
but contoller don't change??
if it's don for seo its beter to be: base-user/create-user

**Comment by klimov-paul** [comment]
Duplicates #1663

**Comment by hooman-pro** [comment]
I sayd that if camel case action link change to word-word 
camel case controllers should have same behavior. but why it's not happend??

**Comment by klimov-paul** [comment]
#7557

**Comment by hooman-pro** [comment]
thank u
