### ISSUE TITLE
output wrong migration directory: ./yii migrate/create --migrationPath=@app/backend/migrations

### ISSUE THREAD

**Issue by haoliangxxx** [yiisoft/yii2#8265]
```bash
% ./yii migrate/create --migrationPath=@app/backend/migrations create_table_url
Yii Migration Tool (based on Yii v2.0.3)

Create new migration '/srv/http/ferry/console/backend/migrations/m150504_121021_create_table_url.php'? (yes|no) [no]:
```

Is the output directory correct ? I suppose it to be `/srv/http/ferry/ferry/migrations`

**Comment by klimov-paul** [comment]
Yes, it is correct.

**Comment by haoliangxxx** [comment]
@klimov-paul but what the `@app/backend/migrations` means in this command?

**Comment by klimov-paul** [comment]
`@app` is an alias of the current application root, which is a 'console' application in your case.
So `@app` is resolved as '/srv/http/ferry/console'. Everything is correct.

**Comment by haoliangxxx** [comment]
oh, I see. I should use `@backend` instead.
Thanks.
