### ISSUE TITLE
Component get on Redis returns wrong connection

### ISSUE THREAD

**Issue by stefandoorn** [yiisoft/yii2#8269]
I have a weird issue I can't get the solution for. I try to get the connection 'redis2' but in my frontend app it keeps returning me the information set on 'redis'. Might be some interference as the cache driver is loaded before, but still. On my console it works as expected. 

I have two Redis connections:

    'components.redis' => [
        'class' => 'yii\redis\Connection',
        'hostname' => 'localhost',
        'port' => 6379,
        'database' => 0,
    ],
    'components.redis2' => [
        'class' => 'yii\redis\Connection',
        'hostname' => '127.0.0.1',
        'port' => 6379,
        'database' => 1,
    ],

In my frontend app this:

        echo '<pre>';
        print_r(\Yii::$app->get('redis'));
        print_r(\Yii::$app->get('redis2'));
        exit;

Results in:
````
yii\redis\Connection Object
(
    [hostname] => localhost
    [port] => 6379
    [unixSocket] => 
    [password] => 
    [database] => 0
````
&
````
yii\redis\Connection Object
(
    [hostname] => localhost
    [port] => 6379
    [unixSocket] => 
    [password] => 
    [database] => 0
````
While doing the same on my console command gives:
````
yii\redis\Connection Object
(
    [hostname] => localhost
    [port] => 6379
    [unixSocket] =>
    [password] =>
    [database] => 0
````
&
````
yii\redis\Connection Object
(
    [hostname] => 127.0.0.1
    [port] => 6379
    [unixSocket] =>
    [password] =>
    [database] => 1
````

I've been digging in this problem for a while now. Ofcourse I can solve it by using one connection and switching database, but I would like to keep it split to support separating things later on in the process. I might be overlooking something, or it might be a bug.

**Comment by cebe** [comment]
> 'components.redis' => [

this is not what goes into the final application configuration, please check the 'components' section of the application config if you assign it correctly.

**Comment by stefandoorn** [comment]
True, this is what the config looks like (see below). Previous format is due to our setup where we merge several other configs into this one below.

````
Array
(
    [components] => Array
        (
            [redis] => Array
                (
                    [class] => yii\redis\Connection
                    [hostname] => localhost
                    [port] => 6379
                    [database] => 0
                )
            [redis_dbqueue] => Array
                (
                    [class] => yii\redis\Connection
                    [hostname] => localhost
                    [port] => 6379
                    [database] => 1
                )
````

**Comment by cebe** [comment]
are you sure your config merging works correctly? Also you are talking about `redis1` and `redis2` in the report above but now you show `redis_dbqueue` which looks correct. Please verify your setup and try to reproduce this in a simple setup.

**Comment by stefandoorn** [comment]
Ah sorry. I made the first example simplified, but now I pasted from the real environment. To make things look easier I changed the comment above. We do the same for a long time with database connections and used redis also for a long time already. Only recently added 'redis2' to it. What might be interesting to know is that it's the yii2 advanced app. Apologies for the unclear naming.

**Comment by cebe** [comment]
you should check in console and web app config if you are really using different names for assigning the component from common config.

**Comment by stefandoorn** [comment]
I will try to reproduce the issue in a clean yii2 advanced app later this week to see how things work in there. Will keep you posted.

**Comment by stefandoorn** [comment]
@cebe, installed clean advanced apps with Redis included and did some testing. In a clean environment I get the correct connections returned and also the correct information shown in Redis using the CLI. I will dig in our application later.
