### ISSUE TITLE
registerCssFile position restricted to POS_HEAD?

### ISSUE THREAD

**Issue by antokara** [yiisoft/yii2#8270]
I understand that for JS I can define the position, but for CSS it is explicit and limited to POS_HEAD?

There are cases where CSS can and is needed to be placed at POS_END (to satisfy for example Google's Page Speed Insight Rules) and not block the html rendering process of the browser...

At the moment I have to manually insert the code inside the view?
I think even the registerLinkTag is out of the question for such scenario.
(same applies to AssetBundles CSS I believe)

Please advise.

**Comment by yurii-github** [comment]
css file can be linked only in head according to html standard.
and style tag is not recomended

**Comment by antokara** [comment]
You are correct. I guess the only solution then is to append the tag in the head using javascript, to avoid the render blocking and to be in accordance to html standards...

Thanks!

**Comment by TriAnMan** [comment]
@yurii-github @antokara 
Hmm seems HTML5 Recomendations has a little ambiguity about <link> position: http://www.w3.org/TR/html5/document-metadata.html#the-link-element

You see "Contexts in which this element can be used:" is "Where metadata content is expected".
There is no exact definition of this context. But the whole page describes the content of this context e.g. head, title, base, link, meta, style.

And there is a paragraph:
"A link element must have a rel attribute.
If the rel attribute is used, the element is restricted to the head element."

Seems that it has redundant or mutually exclusive phrases.

So could anybody clarify the situation with <link> tag position?
Does Google right about https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery#example
Or it violates W3C recomendation?

**Comment by yurii-github** [comment]
TriAnMan 
in that example they add link to head via javascript what is ok. about style, it is ok in head only too as i know (it was ok in html4 though)

link is generic tag so it may have different places for different rel. for stylesheet it should be in head only.

regards
