### ISSUE TITLE
Wish: allow wildcards in rbac defaultRoles

### ISSUE THREAD

**Issue by fsateler** [yiisoft/yii2#8271]
On simple systems where a user will  only be assigned to one role, the `$defaultRole` functionality combined with a `DefaultRoleRule` is very helpful. However there is a small annoyance: one needs to list all roles in the `$defaultRoles` array if one wants to use `user->can('roleName')`.

Therefore the wish to be able to set `$defaultRoles` to a wildcard so that the list of roles need only be set in the rbac initialization code.

**Comment by samdark** [comment]
What's `DefaultRoleRule`?

**Comment by fsateler** [comment]
Sorry, copy paste error. In the guide it is called `UserGroupRule`

On 4 May 2015 at 18:39, Alexander Makarov <notifications@github.com> wrote:
> What's DefaultRoleRule?
>
> —
> Reply to this email directly or view it on GitHub.



-- 

Saludos,
Felipe Sateler

**Comment by samdark** [comment]
Need more details about the way you're using RBAC and about what you're actually trying to achieve.

**Comment by fsateler** [comment]
OK, I'll try to explain better. RBAC, while very powerful, is complex and many applications can work with a restricted form: each user has 1 role. Moreover, the permissions scheme is static, so there is no need for an RBAC modification module (ie, the app does not allow modifying permissions). In this scheme, it is very useful to use the default role pattern: each user has a type, and the type maps to a role. So far I have just described what is possible with yii and is shown in the guide.

Because the defaultRoles option can be used for more patterns than this, the different manager classes check that the role is in the default role set, and if not they do not check if the user is part of said role.

What I want is a way to tell yii to apply all known roles to the defaultRoles array, and let my custom Rule determine which ones should be allowed (eg, select the role based on the user type). This way I do not have to maintain 2 lists: the list of user types and the list of defaultRoles, and instead use a single one.

**Comment by samdark** [comment]
OK, got it. Not sure how common is such usage. Need to think about it.
