### ISSUE TITLE
Error with Concat in active record select functions 

### ISSUE THREAD

**Issue by rrhyne** [yiisoft/yii2#8276]
AR parses select calls so that every word in a select query is surrounded by ticks. This breaks the ability to concat() strings with field values. 

    $quotes = Quote::find()->select("id, CONCAT(`name`, ' model id: ' ,id) as name")->all();

Results in the error:

<pre>
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM `quote`' at line 1
The SQL being executed was: SELECT `id`, CONCAT(`name`, `' model id: '`, `id)` AS `name` FROM `quote`
</pre>

You can clearly see the middle value of the concat statement is surrounded by ticks as if it were a field.

A valid sql query would be:

select id, CONCAT(`name`, ' model id: ' ,`id`) as name from quote;

**Comment by arisk** [comment]
Maybe this can help you
```php 
$quotes = Quote::find()->select(['id', new \yii\db\Expression("CONCAT(`name`, ' model id: ', `id`) as name")])->all();
```

**Comment by rrhyne** [comment]
Thanks arisk. In case anyone else finds this issue, this is also a solution, from the documentation: 

"If you do not call the select() method when building a query, * will be selected, which means selecting all columns.

Besides column names, you can also select DB expressions. You must use the array format when selecting a DB expression that contains commas to avoid incorrect automatic name quoting. For example:"

$query->select(["CONCAT(first_name, ' ', last_name) AS full_name", 'email']);
