### ISSUE TITLE
Gii should support specifying primary key when generating model?

### ISSUE THREAD

**Issue by fproject** [yiisoft/yii2#8277]
Sometimes we want to use some other ID field(s) instead of the default primary key defined in DB.

Should Gii support to generate model class with the method `public static function primaryKey()` overridden by specifying the key fields that user inputted from Gii's form?

This will help in the case we generate models from DB View, for example.

**Comment by samdark** [comment]
Probably yes. In case there's no PK it could ask about it.

**Comment by nineinchnick** [comment]
That would be useful when generating models for views, which don't have any constraints at all.

**Comment by samdark** [comment]
Yep.
