### ISSUE TITLE
Bug in loading-unloading dependent fixtures with foreign keys

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#8278]
From docs
*As we described earlier, a fixture may depend on other fixtures. For example, a UserProfileFixture may need to depends on UserFixture because the user profile table contains a foreign key pointing to the user table. The dependency is specified via the yii\test\Fixture::$depends property, like the following,*

It was so when $this->resetTable(); was in unload method
We loaded fixtures in load method, and reversly unloaded it in unload method.
So there were no problems with foreign keys

Then $this->resetTable(); was moved in  load method. We in default order we try to resetTable.
So dependent don't work properly

**Comment by cebe** [comment]
related to #5442

**Comment by klimov-paul** [comment]
Duplicates #5442
