### ISSUE TITLE
GroupUrlRule with prefix has unexpected behavior for empty ('') rules

### ISSUE THREAD

**Issue by fortex** [yiisoft/yii2#8281]
Hello,

I've encountered a "strange" (at least for me it is strange) behavior while using a GroupUrlRule.

Using the following rule:

```php
new \yii\web\GroupUrlRule(
        [
            'prefix'      => 'ideas',
            'routePrefix' => 'keywordIdeas',
            'rules'       => [
                ''    => 'index/index',
            ]
        ]
    )
```

Matches for the given URL:

```
/ideas
```

But NOT for:

```
/ideas/
```

The same applies if I change the rule to:

```
'/'    => 'index/index',
```

But if I add a rule:

```
'/'    => 'index/index',
'/?' => 'index/index'
```

/ideas is matched by the first rule and /ideas/ by the second. I think this is kind of unexpected.

I would assume that an empty rule would always be matched by /ideas and /ideas/.
And given the case I mentioned here, I would further assume, that the rule '/' only matches for /ideas/ but it only matches /ideas.

Edit: Any rule starting with '/' does not work.

Is this a bug or expected behaviour?

**Comment by cebe** [comment]
related to #7670, maybe even duplicate
