### ISSUE TITLE
Could yii\console\Request::$_params be changed from private to protected?

### ISSUE THREAD

**Issue by sol-hiqdev** [yiisoft/yii2#8282]
Hello,

I want to extend console Request incoming params processing.
But because of $_params is private it becomes a bit unnatural.
Why not make $_params protected instead of private?

P.S.
Actually I want to implement aliases like shell or git aliases to substitute original params with aliased params - I think Request is the good place to do it.

**Comment by cebe** [comment]
You can extend `getParams` and `setParams` to have your own implementation. There is no need to expose the internal variable here.
