### ISSUE TITLE
joinWith should move relation conditions to ON instead of WHERE

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#8283]
I have a relation defined in a class `Product` like this:

```
public function getText()
{
    return $this
        ->hasOne(Text::className(), ['product_id' => 'id'])
        ->andWhere(['language' => Yii::$app->language]);
}
```

`text` is a table with fk `product_id` to product and a `language` column.

Now I want to do a Product query with joined `text`:

```
Product::find()
    ->joinWith('text');
```

This creates SQL similar to:

```
SELECT `product`.* 
FROM `product` 
LEFT JOIN `text` ON `product`.`id` = `text`.`product_id`
WHERE `language_id`='en'
```

But instead this should rather be:

```
SELECT `product`.* 
FROM `product` 
LEFT JOIN `text` ON `product`.`id` = `text`.`product_id` AND `text`.`language`='en'
```

There's a difference in both results which becomes obvious if you want to do a query like:

```
Product::find()
    ->joinWith('text')
    ->andWhere('text.id IS NULL');
```

This now leads to: 

```
SELECT `product`.* 
FROM `product` 
LEFT JOIN `text` ON `product`.`id` = `text`.`product_id`
WHERE `language`='en' AND `text`.`language` IS NULL
```

which *always* gives you an empty result. Whereas the correct query:

```
SELECT `product`.* 
FROM `product` 
LEFT JOIN `text` ON `product`.`id` = `text`.`product_id` AND `text`.`language`='en'
WHERE `text`.`language` IS NULL
```

Gives you those `Product` records, that don't have a related `text` set.

### Suggestion:

To not break BC I'd suggest an additional argument to `joinWith()`:

```
joinWith($with, $eagerLoading='true', $joinType='LEFTJOIN', $useOn = false)
```

If `$useOn` is true, the WHERE conditions from the related query would be moved to the `ON` clause.

Sidenote: I remember having reported this exact same problem already in Yii 2's predecessors (namely PRADO and Yii 1). It was fixed but then the fix was undone if I remember correctly. So there probably where some issues with this. Still I think with the above argument, as a developer you can decide for yourself, if you want to use it.

**Comment by arisk** [comment]
Does something like this work?
```php
public function getText()
{
    return $this
        ->hasOne(Text::className(), ['product_id' => 'id'])
        ->onCondition(['language' => Yii::$app->language]);
}
```

**Comment by qiangxue** [comment]
Use `onCondition` as suggested by @arisk.

**Comment by mikehaertl** [comment]
Great, thanks. I've missed that method.
