### ISSUE TITLE
Captcha doesnt render because of failing IMagick

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#8284]
Following situation:
We have a webserver that is running a modified ImageMagick Version + the GD extension
The IMagick extension is not working normally due to personal optimizations its just working for a specified set of tasks.

Now Yii Captcha is checking if a the extension imagick is loaded then use it otherwise check for gd and use it. 

because of the server configuration (wich a developer cant change allways) that behavior isnt really helpful. it would be better if we could choose between the used extension in Captcha and set it via config option at CaptchaAction level.

Stacktrace:
```
[error][ImagickException] exception 'ImagickException' with message 'Failed to query the font metrics' in vendor/yiisoft/yii2/captcha/CaptchaAction.php:318
Stack trace:
#0 yii2/captcha/CaptchaAction.php(318): Imagick->queryfontmetrics(Object(ImagickDraw), 'rlhzaa')
#1 yii2/captcha/CaptchaAction.php(245): yii\captcha\CaptchaAction->renderImageByImagick('rlhzaa')
#2 yii2/captcha/CaptchaAction.php(134): yii\captcha\CaptchaAction->renderImage('rlhzaa')
#3 [internal function]: yii\captcha\CaptchaAction->run()
#4 yii2/base/Action.php(92): call_user_func_array(Array, Array)
#5 yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array)
#6 yii2/base/Module.php(455): yii\base\Controller->runAction('captcha', Array)
#7 yii2/web/Application.php(83): yii\base\Module->runAction('site/captcha', Array)
#8 yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 frontend/web/index.php(18): yii\base\Application->run()
```

**Comment by cebe** [comment]
could be done by adding a property: `$imageLibrary`, which is null by default meaning auto detect and could be set to 'gd' or 'imagick'
