### ISSUE TITLE
Active Record ReadOnly Option

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#8285]
I have a question and I did not find references to explain what I need.

I have an application being made in Yii2 of which will not have the CRUD the delete, edit and create new records, just to list and visualziar records. For this removed in the controller methods that define the actions and removed the views of views folder.

However ...

If someone lifting a model, fill their attributes and then send save, it will save the bank. Something I would not want to.

There are possibilities today, or future, of an inherited base class ActiveRecord have to define it is an ORM-type read only?

**Comment by klimov-paul** [comment]
@lukBarros, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by lukBarros** [comment]
@klimov-paul  I know the purpose, come contributing subprojects oo yii2 as the bootstrap and the gii with translations and improvements.

Understand me , I know the team is the core feature exists, if not, to feel good to have this so that we can together implement improvement.

Please look better for this issue .

**Comment by cebe** [comment]
if your app is read only, AR is not the layer where you need to implement read only. Better use permission system of the database enging.

**Comment by lukBarros** [comment]
@cebe  ok. You report is true. I am thinking about it. I did not think the way you spoke . I will try in my project. Thank you.
