### ISSUE TITLE
Yii::t() message generation when nested

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#8286]
I have code like this:

    Yii::t('employer',"Please click the verification link sent to you by email to activate your account.<br/>{resendLink}",[
        'resendLink' => \yii\helpers\Html::a(Yii::t("employer", "Resend Verification Email"), ["site/resend-verification"]),
    ]));

Now when I run `./yii messages common/messages/config.php` - all messages are generated, however the nested `Resend Verification Email` is not generated. It works if I add it manually to the file.

Is there a better way to do this?

**Comment by cebe** [comment]
currently the message command is not able to detect this situation, could be fixed by adding a recursive check.

**Comment by klimov-paul** [comment]
Resolved by commit 72ec914
