### ISSUE TITLE
Advanced Template: Functional tests fail out of the box with "ID form-signup already defined"

### ISSUE THREAD

**Issue by daniel-mc** [yiisoft/yii2#8288]
I've done a search in the issue tracker and this seems to not have been reported yet.

SignupCept, LoginCept and ContactCept all fail with the same error of `yii\base\ErrorException: Codeception\Lib\InnerBrowser::getFormFromCrawler(): ID form-* already defined`. There has been no change to the files installed by composer.

To reproduce:
* composer create-project --prefer-dist yiisoft/yii2-app-advanced test
* cd test
* ./init
* cd tests
* codecept build
* (make sure test DB exists and is up to date)
* cd codeception/frontend
* codecept run functional

The error is the same for the three tests mentioned. Sample output for SignupCest:
```
1) Failed to ensure that signup works in tests\codeception\frontend\functional\SignupCest::testUserSignup (/var/www/html/test/tests/codeception/frontend/./functional/SignupCest.php)
Couldn't click "signup-button":
yii\base\ErrorException: Codeception\Lib\InnerBrowser::getFormFromCrawler(): ID form-signup already defined

Scenario Steps:
5. I click "signup-button"
4. I am going to submit signup form with no data
3. I see "Please fill out the following fields to signup:"
2. I see "Signup","h1"
1. I am on page "/frontend/web/index-test.php?r=site%2Fsignup"

#1  Codeception\Lib\InnerBrowser->click
#2  /var/www/html/test/tests/codeception/frontend/functional/FunctionalTester.php:538
#3  /var/www/html/test/tests/codeception/frontend/_pages/SignupPage.php:25
#4  /var/www/html/test/tests/codeception/frontend/functional/SignupCest.php:55
#5  tests\codeception\frontend\functional\SignupCest->testUserSignup
#6  Codeception\TestCase\Cest->testCodecept
```

**Comment by daniel-mc** [comment]
The codeception version used is the latest one, 2.0.13.

**Comment by simogirodot** [comment]
The test fail in Yii2 advanced and in Yii2 basic.

**Comment by samdark** [comment]
That's weird. We're running these tests continuously and recent ones with Codeception 2.0.13 are passing: https://travis-ci.org/yiisoft/yii2-app-advanced/jobs/61472542

**Comment by githubjeka** [comment]
I catch it :(

Strange that codecep yesterday I had the same version, but the tests worked.

**Comment by daniel-mc** [comment]
On a different system I'm using 2.0.13 and it works fine. Might be caused by some other dependency.

**Comment by samdark** [comment]
No way to reproduce it. Closing.
