### ISSUE TITLE
JS and CSS block in yii\web\View for IDE-friendliness

### ISSUE THREAD

**Issue by petrabarus** [yiisoft/yii2#8290]
Just a suggestion,

Right now we have method registerJs and registerCss in `yii\web\View`. The usage will be something like this.

```
$view->registerJs(<<<JS
     alert('Hello World!');
JS
    );
$view->registerCss(<<<CSS
    body {
        color: red;
    }
CSS
    );
```
The downside of this method, is that it's not really IDE-friendly. Yes, I know it's not really a good reason like the issue I opened previously (https://github.com/yiisoft/yii2/issues/172).

But if I may suggest, we can do something like this

```
<?php $view->beginJs($position, $key);?>
<script>
   alert('test');
</script>
<?php $view->endJs();?>

<?php $view->beginCss($options, $key);?>
<style>
   body {color: red;}
</style>
<?php $view->endJs();?>
```

Again, I know IDE-friendliness is not really a good reason and doing above will add more overhead (removing the `<script>` and the `<style>` tag obviously). A lot of time I put a lot of JS and CSS in the widget file and view file before putting it into standalone .js and .css file. But the fact that the editor and IDE treat it like string, a lot of time it makes it hard to debug.

**Comment by mdmunir** [comment]
:+1:

**Comment by petrabarus** [comment]
Never mind, turns out I can do something like this

```
$view->registerJs($this->render('script.js'), $position, $key);
```

**Comment by cebe** [comment]
not sure what you mean with IDE friendly here. PHPStorm for example will detect and highlight javascript and css correctly if you use `<<<JS` and `<<<CSS`.

**Comment by petrabarus** [comment]
I'm using NetBeans and Sublime. But since I can use render for js and css file, I pull back this suggestion.

--
Petra Novandi Barus
http://id.linkedin.com/in/petrabarus
http://blog.petrabarus.net

Sent from Outlook for iPhone




On Wed, May 6, 2015 at 7:42 AM -0700, "Carsten Brandt" <notifications@github.com> wrote:












not sure what you mean with IDE friendly here. PHPStorm for example will detect and highlight javascript and css correctly if you use <<<JS and <<<CSS.
