### ISSUE TITLE
Numeric keys in $_GET

### ISSUE THREAD

**Issue by quantum13** [yiisoft/yii2#8291]
Numeric keys in $_GET transforms to 0-based.

For example if we load page `site.com/page?1=param1&2=param2` in action in $_GET we have:
```php
[
    0 => 'param1',
    1 => 'param2'
]
```

It happens because in Request::resolve $_GET merges with $params: https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L183

Maybe we should use + instead of array_merge in this case?

**Comment by klimov-paul** [comment]
Resolved by commit 8609311
