### ISSUE TITLE
checkboxList question

### ISSUE THREAD

**Issue by wuxing164** [yiisoft/yii2#8292]
Hi
the code like this
 <?php echo $form->field($model, 'type')->checkboxList(['2'=>'A','3'=>'B'], [])?>

how to set the item 'A' and 'B'  disabled
<input name="Form[type][]" value="2" checked="" type="checkbox" disabled="disabled">A

thank you

**Comment by wuxing164** [comment]
the html like this
"<input name="BorrowAutoForm[type][]" value="2" checked="" type="checkbox"  disabled=" disabled">"
A

**Comment by unclead** [comment]
You have to use [official forum](http://www.yiiframework.com/forum/) for asking questions. This is issue/bug tracker
