### ISSUE TITLE
Add INSERT INTO SELECT support

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#8293]
Description of syntax can be found [here](http://www.w3schools.com/sql/sql_insert_into_select.asp).

Example (taken from [here](http://stackoverflow.com/questions/30068624/how-to-write-insert-query-in-yii2)):

``` sql
INSERT INTO Customers (CustomerName, Country)
SELECT SupplierName, Country FROM Suppliers;
```

Can't find it in core. `QueryBuilder`'s `insert` method returns concatenated string with `VALUES`:

``` php
return 'INSERT INTO ' . $schema->quoteTableName($table)
    . ' (' . implode(', ', $names) . ') VALUES ('
    . implode(', ', $placeholders) . ')';
```

**Comment by cebe** [comment]
Well, w3schools is not a good resource to refer to for a specific syntax.

Need to check the manuals of all Yii supported DBMS, here are some:

- MySQL: https://dev.mysql.com/doc/refman/5.5/en/insert-select.html
- Postgres: http://www.postgresql.org/docs/current/static/sql-insert.html
- ...

**Comment by mdmunir** [comment]
How if this feature added to `batchInsert`?
```php
     * @param string $table the table that new rows will be inserted into.
     * @param array $columns the column names
     * @param array|Query $rows the rows to be batch inserted into the table
     * @return $this the command object itself
     */
    public function batchInsert($table, $columns, $rows)
    {
```

**Comment by xiongxinag** [comment]
if (is_array($info)) {..........}
    if (is_array($result) && isset($result[0])) {........}


    if (isset($info[0])) {..........}
    if (isset($result[0])) {........}

**Comment by cebe** [comment]
what do you want to say?

**Comment by JQueryBoy14** [comment]
there is an issue regarding this added function.

I tried it like **insert into ... select ... from ... where ...**

An error says **[Microsoft][ODBC Driver 11 for SQL Server]COUNT field incorrect or syntax error**

I tried removing **where** condition and it works

**Comment by samdark** [comment]
Please create a separate issue and describe everything in detail: how to reproduce the issue, what SQL is generate, what SQL is expected. Thanks.

**Comment by JQueryBoy14** [comment]
Please see #13807
