### ISSUE TITLE
Не получается использовать $app->user->can в моделе

### ISSUE THREAD

**Issue by RooTooZ** [yiisoft/yii2#8296]
PHP Fatal Error – yii\base\ErrorException
Maximum execution time of 30 seconds exceeded

Такую ошибку я получаю когда пытаюсь использовать в самой моделе.

```php
Yii::$app->user->can('ability')
```

Стоит отключить этот код и приложение работает

**Comment by githubjeka** [comment]
Не стоит проверять в модели то, что может или не может пользователь. Это может быть в контроллере или его фильтрах, или в представлениях для скрытия чего-либо.

Но ошибка скорее всего совершенно не связана с тем, что это находится в модели.

**Comment by cebe** [comment]
please paste the full stack trace of the error.

**Comment by klimov-paul** [comment]
Closed, unless more information provided.
