### ISSUE TITLE
Exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: ... /vendor/bower/jquery/dist'

### ISSUE THREAD

**Issue by agarb7** [yiisoft/yii2#8299]
I have this error on fresh stable installation of yii2. 
My steps:

1. `curl -s http://getcomposer.org/installer | php`
1. `sudo mv composer.phar /usr/local/bin/composer`
1. `composer global require fxp/composer-asset-plugin`
1. `composer require --prefer-dist yiisoft/yii2`

It's clean, all packages stable, but why?

When I do: `ln -s bower-asset bower` in `vendor/`; and all works! - Can I do this in prodation? 
Why this in clean & stable installation?

**Comment by cebe** [comment]
You need this configuration in composer.json: https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L49-L52
