### ISSUE TITLE
BaseMailer useFileTransport not working

### ISSUE THREAD

**Issue by lembadm** [yiisoft/yii2#8300]
No implementation 

https://github.com/yiisoft/yii2/blob/master/framework/mail/BaseMailer.php#L257

**Comment by klimov-paul** [comment]
What does this mean?

**Comment by lembadm** [comment]
```php
if ($this->useFileTransport) {
    $isSuccessful = $this->saveMessage($message);
} else {
    $isSuccessful = $this->sendMessage($message);
}
```

Regardless of the conditions will be executed $this->sendMessage($message);

**Comment by klimov-paul** [comment]
Everything is correct.

**Comment by cebe** [comment]
@lembadm **save**Message vs. **send**Message

**Comment by lembadm** [comment]
Sorry, this is my mistake
