### ISSUE TITLE
NumberValidator keeps whitespaces

### ISSUE THREAD

**Issue by cbhp** [yiisoft/yii2#8302]
There is a model with an attribute 'amount' and the rule:
[['amount'], 'number', 'min' => 1, 'max' => 10]

If the user submits the form with an input like '  7  ' for 'amount', $model->load(Yii::$app->request->post() will keep these whitespaces. 
My current workaround is an additional rule:
[['amount'], 'trim']

But I expected NumberValidator would remove or detect whitespaces. (BooleanValidator does.)

**Comment by cebe** [comment]
what makes you believe that boolean validator would trim whitespace? none of the validators are doing this currently.

**Comment by cbhp** [comment]
@cebe Well, BooleanValidator does an exact comparison (source: `$value == $this->trueValue || $value == $this->falseValue`) -- That's an implicit trimming ;-)

My problem is that I wanted to work with $model->amount directly without loading it again from the database (where the whitespaces are removed because of the data type), but the whitespaces make trouble.

**Comment by cebe** [comment]
> That's an implicit trimming

is is not... http://3v4l.org/46Gv7 :)

**Comment by cebe** [comment]
you should use the trim filter as you already do.

**Comment by cbhp** [comment]
Nevertheless, the BooleanValidator works as expected since it returns not the input but the defined trueValue | falseValue :D

**Comment by klimov-paul** [comment]
I can see no issue here.
