### ISSUE TITLE
yii\web\Session::getAllFlashes() has a weird example in the description

### ISSUE THREAD

**Issue by cbhp** [yiisoft/yii2#8303]
https://github.com/yiisoft/yii2/blob/8e33fbfbff881a18dca75af308b2d7c3a99621bc/framework/web/Session.php#L674

The current example for using Yii::$app->session->getAllFlashes() is a bit weird.
- Possible XSS
- Not supporting arrays (But: key => message | [message1, message2])

I suggest changing the example to:
```
foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
	$msg = is_array($message) ? implode(PHP_EOL, $message) : $message;
	echo '<div class="alert alert-' . $key . '">' . nl2br(Html::encode($msg)) . '</div>';
}
```

**Comment by cebe** [comment]
the thing about array is already noted:

> Note that if you use [[addFlash()]], `$message` will be an array, and you will have to adjust the above code.

Agree that it should be HTML encoded.

**Comment by cebe** [comment]
hm.. but it could be that you want to add a link to your flash messages so I prefer leaving it as is. 

Html::encode should be called when the message is created.
