### ISSUE TITLE
Unexpected character in \vendor\yiisoft\yii2\i18n\Formatter.php

### ISSUE THREAD

**Issue by cbhp** [yiisoft/yii2#8305]
I use Optimistic Locks (yii\db\StaleObjectException).

Here is an example of the problematic controller action:

```
public function actionPublish($id)
{
    $model = $this->findModel($id);
    $model->scenario = 'publish';

    if ($model->load(Yii::$app->request->post())) {

        $model->published = new yii\db\Expression('NOW()');

        try {
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } catch (yii\db\StaleObjectException $e) {
            Yii::$app->session->setFlash('danger', 'Since your last view there was a change. Here you see your last edits for saving to clipboard.');
        }
    }

    return $this->render('view', ['model' => $model]);
}
```

view.php:

```
<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        // ...
        'published:datetime',
        // ...
    ],
]) ?>
```

If no changes has been made meanwhile, saving the model succeeds. 

If there was a change, the StaleObjectException is raised (correctly). But the view breaks:

```
Invalid Parameter – yii\base\InvalidParamException 'NOW()' is not a valid date time value: DateTime::__construct(): Failed to parse time string (NOW()) at position 3 ((): Unexpected character
in \vendor\yiisoft\yii2\i18n\Formatter.php at line 639
```

**Comment by cebe** [comment]
This is because you have a TimestampBehavior which sets a column value for the updated timestamp to yii\db\Expression('NOW()'). Normally this would be solved by calling $model->refresh() but this means your changes to the models attributes are lost.

**Comment by cebe** [comment]
something like `$model->updated = $model->getOldAttribute('updated');` should work. Replace `updated` with the name of the timestamp column.

**Comment by cbhp** [comment]
Thank you for the advice. 
Is it an expected behavior of the Formatter (`'published:datetime'`) to raise an exception if the value could not be parsed?

**Comment by cebe** [comment]
yes

**Comment by schmunk42** [comment]
@cebe The `oldAttribute` workaround does not work (for me), after updating a record I get always `NOW()` as a string.

I think a solution might be to create a custom expression and override `__toString()`

**Comment by cebe** [comment]
> [addon] In my case I accidentally rendered a the view view after update, instead of redirecting to the view action.

the solution in that case would be to call `$model->refresh();` to get the values stored in the database.
