### ISSUE TITLE
Mailer not wrap all method swiftmailer

### ISSUE THREAD

**Issue by zinzinday** [yiisoft/yii2#8307]
```
Yii::$app->mailer->compose('view')->setPriority(5);
```
```
Calling unknown method: yii\swiftmailer\Message::setPriority()
```
see: [priority](http://swiftmailer.org/docs/messages.html#setting-the-message-priority)

Please review and addition method,
i want to use yii2 wrap Mailler and not direct from @vendor/swiftmailer

**Comment by cebe** [comment]
you can use [getSwiftMessage()](http://www.yiiframework.com/doc-2.0/yii-swiftmailer-message.html#getSwiftMessage%28%29-detail) to access the switfmailer message object.

**Comment by zinzinday** [comment]
Thanks @cube
