### ISSUE TITLE
Camel Case Controller name causes InvalidRouteException

### ISSUE THREAD

**Issue by zhangyf** [yiisoft/yii2#8308]
PHP version: 5.5.15
Yii version: 2.0.3

I have a custom controller named GetUserInfoController in GetUserInfoController.php and I have a url route rule : **'g' => getUserInfo/action-id**. But when visited the url **my_host_name/g** I receive an error of 404. I found InvalidRouteException in log of framework.

Then I read the code of framework.

I found that in function createControllerByID() of base/Module.php there is code

    if (!preg_match('%^[a-z][a-z0-9\\-_]*$%', $className)) {
           return null;
    }

it means my controller ID 'getUserInfo' cannot match the regular expression **'%^[a-z][a-z0-9\\-_]*$%'**, because there a 'U' and 'I' in controller ID. It returns null, so creating controller failed. 

Could the regular expression be **'%^[a-z][a-zA-Z0-9\\-_]*$%'**? 

The exception log is below:

    exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "getUserInfo/get".' in /home/xxxxx/vendor/yiisoft/yii2/base/Module.php:461

**Comment by klimov-paul** [comment]
#7557
