### ISSUE TITLE
[FR] yii\web\Request::$routeParams

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#8309]
Please see [angular $routeParams](https://docs.angularjs.org/api/ngRoute/service/$routeParams).
For now, we can access `$routeParams` via `$_GET` or `Request::get()`, but this value is also provided from original `$_GET`. Example:
We have url rule like this
```php
'product' => 'product/index',
'product/<id>' => 'product/index',
```
If we access this url as 'product/2' and 'product?id=2' it will be treated as same behavior. I want this will be treated as diferent behavior.
I know this is rare rare case. But, IMO is a good point to have that.
My proposal,change this lines https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L182-L185
```php
            list ($route, $params) = $result;
            $_GET = $_GET + $params; // change order
            $this->routeParams = $params;

            return [$route, $_GET];
```

**Comment by klimov-paul** [comment]
Duplicates #254
