### ISSUE TITLE
Getting unknown property error on Yii2 model filter

### ISSUE THREAD

**Issue by abdulahad** [yiisoft/yii2#8310]
On making a join in yii2 model and apply filter on it, gives me an error:

Getting unknown property: common\models\Application::

<pre>
$filters=(object)json_decode($_GET['filters']);
    $model = Application::find()->distinct()
            ->join('LEFT JOIN','profile_detail','profile_detail.account_id=application.account_id')
            ->where(['post_id'=>62]);
    $model->orFilterWhere(['like','profile_detail.institude_name',$filters->institude]);
    return $model->all();
</pre>

PS: On writing direct query instead of model its work fine. Also if i remove the filter it also give the result, with the join.

**Comment by klimov-paul** [comment]
Please, provide a stack trace.

**Comment by abdulahad** [comment]
Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: common\models\Application::

1. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Component.php at line 143
2. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\db\BaseActiveRecord.php – yii\base\Component::__get('') at line 246
3. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Model.php – yii\db\BaseActiveRecord::__get('') at line 926
4. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\db\ActiveQuery.php – yii\base\Model::offsetGet(false) at line 263
5. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\db\ActiveQuery.php – yii\db\ActiveQuery::removeDuplicatedModels([common\models\Application, common\models\Application, common\models\Application, common\models\Application]) at line 220
6. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\db\Query.php – yii\db\ActiveQuery::populate([['application_id' => '2', 'post_id' => '62', 'account_id' => '19', 'fullname' => 'saad', ...], ['application_id' => '3', 'post_id' => '62', 'account_id' => '20', 'fullname' => 'saad', ...], ['application_id' => '4', 'post_id' => '62', 'account_id' => '21', 'fullname' => 'saad', ...], ['application_id' => '5', 'post_id' => '62', 'account_id' => '22', 'fullname' => '', ...]]) at line 207
7. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\db\ActiveQuery.php – yii\db\Query::all(null) at line 130
8. in C:\xampp\htdocs\...\frontend\controllers\PostController.php – yii\db\ActiveQuery::all() at line 165
9. frontend\controllers\PostController::actionGetFilteredApplicants()
10. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\InlineAction.php – call_user_func_array([frontend\controllers\PostController, 'actionGetFilteredApplicants'], []) at line 55
11. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Controller.php – yii\base\InlineAction::runWithParams(['r' => 'post/get-filtered-applicants', 'filters' => '{"isPending":true,"isRejected":t...']) at line 151
12. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Module.php – yii\base\Controller::runAction('get-filtered-applicants', ['r' => 'post/get-filtered-applicants', 'filters' => '{"isPending":true,"isRejected":t...']) at line 455
13. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\web\Application.php – yii\base\Module::runAction('post/get-filtered-applicants', ['r' => 'post/get-filtered-applicants', 'filters' => '{"isPending":true,"isRejected":t...']) at line 83
14. in C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Application.php – yii\web\Application::handleRequest(yii\web\Request) at line 375
15. in C:\xampp\htdocs\...\frontend\web\index.php – yii\base\Application::run() at line 18

**Comment by klimov-paul** [comment]
What does your `common\models\Application::primaryKey()` return?

**Comment by abdulahad** [comment]
its return <b>application_id</b>

**Comment by klimov-paul** [comment]
It should return array.

**Comment by abdulahad** [comment]
yes, its an empty array

**Comment by klimov-paul** [comment]
What does
```
var_dump(common\models\Application::primaryKey());
```
outputs?

**Comment by abdulahad** [comment]
array(0) { }

**Comment by klimov-paul** [comment]
Duplicates #7780

**Comment by abdulahad** [comment]
Now, after adding the primary key in this model then it give an error

Trying to get property of non-object

<pre>0: "#0 C:\xampp\htdocs\...\api\modules\v1\controllers\PostController.php(316): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 316, Array)"
1: "#1 [internal function]: api\modules\v1\controllers\PostController->actionGetFilteredApplicants()"
2: "#2 C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)"
3: "#3 C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)"
4: "#4 C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('get-filtered-ap...', Array)"
5: "#5 C:\xampp\htdocs\...\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('v1/post/get-fil...', Array)"
6: "#6 C:\xampp\htdocs\...\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))"
7: "#7 C:\xampp\htdocs\...\api\web\index.php(17): yii\base\Application->run()"
8: "#8 {main}"</pre>

**Comment by abdulahad** [comment]
Thanks @klimov-paul

**Comment by HASSAANALVI20** [comment]
klimov-paul  sir kindly tell me  where the put this line var_dump(common\models\Application::primaryKey()); 

i have same error

**Comment by HASSAANALVI20** [comment]
@klimov-paul sir kindly tell me where the put this line var_dump(common\models\Application::primaryKey());

i have same error
