### ISSUE TITLE
Default controller for subdirectory

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#8314]
Is it possible to define a default controller for a subdirectory?

Example: Someone wants to the admin-zone of a page `page.example/admin`. The admin-zone has more than one controller, which are under a subdirectory, so he gets a 404.
* SiteController
* admin
 * UserController
 * SettingsController

My first approach was to create a `AdminController` on the root.
* SiteController
* `AdminController`
* admin
 * UserController
 * SettingsController

But this leads to the problem that all controllers in the `admin` subdirectory can't be reached, because everything like `page.example/admin/user` will now be handled by the `AdminController`.

**Comment by cebe** [comment]
why not create a url rule: `'admin' => '/admin/settings/index'`

**Comment by thejahweh** [comment]
Thanks problem solved, that was easy :tada:
