### ISSUE TITLE
Using relation objects as parameters in ActiveQuery functions

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#8321]
Currently, `ActiveQuery` functions like `joinWith()` take relation names as parameters which requires an existing function to refer to by that name. It would be more flexible and powerful to be able to pass relations as `ActiveQuery` objects too besides name. In such case, relations could be newly created objects or existing relations modified as required.

For example, assume the following situation:
- We have a `Customers` model with a `has-many` relation called `orders` to `Orders` model.
- `Orders` overrides `find()` to add a default sorting via `orderBy('order_date')`.
- `Orders` is referred to via the relation as in `$customers = Customer::find()->joinWith('orders')`.

In such case, the resulting SQL statement would have `ORDER BY "order_date"` and there is no parametrized way to remove this part if not required in this context (please let me know if I've missed something here). In fact it would cause an error because the `orders` table names does not exist. The related model becomes read-only in this situation, you can add settings to it but can not modify it to suit the the context if required.

If `joinWith()` accepts relation objects, this could be achieved by getting the relation via `$relation = $customers->getRelation('orders')`, clearing the `orderBy` property of `$relation`, then passing the relation as an object as `joinWith($relation)`. This might not be the best example but it explains the main idea of flexibility when dealing with relations. This may even be necessary if the developer does not have control over the related model such as in using 3rd-party extensions (e.g. user management) whose could should not be touched.

**Comment by unclead** [comment]
As i understood you want to modify relation query and this case is described in a guide
```
$customers = Customer::find()->joinWith([
    'orders' => function ($query) {
        $query->andWhere(['>', 'subtotal', 100);
    },
])->with('country')
    ->all();
```
Did i miss something?

**Comment by YasserHassan** [comment]
@unclead yes, thank you for mentioning this. I stand corrected about the "read-only" part in my post. This way, the benefit of my suggested approach is the ability to create new relations on-the-fly conveniently by using relation objects instead of names referring to functions. However, I don't think there's enough added value of such enhancement to deserve its implementation unless there are other developers who'd find it useful.

**Comment by YasserHassan** [comment]
The remaining benefit would have limited application so I'm closing this issue.
