### ISSUE TITLE
yii2 grid view filter and active form action conflict

### ISSUE THREAD

**Issue by saifabbasi** [yiisoft/yii2#8323]
i have an active form on a page with a different action and a grid on same page which filter with the help of defined filter url, if i remove form filters work correctly, if form is added, filter start posting to form action. Any suggestions, solution?

**Comment by hatef-madani** [comment]
I have the same problem it will be appreciated if you could share the solution, Thanks a lot!

**Comment by saifabbasi** [comment]
i have closed form tag before grid start, and the problem was resolved, earlier it was not working because i was opening form tag outside a div and closing inside div, which was not identified by browser, when i took start and ending tag inside div and before or after grid it is working. Also i have explicitly associated grid filter url with its attribute.

**Comment by SilverFire** [comment]
Failed to reproduce. I'm closing the issue unless further information provided.
