### ISSUE TITLE
rbac: assign not only role

### ISSUE THREAD

**Issue by dizews** [yiisoft/yii2#8324]
Hello.

In a description of ```ManagerInterface::assign``` I can assign only role not a permission. I think it will be useful if we can give to user more permissions without to create a special role with one permission.

what do you think?

**Comment by cebe** [comment]
well, this is considered bad practice... A user is granted a permission because of his function on a platform which is represented as the role. By assigning permissions directly you are likely to loose overview over who can do what.

**Comment by dizews** [comment]
@cebe why do I loose overview?
in the user manager interface I can see user's roles and permissions

**Comment by cebe** [comment]
I mean you will get multiple users all with different kind of permission combinations. Having a defined set of rules you can assign makes it easier to manage.

**Comment by dizews** [comment]
thanks for your explanations.
