### ISSUE TITLE
Feature request: Dependency Injection Container - support for multiple resolution

### ISSUE THREAD

**Issue by mikolaj-milewski** [yiisoft/yii2#8325]
Hi,

Many DI/IoC containers allows to register multiple implementations of single interface and to resolve them at once. Here's an example:

http://autofac.readthedocs.org/en/latest/resolve/relationships.html#enumeration-ienumerable-b-ilist-b-icollection-b

I do heavily use that feature to implement modularity and plugin-ish scenarios.

I do realize that PHP lacks strong-type capabilities of, f.e., C#, but I think it is possible to at least emulate that feature even for DI container as simple as Yii's. What do you think about something like that?:

$db_connections = $container->multipleGet('/db_.*/');

That won't support injection, but will greatly widen scope of scenarios that container can be used in.

**Comment by samdark** [comment]
What's your use case for it?

**Comment by mikolaj-milewski** [comment]
Plenty of them, just to name a few most common for me:
- dynamic registration of multiple databases/services/name-it to integrate with
- extending app functionality with in-module-registered plugin classes; module's availability depends on user account level / pricing plan
- registering different logging backends

In strong-typed world, multiple resolution is common feature of IoC containers.

**Comment by samdark** [comment]
Not going to implement that. See https://github.com/yiisoft/yii2/issues/8911#issuecomment-180974335
