### ISSUE TITLE
EVENT_BEFORE_ACTION does not handle Exceptions

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#8326]
I have a bootstrap-class, which triggers on `Application::EVENT_BEFORE_ACTION` and throws `NotFoundHttpException`.
```php
public function bootstrap($app)
{
	$app->on(Application::EVENT_BEFORE_ACTION, [$this, 'initLanguage']);
}
```

The problem is, that it does not show the normal 404 error page.

If I change the trigger event to `Application::EVENT_BEFORE_REQUEST` it shows the normal error page.

**Comment by klimov-paul** [comment]
This is expected as "normal 404 error page" is rendered by controller action, which also trigger the same event and throws the same exception.

**Comment by thejahweh** [comment]
So I cannot send a 404 error page or do anything about that ugly blank page with the status code 200?

**Comment by cebe** [comment]
No, looks like there is something wrong here.

**Comment by cebe** [comment]
I got it reproduced. There are two problems here:

1. the fact that you throw a 404 error in BEFORE_ACTION results in another 404 error being thrown in the beforeAction call that comes for the triggered errorAction. An exception thrown while handling an error will result in a fallback that just prints out the exception message and exits.
2. in this fallback there is a call to set the http response code to 500 but it somehow seems to have no effect: https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L117

**Comment by cebe** [comment]
related to #7571, the [fix](https://github.com/yiisoft/yii2/commit/b6a591c720046f36688e4be4ed8d41853a01abe3) does not seem to have the expected effect...

**Comment by cebe** [comment]
Fixed, thanks for reporting!
