### ISSUE TITLE
joinWith not respected.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#8327]
Nested joinWith statements are not being respected by Yii AR. Executing the query via AR, by doing $query->all() instead runs a separate query to get the companies.

       $query = Post::find()->innerJoinWith(['author' => function($q) {
         return $q->joinWith('companies');
      }]);

Printing SQL via $query->createCommand()->sql will give me the expected query: 

        SELECT .. FROM `post` 
        INNER JOIN `author` ON...
        LEFT JOIN `company` ON ..

**Comment by SamMousa** [comment]
Okay, further research: 
- In both cases it does the join.
- When using AR, after the join it does another query to get the related models..

**Comment by klimov-paul** [comment]
Duplicates #4631
