### ISSUE TITLE
ActiveRecord behaviors()

### ISSUE THREAD

**Issue by sjaakp** [yiisoft/yii2#8328]
Documentation says 'A behavior configuration can be either a string specifying the behavior class or an array of the following structure ...'.

However, I found that this didn't work for me (times not updated, TimestampBehavior::getValue() never called):

    class Article extends ActiveRecord
    {
        public function behaviors() {
            return [
                TimestampBehavior::className(),
            ];
        }
        ...
    }

while this just works fine:

    class Article extends ActiveRecord
    {
        public function behaviors() {
            return [ 
                [ 
                    'class' => TimestampBehavior::className(),
                ]
            ];
        }
        ...
    }

**Comment by klimov-paul** [comment]
Unable to reproduce. Unit test for `TimestampBehavior` uses first example declaration successfully:
https://github.com/yiisoft/yii2/blob/master/tests/framework/behaviors/TimestampBehaviorTest.php#L102
