### ISSUE TITLE
Enh: extract messages for specified language

### ISSUE THREAD

**Issue by vchenin** [yiisoft/yii2#8329]
Because translator work mostly with one language, it should be better have ability extract messages for specified language easier than generate new config.php and then edit it.

After this patch translator can use default config.php "from the box" like below:
```
./yii message/extract messages/config.php langCode
```

Patch code:
```php
--- a/framework/console/controllers/MessageController.php
+++ b/framework/console/controllers/MessageController.php
@@ -76,9 +76,12 @@ class MessageController extends Controller
      * @param string $configFile the path or alias of the configuration file.
      * You may use the "yii message/config" command to generate
      * this file and then customize it for your needs.
+     * @param string $specifiedLanguage the language code.
+     * This parameter override 'languages' array content
+     * from $configFile with one specified language code.
      * @throws Exception on failure.
      */
-    public function actionExtract($configFile)
+    public function actionExtract($configFile, $specifiedLanguage = NULL)
     {
         $configFile = Yii::getAlias($configFile);
         if (!is_file($configFile)) {
@@ -93,6 +96,9 @@ class MessageController extends Controller
             'format' => 'php',
             'ignoreCategories' => [],
         ], require($configFile));
+        if (!empty($specifiedLanguage)) {
+            $config['languages'] = [ $specifiedLanguage ];
+        }
 
         if (!isset($config['sourcePath'], $config['languages'])) {
             throw new Exception('The configuration file must specify "sourcePath" and "languages".');
```

**Comment by klimov-paul** [comment]
I am usure about this. There are plenty other options for message extration. If add this as a parameter, then waht about 'sourcePath', 'sort', 'format' ,'messagePath' and so on? Justification for ability of setup via command optnion an be found for each of them.
Following this path we should either allow all parameters be overridden via command options or leave everything as it is now.

**Comment by klimov-paul** [comment]
> Because translator work mostly with one language, it should be better have ability extract messages for specified language easier than generate new config.php and then edit it.

I don't get it. If you have an interpreter (translator) as a separated member of the project team, why he ever runs 'message' command? In such case this command should be run by developer and generate blank translation files. Then you point your interpreter to thier source dir and say 'here you go translate these'.

**Comment by vchenin** [comment]
@klimov-paul I agree that it's better to leave everything as it is now for clarity of design.
So let close issue.

**Comment by cebe** [comment]
> then waht about 'sourcePath', 'sort', 'format' ,'messagePath' and so on?

these are pretty fix for the whole application and when they change, they change for all languages.

The use case for adding lanuage is that if you want to update one language without touching other language files you always have to revert changes to other languages.
You see the problem if you run the message command on the framework messages for example. If I want to update the messages for german, all other language files get updated and I have to revert them before committing my changes.

**Comment by vchenin** [comment]
@cebe Yes It Is!
The main idea of this feature is to simplify process of message translation without need to do extra operations (generate and edit config, revert changes for other languages).
I agree with @klimov-paul that it's better for framework architecture to implement full-feature command-line interface, but in this case such implementation adds undesired and superfluous complexity and override the main idea of this feature.
The most popular scenario for message translation is like:
```
get msgs for specified lang -> modify -> save -> push to repo
```
My proposition cover this scenario, in all other cases it's always possible to generate and edit config.php.
I think this is nice tweak and personally cast a vote for this feature.
