### ISSUE TITLE
jQuery UI Dialog - Javascript not formatted correctly

### ISSUE THREAD

**Issue by osCMattiFinn** [yiisoft/yii2#8330]
I have a simple dialog, with the buttons parameter set as follows:

'buttons' => [[ 'text' => 'test', 'click' => 'js:function(){alert("test")}']]

This fails with the following error (Firebug):

TypeError: click.apply is not a function
click.apply( that.element[ 0 ], arguments );

This is because the button Javascript function is wrapped in quotes:

"buttons":[{"text":"Yes","click":"js:function(){alert(\"test\")}"}]});

My understanding was that Yii would detect the 'js:', remove it and leave the following code without quotes.

**Comment by davidjeddy** [comment]
Confirm this issue.

Dialog::begin([
	'id'           => 'dlgEditForum',
	'clientOptions'=> [
		'autoOpen' => false,
		'buttons'  => [
			['text' => 'Cancel'), 'click' => 'function(){cancel( $( this ).dialog( "close" ); )}'],
		],
		'modal'    => true,
		'show'     => 'fade',
		'title'    => 'Edit',
		'width'    => 800,
	],
]);

The Dialog opens,  when pressing the 'close' button I receive the same error as @osCMattiFinn 

Please advise.

**Comment by osCMattiFinn** [comment]
It must be done like this:

'buttons' => [
			[ 'text' => 'Test', 'click' => new JsExpression('function(){alert("test')]]

**Comment by davidjeddy** [comment]
Thank you.
Correct syntax:

use yii\web\JsExpression;
...
[
   [ 'text' => 'Test', 'click' => new JsExpression('function(){ alert("test") }') ],
]
