### ISSUE TITLE
yii\rest\ActiveController ignores `Accept-encoding: gzip` when `Accept: application/xml`

### ISSUE THREAD

**Issue by hbschr** [yiisoft/yii2#8331]
i was building a rest api (hopefully) following the guide.
`https://<foo>/device` gives the 'index'-action. comparing the two requests:
```
curl -i https://<foo>/device -H "Accept-encoding: gzip" -H "Accept:application/json" 
curl -i https://<foo>/device -H "Accept-encoding: gzip" -H "Accept:application/xml" 
```
gives gzipped json, but uncompressed xml.

can anyone reproduce this?

**Comment by marcomarsella** [comment]
In fact I have the same problem but in my case XML is compressed while JSON is not. Using Yii 2.0.8

Please help!

**Comment by cebe** [comment]
can you provide more info about the server environment? gzip is not handled by yii but by the webserver.

**Comment by marcomarsella** [comment]
Wow! Thank you for responding and pointing me to the right direction!

I fixed the Apache configuration and it now works just fine.

Thank you very much!

M

**Comment by Forin** [comment]
Marcos solution: http://www.yiiframework.com/forum/index.php/topic/71032-rest-api-returning-compressed-xml-but-not-json/page__pid__299932
