### ISSUE TITLE
docs: why extend class for filter?

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#8344]
https://github.com/yiisoft/yii2/blob/master/docs/guide/output-data-widgets.md#filtering-data
there model class is extended with additional function. why to do it? i find it easier to do it just in controller and scenario

controller

	public function actionIndex()
	{
		$filtered = new Books(['scenario'=>'filter']);
		$filtered->load(\Yii::$app->request->get());
		$filtered->validate();
		$dataProvider = new ActiveDataProvider([
			'query' => Books::find()->andFilterWhere(['like', 'title', $filtered->title]),
			'pagination' => [
				'pageSize' => 20,
			],
		]);
		return $this->render('index', ['dataProvider'=>$dataProvider, 'filterModel' => $filtered]);
	}

model

	public function rules()
	{
		return [['title', 'integer', 'on' => 'filter'],]
	}

it works the same way w/o extra class hassle.

**Comment by samdark** [comment]
You can do it like you've proposed, it's a personal choice about how to handle things. Separate class introduced mainly not to put too much stuff into the model itself.
