### ISSUE TITLE
Params Yii2-Problem.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#8346]
Hi, i have a question I sought documentation and I have found nothing and do not know if it's a bug,

My Code:

params.php:

    <?php
        return [
        'adminEmail' => 'example@gmail.com',
     ];

Views For Example (index):

    yii::$app->params['menu'] = 'Forum';

    var_dump(yii::$app->params);

   Show: 

    array(2) { ["adminEmail"]=> string(17) "example@gmail.com"  ["menu"]=> string(5) "Forum" }

Other View for example (view):

    var_dump(yii::$app->params);

    Show:
   
    array(1) { ["adminEmail"]=> string(17) "example@gmail.com" 

    Params[menu] is lost, this is normal,

Thks,

Wilmer.

**Comment by cebe** [comment]
if you set it in another request it will not persist if you mean that. If you want things to persist over requests you have to store it in session.
