### ISSUE TITLE
Array value in Request::getQueryParam

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#8351]
Select2 send `search['term']=123123`:

```
/index.php?r=site%2Fnode-list&search%5Bterm%5D=123123
```

My code is bad:

```php
        if (Yii::$app->request->getQueryParam('search') === null) {
            throw new BadRequestHttpException('Не корректный запрос');
        }

        $searchModel = new ElasticSearch();
        $dataProvider = $searchModel->search(
            [
                'address' => Yii::$app->request->getQueryParam('search')["term"],
                'number' => Yii::$app->request->getQueryParam('search')["term"],
            ]
        );
```

Three problems:
- `getQueryParam('search["term"]')` return null
- `getQueryParam('search%5Bterm%5D')` return null
- For future getQueryParam('search')["term"] may return PHP Notice. Need check of `isset(Yii::$app->request->getQueryParam('search')["term"])`

:(

**Comment by cebe** [comment]
```
        if (($search = Yii::$app->request->getQueryParam('search')) === null) {
            throw new BadRequestHttpException('Не корректный запрос');
        }

        $searchModel = new ElasticSearch();
        $dataProvider = $searchModel->search(
            [
                'address' => ArrayHelper::getValue($search, 'term'),
                'number' => ArrayHelper::getValue($search, 'term'),
            ]
        );
```

**Comment by githubjeka** [comment]
Ok it is fix for my third problem. And first or second?

**Comment by githubjeka** [comment]
```php
if ($search = ArrayHelper::getValue(Yii::$app->request->getQueryParam('search'),  'term') === null) {
    throw new BadRequestHttpException('Не корректный запрос');
}
//...
 $dataProvider = $searchModel->search(['address' => $search,'number' => $search]);
}
```
Hmm instead  :)
```php
isset($_GET['search']['term'])
```

**Comment by TerraSkye** [comment]
it would be nice to have the ability to acces nested params by doing  request->getQueryParam('search.term')

Pixel and tonic do it in theur HttpRequestService.
<code>
private function _getParam($name, $defaultValue, $data)
	{
		// Do they just want the whole array?
		if (!$name)
		{
			return $this->_utf8AllTheThings($data);
		}

		// Looking for a specific value?
		if (isset($data[$name]))
		{
			return $this->_utf8AllTheThings($data[$name]);
		}

		// Maybe they're looking for a nested param?
		if (strpos($name, '.') !== false)
		{
			$path = explode('.', $name);
			$param = $data;

			foreach ($path as $step)
			{
				if (is_array($param) && isset($param[$step]))
				{
					$param = $param[$step];
				}
				else
				{
					return $defaultValue;
				}
			}

			return $this->_utf8AllTheThings($param);
		}

		return $defaultValue;
	}
</code>

**Comment by Alex-Code** [comment]
https://github.com/yiisoft/yii2/issues/8100

**Comment by TerraSkye** [comment]
didnt see that one! my bad.
