### ISSUE TITLE
Why are you implement BC in 2.0.x releases?

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#8355]
For example.
Using Bootstrap Collapse. After update from 2.0.1 to 2.0.4
`
Invalid Configuration – yii\base\InvalidConfigException
The "content" option should be a string or array.
`
it shouldnt contain any bcs only fixes, new features an enhancements or am i wrong?

And the next problem if youre going to implement a BC why not note it in https://github.com/yiisoft/yii2/blob/master/framework/UPGRADE.md ?

**Comment by samdark** [comment]
We're trying to keep BC but sometimes breaking changes are getting in (usually accidentally). If it's not mentioned in upgrade for either framework or extension it could be considered as documentation bug and should be fixed.

**Comment by ItsReddi** [comment]
thats the commit 
https://github.com/yiisoft/yii2-bootstrap/commit/599d60c376eaf9dedac0b8b5f48099beabefbe5b#diff-e2c8b04a3abee6260473c9f21e76bf7eL138

$content cant be an object anymore like an for example ActiveField.

**Comment by samdark** [comment]
According to docs it was never meant to. It specifies `string` as type.

**Comment by ItsReddi** [comment]
yeah i saw. but it was working. nevermind than maybe make an enhancement out of this issue.
like 
```php
if (is_string($item['content']) || is_object($item['content'])) {
                $content = Html::tag('div', $item['content'], ['class' => 'panel-body']) . "\n";
            } elseif (is_array($item['content'])) {
                $content = Html::ul($item['content'], [
                    'class' => 'list-group',
                    'itemOptions' => [
                        'class' => 'list-group-item'
                    ],
                    'encode' => false,
                ]) . "\n";
                if (isset($item['footer'])) {
                    $content .= Html::tag('div', $item['footer'], ['class' => 'panel-footer']) . "\n";
                }
            } else {
                throw new InvalidConfigException('The "content" option should be a string, array, or object.');
            }
```

**Comment by samdark** [comment]
Yep. That would work.
