### ISSUE TITLE
Microdata encoding with renderTagAttributes()

### ISSUE THREAD

**Issue by PELock** [yiisoft/yii2#8363]
How to encode itemscope in Html::a()

`<a href="..." itemscope itemtype="...">`

renderTagAttributes() doesn't allow single tag items (I can sneak them in a single string, but I don't think it should be used), but Microdata is taking the web and it's everywhere, Yii2 should follow the trends and allow such simple things to be done without too much trouble.

Right now I'm rebuilding the Breadcrumbs widget to support the microdata and it's ugly without the support of native Yii2 functions.

**Comment by samdark** [comment]
You mean `itemscope`? Have you tried specifying attribute as `'itemscope' => true`?

**Comment by PELock** [comment]
Ok, I dug into the base classes and found the problem on my side, sorry for the confusion.
