### ISSUE TITLE
Default url parsing logic does not enforce trailing slash or not

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#8370]
If you have actionIndex in SiteController, `site/index` and `site/index/` both work. But if you create a url rule, e.g.:

`'foo/<action:\w+>' => 'site/<action>'`

then only `foo/index` will work, because of #1807.

**Comment by cebe** [comment]
duplicate of #7670?

**Comment by nkovacs** [comment]
No. `site/index/` should not work either, for the same reasons as #1807, but that would break BC.
