### ISSUE TITLE
pjax: one container - two different actions

### ISSUE THREAD

**Issue by szewciu** [yiisoft/yii2#8374]
I have following issue: I need to use exactly one pjax container for two different actions.

To be exact, one of them is used for reloading gridview after form submitted. The second one is required to fill in form with data of model user'd like to edit. Even though in the first case script works correctly, the second one causes filling in right form and also replaces gridview to form.

Any suggestions how to solve this problem?

**Comment by klimov-paul** [comment]
Either both your actions should render the full HTML, containing both form and grid, or you should use different containers.
