### ISSUE TITLE
CRUD generate does not set default access rule

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#8376]
in Yii 1.x, controller generated by CRUD has default Access Filter Rule already in place. In Yii 2.x, controller does not have Access Filter Rule. I think it should has some default Access Filter Rule for 'index', 'view', 'create', 'update' and 'delete'

**Comment by cebe** [comment]
could be a checkbox option.

**Comment by YaroslavShapoval** [comment]
What do you think about such as [this](https://jsfiddle.net/shapoval/nxpnpctj/embedded/result/) style for the access to actions?
