### ISSUE TITLE
Conditional statement - does not always trigger a new validation

### ISSUE THREAD

**Issue by Smiggel** [yiisoft/yii2#8382]
Hello,

I noticed that the conditional statement is not always working correctly on the client side with Yii2.

For example: create a statement where the attribute year in a model should be required when a name is not empty. Make a form and then add the two fields. Now, fill the name and go to the year. Leave the field without entering data. The validator says the field is required according to the rule. That's good.
Now empty the name field and go to the year field. Leave the field again without entering data. The validator is now not triggered and so the message that it is required remains there, when it is actually now not required anymore.

Perhaps it would be better to trigger the validator on "focusout" instead of on a change.

Best regards.

**Comment by cebe** [comment]
related to #6744

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/88241f24f37498ffcd99d25248edebf2f12ed9e5
