### ISSUE TITLE
Explode in EachValidator

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#8391]
Have an idea to add property `explode` to the `EachValidator`, which will call `StringHelper::explode()` if the validating value is a string.

The property may be
 - `true` - call `StringHelper::explode()` without additional params
 - `string` - use string as a delimiter to call `StringHelper::explode()`
 - `array` - use the array in `call_user_func_array` to call `StringHelper::explode()`
 - `false` - do not try to explode a string

For example, when you want to create an input, suitable for multiple values (like emails), you can easily validate it with `EachValidator`:

```php
 ['emails', 'each', 'rule' => 'email', 'explode' => true]
```

The same may be done with two validation records like:
```php
[
   ['emails', 'filter', 'filter' => function ($value) {
       return StringHelper::explode($value);
   }],
   ['emails', 'each', 'rule' => 'email']
]
```
so i'm not sure, that my idea is good. What do you think about this?

**Comment by klimov-paul** [comment]
It is better to perfrom `explode` using `FilterValidator` rather then overcomplicate `EachValidator`.
