### ISSUE TITLE
compare date validation is not working

### ISSUE THREAD

**Issue by ajkosh** [yiisoft/yii2#8394]
if i am using this in my model rules
 ```[['end_date'], 'compare', 'compareAttribute'=>'start_date', 'operator'=>'>=', 'skipOnEmpty'=>true,
             'message'=>'{attribute} must be greater than {compareValue} '],```
then it is only comparing with date not with month or year
if start_date is 01-05-2014 and end_date is  01-05-2015,, it is giving error end_date must be greater than start_date
the i changed to ajax validation ,write my own function
```code
    public function validateDate($attribute, $params) {
      st= strtotime( $this->start_date);
      $et=strtotime( $this->end_date);
      if($et<$st){
        $this->addError($attribute, Yii::t('app', 'end date must be greater than start date'));
      }
    }
```

with ajax it is working but i cant use ajax because i submitting my form with method get,so on get method ajax validation is not working.

**Comment by klimov-paul** [comment]
Dates if such format as '01-05-2014' will be compare as a plain strings. So there is not surprise you have unexpected result.
If you wish to perfrom correct comparision, you should consider to apply `DateValidator` first and convert date values into timestamps before actual comparision.

**Comment by ajkosh** [comment]
@klimov-paul but why ajax validation is not working if form is submitting via get method

**Comment by ajkosh** [comment]
there is no docs about compare date so plz it will helpful if you give example

**Comment by klimov-paul** [comment]
> why ajax validation is not working if form is submitting via get method

If you have problem with ajax validation - open a separated issue for it, but first search for existing ones.

> there is no docs about compare date so plz it will helpful if you give example

Please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by ajkosh** [comment]
i asked issue lots of time non one reply because there is no docs only who are at master level they can resolve otherwise it is not possible to get your answer or move to laravel

in december 2014 i asked this question i did nt get answer and today i posted this issue again here is link
http://www.yiiframework.com/forum/index.php/topic/63799-pagination-is-not-working-with-arraydataprovider/
now u tell me wat to do if no one is replying,that why every one is asking question here
