### ISSUE TITLE
BaseOAuth::sendRequest  - Can't send raw content

### ISSUE THREAD

**Issue by SnippLeaf** [yiisoft/yii2#8396]
Problem is with **BaseOAuth** and it's methods `api()` and `sendRequest()`.
 Everything was ok until I tried to send clean raw PATCH request with json in it.

`sendRequest()` allows only array as input params and my content can't be passed.

Also I can't override `CURLOPT_POSTFIELDS` with setCurlOptions().

If I set 

>    curl_setopt( $curlResource, CURLOPT_POSTFIELDS, '{"message":"raw json"}' );

inside `BaseOAuth::sendRequest` with other `curl_cetopt` -  it works.

**Comment by klimov-paul** [comment]
Same as #6961

**Comment by smorocho** [comment]
This is solved with this pull request https://github.com/yiisoft/yii2-authclient/pull/33
