### ISSUE TITLE
ajax validation is not working if form submit method is get

### ISSUE THREAD

**Issue by ajkosh** [yiisoft/yii2#8399]
for detail see this issue #8394

**Comment by Alex-Code** [comment]
Not enough info.

What's happening when you click submit?
What does your action look like that performs the validation?

**Comment by ajkosh** [comment]
when i m clicking on submit button, it is rendering my full form to url ,instead this should call rules and throw error.i m checking in firebug

**Comment by Alex-Code** [comment]
Can you show your `View`, `Controller`/`Action`

**Comment by ajkosh** [comment]
i m ready to post are u there,i created gist files so i can post here,when u are available i can post.

**Comment by ajkosh** [comment]
why pagination is not working if i m using arraydataprovider

**Comment by cebe** [comment]
@ajkosh please provide the information requested here, otherwise we can not reproduce the issue. Also for general questions, please use the form, github is for bugtracking.

**Comment by klimov-paul** [comment]
Unable to reproduce.
