### ISSUE TITLE
Anyone can help me with Yii::$app->security->validatePassword($password, $hash)

### ISSUE THREAD

**Issue by Lynnworld** [yiisoft/yii2#8400]
my problem is Yii::$app->security->validatePassword($password, $hash) cost 500ms+ on my pc.
finally i found it's password_verify cost much time.
I know it's not a problem for yii. but I can't find why and need help,
Any one can help me what's the problem with password_verify

**Comment by Alex-Code** [comment]
This is the bug tracker for issues in Yii.
You'd get a better response on the forums. Post it there and provide more details such as hardware and PHP version.

[Yii 2.0 Forum](http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/)

**Comment by genyii** [comment]
change the Security component's passwordHashCost in your main.php
```php
'components' => [
    'security' => [
        'passwordHashCost' => 10, //default is 13
    ],
    //...
],
```
note: it only works for new password.cause your old password was encrypted use cost 13
