### ISSUE TITLE
How To Get List of Relations on Model?

### ISSUE THREAD

**Issue by mootensai** [yiisoft/yii2#8402]
I'm trying to create a loadWithRelations() function, but i need to get the list of relation on Model like relations() function on Yii 1.1

How to get that list? I need relation name, isHasMany, Fully Qualified Relation Model Class Name, RelationModelClassName, and link

I already create an issue here

https://github.com/yiisoft/yii2-gii/issues/35

But as you can see it's already closed by suggesting a discussion here

https://github.com/yiisoft/yii2/issues/583

Can you give me any work around?

**Comment by klimov-paul** [comment]
Duplicates #1282
