### ISSUE TITLE
Override dropdown-menu when adding a class

### ISSUE THREAD

**Issue by ebisbe** [yiisoft/yii2#8405]
Is there a way to override all class styles in the Dropdown:

```php 
    public function init()
    {
        parent::init();
        Html::addCssClass($this->options, 'dropdown-menu');
    }
```
I'm building a template that doesn't need that option by default. And I cannot deleted. That addCssClass should be optional right?

**Comment by alexandernst** [comment]
Sounds a lot like #8229

**Comment by ebisbe** [comment]
Yes, it the same problem. Hardcoded clases in the code that cannot be override.

**Comment by klimov-paul** [comment]
Resolved by https://github.com/yiisoft/yii2-bootstrap/pull/52
