### ISSUE TITLE
User Identity Secure? 

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#8409]
Is there any way a user can force switch his Yii::$app->user->identity without logging into another account?

During development I was logged in as user id #1. I made some design changes to the view then hit refresh then I was suddenly logged in as user id #3 (which I don't have the access details for)

I relogged and tried replicating the issue but it never happened again. It's really creepy

**Comment by cebe** [comment]
thats really weird, can you explain more details about the environment where this was happening?

**Comment by samdark** [comment]
It's a common scenario when you're an admin but want to preview how another user is experiencing the app.

**Comment by cebe** [comment]
does not sound like something like that was implemented or used here.

**Comment by samdark** [comment]
If there's nothing like that, that's weird.

**Comment by BAWES** [comment]
I'm on iMac 5K - PHP 5.6.7 (cli) (built: Mar 23 2015 01:51:22) 
I have my user component configured as follows:

    'user' => [
            'identityClass' => 'common\models\Employer',
            'enableAutoLogin' => true,
        ],

Could it be that I had an old cookie for that other user which got loaded when I refreshed?
Im logging them in using the following:

    return Yii::$app->user->login($this->getEmployer(), $this->rememberMe ? 3600 * 24 * 30 : 0);

The page I was loading was accessing a relation of the identity with the following:

    $jobs = Yii::$app->user->identity->jobs;

It's working fine now, haven't been able to replicate the issue. The only other place where I log the user in is after they verify their email by calling the following:

    Yii::$app->user->login($employer, 0);

**Comment by BAWES** [comment]
I was able to replicate the issue. First I log in to my `Employer` application as an `Employer` of `Id - 1` with the email of `khalid@bawes.net` - everything works fine.

Then I go to the `Backend` application and login as `Admin` of  `Id - 3` with the email of `khalid@bawes.net`

When I refresh the `Employer` application, I am now logged in as `Employer Id - 3`

It seems the issue is there because both an Employer and an Admin have the same email? Is there any additional configuration required for the user component so there is no conflict during login of separate applications?

User component config for the `Employer` App:

    'user' => [
            'identityClass' => 'common\models\Employer',
            'enableAutoLogin' => true,
        ],

User component config for the `Backend` app:

    'user' => [
            'identityClass' => 'common\models\Admin',
            'enableAutoLogin' => true,
        ],

The login function:

    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getAdmin(), $this->rememberMe ? 3600 * 24 * 30 : 0);
        } else {
            return false;
        }
    }

**Comment by cebe** [comment]
for this to work you have to create separete cookie names for both applications.

**Comment by BAWES** [comment]
I have used the advanced application template, does this mean by default you need to do this to separate `backend` from `frontend` in yii2-advanced?

If I change the cookie name, can a user who has access to `frontend` change his cookie name to the `backend` cookie to gain access?

What's the best approach to creating separate cookie names for each application?

**Comment by cebe** [comment]
1. you need separate cookie verification keys
2. you need different cookie names

@samdark maybe this should be the default?

**Comment by cebe** [comment]
session name can be set like this in app components config:

```php
'session' => [
	'name' => 'yii-backend',
],
```
cookie validation key is part of the request config and should already be there.

**Comment by BAWES** [comment]
Thanks! It seems to be working better now.
Is this all the config I need (within session component)? Or is there another one for cookie name?

Cookie validation key is already there and being generated by `./init`

**Comment by samdark** [comment]
Advanced app was meant to be served from two separate subdomains but making cookies separate by default could be a good idea...

**Comment by tom--** [comment]
Depending on a specific web server config to prevent cookie reuse is probably not a prudent default.

Well spotted @BAWES

**Comment by dynasource** [comment]
for reference: this issues also occurs with different projects on a localhost

**Comment by samdark** [comment]
If your localhost serves projects from subdirs.

**Comment by tom--** [comment]
In advanced we could add some random chars to the session ids in init.

In basic we could put the default session id explicitly in config and add a comment. Actually I think this is the better way for both because the important thing is for users to know that session ids are unique/global per domain.

**Comment by spikyjt** [comment]
IE (at least oldish versions, not sure about 11 or Edge) treat subdomains as the same domain as the base, as far as cookies are concerned. So if your frontend is on mydomain.com and your backend is on admin.mydomain.com and you use the same cookie name for your sessions, you will get the same session in both.

Different cookie names for the separate apps is a must IMHO. I think this should be part of the basic app too, generated by the build script, like the verification key (this will solve the problem also if you had two basic apps on the same domain in subfolders or subdomains).

**Comment by SilverFire** [comment]
Agree with @tom--

**Comment by maine-mike** [comment]
Perhaps this is a factor too:

I found a problem when you do a Yii::$app->user->login( <user1> , <non-zero value> ) followed by Yii::$app->user->login( <user2> , 0 ) without a logout in between.  The identity cookie from user1 doesn't get removed when user2 logs in and it appears to be possible that user1 can be auto-logged in later.

The fix I came up with is here:  https://github.com/yiisoft/yii2/pull/10480

**Comment by samdark** [comment]
Seems to be already fixed.
