### ISSUE TITLE
Killing console process

### ISSUE THREAD

**Issue by TimNZ** [yiisoft/yii2#8410]
Please advise if this is not the place to post

I have a console controller instance managed via upstart that implements a persistent background job processor.

After I do a Model::find() call the KILL signal doesn't terminate the process.

Ctrl C (OS X) kills the process if I just have a loop with a sleep(1).

Looks like after a DB operation is executed ctrl-C no longer KILLs the process, the loop continues.

I also tried implementing pcntl_signal(SIGTERM, [$this,"sig_handler"]) and doing a kill -s TERM on the process, it dies but with a 'segmentation fault: 11'

PHP 5.5.23 on Yosemite 10.10.3

**Comment by samdark** [comment]
Questions should be asked at the forum: http://www.yiiframework.com/forum/

**Comment by TimNZ** [comment]
I posted on the forum, no responses.

http://www.yiiframework.com/forum/index.php/topic/63817-persistent-console-process
