### ISSUE TITLE
Gii should have option under Model Generator to generate file under @common/models directory

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#8411]
For Advance Application Template, I should be able to tell Model Generator where I want the new model file to be

**Comment by lynicidn** [comment]
change namespace `app\models` to `myVendor\models`

**Comment by lichunqiang** [comment]
+1 @lynicidn

**Comment by duynguyen0511** [comment]
thanks. i thought the Namespace field is read-only as it appears as text, not input field
