### ISSUE TITLE
Oracle batch insert

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#8416]
It fails, because oracle uses different syntax

**Comment by klimov-paul** [comment]
Please, be more specific: what is expected syntax in your opinion and what is actual syntax, generated by Yii?
For the "oci" `batchInsert()` method is overridden respecting Oracle dialect.

**Comment by BenasPaulikas** [comment]
well it currently does insert into x values () () (), but that does not works on oracle ? It should contain attributes to insert before every value ?

**Comment by klimov-paul** [comment]
Here is a specification for Oracle bacth insert:
http://www.techonthenet.com/oracle/questions/insert_rows.php

Current Yii implementation matches it, as far as I see.

What is your problem?

**Comment by BenasPaulikas** [comment]
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 933 OCIStmtExecute: ORA-00933: SQL command not properly ended
 (ext\pdo_oci\oci_statement.c:148)

As I said before its generating: "Insert into X ("ATTR1", "ATTR2") VALUES () () () () () () ...

**Comment by klimov-paul** [comment]
Please provide exact generated SQL content.

**Comment by BenasPaulikas** [comment]
INSERT INTO "X" ("ATTR1", "ATTR2") VALUES (1, 'daniella'), (2, 'benas')

**Comment by nineinchnick** [comment]
@BenasPaulikas please provide the code that generates this query and check your framework version. Oracle `batchInsert` is properly supported since latest 2.0.4

**Comment by klimov-paul** [comment]
> INSERT INTO "X"

This is can not be, according to
https://github.com/yiisoft/yii2/blob/master/framework/db/oci/QueryBuilder.php#L218

Generated SQL should start with `INSERT ALL `

**Comment by BenasPaulikas** [comment]
All god with 2.0.4 Mark as fixed :) Ty for help (y)
