### ISSUE TITLE
Link - data-method post - not working anymore

### ISSUE THREAD

**Issue by Smiggel** [yiisoft/yii2#8419]
Since Yii 2.0.4. a simple link in an form with a data-method post doesn't work anymore. Example:
```html
<a class="btn btn-danger" href="/quote/delete/6" data-confirm="Are you sure you want to delete this record?" data-method="post">Delete</a>
```

Before the link would go to the quote controller and delete action and post 6 as the id. Now it just posts to the current action.

**Comment by gigi** [comment]
Critical bug
```
<a href="/campaigns/70/delete" data-confirm="Are you sure you want to delete the campaign?" data-method="post">Delete campaign</a>
```
Update to 2.0.4 has broken links' actions. Downgrading to 2.0.3

**Comment by klimov-paul** [comment]
Unable to reproduce.
Both application templates have 'Logout' link in menu composed using 'data-method="post"', adding extra 'data-confirm' does not affect it - evrything is working fine.

Are your links inside a form or there is anything else, which make them different?

**Comment by Smiggel** [comment]
The link is inside the forum. The buttons is positioned next two submit buttons. This used to work fine. When the link has no data-method tag, the link works. However, I need it to be a post.

**Comment by gigi** [comment]
Just small example to reproduce
Whole view file 
```
<?php
/**
 * Test view to reproduce data-method=post bug
 */
use yii\helpers\Html;
?>

<?=Html::a('Test', 'index/test', [
    'data' => [
        'confirm' => 'Are you sure you want to delete the campaign?',
        'method' => 'post',
    ]
])?>
```
If you click on the link you will have POST request to the current page, not to 'index/test'

**Comment by klimov-paul** [comment]
Duplicates #8161
