### ISSUE TITLE
update TimestampBehavior doc

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#8422]
I suggest adding to ( http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html ) something to say about "make sure created_at and updated_at are not in any validation rule"

I've struggled for several hours why TimestampBehavior does not work as I stuck at "created_at" / "updated_at" can not be blank. It turns out that I must remove "created_at" and "updated_at" from validation rule which was generated by Gii Model Generator

**Comment by samdark** [comment]
Agree.

**Comment by ScottHuangZL** [comment]
I use below code.  It is strange that update work, however event_before_insert not work.
I have to manual assign Create_At = 'now()' and Update_At = 'now()' to pass the validation.

So, do you mean, I need to remove Create_At/Update_At from validation rule?
Why??

  public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['Update_At'],
                    ActiveRecord::EVENT_BEFORE_INSERT => ['Create_At', 'Update_At'],
                ],
                'value' => new Expression('now()'),
            ],
        ];
    }
