### ISSUE TITLE
ActiveForm's error summary not displaying neigther with client nor ajax validation

### ISSUE THREAD

**Issue by tekord** [yiisoft/yii2#8423]
I have the form:
```
	<?php $form = ActiveForm::begin([
		'id' => 'ordering',
		'enableAjaxValidation' => true,
		'validationUrl' => ['checkout/validate-form'],
		'fieldConfig' => [
			'template' => "{label}\n{input}\n{hint}"
		]
	]) ?>
   ...
   Some controls here
   ...
   <?= $form->errorSummary($model) ?>
   ...
    <?php ActiveForm::end() ?>
```
After field validation the error summary didn't update. Form has errors, fields are highlighted (input div's has 'has-error' class and populated 'help-block' with error message), but error summary doesn't provide any info about errors. It has `style="display: none"` and empty error list (ul). It doesn't work neither with ajax validation nor client validation.

Questions are:
1. Do I understand correctly the purpose of error summary?
2. I used error summary in beta version of Yii2, it worked then for client validation. How I can make it work in Yii 2.0.4?

**Comment by klimov-paul** [comment]
Error summary is updated on form submit either by client or ajax validation. However validation triggered by such events like 'ontype' does not affect summary.

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
