### ISSUE TITLE
Only one AuthManager and extended interfaces

### ISSUE THREAD

**Issue by sashaaro** [yiisoft/yii2#8424]
Hello. Sorry for my english. I hope you understand me.I have problem with AuthManager. Very important to encapsulate the storage of assignments and operations. All operations (permissions) is can be defined in php files (in around 95% case it is permanent data, likely PhpAuthManager). No need to write init rbac function (it is not convenient, especialy when operations very much) I have project with mongodb. Hold assignments in separated collection make no sense. it is hold in user's collection. And operations is hold in php files (them is very much). I wrote own authmanager. Besides there is ability add own roles through admin panel. Therefore roles is hold in php files (for default roles) and in db (in mongo for added roles). I think need likely Assignment Provider class (db, php, mongo...) and PermissionProvider for operations and roles(more constans data). In my case I have ChainPermissionProvider(mongodb and file). Conclusion. Assignments in db(dynamically data), operations rules roles in php (permanent data).Only one authmanager

**Comment by klimov-paul** [comment]
The issue is too specific. It does not worth to split `AuthManager` for that.
However the feature may be achieved via implemetation of #570, which will allow different ActiveRecord per "assignment" and "operations".
