### ISSUE TITLE
Css compression is making problem

### ISSUE THREAD

**Issue by harshitj2005** [yiisoft/yii2#8428]
i dont to compress my css and js files. is there any way to do it.?
i have tried making cscompressor false but still cant do it. 
css and js files ain't compressed while the site is on my local but as soon as i make on live on AWS then it compresses them.

**Comment by klimov-paul** [comment]
@harshitj2005, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
