### ISSUE TITLE
Debug panel catches errors but the application itself doesn't display it.

### ISSUE THREAD

**Issue by dbsparkle** [yiisoft/yii2#8429]
I spotted a log message of error level in debug panel, but my application was running and not throwing errors in the browser:
![display_errors](https://cloud.githubusercontent.com/assets/417757/7648694/b2a756ac-fb20-11e4-97fe-ebbc12bcbb5f.png)

So to test it, I tried:
```
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/../common/config/bootstrap.php');
require(__DIR__ . '/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../common/config/main.php'),
    require(__DIR__ . '/../common/config/main-local.php'),
    require(__DIR__ . '/config/main.php'),
    require(__DIR__ . '/config/main-local.php')
);
echo 'display_errors1 = ' . ini_get('display_errors') . "\n";
$application = new yii\web\Application($config);

echo 'display_errors2 = ' . ini_get('display_errors') . "\n";
$application->run();
```
And got the results:
**display_errors1 = 1**
**display_errors2 = " "** !

Is it a normal behavior or a possible bug in the framework?

 `yii\base\ErrorHandler` sets `display_errors` to `false` and `yii\WEB\errorHandler`
switches it to `true`... I also suspect that my issue may be somehow related to: #7616

**Comment by klimov-paul** [comment]
So what is this error, which is indicated at debug panel? What causing it?

**Comment by dbsparkle** [comment]
Now I tried to reproduce it in clean installation of Basic App Template.

In web/index.php:

```
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/../config/web.php');

echo 'display_errors1 = ' . ini_get('display_errors') . "\n";

use yii; // <---- just to cause an error

(new yii\web\Application($config))->run();

echo 'display_errors2 = ' . ini_get('display_errors') . "\n";

```
Results were the same:
display_errors1 = 1
display_errors2 = " " !

**Comment by klimov-paul** [comment]
Can you answer my question?

**Comment by dbsparkle** [comment]
@klimov-paul Yeah, in my first case I didn't have a translate category (yii\i18n\PhpMessageSource::loadMessages)

In second case see the error above

**Comment by klimov-paul** [comment]
'display_errors' are unset by `ErrorHandler`:
https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L54
But this should not be a problem.

**Comment by klimov-paul** [comment]
This may be specific to your environment.

**Comment by dbsparkle** [comment]
nope, I got the same report from my team developer (using a different OS and PHP version)

**Comment by andreev1024** [comment]
```
<?php
use yii;
?>
```
Выбрасывает ошибку 
![Image of Yaktocat](http://dl2.joxi.net/drive/0005/3013/392133/150515/6640b6db86.jpg)
При этом в дебаг-панели сообщение об этом не логируется

**Comment by samdark** [comment]
Is it AJAX thing?

**Comment by andreev1024** [comment]
мой вопрос снят. Проблема была в opcache. Однако, то что перекрываются глобальные настройки - как-то не комильфо.

**Comment by yurii-github** [comment]
display is set during exception at ErrorHandler::renderException() line 93

     elseif ($response->format === Response::FORMAT_HTML) {
                if (YII_DEBUG) {
                    ini_set('display_errors', 1);
                }

do you have response format other than FORMAT_HTML ?

**Comment by cebe** [comment]
> I spotted a log message of error level in debug panel, but my application was running and not throwing errors in the browser:

this is normal, not all errors result in a fatal crash of the application, you can just log `Yii::error('app', 'hi there')` and you get an entry in error log.

**Comment by dbsparkle** [comment]
I wasn't talking a fatal crash, my point was that if you set ini file to show all errors and have debug panel enabled I, as maybe many other developers expect to "see" them there. Without digging into ErrorHandler code I wouldn't know that it silently switches off.

**Comment by cebe** [comment]
Any PHP error that might occur is converted to an exception so you have not chance to see it inside the website. there is no sense in turning  display_errors on when yii error handler is active.

**Comment by dbsparkle** [comment]
That's the point! Read the messages above please. 

You have the highest level of error displaying and reporting set in global ini file. You have Opcache set on and you have ErrorHandler and debug panel enabled.  You assume that if a critical error happens it will be shown as an exception or traced in debugging panel. But it fails to do that and at the same time it turns off/overrides the master settings of your environment....

So do you really read all your logs after every and each iteration you made to the code? 

My proposal is instead of letting ErrorHandler turn error display off by default (without mentioning about it in the docs) give developers a choice to set that in config.

**Comment by samdark** [comment]
@dbsparkle having a missing translation category isn't the thing that should result in app crash. That's intentional.

Having `display_errors` on won't add this error to the screen because, in fact, it's logging directly using Yii log component in this case, not causing error.

Also `display_errors` on will affect our exception page in case of fatals. If it's turned on there's no way to get rid of standard PHP message and render our nice exception with source, stacktrace etc.

**Comment by dbsparkle** [comment]
@samdark ,  here is a real example: A developer added `use yii` in the view file. I expected him to see a nice exception to tell him that "The use statement with non-compound name 'yii' has no effect.". Unfortunately the framework failed to do that... You can't say that it's a normal practice.

**Comment by cebe** [comment]
> I expected him to see a nice exception to tell him that "The use statement with non-compound name 'yii' has no effect.".

this is exactly what happens...

**Comment by dbsparkle** [comment]
That wasn't happening, and that's why I came here and posted this issue. After investigation we found out that opcache was the reason for that. So I wondered why he didn't see the php' error message. And after looking into framework code I found out that ErrorHandler was switching display_errors to OFF state. 
I personally think that in the "DEV" environment we should give an option to choose if they want to set display_errors on or not. Or at least write a note in the docs that ErrorHandler overrides the ini settings.

**Comment by cebe** [comment]
whatever happended in your case has nothing to do with display_errors and turning it on will change nothing. Yii will turn anything that could be displayed by display_errors into an exception which will render an exception page.

**Comment by dbsparkle** [comment]
Hmm... You're right, in this particular case it won't help

**Comment by samdark** [comment]
btw., @dbsparkle do you have reliable way to reproduce it? Not sure we can catch such errors but I can look into it if I have an environment with such error.
