### ISSUE TITLE
php date() function give differents values in runtime code and in config when logging via email

### ISSUE THREAD

**Issue by realtebo** [yiisoft/yii2#8431]
In siteController->actionIndex() I'm testing logging via email using this simple row

    Yii::error("testing mail, now is " . date('H:i:s'), "email_test");

And the log emailTarget is configured as is:

	'class' 		=> 'yii\log\EmailTarget',
	'levels' 		=> ['error'],
	'categories' 	=> ['yii\db\*', 'email_test'],
	'logVars'       => [], 
	'message' 		=> [
	   'from' 			=> ESHOP_EMAIL,
	   'to' 			=> [DEVELOPER_EMAIL => DEVELOPER_NAME],
	   'subject' 		=> 'Errore db [' . YII_ENV . '] ' . date ("H:i:s"),
	],

When my email arrives has in the subject the RIGHT time, for example `Errore db [dev] 14:34:03`, but the body tells `now is 12:34:03`, so it's 2 hour before the right one.

I'm in Italy with 24h date time format, and the app has language= "it_IT"

Must I specify timezone in config to avoid this problem?

**Comment by klimov-paul** [comment]
See #209

**Comment by realtebo** [comment]
I can't understand a clear solution. 

I tried this in my index.php 

    echo "1: " . date("H:i:s") . "<br>";
    $application = new yii\web\Application($config);
    echo "2: " . date("H:i:s") . "<br>";
    $application->run();

I get the right timezone at '1' and wrong at '2'. 

So I must re-set the timezone at app config level. But why Yii overrides the right timezone set by my server?

The time at '1' is right, so my server has the right timezone set.. or not?

**Comment by klimov-paul** [comment]
Do you have a `timeZone` key at your application config?

**Comment by realtebo** [comment]
No, I hadn't. 

Now I added one timeZone to the app config and all is working well.

But I don't understand why Yii 2 overrides the default timezone of my server (at php.ini level I suppose, but it's a shared host)

**Comment by klimov-paul** [comment]
What does the following script outputs in your environment?
```php
<?php
var_dump(ini_get('date.timezone'));
```

**Comment by cebe** [comment]
@realtebo if you do not configure it yii will only override it if it is not defined. and set default to UTC. to be sure, just configure it explicitly.
