### ISSUE TITLE
How to stored all uft-8 characters?

### ISSUE THREAD

**Issue by zinzinday** [yiisoft/yii2#8432]
I have db with construct with collate uft8_unicode_ci
![construct](https://cloud.githubusercontent.com/assets/441560/7653892/552cdb6e-fb43-11e4-8e44-a54f186144b9.png)
i insert data records with yii2 activerecord
value of field `chars` generate by
```
    /**
     * @return string
     */
    public function getUnicodeChar()
    {
        return  mb_convert_encoding("&#" . hexdec($this->hexcimal) . ";", 'UTF-8', 'HTML-ENTITIES');
    }
```
but result of field `chars` same `null` or `?`
![listview](https://cloud.githubusercontent.com/assets/441560/7654030/37ec5b00-fb44-11e4-9b09-a6a2c2408404.png)

Please, help me

**Comment by klimov-paul** [comment]
@zinzinday, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
