### ISSUE TITLE
Russian translate db-dao

### ISSUE THREAD

**Issue by miramir** [yiisoft/yii2#8442]
Я занимаюсь переводом главы Объекты доступа к данным (DAO)

**Comment by miramir** [comment]
подскажите как перевести Quoting Table and Column Names

**Comment by samdark** [comment]
Экранирование имён таблиц и столбцов.

**Comment by miramir** [comment]
а Savepoint? в лоб как-то некрасиво смотрится. Всё приложение выглядит так:
If your DBMS supports Savepoint, you may nest multiple transactions like the following

**Comment by zelenin** [comment]
@miramir донесите корректно баг или предложение.

**Comment by miramir** [comment]
Скорее предложение. Просто я начал переводить данную главу, и как просят в workflow создал issue.
Pull request я пока не готов создать, а вопросы по переводу есть, вот и решил задавать их здесь.
А как правильнее было сделать?

**Comment by zelenin** [comment]
issue надо создавать с целью не пересекаться с другим разработчиком, решающим ту же проблему.
Для вопросов надо идти на форумы.

**Comment by miramir** [comment]
ну ок.
