### ISSUE TITLE
ActiveRecord using joinWith and sorting on joined table columns comes back wrong

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#8448]
I am running the following (please note that column ```ts``` belongs to table ```activity``` and not ```player```)

```
        $players = Player::find()
            ->joinWith(['activities'])
            ->where(['player.id' => 12])
            ->orderBy(['ts' => SORT_ASC])
            ->all();
```

and then noticed my records don't come back sorted. Checking on Yii debug I see it actually runs the following (which is correct according to the documentation)

```
SELECT `player`.* FROM `player` LEFT JOIN `activity` ON `player`.`id` = `activity`.`user_id` WHERE `player`.`id`=12 ORDER BY `ts`
```
and
```
SELECT * FROM `activity` WHERE `user_id`=12
```

Is there some way that I can use the joinWith (maintaining the nice and clear syntax) and still have it return the records correctly?

**Comment by fbau123** [comment]
* // find all orders, eager loading "books", and sort the orders and books by the book names.
     * Order::find()->joinWith([
     *     'books' => function ($query) {
     *         $query->orderBy('item.name');
     *     }
     * ])->all();

I haven't tested it, but according to this you should put the orderBy inside the relation

   $players = Player::find()
            ->joinWith( ['activities' => function($q){ $q->orderBy('ts');}] )
            ->where(['player.id' => 12])
            ->all();

**Comment by cebe** [comment]
your select could be the problem: `` `player`.* `` ts does not seem to be in the result so it can not be used for sorting. are you sure you do not have a column `ts` in player? otherwise it should fail imo.

**Comment by Faryshta** [comment]
@cebe is there a way to change the select and store the data on the active record?

example 

        $players = Player::find()
            ->joinWith(['activities'])
            ->select(['max_ts' => 'max(ts)'])
            ->where(['player.id' => 12])
            ->orderBy(['ts' => SORT_ASC])
            ->all();

**Comment by klimov-paul** [comment]
Order specified for the main query (the one with `joinWith`) applies only for the main query. It can not be automatically applied to the query, which performs eager loading of the related records, because such order may contain fields, which are not present in related table.
If you with 'has many' relation results be sorter you should use the solution proposed by @fbau123.
