### ISSUE TITLE
Formatter timeZone problem

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#8451]
Hi,
I have problem with Formatter. ```asTime``` method always add 2 hours.

I think that it is because php on my server ```date.timezone``` option is set on ```Europe/Warsaw```.
But Yii Formatter have ```$defaultTimeZone = 'UTC'``` by default.

Yii should sync this settings, because for now I need to configure this option in this way:
```
        'formatter' => [
            'defaultTimeZone' => date_default_timezone_get(),
        ],
```

**Comment by cebe** [comment]
dates and times stored in the database are usually in UTC so the input value is considered UTC by default. If you store it in a different timezone you should configure it explicitly.

Note that using `date_default_timezone_get()` could result in unexpected results because the timeZone setting of the application sets this.

http://www.yiiframework.com/doc-2.0/guide-output-formatter.html#time-zones

**Comment by mklemarczyk** [comment]
So there are an error, becouse I do not change any configuration about timezone in database.

**Comment by cebe** [comment]
the fact that you did not change the config does not tell anything about whether it is correct or not.
If you have everything in one timezone you should set the configs to state the timezone explicitly.

for further questions please use the forum, github is for bug tracking.

**Comment by mklemarczyk** [comment]
@cebe I still think that it IS a bug. Because Yii should by default use php server timezone do convert user input and display proper time, but store in files and database in UTC format.

For now, Yii store time data directly based on user input without casting it to UTC time.

**Comment by cebe** [comment]
> @cebe I still think that it IS a bug. Because Yii should by default use php server timezone do convert user input and display proper time, but store in files and database in UTC format.

it does exactly that:
- database time is UTC:
  - https://github.com/yiisoft/yii2/blob/master/framework/validators/DateValidator.php#L108
  - https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L82
- Output is php server default:
  - https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L470

> For now, Yii store time data directly based on user input without casting it to UTC time.

this is not true, see links above. If it is the case in your app, you are doing something wrong.

**Comment by mklemarczyk** [comment]
You introduced ```timestampAttribute``` field. Why Yii does not use database data/time formats for storing data/time?
Timestamp format can not be easy filtered. (By year, month, day etc.)

**Comment by cebe** [comment]
I do not understand your question, please explain in more detail.

**Comment by mklemarczyk** [comment]
Yii should use default DATE, DATETIME and TIME types to store time information in database.

Why you force to use INTEGER as type for storing time information?
It is very uncomfortable way to store that, because databases have defined many features (like procedures and functions) to manage time information. Also UNIX timestamp have a lot of limitations. First is can not easy find records from chosen year or month, next is you can not save date before 1970 year.

Yii should provide support for database date and time data types.
Why you force me to store time in UNIX timestamp (date validator use it by default)?

I know that I can define ```timestampAttributeFormat```, but it depend on format in database and database engine. Finally, I can not define it for entire application.

Why Yii can not determine it based on data in database?

**Comment by cebe** [comment]
> Why you force to use INTEGER as type for storing time information?

we do not force it, it is just a default that works cross db.

> First is can not easy find records from chosen year or month, next is you can not save date before 1970 year.

You can create a condition like `WHERE date > 12349879 AND date < 12384536`. And it can store dates before 1970, these are just negative numbers.

> Yii should provide support for database date and time data types.

It does support this by `timestampAttributeFormat`.

> Why Yii can not determine it based on data in database?

because as you said, it depends very much on the database and environment. If it were only mysql this would be quite easy but yii supports more that that.

> Finally, I can not define it for entire application.

you can:

```php
Yii::$container->set('yii\validators\DateValidator', ['timestampAttributeFormat' => 'php:Y-m-d H:i:s']);
```

> Moreover, there are more features are missing about date and time processing in Yii right now.

please be more specific. imo datetime support is very complete right now.

**Comment by mklemarczyk** [comment]
Really? I do not think so.
When I use negative integer I have an exception:
```
'-20602' is not a valid date time value: Failed to parse '-20602' as a UNIX timestamp.
```

**Comment by cebe** [comment]
> '-20602' is not a valid date time value: Failed to parse '-20602' as a UNIX timestamp.

well, this is a bug...

**Comment by giannisdag** [comment]
The problem with the negative values seems to remain. This is the report:

exception 'yii\base\InvalidParamException' with message 'Failed to parse '-154317600' as a UNIX timestamp.' in /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php:645 Stack trace: #0 /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php(558): yii\i18n\Formatter->normalizeDatetimeValue(-154317600, true) #1 /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php(462): yii\i18n\Formatter->formatDateTimeValue(-154317600, 'dd-MM-yyyy', 'date') #2 [internal function]: yii\i18n\Formatter->asDate(-154317600) #3 /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php(285): call_user_func_array(Array, Array) #4 /var/www/akadim/vendor/yiisoft/yii2/widgets/DetailView.php(155): yii\i18n\Formatter->format(-154317600, Array) #5 /var/www/akadim/vendor/yiisoft/yii2/widgets/DetailView.php(136): yii\widgets\DetailView->renderAttribute(Array, 8) #6 /var/www/akadim/vendor/yiisoft/yii2/base/Widget.php(97): yii\widgets\DetailView->run() #7 /var/www/akadim/backend/views/coach/view.php(86): yii\base\Widget::widget(Array) #8 /var/www/akadim/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/akadim...')

**Comment by cebe** [comment]
The error message does not exist in the code after the fix so it seems you are not using the latest version. Note that this will be fixed in 2.0.5 which is not yet released.

**Comment by giannisdag** [comment]
Yes, my mistake, I watched the dates and thought that 2.0.5 was released. So this is one more reason to expect the release, thank you. :+1:

**Comment by giannisdag** [comment]
this time I have updated to 2.0.5, and test it again. It seems that the bug remains or I am doing something wrong. [I have changed the date for test purposes].
exception 'yii\base\InvalidParamException' with message 'Failed to parse '-269748000' as a UNIX timestamp.' in /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php:645 Stack trace: #0 /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php(558): yii\i18n\Formatter->normalizeDatetimeValue(-269748000, true) #1 /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php(462): yii\i18n\Formatter->formatDateTimeValue(-269748000, 'dd-MM-yyyy', 'date') #2 [internal function]: yii\i18n\Formatter->asDate(-269748000) #3 /var/www/akadim/vendor/yiisoft/yii2/i18n/Formatter.php(285): call_user_func_array(Array, Array) #4 /var/www/akadim/vendor/yiisoft/yii2/widgets/DetailView.php(155): yii\i18n\Formatter->format(-269748000, Array) #5 /var/www/akadim/vendor/yiisoft/yii2/widgets/DetailView.php(136): yii\widgets\DetailView->renderAttribute(Array, 8)

**Comment by cebe** [comment]
Yeah sorry, we were urged to release a security fix as 2.0.5, this release only includes the fix for the security issue, the regular release which includes this fix is now 2.0.6.

**Comment by cebe** [comment]
Btw, the due date for the next regular release is available here: https://github.com/yiisoft/yii2/milestones

**Comment by giannisdag** [comment]
Ok, I had understood this just now, that' s why I deleted my message, thank you for the quick response
