### ISSUE TITLE
Yii::$app->formatter->asRelativeTime()

### ISSUE THREAD

**Issue by halfahad** [yiisoft/yii2#8453]
```
echo Yii::$app->formatter->asRelativeTime('yesterday')
```

is outputting a literal: **{delta, plural, =1{a day} other{# days}} ago.**

with debug message:

```
Formatting message for language 'en-US' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_CHARACTER. The message being formatted was: {delta, plural, =1{a day} other{# days}} ago.
```

**Comment by lynicidn** [comment]
time()-24*60*60

**Comment by cebe** [comment]
please show the ICU version you are using.

**Comment by halfahad** [comment]
PHP: 5.5.24 
ICU: 4.2.1

Yii 2.0.4

**Comment by halfahad** [comment]
from a different post by you:
**The syntax used in the translation message for relative time is only supported by ICU version 4.8 or higher.**

A suggestion to do an ICU check in the code and gracefully inform users.
Thanks for your continued hard work on this project, we all appreciate it.

**Comment by lynicidn** [comment]
http://stackoverflow.com/questions/6796866/php-date-yesterday
hm, require strtotime?

**Comment by cebe** [comment]
@lynicidn what do you want to say? your comments seem totally unrelated to me...

**Comment by lynicidn** [comment]
@cebe yeah sorry, u right, current TS code should work

**Comment by cebe** [comment]
Will not throw an error here, you could replace yii messages by providing an alternative implementation that works with ICU < 4.8. e.g. `in {delta, plural, =1{a year} other{{delta} years}}` which however might cause issues with newer icu versions. We will just stick to requiring 4.8 as it is already documented for everything to work properly.
