### ISSUE TITLE
Yii::$classMap seems not work

### ISSUE THREAD

**Issue by feitian124** [yiisoft/yii2#8462]
1. i installed Yii2 with the `Basic Application Template` and everything is fine, nice welcome page, all green tests. 

2. then i want to use a 3rd party code namely [wechat-php-sdk](https://github.com/dodgepudding/wechat-php-sdk ) following [working-with-third-party-code](http://www.yiiframework.com/doc-2.0/guide-tutorial-yii-integration.html#working-with-third-party-code). i composer installed the sdk, it located in vendor folder as below:
```
vendor
  |--dodgepudding
      |--wechat-php-sdk
         |--wechat.class.php
```
i want to use the `wechat.class.php` file, so i config in the `entry point` as below:
```php
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
Yii::$classMap['Wechat'] =  __DIR__ . '/vendor/dodgepudding/wechat-php-sdk/wechat.class.php';
```

3. at last, i add a line to the action `actionIndex` of controller `SiteController`, which is the defaultRoute,
in order to see the log when i visit home page.
```php
      Yii::info('wechat:' . \Wechat::MSGTYPE_TEXT);
```
then error happens, it says `Class 'Wechat' not found`.

4. if i change above line to
```php
    Yii::info('wechat:' . Yii::$classMap['Wechat']);
```
the error says `Undefined index: Wechat` as if the line i added in `entry point` did not invoked...

5. My enviroment is as below:
```
Yii 2.0.4 
PHP 5.5.12-2ubuntu4.4
ubuntu 14.10
```

i am new to yii2 and IMO above should work, where am i wrong? thank you.

**Comment by cebe** [comment]
can you try to add these Yii::info calls directly in the index.php file after adding it to the classmap?

**Comment by feitian124** [comment]
i tried that.
if so no error happens and no extral log found in yii debugger..

**Comment by mdmunir** [comment]
Its work ok for me
```php
// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

Yii::$classMap['MyClassTest'] = __DIR__.'/app/components/test.class.php';
MyClassTest::doSomething();
```
`test.class.php` file
```php
<?php

class MyClassTest
{

    public static function doSomething()
    {
        echo "\n\n".__METHOD__." : Success\n";
    }
}
```

![screenshot from 2015-05-19 15 30 01](https://cloud.githubusercontent.com/assets/5828252/7698678/6e9ebb16-fe3c-11e4-9b4c-7183d7b86c7f.png)

**Comment by feitian124** [comment]
hi @mdmunir , how can i echo output to my terminal console, not broswer console?
i never see output in my terminal console; and in your case, i don't see log in yii logger, so i am not sure if 
it works in your case.

**Comment by mdmunir** [comment]
so, what the issue? `Yii::$classMap` or yii logger?
FYI, yii logger cannot be used before application created.

**Comment by feitian124** [comment]
@mdmunir  can you test if `MyClassTest` accessible in your controller?

**Comment by mdmunir** [comment]
ya, it work.
my controller
```php
<?php

namespace app\commands;

/**
 * Description of TestController
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class TestController extends \yii\console\Controller
{
    public function actionIndex()
    {
        \MyClassTest::doSomething();
    }
}
```
![screenshot from 2015-05-19 18 04 15](https://cloud.githubusercontent.com/assets/5828252/7701471/a1c6bfe2-fe51-11e4-8854-ae5f1300b758.png)

**Comment by mdmunir** [comment]
It seems you are not change the corect file. Make sure the file is `web/index.php`.

**Comment by feitian124** [comment]
thank you so much, @mdmunir, this should be the root case. 

i mistake the `yii` file as the  [entry script](http://www.yiiframework.com/doc-2.0/guide-structure-entry-scripts.html) but it should be `web/index.php`.

thank you again. :kiss:

**Comment by samdark** [comment]
`yii` is an entry file as well but for console application.
