### ISSUE TITLE
Menu widget: uncaught error syntax error unrecognized expression

### ISSUE THREAD

**Issue by kdjonua** [yiisoft/yii2#8464]
I created the menu view:

```php
echo yii\widgets\Menu::widget([
    'items' => [
        [
            'label' => 'Title 1',
            'url' => ['/my/path/one'],
        ],
        [
            'label' => 'Title 2',
            'url' => ['/my/path/two'],
        ],
    ],
    'options' => [
        'class' => 'nav nav-tabs',
    ],
])
```

But when I click on the two tab, I see an error in the console:
```
Uncaught Error: Syntax error, unrecognized expression: /my/path/two
```

I don't to follow to the second tab.

I use //ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js

**Comment by klimov-paul** [comment]
It is obvious you are using Twitter Bootstrap JS. It applies own js on `nav-tabs`, which produces this error.
If you need Bootstrap tabs use:
https://github.com/yiisoft/yii2-bootstrap/blob/master/Tabs.php
