### ISSUE TITLE
Log extra variables

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#8465]
Currently it is not possible, to log some extra information with the Yii::trace, -error, -warning and -info methods, so this would be an enhancement.

Here is a snipped:
```php
public static function info($message, $category = 'application', $extra = null)
{
    static::getLogger()->log($message, Logger::LEVEL_INFO, $category, $extra);
}
```
So it does only pass an extra variable/array to the logger, who does just pass it to his messages array. The magic or how the extra variables are used for is the job of the log-targets.

I would use it to log special user actions for example:
* `user {name} deleted the article {title}`
* `user {name} deleted the image <img src="data:image/png;base64,{verySmallThumbBase64}" />`

The message would be run through the translator like this:
`Yii::t('logs', $logEntry->message, $logEntry->extra)`.

I have it not fully thought through, but maybe someone else has some ideas.

**Comment by klimov-paul** [comment]
`$message` can be any complex data including array. If you with to store some translateable data, this is enough:
```php
Yii::info(['message' => 'user {name} deleted the article {title}', 'params' => [...]]);
```
