### ISSUE TITLE
Translate messages with byte size

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#8466]
I've struggled into some ugly things with the ICU translation.

The original error message for uploaded file which are too big is:
```
The file "{file}" is too big. Its size cannot exceed {limit, number} {limit, plural, one{byte} other{bytes}}.
```
Which results at 20MB in:
```
The file "xyz" is too big. Its size cannot exceed 20971520 bytes.
```
This message is not that user friendly, because nobody knows how much 20971520 bytes really is.

My current workaround is this:
```php
public function rules()
{
	return [
		['attachments', 'file', 'maxFiles' => 10, 'maxSize' => 20 * 1024 * 1024,
			'extensions' => ['png', 'jpg', 'gif', 'tif', 'doc', 'docx', 'pdf'],
			'tooBig' => Yii::t('app', 'The file "{file}" is too big. Its size cannot exceed {limitSize}', [
				'limitSize' => Yii::$app->formatter->asShortSize(20 * 1000 * 1000)])
		]
	];
}
```

**Comment by samdark** [comment]
Hmm, I think formatter should cover it.

**Comment by thejahweh** [comment]
Are here future plans or some ideas to handle it?

**Comment by bryglen** [comment]
any updates here? i encounter same issue for this.

**Comment by SilverFire** [comment]
Please, check out #10434
