### ISSUE TITLE
orWhere() / andWhere(), etc.. binded params are not set correctly in loops

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#8467]
for example
```php
$xy = ['foo1','foo2','foo3'];
$bar = Foo::find()->select('var1, var2');
foreach($xy as $x ){
  $bar->orWhere('abc = :xy', [':xy'=>$x]);
}
$bar->groupBy(['var1', 'var2']);
$bar->asArray()->all();
```
will result in
`Select var1, var2 from foo where ((abc = foo3 OR abc = foo3) OR abc = foo3) groupBy var1,var2;`
instead of
`Select var1, var2 from foo where ((abc = foo1 OR abc = foo2) OR abc = foo3) groupBy var1,var2;`

**Comment by Alex-Code** [comment]
How would the framework know you're in a loop?
You have to specify unique parameter names.

```php
foreach ($xy as $key => $x) {
  $bar->orWhere("abc = :xy{$key}", [":xy{$key}" => $x]);
}
```
