### ISSUE TITLE
Event ActiveRecord on EVENT_AFTER_UPDATE not "executed"

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii2#8468]
Hi,

I have an module, which handles "activities" now I wanna execute code based upon the 
ActiveRecord EVENT_AFTER_UPDATE but it's not "catchable" :(

So in the "catch module" i put the following code into the module file:

```
use yii\base\Event;
use app\modules\activity\models\Activity;

Event::on(Activity::className(), Activity::EVENT_AFTER_UPDATE, function($event){
    \Yii::$app->mailer->compose('hello-world')
        ->setFrom('test@test.net')
        ->setTo(\Yii::$app->params['adminEmail'])
        ->setSubject('TEST: Hello World')
        ->send();
});
```
Follwing the docs, I really miss a description on "which file" needs to handle which code to get the Events running...

Thanks for your support!
Philipp

**Comment by mdmunir** [comment]
> So in the "catch module" i put the following code into the module file:

what do you mean about "catch module"?

Try to put your code in file `config/bootstrap.php`

**Comment by philippfrenzel** [comment]
Hi mdmunir,

I put the code into the module Bootstrap, but still "no" event catched...

```
namespace app\modules\prospecting;

use yii\base\BootstrapInterface;

use \net\frenzel\activity\models\Activity;
use yii\base\Event;

Event::on(Activity::className(),Activity::EVENT_ACTIVITY_UPDATE,function($event){
	Yii::warning(get_class($event->sender) . ' is inserted');
});

/**
 * Bootstrap Interface
 */
class Bootstrap implements BootstrapInterface
{
	/**
	 * [bootstrap description]
	 * @param  [type] $app [description]
	 * @return [type]      [description]
	 */
	public function bootstrap($app)
	{

	}
}
```

**Comment by klimov-paul** [comment]
Unable to reproduce.
Following code:
```php
Event::on(Customer::className(), Customer::EVENT_AFTER_UPDATE, function($event) {
    echo get_class($event->sender) . ' is updated' . "\n";
});

$customer = Customer::find()->one();
$customer->name = 'new name';
$customer->save();
```

Works as expected.

Check your code.

**Comment by philippfrenzel** [comment]
@klimov-paul where do I have to put the code?! Into config/bootstrap? Pls. update documentation otherwise this super useful feature is so hard to setup, that people might get frustrated by implementing it... THX

**Comment by klimov-paul** [comment]
You may do it either at config or at bootstrap.
I can't see anything wrong with the documentation.

**Comment by philippfrenzel** [comment]
so acutally, putting it into the config does the job, but I'm a little bit disapointed, as I wanna put this "catch" into a module and not into the global app part... is their another way to manage it? As e.g. I wanna "sender module" and a "reciever module" - which will "install" and "update" without the user adapting the config/bootstrap.php ?

**Comment by philippfrenzel** [comment]
@klimov-paul - I found "a solution" - if I add the Module to the main.php config within the bootstrap array, then the events are beeing catched... I don't know if this will run into a "performance killer" but for now, it's working .-- Thanks!
