### ISSUE TITLE
Nested set Parent relation

### ISSUE THREAD

**Issue by Velm14** [yiisoft/yii2#8472]
Hello to everyone, I really need parent relation in nested set Yii2, I done this in Yii1.0.1, but how I can do this in second version. If developers read it, pls make a chance to do Eager loading parent in Yii2

**Comment by samdark** [comment]
Please elaborate. We don't have nested set support so you're probably using an extension. If it's true, please specify which one it is and what's missing exactly.

**Comment by Velm14** [comment]
Sory, I use NestedSetBehavior. https://github.com/creocoder/yii2-nested-sets . I am missing "parent" relation. I mean, that I can not do Eager loading in relation ( I canno't write such relation )

**Comment by klimov-paul** [comment]
Report this issue to the extension author.
