### ISSUE TITLE
Behavior extended property not present in FORMAT_JSON response

### ISSUE THREAD

**Issue by d-bo** [yiisoft/yii2#8479]
Hello !
I have a behavior defined to add **testField** property:

    class testBehavior extends Behavior
    {
        protected $testField;

        public function getTestField()
        {
            return $this->testField;
        }

        public function setTestField($value)
        {
            $this->testField = $value;
        }
    }

The model:

    public static function getTestVehicles()
    {
        $data = self::find()->all();
        foreach ($data as $k => $v) {
            $v->testField = $v->Id + 100;
        }
        return $data;
    }

There is no **testField** on response from controller:

    public function actionJson()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        return Model::getTestVehicles();
    }

**Comment by d-bo** [comment]
as the **testField** appears in template after

    return $this->render('template', Model::getTestVehicles())

**Comment by d-bo** [comment]
convert ActiveRecord object to array

    $data = self::find()->all();
    foreach ($data as $k => $v) {
        $v->testField = $v->Id + 100;
    }
    $data = \yii\helpers\ArrayHelper::toArray($data);

no merge between activerecord attributes and behavior properties

**Comment by mdmunir** [comment]
If you using `\yii\helpers\ArrayHelper::toArray()` try to override method `Model::fields()` http://www.yiiframework.com/doc-2.0/guide-rest-resources.html#overriding-fields

**Comment by klimov-paul** [comment]
@mdmunir's explanation is correct: you should override `fields()` method in your model in order to add extra fields to the response of `ArrayHelper::toArray()` and thus to REST controller response.

**Comment by d-bo** [comment]
can i make it dynamically from model ?
cause i want to override fields in special cases

like that

    public static function getTestVehicles()
    {
        $this->fields([
            'Id',
            'ModelName',
            'calc' => function($model) {
                return $model->Id + 100;
            }
        ]);
        $data = self::find()->all();

       return $data;
   }

**Comment by klimov-paul** [comment]
You may implement your `fields()` as you like.

**Comment by mdmunir** [comment]
Use `ArrayHelper::toArray()`, set parameter `$properties` as you like.
http://www.yiiframework.com/doc-2.0/yii-helpers-basearrayhelper.html#toArray()-detail

**Comment by d-bo** [comment]
thank you, ```$properties``` is the right way
