### ISSUE TITLE
yii\db\Schema::getLastInsertID fails with schema.sequence name in postgresql

### ISSUE THREAD

**Issue by pyd** [yiisoft/yii2#8483]
Hi all, after a framework update I receive this error from postgresql:

PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "admin.user_id_seq" does not exist    // see the way the sequence name is quoted

Since this fix https://github.com/yiisoft/yii2/commit/4f49feee8d2b0f0973ae1d0f29d66dccf9f06605 the sequence name is quoted with yii\db\Schema::quoteSimpleTableName.

Problem can be solved using yii\db\Schema::quoteTableName but I don't know what would happen with other dbms. Maybe this could be done in a new yii\db\pgsql\Schema::getLastInsertID method?

Note: the yii\db\pgsql\Schema::quoteSimpleTableName() override its parent's method but the code is the same. Maybe by choice.

Thanks.

**Comment by cebe** [comment]
looks like this line https://github.com/yiisoft/yii2/commit/4f49feee8d2b0f0973ae1d0f29d66dccf9f06605#diff-84149d0e707aedabae10e03f95c23bd0R316 needs to use `quoteTableName` instead of `quoteSimpleTableName`

@nineinchnick can you verify it please?

**Comment by nineinchnick** [comment]
@cebe yes, you're right. I can make a unit test for objects in a schema different than the default one.

**Comment by cebe** [comment]
that would be great!
