### ISSUE TITLE
maxlength does not work for textArea

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#8486]
```php
// model code
public function rules()
{
    return [
        [['type', 'description'], 'required'],
        [['type'], 'string', 'max' => 32],
        [['description'], 'string', 'max' => 256]
    ];
}

//view code
<?= $form->field($model, 'type')->textInput(['maxlength' => true]) ?>

//outputs
<input type="text" id="contracttype-type" class="form-control" 
name="ContractType[type]" maxlength="32">

<?= $form->field($model, 'description')->textArea(['maxlength' => true]) ?>

//output
<textarea id="contracttype-description" class="form-control" 
name="ContractType[description]" maxlength></textarea>

```

**Comment by unclead** [comment]
it has been implemented only for an activeTextInput. See #7440

**Comment by lynicidn** [comment]
@unclead but need for teaxarea too :)

**Comment by unclead** [comment]
i agree but in this case this is feature request and not bug :wink:

**Comment by klimov-paul** [comment]
Issue resolved by commit 0f04af1

**Comment by pstddc** [comment]
ловим баги с новыми кодировками в новом году
['comment', 'match', 'pattern' => '/^[0-9a-zа-я\-_\s]+$/isU'],
['comment', 'string', 'encoding' => '8bit', 'max' => 2048],

$form->field($request, 'comment')->textarea(['maxlength' => true])

**Comment by SilverFire** [comment]
@pstddc пожалуйста, создаёте отдельную задачу, если это проблема фреймворка.
