### ISSUE TITLE
Getting error message in AssetConverter.php ( filemtime(): stat failed for ...)

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8488]
Getting this error

http://prntscr.com/779bd1

**Comment by lynicidn** [comment]
may be need `js` ?

**Comment by turalsprofile** [comment]
no it's TypeScript:)

**Comment by turalsprofile** [comment]
I have following config

        'assetManager' => [
            'linkAssets' => true,
            'appendTimestamp' => true,
            'converter' => [
                'class' => 'yii\web\AssetConverter',
                'commands' => [
                    'ts' => ['js', 'tsc --out {to} {from}']
                ],
            ]
        ],

**Comment by lynicidn** [comment]
file exists?

**Comment by turalsprofile** [comment]
and after chmod 0777 of whole js folder, error disappeared

**Comment by lynicidn** [comment]
show please:
```bash
$ ls -l /var/www/frontend/web/js/lib/color.ts
```

**Comment by turalsprofile** [comment]
-rwxrwxrwx 1 root root 676 May 20 11:48 /var/www/frontend/web/js/lib/color.ts

**Comment by lynicidn** [comment]
try: `sudo chown www-data:www-data /var/www/frontend/web/js/lib/color.ts`

**Comment by klimov-paul** [comment]
This is not Yii issue.
If you have problems with `filemtime` please report them to php.net

**Comment by lynicidn** [comment]
@klimov-paul - in one case set `@` for silent error, but in second case `@` out O_o it remark imho

**Comment by lynicidn** [comment]
`@filemtime < filemtime`

**Comment by klimov-paul** [comment]
> in one case set @ for silent error, but in second case @ out

Indeed: b57b994
