### ISSUE TITLE
Docs: add some documentation about ActiveQuery class

### ISSUE THREAD

**Issue by realtebo** [yiisoft/yii2#8491]
When using gii to create a model, it asks to the user to create or not an ActiveQuery class paired with the model just being created.

I'm looking at official guide, at http://www.yiiframework.com/doc-2.0/guide-db-active-record.html. In this page, of course, there is nothing about ActiveQuery. It's right, but in all the section about "Working with databases" there is no info about this class.

What is its goal? When to create, when not? Some real-world examples of when it could be usefull. Etc..

Thanks for this marvellious framework, I'd thank you every day I use it.

**Comment by realtebo** [comment]
Just a postfix: I found what I was looking for at this url: http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#customizing-query-classes

Probably, a brief note about this topic in the Active Record guide could be enough. The important is that information is available and more easily findable.

**Comment by klimov-paul** [comment]
`ActiveQuery` is mentioned 46 times around the docs.
At http://www.yiiframework.com/doc-2.0/guide-db-active-record.html it is mentioned 38 times.

There is a specific topic related to it:
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#customizing-query-classes

I can't see what else can be improved here.
