### ISSUE TITLE
Sphinx DataProvider pagination over max_matches

### ISSUE THREAD

**Issue by disem** [yiisoft/yii2#8492]
If total count of possible results is greater then max_matches in sphinx options, there will be pagination issue that leads to exception.
This can be solved by setting somewhere max_matches property which should be used to calculate when "option max_matches" should be applied to the query. If pagesize*page > max_matches - add max_matches option.

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-sphinx/issues/12
