### ISSUE TITLE
Session::open() and ::close() return null

### ISSUE THREAD

**Issue by sasha-ch** [yiisoft/yii2#8493]
Hello,
Let's \yii\web\Session::open() and ::close() return true on success.
Now var_dump(Yii::$app->session->open()) show NULL. 
This may confuse people.

**Comment by klimov-paul** [comment]
Why these methods should return anything?
We may return a meaningful value from `Session::open()`, but for `Session::close()` there is no one: it invokes `session_write_close`, which return `void`.
What is a usecase for this?

**Comment by cebe** [comment]
they will throw exceptions on errors so its totally fine this way.

**Comment by klimov-paul** [comment]
@cebe, `Session::open()` will not throw an exception on failure, it will just log error silently:
https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L135

**Comment by sasha-ch** [comment]
Primary I mean Session::open(). And "return true" is a clear way say "ok, session opened".

**Comment by klimov-paul** [comment]
> I mean Session::open(). And "return true" is a clear way say "ok, session opened".

You can always use `Session::getIsActive()` for such check.
`Session::open()` usually called implicitly in the places, where its result is not checked.

**Comment by sasha-ch** [comment]
@klimov-paul, thanks.
