### ISSUE TITLE
UrlManager camel case issue

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8494]
I have following rule:
 
         'page/<id:\d+>/<action:\w+>' => 'page/<action>',

and `PageController` with `actionListChilds` 

When I enter to

          http://domain.com/page/12/list-childs

Getting following error message in log and 404 page

'Unable to resolve the request `"page/12/list-childs"`

But, when action name is only 1 word, like `list` instead of `list-childs` it works well.

As far as I know, `actionListChilds` translates into `list-childs` in rules. 

what am I doing wrong? why camel case named action brings this error message.

**Comment by klimov-paul** [comment]
Duplicates #8308
