### ISSUE TITLE
behavior if you are cloning an AR object

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#8498]
if youre cloning an AR object the cloned one is still the same as the original in the case of updating or inserting
you have to set `isNewRecord = false` and PK to `null`

example
```
$model = User::find('id = 1')->one();
$modelClone = clone $model;
$modelClone->attribute = 'xyz';
$modelClone->save();
```

expected (in my case) = new record
real behavior = $model is updated

this behavior has two sides on the one hand clone is working as expected because the object is cloned as normal but on the otherhand its also expected that the object is a new row.

Maybe a discussion for 2.1?

**Comment by samdark** [comment]
Why it's expected that the object is new row?

**Comment by klimov-paul** [comment]
I don't think so.
From the programming point of view everything is correct: all property values have been copied.
Why entire copy of the record should become a new record?

**Comment by ItsReddi** [comment]
because the cloneObject should lose the possibility to change the original object since the AR object is representing a database entry the database entry shouldnt be changed also.

**Comment by klimov-paul** [comment]
Disagreed.
Consider following code:

```php
$ar1 = Item::find()->where(['id' => 1])->one();
$ar2 = Item::find()->where(['id' => 1])->one();
$ar1->name = 'new name';
$ar1->save();
echo $ar2->name; // outputs 'old name'
```

Same is for the cloning.
You are responsible for your code consistency on your own, framework will not do it for you.
