### ISSUE TITLE
ActiveForm - "continue" method?

### ISSUE THREAD

**Issue by szewciu** [yiisoft/yii2#8502]
I think for ActiveForm widget class should be continue method called with 
<?php $form = ActiveForm::continue(); ?> that allows render a part of a form from partial view and they both constitute on, the same form. Or there is any other way to do this?

**Comment by klimov-paul** [comment]
Good old `require('path/to/file.php')` will do the trick for you.
Or use `View::render('file.php', ['form' => $form])`
