### ISSUE TITLE
Theme is not applying, though Theme is attached in configuration 

### ISSUE THREAD

**Issue by maheshtc** [yiisoft/yii2#8503]
I have attached theme correctly inside theme directory and configuration file

``` php
[view] => Array
                (
                    [theme] => Array
                        (
                            [pathMap] => Array
                                (
                                    [@app/views] => @app/themes/advanced/views/
                                    [@app/modules] => @app/themes/advanced/modules
                                    [@app/widgets] => @app/themes/advanced/widgets
                                )

                            [baseUrl] => /themes/advanced
                        )

                )
```

It is taking default main.php layout from views directory. but it should take main.php layout from theme directory. Please suggest solution what could be the problem for this.

It is giving fatal error 

``` php
Class 'frontend\assets\AppAsset' not found
in /var/www/cbmp/sitefrontend/views/layouts/main.php at line 12. 
```

Actual asset file located inside 

`/var/www/cbmp/sitefrontend/themes/advanced/views/layouts/main.php`

**Comment by dynasource** [comment]
make sure either `frontend\assets\AppAsset` exists or that the yii namespace is loaded in your bootstrap.
