### ISSUE TITLE
Pjax in ENV_TEST gives an warning on ob_end_clean in widget

### ISSUE THREAD

**Issue by joester89** [yiisoft/yii2#8506]
When using a widget which uses Pjax and the environment is test, gives a warning. This happens because the widget tries an ob_end_clean when a exception is thrown. Pjax itself throws an ExitException sinds the appliction is terminated and before that gets and cleans the output buffer.

Problem in \yii\base\Widget.php in function widget

        try {
            /* @var $widget Widget */
            $config['class'] = get_called_class();
            $widget = Yii::createObject($config);
            $out = $widget->run();
        } catch(\Exception $e) {
            ob_end_clean();
            throw $e;
        }

Possible solution

        try {
            /* @var $widget Widget */
            $config['class'] = get_called_class();
            $widget = Yii::createObject($config);
            $out = $widget->run();
        } catch(\Exception $e) {
            if(ob_get_level() > 0) {
                ob_end_clean();
            }
            throw $e;
        }

**Comment by cebe** [comment]
Fixed, thanks for reporting!
