### ISSUE TITLE
Service locator / DI container aliasing

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#8509]
As i see it is not currently possible to make alias from one service to another, i think this feature should be added similar like it is now in `Symfony2` or `ZF2`. I can handle this one if needed.

@samdark @qiangxue what are your thoughts on this one ?

**Comment by cebe** [comment]
can you give a use case for this?

**Comment by Ragazzo** [comment]
```php
'port.adapter.persistence.redis.CountryRepository' => function ($serviceLocator) {},
'port.adapter.persistence.doctrine2.CountryRepository' => function ($serviceLocator) {},

'domain.model.country.CountryRepository' => 'port.adapter.persistence.redis.CountryRepository',

'infrastructure.MCryptPasswordService' => function ($serviceLocator) {},
'infrastructure.AnyOtherPasswordCryptingService' => function ($serviceLocator) {},

'domain.model.PasswordService' => 'infrastructure.AnyOtherPasswordCryptingService'
```

**Comment by Ragazzo** [comment]
Working on this one

**Comment by qiangxue** [comment]
Are you sure this is not supported? Have you tried it?

**Comment by Ragazzo** [comment]
no, i did not tried it with last version, but i looked through the code and have not found anything similar. Did i missed anything?

**Comment by Ragazzo** [comment]
@qiangxue just reread docs and saw this:

```php
// register an interface
// When a class depends on the interface, the corresponding class
// will be instantiated as the dependent object
$container->set('yii\mail\MailInterface', 'yii\swiftmailer\Mailer');
```

but i am not sure if it is the thing that is needed, as you can see in my example i refer alias by alias, not by a particular class

**Comment by qiangxue** [comment]
Please try it before you set forth to implement. It should already work although the documentation doesn't write about it.

**Comment by Ragazzo** [comment]
Ok

**Comment by dynasource** [comment]
this is actually quite straightforward
