### ISSUE TITLE
about redirect function for response object

### ISSUE THREAD

**Issue by incNick** [yiisoft/yii2#8510]
In the document said like

you can use $response->redirect($url)->send() confirm not more content append to response, but in my test I must add exit after above.

For example,
$response->redirect($url)->send();
$hd=fread('test.txt', 'w');

ok, you can see test.txt created, except modify to 
$response->redirect($url)->send(); exit;

**Comment by cebe** [comment]
in an action you can use `return  $response->redirect($url);`. in other places of the appliciation you may call `Yii::$app->end();`
