### ISSUE TITLE
DbSession fails

### ISSUE THREAD

**Issue by vskvortsov** [yiisoft/yii2#8511]
Just created a fresh advanced app. 
Updated default session to yii\web\DbSession

On the second page load a got 502 (if i delete phpsessid - the first page load is ok)
I found that my php-fpm ( 5.4.40-1~dotdeb+wheezy.1) crashes with SIGSEGV
Starting XDEBUG i can avoid the crash and got this in my log files:

2015/05/21 18:32:59 [error] 6718#0: *228 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Yii::$classMap in /media/sf_plusplus-source/vendor/yiisoft/yii2/BaseYii.php on line 274
PHP message: PHP Stack trace:
PHP message: PHP   1. yii\web\DbSession->writeSession($id = *uninitialized*, $data = *uninitialized*) /media/sf_plusplus-source/vendor/yiisoft/yii2/web/DbSession.php:0
PHP message: PHP   2. yii\BaseYii::autoload($className = *uninitialized*) /media/sf_plusplus-source/vendor/yiisoft/yii2/web/DbSession.php:171" while reading upstream, client: 192.168.1.5, server: plus-plus.dev, request: "GET /index.php?r=site%2Findex HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "plus-plus.dev", referrer: "http://plus-plus.dev/index.php?r=site%2Fcontact"

It crashes right after it enters writeSession for the second time, this line: (DbSession.php, line: 171)
$expire = time() + $this->getTimeout();

**Comment by cebe** [comment]
not sure what is wrong in your environment but it is there: https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L69

**Comment by vskvortsov** [comment]
I found my problem. It was apc extension, actually. After i've turned off opcode caching ( i still use it for data caching) the problem is gone.
