### ISSUE TITLE
URL Encoding

### ISSUE THREAD

**Issue by osCMattiFinn** [yiisoft/yii2#8512]
This does not work as expected (why have it in the first place, it's extremely ugly and not user friendly???).

The following URL returns a 404 NOT FOUND:

index.php?r=module%26method%3Dpayment%26module%3DAuthorizenet%26action%3Dedit

This returns the correct page:

index.php?r=module&method=payment&module=Authorizenet&action=edit

Where do I need to edit to switch off URL encoding?

**Comment by klimov-paul** [comment]
How did you generate such URL?

**Comment by osCMattiFinn** [comment]
Html::a('Edit', ['/module&method=' . $method . '&module=' . $info->code . '&action=edit'], ['class' => 'btn btn-primary'])

We all know that Yii2 encodes all URLs - I have never seen any other application do this!!

**Comment by klimov-paul** [comment]
Did you evere read a docs?
This one in particular:
https://github.com/yiisoft/yii2/blob/master/docs/guide/runtime-routing.md

**Comment by osCMattiFinn** [comment]
Did you not ever learn manners?

I makes no difference, the structure of the encoded URL is exactly the same and returns a 404 NOT FOUND

**Comment by klimov-paul** [comment]
> Did you not ever learn manners?

Same to you.

> I makes no difference, the structure of the encoded URL is exactly the same and returns a 404 NOT FOUND

So you do not read the docs.
In order to create a URL from different parameters you should specify them as array keys.
So instead of:
```php
Html::a('Edit', [
    '/module&method=' . $method . '&module=' . $info->code . '&action=edit'
], ['class' => 'btn btn-primary'])
```
It should be:
```php
Html::a('Edit', [
    '/module', 
    'method'=> $method, 
    'module' => $info->code, 
    'action'=>'edit'
], ['class' => 'btn btn-primary'])
```
