### ISSUE TITLE
[suggest] model inititialization

### ISSUE THREAD

**Issue by flamerecca** [yiisoft/yii2#8516]
When I new a model, I find out that even the rule set an attribute to IntergerOnly, it is not yet defined. Sometimes it will cause some errors. I have to set the attribute to 0 after newing the model.

Maybe It's a good idea to set all IntergerOnly attributes to 0, and all string attribute to empty string first?

**Comment by qiangxue** [comment]
You can do this in `init()` if you really need it. But in general, this is not a good idea because a model is not just for form input purpose.

**Comment by flamerecca** [comment]
Interesting, Thanks!
