### ISSUE TITLE
BaseUrl - Ability to configure which UrlManager to use

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#8518]
Would be great if we can configure which UrlManager we wish to use in https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseUrl.php

Im in front-end and wish to link to backend using an alias. 
Apologies if this is already included as im fairly new to the framework.

**Comment by klimov-paul** [comment]
Don't use helper - use particular `UrlManager` component.

**Comment by BAWES** [comment]
In Advanced template, I created separate `UrlManager` components to link between `frontend` and `backend`

`UrlManager::createUrl()` does not let me use alias `@web`

**Comment by cebe** [comment]
why would you use `@web` in createUrl() ?

**Comment by BAWES** [comment]
My urls change based on environment setup, I'd like to link to an image in `frontend` at `@web/images/univ/image.jpg` from the `backend`

If I use `Yii::setAlias('frontend', dirname(dirname(__DIR__)) . '/frontend');` , I get the path not the web address. 

What's the best way to link to an image in frontend from the backend?

**Comment by cebe** [comment]
`createUrl()` is used to build URLs to controller actions, if you just want to link to a file you can define an alias like `@frontendweb` and use it directly.

**Comment by BAWES** [comment]
How to define `@frontendweb` alias to get the hostname of front-end from the backend?

**Comment by cebe** [comment]
`Yii::setAlias('@frontendweb', http://example.com/frontend)` ?

**Comment by BAWES** [comment]
Then we create a a different alias for each environment (production, development, teamMember#1, teamMember#2)? Doesn't seem very convenient

**Comment by cebe** [comment]
for SSL you could leave it protocol relative, for the environment, just set it in local config
