### ISSUE TITLE
Add a method to Formatter to allow reverse datetime conversion

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#8521]
It would help a lot if we could have a method in Formatter class that does the reverse conversion of datetime value, e.g. from client datetime value to a server datetime value. Currently I have to swap the values of ```Formatter#timeZone``` and ```Formatter#defaultTimezone``` to run the conversion with help of ```asDatetime```, then restore the original settings after I'm done.

```php
            $userDate = Yii::$app->formatter->asDate(time());
			$userTimezone = Yii::$app->formatter->timeZone;
			$defaultTimeZone = Yii::$app->formatter->defaultTimeZone;
			Yii::$app->formatter->timeZone = $defaultTimeZone;
			Yii::$app->formatter->defaultTimeZone = $userTimezone;
			$nextInvocation = Yii::$app->formatter->asDatetime(
				strtotime("+". $this->schedule_time . "hours",
					strtotime(date('Y-m-d', strtotime($userDate)))), 'php:Ymd H:i:s');
			Yii::$app->formatter->timeZone = $userTimezone;
			Yii::$app->formatter->defaultTimeZone = $defaultTimeZone;
```

**Comment by cebe** [comment]
the DateValidator is used for the reverse direction.

**Comment by dryu** [comment]
Could you please elaborate how DateValidator is used for reverse conversion? Isn't this is something that better fits Formatter class?

**Comment by cebe** [comment]
formatter is for output, validators are for input.

http://stuff.cebe.cc/yii2docs/guide-tutorial-core-validators.html#date
