### ISSUE TITLE
urlManager, createUrl & generateRandomString

### ISSUE THREAD

**Issue by pedros80** [yiisoft/yii2#8525]
if a string generated by `Yii::$app->getSecurity()->generateRandomString()` contains a minus sign `-` and is passed as a named parameter to `Url::toRoute()`, the rules defined in `urlManager` for re-writing can not be applied and simple 'clean url' appears.

I changed `base/Security.php`, line 506 to 

`return strtr(substr(base64_encode($bytes), 0, $length), '+/', '__');  # note 2nd underscore` 

e.g. in my account password reset email

    Please click the link below to complete your password reset.
    http://MYDOMAIN/reset/79/ipYoDVtpB9qFU4QIdAYnErN8zBnx8FV5

vs

    Please click the link below to complete your password reset.
    http://MYDOMAIN/user/recovery/reset?id=96&code=Vl2ZPX9o_5i-KzeAnaiKLZMwjDjnlT-c

Note the minus signs in the second url...

**Comment by cebe** [comment]
what is the problem here? using `-` in url is just fine.

**Comment by pedros80** [comment]
it is not a problem with having a minus sign in the url as such, rather in the parameter that will be passed to 

               //web/UrlManager.php line 327-334 in `createUrl()`

                if ($url === false) {
                foreach ($this->rules as $rule) {
                    if (($url = $rule->createUrl($this, $route, $params)) !== false) { # always false if string contains minus sign
                        $this->_ruleCache[$cacheKey][] = $rule;
                        break;
                    }
                }
            }

it seems when the string contains a minus sign `$rule->createUrl()` will always return `false` so the url returned is of the form of the second example.

**Comment by klimov-paul** [comment]
Same as #4585 : you should adjust your URL rule patterns to accept dash (-) in this case.
