### ISSUE TITLE
AppAsset Frustration

### ISSUE THREAD

**Issue by jwenk** [yiisoft/yii2#8526]
Hi,

This is frustrating. I have this file:

<?php

namespace app\themes\brave;

use yii\web\AssetBundle;

class ThemeAsset extends AssetBundle
{
    //public $basePath = '@app/themes/brave/asset';
    //public $baseUrl = '@web/assets';
    public $sourcePath = '@app/themes/brave/asset';
    public $css = [
        'css/test.css',
    ];
    public $js = [
    ];
}

I register the Asset in my main layout:

	use app\themes\brave\ThemeAsset;
	ThemeAsset::register($this);

The file is published but is not showing on the rendered html.

Anyone can advise?

**Comment by nunomaduro** [comment]
Are you calling head() function on your main layout ? For example like this:

use app\themes\brave\ThemeAsset;
ThemeAsset::register($this);
$this->head();

**Comment by jwenk** [comment]
Hi, 

	use app\themes\brave\ThemeAsset;
	ThemeAsset::register($this);
	$this->head();

I just tried it, what it output is this:

<![CDATA[YII-BLOCK-HEAD]]>		<meta charset="utf-8">

no trace of my css file yet. 

Thanks

**Comment by Faryshta** [comment]
you need to include the entire life cycle of the view http://www.yiiframework.com/doc-2.0/guide-structure-views.html#creating-layouts

<![CDATA[YII-BLOCK-HEAD]]>

Is meant to be replaced when you call `endBody` and `endPage` on the layout.

http://www.yiiframework.com/doc-2.0/guide-structure-views.html#creating-layouts

**Comment by jwenk** [comment]
That is great. It came out. =)

Thanks a lot
