### ISSUE TITLE
Add get currency code by iso code via Yii::$app->formatter

### ISSUE THREAD

**Issue by bupy7** [yiisoft/yii2#8527]
Add get currency code by iso code via Yii::$app->formatter as in Symphony library 

```
echo Symfony\Component\Intl\Intl::getCurrencyBundle()->getCurrencySymbol('RUB');
```

```
.руб
```

**Comment by bupy7** [comment]
For those looking for. Temp solution:

```php
<?php

namespace common\components;

/**
 * @inheritdoc
 * 
 * @author Belosludcev Vasilij http://mihaly4.ru
 */
class Formatter extends \yii\i18n\Formatter
{
    
    /**
     * Return symbol currency by iso code in $currency parameter.
     * 
     * @param string $currency the 3-letter ISO 4217 currency code indicating the currency to use.
     * @return mixed
     * @example RUR => .руб
     */
    public function getCurrencySymbol($currency = null)
    {
        $string = $this->asCurrency(0, $currency);
        $symbol = mb_ereg_replace('^[\d]*.[\d]*.', '', $string);
        return $symbol;
    }
    
}
```

**Comment by cebe** [comment]
what do you need this for? you can just instantiate an IntlFormatter and get it from there...

**Comment by bupy7** [comment]
@cebe I would like to it to be initially to Formatter component. Very often need get symbol of currency without formatting currency. It yes, then what you suggest - this option, but what for so? Why not from initially in component?

**Comment by cebe** [comment]
> Very often need get symbol of currency

I am interested in these cases. Where/when do you need it, please name concrete examples.

**Comment by bupy7** [comment]
@cebe To UI, when can enter few option price of (example) USD, UER, RUB, UAH.

**Comment by samdark** [comment]
You mean these?

![Currencies](https://cloud.githubusercontent.com/assets/47294/7822403/f0704be8-03fd-11e5-93ff-af113c99a0d5.png)

**Comment by bupy7** [comment]
@samdark hz =)  I not known what you do =) 

As example:

![screenshot at 27 01-26-08](https://cloud.githubusercontent.com/assets/5145037/7822520/7f8f6a32-040f-11e5-96ce-091f3505706f.png)

symbol as suffix of value to textInput with mask.

**Comment by samdark** [comment]
So basically you're displaying these. OK.

**Comment by nkovacs** [comment]
This is based on Symfony's solution, it's a bit more robust and returns more info:

```php
/**
 * Return currency info
 * @return array:
 *  - string, currency symbol
 *  - boolean, true if the symbol is in front of the amount
 *  - integer, number of decimals
 */
public static function getInfo($currency = null, $options = [], $textOptions = [])
{
    // Hack taken from Symfony \Symfony\Component\Form\Extension\Core\Type\MoneyType
    $pattern = Yii::$app->formatter->asCurrency(123, $currency, $options, $textOptions);

    // the spacings between currency symbol and number are ignored, because
    // a single space leads to better readability in combination with input
    // fields
    // the regex also considers non-break spaces (0xC2 or 0xA0 in UTF-8)
    preg_match('/^([^\s\xc2\xa0]*)[\s\xc2\xa0]*123([,.]0+)?[\s\xc2\xa0]*([^\s\xc2\xa0]*)$/u', $pattern, $matches);

    $prefix = false;
    $decimals = 0;
    $symbol = '';

    if (!empty($matches[1])) {
        $symbol = $matches[1];
        $prefix = true;
    } elseif (!empty($matches[3])) {
        $symbol = $matches[3];
        $prefix = false;
    }
    if (!empty($matches[2])) {
        $decimals = strlen($matches[2]) - 1;
    }

    return [$symbol, $prefix, $decimals];
}
```

I needed it to format currencies in an angular filter the same way they're formatted by php, and to display a bootstrap input addon:

```php
if ($prefix) {
    $input = '<div class="input-group"><div class="input-group-addon">' . $symbol . '</div>{input}</div>';
} else {
    $input = '<div class="input-group">{input}<div class="input-group-addon">' . $symbol . '</div></div>';
}
```

**Comment by maxxer** [comment]
Not exactly the same need, but I'm facing a similar problem: get the current decimal and thousand separator.

Right now I can get it via `Yii::$app->formatter->decimalSeparator` but **only** if it has been set in configuration. If it comes from *intl* that value is empty, so I have to obtain it via  (thanks to @cebe for the hint):

```php
$formatter = new NumberFormatter(Yii::$app->formatter->locale, NumberFormatter::DECIMAL);
$separator = $formatter->getSymbol(NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
```

it would be nice that `yii\i18n\Formatter::decimalSeparator` returns the currently used value, not only the one overridden in config.

**Comment by cebe** [comment]
As already pointed out in https://github.com/yiisoft/yii2/pull/14607#issuecomment-322164066 there should be a separate component to return locale related information like this.
