### ISSUE TITLE
StringHelper::endsWith() seems not working ?

### ISSUE THREAD

**Issue by osnwach** [yiisoft/yii2#8533]
I am having an issue with; StringHelper::endsWith()
It seems not to be working.

whereas startsWith() is working okay, but StringHelper::endsWith() is not working for me.

I tried: 
StringHelper::endsWith('bio1998B2.png', '.png', $caseSensitive = false );

please kindly check and confirm that StringHelper::endsWith() is working as expected !

Warm Regards !!!

**Comment by mdmunir** [comment]
```php
StringHelper::endsWith('bio1998B2.png', '.png', false );
```

**Comment by osnwach** [comment]
@mdmunir 
I just tried;
 StringHelper::endsWith('.bio1998B2.png', '.png', false )

I am still having same issue. Kindly try it yourself yourself ?

It is not working for me.

**Comment by mdmunir** [comment]
What do you mean "not working"?
```php
<?php

namespace app\commands;

use yii\helpers\StringHelper;

/**
 * Description of TestController
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class TestController extends \yii\console\Controller
{
    public function actionIndex()
    {
        if(StringHelper::endsWith('bio1998B2.png', '.png', false )){
            echo "True\n";
        }  else {
            echo "False\n";
        }
    }
}
```
![screenshot from 2015-05-24 13 18 18](https://cloud.githubusercontent.com/assets/5828252/7786937/6c8fe726-0217-11e5-9136-c92fa25c6813.png)

**Comment by samdark** [comment]
Works for me. `StringHelper::endsWith('bio1998B2.png', '.png', false);` is `true`.
