### ISSUE TITLE
IDE Autocomplete for ActiveRecord fields in Console app

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#8534]
I'm using the Advanced application template and my IDE isn't autocompleting `ActiveRecord` table columns within controller actions (console app)

**Comment by samdark** [comment]
What's your IDE name and version? Which columns it doesn't autocomplete exactly? Can you show some code?

**Comment by BAWES** [comment]
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.8.0_25; Java HotSpot(TM) 64-Bit Server VM 25.25-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_25-b17
System: Mac OS X version 10.10.3 running on x86_64; UTF-8; en_US (nb)

    <?php

    namespace console\controllers;

    use Yii;
    use yii\helpers\Console;
    use common\models\Admin;

    /**
     * Test Controller
     */
    class TestController extends \yii\console\Controller {

    public function actionListAdmins() {
        $allAdmins = Admin::find()->all();
        foreach($allAdmins as $admin){
            echo $admin->admin_name."\n"; //This works but "admin_name" is not visible my autocomplete
        }
        
        return self::EXIT_CODE_NORMAL;
    }

    }


The properties listed in the comments for table columns aren't autocompleting. Everything else is autocompleting:

    /**
     * Admin model
     *
     * @property integer $admin_id
     * @property string $admin_name 
     * @property string $admin_email
     * @property string $admin_auth_key
     * @property string $admin_password_hash write-only password
     * @property string $admin_password_reset_token
     * @property string $admin_datetime
     */
    class Admin extends ActiveRecord implements IdentityInterface {

Autocomplete works fine for `frontend` and `backend`

**Comment by samdark** [comment]
If it works fine in one place but doesn't in another means NetBeans supports `@property` (for years actually) but has a bug that meta read isn't used in that case. phpdoc is correct so we can't fix it on Yii side. Please report to NetBeans team.
