### ISSUE TITLE
logger does not work after run console command

### ISSUE THREAD

**Issue by nepster-web** [yiisoft/yii2#8538]
There is a test console command:
```
public function actionAdvertInTop()
{
        Yii::error('Error', 'services');

        $fp = fopen(Yii::getAlias("@common/test.txt"), "a+");
        fwrite($fp, 'Test');
        fclose($fp);
}
```

use: php yii services/advert-in-top

It works: creates file and writes logs

but if you run this command from the application, for example:
```
pclose(popen('/usr/bin/php /home/nepster/www/site.ru/yii services/advert-in-top /dev/null &'));
```
OR

```
exe('/usr/bin/php /home/nepster/www/site.ru/yii services/advert-in-top');
```

Then it creates file, but not logs.

**why do not work logs in this situation ?**

**Comment by cebe** [comment]
looks like your webserver has not the permission to access the files.

**Comment by nepster-web** [comment]
thank you very much. I could not understand this.
