### ISSUE TITLE
renderAjax doesn't loads assets bundle JS files

### ISSUE THREAD

**Issue by xskif** [yiisoft/yii2#8540]
Hi.
I have products search page with the only search form and pjax container. Search request might returns products list with `FancyboxWidget` that registers `FancyboxAsset` in the view like that:
```php
        $view = $this->getView();
        $view->registerAssetBundle(FancyboxAsset::className());
```

`actionSearch` in `ProductsController` looks like that:
```php
    public function actionSearch()
    {
        $searchModel = new ProductSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->get());
        return $this->renderAjax('_searchResult', [
            'dataProvider' => $dataProvider
            'searchModel' => $searchModel
        ]);
    }
```

It works fine without ajax request, but if i use Pjax widget and `renderAjax` method to render search result, all js files inside FancyboxAsset are gone. There are only registred js strings like `$view->registerJs("$('{$this->selector}').fancybox($options)");`. CSS files loading well.

I have the same issue with another widgets, like kartik GridView with expanded columns.

**Comment by xskif** [comment]
The problem still there, `renderAjax` behavior contrary to documentation.

**Comment by SilverFire** [comment]
Duplicates #3680

**Comment by xskif** [comment]
> Scripts are being removed on Pjax prefiltering.

So, what that means?

**Comment by SilverFire** [comment]
It is a common problem and we are going to fix it.
For detailed information you can read related issues.

**Comment by samdark** [comment]
Let's use issue in PJAX repo.

**Comment by SilverFire** [comment]
Yepp.

**Comment by SilverFire** [comment]
Should be fixed by https://github.com/yiisoft/jquery-pjax/pull/30
