### ISSUE TITLE
optimisticLock bug

### ISSUE THREAD

**Issue by sp1995** [yiisoft/yii2#8544]
It appears that optimistic locking has a bug. When I implement everything according to documentation and attempt to read 'version' right after save(), such as to send it back to my user through ajax, the new 'version' is not updated.

    $order->version equals 0

However, when I access 'version' through getOldAttribute('version') the code works as expected.

    try {
        if($order->save(false)) {
            return ['data' => array('validated'), 'tag' => array($order->tag), 'version' => array($order->getOldAttribute('version'))];`
        else
            return ['data' => array('error'), 'reason' => array('Server error while saving order.')];
    }
    catch(StaleObjectException $e) {
        return ['data' => array('error'), 'reason' => array('The order has been modified. Please, look up this order again.')];
    }

**Comment by sp1995** [comment]
So, another words, immediately after updating an existing record (within the same request):

    $order->version = 0;

but

    $order->getOldAttribute('version') = 1;

I am expecting this to be in reverse.

**Comment by sp1995** [comment]
Looking into the source code, looks like 'version' is added to and incremented in `$values[]` array and copied into `$_oldAttributes`, but is not copied into `$_attributes`?

    protected function updateInternal($attributes = null)
    {
        if (!$this->beforeSave(false)) {
            return false;
        }
        $values = $this->getDirtyAttributes($attributes);
        if (empty($values)) {
            $this->afterSave(false, $values);
            return 0;
        }
        $condition = $this->getOldPrimaryKey(true);
        $lock = $this->optimisticLock();
        if ($lock !== null) {
            $values[$lock] = $this->$lock + 1;
            $condition[$lock] = $this->$lock;
        }
        // We do not check the return value of updateAll() because it's possible
        // that the UPDATE statement doesn't change anything and thus returns 0.
        $rows = $this->updateAll($values, $condition);

        if ($lock !== null && !$rows) {
            throw new StaleObjectException('The object being updated is outdated.');
        }

        $changedAttributes = [];
        foreach ($values as $name => $value) {
            $changedAttributes[$name] = isset($this->_oldAttributes[$name]) ? $this->_oldAttributes[$name] : null;
            $this->_oldAttributes[$name] = $value;
        }
        $this->afterSave(false, $changedAttributes);

        return $rows;
    }

**Comment by klimov-paul** [comment]
Issue resolved by commit 51a442d

**Comment by sp1995** [comment]
I looked at the fix and without testing it, it seems that the fixed code will now produce the same result for

     $order->version will be 1 and 
     $order->getOldAttribute('version') will also be 1 instead of 0

**Comment by klimov-paul** [comment]
This is expected: as version value has been just updated, so it is not 'dirty'.

**Comment by sp1995** [comment]
OK. Cool. Thanks!
