### ISSUE TITLE
Own User component for Module

### ISSUE THREAD

**Issue by progreg** [yiisoft/yii2#8556]
Hello, i want to module had own user component with own session & own AuthManager. 

I do the following :
```php
$modules = [
    'backend' => [
        'class' => '\backend\Module',
        'components' => [
            'user' => [
                'class' => 'yii\web\User',
                'identityClass' => 'backend\models\User',
                'loginUrl' => ['/backend/default/login'],
                'identityCookie' => ['name' => 'backend_identity', 'httpOnly' => true],
                'idParam' => 'backend__id',
                'authTimeoutParam' => 'backend__expire',
                'absoluteAuthTimeoutParam' => 'backend__absoluteExpire',
                'returnUrlParam' => 'backend__returnUrl',
            ],
            'authManager' => [
                'class' => 'yii\rbac\DbManager',
                'itemTable' => '{{%backend_auth_item}}',
                'itemChildTable' => '{{%backend_auth_item_child}}',
                'assignmentTable' => '{{%backend_auth_assignment}}',
                'ruleTable' => '{{%backend_auth_rule}}',
            ],
        ],
    ],
];
```

But in User component you have hardcoded getter of AuthManager from Application SL
```php
    public function can($permissionName, $params = [], $allowCaching = true)
    {
        $auth = Yii::$app->getAuthManager();
        ... 
        return $access;
    }
```
So, I think it would be great if we will have public property User::authManager that will be used in User::can method, because if not then we must override all private properties and methods in User component.

For example instead of
```php
    public function can($permissionName, $params = [], $allowCaching = true)
    {
        $auth = Yii::$app->getAuthManager();
        ... 
        return $access;
    }
```
we can do following or something else:
```php
    public $authManager = null;
    public function can($permissionName, $params = [], $allowCaching = true)
    {
        $auth = ($this->authManager === null) ? Yii::$app->getAuthManager() : $this->authManager;
        ... 
        return $access;
    }
```

Thanks

**Comment by samdark** [comment]
An option currently is to move it to separate application (like it's done in advanced project template).

**Comment by samdark** [comment]
@progreg is `can()` method your only problem?

**Comment by progreg** [comment]
@samdark ,

> An option currently is to move it to separate application (like it's done in advanced project template).

Yes i know, but target is make it is as module component, not application. Also if we can separate backend and frontend via modules then it is not bad idea to provide this option.

> is can() method your only problem?

Yep. It is not a problem to override User component, but why duplicate code?

**Comment by samdark** [comment]
I see. It's valid suggestion. @yiisoft/core-developers any suggestions about how to handle it?

**Comment by klimov-paul** [comment]
We can introduce a property inside `yii\web\User` for actual auth manager specification in the way similar to:
https://github.com/yiisoft/yii2/blob/master/framework/web/CacheSession.php#L50

However, even doing so using of the component declared inside some module will be not available unless direct object set somewhere at module `init()`.

**Comment by progreg** [comment]
How about just make public method `getAuthManager` in User component? Then we can override it to set own authManager.
For Example:

```php
    public function can($permissionName, $params = [], $allowCaching = true)
    {
        $auth = $this->getAuthManager();
        ... 
        return $access;
    }
    public function getAuthManager()
    {
        return Yii::$app->getAuthManager();
    }
```
and child component will be:

```php
namespace backend\components;

class User extends yii\web\User
{
    public function getAuthManager()
    {
        return Yii::$app->getModule('backend')->authManager;
    }
}
```

**Comment by samdark** [comment]
Yep, I like it better than a property...

**Comment by samdark** [comment]
It's the same style as https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecord.php#L131

**Comment by samdark** [comment]
Done. Thanks for suggestion.
