### ISSUE TITLE
Specific rule on UrlManager

### ISSUE THREAD

**Issue by nunomaduro** [yiisoft/yii2#8557]
Hey,

It is possible to do a specific rule on url manager that redirect the user to another application ( like backend ), like this:

```
        'urlManager' => [
            'rules' => [
                '' => 'backend/site/default/index',
            ]
        ],
```

**Comment by klimov-paul** [comment]
@nunomaduro, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
