### ISSUE TITLE
Sphinx order by RAND()

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2#8558]
Hi,

Still in the process of porting my current application from Yii to Yii 2 and come across (what I think) is a limitation with Sphinx.

In Yii 1 I could run the following SphinxQL: SELECT id FROM index_name ORDER BY RAND();

However, in Yii2 it doesn't seem to actually pay attention to the RAND() function.

I've tried two different approaches.
This one seems to ignore the RAND() and always returns the same row, if you do queryAll() it returns the same results each time.
$sql =  "SELECT id FROM index_name ORDER BY RAND()";
$query = Yii::$app->sphinx->createCommand($sql)->queryOne();

Also, this way through an exception or can't find the column.
$query->select('id')
    ->from('index_name')
    ->orderBy('RAND()') // ->orderBy('RAND')
    ->limit(10);

Is there support for this? Or am I going at this wrong?

Thanks,
Gary

**Comment by klimov-paul** [comment]
This is the question to the Sphinx Search Engine project. It does not related to Yii.
