### ISSUE TITLE
extra onConditions for relations.

### ISSUE THREAD

**Issue by yomexzo** [yiisoft/yii2#8559]
I have a relationship between `parents` and `special_children`.
With plain SQL, i can get `parents` and their `special_children` as shown below. How do I achieve same with Yii ActiveRecord and relations.

```
SELECT * 
FROM parents
LEFT JOIN children special_children ON special_children.parent_id = parents.id AND special_children.type = "special"
```

so I can now make second query with `special_children` ids gotten from above to get the relation like this

```
SELECT *
FROM children special_children
WHERE id IN (1, 2, 3, 4 ...)
```

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for bugs and feature requests.

**Comment by yomexzo** [comment]
Hi @samdark, I asked the question following my earlier raise issue - https://github.com/yiisoft/yii2/issues/8496

I was hoping it will better clear what I was trying to achieve. It is still a blocker for my project and have had to use a very expensive approach.

**Comment by samdark** [comment]
I don't quite get it to be honest. You can use `joinWith` and `andWhere` when defining relation. What's the problem with it?

**Comment by yomexzo** [comment]
Ordinarily i would do the below

	// in Parent model
	public function getSpecialChildren() {
		return $this->hasMany(Children::className(), ['id' => 'parent_id'])->onCondition('type = "special"');
	}

	// Then I call as follows
	Parent::find()->joinWith('specialChildren')->all();

With the above, the first query is fine as shown below

	SELECT * 
	FROM parents
	LEFT JOIN children special_children ON special_children.parent_id = parents.id AND special_children.type = "special"


BUT, the second query carries the `onCondition` from the relation definition above as shown below

	SELECT *
	FROM children special_children
	WHERE id IN (1, 2, 3, 4 ...) AND type = "special"

The above *would* work well because `type` is in `children` table. It becomes an issue when the extra onCondition is from the primary table as seen in - https://github.com/yiisoft/yii2/issues/8496 . Would get column not found in secondary table.

Ideally, the extra onCondition should only be used in the first query when `joinWith` is used. Since we can already get the `ids`

Clear?

**Comment by master-7** [comment]
I have the same issue. Why there is no clear answer to this question?

**Comment by master-7** [comment]
Problem is here https://github.com/yiisoft/yii2/blob/2.1/framework/db/ActiveQuery.php#L202
Why do this?

**Comment by master-7** [comment]
This is a detailed description prolem
http://stackoverflow.com/questions/30349913/yii2-oncondition-added-to-where-part-of-child-query

**Comment by svit-ws** [comment]
the same behavior if onCondition used in AQ ->with() or ->joinWith()

**Comment by dynasource** [comment]
can you post us your code? The easier it will be to grasp and to fix!

**Comment by svit-ws** [comment]
`

        $query = Order::find();

        $query->joinWith([
            'request' => function (ActiveQuery $query) {
                $query->andOnCondition(['>', 'order.cash', 0]);
            },
        ]);
`
proceeds to:

SELECT `order`.* FROM `order` LEFT JOIN `request` ON (`order`.`request_id` = `request`.`id`) AND (`order`.`cash` > 0)

and

SELECT * FROM `request` WHERE (`id` IN (15, 8, 9, ...)) AND (`order`.`cash` > 0)

I think the condition (`order`.`cash` > 0) has no relation to WHERE clause in second query (it proceeds to Unknown column 'order.cash' in 'where clause') 

and in condition (`id` IN (15, 8, 9, ...)) values number must be reduced by onCondition

**Comment by cebe** [comment]
@svit-ws why do you add the onCondition to the JOIN if it limits the result of the main table?

```php
        $query = Order::find();
        $query->joinWith(['request']);
        $query->where(['>', 'order.cash', 0]);
```

**Comment by svit-ws** [comment]
@cebe I want to fetch `request` only for (`order`.`cash` > 0) rows, but `order` must be all.

**Comment by cebe** [comment]
It is really hard to filter the additional condition for the eager loading query. What is the reason you call joinWith()? Is it for eager loading or for the join? If you need eager loading you can just use `with()` instead of `joinWith()`. If you need the join, you can disable eager loading in `joinWith()`.

Thats to the workarounds. Not sure if it is possible to make ActiveQuery detect such situations and act on it automatically. need to check that.

**Comment by svit-ws** [comment]
joinWith() only for make sure that onCondition handled right (at least in first query)
As I mentioned above - with() behaves in the same

I undestand that this is too deeply... 
but onCondition in WHERE clause - it's a bug
reducing related rows number by onCondition - it's enhancement
