### ISSUE TITLE
@property clause not rendered in documentation with apidoc

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii2#8560]
When use apidoc to generate documentation, `@property` items in comment immediately before class statement are not published in html.

This example will return in html documentation only "This is the model class for table "tbl_auth_item"",
without all properties declared.
```
/**
 * This is the model class for table "tbl_auth_item".
 *
 * @property string $name
 * @property integer $type
 * @property string $description
 * @property string $ruleName
 * @property string $data
 *
 */
class PrenotazioniController extends \api\components\BaseController
{
.....
}
```

**Comment by FabrizioCaldarelli** [comment]
Seems that only properties defined in class will be rendered in html.
But virtual properties of models that extend ActiveRecord class will never be explicitally in classes, so to render them in documentation it is necessary to use alternative as bullet list as
```
/**
- property string $name
- property integer $type
*/
```

instead automatic comment generated by Gii.

**Comment by cebe** [comment]
the api generator was originally written for documenting the yii core code which does not have this. We could add processing of additional property tags for documenting application code.

**Comment by FabrizioCaldarelli** [comment]
I think that in applications, mostly for models, this would be a popular feature, because models never have explicited properties. Maybe could be also useful that this behaviour was enabled/disabled by some kind of token.

**Comment by cebe** [comment]
It could even check if the class is an active record and apply special information based on that.
