### ISSUE TITLE
AssetManager::getAssetUrl problem with filemtime

### ISSUE THREAD

**Issue by porshkevich** [yiisoft/yii2#8562]
In code:

```php
if ($this->appendTimestamp && ($timestamp = @filemtime("$basePath/$asset")) > 0) {
```
$basePath can be set to "@webroot/asset", but 'filemtime' need real filename not alias

It may need to replace
```php
@filemtime("$basePath/$asset")
```
to
```php
@filemtime(Yii::getAlias("$basePath/$asset"))
```

**Comment by cebe** [comment]
the code is correct, alias is resolved after configuration: https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L173
