### ISSUE TITLE
First page problem in pagination

### ISSUE THREAD

**Issue by saidbakr** [yiisoft/yii2#8564]
The first Page in a pagination is duplicated and there is no way or option that allow removing number "1" from its URL

The problem simply is `books/index` returns the same output as `books/index/1` In the case of pagination of books titles for example.

I think that it is important to be an option that allows remove the number of the first page from the URL.

**Comment by samdark** [comment]
I think it could be done via url manager rules.

**Comment by kidol** [comment]
Should work with this rule:
```php
['pattern' => 'books/index/<page:\d+>', 'route' => 'controller/action', 'defaults' => ['page' => 1]]
```

**Comment by klimov-paul** [comment]
I think it is better to be handled inside pager widget.
Otherwise, if you do not use 'pretty URLs', you will be unable to solve such SEO problem.

**Comment by klimov-paul** [comment]
There is no issue here: you need to disable `Pagination::forcePageParam` if you don't want page param appear for the first page.
Unit tests cover added: bc6cc9b

**Comment by saidbakr** [comment]
@klimov-paul @samdark Well, using `forcePageParam` with the `pager` options in `ListView` widget is not possible:

```
<?= ListView::widget([
	  'dataProvider' => $dataProvider,
	  'options' => ['class'=>'v1', 'tag'=>'ul'],
	  'itemOptions' => ['tag'=>'li', 'class' => 'a2'],
	  'pager' => ['options'=>['class' => 'fox-page pagination'],'forcePageParam' => false], 
....
```
It will generates Unknown property error:

> Setting unknown property: yii\widgets\LinkPager::forcePageParam

**Comment by klimov-paul** [comment]
`forcePageParam` property belongs to `Pagination` class, not to the `LinkPager` - do not mix this entities.

**Comment by saidbakr** [comment]
@klimov-paul You are right and I've found the solution of @kidol works so perfect with ListView. 

**The conclusion**
`Pagination::forcePageParam`  has no any effect or could not be used if the LinkPager is called by another Widget.
