### ISSUE TITLE
the field checkBox is not reasonable

### ISSUE THREAD

**Issue by djfly** [yiisoft/yii2#8567]
This is a general checkbox
![20150527113304](https://cloud.githubusercontent.com/assets/4409731/7828293/40439286-0464-11e5-80f5-e957c012f950.png)

it's not have label at left

if set enclosedByLabel false checkbox is not have name and Not aligned

![1432698007](http://chuantu.biz/t2/9/1432698007x1822611419.png)

I need the effect like this
![1432698007](http://chuantu.biz/t2/9/1432698215x1822611409.png)

**Comment by djfly** [comment]
and Another issue, radioList hint should appear at the bottom, not on the right
![radioList ](http://chuantu.biz/t2/9/1432699454x1822611409.png)

**Comment by klimov-paul** [comment]
Can you specify a correct markup for this case?

**Comment by djfly** [comment]
look this 
![checkbox](http://chuantu.biz/t2/9/1432977939x1822611350.png)
can you understand that? red background area is checkbox name, label like othe is normal

**Comment by klimov-paul** [comment]
I meant: can you provide HTML code, which produces correct checkbox appearance?

**Comment by djfly** [comment]
i'm set `'layout' => 'horizontal'` you say this code?
```html
<div class="form-group field-signupform-allowsignup has-success">
<label class="control-label col-sm-2" for="signupform-allowsignup">allowsignup</label>
<div class="col-sm-6">
<input type="hidden" name="SignupForm[allowSignup]" value=""><div id="signupform-allowsignup">
     <div class="checkbox">
        <label>
          <input type="checkbox"> Allow signup
        </label>
     </div>
</div>
<div class="help-block help-block-error "></div>
</div>

</div>
```

**Comment by klimov-paul** [comment]
What makes it different from the one generated by `ActiveField`?

**Comment by djfly** [comment]
This is the code currently generated
```html
<div class="form-group field-commentform-needlogin">
<div class="col-sm-6 col-sm-offset-2">
<div class="checkbox">
<label for="commentform-needlogin">
<input type="hidden" name="CommentForm[needLogin]" value="0"><input type="checkbox" id="commentform-needlogin" name="CommentForm[needLogin]" value="1" 0="Users must be registered and logged in to post a comment">
Need Login
</label>
</div>
<div class="help-block help-block-error "></div>
</div>

</div>
```

it's not have label 
![checkbox](http://chuantu.biz/t2/9/1432982007x1822611357.png)

**Comment by djfly** [comment]
@qiangxue 你能给他解释下吗？ 
checkbox 没有label，其他的都有，
