### ISSUE TITLE
RBAC, build a foreign key

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2#8568]
Why in rbac [migrate](https://github.com/yiisoft/yii2/blob/master/framework/rbac/migrations/m140506_102106_rbac_init.php#L75) field 'user_id' is varchar (64)

if you [migrate](https://github.com/yiisoft/yii2-app-advanced/blob/master/console/migrations/m130524_201442_init.php#L17) to yii2-app-advanced field 'id' in table 'user' integer (11)

because of this, between them you can't build a foreign key

**Comment by unclead** [comment]
look at #5435
> you can write your own migration to create the table with an integer id.
