### ISSUE TITLE
Database empty connection too much

### ISSUE THREAD

**Issue by heyanlong** [yiisoft/yii2#8571]
@qiangxue my project is use yii2 version 2.0.4. When the amount of the project request is huge, a special number of empty database connections will be generated, leading to the new request not connected to the database.
@qiangxue 薛强你好。我项目用的是yii2的2.0.4版本。在项目有海量请求的时候，会导致大量的空数据库连接连着数据库，不做任何查询操作，导致新的请求连接不上数据库。因为数据库连接数已经满了。是什么导致了链接不释放呢？

**Comment by samdark** [comment]
It's not handled by Yii so we can't affect it.

1. Make sure you're not using persistent connections.
2. Make sure you have reasonable timeout for DB queries.
3. Profile your app to find out about very slow SQL requests.

**Comment by heyanlong** [comment]
@samdark Thank you very much
