### ISSUE TITLE
Strange issue with TimestampBehavior

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8572]
UpdatedAt works well after any moficiation in row. But, I can't say the same for row creation. 
After new row creation `createdAt` still 0000-...
      
    public function behaviors()
      {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createdAt',
                'updatedAtAttribute' => 'updatedAt',
                'value' => new Expression('NOW()')
            ],
          ];
      }

Here is database table: http://prntscr.com/79xt5n

And here is model: https://gist.github.com/turalsprofile/85eca5d307074b42a215

What am I doing wrong?

**Comment by rupsk1607** [comment]
hi,
check datatype of createdAt

**Comment by turalsprofile** [comment]
Timestamp. Both of datatypes

**Comment by progreg** [comment]
Check `rules` method, may be `createdAt` is not safe attribute.

**Comment by cebe** [comment]
please paste the CREATE TABLE statement. @progreg it must not be safe or validated as it does not receive user input.

**Comment by turalsprofile** [comment]
http://prntscr.com/79xt5n

**Comment by cebe** [comment]
have you overridden beforeSave in your model?

**Comment by turalsprofile** [comment]
nope.

**Comment by turalsprofile** [comment]
so what can be issue?

**Comment by fernandezekiel** [comment]
maybe you can share your whole model code if it's not big

**Comment by turalsprofile** [comment]
Yes of course: https://gist.github.com/turalsprofile/85eca5d307074b42a215

**Comment by turalsprofile** [comment]
any suggestions?

**Comment by rupsk1607** [comment]
can u share ur action code?

**Comment by turalsprofile** [comment]
action is just saving model. nothing more. it doesnt change any of createdAt, updatedAt.

**Comment by rupsk1607** [comment]
kindly check in ur controller that CV model is reference from common folder?

**Comment by turalsprofile** [comment]
yes of course

**Comment by turalsprofile** [comment]
please read carefully. I've already written that, updatedAt works well. problem only with createdAt

**Comment by akaNightmare** [comment]
```php
public function behaviors()
    {
       return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createdAt',
                'updatedAtAttribute' => 'updatedAt',
                'value' => function() {
                    return new Expression('NOW()');
                },
            ],
        ];
    }
```
just wrap it to closure

**Comment by mucha1306** [comment]
I have same issue at 2.0.4.
On 2.0.3 works well

**Comment by turalsprofile** [comment]
@akaNightmare not working still

**Comment by turalsprofile** [comment]
@mucha1306 I don't think we're having same problems

**Comment by duynguyen0511** [comment]
It works for me, I dont think it's a bug. Here is my test code https://gist.github.com/duynguyen0511/af8e859da308cf9699a5

**Comment by turalsprofile** [comment]
@duynguyen0511 please paste the CREATE TABLE statement.

**Comment by turalsprofile** [comment]
@duynguyen0511 Ah I just saw that you already pasted. But in this case what might be issue? I even restarted the mysql server

**Comment by turalsprofile** [comment]
I tried to change createdAt -> created_at and updatedAt -> updated_at. And retried using following code snippet

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className()
            ],
        ];
    }

same result. No success!

**Comment by maximal** [comment]
After Yii update to `2.0.4` `Expression('now()')` got broken it returns '0000-00-00 00:00:00'.

Rewrote all of these to `(new DateTime())->format('c')`.

**Comment by samdark** [comment]
@maximal what's the SQL query generated?

**Comment by maximal** [comment]
Code:
```php
$sql = \Yii::$app->db->createCommand()
	->insert(
		\app\models\Comment::tableName(),
		[
			'id' => 1,
			'userId' => 1,
			'type' => 'repo',
			'text' => 'text',
			'createdAt' => new \yii\db\Expression('now()')
		]
	)
	->sql;
var_dump($sql);

$sql = \Yii::$app->db->createCommand()
	->insert(
		\app\models\Comment::tableName(),
		[
			'id' => 1,
			'userId' => 1,
			'type' => 'repo',
			'text' => 'text',
			'createdAt' => new \yii\db\Expression('now()')
		]
	)
	->rawSql;
var_dump($sql);
die;
```

Output:
```
string(106) "INSERT INTO `comments` (`id`, `userId`, `type`, `text`, `createdAt`) VALUES (:qp0, :qp1, :qp2, :qp3, :qp4)"

string(108) "INSERT INTO `comments` (`id`, `userId`, `type`, `text`, `createdAt`) VALUES ('1', '1', 'repo', 'text', :qp4)"
```

As you can see, `\yii\db\Expression` was not expanded to raw SQL.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/6e48ed05c71128be5610377ec81e2fa0fa14ba9a is the culprit according to git bisect.

**Comment by maximal** [comment]
Yes, looks like this. Big mistake.

**Comment by cebe** [comment]
that commit is in 2.0.5-dev (#8034) @maximal , are you using 2.0.4 or the dev version?

**Comment by maximal** [comment]
On production I’m using “stable“ branch now, so I have `2.0.4`.
Temporarily rewrote timestamps to be `(new DateTime)->format('c')`.
Will wait until `2.0.5` is released.

**Comment by samdark** [comment]
Already fixed in master.

**Comment by maximal** [comment]
Yeah, I noticed. Thank you.

**Comment by c-schmitz** [comment]
This fix does not seems to be in 2.0.6 - why?

**Comment by samdark** [comment]
It's in 2.0.6. https://github.com/yiisoft/yii2/commit/aa5887fec783ec82de193066299d11cbeed5aae4

**Comment by iloveyii** [comment]
May be late but great, Check your table structure and will show CURRENT time etc on update. So the bug is not in code mysql updates the timestamp field itself.

Also in migrations, timestamp() behaves strange without default so always use like:
$this->timestamp()->defaultValue(null),
