### ISSUE TITLE
oci schema map wrongly NUMBER dbType to either type INTEGER or DECIMAL

### ISSUE THREAD

**Issue by bobonov** [yiisoft/yii2#8573]
In /yii2/db/oci/Schema.php
extractColumnType method wrongly map NUMBERS to INTEGER or DECIMAL.

According to Oracle documentation
http://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1832

When scale is 0 the number should be treated as an integer.
But if "If a precision is not specified, the column stores values as given."
As I tested, even is is not clear from the docs, this override the scale.

So if the NUMBER column has scale=0 and precision=0 a double value is stored correctly.

**Comment by cebe** [comment]
thanks for reporting this. can you send a pull request that fixes it?

**Comment by vbelogai** [comment]
I have solution for this:
https://github.com/vbelogai/yii2/blob/oci/framework/db/oci/Schema.php#L398

but my project's tree contains another pending pull request (https://github.com/yiisoft/yii2/pull/8368).

How i can make new pull request without pending changes (only framework/db/oci/Schema.php)?

**Comment by cebe** [comment]
> How i can make new pull request without pending changes (only framework/db/oci/Schema.php)?

you should always work on a different branch to separate the changes.

**Comment by vbelogai** [comment]
OK, #8643 pull request is ready

**Comment by SilverFire** [comment]
Fixed https://github.com/yiisoft/yii2/commit/1f8aafd36ba6b7f8bb33e8f06067b7f1ff2a3989
