### ISSUE TITLE
Auth: allow/deny non-user entities, or multiple domains of user-alikes ?

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#8575]
How can I use authentication behaviors on controllers/actions but not log in any user ?

I have project split to "mastermind" site (users, OAuth2 etc) and separate sites for particular business needs, they may be created by me or by third parties.

The sites need to talk to each other by API in both directions - manage users and groups, collect notifications and usage info.

Calls between the sites need to be protected. But the master site is not a user for satellite site, no user has this kind of role, rights or UI.

How can I protect my URLs by Yii2 auth behaviors, but skip anything related to users ? Or the only way is to put fake users into DB ?

**Comment by klimov-paul** [comment]
@mcd-php, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
