### ISSUE TITLE
Default value in DefaultValueValidator won't make its way through post

### ISSUE THREAD

**Issue by amlopezalonso** [yiisoft/yii2#8577]
Having for instance:

    [['myAttribute'], 'default', 'value' => 0]

Then in controller (say in `actionCreate`) :

    if ($model->load(Yii::$app->request->post())) {

I expected `$model->myAttribute` to be `0` before doing `$model->save()` but it is empty in turn.

So I don't know whether this is a bug or it is really intended that way.

Regards,
Antonio

**Comment by klimov-paul** [comment]
Validators are triggered on `Model::validate()`, which is triggered by `ActiveRecord::save()`. Before `validate()` invocation no default values specified via `DefaultValidator` can be applied.
