### ISSUE TITLE
Sort widget with specified 'orderBy' on query object doesn't work

### ISSUE THREAD

**Issue by xskif** [yiisoft/yii2#8581]
Hi.
I need to specify default sorting order for all product models.
```php
// class Product
function find ()
{
    return (new ActiveQuery(get_called_class()))->orderBy('sort ASC');
}
```

When i put `ActiveDataProvider` in the `GridView` with the query like `Product::find()` the sort widget do not sorting at all. If i trying to sort e.g. by product name the result query looks like this:
```sql
SELECT * FROM `products` ORDER BY `sort`, `name`
```
and products sorted only by the sort column.

I know about `defaultOrder` setting on the sort widget, but it does not suit me since i need to specify default order for all queries and relations (associations) like `catalog->products`, `catalog->fields`, `product->types`, `user->catalogs`, etc.

**Comment by cebe** [comment]
you can reset the default sort in the case where you do not need it `Product::find()->orderBy([])`.

**Comment by xskif** [comment]
ok, so why sort widget don't do that instead of `andOrderBy` ?

**Comment by cebe** [comment]
This way you have full control over the query, maybe the added condition is what you want?

**Comment by xskif** [comment]
ok, i got it, thank you.
I think, this should be documented as `warning` to prevent the same issues.
