### ISSUE TITLE
Pagination bug with `joinWith` query.

### ISSUE THREAD

**Issue by xskif** [yiisoft/yii2#8583]
I have very complicated query like this:
```php
        $query->joinWith([
            'catalog',
            'variations',
            'image',
            'variations.fieldValues.field',
            'variations.groups',
        ])->indexBy('id');
```

Pagination widget shows me strange results, e.g. i have 1 product on the page, but it shows me 1-1 of 3. Or i have 3 product by 2 per page, but it shows me 4 pages with duplicates

i'm alredy change `joinWith` to `with` method instead on production, but it made me lose some features like sorting or searching by joined table.

**Comment by klimov-paul** [comment]
You should add `groupBy('mainTable.id')`.

**Comment by xskif** [comment]
it works, thanks a lot.

**Comment by marty-krishner** [comment]
will this run two queries after group by?

**Comment by yii2backendwebdeveloper** [comment]
> You should add `groupBy('mainTable.id')`.

```$query->distinct()->joinWith()``` for newer version of mysql
