### ISSUE TITLE
Add warning while trying to pass parameters to find() method

### ISSUE THREAD

**Issue by kozmenkoav** [yiisoft/yii2#8591]
It is a common mistake for beginners to pass parameters to find() method, which is hard to debug.
A little bit confusing:
```php
Model::findOne(['status' => 'active']); // Success
Model::findAll(['status' => 'active']); // Success
Model::find(['status' => 'active'])
     ->orderBy('date')
     ->all();                           // BUG !!!
```
So I think showing a warning will be a useful improvement. Thanks.

**Comment by klimov-paul** [comment]
There is no reason to force check for empty parameters of the `find()`.
We are already using PHP Doc comments to indicate whether particular method has any argument or not.
If you are concerned about such issue, please report it to php.net.
