### ISSUE TITLE
Clarifying Documentation for yii\bootstrap\BootstrapAsset

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii2#8597]
Many of us [1] think of yii\bootstrap\BootstrapAsset as bundle that fully support BS3. It turns out to be false. The bundle have only CSS in it and there is not mention of the other yii\bootstrap\BootstrapPluginAsset which actually contains the js.

I used two days to troubleshoot a "bug" in my app only to find this error of mine.
Please clarify this in API documentation so that no more precious hours are lost.

Also as side note, is there any reason why the asset skips including JS from same framework?

Thanks for good work and support
S.

[1] http://stackoverflow.com/questions/12458522/bootstrap-dropdown-not-working

**Comment by arogachev** [comment]
:+1: Should be added to docs.

http://stackoverflow.com/questions/30327781/yii2-bootstrapasset-is-not-loading-bootstrap-js/

**Comment by klimov-paul** [comment]
Resolved by commit https://github.com/yiisoft/yii2-bootstrap/commit/2c4ed78a7caceba585f46f08de739f7b97010b03
