### ISSUE TITLE
Automatic maxlength enhancements

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#8598]
I am suggesting applying `ActiveField`'s automatic `maxlength` (by setting it to `true`) to `passwordInput`. Or probably better yet applying it to `Html::activeInput()` so it works with all similar input types such as `email`, `tel`, `url`, ...etc if created using `ActiveField::input()`.

**Comment by cebe** [comment]
there is no reason to apply a maxlength to a password... for the other fields this could be done.

**Comment by klimov-paul** [comment]
Already resolved, see #8486

**Comment by YasserHassan** [comment]
@klimov-paul thank you for pointing that out.

@cebe my rational is that it is an HTML standard so why have it in one field type and not the other. My main interest is the other input types though.
