### ISSUE TITLE
Production and development main view is not compadebale

### ISSUE THREAD

**Issue by sthorsen** [yiisoft/yii2#8599]
Hi there, Just started to use the advanced version of yii and I found out that the main view is not working if you do this:

In development this does not work:
$menuItems[] = [
                        ['label' => 'Reports', 'url' => ['/site/reports']],
                        ['label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                                'url' => ['/site/logout'],
                                'linkOptions' => ['data-method' => 'post']
                        ],
                ];

But it does work in production

In production I have to do like this:
$menuItems[] = ['label' => 'Reports', 'url' => ['/site/reports']];
                $menuItems[] = ['label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                                'url' => ['/site/logout'],
                                'linkOptions' => ['data-method' => 'post']
                                ];
Does anyone else had something like this?

**Comment by cebe** [comment]
> this does not work:

what does that mean? what do you expect it to do, what do you see instead?

**Comment by sthorsen** [comment]
I get the error: The 'label' option is required.

1. in /var/www/xlt/vendor/yiisoft/yii2-bootstrap/Nav.php at line 159
150151152153154155156157158159160161162163164165166167168     * @return string the rendering result.
     * @throws InvalidConfigException
     */
    public function renderItem($item)
    {
        if (is_string($item)) {
            return $item;
        }
        if (!isset($item['label'])) {
            throw new InvalidConfigException("The 'label' option is required.");
        }
        $encodeLabel = isset($item['encode']) ? $item['encode'] : $this->encodeLabels;
        $label = $encodeLabel ? Html::encode($item['label']) : $item['label'];
        $options = ArrayHelper::getValue($item, 'options', []);
        $items = ArrayHelper::getValue($item, 'items');
        $url = ArrayHelper::getValue($item, 'url', '#');
        $linkOptions = ArrayHelper::getValue($item, 'linkOptions', []);
 
        if (isset($item['active'])) {
2. in /var/www/xlt/vendor/yiisoft/yii2-bootstrap/Nav.php – yii\bootstrap\Nav::renderItem([['label' => 'Reports', 'url' => ['/site/reports']], ['label' => 'Logout (st)', 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post']]]) at line 141
135136137138139140141142143144145146147    {
        $items = [];
        foreach ($this->items as $i => $item) {
            if (isset($item['visible']) && !$item['visible']) {
                continue;
            }
            $items[] = $this->renderItem($item);
        }
 
        return Html::tag('ul', implode("\n", $items), $this->options);
    }
 
    /**
3. in /var/www/xlt/vendor/yiisoft/yii2-bootstrap/Nav.php – yii\bootstrap\Nav::renderItems() at line 128
122123124125126127128129130131132133134    /**
     * Renders the widget.
     */
    public function run()
    {
        BootstrapAsset::register($this->getView());
        return $this->renderItems();
    }
 
    /**
     * Renders widget items.
     */
    public function renderItems()
4. in /var/www/xlt/vendor/yiisoft/yii2/base/Widget.php – yii\bootstrap\Nav::run() at line 97
5. in /var/www/xlt/frontend/views/layouts/main.php – yii\base\Widget::widget(['options' => ['class' => 'navbar-nav navbar-right'], 'items' => [['label' => 'Home', 'url' => ['/site/index']], [['label' => 'Reports', 'url' => ['/site/reports']], ['label' => 'Logout (st)', 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post']]]]]) at line 54
48495051525354555657585960                ]
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
?>
 
<div class="container">
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
6. in /var/www/xlt/vendor/yiisoft/yii2/base/View.php – require('/var/www/xlt/frontend/views/layo...') at line 325
7. in /var/www/xlt/vendor/yiisoft/yii2/base/View.php – yii\base\View::renderPhpFile('/var/www/xlt/frontend/views/layo...', ['content' => '<div class="site-index"> <div ...']) at line 247
8. in /var/www/xlt/vendor/yiisoft/yii2/base/Controller.php – yii\base\View::renderFile('/var/www/xlt/frontend/views/layo...', ['content' => '<div class="site-index"> <div ...'], frontend\controllers\SiteController) at line 386
9. in /var/www/xlt/vendor/yiisoft/yii2/base/Controller.php – yii\base\Controller::renderContent('<div class="site-index"> <div ...') at line 372
10. in /var/www/xlt/frontend/controllers/SiteController.php – yii\base\Controller::render('index') at line 70
64656667686970717273747576            ],
        ];
    }
 
    public function actionIndex()
    {
        return $this->render('index');
    }
 
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
11. frontend\controllers\SiteController::actionIndex()
12. in /var/www/xlt/vendor/yiisoft/yii2/base/InlineAction.php – call_user_func_array([frontend\controllers\SiteController, 'actionIndex'], []) at line 55
13. in /var/www/xlt/vendor/yiisoft/yii2/base/Controller.php – yii\base\InlineAction::runWithParams([]) at line 151
14. in /var/www/xlt/vendor/yiisoft/yii2/base/Module.php – yii\base\Controller::runAction('', []) at line 455
15. in /var/www/xlt/vendor/yiisoft/yii2/web/Application.php – yii\base\Module::runAction('', []) at line 84
16. in /var/www/xlt/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::handleRequest(yii\web\Request) at line 375
17. in /var/www/xlt/frontend/web/index.php – yii\base\Application::run() at line 18
12131415161718    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
 
$application = new yii\web\Application($config);
$application->run();
 $_SERVER = [
    'HTTP_HOST' => '192.168.86.136',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_CACHE_CONTROL' => 'max-age=0',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36',
    'HTTP_REFERER' => 'http://192.168.86.136/xlt/frontend/web/index.php?r=site%2Flogin',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,da;q=0.6',
    'HTTP_COOKIE' => '_csrf=35b82a24d68778cd5430814d56d3859dc269b9e1b9626c3f44bfcff19262de70a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%223S_6x3x2YDX9tvYqxxJTSMe73VH0MH81%22%3B%7D; PHPSESSID=op6uggmnaagjoa37mr5s64m2l6; _identity=a3c2835a0a132029620d9f0936a3266c07434baae284bf18124f05318a4bab0fa%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A46%3A%22%5B1%2C%22fejxb4gamapGjWPZCSXEIbR68HljIkyH%22%2C2592000%5D%22%3B%7D',
    'PATH' => '/usr/local/bin:/usr/bin:/bin',
    'SERVER_SIGNATURE' => '
Apache/2.2.22 (Debian) Server at 192.168.86.136 Port 80

',
    'SERVER_SOFTWARE' => 'Apache/2.2.22 (Debian)',
    'SERVER_NAME' => '192.168.86.136',
    'SERVER_ADDR' => '192.168.86.136',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '192.168.86.1',
    'DOCUMENT_ROOT' => '/var/www',
    'SERVER_ADMIN' => 'webmaster@localhost',
    'SCRIPT_FILENAME' => '/var/www/xlt/frontend/web/index.php',
    'REMOTE_PORT' => '50761',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/xlt/frontend/web/index.php',
    'SCRIPT_NAME' => '/xlt/frontend/web/index.php',
    'PHP_SELF' => '/xlt/frontend/web/index.php',
    'REQUEST_TIME_FLOAT' => 1432846373.6949999,
    'REQUEST_TIME' => 1432846373,
];

$_COOKIE = [
    '_csrf' => '35b82a24d68778cd5430814d56d3859dc269b9e1b9626c3f44bfcff19262de70a:2:{i:0;s:5:"_csrf";i:1;s:32:"3S_6x3x2YDX9tvYqxxJTSMe73VH0MH81";}',
    'PHPSESSID' => 'op6uggmnaagjoa37mr5s64m2l6',
    '_identity' => 'a3c2835a0a132029620d9f0936a3266c07434baae284bf18124f05318a4bab0fa:2:{i:0;s:9:"_identity";i:1;s:46:"[1,"fejxb4gamapGjWPZCSXEIbR68HljIkyH",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
];
Yii Framework
2015-05-28, 20:52:53

Apache/2.2.22 (Debian)
Yii Framework/2.0.4

**Comment by zelenin** [comment]
[['label' => 'Reports', 'url' => ['/site/reports']] - too many brackets
