### ISSUE TITLE
Fix for issue #7757 breaks database Expression

### ISSUE THREAD

**Issue by Blizzke** [yiisoft/yii2#8601]
The fix that was added for issue #7757 via commit 4f49feee8d2b0f0973ae1d0f29d66dccf9f06605
breaks support for database expressions. 

It's actually all about the extra added condition to the last part on line 167:
 `elseif (!is_object($value) && !is_resource($value))`

It should still allow objects of type \yii\db\Expression.

**Comment by Blizzke** [comment]
An example:

    public function beforeSave($insert)
    {
       $this->created = new \yii\db\Expression('NOW()');
       return parent::beforeSave($insert);
    }

Results in "0000-00-00 00:00:00" in the database while before this worked perfectly.

**Comment by klimov-paul** [comment]
Should be already fixed by aa5887f

**Comment by Blizzke** [comment]
:thumbsup:
