### ISSUE TITLE
yii\jui\Spinner clientEvents

### ISSUE THREAD

**Issue by sjaakp** [yiisoft/yii2#8607]
The only client event Yii2 listens to is 'spin'. The other events don't work as expected.

For instance, trying to catch the 'change' event by setting:

            'clientEvents' => [
                'change' => 'function(e, ui) { console.log(this); }'
            ]

Results in the following Js:

           jQuery('#xxx').on('spinnerchange', function(e, ui) { console.log(this); });

While it should be:

           jQuery('#xxx').on('spinchange', function(e, ui) { console.log(this); });

I suppose it has something to do with the protected property $clientEventMap.

**Comment by samdark** [comment]
Fixed https://github.com/yiisoft/yii2-jui/commit/3d4f3d7d0e86af0e0b051a3660517f3041623ffa. Thanks!
