### ISSUE TITLE
indexBy handling of ambiguate columns

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#8609]
IndexBy function can't take a column name in form of 'tableName'.'columnName'.
To make it work I had to select the column and gave this column an alias (The alias can be the same as the column name). 
This works:
```php
return self::find()
->select(['adr', self::tableName().'.id as id'])    // select of column 'id' and aliasing is required! 
 ->indexBy('id')                                          // The value of the selected, aliased column 'id' is taken
->joinwith('adresse')
->orderBy('adr')->column();
```
This returns wrong results for the 'id' column.
```php
return self::find()
->select(['adr'])                                               // What should be possible 
->indexBy( self::tableName().'.id')                   //  index starts wiht 0 - it's not the column value!
->joinwith('adresse')
->orderBy('adr')->column();
```

**Comment by klimov-paul** [comment]
This is not implementable. `indexBy` can manipulate only the query result set, which does NOT contains the table prefix for the columns.
