### ISSUE TITLE
Validation of dirtyAttributes

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2#8610]
I have model with following validator in rules:

```php
['birthdate', 'date', 'format' => 'dd.MM.yyyy', 'timestampAttribute' => 'birthdate', 'timestampAttributeFormat' => 'yyyy-MM-dd'],
```

I use this validator to convert user inputted date to MySQL date format before saving.

Problem arises when I edit one field of this model, e.g. `name` and `ActiveRecord::save()` calls `update` internally which itself calls `validate` if I don't pass `false` to it. `validate` fails as `birthdate` is not in correct format. I know that I have many workarounds here: to call validate explicitly and pass only needed arguments to it and then call `save(false)`, to have scenario...

But why we take into account dirty attributes when updating attributes, but don't take it into account when validating. I think it is more expected behaviour to call validators only for dirtyAttributes. I can't recall any case when calling all validators when one field is changed is adding any value.

**Comment by cebe** [comment]
is the birthdate field editable on the form that changes the name? if not you must use scenario to skip it.

**Comment by armpogart** [comment]
@cebe It's not editable, it's not even in form. In that particular form, I don't have birthdate and I don't care about it. I understand that I can use scenraio or validate explicitly mentioning fields. The point of opening this issue was to understand why non-dirty attributes are validated every time, what's the point of validating them if they haven't changed?

**Comment by cebe** [comment]
1. Validation is to ensure the user can only edit the fields he is allowed to and only with the constraints we define. If a user is not allowed to edit field, you must exclude them in scenario. Otherwise someone could send you a POST request with the data and change it, regardless of the form.

2. if an input is invalid, regardless if it was invalid before or not, it must be validated.

**Comment by armpogart** [comment]
Thanks for your answer, now regarding your points:

1. It doesn't matter if the field is present in form, disabled, or anything else. If someone sends post request, the attribute will become dirty in any case and dirty attributes would be validated if I get everything right.
2. If input is invalid as developer made it invalid, e.g. changed the value in database, it doesn't add any security. The framework isn't supposed to protect data from developer, developer can invalidate data in many ways anyway. I don't see any other method to invalidate data.

@cebe Sorry for taking your precious time, but really, is there any case I can't oversee here?

**Comment by cebe** [comment]
You are missing the whole point of input validation. You should only allow the values from the form to be set by the user and then only validate those. If you do this, there is no need to ask for skipping non-dirty attributes.

**Comment by armpogart** [comment]
Ok, thanks again. The issue arose as we had only one form where user is quick editing his main attributes and birthday was unaffected there. I clearly see that I can create scenario for that one, but it was still logical for me for validator to only validate dirty attributes in any case.
