### ISSUE TITLE
SQL Server batch query data bug

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2#8616]
~~~php
$query = (new Query())->select(['t.*'])
                    ->from('{{news_article}} t')
                    ->where([
                        't.channelid' => self::CHANNEL_ID,
                        't.classid' => array_keys($this->categoryMap)
                    ])
                    ->orderBy([
                        't.id' => SORT_ASC
                    ])
                    ->offset($currentPage * self::PAGE_SIZE)
                    ->limit(self::PAGE_SIZE);
            foreach ($query->batch(100, $sqlServerDb) as $rawData) {
}
~~~
Will has follow error message:

Exception 'PDOException' with message 'SQLSTATE[IMSSP]: There are no more rows i
n the active result set.  Since this result set is not scrollable, no more data
may be retrieved.'

if remove batch() function, use all() return all data. will be ok.

Develop environment is:
win7 + SQL Server 9.00.1399.06	RTM	Enterprise Edition

**Comment by cebe** [comment]
why do you do a batch() call when you already have pagination applied?

**Comment by hiscaler** [comment]
Method of use looks a little problem-_-#
