### ISSUE TITLE
GridView sort arrow in the header is missing

### ISSUE THREAD

**Issue by djfly** [yiisoft/yii2#8617]
![ff](http://chuantu.biz/t2/9/1433130692x1822611409.png)
Should add arrows indicate the sort is desc or asc

**Comment by arogachev** [comment]
Both basic and advanced templates contains CSS styles for that:

https://github.com/yiisoft/yii2-app-basic/blob/master/web/css/site.css
https://github.com/yiisoft/yii2-app-advanced/blob/master/frontend/web/css/site.css

Scroll to `/* add sorting icons to gridview sort links */` comment to see it.

**Comment by djfly** [comment]
thanks,
My personal opinion the ico is not appropriate
