### ISSUE TITLE
Dirty attributes & Model::load(): don't compare with type

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#8619]
I use `Model::load()` and pass the posted data (`Yii::$app->request->post()`). That it is the typical update/create procedure. My ActiveRecord model has one attribute (beside other) that is ought to be an integer. It is stored as an integer in a table. Now, when I load the model and then check the dirty attributes with `BaseActiveRecord::getDirtyAttributes()`, the integer attribute is marked as dirty also when the value has not changed. Indeed, it has changed e.g. from 5 to "5" (integer/string) but IMO it is not a real change. At least it will not have any effect when I save the model into db.

I would think that the comparison in getDirtyAttributes should not check the type as well. What do you think?

```php
// if (isset($names[$name]) && (!array_key_exists($name, $this->_oldAttributes) || $value !== $this->_oldAttributes[$name])) {
   if (isset($names[$name]) && (!array_key_exists($name, $this->_oldAttributes) || $value != $this->_oldAttributes[$name])) {
       $attributes[$name] = $value;
   }
```

When I read the docs I would think it would work that way. I didn't see any recommendation to only use strings for ActiveRecord attributes, nor to override `Model::load()` to deal with the issue.

**Comment by hdogan** [comment]
+1

**Comment by cebe** [comment]
this has been discussed a dozen times (see #2790 and references). In your case you can apply casting of the value as a validation filter to ensure it is an integer.

**Comment by robsch** [comment]
@cebe Okay, sorry for asking again. 

However, it would be helpful if this gets documented at least in the class reference. Other people will stumble over that as well, I guess. It is not obvious why dirtyAttributes behave this way. I still don't get what the problem is.

And could you provide a small example for the suggested validation filter? Did you mean to inherit from yii\validators\Validator?

**Comment by cebe** [comment]
updated the docs, an example for the validation filter can be found here: https://github.com/yiisoft/yii2/commit/0959b5d28ed38dde67e972cd0e0a58fb690ae3a8#diff-e9e5f516d52124c69f3ca4a0374943d3R442

**Comment by robsch** [comment]
@cebe Many thanks for the fast response!! The background of this issue is still not obvious. More important though: now it is clear that it's as intended and not just a bug. And there is also an hint now how one can deal with posted data. Thank you, cebe!
