### ISSUE TITLE
Provide BaseActiveRecord::saveMultiple()

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#8620]
We have `Model::loadMultiptle()` and `Model::validateMultiple()`. So there could be also a function to save multiple objects. Maybe also with a integrated (optional?) transaction as well?

**Comment by robsch** [comment]
Okay. This is already considered in some other tickets. Sorry.

**Comment by arogachev** [comment]
@robsch Maybe it's better reference them here?

**Comment by robsch** [comment]
@arogachev Yes, you're right. I just saw this: https://github.com/yiisoft/yii2/issues/8565#issuecomment-106090149 . I should have search a bit before opening another issue, and I thought this issue will be deleted because of its redundance.
