### ISSUE TITLE
ActiveForm with nested GridView submit issue

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#8621]
I have an `ActiveForm` with some input fields in tabs.
One of the tabs also has a `GridView` with `Pjax` for filtering.

Changing one of the filters in the `GridView` causes the form to be submitted due to the way the `GridView` filtering is done with `Pjax`.

This can be alleviated by the `ActiveForm` checking if it was the target of the `submit` event.

https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L357

``` javascript
...
submitForm: function (e) {
    if (e.target !== this) {
        return;
    }        
...
```

Thoughts from devs?

**Comment by dynasource** [comment]
to specific usecase
