### ISSUE TITLE
Compare Validator do not hide error message when changed compareAttribute

### ISSUE THREAD

**Issue by MetalGuardian** [yiisoft/yii2#8623]
Hello!
When I type in password repeat field, validation of the password field do not triggered. And error message do not hided. 
It visible when I make field focused and blur. Even if I change value from "password" to "password2" and back to "password" it will be visible. Because value of the field do not changed and validation do not triggered.

*Few screenshots:*
**Error shown while no error**
![Error shown while no error](https://raw.githubusercontent.com/MetalGuardian/yii-compare/master/download.png)
**No error while it has to be**
![No error while it has to be](https://raw.githubusercontent.com/MetalGuardian/yii-compare/master/download2.png)

I create testing application with latest yii2 base app.
http://yii-compare.herokuapp.com/web/index.php?r=site%2Flogin
code: https://github.com/MetalGuardian/yii-compare
and add compare validator

**Comment by klimov-paul** [comment]
Duplicates #3987
