### ISSUE TITLE
MessageController adds "@@" to messages, that aren't directly used via Yii::t()

### ISSUE THREAD

**Issue by marius7383** [yiisoft/yii2#8625]
In our Yii2 application we use the awesome i18n mechanisms that really save a lot of work by creating the message files automatically. We also have a lot of message keys that aren't passed directly to the `Yii::t(...)` method and therefore always get `@@` appended and prepended. At one point this starts to become really annyoing, since they have to be removed again. It is a nice feature, but we feel it should be possible to turn it off. 

We enhanced the `MessageController` by an additional parameter named `markUnused` that allows to turn the `@@` off ([Gist](https://gist.github.com/marius7383/bfe59084495f1e429498)). Maybe it is possible to introduce this feature into future Yii2 releases.

**Comment by cebe** [comment]
@marius7383 would you mind sending a pull request?

**Comment by samdark** [comment]
Yep, that's OK to add it.

**Comment by marius7383** [comment]
I just sent the pull request, hope it helps.
