### ISSUE TITLE
question from login system

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/yii2#8634]
in yii1 when i have tow yii1 app in my localhost and in config set id of both same. when login in one, i was loged in in other one.
now in yii2 i have 2 application in my localhost and when i login in one by user with id 1 in othere one i'm login, and i changed the id of both but noting change.
I want to know in yii2 how i shoud confing this problem?

**Comment by klimov-paul** [comment]
@hooman-pro, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
