### ISSUE TITLE
Add support for verbs to create url.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#8635]
Currently when creating URLs via the Url helper or UrlManager, the intended verb is not used.

It should be possible to add an optional parameter to the URL creation routines. This would then be passed on to CUrlRule::createUrl, which will return false if the rule does not apply to the passed VERB.

Suppose you have URL rules that do this:
put to /cars/18  ---> CarsController::actionUpdate(18);
get to /cars/18 ---> CarsController::actionRead(18)

Now for some page I need to make a put request to the read action; this is impossible using the url generator functions.

Url::to(['cars/read', 'id' => 18) will create /cars/18, which will resolve to update if i do a put request.

**Comment by klimov-paul** [comment]
This does not seem logical.
String representation of the URL, which is created by `UrlManager::createUrl()`, can NOT contain verb specification. There is no way passed verb can affect the created URL.
It is also unlikely that, for example, PUT and GET request to the same route with the same parameters will use different URL. If you want to create 'put to /cars/18' or 'get to /cars/18', the same URL will be produced: '/cars/18'.

**Comment by klimov-paul** [comment]
Can you provide the actual example, where verb specified to `createUrl()` can affect the result? Which URL rules configuration can provide this?

**Comment by SamMousa** [comment]
@klimov-paul  You are not understanding me.

The whole problem is that the string representation cannot represent it, that is why it needs to be a parameter passed in to url creation.

The parameter tells the url generator what the intended goal of the url is (for example posting, putting or deleting).

**Comment by SamMousa** [comment]
The exact example is:
       
      [
                'verb' => 'GET',
                'pattern' => '<controller>/<id:\d+>',
                'route' => '<controller>/read',
        ], [
                'verb' => 'PUT',
                'pattern' => '<controller>/<id:\d+>',
                'route' => '<controller>/update'
        ],


Now I need to create a PUT request to /cars/update?id=8. But I cannot use the Url helper since it would create a "pretty" URL using the GET rule:

/cars/8

Which, when I do a PUT request is parsed by the wrong rule. Instead if I tell the Url helper I'm generating a URL that will be used in a PUT request, it can see that the first rule does not apply and it will not create a pretty URL:

/cars/update?id=8

**Comment by klimov-paul** [comment]
> The parameter tells the url generator what the intended goal of the url is (for example posting, putting or deleting).

And what purpose it will serve?

> You are not understanding me.

And in return.
So, once again. Assume we add such parameter, lets call it '_verb'.
Now I can NOT imagine the situation, when:
```php
$urlManager->createUrl('controller/action', 'id' => 1, '_verb' => 'get');
```
and
```php
$urlManager->createUrl('controller/action', 'id' => 1, '_verb' => 'put');
```
can produce different results.

> The exact example is:

So, WHY do you need verb here???
While creating URL you will use:
```php
$urlManager->createUrl('controller/read', 'id' => 1); // matcing GET
```
and 
```php
$urlManager->createUrl('controller/update', 'id' => 1); // matcing PUT
```

**Comment by SamMousa** [comment]
Of course there would be different result if we add a verb parameter (btw I'm not saying it has to be the syntax you propose since that would be breaking BC).


In my rules example, you can see that there woudl be a different result.

        $urlManager->createUrl('cars/read', 'id' => 1, '_verb' => 'get');
       
Would give "/cars/1".

        $urlManager->createUrl('cars/read', 'id' => 1, '_verb' => 'post');

Would give "/cars/read?id=1" since the first rule (previous comment) no longer matches.

**Comment by samdark** [comment]
I don't think it should be solved this way. It's better to add support for URL rule aliases so one could explicitly specify which rule to use.

**Comment by SamMousa** [comment]
Hmm, but should I care (or even "know") about URL rules in the view?

In the view I am merely saying get me a URL to this route, with these parameters.
I don't care how you generate the url.

@samdark I don't think aliases for URL rules are the answer here; it will create a strong cohesion between view code and configuration information.

In essence I should be able to implement other routing mechanisms without affecting the view code. For example I could create a URL manager that encrypts and base64_encodes each url; if i then drop that into any application it should work as long as the application uses the helpers properly.

**Comment by klimov-paul** [comment]
> In my rules example, you can see that there woudl be a different result.

For me such example does not make sense. It is example of the bad practice. Why the same controller/action responds to the different request types?
This produces inconsistent code inside the controller, where you should write an `if` statement to determine what should be done: read or write operation.

**Comment by samdark** [comment]
Overall I agree with @klimov-paul. In general, same endpoint should use same URL no matter what verb is.

**Comment by klimov-paul** [comment]
To be more precise: I can not see any practical use case for such feature.
Separation for different request methods usually implemented to support REST architecture, which enforces using different request methods for the same URL. This means each combination of the URL and request method should be responded by different route, but not vice versa.

Although there is acombination of URL rules, which may require this feature, its usage produces inconsistent code. So I don't think such functionality should belong to the core.

I am closing this issue unless more coherit use case provided.

**Comment by SamMousa** [comment]
@klimov-paul I know this is your default way of responding to things, but a bit more patience and open-mindedness would be greatly appreciated!

Endpoints are mapped to URL during URL creation.
URLS are mapped to endpoints during URL parsing.

It seems natural to me that these functions are eachothers inverse.

Specifically, if I generate a URL to a specific endpoint, it should _always_ be parsed to that specific endpoint.
Currently it is not:
        
        $url = Url::to(['projects/read', 'id' => 8]); // $url = '/projects/8';

       // Parse a PUT request:
       parseUrl("/projects/8") ==> ProjectsController::actionUpdate(8);
       // Parse a GET request:
       parseUrl("/projects/8") ==> ProjectsController::actionRead(8);

If we had the extra argument:

        $url = Url::to(['projects/read', 'id' => 8], null, 'PUT'); // $url = '/projects/read?id=8'; Since the GET rule no longer applies.

       // Parse a PUT request:
       parseUrl("'/projects/read?id=8") ==> ProjectsController::actionRead(8);
       // Parse a GET request:
       parseUrl("'/projects/read?id=8") ==> ProjectsController::actionRead(8);


Alternatively the argument could at least specify not to do any pretty url generation, which would at least allow this scenario without forcing me to:
1. Replicate Url helper functionality.
2. Hardcode URLs in my views.

**Comment by samdark** [comment]
Please explain why you need GET and POST to the same endpoint to have separate URLs.

**Comment by klimov-paul** [comment]
> It seems natural to me that these functions are eachothers inverse.

It whould be so, if there be a way to specify request method inside the URL, but such ability does not exist.

> If we had the extra argument:

If you have an extra argument, you have an extra `if` inside your controller;
```php
class ProjectsController extends Controller
{
    public function actionRead()
    {
        if (Yii::$app->request->method === 'PUT') {
            // do saving here
        }  else {
            // do read
        }
    }
}
```
And such action breaks 'single responsibility' pronciple.

While according to the OOP recomendations you should separate 'read' and 'write' actions.
So your controller looks like:
```php
class ProjectsController extends Controller
{
    public function actionRead()
    {
        // responds to the 'GET'
        // do read
    }

    public function actionWrite()
    {
        // responds to the 'PUT'
        // do saving here
    }
}
```

Folloing simple OOP principle, you will never get yourselt inside the situation you may require specificartion of the verb for URL creation, as it is already specified via route!

**Comment by SamMousa** [comment]
I am doing PUT to update an entity: PUT /projects/8  will update project 8.
Sometimes I don't want to not update the entity, but rather it's view (for example pagination or something else). 

So I need to create a request that does PUT /projects/read?id=8.
Which is impossible since a the url generator will always use the rule for the GET verb and create a URL like (/projects/8) that will be routed when PUTting to projects/update..


Note: In general should I not be able to create a URL that will be routed to a specific controller action without knowing about rules? I am in the view I don't care and don't know about URL rules.
So if we add an intended VERB this issue is 100% solved for those who need it and it does not bother anyone else..

**Comment by samdark** [comment]
@yiisoft/core-developers more opinions?

**Comment by qiangxue** [comment]
@SamMousa Why don't you add an additional PUT rule with the pattern `/projects/read/<id>` for the read action? Note that even if we add the verb parameter to the URL creation method, it will still fail to work if we turn on strict parsing.

**Comment by SamMousa** [comment]
@qiangxue, because that is the issue!

If I add another rule it will not be used since the pattern for the get verb is the same. 

So I can have multiple rules with 1 pattern for parsing, but not URL creation!

**Comment by klimov-paul** [comment]
> Alternatively the argument could at least specify not to do any pretty url generation...

> So I can have multiple rules with 1 pattern for parsing, but not URL creation!

There is `yii\web\Rule::mode`, which can be set to 'parsing only' or 'creation only', which allows you to skip unnecessary rules while parsing or creating URL.

You may achieve your goal creating a custom URL rule, which will accept verb as params and vary accordingly. I still think this feature does not belong to the core.

**Comment by SamMousa** [comment]
There are plenty ways to work around Yii, I'd rather just work with Yii.

There is simply no reason for this assymmetry between url parsing and url creation.

**Comment by qiangxue** [comment]
@SamMousa I understand your need now. I think your request makes sense. We probably can consider supporting the syntax:

```php
Url::to(['PUT cars/read', 'id' => 18])
```

**Comment by SamMousa** [comment]
@qiangxue  Thanks for your patience. As to the syntax, I don't have a specific preference.
I've been reading up a bit on versioning and can see that adding an optional argument to these functions could break applications that extend things like UrlRule.
On the other hand, if an UrlRule implementation depends on the route parameter that could cause problems as well ^^.

Anyway, that part is more your job, I've done mine by explaining the problem. If I think of a good syntax, I'll let you know!

**Comment by qiangxue** [comment]
> On the other hand, if an UrlRule implementation depends on the route parameter that could cause problems as well ^^.

What kind of problems do you have in mind?

**Comment by SamMousa** [comment]
@qiangxue if I subclass UrlRule::createUrl and you change the signature I get strict errors. 
See: http://paul-m-jones.com/archives/6136

While you replied I was typing this: 

After digging into the source some more, I think the best solution would be to:

1. Add optional argument to UrlRule::createUrl($manager, $route, $params, $verb = null)
This forces anyone who subclasses UrlRule to update their signature.

2. Add optional argument to UrlManager::createUrl($params, $verb = null)
This forces anyone who subclasses UrlManager to update their signature.

3. Add optional argument BaseUrl::toRoute($route, $scheme, $verb)
This forces anyone who subclasses BaseUrl to update their signature.

--------------------------------------------------------------------------------------------------------------
Alternatively a temporary fix could be implemented that reduces the BC break:
1. Create a subclass "NewUrlRule" of UrlRule that has the new parameter.
2. Set the default class for url rules to "NewUrlRule".

Repeat for UrlManager, implement createUrl to do an "instanceof" check and pass arguments appropriately. Also set default url manager class to "NewUrlManager"

Then update the Url helper, which will be the only location for BC breaks.

**Comment by qiangxue** [comment]
I didn't suggest changing the signature. I was suggesting `['PUT cars/read', 'id' => 18]`

**Comment by SamMousa** [comment]
Oh yes, of course; too quick :p
Well if I implement custom logic that in UrlManager / UrlRule that depends on the route format, which is documented here: https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L272

It could break my application if people put stuff with spaces in there ^^. 
(Playing devils' advocate here, I'd rather have this sooner than later but I know BC is important for Yii)

**Comment by qiangxue** [comment]
Well, the only bad result is that your custom UrlManager/UrlRule won't work with `PUT cars/read`. But this is already the case currently (i.e., the custom class has problem dealing with this issue you reported.)

**Comment by SamMousa** [comment]
One thing that would definitely not break BC is to add it in the same way as anchors, via a 'special' key in $params.

If you pick a name that is unlikely to be used by people normally, like _verb or _method.

@qiangxue  Fair enough, and obviously those people not using this will not have spaces in their routes so if they want the new functionality it is not that strange that they would have to make small changes to their code.

**Comment by SamMousa** [comment]
Can we get a conclusion on the desired direction?

We can use @qiangxue suggestion and add support for prefix the route with a verb.

(If the desired direction is to not support this, feel free to close this)

**Comment by cebe** [comment]
sounds like a good thing in general, will check it in more detail after 2.0.7 is out.

**Comment by SamMousa** [comment]
@cebe, great; if you decide on what kind of implementation you'd like I'm still up for implementing this.

Short list of options discussed above:

1. Put method before URL: `createUrl(['PUT test/create'])`

2. Use specific parameter: `createUrl(['test/create', '_verb' => 'PUT']); (we could use a single character key here forbidden list, this will make random collisions very unlikely: https://tools.ietf.org/html/rfc3986#page-13

3. Change all method signatures to have an extra parameter specifying the verb.

**Comment by SamMousa** [comment]
Okay, spent some more time on this. Currently I have a (partial) implementation:
Rules, strict parsing is enabled:
````
[
        'verb' => 'GET',
        'pattern' => '<controller:\w+>/<id:\d+>',
        'route' => '<controller>/read'
    ],
    [
        'verb' => 'PUT',
        'pattern' => '<controller>/<id:\d+>',
        'route' => '<controller>/update',
    ],
    [
        'verb' => 'POST',
        'pattern' => '<controller>',
        'route' => '<controller>/create',
    ],

    [
        'verb' => 'DELETE',
        'pattern' => '<controller>/<id:\d+>',
        'route' => '<controller>/delete'
    ],

````

This is the output, columns are (test case, route, params and result)
````
1  model/read          [id => 2]            --> /model/2
2  model/read          [id => 2][b => test] --> /model/2?b=test
3  model/update        [id => 2]            --> /model/2
4  POST model/read     [id => 2]            --> /model/read?id=2
5  PUT model/update    [id => 2]            --> /model/2
6  GET model/read      [id => 3]            --> /model/3
7  DELETE model/read   [id => 3]            --> /model/read?id=3
8  DELETE model/delete [id => 3]            --> /model/3
9  DELETE model        [id => 3]            --> /dev/model?id=3
10 DELETE /model       [id => 3]            --> /model?id=3
11 model/create        [test => 2]          --> /model?test=2
12 GET model/create    [test => 2]          --> /model/create?test=2
13 POST model/create   [test => 5]          --> /model?test=5
14 model/update        [test => 2]          --> /model/update?test=2
````

The only issue is the default configuration where there is no `verb` as part of the route. 
This implementation does not "assume" anything, so in the case of `11` it will use the `POST` rule even though this might not be expected behavior.

Feed back please!

**Comment by SilverFire** [comment]
> This implementation does not "assume" anything, so in the case of 11 it will use the POST rule even though this might not be expected behavior.

This behavior does not look valid to me. I suggest the following request routing logic order:

1. Find the rule that matches the request with appropriate `verb`. If not found - see step 2.
2. Find rules that match the request. Ensure, that all of them do not have declared `verb`.
 * `true` - use the first rule
 * `false` - throw an exception, that there are no rules for this `verb`

**Comment by SamMousa** [comment]
Silverfire, your proposal would break BC in a big way though; currently verb in the rule config is irrelevant; I used it only when a method is given to create URL. Your suggestion would require it to be present, right?

**Comment by SilverFire** [comment]
I don't want to make `verb` required, my example logic is malformed.

Try №2:

1. Find the rule that matches the request with appropriate `verb`. If not found - go to step 2.
2. Find the rule that matches the request but does not have `verb`. If not found - throw an exception, that there are no rules for this `verb`

See the example:

```php
$rules = [
    [
        'verb' => 'POST',
        'pattern' => '<controller>',
        'route' => '<controller>/create',
    ],
    [
        'pattern' => '<controller>',
        'route' => '<controller>/index',
    ],
];
```

In this case you have a rule for POST request and a default one for any other request type.
BUT if I remove the second rule - there will be no way to resolve `GET controller` request. Is it clear enough?

**Comment by SamMousa** [comment]
Yes, that's clear. But in my example 11, there is no `GET`. It is fine to throw exceptions for code like this:
`````
->createUrl('GET controller')
````
But how do you handle the case `->createUrl('controller')` (without explicit intended verb).

The problem is not there when an intended verb is present; since that is new behavior we are free to choose a default (and I like your suggestion of throwing an exception). 
The problem is what do we do if we do not have an intended verb; do we assume the intended verb is `GET` or do we try `GET` and fallback to anything else as you suggest.

The current yii behavior currently is to not look at the verb in the route config when creating a url; so if we want least surprise one could argue that we don't change the case where no intended verb is given.

PS. I introduced the term `intended verb`: The verb given as part of the route in a call to `createUrl`; using this to clearly separate it from the verb in route config.

**Comment by SilverFire** [comment]
Ah, okay, now I see the problem. Need some time to think about it

**Comment by SamMousa** [comment]
Bump ^^

**Comment by SamMousa** [comment]
@SilverFire did you get a chance to think about this?

**Comment by samdark** [comment]
Won't be actual for 3.0.
