### ISSUE TITLE
Add an 'empty'  condition to yii\db\Query::where()

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#8636]
A small enhancement:

The `where()` method already provides a lot of conditions. However, I just came across the need to check in a query if a field is null or an empty string. Like empty() in PHP. Could this be done by Yii? 

AFAIK one needs to create two annoying conditions to check for this. It would be nice if Yii could do this.

As an option you could also consider to trim the value first if this is possible.

Small MySQL example: http://stackoverflow.com/a/14575847/57091

**Comment by mdmunir** [comment]
NO

**Comment by nineinchnick** [comment]
Check out [Query::filterWhere()](http://www.yiiframework.com/doc-2.0/yii-db-queryinterface.html#filterWhere%28%29-detail).

**Comment by Alex-Code** [comment]
I would create an `IS_EMPTY` function in `MySQL`.
```php
->where('IS_EMPTY(col)')
```

**Comment by robsch** [comment]
@Alex-Code `ISEMPTY()` is only for geometry data, as far as I can tell.

@nineinchnick This is the other way around. But I'd like to check for the data in the table that might be NULL. Not the variable that I pass to `filterWhere()`.

@mdmunir NO?

**Comment by mdmunir** [comment]
>Like empty() in PHP. Could this be done by Yii?

I said "NO". Mean, do it by your self.

**Comment by robsch** [comment]
@mdmunir Okay. I meant: Could this be done by Yii in a future version?

**Comment by cebe** [comment]
`->where("col1 IS NOT NULL AND TRIM(col1) <> ''")` should work just fine.

**Comment by robsch** [comment]
Of course. I just thought it would be conveniont.

**Comment by igorveremsky** [comment]
if someone need to get records from db with some empty field you can use:
```php
$query->andWhere([
	'or',
	['is', 'col_name', null],
	['=', 'col_name', '']
]);
```
