### ISSUE TITLE
Wrong logic for BaseActiveRecord::findByCondition

### ISSUE THREAD

**Issue by lscgzwd** [yiisoft/yii2#8640]
```php
$query = static::find();

        if (!ArrayHelper::isAssociative($condition)) {
            // query by primary key
            $primaryKey = static::primaryKey();
            if (isset($primaryKey[0])) {
                $condition = [$primaryKey[0] => $condition];
            } else {
                throw new InvalidConfigException('"' . get_called_class() . '" must have a primary key.');
            }
        }

        return $query->andWhere($condition);
```

As we can see, if we give a string condition to this function, it default eq to primaryKey, I think the logic is wrong, if we want to use condition array like where($condition, $params), there have a bug, because the !ArrayHelper::isAssociative($condition), this may cause us cannot use array conditon, Look my example:

BCustomer::findOne(['not',[ 'status'=>'-1']]);

['not',[ 'status'=>'-1']] will return false ArrayHelper::isAssociative   , I think this is wrong.

if the we need default find by primary key , I suggest to and findByPk function, not to deal with findByCondition

**Comment by klimov-paul** [comment]
Acording to `findOne()` method specification at `ActiveRecordInterface`:
https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecordInterface.php#L156
you can not specify conditions like `['not',[ 'status'=>'-1']]` as its argumenent.
