### ISSUE TITLE
Fixture load 2.0.4 postgis pgsql error

### ISSUE THREAD

**Issue by rptts** [yiisoft/yii2#8644]
Since 2.0.4 (prior to that, was working fine) I'm having this error when i try to fixture/load.

My database is PostgreSQL and extends PostGIS.

What is happening is that the Global fixture InitDb is trying to execute the following SQL:
```SQL
    ... ALTER TABLE "public"."geography_columns" DISABLE TRIGGER ALL; ...
```

and I get the error:

    Exception 'yii\db\Exception' with message 'SQLSTATE[42809]: Wrong object type: 7 ERROR:  "geography_columns" is not a table

Now... the thing is that "geography_columns" isn't a table, its a **view**, and yet its included in the SQL statement.

![views](https://cloud.githubusercontent.com/assets/1150267/7964357/3c91ec86-0a0f-11e5-9770-934c0f9b1480.PNG)
(all of the views are in the sql)

Here's the stack trace:

    Stack trace:
    #0 /vagrant/src/yii2-app/vendor/yiisoft/yii2/db/Command.php(779): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE "pu...')
    #1 /vagrant/src/yii2-app/vendor/yiisoft/yii2/test/InitDbFixture.php(94): yii\db\Command->execute()
    #2 /vagrant/src/yii2-app/vendor/yiisoft/yii2/test/InitDbFixture.php(76): yii\test\InitDbFixture->checkIntegrity(false)
    #3 /vagrant/src/yii2-app/vendor/yiisoft/yii2/test/FixtureTrait.php(114): yii\test\InitDbFixture->beforeUnload()
    #4 /vagrant/src/yii2-app/vendor/yiisoft/yii2/console/controllers/FixtureController.php(147): yii\console\controllers\FixtureController->unloadFixtures(Array)
    #5 [internal function]: yii\console\controllers\FixtureController->actionLoad('*')
    #6 /vagrant/src/yii2-app/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
    #7 /vagrant/src/yii2-app/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
    #8 /vagrant/src/yii2-app/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('load', Array)
    #9 /vagrant/src/yii2-app/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('load', Array)
    #10 /vagrant/src/yii2-app/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('fixture/load', Array)
    #11 /vagrant/src/yii2-app/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('fixture/load', Array)
    #12 /vagrant/src/yii2-app/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
    #13 /vagrant/src/yii2-app/yii(23): yii\base\Application->run()
    #14 {main}

**Comment by cebe** [comment]
this is a side effect of #7833, the tables now include views which seems to be unexpected in this case.
/cc @nineinchnick

**Comment by nineinchnick** [comment]
@cebe I'm looking at the `Schema` sources and can't figure out the best solution to this. We can't add arguments to `getTableNames()` and can't modify its return type. `TableSchema` could contain an extra property with its type but I'd prefer to avoid an extra query in `getTableSchema()`. Those are expensive for example in Oracle.

I guess we could add another method like `getViewNames()` to filter them out in `checkIntegrity()` but it would be confusing for `getTableNames()` to also include views.

**Comment by cebe** [comment]
we can have it this way in 2.0.x and clean it up in 2.1.

**Comment by ricpelo** [comment]
Any easy way to workaround this issue? Thanks.

**Comment by cebe** [comment]
@ricpelo this would be the way:

> I guess we could add another method like getViewNames() to filter them out in checkIntegrity() but it would be confusing for getTableNames() to also include views.

**Comment by akaSStalkALEX** [comment]
Could somebody share quick fix for this problem, please?

**Comment by nailfor** [comment]
I have the same error, a temporary solution, since I do not use views,  I remove 'v' of findTableName() method(file pgsql/Schema.php) like that:
        $sql = <<<SQL
SELECT c.relname AS table_name
FROM pg_class c
INNER JOIN pg_namespace ns ON ns.oid = c.relnamespace
WHERE ns.nspname = :schemaName AND c.relkind IN ('r','m','f')
ORDER BY c.relname
SQL;

**Comment by ricpelo** [comment]
I wonder if it could be easier to fix the issue in the fixture/load module instead of Schema.php.
