### ISSUE TITLE
Detaching behaviors inside behavior.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#8645]
Currently when attaching a behavior, the following workflow is used:
1. Instantiate behavior (if needed)
2. Call attach on the behavior so it can do whatever it does when being attached (like updating $this->owner).
3. Add behavior to the _behaviors array.

If I want to prevent my behavior from being attached to a specific owner, how do I go about this?

I cannot call $this->owner->detachBehavior because at the time of attaching the owner does not have the behavior in its _behaviors list. (Also I don't know my name so would have to array_search.)

Each behavior attached to an object increases the application load, if a behavior has decided it does not apply and will not apply to a specific owner, how can it clean itself up? 
Alternatively one could obviously make sure that only "eligible" owners attach to a behavior, but I see no reason for having this available in the behavior as well.

An option would be to check the return value of attach, allowing it to return false in case it does not want to be added.

My use case, let me know if there are other solutions:
I have a behavior for ActiveRecord models.
1. I don't want it to be attached, by accident or on purpose, to anything not decending from ActiveRecord.
2. My behavior only applies to models that use tables with a specific field, for example created. (Think TimeStampBehavior).

Currently we have 100% control from the initiator, and no control from within the Behavior.

Possibly / probably related to #7411, #1053

**Comment by Blizzke** [comment]
:+1:

**Comment by mootensai** [comment]
Is this will help?
```php
if(!($this->owner instanceof ActiveRecord)){
    throw NotSupportedException("This behavior only works on ActiveRecord");
}
$db = $this->owner->db;
$tableSchema = $db->getTableSchema($this->owner->tableName());
// 1st method
if(!in_array('created', $tableSchema->columnNames)){
    throw NotSupportedException("This behavior only works on if there's a column called 'created'");
}
// 2nd method
if($tableSchema->columns[$this->createdAttr]['dbType'] != 'datetime'){
    throw NotSupportedException("This behavior only works on if the created attribute column type is DATETIME");
}
``

**Comment by klimov-paul** [comment]
> I don't want it to be attached, by accident or on purpose, to anything not decending from ActiveRecord.

Technically, asking behavior should restrict which class it should be attached to is like asking trait to do the same way. Behaviors were introduced as a replacement for multiple inheritance, when 'trait' feature has not been introduced yet. Just as trait can not place any restriction on the class using it, behavior does not have such mechanism.

Still if you really need this so badly you can always override `attach()` method inside your behavior to be like following:
```php
public function attach($owner)
{
    if (!($this->owner instanceof ActiveRecord)) {
        throw NotSupportedException("This behavior can be attached only to ActiveRecord");
    }
    parent::attach($owner);
}
```
