### ISSUE TITLE
final report about applied migrations

### ISSUE THREAD

**Issue by dizews** [yiisoft/yii2#8649]
Hello.

I think it will be a good if we add how many migrations was applied in a last time

**Comment by mdmunir** [comment]
```
yii migrate/history
```

**Comment by dizews** [comment]
@mdmunir I talk about migrations applied in a last time. It will be useful for release engineer to rollback last release

**Comment by samdark** [comment]
You mean getting it with a separate command or the output of the command just applied them?

**Comment by dizews** [comment]
@samdark I mean the output of the command.
for example: ```2 from 5 migrations was applied```

**Comment by samdark** [comment]
What do you mean by `from 5`?

**Comment by dizews** [comment]
In the begin the script show us how many migrations will be applied. At the end, I expect to see how many migrations was applied from the first one.

**Comment by samdark** [comment]
OK.
