### ISSUE TITLE
asRelativeTime 'just now' message missing in french translation

### ISSUE THREAD

**Issue by anighazaryan** [yiisoft/yii2#8651]
Hello, 

I noticed that in formatter->asRelativeTime method 'just now' message translation is missing for locale 'fr'.

**Comment by klimov-paul** [comment]
If you can compose such message, open a pull request for its addition, following <a href="https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md">Workflow for Yii contributors</a>

**Comment by Blizzke** [comment]
What would it translate at? I'll add it.
