### ISSUE TITLE
BaseActiveRecord::getter

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#8655]
[Here](https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L246) may be better check as:

``` php
if ($relation = $this->getRelation($name, false)) {
    return $this->_related[$name] = $relation->findFor($name, $this);
} else {
    return parent::__get($name);
}
```
1. Method `getRelation` check at once case sensitive of `name`
2. Not any `ActiveQuery` it relation

**Comment by cebe** [comment]
what exactly is the problem with current implementation?

**Comment by lynicidn** [comment]
it not problem, better way for override relation generate - all logic in one place (implemented method)
as [here](https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L297)

crazy active record code describing situation =)
```php
public function getSearchQuery()
{
    return static::find()->where(['status' => $this->status])
}
```
now if i get `searchQuery` property from model current code try populate relation

**Comment by lynicidn** [comment]
only now `getRelation` not check `primaryModel`, `link` and `multiple` properties in `ActiveQuery` but override it easy in one place
