### ISSUE TITLE
Callback for CheckboxColumn

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#8657]
It would be nice to have a callback for when a checkbox is clicked by the user.

**Comment by rubenjleon** [comment]
+1


-- 




* <http://vanceandhines.com> <http://vanceandhines.com> 
<http://fuelpakfi.com> <http://facebook.com/vanceandhines> 
<http://twitter.com/vanceandhines> <http://youtube.com/vanceandhines> 
<http://instagram.com/vanceandhines> 
<http://www.linkedin.com/company/vance-and-hines>Disclaimer: The 
information contained in this transmission, including any attachments, may 
contain confidential information of Vance & Hines. This transmission is 
intended only for the use of the addressee(s) listed above. Unauthorized 
review, dissemination or other use of the information contained in this 
transmission is strictly prohibited. If you have received this transmission 
in error or have reason to believe you are not authorized to receive it, 
please notify the sender by return email and promptly delete the 
transmission.*

**Comment by fbau123** [comment]
Maybe you can use this http://www.yiiframework.com/doc-2.0/yii-grid-checkboxcolumn.html#$checkboxOptions-detail

**Comment by alexandernst** [comment]
@fbau123 you mean by adding some hacky `onclick()` solution? Yeah, I though about that, but it would be nice if we could get an actual Yii-based way of doing this.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
