### ISSUE TITLE
Make it possible to set/get flash messages from client side

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#8662]
It would be useful to be able to set/get flash messages from the client side.

**Comment by klimov-paul** [comment]
You can use regular AJAX requests for that.

**Comment by alexandernst** [comment]
Yes, I know. I actually implemented an Angular service to do so, but it would be nice to have that functionality in the `yii` namespace (JS). @klimov-paul

**Comment by cebe** [comment]
this means there must be an action defined by the framework that delivers the messages. Not sure if this feature is generic enough to add it...
