### ISSUE TITLE
Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT'

### ISSUE THREAD

**Issue by leyestd** [yiisoft/yii2#8664]
in C:\LeyeShop\vendor\yiisoft\yii2-authclient\BaseOAuth.php
CURLOPT_USERAGENT => Yii::$app->name . ' OAuth ' . $this->version . ' Client',

WHY?

**Comment by yiiworld** [comment]
You need to install php curl module.
- example how to install for debian: apt-get install php7.2-curl
- for windows You need find(download) lib file add php-curl.dll and add it to php extension directory, and then edit php.ini to activete it module: extension=php_curl.dll
