### ISSUE TITLE
Yii2 Gridview with SearchModel 'locks' 

### ISSUE THREAD

**Issue by Paramone** [yiisoft/yii2#8667]
What exactly do I mean?

When I get the search-fields in the gridview, It automatically sets the date, and some other data (for example : product.is_saved)

I'm not really clear why this is, could I get some help with this?

**Comment by klimov-paul** [comment]
@Paramone, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
