### ISSUE TITLE
Allow DbSession store particular data in the separated column.

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2#8670]
For the custom session storages like DB, MongoDB or Redis, It would be nice to have built-in support for storing particular session data in separated fields. For example, allow to store `userId` in the separated column of 'session' table with `DbSession`.

Typical use case: I want to see all active sessions for the particular user and perhaps drop some of them (or all of them) if needed. Such functionality provided by GMail for example.
In morden systems with high security demands restriction: 1 active session per 1 registered user is very common.
Of course this can not be implemented at plain `yii\web\Session` or `yii\web\CacheSession`, but can be present in `DbSession`, `MongoSession` and so on.

We can introduce array map in format: sessionKey => storageColumnName, which can be used for actual data set composition.
Common related functionality can be composed into a trait or a abstract base class.

**Comment by samdark** [comment]
+1. Seen it implemented by overriding session class many many times.

**Comment by klimov-paul** [comment]
I suppose the best way will be introduction of 2 PHP callbacks: one before saving data and another one after read data. This will allow to store even values, which are not present in the session data like request IP address, inside session table.

**Comment by usualdesigner** [comment]
An idea with the callbacks is enough for use in most cases IMO
