### ISSUE TITLE
Inconsistent `QueryInterface::one()` return types in case when record not found

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#8677]
Inside `QueryInterface::one()` its clean from phpDoc that when record not found `false` should be returned. But in case of `Query::one()` will return `false`. In case of `ActiveQuery::one()` if record not found it will return `null`. Is there any sensible reason for such inconsistency?

**Comment by cebe** [comment]
PDO return value is `false` for empty result, and array in case there is a result.
The ActiveQuery will return an Object in case of success, so the representation for no object is usually `null`.

**Comment by creocoder** [comment]
@cebe Its OK with returning `null`. I think this method in both cases should return `null`. But its not BC. Probably we need fix that in 2.1.

**Comment by cebe** [comment]
not sure about this, we would need to always check results for `false` and return null instead in many places.
What exactly is the problem you see with it? you would not interchange an ActiveQuery with a DAO query in any place because the non empty result is also very different.

**Comment by creocoder** [comment]
@cebe 

> What exactly is the problem you see with it?

When you work with DAO you should check for `false` if empty result come. When you work with AR you should check for `null` if empty result come. Its very annoying. More important that returning `false` in case of DAO does not have any benefits.

> you would not interchange an ActiveQuery with a DAO query in any place because the non empty result is also very different.

This is not quite true is you use AR with asArray() method.

**Comment by samdark** [comment]
@creocoder how about simply doing the following in both cases?

```php
$post = Post::find()->one();
if (!$post) {
    // ...
}

$post = (new \yii\db\Query())->from('post')->one();
if (!$post) {
    // ...
}
```

**Comment by creocoder** [comment]
@samdark Using non-boolean expressions inside conditions always considered bad practice. For example inside core i do not meet anything different from `if ([boolean])`.

**Comment by creocoder** [comment]
@samdark Also its just workaround for inconsistency trouble. I can leave with `if ($post === false)` and `if ($post === null)`. Idea is to make returm types consistent inside 2.1

**Comment by samdark** [comment]
OK. For 2.1 idea it's fine.

**Comment by ominds** [comment]
I propose we just fix the documentation there to say that the return value depends on the implementor. Or to make the return value array|boolean|null so that anyone reading it will know what to expect. My main problem is with the documentation rather than consistency.

The reason I think it's a bad idea to change the behavior now is that anyone not aware of this change on an upgrade could face big trouble since it will break his code.

**Comment by samdark** [comment]
It's scheduled for 2.1, not for 2.0

**Comment by cebe** [comment]
Closing in favor of https://github.com/yiisoft/yii2/issues/15151
