### ISSUE TITLE
Model::validateMultiple() quantity of valid models

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2#8678]
Model::validateMultiple() does not allow one to know how many models are valid. So it would be necessary to loop again the set of models to count how many are valid.

In some cases we need validate all models in a set but we dont need ALL OF THEM be valid, but only $min number. 

Example: A ParentModel with multiple ChildModels. When the ParentModel will be saved it should have at least 2 ChildModels valid to be saved altogether.

So that It would great if the method would work as follows: 
```php
// will return true if 2 or more models are valid
Model::validateMultiple($myChildModels, $attrNames, 2); 

// ---- OR ---

// will return how many models are valid
Model::validateMultiple($myChildModels, $attrNames);
```

**Comment by cebe** [comment]
what do you do with the invalid models? just drop them? does not sound like a regular usecase...

**Comment by slinstj** [comment]
Yeah, they are ignored. 

I am checking a specific attribute (name) of multiple models (Options) related to a parent model (Variation). When creating or updating a Variation, the Options values can be defined at the same time. If the name fields are empty, that options should not be saved (they are invalid). 

Everything is really ok here. I created the method in the father model. I thought it would be useful to have this in the fw.

**Comment by cebe** [comment]
I do not think this is common enough to be included. @yiisoft/core-developers other opinions?

**Comment by samdark** [comment]
Yeah, it's kinda specific to the app. Thanks for suggestion @slinstj but I don't think it will make it into core framework.

**Comment by slinstj** [comment]
You are welcome :v:
