### ISSUE TITLE
Enhancement create Widget builders

### ISSUE THREAD

**Issue by fbau123** [yiisoft/yii2#8680]
Create Builder classes that allow for an easier creation of widgets, right now I find myself having to look at documentation to find the allowed properties in a widget due to the lack of IDE support for array configurations. 
The proposal would be to create a builder for each Widget, an example for GridView would be
```php
$gridBuilder  = new GridViewBuilder();
$gridBuilder->id("id")
    ->dataProvider($dp)
    ->columns([
           (new GridViewColumnBuilder())->class("clazz")->build(),
           ...
      ])
      ->build();
```

These classes could be generated with some code generation class, something like:

```php

foreach(get_class_vars('widgetClass') as $option){
      fwrite($fh, "public function $option(\$val){ \$this->$option = \$val; return \$this; }");
}

```

**Comment by klimov-paul** [comment]
My opinion: this will overcomplicate things.

**Comment by samdark** [comment]
Agree.
