### ISSUE TITLE
Sql error while getting ActiveDataProvider totalCount

### ISSUE THREAD

**Issue by dub34** [yiisoft/yii2#8697]
Hi. I get  such error
I have model Performer extends ActiveRecord and overrided method
```
public static function find()
    {
        return new UserQuery(
            get_called_class(),
            [
                'account_type' => [
                    self::ACCOUNT_TYPE_PERFORMER
                ]
            ]
        );
    }
```
Then I write method, that return ActiveDataProvider
```
 public function searchPerformers($params = []){
       $query = Performer::find();
        $dataProvider = new ActiveDataProvider([
            'query'=>$query,
//            'totalCount'=>1000
        ]);
       return $dataProvider;
    }
```
And then I give this dataProvider to GridView and receive an error
`SQLSTATE[42703]: Undefined column: 7 ERROR: column "performer" does not exist`
` SELECT COUNT(*) FROM (SELECT * FROM "user" WHERE "account_type"=performer) "c"`
string "performer" is not quoted. But in other cases it is works correctly

If I set totalCount to dataProvider, of course it works, but not count pager correct. 

I use Postgres 9.4, php 5.5.12

**Comment by cebe** [comment]
what is the code of UserQuery and how does it create the query condition?

**Comment by dub34** [comment]
```
class UserQuery extends ActiveQuery
{
    public $account_type;
    public function prepare($builder)
    {
        if ($this->account_type !== null) {
            $this->andWhere(['account_type' => $this->account_type]);
        }
        return parent::prepare($builder);
    }
}
```
