### ISSUE TITLE
Get params from referrer in class yii\web\Request

### ISSUE THREAD

**Issue by amlopezalonso** [yiisoft/yii2#8701]
Dear developers:

I really don't know whether there is a cleaner approach to this in the API but as I haven't find it: may I suggest adding a *$referrerGet* property to *yii\web\Request*?

It could be useful, for instance, to retrieve page number from an index view and feed breadcrumbs both in view/update views in order to browse back GridView results at the same page number as before.

Kind regards,
Antonio

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L835

**Comment by amlopezalonso** [comment]
I know there is already a `$referrer` property, but I meant a `$referrerGet` as a direct way of getting $_GET params from referrer.

**Comment by cebe** [comment]
a referer could be any kind of url, not necessarily application internal, you need your own url parsing to extract the parameters.

**Comment by amlopezalonso** [comment]
Understood. Thanks.
