### ISSUE TITLE
Inline registering of javascript during PJAX calls uses document.on('ready') instead of document.on('ready pjax:end')

### ISSUE THREAD

**Issue by sergeantjonas** [yiisoft/yii2#8702]
I recently changed my application to use pjax requests, but today I stumbled upon an issue while using inline javascript ($this->registerJS). The javascript is not being executed as it's wrapped in a document.ready. After doing some digging it appears the root cause lies all the way in the web/View.php file.

Line 565 has the following:
````php
$js = "jQuery(document).ready(function () {\n" . implode("\n", $this->js[self::POS_READY]) . "\n});";
````

It should be:

````php
$js = "jQuery(document).on('ready pjax:end', function () {\n" . implode("\n", $this->js[self::POS_READY]) . "\n});";
````

But then even if no PJAX is being used the pjax:end will be there, although I don't think that causes issues, there is probably a cleaner fix (checking for the PJAX request header?)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/4814

**Comment by samdark** [comment]
Shouldn't it be `pjax:success`?

**Comment by sergeantjonas** [comment]
Not sure, I'm guessing pjax:end is safer because then it will trigger no matter the result of the pjax result?

**Comment by samdark** [comment]
Should it trigger no matter what?

**Comment by samdark** [comment]
I guess if PJAX failed, there's nothing to trigger. Also what if I'll do PJAX reload of many fragments. Would that trigger event more than once and cause script to be executed again and again?

**Comment by sergeantjonas** [comment]
I figure it will only execute once per pjax reload, but not sure, I havent worked with fragments

**Comment by sergeantjonas** [comment]
As an extension on this issue, I have noticed that inline javascript which are registered by plugins (such as GridViews) are not being registered to the page during PJAX calls. For example this is my script block at the end of my page after a PJAX call:

````php
<script type="text/javascript">jQuery(document).on('ready', function () {
jQuery(document).pjax("a", "#pjax-maincontainer", {"push":true,"replace":false,"timeout":60000,"scrollTo":false});
});</script>
````

after full reload:

````php
<script type="text/javascript">jQuery(document).on('ready', function () {
var kvGridInit_00000000=function(){

};
kvGridInit_00000000();
jQuery('#adminUserGridView').yiiGridView({"filterUrl":"\/admin\/user","filterSelector":"#adminUserGridView-filters input, #adminUserGridView-filters select"});
jQuery(document).pjax("a", "#pjax-maincontainer", {"push":true,"replace":false,"timeout":60000,"scrollTo":false});
});</script>
````

I'm using the Kartik extension of the GridView, but I don't think that's relevant. The Javascript after the PJAX call is actually the javascript that's on my homepage (or well the page that was most recently fully loaded).
If this is relevant, my PJAX container is actually defined in my layout file. However if I move my PJAX container to my view files I get Javascript errors that some functions are not defined, I'm guessing the correct plugin assets are not being loaded that way?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/4814

**Comment by SilverFire** [comment]
Duplicates #4814
Duplicates #6655
Duplicates #8540
Duplicates #8916

**Comment by SilverFire** [comment]
Should be fixed by https://github.com/yiisoft/jquery-pjax/pull/30
