### ISSUE TITLE
Url::canonical() not returning expected URL

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2#8703]
Hi,

I'm currently using Yii2 for two different projects and each project has a route similar to: 'object/<objectSlug:[\w-]+>' => 'object/view'
When using Url::canonical() in the two projects seems to return different results and I can't see any obvious differences.

For example, If I navigate to http://test.com/object/test-slug.
One of them will return "http://test.com/object/test-slug" as the canonical (which is what I would hope and expect), but the other project returns "http://test.com/object/view".

Is there any obvious reason for this?
Have i enabled/disabled something for one project but not the other?

Thanks,
Gary

**Comment by samdark** [comment]
Just `object/view`? Are there any params? If the slug is required in URL rule, it should be specified when creating it.

**Comment by garyrutland** [comment]
Apologies, will try to be a bit clearer.
For the example I will use "http://www.test.com" as the host and "location" as the object.

My config file:

    ...
    'urlManager' => [
        'class' => 'yii\web\UrlManager',
        'showScriptName' => false,
        'enablePrettyUrl' => true,
        'rules' => [
            'location/<locationSlug:[\w-]+>' => 'location/view',
            ...
        ],
    ],
    ...

URL creation:

    use yii\helpers\Url;
    use app\models\Location;

    // For this example $location->locationSlug is "test-location"
    $location = Location::findOne(['locationId' => 1);
    echo Url::toRoute(['/location/view', 'locationSlug' => $location->locationSlug]);

This will generate "/location/test-location" which is what I would expect.

If I then either follow the link generated from above or manually navigate to "http://www.test.com/location/test-location" which resolves as expected.

While in the view file for "location/view" however if I do the following:

    use yii\helpers\Url;
    echo Url::canonical();

This will return "http://www.test.com/location/view" instead of "http://www.test.com/location/test-location".

I hope this makes more sense now?

Gary

**Comment by samdark** [comment]
Please show your `location/view` controller action.

**Comment by garyrutland** [comment]
Not exactly sure what you want so hope this helps:

    <?php

    namespace app\controllers;

    use Yii;
    use yii\web\Controller;
    use yii\web\HttpException;
    use app\models\Location;

    class LocationController extends Controller
    {
        public function actionView()
        {
            $location = Location::findOne([
                'locationSlug' => Yii::$app->request->get('locationSlug'),
            ]);

            if ($location === null) {
                throw new HttpException(404, 'The requested location could not be found.');
            }

            return $this->render('view', [
                'location' => $location,
            ]);
        }

        ...
    }

**Comment by samdark** [comment]
OK. The problem is that you don't have it like:

```php
public function actionView($locationSlug)
```

If you'll check phpdoc and the guide you'll see how it works.

**Comment by garyrutland** [comment]
Yup, that fixed it.
Thanks for the help.
