### ISSUE TITLE
ActiveForm - easier handling of tabular inputs

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/yii2#8706]
As described in [docs](https://github.com/yiisoft/yii2/blob/master/docs/guide/input-tabular-input.md#updating-a-fixed-set-of-records), we should use 

```php
    echo $form->field($setting, "[$index]value")->label($setting->name);
```

to render multiple model's inputs of same page.

It will be great to improve some option like `multiple` to `ActiveForm`, which will used to get some magic:

```php
$form = ActiveForm::begin(['multilple' => true]);

foreach ($settings as $setting) {
    echo $form->field($setting, "value")->label($setting->name);
}
ActiveForm::end();
```

When `multiple` is set to `true` or filled with `string`, the field name will be prepended with sub-array of primary key:
* for `true` -  
```php
'[' . array_shift($model->getPrimaryKey() . ']'
```
* for `string` - 
```php
'[' . array_shift($model->getAttribute($this->multiple) . ']'
```

Thank you for you thoughts in comments below :)

**Comment by SilverFire** [comment]
:up:

**Comment by samdark** [comment]
What if the form contains both multiple and single fields?

**Comment by SilverFire** [comment]
Then the idea fails :disappointed:

**Comment by samdark** [comment]
I have no good idea about handling it automatically... Closed till someone will come with a good idea.
