### ISSUE TITLE
CRUD issues

### ISSUE THREAD

**Issue by milosbarlov** [yiisoft/yii2#8710]
I have a problem with CRUD generator. When I generated the model, autocomplete worked fine and offered me all the tables from DB. When I wanted to generate CRUD model, autocomplete didn't offer me previous generated model.

Autocomplete works fine on my other projects.

Thank you for your help.

**Comment by cebe** [comment]
it is very hard to find all existing classes so I do not think it is feasable to provide such a feature.

**Comment by milosbarlov** [comment]
@cebe , this has worked as expected on some my previous projects. Is this disabled?

**Comment by cebe** [comment]
I doubt that, we do not have auto completion for class names.

**Comment by samdark** [comment]
@milosbarlov most probably it was your browser.

**Comment by samdark** [comment]
In order to implement it we need to scan all the project files finding ones that are ActiveRecord. For a large project it sounds like a bit too much.

**Comment by milosbarlov** [comment]
@samdark  @cebe Thanks for your help

**Comment by pana1990** [comment]
@samdark can you close this issue?

**Comment by samdark** [comment]
Done.
