### ISSUE TITLE
ActiveField::$inputOptions and $options['id']

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#8718]
i have file input with `id` in form:
```php
$form->field($model, 'filename')->fileInput(['id' => 'filename', 'class' => 'fileinput-button', 'accept' => "image/*"]); 
```
[here](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L715) when collect `clientOptions` for `yiiActiveForm` my `id` = 'filename' ignored.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L415

**Comment by lynicidn** [comment]
@cebe ok, thx, bad usability :(
