### ISSUE TITLE
Add support html5 attributes formaction/formmethod... for ActiveForm (yii.activeForm.js)

### ISSUE THREAD

**Issue by paulzi** [yiisoft/yii2#8719]
The correct behavior of the browser is interrupted in the script "yii.activeForm.js" by call $ form.submit ().
To properly occurred sending the form, you can not interrupt the behavior of the browser's default (preventDefault).

**Comment by waniel** [comment]
I also see this behaviour - I have two submit buttons in a single form with differing "formaction" attribute values however the form is always submitted to the forms "action" attribute value.

**Comment by VirtualRJ** [comment]
@samdark since this is kind of an old issue and noone is assigned I'm not sure if anyone will pick up the PR. If it will be picked up later consider this comment not submitted.
