### ISSUE TITLE
Notion. Don't know if its bug yiiActiveForm after submit

### ISSUE THREAD

**Issue by kLkA** [yiisoft/yii2#8725]
Hi, everyone! I found strange reaction while working with yiiActiveForm.js and validating data.
When we are working with validationOnSubmit normal behavior is to press submit -> yii (js) is using method methods.submitForm which checks if data validated and inserting input[type=hidden][name=submit] when we forcing submit from button. Aftewards, yii forcing second submit on form. 
The bug is occured when on tag button exisiting option [name=submit]. Probably clear JS cannot find input or something and second submit cannot be called from yii. For userthis bug looks like to need to click 2 times on button. What do you think about this reaction. Does yii need to control this situation?

**Comment by samdark** [comment]
How to reproduce it?

**Comment by kLkA** [comment]
You need to create ActiveForm with validationOnSubmit and render Html::submitButton with htmlOption
name=submit
After validation will be created input with same name and bug should happen

**Comment by sallon88** [comment]
same issue! i have the following code, and have to click submit button twice to submit the form. 

```php
<?php $form = ActiveForm::begin() ?>
<?= $form->field($model, 'username')?>
<input type="submit" name="submit" />
<?php ActiveForm::end()?>
```

**Comment by kLkA** [comment]
Btw, sorry that i didnt say that bugfix to that situation is to remove [name=submit] from your Submit button or input. But it still the strange bug

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/8756

**Comment by pana1990** [comment]
@kLkA [this](http://stackoverflow.com/questions/22982741/form-submit-jquery-does-not-work) link explain the problem that cause behavior.

**Comment by pana1990** [comment]
@kLkA see this https://api.jquery.com/submit/ 

>Forms and their child elements should not use input names or ids that conflict with properties of a form, such as submit, length, or method. Name conflicts can cause confusing failures.
