### ISSUE TITLE
index.php missing in Yii 2.0.4 advanced.

### ISSUE THREAD

**Issue by nudostilo** [yiisoft/yii2#8726]
Check the below git link,

https://github.com/yiisoft/yii2-app-advanced/tree/master/frontend/web

**Comment by sinus86** [comment]
As i know the file will be generated when you initialize an environment from cl ..

http://www.yiiframework.com/doc-2.0/guide-tutorial-advanced-app.html

**Comment by nudostilo** [comment]
Yes getting the file after initialization, but is it required even if I have downloaded via yii archives ?

**Comment by samdark** [comment]
Yes.

**Comment by nudostilo** [comment]
Thanks.
