### ISSUE TITLE
ActiveRecord::link in beforeValidate

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2#8731]
I'm trying to figure out a clean way to do this, but it seems that the framework was not designed with this specific case in mind.

I have two models with the pseudo-relation `Appointment->hasOne(Patient, ['id' => 'patient_id'])` and I'm trying to autocreate the Patient model in `beforeValidate` when the `patient_id` is null, since is required, but I want to do this in a transaction, so that if validation of the Appointment model fails, the created Patient is rolled back.

I have the option to hack this in the REST controller and every place I create this modes, but I would like to have the model itself take care of this.

I tried to use the `link` method with a new Patient model in `beforeValidate` but it swaps the models in [here](https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1218) for some reason and I get an exception `Unable to link models: the primary key of app\\models\\Patient is null`.

There is also the case where I want to create both models in the same time, it says in the documentation that only one is possible, but if this would be done in a transaction, theoretically should also work for both in the same time, starting with the primary model.

Any advice is highly appreciated. Thank you!

**Comment by razvanphp** [comment]
I tried a few more things, and this is really tricky because:
- if you call `link` in `beforeValidate`, he will immediately save it without validation, and will fail with DB errors since the rest of the attributes might not always be valid.
- when using ActiveRecord::transactions() in the Appointment model for INSERT and UPDATE it still does not work because transaction is started AFTER `beforeValidate` is run, so the related model cannot be rolled back anymore.

The only way it works is like this, but I strongly feel it's hacky, given we have all transaction and linking stuff in the framework.
````php
public function save($runValidation = true, $attributeNames = null)
{
    if (empty($this->patient_id)) {
        $transaction = static::getDb()->beginTransaction();
        try {
            $patient = new Patient();
            $patient->save();
            $this->patient_id = $patient->id;
            $result = parent::save($runValidation, $attributeNames);
            if ($result === false) {
                $transaction->rollBack();
            } else {
                $transaction->commit();
            }
            return $result;
        } catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }
    } else {
        return parent::save($runValidation, $attributeNames);
    }
}
````

**Comment by cebe** [comment]
why do you call link in beforeValidate? linking only works if you save the model so this should be done after validation. If you want to create a model inside the validation flow you can create it directly without the need to call link. just the the relevant foreign key fields and save it afterwards.

**Comment by razvanphp** [comment]
Yes, this is what I did in the working example above.

This does not solve the problem of the transaction tho, I cannot do it "the yii way" using `ActiveRecord::transactions()`.

**Comment by dynasource** [comment]
link() should not be used for complex usecases. Its designed for simple usecases in which 2 existing records already exist.
