### ISSUE TITLE
"Destroy session" enhancement

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#8733]
Is this possible to destroy session completely via delete appropriate row from DB when using DB Session? Something like that https://www.dropbox.com/s/q3mivqf3q52h8bd/Screenshot%202015-06-10%2011.16.07.png?dl=0

**Comment by klimov-paul** [comment]
See #8670

**Comment by usualdesigner** [comment]
I've talked about 'Revoke' button, not about custom session data.

**Comment by klimov-paul** [comment]
Then I don't know what are you asking about.

> Is this possible to destroy session completely via delete appropriate row from DB

Of course it is possible.

**Comment by usualdesigner** [comment]
Probably , I incorrectly expressed my thought. The issue is I want to delete user's session and after that user should type the login credentials again. For now when DB row was deleted - it created again automatically for the user.

**Comment by klimov-paul** [comment]
Most probably this happens because you have enabled `auto login` and check 'remember me' on logic form.

**Comment by usualdesigner** [comment]
@klimov-paul you're right
