### ISSUE TITLE
yii\log\Target: add current target as parameter to `$prefix`-callable

### ISSUE THREAD

**Issue by Blizzke** [yiisoft/yii2#8734]
I would like to add a single bit of information to the log prefix, but the way it is done now I cannot recuperate the already existing code in `getMessagePrefix()`

By simply passing the Target instance as second parameter to the `return call_user_func($this->prefix, $message)`-call I would be able to set the prefix to `null`, call the function normally and then restore it. All instead of having to duplicate the entire function.

If people agree I could just do a PR for it, it won't break backwards compatibility if we just add `$this` as extra parameter

**Comment by samdark** [comment]
Won't be implemented in 2.0.
