### ISSUE TITLE
Feature Reverse Serial Column

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#8741]
The current implementation of Serial Column is not capable of working with a SORT_DESC. It would be logical to have this feature in scenarios in which you are representing the most recent records first (which is very common).

Two options:
A) parameter in SerialColumn
B) a class like ReverseSerialColumn

**Comment by cebe** [comment]
what is the benefit of this column anyway?

**Comment by dynasource** [comment]
this column is useful for people to know how many items they have active, how many articles they have created, how many messages they still have open, etc etc.

**Comment by rokasr** [comment]
I would like to have that option as well.

**Comment by samdark** [comment]
@rokasr are you sure you're talking about serial column and not sortable ids?

**Comment by rokasr** [comment]
Yes I am pretty sure about that. I recently needed something like "B) a class like ReverseSerialColumn"

I can describe situation for you: my customer asked me to sort their users by created_at DESC. I did that, however they were not pleased by seeing that newest user has #1 next to it, since they know their first user registered long time ago. All I would have to do is to reverse those numbers, yet there is no function like that at the moment.

**Comment by Faryshta** [comment]
Instead of a new class how about using `DataColumn::$value` 

```php
[
    'name' => 'Descending order',
    'value' => function ($model, $key, $index, $column) {
          return $column->grid->dataProvider->totalCount - $index + 1;
    }
]
```

we can also add a property `value` to `SerialColumn` but then it will be equal to `DataColumn` imo

**Comment by SilverFire** [comment]
I don't think we must implement `ReverseSerialColumn` in the core code.

**Comment by agussuhartono** [comment]
easy code formula :

`totalCount - (serialIndex) + 1`

example : 

```
    protected function renderDataCellContent($model, $key, $index)
    {
        $pagination = $this->grid->dataProvider->getPagination();
        if ($pagination !== false) {
            return $pagination->totalCount - ($pagination->getOffset() + $index + 1) + 1;
        } else {
            return $pagination->totalCount - ($index + 1) + 1;
        }
    }
```

**Comment by agussuhartono** [comment]
on columns property

                        [
                            //'class' => 'yii\grid\SerialColumn',
                            'options' => ['width' => '25'],
                            'content' => function($model, $key, $index, $widget) {
                                $pagination = $widget->grid->dataProvider->getPagination();
                                if ($pagination !== false) {
                                   return $pagination->totalCount - ($pagination->getOffset() + $index + 1) + 1;
                                } else {
                                   return $pagination->totalCount - ($index + 1) + 1;
                                }                             }                            
                        ],

**Comment by mkozlovv** [comment]
class ReverseSerialColumn extends Column
{
    /**
     * @inheritdoc
     */
    public $header = '#';

    /**
     * @inheritdoc
     */
    protected function renderDataCellContent($model, $key, $index)
    {
        $pagination = $this->grid->dataProvider->getPagination();
        if ($pagination !== false) {
            return $pagination->totalCount - ($pagination->getOffset() + $index + 1);
        } else {
            return $this->grid->dataProvider->getTotalCount() - ($index);
        }
    }
}

**Comment by mkozlovv** [comment]
`class ReverseSerialColumn extends Column
{
    /**
     * @inheritdoc
     */
    public $header = '#';

    /**
     * @inheritdoc
     */
    protected function renderDataCellContent($model, $key, $index)
    {
        $pagination = $this->grid->dataProvider->getPagination();
        if ($pagination !== false) {
            return $pagination->totalCount - ($pagination->getOffset() + $index + 1);
        } else {
            return $this->grid->dataProvider->getTotalCount() - ($index);
        }
    }
}`

**Comment by mkozlovv** [comment]
Thanks to @agussuhartono made it to class

```class ReverseSerialColumn extends Column
{
    /**
     * @inheritdoc
     */
    public $header = '#';

    /**
     * @inheritdoc
     */
    protected function renderDataCellContent($model, $key, $index)
    {
        $pagination = $this->grid->dataProvider->getPagination();
        if ($pagination !== false) {
            return $pagination->totalCount - ($pagination->getOffset() + $index + 1);
        } else {
            return $this->grid->dataProvider->getTotalCount() - ($index);
        }
    }
}```

**Comment by agussuhartono** [comment]
great @mkozlovv
