### ISSUE TITLE
Auth Manager Documentation

### ISSUE THREAD

**Issue by jepster** [yiisoft/yii2#8742]
Hi,

I would like to contribute to the documentation. A page about creating users, attaching them to roles, creating permissions etc. I've done something with that part of the Yii 2 functionality via the auth manager.

It was a while ago when I found some description about how to get the relevant user tables like auth_assignment, auth_item, auth_item_child, auth_rule and user. Have you any clue how these tables can be created via the yii terminal application? An url with some description would already help.

Thank you.

**Comment by samdark** [comment]
It's documented in `DbManager` class: http://www.yiiframework.com/doc-2.0/yii-rbac-dbmanager.html

**Comment by jepster** [comment]
Thanks. How the auth_* tables will be created?

**Comment by jepster** [comment]
Okay found it at http://www.yiiframework.com/doc-2.0/guide-security-authorization.html
