### ISSUE TITLE
defaultScope, relation alias

### ISSUE THREAD

**Issue by JamesBarnsley** [yiisoft/yii2#8743]
Hi,

I am having to use relationship alias when referencing my join because I have two foreign keys that reference the same table.

The problem is this breaks my default scope ...

```php
public static function find() {

	return parent::find()->where([static::tableName() . ".deleted" => 0]);
							
}
```

The reason why it breaks is because it is looking for tableName() but the relationship is needing to use the alias so the tableName() will not work.

**Comment by cebe** [comment]
can you show the query you are trying to run? also include the names of the models so it is clear which is realted to which one.

**Comment by JamesBarnsley** [comment]
Hi,

Here is the query, I have a PrivateMessageTopic model which is related to the User model.

As you can see in the joinWith() part of the query, I have used the "from" to get the second relation as "userTo".

```php
$query = PrivateMessageTopic::find();
			
$query->joinWith(["user", "userTo" => function($q) { $q->from("user userTo"); }]);
						
$query->orWhere(["fkIDWithUserID" => Yii::$app->user->id])->orWhere(["fkIDWithUserIDTo" => Yii::$app->user->id]);
							
$activeDataProvider = new ActiveDataProvider([
				
	"query" => $query,
	"pagination" => [
					
		"pageSize" => 20
					
	]
				
]);
```
But this causes problems because the find() is looking for the tableName()

**Comment by cebe** [comment]
closing this as duplicate of #7263
