### ISSUE TITLE
ip address behind load balancer

### ISSUE THREAD

**Issue by nikunjtrapasiya** [yiisoft/yii2#8746]
function getUserIP() returns local ip address if the servers are behind load balancer (i am using aws)

```
    public function getUserIP()
    {
        return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : null;
    }
```

i need to change it to each time i upgrade my framework

```
return (isset($_SERVER['HTTP_X_FORWARDED_FOR']) && $_SERVER['HTTP_X_FORWARDED_FOR']) ? $_SERVER['HTTP_X_FORWARDED_FOR'] : null;
```

is there any way i can override the function in my config file or somewhere so i can still use it for logging purpose.

**Comment by samdark** [comment]
Yes.

1. Create your own class that extends from `\yii\web\Request`.
2. Override `getUserIP()`.
3. In the config, specify new class as `request` component.

**Comment by cebe** [comment]
or overwrite `$_SERVER['REMOTE_ADDR']` in index.php

**Comment by dizews** [comment]
hello, what do you think if we implement this functionality like in [symphony](https://github.com/symfony/symfony/blob/v2.2.0/src/Symfony/Component/HttpFoundation/Request.php#L708) ?

**Comment by samdark** [comment]
Via separate method? Yes, that's OK.

**Comment by dizews** [comment]
@samdark I suggest to reimplement ```getUserIP``` which should use trustedHeaders property of request object and make docs how it influence to security.

**Comment by cebe** [comment]
related to #10854 and #13050

**Comment by cebe** [comment]
closing as duplicate of #10854
