### ISSUE TITLE
AR transactions logic. Dont you think is that imperfection?

### ISSUE THREAD

**Issue by kLkA** [yiisoft/yii2#8749]
Hi, i wrote code for redeclare delete method of AR
```php
public function delete()
    {
        $userOrgBinds = UserOrgBind::find()->where([
            'org_id' => $this->id
        ])->all();
         foreach ($userOrgBinds as $userOrgBind) {
            $userOrgBind->delete();
        }
        foreach ($this->addresses as $address) {
            $address->delete();
        }
        foreach ($this->sellOrders as $sellOrderBind) {
            $sellOrderBind->order->delete();
        }
        foreach ($this->invoices as $invoice) {
            $invoice->delete();
        }
        foreach ($this->vendors as $vendor) {
            $shippingRecords = ShippingRecord::find()->where([
                    'vendor_id' => $vendor->id
                ])->all();
            foreach ($shippingRecords as $shippingRecord) {
                $shippingRecord->delete();
            }
            $buyOrders = BuyOrder::find()->where([
                    'vendor_id' => $vendor->id
                ])->all();
            foreach ($buyOrders as $shippingRecord) {
                $shippingRecord->delete();
            }
            $vendor->delete();
        }

        parent::delete();
    }
```
After that i decided to make a transaction which will fully support this code with commit/rollback function.
In guide i found 3 ways to perform support transaction for whole code
1. Refactor it into one big DAO transaction with queryBuilder commands
2. Make x-level nesting transaction(x == count of AR types here)
3. use transactions() method for scenario === 'delete'
First way is very complex to refactor.
Second way is quite unreadable
Third way seems to be good but i found some imperfection to my mind
In above code we can see that transactions() method will work only on last method 
```php
parent::delete() 
```
Other delete methods will not see in their transactions() array delete scenarion and so on.
Is it good idea to send into $otherActiveRecordModel transaction rules to save consistency without much nesting ?
```php
$customer :: Customer::find()
Customer::getDb()->beginTransaction(function($db) use ($customer) {
...
$otherActiveRecordModel->delete()
});
```

**Comment by cebe** [comment]
why don't you override `beforeDelete()` instead of `delete()` ?

**Comment by kLkA** [comment]
Will it help to control all errors on deleting in that transaction?

**Comment by cebe** [comment]
this way you have it all wrapped in the transaction, yes.

**Comment by kLkA** [comment]
Got that. Thank you.
