### ISSUE TITLE
Yii2 does not properly handle name quoting character when MySQL is run in ANSI mode

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#8750]
How to reproduce the problem: configure MySQL to run in ANSI or ANSI_QUOTES mode. Run gii and try to create a model for any table with foreign key to another table.

When MySQL is run in ANSI or ANSI_QOUTES mode the character to escape database names is double quote as in standard ANSI SQL. And while in these modes backtick (`) character still works for quoting MySQL names, when executing SQLs such as "SHOW CREATE TABLE" MySQl will return the result with names quoted with double quote character but Yii2 expects it to contain backtick character.

Some references:
https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sqlmode_ansi
https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sqlmode_ansi_quotes

Alot of code in yiisoft\yii2\db\mysql\Schema.php is affected by this bug. For example, in function findConstraints($table):

```
$fks = array_map('trim', explode(',', str_replace('`', '', $match[1])));
$pks = array_map('trim', explode(',', str_replace('`', '', $match[3])));
```

etc. The lines above remove backtick while the string returned by MySQL contains double quote instead of backtick.

**Comment by cebe** [comment]
whats the benefit of turning that mode on?

**Comment by PowerGamer1** [comment]
The benefit is a compliance with the ISO/IEC 9075 SQL standard which is always a good thing - makes it easier to switch to another database, etc.

**Comment by nineinchnick** [comment]
Maybe the relevant code could check for the current mode? I've added a similar check for Oracle when using `PDO::CASE_UPPER`.

**Comment by PowerGamer1** [comment]
Related issue: https://github.com/yiisoft/yii2/issues/8765
