### ISSUE TITLE
yii\rest\UrlRule patterns should specify OPTIONS verb

### ISSUE THREAD

**Issue by spikyjt** [yiisoft/yii2#8751]
The default `$patterns` property is currently
```php
    [
        'PUT,PATCH {id}' => 'update',
        'DELETE {id}' => 'delete',
        'GET,HEAD {id}' => 'view',
        'POST' => 'create',
        'GET,HEAD' => 'index',
        '{id}' => 'options',
        '' => 'options',
    ];
```
However, if you set `$extraPatterns` to have a rule that is a collection action with another verb, for instance: `'DELETE' => 'deleteAll'` then you can never match this extra pattern, because the pattern for `options` is a catch all, but gets matched first, before anything in`$extraPatterns`.

It should have the `OPTIONS` verb specified so that it is explicit, i.e.:
```php
    [
        'PUT,PATCH {id}' => 'update',
        'DELETE {id}' => 'delete',
        'GET,HEAD {id}' => 'view',
        'POST' => 'create',
        'GET,HEAD' => 'index',
        'OPTIONS {id}' => 'options',
        'OPTIONS' => 'options',
    ];
```

**Comment by Agrumas** [comment]
Could not replicate, @spikyjt please check if you are using latest yii version(2.0.4), because that release includes changes(#8055) for extraPatterns

**Comment by spikyjt** [comment]
You are right, I was still on version 2.0.3 on the project where I needed this. That said, I still think the OPTIONS verb should be specified explicitly. Why make the rule a catch all when OPTIONS is a verb? Perhaps whoever wrote the original code ( @qiangxue ?) can comment on this?

**Comment by cebe** [comment]
the idea of catchall is that the OptionsAction can respond with method not allowed error on the Url instead of a 404 from the router.

**Comment by spikyjt** [comment]
Fair enough. In which case, this is already fixed, sorry for wasting your time.
