### ISSUE TITLE
Consistency problem: specifying attributes in rules() vs validation of specific attributes

### ISSUE THREAD

**Issue by Blizzke** [yiisoft/yii2#8752]
When specifying the validation rules for a model it is allowed to either use a `string` for a single attribute or an `array` for multiple. The framework detects this automatically.

Yet if you want to validate a single attribute (`$model->validate(['attributeName'])`) you are forced to specify an array. A single attribute string is [simply discarded](https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L230) in this case. 
This behaviour should be consistent in al related places and also detect a string and convert it.  

While not a bug, it might be confusing and [cause unexpected errors](http://stackoverflow.com/q/30778690/50158).

**Comment by cebe** [comment]
may be useful. What do you mean with "This behaviour should be consistent in al related places"? which places?

**Comment by Blizzke** [comment]
I just meant it as a generic remark. Do it at one spot, do it everywhere. :)
