### ISSUE TITLE
Codeception acceptance tests. Fixtures loaded after webdriver session starts?

### ISSUE THREAD

**Issue by PommeVerte** [yiisoft/yii2#8754]
Hey guys,

I'm not really sure where the issue stems here as I haven't dived into this too deeply. But it feels like yii2 does the following:

- starts a session with webdriver
- loads fixture for the suite
- runs multiple acceptance tests
- unloads/stops everything

If I'm not mistaken about the process this is a little problematic. 
I've been running into issues where my session would timeout before my fixtures were loaded. I use third party services like browserStack/sauceLabs/etc. for my acceptance tests and the fixtures take some time to fully run (several minutes).

This is obviously an issue since it throws an error. But it's also painful because we can end up paying these third party services for time used loading our fixtures and not running tests.

I don't know if this is something that needs to be reported to codeception rather than here. Let me know and I'll be happy to do it.

**Comment by samdark** [comment]
What do you propose to solve it?

**Comment by PommeVerte** [comment]
I haven't had time to take a look at the code (I'll do so over the weekend). But the idea would be to load the fixtures before initializing the webdriver session.
