### ISSUE TITLE
Mongodb embed attributeName surpport

### ISSUE THREAD

**Issue by monochrome-yeh** [yiisoft/yii2#8755]
will like this:
   public static function getAttributeName($attribute, $model)
    {
if ( $model instanceof \yii\mongodb\ActiveRecord) {
        if (preg_match('/(^|.*)([\w\.]+)(.*|$)/', $attribute, $matches)) {
            return $matches[2];
        } else {
            throw new InvalidParamException('Attribute name must contain word characters only.');
        }
}
else {
        if (preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
            return $matches[2];
        } else {
            throw new InvalidParamException('Attribute name must contain word characters only.');
        }
}
    }

**Comment by klimov-paul** [comment]
Please resubmit this issue to https://github.com/yiisoft/yii2-mongodb , if you still concern of it.
Provide more clear description: I can not understand where `getAttributeName()` should belong and for what purpose.
