### ISSUE TITLE
AssetConverter to convert php -> css or js

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii2#8757]
I want to have css file to be generated with a php template, eg:

```php
use name\space\OtherAssetWithImages;

$asset = OtherAssetWithImages::register($this);
?>
.logo {
    background: url(<?= "{$asset->baseUrl}/images/logo.png" ?>) no-repeat;
}
```

And I will use it from asset like this:

```php
class MyAsset extends \yii\web\AssetBundle
{
    public $css = [
        'css/my.php',
    ];
    public $depends = [
        'name\space\OtherAssetWithImages',
    ];
}
```

So what do you think about adding such feature to core.
I can do it, I already tried, it works.

Actually I want to use images from one asset in another, I don't see a better way.

**Comment by SilverFire** [comment]
Yeah, this might be very useful.
I think that `my.css` should be published instead of `my.php` in a result of processing.

**Comment by klimov-paul** [comment]
You may do so already. Just add the following to the `AssetConverter::commands`:
```php
'php' => ['css', 'php -f {from} > {to}'],
```

**Comment by hiqsol** [comment]
For this solution to work it is necessary to bootstrap Yii inside of the template file, which is not nice.

Also please think of about a bit more:

```php
{
    public $css = [
        'css/my.php',
        'css/other.twig', // smarty, ..
    ];
    public $js = [
        'js/my.php',
        'js/other.twig',
    ];
}
```

Which could be added with few lines of code.

**Comment by klimov-paul** [comment]
You may generate your assets via any controller/action dynamically.
So your asset bundle may look like following:
```php
class AppAsset extends AssetBundle
{
    public $baseUrl = '@web';
    public $css = [
        'index.php?r=css/site',
    ];
    public $js = [
        'index.php?r=js/site',
    ];
}
```
