### ISSUE TITLE
using zend lucene in yii2 framework

### ISSUE THREAD

**Issue by nishanthpininti** [yiisoft/yii2#8759]
i am working in yii2 framework, i need to implement search functionality in my application so i am using  zend lucence,  i tried to download himiklab/yii2-search-component-v2 via composer, but it is failing showing error as 
 Problem 1
   - himiklab/yii2-search-component-v2 2.0.1 requires zendframework/zendsearch
 -> no matching package found.
   - himiklab/yii2-search-component-v2 2.0.0 requires zendframework/zendsearch
 -> no matching package found.
   - Installation request for himiklab/yii2-search-component-v2 * -> satisfiabl
 by himiklab/yii2-search-component-v2[2.0.0, 2.0.1].

is it i needed to install zendframework?

**Comment by klimov-paul** [comment]
There are no plans for support plain Lucene, while <a href="https://github.com/yiisoft/yii2-elasticsearch">ElasticSearch</a> extension is available.
If you have a problem with 3rd party extension, contact its author for consulting.

**Comment by nishanthpininti** [comment]
is it not possible to use himiklab/yii2-search-component-v2 2.0.1 which has a dependeny of zend/zendsearch in yii2 framework

**Comment by cebe** [comment]
this is not a problem with yii but with the zend component which does not seem to have a stable release: https://packagist.org/packages/zendframework/zendsearch

you have to add something like this to your require section in composer.json to allow the rc version to be installed: `"zendframework/zendsearch": "2.0.0rc5"`
