### ISSUE TITLE
advanced project template backend does not have Alert widget enabled by default

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#8762]
the frontend main layout has 

```php
use frontend\widgets\Alert;

# line 60ish
<?= Alert::widget() ?>
```
it's great because setFlash just works. Now, on the backend, it took me awhile to figure out why setFlash does not work. It turns out, Alert is not enabled by default in backend layout. I suggest it should be enabled by default.

so under backend\views\layout\main.php, add the following

```php
use frontend\widgets\Alert; #new code
.
.
<div class="container">
<?= Breadcrumbs::widget([
     'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
]) ?>
<?= Alert::widget() ?> # this line of code allow Flash Messages work automatically
<?= $content ?>
</div>
```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/commit/a38f71c4a2381b49c9338b028e96fe1a76d37a00

**Comment by samdark** [comment]
Thanks for a good idea.
