### ISSUE TITLE
Unable to verify your data submission

### ISSUE THREAD

**Issue by shorif2000** [yiisoft/yii2#8767]
I am suddenly recieving this problem when it used to work before and do not know how to resolve this. I am submitting a form with multiple files.

My action 

<pre>
public function actionCreate()
    {
        $model = new Surveys();
        $connection_prod = \Yii::$app->db2;
        try {
        	$connection_prod->open();
        } catch (yii\db\Exception  $e) {
        	\Yii::$app->mailer->compose()
        	->setFrom(['shapefiles@'.\Yii::$app->params['server'] => 'Shapefiles'])
        	->setTo(array("sharif.uddin@domain.com"))
        	->setSubject("DB Exception")
        	->setHtmlBody('Mysql connection to production not active')
        	->setReplyTo(\Yii::$app->params['adminEmail'])
        	->send();
        	throw new \yii\db\Exception('Mysql connection to production not active');
        }
        
        	
        
        	
        
        $contents = Countries::find()->all();
        $countryList = ArrayHelper::map($contents, 'country_id', 'country');
        
        $contents = Regions::find()->all();
        $regionList = ArrayHelper::map($contents, 'region_id', 'name');
        
        $surveyTypeList = ["2D"=>"2D","3D"=>"3D"];

        if ( $model->load(Yii::$app->request->post()) ) {
        	$shapefile = "";
        	for($i=0;$i < count($_FILES['UploadForm']['tmp_name']['shapefiles']);$i++) {
        		$filename = str_replace(' ', '', $_FILES['UploadForm']['name']['shapefiles'][$i]);
        		copy($_FILES['UploadForm']['tmp_name']['shapefiles'][$i],"/tmp/".$filename);
        		$ext = pathinfo("/tmp/".$filename, PATHINFO_EXTENSION);
        		if($ext == "shp")
        			$shapefile = "/tmp/".$filename;
        	}
        	$model->published = $model::NEW_S; //NEW
        	Yii::error(print_r($model->attributes,true));
        	
        	$rid = $model->region_id;
        	$s = ($model->published == $model::PUBLISHED ) ? "-s" : "";
        	$cmd = "java -Xmx1024M -XX:PermSize=64M -XX:MaxPermSize=1024m -jar /opt/mcmap/library/Application/geotools/mcgeotools.jar -t converter -i $shapefile -rid $rid $s";
        	exec($cmd, $output, $return);
        	Yii::error($cmd);
        	//echo "<br>output<br>";
        	//print_r($output);
        	
        	if(count($output) <= 4)
        		exit();
        	
        	$success = false;
        	if(strpos($output[0], 'Region id') !== FALSE)
        		$success = true;
        	else{
        		echo "Failed executing $cmd";
        		
        		exit();
        	}
        	
        	if(strpos($output[1], 'runconvert rid passed') !== FALSE)
        		$success = true;
        	else{
        		echo "Failed executing $cmd";
        		exit();
        	}
        	
        	if(strpos($output[2], 'Database connection acquired') !== FALSE)
        		$success = true;
        	else{
        		echo "Failed executing $cmd";
        		exit();
        	}
        	
        	if(strpos($output[3], 'Coordinates length') !== FALSE)
        		$success = true;
        	else{
        		echo "Failed executing $cmd";
        		exit();
        	}
        	
        	if(!$return)
        		print_r($output);
        	
        	$connection = \Yii::$app->db;
        	$model_survey_id_max = $connection->createCommand('SELECT max(survey_id) FROM surveys where date_added like "'.date('Y-m-d').'%"');
			$survey_id_max = $model_survey_id_max->queryScalar();
			
			$java_model = Surveys::findOne($survey_id_max);
			$java_model->attributes = $model->attributes;
			//print_r($java_model->attributes);
			
			
			
			//run production java
        	$cmd = "java -Xmx1024M -XX:PermSize=64M -XX:MaxPermSize=1024m -jar /opt/mcmap/library/Application/geotools/mcgeotools.jar -t publisher -i $shapefile -rid $rid $s";
        	exec($cmd, $output, $return);
        	
			if(!$return)
				print_r($output);
			
			if(count($output) <= 4)
				exit();
			 
			$success = false;
			if(strpos($output[0], 'Region id') !== FALSE)
				$success = true;
			else{
				echo "Failed executing $cmd";			
				exit();
			}
			 
			if(strpos($output[1], 'runconvert rid passed') !== FALSE)
				$success = true;
        	else{
				echo "Failed executing $cmd";
				exit();
			}
			 
			if(strpos($output[2], 'Database connection acquired') !== FALSE)
				$success = true;
			else{
				echo "Failed executing $cmd";
        		exit();
			}
			 
			if(strpos($output[3], 'Coordinates length') !== FALSE)
				$success = true;
			else{
				echo "Failed executing $cmd";
				exit();
			}
			
			//check both survey_ids match or do not proceed any further			
			$model_survey_id_max = $connection_prod->createCommand('SELECT max(survey_id) FROM surveys where date_added like "'.date('Y-m-d').'%"');
			$survey_id_max = $model_survey_id_max->queryScalar();
			
			
			if($survey_id_max != $java_model->survey_id){
				echo "Survey Ids do not match between localhost and production. Database is in inconsistent state;";
				throw new Exception ("Survey Ids do not match between localhost and production. Database is in inconsistent state;");
			}
			
			//exit();
			$transaction_prod = $connection_prod->beginTransaction();
			try {
				$set = array();
				foreach ($java_model->attributes as $key => $value) {
					$set[] = "`$key`='$value'";
				}
			
				$set = implode(",",$set);
				$sql = "UPDATE surveys set $set WHERE survey_id = ". $java_model->survey_id;
				$connection_prod->createCommand($sql)->execute();
			
				$transaction_prod->commit();
				$java_model->save();
			
				$this->sendMail($java_model,"create");
				$connection_prod->close();
				return $this->redirect(['view', 'id' => $java_model->survey_id]);
			
			}catch (Exception $e) {
				$transaction_prod->rollBack();
			}
						
        } else {
        	$connection_prod->close();
            return $this->render('create', [
                'model' => $model,
            	'countryList' => $countryList,
            	'regionList' => $regionList,
            	'surveyTypeList' => $surveyTypeList
            ]);
        }
    }
</pre>

<pre>
2015-06-12 14:51:01 [172.16.0.85][-][-][error][yii\web\HttpException:400] exception 'yii\web\BadRequestHttpException' with message 'Unable to verify your data submission.' in /opt/new-website/httpdocs/mcmap/shapefiles/vendor/yiisoft/yii2/web/Controller.php:110
Stack trace:
#0 /opt/new-website/httpdocs/mcmap/shapefiles/vendor/yiisoft/yii2/base/Controller.php(149): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /opt/new-website/httpdocs/mcmap/shapefiles/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('create', Array)
#2 /opt/new-website/httpdocs/mcmap/shapefiles/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction('surveys/create', Array)
#3 /opt/new-website/httpdocs/mcmap/shapefiles/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#4 /opt/new-website/httpdocs/mcmap/shapefiles/web/index.php(17): yii\base\Application->run()
#5 {main}
2015-06-12 14:51:01 [172.16.0.85][-][-][info][application] $_GET = [
    'r' => 'surveys/create'
]

$_COOKIE = [
    '_csrf' => '686f9e8c0f5721fd14516c72e416ccec5d9d77c7a3b64d23220b5273d3f346d2a:2:{i:0;s:5:\"_csrf\";i:1;s:32:\"QlUEHZpXYL0vBqPBeAb_RpadEATvAHzs\";}'
]

$_SERVER = [
    'AUTHORIZE_USERPRINCIPALNAME' => 'sharifu@domain.com'
    'HTTP_HOST' => 'website-qc.uk.domain.com'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
    'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en;q=0.5'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate'
    'HTTP_REFERER' => 'http://website-qc.uk.domain.com/shapefiles/index.php?r=surveys%2Fcreate'
    'HTTP_COOKIE' => '_csrf=686f9e8c0f5721fd14516c72e416ccec5d9d77c7a3b64d23220b5273d3f346d2a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22QlUEHZpXYL0vBqPBeAb_RpadEATvAHzs%22%3B%7D'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_PRAGMA' => 'no-cache'
    'HTTP_CACHE_CONTROL' => 'no-cache'
    'CONTENT_TYPE' => 'multipart/form-data; boundary=---------------------------2969119143586'
    'CONTENT_LENGTH' => '10560280'
    'PATH' => '/sbin:/usr/sbin:/bin:/usr/bin'
    'SERVER_SIGNATURE' => '<address>Apache/2.2.15 (CentOS) Server at website-qc.uk.domain.com Port 80</address>
'
    'SERVER_SOFTWARE' => 'Apache/2.2.15 (CentOS)'
    'SERVER_NAME' => 'website-qc.uk.domain.com'
    'SERVER_ADDR' => '172.16.0.44'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '172.16.0.85'
    'DOCUMENT_ROOT' => '/opt/new-website/httpdocs'
    'SERVER_ADMIN' => 'root@localhost'
    'SCRIPT_FILENAME' => '/opt/mcmap/shapefiles/web/index.php'
    'REMOTE_PORT' => '62045'
    'REMOTE_USER' => 'sharifu@DOMAIN.COM'
    'AUTH_TYPE' => 'Basic'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'POST'
    'QUERY_STRING' => 'r=surveys%2Fcreate'
    'REQUEST_URI' => '/shapefiles/index.php?r=surveys%2Fcreate'
    'SCRIPT_NAME' => '/shapefiles/index.php'
    'PHP_SELF' => '/shapefiles/index.php'
    'PHP_AUTH_USER' => 'sharifu'
    'PHP_AUTH_PW' => 'xxx'
    'REQUEST_TIME_FLOAT' => 1434120661.024
    'REQUEST_TIME' => 1434120661
]
</pre>

**Comment by samdark** [comment]
Please use forums if you don't know how to reproduce the bug.
