### ISSUE TITLE
Option in Gii to select column of composite foreign key to use for naming getter in model

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#8768]
Lets say I have a table Project with a composite foreign key with two columns (account_id,created_by) to another table User. In such a case Gii uses the name of the FIRST column of composite key for a getter in the Project class:
```
public function getAccount1()
{
    return $this->hasOne(User::className(), ['account_id' => 'account_id', 'id' => 'created_by']);
}
```
But in reality the getter needs to be named after the LAST column in the composite foreign key:
```
public function getCreatedBy()
{
    return $this->hasOne(User::className(), ['account_id' => 'account_id', 'id' => 'created_by']);
}
```
So it would be nice to have an option in Gii interface to select which column of composite foreign key to use for naming getters (first or last).

**Comment by nineinchnick** [comment]
You should create this issue in the [yii2-gii repo](https://github.com/yiisoft/yii2-gii).

In my opinion composite keys are rare and naming can be fixed after generating the model. If you use them extensively you could create your own generator that extends from the default one.

I've already added more than 4 new options to my own generator. The default one should not be overloaded with them.

**Comment by PowerGamer1** [comment]
Closing this issue as it was submitted to the wrong repo.
