### ISSUE TITLE
GridView , the filter will not work for duplicated columns

### ISSUE THREAD

**Issue by ScottHuangZL** [yiisoft/yii2#8769]
Dear Yii2 Team,

As for some grid, we may have many columns, and screen width cannot show all columns.

So we intend to add one or two duplicated columns into mid of grid to ensure user can know that row for what keys when user scroll grid to right.

For example: c1 columns show 2 times in below grid.
c1, c2, c3,...c8,    c1    ,c9,c10,c11,c12...c16

The issue is that I have to disable the filter for one of the c1 column, or else I cannot filter any c1 column.

Can Yii2 team to resolve it to allow both c1 column can filter? thanks.

Regards,
Scott Huang

**Comment by cebe** [comment]
> The issue is that I have to disable the filter for one of the c1 column, or else I cannot filter any c1 column.

what exactly is the problem here? what does not work?

**Comment by ScottHuangZL** [comment]
The text type in c1 filter field will disappear and not build in search modal. It will work if I only let one c1 available for filter.

**Comment by Faryshta** [comment]
@cebe lets say you have a filter `UserSearch[email]` being used twice. The url generated by the `GridView` will be

`UserSearch[email]=gmail.com&UserSearch[email]=&`

The first one regrites the second one.

@ScottHuangZL have you tried to use different attribute names for them?

Example

```php
[
  'attribute' => 'email[0]',
  'value' => 'email',
  'format' => 'text',
],
[
  'attribute' => 'email[1]',
  'value' => 'email',
  'format' => 'email',
],
```

**Comment by ScottHuangZL** [comment]
no, I just use same attribute since it is one filter in db. It shou be framework to easy for user.

**Comment by Faryshta** [comment]
@ScottHuangZL i gave you a solution, there is nothing the framework can do to fix that since when you replicate the attribute you rewrite the first time the attribute is sent. What you are doing is the equivalent of

```php
$attribute = 'value1';
$attribute = '';
```

Which obviously rewrites the value of the attribute and you can't get the first value unless you use different names or other ways to make a distinction among them.

**Comment by ScottHuangZL** [comment]
For same attribute the most nature way is generate same filter at url.

lets say you have a filter UserSearch[email] being used twice. The url generated by the GridView will be
UserSearch[email]=xxx
UserSearch[email]=

Why not generate both xxx?

**Comment by cebe** [comment]
@ScottHuangZL "xxx" is what you type. the problem here is that you can not change the first input to change the filter because the second will overwrite it.

**Comment by ScottHuangZL** [comment]
np.  Actually,that only small issue,and i have alt solution at very beginning. Post here just expect framework have elegant build in solution.
