### ISSUE TITLE
ActiveRecord groupBy()->joinWith('relation',false)->asArray() should be supported

### ISSUE THREAD

**Issue by MeyerJL** [yiisoft/yii2#8772]
Currently if you try to do a combination of groupBy()->joinWith('relation', false)->asArray() you get caught by the requirement of having a primary key as part of the select statement. I think that this use case should be supported as long as there are no other eager loading or lazy loading joins present in the query builder.

I think this would just be a matter of tweaking the ActiveQuery `populate` function to check to make sure that there are no with statements, no joins that use eager loading, and that asArray is true and if they are simply return the `$models` variable without doing anything else.

**Comment by Faryshta** [comment]
can you give an example of what that will return?

and why `groupBy()` doesn't have any column specified.

**Comment by MeyerJL** [comment]
The groupBy() doesn't matter so long as it's not the primary key it could be anything. The important part is the `joinWith` being non eagerly loaded and running it `asArray` and attempting to group by.

So for example:

```
Student::find()
->select(['student.instructor', 'AVG(studentScore.scores) AS averageScore']
->joinWith('studentScores', false)
->groupBy(['student.instructor'])
->asArray()
->all()
```

I would exect the results to look something like this:
```
[
    [ 'instructor' => 'Jim', 'averageScore' => 88],
    [ 'instructor' => 'Jane', 'averageScore' => 92],
    [ 'instructor' => 'Bob', 'averageScore' => 85],
]
```

Currently though (assuming that instructor isn't the primary key on the student table) the populate function tries to run, and it can't find the primary key, even though in this case there is no need to have it because the join happens on the database side of things and not in yii because I set joinWith to false.

**Comment by Faryshta** [comment]
your issue is hard, i am checking the code and for all i know the populating query should not be called because of this line https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L409

on your log, do you know more info about when the queries are called or any more info?

**Comment by cebe** [comment]
fixed, thanks for reporting!

**Comment by MeyerJL** [comment]
Thanks @cebe!
