### ISSUE TITLE
Model::findOne() invalid return ??

### ISSUE THREAD

**Issue by arydeoblo** [yiisoft/yii2#8775]
I've record on my users_table, and one column primary key id_user.
Let's say the url of update user :
http://localhost/index.php?r=admin/user-update&id=1
which mean my user id is 1.
when I tried doing this :

if(($model = Model::findOne($id) !== null){
return $model;
}else{
throw new NotFoundHttpException('not found');
}

It's ok when the get Url http://localhost/index.php?r=admin/user-update&id=1
But when I tested the url with http://localhost/index.php?r=admin/user-update&id=1a.
It's return the valid data for id_user 1.
I tested again with http://localhost/index.php?r=admin/user-update&id=a1
It's throw to Not Found.

So i tested url http://localhost/index.php?r=admin/user-update&id=1(randomstringxxxxxxxxxxxxx).
Yeah it's return to data user with id_user 1.

I'm using Yii 2.0.4

**Comment by samdark** [comment]
That's how MySQL works.
