### ISSUE TITLE
Strange behaviour of $this->title

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8777]
I'm using database based i18n. Config looks like this

        'i18n' => [
            'translations' => [
                '*' => [
                    'class' => 'yii\i18n\DbMessageSource',
                    'sourceLanguage' => 'en',
                    'sourceMessageTable' => 'source_message',
                    'messageTable' => 'message',
                ],
            ],
        ],

When I write something like this 

     $this->title = Yii::t("app", "test");

`./yii message/extract` command doesn't recognize it and insert it into database. 

Even if I manually insert this message into database and put differenet values for each language, $this->title reads value as just `test`

Question is, why? What am I doing wrong?

**Comment by samdark** [comment]
What's the `Yii::$app->language`?

**Comment by turalsprofile** [comment]
It's en, but what it has to do with actual problem? It does what it has to, when I seperately echo Yii::t("app", "test"); inside same view. But doesn't even collect to database when I assign

**Comment by lynicidn** [comment]
u should override `app` and `yii` categories, `*` check of end.
