### ISSUE TITLE
Automatically set enctype form option when using file input field

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#8779]
What if when using file input like that:

```php
<?= $form->field($model, 'imgFile')->fileInput() ?>
```

the `enctype` will be set to `multipart/form-data` automatically?

**Comment by samdark** [comment]
Yeah, that's alright thing to do. Any idea on implementation?

**Comment by arogachev** [comment]
The open form tag renders before fields, so maybe it will be better to add this via JS (`yii.activeForm.js`)?

**Comment by klimov-paul** [comment]
Such feature has been rejected at Yii1, see discussion at: https://github.com/yiisoft/yii/issues/2158

**Comment by cebe** [comment]
I am against this unless there is a very simple way to do it which does not involve JS.

**Comment by samdark** [comment]
Checked current implementation. Nothing changes in the process of rendering a form so it's not that easy to implement. Closing it.

@arogachev if you have an idea on how to implement it, let us know.

**Comment by lynicidn** [comment]
у ту амигос есть расширение файл аплоадер, так вот если виджетом рендерить его, то оно аяксово грузит файл, а хайден элемент потом можно засовывать имя загруженного файла, я все это к тому - пример формы с файловым полем, где не нужна логика, которую вы описываете, без нее, я знаю чето у меня только одна точка загрузки файлов - экшн аплоад, а с вашей логикой, файлы могут быть с отключенным яваскриптом отсылаться еще и на главный form action, что имхо уже не прозрачно

**Comment by petrabarus** [comment]
@cebe & @pana1990:
I just updated the Yii version using the newest. Somewhat the commit 425ee440630fad42fe31225b057ef207e1b7cb63 (or 1bd4c0cab5fa908dc7ca4baeaadff2bb2c97919c) breaks on my app. Still looking on how to produce.

**Comment by petrabarus** [comment]
Never mind, false alarm.

Turns out there is a bug in my code that writes

```
$form = new \yii\widgets\ActiveForm();
```

instead of

```
$form = \yii\widgets\ActiveForm::begin();
```
