### ISSUE TITLE
Newly uploaded image not showing on web page

### ISSUE THREAD

**Issue by 256cool** [yiisoft/yii2#8780]
Hi, I have to develop a profile page which has user image shown and an update button to change the profile picture. To show image and update button in view looks like below
```
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
	<?= Html::img($imgPath,['width'=>100,'height'=>100]);?>
	<?= $form->field($model, 'imageFile')->fileInput(); ?>
	<?= Html::submitButton('Update Profile Picture',['class'=>'btn btn-primary','id'=>'uploadButton']) ?>
	<?php ActiveForm::end() ?>
```
With fileInput I am choosing new file and saving it on server with below line
```
$model->imageFile->saveAs('uploads/profilepictures/' . $session['user_name'] . '_profimg.' . $model->imageFile->extension);
```
The image is successfully getting uploaded to server but when I refresh my web page the old image is displayed even though it is replaced in server with new one. Html::img is still fetching the older image not sure why (and from where??). Someone please help!

**Comment by arogachev** [comment]
In provided code you are only displaying input, there is no code for showing uploaded image. It doesn't happen automatically with calling `fileInput()`, you should write the code for this by yourself.

**P.S.** Next time please use forum for asking questions like that.

**Comment by 256cool** [comment]
Updated image exists in $imgPath but for some unknown reason it is not fetched by Html::img. When I close the browser and load the page it shows new image.

**Comment by arogachev** [comment]
The problem is not related with `Html::img()`, check image path getting logic.

**Comment by 256cool** [comment]
I am overwriting the image (path remains same) and I expect the new overwritten image to be displayed on webpage but the old image is displayed (which is already overwritten), not getting from where the old image is fetched...

**Comment by 256cool** [comment]
It was a problem of browser cache...resolved it by appending ?dummy=(random string). Thanks!
