### ISSUE TITLE
How to validate in case of empty file upload

### ISSUE THREAD

**Issue by 256cool** [yiisoft/yii2#8783]
I want to upload a file to server but need to validate before upload to check if file is validated or not, my rule section in model is as below 
```
 public function rules()
    {
        return [
            [['imageFile'], 'file', 'extensions'=>['png','jpg']],
           ];
    }
```

If I add 'skipOnEmpty' => false to my rules, client validation is performed for empty uploads but when  I choose file then too I get the validation error and I am not able to upload the file to server. What is the best way with which I can check if the file is chosen or not?

**Comment by cebe** [comment]
what is the error you get on client side?

**Comment by Faryshta** [comment]
are you instantiating the UploadedFile class on your attribute?

**Comment by 256cool** [comment]
yes I am instatiating uploaded files in controller action method as below,
$model->imageFile = UploadedFile::getInstance($model, 'imageFile');

I just want a way with which I can check if user is not uploading empty file. Currently I am using 
$_FILES['Profile']['name']['imageFile'] != '' to check the same but this does not work in Internet Explorer so looking for some other way to do the same.

**Comment by Faryshta** [comment]
@256cool how about this? http://www.yiiframework.com/doc-2.0/yii-validators-filevalidator.html#$minSize-detail

**Comment by lynicidn** [comment]
```php
            ['photo', 'string', 'max' => 255, 'isEmpty' => function (){return $this->loadFile('photo');}],
            ['photo', 'file', 'extensions' => static::PHOTO_EXTENSION, 'maxSize' => static::PHOTO_SIZE],
```
```php
public function loadFile($attribute)
    {
        if ($file = UploadedFile::getInstance($this, $attribute)) {
            $this->setAttribute($attribute, $file);
            return true;
        }
        return false;
    }
```

**Comment by 256cool** [comment]
Thanks guys!
minSize didn't work not sure what is the issue, as suggested by @lynicidn  I am cheking 
```
$model->imageFile = UploadedFile::getInstance($model, 'imageFile');
				if(isset($model->imageFile->extension))
```
