### ISSUE TITLE
Add min width for GridView column

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#8787]
Steps to reproduce problem:

- Have a column with short label, for example: `ID`.
- Add `ID` to safe attributes in search model, so this column have filter text input.
- Add another columns until horizontal scroll appears.

Now it's impossible to set mouse cursor in `ID` search input because it's too small.

It can be solved with CSS.

I guess it should be added in both basic and advanced templates.

**Comment by cebe** [comment]
can you show which css rule you would like to apply?

**Comment by lynicidn** [comment]
http://htmlbook.ru/css/min-width

only better use max-width

**Comment by cebe** [comment]
I mean the concreate rule

**Comment by YaroslavShapoval** [comment]
I think it should be something like this, no?
```css
.grid-view .filters input,
.grid-view .filters select {
    min-width: 50px;
}
```

**Comment by arogachev** [comment]
@samdark Please close it since it fixed in https://github.com/yiisoft/yii2-app-advanced/pull/67

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2-app-advanced/commit/bcb98987fff0ed8a472f6b3fcab98c27723e3e69
