### ISSUE TITLE
how can we do length validation for number?

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#8789]

**Comment by lynicidn** [comment]
use forum and read guide https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-core-validators.md#yiivalidatorsnumbervalidatorinteger-

**Comment by serhatozles** [comment]
i did. but number validation doesn't have that.

**Comment by samdark** [comment]
What do you mean by "length"? You want to validate number as string?

**Comment by lynicidn** [comment]
[quote]
[[yii\validators\NumberValidator|integer]]

[
    // checks if "age" is an integer
    ['age', 'integer'],
]

This validator checks if the input value is an integer.

    [b]max[/b]: the upper limit (inclusive) of the value. If not set, it means the validator does not check the upper limit.
    min: the lower limit (inclusive) of the value. If not set, it means the validator does not check the lower limit.
[/quote]

**Comment by serhatozles** [comment]
No, My question is not max, i know that i'm asking about length(strlen), for example for telephone number. 05551234567 This is a phone number is a number but its length could be 11. i did with "match" validation(/^[\d]{11}$/i) . but i'm just asking, is there anything for this? for number length?

**Comment by lynicidn** [comment]
math, pattern => '\d{11}'

**Comment by lynicidn** [comment]
also Number validator have pattern for number

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/validators/NumberValidator.php#L56

**Comment by cebe** [comment]
a telephone number is not a number that you should validate using the number validator. e.g. for 0555... the leading 0 will be stripped if you represent that one as an integer. You should use string or regex validator for phone numbers.
