### ISSUE TITLE
Declaration of app\components\Request::validateCsrfToken() should be compatible with yii\web\Request::validateCsrfToken($token = NULL)

### ISSUE THREAD

**Issue by keithslater** [yiisoft/yii2#8791]
After updating yii2 today with composer update I am receiving the following error:

    Declaration of app\components\Request::validateCsrfToken() should be compatible with yii\web\Request::validateCsrfToken($token = NULL)

**Comment by cebe** [comment]
this is a PHP Strict warning. You have to adjust the signature of the method you are overriding to match the original implementation. Concrete you need to add the `$token` parameter to your implementation.
