### ISSUE TITLE
access rule filter check for ajax requests

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#8794]
Currently to allow only ajax requests for an action there is the need to use an if statement like this

```php
if (!Yii::$app->request->isAjax) {
    throw new NotAllowedHttpException('This url can only be accesed by ajax');
}
// rest of your code
```

I propose to have an option on the `yii\filters\AcessRule` or `yii\filters\VerbFilter` to check if a request is ajax and use the `allow` property to determine if that action requires ajax or not.

**Comment by arogachev** [comment]
:+1: for this feature.

**Comment by unclead** [comment]
i think its a duplicate of #7823

**Comment by Faryshta** [comment]
Not a duplicate, that one is about a NEW filter, mine one is about extending functionality of an existing filter. @samdark can you open it again?

**Comment by cebe** [comment]
@Faryshta an issue is about a certain problem. your problem is the same as in #7823. if this will be a separate filter or part of an existing one is to be decided.
