### ISSUE TITLE
Please update documentation to Yii 2.0.4

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#8796]
[The documentation](http://www.yiiframework.com/doc-2.0/index.html) was last rendered on Sat, 21 Mar 2015. Yii 2.0.4 came out on May 10.

**Comment by cebe** [comment]
Will fix it. In the mean time you may use http://stuff.cebe.cc/yii2docs/ which is updated every 15 min.

**Comment by cebe** [comment]
fixed, thanks for reporting.

**Comment by nkovacs** [comment]
Thanks
