### ISSUE TITLE
links with data-method inside forms misbehaviour

### ISSUE THREAD

**Issue by selimachour** [yiisoft/yii2#8801]
My url is /product/view?id=6

I have a 
```html
    <form action="#"> ... 
    <a href="/item/delete?id=76" data-method="post" data-pjax="0" data-confirm="Are you sure ?">delete</a>
....
    </form>
```
When I click the link it goes to /product/view?id=6#  with a 400 Bad Request

This does not happen when I revert changes from 2.0.4 in yii.js 
2.0.3   "var newForm = !$form.length || action && action != '#';"  => works 
2.0.4   "var newForm = !$form.length;"  => does not work

When debugging, I watch $form.attr('action') right before the $form.trigger('submit') which is the right url BUT the trigger never actually fires the submission.

**Comment by cebe** [comment]
related to #6661

**Comment by razvanphp** [comment]
I can confirm this, it clearly worked before.

Yii 2.0.4

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/9261#issuecomment-127013433
