### ISSUE TITLE
Why does a rule execute before assignments check in yii\rbac\DbManager::checkAccessRecursive

### ISSUE THREAD

**Issue by EvgenyOrekhov** [yiisoft/yii2#8808]
Why does a rule execute before assignments check?

``` php
        if (!$this->executeRule($user, $item, $params)) {
            return false;
        }

        if (isset($assignments[$itemName]) || in_array($itemName, $this->defaultRoles)) {
            return true;
        }
```

If a role doesn't have a certain permission, I don't want the permission rule to be executed.
I expect it to be like this:

``` php
        if (isset($assignments[$itemName]) || in_array($itemName, $this->defaultRoles)) {
            return $this->executeRule($user, $item, $params);
        }
```

**Comment by incrize** [comment]
Пользователи, как правило, связаны только с ролями, т.е. в массиве ```$assignments``` только роли, поэтому правила выполняются без проверки наличия в ```$assignments```. Другой вопрос, зачем проверять цепочки разрешений, которые точно не связанны с пользователем.

Предположим, есть 2 разрешения:
Редактирование поста
Редактирование своих постов (условие по авторству)
Есть роли: Админ, Автор.

Связи (родитель, потомок):
Админ - Автор
Админ - Редактирование поста
Автор - Редактирование своих постов
Редактирование своих постов - Редактирование поста

Для проверки разрешения "Редактирование поста", есть следующие возможные цепочки:
Админ - Редактирование поста
Админ - Автор - Редактирование своих постов  - Редактирование поста

Не зависимо от текущего пользователя, будут проверяться все цепочки, пока они не закончатся либо пока не будет получен доступ.
