### ISSUE TITLE
Database exceptions are not logged when YII_DEBUG=false

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#8809]
I did notice the abovementioned behavior on Yii 2.0.3. Database exceptions are logged just fine as soon as YII_DEBUG is set to true. Other exceptions are also logged fine with either YII_DEBUG.

**Comment by cebe** [comment]
can you show some code to reproduce the issue? I am not able to reproduce it here.

**Comment by dryu** [comment]
Not sure what to show. The database (MSSQL) throws an exception on a particular query. When YII_DEBUG=true, I've got it correctly logged to a system log (FileTarget - default). But in production I have YII_DEBUG=false and the exception is not logged to a system log. I check with the production log from time to time and do not see any exception, but when reproduced on production environment, Yii2 errors out as "Database exception" though nothing is logged to a system log.

**Comment by cebe** [comment]
are you sure the log file is writeable?

**Comment by dryu** [comment]
Yes.


-A (mobile)

**Comment by dryu** [comment]
Any updates? I'm still seeing the issue in PROD environment. Once I set YII_DEBUG=true, the exception is logged, with YII_DEBUG=false it is not logged.

**Comment by dryu** [comment]
This is the exception in question if that helps:

```
2015-06-30 04:25:18 [x.x.x.x][abc][l9gpg66jnau62ss7busdoc6ur6][error][yii\db\Exception] exception 'PDOException' with message 'SQLSTATE[42S22]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'start_date_active'.' in D:\qtyii2\vendor\yiisoft\yii2\db\Command.php:825
```

**Comment by mrsombre** [comment]
@dryu can you check my ticket #9183? Maybe it's related

**Comment by dryu** [comment]
I cracked this one. The problem was in my configuration where ```yii\db*``` was set in `except` property of log to avoid filling the production log with SQL queries. Turned out this is also filtering ```yii\db\Exception``` on error level to my surprise. Though from design point of view, this is working as expected, but the docs are misleading as they mention `yii\db*` and it is arguable whether `except` should filter out messages of legit level:

```php
    /**
     * @var array list of message categories that this target is NOT interested in. Defaults to empty, meaning no uninteresting messages.
     * If this property is not empty, then any category listed here will be excluded from [[categories]].
     * You can use an asterisk at the end of a category so that the category can be used to
     * match those categories sharing the same common prefix. For example, 'yii\db\*' will match
     * categories starting with 'yii\db\', such as 'yii\db\Connection'.
     * @see categories
     */
    public $except = [];
```

I'll leave it up to @samdark to decide whether any changes to core are required. Thanks for your help guys.

**Comment by samdark** [comment]
@dryu can you provide whold logging-related config? Would be helpful.

**Comment by dryu** [comment]
```php
'log' => [
			'traceLevel' => 0,
			'targets' => [
				'file' => [
					'class' => 'yii\log\FileTarget',
					'levels' => ['error', 'warning', 'info'],
					'logVars' => [],
					'except' => [
						'yii\web\Session*'
					]
				],
			],
```
and
```php
if (YII_DEBUG) {
	$config['components']['log']['flushInterval'] = 1;
	$config['components']['log']['targets']['file']['exportInterval'] = 1;
	$config['components']['log']['targets']['file']['levels'][] = 'trace';
} else {
    $config['components']['log']['targets']['file']['except'][] = 'yii\db*';
	//$config['components']['log']['targets']['file']['except'][] = 'yii\db\Connection*';
	//$config['components']['log']['targets']['file']['except'][] = 'yii\db\Command*';
	$config['components']['log']['targets']['file']['except'][] = 'yii\web\User::login*';
}
```        
It was like that before I did the changes (commented lines).
