### ISSUE TITLE
match query in elasticsearch

### ISSUE THREAD

**Issue by nishanthpininti** [yiisoft/yii2#8813]
i am able to get match results if i provide entire string like 'name'='hains' ,but is not giving any result if i give 'name'='hai'.can any one help me.

code:

i have given validation as string to name.
$result = Customer::find()->query(["match" => ["name" => "hai"]])->all();

**Comment by alemedinam** [comment]
Have you tried with:
$result = Customer::find()->query(["like_text" => ["name" => "hai"]])->all();

**Comment by nishanthpininti** [comment]
no,it don't seem to work,its giving error

**Comment by nishanthpininti** [comment]
can any one help me to get out of this

**Comment by cebe** [comment]
how is your mapping defined in the index?
can you show an example data entry you expect to find with that query?
See also https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html
