### ISSUE TITLE
Complex relations error - pivot table to pivot table

### ISSUE THREAD

**Issue by sdlins** [yiisoft/yii2#8814]
Tryed in [Yii 2 Forum](http://www.yiiframework.com/forum/index.php/topic/64401-complex-relation-error-would-it-be-a-bug/) with no answers. I think I could be a bug.

I have a complex relation system where part of it is something like this:

``` php
// Tables (04):
// composition(1) <---> (*)composition_to_product_option(1) <---> (1)product_option(*) <---> (1)option

// composition depends on product_option that is a junction table between product and its options;
// composition_to_product_option is another junction table that in this case is between composition (normal) and product_option (junction);

// Relations inside Composition model
public function getCompositionToProductOptions()
        {
        return $this->hasMany(CompositionToProductOption::className(), ['composition_id' => 'id']);
        }

public function getProductOptions()
        {
        return $this->hasMany(ProductOption::className(), ['id' => 'product_to_option_id']);
                ->via('compositionToProductOptions');
        }

// this relation is being the problem
public function getOptions()
        {
        return $this->hasMany(Option::className(), ['id' => 'option_id']);
                ->via('productOptions');
        }
```

When I do a `$composition->productOptions` I get all related models sweetly. Everything works as expected.

BUT when running `$composition->options` I run into this:

``` php
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: common\models\Composition::product_to_option_id
```

Since `product_to_option_id` is a fk field inside the `composition_to_product_option` table pointing to `product_option table` Yii should not look for this field inside composition model. Or should?

If not, It is probably a bug.

**Comment by slinstj** [comment]
And this is my 'workaround'...

I make each model to point (i.e, to have a relation) to the next one. So, each model 'knows' how to get only 'closer' related model(s), and so for. This way and I could get the correct data using 'with()', something like:

```php
$models = Composition::find()
->with('compositionToProductOptions.productOption.option')
->all();
```

In other words, I couldnt get options directly in Composition model in this case (so, I think it is a bug) but I could get using eager loading. BUT it is not so easy 'navigate' inside the relations from Compostion to Option cause their variable multiplicity.

**Comment by cebe** [comment]
could you put together a basic app with the necessary models and a migration to reproduce it?

**Comment by slinstj** [comment]
Sure cebe, later or tomorrow I can put it here.

**Comment by slinstj** [comment]
Sorry, I still have not had enough time, but I will find a bit this week.

**Comment by cebe** [comment]
sure, no hurry :)
