### ISSUE TITLE
extract data from query in elasticsearch in yii2

### ISSUE THREAD

**Issue by nishanthpininti** [yiisoft/yii2#8816]
hi i got a query result in the form of array below:
a:1:{i:0;O:24:"frontend\models\Customer":12:{s:35:"yii\elasticsearch\ActiveRecord_id";s:2:"16";s:38:"yii\elasticsearch\ActiveRecord_score";d:1.6931472000000001;s:40:"yii\elasticsearch\ActiveRecord_version";N;s:42:"yii\elasticsearch\ActiveRecord_highlight";N;s:36:"yii\db\BaseActiveRecord_attributes";a:2:{s:7:"address";s:6:"langer";s:4:"name";s:5:"peter";}s:39:"yii\db\BaseActiveRecord_oldAttributes";a:2:{s:7:"address";s:6:"langer";s:4:"name";s:5:"peter";}s:33:"yii\db\BaseActiveRecord_related";a:0:{}s:23:"yii\base\Model_errors";N;s:27:"yii\base\Model_validators";N;s:25:"yii\base\Model_scenario";s:7:"default";s:27:"yii\base\Component_events";a:0:{}s:30:"yii\base\Component_behaviors";a:0:{}}}

how to extract name from it?

**Comment by zelenin** [comment]
it's not yii issue
http://php.net/manual/en/function.unserialize.php
