### ISSUE TITLE
ERROR:  invalid input syntax for integer: ""'

### ISSUE THREAD

**Issue by pkirill99** [yiisoft/yii2#8817]
Hi all

PostgreSQL 9.x, Yii2.0.4 php 5.6

create table:

CREATE TABLE catalogs_dates (
            id BIGSERIAL PRIMARY KEY
            , dow INTEGER
            , dom INTEGER
            , doy INTEGER
            , mon INTEGER
            , year INTEGER
            , UNIQUE (dow, dom, doy, mon, year)
            );

create models and crud by default sets

have rules:

public function rules()
    {
        return [
            [['dow', 'dom', 'doy', 'mon', 'year'], 'integer'],
            [['dow', 'dom', 'doy', 'mon', 'year'], 'unique', 'targetAttribute' => ['dow', 'dom', 'doy', 'mon', 'year'], 'message' => 'The combination of Dow, Dom, Doy, Mon and Year has already been taken.']
        ];
    }

trying create records  in CRUD ....

1) all field NULL - ok, record created. again all field NULL - ok, record created..... OK ???? where unique rule in YII? for PG index its normal, because NULL != NULL .... BUT Yii checks.....

further

2) dow = 1, and any field is NULL (and also any coombination with integer and NULL value), click "create" button ....... Database Exception – yii\db\Exception:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""
The SQL being executed was: SELECT 1 FROM "catalogs_dates" WHERE ("dow"='1') AND ("dom"='') AND ("doy"='') AND ("mon"='') AND ("year"='')

what ??? NULL === '' ??? (and also ....... integer != string ... "dow"='1' .... but this is not very important)

**Comment by samdark** [comment]
1) Unique works the same way as in PostgreSQL.
2) You should add default validators for these fields because when PHP reads post data, everything empty (or null) is an empty string.

**Comment by pkirill99** [comment]
1) maybe , i dont understand you post, but and here PostgreSQL, unique check in framework is programm... it build and process "SELECT .... " query, and analyzes result. under these conditions isn't started

in PGSQL we have conditional index:
CREATE UNIQUE INDEX ON table1 USING BTREE (column1) WHERE (column2 = NULL);
but not all conditions (logic) is possible to push in index in DBMS, for this we have validators in models


2) yes, i know, but in "box" this is not work, maybe gii to teach to add the this rule

**Comment by samdark** [comment]
2) Yes.
