### ISSUE TITLE
Showing default rating in Kartik star rating widget

### ISSUE THREAD

**Issue by 256cool** [yiisoft/yii2#8818]
Hi Guys,
 I am using kartik widget to display the rating of the user as below
```
<?php $endorsementmodel = new Endorsement;
    echo $form->field($endorsementmodel, 'sense_of_fasion')->widget(StarRating::classname(), ['pluginOptions' => ['size'=>'xs', 'showCaption'=>false, 'readonly' => true]
    ]); ?>
```
I want to show user some default rating for him, (not asking rating from others just want to display the same) How can I do that?

**Comment by Faryshta** [comment]
$endorsementmodel = new Endorsement(['sense_of_fashion' => 4]);

**Comment by 256cool** [comment]
It is still not working, it is not showing the rating (i.e. highlighted stars). I want to show user its rating in terms of star so need something which will convert integer input to highlighted stars, not sure if it is possible in the widget used above.

**Comment by Faryshta** [comment]
close this issue then please :)
