### ISSUE TITLE
Yii2 Pjax is not working, reloads the entire page

### ISSUE THREAD

**Issue by tspvivek** [yiisoft/yii2#8819]
When a file_get_contents($url) is used inside a action and when that action is loaded using Pjax, the entire page reloads.

In controllers/SiteController.php

public function actionAbout()
{
    $url = 'http://api.dar.fm/topsongs.php?q=Music&page_size=20';
    $xml = file_get_contents($url);

    Yii::$app->view->params['xmldata'] = $xml;
    return $this->render('about');
}

In layouts/main.php

      <?php Pjax::begin(); ?>
            <a href="/yiidev/web/index.php?r=site/home">Home</a> 
             <a href="/yiidev/web/index.php?r=site/about">About</a>
             <a href="/yiidev/web/index.php?r=site/contact">Contact us</a>  
      <?php Pjax::end(); ?>

For Home and Contact link, only the area between pjax begin() and end() is updated but for About link the entire page reloads.

If i remove the file_get_contents() call from from actionAbout() the page reload is not happening. I believe the problem is something related to getting contents from external url using file_get_contents()

**Comment by nkovacs** [comment]
Pjax reloads the page if the ajax call returns an error or a full document with an html tag (the pjax widget should prevent the latter). In chrome, click preserve log in the inspector's network tab, and check that the ajax call does not throw an error. Also check that it does not contain a html tag (pjax will reload the page if the response contains a html tag, because it assumes the server doesn't know that it should only render a partial response).

Btw, pjax in the layout file is going to cause you problems: #8227

**Comment by tspvivek** [comment]
Thanks for your suggestion. In inspector's network tab i found below url with GET method and xhr type. but the status is canceled. Whereas the status is 200 for others 

http://127.0.0.1:88/yiidev/fmradioz/web/index.php?r=site%2Fabout&_pjax=%23w0

**Comment by nkovacs** [comment]
Then it's probably a timeout.
You can adjust pjax's timeout: https://github.com/yiisoft/jquery-pjax#pjax-options

**Comment by tspvivek** [comment]
I added the below lines inside my body above Pjax::begin();

<script type="text/javascript">
$.pjax.defaults.timeout = 5000;
</script>

But still facing the same issue.

**Comment by nkovacs** [comment]
It's overriden by the widget it seems: http://www.yiiframework.com/doc-2.0/yii-widgets-pjax.html#$timeout-detail

**Comment by tspvivek** [comment]
I am new to YII . Please tell me how to stop timeout override. I have Nav::widget inside the Pjax.

**Comment by nkovacs** [comment]
`Pjax::begin(['timeout' => 5000 ]);`

**Comment by tspvivek** [comment]
Great!!! It works fine now !! Thank You very much

**Comment by budipratama** [comment]
I use Pjax at GridView. why refreh page when xhr failed in the console log chrome but if xhr finished made gridview refresh. any solution for this ?

**Comment by SilverFire** [comment]
It's a default behaviour. When XHR request fails, Pjax reloads the page ([source](https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L263)). Add `pjax:error` event listener on the Pjax container and call `event.preventDefault()` inside the closure to prevent page reload.

```php
<?php

use yii\widgets\Pjax;

Pjax::begin(['id' => 'myPjax']);
echo 'Some html';
Pjax::end();

$this->registerJs(<<<JS
$('#myPjax'.on('pjax:error', function (event) {
    alert('Failed to load the page');
    event.preventDefault();
});
JS
);
```

**Comment by budipratama** [comment]
Thanks a lot @SilverFire

**Comment by robert589** [comment]
when i add pjax:error, it actually fails and trigger the alert, how to solve the problem?

This is my header looks like
Request URL:http://localhost/startUp/thread/index?id=1&comment_id=1&_pjax=%23childCommentData-1
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:[::1]:80
Response Headers
view source
Connection:close
Content-Length:1387
Content-Type:text/html; charset=UTF-8
Date:Tue, 29 Dec 2015 11:11:10 GMT
Server:Apache/2.4.9 (Win64) PHP/5.5.12
X-Powered-By:PHP/5.5.12
Request Headers
view source
Accept:text/html, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:PHPSESSID=g7cll8a6um1o1824l9irs97qr5; 
Host:localhost
Referer:http://localhost/startUp/thread/index?id=1
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
X-PJAX:true
X-PJAX-Container:#childCommentData-1
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
id:1
comment_id:1
_pjax:#childCommentData-1

**Comment by SilverFire** [comment]
Please, create a separate issue.
