### ISSUE TITLE
Execute DefaultValidator first

### ISSUE THREAD

**Issue by kop** [yiisoft/yii2#8820]
Maybe I don't understant `DefaultValidator` logic correctly, but from my point of view I would like default values to be set before execution of any other validatiors, so they could validate those values.

For example, I can have some required attribute. And want to set a default value there. The only way to archive this is to use `beforeValidate()` always, because for some reason `RequiredValidator` will start before the `DefaultValidator` means validation will fail.

Currently I'm fixing this in my project with help of custom AR class with the following code:

```php
    /**
     * @inheritdoc
     */
    public function getActiveValidators($attribute = null)
    {
        $result = [];
        $validators = parent::getActiveValidators($attribute);
        foreach ($validators as $validator) {
            if ($validator instanceof DefaultValueValidator) {
                array_unshift($result, $validator);
            } else {
                array_push($result, $validator);
            }
        }

        return $result;
    }
```

However, I would like to have this in the framework.

**Comment by miraage** [comment]
Have you tried define `DefaultValidator` before `RequiredValidator`?

**Comment by kop** [comment]
@miraage, no I didn't.

Hovewer, if it works, I see that it's very risky to change that - a lot of developers could use the fact that validators are running in order they are declared.

Maybe it will be a good idea to at least add a note to [documentation](http://www.yiiframework.com/doc-2.0/guide-input-validation.html#handling-empty-inputs) mentioning this fact?

**Comment by miraage** [comment]
As for me - it is pretty obvious, that validators are executed in order they are defined.

**Comment by samdark** [comment]
We won't change it. Validators are running in the order they're specified. Changing it would be confusing. Default validator should be placed before others by developer.
