### ISSUE TITLE
attribute variable in client-side validation is not documented correctly

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#8822]
https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L303
https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md#implementing-client-side-validation-

The `attribute` variable available to client-side validation code is not the name of the attribute, it's an object. I don't think this object is documented anywhere, but it is generated by [ActiveField::getClientOptions](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L685)

**Comment by cebe** [comment]
it is somehow documented here: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L128

**Comment by nkovacs** [comment]
Yeah, but that's not on the website

**Comment by cebe** [comment]
I know I was just pointing to the current place. should be moved to some more visible place.

**Comment by nkovacs** [comment]
same issue with `whenClient` too
