### ISSUE TITLE
Field in array like $form->field($model, 'param[]') does not get model value

### ISSUE THREAD

**Issue by johnekj** [yiisoft/yii2#8826]
I am trying to create tabular form with multiple rows of inputs, like this:
echo $form->field($model, 'param1[]');
echo $form->field($model, 'param2[]');
echo $form->field($model, 'param3[]');
in each row. When done this way, rendered form doesn't show params' values.
When I use:
echo $form->field($model, 'param1');
than it properly reads $model's param1 value properly and show in the form. But than, after submit, I only get value of last input with name=param1.

**Comment by XzAeRo** [comment]
Why not create more attributes in the models and in your tables?
In the issue #3306, is discussed this approach.

Maybe you need to redefine your database structure.

**Comment by cebe** [comment]
the correct syntax would be to have the brackets before the attribute name. See also http://www.yiiframework.com/doc-2.0/guide-input-tabular-input.html
