### ISSUE TITLE
\yii\db\mysql\QueryBuilder has no addPrimaryKey() override

### ISSUE THREAD

**Issue by spikyjt** [yiisoft/yii2#8827]
The core implementation of `addPrimaryKey()` uses `ALTER TABLE ... ADD CONSTRAINT ...  PRIMARY KEY ...`, which fails for MySQL.

Version 1.1.14 had `ALTER TABLE ... ADD PRIMARY KEY ...` (in CMysqlSchema), which worked.

**Comment by samdark** [comment]
Just verified that `ADD CONSTRAINT` works for MySQL I have. Which version are you using?

**Comment by spikyjt** [comment]
With `PRIMARY` as the name of the constraint? https://dev.mysql.com/doc/refman/5.7/en/create-table.html says:
>The name of a PRIMARY KEY is always PRIMARY, which thus cannot be used as the name for any other kind of index.

I'm on version 5.5.43, but I'm not aware this behaviour has changed.

If the primary key must be called PRIMARY and you can't add a constraint called PRIMARY because it is reserved, I can't see how ADD CONSTRAINT is ever correct for adding a primary key (in MySQL).

**Comment by spikyjt** [comment]
OK, further reading suggests you can use that syntax, but the name of the index cannot be PRIMARY because it is reserved and is in fact ignored by MySQL. The index still ends up being called PRIMARY, you just can't specify that. Oh the joys of MySQL's weirdness.

So I guess the question instead is, should we be assisting users by removing the constraint name if we are creating a primary key?

If you create a migration base on an existing table that you created in mysql beforehand, copying the details exactly (which is what I did) then you will fall fowl of this vagary. My understanding is that this is specific to MySQL and does not occur in other DBs.

**Comment by SamMousa** [comment]
When writing a migration I do not know the DB that will be used right?
So it makes sense to just always ask for a primary key name even if this specific backend ignores it.

**Comment by samdark** [comment]
Closing for the reason @SamMousa specified.
