### ISSUE TITLE
Cookies, Session  And CRFS Indepent Some Domain.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2#8828]
@samdark I created an app advance template clean without extensions third, to set cookies and separate sessions and crfs indepent on the same domain I read all the documentation about it, and it works fine but when the Debub of yii2 shows:

    .htaccess root:

        # prevent directory listings
        Options -Indexes
        IndexIgnore */*

        # follow symbolic links
        Options FollowSymlinks
        RewriteEngine on

        RewriteRule ^admin(/.+)?$ /backend/web/$1 [L,PT]
        RewriteRule ^(admin)/$ /$1 [L,R=301]
        RewriteRule ^(.+)?$ /frontend/web/$1

Config Backend:

    .htaccess App Backend:

        # if a directory or a file exists, use the request directly
        # otherwise forward the request to index.php
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . index.php

    main.php:

    return [
        'id' => 'app-backend',
        'language' => 'es',
        'homeUrl' => '/',
        'basePath' => dirname(__DIR__),
        'controllerNamespace' => 'backend\controllers',
        'bootstrap' => ['debug'],
        'modules' => [],
        'components' => [
            // Configuration [User - Backend] //
            'user' => [
                'identityClass' => 'common\models\User',
                'enableAutoLogin' => true,
                'identityCookie' => [
                    'name' => '_backendIdentity',
                    'path' => '/admin',
                    'httpOnly' => true,
                ],
            ],
            // Configuration [Session - Backend] //
            'session' => [
                'name' => 'BACKENDSESSID',
                'cookieParams' => [
                    'httpOnly' => true,
                    'path' => '/admin',
                ],
            ],
        ],
        'params' => $params,
    ];

    main-local.php:

    $config = [
        'components' => [
            // Configuration [Request - Backend] //
            'request' => [
                'baseUrl' => '/admin',
                // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
                'enableCookieValidation' => true,
                'cookieValidationKey' => 'f_qIadbXufMNBJ5aDiOB_QYvJWUpNjv1',
                'enableCsrfValidation' => true,
                'csrfParam' => '_backendCSRF',
                'csrfCookie' => [
                    'httpOnly' => true,
                    'path' => '/admin',
                ],
            ],
        ],
    ];

Config Frontend:

    .htaccess App Frontend:

        # if a directory or a file exists, use the request directly
        # otherwise forward the request to index.php
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . index.php

    main.php

    return [
        'id' => 'app-frontend',
        'language' => 'es',
        'homeUrl' => '/',
        'basePath' => dirname(__DIR__),
        'bootstrap' => ['debug'],
        'controllerNamespace' => 'frontend\controllers',
        'components' => [
            // Configuration [User - Backend] //
            'user' => [
                'identityClass' => 'common\models\User',
                'enableAutoLogin' => true,
                'identityCookie' => [
                    'name' => '_frontendIdentity',
                    'path' => '/',
                    'httpOnly' => true,
                ],
            ],
            // Configuration [Session - Backend] //
            'session' => [
                'name' => 'FRONTENDSESSID',
                'cookieParams' => [
                    'httpOnly' => true,
                    'path' => '/',
                ],
            ],
        ],
        'params' => $params,
    ]

    main-local.php:

    $config = [
        'components' => [
            'request' => [
                // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
                'enableCookieValidation' => true,
                'cookieValidationKey' => 'STcA0EYgcGMX9Efzci6cjQ41illTqngh',
                'enableCsrfValidation' => true,
                'csrfParam' => '_frontendCSRF',
                'csrfCookie' => [
                    'httpOnly' => true,
                    'path' => '/',
                ],
            ],
        ],
    ];

So far so good logging smoothly, but because in the frontend shows me the data correctly and in the backend data shows me, sessions, cookies and crfs and both sessions.

Debug Frontend:

![frontendcookies](https://cloud.githubusercontent.com/assets/4957021/8209697/3a68ccee-14d8-11e5-94dc-2e8d0edc3fc1.jpg)

Debug Backend:

![backendcookies](https://cloud.githubusercontent.com/assets/4957021/8209733/78e284e2-14d8-11e5-8356-4be986eff1c1.jpg)

The truth is not whether it is a bug in the debugger, or simply can not set cookies, sessions and independent crfs within one some domain,

Thks,

**Comment by samdark** [comment]
Yes, you have to adjust your config.

**Comment by tecnologiaterabyte** [comment]
I have read and searched but I can not adjust the settings, I need to set to work correctly, can you tell me that I must adjust, or tell me some link where you can check that I should change.

thanks in advance

**Comment by tecnologiaterabyte** [comment]
hi @samdark with all due respect I think it's a bug in the debugger, I checked with:

var_dump(yii::$app->request->getCookies());

    Result Backend:

    object(yii\web\CookieCollection)#73 (2) { ["readOnly"]=> bool(true) ["_cookies":"yii\web\CookieCollection":private]=> array(2) { ["_backendIdentity"]=> object(yii\web\Cookie)#94 (7) { ["name"]=> string(16) "_backendIdentity" ["value"]=> string(46) "[1,"5mRPhH5rCmkcCUNx_EriHmAlQzkI7RsQ",2592000]" ["domain"]=> string(0) "" ["expire"]=> NULL ["path"]=> string(1) "/" ["secure"]=> bool(false) ["httpOnly"]=> bool(true) } ["_backendCSRF"]=> object(yii\web\Cookie)#96 (7) { ["name"]=> string(12) "_backendCSRF" ["value"]=> string(32) "gYZ6nsI7aHENJucwJfZK3D2eH0Wgybve" ["domain"]=> string(0) "" ["expire"]=> NULL ["path"]=> string(1) "/" ["secure"]=> bool(false) ["httpOnly"]=> bool(true) } } }

    Result Frontend:

    object(yii\web\CookieCollection)#53 (2) { ["readOnly"]=> bool(true) ["_cookies":"yii\web\CookieCollection":private]=> array(2) { ["_frontendCSRF"]=> object(yii\web\Cookie)#69 (7) { ["name"]=> string(13) "_frontendCSRF" ["value"]=> string(32) "wc70ruoctKcgMWJKllggeDzmTga5LQLQ" ["domain"]=> string(0) "" ["expire"]=> NULL ["path"]=> string(1) "/" ["secure"]=> bool(false) ["httpOnly"]=> bool(true) } ["_frontendIdentity"]=> object(yii\web\Cookie)#71 (7) { ["name"]=> string(17) "_frontendIdentity" ["value"]=> string(46) "[1,"5mRPhH5rCmkcCUNx_EriHmAlQzkI7RsQ",2592000]" ["domain"]=> string(0) "" ["expire"]=> NULL ["path"]=> string(1) "/" ["secure"]=> bool(false) ["httpOnly"]=> bool(true) } } }

I think this result is correct because the parameters independently, but the debugger does not show so may revise,

Thks in advance,

**Comment by samdark** [comment]
You have to set path for these cookies.

**Comment by tecnologiaterabyte** [comment]
Hi tested these, set path:

    - 'c:/webs/advanced/backend'
    - 'c:/webs/advanced/backend/web'
    - '/webs/advanced/backend'
    - '/webs/advanced/backend/web'
    - '/advanced/backend'
    - '/admin'
    
No working, path real absolute 'c:\webs\advanced\backend\web', windows apache 2.4.12 php 5.6.6 document root 'c:\webs', 

Which set path correct ?

Thks in advanced,

**Comment by samdark** [comment]
path in a cookie is about query path, not about file paths.

**Comment by tecnologiaterabyte** [comment]
Ok  no problem, then there is a bug in Windows settings with cookies or failing with the debugger:

Example:

Backend Config:

    'components' => [
        // Configuration [Yii2-User - Backend] //
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => [
                'name' => '_backendIdentity',
                'path' => '/admin',
             ],
        ],
        // Configuration [Session - Backend] //
        'session' => [
            'name' => 'BACKENDSESSID',
            'savePath' => sys_get_temp_dir(),
            'cookieParams' => [
                'httpOnly' => true,
                'path' => '/admin',
            ],
        ],
        // Configuration [Urls Managers - IntraCheck] //
        'urlManager' => [
            'enablePrettyUrl' => true,
            'suffix'=>'.html',
            'showScriptName' => false,
        ],
        // Configuration [Request - Backend] //
        'request' => [
            'baseUrl' => '/admin',
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'enableCookieValidation' => true,
            'cookieValidationKey' => 'f_qIadbXufMNBJ5aDiOB_QYvJWUpNjv1',
            'enableCsrfValidation' => true,
            'csrfParam' => '_backendCSRF',
            'csrfCookie' => [
                'httpOnly' => true,
                'path' => '/admin',
            ],
        ],
    ],

Url Backend: (www.advanced.tk/admin)

Path Query String:

    Show Query Path: var_dump(parse_url(yii::$app->request->getAbsoluteUrl()))

    array(3) { ["scheme"]=> string(4) "http" ["host"]=> string(15) "www.advanced.tk" ["path"]=> string(6) "/admin" } 

    Show Cookies Backend: var_dump(yii::$app->request->getCookies());

    object(yii\web\CookieCollection)#73 (2) { ["readOnly"]=> bool(true) ["_cookies":"yii\web\CookieCollection":private]=> array(2) { ["_backendCSRF"]=> object(yii\web\Cookie)#94 (7) { ["name"]=> string(12) "_backendCSRF" ["value"]=> string(32) "YqG7Slc3sqGPj4nntJvVJGJY2ONHsgc9" ["domain"]=> string(0) "" ["expire"]=> NULL ["path"]=> string(1) "/" ["secure"]=> bool(false) ["httpOnly"]=> bool(true) } ["_backendIdentity"]=> object(yii\web\Cookie)#96 (7) { ["name"]=> string(16) "_backendIdentity" ["value"]=> string(46) "[1,"5mRPhH5rCmkcCUNx_EriHmAlQzkI7RsQ",2592000]" ["domain"]=> string(0) "" ["expire"]=> NULL ["path"]=> string(1) "/" ["secure"]=> bool(false) ["httpOnly"]=> bool(true) } } } 

if you check the array of cookies you can see that the information is correct unless the path which assigns '/' by default, but only samples backend cookies.

After reviewing the debugger shows all cookies backend y frontend:

    $_COOKIE 
    Name 	                        Value
    BACKENDSESSID 	'kjfnglpv5vvh8mba01rmj400n7'
    _backendCSRF 	  '763025acc771f79b5aed8e5d407dece7b1466a1db27c6357b8fd11757bbf83f7a:2:{i:0;s:12:\"_backendCSRF\";i:1;s:32:\"YqG7Slc3sqGPj4nntJvVJGJY2ONHsgc9\";}'
    _backendIdentity 	'7340961ec8ef36dbd425f5e4619e83b7f045747dd0d1c0e0e815f450142990d7a:2:{i:0;s:16:\"_backendIdentity\";i:1;s:46:\"[1,\"5mRPhH5rCmkcCUNx_EriHmAlQzkI7RsQ\",2592000]\";}'
    FRONTENDSESSID 	'08mto9v2fu0g643ihgl1r216m2'
    _frontendCSRF 	'781900472e43619f7a486bc4e9674cae784dff138d877fa07ca8c3aa30417546a:2:{i:0;s:13:\"_frontendCSRF\";i:1;s:32:\"lcxw5-78c2SuCU3vThkQvb6nijJP_qQ_\";}'
    _frontendIdentity 	'80efdfee9cebe06d1230475b5adf66bf89e4ad76b0a9147d2d77b1d2917559d2a:2: {i:0;s:17:\"_frontendIdentity\";i:1;s:46:\"[1,\"5mRPhH5rCmkcCUNx_EriHmAlQzkI7RsQ\",2592000]\";}'

Mozilla Firebug Show Route Correct:

![cookies_yii2](https://cloud.githubusercontent.com/assets/4957021/8230717/9c65b830-158c-11e5-8b91-472d48690e3b.jpg)

actually I'm going crazy jejejejeje, I think it's a bug,

Thanks in advance

**Comment by kidol** [comment]
Path `/` means valid for all paths (like `/admin`). So yes, you see frontend cookies in backend uri, but why is this a problem?

**Comment by tecnologiaterabyte** [comment]
thanks for responding @kidol, seeing the debug I note that the cookie is made up of backend and frontend that's right, I thought the expected behavior should be to have separate cookies.

![cookie_request](https://cloud.githubusercontent.com/assets/4957021/8232162/44de92c0-1597-11e5-9efa-802ee5f47a88.jpg)

**Comment by samdark** [comment]
Nah, that's all right as long as names aren't the same.

**Comment by tecnologiaterabyte** [comment]
Thks :+1:
