### ISSUE TITLE
Use SQL ANSI as Query Builder implementation

### ISSUE THREAD

**Issue by vbsessa** [yiisoft/yii2#8830]
I'm implementing a DB2 extension and i'm unable to do a 'LIMIT' and 'OFFSET' statement because DB2 uses the SQL:98 syntax through ROW_NUMBER inside the 'WHERE' clause.

As a workaround, DB2 can be configurated to be compatible with Mysql and Postgresql setting a registry var called DB_COMPATIBILITY_VECTOR=MYS, but sometimes, in real situations, it's out of developers range.

I wonder if would not be better do all DB operations as SQL ANSI (rev 2008 or 2011) and than make dbsm specificities.

**Comment by samdark** [comment]
Probably yes. What do you propose exactly?

**Comment by vbsessa** [comment]
What i mean is whether the resulting sql generated by the "parent class" QueryBuilder is ANSI compilant or not. As i can see, some widgets like pagination rely on `LIMIT` clause in a non-standard way, once in sql08 it's defined as `FETCH FIRST n ROWS ONLY`.

**Comment by samdark** [comment]
Yes. I'm aware of it but it's not practical since `FETCH FIRST` doesn't allow you to specify offset and isn't actually supported by many commonly used DBMS:

```
SELECT * FROM T LIMIT 10 OFFSET 20  Netezza, MySQL, PostgreSQL (also supports the standard, since version 8.4), SQLite, HSQLDB, H2
SELECT * from T WHERE ROWNUM <= 10  Oracle (also supports the standard, since Oracle8i)
SELECT FIRST 10 * from T    Ingres
SELECT FIRST 10 * FROM T order by a Informix
SELECT SKIP 20 FIRST 10 * FROM T order by c, d  Informix (row numbers are filtered after order by is evaluated. SKIP clause was introduced in a v10.00.xC4 fixpack)
SELECT TOP 10 * FROM T  MS SQL Server, Sybase ASE, MS Access
SELECT TOP 10 START AT 20 * FROM T  Sybase SQL Anywhere (also supports the standard, since version 9.0.1)
SELECT FIRST 10 SKIP 20 * FROM T    Interbase, Firebird
SELECT * FROM T ROWS 20 TO 30   Firebird (since version 2.1)    
SELECT * FROM T
WHERE ID_T > 10 FETCH FIRST 10 ROWS ONLY    DB2
SELECT * FROM T
WHERE ID_T > 20 FETCH FIRST 10 ROWS ONLY    DB2 (new rows are filtered after comparing with key column of table T)
```
