### ISSUE TITLE
Yii validation error 

### ISSUE THREAD

**Issue by ajayvembu90** [yiisoft/yii2#8832]
Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Invalid validation rule: a rule must specify both attribute names and validator type.' 

Below is my Model class:

class FilterItemAttr extends ActiveRecord{
	
	public static function tableName()
	{
		return 'filter';
	}
	
	public function rules(){
		return [
				'filter_name' => 'required',
				'filter_name' => 'trim'
		];
	}
	
	public function getFilters($sub_category){
		
		$sub_category_id = SubCategory::find()->select(['sub_category_id'])->where(['sub_category_name'=>$sub_category])->one();
		
		$filters = FilterItemAttr::find()->select(['filter_name'])->where([
				'sub_category_id' => $sub_category_id->sub_category_id
		])->all();
		
		return $filters;
	}
	
	
}

Below in my controller's action method:

public function actionItemsdisplay($sub_category){
		
		$filterItemAttrModel = new FilterItemAttr();
		$itemModel = new Item();
		
		$filtersItemAttr = $filterItemAttrModel->getFilters($sub_category);
		
		$filtersItemAttrArray=array();
		
		foreach($filtersItemAttr as $item){
			$filtersItemAttrArray[$item->filter_name] = $item->filter_name;
		}
		
		if ($filterItemAttrModel->load(Yii::$app->request->post()) && $filterItemAttrModel->validate()){
			$itemsGeneral = $itemModel->getOrderedItems($sub_category,$filterItemAttrModel->filter_name);
			
			return $this->render('itemsdisplay',[
					'sub_category'=>$sub_category,
					'filtersItemAttrArray'=>$filtersItemAttrArray,
					'itemsGeneral' =>$itemsGeneral,
					'filterItemAttrModel'=> $filterItemAttrModel
			]);
		}
	    
		$itemsGeneral = $itemModel->getAllItems($sub_category);
		
		return $this->render('itemsdisplay',[
				'sub_category'=>$sub_category,
				'filtersItemAttrArray'=>$filtersItemAttrArray,
				'itemsGeneral' =>$itemsGeneral,
				'filterItemAttrModel'=> $filterItemAttrModel 
		]);
	}

**Comment by zinzinday** [comment]
Your invalid config 
```php
public function rules(){
    return [
           [ 'filter_name','required'],
           ['filter_name', 'trim']
    ];
}
```

**Comment by ajayvembu90** [comment]
what is invalid? - could you please elaborate?

I have even tried giving the validator type as 'string', but still throwing the error.

**Comment by ajayvembu90** [comment]
I have one more question,

Will the model class members not be populated if I don't invoke my validate() method?
