### ISSUE TITLE
How to access direct url without login that is making exception for particular url?

### ISSUE THREAD

**Issue by jgrasta** [yiisoft/yii2#8836]
in main.php
 'as beforeRequest' => [
   'class' => 'yii\filters\AccessControl',
   'rules' => [
        [
            'actions' => ['login', 'error'],
            'allow' => true,
        ],
       [

            'allow' => true,
            'roles' => ['@'],
       ],
  ],
],

this code restrict me to access any url without login....but reset password url should not get restricted ..how can i make exception for that url(s).

**Comment by klimov-paul** [comment]
@jgrasta, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
