### ISSUE TITLE
Yii添加service层，怎么更好的配合MVC

### ISSUE THREAD

**Issue by Liv1020** [yiisoft/yii2#8838]
Yii的view层物件需要model，但是项目需求添加service一层。怎么写比较好？

**Comment by lichunqiang** [comment]
sevice层是干嘛的

**Comment by zuoRambo** [comment]
经历一些项目之后 现在我也觉得需要有个service层 高于model 可被任意controller调用 这样现有业务逻辑剥离一个api出来 就很简单了

**Comment by lichunqiang** [comment]
不用service层也能实现你所说的

**Comment by samdark** [comment]
Please use forums for discussions.
