### ISSUE TITLE
Validation rules {rules()-method} for dynamically added class properties

### ISSUE THREAD

**Issue by ajayvembu90** [yiisoft/yii2#8845]
As per the Yii2 docs the validation rules can be applied either to the implicit properties (table fields) or to the userDefined properties. 

Is there a way to create validation rules for the properties which are dynamically added to the model class?

**Comment by klimov-paul** [comment]
@ajayvembu90, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
