### ISSUE TITLE
registerMetaTag doesn't overwrite

### ISSUE THREAD

**Issue by CyanoFresh** [yiisoft/yii2#8847]
Hello. I have this code in my layout file:
```
$this->registerMetaTag([
    'name' => 'description',
    'property' => 'og:description',
    'content' => '...',
], 'description');
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => '...',
], 'keywords');
```
and I have this in the child view:
```
$this->registerMetaTag([
    'name' => 'description',
    'property' => 'og:description',
    'content' => 'another',
], 'description');
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => 'another',
], 'keywords');
```
So it shows meta tags from layout, not from child view. Meta tags with the same key.

**Comment by klimov-paul** [comment]
This is expected: layout file is rendered after view file, so meta tags setup at layour overrides the ones setup in view file.

**Comment by CyanoFresh** [comment]
Is there any way to override layout tags from the view?

**Comment by klimov-paul** [comment]
No. you should setup default met tags somewhere else, like `View::beforeRender()`

**Comment by CyanoFresh** [comment]
Thanks for answering

**Comment by valerijv** [comment]
in your layout file you could check if meta tag is already set or not like this:
if ( !isset($this->metaTags['description']) ) {
    $this->registerMetaTag([
        'name' => 'description',
        'property' => 'og:description',
        'content' => '...',
    ], 'description');
}
if ( !isset($this->metaTags['keywords']) ) {
    $this->registerMetaTag([
        'name' => 'keywords',
        'content' => '...',
    ], 'keywords');
}
