### ISSUE TITLE
dropDownList bug

### ISSUE THREAD

**Issue by TvitiDev** [yiisoft/yii2#8848]
hello. I found bug in dropDownList( $items, $options = [] ). In '$options' i can write 'options', for example 
'options' => [
'value1' => ['disabled' => true],
'value2' => ['label' => 'value 2'],
]
If i want choose default "selected", i write 'value1' => ['selected' => true], but this code not work. If i add space after 'selected' this code begin work 'value1' => ['selected ' => true]
My opinion - this bug. Please correct

Yii2 2.0.4

**Comment by pana1990** [comment]
@TvitiDev i wrote a test for this issue, can you check it again?

**Comment by TvitiDev** [comment]
Sorry, I do not know how to do it. I tried, but I have a fatal error due to lack of classes. I  will have reading the documentation on the testing and i trying again later.
PS II want to emphasize that the problem is only the options 'selected'

**Comment by pana1990** [comment]
can you show me full code? please.

I think that your problem is config option.

**Comment by TvitiDev** [comment]
This is view http://pastebin.com/Bv374TU8 (trouble in 206 line. If i remove space after selected - code not work)
This is model  http://pastebin.com/dKLDghe0
This is controller http://pastebin.com/TGTT8kTA

**Comment by pana1990** [comment]
oh ok, sorry for not understand you at first.

When you using dropdownlist with a model it selected the value from model's attribute by default, if you want to another select option you should use Html::dropdowlist instead.

You may suggest add this option how improvement.

**Comment by TvitiDev** [comment]
sorry for my bad English. I'll try again.
In dropDownList can set selected item, but if write 
[ 'options' => [ 'value' => ['selected' => true]],] code not work. If i add space after word "selected" code begin work. [ 'options' => [ 'value' => ['selected ' => true]],] 
The difference in the last symbol 'selected_'

**Comment by TvitiDev** [comment]
In general. If inside the parentheses after the word selected to add a space, then the code works. Logically, this space should not be

**Comment by pana1990** [comment]
you see this http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#activeListBox()-detail

activeListBox not support 'selected' option, this behavior is strange when you add a space.

**Comment by cebe** [comment]
'selected' does not work because it is overwritten by the method using the models attribute value here:
https://github.com/yiisoft/yii2/blob/0c2bde528f60eaaf52f03ef8be7fb9644484dfb5/framework/helpers/BaseHtml.php#L1701

'select ' works because it is a boolean attribute and just rendered out because it is not overrridden.
