### ISSUE TITLE
Ajax Validation - field->error(['encode' => false]) not working

### ISSUE THREAD

**Issue by balajiqandco** [yiisoft/yii2#8853]
I'm trying to disable the encoding the error messages on a dropDownList using the below code,
```php
$form->field($model, 'page')
->dropDownList([1=>'Home', 2=>'Services', ['prompt' => 'Please select...'])
->error(['encode' => false]) 

```
It works fine when the page is submitted via $_POST through a page refresh. But it fails when I set enableAjaxValidation => true.

The error message displayed during both methods are,
1. With Ajax validation - 'Page already exists. &lt;a href="/admin/page/4/update"&gt;Click here&lt;/a&gt; to edit it.'
2. No Ajax validation - 'Page already exists. Click here to edit it.'

Can u please fix this bug?

**Comment by dynasource** [comment]
you should use $errorOptions['encode'] https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L788
