### ISSUE TITLE
Where to place Message-config file for all applications in advanced template?

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8858]
Trying to insert translations from all applications (console, frontend, backend) into database

currently my config look like this and located in one of applications

https://gist.github.com/anonymous/872c18a83f86b2bce5bd

Where to place message-config file if I want to insert messages into database for all applications in advanced template?

**Comment by samdark** [comment]
The location of the config does not matter. What matters is sourcePath. If you'll specify it as root of your project, message command will check all apps.

**Comment by turalsprofile** [comment]
Ok let's say I place message-config in root directory, first problem - it will include vendor directory also to scanning process. Second, where will it get the $db configuration if the file will be in the root directory?

**Comment by samdark** [comment]
Add vendor to `except` section. It will always get config from console since it's run from console.

**Comment by turalsprofile** [comment]
Thank you very much!
