### ISSUE TITLE
Message and job queue

### ISSUE THREAD

**Issue by mongosoft** [yiisoft/yii2#8859]
I want to revive discussion about messages and jobs queues.
This thing is very useful, and many developers sooner or later will realise this task.

That's what I think about the implementation of the queue:

1) First of all, realize the interface to the message queue. The base component of message queues must be able to push-pop a simple text message. Bacause job queue it's a particular case of the implementation of the message queue.
2) For the queue of tasks to be performed by some code - use a component with higher abstraction. Such us ActiveJob in ROR, for example.

The first part includes implementing the following queues:

- MemoryQueue
- DbQueue
- SysVQueue
- IronQueue
- RedisQueue
- MongoQueue
- BeanstalkdQueue
- AmazonSqsQueue
- RabbitQueue
- etc.

What do you think about this?

**Comment by klimov-paul** [comment]
Duplicates #492
