### ISSUE TITLE
Timestamp behaviour issue

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8860]
Take a look at the configuration code below. I want to change/override only 'createdAtAttribute',
 'updatedAtAttribute'. Why on earth do I have to write extra line for 'value', if I want to keep it as default? 

I checked without this line, it doesn't insert to db anything.
```
public function behaviors()
{
    return [
        [
            'class' => TimestampBehavior::className(),
            'createdAtAttribute' => 'create_time',
            'updatedAtAttribute' => 'update_time',
            'value' => new Expression('NOW()'),
        ],
    ];
}
```

**Comment by samdark** [comment]
It's documented:

> If not set, it will use the value of `time()` to set the attributes.

**Comment by turalsprofile** [comment]
I tried without, it set for both fields 0000 .. that's why wrote this as bug

**Comment by turalsprofile** [comment]
Please check my issue once more.

**Comment by cebe** [comment]
This is because a Unix timestamp does not match your schema definition. Looks like you have DATETIME type declared for your column. The default assumption is integer which works the same for all DBMS.

**Comment by turalsprofile** [comment]
it's timestamp datatype

**Comment by samdark** [comment]
timestamp in MySQL is not the same as timestamp in PHP.
