### ISSUE TITLE
Model::loadMultiple($models) is false?

### ISSUE THREAD

**Issue by uiexp** [yiisoft/yii2#8861]
$name = new NameForm();
$password = new PasswordForm();

        if (Model::loadMultiple([$name, $password], Yii::$app->request->post())) {
            if ($name->validate() && $password->validate()) {
                
            }
        }

loadMultiple method is error by 843 line

**Comment by uiexp** [comment]
formName is first fixed, how can read secend?

**Comment by uiexp** [comment]
foreach ($models as $i => $model) {
            /* @var $model Model */
            if ($formName == '') {
                if (!empty($data[$i])) {
                    $model->load($data[$i], '');
                    $success = true;
                }
            } elseif (!empty($data[$model->formName])) {
                $model->load($data[$model->formName], '');
                $success = true;
            }
        }

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L820

**Comment by uiexp** [comment]
yii2 document is Mislead

clearly:
if ($name->load(Yii::$app->request->post()) && $password->load(Yii::$app->request->post())) {
            if ($name->validate() && $password->validate()) {

            }
        }

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
