### ISSUE TITLE
Then exception thrown and caught, no code is run after $app->run()

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#8865]
Expected:

If exception is caught, the execution is continued, `$app->run()` in `index.php` returns, any code after it is executed.

Observed:

If exception is thrown, caught and displayed (this time it's `yii\web\UnauthorizedHttpException`, but I think problem is total), `$app->run()` seemingly never returns and code behind it is never run.

Reason:
I use [phacility/xhprof](https://github.com/phacility/xhprof) not only to improve performance in normal execution but to investigate execution path in case of error, so having it OK in error is crucial for me. I don't want to explode my mind between xhprof and xdebug (it works indepenndent of PHP code and always saves profile).

**Comment by cebe** [comment]
if an exception is thrown that is not cought anywhere inside of the application this will result in the error handling mechanism to turn in and handle it. no code of the original php script can be continued after that. if you need to run some code after this situation you have to put it into a shutdown function.
