### ISSUE TITLE
AssetController Compress is generating config file with double backslashes

### ISSUE THREAD

**Issue by germanliu** [yiisoft/yii2#8871]
Hi, 
When yii asset assets.php config/assets-prod.php is ran, the generated file assets-prod.php has double back slashes, for example in: 

```
'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
```

Any ideas?

Thanks

**Comment by klimov-paul** [comment]
@germanliu, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by germanliu** [comment]
@klimov-paul thanks! I think the auto generated code with double back slashes could be a bug.

**Comment by klimov-paul** [comment]
Try to read something like this:
http://www.homeandlearn.co.uk/php/php7p7.html

**Comment by germanliu** [comment]
Thanks Paul, I understand what an escaping character is, but don't understand why the generated code has it. Anyway, it works!
