### ISSUE TITLE
FileExistValidator and ClassExistValidator

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#8872]
is it possible to have at the core an validator that checks if a file exists on the system and another to check if a class exists on the project?

**Comment by Alex-Code** [comment]
These seem a bit specific to be added to the core.
Why can't you make your own?

**Comment by klimov-paul** [comment]
Validators are ment to control user input. It not a common practice to allow user specify program class names. So it is not belong to the core.

**Comment by alexandernst** [comment]
I agree with @klimov-paul about the class checking. Anyways, I can see some usage cases about the file validation. Maybe open another issue @Faryshta if @klimov-paul thinks file validation could be discussed further?

**Comment by klimov-paul** [comment]
> file validation could be discussed further?

I don't think so. reason is the same: user should not know about files existing on the server - it is possible security breach.

**Comment by alexandernst** [comment]
@klimov-paul Think about a file check validation in a user's profile page, where he/she is allowed to upload documents/photos. The file validation check would check files only in that user's profile folder, thus no security issues would be involved.

**Comment by Faryshta** [comment]
@klimov-paul lets say i have a site where the user can upload images. Then I let that user to choose among the images that he has uploaded one to be his profile avatar.

I won't show to the user *all* the images on my server, just the ones he has uploaded but I do need to validate that the file he choosed to be the avatar is on my server.

**Comment by Alex-Code** [comment]
How are you going to let a user select an image?
If you're building a list of images they can select then won't you have already checked that they exist?

**Comment by alexandernst** [comment]
@Alex-Code I suspect @Faryshta is having some trouble explaining the proposed modification in Yii. The duplicated file validation would happen when the user is uploading pictures to his profile (in order to prevent duplicated photos).

**Comment by Faryshta** [comment]
@alexandernst not my original idea but that seems a very good case use that i hadn't considered.

@Alex-Code even if i show them a list on the front end i have to validate on the backend the information on save.
