### ISSUE TITLE
Should Yii::t be smarter?

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#8874]
Let's say I have this:

```
class Test {
    const TXT = "This is a test";
}

Yii::T("app", Test::TXT);
```

Yii is unable to properly translate that text, but there are no technical issues that I can see that prevent it from doing so. Should Yii be able to analyze texts in a more clever way?

**Comment by klimov-paul** [comment]
Analyzing of the constants requires loading of class, which defines it and avaulating code. This may cause memory overflow during `MessageController::extract()` execution as well as class naming conflicts and so on.
Thus such improvement is too risky.

**Comment by alexandernst** [comment]
@klimov-paul I have been thinking about how to work around that limitation, but I can't find any solution.

Please check this simple example:

```php
class MetricUnit {
    const SIZE = [
        "values" => 0,
        "text" => "Size"
    ];

    //Weight
    //Height
}

echo Yii::t("app", MetricUnit::SIZE["text"]);
```

It doesn't make sense to store the text/description of each metric unit in a database (as it is a single word and fetching it from a database would be an overkill) and it doesn't make sense to do it like `echo Yii::t("app", "Size");` because that same text could appear in different views, and changing the text would require to change each and every view.

I think `Yii::t` should be able to "read" const values somehow.

**Comment by samdark** [comment]
You can strore translations in po or php files.

**Comment by samdark** [comment]
Yii::t doesn't execute any code so it's unlikely.

**Comment by alexandernst** [comment]
That is why I opened this issue in the first place. Maybe Yii should be able to get static / const values. Can you suggest how else would I achieve   what I explained in my last comment?

**Comment by samdark** [comment]
You can:

1. Store translations in files so there will be no DB hit.
2. Instead of real messages use fake keys such as `menu.login` and a fake `sourceLanguage` such as `keys`. This way you'll be able to change translation files only w/o editing code.

**Comment by alexandernst** [comment]
@samdark That still doesn't fix my problem. Ok, let me try to explain it better.

Let's say I have a list (in a GridView) of people. Each person has a state (integer in the database), and that state can be one of a few strings, for example: `Happy`, `Sad`, `Shy`, etc.

Now let's say I have a `Person` class such as:

    class Person {
        const SHY = 0;
        const HAPPY = 1;
        const SAD = 2;
        const TXT = [
            "Shy",
            "Happy",
            "Sad"
        ];
    }

Now let's say I have a column that looks like this:

	[
		'value' => function($model){
			return Yii::t("app", Person::TXT[$model->state]); // <--- won't work
		},
		'label' => Yii::t("app/admin", "Metric units")
	]

Because currently `Yii::t` can't "see" const values, this simple example would be turned into a hacky solution that involves (as suggested) fake keys and fake sourceLanguage.

Could you also, just for the sake of comparing both ways, post some code about how would your solution look like?

**Comment by cebe** [comment]
just to make sure I get you right, you are acutally talking about the message controller, are you? because Yii::t itself will work with that code and translate the string.

**Comment by alexandernst** [comment]
@cebe I'm talking about the fact that when running `./yii message config/i18n.php` Yii won't write down `Shy`, `Happy` and `Sad` in my `app/admin.php` translations file.

**Comment by cebe** [comment]
the common solution to that is to write a switch statement for the different values like it is done e.g. here: https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L1051-L1058

**Comment by alexandernst** [comment]
@cebe I'm not really sure I understand what are you suggesting. Where would I place that switch? In my `Person` class so I can trick Yii to translate those strings?

**Comment by cebe** [comment]
Yii can already translate them, you can add them manually to the file. This is to allow the MessageCommand to find it for you automatically

**Comment by alexandernst** [comment]
Oh, I see what you mean. Reasonable enough, I'll do it that way. But still, it would be nice if Yii could actually understand what static/const values are and write them down in the i18n files automatically.

**Comment by samdark** [comment]
It probably would never be able to.

In order to understand constants the code should be executed. That means Yii should somehow execute all possible code in correct manner in order to get all possible variations of translation strings.

I can see how to make it trigger adding a new message to list of strings if it's not translated but I can't see any way to make Yii itself to execute every line of itself and the app in correct manner.

**Comment by alexandernst** [comment]
@samdark I understand why `Yii::t("app", Class::TXT[$my_var_index]);` won't work, but I can't really understand why `Yii::t("app", Class::PLAIN_TXT);` can't.
That is not a code that should be evaluated/executed at runtime. `Class::PLAIN_TXT` is a sinple const that can be fetched without evaluating anything else.

**Comment by lynicidn** [comment]
see logs
http://sandbox.onlinephpfunctions.com/code/3d63572218f6e8dd1f4c1ba3585b570b3068f622

**Comment by alexandernst** [comment]
@lynicidn I don't see how this fits my last comment.

**Comment by lynicidn** [comment]
<br />
<b>Fatal error</b>:  Arrays are not allowed in class constants in <b>[...][...]</b> on line <b>11</b><br />

**Comment by alexandernst** [comment]
@lynicidn In my example `Class::PLAIN_TXT = "foo bar"`, not `Class::PLAIN_TXT = ["foo", "bar"]`.

**Comment by samdark** [comment]
@alexandernst yes, that's doable but you may have constants elsewhere in other files that are to be scanned later so that will cover just one extremely specific case and it's not that easy to do technically.
