### ISSUE TITLE
$this->id is the incorrect ID

### ISSUE THREAD

**Issue by synackSA** [yiisoft/yii2#8878]
So a problem has recently popped up for me when I have logging to the DB enabled. If I do a ActiveRecord save() and then reference the $id for that record afterwards, it has the wrong id. For instance with the following code:

    public function saveStudent($first_name, $last_name, $gender)
    {
        $student = new Student();
        $student->first_name = $first_name;
        $student->last_name = $last_name;
        $student->gender = $gender;

        Yii::info("Saving student: {$student->first_name} {$student->last_name}");
        $student->save();

        return $student->id;
    }

Uses the following class:

    class Student extends \yii\db\ActiveRecord 
    {

        /* NORMAL CODE HERE */

        public class afterSave($insert, $changedAttributes)
        {
            parent::afterSave($insert, $changedAttributes);

            Class::assignClass($this->id);
        }

    }

The ID that is passed into `Class::assignClass()` is not the ID for the student record, but rather the ID for the record for the log entry that was written to the log table in the DB for the line `Yii::info("Saving student: {$student->first_name} {$student->last_name}");`. This doesn't always happen, but it is happening and it's very annoying. To be clear, the `Student` record is being saved into the DB, as I checked to make sure that the record was there. Here is my config for the writing of the logs to the DB.

                   [
                    'class' => 'yii\log\DbTarget',
                    'exportInterval' => 10,
                    'levels' => ['error', 'warning', 'info'],
                    'logVars' => ['_COOKIE',],
                    'categories' => [
                        'sync',
                        'treb',
                        'sync_cleanup',
                        'application'
                    ],

~~I've written the following code into my `afterSave()` of one of my classes, only to have it happen elsewhere. I don't want to have to write this code all over.~~ Ignore this, the code doesn't work as intended.

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        $this->refresh();

        $lastID = $this->db->getLastInsertID();
        if ($lastID != $this->id) {
            Yii::warning("ERROR: Record ID ({$this->id}) is not equal to last inserted ID ($lastID), reassigning");
            $this->id = $lastID;
        }
    }

Please note that the `$this->refresh()` is not fixing the issue.

**Comment by cebe** [comment]
which version of yii are you using?

**Comment by synackSA** [comment]
2.0.4

**Comment by klimov-paul** [comment]
This issue happens because `insert` SQL statement is logged via `DbTarget`, which performs own `insert` SQL statement, so when it comes to call of `getLastInsertID()` it returns last inserted ID for the log table instead of one used in ActiveRecord.

I can't see any way to fix this. You should either don't apply `DbTarget` for database operations logging or setup `exportInterval` in the way logs will be written at the application end.

Also note that databases, which uses `insert...returning` statement, like Postgres or Oracle, are not affected by such behavior.
