### ISSUE TITLE
一系列问题

### ISSUE THREAD

**Issue by JackZForDream** [yiisoft/yii2#8879]
## 隐藏hint自动
```php
public function attributeHints(){
//这里我定义了一些字段必要说明
}
```
但是非常不幸的是，如果，表单一旦验证错误，天啊，那个error错误和hint提示都是会一起显示的
，很明显我要去除那个hint，填正确又恢复嘛?看了 fieldConfig我发觉解决有点麻烦，
其实就是要解决
```
'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
```
动态增加删除的问题？（难道强哥认为这样子很漂亮）
<hr/>
## 大家是如何对每次成功做某个action之后要做的事情的?比如更新后提示操作成功，删除提示修改成功。
以下是我的解决方案
- 像tp一样搞个跳转页面，（用户体验不好，直接踢）
- 使用yii\bootstrap\Alert + Yii::$app->session->setFlash('alert',$msg);
  (这种问题就是Alert分散在各个需要的页面，dirty code啊)
- 还有一种就是绑定事件了（但是我想不出具体怎么做，觉得这才是王道，难道是init中on，然后具体操作中trigger，这和第二步好       像没什么差别），
<hr/>

## 大家是如何解决url上错误的参数的？
- 我的做法是在控制器中抛出 HttpNotFoundException;
大家有没有更好的方法，另外我感觉我老是需要判断url的参数是否存在，这种代码分散在我的各个模型层中，有什么
好的解决方法吗？
<hr/>

## Yii::$app->user->identity->name这种代码分散在视图中 有什么更好的实践吗？
<hr/>

## query object的一个问题
```
$customers = Customer::find()
    ->indexBy('id')
    ->all();
```
不懂啊；debug了一下，数据好像没差别，大家能说说差别吗？

**Comment by hiscaler** [comment]
1. 既然是出错了，出现正确的输入提示这没有什么不妥吧
2. 使用 Flash
3. public function actionTest($arg1, $arg2) 这样不可以吗？
4. 很少取 name，所以没感觉-_-#，如果只是 id，你可以 Yii::$app->user->id
5. ？

**Comment by JackZForDream** [comment]
@hiscaler 
1 正确的提示是在还没有发生错误的时候出现的，但是error是发生错误的时候出现的。（两者的内容某种程度有些重复，好吧我承认我没有使用hint，我后来思考作者设计这个应该是二选一的考虑）
3 比如id=5的用户是存在的，但id=6的用户是不存在的，此时会报non object，所以我这里用了
   httpnotfoundException，但是觉得不干净
5 其实我想问 由id索引检索出来的内容有什么不一样？

**Comment by hiscaler** [comment]
@JackZForDream 
3. 还是没明白-_-#
5. indexBy('id') 表示以 id 为数组的键返回

**Comment by lichunqiang** [comment]
It's been too long, should be closed now
