### ISSUE TITLE
Bad Request (#400) Unable to verify your data submission.

### ISSUE THREAD

**Issue by AlaFalaki** [yiisoft/yii2#8885]
Hi,
i have a project, it works on shop.local and shop.local/admin, i used the tutorial on sharing hosts to make this happen.
now i wanted to deploy this project in my work office server so that my team mates could see and work with it.
i just copied/pasted the whole thing, updated the mysql database.
everything works fine, except two things:
1- when i want to use my login form, i get "Unable to verify your data submission."
and i have csrf in my head layout.
2- my yii debugging toolbar doesn't show up anymore.

what did i do wrong ?

**Comment by arogachev** [comment]
@AlaFalaki Use official forum to ask such questions.
