### ISSUE TITLE
Weird formatter asDatetime behavior 

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#8887]
```php
echo date_default_timezone_get(); // Europe/Zurich
echo Yii::$app->formatter->asDatetime('26.06.2015 02:10'); // 26.06.2015 04:10
```

The Problem is, that if a string is given it uses the `defaultTimeZone` field in the `normalizeDatetimeValue` method, which is set as default to `UTC`. Is this an expected behavior?

My current workaround is to set the `defaultTimeZone` explicit to `date_default_timezone_get()` in the config-file.
```php
'formatter' => [
	'class' => 'yii\i18n\Formatter',
	'defaultTimeZone' => date_default_timezone_get(),
],
```

**Comment by cebe** [comment]
this is expected and also documented:
https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L77-L78
https://github.com/yiisoft/yii2/blob/master/docs/guide/output-formatting.md#time-zones-
