### ISSUE TITLE
why does Container::mergeParams not a full merge?

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#8888]
I've specified some default parameters with `\Yii::$container->set()`, which are not on the first hierarchy.

```php
\Yii::$container->set('app\models\Test', [
	'options' => [
		'class' => 'test'
	]
]);
$test = Yii::createObject('app\models\Test', [
	'options' => [
		'id' => 'test'
	]
]);
echo $test->class; // NULL
echo $test->id; // test
```
The `class` option just gets overwritten, because the merge is not recursive. Does this have a special reason for not getting merged recursively?

**Comment by cebe** [comment]
recursive merging can cause various unexpected problems, when a property contains a non associative array you most probabily do not want to end up with all values in it but only the set of the second one.

**Comment by thejahweh** [comment]
Is there a way to do it explicitly?

**Comment by cebe** [comment]
not as far as I know.

**Comment by thejahweh** [comment]
Are there plans to support this?
If not, then it should be documented as an expected behavior.

**Comment by klimov-paul** [comment]
Duplicates #4154

**Comment by thejahweh** [comment]
#6922
