### ISSUE TITLE
i18n Google Translate

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8890]
I'm currently using Yii2 inbuilt i18n with database. And extracting using following command: 

```
./yii message/extract messages-config.php
```

And then using CRUD to add, edit translations.

Currently I'm working on huge project which has plenty of basic words to be translated. They can be easily translated by Google so that only few amount of translation will be left for human translation. 

I wonder, Is there any workaround to extract messages into database and on the fly translate them using Google Translate?

**Comment by samdark** [comment]
Nothing like that built-in. I personally would not recommend using Google translate for any sort of automated translation.

**Comment by turalsprofile** [comment]
What about extending message extract's functionality? How can I override current message-extract's some or all functions?

**Comment by samdark** [comment]
Extend from MessageController, then add it to console `controllerMap`. You probably will override `extractMessages` to achieve what you want.
