### ISSUE TITLE
how to check current user is the user has logind with url

### ISSUE THREAD

**Issue by JackZForDream** [yiisoft/yii2#8892]
```
//this is a arbitrary url to access one blog;
http://localhost/aurora/front/web/index.php?r=blog/index&name=jackz

if(Yii::$app->user->identity->name == Yii::$app->request->get('name')){
    $isAuthor = true;
}else{
    $isAuthor = false;
}
```
if $isAuthor is true, the post page will show the button for editing.
I want to make the code in layout file by passing it to $this->params['isauthor']
so that used in nested template,but it not works.
any advice I thanks

**Comment by lynicidn** [comment]
read about rbac

**Comment by JackZForDream** [comment]
@lynicidn
I know I can create a rule before save editing,but I want to check it in controller so that I can 
redirect to the post page

**Comment by klimov-paul** [comment]
@JackZForDream, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by JackZForDream** [comment]
I am new to github,and I got it
