### ISSUE TITLE
Напишите инструкцию для разделения бэка и фронта

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#8894]
как разделить advanced шаблон чтобы 
mysite - mysite/frontend/web/index.php
a mysite/backend - mysite/backend/web/index.php

**Comment by malyshev** [comment]
Вот неплохая инструкция: http://httpd.apache.org/docs/current/mod/mod_rewrite.html

**Comment by samdark** [comment]
Зависит от сервера. Напишу.

**Comment by des1roer** [comment]
ну их популярных два - апач и nginx

**Comment by zelenin** [comment]
https://github.com/mickgeek/yii2-advanced-one-domain-config

**Comment by YaroslavShapoval** [comment]
@zelenin +1

А простого создания symlink типа
```bash
ln -s /app/backend/web frontend/web/admin
```
не будет достаточно?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/commit/7e1d96ac055fbb0ee51521ec5edc2dd9d87dc324
