### ISSUE TITLE
Cross-subdomain authentication and identity cookies - logout problem

### ISSUE THREAD

**Issue by ageusz** [yiisoft/yii2#8896]
I followed solution described by @samdark [here ](https://github.com/samdark/yii2-cookbook/blob/master/book/cookies.md#cross-subdomain-authentication-and-identity-cookies)

When I login into subdomainA I am indeed logged in into subdomainB and `_identity` cookie under domain name is created. 

The problem is logging out. When I logout from subdomainA I'm still logged in at subdomainB (but there's no `_identity` cookie at all). I can then login into subdomainA again on different account but on subdomainB I'm still logged in on previouse account.

Shouldn't the user be logged out from all subdomains? Like in google case?

**Comment by kidol** [comment]
Looks like you have to add `domain` also to `cookieParams` of session component. Otherwise B will create a new session when you come from A (via the shared identity cookie).

Also try to keep such questions out of issue tracker. Use forum instead.

**Comment by ageusz** [comment]
Thanks for the answer. I posted it here because I considered it kind of a bug / miss in docs because setting `identityCookie` cookie in `user` component makes developer thinking it's all done. 

I think it should be noted in the docs. 
Thanks.
