### ISSUE TITLE
Core Validator (>) failed to compare attribute

### ISSUE THREAD

**Issue by sanusi87** [yiisoft/yii2#8897]
I have this **controller**:
```php
class ThisisatestController extends Controller{
	public function actionTest(){
		$test = new TestForm();
		return $this->render('/site/test', [
			'model' => $test
		]);
	}
}
```

**model**
```php
class TestForm extends Model{
	public $salary_min;
	public $salary_max;
	
	public function rules(){
		return [
			[['salary_min'], 'compare', 'compareAttribute' => 'salary_max', 'operator' => '<', 'message' => 'Minimum salary should be less than maximum salary.'],
			[['salary_max'], 'compare', 'compareAttribute' => 'salary_min', 'operator' => '>', 'message' => 'Maximum salary should be greater than minimum salary.'],
			[['salary_min', 'salary_max'], 'double'],
		];
	}
}
```

and **view**
```php
$form = ActiveForm::begin();

echo  $form->field($model, 'salary_min')->textInput();
echo  $form->field($model, 'salary_max')->textInput();
	
echo Html::submitButton('<i class="fa fa-save"></i> Save', [
	'class' => 'btn btn-primary',
	'name' => 'save',
]);
	
ActiveForm::end();
```

## ok
if i use Yii2 version 2.0.1, the validation works fine,
![1](https://cloud.githubusercontent.com/assets/7480483/8351991/2cd27962-1b64-11e5-8171-771f59b6fac3.png)

## not ok
but, if i use Yii2 version 2.0.4, then the validation failed
![2](https://cloud.githubusercontent.com/assets/7480483/8351997/3bc9c3bc-1b64-11e5-893f-ec046211da87.png)

**Comment by cebe** [comment]
may be caused by this commit: https://github.com/yiisoft/yii2/commit/dad47b433e5a11101182483327f500e1312da6fd

**Comment by Faryshta** [comment]
@cebe no, its a documented behavior http://www.yiiframework.com/doc-2.0/yii-validators-comparevalidator.html#$type-detail maybe we can make a patcht that when a '>' operator is used automatically set the type to number.

@sanusi87 just add `'type' => 'number'` to your validators and they will work perfectly.

**Comment by deshario** [comment]
>  [['virtual_remain_amount','virtual_paid_amount'], 'safe'],
            [['virtual_paid_amount','virtual_paid_amount'], 'number'],
            ['virtual_paid_amount', 'compare','compareAttribute'=>'virtual_remain_amount', 'type' => 'number'],

>  
        <?= $form->field($model, 'virtual_remain_amount')->textInput() ?>

        <?= $form->field($model, 'virtual_paid_amount')->textInput() ?>

Hey @Faryshta ... It's still not working after add type => number

![bug](https://user-images.githubusercontent.com/11426727/42184142-a746410e-7e6e-11e8-8696-7bce4cececed.PNG)
