### ISSUE TITLE
Add ability to perform SELECT with FOR UPDATE and LOCK IN SHARE MODE

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#8898]
Sometimes when fetching ActiveRecord model data from DB like so: 
```
$model = MyModel::find()->where('status' => 3)->all();
```
performed SELECT needs to be SELECT ... FOR UPDATE or SELECT ... LOCK IN SHARE MODE (https://dev.mysql.com/doc/refman/5.7/en/innodb-locking-reads.html).
It would be nice to have a built-in support for this in ActiveRecord and QueryBuilder.

**Comment by klimov-paul** [comment]
This will not be supported as it is MySQL specific feature.

**Comment by cebe** [comment]
you should better use transactions to ensure these lockings.

**Comment by robsch** [comment]
What would be a workaround? How could I append the 'FOR UPDATE' string to the query?

I think sometimes transaction are not always the right solution. E.g. currently I have the problem with a transaction that updates and selects different rows (takes some seconds). Other selects get blocked during the transaction, what I'd like to avoid. Changing the isolation level of the transaction did not help. So I thought I have to apply 'FOR UPDATE' at my selects within the transaction. But unfortunately, I'm not sure if this is the right approach at all...
