### ISSUE TITLE
предложение изменить в BaseHtml activeFileInput

### ISSUE THREAD

**Issue by cyxen** [yiisoft/yii2#8899]
есть ли смысл изменить  activeFileInput с 
<code>
return static::activeHiddenInput($model, $attribute, ['id' => null, 'value' => ''])
            . static::activeInput('file', $model, $attribute, $options);
</code>
на 
<code>
return static::activeHiddenInput($model, $attribute, ['id' => null, 'value' => $model->$attribute])
            . static::activeInput('file', $model, $attribute, $options);
</code>
?
P.S.: при сохранении модели без загрузки файла в базе теряется его имя.

**Comment by samdark** [comment]
Нет. Это сделано намеренно потому как чаще всего сохранять оригинальное имя файла не безопасно. Поле не должно быть safe. Если всё-таки надо, сохранение делается руками.
