### ISSUE TITLE
Menu bug with url alias

### ISSUE THREAD

**Issue by demisang** [yiisoft/yii2#8900]
App config:
```php
Yii::setAlias('@home-url', '/site/index');
```

Menu widget item:
```php
['label' => 'Home', 'url' => ['@home-url']]
```

Result: menu item is not active, because url route part is not equal current request route

I made pull-request, but It seems wrong, because not show in repo pull-requests: https://github.com/demisang/yii2/pull/1

Need to do https://github.com/demisang/yii2/commit/89ba32934d2032b615ca418e697058c95c5962b9

**Comment by cebe** [comment]
you somehow managed to send the pull request against your own master branch instead of the yii master :)

**Comment by cebe** [comment]
Issue seems valid, merged your commit manually, thanks!
