### ISSUE TITLE
AssetManager can not get the correct published url or path when only partial published

### ISSUE THREAD

**Issue by hightman** [yiisoft/yii2#8901]
For example, my AssetBundle specified `@bower` as `$sourcePath`, after publishing only the realpath of `@bower` is saved to `AssetManager::$_published`.

When I try to pass "@bower/admin-lte/dist" as parameter into `Yii::$app->assetManager->getPublishedUrl()`, it can not return the correct result. The same issue also occurred in `AssetManager::getPublishedPath()`.

**Comment by Faryshta** [comment]
1) there is already and adminlte asset, you can google it

2) can you show us your composer.json?

**Comment by hightman** [comment]
Please look at the problem, `Admin-LTE` is only an example.

**Comment by klimov-paul** [comment]
Rejected: this is missusage of the AssetBundle publish mechanism.
If there are several bundles which uses files under same root directory, they should specify `sourcePath` to be this root directory, while particular JS or CSS files should be specified as related path.

This how it is done at `yii2-botstrap`:
https://github.com/yiisoft/yii2-bootstrap/blob/master/BootstrapAsset.php#L20-L23
https://github.com/yiisoft/yii2-bootstrap/blob/master/BootstrapPluginAsset.php#L20-L23
https://github.com/yiisoft/yii2-bootstrap/blob/master/BootstrapThemeAsset.php#L20-L23

Overcomplicating the code is not justified here.
