### ISSUE TITLE
Failed to decode downloaded font [bower-asset/bootstrap v3.3.5]

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#8905]
since upgrading to bower-asset/bootstrap v3.3.5 (via composer update), I got in Chrome Console

```js
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.woff2
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.woff
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.ttf
```

Bower-asset/bootstrap v3.3.4 does not have above warnings

Below is the Screenshot showing diff between v3.3.4 and v3.3.5

![2015-06-25_1329](https://cloud.githubusercontent.com/assets/436950/8363734/3da91cc6-1b3e-11e5-9e95-ef58e49f8a4f.png)

**Comment by samdark** [comment]
I don't think it's something that can be fixed from Yii side.

**Comment by duynguyen0511** [comment]
I post on bootstrap github then. Btw, if I want to use bootstrap v 3.3.4, can i do 

```php
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "3.3.4",
        "yiisoft/yii2-swiftmailer": "*",
        "kartik-v/yii2-detail-view": "*"
    },
```

**Comment by cebe** [comment]
yes

**Comment by duynguyen0511** [comment]
@cebe I cant specific the bootstrap version by setting "yiisoft/yii2-bootstrap": "3.3.4" in the composer.

![2015-06-26_1338](https://cloud.githubusercontent.com/assets/436950/8385867/d12b2762-1c08-11e5-8520-cd2efd3d86f3.png)

what is the work around ?

**Comment by cebe** [comment]
sorry, I missread your comment. You have to require the bootstrap version for `bower-asset/bootstrap`, not yii2-bootstrap, like here: https://github.com/yiisoft/yii2-bootstrap/issues/62#issuecomment-116683578
