### ISSUE TITLE
使用leftJoin遇到的问题

### ISSUE THREAD

**Issue by shuo616** [yiisoft/yii2#8907]
当使用 $query->leftJoin(A::tableName(), [A::tableName() . '.id' => B::tableName() . '.id', A::tableName() . '.p_id' => $pid]);
得到的结果是 
LEFT JOIN `a` ON (`a`.`id`='b.id') AND (`a`.`p_id`='110')
这是一个bug？ 还是方法不当？ 望解答

**Comment by shuo616** [comment]
使用 $query->leftJoin(A::tableName(), ['and', [A::tableName() . '.id' => B::tableName() . '.id'], [A::tableName() . '.p_id' => $pid]]);
得到的结果完全一样

**Comment by hightman** [comment]
把 on 参数写成字符串，如果非要用 hash 形式写，值必须用 `\yii\db\Expression` 对象。

```php
$query->leftJoin(A::tableName . ' a', 'a.id = id AND a.p_id = :pid', [':pid' => $pid]);
$query->leftJoin(A::tableName(), [A::tableName . '.id' => new \yii\db\Expression(B::tableName() . '.id']);
```

**Comment by shuo616** [comment]
强迫症患者总是不喜欢直接写字符串 
\yii\db\Expression可以解决！ thx！

**Comment by lichunqiang** [comment]
解决了，就把issue关了啊
