### ISSUE TITLE
вопрос по миграциям

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#8908]
https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/db-migrations.md
можете указать полный список доступных типов колонок?
TYPE_STRING - varchar
TYPE_TEXT - text без ограничителя
TYPE_INTEGER - integer
TYPE_PK - по логике для pg это serial?
TYPE_BOOLEAN - bool
интересуют типы timestamp, date, real

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/MigrateController.php#L140

пробуйте юзать форум - смелее, там не кусаются

**Comment by lynicidn** [comment]
а не туда дал ссыль https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/Schema.php#L25

но форум все же попробуйте, ибо это баг треккер, погуглите, что такое баги и что такое вопросы и для чего нужен форум

**Comment by des1roer** [comment]
ну я думаю не лишним это будет добавить в документацию 
https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/db-migrations.md

**Comment by lynicidn** [comment]
кто вас обязал юзать константы, если вы их не знаете? вы поддерживаемые поля хоть знаете?
вот пример миграции
```php

        $this->createTable('{{%user}}', [
            'id' => 'pk',

            'status' => 'smallint not null default 10',

            'username' => 'string(32) not null unique',
            'altname' => 'string(32) unique',

            'email' => 'string not null unique',
            'email_activate_token' => 'string(32) unique',

            'password_hash' => 'string(32) not null',
            'password_reset_token' => 'string(32) unique',

            'auth_key' => 'string(32) not null',

            'photo' => 'string',

            'visited_at' => 'integer',
            'created_at' => 'integer not null',
            'updated_at' => 'integer not null',
            'updated_by' => 'integer not null',

            'revision' => 'integer not null default 0',
        ], $tableOptions);
```

**Comment by lynicidn** [comment]
а еще скоро (или уже) будет ооп стайл https://github.com/yiisoft/yii2/pull/8833
