### ISSUE TITLE
Postgres не находит схему 

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#8910]
указываю дефолтную схему так

		'yii\db\Connection',
			'dsn' => 'pgsql:host=***.ru;port=5432;dbname=DB_**',
			'username' => 'postgres',
			'password' => '****',
			'schemaMap' => [
				'pgsql' => [
					'class' => 'yii\db\pgsql\Schema',
					'defaultSchema' => 'yii2' //specify your schema here
				]
			],
			'charset' => 'utf8',
		];
при миграции получаю

 Creating migration history table "migration"...Exception 'yii\db\Exception' with message 'SQLSTATE[3F000]: Invalid schema name: 7 ERROR: no schema has been
selected to create in

**Comment by lynicidn** [comment]
юзайте форум, вы вообще кота в будку засовываете

**Comment by lynicidn** [comment]
move http://yiiframework.ru/forum/viewtopic.php?f=19&t=30442

**Comment by des1roer** [comment]
return [
    'class' => \yii\db\Connection::class,
    'dsn' => 'pgsql:host=localhost;dbname=database',
    'username' => 'postgres',
    'password' => 'postgres',
    'schemaMap' => [
        'pgsql' => [
            'class' => \yii\db\pgsql\Schema::class,
            'defaultSchema' => 'my_schema'
        ]
    ],
    'on afterOpen' => function ($event) {
            $event->sender->createCommand("SET search_path TO my_schema")->execute();
    }
];
