### ISSUE TITLE
Dependency Injection: contextual binding

### ISSUE THREAD

**Issue by akireikin** [yiisoft/yii2#8911]
Is it possible to set contextual binding like [here](http://laravel.com/docs/5.0/container#contextual-binding)?

```php
interface SomeInterface {}
class A implements SomeInterface {}
class B implements SomeInterface {}

class SomeClass
{
    private $x;

    public function __construct(SomeInterface $x)
    {
        $this->x = $x;
    }

    public function whoIsX()
    {
        echo get_class($this->x);
    }
}

class ContextA extends SomeClass {}
class ContextB extends SomeClass {}

$container = new \yii\di\Container();

// ??? contextual binding ???

// A
$container->get(ContextA::class)->whoIsX();

// B
$container->get(ContextB::class)->whoIsX();


```

**Comment by lynicidn** [comment]
объясню на русском
1. как вы сопоставите в одном контейнере 2 сущности?
2. если удался п.1 как контейнер поймет какую сущность вам создать?
на уровне 1 контейнера можно сопоставить единую реализацию интерфейса, вам надо смотреть куда то сюда https://github.com/yiisoft/yii2/issues/4130

**Comment by akireikin** [comment]
@lynicidn 
1. Исходя из контекста. Например, в метод set() контейнера добавить необязательный параметр (контекст для которого регистрируется зависимость).
2. Контейнер смотрит контекст (для какого класса запрашивается зависимость), пытается разрешить её в запрашиваемом контексте. Не получается - берёт из глобального.

**Comment by lynicidn** [comment]
1. ты когда получаешь из контейнера уже есть необязательный параметр - контейнер!
2. ты говоришь про то куда я дал ссыль (ишью) только это не верно - глобальный контейнер и дочерниее, тут либо контейнер на уровень модуля вынести, либо все в одном, но тогда твою задачу это не решит, а цепочку контейнеров по приоритету - бред

**Comment by lynicidn** [comment]
Instance::ensure('db', '\yii\db\Connection', MyApp::$container)

**Comment by akireikin** [comment]
Я не хочу с тобой спорить. Просто посмотри как это сделано в Laravel. http://laravel.com/docs/5.1/container#contextual-binding

**Comment by lynicidn** [comment]
да хоть ларавел, хоть симфони - 1 интерфейсу можно сопоставить 1 сущность в контейнере
а то что логика у них спрятана в контейнер это как бы не тру, вот такая запись 
```php
$this->app->when('App\Handlers\Commands\CreateOrderHandler')
          ->needs('App\Contracts\EventPusher')
          ->give('App\Services\PubNubEventPusher');
```
на уии будет
```php
class MyObj
{
    public $db = 'db'; // вот тут задаем id в сервислокатореее
    public fuction init()
    {
    parent::init();
        $this->db = \yii\di\Instance::ensure($this->db, 'вот тут проверяем интерфейс');
    }
}
```
смысл что в ларавеле есть when, который перед выдачей сначала какие то проверки делает, но это ли логика контейнера? какую задачу конкретно не получается решить?
```php
class Module extend \yii\base\Module
{
    public static $container;
    public fuction init()
    {
    parent::init();
        $container = self::$container->has('MyInterface') ? self::$container : null;
        $component = \yii\di\Instance::ensure('MyInterface', $container);
    }
}
```

**Comment by lynicidn** [comment]
я как бы не спорю, что ты не прав, я даже создал давно ишью которая и решала как раз бы такие нюансы, которые ты описываешь, и судя по лейблу и по открытому ишью, это будет все же реализовано

**Comment by akireikin** [comment]
Кому что ближе. Мне нравится когда всё упаковано в контейнер, и я имею дело
только с ним.

я как бы не спорю, что ты не прав, я даже создал давно ишью которая и

**Comment by lynicidn** [comment]
контейнер это костыль быстро чтото поменять в приложении, завязывать логику на него все же не стоит

**Comment by akireikin** [comment]
На моей памяти ты первый, кто считает его костылём. Интересно послушать
твою точку зрения. Почему ты так считаешь?

контейнер это костыль быстро чтото поменять в приложении, завязывать логику

**Comment by lynicidn** [comment]
di это не инструмент в который надо закладывать логику работы компонентов системы, ди это управление зависимостями на уровне контейнера ( вообще ди подразумевает многие вещи, не только инъекцию сеттеров (в уии нет) и конструктора, а так же теггирование компонентов между собой (в уии только проверка на интерфейс - нет у компонентов тегов ) )
ди позволяет непрозрачно переопределить любое звено системы без влезания в код, это нереально поддерживать, т.к. уии не предоставляет какого то инструмента, чтобы можно было в конфиге переопределять(задавать) соответсвия, поэтому запись вида Yii::$container обычно делается в бутстрапе или в index.php вообще, даже исходя из этого можно понять что это костыль, из ди уии юзает только сервис локатор, вот где должны быть объявлены все сервисы. Так же в уии ди позволяет не только сменить(задать) соответствие, но и изменить начальные (дефолтные) конфиги у любого компонента, что опять же не прозрачно для поддержки, ибо это не отображается в конфиге. 
Ди без теггирования вообще теряет основной смысл выстроиь зависимости компонентов между собой, вот возьмем пример \yii\db\Connection оно умеет кешировать схему, но сам компонент кеша мы не можем сменить только у коннекшена, через установку соответствия интерфейсу, т.к. в уии применяется практика сервисного локатора, где  у компонента есть id, в нашем случае cache и чтобы сменить его, мы должны в локатор поместить  новый компонент и в конекшене уже указать его id. Реального применения ди, казалось бы можно достичь используя конструктор, но опять же, это не правильно вызывать класс, не передавая данные ему в конструктор, которые он ждет и надеятся что ди это сделает за нас. Хотя дело каждого как программировать, но повторюсь, логику на ди я бы не стал завязывать. А попробуйте задать соответствие для ActiveQueryInterface, он создается в методе find модели через контейнер - увас это не получится, но если бы это был бы не костыль, то думаю мы бы не делали Yii::createObject('\yii\db\ActiveQuery', get_called_class())
а делали бы чтото вроде Yii::$container->get('\yii\db\ActiveQueryInterface', get_called_class()) <-- это условно, на самом деле get_called_class должен передаваться при задании соответствия <--
Не знаю насколько понятно попытался объяснить, это лично мое мнение, но я бы с радостью выслушал разработчиков по данному вопросу :)

Ты бы объяснил в какой задачи ты это хочешь использовать? Реальное применение какое?

**Comment by lynicidn** [comment]
и да, ди незаменим в тестировании, когда тебе моском надо чтото переопределить к примеру

**Comment by lynicidn** [comment]
русскоязычные разработчики, поддержите дискуссию :)
@samdark @creocoder @klimov-paul

**Comment by samdark** [comment]
Not going to accept it. It's way too magical. Makes reading code and debugging it very hard.
