### ISSUE TITLE
DSN Empty

### ISSUE THREAD

**Issue by osCMattiFinn** [yiisoft/yii2#8913]
I am getting the following error on SOME Ajax calls:

Exception (Invalid Configuration) "yii\base\InvalidConfigException" with message 
"Connection::dsn cannot be empty."

I can make exactly the same call again and it's fine, it just appears intermittently.

There is nothing wrong with my configuration or my database connection (localhost on WAMPserver)

**Comment by samdark** [comment]
Are you using anything special line .env for configuration?

**Comment by osCMattiFinn** [comment]
No, standard configuration.

**Comment by samdark** [comment]
Which opcache is used in WAMP? OpCache? APC? XCache?

**Comment by osCMattiFinn** [comment]
None.

**Comment by creocoder** [comment]
@osCMattiFinn Do you use dotenv?

**Comment by osCMattiFinn** [comment]
No.  This is just a very standard Yii2 Advanced application running on WAMPserver (Windows).  I have never seen a similar issue with a multitude of PHP applications running on my localhost, including other Yii1 and Yii2 applications.  

That the problem is intermittent makes it very difficult to understand exactly what is wrong.  Does Yii2 have it's own cache for something like this?

**Comment by samdark** [comment]
For config? No.

**Comment by rrhyne** [comment]
I'm seeing the same error with the advanced template when running a simple query as so:

`$db = new  Yii::$app->db;
$sql = "SELECT sum(total) as total FROM thing WHERE aid = " .$this->id;
$total = $db->createCommand($sql)->execute();
$this->total = $total;`

Query builder works fine:

`$row = (new \yii\db\Query())
        ->from('thing')
        ->where(['=', 'aid', $this->id])
        ->sum('total');
        return $row;`

All active record queries work fine. 

No caching enabled for PHP.

**Comment by rrhyne** [comment]
dumping Yii::$app->db results in null values for dsn. dumping Yii::$app shows the db array correctly poplated.

**Comment by kidol** [comment]
`$db = new  Yii::$app->db;`

is same as

`$db = new \yii\db\Connection;`

So no wonder dns is null. Remove `new`.

**Comment by osCMattiFinn** [comment]
I have never ever used that kidol.

I only ever use: Yii::$app->db->createCommand($sql)

**Comment by osCMattiFinn** [comment]
Please reopen this cebe, it has not been resolved.

**Comment by osCMattiFinn** [comment]
This problem happens intermittently for exactly the same Ajax call, thus exactly the same database query.  Sometimes it's fine, other times I get the above error.  Something is not right.

**Comment by cebe** [comment]
sorry, thought this was you answering there.

**Comment by cebe** [comment]
can you provide a stack trace for the error?

**Comment by sahifedp** [comment]
Hi.
I have this problem too.
I used .env config file with wamp 3
what do I do?

**Comment by sahifedp** [comment]
My Stack trace:
Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Connection::dsn cannot be empty.' 

in F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php:523

Stack trace:
#0 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(836): yii\db\Connection->open()
#1 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(823): yii\db\Connection->getMasterPdo()
#2 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(796): yii\db\Connection->getSlavePdo()
#3 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\Connection.php(680): yii\db\Connection->getDriverName()
#4 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\ActiveRecord.php(294): yii\db\Connection->getSchema()
#5 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\ActiveRecord.php(317): yii\db\ActiveRecord::getTableSchema()
#6 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\ActiveRecord.php(176): yii\db\ActiveRecord::primaryKey()
#7 F:\lamp\www\ara20\vendor\yiisoft\yii2\db\BaseActiveRecord.php(102): yii\db\ActiveRecord::findByCondition(1)
#8 F:\lamp\www\ara20\common\models\User.php(126): yii\db\BaseActiveRecord::findOne(1)
#9 F:\lamp\www\ara20\vendor\yiisoft\yii2\web\User.php(614): common\models\User::findIdentity(1)
#10 F:\lamp\www\ara20\vendor\yiisoft\yii2\web\User.php(176): yii\web\User->renewAuthStatus()
#11 F:\lamp\www\ara20\vendor\yiisoft\yii2\web\User.php(346): yii\web\User->getIdentity()
#12 F:\lamp\www\ara20\vendor\yiisoft\yii2\base\Component.php(130): yii\web\User->getIsGuest()
#13 F:\lamp\www\ara20\common\behaviors\LocaleBehavior.php(46): yii\base\Component->__get('isGuest')
#14 [internal function]: common\behaviors\LocaleBehavior->beforeRequest(Object(yii\base\Event))
#15 F:\lamp\www\ara20\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\base\Event))
#16 F:\lamp\www\ara20\vendor\yiisoft\yii2\base\Application.php(372): yii\base\Component->trigger('beforeRequest')
#17 F:\lamp\www\ara20\frontend\web\index.php(25): yii\base\Application->run()
#18 {main}

**Comment by SilverFire** [comment]
@sahifedp the issue is very old, please, open a new one.
