### ISSUE TITLE
Improving the CORS behavior

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#8914]
While the CORS behavior is very nice there's some room for improvement. I would expect the CORS behavior to
1. Terminate the request if it came from invalid origin
2. On success, set the response status to 204
3. On success just send the response.

The above would solve the following issues
1. CORS behaviour with CompositeAuth following (preflight req. contains no auth info - usually - and as such CompositeAuth terminates with 401)
2. CORS should not be counted against rate limiting
3. In 99% of the cases, I wouldn't want my action code to run if it was a PREFLIGHT request.

(Especially the CORS with the CompositeAuth following is a very annoying and tricky combination)

What do you guys think?

**Comment by fernandezekiel** [comment]
> 3. In 99% of the cases, I wouldn't want my action code to run if it was a PREFLIGHT request.

isn't a preflight request an `OPTIONS` request? therefore it will not execute any other action than the options action

**Comment by ptheofan** [comment]
preflight requests are sent to the requested URL with verb OPTIONS.
This means that request arrives as expected to the desired controller/action. If you allow the code to normally propagate, after the CORS behavior it reaches the expected controller/action. If you don't handle it per action (or via beforeAction) your action will run and will return what it would return under normal circumstances.

Howerver. preflight requests expect response status 204 (No Content) or browser rejects them.

**Comment by fernandezekiel** [comment]
hmm sorry are we not talking about a REST API here? cause this is not the case for Yii's REST api

**Comment by ptheofan** [comment]
It is a RESTapi (but not using the default Yii2 REST controller).
Still (in my case) the exact same API is used by an AngularJS app and of course by normal server-to-server requests.
I find it verycommon for an AngularJs, Backbonejs, etc, to be accessing a RESTful API directly.

**Comment by fernandezekiel** [comment]
maybe you should create route to a particular OPTIONS action to handle any options request for that endpoint instead of doing a beforeAction to check if it's a preflight or not...
also i don't see in the link requiring the preflight to return 204, i work with emberjs as client and they accept 200 as proper response

**Comment by ptheofan** [comment]
I could create a default route but that could have sideeffects - i.e. an actual preflight to 404 would return 204. Not much of an issue but beforeAction turns out to be a cleaner solution.

- the 204 is not documented there, true, but play over chrome with CORS and after a lot of searching and wondering you'll end up in the 204 (no content) :)

Thing is, one would have expected this to be handled by the CORS behaviour to keep things clean and tidy.

**Comment by fernandezekiel** [comment]
well you also are probably not using Yii's restful routing, that implementation will automatically route options request to the proper actions per controller so the 404 problem will not occur
