### ISSUE TITLE
REST prepareDataProvider for "view" action

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2#8915]
Hey,

Currently building out an API using the parts that come with Yii2, stupidly easy on the most part.
Perhaps I have a special case but I need to override the data source for certain things and have extended the models into my API module.

For the "index" action I was able to set "prepareDataProvider" as described in the docs but "view" doesn't support the same functionality.

How would I go about setting something like this up?
Or is there a different approach to this?

Thanks,
Gary

**Comment by fernandezekiel** [comment]
there's a `findModel` property you can set when declaring the actions for view,update and delete

**Comment by garyrutland** [comment]
So there is, perfect. Thanks.

**Comment by fernandezekiel** [comment]
we should add it in the guide probably, as i've searched it's not there
