### ISSUE TITLE
使用pjax载入包含有<pjax>gridview</pjax>的页面时,会报jQuery(...).yiiGridView is not a function的js错误

### ISSUE THREAD

**Issue by xjdata** [yiisoft/yii2#8916]
请问如何解决  导航链接pjax载入了包含了如下内容的页面时，
```php
<?php Pjax::begin(['id' => 'enum-list']); ?>
 <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'id' => 'enum-data-list',
                       //
                       //
                       //
?>
<?php Pjax::end(); ?>
```
有2个问题， 
controller中使用renderPartial 渲染视图，那么渲染结果就不包含js脚本，gridview第一次点击 分页/任何其他链接，都不会使用pjax。当然因为没有js搜索也不会被触发。
controller中使用renderAjax渲染视图，直接报jQuery(...).yiiGridView is not a function的js错误。
在layout/main，中已经注册了jquery的资源，并且加载在页面头部了。不知道是我那里出错了。
谢谢。

**Comment by SilverFire** [comment]
I guess it's about loading a GridView with Pjax. Script `yii.gridView.js` is being removed on Pjax prefiltering.
Duplicates #3680
Let's close this one.

**Comment by SilverFire** [comment]
Should be fixed by https://github.com/yiisoft/jquery-pjax/pull/30
