### ISSUE TITLE
Rules with server names

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#8921]
I was reading [Rules with Server Names](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#rules-with-server-names) in Yii2 docs and I'd like to suggest some improvements on this feature:
- Make it protocol careless. Instead of `"http://foo.bar.com/something" => "controller/action"`, allow it to be `"://foo.bar.com/something" => "controller/action"`. The use case is websites that support two (or more) protocols would benefit from this because the config wouldn't need to contain two (or more?) copies of each rule, the protocol being the only difference.
- If possible, make it domain careless. So `"http://foo.bar.com/something" => "controller/action"` can become `"://foo.*/something" => "controller/action"`. Use case: easier development as both `bar.com` and `localhost` (which is what most devs work with)  would match the rule.

**Comment by alexandernst** [comment]
And a suggestion for docs improvements (on this topic).

* How to create a URL for a server name. Let's say I want to create a URL such as `http://foo-bar.example.com/xyz`. Should I write something like `Url::to(["slug" => "foo-bar", "example.com", "site/xyz"])`?

**Comment by petrabarus** [comment]
We can define domain in `Url::to()`?

**Comment by dynasource** [comment]
closed in favor of https://github.com/yiisoft/yii2/issues/12691
