### ISSUE TITLE
How to validate only dirty attributes?

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8924]
In users model I have following rule

```
  [['username', 'email'], 'unique'],
```

What I want to do is, to make this rule available during new user creation, on update (when user entered another username or email to check if it's unique or not). but currently user model (in update action) gives error "username is not unique" even if user doesn't edit current username and email and just save filled form (with current values) .

For example, your username is: user1. You opened `update` action and changed your password only. In this situation my configuration gives `user1 is not unique` message. 

Here is actions code:
```
    public function actionMe()
    {
        $data["model"] = $model = $this->findModel(Yii::$app->user->id);

        if ($model->load(Yii::$app->request->post())) {
            if (trim($model->password) != "")
                $model->setPassword($model->password);
            if ($model->validate() && $model->save())
                return $this->redirect(['site/index']);
        }
        return $this->render('me', $data);
    }
```
How can I prevent this behaviour?

**Comment by dhiman252** [comment]
Please refer to the documentation. For these type of situations we make use of scenarios.

Like you want this behaviour at the time of user registration then use


[['username', 'email'], 'unique','on'=>'create'],

**Comment by turalsprofile** [comment]
@dhiman252 please read carefully. I'm already using scenarios. But my situation has nothing to do with scenarios. Even if I seperate rules by scenarios, on update I need validation only when filled form differs from past values. If you fill same things or nothing changes on form and you just saved it, I don't need validation.

**Comment by Skysplit** [comment]
How about

```php
[
    ['username', 'email'],
    'unique',
    'filter' => function ($query) {
        $query->where(['not', ['id' => Yii::$app->user->getId()]]);
    }
]
```

**Comment by turalsprofile** [comment]
@Skysplit the main idea here is, on update to not to validate if values are exactly same after new form submission. I think your workaround is not solution for this problem

**Comment by turalsprofile** [comment]
I mean, for example your username is: user1. You opened `update` action and changed your password only. In this situation my configuration gives `user1 is not unique` message.

**Comment by Skysplit** [comment]
I understand the problem and I think my solution should work. Eventually, you can use `when` in validation rule
```
[
    ['username', 'email'],
    'unique',
    'when' => function ($model, $attribute) {
        return $model->{$attribute} !== $model->getOldAttribute($attribute);
    }
]

**Comment by cherifGsoul** [comment]
Already posted https://github.com/yiisoft/yii2/issues/705, look at dirty attributes and write your own validator

**Comment by turalsprofile** [comment]
@Skysplit and where to declare this rule? On update scenario?  Because it doesn't fit for signup     
```
[
   ['username', 'email'], 
   'unique', 
    'when' => function ($model, $attribute) {
                return $model->{$attribute} !== $model->getOldAttribute($attribute);
            },  
    'on' => 'update''
],
```
And how to switch `actionMe` into `update` scenario? I tried `$model->scenario="update";` got an error.

**Comment by turalsprofile** [comment]
@cherifGsoul how to submit only dirty attributes?

**Comment by cherifGsoul** [comment]
@turalsprofile never done this before but I think you should to write the validator or extend it

**Comment by turalsprofile** [comment]
Resolved http://blog.tural.us/saving-and-validating-only-changed-dirty-values-on-yii2/
