### ISSUE TITLE
bug maybe

### ISSUE THREAD

**Issue by JackZForDream** [yiisoft/yii2#8928]
the bootstrap.php in directory of config for frontend
```
<?php
//note that not char behind '<?php'
```

// the bootstrap.php in directory of config for backend
```
<?php\n
//note that a '\n' or spacing behind '<?php'
```

now following code located in backend controller and frontend
```
public function actionGetValue(){
	if(Yii::$app->request->isAjax){
		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        		return 'jackz';	
	}
}
```

client code following
```
$.get(
	'?r=site/get-value',     
	{},
	function(e){
		console.log(e);
	}
);
```

ok, the issue is  
in backend application,we can get correct value `'jackz'` (note that a `'\n'` behind `'<?php'` in bootstrap.php )  
but in frontend ,we get uncorrect value `<?php'jackz'`(note that not any char behind `'<?php'` in bootstrap.php),and it will works well if you add a `'\n'` or spacing behind `'<?php'`,

**Comment by Faryshta** [comment]
can you link to the files in question?

**Comment by klimov-paul** [comment]
Same as #1972
