### ISSUE TITLE
Adding selected to option attribute in activeDropDownList

### ISSUE THREAD

**Issue by ajesamson** [yiisoft/yii2#8929]
PHP:5.6.3; YII:2.0.3
Setting selected for dropDownList() in activeField is not initializing selected on form view rendering for creation of new record.
The implementation script is as shown below:

```php
<?php
      $countries = ArrayHelper::map($countries, 'id','name');
?>
<?= $form->field($model, 'countries_id')->dropDownList($countries, [
                    'prompt' => '--Select Country--',
                    'options' => ['840' => ['selected'=>'selected']]
 ]); ?>
```

Country table from mysql with attributes id and name is referenced in the above snippet by another model.

**Comment by samdark** [comment]
Selected value is automatically taken from `$model`.
