### ISSUE TITLE
BaseDataProvider does not set pagination's totalCount

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#8932]
This code is duplicated in all the data providers, and if you write your own data provider, you have to do it too, otherwise pagination won't work:

https://github.com/yiisoft/yii2/blob/2.0.4/framework/data/SqlDataProvider.php#L127
https://github.com/yiisoft/yii2/blob/2.0.4/framework/data/ActiveDataProvider.php#L105
https://github.com/yiisoft/yii2/blob/2.0.4/framework/data/ArrayDataProvider.php#L82

This should be put into BaseDataProvider.

**Comment by robert589** [comment]
is there any solution for this? my total count is not working too

**Comment by samdark** [comment]
The code seems to be different enough in all these cases so I won't call this a duplication.

**Comment by nkovacs** [comment]
I meant only this one line:

    $pagination->totalCount = $this->getTotalCount();

The point is that it's entirely not obvious that you have to do this in your own data provider. It's also the kind of bookkeeping boilerplate that I'd expect the base class to handle for me.

**Comment by samdark** [comment]
Won't be changed in 2.0.
