### ISSUE TITLE
Fatal errors show blank page in HHVM Yii2

### ISSUE THREAD

**Issue by dieend** [yiisoft/yii2#8933]
Similar issue with https://github.com/laravel/framework/issues/8744.

I have make sure to set up hhvm options correctly from https://github.com/facebook/hhvm/issues/4818
```
 hhvm.server.implicit_flush = true
 hhvm.error_handling.call_user_handler_on_fatals = true
```

**Comment by samdark** [comment]
@dieend can you check if changes in #8935 are enough?

**Comment by dieend** [comment]
I don't think adding the error code is enough, I've tried it previously but let me check again later, because I wasn't adding the getName() parts.

Typed in mobile, sorry for any typo.

**Comment by dieend** [comment]
@samdark I confirms those changes in #8935 doesn't enough. I'm able to show error exception by modifying https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L217 to 
```
    public function renderFile($_file_, $_params_)
    {
        $_params_['handler'] = $this;
        if ($this->exception instanceof ErrorException || !Yii::$app->has('view')) {
//            ob_start();
//            ob_implicit_flush(false);
            extract($_params_, EXTR_OVERWRITE);
            return require(Yii::getAlias($_file_));
        } else {
            return Yii::$app->getView()->renderFile($_file_, $_params_, $this);
        }
    }
```
I don't know why but `ob_start()` makes empty result for all output after that. `ob_get_clean()` returns empty string.
Looks like after throwing error, output buffer doesn't works in hhvm. I don't know whether it's bug/php-incompability in hhvm, or there is another thing that's missing.
