### ISSUE TITLE
strncmp() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by siva80** [yiisoft/yii2#8947]
I have recently set up a project using Yii2 (advanced template). 

I am using the email target to export the log messages to my email address. I have been receiving this error every day, almost every time someone logs in.

Exception 'yii\base\ErrorException' with message 'strncmp() expects
parameter 1 to be string, object given' in */vendor/yiisoft/yii2/BaseYii.php:131

Can you please advise me where to look for the solution to this problem. Is this an issue with the framework or am I doing something wrong?

Thanks.

**Comment by cebe** [comment]
seems you are passing an object to getAlias() https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L131 to say more you need to give the stacktrace of the error.
