### ISSUE TITLE
PHP Core Error – yii\base\ErrorException  Directive 'register_long_arrays' is no longer available in PHP

### ISSUE THREAD

**Issue by dencygb** [yiisoft/yii2#8952]
I intermittently get this error in my application on server. Is there any way to fix this issue from the application side? Or removing the ''register_long_arrays'' reference from php.ini is the only way to get rid of this error?

Attached is a screenshot of the error.

![sc](https://cloud.githubusercontent.com/assets/6583127/8429696/c9484948-1f47-11e5-83ae-5984096f490d.png)

**Comment by klimov-paul** [comment]
@dencygb, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
