### ISSUE TITLE
Yii2  在 model::rules() 是否支持对 `二者必居其一`验证类型的支持?

### ISSUE THREAD

**Issue by haoliangxxx** [yiisoft/yii2#8953]
由于应用中是第三方登录产生的用户, 所以用户表中会有三个字段: `id, open_id, platform`, 分别表示应用中用户的编号, 第三方用户编号, 第三方平台类型。

提供获取用户信息的接口可以通过 id 获取, 也可以通过 open_id + platform 获取。

这样, 在 `model::rules()` 中是否提供了对 `二者必居其一` 验证的支持, 即必然存在请求中给定了 id 或者给定了 open_id和platform ?

形如 `[ ['id'], ['open_id', 'platform'], 'alternative-required' ]` ？

**Comment by lichunqiang** [comment]
你可以用 `InlineValidator` 来自己实现.

**Comment by haoliangxxx** [comment]
@lichunqiang 是的, 整个rules里的规则都可以通过 `InlineValidator` 实现;
我的重点是: 框架中是否提供了? 没有提供的话, 是否考虑提供？

**Comment by lichunqiang** [comment]
那你还是翻译成e文，其他 contributor会处理，qiang都不见好几天了

**Comment by haoliangxxx** [comment]
`[ [ 'id', 'open_id' ], 'alternative' ]`
上面提到的验证, 相比放到 `model::rules()` 中每个属性都要验证一次,  放到 `model::afterValidate()` 中显然会减少判断的次数;
我觉得没必要引入到框架中了。

@lichunqiang 谢谢提醒, 我还是放到 `model::afterValidate()` 中做吧。

**Comment by haoliang-gao** [comment]
已有的实现 [yii2-at-least-validator](https://github.com/code-on-yii/yii2-at-least-validator)
