### ISSUE TITLE
Wrong Polish translation

### ISSUE THREAD

**Issue by be4code** [yiisoft/yii2#8959]
In Polish translation for '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' should be:
for =1: "znak"
for 2, 3, 4: "znaki"
for 5, 6, 7, ...: "znaków"

**Comment by bizley-code** [comment]
I don't see anything wrong with what we have now
https://github.com/yiisoft/yii2/blob/master/framework/messages/pl/yii.php#L86

**Comment by be4code** [comment]
In my rules():
[['login'], 'string', 'min' => 3]

Error: "Login powinien zawierać co najmniej 3 znaku." instead of "znaku" should be "znaki", as I mentioned previously.

**Comment by bizley-code** [comment]
I've just tested it with my version and got "Login powinien zawierać co najmniej 3 znaki".
And I've checked the repo for changes in this file and looks like it was always the same as now with this message.
What Yii version are you having?

**Comment by be4code** [comment]
My version is 2.0.4

**Comment by bizley-code** [comment]
If the line I've linked above is the same in your local version make sure you don't have any other translation messages for this.

**Comment by be4code** [comment]
The file is same as here on github. 
In my config I've got: 'language' => 'pl-PL' and I don't have any other translations (I'm sure because the app is basic app template from the tutorial).

**Comment by bizley-code** [comment]
Ok, one last try and I give up ;)
Remove all cache, modify the translation line i.e. 
```'{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute} powinien zawierać w cholerę minimalnie {min, number} {min, plural, one{kotek} few{kotki} many{kotków} other{kotka}}.',```
and check again what will be there.

**Comment by be4code** [comment]
Unfortunately 'Login powinien zawierać w cholerę minimalnie 3 kotka.'...

**Comment by bizley-code** [comment]
Can you echo this?
```echo "ICU: " . INTL_ICU_VERSION . "\n";```

**Comment by be4code** [comment]
Use of undefined constant INTL_ICU_VERSION
And I see last paragraph here: http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html I think I need to configure my environment ;)

**Comment by bizley-code** [comment]
Bingo!
