### ISSUE TITLE
Guide: Link to advanced app documentation is wrong/inconsistent

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#8967]
The link of 'Advanced Project Template' in 'Special Topics' is wrong. Should it go to http://www.yiiframework.com/doc-2.0/guide-tutorial-advanced-app.html or to https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/README.md? I would have expect the first link. Currently the link in the navigation and on the start page don't go the URL...

**Comment by samdark** [comment]
Second link is correct.

**Comment by robsch** [comment]
Then the navigation link isn't correct. It leads to the Guides main page: `href="./guide-README.html"`.

Sorry for bothering you with this tiny issue ;-) Yii is great anyway!

**Comment by samdark** [comment]
It's already fixed in code. Docs will be re-generated at some point: https://github.com/yiisoft/yii2/blob/master/docs/guide/README.md#special-topics
