### ISSUE TITLE
Custom message for min and max validation rule

### ISSUE THREAD

**Issue by bohdan-vorona** [yiisoft/yii2#8968]
RegisterForm.php:
```
	public function rules()
	{
		return [
			[['username', 'password', 'repeatPassword', 'email', 'firstName', 'lastName'], 'filter', 'filter' => 'trim'],
			[['username', 'password', 'repeatPassword', 'email', 'firstName', 'lastName'], 'required', 'message' => 'enter a value for {attribute}'],

			[['username', 'email', 'firstName', 'lastName'], 'string', 'min' => 2, 'max' => 256, 'message' => '{attribute} should be at least 2 symbols'],

			['email', 'email', 'message' => 'enter valid e-mail'],

			['username', 'unique', 'targetClass' => '\app\models\User', 'message' => 'this username has already been taken'],
			['email', 'unique', 'targetClass' => '\app\models\User', 'message' => 'this email address has already been taken'],

			['password', 'string', 'min' => 6, 'max' => 256, 'message' => '{attribute} should be at least 6 symbols'],
		];
	}
```

Result:

![yii](https://cloud.githubusercontent.com/assets/5950639/8460480/aa3f36ba-202d-11e5-85f9-b590f634e582.png)

As you can see, for **'min' => 6, 'max'** displays default message. I expected my own message from my own rule.

**Comment by bizley-code** [comment]
String validator have got 3 messages:
'message' => error message used when the value is not a string.
'tooLong' => error message used when the length of the value is greater than $max.
'tooShort' => error message used when the length of the value is smaller than $min.
Replace the proper one.

**Comment by llfm** [comment]
Change the order of the rules or use scenarios.

~ Use the yii forum ~

**Comment by bohdan-vorona** [comment]
@bizley-code thanks a lot.

**Comment by sktandon0121** [comment]
I have same problem
I have defined following rules for phone 
[['phone','ci_mobileno', 'trainer_mobile'], 'string','min'=>10, 'max' => 10,'message'=>'Should be 10 digit long.(Example: 9012687986)'],
but it is showing the below message
Phone should contain at least 10 characters.

**Comment by cebe** [comment]
@sktandon0121 use `length` to set a fixed length.

**Comment by ptcrank** [comment]
Edit the following:
----
Example 1
` [['username', 'email', 'firstName', 'lastName'], 'string', 'min' => 2, 'max' => 256, 'tooShort' => '{attribute} should be at least 2 symbols' , 'tooLong' => '{attribute} should be at most 256 symbols'  ],`
___
Example 2
` [['phone','ci_mobileno', 'trainer_mobile'], 'string','min'=>10, 'max' => 10,'tooShort'=>'Should be 10 digit long.(Example: 9012687986)' , 'tooLong' => 'Should be 10 digit long.(Example: 9012687986)' ],`

Good luck - @sobhan

**Comment by tihoho** [comment]
tooShort/tooLong not work for integer validator.
`Setting unknown property: yii\validators\NumberValidator::tooShort`
