### ISSUE TITLE
Add ability to specify additional conditions in ActiveRecord::update()

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#8971]
I need to perform a following update SQL using ActiveRecord:
```
UPDATE projects SET participant_id=123
WHERE project_id=456 AND participant_id IN (SELECT id FROM users WHERE id=123 AND is_enabled=1)
```
The idea is to update the project 456 with new value 123 for participant_id only if the user 123 is not currently disabled in the users table.

Splitting the above SQL into two separate ones (SELECT and then UPDATE) introduces a concurrency issue (user status can change in between the execution of those SELECT and UPDATE statements).

So the only way to do such update in Yii2 is using ActiveRecord::UpdateAll() method which is kind of strange when having a single $project object and wanting to update only that one record in database. It would be more natural to use ActiveRecord::update() method but it lacks the ability to specify additional conditions.

**Comment by samdark** [comment]
You can do it in transaction. Overall, AR isn't meant to work with such SQL.

**Comment by PowerGamer1** [comment]
Doing it in transaction does not solve the concurrency issue in this situation (unless you set the isolation level to the highest possible - SERIALIZABLE, which would be a total overkill). And yes, I did notice that Yii2 is not build with concurrency issues in mind at all, unfortunately.

**Comment by samdark** [comment]
AR isn't meant for it, that's what I'm saying. Means the query deals with atomicity in a very particular way that isn't possible in many AR backends.

You can execute any SQL with or without transactions though, Yii supports it.
