### ISSUE TITLE
how can i do rescoring of a document in elasticsearch in yii2

### ISSUE THREAD

**Issue by nishanthpininti** [yiisoft/yii2#8973]
i am unable to rescore the document in elasticsearch,my code is below
$result = Item::find()->query([
    				  "match" => ["item_name" => 'shirt1'],],
    				 ["rescore" => [
    				"window_size"=> 5,
    				"query"=> [
    						//"score_mode" => "max",
    						"rescore_query" => [
    								"function_score" => [
    										  "query" => [
    										"match" => ["item_name" => 'shirt1'],],  
    										"script_score" => [
    										 "script" => "100" ]
    		
    								]],"query_weight" => 1.0,
         "rescore_query_weight" => 5.9]]])->asArray()->all(); 
how do i get out of this problem

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for issues.
