### ISSUE TITLE
how should I make asset bundle available for all view in a controller ?

### ISSUE THREAD

**Issue by kalpesh4** [yiisoft/yii2#8974]
pliz help...thanks in advance.....

**Comment by lynicidn** [comment]
register it in lsyout. use forum

**Comment by kalpesh4** [comment]
ya..i used it....i have to register it in every view file.....instead i want to register asset bundle only once....

**Comment by klimov-paul** [comment]
@kalpesh4, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
