### ISSUE TITLE
can Yii2  run in php7 environment

### ISSUE THREAD

**Issue by yrssoft** [yiisoft/yii2#8975]
can Yii2  run in php7 environment？

**Comment by githubjeka** [comment]
Use forum. It's bugtracker. Please please please to all.

**Comment by lynicidn** [comment]
u can ask here https://gitter.im/yiisoft/yii2

**Comment by cebe** [comment]
@yrssoft yes it should work, if you see any problems, please report them here.

**Comment by lynicidn** [comment]
@cebe  :( https://travis-ci.org/yiisoft/yii2

**Comment by cebe** [comment]
well, that failure is by comparing the output which is cluttered because of bad test env config...

**Comment by cebe** [comment]
I have fixed the test, now it is only phpunit which is segfaulting... :-/
https://travis-ci.org/yiisoft/yii2/jobs/69459131#L572

Yii itself is definitively able to run on php 7.

**Comment by cebe** [comment]
try it and report issues, if you find any.
