### ISSUE TITLE
syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$'

### ISSUE THREAD

**Issue by sanket0052** [yiisoft/yii2#8977]
autoHideInfo:false,
        renderInfoPin:false,
        backgroundColor:'#ffffff',
        backgroundOpacity:0.8,
        infoBackColor:'#000000',
        infoBackOpacity:1
    });", $this::POS_READY); ?>
    <?= $this->registerJs("
//this line show error
        $('.yoxview >a >img').hover({
        function(){$(this).animate({opacity:0.7},300)},
        function(){$(this).animate({opacity:1},300)}
        });", $this::POS_READY); ?>

**Comment by lynicidn** [comment]
lol

**Comment by samdark** [comment]
@sanket0052 can you elaborate?

**Comment by Faryshta** [comment]
its taking `$(` as a variable. What you need to do is to be careful when you use the `$` symbol between `""` double quotes.

Shage the line to `\$(` and it will work, the ame with every time you use `$`.

Or you can use single quotes for that JS script. What I do is that I keep the script files in different files and simply render them

`$this->registerJs($this->render('effects.js'))`
