### ISSUE TITLE
Having issue with authclient.

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#8979]
I integrated social authentication based on this tutorial:

http://stuff.cebe.cc/yii2docs/guide-security-auth-clients.html

Here is my configuration file:

```
        'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
                'facebook' => [
                    'class' => 'yii\authclient\clients\Facebook',
                    'clientId' => 'my_id',
                    'clientSecret' => 'my_secret',
                ],
                'linkedin' => [
                    'class' => 'yii\authclient\clients\LinkedIn',
                    'clientId' => 'my_id',
                    'clientSecret' => 'my_secret',
                ],
            ],
        ],
```

My problem is,  when I click on social buttons it redirects into login page. I tried even something like that:
```
   public function onAuthSuccess($client) {
      $attributes = $client->getUserAttributes();
        die(print_r($attributes));
        ...
```

Even this doesn't work for me, it just 302 redirects into login page. 

What might be issue?

**Comment by klimov-paul** [comment]
@turalsprofile, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by turalsprofile** [comment]
@klimov-paul Please stop closing my bug reports. I think it's bug. Because it was working and after composer update it stopped functioning.

**Comment by cebe** [comment]
@turalsprofile then please describe the issue in more detail, what was working before and how does it not work now?
