### ISSUE TITLE
Issue with subdomain

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#8981]
Hi there! I have a localhost with configured domain "localhost" and i want to add thereto subdomain "api" thus i want to get url type of "api.localhost".
```php
        'urlManager' => [
            'rules' => [
                [
                    'pattern' => '<subdomain:\w+>.localhost'
                ]
            ]
        ]
```
But i getting error 503 when trying enter "api.localhost". Don't kick me hard, i'm beginner in Yii...

**Comment by klimov-paul** [comment]
@RSalo, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by lynicidn** [comment]
may be it help for you https://github.com/yiisoft/yii2/issues/6275

**Comment by RSalo** [comment]
Problem with error i've decided. Directly in my browser exclude this url from proxy. Thx for help!
