### ISSUE TITLE
how should I access of other's model data in current model's view

### ISSUE THREAD

**Issue by kalpesh4** [yiisoft/yii2#8984]
controller_1 
      controller_1_view_1.php
      controller_1_view_2.php

controller_2
      controller_2_view_1.php
      controller_2_view_2.php

Question: I want to access controller_1 data into controller_2_view_1.php or controller_2_view_2.php .
How should I implement same in application?

**Comment by llfm** [comment]
Use the http://www.yiiframework.com/forum/ ...
