### ISSUE TITLE
Gridview return 1 row but sql return 3

### ISSUE THREAD

**Issue by rfiedler** [yiisoft/yii2#8985]
Hi !

 1 -My search in **gridview** return **1** row. **(Its the problem)**
 2- **$dataprovider->totalCount**  return **3** results.
 3- SQL in PGAdmin3 return **3** rows too.

**What happens ?**

**Problem**
![search 1 result](https://cloud.githubusercontent.com/assets/1020057/8479656/8e4ae850-20af-11e5-8c3e-dc0291b40066.gif)

** Pure SQL in PGAdmin3**
![sql](https://cloud.githubusercontent.com/assets/1020057/8479697/bfce6af0-20af-11e5-8420-1ba6ce91bcf7.gif)

** Controller Code**
![controller](https://cloud.githubusercontent.com/assets/1020057/8479703/c95f4ae4-20af-11e5-830c-9e9ebe3e7cc5.gif)

**Search Code**
![pacientesearch](https://cloud.githubusercontent.com/assets/1020057/8479707/d08c3e8a-20af-11e5-8299-83fc0960dc71.gif)

Help please!

**Comment by cebe** [comment]
what is the primary key column of your active record? If you do joins and the results contains the same record multiple times, yii will filter that out for you. You may need to add a group by somewhere to solve it.

**Comment by rfiedler** [comment]
These tables do not have unique id . They are imported every day from an old data bank Sybase. I set primary key with getPrimaryKey function. This return "nu_paciente_pac" .....this key returns as the primary key but it is not unique id.

**Comment by rfiedler** [comment]
Hi !  

Implemented auto_increment field and everything worked perfectly.
Sorry for the inconvenience.

Thanks
