### ISSUE TITLE
Why i can't download yii2?

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#8989]
i tried 2 different projects, it's showing like that;
![capture](https://cloud.githubusercontent.com/assets/4962332/8489353/549bc57e-2123-11e5-8c35-ca2abc82da37.PNG)
i tried 10 times and it's staying there,it doesn't continue.
What's the problem?

**Comment by nunomaduro** [comment]
You need to have the git installed.

You can download him in: https://git-scm.com/downloads

**Comment by serhatozles** [comment]
it could not work :-1: 
it wrote the following code then timeout;

[Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "xcopy "C:\Winginx\home\doktor.com\public_html\yii2/vendor/composer/b7113292\yiisoft-yii2-framework-ed54d02\captcha" "C:\Winginx\home\doktor.com\public_html\yii2\ven
  dor/yiisoft/yii2/captcha" /E /I /Q" exceeded the timeout of 1800 seconds.



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-depe
ndencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

**Comment by serhatozles** [comment]
i solved. i didn't understand why. i tried again then shut down web server and it's began to work.
