### ISSUE TITLE
yii\rest\UpdateAction returns model with outdated optimistic lock value

### ISSUE THREAD

**Issue by EvgenyOrekhov** [yiisoft/yii2#8994]
yii\rest\UpdateAction returns the model with the same lock version with which it was saved, but the actual lock version is incremented by 1 during the update.
So a successful PUT/PATCH request returns the model with the outdated optimistic lock value.

**Comment by cebe** [comment]
according to the code of AR it should work: https://github.com/yiisoft/yii2/blob/078b922114e5ba3481487a80f28769e69713ea33/framework/db/BaseActiveRecord.php#L731
can you give more information, e.g. the action and model code you are using?

**Comment by EvgenyOrekhov** [comment]
@cebe you're right, it should, but that piece of code was commited after 2.0.4 release. Waiting for 2.0.5 then!

**Comment by cebe** [comment]
yeah, this has been fixed by 51a442d6c8266bf14e258cc77625b6d192f678d0 and 467596633d3b3dd271d0213fbbffba41e3293982
