### ISSUE TITLE
Add ability to NOT limit number of files that can be uploaded in FileValidator

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#8995]
Currently, if I want to upload multiple files I HAVE to set the maxFiles value to be >1 or the validator will assume that only a single file can be uploaded. But what if I do not want to limit amount of files that can be uploaded? Not setting maxFiles or setting it to 0 will make FileValidator assume that only a single file can be uploaded:
```
    public function validateAttribute($model, $attribute)
    {
        if ($this->maxFiles > 1) {
            // ...
        } else {
            $result = $this->validateValue($model->$attribute);
            if (!empty($result)) {
                $this->addError($model, $attribute, $result[0], $result[1]);
            }
        }
    }
```
To work around this I have to set a very big maxFiles value, but it would be better to let the user set it to 0 (telling the validator to expect multiple files upload with unlimited amount of files) and change the validator code accordingly.

P.S. Despite of this statement https://github.com/yiisoft/yii2/issues/4847#issuecomment-53720338 setting maxFiles to 0 is currently neither documented nor implemented in the validator code.

**Comment by cebe** [comment]
note that there is a limit to the number of files which is set by PHP:

http://php.net/manual/en/ini.core.php#ini.max-file-uploads

>  max_file_uploads integer
> 
> The maximum number of files allowed to be uploaded simultaneously. Starting with PHP 5.3.4, upload fields left blank on submission do not count towards this limit.

**Comment by PowerGamer1** [comment]
If you imply that maxFiles should be set to max_file_uploads then it won't do any good anyway - when client side validation is disabled or JavaScript in the browser is disabled the user can still try to select and upload more than max_file_uploads files. PHP will discard all extra files and issue a warning and FileValidator won't even be able to detect the problem has arisen. But it certainly would be helpful to mention the problem with max_file_uploads in the Yii2 docs dealing with file uploads and maxFiles.

**Comment by cebe** [comment]
> But it certainly would be helpful to mention the problem with max_file_uploads in the Yii2 docs dealing with file uploads and maxFiles.

@SilverFire could you add a note about this to `$maxFiles`?

**Comment by SilverFire** [comment]
Sure  898ffa5
