### ISSUE TITLE
Migrations Logs

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#8998]
Why not have a table called migrations_log where they would keep the output of shot migrations ?

Is stored log msgs (exemple):

    applying m150703_191513_drop_danfe_column
    > drop column boleto_por_email from table {{%finlegado_cliente}} ... done (time: 0.325s)
    > drop column danfe_por_email from table {{%finlegado_cliente}} ... done (time: 0.091s)

In one table content colluns:

- migrarion 
- log 
- status 
- time

**Comment by cebe** [comment]
why would you need such a table?

**Comment by cebe** [comment]
btw, a colum added to the existing migration table would be enough if needed at all.

**Comment by lukBarros** [comment]
Yes @cebe one colunn in the migrations table nomed 'log' type text long is cool.

**Comment by lukBarros** [comment]
I tink in the yii2 debug bar (tool) have one new feature: Show migations log. Simples show in the register by migrations table.

It's is cool.

**Comment by lukBarros** [comment]
@samdark  feature gii? It's is in the core component migrations,not?

**Comment by cebe** [comment]
Sill not convinced. Why is this need? what is the benefit of having such a log information?

**Comment by klimov-paul** [comment]
Does not have any sense for me either.
You can easily store migration command output into the file using `>` console operatior if it is needed:

```bash
php yii migrate > /path/to/my.log
```
