### ISSUE TITLE
Document a gotcha with UploadedFile::getInstance()

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#8999]
When a form contains inputs other than type="file" the following code will not work as one might expect:
```php
$model->someFile = UploadedFile::getInstance($model, 'someFile');
if($model->load(Yii::$app->request->post()) && $model->validate())
{
    // Surprise: $model->someFile will not be an instance of UploadedFile!
    // Need to do $model->load() before calling UploadedFile::getInstance().
```
This should be mentioned and explained in the docs: http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html.

**Comment by SilverFire** [comment]
```php
echo $form->input($model, 'someFile')->fileInput();
```

renders a hidden input `<input type="hidden" ...>` above the real file input. 
`$model->load()` will load the value of hidden input that will override `$mode->someFile`.

It's a normal and obvious behavior, I think it's not necessary to change something in docs
