### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#9002]
Hi. I trying to load debug toolbar, but i getting error on page
Not Found: Unable to find debug data tagged with '5598662f5b135'.

and console
GET http://localhost/index.php?r=debug%2Fdefault%2Ftoolbar&tag=5598662f5b135 404 (Not Found)

XDebug fully disabled and folder "runtime" exist. Thx for help!

**Comment by cebe** [comment]
is everything inside runtime writeable for the webserver?

**Comment by RSalo** [comment]
Yes, permission on folder 777.

**Comment by RSalo** [comment]
Hm, i've tried to enabled "log" in config. Debug toolbar began show normal, but if click on "Yii Debugger" or "Log", then we getting 
localhost/index.php?r=debug%2Fdefault%2Findex 500 (Internal Server Error)
localhost/index.php?r=debug%2Fdefault%2Fview&panel=log&tag=5599a678122a8 500 (Internal Server Error)

And then i disable "log". Debug toolbar again showing normal, but links not working correctly. Mystic!

**Comment by RSalo** [comment]
Problem was solved. It's bug #7571
