### ISSUE TITLE
Add options to addForeignKey() similar to createTable() options

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#9004]
This can be used for example in PostgreSQL to create a deferrable foreign key as in:

```
ALTER TABLE table1 ALTER CONSTRAINT table1_t1_id_fkey DEFERRABLE INITIALLY IMMEDIATE
```

where `DEFERRABLE INITIALLY IMMEDIATE` would be the the function options instead of two statements, one including `addForeignKey()` then another to execute an SQL statement to handle the deferrable part.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
