### ISSUE TITLE
Documentation improvement for method Request::getIsAjax()

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2#9005]
I think we must clearly specify that method Request::getIsAjax() is useless for cross-domain requests (jQuery doesn't set header HTTP_X_REQUESTED_WITH for cross-domain requests).

See: http://stackoverflow.com/questions/8163703/cross-domain-ajax-doesnt-send-x-requested-with-header

**Comment by samdark** [comment]
Added. Thanks!
