### ISSUE TITLE
MySQL BIT column always returned as true

### ISSUE THREAD

**Issue by stratoss** [yiisoft/yii2#9006]
Table structure:
```sql
--
-- Table structure for table `demo`
--

CREATE TABLE IF NOT EXISTS `demo` (
`id` bigint(20) unsigned NOT NULL,
  `test` bit(1) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `demo`
--

INSERT INTO `demo` (`id`, `test`) VALUES
(1, b'0'),
(2, b'1');
```

Test code using auto-generated model:
```php
$all = Demo::find()->all();
foreach ($all as $current) {
    var_dump($current->test);
}
```
Results are TRUE 2 times.

Fetching as array:
```php
$all = Demo::find()->asArray()->all();
foreach($all as $current) {
    if ($current['test'] === chr(0x00))
        echo 0 . PHP_EOL;
    elseif ($current['test'] === chr(0x01))
        echo 1 . PHP_EOL;
}
```
returns 0 and 1.

**Comment by stratoss** [comment]
I would suggest a check if the column type is `BIT(1)` then return `true` for `0x01` and `false` for `0x00`.

**Comment by cbhp** [comment]
Maybe issue #3176

**Comment by RusAlex** [comment]
Im not a yii2 developer or maintainer.

But just did some sort of testing your issue.

Here is my gist of test: https://gist.github.com/d89b4e325f29bc0b3371

When `asArray` approach imply that there wont be done any type casting
by framework. And pure output from PDO will be returned as result.

PDO result of bit(1) column with b'0' value is string "0" and for
column with b'1' - string "1". You can prove it by invoking this pure
php script. https://gist.github.com/c735596977d1ecadf2c6

So it's what PDO returns. And when you compare strings "0" and "1"
with ascii characters `NUL` and `SOH` by executing something like
this:

```shell
php -r 'var_dump("1"===chr(0x01), "0"===chr(0x00));'
```

You will always get false. Because hex ascii code for string "1" is
0x31 and for string "0" is 0x30.

Can be closed.

**Comment by RusAlex** [comment]
Have not seen you tried to do just `find()->all()`.

My test 
```php
$r = MyModel::find()->all();
var_dump(r);
```

first model `test` attribute equals to false. 
and second - equals to true. 

master branch yiisoft/yii2 repository

**Comment by samdark** [comment]
@RusAlex thanks!

**Comment by stratoss** [comment]
@RusAlex, @samdark : 
`var_dump(Demo::find()->all());` returns:
```
array (size=2)
  0 => 
    object(common\models\Demo)[100]
      private '_attributes' (yii\db\BaseActiveRecord) => 
        array (size=2)
          'id' => string '1' (length=1)
          'test' => boolean true
      private '_oldAttributes' (yii\db\BaseActiveRecord) => 
        array (size=2)
          'id' => string '1' (length=1)
          'test' => boolean true
      private '_related' (yii\db\BaseActiveRecord) => 
        array (size=0)
          empty
      private '_errors' (yii\base\Model) => null
      private '_validators' (yii\base\Model) => null
      private '_scenario' (yii\base\Model) => string 'default' (length=7)
      private '_events' (yii\base\Component) => 
        array (size=0)
          empty
      private '_behaviors' (yii\base\Component) => 
        array (size=0)
          empty
  1 => 
    object(common\models\Demo)[108]
      private '_attributes' (yii\db\BaseActiveRecord) => 
        array (size=2)
          'id' => string '2' (length=1)
          'test' => boolean true
      private '_oldAttributes' (yii\db\BaseActiveRecord) => 
        array (size=2)
          'id' => string '2' (length=1)
          'test' => boolean true
      private '_related' (yii\db\BaseActiveRecord) => 
        array (size=0)
          empty
      private '_errors' (yii\base\Model) => null
      private '_validators' (yii\base\Model) => null
      private '_scenario' (yii\base\Model) => string 'default' (length=7)
      private '_events' (yii\base\Component) => 
        array (size=0)
          empty
      private '_behaviors' (yii\base\Component) => 
        array (size=0)
          empty
```

You can see that `test` is returned as `boolean` and not as string! `true` both time, no matter that I have just b'0' and b'1' in the database, so there is an issue for sure.

**Comment by stratoss** [comment]
Another test:
`var_dump(Demo::find()->asArray()->all());` returns
```
array (size=2)
  0 => 
    array (size=2)
      'id' => string '1' (length=1)
      'test' => string '�' (length=1)
  1 => 
    array (size=2)
      'id' => string '2' (length=1)
      'test' => string '' (length=1)
```

**Comment by RusAlex** [comment]
My  environments:

mysql  Ver 15.1 Distrib 10.0.20-MariaDB
PHP 5.6.10 (cli) (built: Jun 11 2015 08:23:54)

Bug not confirmed.

**Comment by stratoss** [comment]
I'm using mysql 5.5.43 with PHP 5.6.9 and latest yii2 (2.0.x-dev) on a debian machine.

**Comment by stratoss** [comment]
I have found and fixed the issue with pull request #9205 . 0x01 and 0x31 (string '1') are considered as true, otherwise false. It seems the issue is in PHP's (bool) cast function.

**Comment by RusAlex** [comment]
Suppose that it's not Yii issue. And something specific in your
environment. Because on my side everything is OK.

**Comment by stratoss** [comment]
@RusAlex Probably it is because you're using MariaDB which has differences compared with MySQL.

**Comment by RusAlex** [comment]
Have you tried with recent versions of PHP 5.6.x and MySQL version ?

Is this bug still exist?

**Comment by RusAlex** [comment]
MySQL 5.6.24
php 5.6.11

Again everything is ok. One model test attribute value is false and
nother - true.

**Comment by stratoss** [comment]
@RusAlex No, I didn't, because I'm currently using the latest versions my distro provides. The fact is that at least for everyone using those versions (which is everyone using Debian OS) - the bug exists.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/9264

**Comment by RusAlex** [comment]
Was going to test this issue on debain linux.

**Comment by samdark** [comment]
Added some tests (not only for MySQL but for all supported DBs). MySQL ones could be run using

```
phpunit --verbose --filter testBit ActiveRecordTest tests/framework/db/ActiveRecordTest.php
```

**Comment by samdark** [comment]
Passing on travis: https://travis-ci.org/yiisoft/yii2/jobs/73409686

MySQL version there is

```
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2
```

**Comment by samdark** [comment]
@stratoss, @mj4444ru could you run the same test?

**Comment by samdark** [comment]
It seems to fail when using HHVM though: https://travis-ci.org/yiisoft/yii2/jobs/73409690.

@stratoss, @mj4444ru are you on HHVM?

**Comment by mj4444ru** [comment]
samdark, No

**Comment by mj4444ru** [comment]
* Original yii2 code

PHPUnit 4.8-g4b4f866 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.5.9-1ubuntu4.11 with Xdebug 2.2.3
Configuration:	/home/ssufa2/...yii2/phpunit.xml.dist

F

Time: 1.11 seconds, Memory: 9.75Mb

There was 1 failure:

1) yiiunit\framework\db\ActiveRecordTest::testBit
Failed asserting that true matches expected false.

/home/ssufa2/...yii2/tests/framework/db/ActiveRecordTest.php:831
/usr/bin/phpunit:46

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.

**Comment by mj4444ru** [comment]
* with patches

PHPUnit 4.8-g4b4f866 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.5.9-1ubuntu4.11 with Xdebug 2.2.3
Configuration:	/home/ssufa2/...yii2/phpunit.xml.dist

.

Time: 1.09 seconds, Memory: 9.50Mb

OK (1 test, 2 assertions)

**Comment by samdark** [comment]
@mj4444ru which of two pull requests have you tested?

**Comment by RusAlex** [comment]
Also have failling environment.

mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (i686) using
readline 6.3

PHP 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:47:09)

Debian 8.1

**Comment by samdark** [comment]
@RusAlex could you test both pull requests on it?

**Comment by RusAlex** [comment]
@samdark it seems the problem in PDO driver.

I've just tested the broken environment but with different pdo driver:
Client API version => mysqlnd 5.0.11-dev

And tests passed.

But with another PDO driver:
Client API version => 5.5.44

it fails. So I would search to understand nature of this bug.

**Comment by RusAlex** [comment]
So it's recommendation to users install package php5-mysqlnd as temporary fix.

**Comment by RusAlex** [comment]
Someone already did it https://bugs.php.net/bug.php?id=70132

**Comment by samdark** [comment]
You can https://bugs.php.net/.

**Comment by Faryshta** [comment]
this is a php bug but if we can patch it, it would be on http://www.yiiframework.com/doc-2.0/yii-db-columnschema.html#phpTypecast()-detail this method.

**Comment by RusAlex** [comment]
https://bugs.php.net/bug.php?id=70170

**Comment by samdark** [comment]
Fixed. Thanks everyone for testing, ideas and PRs. Great job.

**Comment by Faryshta** [comment]
@samdark i still think this is an incomplete fix. If you try

 if ($model->value) {
    // problem
}

**Comment by stratoss** [comment]
I've just updated my yii2 to @dev and tested - the bug is fixed on my machines, false is returned as expected. Thank you!

**Comment by RusAlex** [comment]
PHP still has unconventional behavior. One mysql driver cast 0x00 to
string "0" but another driver do not cast it at all. Suppose they will
change it in future to one conventional way.

**Comment by samdark** [comment]
@Faryshta nope. I've tested it properly. It's OK.

**Comment by samdark** [comment]
@RusAlex, yes. There was positive response to your bug report so I think it will be fixed one day.

**Comment by Faryshta** [comment]
@samdark http://3v4l.org/fchVS here you can see a quick test and see the issue i am talking about.

**Comment by samdark** [comment]
@Faryshta but the check already takes it into account.

**Comment by samdark** [comment]
http://3v4l.org/bsqeR

**Comment by Faryshta** [comment]
@samdark again, as I said this is a half measure because it will work for the 'check' format but it will fail everywhere else.

**Comment by samdark** [comment]
Nope. It's returning boolean. Why should it fail elsewhere? Where exactly?

**Comment by Faryshta** [comment]
i know its returning boolean on the `check` format, thats not my point.

even if the gridview says the value is false when you do `if ($model->attribute) { /* here is the issue */ }`. I am talking about using this attribute OUTSIDE the formatter

**Comment by samdark** [comment]
I still don't get it... Can you put up a failing unit test together?

**Comment by RusAlex** [comment]
It was related #6233

**Comment by RusAlex** [comment]
Sumary: 

There are 2 mysql drivers in PHP world:

libmysql - not recommended (old)
mysqlnd - mysql native driver (newer) recommended

They handle BIT column differently. 
libmysql - returns raw bit value 
mysqlnd - cast it to INT

**Comment by Faryshta** [comment]
@samdark @RusAlex my proposition is to use the `phpTypeCast()` method to turn the raw bit value to an int like mysqlnd does to make them both compatible while using yii2.

**Comment by samdark** [comment]
@Faryshta it does exactly that: https://github.com/yiisoft/yii2/commit/972165ccec17027cdfaf1a4ac54677a3b5bf661a#diff-f433cbb7fc8129ef7be8ff5f34f66e02R137. Casts return value for both drivers to boolean.

**Comment by Faryshta** [comment]
@samdark only for the check format. Everywhere else its a different value

**Comment by samdark** [comment]
Where exactly? Can you provide a test case where it fails?

**Comment by Faryshta** [comment]
http://3v4l.org/fchVS  here. 

And again I am talking about using the attribute, not the check format

**Comment by cebe** [comment]
@Faryshta the AR attribute will contain a boolean because of the typecast applied. the problem you describe exists with using normal db queries and asArray however...

**Comment by samdark** [comment]
We definitely can't affect normal DB queries.

**Comment by Faryshta** [comment]
I get your point now.
