### ISSUE TITLE
Не могу пройти капчу, на чистом basic приложении.

### ISSUE THREAD

**Issue by Ineigo** [yiisoft/yii2#9007]
На днях установил гит, композер, установил, по описанию в офф документации yii2 basic. Зашел в форму отправки сообщения и попытался отправить форму. Но валидация капчи не проходит, типо неверно ввел...

Совсем ни чего не менял.

Среда запуска: php 5.6, сервер запускал из папки web командой php -S localhost:8888, приложение запускал в трех браузерах: Хром, ИЕ, Мозила.

Подскажите с чем это может быть связано и как решить проблему?

![yii2_01](https://cloud.githubusercontent.com/assets/10618646/8511894/23bc497c-2332-11e5-876e-5ab7ef68b3f1.jpg)

**Comment by ismorodin** [comment]
Попробуй почитать здесь https://github.com/yiisoft/yii2/issues/1456

**Comment by githubjeka** [comment]
@ismorodin тут не связано с ajax валидацией.

Тут при `clientValidateAttribute =false` всё успешно проходит, а как только при `clientValidateAttribute=true` (как по умолчанию в basic приложении для contact формы) уже не работает.

**Comment by githubjeka** [comment]
@Ineigo а какие-нибудь ошибки есть в debug браузера?

**Comment by Ineigo** [comment]
В том и дело, что ни ошибок, ни запросов, ни чего... Запрос выполняется только при нажатии на картинку(смена кода капчи)
@ismorodin Спасибо но я не дружу с английским, завтра попробую перевести)

**Comment by githubjeka** [comment]
Запрос не должен отправляться. 

Каптча хранится в виде **hash** числа(как сумма кодов каждого символа), это число получает на стороне сервера и передаётся в html. При вводе каптчи **в браузере** с помощью js ( [charCodeAt](http://www.w3schools.com/jsref/jsref_charCodeAt.asp)) получается число - сумма юникодов каждого символа, которые вы ввели. Эта сумма сравнивается с hash и если это утверждение неверно, то вы получаете ошибку, что капчта введена неверно. 

Поэтому очень странно, что у вас всегда hash не равен верной каптче.

**Comment by Ineigo** [comment]
Попробовал на работе тоже сделать, у меня капча прошла валидацию...
Немного пошалив со средой запуска(сервер локальный) свелся к выводу:
"Если запускать yii 2 приложение из консоли командой php -S localhost:8888, то капча не проходит валидацию. Если пошаманить с Denwer настройками apache2 на нужную папку, то капча проходит валидацию." 
Может кто сможет мне подсказать почему так происходит..?
П.С.:  Просто удобно запускать (php -S localhost:8888) из папки yii2, когда только изучаешь.

**Comment by githubjeka** [comment]
Что значит ?

>Если пошаманить с Denwer настройками apache2 на нужную папку, то капча проходит валидацию

**Comment by Ineigo** [comment]
Ну просто добавить виртуальный хост на папку web.
Такой вывод, получается(php -S localhost):
C:\WebServers\home\yii2-tutorial\yii2-app-advanced\frontend\web>php -S localhost
:8888
PHP 5.6.10 Development Server started at Mon Jul 06 10:08:52 2015
Listening on http://localhost:8888
Document root is C:\WebServers\home\yii2-tutorial\yii2-app-advanced\frontend\web

Press Ctrl-C to quit.
[Mon Jul 06 10:09:10 2015] 127.0.0.1:62105 [200]: /
[Mon Jul 06 10:09:10 2015] PHP Fatal error:  Uncaught exception 'yii\base\ErrorE
xception' with message 'Unknown: open(/tmp\sess_sl5rsigflr15ggukrqdbjt4k93, O_RD
WR) failed: No such file or directory (2)' in Unknown:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Unknown: open(/..
.', 'Unknown', 0, Array)
#1 {main}
  thrown in Unknown on line 0
[Mon Jul 06 10:09:10 2015] 127.0.0.1:62106 [200]: /assets/77e2aad/css/bootstrap.
css
[Mon Jul 06 10:09:10 2015] 127.0.0.1:62107 [200]: /css/site.css
[Mon Jul 06 10:09:10 2015] 127.0.0.1:62108 [200]: /assets/3bd60e11/jquery.js
[Mon Jul 06 10:09:10 2015] 127.0.0.1:62109 [200]: /assets/8e537632/yii.js
[Mon Jul 06 10:09:10 2015] 127.0.0.1:62110 [200]: /assets/77e2aad/js/bootstrap.j
s
[Mon Jul 06 10:09:11 2015] 127.0.0.1:62111 [200]: /index.php?r=debug%2Fdefault%2
Ftoolbar&tag=559a29969d9c5
[Mon Jul 06 10:09:11 2015] 127.0.0.1:62112 [200]: /favicon.ico
[Mon Jul 06 10:09:11 2015] 127.0.0.1:62113 [200]: /favicon.ico
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62114 [200]: /index.php?r=site%2Fcontact
[Mon Jul 06 10:09:12 2015] PHP Fatal error:  Uncaught exception 'yii\base\ErrorE
xception' with message 'Unknown: open(/tmp\sess_sl5rsigflr15ggukrqdbjt4k93, O_RD
WR) failed: No such file or directory (2)' in Unknown:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Unknown: open(/..
.', 'Unknown', 0, Array)
#1 {main}
  thrown in Unknown on line 0
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62115 [200]: /assets/77e2aad/css/bootstrap.
css
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62116 [200]: /css/site.css
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62117 [200]: /assets/3bd60e11/jquery.js
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62118 [200]: /assets/8e537632/yii.js
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62119 [200]: /assets/8e537632/yii.validatio
n.js
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62120 [200]: /assets/8e537632/yii.captcha.j
s
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62121 [200]: /assets/8e537632/yii.activeFor
m.js
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62122 [200]: /assets/77e2aad/js/bootstrap.j
s
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62123 [200]: /index.php?r=debug%2Fdefault%2
Ftoolbar&tag=559a29988d47c
[Mon Jul 06 10:09:12 2015] 127.0.0.1:62124 [200]: /index.php?r=site%2Fcaptcha&v=
559a2998974a6
[Mon Jul 06 10:09:12 2015] PHP Fatal error:  Uncaught exception 'yii\base\ErrorE
xception' with message 'Unknown: open(/tmp\sess_sl5rsigflr15ggukrqdbjt4k93, O_RD
WR) failed: No such file or directory (2)' in Unknown:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Unknown: open(/..
.', 'Unknown', 0, Array)
#1 {main}
  thrown in Unknown on line 0
[Mon Jul 06 10:09:13 2015] 127.0.0.1:62125 [200]: /favicon.ico
[Mon Jul 06 10:09:13 2015] 127.0.0.1:62126 [200]: /favicon.ico
[Mon Jul 06 10:14:32 2015] 127.0.0.1:62159 Invalid request (Unexpected EOF)

**Comment by githubjeka** [comment]
У меня проблем с запуском приложения через `php -S localhost:8888` не возникает, и captcha отрабатывает нормально.

**Comment by githubjeka** [comment]
И судя по логу ошибки, у вас там что-то с настройками сессии в `php.ini` ...

**Comment by Ineigo** [comment]
А можешь прислать php.ini, я поковыряюсь посмотрю что не так.

**Comment by githubjeka** [comment]
https://github.com/php/php-src/blob/master/php.ini-development

**Comment by Ineigo** [comment]
Оо спасибо, замена php.ini исправила проблему.
П.С.: обновлял php до 5.6 в Denwer'e от туда и пошла проблема 
Спасибки огромные, что не бросили в беде )))

**Comment by githubjeka** [comment]
Issue can be closed

6 июля 2015 г., 12:42 пользователь Kira <notifications@github.com> написал:
