### ISSUE TITLE
Yii2 v:2.0.4 AssetManager Invalid Config Exception

### ISSUE THREAD

**Issue by betatesty** [yiisoft/yii2#9009]
Clean and fresh install via composer or archive (init and migrate pass great.. (some issue with composer package with bower refused by composer each day have a différent issue (but often lock install..) that's is about install first step...

when we reach the stage init.. migrate..
We are lock by
1) runtime/logs (folder not created)...
and after...
no writable folder /frontend/web/assets.
chmod is right 777
chown is user apache

Impossible to go over

Install is really for who want to get a congratulation... like for his quest for the Holy Grail

**Comment by samdark** [comment]
Re-checked. Yii tries to create logs dir automatically. Same about assets.
