### ISSUE TITLE
Simple inequality queries do not work

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#9013]
These do not work. They are so simple, you would think they would work. It is so difficult to express an inequality query in Yii. I wonder why something so simple is so hard to do? Not only that, but they fail silently and return 0 or 1 results without giving any indication of an error.

    Cron::findAll('status <= 1');

    # SELECT * FROM `cron` WHERE `id`='status <= 1'

    Cron::findAll(['status <= 1']);

    # SELECT * FROM `cron` WHERE `id`='status <= 1'

    Cron::findAll(['<=', 'status', 1]);

    # SELECT * FROM `cron` WHERE `id` IN ('<=', 'status', 1)

Even the documentation hints that a `findAll()` is turned into a `where()`.

```
// find customers whose age is 30 and whose status is 1
$customers = Customer::findAll(['age' => 30, 'status' => 1]);

// the above code is equivalent to:
$customers = Customer::find()->where(['age' => 30, 'status' => 1])->all();
```

**Comment by trejder** [comment]
I'm maybe missing something awfully obvious, but how in the hell:

    Cron::findAll('status <= 1');

can generate you query like:

    SELECT * FROM `cron` WHERE `id`='status <= 1'

What does this:

    `id`='status <= 1'

mean? How does it appear in your query, if call to `Cron::findAll()` **does not contain `id` column at all**? Form where Yii adds this column to your query in your opinion?

Sorry, if asking for something trivial, but I'm out of coffee for today...

**Comment by nineinchnick** [comment]
@trejder `id` is probably defined as primary key for `Cron` model. Please calm down a bit.

**Comment by nineinchnick** [comment]
From the [ActiveRecord.findAll()](http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findAll%28%29-detail) description:

>   The method accepts:
>    *  a scalar value (integer or string): query by a single primary key value and return an array containing the corresponding record (or an empty array if not found).

In general, it works with primary key values. The docs doesn't mention it _does not_ support the standard array format for `Query.where()`.

**Comment by trejder** [comment]
I'm cool! :> But, thanks for pointing out, that my emotions went a bit to far! :>

I don't have any example using `findAll` right now handy. So, maybe I'm wrong. But, I still claim, that conditions like `WHERE id='status <= 1'` are at least weird. I have never run into something like this (though I'm pretty SQL newbie) and I still wonder, what purpose is in condition like that?

**Comment by nineinchnick** [comment]
@trejder you misunderstand the issue here. `findAll()` by default works only with primary key but it's not obvious from the method name itself. So if one tries to pass different conditions it's behavior is unexpected.

In the example you reference, the whole condition is treated as PK value and it's not a valid query.

**Comment by kidol** [comment]
@starrychloe 
>It is so difficult to express an inequality query in Yii.

Are you aware yet of `ActiveRecord::findBySQL()`? You can also use custom compare operator when using `where()`.

I think the doc is pretty clear in regards to `findAll`.

**Comment by cebe** [comment]
> Cron::findAll('status <= 1');
> # SELECT * FROM `cron` WHERE `id`='status <= 1'

There is an issue with the documentation, `findAll()` does only understand arrays as input. This has to be fixed.

> Cron::findAll(['status <= 1']);
> # SELECT * FROM `cron` WHERE `id`='status <= 1'
> Cron::findAll(['<=', 'status', 1]);
> # SELECT * FROM `cron` WHERE `id` IN ('<=', 'status', 1)

This is the correct result, the docs for `$condition` say that it is a ["Primary key value or a set of column values".](http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#findAll%28%29-detail)

`findAll()` is not meant to be used like this, if you want to express any complex condition, just use `Cron::find()->where(...)->all()`.

**Comment by cebe** [comment]
> There is an issue with the documentation, findAll() does only understand arrays as input. This has to be fixed.

Ah not there is also no problem in this case, it is clearly documented:

> The method accepts: a scalar value (integer or string): query by a single primary key value and return an array containing the corresponding record (or an empty array if not found).
> ...
