### ISSUE TITLE
Add case-insensitive validation in UniqueValidator and ExistValidator (for PostgreSQL)

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#9014]
Currently there seems to be no way to validate case-insensitive unique text values using UniqueValidator when working with PostgreSQL. This is particularly important in cases like detecting duplicate user names and emails during user registration. It would be good to provide a `caseSensitive` option as in as in Yii 1.0 to accommodate both case-sensitive and insensitive situations.

**Comment by Faryshta** [comment]
There is a not so simple way to do it already.

Lets say you have a `User` model with an `username` attribute.

```php
public function getUsernameLowercase()
{
    return strtolower($this->username);
}

public function rules()
{
    return ['username', 'unique', 'targetAttribute' => ['usernameLowercase' => 'lower(username)']];
}
```

**Comment by YasserHassan** [comment]
Thank you for the tip @Faryshta. `ExistValidator` has the same behavior too so I'll add it to the issue title.

**Comment by samdark** [comment]
I don't think it makes sense to abstract it.
