### ISSUE TITLE
how to access base url of yii2 in javascript 

### ISSUE THREAD

**Issue by kalpesh4** [yiisoft/yii2#9015]
hello guys,
I want base url in my javascript .I tried embed php code to javascript in registerJs() method  in main.php
But I cant get baseUrl in another page or another asset file.Pliz guide me for same.
Thanks in advance.

**Comment by Alex-Code** [comment]
Please use the forums for help on using the framework, [Yii 2.0 Forum](http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/)
This is the issue tracker for bugs in Yii.

**Comment by kalpesh4** [comment]
could u help that with which keyword I should find solution for above problem.Pliz guide.
