### ISSUE TITLE
Setting up extra actions for RESTful controllers and limiting to only certain method types

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2#9022]
Hi,

Using yii\rest\UrlRule to set up the basic API routes which works very well and have created my "user" controller to use with this.
I have created extra actions within the class though and would like to limit which method types can access it.

For example, the "check" action I would like to only be accessible via GET and "signin" I would like to only be accessible via POST.
Is there a way to do this?

If I create the route 'POST api/user/signin' => 'api/user/signin' it is still accessible via GET, PUT, etc.
If I create the route 'GET api/user/check' => 'api/user/check' it is still accessible via POST, PUT, etc.

Thanks,
Gary

**Comment by garyrutland** [comment]
In the short term I have been able to achieve this by doing the following:

    use yii\web\MethodNotAllowedHttpException;

    ...

    if (Yii::$app->request->isPost === false) {
        throw new MethodNotAllowedHttpException('Method Not Allowed. This url can only handle the following request methods: POST.');
    }

Would be nice if this could be done through the routing though at some point.

**Comment by cebe** [comment]
can you show the full route config?

**Comment by noecs** [comment]
I encountered a problem consistent with this. It would be great if the request method could be specified by routing, but I have not found a similar answer so far. This means that I need to judge and throw errors in every controller / method. The following is my routing configuration:
```php
<?php
return [
    ...
    'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false,
            'showScriptName' => false,
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'auth',
                    'extraPatterns' => [
                        'POST register' => 'register',
                    ],
                ],
            ],
        ],
    ...
];
```

**Comment by cebe** [comment]
you can use https://www.yiiframework.com/doc/api/2.0/yii-filters-verbfilter for this.
