### ISSUE TITLE
FileValidator error on csv file

### ISSUE THREAD

**Issue by shamyyl** [yiisoft/yii2#9028]
I am using a rule
```php
            [
                ['fileInstance'],
                'file',
                'extensions' => 'csv, ppt, pptx, pdf, xls, xlsx, doc, docx, pps, ppsx'
            ];
```
but when i am trying to upload file with csv extension, validation return false and error on this field

**Comment by cebe** [comment]
`$checkExtensionByMimeType` is true by default, that may cause the error. what is the validation error you get?

**Comment by shamyyl** [comment]
setting $checkExtensionByMimeType to false solved the problem. Thanks
