### ISSUE TITLE
how to download PDF or any file from yii2 when pjax is ON

### ISSUE THREAD

**Issue by GAjay** [yiisoft/yii2#9029]
I have tried to download file by the help of my database field some it was work but when pjax is on that it return me a text string as like this  
![screenshot from 2015-07-06 13 10 04](https://cloud.githubusercontent.com/assets/6947656/8544045/67e004ca-24bf-11e5-8556-e310dd0f2c61.png)

**Comment by cebe** [comment]
you should disable pjax for that specific link.

**Comment by usualdesigner** [comment]
Use 'data-pjax=0' with your link
