### ISSUE TITLE
invalid redirect_uri for oauth 2.0 linkedin authentication error

### ISSUE THREAD

**Issue by gaikwadbhagyashri** [yiisoft/yii2#9030]
I am experiencing same issue. Url I am using is :https://www.linkedin.com/uas/oauth2/authorization?response_type=code&client_id=77plxpppupqbh2&client_secret=IQvZYDZTlYV7PtoI&redirect_uri=http://ws-100945:9080/ArtisWeb/index.html&scope=r_basicprofile 
 I recheck everything but, still experiencing same error as:
 invalid redirect_uri. This value must match a URL registered with the API Key.

Could anyone guide me on same please?

**Comment by samdark** [comment]
Please provide more info: what are you trying to do? Are you using authclient extension?

**Comment by gaikwadbhagyashri** [comment]
issue has been resolved
