### ISSUE TITLE
Need help in fetching particular company's updates from linkedIn to our intranet application

### ISSUE THREAD

**Issue by gaikwadbhagyashri** [yiisoft/yii2#9031]
I am trying to bring updates from linkedIn's company profile page (or test company ,say DevTestCo-url:https://www.linkedin.com/company/devtestco) into our intranet website so as it displays company related feeds/updates on homepage same as rss feeds.

Could anyone please guide me by sharing relevant url for java/jsp/json code or
REST API to implement the same.

![home](https://cloud.githubusercontent.com/assets/13217623/8544441/f2229fd2-24c2-11e5-81af-ab21ae524af0.png)

In image , the way I have pulled twitter feeds ,same way I want to display linkedin feeds.

Thanks in advance!

**Comment by klimov-paul** [comment]
@gaikwadbhagyashri, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by gaikwadbhagyashri** [comment]
Not able to post question, giving "Not allowed" error. Could you try to post it behalf of me and share link for same?

**Comment by samdark** [comment]
"Not allowed" at the http://yiiframework.com/?
