### ISSUE TITLE
Improve scenarios usage docs

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#9032]
The default scenario is implemented via constant `SCENARIO_DEFAULT`. However, in multiple docs pages I saw scenarios are used as raw strings, for example: `'default'`, `'update'`. This is not right and can lead to errors. I saw many developers use just raw strings.

**Comment by githubjeka** [comment]
:+1:

**Comment by githubjeka** [comment]
@arogachev send PR, there is nothing to discuss :)
