### ISSUE TITLE
Error when compare two models

### ISSUE THREAD

**Issue by nepster-web** [yiisoft/yii2#9036]
Why i cant compare two models which are using behaviors ?

**Code example:**
```
$one = \frontend\models\Image::findOne(1);
$two = \frontend\models\Image::findOne(2);

if($one == $two) {

}
```

**Model:**
```
class Image extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            \yii\behaviors\TimestampBehavior::className(),
        ];
    }
}
```

**Result:**
```
Nesting level too deep - recursive dependency?
```

**Comment by samdark** [comment]
`==` compares the objects' contents i.e. it goes recursively through all the properties of the object including behaviors, sub-objects etc. Overall, it's not a good idea to compare it like that.

**Comment by nepster-web** [comment]
Are you sure?

http://php.net/manual/ru/language.oop5.object-comparison.php

**Comment by cebe** [comment]
you should use equals to compare two active records:
```
if ($one->equals($two)) {

}

**Comment by samdark** [comment]
@nepster-web quote from that page:

> When using the comparison operator (==), object variables are compared in a simple manner, namely: Two object instances are equal if they have the same attributes and values, and are instances of the same class.

**Comment by lynicidn** [comment]
:+1: cool ) i don't know it
$class = $model::class;
if ($model1 instanceof $class)

**Comment by nepster-web** [comment]
Great! Thank. it's just work! =)
