### ISSUE TITLE
Sort for group by in ActiveQuery?

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#9039]
How can i do, sort for group by with ActiveQuery? like that;
```sql
GROUP BY q.create_time DESC, `q`.`user_id` ASC
```
I looked groupBy function, but i couldn't see anything for that... and i can't write like this;
```php
->groupBy('q.create_time DESC,q.user_id')
->groupBy(['q.create_time' => SORT_DESC,'q.user_id'])
```

I'm writing to here because i couldn't see property in groupBy function.
http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#groupby

if anyone wants my sql code, is here;
```sql
SELECT COUNT(q.id) AS `count`,
q.user_id,
q.treatment_id,
 @curRank := @curRank + 1 AS `rank`
FROM (
SELECT 
qanswers.id,
qanswers.user_id,
qanswers.create_time,
qa.treatment_id
FROM qanswers
INNER JOIN `profile` ON profile.user_id = qanswers.user_id AND profile.location = 63
INNER JOIN `qa` ON qa.id = qanswers.qa_id AND qa.treatment_id = 3
GROUP BY qanswers.user_id DESC, `qa`.`treatment_id`) `q`
JOIN (
SELECT @curRank := 0) r
GROUP BY q.create_time DESC, `q`.`user_id`
```
it's working on the mysql.

**Comment by cebe** [comment]
you can use an Expression to write plain SQL: `->groupBy([new \yii\db\Expression('q.create_time DESC', 'q.user_id')`.
