### ISSUE TITLE
Add an option to delete file after it was sent with Response::sendFile

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#9044]
Example. Lets say user can upload and later upload more or remove uploaded files from the server.
A button to download all currently uploaded files in a zip archive can be useful. Upon pressing this button server must create a zip archive and send it to user. But since zip archive is created on the fly and is needed only while its download lasts that zip archive must be deleted once the download is finished. Currently this cannot be done in Yii2 by the script that creates zip archive and needs to be implemented as an additional argument of Response::sendFile().

Alternatively there should be an application event (like EVENT_AFTER_REQUEST) which is triggered AFTER the response has been sent so that handler of that event can delete this zip archive.

**Comment by cebe** [comment]
There already is an event like that: http://www.yiiframework.com/doc-2.0/yii-web-response.html#EVENT_AFTER_SEND-detail does that solve your problem?

**Comment by PowerGamer1** [comment]
Well, it does partially - using this event I can run my handler after the file was sent. But there is another problem I found upon inspecting the code of Response::sendFile(). That function supports the HTTP range header, which must be disabled in my use case. Several users on the site can work with files simultaneously (upload new files, remove already uploaded). So two different presses of a "download zip archive" button may return a zip archive with different content (but zip archive can be of the same size). As a result if for some reason user download is interrupted and he tries to restart it, sendFile() will allow it but zip archive passed to sendFile() might be of the same size and DIFFERENT content.

So at the very least an option to disable HTTP range headers in sendFile() must be added. Alternatively, an option to delete a file after send - and in this case HTTP range headers should be always disabled since if the file deleted it wouldn't be possible to resume its download.

**Comment by cebe** [comment]
not sure if the case is valid. if you provide a URL it should return the same content in subsequent GET request unless it was removed. So you can just create different urls for different zips.
As a workaround to disable content range you may remove the Content-Range header after calling send*File function.

**Comment by PowerGamer1** [comment]
> if you provide a URL it should return the same content in subsequent GET request unless it was removed

Not at all - a regular HTML page that displays current time is being retrieved form the same url, yet the content is different every time.

As for the Content-Range  workaround, yes, I can use that.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
