### ISSUE TITLE
Order findAll() by a relation?

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2#9045]
Not sure if this is possible, but I'm building a voting system for feature requests and would like to show the list of features ordered by the amount of votes it has been given.

    // Feature model
    public function getVote()
    {
        return $this->hasMany(FeatureVote::className(), ['featureId' => 'featureId']);
    }

    // FeatureVote model
    public function getFeature()
    {
        return $this->hasOne(Feature::className(), ['featureId' => 'featureId']);
    }

    // Find all
    Feature::find()->all();

When doing Feature::find()->all(); is there a way of ordering by the COUNT() of the getVote() relation?

Thanks,
Gary

**Comment by cebe** [comment]
You may join against a subquery that selects the counts per featureId but please use the [forum](http://www.yiiframework.com/forum/) to ask questions, github is for bug tracking.
