### ISSUE TITLE
Any PHP error/warning in Response::EVENT_AFTER_SEND makes PHP and Apache hang

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#9046]
How to reproduce: add the following in any controller action:
```
\Yii::$app->response->on(\yii\web\Response::EVENT_AFTER_SEND, function($event) { unlink('file that does not exist'); });
return \Yii::$app->response->sendFile('some file that DOES exist');
```
After the first request to that action Apache/PHP will hang and Apache stops responding to any subsequent requests to any other action. In case it matters tested under Windows 8.1 running IE11.

**Comment by cebe** [comment]
reproduced, it is filling my apache log with a bunch of log messages. after 10sec. I get about 800MB of logs...

**Comment by cebe** [comment]
Fixed, thanks for reporting!
