### ISSUE TITLE
Custom form submit handler is fired twice when using ActiveForm

### ISSUE THREAD

**Issue by Coksnuss** [yiisoft/yii2#9048]
The title pretty much describes it. Here is an example:

ViewFile:

``` php
<?php
use yii\bootstrap\ActiveForm;

ActiveForm::begin([
    'enableClientScript' => true, // If this is set to false, everything works fine
    'options' => ['id' => 'myform'],
]);
echo Html::submitButton();
ActiveForm::end();
?>
```

With this JavaScript code:

``` js
$('#myform').submit(function(e) {
        alert("I get called twice");
});
```

We already had a similar issue in #6642 which sadly only fixed an effect of that bug, not the cause.
The first call to the callback is through the form itself, the second call happens through yii.activeForm.js: https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L525

**Comment by cebe** [comment]
for an ActiveForm you better add custom handlers for the events added by yii:

```js

var $form = $('#comment-form');
$form.on('beforeSubmit', function() {
    // your code
   // optionally return false to stop it.
});

**Comment by Coksnuss** [comment]
Thanks for that workaround.

However, it requires the developer to use specialized JavaScript code for a task that is not releated to yii at all. It seems quite unobvious to me to use such an approach. But if there isn't an appropriate solution to it, I can life with that too.

**Comment by pana1990** [comment]
@cebe maybe it should be documented in https://github.com/yiisoft/yii2/blob/master/docs/guide/input-forms.md ?¿

**Comment by dynasource** [comment]
this issue pops up again when try fix multiple submissions with button event handlers (like https://github.com/yiisoft/yii2/issues/10498#issuecomment-167775881)

**Comment by dynasource** [comment]
duplicate #4985
