### ISSUE TITLE
Anonymous config array break application

### ISSUE THREAD

**Issue by zlakomanoff** [yiisoft/yii2#9050]
Hello eweryone, i make this
```
$app = new Application([
    'id' => 'Test',
    'basePath' => dirname(__DIR__)
    ]);
$app->run();
```
and get "Not Found (#404)"

if i put configuration array to the file, and this file put to some directory

```
$conf = require(__DIR__ . '/wtf/config.php');
$app = new Application($conf);
$app->run();
```

its working good. This is feature or bug?

>
PHP Version 5.6.10
>

**Comment by samdark** [comment]
I guess that's because `__DIR__` is relative to current file.
