### ISSUE TITLE
Unknown component ID: elasticsearch

### ISSUE THREAD

**Issue by ceovishnu** [yiisoft/yii2#9058]
I have just recently included Elastic Search widget in Yii2.
but i am getting the below error in Elastic Search.

Unknown component ID: elasticsearch

let me know any suggestion for the same.

**Comment by ceovishnu** [comment]
@kartik-v I have just recently included Elastic Search widget in Yii2.
but i am getting the below error in Elastic Search.

Unknown component ID: elasticsearch

let me know any suggestion for the same.

**Comment by ceovishnu** [comment]
@samdark 

 I have just recently included Elastic Search widget in Yii2.
but i am getting the below error in Elastic Search.

Unknown component ID: elasticsearch

let me know any suggestion for the same.

**Comment by cebe** [comment]
please stop spamming. read the docs: https://github.com/yiisoft/yii2-elasticsearch#configuration and add the component to your config.
Next time please use the forum to ask questions.
