### ISSUE TITLE
ErrorHandling

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9059]
I get a notice when displaying an error:

Notice: Undefined index: args in E:\xampp\htdocs\dmn\wc\6\dev\vendor\yiisoft\yii2\views\errorHandler\exception.php on line 373

The reason:
* when no $args are provided in the stacktrace, $arg is NULL instead of a array and it will show errors notices.

Solution:
Make $args=[] in https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L262

**Comment by cebe** [comment]
can you send a PR with a fix?

**Comment by dynasource** [comment]
I will
