### ISSUE TITLE
Migration in php7 environment

### ISSUE THREAD

**Issue by jerryhsia** [yiisoft/yii2#9060]
Yii Version: 2.0.4
PHP Version: 7.0.0alpha2

**Comment by jerryhsia** [comment]
PHP Warning 'yii\base\ErrorException' with message 'fwrite(): supplied resource is not a valid stream resource'

in /Users/Jerry/Develop/PHP/sdk/vendor/yiisoft/yii2/helpers/BaseConsole.php:697

**Comment by klimov-paul** [comment]
?

**Comment by cebe** [comment]
how are you running the command?

**Comment by cebe** [comment]
may be related to #6853

**Comment by dynasource** [comment]
I can confirm this error in Php7 alpha2

**Comment by jerryhsia** [comment]
`yii migration`

**Comment by cebe** [comment]
I had the same issue with an old master build, pulling the latest php master solved it for me...

**Comment by jerryhsia** [comment]
After the upgrade to php 7.0.0beta1, the issue does not appear.

**Comment by dynasource** [comment]
confirmed
