### ISSUE TITLE
Mysql create index bug

### ISSUE THREAD

**Issue by sebathi** [yiisoft/yii2#9063]
There is a bug on MySql where creating indexes with create index command will rename your database to lowercase.

https://bugs.mysql.com/bug.php?id=48875

**Comment by cebe** [comment]
how is that related to yii?

**Comment by samdark** [comment]
Could be fixed via pull request proposed, I think.

**Comment by sebathi** [comment]
It's not related to Yii, but Yii is using that functionality so updating it will let users that use camelcase tablenames don't have to take care of this on their own.
