### ISSUE TITLE
With DataGrid option $showHeader=false, "selectedRows" not work.

### ISSUE THREAD

**Issue by afernandes465** [yiisoft/yii2#9074]
In this doc http://www.yiiframework.com/doc-2.0/yii-grid-checkboxcolumn.html we have: 
"Users may click on the checkboxes to select rows of the grid. The selected rows may be obtained by calling the following JavaScript code:
var keys = $('#grid').yiiGridView('getSelectedRows');"

With option "$showHeader=false", this JavaScript always result in null.

Someone cound check please.
Thanks.

**Comment by Faryshta** [comment]
Also I would like to add that such method must work from among the columns not the entire grid in case there are two Checkbox Columns.

Sadly that won't be backwards compatible.

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/3ee89ac42ca103544f9ef65a9532c6e667c768ca
