### ISSUE TITLE
Make AR relations case insensitive (or add option to do so)

### ISSUE THREAD

**Issue by joe-meyer** [yiisoft/yii2#9077]
I'm currently experiencing a problem where I have a case insensitive database. What I've found is that if I attempt to join from something that has a different case in one table, than the table I'm trying to relate to, I end up missing records. The database returns this records, the problem appears to be when the bucketing process happens. 

I wonder if we could add something to either the models or to the query builder which would allow these relations to be specified as case insensitive, and then when we compare the buckets to the model keys we could simply do a case insensitive key compare instead of a case sensitive `isset($buckets[$key])`

An XDebug variable list showing the problem (notice I have `s1` and `S1` on the related side but I only have `S1` on the primary model side of the relation):
![image](https://cloud.githubusercontent.com/assets/1292766/8623886/11a5a5e8-2702-11e5-94b4-140385503c92.png)

**Comment by nineinchnick** [comment]
What DB is it? Can't you define your relation names all lowercase/uppercase? Adding such options would probably require a lot of conditions and would be rarely used (small gain).

**Comment by MeyerJL** [comment]
@nineinchnick I'm not sure what you mean by defining my relation names all lowercase/uppercase? the `s1`/`S1` are values returned by one of the fields defined in the relationship. In my scenario I'm using an ODBC driver for a Progress OpenEdge database, but I imagine that this issue is completely valid in other databases as well.

**Comment by MeyerJL** [comment]
So I just confirmed the same issue on MySQL too. Here's a simple example to replicate it:

MySQL dump: http://pastebin.com/cvabLjaM
`Domain.php` model: http://pastebin.com/yFnSJMgc
`User.php` model: http://pastebin.com/xvMZ6rj9

Now, if you run `SELECT * from User WHERE domain = 's1'` against the database you'll notice that the database returns 4 users (billy, Genia, george, joe). However, when you run the `Domain::listDomainUsers('s1')` you'll notice that the related `users` only contains the 3 users that exactly match the case of the domain record in the database. I think this behavior is probably less than desired. If anything I would expect a case insensitive record population to happen, and if someone wanted or needed it to be case sensitive at least they could check it after the fact. Right now I've been unable to find any way to get my records to join up properly, but I'm open to suggestions.

**Comment by cebe** [comment]
do you really think it is a good idea to have case insensitivity on key fields? this could cause a bunch of other problems too...

**Comment by MeyerJL** [comment]
If the database is case insensitive then im not sure  what other problems you're referring to. The foreign and primary keys would also be case insensitive so it's not like those would be an issue. Technically I think this is set at a table level, practically though I'd be happy to set this at a database level. Not having this option means abandoning AR in case insensitive situations and uaing dbal.

**Comment by Sammaye** [comment]
I can see this problem as being database dependent (aside from other problem generated). For example even though MySQL and some other techs have the capacity to do quick, index based, case insensitive searches many techs like MongoDB still do not.

Defining this as a one rule for all in Yii2 could be a serious problem. If it were implemented it would need to be per database layer.

**Comment by Sammaye** [comment]
To add: frankly, it is normally extremely bad design to mix types (upper case and lower case) in this manner (encoding etc etc). Normally you would standardise your data before creating integral relationships on it.

**Comment by MeyerJL** [comment]
In my case im using yii to build a reporting interface for my erp system. Going in and modifying the data simply isnt a feasible option.

**Comment by nineinchnick** [comment]
What about wrapping the FK columns in functions to normalize the case? In some databases you can even put an index on that. I don't know if Yii would suport that (quoting), it's just a shot.

**Comment by MeyerJL** [comment]
@nineinchnick I thought about that but I wasn't sure that yii would support it, additionally, I'd lose the benefit of an indexed comparison for the query since then I'd end up with something like `WHERE uppercase(domain) = 'S1' and uppercase(username) = 'JOE'`

**Comment by cebe** [comment]
For AR relations these need to be real columns because AR needs to work on them lateron which would not be possible if they are db functions.

**Comment by MeyerJL** [comment]
Anyone have thoughts on adding a function / property to models, which would allow it to identify itself as case sensitive or not?  Then we could have it return false if that model's fields are case sensitive, true for case insensitive, or an array of fields if you need to specify specific fields in the model to be case insensitive and not others. This would provide a robust solution for even edge cases where there are mixed collations across a single database as well as other data sources which might allow you to specify case sensitivity on a field by field level (I'm not aware of any but that doesn't mean there wouldn't be the need in the future)

**Comment by Faryshta** [comment]
I propose this solution

http://pastebin.com/7F8iDL9Z even if the db contains upper and lower cases for the models everything will be a lowercase.

Plus you can mix it with some filters on the `rules()` method to ensure no new uppercase domain is created or assigned.

**Comment by MeyerJL** [comment]
@Faryshta the problem I think with the solution you proposed is that when you use a function on your where clause you remove the advantage of an index. In my environment my tables have 5-10 million records each in them and running a query without an index usually means upwards of 30-60 second queries, it's just not a scalable solution unfortunately I don't feel.

**Comment by Faryshta** [comment]
>  when you use a function on your where clause you remove the advantage of an index. I

what do you mean?

**Comment by joe-meyer** [comment]
To work around the issue for my specific database driver, I modified the `ColumnSchema::typecast()` and my database `Schema::loadColumnSchema()` to check the column collation, and then based on that I either leave the value as is, or I force the value to be `strtoupper()/strtolower()` based on whether or not that column's collation says that it should be case insensitive or not. It's not perfect because this modifies the display value, and it doesn't really address what happens if one column is case sensitive and another isn't when doing a join, but those were both things I felt I could do without.

For anyone interested in seeing my implementation it's over at https://github.com/ExchangeCore/yii2-progress-driver. I'm not sure it's worthy of bringing this idea into the core or not since it's only half thought through at this point but it's an idea nontheless.

**Comment by dynasource** [comment]
> I'm not sure it's worthy of bringing this idea into the core or not since it's only half thought through at this point but it's an idea nontheless.

please feel free to reopen if you have finalized your thoughts about this matter
