### ISSUE TITLE
Yii2 Advanced - Migrate not executing 2nd migration

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2#9080]
I have installed a fresh copy of Yii2 advanced app using composer. It comes with one init migration, which creates the user table in the database.

I then run `yii migrate/create create_admin_table`, open the new migration file, and essentially copy the default init code that yii comes with to create the user table. Only I change user to admin. It is exactly the same, except references to "user" are changed to "admin", and of course the file name itself.

I then run `yii migrate` and it shows I have 2 migrations. I confirm I want to apply them. The console reports it runs the user (init) migration, and reports it creates the table. Then it reports it runs the `create_admin_table` migration, but doesn't indicate it created the table. Looking in the db, it only created the user table. It doesn't report an error or anything.

It appears it runs the 1st migration, and attempts to run the 2nd, but doesn't actually execute the code inside.

I can provide screenshots if it's really necessary, but I think this is fairly simple for anyone to reproduce.

I assume it should run every migration in the list, one after the other (given it is a new migration).

For example, you use Yii to create your own site/script. Say your own "Wordpress". It would have a series of migrations. Now say, you want another site running the same exact system. So you copy over your Yii site to the new server and run migrate, and it should run every migration sequentially, so you can build the exact site again.

**Comment by lynicidn** [comment]
check classname

**Comment by lynicidn** [comment]
u should create migration via yii migrate/create admin_table

**Comment by cebe** [comment]
unable to reproduce, please paste the content of the second file and also its file name.

**Comment by WadeShuler** [comment]
Sorry guys, now I can't get it to reproduce either. This isn't my first use of migrations with Yii... Maybe it was just me at like 2am lol.

@lynicidn The Yii docs show an example of `yii migrate/create create_news_table` so the create in the migration name doesn't matter. And the class name is automatically generated by the migration tool.

Only thing different I did last night, was change a few things in the table it was creating, so it was possibly a slip of the finger. However, the migration tool didn't say there was an error. It just skipped it. I guess this can be closed. I have no idea why it didn't work last night, and now it does..
