### ISSUE TITLE
Form, aftervalidate, stop submitting

### ISSUE THREAD

**Issue by MUTOgen** [yiisoft/yii2#9082]
Hi, i need to stop form submission after form validation
So i use js like this

```
$('#form').on('afterValidate',function(event,messages){
....
return false;
});
```

But this doesn't work. By the way beforevalidate event works fine.
Is there any way to make this work?

**Comment by cebe** [comment]
afaik only beforeSubmit can stop the submission so you have to return false there.

**Comment by SilverFire** [comment]
@cebe is right
