### ISSUE TITLE
[DOC] Routing and URL Creation

### ISSUE THREAD

**Issue by martino1919** [yiisoft/yii2#9086]
In guide in the section "Routing and URL Creation" I believe there is a mistake, the view is missing in example below:

![image](https://cloud.githubusercontent.com/assets/9664016/8639666/93d7c4a2-28e1-11e5-848b-dec203977e2b.png)

**Comment by cebe** [comment]
these are just examples of how the URL **might** look like dependend on the config. you can create a config that includes `view` but this is not necessary.

> Depending on the urlManager configuration, the created URL may look like one of the following (or other format)
> http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html
