### ISSUE TITLE
Relation with condition and link()

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#9088]
Looks like link() method doesn't works correctly if relation defined with condition. Params from condition still empty after link() method called.

**Comment by usualdesigner** [comment]
I want to add some explanation:

For example, the relation defined like that:
```
    public function getImages()
    {
        return $this->hasMany(ImageAttachment::className(), ['owner_pk' => 'item_id'])
            ->onCondition([
                'owner_class' => get_class($this)
            ]);
    }
```

And when I use method link() I want to set value of the 'owner_class' field as well. But it doesn't works.

THe background idea is implement something like Laravel's [Polymorphic Relations](http://laravel.com/docs/5.1/eloquent-relationships#polymorphic-relations)

**Comment by lynicidn** [comment]
$item->owner_class = 'blabla';
$owner->link('images', $item)

**Comment by usualdesigner** [comment]
@lynicidn so, it can't be done automatically?

**Comment by usualdesigner** [comment]
Guys, any suggestion? Anyone interested in this functionality? I'm going to make PR.

**Comment by lynicidn** [comment]
I'm going to make PR.))) ok.

**Comment by usualdesigner** [comment]
Will start working on it soon.
