### ISSUE TITLE
Yii 2.0.5 Install via Composer

### ISSUE THREAD

**Issue by stdex** [yiisoft/yii2#9090]
>composer create-project yiisoft/yii2-app-basic basic 2.0.5

return:

>Could not find package yiisoft/yii2-app-basic with version 2.0.5.

When package will be available?

**Comment by samdark** [comment]
https://packagist.org/packages/yiisoft/yii2-app-basic 2.0.5 is there...

**Comment by stdex** [comment]
Now it's work... Maybe connection problem...
