### ISSUE TITLE
Url caching has error

### ISSUE THREAD

**Issue by genichyar** [yiisoft/yii2#9091]
If I use following url rules
```php
[
    'pattern' => '',
    'route' => 'paracms/structure/frontend/page/view',
    'defaults' => ['slug' => 'index'],
],
'page/<slug>' => 'paracms/structure/frontend/page/view',
```
and then run code
```php
echo Url::to('/paracms/structure/frontend/page/view', ['slug' => 'services']);
echo '<br>';
echo Url::to('/paracms/structure/frontend/page/view', ['slug' => 'index']);
```
I have got
```
/page/services/
/page/index/
```
But I expeсted
```
/page/services/
/
```

This problem rises due to https://github.com/yiisoft/yii2/commit/ebc089e6c26ba85642e5b32eaae017c6b637be79

When I call ```Url::to('/paracms/structure/frontend/page/view', ['slug' => 'services']);``` rule № 2 was cached and then it was used when I call ```Url::to('/paracms/structure/frontend/page/view', ['slug' => 'index']);``` instead of rule № 1.

**Comment by klimov-paul** [comment]
See #8205
It seems 'create URL cache' feature should be reverted (which whould be a pity) or made optional.
In present state you should be able to walk around the issue exluding 'index' from second rule:
```php
[
    'pattern' => '',
    'route' => 'paracms/structure/frontend/page/view',
    'defaults' => ['slug' => 'index'],
],
'page/<slug:((?!index).)+>' => 'paracms/structure/frontend/page/view',
```

**Comment by genichyar** [comment]
@klimov-paul, thank you!

I use same regexp as temporary solution: `page/<slug:((?!index).)*>`. But it doesn't work properly if slug has word "index". For example: `index1`, `indexation`, etc.

> It seems 'create URL cache' feature should be reverted (which whould be a pity) or made optional.

I think 'create URL cache' was good idea. If there is no issue with this feature except my issue I propose to not revert this feature and add an ability to make inversed regexp in url.

For example:
`page/<slug:!index>` — All except "index"
`page/<slug:!(index|sitemap|contacts)>` — All except "index", "sitemap", "contacts"

**Comment by cebe** [comment]
there is no need for complex inverse regex, we can simply skip the cache if we detect situations which we can not cache.

checked in a fix for this.
