### ISSUE TITLE
Invalid object ID when session expires!

### ISSUE THREAD

**Issue by alirezastack** [yiisoft/yii2#9092]
It seems that when we use MongoDB  for authentication manager, this error happens and I receive Invalid Object ID.

When I remove _identity cookie from browser, everything seems up & running again.

public static function findIdentity($id)
    {
        return static::findOne(['_id' => new \MongoId($id), 'status' => self::STATUS_ACTIVE]);
    }

![mongodb](https://cloud.githubusercontent.com/assets/6417083/8652433/e957db62-2993-11e5-985f-0e332109affc.png)

**Comment by lynicidn** [comment]
try
```php
function getId()
{
return (string)$this->_id;
}
```

**Comment by klimov-paul** [comment]
Duplicates #2129
