### ISSUE TITLE
Unable to get `ListView` widget instance when render item via file

### ISSUE THREAD

**Issue by hightman** [yiisoft/yii2#9094]
Let's see L95 of `ListView` source code:
<https://github.com/yiisoft/yii2/blob/master/framework/widgets/ListView.php#L95>

```php
        ...
        } elseif (is_string($this->itemView)) {
            $content = $this->getView()->render($this->itemView, array_merge([
                'model' => $model,
                'key' => $key,
                'index' => $index,
                'widget' => $this,
            ], $this->viewParams));
        } else {
        ...
```
I think that here should be used `$this->render(...)` defined in base widget class, instead of `$this->getView()->render(...)`

Otherwise, we can not obtain widget instance via `$this->context` in view file.

**Comment by klimov-paul** [comment]
You don't need `$this->context` inside such view file to get widget instance - it is available via `$widget` variable.
