### ISSUE TITLE
Errors at pdf guide

### ISSUE THREAD

**Issue by codeName007** [yiisoft/yii2#9099]
Is it good, or it is a bug at your pdf guide, starting from page 157 happens places with: 
Error not existing file... you can see it [here](https://screencloud.net/v/plD).
Total count of such messages is 16... suppose it's bug?

**Comment by cebe** [comment]
well, that one is really old, check the new version: http://stuff.cebe.cc/yii2-guide.en.pdf
An up to date version will also come with the new site.

**Comment by cebe** [comment]
there are similar errors in this version but they are related to updates in the guide structure.
