### ISSUE TITLE
gii generators generate broken code

### ISSUE THREAD

**Issue by ChristopheBrun** [yiisoft/yii2#9100]
Most (if not all) classes generated by with Gii are broken because separators are missing in the generated code. A typical result is invalide PHP code like this : 

    namespaceapp\modules\users;
    
    classModuleextends \yii\base\Module
         {
        [etc...]

**Comment by ChristopheBrun** [comment]
NB : I'm going to fix it in my own current project. I'll send you a pull request here asap if the issue is still unaffected

**Comment by samdark** [comment]
Are you sure? I've just tried generating module with Gii and resulting class was OK.

**Comment by ChristopheBrun** [comment]
Yes, I'm sure. I've set up a fresh install this morning with composer (basic app) and the bug shows. 
I fixed the files in the gii extension in my project & now it works fine. 
BTW, I've just spotted the yiisoft/yii2-gii sub-project, I should have opened the issue there... 
What version do you have ?

**Comment by ChristopheBrun** [comment]
OK, I cloned & checked yiisoft/yii2-gii and the files are OK. 
OTOH, it looks like my editor (PHPStorm) removes spaces before the `<?=` tag when reformating the code. My bad. 
You can close this issue, then.
