### ISSUE TITLE
AssetManager appendTimestamp not working if you use registerJsFile()

### ISSUE THREAD

**Issue by otsec** [yiisoft/yii2#9101]
Timestamp is appended only if you create your own bundle. This is too complicated if you just want to register on JS file on certain page.

`registerJsFile()` creates bundle inside, but does not fill the `basePath`. I guess this is the reason timestamp is not appended.

**Comment by saada** [comment]
:+1:

**Comment by SilverFire** [comment]
It you're feeling convenient enough, feel free to send us a PR.

**Comment by saada** [comment]
My pull request
https://github.com/yiisoft/yii2/pull/10297

**Comment by SilverFire** [comment]
#10429

**Comment by SilverFire** [comment]
Resolved by dc23a6d3d8a9cd937cbbc64652db903ee4ff5598

**Comment by githubjeka** [comment]
Please reopen. Because #10429 (comment)

**Comment by cronfy** [comment]
For those who is intersted in (temporary) solution:

Instead of `registerJsFile()` we can create new AssetBundle on the fly. Replace `$this->registerJsFile($file)` in your view with this code:

```
$file = '/js/page.js';
$asset = new \yii\web\AssetBundle([
    'js' => [ltrim($file, '/')],
    'basePath' => '@webroot',
    'baseUrl' => '/'
]);
$this->getAssetManager()->bundles[$file] = $asset;
$this->registerAssetBundle($file);
```

**Comment by SilverFire** [comment]
@cronfy thank you for a good suggestion. I'm closing this issue

**Comment by z316712331** [comment]
@cronfy @SilverFire 
if there is ten special static resources,i need registerAssetBundle ten times or create ten AssetBundles?
