### ISSUE TITLE
SchemaBuilder TYPE_TEXT bugs

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#9102]
[SchemaBuilder::text](https://github.com/yiisoft/yii2/blob/master/framework/db/SchemaBuilder.php#L110) allows you to specify a length. This is wrong, you cannot use length for text fields: http://dev.mysql.com/doc/refman/5.7/en/create-table.html

Instead, you have to use TINYTEXT,  TEXT, MEDIUMTEXT or LONGTEXT. SchemaBuilder does not support these, it always uses TEXT (see also #8950)

**Comment by nkovacs** [comment]
MySQL doesn't fail (it might throw a warning depending on server configuration, I didn't check).

But on postgres you get this error:

```
create table test (foo text(255));

ERROR:  type modifier is not allowed for type "text"
```

**Comment by samdark** [comment]
OK. What's your proposal?

**Comment by nkovacs** [comment]
The length parameter should be removed. I don't think it's used by any of the databases Yii supports. They either ignore it or error out like postgre.

Alternatively, the length parameter could select between TINYTEXT, MEDIUMTEXT etc. on mysql, but like I said in #8950, I think that's a bad idea, because it's a mysql-specific workaround (at first I thought the length parameter did that, before I checked the code).

**Comment by nkovacs** [comment]
2.0.5's release date is almost here. If you release it like this, you won't be able to remove the parameter without breaking BC.

I've checked the documentation of all the supported database systems:

* Cubrid: [text is converted to varchar] (https://github.com/yiisoft/yii2/blob/master/framework/db/cubrid/QueryBuilder.php#L27), which can accept a length parameter. Omitting it defaults to the maximum length.
* MSSQL: does not accept length according to [documentation](https://msdn.microsoft.com/en-us/library/ms187993.aspx).
* MySQL: length is ignored, may cause warnings or errors depending on server settings.
* Oracle: [text is converted to clob](https://github.com/yiisoft/yii2/blob/master/framework/db/oci/QueryBuilder.php#L30). Does not accept length according to [documentation] (http://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements001.htm#i54330)
* PostgreSQL: throws an error if you add a length parameter.
* SQLite: lengths are [ignored](https://www.sqlite.org/datatype3.html). I tested this with sqlite 3:

```
sqlite> create table foo (bar varchar(2), baz text(2));
sqlite> .schema
CREATE TABLE foo (bar varchar(2), baz text(2));
sqlite> insert into foo values ("asdf", "asdf");
sqlite> select * from foo;
asdf|asdf
```

**Comment by samdark** [comment]
Yep, overall makes sense to remove parameter.

**Comment by nkovacs** [comment]
Binary also has a length parameter, and it has a similar problem. With postgre it's converted to [bytea](https://github.com/yiisoft/yii2/blob/master/framework/db/pgsql/QueryBuilder.php#L59), which cannot have a length (same error as text). But for MSSQL it's converted to [binary(1)](https://github.com/yiisoft/yii2/blob/master/framework/db/mssql/QueryBuilder.php#L40), so you must specify a length. Unless you're specifically targeting MSSQL, you won't run into this and you won't specify a length, so your code probably won't work correctly with binary(1). I think it would be better to use `varbinary(max)` here.

**Comment by samdark** [comment]
@nkovacs can you fix the issues you've mentioned in a pull request? Would be much easier to review.

**Comment by nkovacs** [comment]
There are some more problems (these are also problems with the current typeMap system, but SchemaBuilder exposes them):
* Integer precision: only used on mysql and oracle and maybe cubrid, throws error on postgresql. On mysql it only affects the display width, so it's effectively useless.
* Float: on postgresql, it's converted to `double precision`, and you cannot specify precision and scale, so using those two will throw an error.

**Comment by cebe** [comment]
precision/length are stripped from a type definition if a dbms does not support them. how did you manage to get the above error when using postgres?

**Comment by nkovacs** [comment]
I only tested it manually, that's no longer an issue.

**Comment by nkovacs** [comment]
Closing this, since it's no longer an issue with your refactor.
