### ISSUE TITLE
Logic behind & expanded function of Controller:$layout property

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9103]
@developers,

I am working inside a custom Module and was very pleased to see that the layout property is accessing the layout locally inside the module:
* $layout='_layout' -> would refer to /modules/ModuleA/views/layouts/_layout

However, this is not enough for me ;): Sometimes the layout only applies to 1 controller, and therefore I want the layout to be inside /modules/views/article/layouts. The problem is, I cannot access this folder, ie. not by:
* $layout='/../article/layouts/_layout' which refers to "frontend\views\layouts\etc..."

Remarkebly, both '//article' and '/article' do the same. When I look at the implementation of findLayoutFile this is confirmed.

I was expecting that if $layout='article' would mean $layout='/../article/layouts' would be in the same __DIR__ space. Is it an idea to separate the following markups:
* //_layout points to the layout folder at application level
* /_layout points to the layout folder at module level

**Comment by samdark** [comment]
Try using `@app/modules/views/article/layouts...`.

**Comment by dynasource** [comment]
Sam, thanks for your reply. In my scenario it would result in:
$layout = '@app/../vendor/dmn/yii2/modules/article/views/article/layouts/_layout';

This works, but I suppose a relative layout is cleaner and more in line with the routing mechanism:
$layout = '/../article/layouts/_layout';

Btw. Altering findLayoutFile is a minor patch. I could pass a PR. Till then I will keep on using your solution.

**Comment by samdark** [comment]
PR could be helpful. I've proposed solution to fix it right away. I didn't mean to say that it's the best option...
