### ISSUE TITLE
Many PHP errors go nowhere

### ISSUE THREAD

**Issue by TriAnMan** [yiisoft/yii2#9106]
There is a some kind of architectural issue.
Framework hides huge amount of PHP errors and they become lost for any investigation.
For example any of `E_STRICT` message is lost, any messages suppressed in `\yii\caching\FileCache::setValue()` are lost.

I need this kind of errors logged to `app.log` or to `php.log`... Anywhere I can find them for issues investigations and for the application health monitoring.

**Comment by klimov-paul** [comment]
What is the value of `error_reporting()`?
Have you tried to set `error_reporting(E_ALL)` or `error_reporting(E_ALL | E_STRICT)`?

**Comment by TriAnMan** [comment]
You are right about error_reporting. It was E_ALL & ~E_DEPRECATED & ~E_STRICT
Nevertheless the case of suppressed errors still actual.
For example: you can change an owner or mode of the `runtime/cache` directory and you will not know that the cache isn't working.

**Comment by samdark** [comment]
@TriAnMan more examples of such behavior?

**Comment by klimov-paul** [comment]
Well, we can not ignore `error_reporting` value inside `ErrorHandler` otherwise error supression operator (`@`) will not work, and if you for example choose to ignore E_DEPRECATED, it will also be impossible.
If you have further concerns about this matter you should report this to php.net.

**Comment by TriAnMan** [comment]
Sorry, but what do you think about error suppression? I believe, that it is
a bad idea to use it. The right way is to handle errors rather ignore them.
And the example about cacheing is a real world example from my project. I
think there will be more examples of this kind at future.

**Comment by samdark** [comment]
I think caching errors should write something to log.

**Comment by kidol** [comment]
Wasn't it fixed already with #9038?

**Comment by klimov-paul** [comment]
> I think caching errors should write something to log.

Why?
Imagine you are using some legacy code, which code based on some PHP deprecated features, so it triggers E_DEPRECATED on regular basis. If can not rewrite this legacy library the only option for you is exclude E_DEPRECATED from `error_reporting()`. What is the case of logging those E_DEPRECATED? Developer already knows these errors appear - why waste a disk space for the log, which serves no purpose?

> but what do you think about error suppression?

It is widely used even accross the core itself. For instance:
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L281

> The right way is to handle errors rather ignore them.

Do you really understand what are talking about? You say the fact that program reports only errors, which are set via `error_reporting` is a bug. This is noncense! PHP core features can not be just denied.
 What next? You will set 'max_post_size' to 2MB inside 'php.ini' and will complain that you are unabled to upload file with size 5MB - and it will also be a Yii bug?

**Comment by samdark** [comment]
@kidol yes, it was.

**Comment by samdark** [comment]
@klimov-paul I think he's talking mainly about `@` usage in our code.

**Comment by samdark** [comment]
@TriAnMan cache errors will be logged in 2.0.6. If you'll find more instances of such silent failure where it makes sense to log error, please create a separate issues.

**Comment by TriAnMan** [comment]
@samdark
> If you'll find more instances of such silent failure where it makes sense to log error, please create separate issues.

Ok

@klimov-paul 
> You say the fact that program reports only errors, which are set via error_reporting is a bug. This is noncense!

Sorry for misleading you. I agree with your concern about `error_reporting` (as I said before).
Fix #9038 solves my issues with errors in `app.log`.

Thanks for everybody!
