### ISSUE TITLE
Does View Translation works?

### ISSUE THREAD

**Issue by Stern87** [yiisoft/yii2#9107]
http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#view-translation

View Translation from The Definitive Guide seems not working.

What I need to do to make it working correctly? I am using app basic template.

**Comment by samdark** [comment]
1. Put views into <language name> subdir.
2. Switch application language to that language.

**Comment by Stern87** [comment]
Already:
1. I have two different faq.php: /views/site/faq.php and /views/site/ru-RU/faq.php
2. In config (/config/web.php):
$config = [
    ...
    'language' => 'ru-RU',
    'sourceLanguage' => 'ru-RU',
    ...
];

And it's not working.


P.S. From http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#view-translation :
~~~
Note: If the target language is the same as source language, view translation may still work as long as you provide a translated view. For example, if both languages are en-US and you have both views/site/index.php and views/site/en-US/index.php, then the latter will be rendered.
~~~

**Comment by lynicidn** [comment]
@Stern87 вы переводите с русского на русский? тут перевода не будет - не логично

**Comment by Stern87** [comment]
@lynicidn Не логично то, что в документации написано.
Повторяю:
 http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#view-translation :
~~~
Note: If the target language is the same as source language, view translation may still work as 
long as you provide a translated view. For example, if both languages are en-US and you have 
both views/site/index.php and views/site/en-US/index.php, then the latter will be rendered.
~~~

Т.е. даже если language=sourceLanguage="en-US", и если есть 2 файла index.php: views/site/index.php и views/site/en-US/index.php - то должен быть выбран последний.

**Comment by samdark** [comment]
Docs were not correct. Fixed.

**Comment by samdark** [comment]
Thanks for reporting.
