### ISSUE TITLE
Jquery version

### ISSUE THREAD

**Issue by ScottHuangZL** [yiisoft/yii2#9110]
My website cannot display normally at IE browser while can display well at firefox/chrome.
After checking, I find it should caused by jquery issue.
So I change the version from 2.1.4 to 1.11.3, then it can work well at both IE/Firefox/Chrome.

Can Yii2 use jquery1.11.3 to allow better compatibility?
Or, provide choice when install yii2?
Or , at least add this advice/quidance into yii2 document in case some people need consider more compatibility?

Please refer to [forum link](http://www.yiiframework.com/forum/index.php/topic/65444-yii2-website-not-display-correct-at-ie-while-ok-at-chromefirefox/)

**Comment by arogachev** [comment]
You can always customize built-in assets to fit your needs. And it's already mentioned in official docs [here](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#customizing-asset-bundles).

**Comment by ScottHuangZL** [comment]
Thanks for point out this.
Can we default use 1.11.3 since it compatible more browser?? thanks.

**Comment by arogachev** [comment]
I think no, because IE8 is considered deprecated now.

**Comment by samdark** [comment]
No.
