### ISSUE TITLE
Fix for annoying "blink" of Yii Debug Toolbar upon page refresh

### ISSUE THREAD

**Issue by trejder** [yiisoft/yii2#9112]
Yii Debug Toolbar is positioned using Javascript. This creates an annoying (at least to some) effect of "blinking" of whole page, when for a half of seconds a vertical scrollbar appears (page contents shifts left) and then (when YDT is positioned by Javascript) it disappears (page contents shifts right, back to original position).

This problem (at least to some) could be easily fixed, by static, CSS-positioning of Yii Debug Toolbar. This could be achieved by adding following style:

    /* Fix annoying "blink" of Yii Debug Toolbar upon page refresh */
    #yii-debug-toolbar {
        bottom: 0;
        left: 0;
        margin: 0;
        position: fixed;
        right: 0;
    }

to the end of `backend\web\css\site.css` and `frontend\web\css\site.css` (in `app-advanced` scheme) or to .`web\css\site.css` (in `app-basic` scheme).

Could this "fix" be permanently integrated into Yii2 skeleton apps? It won't do much harm, people who doesn't care for this "blink" won't also care for a fix to it and people like me, who are driven crazy by this "blink" and thus must integrate this fix in every new project, would be happy.

**Comment by dynasource** [comment]
+1

**Comment by samdark** [comment]
Are you sure it helps? Toolbar isn't positioned using JavaScript. Here's CSS with current master:

![Debug toolbar CSS](https://cloud.githubusercontent.com/assets/47294/8710100/e9434568-2b4f-11e5-8c1c-4f702230ec1a.png)

**Comment by trejder** [comment]
I'm absolutely sure, that this piece of CSS code helps. Without it blinking appears, with it -- there is no blinking. I'm not sure about cause and thus my guessing about Javascript my be wrong. However, I have verified, that this CSS code works in both _app-basic_ and _app-advanced_. I have just incorporated it to my another Yii2 project.

**Comment by samdark** [comment]
Hmm. I've tried with/without CSS proposed using advanced app template. Saw no difference.

**Comment by dynasource** [comment]
patch supplied by Trejder solves the verticle scrollbar issue for me:

/* Fix annoying "blink" of Yii Debug Toolbar upon page refresh */
#yii-debug-toolbar {
    bottom: 0;
    left: 0;
    margin: 0;
    position: fixed;
    right: 0;
}

**Comment by samdark** [comment]
Where do you put it?

**Comment by dynasource** [comment]
somewhere hardcoded in the view...

**Comment by trejder** [comment]
@samdark I don't know, where @dynasource is putting my piece of code, but I put it -- as in initial issue request -- to the end of `backend\web\css\site.css` and `frontend\web\css\site.css` (in `app-advanced` scheme) or to .`web\css\site.css` (in `app-basic` scheme).

**Comment by samdark** [comment]
I've adjusted debug toolbar to register styles in head instead of outputting them in the body. @trejder can you check if it helped to fix this "blink" (i.e. test it w/o your CSS fix)?

**Comment by trejder** [comment]
@samdark How should I test it? Should I pull (via Composer) the latest dev-branch out of Yii2 framework?

**Comment by samdark** [comment]
You can pull just the `dev-master` version of debug toolbar.

**Comment by samdark** [comment]
I've found out what was causing the issue. Should be OK now.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-debug/commit/338be457a28bfe5410771e3f199b088123f28e93

**Comment by dynasource** [comment]
thx

**Comment by trejder** [comment]
Great! Thanks! :>
