### ISSUE TITLE
dictionary models without storing in a database

### ISSUE THREAD

**Issue by dizews** [yiisoft/yii2#9114]
Hello.

Sometimes AR models have attributes like a ```status_id```. Statuses usually has ```id``` and ```label``` and the range of values would changed rare.
I think it will be a good idea to add a model is similar to AR by interface but is not stored in a database.

as a plus we have a clean database and do not have useless queries.

**Comment by klimov-paul** [comment]
You can use an extension:
https://github.com/yii2tech/filedb
Or an SQLite database.

**Comment by dizews** [comment]
thanks.
