### ISSUE TITLE
[Feature] add  recursive implode function for ArrayHelper

### ISSUE THREAD

**Issue by zuoRambo** [yiisoft/yii2#9120]
implode can Join array elements with a string,but the array can't be multidimensional. So it will be perfect if the ArrayHelper Class could provider a method to join multidimensional array with a string.

**Comment by klimov-paul** [comment]
What is a practical use case?

**Comment by zuoRambo** [comment]
```
Class A{
public function b($paramA,$paramB){
    $cacheKey = __MEHTOD__ .implode('_',func_get_args());
    $cache = Yii::$app->cache->get($cacheKey);
    ....
    //if the $paramA or $paramB was array,the implode function will have some question~
}
}
```

**Comment by bizley-code** [comment]
In case you decide to add this feature I've got working method and can PR.

**Comment by zuoRambo** [comment]
@bizley-code thanks a lot, but where is the repositories? i think i could add into my Helper class file.

**Comment by bizley-code** [comment]
Here is gist https://gist.github.com/bizley-code/23b0b29540f284440313

**Comment by sheillendra** [comment]
In case, get errors model return array recursive, we need simple way to assign the error to session flash, simple like php exception $ex->getMessage();
