### ISSUE TITLE
Add support for AWS Redshift

### ISSUE THREAD

**Issue by DarwinIsGod** [yiisoft/yii2#9121]
It's so close to postgres, but so far...I got it working for my current needs, but have not thoroughly tested it. Pull request coming soon.

**Comment by samdark** [comment]
Not sure it's a good idea to have it in the code. AWS Redshift is quite specific solution so probably it's better to have it as an extension rather than part of the core framework.

**Comment by klimov-paul** [comment]
Since there is no core team member, who can support such extension - it can not taken under 'yiisoft'.
It should be released as separated 3rd party extension.

**Comment by DarwinIsGod** [comment]
Fair enough. Thanks guys.
