### ISSUE TITLE
Cookie stops working after enabling pretty url in Yii2 urlManager configuration

### ISSUE THREAD

**Issue by rahil-geekunit** [yiisoft/yii2#9124]
As soon as I enabled pretty urls in urlManager application configuration, the cookie seems to stop working and somewhat showing ambiguous behavior.

Here is a detailed explanation of the issue;
http://stackoverflow.com/questions/31447327/cookie-stops-working-after-enabling-pretty-url-in-yii2-urlmanager-configuration

**Comment by cbhp** [comment]
You are not using Yii's cookie object: http://www.yiiframework.com/doc-2.0/guide-runtime-sessions-cookies.html#cookies

Instead you are calling the PHP function setcookie() (without setting path or domain) and $_COOKIE directly. That's wrong.
