### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/yii2#9125]
Hi
i'm trying to load bootstrap in a bootstrap file by selecting from db like this (this is a modular system)

public function bootstrap($app){

                        $app->bootstrap[]= 'modules/test/bootstrap';

                        var_dump($app->bootstrap);
}
                        
when i set 'modules/test/bootstrap' in confing main.php it is work currectly
when i do it by top code 'modules/test/bootstrap' dos not execute, but var_dump show it in bootstrap array.

why it not work ??
if it's a bug, can you don it to working in next version?

**Comment by klimov-paul** [comment]
@hooman-pro, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by hooman-pro** [comment]
i done it, is it possible to answer me in : http://www.yiiframework.com/forum/index.php/topic/65501-php-bootstrap/
