### ISSUE TITLE
Add Html::div to HtmlHelper

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9126]
Currently Html::img & Html::a are supported in the HtmlHelper because of their unique characteristics. 

On the other hand you could assume that these are supported because of their widely use.

What is happening in practice, is that I often automatically want to try Html::div() to render a container,. But this should be done by Html::tag('div'), which 'feels' not autonomically yet for such a widely used element. It also is less readible in the code.

I would suggest to include a shortcut to DIV in the Html Helper. For several reasons:
* more intuitive
* faster code to read (especially within widgets)
* shorter code to write

Example:
```php
        $body[] = Html::tag('div',$img,$this->imageOptions);
        $body[] = Html::tag('div',$body,$this->bodyOptions);
        return Html::tag('div',implode($body),$this->options);
```

```php        
        $body[] = Html::div($img,$this->imageOptions);
        $body[] = Html::div($body,$this->bodyOptions);
        return Html::div(implode($body),$this->options);   
```

**Comment by nunomaduro** [comment]
+1

**Comment by klimov-paul** [comment]
`Html::img` and `Html::a` have been extracted because the y use different function API: `img` should always have an "src" attribute and `a` - a "href" attribute.

Using `Html` helper for the general markup composition is a bad practice - you should use plain HTML for your containers.

**Comment by dynasource** [comment]
@klimov-paul: I agree with most of what you are mentioning (and that is what I was saying about 'Html::a and Html::img and  their unique characteristics),  but what you basically are stating that 'plain HTML' should be use for containers at all times (as it is a bad practice). 

With this you imply that using plain HTML is always better than using a function, which of course is not the case. There are enough usecases in which you dont want to use plain HTML:
* when you are making use of dynamic attributes contained in arrays
* when you dont want to use views for HTML (such as in widgets)
* when you prefer consistent codewriting
* when a DIV is not important enough show as plain HTML, but important enough as a container.
* etc etc.

**Comment by cebe** [comment]
in those cases it is fine to use `Html::tag('div',$content,$options)`. there is no need for an extra method.
