### ISSUE TITLE
Memory leaking in Component::behaviors()

### ISSUE THREAD

**Issue by iworker** [yiisoft/yii2#9129]
I have a problem with a lot of ActiveRecord objects – memory is growing up very fast.
I created some tests to detect where is the problem. And I found it.
When we create local instance of Component class with defined behaviors (no matter ActiveRecord or no) in some function:
```
  class Foo {
  ...
      function bar() {
          $object = new ComponentWithBehaviors();
      }
  ...
  }
```
There is an issue with cross-links. Actually, $object will have private $_behaviors array with links to behaviors; and every behavior will have $owner property with link to $object.
And, after all, there is no another clear-way to prevent memory leaking, except using gc_collect_cycles(). But this function is **very** slow.

So the non-clear-way is to use $object->detachBehaviors() before ending scope:
```
  $object = new ComponentWithBehaviors();
  ....
  $object->detachBehaviors();
```
Then all memory for object + all behaviors will be free after ending of method execution.

There is an example with model, controller and foreach cycle:
test model: ```common/models/TestModel.php```:
```
<?php

namespace common\models;

use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;

class TestModel extends ActiveRecord
{
    public function behaviors()
    {
        return [
            'timestamp' => TimestampBehavior::className(),
        ];
    }
}
```
test controller: ```console\controllers\LeakController```:
```
<?php

namespace console\controllers;

use yii\console\Controller;
use common\models\TestModel;

class LeakController extends Controller
{
    private function createModels($detach = true, $count = 1000)
    {
        for ($i = 0; $i != $count; ++$i) {
            $model = new TestModel();
            if ($detach) {
                $model->detachBehaviors();
            }
        }
    }

    public function actionTestModel()
    {
        $test = new TestModel(); // Create temporary object for loading TestModel.php etc.
        $memory = -memory_get_usage();
        $this->createModels(true);
        echo "Usage of memory with detaching: " . (memory_get_usage() + $memory) . " bytes" . PHP_EOL;
        $memory = -memory_get_usage();
        $this->createModels(false);
        echo "Usage of memory without detaching: " . (memory_get_usage() + $memory) . " bytes" . PHP_EOL;
    }
}
```
So let's start this test (```./yii leak/test-model```):
```
Usage of memory with detaching: 544 bytes
Usage of memory without detaching: 4412680 bytes
```

Thats exactly what I tell about: when we using detaching behaviors we got memory free.

But why I created this issue?
Obviously, this solution is very tricky. We can easily forget about this or that model and there will be memory leaking (if we creating 1000+ instances of that).
I think it's possible to increase performance of Yii by creating some more clear solution. I don't know is there PHP capabilities or something in Yii2 but I hope it's possible to do this solution more automatically or more obviously. Let's start discussion this.
Some links about cross-links:
http://paul-m-jones.com/archives/262 (en)
http://habrahabr.ru/post/122407/ (ru)

**Comment by klimov-paul** [comment]
Indeed behavior mechanism produces cross object cycle refreneces.
If you are running long-time script you shold either avoid usage of ActiveRecord or clear he memory manually.
Cycle refreneces can be cleared using `Component::detachBehaviors()` or via PHP `gc_collect_cycles()` function.

**Comment by iworker** [comment]
@klimov-paul I wrote about both solutions. I know about it. I created issue for finding better solution and for notice people who using Yii about this problem and non-automatically way of solution this.

**Comment by cebe** [comment]
I do not see what yii could do about this issue, as far as I see PHP could be able to run this function itself to clean up memory on a regular basis. or you have to do it. I do not see a place where yii could call this to solve the issue.

**Comment by iworker** [comment]
@cebe 
Okay
Then I will attach here results with gc_collect_cycles and timing:
```
Usage of memory with detaching: 544 bytes; Usage of time: 15.379461050034 s
Usage of memory without detaching: 778264 bytes; Usage of time: 11.188360929489 s
Usage of memory with gc_collect_cycles: 0 bytes; Usage of time: 12.584699869156 s
```

**Comment by klimov-paul** [comment]
>  created issue for finding better solution and for noticing people who using Yii2 about this problem and non-automatically way of resolving this.

There is no other solution for this as well as there is no automatic way to solve this.
Still particular behavior may be stripped from owner in case it does not use any code, which requires `$this->owner` invocation. For example: if behavior only handles some events you an override its `attach()` method as following:

```php
public function attach($owner)
{
    parent::attach($owner);
    $this->owner = null; // unset cycle reference
}
```

Then this behavior will not produce a cycle reference.
However this solution may produce unexcepected side effects and can not be used for most behaviors even `TimestampBehavior` requires `owner` reference:
https://github.com/yiisoft/yii2/blob/master/framework/behaviors/TimestampBehavior.php#L128

> Then I will attach here results with gc_collect_cycles and timing

That is why it is better to use `Component::detachBehaviors()`.

**Comment by iworker** [comment]
@klimov-paul as I saw it is better to use ```gc_collect_cycles```: zero bytes and 3 seconds fastest, is it?

**Comment by klimov-paul** [comment]
Sure.

**Comment by iworker** [comment]
@klimov-paul you could run it at your PC:
common/models/TestModel.php: https://gist.github.com/iworker/2998d3fc47aa70d58b21
console/controllers/LeakController.php: https://gist.github.com/iworker/e595e83f4781d087e999
Run: ```./yii leak/test-model```

**Comment by iworker** [comment]
@klimov-paul Maybe it depends on php version and PC?
I repeated again:
```
Usage of memory with detaching: 544 bytes; Usage of time: 13.452949047089 s
Usage of memory without detaching: 778264 bytes; Usage of time: 9.8203780651093 s
Usage of memory with gc_collect_cycles: 0 bytes; Usage of time: 10.001892089844 s
```
```
php -v
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)...
```

**Comment by iworker** [comment]
@klimov-paul on fastest server with php 5.6:
```
Usage of memory with detaching: 544 bytes; Usage of time: 0.94812297821045 s
Usage of memory without detaching: 582400 bytes; Usage of time: 1.0123038291931 s
Usage of memory with gc_collect_cycles: 0 bytes; Usage of time: 0.9381959438324 s
```
and second time
```
Usage of memory with detaching: 544 bytes; Usage of time: 0.9225709438324 s
Usage of memory without detaching: 582400 bytes; Usage of time: 0.81615996360779 s
Usage of memory with gc_collect_cycles: 0 bytes; Usage of time: 0.94035601615906 s
```

**Comment by iworker** [comment]
@klimov-paul  And, finally, the best result is with using php 7.0 (just for fun):
```
php-7.0 yii leak/test-model
Usage of memory with detaching: 0 bytes; Usage of time: 0.36147308349609 s
Usage of memory without detaching: 424080 bytes; Usage of time: 0.33269095420837 s
Usage of memory with gc_collect_cycles: 0 bytes; Usage of time: 0.32146406173706 s
```
and second time:
```
php-7.0 yii leak/test-model
Usage of memory with detaching: 0 bytes; Usage of time: 0.29111480712891 s
Usage of memory without detaching: 424080 bytes; Usage of time: 0.45802903175354 s
Usage of memory with gc_collect_cycles: 0 bytes; Usage of time: 0.33490300178528 s
```

**Comment by dynasource** [comment]
interesting analysis. @iworker, thanks for sharing all the details.

**Comment by TheHett** [comment]
https://github.com/yiisoft/yii2/issues/13256
