### ISSUE TITLE
rbac\DbManager doesn't use cached parents and doesn't cache assignments

### ISSUE THREAD

**Issue by nineinchnick** [yiisoft/yii2#9130]
I've noticed that the `yii\rbac\DbManager.checkAccessFromCache()` method calls `yii\rbac\DbManager.checkAccessRecursive()` which does not use cached parents and fetches them using (multiple) queries.

Also, assignments are never cached. Is there any reason against caching them as well as all other data?

I'd be happy to provide a PR if the above is confirmed.

**Comment by klimov-paul** [comment]
#8810

**Comment by klimov-paul** [comment]
Assignments caching may produce a trouble in case you check permission for several different users during same script execution.
So cache should be performed per each user, and perhaps there should be an option to disable it as it may consume to much memory in case to check permissions for several different users during the same script execution.

**Comment by nineinchnick** [comment]
Duplicate of #8595 and already fixed in 07bcc8fda19655c97dfffe74b2f087878eaff97c
