### ISSUE TITLE
AssetBundles should check if dependencies already registered

### ISSUE THREAD

**Issue by bluezed** [yiisoft/yii2#9131]
I have a case here where I have an AssetBundle (AB1) registered and another AssetBundle (AB2) has the AB1 as a dependency.

At runtime I now get the same AB1 showing up twice in the AssetManager.

Is that expected behaviour?

I would expect the function \yii\web\View::registerAssetBundle() to check if a dependency is already registered or am I misunderstanding the concept?

**Comment by samdark** [comment]
It's checking it so your case could be considered a bug. Can you help reproducing it using simple asset bundles and basic app?

**Comment by bluezed** [comment]
Ok... found the problem.
Have debugged it a bit more and it's like this...
AB1 is registered as "something\somethingElse\SomeAsset"
But in AB2 the dependency is set as "\something\somethingElse\SomeAsset"

So it's because of the leading "\".
Not sure if registerAssetBundle() should resolve this or not or has the author of AB2 set the dependency incorrectly?

**Comment by samdark** [comment]
I think it could be resolved by framework normalizing class names in `AssetBundle::init()`. @yiisoft/core-developers thoughts?

**Comment by klimov-paul** [comment]
We have already disscussed this at #3143 and at #6007.
The conclusion has been already made and there is a corresponding warning in the docs.
