### ISSUE TITLE
Optimistic Locking doesn't work if the lock value is not sent

### ISSUE THREAD

**Issue by EvgenyOrekhov** [yiisoft/yii2#9133]
I'm working on a REST API.
If I send an outdated lock value (e. g. `{"some_field":"some new value","version":0}`), I get StaleObjectException, which is expected.
If I do not send the optimistic lock field (e. g. if I send only `{"some_field":"some new value"}`), the record gets updated and everything is fine, which is not expected.
I expect to get StaleObjectException if I do not send the optimistic lock field.

**Comment by cbhp** [comment]
I was able to reproduce this in the webapp part (deleted the input field for version.)
Even with:
```
    public function rules()
    {
        return [
        	[['version', ...], 'trim'],
        	[['version', ...], 'required'],        	
        	[['version', ...], 'integer'],
        ];
    }
```

**Comment by cbhp** [comment]
Similiar issue: If you delete an required input field from the form in the webapp and submit the form (actionUpdate), the model will be updated (with the old value of the deleted field).

**Comment by EvgenyOrekhov** [comment]
@cbhp either the validation is broken on update, or there is some misunderstanding of how the validation should work on update. Related issue: https://github.com/yiisoft/yii2/issues/9134

**Comment by cbhp** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L213
says:
To use Optimistic locking:
[...]
2. Add a `required` validation rule for the version column to ensure the version value is submitted.

That is what I have done, with no effect.

**Comment by EvgenyOrekhov** [comment]
@cbhp those docs are misleading, it turns out the rules are not for input validation, but for model validation, see https://github.com/yiisoft/yii2/issues/9134

**Comment by cbhp** [comment]
My current workaround is checking if the attribute is sent. Example:
```
public function actionUpdate($id)
{
    $model = $this->findModel($id);
    $model->scenario = 'update';
    $stale = false;
    
    // if ($model->load(Yii::$app->request->post())) {
    if (ArrayHelper::keyExists($model->optimisticLock(), Yii::$app->request->post($model->formName(), []))
        && $model->load(Yii::$app->request->post())) {
        try {
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } catch (yii\db\StaleObjectException $e) {
            $stale = true;
            Yii::$app->session->setFlash('danger', 'Data outdated');
        }
    }
    
    return $this->render('update', [
        'model' => $model,
        'isStale' => $stale,
    ]);
}
```

**Comment by cbhp** [comment]
@EvgenyOrekhov I found the same issue for actionDelete.
If the POST-Request for deletion contains the 'version'-attribute, it will be checked. If not, you can delete the model..

**Comment by EvgenyOrekhov** [comment]
@cbhp I believe the checks should be performed in the model:
```php
public function isAttributeSubmitted($attributeName)
{
    return ArrayHelper::keyExists($attributeName, $this->dirtyAttributes);
}

public function afterValidate()
{
    parent::afterValidate();

    $optimisticLock = $this->optimisticLock();
    $isOptimisticLockSubmitted = $this->isAttributeSubmitted($optimisticLock);

    if (!$isOptimisticLockSubmitted) {
        $this->addError($optimisticLock, "$optimisticLock cannot be blank.");
    }
}

public function beforeDelete()
{
    if (!parent::beforeDelete()) {
        return false;
    }

    $optimisticLock = $this->optimisticLock();

    return $this->isAttributeSubmitted($optimisticLock);
}
```

**Comment by EvgenyOrekhov** [comment]
@cbhp I've just realized that an attribute is not dirty if the loaded value is equal to the old one.
I created a trait for BaseActiveRecord models that overrides the load() method:
```php
/**
 * Trait OptimisticLock for BaseActiveRecord models that use Optimistic Locking.
 */
trait OptimisticLock
{
    /**
     * Sets optimistic lock attribute to null and populates the model
     * with the data from end user.
     *
     * @param array $data the data array. This is usually `$_POST` or `$_GET`,
     * but can also be any valid array supplied by the end user.
     * @param string $formName the form name to be used for loading the data
     * into the model.
     *
     * @return boolean whether `$data` contained some data to populate
     * the models attributes.
     */
    public function load($data, $formName = null)
    {
        /* @var \yii\db\BaseActiveRecord $this */

        $lock = $this->optimisticLock();

        if ($lock !== null) {
            $this->$lock = null;
        }

        return parent::load($data, $formName);
    }
}

```

**Comment by tunecino** [comment]
I think this bug is important because it makes optimistic locks useless when client doesn't send a `version` attribute.  To sum up a bit, current [documentations](https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#optimistic-locks) says:

```
1. Create a column in the DB table associated with the Active Record class to store the version number of each row. The column should be of big integer type (in MySQL it would be BIGINT DEFAULT 0).
2. Override the yii\db\ActiveRecord::optimisticLock() method to return the name of this column.
3. In the Web form that takes user inputs, add a hidden field to store the current version number of the row being updated. Be sure your version attribute has input validation rules and validates successfully.
4. In the controller action that updates the row using Active Record, try and catch the yii\db\StaleObjectException exception. Implement necessary business logic (e.g. merging the changes, prompting staled data) to resolve the conflict.
```
But making `version` required within model rules won't throw any validation error on update or delete as the attribute is already set in DB. So [those lines in source code](https://github.com/yiisoft/yii2/blob/2c997cdb8215255a0f749719cfed72779a1c2ea3/framework/db/BaseActiveRecord.php#L801-L802) will simply use the original DB value as filtering condition without tying on user inputs.

I'm not sure how it could be better fixed but the simplest workaround I could think of is to hold `version` input in a virtual attribute different from the original one. So in the 4 documented steps:

1. do **1** and **2** but name the attribute something like `_version`
2. remove anything related to `_version` from your model rules.
3. create a virtual attribute `version` default to 0. If you really need to make it required you'll need to better handle scenarios as on insert you may not require user to send a version value.
4. use `afterValidate()` to set the original optimistic attribute.
5. use `fields()` to replace it and ensure client won't get confused by 2 different attributes.

So at the end your model will look something like this:

```
class SomeModel extends \yii\db\ActiveRecord
{
    public $version = 0;

    public function rules()
    {
        return [
            ['version', 'integer'],
        ];
    }

    public function afterValidate()
    {
        $this->_version = $this->version;
    }

    public function optimisticLock()
    {
        return '_version';
    }

    public function fields()
    {
        $fields = parent::fields();
        unset($fields['_version']);
        $fields['version'] = '_version';
        return $fields;
    }
```
If there is no better solution, I think we should update docs with something like that.

**Comment by tunecino** [comment]
Ok. I'll check it again to see if I find a better fix to source code. If not and no body else does I'll do a PR to update docs to recommend using virtual attribute as shown above.
