### ISSUE TITLE
'required' validator doesn't work on update in REST API

### ISSUE THREAD

**Issue by EvgenyOrekhov** [yiisoft/yii2#9134]
I'm working on a REST API.
I extend the default yii\restActiveController and I don't override any actions.
I have this in my model's rules:

``` php
[['status_id', 'priority_id', 'performer_id'], 'required']
```

But when I try to update a record by sending only `{"title":"Some title"}`, it gets updated successfully.
Other core validators work as expected.

**Comment by EvgenyOrekhov** [comment]
The 'default' validator doesn't work too.

**Comment by lynicidn** [comment]
update? what is old values?

**Comment by EvgenyOrekhov** [comment]
@lynicidn old values are different of course.

**Comment by EvgenyOrekhov** [comment]
Looks like the bug doesn't relate to REST API only, just've tried to remove a required `<select>` tag from the page of my web application and hit Submit, the model was saved successfully.

**Comment by lynicidn** [comment]
это апдейт, у тебя там старые значения в аттрибутах, естественно они будут проходить правила - проблемы нет, есть недопонимание твое, как работает апдейт актив рекорда

**Comment by EvgenyOrekhov** [comment]
@lynicidn в правилах `[['status_id', 'priority_id', 'performer_id'], 'required']`
Старый объект: `{"id":1,"status_id":1,"priority_id":1,"performer_id":1}`
Обновляю его, отправляю `{"id":1,"status_id":2}`
Ожидаю, что будет ошибка валидации `"priority_id" and "performer_id" are required`.
Если так и задумано, как тогда нужно указать правило, чтобы в этом примере получилась ошибка валидации?

**Comment by lynicidn** [comment]
почему будет ошибка? там же "priority_id":1,"performer_id":1}

**Comment by lynicidn** [comment]
вот смотри у меня было 3 яблока и 2 груши, я вместо 2 груш положил 4 груши - почему у меня яблоки должны исчезнуть?

**Comment by EvgenyOrekhov** [comment]
@lynicidn Как заставить тебя класть яблоки и груши одновременно и запретить класть одни груши отдельно?
Кстати, старые две груши куда делись вообще?

**Comment by lynicidn** [comment]
никак, посылать надо яблоки-0 груши-4, тогда ты затрешь яблоки и соответственно валидатор скажет, что яблоки обязательны

**Comment by lynicidn** [comment]
:D

**Comment by Faryshta** [comment]
thats because its validating the old values already, status_id is not null because its already set on the db.

**Comment by EvgenyOrekhov** [comment]
@Faryshta This behavior is unexpected. I already have the database layer in my development stack, that ensures that the values are required or defaulted on creation. In my view, the framework should assist in implementing the business logic on a higher level, which includes validating user input data on updates.
Anyway, this behavior has to be clarified in the documentation.

**Comment by Faryshta** [comment]
@EvgenyOrekhov thats the exact expected behavior imo. since you are sending just the title you update just the title.

if you want to change that behavior you can run `$model->status_id = null;` before you run `$model->load($params);`

**Comment by EvgenyOrekhov** [comment]
@Faryshta OK, thanks.
Still, the "Validating Input" guide is kind of confusing. It talks about "inputs", and I figured that rules are for "inputs", but in fact rules are for the model as a whole, and validation applies to the whole model, not just the inputs.
I'd like this issue to be considered as a request to clarify the validation documentation.

**Comment by Faryshta** [comment]
@EvgenyOrekhov which part of the guide you mean? Can you make a PR about it?

**Comment by fernandezekiel** [comment]
validations really mean "validating the current state of the model"

**Comment by EvgenyOrekhov** [comment]
Looks like @qiangxue himself was confused about what the validations mean https://github.com/yiisoft/yii2/commit/83b0b3d480a3de8c549a21aaade04f7857b11e31#diff-e1e996b8f4fad49a953291c4f5fc0931R213

**Comment by fernandezekiel** [comment]
i don't see anything wrong about his comments on that commit @EvgenyOrekhov

**Comment by EvgenyOrekhov** [comment]
@fernandezekiel 
```
* 2. Add a `required` validation rule for the version column to ensure the version value is submitted.
```
Adding a `required` validation rule doesn't ensure the submission, it ensures the presence of the value in the current state of the model. You said it yourself in your previous comment.

**Comment by EvgenyOrekhov** [comment]
I am no longer interested in this. Feel free to reopen if needed.
