### ISSUE TITLE
Why not to use date_default_timezone_get() in \yii\base\Application::preInit() ?

### ISSUE THREAD

**Issue by omnilight** [yiisoft/yii2#9135]
In the `\yii\base\Application::preInit()` method we have the following code:

``` php

if (isset($config['timeZone'])) {
   $this->setTimeZone($config['timeZone']);
   unset($config['timeZone']);
} elseif (!ini_get('date.timezone')) {
   $this->setTimeZone('UTC');
}

```

Why not to rewrite it with:

``` php

if (isset($config['timeZone'])) {
   $this->setTimeZone($config['timeZone']);
   unset($config['timeZone']);
} else {
   $this->setTimeZone(date_default_timezone_get());
}

```

Reason: in some OS (Ubuntu, for example), even if 'date.timezone' setting is not set in the php ini, `date_default_timezone_get` will still return correct system timezone, and even if we are in OS, where this function has different behavior, it will return 'UTC', if can't determine system time zone, see
http://php.net/manual/ru/function.date-default-timezone-get.php

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L482

https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L468

**Comment by omnilight** [comment]
Yes, but when we init our application, it's only check for ini param. If by default getTimeZone returns date_default_timezone_get()'s value, then I do not understand, why it is required to set time zone to UTC in the preInit method

**Comment by lynicidn** [comment]
set it manual in config, UTC it valid for override hosting behavior

**Comment by cebe** [comment]
if you have not set `date.timezone` in your php.ini `date_default_timezone_get()` will trigger a PHP warning so we are not calling it in this case and set a default value.
