### ISSUE TITLE
Migration history limit = 0 does not work

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#9141]
The command's help output says you can use limit=0 to display the whole history:

```
USAGE

yii migrate/history [limit] [...options...]

- limit: integer (defaults to 10)
  the maximum number of migrations to be displayed.
  If it is 0, the whole migration history will be displayed.
```

But this throws an exception:

https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php#L379

**Comment by samdark** [comment]
Docs were not correct. Fixed. Thanks!
