### ISSUE TITLE
gii action "preview" return Bad Request (#400) on subdomain

### ISSUE THREAD

**Issue by unknownfix** [yiisoft/yii2#9142]
My yii2-advanced(2.0.3 & 2.0.5) project is localed on localhost local.projectname.com
Any action "preview" in gii return Bad Request (#400) Unable to verify your data submission but gii have csrf tags on page. Backend and frontent on one subdomain
If host without subdomain - it works perfectly.

**Comment by unknownfix** [comment]
I use example http://www.yiiframework.com/doc-2.0/guide-tutorial-shared-hosting.html#separate-sessions-and-cookies but this not works

**Comment by samdark** [comment]
What's the exact domain name?

**Comment by unknownfix** [comment]
local.lingguru.com

**Comment by unknownfix** [comment]
This unworked gii project https://github.com/unknownfix/yii2-advanced-modules-start without separated  sessions and cookies
