### ISSUE TITLE
Problem with dataprovider when there are parameters in select. 

### ISSUE THREAD

**Issue by alexweb** [yiisoft/yii2#9143]
I have this code in model's search() method: 
```php
        $query = Place::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

                $query->select([
                    'places.*',
                    '(6371 * acos( cos( radians(:latitude) ) * cos( radians( geo_lat ) )
                       * cos( radians(geo_lon) - radians(:longitude)) + sin(radians(:latitude))
                       * sin( radians(geo_lat)))) AS distance' // in km
                ])
                ->params([
                    ':longitude'=>$this->geo_lon,
                    ':latitude'=>$this->geo_lat,
                    ':distance'=>5, //in km
                ])
                ->having('distance < :distance')
                ->orderBy('completion');

        return $dataProvider;
```
It returns correct data but when I'm using it with GridView it shows error about incorrect number of PDO parameters: 

"message": "SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens\nThe SQL being executed was: SELECT COUNT(*) FROM `places` ... 

This happens when DataProvider tries to execute COUNT request to build pagination. 

Any ideas how to fix it?

**Comment by Alex-Code** [comment]
This is a bit of an awkward one.

You could set the count value yourself. *This might not be valid, just of the top of my head*
```php
$count = (new Query)->from(['c' => $query])->count();
$dataProvider->totalCount = (int)$count;
```

**Comment by chrisb88** [comment]
I think I remember setting the params at the end fixes such problems. Try placing the params() after order().

**Comment by Alex-Code** [comment]
@chrisb88 That would work if `having()` wasn't used but the select is needed to filter the results.

**Comment by klimov-paul** [comment]
You must calculate `DataProvider::totalCount` by separated query yourself in this case.

The problem occurs because `ActiveDataProvider` performs automatic calculation of `totalCount` using `Query` object stripped from 'select'. If there are any bound parameters in select, data provider can not determine it and can not exclude from `Query::params`.

**Comment by nirvana-msu** [comment]
I have the same issue. Would be nice if `select()` method could accept optional array with parameters to bind, just like `where()` does. That way, `DataProvider` would know to exclude those parameters (together with the whole `select` part) when calculating `totalCount`.

**Comment by arievanden** [comment]
If this helps anybody, you can insert this before passing to Gridview.

// workaround to correct record count issue
// ref. https://github.com/yiisoft/yii2/issues/9143
$dataProvider->setTotalCount(count($dataProvider->getModels()));
