### ISSUE TITLE
PHP Notice when using arabian language

### ISSUE THREAD

**Issue by alexweb** [yiisoft/yii2#9144]
PHP Notice – yii\base\ErrorException
Use of undefined constant ‎ - assumed '‎'

    1. in W:\domains\mysite\vendor\yiisoft\yii2\messages\ar\yii.php at line 102
    93949596979899100101102

        '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}' => '{nFormatted} جيجابايت',
        '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}' => '{nFormatted} كيبيبايت',
        '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}' => '{nFormatted} كيلوبايت',
        '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}' => '{nFormatted} ميبيبايت',
        '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}' => '{nFormatted} ميجابايت',
        '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}' => '{nFormatted} بيبيبايت',
        '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}' => '{nFormatted} بيتابايت',
        '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}' => '{nFormatted} تيبيبايت',
        '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}' => '{nFormatted} تيرابايت',‎

**Comment by alexweb** [comment]
My PhpStorm shows error in W:\domains\mysite\vendor\yiisoft\yii2\messages\ar\yii.php at line 101. Looks like there is some unicode trash symbol. When I removed it everything works well. Please check it.

**Comment by cebe** [comment]
is it fixed by #9136 ?

**Comment by alexweb** [comment]
Yes, thanks
