### ISSUE TITLE
Migation command error should specify directory path missing

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#9149]
Current output:

```
$ yii migrate
Error: Migration failed. Directory specified in migrationPath doesn't exist.
```

Should specify directory path.

Alternative is to create directory automatically.

**Comment by cebe** [comment]
auto creation does only make sense on migration create, when running a typo in config should not create random directories.

**Comment by RusAlex** [comment]
And this logic already implemented in the BaseMigrateController.php

https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php#L73

It throws Exception in case when action not 'create'
