### ISSUE TITLE
Massive assignment not working with arrays (feature request)

### ISSUE THREAD

**Issue by kmergen** [yiisoft/yii2#9152]
In my models i often have array attributes.
But this attributes cannot be set massive because the array_flip function only accept integer or string values. Is there a possibility to set this attributes massive via load function?

**Comment by cebe** [comment]
can you elaborate on where `array_flip` is used and why this is a problem?

**Comment by kmergen** [comment]
For example if I have a model with images.
Therefore I use my own ActiveRecord Class where I have  a property 'images';
This property is an array in the following form:

```php
Array ( [0] => Array ( [fid] => 321 [uri] => images/hunderasse/Affenpinscher_1_9.jpg ) [1] => Array ( [fid] => 322 [uri] => images/hunderasse/Akbash_1.jpg ) )
```

**Comment by kmergen** [comment]
I tried something out not to set the images value manually and ended up with overriding the load function for my need.
