### ISSUE TITLE
Debug output makes no sense for long folder structures and classnames

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#9153]
This is one of the many examples :)
The folder - ns/class (params) line is unreadable (check on the right side).

<img width="1377" alt="screen shot 2015-07-19 at 15 53 27" src="https://cloud.githubusercontent.com/assets/880939/8766201/7b8d4212-2e2e-11e5-84dd-2f92b3923413.png">

**Comment by pana1990** [comment]
duplicated https://github.com/yiisoft/yii2/issues/4763
