### ISSUE TITLE
Cookie could not be read

### ISSUE THREAD

**Issue by stratoss** [yiisoft/yii2#9158]
I'm setting-up a cookie before facebook login, then in the callback function I'm trying to retrieve it.

It is accessible through $_COOKIE, but not with Yii::$app->getRequest()->getCookies()->getValue().

Example:
```
$cookie1 = Yii::$app->getRequest()->getCookies()->getValue('actionAfterLogin');
$cookie2 = $_COOKIE['actionAfterLogin']);
var_dump($cookie1);
var_dump($cookie2);
```

outputs:
```
null
string '{"test":1}' (length=10)
```

**Comment by klimov-paul** [comment]
What is the value of `Request::enableCookieValidation`?
How do you set your cookie? Provide a code snippet.

**Comment by stratoss** [comment]
`Request::enableCookieValidation` is `true`, probably that is the case. I'm setting the cookie from the user end, using. [this plugin] (https://github.com/js-cookie/js-cookie)

**Comment by klimov-paul** [comment]
> which is the best way to set a cookie from the browser, which will pass the validation?

There is no such way, because you'll beed the cookie validation secret key, which should never leave the server side.

**Comment by kidol** [comment]
@klimov-paul Might make sense to add property to `Request` which holds a whitelist of cookie names which should be skipped for hmac validation.

**Comment by stratoss** [comment]
@kidol I agree with you, this way one will not be forced to play with `$_COOKIE` just because of one cookie set in the frontend.

**Comment by apptut** [comment]
I encountered the same problem ! I set some cookie by Javascript but do not get the value by yii 。Finally， I only choose the `$_Cookie['status']` indead of `Yii::$app->request->getCookies()->value('status');`
