### ISSUE TITLE
GridView: emptyCell attribute not working

### ISSUE THREAD

**Issue by gb5256** [yiisoft/yii2#9159]
I am trying this: 

     <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'emptyCell'=>'-',
         ...
If have some cells which are NULL. But I can not set the emtpyCell to be something different than the default, which is "(not set)".
Am I doing something wrong?
I am using yii 2.05

Thanks for any ideas,
gb5256

**Comment by hiscaler** [comment]
You will setting formatter 'nullDisplay' attribute in 'components' section in you config file.

```php
 'formatter' => [
            'nullDisplay' => '-'
 ],
```

**Comment by cebe** [comment]
yeah, this was not really clear from the docs, I have added a note.
