### ISSUE TITLE
[Doc] How can change LinkPager attribute

### ISSUE THREAD

**Issue by dungphanxuan** [yiisoft/yii2#9165]
Hello. I using listview to render item. So on Linkpager, i want to change some attribute.
Example

http://.../?page=1&per-page=5

to 
http://.../?pagename=1

also hide per-page=5 parameter.
thank!

**Comment by klimov-paul** [comment]
@dungphanxuan, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
