### ISSUE TITLE
Why View::registerJs is not static

### ISSUE THREAD

**Issue by macklay** [yiisoft/yii2#9166]
Method registerJs of ANY view actually add script to body end. 
Why we call not static method View::registerJs and save scripts in currently actual view instance?
I was trying to render one view instance with scripts separately, but I did not find how to do it.

If render view instance(with his scripts) separately is impossible, why method registerJs is not static?  Or, if its possible, how to do it?

**Comment by klimov-paul** [comment]
Please provide a code snippet, which can reproduce your problem.

**Comment by macklay** [comment]
Some widget view:
```php
<script type="html/template">
<?php $form = ActiveForm::begin(['view'=>$this]); ?>
    <?= $form->field($model, 'name') ?>
    <?= Html::submitButton('Submit', []) ?>
<?php ActiveForm::end(); ?>
// Im try put active form register script here(by default yii put form script at the body end and I have an error because form tag is not in DOM but in the script template)
</script>
```

**Comment by nkostadinov** [comment]
It will be really nice to be able to render the client script any time and place that you want. I had similar issues which I worked around. Sometimes you want just the client script without including the js/css files.

**Comment by klimov-paul** [comment]
You may use `View::endPage()` to enforce parsing already rendered content as a page.
You'll have to place `View::PH_BODY_END` at your template at the place you wish your JS to be rendered.

**Comment by macklay** [comment]
When Im try use View::PH_BODY_END Im get all inline scripts and script with src. Furthermore, Im have duplicate of js at the end of body.

**Comment by klimov-paul** [comment]
In this case it is obvious you can not create a template with yii.activeform js involved.
You should create other widget or disable `ActiveForm::enableClientScript`.

**Comment by nkostadinov** [comment]
Yes you can but this is a limitation of the framework especially if you have ajax interface. There should be an easy way to control this behavior. Now there are a couple of workarounds e.g. http://www.yiiframework.com/extension/nlsclientscript/ . 
One case is that I have included all the required JS in the page, and after that when I render partial views with JS components there I want only the script part without the inclusion of the JS files. How can this be achieved ?

**Comment by klimov-paul** [comment]
You should create your own `View` class.

**Comment by nkostadinov** [comment]
Yes @klimov-paul  that's alway a solution. But my point is - wouldn't it be nice if its part of the framework thus making it more flexible and more ajax friendly :) 

You can close the issue, but think about it.
