### ISSUE TITLE
UrlRule can not match chinese character

### ISSUE THREAD

**Issue by boultra** [yiisoft/yii2#9167]
If we want to match chinese charator in rule,we should use PCRE_UTF8
UrlRule.php line 151
`
$this->pattern = '/' . $this->pattern . '/';
`
should like this:
`
$this->pattern = '/' . $this->pattern . '/u';
`
read more about it:
https://secure.php.net/manual/en/reference.pcre.pattern.modifiers.php

**Comment by samdark** [comment]
@boultra can you give me example rule and example URL to test with?

**Comment by boultra** [comment]
url:
`
http://www.xxx.cn/3-2-1--好-的-1-30
`
after encode
`
http://www.xxx.cn/3-2-1--%E5%A5%BD-%E7%9A%84-1-30
`
Note:in chrome,the url display as chinese not unicode,when i copy it and paste here,it will convert to unicode
 rule:
`
'/<b:\d{1}>-<r:\d{1}>-<t:\d{1}>-<f:[a-z0-9]*>-<k_cn:[\x{4e00}-\x{9fa5}-zA-Z0-9%]*>-<k_pn:[\x{4e00}-\x{9fa5}-zA-Z0-9%]*>-<pg:\d{1,2}>-<pgs:\d{1,2}>'=>'/xxx/xxx',
`

**Comment by boultra** [comment]
@samdark Can you test it?

**Comment by klimov-paul** [comment]
Usually not encoded UTF cahracters are not aallowed in URL.

> Note:in chrome,the url display as chinese not unicode

Modern browsers usually hide url-encoding replacing it with actual text for better user experience.

Please check via Firebug or Chrome web-development tool the actual HTTP request sent to the server ('network' tab). What URL does it display?

**Comment by boultra** [comment]
I checked it ,It's encoded url ,but why i cannot match the url rule when I use chinese charactor?
@klimov-paul

**Comment by klimov-paul** [comment]
I am unable to reproduce the issue.
Pattern 'post/<slug:\x{044F}+>' parses URL 'post/я' correctly without extra PCRE modifiers.
I am even able to use pattern 'post/<slug:[а-я]+>' correctly without any modifiers.

**Comment by samdark** [comment]
@boultra you have missing character in your regex: `\x{4e00}-\x{9fa5}`**a**`-zA-Z0-9%`.

**Comment by samdark** [comment]
I've verified that it works the following way:

- Install basic app.
- In components config add the following:

```php
'urlManager' => [
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'rules' => [
         'test/<word:[\x{4e00}-\x{9fa5}a-zA-Z0-9%]*>' => 'site/index',
    ],
],
```

- At `views/site/index.php` add the following:

```php
<?php echo Yii::$app->request->get('word') ?>
```

- Follow `http://example.com/test/好`.
- See `好` outputted on the page.

**Comment by boultra** [comment]
OK,I will test again.Thanks
