### ISSUE TITLE
choose simple chinese language error

### ISSUE THREAD

**Issue by ivantree** [yiisoft/yii2#9171]
error	 yii\i18n\PhpMessageSource::loadMessages	
The message file for category 'yii' does not exist: D:\wamp\www\protected\vendor\yiisoft\yii2/messages/zh_cn/yii.php Fallback file does not exist as well: D:\wamp\www\protected\vendor\yiisoft\yii2/messages/zh/yii.php

**Comment by cebe** [comment]
locale setting has to be `zh-CN` instead of `zh_cn`: https://github.com/yiisoft/yii2/tree/master/framework/messages/zh-CN
