### ISSUE TITLE
Change cost for generatePasswordHash when testing

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9177]
With the current default cost of 13, every generation of password goes at cost of performance of the testing process of at least 600ms per occurence.

Because tests dont need to be delayed by this cost, it would be a nice idea to lower the cost for generatePasswordHash during YII_ENV_TEST. Setting the value to 4 will work great, almost instantly. Anythin below is giving issues (dont know why).

This would cut my total testing length with many seconds.

**Comment by samdark** [comment]
That's interesting proposal. Could be used for framework tests as well.

**Comment by dynasource** [comment]
from idea to reality in 1 day. Thumbs up.
