### ISSUE TITLE
Query Caching always return old data

### ISSUE THREAD

**Issue by sadovojav** [yiisoft/yii2#9179]
Yii2: 2.0.5 PHP: 5.4 MySQL: 5.5

```php
        $result = $db->cache(function ($db) {
            $sql = 'SELECT *
                FROM ' . Date::tableName() . '
                ORDER BY date DESC
                LIMIT :limit';

            $command = $db->createCommand($sql);
            $command->bindParam(':limit', $this->limit);

            return $command->queryAll();
        }, 300);
```
This code always return old cache data, and does not return update data.
Used this yii\caching\FileCache

**Comment by samdark** [comment]
Event after 300 seconds?

**Comment by sadovojav** [comment]
@samdark Yes, after 300 seconds I have old info.
During this time (300) I update page. Single Update page is one plus to the counter.
I updated the page tenfold, during 300 seconds, stay 5 minutes, and reload the page where it was to see the new result. But result was the same. I saw old info.
If I used Yii::$app->cache->flush(), and reload result page, i saw new info.

I tried to use yii\caching\DbCache, and it correctly work

**Comment by samdark** [comment]
What's are PHP version, OS and file system you're using? Also which user/group runs PHP and which user/group is the owner of the cache file?

**Comment by sadovojav** [comment]
On Prod.
1. PHP Version 5.4.42-1~dotdeb+6.4
2. Debian 6
3. Linux preparty 2.6.18-348.16.1.el5.028stab108.1PAE #1 SMP Tue Aug 27 13:55:08 MSD 2013 i686

On Dev:
1. OpenServer - PHP Version 5.4.35
2. Windows 7

Group and owner is  www-data. 
On dev machine I don't have any forbiddance. I have admin/root rights, but cache duration does not work.

**Comment by samdark** [comment]
So it doesn't work on both?

**Comment by sadovojav** [comment]
Yes it is. And now i testing it in MAMP 3.3 PHP 5.6.1, and this cache does not update to. Update after cache->flush() only.

**Comment by kidol** [comment]
Can't reproduce this.

Do you use any other caching that could be the cause, like page cache?

If not, try with this test case:

```php
$result = Yii::$app->db->cache(function() {
    return Yii::$app->db->createCommand("SELECT RAND()")->queryScalar();
}, 1);

// Should show new random number every second
var_dump($result); exit;
```

If this also doesn't work, add here: https://github.com/yiisoft/yii2/blob/master/framework/caching/FileCache.php#L110

```php
var_dump(filemtime($cacheFile), time());
```

Then post var_dump output...

**Comment by sadovojav** [comment]
Sorry for late answer. I found a bug. It has been cached on the client. I use the client cache. And I forget about him. Sorry for your time.
