### ISSUE TITLE
Flash message is not displayed when refresh/redirect

### ISSUE THREAD

**Issue by houmamwazzeh** [yiisoft/yii2#9187]
I reviewed the issues #2510 & #4415 but I still face the same problem. I display a contact form in the footer, so it is displayed in all pages, so I process the contact submition in beforeAction() method as follows:
```php
class Controller extends \yii\web\Controller {
    public function beforeAction($event)
    {
        if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
        {
            $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
            \app\components\Flash::success($m);
            return $this->refresh();
        }
        return parent::beforeAction($event);
    }
}
```

All my controllers are sub-classes from the above class and I use a special class to manage flash messages:

```php
class Flash
{
    public static function add($type, $message)
    {
        \Yii::$app->session->addFlash('app-flash-message',[
            'type' => $type,
            'message' => $message
        ]);
    }

    public static function success($message)
    {
        self::add('success', $message);
    }

    public static function render()
    {
        $messages = \Yii::$app->session->getFlash('app-flash-message');
        if(! $messages )
            return '';
        // ELSE:
        ob_start();
        ob_implicit_flush(false);
        echo Html::beginTag('div', ['class'=>'flash-overlay']);
        echo Html::tag('div', '', ['class'=>'overlay']);
        echo Html::beginTag('div', ['class'=>'inner']);
        echo Html::tag('div', Html::a('&times;', '#'), ['class'=>'close-area']);

        foreach ($messages as $flash)
        {
            echo Html::tag('div', $flash['message'], ['class'=>'alert alert-'.$flash['type']]);
        }
        echo Html::endTag('div');   // inner
        echo Html::endTag('div');   // gr-msg-overlay

        $view = \Yii::$app->controller->getView();
        $view->registerJs("
            \$('.flash-overlay .close-area a').click(function(){
                \$('.flash-overlay').remove();
            })
        ");

        return ob_get_clean();
    }
}
```
Finally, I call Flash::render() in my layouts/main.php file to display the flash messages, but unfortunately, they are not displayed in this case. If I omit the line **return $this->refresh();** the message will be displayed, but in this case, the form will be re-submited when the user refresh (F5) the page.

Here is a part of the composer.json file:
```
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.4",
        "yiisoft/yii2-jui": "~2.0.0",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "bower-asset/slicknav": "*"
    },
```

**Comment by samdark** [comment]
Yep. That's because you're getting flash message right before redirect. And it's being removed at the time.

**Comment by houmamwazzeh** [comment]
I could not understand? How do I get the flash messages before the redirection?

The place where I retrieve the message is in layouts/main.php and this requires a view to be rendered. And I do not render any view before the redirection.

**Comment by samdark** [comment]
Need the code where you're doing redirect.

**Comment by houmamwazzeh** [comment]
it is just the above code, I mean in beforeAction(). The idea is I put the contact form in the footer so it will be displayed in all views and I handle the contact submission in beforeAction(). If the form is submitted, I process it and then refresh the page.

I need to refresh the page to prevent resubmitting the form when a visitor refresh the page from the browse.

That is all

**Comment by mikehaertl** [comment]
If you don't return `false` from `beforeAction()`, your action will still get executed and thus the view will get rendered - even if it's not sent to the client due to the redirect.

**Comment by samdark** [comment]
Yep. Good catch.

**Comment by houmamwazzeh** [comment]
Thanks @mikehaertl I modified my beforeAction() to be as follows:
```php
public function beforeAction($event)
    {
        if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
        {
            $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
            \app\components\Flash::success($m);
            $this->refresh();
            return false;
        }
        return parent::beforeAction($event);
    }
```
Now, the flash message is displayed but duplicated and I get two emails. That means the request is processed twice :(

In the first case, the form is processed just one time but the messaged is not displayed. After the modifcation, the form is processed twice: two emails with two flash messages.

I am looking for a solution for this trick. Maybe the way I use to process the form submission is wrong..

**Comment by freezy-sk** [comment]
@houmamwazzeh I think better handling of `beforeAction` is like it's done in `yii\web\Controller` so your code with this little modification should look like this
```
public function beforeAction($action)
{
    if (parent::beforeAction($action)) {
        if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
        {
            $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
            \app\components\Flash::success($m);
            $this->refresh();
            return false;
        }

        return true;
    }
        
    return false;
}
```

**Comment by houmamwazzeh** [comment]
Thanks @freezy-sk . I tried your suggestion but the same problem, I mean, the form is processed twices, so I had two emails with two flash messages. Even though if I use your version with **return $this->refresh()** 
```php
public function beforeAction($action)
{
    if (parent::beforeAction($action)) {
        if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
        {
            $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
            \app\components\Flash::success($m);
            return $this->refresh();
        }

        return true;
    }

    return false;
}
```

I get two emails but without any flash message.

I wounder if I miss something.. ???

**Comment by houmamwazzeh** [comment]
Let us describe the problem again.
I process a form in the controller, I add a flash message, then I do a redirection through refresh() method.
While I do the processing in the controller, that means no view has been rendered yet, even thought (no view had been rendered) the flash message is cleared.
I read the flash messages in the layouts/main.php, that means the flash message must not be cleared until a view is rendered.

The only trick in my problem is I use the beforeAction() method. That is why I do the form processing before the parent::beforeAction(). This will help me break the context and refresh the page if the form is submitted. But the flash messages are being cleared when I refresh the page :sob:

**Comment by mikehaertl** [comment]
@houmamwazzeh Are you using method `get` in your forms? If so, then each `refresh()` will contain the same form data and trigger your form processing.

Apart from that I think this is the wrong place for discussing this. Github is for tracking bugs.

**Comment by mikehaertl** [comment]
@houmamwazzeh Final note: in `beforeAction()` you should **not** use `return $this->refresh()` as this will always return a `true`ish value, which again will not block your action from exection. The correct code is:

```
$this->refresh();
return false;
```

**Comment by freezy-sk** [comment]
@houmamwazzeh As @mikehaertl pointed, don't return value of `$this->refresh()`. And solution for your problem is that you are calling `refresh()` instead of `redirect()`. Every time after successful form submission, call `redirect()` to prevent resubmission of form. You can redirect to current url when you specify redirect url as empty string `''`.

**Comment by mikehaertl** [comment]
@freezy-sk `refresh()` is pretty much the same as `redirect()` to the current URL. So `refresh()` is perfectly fine in his case.

**Comment by houmamwazzeh** [comment]
@mikehaertl I use POST not GET.

I get Two emails with two flash messages with this code (that mean the request is processed twice):
```
if (parent::beforeAction($action)) {
    if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
    {
        $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
        \app\components\Flash::success($m);
        $this->refresh();
        return false;
    }
    return true;
}
return false;
```
The same case for this code:
```
if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
{
    $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
    \app\components\Flash::success($m);
    $this->refresh();
    return false;
}

return parent::beforeAction($action);
```
@freezy-sk refresh() is an alias to redirect('').

**Comment by houmamwazzeh** [comment]
every thing is OK without the two lines:
```
$this->refresh();
return false;
```
But I need a way to prevent form resubmitting when refresh the page from the browser (F5, ctrl-R)

**Comment by houmamwazzeh** [comment]
After doing some DEBUG, I discovered that the problem comes from the client side where the form was submitted TWICE, because I use a JavaScript to process the form and submit it.

The both suggestions woks fine now:
```php
public function beforeAction($event)
{
    if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
    {
        $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
        \app\components\Flash::success($m);
        $this->refresh();
        return false;
    }
    return parent::beforeAction($event);
}
```
```php
public function beforeAction($event)
{
    if(parent::beforeAction($event)) {
        if ($this->footerContact->load(\Yii::$app->request->post()) && $this->footerContact->contact(\Yii::$app->params['infoEmail']))
        {
            $m = \Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.');
            \app\components\Flash::success($m);
            $this->refresh();
            return false;
        }
        return true;
    }
    return false;
}
```


Sorry for bothering you for nothing worthy :disappointed:.

Thanks.
