### ISSUE TITLE
Captcha issue

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#9190]
Captcha doesn't works if yii\web\DbSession is used.

STR:

- create empty advanced application project
- set class of the 'session' component to yii\web\DbSession
- captcha validation always failed

**Comment by klimov-paul** [comment]
Do you able to actually store any data inside the session using `yii\web\DbSession`?

**Comment by usualdesigner** [comment]
@klimov-paul yes, everything other works fine.

**Comment by usualdesigner** [comment]
Guys, can I provide some other details for you?

**Comment by RusAlex** [comment]
just tried. 

1. installed advanced app
```shell
composer create-project --prefer-dist yisoft/yii2-app-advanced advanced
php init #sets development environment
```

2. set database password in common/config/main-local.php

3. created session table
```mysql
      CREATE TABLE session
      (
          id CHAR(40) NOT NULL PRIMARY KEY,
          expire INTEGER,
          data BLOB
      )
```

4. Opened contact form in frontend application. And submitted. Form submitted well.
