### ISSUE TITLE
response component set format not work in browser

### ISSUE THREAD

**Issue by jk2K** [yiisoft/yii2#9192]
main.php
```php
'components' => [
        'response' => [
            'format' => yii\web\Response::FORMAT_JSON,
        ],
```
UserController.php
```php
<?php
namespace backend\controllers;

use yii\rest\ActiveController;

class UserController extends ActiveController
{
    public $modelClass = 'common\models\User';
}
```
visit `/user` chrome return xml response
how to get json response

**Comment by cebe** [comment]
your browser seems to send an accept header which includes XML and ActiveController supports both by default. You need to either disable XML in the API or use an HTTP tool to get responses from your api instead of using the browser directly.

**Comment by jk2K** [comment]
how to disable XML in the API

**Comment by jk2K** [comment]
how to disable xml in the api?

**Comment by cebe** [comment]
it is described in the guide: http://www.yiiframework.com/doc-2.0/guide-rest-response-formatting.html#content-negotiation
