### ISSUE TITLE
Foreign key rules breaks validation

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#9195]
I have 2 tables which are linked by foreign key. After last update Gii generates validation rule like 
```
...
            [['cvID'], 'exist', 'skipOnError' => true, 'targetClass' => CV::className(), 'targetAttribute' => ['id']],
...
```
And while inserting new row into this table, during validation I get:

```"cvID is invalid"``` error

I'm 100% sure that such cvID presents in CV table.

When I remove this rule, everything works ok.

What am I doing wrong?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-gii/issues/64

**Comment by Faryshta** [comment]
Change it to.

`[['cvID'], 'exist', 'skipOnError' => true, 'targetClass' => CV::className(), 'targetAttribute' => 'id'],`
