### ISSUE TITLE
请问如何添加bower-asset 包

### ISSUE THREAD

**Issue by windsdeng** [yiisoft/yii2#9196]
类似
bower-asset/jquery.inputmask: 3.1.*
bower-asset/punycode: 1.3.*
bower-asset/yii2-pjax: >=2.0.1

如果自己要发布一些插件如何操作
是发到bower.io ？

**Comment by cebe** [comment]
would you mind writing in english? Its hard to help otherwise.

**Comment by lichunqiang** [comment]
你自己的插件如果不想让别人用的话，可以在本地啊，不一定要发布到bower

两个方案：

1. 放到web目录，在assetbundle把basepath指向`@webroot`即可

2. 放到一个公共目录「非web目录」，像下载的bower资源一样，将assetbundle的`sourcePath` 指向你的目录就可以了

如果你是真的想发布到bower上，供大家使用就根据文档来吧http://bower.io/docs/creating-packages/

你还可以发布到npm https://docs.npmjs.com/getting-started/publishing-npm-packages
