### ISSUE TITLE
[Feature] Visible of buttons in ActionColumn

### ISSUE THREAD

**Issue by fornit1917** [yiisoft/yii2#9198]
Hi. My english is very bad, i'm sorry.

I want to manage visible of buttons in ActionColumn (GridView). In current version we have the next solution: https://github.com/yiisoft/yii2/blob/5c79ab202cce74048957dce586d7ef2796908138/framework/grid/ActionColumn.php#L70

But i want set only boolean value for this. Example:

```php
'buttonsVisible' => [
      'update' => \Yii::$app->user->can('update'),
      'delete' => function($model){
            return \Yii::$app->user->can('delete') && $model->status != Status::DELETED
       },
 ]
```

That is, I want to separate setting html-content of buttons in ActionColumn and setting visibility of this buttons.
To do this, we can add the parameter buttonsVisible to yii\grid\ActionColumn and modify of method renderDataCellContent:

```php
namespace yii\grid;
class ActionColumn 
{
    public $buttonsVisible = [];


    protected function renderDataCellContent($model, $key, $index)
    {
        return preg_replace_callback('/\\{([\w\-\/]+)\\}/', function ($matches) use ($model, $key, $index) {
            $name = $matches[1];

            if (isset($this->buttonsVisible[$name])) {
                $visible = is_callable($this->buttonsVisible[$name])
                    ? call_user_func($this->buttonsVisible[$name], $model)
                    : $this->buttonsVisible[$name];
            } else {
                $visible = true;
            }

            if ($visible && isset($this->buttons[$name])) {
                $url = $this->createUrl($name, $model, $key, $index);
                return call_user_func($this->buttons[$name], $url, $model, $key);
            } else {
                return '';
            }
        }, $this->template);
    }   
}
```

I can prepare a pull request.
What do you think?

**Comment by samdark** [comment]
So you suggest `buttonsVisible` to be a set of callbacks? One for each button?

**Comment by dizews** [comment]
good suggestion!

**Comment by fornit1917** [comment]
buttonsVisible is parameter of ActionColumn. It may contain conditions display some buttons. Each condition - a boolean value, or a function that returns a Boolean value.

Т.е. buttonsVisible - это параметр колонки ActionColumn, который представляет собой массив, ключами которого будут идентификаторы кнопок в колонке ActionColumn, а значениями - условия, при которых ту или иную кнопку нужно показывать (условие - это либо булево значение, либо функция от модельки, которая возвращает булево значение). 
Этот параметр не обязательный. Перечислять в нем все кнопки также не обязательно - по умолчанию visible для кнопки будет true (т.е. логика отображения кнопок в этом случае будет такая же, как в текущей версии фреймворка, обратная совместимость не нарушится).

**Comment by samdark** [comment]
OK. Overall sounds like a good addition.

**Comment by fornit1917** [comment]
good, I'll do it in a few day

**Comment by pana1990** [comment]
duplicated https://github.com/yiisoft/yii2/issues/6162

**Comment by fornit1917** [comment]
my implementation: https://github.com/yiisoft/yii2/pull/9206

**Comment by fornit1917** [comment]
Good afternoon. Why do you still not merge my pull request? It have some problems?

**Comment by SilverFire** [comment]
Hello. I've answered in your PR. Let's continue disquisition there

**Comment by fornit1917** [comment]
Hello. Thank you for review. I agree with your comments. I'll fix all in the near future.

**Comment by pana1990** [comment]
@SilverFire can you close this issue https://github.com/yiisoft/yii2/issues/6162 (it is duplicated with this issue)?

**Comment by SilverFire** [comment]
@pana1990 yeah, it's a duplicate. I'll close it simultaneously with this issue, thank you!
