### ISSUE TITLE
Mailer & initial viewPath 

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9200]
Currently, the viewPath of \Yii::$app->mailer sets the central path for email. This requires you:
- either to install all default emails from every module in the central email path (extra work)
- either to use @aliases for the viewFile at the compose function in combination with the next point:
- either to use pathMaps with the theme (making the whole software slower)

Wouldnt it be logical to provide extra information to the mailer to:
- to point to a viewFile which always exists
- if a identical custom file exists in the mailer::@viewPath, it takes this one?

Perhaby by checking 2 viewPaths. First the one centrally, then the default one, if defined

Advantages:
- faster: prevent the use of pathMaps & themes or local copying
- easier: no need to use pathMaps
- flexible: default mails can be used + custom mails
- stable: less errors in new projects because of missing mails in central viewPath

**Comment by PommeVerte** [comment]
> - either to use @aliases for the viewFile at the compose function in combination with the next point:
> - either to use pathMaps with the theme (making the whole software slower)

Does this even work? I can't seem to get it working. I'm following a similar methodology to the following post with the difference that my pathMap values are full paths and not aliases : http://www.yiiframework.com/forum/index.php/topic/59859-how-can-i-override-a-mail-view-of-a-package/

Any help with getting this sorted would be awesome. I'm surprised it's been such a struggle.

**Comment by klimov-paul** [comment]
I can not see how mailer compoent can take current module (controller) into account, while rendering views. Such behavior is possible in the scope of `yii\base\Controller` as it implements `yii\base\ViewContextInterface` and thus determines the location of the view files.

Being a global component `mailer` can not vary view path depending on current module or controller as it will be inconsistent, even while technically it is possible.

**Comment by klimov-paul** [comment]
If you wish email view path vary depending on controller, you should use controller methods for the view rendering instead of the one built-in mailer component:

```php
class FooController extends Controller
{
    public function actionMail()
    {
        $message = Yii::$app->mailer->compose();
        $message->setTextBody($this->render('mail-view', ['message' => $message]));
        // ...
        $message->send();
    }
```
