### ISSUE TITLE
Model::loadMultiple() guide vs phpdoc

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#9204]
We have inconsistency in `Model::loadMultiple()` description.

phpdoc says:

> * @param array $models the models to be populated. Note that all models should have the same class.

While in the guide there's example with 2 models of different classes: https://github.com/yiisoft/yii2/blob/master/docs/guide/input-multiple-models.md

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/yii2/issues/8009

**Comment by Faryshta** [comment]
that example on the guide is very problematic. first of all, it will return true if at least one of the models load. Which means it will enter the `if` statement even when one of the forms is missing.

i vote for rewriting the guide.

**Comment by samdark** [comment]
@qiangxue it seems both code and guide were done by you. Which one should be considered correct?

**Comment by qiangxue** [comment]
The guide is not right. Should use `load()`. `loadMultiple()` is for loading multiple models of the *same* class.

**Comment by samdark** [comment]
OK, will fix it.
