### ISSUE TITLE
Package yiisoft/jquery is abandoned

### ISSUE THREAD

**Issue by atiberius** [yiisoft/yii2#9211]
Suddenly, after a 'composer update' I got: "Package yiisoft/jquery is abandoned, you should avoid using it. No replacement was suggested." and then the whole framework stopped working with message:
'Calling unknown method: yii\web\UrlManager::addRules()'. I verified the UrlManager class and it is right where is supposed to be. I suspect it has something to do with that message about jquery.
I tried doing this with no result: composer global require "fxp/composer-asset-plugin:1.0.*@dev"
Any ideas on why this happened and how to solve it? I am effectively stuck, cannot work on the project anymore because the framework fails and cannot test anything.

**Comment by cebe** [comment]
Looks like you have some conflict in your composer requirements and composer solved it by installing the alpha version of yii.

Do you have a minimum stability setting? Try to set it to stable.

You may also paste your composer.json file so we can take a look.

**Comment by atiberius** [comment]
I did these:
1. changed to minimum-stability from 'dev' to 'stable'
2. composer global require "fxp/composer-asset-plugin:~1.0.0"
3. composer update
Got this:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Removal request for yiisoft/yii2 == 2.0.0.0-beta
    - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.0-beta].*

**Comment by cebe** [comment]
you had installed a dev version  of jquery before, downgrade does not easily work, this is a speed optimization of the composer asset plugin. You can solve this by removing the vendor directory and run composer update again. More information here: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/faqs.md#composer-throws-an-exception-stating-that-the-version-does-not-exist

**Comment by atiberius** [comment]
Thanks a lot!
Deleting vendor and composer update again solved it.
