### ISSUE TITLE
Required Validator ignores skipOnEmpty in clientValidation

### ISSUE THREAD

**Issue by snorrsi** [yiisoft/yii2#9213]
According to the code in yii.validate.js it does not act regarding to the settings of skipOnEmpty.
It is possible to allow empty values to be validated by using strict as true (when requiredValue is not set it does not affect the outcome.
Is it however the correct behaviour ? , as skipOnEmpty one of the parameters for the validator it seems strange.

Code from yii.validate.js , require part
```javascript
required: function (value, messages, options) {
            var valid = false;
            if (options.requiredValue === undefined) {
                var isString = typeof value == 'string' || value instanceof String;
                if (options.strict && value !== undefined || !options.strict && !pub.isEmpty(isString ? $.trim(value) : value)) {
                    valid = true;
                }
            } else if (!options.strict && value == options.requiredValue || options.strict && value === options.requiredValue) {
                valid = true;
            }

            if (!valid) {
                pub.addMessage(messages, options.message, value);
            }
        },
```

**Comment by Faryshta** [comment]
isn't that what required means?

**Comment by snorrsi** [comment]
Pretty much, but it can actually be defined and is defined in the validator itself.
´´´php
public $skipOnEmpty = false;
´´´
However the issue I had was more complex as I am rewriting a yii application.
I though my error was related to this, but is due to how client validation was set by default for all ActiveForm fields.
This actually works as designed, if skipOnEmpty is never set to true.
It can though due to the variable being public. Might be good to mention that in the comments for the variable

**Comment by Faryshta** [comment]
some properties for the validators act only on client level and others on server level. `skipOnEmpty` acts only on server level. What you require is to check the `whenClient` attribute

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
