### ISSUE TITLE
ExistValidator::allowArray does the exact opposite of the documented behavior

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#9214]
The issue is here https://github.com/yiisoft/yii2/blob/master/framework/validators/ExistValidator.php#L89

It should read `!$this->allowArray`

**Comment by samdark** [comment]
Hmm, yes. That's weird.

**Comment by Faryshta** [comment]
We can fix it by changing that line and the default definition for `allowArray`, currently its set to false, we need to change it to true and publish it to prevent bc break

**Comment by samdark** [comment]
Actually [the line you linked to](https://github.com/yiisoft/yii2/blob/master/framework/validators/ExistValidator.php#L89) is OK.

- `allowArray` means allow input of multiple values for the same parameter i.e. `http://example.com/?ids[]=1&ids[]=2`.
- Exception means that in order for it to work properly there should be only one `targetAttribute`.

**Comment by Faryshta** [comment]
> Exception means that in order for it to work properly there should be only one targetAttribute.

That line is doing exactly the opposite. Lets say I set `allowArray = true`, the previous line checks if `targetAttribute` is array, then if `allowArray` is true it throws an exception. It should to the opposite.

**Comment by creocoder** [comment]
@Faryshta Please read code carefully with fully understanding what happens. Everything OK with that code.

**Comment by Faryshta** [comment]
@creocoder I read it again including the doc for the `allowArray` attribute, still that attribute behaves differently than it should.

`[['category_id`], 'exist', 'allowArray' => false, 'targetAttribute' => ['category_id' => 'id']]`

Won't throw an exception.

`[['category_id`], 'exist', 'allowArray' => true, 'targetAttribute' => ['category_id' => 'id']]`

will throw it

**Comment by samdark** [comment]
Yep. `allowArray` requires you to specify `targetAttribute` as a single attribute name. That's intended as far as I understand.

**Comment by Faryshta** [comment]
@samdark then why `'allowArray' => true` throw an exception?

**Comment by samdark** [comment]
`'allowArray' => true` requires you to specify `targetAttribute` as a single attribute name.

**Comment by Faryshta** [comment]
shouldn't it be `disallowArray` then?

**Comment by samdark** [comment]
I guess that's because there's no way to pass array of column-value pairs via URL in case of accepting arrays.

**Comment by samdark** [comment]
@Faryshta nope. `allowArray` means allow taking array from input. It doesn't mean "allow targetAttribute to be an array".
