### ISSUE TITLE
CamelCased controller names apparently may refer to two different view folders

### ISSUE THREAD

**Issue by mjwvb** [yiisoft/yii2#9215]
After creating lots of controllers in a yii2 project of mine, I noticed something weird which seems to be a bug. 

Sometimes I'm using CamelCased names for my controllers, like AwesomeYiiController with view folder "(...)/views/awesomeYii/..." in a Theme enabled environment. However, one can reference to the controller using two routes, namely "//.../awesomeyii" and "//.../awesome-yii". Usually I'm using the former way to create urls, referring to the "awesomeYii" view folder. Somewhere else I was using the latter as well, which was throwing an error about not being able to find view file "(...)/awesome-yii/index.php". So when routed lowercased it looks for the lowercased view folder (awesomeYii), and when routed dashed it looks for dashed folder (awesome-yii).

I checked it in the yii code, and indeed, it uses the plain controller id to determine the view folder (https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L449). The id is automatically determined by the route (https://github.com/yiisoft/yii2/blob/master/framework/base/Module.php#L502) and not by the controller name, which causes this problem as the controller listens to different routes.

So apparently Yii may be looking for the view folder for CamelCased controllers in two ways (lowercased or dashed), which the user decides by just changing the route. This is unexpected to me and really should be fixed.

**Comment by cebe** [comment]
this only works if your file system file names are case in-sensitive. so you have not only AwesomeYiiController.php on your disk but yii can also find AwesomeyiiController.php if requested.
There is not much we can do about this.

**Comment by mjwvb** [comment]
I'm not talking about resolving the controller name, but about resolving the view directory of a requested controller. Controller resolving works fine actually. What I mean to say is twofold:

a) There is no consistent way of creating the view file directory for my controllers. For CamelCased controllers I can choose to create the view folder like "camelCased" or "camel-cased", depending on how I and the user request it. The user should not even be able to decide about this in any way...

b) Controllers (AwesomeYiiController) can have two different controller id's right now, awesomeYii and awesome-yii. Why is this not static? Why not always assign id awesomeYii to the controller, independent from how you request that controller? By fixing the id of a controller, you also fix the view folder name resolving.

To my opinion it would be better to drop dynamic controller id assignment at all, so view folder names correspond to the controller names and not to the route id. After resolving the controller name out of the route, just determine the controller id by the controller name instead of the route. 

Although easy to implement I guess it may be too radical, as developers may already be mixing dashed and camelCased right now. Though this really is a problem for me right now, and yet foresee unexpected problems for others as well. Correct me if I'm wrong of course.

**Comment by cebe** [comment]
this problem only exists because of windows file system which has case insensitive names. I just checked the code and found that it should have been in c01804d7c979ec1652229735ff015dda1db4909a which was released in 2.0.4, which version of yii2 are you using?

**Comment by mjwvb** [comment]
I'm using mac, and apparently Yii version 2.02, which is very strange as I know for sure that I updated Yii to 2.05 at release. Anyway, I updated to 2.05 and now I'm forced to use dashed routes for CamelCased controllers. That's correct then, I guess?

Stupid of me to not confirm the version... Thanks for your help!

**Comment by mjwvb** [comment]
Maybe it's good to put it in the upgrading instructions. I was using CamelCased instead of dashed named view folders and routes for CamelCased controllers. Now I had to rename all view folders and routes from e.g. awesomeYii to awesome-yii to make it work again after the upgrade.

**Comment by samdark** [comment]
@mjwvb have you ever deployed it to linux-server?

**Comment by mjwvb** [comment]
Nope not yet

**Comment by samdark** [comment]
Well, you have to use `dashed-names` anyway because `camelNames` won't work on Linux anyway.

**Comment by mjwvb** [comment]
I probably would have stumbled upon it on deployment indeed. I changed everything to dashed names now, luckily wasn't too much work. Nevertheless, it probably saves some struggling for other developers that were using camelCased dirs and routes as well and are about to upgrade and/or deploy to a linux server. Or I could have been the only one of course, hehe

**Comment by mjwvb** [comment]
*I mean putting it somewhere in the manual or upgrade instructions would save the struggling for the unlucky ones.

**Comment by samdark** [comment]
It's in the guide right from the start.

**Comment by mjwvb** [comment]
Ah I didn't notice the update of your post of 2 hours ago, about the consistency and the non-break. Never mind anyway :)
