### ISSUE TITLE
BUG:can not find input element when validate checkbox or radio  (which set tag)

### ISSUE THREAD

**Issue by yiifans** [yiisoft/yii2#9217]
when I set tag to checkboxList or radioList in activeFrom. and change the tag value from default value(div) to others (for example ul).

then,when validate, the input can not be found. so validate error.
I found the code in yii.activeForm.js

tagName.toLowerCase() === 'div'

    var findInput = function ($form, attribute) {
        var $input = $form.find(attribute.input);
        if ($input.length && $input[0].tagName.toLowerCase() === 'div') {
            // checkbox list or radio list
            return $input.find('input');
        } else {
            return $input;
        }
    };

**Comment by taxp** [comment]
Is this issue linked with https://github.com/yiisoft/yii2/issues/5881 ?

**Comment by yiifans** [comment]
yes ,  it is the same issuer. thanks.
by the way, where do i configure selectors['input']

**Comment by yiifans** [comment]
ok i found it .
