### ISSUE TITLE
建议loadDefaultValues改为加载模型规则里的默认值，而非数据库的

### ISSUE THREAD

**Issue by niefufeng** [yiisoft/yii2#9219]
> 在issue搜了一下，看不懂E文，也不知道有人建议过没！

我觉得`loadDefaultValues`还是加载验证规则里的默认值符合实际一点，因为在不同的`场景`下，验证规则里的默认值不一定是一样的，而数据库那个是写死的（比如字符串类型的，我设置的`default=''`，而数字类型的全都设置的是`default=0`，如果加载数据库的默认值，那这显然不科学。

**Comment by klimov-paul** [comment]
Closed unless readable decription provided.
