### ISSUE TITLE
CRUD model generator - Foreign key rule - code update

### ISSUE THREAD

**Issue by c006** [yiisoft/yii2#9221]
I am suggesting to change the way the foreign key rules are generated.

File: vendor/yiisoft/yii2-gii/generators/model/Generator.php
Line: 302

Bellow is the update code. It adds a key/value pair to targetAttribute.

>
        // Exist rules for foreign keys
        foreach ($table->foreignKeys as $refs) {
            $refClassName = $this->generateClassName($refs[0]);
            unset($refs[0]);
            foreach ($refs as $_attribute => $_ref) {
                $rules[] = "[['$_attribute'], 'exist', 'skipOnError' => true, 'targetClass' => $refClassName::className(), 'targetAttribute' => ['$_attribute'=>'$_ref']]";
            }
        }

Without the key/value pair I have run into instances where the validation returns a false negative.

**Comment by samdark** [comment]
Already done in master.

**Comment by c006** [comment]
Excellent, thanks for the update.
