### ISSUE TITLE
How to customize XML output

### ISSUE THREAD

**Issue by ivantree** [yiisoft/yii2#9222]
how to customize XML output root note "response" to "appinof"
For example：
![aa](https://cloud.githubusercontent.com/assets/9014680/8899659/cc19a720-3469-11e5-9039-56dae9bbe4a9.JPG) to 
![b](https://cloud.githubusercontent.com/assets/9014680/8899664/ed9e8b40-3469-11e5-8ff0-869b5ae7e51f.JPG)

**Comment by samdark** [comment]
Is it rest API response? Please provide more details.

**Comment by ivantree** [comment]
![aa](https://cloud.githubusercontent.com/assets/9014680/8900241/820681e2-3470-11e5-8831-4e424f70147d.JPG)
it's rest api

**Comment by nepstor** [comment]
You may try this code
```php
        Yii::$app->getResponse()->format = Response::FORMAT_XML;
        Yii::$app->getResponse()->formatters = [
            Response::FORMAT_XML => [
                'class' => \yii\web\XmlResponseFormatter::className(),
                'itemTag' => 'Timesheet',
            ]
        ];

**Comment by ivantree** [comment]
Thank a lot!
