### ISSUE TITLE
Suggestion: Option to prevent migrating down (in production environment)

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#9226]
The chance of migrating a database down unintentionally and losing data in a production environment should be very low (especially with automation). Yet, the consequences of such rare mistake would be extremely severe. That's why I'm suggesting adding an option (lock) that by default prevents migrating down in production environments. To do so, the developer must intentionally disable that lock. Besides acting as a safety net, it also adds a level of comfort during the continuous movement between development, testing, and production.

Some ideas for how this could work:
- An application-level setting such as `migrateDown` that takes true/false or constants `MIGRATE_ALL`, `MIGRATE_NONE`, or `MIGRATE_NO_PROD` or...
- Extending the above point by an application-level setting `migratable` that can be set via constants `MIGRATE_UP`, `MIGRATE_DOWN`, `MIGRATE_ALL`, `MIGRATE_NONE` for finer control over migrations. For example `MIGRATE_NONE` would prevent executing migrations at all on production if the developer wants to use them for development only and a different tool for applying database changes.
- A migration-level setting such an attribute of one of the above settings but in `yii\db\Migration`. After each successful production database upgrade, the developer seals (locks) the successful migrations by setting that value inside each one so from now on those migrations work down in development and testing environments only.
- Both of the above so individual migrations can override application lock but this could be confusing and not safe.

Making such setting work with `YII_ENV` would be even better.

**Comment by klimov-paul** [comment]
I don't think this is general enough to be implemented in the core.
It could be a lot of possible user mistakes, which may break the production server, like good old `rm -rf /`.
The requested feature can be acheived using an action filter or behavior, which interacts with `Controller::EVENT_BEFORE_ACTION`.

**Comment by samdark** [comment]
Agree. It's asking for confirmation already and I think that's enough.
