### ISSUE TITLE
Add column to SQL query results

### ISSUE THREAD

**Issue by abutouq** [yiisoft/yii2#9227]
Currently I'm trying to add column to ActiveQuery and the coulmn I added must be string to work like this:
`SELECT [id], [body], 'web' AS [type] FROM [web_article] WHERE body LIKE '%a%'`

Below the original code:
`$webArticle = WebArticle::find()->select('id, body, \'web\' AS type')->where('body LIKE :query')->addParams([':query'=>"%{$model->text}%"]);`

But when I execute this query it convert the `'web' AS [type]` to `['web'] AS [type]` the square brackets make the `'web'` string as column in the table this is not true.

How can I add this column using ActiveQuery?

**Comment by mdmunir** [comment]
```php
->select(['id','body','type'=>new \yii\db\Expresion("'web'")])
```

**Comment by abutouq** [comment]
@mdmunir Thanks alot its work :smile: but Expresion with duple `s`
