### ISSUE TITLE
Advanced Project Template guide url is broken

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#9229]
go to Yii 2.0 Guide (http://www.yiiframework.com/doc-2.0/guide-README.html), then go Special topics > Advanced Project Template

**Comment by samdark** [comment]
It's already fixed in master code: https://github.com/yiisoft/yii2/blob/master/docs/guide/README.md

**Comment by duynguyen0511** [comment]
the link on the sidebar is broken

![2015-07-28_0937](https://cloud.githubusercontent.com/assets/436950/8936494/e2367a50-350f-11e5-8da6-ab7d11ad1d75.png)

**Comment by samdark** [comment]
It is and it is already fixed in the code. Not re-rendered yet.

**Comment by duynguyen0511** [comment]
thanks.  just wonder how re-rendered works ?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-apidoc
