### ISSUE TITLE
 Load the form data && files to the model by one step.

### ISSUE THREAD

**Issue by atcq1** [yiisoft/yii2#9230]
By default, the form data and form files are loaded into the model in a few steps in the controller. 
```
        $model = new Model();
        if ($model->load(Yii::$app->request->getBodyParams()))
        {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->save())
                return $this->redirect(['controller/action']);
        }
```
Since all the data belong to model - it would be convenient to download them in a single step.
For Example
```
        $model = new Model();
        if ($model->loadForm(Yii::$app->request->formData) && $model->save())
                return $this->redirect(['controller/action']);
```
This will reduce the amount of redundant code and make controllers more small.

**Comment by petrabarus** [comment]
I also got this problem. I don't really like putting the `UploadedFile` routine in every controller. So what I can do is to tell the Model what attribute is an image and tell it to execute the `UploadedFile` before the validation. I came up with something like this.

```php
class Behavior extends \yii\base\Behavior {
      public $imageAttribute = 'imageFile';

      public $events = [];

      public function events() {
          return [\yii\base\Model::EVENT_BEFORE_VALIDATE => 'assignImage'];
      }

      public function assignImage() {
      	  $this->owner->{$this->imageAttribute} = UploadFile::getInstance($this->owner, $this->imageAttribute);
      }
}
```

**Comment by mdmunir** [comment]
https://github.com/mdmsoft/yii2-upload-file

**Comment by mikehaertl** [comment]
I've suggested a simplified pattern to handle uploads in #4352.

**Comment by SilverFire** [comment]
Could be done using behaviors. There is a bunch of available implementations:

https://github.com/mohorev/yii2-upload-behavior
https://github.com/yii-dream-team/yii2-upload-behavior
https://github.com/mdmsoft/yii2-upload-file
