### ISSUE TITLE
composer update issue

### ISSUE THREAD

**Issue by makroxyz** [yiisoft/yii2#9231]
This morning I have this issue... also on create project...

Importing tag v2.0.4 (2.0.4.0)
Adding VCS repository bower-asset/bootstrap
                                                                            [UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*" 

Any ideas?

**Comment by fourteenmeister** [comment]
> Could not parse version constraint <=2.: Invalid version string "2." 

A similar problem.

**Comment by freezy-sk** [comment]
try
```
composer selfupdate
composer clearcache
```
it sometimes helps in situations like this

**Comment by makroxyz** [comment]
I've already tried with no success
same error in bower-asset
Il 28/lug/2015 09:58, "freezy" <notifications@github.com> ha scritto:

**Comment by jojithomas** [comment]
Same error here 

[UnexpectedValueException]
Could not parse version constraint <=2.* Invalid version string "2.*"

**Comment by lynicidn** [comment]
+

**Comment by lynicidn** [comment]
https://github.com/twbs/bootstrap/commit/9b1a213cf758e1b60e20c59a721a63e13da098f7

**Comment by cvrebert** [comment]
Known bug: https://github.com/francoispluchino/composer-asset-plugin/issues/129

**Comment by tayyabhussain** [comment]
issue resolved by command below
bower install 'jquery#1.9.1 - 2'

**Comment by makroxyz** [comment]
Is it the best solution?
I need to install npm on my server (linux) for that command

**Comment by SonicGD** [comment]
@makroxyz wait for https://github.com/francoispluchino/composer-asset-plugin/pull/137

**Comment by petrabarus** [comment]
Same problem here, I tried clearing the cache `composer clear-cache` and tried removing the `vendor/` directory content, and then use `composer update --prefer-dist`. Not sure which one give the effects but they works.

**Comment by samdark** [comment]
It's already fixed by fxp-composer-asset-plugin but it wasn't tagged yet. You can try using its `dev-master`.
