### ISSUE TITLE
loginByCookie needs to remove slashes

### ISSUE THREAD

**Issue by nilsburg** [yiisoft/yii2#9235]
I've noticed that the cookies created when logging in have slashes.
Here is an
example of cookie created when logging in and using the "remember me" option: 
> [5,\"n6BijUtHAarb4t0IuDrJlp28TwglRcHq\",7776000]

Even thought when creating the JSON string it has the **JSON_UNESCAPED_SLASHES** and **JSON_UNESCAPED_UNICODE** parameters, after saving the cookis the slashes are added.
So when calling the **loginByCookie** function it never gets to autoLogin because the JSON string is invalid.
I've extended the web\User class and changed the loginByCookie method adding just before 

> "$data = json_decode($value, true);" (line 287)

The following line:

> $value = stripslashes($value);

After this modification the autoLogin works.

**Comment by samdark** [comment]
Auto-login definitely works. I'm using it in production and tested it many times. Can you reproduce it with [clean basic project template](https://github.com/yiisoft/yii2-app-basic)?

**Comment by nilsburg** [comment]
Hi,
You're right, I tested the basic project template and auto-login works.
I've tested on my project and it seems that for some reason when writing the cookies it adds slashes:

I create the cookie like this:
> $cookie = new Cookie(['name' => '_test', 'httpOnly' => true]);
        $cookie->value = json_encode([
            1,
            'test string',
            3600
        ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        $cookie->expire = time() + 3600;
        Yii::$app->getResponse()->getCookies()->add($cookie);
        var_dump($cookie->value);

Output:
> string '[1,"test string",3600]' (length=22)


Then I dump the cookie content with the following:
> var_dump($value = Yii::$app->getRequest()->getCookies()->getValue('_test'));

Output:
> string '[1,\"test string\",3600]' (length=24)

I am trying to find out where in the code it writes the cookie to see why this is happening, but I am unable de find it.

**Comment by nilsburg** [comment]
Update: I am very sorry, It has nothing to do with Yii, it is just Wordpress who is doing this (with have some wordpress integrations in the project).
