### ISSUE TITLE
OEM Bundled Source Code

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii2#9237]
Not really related to Yii2 code - but a question related to OEM bundled licensed products with Yii. Wished to understand how to get access to the source code for [Redactor Plugin that is OEM licensed with Yii](http://www.yiiframework.com/news/64/redactor-is-oem-licensed-for-yii/).

Wish - if we could have it as a packagist or bower accessible resource.

**Comment by bizley-code** [comment]
I think this question should be asked here https://github.com/yiiext/imperavi-redactor-widget
Anyway source code is available in the assets folder there.

**Comment by kartik-v** [comment]
Thanks for the link (understand that's a Yii 1.x extension). 

Is there a better way to access in Yii2. Considering how other packages or plugins are sourced in Yii2 - maybe via a bower or packagist source.

**Comment by samdark** [comment]
It's not open-licensed. Yii community got OEM license for it and I'm updating it manually in that repo from time to time. It's not a thing officially done by Yii team, it's community thing.

**Comment by bizley-code** [comment]
Just curious:
If @samdark decides to leave Yii who will take care of it?
Any other implement for Yii 2 than https://github.com/vova07/yii2-imperavi-widget ?

**Comment by samdark** [comment]
I'll pass it to someone if I'll ever decide to leave. As far as I know, vova07 implementation is the only one for Yii 2.0.
