### ISSUE TITLE
Не могу использовать модуль

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#9238]
с чем может быть связана такая проблема 

есть ли какая нибудь хитрость при подключении своего модуля (ничего сложного, просто модели и круды, отвечающие за примерно одинаковый функционал)

использую https://github.com/vova07/yii2-start

![screenshot_13](https://cloud.githubusercontent.com/assets/10970793/8929101/76566944-353c-11e5-9d4b-79c52e9140bf.png)

пытаюсь в yii 2 сделать свой модуль. ложу его в frontend\modules.  туда же генерю модель и круд. но сайт говорит что нет такой страницы. в чем может быть подвох

common\config

    'modules' => [
        'main' => [
             'class' => 'app\modules\main\Module',
        ],

http://yii2-start/main/pages
Not Found (#404)

**Comment by lynicidn** [comment]
подключить в конфиге надо модуль

**Comment by lynicidn** [comment]
и пути ко вьюхам проверьте согласна мануала https://github.com/yiisoft/yii2/blob/master/docs/guide/structure-views.md

**Comment by des1roer** [comment]
https://drive.google.com/open?id=0B8SBzylZ-emOOG5xVV9hbkpWZTA

**Comment by lynicidn** [comment]
http://yiiframework.ru/forum/

**Comment by des1roer** [comment]
http://yiiframework.ru/forum/viewtopic.php?f=19&t=31102&p=158327#p158327

**Comment by samdark** [comment]
Github is for issues. For questions please use forums, chats etc.
