### ISSUE TITLE
Refactoring `AssetManager` hash function.

### ISSUE THREAD

**Issue by petrabarus** [yiisoft/yii2#9245]
In my cases, I deployed a lot of identical Yii2 app on instances behind a load balancer. And I usually set the load balancer to not use session stickiness, meaning the following requests can be served by different instances.

The problem is in the hashed directory generated by `AssetManager` that uses `filemtime`. Since the deployment in instances can be in different seconds, the hashed directory for an asset can be different for each instances.

So I extended my own `AssetManager`, which means I have to modify all `getPublishedUrl`, `publishFile`, `publishDirectory`, `getPublishedPath`, which pretty much have a lot of similar codes like `$this->hash(dirname($path) . filemtime($path))`.

- https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L443
- https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L488
- https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L536
```
 if (is_file($path)) {
    return $base . $this->hash(dirname($path) . filemtime($path)) . DIRECTORY_SEPARATOR . basename($path);
} else {
    return $base . $this->hash($path . filemtime($path));
}
```
- https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L561
```
 if (is_file($path)) {
    return $this->baseUrl . '/' . $this->hash(dirname($path) . filemtime($path)) . '/' . basename($path);
} else {
    return $this->baseUrl . '/' . $this->hash($path . filemtime($path));
}
```

I'm just thinking that maybe the `hash` method and the methods using it can be refactored and the `filemtime` can be put into the refactored method where the developers can opt to use their own hash generation strategy. The strategy can maybe change the length of the hash string or maybe a certain salt that is generated every time the app is built.

**Comment by dieend** [comment]
+1.

Or refactor `filemtime($path)` into `hashSuffix()` function.

**Comment by samdark** [comment]
Yes, that would be a good enhancement. @petrabarus do you want to work on a pull request?

**Comment by petrabarus** [comment]
Will do. But one question. Why do we need different seed for `hash` for file and directory?

`$this->hash(dirname($path) . filemtime($path)` and `$this->hash($path . filemtime($path));`

**Comment by samdark** [comment]
It's for CSS-resources loaded via `url()` such as images. These should always be published into the same dir.
