### ISSUE TITLE
Impossible to install Yii2 via composer

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#9250]
This morning I noticed that trying to install Yii2 via composer gets me this:

    $ composer create-project --prefer-dist yiisoft/yii2-app-basic basic
    Installing yiisoft/yii2-app-basic (2.0.4)
      - Installing yiisoft/yii2-app-basic (2.0.4)
        Downloading: 100%         

    Created project in basic
    Loading composer repositories with package information
    Installing dependencies (including require-dev)
                                                                          
      [UnexpectedValueException]                                              
      Could not parse version constraint <=2.x: Invalid version string "2.x"  
                                                                          

This was working fine a few days ago (last time I tried), so I'm guessing something in either Yii or one of the repos that Yii uses changed and the FXP plugin isn't able to parse the changes.

**Comment by lynicidn** [comment]
# composer global update

**Comment by lynicidn** [comment]
for detail https://github.com/francoispluchino/composer-asset-plugin/pull/137

**Comment by klimov-paul** [comment]
Duplicates #9231

**Comment by alexandernst** [comment]
@lynicidn @klimov-paul I read the entire discussion, but it's not very clear how exactly to fix this. I tried cleaning the cache, self-update, deleting global and project lock files and I still get the error.

Can you tell me what exactly I must do to fix this?

**Comment by lynicidn** [comment]
remove vendor also

**Comment by alexandernst** [comment]
I had to place `"fxp/composer-asset-plugin": "dev-master"` in my global `composer.json`.

**Comment by alexandernst** [comment]
Btw, I iterate what I said in https://github.com/yiisoft/yii2/issues/8688
FXP is *completely* and utterly rubbish. Stupidest piece of software I have seen in quite some time. Yii2 would be *so* much better ditching it.

**Comment by samdark** [comment]
@alexandernst there's such plan for 2.1.
