### ISSUE TITLE
How to update attributes of related objects without selecting them first?

### ISSUE THREAD

**Issue by petrabarus** [yiisoft/yii2#9262]
Sorry for the dumb question. Right now to update all related objects, I have to do something like this

```
$objects = $foo->getRelation('name')->all();
foreach($objects as $object) {
    $object->updateAttributes(['attribute' => 'value']);
}
```

In the `\yii\db\ActiveRecord` we have `updateAll` which can be use to update all records in the table without selecting them first (with the trade-off of inability to trigger events).

I'm wondering if there is an easy way to do the same for the relation. Maybe something like
`$foo->updateAllRelations('name', ['attribute' => 'value']);` ?

**Comment by samdark** [comment]
- https://github.com/yiisoft/yii2/issues/8565
- https://github.com/yiisoft/yii2/issues/6326
- https://github.com/yiisoft/yii2/issues/7585
- https://github.com/yiisoft/yii2/issues/6664

**Comment by petrabarus** [comment]
Okay, so no built-in way. Just want to make sure. Thanks!
