### ISSUE TITLE
What is the rational behind current beginTransaction() logic

### ISSUE THREAD

**Issue by tsvetann** [yiisoft/yii2#9265]
Just noticed that Yii forcefully & silently prevents transactions if currently another transaction is active in the same session. The framework doesn't allow to change this! What is the rational behind this decision given that as per mysql starting transaction automatically commits an active one in the same session?

Thanks!

**Comment by cebe** [comment]
> Just noticed that Yii forcefully & silently prevents transactions if currently another transaction is active in the same session.

yii does not do that, please elaborate about the problem you are having.

**Comment by tsvetann** [comment]
Please look at vendor/yiisoft/yii2/db/Transaction.php::begin()

Transaction is allowed to start only if `if ($this->_level == 0)` is true! I have a long running process (1 session). Yii does not allow me to begin a new transaction if the current session has one active! The question is why?

**Comment by cebe** [comment]
database transactions are nested if supported by the dbms. if not, this is simulated by yii. You can only have one transaction per database connection or you need to have nested transactions.

**Comment by tsvetann** [comment]
Right! In mysql if you start transaction within another running one, mysql commits the already running one and allows you to start the new one. Yii prevents this default behaviour of mysql. What is the reason for that?

**Comment by cebe** [comment]
you really want an implicit commit? that is not what I would expect as it may commit a possibly incomplete transaction. if you start a transaction inside of an existing one, the transactions are nested so that if you roll back the inner transaction you get a rollback to the point where it started, which is the expected result.

**Comment by tsvetann** [comment]
What you are describing is innodb savepoints (for mysql_! What I am describing is starting a transaction within another active transaction and later one being implicitly committed - default Mysql behaviour which Yii changes - why? Yii does not even allow me to configure it. Why would I not expect a DB default behaviour?

**Comment by samdark** [comment]
That's by design and to allow nesting in domain layer. It's quite hard to achieve w/o it.
