### ISSUE TITLE
Impossible to use ActiveQuery through findBySql in subquery.

### ISSUE THREAD

**Issue by RoelofRuis** [yiisoft/yii2#9266]
It seems impossible to use an `ActiveQuery` instantiated through calling `ActiveRecord::findBySql()` as a subquery.

I've reduced the problem to its basic form in this function:
```php
public function testFindBySql() {
    $user_subquery = ActiveRecord::findBySql('SELECT * FROM {{%user}} WHERE [[last_name]] ILIKE :lastname');
    $user_subquery->addParams([':lastname' => 'smith']);

    $query = new Query();
    $query->from(['users' => $user_subquery]);

    printf("Subquery SQL:\t%s\nMain query SQL:\t%s",
            $user_subquery->createCommand()->getRawSql(),
            $query->createCommand()->getRawSql());
}
```
This outputs
```
Subquery SQL:	SELECT * FROM "tbl_user" WHERE "last_name" ILIKE 'smith'
Main query SQL:	SELECT * FROM (SELECT * FROM "tbl_active_record") "users"
```
Although I would expect the inner select statement in the main query SQL to contain the complete Subquery SQL.

It seems like the subquery is always constructed from the standard query attributes, but it seems desirable to be able to use it in the way described above.

**Comment by cebe** [comment]
there is no need to wrap the SQL in `findBySql()`. ` findBySql()` is only useful if you want to compose plain SQL to retrieve records. for a subquery you can just use a simple string.

I have adjusted the docs for it and added a test.
