### ISSUE TITLE
GridView pagination: no API to customize base url path

### ISSUE THREAD

**Issue by saada** [yiisoft/yii2#9267]
I can't seem to find an API to edit the url path easily without writing my own pagination UI.

I want to write a custom base url for a GridView's pagination widget.
Thanks!

**Comment by samdark** [comment]
What do you mean by custom base URL? Any examples?

**Comment by saada** [comment]
I have this gridview
```php
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel'  => $searchModel,
    'columns'      => [...]
```
Our main url manager has a configuration that looks like
```php
 '<controller>/<id:\d+>/<action>/<action_id:\d+>' => '<controller>/<action>',
```
Our url looks like `domain.dev/controller-name/2/action-name/5`.
The pagination render links with href =  `/controller-name/action-name/2?action_id=5&page=1&per-page=10`.
Notice that action_id is moved out of the base url and added as a $_GET parameter while the id got shifted to the end of the base url.

Keep in mind that the URL ids have nothing to do with the page numbers of the grid. This is a grid within a specific view although it does use the URL params for the search model.

Is there a way to customize the pagination URL such that it becomes relative instead of absolute? and also not lose the id as shown above?

**Comment by samdark** [comment]
Still don't get it. Can you show URLs you want to achieve?

**Comment by saada** [comment]
Sure! Let's try one more time :smile: 
# Expected Result


### Base URL
```
domain.dev/controller-name/2/action-name/5
```
### Paginated links

```
domain.dev/controller-name/2/action-name/5?page=2
domain.dev/controller-name/2/action-name/5?page=3
domain.dev/controller-name/2/action-name/5?page=4
```
# Actual Result
### Base URL
```
domain.dev/controller-name/2/action-name/5
```
### Paginated links

```
domain.dev/controller-name/action-name/2?action_id=5&page=2
domain.dev/controller-name/2/action-name/2?action_id=5&page=3
domain.dev/controller-name/2/action-name/2?action_id=5&page=4
```

**Comment by klimov-paul** [comment]
I can see no issue here.
`Pagination::createUrl()` uses `UrlManager::createUrl()` thus it inherits all URL rewrites from it.

You may also setup different URL manager for the pagination via `Pagination::urlManager` property, changing `UrlManager::baseUrl` for it if you like.

**Comment by saada** [comment]
@klimov-paul, can you please show me an example with GridView? How can I set the URLs generated from the paginated links using your approach?

**Comment by cebe** [comment]
> Our url looks like domain.dev/controller-name/2/action-name/5.
> The pagination render links with href = /controller-name/action-name/2?action_id=5&page=1&per-page=10.

this can only happen if there is another rule that does that. make sure the ordering of your url rules is correct. First rule that matches will be used.
