### ISSUE TITLE
db/Command getRawSql boolean values doesn't work

### ISSUE THREAD

**Issue by arkhamvm** [yiisoft/yii2#9268]
Hi. There is no boolean check in getRawSql function (db/Command line 155), so 'false' values converts to empty string, which cause an syntax error (at least in pgsql), e.g.:
```
UPDATE "city" SET "deletion_mark"=,
```

Fix should look like (line 163):
```
 if (is_string($value)) {
        $params[$name] = $this->db->quoteValue($value);
} elseif (is_bool($value)) {                            // <= fix
        $params[$name] = ($value ? 'TRUE' : 'FALSE');   // <= fix
} elseif ($value === null) {
        $params[$name] = 'NULL';
} elseif (!is_object($value) && !is_resource($value)) {
        $params[$name] = $value;
}
```

**Comment by samdark** [comment]
Fixed. Thanks for reporting.

btw., here's the quote from that method docs:

> Note that the return value of this method should mainly be used for logging purpose.
> It is likely that this method returns an invalid SQL due to improper replacement of parameter placeholders.

So don't rely on SQL produced. Use `$command->sql` and bound parameters instead.
