### ISSUE TITLE
Log in MongoDB

### ISSUE THREAD

**Issue by thiagotalma** [yiisoft/yii2#9270]
Today I went to test write the log using MongoDB and found that it's not possible.

>Invalid Configuration – yii\base\InvalidConfigException

>"mongodb" refers to a yii\mongodb\Connection component. yii\db\Connection is expected.

I honestly do not even know MongoDB enough to understand why.
It is a limitation of MongoDB or Yii2?

Or, ask them: save the log in MongoDB is not a good idea, thinking about performance?

**Comment by SDKiller** [comment]
Have you configured `yii\mongodb\log\MongoDbTarget` as target?

Because `\yii\log\DbTarget` is `sql`-specific

**Comment by klimov-paul** [comment]
You should use MongoDbTarget:
https://github.com/yiisoft/yii2-mongodb/blob/master/log/MongoDbTarget.php
