### ISSUE TITLE
Validation is passed, but $model->errors returns an array of error messages

### ISSUE THREAD

**Issue by dave-yang** [yiisoft/yii2#9273]
I encountered a tricky bug when did file uploading. The problem is that, when form validation is passed, `$model->save()` returns false, and  `$model->getErrors()` returns an array with one error message regarding file input only.

And the scenario, where its used is the following:

There are 3 columns in a table `(id, name, cover)`, and this is a very basic photo-album. The validation rules for this are pretty simple: when a user uploads a new photo, he must fill both name (`input type="text"`) and cover (`input type="file"`) fields. But when editing some existing record, he's allowed not to upload a file, since that's optional.

Pretty simple, right?

Now consider the relevant parts:

    class Album extends ActiveRecord
    {
        public $file;
        
    	public function rules()
    	{
    		return [
    			[['name'], 'required'],
    			[['file'], 'file', 'extensions' => 'gif, jpg, jpeg, png', 'skipOnEmpty' => !$this->isNewRecord],
    		];
    	}
    }

After filling both name and file fields in the browser manually, Yii's client-side validator highlights all fields green, which means that validation is passed successfully.

Here come the dragons now (after submitting successfully validated form):

    public function actionCreate()
    {
       $album = new Album();
       $album->load(Yii::$app->request->post());
       
       // The data is sent, $_POST and $_FILES aren't empty
       
       var_dump($album->save()); // false, but must be true
       print_r($album->errors); // Please upload a file (jeez, but a file is uploaded), but must be an empty array
    }

This bug occurs only in "Add form", while it works in "Edit form". When I remove the file input everything works as expected, so that must be its own issue. 

The environment itself, if that matters in this case:

- PHP 5.6
- Apache 2.2
- Yii 2.0 (downloaded that version 2 months ago)
- Tested on Windows/Linux, and all browsers

**Comment by dbavscc** [comment]
You should assign UploadedFile instance to file field of model before validation/save
`$model->file = UploadedFile::getInstance($model, 'file');`

**Comment by dave-yang** [comment]
Guys, assigning `$model->file = UploadedFile::getInstance($model, 'file');` before doing `save()` works. But it works in case it comes after, `$model->load(Yii::$app->request->post());`, not before.

Since the `file` attribute is marked as a file in validation rules and since the property expects an instance of `UploadedFile::getInstance()`, wouldn't it make sense to throw an exception on mismatch to avoid confusions instead of ignoring this and letting users see the error?

**Comment by Faryshta** [comment]
>  wouldn't it make sense to throw an exception on mismatch to avoid confusions instead of ignoring this and letting users see the error?

Thats what validations are supposed to do. You are validating user input so if there is a fault in the validation the user is supposed to see it so it can be fixed by the user.

and about your error. When you create the new instance for the update you are editing the value of the attribute so when you execute `save()` it tries to save the `cover` column with a `null` value to fix this its simple.

```
if (empty($model->file)) {
    $model->save(true, ['name']);
} else {
    $model->save();
}

**Comment by dave-yang** [comment]
@Faryshta I got your point

When I was referring to users, I meant frameworks users (i.e developers that use a framework), not web-application users. The point I'm trying to make, is that it's not really that good, when programming errors aren't handled by exceptions.

As I said above, if the validation is passed and if there's no `$model->file = UploadedFile::getInstance($model, 'file');` assignment before `save()`, then an error should be thrown, because it doesn't match expectations, instead of displaying wrong and confusing error message.

**Comment by Faryshta** [comment]
if no file is sent then `UploadedFile::getInstance($model, 'file')` returns null, which means even if you are calling it, it won't fill the expectation you named and it will throw an exception instead of showing an error to the end user

**Comment by klimov-paul** [comment]
I can see no issue here.
