### ISSUE TITLE
model::find()->all() return incorrect rows

### ISSUE THREAD

**Issue by yrssoft** [yiisoft/yii2#9274]
model::find()->all() return incorrect rows
problem(using Pagination):
model::find()->all() return 5rows
But $countQuery->count() is 10 rows,otherwise there are 10 rows in database
And then i find the SQL statement by debug info,and run the sql statement,it return 10 rows 
v2.0.5

**Comment by cebe** [comment]
I guess you are using a join that produces multiple rows for one record. You have to use a distinct select or group by the pk of the model.

**Comment by Faryshta** [comment]
@yrssoft add a group by to your $countQuery

**Comment by yrssoft** [comment]
I was too half-hearted, thank you
