### ISSUE TITLE
File doesn't uploading, if it is empty

### ISSUE THREAD

**Issue by BooleanType** [yiisoft/yii2#9281]
I have rules:

`return [
            [['docFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'docx, doc, txt'],
 ];`

It's OK, if file is not empty. But if it is, Yii2 throws validation error. E.g., if extension of empty file is 'docx', it displays `'Only files with these extensions are allowed: docx, doc, txt.'` I found, that `FileValidator::validateExtension()` return `false`, cause this conditions fulfills:

`if (!in_array($extension, $extensionsByMimeType, true)) {
         return false;
 }`

`$mimeType` in this case is `inode/x-empty`.

What can I do with this?

**Comment by samdark** [comment]
What do you mean by "empty"?

**Comment by BooleanType** [comment]
0 bytes size.

**Comment by samdark** [comment]
1. Do you really want to allow uploading such files?
2. mime type of empty file could not be determined since there's no content.

**Comment by BooleanType** [comment]
In current project it is not necessary, but what if I am a teacher and need to send just file sctructure (tabs, indents, etc.), in a students portal without any text? In source code I found, that checking MIME-type and ext is in the same function. If they were separated, the problem would disappear. But, maybe, u are right and it is not so great problem, which need resolving... :)

**Comment by BooleanType** [comment]
But I think, it is not correct to show extension error, if file is empty. I had to look at Yii core to understand, what problem occurs.

**Comment by samdark** [comment]
Tabs, indents, etc. means the file has some content and it will be recognized.

**Comment by samdark** [comment]
You could turn off mime validation if you truly want empty files to be uploaded or add `inode/x-empty` to the list.

Overall, I don't think it worth handling specially.

**Comment by BooleanType** [comment]
By tabs, etc. I meant not chars, but this:
![Word](http://cs625620.vk.me/v625620403/3bb48/J4OOL90hwLs.jpg)

Thanks, understood.
