### ISSUE TITLE
PHP 5.5 adds new JSON error codes

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#9282]
- JSON_ERROR_RECURSION 	One or more recursive references in the value to be encoded
- JSON_ERROR_INF_OR_NAN 	One or more NAN or INF values in the value to be encoded
- JSON_ERROR_UNSUPPORTED_TYPE 	A value of a type that cannot be encoded was given

http://php.net/manual/en/function.json-last-error.php

should be handled in https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseJson.php#L89

**Comment by freezy-sk** [comment]
I don't like hardcoded constant values in #9289 so I was trying to make `handleJsonError` more compatible with differences between **PHP 5.4** and **5.5** and I've found this:
**PHP 5.4** is throwing `E_WARNING json_encode(): type is unsupported, encoded as null` when you are trying to encode Resource like this
```php
$fp = fopen('php://stdin', 'r');
Json::encode(['a' => $fp]);
```
and result is `{"a":null}` with `json_last_error() JSON_ERROR_NONE`

**PHP 5.5** is result `false` with `json_last_error() JSON_ERROR_UNSUPPORTED_TYPE`

This can be solved with custom error handler in `encode()`, but I think it's breaking compatibility
```php
set_error_handler(function () {
    static::handleJsonError(JSON_ERROR_SYNTAX);
}, E_WARNING);
$json = json_encode($value, $options);
restore_error_handler();
```

**Comment by freezy-sk** [comment]
This is how I handled it https://github.com/freezy-sk/yii2/commit/f0e9078cc61feaa25cc396625f928dbf90bdbb79

**Comment by SilverFire** [comment]
@freezy-sk solution looks good as for me
