### ISSUE TITLE
Widget auto generate ID and FragmentCache

### ISSUE THREAD

**Issue by demisang** [yiisoft/yii2#9284]
When **FragmentCache** using for caching some code with **Widget**s may cause a problem:
Before caching: "w0", "w1"
After caching: "w0", "w0"

Code for example:
```php
<?php if ($this->beginCache('input1cache', ['enabled' => true])): ?>
<div>
    Number input:
    <?= yii\widgets\MaskedInput::widget(['name' => 'test1', 'mask' => '9999999999']) ?>
</div>
<?php $this->endCache() ?>
<?php endif ?>

<div>
    Text input
    <?= yii\widgets\MaskedInput::widget(['name' => 'test2', 'mask' => 'aaaaaaaaaa']) ?>
</div>
```
1. After obtaining from cache are not registered JS code for the masked input widget.
2. Not to keep ```yii\base\Widget::$counter```

### Solution for keep unique widgets ids
Change autoIdPrefix to cache id key and restore it after:
```php
yii\base\View::beginCache() {
    $properties['id'] = $id;
    $properties['view'] = $this;
    /* @var $cache FragmentCache */
    
	// Set new widgets auto-prefix same as cache key
    Widget::$autoIdPrefix = $id; // <--- THIS IS NEW LINE
	
    $cache = FragmentCache::begin($properties);
    if ($cache->getCachedContent() !== false) {
        $this->endCache();
    
        return false;
    } else {
        return true;
    }
}
```
```php
yii\base\View::endCache() {
    FragmentCache::end();
	
	// Restore widgets auto-prefix to default. @todo Need to refine it for keep custom prefix.
    Widget::$autoIdPrefix = 'w'; // <--- THIS IS NEW LINE
}
```

### Solution for keep View assets:
Any idea? :)

Maybe add any asset registration within cache block to the cache dynamic content placeholders?

**Comment by petrabarus** [comment]
Caching widget has been a problem to me too. I was proposing #7435

By having an event before render and after render in the widget, we can have a fragment cache for a widget.

```php
<?= 
yii\widgets\MaskedInput::widget([
   'name' => 'test1', 
   'mask' => '9999999999',
   'as cached' => [       
       'class' => WidgetCache::class,
   ]
]) ?>
```

Then in the widget cache,

```
public function cache() {
    $this->owner->options['id'] = some_random_variable();
}
```

**Comment by klimov-paul** [comment]
You should explicitely specify the widget id for the widgets, which will be cached.
This will avoid all the problems.
Keeping autogenerated ids may lead to different problems like this one or ajax rendering.
