### ISSUE TITLE
Official bridge

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/yii2#9286]
since yii soft developed yii2 framework, and it have ability to work with yii1 framework together, I have a request from yii team to develope an official bridge like: https://github.com/slavcodev/yii2-yii-bridge
but with yii team support to working in all version of yii2 and application(basic or advanced). this repo (https://github.com/slavcodev/yii2-yii-bridge) is not good because have some error and no body resolve them.

it is necessery al last for my  company and company like us have some project that's started when yii2 dose not exist and developing of that project have been continue,

**Comment by cebe** [comment]
how is that different from http://www.yiiframework.com/doc-2.0/guide-tutorial-yii-integration.html#using-yii-2-with-yii-1 ?

**Comment by hooman-pro** [comment]
I wanan to have controller working in yii1 and yii2 if controller in yii1 not found use from yii2 controller, and push the yii1 app in a folder like a libery. and from today use yii2 for my project

**Comment by cebe** [comment]
That is a really complext task to solve and I do not think it is possible to do that in an easy way. We are not going to provide such a tight integration. Yii1 and Yii2 are two different frameworks, we can not easily integrate them.
