### ISSUE TITLE
PHP Parse Error – yii\base\ErrorException  syntax error, unexpected ';' (T_STRING)

### ISSUE THREAD

**Issue by AndruAlex** [yiisoft/yii2#9292]
I dont understand.
Can someone tell me how i can slove this problem?
![image](https://cloud.githubusercontent.com/assets/11726264/9035313/642c4124-39df-11e5-90fb-a1d8ab97b282.png)

**Comment by samdark** [comment]
That's error in your application. Update to `master` code and error page will give you more details.

**Comment by AndruAlex** [comment]
but how update to master?

**Comment by samdark** [comment]
In your `composer.json` you can change Yii version to `dev-master@dev` and do `composer update`. Note that `2.0.6` will be released soon and when it happens it's better to switch back to `~2.0.0`.

**Comment by freezy-sk** [comment]
@AndruAlex there is a missing semicolon on line 42 `$params['name'] = $this->username`
