### ISSUE TITLE
Documentation of Validator::$whenClient callback arguments is wrong

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#9298]
[Documentation for $whenClient ](http://www.yiiframework.com/doc-2.0/yii-validators-validator.html#$whenClient-detail) currently says

> The signature of the function should be `function (attribute, value)`, where
 `attribute` is the name of the attribute being validated and `value` the current value of the attribute.

which implies that `attribute` is a string. But attribute is in fact an object that's rather more useful in client validation than the attribute's yii\base\Model name.

![attribute screenshot](https://cloud.githubusercontent.com/assets/1178722/9045125/2193ef28-39ef-11e5-9528-ac12b67e47e6.png)

Sorry, I am not able to propose correct documentation for `attribute`. It would be an improvement (less incorrect) to say "a JavaScript object with properties relating to the form input" but beyond that I don't have any suggestions.

**Comment by nkovacs** [comment]
I think this is the same object as in #8822
