### ISSUE TITLE
Dynamic Form validation - case of radio/checkbox lists

### ISSUE THREAD

**Issue by fabioaccetta** [yiisoft/yii2#9300]
I hope I have done the right choice opening a new issue instead of commenting [this one](https://github.com/yiisoft/yii2/issues/1422).

I have a relation between `$product` model with many `$color` ones; the color form (the row to be inserted inside the product form) is like this:

``` php
[...]
$colors = [
   'red' => 'Red',
   'green' => 'Green',
   'blue' => 'Blue',
];
// $i represents an incremental variable,
// valued with the next available index of the colors array (already created)
echo $form->field($color, "[{$i}]name")
    ->inline(true)
    ->radioList($colors)
;
// inside the view, we will suppose that $product has already 1 $color for semplicity,
// so $i will be 1
[...]
```

The corresponding html is:

``` html
[...]
<div class="form-group field-color-1-name required">
   <label for="color-1-name" class="control-label">Name</label>
   <div>
      <input type="hidden" value="" name="Color[1][name]">
      <div id="color-1-name">
         <label class="radio-inline">
            <input type="radio" value="red" name="Color[1][name]"> Red
         </label>
         <label class="radio-inline">
            <input type="radio" value="green" name="Color[1][name]"> Green
         </label>
         <label class="radio-inline">
            <input type="radio" value="blue" name="Color[1][name]"> Blue
         </label>
      </div>
      <p class="help-block help-block-error"></p>
   </div>
</div>
[...]
```

According to the [yii2-cookbook](https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md#adding-and-removing-fields-dynamically), I need to execute this after the ajax call:

``` javascript
var attribute = {
    'id': 'color-1-name',
    'name': '[1]name',
    'container': '.field-color-1-name',
    'input': '#color-1-name',
    'error': '.field-color-1-name .help-block'
};
$('#product-form').yiiActiveForm('add', attribute);
```

On validation (on submit for example), my required radio buttons are empty and considered valid (green), while other required fields are considered invalid with error message (red). What I miss?

**Comment by IgorCode** [comment]
I'm facing the same issue, radioList control is validated for initial control but not for added/cloned ones. Inspecting `$("#form").data('yiiActiveForm').attributes` reveals that new radio list controls are not added for validation.

**Comment by IgorCode** [comment]
I just realized that this issue has been reported in yii2 project, I don't know about @fabioaccetta but my issue is with https://github.com/wbraganca/yii2-dynamicform, they are doing it wrong when finding new controls to be added for validation.

**Comment by samdark** [comment]
Closed since it's not clear if there are extra plugins involved.
