### ISSUE TITLE
Issue with the CRUD generated rule re ExistValidator

### ISSUE THREAD

**Issue by kryshtalev** [yiisoft/yii2#9303]
Yii 2.0.5 brought something new to CRUD model generator. I see there are few new rules

```php
    public function rules()
    {
        return [
            [['venue_id', 'consumer_id', 'checked_in_at'], 'required'],
            [['venue_id', 'consumer_id'], 'integer'],
            [['checked_in_at', 'checked_out_at'], 'safe'],
            [['consumer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Consumer::className(), 'targetAttribute' => ['id']],
            [['venue_id'], 'exist', 'skipOnError' => true, 'targetClass' => Venue::className(), 'targetAttribute' => ['id']],
        ];
    }
```

ExistValidator has a critical issue that does not pass the validation. It takes id of the model itself except getting the id of the related model. Therefore it executes a wrong SQL that checks the related model with the id. For instance in the sample above (it is a CheckIn model) id of the model is 116. Validating consumer will generate a command like 

```sql
select * from consumer where id = 116
``` 

But it is not true! check-in.id is equal to 116 but not consumer's id. 
That brings a lot of problems

**Comment by samdark** [comment]
2.0.5 brought nothing new. It was security release.

**Comment by samdark** [comment]
Can you reproduce your issue with code from master?

**Comment by cebe** [comment]
isn't this the issue which is fixed by https://github.com/yiisoft/yii2-gii/commit/db79e960620c515ed502a09c04f0c7b714944c92 ?

**Comment by samdark** [comment]
Yes. Should be.
