### ISSUE TITLE
Pagination totalCount empty

### ISSUE THREAD

**Issue by iJackUA** [yiisoft/yii2#931]
I have noticed this when I explicitly specify pagination pageSize config for DataProvider

```php
   $dataProvider = new \yii\data\ActiveDataProvider(
                [
                'query' => Posy::find(),
                       'pagination' => [
                              'pageSize' => 3,
                       ],
                ]);
```
pagination output for ListWidget is empty then
As I see via debugger  pagination totalCount property is being empty in this case

but with this call - pagination output is shown  (and totalCount has correct value)
```php
   $dataProvider = new \yii\data\ActiveDataProvider(
                [
                'query' => Posy::find()
                ]);
```

issue is related to this PR https://github.com/yiisoft/yii2/pull/909
reverting changes from those PR fixes pagination appearance for my issue, but I am not sure as for really correct solution.

**Comment by sergeymaskin** [comment]
Hi.
I generated sphinx model and crud with gii and note one problem. When responce more than 1000 elements and I move to last pages I got error. Sphinx has total and total_found values and it looks like dataProvider use total for pagination. I've solved it like this:
```
$dataProvider = new ActiveDataProvider([
    'query' => AnySphinxAr::find();
    'totalCount' => $query->count() > 1000 ? 1000 : 0
]);
```
May be is there better solution? Thanks

**Comment by samdark** [comment]
@sergeymaskin please don't reuse old issues for new problems. Also please ask questions at the forum. GitHub is for bugs and feature requests. Thanks!
