### ISSUE TITLE
Fail to upload image using HTTP Post (multipart/form-data)

### ISSUE THREAD

**Issue by kelckhyw21** [yiisoft/yii2#9310]
I am developing a RESTful API which required to upload images. I tried to use this method: https://github.com/yiisoft/yii2/blob/master/docs/guide/input-file-upload.md.

The only difference is Paw/2.2.2 is used as REST client(User-Agent) instead of use `ActiveForm`.
Content-Type is set to multipart/form-data.

```
POST /test/v1/site HTTP/1.1
Content-Type: multipart/form-data; boundary=__X_PAW_BOUNDARY__
Host: localhost
Connection: close
User-Agent: Paw/2.2.2 (Macintosh; OS X/10.10.4) GCDHTTPRequest
Content-Length: 9699

--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="imageFile"; filename="123.jpg"
Content-Type: image/jpeg
```

Here is the main.php:
```
'urlManager' => [
    'enablePrettyUrl' => true,
    'enableStrictParsing' => true,
    'showScriptName' => false,
    'rules' => [
        [
            'class' => 'yii\rest\UrlRule',
            'controller' => [
                'v1/site',
            ],
            'patterns' => [
                'POST' => 'upload'
            ],
            'pluralize' => false,
        ]
    ]
]
```

I have checked that $_FILES contain the uploaded image
```
$_FILES = [
    'imageFile' => [
        'name' => '123.jpg',
        'type' => 'image/jpeg',
        'tmp_name' => '/Applications/XAMPP/xamppfiles/temp/phpKca0Us',
        'error' => 0,
        'size' => 9553,
    ],
];
```

But `UploadedFile::getInstance($model, 'imageFile')` always return `null`.

**Comment by SDKiller** [comment]
> name="imageFile"

Most probably it is not bound to model  because of missing form name - 
for reference see `\yii\helpers\BaseHtml::getInputName`

**Comment by kelckhyw21** [comment]
Thanks SDKiller, problem solved.
For `\yii\web\UploadedFile::getInstance($model, 'imageFile')`, use `name="UploadForm[imageFile]"`
For `\yii\web\UploadedFile::getInstanceByName('imageFile')`, use `name="imageFile"`
