### ISSUE TITLE
wrong id generated by yii\grid\ActionColumn

### ISSUE THREAD

**Issue by aliv** [yiisoft/yii2#9311]
hi,
[doc has a example] (http://www.yiiframework.com/doc-2.0/yii-data-activedataprovider.html) which shows how to use ActiveDataProvider without ActiveRecord.

but generated gridview action url has wrong id started with 0 when query is created by query builder. everything is ok when query passed to dataproviader with ActiveRecord.

i guess problem is with $key (key of model) in yii\grid\ActionColumn which is not defined in query builder.
[there is another report](http://www.yiiframework.com/forum/index.php/topic/57623-wrong-id-in-gridview-action-column/) on forum which i found.

**Comment by cebe** [comment]
you have to configure the key property if you need a key column: http://www.yiiframework.com/doc-2.0/yii-data-activedataprovider.html#$key-detail

**Comment by tonny-sofijan** [comment]
I have 2 related table, **event** and **participant**

**Event Model**:
```
    public function getParticipants() {
        return $this->hasMany(Participant::className(), ['event_id' => 'id']);
    }
```

**EventController:**
```
    public function actionView($id) {
        $model = $this->findModel($id);
        $participants = new ArrayDataProvider([
            'allModels' => $model->participants,
            'pagination' => false,
        ]);
        return $this->render('view', ['model' => $model, 'participants' => $participants]);
    }
```

**views/event/view.php:**
```
<?= $this->renderAjax('/participant/index', [
        'dataProvider' => $participants, 
        'searchModel' => false
    ]) ?>
```
**view/participant/index.php** generated by yii


**_The Question is:_**
- Why renderAjax gridview action url has wrong id? There's a workaround (adding a bit of code to views/participant/index.php, ActionColumn template and buttons. But can we have it automated? When we call ActiveDataProvider or ArrayDataProvider, it will check and get the ActiveRecord automatically.

Thanks!
