### ISSUE TITLE
Date discreapncies between Formatter::asDate() and FormatConverter::convertDateIcuToJui() discrepancies

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#9312]
I noticed the following differences when using jQuery-UI Datepicker. `Formatter` was providing the date input's initial value on page load and the format changed after using Datepicker.

Both are ICU 'medium'.

| locale | asDate() | convertDateIcuToJui() |
| --- | --- | --- |
| en-US | Apr 4, 2015 | Apr 4 2015 |
| ru-RU | 04 авг. 2015 г. | 04 Авг 2015 г. |

or something like that

**Comment by cebe** [comment]
I am unable to reproduce this, do you have the PHP intl extension installed?

**Comment by tom--** [comment]
intl 1.1.0
ICU 52.1
PHP 7.0.11

In app config

```
    'language' => 'ru-RU',
```

```php
<?php

class TestForm extends \yii\base\Model
{
    public $date = '2016-11-27';
}

class TestController extends \yii\web\Controller
{
    public function actionTest()
    {
        return $this->render('test', ['model' => new TestForm()]);
    }
}
```

```php
<?php $form = \yii\widgets\ActiveForm::begin(); ?>
<?= $form->field($model, 'date')->widget(\yii\jui\DatePicker::className(), ['dateFormat' => 'medium']) ?>
<?php \yii\widgets\ActiveForm::end(); ?>
```

Initial page load

![Alt text](https://monosnap.com/file/sKFUEu6HWYeXYChf3FIFlTVuWL3tzs.png)

Click on 27 Nov in the date picker

![Alt text](https://monosnap.com/file/j8mk0f0QshW3hWXbrLAxUyOVa43Yxf.png)

Date is now formatted as

![Alt text](https://monosnap.com/file/CyKeAsf9fKoqBf2lbTnfbbVi4VDLqS.png)

**Comment by tom--** [comment]
i cannot be sure that intl was installed when i ran the test in aug last year but it most likely was because i have required it as standard for years

**Comment by bscheshirwork** [comment]
confirm now

```sh
bower-asset/bootstrap                   v3.3.7            
bower-asset/highcharts                  v5.0.14           
bower-asset/inputmask                   3.3.10            
bower-asset/jquery                      3.2.1             
bower-asset/jquery-ui                   1.11.4            
bower-asset/punycode                    v1.3.2            
bower-asset/typeahead.js                v0.11.1           
bower-asset/yii2-pjax                   2.0.7.1           
yiisoft/yii2                            dev-master 1ad69de Yii PHP Framework Version 2
yiisoft/yii2-jui                        dev-master 75e6f78 The Jquery UI extension for the Yii framework
```
php: [7.1.10-fpm-alpine-4yii2-xdebug](https://github.com/bscheshirwork/docker-php/blob/master/yii2-alpine-xdebug/Dockerfile)
```sh
intl 1.1.0 

ICU version => 57.1
ICU Data version => 57.1
```
```
requirements.php
ICU version: OK
ICU Data version: OK
```

```php
<?php
\Yii::$app->language = 'ru';
class TestForm extends \yii\base\Model
{
    public $date = '2017-10-25';
}
$model = new TestForm;
$form = \yii\widgets\ActiveForm::begin();
?>
<?= $form->field($model, 'date')->widget(\yii\jui\DatePicker::className(), ['dateFormat' => 'medium']) ?>
<?php \yii\widgets\ActiveForm::end(); ?>
```
![peek 2017-10-25 12-19](https://user-images.githubusercontent.com/5769211/31991401-59981fb2-b980-11e7-9b83-a10eed1ce057.gif)

**Comment by cebe** [comment]
@bscheshirwork thanks for the detailed research. I just looked into the jquery UI sources and found that they have hardcoded the month names:

https://github.com/jquery/jquery-ui/blob/74f8a0ac952f6f45f773312292baef1c26d81300/ui/i18n/datepicker-ru.js#L22-L23

**Comment by cebe** [comment]
>  So... This issue can be moved to yiisoft/yii2-jui and can be remove from milestone 2.0.13?

yep, thanks for noting.
