### ISSUE TITLE
RBAC DbManager getPermissionsByUser cannot get all permissions

### ISSUE THREAD

**Issue by yrssoft** [yiisoft/yii2#9314]
I allot permission and role to user （insert into auth_assignment）
such as 

```
item                user_id
permission1    1
permission2    1
role1               1                           
role2               1                           
```
 
`role1` include `permission3` and `role2` include `permission4` `permission5`

when i try to get all permissions by the method named `getPermissionsByUser` of `DbManager`
it just return the `permission3` `permission4` `permission5`

i viewed the source,in my opinion,This is because the code below：

```php
protected function getChildrenRecursive($name, $childrenList, &$result)
    {
        if (isset($childrenList[$name])) {
            foreach ($childrenList[$name] as $child) {
                $result[$child] = true;
                $this->getChildrenRecursive($child, $childrenList, $result);
            }
        }
      // when i add the below code,i get all permissions exactly
       else {
            $result[$name] = true;
        }
    }
```

**Comment by dynasource** [comment]
can you please put it little more effort in your post? You should take a loot at Markdown https://guides.github.com/features/mastering-markdown/ and put your code in code containers.

**Comment by samdark** [comment]
Formatted first post. Looks much more readable now.

**Comment by hesna** [comment]
I have the same problem. my case is much simpler though. I have a user and it has just one permission.
the permission is assigned to user directly, there are no roles involved:
```php
Yii::$app->authManager->assign($permision, $userId);
```
`getPermissionsByUser()` method returns an empty array. looking at its code, it seems that it does not look for directly assigned permissions to a user. it just tries to return permissions that are inherited from an assigned role:
```php
        $query = (new Query)->select('item_name')
            ->from($this->assignmentTable)
            ->where(['user_id' => (string) $userId]);

        $childrenList = $this->getChildrenList();
        $result = [];
        foreach ($query->column($this->db) as $roleName) {
            // $result is empty because there are no roles assigned to this user.
            $this->getChildrenRecursive($roleName, $childrenList, $result);
        }

        if (empty($result)) {
            // but this user has a direct permission, we should check for that before returning empty!
            return [];
        }
```
Also in the case @yrssoft described system is returning inherited permissions, but not directly assigned permission (permission1 and permission2).

**Comment by samdark** [comment]
Merged with some minor adjustments. Well done. Thanks!

https://github.com/yiisoft/yii2/commit/5569eaae061a8adbb222489c532c320baa673e87
