### ISSUE TITLE
Some warnings ignored in Event callback

### ISSUE THREAD

**Issue by circulon** [yiisoft/yii2#9315]
There seems to be a problem with handling some warnings (and possibly errors) in event callbacks
like beforValidate()
example this does not throw an error in a form model when its submitted and continues on and then even redisplays the view.   getErrors is also empty on redisplay of the view.
$model->load($_POST) returns true

```php 
    public function beforeValidate($attributeNames = NULL, $clearErrors = true)
    {
        if (parent::beforeValidate($attributeNames, $clearErrors)) {
          // the following line SHOULD throw a warning but does not
           $number = preg_replace('-', '' , '123-456-789');
           return true; 
       }
       return false;     
}
```

whereas the following in the same model works correctly and throws a warning like
    preg_replace(): No ending delimiter '-' found

```php
    public function init()
    {
        parent::init();
        $number = preg_replace('-', '' , '123-456-789');
    }
```

Let me know if this needs clarification

**Comment by cebe** [comment]
where did you get the signature of beforeValidate() from? why are there two parameters?
Maybe the code above is never executed?

**Comment by circulon** [comment]
Oops my bad for putting the wrong method sig, looks like I was reading the wrong docs!
I will edit the question,  but the problem still stands.

doing a var_dump or d()  (using Kint) in the beforeValidate like this
```php
    d("before");
    $number = preg_replace('-', '' , '123-456-789');
    d("after");
```
will render the view with "before" but NOT "after" and no PHP error either.

I hope this clarifies things and thanks for the method sig note, its getting late and I think I need some sleep! ;)

**Comment by dynasource** [comment]
> Let me know if this needs clarification
definately. Its hard to understand what your issue is and where the root of your issue comes from (show a complete representation of your code)
