### ISSUE TITLE
Advanced Project Template guide url is broken [RU]

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#9316]
rel #9229

@samdark in https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/README.md 

```
Специальные темы
 - Шаблон приложения advanced (broken)
```

It has been just deleted.
https://github.com/yiisoft/yii2/blob/2.0.5/docs/guide-ru/tutorial-advanced-app.md

And no transfer to https://github.com/yiisoft/yii2-app-advanced/tree/master/docs

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/187cec5e8e807184828cfff4867d7211b2b03d0d

**Comment by githubjeka** [comment]
Безвозвратно утерянный перевод - https://github.com/yiisoft/yii2/blob/2.0.5/docs/guide-ru/tutorial-advanced-app.md

ну да ладно :)

**Comment by samdark** [comment]
Оригинал прилично поменялся.
