### ISSUE TITLE
Fatal error when using $user->can

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9317]
A fatal error is thrown when using $user->can, when authManager is not yet defined. This breaks the stacktrace. A pull request will follow.

**Comment by samdark** [comment]
What do you mean by "breaks the stacktrace"?

**Comment by dynasource** [comment]
the following line renders a fatal error when authmanager is not defined:
https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L661

cannot access property on object which isnt defined.

**Comment by samdark** [comment]
Ah, right. If you'll install XDebug it will show you full stacktrace. That's PHP limitation.

But overall, that's probably a good check.

**Comment by dynasource** [comment]
I guess this check better suits the method description also: https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L642

**Comment by creocoder** [comment]
@dynasource Why you close it?!

**Comment by dynasource** [comment]
I prefer the solution in application . If it has getters over there, I prefer errorhandling over there like in your solution.
