### ISSUE TITLE
composer.json not contain require ext-ctype

### ISSUE THREAD

**Issue by Yiivgeny** [yiisoft/yii2#9319]
My php installation without ctype module crashed yii application.
`Call to undefined function yii\db\ctype_digit() in yiisoft/yii2/db/QueryBuilder.php on line 832)`
Why composer.json not contain `ext-ctype` in require section?

Also ctype extension used in https://github.com/yiisoft/yii2/blob/master/framework/caching/Cache.php#L86

Same problem in depedencies **cebe/markdown**, ezyang/htmlpurifier, swiftmailer/swiftmailer

**Comment by samdark** [comment]
Adding `ext-ctype` is a good idea. It's already in requirements checking script.

Other dependencies are there:

- https://github.com/yiisoft/yii2-swiftmailer/blob/master/composer.json#L22
- https://github.com/yiisoft/yii2/blob/master/framework/composer.json#L59
- https://github.com/yiisoft/yii2/blob/master/framework/composer.json#L60
