### ISSUE TITLE
Using DB for translation messages errors if database isn't called 'db'

### ISSUE THREAD

**Issue by raccoon69** [yiisoft/yii2#9323]
yii2/console/controllers/MessageController.php passes in a $db definition to the function saveMessagesToDb() function, line 164.

```php
    protected function saveMessagesToDb($messages, $db, $sourceMessageTable, $messageTable, $removeUnused, $languages)
    {
        $q = new \yii\db\Query;
        $current = [];

        foreach ($q->select(['id', 'category', 'message'])->from($sourceMessageTable)->all() as $row) {
            $current[$row['category']][$row['id']] = $row['message'];
        }
```

However, since the all() function isn't passed the $db, it tries to get a component called 'db', this is fixed by changing line 169 to 

```php
        foreach ($q->select(['id', 'category', 'message'])->from($sourceMessageTable)->all($db) as $row) {
```

I discovered this on version 2.0.5, but it looks like the problem still exists in 2.1

The relevant part of my messages.php file is:

```php
    // 'db' output format is for saving messages to database.
    'format' => 'db',
    // Connection component to use. Optional.
    'db' => 'shared_db_i8n',
```

If I copy the contents of the database definition 'shared_db_i8n' to a new one 'db', the error goes away.  The problem still exists with the code.

This problem may exist in other places

**Comment by samdark** [comment]
Fixed. Thanks!
