### ISSUE TITLE
Console command via web interface

### ISSUE THREAD

**Issue by johnss** [yiisoft/yii2#9325]
I want to use console command via web interface because i dont have acces to cli using my android tablet & other mobile device, there are exists PHP for Android ( http://php-for-android.googlecode.com ) however seems no longer maintained.

Since many important action can only be performed using cli such as migration, i want yii to add this feature, maybe in we can add the feature to the Gii interface.

**Comment by samdark** [comment]
I plan creating an extension providing it in a browser.

Will be here: https://github.com/samdark/yii2-webshell

**Comment by cebe** [comment]
also related #6904
