### ISSUE TITLE
ActiveQuery getAlias

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9326]
I am looking for a function which returns the alias for a 'from' in ActiveQuery. It doesnt seem available.
Looking forward into ActiveQuery, it seems that some refactoring is still left to do:
* https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L161
* https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L541

Is this something on the roadmap or should someone do a PR?

**Comment by cebe** [comment]
a bit related to #2377

**Comment by mikk150** [comment]
What's the status on this one?

**Comment by dynasource** [comment]
I can make a PR? @cebe?

**Comment by cebe** [comment]
@dynasource sure you can work on this. A good solution however is not easy to achive as it should cover a lot of things. Thus the relation to  #2377 and #7263.

**Comment by dynasource** [comment]
I will look at it. Start with small steps at a time.

**Comment by cebe** [comment]
@dynasource see #10253

**Comment by cebe** [comment]
@dynasource can you please describe your use case in detail? While discussing my PR we found that there are problems with finding a solution in situations where a table is joined multiple times.
For finding a solution that fits your case we need to know what you are trying to do.

**Comment by cebe** [comment]
closing this as a duplicate of #7263 as that one contains more info on use cases.
@mikk150 @dynasource please add your thoughts there.
