### ISSUE TITLE
Add ability to add comment for SchemaBuilder

### ISSUE THREAD

**Issue by alxkolm** [yiisoft/yii2#9330]
Add ability for adding comment to SchemaBuilder

Somthing like:
```$this->boolean()->notNull()->defaultValue(0)->comment('column comment')```

**Comment by samdark** [comment]
Related to #8148

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/9089

**Comment by SilverFire** [comment]
Implemented in fde8aa6bcbb902aaea10f02f07fa87e11e5d2d17
