### ISSUE TITLE
Simplify DI callable example

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#9331]
In the [documentation](http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#php-callable-injection) we find this example:

```php
class FooBuilder
{
    public static function build()
    {
        return function () {
            $foo = new Foo(new Bar);
            // ... other initializations ...
            return $foo;
       };        
    }
}

$container->set('Foo', FooBuilder::build());

$foo = $container->get('Foo');
```

I think, this is unnecessarily complex: It calls a function, which returns another function which, when called, will finally build the requested `Foo` component. The method `FooBuilder::build()` is called every time, no matter if the `Foo` component is used or not.

Here's my suggestion for a simpler implementation:

```php
namespace app\helper;
class FooBuilder
{
    public static function build()
    {
            $foo = new Foo(new Bar);
            // ... other initializations ...
            return $foo;
    }
}

$container->set('Foo', ['app\helper\FooBuilder', 'build']);

$foo = $container->get('Foo');
```

The advantage is, that `FooBuilder::build` is only called, when the component is really requested.

Remember, that the above constructs are most likely to be used in config files. So it makes a difference if we can avoid some method calls until they are really required.

**Comment by lynicidn** [comment]
:+1:

**Comment by dynasource** [comment]
I agree on this one. Why use a nested function in an empty function? Either show a usecase for this or use the suggestion of @mikehaertl

**Comment by samdark** [comment]
Done. @mikehaertl thanks!
