### ISSUE TITLE
AssetManager symlink fails if hashCallback returns nested directories

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#9333]
If you use `hashCallback` and return a nested path, e.g. 

```php
return sprintf('%x/%x', crc32($path), crc32(Yii::getVersion() . $time));
```

and `linkAssets` is true, the symlink will fail, since the base directory does not exist yet.
You can work around this by creating the base directory in your callback, but this could be handled by AssetManager.

**Comment by klimov-paul** [comment]
What is a reason of returning a nested path at `hashCallback` ? It does not make any sense.
Issue sounds like incorrect usage.

**Comment by nkovacs** [comment]
The reason is that I can separate the asset directories into stable hashes, so that I can delete older versions of assets when they're no longer needed.

**Comment by SilverFire** [comment]
Fixed 01a6235

**Comment by SilverFire** [comment]
Thank you!

**Comment by githubjeka** [comment]
https://github.com/yiisoft/yii2/commit/01a6235059027c6ab692b86523118498f77055d7#commitcomment-15105103
