### ISSUE TITLE
[FR] yii\i18n\Formatter: add asUTC[Date|Time|Datetime]() functions

### ISSUE THREAD

**Issue by fabioaccetta** [yiisoft/yii2#9334]
If I correctly understand, `yii\i18n\Fromatter::as[Date|Time|Datetime]()` functions convert date/time values from other timezones (or from the default one - UTC is suggested) to the application or component timeZone (i.e. the timezone written in the application config or in the component one).

According to the idea to have date/time saved on database in UTC format, I think it would be useful having UTC methods. For example, to save the `'now'` datetime value to db (in UTC timezone), today I need to use this workaround:

```php
$formatter = Yii::$app->formatter;
$old = $formatter->timeZone;
$formatter->timeZone = 'UTC';
$model->date_field = $formatter->asDatetime('now');
$formatter->timeZone = $old;
```

Instead, it would be more easy if I could write:
```php
$model->date_field = $formatter->asUTCDatetime('now');
```
or, for post data
```php
$post = Yii::$app->request->post();
if ($model->load($post) && $model->validate())
{
   // suppose 'date_field' comes, for example, from a DateTime Widget
   // that does not automatically convert user value (i.e. localized date/time) to UTC
   $model->date_field = $formatter->asUTCDatetime($model->date_field);
}
```

This way, `yii\i18n\Fromatter` could be used both in views (to format database values - from UTC to actual timeZone) and in controllers to save models (i.e., data value comes from a date widget, so input date is in local timezone and not in UTC).
Thanks.

**Comment by fabioaccetta** [comment]
Otherwise, we could consider `asDefault[Date|Time|Datetime]()` functions instead of `UTC` ones, to convert from `Formatter::$timeZone` to `Formatter::$defaultTimeZone`, because `Formatter::$defaultTimeZone` may not be `UTC`.

**Comment by cebe** [comment]
> According to the idea to have date/time saved on database in UTC format, I think it would be useful having UTC methods.

Formatter is for creating i18n date output for user view. If you want to create dates for the database you can use DateValidator or just use `date('Y-m-d')`.

`asUTCDatetime` would return a date in a human readable format which is not suited for storage.
