### ISSUE TITLE
add saveAll on activerecord

### ISSUE THREAD

**Issue by engmmrj** [yiisoft/yii2#9335]
hi , guies yii

for exsample for count of fields more than 1 must it send array.
method saveAll add to activerecord array insert.

$item = [
    'User' => [
        ['name' => 'Hussein'],
        ['name' => 'Ali']
    ]
];

like method fllow:
public function saveAll($runValidation = true, $attributesNames = null)
    {
        
        if ($this->getIsNewRecord()) {
            $transaction = $order->getDb()->beginTransaction();
            foreach($attributesNames as $attr) {
               
                  if (! $this->insert($runValidation, $attributeNames)) {
                    $transaction->rollBack();
                    return false;
                  }
            }
        }
        else {
              $transaction = $order->getDb()->beginTransaction();
            foreach($attributesNames as $attr) {
                if (! $this->update($runValidation, $attributeNames)) {
                    $transaction->rollBack();
                     return false;
                  }
              
            }
        }
    }

**Comment by cebe** [comment]
you can not have many records in one object. you have to create one activerecord instance per database column.

**Comment by engmmrj** [comment]
what's Model::updateAll(), cebe ?

**Comment by cebe** [comment]
it does not fit your use case as far as I see. check the docs: http://www.yiiframework.com/doc-2.0/yii-db-activerecord.html#updateAll%28%29-detail
