### ISSUE TITLE
Add ability to use \yii\db\Expression for SchemaBuilder::defaultValue()

### ISSUE THREAD

**Issue by alxkolm** [yiisoft/yii2#9337]
Add ability to use `\yii\db\Expression` for `SchemaBuilder::defaultValue()`.
Particularly this need for assign default value to TIMESTAMP column:
`$this->timestamp()->defaultValue(new \yii\db\Expression('CURRENT_TIMESTAMP'))`

**Comment by klimov-paul** [comment]
Perhaps we should introduce another method `defaultExpression()` for expressions to simplify syntax:
```php
$this->timestamp()->defaultExpression('CURRENT_TIMESTAMP')
```

**Comment by cebe** [comment]
:+1:

**Comment by yupe** [comment]
+1

**Comment by bajabob** [comment]
+1
