### ISSUE TITLE
Add after('some_column') in ColumnSchemaBuilder

### ISSUE THREAD

**Issue by ViZH** [yiisoft/yii2#9340]
It's better to use new syntax:

```php
$this->addColumn(Model::tableName(), 'new_column', $this->boolean()->after('some_column'));
```

instead of 

```php
$this->addColumn(Model::tableName(), 'new_column', Schema::TYPE_BOOLEAN.' AFTER some_column');
```

**Comment by cebe** [comment]
can you do some research about the syntax for this in different dbms? Links to the corresponding docs would be helpful.

**Comment by ViZH** [comment]
It's not possible to add a column between two existing columns with an ALTER TABLE statement in SQLite, PostgreSQL and MSSQL. But it's important to Oracle and MySQL. Fixed length fields in some storage engines must be aligned before varchars, texts and blobs.

Oracle syntax (http://docs.oracle.com/cd/E17952_01/refman-5.0-en/alter-table.html)
ALTER TABLE table CHANGE COLUMN column AFTER column

MySQL syntax (https://dev.mysql.com/doc/refman/5.1/en/alter-table.html)
ALTER TABLE table CHANGE COLUMN column AFTER column

Cubrid syntax (http://www.cubrid.org/manual/841/en/CHANGE%7CMODIFY%20Clause)
ALTER TABLE table CHANGE COLUMN column AFTER column

**Comment by df2** [comment]
This covers it I think: https://github.com/df2/yii2/commit/8501bb2e644f24b43742de923f550412558fcc1e

Can someone please take that and plz make it into a pull request.

Regarding the tests: I made some modifications to the formatting of the test data structures in another pull request (https://github.com/yiisoft/yii2/pull/9617).

I think someone has made changes to the test data in the mean time so the tests aren't mergable anymore.

It might be worth deciding if you want to stick with the old or new test data format before we write the tests for this. We can get the `char` tests up to shape at the same time then.

**Comment by samdark** [comment]
@df2 if it's MySQL and Oracle, it should not add anything when used with other DBs.

**Comment by df2** [comment]
@samdark well I would have thought in that case they would just not use the `after()` method when writing their migrations.

**Comment by df2** [comment]
@samdark I suppose switching from one database that supports it to another that doesn't and you want to run the migrations against the new one... So something like this then? Where should that list of compatible databases be stored? Thx!

```php
protected function buildAfterString()
{
    if ($this->after !== null && in_array(Yii::$app->db->..., [ORACLE,MYSQL,CUBRID]) {
         return " AFTER ('{$this->after}')";
    } 
    else {
        return "";
    }
}
```

**Comment by samdark** [comment]
Yes. Note that there are DB specific `ColumnSchemaBuilder` classes.

**Comment by df2** [comment]
This is the only other one I could find. If so, then it just needs the line added to call the `buildAfterString()` method. I would submit it myself but I believe something went awry with the forked repo and I have other open pull requests.
![2015-12-28-050426_1680x1024_scrot](https://cloud.githubusercontent.com/assets/1834925/12019092/916cc190-ad20-11e5-87c9-7847839435c2.png)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/9455

**Comment by twisted1919** [comment]
Bump on this...

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/10494 partially solves the issue. @twisted1919 do you want to add `first` support to it?

**Comment by twisted1919** [comment]
@samdark - i am just picking up yii2 after tons of yii1 and golang. Will be a while till i will be comfortable to do a pull request.

**Comment by samdark** [comment]
I see. I can solve it for 2.0.8.

**Comment by df2** [comment]
@samdark Would be interested in a consensus on how to implement generic vs independent build methods. Your approach with `unsigned` was to override the parent implementation with a version that returns an empty string when the feature is not supported.

I would like to suggest we reverse this approach. The base implementations should return an empty string, and the features _added_ by vendor specific implementations.

This would apply to `unsigned`, `after`, `first`.

**Comment by samdark** [comment]
Then we have to create more DB-specific classes: MySQL, Cubrid etc.
