### ISSUE TITLE
Need to click submit button twice if button name is being set

### ISSUE THREAD

**Issue by edxz** [yiisoft/yii2#9351]
I have a form with multiple submit buttons, so I've to differentiate them using name and value
This is the sample of my form:
```

<?php $form = ActiveForm::begin([
    'enableClientValidation' => false
]); ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Calculate'), [
              'class' => 'btn btn-success hidden',
              'value'=> 'calculate',
              'name' => 'submit',
            ]) ?>
            <?= Html::submitButton(Yii::t('app', 'Submit'), [
                'class' => 'btn btn-success',
                'value'=> 'submit',
                'name' => 'submit',
            ]) ?>
    </div>
<?php ActiveForm::end(); ?>
```

When I click the button/enter for the first time, it won't respond, and the form will submit after second attempt.
Is there any workaround for this issue ?  thx

**Comment by edxz** [comment]
I managed to workaround it by following the buttons in gii
I just remove the button value and set the name to 'calculate'
and then change some logic in controller

**Comment by cebe** [comment]
check the docs of submitButton: http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#submitButton%28%29-detail
