### ISSUE TITLE
Using `AccessFilter` may lead to php fatal error in some cases

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#9353]
Example:

```php
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index'],
                        'roles' => ['*'],
                        'allow' => true,
                    ],
                ],
            ],
        ];
    }
```

Will lead to:

```
PHP Fatal Error – yii\base\ErrorException
Call to a member function checkAccess() on null
```

**Comment by cebe** [comment]
stacktrace?

**Comment by creocoder** [comment]
@cebe Stacktrace:

1. in C:\Users\creocoder\Projects\test\vendor\yiisoft\yii2\web\User.php at line 661
2. yii\base\ErrorHandler::handleFatalError()

Nothing more.

**Comment by cebe** [comment]
do you have an error action configured and not provided access to it in AccessControl filter?

**Comment by creocoder** [comment]
@cebe Please check code. This is pure AccessFilter (under layer components) coding mistakes. Any non existent role will lead to that error. Also not that trouble happen only when user is guest.

**Comment by creocoder** [comment]
> do you have an error action configured and not provided access to it in AccessControl filter?

@cebe `'only' => ['index']` does not affect anything. Fatal error is happen in any case.

**Comment by dynasource** [comment]
this is a reason for applying https://github.com/yiisoft/yii2/pull/9318

You are using $user->can when authManager is not yet defined.
With a full stacktrace you could find out where.

**Comment by creocoder** [comment]
> this is a reason for applying #9318

This is NOT RELATED issue.

**Comment by creocoder** [comment]
Dublicate of #9317
