### ISSUE TITLE
$this->registerJs(<<<EOF loses IDE javascript formatting

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#9354]
Maybe we should integrate a new way to do this, like

<?php $this->registerJsStart() ?>
//Javascript code here
<?php $this->registerJsEnd() ?>

**Comment by creocoder** [comment]
Use `<<<JS` in PhpStorm or move js to external files (better).

**Comment by BenasPaulikas** [comment]
I need this to be in view file, am I missing something ?
![lol](https://cloud.githubusercontent.com/assets/6473565/9154408/82585b8c-3e95-11e5-9736-1b82234c473f.png)

**Comment by cebe** [comment]
works fine in phpstorm:

![bildschirmfoto vom 2015-08-09 22 51 12](https://cloud.githubusercontent.com/assets/189796/9156884/52ff4d56-3ee9-11e5-8c82-6cda09dbf708.png)

make sure to set inspection and highlighting level to maximum. Anyway not a yii issue.

**Comment by cebe** [comment]
you may have an external file and register its contents like `$view->registerJs(file_get_contents('somefile.js'));`

**Comment by Faryshta** [comment]
@cebe no please don't promote that.

`$view->registerJs($this->render('hellotest.js'));
