### ISSUE TITLE
BaseActiveRecord could do with it's own setAttributes()

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2#9355]
I came across this when needed to implement my own `populateRecord` due to finding that console edited documents in my MongoDB totally mess up PHP data types.

Essentially the problem is in performance. You use the `Model` function which looks like:

``` php
    public function setAttributes($values, $safeOnly = true)
    {
        if (is_array($values)) {
            $attributes = array_flip($safeOnly ? $this->safeAttributes() : $this->attributes());
            foreach ($values as $name => $value) {
                if (isset($attributes[$name])) {
                    $this->$name = $value;
                } elseif ($safeOnly) {
                    $this->onUnsafeAttribute($name, $value);
                }
            }
        }
    }
```

Which looks fine until you realise what `__set` does in `BaseActiveRecord` when calling `hasAttribute`:

``` php
    public function hasAttribute($name)
    {
        return isset($this->_attributes[$name]) || in_array($name, $this->attributes());
    }
```

As you can see it is doubling (at least) the work of the function by calling `$this->$name`. Instead `BaseActiveRecord` should have it's own `setAttributes` which looks like:

``` php
    public function setAttributes($values, $safeOnly = true)
    {
        if (is_array($values)) {
            $attributes = array_flip($safeOnly ? $this->safeAttributes() : $this->attributes());
            foreach ($values as $name => $value) {
                if (isset($attributes[$name])) {
                    $this->_attributes[$name] = $value;
                } elseif ($safeOnly) {
                    $this->onUnsafeAttribute($name, $value);
                }
            }
        }
    }
```

That would make that function a lot more performant by the looks of it.

**Comment by ssjssh** [comment]
:+1:

**Comment by dynasource** [comment]
its good to see you are trying to find optimizations for the setter. The problem with your example is that you are ignoring the current __set, which make you ignore potential behaviors and other stuff defined in Component:
```php
    public function __set($name, $value)
    {
        if ($this->hasAttribute($name)) {
            $this->_attributes[$name] = $value;
        } else {
            parent::__set($name, $value);
        }
    }
```

I tried your solution though and almost of all my tests broke. I guess you are are making less use of behaviors to set attributes.

**Comment by Sammaye** [comment]
True I didn't think of the parent `__set`, hmm

**Comment by Sammaye** [comment]
Thinking about this more I don't think this is solvable, I understand why it was never change. Tbh, what I am really looking for in my scenario is:
```php
public function setAttributeDirect($name, $value)
{
    $this->_attributes[$name] = $value;
}
```

So I can modify the `populateRecord` function without having to copy near the entire `baseActiveRecord`

**Comment by dynasource** [comment]
This is implemented by setAttribute already:
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L445

```php
    /**
     * Sets the named attribute value.
     * @param string $name the attribute name
     * @param mixed $value the attribute value.
     * @throws InvalidParamException if the named attribute does not exist.
     * @see hasAttribute()
     */
    public function setAttribute($name, $value)
    {
        if ($this->hasAttribute($name)) {
            $this->_attributes[$name] = $value;
        } else {
            throw new InvalidParamException(get_class($this) . ' has no attribute named "' . $name . '".');
        }
    }

**Comment by Sammaye** [comment]
`setAttribute` would not work in a good way here. Imagine this function:
```php
    public static function populateRecord($record, $row)
    {
        $columns = array_flip($record->attributes());
        foreach ($row as $name => $value) {
            if (isset($columns[$name])) {
                $record->_attributes[$name] = $value;
            } elseif ($record->canSetProperty($name)) {
                $record->$name = $value;
            }
        }
        $record->_oldAttributes = $record->_attributes;
    }
```
but not i the same class as the private `_attributes` array. 

I mean it will work in a technical sense but not in a performance sense.

**Comment by Sammaye** [comment]
Atm I have left my code like this:
```php
    public static function populateRecord($record, $row)
    {
        foreach ($row as $name => $value) {
        	try{
        		$record->setAttribute($name, $record->resolveRecordValue($value));
        	}catch(InvalidParamException $e){
        		if ($record->canSetProperty($name)) {
        			$record->$name = $record->resolveRecordValue($value);
        		}
        	}
        }
        $record->setOldAttributes($record->getAttributes());
    }
```

which is just as bad since I am spinning up that exception everytime. In fact I might benchmark the two current variations of using this outside of `BaseActiveRecord`

**Comment by dynasource** [comment]
Im getting confused. 

In your original post, you were talking about a performance problem with the double check 'isset($this->_attributes[$name])', which can be bypassed using setAttribute()

Now you are talking about skipping hasAttribute() which basically means you can set anything in _attributes you want, skipping the allowed properties for a model.

If that is something you are after, than this is al whole different story. Why dont you implement it in you'r own function as in: _attributes_dynamic

**Comment by Sammaye** [comment]
Well my sight of the performance problem is in relation to alsp not considering the parent __set. You see I was seeing from the `populateRecord` function that I was trying to manipulate in `BaseActiveRecord`.

As I tried to fix the performance in this function, in my own `BaseActiveRecord` child, I realised that `setAttributes` would be great to use if it had that fix done. Of course, I did not foresee that the `parent::__set` would not be called for other scenarios.

So that gives you direction about my perspective. That is why I gave off a frank reply that really a way to override the `hasAttribute` method and get around it, like Yii2 does in `populateRecord`, without being in the same class would be the most ideal solution for me.

> Why dont you implement it in you'r own function as in: _attributes_dynamic

You mean as a function in my own child `BaseActiveRecord`? Because 80% of the `BaseActiveRecord` class uses `_attributes` in some way. PHP's private scoping would require me to copy the entire class nearly to do it. This means bad code reuse, especially for potential Yii2 updates.

**Comment by dynasource** [comment]
What is your biggest concern / ideal situation?

**Comment by Sammaye** [comment]
Performance and code copying.

So the first option is to use the functions that currently existin `BaseActiveRecord`. These functions are less than performant. In fact they are down right bad for this scenario, hence why the current code in `populateRecord` does not use these functions (as was said to me by Yii2 team).

The second problem is code copying. If I touch `_attributes` in any way in my child class I would have to copy (due to PHP private scoping properties) about 80% of the `BaseActiveRecord` Yii2 has in place by default. This would make for massive ode copying as well as bad reuse and for problematic updates should any part of that code experience a bug connected or in part by another part related to the `baseActiveRecord` and it needs updating (my own personal code will overwrite any updates).

To be frank, the ideal solution to this is to be able to skip Yii2's validation functions etc for `_attributes` and be able to just set it directly in a function.

**Comment by dynasource** [comment]
why dont you override the public method hasAttribute and let it return true for your scenario. It would basically gives you the solution you are looking for 

> Tbh, what I am really looking for in my scenario is:
> 
> public function setAttributeDirect($name, $value)
> {
>     $this->_attributes[$name] = $value;
> }

**Comment by Sammaye** [comment]
Because of PHP scoping. It requires me to copy every piece of code that also uses `_attributes` in `BaseActiveRecord`. I cannot just use parent private variable in a child class like that. They appear as two separate variables in inheritance (I know, weird).

**Comment by dynasource** [comment]
No I mean:
* override hasAttribute() and return i.e. true
* use setAttribute from BaseActiveRecord

in this way, you are still within BaseActiveRecord private scope

**Comment by Sammaye** [comment]
That would break the `hasAttribute` function for other scenarios wouldn't it? I only want to break it for running `populateRecord` function in the model

**Comment by Sammaye** [comment]
I mean hasAttribute is a very useful function and helps massively in other functions in the active record.

**Comment by dynasource** [comment]
you can customize this hasAttribute to whatever you want. I proposed returning true, but you can put a whole piece of software behind it.

Ie.:
```php
 public $skipHasAttribute=false;
 public function hasAttribute($name)
    {
        if($this->skipHasAttribute===true){
              $this->skipHasAttribute = false;
             return true;
        }
        return isset($this->_attributes[$name]) || in_array($name, $this->attributes());
    }

```

And then its up to you when & where you want skipping.

**Comment by Sammaye** [comment]
Yeah that could work actually, didn't think of that, lemme try it thanks

**Comment by Sammaye** [comment]
Oh wait yes, seen a way around that, nvm I will try it

**Comment by Sammaye** [comment]
Ha, I have just remembered my db contains data not meant for my PHP app. This would actually break that functionality and cause massive more recursion in `populateRecord` than is needed. I wanna know if an attribute is valid but I only wanna evaluate `attributes()`once for the entire function, not every time I go round.

**Comment by dynasource** [comment]
attributes() is public and customizable

**Comment by dynasource** [comment]
@Sammaye, can this one be closed?

**Comment by dynasource** [comment]
expired
