### ISSUE TITLE
Does Yii need a 'demo' enviroment?

### ISSUE THREAD

**Issue by gooGooGaJoob** [yiisoft/yii2#9358]
For a project I'm writing, I've just added a DEMO Environment which exists alongside the "dev" and 'prod' environments. 

The idea behind this is to enable web developers an easier means of creating a DEMO Version of their website. I.e. if the global constant YII_ENV_DEMO is defined, one can  activate specific code segments that would be needed in a demo version of the website.

If the yii community thinks this is a useful addition, I can create a pull request with the changes.

What does everyone think?

**Comment by cebe** [comment]
this is an application specific need so this constant can easily be defined in index.php of the project when needed. Imo it is not generic enought to be part of the framework by default.

**Comment by dynasource** [comment]
apart from this constant, I dont think its a bad idea to elaborate on the practical requirements for a demo environment, as a demo environment in itself is generic enough. Its plays a important role in a development lifecycle.
