### ISSUE TITLE
Number max rule is not behaving properly

### ISSUE THREAD

**Issue by kalpitpandit** [yiisoft/yii2#9361]
I have my rules method as below : 

return [
            [['discount'], 'number', 'min' => 1, 'max' => 3], // Not working properly
            [['promotion_code'], 'string', 'max' => 15],
];

When i am submitting form i am getting error "Discount must be no greater than 3" though i am inserting 2 digit from form.

As i see if i enter 1 number its working fine but for more than 1 its throwing above error.

I have checked with string max and its working fine.

**Comment by cebe** [comment]
can you check whether it works with the compare validator?

**Comment by kalpitpandit** [comment]
Yes its working fine with compare.. 

['discount', 'compare', 'compareValue' => 99, 'operator' => '<=']

**Comment by kalpitpandit** [comment]
I can see in NumberValidator validateAttribute() condition is wrong. its comparing value with <,> operator. it should be comparing length of number. i have modified validateAttribute() and its started working.

public function validateAttribute($model, $attribute)
    {
        $value = $model->$attribute;
        if (is_array($value)) {
            $this->addError($model, $attribute, $this->message);
            return;
        }
        $pattern = $this->integerOnly ? $this->integerPattern : $this->numberPattern;
        
        $length = strlen((string)$value);
        
        if (!preg_match($pattern, "$value")) {
            $this->addError($model, $attribute, $this->message);
        }
        if ($this->min !== null && $length < $this->min) {
            $this->addError($model, $attribute, $this->tooSmall, ['min' => $this->min]);
        }
        if ($this->max !== null && $length > $this->max) {
            $this->addError($model, $attribute, $this->tooBig, ['max' => $this->max]);
        }
    }

**Comment by cebe** [comment]
no, it should not compare the length. if you need to check the length of a number you have to user string validator for that.

**Comment by kalpitpandit** [comment]
ahh i see.
