### ISSUE TITLE
redirect HTTP to HTTPS in advanced Yii2 app.

### ISSUE THREAD

**Issue by jaiminmoslake7020** [yiisoft/yii2#9363]
My .HTACCESS at root directory

```
Options -Indexes

<IfModule mod_rewrite.c> 
  RewriteEngine on

  RewriteCond %{REQUEST_URI} !^public
  RewriteRule ^(.*)$ frontend/web/$1 [L] 
</IfModule>

# Deny accessing below extensions
<Files ~ "(.json|.lock|.git)">
Order allow,deny
Deny from all
</Files>

# Deny accessing dot files
RewriteRule (^\.|/\.) - [F]
```

and my .HTACCESS at root/frontend/web/ folder is

```

RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule . index.php

```

Now i want to transfer all urls fropm  HTTP to HTTPS ... i tried some possible ways but thety are not working

Here it is my stackoverflow question.  [stackoverflow question](http://stackoverflow.com/questions/31835406/redirect-http-to-https-in-yii2-htaccess)

**Comment by samdark** [comment]
That's server config question, not Yii issue.

**Comment by jaiminmoslake7020** [comment]
hello @samdark  but is there any way i can solve it... .HTACCESS is working ... just i am not finding any way to redirect my urls from HTTP to HTTPS ... i had asked question in forum and stackoverflow but not able to get solution. So may be you guys had done something like this...  so can i get code snippet of that .HTACCESS

**Comment by samdark** [comment]
Yes. I'm sure it can be solved. I'm not using Apache so I can't help.

**Comment by jaiminmoslake7020** [comment]
@samdark  Ok thanks..

**Comment by semiromid** [comment]
it can make in `UrlRuleInterface`.

`
            if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'off') { 

            } 
`
