### ISSUE TITLE
ReflectionException help slove the problem

### ISSUE THREAD

**Issue by AndruAlex** [yiisoft/yii2#9365]
On the localhost yii2 work good!
When i push on the repo git and filled to the server i recive this error!
plz help with problem
![image](https://cloud.githubusercontent.com/assets/11726264/9170625/2443c58a-3f6d-11e5-8db3-6b1dfcfc2343.png)

**Comment by samdark** [comment]
Please use forums for troubleshooting. This is issue tracker i.e. you should be sure there's a problem in framework code. Thanks.
