### ISSUE TITLE
Feature request Menu widget - hideInActiveNephews

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9366]
Most of the times when using a menu with subitems, it is not necessary to also output the subitems of other menu items which are inactive (the nephews). 
Usecase:
1) performance: prevents HTML being outputted (large menus)
2) flexibility: when only 1 vertical menu 'echelon line' is required (for whatever reason)

Currently:
* outputted in HTML & active: menu 1
* outputted in HTML & active: menu 1 > menu 1.1
* outputted in HTML & non-active: menu 2 
* outputted in HTML & non-active: menu 2 > menu 2.1

Therefore I would suggest to add another parameter called:
* hideInactiveNephews
* or hideNephews

This will prevent the output of redundant and non visible menu items which would never be visible in the current route:

* outputted in HTML & active: menu 1
* outputted in HTML  & active: menu 1 > menu 1.1
* outputted in HTML & non-active: menu 2 
* not outputted in HTML & non-active: menu 2 > menu 2.1

**Comment by dynasource** [comment]
Let me try to make it more clear:

From:
* 1 > 1.1 > 1.1.1 > 1.1.1.1
* 2 > 2.2 > 2.2.2 > 2.2.2.2
* 3 > 3.3 > 3.3.3 > 3.3.3.3
* 4 > 4.4 > 4.4.4 > 4.4.4.4

To:
* 1 
* 2 > 2.2 > 2.2.2 > 2.2.2.2 
* 3 
* 4

**Comment by SilverFire** [comment]
If you set `visible` to `false`, the descendant items will not be rendered, as well as the item itself. I see no reason to duplicate behavior for the `active` option.
