### ISSUE TITLE
Prevent multiple form submission

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#9367]
I've done some tests with forms and CSRF validation. Shouldn't CSRF prevent multiple form submission too?

It doesn't matter if `enableCsrfCookie` is true or false, F5 does the job and could flood some DBs.

**Comment by samdark** [comment]
No, CSRF has nothing to do with it.

**Comment by thejahweh** [comment]
So would it not make sense to support this with a token or something?

**Comment by cebe** [comment]
F5 should not trigger a new form submission, you should redirect after a POST request.
