### ISSUE TITLE
i18n Formatter::asRelativeTime() not working

### ISSUE THREAD

**Issue by defektrain** [yiisoft/yii2#9370]
I have a problem with method asRelativeTime().

I try:
```
<?php
echo "PHP: " . PHP_VERSION . "\n";
echo "ICU: " . INTL_ICU_VERSION . "\n";
echo Yii::$app->formatter->asDate('2014-01-01');
echo Yii::$app->formatter->asRelativeTime('2014-01-01');
?>
```

and get:
```
PHP: 5.6.11
ICU: 54.1

1 янв. 2014 г.
a year ago
```

Why does the "asRelativeTime" does not return an answer in Russian?

**Comment by samdark** [comment]
Do you have `sourceLanguage` as default and `language` as `ru_RU`?

**Comment by defektrain** [comment]
yes,
```
        'language' => 'ru-RU',
        'sourceLanguage' => 'ru-RU',
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'nullDisplay' => ''
        ]
```

**Comment by samdark** [comment]
Well, you have both source and target language the same which means translation won't happen.

**Comment by defektrain** [comment]
no,
```
        'language' => 'ru_RU',
        'sourceLanguage' => 'en_US',
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'nullDisplay' => ''
        ]
```
also won't work

**Comment by samdark** [comment]
Do you have file with translated string?

**Comment by samdark** [comment]
OK. It works well for me producing

```
01 янв. 2014 г.
год назад
```

My language is set to `ru-RU`. Source language is left as default.

**Comment by samdark** [comment]
It's not connected to ICU version for sure.

**Comment by samdark** [comment]
Aha, you've used `ru_RU` while it should be `ru-RU`.

**Comment by defektrain** [comment]
no) I try to use ```ru-RU```, its not works for me.
for this method need a translation file with translate string?
eg:
```
Yii::t('yii', 'in {delta, plural, =1{a year} other{# years}}', ['delta' => $interval->y], $this->locale)
```

I thought this method works as ```asDate()```?

**Comment by samdark** [comment]
It uses `yii` category for which translations are bundled with the framework. If you haven't changed message source for it, it should work.

**Comment by defektrain** [comment]
I have a clean install ```yii2``` from ```composer```. (Windows, XAMPP)
Nothing changes, the translation files are not created. The config file contains rows:
```
        'language' => 'ru-RU',
        'sourceLanguage' => 'en-US',
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'nullDisplay' => ''
        ]
```

```asDate()``` working, but ```asRelativeTime()``` not.
What could be the reason? Any ideas?

**Comment by defektrain** [comment]
Maybe this method requires the translation files?
The file ```\yii\i18n\Formatter``` have this method, and it has a line, maybe they need to be translated? Or all the same method should work without translation files? As a method ```asDate```?

**Comment by cebe** [comment]
I have just tried to reproduce this, no luck. Works fine for me... Translations are provided by yii so there should not be anything to add from your side...

**Comment by dynasource** [comment]
what have you set in $app->i18n?

**Comment by defektrain** [comment]
```Yii::$app->i18n``` a big object.
What particularly interested in?

**Comment by dynasource** [comment]
if you empty it, will it translate?

**Comment by defektrain** [comment]
how to clean it? he is ```read-only```

**Comment by dynasource** [comment]
dont set it in config

**Comment by defektrain** [comment]
yes! its working

**Comment by defektrain** [comment]
sorry, that's my fault

**Comment by dynasource** [comment]
:+1:
