### ISSUE TITLE
Getting error unable to resolve the request

### ISSUE THREAD

**Issue by amjadniazi48** [yiisoft/yii2#9377]
I have used the following tutorial to get rid of backend and frontend
http://stackoverflow.com/questions/28118691/yii2-htaccess-how-to-hide-frontend-web-and-backend-web-completely (Last 3 steps tutorial)
and this guide to separte frontend user and backend admin table
http://www.yiiframework.com/wiki/814/guide-how-to-actually-separate-frontend-user-and-backend-admin-on-yii2-advanced/
and when i generate crud for user table or admin table and use this route to go to the user table or admin table
for user
----------------
```
localhost/mysitename/admin/user -------- [in the backend]
```
for admin
-------------------------
```
localhost/mysitename/admin/admin ----- [ in the backend]
```
i   got this error
![unable](https://cloud.githubusercontent.com/assets/2420029/9191925/0e99749c-4020-11e5-9821-01184baaf366.png)

**Comment by dynasource** [comment]
you should supply more information if you us to be able to debug:
- what is the full url for that application you're requesting
- whats is the config corresponding to this application

**Comment by amjadniazi48** [comment]
This is the code for the config in backend i.e backend/main.php

<?php

$params = array_merge(
        require(__DIR__ . '/../../common/config/params.php'), require(__DIR__ . '/../../common/config/params-local.php'), require(__DIR__ . '/params.php'), require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'name' => 'DoojaViyah.com',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
     
    'bootstrap' => ['log'],
    'modules' => [],
    'components' => [
        'user' => [
            'identityClass' => 'common\models\Admin',
            'enableAutoLogin' => true,
            'identityCookie' => [
                'name' => '_backendUser', // unique for backend
            ]
        ],
        'request' => [
            'class' => 'common\components\Request',
            'web' => '/backend/web',
            'adminUrl' => '/admin',
            'cookieValidationKey' => '[MFX3714LFI]',
            'csrfParam' => '_backendCSRF',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
        ],
        
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'session' => [
            'name' => 'PHPBACKSESSID',
            'savePath' => sys_get_temp_dir(),
        ],
    ],
    'params' => $params,
];
and following is the code for config in common/main.php
return [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
   // 'language' => 'en',
    'as beforeRequest' => [
        'class' => 'common\components\LanguageHandler',
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'i18n' => [
            'translations' => [
                'app*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    //'basePath' => '@app/messages',
                    //'sourceLanguage' => 'en-US',
                    'fileMap' => [
                        'app' => 'app.php',
                        'app/error' => 'error.php',
                    ],
                    'on missingTranslation' => ['common\components\TranslationEventHandler', 'handleMissingTranslation']
                ],
            ],
        ],
    ],
];

**Comment by amjadniazi48** [comment]
Following is the code for getting request in component
```
<?php //



namespace common\components;





class Request extends \yii\web\Request {

    public $web;

    public $adminUrl;



    public function getBaseUrl(){

        return str_replace($this->web, "", parent::getBaseUrl()) . $this->adminUrl;

    }





    /*

        If you don't have this function, the admin site will 404 if you leave off

        the trailing slash.



        E.g.:



        Wouldn't work:

        site.com/admin



        Would work:

        site.com/admin/



        Using this function, both will work.

    */

    public function resolvePathInfo(){

        if($this->getUrl() === $this->adminUrl){

            return "";

        }else{

            return parent::resolvePathInfo();

        }

    }

}
```

**Comment by dynasource** [comment]
you are using your own Request component. Thats goes beyond Yii2 issue tracker.

**Comment by amjadniazi48** [comment]
I made a fresh install of the advanced application and then create user table with gii and got the same error, no component use nothing  just fresh advanced template install and getting the same error

**Comment by amjadniazi48** [comment]
ll the code is just generated code i create only the UserController and User Views
Followng is the Config code for the backend app
```
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
    'bootstrap' => ['log'],
    'modules' => [],
    'components' => [
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
    ],
    'params' => $params,
];

```
Following is the code for user controller
```
<?php

namespace backend\Controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

```
when i use the above mentioned url  in backend i.e
```
http://localhost/newyii2/backend/web/?r=user
```
it shows the page not found error as i mentioned above

**Comment by samdark** [comment]
`namespace backend\Controllers;`
should be
`namespace backend\controllers;`

**Comment by amjadniazi48** [comment]
Thanks very much ....got it
