### ISSUE TITLE
Replaced pager links

### ISSUE THREAD

**Issue by szewciu** [yiisoft/yii2#9378]
Pjax builtin Yii2 causes replacing gridview pager links after clicking any action column button.

How to prevent it?

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for reporting issues.

**Comment by szewciu** [comment]
That's the issue. It shouldn't happened.

**Comment by samdark** [comment]
What do you mean by replacing? Overall, PJAX is replacing the whole container with new data. That's how it works.

**Comment by szewciu** [comment]
Pagination uses default action to load data showed in GridView. When I click eg. delete button in action column, it goes to actionDelete and after success links in Pager are also related to this action (delete) but they really shoulnd't - pager should be still used only to change pages, not deleting data.

**Comment by samdark** [comment]
You mean after PJAX refresh pagination buttons are triggering delete?

**Comment by szewciu** [comment]
Yes, but only when I firstly click delete button on any gridview row. When first page load and only changing gridview pages it works correctly but as I said it replaces pagination links after calling any gridview action column button, eg. 

1. Correct pagination url:

http://ue_frontend/user/address/75?_pjax=%23ustalenia-container&_=1439279618439&page=2

2. Incorrect pagination url:

http://ue_frontend/user/deleteaddress/2520?_pjax=%23ustalenia-container&_=1439279618440&page=2

As you can see in second case controller's action is changed to deleteaddress and id parameter is set to id of last deleted row.

**Comment by dynasource** [comment]
are you using enablePrettyUrl?

**Comment by szewciu** [comment]
@dynasource yes.

**Comment by dynasource** [comment]
do you have the same issue without it?

**Comment by szewciu** [comment]
Yes. 

Anyway I found temporary solution but now I need to edit whole project pjax action. It looks like:

$dataProvider->pagination->route = 'worker/address/'.$workerid;

I don't think it's good solution but it works.

**Comment by dynasource** [comment]
dont you have data-pjax="0" in the delete links?

**Comment by szewciu** [comment]
No. URLs I've posted are not from browser bar, but from inspecting element.

**Comment by dynasource** [comment]
I cannot reproduce your issue. It looks like you're delete call does not finishes with a 302
