### ISSUE TITLE
Class 'yii\bootstrap\Html' not found

### ISSUE THREAD

**Issue by look4raymond** [yiisoft/yii2#9379]
I'm having a _PHP Fatal Error – yii\base\ErrorException_.
This happens when I began to include <code>use yii\bootstrap\Html;</code> and use <code><?= Html::submitButton('Resend Activation Link', ['class' => 'btn btn-primary']) ?></code> somewhere in one of my views file.

Under the directory _vendor/yiisoft/yii2-bootstrap_, I couldn't find the file _Html.php_.
![screen shot 2015-08-11 at pm 05 03 18](https://cloud.githubusercontent.com/assets/11458029/9194060/0effdc70-404b-11e5-8605-8c8ef3b31628.png)

I just did an upgrade to Yii version 2.0.6 from 2.0.5 and the file _Html.php_ did not appear too.
For testing sake, I did a totally fresh Composer installation as per http://www.yiiframework.com/doc-2.0/guide-start-installation.html. Nope, _Html.php_ did not appear too.

I'm very tempted to just download https://raw.githubusercontent.com/yiisoft/yii2-bootstrap/master/Html.php and paste into the yii2-bootstrap directory.
Kindly advise me. Thank you for your time! :heart_eyes:

**Comment by dynasource** [comment]
1) delete the /vendor/yiisoft directories
2) delete your composer cache

this will solve it

**Comment by look4raymond** [comment]
This is what I did:
<code>rm -rf yiisoft</code>
<code>sudo composer self-update</code>
<code>sudo composer clear-cache</code>
<code>cd myprojectdirectory</code>
<code>composer update</code>

![screen shot 2015-08-12 at pm 03 40 55](https://cloud.githubusercontent.com/assets/11458029/9218870/e86046a4-4108-11e5-9b01-1d7ceeb9fc9a.png)
_Html.php_ still did not appear.

I actually dig into _~/.composer/cache/files/yiisoft/yii2-bootstrap/1b6b1e61cf91c3cdd517d6a7e71d30bb212e4af0.zip_ and extract the zip file and couldn't find the _Html.php_ too.

Any solution? Thanks for your time. :cry:

**Comment by look4raymond** [comment]
I digged into https://github.com/yiisoft/yii2-bootstrap/releases and downloaded 2.0.4.zip.
___Html.php_ was not inside__!

**Comment by dynasource** [comment]
true, I just wanted to mention it ;)

**Comment by samdark** [comment]
Yes. It's not released yet.
