### ISSUE TITLE
Ability to ActiveRecord method getErrors() return errors with input form id's as keys

### ISSUE THREAD

**Issue by Akdmeh** [yiisoft/yii2#9383]
Several days ago you added into yii 2.0.6 ability to show user-defined error messages in yiiActiveForm via JS:
https://github.com/yiisoft/yii2/commit/11de09bf8b5b2186d75f8cddfb530f4511674f5d
It's great feature and I waited for it to use without dirty hacks.
But new JS method updateMessages() takes only input id's, which usually generated like [modelname-attributename] via Html::getInputId($model, $attribute).
Maybe you should create new method in ActiveRecord, which will be return errors with keys, generated equally to that in input field?
Example:

Somewhere in controller:
```php
if(!$model->validate() && Yii::$app->request->isAjax){
Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
return $model_in->getErrorsWithInputIds();
}
```
Where **getErrorsWithInputIds** is hypothetical new method.

Then somewhere in view:
```javascript
success: function (response) {
            if(response.status=='success') {
                ...
            } else {
                $('#form').yiiActiveForm("updateMessages", response)
            }
        }
```

For now I must use some "hack":
```php
if(!$model->validate() && Yii::$app->request->isAjax){
Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
$errors=$model->getErrors();
$new_error_array=[];
foreach($errors as $k=>$v){
    $new_error_array[\yii\helpers\Html::getInputId($model, $k)]=$v;
}
return $new_error_array;
}
```
It's not a magical pill - it will creates problems if you, for example, redefined id attribute in Html::activeInput. That's why my examples isn't solution to all problems.

So, what you think about it, or I just don't see elephant in the living room and the better way exists?..

P.S. Traditional for all ex-USSR user excuses for poor language

**Comment by cebe** [comment]
why don't you use native ajax validation for this?

**Comment by Akdmeh** [comment]
In highloaded project even between ajax-validation and actual submit request there can be error.
In my case, even after validating money-balance some errors can raise (for that time balance have been change), and I don't invented any better solution but return error again.
So, maybe I don't understand ajax-validation and it's solve my problem by returning error even when submit-request was sent?

**Comment by cebe** [comment]
Normal validation of submit request has nothing to do with ajax. Seems I am missing something from what you are trying to do. How are you submitting the form?

**Comment by Akdmeh** [comment]
Sorry, now I understand. I forget about ActiveForm::validate.
Stupid misunderstand.
Maybe it's time to sleep for me.
My regrets.
