### ISSUE TITLE
AssetBundle fixed output directory?

### ISSUE THREAD

**Issue by e-frank** [yiisoft/yii2#9387]
I have some custom extensions, but i cannot set fixed deployment paths for my assets.
The reason i want to do this are some javascripts using ***UMD and requirejs***.

IMHO it's not worth the effort to have the main.js generated (already tried this, too many use cases).
And when handwriting, i can either create my ***own config from php*** (for getting asset-paths), or ***copy&paste*** js files to directories by name.

So, why this restriction:
> if $sourcePath is set, $basePath will be overwritten by yii\web\AssetManager when it publishes the asset files from $sourcePath.

I think it wouldn't break any existing logic, if you dropped this restriction.
In case both source- and base-Path are set, files could be copied from source to well defined base-path.

BTW: i think a closer entanglement with an AMD loader could simplify JS registering.
think of custom forms, with some parts dynamically loaded, respectively script ordering.

**Comment by samdark** [comment]
http://www.yiiframework.com/news/88/yii-2-0-6-is-released/, see "Assets". Does it solve the issue?

**Comment by e-frank** [comment]
no, it does not. still facing the problem, that i can't set the asset's output directory name. i think this is a mandatory requirement when using AMD loaders. I have some custom requirejs modules i want to share.

What about my ```$source-/$base-Path``` suggestion?

**Comment by SilverFire** [comment]
Use [AssetManager::hashCallback](http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#$hashCallback-detail) to avoid hash calculating and get your assets available at the static path.
