### ISSUE TITLE
updateAll where in

### ISSUE THREAD

**Issue by webwlsong** [yiisoft/yii2#9388]
$uid  =  array(1,2);
$user_id = implode(",",$uid);

$result = user::updateAll(['status'=>0],['user_id'=>[$user_id]])

This can't work.
reason this $user_id is string .
not int

**Comment by samdark** [comment]
Try passing array as is.

**Comment by webwlsong** [comment]
$result = user::updateAll(['status'=>0],['user_id'=>$uid]);

TKS, array   is  sucess
