### ISSUE TITLE
Why response have a blank row?

### ISSUE THREAD

**Issue by gavin-k** [yiisoft/yii2#9390]
Dear Developer,
   This is my controller action:
   
![qq 20150812164740](https://cloud.githubusercontent.com/assets/7688199/9220077/5be98de8-4112-11e5-8123-910e7e0a96e7.png)

This look like normally.But you open chrome browser,and open Developer tools.
You will see this.
![qq 20150812164831](https://cloud.githubusercontent.com/assets/7688199/9220100/8d8d6798-4112-11e5-986b-7963978ef5bb.png)

I do not know if this count is a bug.
Why this have a blank row?Why native PHP don't have this problems?

**Comment by dynasource** [comment]
this is not what I get when reproducing your actionTest, using dev-master of 2015-08-09
Have you already done a find on " <?php"?

**Comment by gavin-k** [comment]
My yii2 framework version is stable 2.0.6,PHP version is version 5.6.6.
And my developer tools is Phpstorm8.0.1.Platform is Windows10 or Windows8.1
Yes I have do that.
You just put it in SiteController. open browser ,type url: localhost/index.php?r=site/test

**Comment by gavin-k** [comment]
This is my native PHP function:
![qq 20150812173145](https://cloud.githubusercontent.com/assets/7688199/9220851/1bc94982-4118-11e5-974b-f6c2a1112ec2.png)

And the result is there,
![qq 20150812173051](https://cloud.githubusercontent.com/assets/7688199/9220861/37821e56-4118-11e5-9d1b-34d543f06d01.png)

I'm sorry,I know a little english.

**Comment by dynasource** [comment]
you should post your code in github, easier for us to reuse.

**Comment by dynasource** [comment]
I cannot reproduce. Steps taken:
* download 2.0.6 https://github.com/yiisoft/yii2/releases/download/2.0.6/yii-basic-app-2.0.6.tgz
* put in SiteController:
```php
    public function actionTest()
    {
        return 'test';
    }
```
* preview is perfectly fine

So something has gone wrong in your app. I would suggest to reproduce my steps and sort it out from there yourself.

**Comment by gavin-k** [comment]
Yes,you are right.
My project template based on Krajee practical-a template.
I dont know why my project have this problems.
Thank you!
