### ISSUE TITLE
load js file while using renderAjax

### ISSUE THREAD

**Issue by gauravparashar12** [yiisoft/yii2#9393]
I want to load a JS file, My content is loading using renderAjax method.

I have tried registerJsFile method but, it is not working as i am expecting. It loads that JS file when the full page reloads or rendered.

But, In my case i am loading a partial template and the same is not working. Please help, Thanks a lot for giving time to my query.

**Comment by dynasource** [comment]
is this JS file loaded in the content requested by Ajax?

**Comment by gauravparashar12** [comment]
@dynasource  Yes

**Comment by dynasource** [comment]
this is an JS thing. Its not supported by Yii2 but it is in fact possible. Tip: use the getScript functions of jquery or prototype. I have an implementation with prototype working. 

Reference: http://stackoverflow.com/questions/11803215/how-to-include-multiple-js-files-using-jquery-getscript-method
