### ISSUE TITLE
How to disable debugtoolbar

### ISSUE THREAD

**Issue by train860** [yiisoft/yii2#9396]
I want to disable debug toolbar in my project.I have tried delete 'YII_DEBUG' in my index.php,but it's not work! 
can you help?
thank you!

**Comment by dynasource** [comment]
Did you know there is a guide for this?:
http://www.yiiframework.com/doc-2.0/guide-tool-debugger.html

**Comment by 2012mjm** [comment]
At the end "config/web.php" file
<pre><code>if (YII_ENV_DEV) { ... //debug toolbar
</code></pre>


"web/index.php" file
<pre><code>defined('YII_ENV') or define('YII_ENV', 'dev');</code></pre>

"BaseYii.php" file
<pre><code>/**
 * Whether the the application is running in development environment
 */
defined('YII_ENV_DEV') or define('YII_ENV_DEV', YII_ENV === 'dev');
</code></pre>

if (YII_ENV === 'dev') ----> YII_ENV_DEV = true

The default value of "YII_ENV" is equal "prod"
// 'prod' (production), 'dev' (development), 'test', 'staging', etc

*change value of "YII_ENV" to "prod" at "web/index.php" file*

**Comment by train860** [comment]
@dynasource thank you!

**Comment by arian-askari** [comment]
@2012mjm Thanks for explanations, my friend.
