### ISSUE TITLE
[help wanted] How can i get the asset url of one assetbunle manually

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/yii2#9399]
For example:

I want to get the the full url of `yii.js`  in `YiiAsset`.

It should be `http://www.test.com/assets/123dasda/yii.js`

How can i reach this?

**Comment by dynasource** [comment]
do a print_r on the Yii::$app->view and you will will see all the info you need. 

Yii::$app->assetBundles['yii\web\YiiAsset']->basePath

Isnt it there yet? That the Yii Asset is not yet registered (when you have not yet registered a Asset depending on Yii)

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for issue reports.

**Comment by lichunqiang** [comment]
@dynasource 

I dump the `$this` in the view file, but the assetBundles is empty array,

@samdark 

ok,

**Comment by dynasource** [comment]
See my post
> Isnt it there yet? That the Yii Asset is not yet registered (when you have not yet registered a Asset depending on Yii)

You should do it AFTER you have registered an Asset Bundle

**Comment by lichunqiang** [comment]
@dynasource 

Thanks
