### ISSUE TITLE
Add catchAll support to yii\console\Application

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#9404]
I suggest to add `yii\web\Application::$catchAll` functionality to `yii\console\Application`, so we can use this option to turn off console controllers while maintenance.
For example, if you have backend, frontend and console applications, you can turn on `catchAll` only for one of them (in app config) or for all at once by setting this option in common config (so console scripts in crontab will not try to update somethnig, when you are conducting maintenance).

**Comment by dynasource** [comment]
can we make decision on this feature. Can't this simply be done with an action filter.

**Comment by cebe** [comment]
could be added to console too, but that would also mean you can not use the ./yii command while doing maintainance, e.g. yii migrate/up will not work if all calls are redirected to another action...

**Comment by samdark** [comment]
I don't think it's a good idea because of what @cebe mentioned. Console isn't exposed to end users and to disable background services it's better to implement the check per command.
