### ISSUE TITLE
Yii Debugger Mail panel is not showing any Email messages.

### ISSUE THREAD

**Issue by look4raymond** [yiisoft/yii2#9405]
Using PHP 5.6.10 and Yii 2.0.6 on Snow Leopard, Chrome browser.

I did not change the mailer configuration at all as I want to view the emails _internally_:
<pre><code>'mailer' => [
    'class' => 'yii\swiftmailer\Mailer',
    // send all mails to a file by default. You have to set
    // 'useFileTransport' to false and configure a transport
    // for the mailer to send real emails.
    'useFileTransport' => true,
],</code></pre>

In one of my models, this is the code for sending emails:
<pre><code>Yii::$app->mailer
    ->compose('activation-email-html', ['accessToken' => $this->_user->accessToken])
    ->setFrom('something@somewhere.com')
    ->setTo($this->email)
    ->setSubject('Activate Your Student Account.')
    ->send();</code></pre>

As you can see from the screenshots below, there are emails stored in the _runtime/mail_ directory. However, they do not show in the Debugger Mail panel.
![screen shot 2015-08-13 at pm 08 26 38](https://cloud.githubusercontent.com/assets/11458029/9249899/97300e9c-41fb-11e5-8060-7803a3470a70.png)

![screen shot 2015-08-13 at pm 08 28 55](https://cloud.githubusercontent.com/assets/11458029/9249903/a2cf5cb2-41fb-11e5-8c16-2e3b934ab899.png)

Am I missing something? :worried:

**Comment by dynasource** [comment]
all those panels belong to the current request. I guess those 4 emails in your screenshot are not sent in the current request?

**Comment by samdark** [comment]
Try selecting previous requests.

**Comment by look4raymond** [comment]
That is how you do it???
Aargh, I'm such a noob. :sob: 

Thanks for your time!

**Comment by samdark** [comment]
You're welcome.
