### ISSUE TITLE
theme layout render strange

### ISSUE THREAD

**Issue by borgez** [yiisoft/yii2#9406]
have 
```
        'view' => [
            'theme' => [
                'basePath' => '@app/themes/ru',
                'baseUrl' => '@web/themes/ru',
                'pathMap' => [
                    '@app/views' => [
                        '@app/themes/en/views',
                        '@app/themes/ru/views',
                    ],
                    '@app/modules' => '@app/themes/classic/modules',
                    '@app/widgets' => '@app/themes/classic/widgets'
                ],
            ],
        ],
```
and different menu template
en/layouts/leftMenu.php
ru/layouts/leftMenu.php

in ru/layouts/main.php
```
<?= $this->render('leftMenu') ?>
```
**Expect** en/layouts/leftMenu.php **but** ru/layouts/leftMenu.php

**Comment by borgez** [comment]
but if ru/layouts/main.php move to app/views/
it work.

**Comment by samdark** [comment]
What's the app language?

**Comment by borgez** [comment]
ru.
it is not directly related to the language of the application.
Just on the English version planned other templates like original but other =).

**Comment by samdark** [comment]
I think it's related. Yii view component prefers `views/<language>/viewname.php` to `views/viewname.php` if language is set.

**Comment by borgez** [comment]
yii2 do that? i dont cnow

**Comment by samdark** [comment]
Yes, it does that. See http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#view-translation
