### ISSUE TITLE
Convert ActiveRecord attribute name from underscore to camelCase

### ISSUE THREAD

**Issue by zetamen** [yiisoft/yii2#9409]
Underscore naming convention is popular standard for table and column naming. Generated AR attributes use underscore naming convention too. It's contrary framework code style, contrary corporative code style.

To avoid mistakes, names conversion will work only for ActiveRecord attributes. Names conversion is very simple action does not affect performance. Conversion turn on by switcher, by default off.

**Comment by samdark** [comment]
It's not as simple as it seems. Especially when it comes to queries and the fact that you should use `field_name` in conditions and `fieldName` when accessing properties.

**Comment by zetamen** [comment]
Yes, therefore It only for attributes: insert, update, access to attributes.

**Comment by cebe** [comment]
we have discussed this before and it is confusing if attributes are named different in insert, update than in query.

see #6760, #7136

**Comment by zetamen** [comment]
It's not required feature. This will be useful someone.

**Comment by j3rrey** [comment]
Omg this is really annoying and kinda a deal breaker for us.... Why not just give an option to use camelCase ?
This greatly increases code consistency, Hundreds of devs wish for this feature and your reason to not do it is because it is "confusing"?

Thinking of switching to Laravel because of this or enhancing ur implementation.... 
Kinda disappointed

**Comment by samdark** [comment]
@j3rrey it's not as simple as it looks as I've already pointed out https://github.com/yiisoft/yii2/issues/9409#issuecomment-130868475.

If you have a plan for a complete solution which isn't too complex and solves the two-way mapping, it would be great.

**Comment by j3rrey** [comment]
I will give it a shot and come back later to this issue, and yes I've read all the issues and your answers

**Comment by samdark** [comment]
Looking forward to it.

**Comment by cebe** [comment]
> Thinking of switching to Laravel because of this or enhancing ur implementation....

I am not aware of laravel supporting this feature, can you point me to the docs or implementation?

**Comment by j3rrey** [comment]
Hey hey, so I don't have the time to enhance ur current implementation.... also ur comment about it's confusing kinda was a deal breaker to further use ur framework.
We will switch.
@cebe It's all here in the eloquent documentation https://laravel.com/docs/5.4/eloquent

**Comment by rob006** [comment]
> It's all here in the eloquent documentation https://laravel.com/docs/5.4/eloquent

Where do you see automatic conversion of attributes names in eloquent? Even in docs they use snake_case for attributes names:

```php
$user = App\User::find(1);

$firstName = $user->first_name;
```

**Comment by bizley** [comment]
I also can not find it. I'm not even sure if this is supported at all in current Laravel version, see some old tickets:

- https://github.com/laravel/framework/issues/316
- https://github.com/laravel/internals/issues/41

**Comment by Kolyunya** [comment]
It was implemented in Doctrine like ages ago.

**Comment by bizley** [comment]
Well yes, there is naming strategy there.

**Comment by j3rrey** [comment]
I'm sure it was somewhere in the documentation maybe a bit hidden.
What I've just found are packages that do provide it for Laravel.
Either way in this issue Taylor said he is fine with it not sure if he meant the created_at and updated_at attributes.

https://github.com/jarektkaczyk/eloquence/wiki/Mappable
https://github.com/jarektkaczyk/eloquence

Checking the code later today:
https://laravel.com/api/5.4/Illuminate/Database/Eloquent/Model.html
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Model.php

**Comment by Kolyunya** [comment]
@j3rrey this feature was deprecated in Laravel.

**Comment by zetamen** [comment]
This can be realized by gii generating. Add getters/setters in class body. 

```php
<?php foreach ($tableSchema->columns as $column): ?>
<?php
    $camelCaseName = Inflector::camelize($column->name);
    $variableName = Inflector::variablize($column->name); ?>
    /**
    * @return <?= $column->phpType . "\n"; ?>
    */
    public function get<?= $camelCaseName; ?>()
    {
        return $this->getAttribute('<?= $column->name; ?>');
    }

    /**
    * @param <?= $column->phpType . ' $' . $variableName. "\n"; ?>
    */
    public function set<?= $camelCaseName; ?>($<?= $variableName; ?>)
    {
        $this->setAttribute('<?= $column->name; ?>', $<?= $variableName; ?>);
    }
<?php endforeach; ?>
```

**Comment by sebathi** [comment]
@zetamen Also you can add 
`
@property $columnNameCamelCase
`
 at the class definition for autocomplete on IDEs

**Comment by xeoshow** [comment]
So camel naming is supported now? Thanks!~
