### ISSUE TITLE
Response->sendHeaders() patch to allow sending a Location header with a 202 status

### ISSUE THREAD

**Issue by nd4c** [yiisoft/yii2#9412]
The current sendHeaders method in the Response class does not handle a php bug.

The fix is very simple and the explanation is in the comments below:

    /**
     * Sends the response headers to the client
     */
    protected function sendHeaders()
    {
        if (headers_sent()) {
            return;
        }
        $statusCode = $this->getStatusCode();
        header("HTTP/{$this->version} $statusCode {$this->statusText}");
        if ($this->_headers) {
            $headers = $this->getHeaders();
            foreach ($headers as $name => $values) {
                $name = str_replace(' ', '-', ucwords(str_replace('-', ' ', $name)));
                // set replace for first occurrence of header but false afterwards to allow multiple
                $replace = true;
                foreach ($values as $value) {
                    header("$name: $value", $replace);
                    $replace = false;
                }
            }
        }
        
        /*
         * Patch to allow sending Location header with 202 status
         * 
         * If the Location header is set
         * And the status code is not 201 or 3xx
         * PHP will automatically set the status code to 302  
         * 
         * However, the status code 202 would also typically pass a Location header.
         * 
         * From: http://www.php.net/manual/en/function.header.php
         * 		...
         * 		The second special case is the "Location:" header. 
         * 		Not only does it send this header back to the browser, 
         * 		but it also returns a REDIRECT (302) status code to the browser 
         * 		unless the 201 or a 3xx status code has already been set.
         * 		...
         * 
         * To resolve this problem PHP does allow forcing the status:
         * 
         * From: http://www.php.net/manual/en/function.header.php
         * 		void header ( string $string [, bool $replace = true [, int $http_response_code ]] )
         * 		...
         * 		http_response_code
         * 			Forces the HTTP response code to the specified value. 
         * 			Note that this parameter only has an effect if the string is not empty.
         * 
         * So we need to force the status AFTER all the headers are sent.
         * 
         * However, we do NOT want to force it if it is not the 202 status.  
         * This is to allow for the default PHP behavior
         * 
         */
    	if ($statusCode == 202) {
			header("HTTP/{$this->version} $statusCode {$this->statusText}", true, $statusCode);
		}
                
        $this->sendCookies();
    }

**Comment by samdark** [comment]
Which PHP bug?

**Comment by nd4c** [comment]
Sorry, that was an opinion.  Actually I'm planning on submitting this to the PHP group as a bug.

However, I do believe it's an actual bug.  The PHP documentation mentions the following:

Quote:
(from http://php.net/manual/en/function.header.php)

The second special case is the "Location:" header. Not only does it send this header back to the browser, but it also returns a REDIRECT (302) status code to the browser unless the 201 or a 3xx status code has already been set.

Endquote

This works as mentioned.  The bug is that the http status 202 is also used with a Location header, but php will convert the 202 to a 302 unless you force it.  I would consider that a bug, since the auto-conversion for the Location header simply does not work as it should.

The 202 is used for asynchronous RESTful operations:

Quote:
(from: http://restcookbook.com/Resources/asynchroneous-operations/)

Instead of creating the actual resources, create a temporary one. Instead of returning a 201 (Created) HTTP response, you can then issue at 202 (Accepted) response code. This informs the client that the request has been accepted and understood by the server, but the resource is not (yet) created. Send the temporary resource inside the Location header.

Request:
POST /blogs HTTP/1.1
<xml>
    blogdata
</xml>

Response:
HTTP/1.1 202 Accepted
Location: /queue/12345

This location can store information about the status of the actual resource: an ETA on when it will be created, what is currently being done or processed.

Endquote

I hope that helps.

At any rate the only way to use a 202 with a Location header from the Yii 2.0 framework is to rewrite the Response->sendHeaders method.

**Comment by nd4c** [comment]
@samdark 

After some more research, it appears that the use of the Location header for a 202 response is non-standard.  There is nothing in any RFCs that I could find on the subject that would suggest using a Location header for a 202 response.  On the other hand, none of them, in any way, suggest that it should not be used. There are several forum replies and the "http://restcookbook.com/" recommends it, but I don't at this time think this is a bug.  Sorry for any time wasted or headaches about this.  

That said, it would be nice to be able to use a Location header with a 202 response.  The current sendHeaders method does not allow for that.  I would suggest having some way to 'force' the status code for a response, possibly a property of the Yii::$app->response instance.

**Comment by nd4c** [comment]
By the way.  The current bug on PHP is: #70273.

https://bugs.php.net/bug.php?id=70273

I now think that it is a valid PHP bug.  However, for the Yii 2.0 Response class, I think it would be helpful, as I mentioned earlier, to have some way to 'force' the status code.  Either a boolean property like "isForcedStatusCode"  or an alternative status code property, "forcedStatusCode" that can be null, false or a force status.

**Comment by nd4c** [comment]
oh,...
And because of the PHP bug, any forced Status Code would have to be sent last.  Sort of like in the solution mentioned in the first post.

**Comment by kidol** [comment]
Why is it bad to always force status code? Just to protect user in case he does stupid stuff like

```php
return $this->redirect("http://example.com", 200);
```

?

**Comment by nd4c** [comment]
@kidol 

Good question.  I guess it's more a matter of whether the Yii framework wants to support the 'magic' side-effect of the PHP header() function.

Since 'magic' side-effects are typically frowned upon, I would recommend that the Yii response class not support it, and to always send the status code last as a forced status code to the PHP header() function.

You would not have to pass the status code to a redirect() method, since a redirect, by definition, has a status code or 302.  I don't think the current response class is a problem for a normal website.

I imagine this issue applies mainly to a site where you want to have a little more control over the headers.  I ran into this problem with a REST api that I have set up as stub for an online web service.  I needed to pass back a 202 and a Location header for any post to the api.  And PHP was 'magically' converting the 202 to a 302.  I had to rewrite the Yii reponse class to get around PHP.

**Comment by kidol** [comment]
@nd4c Yes I understand, I was just referring to your code proposal, asking myself whether there is any need to NOT force it.

Looking at symfony, they always force it. However, they also throw exception in case of Location-redirect and a non-valid redirect code (202 is considered invalid).

I guess Yii could just always force status code... If developer wants to use non-valid code which isn't covered by any RFC, then it's his choice. Also if he uses invalid code by mistake, he probably will get no redirect on the client side anyway, so he will figure out.

Also, the current logic already sets status code last. (`sendHeaders()` is called after `redirect()`).

**Comment by nd4c** [comment]
@kidol 

I might not be clear enough.  The Yii response sendHeaders() method will always set the Status Code and any headers applied to the response instance.  Which could be interpreted as being 'forced' but what I'm referring to is the way the PHP header() function handles the status code. 

By default if the Location header is sent to the PHP header() function is will 'magically' set the status code to 302 (except for certain status codes.)  You can supposedly 'force' a status code by sending it as the third parameter.  

But the current header() function is buggy as far as I'm concerned.  And the Yii response sendHeaders() method does not allow for the bug.  So when I say that the status code must be set last I'm referring inside the sendHeaders() method itself.  It's currently sending the status code header first and then any other headers.  I'm recommending sending it last and passing in the status code as the third parameter.  Thus 'forcing' PHP to set the status code to the Yii status code and not using any of the buggy PHP 'magic'.

**Comment by kidol** [comment]
I thought the important thing is that the Location-header is send BEFORE status code? I doubt any other header will reset status code? Did you test this? In you php bug you only test with Location-header.

As I said, currently the Location-header is send BEFORE status code. All what's missing as far as I can tell is to force status code with 3rd parameter.

**Comment by nd4c** [comment]
You are right about the Location-header needing to be sent before the status code.  And, yes, as far as the PHP documentation states (http://php.net/manual/en/function.header.php), only the Location-header magically changes the status code.  And the current solution is to send the status Code after the location header and passing the status code in as the third parameter to force it.

However, the Yii response class does not send the location header first nor does it ever send the status code as the third parameter.  When you call the response redirect method is will only 'save' the location header.  The sendHeaders method is where it is actually sent.  And it is sent after the status code.

That's why the sendHeaders method needs to be fixed. (IMO)  My suggestion was to have another property to control the forcing of the status code.  You point, however, sound valid.  It might just make sense to always force it.  I'm just not sure of any other possible consequences of doing that, so I think it might take some more research.

**Comment by kidol** [comment]
@nd4c 
Ah yes you are right, should've looked more carefully about headers...

Since Yii already tries to set a specific status code, why rely on some magic that changes it for whatever reason? I can see no problem with always forcing it at the moment.

Well let's see if someone else has something to say.

**Comment by nd4c** [comment]
The latest on the PHP bug report (https://bugs.php.net/bug.php?id=70273) is that it is not considered a bug.  Backward Compatibility is a big issue.  Also they consider automatically changing the status code to 302 when a Location header is set, to be a "generic use case."  So, as it stands, the PHP header() function will not be changing.

That leaves the fix up to the Yii framework itself.

I currently see two different ways to resolve it, both of which are extremely simple to implement.

The first (easiest) is to simply set the status code header last and to send in the status code as the third parameter to force it.

The caveat to this would be that if there are any programmers depending on the current PHP header() redirect functionality, it would no longer work.  They would now be responsible to set the status code to 302 for any redirect.  (Which, actually, seems to make more sense, since if the program is going to set a redirect by passing in a Location header, how could it not know to also send in the 302 status code.)  That said, the default header() functionality may be need to be considered.

The second solution (not quite as easy) is to add another property the response class that can optionally store a forced status code.  If it is set, then to set the status code header last and pass in the forced status code as the third parameter.  Not much harder and it correlates with the current PHP header() behavior.  It is also backward compatible with any code that might have depended on the PHP header() behavior.

**Comment by kidol** [comment]
@nd4c Currently, even if you do
```php
header("Location: http://example.com/", true, 302);
return;
```
in controller, Yii will overwrite the status code with 200 in `sendHeaders()` method, so it doesn't change anything. For `redirect()` method, the default is 302, so it doesn't change anything either.

With fix you can now do

```php
return $this->redirect('http://example.com/', 202);
```
or
```php
Yii::$app->response->headers->add("Location", "http://example.com");
Yii::$app->response->statusCode = 202;
```

Let me know if you have any doubts, or better wording for changelog.

**Comment by nd4c** [comment]
@kidol 

Looks good!  I believe that would be perfect.  The `redirect` will work like it always has, no surprises. But it will also allow for additional control if desired.  And the `Yii::$app->response` handling looks clean.  

I'm assuming that the order of calling `headers->add()` and setting `statusCode` shouldn't matter?  ie: 

```php
Yii::$app->response->statusCode = 202;
Yii::$app->response->headers->add("Location", "http://example.com");
 ```
Would that work the same?  Whether it works the same or not, is not really a problem, but I think it should be noted.

Thanks for all the help with this!  Nice!

**Comment by kidol** [comment]
@nd4c Yes works the same. Basically you just modify two properties which will then get read at `sendHeaders()`. Also the two properties do not modify each other.

**Comment by nd4c** [comment]
@kidol Nice!  Again, Thanks!

**Comment by cebe** [comment]
Merged the fix, thanks for detailed evaluation of the issue!
