### ISSUE TITLE
does yii\mongo\query surpport explain and hint method ?

### ISSUE THREAD

**Issue by monochrome-yeh** [yiisoft/yii2#9413]
native method
http://docs.mongodb.org/manual/reference/operator/meta/explain/
http://docs.mongodb.org/manual/reference/operator/meta/hint/

how can i use ActiveRecord or ActiveQuery for these method?

**Comment by webdevsega** [comment]
@monochrome-yeh I added explain method in PR yiisoft/yii2-mongodb#39
