### ISSUE TITLE
ActiveRecord updateCounters fails when target field is Null

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2#9419]
Hello,

It seems that updateCounters fails when the target field is null.

To reproduce, create a counter field like 'view_counter' in any table, then try to update field when form is viewed with code like this;

public function actionView($id)
{
    $model = $this->findModel($id);
    $model->updateCounters(['view_count' => 1]);

    return $this->render('view', [
        'model' => $model,
    ]);
}

No update occurs and updateCounters returns false.

My theory is that Yii attempts UPDATE post SET view_count = view_count + 1 WHERE id = 100 which evaluates as SET view_count = Null + 1 WHERE id = 100 thus failing

Not sure if this requires a fix or clearer error message but maybe updating AR documentation with a note suggesting initializing counter fields to zero before any call to updateCounters will suffice?

Regards,

Adam

**Comment by samdark** [comment]
Closed since current behavior is valid. See comments in a pull request.
