### ISSUE TITLE
model rules - seems problem with massage in string validator

### ISSUE THREAD

**Issue by Gl00mY-ZeiZ** [yiisoft/yii2#9421]
In rules:
```
[['password', 'email'], 'string', 'length' => [6, 255], 'message' => 'Too short or too long'],
```
I had std "Password should contain at least 6 characters." but not my own message.

**Comment by cebe** [comment]
there are different messages for different cases. http://www.yiiframework.com/doc-2.0/yii-validators-stringvalidator.html#$tooLong-detail

**Comment by Gl00mY-ZeiZ** [comment]
My fault! Sorry.
