### ISSUE TITLE
load assets on cdn server 

### ISSUE THREAD

**Issue by engmmrj** [yiisoft/yii2#9423]
can i load asstes files on cdn server ?
http://site.com/web/assets/7b3a3c7b/yii.gridView.js

change to 
http://cdn.site.com/web/assets/7b3a3c7b/yii.gridView.js

**Comment by samdark** [comment]
Yes, you can. Please use forums for questions.

**Comment by engmmrj** [comment]
i asked in yii forums but no one answer correct.
http://www.yiiframework.com/forum/index.php/topic/66462-how-can-in-the-yii2-use-cdn-server/
