### ISSUE TITLE
DI Reflectionexception php 7.0.0b

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9424]
Php7 seems to have a new way of showing ReflectionExceptions. Its not very informative. I would suggest to give more support about the error, because you have to investigate whats going on.

Minor thing, but useful. Monday Ill do a PR.

![screenshot 2](https://cloud.githubusercontent.com/assets/125726/9287889/20ef278a-432d-11e5-9edf-0a8732f339d1.png)

**Comment by cebe** [comment]
should better be reported to PHP so that they adjust the error message. PHP7 is not stable yet so they can fix it without the need for yii to create a workaround.

**Comment by dynasource** [comment]
Done. Thx https://bugs.php.net/bug.php?id=70282
