### ISSUE TITLE
ActiveQuery::exists() should generate SELECT EXISTS()

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#9425]
ActiveQuery::exists() method should generate a much more efficient and to the point ISO SQL standard `SELECT EXISTS()` query instead of the one it generates now (without even adding a LIMIT 1).

**Comment by arogachev** [comment]
1) Please provide reference to standard where it's pointed.
2) Could you provide some examples?
3) What if condition is empty?

**Comment by PowerGamer1** [comment]
1) You may purchase a copy of the standard at iso.org otherwise google is your friend.
2) `SELECT EXISTS(SELECT * FROM user WHERE is_enabled=0)`
3) You mean like this: `SELECT EXISTS(SELECT * FROM user)` ? It would work.

**Comment by arogachev** [comment]
Thanks, it's clear now.

**Comment by PowerGamer1** [comment]
Fixed issues with pull request, it is now ready: https://github.com/yiisoft/yii2/pull/11363.

**Comment by PowerGamer1** [comment]
Cubrid, MSSQL and Oracle do not support SQL92 standard form of  `SELECT EXISTS()` but they do support their own nearly identical forms of it. Implemented them in https://github.com/yiisoft/yii2/issues/11369.
