### ISSUE TITLE
uploadedfile in yii2 cannot upload .xls file

### ISSUE THREAD

**Issue by bubifengyun** [yiisoft/yii2#9433]
i know the produce of uploading file.
the rules as follows
```php
public function rules()
    {
        return [
	    ['file', 'required'],
            // file has to be a valid excel file
            [['file'], 'file',  'extensions' => 'et, xls, xlsx', 'maxSize'=>1024*1024*20],
        ];
    }
```
however, when i upload xxx.xlsx file, it can be saved successfully. xls can not.
## another problem. 
xls file can be validated by client browser, but when i click confirm, it will pops error: file format must be "et, xls, xlsx".

**Comment by mikehaertl** [comment]
You can try to disable the Extension-by-MIME-type check: `'checkExtensionByMimeType'=>false`. It's on by default, and I found, that it sometimes does not work very well.

**Comment by lynicidn** [comment]
try define mime types for validate http://stackoverflow.com/questions/974079/setting-mime-type-for-excel-document

**Comment by mikehaertl** [comment]
> upd: 'checkExtensionByMimeType'=>false it unsafe

Care to explain that claim?

**Comment by dizews** [comment]
@mikehaertl because mime type validation of xls files return ```application/CDFV2-corrupt``` instead of ```application/x-ms-excel``` or simlar.

**Comment by mikehaertl** [comment]
@dizews I think, you misread my question and try to explain why it doesn't work.

My question was directed to @lynicidn as he claims that turning this off is a security risk. I tend to disagree.

**Comment by lynicidn** [comment]
@mikehaertl check extension it not needed validation - i can create js file and rename to *.xls and it be valid

**Comment by mikehaertl** [comment]
@lynicidn Right, then you have a js file with `.xls` extension. While this may lead to problems in some cases I wouldn't say, that it's a security problem in any situation.

**Comment by samdark** [comment]
Overall, there's nothing to fix. We can't improve accuracy of such detection and it's already in the guide.

**Comment by bubifengyun** [comment]
cancel $model->validate(), just OK. it can check in browser.
 but no matter what the file it is, it can be validated if its name like this "xxx.xls".
