### ISSUE TITLE
Formatter date issue

### ISSUE THREAD

**Issue by DawidMyslak** [yiisoft/yii2#9435]
I'm trying to use formatter class before I save my object to the database, base on samples provided here:
http://www.yiiframework.com/wiki/684/save-and-display-date-time-fields-in-different-formats-in-yii2/

Here is my code:
```php
Yii::$app->formatter->asDate('15/09/2014', 'dd/MM/yyyy');
```
or
```php
Yii::$app->formatter->asDate('15/09/2014', 'php:d/m/Y');
```

And the error I'm getting:
`'15/09/2014' is not a valid date time value: DateTime::__construct(): Failed to parse time string (15/09/2014) at position 0 (1): Unexpected character`

If I try to change day to be less or equal 12, then it will work:
```php
Yii::$app->formatter->asDate('09/09/2014', 'dd/MM/yyyy');
```
Looks like month and date are replaced somehow.

Any ideas?

**Comment by cebe** [comment]
when converting user input for storing it in the database you should use DateValidator instead of Formatter. "Tip 4" in that wiki link is wrong usage.

**Comment by DawidMyslak** [comment]
Thanks for that, will try it.
