### ISSUE TITLE
Could yii\db\pgsql\Schema::findSchemaNames be public?

### ISSUE THREAD

**Issue by pyd** [yiisoft/yii2#9439]
Hi,
I wish I could have access to this - protected - method. It's just a getter - returning data - that could be set public without risk - IMHO.

Thanks

**Comment by cebe** [comment]
why do you need it? please explain your use case.

**Comment by pyd** [comment]
Hi,
I'm dealing with a db that contains the same schema - same objects - with different names. In order to manage - create, remove - them I was looking for a way to get a list and found this method.

These schemas use a specific naming pattern so I ended up creating my own method - with a custom sql condition - to find them.

Anyway, it is a useful method for managing schemas.

Thanks again.

**Comment by samdark** [comment]
You can use `getSchemaNames()`.
