### ISSUE TITLE
New migration style (defaultValue('NULL')

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2#9445]
As far as I can see in new migration style, there is no ability to define `NULL` default.

* `defaultValue('NULL')` will create `DEFAULT 'NULL'` which is not right
* `defaultValue(null)` will ignore the specified null

**Comment by samdark** [comment]
Isn't it default?

**Comment by cebe** [comment]
its is the default if nothing it specified but still the method should cover that case correctly.

**Comment by cebe** [comment]
Oh, seems like the method covers the case already. All fine here.

> If no default value is declared explicitly, the default value is the null value. This usually makes sense because a null value can be considered to represent unknown data.
> http://www.postgresql.org/docs/current/static/ddl-default.html

>  If the column can take NULL as a value, the column is defined with an explicit DEFAULT NULL clause. 
> https://dev.mysql.com/doc/refman/5.0/en/data-type-defaults.html

**Comment by armpogart** [comment]
Sorry, I've looked through the php source code only and haven't checked what PostgreSQL does by default. Thanks.
