### ISSUE TITLE
error csrf and cookies deleted

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#9448]
i have a problem in this case
when you enter the first time, and you add a register-login in the "index" i get this error (Unable to verify the submitted data.)

only happen when the user is first time to enter or when delete the cookies

any have idea how can solve this or is a bug ?, i readed the documentation yii2 and i cant find this case...

i missed a lot clients because in the first enter on the site, the register display the error (Unable to verify the submitted data.)

this is the config.php frontend

```php
'components' => [
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
            'loginUrl' => ['user/login'],
            'identityCookie' => [
                'name' => '_frontendIdentity', // unique for frontend
                'httpOnly' => true,
                'path' => '/frontend' // correct path for frontend app.
            ],
            'authTimeout' => ($params['session_timeout'] != -1)? $params['session_timeout'] : 3600 * 24 * 30 //15 minutos afk
        ],
        'session' => [
            'name' => 'FRONTENDSESSION',
            'cookieParams' => [
                'path' => '/frontend',
            ],
        ],
        'request' => [
            'csrfParam' => '_frontendCSRF',
            'baseUrl' => $baseUrl,
            'csrfCookie' => [
                'httpOnly' => true,
                'path' => '/frontend',
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
    ],
```

and i used this documentation

https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-shared-hosting.md

**Comment by samdark** [comment]
Can you reproduce it with [basic application](https://github.com/yiisoft/yii2-app-basic) contact form? If yes, how exactly?

**Comment by spiritdead** [comment]
@samdark  i used advanced application because in this i have the user migration ready

**Comment by samdark** [comment]
I cannot reproduce it locally.

**Comment by spiritdead** [comment]
ok a moment i will try reproduce in a new installation advanced

**Comment by samdark** [comment]
Configure frontend only this time.

**Comment by spiritdead** [comment]
REPRODUCED !

**Comment by spiritdead** [comment]
@samdark  create the advanced,configure,migrate,etc, add this config in the main.php

```php
`'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
            'loginUrl' => ['user/login'],
            'identityCookie' => [
                'name' => '_frontendIdentity', // unique for frontend
                'httpOnly' => true,
                'path' => '/frontend' // correct path for frontend app.
            ],
            'authTimeout' => ($params['session_timeout'] != -1)? $params['session_timeout'] : 3600 * 24 * 30 //15 minutos afk
        ],
        'session' => [
            'name' => 'FRONTENDSESSION',
            'cookieParams' => [
                'path' => '/frontend',
            ],
        ],
        'request' => [
            'csrfParam' => '_frontendCSRF',
            'baseUrl' => $baseUrl,
            'csrfCookie' => [
                'httpOnly' => true,
                'path' => '/frontend',
            ],
        ],
```

enter in the url signup,delete all cookies, and try signup

automatic you get the error 400, cant validate CSRF because the _frontendCSRF not exist

**Comment by samdark** [comment]
Deleted !== wasn't created yet. CSRF is all about verifying there's correct token in the cookie so such behavior is expected. No token — no action.

**Comment by spiritdead** [comment]
@samdark  but how can solve this im trying find documentation for this case if i define the signup in the index when the user enter the first time and register get this error ?

**Comment by samdark** [comment]
1. You cannot emulate this by deleting a cookie.
2. I'm trying the same using clean advanced app and not getting any errors:
  - Register new user.
  - Go to contact form.
  - Submit it.

**Comment by spiritdead** [comment]
@samdark  i can show you in teamviewer or skype ?, you have separed the cookies by frontend/backend ?

```php
`'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
            'loginUrl' => ['site/login'],
            'identityCookie' => [
                'name' => '_frontendIdentity', // unique for frontend
                'httpOnly' => true,
                'path' => '/frontend' // correct path for frontend app.
            ],
        ],
        'session' => [
            'name' => 'FRONTENDSESSION',
            'cookieParams' => [
                'path' => '/frontend',
            ],
        ],
        'request' => [
            'csrfParam' => '_frontendCSRF',
            'csrfCookie' => [
                'httpOnly' => true,
                'path' => '/frontend',
            ],
        ],
```

im sure if i show you, you can see better this

**Comment by samdark** [comment]
I have totally separated frontend/backend on different hosts. Frontend is `http://yii2-af.dev/`, backend is `http://yii2-ab.dev/`. I don't have any extra configs, it's out of the box advanced project template.

**Comment by spiritdead** [comment]
i think is my error because i have redirections using .htaccess for hide the folder /web and redirect base-url to /frontend

that will give the error ?

**Comment by samdark** [comment]
I guess it could. Anyway, that's config issue, not code issue. Nothing to fix.

**Comment by spiritdead** [comment]
@samdark sorry for this i missed beginPage in the layout Sorry man!
