### ISSUE TITLE
namespace class loading not working with call_user_func method.

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#9453]
In my controller, model is loaded using 

```php
use backend\models\AdminUser;
```

My action method is as below:

```php
public function actionIndex()
{
 $class = 'AdminUser';
 $method = 'find';
		
 $arr = array($class, $method);
		
 $query = call_user_func($arr);
}
```

If I call find method as `AdminUser::find()` its working fine but it's not working as I have mentioned in above code. 

The error says class 'AdminUser' not found so looks like it is not respecting the class loaded using namespaces.

same code works if I provide my full namespace to class name like `backend\models\AdminUser` as a class name.

Let me know if any further information required from my end.

**Comment by dynasource** [comment]
This is not Yii, you are using wrong PHP code syntax.
Variables are not connected to any classes in the use statements.

You should always use full classes declarations, unless you are within the Namespace and then only without $, which will also be recognized by your IDE.
