### ISSUE TITLE
After column for migration command

### ISSUE THREAD

**Issue by hulyman** [yiisoft/yii2#9455]
In ColumnSchemaBuilder not enough method for set AFTER column command.

**Comment by bryglen** [comment]
please add a parameter such as `$this->string(255)->custom('UNSIGNED')->notNull()->custom('AFTER status')` so it will generate by order `VARCHAR(255) UNSIGNED NOT NULL AFTER status`

**Comment by arogachev** [comment]
@samdark, @cebe What do you think about it? I think it's better to create separate MysqlColumnSchemaBuilder as it's done with Oracle and add custom `after()` method. Also I thinks it will be useful to have possibility to use `FIRST` statement for inserting column to the very beginning, before second column. Or define `custom()` method for insertion custom code?

**Comment by samdark** [comment]
I don't like the idea of having different API for different database types.

**Comment by bryglen** [comment]
we can create `custom()` sort of like that to handle different methods for each database

**Comment by arogachev** [comment]
Yes, creating additional property and method for each statement is indeed not good idea.

**Comment by Faryshta** [comment]
wasn't this closed by #10494 ?

**Comment by samdark** [comment]
Yes, it was. Thanks!
