### ISSUE TITLE
add noscript tag support for registerJs()

### ISSUE THREAD

**Issue by Renkas** [yiisoft/yii2#9459]
Usecase:
I would like to dynamically add FB/Google etc tracking pixels to pages with registerJs(). There's no problem adding the JS part. But for the full compatibility I would really like to also include `<noscript>` tag with generated `<script>`

**Comment by klimov-paul** [comment]
`registerJs` provides ability to specify 'position' of the script, which includes `jQuery(window).load()` and `jQuery(document).ready()`. Such positions have no place for 'noscript' tag.
In general 'noscript' should be placed manually at the desired place as its content is a HTML code and can not be bound to the particular position by default.

You may pass necessary 'noscript' content to the layout via `View::params`.
