### ISSUE TITLE
ActiveForm adds extra parameters to URL

### ISSUE THREAD

**Issue by m00nk** [yiisoft/yii2#9460]
The code:
```php
$model = new MyModel();
$form = ActiveForm::begin([
	'method' => 'get', // IMPORTANT!!!
]);
echo $form->field($model, 'text');
...
ActiveForm::end();
```

The URL of the page is 'http://site.dev/page'.

When I will click "Submit' the page will be reloaded and the URL will be changed to:
http://site.dev/page?MyModel%5Btext%5D=123 it is ok. 

The model "catches" the new values and appears on the page. But if I will click "Submit" again the URL will have "the twins" of all parameters:
http://site.dev/page?MyModel%5Btext%5D=123&MyModel%5Btext%5D=123

After the third click, every parameter will be added to URL three times, etc.

form

**Comment by samdark** [comment]
Specify `'action' => ['controller/action'],` and it won't happen. Leaving action empty means "use current URL".
