### ISSUE TITLE
response redirect doesn't go to url

### ISSUE THREAD

**Issue by JalalJaberi** [yiisoft/yii2#9463]
Hi
I made a basic app with Yii2 and then uploaded it on a webhost. Then to remove web folder from address, move everything one level upper. Now in public_html I have everything has been in web folder before and other folders are outside of public_html.

My problem is redirect doesn't work totally. Even in such a simple situation:

    <?php
    namespace app\modules\newsletter\controllers;
    use Yii;
    use yii\web\Controller;
    use yii\web\NotFoundHttpException;

    class TestController extends Controller
    {
        public function actionIndex()
        {
            echo 'Hi';
            return $this->redirect(I TESTED MANY URLS);
        }
    }

I can see 'Hi' but redirect doesn't occur. I checked the

    Yii::$app->response->i_sent
and that is true after redirect!

**Comment by derekisbusy** [comment]
The echo statement is probably forcing the headers to be sent before the redirect and therefore the redirect doesn't work. You need to keep all your content within view files. So you would move the echo statement to a view file and either show that view or redirect. You cannot echo out content and redirect in the same request...

```php
<?php
namespace app\modules\newsletter\controllers;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class TestController extends Controller
{
    public function actionIndex()
    {
        if($statement)
             return $this->render('view'); // echo 'Hi'; would be within the view file
        else
             return $this->redirect('/your/url');
    }
}

```

**Comment by alchimik** [comment]
http://php.net/manual/en/function.header.php
> Remember that header() must be called before any actual output is sent, either by normal HTML tags, blank lines in a file, or from PHP. It is a very common error to read code with include, or require, functions, or another file access function, and have spaces or empty lines that are output before header() is called. The same problem exists when using a single PHP/HTML file.
