### ISSUE TITLE
logger and delimiter

### ISSUE THREAD

**Issue by dizews** [yiisoft/yii2#9464]
Hello.

Sometimes we need to analyze logs. but if we have multiline logs it is painful for auto analyzer. It will be useful to add ```Target::delimiter ``` params.

**Comment by samdark** [comment]
What's `Target::delimiter`? How it works? Any examples?

**Comment by nineinchnick** [comment]
@dizews then consider logging to the database or specialized logging software like Logstash

**Comment by dizews** [comment]
@samdark it usually useful for logs to file and post treatment

**Comment by samdark** [comment]
@dizews I have no idea what do you mean by this "delimeter" at all.

**Comment by dizews** [comment]
delimiter should be help us to split two or more packets of log

**Comment by samdark** [comment]
What is this delimiter?

**Comment by dizews** [comment]
any sequence of chars which does not be exist in body of log message.
for example: "----------" or similar.

**Comment by klimov-paul** [comment]
This does not belong to the core. You should create your own log target for this.
Since each log entry is plain string there is no garantee chosen delimiter will not appear as a part of log message.

**Comment by klimov-paul** [comment]
Note: the correct term for the feature is "boundary"

**Comment by samdark** [comment]
Agree that it's not a good idea to have it in the code. Btw., check rollbar.com and getsentry.com.
