### ISSUE TITLE
[ENH]  migrate/create generate migration code automatically

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#9465]
is it also possible to generate migration code automatically? that would save a lot of time.

For example : 
 
```
yii migrate/create CreatePost --fields=title:string(10):notNull,body:text:notNull
```

Generate

```php
<?php

use yii\db\Schema;
use yii\db\Migration;

class m150811_220037_createPost extends Migration
{
    public function up()
    {
        $this->createTable('post', [
        	'title' => $this->string(10)->notNull(),
        	'body' => $this->text()->notNull(),
        ]);
    }

    public function down()
    {
        $this->dropTable('post');
    }
}
```

For more details or ideas http://guides.rubyonrails.org/active_record_migrations.html#creating-a-migration

**Comment by klimov-paul** [comment]
I am unsure we should pursuit Ruby with this issue.
It requires creating another DSL for the migration creation. While in Ruby it is a common practice, in PHP - it is not.

Another concern: code generation is covered by Gii module in Yii, it may be confusing to have it in other place.

**Comment by klimov-paul** [comment]
Relates to #1692

**Comment by pana1990** [comment]
>It requires creating another DSL for the migration creation. While in Ruby it is a common practice, in PHP - it is not

Laravel generators use this feature too, you see for more details https://github.com/JeffreyWay/Laravel-4-Generators#migrations

> Another concern: code generation is covered by Gii module in Yii, it may be confusing to have it in other place.

I am agree, i can try send pull request in yii2-gii extension.

**Comment by pana1990** [comment]
@samdark @klimov-paul what do you think to about it?

**Comment by samdark** [comment]
That's kinda controversial. From one point of view, we have Gii that generates code... and migration is code. From another point of view, we already have `yii migrate/create`.

Personally I'm in favor of having it into `migrate/create`.

**Comment by df2** [comment]
I'm working on a hosted migrations solution. Will probably end up open sourcing parts of it so others can contribute. Makes using migrations a breeze, SCM and team access built in. Send me a msg at chris@buckshotsoftware.com if you want early bird access </ad> ;-)

**Comment by gwelr** [comment]
Gii is web-based code generator, migrate/create is a console one. 
That makes the whole difference IMHO, and a difference that makes sense. 

If I can voice in on the initial request, I believe this should not be part of the core framework. It can be offered as an extention. Otherwise, you will end up creating a whole new syntax just for migration with a bunch of potential questions, some easy(how to specify indexes, primary keys, ...) to more complex ones (first that comes to my mind: What if I want to drop a table in my up() method?).
Just my 2 cents

**Comment by samdark** [comment]
@gwelr Gii isn't only web generator. It could be used from console as well.

**Comment by mdmunir** [comment]
https://github.com/deesoft/yii2-gii/tree/master/generators/migration
generate migration from existing database.

**Comment by dinhtrung** [comment]
I think we can easily achieve this by modify the default `@yii/views/migration.php` template a bit.

My suggestion is, using `--migrationTable=table,names,need,to,create` to let the developer choose which table the code should use.
 
Here is the template I use:

```[php]
/* @var $className string the new migration class name */
$controller = Yii::$app->controller;
$schema = Yii::$app->get($controller->db)->getSchema();
$tables = explode(",", Yii::$app->controller->migrationTable);
echo "<?php\n";
?>

use yii\db\Migration;
use yii\db\Schema;

class <?= $className ?> extends Migration
{
    /** Table option applied to all tables **/
    public $tableOption;
    /** @TODO: Table definitions goes here **/
    public function init(){
    	if ($this->db->driverName === 'mysql') {
    		$this->tableOption = 'CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE=InnoDB';
    	}
    }

    /** Upgrade database **/
    public function up()
    {
		/** Create one table
		$this->createTable('{{%table}}', [
			'id' => Schema::TYPE_PK,
			'title' => Schema::TYPE_STRING,
			'description' => Schema::TYPE_TEXT,
			'status' => Schema::TYPE_BOOLEAN,
		], $this->tableOption);
		*/
<?php foreach ($tables as $name): ?> <?php if ($def = $schema->getTableSchema($name)):?>
		/*** Table structure for `<?= $name ?>` ***/
		$this->createTable('{{%<?= $name ?>}}', [
<?php foreach ($def->columns as $col): ?>
			'<?= $col->name ?>' => '<?= $col->type ?>',
<?php endforeach; ?>
		], $this->tableOption);
		$this->addPrimaryKey('pk_<?= $name ?>', '{{%<?= $name ?>}}', '<?= implode(', ', $def->primaryKey) ?>');



<?php endif; ?> <?php endforeach; ?>

	}

    public function down()
    {
<?php foreach ($tables as $name): ?> <?php if ($def = $schema->getTableSchema($name)):?>
		$this->dropTable('{{%<?= $name?>}}');
<?php endif; ?> <?php endforeach; ?>
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
```

After use a `devDb` component to write code, I can create migration to apply to main `db` with this command:

```
./yii migrate/create --migrationTable=table1,table2,table3 --db=devDb --migrationPath=@module/dir/migrations create_table
```

If I omit the `--migrationTable` params then it will result in the default migration template of Yii.

**Comment by pana1990** [comment]
@dinhtrung can you check my pr https://github.com/yiisoft/yii2/pull/9490? what do you think about it?

it support : 

 - create/drop table with schema
 - add/remove column 
 - create juntion tables

**Comment by dinhtrung** [comment]
@pana1990 I think we are approach the same target but with different path. 

Your solution are full features, and my suggestion is only a kickstart and need to adjust by developer to write extra code (foreign keys, constrain, fine tune the parameter etc...).

Can we merge? I think my template is simple and support multiple table definition from dev database, which is quite convenient and stick with framework GII approach (design the DB first, GII, write custom code, then write migration) while yours can do more fine tuning on the DB (add/remove column, fk, etc).

Anyway, `migrate/create` already got `--templatePath` param, so it's quite easy to write and select a migration template to use.

**Comment by pana1990** [comment]
My target is different.

My worflow with gii it would be the following : 

1º I generate my migration with generator, for example i want to create post table : 
`yii migrate/creation create_post --fields=title:string(20):notNull,body:text`
 this generate : 
```php
$this->createTable('post', [
  'id' => $this->primaryKey(),
  'title' => $this->string(20)->notNull(),
  'body' => $this->text()
]);
```
2º i generate model with gii
3º i crud with gii
4º i custom controllers and views (Optional)

This workflow is usually in rails and laravel, i like it.
