### ISSUE TITLE
Yii2 Restfull strange behaviour

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#9468]
Trying to create API app (based on RESTFull services) using Yii2 Advanced template. Created subdomain api.domain.com for this purpose. 

The directory structure looks like this: 

[![enter image description here][1]][1]

The problem is, when I try to send GET request to `api.domain.com/users` getting following response:

    {
      "name": "Not Found",
      "message": "Page not found.",
      "code": 0,
      "status": 404,
      "type": "yii\web\NotFoundHttpException",
      "previous": {
        "name": "Invalid Route",
        "message": "Unable to resolve the request \"user/index\".",
        "code": 0,
        "type": "yii\base\InvalidRouteException"
      }
    }

Here is config file:

https://gist.github.com/d1930b6bf20e3d50fe63

Here is controller (which is located in Controllers folder):

https://gist.github.com/anonymous/180a7e791e879570e0f4

The question is, what is wrong?

  [1]: http://i.stack.imgur.com/TtXNu.png

**Comment by samdark** [comment]
Seems like framework is trying to access `user/index` route and can't find it. Check if there's namespace properly defined, check URL rules.

**Comment by turalsprofile** [comment]
@samdark Well, I placed all my config files and even controller's contents. Do you see any wrongs?

**Comment by samdark** [comment]
No. Try forums.
