### ISSUE TITLE
we got an error as "server has gone away"  on my console application with mysql database

### ISSUE THREAD

**Issue by JasLin** [yiisoft/yii2#9470]
same problem as this [question](http://stackoverflow.com/questions/26962120/yii2-mysql-server-has-gone-away)

set pdo:attr_persistent => true or set the wait_timeout to a bigger value could help to workaround it.

but i don't think it's good idea . etc. in some situations of unstable network environments, the connection may be forced to  close , it will cause this problem too.

so,may be we should try  to catch the exception  ,then open an new connection  ? and try several times if the problem still exist.

**Comment by yugenekr** [comment]
The same issue [was discussed for yii 1](http://www.yiiframework.com/forum/index.php/topic/20063-general-error-2006-mysql-server-has-gone-away/)

**Comment by SilverFire** [comment]
Already discussed here: https://github.com/yiisoft/yii2/issues/10168
