### ISSUE TITLE
Issue with ArrayDataProvider

### ISSUE THREAD

**Issue by RothLab1** [yiisoft/yii2#9471]
With the latest Development update: I get the following error:

PHP Fatal Error – yii\base\ErrorException

Class 'ArrayDataProvider' not found

I am using 	use yii\data\ArrayDataProvider; in the view

**Comment by samdark** [comment]
[It's still there](https://github.com/yiisoft/yii2/blob/master/framework/data/ArrayDataProvider.php). Nothing was changed about it.
