### ISSUE TITLE
[DOC] Creating nested RESTful resources routes

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#9474]
This is how that can be done:

``` php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['collaborators' => 'v1/collaborator'],
        'prefix' => 'v1/projects/<projectId:\d+>',
    ],
],
```

After that api will have next endpoints:
- /projects/1/collaborators
- /projects/1/collaborators/1

P.S. All issues which requests such feature after that can be complettely closed. Feature there from start.

**Comment by samdark** [comment]
Would be cool if you'll help with docs. Also it would be great if you'll point to these other issues.

**Comment by mdmunir** [comment]
I hope we can do this
```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'v1/<controller>' => '<controller>',
            'v2/<controller>' => 'v2/<controller>',
        ],
    ],
],
```

**Comment by creocoder** [comment]
@mdmunir Its not possible, this syntax is already taken.

**Comment by fernandezekiel** [comment]
this is most straightforward implementation we can have at the moment, we probably can create an example application utilizing nested routes

**Comment by fernandezekiel** [comment]
the application will have to demonstrate not just query adjustment based on the nested URL but also modification of the model to be created on something like:|
```
POST /projects/1/collaborators
``

**Comment by fernandezekiel** [comment]
here's my suggested example:
https://github.com/yiisoft/yii2/issues/7184#issuecomment-73396628

**Comment by tunecino** [comment]
@creocoder I think you mean : 
```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['collaborators' => 'v1/collaborator'],
        'prefix' => 'projects/<projectId:\d+>',
    ],
],
```
instead of ```'prefix' => 'v1/projects/<projectId:\d+>'``` or am I wrong ?

One more think I'm not getting. If docs is saying : 
```
$prefix: The common prefix string shared by all patterns.
```
Then how to do to get only ``` /projects``` or ``` /projects/1`` or a different not-related collection to preject ?

**Comment by tunecino** [comment]
mmm I finally understood what you've been trying to do. I didn't know that we can chain rules :  
```php
'rules' => [
    [
        'class' => 'yii\rest\UrlRule', 
        'controller' => [
            'projects' => 'v1/project',
            'collaborators' => 'v1/collaborator'                        
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['collaborators' => 'v1/collaborator'],
        'prefix' => 'projects/<projectId:\d+>',
    ],
],
```
This will make all those working : 
```
/projects
/projects/1
/collaborators
/collaborators/1
/projects/1/collaborators/1
/projects/1/collaborators?a=b
```
where the last one will be converted by ```yii\rest\UrlRule::createUrl()``` method to something like 
 ```
collaborators?projectId=1&a=b&page=1
```

**Comment by tunecino** [comment]
Here is what I like about this approach : 

If you customize your Controller and make it accept params as suggested by @samdark here : https://github.com/yiisoft/yii2/issues/4479#issuecomment-50285867 (*or also as suggested by most common REST api designs like [in this great article](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api)*),
 
then, if you make your indexAction use those params (*if matching your model safe attr*) to filter results within a custom `dataProvider` instance (*i'd rather use the ModelSearch class for it + adding Sort to it*),

then by setting `prefix` with the attribute used by ActiveRecord to retrieve the parent model related to it : 
```
'prefix' => 'projects/<project_id:\d+>',
```
This way, an url like `/projects/1/collaborators?organization=abc&sort=name` after being translated to `collaborators?project_id=1&organization=abc&sort=name&page=1` will be filtered by default using its `project_id` attribute which brings the resources that we've been looking for.

It needs more customization, as example when doing PUT or PATCH to `/projects/99/collaborators/1` a *ServerErrorHttpException* need to be thrown if projects#99 doesn't exist. But all can be handled in the Controller Side and I think this looks more like the Yii way to solve things.
