### ISSUE TITLE
DI injection via method signature

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#9476]
While constructor injection is enough in general, controllers are a special case because there are too many different contexts (actions) and each needs a separate set of class instances.

Would be cool to support doing it like this instead of checking for action name in constructor:

```php
class PostController extends Controller
{
    public function actionView($id, OpenGraphInterface $og)
    {
        $post = Post::findOne($id);
        $meta = $og->getMeta($post);
        // ...
    }
}
```

**Comment by samdark** [comment]
Preferrably to be implemented via trait so method-injection could be added to any user class.

**Comment by samdark** [comment]
```php
class MyClass
{
    use MethodInjection;

    public function doIt(CoolInterface $coolClass)
    {
        // ...
    }
}
```

**Comment by briedis** [comment]
Oh yes, at last. Really enjoyed this feature in Laravel.

I would like to suggest to cleanup the controller constructor, because it's kinda stupid, that I have to inject dependencies between second and third parameter. I still don't understand why would some kind of `$config` be needed there.

I like how cleanly Laravel does it - no default arguments for constructors and actions. 

And it works awesome when you can request Request object to be injected in the method - and it just injects the current request.

```
    public function actionNewOrder()
    {
        $storeId = (int)Yii::$app->request->post('storeId');
        $isSampleOrder = (bool)Yii::$app->request->post('isSampleOrder');
```

would nicely become, much much cleaner:

```
    public function actionNewOrder(Request $request)
    {
        $storeId = (int)$request->post('storeId');
        $isSampleOrder = (bool)$request->post('isSampleOrder');
```

**Comment by df2** [comment]
> I still don't understand why would some kind of $config be needed there.
Have you tried it without?

> would nicely become, much much cleaner:
Would conflict with passing url parameters as action parameters. And I really think you could add one line to store the request object locally to get the same effect.

**Comment by df2** [comment]
@samdark 

When would the services be binded? After beforeAction event?

**Comment by briedis** [comment]
I bind services in a separate file. Sadly, there isn't a documented place where you should put your bindings. Service provider class would be useful.

**Comment by df2** [comment]
Gotcha. I have a particular use case where I don't know the implementation of a particular interface until beforeAction(), so I have to set it there. Other than that I am using the constructor method and filling the container in the entry script before running the application.

**Comment by samdark** [comment]
@df2 not sure about it yet. I guess, yes. Either before or after `beforeAction`.

**Comment by df2** [comment]
Considering url params aren't bound yet then either, it would seem most consistent to do the binding of services at the same time (after beforeAction).

**Comment by df2** [comment]
(With public `bindActionServices($action)` method and public `$actionServices` in controller.)

Maybe Services naming is too specific, but I am thinking most all of injected classes are services.

**Comment by mdmunir** [comment]
:+1: 
```php
// bindActionParams

            $name = $param->getName();
            if (array_key_exists($name, $params)) {
                if ($param->isArray()) {
                    $args[] = $actionParams[$name] = (array) $params[$name];
                } elseif (!is_array($params[$name])) {
                    $args[] = $actionParams[$name] = $params[$name];
                } else {
                    throw new BadRequestHttpException(Yii::t('yii', 'Invalid data received for parameter "{param}".', [
                        'param' => $name,
                    ]));
                }
                unset($params[$name]);
            } elseif ($param->isDefaultValueAvailable()) {
                $args[] = $actionParams[$name] = $param->getDefaultValue();
            } elseif (($c = $param->getClass()) !== null) {
                $type = $c->getName();
                if (Yii::$app->has($name) && ($o = Yii::$app->get($name)) instanceof $type) {
                    $args[] = $o;
                }else{
                    $args[] = Yii::$container->get($type);
                }
            } else {
                $missing[] = $name;
            }
```

**Comment by samdark** [comment]
@mdmunir how about a pull request?

**Comment by akireikin** [comment]
Nice feature.

It seems we will be able to do smth like that.

```php
Yii::$container->set(Post::class, function () {
    $id = Yii::$app->request->get('id');
    return $id ? Post::findOne($id) : new Post();
});

class PostController extends Controller
{
    public function actionView(Post $post, OpenGraphInterface $og)
    {
        $meta = $og->getMeta($post);
        // ...
    }
}
```

Of course, there are two sides of the same coin.

**Comment by samdark** [comment]
@akireikin which two sides?

**Comment by akireikin** [comment]
On the one hand, controllers look clear and simple.

On the other hand, if a lot of magic are shifted to DI config (especially **Callable Injection** for entities), we will get bugs hard to track.

**Comment by samdark** [comment]
Well, yeah. Yii is a framework so it should allow both straightforward and flexible approaches. Straightforward one is already polished. Flexible one was definitely missing DI in controller actions.

**Comment by akireikin** [comment]
It makes sense.
Пн, 7 сент. 2015 г. в 19:12, Alexander Makarov <notifications@github.com>:

**Comment by dynasource** [comment]
@samdark: Could you give us some usecases with examples in which you'd use this feature?

**Comment by samdark** [comment]
I'm thinking about reusable modules where components are to be implemented in the app. Module is providing interfaces for these components but not implementation.

**Comment by lynicidn** [comment]
@samdark так 1 контейнер на все, вы же не вынесли контейнеры на уровень модулей, так что в твоем понимании это работать не будет как ожидаешь https://github.com/yiisoft/yii2/issues/4130

**Comment by klimov-paul** [comment]
For me allowing DI param binding for the acontroller action params is wrong.

Controller action params are meant to track and accept user input. We are binding request params to the action arguments.
With this change it seems user can choose particular application component to be used in action.

For example:

```php
public function actionFoo($foo, Security $crypt)
{
}
```

If I have more then one `Security` instance among the application components user can switch, which one to be used in action, passing different value for 'crypt' URL param.
This does not feel right.

**Comment by klimov-paul** [comment]
What we are trying to achieve here exactly?
Removing call of single code row:
```php
$crypt Yii:$app->get('secutiry');
```
whle introducing some hard-to-undestand fancy interface?

And what about binding ActiveRecord instances, like #9890 suggests, then?

**Comment by klimov-paul** [comment]
May be I simply do not understand the feature, but seems pretty odd and risk prone.

**Comment by SamMousa** [comment]
@klimov-paul I think for this case we are not looking at the value of `$crypt` but merely at the name of the variable?

Ie in this case if `$crypt` is passed in URL it would throw 400?

**Comment by dynasource** [comment]
I'm agreeing with @klimov-paul. Perhabs this provides some extra configuration, but it feels like magic and adds confusion.

**Comment by klimov-paul** [comment]
Originally action method arguments specified request (URL query string) parameters, which should be passed to the action. This is quite logical, while removes calls of `Yii::$app->request->getQueryParam()` for every case.
Now we are mixing this feature with something else.

**Comment by dynasource** [comment]
exactly

**Comment by SamMousa** [comment]
@klimov-paul You are right, but there is a clear boundary: user parameters are always string typed and injected parameters are always object instances.

Also there is no need to explicitly choose what we do for everyone. We could implement the code in the core and enable / disable it by default?

**Comment by klimov-paul** [comment]
The good thing about Yii - it is simple. Why do we need such complex and twisted feature inside it?

**Comment by briedis** [comment]
@klimov-paul Yeah, I vote that we should remove constructor injection too, it's too complicated and fancy.

**Comment by klimov-paul** [comment]
> we should remove constructor injection too

No we can not. This is a repalcement for old-fasion 'factory' OOP pattern. Without it adjusting widgets and some other things will be impossible.

Having some method argument injection similar to constructor injection can be considered. We may have some `Yii::invokeMethod()` with built-in DI support just as we have `Yii::createObject()`. Curently it is not implemented, by the way.

However, controller action methods should NOT be affected by such arguments injection - they already have thier own logic bound with them.

**Comment by klimov-paul** [comment]
@cebe can you take a look?

**Comment by df2** [comment]
Constructor injection has been solid. I have reservations now about method injection and see it as a premature optimization. I would also prefer the least 'sweeps' possible at runtime; for purists or anyone who won't use action binding, we are laboured with the extra cycles. My 2/c

**Comment by cebe** [comment]
I have never used DI container explicitly in my code and I never felt the need for it. So I can not tell whether this feature is needed or not. But when reviewing this feature I find that it adds too much magic and I would be confused on how to debug it. For example:

```php
<?php
namespace app\controllers;
class SomeController extends \yii\web\Controller
{
    public function actionDoSeomthing($id, \yii\base\Security $security) {
      // getting $security via action params is magic and
      // I have no idea where to look or debug when I do not get what I wanted...
    }
}
```

The explicit way is directly clear where it comes from (also this allows me to see which DI container is used):

```php
<?php
namespace app\controllers;
class SomeController extends \yii\web\Controller
{
    public function actionDoSeomthing($id, Security $security) {
      
      // I need the security instance here, so I either do:
      $security = Yii::$app->security;
      
      // or "give me some implementation of that security class"
      $security = Yii::$container->get('yii\base\Security');

    }
}
```

Additionally there is already a bit of magic involved in the action params. Imo this is too much. I'd vote for reverting this feature.

**Comment by cebe** [comment]
Note that constructor injection is different. For the person who writes the constructor, there is no magic at all, it expects the creator of the object to pass an instance. In that case it does not matter where the instance comes from as the class is generic so it works with any kind of instance that matches the specified interface or base class. For the creator it is clear that the constructor expects arguments so they have to be passed if the object is created manually or if it is created via DI, it is clear for the creator that DI is involved because it is called explicitly.

In case of the action we expect a specific instance that depends on the class type hint and the param name which is totally unclear when I look at the code as someone who does not know this feature in detail.

**Comment by briedis** [comment]
You gotta be kidding me…

**Comment by cebe** [comment]
@briedis care to elaborate?

**Comment by briedis** [comment]
We're finally moving towards a more pleasant coding experience and you shoot it down just because you haven't used it. 

> Note that constructor injection is different.

It's not different, it's just another way injection works. It's useful when dependencies vary withing methods. Why do I have to inject everything in the constructor if one dependency is used only per one method. 

Sure, I can use `Yii::$container->get(MyDependency::class)` but that's not very convenient and depends on global container.

The method injection is perfect for testing too - you just pass your instance or mock or whatever to the method you test and done, you don't have to pass all dependencies that are required by constructor.

**Comment by df2** [comment]
@briedis The way to comprehend this is in terms of what Yii provides compared to alternatives: aluminum scaffolding, clear code path, and no cruft.

To add in a feature like method injection makes the framework more obese. Of course it is a preference whether that is an okay trade off. But the idea of adding quite a bit of weight to every request should be down to the developer who can choose to implement this by their own base controller.

**Comment by cebe** [comment]
> We're finally moving towards a more pleasant coding experience and you shoot it down just because you haven't used it.

I am not shooting it down because I am not using it. Above my comment a lot of arguments have been given against this feature and I have explained why it is too magical in my opinion.

> Why do I have to inject everything in the constructor if one dependency is used only per one method.

What my PR reverts is not generic method injection but "controller action injection" which is much more magical than generic method injection. I am not opposing method injection in general.

> Sure, I can use Yii::$container->get(MyDependency::class) but that's not very convenient and depends on global container.

What is inconvenient about it? Your Controller depends on `Yii::$container` anyway with this feature.

**Comment by cebe** [comment]
Generic method injection is proposed by #9795 which is still open and under discussion.

**Comment by samdark** [comment]
> What is inconvenient about it? Your Controller depends on Yii::$container anyway with this feature.

Nope. Controller depends on concrete class in that case, not container.

**Comment by briedis** [comment]
And code looks much cleaner too, and I don't have to force-document the instace, because IDEs cannot resolve type from generig `->get()` method.

[Image](https://ziedlejas.lv/screenshots/img.2016.02.06.LpXouZ.png)

vs

[Image](https://ziedlejas.lv/screenshots/img.2016.02.06.6lauam.png)

**Comment by samdark** [comment]
Thinking more about it, controller in Yii depends a lot on framework itself, environment etc. so it makes no sense to inject anything into it via magic.

@briedis your argument makes sense only from IDE completion standpoint.

**Comment by samdark** [comment]
There are con and pro of having controller action injection. Pro is that it provides new fancy way of writing code which is nice to IDEs and code completion. Con is that this code behavior is pretty much magical and is harder to understand and debug.
We prefer easy to debug and understand to a bit fancier IDE support. As for injection itself, Yii controllers are already pretty much dependent on Yii::$app, base controller and environment so it makes no sense trying to inject dependencies into them in implicit way.

**Comment by samdark** [comment]
@mdmunir again, sorry for rejecting contribution. It resulted in very productive discussion and important decisions though.

**Comment by mdmunir** [comment]
:+1:

**Comment by SamMousa** [comment]
So just to get it straight; this will be reverted meaning it will break BC? Since I currently use action injection in my code and it was in 2.0.6? -- Or am I missing something?

**Comment by samdark** [comment]
No BC will be broken. 2.0.6 has no controller action injection.

**Comment by SamMousa** [comment]
Okay; guess I had some projects running on dev-master :-1: 
So if I want this kind of injection I can either refactor to separate action classes (and use constructor injection) or override the appropriate controller.. And since there is no event other than before action I can't do this via configuration / behaviors...

**Comment by samdark** [comment]
@SamMousa can be done via trait where you'll override `bindActionParams()` as [it was done before it was reverted](https://github.com/yiisoft/yii2/commit/42b85698460102751e819d34e0c3dbf5ab5d280a).

**Comment by kirsenn** [comment]
It's very sad, I've been waiting 2 years for this feature

**Comment by samdark** [comment]
@kirsenn if you want you can have it via trait.

**Comment by cebe** [comment]
@mdmunir @SamMousa would someone of you want to create and maintain an extension that provides a trait with this functionality?

**Comment by SamMousa** [comment]
Yes I will, expect it to be up end of the week

**Comment by cebe** [comment]
awesome, thanks :)

**Comment by cebe** [comment]
> Yes I will, expect it to be up end of the week

@SamMousa does that thing exist already, if so, it would be great to link it here.

**Comment by SamMousa** [comment]
Yes it does, I'm already using it in production.

https://github.com/sam-it/yii2-magic

**Comment by allowing** [comment]
I think, controller is like a Client, we code in it.

So, it not need unit test, not need debug.

.....hahahaha

**Comment by webivan1** [comment]
Hi! My extension https://github.com/webivan1/validateAction, usage DI in action
