### ISSUE TITLE
PHP Fatal error: Class 'resque\lib\Resque\Resque_Job_DirtyExitException' not found

### ISSUE THREAD

**Issue by rohitmel** [yiisoft/yii2#9480]
PHP Fatal error: Class 'resque\lib\Resque\Resque_Job_DirtyExitException' not found in xxxxxxxxx/vendor/resque/yii2-resque/lib/Resque/Worker.php on line 233
Error: Class 'resque\lib\Resque\Resque_Job_DirtyExitException' not found

**Comment by samdark** [comment]
It's not framework part.

**Comment by rohitmel** [comment]
k thanks
