### ISSUE TITLE
Are we allowed to directly assign permissions to users?

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2#9483]
I was working on #9314 when I realised no where in the docs we have an example of directly assigning permissions to users.
I asked in [forum](http://www.yiiframework.com/forum/index.php/topic/67350-are-we-allowed-to-directly-assign-permissions-to-users/), but no one answered and I think here is a more suitable place to ask.
in [official guide](http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#generating-rbac-data) we have:
```php
        $auth = Yii::$app->authManager;

        $createPost = $auth->createPermission('createPost');
        $createPost->description = 'Create a post';
        $auth->add($createPost);

        $author = $auth->createRole('author');
        $auth->add($author);
        $auth->addChild($author, $createPost);
        
        $auth->assign($author, 2);
```
permissions are children of roles and roles are assigned to users. this quote from guide also promotes this:
> A role represents a collection of permissions (e.g. creating posts, updating posts). A role may be assigned to one or multiple users. To check if a user has a specified permission, we may check if the user is assigned with a role that contains that permission.

But what if one assigns a permission directly to a user? no roles in between.
```php
        $auth = Yii::$app->authManager;

        $createPost = $auth->createPermission('createPost');
        $createPost->description = 'Create a post';
        $auth->add($createPost);
        
        $auth->assign($createPost, 2);
```
the above code works fine and also `checkAccess(2, 'createPost')` method will return true. 
Is it okay to do that?  if Yes then #9314 makes sense, if not then I think `assign()` method should throw an exception when a permission is passed to it.

**Comment by samdark** [comment]
Technically it will work. It's less flexible though.
