### ISSUE TITLE
Missing "use Yii;" on the "Saying Hello" - guide-start-hello

### ISSUE THREAD

**Issue by brunofunny** [yiisoft/yii2#9486]
When creating a new controller it must have a "use Yii;" line in order to the controller to work. It's missing in the "Saying Hello" guide, what can misguide some new users and lead them to error.

File: https://github.com/yiisoft/yii2/blob/master/docs/guide/start-hello.md

**Comment by cebe** [comment]
which example code are you referring to? I do not see any use of the `Yii` class in the article you have linked.

**Comment by samdark** [comment]
Hmm... indeed no usage of `Yii` class in the doc linked.

**Comment by brunofunny** [comment]
Yeah, so I think it would be great to fix it right ?
Because newcomers can read the start-hello and get a "Class 'app\controllers\Yii' not found".

**Comment by cebe** [comment]
@brunofunny would you mind explaining how to get this error?

**Comment by brunofunny** [comment]
Sure, not using "use Yii;" declaration in any controller causes it.

**Comment by cebe** [comment]
in combination with which code?

**Comment by brunofunny** [comment]
@cebe using what's declared in the guide. If you download the basic template it's ok, because the SiteController already contains the "use Yii;" but if you're not using Gii and is creating a controller manually, if you do not put this, then it will return an error. 

So the guide should declare the use of it in my opinion.

**Comment by samdark** [comment]
@brunofunny but at https://github.com/yiisoft/yii2/blob/master/docs/guide/start-hello.md there are no calls to `Yii::` so `use \Yii` isn't needed and no errors would appear w/o it.

**Comment by AtillaMaia** [comment]
I wasted my time this afternoon about this error. I'm new here. I downloaded the basic one and I'm following the guide. I could just do the "Saying Hello" after comment or delete  "use Yii;" on SiteController.

**Comment by cebe** [comment]
@AtillaMaia can you give more information about this error? How does your controller look like and how is the actual error message? also please add the stack trace of the error.
