### ISSUE TITLE
Model::setAttributes() accepts only arrays, not ArrayAccess

### ISSUE THREAD

**Issue by elnoro** [yiisoft/yii2#9494]
From here https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L692
Why Model::setAttributes() accepts only arrays? Should it not be allowed to use collections like this https://github.com/morrisonlevi/Ardent or a custom class which implements ArrayAccess interface?

**Comment by samdark** [comment]
It should then implement not only ArrayAccess but Traversable as well.

**Comment by SamMousa** [comment]
Custom objects can implement `Traversable` as @samdark said.
There is no way to iterate over an object with just `ArrayAccess`.
Alternative is to iterate over the attributes of the model and then try to pull the values from the model.

The library mentioned in the OP supports its own `Enumerable` construct which extends `IteratorAggregate`. As far as I can tell this should work.

**Comment by samdark** [comment]
I think it's out of scope of `setAttributes()`...

**Comment by samdark** [comment]
Won't be implemented in 2.0.
