### ISSUE TITLE
Documentation Testing

### ISSUE THREAD

**Issue by WJRovers** [yiisoft/yii2#9499]
I would love to develop some testing with codeception within yii2. I'm however having troubles with simply getting started to setup the environment. I've been toying around for a while now and all I'm getting is a succeeded testing run because he detects no tests at all!

If anyone could get me started on how to get running i could add to the documentation myself later on.

**Comment by samdark** [comment]
Check how it's done in basic/advanced apps.

**Comment by samdark** [comment]
Basic concepts are well described in codeception docs.

**Comment by Faryshta** [comment]
@samdark well i found it very hard to understand how to configure a test environment for codeception and even after reading the docs still don't understand the differences between functional and acceptance testing.

**Comment by klimov-paul** [comment]
> don't understand the differences between functional and acceptance testing

There is no technical difference between functional and acceptance tests - it is a philosophic difference between them.
Acceptance test means the one explicitely defined by the customer or project owner, reflecting some high level system demand. While functional test means any test performed over the complete product.

**Comment by Faryshta** [comment]
That explains it much better thanks @klimov-paul
