### ISSUE TITLE
yii.activeform.js integrate function to check if input is validated

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#9500]
I have form and 8 fields. What I want to do is in Javascript validate only 2 fields and return true or false depending on if they are both valid or no.

**Comment by samdark** [comment]
```javascript
$('#contact-form').data('yiiActiveForm').submitting = true;
$('#contact-form').yiiActiveForm('validate');
if ($('#contact-form').find('.has-error').length) {
    // error
}
```

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md

**Comment by BenasPaulikas** [comment]
Correct me if I'm wrong but I think $('#contact-form').yiiActiveForm('validate') uses ASYNCHRONOUS methods. So when It start validation and I check for $('#contact-form').find('.has-error').length its equal to 0

**Comment by samdark** [comment]
Ah. Yes.

**Comment by BenasPaulikas** [comment]
console.log($('#contact-form').find('.has-error').length);
    setTimeout(function(){
        console.log($('#test-form').find('.has-error').length);
    }, 1000);

Output:

    0
    5

**Comment by Alex-Code** [comment]
You could use the [`afterValidate`](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L50) event.
That will be called after asynchronous validation.

**Comment by BenasPaulikas** [comment]
afterValidate events works perfect :+1: 

My current code is and it works perfectly. I get message that "Form is validated"

    $('#test-form').data('yiiActiveForm').submitting = true;
    $('#test-form').yiiActiveForm('validate');
    $('#test-form').on('afterValidate', function(e){
        console.log('Form validated');
    });

However if I change 
    $('#test-form').yiiActiveForm('validate');
with
    $('#test-form').yiiActiveForm('validateAttribute', 'test-location');

It doesn't validate and I don't get valiadtion error :(

**Comment by BenasPaulikas** [comment]
Thanks. afterValidate works perfect. :+1: 
However I want to validate 2 specific fields and as I see there's no event for that. I woud use

    afterValidateAttribute

but it requires whole form validation 

    afterValidateAttribute event is triggered after validating the whole form and each attribute.

**Comment by nkovacs** [comment]
afterValidateAttribute is called in both cases (whole form and single attributes - the documentation is a bit confusing). afterValidate is called only after whole form validation.

**Comment by SilverFire** [comment]
I've checked the use case.

First of all it's better to check for the [attribute status](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L156) istead of searching for some DOM elements with specific class.

```
0: empty, not entered before, 1: validated, 2: pending validation, 3: validating
```

There are two ways to solve the task:

1. Listen for `afterValidate` event, which is triggered for the full form validation (for example on `submit` button click):
```js
$('#my-form').on('afterValidate', function (event, messages, errorAttributes) {
   var scrollPosision = null;
   $(errorAttributes).each(function (key, attribute) {
       // Special behavior for unchecked "Accept agreement" input
       if (attribute.name === 'accept_agreement') { 
           alert('You should accept the agreement!');
       }
       // Save the position of the first errored element
       scrollPosision = scrollPosision || $(attribute.input).offset().top;    
    });

   // Scroll smoothly to the first errored element
   if (scrollPosision !== null) {
      $('html, body').animate({scrollTop: scrollPosition}, 1000);
   }
});
```

2. Listen for the `afterValidateAttribute`, which is triggered for each field being validated (for example on input blur, change of form submit attempt):
```js
$('#my-form').on('afterValidateAttribute', function (event, attribute, messages) {
   // When the attribute name is 'username', and it's under validation, and there are error messages
   if (attribute.name === 'username' && attribute.status === 3 && messages.length > 0) {
      alert('Your username is invalid! See the error message near to the input!');
   }
});
```
