### ISSUE TITLE
After update got unstable

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#9503]
I have backend (backend.domain.com) and frontend (domain.com) apps in advanced template. They have separate nginx configs. And they worked well until last update. (Btw, I'm on stable channel)

It redirects all requests into backend. And opens domain.com as backend app. I tested frontend separately. Added die("test") into frontend's index file. It dies and show up "test". So there is no problem with nginx or php. 

Please fix this issue.

**Comment by samdark** [comment]
Have you updated from 2.0.5 to 2.0.6?

**Comment by samdark** [comment]
Based on description I can't imagine any reason for such behavior. Unable to fix it if you won't provide a way to reproduce it.

**Comment by turalsprofile** [comment]
First I updated to 2.0.7 in dev channel. After this behaviour removed all contents of vendor folder, also composer.lock and switched composer into stable channel and upgraded to 2.0.6. Same behaviour. I even removed environments folder and re-downloaded default environments folder from yii repository and re-initialized in both environments. Same issue. Frontend forwards all requests into backend. Added die("test") into frontend's index file. It dies and show up "test". Even rebuilt server from ground up. Same issue.

**Comment by samdark** [comment]
Well, I have no idea how your frontend and backend are configured.

**Comment by cebe** [comment]
@turalsprofile yii has no builtin code that could redirect to your backend there must be something in your application code that does that. unless you can give us more information about which part of yii might cause the issue we can not help your with this. You may use xdebug to trace the code that does the redirect.

**Comment by turalsprofile** [comment]
@cebe @samdark 

I'm trying to recreate issue:

On fresh installed Debian 8 X64 installing following packets:

```
apt-get install nginx zip git php5-fpm php5-gd php5-json php5-xcache php5-mysql php5-mcrypt php5-imagick curl php5-curl php5-cli mysql-client mysql-server apache2-utils vim -y

php5enmod mcrypt

curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

composer global require "fxp/composer-asset-plugin:~1.0.3"

cd /var/www
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application
```

Forwarding both: backend.domain.com and domain.com to the same IP. And setting up nginx as:

```
server {
    charset utf-8;
    client_max_body_size 128M;
    listen 80;
    server_name domain.com;
    root        /var/www/frontend/web;
    index       index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        #fastcgi_pass   127.0.0.1:9000;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        try_files $uri =404;
    }

    location ~ /\.(ht|svn|git) {
        deny all;
    }
}
server {
    charset utf-8;
    client_max_body_size 128M;
    listen 80;
    server_name backend.domain.com;
    root        /var/www/backend/web;
    index       index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        #fastcgi_pass   127.0.0.1:9000;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        try_files $uri =404;
    }
    location ~ /\.(ht|svn|git) {
        deny all;
    }
}
```

Everything besides of this procedures are untouched. So after all of these procedures, I initialized freshly installed yii2 advanced template in production mode. In this environment either backend.domain.com or domain.com opens same: frontend's views. 

When I switch into development env. Now it forwards all traffic into backend. t either backend.domain.com or domain.com opens same: backend views.

But when I touch their index.php files separately (for example add die("test") to one of them) they show changes immediatelly. 

Please recreate this environment and test. Thank you very much

**Comment by kidol** [comment]
@turalsprofile 
Why don't you debug it further by adding var_dump into certain places like view-file resolution?
You can start here: https://github.com/yiisoft/yii2/blob/master/framework/base/View.php#L149

**Comment by turalsprofile** [comment]
I think it's related to Yii itself. It's neither PHP nor NgInX problem. I wrote lots of projects on Yii2 advanced template and everytime installed like this. It happened recently

**Comment by turalsprofile** [comment]
@cebe @samdark It's only related to Debian 8 x64. Did same steps on Ubuntu 14.04. Now it works good.

**Comment by samdark** [comment]
OK. It seems there's nothing to fix framework side.

**Comment by turalsprofile** [comment]
This problem appeared again. I decided to test backend's index.php. Line by line. 

```
require(__DIR__ . '/../../vendor/autoload.php');
require(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/../../common/config/bootstrap.php');
require(__DIR__ . '/../config/bootstrap.php');
```

I took die("test") on every line. It appeard everytime except after last line
```
require(__DIR__ . '/../config/bootstrap.php');
```

The thing is, bootstrap.php of backend is completely empty file. It has only opening <?php . I just copied and pasted contents of common's bootstrap.php
```
Yii::setAlias('common', dirname(__DIR__));
Yii::setAlias('frontend', dirname(dirname(__DIR__)) . '/frontend');
Yii::setAlias('api', dirname(dirname(__DIR__)) . '/api');
Yii::setAlias('static', dirname(dirname(__DIR__)) . '/static');
Yii::setAlias('backend', dirname(dirname(__DIR__)) . '/backend');
Yii::setAlias('console', dirname(dirname(__DIR__)) . '/console');
```

It worked. 

Now the question is, how is it possible to forward all traffic from backend to frontend just because of empty bootstrap file?

What makes it to behave so?

@samdark  @cebe

**Comment by cebe** [comment]
Unable to reproduce. If I remove bootstrap config or make it empty, I get the following error:

> An Error occurred while handling another error:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "site/error".'

maybe your error handling causes some redirects?

**Comment by turalsprofile** [comment]
@cebe how can I make error handling as default?
