### ISSUE TITLE
Connection::cache don't cache?

### ISSUE THREAD

**Issue by ssjssh** [yiisoft/yii2#9505]
As comment mentioned, Connection::cache is supposed to cache the results after $callable executed. But when I explore the source code, I find that this function just call $callable and returns. So, What I am missing? Is it a bug?
I do test it ,
<pre>
$user = \Yii::$app->db->cache(function (Connection $db) {
            var_dump("this time execute");
            return $db->createCommand('SELECT * FROM user WHERE id=1')->queryOne();
        });//print "this time execute" every time.
</pre>

**Comment by cebe** [comment]
the method will always execute but the query will only hit the DB on the first run. on the second call it will return cached result. this happens inside of `->queryOne()` method.
