### ISSUE TITLE
how to change default controller viewPath in yii2

### ISSUE THREAD

**Issue by PooyaE** [yiisoft/yii2#9506]
I recently change my app directory (all views and controllers are in new path)

but I get new issue with my defaultController, views are not working for debug,gii and etc...
    
    Exception 'yii\base\InvalidParamException' with message 'The view file does not exist:     \default\toolbar.php' 
    
    in D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\base\View.php:225
    
    Stack trace:
    #0 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\base\View.php(149): yii\base\View-    >renderFile('\default\toolba...', Array, Object(yii\debug\controllers\DefaultController))
    #1 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\base\Controller.php(402):     yii\base\View->render('toolbar', Array, Object(yii\debug\controllers\DefaultController))
    #2 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2-    debug\controllers\DefaultController.php(98): yii\base\Controller->renderPartial('toolbar', Array)
    #3 [internal function]: yii\debug\controllers\DefaultController->actionToolbar('55d983f0783eb')
    #4 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\base\InlineAction.php(55):     call_user_func_array(Array, Array)
    #5 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\base\Controller.php(151):     yii\base\InlineAction->runWithParams(Array)
    #6 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\base\Module.php(455):     yii\base\Controller->runAction('toolbar', Array)
    #7 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\web\Application.php(84):     yii\base\Module->runAction('debug/default/t...', Array)
    #8 D:\xampp\htdocs\green-fw.git\api\resources\vendor\yiisoft\yii2\base\Application.php(375):         yii\web\Application->handleRequest(Object(yii\web\Request))
    #9 D:\xampp\htdocs\green-fw.git\index.php(12): yii\base\Application->run()
    #10 {main}

how cant I fix that?

or more than that, how is the best way to change app path?

**Comment by lichunqiang** [comment]
It support path alias, you can do like this:

```
return $this->render('@app/newpath/default/index');
```
