### ISSUE TITLE
Can't set cookie at first access after clear cookie

### ISSUE THREAD

**Issue by kestrelbright** [yiisoft/yii2#9508]
normal
![qq20150824-1](https://cloud.githubusercontent.com/assets/1538847/9432156/86fff070-4a50-11e5-99f0-129fae380aa9.png)
delete all, then refresh
![qq20150824-2](https://cloud.githubusercontent.com/assets/1538847/9432154/83e80eae-4a50-11e5-84dc-ecd71558a09a.png)
set csrf cookie failed.
I update here(\yii\web\Request)
```
    /**
     * Generates  an unmasked random token used to perform CSRF validation.
     * @return string the random token for CSRF validation.
     */
    protected function generateCsrfToken()
    {
        $token = Yii::$app->getSecurity()->generateRandomString();
        if ($this->enableCsrfCookie) {
//            $cookie = $this->createCsrfCookie($token);
//            Yii::$app->getResponse()->getCookies()->add($cookie);
	      setcookie($this->csrfParam, $token);
        } else {
            Yii::$app->getSession()->set($this->csrfParam, $token);
        }
        return $token;
    }
```
set succeed.

**Comment by cebe** [comment]
could be that you are sending output before headers are sent. hard to debug that. could be in your layout if you forget beginPage() call maybe.

**Comment by kestrelbright** [comment]
Indeed, I didn't call beginPage(). I'm use smarty render html. Thanks your answer.
