### ISSUE TITLE
unable to set session for IVR users

### ISSUE THREAD

**Issue by senguttuvang** [yiisoft/yii2#9509]
I'm using Yii2 to power my IVR app. The IVR vendor passes an CallSid param each time they hit an end point. CallSid is unique across the calls so I mapped CallSid's value to Session Id name. I extended the Session to accomplish this -- initialize session without cookies, but it doesn't seem to work.

I understand it may lead to session fixation, I can resolve it by making an API to call to validate the CallSid. How can I make Yii2 to recognize CallSid to initialize session?

```php
use yii\web\Session as BaseSession;

class Session extends BaseSession {

	public function init() {
		$request = Yii::$app->request;
		if( ! is_null($request->get('CallSid'))) {
			 ini_set("session.use_cookies", 0);
			 ini_set("session.use_only_cookies", 0);
			 ini_set("session.use_trans_sid", 1);
			 ini_set("session.cache_limiter", "");
			$this->setId($request->get('CallSid'));
		}
		parent::init();
	}

}
```

**Comment by senguttuvang** [comment]
With the current setting, I'm able to initialize the session with CallSid param and able retrieve the values from session. But, when I use the same setting with app on browser, it keeps showing me the login page. I expected CallSid to automatically rewritten to URL, but that didn't happen.

**Comment by klimov-paul** [comment]
> How can I make Yii2 to recognize CallSid to initialize session?

The code snippet you provided should work just fine.

> when I use the same setting with app on browser, it keeps showing me the login page. I expected CallSid to automatically rewritten to URL, but that didn't happen.

I am unsure I understand this part. If you expect `CallSid` param magically appear at all URLs created by Yii - this will not happen. You'll have to adjust `UrlManager` to do so.

Closing, unless more coherit description provided.
