### ISSUE TITLE
how to create multiple login access in yii2?

### ISSUE THREAD

**Issue by engmmrj** [yiisoft/yii2#9513]
I am creating a site in Yii2. I want have two login with two tables but suppose there is an Id for logged in user is 1 and same id belongs from other table for admin user than Yii takes both identity and it show two logout button one for admin user and other for normal user but it should show only one logout and Yii should keep identity for that particular controller/login. Please help what can i do.
using basic version
i think it's a bug !

// login admin module
    'user' => [
    				'class' => 'yii\web\User',
    				'identityClass' => 'app\models\User',
    				'enableAutoLogin' => true,
    		
    		],
    // login site   
    	'marketer' => [
    		'class' => 'yii\web\User',
    	    'identityClass' => 'app\models\Marketer',
    		'enableAutoLogin' => true,
    		'loginUrl' => 'test/index',
    		'identityCookie' => [
    			'name' => '_marketer', 
    			'httpOnly' => true,
    		]
    	],

**Comment by samdark** [comment]
How would you fix it?

**Comment by engmmrj** [comment]
i don't no , you are programmer of yii

**Comment by denniselite** [comment]
You can create extended userIdentity class for multiple application users. Why not?

**Comment by engmmrj** [comment]
i am elementary , can you it doing ?

**Comment by klimov-paul** [comment]
This is obviously a forum question.

**Comment by YogeshPiP** [comment]
How would you fix it?
