### ISSUE TITLE
BaseArrayHelper should should treat object in same way as arrays

### ISSUE THREAD

**Issue by tebazil** [yiisoft/yii2#9516]
WIth arrays we are getting the default value for nonexistent key, thanks to `array_key_exists` check. With objects, however, we are trying to access property regardless on whether it is accessible.

I suggest this method treats objects the same way as arrays: in case of private or nonexistent properties we are getting the default value.

**Comment by tebazil** [comment]
I suggested s [PR](https://github.com/yiisoft/yii2/pull/9517) on the subject

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/issues/7193#issuecomment-73287156
