### ISSUE TITLE
Docblock "@return" into \yii\db\ActiveRecord::findOne and others failed

### ISSUE THREAD

**Issue by antivir88** [yiisoft/yii2#9520]
findOne return static or null , IDE PhpStorm thinking that is Controller , not Model ((((

**Comment by samdark** [comment]
How can I reproduce it?

**Comment by antivir88** [comment]
public function actionDeltrans()
    {
        /** @var Transaction $trans */
        $trans = Transaction:



Remove doc-block and add ":" into PHPStorm

**Comment by antivir88** [comment]
https://github.com/yiisoft/yii2/pull/9521

**Comment by cebe** [comment]
closed. see https://github.com/yiisoft/yii2/pull/9521#issuecomment-135395423 and #7404 and https://youtrack.jetbrains.com/issue/WI-19953 .
