### ISSUE TITLE
how to setup cron in yii2

### ISSUE THREAD

**Issue by dewoolkarjanhavi** [yiisoft/yii2#9523]
I am trying to setup CRON in my yii2 project. I have already referred the following link -http://www.yiiframework.com/wiki/646/how-to-implement-cron-in-yii-2/
This link does not explain the entire flow properly. Below is the error which I am getting- 
![issue](https://cloud.githubusercontent.com/assets/11611520/9493624/87e03c28-4c1e-11e5-8bd0-59073674ef6c.jpg)
Can anyone please explain all the config settings and the flow needed for cron setup in yii2?
Thanks in advance.

**Comment by klimov-paul** [comment]
@dewoolkarjanhavi, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by philippfrenzel** [comment]
This error is appearing while CLI is not enabled... happens on some servers... e.g. 1und1 in germany...
