### ISSUE TITLE
Темизация. Баг с путями?

### ISSUE THREAD

**Issue by maxyc** [yiisoft/yii2#9524]
@samdark прошу прощения, что на русском. 
Итак. Сделал следующую структуру файлов:
```
@app/themes
@app/themes/basic
@app/themes/basic/assets
@app/themes/basic/assets/js
@app/themes/basic/assets/css
@app/themes/basic/assets/img
@app/themes/basic/AppAssets.php
@app/themes/basic/layouts
@app/themes/basic/site
...etc...
```
Сделал ассет themes/basic/AppAssets.php
```php
namespace app\themes\basic;

use yii\web\AssetBundle;

class AppAsset extends AssetBundle
{

    public $sourcePath = '@app/themes/basic/assets';
    public $publishOptions = [
        'forceCopy'=>true
    ];

    public $css = [
        'fonts/font-awesome/css/font-awesome.min.css',
        'css/uniform.css',
        'css/ripple.min.css',
        'css/fullcalendar.css',
        'css/styles.css'
    ];
    public $js = [
        '//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.full.min.js',
        'js/jquery-ui.js',
        'js/jcarousel.js',
        'js/uniform.js',
        'js/ripple.min.js',
        'js/moment.min.js',
        'js/fullcalendar.min.js',
        'js/ru.js',
        'js/jquery.jcarousel.min.js',
        'js/jquery.spoiler.min.js',

        //'/assets/js/dynamic-old.js',
        'js/plugins.js',
        'js/app.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\widgets\MaskedInputAsset',
        'yii\web\JqueryAsset'
    ];
}
```

в @app/themes/basic/layouts/landing.php вставил \app\themes\basic\AppAsset::register($this);
вроде все хорошо на данном этапе. 
Далее в верстке присутствуют картинки из раздела @app/themes/basic/assets/img, чтобы к ним получить доступ нам нужно обратиться к docs: https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/output-theming.md
Там предложен вариант: $this->theme->getUrl('img/logo.gif');
Ок. пробую. ```The "baseUrl" property must be set.```
ок. иду в конфиг компонента view и **что ему указывать**? указал как в примере /themes/basic/assets/, но этот путь ведет к site.ru/themes/basic/assets/ а должен к site.ru/assets/6ab6f6/img/logo.gif

короче в layout.php добавил 
```
$asset = \app\themes\basic\AppAsset::register($this);
$this->theme->baseUrl = $asset->baseUrl;
$this->theme->basePath = $asset->basePath;
```

и в layout ошибка  ```The "baseUrl" property must be set.``` исчезла. 

но т.к. layout отрабатывает после контроллеров, то это не решение. в них $this->theme снова пустые.

Что мне делать? делать отдельно еще одну копию img не вариант как то

**Comment by samdark** [comment]
Идти на форум http://yiiframework.ru/. Баг-трекер для баг-репортов.
