### ISSUE TITLE
Yii2 advanced app multiple front-ends (layers)

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2#9526]
Yii2 advanced app multiple front-ends (layers)

It occurred to me an idea to have only one back-end with multiple front -ends .

I keep my back end with all heavy logic , single , for any customer , for example, a CMS product, and each front would be isolated (url ) and have six themes , assets , controls , views , etc.

In a way that probably reflects in some capacity of front ends complete isolation between them.

What do you think of this?

**Comment by dynasource** [comment]
perhabs this discussion is something you are looking for
https://github.com/yiisoft/yii2/issues/4771#issuecomment-52934777

**Comment by samdark** [comment]
I think this is a forum topic.
