### ISSUE TITLE
Pass parameters to asset publish file

### ISSUE THREAD

**Issue by tongtoanbs** [yiisoft/yii2#9527]
I wanna pass parameters to the file that I'm gonna publish through asset, is there anyway I can archive it?

Example: test.php
```php
<?php
echo $var;
```
And then pass the variable `$var = "Hello World";` through `Yii::$app->assetManager->publish('test.php')`

Is this porsible to do it?

**Comment by klimov-paul** [comment]
@tongtoanbs, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
