### ISSUE TITLE
Date format "Y-m-t" returning "Y-m-"

### ISSUE THREAD

**Issue by khotim** [yiisoft/yii2#9529]
as described in [official doc Formatter for `asDate()`] (http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#asDate%28%29-detail):

`Alternatively this can be a string prefixed with php: representing a format that can be recognized by the PHP date()-function.`

so i assumed it's safed to use whatever format available at [php official doc for `date()`] (http://php.net/manual/en/function.date.php).

but when i tried to get last date with :
``` html+php
Yii::$app->formatter->asDate('2015-02', 'php:Y-m-t')
```
it returned `2015-02-` instead of `2015-02-28` (as returned by php `date()` function).
it also returned the same for full date input `2015-02-01`.

**Comment by cebe** [comment]
the format of `t` for PHP date function is not supported by intl so we can not use it to display i18n formatted date. If you simply need a date in format `Y-m-d` you can just use date() function. there is no benefit in using the formatter for this.
