### ISSUE TITLE
Support for Google App Engine

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii2#953]
Google App Engine now supports PHP. We should check if Yii can run on it and may consider providing some extensions to support specific GAE features such as task queues.

**Comment by TurtleWolf** [comment]
I'm still having issues launching Yii2 on App Engine... are there any tutorials or a walk through that would elaborate on the process.  I am relatively knew to all 3, Yii, App Engine and servers in general, so a real step by step or even a video would be awesome.

**Comment by TurtleWolf** [comment]
Maybe I'm just being a cheapskate.. Are you using a Compute Engine with this method? I thought I'd try installing a different PHP framework and I have Joomla running at fat-cow already, that I'll probably need to move to App Engine anyways. So in preparing to tackle the transition, I found Google's tutorial on installing it, but I noticed they are using the compute engine. https://cloud.google.com/compute/docs/tutorials/setup-joomla

**Comment by samdark** [comment]
It's not as straightforward as just "installing". Environment is pretty different from common Linux, PHP, Apache, MySQL.

**Comment by dbd5** [comment]
@samdark have you arrived at any conclusions in your test of Yii2 on GAE?
This seems to be very interesting considering the potentials but there doesn't seem to be any documentation of anyone's efforts in a way that tracks the issues and gives the Yii2 community an opportunity to resolve them. How can we put community effort behind this?

**Comment by samdark** [comment]
Nope. It was long time ago and I haven't finished it that time.

**Comment by masiorama** [comment]
Is there any plan to add this feature in the near future?
Is it possibile to have a list of the bottlenecks to get a working deploy in order to try to dig a bit?

**Comment by dbd5** [comment]
@masiorama, @samdark - It appears that the challenge from Google's point of view is to eliminate any dependency on unsupported PHP functions or in our case the use of such PHP functions by the YII framework (Disclaimer: I'm not an expert)

Here's a summary of unsupported PHP features according to Google: -

DISABLED FUNCTIONS

Either for security reasons, or for compatibility with Google App Engine execution environment, some PHP functions have been disabled. Some of these functions can be explicitly re-enabled in the php.ini file for your application.

Permanently disabled functions

The following functions have been permanently disabled in Google App Engine:
disk_free_space()
disk_total_space()
diskfreespace()
escapeshellarg() and escapeshellcmd()
exec()
highlight_file()
lchgrp(), lchown(), link(), and symlink()
passthru()
pclose() and popen()
proc_close(), prog_get_status(), proc_nice(), proc_open(), and proc_terminate()
set_time_limit()
shell_exec()
show_source()
system()

Google App Engine does not include the pcntl module, and thus the functions provided by pcntl are not available to PHP programs running in Google App Engine.

Partially restricted functions

The Google App Engine for PHP runtime does not support the /e pattern modifier of the preg_replace() andmb_ereg_replace() functions. See the PREG_REPLACE_EVAL documentation for the deprecation notice and an example of how to update your code to use preg_replace_callback() instead.

Disabled stream transports

The following stream transports have been disabled.
ssl
sslv2
sslv3
tcp
tls
udg
udp
unix

See details here https://cloud.google.com/appengine/docs/php/

I think it will be worth it to develop wrappers for any of these features that implements the required function without breaking compatibility with GAE platform. The ability to scale load at Google scale alone is worth it. (Google: Some of the world’s most popular web services are built on our platform. You can scale up to 7 billion requests per day and automatically scale down when traffic subsides. See details here https://cloud.google.com/appengine/)

For my part, I will contribute whatever is within my ability to support any community effort around this. I think what is required is someone to lead the effort with enough knowledge of exactly what needs to be done.

Regards,

Adam

**Comment by zinzinday** [comment]
i will try Google Cloud and test it )

**Comment by cebe** [comment]
as far as I see these functions should not cause any problems as they are if at all only used in very specific parts of the frameworks functionality.

**Comment by razvanphp** [comment]
Any news on this? Cloud seems to be the future.

Any solution for the obvious problems like asset publishing and runtime directory?

I think google offers custom logging API.

**Comment by samdark** [comment]
Haven't looked at it anymore but it seems there's assets component available: 
https://github.com/postor/yii2-for-sae/blob/master/SaeAssetManager.php.

The rest are logs and cache for which non-file backends are already available.

Overall, I think GAE support could be released as application template.

**Comment by razvanphp** [comment]
I just tried it with the development server, and it seems to work, but the path is wrongly generated because of the way `$_SERVER` values are set in this environment.

Documentation: https://cloud.google.com/appengine/docs/php/config/appconfig#Updated_PHP_SELF

More precise, for this config:
```
application: myapp
version: alpha-001
runtime: php55
api_version: 1

handlers:
- url: /assets
  static_dir: web/assets

- url: /.*
  script: web/index.php
```

we get:
```
'REQUEST_URI' => string '/'
'PHP_SELF' => string '/web/index.php'
'PATH_INFO' => string '/'
'SCRIPT_FILENAME' => string '/usr/share/nginx/current/web/index.php'
'SCRIPT_NAME' => string '/web/index.php'
```

while on the normal nxginx we have:
```
'REQUEST_URI' => string '/'
'PHP_SELF' => string '/index.php'
'SCRIPT_FILENAME' => string '/usr/share/nginx/current/web/index.php'
'SCRIPT_NAME' => string '/index.php'
```

To fix this, one needs to set this into the config:
```
'request' => [
    'scriptUrl' => '/index.php',
],
```

I don't know if this limitation should also be addressed in google cloud, like setting the root of htdocs, but from yii point of view I think we are fine with this solution, right?

**Comment by samdark** [comment]
Yes.

**Comment by razvanphp** [comment]
For the assets part, google supports writing files using stream wrapper `gs://bucket_name/desired_object_name`.

As most of the filesystem access functions are mapped, I think the original yii2 AssetManager class should work, I will try it and come back with needed changes.

Documentation: https://cloud.google.com/appengine/docs/php/googlestorage/

Thank you!

**Comment by iadj** [comment]
Any news on this? I've been looking into building a Yii2 app with autoscaling through Google App Engine (or Amazon Elastic Beanstalk), but it doesn't appear to be working out of the box as of yet.

**Comment by samdark** [comment]
@iadj not really. Haven't touched it. If you want to dig into it, feel free to do so.

**Comment by iadj** [comment]
@samdark Managed to get Yii2 working perfectly with Google Cloud using a Managed Compute Instance and a Load Balancer simply by configuring Redis for both the Session and Cache management!

**Comment by samdark** [comment]
That's good news. Can you share something like a manual on how to do so? I bet it would be interesting for many people and it worth including into https://github.com/samdark/yii2-cookbook

**Comment by iadj** [comment]
@samdark Yes absolutely! Will write up a small guide this week.

**Comment by samdark** [comment]
Thank you!

**Comment by iadj** [comment]
@samdark https://github.com/samdark/yii2-cookbook/pull/114

**Comment by samdark** [comment]
Nice! I'll close this issue. Would link to the cookbook later from the guide on performance.

**Comment by abra2015** [comment]
The directory is not writable by the Web process: /base/data/home/apps/some_adress/frontend/web/assets

и что делать?

**Comment by SilverFire** [comment]
[Можно попробовать погуглить](https://www.google.com.ua/search?q=the+directory+is+not+writable+by+the+web+process+web/assets)

**Comment by samdark** [comment]
Раньше вообще нельзя было писать. Теперь вроде можно: https://cloud.google.com/appengine/docs/php/googlestorage/

**Comment by earlcherry** [comment]
А как разрешить запись? Ссылка выше на запись в облако, а YII сам пишет к себе в папку кеш и т.п.

**Comment by samdark** [comment]
Сам к себе не пишет, если не использовать файловый кеш и файловые логи.

**Comment by earlcherry** [comment]
А как можно отключить их?

**Comment by samdark** [comment]
Это всё есть в документации. Читайте.

**Comment by earlcherry** [comment]
Затупил, разобрался. Сейчас встрял на том, что не получается применить миграции в cloud sql. Из cloud shell недоступен pdo_mysql,а php,ini работает только для инстанса. Может кто то знает как это делается?

**Comment by iadj** [comment]
Guys can we please talk English if the OP is written in English?:

**Comment by samdark** [comment]
@iadj translated.
