### ISSUE TITLE
How come $query can change pageSize in ActiveDataProvider

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#9530]
Hey. Strange issue:

    $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'defaultPageSize' => 20,
                'pageSize' => 20,
            ],
        ]);

If I add this to query:

    $query->innerJoin('country_manager', '`country_manager`.`country_id` = `user`.`country_id`');

Suddenly page size is 10.

How come ?

**Comment by samdark** [comment]
What's URL of the page?

**Comment by BenasPaulikas** [comment]
I don't have URL since It's not deployed to public :/ I'm attaching same table image
![github](https://cloud.githubusercontent.com/assets/6473565/9523933/fd1d299e-4ce4-11e5-8ba4-1dc96a0e9842.png)

**Comment by samdark** [comment]
I'm asking URL to check params, not to see it in action.

**Comment by cebe** [comment]
the innerJoin may produce duplicate rows which are afterwards filtered by active record. If you join, make sure you get one row per record.
