### ISSUE TITLE
DbMessageSource::CACHE_KEY_PREFIX is not used anywhere

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#9533]
`__CLASS__` is used as a prefix instead (not that there's much of a difference, since you can't change either through configuration).

**Comment by cebe** [comment]
caused by https://github.com/yiisoft/yii2/commit/d48ef4198ebd5e5107335091e94f4910384c3af0
constant should be removed.

**Comment by SamMousa** [comment]
@cebe Can this be closed?
Since it has been deprecated in code having this issue open just adds clutter.

**Comment by nkovacs** [comment]
This has been removed in the 2.1 branch: https://github.com/yiisoft/yii2/commit/b05e01b2d4b7252a41935f1e59c132de4fc73330
Closing.
