### ISSUE TITLE
Move DbMessageSource cache key generation into a static function

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#9534]
I'd like to invalidate the cache when an administrator edits a translation. I could hardcode [this](https://github.com/yiisoft/yii2/blob/2.0.6/framework/i18n/DbMessageSource.php#L119) into my app, but having a static function in DbMessageSource would be nicer.

I don't want to use a cache dependency, since I know exactly what and when I need to delete from the cache.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
