### ISSUE TITLE
The placeholder attribute doesn't work when I use the yii2 captcha.

### ISSUE THREAD

**Issue by tianyirenjian** [yiisoft/yii2#9536]
Here is the code:

```
<div class="row" style="margin-bottom:8px;">
    <div class="col-md-12">
        <?= $form->field($model, 'verifyCode',["inputOptions"=>["placeholder"=>"something"]])->widget(Captcha::className(),['imageOptions'=>["title"=>Yii::t("backend","Click to refresh verifyCode"),'style'=>'max-width:200px;max-height:50px;']]) ?>
    </div>
</div>
```
The placeholder will not show.When I remove  `->widget...` The placeholder work again.

-----------
我用验证码的时候，placeholder属性无法正常的显示。我删除后面的``->widget……`这段代码后，placeholder就能正常的显示了。

**Comment by cebe** [comment]
that is because inputOptions only work on the input field created by ActiveField. If you use a widget, you have to configure the widget in a way so that it has the place holder. For Captcha that would be done by configuring the `options` property of the Captcha widget.

**Comment by tianyirenjian** [comment]
Thank you!

**Comment by mohammad1381** [comment]
I use `options `but still `placeholder `does not work.

**Comment by dynasource** [comment]
show us your full code snippet
