### ISSUE TITLE
Migration. Аdd the field type integer[] and the like.

### ISSUE THREAD

**Issue by jumper423** [yiisoft/yii2#9539]
Migration. Аdd the field type integer[] and the like.

**Comment by samdark** [comment]
Please elaborate.

**Comment by jumper423** [comment]
For example in PosrgreSQL have field types integer[], text[] or text[][]. To do so they could be added through Migration. 

Instead 

```php
$this->addColumn('{{%table}}', 'field', 'integer[][]');
```

To do for example

```php
$this->addColumn('{{%table}}', 'field', $this->integer()->dimension(2));
```

**Comment by samdark** [comment]
There's no support for many databases we have implementations for.

**Comment by jumper423** [comment]
Displays error if there is no such type of the field in the database.

**Comment by samdark** [comment]
There are endless custom types for each specific database. I'm not sure we should support arrays and sub-arrays while not supporting everything else.

**Comment by cebe** [comment]
ColumnSchemaBuilder is only useful for creating database independend schema defintion. imo it does not make sense to include specific syntax types in it.

**Comment by jumper423** [comment]
I think You know better.
