### ISSUE TITLE
Out of Memory ErrorException not catchable

### ISSUE THREAD

**Issue by WJRovers** [yiisoft/yii2#9542]
The error in app.log
```2015-08-28 12:23:38 [127.0.0.1][1][-][error][yii\base\ErrorException:1] exception 'yii\base\ErrorException' with message 'Out of memory (allocated 1501560832) (tried to allocate 36 bytes)' in C:\xampp\htdocs\application\vendor\yiisoft\yii2-debug\LogTarget.php:109```

Debug is off

```php 
defined('YII_DEBUG') or define('YII_DEBUG', false);
```

The code that leads to a memory exception
```php
public static function doNotify() {
        try{
            //Prepare
            self::initNotify(); //contains: ini_set('memory_limit', '128M');
            //This function causes (forced) memory exception
            self::runNotify();
            //End if was successfull
            self::endNotify();
        }catch(ErrorException $e){
            //End if was unsuccesfull
            self::endNotify('Failed');
            //Log Error
            Yii::error(VarDumper::dumpAsString($e));
        }
    }
```

As [documentation](http://www.yiiframework.com/doc-2.0/yii-base-errorhandler.html#$memoryReserveSize-detail) says the ErrorHandler has a reserve memory in case there is a memory fatal error.
I'm seeing Yii log the exception as it is showing in app.log. 
However I want it to at least run the self::endNotify aswell. My guess is that it has not enough memory at this point to do anything but log as this is burried deep inside the ErrorHandler->FatalError() functionality.

Basicly I want my program to give feedback via a custom action when the FatalError occurs; how do I do this? As it seems to be fully ignoring the catch.

**Comment by samdark** [comment]
Fatal errors are not catchable in general in PHP.

**Comment by cebe** [comment]
Memory limit error is fatal so it is not catchable. You could extend the ErrorHandler to do something in `handleFatalError()` method but that part is already out of execution context...
