### ISSUE TITLE
Attaching columns from junction table as properties for child models.

### ISSUE THREAD

**Issue by alexinator1** [yiisoft/yii2#9544]
Hello, I didn't find a way to access values from additional columns(apart from keys) of junction table using
ActiveRecord. And I haven't find similar issue, if I missed it, please point me.
 
So what I could is: what if we add additional input param to viaTable function which will specify columns of pivot table should be attached and populated as properties of child models.

Example:
![structure](https://cloud.githubusercontent.com/assets/1975274/9558163/13a21ec0-4deb-11e5-800d-46d2ba687ff8.png)

So we can have something like this:
```php
class Room extends ActiveRecord
{
...
    public function getMembers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])
            ->viaTable('user_room', ['room_id' => 'id'], function(){}, ['user_role', 'entered_at'] );
    }
}

class User extends ActiveRecord
{
    public $user_role;
    public $entered_at;
    .......
}
```

So when we call 

```php
$users = $room->members;
```
We get 

```php
// $users 
[
  0 => [
     'id' => 1
     'name'=>'John', 
     ...
     'user_role' => 'Admin',
     'entered_at' => '2015-07-07 15:40'
  ],
  1 => [
     'id' => 2
     'name'=>'Jimm', 
     ...
     'user_role' => 'Regular',
     'entered_at' => '2015-08-08 12:30'
  ],
  ....
]
```
Does that make sense?

My apologies if such question have already been discussed and I missed it.

Thanks.

**Comment by klimov-paul** [comment]
@alexinator1, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
