### ISSUE TITLE
Validator replacement/configuration and $builtInValidators

### ISSUE THREAD

**Issue by e-frank** [yiisoft/yii2#9547]
In my extension, i want to 
1. add a new shortname '```datetime```' for my custom ```DatetimeValidator```
2. set the default ```$format``` value for the ```DateValidator```

**problem:**
i can't change the ```yii\validators\Validator``` class to my own neither in configuration, nor in bootstrap.

within bootstrap, only replacing the ```DateValidator``` with DI works like:
```
\Yii::$container->set('yii\validators\DateValidator', [
	'class'  => 'yii\validators\DateValidator',
	'format' => 'yyyy-M-d H:m:s',
]);
``` 

working solution, in my extensions bootstrap:
```
class DataBootstrap implements BootstrapInterface
{
    public function bootstrap($app)
    {
    	\yii\validators\Validator::$builtInValidators['datetime'] = [
    		'class'  => 'yii\validators\DateValidator',
    		'format' => 'yyyy-M-d H:m:s',
    	];

    	\yii\validators\Validator::$builtInValidators['date'] = [
    		'class'  => 'yii\validators\DateValidator',
    		'format' => 'yyyy-M-d',
    	];
    }
}
```

i expected such options to be configurable.

BTW:
i don't get what all the internationalisation is about with validators, since i always need all values in db-format.
on client-side, i usually have some javascript to do calculations, so number and dateformats again have to be stored in 'computer' format.
**Further, ```datetime``` respects intl, ```number``` does not.**

IMHO, the only reason for conversion is displaying values in user friendly format. so in webforms, why not implement (display-)input in user-friendly format linked to hidden input in db/iso-format by design?

**Comment by SilverFire** [comment]
Yeah, changing static parameter `\yii\validators\Validator` is the only solution for you now.

But usually it's fine to write something like this:

```php
public function rules() 
{
    return [
        [['foo'], BarValidator::class],
    ];
}
```

I'm closing the issue since it is not supported by community as required and the original problem could be already solved by different ways.
