### ISSUE TITLE
Have you considered the DatetimeBehavior?

### ISSUE THREAD

**Issue by vistart** [yiisoft/yii2#9550]
Have you considered the DatetimeBehavior?
Sometimes we need to store the date & time string directly, and store the time which is earlier than 1970-1-1 00:00:00 or later than the maximum of unix timestamp.
See also https://github.com/vistart/yii2/blob/master/framework/behaviors/DatetimeBehavior.php

**Comment by freezy-sk** [comment]
There is no need for this because it can be done with `TimestampBehavior`.
You just need to define it's `value` option as lambda function.

```
[
    'class' => TimestampBehavior::className(),
    'value' => function($event) {
        return date('Y-m-d H:i:s');
    },
],
```
