### ISSUE TITLE
Validating disabled

### ISSUE THREAD

**Issue by andrewblake1** [yiisoft/yii2#9551]
Re: closed issue https://github.com/yiisoft/yii2/issues/7341 apologies for opening a new issue but I see another more recent non-responded comment (May) supporting @nkovacs case and being closed wasn't sure if it was being monitored any more.

A quick google search of "validate disabled" shows yiis approach is non typical behaviour e.g. jQuery:
https://forum.jquery.com/topic/jquery-jquery-validate-validating-disabled-inputs

http://www.w3schools.com/tags/att_input_disabled.asp indicates that disabled attribute is often controlled by javascript.

If a check box for a hotel booking system says "I want a breakfast", it makes sense to enable a select which forces the user to choose what e.g. 'cooked', 'continental' (defaulting wouldn't be appropriate as you want to force a choice) hence 'required' - but only if that check box is checked. Currently client validation fails if the checkbox isn't checked and the select is disabled. This is simplified - could use a non required enabled select without a checkbox.

I can't imagine a use case for validating disabled inputs.

> Even if the input is not submitted, it will still be validated on the server.

Not necessarily. In above I would only create, load, and validate the Breakfast model if the checkbox is posted.

> If a field is disabled, i.e. the user should not be able to change it, you have to remove it from the scenario/validation rules. otherwise it is possible to edit the html, enable the field and change its value

The user should be able to change it - after an an event handler enables it. If just there as a label then yes, remove from scenario/validation rules. Two different situations. Neither of which require validating disabled, and one of which breaks when you do.

Like @nkovacs I will use remove and add.

**Comment by df2** [comment]
Look at the `when` and specifically `whenClient` options of validators. You do not need to manually add and remove attributes!

**Comment by andrewblake1** [comment]
Thanks. Will look now.

**Comment by df2** [comment]
No probs.

**Comment by andrewblake1** [comment]
Yes, thanks @df2 df2, will work and may be easiest for some use cases. I will probably use this in some situations now that I am aware of it.

IMHO, validation of disabled attributes in client is unusual - based on things like jQuery but perhaps there is a good reason in Yii2 - I don't yet understand the reasoning offered in the issue linked above.

My use case is complex - the example I put isn't it. For me I will need to add whenClient to quite a few rules simply to check for disabled attribute in the element. This will mean duplicating the efforts of my client code that adds the disabled attribute. For me it is easier to apply an overall remedy like:

```
$this->registerJs('$("form").on("beforeValidate", beforeValidate)');
```
```
beforeValidate = function () {
    var $input, $form = $('form');
        // restore any validation attributes previously shifted out
        $('[data-yiiActiveForm]', $form).each(function() {
            $input = $(this);
            $form.yiiActiveForm('add', $input.data('yiiActiveForm'));
            $input.removeData('yiiActiveForm').removeAttr('data-yiiActiveForm');
        });
        // shift validation attribute data from form to attribute for currently disabled inputs
        $.each($form.yiiActiveForm('data').attributes, function() {
            $input = $('#' + this.id, $form);
            if ($input.is(':disabled')) {
                $input.data('yiiActiveForm', $form.yiiActiveForm('remove', this.id)).attr('data-yiiActiveForm', true);
            }
        });
        return true;
     }
```

**Comment by df2** [comment]
Yeah, that will work. I suppose where that wouldn't work is where you hide an element rather than disabling it. Other than that you could use prototypes to monkey patch the Yii JS validators and do the disabled check there. 

```JS
var oldValidateAttribute = $.fn.yiiActiveForm.Constructor.prototype.validateAttribute;
$.fn.modal.Constructor.prototype.validateAttribute = function ($form, attribute, forceValidate, validationDelay) {
    //Check if input is disabled and exit here if so
    oldValidateAttribute.apply(this);
}
```

**Comment by SamMousa** [comment]
It makes sense that if I disable a field client side it does not get validated by Yii right?

I am especially unclear on the arguments against the alternative (and imo more intuitive) behavior.
Why would we ever want to validate a disabled input with client side validation?
1. A user cannot edit it, client validation is to improve UX.
2. If a user manually edits the page client validation is irrelevant.

Furthermore HTML5 does not validate disabled inputs AFAIK, so principle of least surprise suggests Yii2 does the same...
