### ISSUE TITLE
Git workflow. Composer update or composer install?

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2#9553]
Here https://github.com/rugabarbo/yii2/blob/master/docs/internals/git-workflow.md is written:

> run composer update to install dependencies

But if we run **composer update** composer will update composer.lock which is under git. It may be more correct to use **composer install** for contributing? Or not?

**Comment by samdark** [comment]
Nope. It's correct in the doc. Pull requsets should be based on current master code.
