### ISSUE TITLE
Yii debug enhancement

### ISSUE THREAD

**Issue by zakrot** [yiisoft/yii2#9555]
hi
I worked with cakephp ,but recently I have switched to Yii.
Yii is Great , but its debug is unbearable!
in cakephp app does not stop running while notice or warning occuring.
you can see cakephp notice debug bellow:
![cakephp3_debug](https://cloud.githubusercontent.com/assets/6356030/9572371/58ad4b86-4fc4-11e5-84c1-c2338694e377.png)

By clicking on error title (warning or notice) , you can see more details:
![cakephp3_debug_click_the_code](https://cloud.githubusercontent.com/assets/6356030/9575673/b0d9ab2a-4fe6-11e5-8688-3182942b3075.png)

is there any chance that add this kind of debug mode in future releases?
Thank you for your attention.

**Comment by samdark** [comment]
No. Notice in Yii is considered a really serious thing that should stop the app. It won't be changed.

**Comment by cebe** [comment]
you can set php error_reporting to skip notices but that is not recommended.

**Comment by zakrot** [comment]
Is there any way to enhance Yii Debugger and insert Notice in my own projects?
For example changing current plugin or writing new plugin.

**Comment by cebe** [comment]
you can extend the ErrorHandler class and configure the application component.
