### ISSUE TITLE
Add beforePrepare event in ActiveQuery

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#9558]
It would be great if an event could be added to ActiveQuery to allow for preprocessing to be done before a query is prepared.

This would allow modifying the query through behaviors or other event handlers..

**Comment by cebe** [comment]
can you give an example use case for how you would modify the query?

**Comment by SamMousa** [comment]
Yes, in this case i'm trying to implement: https://github.com/yiisoft/yii2/issues/8316 through a behavior.

What I do in my behavior is add a method "withField" to the behavior, the behavior is then added to ActiveQuery.
When I call withField i'm actually (indirectly) adding a subquery to the select clause; however this might not be obvious to the user.
So suppose my withField does some processing and then updates the select, the following code would not behave intuitively:

$query->withField('test')->select('*')  --> select *
$query->select(*)->withField('test') --> select (select something from something limit 1) as test

I'd like to be able to keep my own list in the behavior and only update the select when the query actually gets prepared.

In any case, ideally I do not want to extend the ActiveQuery class since that would force anyone who wants to use my feature / extensions to not use other extensions that do the same (since we don't have multiple inheritance). 
Combining Yii2 DI container with behaviors however would allow for proper integration were it not for the lack of events or other methods of changing the behavior of an owner from within a behavior.

**Comment by SamMousa** [comment]
Hmm, seems a behavior approach is not ideal. 
VirtualFields should instead just be supported by the core ;-)
