### ISSUE TITLE
Ability to remove URL params using Url::current()

### ISSUE THREAD

**Issue by usualdesigner** [yiisoft/yii2#9560]
Looks like there is no ability to remove some of the url params from the current url. In accordance with https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseUrl.php#L382 there is ability to add or replace some of the params only. Any suggestions?

**Comment by df2** [comment]
You can set them to `null`.
```php
Url::current(['sort' => 'az', '_pjax' => null])
```

**Comment by usualdesigner** [comment]
@df2 what about replace exists value? (not merge with the exists)

**Comment by df2** [comment]
@usualdesigner 
`sort` will be replaced in the above example, and `_pjax` will be removed.
