### ISSUE TITLE
\yii\helpers\Html does not properly process JSON data assigned to a HTML attribute

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#9564]
I was trying to pass in JSON object in HTML attribute to be later used in JS with help of $.parseJSON:

```php
Html::tag("span", "", ["data-options" => '{"create":true}']);
```

The resulting HTML code looks like that:

```html
<span data-options="{"create":true}"></span>
```

jQuery is not able to understand that - it looks like quotes are intermixing here. Using JsExpression also didn't yield any different result.

I think ```\yii\helpers\Html``` should be able to use single quotes instead of double quotes to quote attribute values in specific circumstances.

Yii 2.0.6

**Comment by avinashz** [comment]
@dryu you should try [renderTagAttributes() ](http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#renderTagAttributes()-detail)

It should work for you.

**Comment by dryu** [comment]
I don't see how using ```renderTagAttributes()``` helps.

Checked the code, it looks like it renders the attributes consistently wrapping those in double quotes and encoding the value`:

```php
$html .= " $name=\"" . static::encode(implode(' ', $value)) . '"';
```

**Comment by dryu** [comment]
Ah, figured it out from the source code. I should pass JSON structure as an array and then it will be wrapped with the single quotes. 

Thanks for the hint.
