### ISSUE TITLE
Where is qiang xue?

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#9568]
Who know, why qiang xue is not active so long?

**Comment by klimov-paul** [comment]
People personal life is a private matter and does not concern you.
GitHub is a bugtracking - not a tabloid.

**Comment by dataskills** [comment]
dayum

On Wed, Sep 2, 2015 at 1:31 AM, Paul Klimov <notifications@github.com>
wrote:

> Closed #9568 <https://github.com/yiisoft/yii2/issues/9568>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii2/issues/9568#event-398659580>.
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by dataskills** [comment]
My reply was a mistake, please disregard.

On Wed, Sep 2, 2015 at 10:20 AM, J. Bundy <dataskills@gmail.com> wrote:

> dayum
>
> On Wed, Sep 2, 2015 at 1:31 AM, Paul Klimov <notifications@github.com>
> wrote:
>
>> Closed #9568 <https://github.com/yiisoft/yii2/issues/9568>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/yiisoft/yii2/issues/9568#event-398659580>.
>>
>
>
>
> --
> ------------------------
> J. Bundy
> dataskills@gmail.com
> +1.206.406.1534
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by derekisbusy** [comment]
https://github.com/qiangxue?tab=activity
