### ISSUE TITLE
GridView numeric column names issue

### ISSUE THREAD

**Issue by john-d-o-e** [yiisoft/yii2#9571]
When you use numeric columns in GridView widget,  php warning occured.
Probably need to change if condition in GridView.php line 525
![bug](https://cloud.githubusercontent.com/assets/11157933/9626582/51538e8c-5167-11e5-90d0-4868a155dbd1.jpg)

**Comment by Alex-Code** [comment]
Can you show your view code.

**Comment by john-d-o-e** [comment]
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => $columnsForDataProvider,
]);
?>
where
$columnsForDataProvider =  [
  ['class' => 'yii\grid\SerialColumn'],
  1,
  2,
  3,
];

**Comment by Alex-Code** [comment]
You need to specify column names, Yii won't know what to show when it sees an ambiguous number.

```php
$columnsForDataProvider = [
  ['class' => 'yii\grid\SerialColumn'],
  'col1',
  'col2',
  'col3',
];
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => $columnsForDataProvider,
]);
?>
```

**Comment by mdmunir** [comment]
I'am unsure. try this
```php
$columnsForDataProvider =  [
    ['class' => 'yii\grid\SerialColumn'],
    '1',
    '2',
    '3',
];
```

**Comment by john-d-o-e** [comment]
I'm uploading and showing csv, and I want to show it as it is. Sometimes columns are numbers, why yii can't show column names which are numbers?
Actually I already fixed it
```
  $columnsForDataProvider = array_map(function($elem) {
                    return (string)$elem;
                }, $columns);
```
