### ISSUE TITLE
Migration bug Timestamp

### ISSUE THREAD

**Issue by ventayol** [yiisoft/yii2#9574]
There's a related bug that someone has already closed (https://github.com/yiisoft/yii2/issues/8080) but I think it's a yii bug.

I've the following migration:

        $this->createTable('sector', [
            'id' => Schema::TYPE_PK,
            'name_i18' => Schema::TYPE_INTEGER. ' NOT NULL',
            'created_at' => Schema::TYPE_TIMESTAMP,
            'updated_at' => Schema::TYPE_TIMESTAMP
        ], $tableOptions);

And on the mysql server it's created like this:

![screen shot 2015-09-02 at 15 51 51](https://cloud.githubusercontent.com/assets/1505998/9632976/929b9c2c-518a-11e5-9a11-09e18be541ad.png)
which is completely wrong as the `created_at` field is updated every time the row is updated (I already have the TimeStampBehaivour for this).

I've done a test running the following SQL directly on MySQL:

    CREATE TABLE test (created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT '0000-00-00');

and here you have the result:

<img width="894" alt="screen shot 2015-09-02 at 15 55 45" src="https://cloud.githubusercontent.com/assets/1505998/9633072/1e4105f0-518b-11e5-8796-1e30c911a8b2.png">
So it really doesn't look like a MySQL error.

**Comment by yaKostin** [comment]
I have this bug too.

**Comment by alchimik** [comment]
https://github.com/yiisoft/yii2/issues/8080#issuecomment-92953426

directly on MySQL:
``` sql 
CREATE TABLE test (
    created_at TIMESTAMP, 
    updated_at TIMESTAMP
);

show create table test;
```

```
CREATE TABLE `test` (
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
)
```

**Comment by ventayol** [comment]
@alchimik 
Any idea on how to avoid this problem?

**Comment by alchimik** [comment]
set default value explicitly:

``` sql
CREATE TABLE test (
    created_at TIMESTAMP NULL DEFAULT NULL, 
    updated_at TIMESTAMP NULL DEFAULT NULL
);

show create table test;
```
```
CREATE TABLE `test` (
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
);
```

something like:
``` php
$this->createTable('sector', [
    'id' => Schema::TYPE_PK,
    'name_i18' => Schema::TYPE_INTEGER. ' NOT NULL',
    'created_at' => Schema::TYPE_TIMESTAMP . ' NULL DEFAULT NULL ',
    'updated_at' => Schema::TYPE_TIMESTAMP .  . ' NULL DEFAULT NULL '
], $tableOptions);
```

**Comment by ventayol** [comment]
That makes sense, but maybe Yii should set the `'NULL DEFAULT NULL'` if no default is specified in the `createTable`.
As a lot of people will be using MySQL with Yii it makes more sense to avoid these problems to future users (or at least put some note somewhere).
We have messed up a big project because of this problem.

**Comment by githubjeka** [comment]
**Code to repoduce:**
```php
class m160321_163840_test extends Migration
{
    public function up()
    {
        $this->createTable('{{%test}}', [
            'id' => $this->primaryKey(),
            'created_at' => $this->timestamp()->defaultValue(null),
            'updated_at' => $this->timestamp()->defaultValue(null),
        ]);
    }

    public function down()
    {
        $this->dropTable('{{%form_builder}}');
    }
}
```

**Comment by cebe** [comment]
@githubjeka thanks. But I do not think this is a yii issue, see: https://github.com/yiisoft/yii2/issues/9343#issuecomment-188925372

**Comment by githubjeka** [comment]
When I used ` 'created_at' => $this->timestamp()->defaultValue(null),` I expect from mysql

```sql
CREATE TABLE t (
  created_at TIMESTAMP NULL DEFAULT NULL,
);
```

**Comment by cebe** [comment]
Okay, now I see, this test fails:

```diff
diff --git a/tests/framework/db/ColumnSchemaBuilderTest.php b/tests/framework/db/ColumnSchemaBuilderTest.php
index 1f79721..72448a8 100644
--- a/tests/framework/db/ColumnSchemaBuilderTest.php
+++ b/tests/framework/db/ColumnSchemaBuilderTest.php
@@ -66,4 +66,10 @@ class ColumnSchemaBuilderTest extends TestCase
 
         self::assertEquals($expected, $builder->__toString());
     }
+
+    public function testMySQLTimestamp()
+    {
+        $timestampColumn = (string) $this->getColumnSchemaBuilder(Schema::TYPE_TIMESTAMP)->defaultValue(null);
+        $this->assertEquals('TIMESTAMP NULL DEFAULT NULL', $timestampColumn);
+    }
 }
```
