### ISSUE TITLE
Add limit 1 to improve performance of BaseActiveRecord::findOne()

### ISSUE THREAD

**Issue by hightman** [yiisoft/yii2#9578]
I have noticed manual annotation, but in `BaseActiveRecord::findOne()` there is no chance to add `limit (1)` unless override this method.

Lots of time we can not construct an unqiue condition (such as just get the first record after sorting), it cause performance problem when granted call `findOne()`.

There is no reason to refuse such modifications.
```
    public static function findOne($condition)
    {    
        return static::findByCondition($condition)->limit(1)->one();
    } 
```

Further, we can optimize `Query::one()` as following.
```
    public function one($db = null)
    {
        $oldLimit = $this->limit;
        $result = $this->limit(1)->createCommand($db)->queryOne();
        $this->limit = $oldLimit;
        return $result;
    } 
```

**Comment by klimov-paul** [comment]
Duplicates #4348

**Comment by hightman** [comment]
Hello, my main point is to add `limit(1)` within `BaseActiveRecord::findOne()`, rather than the `Query::one()`.

Could you look into my content, completely unable to add a `limit (1)` to `findOne()`, it is a static method, unless overridden method.  This is entirely a trick.

@qiangxue @klimov-paul

**Comment by cebe** [comment]
findOne() is a shortcut for the very simple case. If you need anything more, you should use ::find()->limit(1)->one()

**Comment by hightman** [comment]
@cebe I certainly know that we can do so, I accept the implementation of `Query::one()` implementation, but it is difficult to accept not add limit(1) to `ActiveRecord::findOne()`.

**Comment by hightman** [comment]
And, I really do not know what harm with `limit(1)` in `findOne()`, internal `Query` object will not be reused forever.
