### ISSUE TITLE
Return Model with relashions (Restful API)

### ISSUE THREAD

**Issue by sergey-rud** [yiisoft/yii2#9588]
Hi all. I built few API using Yii2 and all works well, but I have one small issue.

Quest::find()
            ->with(['images', 'route'])
            ->all();

Return only Quest object as response, without images and route.

We can fix it:
Quest::find()
            ->with(['images', 'route'])
            ->asArray()
            ->all();
This response will contain quests with images and route. But it's a bad way, because using asArray() we lost some ActiveRecord features (eg, afterFind). 

So how we can solve this?

**Comment by sinus86** [comment]
I think your solution is the following public method: joinWith()
(http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#joinWith()-detail)

Please use forums for questions.

**Comment by sergey-rud** [comment]
Thanks for answer, and note about forum. But joinWith() returns the same endpoint response (JSON)  as  
Quest::find()
->with(['images', 'route'])
->all();

**Comment by sergey-rud** [comment]
Moved: 
http://www.yiiframework.com/forum/index.php/topic/67550-return-model-with-relashions-restful-api/
