### ISSUE TITLE
one() returns null if nothing found instead of a boolean false

### ISSUE THREAD

**Issue by realtebo** [yiisoft/yii2#9589]
I talk about this guide page: http://www.yiiframework.com/doc-2.0/yii-db-queryinterface.html#one%28%29-detail

It tells:" False is returned if the query results in nothing."

I've used one in this way
```
    $product = Product::find()->where(['internal_code' => $internal_code])->one();
    if ($product === false) {
                // create it as new
                $product = new Product();
                echo "Product $code NOT found <BR>";
    } else {
               \yii\helpers\VarDumper::dump($product,2,1);
    }
```

I expected a boolean `false` as documented, but I got that the `dump` is executed and it tells me that `$product` is `null`.

Am I doing something wrong, or is a mistake in the doc? I got no error and no warning at all.

**Comment by arogachev** [comment]
Because you are using `ActiveQuery`, it's documented [here](http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#one%28%29-detail).
