### ISSUE TITLE
FR: Open files in IDE from Exception traces

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9590]
![screenshot 1](https://cloud.githubusercontent.com/assets/125726/9661636/dd319d5a-525b-11e5-8686-4dfc9096a361.png)

Usecase:
- an error is thrown
- you get the stacktrace presented
- you see the files (and their code lines)
- I want to open this file in my IDE

Currently, I have to do my best to get the filename, because of disturbing collapsing.

Ideally, I would click on the filename and it would be opened automaticallly by my favorite browser.
If that is not possible (never digged into this), would love to see a button for  'copy filename to clipboard' so I have a optimal processes:
- click on button
- ctrl-o in IDE 

and there I go!

**Comment by samdark** [comment]
I think it should be possible to form a link IDE could understand. Saw that in Netbens docs years ago.

**Comment by dynasource** [comment]
hmm...
I see something over here https://pla.nette.org/en/how-open-files-in-ide-from-debugger

**Comment by dynasource** [comment]
something similar on this matter is to provide the file corresponding with the error. Look at this pic:
![screenshot 2](https://cloud.githubusercontent.com/assets/125726/9666035/0cad8306-5274-11e5-938b-9a6bf5cef1c6.png)

I would find it very useful to get the full path of the for dmn\yii2\components\relations\components\LinkActiveQuery so I can easily look in this file as its namespace does not give me enough info to get to its file fast enough

**Comment by SamMousa** [comment]
I think this is implemented and thus can be closed!
http://www.yiiframework.com/doc-2.0/ext-debug-index.html#open-files-in-ide

**Comment by dynasource** [comment]
not for exceptions

**Comment by SilverFire** [comment]
2 days ago thought that it will be good to do the same for exceptions :)

**Comment by samdark** [comment]
Implemented.
