### ISSUE TITLE
YUICompressor 2.4.8 fails on yii.validation.js

### ISSUE THREAD

**Issue by hofrob** [yiisoft/yii2#9591]
YUICompressor Version: 2.4.8
Yii Version 2.0.6
Command: `yuicompressor --type js yii.validation.js`

    [ERROR] in vendor/yiisoft/yii2/assets/yii.validation.js
      39:16:invalid property id

"boolean" is a reserved name and therefor invalid as a property id.

This affects efforts to minify the ValidationAsset for use in production environments.

Solution: Put the property [boolean](https://github.com/hofrob/yii2/blob/master/framework/assets/yii.validation.js#L39) in yii.validation.js under quotes.

**Comment by samdark** [comment]
Fixed.
