### ISSUE TITLE
Database type and version properties in \yii\db\Conection?

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#9592]
In [yii2-dynamic-ar](http://tom--.github.io/yii2-dynamic-ar/) we haven't found a clean way to discover a connection's database type and version. And I think anyone building an extension (or other reusable code) that depends on advanced DBMS features from more recent versions might face a similar problem.

For example, yii2-dynamic-ar can use Dynamic Columns if the DBMS is Maria 10.0+. It can use JSON if the DB is MySQL 5.7+. And it can use jsonb if it has PostgreSQL 9.4+. But it can't even see the difference between Maria and MySQL and it can't check versions at all.

Reading the version string from the database, parsing it and caching the result is possible but that's as appealing as branching on a parsed user agent string. (I don't like the idea, is what I'm saying.) I would prefer an application configuration that the developer is responsible for. But I don't know where it should go. \yii\db\Conection?

Any thoughts on this would be welcome.

**Comment by samdark** [comment]
Connection seems to be natural choice.

**Comment by klimov-paul** [comment]
Note, that there is already `\yii\db\Connection::driverName`.
