### ISSUE TITLE
yiiActiveForm not working when clientValidation or dynamic fields is OFF

### ISSUE THREAD

**Issue by bryglen** [yiisoft/yii2#9598]
I have a form that I add a form dynamically. so basically its a collection input, however I want to validate it using the yiiActiveForm but it was not working because it was dependent when the clientValidations is set to true

```php
// add error
$('#contact-form').yiiActiveForm('updateAttribute', 'contactform-subject', ["I have an error..."]);
 
// remove error
$('#contact-form').yiiActiveForm('updateAttribute', 'contactform-subject', '');
```

**Comment by steppefox** [comment]
If you need yii.activeform.js registered in your page, register asset `yii\widgets\ActiveFormAsset` in it.

**Comment by bryglen** [comment]
Up

**Comment by samdark** [comment]
What do you mean by "was dependent"?

**Comment by bryglen** [comment]
try to do

```php
'enableClientValidation' => false,
```

and do `$('#contact-form').yiiActiveForm('updateAttribute', 'contactform-subject', ["I have an error..."]);`

you will see that you can't do that anymore but when you turn on the `enableClientValidation => true`, it will work as fine.

**Comment by samdark** [comment]
Well, that is expected. `updateAttribute` is part of client validation you've disabled.

**Comment by bryglen** [comment]
could be? 

but what if you have a special field that you need to check in server side and manually use `ajax()` like calling some 3rd party API and if its fail. you need to update the field and you can't maximize the usage of `yiiActiveForm('updateAttribute')`

**Comment by samdark** [comment]
If you want client validation you have to keep it enabled.

**Comment by bryglen** [comment]
ok but would it be better if you can maximize everything even the clientValidation is turn off. isnt it?

**Comment by samdark** [comment]
No. If it's turned off, it's turned off.
