### ISSUE TITLE
AssetsManager, not possible to change $sourcePath globaly

### ISSUE THREAD

**Issue by DarkRide** [yiisoft/yii2#9603]
Hi, 

In application config, I would like to change assets' sourcepath like this : 

```php
$config['components']['assetManager']['sourcePath'] = "/var/tmp/assets";
```

I don't want to store my assets in a folder accessing by the web.
Unfortunately, I get an error : 

>
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: yii\web\AssetManager::sourcePath
>

In fact, nothing in yii/web/AssetManager refers to sourcePath... So sourcePath property is unusable

Thanks for your help

**Comment by samdark** [comment]
`sourcePath` is about asset bundles, not about asset manager. Check docs: http://www.yiiframework.com/doc-2.0/guide-structure-assets.html
