### ISSUE TITLE
Feature Request : REFRESH event for ActiveRecord

### ISSUE THREAD

**Issue by raoul2000** [yiisoft/yii2#9604]
Hi,

**use case** : a behavior is attached to an ActiveRecord model and registers to all apropriates events (AFTER_FIND, AFTER_INSERT, AFTER_UPDATE) so to be able to maintain its internal state aligned with the owner model attributes. 

**the problem** : no event is fired when [refresh()](http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#refresh%28%29-detail) is called and the behavior is not notified, it can't maintain a consistent internal state.

One solution could be to fire an EVENT_REFRESH when the AciveRecord is refreshed.

thank you

**Comment by samdark** [comment]
It sounds OK to me. @yiisoft/core-developers thoughts?

**Comment by cebe** [comment]
there is an afterFind event triggered on the record that is used for the refresh. But sure, that one is not very helpful. agree to add it.

**Comment by klimov-paul** [comment]
Why `afterFind` event is not enough?

**Comment by cebe** [comment]
we could trigger afterFind again on the same record but maybe there is a case where it makes a difference.

**Comment by klimov-paul** [comment]
> we could trigger afterFind again on the same record

It is triggered already inside `BaseActiveRecord::findOne()`:
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L960

**Comment by klimov-paul** [comment]
Although, no: indeed no event will be triggered for the record being refreshed.

**Comment by klimov-paul** [comment]
It is fine to add extra event here.

**Comment by cebe** [comment]
@raoul2000 would you like to work on a pull request?

**Comment by raoul2000** [comment]
I've never contributed but I'll be glad to start. 
So if you agree a call to *refresh()* will trigger an EVENT_AFTER_REFRESH event

**Comment by samdark** [comment]
Yes, please do it.
