### ISSUE TITLE
[Test] Runing test error

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#9605]
```
phpunit --group=web
```
![screenshot from 2015-09-05 09 16 08](https://cloud.githubusercontent.com/assets/5828252/9697233/425cd664-53af-11e5-84f6-6b33d62807f7.png)

**Comment by samdark** [comment]
Reproduced. Any idea why it fails when run as a group but passes if run separately?

**Comment by lynicidn** [comment]
php-cli not have session :(

**Comment by mdmunir** [comment]
Work ok if `RequestTest` exclude from froup

**Comment by alchimik** [comment]
Ошибка происходит если в предыдущем тесте использовались сессии. Я проверял с тестом `framework/web/RequestTest.php::testCsrfTokenValidation`.
Проблема в том, что функция Session::close выполняется не после выполнения теста, а после выполнения всех тестов. Т.е. после запуска `framework/web/RequestTest` (использующего сесии) и перед запуском `framework/web/UserTest.php` функция `Session::close` не выполняется. И получается что в `framework\web\UserTest::testLoginExpires` имеем
`Yii::$app->session->getIsActive() === true` (так как сессия не была закрыта)
`isset($_SESSION) === false` (phpunit очистил)
При вызове `Session::open` `session_start` не вызывается, так как сессия уже 'активна'

**Comment by alchimik** [comment]
Можно в `TestCase.php` вручную закрывать сессию
``` php 
protected function destroyApplication()
{
    \Yii::$app->session->close();
    \Yii::$app = null;
}
```

**Comment by lynicidn** [comment]
хм, а на дестрой апп разве сессия не убивается?

**Comment by alchimik** [comment]
Что значит 'дестрой апп'? 
Сейчас сессии автоматом закрываются так:
``` php
public function init()
{
    parent::init();
    register_shutdown_function([$this, 'close']);
}
```
И получается что `Session::close` вызывается после все тестов, я надо чтобы сессия закрывалась после каждого теста (использующего сессии)

**Comment by lynicidn** [comment]
http://php.net/manual/en/language.oop5.decon.php
когда апп уничтожается оно должно всех кого лениво подтянуло в сервис локатор, как то очищать от мусора (закрывать сессии, удалять временные файло-кеши)

**Comment by lynicidn** [comment]
даже не апп, а сам контейнер

**Comment by mdmunir** [comment]
@samdark change `yiiunit\TestCase::destroyApplication()` can solve this issue.
```php
    /**
     * Destroys application in Yii::$app by setting it to null.
     */
    protected function destroyApplication()
    {
        if(\Yii::$app && \Yii::$app->has('session', true)){
            \Yii::$app->session->close();
        }
        \Yii::$app = null;
    }
```
