### ISSUE TITLE
loadDefaults应该加载模型的默认值，而不是数据库的

### ISSUE THREAD

**Issue by str2code** [yiisoft/yii2#9608]
加载`模型的默认值`我可以根据不同`场景`load不同的默认值，这样在`不同场景`下，可实现表单单选（多选）和下拉列表的默认选中（不同选项），不知道加载数据库的默认值有啥意义？
@qiangxue

**Comment by vistart** [comment]
You can override loadDefaultValues() method to implement loading default values depending on variant scenarios.

**Comment by str2code** [comment]
@vistart 我是觉得读取rules的默认值科学一点

**Comment by vistart** [comment]
~~~php
public function rules()
{
return [
……
    ['attr1', 'attr2'], 'default', 'on' => 'scenario1', 'value' => 'value1'],
    ['attr1', 'attr2'], 'default', 'on' => 'scenario2', 'value' => 'value2'],
……
];
}

$model->scenario = 'scenario1';
if ($model->validate()) {
……
}
~~~
The return value of rules() is commonly used for attributes validation, not for initializing the default value of attribute. So calling the loadDefaultValues() method is necessary after creating an instance of a model class and display its attribute(s) in a view. If you have defined the default value of an attribute in database table schema, the default value will be loaded automatically after creating an instance. But if you want to implement "loading default value(s) depending on variant scenarios when initilizing an model", the best choice is implementing the loadDefaultValues() by your own and call it after new Model().

**Comment by str2code** [comment]
@vistart 对，这样能在保存的时候附上默认值，但是并不会在我添加和更新内容时在`ActiveForm`里体现出默认值（比如单选多选我就需要默认值使其能默认选中一个值）
