### ISSUE TITLE
issue with redirect() in controller action - page not found

### ISSUE THREAD

**Issue by ravindrakashyap** [yiisoft/yii2#9610]
I am trying to use  " return $this->redirect('/Dashboard/index'); "  but it is not working. I am getting a Page not found error ( #404).

here is the code :
File : Dashboardcontroller.php

<?php

namespace frontend\controllers;

class DashboardController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

}

File : Sitecontroller.php

/**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
			
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
			return $this->redirect('/Dashboard/index');
			
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

**Comment by mdmunir** [comment]
`return $this->redirect('/dashboard/index'); `

**Comment by alchimik** [comment]
http://www.yiiframework.com/doc-2.0/yii-helpers-baseurl.html#to()-detail
maybe: `$this->redirect(['dashboard/index']);`

ps: use markdown

**Comment by ravindrakashyap** [comment]
Thanks for the help. It worked for me. I think controller name is case sensitive ( Dashboard -> dashboard).
