### ISSUE TITLE
[Schemabuilder] support for unsigned integers

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#9611]
Schemabuilder should have unsigned integer support
```php
$this->integer()->unsigned()
```
For DBMS that do not support it, it should be ignored(not to throw errors)

**Comment by padlyuck** [comment]
It would also be nice if there was an opportunity to pass the Expression object as an argument to a method defaultValue()

**Comment by mikk150** [comment]
@padlyuck #9337 and please do not clutter github

**Comment by samdark** [comment]
Duplicate of https://github.com/yiisoft/yii2/issues/9443
