### ISSUE TITLE
SwiftMailer: escapeshellarg() has been disabled for security reasons

### ISSUE THREAD

**Issue by platx** [yiisoft/yii2#9613]
When i try to send message via swift mailer, get this error: escapeshellarg() has been disabled for security reasons.
Hosting provider said, that this function cannot be enabled. Is the other way to send mail messages withaout this function?
![yiibaseerrorexception - google chrome](https://cloud.githubusercontent.com/assets/5385861/9704321/9472fce2-54ab-11e5-92d1-f5e52c8096b2.jpg)

**Comment by klimov-paul** [comment]
Report this issue to the https://github.com/swiftmailer/swiftmailer/ project. It does not relates to Yii.
