### ISSUE TITLE
[ActiveQuery] get table name

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#9614]
would be nice, if we could get select table name, if doing query with ActiveRecord because at this moment, it is quite hard
```php
class testQuery extends ActiveQuery
{
    public function active()
    {
        $table=call_user_func([$this->modelClass,'tableName']);
        return $this->andWhere([$table.'.active' => 1])->andWhere([$table.'.terminated' => 0]);
    }
}
```
seems like retarded

**Comment by mikk150** [comment]
or maybe andwhere should prefix with table name automatically, if one isn't supplied

**Comment by cebe** [comment]
related to #2377

**Comment by mikk150** [comment]
I'd even say dublicate of #9326

**Comment by cebe** [comment]
yep
