### ISSUE TITLE
Query [[key => value], Expression, [operator, key, value]]

### ISSUE THREAD

**Issue by njitram** [yiisoft/yii2#9622]
I tryed many things but this combination is not possible, which i think it should:
```
$criteria = [
    'column1'=>'value',
    new Expression('1=0'),
    ['>', 'column2', 'value']
];
$query->where(['and', $criteria]);
```

**Comment by mdmunir** [comment]
```php
$query->where(['and', ['column1'=>'value'], new Expression('1=0'), ['>', 'column2', 'value']])
```

**Comment by njitram** [comment]
How stupid of me, it works. Thank you.
i was confused by the function andWhere(); because i saw the array ['and', $where] so i thought an array should fit, but it doesn't. Thanks again.
