### ISSUE TITLE
Why don't check exists property in object?

### ISSUE THREAD

**Issue by dropShippingDev** [yiisoft/yii2#9623]
Why don't check exists property in object?
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L202

possible fix:
<code>
return isset($array->$key) ? $array->$key : $default;
</code>

**Comment by Alex-Code** [comment]
See comment here https://github.com/yiisoft/yii2/issues/7193#issuecomment-73287156
