### ISSUE TITLE
Error message is displayed "twice" if a DB error occurs when using PageCache and DB dependency

### ISSUE THREAD

**Issue by drscre** [yiisoft/yii2#9624]
I am using PageCache with DB dependency.
If DB server becomes unavailbale and I try to access DB in controller action, a DB exception is thrown.
And I get the following output:
```
{
  "name":"Internal Server Error",
  "message":"There was an error at the server.",
  "code":0,"status":500
}An internal server error occurred.
```
Note and extra "An internal server error occurred" string after the valid JSON.

This happens because `PageCache::cacheResponse()` tries to access DB once again to caclulate variations.
Since DB is unavailble, a second DB exception occurs during handling of the first DB exception.

Probably, `PageCache::cacheResponse()` shouldn't be called for 5xx responses at all. 
Response content for 5xx (content == FALSE, btw) is cached, but not used anyway. Why bother caching content == FALSE and headers?

**Comment by kidol** [comment]
You can enable `$reusable` of db dependency, then you'll only get the first exception as expected.

Alternatively you can apply this unmerged patch #8614 which fixes the problem.

In the long run, PageCache needs refactoring.

**Comment by drscre** [comment]
@kidol $reusable won't fix the problem in my case. 
DB is away and any attempt to access it will throw an exception. DB dependency doesn't get caclulted

Your patch seems to fix the problem, thanks!

The only thing i'm not sure about is `($content === '')` check.
An empty string seems as a valid $content to me. Probably, only `$content === FALSE` should be used.
Take a look at [yii\base\View::beginCache](https://github.com/yiisoft/yii2/blob/95ba06c01b35b84740cd566edf4bdc0611db1efa/framework/base/View.php#L461) - only FALSE is considered as a cache miss.

**Comment by kidol** [comment]
@drscre Yes sorry, mixed something up...

Your can see the reasoning for `$content === ''` here: #8613. If you have the time, please read that issue report and make suggestion for better or modified fix there. Thanks.

**Comment by kidol** [comment]
@samdark Since #8613 was merged, this can be closed I guess.
