### ISSUE TITLE
Problem with dynamic content in fragment caching.

### ISSUE THREAD

**Issue by andrey-bahrachev** [yiisoft/yii2#9626]
Here's the problem I'm facing. While using fragment caching I need to output date and time bits dynamically. As it's a time zone specific data it must be rendered dynamically and shouldn't be cached, and it's obviously not an option to generate the variations of cached data for different time zones. From what I can see there's no way to pass any parameters to the yii\base\View::renderDynamic() method so that I could use that. So how could I do that? Maybe I'm just missing something. Thanks.

**Comment by Renkas** [comment]
>  The renderDynamic() method takes a piece of PHP code as its parameter.
http://www.yiiframework.com/doc-2.0/guide-caching-fragment.html#dynamic-content

So what is the problem there exactly? I see that it does exactly what you need.

**Comment by andrey-bahrachev** [comment]
Ok, let me explain it a bit more. In order to render correct date and time for a given user I need a timestamp and user's time zone name to be used in the renderDynamic() method, but I don't see how I could do that. Obviously something like this won't work:
`$this->renderDynamic('return date('Y-m-d', $timestamp);');`

**Comment by andrey-bahrachev** [comment]
In Yii 1.x the renderDynamic() method accepted a callback as its first parameter and subsequent parameters as parameters to be passed into that callback which made perfect sense. I expected the same here in Yii2, but it accepts a string of evaluated code instead. What's the point in that change?

**Comment by lichunqiang** [comment]
you can do like this:
```
$this->renderDynamic('return Yii::$app->formatter->asDate($timestamp);');
```

**Comment by andrey-bahrachev** [comment]
Yeah, that does the trick, but for me this is kind of dirty solution.
It would be better to use closure as a parameter for renderDynamic() method if possible. Besides, using evaluated code is potentially unsafe.

**Comment by andrey-bahrachev** [comment]
Actually the way proposed by lichunqiang doesn't work either, I just checked that to make sure, as in this case rendering becomes not dynamic and the result is just get cached.

**Comment by lichunqiang** [comment]
It work for me actually...

can you show me your code? I

**Comment by andrey-bahrachev** [comment]
The code is fine. But I've just realized that my situation is even worse.
To make it more clear for understanding let's say I'm rendering a list of comments, so I have a `comments` view in which fragment caching is enabled and which contains render calls in a loop for a child `comment` view (single comment view). That single comment view is where renderDynamic() is called, and when I try to use something like this
`$this->renderDynamic('return Yii::$app->formatter->asDate(' . $timestamp . ');');`
the result is just get cached within an outer parent view.
So the actual problem is different from the one that I thought of initially.
Of course, I could cache every single comment separately, but that's just an overkill...

**Comment by andrey-bahrachev** [comment]
Moreover, now after some experiments I can see that it doesn't matter if it's an outer or child view. Consider this example (it's simplified version of my code):
```php
...
<?php
if ($this->beginCache('comment-' . $model->id, ['duration' => 60, 'dependency' => $dependency])):
?>
<li class="comment">
    ...
    <span class="datetime">
        <?= $this->renderDynamic('return Yii::$app->formatter->asDate(' . $model->created . ');'); ?>
    </span>
    ...
</li>
<?php 
    $this->endCache();
    endif;
?>
...
```
To make clear, `Yii::$app->formatter->asDate()` method here is used as an example, my real code takes into account user's time zone to display the correct date time.
I don't know lichunqiang how it works for you, but the thing is that the value of `$model->created` (or whatever variable is used there) is get cached. Yes, I receive the date and time output, but the same for all the time zones which is incorrect.
So I'm really stuck here guys.

**Comment by lichunqiang** [comment]
a ha..

you should change the `yii\i18n\Formatter::timeZone`

**Comment by andrey-bahrachev** [comment]
No, it's not it, please read carefully.

**Comment by kidol** [comment]
@andrey-bahrachev 
>In order to render correct date and time for a given user I need a timestamp and user's time zone

Try this, it works for me.

```php
<?= $this->renderDynamic('return Yii::$app->formatter->asDateTime(' . $comment->time . ', "full"); ?>
```

In controller I do:

```php
$zones = ['America/Chicago', 'Europe/Berlin'];
Yii::$app->timeZone = $zones[array_rand($zones)];
```

Also, if you're in doubt whether `renderDynamic()` works correctly, you can add `rand(1,999)` at the end of the expression to see if it's really dynamic.

**Comment by andrey-bahrachev** [comment]
I'm sorry guys, my bad :(
Using Yii::$app->timeZone makes it work, I completely forgot about this setting! Arrrgh, stupid me :)
Very much appreciated! Thanks a ton!

**Comment by lichunqiang** [comment]
:cry: My bad english.
