### ISSUE TITLE
how to crate customized directory in yii2 framework under protected folder.

### ISSUE THREAD

**Issue by mani1905** [yiisoft/yii2#9631]
i wnt to  implement backend inside protected folder as per my requirements.
frontend outside the protected folder.
plz giv me suggestions how to customize yii2 framework directory structure according to me.
giv some eg if u hav. thnks...

**Comment by klimov-paul** [comment]
@mani1905, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by mani1905** [comment]
hi paul i used the official yii2 forum for my query but i am not getting
any suggestion from there if you have any idea pls suggest me some

**Comment by df2** [comment]
@mani1905 download this[1] and set your web server to the `web` directory. That's the frontend folder that also contains the entry script (`index.php`), and the rest is backend. 

[1] https://github.com/yiisoft/yii2-app-basic
