### ISSUE TITLE
Compare validator always return false when comparing different number of digits

### ISSUE THREAD

**Issue by amlopezalonso** [yiisoft/yii2#9633]
Having:

    [['end_page'], 'compare', 'compareAttribute' => 'start_page', 'operator' => '>='],

always returns false when number of digits is different in each integer attribute.

For instance, if 'end_page' = 120 and 'start_page' = 90, then the validator will return false though it is true. But if  'end_page' = 120 and 'start_page' = 100, then the validator will return true as expected.

Regards,
Antonio

**Comment by lichunqiang** [comment]
It works as expected for me:
```
class TestModel extends \yii\base\Model
{
    public $start_page;

    public $end_page;

    public function rules()
    {
        return [
            [['start_page', 'end_page'], 'integer'],
            [['end_page'], 'compare', 'compareAttribute' => 'start_page', 'operator' => '>='],
        ];
    }
}
```
test case:

```
$model = new TestModel([
    'start_page' => 90,
    'end_page' => 120
]);

var_dump($model->validate()); // true
```

**Comment by df2** [comment]
@lichunqiang can you try the following, as this might be the state after loading from request:
```php
$model = new TestModel([
    'start_page' => '90',
    'end_page' => '120'
]);

var_dump($model->validate()); 
```

**Comment by lichunqiang** [comment]
@df2 `true` as expected.

internally, it will run `120 >= 90` or `'120' > '90'`, so i think it's not yii bug, but the other reason.

In addition, we can set `[['end_page'], 'compare', 'compareAttribute' => 'start_page', 'operator' => '>=', 'type' => 'number']`,  it will be converted using `(float) $value`

**Comment by df2** [comment]
@lichunqiang @amlopezalonso either way will work then

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/validators/CompareValidator.php#L66

**Comment by amlopezalonso** [comment]
I'm still having this issue but I'm afraid I was not clear enough: by 'true' or 'false' I meant the ActiveForm was throwing the corresponding validation error so it might be as well the issue is not in the validator code itself but somewhere in ActiveForm, etc.

I entered a set of selected values to help breaking this down:

start_page         end_page          validation in form is:
1                        1 ... 10               ok
2                        1 ... 9                 ok
2                        10 ... 19             wrong 
2                        20 ... 99             ok
2                        100 ... 199         wrong
2                        200 ... 999         ok
2                        1000 ... 1999     wrong
2                        2000 ... 9999     ok
25                      1 ... 99              ok
25                      100 ... 249        wrong
25                      250 ... 999        ok
25                      1000 ... 2499    wrong
25                      2500 ... 9999    ok
25                      10000 ... 24999 wrong
25                      25000 ...            ok

So it seems the form is comparing just the leftmost digits in start_page.

Any ideas?

Regards,
Antonio

**Comment by cebe** [comment]
@amlopezalonso have you configured ` 'type' => 'number'` in your validator?

**Comment by amlopezalonso** [comment]
Ah! I missed that part so sorry for the noise. I thought being both attributes declared as integers it would be not necessary to add 'type'.

**Comment by MigueSchpeir** [comment]
@amlopezalonso i'm having the same issue.

![captura_de_pantalla_112015_101657_am](https://cloud.githubusercontent.com/assets/7605756/11300706/e47c5036-8f6f-11e5-869e-92679e796dfd.jpg)

**Comment by cebe** [comment]
@MigueSchpeir please open a new issue for this. Problem looks different.
