### ISSUE TITLE
Supply ActionColumn with corresponding header class

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9635]
currently, the ActionColumn is rendered without column class. it would be logical to have this one set as default because of i.e. width declarations in CSS:
* $headerOptions = ['class'=>'action-column']

Can make a PR if requested

**Comment by cebe** [comment]
In which way is this a generic requirement? seems quite application specific to me.

**Comment by dynasource** [comment]
I am surprised that a default column as the ActionColumn (rendered in Gii) is not supplied with a corresponding class. It was something that I (as a user) was expecting to be there already, so from an expectation perspective I could see this as a requirement. From a usecase perspective, styling of the actioncolumn is required often and having a class name is more stable than using :last.

**Comment by samdark** [comment]
I think it makes sense.
