### ISSUE TITLE
Post Ajax to Controller Action - Bad Request - missing required parameters

### ISSUE THREAD

**Issue by MartinMuzatko** [yiisoft/yii2#9644]
Hello there!

After consulting the irc channel, looking for documentation in the guide on that topic and looking for other people having the same problem without any result, I think this could be a bug or just non-documented behavior.

I'm using PHP 5.5

```
Bad Request (#400): Missing required parameters: form
```

I have prettyUrls enabled, which is why the post request is adressed to 'spot/edit-video'.
It works when there are no paremeters in the action.
Javascript part (I'm using www.riotjs.com as my clientside framework/UI lib):

```js
		saveClip(e) {
			this.parent.toggle()
			var request = jQuery.post(
				url+'spot/edit-video',
				{
					form :
					{
						title: this.title.value,
						description: this.description.value,
						path: this.video.path
					}
				}
			)
			request.success(
				function()
				{
					this.trigger('videoUpdated')
				}.bind(this)
			)
		}
```

PHP - in the Controller:

```php
	public function actionEditVideo($form)
	{
		\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		$form = (object) $form;
		//do sql stuff
		return 'test';
	}
```

I think that the parameter should be able to be utilized for ajax post request calls.

If you know any documentation regarding to this issue, I'd be happy to read and update that documentation.

**Comment by Alex-Code** [comment]
Do you have any dev tools in your browser that will allow you to see what gets posted?
Not sure how `jQuery` handles javascript objects as params.

**Comment by MartinMuzatko** [comment]
Chrome Dev Tools:

**Console:**
```
POST http://localhost/yiisimple/web/spot/edit-video 400 (Bad Request)
```
**Form Data**
```
form[title]:Cats
form[description]:Kitties playing around
form[path]:customer/5/videos/
_csrf:QTZKVnlSYVQ5bD0gLT4ZAAhBHCYgGDVnM0BnAQoaMCAFARklEDUpYQ==
```

I hope this info is sufficient.
I'd like to know: Is post data supposed to be retrievable within the controller action by using the paremter? in my case - form or video (depending on the param name)

![error](https://cloud.githubusercontent.com/assets/2950505/9761397/cfa37398-56fc-11e5-9906-07679a1f68f9.jpg)

**Comment by Alex-Code** [comment]
Just realised, By default only `$_GET` values are bound to an actions params.
You'll need to use `Yii::$app->request->post('form');` within the action.

**Comment by MartinMuzatko** [comment]
Is there a setting of changing this? I'd love to use the full power of optional params. 
e.g. 
```php
actionSaveVideo($doStuff = false)
```
or 
```php
actionDoStuff(boolean $confirm)
```

Still: I'd love to see if this is somewhere in the docs described. I'd be happy to extend the existing docs, as there are only very little use cases documented for ajax in yii2

**Comment by MartinMuzatko** [comment]
When using get, I get this error:

```
Bad Request (#400): Invalid data received for parameter "video".
```

**Comment by Alex-Code** [comment]
Docs about action params [here](http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html#action-parameters).

**Comment by MartinMuzatko** [comment]
Alright, that worked. Although I'd love to use post to avoid any get url limitations if existing (http://stackoverflow.com/questions/3091485/what-is-the-limit-on-querystring-get-url-parameters)

From what I understand, yii2 is not designed to accept post via action param (by default).
If someone knows any docs regarding this setting, I'd love to close this issue and improve the docs.

Thanks a lot for your time.

**Comment by SamMousa** [comment]
This works:

http://aaronfrancis.com/blog/2013/10/16/automatic-parameter-binding-to-post-variables-in-yii2

**Comment by samdark** [comment]
Won't be changed. This is by design.
