### ISSUE TITLE
composer create-project

### ISSUE THREAD

**Issue by lloyd966** [yiisoft/yii2#9647]
I am getting a Composer\RepositorySecurityException when running the following composer command

C:\wamp\www\yii2advanced>composer update

  [Composer\Repository\RepositorySecurityException]
  The contents of http://packagist.org/p/yiisoft/yii2$c6e8f9af3e86a8cf7a0f3088722800c2d327505b7334a98c9b10cba1d86df859.json do not match its signature. This should indicate a man-in-the-middle attack
  . Try running composer again and report this if you think it is a mistake.

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

C:\wamp\www\yii2advanced>

Can anyone explain to me what I need to do, to get this to work

Thank you

**Comment by mdmunir** [comment]
try to running composer again

**Comment by lloyd966** [comment]
I tried cleaning the cache and running composer numerous times with the same error

**Comment by mdmunir** [comment]
are you sure you install the correct framework?
```
# composer global require "fxp/composer-asset-plugin:~1.0.3"
# composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application
```
or
```
# clone https://github.com/yiisoft/yii2-app-advanced yii2advanced
# cd yii2advanced
# composer global require "fxp/composer-asset-plugin:~1.0.3"
# composer install
```

**Comment by lloyd966** [comment]
rebooted my computer, and know it works. Had something to do with my upgrade to windows 10, but I do not know why
