### ISSUE TITLE
autoLogin and IdentityInterface getAuthKey, validateAuthKey

### ISSUE THREAD

**Issue by smsteel** [yiisoft/yii2#9649]
As i can see from docs of these 2 methods:
`This is required if [[User::enableAutoLogin]] is enabled.`
I've tried to log them, they absolutely never being executed while `enableAutoLogin` was set to true in config.
When they will be called and why do i need these methods or this is a possible bug?

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L542
https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L302

**Comment by smsteel** [comment]
The thing is, cookie authentication didn't check for auth key, just used `id` of `Identity`.
If i understand correctly, i need to set `autoRenewCookie` to false in order to force check each time page requested?

**Comment by klimov-paul** [comment]
@smsteel , please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
