### ISSUE TITLE
ErrorHandler + Soap error = Fatal error at the end of request

### ISSUE THREAD

**Issue by Blizzke** [yiisoft/yii2#9650]
I have a nice one for you guys (took me a while to figure out) :)

Apparently `\SoapClient` does a `trigger_error('SOAP-ERROR: The error Message', E_ERROR)`, even when you have the exceptions enabled. 

The exception is caught and processed, deemed survivable and the page request continues.
Unfortunately at the end of that request, Yii's error handler does its `error_get_last()`-call.
It then receives the soap error message with a type of `E_ERROR` and promptly discards the successful response and replaces it by a fatal error. 

I've worked around it by doing a `@trigger_errror('')` in my code to get rid of the fatal error.

Should this be considered a bug? I don't know, I'll leave that up to you guys. 
But I think it's important this is at the very least logged as a possible serious issue.

**Comment by samdark** [comment]
Not a bug. Yii converts errors to exceptions. It could be handled with `try-catch`.

**Comment by Blizzke** [comment]
Think you are completely mistaken here: This happens after the full page has been finalised, at the very end. So there is no user control here anymore. It is triggered by `main`.

**Comment by samdark** [comment]
What's `main`?

**Comment by Blizzke** [comment]
`main` as in the top level "function", outside of the complete application flow. It's [this line](https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L229) I'm talking about and that one is called via `register_shutdown_function()` as you well know. So completely outside of the users' influence.

**Comment by Blizzke** [comment]
```
application
   controller
     action
       try {
            soap request that fails and calls both trigger_error and throws exception
       } catch (\SoapFault) {
           exception handled, flow continues
      }
      action terminates, returns regular page content
   controller terminates
   response is finalised
   php terminates, calls the shutdown function
   error_get_last() retrieves the soap E_ERROR, discards output and replaces it with an exception output
```

Dunno if that made it more clear?

**Comment by samdark** [comment]
Hmm. But [there's a check for fatal error](https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorHandler.php#L231) and you're saying that SOAP error is not fatal. So it should not be the case.

**Comment by Blizzke** [comment]
Indeed, but soap calls `trigger_error` with type `E_ERROR`. 
[Lo and behold](https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorException.php#L93): Yii considers this fatal. Game over.

**Comment by samdark** [comment]
Right. But this one is indeed fatal according to PHP guide: https://secure.php.net/manual/en/errorfunc.constants.php

> Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.

**Comment by Blizzke** [comment]
For proof:
![screen shot 2015-09-10 at 14 43 25](https://cloud.githubusercontent.com/assets/231572/9788493/85e22b5e-57ca-11e5-8416-aa132886974e.png)

As you can see the `get_last_error` call returns `type = 1`
Guess that means the PHP SoapClient has a bug?

**Comment by samdark** [comment]
Most probably yes. Yii is given fatal runtime error and it's handling it as so.

**Comment by Blizzke** [comment]
For future reference: https://bugs.php.net/bug.php?id=70469

**Comment by Ne-Ray** [comment]
https://bugs.php.net/bug.php?id=47584
