### ISSUE TITLE
Pjax::begin should only render content on Pjax requests when id matches

### ISSUE THREAD

**Issue by df2** [yiisoft/yii2#9651]
Otherwise it is a waste of resources as the rendered content will be discarded later when the matching id's Pjax widget starts.

**Comment by samdark** [comment]
Any idea of implementation?

**Comment by df2** [comment]
I think something like this in the Pjax class would work and not break BC.
```php
/**
 * @var when set to `true` and the request is a Pjax request but does not have a matching
 * widget id, the rendering of this widget's content will be skipped.
 */
public $autoSkipContent = false;

**Comment by SilverFire** [comment]
@df2 can you make a PR?

**Comment by df2** [comment]
@SilverFire um, can, but what is the state of the Pjax class? Like is it being deprecated or something? Would have to return boolean from `begin()`. In the mean time, but basically the same:

```php
<?php if (!$isPjax || $pjaxContainer === '#whats-new-wrapper'): ?>
    <?php
    Pjax::begin([
        'id' => 'whats-new-wrapper',
        'enablePushState' => false,
        'linkSelector' => '#whats-new-wrapper a.pjax',
    ]);
    ?>
    <?= ProjectFeed::widget(); ?>

    <?php Pjax::end(); ?>
<?php endif; ?>
```

**Comment by Faryshta** [comment]
how would you deal with nested pjax?

**Comment by SilverFire** [comment]
@Faryshta good point. Maybe, we can introduce additional property whether to render the Pjax block on Pjax request even when ID is different. But as for me, this kind of optimisation brng BC-brak and does not save much resources per request

**Comment by SilverFire** [comment]
I'd rather close this issue than change current behavior

**Comment by Faryshta** [comment]
@SilverFire agree. What I do is to determine on the controller if its a pjax request and only render the file containing the pjax widget.

```php
public function actionIndex()
{
    // code
    $request = Yii::$app->request;
    $view = $request->isPjax ? $request->post('_pjax') : 'index';
    return $this->render($view, [
        'model' => $model,
    ]);
}
```

I don't think an option to avoid rendering a pjax if the id doesn't match is not convenient either, What happens if the pjax widget is not found? you will end up with a partially rendered view. And you are not saving any process time at all since all the pjax content is still executed. At most you are saving a few memory bytes.
