### ISSUE TITLE
yii2 redis yii\redis\ActiveRecord

### ISSUE THREAD

**Issue by webwlsong** [yiisoft/yii2#9652]
use yii\redis\ActiveRecord 

MySQL save to redis

Redis can not be linked table query

eg: use leftjoin  join

**Comment by cebe** [comment]
what? please formulate complete sentences and state in detail what the problem is.

**Comment by webwlsong** [comment]
Redis as DB storage.,mysql save to redis 

Now, I am  searching from redis.

Cannot use the following query
$query = User::find();
$query->leftjoin();

Like query from the database？

**Comment by webwlsong** [comment]
I find this now, should not support the relationship

https://github.com/yiisoft/yii2-redis/blob/master/docs/guide/usage-ar.md  
It is also possible to define relations from redis ActiveRecords to normal ActiveRecord classes and vice versa.

Usage example:

$customer = new Customer();
$customer->attributes = ['name' => 'test'];
$customer->save();
echo $customer->id; // id will automatically be incremented if not set explicitly

$customer = Customer::find()->where(['name' => 'test'])->one(); // find by query
$customer = Customer::find()->active()->all(); // find all by query (using the `active` scope)

**Comment by vistart** [comment]
Redis is a NoSQL storage, which is not support data constraints like RDMS.

**Comment by cebe** [comment]
You can not JOIN across different DBMS and also not between redis records.
