### ISSUE TITLE
GridView, have a column class change row options.

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#9654]
I have a few `GridView` widgets. Each has a common column which shows a date as to when the item will expire so I've made it into a `DataColumn` class.

I want to make use of `Bootstraps` contextual classes for tables so the rows are coloured depending on how long is left on the date.

This can be done using `rowOptions` on the `GridView` but means repeating code across the grids.

It would be handy if a `Column` class could change the row options.

e.g. `protected function renderDataCellContent($model, $key, $index, &$rowOptions) { ... }` or `protected function renderDataCell($model, $key, $index, &$rowOptions) { ... }`

**Comment by dynasource** [comment]
you definately got a usecase. Im not fond of your proposed solution though. Either the row options should be accessed by something as $this->row within your column class, but this is not how the grid is built. 

Ultimately, you want a table that is fully object oriented, but for large tables, perhavs this goes at cost of performance. In you'r scenario, which is quite usecase specific, I would try to hook into the closure GridView::$rowoptions by a Event::init or DI.

**Comment by Alex-Code** [comment]
It is a bit specific but would help with creating reusable columns.
Currently I do set the $rowOptions from the Column init() but it feels a bit wrong and means it can't be used by the GridView anymore.

It's a shame there's no parent selector in CSS.
