### ISSUE TITLE
DbManager cache getAssignments result

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2#9659]
There was some talk of this here #7626 but thought it could do with some discussion.

I have a backend with a menu that has items which are visible based on the current users permissions.
According to the debug toolbar this is generating 32 identical queries `SELECT * FROM auth_assignment WHERE user_id='1'` and memory is 3.4mb.

Changing `DbManager` to store the query result in a local var the query only gets executed once and the memory dropped to 3.2mb.

**Comment by samdark** [comment]
Caching once per request in local variable sounds OK to me.

**Comment by samdark** [comment]
Caching in cache component doesn't for the reasons explained in the issue linked.

**Comment by klimov-paul** [comment]
Should not it be already resolved by #8595 ?

**Comment by nineinchnick** [comment]
I'd made optional caching in #9659. I've got a contr-argument when an app only uses default assignments so there are no assignments at all but I'd be also very happy with a local var cache.

**Comment by Alex-Code** [comment]
I modified the getAssignments method.
It first checks if the local var has any data and returns that otherwise it queries the db.

I can't see a need to make this optional, the results are only cached for the lifetime of the request.

**Comment by nineinchnick** [comment]
I meant optional caching using a cache component, not a local var. @Alex-Code  can you make a PR?

**Comment by samdark** [comment]
@nineinchnick nope. That's definitely not a good idea to cache it via cache component.

**Comment by samdark** [comment]
Because it could be changed, for example, from console or backend app not sharing the same cache. And that could result in serious security issues.

**Comment by nineinchnick** [comment]
And this doesn't concern auth roles, items and their associations?

**Comment by samdark** [comment]
Not at the same degree:

1. These aren't changed that often.
2. These would be noticed immediately by the guy who's testing if everything deployed well.

In case of individual assignments it's nearly impossible to notice that one user who isn't you is affected i.e. still has admin permissions while you're removed it from admin panel a week ago.

**Comment by Alex-Code** [comment]
Would using a ternary expression be suitable here?
```php
public function checkAccess($userId, $permissionName, $params = [])
{
    $assignments = $this->_assignments ?: ($this->_assignments = $this->getAssignments($userId));
    //...
}
```

**Comment by nineinchnick** [comment]
Duplicate of #7743
