### ISSUE TITLE
 PHP Notice – yii\base\ErrorException Array to string conversion

### ISSUE THREAD

**Issue by HemanthkumarHJ** [yiisoft/yii2#9665]
![untitled](https://cloud.githubusercontent.com/assets/13161368/9808247/3bc812b6-587b-11e5-93e2-4b923d252abb.jpg)

**Comment by arogachev** [comment]
Please add more details and code. In current state we are unable to help.
Seems like it's a bug in your code, not framework problem.
Use forum to ask such question in this case.

**Comment by dynasource** [comment]
FindOneRow? This is not Yii's scope. Its your own custom function.
