### ISSUE TITLE
Parsing Fundamentals in Yii

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9666]
Parsing text is a basic principle within projects. After all, a basic website is about transforming:
* input -> db -> output

This parsing principle (what I think it is) is not covered by docs, or I am missing it. Several questions about this come to mind:
* Is markdown Yii's core parser component?
* Should/can markdown be applied for other conversions?
* If its a central component https://github.com/dynasource/yii2/blob/master/framework/helpers/Markdown.php, why is based on cebe\markdown
* If it is a central component, why isnt it called Parser.
* Why is configuration put in a helper with static. It would be cleaner to put in components
* etc etc.

A lot of confusion. A lot of questions.
So what is my point here?

Shouldnt Yii provide:
* a base Parser (with this general name)
* that is configurable
* from which MarkDown extends (and helpers are put in yii2/markdown)
* which is well documented in yii2 docs about 'Parsing'

Supplied with a MVC best practice: how to transform text in a:
* optimal (fast rendering)
* consistent (where to put the logic about config, transformation, etc)
* safe (prevent data pollution)
* etc

**Comment by samdark** [comment]
> Is markdown Yii's core parser component?

Kinda yes. It's a helper, not components.

> Should/can markdown be applied for other conversions?

Which conversions? Overall, it's totally optional to use. It's used in a helper only.

> why is based on cebe\markdown

Why not?

> If it is a central component, why isnt it called Parser.

Because there are many parsers out there. Markdown is a very specific one.

> Why is configuration put in a helper with static. It would be cleaner to put in components

Why not? Using DI container it's easy to configure.

> MVC best practice: how to transform text

It's not related to MVC at all.

**Comment by dynasource** [comment]
Thanx for your fast reply. 

Firstly, my point about MVC is, where to put the parsing logic. There are so many places where the transformation can be done. What would be the best solution? Should it always be done in the Model, Widgets or in the View, or through a central component. Why reinventing the wheel if a framework has already solved this for you.

Secondly, how to deal with multiple parsing processes, like a parsing pipeline (perhabs in combination with purifiers etc.). IMHO, this deserves a processor that fits well in the Application life cycle. 

Thirdly, I still think it is strange to have Yii depending on external composer packages, such as with cebe/markdown. Why not put all the Markdown logic over there.

To conclude. I see many chances for further development. Just wanted to share.

**Comment by nineinchnick** [comment]
I'm not sure it's the same issue, but I remember having troubles figuring out how to filter and format data when storing it in a different format than it's displayed to and entered by users. Some examples are dates and monetary values.

Finally what I'm doing now is using validators for filtering data and formatters for displaying it. Others may try to do it in before/afterSave events of the model, manually in the view etc.

Can one solution be selected as better and advertised? If yes, it might be helfpful if the docs describe a forkflow like this somewhere.

**Comment by samdark** [comment]
> where to put the parsing logic

Since Carsten't markdown lib is quite fast, I'm applying it right in the view. When it was PHP markdown extra I did it in `afterSave()` to speed page rendering up a bit.

> Why reinventing the wheel if a framework has already solved this for you.

It did not. Where to apply transformation is your choice as developer.

> Secondly, how to deal with multiple parsing processes, like a parsing pipeline (perhabs in combination with purifiers etc.). IMHO, this deserves a processor that fits well in the Application life cycle.

Why complicating it that much? Call methods in the sequence you need. If it's quite a big chain of calls, wrap it into a method or a helper.

> Thirdly, I still think it is strange to have Yii depending on external composer packages, such as with cebe/markdown. Next to that, why not put all the Markdown logic over there.

That's probably a good idea to remove markdown support from the core since it's used in a helper only.

**Comment by samdark** [comment]
Overall, I see it as a good candidate for cookbook recipe.

**Comment by dynasource** [comment]
Agreed, supplied with a lifecycle with do's and don't, based on performance, flexiblity, configurability and safety.

Currently I am working on a parsing workflow. When this is up and running, I will share my learnings through a cookbook recipe. Thanks for your time and insights.

**Comment by samdark** [comment]
Here's a draft: https://github.com/samdark/yii2-cookbook/blob/master/book/processing-text.md

**Comment by dynasource** [comment]
thanks
