### ISSUE TITLE
Enhancement Doc: Session by DB or PHP

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#9668]
I see the following line at http://www.yiiframework.com/doc-2.0/guide-tutorial-performance-tuning.html#optimizing-session:

```php
"By default session data are stored in files. This is fine for development and small projects. 
But when it comes to handling massive concurrent requests, 
it is better to use more sophisticated storage, such as database."
```

This is a statement not supported with any arguments. Is it speed? Is it stability? It would be helpful to go into a little more depth with links to sources that prove this statement. I have looked at some sources on the internet and conclusions vary. If a convincing conclusion can be drawn, I would to see details on the switching point. Perhabs 100 concurrent users?

**Comment by samdark** [comment]
Default PHP session handling is based on files and is using locking to deal with concurrency issues so it totally denies parallel accessing to session data. As a result such requests are blocking each other. 

I've posted about it in 2012 but in Russian. You may use google translate to get an idea: http://rmcreative.ru/blog/post/blokirovanie-sessiy-v-php.

I really should be writing in English one day starting with translating interesting posts I've published previously...

**Comment by klimov-paul** [comment]
This is a general PHP relate question. It does not belongs to the framework.

**Comment by dynasource** [comment]
Nope. This is a point to a incomplete doc

**Comment by samdark** [comment]
Docs improved. Thanks for suggestion.
