### ISSUE TITLE
Redirect problems in Internet Explorer 11 (IE11)

### ISSUE THREAD

**Issue by w3MediaLabs** [yiisoft/yii2#9670]
When I use the included IE debugger and view the response headers, the header is there and the url is correct, but IE11 isn't reading it.

The response error:
![pjax-response-error](https://cloud.githubusercontent.com/assets/7306696/9818278/b982718e-5875-11e5-8180-c00d9888e3f1.jpg)

The response headers:
![pjax-response-headers](https://cloud.githubusercontent.com/assets/7306696/9818283/c46e34f2-5875-11e5-8b4b-83992c9b264f.jpg)

One comment on StackOverflow suggested using the status code `200`, and after testing, this does appear to work.  I know the default redirect status code is 302, but this just doesn't work.

## Update

I just respond with redirect to ajax request. Page redirects in all browsers except IE. I'm testting in IE11. I'm getting the following error in console: XMLHttpRequest: Network Error 0x2f76, Could not complete the operation due to error 00002f76..

URL for redirect sent in X-Redirect header. yii.js script handles this header, see line 265. var url = xhr.getResponseHeader('X-Redirect');. In case of IE11 getResponseHeader() returns null instead of URL. As I mentioned before I just respond with 200 status at the moment instead of 302.

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft/jquery-pjax/issues/26

**Comment by SilverFire** [comment]
Added `Update` section to the topic. The problem does not really relates Pjax, it's about yii.js and IE

**Comment by DMGPage** [comment]
When this bug will be corrected? I have same problem with IE 10 till edge. If I make ajax request and page redirects to login with status code 302, IE throw "SCRIPT7002: XMLHttpRequest: Network Error 0x2f76, Could not complete the operation due to error 00002f76.".

For now I will rewrite loginRequired function to redirect ajax requests with status code 308, but I hope this bug will be corrected soon.

**Comment by SilverFire** [comment]
Related on SO:
http://stackoverflow.com/questions/32964266/ajax-post-not-working-in-ie11
http://stackoverflow.com/questions/33367746/internet-explorer-doesnt-redirect-on-ajax-response
http://stackoverflow.com/questions/30351338/yii2-jquery-not-working-in-ie11

Related on GitHub:
https://github.com/NodeBB/NodeBB/issues/3587

it seems, that it's not a really Yii2-related problem

**Comment by SilverFire** [comment]
Also I don't like 308 code for redirect, because according to RFC it's a permanent redirect.

> The 308 (Permanent Redirect) status code indicates that the target
   resource has been assigned a new permanent URI and any future
   references to this resource ought to use one of the enclosed URIs.

**Comment by SilverFire** [comment]
There is a good article on [HabraHabr](http://habrahabr.ru/post/86258/) in Russian, where the author suggests to use 303 code. In the end of the post, there is a tip, that 303 doesn't work in old browsers, but the post was written almost 6 years ago.

So I've tested IE11 with both 303 and 308 redirects:
__303__: The same error as with 303, no redirect.
__308__: No error, no redirect. Nothing happens. Absolutely nothing.

**Comment by DMGPage** [comment]
All SO posts are about Yii and you say it's not Yii problem? Sounds like a joke. Especially when yii.js handles redirects. And yes 303 code is not a solution.

**Comment by SilverFire** [comment]
I said that it's not a Yii problem since you can easily reproduce it with plain PHP and AJAX.

The root of the problem is `X-Pjax-Url` header, which is generated instead of `Location` to redirect client's PJAX request. I guess IE has a pre-filter that marks responses with status-code 302 and without `Location` header as invalid. `X-Redirect` is ignored by IE as well.

Since the problem affects all the IE versions (including modern) I think that we should try fix it somehow.
The easiest way is changing [Response.php:763](https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L763) and setting `Location` header instead if anything else, but it will bring backward incompatibility.

@yiisoft/core-developers do you have any ideas?

**Comment by samdark** [comment]
We could probably detect IE and send another header for it.

**Comment by SilverFire** [comment]
I'm not happy with the idea of detecting browser versions in core code =/

**Comment by samdark** [comment]
Well, yes but I see no other choice right now.

**Comment by SilverFire** [comment]
@yiisoft/core-developers nobody else have a better idea? Or nobody complains about adding such check to the `response->redirect()` method?

**Comment by AnatolyRugalev** [comment]
May be pjax can add custom header for problem browsers and yii will detect it? `X-Redirect-Compability: 1` for example

**Comment by AnatolyRugalev** [comment]
And we should have an option in it to disable this new behavior

**Comment by SilverFire** [comment]
@AnatolyRugalev that's a better idea!

**Comment by SilverFire** [comment]
Please, check out #10483 and https://github.com/yiisoft/jquery-pjax/pull/38

**Comment by degibons** [comment]
So, it's only corrected for PJAX. What about regular ajax redirect (handled in other browsers with yii.js RedirectHandler)? In IE it's still not working.

**Comment by Fr1ar** [comment]
The problem is still persists for regular ajax redirects in IE & Edge, because HTTP request does not contain header "X-Ie-Redirect-Compatibility" so redirect does not work properly.

**Comment by njasm** [comment]
I agree with @Fr1ar .
 yii should handle this, issue in yii.js RedirectHandler. we're having this problem still.

**Comment by vsmelarkod** [comment]
How to fix this issue? I am getting the same error trying to post json data to controller/action from Javascript using $.ajax. Works well in other browsers.. having issue in IE11. 

$.ajax({
                            type: 'POST',
                             url: '/site/register-payment',
                             data: {paymentdata:res},
                             dataType: 'json'
                });

**Comment by art40100** [comment]
Issue is still ongoing, tested with IE11 and Yii 2.0.12, even latest (to this date) Yii 2.0.22 - has the same issue.

**Comment by samdark** [comment]
Please report issue separately. Thanks.
