### ISSUE TITLE
[CRUD generator] Info alert after delete.

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#9672]
Can you provide alert feedback option in CRUD generator?

I mean info alerts after create, update, delete actions?
Example: "The user was created successfully.", "The user was updated successfully.", "The user was deleted successfully."

I think it can be very useful when user operate on list of hundreds entries. Sometimes user can not remember what just did or is not sure.

**Comment by pana1990** [comment]
duplicated https://github.com/yiisoft/yii2-gii/issues/26
