### ISSUE TITLE
Circular dependency when using fixtures

### ISSUE THREAD

**Issue by mjwvb** [yiisoft/yii2#9673]
It might be that I'm doing something wrong, but here's the thing:

I'm using the fixture dependency feature while unit testing in Yii 2.0.6. I have a situation here whereby one table refers to another table, but that the other table also refers to the former table. Using InnoDB's foreign key definitions, both tables require each other. Therefore I defined the $depends attribute accordingly for both fixtures.

I simplified the case into the following two fixtures:

```
class UserFixture extends ActiveFixture
{
    public $modelClass = 'common\models\User';
    public $depends = [
        'tests\codeception\common\fixtures\CityFixture',
    ];
}
```
```
class CityFixture extends ActiveFixture
{
    public $modelClass = 'common\models\City';
    public $depends = [
        'tests\codeception\common\fixtures\UserFixture',
    ];
}
```

However, I receive the following error when executing the codeception tests: 

> yii\base\InvalidConfigException: A circular dependency is detected for fixture 'tests\codeception\common\fixtures\UserFixture'.
> 
> #1  /htdocs/app/vendor/yiisoft/yii2/test/FixtureTrait.php:132
> #2  /htdocs/app/vendor/yiisoft/yii2/test/FixtureTrait.php:109
> #3  /htdocs/app/vendor/yiisoft/yii2-codeception/TestCase.php:85
> #4  /htdocs/app/tests/codeception/common/unit/models/UserTest.php:20

Am I doing something wrong, or is the framework not supporting such a relationship for AR fixtures yet?

**Comment by cebe** [comment]
The message clearly states that a circular dependency is a problem. Dependencies are mostly useful if you have foreign keys that need to match so we can not support circular dependencies. If you need user and city together you may create another fixture that depends on both.

**Comment by mjwvb** [comment]
That's indeed an option, but I have many tables with circular relationships. Creating a fixture for every circular dependency is generating a fixture forest here.

I don't see how circular dependency is actually a problem in this case where foreign key integrity checks are turned off. Why not just check if the circulated fixture is already being loaded, and if so, ignore it, and otherwise add it to the load stack? I tested it by just commenting out the error throwing in FixtureTrait, it actually works like a charm... What is the real problem that may occur for fixtures in a testing environment so that an exception is required?
