### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2#9676]
Hello,

I need a bit of help to resolve a nagging problem.

History; 
A while ago I used to get the error "PHP Fatal error: strtotime(): Timezone database is corrupt - this should never happen!" and I thought the machine had insufficient resources. So I recreated the machine a number of times and played with RAM size from 512K to 2MB. This seems to have gone away.

Current Situation;
Up to 2 - 3 times each day I get the error "failed to open stream too many open files" and then I have to restart the entire Vagrant machine to get anything done.

My code does not use any explicit file open routines, not sure if Yii2 does in the background. I've even set the maximum number of open files to 65000 but that didn't help. 

Will appreciate if someone can point me in the right direction cause I'm not sure if this is even a Yii2 issue.

My environment is Ubuntu linux 14 + php 5.4.

Thank you in advance.

**Comment by samdark** [comment]
Please ask questions at forums. This is not Yii bug for sure. Should be something about OS config. Most probably the way webserver is configured.
