### ISSUE TITLE
Empty response on using strlen()

### ISSUE THREAD

**Issue by xphoenyx** [yiisoft/yii2#9677]
I have a REST application with an ActiveRecord class which overrides method  `fields()`. Some fields (array keys) are set with callable values as described [here](https://github.com/yiisoft/yii2/blob/master/docs/guide/rest-resources.md#overriding-fields-). In one of these functions I am using `strlen()` function and this is the case when problem is arising - as long as there is a `strlen()` in any anonymous function, I am getting an empty response (totally empty body) and status 200. The output is correct when no such function is used.  See my example below:

```php
public function fields() {
    return [
        /* other fields */
        'shortTitle' => function($model) {
            return array_map(function($title) {
                return strlen($title) > 29 ? substr($title, 0, 26) . '...' : $title;
            }, $model->title);
        },
        /* other fields */
    ];
}
```

In this example, I am getting a collection of documents from MongoDB, where field `title` is an object with next structure:
```
{
    'en': 'A pretty long title',
    'ru': 'Довольно длинное название'
}
```

I am not sure if it is a framework bug or the problem of mine. I thought that it might be a memory issue, but it is not - even if the field is single, an empty response is coming from server.

**Comment by ufocoder** [comment]
There's not a framework bug. 
How you didn't catch a warning about `array_map` function, because `$model->title` is not an array? 
If you develop with disabled error reporting there's not good practice I believe. 

Try to modify your method like this:

```
public function fields() {
        return [
            /* other fields */
            'shortTitle' => function($model) {
                return strlen($model->title) > 29 ? substr($model->title, 0, 26) . '...' : $model->title;
            },
            /* other fields */
        ];
}
```

**Comment by xphoenyx** [comment]
The code in my example is a simplified version. There were many other versions of this, including ones with a check for an array type, and I just took the simplest one just to show the point. I also gave an example of the structure of a field `title` to assume that `$model->title` will always return an array. In your example, you are using a `strlen()` function without any extra check of `$model->title`, which will throw an error for a non-string argument. 
I am using a development environment with an enabled error reporting, catching all types of errors.

**Comment by SilverFire** [comment]
@xphoenyx as you store data is UTF8, you should use multibyte-safe functions `mb_strlen` and `mb_substr` instead of `strlen` and `substr`.

I think you `substr($model->title, 0, 26)` cuts a moiety of UTF-8 char and it causes tons of problems.

**Comment by xphoenyx** [comment]
@SilverFire, thank you for your suggestion, that was a multibyte problem indeed. It seems that error, arising in anonymous function, assigned to any of array keys in `fields()` method, leads to unexpected immediate empty response with no sign of error. Could this case be handled somehow?
