### ISSUE TITLE
Memory leak during ActiveRecord::save()

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#9679]
I found this memory leak when trying to save 90k ActiveRecords. I run out of memory and reached the limit of the cloud server. Here is a test case you can run from the console:

```
  public function actionTest() {
    // ini_set('memory_limit', '450M');
    $agk = AdGroupKeyword::find()->all();
    foreach($agk as $v) {
      $v->save();
      gc_collect_cycles();
      echo memory_get_usage().PHP_EOL;
    }
  }
```

It starts out at `109970136` and gets up to 400M+. 

This is Yii version 2.0.4. Also happens in 2.0.6.

**Comment by klimov-paul** [comment]
Most probably it is related to the log collection.
Do you have YII_DEBUG = false?

**Comment by starrychloe** [comment]
It fails in both dev and production. The test above was only run in dev.

```
if ($_SERVER['SERVER_NAME'] == 'localhost' || $_SERVER['SERVER_NAME'] == '127.0.0.1') {
  defined('YII_DEBUG') or define('YII_DEBUG', true);
```

I have log levels set to 

                    'levels' => ['error', 'warning'],

**Comment by arogachev** [comment]
As I remember `save()` in this case should not even trigger SQL query, because none of attributes has changed.

**Comment by klimov-paul** [comment]
Try to set `Yii::getLogger()->flushInterval = 1` and use `Query::each()` instead of `Query::all()`

**Comment by arogachev** [comment]
We were facing similar problem (update of about 130 000 records was needed in migration), using `each` solved it.

**Comment by samdark** [comment]
@arogachev if you're talking about memory, it would be cool if you'll try profiling it to find out the reason. I know you're capable of it ;)

**Comment by mfrancis107** [comment]
I ran into this issue but discovered it was because of the debug module.

```php

    /**
     * Processes the given log messages.
     * This method will filter the given messages with [[levels]] and [[categories]].
     * And if requested, it will also export the filtering result to specific medium (e.g. email).
     * @param array $messages log messages to be processed. See [[\yii\log\Logger::messages]] for the structure
     * of each message.
     * @param boolean $final whether this method is called at the end of the current application
     */
public function collect($messages, $final)
    {
        $this->messages = array_merge($this->messages, $messages);
        if ($final) {
            $this->export();
        }
    }
```

The collect method in the debug\LogTarget only dumps when it's the end of the application.
So even calling Yii::getLogger()->flush() won't solve the problem.

**Comment by starrychloe** [comment]
@arogachev There are no event handlers or behaviors. There are only two relations. It happens on all models. `->each()` and `->batch()` do help.

**Comment by georaldc** [comment]
I think its related to the yii\base\Model::validate() method. Have you tried skipping validation and seeing if memory usage still goes up (save(false))?

**Comment by klimov-paul** [comment]
Closed, unless more information provided.

**Comment by TheHett** [comment]
https://github.com/yiisoft/yii2/issues/13256
