### ISSUE TITLE
Create Vagrant file for developers.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#9682]
It would be great if a Vagrant file could be added to the repo so developers can run the full test suite more easily.

The Vagrant file could manage:
1. Setting up all DBMSes
2. Creating the databases (ie no more configuration required).

**Comment by akireikin** [comment]
+1 need official Vagrant Box

**Comment by SamMousa** [comment]
This is more than a year old; currently containers are the hot topic and using `docker-compose` is easier as well. I'm closing this.
