### ISSUE TITLE
Validator 'compare' on same attribute

### ISSUE THREAD

**Issue by evilito** [yiisoft/yii2#9686]
This doesn't seem to have any effect on Yii 2.0.6:

```
['age', 'compare', 'compareAttribute' => 'age', 'operator' => '>=', 'message'=>'You can't get any younger.'],
```

Currently, it is necessary to do it this way:

```
['age', 'compare', 'compareValue' => $this->age, 'operator' => '>=', 'message'=>'You can't get any younger.'],
```
Is this intended or should be fixed? I don't see a good reason why we wouldn't be able to just reference the same attribute using `compareAttribute`.

**Comment by lichunqiang** [comment]
Test Case:
```
class TestModel extends \yii\base\Model
{
    public $age;

    public function rules()
    {
        return [
            ['age', 'compare', 'compareAttribute' => 'age', 'operator' => '>=', 'message' => 'You can\'t get any younger.'],
        ];
    }
}

//1.
$model = new TestModel;
$model->age = '12';

$model->validate();
var_dump($model->getErrors()); //empty array
//2
$model = new TestModel;
$model->age = 50;

$model->validate();
var_dump($model->getErrors()); //empty array
```

yii version is 2.0.6

**Comment by evilito** [comment]
Hello, I think the test case should include a model that is saved first, and then using the same model variable, try to update the age to a lower value.

```
$model = new TestModel;
$model->age = '50';
$model->save();
$model->age = '25';
$model->validate(); // should return false, but it doesn't.
```

**Comment by klimov-paul** [comment]
> This doesn't seem to have any effect

This can not work anyhow: at the validation stage 'age' attribute have a single value - from the user input.
For this use case you should create your own validator, which will compare attribute value with its origin value from `oldAttributes`.
