### ISSUE TITLE
Model : How to get select in hasmany

### ISSUE THREAD

**Issue by dev10calypso** [yiisoft/yii2#9687]
I have 2 table relation is one to many 
select * from topic 
left join (select * from note group by idtopic) as note on topic.idtopic = note.idtopic

how to make relation on model like this sql?

**Comment by vistart** [comment]
Have set the column `idtopic` of table `note` as foreign key, which is referenced from `idtopic` of `topic`?

**Comment by dev10calypso** [comment]
i'm set already but now i want to join just only last record of table 'note'

**Comment by arogachev** [comment]
Please use forum to ask questions like that. Issues are for bugs, enhacements, etc.

**Comment by dev10calypso** [comment]
@arogachev  i'm so sorry

**Comment by arogachev** [comment]
Alternatively you can ask for example in [Gitter chat](https://gitter.im/yiisoft/yii2).
