### ISSUE TITLE
FileValidator fails validating mp3 MIME type

### ISSUE THREAD

**Issue by akireikin** [yiisoft/yii2#9688]
FileValidator thinks that MIME type of [this file](https://yadi.sk/d/8uZu2vXYj6gAk) is `application/octet-stream`.

Current framework implementation of `FileValidator` uses `finfo_file()` to determine MIME type. May be we should use [JamesHeinrich/getID3](https://github.com/JamesHeinrich/getID3/) or [MimeReader](http://pastebin.com/raw.php?i=NcL5BLwg) for audio files instead?

BTW, the same issue in Laravel 4.
http://stackoverflow.com/questions/21564029/file-upload-mime-type-validation-with-laravel-4

**Comment by samdark** [comment]
I don't think it is a good idea to solve it at framework level.

Moreover, mp3 can have no ID3 or even ID1.

**Comment by akireikin** [comment]
Why?

**Comment by samdark** [comment]
You mean why mp3 w/o ID3 or ID1 could be valid? Or why framework doesn't solve that specific issue?
