### ISSUE TITLE
Allow setting name attribute in hidden input file upload

### ISSUE THREAD

**Issue by graphcon** [yiisoft/yii2#9689]
Hi Yii2 team.

Currently, one can rename input fields in ActiveForm by passing the name key in $options array. This does work (as I've seen it) in every field but not for the hidden field in a file upload.

I would suggest as fix in this code line:
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1317

From:
`return static::activeHiddenInput($model, $attribute, ['id' => null, 'value' => ''])`
To:
```php
$hiddenInputOptions = ['id' => null, 'value' => ''];
if(isset($options['name'])) {
    $hiddenInputOptions['name'] = $options['name'];
}
return static::activeHiddenInput($model, $attribute, $hiddenInputOptions)
```

As this would be the first contribution to this project, I want to first ask whether that is the supposed way and if it suits the code style.

**Comment by moicirk** [comment]
The options array must be used for activeInput only I guess.
Why don`t you just use hiidenInput contatinated with fileInput manually in a template?

**Comment by graphcon** [comment]
@moicirk Well, that is because I'd prefer it when the framework does this conveniently for me :) Concatenating hiddenInput and fileInput manually is a workaround for an issue in the framework, I would say...

**Comment by cebe** [comment]
Fixed, thanks for reporting!
