### ISSUE TITLE
FR: I wish View::render() can be used like require()

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#9690]
I mean, it can be used to render file with content like
```php
// view file
return [
   'items' => 'somethings',
   
];
```

**Comment by klimov-paul** [comment]
`View::render()` exist mainly because of usage of `ViewRenderer` and theme.
The requested feature does not make sense you should use `require` operator for this case.
You can use `Yii::getAlias()` or `__FILE__` / `__DIR__` magic constants to get actual file name.

**Comment by dynasource** [comment]
I agree with Mdmunir. If its possible, it would be something to implement for 2 reasons:
* firstly, it would enable overriding settings of modules locally as render implements Theme::applyTo
* secondly, it makes render more consistent as it copies the functionality of require even more

**Comment by dynasource** [comment]
thirdly, it allows parameter passing

**Comment by cebe** [comment]
you mean View::render() should have a return value if the file has a return statement? Please elaborate more about what this should be good for.

**Comment by dynasource** [comment]
Render mimics require...but not the return of Arrays.

1) Currently I cannot use require for including _config.php files. Require does not take Theme view file overriding into account, so I have to do this manully every time (with Theme::applyTo)
2) Why does render not mimic the return behavior of a file. I expected it, just like @mdmunir was.
3) If render() would enable inclusion of files returning arrays, I can also benefit from parameter scoping, so I pass specific $options to the _config.php file.

**Comment by cebe** [comment]
render executes a view file and returns the output, why should it return an array?

**Comment by fernandezekiel** [comment]
it sounds like what you want/need is something like an Output object being returned and just has a Output::__toString() implementation instead of an array
