### ISSUE TITLE
yii/db/ActiveController error

### ISSUE THREAD

**Issue by webwlsong** [yiisoft/yii2#9696]
$scrap = Scrap::findAll(['first'=>0,'user_id'=>$user_id,'TO_DAYS(add_time)'=>TO_DAYS(NOW())]);

error:
name: "PHP Fatal Error"
message: "Call to undefined function \modules\v1\controllers\TO_DAYS()"
code: 1
type: "yii\base\ErrorException"

**Comment by mdmunir** [comment]
```php
Scrap::findAll([
    'first'=>0,
    'user_id'=>$user_id,
    'TO_DAYS(add_time)'=>new \yii\db\Expresion('TO_DAYS(NOW())'),
]);
```
http://www.yiiframework.com/forum/

**Comment by webwlsong** [comment]
TKS
