### ISSUE TITLE
Html::error doesn't seems to be working on ajaxValidation or clientsidevalidation

### ISSUE THREAD

**Issue by drinkncode** [yiisoft/yii2#9700]
Hi, i have been shifting from yii 1.1 and yii 2.0, and i have to display my attribute error at the top of the form and no inline errors, but finding it hard to so, to achieve my requirement i tried putting below code at the top of my form: 
<?= Html::error($model, 'username',['class'=>'help-block']); ?>

but it doesn't display any errors on ajaxValidation and clientValidation while on normal submit and validate it is showing up the error.

Am i doing something wrong or is there an alternative to achieve this or is this missed or left out?

**Comment by samdark** [comment]
It should be active form error summary: http://www.yiiframework.com/doc-2.0/yii-widgets-activeform.html#errorSummary()-detail

**Comment by drinkncode** [comment]
@samdark i don't want to display the error summary, i just want to display the error of a particulat attribute say "username", which i am not able to find a way to achieve, 

<?= Html::error($model, 'username',['class'=>'help-block']); ?>

is not working on ajaxValidation.

<?= $form->errorSummary($model); ?> displays all the errors of the form.

**Comment by samdark** [comment]
Client validation works with Active Form only so any `Html::` won't work.

A field for a single attribute rendered via http://www.yiiframework.com/doc-2.0/yii-widgets-activeform.html#field()-detail will display error for that attribute.

**Comment by drinkncode** [comment]
@samdark: Yes it displaying error for that attribute, but only inline, that is below the field itself which i already know, but not at the top of the form..
Look here, explaining my scenario with the help of some code..

my form with Ajax Validation: 

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'enableAjaxValidation' => true,
        'enableClientValidation' => false,
        'validateOnSubmit' => true,
        'validateOnChange' => false,
        'validateOnType' => false
        
        ]); ?>
    
    //  Error for username attribute here is not showing up, on validating with ajax,
    <?= Html::error($model, 'username', array('class' => 'loginerrors help-block')); ?> 
    //  how to show the error here..?? In yii 1.1 we simply call $form->error($model, "username") but here there is nothing like it.

    <div class="loginForm" id="login1">
        <div class="container">
            <div class="row"> 
                <div class="span4 offset4 control-group" id="username_offset">
                    <?= $form->field($model, 'username')->textInput(); ?> //Not here, it is displaying the error here on ajax validation, by forming divs dynamically.
                </div>
                <div class="span4 control-group">
                    <?= $form->field($model, 'password')->passwordInput(); ?>
                </div>
                <div class="span12">

                        <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>`

**Comment by cebe** [comment]
Please use the forum for asking such questions, github is for bug and feature requests.

**Comment by drinkncode** [comment]
@cebe Apologies, but it looked like a feature being ignored in yii 2.0 while it was there in yii 1.1..hence i raised this question here. Googled the same thing didn't found the solution for this.

**Comment by samdark** [comment]
@drinkncode is that real requirement in your app to display error for exactly one field at the top of the form?

**Comment by drinkncode** [comment]
@samdark Yes, i can even provide an screenshot, we are already doing this in our website which is on Yii 1.1..and this is not possible in Yii 2.0..
Here is the screenshot please check, its on Yii 1.1..
![2015-09-17_1755](https://cloud.githubusercontent.com/assets/14182019/9932940/5baeb7e4-5d65-11e5-8ac8-7d55dc8f12b7.png)

**Comment by samdark** [comment]
Umm... but summary should work in this case.

**Comment by drinkncode** [comment]
But summary doesn't accept any parameters, which can limit the errors to a particular attribute, like..
    <?= $form->errorSummary($model, ['attributes'=>'username']); ?> // Not applicable
if nothing is passed it can show all the errors.. Or possible please add error function in the class ActiveForm.just like yii 1.0 used to have..

**Comment by samdark** [comment]
What if email is filled correctly but password isn't filled?

**Comment by drinkncode** [comment]
It says "Email/Password can't be empty", which we show that to user by adding that error in "username" attribute..by the code below..

     $this->addError('username', 'Email/Password can't be empty');

and if login credentials are wrong we display that using..

     $this->addError('username', 'Invalid username or password');

also when user clicks on forgot password we validate the username only and can display message for email only not for password.

**Comment by samdark** [comment]
OK but then summary won't display multiple lines since there are no multiple errors...

**Comment by drinkncode** [comment]
Ok here is the catch, there will always be two errors, when we have entered invalid email id or special characters or something else, i.e
"Email id is not a valid email address"
"Email/Password can't be empty"

where errorSummary will display all at the same time, but this->error("username"), queue them and always displays error at the 0 index.

**Comment by samdark** [comment]
If these are for the same attribute and you haven't touched `skipOnError` (it's `true` by default) then it will be one error.

**Comment by samdark** [comment]
It's a very bad idea to use one field error instead of summary.
