### ISSUE TITLE
Provide a Formatter for distance

### ISSUE THREAD

**Issue by cbhp** [yiisoft/yii2#9703]
Please provide a formatter for distance, e.g. given a value in meters:
891 -> 891 m
2305 -> 2.3 km
86397 -> 86.4 km

(km: kilometers)

**Comment by klimov-paul** [comment]
This can work only for metrical length system. But what about miles and so on?

**Comment by nineinchnick** [comment]
This would be a different formatter then? The less common one could use a prefix/suffix in the name.

**Comment by klimov-paul** [comment]
The problem with 'miles' is there is no 'kilo-miles'. 1 mile = 1,760 yards. So, yes this is quite a different formatter.

Also: 1 mile = 1.609344 kilometers.

And finallly: how do you attempt to find out which measure units are for the raw value, you are willing to format? Who tells it is always a metre?

This issue seems to not belong to the core.

**Comment by klimov-paul** [comment]
There are many different systems of measure units: 'SI', 'CGS' and so on.
Each uses different measure units as canonical. Who can tell if raw length is saved in 'meters' or 'milimeters' or even 'yards'?
This is too project specific.

**Comment by nineinchnick** [comment]
But the metric system is very common compared to others. The formatter could take a multiplier argument to determine the base unit.

**Comment by klimov-paul** [comment]
> But the metric system is very common compared to others

Well, tell this to the 300 millions people living in USA.

> The formatter could take a multiplier argument to determine the base unit.

In the same project I may have several different canonical unit of length: I may write building size n meters, roads in kilometers, while I may be working with nanometers for the main production.

Also who tells formatter should agregate measure units from low (metre) to high (klimometre). It could be quite an opposite need - convert 'metre' to 'nanometre'.

Such formatter may be created for the particular project, but in can not be universal.

**Comment by samdark** [comment]
It can be universal if you'll find a huge pile of data that describes all possible formats on planet earth. I'd look at CLDR.

**Comment by cbhp** [comment]
I suggest the source data has to be a SI base unit (metre, kilogram, second, ...) and the formatter would format the value in a human readable output.
https://en.wikipedia.org/wiki/International_System_of_Units#Base_units
