### ISSUE TITLE
Memcached expire cannot exceed 30 days

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#9707]
According to PHP manual Memcached expire cannot be more than 30 days. (http://php.net/manual/en/memcache.set.php).
If it does, the value is not set but Memcached ext. returns true!

I suggest in the \yii\caching\MemCache @ setValue(...) to limit the duration to 30 days (or throw some exception or at least a warning in the logs).

**Comment by samdark** [comment]
Does it apply to `memcache` only or to `memcached` as well? These are two separate extensions.

**Comment by Vatruha** [comment]
According to this http://php.net/manual/ru/memcache.set.php for Memcache we have the same thing.

> expire
Expiration time of the item. If it's equal to zero, the item will never expire. You can also use Unix timestamp or a number of seconds starting from current time, but in the latter case the number of seconds may not exceed 2592000 (30 days).

**Comment by samdark** [comment]
OK. Makes sense to throw an exception or at least to write something to logs.

**Comment by samdark** [comment]
What do you think is better?

**Comment by klimov-paul** [comment]
Perhaps it is better to truncate expiration value to 30 days silently.
Cache is an unreliable storage by definition, so I supose such solution is acceptable.

**Comment by samdark** [comment]
Probably yes since it is very unlikely that exception will be handled.

**Comment by ptheofan** [comment]
The only thing that would not break backward compatibility would be to silently override it and set it to 30 days.
And if we add appropriate comments there then any developer not familiar with the limitation would very easily discover why his cache is not really set.
Ideally however, a warning in the logs in debug mode would be the best - makes it easier to spot on staging environments.

**Comment by nikashitsa** [comment]
Done as you discussed. Looking forward for feedback :wink:
