### ISSUE TITLE
LinkPager set class for li item's

### ISSUE THREAD

**Issue by ShNURoK42** [yiisoft/yii2#9711]
Hi,

I'm using BEM methodology and in it I need set class for each elements.
Can you add a properity `$internalPagesCssClass = null;` in LinkPager?
I can do PR for it, if you agree.

**Comment by samdark** [comment]
`$pageCssClass` could be added with `null` as default value and used in `renderPageButton()` method:

```php
$options = ['class' => $class === '' ? $this->pageCssClass: $class];
```

**Comment by ShNURoK42** [comment]
@samdark it works if `$class === ''` changed to `$class === null` or `$buttons[] = $this->renderPageButton($i + 1, $i, null, false, $i == $currentPage);` to `$buttons[] = $this->renderPageButton($i + 1, $i, '', false, $i == $currentPage);`

**Comment by ShNURoK42** [comment]
We can check $class as in https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1772 changed `$class === ''` to `empty($class)`? Maybe it more correct.

**Comment by samdark** [comment]
Yes.
