### ISSUE TITLE
Integer validation not working if value has 2 or more leading minus/plus signs

### ISSUE THREAD

**Issue by tekord** [yiisoft/yii2#9715]
I have a form with integer attributes. Form model has the following rules:

```php
...
[['area', 'seatCount'], 'required'],
[['area', 'seatCount'], 'integer', 'min' => 0],
...
```

Here is a screenshot of validation result (english translation below): https://i.gyazo.com/61064d9d98da19aa011b5e852d39debc.png

The first field is 'Area', error message: "Area must be not less than 0" (it is `integer` validator)
The second field is 'Seat Count', error message: "Seat count cannot be blank" (it is 'required' validator).

The problem is the Seat Count is filled. It is not blank. It should be validated as number and shows error message: Seat Count must be integer. But integer validator number pattern does not recognize value as number due to sequence of leading minuses (leading pluses as well).

I guess it is bug.

**Comment by klimov-paul** [comment]
Unable to reproduce. Number validator works correctly for the value containing multiple minus or pluses.
It must be something else breaking your form.
