### ISSUE TITLE
Session compability within Yii1 and Yii2

### ISSUE THREAD

**Issue by dieend** [yiisoft/yii2#9723]
We are currently on progress of migrating to Yii2 from Yii1. Is the session key compatible? If it isn't, is there any way to have Yii2 using same session with Yii1? Assume we are using same storage to store the session (in our case, memcache).

**Comment by klimov-paul** [comment]
@dieend, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
