### ISSUE TITLE
InvalidConfigException 'Unable to determine the entry script URL' when using Apache 2.4 Alias Directive

### ISSUE THREAD

**Issue by scottbeacher** [yiisoft/yii2#9725]
I'm using Yii2 as a REST API for a single page app. Both code bases reside on the same server and are configured using virtual hosts. I am using Yii2 to serve up the sitemap.xml for the front end site. Since they are on the same server (but different subdomains) My virtual host is configured like this:

    <VirtualHost *:80>
       ServerName testserver.dev
       DocumentRoot "D:\Path\to\public\build"

       Alias /sitemap.xml "D:\Path\to\yii2\web\index.php"
    </VirtualHost>

When I make a call to http://testserver.dev/sitemap.xml it correctly makes the request through Yii2, however, I get an `InvalidConfigException` in `yii\web\Request.php` in the `getScriptUrl` function because $scriptFile is not matched in $_SERVER['DOCUMENT_ROOT'] and Yii2 doesn't know how to handle it. 

I've temporarily gotten around the issue by setting `SetEnv ORIG_SCRIPT_NAME "/index.php"` in my virtual host definition since I'm using PHP as an apache module, but this is obviously not optimal and is just a temporary hack. Should Yii2 be able to handle this or am I just trying to do something too weird?

My stack is Wampserver 2.5 (Apache 2.4.9 and PHP 5.5.12) running on Windows 7 x64. The version of Yii I'm using is 2.0.6

**Comment by samdark** [comment]
How would you solve it?

**Comment by cebe** [comment]
Why did you alias the sitemap to index.php?

**Comment by scottbeacher** [comment]
@samdark not sure. If there is no automated way to figure it out then perhaps a similar solution to what I'm currently doing, only use a custom environment variable that overrides it for a situation like this? Something like YII_CUSTOM_DOCUMENT_ROOT?

@cebe I had to use the alias because otherwise the front end framework (ember) would take over the routing. I can't use that to just call an api that returns the sitemap data because once the single page app loads it has already sent the headers so I can't return the sitemap as raw xml.

**Comment by cebe** [comment]
What about using mod_rewrite instead of Alias? Should work fine with a rewrite rule.

**Comment by scottbeacher** [comment]
@cebe If I used mod_rewrite I would have to actually redirect the URL. Since my use case here is for the sitemap if I redirected to a different subdomain the URLs in the sitemap would then be incorrect as the domain would differ in the URL compared to them. (i.e. www vs api)

**Comment by cebe** [comment]
All normal URL rewrite works this way, I do not see why it shouldn't work in your case. Why would you need to redirect?

**Comment by samdark** [comment]
Closing since no information required to make a decision was provided for a long time.
