### ISSUE TITLE
header referer lost

### ISSUE THREAD

**Issue by Yannyezixin** [yiisoft/yii2#9726]
it exists when I route to create, but it's lose when i route to my custom action, such as demo.

       Request URL:http://localhost:8484/system/permission/create

       Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
       Accept-Encoding:gzip, deflate, sdch
       Accept-Language:zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
       Connection:keep-alive
                                            Cookie:68240766fd8257b8f586d495d87232bd=d4ae4bcff0e398e40b8cb6658e47a092a7f9afe5a%3A4%3A%7Bi%3A0%3Bs%3A5%3A%22admin%22%3Bi%3A1%3Bs%3A5%3A%22admin%22%3Bi%3A2%3Bi%3A2592000%3Bi%3A3%3Ba%3A1%3A%7Bs%3A8%3A%22username%22%3Bs%3A5%3A%22admin%22%3B%7D%7D;          _csrf=94e85ec0dc65178c2731ae345fd534e6ec88ac43f18ac36ac368ba7d03d9c40ca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%228jSOwYrXBhIbNoozZtIMmT9m4SuiIO1F%22%3B%7D; PHPSESSID=shb666ml5oi1n2auufg23usu73
        Host:localhost:8484
        Referer:http://localhost:8484/system/permission/index
        Upgrade-Insecure-Requests:1
        User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)        Chrome/45.0.2454.85 Safari/537.36 

       Request URL:http://localhost:8484/system/permission/demo?id=12
        it will lose referer

**Comment by cebe** [comment]
referer is sent by the browser or other HTTP client, what should yii do about this?

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
