### ISSUE TITLE
Nice to have - Yii2 serverside and Yii2 clientside packages instead of all in one

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#9730]
Yii2 package comes by default bundled with clientside package including jquery, etc. Although this is not really an issue it would be nice if the framework was split in - say serverside and clientside packages. This way, when building RESTful API and web services that are only serverside our codebase would be clean of stull like jquery keeping our composer install and update runs also significantly smaller.

**Comment by cebe** [comment]
#9525

**Comment by tunecino** [comment]
there is also this open discussion about re-designing the RESTful API : #3635

**Comment by dhoomm** [comment]
+1
