### ISSUE TITLE
wrong gii relation generation

### ISSUE THREAD

**Issue by pkirill99** [yiisoft/yii2#9731]
hi all

yii 2.0.6, php 5.6.12, postgreesql 9+

i have this table:

```
$this->createTable('{{%table_suppliers}}', [
    'id'         => $this->bigPrimaryKey(),
    'identifier' => $this->string(32)->notNull()->unique(),
    'name'       => $this->string(32),
]);


$this->createTable('{{%table_main}}', [
    'id'          => $this->bigPrimaryKey(),
    'supplier_id' => $this->bigInteger()->notNull(),
    'name'        => $this->string(32),
    'updated'     => 'timestamp(3) with time zone DEFAULT NOW()',
    'logging'     => $this->boolean()->notNull()->defaultValue(false),
]);

$this->addForeignKey('{{%table_main_fkey_supplier}}', '{{%table_main}}', 'supplier_id', '{{%table_suppliers}}', 'id', 'CASCADE', 'CASCADE');
$this->createIndex('{{%table_main_idx_id_supplier}}', '{{%table_main}}', 'id, supplier_id', true);

$this->createTable('{{%table_properties}}', [
    'id'          => $this->primaryKey(),
    'supplier_id' => $this->bigInteger()->notNull(),
    'main_id'   => $this->bigInteger(),
    'value'       => $this->string(255)->notNull(),
]);

$this->addForeignKey('{{%table_properties_fkey_suppliers}}', '{{%table_properties}}', 'supplier_id', '{{%table_suppliers}}', 'id', 'CASCADE', 'CASCADE');
$this->addForeignKey('{{%table_properties_fkey_main}}', '{{%table_properties}}', 'main_id, supplier_id', '{{%table_main}}', 'id, supplier_id', 'CASCADE', 'CASCADE');
$this->createIndex('{{%table_properties_idx_value}}', '{{%table_properties}}', 'value');
```

gii generated this model and relation:

```
class Supplier extends \yii\db\ActiveRecord
{
    public static function tableName() {
        return '{{%table_suppliers}}';
    }

    ..........
    public function getTableMain() {
        return $this->hasOne(TableMain::className(), ['supplier_id' => 'id']);
    }
    public function getTableProperties() {
        return $this->hasMany(TableProperties::className(), ['supplier_id' => 'id']);
    }
}
```

why in model relation "TableMain" with "hasOne" function ?

**Comment by pkirill99** [comment]
sorry, wrond migration

this true:


		$this->createTable('{{%tables_suppliers}}', [
			'id'         => $this->bigPrimaryKey(),
			'identifier' => $this->string(32)->notNull()->unique(),
			'name'       => $this->string(32),
		]);


		$this->createTable('{{%table_main}}', [
			'id'          => $this->bigPrimaryKey(),
			'supplier_id' => $this->bigInteger()->notNull(),
			'sub_id'      => $this->string(32),
			'name'        => $this->string(32),
			'updated'     => 'timestamp(3) with time zone DEFAULT NOW()',
			'logging'     => $this->boolean()->notNull()->defaultValue(false),
		]);
		$this->addForeignKey('{{%table_main_fkey_supplier}}', '{{%table_main}}', 'supplier_id', '{{%tables_suppliers}}', 'id', 'CASCADE', 'CASCADE');
		$this->createIndex('{{%table_main_idx_id_supplier}}', '{{%table_main}}', 'id, supplier_id', true);
		$this->execute('CREATE UNIQUE INDEX tables_main_idx_supplier_nullsub ON table_main (supplier_id) WHERE (sub_id IS NULL);');


		$this->createTable('{{%table_properties}}', [
			'id'          => $this->primaryKey(),
			'supplier_id' => $this->bigInteger()->notNull(),
			'main_id'     => $this->bigInteger(),
			'value'       => $this->string(255)->notNull(),
		]);
		$this->addForeignKey('{{%table_properties_fkey_supplier}}', '{{%table_properties}}', 'supplier_id', '{{%tables_suppliers}}', 'id', 'CASCADE', 'CASCADE');
		$this->addForeignKey('{{%table_properties_fkey_table}}', '{{%table_properties}}', 'main_id, supplier_id', '{{%table_main}}', 'id, supplier_id', 'CASCADE', 'CASCADE');
		$this->createIndex('{{%table_properties_idx_value}}', '{{%table_properties}}', 'value');

**Comment by nineinchnick** [comment]
The reason is because there's an unique index on the FK column. Currently, gii does not detect that there is an extra condition.

The implementation of `\yii\db\pgsql\Schema::getUniqueIndexInformation()` should be extended.

**Comment by nineinchnick** [comment]
I'm not sure how this can be resolved. We either have to change the output of `\yii\db\Schema::findUniqueIndexes()` or ignore unique constraints with conditions.
