### ISSUE TITLE
gii not like "void" word in table

### ISSUE THREAD

**Issue by pkirill99** [yiisoft/yii2#9732]
hi all

this is not very important bug, but it is

php 5.6.12, yii2.0.6, postgresql 9+

		$this->createTable('{{%table}}', [
			'id'   => $this->primaryKey(),
			'name' => $this->string()->notNull()->unique(),
		]);

		$this->createTable('{{%userauth_main_table_integer}}', [
			'id'       => $this->primaryKey(),
			'status'   => $this->integer()->notNull()->defaultValue(10),
			'username' => $this->string()->notNull()->unique(),
		]);
		$this->addForeignKey('{{%userauth_main_table_integer_fkey_status}}', '{{%userauth_main_table_integer}}', 'status', '{{%table}}', 'id', 'CASCADE', 'CASCADE');

		$this->createTable('{{%userauth_main_table_void}}', [
			'id'       => $this->primaryKey(),
			'status'   => $this->integer()->notNull()->defaultValue(10),
			'username' => $this->string()->notNull()->unique(),
		]);
		$this->addForeignKey('{{%userauth_main_table_void_fkey_status}}', '{{%userauth_main_table_void}}', 'status', '{{%table}}', 'id', 'CASCADE', 'CASCADE');

gii generated:

    /**
    *
    * @property UserauthMainTableInteger[] $userauthMainTableIntegers
    * @property UserauthMainTableVoid[] $userauthMainTableVos
    */
    class Table extends \yii\db\ActiveRecord
    {
    ...............

    public function getUserauthMainTableIntegers()
    {
        return $this->hasMany(UserauthMainTableInteger::className(), ['status' => 'id']);
    }

    public function getUserauthMainTableVos()
    {
        return $this->hasMany(UserauthMainTableVoid::className(), ['status' => 'id']);
    }
    }

why gii generated name userauthMainTableVos ?? true name in userauthMainTableVoids
and also for relation "hasOne" generated name "userauthMainTableVo"

but relation "getUserauthMainTableIntegers" name length is more than "getUserauthMainTableVos"....

**Comment by SilverFire** [comment]
I think it does not like `id` ending :)

Vos = Vo~~id~~**s**

**Comment by SilverFire** [comment]
I don't know how to fix it carefully

**Comment by samdark** [comment]
Migrated to https://github.com/yiisoft/yii2-gii/issues/119
