### ISSUE TITLE
AssetManager generate css id and class

### ISSUE THREAD

**Issue by jiyi1990** [yiisoft/yii2#9734]
Hi,

    I want to generate some css link like '<link rel="stylesheet" href="style.css" class="main" id="main" />'.
I know  'public $css = ['css/site.css'];' can generate <link rel="stylesheet" href="../assets/css/ace.css" />,
but how can i generate the id and class use the AssetManager?

                                                                                                                           Thank you very much!

**Comment by samdark** [comment]
Please use forum for questions.
