### ISSUE TITLE
Небольшие замечания по документации

### ISSUE THREAD

**Issue by pantsarny** [yiisoft/yii2#9735]
Добрый день. В примерах конфигурации nginx https://github.com/yiisoft/yii2/blob/master/docs/guide/start-installation.md я заметил несколько неточностей,а именно:
try_files $uri $uri/ /index.php?$args;
рекомендую заменить на 
try_files $uri $uri/ /index.php$is_args$args;
и
fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
подправить на
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

**Comment by samdark** [comment]
Почему?

**Comment by pantsarny** [comment]
Первый момент - параметров может и не быть, $is_args подставляет '?' только если есть $args
Второй момент, $fastcgi_script_name начинается с "/" и в результате получается 2 слеша подряд.

**Comment by samdark** [comment]
Спасибо!
