### ISSUE TITLE
Force asset re-publishing when deploying to production

### ISSUE THREAD

**Issue by nirvana-msu** [yiisoft/yii2#9736]
I am looking for some guidance on properly propagating updates to js/css code in production. By default, if the asset folder is already published, `AssetManager` will not overwrite it. In development environment there are two ways to deal with it: either delete published assets folder manually, or set `forceCopy` of `AssetManager` to true to republish assets on each request.

Republishing assets on each request is obviously not acceptable for production due to performance reasons. And in fact, the only time code gets changed is when you deploy it, so this is the only time you really need to re-publish assets.

So I see three solutions to my problem:

1. Add a few lines to the deployment script (e.g. git post-receive hook) to clear `/web/assets` folder content when deploying.
2.  Create "official" yii console command or script that would do the same as above, and execute that. In fact, file/folder permissions get reset each time code is checked out by the git `checkout` command, so I have to call `./yii init` on each deploy to update them. Might as well just add (optional) asset removal to the same script.
3. I am running `asset/compress` as part of my deployment script. If it had `forceCopy` option that would force asset re-publishing, that would also solve my problem - at least for those assets that get compressed (but probably not for the others).

Any thoughts on what is the right way to approach this? I guess for now I will just stick to option 1, but I was hoping yii would provide a solution for this out of the box.

**Comment by dynasource** [comment]
this is not an Yii issue, but my tip for you is not to use 'forceCopy' for a deploy.
A better way is to:
- deploy your app + vendor stuff to a new empty folder. 
- after your deploy is complete, change all references to the new folder
- then your website will automatically use the new clean deployment (including compressed assets)
- after the deploy, clear your assets folders, which will be regenerating

**Comment by klimov-paul** [comment]
There is no universal solution for production server update. It depends on server type (dedicated or cloud) and other parameters.

For the ispiration you can look at:
https://github.com/yii2tech/selfupdate
