### ISSUE TITLE
Error while installing with composer

### ISSUE THREAD

**Issue by semir-karic** [yiisoft/yii2#9738]
When I try to install using composer I get the following error:
[ErrorException]
  Argument 1 passed to Fxp\Composer\AssetPlugin\Repository\BowerRepository::createVcsRepositoryConfig() must be of the t
  ype array, null given, called in /root/.composer/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.
  php on line 136 and defined

**Comment by agungsijawir** [comment]
duplicate with #9737

**Comment by semir-karic** [comment]
S.  V. Vv. Vvv   vw.  242,
