### ISSUE TITLE
Stringvalidator crashes on intl icu version 55.1

### ISSUE THREAD

**Issue by PietDeVries** [yiisoft/yii2#9742]
StringValidator defines: 
$this->tooLong = Yii::t('yii', '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.');

This works fine locally on php 5.6.11 using INTL ICU version 54.1

On my server on PHP 5.6.13 using INTL ICU version 55.1 it causes a crash in 
MessageFormatter->format.  

By redefining toolong as '{attribute} should contain at most {max} characters.' the problem was solved.

**Comment by cebe** [comment]
yes, this is an issue with ICU, what should we do about it?

**Comment by PietDeVries** [comment]
There will be more people like me, that cannot control the icu version on the server. 
So maybe we should have a workaround because it will cost them quite some time to figure out the cause of the problem and to make their own workaround.

**Comment by samdark** [comment]
First of all, it should be reported to PHP bug tracker for intl extension (if it's not there yet).

**Comment by samdark** [comment]
@cebe is it ICU crashing or intl crashing?

**Comment by cebe** [comment]
afair it was a bug in ICU but not sure

**Comment by PietDeVries** [comment]
Could be there was something wrong with the intl icu implementation on the server I use.
The provider removed it and of course the problem is over now.
Issue can be closed as far as I'm concerned.
