### ISSUE TITLE
No interface for yii\db\Connection

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#9743]
Most of the AR stack in Yii is programmed against interfaces.

If I want to, for example, create a custom ActiveQuery class, I could create an empty class and implement the required interfaces. (Note that in practice extending the class provided by Yii is usually a better idea).

Ideally, there would be an interface for database connections as well, so I could implement my new connection class.

**Comment by SamMousa** [comment]
Considering you already have https://github.com/yiisoft/yii2-elasticsearch/blob/master/Connection.php I think there already is some implicit interface for connections.

**Comment by cebe** [comment]
for what kind of connection should that be useful? note that there is a siginficant difference between how SQL based Connection works and how the nosql connections work.

**Comment by SamMousa** [comment]
I'm not diving into creating an AR stack that talks to (a) REST service. (#3635).

Just looking into the whole AR stack there is something missing for the connection. I think most connections have some stuff in common...
Things like:
- getIsActive
- open 
- close

Also it is unclear whether I could implement a non-pdo connection (for some sql backend) since $pdo is public and I have no idea what the requirements are.
Sidenote: Looking into the other classes in the stack I can probably make #3635 work at the query level, without implementing a specific interface in the connection object, but still if there is some implicit interface it should be made explicit.

Feel free to close if you disagree, will reopen if I can come up with an actual case where this is a must.

**Comment by SamMousa** [comment]
Oh, found it!
ActiveRecordInterface requires me to implement the getDb function with return type mixed..
Either that should be removed or it should have return type ConnectionInterface.

Having a mixed return type in an interface doesn't help me at all when implementing this function.. I know it is required by the framework, but have no idea how the framework will use it...


    /**
     * Returns the connection used by this AR class.
     * @return mixed the database connection used by this AR class.
     */
    public static function getDb();

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/pull/9859#issuecomment-263091903
