### ISSUE TITLE
FileValidator wrong mimetype for dotx

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#9744]
I could not upload/check any `.dotx` file, because the FileValidator does check the mimetype with `finfo_file` which gives me 
```
application/vnd.openxmlformats-officedocument.wordprocessingml.document
```
which is wrong. The correct mime type would be
```
application/vnd.openxmlformats-officedocument.wordprocessingml.template
```
which is correctly defined in the `mimeTypes.php` file.

I currently don't know why finfo gives a wrong mimetype.

**Comment by SilverFire** [comment]
Seems not a Yii problem.

I can offer you two solutions:
 - create your own `mimeTypes.php` and merge `['dotx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']` with contents of default one. Then configure `FileHelper` and set the `mimeMagicFile` pointing to your customized file.
 - in model rule of file validation set `'checkExtensionByMimeType' => false`. Be careful about this, it is not reliable but would work at least.
