### ISSUE TITLE
yii\helpers\Url isRelative will return false when url is relative

### ISSUE THREAD

**Issue by takashiki** [yiisoft/yii2#9747]
in yii\helpers\BaseUrl

```php
    public static function isRelative($url)
    {
        return strncmp($url, '//', 2) && strpos($url, '://') === false;
    }
```

`strncmp($url, '//', 2)` will return 0 when the url is start with '//'

**Comment by samdark** [comment]
`//` not relative URL. It is absolute.

**Comment by takashiki** [comment]
oh, I get it now. I thought this function is used for validate protocol relative url.
