### ISSUE TITLE
Extract events from Component class into trait

### ISSUE THREAD

**Issue by omnilight** [yiisoft/yii2#9748]
Currently, if I want to use events in my class, I have to make it a child fo the `Component`. But `Component` class have a lot of other functions, that I do not need.

Whould not it be more useful, if we have somthing like `EventsTrait` , which we can to use in any class?

``` php
trait EventsTrait
{
   public function on(...) { ... }
   public function off(...) { ... }
   public function trigger(...) { ...}
}
```

``` php
class Component
{
   use EventsTrait;
}
```

**Comment by mdmunir** [comment]
https://github.com/yiisoft/yii2/wiki/Ideas-for-2.1

**Comment by lichunqiang** [comment]
I want to know when will the 2.1 will be birthed.

**Comment by omnilight** [comment]
But 2.1 - will break backward compatibility. Implementing events as trait - will not. So why have we to wait for 2.1 for this thing?

**Comment by rob006** [comment]
See https://github.com/yiisoft/yii2/pull/12929#issuecomment-322903648

**Comment by samdark** [comment]
See https://github.com/yiisoft/event-dispatcher
