### ISSUE TITLE
Using Response::FORMAT_RAW can lead to information-leak

### ISSUE THREAD

**Issue by da-mkay** [yiisoft/yii2#9750]
Yii: 2.0.6

If an Exception is thrown then Yii's web/ErrorHandler will do a good job if the response type is HTML or JSON: if YII_DEBUG is not set then only 'An internal server error occurred.' is shown instead of a full call trace.

However if the response format is set to FORMAT_RAW then web/ErrorHandler never checks if YII_DEBUG is set and always sets the response data to the thrown exception. Thus the complete exception including the call stack is shown to end users even if YII_DEBUG is not set.

I think it would be better to show the same 'An internal server error occurred.'-message to end users instead. Otherwise at least the server's folder structure is revealed.

Code to reprocude:

    public function actionFoo()
    {
        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_RAW;
        
        $foo++; // throws an exception
        
        return $response;
    }

**Comment by samdark** [comment]
Already fixed by #9874
