### ISSUE TITLE
Extend migrations (ColumnSchemaBuilder): add support of db\Expression into ColumnSchemaBuilder::default()

### ISSUE THREAD

**Issue by IStranger** [yiisoft/yii2#9752]
Currently, when i do (in migration class):
```php
$this->timestamp()->defaultValue('NULL')
```
builder makes following SQL: `TIMESTAMP DEFAULT "NULL"`
  
I suggest to add support of db/Expression:
```php
$this->timestamp()->defaultValue(new \yii\db\Expression('NULL'))
```
and we get: `TIMESTAMP DEFAULT NULL`

For this need small modification, for example, like this:
https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchemaBuilder.php#L164
```php
if ($this->default instanceof \yii\db\Expression) {
    return ' DEFAULT ' . $this->default;
}
```

**Comment by klimov-paul** [comment]
Duplicates #9337
