### ISSUE TITLE
Extend migrations (ColumnSchemaBuilder): add support NULL value of column

### ISSUE THREAD

**Issue by IStranger** [yiisoft/yii2#9753]
Currently we can define `NOT NULL` value of column using method `\yii\db\ColumnSchemaBuilder::notNull()`

But how define `NULL` value of column? Possible should change implementation of this method:
https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchemaBuilder.php#L143
```php
    protected function buildNotNullString()
    {
        return $this->isNotNull ? ' NOT NULL' : ' NULL';
    }
```

**Comment by samdark** [comment]
NULL is default. No need to define it.
