### ISSUE TITLE
Different rules with default min/max values for different kind of field types

### ISSUE THREAD

**Issue by shamyyl** [yiisoft/yii2#9756]
I have int4 field in my postgres database table. Gii generates for this field "integer" rule without default min/max values. 
So when i try to add 4 000 000 000 value in this field postgres throws the exeption: 

```
"4000000000" is not a valid integer value.
```

Ok.
I don`t want to add for all my models min/max values in integer rules and override `init()` method in `yii\validators\NumberValidator`:

``` php
namespace app\components\validators;
class NumberValidator extends \yii\validators\NumberValidator
{
    public function init()
    {
        if ($this->max === null && $this->integerOnly) {
            $this->max = 2147483647;
        }

        if ($this->min === null && $this->integerOnly) {
            $this->min = -2147483648;
        }

        parent::init();
    }
} 
```

and add the next code in index.php:

``` php
\Yii::$container->set(
        'yii\validators\NumberValidator',
        ['class' => '\app\components\validators\NumberValidator']
    );
```

But khow validation return false, when i try add 4 000 000 000 value in int8 field, because gii generate "integer" rule for int2, int4 and int8 fields:

``` php
namespace yii\gii\generators\model;
class Generator extends \yii\gii\Generator
{
    public function generateRules($table)
    {
     ...
            switch ($column->type) {
                case Schema::TYPE_SMALLINT:
                case Schema::TYPE_INTEGER:
                case Schema::TYPE_BIGINT:
                    $types['integer'][] = $column->name;
                    break;
       ...
      }
}
```

**What about create different rules with default min/max values for different kind of field types?**

Something like this:

``` php
namespace yii\gii\generators\model;
class Generator extends \yii\gii\Generator
{
    public function generateRules($table)
    {
     ...
            switch ($column->type) {
                case Schema::TYPE_SMALLINT:
                    $types['smallint'][] = $column->name;
                    break;
                case Schema::TYPE_INTEGER:
                    $types['integer'][] = $column->name;
                    break;
                case Schema::TYPE_BIGINT:
                    $types['bigint'][] = $column->name;
                    break;
       ...
      }
}
```

**Comment by samdark** [comment]
Could be done but the limits are different for each database.

**Comment by shamyyl** [comment]
It will be in the next version?

**Comment by samdark** [comment]
I don't know. It doesn't look like a simple task. Each database has its own limits.

**Comment by shamyyl** [comment]
Maybe then just to be able to create separate validators for different column types without default min/max values.
Who else will have to limit values (such as I), is to do it yourself.
While I can not set limits separately for each type of

**Comment by samdark** [comment]
Well, the output of Gii is meant to be corrected and I think if there's min/max it is easier to correct it than to add such validator from scratch.

If you have an idea how to support it for all databases and types, propose solution.

**Comment by shamyyl** [comment]
Ok
