### ISSUE TITLE
Pjax Broken in GridView

### ISSUE THREAD

**Issue by osCMattiFinn** [yiisoft/yii2#9757]
Adding Pjax to a gridview (freshly generated CRUD) - the Ajax fires, however it then aborts and the page reloads - tested search filters and pagination.

Followed the simple directions here: http://www.yiiframework.com/doc-2.0/yii-widgets-pjax.html

**Comment by derekisbusy** [comment]
What's your controller return on the Pjax request? Also it will do this if the page request times out. 

https://github.com/defunkt/jquery-pjax#pjax-options

The default is 650 ms so if your script doesn't return data before 650ms then the page will refresh.

**Comment by osCMattiFinn** [comment]
I have a test action (ActionColumn) which returns nothing, so all that should happen is that the Ajax request fires.  I see that the Ajax request fires, then the page refreshes to the action.

The same happens using the pagination and the search filters.

I also tested on a freshly generated CRUD with no changes whatsoever other than adding Pjax.  Both the search filters and pagination do the same.

There is no timeout, the page starts refreshing immediately.

I set the timeout to something ridiculous and it still refreshes the page.

Test it yourself, it's a bug.

**Comment by samdark** [comment]
Instead of returning nothing try returning `123`.

**Comment by osCMattiFinn** [comment]
"Instead of returning nothing try returning 123."

Which makes no difference.

I also tested on a freshly generated CRUD with no changes whatsoever other than adding Pjax. Both the search filters and pagination do the same.

**Comment by osCMattiFinn** [comment]
Why don't you guys test this yourselves.  I have tested again on a perfectly fresh install with one siimple table, model and CRUD generated by Gii:

```php
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'artist_name',
            'artist_bio:ntext',
            'artist_image',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
	<?php Pjax::end(); ?>
```

**Comment by nineinchnick** [comment]
What's the server response code for the ajax request?

**Comment by osCMattiFinn** [comment]
The request is "aborted" because the page reloads.

If I copy and paste the Ajax request into my browser the page loads with what we would expect the Ajax request to return.

Its the same as though you fire an Ajax request from a hyperlink and forget to put 'return false' in your code.  That is how it's behaving.

Please take the time to try it yourself.

**Comment by duynguyen0511** [comment]
can you post Controller, View and model on Gist (https://gist.github.com/) ?

I usualy Pjax + Gridview alot and dont have the refresh issues at all.

**Comment by osCMattiFinn** [comment]
You can see the files here.

They are virgin CRUD with only the call to Pjax added.

https://gist.github.com/osCMattiFinn/f57746adc1f15ea0cfdd

**Comment by duynguyen0511** [comment]
try this 

```php
<php \yii\widgets\Pjax::begin(['id' => 'my-grid', 'timeout' => false, 'enablePushState' => false, 'clientOptions' => ['method' => 'POST']]) ?>
```

My guess is the timeout is the issue. Set it to false and you are good

**Comment by derekisbusy** [comment]
Try this patch...

https://github.com/yiisoft/yii2/pull/9432

**Comment by osCMattiFinn** [comment]
Patch #9432 made no difference.

Setting 'timeout' => false fixed the issue.  Why does it timeout so quickly?  Clearly 650ms is too low a setting....

**Comment by samdark** [comment]
It's a default, I guess.

**Comment by samdark** [comment]
I don't think we can do anything about it.
