### ISSUE TITLE
 forgotten in comment?

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#9758]
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1024

**Comment by cebe** [comment]
? Whats wrong with that?

**Comment by samdark** [comment]
I guess `$asArray` property name missing.

**Comment by samdark** [comment]
Thanks!

**Comment by cebe** [comment]
Wtf? The docblock is totally valid! it describes the property defined by this getter.

**Comment by kidol** [comment]
@cebe It's at top of file. Same with $primaryKey.

**Comment by samdark** [comment]
Hmm... are you sure it is valid to use `@property` like that?

**Comment by cebe** [comment]
@kidol @samdark the comment on top of the class is generated from this `@property` annotation. 
@samdark it is not official PHPdoc but yii internal.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/blob/master/build/controllers/PhpDocController.php#L545-L549

**Comment by kidol** [comment]
@cebe Thanks for info, but what's reason for it? Wouldn't it work the same if method doc had $property variable?

**Comment by cebe** [comment]
the reason for this is that the description of the getter method does not fit as a proper description for the property because the return value differs dependend on a parameter. the property does not differ because the parameter always has default value.

**Comment by lynicidn** [comment]
hm hm hm, for it your construct bicycle ?
/**
@property mixed $user [[getUser()]] ///read-only
@property mixed $user [[getModel()]] [[setModel()]]
**/

**Comment by cebe** [comment]
???

**Comment by kidol** [comment]
@lynicidn Not sure what you mean but Yii automatically adds "This property is read-only" in doc comment on top in case there is no setter.
