### ISSUE TITLE
default attribute value after validation errors

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2#9761]
Add something like 'error' validator with 'value' => 'foobar' or add to 'default' validator like 'applyOnErrors' => true to insure that attribute has default value even on errors, useful for DynamicModel. DynamicModel need addRules([]) method too :)

**Comment by klimov-paul** [comment]
> Add something like 'error' validator with 'value' => 'foobar' or add to 'default' validator like 'applyOnErrors' => true to insure that attribute has default value even on errors

Use `skipOnError = false`.

> DynamicModel need addRules([]) method too

I don't think so. Dynamic model exist mainly for the ability to run single validator against absstract value.
Even if several rules need to be attached it is easy enough with the current syntax.

**Comment by DrDeath72** [comment]
skipOnErrors = false didn't work, because 'default' apply only empty values. error value not empty :)

->addRule() * 10 better ->addRules([]) * 1?
