### ISSUE TITLE
Json response formatting

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#9762]
When creating Restful apis, it would be great if we could have a good presentation, which can be read and understood easily. But the actual response has no formatting (indentation etc.) which makes it hard to read when we have lots of data.

It would be great if we could have a pretty print for json or simply use the "JSON_PRETTY_PRINT" in Json::encode().

Json::encode($response, JSON_PRETTY_PRINT);

Thanks

**Comment by nineinchnick** [comment]
This could be enabled when YII_DEBUG is set.

**Comment by Locustv2** [comment]
I am on my dev environment with YII_DEBUG on and it doesn't change anything.

**Comment by nineinchnick** [comment]
I said it _could_ do that, not that it does now.

**Comment by Locustv2** [comment]
Ohh. My bad, i thought you meant it already does. :)

**Comment by tunecino** [comment]
@Locustv2 there is great navigator's extensions that may help with large data like those 2 for chrome : 
https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en
https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh
I don't know much about the 2nd one, I've only tried the first and it already made my life easier.

**Comment by petrabarus** [comment]
I usually use `curl http://example.com | python -mjson.tool`

or extend the `yii\web\JsonResponseFormatter` to something like this

```php
    /**
     * Formats response data in JSON format.
     * @param Response $response
     */
    protected function formatJson($response)
    {
        $response->getHeaders()->set('Content-Type', 'application/json; charset=UTF-8');
        if ($response->data !== null) {
            $response->content = Json::encode($response->data, JSON_PRETTY_PRINT);
        }
    }

```
