### ISSUE TITLE
Collections in php and yii.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#9763]
I have been using yii for a long time now, since version 1, and one thing which i feel is missing is a Collection implementation to manipulate arrays easily. The yii\helpers\ArrayHelper is very useful and i use it a lot, but it still lacks some functionalities.

A Collection interface would would probably have basic functions like 
- add($element)
- contains($element)
- remove($element)

And subclasses would be:
- Set => can contain an element only once
- Queue => first in first out
- Stack => last in first out / first in last out
- Map => more like an associative array but easier to manipulate
- List => an array which is not indexed.

Some years back i did work on something like this which can be found at: https://github.com/Locustv2/ezyslib/tree/master/collections.

Maybe the codes can be improved and implemented to yii.

What do you think of adding a collection library to yii?

**Comment by klimov-paul** [comment]
You can use SPL `ArrayObject` class. There is no need for the general custom collection at PHP 5.4 with SPL.

**Comment by dynasource** [comment]
I think it is a good suggestion. It is supported by all the requests by users for customization of the ArrayHelper class. It would end all discussions and add value for Yii2 & improve code efficiency regarding arrays. Many other frameworks have support for it, ie. Doctrine http://www.doctrine-project.org/api/common/2.1/class-Doctrine.Common.Collections.ArrayCollection.html

**Comment by dynasource** [comment]
btw, its also adopted in the Laravel library https://laravel.com/docs/5.1/collections

**Comment by cebe** [comment]
PHP already provides all this stuff as far as I see: http://php.net/manual/en/spl.datastructures.php what else should be added by yii?
