### ISSUE TITLE
Add addFrom() method in yii\db\Query

### ISSUE THREAD

**Issue by galkindev** [yiisoft/yii2#9765]
Hello, what about to add addFrom() method in yii\db\Query class? Similar to the addSelect() method, this method will add more tables to the FROM part of the query.

**Comment by Renkas** [comment]
There is already a join() method and shorthands for: innerJoin(), leftJoin() and rightJoin() methods. It's not good to use comma JOINs - you should always use correct join clause.

**Comment by samdark** [comment]
Not going to add it for the reason @Renkas described.

**Comment by galkindev** [comment]
Yes, I will use innerJoin(), thanks for answers.
