### ISSUE TITLE
support for detect if the user is mobile or pc

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#9767]
i cant find in the framework a method for detect the type of device use the user 

i see this https://github.com/serbanghita/mobile-detect for example this have support for laravel but no for yii2

can add support for detect this in yii2 ?

**Comment by Renkas** [comment]
Did you even look at the link? There's a link to the Yii2 extension there: https://github.com/alexandernst/yii2-device-detect/

**Comment by spiritdead** [comment]
ohh i see this extension use the other github u.u

**Comment by samdark** [comment]
Not related to core framework.
