### ISSUE TITLE
Unable to debug view files

### ISSUE THREAD

**Issue by stratoss** [yiisoft/yii2#9768]
Hello,

I'm trying to debug a view file with X-Debug, but the breakpoints in it are skipped.

When the debugger reaches ```$this->render()``` in my controller it skips the view file and continues to ```yii2/base/Controller.php```, executing line 153 ```$result = $this->afterAction($action, $result);```

I'm using PHPStorm if that matters.

**Comment by samdark** [comment]
That could be XDebug issue or configuration issue. Anyway, it doesn't sound like we're able to fix it from framework side.
