### ISSUE TITLE
Cannot register_shutdown_function for max execution time

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#9769]
I have a controller action as follows:

    public function actionTest()
    {
        set_time_limit(1);
        register_shutdown_function(function()
        {
            var_dump('shutdown');
        });

        while(true){} //infinite loop
    }

And i still get the fatal error "Maximum execution time of 1 second exceeded"

If i don't sleep or make the execution time to exceed, the shutdown function is called.
According to http://php.net/manual/en/function.register-shutdown-function.php#33575 and several examples from the internet, the shutdown should be called even if the execution time is exceeded.

How should i handle the execution time error?

**Comment by samdark** [comment]
Not related to Yii.
