### ISSUE TITLE
RBAC migration DbManager exception

### ISSUE THREAD

**Issue by fedemotta** [yiisoft/yii2#9772]
Hi,
This is a follow up of a [yii2-admin issue](https://github.com/mdmsoft/yii2-admin/issues/205).

Why is there an exception raised if you don't have added the DbManager module in the console configuration? Why is not using the default db ($this->db) instead of the DbManager db? (See this [line of code](https://github.com/yiisoft/yii2/blob/master/framework/rbac/migrations/m140506_102106_rbac_init.php#L35)).

This generates this extra dependency (the DbManager module) in the console application of the yii2-advance-app.

Thank you

**Comment by samdark** [comment]
Because one could use different DB to store their RBAC data.
