### ISSUE TITLE
Pjax and Controller::goBack()/returnUrl issues

### ISSUE THREAD

**Issue by harman83in** [yiisoft/yii2#9776]
Hi guys,

This is the first issue I'm submitting, so pardon me if I'm not following all standards.
## Issue description:

Basically, what I have experienced is that all links within a Pjax block, which require user to login, do not get set in the Yii::$app->getUser()->getReturnUrl(). Hence for all such links the [Controller::goBack()](https://github.com/yiisoft/yii2/blob/master/framework/web/Controller.php#L184) fails and the user after login ends up on the homepage rather than the link clicked
## How to replicate/debug:

Use a GridView and put a PJAX block around it. Put a link to a page which requires user to login (say www.mydomain.com/user/create). 
1. Click on the link in the GridView, you'll be prompted to login, after which you'll go to homepage instead of www.mydomain.com/user/create
2. Logout. Then paste www.mydomain.com/user/create in the browser address bar directly  and after login you will goto www.mydomain.com/user/create as expected.
3. Logout. Comment the PJAX block. Reapeat step 1 and this time you will goto www.mydomain.com/user/create after login.

I also noticed in case 2 and 3 the Yii::$app->getUser()->getReturnUrl() was getting set correctly, but in case 1 it was being set to '/' instead
## Causes:

Could it be related to #2692 ?? Haven't dug deeper, but will update this section if I find anything
## Versions used

Issue replicated on Mac Yosemite using following browsers (Yii version - 2.0.7-dev):
Chrome Version 45.0.2454.93 (64-bit)
Firefox 40.0.3

**Comment by yashlohia** [comment]
I am also facing similar issue. My application has a List page from where user foes to teh Pjax enabled grid view. The grid view has link to another page. Once the user go to this another page and tries to go back to the grid view page, he/she ends up on the list page instead of the grid view page.

**Comment by dynasource** [comment]
see https://github.com/yiisoft/yii2/pull/13545#issuecomment-280837915
