### ISSUE TITLE
REST PUT (and DELETE) to replace (or delete) the entire collection

### ISSUE THREAD

**Issue by tunecino** [yiisoft/yii2#9777]
The `yii\rest\UrlRule` class is already supporting those RESTful API endpoints : 

``` 
'POST users' => 'user/create' : create a new user
'PUT,PATCH users/<id>' => 'user/update' : update a user
```

I think it would be useful to also add this endpoint (*see referenced links below*) : 
``` 
'PUT users' => 'user/replace' : Replace the entire collection with another collection.
```

This could be handled within `yii\rest\ReplaceAction` or equivalent to remove then save multiple data.
 
I think this action would be also useful if overridden within controller to handle *many_to_many* relational data by *linking* and/or *unlinking* them like when you change for example all *post*'s *tags* then you click a save button.

**references :**
https://en.wikipedia.org/wiki/Representational_state_transfer#Example
http://stackoverflow.com/questions/2001773/understanding-rest-verbs-error-codes-and-authentication#answer-2022938

**Comment by fernandezekiel** [comment]
what is the request going to look like?

**Comment by tunecino** [comment]
well if following common REST approaches, it would be like : 
``` 
PUT /tags

{
  "tags": [
  	{ "name": "php" },
  	{ "name": "jquery" },
  	{ "name": "java" },
  ]
}
```
to remove all tags and create the new submitted array. 

To handle relational data, it can be overriding in controller,  and can be used like : 

```
PUT /tags?post_id=3

{
  "tags": [
  	{ "name": "php", "id": "12" },
  	{ "name": "jquery", "id": "11" },
  	{ "name": "java", "id": "10" },
  ]
}
```
To *unlink* all old related tags to `post#3` and *link* it with the new list and maybe throw an exception if any of tags doesn't exist.

@fernandezekiel from our discussion at https://github.com/yiisoft/yii2/issues/9474, it would be `PUT post/3/tags` instead of `PUT /tags?post_id=3`

**Comment by tunecino** [comment]
I forgot to also mention deleting the entire collection :  
```
'DELETE tags' => 'tag/deleteAll' : delete the entire collection.
```
Which is also described in the same referenced links above.

**Comment by fernandezekiel** [comment]
oh i have been definitely following this whole feature set for quite and already implement a feature similar to the one you are talking about (Exactly tags actually)
i think however that @creocoder  is only talking about creating a Doc instead of implementing actual new features

i'm planning to create a small example application that covers this

**Comment by fernandezekiel** [comment]
i'm a bit confused on your example, i want to confirm if your example would look like this:
```
PUT /post/3/tags
{
  "tags": [
    { "name": "php", "id": "12" },
    { "name": "jquery", "id": "11" },
    { "name": "java", "id": "10" },
  ]
}
```

**Comment by tunecino** [comment]
What I'm suggesting here is the support of `'PUT tags'` and `DELETE tags` to respectively *replace* and *delete* an entire collection as those features are supported by many RESTful API designs and as described in the referenced links.

About relating models, I think it should be manually added by user and I meant that it would be easier to handle if that kind of feature is enabled by overriding its related action in the controller side and implementing relational code like using *active record*'s *link* and *unlink* methods when handling *many_to_many* relations.

Now about @creocoder Docs #9474 I was only suggesting a way to handle nested resources in the controller side if filtering is also enabled (https://github.com/yiisoft/yii2/issues/4479). I made a small app (which is not working yet until few more commits to redesign frontend) I'm using it to try different stuffs and figure out a good structure I'm going to use in a next project, so it is using those 3 models sharing *one_to_many* and *many_to_many* relationships : [owner](https://github.com/tunecino/Yii2_foundation-apps/blob/master/backend/models/Owner.php), [image](https://github.com/tunecino/Yii2_foundation-apps/blob/master/backend/models/Image.php) and [tag](https://github.com/tunecino/Yii2_foundation-apps/blob/master/backend/models/Tag.php). Relation between them are handled in their respective [Search Classes](https://github.com/tunecino/Yii2_foundation-apps/tree/master/backend/models/searches) and they have almost the same [controllers](https://github.com/tunecino/Yii2_foundation-apps/tree/master/backend/controllers). All nested combinations between them are now possible thanks to what @creocoder did suggest : see [rules.php](https://github.com/tunecino/Yii2_foundation-apps/blob/master/backend/config/rules.php) and a request like `GET /owners/3/images/1/tags/5?name=a` will throw a 404 error only if tag#5 and image#1 are not linked or if image#1 doesn't belong to owner#1 or if any of them doesn't exist. 

Now I need to implement an action to relate models and I think PUT a collection of tags to `/images/1/tags` is the most convenient RESTful way to do it. So am going to add it within yii\rest\UrlRule's **$extraPatterns** property and I'll share it when the repo is working to get feedbacks and suggestions with better approaches. We are meeting in the same REST discussions any way ;)

**Comment by tunecino** [comment]
I will close this as it doesn't seem to be widely used and those actions can be manually implemented while they may differ from a project to another. I also learned that most of people or even known api's have kind of an own design for REST. I think the Yii RESTfull Framework should be kept simple but as flexible as possible and any commun full specs to follow (like jsonapi.org) should be better implemented as an extension.
