### ISSUE TITLE
yii.js аякс префильтр по всей видимости не правлиьно определяет jsonp запросы

### ISSUE THREAD

**Issue by gromver** [yiisoft/yii2#9782]
При попытке подключить кладр апи (https://github.com/garakh/kladrapi-jsclient) наткнулся на конфилкт с yii.js, кладр апи успевает сделать только 1 запрос, все остальные закрываются префильтром
```
        $.ajaxPrefilter('script', function (options, originalOptions, xhr) {
            if (options.dataType == 'jsonp') {   // здесь, видимо происходит ошибка, т.к. jquery для jsonp запросов почемуто ставит dataType='json', но добавляет заполненные своиства jsonp, jsonpCallback
                return;
            }
            var url = options.url.charAt(0) === '/' ? hostInfo + options.url : options.url;
            if ($.inArray(url, loadedScripts) === -1) {
                loadedScripts.push(url);
            } else {
                var found = $.inArray(url, $.map(pub.reloadableScripts, function (script) {
                    return script.charAt(0) === '/' ? hostInfo + script : script;
                })) !== -1;
                if (!found) {
                    xhr.abort();
                }
            }
        });
```

Кладр, формирует запросы на сервер так:
```
		$.getJSON($.kladr.url + "?callback=?",
			toApiFormat(query),
			function (data) {
				if (timeout) {
					callback(data.result || []);
					clearTimeout(timeout);
				}
			}
		);
```

**Comment by zelenin** [comment]
не вижу ни слова про конфликт с yii.js. Только про проблемы с jquery ajax.

**Comment by gromver** [comment]
Не знаю, баг это или так и должно быть, но jsonp запросы не верно определяются, изза этого эти запросы блокируются в yii.js и соотвественно сервис кладра не работает.

Насчет jsonp jQuery говорит
If the URL includes the string "callback=?" (or similar, as defined by the server-side API), the request is treated as JSONP instead. See the discussion of the jsonp data type in $.ajax() for more details.

Запрос считается как jsonp но dataType = 'json'
Отсюда проблема.

**Comment by SilverFire** [comment]
Фильтр был переделан, скорее всего проблема уже решена.
Если вопрос всё еще актуален - просьба сообщитью
