### ISSUE TITLE
Update Javascript of MaskedInput

### ISSUE THREAD

**Issue by rafaelwithoeft** [yiisoft/yii2#9783]
Please, update javascripts envolved on maskedinput. He has some features that i need.

Images attached to show error ocurred (this not occurred on most recent version 3.2...).

![bug1](https://cloud.githubusercontent.com/assets/6033499/10134799/e7d17aa2-65be-11e5-9292-4594622c9dc2.png)

Example, test this code on already version:

    <?php echo $form->field($model, 'currency')->widget(\yii\widgets\MaskedInput::className(),
        [
            'clientOptions' => [
                    'alias' => 'currency',
                    'groupSeparator' => '.',
                    'placeholder' => '0,00',
                    'numericInput' => true,
                    'autoGroup' => true
            ],
        ]
    ); ?>

And now update to most recent javascript... that worked...

Current version on yii widget: Version: 3.1.63
Latest version: Version: 3.2.1-89

https://github.com/yiisoft/yii2/blob/master/framework/widgets/MaskedInput.php

Best Regards

**Comment by samdark** [comment]
https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/CHANGELOG.md#320---2015-09-04

**Comment by samdark** [comment]
Any idea if 3.2 is compatible with 3.1?

**Comment by samdark** [comment]
https://github.com/RobinHerbots/jquery.inputmask/issues/1069
