### ISSUE TITLE
Ignore some categories in message/extract

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#9784]
Sometimes I use translations from the yii category or from another extension in my own code. MessageController's actionExtract picks these up, and generates useless translation files that I have to delete every time. It would be great if I could specify a list of categories to ignore in the config file.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/views/messageConfig.php#L53

**Comment by nkovacs** [comment]
Thanks
