### ISSUE TITLE
DI injection via method signature

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#9785]
According this https://github.com/yiisoft/yii2/issues/9476#issuecomment-132924113, i suggest we add new method to `yii\di\Container`.
```php
public function invoke($callable, $params)
{
    $dependencies = $this->getCallableDependencies($callable);
    $dependencies = $this->resolveCallableDependencies($dependencies,$params);
    return call_user_func_array($callable,$dependencies);
}
```
## Usage
```php
// Component::trigger()
foreach ($this->_events[$name] as $handler) {
    $event->data = $handler[1];
    $container->invoke($handler[0], [$event]);
    ...
}

// config
'on beforeAction' => function($event, yii\db\Connection $db){
    // do something
}
```

**Comment by samdark** [comment]
Makes sense to me.

**Comment by softark** [comment]
I'm not sure if it's proper to point it here, but I couldn't get what "Controller action injection" means from the guide 
https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-di-container.md#controller-action-injection
Probably you need to elaborate it further.
