### ISSUE TITLE
Docs: Fix incorrect composer require for fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by jc21** [yiisoft/yii2#9788]
In the docs there are references to:

```
composer global require "fxp/composer-asset-plugin:~1.0.3"
```

but version 1.0.3 is no longer compatible with the latest composer package.

The docs should simply be:

```
composer global require "fxp/composer-asset-plugin:~1.0"
```

**Comment by samdark** [comment]
What do you mean by "no longer compatible with the latest composer package"?

**Comment by jc21** [comment]
The 1.0.3 plugin complains about a function, parseLinks I think from memory, that was deprecated in Composer recently.

**Comment by samdark** [comment]
Nope. 1.0.3 fixes it.
