### ISSUE TITLE
BaseFileHelper::createDirectory fails if path points to non-existing drive letter on windows

### ISSUE THREAD

**Issue by lukos** [yiisoft/yii2#9791]
If the directory trying to be created is on a non-existing drive letter (let's say D:), then I would expect a normal PHP/Yii error to say that the operation failed. 

What happens is that the recursion gets stuck at the D:\ level and the recursion limit is reached causing a white screen with error logged to the PHP error log.

This is because once the recursion has reached D:\, is_dir() returns false (because the drive letter does not exist) but calling dirname("D:\") returns "D:\" and it recurses and tries again.

I don't know how to recognise the root of the drive being reached in PHP or otherwise to check the drive letter right at the start of the function - since there are not always drive letters in the path (e.g. Linux/Unix). There are obvious workaround fixes possible like checking whether $parentDir == $path, which might work but don't want to suggest a messy fix if there is a neater one available.

**Comment by cebe** [comment]
I have checked in a fix, could you test if it works as expected, I have no windows system to try it on and linux does not have this problem. Thanks for reporting.

**Comment by lukos** [comment]
Thanks for the quick fix but my friend thinks this will also fail incorrectly if the parent directory and sub directory have the same name like: c:\var\www\mysite\mysite\
So the fix would work for me but would possible break other situations.

**Comment by cebe** [comment]
if `$path = 'c:\var\www\mysite\mysite'`, then `dirname($path)` will be `c:\var\www\mysite`, which are not equal so this should be fine.

**Comment by lukos** [comment]
That works and the error is: 

**Failed to create directory 'D:\': mkdir(): No such file or directory**

which isn't too bad (and probably quite a rare error). Thanks for that.
