### ISSUE TITLE
composer error when run composer update

### ISSUE THREAD

**Issue by ajkosh** [yiisoft/yii2#9794]
following error is coming when i run composer update
PHP Fatal error:  Call to undefined method Fxp\Composer\AssetPlugin\Package\Version\VersionParser::parseLinks() in /root/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php on line 272

Fatal error: Call to undefined method Fxp\Composer\AssetPlugin\Package\Version\VersionParser::parseLinks() in /root/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php on line 272

**Comment by lynicidn** [comment]
try `composer self-update` and use forum

**Comment by ajkosh** [comment]
not working still coming

**Comment by lynicidn** [comment]
composer global require "fxp/composer-asset-plugin:~1.0.3"
(c) https://github.com/yiisoft/yii2/blob/master/docs/guide/start-installation.md

**Comment by ajkosh** [comment]
thanku it works

**Comment by alirustamov** [comment]
Hi! I have the same error when trying <code>composer update</code>, <code>composer global update</code> and <code>composer global require "fxp/composer-asset-plugin:~1.0.3"</code>, composer is up to date. Can anyone help, please?

**Comment by umneeq** [comment]
For those who still same the problem (I have ubuntu):
just remove directory `/home/user/.composer/vendor/fxp`

**Comment by futureglorydev** [comment]
just remove directory /home/user/.composer/vendor/fxp
thank you, it works!

**Comment by index-panayotov** [comment]
@futureglorydev - THANKS!

**Comment by hacentech** [comment]
@umneeq  thanks. I have ubuntu and it works for me

**Comment by anthony-brindley** [comment]
Thank you - got me out of a tricky spot!

**Comment by resting** [comment]
Have the same error on my mac too. Ran `rm -rf ~/.composer/vendor/fxp` and its working again. But what is fxp anyway?

**Comment by wrewolf** [comment]
on windows:
remove from Users folder  \AppData\Roaming\Composer\vendor\fxp

**Comment by yesworld** [comment]
@umneeq Спасибо, работает! И так просто...

**Comment by yagmikita** [comment]
It works, thanks!

**Comment by kazip** [comment]
Странно, что не работало без этого.

**Comment by anvarulugov** [comment]
@umneeq thank you man! :+1:

**Comment by RiyadWu** [comment]
@futureglorydev Thank you. It works

**Comment by PiloTeZ** [comment]
@umneeq, thanks )

**Comment by gidedin** [comment]
On windows just remove the folder **fxp** from **%appdata%\Composer\vendor\**

**Comment by eothein** [comment]
Thanks, have been working on that issue for some time now...

**Comment by pborges2** [comment]
Thanks,  gidedin..

**Comment by hmphu** [comment]
@futureglorydev - THANKS!

**Comment by strihar** [comment]
Уже не первый раз ничего не помогает кроме совета /home/user/.composer/vendor/fxp, в моем случае путь был /root/.composer/vendor/fxp

**Comment by lynicidn** [comment]
в твоем случае не надо запускать композер от рута

**Comment by SiZEg** [comment]
@wrewolf thak you, it works.

**Comment by miradnan** [comment]
@futureglorydev Thanks! it works.

**Comment by jazzlevit** [comment]
yes, great. It also works for me.
