### ISSUE TITLE
 yii2/framework/grid/ActionColumn.php :: initDefaultButtons()

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#9796]
https://github.com/yiisoft/yii2/blob/95ba06c01b35b84740cd566edf4bdc0611db1efa/framework/grid/ActionColumn.php#L111
should not check `$this->template`, if `strpos` ? ... eager buttons %)

**Comment by samdark** [comment]
Could you please elaborate?

**Comment by lynicidn** [comment]
@samdark нет никакой проблемы, просто я думаю что строить такой массив заранее, не зная будут ли юзаться эти бутоны или нет. Сейчас проект правлю, а там религия не позволила оставить create view update delete, попереименовали зачемто в show edit и т.п. вот нашел это место, где все равно объявятся эти баттоны в параметрах для парсинга темплейта

**Comment by samdark** [comment]
OK. The proposal is to fill default `$this->buttons` values only when these are requested in https://github.com/yiisoft/yii2/blob/master/framework/grid/ActionColumn.php#L173 but do not exist.
