### ISSUE TITLE
No way to create a partial index for a migration

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#9799]
It's not apparent how to create a partial index (with a where clause) in a Yii migration.

https://devcenter.heroku.com/articles/postgresql-indexes#partial-indexes

http://www.yiiframework.com/doc-2.0/yii-db-migration.html#createIndex()-detail

You can set this to low priority. I just created it manually and I don't think it's widely used.

**Comment by samdark** [comment]
Not going to add that since:

1. It's PostgreSQL specific.
2. It could be achieved by executing SQL in migration.
