### ISSUE TITLE
Option to register asset with scheme

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#9803]
it's necessary create option to register asset with `scheme`.

Currently `AssetBundle` generate resources with relative path like: 
```html
<link href="/yii2-myapp/web/assets/ca59520f/toolbar.css" rel="stylesheet"></head>
```
in some cases it's necessary that will be generate:
```html
<link href="http://localhost/yii2-myapp/web/assets/ca59520f/toolbar.css" rel="stylesheet"></head>
```
i need this feature, when i was using [wkhtmltopdf](http://wkhtmltopdf.org/) to generate pdf from html

**Comment by samdark** [comment]
Yeah. Could be added as an option.

**Comment by nikashitsa** [comment]
@samdark @leandrogehlen I've implemented it. Please have a look at Pull Request #10031.

**Comment by klimov-paul** [comment]
The most obvious way to achieve the described effect will be usage of an special alias at `AssetBundle::baseUrl` like `@absoluteweb`, which will be resolved as absolute URL with schema part.
Other option will be override existing `@web` alias with another value.
If you may also change `AssetManager::baseUrl` to the absolute URL to have same effect for the published assets.
