### ISSUE TITLE
Query: Allow to select NULL

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#9804]
A small improvment: If I'd like to create a query like `SELECT NULL AS a, b, c FROM table` I have to do something like this:

    $query->select(['a' => '(NULL)', 'b', 'c'])->from('table')
    // or
    $query->select(['(NULL) AS a', 'b', 'c'])->from('table')

It would be nice if I don't need the workaround with the brackets. `'a' => null` would be also nice.

Why do I need this? I just have created a union query in which not all fields have values. Took some time to find out that I need the brackets.

If you don't want to implement this you could update documentation.

**Comment by klimov-paul** [comment]
Rejected: `NULL` is a regular SQL expression just like any other, `DATE()` for example.
You should use `yii\db\Expression` if you need any SQL epxression at the select statement:

```php
$query->select([
    new \yii\db\Expression('(NULL) AS a'),
    'b',
    'c'])
->from('table')
```
