### ISSUE TITLE
Yii2 - Render actionView inside index.php of a view

### ISSUE THREAD

**Issue by phuongktax** [yiisoft/yii2#9806]
In my index.php, I want to display some information of view.php, so I use

```php
$this->render('view',array('id'=>$model['id']) ); 
```

where  $model['id'] comes from the loop.

In my actionView :  

```php
public function actionView($id)
    {
        $project = Users::findOne($id);
        $list = $project->getProjects()->asArray()->all();
        $list2 = $project->getGroups()->asArray()->all();

        return $this->render('view', [
            'model' => $this->findModel($id)->toArray(),
            'projects' => $list,
            'groups' => $list2          
        ]);
    }
```

needs parameter $id, however the result in my index view is "Undefined variable: groups"
I think that I have to pass the  $model['id']  into   actionView($id), how to do it? Many thanks...

**Comment by samdark** [comment]
Please [use forums for questions](http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/). Thanks.

**Comment by tieppt07** [comment]
sao nhạc nào cũng nhảy thế e :+1: 
cả asp vs php
