### ISSUE TITLE
Html Files doesn't reload when using ng-include in angularjs

### ISSUE THREAD

**Issue by moylua** [yiisoft/yii2#9807]
Hello, we are using yii2 together with angularjs. We encountered a problem when using ng-include in angularjs to include partial html templates. We are also using stateProvider of angular and binding it to ui-view. The request goes first to yii and then renders the html using ui-view. Is this a problem in assets manager or does yii caches the html files?

**Comment by moylua** [comment]
update: when i open that static html page using chrome developer tools it reloads

**Comment by samdark** [comment]
Then it looks like a problem with Angular and we can't fix it from Yii side.
