### ISSUE TITLE
REST routes formats are inconsistent

### ISSUE THREAD

**Issue by EvgenyOrekhov** [yiisoft/yii2#9812]
Some components ignore the leading slash in routes, some don't.
This works:

``` php
'urlManager' => [
    'enablePrettyUrl'     => true,
    'enableStrictParsing' => true,
    'showScriptName'      => false,
    'rules'               => [
        '/rest/v1/tasks'  => '/rest/v1/task/index', // note the leading slash in the value
```

This doesn't work because of the leading slash:

``` php
'as authenticator' => [
    'class'  => 'yii\filters\auth\HttpBasicAuth',
    'except' => [
        '/rest/v1/task/options', // note the leading slash
```

**Comment by cebe** [comment]
where did you put the second code for authenticator?

Note that `except` property of ActionFilter contains action ID only when applied to a controller. e.g. `options` instead of `/rest/v1/task/options`

**Comment by EvgenyOrekhov** [comment]
@cebe 'as authenticator' is in the main.php config of my app, 'rest' and 'v1' are modules
```
api -- application root
    config
        main.php -- 'as authenticator' is here in my config array
    modules
        rest
            modules
                v1
                    controllers
                        TaskController.php -- here is my 'options' action
```
I want to bypass the authenticator when accessing the 'options' action.
Am I doing it right?

**Comment by EvgenyOrekhov** [comment]
I am no longer interested in this. Feel free to reopen if needed.
