### ISSUE TITLE
matchCallback does not work with other rules

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2#9813]
I have been playing with this for a bit, and it doesn't make sense. Maybe it is "coded" this way on purpose, but if it is, then it isn't documented. So if `matchCallback` is not supposed to contain other rules, then the docs should make that clear! However, scouring the code, it looks like it is supposed to match ALL of the rules.

Here is what I found in the code:

    public function allows($action, $user, $request)
    {
        if ($this->matchAction($action)
            && $this->matchRole($user)
            && $this->matchIP($request->getUserIP())
            && $this->matchVerb($request->getMethod())
            && $this->matchController($action->controller)
            && $this->matchCustom($action)
        ) {
            return $this->allow ? true : false;
        } else {
            return null;
        }
    }

This seems to indicate all the rules are required, including `matchCustom`.

So if you have a rule like so:

    [
        'actions' => ['create'],
        'allow' => true,
        'roles' => ['@'],
        'matchCallback' => function ($rule, $action) {
            return AdminRole::canCreateUserAccounts();    // return boolean
        }
    ],

They should be logged in (`@`) AND `matchCallback` should return true. I also tried by removing the `allow` line, still lets them pass right on through.

It seems if `matchCallback` is false, it lets me in. If it is true, it blocks me... This seems backwards..
So since it seemed backwards, I experimented with the `allow` rule.. setting it `allow` to true, then toggled the user->id check between 1 (me) and 2 for another user.. It had no effect at all, like `allow`=>true overrides it no matter what. Setting `allow` to false, does the same action as if it was commented out.

    public function behaviors()
    {
        return [
            'access' => [
                'rules' => [
                    [
                        'actions' => ['index'],
                        //'allow' => true,
                        //'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if ( Yii::$app->user->id === 1 ) {
                                return true;
                            }
                            return false;
                        },
                    ],
                ],
            ],
        ];
    }

It just seems like I can't make it happy. What I am trying to do is actually run a function inside the match callback. For example:  AdminRole::canCreateAccounts() which does a check if the admin is ROOT level  (only root admins can create accounts). It grabs the current users role from db column, and returns true if they can, false if not. When using that function, it throws an error if the user is not logged in. Well, I had `roles` set to `@` during my testing, so that should have failed and sent them to the login page, before my action tried to access user data..

Am I missing something? or is the matchCallback clunky?

**Comment by WadeShuler** [comment]
I think I have a bit more info on this. Again, I don't know the mind of who created this, but it seems like (from an end-user standpoint) the logic is a bit off.

If you use `matchCallback` on your rule, you would expect that if it returns true, it should allow you (given other rules match), or deny you if it returns false.. ie: matchCallback should be a boolean, true or false.. Actually, the docs tell you it is `true` or `false`.. weird that it actually returns null! matchCallback **should** return what **we tell it to**. It is a callback function, we code how we want it to act within the criteria (ie: true or false). It should respect that I told it to return false.

It seems that if our `matchCallback` returns false, it actually returns null.

This question and answer on SO seem to illustrate it: [http://stackoverflow.com/questions/31251346/setting-custom-denycallback-even-when-returning-false-from-matchcallback-with-yi](http://stackoverflow.com/questions/31251346/setting-custom-denycallback-even-when-returning-false-from-matchcallback-with-yi)

I extended `AccessRule` to fix this: `MyCustomRule.php` in `backend\models\rbac`

    namespace backend\models\rbac;
    use yii\filters\AccessRule;

    class MyCustomRule extends AccessRule
    {
        public function allows($action, $user, $request)
        {
            $allows = parent::allows($action, $user, $request);
            if ($allows === null) {
                return false;
            } else {
                return $allows;
            }

        }
    }

*Note: Credit to [@Tony](http://stackoverflow.com/users/2232850/tony) from StackOverflow*

Then referenced it in my Controller:

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'class' => \backend\models\rbac\MyCustomRule::className(),
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            if ( Yii::$app->user->id === 1 ) {
                                return true;   // let them in
                            }
                            return false;   // get lost
                        },
                    ],
                ],
            ],
        ];
    }

It now works exactly as I expected it to. So it seems the problem is that `matchCallback` actually returns null if your code returns false...

It seems to work properly with the roles `@` declaration as well! If I put my original function back in, `AdminRole::canCreateAdminAccounts()` while using the `@` role, it does not throw an error! Before, the `canCreateAdminAccounts` function threw an error because it relies on data of the logged in user, which doesn't exist if they aren't logged in.

Furthermore, I don't see documentation telling me I can use `class` in my rules array? I simply tried it, and it worked (since answer on SO didn't specify). I expected to see `class` as an option here: [http://www.yiiframework.com/doc-2.0/yii-filters-accessrule.html](http://www.yiiframework.com/doc-2.0/yii-filters-accessrule.html)

## Proposal
Change the `matchCallback` logic to make it actually return false, instead of overriding it to return null. Obviously, unless there is a good reason why it is the way it is :+1: I just don't like having to create a custom class to hijack it, to make it perform the way I think it should. Judging by other questions I have seen related to this, `matchCallback` is confusing to most people, or at least those who first try to use it. My assumption is because it doesn't work the way we think it should.

**Comment by WadeShuler** [comment]
Thanks @samdark for taking notice.

I seemed to have other quirks while using `matchCallback`. I admin, I am not a pro with the rules though, even without `matchCallback`, they take a bit of trial and error for me.

I am trying to roll out my own mini RBAC. Maybe I should create a behavior or something? The RBAC in the docs (Php or Db version) don't really do what I want. I don't want to assign every single user a role. If I had 1 million users, I don't want a million role entries. I simply need hard coded checks. I have a "role" column in the database table that is an integer, mapped to a constant in the Model. ROLE_ROOT = 100, ROLE_SUPER = 50, ROLE_ADMIN = 10. I simply need functions to check if they can do something, based on that value. ie: `canAdminCreateAccounts()` checks whether they are ROLE_ROOT or not. -- Maybe this is already possible using the built in RBAC? Just a Rule model that performs these functions?

On topic though, I seemed to still have quirks. With what I had above for the rules, it performed like an 'only' operation, though I didn't specify `only`...  It was denying me `index` and `view` actions.. like it hijacked them.

For example, this didn't work:

    'access' => [
        'class' => AccessControl::className(),
        'only' => ['create', 'update', 'delete'],
        'rules' => [
            [
                // only allowed admins can perform these actions
                'actions' => ['create', 'update', 'delete'],
                'class' => MyCustomRule::className(),
                'allow' => true,
                'roles' => ['@'],
                'matchCallback' => function ($rule, $action) {
                    return AdminRole::canManageAdminAccounts();
                },
            ],
            [
                // everything else for logged in users only
                'allow' => true,
                'roles' => ['@'],
            ],
        ],
    ],

I even tried putting the 2nd rule above my custom one, thinking they took order.. still couldn't access `index` or `view`. I added a `denyCallback` under my `matchCallback` and had it throw an error and include the `$action->index` to see what action is saw.. When I tried to view `index` it spit out the `denyCallback` that was in the `['create', 'update', 'delete']` rule. Telling my I didn't have permission, and said `index`. So it saw it was the index action, but `matchCallback` and `denyCallback` were still handling it... weird..

So I then tried this.. which I don't think I have seen anywhere, but it seems (so far) to be working.. I made another `rules` array for the rest.. well, actually to restrict everything else to logged in users only.. like so:

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        // only allowed admins can perform these actions
                        'actions' => ['create', 'update', 'delete'],
                        'class' => MyCustomRule::className(),
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return AdminRole::canManageAdminAccounts();
                        },
                    ],
                ],

            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

So far it seems to be working, but I thought that last time, and ran into snags.. Sorry for the long messages, I have spent hours on this. Maybe I should have just went down the custom behavior route?

**Comment by mikehaertl** [comment]
I think your misunderstanding is, that you can use `matchCallback` to define wether the rule is `allow` or `deny`. But that's not the case. As the name implies, it only defines, whether the current rule *matches*. So if you have a rule with `'allow' => true` it will always be an *allow* rule. `matchCallback` only checks, whether this ruly should be applied or not.

**Comment by mikehaertl** [comment]
I'm also very much against your proposed change. The docs are pretty clear about what `matchCallback` does:

> @var callable a callback that will be called to determine if the rule should be applied.

It no were says "to determine, if the current action is allowed". It only checks, if the rule is going to be applied, that's all.

Coming back to your initial example:

```
[
    'actions' => ['create'],
    'allow' => true,
    'roles' => ['@'],
    'matchCallback' => function ($rule, $action) {
        return AdminRole::canCreateUserAccounts();    // return boolean
    }
],
```

So this rule is of type `allow` - nothing else. And it will be applied if all its criterias match:

 * Action is `create`
 * User is logged in
 * `AdminRole::canCreateUserAccounts()` returns `true`

In this case, access is allowed. In all other cases, the rule is skipped and (if that's your only rule) access will be denied.

**Comment by WadeShuler** [comment]
My problem is, if `AdminRole::canCreateUserAccounts()` returns false, it still allows them to access the `create` page. Default for my admin accounts is `int 10`. Super is `50` and Root is `100`. In this example, `create`, only Root and Super are allowed to create accounts. Regular admins can not. So if a regular admin with a role of `10` tries to access the `create` page, he should be denied.

I can easily perform these checks in the Controller for each action, but I try to learn something new every time.

You could still have `matchCallback` return null in your function, and it will skip the rule. My proposal would also allow you to return `false` to easily escape the match.

I am going down other routes right now. Expanding AccessRule, and seeing if I get better results. What I had, still had issues. ie: guests being able to access the page because the other rule to block them wasn't being respected. So it's like I appease one, and break another. I just want a simple RBAC based off the user's role value in the db.

**Comment by klimov-paul** [comment]
Most probably you should use `AccessRule::denyCallback` for your use case.

**Comment by mikehaertl** [comment]
@WadeShuler Sorry, I still don't get what you try to say. `matchCallback` does exactly what it should. I also can not confirm your issues. Everything works exactly as expected. Here's a quick test:

```
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['@'],
                        'matchCallback' => function($r, $a) {
                            return false;
                        },
                    ],
                ],
            ],
        ];
    }
```

If I return `true` in the callback, the rule matches for logged in users and access is granted. If I do return `false` the rule does not match so the default rule of `deny` is used. It's probably your `AdminRole::canCreateAction()` that is faulty or something.

**Comment by mikehaertl** [comment]
@klimov-paul `denyCallback` would only be called in the deny case. That's something entirely different than OP's problem. Again this callback can't be used to determine, if the rule should allow or deny access.

**Comment by klimov-paul** [comment]
Yes I have noticed this alreay.
We may consider to enhance `allow` to be a callable - not just a boolean. This may solve the use case.

**Comment by klimov-paul** [comment]
However the most simple solution is having a entire deny rule at the end of the list:
```php
'access' => [
    // ...    
    'rules' => [
        [
                // only allowed admins can perform these actions
                'actions' => ['create', 'update', 'delete'],
                'allow' => true,
                'roles' => ['@'],
                'matchCallback' => function ($rule, $action) {
                    return AdminRole::canManageAdminAccounts();
                },
        ],
        [
            // Deny from all:
            'actions' => '*',
            'allow' => false,
            'roles' => '*',
        ],
    ],
],
```

**Comment by mikehaertl** [comment]
@klimov-paul You don't need that deny rule. Deny is the default anyway. So there's not issue at all here: Just create an `allow` rule, and use `matchCallback` to decide, whether the rule should apply or not. Problem solved.

**Comment by mikehaertl** [comment]
I do agree, though, that using a callback for `allow` would be a nice feature. Still it's not required for the OP's problem. It would rather be a convenience feature.

**Comment by samdark** [comment]
Since there's no issue with docs or anything. This one is closed. If you think the enhancement could be made, please create new issue.

**Comment by WadeShuler** [comment]
@mikehaertl It would be a handy feature.

I don't really like having to declare every single action throughout the entire system. So using:

    [
           'allow' => true,
           'roles' => ['@'],
    ],

is great for that. However, it overrides the other rules.

    [
        'allow' => true,
        'roles' => ['@'],
    ],
    [
        'actions' => ['create', 'update', 'delete'],
        'allow' => true,
        'roles' => ['@'],
        'matchCallback' => function ($rule, $action) {
            return false;
        },
    ],

The only way to get around it (without going down a rabbit hole of RBAC or extending things), is to explicitly declare each and every action.

    [
        'actions' => ['index', 'view'],   // etc. etc. etc...
        'allow' => true,
        'roles' => ['@'],
    ],
    [
        'actions' => ['create', 'update', 'delete'],
        'allow' => true,
        'roles' => ['@'],
        'matchCallback' => function ($rule, $action) {
            return false;
        },
    ],

A way to overcome this would be awesome. A way to tell it if `matchCallback` returns true, to allow it no matter what. And false, deny it no matter what. I understand, if it returns null, to keep checking. It is just annoying that the 1st global "authorized users" rule overrides it completely.

**Comment by mikehaertl** [comment]
Please: All this has nothing to do with `matchCallback`. This callback is used for something else and is fine the way it is.

I don't know, what you mean by "declare every single action". If a rule applies to all actions, leave the `actions` parameter away. If it doesn't then how else would you solve it than to list all those actions explicitely. A callback doesn't help you any further here.

**Comment by footniko** [comment]
It works like expected when you set actions explicitly, like following:  
```
...
'access' => [
    'class' => AccessControl::class,
    'rules' => [
        [
            'actions' => ['action1', 'action3', 'action4'], // need to set all actions here
            'allow' => true,
            'roles' => ['@'],
        ],
        [
            'actions' => ['action2'],
            'allow' => true,
            'roles' => ['@'],
            'matchCallback' => function($rule, $action) {
                /* @var $user User */
                $user = Yii::$app->user->identity;
                return $user->isMandatoryInfoFilled();
            }
        ],
    ],
],
...
```
But it will not work if you want to set some behaviour for all actions and some more specific for one action:  
```
...
'access' => [
    'class' => AccessControl::class,
    'rules' => [
        [
            'allow' => true,
            'roles' => ['@'],
        ],
        [
            'actions' => ['action2'],
            'allow' => true,
            'roles' => ['@'],
            'matchCallback' => function($rule, $action) {
                /* @var $user User */
                $user = Yii::$app->user->identity;
                return $user->isMandatoryInfoFilled();
            }
        ],
    ],
],
...
```
So that's the issue, because we have to set all of the actions explicitly which is annoying.

**Comment by Lisio** [comment]
I'm agree with @klimov-paul that matchCallback works fine for it's purpose but I also agree with @footniko that entire behavior is not very obvious and there is also no way to deny access to a single action without explicitly listing all other actions in allow rules.

There are two ways to solve this. First one is to make the `allow` a callable as @klimov-paul mentioned previously and if it returns false - deny access to that action(s).
The second one is to add new param `deny` similar to `allow` which will deny access to action(s) if the rule is applied and will ignore other rules.
