### ISSUE TITLE
Html::a() - encode bad behaviour

### ISSUE THREAD

**Issue by Heddy147** [yiisoft/yii2#9816]
Hi,

if I use the function a() of Html, there is a bad behaviour.
Accepted I use it so:
Html::a('Foobar', ['foo', 'bar' => 'rofl', 'lol' => 'wtf'])

The assumed value for the href-attribute of the anchor-tag is "mydomain.com/foo?bar=rolf&lol=wtf".
I get  "mydomain.com/foo?bar=rolf&amp;lol=wtf".

The same issue if I use pagination.

Hope I have a mistake.

**Comment by samdark** [comment]
What do you mean? Both assumed and actual URLs are the same? What's wrong with that?

**Comment by Heddy147** [comment]
Sorry, GitHub recognize & a m p ; and convert it to &.
So i get "mydomain.com/foo?bar=rolf&*m*p*;lol=wtf" (without *)

**Comment by samdark** [comment]
Do you get it in URL after clicking it or in HTML? In HTML that's correct encoding of attribute.

**Comment by Heddy147** [comment]
Yeah,
in HTML it's correct.

I get it in URL after clicking.

**Comment by samdark** [comment]
Can't reproduce.

- Take basic project template.
- In config set up urlManager to use clean URLs:

```php
'urlManager' => [
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'rules' => [
    ],
],
```

- In `views/site/index.php` add `<?= Html::a('Foobar', ['site/index', 'bar' => 'rofl', 'lol' => 'wtf']) ?>`.
- Click the link at the front page.

It opens `http://yii2-basic.local/site/index?bar=rofl&lol=wtf` as expected.

**Comment by SilverFire** [comment]
I have reproduced. Browser opens correct URL, but the HTML contains `&amp;` instead of `&`

`<a href="http://yii2-basic.local/site/index?bar=rofl&amp;lol=wtf">Foobar</a>`

@samdark, try to open `view-source:http://yii2-basic.local/site/index.php` and find your link

**Comment by samdark** [comment]
Yes but this is exactly what's expected. `&` is HTML entity within attribute and should be encoded.

**Comment by SilverFire** [comment]
@samdark hm, you're right. Sorry, that was my bad.

@Heddy147 what browser did you used, when got Yii error "one parameter is missing: lol"?

**Comment by Heddy147** [comment]
@SilverFire 
I used Firefox Version 40.
What did I wrong? I get this error too if I use the GridView widget with the pagination.

**Comment by SilverFire** [comment]
Could you, please, provide full code for that column in GridView?

**Comment by samdark** [comment]
@Heddy147 tried with Firefox 40.0.3. Works.

**Comment by SilverFire** [comment]
@Heddy147 maybe you have accidentally encoded HTML twice?

**Comment by Heddy147** [comment]
I used GridView::widget(...) with few parameters, no double encoding, no other function.

Firefox 41 does the same

**Comment by samdark** [comment]
Please provide code to reproduce it.

**Comment by Heddy147** [comment]
**Controller->actionIndex()**
```php
$searchModel = new ModelSearch();
$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

return $this->render('index', [
    'searchModel' => $searchModel,
    'dataProvider' => $dataProvider
]);
```

**View**
```php
<?= GridView::widget([
	'dataProvider' => $dataProvider,
	'columns' => [
		'attr6',
		'attr7',
		'attr8',
		[
			'class' => \yii\grid\DataColumn::className(),
			'label' => 'Attributes One',
			'content' => function($model, $key, $index, $column) {
				return $model->attr1 . "<br/>" . $model->attr2 . " " . $model->attr3;
			}
		],
		[
			'class' => \yii\grid\DataColumn::className(),
			'label' => 'Attributes Two',
			'content' => function($model, $key, $index, $column) {
				$string = [];
				if(strlen($model->attr4) > 0) {
					$string[] = "<i class='fa fa-home'></i> <a href='tel:" . $model->attr4 . "'>" . $model->attr4 . "</a>";
				}
				if(strlen($model->attr5) > 0) {
					$string[] = "<i class='fa fa-phone-square'></i> <a href='tel:" . $model->attr5 . "'>" . $model->attr5 . "</a>";
				}
				return implode('<br/>', $string);
			}
		],
		[
			'class' => 'yii\grid\ActionColumn',
			'buttons' => [
				'update' => function($url, $model, $key) {
					return Html::a('<i class="fa fa-pencil"></i>', $url, ['class' => 'btn btn-warning btn-sm']);
				},
				'delete' => function($url, $model, $key) {
					if(Yii::$app->user->can('permission:model:delete')) {
						return Html::a('<i class="fa fa-remove"></i>', $url, [
							'class' => 'btn btn-danger btn-sm',
							'data' => [
								'confirm' => 'Are you sure you want to delete this item?',
								'method' => 'post',
							]
						]);
					}
					
					return null;
				},
				'view' => function($url, $model, $key) {
					return Html::a('<i class="fa fa-eye"></i>', $url, ['class' => 'btn btn-success btn-sm']);
				}
			]
		],
	],
	'options' => [
		'class' => 'grid-view table-responsive'
	]
]); ?>
```

**Comment by samdark** [comment]
@Heddy147 which link fails?

**Comment by Heddy147** [comment]
In GridView all links of pagination.

**Comment by samdark** [comment]
Wait, there's nothing in the code above affecting pagination. Are you sure?

**Comment by Heddy147** [comment]
The GridView generates the page selection at the bottom of the GridView table.

**Comment by samdark** [comment]
Yes. But you're not customizing it at all so the thing is that pretty standard links are generated in the wrong way for you. Correct?

**Comment by Heddy147** [comment]
Correct, no customizing

**Comment by samdark** [comment]
OK. Which webserver you're using? If it's Apache, do you have mod_rewrite configured properly (either with .htaccess or in the config)?

**Comment by Heddy147** [comment]
Apache 2.0
mod_rewrite is loaded and .htaccess is parsed without errors

**Comment by samdark** [comment]
What's its contents?

**Comment by samdark** [comment]
Also, if you do https://github.com/yiisoft/yii2/issues/9816#issuecomment-145278511, does it have the same issue?

**Comment by Heddy147** [comment]
.htaccess
```
RewriteEngine on

# Verwende Verzeichnis oder Datei, wenn sie vorhanden sind
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# Leite andernfalls auf index.php um
RewriteRule ^.*$ index.php [NC,L]
```

pretty-url is enabled
scriptname isn't shown

**Comment by samdark** [comment]
Could you change rule to `RewriteRule . index.php` and check?

**Comment by Heddy147** [comment]
Change rule to `RewrtieRule . index.php`
No effect

**Comment by samdark** [comment]
OK. Then try with clean basic app as here https://github.com/yiisoft/yii2/issues/9816#issuecomment-145278511

**Comment by SilverFire** [comment]
@Heddy147 contact me in https://gitter.im/silverfire

**Comment by SilverFire** [comment]
In PM with @Heddy147 decided to dig deeper when he will have some free time

**Comment by Heddy147** [comment]
After looking for the issue with SilferFire he has found the issue:

The problem was in config option [arg-separator.output](http://php.net/manual/ru/ini.core.php#ini.arg-separator.output) that was set for some reasons to non-default value `&amp;` by server admin.

If you didn't set it to default value Yii will encode the URL double.

While testing we set it with php_ini:
`ini_set('arg_separator.output', '&');`

It will help.
