### ISSUE TITLE
It's time to add the extension foundation for yii 2.1?

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2#9825]
One reason to use Bootstrap, since Foundation dropped support of IEs except the very latest too soon, And `NOW` when yii2-bootstrap for yii 2.1 will switch to the bootstrap 4 (`alpha`), it's same will remove IE8 support as well.

So whether it can add yii2-bootstrap and yii2-foundation(same with bootstrap 4 foundation will updated to version 6 soon) also for yii 2.1 ?

**Comment by dynasource** [comment]
thanks for your remark
