### ISSUE TITLE
problem with date language

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#9829]
good day i have this problem
i have defined the "language,timeZone" in the common/config/main.php
work great, affect translations BUT when i use this for example 
date('jS M Y - h:i a',$message->created_at)

this return all time in english

im reading this
http://stackoverflow.com/questions/22635303/get-day-from-string-in-spanish-php
and is defining the setLocale, why if i define "language" in the app this is not affected

**Comment by samdark** [comment]
Because it is different. Yii uses intl locale which is set via `language`. `date()` uses PHP locale which is set via `setLocale`.

**Comment by spiritdead** [comment]
@samdark  in the config not exist this ?, for no add in all views the setlocale ?

**Comment by samdark** [comment]
It can be done once in `index.php`, for example/

**Comment by spiritdead** [comment]
@samdark i added in the index (frontend/web/index.php) 

<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../../vendor/autoload.php');
require(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/../../common/config/bootstrap.php');
require(__DIR__ . '/../config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../../common/config/main.php'),
    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
setlocale(LC_ALL,$config['language']);
$application = new yii\web\Application($config);
$application->run();

but not work, all time in english...

**Comment by samdark** [comment]
Well, try https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L457.

**Comment by spiritdead** [comment]
@samdark hehe i tried with this format (jS M Y - h:i a) but only get numbers i cant get for example "Noviembre/november in spanish" :S

**Comment by spiritdead** [comment]
@samdark can open this plz, because if i use yii2 in spanish and i cant translate the dates is a problem...

**Comment by samdark** [comment]
@spiritdead you're trying to use `date()`'s format for a method that accepts ICU format.
