### ISSUE TITLE
Suggestion: JSON in DB comments to ehncance gii model generation

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#9830]
I use Gii way too much. I have converted it into a console based model generator that will always ensure all the DB related rules are up to date and in place in a BaseModel. However heavily using behaviors makes the default rules and code generated by Gii a bit of a drawback. For this I put in my db columns comments in Json format indicating specific things (i.e. {validation: false, label: 'XYz'}), etc.
To allow me to maintain proper MySQL comments (if and when needed), I test if json is valid and only then use it, otherwise gii goes around it's usual business.

So, my recommendation is to kinda formalise JSON format support in DB comments in core level to enhance the automated Gii generators.

What do you think?

**Comment by samdark** [comment]
Sounds a bit too specific and complicated but I could be wrong...

**Comment by ptheofan** [comment]
If the db comments feels wrong we could as easily also just use some php array in the configuration.

The idea is that Gii (which I find really great) should be a full CLI tool that can automate a nearly everything related to database models. However, when mass automating things sometimes you need exceptions.

examples

1. I have a SET which I don't want to be validated as string. As such I can use my configuration to exclude that rule from that table.column
2. For a specific column I want the label to be XYZ instead of Xyz. And I don't want to override the labels function just for that. I can simply there tell Gii to set the label to XYZ thus eliminating overhead.
3. (I can mention more if needed).

The idea behind base models (at least in my context) is

1. I always want to have clean separation between the DB login (so I don't have MySQL exception) and the business logic.
2. As such I put all the DB related stuff in a Base file (i.e. BaseOrders.php) and my business logic in the Orders.php.

**Comment by SilverFire** [comment]
I agree with @samdark, that is it very specific to add to the core.
But is a good idea for advanced users. Yii2 gives you ability to create an extension, so you can do it and use Gii with new specific power :)
