### ISSUE TITLE
[Bug] publishOptions not working

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#9835]
In this example : 

```php
<?php
namespace app\assets;

use yii\web\AssetBundle;

class FontAwesomeAsset extends AssetBundle 
{
    public $sourcePath = '@bower/font-awesome'; 
    public $css = [ 
        'css/font-awesome.min.css', 
    ];
    public $publishOptions = [
        'only' => [
            'fonts/',
            'css/',
        ]
    ];
} 
```

Assets not publish files : 

![screenshot_2](https://cloud.githubusercontent.com/assets/6630197/10272919/d8f00080-6b27-11e5-904a-29b6de2661d9.png)

**Comment by martingeorg** [comment]
This is related to #9669 and #8785 and few other issues about publishOptions

I am also experiencing this issue.

There was a comment in one of the issues created, about using

<code>
$publishOptions = [
    'forceCopy'=>true
];
</code>

It seems to work as a fix for the moment.
http://www.yiiframework.com/doc-2.0/yii-web-assetbundle.html#$publishOptions-detail
http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#$forceCopy-detail

**Comment by pana1990** [comment]
of course, i close this issue, it is duplicated.

@martingeorg thanks for the links :)
