### ISSUE TITLE
New DBConnection, function does not exist

### ISSUE THREAD

**Issue by ebtc** [yiisoft/yii2#9841]
Hi there,

Either your docs are not up to date, or I am missing something obvious. In a model, extending from \yii\db\ActiveRecord I try to set a new DB Connection by doing the following:

```php
public static function getDB()
    {
        return \yii\db\Connection([
            'dsn' => Yii::$app->session->get('client_connection.dns'),
            'username' => Yii::$app->session->get('client_connection.username'),
            'password' => Yii::$app->session->get('client_connection.password'),
        ]);
    }
```

On calling $stats = $daily::find()->select('*')->asArray()->all(); I get a nasty "Call to undefined function yii\db\Connection()". How is that? According to [this link](http://www.yiiframework.com/doc-2.0/yii-db-connection.html), it should have no issue.

I noticed that the Connection class does not have a constructor defined. Should it inherit that from Object? How would the class then know what to do with the array passed into it?

Thanks for your help.

**Comment by jeicd** [comment]
You are missing "new" operator when you create  \yii\db\Connection class.

**Comment by klimov-paul** [comment]
You have missed `new` operator.

**Comment by ebtc** [comment]
where is the face-palm emo for Github?? Thanks. I will burry myself now....
