### ISSUE TITLE
FR: Add html minify (helpers or widget)

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#9843]

**Comment by klimov-paul** [comment]
What do you mean?

**Comment by samdark** [comment]
If you mean removing spaces and line breaks between HTML tags, we won't add it because it doesn't make any sense considering content is gzipped.

**Comment by mdmunir** [comment]
@klimov-paul 
Like `Spaceless` widget but more powerfull.
@samdark 
Why not make sense? Sorry, what do you mean "content is gzipped".
I just want to minify some of element. not entire page. What your recomendation?
```php
$content = json_encode(minify($this->render('my_content')));
$js = <<<JS
var content = {$content};
function addContent()
{
    jQuery('#mydiv').append(content);
}
JS;

```

**Comment by samdark** [comment]
My recommendation is not to do it. If you'll enable gzip (output compression) in nginx or Apache there would be basically no difference. You'll maybe save a byte or two at max.

**Comment by dynasource** [comment]
I agree with Samdark

**Comment by mdmunir** [comment]
I planned to convert all element as javascript variable. So, if it can be compress with gzib, its ok for me.

**Comment by samdark** [comment]
Yes, it absolutely could.

**Comment by adiramardiani** [comment]
You mean [yii2-minify-view](https://github.com/rmrevin/yii2-minify-view) ?

**Comment by samdark** [comment]
I mean Apache or nginx, not PHP code.
