### ISSUE TITLE
Bootstrap NavBar

### ISSUE THREAD

**Issue by claudioferrari** [yiisoft/yii2#9845]
Hello team,
I don't know if is a bug or a desired behavior: in yii\bootstrap\NavBar at line 118 there is a check if brandLabel is false or not but there no check on brandUrl, so if I want to see brandLabel and I set 'brandUrl' => false I expect to see MyCompany brandLabel and no brandUrl, i.e. no href tag should be created.

Thanks in advance

**Comment by cebe** [comment]
according to the [docs] `false` means that the application home url is used. You may set it to `null` to disable `href`.

[docs]: http://stuff.cebe.cc/yii2docs/yii-bootstrap-navbar.html#$brandUrl-detail
