### ISSUE TITLE
\yii\web\User::loginRequired() should throw 401 not 403

### ISSUE THREAD

**Issue by spikyjt** [yiisoft/yii2#9846]
If `loginUrl` is set NULL, `loginRequired()` will throw a \yii\web\ForbiddenHttpException, i.e 403. I think this is incorrect. It should be \yii\web\UnauthorizedException, i.e. 401 as per the spec.

**Comment by cebe** [comment]
I tend to disagree, we had this request before and there are arguments against it:

- https://github.com/yiisoft/yii2/pull/7818#issuecomment-84474283
- https://github.com/yiisoft/yii2/pull/829

@samdark please re-check the decision.

**Comment by spikyjt** [comment]
I've read those and I get the point. The general use case for loginUrl=NULL is for a standalone restful API, which is stateless and every request should be authenticated, therefore 403 is appropriate.

My current use case is that I have a restful-style API for an AJAX application, that does have state. In that case I want to differentiate between unauthorized and unauthenticated. I definitely do not want to redirect my AJAX requests. In this case, 403 definitely doesn't fit the bill. I'm not quite sure what the correct response is, but that's my problem. Just explaining how I came to report this.

I'm happy for you to revert the change.

**Comment by samdark** [comment]
Hmm...

**Comment by samdark** [comment]
Reverted.
