### ISSUE TITLE
DbManager updateItem() doesn't update new name

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#9848]

**Comment by samdark** [comment]
How to reproduce that?

**Comment by duynguyen0511** [comment]
```php
$auth = Yii::$app->authManager;
$role = $auth->getRole('test1');
$auth->update('test2', $role); //$role name doesnt change to 'test2'
```

p/s: my first time to do a pull request so please be patient as I may miss out something :)

**Comment by samdark** [comment]
That's expected. The call could be read as "find role with name = test2 and replace it with $role". Since `$role->name` wasn't changed, it was not updated.

**Comment by duynguyen0511** [comment]
got ya. I misunderstood update() functionality
