### ISSUE TITLE
Ability to rollback a closure-style transactions

### ISSUE THREAD

**Issue by Vovan-VE** [yiisoft/yii2#9851]
Closure-style transaction shortcut is much readable in easy to use, then full code. But closure-style does not allow an easy rollback. The only whay is to `throw` and `catch` custom exception. In that way it will be a mess of that two styles:

```php
try {
    \Yii::$app->db->transaction(function () {
        if (something was wrong) {
            throw new MyRollbackException();
        }
    });
    // done
} catch (MyRollbackException $e) {
    // rolled back
}
```

It whould be very nice to have ability to make rollback more easy. For example, it can be something like this:

```php
\Yii::$app->db->transaction(function () {
    if (something was wrong) {
        throw new \yii\db\RollbackException();
    }
});
```

But the problem is what to do with return value in case of rollback.
May be

```php
$result = \Yii::$app->db->transaction(function () {
    throw new RollbackException(42);
});
// $result === 42
```

or one more closure, which will be called in case of `RollbackException` and which return value will be used in that case:

```php
// another method to keep BC
$result = \Yii::$app->db->transaction2(
    function () {
        throw new RollbackException();
    },
    function (RollbackException $e) {
        return 42;
    }
);
// $result === 42
```

**Comment by SamMousa** [comment]
How about passing the transaction object as an argument to the closure?

        $result = \Yii::$app->db->transaction(function ($db, $transaction) {
           $transaction->rollback();
        return 42;
        });


Note that you can already access the transaction object directly via $db->getTransaction().

**Comment by Vovan-VE** [comment]
@SamMousa, transaction object already can be accessed with `$db->transaction`, but there is only one and the same Transaction object. Any way it will be either commited or rollback'ed inside `transaction()` method. So, using `commit()` or `rollback()` in such manner will broke nested transactions.

**Comment by SamMousa** [comment]
Commit and rollback support nesting just fine, I don't see how this would break it.

**Comment by Vovan-VE** [comment]
@SamMousa, Just try it.

```php
// Transaction::level == 0
// Transaction::begin() ==> START TRANSACTION
// Transaction::level == 1
\Yii::$app->db->transaction(function () {
    // INSERT ...
    // Transaction::begin() ==> SAVEPOINT s1
    // Transaction::level == 2
    \Yii::$app->db->transaction(function ($db) {
        // INSERT
        // Transaction::rollback() ==> ROLLBACK TO SAVEPOINT s1
        $db->transaction->rollback();
        // Transaction::level == 1
    });
    // Transaction::level == 1 <--- but shoud  be 2
    // Transaction::commit() ==> COMMIT
    // Transaction::level == 0
    // whole transaction already committed *errornously*
    // but it 's incomplete yet
    // INSERT ... <--- outside of true transaction
});
// Transaction::level == 0 , but shoud be 1
// Transaction::commit() ==> trying to commit outside of transaction
```

**Comment by SamMousa** [comment]
Ah, I figured out the problem!
`Connection::transaction()` checks `isActive()` to see if it should commit / rollback.
Instead it should inspect the actual isolation level.

For this to be implemented we need to make `private $_level` accessible some how.
Some options for this:
- Normal getter (isolationLevel is currently write-only).
- Add parameter to `getIsActive` to check if the transaction is active at  the given `isolationLevel` (so `$_level >= $level`)

I can implement this if one of these proposals is accepted.

**Comment by samdark** [comment]
Well, it looks like a bug so yes. Try it starting with unit tests that fail.

**Comment by Vovan-VE** [comment]
IMHO, it's not enought. `Connection::transaction()` should to ensure, that `Transaction::begin()` was called by himself and not by another (recursive) `Connection::transaction()` call. For example, `Transaction::begin()` should to return some unique id to pass it into `Transaction::commit()` and `Transaction::rollback()`, or there should be different `Transaction` objects for each `Connection::beginTransaction()` to prevent call to alien `Transaction::commit()` and `Transaction::rollback()`.

I'm sorry, I have no much free time to implement it and check.

**Comment by SamMousa** [comment]
Vovan-VE, there is no need for that. Since `commit` and `rollback` just decrement `$_level`.. The problem is the checks after the closure don't (and currently can't) properly check if the commit / rollback has been called.

**Comment by SamMousa** [comment]
@samdark What approach do you prefer? Readable isolation level, or extra parameter to getIsActive that specifies the isolation level to test against (which defaults to 0, to keep current behavior).

**Comment by samdark** [comment]
Extra parameter to getIsActive means BC break thus could be applied to 2.1 only.

**Comment by SamMousa** [comment]
If it is optional it doesn't break BC right? Anyway, shall I implement `getLevel()` then?

**Comment by samdark** [comment]
It does break BC even if it's optional. It will cause exception in case of method override in nested class.

**Comment by Vovan-VE** [comment]
Why not just to check `Transaction::$level` like this:

```php
// Connection::transaction()
$transaction = $this->beginTransaction($isolationLevel);
$this_level = $transaction->level;
...
while ($transaction->level >= $this_level) {
    $transaction->commit();
}
// or
$transaction->commitLevel($this_level);
```

**Comment by SamMousa** [comment]
Because it is protected. Also, it shouldn't do multiple commits it should only do 1, if you begin a new transaction it is your job to finish it...
