### ISSUE TITLE
Suggestion: Add option to ActiveQuery::asArray() to return an associatvie array.

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#9855]
It could be something like `asArray ($value = true, $key = null)`. If `$key` is not null, an associate array is returned using `$key` instead of indexed. Typically, `$key` is the `id` column name. If `$key` value is not unique in the returned data, the function could either fail or return the last data row. Probably a third boolean argument such as `$uniqueOnly` could be used to return `false` (or thrown exception) when the key value is not unique.

This can help in scenarios that require processing the returned data prior to displaying it especially with related data sets. For example looping through a big set of `products` and increasing a subtotal product counter and value in another array representing the `product_categories`. This could be done on the database level but not a good idea if you want to avoid business logic in the database.

The above example could be achieved via further processing to `asArray()`'s result and filtering the related data array but I believe the above suggestion can enhance the performance in such scenarios.

**Comment by SamMousa** [comment]
It supports that: http://www.yiiframework.com/doc-2.0/yii-db-querytrait.html#indexBy()-detail

**Comment by YasserHassan** [comment]
I did not notice it. Thank you @SamMousa.
