### ISSUE TITLE
Multi Database Connection Based On User Login

### ISSUE THREAD

**Issue by MrAwanishKumar** [yiisoft/yii2#9858]
Hi,

I am working a project which includes more than one organization and I need to keep the database separately for every organization. I would like to know how to handle the dynamic database connection for the whole project. 
I am storing the required parameters for database connection, in the user table, so that I can get these details easily when user logged in (by using identity). 
So I need to know how to create dynamic database connection when the user logged in.

Thanks

**Comment by samdark** [comment]
`new Connection()` etc.

**Comment by MrAwanishKumar** [comment]
Thank you @samdark

I will try and let you know
