### ISSUE TITLE
Formatter works incorrect for 'today', 'yesterday', 'last week', etc.

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii2#9860]
Server time is 2015-10-09 14:00:00 UTC

Set Australia timezone: 
```php
\yii::$app->setTimeZone('Australia/ACT');
```

Echoing of `today` will output incorrect datetime:
```php
echo date('Y-m-d H:i:s', \yii::$app->formatter->asTimestamp(('today'))); // 2015-10-08 11:00:00
```

The workaround is to use native `strtotime` function:
```php
echo date('Y-m-d H:i:s', \yii::$app->formatter->asTimestamp(strtotime('today'))); // 2015-10-09 00:00:00
```

The same behavior keeps for all formatter's methods: `asDate()`, `asDateTime()`, etc. It works incorrect also for the following values: `yesterday`, `last week`, etc. But for `now` and `+1 day` it works fine.

**Comment by SilverFire** [comment]
Checked. This is not an error.

To create timestamp from a relative string, `Yii::$app->formatter->asTimestamp` uses `Yii::$app->formatter->defaultTimeZone`, which defaults to UTC. You pass `today`, which is treated as `beginning of the day in UTC`, than `date` checks current timezone for application, and formats your timestamp representation of as `local time for beginning of the day in UTC`. Yes, when UTC time is 00:00:00, Australia time is 11:00:00
