### ISSUE TITLE
Controller中的actions问题

### ISSUE THREAD

**Issue by shiwolang** [yiisoft/yii2#9863]
Controller中的action不是惰性加载的，是初始化的时候会被运行，当程序运行时无用的Action会被运行使用

**Comment by samdark** [comment]
Please use English.

**Comment by lichunqiang** [comment]
谁说的！

**Comment by samdark** [comment]
@lichunqiang there's currently noone to read Chinese. Qiang is on vacation. Google translate doesn't help to understand issue much so there's basically no choice.
