### ISSUE TITLE
link() foreign model where part of PK is null

### ISSUE THREAD

**Issue by djeux** [yiisoft/yii2#9867]
For example we have a primaryModel which has a Primary key which consists of 2 fields, ID1 and ID2. In some cases ID2 can be null. The primary model can be saved in DB as usual. 
Then we have a relation to the primaryModel which also has a composite primary key whose primary key mirrors the primaryModel.

If you try to use $primaryModel->link('relation', $foreignModel) and the primary model has null as part of the primary key, BaseActiveRecord::bindModels() will throw an InvalidCallException thanks to the 

```
$value = $primaryModel->$pk;
        if ($value === null) {
            throw new InvalidCallException('Unable to link models: the primary key of ' . get_class($primaryModel) . ' is null.');
        }
```

**Comment by dynasource** [comment]
http://stackoverflow.com/questions/386040/whats-wrong-with-nullable-columns-in-composite-primary-keys
