### ISSUE TITLE
active form send from pjax in yii2 do not work

### ISSUE THREAD

**Issue by vadym34** [yiisoft/yii2#9871]
I use ajax for send the active record form. When I send Active record form, pjax not working. 
When I submit the form be carrying js code of activerecord.js

Currently pjax for active record does not work?

**Comment by samdark** [comment]
It works.

**Comment by vadym34** [comment]
why there is a conflict with the processing of the form with the file and active form.js pjax.js

**Comment by samdark** [comment]
I have no idea. Please provide a way to reproduce it.

**Comment by vadym34** [comment]
In attribute form is set 'data-pjax' => true, the container forms wrapped pjax. 


In controller check: 

example test in controller

 if(Yii::$app->request->isAjax){
  echo 'ajax'
}else if(Yii::$app->request->isPajax){
  echo 'pjax'
}


the result is "ajax"


My situation is similar to:
https://github.com/yiisoft/yii2/issues/9566
Is a conflict active record with pjax

**Comment by vadym34** [comment]
why my post is closed ?

**Comment by derekisbusy** [comment]
@vadym34 Pjax is ajax so `Yii::$app->request->isAjax` will also be true in a pjax call. 

If you mean to say you're using ajax validation inside pjax then #13545 solves this.
