### ISSUE TITLE
Double escape not working

### ISSUE THREAD

**Issue by Sepaka22** [yiisoft/yii2#9875]
I need to print number 9 into my input. Only 9. Not 8 or 7.

So my code is 'mask' => '+7 (\\999) 999-99-99'
But it's useless:
![image](https://cloud.githubusercontent.com/assets/13955452/10409068/e1e45b42-6f18-11e5-9aed-db98fbd08445.png)

However it works without yii: http://jsfiddle.net/7jhzf6oh/

Widget upgrade did not help.
https://github.com/RobinHerbots/jquery.inputmask/issues/1069

**Comment by cebe** [comment]
have you tried ` 'mask' => '+7 (\\999) 999-99-99'`?

**Comment by samdark** [comment]
Are you sure widget was updated?

**Comment by Sepaka22** [comment]
I tried double escape at first.
i cant print double escape because github moderates my double escape to one \\ 
and my site do the same.

widget using js v.3.2.2
![7](https://cloud.githubusercontent.com/assets/13955452/10412806/0b7644a8-6f9a-11e5-8820-f497a3a7daaa.png)

**Comment by samdark** [comment]
Well, then it is JS code thing as well... I've fixed version constraints so now it's all about plugin author. We can't do anything from Yii side.

**Comment by Sepaka22** [comment]
no, no, no. this is not "inputmask.js'
![8](https://cloud.githubusercontent.com/assets/13955452/10412910/3d5bde98-6f9e-11e5-9d1e-ad2e1c4b21d9.png)
 error. something else destroy one of my escapes

**Comment by samdark** [comment]
:) That's PHP. Use 4 backslashes.

**Comment by Sepaka22** [comment]
sorry, not working (:
![9](https://cloud.githubusercontent.com/assets/13955452/10412930/561c7784-6f9f-11e5-9082-93e58ea81773.png)

**Comment by samdark** [comment]
But you've got 2 backslashes so the problem is about JavaScript plugin.

**Comment by Sepaka22** [comment]
My first comment: http://jsfiddle.net/7jhzf6oh/
js without yii works perfect imho

**Comment by samdark** [comment]
Sorry about misleading you. The following works:

```php
echo \yii\widgets\MaskedInput::widget([
        'name' => 'phone',
        'mask' => '+7 (\\999) 999-99-99',
]);
```

**Comment by samdark** [comment]
![qip shot - screen 343](https://cloud.githubusercontent.com/assets/47294/10413740/61893b8e-6fbd-11e5-9cab-f4e2b1689f95.png)

**Comment by Sepaka22** [comment]
ok. i think it's a conflict beetween my scripts.
Your example works on one of my pages, but not working on another one.
