### ISSUE TITLE
yii\db\Schema::getColumnPhpType returns string for decimal

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2#9876]
For a column defined as 
````
`payment` decimal(17,2) NOT NULL DEFAULT '0.00'
````
 we get
````
object(yii\db\ColumnSchema)[179]
  public 'name' => string 'payment' (length=7)
  public 'allowNull' => boolean false
  public 'type' => string 'decimal' (length=7)
  public 'phpType' => string 'string' (length=6)
  public 'dbType' => string 'decimal(17,2)' (length=13)
  public 'defaultValue' => string '0.00' (length=4)
  public 'enumValues' => null
  public 'size' => int 17
  public 'precision' => int 17
  public 'scale' => int 2
  public 'isPrimaryKey' => boolean false
  public 'autoIncrement' => boolean false
  public 'unsigned' => boolean false
  public 'comment' => string '' (length=0)
````

I guess `phpType` should be `double` in this case. Should I create a PR for this?

**Comment by samdark** [comment]
No. It could not be double since PHP's double doesn't fit all the values range of database double.

**Comment by razvanphp** [comment]
Is this open for discussion?

While your argument is valid, in practice, when you deal with monetary values, you will for sure want to make mathematical operations, so you will have to cast them to numeric values anyway.

If somebody needs such big numbers, they will use varchar anyway, while in real use cases for decimal this is an issue, when casting you need to make sure what local you use, and replace "," with ".".

**Comment by samdark** [comment]
If you'll cast monetary values that are high enough, you'll screw things up. I'd use https://secure.php.net/manual/en/book.bc.php for monetary things.

**Comment by cebe** [comment]
> so you will have to cast them to numeric values anyway

that is the point, if you cast the values yourself, you know about it. if yii does it automatically, you may not know and run into problems.

**Comment by razvanphp** [comment]
Yes, but since float and double are casted, one can say the framework is inconsistent.

What bothers me is that values are displayed in forms with .00 sufix all the time when stored as string, while for float and double the real part is stripped in this case.

**Comment by cebe** [comment]
float and double will not loose precisino if casted, i.e. float -> float or double -> double.
if you cast a fixed decimal to double or float you can loose precision.
behavior is consistent in that way.

> What bothers me is that values are displayed in forms with .00 sufix all the time when stored as string, while for float and double the real part is stripped in this case.

that is part of the difference, decimal type has a fixed number of digits before decimal point and also after. Float and Double are dynamic in that regard but have the drawback of having rounding problems when it comes to larger numbers.

**Comment by razvanphp** [comment]
Thank you, after intensive reading on the subject I agree with you, I now use BC math functions.

Keep up the good work!
