### ISSUE TITLE
\base\Security should use PHP's password_hash() by default

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#9880]
password_hash() was introduced in PHP 5.5 and today I think the way Security::generatePasswordHash() and validatePassword() choose between that and using crypt() is silly. Better to simply prefer password_hash() when available and avoid the confusing $passwordHashStrategy config variable. Moreover, using crypt() is the default strategy at present.

Options

1. Change algorithms to use password_hash() when available and remove $passwordHashStrategy → Breaks BC.
2. Change algos, leave $passwordHashStrategy alone but ignore it → works, is BC, but unsavory, perhaps even dishonest.
3. Like option 2 but throw an exception with a specific message when an app sets $passwordHashStrategy → is BC [**update** actually it isn't BC but any dev that tests before deployment can easily correct config and be done] but how exactly to implement?
4. Introduce a third value $passwordHashStrategy = 'default', as new default, and this strategy prefers password_hash() when available over crypt() → BC but adds complexity rather than simplifying and making it easier for devs to understand

I think option 1 is a possibility for Yii 2.1. Options 3 and 4 could be done now.

**Comment by samdark** [comment]
`3.` Could be done via check in init.

**Comment by tom--** [comment]
I just updated option 3 because it isn't really BC. It's just not a big problem to upgrade.

@samdark if $passwordHashStrategy can't be changed after init() then I like this option rather a lot.

**Comment by samdark** [comment]
Right. It can be changed..

**Comment by tom--** [comment]
Another option

5. Keep current algorithms and change the default `$passwordHashStrategy = 'password_hash'` → Not BC for anyone on PHP 5.4 but easily fixed in config. Disadvantage: doesn't automatically get apps to use password_hash() when the upgrade from 5.4 happens.

**Comment by samdark** [comment]
Password hashes produced by our current code (w/ any strategy) are compatible with PHP `password_hash`, right?

**Comment by tom--** [comment]
yes, they are. afaik, they are two ways to access the same underlying Bcrypt lib.

**Comment by samdark** [comment]
How about marking `$passwordHashStrategy` w/ `@deprecated` tag and not using it anymore? That's quite prominent in IDEs, is compatible in terms of resulting hash and won't break existing apps.

**Comment by tom--** [comment]
I'm unfamiliar with the behavior of @deprecated in either IDEs or in the Yii online docs. So long as it is obvious then the objection to option 2 is overcome and I like it.

**Comment by tom--** [comment]
My [first draft](https://github.com/tom--/yii2/commit/f02ddfbbd0bbe6a6c760b382527129fe78bae9b6) but I want to add unit tests for strategy compatibility.

And the input checking in validatePassword() no longer seems quite right.

- I put password_verify() at the top because I assume it checks its inputs so we don't have to. But it returns simply true/false, it doesn't throw errors.
- Checking type and non-emptiness of both $password and $hash seems reasonable enough but, beyond that, if hashes could have come from another source, which they can, then why not let crypt() decide the rest?
