### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by soulhunter1987** [yiisoft/yii2#9881]
http://www.yiiframework.com/doc-2.0/guide-tutorial-yii-integration.html#using-both-yii2-yii1

I think line
```
Yii::registerAutoloader(['Yii', 'autoload']);
```
should look like
```
Yii::registerAutoloader(['yii\BaseYii', 'autoload']);
```
otherwise it registeres not Yii2, but Yii1 autoloader twice.

**Comment by cebe** [comment]
adjusted the guide. thanks for reporting!
