### ISSUE TITLE
Unexpected quotes in \yii\db\Expression

### ISSUE THREAD

**Issue by SDKiller** [yiisoft/yii2#9883]
> * When an Expression object is embedded within a SQL statement or fragment,
> * it will be replaced with the [[expression]] property value without any
> * DB escaping or quoting.

Usecase:

```
        $foo = 1;

        $str = $foo . ' AS foo';

        $expr = new \yii\db\Expression($str);

        $rows = (new \yii\db\Query())
            ->select('id')
            ->addSelect($expr)
            ->from(MyModel::tableName())
            ->all();
```

Produces:

>```
>Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column '1' in 'field list'
>
>The SQL being executed was: SELECT `id`, `1` AS `foo` FROM `my_model`
>```

I expected at least
```
SELECT `id`, 1 AS foo FROM `my_model`
```

What I'm missing?

**Comment by arisk** [comment]
Try this `$query->addSelect([(string)$foo => 'foo']);`

**Comment by SDKiller** [comment]
@arisk 

That will not work as php will anyway cast array key to integer in that case.

This works
```
        $str = '(' . $foo .') AS foo';

        $expr = new \yii\db\Expression($str);
```
But I expected that with `Expression` I can do without it.

**Comment by SDKiller** [comment]
String `$foo` is also qouted:

```
        $foo = 'bar';
        $str = $foo . ' AS foo';
        $expr = new \yii\db\Expression($str);
```

```
>Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'bar' in 'field list'
The SQL being executed was: SELECT `bar` AS `foo`, `id` FROM `my_model`

>
```

**Comment by cebe** [comment]
this way it should work: `->addSelect([$expr])`.
If argument is not an array it will be split by `,`. not sure how to fix it or just document the fact.

**Comment by SDKiller** [comment]
Yeah, this works.
Imo, if it cannot be fixed it must be documented.

**Comment by cebe** [comment]
Checked in a fix. should work now.
