### ISSUE TITLE
Архитектурная ошибка Yii2  в соединении и компрессии бандлов

### ISSUE THREAD

**Issue by shastox** [yiisoft/yii2#9885]
Есть бандлы A,B,C,D,E,F. И два раздела сайта: 1й использует A,B,C,D, а второй - C,D,E,F. 

**Задача в реальной практике**: сделать (соединить и сжать) бандл ABCD (один css и один js  в итоге) и показывать его в разделе1, и сделать бандл CDEF (один css и один js файл) и показывать его  разделе2. 

Yii2  не даст нам это сделать, она не даст использовать бандлы C, D в разных таргетах (конфиг assets.php в терминах документации), т.к. в результируемом конфиге, который в доке зовется assets-prod.php, не будет понятно, к какому именно бандлу относится бандл C и D (т.е. к ABCD или к CDEF?). 

Yii2 предлагает сделать 3 бандла:
AB, CD, EF в разделе1 сайта подключать AB и CD, в во 2м - CD и EF. Но в данном случае в каждом разделе сайта будет 2 js файла и 2 css, что неправильно в плане оптимизаций.

Сделать правильно, как описано в самом начале, не так-то просто, т.к. это не предусмотрено фреймворком. Я вижу 2, кривых, пути:
- 2 разных assets-prod-1.php и assets-prod-2.php
- Хитрые манипуляции с конфигом assetManager, а точнее с бандлами.

**Comment by klimov-paul** [comment]
If you have 2 trully independednt site sections, then you can use 2 separated configs for them - that is normal.
Or you can compress your assets into 3 separated targets.
The `AssetManager` is unable to process in any other way.

**Comment by shastox** [comment]
@klimov-paul Вы, похоже, не читали, что в стартовом посте. Я указал на архитектурную проблему в Yii, а также привел реальную практическую задачу. Но, если не ошибаюсь, в одном из обновлений все же это было пофикшено.

**Comment by klimov-paul** [comment]
Еще раз `AssetManager` НЕ может работать так как вы хотите.
По большому счету `AssetCommand` составляет конфигурацию для `AssetManager::bundles`, которая едина(!) для этого менеджера и соответственно приложения которое его использует.

Ваша ситуация:
`BundleC` зависит от `BundleA` и `BundleB` зависит от `BundleA`.

и вы хотите написать конфигурацию для `AssetManager::bundles` таким образом, чтобы если вы загружаете `BundleC`, то применялся одна конфигурация для зависимого `BundleA`, а если загружаете `BundleB` - то другая.

Сожалею, но в рамках одного `AssetManager` это невозможно.

**Comment by shastox** [comment]
В этом и заключается архитектурная ошибка Yii2: при подключении БандлаА не известно, какой именно результирующий JS (или CSS)-файл подключать (дело вовсе не в зависимостях, про которые вы говорите).

**Comment by klimov-paul** [comment]
> при подключении БандлаА не известно, какой именно результирующий JS (или CSS)-файл подключать

Результирующий файл определяется зависимостями которые построены для `BundleA` в процессе сжатия. Разбирая цепочку `depends` в конечном итоге мы приходим к результирующему `BundleTraget`, который хранит сжатые файлы.

> дело вовсе не в зависимостях

Наоборот: здесь все построено на зависимостях.

> Хитрые манипуляции с конфигом assetManager, а точнее с бандлами.

Действительно вы можете составить конфигурацию для `AssetManager::bundles` таким образом, что определенный `AssetBundle` - `BundleA` - будет полностью исключен из дерева зависимостей, однако все это пойдет прахом если где-то в коде он регистрируется напрямую:

```php
BundleA::register(Yii::$app->view);
```

**Comment by shastox** [comment]
Сайт: использует Бандл1 и Бандл2
Сайт-панель: использует Бандл2 и Бандл3.
Сделать так, чтобы сайт использовал один сжатый JS-файл, а сайт-панель использовал другой сжатый JS-файл не получится. Согласны?
Вариант вашего ответа:
1. Это не практическая задача, такого в практике не бывает!
2. Да, это практическая задача, но увы, Yii2 так сделать не может:(
3. Делать для сайта и для сайт-панели по 2 JS-файла. Так делают все. А то, что для всяких SEO лишний запрос к JS или CSS - это плохо, да и ладно.

Вы за какой вариант, а то я до конца не пойму.

**Comment by klimov-paul** [comment]
> Это не практическая задача, такого в практике не бывает!

В каком месте я такое говорил?

> 2. Да, это практическая задача, но увы, Yii2 так сделать не может:(
3. Делать для сайта и для сайт-панели по 2 JS-файла. Так делают все.

Я ответил в самом начале: https://github.com/yiisoft/yii2/issues/9885#issuecomment-243434071

Есть 2 варианта:

1) иметь 2 раздельные конфигурации для `AssetManager::bundles` и проводить 2 независимые компресии. У вас в любом случае будет 2 разных(!) результирующих файла для "Сайта" и "Сайт-панель" даже при том, что часть их содержимого будет повторяться.
Надо сделать 2 разных конфигурации для 2-х разных(!) приложений.

2) Вы можете составить 3 результирующих файла: общий для "Сайта" и "Сайт-панель" и по одному специфичному для каждого. В таком случае вы можете использовать единую конфигурацию и выполнять сжатие один раз.

> А то, что для всяких SEO лишний запрос к JS или CSS - это плохо, да и ладно.

Для SEO оба варианта могут быть равно как хороши так и плохи. Это зависит от того, насколько ваши "Сайта" и "Сайт-панель" независимы друг от друга.
Загружать один JS файл лучше чем 2, но если 2 разных страницы загружают по большому JS файлу, в которых 70% кода повторяется - это тоже не очень хорошо.
Если в одном сеансе "Сайта" и "Сайт-панель"  могут быть вызваны оба, то лучше 2-й вариант.
Если в одном сеансе может быть вызван только один из них - то первый.

Вы можете достигнуть любого.

**Comment by shastox** [comment]
В любом спасибо, что потратили время на ответы.
