### ISSUE TITLE
Mass-assigned empty date saved as '0000-00-00 00:00:00' instead of null, even if table field allows null

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii2#9886]
If an ActiveRecord model has a date field, let's call it `$fdate` with this rule:
```
public function rules() {
    return array(
        array('fdate', 'date', 'format'=>'whatever'),
    );
}
```
(which has allowEmpty true by default) and you mass-assign it, validate and save, e.g.:
```
    $model=MyModel::model()->find($someCriteria);
    $model->attributes=$_POST['MyModel'];
    $model->save();
```
then the following happens: if the field sent via *POST* is empty, the value `0000-00-00 00:00:00` is saved instead of NULL, **even if** the column in the table can be null.

This is **inconsistent** with what happens if you do:
```
  $model=MyModel::model()->find($someCriteria);
  $model->fdate=null;
  $model->save(false);
```
In this case, as expected, if the column can be null, a true `NULL` value is saved to the table row.

(I haven't tested what happens when the table column in the database is set to not allow null values, i.e. `NOT NULL`: I guess the expected behavior, and probably the actual behavior, in this case would be to save the zero-date value both for validated mass-assignment and for explicit single-attribute assignment, that is for both the above examples).

**Comment by samdark** [comment]
In this case you need `default` rule setting `null` prior to `date`.

**Comment by teo1978** [comment]
Whops, I meant to report this against yii 1.1.
Does your answer apply to yii1 too?

**Comment by teo1978** [comment]
Also, I wonder: will that solve the following use case? (I think this applies to other types, not only dates, btw)
Suppose I don't want the default to be null, and I explicitly declare some other non-null default (in the case of date a real-world default could be `new CDbExpression('NOW()')`; in the case of integer or string fields it could be any static non-zero number or non-empty string).
Now a user uses a form to update the model and wants to set the field to null, so he deletes whatever is contained in the corresponding field and sends the form. Will that set the value to the default or to null? If it sets it to the default (which I guess must be the case, otherwise I couldn't see how your solution would work), then there is no way to update a field setting its value to null?

**Comment by samdark** [comment]
Yes. It applies to 1.1 as well. Rules are applies for mass assignment only.

**Comment by teo1978** [comment]
> Rules are applies for mass assignment and validate() only.

I know. The problem I mentioned in my last comment is about mass-assignment.

So I think there's still the problem of how to update a value to null when sending a form, if a non-null default value is defined.
Note that a default value means that there is a default value, it doesn't mean that it cannot be overwritten, and when updating a record via a form, one may want to allow a value to be set to null, even if its default was something else.

**Comment by samdark** [comment]
There are two defaults:

1. The one defined by DBMS.
2. Validator that's defined by developer.

- `#1` applies when value is not provided or when null is provided and column is `not null`.
- `#2` applies only when input value is empty. If developer specified something that is not null there, setting field to null won't be possible but in this case it is intentional.

Rules could be set based on scenario so using different scenarios developer may change possible default values.

**Comment by teo1978** [comment]
>There are two defaults:
> The one defined by DBMS.
> Validator that's defined by developer.

I know
> #1 applies when value is not provided or when null is provided and column is not null.

I know
> #2 (...) If developer specified something that is not null there, setting field to null won't be possible but in this case it is intentional.

And that's the probl-...

> Rules could be set based on scenario so using different scenarios developer may change possible default values.

Oh, ok, **that's the part I missed**. I did think about it but somehow I didn't realize it solves the problem, in most cases at least. You set the non-null default only for the *insert* scenario. For the *update* scenario, you wouldn't want a non-null default unless you intentionally want an empty value to be reset to the default. Ok.

There actually still is a problematic case, but I guess it's rare/minor. There's no way to **distinguish between an empty string `''` and a null value** for a text field, when updating a VARCHAR or TEXT field that can be null. But I guess the practical use cases for such a distinction to have a meaning are pretty rare and can be handled with ad-hoc solutions.

**Comment by samdark** [comment]
> There's no way to distinguish between an empty string '' and a null value for a text field, when updating a VARCHAR or TEXT field that can be null. But I guess the practical use cases for such a distinction to have a meaning are pretty rare and can be handled with ad-hoc solutions.

No since everything that comes from the form is a string.
