### ISSUE TITLE
Debug module, no way to disable 200 requests log ?

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#9887]
I don't need to save requests with statusCode 200, and there's no option to disable that ?

**Comment by samdark** [comment]
No.

**Comment by BenasPaulikas** [comment]
Why not ? I'm saving debug logs even on prod env because some errors like 500 might still occur so it's good to save them :) ?

**Comment by samdark** [comment]
Debug module should not be used at production. It requires running in YII_DEBUG = true mode with is significantly slower than production mode. As for logs they're OK w/o debug module.
