### ISSUE TITLE
model rule  - 'file' extensions seem not 100% work

### ISSUE THREAD

**Issue by ScottHuangZL** [yiisoft/yii2#9888]
Dear Yii2 Team,

I try to upload file with below model.  It is work tofilter xls/zip and so on, however, the extensions limitation failed for outlook .msg files.
It allow select .msg file, but failed to pass validate model, and then cannot upload.

Can you help to look into for this issue? Thanks.

```php
public function rules()
    {
        return [
            [['excelFile'], 'file','skipOnEmpty' => false
                ,'extensions' => 'xls, xlsx, xlsm, msg, zip, 7z, rar'
                ,'maxSize'=>1024*1000 //1M
//                , 'mimeTypes' =>[ 'xls' => 'application/vnd.ms-excel'] //text/plain, image/png
            ],
        ];
    }
```

**Comment by samdark** [comment]
It's a known issue because for some files it's not possible to detect type based on contents. For these you can validate against plaintext and check file extension. Not reliable but would work at least.

**Comment by ScottHuangZL** [comment]
No, I not mention the mimeTypes, you see, I not turn on the 'mimeTypes'.
I just talk about the extensions itself.

For example:
'extensions' => 'xls, xlsx, xlsm, msg, zip, 7z, rar'

I can select xxx.msg to upload at 1st step, but $model->validate() step return false and warning me only can upload 'xls, xlsx, xlsm, msg, zip, 7z, rar' files.  

Can you double check?

**Comment by SilverFire** [comment]
Can you post a sample if `.msg` file, please?

**Comment by ScottHuangZL** [comment]
.msg file is outlook emails.   Usually, I can copy one email from outlook and save to desktop as .msg file.
I cannot attached my company email sample to you due to regulation.

But I think you can rename any xxx.txt file to xxx.msg to testing.
Thanks.

**Comment by SilverFire** [comment]
Okay, I got your problem. File extension `msg` is not described in `yii2\helpers\mimeTypes.php`, so validator treats your `msg` file as unacceptable.

I can offer you two solutions:
 - create your own `mimeTypes.php` and merge `['msg' => 'text/plain']` with contents of default one. Then configure `FileHelper` and set the `mimeMagicFile` pointing to your customized file.
 - in model rule of file validateion set `'checkExtensionByMimeType' => false`. Be careful about this, as @samdark mentioned, it is not reliable but would work at least.

**Comment by ScottHuangZL** [comment]
Can you add .msg type into mimeTypes?
Outlook email is popular, thanks.

**Comment by ScottHuangZL** [comment]
I select option 
```php
'checkExtensionByMimeType' => false
```

Can Yii2 team at least provide different error message in case I not add above code?
It should be not ext error, it is mimeType checking error.

Or, set that flag default as false.

Or, handle .msg type too, since as I mentioned, it is outlook email, popular. Thanks.

**Comment by samdark** [comment]
We're importing Apache mime types: https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types. There's no plan to add more types except if the file is updated by Apache project.

**Comment by ScottHuangZL** [comment]
Ok, thanks.

**Comment by luke-** [comment]
What do you think, if we only validate the mimetype of the extension, if we find a corresponding entry for it in the magicfile?

**Comment by samdark** [comment]
@luke- is the problem you're trying to solve the same as the initial problem indicated in this issue?

**Comment by luke-** [comment]
@samdark yes, we just had the same issue with ".msg" files.
I think it should be sufficient to check the mime type of the file only if it's known (listed in mime type file).

Iust wanted to hear your opinion about this, here is our "fix":
https://github.com/humhub/humhub/commit/49ee6ffab47c8d13fc6479984c722e8c8650e8c2#diff-b6fba767073a31f8509978169968c22bR137

**Comment by samdark** [comment]
@luke- while this mode of checking is convenient, it potentially may cause security issues if either using `checkExtensionByMimeType = false` or falling back to this mode as you are suggesting so I'd not have it in the framework.

**Comment by luke-** [comment]
@samdark In our case I want both, best possible security (if the mime type is known --> checkExtensionByMimeType), but also the support of (still) unknown file/mime types.  But I understand that you don't want to have this behavior in the framework. Anyway, thanks for the clarification and also thanks for the good work!
