### ISSUE TITLE
Passing models from Url Rule to Controller fails

### ISSUE THREAD

**Issue by stefandoorn** [yiisoft/yii2#9889]
In one of our projects we are just using dev-master to load Yii2 (I know, that shouldn't be the case). Anyway, today we experienced the next problem, after running a composer update.

We are using URL Rules, while in the URL Rule finding a model and passing it to a frontend controller.

So, in the URL rule, within the `parseRequest` function:

````
$product = Product::findOne(2105816);
return array('product/index', ['product' => $product]);
````

Outputting $product gives ($product->getAttributes()):

````
Array
(
    [id] => 2105816
    [brand_id] => 1
    [type] => 'Test'
)
````

In the ProductController in frontend:

````
public function actionIndex(Product $product) {
````

Outputting $product gives ($product->getAttributes()):

````
Array
(
    [id] => 
    [brand_id] => 
    [type] => 
)
````

It might never have been the proper method of doing this (passing objects), but it clearly introduces a breaking change somewhere. Unfortunately I can't find which change introduced our problem, so I can't pinpoint it :(

**Comment by samdark** [comment]
You can try git bisect in order to find that change: https://git-scm.com/docs/git-bisect

**Comment by stefandoorn** [comment]
Alright, I used bisect to find the moment the page stopped functioning. I believe this is the part of the composer.lock file that gives the references that changed on the yiisoft/yii2 package:

````
-                "reference": "3136632560e1a57f8a103e5a356d1809a078deec"
+                "reference": "e63916c82f24d0254b24cb7acc5368a6479f045e"
````

**Comment by kidol** [comment]
It ends up here: https://github.com/yiisoft/yii2/blob/master/framework/web/Controller.php#L79

Switching the if statements at L74 & L81 fixes it.

Currently it simply assumes that every class name in method signature does NOT exist as value in `$params`.

**Comment by SamMousa** [comment]
That timing! Just made a feature request that's related: #9890

**Comment by samdark** [comment]
@kidol could you create a pull request?

**Comment by samdark** [comment]
@SamMousa would @kidol change cover your request?

**Comment by stefandoorn** [comment]
Looks like a good fix to me. @kidol, let me know if you can make it, else I'm available to submit it.

**Comment by kidol** [comment]
@stefandoorn Go ahead :) I didn't work on feature nor did I look further into it. Are there any tests for it yet? Probably should also add test for this issue.

**Comment by stefandoorn** [comment]
It looks to me like this fix introduces the problem: #9476. I will make a PR, not sure if it's that easy to test it. Especially as I'm not that familiar with that Yii2 core.

**Comment by SamMousa** [comment]
@samdark, no, but my feature request would resolve his need for custom URL rule implementation I think.

**Comment by kidol** [comment]
@stefandoorn
Looks like test fail with fix:

>Argument 2 passed to yiiunit\framework\web\FakeController::actionAksi6() must be an instance of yii\validators\EmailValidator, string given

This is ugly but passes tests and fixes problem:

```php
if (($class = $param->getClass()) !== null && ($className = $class->getName()) && (!array_key_exists($name, $params) || !$params[$name] instanceof $className)) {
```

The first 2 checks should not be in the if, they should be evaluated before.

Let me know if you need help or want me to do fix.

**Comment by stefandoorn** [comment]
I'm also bumping into the same test error indeed. If you have it ready to commit in there, please submit the PR. Some cleaning + comments in that function would help also, it's not easy to follow what's happening if looking at it for the first time :)

**Comment by kidol** [comment]
OK will make PR.
