### ISSUE TITLE
Support parametrized objects in parameter binding.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#9890]
This is not so much a bug report as it is a feature request.

Currently action parameter binding works as follows:
1. Iterate over action parameters.
2. If a class is hinted:
- Check if application component with name and class exists.
- Use DI container to create object.
3. Else, if named parameter is set.
- Check if param is array type hinted, if so cast to array.
- Pass normally
4. Else if default exists, pass default.
5. Else throw exception.

For me it often happens that I pass in an ID of a model and have a "loadModel" function in the controller.

Syntactically it would be nice if instead I could write:

        public function actionShow(Project $project) {
                
        }

The parameter binding could check if the typehinted class is an instance of ActiveRecord after using the DI container to construct the object and if a parameter with the same name is set. 
That way if it is an instance of ActiveRecord it could use the parameter to find by primary key.

This does not break BC for anyone not using the type hinting. For anyone using type hinting to get a "fresh" AR, (which does not make much sense to me) it would break BC.

This could be further extended to support value objects, for example having a Date value object and throwing 400 errors when the passed data can not be coerced.

Currently there is a gap between types in http requests (where the data type always string) and in the application where arguments have types.

Thoughts and comments please!

**Comment by cebe** [comment]
> This does not break BC for anyone not using the type hinting. For anyone using type hinting to get a "fresh" AR, (which does not make much sense to me) it would break BC

As 2.0.7 is not released yet, we do not need to care about this BC break.

**Comment by SamMousa** [comment]
Want me to create a PR?

**Comment by samdark** [comment]
Yes.

**Comment by SamMousa** [comment]
@samdark How do I write the unit tests?
Currently controller / web tests are separated from AR tests.

If I add the test to ControllerTest it becomes dependent on having a working database. Should I just add it?

**Comment by samdark** [comment]
Is it test-able w/ dummy object or Model (not AR)?

**Comment by SamMousa** [comment]
I'm not sure, I think we need to use actual find methods.
I'll create a PR with some test functions that might need refactoring and I'm hoping you can give me feedback then ;-)

**Comment by samdark** [comment]
OK.

**Comment by SamMousa** [comment]
Almost done, have some questions on behavor regarding default values:

        public function actionShow(Customer $customer = null)

If the passed parameter is a valid but unknown customer id should I pass null or should I throw a not found exception?

Current behavior:
- Without default, throw not found exception when not found.
- Throw badrequest exception when passing an array where expecting a scalar. (Has proper support for composite primary keys).
- With default, pass null if not found.

**Comment by samdark** [comment]
What do you mean by "unknown customer id"? There's no ID in your method.

**Comment by SamMousa** [comment]
Customer is an ActiveRecord model, it has primary key id (I'm using the yii test database schema).

So when you call /somecontroller/show?customer=5, and you typehint $customer you get a Customer object for Customer with primary key 5.

**Comment by samdark** [comment]
So you want to automatically get AR instance from database behind the scenes and throw 404 if it's not found? Sounds a bit too much for DI to me...

**Comment by SamMousa** [comment]
What did you think the idea was then? =)

The use case seems very common to me, also the use case that we break (using DI to insert a blank AR model) seems very uncommon.

We don't have much choice if the argument is not optional, either do not support it at all or support it and throw an exception.

**Comment by samdark** [comment]
I thought you want to ignore auto-binding if it's passed directly to the method.

**Comment by samdark** [comment]
I'd like to hear @yiisoft/core-developers opinion on it.

**Comment by SamMousa** [comment]
Not sure by what you mean with "if it's passed directly to the method.".

Anyway, I'm always up for a discussion and would love some feedback on the idea in general.
I think some other frameworks and maybe Ruby uses this as well (couldn't find it with a quick google search though)

**Comment by samdark** [comment]
I mean when calling action like a method:

```php
$post = Post::findOne($id);
$this->actionView($post);
```

**Comment by samdark** [comment]
The feature itself feels very cool and tempting but definitely is "magical". We're avoiding alike magic for views not calling `render` automatically.

**Comment by SamMousa** [comment]
We don't do any autobinding when you call a function directly right?
So in those cases nothing changes.

**Comment by samdark** [comment]
Not yet. Right.

**Comment by SamMousa** [comment]
Btw @samdark, what did you think the goal was of this feature request? I'm curious since we have obviously had a miscommunication at some point!

**Comment by cebe** [comment]
I have implemented something similar to this in a project of mine, hopefully I'll find some time to look at this this week.

**Comment by klimov-paul** [comment]
Relates #9476

**Comment by klimov-paul** [comment]
I don't like the idea of magical converting URL params specified by user into the ActiveRecord instance.
This may work for the simple use case: fetching record by PK.
However it can not cover more or less comlex use case.

For example: assume user making a purchasing on the site. He should be able to see the history of his purchases and see a detail page for any of them. Thus controller action for such page looks like:

```php
public function actionView($id)
{
    ...
}
```

However user should NOT see purchases made by other users. Thus while searching `Purchase` model I use double condition instead of simple ID match:

```php
$model = Purchase::find()->andWhere(['id' => $id])->andWhere(['userId' => Yii::$app->user->identity->id])-one();
if (!$model) {
     // throw 404 error
}
```

There could be as well checks for model to be "published", "active" and so on.

Proposed solution does not leave any room for such workflows.

**Comment by SamMousa** [comment]
The detailed stuff could simply be handled by overriding a method:

````
protected function createDependency($action, $type, $name, $value = null)
{
}
````
Where `$action` is the name of the action, `$type` is the type hinted class, `$name` is the name of the parameter, `$value` is the user supplied value for the parameter.

That would provide good separation (ie creating the dependency is not part of running hte action) and it creates infinite flexibility.

**Comment by klimov-paul** [comment]
> The detailed stuff could simply be handled by overriding a method:

And what is simple about that?

Why introduce a magic way of binding ActiveRecord, if it can handle only simpiest use case, while its adjusting requires some much effots?

I prefer to stick with old-fasion `findModel()` method approach. It has less confusion and leave prepared space for advancing if needed.

**Comment by SamMousa** [comment]
The argument in favor of supporting "the simplest" case, is that it is also the most used case..
Note that your example where there is some kind of authorization would normally not  be implemented (I hope) at the controller level, instead it would by default be added to the query that is returned by your AR class.

**Comment by dynasource** [comment]
The issue here is that even more magic idd added to the actionX methods which impacts code readibility. Why do we want 1 function to do all the magic?

It would be more clear if a new function is created for this use case

**Comment by klimov-paul** [comment]
> The argument in favor of supporting "the simplest" case, is that it is also the most used case..

Well if it so for you - you are lucky man indeed. Mostly finding records always require additional checks and conditions: owner user reference, status, blong to certain thread etc. Only some "hello world" application does not need that.

> instead it would by default be added to the query that is returned by your AR class.

So you suggest I put `andWhere(['userId' => Yii::$app->user->identity->id])` inside the ActiveRecord model? Are you serious? It will break with exception once run in cosole application!

**Comment by SamMousa** [comment]
My console application also runs in the context of some user, and whether you copy it exactly as is is irrelevant ;-) My point was that if you have access restrictions on your AR model the safest place to do them is inside the AR so they can never be by passed regardless of the controller. Anyway, that's irrelevant.

-- I appreciate the patience and open discussion btw :)

I think from a technical perspective I've contributed as much as I can to this discussion, in the end it is up to you and the team to decide. Thanks for considering regardless of your decision!

**Comment by SilverFire** [comment]
Well, first of all it's not an obvious decision for me.

> The argument in favor of supporting "the simplest" case, is that it is also the most used case

Unfortunately, I tend to agree with @klimov-paul on this. This simplest case that could be shown in the manual, but it's rarely usable in real life.
**Wins:** -1 line, beautiful example in manual, good for apps with minimum logic.
**Looses:** more code in Yii (need to support it), one more concept (increases the barrier to entry), too much magic, more questions on making something a little bit more complicated.

Therefore, I vote for refusing this idea.

@SamMousa we really appreciate for your effort: ideas, contributions and adherence you give to Yii2 and it's community. Thank you for your good mood, argued answers and sensitivity :beers:

**Comment by samdark** [comment]
Hmm... indeed when we're taking statuses and ownership into account it becomes useless... I haven't thought about that previously :(

i.e. it's common when there are N context of using a model. In one context we're in admin panel and want to edit a record regardless of its status or owner. In another context we're in user part and there we need to have both status and owner in condition for editing action. In this case we're either adding it in `createDependency` which feels magical and could become too messy if there are multiple cases like that or we're doing it the old way which is fine but inconsistent with what we have for another context.

**Comment by klimov-paul** [comment]
Unfortunally we can not accept this feature in the core.
Still you should be able to release it as a separated extension.
See my comment on this matter: https://github.com/yiisoft/yii2/pull/9904#issuecomment-179876958
