### ISSUE TITLE
Form submission via link does not support form attribute.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#9893]
Currently Yii supports form submission via the data-method attribute.
If the link is inside a form, Yii will submit that form, if not Yii will create a form for submission.

The current implementation reintroduces an issue that has been fixed for generic inputs in HTML5; form submission when the button is not a child of the form.

I propose to add support for the form attribute.

The change would be minor just changing:

       $form = $e.closest('form')

to:

       $form = $e.attr('form') ? $('#' + $e.attr('form')) : $e.closest('form');

https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L148

This would:
- Add support for links outside forms.
- Not affect BC unless people use the data-form attribute on their links which already have data-method.
- Add support for having a link inside form A submit form B.

**Comment by SilverFire** [comment]
Attribute `form` for links is in the [HTML5 input sepcs ] (http://www.w3schools.com/tags/att_input_form.asp). This enhancement will be helpful, does not conflict with HTML5 standards and, as for me, should be implemented. What about PR?

**Comment by SamMousa** [comment]
I'll make one when a core dev tells me they like this feature as well ;)

**Comment by SilverFire** [comment]
Sure :) I'm voting for

**Comment by SamMousa** [comment]
https://github.com/yiisoft/yii2/pull/10321

**Comment by SamMousa** [comment]
The implementation was merged so closing this.

**Comment by SilverFire** [comment]
Thank you
