### ISSUE TITLE
Formatter->asRelativeTime() doesn't show time

### ISSUE THREAD

**Issue by alexweb** [yiisoft/yii2#9897]
I use it this way: Yii::$app->formatter->asRelativeTime($model->updated_at);
And it shows: {delta, plural, =1{a day} other{# days}} ago
Intl extension is installed.

Is it a bug or I need to configure something on my server?

Locale is en-EN and Intl settings are below:
<img width="964" alt="2015-10-12 22 52 33" src="https://cloud.githubusercontent.com/assets/960052/10437107/8f7ad1de-7133-11e5-9f00-57bb8c3dcc26.png">

**Comment by kidol** [comment]
ICU version too low. #8453

**Comment by alexweb** [comment]
Thanks for quick respond! I will try it.
