### ISSUE TITLE
Weird/Wrong Result with ActiveRecord Query::count()

### ISSUE THREAD

**Issue by BAWES** [yiisoft/yii2#9909]
I have a method returning an `ActiveQuery` in my activerecord model class, then another method under it that returns the `count()` of that query result.

When I call the query by itself and loop through the results, I get 3 records. But when I call the count, I get 6 results (double). I have multiple joins in that `ActiveQuery`, could that be the reason? I also have `["owner"]=> *RECURSION*` in my var dump, what's that and does it have anything to do with this issue?

*My Code:*

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQualifiedStudents(){
        /**
         * Only verified and non-banned students
         */
        $students = Student::find()->active();

        /**
         * Add conditions based on filter values
         */
        $filter = $this->filter;
        if($filter){
            $countryList = $filter->countries;
            $universityList = $filter->universities;
            $languageList = $filter->languages;
            $majorList = $filter->majors;

            $students->minimumGPA($filter->filter_gpa);
            $students->graduationYearBetween($filter->filter_graduation_year_start, $filter->filter_graduation_year_end);
            $students->englishLevel($filter->filter_english_level);
            $students->degree($filter->degree_id);
            $students->nationalityFilter(ArrayHelper::getColumn($countryList, "country_id"));
            $students->universityFilter(ArrayHelper::getColumn($universityList, "university_id"));
            $students->languageFilter(ArrayHelper::getColumn($languageList, "language_id"));
            $students->majorFilter(ArrayHelper::getColumn($majorList, "major_id"));
            if($filter->filter_transportation){
                $students->transportationAvailable($filter->filter_transportation);
            }
        }
        
        return $students;
    }
    
    public function getQualifiedStudentsCount(){
        return $this->getQualifiedStudents()->count();
    }

The following is the output of `var_dump($model->getQualifiedStudents()->all());`

    array(3) { [0]=> object(common\models\Student)#287 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(39) { ["student_id"]=> int(186) ["degree_id"]=> int(2) ["country_id"]=> int(84) ["university_id"]=> int(1) ["student_firstname"]=> string(6) "Yousef" ["student_lastname"]=> string(9) "Al-Mutawa" ["student_dob"]=> string(10) "1992-06-01" ["student_enrolment_year"]=> string(4) "2010" ["student_graduating_year"]=> string(4) "2015" ["student_gpa"]=> string(4) "3.03" ["student_english_level"]=> int(2) ["student_gender"]=> int(1) ["student_transportation"]=> int(1) ["student_contact_number"]=> string(8) "50647795" ["student_interestingfacts"]=> string(32) "I like to keep things organized." ["student_photo"]=> string(36) "ftKhNwxzOmbkY0ZAaz6FOPDW_BV6vp8y.png" ["student_cv"]=> string(37) "I0y5u-CBJEvgs-ZQkh2vmWnrQnqInF3A.docx" ["student_skill"]=> string(10) "Management" ["student_hobby"]=> string(8) "Swimming" ["student_club"]=> NULL ["student_sport"]=> string(17) "Basketball,Squash" ["student_experience_company"]=> string(3) "GCS" ["student_experience_position"]=> string(22) "Communications Officer" ["student_verification_attachment"]=> NULL ["student_email_verification"]=> int(1) ["student_id_verification"]=> int(1) ["student_id_number"]=> NULL ["student_email_preference"]=> int(1) ["student_email"]=> string(20) "x@gmail.com" ["student_auth_key"]=> string(32) "s2Yo54cldVVeuqY_27i0Tz66znOCSmZi" ["student_password_hash"]=> string(60) "$2y$13$SK91i0LcsQ82Y01nzgTROedpKEyYq6IbwvdK.PCUf3XwsxE/s5wAK" ["student_password_reset_token"]=> string(0) "" ["student_language_pref"]=> string(5) "en-US" ["student_note"]=> NULL ["student_banned"]=> int(0) ["student_support_field"]=> string(0) "" ["student_limit_email"]=> string(19) "2015-09-30 01:41:56" ["student_updated_datetime"]=> string(19) "2015-09-30 01:53:03" ["student_datetime"]=> string(19) "2015-09-30 01:20:26" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(39) { ["student_id"]=> int(186) ["degree_id"]=> int(2) ["country_id"]=> int(84) ["university_id"]=> int(1) ["student_firstname"]=> string(6) "Yousef" ["student_lastname"]=> string(9) "Al-Mutawa" ["student_dob"]=> string(10) "1992-06-01" ["student_enrolment_year"]=> string(4) "2010" ["student_graduating_year"]=> string(4) "2015" ["student_gpa"]=> string(4) "3.03" ["student_english_level"]=> int(2) ["student_gender"]=> int(1) ["student_transportation"]=> int(1) ["student_contact_number"]=> string(8) "50647795" ["student_interestingfacts"]=> string(32) "I like to keep things organized." ["student_photo"]=> string(36) "ftKhNwxzOmbkY0ZAaz6FOPDW_BV6vp8y.png" ["student_cv"]=> string(37) "I0y5u-CBJEvgs-ZQkh2vmWnrQnqInF3A.docx" ["student_skill"]=> string(10) "Management" ["student_hobby"]=> string(8) "Swimming" ["student_club"]=> NULL ["student_sport"]=> string(17) "Basketball,Squash" ["student_experience_company"]=> string(3) "GCS" ["student_experience_position"]=> string(22) "Communications Officer" ["student_verification_attachment"]=> NULL ["student_email_verification"]=> int(1) ["student_id_verification"]=> int(1) ["student_id_number"]=> NULL ["student_email_preference"]=> int(1) ["student_email"]=> string(20) "dwa@gmail.com" ["student_auth_key"]=> string(32) "s2Yo54cldVVeuqY_27i0Tz66znOCSmZi" ["student_password_hash"]=> string(60) "$2y$13$SK91i0LcsQ82Y01nzgTROedpKEyYq6IbwvdK.PCUf3XwsxE/s5wAK" ["student_password_reset_token"]=> string(0) "" ["student_language_pref"]=> string(5) "en-US" ["student_note"]=> NULL ["student_banned"]=> int(0) ["student_support_field"]=> string(0) "" ["student_limit_email"]=> string(19) "2015-09-30 01:41:56" ["student_updated_datetime"]=> string(19) "2015-09-30 01:53:03" ["student_datetime"]=> string(19) "2015-09-30 01:20:26" } ["_related":"yii\db\BaseActiveRecord":private]=> array(2) { ["languages"]=> array(2) { [0]=> object(common\models\Language)#312 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(1) ["language_name_en"]=> string(7) "English" ["language_name_ar"]=> string(20) "الإنجليزية" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(1) ["language_name_en"]=> string(7) "English" ["language_name_ar"]=> string(20) "الإنجليزية" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } [1]=> object(common\models\Language)#313 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(2) ["language_name_en"]=> string(6) "Arabic" ["language_name_ar"]=> string(14) "العربية" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(2) ["language_name_en"]=> string(6) "Arabic" ["language_name_ar"]=> string(14) "العربية" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } } ["majors"]=> array(1) { [0]=> object(common\models\Major)#314 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["major_id"]=> int(269) ["major_name_en"]=> string(22) "International Business" ["major_name_ar"]=> string(23) "اعمال عالمية" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["major_id"]=> int(269) ["major_name_en"]=> string(22) "International Business" ["major_name_ar"]=> string(23) "اعمال عالمية" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } } } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(2) { ["beforeInsert"]=> array(1) { [0]=> array(2) { [0]=> array(2) { [0]=> object(yii\behaviors\TimestampBehavior)#289 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#288 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } [1]=> string(18) "evaluateAttributes" } [1]=> NULL } } ["beforeUpdate"]=> array(1) { [0]=> array(2) { [0]=> array(2) { [0]=> object(yii\behaviors\TimestampBehavior)#289 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#288 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } [1]=> string(18) "evaluateAttributes" } [1]=> NULL } } } ["_behaviors":"yii\base\Component":private]=> array(1) { [0]=> object(yii\behaviors\TimestampBehavior)#289 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#288 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } } } [1]=> object(common\models\Student)#290 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(39) { ["student_id"]=> int(210) ["degree_id"]=> int(2) ["country_id"]=> int(84) ["university_id"]=> int(2) ["student_firstname"]=> string(5) "Jarah" ["student_lastname"]=> string(10) "Alshimmeri" ["student_dob"]=> string(10) "1992-11-01" ["student_enrolment_year"]=> string(4) "2010" ["student_graduating_year"]=> string(4) "2015" ["student_gpa"]=> string(4) "2.20" ["student_english_level"]=> int(2) ["student_gender"]=> int(1) ["student_transportation"]=> int(1) ["student_contact_number"]=> string(8) "55543256" ["student_interestingfacts"]=> string(48) "I love to listen to music only while i'm driving" ["student_photo"]=> string(36) "n9bNkBl5UboUjkFnGD1gIWDvuFgMN6dY.jpg" ["student_cv"]=> string(37) "3mOyR7E8-ES-_C6iP4I4SLZYePzTZodb.docx" ["student_skill"]=> string(83) "Teamwork,Leadership,Communication skills,presentation skills,Decision making skills" ["student_hobby"]=> string(21) "MMA,Social activities" ["student_club"]=> NULL ["student_sport"]=> string(3) "MMA" ["student_experience_company"]=> NULL ["student_experience_position"]=> NULL ["student_verification_attachment"]=> string(36) "ELGjzedWSJc0blZJEH1I5lQ_4n4WIYOH.jpg" ["student_email_verification"]=> int(1) ["student_id_verification"]=> int(1) ["student_id_number"]=> string(9) "210116905" ["student_email_preference"]=> int(1) ["student_email"]=> string(24) "j.dwad@gmail.com" ["student_auth_key"]=> string(32) "49NYzqKoV8cORtptKDhkJahXcQdV3Iq9" ["student_password_hash"]=> string(60) "$2y$13$Jea3Oqgnh.0p/NBUGnUpneUEOxS.4LwhCddfk0sQ4UUweHfKAA5KG" ["student_password_reset_token"]=> string(0) "" ["student_language_pref"]=> string(5) "en-US" ["student_note"]=> NULL ["student_banned"]=> int(0) ["student_support_field"]=> string(0) "" ["student_limit_email"]=> string(19) "2015-10-04 11:35:02" ["student_updated_datetime"]=> string(19) "2015-10-10 19:02:51" ["student_datetime"]=> string(19) "2015-10-04 11:35:02" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(39) { ["student_id"]=> int(210) ["degree_id"]=> int(2) ["country_id"]=> int(84) ["university_id"]=> int(2) ["student_firstname"]=> string(5) "Jarah" ["student_lastname"]=> string(10) "Alshimmeri" ["student_dob"]=> string(10) "1992-11-01" ["student_enrolment_year"]=> string(4) "2010" ["student_graduating_year"]=> string(4) "2015" ["student_gpa"]=> string(4) "2.20" ["student_english_level"]=> int(2) ["student_gender"]=> int(1) ["student_transportation"]=> int(1) ["student_contact_number"]=> string(8) "55543256" ["student_interestingfacts"]=> string(48) "I love to listen to music only while i'm driving" ["student_photo"]=> string(36) "n9bNkBl5UboUjkFnGD1gIWDvuFgMN6dY.jpg" ["student_cv"]=> string(37) "3mOyR7E8-ES-_C6iP4I4SLZYePzTZodb.docx" ["student_skill"]=> string(83) "Teamwork,Leadership,Communication skills,presentation skills,Decision making skills" ["student_hobby"]=> string(21) "MMA,Social activities" ["student_club"]=> NULL ["student_sport"]=> string(3) "MMA" ["student_experience_company"]=> NULL ["student_experience_position"]=> NULL ["student_verification_attachment"]=> string(36) "ELGjzedWSJc0blZJEH1I5lQ_4n4WIYOH.jpg" ["student_email_verification"]=> int(1) ["student_id_verification"]=> int(1) ["student_id_number"]=> string(9) "210116905" ["student_email_preference"]=> int(1) ["student_email"]=> string(24) "j.dwa@gmail.com" ["student_auth_key"]=> string(32) "49NYzqKoV8cORtptKDhkJahXcQdV3Iq9" ["student_password_hash"]=> string(60) "$2y$13$Jea3Oqgnh.0p/NBUGnUpneUEOxS.4LwhCddfk0sQ4UUweHfKAA5KG" ["student_password_reset_token"]=> string(0) "" ["student_language_pref"]=> string(5) "en-US" ["student_note"]=> NULL ["student_banned"]=> int(0) ["student_support_field"]=> string(0) "" ["student_limit_email"]=> string(19) "2015-10-04 11:35:02" ["student_updated_datetime"]=> string(19) "2015-10-10 19:02:51" ["student_datetime"]=> string(19) "2015-10-04 11:35:02" } ["_related":"yii\db\BaseActiveRecord":private]=> array(2) { ["languages"]=> array(2) { [0]=> object(common\models\Language)#312 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(1) ["language_name_en"]=> string(7) "English" ["language_name_ar"]=> string(20) "الإنجليزية" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(1) ["language_name_en"]=> string(7) "English" ["language_name_ar"]=> string(20) "الإنجليزية" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } [1]=> object(common\models\Language)#313 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(2) ["language_name_en"]=> string(6) "Arabic" ["language_name_ar"]=> string(14) "العربية" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(2) ["language_name_en"]=> string(6) "Arabic" ["language_name_ar"]=> string(14) "العربية" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } } ["majors"]=> array(1) { [0]=> object(common\models\Major)#315 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["major_id"]=> int(279) ["major_name_en"]=> string(9) "Marketing" ["major_name_ar"]=> string(10) "تسويق" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["major_id"]=> int(279) ["major_name_en"]=> string(9) "Marketing" ["major_name_ar"]=> string(10) "تسويق" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } } } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(2) { ["beforeInsert"]=> array(1) { [0]=> array(2) { [0]=> array(2) { [0]=> object(yii\behaviors\TimestampBehavior)#292 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#291 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } [1]=> string(18) "evaluateAttributes" } [1]=> NULL } } ["beforeUpdate"]=> array(1) { [0]=> array(2) { [0]=> array(2) { [0]=> object(yii\behaviors\TimestampBehavior)#292 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#291 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } [1]=> string(18) "evaluateAttributes" } [1]=> NULL } } } ["_behaviors":"yii\base\Component":private]=> array(1) { [0]=> object(yii\behaviors\TimestampBehavior)#292 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#291 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } } } [2]=> object(common\models\Student)#293 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(39) { ["student_id"]=> int(288) ["degree_id"]=> int(2) ["country_id"]=> int(84) ["university_id"]=> int(5) ["student_firstname"]=> string(4) "Dana" ["student_lastname"]=> string(7) "Binsabt" ["student_dob"]=> string(10) "1993-12-08" ["student_enrolment_year"]=> string(4) "2012" ["student_graduating_year"]=> string(4) "2015" ["student_gpa"]=> string(4) "3.50" ["student_english_level"]=> int(2) ["student_gender"]=> int(0) ["student_transportation"]=> int(1) ["student_contact_number"]=> string(8) "51433100" ["student_interestingfacts"]=> string(41) "I love traveling and exploding new things" ["student_photo"]=> NULL ["student_cv"]=> string(37) "cXe7m3EqK1FEku_fdRZZm1x2qkayfLHp.docx" ["student_skill"]=> string(100) "Teamwork,Photography,Management,Sports,Communication skills,Marketing,Advertisement skills,Bilingual" ["student_hobby"]=> string(29) "cooking,Baking,Sports,Reading" ["student_club"]=> NULL ["student_sport"]=> string(10) "Volleyball" ["student_experience_company"]=> string(5) "Loyac" ["student_experience_position"]=> string(21) "Internship SUPERVISOR" ["student_verification_attachment"]=> NULL ["student_email_verification"]=> int(1) ["student_id_verification"]=> int(1) ["student_id_number"]=> NULL ["student_email_preference"]=> int(2) ["student_email"]=> string(21) "1109262@go.ack.edu.kw" ["student_auth_key"]=> string(32) "bIw00hjmN7jekLOoED7q0i32M8R0NL7C" ["student_password_hash"]=> string(60) "$2y$13$bEWDCcxp8waRObSj66aYmO37uqr/lFx3AeN0BxzgJGs9juCvDf8Zu" ["student_password_reset_token"]=> string(0) "" ["student_language_pref"]=> string(5) "en-US" ["student_note"]=> NULL ["student_banned"]=> int(0) ["student_support_field"]=> string(0) "" ["student_limit_email"]=> string(19) "2015-10-10 23:17:38" ["student_updated_datetime"]=> string(19) "2015-10-10 23:20:16" ["student_datetime"]=> string(19) "2015-10-10 23:17:38" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(39) { ["student_id"]=> int(288) ["degree_id"]=> int(2) ["country_id"]=> int(84) ["university_id"]=> int(5) ["student_firstname"]=> string(4) "Dana" ["student_lastname"]=> string(7) "Binsabt" ["student_dob"]=> string(10) "1993-12-08" ["student_enrolment_year"]=> string(4) "2012" ["student_graduating_year"]=> string(4) "2015" ["student_gpa"]=> string(4) "3.50" ["student_english_level"]=> int(2) ["student_gender"]=> int(0) ["student_transportation"]=> int(1) ["student_contact_number"]=> string(8) "51433100" ["student_interestingfacts"]=> string(41) "I love traveling and exploding new things" ["student_photo"]=> NULL ["student_cv"]=> string(37) "cXe7m3EqK1FEku_fdRZZm1x2qkayfLHp.docx" ["student_skill"]=> string(100) "Teamwork,Photography,Management,Sports,Communication skills,Marketing,Advertisement skills,Bilingual" ["student_hobby"]=> string(29) "cooking,Baking,Sports,Reading" ["student_club"]=> NULL ["student_sport"]=> string(10) "Volleyball" ["student_experience_company"]=> string(5) "Loyac" ["student_experience_position"]=> string(21) "Internship SUPERVISOR" ["student_verification_attachment"]=> NULL ["student_email_verification"]=> int(1) ["student_id_verification"]=> int(1) ["student_id_number"]=> NULL ["student_email_preference"]=> int(2) ["student_email"]=> string(21) "dwadwad@go.ack.edu.kw" ["student_auth_key"]=> string(32) "bIw00hjmN7jekLOoED7q0i32M8R0NL7C" ["student_password_hash"]=> string(60) "$2y$13$bEWDCcxp8waRObSj66aYmO37uqr/lFx3AeN0BxzgJGs9juCvDf8Zu" ["student_password_reset_token"]=> string(0) "" ["student_language_pref"]=> string(5) "en-US" ["student_note"]=> NULL ["student_banned"]=> int(0) ["student_support_field"]=> string(0) "" ["student_limit_email"]=> string(19) "2015-10-10 23:17:38" ["student_updated_datetime"]=> string(19) "2015-10-10 23:20:16" ["student_datetime"]=> string(19) "2015-10-10 23:17:38" } ["_related":"yii\db\BaseActiveRecord":private]=> array(2) { ["languages"]=> array(2) { [0]=> object(common\models\Language)#312 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(1) ["language_name_en"]=> string(7) "English" ["language_name_ar"]=> string(20) "الإنجليزية" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(1) ["language_name_en"]=> string(7) "English" ["language_name_ar"]=> string(20) "الإنجليزية" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } [1]=> object(common\models\Language)#313 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(2) ["language_name_en"]=> string(6) "Arabic" ["language_name_ar"]=> string(14) "العربية" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["language_id"]=> int(2) ["language_name_en"]=> string(6) "Arabic" ["language_name_ar"]=> string(14) "العربية" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } } ["majors"]=> array(1) { [0]=> object(common\models\Major)#315 (8) { ["_attributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["major_id"]=> int(279) ["major_name_en"]=> string(9) "Marketing" ["major_name_ar"]=> string(10) "تسويق" } ["_oldAttributes":"yii\db\BaseActiveRecord":private]=> array(3) { ["major_id"]=> int(279) ["major_name_en"]=> string(9) "Marketing" ["major_name_ar"]=> string(10) "تسويق" } ["_related":"yii\db\BaseActiveRecord":private]=> array(0) { } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } } } } ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(2) { ["beforeInsert"]=> array(1) { [0]=> array(2) { [0]=> array(2) { [0]=> object(yii\behaviors\TimestampBehavior)#295 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#294 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } [1]=> string(18) "evaluateAttributes" } [1]=> NULL } } ["beforeUpdate"]=> array(1) { [0]=> array(2) { [0]=> array(2) { [0]=> object(yii\behaviors\TimestampBehavior)#295 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#294 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } [1]=> string(18) "evaluateAttributes" } [1]=> NULL } } } ["_behaviors":"yii\base\Component":private]=> array(1) { [0]=> object(yii\behaviors\TimestampBehavior)#295 (5) { ["createdAtAttribute"]=> string(16) "student_datetime" ["updatedAtAttribute"]=> string(24) "student_updated_datetime" ["value"]=> object(yii\db\Expression)#294 (2) { ["expression"]=> string(5) "NOW()" ["params"]=> array(0) { } } ["attributes"]=> array(2) { ["beforeInsert"]=> array(2) { [0]=> string(16) "student_datetime" [1]=> string(24) "student_updated_datetime" } ["beforeUpdate"]=> string(24) "student_updated_datetime" } ["owner"]=> *RECURSION* } } } }

**Comment by cebe** [comment]
> I have multiple joins in that ActiveQuery, could that be the reason?

very likely, fetching the results will filter duplicate records, count will just get the count from DB so duplicates are included.

**Comment by cebe** [comment]
btw: you can disable filtering of records by setting indexBy to something that does not kick out duplicates.

**Comment by jamesepi** [comment]
I was having a similar issue.

I defined a query that used joinWith.

Then, 
calling $query->count() would give me 10
but calling $query->all() would return only 6 records

So, after reading this thread i tried the following:
$query->distinct()

And finally i got the right count
$query->count() = 6
$query->all() returned 6 records.

**Comment by BAWES** [comment]
That's cool! Thanks for the solution

Best Regards,
Khalid Al-Mutawa

**Comment by credencysrajesh** [comment]
still not working reduced only 1 count

Then,
calling $query->count() would give me 8
but calling $query->all() would return only 3 records

So, after reading this thread i tried the following:
$query->distinct()

And finally i got the right count
$query->count() = 7
$query->all() returned 3 records.
