### ISSUE TITLE
Multiple queries on identity class table

### ISSUE THREAD

**Issue by jacksumit** [yiisoft/yii2#9913]
Yii is generating a query on identity class once per request where action code is calling Yii::$app->user->isGuest . Is this expected? Isn't identity class instance stored in seasion?

**Comment by lichunqiang** [comment]
Yes, not instance but the primary key

**Comment by jacksumit** [comment]
So these multiple queries are expected?

**Comment by lichunqiang** [comment]
Yes.

**Comment by dynasource** [comment]
duplicate of https://github.com/yiisoft/yii2/issues/4464

**Comment by jacksumit** [comment]
Thanks for clarifying.
