### ISSUE TITLE
HttpCache last modified and seo implementations

### ISSUE THREAD

**Issue by Bdiang** [yiisoft/yii2#9918]
Current realization is not applicaple for seo, because in behaviour we set LM header based on stored data changed time. But if we change seo stuff: title, h1, text we cannot tell crawlers to rescan page, because of 304 not modified header (data in DB did not change).

**Comment by samdark** [comment]
Aren't title, h1 and text are from DB as well?

**Comment by Bdiang** [comment]
In Yii2? No in doesn't. For example I change text in view "Pizza in NY" to "Pizza delivery in NY". I can change meta tags description/keywords or just seo text.

**Comment by samdark** [comment]
Well, you can specify where to get the time via `lastModified` callback.

**Comment by Bdiang** [comment]
Usually it could be solved by storing hash of page in DB along with date and do some logic with hash, hashDate and if-modified-since. 

Is it possible calculate page hash based on content in that callback?

**Comment by kidol** [comment]
You could use etagSeed I guess:

```php
'only' => ['view'],
'etagSeed' => function ($action, $params) {
   return Yii::$app-db->createCommand("
      SELECT CONCAT(title, '_', keywords, '_', update_time) FROM article
         WHERE id = :id
   ")->bindValues(['id' => $_GET['id'])->queryScalar();
}
```
If title, keywords or update_time changes in db, then etag changes too. Or you update update_time when somthing changes, then you can use lastModified instead.

**Comment by samdark** [comment]
@Bdiang yes. You can use filemtime on the view.

**Comment by Bdiang** [comment]
Thanks.
