### ISSUE TITLE
Timezone - formatter - model->save()

### ISSUE THREAD

**Issue by sreenadh** [yiisoft/yii2#9920]
in php.ini timezone is UTC. system timezone is UTC. yii defaultTimeZone is UTC. But my datetime attribute gets converted to my timezone "Asia/Kolkata" before saving into db.

Eg: UTC time 12:00Hrs
my input 17.30hrs
what I expect in db is 12:00hrs and in view 17.30hrs
But what I got in db is 17:30hrs and in view I got 23:00hrs.

web.php:
```
'formatter' => 
        [
			'class' => 'yii\i18n\Formatter',
			'dateFormat' => 'php:d-m-Y',
			'datetimeFormat' => 'php:d-m-Y H:i a',
			'timeFormat' => 'php:H:i A',
			'timeZone' => 'Asia/Kolkata',
		],
```

**Comment by sreenadh** [comment]
@cebe need to convert from user timezone to UTC. formatter does not do any conversion on beforeSave.

**Comment by SilverFire** [comment]
Looks similar with #9937

**Comment by cebe** [comment]
@sreenadh are you using datevalidator to validate the value?

**Comment by sreenadh** [comment]
@cebe yes

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/yii-validators-datevalidator.html#$timeZone-detail

> If this property is not set, yii\base\Application::$timeZone will be used.

which is `UTC`, so your input is assumed to be 17:30 UTC.

> yii defaultTimeZone is UTC

do you mean `Yii::$app->timeZone`?

**Comment by sreenadh** [comment]
my input will be in Asia/Kolkata and I should get that value stored in db as UTC and show in view as Asia/Kolkata

**Comment by cebe** [comment]
then why did you set `Yii::$app->timeZone` to UTC? You have to either set `Yii::$app->timeZone` to your timezone or configure $timeZone property of the date validator to be `Asia/Kolkata`.

**Comment by sreenadh** [comment]
web.php
```
$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'timeZone' => 'Asia/Kolkata',
    'components' => [
		'formatter' => 
        [
			'class' => 'yii\i18n\Formatter',
			 'nullDisplay' => '',
			'dateFormat' => 'php:d-m-Y',
			'datetimeFormat' => 'php:d-m-Y h:i A',
			'timeFormat' => 'php:h:i A',
			'defaultTimeZone' => 'UTC',
			'timeZone' => 'Asia/Kolkata',
		],
```    
in model 

```
 public function rules()
    {
        return [
           [['created_datetime'], 'safe'],
            [['created_datetime'], 'date', 'format' => "php:d-m-Y h:i A" ],
        ];
    }
``

But Date time is saved in database as "0000-00-00 00:00:00" !
