### ISSUE TITLE
Enhancement: Allow filling multiple attributes with different values in AttributeBehavior

### ISSUE THREAD

**Issue by YasserHassan** [yiisoft/yii2#9921]
It would be good to enable filling multiple model attributes with different values in AttributeBehavior. When AttributeBehavior is used with multiple attributes as in
```
public function behaviors()
{
    return [
        [
            'class' => AttributeBehavior::className(),
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['attribute1', 'attribute2'],
                ActiveRecord::EVENT_BEFORE_UPDATE => ['attribute1', 'attribute2'],
            ],
            'value' => function ($event) {
                return 'some value';
            },
        ],
    ];
}
```
it is more likely that `attribute1` and `attribute2` need to be assigned different values than the same one, otherwise they would be replaced by a single column in the database. A work around would be using multiple behaviors but it's not always a good idea.

**Comment by SamMousa** [comment]
I feel the natural Yii syntax would be: 

       'attributes' => [
           ActiveRecord::EVENT_BEFORE_INSERT => [
                'attribute1' => function($event) { return 42; }, 
                'attribute2'
       ],

Note that currently AttributeBehavior ignores the attribute if it is not a string:
> // ignore attribute names which are not string (e.g. when set by TimestampBehavior::updatedAtAttribute)

As far as I can tell TimestampBehavior also does not set string keys, so it should be safe to use string keys to check if it is a attribute => value pair vs an attribute name.

I see no BC issues.

**Comment by YasserHassan** [comment]
@SamMousa the drawback of your syntax is that you'll run a different function for each attribute. If there's shared functionality like retrieving records from the database and performing calculations on them (e.g. looping and calculating total value for `attribute1` and count for `attribute2`), you'll either need to execute the shared part once for each attribute or resolve to a complicated implementation.

Using the array format `ActiveRecord::EVENT_BEFORE_INSERT => ['attribute1', 'attribute2']` with a single function whose return could be assigned as a different value to each attribute would be a more generic solution.

**Comment by SamMousa** [comment]
We could pass the result of the generic value function to the closure.
That seems clean and flexible to me.

**Comment by SamMousa** [comment]
Side note: the closure is defined per model instance so you could even utilize a static variable inside the Closure

**Comment by YasserHassan** [comment]
Passing a result of a generic function would require a generic function at the first place, besides we'd lose the benefit of a single loop in my example above. I agree static variable are a way but I believe this will complicate things as we'll need to think how both functions will work together and which will come first, or check if that variable is set to set it using an external functional. In my opinion things could be done in a simpler and more maintainable way by using a single function/closure.

I'm sure we'll reach the best way to do it but before all we need to know whether this suggestion will gain acceptance or not.

**Comment by SamMousa** [comment]
> Passing a result of a generic function would require a generic function at the first place

I did not say "a" generic function, but the, because it already exists.

Look at the value key in your original post. That is the generic value function, the individual attributes can than take that result as closure argument and use it if they want.

**Comment by usualdesigner** [comment]
Can you add two behaviors with the 'AttributeBehavior' class? Like that: 

```
    public function behaviors()
    {
        return [
            'attr_one' => [
                'class' => AttributeBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_VALIDATE => 'attr_one',
                ],
                'value' => function ($event) {
                    return YOUR VALUE;
                },
            ],
            'attr_two' => [
                'class' => AttributeBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_VALIDATE => 'attr_two',
                ],
                'value' => function ($event) {
                    return YOUR VALUE;
                },
            ],
        ];
    }
```

**Comment by SamMousa** [comment]
Usualdesigner, yes you can as mentioned in the original post; it is not ideal though.

**Comment by SamMousa** [comment]
I think the issue has been described clearly, lets wait for a team member to point us in a direction for a solution (if any).

**Comment by samdark** [comment]
I'm for keeping it simple i.e. going with @usualdesigner way of dealing with it.
