### ISSUE TITLE
strftime > setLocale()

### ISSUE THREAD

**Issue by njitram** [yiisoft/yii2#9927]
When using strftime i hoped locale was set by using the 'language' config parameter, but it isn't. Can you add setLocale to the internationalization?

**Comment by mikehaertl** [comment]
The situation is not so easy. From the PHP manual:

> **Warning** The locale information is maintained per process, not per thread. If you are running PHP on a multithreaded server API like IIS, HHVM or Apache on Windows, you may experience sudden changes in locale settings while a script is running, though the script itself never called setlocale(). This happens due to other scripts running in different threads of the same process at the same time, changing the process-wide locale using setlocale().

The other thing is, that you don't know, which locales are available on your system. On Linux based OS you can find out with `locale -a`. You can only use locales that are available there.

I had the same problem with `asort()` and ended up writing a sort helper class, that uses an existing locale. It also resets the locale setting after execution:

```
class SortHelper
{
    /**
     * Apply asort() on an array and set loclae to 'en_US.utf8' for correct ordering of umlauts
     *
     * @param array $array the array to sort
     */
    public static function asort(&$array)
    {
        $locale = setlocale(LC_COLLATE, '');
        @setlocale(LC_COLLATE, 'en_US.utf8');
        asort($array, SORT_LOCALE_STRING | SORT_FLAG_CASE);
        @setlocale(LC_COLLATE, $locale);
    }
}
```

**Comment by njitram** [comment]
Thank you for your answer. I didn't solve the problem, i integrated Yii2 in the library, like so:
    $format = 'EEEE d MMMM, \'\'yy';
    Yii::$app->getFormatter()->asDatetime($timestamp, $format);
