### ISSUE TITLE
SchemaBuilderTrait is missing unsigned attribute

### ISSUE THREAD

**Issue by stratoss** [yiisoft/yii2#9929]
How ```Schema::TYPE_SMALLINT . ' UNSIGNED NULL',``` could be transformed?

```$this->smallInteger()``` returns just ```smallint``` and I can't find a way to set the unsigned attribute.

**Comment by samdark** [comment]
`$this->smallInteger() . ' UNSIGNED NULL'`?

**Comment by stratoss** [comment]
I'm already using it like this, but I thought something like ```$this->smallInteger()->unsigned()->null()``` would be more convenient, just like ```$this->smallInteger()->notNull()``` for example.

**Comment by pana1990** [comment]
duplicated https://github.com/yiisoft/yii2/issues/9443
