### ISSUE TITLE
Documentation issue on packagist.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#9930]
https://packagist.org/packages/yiisoft/yii2

Not sure where the readme is coming from, but as far as I can tell yiisoft/yii2 is not a git submodule.

> This repository is a git submodule of https://github.com/yiisoft/yii2. Please submit issue reports and pull requests to the main repository. For license information check the LICENSE-file.

**Comment by samdark** [comment]
It's a subsplit, not submodule.

**Comment by cebe** [comment]
fixed, thanks!
