### ISSUE TITLE
A trouble with formatted date in GridView

### ISSUE THREAD

**Issue by bohdan-vorona** [yiisoft/yii2#9937]
**MySQL:**

![date1](https://cloud.githubusercontent.com/assets/5950639/10538951/c53a80ac-7404-11e5-9669-ca8bd82987dd.jpg)

**My GridView:**

```
...
							[
								'attribute' => 'date_of_creation',
								'format' =>  ['date', 'php:d M Y H:i'],
								'filter' => false,

							],
...
```

**Result from admin panel, view:**

![res1](https://cloud.githubusercontent.com/assets/5950639/10538983/1087059e-7405-11e5-9014-30422325dbc2.jpg)

**PHP:**

```
echo date('d M Y H:i'); => 16 Oct 2015 12:46
```

--------------

**['date', 'php:d M Y H:i']** and **echo date('Y-m-d h:i:s') / the stored date in MySQL** is diffenet.

**Comment by SilverFire** [comment]
This is rather related to timezone config then with Yii2 or GridView. Try this:

```php
var_dump(Yii::$app->db->createCommand('SELECT @@system_time_zone')->queryAll());
var_dump(date_default_timezone_get());
```

**Comment by cebe** [comment]
@bohdan-vorona yii does timezone conversion from database ([assumed as UTC](http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#$defaultTimeZone-detail)) to formatter [timeZone](http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#$timeZone-detail).
You need to configure these to your needs.

**Comment by snickom** [comment]
I have the same problem.

Yii::$app->formatter->timeZone is "Europe/Bratislava"
Yii::$app->formatter->defaultTimeZone is "UTC"
Yii::$app->db->createCommand('SELECT @@system_time_zone')->queryAll()  is "CEST"
date_default_timezone_get() is "UTC"

In mysql db is: 2015-10-20 19:30:38
Select give me: 2015-10-20 19:30:38
Yii::$app->formatter->asDatetime give me: 2015-10-20 19:30:38
In Gridview with format=>'datetime' is: 2015-10-20 19:30:38

Output from Formatter should be 2015-10-20 21:30:38 ... I have the latest stable Yii 2.0.6.
