### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Mirocow** [yiisoft/yii2#9938]
Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.4 -> satisfiable by yiisoft/yii2[2.0.4, 2.0.5, 2.0.6, dev-master, 2.0.x-dev].
```

composer.json

```
{
  "name": "yiisoft/yii2-app-basic",
  "description": "Yii 2 Basic Application Template",
  "keywords": [
    "yii",
    "framework",
    "basic",
    "application template"
  ],
  "homepage": "http://www.yiiframework.com/",
  "type": "project",
  "license": "BSD-3-Clause",
  "support": {
    "issues": "https://github.com/yiisoft/yii2/issues?state=open",
    "forum": "http://www.yiiframework.com/forum/",
    "wiki": "http://www.yiiframework.com/wiki/",
    "irc": "irc://irc.freenode.net/yii",
    "source": "https://github.com/yiisoft/yii2"
  },
  "minimum-stability": "dev",
  "require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": ">=2.0.4",
    "yiisoft/yii2-swiftmailer": "*",
    "yiisoft/yii2-bootstrap": "*",
    "yiisoft/yii2-authclient": "*",
    "yiisoft/yii2-debug": "*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-sphinx": "*",
    "yiisoft/yii2-jui": "*",
    "mirocow/yii2-redactor": "dev-master",
    "mirocow/yii2-user": "dev-master",
    "mirocow/yii2-yandex-maps": "dev-master",
    "mirocow/yii2-file-input-widget": "dev-master",
    "mirocow/yii2-minify-view": "dev-master",
    "mirocow/yii2-scroll-pager": "dev-master",
    "willdurand/geocoder": "@stable",
    "2amigos/yii2-type-ahead-widget": "dev-master",
    "2amigos/yii2-transliterator-helper": "*",
    "2amigos/yii2-taggable-behavior": "*",
    "filsh/yii2-autocomplete": "*",
    "webcreate/jquery-ias": "dev-master",
    "kartik-v/yii2-widgets": "dev-master",
    "kartik-v/yii2-mpdf": "dev-master",
    "kartik-v/yii2-date-range": "dev-master",
    "yiisoft/yii2-redis": "dev-master",
    "ladamalina/yii2-smsc": "*",
    "wartron/yii2-mobiledetect": "*"
  },
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/mirocow/yii2-redactor.git"
    },
    {
      "type": "git",
      "url": "https://github.com/mirocow/mirocow-widgets.git"
    },
    {
      "type": "git",
      "url": "https://github.com/mirocow/yii2-user.git"
    },
    {
      "type": "git",
      "url": "https://github.com/Mirocow/yii2-yandex-maps.git"
    },
    {
      "type": "git",
      "url": "https://github.com/2amigos/yii2-taggable-behavior.git"
    },
    {
      "type": "git",
      "url": "https://github.com/mirocow/yii2-file-input-widget.git"
    },
    {
      "type": "git",
      "url": "https://github.com/ZhandosKz/notification.git"
    },
    {
      "type": "git",
      "url": "https://github.com/thiagotalma/yii2-jstree-widget.git"
    },
    {
      "type": "git",
      "url": "https://github.com/mirocow/yii2-scroll-pager.git"
    },
    {
      "type": "git",
      "url": "https://github.com/Mirocow/yii2-minify-view.git"
    },
    {
      "type": "git",
      "url": "https://github.com/wartron/yii2-mobiledetect.git"
    },
    {
      "type": "git",
      "url": "https://github.com/yiisoft/yii2-redis.git"
    }
  ],
  "require-dev": {
    "yiisoft/yii2-codeception": "*",
    "yiisoft/yii2-debug": "*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-faker": "*"
  },
  "config": {
    "process-timeout": 1800
  },
  "scripts": {
    "post-create-project-cmd": [
      "yii\\composer\\Installer::postCreateProject"
    ]
  },
  "extra": {
    "yii\\composer\\Installer::postCreateProject": {
      "setPermission": [
        {
          "runtime": "0777",
          "web/assets": "0777",
          "yii": "0755"
        }
      ],
      "generateCookieValidationKey": [
        "config/web.php"
      ]
    },
    "asset-installer-paths": {
      "npm-asset-library": "vendor/npm",
      "bower-asset-library": "vendor/bower"
    }
  }
}
```

**Comment by Mirocow** [comment]
i tried yii2 >=2.0.4, 2.0.6, dev-master
result ERROR

**Comment by Mirocow** [comment]
- Updating fxp/composer-asset-plugin (dev-master f84731b => v1.0.3)
    Checking out c2b0406ac19e9ea2d9556987e827d4e7f6924fde

**Comment by SilverFire** [comment]
1) This not a problem in Yii2 core repo
2) @yiisoft/yii2-app-basic contains another [composer.json](https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json) file. Where did you get listed file from?
3) You didn't describe any steps you did prior to get an error.

**Comment by Mirocow** [comment]
but where does yiisoft / yii2-app-basic repository?
this proplem with bower-asset/jquery

**Comment by SilverFire** [comment]
`php composer.phar global require "fxp/composer-asset-plugin:~1.0.3"`
There is a link in my previous post. And please, answer questions I asked there, if you want to get any further help

**Comment by Mirocow** [comment]
yes

Updating fxp/composer-asset-plugin (dev-master f84731b => v1.0.3) Checking out c2b0406ac19e9ea2d9556987e827d4e7f6924fde

**Comment by Mirocow** [comment]
i create the composer.json with config i write it on first topic
and then run composer install

$ composer install
Loading composer repositories with package information                                                                                          Installing dependencies (including require-dev)       Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for 2amigos/yii2-type-ahead-widget dev-master -> satisfiable by 2amigos/yii2-type-ahead-widget[dev-master].
    - 2amigos/yii2-type-ahead-widget dev-master requires bower-asset/typeahead.js ~0.11.0 -> no matching package found.
  Problem 2
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.5 -> satisfiable by yiisoft/yii2[2.0.5, 2.0.6, dev-master, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by SilverFire** [comment]
You have a malformed config. I forgot about some problem with the plugin and gave you wrong command. Please run:
```
php composer.phar global require "fxp/composer-asset-plugin:@dev"
```

Read the installation instructions in https://github.com/yiisoft/yii2-app-basic/ and install basic app - you will be definitely succeed with it.
So I'll say it again this is not a problem of Yii2 core, so welcome to Russian Yii2 support chat https://gitter.im/yiisoft/yii2/rus and feel free to ask there.

**Comment by Mirocow** [comment]
i try composer global require "fxp/composer-asset-plugin" "dev-master"
don`t work

**Comment by Mirocow** [comment]
```
$ composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic
Installing yiisoft/yii2-app-basic (dev-master 96b8989742fd735f99bdd6c0108ea47f6555327f)
  - Installing yiisoft/yii2-app-basic (dev-master master)
    Downloading: 100%

Created project in basic
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.5 -> satisfiable by yiisoft/yii2[2.0.5, 2.0.6, dev-master, 2.0.x-dev].
```

**Comment by SilverFire** [comment]
`composer global require "fxp/composer-asset-plugin:@dev"`

**Comment by Mirocow** [comment]
composer global require "fxp/composer-asset-plugin" "dev-master"
f84731b714c4c8dc090c629b631c1fc7bd235d95 = f84731b714c4c8dc090c629b631c1fc7bd235d95

**Comment by SilverFire** [comment]
`composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic`

**Comment by Mirocow** [comment]
my problem with don`t refreshed ivarement after i install dev version of fxp

**Comment by SilverFire** [comment]
So it's solved?

**Comment by Mirocow** [comment]
i check it

**Comment by SilverFire** [comment]
Можно писать по-русски, если что

**Comment by Mirocow** [comment]
я убил .composer в локальном пользователе затем в другом окне проинсталил fxp и вот как раз в этом и была ошибка, енвайрмент окна в котором работал не обновился, хотя и установлен композер и модуль глобально. бага так сказать

**Comment by Mirocow** [comment]
my problem resolved
thx

**Comment by SilverFire** [comment]
Close this please

**Comment by samdark** [comment]
@SilverFire thanks for helping out to resolve the issue.

**Comment by indicalabs** [comment]
Its still problem 
<code>Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: /var/www/html/myproject/vendor/yiisoft/yii2/authclient/assets</code>

I use 
<code>composer global require --no-progress "fxp/composer-asset-plugin:@dev"; \</code>
and 
<code>"asset-installer-paths":{
			"npm-asset-library":"vendor/npm",
			"bower-asset-library":"vendor/bower"
		}</code>

**Comment by abdulmanan7** [comment]
What i did 
`composer global require --no-progress "fxp/composer-asset-plugin:@dev";`
Then 
Delete vendor folder 
and finally 
`composer install `
my issue has been resolved
