### ISSUE TITLE
Formatter timestamp with ms (int 13)

### ISSUE THREAD

**Issue by EagleMoor** [yiisoft/yii2#9940]
In over system timestamp with ms can write as int(13). If we try formatted with we have error.

Example 
```php
$time = 1445003103605;
echo \Yii::$app->formatter->asDatetime($time); //47760-05-04 09:30:06+0300
echo \Yii::$app->formatter->asDatetime($time / 1000); //2015-10-16 16:45:03+0300
```

Fix it
```php
// yii2/i18n/Formatter.php:646

if (strlen($value) > 10) {
    $value = $value / ('1' . (str_repeat('0', strlen($value) - 10)));
}
```
But I'm not sure that's a good code :)

**Comment by cebe** [comment]
formatter expects a unix timestamp, if you have something else, you have to convert it first. it is not possible to detact that automatically.

**Comment by EagleMoor** [comment]
Unix timestamp can coding just 1445003103605 or 1445003103.605. In php it's 1445003103.605 in node js and android and iOS and in Java it's 1445003103605...
