### ISSUE TITLE
Нет возможности зарегистрировать CSS-файл не в <head>

### ISSUE THREAD

**Issue by shastox** [yiisoft/yii2#9943]
https://github.com/yiisoft/yii2/blob/master/framework/web/View.php#L496

Данная возможность актуальна для SEO-оптимизации сайта, официальная документация веб-мастера Google иногда говорит так делать: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

В данный момент проблема решается только переопределением View.

**Comment by SilverFire** [comment]
@shastox is talking about fixed render position of CSS and proposes to set position for CSS render. The only way to do it now is to override `renderHeadHtml` in custom `View` and register it as a component

**Comment by samdark** [comment]
Спецификация HTML чётко определяет, что внешние стили подключаются исключительно в `head`. По ссылке не нашёл рекомендаций подключать внешние стили как-либо иначе.
