### ISSUE TITLE
Yii::$app->timeZone has no effect on datetime attributes on BeforeSave

### ISSUE THREAD

**Issue by sreenadh** [yiisoft/yii2#9944]
```
public function rules()
    {
        return [
           [['created_date'], 'safe'],
            [['created_date'], 'date', 'format' => "php:d-m-Y h:i A" ],
        ];
    }
```
But Date time is saved in database as "0000-00-00 00:00:00" .

So we need a saveFormat and saveTimeZone for datetime attributes.

saveFormat: 'php:Y-m-d H:i:s'
saveTimezone: 'UTC'

**Comment by cebe** [comment]
> saveFormat: 'php:Y-m-d H:i:s'

http://www.yiiframework.com/doc-2.0/yii-validators-datevalidator.html#$timestampAttributeFormat-detail

> saveTimezone: 'UTC'

http://www.yiiframework.com/doc-2.0/yii-validators-datevalidator.html#$timestampAttributeTimeZone-detail

**Comment by sreenadh** [comment]
@cebe instead of giving saveFormat and saveTimezone in model validation rules can I give it in main.php for all date, datetime and time validators?

**Comment by cebe** [comment]
you may use DI container to set default properties globally but I have not checked if that works.
