### ISSUE TITLE
GROUP_CONCAT has no effect on integer columns

### ISSUE THREAD

**Issue by poliuretano** [yiisoft/yii2#9945]
With 
* Yii 2.0.6 

I have also:
* Xubuntu14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
* Apache Server version: Apache/2.4.7 (Ubuntu) Server built:   Sep 23 2015 15:34:04 
* MySQL Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3 + PHP Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3 

A table like this:

```sql
create table test (
    id int auto_increment,
    name varchar(10),
    birth date,
    money decimal(6,2),
    number int,
    primary key(id)
);

insert into test (name, birth, money, number) values
('marge', '1951-01-01', 1.12,      1),
('marge', '1951-01-01', 12.12,     2),
('marge', '1951-01-01', 123.12,    3),
('marge', '1951-01-01', 1234.12,   4),
('bart', '1979-01-01', 1.12,       2),
('bart', '1979-01-01', 12.12,      3),
('bart', '1979-01-01', 123.12,     4),
('bart', '1979-01-01', 1234.12,    1),
('lisa', '1981-01-01', 1.12,       3),
('lisa', '1981-01-01', 12.12,      4),
('lisa', '1981-01-01', 123.12,     1),
('lisa', '1981-01-01', 1234.12,    2),
('maggie', '1988-01-01', 1.12,     4),
('maggie', '1988-01-01', 12.12,    1),
('maggie', '1988-01-01', 123.12,   2),
('maggie', '1988-01-01', 1234.12,  3),
('homer', '1950-01-01', 1.12,      4),
('homer', '1950-01-01', 12.12,     3),
('homer', '1950-01-01', 123.12,    2),
('homer', '1950-01-01', 1234.12,   1);

```

A model produced by Gii, and a query like:

```php
<?php
$thang = Test::find()->select('GROUP_CONCAT(DISTINCT number) AS number')->one();
```
The resulting object's 'number' field is int(1), and not  string(7) "1,2,3,4"

**Comment by mikehaertl** [comment]
I see two problems with your code here:

1. You use ActiveRecord for the query which is not aproproate here unless you use the technique described [here](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#selecting-extra-fields). You should use the [query builder](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html) or [data access objects](http://www.yiiframework.com/doc-2.0/guide-db-dao.html#executing-sql-queries) instead
2. You seem to use a aggregate function without a `GROUP BY` statement which seems odd to me

**Comment by poliuretano** [comment]
:V, I had a GROPY BY in there, but as you say, the problem is the use of Active Record. It uses the model and the rules, right? Well thanks.

**Comment by samdark** [comment]
@poliuretano issue solved?
