### ISSUE TITLE
TimestampBehavior::value is inconsistent with other behaviors

### ISSUE THREAD

**Issue by mytskine** [yiisoft/yii2#9953]
`TimestampBehavior::getValue()` overrides `AttributeBehavior::getValue()`.
`AttributeBehavior::getValue()` accepts one special type in `$this->value`: if it's not a Closure, the value will be used directly.
`TimestampBehavior::getValue()` accepts one special type in `$this->value`: if it's not an Expression, the value will be used as a callback, unless it's null.

So if one wants to set the timestamp to a fixed value like `$_SERVER['REQUEST_TIME']`, they have to use a closure.
This behavior is not intuitive, leads to unexpressive errors, and is inconsistent with its parent. TimestampBehavior, like its parent, should detect Closure instances and accept constant values.

**Comment by SilverFire** [comment]
The PR #9954 is BC-breaking according to the [report](https://github.com/yiisoft/yii2-framework/commit/ebc8f6aa6ccd1978e5e6483c90f845998f5d7ddd#commitcomment-16013367). This issue is opened for discussion.

The question is should we allow `[$this, 'method']` as a value?
I don't think that is must not be accepted, because `AttributeBehavior` can set an array value to the attribute, therefore array format is ambiguous.

I vote for adding it to `UPGRADE.md`

**Comment by samdark** [comment]
`is_callable` could be used. That would cover both use cases:

```php
return is_callable($this->value) ? call_user_func($this->value, $event) : $this->value;
```

**Comment by SilverFire** [comment]
:+1: I'll do it

**Comment by SilverFire** [comment]
I'm not sure whether it is the best idea, because it might bring unexpected results for the string values, that collide with existing functions in global scope.

**Comment by samdark** [comment]
Right. Then upgrade note should be added. I don't think it was expected to use arrays...

**Comment by emimarz** [comment]
en getValue function on AttributeBehavior file, line 116 this work for me

`return ($this->value instanceof Closure) ? call_user_func($this->value, $event) : (($this->value instanceof Expression)?$this->value:time());
`

**Comment by SilverFire** [comment]
Decided to fix without BC-breaking. Will do

**Comment by SilverFire** [comment]
Fixed: https://github.com/yiisoft/yii2/commit/2e13136ca8003caaeac6d16682d8f2f0e584a46a
UPGRADE notice removed: https://github.com/yiisoft/yii2/commit/5714ae576d97d7a36a36897be14d1a45b0faea9e#diff-52cc367433099653db4ed9f9aafdce80L61
Added a test: https://github.com/yiisoft/yii2/commit/624be05be013a33bcae8761cbc3836293d194e53

**Comment by cebe** [comment]
:+1:
