### ISSUE TITLE
ActiveRecord::findAll() and ActiveRecord::findOne() works wrong in some cases

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#9955]
```php
Model::findOne([
    'some' => 1,
    'some' => 2,
]);
```

works

```php
Model::findOne([
    'and',
    ['some' => 1],
    ['some' => 2],
]);
```

do not works as expected while

```php
Model::deleteAll([
    'and',
    ['some' => 1],
    ['some' => 2],
]);
```

works as expected

Same things for `findAll`. We have serious inconsistency which lead to bugs and long investigations in 2nd cases. For now workaround is to use `findOne/findAll` with hash format conditions only. If fix was impossible by BC reasons such restrictions should be documented in corresponding methods phpDoc.

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2/issues/7888#issuecomment-86786985

**Comment by samdark** [comment]
So it's already in docs. OK.
