### ISSUE TITLE
Suggestion of including select all records at once option in gridview

### ISSUE THREAD

**Issue by bhavuksuthar** [yiisoft/yii2#9957]
Hi guys
I have a suggestion that yii2 gridview checkbox column should have option of select/deselect all records in the gridview,not just the records on the first page but every record in gridview

So that we could easily implement bulk action to all records

if any technique is already implement than include it in the checkbox column docs

thank you

**Comment by samdark** [comment]
It already does that if `multiple` is enabled and `header` is left out from config.

**Comment by bhavuksuthar** [comment]
Do you mean something like this???

            [
                'class' => 'yii\grid\CheckboxColumn',
                'multiple'=>true,
            ],

If yes than it doesnt work,i have 50 records in gridview and i display 20 on one page
so to do the bulk action i can only do 20 at a time,i cant select all 50 at once and do the action.

**Comment by samdark** [comment]
Ah, that's what you mean... select all records in all pages.

**Comment by samdark** [comment]
Yes, that sounds useful.

**Comment by bhavuksuthar** [comment]
Yes, thank you very much

**Comment by usualdesigner** [comment]
It would be good solution to set some hidden input value like that: Form['all'] => 1. There is no good idea to submit all key values because of performance issues.

**Comment by bhavuksuthar** [comment]
Or we can give the option just like gmail.
When user clicks on checkbox in header it will select the record on first page 
and if there are any more records in the grid it will give option to select all

Kartik grid already has feature to select all records but i could not figure out how he did it

**Comment by samdark** [comment]
Won't be implemented in 2.0.
