### ISSUE TITLE
enableAjaxValidation submit activeform directly before clicking the submit button ...

### ISSUE THREAD

**Issue by hitesh2088** [yiisoft/yii2#9958]
I have used activeform and one of the field which I need unique against the database value for which I have kept enableAjaxValidation true but all the fields are getting submit with ajax and there are some field which value suppose to be change before I change it the form gets submit as all field has no error...

How do I suppose to tackle such issue ....

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for bug reports.

**Comment by SilverFire** [comment]
I faced the same problem. Try this solution:

```js
    $('form[data-ajax-submit]').on('submit', function(event) {
        var form = $(this);
        if (event.eventPhase === 2) { // This phase is when the validation is passed
            $.ajax({ // actually the ajax request
                url: form.attr('action'),
                data: form.serialize(),
                type: form.attr('method')
            }); 
        }
        event.preventDefault(); // Prevents default submit behaviour
    });
```

**Comment by hitesh2088** [comment]
Thanks SilverFire  but it is not serving my purpose and Its a kind of bug only... hence I have kept this into issues .... how does it submit directly where I have not clicked on submit there is direct action performed which suppose to handle by the user requirement.

**Comment by SilverFire** [comment]
Can you show your action definition in controller and view code?

**Comment by hitesh2088** [comment]
below is the actrion code 

 public function actionSignupform()
    {
        $counsellor= new Counsellor();
        $model= new SignForm();
        $model->load(Yii::$app->request->post());
             
        $model->validate();
        if($model->hasErrors()) 
       { 
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
       }
        else
      {     
        
            $counsellor->load(Yii::$app->request->post() );
            $counsellor->caption = Yii::$app->request->post()['SignForm']['caption'];
            $counsellor->experties= Yii::$app->request->post()['SignForm']['experties'];
            $counsellor->qualifications= Yii::$app->request->post()['SignForm']['qualifications'];
            $counsellor->registration_number= Yii::$app->request->post()['SignForm']['registration_number'];
            $counsellor->achievements_awards= Yii::$app->request->post()['SignForm']['achievements_awards'];
            $counsellor->association= Yii::$app->request->post()['SignForm']['association'];
            $counsellor->applications= Yii::$app->request->post()['SignForm']['applications'];
            $counsellor->language= Yii::$app->request->post()['SignForm']['language'];
            $counsellor->contributeToWebsiteContent= Yii::$app->request->post()['SignForm']['contributeToWebsiteContent'];
            $counsellor->additionalInfo= Yii::$app->request->post()['SignForm']['additionalInfo'];
            $counsellor->counsellingInvolment= Yii::$app->request->post()['SignForm']['counsellingInvolment'];
        
            $counsellor->save(false);
        
             return $this->goHome();

       }     
    }   

View code is as given below 

<?php 
                       $form =ActiveForm::begin([
    'id' => 'counsellor_form',
    'action'=>Url::to(['/counsellor/profile/signupform']),
    'method'=>'post',
    'enableClientValidation'=>true,
   // 'enableAjaxValidation'=>false,
     'options' => [
        'enctype' => 'multipart/form-data',
       // 'onSubmit'=> 'return false'
        ],
])
                       ?>  
                <div class="container-fluid clearfix margin-top-15">
                    <div class="form-group col-md-6 center-div ">
                        
                        <?= $form->field($model,'caption')->textInput(['placeholder'=>'Add caption e.g. Counsellor, psychologist etc.'])->label(false) ?>
                    </div>
                </div>
                <div class="container-fluid clearfix margin-top-40">
                    <div class="col-md-6 text-left">
                        <div class="form-group ">
                            <label for="name">Name</label>
                            <?= $form->field($model,'name')->textInput(['placeholder'=>'Enter your name'])->label(false)?>
                            
                        </div>
<div class="col-md-6 text-left">
                        <div class="form-group ">
                            <label for="email">Correspondence email</label>
                            <?= $form->field($model,'email',['enableAjaxValidation' => true,])->textInput(['placeholder'=>'Enter your email address'])->label(false); ?>
                        </div>
                    </div>
   <button id="upload" class="btn btn-primary ghost btn-lg">Upload </button>
                             <p>Supported Format: jpg,png,jpeg,gif,pdf,doc,docx</p>
                             
                             <div id="status" class="has-error"></div>
                            <ul id="list" class="margin-top-20 uploaded-file-list"></ul>
 <div>
                        <?= Html::submitButton('Submit now!', ['class'=> 'btn btn-primary btn-lg margin-top-40']) ;?>
                        </div>

**Comment by SilverFire** [comment]
Ouh. It's really hard to read. Could you please wrap your code with [Markdown code tag](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting).

**Comment by hitesh2088** [comment]
I n above form I have some active form field and there is upload file button which will be uploading file with normal ajax way... so as I am completing the form and before upload the file form gets directly submit.

**Comment by hitesh2088** [comment]
below is the action code
```php
public function actionSignupform()
{
$counsellor= new Counsellor();
$model= new SignForm();
$model->load(Yii::$app->request->post());

    $model->validate();
    if($model->hasErrors()) 
   { 
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
   }
    else
  {     

        $counsellor->load(Yii::$app->request->post() );
        $counsellor->caption = Yii::$app->request->post()['SignForm']['caption'];
        $counsellor->experties= Yii::$app->request->post()['SignForm']['experties'];
        $counsellor->qualifications= Yii::$app->request->post()['SignForm']['qualifications'];
        $counsellor->registration_number= Yii::$app->request->post()['SignForm']'registration_number'];
        $counsellor->achievements_awards= Yii::$app->request->post()['SignForm']['achievements_awards'];
        $counsellor->association= Yii::$app->request->post()['SignForm']['association'];
        $counsellor->applications= Yii::$app->request->post()['SignForm']['applications'];
        $counsellor->language= Yii::$app->request->post()['SignForm']['language'];
        $counsellor->contributeToWebsiteContent= Yii::$app->request->post()['SignForm']['contributeToWebsiteContent'];
        $counsellor->additionalInfo= Yii::$app->request->post()['SignForm']['additionalInfo'];
        $counsellor->counsellingInvolment= Yii::$app->request->post()['SignForm']['counsellingInvolment'];

        $counsellor->save(false);

         return $this->goHome();

   }     
}   
```
below is the view code 
```
  <small class="text-muted container-fluid" style="line-height:50px">* Minimum dimension 200 Pixels under 2 MB size</small>
              <?php 
                       $form =ActiveForm::begin([
    'id' => 'counsellor_form',
    'action'=>Url::to(['/counsellor/profile/signupform']),
    'method'=>'post',
    'enableClientValidation'=>true,
   // 'enableAjaxValidation'=>false,
     'options' => [
        'enctype' => 'multipart/form-data',
       // 'onSubmit'=> 'return false'
        ],
])
                       ?>  
                <div class="container-fluid clearfix margin-top-15">
                    <div class="form-group col-md-6 center-div ">
                        <!--input type="text" class="form-control" name="caption" id="caption" placeholder="Add caption e.g. Counsellor, psychologist etc." aria-required="true" aria-describedby="caption-error"-->
                        <?= $form->field($model,'caption')->textInput(['placeholder'=>'Add caption e.g. Counsellor, psychologist etc.'])->label(false) ?>
                    </div>
                </div>
                <div class="container-fluid clearfix margin-top-40">
                    <div class="col-md-6 text-left">
                        <div class="form-group ">
                            <label for="name">Name</label>
                            <?= $form->field($model,'name')->textInput(['placeholder'=>'Enter your name'])->label(false)?>
                            <!--input type="text" id="name" name="name" class="form-control" placeholder="Enter your name" aria-required="true" aria-describedby="name-error" aria-invalid="true"-->
                        </div>
  <button id="upload" class="btn btn-primary ghost btn-lg">Upload </button>
                             <p>Supported Format: jpg,png,jpeg,gif,pdf,doc,docx</p>
                             <!--<div id="upload" ><span class="btn btn-primary ghost btn-lg">Upload</span></div>-->
                             <div id="status" class="has-error"></div>
                            <ul id="list" class="margin-top-20 uploaded-file-list"></ul>
                        <?= Html::submitButton('Submit now!', ['class'=> 'btn btn-primary btn-lg margin-top-40']) ;?>

```

**Comment by SilverFire** [comment]
You have incorrect action. Usually we use HTTP POST request to submit and HTTP AJAX POST to validate. In your case, you use ajax post request for both, so you are not determining what's going on in controller action. You have to separate validate and create actions

Uncomment this:
```
'enableAjaxValidation'=>false,
```
and add this
```
'validationUrl'          => Url::toRoute(['validate-form']),
```

Make your actions look like this:

```php
    public function actionCreate()
    {
        $model = new Model();
        $model->load(Yii::$app->request->post());

        if ($model->save()) {
            return $this->goHome();
        }
    }

    public function actionValidateForm() {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $model = new Model();
        $model->load(Yii::$app->request->post());
        return ActiveForm::validate($model);
    }
```

And your code with
```
$counsellor->caption = ...
```
is very weird.

**Comment by hitesh2088** [comment]
I know its weird but I need to submit different post data into different database table hence I did it in that way ... do u have any better suggestion for that.

**Comment by SilverFire** [comment]
Does this example work?

**Comment by hitesh2088** [comment]
No ... Its project

**Comment by SilverFire** [comment]
I'm talking about my example of code with separated validator and crate action

**Comment by hitesh2088** [comment]
yeah ... actully I was doing validation in post_action and checking for errors so the form used to get submit directly .. so as you said I seperated the validation action and post action so it worked... only get submit on clicking on submit.
