### ISSUE TITLE
getAttribute() and setAttribute() through getter/setter why not?

### ISSUE THREAD

**Issue by ivan-chkv** [yiisoft/yii2#9959]
Why __get(), __set(), getAttribute() and setAttribute() methods of BaseActiveRecord class has no ability to get or set a value through a getter/setter like it implemented in __get() and __set() methods of Component class?

It could looks like it:
```
class ActiveRecord extends BaseActiveRecord

    public function __get($name)
    {
        $getter = 'get' . $name;
        if ($this->hasAttribute($name) && method_exists($this, $getter)) {
            // read property, e.g. getName()
            return $this->$getter();
        } else {
            return parent::__get($name);
        }
    }

    public function getAttribute($name)
    {
        $getter = 'get' . $name;
        if (method_exists($this, $getter)) {
            // read property, e.g. getName()
            return $this->$getter();
        } else {
            return parent::getAttribute($name);
        }
    }
```

And it would give ability to do some attribute processing in lazy mode.

**Comment by SilverFire** [comment]
I think it's bad idea because it will bring inconsistency with `attributes()` method.
Otherwise you should collect all your getters/setters to `_attributes` array, but is not what you always need.
