### ISSUE TITLE
Put Site Offline

### ISSUE THREAD

**Issue by MrAwanishKumar** [yiisoft/yii2#9960]
Hi,

I am working on a website, developing in Yii2 framework. Sometimes need to put the site offline for maintenence, so I just configure the catchAll feature and specified in my frontend/config/main.php file
e.g 
'catchAll' => ['site/offline'],
here offline is a view file containing the site maintenance message. 
Now I want to do this dynamically, but can not figure out how? Need help.

Thanks 
Awanish Kumar

**Comment by samdark** [comment]
Try doing it in bootstrap.

**Comment by MrAwanishKumar** [comment]
How? did not understand. Can you please explain with example?

Thanks

**Comment by samdark** [comment]
https://stackoverflow.com/questions/27450447/yii2-dynamic-maintenance-mode

**Comment by MrAwanishKumar** [comment]
I have gone through this link http://www.yiiframework.com/doc-2.0/guide-structure-applications.html and trying to implement the same. But could not achieve that.
Still trying.......

**Comment by cebe** [comment]
its better to have maintainance mode at webserver level, what if you need to change some php code in maintainance mode, the maintainance site may be affected if it is served by php.
