### ISSUE TITLE
Pjax and List view pagination issues

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#9961]
I have a controller which have 2 action as follows:

```php
class PostController extends Controller
{
    public function actionView($id)
    {
        // contains codes to create active data provider and pass it to my view
    }

    public function actionComment()
    {
        // contains codes to get post data and save it to database and return or throw exception as needed
        // the return is as follows
        return $this->runAction('view', ['id => $comment->postId]);
    }
}
```

in my view file i have a list view that list some posts with pagination. the listview widget is inside a Pjax.

The view contains a form to add a new post and the Pjax use **'formSelector'** to listen to it.

When the form is submitted, the listview is updated, but the pagination urls are broken.
An example of a url is:
http://localhost/post/view?page=2&per-page=25

There is no id in the url as you can see above. The correct url should have been something like:
http://localhost/post/view/**{id}**?page=2&per-page=25
or
http://localhost/post/view?**{id=id}**&page=2&per-page=25
or
http://localhost/post/**{id}**?page=2&per-page=25

depending on url rules.

**Comment by samdark** [comment]
What's form action?

**Comment by Locustv2** [comment]
The form is posting to /post/comment, and the actionComment just create a new record in db then return as said in the above example

**Comment by samdark** [comment]
I wonder why it's accessing post/view if you're using comment action only...

**Comment by Locustv2** [comment]
It's a list view that contains all comments on a post/view page.
So when you comment it should do it via ajax so i am using pjax to do this.
When the user add a new comment the list view of coomments should be updated so i am returning the view action..

I also copied the contents of the view action and pasted in the comment action and then i return $this->render('view', [params]); and i still get the error

**Comment by samdark** [comment]
Well, it seems you're doing something wrong in the code that's not posted here. Anyway, it seems to be too general to be considered as a bug report. It's better to ask for help at forums in this case.

**Comment by Locustv2** [comment]
So after going through docs, i noticed: http://www.yiiframework.com/doc-2.0/yii-data-pagination.html#$params-detail

Parameters (name => value) that should be used to obtain the current page number and to create new pagination URLs. If not set, all parameters from $_GET will be used instead.

the params take `$_GET` and when you are in the situation that i am, `$_GET` does not contain the id as i am calling `$this->runAction()` and passing parameters directly.

So i had to modify my as follows: 

```php
public function actionView($id)
{
    ...
    $dataProvider = new ActiveDataProvicer([
        ...
        'pagination' => [
                'pageSize' => 25,
                'params' => array_merge($_GET, ['id' => $id]),
            ],
        ]);
    ...
}
```

Maybe this should be integrated with yii so we can use $this->runAction() with an action of Pjax.
