### ISSUE TITLE
ActiveQuery while next performance optimization

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#9962]
I have a console action, which does select some thousand DB entries. Then it does a simple foreach through them. The problem is, that it consumes some GB of memory. I've done it then via `asArray` which improved the memory consumption heavy. The problem then was, that I need the record as a object.

I've optimized it to this:
```php
$simpleArray = SimpleObject::find()->asArray()->all();
foreach ($simpleArray as $simpleObjectArray) {
	$simpleObject = SimpleObject::instantiate($simpleObjectArray);
	SimpleObject::populateRecord($simpleObject, $simpleObjectArray);
	$simpleObject->afterFind();
	// fancy things...
}
```

So, here's my question: Is there a way to do something like a "while next"?
It was a bit tricky to find out how to populate the record, that it behaves afterwards like it would normally.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#retrieving-data-in-batches-

**Comment by thejahweh** [comment]
thanks @klimov-paul that's what I wanted to do, but this gives me now the next problem:

```
Error: SQLSTATE[IMSSP]: There are no more rows in the active result set.
Since this result set is not scrollable, no more data may be retrieved.
```

This is a MSSQL error, but I just don't know where the real problem is.
