### ISSUE TITLE
some links down

### ISSUE THREAD

**Issue by juans0524** [yiisoft/yii2#9963]
Some links in the spanish guide are not working fine.

**Comment by samdark** [comment]
Which ones?

**Comment by samdark** [comment]
And how are you reading it? Via GitHub?

**Comment by juans0524** [comment]
this link are down and others https://github.com/yiisoft/yii2/blob/master/docs/guide-es/input-multiple-models.md

**Comment by juans0524** [comment]
@samdark sr. from the subject "working with databases" the links are down in the guide-es folder.

**Comment by samdark** [comment]
Well, it's not translated yet.

**Comment by pana1990** [comment]
@juans0524 las traducciones en español no están actualizadas, te recomiendo que sigas la guía en inglés o actualices tu mismo las traducciones.

Un saludo.
