### ISSUE TITLE
Migrations should standardize the "CASCADE" "RESTRICT" actions (i.e. SQL Server)

### ISSUE THREAD

**Issue by tsdogs** [yiisoft/yii2#9964]
When using a migration that was created for mysql in a sql server, the "RESTRICT" keyword should be converted to "NO ACTION"

now, wouldn't it be more appropriate to have some constants or so that are taken by the database ($this->db->RESTRICT, or something like that?)

**Comment by samdark** [comment]
Why "RESTRICT" keyword should be converted to "NO ACTION"?

**Comment by tsdogs** [comment]
'cause RESTRICT in SQL SERVER is not supported, and the "NO ACTION" does what RESTRICT does on other databases (mysql)

https://technet.microsoft.com/en-us/library/aa902684%28v=sql.80%29.aspx

**Comment by samdark** [comment]
What a nice naming :)

**Comment by thejahweh** [comment]
I've done a fix for that problem, but its more like a ugly workaround. This should be done like the type-map.

**Comment by samdark** [comment]
Won't be implemented in 2.0.
