### ISSUE TITLE
Automatically clear Session table in database

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#9965]
Is there any workaround to automatically clear session table mentioned on this page: 

http://www.yiiframework.com/doc-2.0/guide-runtime-sessions-cookies.html 

It's becoming huger and huger by the time.

**Comment by cebe** [comment]
There is an expiry time in the table, which should be automatically cause the Entry to be removed. Do you have expiry times that are far in the past but still stored in the table?

**Comment by klimov-paul** [comment]
Closed since there is no response from the author.

**Comment by egorsmkv** [comment]
Good answer about this topic: https://stackoverflow.com/a/34310472/5707560
