### ISSUE TITLE
Relational AR joinWith produces both a join and lazy-load request

### ISSUE THREAD

**Issue by soulhunter1987** [yiisoft/yii2#9969]
When using joinWith() to join a hasOne relation - a join query is performed and lazy-loading query (SELECT .... WHERE key IN (....)) is also executed.

class SomeModel has a relation:
```php
public function getSrcUser()
{
    return $this->hasOne(User::className(), ['name' => 'src']);
}
```
creating a search query like this:
```php
$query = SomeModel::find();
$query->joinWith('srcUser')->select('some_model.*, user.callerid');
```

When accessing $SomeModel->srcUser - lazy-loading query is executed, which is not expected.

Using YII 2.0.7-dev

**Comment by samdark** [comment]
It's expected.

**Comment by soulhunter1987** [comment]
Эм, а как избежать этого? Зачем тогда нужен join, если все равно будет выполнен ленивый запрос?

**Comment by samdark** [comment]
Это не ленивый запрос. Отличается от ленивого он тем, что на выборку 100 записей со связанными будет сделано два запроса, а не 200. join нужен для фильтрации данных.
