### ISSUE TITLE
public getter for view params that checks for isset and has default value

### ISSUE THREAD

**Issue by Renkas** [yiisoft/yii2#9976]
I have used view->params array to pass some global values to layout and/or other views. But I'm not really happy about checking to see if the array key exists in every case. I think this could/should be a functionality in framework. Maybe in a `getParam` method in View object?

For example I have used these constructs in many places:
`isset($this->params['sidebar-search']['q']) ? $this->params['sidebar-search']['q'] : null`

But I think something like this would be much better:
`$this->getParam('sidebar-search.q', null)`

`null` in this case is to demonstrate a method signature and would be default and could be omitted in real world use case.

**Comment by samdark** [comment]
`ArrayHelper::getValue()`

**Comment by Renkas** [comment]
Seems reasonable.
