### ISSUE TITLE
Множественное число для русского языка не работает

### ISSUE THREAD

**Issue by alexk984** [yiisoft/yii2#9977]
Берем строку 

    Yii::t('app', '{n, plural, =0{часов} =1{час} one{час} few{часа} many{часов}}', ['n' => 2]);

Она не работает, `ошибка Message pattern is invalid: msgfmt_create: message formatter creation failed: U_DEFAULT_KEYWORD_MISSING`. Однако если добавляем 

    Yii::t('app', '{n, plural, =0{часов} =1{час} one{час} few{часа} many{часов} other{ошибка!!}}', ['n' => 2])

То видим на выходе `ошибка` хотя должно браться из раздела `few`. Проверял много раз.

**Comment by samdark** [comment]
Версии intl/ICU какие?

**Comment by alexk984** [comment]
version	1.1.0
ICU version	52.1
ICU Data version	52.1

**Comment by SilverFire** [comment]
Воспроизводится.


```php
foreach ([0,1,2,3,5,12] as $i) {
   echo Yii::t('app', '{0, plural, one{# час} few{# часа} many{# часов(many)} other{# часов(other)}}', $i) . "<br />";
}
```

```
0 часов(other)
1 час
2 часов(other)
3 часов(other)
5 часов(other)
12 часов(other)
```

```
PHP 5.6.4-4ubuntu6.3 (cli) (built: Sep 29 2015 12:44:47)

Internationalization support => enabled
version => 1.1.0
ICU version => 52.1
ICU Data version => 52.1
```

**Comment by SilverFire** [comment]
A strange thing: https://3v4l.org/GKmfq
The same code on local gives me `2 часов(other)` :confused:

**Comment by LAV45** [comment]
Можете подсказать как установить ICU старше 4.8 версии если в завимостях php5-intl наглуха прописана libicu48 (>= 4.8-1).
```
~ $ aptitude show php5-intl
Пакет: php5-intl                                 
Состояние: установлен
Автоматически установлен: нет
Версия: 5.6.14-1~dotdeb+7.1
Приоритет: необязательный
Раздел: php
Сопровождающий: Guillaume Plessis <gui@dotdeb.org>
Архитектура: amd64
Размер в распакованном виде: 456 k
Зависимости: libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libicu48 (>= 4.8-1), phpapi-20131226, php5-common (= 5.6.14-1~dotdeb+7.1), ucf
Пред-зависимости: dpkg (>= 1.15.7.2~)
Конфликтует: php5-idn, php5-idn, php5-intl
Заменяет: php5-idn, php5-idn
Предоставляет: php5-idn
Описание: internationalisation module for php5
 This package provides a module to ease internationalisation of PHP scripts. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development
 and can be embedded into HTML.
Сайт: http://www.php.net/

~ $ aptitude search icu | grep ^i
i   libbasicusageenvironment0       - multimedia RTSP streaming library (BasicUs
i   libharfbuzz-icu0                - OpenType text shaping engine ICU backend  
i A libicu48                        - International Components for Unicode      
i   libicu52                        - компоненты интернационализации для Unicode
i   python3-icu                     - Python 3 extension wrapping the ICU C++ AP
i   python3-pyicu                   - dummy transitional package for PyICU Pytho

~ $ php -i | grep ICU
ICU version => 4.8.1.1
ICU Data version => 4.8.1
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by SilverFire** [comment]
@LAV45 В зависимостях сказано, что требуется ICU версии старше или равной `>= 4.8-1`
Можно попробовать поставить libicu52 и посмотреть, подхватит ли. Возможно менеджер пакетов разрешит удалить libicu48 после установки libicu52. Если нет - можно скомпилировать php5-intl

**Comment by LAV45** [comment]
Подсказали тут http://yiiframework.ru/forum/viewtopic.php?t=22716#p135719 )) 
```
~ $ aptitude remove libicu48
~ $ aptitude install libicu-dev php5-dev
~ $ pecl install intl
~ $ php5enmod intl
~ $ service php5-fpm restart
```

**Comment by alexk984** [comment]
version	PECL-3.0.0
ICU version	52.1
ICU Data version	52.1

вот такие версии показывает после этих процедур однако работает также

**Comment by LAV45** [comment]
2 часов(other)
3 часов(other)

@SilverFire , а почему часов если должно быть 2 часа ?

Запустил и по их примеру http://icu-project.org/apiref/icu4j/com/ibm/icu/text/PluralFormat.html но выводит результат не совсем корректно.

**Comment by samdark** [comment]
https://stackoverflow.com/questions/25750106/make-it-work-icu-php-intl-mnemonic-tag-few-for-pluralization-formatting

**Comment by samdark** [comment]
Попортили правила в версии 52.1. [В 4.8.1](http://source.icu-project.org/repos/icu/icu/tags/release-4-8-1/source/data/misc/plurals.txt) было:

```
 set10{
            few{"n mod 10 in 2..4 and n mod 100 not in 12..14"}
            many{"n mod 10 is 0 or n mod 10 in 5..9 or n mod 100 in 11..14"}
            one{"n mod 10 is 1 and n mod 100 is not 11"}
        }
```

[В 52.1](http://source.icu-project.org/repos/icu/icu/tags/release-52-1/source/data/misc/plurals.txt) стало:

```
 set34{
            many{
                "v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100"
                " = 11..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …"
            }
            one{
                "v = 0 and i % 10 = 1 and i % 100 != 11 @integer 1, 21, 31, 41, 51, 6"
                "1, 71, 81, 101, 1001, …"
            }
            other{
                " @integer 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, 1002, … @decimal"
                " 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …"
            }
        }
```

[В 53.1](http://source.icu-project.org/repos/icu/icu/tags/release-53-1/source/data/misc/plurals.txt) пофиксили:

```
set29{
            few{
                "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 3"
                "2~34, 42~44, 52~54, 62, 102, 1002, …"
            }
            many{
                "v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100"
                " = 11..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …"
            }
            one{
                "v = 0 and i % 10 = 1 and i % 100 != 11 @integer 1, 21, 31, 41, 51, 6"
                "1, 71, 81, 101, 1001, …"
            }
            other{
                "   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000"
                ".0, …"
            }
        }
```

**Comment by samdark** [comment]
То есть надо обновляться.

**Comment by LAV45** [comment]
@samdark 
https://github.com/yiisoft/yii2/blob/master/framework/requirements/requirements.php#L67
Может тогда добавить как рекомендуемую версию для использования?!

**Comment by samdark** [comment]
Это проблема одного конкретного языка в одной конкретной версии данных.

**Comment by samdark** [comment]
Можно в перевод гайда по i18n включить в виде заметки.

**Comment by LAV45** [comment]
@SilverFire , ЗЫ
```
~ $ php -i | grep ICU
ICU version => 55.1
ICU Data version => 55.1
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```php
        foreach ([0,1,2,3,5,12] as $i) {
            echo Yii::t('app', '{0, plural, one{# hour} other{# hours}}', $i) . "<br />";
        }
```
frontend/messages/ru/app.php
```
return [
    '{0, plural, one{# hour} other{# hours}}' => '{0, plural, one{# час} few{# часа} many{# часов(many)} other{# часов(other)}}',
];
```

0 часов(many)
1 час
2 часа
3 часа
5 часов(many)
12 часов(many)

**Comment by SilverFire** [comment]
@LAV45 так все в порядке, вроде?

**Comment by samdark** [comment]
Ну да. Это про то, что апдейт помог. Я открыл чтобы в русскоязычной доке поправить.

**Comment by antonmarin** [comment]
Повторяется в версии ICU 50.1.2
```
composer show lib-icu --platform

name     : lib-ICU
descrip. : The intl PHP library
keywords : 
versions : * 50.1.2
type     : library
source   : []  
dist     : []  
names    : lib-icu
```

**Comment by SilverFire** [comment]
Обновляйтесь до 53.1+

**Comment by Valsym** [comment]
У меня 
ICU version => 68.2
ICU Data version => 68.2
ICU Unicode version => 13.0
few - не работает, показывает вместо неё other.

`Yii::t('app', '{n,plural,=0{нет отзывов} one{# отзыв} few{# отзыва} many{# отзывов} other{# отзывов}}', ['n' => 2], 'ru-RU')`

2 отзывов

**Comment by samdark** [comment]
Поставьте себе локально https://github.com/samdark/intl-icu-data-tables и посмотрите этим приложением правила. Вероятно, что-то не так с ICU Data. Но это не точно.
