### ISSUE TITLE
LinkPager: DropDown to choose number of listed rows

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2#9979]
The pager works fine. However, I miss an UI element to easily change the number of listed elements. A DropDown would be ideal, with options for e.g. 20, 50, 100,... elements (should be configurable). This would set the 'per-page' parameter.

Would you like to enhance the LinkPager with this? 
(Only if you're not too busy.)

**Comment by samdark** [comment]
Not really. Usually it's fine to have fixed size and this additional element clutters UI.
