### ISSUE TITLE
config/main.php: array_replace_recursive instead of array_merge?

### ISSUE THREAD

**Issue by dguhl** [yiisoft/yii2#9982]
Hello there.

Doing my work with Yii2, I programmed a service component which needs combined parameters of params.php and params-local.php as well. For instance, I never commit credentials; instead I distribute them manually by local configurations which are not part of the repo.

I saw you wrote a helper method for that problem but it only applies to main.php and main-local.php respectively. The parameter files are not merged by that method, instead, the currently used method "array_merge" completely replace first-level keys in an array with another. 

The native PHP function array_replace_recursive does the same like your helper, except that integer keys are not appended to the result array, but replace their same-keyed counterpart. For the params, I use array_replace_recursive, and from the last to the first array, the parameters are recursively replaced by their key or created. Beside the name of that method, you get a merged parameter array in the intended order of priority.

I suggest to use the method array_replace_recursive for parameters by default. Since this change is so little to do, I did not start a debate in your forums - which, by the way, inexplicaby lack of a GitHub registration &/ login method ;)

**Comment by samdark** [comment]
Could you provide use case when array_merge isn't OK?

**Comment by klimov-paul** [comment]
Duplicates #4021

**Comment by dguhl** [comment]
@samdark 

params.php
```php
<?php
return [
    'test' => [
        'beverages' => [
            'apple juice',
            'banana juice'
        ]
    ];
];
```
params-local.php
```php
<?php
return [
    'test' => [
        'credit-cards-supported' => [
            'amex',
            'visa',
            'mastercard'
        ]
    ];
];
```

With ```array_merge``` you get the following array:
```php
[
    'test' => [
        'credit-cards-supported' => [
            'amex',
            'visa',
            'mastercard'
        ]
    ];
];
```

With ```array_replace_recursive``` you'd get this:

```php
[
    'test' => [
        'beverages' => [
            'apple juice',
            'banana juice'
        ],
        'credit-cards-supported' => [
            'amex',
            'visa',
            'mastercard'
        ]
    ];
];
```

array_merge requires you to repeat default params configuration in your local, array_replace_recursive doesn't.

**Comment by samdark** [comment]
It depends very much on the project. It could be that `array_merge` is desired. Since it's template, you may adjust it as you need.

**Comment by dguhl** [comment]
Well, thanks for considering anyway.
