### ISSUE TITLE
RBAC unserialize issue

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#9986]
Hello everybody! Have issue with RBAC unserialize. I'm trying to check permission access but getting error "Rule not found : isAuthor". All actions i did step by step as in manual. I'll be grateful for any help!
![login2](https://cloud.githubusercontent.com/assets/4490762/10648153/8ce8d0ce-7845-11e5-897b-2ec7dfb12207.png)
![login3](https://cloud.githubusercontent.com/assets/4490762/10648196/b9ffba50-7845-11e5-82c5-044c0e0f4b97.png)

**Comment by samdark** [comment]
Do you have rule class?

**Comment by RSalo** [comment]
@samdark yes, i do.
```php
namespace app\rbac;

use yii\rbac\Item;
use yii\rbac\Rule;


class AuthorRule extends Rule
{
    public $name = 'isAuthor';

    public function execute($user, $item, $params)
    {
        return isset($params['post']) ? $params['post']->createdBy == $user : false;
    }
}
```
But maybe i doing something wrong?

**Comment by samdark** [comment]
Doesn't seem so. Looks weird.

**Comment by RSalo** [comment]
I hope, this information have to help solved my problem:
Data from auth_rule table:
```
name : isAuthor
data : O:19:"app\rbac\AuthorRule":3:{s:4:"name";s:8:"isAuthor";s:9:"createdAt";i:1444865585;s:9:"updatedAt";i:1444865585;}
created_at : 1444865585
updated_at : 1444865585
```
Yii 2.0.5
PHP 5.6.1 (cli)
Loaded extensions:
```
Core
ctype
curl
date
dom
ereg
fileinfo
filter
hash
iconv
imap
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
zlib
```

**Comment by SilverFire** [comment]
Could you try to change the serialized data in DB rules table to this: `\app\rbac\AuthorRule` (i added `\` at the beggining of the class name)

**Comment by RSalo** [comment]
@SilverFire i added in DB "\" and right now get error
![login4](https://cloud.githubusercontent.com/assets/4490762/10672457/0ce20df0-78f9-11e5-94d5-0f17e83df409.png)

**Comment by duynguyen0511** [comment]
can you post

* your controller code that check rbac permission
* your rule code and where its location
* dump content of your auth_assignment, auth_item, auth_item_child and auth_rule table
* steps you took to create the rule and assign it to a permission

on Gist ( https://gist.github.com/ )

**Comment by RSalo** [comment]
@duynguyen0511 yes of course https://gist.github.com/RSalo/1b97b52f1ccc011a63e7

**Comment by duynguyen0511** [comment]
your AuthorRule class use "namespace app\rbac", but you place it under "/config/rbac/"

you can

1. change the namespace to config/rbac

or 

2. move AuthorRule.php under "/rbac" if you use simple template or under "/front/rbac" or "backend/rbac" if you use advance template

The point is your namespace must match the file location or Yii2 cant auto-load your AuthorRule class

**Comment by RSalo** [comment]
@duynguyen0511 changed https://gist.github.com/RSalo/cf545b689f996aa33dcb
and have the same error
https://cloud.githubusercontent.com/assets/4490762/10672457/0ce20df0-78f9-11e5-94d5-0f17e83df409.png

**Comment by duynguyen0511** [comment]
would you remove your rule and re-add them again ?

e.g. remove entry in auth_rule (the rule itself), remove entry in auth_item (permission that use the rule)

Then, create new rule, then add it to permission .

It should work.

**Comment by RSalo** [comment]
@duynguyen0511 no i don't it. one moment, i remove all tables and will create a new

**Comment by RSalo** [comment]
Probably, i found where is problem.
In AuthorRule we have namespace "app\rbac\AuthorRule" that = "/srv/www/htdocs/shelter/config/rbac/AuthorRule.php", but yii in vendor have other path to my rule at the same namespace "/srv/www/htdocs/shelter/rbac/AuthorRule.php".
![login5](https://cloud.githubusercontent.com/assets/4490762/10711941/c3ad0436-7a93-11e5-8bb1-73d1bee25096.png)

I see only one path - hard write correct  "@app" alias in config. Or have you other ways to solved it issue?

**Comment by SilverFire** [comment]
You're wrong.
`@app` alias points to `/src/www/htdocs/shelter/`, so 
`app\rbac\AuthorRule` namespace points to the `/src/www/htdocs/shelter/rbac/AuthorRule.php`

If you want to rule the file in the config directory, change its namespace to `app\config\rbac\AuthorRule`.

Is it clear for you?
