### ISSUE TITLE
Submit Button with Formaction does not work in Activeform with client script

### ISSUE THREAD

**Issue by chris68** [yiisoft/yii2#9989]
When I use the client script in an active form a formaction is no longer executed. The form will just be submitted normally. If I disable the client script it works smoothly.
```
<?php ActiveForm::begin([
    'enableClientValidation' => false, // it's not related to client validation
    'enableClientScript' => true, // but related to yii.activeForm.js]); ?>
        <button type="submit" formaction="delete" formmethod="post" >Delete</button>
<?php ActiveForm::end(); ?>

```
Bug similar to https://github.com/yiisoft/yii2/issues/8015

**Comment by samdark** [comment]
Have you tried with code from master?

**Comment by chris68** [comment]
No. Using 2.06, but checked that no bug fixing commits occurred in between. I am not using ajax here so this should not be related (https://github.com/yiisoft/yii2/commit/17e2255472a2b1a30fb1ce42a8937793214bbc46)

It used to work before the summer and I could assume  https://github.com/yiisoft/yii2/commit/1d6a340534a79fe2ce79db82abbf653a3c39cd7e introduced the error.

**Comment by SilverFire** [comment]
Verified

**Comment by AnatolyRugalev** [comment]
I can handle it with same manner as in #11410

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/fa5baf32756a8193a380a8cf43251983bb16b221
