### ISSUE TITLE
Possible security issue with REST exceptions

### ISSUE THREAD

**Issue by scottbeacher** [yiisoft/yii2#9990]
When exceptions are thrown using the framework as a REST API there is a 'type' property returned in the json which is the namespace of the exception that was thrown. This path gives away information that the framework being used is Yii. For example, calling an endpoint that doesn't exist returns a 404 error the following JSON:

    {
        "name": "Not Found",
        "message": "Page not found.",
        "code": 0,
        "status": 404,
        "type": "yii\web\NotFoundHttpException"
    }

While not specifically a security hole, someone looking for vulnerabilities in the server now can assume based on that path the sever is using Yii and plan their attack with this head start.

Is there a specific reason this information is returned? Or is there a specific way to toggle it off? Perhaps this information should only be returned if YII_DEBUG is true?

My temporary fix (not thoroughly tested) for this is to change my config to the following:

    'response' => [
        'format' => yii\web\Response::FORMAT_JSON,
        'on beforeSend' => function($event) {
            $response = $event->sender;
            if ($response->data !== null && $response->isSuccessful === false) {
                unset($response->data['type']);
            }
        }
    ],

Which works but doesn't seem like the best solution due to it running on every response.

**Comment by samdark** [comment]
There are tons of ways one could determine the framework used is Yii: CSRF meta, forms, scripts etc. I don't think it's a security issue since security through obscurity doesn't work anyway.

**Comment by thejahweh** [comment]
This information is only returned if `YII_DEBUG` is true. I would not recommend to use the debug mode on a productive server.

**Comment by samdark** [comment]
Oh, YII_DEBUG is absolutely no go for production.
