### ISSUE TITLE
Not working - UrlManager rule having parameter with dash

### ISSUE THREAD

**Issue by summerknight** [yiisoft/yii2#9999]
I use Yii2 advanced template, Linux OS, Google Chrome browser.

On my page I'm using [yii\data\Pagination](http://www.yiiframework.com/doc-2.0/yii-data-pagination.html) object for pagination.

It is necessary to set pageSize, so:
```php
        $pagination = new Pagination(['totalCount' => $vuz->count(), 'pageSize' => 9,]);
```

View code:
```php
        echo LinkPager::widget([
            'pagination' => $pagination,
        ]);
```

Config part related to `UrlManager` is such:
```php
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'showScriptName' => false,
            'enablePrettyUrl' => true,
            'rules' => array(
                'search-vuz' => 'site/search-vuz',

                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ),
        ],
```

When I click on pagination links an end of  URL looks like this: `/frontend/web/search-vuz?page=2&per-page=9`

It is necessary to have a such URL end: `/frontend/web/search-vuz/2/9`

So I add additional rules:
```php
            'rules' => array(
                 'search-vuz/<page:\d+>/<per-page>' => 'site/search-vuz', // added
                 'search-vuz/<page:\d+>' => 'site/search-vuz', //added
                'search-vuz' => 'site/search-vuz',

                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ),
```
Again I try pagination links and get such URL `/frontend/web/search-vuz/1?per-page=9`
`per-page` is still here.
Everything is working If I change `pageSize` parameter name like this:
```php
        $pagination = new Pagination(['totalCount' => $vuz->count(), 'pageSize' => 9,
            'pageSizeParam' => 'n'
        ]);
```
And rule like this:
```php
'search-vuz/<page:\d+>/<n>' => 'site/search-vuz', 
```

So the question is - how to use parameters with dashed name in urlManager rule.

Doesn't work:
```php
'search-vuz/<page:\d+>/<per\-page>' => 'site/search-vuz',
```

**Comment by SilverFire** [comment]
Reproduced.

In [UrlRule.php:170](https://github.com/yiisoft/yii2/blob/master/framework/web/UrlRule.php#L170) regexp `\w` is too strict and causes incorrect rule parsing.

![screenshot from 2015-10-26 12 53 31](https://cloud.githubusercontent.com/assets/4499203/10727188/98352a24-7be0-11e5-96b8-b888bf307a67.png)

**Comment by cebe** [comment]
@SilverFire thanks for finding the cause, could you fix it and send a PR?

**Comment by SilverFire** [comment]
In [UrlRule.php:238](https://github.com/yiisoft/yii2/blob/master/framework/web/UrlRule.php#L238) you will get the following call:

```php
preg_match("#^search-vuz/(?P<page>\d+)/(?P<per-page>[^\/]+)$#u", 'search-vuz/2/3', $matches);
```

PHP does not allow to use `-` in named groups for regexp: https://3v4l.org/NWC2g.
@cebe I don't know, how to fix it easily.

**Comment by SilverFire** [comment]
Also it's not working with [alternative named group syntax](http://php.net/manual/en/function.preg-match.php#refsect1-function.preg-match-changelog):

```php
preg_match("#^search-vuz/(?<page>\d+)/(?<per-page>[^\/]+)$#u", 'search-vuz/2/3', $matches);
preg_match("#^search-vuz/(?'page'\d+)/(?'per-page'>[^\/]+)$#u", 'search-vuz/2/3', $matches);
```

Both of lines caused `Compilation failed: syntax error in subpattern name`

We can replace group name with placeholder and then restore it. It will be something like this:
```php
$tr3 = ['d495b570' => 'page', 'b2ce9e4a' => 'per-page'];
preg_match("#^search-vuz/(?P<d495b570>\d+)/(?P<b2ce9e4a>[^\/]+)$#u", 'search-vuz/2/3', $matches);
foreach ($matches as $key => $match) {
    if (isset($tr3[$key]) {
        $matches[$tr3[$key]] = $match;
        unset($matches[$key]);
    }
}
```

**Comment by samdark** [comment]
Yes, that's an option. I'd go for it.

**Comment by samdark** [comment]
It could make routing a bit slower though...

**Comment by samdark** [comment]
@SilverFire is handling it.

**Comment by ServerDotBiz** [comment]
I have similar problems using hyphens in my URL. The URL manager contains the following rule: post/<slug:[\w\-]+> , going to /post/slug-value-1 works as expected but when I try to create a URL linking to this page using Html::a('view post', ['post', 'slug' => $model['slug']]) it fails when there is more than 1 hypen/dash in the url. As slug with value "slug-1" works, but "slug-value-1" fails. I have tried different regular expressions, the route works fine but creating the url fails.

**Comment by ServerDotBiz** [comment]
I have similar problems using hyphens in my URL. The URL manager contains the following rule: post/<slug:[\w\-]+> , going to /post/slug-value-1 works as expected but when I try to create a URL linking to this page using Html::a('view post', ['post', 'slug' => $model['slug']]) it fails when there is more than 1 hypen/dash in the url. As slug with value "slug-1" works, but "slug-value-1" fails. I have tried different regular expressions, the route works fine but creating the url fails.

**Comment by SilverFire** [comment]
@ServerDotBiz please create a separate issue
